{1}{1}29.970
{1}{108}Ta Mu mu pøinese mnoho problémù.
{128}{248}Sworde, víš proè jsem se nikdy neoenil?
{265}{385}Nemùeme se ukrıt pøed svımi osudy.
{608}{728}Neuspìli jsme, protoe|jsme podcenili jejich schopnosti.
{810}{923}Obzvláštì Hrdinu.
{923}{1003}Jsem šastnı, e jsme stále na ivu.
{1003}{1123}Pøeji si vrátit se do Japonska.
{1299}{1419}Mu.
{2208}{2328}Toto je tvoje.
{2350}{2470}Dìkuji.
{3254}{3292}Šéfe, zavíráte obchod?
{3292}{3412}Ano, u se opozdívá.
{4572}{4643}Pøišel jsem se na tebe podívat.
{4643}{4763}Jak jsi vìdìl, e jsem tady?
{4781}{4831}Co tvoje zranìní?
{4831}{4951}Je to mnohem lepší.
{5899}{5977}Kde je tvá ena?
{5977}{6045}Spí.
{6045}{6136}Proè mi to dìláte?
{6136}{6256}Slyšela jsem, e hrajete na flétnu.|Stıská se ti po domovì?
{6897}{7013}Ty nejsi hrdina. Je to pøevlek.
{7013}{7101}Udìlal jsem to ze zoufalství.
{7101}{7183}Ty víš, jak moc tì miluji.
{7183}{7255}Proè mì nemùeš pøijmout?
{7255}{7375}Dnes se tì zmocním, a se stane cokoliv.
{7375}{7417}Co to dìláš?
{7417}{7537}Ještì jeden krok a zabiju se.
{7618}{7736}Proè jeho? Proè Hrdinu Hua?
{7736}{7837}Je jenom Èíòan|a ák Pıchy.
{7837}{7880}Proè sis vybrala jeho?
{7880}{7976}Nejsi jako on.
{7976}{8096}Zítra se vracíme do Japonska.|My nejsme tak drzí jako ty.
{8788}{8857}Poté, co Hrdina opustil dùl, se vdy zajímal
{8857}{8925}o to, jaká je situace v|Steel Bull Canyonu.
{8925}{8982}Rozhodli jsme se najít Bogota.
{8982}{9053}Upøímnì, nebojíme se toho.
{9053}{9173}Ninjové hledají Mistra Pıchu.
{9370}{9490}My chceme jen informaci|o Steel Bull Canyonu.
{9547}{9651}Všichni jsme Èíòané,|musíme si navzájem pomáhat.
{9651}{9771}Prosím, dejte mi vìdìt, jestli |mohu nìco udìlat.
{9951}{10071}Snìz nìjaké.
{10279}{10399}Je to dobré?
{10452}{10516}Co se dìje?
{10516}{10551}Bolest.
{10551}{10582}Dítì pøichází.
{10582}{10632}Rychle, zavolej porodní bábu.
{10632}{10681}Já pùjdu.
{10681}{10801}Já ti pomùu. Buï opatrnı.
{11037}{11157}Paní Huaová, relaxujte. Nebojte se.
{11415}{11450}Kde je Hrdina?
{11450}{11557}Hrdino? Jdu se po nìm podívat.
{11557}{11677}Vy chlapy, pryè, pryè.
{11725}{11845}Paní Huaová, relaxujete.
{12202}{12258}- Hrdino, pøišel jsi právì v èas.|- Co se dìje?
{12258}{12361}Jade rodí.
{12361}{12481}Gratuluji.
{12552}{12656}Tlaète. Tlaète silnìji.
{12656}{12776}Hrdino, ještì tam nemùeš jít. |Poèkej zde.
{12837}{12917}Dítì je tady, dítì je tady.
{12917}{12958}Je to chlapec, nebo dívka?
{12958}{13078}Chlapec by byl lepší, nemyslíš?
{13092}{13194}Hrdino, jsi opìt otcem.
{13194}{13314}Dvojèata. Úasné.
{13477}{13517}Je to v poøádku. Nebojte se.
{13517}{13612}- Jsi v poøádku? Mohu nìjak pomoci?|- Ne.
{13612}{13648}Neboj.
{13648}{13734}Ne! Hoøí!
{13734}{13797}Západní køídlo.
{13797}{13917}Gratuluji, Paní Huaová.|Máte dvojèata.
{13967}{14017}Jade.
{14017}{14088}Chlapce a dìvèe.
{14088}{14172}Oheò! Všichni vstaòte. |Utíkejte pryè.
{14172}{14257}Neberete si své vìci. |Utíkejte pryè!
{14257}{14377}Tam hoøí!|Musíme rychle odejít.
{14414}{14534}Pane Hua, tohle je vaše dcera.
{14536}{14656}Paní Huaová pøišla o mnoho krve.
{14747}{14846}Jade, neboj se, budeš v poøádku.
{14846}{14902}Oheò se blíí.
{14902}{14979}Porodní bábo, vezmi dítì a utíkej.
{14979}{15099}Hrdino, vezmi svoji enu. Rychle.
{15104}{15224}Shengu.
{15386}{15497}Rychle.
{15497}{15560}- Jade.|- Hrdino.
{15560}{15669}Vypadnìte.
{15669}{15728}Dej mi ji.
{15728}{15787}- Co to dìláš?|- Nepøibliuj se ke mnì.
{15787}{15858}- Co chceš?|- A ty.
{15858}{15924}Pøibli se a zabiju ji.
{15924}{16044}Ne! Ona je má dcera. |Vra mi ji
{16048}{16168}Polo to dítì.
{16182}{16302}Zachraò naši dceru, Hrdino.
{17237}{17292}S tím ohnìm.
{17292}{17412}Chci, aby Hrdina a|Èínskı dùm navdy zmizeli!
{17413}{17533}Vìdìl jsem, e jsi to byl ty.
{18790}{18910}Jade! Jade!
{19012}{19091}Hrdino, naše dcera...
{19091}{19211}Neboj se. Zachráním ji.
{19252}{19372}Pamatuj si, e strávíme|pøíští Vánoce s našimi dìtmi.
{19487}{19538}Hrdino!
{19538}{19658}Vìø mi.
{20209}{20311}Budeme v poøádku.
{20311}{20431}Dítì je v poøádku.
{21824}{21883}To je Hrdina! Vychází ven.
{21883}{22003}Co je to, Hrdino?
{22591}{22711}Jade!
{22792}{22903}Jade!
{22903}{22994}Jade!
{22994}{23077}Jade!
{23077}{23178}Jade!
{23178}{23298}Jade!
{23397}{23517}Jade!
{24082}{24148}Jade!
{24148}{24257}Jade!
{24257}{24377}Slíbil jsem zachránit naši dceru.
{25757}{25848}Tento starı mu je vìštec.
{25848}{25927}Jeho jméno je Ming.
{25927}{25979}Co øekl Hrdinovi?
{25979}{26099}Ovlivnil Hrdinu po zbytek jeho ivota.
{26203}{26323}Hvìzda smrti øídí tvùj ivot.
{26542}{26636}Tvá mapa narození|je jiná ne u ostatních.
{26636}{26742}Kdy jsi se narodil, smrt byla ve vzduchu.
{26742}{26829}Do tvıch 18 byl ivot obyèejnı.
{26829}{26902}Po 18 se to zmìnilo, tví rodièe ještì ili
{26902}{27022}Pozdìji umøeli nepøirozenou|smrtí, e?
{27138}{27258}Byl jsi pøedurèen bıt sám|a bez dìtí.
{27312}{27432}Tví pøátele a rodina|brzy dojdou ke špatnému konci.
{27610}{27730}Protoe jsi se narodil|pod hvìzdou smrti.
{27858}{27942}Pøestoe má ena zemøela,
{27942}{28050}dala ivot dvojèatùm.
{28050}{28099}Kdy se opìt shledáme?
{28099}{28185}- Nemìl bys.|- Proè ne?
{28185}{28301}Ty a tvá dcera máte zkøíené znaky.
{28301}{28398}Nemùete spoleènì pøeít.
{28398}{28518}Má víra je v mıch rukách,|já najdu cestu.
{28586}{28706}Pokud døív nezemøeš.
{29352}{29472}"Jade, odpoèívej zde v pokoji."
{30168}{30288}Shengu, pøines Sworda zpìt do naší vlasti.
{30389}{30448}A ty?
{30448}{30568}Já musím nìco sledovat|spolu se Stínem.
{30886}{31006}Hrdino, ty opravdu vìøíš,|e jsi hvìzda smrti?
{31482}{31550}Hrdina šel se mnou do Japonska.
{31550}{31670}Èasem nadešel Mistrùv souboj.
{31889}{31962}Bratr, Nepøemoitelnı,|je fanatik do bojovıch umìní.
{31962}{32020}Dosáhnutí posledního tajemství |v bojovém umìní China Secret
{32020}{32139}byl dùvod, proè tito dva bratøi spolu bojovali.
{32139}{32211}Tehdy jsme nevìdìli|o poáru v Èínském domì,
{32211}{32287}kterı zpùsobil Jin.
{32287}{32407}Nicménì Hrdina bude chtít|urèitì pomstu.
{32470}{32590}Èínské tajemství je esencí|naší školy šermu.
{32677}{32797}Mistr øekl, e jej nás všechny nauèí.
{32857}{32938}Dokonce i pøesto, e jsi starší ák.
{32938}{33042}Ty nejsi jenom student.
{33042}{33162}Vìøím, e uchráníš Èínské tajemství
{33172}{33292}pøed Neporazitelnım.|Vrátil jsem se do Japonska,
{33342}{33462}abych byl jmenován|Mistrem našeho spolku.
{33469}{33552}A abych pøedal Èínské tajemství.
{33552}{33619}Naše pravidla praví,
{33619}{33739}e Èínské tajemství musí bıt|v drení mistra našeho spolku.
{33748}{33868}Take tvá ádost je zmítnuta.
{33920}{34017}Odmítám tvé zvolení Mistrem.
{34017}{34137}Ty dokonce nejsi ani Japonec.
{36594}{36642}Mistøe.
{36642}{36762}Neporazitelnı,|tvùj šerm je pouze prùmìrnı.
{36849}{36927}Víš, proè jsi byl poraen?
{36927}{37017}Je to proto, e máš zmatek ve svém srdci.
{37017}{37137}Jdi domù, buï dobrı manel a otec.
{37211}{37286}Nejsi skuteènı bojovník.
{37286}{37362}Katanaka Fuji, znovu se utkáme.
{37362}{37482}Není to potøeba.|Je zøejmé, kdo dnes vyhrál.
{37489}{37577}Jdi a trénuj.
{37577}{37697}Nesmím s tebou bojovat,|ale moji áci mohou.
{38725}{38845}Mistøe.
{39027}{39147}Hrdino, tvùj osud dorazil.
{39159}{39279}Chystám se ti pøedat Èínské tajemství.
{39779}{39899}Nepøemoitelnı je pøíliš fanatickı|ve snaze dosáhnout vyšší moc.
{39917}{40009}Odmítám mu pøedat Èínské tajemství.
{40009}{40129}Ano, Mistøe.
{40151}{40271}Mistøe.
{41880}{41996}Ano, náš Mistr odešel.
{41996}{42116}Do mìdíce zemøel na vnitøní zranìní.
{42143}{42255}Hrdina opravdu vìøil,|e je Hvìzdou smrti.
{42255}{42368}Cítil, e Mistr zemøel kvùli nìmu.
{42368}{42418}Proto se beze slov vytratil.
{42418}{42509}Èínské tajemství si vzal s sebou.
{42509}{42594}Neslyšel jsem o nìm od doby,
{42594}{42642}kdy jsem se vrátil do Ameriky.
{42642}{42741}Našel nìkoho, kdo si mì vzal,
{42741}{42789}a mìl jsem dceru.
{42789}{42909}Nedokáu si pøedstavit,|e se opìt setkám se synem Hrdiny
{42986}{43093}Kadı, všichni z Èínského domu.
{43093}{43213}Pokusíme se udìlat vše, abychom našli Hrdinu.
{43271}{43391}Jak se cítíš|po vyslechnutí všech tìch pøíbìhù?
{43421}{43541}Chci se teï mnohem víc setkat s otcem.
{43561}{43606}Zítra je festival luceren.
{43606}{43700}To je velmi vıznamnı svátek |pro Èíòany ijící v cizinì
{43700}{43820}Myslím na útrapy našich krajanù.
{43824}{43887}Dìlníku v Steel Bull Canyonu.
{43887}{43941}Luohan od tamtud utekl.
{43941}{44027}On ví hodnì o Steel Bull Canyonu.
{44027}{44108}Chci sjednotit sílu Èínského domu.
{44108}{44215}A v plíit se zítra do Canyonu.
{44215}{44301}Zachránit je.
{44301}{44377}Doruèil jsi ty buchty?
{44377}{44497}Ano.
{45766}{45886}Co je to za opièárnu?
{45887}{46007}Èínská opera.
{46096}{46208}Èínské eny, kung fu.
{46208}{46328}Kung fu? Zdá se mi to jako kravina!
{46885}{47005}"Dávejte pozor na znamení bìhem Opery."
{47190}{47310}Sworde, ten mu vypadá povìdomì.
{47422}{47534}Pamatuju. To je Bigot, mu|kterı unesl tvoji sestru!
{47534}{47654}Pokraèuj.
{49909}{50029}Do vozù.
{50416}{50536}Rychle, do vozù.
{51373}{51493}Kde je má malá sestra?
{51527}{51642}Jaká sestra? Nerozumím.
{51642}{51762}Sworde, on je ten zrádce,|kterı zradil všechny Èíòany!
{51893}{51977}Stále pouíváš meè?
{51977}{52097}Bìloši a já|jsem zabili tvé prarodièe.
{52151}{52271}Jsem pøedurèen zabít|3 generace Huau.
{52377}{52477}Hrdina.
{52477}{52516}Kde je má dcera?
{52516}{52636}Hrdina Hua, kde jsi byl?
{52643}{52718}Jen jsem si hrál.
{52718}{52789}Brzo na tomto místì pøevezmu vedení.
{52789}{52882}Pokud se mnou budeš spolupracovat,|nebudeš mít jen jednu dívku.
{52882}{53002}Mùeš mít tucet dívek!
{53630}{53750}Luohane.
{53783}{53903}Hrdino, po tolika letech|se opìt potkáváme.
{54030}{54150}Nemluv.
{54208}{54327}Hrdino.
{54327}{54447}Luohane.
{55959}{56079}Otèe.
{57409}{57529}Otèe.
{57648}{57768}Strıèek Sheng o tobì hodnì mluvil.
{57848}{57968}Na mùj návrat, Luohane, Stíne.
{58006}{58126}A kadı o tobì mluvil velmi dobøe.
{58182}{58302}Mám o tobì dostateènì silnou pøedstavu.
{58364}{58484}Ale pøi setkání s tebou|jsi naprostı opak.
{58496}{58616}Jsi zklamanı?
{58618}{58699}Co jsem udìlal špatnì?
{58699}{58812}Ztratil jsem tebe a tvoji matku pøi porodu.
{58812}{58932}Jsem závistivı,|kdy vidím jiné dìti.
{58945}{59064}Mají rodièe, kteøí je milují.
{59064}{59184}Mnohokrát jsem snil o tobì a o matce.
{59217}{59337}Opravdu bych se s vámi obìma chtìl shledat.
{59867}{59985}Sworde.
{59985}{60105}Proè mì nechceš pøijmout?
{60132}{60252}Promiò, narodil jsem se|pod hvìzdou Smrti.
{60285}{60405}Všichni v mém okolí|špatnì skonèí.
{60413}{60533}Já tomu nevìøím,|a ani ty bys nemìl.
{60833}{60953}Kdy sníš, jak vypadá matka?
{60998}{61118}Je milá. Je nádherná.
{61276}{61396}Vypadá jako obrázek?
{61581}{61701}Vyfotil jsem se s tvojí matkou|pøedtím, ne jsi se narodil.
{61756}{61876}Nechej si ji.
{62115}{62235}Vyrostl jsi.
{62270}{62350}Otèe, otèe!
{62350}{62470}Otèe...
{63119}{63239}Po takové dobì,|proè mì stále sleduješ?
{64096}{64216}Nikdy jsem nesplnil tvé pøání.
{64452}{64572}Vím, e nikdy nezapomeneš na svoji enu.
{64589}{64706}Ale pokud víš, jak je bolestivé nìkoho ztratit,
{64706}{64826}mìl bys vìdìt, jak se cítím posledních 16 let.
{65009}{65100}Pøišel jsem ti øíct.
{65100}{65220}Mùj Mistr a jeho áci|pøišli do Ameriky,
{65244}{65364}aby s tebou bojovali.
{66948}{67068}Hrdino Hua!
{67811}{67921}Neporazitelnı, tohle je èínskı ètvr. |Zadr!
{67921}{68021}Øeknìte tomu zbabìlci Hrdinovi,|aby ukázal svùj oblièej.
{68021}{68065}Hrdina Hua pøed mìsícem odešel.
{68065}{68185}Nevrátí se.
{68198}{68318}Èínskı dùm nebude mít klid,|dokud se nevrátí.
{68411}{68531}Pojïme ho porazit.
{69728}{69848}Neomezenı oceán!
{70586}{70706}Hrdina Hua, koneènì jsi dorazil.
{70751}{70840}Bratr Hua.
{70840}{70960}Nechci zranit nevinné lidi.|Pojïme.
{70976}{71056}Dobrá.
{71056}{71176}Otèe.
{71269}{71347}Rudı Meè.
{71347}{71467}Starı pøíteli, byla to dlouhá doba.
{71574}{71680}Otèe.
{71680}{71800}Dnešní bitva není jen o|èest jména mistra Pıchy.
{71836}{71956}Je o cti všech Èíòanù.
{72128}{72248}Otèe, musíš vyhrát.
{72377}{72481}Musí se ukázat vítìz v dnešní bitvì?
{72481}{72601}Ano. Èekal jsem na tento zápas|dlouhou dobu.
{73034}{73127}Neporazitelnı, odmítl jsem vidìt svého syna.
{73127}{73231}Proto jsem mohl cvièit Èínské tajemství,|které mì Mistr nauèil.
{73231}{73351}Proto s tebou neprohraji.
{74499}{74609}Pro tento duel jsem se oslepil.
{74609}{74671}Zabil jsem svoji enu a dítì.
{74671}{74751}Teï mì u nic nemùe rozptılit.
{74751}{74861}A proto si myslíš, e vyhraješ?
{74861}{74981}Pøemıšlel jsi nìkdy|o tom, proè chceš vyhrát?
{76749}{76869}Hrdino Hua, jsi pøedurèenı se mnou prohrát.
{78237}{78357}Starı pøíteli.
{78367}{78487}Èínské tajemství.
{79388}{79508}Neporazitelnı, opovrhuješ láskou,|proto jsi prohrál.
{81293}{81342}- Nashle.|- Postarejte se o sebe.
{81342}{81381}Dìkuji.
{81381}{81501}- Postarejte se o sebe.|- Sbohem.
{82168}{82288}Sbohem.
{82300}{82500}*** Pøeloil Bluedog ***|http://www.treehouse.cz/titulky/