{1}{1}29.970
{200}{300}Pro asijskou sekci PLsubtemu|pøeloil Bluedog
{310}{410}Korekci s velkou dávkou trpìlivosti|provedl Meo 
{1616}{1680}Narodil jsem se pod Hvìzdou Smrti.
{1680}{1800}Byl jsem pøedurèen zùstat navdy sám.
{4961}{5031}Divné, e na jihu snìí.
{5031}{5123}Je to jako opera,|létající mráz v èervnu.
{5123}{5243}Pospìš si, tvùj otec tì hledá.
{5379}{5491}My Èíòané víme, jak respektovat naše uèitele.
{5491}{5576}Mistr Pıcha je nejnadanìjší|a nejèestnìjší.
{5576}{5696}Máme to štìstí, e tì moná |pøijme jako svého áka.
{5739}{5840}Ano, pane.
{5840}{5960}Dej mu to.
{5967}{6023}Je zima. Obleè si kabát.
{6023}{6143}Dìkuji, matko.
{6173}{6263}Tento Rudı meè je dìdictví mé rodiny.
{6263}{6317}Teï ho pøedávám tobì. |Vezmi si jej.
{6317}{6437}A buï úspìšnı v trénincích|se svım mistrem.
{7184}{7303}Kam si myslíš, e jdeš?
{7303}{7423}Já ti ukáu.
{7487}{7607}Stop, vzdávám se.
{7727}{7779}Dnes ráno jsem se podívala z okna.
{7779}{7826}Vše bylo bílo.
{7826}{7916}Nikdy pøedtím jsem to nevidìla.|Tak krásné.
{7916}{8022}Má matka si myslí, e je to podivné.
{8022}{8091}Sníh v èervnu není dobré znamení.
{8091}{8154}Taky se mi to zdá podivné.
{8154}{8216}Mistøe!
{8216}{8259}Shengu, buï opatrnı s mım meèem!
{8259}{8379}Je to rodinné dìdictví.
{8396}{8516}Hrdino.
{8539}{8577}Bratøe Stíne.
{8577}{8697}Neøíkej mi bratøe,|dokud tì Mister nepøijme.
{8725}{8845}Co tím myslel?
{9982}{10028}Mistøe.
{10028}{10148}Dobøe, Hrdino. Vedl sis dobøe.
{10161}{10277}Pøijímám tì jako svého áka.
{10277}{10361}A se vrátíme z Japonska,
{10361}{10436}nauèím tì 'Èínské tajemství'.
{10436}{10483}Dìkuji, Mistøe.
{10483}{10531}Já...
{10531}{10648}Shengu, potøebuješ talent,|aby jsi se mohl nauèit bojovım umìním.
{10648}{10767}Nejsi talentovanı,|ale pokud budeš tvrdì pracovat...
{10767}{10854}Uspìješ, budeš-li více cvièit.
{10854}{10974}Dìkuji, Mistøe. Dìkuji.
{11307}{11427}Wangu!
{11656}{11757}Otèe.
{11757}{11806}Otèe.
{11806}{11900}"Zaslouíš si to."
{11900}{11988}Zaplatil za své slova.
{11988}{12108}Matko.
{12182}{12269}Matko.
{12269}{12369}Tvùj otec napsal do novin...
{12369}{12419}Zlodìj
{12419}{12491}...a spoleèenskıch nemocech|zpùsobené cizinci prodávající opium
{12491}{12611}Za to ho zabili.
{12647}{12767}Vrah je z Obchodní spoleènosti.
{12821}{12912}Matko!
{12912}{13032}Matko. Matko.
{13090}{13186}Matko.
{13186}{13306}Matko.
{13703}{13802}Pane Petere, víte,
{13802}{13877}jak øíkáme tìmto kvìtinkám?
{13877}{13989}Slepice. Kvok, kvok.
{13989}{14032}Špatnì. Ony jsou Moøské dívky.
{14032}{14152}Proè? Protoe to znamená,|e jsou hezké.
{14235}{14301}Víte, proè jsem tak úspìšnı|ve vedení tohoto místa?
{14301}{14384}Je to proto, e pouívám Èíòany|pro ovládnutí Èíòanù.
{14384}{14446}Jste jen spolek zbabìlcù.
{14446}{14566}To je vše.|Musím se jít vymoèit.
{15538}{15658}Kdo je to? Vypadni odsuï!
{15840}{15960}Jdi do pekla.
{16191}{16311}Co se dìje? Kdo jsi?
{17181}{17301}Hrdina.
{17326}{17439}Jsi v poøádku?
{17439}{17559}Právì jsem nìkoho zabil.
{17621}{17721}Budeš v poøádku.
{17721}{17841}Nechci tì ztratit.
{17934}{18054}Já navdy budu s tebou.
{18084}{18204}Jade.
{18713}{18833}Zavøi oèi, a nìco si pøej.
{19215}{19261}Co se stalo?
{19261}{19330}Obdrel jsem tvé pøání.
{19330}{19401}- Mé pøání...|- Neøíkej ho,
{19401}{19521}nebo se nevyplní.
{20456}{20566}Jedno po druhém.
{20566}{20595}Tvé jméno?
{20595}{20715}Hrdina Hua.
{20716}{20836}Tvùj otisk palce zde.
{20851}{20953}Rychle na loï. |Za chvíli odjídíme.
{20953}{21073}Je èas jet.
{21829}{21925}Hrdino.
{21925}{22031}Hrdino.
{22031}{22151}Hrdino.
{22801}{22852}Po 20 dnech na moøi,
{22852}{22965}jsem koneènì v Americe.
{22965}{23085}Myslím si, e tohle musí bıt Socha svobody.
{23109}{23229}Jak to mùeš vìdìt?
{23236}{23311}Nevidìl jsi mì kadı den èíst?
{23311}{23367}Pøeèetl jsem o Americe všechno.
{23367}{23444}Ty jsi tu byl, ale já ne, strıèku.
{23444}{23564}Tvá matka si myslela,|e je to Èínská bohynì milosrdenství.
{23600}{23663}Najdu otce?
{23663}{23696}Uvidíme.
{23696}{23816}Pojedeme do|Èínského domu v èínské ètvrti.
{24466}{24579}Opatrnì.
{24579}{24699}Tomuto se øíká auto.|Nechovej se jako vesnickı balík.
{24931}{25031}Strıèku, nevìdìl jsem,|e bìloši umí Lví tanec.
{25031}{25097}Nikdo z tìchto lidí není bìloch.
{25097}{25217}Ti Lví taneènicí jsou všichni Èíòané.
{25289}{25368}Èínskı dùm je pøed námi.
{25368}{25488}Tvá matka a já jsme tu zùstali,|kdy jsme sem pøišli.
{25706}{25799}Jak to, e si to nepamatuju?
{25799}{25919}V té dobì jsi ještì nebyl naivu, hlupáku.
{25936}{26056}Ale je jisté,|e se to tu za ty roky zmìnilo.
{26773}{26864}Šastnı novı rok, gentlemani.
{26864}{26984}Budete chtít jídlo nebo pokoj?
{27002}{27122}Plánujeme tu zùstat,|ale potøebujeme vaši pomoc.
{27198}{27301}Všichni jsme bratøi z cizí zemì.
{27301}{27421}Všichni jsme Èíòané.|Ptejte se na cokoli.
{27438}{27503}Pokud máte problémy,
{27503}{27621}my z Èínského domu|udìláme vše, abychom vám pomohli.
{27621}{27675}Dìkuji.
{27675}{27710}Zajímalo by mì, jestli...
{27710}{27830}zdejší šéf je stále mu|s krátkımi vlasy?
{27897}{27990}U ne. Teï je tu novı šéf.
{27990}{28110}Vede venku Lví tanec.
{28437}{28524}Dobøí mui Èíny, spojeni v srdci,
{28524}{28644}všemi ètyømi moøi
{28822}{28942}Velcí Hrdinové v èase, spolu v odvaze,|ve všech osmi zemích
{29126}{29246}Pohnìte se! Zmiz mi z cesty!
{29726}{29846}Dobøe, zbij ho.
{30150}{30234}Co se dìje?
{30234}{30312}- Co se dìje?|- Poèkejte!
{30312}{30432}Dnes je èínskı novı rok.|Nechci to tvım lidem kazit.
{30434}{30488}Teï.. kde je ten posranı mnich?
{30488}{30580}Co jsi to øekl?
{30580}{30661}Já jsem šéf Èínského domu.|Jak vám mùu pomoci?
{30661}{30752}Jsi docela dobrı. Rád bych si to s tebou|nìkdy rozdal, jeden na jednoho. Kdykoli.
{30841}{30958}Vím, e je tady.|Tohle je mu, kterého hledám!
{30958}{31020}Toto je penzion a restaurace.
{31020}{31140}Chcete mnicha,|tak to byste mìli jít do chrámu.
{31141}{31232}Vy Èíòané vdy kryjete zadek ostatním.
{31232}{31307}Vím, e se skrıvá uvnitø.
{31307}{31427}Teï pro nìj pùjdu.
{31431}{31518}My Èíòané jsme zdvoøilí lidé dbající zákona.
{31518}{31606}Pokud chceš vstoupit, tak se mnou nejdøív bojuj.
{31606}{31701}Jestli vyhraješ, prosím, mùeš jít dál.
{31701}{31821}Jak vy Èíòané øíkáte:|"Vaše slova vaše èest."
{31821}{31941}Divocí konì nemohou vzít zpìt|gentlemanova slova.
{32271}{32391}Skvìlı boj!
{33190}{33279}Všichni, dnes je èínskı Novı rok.
{33279}{33343}Nedovolte, aby nám bìloši zkazili naši náladu.
{33343}{33463}Pøeji všem dobrı osud.|Rozdejte rudé sáèky.
{33591}{33630}Dìkuji, šéfe.
{33630}{33731}Mladı mui, ty jsi tu novı?
{33731}{33795}Ano. Dnes jsem dorazil.
{33795}{33872}Váš zrak je dokonce lepší|ne vaše bojové umìní.
{33872}{33954}Není zde mnoho Èíòanù.|Musíme bıt spojeni.
{33954}{33991}S kım jsi pøišel?
{33991}{34097}S mım strıèkem, strıèek Sheng.
{34097}{34217}Sworde, tohle je starı pøítel tvého otce,|mnich Luohan.
{34278}{34328}Znáte Luohana?
{34328}{34372}Ano, pane.
{34372}{34466}Zajímalo by mì,|neslyšel jste nìkdy o mui...
{34466}{34539}- Pokraèujte.|- Hrdina Hua.
{34539}{34588}Hrdina Hua?
{34588}{34691}Já jsem Sword Hua. |Hrdina je mùj otec.
{34691}{34778}Nikdy jsem se s ním nesetkal,|ale hodnì jsem o nìm slyšel.
{34778}{34831}A Luohan?
{34831}{34951}Pojïte se mnou.
{35006}{35060}Ty jsi Hrdinùv syn?
{35060}{35121}Strıèku Luohane.
{35121}{35241}Meèi. Vypadáš jako on.|Máš jeho oèi.
{35327}{35430}Víš, kde je mùj otec?
{35430}{35550}Hledám ho u|více jak deset let.
{35741}{35861}"Rok 1914."
{36060}{36180} Opustil jsem Èínu, tak jako tvùj otec,|pøed 16ti lety.
{36211}{36323}Více jak sto lidí|namaèkáno do jedné malé lodi.
{36323}{36443}Naprosto bez svobody.
{36630}{36750}Je tu nìjaká voda? Umíráme ízní.|Dejte nám nìjakou vodu.
{36806}{36869}Je tam nìkdo?
{36869}{36948}Kvùli èemu tak hulákáte?
{36948}{37068}Nechte nás se projít.|Je tu pøíliš horko.
{37077}{37138}Je zde horko, pøíliš horko.
{37268}{37373}Velitel s námi nejednal jako s lidmi.
{37373}{37493}Lili nám naše jídlo|a vodu z vrchu.
{37511}{37631}Nemìli jsme jinou monost,|ne sbírat jídlo ze zemì.
{37912}{38000}Tvùj otec a já jsme jedli velmi málo.
{38000}{38078}Byl jsem zvyklı na hlad.
{38078}{38153}Ale poté, co všichni usnuli,|tvùj otec
{38153}{38267}sbíral zrníèka rıe ze zemì.
{38267}{38307}Byl neuvìøitelnı.
{38307}{38412}Dokázal sesbírat|více jak polovinu misky.
{38412}{38532}A nìkdy dokonce i bílkoviny.
{39528}{39608}Vy jste nejedl v tìchto dnech.
{39608}{39686}Nezabiju.
{39686}{39806}Je to jenom bílá rıe.
{39864}{39984}Snìdl jsem šváby.
{40049}{40152}Pamatuju si, e jsme byli na lodi 37 dnù.
{40152}{40212}Protoe s kadım vıchodem slunce a západem
{40212}{40332}jsem udìlal na palubì znaèku.
{42121}{42241}Kdy jsme pøistáli,|byli jsme vyšetøeni a odvšiveni.
{42250}{42370}Cítil jsem, e jsme ménì ne prasata nebo psy.
{42734}{42823}Po všech fyzickıch vyšetøení a registraci
{42823}{42943}byla naše skupina nahnaná na náklaïák.
{42960}{43070}Nevìdìli jsme, kam nás odváejí.
{43070}{43190}Vìdìl jsem, e to mùe bıt cesta bez návratu.
{43399}{43519}Koneènì jsme byli dopraveni do dolu|se jménem Steel Bull Canyon.
{43531}{43651}Do práce.
{43787}{43846}Øekni mu, aby dìlal rychle.
{43846}{43933}Rychle, pospìšte si.
{43933}{44005}ivot dìlníka byl krutı.
{44005}{44117}Majitel se nezajímal,|zdali jsme iví, èi mrtví.
{44117}{44202}Nìkteøí lidé omdleli vyèerpáním.
{44202}{44260}Ale nevzali je k doktorovi.
{44260}{44380}Odnesli je do pouštì|a tam je ponechali smrti.
{44384}{44471}Tak jsme si zvykli nestìovat si,|kdy jsme byli nemocní.
{44471}{44528}Moje pøátelství s tvım otcem
{44528}{44648}zaèalo bìhem té doby.
{44656}{44776}Vıplata! Rychle, vıplata!
{44859}{44892}- Jméno?|- Luohan.
{44892}{45012}Tvùj otisk prstu zde.
{45049}{45077}Dìkuji.
{45077}{45197}Hrdina Hua.
{45301}{45412}Hrdino, mùj maneli,|byl jsi pryè více jak 2 mìsíce.
{45412}{45477}Moc mi chybíš.
{45477}{45560}To ráno,|Sheng a já, jsme se hnali na molo.
{45560}{45629}Ale ty u jsi odjel.
{45629}{45702}Plakala jsem celou noc, moc jsem se bála.
{45702}{45793}Myslela jsem si, e u tì víckrát neuvidím.
{45793}{45908}Musím ti nìco øíct. |Jsem tìhotná.
{45908}{46011}Sheng a já tì jedeme do Ameriky najít.
{46011}{46070}Musíš na mì poèkat.
{46070}{46136}Tvá navdy milující ena, Jade.
{46136}{46215}Vìøím, e naše pøání se vyplní.
{46215}{46305}Dopis z domova?
{46305}{46418}Má ena je tìhotná.
{46418}{46480}Gratuluji.
{46480}{46575}Dìkuji.
{46575}{46615}To je smìšné.
{46615}{46700}Vy jste dokonce vzal dva centy|za vejce od pana Charlieho.
{46700}{46813}Vy jste øíkal, e to byl dárek.|Nedám vám mùj otisk prstu.
{46813}{46933}Pak vás mùu zaalovat|za porušení kontraktu.
{46978}{47098}Berete nám naše vıhody.|Budeme bojovat.
{47148}{47265}Jste krutı.|Zítra budeme stávkovat.
{47265}{47385}Stávkujeme.
{47837}{47957}To je to, co se stane, pokud |nebudete poslouchat.
{48821}{48941}Musíme pohøbít tìlo, nebo shnije.
{49102}{49213}Tichı protest nemùe vydret dlouho.
{49213}{49333}Dìlníci mìli od toho incidentu ještì horší èasy.
{49770}{49890}Èetl jsi ten dopis u tolikrát.|Nejsi znudìnı?
{49988}{50108}Ty jsi mnich.|Co ty víš o lásce?
{50168}{50288}A co ty?
{50342}{50462}Poslouchej ty vlky venku.
{50685}{50805}Dva mui nebyli zabiti duchem.
{50810}{50903}Ale èlovìkem hledajícím pomstu.
{50903}{51023}odedneška|jsem najmul bìlošské hlídaèe.
{51103}{51223}A také budete nohami pøipoutáni|ve skupinách po šesti.
{51410}{51530}To je Hrdina Hua. Zatknìte ho.
{51657}{51766}Tvùj otec byl podezøelı|z vrady tìch strácù.
{51766}{51865}ivot pro nìj zaèal bıt mnohem horší.
{51865}{51970}Aèkoli jsem neznal tvého otce pøíliš dlouho,
{51970}{52080}spoleènì jsme trpìli jako dìlnicí v Americe.
{52080}{52151}Také jsem obdivoval|jeho smysl pro spravedlnost.
{52151}{52270}Naplnilo mì pıchou mít takového pøítele.
{52270}{52390}Proto jsem se rozhodl riskovat |svùj ivot a osvobodit ho.
{52511}{52591}Ale tu noc ho nìkdo jinı
{52591}{52711}chtìl osvobodit a vzít pryè.
{53025}{53145}Hrdino, jak se máš? |Tady máš trochu vody.
{53275}{53342}Luohane, vypadni odsuï.
{53342}{53451}O oøechu pozdìji.
{53451}{53560}Co tu dìláš?
{53560}{53680}Hrdino, Mistr mi øekl, abych tì zachránil.
{53770}{53890}Jdi napøed.
{54130}{54195}V poøádku. Všichni vstávat!
{54195}{54315}Všichni vstaòte!
{54479}{54599}Co se dìje?
{54712}{54807}Od té noci jsem tvého otce nevidìl.
{54807}{54899}Pozdìji jsem zjistil, e ho zachránil Stín.
{54899}{55019}Nejstarší ák Pıchy.
{55125}{55245}Luohan mi øekl o dnech,|kdy tvùj otce pracoval jako dìlník.
{55285}{55405}Ale já jsem nikdy|neslyšel, e by to otec zmínil.
{55488}{55558}Proè se otec nevrátil do Èíny...
{55558}{55678}k tobì a k matce?
{55767}{55887}Tvá matka a já jsme ho pøišli do Ameriky najít.
{55912}{56032}Tvá matka byla ve ètvrtém mìsíci tìhotenství.
{56360}{56411}Vítejte v Americe.
{56411}{56470}- Jste Èíòané?|- Ano.
{56470}{56504}Kam chcete jít?
{56504}{56575}Hledáme místo, kde mùeme zùstat.|Nìkde, kde je to levné a dobré?
{56575}{56634}Není problém.
{56634}{56721}Nespìchejte.
{56721}{56787}Opatrnì.
{56787}{56838}Dìkuji.
{56838}{56958}Opatrnì.
{57618}{57720}Podívej se na všechny ty lidi|s èervenımi vlasy a zelenımi oèi.
{57720}{57840}Vidìl jsem je v Èínì. Neboj se.
{57842}{57962}Myslím si, e Amerika je velmi velká|a budovy jsou vysoké.
{57970}{58070}Kdy jsme dorazili, vidìla jsem|tu velkou bohyni milosrdenství.
{58070}{58103}Jakou bohyni milosrdenství?
{58103}{58223}Tu s pochodní,|je velká jako hora.
{58240}{58350}To je Socha svobody, madam.
{58350}{58441}Sklapni a tlaè svoji rikšu.
{58441}{58517}Vyslovila jsem u bohynì milosrdenství pøání.
{58517}{58637}Vím, e mùu najít na této cestì Hrdinu.
{58690}{58753}Toto je Èínskı dùm.|Mùete se zde najíst a taky se ubytovat.
{58753}{58802}Nemusíte mluvit anglicky.
{58802}{58889}Je to vedeno Èíòany.
{58889}{59009}Tudy, prosím.
{59069}{59183}Opatrnì.
{59183}{59265}Tvá matka a já jsme cestovali 40 dní,|ne jsme se dostali
{59265}{59350}do Ameriky, najít tvého otce.
{59350}{59468}Vše, co jsem mìl,|byla adresa dolu.
{59468}{59530}Naštìstí zde nebylo mnoho Èíòanù.
{59530}{59650}Tak jsem pouil nejjednodušší metodu,|ptal jsem se všech.
{59729}{59831}Steel Bull Canyon je odtud
{59831}{59880}2 dny vlakem, nebo víc.
{59880}{59942}Je tam mnoho èínskıch dìlníkù?
{59942}{60010}Ano, témìø všichni.
{60010}{60130}Ale ti vedou tìkı ivot,|témìø nelidskı.
{60145}{60229}- Máte tam pøíbuzné?|- Mého mue.
{60229}{60322}Budou to ètyøi mìsíce.
{60322}{60370}Mùete mi pomoci se poptat kolem
{60370}{60435}po mui jménem Hrdina Hua?
{60435}{60470}Hrdina Hua.
{60470}{60590}Zníte vzrušenì, musíte ho tedy znát.
{60602}{60649}Hrdina Hua je váš manílek?
{60649}{60689}Co je to " manílek "?
{60689}{60801}Manel, mu kterého jste si vzala.
{60801}{60879}Vypadá to, e jste sem pøišla zbyteènì.
{60879}{60944}Nerozumím.
{60944}{61064}Poèkejte. Nìco vám ukáu.
{61090}{61150}Hrdino!
{61150}{61232}Ne tak nahlas.|Bìloši zde rozumí èínsky.
{61232}{61303}Co se stalo Hrdinovi?
{61303}{61352}Zabil nìkoho v dole.
{61491}{61556}Jak se mu daøí?
{61556}{61645}My Èíòané si pomáháme navzájem.
{61645}{61765}Proto jsem nevyvìsil tento plakát.
{62124}{62244}Uklidni se.
{62318}{62361}Vezmi nás do Asociace.
{62361}{62397}Hledáte práci?
{62397}{62439}Prostì jeï tam, kam jsme ti øekli.
{62439}{62500}V tìchto dnech je tìké najít práci.
{62500}{62571}Promluv ještì jednou a zmlátím tì.
{62571}{62650}Nìkoho hledáme.
{62650}{62701}Tudy, prosím.
{62701}{62821}Opatrnì.
{62997}{63052}Promiòte, pane.
{63052}{63098}Ano?
{63098}{63218}Nevidìl jste tohoto mue?
{63221}{63280}Ne.
{63280}{63372}Kadı den jsme ho s tvojí|matkou hledali.
{63372}{63492}Nezáleelo na poèasí nebo na èase.
{63495}{63585}Nemìli jsme tady ani rodinu, ani pøátelé.
{63585}{63682}Nalezení tvého otce...
{63682}{63802}bylo naší jedinou nadìjí.
{64436}{64532}Venku prší.|Kam jdeš?
{64532}{64631}Slyšela jsem, e je na severu mìsto
{64631}{64751}S mnoha èínskımi dìlníky.|Chci tam jít.
{64780}{64900}Jsi tìhotná. Mìla bys odpoèívat.
{64977}{65030}Udìlej cestu.
{65030}{65150}Dávej pozor kam jdeš!
{65339}{65459}Prosím, vezmìte mì do Yorktownu na severu.
{65545}{65665}Proè se nehıbete?|Chcete postrèit?
{66300}{66420}Hrdino! To je Hrdina!
{66675}{66761}Hrdino.
{66761}{66798}Moc jsi mi chybìl.
{66798}{66918}Celou dobu jsem tì hledal.
{66952}{67072}- Hrdino.|- Jade.
{67279}{67399}Shengu.
{67764}{67884}Poté, co tvùj otec|obdrel matèin dopis,
{67887}{68003}zùstal v Americe,|tahal rikšu.
{68003}{68063}Kadı den èekal na molu na pøistìhovalce.
{68063}{68183}Doufajíce, e jednoho dne |vyzvedne tvoji matku.
{68188}{68268}Ale zdálo se to beznadìjné.
{68268}{68388}Do toho dne jsme se nevidìli.
{68595}{68687}Divné, jsou zde dva tlukoty srdce.
{68687}{68807}Jeden je mùj a ten druhı|patøí dítìti, hlupáèku.
{68909}{68994}Zdá se e kope, tady.
{68994}{69110}Pojïme se ven projít.
{69110}{69230}Jistì.
{69510}{69555}Znovu mì koplo.
{69555}{69675}Unavená? Zde si odpoèiòme.
{69788}{69908}Je naše dítì unavené?|Nechej mì poslechnout.
{69971}{70032}Pamatuješ si tu noc|pøedtím, ne jsi odešel?
{70032}{70152}Mìla jsem pøání.
{70510}{70630}A opravdu se splnilo.
{71427}{71484}Mám podezøení, e máte...
{71484}{71538}Co je to, doktore?
{71538}{71658}Dvojèata. Gratuluji.|Dovolte mi vám dát lék.
{71841}{71961}V poøádku, chvíli vydrte, prosím.|Zaberete to minutku.
{72010}{72130}Dobrá. Dìkuji. Dobøe!
{72146}{72250}Shengu, pojï sem.
{72250}{72288}Spoleènì.
{72288}{72408}Ne, ne pro mì.
{72494}{72608}Jeden, dva, tøi.
{72608}{72728}Sworde, vìdìl jsi to?|První fotku, na které jsem,
{72740}{72800}poøídili zde v tomto salónu.
{72800}{72850}Odmítl jsem bıt focen.
{72850}{72970}Bál jsem se, e kdy fotoaparát bleskne.|A má duše opustí mé tìlo. 
{72970}{73150}Ale tvoji rodièe naléhali.|tak jsem se k nim pøipojil.
{73195}{73252}Máš stále tu fotku?
{73252}{73372}Hlupáku, je to u dávno.
{73374}{73494}Salon byl uzavøen.
{73629}{73749}Cítím se divnì,|jako by mì sledoval ïábelskı duch.
{73789}{73909}Cítím to tak u od høbitova.
{73909}{73960}Co budeme dìlat, strıèku Shengu?
{73960}{74050}Vymítíme ho, samozøejmì.
{74050}{74170}Moje øeè.
{75567}{75641}Ne.
{75641}{75671}Kdo jsi?
{75671}{75741}Kdo jsi?|Sledovala jsi nás celé dny.
{75741}{75820}Strıèku Shengu. Bratøe Sworde.
{75820}{75866}Bratøe? Jsme pøíbuzní?
{75866}{75979}Myslím si, e jste ti praví lidé.|Já jsem Kate.
{75979}{76044}Otec mì poádal, abych vás |k nìmu pøivedla.
{76044}{76078}Kdo je tvùj otec?
{76078}{76198}Jeho jméno je Stín.
{76950}{77070}Bratr Stín.
{77086}{77206}Sheng.
{77229}{77327}Velkı strıèek Stín,|bratr ve zbrani tvého otce.
{77327}{77400}Vidìl tì, kdy jsi se narodil.
{77400}{77442}Strıèek Stín.
{77442}{77548}Vidíš? Øíkal jsem ti, e jsme pøíbuzní,|bratøe Sworde.
{77548}{77630}Kate, klid.
{77630}{77750}Sworde, dovol mi se na tebe lépe podívat.
{77829}{77949}Hrdinùv syn má velkı|bojovı potenciál.
{78020}{78140}Bratøe Stíne, proè jsi tu?
{78192}{78294}Shledání Hrdiny|a Jade nás sem pøivedlo.
{78294}{78414}Nejšastnìjší èas jejich ivotù.
{78439}{78559}Ale to štìstí...
{78671}{78791}Veselé Vánoce.
{78879}{78999}Milé!
{79008}{79123}Tvùj vánoèní dárek.
{79123}{79243}Dìkuji.
{79364}{79468}Mistr mi naøídil|zachránit Hrdinu z dolu.
{79468}{79571}Zùstal v èínské ètvrti|èekajíc na svoji enu.
{79571}{79670}Ty Vánoce|jsem ho nalezl v Èínském domì.
{79670}{79786}Mistr byl vyzván svım bratrem|ve zbrani na souboj.
{79786}{79906}Vìøil jsem, e Hrdina mùe Mistrovi pomoci.
{80089}{80181}Chci 3 pokoje. |Dva musí bıt sousedící.
{80181}{80301}Tøetí musí bıt dost velkı pro tøi lidi|a musí bıt odlehlejší.
{80323}{80417}- Pokusím se.|- Nepokoušejte se. Udìlejte to.
{80417}{80537}Vy 3 budete v jednom pokoji.|Mu a já si vezmeme kadı svùj pokoj. 
{80540}{80620}Proè vy dva budete mít svùj pokoj|a my se musíme dìlit o jeden?
{80723}{80843}Já vím, Jin chce bıt|v soukromí, co nejblíe Mu.
{80863}{80968}Musel jsem to øíct.|Od tebe ádné poznámky, ani otázky. Zde, pane.
{81114}{81208}Dva ve vıchodním køídle,|jeden v západním køídle. Je to dostateènì daleko?
{81208}{81309}Je to v poøádku?
{81309}{81403}Tihle jsou japonští ninjové.
{81403}{81459}Co mají se mnou spoleèného?
{81459}{81562}Jsou zde pro zprávy o Mistrovi.
{81562}{81682}Kdy najdete toho mue,|setkáme se v jejím pokoji.
{82284}{82404}Pıcha má dva áky.
{82406}{82526}Jeden je Stín a ten další je Hrdina Hua.
{82526}{82646}Stína je tìké najít.
{82667}{82787}Jednou jsem mìl ve svıch |rukách Hrdinu Hua.
{82849}{82969}Ale zabil nìkoho v dole|a nyní je uprchlík.
{83026}{83146}Steel Bull Canyon|dal za jeho hlavu odmìnu.
{83176}{83296}Ale já u vím, kde je.
{83329}{83449}Tak proè jim to neøekneš?
{83472}{83592}Nabízejí jenom 1000 dolarù.
{83633}{83753}Ale pokud vám øeknu, Jine, tuto informaci,
{83878}{83998}má odmìna bude|vìtší ne to.
{84038}{84158}Mùj mistr mi naøídil|najít Pıchu a jeho áky.
{84182}{84302}Bigote, jdi k vìci, øekni svou cenu.
{84360}{84444}Je lepší obchodovat|s Japonci.
{84444}{84564}Tito bìloši jsou tak hloupí.
{84572}{84683}Kdybych byl Hrdina,|chtìl bych se vrátit do Èíny,
{84683}{84803}nebo bych se schoval zde v èínské ètvrti.
{84956}{85076}Hrdina byl zde v Èínském domì|více jak mìsíc.
{85152}{85272}Stíne, nehıbej se.
{85389}{85463}Právì jsi dostal odmìnu.
{85463}{85583}Dám vám instrukce|pøi dalším setkáni.
{85618}{85730}Sbohem.
{85730}{85850}Nashle.
{85868}{85988}Nashle.
{86023}{86143}Pouij Èíòany pro kontrolu Èíòanù.|Se zrádcem jako
{86159}{86238}je Bigot, budu schopen najít Hrdinu Hua.
{86238}{86358}Ohni, Vodo, Zemi, vrate se do svého pokoje.
{86392}{86512}- Ano.|- Musím si promluvit s Mu.
{86712}{86804}Mu, Mistr mi slíbil.
{86804}{86924}Kdy dokonèíme tento úkol,|mùeme se vzít.
{86980}{87100}Kdo øíkal, e si tì vezmu?
{87191}{87311}Po celé ty roky, ty nevíš,|co k tobì cítím?
{87355}{87441}Pak bys mìl vìdìt také,|co k tobì cítím.
{87441}{87561}Pokud je to vše, prosím, jdi.
{87619}{87739}Nesmím tì ztratit v boji.
{89269}{89359}Další den jsme se rozhodli|sledovat tyto lidi.
{89359}{89479}Ale všichni se vytratili.
{94766}{94886}Omlouvám se.
{95422}{95507}Je tvé zranìní váné?
{95507}{95589}Pøišel jsi vèas,|nemá ádné vnitøní zranìní.
{95589}{95709}Bude v poøádku. Neboj se.
{96172}{96284}Doktore, prosím, postarejte se o ni.
{96284}{96346}Od doby, kdy Hrdina zranil Mu,
{96346}{96434}se vyvinul velmi zvláštní pocit.
{96434}{96518}Podívej, je to romantické,|jak se ke mnì chováš.
{96518}{96627}Ukázal jsi slitování, jakmile|jsi zjistil, e jsem dívka.
{96627}{96747}Bude to více romantické,|kdy tì odnesu k doktorovi.
{96766}{96851}Náš boj s ninji|byl jen zaèátek.
{96851}{96889}Ale ani Hrdina neoèekával,
{96889}{96901}e ušetøení Mu|mu mùe pøinést tolik problémù.
