{1}{1}23.976
{476}{507}Èekal jsem vás.
{507}{554}Orb Hunters.
{971}{1014}Ochráním tì...
{1152}{1193}Nezáleí na tom, kde jsi...
{1362}{1424}I kdy poloím ivot...
{1545}{1595}Ochráním tì!
{1830}{1851}Jete!
{1860}{1907}Jsi vadnı!
{2075}{2100}Pøestaòte!
{2100}{2188}Neubliujte...
{2234}{2266}lidem pro mì dùleitım!
{2663}{2702}TaSHee's Gang uvádí|NEO ANGELIQUE ABYSS
{3371}{3408}Co se dìje?
{3408}{3486}Objevil se tu opravdu pìknı mu.
{3486}{3581}A øíká, e pøijel za Angelique.
{3592}{3616}Angelique?
{3769}{3801}Omluvte mì.
{4397}{4423}E-Ehm...
{4474}{4510}Zázraèná dívka.
{4609}{4664}ZÁZRAÈNÁ DÍVKA
{4719}{4802}Angelique, tento gentleman tì pøijel navštívit.
{4802}{4837}Ano, paní øeditelko.
{4924}{5002}Pan Nyx je øeditelem naší Dívèí Akademie Merlose.
{5002}{5066}Chtìl by s tebou mluvit o nìèem dùleitém.
{5120}{5148}O èem chcete mluvit?
{5163}{5223}Prosím nebuï nervózní.
{5223}{5312}Nejdøív ti øeknu o mé práci.
{5325}{5473}Myslím si, e si jsi vìdoma toho, e v posledních| letech nabraly útoky Thanatosù na síle.
{5488}{5512}Ano.
{5512}{5591}V minulosti útoky nebyly tak èasté.
{5591}{5666}Silver Tree Knights je nemohou sami zvládnout.
{5687}{5784}Mnozí vyhledávají jejich pomoc, ale nemùou je najít.
{5784}{5923}Proto jsem se rozhodl vytvoøit organizaci ke znièení |Thanatosù a k vyøešení tohoto problému.
{5938}{5988}Je to moné?
{5988}{6116}Je pravda, e máme málo oèistnıch schopností, abychom Thanatose porazili.
{6116}{6268}Ale pan Nyx má zvláštní schopnost, je to Purifier |/doslovnì oèišovaè ;)/
{6285}{6323}Purifier?
{6424}{6510}Tento kultivovanı mu je Purifier?
{6527}{6586}Nezírej na mì tak upøenì.
{6600}{6662}Nejsem ádné zvláštní exotické zvíøe.
{6694}{6736}O-Omlouvám se.
{6736}{6769}V poøádku.
{6769}{6889}V souèasné dobì pracuju s ostatními Purifiery.
{7852}{8018}Jestlie mám schopnost nièit Thanatose, odmítám |neèinnì sedìt a dívat se, jak ostatní trpí.
{8033}{8063}Obdivuhodné!
{8078}{8113}Dìkuji mnohokrát!
{8113}{8215}Jestlie souhlasíš s mımi nápady, pak by to mìlo bıt rychlé.
{8247}{8402}Dùvod proè jsem dnes tady je, protoe |bych chtìl, abys pracovala se mnou.
{8448}{8506}Obávám se, e nerozumím.
{8584}{8610}To je...
{8627}{8732}Øeditelka byla natolik laskavá, e mi poslala toto vydání školních novin.
{8753}{8819}Je tam napsáno nìco zajímavého.
{9190}{9336}"Pacient, kterı upadl do kómatu po útoku Thanatose
{9336}{9408}byl probuzen pouhım stiskem Angelièiny ruky.
{9463}{9538}Bylo to jako zázrak."
{9548}{9619}Tak jsem se na tebe pøijel ihned podívat.
{9653}{9684}Byla to pouhá náhoda.
{9684}{9772}Probudil se hned, kdy jsem uchopila jeho ruku.
{9772}{9824}Ne. Nebyla to náhoda.
{9853}{9927}Jsi Purifier.
{9927}{10002}Ne, jsem jen...
{10002}{10094}Uvnitø tvého tìla je asi ohromná síla.
{10096}{10185}Jen si ji jednoduše neuvìdomuješ.
{10294}{10400}Bydlím v domì zvaném Sunlit Mansion na okraji mìsta Rhys.
{10400}{10517}Rád bych, abys tam jela se mnou a pomohla mi nièit Thanatose.
{10541}{10583}Zabal si vìci.
{10622}{10677}Nemùu to udìlat.
{10696}{10728}A proè ne?
{10728}{10844}Protoe... by to znamenalo opustit školu.
{10862}{10896}Jistì, to znamenalo.
{10926}{10962}Nemùu to udìlat.
{10971}{11056}Chci bıt doktorkou. A chci pomáhat lidem.
{11056}{11134}Proto chci studovat!
{11155}{11244}Protoe tvùj zesnulı otec byl doktor?
{11293}{11368}Nìco jsem si o tobì vyhledal.
{11396}{11474}Chceš bıt doktorka a uzdravovat nemocné.
{11487}{11544}Rozumím. Je to šlechetnı úmysl.
{11567}{11783}Ale vìøím tomu, e bys mohla zachránit více lidskıch|ivotù vyhlazováním Thanatosù v Arcadii.
{11817}{11935}Naznaèuješ tedy, e jestli máš moc nìkoho zachránit, nechceš ji pouívat?
{12015}{12060}Odpus mi, Mademoiselle.
{12079}{12159}Máš moc zachránit svìt.
{12294}{12370}Jsi Purifier.
{12421}{12482}Proè mi to øekl?
{12814}{12857}Nikdy jsem tì tu pøedtím nevidìla.
{12857}{12895}Máš hlad?
{13489}{13517}Volá mì?
{13521}{13545}Ta koèka...
{13866}{13884}To je...
{14400}{14420}He!
{14435}{14489}Pojï se mnou do mého pokoje.
{14621}{14658}Budeš v poøádku, zastavila jsem krvácení.
{14658}{14827}V této chvíli je to v poøádku, ale nechejte |ránu navlhèenou, abyste se vyhnul infekci.
{14827}{14894}Dobøe, dìkuju.
{14902}{14957}Jsi v tom opravdu dobrá.
{14957}{14998}Jsem na to zvyklá.
{14998}{15031}Ale, vy jste...
{15063}{15101}Jmenuju se Rayne.
{15101}{15164}Rayne-san? Kdo vás zranil?
{15164}{15215}Byl jsem zranìnı pøi boji s Thanatosi v lese.
{15216}{15250}Thanatos?!
{15263}{15292}Zabil jsem je.
{15308}{15342}Nedìlej si s tím starosti.
{15368}{15438}Tím myslíš... jsi Purifier?
{15474}{15512}Ano, nìco na ten zpùsob.
{15512}{15546}Aha...
{15676}{15698}Mimochodem ty jsi...
{15732}{15752}Ange?
{15752}{15784}Jsi tam?
{15791}{15819}Nìkdo je u dveøí.
{15819}{15863}To je Hannah a Sally.
{15912}{15949}Nesmí vás tu najít!
{15949}{15983}Tohle je dívèí lonice.
{15983}{16013}Schovejte se!
{16050}{16093}Eh... Dovnitø!
{16093}{16147}Poèkej chvíli, nemùeš mì nutit...
{16147}{16175}Vlezte tam!
{16233}{16293}Hannah, Sally. Co se dìje?
{16293}{16324}Ange!
{16324}{16451}Nemùu uvìøit tomu, co jsi dìlala celou dobu svého studia.
{16451}{16493}Sally?
{16493}{16600}Sally, buï šastná, e má naše kamarádka takové štìstí.
{16613}{16654}Já nemùu!
{16688}{16781}Pøekvapilo mì, e tì navštívil chlapec, Ange.
{16878}{16917}Slyšely jste to?
{16917}{16949}Ano...
{16949}{16985}O-Oh?!
{16985}{17019}Jste si jisté, e se vám to nezdálo?
{17019}{17036}Opravdu?
{17053}{17094}Co to dìlám?
{17131}{17194}Doufám, e budeš vdycky šastná, Ange.
{17194}{17239}Je to nepøíjemné, ale pøeju ti to samé.
{17239}{17311}Poèkejte! Hannah, Sally! Není to tak...
{17311}{17332}Je to...
{17332}{17360}Není to pravda?
{17387}{17459}Slyšely jsme tì mluvit s tím muem v øeditelèinì kanceláøi.
{17459}{17514}Ah, s ním?
{17528}{17640}Øeditel školy, pan Nyx se mì ptal, jestli bych mu nepomohla s jeho prací.
{17640}{17659}Co?
{17659}{17746}Myslíš Nyxe, kterı bydlí v Sunlit Mansion?
{17746}{17779}Ano, tohle øíkal.
{17792}{17812}Znáš ho?
{17824}{17981}Je to bohatı velkostatkáø, kterı bydlí v sídle na okraji Rhysu.
{17987}{18047}Je tak elegantní a pìknı!
{18073}{18115}Pìknı a BOHATİ!
{18115}{18176}Chci, aby mì vzal na ples.
{18176}{18240}Chci jet ve velkolepém koèáøe!
{18288}{18385}Take, s jakou prací mu chceš pomáhat?
{18406}{18454}Nezdá se mi to jako dobrı nápad.
{18454}{18503}Nechci to dìlat.
{18750}{18774}A potom?
{18931}{18956}Co je?
{19072}{19088}Co se dìje?
{19101}{19145}Na nádvoøí se objevil Thanatos!
{19145}{19177}Uteète!
{19177}{19202}Thanatos?
{19285}{19316}Ještì jeden?
{19328}{19353}Bìte hned odsud!
{19372}{19400}Vy taky!
{19460}{19480}Kdo je to?
{19528}{19557}Thanatos..
{19626}{19662}Rychle odsud pryè!
{19715}{19776}Ta dívka... Purifier...
{19834}{19873}To je nemoné.
{20536}{20568}Zachraòte mì!
{20663}{20690}Rychle pryè!
{20700}{20728}Dìkuju!
{20885}{20909}Tak pojï!
{21079}{21111}Vy jste...
{21138}{21199}Angelique, pojï se mnou prosím.
{21237}{21270}Pojïme znièit Thanatose.
{21350}{21380}Promiò mi mou hrubost.
{21428}{21457}Ange!
{21457}{21540}Byl to Nyx ze Sunslit Mansion, e?
{21563}{21619}Nyxi-san! Prosím, nechte mì jít.
{21619}{21655}Nechte mì jít!
{21704}{21784}Nemám ádné schopnosti!
{21784}{21870}Proè teda sama nezjistíš zdali je máš nebo ne?
{21870}{21952}Tvá síla je neocenitelná.
{21974}{22001}Nechte mì jít!
{22124}{22166}Noblesse oblige.|/šlechetnı závazek/
{22199}{22303}Jestlie máš sílu a nedokáeš ji pouívat, tak je to høích.
{22327}{22358}To  je vıznam tìchto slov.
{22381}{22467}Prosím, dej mi šanci, Mademoiselle.
{22733}{22770}Hej, prober se...
{22770}{22820}Prosím, prober se!
{22820}{22855}Co to dìláš?
{22855}{22886}Bì odsud pryè!
{22886}{22914}Rychle!
{23130}{23148}Nyxi!
{23148}{23220}Jsi v poøádku, Rayne-kun?
{23394}{23414}Ty...
{23441}{23467}Thanatos.
{23743}{23764}Rayne!
{23781}{23833}Zautoèíme z obou stran.
{23833}{23889}Dobøe, je odolnı.
{24253}{24266}Rayne-kun!?
{24842}{24866}Co to dìláte?
{24866}{24905}Bìte se rychle schovat!
{24905}{24961}Ale Ellen...
{24961}{24982}Ellen!
{25645}{25671}Chci je zachránit!
{25727}{25798}Jestli mám moc k jejich záchranì...
{25812}{25891}Jestlie je mùu všechny zachránit...
{25990}{26021}Chci je zachránit.
{26021}{26086}Ano! Chci je zachránit!
{26102}{26123}Chci...
{26123}{26161}je všechny ochránit!
{26616}{26683}Thanatos se rozpadá!
{26801}{26845}Light of Orb!
{27253}{27299}To svìtlo...
{27817}{27839}He!
{27877}{27907}Hej, je to Ona?
{27929}{28010}Její nadání jako Purifier pøevyšuje to naše.
{28035}{28117}Stále mi odmítáš vìøit, Rayne-kun?
{28209}{28234}Jsi v poøádku?
{28252}{28315}Co jsem to...?
{28326}{28406}Znièila jsi Thanatose svou prosbou.
{28406}{28454}Ano... byla to oèista.
{28477}{28596}Jsi jediná dívka-Purifier v Arcadii.
{28606}{28694}Máš unikátní schopnost.
{28973}{29025}Hannah... Sally?
{29038}{29059}Ehm...
{29188}{29214}Ty...
{29589}{29646}Ah, jak sem si myslel.
{30030}{30054}To je krása.
{30064}{30125}Legendární Aurora!
{30192}{30248}Cítím peníze!
{30630}{30665}Nakonec...
{30722}{30743}Aurora...
{30760}{30834}Dùkaz, e se objevilo Queen's Egg.
{30846}{30929}Èekal jsem na tebe.
{31060}{31132}Co je to?
{31224}{31331}Tato nádhera je dùkazem tvé existence.
{31331}{31497}Angelique, jsi jediná nadìje Arcadie, jsi Queen's Egg.
{31582}{31650}Queen's Egg...
{31728}{31820}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31852}{31901}www.mycolorfullife.blog.cz
