{1}{1}23.976
{186}{222}Angelique, zùstaò vzadu!
{251}{315}Poèkej si na vhodnou dobu k oèistì.
{716}{753}Svìtlo Oèisty...
{1061}{1076}Neuvìøitelné!
{1076}{1110}Jsme vám vdìèní, Orb Hunters.
{1110}{1131}Queen's Egg!
{1131}{1164}Boí!
{1164}{1200}Go, Orb Hunters!
{1213}{1236}Orb Hunters...
{1236}{1290}To kvùli názvu Bernardova èlánku.
{1290}{1366}Nemyslím si, e bychom si tak sami øíkali, ale...
{1381}{1435}Proè ne?
{1435}{1484}Jo, všichni jsou šastní.
{1583}{1626}Jsem šastná, e jsou všichni v bezpeèí!
{1680}{1735}TaSHee's Gang uvádí
{1925}{1959}NEO ANGELIQUE ABYSS
{3843}{3899}ROZHODUJÍCÍ CESTA
{4685}{4731}Hej, co to øíkáte?
{4746}{4843}Je tu napsáno "Jeïte do Celestizamu" a je to vızva Head Order.
{4843}{4898}Head Order?
{4898}{4968}Vızva z Holy Capital, ne?
{4996}{5050}Setkání s Head Order...
{5069}{5105}Proè já?
{5116}{5228}Dùvod, e tì pozvali mùe bıt jakıkoli, kadopádnì musíš pøijmout.
{5240}{5336}Head Order má velké  nadìje v Queen's Egg.
{5357}{5417}Je pocta se s ním setkat.
{5500}{5566}Hyuugo-dono! U je to dlouho!
{5589}{5657}Je dobøe, e slouíš Queen's Egg.
{5657}{5772}I kdy jsi opustil Silver Tree Knights, tak tvoje èest je ve tvém srdci.
{6178}{6216}Ten vítr je pøíjemnı!
{6216}{6290}Vdycky jsem chtìla jet na místì pro koèího.
{6290}{6324}Omlouvám se.
{6324}{6408}Ale mu jako já vám jen zkazí náladu.
{6425}{6451}Nebuïte hloupı...
{6462}{6536}Jedete do Celestizamu poprvé?
{6536}{6607}Ano, mám strach, protoe toho o Order moc nevím...
{6621}{6651}Celestia Order.
{6651}{6840}Pro ty, kteøí uctívají legendární, prorokovanou Královnu. |Jsou duševní podporou.
{6852}{6928}A jejich vedoucím je Head Order.
{6941}{7021}Proè bych se mìla setkat s nìkım tak dùleitım?
{7021}{7112}Pravdìpodobnì proto, e Organizace vidìla vèerejší èlánek.
{7156}{7180}Èlánek...
{7216}{7284}Chtìjí potkat dívku, která by mohla bıt Queen's Egg.
{7300}{7393}Dává to smysl, protoe Order chce bıt pøední náboenskou organizací.
{7436}{7479}ádnı strach.
{7479}{7548}Urèitì nám chtìjí pomoct.
{7548}{7577}To je pravda.
{7752}{7849}Hyuugo-san, proè jste opustil Silver Tree Knights?
{7849}{7898}Protoe jsem byl nezkušenı.
{7911}{7973}Není to nic, co by vás mìlo znepokojovat.
{7973}{7993}Dobøe...
{8081}{8153}Mùeš prosím zastavit u Melrose Academy?
{8153}{8206}Rád bych pozdravil paní øeditelku.
{8324}{8370}Moná uvidím Hannah a Sally!
{8421}{8448}U je to dlouho!
{8448}{8472}Ange!
{8486}{8548}Oh Ange, chybìla's mi!
{8548}{8583}Vidìla jsem noviny!
{8583}{8620}Dokáeš neuvìøitelné vìci, e?
{8620}{8646}Ale ne...
{8658}{8680}Ale omlouvám se!
{8680}{8759}Chtìla jsem vás pøijet navštívit døív.
{8759}{8854}Ne, máš daleko dùleitìjší vìci, ne se starat o nás.
{8904}{8948}Oh Sally, nehraj to...
{8948}{9044}Poøád mluvila o tom, e odsud odejde a pùjde tì navštívit.
{9044}{9157}Sakra, vím, e bych ji otravovala.
{9248}{9282}Je to opravdu ona!
{9364}{9380}Poèkejte...
{9449}{9498}Ty jsi Queen's Egg...
{9498}{9554}Vìdìla jsem, e jsi jiná!
{9554}{9671}A se staneš Královnou, nezapomeneš na nás, e?
{9688}{9708}Co mám dìlat?
{9708}{9753}Tohle se mi vymklo z rukou...
{9784}{9841}Máte rád vaøení, e?
{9841}{9931}Ano. Jsem šastnı, kdy se lidí usmívají, kdy jí moje jídlo.
{9931}{9997}Urèitì to taky zkuste.
{9997}{10022}J-Jistì!
{10041}{10120}Nebojíte se bojovat s Thanatosem?
{10120}{10184}Ano... èasto se tøesu strachy.
{10184}{10279}Ale víte, Rayne-kun je stateènìjší!
{10279}{10308}H-He! Coe, já?
{10308}{10355}Úasné!
{10439}{10513}Kdybych vìdìl, e se to stane, radši bych taky zùstal v koèáru.
{10649}{10663}Ange.
{10721}{10775}Dlouho se neuvidíme, take...
{10775}{10825}Hodnì štìstí, dobøe?
{10840}{10877}Spoléháme na tebe!
{11091}{11162}Je to pravda, e tu Orb Hunters zùstanou?
{11162}{11260}Hm... zøejmì o tom starosta ví a pøipravil uvítací veèírek!
{11310}{11326}To je...
{11341}{11442}Pøipravili jsme to pro budoucí Královnu.
{11455}{11476}Co budeme dìlat?
{11476}{11560}Bylo by od nás hrubé, kdybychom to odmítli.
{11560}{11622}Tak uijme jejich laskavosti!
{11634}{11677}Máte pravdu.
{11693}{11737}Dìkujeme za vaši laska-
{11829}{11923}Hej, Marie! Vítáme dùleitou návštìvu.
{11997}{12064}Prosím, zachraòte moji maminku, Královno!
{12141}{12233}Tahle vesnice byla napadena Thanatosem.
{12233}{12306}Spousta lidí pøišla o ivot.
{12306}{12418}Mariina matka pøeila, ale...
{12418}{12522}u nenabyla vìdomí.
{12598}{12630}Strašnì se omlouvám...
{12630}{12698}Øíkal jsem jí, aby vás neobtìovala, ale...
{12710}{12801}Ale øíkal jsi, e Královna dokáe zázraky.
{12801}{12885}Máminy ruce chladnou.
{12900}{12928}Jestli nepomùete...
{12989}{13044}Prosím, pomozte jí!
{13069}{13155}Marie, vím jak se cítíš, ale nebuï sobecká.
{13191}{13207}Ehm...
{13225}{13262}Jestli chceš, mùu...
{13294}{13374}Budoucí Královna udìlá zázrak!
{13430}{13459}Hej, u to zaèalo?
{13459}{13505}Eh... nic nevidím...
{13505}{13561}Modlí se!
{13694}{13726}To je hluku...
{13825}{13857}Svìtlo Oèisty...
{13875}{13945}Prosím, probuï Mariinu matku!
{14113}{14218}Tehdy jsem chtìla zachránit lidi, kteøí nemìli šanci.
{14260}{14310}A teï je to stejné...
{14573}{14594}To je divné...
{14594}{14626}Je to dobré?
{14626}{14679}Uzdravila ji?
{14679}{14821}Všichni na mì spoléhají, to je hrozné!
{14924}{14973}Královno, prosím, zachraòte moji maminku!
{14983}{15028}Dlouho se neuvidíme, take...
{15028}{15054}Hodnì štìstí!
{15054}{15127}Spoléháme na tebe, dobøe!
{15148}{15233}Jestlie zmaøím jejich nadìje...
{15306}{15345}Hej, Angelique!
{15357}{15382}Jsi v poøádku?
{15397}{15443}A-Ano...
{15443}{15474}Je v poøádku?
{15474}{15500}Co se stalo?
{15500}{15548}Necítí se dobøe?
{15548}{15635}Královno... moje maminka...
{15740}{15837}Omlouvám se, ale je unavená po dlouhé cestì.
{15837}{15870}Ale moje maminka...
{15884}{15985}Necháme ji dneska odpoèívat, ano?
{16204}{16269}Doprovodím vás do vašich pokojù.
{16301}{16348}Tudy.
{16575}{16697}Proè nestrávíme noc pod hvìzdami?
{17048}{17093}Tvùj èaj, Angelique.
{17113}{17144}Dìkuji.
{17293}{17358}Kdybych byla silnìjší...
{17375}{17426}Podstata tohoto problému je Thanatos.
{17437}{17510}Dùvodem není to, jak se cítíš.
{17510}{17531}Ale...
{17548}{17623}Bolí tì srdce, e?
{17636}{17717}Kdybych mohl udìlat nìco, co by ti pomohlo...
{17717}{17774}Hej, taky na to myslím...
{17774}{17899}Máš tendenci upøednostòovat ostatní, ne sebe.
{17899}{17963}To je špatné...
{18050}{18119}Je to problematické, ale nauèila jsem se silou pozorovat moji matku a otce.
{18134}{18237}Poøád chci pomáhat lidem jako moji rodièe.
{18237}{18310}Byli doktoøi, kteøí zachraòovali ivoty...
{18356}{18420}Tati, pomùu ti!
{18420}{18504}Ale, ale... Jaká roztomilá doktorka.
{18514}{18584}Trvala na tom.
{18584}{18649}Vidíš? Zkoušela to na mì!
{18685}{18740}Jednou bude urèitì doktorka.
{18757}{18907}Ale pak byla naše vesnice Fleur napadena Thanatosem...
{19166}{19199}Stále mají puls, ale...
{19199}{19231}Nevzdávej to!
{19231}{19303}Urèitì mùeme nìco udìlat!
{19581}{19682}Moji rodièe tvrdì pracovali, aby zachránili ostatní, a do úplného konce.
{19698}{19783}Tahle vzpomínka na nì je ta nejpyšnìjší vìc, kterou jsem kdy cítila.
{19783}{19853}Od té doby iješ sama, e?
{19853}{19911}Musela's bıt osamìlá.
{19929}{20048}Ne, mìla jsem hodnì lidí, kteøí mì podporovali.
{20119}{20219}Jednou budu doktorkou jako moji rodièe a budu zachraòovat ivoty.
{20219}{20352}Drím se toho od té doby, co se ve mì probudily oèistné schopnosti.
{20392}{20473}Jestlie budu pouívat své síly, zachráním více lidí.
{20473}{20550}Ano, to je to o èem jsem tì pøesvìdèoval.
{20550}{20610}A stále vìøím, e je to tvùj dùvod.
{20610}{20685}Ale, jestli zmaøím jejich nadìje jako dnes...
{20705}{20775}Tyhle nadìje a sny moná zmizí!
{20825}{20951}Tvé pøání zachránit je, je dùleitìjší, ne jejich vlastní pøesvìdèení.
{20987}{21104}Všichni víme, e jsi dìlala co jsi mohla, abys zachránila Mariinu matku.
{21120}{21152}A oni to ví taky.
{21179}{21268}Jsem si jistı, e v budoucnosti budete podrobena nìèemu podobnému.
{21284}{21343}Ale já vás stále budu podporovat, jak jen budu moct.
{21473}{21514}Máte pravdu...
{21514}{21555}Nejsem sama.
{21590}{21635}Nakonec jsi se usmála.
{22525}{22551}Nemùeš spát?
{22596}{22620}Nyxi-san!
{22690}{22732}Pøemıšlím o spoustì vìcech...
{22805}{22909}Opravdu mùu zachránit Arcadii?
{22952}{22977}Podívej.
{23005}{23105}Poehnaná pøíroda, všude krásné kvìtiny .
{23120}{23230}Na kolik kvìtin se teï díváš?
{23249}{23287}Neumím si to ani pøedstavit...
{23287}{23356}I kdybych strávila celı den jejich poèítáním, nikdy by nebyly všechny.
{23372}{23459}Víš kolik kvìtin je na celém svìtì?
{23471}{23487}Ne...
{23487}{23521}Správná odpovìï.
{23521}{23612}Pøedstav si èíslo, které nikdy nebudeš moct uhádnout.
{23641}{23765}Pøedtím jsem ti øekl, e tvé schopnosti zachrání hodnì lidí.
{23765}{23786}Ano.
{23803}{23902}Ale nikdy jsem nenaznaèoval, e bys je mohla všechny zachránit ve stejnı èas.
{23947}{24035}Stejnì jako je nemoné spoèítat všechny kvìtiny na svìtì,
{24035}{24219}nemùeš zachránit všehny lidi v celé, velké Arcadii, aby se vyhli utrpení.
{24231}{24297}Rozumím tvé jemné povaze...
{24297}{24429}taky vím, e bolest z toho, e nìkoho nezachráníš, |zastíní tvou radost, kdy nìkomu pomùeš.
{24429}{24449}To je...
{24464}{24522}Nikdy je nebudeš moct všechny zachránit.
{24522}{24572}Jsi budoucí Královna.
{24572}{24622}Budeš vládnout lidem v této zemi.
{24637}{24754}Mìla bys pochopit, e obìti jsou nezbytné.
{24790}{24815}Mılím se?
{24841}{24919}To, co øekl je logické.
{24919}{25006}Mluví z nìj zkušenosti.
{25019}{25068}Ale jestlie to pøijmu...
{25102}{25152}Tati... mami!
{25220}{25255}Myslím, e se mılíte.
{25288}{25380}Mùe to bıt hloupé, myslet si, e všechny zachráním...
{25380}{25454}Ale je tu èlovìk, kterı se pøede mnou trápí...
{25474}{25511}Nemùu to ignorovat!
{25631}{25710}Vìdìl jsem, e to øekneš, Mademoiselle.
{25710}{25796}Pokraèuj v tom, v co vìøíš.
{25812}{25917}A bude mi ctí kráèet po tvém boku.
{25957}{26002}T-To je...
{26002}{26053}Promiòte, byla jsem arogantní...
{26053}{26113}Já jsem ta, co by se mìla omluvit.
{26154}{26246}Nyxi-san... Zkoušíte mì?
{26305}{26391}Ne, dívá se na mì!
{26459}{26490}Jémine!
{26490}{26517}O-omlouvám se...
{26602}{26730}Bude pøíjemné, jestli má vøelost trochu zahøeje.
{26730}{26769}D-Dìkuji mnohokrát...
{27090}{27130}Budeš se se mnou modlit?
{27155}{27170}Ano.
{27513}{27543}Svìtlo Oèisty...
{28038}{28054}Kde to jsem?
{28054}{28074}Mami!
{28092}{28108}Marie!
{28108}{28136}Mami!
{28264}{28286}Zvládla jsi to.
{28286}{28313}Ano!
{28313}{28340}Královno!
{28364}{28421}Mnohokrát dìkuju, Královno.
{28421}{28493}Ne, to já bych ti mìla dìkovat.
{28538}{28612}Díky tobì jsem zjistila, co je opravdu dùleité.
{28723}{28785}Ah, jsi opravdu...
{30048}{30108}Opravdu nevím jestli skuteènì mùu zachránit svìt.
{30108}{30239}Ale udìlám všechno, co budu moct.
{30261}{30327}Jako moji rodièe!
{30685}{30710}Omlouvám se.
{30737}{30808}Rád bych zùstal tady.
{30857}{30916}Opustil jsem Knights.
{30916}{30975}Nemùu zamoøit Capitale svou pøítomností.
{31000}{31053}Vím, e budete v poøádku.
{31233}{31250}Angelique.
{31762}{31854}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31905}{31977}www.mycolorfullife.blog.cz
