{1}{1}23.976
{141}{173}Oèekávali jsme vás.
{213}{247}To je...
{247}{309}To je nìjaké uvítání!
{441}{518}Jmenuju se Dion a jsem kapitán Silver Tree Knights.
{719}{776}TaSHee's Gang uvádí
{951}{1000}NEO ANGELIQUE ABYSS
{3127}{3178}POU DO SVATÉHO MÌSTA
{3240}{3294}Pøekáí mi...
{3339}{3436}Sakra... Nejsem tady kvùli vašim fotkám!
{3664}{3692}Jak jsem si myslel!
{3726}{3768}Mùj malı sladkı poklade!
{3863}{3914}A co Hyuuga ?
{3948}{4010}Znám ho dlouhou dobu.
{4029}{4088}Ah, je taky rytíø jako vy?
{4100}{4177}Ano. Spoleènì jsme se uèili šermovat.
{4191}{4235}U nìkolikrát jsem ho hledal...
{4247}{4286}Hyuuga-san se má opravdu dobøe.
{4286}{4365}Pøijel zde s námi, ale...
{4365}{4414}Zùstal venku, e?
{4414}{4471}Nezmìnil se.
{4471}{4501}Opravdu?
{4686}{4777}Od té doby, co se objevila Aurora, navštìvuje nás hodnì poutníkù.
{4794}{4878}Nadìje, e se narodila královna, stoupá.
{5053}{5116}Nemùu uvìøit, e na mì èeká tolik lidí...
{5229}{5290}Head Order vás oèekává.
{5310}{5344}Dobøe, pùjdu.
{5344}{5361}Ok.
{5390}{5412}ádnı strach.
{5434}{5452}Budeš v poøádku.
{5476}{5541}Je to v poøádku. Sna se.
{5541}{5622}Jsem si jistı, e setkání probìhne v poøádku, Mademoiselle.
{5654}{5666}Ano.
{6005}{6023}Pojïme.
{6548}{6606}Head Order pøichází.
{7111}{7175}Dìkuji, e jsi pøijela, Angelique.
{7234}{7254}Jmenuji se Angelique.
{7342}{7408}Tohle je Head Order.
{7439}{7495}Dìkuji za všechno, Dione.
{7495}{7529}Mùeš odejít.
{7529}{7547}Dobøe.
{7630}{7700}Angelique, Queen's Egg.
{7700}{7800}Zvìsti o tıch skutcích dolehly a ke mì.
{7800}{7900}Nebyly to jen mé skutky... Stále pøijímám pomoc od ostatních.
{7900}{7947}Nemusíš bıt skromná.
{7964}{8031}Ne! Moc tomu nerozumím...
{8031}{8095}Stále se vypoøádávám s tím, co stojí pøede mnou...
{8095}{8181}Pak to byly zásluhy, které tì zavolaly sem.
{8210}{8341}Dùvodem, proè jsem tì sem zavolal je, abys byla mou následnicí.
{8365}{8551}Pùsobivé... Pøedpokládám, e máme lepší pokoj, jakoto sluebníci Queen's Egg.
{8583}{8654}Nepamatuju si, e bych byl její sluebník.
{8654}{8707}Mimochodem, kde je J.D.?
{8721}{8776}Øíkal, e se chce projít po okolí.
{8794}{8868}Pøedpokládám, e bude tady, ne se Angelique vrátí.
{8868}{8891}To je pravda.
{8930}{9046}Angelique, Thanatosové jsou jen stíny.
{9046}{9068}Stíny?
{9083}{9094}Ano.
{9109}{9203}Ano, stíny, které jsou pùvodcem útrap celé Arcadie.
{9222}{9282}A jádrem tohoto problému je...
{9282}{9303}Erbos.
{9318}{9347}Erbos?
{9347}{9405}Nevíme nic o jeho fyzické formì, ale...
{9405}{9465}domníváme se, e je to smìs špatnıch úmyslù.
{9485}{9689}Erbos byl jednou zapeèetìn do jiné dimenze,| ale jednoho dne našel trhlinu a otevøel ji.
{9718}{9944}Erbos posílá stíny, Thanatose, skrz trhlinu, aby získávali ivotní energii.
{9975}{10130}Právì teï je poškození lokalizováno, ale èasem mùe bıt svìt stejnì znièen.
{10176}{10289}Silver Tree Knights a Orb Hunters jsou pouze doèasní zachránci pøed Thanatosi.
{10289}{10335}Nemùeme je znièit.
{10353}{10459}Pouze Královna je mùe kompletnì znièit.
{10482}{10583}Jak mùe Královna znièit Erbose?
{10614}{10703}Mohla by... jestlie by mìla skuteèné schopnosti královny.
{11119}{11141}Ty?
{11168}{11212}Øíká se, e jsi stále stejnì agresivní.
{11242}{11267}Stejnì jako ty.
{11278}{11341}Ujel jsi dlouhou cestu.
{11341}{11404}Mìl bys alespoò navštívit Head Order.
{11422}{11453}Nemùu.
{11480}{11530}Jsi tvrdohlavı jako vdycky.
{11556}{11626}Stále se nechceš vrátit k Order?
{11664}{11714}Nikdo tì neobviòuje!
{11714}{11786}Mu s tvım talentem by mìl...
{11786}{11828}Nechci.
{11920}{12012}Take jsi stále ranìnı kvùli Carlylovi?
{12059}{12216}Jestlie se narodila Královna, lidé u nebudou trpìt strachem a budou moci ít v míru.
{12231}{12254}Ano.
{12254}{12347}Neseš nadìji všech lidí.
{12347}{12398}Ale já jsem...
{12473}{12581}Opravdu nevím, jestli mùu splnit jejich oèekávání...
{12913}{13020}Nikdy jsem si nemyslel, e by Queen's Egg mohla bıt tak køehká dívka.
{13153}{13175}Angelique...
{13204}{13234}Queen's Egg.
{13264}{13397}Moná stále potøebuješ pomoc, aby se ti nic nestalo.
{13433}{13503}Ale vìø si!
{13503}{13581}Vìz, e svìt na tebe dohlíí.
{13699}{13814}Modlím se za den, kdy se z tebe stane pravá Královna.
{13814}{13921}To je nejen má prosba, ale také prosba Order celého svìta.
{13921}{13952}Dobøe.
{13965}{13993}Dìkuji mnohokrát.
{14122}{14222}Budu dìlat co je v mıch silách.
{14254}{14301}Dìkuji mnohokrát, Angelique.
{14314}{14373}Omluvte nás.
{14373}{14468}Vaši pøátelé vás èekají támhle.
{14468}{14497}Dìkuji mnohokrát!
{14614}{14647}Byla jsem tak nervózní!
{14665}{14723}Potøebuju se za nimi vrátit.
{14790}{14820}Co?
{14930}{14987}Jaká byla schùzka, Queen's Egg?
{15003}{15041}V-Vy jste?
{15057}{15107}Pardon! Nejsem nikdo dìsivı!
{15107}{15162}Jmenuju se Roche!
{15162}{15207}Jsem novináø.
{15232}{15259}Novináø?
{15259}{15360}Ano. Mùu s tebou chvilku mluvit?
{15360}{15419}Právì jsi støedem pozornosti, víte to?
{15449}{15516}Èekají na mì pøátelé...
{15540}{15579}Èekají na tebe?
{15594}{15645}Ah, oni!
{15678}{15721}Oni poèkají!
{15738}{15769}Jak hrubé!
{15784}{15812}Omluvte mì.
{15874}{15907}Nebuï taková!
{15907}{15989}Dobøe? Mùeme si promluvit u èaje jestli chceš.
{16063}{16114}Jsi roztomilá, kdy jsi rozèilená!
{16190}{16245}V kadém pøípadì pojï, pomoz mi.
{16245}{16291}H-Hej...
{16388}{16408}Hej ty!
{16427}{16460}Podívej, co jsi udìlal!
{16460}{16528}O-Omlouvám se, e jsme blokovali ulici...
{16528}{16646}Co tady chcete?
{16660}{16732}Podle vašeho obleèení rozhodnì nejste poutník.
{16767}{16861}Bude to zlé jestli vás rytíøi najdou...
{16904}{16936}Tam jsou!
{17085}{17103}Pojï se mnou.
{17177}{17195}Rychle!
{17210}{17229}Zastav!
{17252}{17301}Co? Nikdo tam není...
{17331}{17347}Neøíkejte, e...
{17408}{17448}Ten kluk!
{17462}{17485}Tudy!
{17524}{17556}Co je?
{17613}{17646}Co se dìje?
{17801}{17832}Zpozdila se.
{17850}{17927}Nemìj starosti, Rayne.
{17927}{17952}To je pravda.
{18022}{18072}Ehm.. Kam to jdeme?
{18095}{18137}Sleduje nás.
{18191}{18246}To je teda terno!
{18246}{18306}Mu unášející Queen's Egg.
{18345}{18381}Ale kdo to je?
{18381}{18469}Bìhat kolem Holy Capitale je tak lehkomyslné...
{18469}{18509}Dobøe, bude to terno!
{18524}{18565}Sakra... Je vytrvalı.
{18565}{18587}Tudy!
{18654}{18673}Poèkejte!
{18736}{18753}Pojï!
{18823}{18854}Nenechám vás utéct!
{18873}{18898}Kde jste?
{18934}{18953}Tudy!
{18981}{19023}Co to s nima je?
{19104}{19143}Poèkejte!
{19143}{19162}Tudy!
{19230}{19253}Tudy, tudy!
{19291}{19310}Sakra!
{19333}{19352}Poèkejte!
{19412}{19439}To je...
{19473}{19543}Sakra! Za tohle vás dostanu!
{19585}{19616}Co to dìláte?
{19650}{19713}Takové podivné dítì...
{19713}{19729}Pojïme.
{19764}{19802}Poèkejte!
{19802}{19835}Vy byste mìl poèkat
{19835}{19869}Nechte mì jít!
{19869}{19918}Fotit bez povolení je ilegální.
{19918}{19955}Zabavíme vám váš fotoaparát.
{19981}{20047}To není pravda! Poèkejte!
{20072}{20132}Mùj poklade!
{20306}{20341}Byla jsem pøekvapená.
{20356}{20470}Dìkuji mnohokrát, e jsi mì zachránil pøed tím muem.
{20561}{20585}To je krásné!
{20615}{20687}Nikdy jsem nevidìla nic tak krásného!
{20714}{20744}Jmenuju se René.
{20761}{20808}Jsem èlenem Silver Tree Knights.
{20831}{20855}Ale stále jsem ještì uèeò.
{20884}{20920}Já jsem Angelique.
{20936}{21007}Já vím. Jsi Queen's Egg?
{21007}{21043}Pøijela jsi za Matsiasem...
{21043}{21109}Tedy myslel jsem, lordem Mathiasem.
{21109}{21142}Lord Mathias?
{21142}{21214}Osoba, kterou jsi navštívila.
{21214}{21249}Ah, Head Order.
{21333}{21409}iješ tady, René-san?
{21409}{21427}Ano.
{21450}{21502}Je to opravdu krásné místo!
{21562}{21610}Moná to tak podle vás vypadá...
{21679}{21723}Vlastnì, Angelique!
{21723}{21787}Vezmu tì na tajné místo.
{21787}{21810}Eh...
{21944}{21977}Jsi roztomilá.
{21977}{22040}Dreli jsme se za ruce celou dobu.
{22056}{22087}Coe?
{22109}{22168}To je divné...
{22168}{22214}Je to jako bych ho znala.
{22575}{22608}Silver Tree...
{22644}{22686}Je to moje tajné místo...
{22702}{22733}Je tu teplo!
{22733}{22789}Tady nesnìí?
{22789}{22839}Ne, takhle je tady celı rok.
{22991}{23017}Co je to?
{23138}{23183}Je to jako by mì k sobì ten strom volal...
{23444}{23496}Ehm, René-san... Ten strom je...
{23496}{23560}Je to Great Silver Tree.
{23583}{23657}Je to ivotní forma Arcadie.
{23657}{23755}Kdy svìt zùstává krásnı, strom se nepøestává tøpytit...
{23784}{23848}ivotní... forma Arcadie.
{24507}{24575}Tohle se nikdy pøedtím nestalo...
{24704}{24724}Je to teplé...
{24780}{24861}To teplé svìtlo mi naplòuje srdce...
{25006}{25051}Vypadá to, e tì vítá!
{25099}{25151}To by bylo úasné!
{25179}{25220}Øekni, Angelique...
{25254}{25339}Øekli ti, e svìt má bıt tvùj a máš ho zmìnit.
{25354}{25447}Jestli se staneš Královnou, budeš muset vést svìt.
{25484}{25552}Moná budeš muset vydret bolestivé záitky.
{25565}{25621}Vydríš to?
{25667}{25787}Bude to tìké, ale udìlám co budu moct.
{25787}{25861}Vìøím, e mì lidé podporují.
{25931}{25953}Aha...
{25996}{26009}Jsem...
{26044}{26080}pták v kleci.
{26114}{26144}Ale Angelique...
{26185}{26205}Ty jsi...
{26376}{26434}Kolik knih u jsi pøeèetl?
{26434}{26467}Tohle je dvanáctá.
{26509}{26559}A ty? Kolik šálkù èaje jsi vypil?
{26559}{26601}Tohle je druhı.
{26637}{26690}Moná u je èas.
{26702}{26714}Ano.
{26760}{26778}Kde je J.D.?
{26998}{27036}Musím se vrátit...
{27505}{27568}Musím se vrátit... Musím se k ní vrátit.
{27701}{27735}Co to dìláš?
{27735}{27782}Angelique u se vrátila.
{27782}{27795}Ano...
{27845}{27904}U jdu za ní.
{27981}{28034}Promiòte, e jsem se zpozdila.
{28055}{28097}To je v poøádku.
{28097}{28146}Všechno je v poøádku, kdy u jsi tady.
{28146}{28199}Potkala jsi nìjaké zajímavé lidi?
{28199}{28243}Ano!
{28243}{28276}Oh? To je...
{28384}{28420}Head Order!
{28420}{28476}Co? To je Head Order?
{28531}{28585}Dìkuji za dnešek.
{28585}{28651}Právì se vracím.
{28651}{28743}Ne. Zùstanete v Celestizamu.
{28788}{28870}Váš osud je veliec nejasnı.
{28895}{28955}Nemùeme riskovat vás ivot.
{28982}{29071}Mìla byste zùstat tady, pod ochranou rytíøù, ne pøijde èas.
{29089}{29118}Ale, ale...
{29118}{29202}Chcete si udret tuto krásnou kvìtinku u sebe?
{29225}{29267}Jakı to nápad!
{29267}{29307}Avšak, nemùu to dovolit.
{29348}{29414}Mùete to zváøit, sire?
{29437}{29483}Je naší dùleitou souèástí.
{29483}{29558}Ochráníme ji.
{29584}{29605}Pøátelé...
{29672}{29743}Já.... kdy jsem s vámi...
{29775}{29837}Promiòte mou hrubost, sire.
{29859}{29999}Do dne, ne se stanu královnou, chci zachránit |tolik lidí, kolik jen bude moné.
{30016}{30097}Budu dìlat co bude v mıch silách s mımi spoleèníky v Sunlit Mansion.
{30375}{30424}Take se nevrátíš?
{30424}{30483}Ne.
{30483}{30569}Jsi rozpustilı jako vdy.
{30725}{30757}Hej, Matshiasi!
{30757}{30773}René!
{30787}{30850}Ta dívka opravdu existuje!
{30866}{30886}Opravdu...
{30916}{30938}Aha.
{31004}{31095}Jednou se sem vrátí.
{31115}{31137}Vím to.
{31222}{31291}Mí drazí... pøátelé...
{31433}{31463}Dìlej co mùeš.
{31488}{31576}Je to velmi dùleitá cesta, Angelique.
{31590}{31655}Tak pojeïme domù.
{31670}{31688}Ano!
{31985}{32064}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32094}{32135}www.mycolorfullife.blog.cz
