{1}{1}23.976
{369}{409}To všechno udìlala Jinx?
{409}{445}Ano...
{445}{494}Za zlomek vteøiny.
{494}{588}Jeden dìlovı vıbuch a Thanatos byl znièen.
{606}{647}A naše domy s ním.
{711}{780}Bude to takhle dál pokraèovat?
{817}{910}V momentì, kdy byl Thanatos znièen...
{910}{951}No, nestìuju si.
{1195}{1220}Jinx?
{1271}{1324}TaSHee's Gang uvádí
{1498}{1548}NEO ANGELIQUE ABYSS
{3680}{3731}VOLNİ DEN VE WODON
{4103}{4168}Oh, dáváš si pauzu od bádání?
{4170}{4200}Jo.
{4233}{4292}Je tu bez ní ticho.
{4292}{4346}Odcházela opravdu šastná.
{4399}{4436}Chceš, Rayne?
{4436}{4526}Pøipravil jsem je s láskou pro pøátele Ange.
{4526}{4574}Ano, voní to pìknì.
{4678}{4775}Doufám, e se máš dobøe, Mademoiselle.
{5036}{5070}Vítej, Ange.
{5087}{5130}Chybìla's mi, Ange!
{5150}{5193}Dìkuju za vaše pozvání.
{5193}{5206}Tady.
{5233}{5268}Ah, voní to hezky.
{5268}{5385}Dobøe, dnešní den strávíme spoleènì! Máme si toho tolik co øíct!
{5412}{5426}Ano!
{5487}{5518}Mmmm... je to vynikající!
{5518}{5639}Øekni, Ange! Pøipravujou ti takové vıborné koláèky kadı den?
{5639}{5718}Ano. Jsou to všichni vıborní kuchaøi.
{5718}{5746}To není fér.
{5759}{5877}árlím, e jsi obklopená chlapíky jako jsou Orb Hunters.
{5877}{5927}A ještì si jíš takové vıborné domácí jídlo!
{5927}{5978}Já tak strašnì árlím!
{5978}{6079}Ale jsem si jistá, e tohle štìstí musí mít nìjakı háèek.
{6079}{6216}Kadı z nich je jinı, ale jsou to skuteèní gentlemani.
{6232}{6310}I sleèna "Váná" se musí do jednoho z nich zamilovat, a u chce nebo ne.
{6310}{6327}Take...
{6327}{6377}Kterého z nich chceš?
{6534}{6610}Všechno na svìtì je v poøádku.
{6624}{6661}Ooo, vy dvì!
{6683}{6717}Promiò, promiò!
{6717}{6830}Jen jsme ti øekly, e máš nejvyšší èas se zamilovat.
{6830}{6857}To je nemoné...
{6868}{6949}Ale jsem si jistá, e teï neseš na bedrech menší bøemeno.
{6949}{7012}Od té doby, co Foundation vyrobila Jinx.
{7040}{7059}Jinx...
{7152}{7185}Poslouchejte...
{7207}{7226}Jinx je...
{7517}{7547}Takovou vìc vyrobili...
{7567}{7673}Jinx mùe bıt pro lidi nebezpeèná!
{7687}{7769}Ale, nakonec nebyly ádné obìti.
{7787}{7869}Mìlo by se moná dívat na druhoøadé vìci.
{7869}{7889}Hannah...
{7900}{7942}Moc pøemıšlíš!
{7942}{8005}Foundation si toho pravdìpodobnì jen nevšimla.
{8005}{8075}Ne! Vidìla jsem to na vlastní oèi!
{8075}{8143}Ok, ok! Netvaø se tak na mì!
{8187}{8214}Oh, vím!
{8214}{8288}Našla jsem tady úasnı butik, jestli chcete-
{8288}{8320}Poslouchejte mì!
{8369}{8461}Øíkáte to, protoe ignorujete veškerou pravdu.
{8494}{8528}Ignorujeme pravdu?
{8528}{8580}Kdo ji ignoruje?!
{8594}{8610}Sally...
{8625}{8737}Máš své speciální schopnosti a Orb Hunters tì stále hlídají!
{8772}{8859}Ale co máme dìlat my, kdy náš napadne Thanatos?
{8871}{8938}Je snad nìco špatného spoléhat se na Jinx?
{8938}{8959}Sally!
{9098}{9150}Ange, prosím pochop.
{9165}{9259}Jestli se objeví Thanatos, tak je s námi konec.
{9259}{9339}Nejsme jiné jako ty, Ange.
{9409}{9429}Rozumím...
{9471}{9487}Ange!
{9611}{9657}Proè tomu nerozumí?!
{9657}{9715}Øekla jsem jim pravdu!
{9772}{9905}Hej, je tu nìkdo, kdo by mi pomohl?
{9961}{9974}Tady je.
{10095}{10153}Hej, mùj malı poklade!
{10199}{10301}Ahoj! Musí to bıt osud, e jsme se tu potkali.
{10301}{10388}Moná jsme pøedurèení jeden druhému.
{10408}{10471}Eh... nemám náladu na interview.
{10471}{10525}Eh? Pláèeš.
{10540}{10582}Pohádala jsi se s pøítelem?
{10734}{10797}Rozveselím tì!
{10797}{10887}Omlouvám se, ale nechte mì na pokoji.
{10887}{10920}Nemùu.
{10975}{11068}Nemùu nechat plaèící dívku samotnou.
{11244}{11265}Eh...
{11265}{11351}Neboj se! Vybral jsem to sám!
{11351}{11415}Budeš vypadat dobøe!
{11415}{11431}Ale...
{11598}{11628}Není to špatné.
{11643}{11712}Kdy máš dobrou postavu, sluší ti všechno.
{11712}{11740}Nemám...
{11740}{11797}Take teï...
{11839}{11908}Kdy si pøedstavíš tajné rande, pøedstav si...
{12140}{12200}To je poprvé, co jsi v tomhle mìstì?
{12200}{12220}Ano.
{12220}{12344}Ne jsem odjela do Sunlit Mansion, nikdy jsem neopustila akademii.
{12344}{12373}Pøestaò!
{12384}{12486}Tenhle druh konverzace není vhodnı pro tohle místo.
{12506}{12519}Ale...
{12540}{12561}Dobøe?
{12561}{12635}Kdyby nìkdo zjistil, e jsi Queen's Egg, byl by to obrovskı rozruch.
{12726}{12812}Tak, zkus mluvit víc uvolnìnì.
{12891}{12914}Ah, to je Roche!
{12914}{12943}Roche!
{12943}{12986}Vyfo mì, Roche!
{12986}{13015}Nemoné.
{13015}{13090}Pøedtím jsem vám øekl, e dìlám fotky jen za peníze.
{13090}{13134}Lakomec!
{13134}{13208}Oh, nová pøítelkynì?
{13208}{13272}Opravdu odlišná od ostatních.
{13304}{13415}Neøíkejte takové vìci! Stále ji svádím!
{13415}{13485}Sleèno, dovolte, abych vám dal radu...
{13485}{13532}Jestli jdete na rande s kadım, tak pojïte radìji se mnou.
{13556}{13662}Øeknu o tom tvé manelce.
{13662}{13705}Nic takového!
{13739}{13795}Znáte všechny z trhu?
{13795}{13820}Prakticky.
{13820}{13869}Je to jako velká zahrada.
{14044}{14085}Roche je mùj!
{14161}{14203}I malé holèièky...
{14244}{14291}Ne! Není to, jak si myslíš!
{15302}{15336}Co myslíš?
{15336}{15431}Vsadím se, e to byla vzrušující zkušenost pro princeznu, jako jsi ty.
{15431}{15478}Musel jste s tím poèítat...
{15478}{15524}A nejsem ádná princezna.
{15533}{15562}To je pravda...
{15562}{15608}Vmísila jsi se dobøe.
{15608}{15652}Mohla bych tu bez problému ít.
{15666}{15691}To je pravda.
{15725}{15817}To jsem já. Nejsem nikdo zvláštní.
{15854}{15939}Všem v Sunlit Mansion o dnešku øeknu.
{15955}{16069}Øeknu jim, e jsou tu lidé, kteøí nejsou vystrašení |z Thanatosù. Lidé, kteøí odvánì ijí své ivoty.
{16114}{16166}O èem to mluvíš?
{16216}{16240}Nìco ti ukáu.
{16303}{16334}Poèkejte!
{16549}{16633}Tohle mìsto bylo napadeno Thanatosi.
{16818}{16925}Bylo to tu pøecpané. Nebylo kde utéct, |tak jsou tu škody horší, ne jinde.
{17049}{17119}Pamatuješ si je, e?
{17119}{17153}Jsou to všechno sirotci.
{17153}{17181}Sirotci...
{17197}{17279}Jejich rodièe byli zabiti Thanatosi.
{17279}{17301}Ne...
{17313}{17375}"Ale všichni jsou tak šastní!" øekneš.
{17431}{17552}Ztratili rodièe. Kdyby nenasadili šastné vırazy, nemìli by kam jít.
{17574}{17695}A ti staøí mui a eny, s kterımi jsi mluvila... Všichni ztratili pøátelé a rodinu.
{17717}{17782}Není to tu tak vzácné.
{17925}{17950}To je...
{17964}{18016}Ano. Tohle udìlala Jinx.
{18016}{18038}Jinx?
{18434}{18516}Nemohli by v tìchto podmínkách pøeít.
{18545}{18594}Spoléhají na své pøátele a pøíbuzné, aby nalezli nìco k bydlení.
{18670}{18685}To je strašné...
{18717}{18743}Ne, opravdu.
{18787}{18843}Nakonec, stále ijí.
{18877}{18992}Kadı tu dìlá všechno, co mùe kadı den...
{19013}{19134}Ale dokud ijeme, mùeme pøestavìt naše mìsto, i kdy ho Jinx znièila.
{19155}{19232}Ale jestli nás dostane Thanatos, tak je konec.
{19232}{19398}Ale jestlie nás Queen's Egg zachrání, kdy |se objeví Thanatos, tak to bude jiné.
{19453}{19540}Ale co máme dìlat, kdy nás napadne Thanatos?
{19549}{19610}Je snad nìco špatného spoléhat se na Jinx?
{19661}{19702}Sally má pravdu.
{19723}{19777}Všechno ignuruju.
{19777}{19899}Lidé mùou soudit na základì vlastních zkušeností.
{19899}{19975}Nevím nic o svìtì, ve kterém iješ.
{20103}{20212}Ale nakonec, mùeme ít jak chceme.
{20212}{20311}Já i ty.
{20394}{20409}Roche...
{20450}{20529}Øekl jsem nìco cool?
{20529}{20573}Jsem tak cool nebo co?
{20646}{20700}Sakra... Zkazil jsi to!
{20865}{20894}Nebuï hloupı!
{20932}{20985}Vy jste znièili mùj obchod, ne?
{20985}{21071}S touhle almunou ho znovu nepostavím!
{21166}{21221}Nikdo neøíká, e to bylo na rekonstrukci.
{21221}{21296}S tìmito penìzi si's mìl najít nové bydlení.
{21316}{21342}Co to øíkáte?
{21342}{21409}Nebuï tak chamtivı.
{21409}{21516}Aha, snaíš se získat víc penìz... Ale my nejsme kupující.
{21543}{21608}Nemùu uvìøit, e by mohli navrhovat takovou vìc!
{21608}{21632}Poèkej!
{21632}{21680}Co chceš dìlat?
{21697}{21732}Dám jim lekci!
{21750}{21808}To jen proto, e jsi øíkala, e všechno ignoruješ.
{21808}{21839}Ale...
{21839}{21863}Podívej.
{21863}{21921}Ukáu ti, jak se to dìlá.
{22011}{22045}P-Poèkejte!
{22045}{22162}Jen trochu víc, abych mohl znovu zaèít v malém obchodì.
{22180}{22199}Jsi otravnı!
{22295}{22355}Oh, to je terno!
{22413}{22536}Nazvu to "Èlenové Foundation dávají koneènı úder obìtem bez penìz"!
{22553}{22589}Zavøi hubu!
{22589}{22611}Kdo jsi?
{22654}{22674}Ups!
{22708}{22731}Au!
{22731}{22751}Co to dìláš?
{22751}{22815}Bolí mì to, jen na to myslím...
{22857}{22936}Co se stane, kdy to dám na první stranu.
{22959}{23042}Take, kolik jste ochotnı vyklopit?
{23333}{23385}Oh, to je štìstí!
{23385}{23446}Musí bıt skvìlé bıt v tak velké spoleènosti.
{23522}{23534}Dìkuju!
{23534}{23564}Hej!
{23625}{23648}Neøáde!
{23666}{23708}Díky za kompliment!
{23785}{23818}Jste v poøádku, pane?
{23818}{23890}Ano... Obchod je špína.
{23935}{24020}Nemùete zavøít obchod.
{24020}{24114}Nedokáu si pøedstavit, e bych nezaèal den vaším espressem.
{24126}{24212}Bylo by tøeba, abyste mi za všechny zaplatil.
{24238}{24280}Nemyslete na to, nemìl jsem tolik.
{24280}{24322}Tak dobøe...
{24383}{24421}H-Hej!
{24421}{24460}To je dobrá pøíleitost.
{24460}{24493}Mìlo by se to splatit.
{24585}{24640}Nevypadáš spokojenì.
{24640}{24673}To proto...
{24797}{24834}Aha.
{24834}{24921}Tedy tvoje metoda dìlání vìcí, je jako od malé holèièky.
{24963}{25062}Myslím si, e je špatné vydírat lidi.
{25062}{25078}Ale...
{25113}{25160}pokud to pomùe...
{25160}{25249}Mám taky jeden špatnı nápad.
{25249}{25277}Zamilovala jsi se do mì?
{25277}{25297}Ne!
{25315}{25388}Dobøe, ale jednou budeš.
{25611}{25623}Ehm...
{25650}{25678}Dìkuju za všechno.
{25693}{25734}Hodnì jste mi pomohl.
{25734}{25804}Ale opravdu... To nebylo to, co jsem chtìl...
{25820}{25937}Stále nejsem moc dùvìøivá, ale budu následovat cestu v kterou vìøím.
{25979}{26015}A jaká cesta to je?
{26027}{26083}Stanu se Královnou co nejdøív budu moct.
{26083}{26251}Jestli se tak stane, lidé u se nebudou muset bát |útokù Thanatosù ani toho, e jim Jinx znièí majetek.
{26378}{26404}Ange!
{26452}{26474}Ange!
{26729}{26755}Mìj se.
{26855}{26872}Ange...
{27060}{27082}Ange!
{27112}{27168}Všude jsme tì hledaly!
{27191}{27239}Omlouvám se!
{27676}{27727}Angelique?
{27727}{27760}Jo!
{27760}{27802}Co je s Queen's Egg?
{27815}{27879}Co jsi mi pøišel prodat dneska?
{27879}{27914}Ah, nic dùleitého.
{27914}{27987}V kadém pøípadì, píšeš zprávu o Queen's Egg?
{28023}{28092}Jo... Dozvìdìl jsem se to, kdy jsem zkoumal Orb Hunters.
{28105}{28148}Vypadá to, e je sirotek.
{28162}{28181}Sirotek?
{28194}{28250}Je to jisté?
{28250}{28308}Mám to od spolehlivého zdroje.
{28326}{28350}Aha...
{28370}{28439}Myslel jsem si, e je to nóbl, rozmazlená sleèinka.
{28439}{28481}Ale je stejná jako já.
{28532}{28572}Tvùj vıraz naznaèuje, e tì nìco obtìuje.
{28587}{28621}Mì? Obtìuje?
{28646}{28670}Máš pravdu.
{28694}{28746}Cítím se jako...
{28814}{28882}Oh... Pøišel jsi mi nìco prodat?
{28897}{28932}Co je na tom filmu?
{28932}{28992}Ale nic...
{29014}{29067}Jen jsem se zastavil, abych tì pozdravil.
{29103}{29124}Mìj se!
{29269}{29309}Ty jsou ze vèerejška...
{29309}{29352}Ano, byly ve schránce.
{29367}{29395}Kdy je...
{29395}{29456}Jak je udìlal?
{29471}{29624}Øíkal jsem, e z Angelique nevytìí, ne?
{29660}{29746}Tím myslíte, e mì podporuje?
{29782}{29844}Aaaa, všechny ty fotky jsou tak roztomilé.
{29858}{29903}Zvláštì tahle.
{29933}{30021}Sakra... Neklesla ti trochu ostraitost?
{30436}{30574}Nikdy jsem si nevzal obrázky, které mi nevydìlaly peníze,| ale ne jsem si to uvìdomil, tenhle jsem si vzal.
{30588}{30651}Jak dlouho u jsem nedìlal fotky, které jsem nemohl prodat?
{30724}{30804}Proè... To nejsem já!
{31010}{31071}Silvert Tree je nedoèkavı.
{31089}{31156}Mùeš ho slyšet, René?
{31170}{31201}Starší øíkali...
{31225}{31287}e nastal èas.... Pro mì.
{31344}{31371}Aha.
{32007}{32103}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32157}{32236}www.mycolorfullife.blog.cz
