{1}{1}23.976
{407}{429}Angelique!
{600}{639}Byla unesena!
{800}{820}Ange!
{841}{860}J.D.-san!
{1244}{1256}Ange!
{1556}{1568}J.D.-san!
{1604}{1619}Ange!
{1640}{1661}Ange!
{2013}{2067}TaSHee's Gang uvádí
{2231}{2290}NEO ANGELIQUE ABYSS
{4426}{4480}UVÌZNÌNÁ ANGELIQUE
{4771}{4801}Proè jste mì unesl?
{4859}{4900}Proè musíte všem ubliovat?
{4919}{5007}Vy a J.D.-san jste jako bratøi, ne?
{5007}{5033}Bratøi?
{5046}{5066}Ano...
{5066}{5148}Jste oba artefakty.
{5148}{5197}Originál je vadnı.
{5211}{5263}Døíve nebo pozdìji zaène selhávat.
{5276}{5318}To není pravda! J.D.-san je...
{5469}{5532}Do mìsta pøijedeme za 3 minuty a 17 vteøin.
{5532}{5556}Zùstaò potichu.
{5833}{5853}Co to dìláš?
{5905}{5952}Jste zranìnı.
{6092}{6143}Dìláš zvláštní vìci.
{6363}{6396}Pharian?!
{6410}{6447}Jsi si jistı?
{6447}{6501}Angelique je v Pharianu?
{6501}{6516}Ano.
{6532}{6692}Prohledal jsem rùzné dokumenty, ale Foundation HQ| je jediné místo s autem takového typu.
{6704}{6741}Foundation HQ?
{6769}{6806}Yorgo by nemohl...
{6820}{6936}Ne. ten byl teï nìkolik dní na kongrese øešit problémy s Jinx.
{6950}{7039}Byl to pravdìpodobnì nesouvisející èin uskuteènìnı individuálnì.
{7039}{7068}Je to tak?
{7124}{7207}Dobøe, nechej to na nás.
{7207}{7266}Omlouvám se, Rayne.
{7287}{7350}Momentálnì nemùu udìlat víc.
{7363}{7418}Postarejte se o Angelique.
{7418}{7435}Ano.
{7754}{7769}To je...
{7793}{7825}medailon Angelique...
{7917}{7946}Koneènì rozumím.
{7970}{8038}Musím ti øíct nìdo dùleitého.
{8103}{8172}Buï v bezpeèí, Ange.
{8377}{8567}Bez Yorga je tam jediná osoba, která umí ovládat |Jasper Doll nebo dávat pøíkazy.
{8567}{8591}Je to Erenfried.
{8603}{8678}Proè by takové dítì tak moc chtìlo Angelique?
{8678}{8764}Panikaøí, protoe Jinx nepøestává prohrávat.
{8764}{8876}Pravdìpodobnì zkouší vyuít schopnosti Angelique, aby posílil Jinx.
{8890}{8930}Bezmyšlenkovitì zkouší všechny monosti.
{8943}{9007}Ale, ale. Jak problematické dítì!
{9034}{9118}Pravdìpodobnì ví, e pøijdeme, tak pøipravuje léèku.
{9132}{9165}Riskuje pro to všechno.
{9165}{9216}Pravdìpodobnì udìlá všechno proto, aby nás dostal.
{9216}{9295}Ale jestlie teï odejdeme, pøijdeme do Pharianu za soumraku.
{9305}{9455}Take budeme mít perfektní jevištì pro záchranu princezny od zlosynù.
{9495}{9531}Co se dìje, J.D.?
{9555}{9696}Vzpomínám na èas, kterı jsem strávil s Ange v Sunlit Mansion.
{9708}{9816}Všechno co mùu udìlat je, pamatovat si ty èasy.
{9816}{9862}Je to opravdu smutné...
{9888}{9998}Kdy tam byla Ange... s námi... v Sunlit Mansion.
{10011}{10096}V urèitém okamiku, kterı se stal pøirozenım.
{10096}{10136}Obnovíme to!
{10150}{10199}Teplé svìtlo, které kolem záøí...
{10212}{10250}I kdy mì to bude stát ivot!
{10262}{10414}Pøesnì tak, kdyby jeden z nás zemøel, ty èasy u se nikdy nevrátí.
{10437}{10461}Vrátíme se!
{10461}{10538}S ní... do Sunlit Mansion!
{10551}{10582}Do našeho domova!
{10751}{10773}Kde to jsem?
{10969}{11026}Vítej ve Foundation.
{11124}{11188}Omlouvám se za hrubé zacházení.
{11188}{11278}Vìdìl jsem, e bys nepøijela,|kdybych nebyl takhle èilı.
{11278}{11305}Nechte mì jít!
{11305}{11353}Nechte mì jít... prosím!
{11370}{11407}Nemáš to ráda?
{11407}{11503}Toto je speciální idle vyvinutá pro uívání Queen's Egg
{11562}{11699}To jsou nejlepší nástroje. Jeden koneènì dokonèí mé zkoumání.
{11734}{11814}Queen's Egg, která oèišuje Thanatose...
{11814}{11943}Jestlie pøenesu tvé schopnosti do Jinx, bude schopná oèišovat Thanatose.
{11965}{12018}Pomùeš mi, e?
{12049}{12130}Nesouhlasím s tvımi metodami.
{12130}{12248}Nièíš domy, mìsta i lidi,  jen abys zneškodnil Thanatose.
{12334}{12464}Dokud budeš Jinx pouívat takto, odmítám ti pomoct!
{12464}{12514}Tak to je tvoje odpovìï?
{12532}{12641}Dobøe... co jiného navrhuješ?
{12641}{12744}Všechno co dìlám, je nejlepší monı postup.
{12744}{12842}Ale právì teï lidé kvùli Jinx trpí...
{12857}{12905}Moje Jinx jsou perfektní!
{12905}{12997}Jen je nemùu zmodifikovat, aby odpovídaly Thanatosùm.
{12997}{13079}Jednou se vyrovnám øediteli Yorgovi!
{13099}{13155}To proto potøebuju tvé schopnosti.
{13155}{13234}Jediná obì mùe zachránit svìt!
{13259}{13280}Obì?
{13455}{13582}To je pravda. Vznešená obì je nutná ve jménu vìdy.
{13597}{13709}Je to pro záchranu svìta, take jsem si jistı, |e jsi nadšená, Queen's Egg, e?
{13709}{13811}Vaše doporuèení není pro záchranu svìta.
{13811}{13845}Je to pro vaši záchranu!
{13845}{13867}Coe?
{13867}{13972}Rayne mi øekl, e jste stejnı jako bıval on.
{13972}{14045}Jste posedlı svımi vızkumy a zaèínáte bıt zaslepenı.
{14074}{14171}Ale jednou, si Rayne uvìdomil, jak špatné vìci dìlá.
{14171}{14218}Chce, abyste si to taky uvìdomil...
{14233}{14264}To staèí! Zavøi hubu!
{14282}{14315}Zaèínám s vızkumem.
{14332}{14413}Jete, umísti zaøízení na zkoumanı pøedmìt.
{14431}{14459}Rozkaz.
{14459}{14509}Umisuji zaøízení na zkoumanı pøedmìt.
{14588}{14639}Poèkejte, Jete-san!
{14670}{14705}Zùstaò v klidu.
{14969}{15015}Dobrou noc...
{15036}{15065}Angelique.
{15398}{15500}Úspìšnì vyuiju tvá data!
{15762}{15791}Jsou tu...
{15815}{15887}Necítím svého bratra...
{15887}{15921}Musím bojovat.
{15921}{15984}Tak nás èekají, e?
{15997}{16079}Nezáleí na tom, co se stane, naše rozhodnutí nesmí zakolísat.
{16079}{16173}Smìøujeme do místnosti, kde je drena Angelique.
{16253}{16333}Tak to ukonèíme, Rayne.
{16419}{16436}Rayne...
{16958}{16988}Èekal jsem vás.
{16988}{17036}Orb Hunters.
{17171}{17317}Poøídil jsem si lepší Jinx, aby vás pøivítala!
{17317}{17379}Take nás opravdu èekal!
{17379}{17438}Vezmeme si zpìt naši princeznu!
{17477}{17517}Jdìte!
{17896}{17924}Ochráním tì...
{17954}{17975}J.D.-san!
{18130}{18173}Nezáleí na tom, kde jsi...
{18198}{18225}Rayne!
{18388}{18433}I kdybych mìl poloit ivot...
{18456}{18481}Nyxi-san!
{18612}{18653}Ochráníme vás!
{18682}{18703}Hyuugo-san!
{19124}{19152}Jete!
{19168}{19216}Jsi vadnı!
{19628}{19650}Pøestaòte!
{19928}{19942}Jete!
{19958}{19986}Zastavím tì!
{20155}{20217}Neubliujte...
{20331}{20377}To je konec.
{20453}{20488}lidem pro mì dùleitım!
{20732}{20772}Co to... je?
{20975}{21029}To svìtlo je... Angelique!
{21041}{21103}Cítím její vøelost.
{21103}{21156}Svìtlo naplnìné láskou.
{21267}{21305}Opravdu jsi...
{21883}{21910}Promiò!
{22585}{22637}Vzdej to, Erenfriede!
{22652}{22716}U ti nedovolím Angelique ublíit!
{22769}{22792}Ještì není konec!
{22811}{22841}Vstaò, Jete!
{22853}{22866}Jete!
{22866}{22913}Co se dìje, Jete?!
{22973}{22994}Dost.
{23076}{23089}Yorgo!
{23127}{23149} Øeditel Yorgo...
{23182}{23198}To je...
{23233}{23253}Dost.
{23301}{23386}Dostal jsem zprávu o tvıch èinech.
{23406}{23501}Ignoroval jsi pøíkaz zastavit vırobu Jinx.
{23501}{23568}Pøikázal jsi vıpad bez mého svolení.
{23568}{23631}Skrıval jsi škody zpùsobené tou operací.
{23669}{23767}A teï... co jsi to pøede mnou zkoušel skrıt?
{23767}{23830}Já... já...
{23834}{23861}Pro Foundation!
{23926}{23957}Idiote.
{24488}{24511}Pøátelé!
{24625}{24699}Jsem rád, e se znovu vidíme.
{24699}{24829}Bolest doèasného odlouèení je jen zaèátek šastného shledání.
{24829}{24917}Zdá se, e zaèátek dnešního veèera byl trochu delší, ne se plánovalo.
{24917}{24971}Tvùj hlas nás k tobì zavolal.
{24971}{25056}Hlas dávající vìtší odvahu, ne nejlepší schopnosti.
{25056}{25182}Nikdy vám nedovolím jít znovu cestou utrpení, |i kdyby mì to mìlo stát ivot.
{25182}{25303}Také jsem slyšela vaše hlasy.
{25303}{25402}Ale nezáleelo na tom, jak blízko znìly, nemohla jsem za vámi utéct.
{25402}{25469}To proto, e jsme byli tady.
{25489}{25513}Dìkuju!
{25618}{25666}Taky jsi pøišel, Erwine?
{25753}{25809}Co chceš, Yorgo?
{25809}{25903}Foundation vzala veškerou zodpovìdnost za tento incident.
{25903}{25993}V nadcházejících dnech se znovu omluvíme.
{25993}{26027}Yorgo-san...
{26027}{26068}Pojïme, Angelique.
{26105}{26166}Potøebuju s tebou mluvit, Rayne.
{26206}{26263}Musí to bıt hned?
{26344}{26456}Aha. Situace je vánìjší, ne jsem si myslel.
{26456}{26627}Podle našich vızkumù, i kdy budou Silver Tree Knights |schopni Thanatosy zadrovat, jejich síla stále vzrùstá.
{26627}{26717}Co zamıšlíš tím, e jsi mi to øekl?
{26716}{26763}Jsem si jistı, e si's uvìdomil...
{26801}{26905}skryté monosti ve svìtle Queen's Egg.
{26905}{27050}Teoreticky je moné pøenést její Svìtlo Oèisty na Jinx.
{27085}{27202}Ne. Pro její tìlo by to bylo velké napìtí.
{27202}{27268}V této situaci je to jedinı zpùsob!
{27268}{27302}Rozumíš?
{27302}{27371}Rozumím, ale je to pro mì nemoné!
{27447}{27459}Rayne!
{27566}{27617}Nech mì o tom pøemıšlet tuto noc.
{27906}{27917}Rayne!
{27934}{27946}Hej!
{27946}{27991}Co øíkal Yorgo-san?
{27991}{28042}Nic dùleitého.
{28042}{28120}Poèkej! Chci se tì na nìco zeptat!
{28253}{28402}Erenfried-san øíkal, e je moné vyuít mé svìtlo k záchranì svìta.
{28450}{28563}To je nemoné. Tato metoda je moc nebezpeèná.
{28581}{28653}Ale já jsem pøemıšlela o tom co øíkal...
{28653}{28767}"Bylo by to moné, kdyby mi Rayne pomohl?"
{28825}{28940}K-Kdyby to bylo moné, co bych mì dìlat?
{28955}{29131}Bála bych se. Potøebovala bych hodnì odvahy, |ale kdybych takhle mohla zachránit lidi...
{29214}{29239}Rayne?
{29239}{29335}Nchci tímto zpùsobem zachraòovat lidi.
{29335}{29434}Nemùu tì dostat do takového nebezpeèí.
{29472}{29587}Ale jako vìdec... Nemùu popírat Yorgovu hypotézu.
{29637}{29764}Podle nìj, nebudou moct Silver Tree Knights |dlouho Thanatose zadrovat.
{29809}{29944}Jestlie se nic neudìlá, moná pøijde den, |kdy na této planetì u nebude ádnı ivot.
{29972}{30060}Proto navrhuje plán.
{30099}{30144}A ten plán je?
{30162}{30214}Vyuít tvé schopnosti.
{30214}{30306}Kdyby to šlo dobøe, mohli bychom definitivnì zneškodnit Thanatose.
{30321}{30445}Ale kdyby se operace protáhla, mohlo by to mít znaèné napìtí na tvé tìlo.
{30465}{30532}A mohla bych zemøít.
{30553}{30577}Je to tak?
{30616}{30680}Dokud jsem tady, nenechám tì zemøít!
{30694}{30745}Musíme se všichni vrátit do Sunlit Mansion!
{30808}{30866}Ale... mùeš to ukonèit, kdykoli budeš chtít.
{30883}{31005}Je to nefér øíct, ale potøebuju tvé rozhodnutí, Ange.
{31175}{31192}Já...
{31257}{31323}chci bıt s mımi pøáteli v Sunlit Mansion!
{31346}{31362}Ale...
{31393}{31461}Ale jestlie nic neudìláme, Sunlit Mansion bude jednou...
{31548}{31637}Jestlie to moje schopnosti mùou zastavit...
{31656}{31672}Potom já...
{32001}{32096}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32148}{32255}www.mycolorfullife.blog.cz
