{1}{1}23.976 Èasováno pro asijské verze, napø. Echizen rip
{1855}{1942}ÈAS
{1993}{2052}Poøád si pamatuju své první zatèení.
{2110}{2170}Bylo to 12. prosince 1980.
{2260}{2334}Já a mùj parák jsme hlídali Hano Road.
{2337}{2461}Tam v New World Center se nic nedìlo.|Teda skoro nic.
{2477}{2547}Strhla se tam rvaèka mezi gangy.|Kdy jsme pøišli,
{2550}{2632}asi patnáct u jich leelo na zemi.
{2651}{2696}Bylo tam spousta krve.
{2729}{2785}A useknuté ruce, svírající noe.
{2918}{3068}Parák mi øekl, a udìlám, co myslím.|No a já to udìlal.
{3103}{3228}Ale ne jsem staèil vytáhnout zbraò,|tak parák padl. Byl mrtvej.
{3263}{3358}Jeden fracek mu vrazil trubku pøímo do bøicha.
{3394}{3462}Zaèala z nìj strašnì cákat krev.
{3507}{3562}Nevìdìl jsem, co mám dìlat.
{3565}{3648}A tak jsem napumpoval všech šest nábojù|do toho fracka!
{3723}{3783}Ale nezabil jsem ho, bohuel.
{3827}{3932}Pak jsem ho potkal, asi za dva roky v klubu,|díval se na mì strašnì.
{3937}{4031}A jeho kamarádi byli Kwanovi najatí zabijáci!
{4039}{4095}Ïábel zvítìzil.
{4183}{4286}U si ani nevzpomínám,|jak mùj parák vypadal.
{4455}{4580}Jenom lituju toho, e jsem tìch šest nábojù
{4602}{4677}nenapálil tomu frackovi do lebky.
{4830}{4886}Svìt je pøíšernı.
{4914}{4965}Takhle to dál nejde, Same.
{5141}{5181}Jak dlouho jsi tady?
{5216}{5268}Asi dva roky.
{5316}{5383}Jestlipak víš, proè jsem s tebou nezatoèil?
{5404}{5455}Protoe jsem úasnı.
{5474}{5518}Moná proto.
{5544}{5596}A protoe seš slušnej chlap.
{5658}{5753}Ale mìl bys bıt daleko víc zodpovìdnìjší.
{5756}{5846}Na to zapomeò.|Nemohl jsi ho minout šesti kulkama.
{5853}{5900}To z tebe taky dìlá slušòáka, ne?
{5912}{6005}Jenome tím já u nechci bıt.
{6187}{6259}Kwan mi dal všechno, dokonce i mùj ivot.
{6280}{6419}Kdybych se otoèil proti nìmu,|byl bych v tvıch oèích opovreníhodnı, e jo?
{6484}{6556}- Jo, vìdìl jsem, e to øekneš.|- No, vdy mì znáš.
{6593}{6673}Chivalry pro Ngaiovu rodinu moc neznamená.
{6824}{6951}Pán vdycky øíká, odplata má svùj èas.
{7007}{7097}Kdo ví, jak ty a já skonèíme?
{7188}{7232}Do práce!
{7241}{7345}- Coe, tak brzy?|- Musím jíst! No, a moji kluci taky.
{7352}{7392}Vem jim klidnì to moje.
{7396}{7458}- Nechám to tady.|- No, tak jo.
{7515}{7558}- Ahoj.
{7578}{7625}Poèkej!
{7678}{7718}Nechceš jít zadním vchodem?
{7735}{7805}Na to jsou novı pravidla,|kdy si chci pokecat s poldou?
{7825}{7885}Pøední vchod staèí.|Zvykl jsem si na to.
{8275}{8317}Pretova ulice.
{8824}{8874}Pretova ulice.
{11008}{11040}- Je tady strıèek Kwan?
{11080}{11133}Strıèku Kwane, nìkdo tì hledá.
{12035}{12276}VOLAVKA 2
{12490}{12545}Ahoj, Mary.
{12881}{13019}Øíká se, e Amerièanky mají krásné vıšky,|ostré støední tóny a silné basy.
{13045}{13181}To jsou kecy! Sto osmdesát tácù!|Kdo si to v Hong Kongu dovolí?
{13208}{13258}Sedni si.
{13394}{13442}Dovolí si to jen deset tisíc lidí.
{13461}{13579}Sam chce, abys byl špionem.|Jestli nechceš, øekni mu to.
{13647}{13686}Chci.
{13704}{13756}Urèitì?
{13771}{13815}Jasnì.
{13869}{13925}Podej mi tu tašku.
{13993}{14037}Mary.
{14068}{14159}Promiò, myslela jsem, e se toho bojíš.
{14186}{14265}Schovej se v Thuen Mun,|ne se vìci uklidní.
{14268}{14342}Poèkáš si na novı termín akademie.
{14396}{14471}Peníze, co máš, utrácej rozumnì.
{14551}{14608}Líbí se ti to?
{14631}{14678}Jo.
{14793}{14897}Je tvoje. Na jiném pøehrávaèi|tak dobøe hrát nebude.
{14928}{14986}Nìkdy ti vyberu nìjaké jiné.
{15039}{15105}Co je? Nechceš ho?
{15138}{15219}Ale jo. Tyhle hodinky ti dal Sam?
{15229}{15279}Neptej se.
{15426}{15560}Jenom ty a já víme o dnešní noci.|Sam se to nesmí dozvìdìt.
{15590}{15635}A proè ne?
{15652}{15717}eny jsou velmi jednoduché.
{15719}{15820}Dokud je mu hodnı,|udìlají pro nìj cokoliv.
{15888}{15981}- Jdi domù. Mám moc práce.|- Ano.
{16249}{16373}Buï ty, nebo já. Mùj šéf øekl,|dneska uvidím téct krev.
{16388}{16537}A ten divnej chlápek se poøád ptal,|seenete na veèer mercedes, Keungu?
{16547}{16687}A já jsem øekl, no jistì. A šel jsem na to.|Vyhlídl jsem si krásnej mercedes.
{16712}{16821}No a takhle jsem dopadl.|Visím na plotì.
{16834}{16931}Jinak bych se tady s tebou nebavil.|Ani s touhle dámou. To je teda jistı.
{17063}{17133}Hele, nemáš cigaretu?
{17155}{17205}Nekouøím.
{17549}{17602}Zapomeòme na to.
{17606}{17679}- Moje auto je v poøádku.
{17705}{17846}Je pìknì obleèená. Je vidìt,|e nechce ádnı problémy, e ne?
{17860}{17986}Koukni se na mì. Zbils mì.|Komu myslíš, e soudce uvìøí?
{17989}{18121}es nikdy nebyl ve vıchodní ètvrti?|Hele, víš, kdo jsem? Já jsem Keung!
{18128}{18195}Jsem Samovo nejvìtší zvíøe.
{18198}{18287}Del Pierùv kluk.|Nakopu ti prdel, kdy chci.
{18297}{18343}Tím si mùeš bejt jistej, poldo.
{18846}{18874}Co je?
{18878}{18971}A co takhle zavolat sanitku?|Kouknìte se na tu krev!
{18979}{19047}Ale a pøijedou hodnì rychle,|prosím, nebo umøu.
{19051}{19172}Dr hubu! Poèkej,|ne budeš na stanici. Vemte ho.
{19175}{19251}Poèkejte, pane! Proè bych mìl|chodit na stanici? Proè?
{19255}{19328}Ukradl jsem jen starej krám!
{19332}{19402}Nevíš, e jsi ještì kadet?
{19406}{19471}A mìl bys tento rok dostat medaili.
{19475}{19529}A se to Yip nedozví!
{19795}{19834}Veselé narozeniny!
{19837}{19941}Není dùvod k oslavì.|Deset let v akademii.
{19944}{19990}Spíš je to k pláèi.
{20047}{20150}Pomohl jsi mi odejít.|A ten tvùj pøípad u je pøece historie.
{20155}{20205}Tak odejdi taky, co ty na to?
{20260}{20389}No jo, ale co kdy bude komisaø Èíòan?|Poøád zbıvá šest let do pøedání!
{20400}{20450}To mi bude ètyøicet osm.
{20481}{20586}Budu vytrénovanı|jako ti nejlepší policajti tady!
{20617}{20708}Pøece tu šanci nezahodím.|No, tak co?
{20711}{20761}- Napijeme se! Na zdraví!|- Na zdraví!
{20788}{20915}Yane, co je? Pípá ti to celı den.|Proè nezavoláš zpátky? Pøítelkynì?
{20930}{20980}- Na zdraví, pane!|- Na zdraví!
{20984}{21087}Kdo to byl! Sakra, øekni, kdo to udìlal!|No kdo? Urèitì to víš!
{21200}{21287}Co je! Co se dìje?
{21344}{21399}Mùj otec dnes zemøel.
{21494}{21643}Pøál si, aby se jeho dìti dozvìdìly,|e se mu nìco stalo.
{21710}{21761}Promiòte, pánové.
{22294}{22347}Vykašli se na televizi a najez se.
{22350}{22457}Ale, zajímalo by mì,|co mají na Kwanovu smrt.
{22473}{22515}Udìlals to ty, Chingu?
{22541}{22623}Já jsem ukecanej. Kdybych to udìlal,|u bych ti to dávno øekl.
{22631}{22694}- Zeptej se Waha a Gandhiho.|- Co?
{22697}{22751}Kdy Kwan zemøel, byl jsem v Macau.
{22754}{22851}To ví všichni! Ale vsadím se,|e jeho dìcka obviòují mì.
{22878}{22943}Toho bych se nebál.|Nejstarší syn je doktor,
{22946}{23033}nejmladší je spratek|a dcera je u léta vdaná.
{23037}{23147}Ve høe je jen prostøední syn.|Jestli na to pùjdou rychle, tak jim ukáu!
{23178}{23230}Je to všechno jen naše chyba!
{23256}{23310}To staèí, strıèku Johne.
{23314}{23427}Táta øíkával, co má pøijít, pøijde.
{23442}{23527}Naštìstí to pøišlo pozdìji,|ne jsme èekali.
{23555}{23606}Wah, Ching, Negro a Gandhi.
{23628}{23688}Na copak asi ti ètyøi myslí?
{23781}{23831}Dìkuji. Na shledanou.
{23895}{23969}Jsem rád, e jste pøišli.|Co máma?
{23986}{24140}Spí. U je jí dobøe. Donesl bys tátovi|do márnice nìjaká cigára?
{24151}{24194}U jdu pro nì.
{24354}{24415}Tım B, sledujte ulici Tag Shing.
{24423}{24530}Tım C, sledujte na Austin Road vıchody z tìch|obchodních budov. Jsou tam dva vıchody.
{24540}{24660}Jeden je na ulici Tag Shing. Sleduje tım B.|A ten druhı je na Austin... Promiòte.
{24772}{24846}- Haló?|- Tak dùleitá zpráva, proè jsi nezavolal?
{24854}{24919}Volal jsem kadému hned,|jak se to stalo.
{24923}{25009}Kwanovi kluci nemùou klidnì spát.|Dneska v noci se bude nìco dít.
{25013}{25046}Je ètrnáctého, vìdìl jsi to?
{25050}{25141}Dnes je ètrnáctého.|Èas na odplatu pro Ngaiovu rodinu.
{25165}{25273}Jo. Jsem nejmladší,|take budu ten blbec.
{25283}{25405}U nikdy nebudu Ngaiovi platit.|Co si myslíte?
{25672}{25763}- Na zdraví. - Jasnì, na zdraví!|- Dobrej nápad.
{26695}{26772}- Wongu! Co se dìje?|- Co dìlají tví mui pøed Wahovım domem?
{26775}{26834}- Není vhodná doba na legraci.|- Zajímáš se o nìho?
{26837}{26886}- Teï ne, øeknu ti to jindy.|- Dobøe.
{26993}{27040}Copak tu slavíme?
{27068}{27121}No tak, kde sedím?
{27254}{27337}Pokud jste tady, aby jste se najedl.
{27338}{27430}- Všechno ostatní mùe poèkat.|- Všechno je o jídle. Co?
{27625}{27682}Dneska v noci to pøijde.
{27698}{27775}Velká ètyøka udìlá, co musí.|Vyvodíme dùsledky.
{27815}{27883}Nenech je bojovat.|Jinak uvidíš mrtvá tìla.
{27904}{27954}Co je? Nejsi spokojenı?
{27990}{28042}Znáš pravidla. Vyber si kartu.
{28073}{28129}Dobøe. Vyšší karta vyhrává.
{28451}{28527}Co mì otravuješ, nevidíš, e jíme?
{28571}{28610}Co se dìje, Hau?
{28613}{28729}Nic moc. Slyšel jsem, e plánuješ|v Macau kasino.
{28757}{28847}Mám tam vládu v kapse.|Co takhle spoleèná majetková úèast?
{28866}{28948}Strıèek Kwan je mrtvı.|Nemám na to náladu.
{29046}{29165}Chápu. Vılet do Macau, to není všechno.
{29199}{29275}Vím, e sis uíval s Gandhiho enou.
{29908}{30018}Promiòte, ale nemùu si to kasino nechat ujít.|Musím jít.
{30524}{30575}Co dìlají Samovi lidé?
{30589}{30638}Vím, e se Wah s nimi vyrovnal.
{30669}{30736}Nemìò téma.|Øekni mi nìco, co nevím.
{30799}{30848}Sakra, zavolej mi pozdìji.
{30888}{30978}Hele, Hau se o Waha postará|bìhem deseti minut.
{30981}{31071}Velká ètyøka proívá tìké období.
{31136}{31192}Hau si prı vybral velké mnoství penìz.
{31566}{31648}Copak? Mafie nás nepustí?
{31713}{31750}Uhni!
{31920}{32043}Já nevím, proè jim Wah zaplatil.|Ale já nebudu vyjednávat.
{32047}{32122}Já taky nechci vyjednávat. Dej mi Negra.
{32149}{32263}Hele, Negro, nemám tušení proè,|ale chce s tebou mluvit.
{32325}{32356}Co se dìje?
{32372}{32506}Urèitì budu s Gandhim.
{32541}{32607}Slyšel jsem,|e ty a Gandhi jste si blízcí.
{32612}{32702}Ten heroin, co jste vy dva pašovali,|nìkdo ukradl.
{32714}{32768}Kadı jste ztratili nìkolik milionù.
{32803}{32905}A já ho našel u tebe ve skladu.|Dáš mi k telefonu zase Gandhiho?
{32992}{33037}Hele, co øíká?
{33401}{33507}V rámci velké pìtky Tsim Sha Tsui,|Wah a Negro zaplatili.
{33535}{33659}Kdy poèítám Sama, je to tøi na dva.|Jsem tady nejmladší, musím zaplatit!
{33706}{33755}No, uvidíme se!
{33890}{33937}Nepøemıšlej tolik. Na zdraví.
{34108}{34187}Jo? Zapla mùj podíl!
{34300}{34366}Pan Ngai se šel najíst,|inspektore Wongu.
{35228}{35278}Trochu pozdì na jídlo, nemyslíš?
{35327}{35467}Mùj otec sem chodíval po práci.|Musím pøece udrovat jeho zvyky.
{35488}{35535}Nechceš se pøipojit, Wongu?
{35588}{35655}Teï u je to tvoje místo. Je to tìké?
{35668}{35690}Vùbec ne.
{35722}{35817}Za to vy jste dnes pracovali|a bylo to nanic. To je tìké.
{35875}{35960}Trefné. Vıbornì, to byl skvìlı vtip.
{35973}{36016}Otcovu smrt ustojíš.
{36026}{36097}Nedìlej z toho takovou tragédii.|Jdeme.
{36100}{36141}Co jsi to øíkal?
{36216}{36333}Jdeme zapít Kwanovu smrt.|Je èas bouchnout šampaòské, a oslavit to.
{36649}{36701}Mám ti jedno otevøít?
{36734}{36841}Co? Ty se chceš zaplést s poldou?
{36972}{37100}Ale, pánové! Ngaiovi lidé truchlí.|Co ještì chcete?
{37223}{37280}Jdeme. Odchod!
{37481}{37531}Same.
{37607}{37651}Sednìte si.
{37924}{37974}Otec øídil poulièní hazard.
{38009}{38122}Zaèínal tady obchody úplnì od píky.
{38154}{38226}A teï, kdo nezná jeho jméno?
{38470}{38586}Èasto nám øíkal, co má pøijít, pøijde.
{38622}{38683}A teï je...
{38843}{38894}Navdy si zapamatuju tenhle den.
{39958}{40045}- Co je? - Všechno je v poøádku, miláèku.|- Mám pøinést nìco k jídlu?
{40054}{40141}To ráda slyším. Pojï rychle domù.
{40350}{40467}Dobøe mì poslouchejte.|Policista musí mít èistı rejstøík.
{40502}{40647}I kdy jste zpøetrhal vazby s Ngaiovımi lidmi,|poøád máte s Hauem stejného otce.
{40675}{40756}To znamená, e jste ve své ádosti lhal.
{40759}{40810}Musím vás vyhodit.
{40824}{40926}Ale ne odejdete,|zajdìte ještì za vedoucím.
{41076}{41126}Poøád chceš bıt polda?
{41232}{41275}To bych mohl?
{41303}{41357}Jen, kdy mi øekneš dobrı dùvod.
{41447}{41492}Spravedlnost.
{42293}{42396}Jestli chceš bıt polda,|tak mi pomoz, to je všechno.
{42422}{42480}Vybral jsi mì, protoe jsem Haùv bratr, e?
{42533}{42595}A pøijde èas, zavøeš ho sám?
{42631}{42674}Kde mám zaèít?
{42730}{42805}Ticho! Dìlej, tak pojï!
{43155}{43209}To jsou vlasy!
{43416}{43440}Vyjdìte!
{43443}{43494}- Hele, my chceme taky ven!|- Dr hubu!
{43497}{43541}To je nespravedlivı.
{43631}{43714}- To vypadá na zabijaèku.|- Ticho!
{43946}{43992}Jsi v poøádku?
{44117}{44167}Vydr to tam.
{45005}{45101}Co je? Co se dìje?|Poøád to bolí?
{45139}{45276}Mùj otec dnes zemøel.|Byl na mì tak hodnej.
{45302}{45422}Zeptal jsem se stráce,|jestli mùu jít na jeho pohøeb.
{45470}{45534}Øek mil, víš, co to znamená,|bejt vìznìm?
{45539}{45698}To znamená, e nikam nesmíš,|ani na pohøeb svıho otce.
{45710}{45863}Nech mì! Vypadni!|Bì pryè!
{45956}{46009}No tak, pøestaò.
{46256}{46310}Nech toho.
{46379}{46442}No tak, slyšíš?
{46877}{46927}ÈAS
{47679}{47769}Zbláznil ses?|Poslal jsi Yana jako špiona?
{47774}{47833}Hau je jeho nevlastní bratr.
{47938}{47982}No a co?
{48027}{48062}Pøines jeho dokumenty!
{48211}{48263}Tak ty si teï hraješ na šéfa, jo?
{48292}{48390}Zatracenì dobøe víš,|e ty dokumenty jsou utajené.
{48448}{48530}Bral jsem tì jako svého bratra.
{49045}{49102}Jestli jsi bratr, pøestaò se ptát!
{50345}{50474}Co dìláš, co? Uklidni se!|Co se dìje? Co?
{50480}{50551}Šla na potrat!
{50564}{50645}To není tak hroznı.|Je to jenom dítì.
{50653}{50734}No tak, neblázni.|Vdycky mùeš mít další.
{50830}{50959}Byla jsem s tebou ètyøi roky.|A obìtovala ti spoustu èasu.
{50985}{51114}V jednu chvíli veèeøíme s našimi lidmi,|ale v zápìtí u bojuješ v nìjaké bitce gangù.
{51116}{51223}Nechci, aby naše dítì vyrùstalo jako ty,|copak to nechápeš?
{51878}{51942}Proè jsi tak podrádìnı?
{51952}{51994}Nejsem.
{52014}{52087}Strıèek John øíkal, e se ti daøí.
{52120}{52176}Nechceš mít s rodinou nic spoleèného?
{52248}{52318}Vím, e si chceš od rodiny udrovat odstup.
{52370}{52484}Ale jsme pokrevní bratøi,|to nezmìníš. To je fakt.
{52555}{52637}Tuhle nedìli má moje dcera narozeniny,|zvu tì na oslavu.
{52697}{52777}- Nerad se mnou mluvíš, co?|- Ano.
{52846}{52884}Nerad.
{53148}{53294}U seš povıšenej?|Za chvíli budeš policajt na plnı úvazek.
{53382}{53442}Sam kecá, no tak, usmìj se na mì.
{53507}{53570}Dìkuji, e jste se o mì ty dva roky tak starali.
{53595}{53690}Kdy jsi byl ještì zelenáè,|pomáhal jsem ti chytat nìjaké malé ryby.
{53693}{53804}Je èas, abys sám chytil nìjaké vìtší.|Co takhle chytnout mì?
{53816}{53930}Co takhle chytnout mì.|Nebo tøeba chytit tuhle dámu.
{53933}{53987}Nech toho, co to dìláš?
{53990}{54108}Ale, mamce se to nelíbí!|Tvùj mu musí bıt ten dobøe vypadající hajzl.
{54111}{54166}Jsi to ty, kdo jinı?
{54181}{54281}- Musím jít. - A proè?|- Mám schùzku s panem Ngaiem.
{54641}{54692}Sam je na tebe hodnı!
{54759}{54807}Ale není hodnı na sebe.
{54859}{54986}Ètyøi roky. U by mìl bıt ve vedení.
{55023}{55072}Ale dává všechno Ngaiovi.
{55149}{55307}A teï je Ngaiova rodina velká a zlá.|Hau to musel zjistit.
{55338}{55438}Ty ètyøi roky jsem nespala dobøe.
{55460}{55518}Jsem inspektor Wong.|Dobøe mì poslouchejte.
{55522}{55605}- Nedovolím, - Náš plán je následující.|- Aby se ti nìco stalo.
{55607}{55655}Nasazení tajní agenti|podávají dùvìrné informace.
{55662}{55740}- Samá slova. - Musíme ty agenty|chránit.
{55742}{55788}- Nejsou.
{56593}{56702}Uka, no tak. Podej mi to!
{56926}{56990}Pøed dvìma dny pøišel obchodník|s nemovitostmi.
{57013}{57135}Hádejte, kolik nabízel?|Sto šedesát. Sto šedesát milionù!
{57147}{57256}Co se s Hong Kongem dìje?|Kdy to mùj otec koupil,
{57266}{57380}stálo to devìt milionù dvìstì osmdesát tisíc.
{57386}{57429}Stìhujete se, pane Ngai?
{57432}{57519}Rok 1997 se blíí. Je èas emigrovat.
{57546}{57624}To není problém,|komunikace je dnes jednoduchá.
{57627}{57673}Staèí jeden telefonát a je to.
{57675}{57762}Jenom se bojím vysokıch úètu za telefon.
{57764}{57827}Telefonní spoleènosti jsou nenasytné.
{57865}{57999}Probíral jsem to s mámou. Všechny|naše obchody jsou na správné cestì.
{58032}{58091}Vy jste nám v minulosti hodnì pomohli.
{58128}{58195}A já k vám nechci bıt nevdìènı.
{58203}{58315}Chci se s vámi o ty obchody rozdìlit.|Berte to jako dárek,
{58317}{58431}nebo dùchodovı pøíspìvek,|nebo nìco takového.
{58502}{58628}- Díky. - Dejte si tøeba doutník!|Vezmìte si cokoliv chcete!
{58630}{58683}Mìli bychom se takhle flákat èastìji.
{58859}{58948}Pane Ngai. Vy odcházíte?
{59053}{59104}Jestli odejdete, rozpoutá se tady peklo!
{59104}{59154}Ty jsi buddhista, e?
{59203}{59252}Je lehké zaèít, ale tìké toho nechat.
{59282}{59337}A já toho nechávám.
{59408}{59523}Pøemıšlel jsem o tom.|Kokain bude budoucnost.
{59557}{59663}Ti ètyøi ho budou transportovat|v taškách z jiní Ameriky. Troškaøi!
{59706}{59807}Uzavøel jsem dohodu s Thajci.|Budete mít monopol.
{59820}{59877}Budete na trhu ti nejvìtší psi.
{59927}{60022}Radím ti dobøe,|sbalte se a jeïte do Thajska.
{60305}{60365}Zbavíte se tìch ètyø?
{60819}{60867}Posuòte se víc doprava, prosím.
{60881}{60962}- Yane. Pojï se s námi vyfotit.|- Jo.
{61042}{61083}Stoupni si vedle mì.
{61143}{61265}Tak, prosím, všichni k sobì|a usmívat se. Pozor, vyletí ptáèek!
{61278}{61330}Tyhle dva roky jsem se neflákal.
{61333}{61433}Je to úasné, trávit èas s celou rodinou.
{61464}{61566}Tvoji sourozenci dìlají|velmi správné obchody.
{61607}{61658}Je èas, abys pomohl své rodinì.
{61675}{61752}Všechno, co jsme s tátou dìlali,|bylo pro rodinu.
{61757}{61820}Doufám, e v tom budeš pokraèovat.
{61983}{62062}Pøíští tıden tady bude jeden obchod,|pojï do nìj se mnou.
{62135}{62184}Zavolám ti.
{62857}{62931}Myslím, e ten údìl bere moc vánì.
{62934}{63009}Pøijede osobnì pøíští støedu.
{63023}{63147}Ètrnáctého, to byl Kwanùv pohøeb.|Udeøí na velkou ètyøku.
{63207}{63282}Proè poslal Sama pryè?
{63294}{63383}Já nevím. Mohl mu bıt nápomocnı.
{63442}{63491}Pokud nechce Sama zabít taky!
{63792}{63877}Hele, u nìkolik dní tì sleduju!
{63929}{64036}Konec koncù, jsem tvùj nadøízenı.|Chci vìdìt, jakı máš plán.
{64200}{64289}Ngaiovi jsou tvá rodina.|Yane, opravdu víš, co dìláš?
{64442}{64529}Pane! Já jsem polda!
{64621}{64685}No, tak mi zasalutuj.
{64805}{64879}Zamluvil jsem stùl. Dáš si veèeøi?
{64949}{65020}Hele, vypadám dobøe, ne?
{65307}{65355}Keungu!
{65414}{65463}Poletíme.
{65475}{65557}Co budeš takhle dìlat v Thajsku?
{65560}{65687}Dám si raloèí ploutev, masáe.|Nevím, co se ti nezdá.
{65757}{65806}- Miláèku!|- Copak je?
{65809}{65910}- Proè jsi mi neøekl o svém vıletu?|- Je to obchodní cesta, ne za zábavou!
{65913}{65978}Neboj se. Budu rozumnı, jo?
{65981}{66033}Hau má plány jak znièit Waha a ty chlapy.
{66076}{66167}- Já vím.|- A víš, e ty jsi taky jeho terèem?
{66201}{66267}To je pøece nesmysl! To není moné.
{66270}{66337}Jen na mì poèkej na letišti! Ahoj.
{66383}{66430}Same, musíme nastoupit!
{66903}{66953}Zavolej Samovi znovu,
{66993}{67039}a letadlo pøistane.
{67134}{67185}Dnes v noci zabiju Haua.
{67205}{67254}Nebuï ukvapená!
{67257}{67305}Tak to nejsem.
{67377}{67495}Pøed ètyømi roky jsi mi øekl,|abych zabila Kwana.
{67714}{67812}- Budeš mì teï vydírat?|- Já tì nevydírám.
{67846}{67929}Jen jsme u minuli místo,|odkud není návratu!
{68500}{68560}Pošlu všechny pryè.
{68769}{68860}K dnešní veèerní operaci.|Tøi skupiny.
{68906}{69008}Áèko, to bude tady. Béèko tady.
{69011}{69135}Nic nedìlejte, poèkejte na moje rozkazy.|Céèko bude sledovat cíl a...
{69192}{69240}Jak to, e je to dneska?
{69277}{69360}Víš pøece, e Hau poøád všechno mìní.
{69436}{69553}Myslíš, e Yan je jedinı špion?|Moji mui jsou špioni u sedm let!
{69580}{69631}Kde je balíèek karet?
{69960}{70018}Dnes v tom jedeme spolu.
{70097}{70140}Jdeme!
{73231}{73298}- Zdravím. Jak se máte?|- Dobøe, dìkuji ti.
{73651}{73705}Ani hnout! Stát!|Zùstaòte kde jste!
{75209}{75307}Zùstaneš, dokud nepøijede|tvùj právník.
{75329}{75372}Nebo spolupracuj.
{75387}{75490}To nejde. Nemohu spolupracovat.
{75493}{75585}Znáte Zen? Já ho nikdy nezvládl.
{75655}{75855}Táta øíkával. Co se má stát, stane se.
{75919}{75956}Zemøel pøesnì pøed ètyømi roky.
{75970}{76022}U je to dlouho.
{76243}{76310}- Kamna u jsou vyhøátá.|- Díky.
{76677}{76740}- U je tady, šéfe.|- Koneènì.
{77622}{77672}Tak jo, u jdu.
{77734}{77877}- Myslíte si, e jste vyhrál?|- Poèkejte a uvidíte.
{77901}{77980}Máme to, pane.|Ti dva jsou soukromı oèka.
{79672}{79796}- Haló, miláèku! Kde jsi?|- V Thajsku, kde jinde.
{79799}{79876}- Okamitì se vra!|- Proè bych se mìl vracet?
{79885}{79978}Na nic se neptej, jenom se vra!|Hau tì chce zabít!
{79981}{80046}Nesmysl, pracuju pro nìho.
{80049}{80086}Poslouchej!
{80128}{80200}Kwana jsem zabila já!
{80461}{80506}Máte video?
{80616}{80722}- Je to dobré?|- Je to úasná šou!
{80851}{80896}Co Hau øíkal?
{81308}{81363}Pan Ngai mi øíkal,|abych se o tebe dobøe postaral!
{83865}{84000}Pøed ètyømi roky jsi mi øekl,|abych zabila Kwana.
{84040}{84156}- Budeš mì teï vydírat?|- Já tì nevydírám.
{84171}{84247}Jen jsme u minuli místo,|odkud není návratu!
{84327}{84377}Pošlu všechny pryè.
{84484}{84605}Najal jsem ty dva,|aby vyšetøili vradu mého otce.
{84608}{84665}Ale kdo by to byl tušil?
{84891}{84996}Policie se spikla,|aby zabila mého otce.
{85028}{85092}Obèana dodrujícího zákony.
{85175}{85310}Luku, není tohle ten úøedník z videa?
{85785}{85910}Jestli ho zatkneš, nebo ne,|je jen na tobì.
{87149}{87200}Opravdu skvìlá šou!
{87314}{87376}Nejseš fotogenickej.
{88199}{88245}Pøed ètyømi roky.
{88273}{88332}Kolik vám Samova ena zaplatila?
{88423}{88476}Dejte mi ještì šanci.
{89265}{89377}Dal jsem jim šanci pøed ètyømi roky.|Nevyuili ji.
{89431}{89530}Kdy dám tobì šanci,|vyuiješ ji?
{89926}{89995}Jsi s námi u sedm let.
{90007}{90083}Jsi polda.
{90133}{90248}A my jsme ti špatní.|Je èas, pøijmout osud.
{90349}{90484}Nedìlám to rád,|ale inspektor Wong zabil tátu.
{94439}{94491}Nìjaké zprávy od Sama?
{94531}{94604}Sam mi volal. Je v poøádku.
{94612}{94710}Chce, abys tady na nìj poèkala.
{94921}{94971}Co tvoji lidé?
{94991}{95047}Emigrovali.
{95102}{95154}Ty jsi nešel?
{95933}{96014}Jdeme, Same!|Zbavíme se jich! Dìlej!
{96060}{96121}Ty víš, e to nezvládneš.
{96124}{96162}Já vím.
{96201}{96250}Moje ena je v nebezpeèí.
{96290}{96364}- Prosím, pomoz mi.|- A proè bych to mìl dìlat?
{96380}{96428}Pomohl jsem ti, zbavit se šéfa.
{96475}{96527}Vím, e chceš bıt šéfem ty.
{96580}{96660}A taky,
{97143}{97203}bral jsem tì jako kamaráda.
{97346}{97403}Nevìø mu, Same, nedìlej to!
{97406}{97479}- Zmiz! - Nevìø mu!|- Dìlej!
{97908}{97977}Promiò, Same.
{99793}{99915}- Chceš mì zavøít?|- Jestli chceš zabít Haua, tak ano.
{100012}{100064}Pak není co øešit.
{100144}{100269}Mluvil jsem s šéfama.|Všichni za tebou poøád stojí.
{100289}{100370}Jak to? Inicioval jsem vradu!
{100502}{100617}I Britové souhlasí,|e nesmíme nechat triádu bıt.
{100629}{100768}Hele, celé oddìlení za tebou stojí.|Dost dobré, ne?
{100859}{100909}Máš karty?
{101082}{101131}Vyšší vyhrává.
{101169}{101232}Tak pojï, jdeme na stanici.
{101308}{101356}Klíè!
{101378}{101464}Zvoral jsem to.|Nepotøebuju, abys mi pomáhal.
{101928}{102013}Našli jsme je pøi první akci.|Nechával sis je celou dobu.
{102016}{102071}Vìdìl jsem to.
{102088}{102220}Víš, nechal jsem tì jít si svou cestou.
{102225}{102320}Ale teï je øada na tobì,|abys poslouchal.
{102328}{102380}Jsme pøece jako bratøi, ne?
{102526}{102607}Mám u Ngaie práskaèe.
{102621}{102691}Nekontaktoval mì nìkolik dní.
{102719}{102767}Ani Yan, ne!
{102810}{102862}Ty klíèe!
{103949}{104020}Pomoc! Seeòte pomoc!
{104042}{104090}Pomoc!
{106490}{106547}Proè jsi mi lhal?
{106573}{106621}Nelhal!
{106624}{106686}Samovi se nìco stalo!
{106689}{106746}Øíkala jsem ti,|e jsem jednoduchá ena.
{106750}{106824}Musím udìlat nìco pro svého manela.
{106827}{106879}Jedu do Thajska.
{106881}{106932}Prosím, nejezdi!
{106955}{107010}Pojedu. Ty se mnou nemusíš.
{107055}{107134}Nechci, abys tam jezdila.
{107251}{107348}Mary, jsi se Samem u roky.
{107361}{107465}Napadlo tì vùbec,|e Sam je moná...
{107478}{107518}Co to øíkáš?
{107520}{107570}Co to dìláš?
{107697}{107778}- Co to dìláš?|- Nechci, abys odjela.
{107832}{107883}To pøeháníš!
{108053}{108101}Poslouchej!
{108104}{108154}Jsem ena tvého šéfa!
{108278}{108331}Nechci tì u nikdy vidìt!
{109626}{109739}- Dnes veèer pùjde na letištì.|- Haló? Haló?
{111796}{111844}Já jsem zabila Kwana!
{111871}{111932}Kdy je na mì mu hodnı,|udìlám pro nìj cokoliv.
{112990}{113049}ÈAS
{113204}{113350}Pøípad IO 31 42. Tıká se úèasti|pana Wonga na vraedném spiknutí.
{113359}{113463}Tohle je jedenácté interní slyšení|policejního dùstojníka.
{113469}{113551}Inspektore Wongu,|máte nìjaké otázky?
{113566}{113629}Ne. Ne.
{113649}{113786}Inspektor musí mít vùdcovské vlastnosti.|Pane Lau, jste pouhı policejní konstábl.
{113786}{113862}Mùete øíct povyšující radì,|proè si zaslouíte povıšení?
{113863}{113889}Jistì, pane.
{113893}{114044}11. Dubna devadesát pìt|dostalo oddìlení tuhle nahrávku.
{114071}{114142}Obviòující vás z úèasti|na vraedném spiknutí.
{114144}{114182}Pøiznávám se, pane.
{114185}{114308}Je rok 1997. Pokud do 1. Èervence|neobdríme váš posudek,
{114310}{114347}myslíte, e budete povıšen?
{114350}{114453}Èína má pøísloví. S novım králem|pøicházejí noví stoupenci.
{114456}{114546}Take, myslím, e budeme muset|zaèít úplnì od zaèátku.
{114558}{114615}Co se s vámi stalo?
{114661}{114774}Kdybych øekl, e ty jejich|dùkazy neobstojí,
{114816}{114868}chtìl byste zaèít znovu?
{114927}{115004}Je mi to líto. Porušil jsem zákon.
{115021}{115096}Co si myslíte o morálce policie|po roce '97?
{115099}{115158}Èíòané jsou sentimentální.
{115161}{115218}Doufám, e zákony mì budou|i nadále chránit.
{115221}{115315}Ale také velmi pevnì vìøím|v sebe samého, pane!
{115334}{115383}Jsem vám velmi vdìènı!
{115413}{115495}Ale u nemám dùvìru.|Prohrál jsem!
{115497}{115558}A co chudák Luk?
{115561}{115639}Budete mít èisté svìdomí,|kdy to vzdáte?
{115655}{115727}Válka ještì neskonèila.
{115749}{115852}Všichni chceme tenhle pøípad uzavøít.
{115883}{115993}Hong Kong pøece neøídí|Ngaiova rodina, ne?
{116125}{116223}Tady jsou záznamy Interpolu.|Pøeètìte si to.
{116773}{116822}Byl jsi nìkdy na pohøbu v Thajsku?
{116875}{116994}Pøed pár mìsíci jsem byl|na obøadu své eny.
{117025}{117128}Mniši tøi dny zpívali svoje písnì.
{117197}{117286}Neuronil jsem jedinou slzu.
{117372}{117540}V den pohøbu nechali rakev v obıváku.
{117601}{117681}Bláznil jsem. Chtìl jsem je zmlátit.
{117733}{117871}Mnich mi øekl, e v Thajsku je to tradice.
{117946}{118033}Ta zesnulá pokud jsme s ní,
{118076}{118203}mùe dosáhnout vìèného míru.
{118334}{118384}Zeptal jsem se mnicha,
{118452}{118532}co kdy moje ena není v té rakvi?
{118554}{118613}I tak toho míru dosáhne?
{118780}{118856}To je mi velmi líto.
{119005}{119082}Mnich dal ruku sem a øekl,
{119101}{119237}nebojte se, vaše ena je tady.
{119407}{119557}A to je pøesnì to místo,|kam mì Thajci støelili!
{119675}{119724}Tak jsem si øekl,
{119873}{119957}minul jsem místo,|odkud není návratu.
{120046}{120147}Ale svìdèit proti Hauovi|bude nebezpeèné.
{120273}{120352}V tebe vìøím. Jsi tak slušnı.
{120436}{120507}To u jsem neslyšel léta. Díky.
{120577}{120616}Máš plán?
{120679}{120789}Budu dìlat, co umím.|Svoji práci.
{120821}{120896}A a to skonèí,|odjedu z Hong Kongu.
{121119}{121170}Zmìnil ses.
{121584}{121638}Dìátko!
{121745}{121799}Pojï ke mnì!
{122892}{122942}Tys to zøedil, e jo?
{123006}{123067}Co mi øekneš?
{123393}{123445}Tak si to seer!
{123561}{123665}Hele, tohle u nedìlej.|Zlomilo by to morálku tìch klukù.
{123763}{123806}Pan Ngai øekl, abych to vedl.
{123846}{123897}Nelíbí se ti to snad, co?
{124273}{124354}A je to jak chce, jsou starší.
{124380}{124439}Musíš se od nich ještì hodnì uèit.
{124496}{124555}Strıèek John za pár let skonèí.
{124614}{124664}Chápeš to?
{124708}{124779}Nepotøebujeme ádné zádrhely.
{124842}{124985}Mám teï velmi vlivné známé,|kteøí jsou nám ochotni pomoct.
{125026}{125142}Jestli vše dobøe dopadne,|naše rodina u nemusí ít ve stínu.
{125807}{125909}- Pane Cheungu, to je pan Ngai.|- Jak se máte? - Tìší mì.
{125912}{126007}Kdy se mi o vás právní zástupce zmínil,|nevìøil jsem mu.
{126010}{126114}Jste velmi mladı, pane Ngai.|V jakém jste znamení? Øeknìte?
{126144}{126185}- Vola?|- Rok vola.
{126189}{126253}Co? Ale, to je dobré.
{126256}{126389}- Vùdce Chan má rád mladé lidi.|Jestli chcete, seznámím vás. - Dìkuji
{126394}{126440}Vánì?
{126470}{126573}Pokud vím, tak vùdce Chan øíkal,|e nesnáší triády.
{126725}{126856}To je pravda. Pan Ngai byl vyzván,|aby se poradil s policií.
{126858}{126975}- Vánì? Gratuluji, skvìlı nápad!|- Ano, dobrı nápad.
{127348}{127394}Pan Hau Ngai?
{127472}{127563}Jsem Ngaiùv právní zástupce.|Dnes slaví Hong Kong své pøedání.
{127566}{127605}Všechny ostatní obchody mùou poèkat.
{127608}{127688}Co kdy øeknu ne? Bude to vadit?
{127768}{127886}Ngai. Jste podezøelı z nìkolika vrad|z roku 1995.
{127916}{127994}Jste zatèen. Tady je pøíkaz.
{127997}{128116}Cokoliv øeknete, bude zaznamenáno,|a mùe bıt pouito proti vám.
{128121}{128188}- Nìjaké otázky?|- Nemám.
{128525}{128606}Ta obvinìní z vrad podle mì neobstojí.
{128610}{128732}Ale fakt, e jsi byl šéfem triády,|bude dìlat problémy.
{128740}{128865}Nechápu, e si nìjakı inspektùrek,|klidnì pøijde, a jen tak tì obviní.
{128951}{129052}Zpráva z Hong Kongu.|Odvolali tvou kandidaturu.
{129070}{129155}- Zavolej Beijinga. A seene|nìjaké pøátele. - Zkusím to.
{129171}{129244}Na to zapomeòte. Nikdo vám nepomùe.
{129258}{129358}Kadı ví, jak ti byl Sam oddanı,|a teï je svìdkem obaloby.
{129360}{129450}Je konec. Promiò. Nepomùu ti.
{129460}{129558}Øíkal jsi, e to nebude problém!|Kadı sleduje, jak zareagujeme.
{129560}{129605}Co tedy udìláš?
{129608}{129662}Co mùu dìlat? Vyhroovat vládì?
{129665}{129755}Ale takhle to nemùe jít dál.|Jsme pøece na jedné lodi, ne?
{129758}{129871}Pak musím vystoupit.|Jsem jen právník. Ne jeden z vás.
{129881}{129951}Nechci se s vámi potopit. Promiòte.
{130219}{130254}Ano?
{130274}{130345}Samova ena a dcera jsou v Thajsku!
{130378}{130443}Je to na tobì.
{130597}{130631}Sestro.
{130658}{130767}Ty a bratøi byste mìli vzít mámu|a odjet s ní na nìjakı èas na Hawaj.
{130793}{130886}- Ano. - Jistì. U jsme tam|dlouho nebyli.
{131139}{131189}- Budeš v poøádku?|- Neboj.
{131237}{131292}Je mi líto, e nemùu pomoct rodinì.
{131296}{131346}Hlavní vìc je, dostat tì ven.
{131378}{131427}Postarejte se o mámu!
{131429}{131476}- Jasnì. - Neboj se.|Nech to na nás.
{131758}{131919}Bohuel, Wongu, i s mım svìdectvím|dostane Hau jen nìkolik let.
{131963}{132064}To je fakt. Ale i tak tì asi|nebude mít rád.
{132168}{132240}- Vtipnı. - No, tak já jdu.|- Poèkej.
{132268}{132399}Musím ti podìkovat.|Bez tebe bych se nikdy nevrátil.
{132446}{132541}No jo. Musím u jít,|mám hodnì práce.
{132544}{132645}Kdybys nìco potøeboval,|øekni jim to, budou tì chránit. Jo?
{132647}{132688}Jasnì.
{133054}{133101}Same!
{133170}{133216}Díky.
{133265}{133353}- Tak, jak to jde? - Dobøe.
{133356}{133455}Pøeloili mì k CIB.|Budu teï vyšetøovatelem v zácviku.
{133611}{133718}Zavolala ti Mary, ne odjela?
{133909}{133991}Zbyteènì si neubliuj.
{134132}{134245}Wong mi øekl, e kdy budu|nìco potøebovat,
{134310}{134356}mám jít za tebou.
{136120}{136169}Myslel jsem, e nepøijedeš.
{136231}{136278}Jsem tady.
{136653}{136730}Jsou to dva roky.
{136785}{136889}Kvùli pøípadu mého otce ses mi|neodváil zavolat dva roky?
{136892}{136945}Neumíš se mi podívat do oèí?
{136986}{137028}Ne.
{137271}{137369}Vše, co potøebuješ,|abys ho usvìdèil, je v bezpeèí.
{137396}{137451}Roztøídil jsem to podle data.
{137558}{137610}Proè mi pomáháš?
{137792}{137913}Já ti nepomáhám.|Jsem polda.
{137945}{138009}Chci splnit slib,|kterı jsem dal Lukovi!
{138076}{138144}A u nechci bıt špionem.
{138173}{138262}Ještì dva roky|a jak bych asi skonèil.
{138265}{138362}Ty to nevíš? Ve vìzení.
{138526}{138576}Pohøbìme minulost.
{138600}{138690}Jen mì vem zpátky na oddìlení.|Dej mi kanceláø.
{138704}{138771}Jenom malou, s vıhledem na moøe.
{138776}{138904}A zaøiï, abych tì u nikdy nevidìl.
{138993}{139066}To se neboj. U mì neuvidíš.
{139081}{139126}Ještì nìco.
{139143}{139203}Nìkteré vìci jsem nevìdìl,|jak napsat.
{139206}{139264}Pøijï se mì zeptat,|kdybys tomu nerozumìl.
{139267}{139392}Ale nepomíchej to.|Zabiju tì, jestli to pomícháš.
{139419}{139496}To je skvìlé.|Pomùe mi to, Yane.
{139521}{139571}To doufám.
{139727}{139776}Dìkuji ti.
{141290}{141363}Take, soud s Hauem|zaèíná u za tøi dny.
{142843}{142900}- Dej mi to.|- Policie!
{142966}{143031}Inspektore Wongu! Sam je pryè!
{143388}{143495}- Sam utekl kuchyní, inspektore Wongu.|- Kdo mìl hlídat v kuchyni?
{143571}{143609}Promiòte, pane.
{143626}{143723}Inspektore, Sam telefonoval|do Thajska, ne utekl.
{143809}{143856}Ano?
{145029}{145128}Pane Ngai. Co ode mì chcete?
{145156}{145222}Vy jste mi pøece volal.
{145227}{145296}Take mi, prosím, øeknìte,|jak mi mùete pomoct.
{145299}{145376}Posaïte se. Tady.
{145627}{145676}Dìlejte.
{145732}{145801}Zabijte mì a bude po všem!
{145804}{145897}Nìco takového jsem neudìlal léta.
{145973}{146031}Na všem se spolu mùeme domluvit.
{146050}{146108}Hong Kong je pro nás dva dost velkı.
{146115}{146165}Mohli bychom bıt dokonce i partneøi.
{146261}{146311}Minulost u není.
{146691}{146803}Zabijte mì, prosím.|Zabijte mì dnes v noci.
{147074}{147149}Ale kdo se potom postará o vaši rodinu?
{147578}{147670}Máme zprávy! Hau má Samovu enu|a dceru jako rukojmí.
{147699}{147763}To je jeho thajská pokojská!
{147971}{148077}Celé roky jsem zùstával naivu.
{148086}{148202}Díky tomu, e mám v Thajsku pár pøátel.
{148357}{148406}Chcete si nìco poslechnout?
{148458}{148510}Je to z Hawaje.
{148599}{148650}Je tam vaše rodina.
{148697}{148747}A moji thajští pøátelé také.
{148999}{149110}Pane Ngai. Mùj šéf mì poádal,|abych se postaral o vaši rodinu.
{149402}{149459}Tati, kde jsi?
{149596}{149643}Haue!
{149740}{149787}Dr hubu!
{149900}{149950}Øíkal jsem, e mì zabijete.
{151284}{151347}Dej to dolù, neslyšels!
{151350}{151475}Nechte ho. U jednou to zkusil.
{151495}{151559}Nech ho to udìlat znovu!
{151727}{151848}A mì støelí, bude to na vás,
{151898}{151944}jestli ho zastøelíte, nebo ne.
{152108}{152196}Co má pøijít, a pøijde!
{155475}{155525}Dvì otázky.
{155592}{155667}Zabil jsi celou jeho rodinu?
{155681}{155755}Jistì, e ne!
{155773}{155870}Jenom jsme ho vystrašili!
{155921}{155990}Oèekával jsi, e ho zabiju?
{156174}{156219}Co myslíš, e asi øeknu?
{156222}{156304}Ne, oèekával jsem, e umøu.
{156324}{156371}Byla to jediná monost.
{156525}{156566}Promiò.
{156637}{156734}Víš, jak tvrdì jsem pracoval,|abych získal dùkazy,
{156758}{156821}aby sedìl na doivotí?
{157342}{157457}Jak se daøí? Dobøe.|Same! Thajsko.
{157578}{157663}Paule! Dìkuji ti.
{157666}{157763}Všechno v poøádku.|Tak teï jsme partneøi.
{157795}{157926}Kokain pøímo do Hong Kongu.|Mám uzavøít Ngaiùv pøípad?
{157951}{158101}Paule, nemìli bychom chodit tak daleko.
{158117}{158184}Štìstí, e jsi narazil na mì.
{158204}{158255}Jinak u bys byl mrtvı.
{158258}{158336}Byli jsme pøedurèeni k tomu,|abychom byli partneøi, v momentì,
{158338}{158403}kdy mì zklamala moje zbraò.
{158405}{158455}Jasnì.
{159129}{159281}Pøedávací obøad Hong Kongu|zaèal døív, v jedenáct dvacet.
{159310}{159446}Hrály hymny obou zemí.|V sále byla vyzdviena vlajka Británie.
{159448}{159533}Obøad byl velmi dùstojnı.
{159580}{159697}Pøed zahájením bylo k vidìní|nìkolik dojemnıch momentù.
{159739}{159880}Kdy kráèely kapely obou zemí,|nìkteøí èínští pøedstavitelé neustále fotili.
{159887}{159994}Princ Charles a guvernér Patten se usmívali.
{160047}{160099}Kdy ceremonie oficiálnì zaèala,
{160164}{160250}tøi britští a tøi èínští vojáci pomalu|vpochodovali na pódium.
{160276}{160329}Èínští vojáci ukázali vlajku|Èínské lidové republiky.
{160435}{160534}Dle jejich vzoru se tøi Hong Kongští policejní|úøedníci objevili se tøemi britskımi úøedníky.
{160608}{160684}Také ukazovali vlajky.|A pak všichni povstali.
{160703}{160790}Byla pøesnì pùlnoc.
{160892}{161009}Pøišel 1. Èervenec roku 1997.
{161062}{161191}Vlajky byly vytaeny nahoru,|aby ukázaly konec koloniálního období.
{161222}{161329}A také zaèátek jedné zemì|s dvìma politickımi pøístupy.
{161346}{161470}Konec koloniálního období,|zaèátek nového Hong Kongu.
{161510}{161715}Vznikla nová Hong Kongská oblast s lidmi,
{161730}{161847}kteøí chtìjí ít v klidu.
{163938}{164043}Tak dobøe. Je to obchod.|Pojï se k nám pøidat.
{164050}{164131}Víš, jakı šéf je nejhorší?|Škaredı.
{164150}{164204}Podívej se na mì, jak já záøím!
{164336}{164389}Take, jak se jmenujete?
{164715}{164768}Jak se jmenujete, sleèno?
{164874}{165007}Já jsem Mary. Jsem Mary. Mary.
{165024}{165199}M A R. M A R...