{1}{1}23.976
{2855}{2923}Dnes zaèíná druhı semestr!
{2966}{3010}To jsou ochránci!
{3016}{3057} Tadase-kun vypadá tak cool!
{3066}{3095}Dobré ráno všem.
{3128}{3175}Rima-sama vypadá tak krásnì!
{3183}{3255}Hinamori-senpai! Cool a pikantní!
{3267}{3314}Je to stále stejná velkolepá scéna.
{3314}{3399}Ukazuje se kadého vnìjší charakter.
{3413}{3445}Ale ve skuteènosti jsou…
{3527}{3554}Takovı.
{3585}{3626}Vyváená rovnováha!
{3626}{3647}Taková.
{3679}{3743}Co mám dìlat? Kadı se na nás dívá!
{3743}{3776}Tento charakter.
{3776}{3811}Je spíš takovı.
{3836}{3879}Amu-chi! Dobré ráno!
{3890}{3930}Dobré ráno!
{3930}{3963}Ah! Yaya!
{3963}{4020}Tadase, Rima-tan! Dobré ránko!
{4024}{4057}Dobré ráno, Yaya-san.
{4057}{4081}Dobré ránko!
{4081}{4166}Celé léto jsem byla osamìlá, protoe jsem vás nevidìla!
{4166}{4238}To není pravda. Vídali jsme se po celé léto.
{4238}{4331}Ale já byla osamìlá! Osamìlá!
{4354}{4451}OK! Pochopila jsem.Nemùeš nìco udìlat s tím charakterem rozmazleného dítìte?
{4451}{4493}Yuiky-san! Jsi tak roztomilá!
{4493}{4555}Ta sladká osobnost je tak neodolatelná!
{4567}{4611}Yaya-chan-senpai!
{4611}{4642} Ahojky.
{4642}{4725}Jsi stále tak populární i s dìtskım vyjadøováním?
{4725}{4762}To teda je.
{4788}{4890}Kdy o tom teï tak pøemıšlím, kadı se na Yayu dívá jinak ne my.
{4890}{4962}Tváø Rima-tan je tak hladká a jemná!
{4962}{4981}Hej.
{5007}{5081}I kdy jsme obì ochránci, je to trochu záhadné.
{5103}{5178}{C:$0000FF}{Y:bi}Nechte to na Yayu!
{5280}{5308}Je to lahodné!
{5317}{5401}Tento Chiffon Cake chutná vıbornì! 
{5401}{5465}Ah, jeden zbyl. Vezmu si ho.
{5480}{5526}Proè jsme udìlali jeden navíc?
{5541}{5582}Asi ze zvyku.
{5674}{5728}Pøedseda… Ráda bych vìdìla co dìlá.
{5752}{5832}Hej,Tadase. Co se stane se idlí Jacka?
{5832}{5909}Vıbìr ochráncù je práce prezidentského vıboru.
{5909}{5965}I já se toho trochu bojím.
{5985}{6036}Take to místo necháme zatím prázdné?
{6036}{6060}Ano.
{6068}{6204}I kdy tu po Sanjou-kun zùstalo velké prázdno, spojme jako vdy své síly a sname se.
{6204}{6223}Ano!
{6230}{6260}Rozkaz!
{6260}{6327}Jsem si jistı e si to uvìdomujete, ale…
{6327}{6424}jasnì záøící bílé vajíèko, které se nedávno objevilo.
{6454}{6543}Jsem si jistı, e je to Embryo. To si myslím.
{6565}{6585}Embryo?
{6585}{6616}e by?
{6631}{6685}V tom pøípadì ho musíme rychle chytit!
{6685}{6749}Jsi tak blízko nadvlády nad svìtem, e?
{6749}{6792}Princi.
{6828}{6850}Princi?
{6871}{6971}Pøesnì! Chytím ho co nejdøív!
{6984}{7122}Rozhodl jsem, e chycení Embrya je prvoøadá priorita ochráncù!
{7137}{7220}A bude to vajíèko v mıch rukách, stanu se králem svìta!
{7232}{7277}Budu nejvyšší ze všech králù!
{7303}{7341}To je úasné, Tadase-kun!
{7341}{7399}První zmìna charakteru v tomto roce.
{7400}{7449}Vıbornı charakter jako vdy.
{7450}{7479}Urèitì! Urèitì! 
{7501}{7556}Jste dost nadšení.
{7559}{7590}Ah! Odkdy?
{7597}{7661}Trochu jsem se bál co se stane kdy tu nebude Jack.
{7661}{7715}Ale pøedpokládám, e jsem nemusel.
{7731}{7780}Jo! ádnı problém!
{7780}{7834}Chycení Embrya bude malièkost!
{7873}{7935}Mluvíš smìle, poddanı.
{7949}{8027}Ah! Tadase, nálada tvé obvyklé pøemìny je jiná!
{8027}{8171}Dìti jako ty potøebují získat více síly, ne budou schopni chytit Embryo!
{8171}{8209}Uh? Síly?
{8209}{8266}Vskutku. Potøebuješ trénink!
{8301}{8357}Velmi od tebe oèekávám! Pøíprav se!
{8416}{8474}Jste velmi energiètí.
{8622}{8703}Yukari-senpai si dovolila pøíliš.
{8716}{8781}Nechat mì v temnotì a opustit Easter.
{8781}{8876}Aspoò mi o tom mohla øíct.
{8881}{8905}Vedoucí Tsukumo!
{8905}{8934}O co jde?
{8934}{8979}Je tu nìco co mì trápí.
{9002}{9038}Pošli mi to sem.
{9038}{9058}OK.
{9117}{9152}Vedoucí! Je to i tady!
{9177}{9205}Právì to posílám.
{9324}{9355}To je…!
{9436}{9522}Protoe jsem udìlal zmìnu charakteru, povídal jsem divné vìci.
{9540}{9628}Ale protoe nás Sanjou-kun opustil, chtìl jsem, aby se Yuki-san snaila.
{9628}{9653}Ahoj!
{9666}{9680}Desu.
{9680}{9721}Hej! Posloucháte vùbec?
{9721}{9780}Já jsem se sebou spokojená.
{9778}{9800}Desu!
{9801}{9848}To si myslím o tvém tréninku.
{9856}{9875}Hej. Hej.
{9899}{9982}Cítil jsem se sám, tak jsem vás pøišel navštívit.
{9988}{10045}Kukai! U je to doba!
{10045}{10087}Ahoj! Jak se daøí?
{10096}{10117}Kukai...
{10129}{10248}On je jedinı o kom si myslím, e by mohl bıt trenér, tak jsem ho poádal.
{10248}{10345}Ale proè tak moc chceš aby Yaya trénovala?
{10429}{10498}Yuiki-san má víc ne dost síly, ale nikdy ji nechce skuteènì pouít.
{10503}{10551}Trénink není cíl.
{10565}{10706}Je to cesta jak ji nechat trochu dospìt.
{10706}{10739}Rozumím.
{10761}{10785}Ale..
{10785}{10853}Hej, vzhledem k tomu, e u je to dlouho, pojï si hrát!
{10853}{10910}Vypadá to trochu jinak.
{10910}{10956}Ona je opravdu rozmazlené dítì.
{10956}{11018}Nejdøív pojïme do královské zahrady.
{11018}{11058}Udìlám ti èaj.
{11058}{11089}Opravdu?
{11089}{11121}Soma-kun.
{11137}{11159}Hups.
{11159}{11225}Skoro mì vtáhla do svého svìta.
{11225}{11286}Ne, ty u v nìm jsi.
{11286}{11346}Pojïme na to! Speciální trénink!
{11346}{11363}Ne!
{11383}{11419}To vypadá na problém.
{11476}{11541}Yuiki-san, opravdu na tebe spoléháme.
{11541}{11616}Myslím si, e z nás všech máš nejvìtší potenciál.
{11616}{11680}Kdy to zkusíš, dokáeš cokoli!
{11680}{11739}Chci vidìt Yainu cool stránku!
{11739}{11806}Pepe-chan by se taky mela snait!
{11806}{11867}Sna se! Sna se! Pepe-chan!
{11942}{11974}Kdy to povídáte,
{11974}{12002}Tak myslím e nemám na vıbìr.
{12046}{12084}Dobrá! Nejdøív udìláme toto!
{12084}{12116}Sprint naplno!
{12195}{12242}Jen ji tahá.
{12314}{12354}U víc nezvládnu.
{12375}{12448}Hej! Nemá to smysl kdy nebudeš bìhat sama!
{12448}{12487}Ale…
{12508}{12556}Budoucnost bude tìká.
{12561}{12584}Um…
{12605}{12669}Nevidìli jste tu ptáèka?
{12669}{12696}Ptáèka?
{12747}{12777}Kdy o tom tak pøemıšlím…
{12825}{12852}Ahojky!
{12867}{12912}Je s tím ptáèkem nìco v nepoøádku?
{12912}{12987}Je to domácí mazlíèek, kterého si koupily áci tøetího roèníku tøídy hvìzdy.
{13019}{13063}Kdy jsme mu dovolili vyjít z klícky, uletìl nám.
{13063}{13098}Je to má chyba!
{13161}{13191}Neobviòuj se.
{13222}{13282}Toho ptáèka pro vás najdeme.
{13284}{13326}Ah! Opravdu to pro nás udìláte, ochránci?
{13326}{13418}Kdy má ák problém, je povinností ochráncù pomoci mu.
{13418}{13465}Miki, zmìna charakteru.
{13465}{13492}OK.
{13514}{13604}Na dìvèe co vše nakreslí správnì! Zmìna charakteru!
{13708}{13724}Jaké to je?
{13748}{13839}Úasné! Vypadá jako on. To je Pi-chan!
{13839}{13911}A co takhle to nechat na Yayu?
{13911}{13990}Moná se v ní takto vzbudí dobrı ochránce.
{14061}{14149}Yaya-chan! Mùeme tento pøípad pøenechat tobì?
{14175}{14208}Co? Jen já?
{14242}{14317}Kdy je novı rok,mám na starosti hodnì práce.
{14332}{14351}I já.
{14379}{14407}A co Amu-chan?
{14421}{14473}Amu-chi, ty beztak nemáš co na práci, e?
{14490}{14534}Mám pro tyto oèi slabost.
{14534}{14575}Vlastnì ne.
{14575}{14662}Jsem olík, má práce je odchyt X vajíèek.
{14662}{14774}Co? Nevytahuj znova tu starou historku.
{14774}{14836}Yaya-chan-senpai.
{14861}{14900}Senpai!
{14927}{14992}Prosím,najdi Pi-chan!
{15045}{15079}U to chápu.
{15109}{15137}Jak se od Yayi dalo oèekávat!
{15137}{15180}Dekujeme moc! Sna se, Yaya-san!
{15192}{15219}Udìlám to zítra.
{15219}{15244}Ne, hned!
{15361}{15420}Hej mami, posloucháš mì?
{15420}{15457}Poslouchám.
{15457}{15570}Amu-chi, Tadase a ani Rima-tan! Nikdo mi nepomáhá!
{15570}{15628}A našla jsi toho ptáèka?
{15628}{15651}Ne.
{15651}{15707}I kdy jsem se dívala všude.
{15760}{15792}Haloo!
{15804}{15841}Ani tady není.
{15858}{15929}Já nechci Senpai charakter!
{15929}{15989}Mì staèí dìtskı charakter.
{15989}{16017}Vánì?
{16084}{16112}Jdeme, Chappy!
{16112}{16142}OK, Sanny!
{16152}{16207}Lehce vyøešíme kadı pøípad!
{16219}{16271}Legendární vyšetøovatelé! Sanny a Chappy!
{16408}{16478}Tsubasa tì má rád, Yaya-san.
{16478}{16561}Ví, e jsi jeho sestra.
{16579}{16630}Yaya-chan-senpai.
{16642}{16694}Prosím,najdi Pi-chan!
{16813}{16840}Aha.
{16948}{16991}Myslím, e to ještì jednou zkusím.
{17429}{17473}Yaya, proè jsi tak obleèená?
{17473}{17523}Legendární vyšetøovatelé, Yaya a …
{17523}{17547}Pepe!
{17605}{17628}Vyšetøovatelé?
{17628}{17684}Vèera to bylo v televizi!
{17697}{17719}Jdeme, Chappy!
{17719}{17753}OK, Sanny!
{17764}{17817}Lehce vyøešíme kadı pøípad!
{17833}{17876}Legendární vyšetøovatelé! Sanny a Chappy!
{17920}{17985}Takhle bude nalezení ptáèka hraèka!
{17985}{18008}Desu!
{18008}{18052}Jen jsi zkopírovala obleèení.
{18052}{18090}Zaèneme s vyšetøováním.
{18090}{18123}Nejdøív získáme nìjaké informace!
{18123}{18153}Jdeme na to!
{18194}{18237}Mám z toho opravdu zlı pocit.
{18356}{18392}Yaya-chan-senpai!
{18432}{18467}Co je? Vystrašili jste mì.
{18467}{18526}Um… Pi-chan…
{18526}{18598}Nebojte se, dnes ho urèitì najdu!
{18598}{18628}Nechte to na nás!
{18727}{18763}Dobrı den.
{18769}{18840}Mùu si s vámi na chvíli promluvit?
{18840}{18888}Jistì, o èemkoli.
{18936}{19036}Huh? Zakládající králi, vy se jmenujete Amakawa Tsukasa?
{19036}{19056}Vskutku.
{19056}{19105}To je trochu pøekvapivé!
{19105}{19128}Ale, ale…
{19128}{19250}Jste zakládající král, øeditel školy, správce planetária.
{19261}{19300}Kdo opravdu jste?
{19300}{19327}Podivné.
{19327}{19369}Dej si koláèek.
{19369}{19417}Itadakimasu!
{19513}{19565}Moment, neptala se na nic co by se tıkalo ptáèka.
{19565}{19660}A co je zajímavé, proè se tu musíme plíit?
{19660}{19733}Protoe jsme tento pøípad nechali na Yuiki-san.
{19733}{19796}Ale i kdy jsme tohle øekli, nemùeme ji nechat samotnou.
{19796}{19870}Ale nikdo tak silnı jako my, nemusí…
{19870}{19895}Pššš!
{19895}{19924}Yaya nás objeví!
{19924}{19977}Lahodné.
{20080}{20111}Toto je embryo?
{20128}{20187}Pravdìpodobnì. Není o tom pochyb!
{20257}{20351}Také sis ho musel všimnout. Proè jsi to neoznámil?
{20370}{20412}Vlastnì ani nevím.
{20436}{20566}Kdy jsme ztratily Hoshinu Utau, mìll bys vìdìt, e odteï, Tsukiyomi Ikuto,
{20566}{20629}úkol nalézt embryo pøipadl tobì.
{20647}{20692}Jak to udìláš ještì jednou, neodpustím ti to.
{20847}{20980}Nechal jsem Hoshinu Utau dìlat co chce, jak si chtìl. Za to od tebe ádám práci.
{21018}{21123}Tohle mì vánì štve! Jednoho dne tì dostaneme!
{21123}{21155}Pøesnì.
{21183}{21275}Nezáleí na tom,kolik má v sobe nenávisti. Je to jen loutka v mıch rukách.
{21277}{21348}Je nemoné znièit pouto, co je mezi námi.
{21379}{21433}I nadále mi posílej získaná data.
{21433}{21453}Ano!
{21519}{21580}Pi-chan nikde není.
{21580}{21626}Zajímalo by mì, kde je.
{21626}{21675}Vùbec ho nemùeme najít.
{21695}{21782}Moná ho unesli.
{21782}{21817}Unesli?!
{21831}{21921}Jestli chcete rukojmí zpátky,dejte mi sto milionu yenu!
{21931}{21964}Jak troufalé, Namine!
{21964}{22013}To je odpornı chlap.
{22013}{22064}To je hnusné!
{22064}{22117}C-C-Co budeme dìlat?
{22125}{22153}Co se dìje?
{22153}{22183}Kdo ví.
{22267}{22331}Moná je to hovor kvùli vıkupnému od únoscù!
{22331}{22365}Mám strach.
{22396}{22481}Nezaplatím sto milionu yenu! Na vıkupné zapomeò!
{22481}{22520}Vıkupné?
{22544}{22571}Mimika-sensei?
{22667}{22711}To bolíí!
{22711}{22821}Ah, u jsi tu dlouho nebyla, Yaya.
{22821}{22900}Kdy si jen lenošila, tvé tìlo celé ztuhlo.
{22900}{22930}Ne takhle.
{22930}{22978}Ohni se!
{22978}{23025}Stále stejnì silná povaha.
{23025}{23067}M-M-Mimiko-sensei.
{23067}{23113}Nevidìla jste tohoto ptáèka?
{23113}{23190}Ne, nikdy pøedtím jsem ho nevidìla.
{23190}{23253}Piari-chan, a co vy?
{23253}{23288}Nevidìli jsme ho.
{23288}{23322}Nikdy pøedtím jsme ho nevidìli.
{23325}{23368}Nikdo nic?
{23368}{23478}Ale co je dùleitìjší, Yaya-san, dnes s tebou budu více cvièit!
{23540}{23588}Co to dìlá?
{23660}{23709}To pøed chvílí byl aludek Ran?
{23745}{23796}Amu-chan mám hlad.
{23796}{23852}Co to teï povídáš? Vydr-
{23899}{23936}Amu-chan, to pøed chvílí-
{23936}{23991}Oh ne! Zrovna pøed Tadase-kun!
{23991}{24057}Samozøejmì e ne! Nepøedstavuješ si to?
{24057}{24089}Nikoho neoklameš.
{24105}{24157}Mùeme jít nìco koupit.
{24159}{24231}Zdá se, e Yayaino cvièení nìjakou chvíli zabere.
{24285}{24343}Yaya-tan, cviè poøádnì!
{24343}{24365}Yuiki-san.
{24395}{24423}Mai-ti.
{24423}{24495}Ptáèek, kterého hledáš, je to…
{24507}{24536}tamten?
{24585}{24616}Tady jsi!
{24633}{24688}Dekuji ti, Mai-ti, Mimiko-sensei!
{24688}{24735}Poèkej, Yaya-san!
{24735}{24818}Vánì. Hravá víla.
{24867}{24908}Pojï sem. Pojï sem, pojï sem!
{24908}{24930}Pi-chan! 
{24930}{24969} Pojï si s námi hrát!
{24969}{25000}Pojï sem!
{25037}{25060}Ah! Poèkej!
{25117}{25162}Jsi v poøádku, Yaya-tan?
{25281}{25319}Nebudeš plakat?
{25319}{25349}Dnes plakat nebudu!
{25349}{25386}Jdeme, Pepe-chan!
{25386}{25425}Yaya-tan.
{25443}{25476}Rozkaz!
{25515}{25549}Yaya-chan-senpai…
{25611}{25679}Mluvili jste o jídle, ale je to buchta s èervenımi fazolkami a mléko!
{25679}{25771}Je to chabé. U ani policajti v televizi tohle nedìlají.
{25771}{25839}Ale dává to pocit, e jsme se skuteènì stali detektivy.
{25856}{25934}Tadase-kun detektiv?
{25982}{26054}Tvé srdce! Zatıkám ho!
{26082}{26136}Chci bıt zatèená!
{26136}{26173}Amu-chan…
{26189}{26239}Ale co je dùleitìjší, Yaya u tu není.
{26268}{26308}Zmizela!
{26392}{26438}Jsem si celkem jistá, e letìl tudy.
{26438}{26490}Stále by tu nìkde mìl bıt.
{26490}{26522}Promiòte, nevidìli jste ptáèka?
{26796}{26838}Kukai, podívej!
{26879}{26918}Vidím ho! Je to Pi-chan!
{26947}{26978}Stùj!
{26995}{27038}Rád bych vìdìl, kam Yaya-san šla.
{27054}{27093}Úplnì jsme ji ztratili.
{27093}{27153}To jen proto, e jsme šli koupit to jídlo.
{27153}{27209}Co? Tys mìla hlad!
{27209}{27223}Pøesnì.
{27223}{27248}Ano!
{27345}{27371}Yaya!
{27406}{27455}Amu-chi…všichni!
{27455}{27523}Proè tu vlastnì jste?
{27550}{27570}Toti...
{27570}{27611}To je jedno! Co ptáèek?
{27627}{27646}Pepe-chan!
{27646}{27685}Nechte to na mì!
{27716}{27738}Pøiprav…
{27738}{27759}se...!
{27786}{27809}To bylo blízko!
{27872}{27950}Vánì! Kdy to došlo a sem… Jdeme, Pepe-chan!
{27953}{27969}Rozkaz!
{27969}{28058}{C:$0000FF}{Y:bi}Yayino srdce. Odemknout!
{28117}{28151}Jdeme, Pepe-chan!
{28173}{28185}OK!
{28471}{28514}{C:$0000FF}{Y:bi}Pøemìna charakteru   :   Milé dítì!
{28536}{28613}Tím ho dostaneme!
{28627}{28666}{C:$0000FF}{Y:bi}Sladké, sladké!
{28805}{28837}Chytla jsem ho!
{28909}{28965}Zajímalo by mì, jestli budou ty dìti šastné.
{28965}{29072}Dekuji ti velmi pìknì, milé dítì-
{29072}{29124}Oh, není to Yaya-san?
{29124}{29145}Sensei!
{29145}{29248}Pediatr, kterı se postaral o Tsubasa-chan!
{29255}{29333}Je od tebe hezké, e jsi chytila mou Margaret-chan.
{29333}{29368}Margaret chan?
{29368}{29394}Kdo je to?
{29394}{29439}To je tento ptáèek?
{29439}{29510}Uhm. Toto je moje Margaret-chan.
{29544}{29592}Nemoné! Není to Pi-chan?
{29606}{29653}Tváø je trochu odlišná.
{29664}{29692}Ne!
{29733}{29775}Co budeme dìlat?
{29904}{29948}Nìjak jsme s vyšetøováním uvízli.
{29948}{30008}Tak se vrátíme na místo èinu!
{30132}{30155}Nemoné!
{30155}{30182}To je Pi-chan!
{30182}{30223}Yaya-chan-senpai.
{30242}{30294}Pi-chan se vrátil.
{30294}{30314}Úasné!
{30314}{30347}Velmi dìkujeme!
{30347}{30382}Co se dìje?
{30382}{30444}Urèitì je to ta tøída s ptáèkem.
{30449}{30469}Ahoj!
{30487}{30507}Kukai!
{30507}{30529}Tak je to.
{30529}{30566}Kopa schopnıch mladıch dìtí.
{30580}{30656}Udìlal to bez odmlouvání, udìlal pro Yayu velkou laskavost.
{30656}{30707}Huh,víš nìco víc ne my, Kukai?
{30707}{30786}Toho ptáèka našli ty dìti.
{30861}{30902}Kukai, podívej!
{30928}{30950}No.
{30969}{31007}Pi-chan, pojï sem.
{31140}{31204}Moná se na Yayu nespoléhali.
{31204}{31255}Pravdìpodobnì ji v tom nechtìli nechat samotnou.
{31255}{31323}Kdy ji v tom opravdu nikdo nechtìl nechat samotnou a všichni jí chtìli pomoci,
{31323}{31381}myslím e je to její plus.
{31398}{31491}Pravda! Také jsme ji dnes sledovali!
{31506}{31550}Kdy o tom teï tak pøemıšlím, máš pravdu.
{31550}{31654}Nechat lidi pomoct ti a pomáhat ostatním, je také dobrı nápad.
{31654}{31804}Ano, Yuiki-san dìlá svou ochranáøskou práci svım zpùsobem.
{31828}{31889}No, myslím, e by jsme jí mìli pogratulovat.
{31889}{31972}Ano. I bez nás tvrdì pracovala.
{31972}{32045}Yaya se snaila. Ale jen Yaya.
{32045}{32081}Ale jen Yaya.
{32162}{32234}Zajímalo by mì, jestli se vrátil sám.
{32234}{32294}Ano, Pi-chan je urèitì záhadnı.
{32294}{32314}Urèitì.
