{1}{1}23.970
{2950}{2980}Špatnì!
{3001}{3026}Má to bıt takhle!
{3078}{3145}Pokud by vás zajímalo jak se toto stalo,
{3145}{3192}zaèalo to pøed pár dny
{3192}{3244}Vrame se!
{3402}{3466}Zdá se kadı má pìkné prázdniny.
{3466}{3504}To ano.
{3504}{3550}Hinamori senpai!
{3574}{3628}Senpai!
{3709}{3784}Je super potkat Hinamori senpai i o prázdninách....
{3784}{3824}Viva návštìvní den!
{3824}{3848}Kdo jsi?
{3877}{3919}Já ... jsem já!
{3919}{3955}Suzuki Seiichiro!
{3955}{4016}Suzuki ...Seiichiro?
{4016}{4045}Ah! Mé brıle!
{4096}{4128}Oh! To jsi ty?
{4128}{4180}U si na mì vzpomínáš?
{4195}{4264}Zkusil jsem pro zmìnu nosit èoèky ale asi to nebyl dobrı nápad.
{4264}{4332}Kdy nenosí brıle je z nìj bishounek ...
{4332}{4410}Kadopádnì: On se jmenuje Seiichiro?
{4433}{4509}{C:$0000FF}{Y:b}Sna se, Seiichiro!
{4545}{4568}Soutì zpìvu
{4600}{4623}Proto,
{4634}{4672}my, Seyitská akademie,
{4672}{4740}se pøihlásíme do pìvecké soutìe.
{4758}{4810}Bude se konat o letních prázdninách.
{4827}{4882}tak se všichni sname.
{4896}{5003}Je to trochu náhle, ale ještì nemáme pianistu ani sólistu.
{5015}{5048}Pojïme zkoušet!
{5292}{5347}Piano je vısadou celebrit!
{5363}{5393}Dívejte se!
{5393}{5428}To je má technika!
{5428}{5469}Na kterou jste cekali!
{5568}{5610}Není špatná.
{5610}{5659}Jene si to upravila podle sebe.
{5980}{6018}Bez dalšího protahování oznamujeme,
{6024}{6090}Pianista skupiny bude ..
{6123}{6179}Ètvrtı roèník, tøída hvìzdy, Hatanaka morime-san.
{6206}{6230}Já?
{6230}{6269}Hej, poèkat, poèkat!
{6269}{6333}Neslyšeli jste mé super úasné schopnosti?
{6338}{6401}Pokud bys hrála takhle,tak bychom nemohli zpívat.
{6421}{6471}Dále, sólistka bude ...
{6490}{6555}Šestı roèník, tøída Hvìzdy, Hinamori Amu-san.
{6555}{6585}Ah,chápu.
{6599}{6627}Poèkat, já?!
{6627}{6678}Proè? Vdy jsem ani nesoutìila!
{6690}{6741}Hinamori Amu je jediná co mue zpívat toto sólo!
{6741}{6773}Ta jediná!
{6773}{6798}Pøesnì!
{6819}{6878}I kdy jste mì nevolali, objevil jsem se!
{6878}{6930}Všichni jste se zbláznily!
{6940}{6995}I tak není nikdo kdo by to chtìl vzít.
{7014}{7040}Sna se bıt nejlepší, dobrá?
{7040}{7061}Hinamori-san.
{7171}{7229}Proto se dìje tohle všechno.
{7229}{7275}No, musí nacvièovat.
{7275}{7302}Sna se! Sna se!
{7302}{7327}Amu-chan!
{7737}{7779}Není to trochu hrozivé?
{7779}{7806}A nemálo.
{7851}{7869}Já?
{7889}{7915}O-omlouvám se!
{7998}{8043}Tak, dnes konèíme.
{8101}{8136}Jsem vyèerpaná.
{8148}{8198}I kdy jsi jen zpívala?
{8198}{8243}Zpívala jsem pøede všemi!
{8255}{8298}Kadı mì slyšel!
{8298}{8356}Jsem v tom stejnì špatná jako v karaoke!
{8356}{8401}Amu-chan,
{8401}{8438}zpívá ale ...
{8438}{8482}je v tom opravdu ...
{8482}{8522}špatná!
{8522}{8570}Ah! Nezpívejte!
{8616}{8652}Slyšeli jste to?
{8823}{8890}Trénuje sám?
{8890}{8924}Je pilnı.
{8951}{9031}Ale musím øíct, e má hroznı cit pro hudbu.
{9132}{9173}To nezvládnu!
{9173}{9197}Je to celkem dobré.
{9219}{9247}Hinamori-senpai!
{9244}{9330}Zase vidí další mou patetickou stránku!
{9343}{9365}Je to pravda!
{9365}{9476}Ztratil jsem právo bıt fanouškem Hinamori-senpai!
{9503}{9534}O èem to mluvíš?
{9534}{9581}Hinamori-senpai je ochránce!
{9581}{9675}a s kadou minutou její ivot záøí víc a víc
{9675}{9733}Nezaslouím si to!
{9754}{9825}To nemyslíš vánì,e?
{9841}{9889}V takovıch chvílích si myslíš,
{9890}{9981}e nejde nic dìlat.
{10010}{10084}Opravdu to tak nebereš ne?
{10084}{10141}Ah! Ale nemusíš se bát!
{10141}{10211}Pokud se do koncertu nenauèím dobøe zpívat,
{10211}{10262}budu jen otvírat pusu.
{10294}{10332}A to mùeš?
{10366}{10444}Pokud bych v ten den jen otvírala pusu,
{10456}{10486}Huh?
{10519}{10590}Kdy je to sólo,tak pokud nebudu zpívat,bude ticho!
{10618}{10642}Hinamori-san!
{10642}{10703}Chci nacvièovat dirigování.
{10703}{10749}Pomùeš mi? Budeme trénovat spolu?
{10776}{10846}Neeee...!
{10944}{10966}Suzuki-kun.
{11008}{11036}Hatanaka-san!
{11049}{11088}Budeme zkoušet spolu?
{11088}{11109}Huh?
{11109}{11173}Kdy nemáš doprovod,|tak je zkoušení tìké, ne?
{11181}{11230}Budu hrát na piano.
{11230}{11286}Ne, je to pøíliš problémové ne?
{11286}{11302}To je v poøádku!
{11302}{11364}Krom toho, i já musím cvièit.
{11379}{11411}Sname se spoleènì!
{11489}{11528}P-prosím dohlédni na mì!
{11538}{11560}Dohlédnu!
{12211}{12232}Hej! Hej!
{12232}{12285}Myslíte si,e zazpíváme dobøe?
{12288}{12345}Moná vyhrajeme!
{12345}{12413}Ale to není o vıhøe a prohøe.
{12413}{12467}Kadı se snaí a vloí do toho kus sebe.
{12467}{12493}Jasné, jasné.
{12493}{12538}Zase projev Tadase-nej studenta.
{12538}{12571}Co si o tom myslíš, Amu-chi?
{12591}{12639}Znamená to,e jsi poøád nervózní?
{12639}{12655}Huh?
{12668}{12685}Nemoné.
{12695}{12728}Bude to jen takové,jaké to udìláš.
{12728}{12790}Jasné, promluvila tvrdohlavá osobnost Amu-chan.
{12871}{12924}Ahhh, dnešek byl také vyèerpávající.
{13113}{13135}Ah!
{13135}{13162}To je on.
{13217}{13272}Ano! To je o moc lepší ne pøedtím.
{13272}{13313}Musíš zpívat sebevìdomì!
{13320}{13402}Kdy se pøi zpìvu budeš omezovat, pùjdeš mimo notu.
{13402}{13444}Ano, rozumím.
{13444}{13539}Jsme spoluáci, nemusíš bıt tak zdvoøilı.
{13576}{13604}Ano, chápu.
{13611}{13628}Jaké to bylo?
{13650}{13701}To u je lepší.
{13704}{13741}Tak, zkusíme to ještì jednou?
{13741}{13764}Ano!
{13786}{13806}Uhm..!
{13832}{13874}Nezní to Špatnì ...
{13874}{13906}Pøesnì, pøesnì.
{14029}{14109}Omlouvám se e jsi se mnou musela zkoušet tak dlouho.
{14109}{14190}Nic se nestalo,i já jsem zkoušela.
{14230}{14282}Ale staèí to na to, abych skuteènì lépe zpíval?
{14289}{14316}To bude dobré.
{14326}{14428}Já si dokonce nemyslím, e zpívat dobøe je to nejlepší.
{14460}{14499}Dùleitìjší je se pøi zpívání bavit.
{14515}{14539}Kanji-hudba,
{14539}{14587}nevznikla ze slov šastnı a zvuk?
{14601}{14647}Pokud si to nebudeš uívat, tak to bude špatné.
{14659}{14708}Tak...to je?
{14720}{14801}Pokud bych o tom já mohla mluvit, vdy ani dobøe nehraju.
{14801}{14848}Ne! Hatanaka-san!
{14860}{14936}Ne, to je v poøádku. Já to vím.
{14936}{15056}Kadopádnì se za to e neumím hrát nemùu nenávidìt.
{15066}{15218}Ale i tak, profesionálové jsou tak úasní, závidím jim...
{15233}{15293}Ale ... mùj sen je ...
{15375}{15405}Nebudeš se mi smát?
{15405}{15431}Nebudu!
{15471}{15546}Nechci pøestat hrát na piano.
{15570}{15622}A vyrostu a vdám se,
{15622}{15728}budu kadı den hrát na piano pro mého manela a mé dìti.
{15805}{15852}To je mùj sen.
{15852}{15904}V-V-Vdáš?!
{15904}{15929}Je to divné?
{15929}{15965}N-Ne,vùbec!
{15965}{16015}Jen si myslím e je to úasnı sen!
{16015}{16046}Stalo se nìco?
{16046}{16081}Nedívej se na mì!
{16199}{16221}Dìje se nìco?
{16221}{16255}Ta dívka je...
{16281}{16314}Sname se spolu!
{16314}{16337}Ano!
{16350}{16376}Hmmm...
{16376}{16437}Mám pocit e se nìco stane.
{16705}{16744}Zítra je Den D!
{16744}{16795}Tohle je naše poslední zkouška
{17085}{17158}Omlouvám se,mùeme to vzít ještì jednou?
{17164}{17182}Ovšem.
{17188}{17226}To je skuteènì nesnesitelné.
{17255}{17316}Taková jednoduchá èást a ty ji nezahraješ správnì.
{17333}{17388}Jak to potom zahraješ zítra?
{17388}{17483}Jak jsem oèekávala,|Saya je na klavírní doprovod vhodnìjší.
{17508}{17556}To je v poøádku,vezmeme to ještì jednou.
{17564}{17639}Kdy bude hrát Saya,tak je vıhra naše.
{17639}{17698}Pøesnì. Urèitì bysme vyhráli.
{17705}{17743}Navádí ostatní.
{17743}{17782}Pravda...
{17782}{17822}Ostatní ji ji zaèínají nenávidìt.
{17862}{17913}Omlouvám se,budu se snait.
{17913}{17975}To není problém kterı se vyøeší snaením.
{18002}{18023}Hej!!
{18023}{18089}Hudba znamená šastnı zvuk!
{18089}{18159}Proto není dùleité vyhrát!
{18159}{18217}Štìstí plyne z toho e jsme souèástí soutìe!
{18253}{18326}Kdy nechcete vyhrát tak co teda?
{18326}{18427}Jen zkoušení nemá smysl.
{18441}{18500}Nechce snad kadı vyhrát?
{18500}{18551}No,kdybychom vyhráli…
{18578}{18636}Poèkat!To je jejich volba!
{18644}{18694}Vìtšina z nich zmìnila názor.
{18705}{18742}Uklidnìte se!
{18751}{18821}Kdy chcete nìco dìlat,proè v tom nechcete bıt nejlepší?
{18821}{18977}Je normální dìlat to jen pro zábavu,nebo co?|To jsou slova poraenıch.
{18988}{19093}Kdy nechcete bıt extra|tak jakou má pak ta snaha smysl?
{19097}{19129}Vıhra?
{19134}{19196}Souèasnı doprovod na piáno nám k tomu nedá šanci.
{19196}{19226}Hej, lidi!
{19259}{19281}Hatanaka-san...
{19321}{19365}To je v poøádku.
{19376}{19457}Jestli mì chcete nahradit nìkım lepším,|pak vím e je to pro dobrou vìc.
{19475}{19492}Odcházím.
{19542}{19592}Tadase-kun.Dohlédnu na ni.
{19592}{19608}Dobrá.
{19690}{19744}Mé dlouho oèekávané záøící jevištì.
{19744}{19781}Tak teda,Tadase-kun!
{19781}{19820}Dirigování nechám na tobì.
{19843}{19879}To jsem rád....
{20142}{20171}Saya…
{20258}{20300}Hatanaka-san, poèkej!
{20316}{20348}Stalo se snad nìco?
{20361}{20452}No,já jen e si myslím,|e bys jako doprovod byla lepší.
{20452}{20469}Proto...
{20525}{20560}Díky.
{20566}{20651}Ale cítím e pøenechat to osobì,která je nadanìjší,je lepší.
{20660}{20692}Mìla by ses vrátit!
{20692}{20728}Budeme na tebe cekat!
{20759}{20800}Plakala...
{20800}{20860}Po tom co si vyslechla mì to nepøekvapuje.
{21064}{21143}Já….nechci pøestat hrát na piáno….
{21293}{21398}Jestli nechcete bıt extra,|tak jakou má pak ta snaha smysl?
{21413}{21451}Je to opravdu pravda?
{21464}{21499}To tedy není!Vánì!
{21510}{21582}Cítit se šastnı je hlavní!
{21582}{21647}To je pravda,kdy se staneš dokonalou,|ale nejsi šastná,
{21647}{21712}pak to nemá smysl.
{21728}{21754}Asi jo...
{21769}{21837}Ukáeš se zítra,Hatanaka-san?
{22075}{22120}Jsem nervózní!
{22120}{22188}Hej! Hej!Amu-chi,nemám pokrèené stuhy,e?
{22188}{22219}Amu-chi?
{22235}{22304}Zdá se e nemá náladu starat se o ostatní.
{22304}{22345}Celá ztuhla.
{22345}{22375}Proboha.
{22379}{22402}Hinamori-san.
{22428}{22469}Nevidìla jsi Hatanaka-san?
{22469}{22499}Hatanaka-san?
{22509}{22558}Kdy o tom mluvíš tak jsem ji ani nezahlédla.
{22558}{22645}To je zlé,za chvíli vystupujeme.
{22660}{22684}Nemáme na vıbìr….
{22687}{22716}Kde je Yamabuki-san?
{22716}{22753}Puste mì!
{22753}{22821}Kdy nebudu hrát já tak kdo?!
{22821}{22879}I kdy je vıkon Saya-sama skvostnı,
{22879}{22938}Musíme øíct:není jako doprovod vhodná.
{23087}{23175}Je to pro mì opravdu dobré?
{23194}{23261}Je normální dìlat to jen pro zábavu nebo co?
{23261}{23342}To jsou slova poraenıch.
{23595}{23624}Zrodilo se X vajíèko!
{23627}{23656}Ted?
{23656}{23680}Hinamori-san!
{23692}{23758}Pro ochránce je nepøístupné aby to ignorovali!
{23762}{23783}Ano.
{23788}{23810}Um...!
{23810}{23856}Hatanaka-san urèitì pøijde!
{23856}{23891}Jdu ji hledat!
{23891}{23922}Poèkej!
{23922}{23976}Kadopádnì,jdeme!
{23976}{24000}Ano.
{24142}{24170}Hatanaka-san!
{24184}{24224}{C:$0000FF}{Y:b}Zbyteèné!
{24245}{24287}Myslím e jsem nìco zaslechl…
{24312}{24340}{C:$0000FF}{Y:b}Je to Zbyteèné!
{24425}{24464}Mé brıle!
{24485}{24537}Spletla jsem se.
{24571}{24610}Amu-chi! Tam!
{24657}{24687}U se z nej stal X charakter!
{24700}{24716}Jdeme!
{24716}{24741}Zadrte!
{24855}{24880}Hatanaka-san!
{24915}{24962}Hatanaka-san se nemılila!
{24970}{25049}Znamená to bez brılí nevidí X charakter?
{25049}{25149}Hatanaka-san,øekla jsi mi co je tvùj sen ne?
{25149}{25209}Nechci pøestat hrát na piáno!
{25211}{25303}Kadı si myslí e kdy nejsi první tak to nemá smysl!
{25303}{25344}Kdo se stará o hloupé sny!
{25344}{25394}Není to hloupı sen!
{25434}{25551}Bez ohledu na to jestli se to tıká studia nebo sportu.|Nikdy nejsem první.
{25544}{25624}Ale i tak mám svùj sen.
{25624}{25671}Stát se øeditelem,
{25671}{25711}Stát se astronautem,
{25711}{25761}A taky sním o tom e budu závodník!
{25761}{25794}Jsi hloupı?
{25795}{25853}Jaké mají ty sny smysl?!
{25911}{25949}Hinamori-san,nebezpeèí!
{25988}{26025}Moná jsou nesmyslné,
{26025}{26097}ale momentálnì jsou pro mì dùleité!
{26097}{26147}Vše co mám jsou mé sny!
{26193}{26279}Kdy bych si myslel e jsou mé sny nesmyslné,
{26279}{26326}Tak budou mé sny patetické!
{26326}{26458}Mé sny nepatøí nikomu jinému…jsou jen mé!
{26458}{26516}V tom pøípadì jsou mé sny vdy na prvním místì!
{26553}{26577}Pøesnì!
{26585}{26643}Tvé sny nepatøí nikomu jinému.
{26643}{26701}Jsou to sny co jsou nejdùleitìjší pro tebe!
{26701}{26769}Hinamori-senpai…
{26769}{26797}To nebylo špatné.
{26910}{26966}{C:$0000FF}{Y:b}Mé vlastní srdce,odemknout!
{27036}{27099}Z Hinamori-san jde rùová záøe!
{27388}{27433}{C:$0000FF}{Y:b}Pøemìna charakteru   :   Srdcovı amulet!
{27569}{27591}Ah! Promiò!
{27838}{27898}Mám ráda tvou hru na piáno.
{27952}{27980}{C:$0000FF}{Y:b}Srdce napravení
{28029}{28050}{C:$0000FF}{Y:b}Odemknout!
{28186}{28226}{C:$0000FF}{Y:b}Otevøít srdce!
{28575}{28611}Dekuji,Hinamori-san.
{28611}{28664}A také Suzuki-kunovi.
{28677}{28696}Brıle...
{28730}{28757}Tak teda ahoj.
{28757}{28779}Ano.
{28779}{28809}Našel jsem je!
{28901}{28926}H-Hinamori-senpai...?
{28926}{28958}To obleèení…
{28996}{29026}Máš pøevlek?
{29026}{29093}Nikdy by mì nenapadlo ze má Hinamori-senpai takové hobby!
{29093}{29137}Nalezenı další plusovı bod!
{29137}{29182}Ah! To je špatné!
{29182}{29215}Nazval to pøevlekem.
{29215}{29267}Není to trochu...pøehnané?
{29304}{29363}Uh? Já…
{29363}{29405}U je vše v poøádku.
{29416}{29439}Hatanaka-san.
{29459}{29517}Mùeme se na tebe spolehnout s doprovodem?
{29576}{29604}Ano.
{30255}{30317}Chvilková zmìna charakteru to vylepšila!
{30317}{30379}Taky je to jen pro dnešek.
{30757}{30817}Ah,koneènì je konec.
{30817}{30890}Zpívání je neèekanì tìké e?
{30890}{30913}Nebylo to zlé.
{30913}{30930}Díky!
{30930}{30952}Bylo to opravdu skvìlé!
{31033}{31185}Co se dìje? Takhle zírat.e by ses do ní zamiloval?
{31210}{31256}Co to povídáš Hinamori-senpai!
{31270}{31329}Myslím e to co jsi pøedtím øíkal byla celkem pravda.
{31337}{31386}Proè jí nejdeš pogratulovat?
{31386}{31415}Nemoné!
{31430}{31545}Já… já myslím e kdy se budeme snait,|dokáeme cokoli.
{31545}{31585}Tak dlouho dokud tomu budeme rozumìt
{31585}{31696}Kdy budeme mít sebevìdomí tak….
{31753}{31807}Sna se, Suzukii Seiichito!
{31850}{31888}Promiò,bolí to?
{31888}{31911}Jsem dojatı!
{31933}{31991}To je poprvé co Hinamori-senpai øekla celé mé jméno!
{32006}{32083}Øekla mé jméno!
