{0}{50}timecorrection by wert668 + some corrections
{115}{187}Kanoucí slzy, musí uschnout
{213}{285}osamìlost íznící po krvi
{290}{362}andìl smrti, kterému nevadí pach jeho peøí.
{566}{638}Na ulici, kde èerné slunce nikdy nezapadá
{738}{810}všichni vypadají podezøele.
{923}{995}Nepotkáš tady dítì.
{1009}{1081}Nepotkáš tady sebe.
{1096}{1168}Bùh, jen nás spasí.
{1347}{1419}Lidé jsou jak loutky, které zkouší tancovat.
{1451}{1522}Jehòátka, obìtovaná na oltáøi.
{1609}{1681}Divím se, co udruje pøi ivotì ten sen...
{1801}{1873}Svìtla, která otevírají v temnotì oèi.
{1894}{1966}Jehòátka obìtovaná na oltáøi.
{1968}{2040}Kde je sen, ztracenı v pustinì?
{2273}{2311}Noir
{2311}{2383}Jméno osudu stanovené minulostí
{2467}{2522}Prosím, Nech Èerná ruka nad novorozenci
{2522}{2594}ochraòuje mír.
{2913}{2949}Promiò
{2949}{3021}U to bude...
{3074}{3146}Kdy jsme se poprvé setkaly, taky jsi mi ošetøovala zranìní.
{3198}{3270}Obèas mi pøipadá, e u je to hroznì dávno.
{3292}{3364}Jo, je to u fakt dlouho...
{3462}{3534}Zrození
{3618}{3690}Take, Artena nás zatáhla do takového zapadákova...
{3779}{3824}Nemùu si pomoci.
{3824}{3896}Rituál konanı v Panství je tradicí
{3913}{3968}Tradicí, øíkáš...
{3968}{4040}Graipaule, co ta ena?
{4040}{4112}Korsická dcera?
{4119}{4191}Udìlá to...
{4647}{4718}Noir...
{4718}{4790}Byly stvoøené pøi vzniku Soldatù.
{4829}{4901}Pøed nìjákım èasem, se to jméno stalo v podsvìtí legendou.
{4997}{5066}Spravedlivé Noir Soldatù.
{5066}{5138}Kolik jich u bylo?
{5143}{5198}To nikdo neví.
{5198}{5270}Ale vdy tu byl nìkdo, kdo sám sobì øíkal Noir,
{5339}{5411}ani by znal pravı vıznam.
{5438}{5510}Stejnì jako my.
{5733}{5800}Arteno! Arteno!
{5800}{5872}Arteno!!!
{5879}{6011}Chloe byla...
{6531}{6572}Jsi v poøádku?
{6572}{6644}Ano, jsem pøeci skromná Noir
{6689}{6761}Jseš ok?
{6764}{6836}Jakmile jednou pùjdeme dolù, u se nebudeme moci vrátit.
{7301}{7373}Já...
{7387}{7459}U nechci víc utíkat!
{8799}{8869}Jsme Noir!
{8869}{8936}Ty, které se bojíte vìèné temnoty,
{8936}{9008}Uvolnìte cestu!
{9221}{9293}Pojïme.
{10034}{10106}Uhohoo...
{12324}{12396}Mireille!
{12710}{12755}Situace se vymkla kontrole!
{12755}{12796}Kdy jeden z Vnitøních Stromù padl,
{12796}{12868}zbıvají dvì, aby se staly Noir ale...
{12875}{12947}Chloe zemøela a meèe zbıvajících dvou jsou namíøeny na nás!
{12983}{13038}I kdybychom se odtud dostaly,
{13038}{13110}èeká na nás vyšetøovací komise!
{13160}{13232}Po tom všem by mìla bıt Korsická dívka zabita.
{13477}{13539}Posloucháš, Arteno?!
{13539}{13587}Celé to skonèilo!
{13587}{13635}Ty a Noir.
{13635}{13707}Rituál bude dokonèen podle plánu.
{13731}{13803}Tato situace nemùe bıt nazvána nepøedpokládanou.
{13825}{13887}Poslední, nejobtínìjší zkouška.
{13887}{13940}Arteno?
{13940}{14012}Nejdùleitìjší je, znovu pøinést starobylé èepele zpátky na svìt.
{14069}{14141}Ano, pøestoe svìt sám u Soldaty je.
{14179}{14251}Mluvíš pro Noir? Nestarala jsi se co bude se Soldaty?!
{14323}{14374}Lidé jsou mezi lidmi,
{14374}{14424}láska je s láskou,
{14424}{14493}høích je mezi høíchem,
{14493}{14565}Pùvodnì byli Soldaté pravdou lidské spoleènosti.
{14736}{14808}U od té doby uplynulo hodnì èasu, Soldaté se zmìnili.
{14841}{14913}Právì teï jsou Soldaté bledí z nemoci,
{14925}{14997}A spoleènost se zmítá v bolestech.
{15026}{15059}Je to moné...
{15059}{15131}To co je opravdu potøeba je èistá èepel,
{15153}{15225}nìkdo bez zábran.
{15311}{15383}Ano, chvíle znovuzrození Noir,
{15393}{15465}Ta chvíle bude prvním okamikem Grand Retour,
{15474}{15546}Pùvodní síla Soldatù se stane skuteèností.
{15589}{15661}Je moné, e jsi tohle všechno plánovala u od zaèátku?
{16074}{16145}Ty, které prošli závìreènou zkouškou jste vy dvì.
{16172}{16244}Toto pouto je pravım svìdectvím Noir.
{16280}{16352}Vítejte, Pravé Noir.
{16383}{16438}Ty musíš bıt Artena.
{16438}{16510}Mìla bych øíci "Ráda se s tebou setkávám?"
{16519}{16567}Není to poprvé.
{16567}{16639}Bdìla jsem nad tebou po dlouhı èas.
{16668}{16740}Ano, to ty víš.
{16740}{16812}Nerozèiluj mì!
{17066}{17138}Poslední, neojbtínìjší zkouška...
{17143}{17215}teï...
{17220}{17291}zaènìme s rituálem.
{17514}{17577}Zemì je pohlcena høíchem.
{17577}{17644}Avšak Noir byly vdy na pokraji temnoty,
{17644}{17716}bojující za dìti, topící se v neštìstí.
{17783}{17855}Pravá tváø pùvodních Soldatù,
{17855}{17927}jsou dva lidé, kteøí dokonale rozumí srdcím všech ostatních.
{19258}{19329}Jestlie mùe láska zabíjet lidi,
{19353}{19425}nenávist je tedy mùe zachránit.
{20744}{20816}Tento oltáø je pravou obøadní síní.
{20955}{21027}Místo, o kterém nikdo neví, zapomenuté èasem.
{21053}{21125}Vaše pou konèí zde.
{21173}{21238}Mnoho lidí zemøelo...
{21238}{21293}Soldatští lidé...
{21293}{21339}Mireillina rodina...
{21339}{21401}a Chloe...
{21401}{21473}Kvùli èemu?!
{21509}{21552}Je to tak pošetilé...
{21552}{21610}Tolik pošetilé...
{21610}{21681}Stejnì tak to øekla tvá matka.
{21696}{21768}Ti, kdo ztratí svùj zámìr jsou hlupáci.
{21845}{21916}Nicménì se dají pouít jako obìtní beránci poloení na váš oltáø.
{22180}{22252}Jak jen mùeš!
{23039}{23103}Arteno,
{23103}{23175}ty nemáš právo bıt zabita!
{23187}{23259}Take se nedá nic dìlat.
{23492}{23530}Jen vystøel,
{23530}{23602}jinak tvoje pøítelkynì zemøe.
{23621}{23693}Ano, mnoho ivotù bylo zmaøeno...
{23739}{23803}tvıma vlastníma rukama.
{23803}{23875}Chceš, aby se teï jejich smrt stala zbyteènou?
{23988}{24060}Mìla bys to vìdìt.
{24067}{24125}Ty jseš Noir.
{24125}{24197}Zrozená s høíchem, vychována høíchem...
{24228}{24300}Vyšší bytosti vládnoucí nad smrtí.
{24321}{24393}Tvoje jediná ivotní cesta leí tady.
{24463}{24535}Já...
{24537}{24561}Já musím...
{24561}{24633}Jako Noir jsi spáchala nepoèítanì zloèinù,
{24667}{24738}tyto høíchy nebudou nikdy odpuštìny.
{24885}{24947}Není dùvod bıt smutná.
{24947}{25019}Tyto høíchy jsou nezbytné tak dlouho, jak svìt svìtem stojí.
{25062}{25134}A ty jsi jedna z vyvolenıch pro tento úèel.
{25196}{25268}Teï stiskni spouš.
{25275}{25347}Zabij mì a ij dál jako Pravá Noir.
{25810}{25882}Prosím, postarej se o Mireille.
{26256}{26328}Kiriko!
{26707}{26755}Naše ruce jsou...
{26755}{26827}Èerné.
{26834}{26887}Tyto høíchy...
{26887}{26959}nelze odestát.
{26975}{27047}Noir...
{27055}{27102}Nicménì já...
{27102}{27174}pøijmu tyto høíchy jako Yuumura Kirika!
{27242}{27282}My nejsme...
{27282}{27354}tím, co si myslíš, e jsme!
{27488}{27560}Kiriko!
{27714}{27752}Kiriko!
{27752}{27824}Sbohem, Mireille.
{28004}{28076}KIRIKO!!!!!!
{28256}{28328}Mireille, nech mì jít...
{28572}{28618}Prosím...
{28618}{28690}Prosím tì!
{28829}{28901}Pojï nahoru.
{29898}{29956}Noir?
{29956}{29977}Mılíte se.
{29977}{30035}Ustupte!
{30035}{30107}Paklie se bojíte vìèné temnoty.
{30459}{30519}Co teï budete dìlat?
{30519}{30591}Ještì to neskonèilo.
{30605}{30646}Dobrá...
{30646}{30718}Budeme ít dál takové, jaké jsme.
{30725}{30797}To vše.
{30939}{31011}Svìt, ve kterém ijeme je vdy na pokraji temnoty.
{31054}{31109}Proto,
{31109}{31181}hledáme svìtlo.
{31334}{31368}Mireille...
{31368}{31399}Copak?
{31399}{31454}Co teï budeme dìlat?
{31454}{31526}Chci se vrátit do Paøíe a dát si trochu teplého èaje.
{31555}{31627}A o ostatním si promluvíme pozdìji, co ty na to?
{31632}{31699}Jo.
{31699}{31771}Udìláš èaj?
{31775}{31847}Jasnì.
{32641}{32713}Letmı dotyk,
{32776}{32847}mrází mì na tváøi,
{32927}{32999}koneènì jsem pochopila...e...
{33080}{33152}jak jsem se ráno probudila
{33298}{33370}zpìvem ptákù,
{33442}{33514}náhle jsem nic nevìdìla.
{33663}{33735}Nevìdìla jsem, co chce tvoje srdce.
{33890}{33962}Zírala jsem na oblohu, která
{34018}{34089}od té chvíle byla vdy jako tenkrát.
{34188}{34260}Pod mraky
{34315}{34387}jsem odhodila pryè svoje pocity...