{0}{50}timecorrection by wert668
{748}{820}Copperiova rakev, ...
{820}{921}... kanoucí slzy je vysušily ...
{921}{997}... osamìlost íznící po krvi ...
{997}{1148}... andìla smrti, kterému nevadí pach jeho peøí.
{1194}{1283}N O I R
{1283}{1451}Na ulici, kde èerné slunce nikdy nezapadá, ...
{1451}{1628}... kde, všichni vypadají podezøele, ...
{1628}{1702}... nemùeš se potkat s dítìtem, ...
{1717}{1796}... nemùeš zde potkat sebe, ...
{1808}{1983}... Bùh, je ochrání nás.
{1983}{2060}Copperiova rakev, ...
{2060}{2158}... lidská jako panenka, unavená z tance, ...
{2158}{2237}... promìnìná v obìtní jehòátka.
{2237}{2390}Jak daleko zajde tento umìlı sen?
{2426}{2505}Copperiova rakev, ...
{2505}{2604}... svìtlo, které otevírá oèi v temnotì, ...
{2604}{2681}... promìnìná v obìtní jehòátka.
{2681}{2846}Kde je ten sen, ztracenı v divoèinì?
{2973}{3002}Noir
{3021}{3086}Jméno osudu urèené minulostí.
{3105}{3165}Dvì eny vládnoucí nad smrtí, ...
{3184}{3237}... smìjí chránit Èernou ruku nad loukou.
{3242}{3299}Prosím, chraòte mír.
{3668}{3764}Song-sensei.
{3836}{3932}Obchodníci, jsou pøipraveni na vımìnu dnes v noci.
{3932}{3956}Promiòte.
{3956}{4052}V poøádku, nic se nestalo.
{4124}{4172}Omlouvám se.
{4172}{4196}Není potøeba.
{4196}{4292}Dìkuji.
{4531}{4627}Dobrá tak pojïme.
{4675}{4699}Sensei?
{4723}{4771}Sensei, co se dìje??
{4771}{4795}Sensei!
{5251}{5323}Nemilosrdnı Zabiják-èást první
{6713}{6809}Jezero...
{6809}{6881}Nepùjdu.
{6881}{6977}Ty jsi opravdu dcera Rolanda Bouqueta.
{8991}{9039}Tohle?
{9111}{9207}Co to je?
{9207}{9255}Zakázka.
{9255}{9327}E?
{9327}{9399}Øíka se tam, bì pracovat na Thaiwan.
{9399}{9423}No tohle...
{9423}{9518}Co myslíš?
{9566}{9662}Klient je...
{9686}{9782}Soldats.
{10597}{10693}Hong Li Pan
{10693}{10765}Na Thaiwanu mezi vládci podsvìtí,
{10765}{10861}je jeden vemi mocnı klan.
{10861}{10885}Jmenuje se Elder.
{10885}{10957}Soldaté nám zadali úkol
{10957}{11053}odstranit Whua.
{11580}{11676}Zajímalo by mì, co Soldats zamıšlí?
{11676}{11724}Nevím.
{11724}{11772}Kadopádnì, Soldats...
{11772}{11820}se pøibliují...
{11820}{11868}k nám.
{11868}{11916}Souhlasím
{11916}{11988}Nìkdo nechal v našem pokoji dopis...
{11988}{12036}Spoleènì s podpisem Soldats.
{12036}{12108}Pomalu sundavají masku,
{12108}{12180}a odkrıvají svou tváø.
{12180}{12252}Nesnáším, kdy si se mnou nìkdo takhle hraje.
{12252}{12300}My je pøinutíme tu masku sundat.
{12300}{12372}To je dùvod, proè jsme jely na Thaiwan.
{12372}{12468}Ano. Nepøišly jsme sem plnit jejich pøíkazy jako loutky.
{12635}{12707}stále...je to nebezpeèné.
{12707}{12755}E?
{12755}{12803}My...
{12803}{12875}Nemìly jsme sem jezdit.
{12875}{12971}Neøíkej takové hloupé vìci.
{12995}{13043}Neèekaly jsme na tuto pøíleitost?
{13043}{13139}Na to, a nás kontaktují?
{13139}{13163}I kdyby to mìla bıt past.
{13163}{13211}I kdyby to bylo celé narafièené!
{13211}{13283}Nemáme jinou monost ne kousat.
{13283}{13379}To je dùvod proè jsme se spojili.
{13379}{13451}I kdy nechceš...
{13451}{13475}Já to udìlám.
{13475}{13570}Sama.
{14338}{14362}Má milá Chloe.
{14362}{14458}Ètu dopis, co jsi mi nechala.
{14458}{14529}Jaké bezmocné dítì.
{14529}{14625}Nalákala jsem to dítì a její pøítelkyni,
{14625}{14673}na Thaiwan.
{14673}{14769}Pøidìlila jsem jim úkol.
{14769}{14865}Jenome situace na Thaiwanu se drasticky zmìnila...
{14865}{14937}Nepøedstavitelnì...
{14937}{15033}Vánì...
{15033}{15129}Mùe se z nich stát potrava pro tenhle hladovı hmyz.
{15177}{15273}A, Chloe.Jaké jemné dítì.
{15273}{15345}Nech svoje obavy kontrolovat svoje emoce.
{15345}{15441}Rozumím, je dobøe, kdy mì to bolí.
{15465}{15488}Bude to v poøádku.
{15488}{15512}Vra se v poøádku, Chloe.
{15512}{15608}Budu nad tebou celou dobu bdít.
{16064}{16136}Pánové
{16136}{16232}Situace se vyvyjí v náš prospìch.
{16256}{16352}Pouili jsme Shao Li a odstranili Èínského velvyslance.
{16400}{16472}On také pracoval pro Soldats.
{16472}{16567}Take Soldats pøišli na to, e jsme za tìmi vradami stáli my,
{16591}{16663}a chystají se na odvetu.
{16663}{16759}Znièit nás.
{16903}{16999}Ještì pøedtím ne jsme pøišli s Chlang Kal-Shek na Thaiwan,
{17023}{17119}jsme stáli tiše za Soldaty.
{17119}{17215}Jenome teï se nás snaí Soldati zbavit.
{17263}{17359}Pøesnì tak, budeme bojovat!
{17359}{17383}Ne pro politické cíle,
{17383}{17455}ale pro podsvìtí jako takové!
{17455}{17526}Noir vstoupili do Thaiwanu.
{17526}{17574}Soldats nejsou neporazitelní.
{17574}{17670}Máme velmi uiteèného informátora.
{17670}{17766}Øíkáš, e mùeme podniknout útok døív ne oni?
{17814}{17862}To je ten mu?
{17862}{17934}Soldatskı pes.
{17934}{17982}Pokud budeme sledovat tohoto mue,
{17982}{18078}dovede nás k Noir.
{18078}{18174}Shao Li!
{18174}{18246}Udìláš to Shao Li?
{18246}{18294}Dostaò Noir.
{18294}{18342}Samozøejmì.
{18342}{18414}I kdy jsou Noir 1000 let Evropské temnoty.
{18414}{18485}naše koøeny leí 2000 let v minulosti.
{18485}{18581}Není tu nepøítele, kterı by odolal mému jedu.
{18605}{18701}Nezapomeò na svoje slova.
{19061}{19109}Mám tu pro vás vzkaz.
{19109}{19205}Vánì? Dìkuji.
{20356}{20428}Zdá se, e jste vzkaz dostaly.
{20428}{20452}Ano.
{20452}{20523}Chtìl bych vás o nìèem informovat.
{20523}{20595}Poslouchám.
{20595}{20691}Hong Li Pan si najal hrozivého kata.
{20691}{20739}Kata?
{20739}{20787}Myslíš tím zabijáka?
{20787}{20859}enu jménem Shao Li.
{20859}{20955}Uvnitø podsvìtí se jí øíká Nemilosrdnı Zabiják.
{20955}{21027}Nemilosrdnı Zabiják?
{21027}{21099}Slyšela jsem o ní. Není to ten expert?
{21099}{21195}Hong Li Pan plánuje pouít Shao Li k odstranìní Noir.
{21578}{21674}Soldats a Thaiwanské podsvìtí bylo vdy v konfliktu kvùli tomu,
{21698}{21794}jak nejlépe manipulovat Èínu.
{21818}{21914}Nakonec spor vyvrcholil.
{21914}{22010}Podsvìtí dává jasnì najevo, e se bude mstít.
{22034}{22130}Informace Soldats zaèaly nejákım zpùsobem unikat ven.
{22298}{22346}Poèkejte chvilku!
{22346}{22394}O co vám jde?
{22394}{22489}Pøijal jsem rozkaz, abych s vámi spolupracoval.
{22489}{22537}To je vše.
{22537}{22633}Nedrádìte mì!
{22633}{22729}Chci vìdìt nìco jiného!
{22921}{23017}Øeknete mi všechno o Soldats!
{23473}{23520}To je ona!
{23520}{23616}Nemilosrdnı Zabiják!
{23664}{23760}Dokonce vìdìli kde jsem?
{24240}{24264}Kryj mì!
{24264}{24360}Mireille!
{24851}{24887}A
{24911}{24983}Opravdu? Rozumím.
{25031}{25103}Chrám je kompletnì zajištìn.
{25103}{25175}Jediné co ještì musíme udìlat je chytit myšku.
{25175}{25247}Shao Li ji pro nás dostane.
{25247}{25319}Èerná myška, jak víš.
{26733}{26829}Není to k nièemu.
{26877}{26973}U nejsi víc potøebnı.
{28028}{28124}Mireille...
{29179}{29251}Je mrtvá?
{29251}{29323}Ne.
{29323}{29371}Tak jako tak ji nenechám jít.
{29443}{29538}Mireille! Mireille!
{31744}{31816}Pøišla jsem pomoci...
{31816}{31912}tobì
{32997}{33136}Letmı dotyk, ...
{33136}{33285}... mrazení na tváøi, ...
{33285}{33443}... koneènì jsem si uvìdomila, ...
{33443}{33798}... e kdy jsem se ráno probudila zpìvem ptákù, ...
{33798}{33976}... náhle jsem nic nevìdìla.
{34021}{34251}Nevìdìla jsem, co chce tvoje srdce.
{34251}{34376}Jen jsem zírala na oblohu, ...
{34376}{34549}... která byla od té doby vdy jako tenkrát.
{34549}{34671}Pod tímto mrakem ...
{34671}{34858}... jsem odhodila pryè své pocity.
{35004}{35669}Pøíštì uvidíte ...
{35671}{35718}=== KONEC ===
