{0}{17}timecorrection by wert668 + some corrections
{18}{100}Copperiova rakev, ...
{115}{187}Kanoucí slzy, musí uschnout
{213}{285}osamìlost íznící po krvi
{290}{362}andìl smrti, kterému nevadí pach jeho peøí.
{566}{638}Na ulici, kde èerné slunce nikdy nezapadá
{738}{810}všichni vypadají podezøele.
{923}{995}Nepotkáš tady dítì.
{1009}{1081}Nepotkáš tady sebe.
{1096}{1168}Bùh, jen nás spasí.
{1347}{1419}Lidé jsou jak loutky, které zkouší tancovat.
{1451}{1522}Jehòátka, obìtovaná na oltáøi.
{1609}{1681}Divím se, co udruje pøi ivotì ten sen...
{1801}{1873}Svìtla, která otevírají v temnotì oèi.
{1894}{1966}Jehòátka obìtovaná na oltáøi.
{1968}{2040}Kde je sen, ztracenı v pustinì?
{2213}{2242}Noir
{2261}{2326}Jméno osudu urèené minulostí.
{2345}{2405}Dvì eny vládnoucí nad smrtí, ...
{2424}{2477}... smìjí chránit Èernou ruku nad loukou.
{2482}{2539}Prosím, chraòte mír.
{3069}{3117}Korsika...
{3117}{3189}Vracím se domù...na chvíli...
{3189}{3340}Dlouho jsem tam nebyla.
{3357}{3405}Nechci se vrátit.
{3405}{3556}Návrat na Korsiku
{4627}{4651}Protoe byli moji rodièe zavradìni,
{4651}{4699}Rodinı klan Bouquettù se rozpadl.
{4699}{4819}Korsika byla pohlcena soupeøícím klanem.
{4819}{4867}Ztratila jsem místo, kde bych mohla ít.
{4867}{4915}Vedena rukou strıèka Clauda,
{4915}{5066}jsem opustila Korsiku.
{5802}{5850}Omluvte nás.
{5850}{6001}Není tøeba.
{6042}{6193}Prosím omluvte nás.
{6977}{7128}Vrátila jsem se...
{10501}{10653}Madam Odett!
{10693}{10765}Marie! Marie, je to tak?
{10765}{10916}Myslela jsem, e se mi srdce zastaví.
{10957}{11029}Zkrásnìla jste.
{11029}{11101}Nikdy jsem si nemyslela...
{11101}{11149}e vás ještì nìkdy uvidím
{11149}{11197}Kdy jsi mì vidìla...
{11197}{11245}volala jsi na mì jménem mé matky, e?
{11245}{11389}Dìlala jsem pro ní od jejího narození.
{11389}{11485}I kdy jsem zkoušela na ni zapomenout, nemohla jsem.
{11485}{11556}Jste tak podobná Madame Odette, sleèno.
{11556}{11707}Je to jako by se moje paní vrátila zpìt.
{11844}{11892}To je mùj manel, Viktor.
{11892}{11940}Ano, pamatuji si na nìj.
{11940}{12012}Drahı, tohle je Lady Mireille.
{12012}{12163}Podívej je to dcera Madame Odette.
{12180}{12276}Omlouvám se, mùj manel u dávno zapomnìl na svoje mravy.
{12276}{12396}To je v poøádku, Marie.
{12396}{12491}Vypadá to e lidé nechtìjí mít nic spoleèného s mojí rodinou.
{12491}{12597}Lady Mireille.
{12597}{12669}Dìkuji, u pùjdu.
{13546}{13594}Pan Beltoni by s vámi rád mluvil.
{13594}{13618}Nasednìte si.
{13618}{13762}Dobøe.
{13762}{13913}Dobrá práce.
{14002}{14050}Odette?
{14050}{14170}To je ale pøekvapení.
{14170}{14290}Mirielle Bouquet. Proè jsi se vrátila?
{14290}{14338}Jenom abych zavzpomínala.
{14338}{14410}Ne abych se pomsitla.
{14410}{14553}Chápu...
{14553}{14601}Minulost je minulostí.
{14601}{14752}Nezajímá mnì kdo to tady dneska ovládá.
{14769}{14817}Ale je tu nìco, co bych ráda vìdìla.
{14817}{14961}Co?
{14961}{15057}O mıch rodièích.
{15057}{15105}Nebyl jsem to já.
{15105}{15177}Vím.
{15177}{15249}Bez pochyby jsi dcera Bouquetù.
{15249}{15321}Jsi odváná.
{15321}{15369}Myslím, e je to v poøádku...
{15369}{15512}Dáš si nìco?
{15512}{15632}Korsika mìla vdy pár soutìících frakcí, která se stavìla jedna proti druhé.
{15632}{15728}Byli jsme jedna z nich.
{15728}{15824}Jenome klan Bouquetù byl jinı.
{15824}{15944}Oni byli na vrcholku podsvìtí.
{15944}{16095}Ještì ne dìdictví skonèilo, byli Roland a Odette zavradìni.
{16112}{16184}Bylo to krátké.
{16184}{16232}Nesouhlasím se sentimentalitou.
{16232}{16328}Tenkrát mìl mùj otec nìjákı konflikt,
{16328}{16376}s jinım klanem.
{16376}{16448}Byl tu jeden klep,e
{16448}{16591}byl Roland znièen nìjákou neobvykle mocnou organizací.
{16591}{16663}To bylo nìco, na co jsem nemohl pøijít.
{16663}{16711}Ale také tomu vìøím.
{16711}{16783}Vrada nebyla provedena nikım s Korsiky.
{16783}{16855}Jsem o tom pøesvìdèen.
{16855}{16927}Setkala jsi se s Madoranem?
{16927}{16975}Madoranem?
{16975}{17023}Georgem Madoranem?
{17023}{17119}Ano, on byl pravá ruka tvìho otce.
{17119}{17167}Moná, e bude nìco vìdìt.
{17167}{17239}On nebyl zabit?
{17239}{17335}Ne, ije.
{17335}{17407}Nechci vás urazit.
{17407}{17455}Jen vám dám radu.
{17455}{17606}Mìla byste opustit tenhle ostrov hned, jak to bude moné.
{19013}{19085}Kdo je tam?
{19085}{19236}U je to nìjáká doba, Georgi,co jsme se vidìli naposledy.
{19277}{19349}To jsem já, Mireille.
{19349}{19469}Byla jsem tak ráda, kdy jsem zjistila, e jsi naivu.
{19469}{19492}Georgi, byla jsem...
{19492}{19612}Prosím, jdi domù!
{19612}{19660}Prosím, chci s tebou mluvit!
{19660}{19732}Georgi, otevøi! Co se dìje?
{19732}{19804}Georgi! Prosím! Vyslechni mì!
{19804}{19955}Georgi!
{20499}{20547}Olivové háje mojí rodiny...
{20547}{20667}Zajímalo by mì, co s nimi dnes je.
{20667}{20739}Nevíš kdy se vzdát, stejnì jako pohasínající plamínek.
{20739}{20835}Jsi vánì jako madam Odette.
{20835}{20883}Take, kdo ti o mne øekl?
{20883}{21034}Pamtuješ si...toto?
{21051}{21202}Jsou to hodinky mìho otce.
{21482}{21554}Tady to nejde...
{21554}{21602}Co tím myslíš?
{21602}{21650}Promluvíme si zítra,
{21650}{21801}o všem, co vím.
{22154}{22298}Rodina Bouquetù mìla velké tajmství.
{22298}{22370}Velké tajemství?
{22370}{22442}Bylo dùvodem, toho e byla schopná ovládnout Korsiku.
{22442}{22466}Ty dùvody jsou odhaleny ve smlouvì s jistou organizací.
{22466}{22617}Rodinnı vùdcove Bouquetova rodu, se tradiènì vázali slibem loajality k ní.
{22657}{22777}Na oplátku, Bouquetové dosáhli moci, která vládla nad Korsikou.
{22777}{22921}To bylo privilegium Bouquetù.
{22921}{22993}Jejich jméno bylo...
{22993}{23065}Soldati!
{23065}{23137}Ty u je znáš?
{23137}{23185}Moje matka a otec...
{23185}{23281}byli souèástí Soldatù?
{23281}{23377}Ano. Ty hodinky jsou toho dùkazem.
{23377}{23425}To je le!
{23425}{23496}To nemùe bıt pravda!
{23496}{23568}Oni byli zabiti Soldaty.
{23568}{23640}To je pravda.
{23640}{23736}Proè?
{23736}{23832}Protoe...
{23832}{23983}Georgi!
{24216}{24288}Pan Roland a madam Odette,
{24288}{24408}byli zabiti, kdy se tì pokoušeli chránit.
{24408}{24456}Nemohl jsem nic dìlat.
{24456}{24607}A nejen to, musel jsem utéci.
{24623}{24719}S tímto...nakonec...
{24719}{24870}Georgi!
{27117}{27165}Chloe!
{27165}{27189}Tenhle mu je...?
{27189}{27309}Má zabít všechny, kteøí by zkusili rozlomit peèe minulosti Korsiky.
{27309}{27381}To bylo jeho poviností.
{27381}{27429}A ty?
{27429}{27500}Nepomáhám mu v tom.
{27500}{27570}Ani do toho nezasahuji.
{27570}{27616}Take proè jsi tady?
{27616}{27668}Neøíkej mi e jsi tu jen tak na vıletì.
{27668}{27740}Korsika je pro mì vyjímeèné místo.
{27740}{27836}Pro mì a pro to dítì.
{27836}{27884}To dítì?
{27884}{27908}Myslíš Kiriku?
{27908}{27980}Ano.
{27980}{28052}Ona a já jsme vyjímeèné.
{28052}{28148}Ona a já jsme pravé Noir.
{28148}{28196}Kirika je...
{28196}{28268}pravá Noir?
{28268}{28340}Ano.
{28340}{28460}Chtìla bych ti nìco øíct.
{28460}{28483}Posluchám.
{28483}{28627}A se rozhodne vrátit, nestùj jí v cestì.
{28627}{28747}Ten, kdo s ní podnikne pou do minulosti budu já.
{28747}{28795}A kdy øeknu ne?
{28795}{28891}Zabiju tì.
{28891}{28963}Uvauji o tom, e bych chtìla bıt tvou kamarádkou.
{28963}{29059}Kama...rádkou?
{29059}{29179}Nejseš její kamarádka?
{29179}{29251}Ano, jsem si jistá, e se mùeme spøátelit.
{29251}{29402}Ty jseš zkrátka dítì Soldatù.
{29634}{29785}Dítì...Soldatù...
{30378}{30473}Tohle...jsou hodinky Soldatù.
{30905}{31001}Já...
{31001}{31097}Mireille?
{31193}{31241}Já...
{31241}{31337}Øekli mi, e jsem dítì Soldatù.
{32281}{32353}Letmı dotyk,
{32416}{32487}mrází mì na tváøi,
{32567}{32639}koneènì jsem pochopila...e...
{32720}{32792}jak jsem se ráno probudila
{32938}{33010}zpìvem ptákù,
{33082}{33154}náhle jsem nic nevìdìla.
{33303}{33375}Nevìdìla jsem, co chce tvoje srdce.
{33530}{33602}Zírala jsem na oblohu, která
{33658}{33729}od té chvíle byla vdy jako tenkrát.
{33828}{33900}Pod mraky
{33955}{34027}jsem odhodila pryè svoje pocity...
