{0}{40}timecorrection by wert668 + some corrections
{41}{100}Copperiova rakev,
{115}{187}Kanoucí slzy, musí uschnout
{213}{285}osamìlost íznící po krvi
{290}{362}andìl smrti, kterému nevadí pach jeho peøí.
{566}{638}Na ulici, kde èerné slunce nikdy nezapadá
{738}{810}všichni vypadají podezøele.
{923}{995}Nepotkáš tady dítì.
{1009}{1081}Nepotkáš tady sebe.
{1096}{1168}Bùh, jen nás spasí.
{1347}{1419}Lidé jsou jak loutky, které zkouší tancovat.
{1451}{1522}Jehòátka, obìtovaná na oltáøi.
{1609}{1681}Divím se, co udruje pøi ivotì ten sen...
{1801}{1873}Svìtla, která otevírají v temnotì oèi.
{1894}{1966}Jehòátka obìtovaná na oltáøi.
{1968}{2040}Kde je sen, ztracenı v pustinì?
{2213}{2242}Noir
{2261}{2326}Jméno osudu urèené minulostí.
{2345}{2405}Dvì eny vládnoucí nad smrtí,
{2424}{2477}smìjí chránit Èernou ruku nad loukou.
{2482}{2539}Prosím, chraòte mír.
{2733}{2756}Je to marné.
{2757}{2829}V Alexander Trading Corporation nejsou ádné informace.
{2868}{2939}Nezùstala jediná stopa.
{3237}{3309}Høíšníci se nikdy nesetkají po smrti,
{3333}{3405}Kdy høích nikdy nezmizí,
{3405}{3477}láska se také nikdy neztratí.
{3477}{3524}Osamìní jednou skonèí.
{3524}{3572}Krev Soldatù je pohlcena pustinou,
{3572}{3596}Jseš tady Kiriko?
{3596}{3644}A vtéká do tìla.
{3644}{3692}Obì ruce Soldatù jsou...
{3692}{3764}Obì ruce Soldatù jsou...?
{3764}{3836}Hej Kiriko!
{3836}{3908}našla jsem tu nìjáké informace o té knize!
{4028}{4100}Kiriko?
{4148}{4220}Kiriko...
{4316}{4388}Co se dìje?
{4460}{4507}Nic...
{4507}{4555}To nic není.
{4555}{4627}Obì Ruce Soldatù
{5035}{5107}Byla to fakt fuška!
{5538}{5610}Profesor Sharpel studuje historické dokumenty,
{5610}{5682}nedávno jsem se ho ptala na ty kopie.
{5682}{5754}A teï pøišla odpovìï.
{5754}{5826}Aèkoli tady mùeme zase jen maøit èas.
{5850}{5874}Nemùe bıt mılka.
{5874}{5946}Je to èást Langonského Rukopisu.
{5946}{6018}Langonskı Rukopis?
{6018}{6090}Ano.
{6258}{6330}Prosím, podívejte se.
{6378}{6450}Tenhle odstavec je z rukopisu , jeho pùvod je ve støedovìku.
{6474}{6545}Je tam pouit podobnı styl vìt.
{6545}{6593}Lidé mezi lidmi.
{6593}{6617}Láska mezi láskou.
{6617}{6665}Zloèin mezi zloèinem.
{6665}{6713}To je ono!
{6713}{6785}Behem tøináctého století, to bylo...
{6785}{6857}tajnì opsáno z Ilustrovaného Rukopisu z Langonského kláštera.
{6857}{6929}Je známo, e byl jednou pøeloen do Francouštiny.
{6929}{7001}Langonskı Rukopis.
{7001}{7073}Ovšem, co se obsahu originálu tıèe...
{7073}{7145}ještì stále není znám.
{7145}{7169}Aèkoli jsem vidìl jen jedinou kopie,
{7169}{7241}Langonského Rukopisu na vlastní oèi...
{7265}{7313}Jsem opravdu pøekvapen.
{7313}{7385}Kde je teï ta kniha?
{7409}{7481}jedna kopie je v Paøíi...jedna kopie v Berlínì.
{7504}{7576}Naneštìstí se obì kopie po válce ztratily.
{7600}{7672}Ztratily?
{7672}{7744}Nicménì, tahle kopie pøeci jenom pøipouší monost, e by mohl rukopis ještì existovat.
{7816}{7888}Tyto kopie jsou moná...z jednoho z nich.
{9135}{9183}Mám to!
{9183}{9231}Casper Edlinger.
{9231}{9279}Rakouskı multimilionáø.
{9279}{9351}To je ono!
{9902}{9974}Díky.
{10094}{10142}Ty nespíš?
{10142}{10214}Koneènì jsme to dokázaly.
{10238}{10286}Jo.
{10286}{10358}Langonskı rukopis...
{10358}{10430}Kopie originálu je ve Vídni.
{10525}{10597}Brzy budou dveøe do minulosti otevøeny...
{10621}{10693}námi dvìma...
{10741}{10813}Kiriko.
{10837}{10885}Ten slib.
{10885}{10933}Pamatuji se.
{10933}{11005}A budeme vìdìt všechno...
{11005}{11077}zabiju tì.
{11461}{11532}Tyhle dvì budou odstranìny.
{11532}{11604}ádná zkouška ale skuteèná smrt.
{11628}{11700}Take tu není jiná monost...
{11700}{11772}Pokud by to bylo moné,chtìl bych, aby se k nám pøidaly.
{11796}{11868}Nedá se nic dìlat.
{11868}{11940}Artena rozpíná svou moc rychleji, ne jsme oèekávali.
{12060}{12132}Pošlete Rytíøe Enki.
{12132}{12204}Mise bude stále oznaèena jako zkouška.
{12204}{12276}Vrada byla povıšena na 'zkoušku'.
{12300}{12348}Nemìl by tu bıt problém.
{12348}{12420}Ona také mùe pouít Chloe.
{12444}{12515}Samozøejmì.
{12875}{12923}Pøed dvìma roky
{12923}{12995}knihovna Edingerské rodiny
{12995}{13067}celá lehla popelem.
{13115}{13187}Langonskı rukopis shoøel samozøejmì také.
{13235}{13307}To co zbylo po ohni zùstalo tak jak bylo. Mùete se jít podívat.
{13379}{13451}Ano.
{13451}{13522}U na svìtì nezbyla ádná kopie Langonského rukopisu
{13594}{13642}jestlie není...
{13642}{13714}na místì, zapomenutém èasem.
{13786}{13858}Po tom všem jsme jenom zjistily, e to tady nìkdo zapálil.
{13906}{13978}Kniha u dál neexistuje.
{14002}{14074}Tak kde se vzaly tyhle kopie pøed poárem?
{14338}{14410}Høíšníci se nikdy nesejdou po smrti,
{14410}{14482}kdy høích nikdy nevymizí,
{14482}{14553}láska se také nemùe nikdy vytratit.
{14577}{14625}Chloe.
{14625}{14697}Osamìní se jednou rozplyne.
{14697}{14769}Krev Soldatù je vstøebána pustinou,
{14817}{14841}a vtéká do tìla.
{14841}{14913}Chloe!
{15033}{15105}Tolik toho u víte, e?
{15153}{15225}Tohle je napsáno za tím.
{15273}{15345}Obì ruce Soldats jsou dvì Panny.
{15345}{15417}Ruka lásky, která je schopná nést høích. Ruka temnoty která ho snese.
{15465}{15536}Noir.
{15560}{15632}Je to tak. Noir byly pùvodnì,
{15632}{15704}souèástí Soldatù.
{15920}{15944}Dvì jsou jedním.
{15944}{16016}Meè temnot, kterı mùe bıt pouit Saldaty.
{16016}{16064}Obì ruce Soldatù.
{16064}{16112}To jsou Noir.
{16112}{16184}jak šel èas, existence Noir byla zapomenuta.
{16232}{16304}Jedné co zbylo byl strach, kterı to jméno vyvolává.
{16328}{16400}Mnoho lidí nazıvalo samo sebe Noir,
{16424}{16495}ani by znali pravı smysl.
{16903}{16975}Vybrala jsem krycí jméno Noir pro práci s Kirikou.
{17023}{17095}Nicménì, pùvodnì je jméno Noir pro dvì jako tım, ne?
{17167}{17191}Ano.
{17191}{17263}Vlákno, které spojuje tebe a mnì...
{17263}{17335}Nevypadá to, e je Chloe je jenom jedna.
{17359}{17431}Tohle kroutící se vlákenko osudu.
{17431}{17502}Obklopuje nás neviditelná pavuèina.
{18078}{18150}Proè nám tohle všechno øíkáš?
{18150}{18222}Nech je tu vdy Svìlo a Voda pro Strom.
{18222}{18294}Kadopádnì jsem øekla jenom to, co Artena chtìla.
{18342}{18366}Artena...
{18366}{18438}Vypadá jako tvùj šéf.
{18438}{18509}Artena je pøísná ale laskavá.
{18509}{18581}Ona doopravdy s tìkım srdcem èeká na to,
{18581}{18653}a sloíš svou zkoušku.
{18677}{18701}Zkoušku?
{18701}{18725}Ano.
{18725}{18797}Je to údìl tìch, které se stanou Noir.
{18797}{18869}Pro ty, které se stanou Noir je...
{18869}{18917}údìl?
{18917}{18989}Ano.
{19325}{19397}Vypadá to, e jsi byla zamìøena.
{19421}{19492}Bojovat s mocnımi rytíøi,
{19492}{19564}pøekonánat pasti, které jsou jako pavouèí sí,
{19612}{19684}a uskuteènit misi.
{19708}{19780}Tyhle zkoušky jsou všechny tradièní rituál, kterı provází tu,|která se stává Noir.
{19852}{19924}To je...!
{21674}{21746}Kiriko...
{22178}{22226}Moná e Kirkia je...
{22226}{22274}Kirièina minulost je...
{22274}{22346}Zabíjíš lidi.
{22370}{22442}Zabíjíš je bez nejmenšího zaváhání.
{23616}{23688}Ty a já jsme pravé Noir.
{23712}{23784}Spoleènì narozené a vychované Soldaty.
{23784}{23856}Mající nejvyšší kvality vraha.
{24072}{24144}Soldaté nejsou tvım nepøítelem.
{24144}{24216}Soldaté jsou tvım domovem.
{24264}{24336}Ztratila jsi své vzpomínky.
{24360}{24432}To je, dùvod proè tomuhle èelíš, e?
{24479}{24527}Pøestaò...
{24527}{24551}Ale to je v poøádku.
{24551}{24623}Zaèínáš si vzpomínat.
{24671}{24719}Jako Noir.
{24719}{24791}Jako vyvolenı vrah.
{24791}{24863}Pøestaò...
{24863}{24935}Jako nìkdo, kdo splní kadou misi bez chybièky.
{24959}{24983}Prosím...
{24983}{25031}Pøestaò...
{25031}{25103}Protoe kdy jsi byla malá...
{25103}{25175}Mlè!!!!
{26517}{26541}Noir.
{26541}{26613}Jméno osudu, jen bylo stanoveno v minulosti.
{26613}{26685}Dvì eny vládnoucí nad smrtí.
{26709}{26769}Duchu temna, prosím provázej ztracené dítì.
{26769}{26841}Provázej dítì zpìt od okraje.
{26997}{27069}Jméno osudu, jen bylo stanoveno v minulosti.
{27093}{27165}Dvì eny vládnoucí nad smrtí.
{27165}{27213}Prosím nech Èerné ruce nad novorozenci
{27213}{27285}opatrují mír.
{27285}{27357}Jméno osud, jen bylo stanoveno v minulosti.
{27381}{27453}Dvì eny vládnoucí nad smrtí.
{27453}{27500}Prosím nech Èerné ruce nad novorozenci
{27500}{27524}opatrují mír.
{27524}{27596}Kiriko, ty jseš...
{28220}{28244}Já...
{28244}{28316}Já jsem...
{28699}{28747}Pøíjdu znova.
{28747}{28819}Ještì jednou, brzy.
{28819}{28867}To bude,
{28867}{28939}a tì pozvu do Zahrady.
{29107}{29155}Odlouèení jednou skonèí.
{29155}{29227}Krev Soldatù je pohlcena pustinou,
{29227}{29299}a vtéká do tìla.
{29299}{29347}Obì ruce Soldatù jsou dvì Panny.
{29347}{29419}Ruka lásky, která mùe nést høích. Ruka temnoty která ho snese.
{29490}{29562}Noir.
{30306}{30354}Já vím, to všechno okolo...
{30354}{30426}Mìla bych to vìdìt...
{30450}{30521}Právì tohle...
{30713}{30785}Èást mì chce vìøit, e jsem vlastnì svım zpùsobem normální...
{30833}{30905}Právì...tohle...
{30953}{31025}nechci vìdìt.
{31073}{31145}Ale teï vím...
{31217}{31289}Teï já...
{31433}{31504}Prosím... Mireille...
{31648}{31720}Nekoukej se...
{31720}{31792}na mì tak.
{32281}{32353}Letmı dotyk,
{32416}{32487}mrází mì na tváøi,
{32567}{32639}koneènì jsem pochopila...e...
{32720}{32792}jak jsem se ráno probudila
{32938}{33010}zpìvem ptákù,
{33082}{33154}náhle jsem nic nevìdìla.
{33303}{33375}Nevìdìla jsem, co chce tvoje srdce.
{33530}{33602}Zírala jsem na oblohu, která
{33658}{33729}od té chvíle byla vdy jako tenkrát.
{33828}{33900}Pod mraky
{33955}{34027}jsem odhodila pryè svoje pocity...
