{0}{17}timecorrection by wert668 + some corrections
{18}{100}Copperiova rakev, ...
{115}{187}Kanoucí slzy, musí uschnout
{213}{285}osamìlost žíznící po krvi
{290}{362}andìl smrti, kterému nevadí pach jeho peøí.
{566}{638}Na ulici, kde èerné slunce nikdy nezapadá
{738}{810}všichni vypadají podezøele.
{923}{995}Nepotkáš tady dítì.
{1009}{1081}Nepotkáš tady sebe.
{1096}{1168}Bùh, jenž nás spasí.
{1347}{1419}Lidé jsou jak loutky, které zkouší tancovat.
{1451}{1522}Jehòátka, obìtovaná na oltáøi.
{1609}{1681}Divím se, co udržuje pøi životì ten sen...
{1801}{1873}Svìtla, která otevírají v temnotì oèi.
{1894}{1966}Jehòátka obìtovaná na oltáøi.
{1968}{2040}Kde je sen, ztracený v pustinì?
{2213}{2242}Noir
{2261}{2326}Jméno osudu urèené minulostí.
{2345}{2405}Dvì ženy vládnoucí nad smrtí, ...
{2424}{2477}... smìjí chránit Èernou ruku nad loukou.
{2482}{2539}Prosím, chraòte mír.
{3405}{3477}Moje Temnota
{3908}{3956}Chloe!
{3956}{4004}Korsika je pro mne vyjímeèným místem.
{4004}{4076}Pro mì i pro to dítì.
{4100}{4148}Dítì?
{4148}{4172}Myslíš Kiriku?
{4172}{4220}Ano.
{4220}{4292}Ona a já jsme vyjímeèné.
{4292}{4364}Ona a já jsme pravé Noir.
{4364}{4436}Kirika je...
{4436}{4507}pravá Noir?
{4555}{4627}Pøemýšlím, že bych se chtìla stát tvou kamarádkou.
{4675}{4747}Kama...rádkou?
{4747}{4819}Ano, nejsi snad její kamarádka?
{4867}{4939}Jsem si jistá, že se spøátelíme.
{4939}{5011}Jsi zkrátka dítì Soldatù.
{5203}{5275}Dítì...Soldatù...
{5562}{5634}Na Korsice mi chloe øekla,
{5658}{5730}že ty a ona jste vyjímeèné,
{5730}{5802}Že ty a ona jste pravé Noir.
{5850}{5922}Moji rodièe byli èlenové Soldatù.
{5922}{5970}Ty hodinky to dokazují.
{5970}{6042}Rodièe se mne snažili chránit...
{6090}{6138}...i...
{6138}{6210}mého bratra...
{6210}{6282}Proè?!
{6450}{6521}Vím, že nelžeš.
{6617}{6689}Také uznávám, že máš talent.
{6689}{6761}Jsi o mnoho lepší v zabíjení než já.
{6881}{6953}Jsi neobyèejnì výborný vrah.
{6953}{7025}A...
{7049}{7121}nezjistitelný
{7121}{7169}Odejdi...
{7169}{7241}Nechci tì vidìt...
{7265}{7337}Prosím...alespoò ne teï...
{7457}{7528}Prosím.
{8032}{8104}Je dnes dost vlhko, že?
{8104}{8152}Ano...
{8152}{8200}Autobus má zpoždìní.
{8200}{8272}Zdražili ceny jízdného a na oplátku nám dávají takovéhle služby!
{8296}{8344}Ano...
{8344}{8416}Jsem na cestì za svým vkouèetem.
{8416}{8464}Ale nechce se mi vidìt se svou snachou
{8464}{8535}Nedá si øíct.
{8535}{8607}Kam máš namíøeno mladá dámo?
{8727}{8799}Cítíš se dobøe?
{8799}{8871}Nerozumím.
{8895}{8967}Mùj pøítel trpí.
{8967}{9039}I když myslím...rozumím tomu utrpení...
{9063}{9135}nerozumím už nièemu jinému.
{9135}{9207}To je hamba.
{9231}{9303}A, autobus už je tu.
{9375}{9447}Ty nenastupuješ?
{10070}{10118}Kdo jsem?
{10118}{10166}Jsem Noir.
{10166}{10238}Pravá Noir.
{10334}{10382}Npostižitelná...
{10382}{10454}Nìco.
{10957}{11029}Nemohou být poøád dvì.
{11868}{11940}Tady.
{11988}{12060}Byl jsem požádán, abych vám to doruèil.
{12084}{12156}Podívejte. Od toho øidièe.
{12851}{12923}Jsem rád, že mì budete doprovázet.
{12923}{12995}Chtìl bych si promluvit.
{13019}{13062}Jeï.
{13062}{13134}Ano.
{13211}{13283}Vynechme pøedstavování.
{13307}{13379}Protože já nejsem víc než pouhý posel.
{13427}{13498}Ale jste souèástí Soldatù.
{13498}{13522}To je pravda.
{13522}{13594}Nicménì proteï se nemáš èeho obávat.
{13594}{13642}Nepøišel jsem tì zabít.
{13642}{13714}Vraždy jsou záležitostí nìkoho jiného.
{13738}{13762}Chloe?
{13762}{13834}Ne.
{13834}{13906}Pøestože rozkaz k vraždì byl dán celé organizaci, Chloe...
{13978}{14050}Chloe pracuje jen na žádost Arteny.
{14050}{14122}Artena?
{14122}{14170}Chloe je pod Arteninou kontrolou,
{14170}{14242}proto nutnì potøebujeme lidi jako ty.
{14304}{14376}jsem souèástí strany, která nesouhlasí s Arteninou politikou.
{14386}{14458}Artena? Ona je jedna z vùdcù Soldats?
{14529}{14577}Ano.
{14577}{14625}Grand Retour. Grand Retour.
{14625}{14697}Slyšela už jsi to nìkdy?
{14697}{14745}Chloe to øíkala.
{14745}{14817}Ale jen to, nic víc...
{14817}{14889}Aha...
{14889}{14961}Artena chce Grand Retour.
{14961}{15033}Bezpochyby je to smysl existence Soldats.
{15057}{15129}Nicménì, jsme zjistili, že nás Arteniny metody ohrožují.
{15201}{15273}Má to nìco spoleèného se mnou a Chloe, že?
{15297}{15321}Ano.
{15321}{15393}Nech´t je navždy Svìtlo a Voda pro Strom.
{15417}{15488}Máme v úmyslu ti poskytnout informace.
{15488}{15560}Ulice Claire 27.
{15560}{15632}Mìla bys navštívit Alexander Tradin Corporation.
{19109}{19181}Høíšníci se nikdy nesetkají po smrti,
{19205}{19277}zatímco høích sám o sobì nikdy nezmizí,
{19277}{19349}láska také nikdy nemùže zmizet.
{19349}{19421}Odlouèení jednou ustoupí.
{19421}{19492}Krev Soldatù je pohlcena pustinou,
{19516}{19588}a vtéká do tìla.
{19778}{19804}To jsem já.
{19804}{19852}Jsi ta osoba ze vèerejška?
{19852}{19876}Jseš to ty?
{19876}{19948}Muž byl zabit v Alexander Trading Corporation.
{19996}{20068}To už jsem se také doslechl.
{20068}{20140}Muž držel okopírované papíry.
{20140}{20188}Dvì stránky z knihy.
{20188}{20260}Chtìli jsme ti dát kopii té knihy.
{20260}{20308}A teï...
{20308}{20356}Nejsou tu jiné kopie?
{20356}{20404}Originál?
{20404}{20452}Nevím, kde by mohl být originál.
{20452}{20499}Ale kopie...
{20499}{20523}Prosím, ukažte mi ji!
{20523}{20571}Situace se zmìnila.
{20571}{20619}Jsem pøíliš ohrožen.
{20619}{20691}Nemùžu se s tebou znovu setkat.
{20691}{20763}Prosím.
{20811}{20883}20:00 pøed Karionjou.
{20883}{20955}To bude naposledy.
{21459}{21530}Mireille! Mireille!
{22322}{22370}Hledala jsem tì.
{22370}{22442}Mrtvý v Alexander Trading Corporation, tos byla ty?
{22466}{22513}Ne.
{22513}{22585}Ale kdybych jsem dostala tento úkol,
{22609}{22681}bez váhání bych ho splnila.
{22705}{22777}Vím, že tì kontaktoval jeden èlánek Soldats.
{22825}{22897}Ale kvùli tomu jsem tì nehledala.
{22993}{23065}Týká se to tvojí pøítelkynì.
{23089}{23161}Mireille?
{23305}{23377}Už tedy víš o pøíkazu k vraždì?
{23401}{23473}Nìkolik pastí bylo proto nachystáno a stále se pohybují ve stínech.
{23520}{23592}Dokonce i teï...v každý okamžik.
{23616}{23688}Ano, tvoje pøítelkynì bude...
{23808}{23880}Dnes v noci v 20:00 na Yustovì námìstí.
{23904}{23952}Neznám podrobnosti.
{23952}{24000}20:00?
{24000}{24072}Je jedno, co bude fungovat jako návnada.
{24072}{24096}Jestli to jsou Soldats,
{24096}{24144}nebo hodinky,
{24144}{24216}tvoje pøítelkynì pùjde.
{24216}{24288}Myslela jsem, že to nechám na pokoji.
{24312}{24384}Není to nic víc než bìžná zkouška, které se musí èelit.
{24432}{24503}Ale..je to tvoje pøítelkynì...
{24575}{24647}Rozhodnutí je na tobì.
{24647}{24695}Zvolit cestu...
{24695}{24767}nebo...
{25079}{25151}Díky!
{25990}{26062}Mlada paní! Tady máte nazpatek!
{29658}{29730}Høíšníci se nikdy nesetkají po smrti,
{29754}{29802}Zatímco høích sám o sobì nikdy nezmizí,
{29802}{29874}láska se taky nemùže ztratit.
{29874}{29922}odlouèení jednou skonèí.
{29922}{29994}Krev Soldatù je pohlcena pustinou,
{29994}{30066}a vtéká do tìla.
{30162}{30234}To je ono?
{30234}{30306}Nechala jsi být tak dobrou stopu, abys mì zachránila?
{30378}{30450}Nešla jsi pro kopi, místo toho jsi mì zachránila?
{30593}{30665}Nìco sis zapomnìla.
{30881}{30953}Zranìné zvíøe se soustøedí pouze na svou bolest.
{30953}{31025}Jako já.
{31193}{31265}Tvoje rány musí být ještì hlubší.
{31313}{31385}Musela jsem být nesnesitelná...
{31385}{31457}Možná jo...
{31480}{31528}Každopádnì,
{31528}{31600}to chci pro jistotu najít.
{31888}{31936}Já ve tmì...
{31936}{31984}Ne.
{31984}{32056}Temnota jsem já sama.
{32281}{32353}Letmý dotyk,
{32416}{32487}mrází mì na tváøi,
{32567}{32639}koneènì jsem pochopila...že...
{32720}{32792}jak jsem se ráno probudila
{32938}{33010}zpìvem ptákù,
{33082}{33154}náhle jsem nic nevìdìla.
{33303}{33375}Nevìdìla jsem, co chce tvoje srdce.
{33530}{33602}Zírala jsem na oblohu, která
{33658}{33729}od té chvíle byla vždy jako tenkrát.
{33828}{33900}Pod mraky
{33955}{34027}jsem odhodila pryè svoje pocity...
