{1}{1}23.976
{43}{199}TaSHee's Gang uvádí
{260}{389}GANKUTSUOU
{2427}{2521}Pøátelství je nìco velmi zajímavého a krásného.
{2521}{2598}Díky síle pøátelství mohl tento mladík uniknout banditùm.
{2609}{2728}A teï, mi mùj pøítel øekl, e nic není tak nestálého jako lidské srdce...
{2770}{2782}22. KVÌTNA, BOUØE
{4124}{4179}Hej, Alberte.
{4204}{4229}Vstávej!
{4372}{4412}Nemùu uvìøit, e jsi ještì stále spal.
{4490}{4544}Víš, e jsem dnes zaneprázdnìnı.
{4544}{4587}Oèekávám dùleitého hosta.
{4587}{4641}Jestlie jsi nechtìl jet, mìl jsi zùstat doma.
{4667}{4693}Kdo je ten host?
{4693}{4737}Nìkdo, kdo mi pomohl na Lunì.
{4737}{4832}Ah, správnì. Ten Hrabì Jakékoli-bylo-jeho-jméno.
{4832}{4857}Eugénie!
{4857}{4886}Pøeháníš to!
{4886}{4981}Kdy u mluvíme o hostech, Renaud øíkal, e taky nìkoho pøivede.
{5038}{5070}Co?
{5095}{5203}Alberte, musíš bıt dobrá koøist pro šarlatány.
{5203}{5216}Co-
{5408}{5446}Nesnášejí se.
{5803}{5834}Kvùli èemu jsi tak rozzlobená?
{5845}{5867}Kvùli nièemu.
{5867}{5917}Jen si uívám jízdu.
{5917}{5955}Víš, tohle není závod.
{5955}{5987}Dobøe,
{5987}{6075}zapomnìla jsem, e ty se rád jen tak touláš...
{6075}{6111}je jedno jestli ve svém autì nebo ve svém ivotì.
{6216}{6255}To není tvá starost!
{6266}{6283}Vystup.
{6283}{6321}Dobøe, vystoupím.
{6321}{6350}U nechci bıt v tomhle autì.
{6350}{6377}O èem to mluvíš?
{6377}{6418}Jsme tu.
{6448}{6509}Opravdu nechápu, proè jsme my dva zasnoubení.
{6509}{6572}Proè teda nejedeš nazpátek v Dupréovì autì.
{6646}{6673}Oops.
{6673}{6729}Oh, tohle mi nedìlej.
{6744}{6763}Jsi v poøádku?
{6763}{6780}Ano.
{6797}{6847}Hej, Alberte!
{6847}{6879}Tady jsme!
{6890}{6919}Hej!
{6919}{6950}Jasnì.
{6961}{7023}Jsou snad eny to jediné co umíš dobøe ovládat,
{7023}{7055}pane Tajemníku?
{7055}{7142}Sem tam je potøeba nìjakého zpestøení pøi nudné cestì, ne?
{7142}{7180}Po mojí pravici nedbalı novináø,
{7197}{7257}na zadním sedadle snoubenci.
{7770}{7810}To bylo úasné!
{7810}{7832}To nic nebylo.
{7832}{7877}Pouíval jsem to pøi speciálních vojenskıch operacích.
{7890}{7937}Ah, proces zesílení svalù.
{7937}{7994}O tom jsem nìco slyšel.
{7994}{8027}Dìkuju.
{8186}{8227}U-Udìlám to sám.
{8378}{8417}Promiòte mi...
{8417}{8444}ale jak se jmenujete?
{8459}{8500}Valentina.
{8500}{8574}J-Já jsem...
{8589}{8614}Hej!
{8614}{8664}Maxmiliáne!
{8664}{8710}Omluvám se, e jsem se zpozdil!
{8740}{8771}Pøi prozkoumávání,
{8771}{8854}jsem se pøiblíil k nepøátelské skrıši!
{8854}{8940}Kdy jsem upustil mùj oblíbenı granát,
{8940}{8980}byl jsem bledı jako stìna.
{8994}{9022}Zevnitø té skrıše,
{9022}{9110}byly slyšet zvuky Eridanusianù, nìco jako "click-click-click".
{9121}{9227}Nesouhlasím s teorií, e by to byli vnímavé bytosti.
{9247}{9308}Vemte si, jestli chcete.
{9324}{9353}Dìkuju.
{9473}{9498}To je vıborné!
{9593}{9632}Franz je šastnı èlovìk!
{9632}{9734}Jednou se oení a bude moct jíst takové jídlo kadı den...
{9779}{9829}Oh, kde jsem to byl?
{9829}{9905}Oh ano, kdy jsem si myslel, e jsem skonèil,
{9905}{9962}kdo si myslíte, e se objevil?
{9983}{10022}Kapitán vesmírné kavalerie
{10022}{10069}a mùj zachránce,
{10069}{10127}Maxmilian Morrel.
{10210}{10248}Jste opravdu chlápek,
{10248}{10342}kterı hlídá idiota, kterı zabloudí do boje.
{10364}{10397}Odkud jste?
{10397}{10455}Mùj dùm je v Marseille.
{10455}{10507}Opravdu barbarské místo.
{10521}{10547}A vy jste z...
{10547}{10597}Z Paøíe, samozøejmì.
{10597}{10631}Z oblasti centra.
{10673}{10704}Marseille...
{10735}{10773}Jaké místo to je?
{10773}{10825}Kdy jsem byl dítì,
{10825}{10887}bylo to krásné pøístavní mìsto, ale...
{10887}{10992}bez ohledu na to, to není místo vhodné pro dámy.
{11509}{11554}U je to nìjaká doba, co jsme tu naposledy byli.
{11554}{11589}Pøíjemnı vánek.
{11589}{11668}Ale mraky vypadají hrozivì.
{12393}{12457}Vidíte nìco zajímavého?
{12475}{12570}Zajímá mì, proè potøebujeme rozdìlovat svìt zdmi.
{12570}{12622}Existence ohavností z vnìjšího svìta
{12622}{12713}by ještì víc podtrhla krásu království.
{12725}{12833}Ale, za tìmi zdmi je také spousta úasnıch vìcí.
{12833}{12863}Nemìli bychom
{12863}{12911}jen víc otevøít oèi?
{12911}{12994}Zmìnil se's nebo jsi dospìl bìhem cest?
{12994}{13035}Máš pravdu.
{13046}{13133}Bì ven a vezmi na sebe všechny komplikace zvenku.
{13133}{13226}Pak, se aspoò trochu zmenší tvá znudìnost.
{13262}{13315}To, na co bychom se mìli dívat, je tohle.
{13334}{13403}Nejvyšší soudní dvùr, Danglarova banka
{13422}{13516}a Velitelství vesmírnıch sil, kde pracuje tvùj otec.
{13516}{13553}To je Trojúhelník moci.
{13568}{13676}Toto jsou opravdu zázraky, které bychom mìli zdìdit, nemyslíš?
{13787}{13813}Cítím se jako...
{13813}{13869}bychom byli jediní uvìznìní.
{14220}{14318}Má osamìlost u není jen mou osamìlostí.
{14337}{14433}Jsem doprovázen bohyní pomsty.
{14454}{14500}V temnotì...
{14514}{14551}jsem oèekával úsvit.
{14577}{14619}Kdy úsvit pøišel...
{14619}{14680}proklínal jsem svou existenci, ne padla noc.
{14680}{14793}Modlil jsem se, abych ztratil své smysly.
{14793}{14826}Nicménì...
{14826}{14872}mé modlitby padaly do hluchıch uší.
{14898}{14949}Vyzıval jsem smrt,
{14949}{15073}ale Satanova chladná a nemilosrdná ruka mì drela.
{15098}{15132}Témìø...
{15144}{15177}U je èas.
{15484}{15507}Ale, ale.
{15507}{15563}To byla jízda.
{15563}{15635}Asi to byl trest za to, e jsem nešel na schùzku vlády.
{15635}{15703}U byli vybráni kandidáti na prezidenta?
{15703}{15730}Šušká se o tom,
{15730}{15795}e favoritem je pan Morcerf, ale...
{15795}{15847}Slyšel jsi nìco od otce,
{15847}{15868}Alberte?
{15882}{15958}Maxmiliáne, buï okolo Beauchampa opatrnı.
{15958}{16029}Je to hroznı mu, kterı vyuije i skandály vlastních pøátel,
{16029}{16064}aby mìl èlánek na první stranì.
{16064}{16132}Tomu se øíká kouzlo nezávislé urnalistiky.
{16143}{16188}Èasto ètu vaše èlánky,
{16188}{16234}ale moc nesouhlasím s jejich obsahem.
{16250}{16293}Èasto mi to øíkají.
{16393}{16417}Kde jsou dámy?
{16417}{16482}Øíkaly, e jejich obleèení bylo pøíliš vlhké nebo nìco, tak šly domù.
{16495}{16528}Renaudova staroitnost taky.
{16528}{16582}Kdyby se mi zmínily, odvezl bych je domù.
{16582}{16654}To je jako házet jídlo opici.
{16713}{16755}Take, Hrabì Monte Christo.
{16773}{16819}To není pøíliš známé jméno.
{16823}{16877}Ve Vládní kanceláøi o nìm není ani zmínka.
{16877}{16940}Moná je to vetøelec, nebo...
{16940}{16990}nebo klaun, nebo podvodník.
{16990}{17036}Rád bych zastavil vaše kritizování
{17036}{17084}váeného hosta rodiny Morcerf.
{17084}{17179}A kdy jsi øíkal, e jsi toho váeného hosta poznal?
{17179}{17244}Minulé jaro o karnevalu na Lunì.
{17253}{17330}Zøejmì jak byl synek unesen bandity.
{17330}{17371}Smìšné.
{17371}{17449}Nebyl jsi sveden nìjakou draèicí z Luny nebo nìco?
{17662}{17696}Sakra...
{17834}{17864}A pak
{17864}{17913}mì Hrabì zachránil.
{17924}{17987}Take další zachránce.
{17987}{18106}To je pravda. Je extrémnì bohatı a velkorysı.
{18106}{18231}A byl mìšec toho chlápka pøecpanı falešnımi penìzi?
{18232}{18256}Podívej se na tohle.
{18262}{18313}Nemohl by mít nìco tak nádherného
{18313}{18373}kdyby nebyl z nìjaké zajištìné domácnosti.
{18386}{18465}Šarlatáni èasto pouivají vìci jako je tahle,
{18471}{18515}kdy zkouší získat nìèí dùvìru.
{18515}{18546}Není to šarlatán!
{18567}{18607}Velí obrovské vesmírné lodi,
{18607}{18691}doprovází ho krásná ena z Vıchodního vesmíru |a také "mimozemšané" jako sluhové,
{18696}{18756}je osvobozen od státních autorit
{18756}{18855}a svobodnì se stıká s lidmi ze všech tøíd.
{18864}{18935}Je nekonventní v kadém smìru.
{18935}{18962}A...
{18962}{19002}kdy padne noc...
{19002}{19087}prochází se temnotou a pátrá po krvi krásnıch en.
{19087}{19165}Nebyl bych pøekvapenı, kdyby to byla pravda.
{19165}{19231}Hrabì je chladnı, a si èlovìk myslí,
{19231}{19263}e mu nezáleí na ivotì jinıch.
{19263}{19287}Franzi!
{19522}{19569}Uklidni se, Alberte.
{19606}{19711}Pøed nìjakım èasem se jeden cestovatel nakazil |nìjakou nemocí z nìjaké planety,
{19711}{19789}a pak se procházel okolo a sál krev, kde mohl.
{19789}{19838}Buï opatrnı, Alberte.
{19838}{19912}Slyšel jsem, e mají rádi krev panen.
{19912}{19945}Upíøi?
{19945}{19970}Nesmysl.
{19970}{20016}Je to pravdìpodobnìjší, ne bandité na Lunì.
{20016}{20085}Nebo velkorysı, bohatı mu.
{20180}{20250}Právì pøijela jeho Excelence, Hrabì Monte Christo.
{20410}{20445}Okamitì ho uvìï-
{21237}{21265}Omlouvám se.
{21265}{21313}Dveøe byly otevøené.
{21337}{21383}Je mi ctí znovu vás vidìt.
{21408}{21475}Jsem to já, kdo je poctìn, Vikomte de Morcerf.
{21475}{21547}Prosím, øíkejte mi Alberte.
{21547}{21607}Pøeci se známe, ne?
{21629}{21697}Jak jsem slíbil, pøedstavím vás mım pøátelùm.
{21718}{21774}Franze u znáte.
{21774}{21819}To je Lucien Dupré.
{21819}{21933}Vzhledem k jeho vìku, je velmi dobrım úøedníkem |a také má pozici na Ministerstvu vnitra.
{21933}{21959}Beauchamp
{21959}{21995}je novináø.
{21995}{22066}Mùete se jich zeptat na cokoli ohlednì Paøíe.
{22066}{22160}Mé "noviny", jak jim øíká, jsou spíše bulvární plátek.
{22160}{22213}Opravdu zajímavé.
{22225}{22284}Kavalérní kapitán Maxmilián Morrel,
{22284}{22341}hrdina z Eridanuské války.
{22341}{22376}Rád vád poznávám.
{22376}{22469}Model vojáka, kterı je upøímnı a odánı.
{22486}{22531}Znáte kapitána?
{22531}{22564}Oh, ne.
{22564}{22661}Slyšel jsem, e jste pøijel z velmi vzdáleného místa.
{22661}{22707}U dìláš interview?
{22707}{22736}Nebuï neslušnı.
{22736}{22782}Hej, je to moje práce.
{22848}{22892}Ve vìtšinì svìtù,
{22892}{22960}se na fotografie dívají jako na nechutnı zvyk.
{22960}{23004}Prosím, nedìlejte je.
{23004}{23047}Ah, omluvte mì.
{23058}{23136}Bìhem mıch cest po èetnıch zemích,
{23136}{23232}jsem se stal souèástí jejich zvykù.
{23243}{23278}Jsem si jistı, e paøískému lidu,
{23278}{23346}jako mì, se to musí zdát barbarské.
{23359}{23407}Jaká místa jste navštívil?
{23407}{23482}Cestoval jsem po rùznıch zemích:
{23482}{23518}Vıchodní vesmír,
{23518}{23552}Severní vesmír,
{23552}{23629}a také Centrum galaxie.
{23629}{23662}Území Impéria také?
{23662}{23682}Samozøejmì.
{23698}{23759}Nejsou ádné hranice pro nìkoho, kdo pluje hvìzdami.
{23759}{23832}Není to však zrada vùèi Impériu?
{23832}{23901}Nemám dùvod slibovat vìrnost
{23901}{23955}lidem, kteøí mì neochraòují.
{23955}{24003}Øíkám to špatnì?
{24003}{24080}Velmi troufalı názor.
{24080}{24114}Aha.
{24132}{24248}Mìl byste si zkusit zaít ohromnı vesmír sám.
{24248}{24351}Potom byste pochopil, e èlovìk se mùe spoléhat jen sám na sebe.
{24470}{24519}Pøipravte èaj.
{24637}{24674}Odkud jste?
{24691}{24799}Narodil jsem se v zemi mimo vaši pøedstavivost.
{24799}{24835}Oh?
{24848}{24897}Je to nìkde o èem nemùete mluvit?
{24958}{24998}Nebuï drzı, Franzi!
{25001}{25057}Nemyslíš si, e bychom mìli vìdìt aspoò tohle
{25057}{25113}jestlie se pøedpokládáme spøátelit?
{25113}{25148}Docela pochopitelné.
{25148}{25211}Je to proto, e jsem zahalen záhadami,
{25211}{25260}e se mui jako vy,
{25260}{25327}zajímají o nìkoho jako jsem já?
{25336}{25371}Kdyby tomu tak nebylo,
{25371}{25431}nepøichystali byste takové uvítání
{25431}{25518}pro vesnického šlechtice ze vzdálené oblasti vesmíru.
{25590}{25628}Dobøe, prokoukl nás.
{25643}{25746}Ale to je to, proè o vás chceme vìdìt víc, Hrabì!
{25746}{25801}Jsi stále naivní, e?
{25868}{25885}Peppo?!
{25898}{25925}Nìco se dìje?
{25925}{25955}Eh,
{25955}{25989}nic.
{26522}{26554}Co tím sleduješ?
{26583}{26615}Skonèila jsem a pøijela sem.
{26629}{26684}Opustila jsem bandity,
{26684}{26772}tak jsem pøijela do Paøíe hledat práci.
{26772}{26822}Ale, jak si's našla tohle místo?
{26830}{26886}Pøijela jsem, abych tì našla, Alberte.
{26922}{26953}Oh, dìlám si legraci.
{26953}{26977}Je to jen náhoda.
{26977}{27013}Prostì se to takhle stalo.
{27026}{27083}Hej, Peppo.
{27083}{27151}Aha, pamatuješ si mé jméno.
{27151}{27198}Hodláš tu zùstat?
{27198}{27235}Nechceš mì tu?
{27235}{27260}No, hm...
{27260}{27297}Jak bych to øekl...
{27310}{27344}Nìdìlej si starosti.
{27344}{27417}Pøísahejme si, e to bude naše tajemství.
{27496}{27553}Obáváš se identity toho mue?
{27588}{27621}Nedìlej si takové starosti.
{27621}{27653}Není to nikdo zvláštní.
{27653}{27697}Co chcete dìlat dnes veèer?
{27697}{27751}Co takhle vyrazit do Le Queen?
{27751}{27806}Ne, to vynechám.
{27806}{27856}Taky to vynechám.
{27899}{27925}Co to je?
{27957}{28021}Hlas Hrabìte Monte Christa...
{28021}{28055}Co s tím?
{28080}{28107}Není nahranı.
{28139}{28183}"Jaká místa jste navštívil?"
{28252}{28278}"Území Impéria také?"
{28383}{28412}"Není to zrada vùèi Impériu?"
{28412}{28444}Nahrávaè musí bıt porpouchanı.
{28444}{28512}A tohle je taky porouchané?
{28879}{28934}Je velmi krásná.
{28955}{28985}T-To je moje matka.
{29017}{29059}Je docela mladá.
{29099}{29169}To je vıjev z Marseille, e?
{29169}{29200}Má ráda to místo.
{29212}{29279}Nevím, proè si ho vybrala.
{29279}{29333}Ah, je to úasné.
{29333}{29400}Nicménì, mùj otec nemá ten obraz rád.
{29400}{29442}Chtìl ho spálit,
{29442}{29495}tak jsem se rozhodl dát ho do svého pokoje, a pak se uklidnil.
{29576}{29595}Edmonde...
{29673}{29704}Je na tom obraze nìco, co vás zaujalo?
{29704}{29725}Ah, ne.
{29725}{29773}Mìl bych u jít.
{29782}{29815}Prosím, neøíkejte to!
{29815}{29863}Prosím, zùstaòte s námi na veèeøi.
{29863}{29958}Mùj otec a matka se tìšili, a vás poznají.
{29958}{29997}Jestlie vás zajímá malíøství,
{29997}{30074}támhle jsou další obrazy z kolekce mıch rodièù.
{30211}{30277}Jak odvánı obraz.
{30277}{30311}Otec má rád takové obrazy.
{30311}{30371}Obrazy mé matky jsou támhle.
{30518}{30563}Ah, je tohle náš host?
{31477}{31567}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31615}{31677}www.mycolorfullife.blog.cz
