{1}{1}23.976
{53}{235}TaSHee's Gang uvádí
{278}{401}GANKUTSUOU
{2446}{2494}Dobrı veèer, dámy a pánové.
{2517}{2591}Jednoho bouølivého dne na konci jara,
{2591}{2691}jsem já a mùj pøítel dorazili do Paøíe, kde nás oèekával chlapec.
{2715}{2839}Tiše se tøesu tìmi pøebyteènımi emocemi,
{2839}{2907}jak se èas našeho opìtovného shledání pøiblíil.
{3000}{3045}Ah, to je náš host?
{3457}{3510}Pokud je všechno v poøádku, Hrabì,
{3510}{3585}byl bych rád, abyste se k nám pøidal na veèeøi a se poznáte s rodièi.
{3775}{3797}Hrabì?
{3894}{3937}Jestlie to nebude pøíliš problematické.
{3961}{3988}Musím na tom trvat.
{3988}{4065}Zachránil jste ivot našeho syna.
{4085}{4151}Vítejte, Hrabì Monte Christo.
{4352}{4407}MATÈINO TAJEMSTVÍ
{4502}{4598}Na našeho nového pøítele, Hrabìte Monte Christa.
{4723}{4746}Opravdu?
{4760}{4843}Je mi trapnì, e víte o taení na Janinu.
{4868}{4944}Aèkoli jsem velebenı lidem jako hrdina,
{4944}{5007}musím øíct, e pro vojáka to pøíliš neznamená.
{5021}{5086}Kdy znièíme, nic nevytvoøíme.
{5086}{5111}Nesouhlasím.
{5111}{5201}Tato klidná doba vyhledávala obìti.
{5201}{5244}To je to, v co vìøím.
{5244}{5309}Ale, jsem si jistı, e jméno Generála Morcerfa
{5309}{5365}je známo po celé galaxii.
{5365}{5411}Jsem potìšen.
{5774}{5798}Omluvte mì...
{5809}{5866}ale bylo to jídlo, které nemáte rád?
{5896}{5926}Oh, ne!
{5926}{5980}Prosím, neznepokojujte se.
{5980}{6076}Zvykl jsem si moc nejíst.
{6110}{6180}Rozumím tomu, jak se cítíte.
{6180}{6313}V tìchto letech, jsem zaèal bıt unaven tìmito luxusními jídly.
{6329}{6405}Navíc, poslední dobou ani moc nespím.
{6434}{6491}Jsem pøekvapenı, e vaše zdraví netrpí.
{6523}{6566}To díky tomuto.
{6592}{6621}Nìjaké vesmírné jídlo?
{6634}{6710}Na konci let, kdy jsem cestoval tím moøem hvìzd,
{6710}{6804}se mé srdce a má duše zmìnily.
{6804}{6908}Kdybyste mohl jíst alespoò trochu...
{6908}{6986}Je úzkostné, jestlie nemùete jíst ani spát.
{6986}{7023}Úzkostné?
{7033}{7056}Aha.
{7128}{7180}Pak si tedy vezmu toto.
{7210}{7228}Prosím.
{7577}{7626}Toto pøivádí zpìt vzpomínky.
{7626}{7660}Vzpomínky?
{7667}{7765}Ochutnal jsem podobné vıborné jídlo na jihu Francie.
{7804}{7882}To je jídlo, které dìláš èasto, e, matko?
{7882}{7921}A-Ano...
{7921}{8008}Je moné, e jste z Marseille?
{8008}{8039}Ne.
{8039}{8129}Moje ena je znaènì odlouèena od nekulturních oblastí.
{8129}{8178}Není ro pravda, Mercédés?
{8178}{8213}A-Ano...
{8237}{8269}Oh, aha...
{8269}{8305}Nìco se dìje?
{8330}{8384}Jeden mùj pøítel je odtamtud.
{8397}{8481}Jmenuje se Maxmilian Morrel, ale je to velmi milá osoba.
{8481}{8513}Morrel...
{8548}{8590}Omluvte mou drzost.
{8590}{8657}Prosím, nenechte si tím zkazit náladu.
{8690}{8719}To nic...
{8734}{8851}Kdy se vrátíte zpìt, zjistíte, e naše rodina je pokrevnì| spøíznìná s jednou mocnou katalánskou rodinou.
{8866}{8938}Moje ena pøipravuje toto jídlo u od dob, co byla malá.
{8967}{9027}Jste pøátelé z dìtství?
{9027}{9063}Ano, jsme.
{9063}{9108}Nedivím se, e jste si tak blízcí.
{9108}{9162}Závidím vám.
{9178}{9287}I nìkdo jako vy pociuje závist, Hrabì?
{9297}{9324}Samozøejmì.
{9324}{9394}Jestlie je nìkdo tak dokonalı jako váš otec.
{9416}{9473}No, pøineste Hrabìti nìjakı drink.
{9473}{9505}Jeho sklenice je prázdná.
{9704}{9775}Prosím zùstaòte tu tak dlouho, jak vám vaše plány dovolí.
{9775}{9871}Kdy jsme tu tahle, cítím jako bychom byli rodina.
{10119}{10181}Jak opojná vùnì.
{10192}{10217}Hrabì...
{10237}{10278}Jsou tu muškátové oøíšky.
{10298}{10353}Jste unavená?
{10353}{10374}Ale ne.
{10386}{10522}Omlouvám se, e jsem vás pøedtím tak dùraznì nutila jíst.
{10522}{10547}Nemusíte se omlouvat.
{10547}{10617}Je to vıborné jídlo, které jsem chtìl znovu ochutnat.
{10632}{10689}Byl jsem v ráji.
{10699}{10742}Je to jen venkovské jídlo.
{10742}{10818}Ale, jsem ráda, e to øíkáte.
{10898}{10954}Slyšel jste nìkdy o tomhle pøísloví?
{10954}{11041}Ti, kteøí sdílejí chléb a sùl pod jednou støechou
{11041}{11114}se stanou pøáteli navìky.
{11126}{11188}To je báje z Vıchodního vesmíru, ne?
{11188}{11211}Ano!
{11211}{11329}Take my jsme ji pøátelé... navìky.
{11344}{11418}Nicménì, toto není Vıchodní vesmír...
{11434}{11462}Toto je Paøí.
{11474}{11613}V Paøíi, kromì sdílení chleba a soli, vìèné pøátelství nemùe existovat.
{11675}{11730}Ta polévka byla opravdu vıborná.
{11730}{11810}Teplá, vyvolávající minulost.
{11839}{11885}To je utìšující vìc...
{11885}{11962}jako moøskı vánek vanoucí pøes Støedozemní moøe.
{11962}{11982}Omluvte mì...
{11992}{12068}ale jste v Marseille hodnì známı, Hrabì?
{12080}{12126}Jsem, v jiném smyslu...
{12174}{12260}ale nemohlo by to tak bıt, kdybych o ní nic nevìdìl.
{12305}{12337}Nevìra, pletky...
{12337}{12383}a flirtování ve tmì noci.
{12397}{12490}Je to jak se šeptá, i aristokraté opravdu dìlají takové vìci.
{12490}{12524}Neøíkej takové sprosté vìci!
{12534}{12579}Hrabì je mùj pøítel!
{12579}{12622}Jsi ještì dítì!
{12634}{12723}Kdyby se lidé mohli stát pøáteli jen sdílením chleba a soli,
{12723}{12757}nikdo by netrpìl.
{12757}{12780}O èem to mluvíš?
{12796}{12853}Jednoho dne se pouèíš, chlapeèku.
{13042}{13167}Opravdu vám dìkuji za strávení dnešního dne.
{13167}{13193}Oh, prosím.
{13193}{13298}Je mi ctí, e jsem vás mohl pøedstavit mım rodièùm.
{13315}{13344}Obdivuju vás.
{13389}{13414}Vánì?
{13414}{13508}Rád bych vás v blízké budoucnosti pozval do mého sídla na Champs-Élysées.
{13537}{13561}Rád pøijdu!
{13588}{13621}Je to opravdu záhadnı mu, e?
{13621}{13659}Hrabì Monte Christo.
{13671}{13692}Ano...
{13692}{13783}Byla v nìm ovšem jakási strohost, která nedovolí lidem, aby se mu pøiblíili.
{13783}{13882}Ah, ve srovnání s ním jsou ostatní Paøíané nudní.
{13882}{13900}Ale, ale.
{13914}{13965}Moná to nevíš, Matko,
{13965}{14001}ale Paøí není svìt.
{14023}{14110}Venku za zdmi, je nezmìrnı a úchvatnı svìt.
{14128}{14195}Zmìnil jsi se od té doby, ne jsi odjel na Lunu.
{14195}{14273}Má cesta teprve zaèala.
{14273}{14350}Prosím, neodjídìj daleko.
{14365}{14458}Zkus si udret pøátelství s hrabìtem v rámci pøimìøenıch mezí.
{14458}{14488}Oh prosím, matko.
{14488}{14542}Zníš jako Franz.
{14542}{14607}Dobøe, pøestoe je trochu podezøelı,
{14607}{14688}není bezpodmíneènì špatnou vìcí pro rodinu Morcerfù, |aby si udrela vztah s nìkım jako je on
{14688}{14771}od té doby co debutujeme v politice.
{14840}{14922}Proboha, proè aristokraté vdycky jí-
{14922}{14983}Veèírky, èajové dıchánky a plesy.
{14983}{15036}Dobrá, nejspíš nemají co dìlat.
{15053}{15078}Jinımi slovy,
{15078}{15170}kdyby si's odmyslel obérství, chtíè a chamtivost, nezbyde z nich nic.
{15170}{15212}Zacházíš daleko.
{15233}{15270}Nebyl dnešní host
{15270}{15333}kultivovanı a docela hezkı?
{15333}{15356}Myslíš si to?
{15356}{15388}Byl nevzdìlanı.
{15388}{15420}Ale poslouchej,
{15420}{15509}mìli s paní hezkı okamik pod møíkou s hrozny.
{15516}{15534}Oh, opravdu?
{15534}{15640}Myslela jsem si, e paní byla vdy vìrná svému mui.
{15640}{15732}Nemyslíš si, e dámy by podlehly šarmu hrabìte, ne bys øekl švec?
{15732}{15772}U pøestaò!
{15833}{15903}Bezpochyby se tváøila jako zamilovaná ena.
{15912}{15955}Jestli nepøestaneš, øeknu to paní.
{15955}{15987}Oh, bojím se.
{16036}{16059}Smìšné.
{16059}{16118}Ze všech lidí, by má matka nikdy nemohla...
{16310}{16329}Matka?
{16492}{16553}Na èí fotografii se to dívá?
{16732}{16794}Bojíš se mì?
{16812}{16830}Ne.
{16830}{16890}Budu vás navdy následovat.
{16890}{16963}I kdyby to znamenalo, e budu pokraèovat cestou ke zkáze.
{16980}{17019}Ti, kdo budou znièeni...
{17019}{17053}nebudeme my.
{17539}{17575}Vrátil jsem se...
{17599}{17623}Otèe...
{18012}{18035}Ty jsi stále tady?
{18108}{18132}Hej, nedotıkej se toho!
{18132}{18163}Bohuel pro tebe,
{18163}{18248}jsem se zalíbila tvému otci a musím tu na chvíli zùstat.
{18248}{18275}Zalíbila se's mu?
{18288}{18367}Znamená to, e tvùj otec... je taky mu.
{18438}{18481}Vynech špatné vtipy.
{18481}{18531}Dobøe, mimo tvého otce,
{18531}{18611}by si's spíš mìl dìlat starosti o svou matku, ne?
{18611}{18645}Co tím myslíš?
{18659}{18755}Myslím, jak se upøenì dívala na fotografii mladého mue.
{18776}{18799}Vidìla jsi ji?
{18799}{18863}Na té fotce byl bezpochyby mu...
{18863}{18911}a nebyl to pán.
{18976}{19004}Rozumím.
{19004}{19108}Jsem si jistá, e bych taky mìla depresi, kdyby| má matka zírala na fotku cizího mue.
{19108}{19141}Není to tak, vypadni!
{19141}{19168}Jak chceš.
{19507}{19556}Nevìdel jsem, e jsi tady, Eugénie.
{19556}{19606}Jako obvykle jsi vstával pozdì.
{19606}{19654}Co je to za šaty?
{19677}{19702}Co?
{19702}{19763}Suknì se k tobì nehodí.
{19763}{19819}Nepøijela jsem tady, abych tì vidìla.
{19831}{19876}Tak mì neotravuj, abych vstával.
{19910}{19974}Já jsem ta, co tì nechala probudit, Alberte.
{20110}{20135}Nìco se dìje?
{20153}{20164}Ne.
{20164}{20235}Není Eugénie tvá snoubenka?
{20235}{20304}Myslím si, e je pro ni pøirozené, aby tì pozdravila.
{20310}{20345}Dobøe, to je pravda, ale...
{20345}{20399}Eh, nìkam jdete?
{20399}{20454}Jdeme nakupovat!
{20454}{20501}Pojïmì, madam.
{20597}{20702}Mimochodem, slyšela jsem, e jsi byl pozván do sídla Hrabìte Monte Christa.
{20715}{20737}Jak o tom víš?
{20737}{20787}Slyšela jsem to od Franze.
{20787}{20856}On a Maxmilián byli také pozváni.
{20870}{20898}Ty dva pozval taky?
{21286}{21306}Ta dívka...
{21342}{21379}Co to dìláš, Peppo?
{21393}{21425}Oh, ahoj, Alberte.
{21425}{21460}Neøíkej mi "oh, ahoj"!
{21460}{21496}Hraješ si se šperky mojí matky!
{21496}{21536}Ale jsou tak krásné!
{21547}{21630}Jestli tì uvidí mùj otec, vyhodí tì!
{21630}{21664}Dobøe, dobøe.
{21664}{21700}Tak já je vrátím, dobøe?
{21700}{21728}Vrátím je.
{21905}{21965}Ta zásuvka... Rozrušuje tì, co?
{21976}{22060}Zdá se, jako by tam byl schován nìjakı matèin poklad.
{22137}{22156}Nemùe to bıt...
{22156}{22259}Oh, kadı má tajemství.
{22259}{22351}Jako ty a já máme tajnou noc.
{22351}{22416}Byl jsem to já, kdo byl tebou oklamán!
{22446}{22519}Kdybys chtìl tu zásuvku otevøít, øekni mi.
{22519}{22569}Jsem opravdu dobrá na otvírání zamèenıch vìcí.
{22587}{22646}Pøestaò a dìlej svou práci!
{22646}{22677}Dobøe.
{23053}{23084}T-To nemùe bıt.
{23105}{23172}Proè má matka... fotku hrabìte...
{23358}{23391}To je smìšné.
{23391}{23433}Èeho se tak bojím?
{23864}{23921}Vítejte, pane Morcerfe!
{24243}{24275}Pùsobí tak vznešenì a mocnì, e?
{24472}{24492}Jaké to je?
{24503}{24532}Nevypadám divnì?
{24532}{24580}Opravdu vám to sluší.
{24620}{24634}Co?
{24634}{24666}Jsem ráda,
{24666}{24706}e vypadáš tak neoèekávanì dobøe.
{24730}{24753}Díky.
{24753}{24848}Jestlie jdeš ale navštívit Hrabìte,
{24848}{24888}není tvùj zjev trochu prostı?
{24923}{24987}Trochu... prostı?
{25114}{25145}Alberte...
{25145}{25201}Co to máš na sobì?
{25201}{25229}Je to divné?
{25229}{25262}"Divné" by bylo zmírnìné...
{25263}{25320}Kdo rozumí aristokratùm...
{25320}{25366}Proè vypadáš jako pirát?
{25386}{25410}Dùleitìjší je,
{25410}{25454}proè jsi tady Beauchampe?
{25454}{25565}Pøece si nenechám ujít monost k interview s hrabìtem.
{25590}{25622}Oh, jasnì...
{25622}{25698}Jestli je tohle všechno moné, tak bych rád jel sám.
{25737}{25800}Kdy jsem tì poprvé potkala,
{25822}{25945}jsi mi pøipomnìl, e vdy existuje nadìje, nezáleí na èase ani na místì.
{25973}{26041}Nezapomenu na to.
{26092}{26114}Nadìje...
{26151}{26288}Jediná vìc, kterou jsem mìl, kdy jsem byl vren
{26328}{26435}z Chateau d'If do širé, temné galaxie...
{26742}{26764}Je to tady, ne?
{26764}{26825}Ano, to je Champs-Élysées, èíslo 30.
{26825}{26847}To je ono.
{26847}{26917}Na sídlo Hrabìte je to dost tlumené.
{26917}{27054}Pøedstavoval jsem si nìco, co by mohlo rozèílit prosté obèany, kdy to uvidí.
{27242}{27292}Vítejte, pánové.
{27292}{27336}Oèekáváme vás.
{27381}{27419}Rané rokoko...
{27419}{27460}A není to obnovené.
{27528}{27556}Úasné, ne?
{27556}{27627}Ah, no, tento svìt se od mého trochu liší.
{27680}{27725}Dìkuji vám, e jste poèkali.
{27725}{27786}Zavedu vás za Hrabìtem.
{27828}{27844}Co to je?
{27844}{27870}Klesáme!
{27903}{27943}Kam jedeme, Baptistine?
{28348}{28364}Zastavilo se to.
{28452}{28476}Vítejte.
{28476}{28506}Hrabì vás èeká.
{28534}{28559}To je...
{28999}{29054}Má to ten samı vkus,
{29054}{29098}sloupy a podlaha jsou potaeny zlatem.
{29098}{29178}Kde jeden najde tolik zlata?
{29197}{29259}To je to, proè øíkám, e je podivnı.
{29259}{29332}Nakonec bude i jeho postel a polštáøe ze zlata.
{29332}{29384}Nemohl bych spát, protoe to strašnì záøí.
{29384}{29415}Hej, podívejte!
{29478}{29501}To je...!
{29523}{29542}Oceán...
{29542}{29585}Ne, poèkejte! Podívejte se na oblohu!
{29639}{29676}Je to umìlé?
{29688}{29714}Nemoné...
{29736}{29797}Tyhle fotky samotné jsou dobrı materiál.
{29966}{30007}Nádherné...
{30055}{30074}Ta scenérie...
{30252}{30296}Ten odìv vám sluší,
{30296}{30327}pane Piráte.
{30327}{30349}Hrabì.
{30448}{30460}Pr-
{30720}{30778}Pokud byste chtìl, pøijmìte toho jako dárek,
{30778}{30809}pane Piráte.
{30947}{31024}Tento meè mi byl darován jedním navigátorem.
{31065}{31092}Meè vás ochrání
{31103}{31174}a otevøe vaši cestu...
{31174}{31207}Mùe bıt velmi uiteènı.
{31501}{31573}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31623}{31683}www.mycolorfullife.blog.cz
