{1}{1}23.976
{60}{157}TaSHee's Gang uvádí
{272}{383}GANKUTSUOU
{2444}{2557}Opìt jsem byl spojen s chlapcem v domì mého pøítele.
{2577}{2782}Jeho duše, která nevìdìla, co je to láska, byla otøesena tím, kterı lásku znal.
{2811}{2878}"Miluješ svou snoubenku?"
{2990}{3117}Mùj ivot je... prázdnı a prchavı.
{3517}{3551}Cítím, e se vìci ujasní,
{3551}{3633}kdy budu ménì myslet na vyhlídku svatby s Eugénií.
{3633}{3679}Co to povídáš?
{3679}{3712}Nemùu øíct...
{3711}{3797}jestli ji vlastnì miluju nebo ne.
{3819}{3830}Hej!
{3951}{4004}Obáváš se nìèeho takového?
{4004}{4030}Co?
{4044}{4083}Nejdøív formality.
{4083}{4125}Pocity a potom.
{4125}{4137}Hej!
{4213}{4246}Pane Alberte,
{4246}{4343}poslíèek Hrabìte Monte Christa vám tohle pøinesl.
{4343}{4364}Od Hrabìte?
{4377}{4405}Pozvánka do opery.
{4424}{4491}Mìl jsem velké štìstí
{4491}{4544}získat v opeøe lóe.
{4544}{4633}Jesli budete chtít, zastavte se dnes veèer
{4633}{4692}s vaší snoubenkou.
{4692}{4806}To je na operu vzácné, e má dostupné lóe.
{4806}{4830}Ano.
{4830}{4916}Promiòte, ale mohla byste to doruèit Eugénii?
{4916}{4969}Doruè to sám, Alberte.
{4969}{4996}Otèe...
{4996}{5104}Kousek po kousku, taková pozornostt na ni zapùsobí.
{5151}{5167}Hej!
{5167}{5228}JEJÍ DEPRESE, MÁ DEPRESE
{5404}{5443}Dnes ráno to není zapotøebí.
{5460}{5516}Mohl by to bıt... Lord Dupré?
{5538}{5559}Pøichází dcera naší paní.
{5611}{5676}Dobré ráno, sleèno.
{5676}{5700}Dobré ráno.
{5700}{5752}Má matka stále spí?
{5752}{5793}Ano, vypadá to tak.
{6258}{6314}Ah, dobré ráno Eugénie.
{6314}{6354}Jsi krásná jako vdycky.
{6370}{6392}Dobré ráno.
{6413}{6455}Zùstal jsi pøes noc.
{6661}{6686}Otèe,
{6686}{6719}vychladne ti polévka.
{6719}{6772}Ah ano, máš pravdu.
{6893}{6943}Dobré ráno, Barone.
{6943}{6982}Ah, dobré ráno.
{6982}{7026}Vyspal jste se dobøe?
{7026}{7069}Ano, dìkuji za vaše pohostinství.
{7126}{7145}Mimochodem,
{7145}{7176}o Dùlním prùmyslu Olympus...
{7254}{7289}Není o tom pochyb.
{7304}{7319}Aah!
{7319}{7378}Dìkuji za dùleitou informaci!
{7390}{7502}Zamyslím se nad tím, jak vhodnì odmìním ty, |kteøí dávají informace mì a ne ostatním.
{7502}{7530}Pokud nespìcháte,
{7530}{7583}nedáte si s námi snídani?
{7867}{7925}Dìkuji za pozvání.
{7925}{8020}Zrovna jsem to chtìl doruèit Eugénii.
{8025}{8091}Také smìøuji k Baronu Danglarsovi,
{8091}{8139}abych mohl projednávat obchodní záleitost.
{8139}{8181}Jaká náhoda!
{8181}{8244}Prosím, dovolte mi, abych vás mu pøedstavil!
{8254}{8298}To je to, v co doufám.
{8308}{8338}Na tom místì je spousta vìcí,
{8338}{8389}které vzbudí váš zájem.
{8410}{8426}Vím!
{8426}{8486}Jestli máte èas, necháme je, aby vám ukázali stáje!
{8498}{8608}Nejlepšího konì v Paøíí, Eclipse, vlastní paní!
{8608}{8629}Opravdu?
{8689}{8712}Tudy, prosím.
{8712}{8767}Poèkejte prosím v salónu.
{8767}{8790}Alberte!
{8805}{8828}Luciene!
{8828}{8864}Co tu dìláš tak brzy ráno?
{8884}{8937}Jsem zamìstnán v mnoha smìrech.
{8978}{8996}Eugénie!
{8996}{9013}Dobré ráno.
{9072}{9097}Jestli jsi mu,
{9097}{9147}musíš bıt opravdu šikovnı,
{9147}{9167}správnì?
{9167}{9199}Hrabì!
{9199}{9268}Dovolte mi mít tu èest pozvat vás do mého domu!
{9268}{9309}To by mohlo bıt úasné. Dìkuji.
{9310}{9337}Oh, ano!
{9337}{9381}Pøijdu pozdìji do tvého pokoje.
{9687}{9760}Michéle, akcie Dùlní spoleènosti Olympus zaèaly klesat.
{9760}{9843}Budeme pøedstírat podporování akcií, a pak |je odstarníme veškerımi našimi podporami.
{9843}{9891}Mohlo by bıt nebezpeèné jich koupit více.
{9905}{9954}Brzy akcie spadnou pod opìrnou úroveò.
{9966}{9988}To je mi jedno.
{9988}{10039}Poèkej a spadnou na dno, a pak všechny vykup!
{10039}{10077}Rozumím.
{10107}{10185}Spousta investorù po tomhle bude viset!
{10196}{10306}Hrabì Monte Christo na vás èeká v salónu, pane.
{10306}{10341}Aha!
{10341}{10433}Máš finanèní hodnocení Hrabìte Monte Christa, Michéle?
{10433}{10467}Z vızkumù tøí agentur,
{10467}{10510}dvì z nich mu dali status AA+,
{10510}{10551}a jedna mu dala dokonce status AAA.
{10564}{10608}Jeho titul byl takté ovìøen.
{10621}{10687}Vsadím se, e si ho koupil za hromadu penìz!
{10751}{10799}Ah, omlouvám se, e jsem vás nechal èekat!
{10799}{10853}Oh, ty jsi tu taky, Alberte?
{10853}{10907}Dobré ráno, Barone.
{10907}{10961}Toto  je Hrabì Monte Christo.
{10961}{10996}Chtìl jsem vám ho pøedstavit.
{11033}{11151}Hrabì se zmínil, e nemìl ádnou bankovní pøízeò,
{11151}{11238}tak jsem pocítil, e vám ho musím pøedstavi, Barone.
{11238}{11288}To je obdivuhodné myšlení.
{11288}{11375}Vítám pøedstavení vıznaènıch klientù.
{11375}{11448}Toto je právì teï nejúspìšnìjší bankéø v Paøíi,
{11448}{11481}Baron Danglars.
{11481}{11514}Dìkuji
{11529}{11559}za uvedení.
{11664}{11698}Hej, ten flek taky.
{11699}{11786}Prosím buï opatrnìjší, kdy obsluhuješ Eclipse.
{11786}{11819}Ano, paní.
{11819}{11911}Nikdy mu nedávej nic jiného, ne predepsané jídlo.
{11911}{11941}Ano, paní.
{11983}{12089}Dopis o zavedení a smlouva vám budou zaslány od Thomson a French.
{12101}{12208}Upøímnì øeèeno, jsem pøekvapenı, e se firma zaruèila za jednotlivce.
{12227}{12297}Je to nejvìtší finanèní instituce ve Vıchodním vesmíru.
{12297}{12337}No, ano.
{12337}{12441}Ale ve smlouvì je jedna pøekáka.
{12441}{12491}Oh? Pøekáka?
{12491}{12596}Podle tohoto dokumentu, je pro pùjèky stanovenı maximální limit.
{12619}{12682}Jinımi slovy, pokud si bude hrabì pøát,
{12682}{12758}naše banka ho mue financovat bez maximálního limitu.
{12758}{12841}Tímto zpùsobem by mìla bıt smlouva vytvoøena.
{12841}{12887}Pøedpovídáte s tím nìjaké problémy?
{12934}{12980}Máte mì...
{12980}{13034}Je to nepøedvídatelné.
{13034}{13117}Jedostranné obchody v tomto svìtì neexistují.
{13117}{13244}Nicménì, Thomson a French tyto podmínky pøijali.
{13244}{13323}Pochybují snad o platnosti této smlouvy?
{13323}{13362}Oh, ne, samozøejmì e ne.
{13362}{13395}U byla potvrzená.
{13395}{13443}Ta smlouva je dùvìryhodná.
{13443}{13477}Aha.
{13477}{13612}Take, øíkáte, e jsem ten, kdo je nedùvìryhodnı.
{13974}{14052}Hrabì mi dal na dnešní veèer vstupenky do opery.
{14065}{14118}O Hrabìti Monte Christovi...
{14141}{14219}Zdá se, e se mu podaøilo získat sedadla v lói v opeøe.
{14265}{14317}Je docela zkušenı hráè.
{14317}{14355}Vypadá to tak.
{14355}{14445}Myslím, e bychom mu mìli zaplatit a navštívit ho dnes veèer bìhem pøestávky.
{14526}{14542}Jeden.
{14542}{14566}Dva.
{14566}{14587}Tøi.
{14609}{14626}Pìt?
{14645}{14677}P-Pìt set miliónù?!
{14677}{14779}Plánoval jsem dnes otevøení úètu s vámi a uloení pìnez.
{14779}{14895}Mìl jsem v úmyslu zamìøit všechny zisky mıch investicí na tento úèet,
{14895}{14987}ale zdá se, e nejte moc zaujatı.
{14987}{15040}Ne, no...
{15040}{15077}Pøedpokládám, e nepotøebujete pomoc.
{15077}{15130}Pùjdu zkusit další banky-
{15130}{15195}P-Prosím poèkejte!
{15225}{15259}Prosím poèkejte.
{15285}{15355}Ale Lucien je docela dobrı, ne?
{15355}{15426}Obchoduje s tvım otcem u tak brzy ráno.
{15426}{15467}Jsi jako dítì.
{15467}{15498}Co?
{15498}{15553}Jsi ohromen muem jako je on?
{15553}{15608}Muem jako je on? Ale je to náš pøítel!
{15638}{15667}Já...
{15667}{15727}nikdy jsem o nìm nepøemıšlela jako o pøíteli.
{15727}{15786}Byli jsme spolu u od dìtství!
{15892}{15967}A ten pøítel spí s mou matkou!
{15976}{15996}Co?!
{16032}{16075}Tak, urovnáno.
{16086}{16164}Vloím to na váš úèet.
{16177}{16235}Co se tıèe rozsahu pùjèky, to jsme probírali na zaèátku,
{16235}{16284}zprávu vám pošlu pozdìji.
{16284}{16317}Rozumím.
{16317}{16385}Mimochodem dneska ráno jsem slyšel,
{16385}{16462}e vlastníte nejlepšího konì v Paøíi.
{16475}{16546}Ah, zajímate se o konì, hrabì?
{16546}{16625}Ano, zvláštì o konì anglického pùvodu.
{16625}{16717}Vlastnì, rád bych si takového konì koupil.
{16745}{16782}Jaká je cena?
{16824}{16873}Zase ertujete.
{16873}{16990}Ten kùò patøí mé enì.
{17019}{17120}Je-li nabízena suma penìz,
{17120}{17188}cokoli se mùe stát komoditou, Barone,
{17188}{17220}jak jste si toho vìdom.
{17463}{17483}Stalo se nìco hrozného!
{17495}{17572}Pán prodal konì od paní!
{17572}{17599}Prodal Eclipse?
{17599}{17633}Ano, právì teï!
{17657}{17695}Zase budou hádat...
{17695}{17741}Pán øíkal, e byla nabídnutá neuvìøitelná suma penìz
{17741}{17794}a zdál se bıt velmi vzrušenı.
{17804}{17835}To musel bıt hrabì...
{17955}{17969}Co?
{17969}{18003}Jsi nezdvoøilá.
{18003}{18047}Omlouvám se, Hrabì.
{18047}{18084}To je má ena.
{18097}{18141}Tento gentleman je Hrabì Monte Christo.
{18141}{18193}A co mùj kùò?!
{18193}{18237}Kde je Eclipse?!
{18237}{18301}Chtìl jsem s tebou mluvit pozdìji, ale...
{18301}{18353}Prosím omluvte mì na chvilku, Hrabì.
{18369}{18413}Ty's prodal Eclipse?!
{18439}{18471}Potichu!
{18471}{18526}Poslouchej, nebuï v šoku.
{18526}{18594}Hrabì koupil konì v hodnotì 5, 800 000 frankù,
{18606}{18674}za 20, 000 000 frankù!
{18700}{18756}Eclipse je mùj kùò!
{18773}{18812}Tak jsem øekl, e kùò-
{18812}{18862}To není o penìzích!
{18862}{18925}Zítra mám schùzku s madam Villefort!
{18925}{18969}Jsou další konì-
{18969}{19025}Chci jen Eclipse!
{19025}{19093}Okamitì zruš tu dohodu!
{19093}{19125}Co to povídáš?
{19125}{19222}Nemáš ádné právo prodávat mého konì!
{19236}{19273}Baronko,
{19273}{19366}pokud jsem rozhnìval tak krásnou dámu jako jste vy,
{19366}{19400}musím se omluvit.
{19400}{19526}Myslel jsem, e kdybych nabídl 60, 000 000 frankù, |mohlo by to bıt pro vaše uspokojení dostaèující,
{19526}{19655}ale všichni máme vìci, které nelze koupit za kadou cenu.
{19655}{19707}Za mou hloupost zlehèovat tento fakt,
{19718}{19772}prosím, odpuste mi.
{19786}{19843}Oh, ale...
{19843}{19899}Ale, poèkejte chvíli.
{19899}{19958}Øíkal jste 60, 000 000 frankù?
{19958}{19981}Ano.
{19981}{20058}Zaplatil jsem 60, 000 000 v ryzím zlatì.
{20058}{20087}Aha...
{20087}{20160}Omlouvám se, e jsem poloila tak nemístnou otázku.
{20160}{20239}No, musím se pro dnešek omluvit.
{20239}{20333}Dovolte mi uèinit vhodné opatøení vyhovìt pøání madam.
{20429}{20462}Hrabì...
{20574}{20593}Choti,
{20593}{20668}chtìl jsi mít urèité procento zisku i ode mì?
{20668}{20698}Je to všechno nedorozumìní!
{20698}{20749}Jsi prolhanı!
{20749}{20800}Pøijï pozdìji do mého pokoje!
{20845}{20900}Pojïme nìkam, Alberte.
{20900}{20935}Je v poøádku opustit je?
{20935}{20964}Je to tak vdycky.
{21157}{21184}Mùeš jet rychleji?
{21184}{21223}Nemùu jet rychleji.
{21263}{21299}To je na nic...
{21311}{21351}Má rodina je na nic...
{21351}{21386}Mùj otec je na nic...
{21403}{21424}Ale,
{21424}{21484}pan Danglars se o tebe hodnì stará!
{21531}{21572}Nièemu nerozumíš, e?
{21589}{21682}Mohl by mì prodat, kdybych vynesla dostateènou cenu.
{21867}{21903}Dokud tu zùstaneme,
{21903}{21970}nikdy neuteèeme našim rodièùm.
{21983}{21993}Eh?
{22016}{22047}Chci...
{22070}{22102}ít volnìji.
{22124}{22160}Chci hrát na klavír, kterı miluju...
{22160}{22199}nejvíc na svìtì.
{22211}{22235}Eugénie...
{22258}{22295}Chci ít nìkde daleko...
{22309}{22352}kam nedosáhne vliv mıch rodièù.
{22496}{22516}Pojïme!
{22551}{22577}Pojïme spoleènì.
{22592}{22617}Opusme naše domovy.
{22855}{22869}Idiote.
{22869}{22894}Coe?
{22917}{22947}Co je?
{22947}{22981}Vracíme se zpátky.
{22981}{23023}Musím se dostat do šatù, které si dne veèer obleèu.
{23023}{23041}Hej, p-
{23041}{23072}Chceš odsud, jo?
{23106}{23119}Hej!
{23960}{24002}Hej, kde je Valentina?
{24052}{24133}No a co ty? Nepøedpokládal jsi, e budeš s Eugénií?
{24165}{24195}To je pravda!
{24195}{24251}Dokonce se mi objevil ve snech!
{24251}{24321}Chceš slyšet, co mi øekl?
{24321}{24335}Co?
{24403}{24416}Oh!
{24474}{24497}Dobrı veèer!
{24527}{24555}Dobrı veèer.
{24591}{24672}Také jsem dostal pozvání...
{24672}{24724}ale cítím se v tom nìjak...
{24739}{24768}Oh, vùbec ne.
{24768}{24797}Vypadá to na vás dobøe.
{24833}{24851}Oh...
{24851}{24886}Je to vypùjèenı oblek.
{25465}{25493}Princovo lóe
{25493}{25584}bylo od té nehody zablokováno, ne?
{25584}{25654}Dvacet let uplynulo od té nešastné nehody...
{25665}{25728}Slyšela jsem, e si na nìj nìkdo umístil trvalou rezervaci.
{25728}{25760}Hrozivé...
{25760}{25815}Je to jako by se ta osoba, která zemøela, vrátila...
{25815}{25840}Oh, prosím.
{25840}{25876}Pøestaòte øíkat takové dìsivé vìci.
{26531}{26573}Jak podivuhodnı mu!
{26573}{26631}Kdo je ta dívka vedle nìj?
{26631}{26671}Nevím.
{26671}{26756}Ale je tak krásná...
{26869}{26919}Ty se s ním znáš, Alberte?
{27057}{27077}Má paní!
{27077}{27119}Co znamená ten poprask kolem?
{27133}{27153}Kùò...
{27153}{27210}Eclipse... byl vrácen!
{27210}{27242}Co jsi to øekla?!
{27394}{27464}To je nové lóe, které dnes bylo zveøejnìno.
{27483}{27534}To musí bıt Hrabì Monte Christo.
{27534}{27574}Kde sedí?
{27654}{27684}To je-
{27684}{27727}Mrtvého prince...
{27727}{27755}Co tím zamıšlí?!
{27755}{27801}Nevím ádné detaily.
{28478}{28527}Oh, ale!
{28547}{28585}Nemùu tomu uvìøit!
{28629}{28673}Od hrabìte pro mou paní,
{28673}{28719}jako projev jeho omluvy
{28719}{28783}a jeho známosti.
{28803}{28847}Co mám dìlat?
{28861}{28911}Úasné!
{28924}{29003}Došlo k vkladu 450, 000 000 dolarù
{29003}{29062}z Alpha Cygni Far East Vanderbilt.
{29062}{29141}Z Northern Political Coalition Space Canal Corporation
{29141}{29213}vklad 3, 280 000 000 pesos.
{29213}{29315}Z Central United Emirated Gravity Advanced Materials
{29315}{29377}vklad 1, 420 000 000 liber.
{29377}{29482}Zahranièní investoøi jeden po druhém vkládají| peníze na úèet hrabìte Monte Christa.
{29482}{29542}Kdo je ten mu?
{29542}{29611}Jak vydìlal tolik penìz?
{29611}{29668}Hrabì Monte Christo...
{29668}{29734}Ah, jak úasnı mu!
{29751}{29786}Úasnı!
{29805}{29834}Øekni, Michéle...
{29834}{29897}Ten mu nìco skrıvá.
{29912}{29968}Nic podezøelého nezpozorováno.
{29968}{30023}Prozkoumej ho skrz na skrz.
{30023}{30086}Prozkoumej jeho obchodní partnery jemnozubım høebínkem!
{30086}{30114}Rozumím.
{30331}{30352}Ten mu...
{30485}{30510}Ten mu...!
{31434}{31484}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31512}{31597}www.mycolorfullife.blog.cz
