{1}{1}23.976
{44}{178}TaSHee's Gang uvádí
{277}{381}GANKUTSUOU
{2446}{2571}Mladík, kterı se vkradl na panství, aby pomohl lásce svého pøítele,
{2571}{2642}byl svìdkem dospìlıch uprostøed milostné aféry.
{2653}{2716}Mùj pøítel øíká, "Musí vìdìt."
{2750}{2839}V jeho nevinné duši je znièeno...
{3132}{3185}NOC V BOULOGNE
{3669}{3695}To není dobré.
{3717}{3734}Alberte!
{3758}{3817}C-Co znamená to náhlé vniknutí?
{3817}{3847}Oh, promiò!
{3847}{3917}Ale neodpovídal jsi bez ohledu na to, kolikrát jsem volala.
{3938}{3990}Máš návštìvníka z Champs-Élysées.
{4026}{4046}Hrabì?
{4046}{4076}Vlastnì,
{4076}{4136}øíkal, e vás dnes nechce vidìt.
{4147}{4180}Vzkazuje nìco?
{4180}{4233}Ne, nic konkrétního.
{4249}{4275}Aha.
{4292}{4313}Co je to?
{4313}{4369}Pozvánka na veèírek.
{4369}{4458}Pøeje si mít veèírek ve své nové vile.
{4458}{4477}Prosím, pøijïte se svou rodinou.
{4477}{4509}To bych rád.
{4509}{4529}Kde to je?
{4543}{4601}Auteuilskı les.
{4617}{4656}Na takovém pustém místì?
{4656}{4687}Ano.
{4687}{4760}Jeho excelence na tom trvala.
{5128}{5156}Tohle místo...
{5169}{5283}Jestli si dobøe vzpomínám, tahle vila byla majetkem pana Villeforta.
{5305}{5344}Vypadá jako ruina.
{5356}{5454}Kdy byla jeho pøedchozí ena naivu, byla nádherná.
{5468}{5550}Nepoukazuješ náhodou na Valentininu skuteènou matku?
{5563}{5631}Byla mladá a krásná.
{6132}{6174}Dìkuji, e jste pøišli.
{6198}{6235}Pane Generále.
{6235}{6282}Dìkuji, e jste nás pozval.
{6440}{6461}Hrabì!
{6493}{6541}Ale, ale. Madam Villefort.
{6582}{6616}To je mùj manel-
{6628}{6677}Váenı, Nejvyšší soudce,
{6698}{6718}domnívám se.
{6755}{6818}Slyšel jsem, e jste pomohl mé enì a synovi.
{6867}{6941}Jsem poctìn vaší pøítomností.
{6981}{7078}Tato vila je a pøíliš pustá pro pobavení hostù.
{7078}{7107}Naopak,
{7107}{7155}je tu klid,
{7155}{7237} a já jsem tu docela rád.
{7296}{7433}A teï, jsou zde tøi gentlemani, kteøí pøedstavují Paøí.
{7451}{7514}Pan Danglars, kterı vládne finanènímu svìtu;
{7514}{7576}Generál Morcerf, kterı kontroluje vojenské události;
{7576}{7658}a vy, kterı pøedsedáte zákonu.
{7676}{7803}Existuje jen jeden dùvod, proè jsem vás tøi |pozval na soukromé setkání dnes veèer.
{7822}{7876}Dovolte mi bıt upøímnı v mém pøiznání.
{7955}{8021}Cestovatelé jsou plni starostí.
{8039}{8076}Rád bych
{8076}{8151}s vámi tøemi navázal pøátelství.
{8215}{8326}Slyšel jsem, e jste si pøál bıt pøedsedou, pane Generále.
{8339}{8380}Kde jste to slyšel?
{8392}{8486}Rád bych vám pomohl k nejlepším svımi skromnımi schopnostmi.
{8521}{8581}Nech nás prosím, Alberte.
{8581}{8600}Co?
{8600}{8623}Ale...
{8629}{8680}My dospìlí si musíme promluvit.
{8777}{8799}Alberte.
{8813}{8836}Co se dìje?
{8836}{8869}Jsi opuštìnı.
{9288}{9321}Nevypadáš moc dobøe.
{9342}{9399}Ne, je mi dobøe matko.
{9399}{9455}Omlouvám se, ì tì tak moc odstrkuju.
{9530}{9554}Zajímá mì...
{9582}{9621}jestli se mi Hrabì vyhıbá.
{9673}{9710}Náhodou jsem nìco vidìl ve Villefortovì...
{9738}{9786}No...
{9786}{9816}Hrabì a paní byli...
{9816}{9854}blízko.
{9870}{9893}A?
{9918}{9948}Pak...
{9965}{9990}Hrabì...
{10002}{10048}zpozoroval, e...
{10074}{10105}jsem se díval...
{10105}{10124}Myslím.
{10124}{10164}A tak?
{10178}{10230}Jsem bastard.
{10301}{10376}Pøedpokládám, e mùu íct, e má Hrabì mnoho stránek...
{10388}{10444}Znamená to, e je to mu.
{10468}{10564}Kromì toho, nebyli jste tam kvùli Maxmiliánovi?
{10600}{10640}Teï na tohle není vhodnı èas.
{10751}{10773}Omluvte mì...
{10799}{10875}Mohu si pøisednout?
{10876}{10910}Kdo je to?
{10932}{10956}Já...
{10956}{10994}pùjdu se ven nadıchat èerstvého vzduchu.
{10994}{11040}Em... já...
{11094}{11122}Boooe...
{11122}{11167}Co jste udìlali?
{11211}{11251}A kdo jste vy?
{11272}{11321}J-J-Já já jsem...
{11321}{11378}Kapitán Maxmilián Morrel,
{11378}{11416}talentovanı voják.
{11451}{11477}Rád vás poznávám, pane!
{11477}{11597}Kapitán Maxmilián Morrel z Gamma Canes Venatici Army.
{11597}{11692}Má rodina se zabıvá zahranièním obchodem v Marseille,
{11692}{11711}a já-
{11711}{11769}A? Jakı je váš úmysl?
{11769}{11799}Eh, no...
{11799}{11851}R-Rád bych... vaši dceru-
{11851}{11957}Máte èestnou pozici jako obránce království.
{11957}{12008}Máte za to mùj respekt.
{12008}{12039}Nicménì!
{12039}{12085}Jste ale prostı obèan
{12085}{12152}a má dcera má snoubence.
{12152}{12223}ádám, abyste si uvìdomil tento fakt.
{12297}{12324}Vy nestydatı blázne!
{12378}{12451}Marseillská polévka.
{12619}{12674}Take, co se stalo s návrhem svatby?
{12715}{12740}Nevšímavost.
{12740}{12794}Mohlo by to bıt...
{12810}{12837}e ona...
{12837}{12865}k tobì nìco cítí?
{12865}{12906}O èem je tato tajná schùzka?
{12931}{12953}Beauchampe!
{12953}{13061}Máš odvahu pøekvapit Nejvyššího soudce fotografováním s bleskem.
{13061}{13170}Kdy vidím aroganci, mùj vzpurnı blesk se rozhoøí.
{13170}{13231}Tak, co se dìje? Problémy dospívání?
{13231}{13271}Booe, mluvit o tragickém svìtì,
{13271}{13349}kdy všichni slábnou láskou a kdo ví, èím ještì.
{13349}{13375}Podívejte se.
{13375}{13472}Proslıchá se, e ti dva byli kdysi milenci.
{13487}{13518}Nejvyšší soudce?!
{13518}{13552}S matkou Eugénie?!
{13579}{13637}Omlouvám se za nerozumné poadavky.
{13637}{13659}To nic.
{13659}{13702}Prosím neznepokojujte se mnou.
{13727}{13795}Zaplatil jsem obrovské èástky za její lekce,
{13795}{13848}aby se mohla v tìchto situacích pøedvést.
{14079}{14092}Já...
{14092}{14143}Prosím, vyslechnìte, co vám chci øíct.
{14159}{14234}Chci se vám omluvit.
{14274}{14320}Kdy jsme naposledy mluvili, já...
{14337}{14411}jsem øekl hroznou vìc... bez uváení vašich pocitù.
{14436}{14476}Co øekla Valentina?
{14523}{14545}Plakala.
{14653}{14712}Povìøil jsem tì namáhavım úkolem.
{14712}{14740}Omlouvám se za to.
{14751}{14785}Valentina...
{14796}{14849}tì miluje, to víš.
{14849}{14881}Nikterak.
{14881}{14909}Ale ano.
{14943}{15002}Jsem si jistı, e ano.
{15083}{15145}Eugénie se stala talentovanou.
{15145}{15201}Hej, nemìò téma.
{15201}{15272}Vlastnì jsem s ní mluvil druhı den.
{15283}{15351}Vsadím se, e o mì øíkala zase špatné vìci.
{15351}{15385}No, ano.
{15408}{15427}Co?
{15427}{15459}Øekni mi to!
{15459}{15493}No tak, øekni mi to!
{15596}{15653}Co pro mì máš teï?
{15653}{15681}Bojím se.
{15681}{15725}Co kdy nás nìkdo uvidí?
{15725}{15779}Tady, já...
{15779}{15822}ta dívka...
{16499}{16531}Bylo to úasné.
{16547}{16618}Vaše hudba je boskım voláním.
{16633}{16665}Boí volání, ehm.
{16665}{16692}Vsadím se...
{16692}{16763}e Hrabì zná hodnì talentovanıch lidí.
{16779}{16821}Dìkuji vám a krásnı vıkon,
{16849}{16887}krásná sleèno.
{17007}{17034}Rád vás poznávám.
{17075}{17140}Teï, kdy jsme pøedstavili mladı talent,
{17140}{17196}nechte mì vám pøedstavit tohoto mladíka,
{17213}{17297}Marquise Andreu Cavalcantiho.
{17349}{17373}Oh, ale...
{17427}{17489}Rodina má dìdice?
{17501}{17583}Jeho otec je mùj starı pøítel.
{17583}{17649}Pokud byste s ním byl v tak pøátelském vztahu jako se mnou,
{17649}{17691}bylo by to ocenitelné.
{17691}{17798}Jsem ale pouze dítì, které teprve nedávno zdìdilo jeho majetek.
{17798}{17838}Je mi potìšením, e vás poznávám.
{17838}{17893}Podívej se na ornament na jeho hrudi.
{17893}{17943}Má hodnotu tak pìt milionù.
{17992}{18022}Kdo to sakra je?
{18022}{18086}Myslím, e novı favorit hrabìte.
{18086}{18103}Co-
{18103}{18181}Moná je opravdu talentovanı.
{18222}{18252}Tak tedy,
{18252}{18270}všichni.
{18283}{18351}Omlouvám se za pøerušení vaší prohlídky,
{18361}{18446}ale prosím podíváte se na chvíli tímto smìrem?
{18446}{18511}Dùvod, proè jsem získal tuto vilu
{18511}{18572}byl útìk z rušného mìsta,
{18572}{18661}abych mohl mít èas na pøemıšlení.
{18661}{18704}Nicménì, nyní se divím.
{18704}{18874}Kdy jsem sem pøijel, byl jsem jako v transu |z atmosféry, která tuto vilu obklopuje.
{18874}{18951}Je to tak? Co by to mohlo bıt?
{19029}{19094}Jak mám dát...
{19116}{19136}Ano,
{19157}{19183}mohlo by to bıt...
{19209}{19231}prokletí.
{19261}{19311}Pøemıšlel jsem o tìchto vìcech:
{19325}{19413}co se zde dìlo v minulosti....
{19413}{19546}a co existovalo za tragédie, bez vìdomí všech?
{19578}{19634}Vdycky kdy v mé mysli tancují tyto myšlenky...
{19651}{19754}Jsem plnı nevysvìtlitelného štìstí a míru.
{19836}{19885}Neexistuje ádná chba.
{19896}{19947}Vùbec ádná chyba.
{19977}{20000}Nesmysl.
{20000}{20030}Prokletí?
{20053}{20067}Oh?
{20067}{20218}Ctìnı soudce, øíkáte, e jste si nevšiml hloubavé, |zlovolné pøítomnosti, která vyplòuje tuto vilu?
{20226}{20267}Nejvyšší soudce.
{20288}{20312}Velmi dobøe.
{20312}{20392}Pak byste si to mìl ovìøit na vlastní oèi.
{20392}{20429}Vlastnì...
{20429}{20490}je tu jeden pokoj, hluboko uvnitø vily,
{20490}{20549}kterı byl nedotèen.
{20563}{20604}Co by to mohlo bıt?
{20638}{20678}A nemohu se ubránit pocitu...
{20694}{20764}e je ten pokoj zdrojem
{20764}{20858}a vyzaøuje z nìj pøítomnost zla.
{20973}{20998}Jaká uráka!
{20998}{21029}Odcházíme.
{21029}{21049}Drahı!
{21049}{21147}No tak, no tak, neøíkejte takové vìci.
{21147}{21237}Proè dnes veèer nesouhlasíme s názory našeho hostitele?
{21287}{21317}Co s tím, dámy a pánové?
{21317}{21409}Proè se nejdeme všichni podívat do takzvané místnosti zla?
{21409}{21436}Poèkejte chvíli.
{21448}{21495}Jestli pùjdeme všichni v houfu,
{21495}{21543}pøiostøí se to.
{21543}{21573}Albert.
{21573}{21614}Oh, ano!
{21629}{21650}Franz.
{21672}{21709}A Eugénie.
{21723}{21746}Já?
{21759}{21858}Proè se nerozdìlit do skupin po tøech a hledat ten pokoj?
{21890}{21965}Budeme mít tøi mladé, kteøí budou proráet cestu.
{21987}{22043}Rád bych odmìnil toho, kdo zvládne dosáhnout
{22043}{22184}nejhlubších hlubin této temné vily, skromnım dárkem.
{22184}{22209}Co si všichni myslíte?
{22241}{22275}Skvostné!
{22275}{22315}Fascinující!
{22315}{22342}Jdeme na to!
{22342}{22370}Jdeme na to, lidi!
{22370}{22411}Alberte!
{22426}{22474}Spoléhám na vás.
{22554}{22570}Ano!
{22718}{22772}U je to chvilka, Marchioness.
{22805}{22841}Zdá se, e se ti daøí dobøe.
{22853}{22894}Prosím buï váná.
{22894}{22949}"Ujmìte se vedení a vyhrajete."
{22971}{23058}Mimochodem, odkud jste Marquisi?
{23058}{23077}Promiòte?
{23077}{23149}Oh, pøijel jsem z daleka, z Vıchodního vesmíru.
{23161}{23243}To místo má opravdu krásnı planetární systém,
{23258}{23303}a jedna z planet je obıvaná ptáky,
{23316}{23404}kteøí jedí rudy a kladou vajíèka z drahıch kamenù.
{23416}{23491}Jednou za padesát let tvoøí kvùli páøení kolonie, ale...
{23680}{23711}Koneènì...
{23733}{23782}jsme sami a mùeme mluvit.
{23816}{23840}Omluvte mì.
{24171}{24198}Hrabì?
{24214}{24255}Je tu nìco o èem bych si pøála s vámi mluvit.
{24302}{24339}Co máte na mysli,
{24339}{24377}madam de Morcerf?
{24413}{24444}Prosím øíkejte mi...
{24444}{24479}Mercédés.
{24537}{24582}Esence zlovolné pøítomnosti.
{24619}{24646}Esence...
{24670}{24713}Zajímalo by mì, co to je.
{24834}{24919}Proè jste fixován na Marseille?
{24936}{24968}O èem to mluvíte?
{24968}{25064}Dnes veèer jste servíroval jídlo z Marseille.
{25077}{25123}Nesedí vám to?
{25123}{25150}Ne...
{25150}{25208}To jen kdy se na vás podívám,
{25208}{25272}tak mi pøipomínáte nìkoho, koho jsem znala.
{25297}{25344}Dlouhou dobu,
{25344}{25443}jsem ila v nadìji, e se ta osoba ještì jednou objeví.
{25443}{25560}Ale teï, se cítím vydìšená, nìjak...
{25691}{25713}Hrabì?
{25740}{25824}Nejste sama...
{25848}{25940}Vdy se najde nìkdo, kdo na vás bude myslet.
{25953}{26041}Prosím nezapomínejte na to.
{26155}{26174}Tohle je...
{26191}{26275}memento, které mi dal mùj otec ne zemøel.
{26275}{26331}Byl bych rád, kdybyste to mìla.
{26410}{26439}To je slepá ulièka.
{26474}{26533}Prosím zastav, Alberte.
{26533}{26570}Sleèna u je hodnì unavená.
{26570}{26602}Budeme se muset rozlouèit.
{26602}{26630}Pane Villeforte!
{26648}{26675}Támhle jsou zadní dveøe!
{26698}{26758}To-To-To-Tohle místo je...!
{27324}{27353}Gratuluji.
{27398}{27458}Pøišli jste první.
{27470}{27570}Líbila se vám kuriózní
{27570}{27616}atmosféra této vily?
{27636}{27732}Majitel této vily nevypadá, e by vìdìl, jak pobavit své hosty!
{27804}{27888}ádám tì o pomoc, Alberte.
{27888}{27926}Oh, jistì!
{28003}{28060}Dìkuji, e jsi pøišel celou cestu a sem.
{28100}{28136}Muselo to bıt tìké, ne?
{28167}{28228}Omlouvám se, Hrabì.
{28266}{28301}Co tím máte na mysli?
{28326}{28360}No, øíct vám pravdu...
{28415}{28442}Vidìl jsem...
{28475}{28531}ve skleníku pana Villeforta...
{28597}{28632}Prokoukl jste mì.
{28632}{28674}Take jste se díval.
{28674}{28700}Ah dobøe,
{28700}{28746}paní byla tak vytrvalá...
{28792}{28850}Byl jsem pøesvìdèen, e se na mì zlobíte!
{28867}{28904}Samozøejmì, e ne!
{29045}{29138}Mimochodem, prosím pøijmìte moji omluvu,
{29138}{29225}e jsem s vámi dnes nemohl konverzovat.
{29239}{29268}Øíct vám pravdu...
{29268}{29352}Jsem postien nemocí ze vzdáleného vesmíru.
{29352}{29475}Nìkdy si pøeju odpoèinout, ani by mì nìkdo vidìl.
{29623}{29651}To je...
{29671}{29733}Oh, není to nic váného,
{29733}{29781}i kdy nìkdy pociuju znecitlivìní.
{29820}{29841}Alberte...
{29857}{29880}tohle...
{29892}{29967}je tajemství mezi námi dvìma.
{30004}{30079}Mezi vámi a mnou.
{30138}{30165}Rozumím.
{30165}{30209}Slibuji.
{30237}{30258}Tak tedy,
{30259}{30315}vezmìme tuto truhlu a pojïme ven.
{30353}{30377}To je ten pokoj,
{30377}{30414}kde jsem porodila to dítì!
{30414}{30446}T-T-To dítì...
{30460}{30543}To dítì nás zde zavolalo!
{30543}{30579}Vzchop se!
{30579}{30612}Ale!
{30612}{30687}Ta noc, pøed sedmnácti lety...
{30687}{30716}Gratuluji!
{30740}{30784}Tady je dárek od hrabìte!
{30838}{30905}NE!
{30947}{30963}Madam!
{31036}{31061}Vy...
{31090}{31114}Kdo...
{31126}{31160}jste?!
{31465}{31548}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31593}{31682}www.mycolorfullife.blog.cz
