{1}{1}23.976
{62}{215}TaSHee's Gang uvádí
{282}{385}GANKUTSUOU
{2450}{2526}Dobrı veèer, dámy a pánové.
{2550}{2623}Chlapec, chtìl vyjádøit své pocity,
{2633}{2749}proto spìchal do Opery, kde èekala jeho snoubenka.
{2774}{2809}Nicménì, ještì neví,
{2809}{2954}o hrozné minulosti jeho otce skryté za zrušenım zasnoubením...
{3012}{3055}HAYDÉE
{3487}{3547}Ten mu je vrah!
{3604}{3662}Jsem pøekvapen, e jste pøišel vy sám, Vaše Ctihodnosti.
{3675}{3726}Je toto vedlejší èinnost Opery?
{3726}{3782}Musíte to pøipustit.
{3798}{3893}Toto je opravdu prsten, kterı jsem dal vaší enì.
{3893}{3956}Obsahuje jed.
{3993}{4037}Jakı zajímavı vımysl.
{4037}{4146}Zdá se, e jste se snail pøiblíit mé enì.
{4146}{4193}Je divné, e to øíkáte vy.
{4193}{4226}Jakı dùvod bych musel-
{4226}{4248}Víte velmi dobøe!
{4259}{4353}Není to krutı zvyk z Vıchodního vesmíru,
{4353}{4394}zabíjet pro potìšení?
{4411}{4451}Hrabì není nìkdo, kdo by udìlal takovou vìc!
{4451}{4475}Jsi tím muem podvádìnı.
{4512}{4597}Byl to hrabì, kdo mì informoval o tom, e je Valentina v nebezpeèí!
{4597}{4643}I cizinci jako jsem já,
{4643}{4734}bude doufám poskytnut oficiální soud.
{4734}{4757}Samozøejmì.
{4757}{4832}Podle zákona budete mít pøísnı a spravedlivı proces.
{4832}{4900}Uklidòuje mì to slyšet.
{4912}{4962}Mám svìdka.
{4962}{4989}Coe?!
{4989}{5064}Nìkdo, kdo zná pravdu.
{5191}{5219}Héloise!
{5219}{5336}Slyšel jsem od vaší eny a syna mnoho zajímavıch vìcí.
{5370}{5450}I vìci, které jsou pro vaši rodinu dost osobní...
{5450}{5485}Ty parchante!
{5485}{5525}Co udìláte?
{5525}{5562}Zatknete mne?
{5698}{5729}Co se dìje?
{5729}{5774}Nepøišli jste ho zaknout?
{5774}{5814}ádné starosti.
{5828}{5892}Zdá se, e jeho èestnost uèinila špatnı odhad.
{5892}{5937}Dobrá práce, Hrabì!
{5955}{5991}I "soudce démon" ztratil tváø!
{6012}{6067}Bylo by pro tebe nejlepší vrátit se domù.
{6090}{6110}Ale...
{6122}{6177}Nedìlej si o mì starosti, prosím.
{6413}{6475}Nemysli si, e s tímhle unikneš!
{6486}{6509}Pane Villeforte.
{6509}{6596}Ten mu si pøeje mùj pád.
{6596}{6660}Nemùu uvìøit, e stále øíkáte takové vìci!
{6660}{6698}Cítím to...
{6698}{6786}Cítím v jeho duši pøítomnost zla.
{6977}{7062}Stále jste zaujatá muem z vaší minulosti?
{7091}{7125}Marquis Cavalcanti!
{7146}{7184}Prosím, øíkejte mi Andrea.
{7199}{7251}Nevím co vám mùj otec øekl,
{7251}{7318}ale necítím k vám vdìènost.
{7318}{7350}Oh mùj...
{7366}{7435}Vystupování v Opeøe byl mùj sen,
{7435}{7485}a kdy jste koupil ten sen za peníze...
{7503}{7602}Získala jste právo na koncert vlastní zásluhou.
{7602}{7629}Nakonec,
{7632}{7751}váš talent ze mì udìlal vašeho ubohého sluhu.
{7780}{7819}On odešel.
{7838}{7916}Zdá se, e nemá tolik odvahy vzít vás s sebou.
{8139}{8156}To je k nièemu.
{8203}{8252}Dokumenty, které odpovídají vašemu poadavku
{8252}{8314}nebyly nikde v této knihovnì nelezeny.
{8314}{8338}Aha.
{8356}{8437}Nemùu uvìøit, e existuje slovo, které |není registrováno v královské knihovnì,
{8437}{8497}která se pyšní nejvìtším objemem informací ve vesmíru.
{8497}{8604}Moná je to slovo, které je zakázáno |veøejnım názorem Security Directorate.
{8617}{8639}Co tím myslíte?
{8639}{8763}Je to postup, kterı zamítá veøejnosti pøístup k utajenım informacím.
{8911}{8957}Snííte finanèní prostøedky?!
{8973}{9024}Nakonec to bylo na naše vıdaje pøíliš.
{9055}{9097}Ale co kampaò pøed prezidentskımi volbami?!
{9109}{9167}Omlouvám se, ale musíme zrušit naši podporu.
{9178}{9207}Já,
{9207}{9235}ty
{9235}{9259}a Villefort...
{9276}{9378}Bylo naším snem dostat se na vrchol Paøíe!
{9378}{9424}Oh, to bylo...?
{9455}{9519}Proè, kdy jsme od toho jen krùèek?
{9543}{9616}Naši analytikové...
{9616}{9696}øíkali, e bychom nemìli sázet na Generála Morcerfa.
{9744}{9777}Kvùli tomu incidentu s Edmondem?
{9777}{9814}No tak, no tak...
{9814}{9898}Øeknìme, e kadı z nás by mìl dávat pozor na své postavení.
{9915}{9954}Jestli vyhraješ volby...
{10021}{10063}Zavolej mi prosím.
{10195}{10214}Mùj pane,
{10214}{10286}zaøídili jsme schùzku se Sedmou flotilou z Vıchodního vesmíru.
{10471}{10511}Minulou noc jste ze sebe udìlal hlupáka.
{10511}{10555}Vy domıšlivé štìnì. Kdo jste?
{10555}{10625}Lucien Dupré, první tajemník.
{10625}{10666}Jsem zarmoucen, e jste na mì zapomnìl.
{10666}{10737}Ah, vy jste ten mladı z Misterstva vnitra.
{10750}{10817}Hrabì Monte Christo je nyní paøískou celebritou.
{10850}{10892}Nemìl byste ho zatıkat bez opodstatnìní.
{10892}{10942}Nìco intrikuje!
{10942}{10967}A váš dùkaz?
{10967}{11042}Já rozhoduju, zda je nevinnı èi vinnı.
{11042}{11093}Bezpeènostní øeditelství se chystá pøijmout opatøení
{11093}{11166}pokud jde o podezøení, e nejvyší soudce
{11179}{11213}intrikuje falešné obvinìní.
{11233}{11278}Udìlal jste trochu moc.
{11278}{11367}Je pravdìpodobnì otázkou èasu, kdy vám |budou poslány propouštìcí papíry.
{11400}{11426}Nemoné!
{11441}{11469}Oh, jsi tady?
{11537}{11583}Chtìl jsem se zeptat na radu.
{11583}{11647}Chceš radu? Neobvyklé.
{11668}{11739}Nemám jinou monost, jen poádat elitu Ministerstva vnitra.
{11776}{11817}Dnes nejsi se svım nejlepší pøítelem?
{11966}{11984}Kde je Victorie?
{11984}{12059}Paní odpoèívá ve svém pokoji.
{12073}{12130}Nevím co mám s její matkou dìlat.
{12130}{12235}Byla taková do té doby, ne dostala zimnici a rımu
{12235}{12279}na veèírku v Auteuil.
{12327}{12354}Dùsledkem tìchto okolností,
{12354}{12401}vás nemohu ani poøádnì uvítat,
{12401}{12457}tak co takhle si s námi dát veèeøi?
{12457}{12493}Oh, rád!
{12508}{12575}Pøedtím musím dokonèit práci,
{12575}{12607}do té doby bude má dcera hostitelkou.
{12607}{12624}Coe?!
{12642}{12687}Co takhle další píseò?
{12687}{12745}Tentokrát pro Andreu?
{12745}{12794}Byl bych poctìn!
{12794}{12828}Oh, já vím...
{12932}{12992}Akcie Èerné díry?
{13018}{13046}Tak tedy...
{13070}{13114}Mùeme zaèít, Michéle?
{13114}{13199}Tady je schùzka s Generálem Morcerfem, ale-
{13199}{13232}Zapomeò na to!
{13232}{13296}Tohle je super-dùleité-osudové zboí na trhu!
{13296}{13321}Rychle!
{13321}{13354}Rozumím.
{13442}{13504}Danglars spouští pøístup.
{13504}{13529}Dobøe.
{13529}{13550}Prodej to.
{13550}{13581}Rozumím.
{13581}{13617}Nechte ho oslavit jeho nasycení.
{13643}{13703}Nakrmíme ho v dostateèné míøe.
{13703}{13738}A nastane vhodná doba,
{13738}{13832}úniku informací, to budou znamení, aby |Císaøská armáda zaèala hlavní útok
{13832}{13859}ve Støedním vesmíru.
{13872}{13981}Je ponìkud frustrující myslet si, e ponecháme| toho nenasytného supa sklízet zisk.
{14047}{14087}"Gankutsuou", eh?
{14119}{14147}Jsi pøipravenı?
{14147}{14166}Ano.
{14196}{14214}Pojïme.
{14335}{14395}Vítej v sídle státních tajemství.
{14419}{14445}Co je to za místo?
{14445}{14503}Databáze pod pøímou kontrolou Ministerstva vnitra.
{14834}{14868}Vyhledávané slovo, prosím.
{14892}{14917}"Gankutsuou".
{14937}{15020}Lucien Dupré, První tajemník, Kategorie S.
{15020}{15051}Prohlíení povoleno.
{15153}{15181}Co je to za místo?!
{15181}{15203}Potichu.
{15217}{15290}Gankutsuou je vládce temnoty.
{15301}{15319}Vıznam?
{15319}{15370}Nikdo nevidìl jeho oblièej.
{15370}{15418}Nikdo neøíká jeho jméno.
{15418}{15493}Ti, kteøí poruší toto tabu, budou postieni osudem horší ne smrt.
{15505}{15531}Mìstská legenda?
{15531}{15566}Skuteènost.
{15566}{15629}Objevil se pøed tisíci lety
{15629}{15668}ve vzdálenıch místech vesmíru
{15668}{15722}a snail se vládnout podzemní spoleènosti.
{15751}{15780}Vetøelec?
{15793}{15841}Gankutsuou je nepøemoitelnı.
{15841}{15912}Poírá lidské touhy a jejich pravidla.
{15912}{15976}Nicménì, byl znièen osudem.
{15976}{16057}V èervnu, v roce 4002 podle kalendáøe Louise Phillipa,
{16057}{16116}byl chycen a zavøen.
{16129}{16147}Kde?!
{16188}{16225}Nemáme odpovìï.
{16225}{16259}Kde byl uvìznìn?
{16259}{16297}Nemáme odpovìï.
{16309}{16370}Vydávám Císaøskı pøedpis èíslo 53!
{16421}{16535}Gankutsuou byl uvìznìn v Chateau d'If.
{16535}{16586}A co se stalo?
{16586}{16681}23. prosince roku 5043,
{16681}{16717}byla potvrzena jeho smrt.
{16717}{16759}Pøed deseti lety?!
{16759}{16815}Byl ve vìzení tisíc let?!
{16815}{16852}A jaké je jeho jméno?!
{16852}{16910}Maskovanı mu...
{16910}{16944}Jaké je jeho køestní jméno?!
{16944}{17009}Okamitì zastavit pøístup.
{17009}{17031}Proè?!
{17031}{17068}Nemáme odpovìï.
{17077}{17144}Vydávám zvláštní pøíkaz 3 èíslo 53!
{17180}{17206}To je...
{17206}{17249}Jeho jméno je...
{17249}{17282}Protiprávní pøístup.
{17302}{17328}Protiprávní pøístup.
{17328}{17414}Utajovací kód 6 sekce 2, aktivován.
{17860}{17907}To je zatracenì nebezpeèné.
{17920}{17960}Chci vìdìt, kdo to je!
{17960}{17989}Gankutsuou!
{17989}{18051}Ne, musím to vìdìt!
{18124}{18180}Moná pan Noirtier mùe...
{18202}{18223}Mùe?
{18223}{18286}Bıval vysoce postavenım úøedníkem Ministerstva vnitra.
{18298}{18345}Ale také mìl spoustu nepøátel...
{18345}{18366}a byl poraen.
{18375}{18415}Po princovì atentátu?
{18440}{18457}Ano.
{18457}{18540}Obhajoval mír s Imprériem.
{18540}{18632}Vısledkem bylo, e se jeho syn, Villefort, jen stìí prorazil.
{18632}{18697}No, vše se obrátilo v prach.
{18803}{18818}Otèe...
{18849}{18917}Musíš se mi smát,
{18929}{18974}kdy jsem ztratil postavení a rodinu.
{19007}{19070}Musíš si myslet, e je to trest
{19070}{19173}za posílání nevinnıch do vìzení a vedení| nemilosrdného hodnocení, ne?
{19202}{19303}To je trest za to, e jsem šel proti tvım |názorùm, obhajující válce s Impériem
{19303}{19379}a zabíjel tvé pøátele!
{19391}{19454}Pracoval jsem tvrdì, abych tì pøekonal!
{19454}{19505}Pøekonal tebe, kterı ovlivnil státní záleitosti!
{19505}{19606}Mùeš pochopit, co to znamená?!
{19606}{19646}Bıt tvım synem
{19646}{19707}ve svìtì ovládaném vydøiduchy?!
{19773}{19819}"Odvolání z funkce"?
{19819}{19864}A co?!
{19864}{19888}Co s tím?!
{19888}{19944}Takhle neskonèím!
{19944}{19970}Jen sleduj...
{19970}{20050}Vrátím se na scénu!
{20318}{20360}Takto u je tu celou dobu.
{20396}{20450}Je to jako kdyby se vrátila do dìtství.
{20625}{20689}Mùj pane, jste si jistı, e je to v poøádku?
{20689}{20766}Mùeme ještì jednat poté, kdy jsme se objevili |v enevì na mírovıch jednáních.
{20766}{20817}Musíme útoèit dokud mùeme!
{20829}{20894}Abychom zvıšili náš prospìch jako jednacímu stolu,
{20894}{20927}nesmíme váhat!
{20927}{21003}Tato bitva skvìle zvıší vaši oblibu,
{21003}{21030}mùj pane!
{21551}{21595}Vikomt de Morcerf.
{21628}{21670}Vítám vás v sídle.
{21696}{21740}Je nìco, o èem si se mnou dnes pøejet mluvit?
{21758}{21810}Vlastnì, pøijel jsem za hrabìtem.
{21843}{21906}Hrabì onemocnìl.
{21916}{21957}Ano, to mi bylo øeèeno.
{21957}{22018}Prosím, nechte mì ho vidìt!
{22046}{22116}Prosím nechte ho bıt.
{22133}{22165}V èasech jako jsou tyto,
{22165}{22217}uvidí jen mì.
{22241}{22302}Sleèno Haydée, musíte Hrabìti hodnì...
{22314}{22335}vìøit.
{22398}{22458}Prosím, øeknìte mu, aby si dával pozor na pane Villeforta!
{22458}{22485}Øíkal,
{22485}{22543}e nenechá Hrabìte uniknout s tím, co udìlal.
{22543}{22560}Tak-
{22560}{22645}Musíte mít Hrabìte hodnì rád, pane Alberte.
{22645}{22661}Eh?
{22661}{22679}No...
{22692}{22707}ano.
{22793}{22845}Jsem ráda, e o nìj máte starost.
{22856}{22911}Jak dlouho jste s ním?
{22961}{23016}Mnoho èasu uplynulo...
{23042}{23114}od tédo by, co mì koupil.
{23114}{23157}K-Koupil?!
{23190}{23295}Narodila jsem se v královské rodinì na jisté |planetì ve vzdáleném vesmíru.
{23316}{23393}Byla to planeta, která leela mezi |Vıchodním vesmírem a tímto královstvím
{23393}{23434}a prosperovala v obchodu.
{23473}{23491}Ale...
{23516}{23599}naše štìstí netrvalo dlouho.
{23629}{23700}Vypukla válka mezi Zemí a Impériem
{23700}{23781}a má vlast byla vtaena do boje.
{23797}{23817}Mùj otec...
{23817}{23878}se rozhodl vytvoøit alianci se Zemí.
{23891}{23931}Bylo to proto, e slyšel,
{23931}{24004}e lidé na Zemi oceòují svobodu.
{24039}{24059}Pak...
{24059}{24124}pøijely pomocné jednotky ze Zemì.
{24165}{24226}Slyšel jsem, e pøed deseti lety byla doba sporu.
{24241}{24261}Mùj otec sám
{24261}{24323}byl v nìkolika kampaních válek za nezávislost.
{24416}{24462}Ty posily ze Zemì
{24474}{24504}zradily mého otce!
{24559}{24681}Údajnì byly spiknuty s Impériem,
{24681}{24723}povstali ve vzpouru.
{24745}{24810}Mùj otec byl zabit jako vlastizrádce;
{24810}{24884}má matka a já jsme byly zbaveny našich pozic
{24884}{24935}a prodány nepøíteli.
{24966}{24987}Brzy potom,
{24987}{25023}má matka zemøela
{25043}{25077}a já byla osamìlá...
{25102}{25147}jako ijící mrtvola.
{25264}{25284}Ano...
{25299}{25343}dokud jsem nepotkala Hrabìte.
{26248}{26272}Omlouvám se...
{26287}{26343}e jste si vzpomnìla na tak bolestné vzpomínky.
{26371}{26390}Já...
{26390}{26422}jsem pitomı, e?
{26447}{26485}Má pøítelkynì mi to taky hodnì øíká.
{26502}{26553}Øíká, "Nemyslíš na pocity ostatních lidí."
{26553}{26602}Oh! Ona je spíš kamarádka z dìtství,
{26602}{26637}ne má pøítelkynì, ale...
{26655}{26713}Nedávno hrála na klavír v Opeøe!
{26765}{26830}Je úasné bıt schopen nìco vyjádøit, e?
{26830}{26910}Vnímal jsem tímto zpùsobem, kdy jsem slyšel její pøedstavení.
{26929}{26984}Vy jste také velmi dobrá ve høena na harfu, sleèno Haydée.
{27057}{27119}Prosím, navštivte jednou mou rodinu.
{27132}{27198}Dovolte mi také vám pøedstavit mé pøátele.
{27231}{27270}Noc, kdy jsme pøijeli do Paøíe,
{27312}{27380}mi Hrabì øekl:
{27403}{27425}"Haydée,
{27425}{27509}tohle je zemì, kde je pøijímáná svoboda a lidská práva.
{27509}{27619}Mìla bys dìlat, co si pøeješ, ze své vlastní vùle."
{27640}{27693}Ale já si myslím toto:
{27711}{27773}Jestlie jsem tady ze své vlastní vùle,
{27773}{27854}pak je toto má svoboda.
{28289}{28345}To dítì je tak bezstarostné, e?
{28363}{28442}I kdy mu hoøí za patama.| /jinak to pøeloit vánì nešlo :P/
{28443}{28462}Prosím pøestaò.
{28481}{28556}"Je úasné bıt schopen nìco vyjádøit, e?"
{28556}{28604}Hah! Zbyteèné!
{28617}{28646}To je zbyteèné!
{28673}{28739}Jsme stejní, ty a já.
{28739}{28806}Vidím skrz tebe, co si doopravdy myslíš!
{28806}{28821}Ne!
{28821}{28855}Já...
{28855}{28902}Nenávidíš ho, ne?!
{28902}{28954}Chceš ho roztrhat na kousky!
{28954}{28994}Pobavme se, ne?
{28994}{29018}Pus ji.
{29164}{29194}Hrabì...
{29236}{29260}Táhni!
{29342}{29386}Jak si pøejete.
{29650}{29690}Pan... Villefort?
{29737}{29764}Zahodila jsem
{29785}{29828}ty hrozné pocity uvnitø mì,
{29828}{29886}kdy jsem vás potkala.
{29886}{29946}Vìøila jsem, e...
{29978}{30056}a doufala jsem v uklidnìní
{30056}{30114}vašeho krutého rozhodnutí.
{30125}{30145}Ale...!
{30145}{30179}Já...
{30179}{30236}nemohla jsem zapomenout!
{30249}{30324}Nemohla jsem zapomenout co jsem |cítila, kdy jsem pøísahala pomstu!
{30355}{30394}Byla to chyba sama o sobì...
{30394}{30483}e jsem dokonce myslela, e jsem chtìla zmìnit vaše rozhodnutí
{30496}{30532}kdy jsem myslela tímto zpùsobem!
{30752}{30778}Hrabì.
{30819}{30882}Tehdy jsem vám zpùsobil velké nepøíjemnosti
{30882}{30948}poskoèením k závìrùm.
{30948}{31026}Jako znak mé omluvy za to, e jsem vás hrubì urazil,
{31026}{31051}prosím pøijmìte toto!
{31051}{31086}Hrabì!
{31466}{31533}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31574}{31650}www.mycolorfullife.blog.cz
