{1}{1}23.976
{49}{148}TaSHee's Gang uvádí
{283}{387}GANKUTSUOU
{2444}{2505}Dobrı veèer, dámy a pánové.
{2521}{2571}Úzkost... Znepokojení.
{2588}{2718}Jeho duše je náchylná k nejistotì a zkaení, |protoe je nevinnı a èistı.
{2734}{2844}Zkaenost, která ho poskvròuje se postupnì rozšiøuje...
{2868}{3060}Nazıvá se to "dospívání", kdy si lidé nemohou| déle navzájem dùvìøovat?
{3162}{3213}KONEC ŠTÌSTÍ A POÈÁTEK PRAVDY
{3702}{3735}Svìt, na kterém ijeme
{3735}{3780}je tenhle mròous?
{3780}{3799}Ano.
{3817}{3900}V tomto obrovském vesmíru je to jako trocha prachu.
{3900}{4004}Navíc od místa, kde jsme nyní, dvacet pìt let od Zemì,
{4018}{4147}svìtlo, které vidíte je z minulıch dvaceti pìti let.
{4184}{4216}Dvacet pìt let...
{4250}{4299}Ano, dvacet pìt let...
{4371}{4392}Jsem rád,
{4392}{4438}e jste mì sem vzal.
{4456}{4525}Kdy se podívám na vìci z vesmíru, zaèínám pøemıšlet, e
{4525}{4604}se mé starosti zdají bezvıznamné.
{4604}{4639}Nicménì,
{4639}{4768}je to v temnotì vesmíru, e nenávist a hoøkost zesilují.
{5178}{5221}Všichni jsou pryè.
{5221}{5248}Franz...
{5266}{5288}a Albert...
{5353}{5417}Omlouvám se, e jsem tì tak najednou zavolala, Franzi.
{5417}{5468}Ne, jsem rád, e tì mùu vidìt,
{5468}{5523}protoe plánuju na chvíli cestovat.
{5567}{5602}Albert pojede s tebou?
{5623}{5686}Zdá se, e odjel nìkam sám,
{5686}{5755}navzdory tomu, e je jeho otec uprostøed voleb...
{5755}{5791}Jak problematickı kluk.
{5791}{5826}Kde je to "nìkde"?
{5840}{5861}Promiò.
{5861}{5908}Ani nevím.
{5932}{5952}Aha...
{5952}{6015}Ale jedna vìc, kterou vím jistì je, e
{6015}{6091}byl stren do nìèeho obrovského,
{6091}{6134}i kdy si to ještì neuvìdomil.
{6189}{6219}Franzi, já-
{6232}{6281}Já vím. Jsi také obì.
{6311}{6330}Poslouchej.
{6330}{6403}Nezáleí na tom, co se od teï stane, neztrácej pohled na to, kdo jsi.
{6429}{6479}Hledej pravdu podle sebe.
{6939}{6989}Pøed tím, ne jsem vás poznal Alberte,
{6989}{7048}pilotoval jsem tuto loï sám
{7048}{7101}a cestoval na úplnı konec vesmíru.
{7123}{7165}Vy jste pilotoval tuto velkou loï sám?
{7183}{7210}Ano.
{7210}{7282}Tehdy jsem byl docela pyšnı na fakt, e
{7282}{7344}bych mohl ovládat obrovskou loï.
{7344}{7406}Teï se na to prosím podívejte.
{7427}{7448}Co je to?
{7460}{7501}V prastarıch dobách,
{7501}{7563}to bylo v Orientu známo jako "River of Heaven".
{7563}{7594}Mléèná dráha?
{7610}{7663}Chtìl jsem vám to ukázat.
{7692}{7734}Nádherné...
{7734}{7779}Podle legendy,
{7779}{7929}ili dva milenci na protìjších bøìzích rozdìlujících River of Heaven,
{7929}{8035}ale jednoho roku, pøekroèili øeku a sešli se.
{8035}{8073}Romantickı pøíbìh.
{8132}{8240}Mezi mımi starımi pøáteli je námoøník z Marseille.
{8240}{8327}Mìl ve zvyku mi èasto øíkat tento pøíbìh.
{8361}{8433}Vaši pøátelé musí bıt zamilovaní.
{8481}{8571}Námoøník mìl velmi krásnou snoubenku
{8571}{8634}a blízkého pøítele, kterı se tím uklidòoval.
{8646}{8695}Ti tøi byli pøátelé z dìtství
{8695}{8774}a byli k sobì vdy ohleduplní.
{8774}{8901}Ano, podobnì jste na tom vy, pan Franz a sleèna Eugénie.
{8937}{8956}Nicménì,
{8956}{9082}pøítel tajnì miloval námoøníkovu milenku.
{9082}{9115}A...
{9144}{9239}chtìl získat námoøníkovu snoubenku za kadou cenu,
{9239}{9278}pøedevším,
{9278}{9354}pøítel zapletl námoøníka do zloèinu, kterého se nedopustil.
{9354}{9372}Coe?
{9384}{9420}Neznámo všem,
{9420}{9466}nešastnı námoøník byl pøipoután ve vìzení
{9466}{9557}v nejvzdálenìjším dosahu vesmíru na deset let.
{9752}{9786}Taková vìc...
{9800}{9836}Nicménì, nastal zázrak.
{9836}{9916}Námoøník byl propuštìn a vrátil se do Marseille.
{9937}{9979}Ulevilo se mi.
{9979}{10000}Nicménì,
{10012}{10118}krásná snoubenka vzdala èekání na námoøníkùv návrat
{10128}{10176}a stala se snoubenkou jeho pøítele.
{10193}{10206}Coe?
{10253}{10276}Ale, to je...
{10311}{10387}Proè... nepoèkala na námoøníka?
{10407}{10452}A proè ukradl
{10452}{10529}snoubenku svého pøítele, navzdory jejich pøátelství?
{10529}{10617}Námoøník zrazen obìma, jeho blízkım pøítelem a jeho snoubenkou,
{10617}{10693}znovu nevkroèil na Zem.
{10806}{10854}Proè pláèete?
{10871}{10896}Nevím...
{10914}{10937}Do teï,
{10952}{11014}jako vy, jsem si myslel...
{11014}{11121}e bych pøíštì nemohl vìøit lidskému srdci...
{11145}{11208}ale nìjak, kdy jsem se díval na vaši tváø,
{11208}{11330}cítil jsem, e takové myšlení je nejsmutnìjší vìc na svìtì a...
{11450}{11468}Hrabì!
{11468}{11563}Uvìøme, e naše pøátelství je samo o sobì vyjímka!
{11578}{11645}A pøinejmenším, já vám vìøím!
{11725}{11753}Ty hodinky.
{11753}{11826}Stále jsou pøesné?
{11967}{11987}Alberte...
{12029}{12098}V blízké budoucnosti opustím Paøí.
{12115}{12130}Coe?
{12146}{12182}Co tím myslíte hrabì?
{12202}{12245}Tak najednou-
{12245}{12300}Mohlo by to bıt kvùli vaší nemoci?
{12311}{12333}Ne.
{12342}{12425}Bylo tu nìco, co jsem musel v Paøíi vykonat,
{12425}{12509}take jsem si dokonce udìlal domov na Champs-Élysées.
{12524}{12663}Nicménì, u je to dokonèeno.
{12697}{13108}Morcerf!
{13108}{13139}Prosím to neøíkejte!
{13139}{13187}Prosím, zùstaòte v Paøíi navdy.
{13187}{13252}Nebo spíše, kdybyste øekl, e to není nemoné,
{13262}{13321}pak prosím, nechte mì jet s vámi!
{13321}{13391}Nechci od vás bıt oddìlen!
{13426}{13456}Vy...
{13456}{13516}se tak moc o mì staráte?
{13516}{13536}Ano.
{13618}{13678}Vášeò èasem uvadá.
{13678}{13719}To není pravda!
{13719}{13744}Já...
{13769}{13799}Já... vás...
{13870}{13894}Jednou...
{13927}{13950}Jednou...
{13950}{14014}se vás zeptám na tu samou otázku.
{14026}{14067}Pochubuju, e se o mì
{14067}{14136}pak budete stále stejnì starat.
{14254}{14274}Hrabì!
{14274}{14306}Máme zprávu z Paøíe.
{14350}{14377}Prosím omluvte mì na chvíli.
{14813}{14833}Pane Noirtiere,
{14846}{14870}proisím øeknìte mi,
{14887}{14928}co je Gankutsuou.
{15581}{15607}Co je to?
{15619}{15639}Mohlo by to bıt?
{15919}{15957}"V pøípadì nouze,
{15957}{16042}je tøetí strana ta, co zná heslo k pouítí tohoto pera
{16042}{16115}a kontakt na majitele."
{16130}{16164}Øíkáte, e dokud známe heslo,
{16177}{16244}máme pøístup do vaší mysli?
{16547}{16595}Krásná.
{16595}{16616}Ano, jestli si správnì vzpomínám-
{16616}{16656}Ano, ona je Hrabìte Monte Christa-
{16813}{16847}Aèkoli opodìnì,
{16847}{16920}pøišla jsem podpoøit generála Morcerfa.
{16920}{16965}Šlechetné!
{16965}{17016}Prosím pojïte. Tudy prosím.
{17351}{17379}Valentino...
{17379}{17407}Tvùj dìdeèek...
{17419}{17489}ti øekl dùleité heslo.
{17516}{17537}Víš co je to?
{17646}{17669}Valentino,
{17688}{17758}teï mám kolem sebe jen nepøátele.
{17758}{17850}Kdyby se mi nìco stalo,
{17850}{17910}pamatuj si tyto kvìtiny.
{17997}{18025}Modré rùe...
{18255}{18301}Jmenuji se Haydée.
{18301}{18355}Pøijela jsem do Paøíe z jistıch dùvodù
{18355}{18465}a dychtivì jsem oèekávala den, kdy spatøím Generála Morcerfa.
{18465}{18528}Ah, jsem poctìn.
{18528}{18620}Omluvte mùj nedostatek mravù, ale vidìl jsem vás pøedtím nìkde?
{18638}{18653}Ano.
{18653}{18717}Nepamatuju si, co se stalo pøed deseti lety,
{18717}{18758}kdy mi byly ètyøi roky...
{18758}{18792}na Janinì.
{18792}{18811}Janina?
{18825}{18950}Ochraòoval jste nás jako odvánı vesmírnı armádní velitel.
{18964}{19013}B-Bylo to tak?
{19029}{19046}Jste
{19057}{19102}hrdina, kterı zachránil království.
{19102}{19135}To je to, èemu jsem vìøila.
{19150}{19173}Do dne...
{19309}{19322}Tak.
{19806}{19897}Nikdy jsem si nemyslel, e bych mohl skonèit pouíváním této spojky jako...
{19897}{20005}Nicménì, to je nìco, za co ji nebudu zapotøebí, odešel jsem z politiky.
{20029}{20075}Dìkuji, Franzi.
{20094}{20173}Tvoji lidé ochránili mou vnuèku.
{20179}{20264}Kdyby ti mé vzpomínky byly uiteèné, vezmi si je.
{20287}{20378}Prosím, postarej se o Valentinu.
{20498}{20543}K-Kdo jsi?
{20543}{20670}Jsem ubohá ena, která ztratila svého otce bìhem neštìstí na Janinì
{20681}{20758}a padla se svou matkou,
{20758}{20800}do rukou kupcù.
{20913}{20998}Mùj otec byl falešnì obvinìn jistım mladíkem z velitelskıch intrik
{20998}{21039}a byl mu vzat ivot.
{21039}{21077}Oh boe!
{21077}{21121}O èem to pro všechno na svìtì mluví?
{21179}{21268}A-A co to má co dìlat s tímhle?
{21268}{21307}To nemá ádnou spojitost?
{21307}{21371}Je to, jak jste øíkal, Generále Morcerfe...
{21383}{21432}ne, Fernande Mondego?
{21432}{21474}Coe?
{21474}{21502}O co jde?
{21502}{21536}Co je s tou enou?
{21536}{21565}"Mondego"?
{21651}{21699}"Gankutsuou": To je...
{21866}{21904}Chateau d'If.
{22173}{22224}Edmond Dantés...
{22300}{22349}Jsem Haydée Tebelin!
{22364}{22407}Jsem dcera bıvalého místokrále Janiny,
{22407}{22491}Aliho Tebelina a jeho eny Vasiliki!
{22566}{22633}Jsem dcera, její otce jste znièil spiknutími
{22633}{22737}a její matka zemøela uprostøed zoufalství!
{22817}{22874}Vìøím, e nemáte omluvy?
{22906}{22938}S-Smìšné...
{22938}{22966}Všichni!
{22966}{23000}To je spiknutí!
{23000}{23092}To je zrada rebelù, kteøí usilují o to, abych se nesta lprezidentem!
{23092}{23111}Má pravdu!
{23111}{23146}Vyeòte tu enu odsud!
{23146}{23176}To je spiknutí!
{23176}{23211}Nenechte se oblbnout!
{23235}{23255}To je pravda.
{23255}{23291}Okamitì zmiz-
{23291}{23352}Ticho, Fernande Mondego!
{23506}{23551}C-Coe?
{23551}{23588}Nedívej se na mì tak!
{23618}{23659}Máš dùkaz?!
{23922}{23959}Oh mùj... Co je to?
{23974}{24081}Dùkaz, kterı se mnou zùstane do konce mého |ivota; dùkaz, kterı mì oznaèkoval,
{24081}{24135}kdy mì tento mu prodal kupcùm.
{24156}{24233}Tato znaèka zaznamenala všechno.
{24300}{24324}Haydée...
{24354}{24410}Dr památku svého otce.
{24410}{24478}Pokud zjistíš, e bys byla zneuctìna,
{24478}{24525}ukonèi svùj ivot... tímto.
{24720}{24753}Fernande Mondego.
{24770}{24814}Nezáleí na tom, jak jste si zmìnil jméno,
{24832}{24912}krev mého otce, která støíkala na vaše èelo
{24936}{24966}nikdy nezmizí!
{25553}{25581}A-Ali...
{25598}{25624}Já...
{25644}{25685}Já jsem se nepletla.
{25685}{25721}Je to tak, jak by to mìlo bıt.
{25736}{25827}Ten mu je mùj nenávidìnı nepøítel - ten, kterı mi všechno vzal.
{25852}{25884}I tak...
{26032}{26053}Ali...
{26135}{26154}Musím...
{26168}{26224}Musím to øíct Hrabìti.
{26224}{26297}Nesmím mu nechat dojem, e je to tak!
{26534}{26550}Hrabì...
{26570}{26613}Stalo se nìco?
{26613}{26679}Proè vypadáte tak znepokojenì?
{26679}{26711}Nevím.
{26723}{26820}Ale cítím pøítomnost hluboké a hrozivé temnoty!
{26847}{26867}Hrabì,
{26885}{26913}co bych mìl-
{26913}{26936}Alberte,
{26953}{26989}vrate se na Zem.
{26989}{27007}Hned teï.
{27007}{27024}Coe?
{27050}{27108}Mìl byste zùstat na stranì svého otce.
{27128}{27153}Mého otce?
{27186}{27236}Právì teï má kolem sebe mnoho nepøátel.
{27236}{27269}Mìl bys bıt taky opatrnı.
{27279}{27335}Stalo se mu nìco?
{27335}{27388}Ihned se vrate.
{27388}{27443}Pùjèím vám svou loï, Spadu.
{27542}{27616}Teï se koneènì dozvíte pravdu.
{27694}{27713}Toto je moná
{27713}{27747}naše sbohem.
{27762}{27779}Ne!
{27823}{27843}Sbohem...
{27895}{27911}Alberte.
{27982}{28006}Hrabì...
{28125}{28149}Proè...
{28189}{28241}Pøinejmenším jsem si myslel, e my dva |bychom si mohli navzájem vìøit...
{28258}{28288}Hrabì!
{28331}{28361}Hrabì!!!
{28737}{28755}Hrabì!
{28839}{28866}Hrabì!
{28931}{28967}Hrabì!
{28987}{29019}HRABÌ!
{30821}{30838}Vracíme se!
{30838}{30878}Zpátky do hlavního mìsta,
{30891}{30919}kde kvete zlo!
{31022}{31091}Loï se nyní vrátí do atmosféry.
{31478}{31527}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31558}{31616}www.mycolorfullife.blog.cz
