{1}{1}23.976
{57}{101}TaSHee's Gang uvádí
{282}{390}GANKUTSUOU
{2445}{2512}Dobrı veèer, dámy a pánové.
{2532}{2655}Koneènì nadešel èas pro mého pøítele na èást cesty s krásnımi vìcmi.
{2673}{2749}Nevinnost, víra a pøátelství.
{2749}{2869}Odhodil své ctnosti a všechny úasné vìci ovládané dìtmi
{2869}{3023}do temnoty vesmíru a dal jim koneèné sbohem.
{3154}{3205}SKANDÁL
{3395}{3479}Janina byla napadena Impériem pøed 15 lety.
{3479}{3577}Dùstojníci Vesmírné armády, kteøí byli na záchranné misi Janiny, |vytvoøili tajnou dohodu s Impériem.
{3596}{3639}Koncil se zachvìl
{3639}{3708}díky skandálu zahrnujícího Generála Morcerfa, |vedoucího kandidáta na prezidentství.
{3754}{3797}Na ústøedí Vesmírné armády.
{4525}{4576}Jsem Albert de Morcerf.
{4589}{4624}Syn prezidentského kandidáta!
{4747}{4803}Byl jste si vy a rodinní pøíslušníci vìdomi
{4803}{4860}toho, co váš otec provedl na Janinì?
{4860}{4956}Prahnul generál po bohatství Janiny?
{4956}{4991}Hej, au! Nestrkejte se!
{4991}{5057}Co si myslíte o odpornıch èinech svého otce?
{5072}{5095}Prosím uhnìte z cesty!
{5095}{5141}Prezidentskı kandidát by se mìl paøíanùm omluvit!
{5141}{5160}Omluvit!|/To je pravda!/
{5160}{5197}Omluvit!|/Slyšeli jsme, e vaši rodièe jsou z Marseille./
{5197}{5221}Nemám tušení!
{5221}{5266}Poádal jsem, abyste uhnuli z cesty!
{5266}{5339}Šíøí sezvìsti, e vaše Snìmovna není ve skuteènosti šlechtická.
{5339}{5387}Mùeme to vyloit jako monı dùkaz o padìlání záznamù?
{5387}{5416}Hrubé!
{5416}{5476}Pøestaòte uráet mého otce, bastardi!
{5488}{5511}"Uráet"?
{5511}{5593}My, paøíané, jsme jediní, kdo byli uraeni!
{5593}{5622}Jsi syn zrádce,
{5622}{5688}kterı spolupracoval s nepøátelskımi vojsky|a prodal krále pro lásku k penìzùm!
{5850}{5873}Vikomte de Morcerfe.
{5873}{5892}Mùj otec!
{5892}{5924}Kde je?!
{5938}{5999}Pøišel jste hlavní branou?
{5999}{6033}Ztøeštìné...
{6033}{6075}Nyní se mnou pojïte k zadní bránì.
{6075}{6110}Je pro vás nebezpeèné, zùstat zde.
{6110}{6129}Otec!
{6129}{6158}Kde je?!
{6158}{6184}Nechte mì s ním mluvit!
{6195}{6218}Bohuel,
{6218}{6300}tato situace mu dìlá starosti,
{6300}{6332}tak se sem dnes s nejvìtší pravdìpodobností nevrátí.
{6353}{6376}Aha.
{6376}{6448}Pak, a mùj otec ví,
{6448}{6485}e bych s ním rád o nìèem mluvil...
{6497}{6517}a e já
{6534}{6577}mu vìøím!
{6593}{6625}Rozumím.
{6984}{7002}Vstupte.
{7115}{7149}Udìlal jsem vše, co jsem mohl.
{7149}{7251}Nicménì, ospravedlnit vás pøed Koncilem... mùe bıt teké.
{7251}{7320}Ji mluví o povolání svìdkù.
{7320}{7347}V poøádku.
{7347}{7368}Teï odejdi.
{7380}{7439}Pøed chvílí tu byl váš syn.
{7466}{7553}Dle pøíkazù jsem mu øekl, e tu nejste.
{7565}{7589}Co øíkal?
{7589}{7627}Váš syn...
{7627}{7707}øekl, e vìøí svému otci.
{8042}{8059}Alberte!
{8077}{8099}Rychle nastup!
{8283}{8303}Eugénie!
{8328}{8366}Kam si myslíš, e v takové dobì jdeš?
{8385}{8443}Proè nemùeš poslouchat to, co øíkám?
{8443}{8458}Ne.
{8458}{8485}Pus.
{8485}{8511}Pus mì!
{8525}{8600}Pøikázal jsem ti, abys nenechala mou dceru opustit dùm!
{8600}{8630}Proè tady teda je?!
{8630}{8652}Zavolej stráe!
{8652}{8677}Ano, pane.
{8689}{8796}Otèe, øíkáš mi, abych ignorovala mého pøítele,|kdy je jeho rodina v takové situaci?!
{8796}{8831}Hlupaèko!
{8831}{8890}Jestli teï odejdeš, staneš se obìtí novináøù!
{8890}{8986}Všichni budou u vytrení z toho co se stalo nebo|nestalo mezi tebou a tím klukem, Albertem
{8986}{9035}a skonèíš jako veøejná zábava!
{9035}{9076}Mùeš tomu rozumìt?!
{9076}{9121}To s tím nemá nic spoleèného!
{9191}{9209}Poslouchej mì.
{9209}{9256}Nezáleí jen na tobì.
{9269}{9359}Nedovolím nic, co by mohlo sníit tvou hodnotu!
{9390}{9419}Ujistìte se, e sledujete mou dceru tak,
{9419}{9452}aby se nemohla dostat ven!
{9585}{9631}Tolik se bojíte
{9631}{9680}o Vikomta Morcerfa?
{9704}{9736}Jestli je to pro vás v poøádku,
{9736}{9827}tak se pùjdu Alberta zeptat místo vás.
{9846}{9860}Ale...
{9956}{9998}Mìla byste zùstat tady.
{9998}{10076}Nemohl bych snést pohled na tak bájeènou osobu, jako jste vy,
{10076}{10133}aby byla poskvrnìna nemilosrdnımi lidmi.
{10211}{10256}Zoufale jsem tì hledal, Alberte.
{10273}{10368}Tvá spolehlivost je nezodpovìdná, zkoušet pøitanèit pøímo do ústøedí armády,
{10368}{10427}kdy se stal takovı skandál.
{10551}{10628}"Rádi bychom nìco øekli o generálu Fernandu de Morcerfovi."
{10628}{10653}Novináø,
{10653}{10687}Robert Beauchamp...
{10791}{10841}Vezmi mì za Beauchampem.
{10858}{10874}Hned!
{10929}{10988}Ah, promiòte za èekání.
{11027}{11042}Alberte?
{11042}{11058}Ty-
{11152}{11174}Bastarde!
{11174}{11233}Jak se opovauješ chovat jako pøítel, kdy|jsi mì celou dobu klamal?!
{11248}{11292}"Dávej pozor na skandály"?!
{11292}{11388}Po celou dobu jsi zamıšlel prodat mého |otce exkluzivnì na první stranu!
{11401}{11426}Není to pravda?!
{11426}{11448}Huh?!
{11485}{11531}Poslouchej mì, Alberte.
{11531}{11630}Øeknu ti všechno, co jsem zjistil a do teï; prostou pravdu,
{11642}{11679}bez lí.
{11679}{11736}Tak, poslouchej, co chci nejdøív øíct.
{11805}{11833}Podívej se na tohle.
{11833}{11889}Koupil jsem to na èerném trhu od dealera z Impéria.
{11889}{11926}Je to kopie potvrzení.
{11926}{12069}"Tímto já pøevádím Královnu Janiny Vasiliki| a Princeznu Haydée, za milion frankù."
{12077}{12143}Pøevodce, Fernand Mondego.
{12175}{12216}Tak co?!
{12232}{12316}Sledoval jsem stopy mue jménem Mondego.
{12316}{12380}Nicménì, všechny ostatní informace tıkající se ho, byly vymazány,
{12380}{12473}jako by nikdy neexistoval.
{12491}{12553}Ale Mondego existoval.
{12570}{12611}Po návratu do Marseille,
{12611}{12646}okamitì pouil získané peníze,
{12658}{12723}pro koupi svého titulu.
{12735}{12777}Potom si zmìnil jméno.
{12801}{12828}Kde je dùkaz?!
{12828}{12848}Dej mi dùkaz!
{12860}{12924}Alberte, dokumenty Ministerstva vnitra
{12924}{13010}také ukazují, e Mondego a Villefort sahají daleko.
{13022}{13060}Jsou oba z Marseille,
{13081}{13210}a Villefort je jedinı, kdo mohl vymazat všechny|zmínky o Mondegovi z oficiálních dokumentù.
{13210}{13317}Takhle, osoba jménem Mondego byla odstranìna,
{13317}{13389}a osoba jménem Fendand de Morcerf se narodil na jeho místì.
{13389}{13446}Take mi øíkáte, e mùj otec je stejná osoba jako
{13446}{13513}toto chladnokrevné zvíøe Fernand Mondego?!
{13513}{13585}Je to zábava, srazit jeden druhého,|zatímco se loví neštìstí mé rodiny?!
{13585}{13608}Nesmysl!
{13608}{13695}Myslíš si, e bych lehkovánì napsal falešnı èlánek?!
{13695}{13719}Ty...
{13719}{13794}Rozumíš tomu, jak jsem se cítíl, kdy jsem to psal?
{13794}{13913}Øíkáš, e jsem lstivı bastard,|kterı by prodal exkluzivnì své pøátele-
{13913}{13927}U dost.
{13987}{14048}Jsem... novináø.
{14048}{14153}Nesu odpovìdnost øíkat svìtu pravdu,|bez ohledu na následky.
{14334}{14349}Sakra!
{14421}{14489}Nesmrtelnı mu, kterı ije v Chateau d'if.
{14489}{14516}Gankutsuou...
{14533}{14640}Znaèka, kterou jsem vidìl na èele Hrabìte v sídle Auteuil je,
{14640}{14688}bezpochyby, symbol Gankutsuou.
{14725}{14803}Pak, znamená to, e se Hrabì stal Gankutsuou?
{14826}{14855}Proè je v Paøíi?
{14881}{14956}Jestli budeš tak tìce pracovat, tvé zdraví bude trpìt.
{14968}{15027}Nezùstal jsi vzhùru celou vèerejší noc, e?
{15040}{15104}Moc se o mì staráš, Maxmiliáne.
{15114}{15139}Prosím jez.
{15139}{15189}Je to vesnické jídlo, ale zregeneruje tì.
{15201}{15246}Jo, vypadá to skvìle.
{15246}{15279}Díky.
{15332}{15373}Vezmi mu to.
{15373}{15432}Nechci. Je mi trapnì.
{15432}{15510}Jsi ta, co øíkala, e chce vidìt Franze.
{15510}{15563}Pojï se mnou, bráško.
{15563}{15600}Copak to dìláte?
{15600}{15634}Bráško!
{15657}{15679}Um...
{15688}{15702}Um...
{15702}{15726}Pojïte.
{15804}{15835}Prosím snìz tohle.
{15857}{15903}Øíkala, e vypadáš nešastnì,
{15914}{15952}tak jsme tohle spoleènì udìlali.
{16047}{16065}Dìkuji.
{16293}{16318}Dobrá práce.
{16991}{17010}Poslouchej!
{17010}{17045}Jsi naøadì!
{17045}{17131}Pohroma stihne i tvùj dùm!
{17244}{17262}Divné.
{17262}{17277}Co?
{17288}{17354}Divné, e je tak velká rodina v jednom domì.
{17354}{17435}Ale ve vašem domì musí bıt taky hodnì lidí, Franzi.
{17445}{17467}Pøedtím ano.
{17467}{17491}Byla tam spousta najatého sluebnictva.
{17517}{17599}Ale teï, jen pár z nich tam stále je spolu s mou matkou.
{17599}{17635}Je to pravda...
{17650}{17709}Je mnoho druhù aristokratù.
{17709}{17856}Mé zasnoubení s Valentinou bylo násilnì rozhodnuto panem Villefortem,
{17856}{17910}protoe má rodina byla po generace paøíští Loajalisté.
{17925}{18027}No, myslel jsem si, e by nemusel bıt špatnı nápad mít podporu,
{18027}{18071}kdy jsem se rozhodl jít do doplomacie,
{18071}{18138}protoe jsem nemìl tolik penìz jako Albertova rodina.
{18150}{18177}Omlouvám se.
{18177}{18234}Neuvaoval jsem. Neznal jsem okolnosti...
{18264}{18335}Nejsem tak hloupı, abych potøeboval tvou starost.
{18335}{18396}I kdy na to moná nevypadám, hodnì studuju.
{18599}{18641}Pan Noirtier øekl také toto:
{18641}{18712}Maxmiliáne, mìl bys udìlat Valentinu šastnou
{18712}{18789}od teï místo mì.
{18801}{18821}Udìlám.
{19058}{19082}Kdo je ten mu?
{19113}{19175}Mùj otec. Zemøel pøed tøemi roky.
{19175}{19225}Musel mít dobrou loï.
{19241}{19327}Jmenovala se Pharaon. Byla naším hvìzdnım plavidlem.
{19327}{19374}Aèkoli, teï patøí nìkomu jinému.
{19464}{19495}"Edmond Dantés"?
{19510}{19528}"Edmond"?
{19528}{19588}Znáš Edmonta Danta?
{19600}{19660}Víš o tom mui?
{19660}{19681}Ano.
{19696}{19780}Byl prvním dùstojníkem "Morrel a Syn".
{20054}{20074}To není dobré.
{20074}{20165}V téhle míøe není zpùsob, jak se dostat dovnitø|prostøednictvím hlavní nebo zadní brány.
{20232}{20266}Tudy, tudy!
{20314}{20337}Tady je to.
{20360}{20435}Jediné dveøe v celém domì, které nejsou chránìny.
{20450}{20499}Jak víš o nìèem takovém?
{20522}{20543}Hej, Peppo.
{20570}{20596}Rychle,
{20596}{20632}nebo se objeví paparazzi.
{20661}{20684}Jsem tvùj dluník.
{20831}{20874}Sbohem, Alberte.
{20905}{20934}Hej, nìkdo tam je!
{20934}{20951}Co je to?
{20951}{20963}Bìte!
{20989}{21012}Matko!
{21012}{21040}Jsi tady?
{21066}{21088}Matko!
{21115}{21138}Matko!
{21138}{21163}Jsi pryè?
{21395}{21409}Matko!
{21558}{21580}Alberte...
{21595}{21638}Matko, jsi v poøádku!
{21649}{21729}Jsem ráda, jsem ráda, e jsi také v poøádku.
{21729}{21778}Matko, já-
{21778}{21832}Vypadáš tak vyèerpanì.
{21832}{21880}Nejspíš jsi nic nejedl.
{21905}{21976}Poèkej tady. Zeptám se jich, jestli by ti mohli udìlat nìco k jídlu.
{21990}{22063}Prosím pøestaò nastavovat dobrou tváø.
{22063}{22155}Mám dost toho, e jsem byl povaová za dítì, které nic neví!
{22182}{22199}Já...
{22212}{22258}nechci slyšet ádné li.
{22362}{22444}Ani Fernand ani já... nejsme praví aristokrati.
{22479}{22596}Jsme prostí lidé, narození v malé vesnièce Catalinii, na okraji Marseille.
{22611}{22631}Matko...
{22697}{22744}Pak, otcovo jméno...
{22791}{22828}Pravé jméno tvého otce je...
{22856}{22900}Fernand Mondego.
{22966}{23048}Jakmile jsem si uvìdomila, co se stalo, |bylo moc pozdì na to, vrátit to zpìt.
{23048}{23157}Jednou jsem øekla, e jsem byla aristokratkou od narození, |nemìla jsem na vıbìr, jen v tom dále pokraèovat.
{23179}{23251}Potom, bìhem volební øeèi, jsem se dozvìdìla pravdu.
{23265}{23284}Ale proè?
{23298}{23345}Proè to øíkáš, matko?
{23360}{23417}Proè otci nevìøíš?
{23428}{23569}Ten den, jsem slyšela øeè princezny Janiny na vlastní uši.
{23582}{23676}Kdybych cítila, e je to le, klam,
{23676}{23794}jsem si jistá, e bych si vynutila,|aby byla potrestána hned tam, na Nebeském místì.
{23794}{23811}Ale...
{23851}{23874}Alberte,
{23896}{23984}èlovìk musí dostat za své èiny to, co si zaslouí.
{24004}{24070}Nikdo nemùe obrátit nìèí oèi daleko od pravdy.
{24307}{24375}Haydée chtìla, aby se tohle stalo, u od zaèátku!
{24410}{24420}Sakra.
{24420}{24444}Sakra!
{24449}{24554}Mùj otec a já jsme kadı rok nosili kvìtiny
{24554}{24590}na hrob pana Edmonda Danta.
{24621}{24681}Mùj otec vdycky tiše upøenì sledoval moøe
{24681}{24761}a nikdy o nìm moc neøekl.
{24761}{24819}Nicménì, na své smrtelné posteli,
{24819}{24919}mùj otec volal Edmondovo jméno, kdy køièel.
{24919}{24948}"Chci vidìt Edmonda.
{24948}{24987}Chci vidìt Edmonda.
{24987}{25065}Proè jsem nemohl Edmonda zachránit?"
{25065}{25086}A tak dál.
{25101}{25122}Maxmiliáne...
{25144}{25205}Prosím, uka mi seznam posádky "Morrel a Syn".
{25258}{25344}Skoro nikdy jsem nevidìl záznamy z èasù mého otce.
{25362}{25377}Edmond...
{25377}{25403}Edmond...
{25403}{25435}Oh, tady je to.
{25471}{25492}Je to jiné...
{25492}{25532}Jeho oblièej je úplnì jinı.
{25545}{25564}Nicménì...
{25564}{25616}Je tu o nìm nìjaká chyba?
{25616}{25702}Edmond je jméno ze vzpomínek pana Noirtiera.
{25715}{25752}Pøed dvaceti pìti lety,
{25752}{25835}byl poslán do vìzení ve vzdáleném |vesmíru za zloèin, kterı nespáchal.
{25949}{25969}To nemùe bıt!
{25969}{26004}Danglars!
{26004}{26060}Byl lodní úèetní?
{26437}{26452}Aha...
{26452}{26490}Tak to je to, co to asi bylo...
{26523}{26558}Musím rychle zpìt.
{26558}{26592}Albert je v nebezpeèí!
{26592}{26645}Tak co se dìje?
{26679}{26698}On ije.
{26744}{26773}Edmond Dantés...
{26794}{26814}je naivu!
{26884}{26912}Haydée!
{26933}{26963}Pojï ven!
{26963}{27001}Haydée!
{27010}{27062}Uka se!!!
{27062}{27125}Haydée!
{27586}{27639}Dlouho jsme se nevidìli, chlapeèku.
{27639}{27680}Vidíme se poprvé od setkání na Lunì.
{27709}{27729}Luigi...
{27729}{27760}Vampa.
{27778}{27833}Co dìláte v domì Hrabìte?
{27833}{27919}Co tady dìláme? Hah.
{27919}{27975}Jsi stále trochu pomalı.
{27994}{28043}No, proè mu to nevysvìtlíš?
{28255}{28272}Ty...
{28272}{28320}jsi øíkala, e jsi bandity opustila.
{28320}{28347}Peppo!
{28361}{28477}Podle pøíkazù hrabìte jsem tì sledovala celou dobu, Alberte.
{28495}{28526}V podstatì,
{28526}{28615}oznamovala jsem kadı tvùj pohyb Hrabìti.
{28797}{28850}Proè by hrabì naøizoval nìco takového?
{28882}{28932}Zaèal jsi mít tušení, e?
{28947}{29022}Proè se ti hrabì na Lunì pøiblíil
{29022}{29069}a pøijel do Paøíe.
{29101}{29121}Sklapni!
{29121}{29151}Kde je Haydée?!
{29151}{29202}Pohnìte a pøiveïte Haydée sem!
{29280}{29325}Jeho dvoøané opustila tento dùm.
{29386}{29456}Majitel brzo pøiletí na Zem.
{29697}{29732}Generál Morcerf...
{29746}{29780}Skandál o Janinì...
{29797}{29854}Zaèal jste jednat, hrabì.
{29885}{29939}Buï prosím v bezpeèí, Alberte.
{30329}{30367}Haydée!
{31474}{31555}Pøeklad + korekce+ èasování: WelW(etkaAa)-hime
{31575}{31638}www.mycolorfullife.blog.cz
