{1}{1}23.976
{58}{157}TaSHee's Gang uvádí
{284}{388}GANKUTSUOU
{2437}{2497}Dobrı veèer, dámy a pánové.
{2520}{2664}ivot chlapce, kterı byl nabídnut mému pøíteli,|vymizel v objetí nevinné duše.
{2678}{2715}A já jásal.
{2733}{2788}Nakonec, byla ta duše zašpinìna
{2803}{2920}plameny lítosti a nenávisti, které nikdy nezmizí...
{3271}{3314}Franzi... proè...?
{3340}{3452}Slíbil jsi... e bys nešel na vzdálené |místo bez toho, abys mi o tom øekl...
{3725}{3747}Franzi...
{3769}{3785}Já...
{3811}{3882}nemohl jsem se pøinutit, abych se zúèastnil tvého pohøbu.
{3904}{3937}Myslím, jak jsem mohl?
{3937}{4033}Do vèerejška, jsi byl... na mé stranì, správnì?
{4046}{4084}Nezáleelo na tom, o jakou situaci šlo,
{4084}{4130}vdycky si byl na mé stranì, správnì?
{4147}{4169}A pøesto...
{4196}{4237}opustil jsi mì tímto dopisem...
{4290}{4329}Proè jsi to musel bıt ty?!
{4329}{4395}Proè ty a ne já?!
{4423}{4444}Franzi...
{4463}{4500}Prosím odpovìz mi...
{4516}{4553}jak jsi to vdycky dìlal...
{4553}{4627}Øekni nìco... cokoli...
{4640}{4672}Franzi!
{4697}{4756}I KDYBYCH U NEBYL SÁM SEBOU
{4866}{4908}Královna na F3.
{4991}{5070}Pìšák z C7 na C6.
{5197}{5237}Akcie z Danglars Bank
{5237}{5298}zasáhly pøed pár dny vıškovı limit.
{5329}{5362}Jezdec na E4.
{5423}{5459}Ceny akcií kadé investice|/Královna z B6 na C7./
{5459}{5531}se budou dále zvyšovat prudkou rychlostí.
{5531}{5604}Andrea... Vede si lépe, ne jsme oèekávali.
{5604}{5635}Dobøe.
{5635}{5703}"Osprchujeme" ho tím, e všechny |jeho investice rozprodáme.
{5715}{5744}Ty v Paøíi, samozøejmì;
{5744}{5805}jako ty ve Vıchodním vesmíru a ty za hranicemi,
{5805}{5904}oèistíme je rozprodáním do všech|otevøenıch oken ve správném èase.
{5904}{5927}Jak si pøejete.
{5972}{6004}Pìšák na C4.
{6022}{6057}Mimochodem, hrabì,
{6068}{6128}Haydée øíká, e by s vámi ráda mluvila.|/Jezdec z D5 na E7./
{6176}{6200}Hrabì...
{6219}{6331}Nesnesu, e vidím nìkoho, koho miluji|více ne vlastního otce, dále se mìnit.
{6346}{6365}Prosím...
{6385}{6453}nepokraèujte v takovıch vìcech-|/Jezdec z E4 na G5./
{6453}{6493}Neodhazuj stranou zbyteèné kousky bez lítosti!
{6493}{6578}Všichni z tìch, kteøí stojí na cestì pomsty... bez slitování!|/Jezdec z E7 na C8./
{6578}{6609}Bertuccio!
{6609}{6647}Odveï Haydée pryè.
{6647}{6682}Rozumím.
{6706}{6729}Hrabì!
{6729}{6814}Zachránil jste mì, protoe jste si pøál|pouít mì jen jako nástroj k pomstì?!
{6828}{6872}Nejste takovı!
{6872}{6902}Hrabì...
{6902}{6946}Vìøím vám!
{6962}{6984}Hrabì!
{6994}{7025}Hrabì!!!
{7046}{7076}Pìšák na C5.
{7132}{7170}Vyhrál jste.
{7246}{7266}Konec...
{7266}{7302}u mám na dosah!
{7324}{7370}Podívejte, Andreo!
{7370}{7404}Podívejte se na dnešní ceny akcií!
{7419}{7477}Ah, nemùu se pøestat smát!
{7477}{7511}Je hezké to slyšet.
{7536}{7578}Tento úspìch by bez vás nebyl monı.
{7578}{7606}Jsem vašim dluníkem.
{7606}{7634}Prosím, to neøíkejte.
{7654}{7680}Dùleitìjší,
{7680}{7738}tıkající se svatby s vaší dcerou...
{7780}{7818}O-O tom...
{7818}{7879}Kòuèí, e se právì teï nemùe vdát,
{7879}{7947}protoe jí právì zemøel pøítel.
{7966}{8040}Ah, zajímalo by mì, komu se to podobá... |Tak sobecká dívka.
{8040}{8075}Ah, rozumím.
{8103}{8163}Mimochodem, jak se má její matka?
{8177}{8226}Dlouhou dobu mìla depresi, e?
{8226}{8259}Mohl bych jí vìnovat pozornost-
{8259}{8288}Samozøejmì!
{8288}{8358}Kdybyste se drel v její spoleènosti, jsem |si jistı, e by se cítila lépe.
{8386}{8402}Doufám...
{8402}{8434}e je to dùvod.
{8476}{8605}Zajímá mì, o kolik se zvıší jmìní naší banky, Michéle.
{8605}{8627}Ano.
{8659}{8674}Otevøít!
{8674}{8805}Kadı jedinec si vede dobøe.
{9124}{9138}Alberte...
{9187}{9250}Prosím poslouchej pozornì, Alberte.
{9250}{9308}Pøemıšlím o... opuštìní Paøíe.
{9339}{9390}Pojeïme spoleènì do mé vlasti.
{9407}{9519}Samozøejmì, naše zpùsoby ivota se stanou|více utlumenımi, ve srovnání s nynìjšími.
{9519}{9575}Kdybychom jen my dva,
{9575}{9646}mám dost úspor na to, abychom se uivili-
{9646}{9680}A co otec?
{9712}{9760}Opravdu usiluješ o to, co je pohodlné,
{9760}{9779}e, matko?
{9801}{9823}Alberte!
{9823}{9865}U toho mám dost!
{9884}{9963}To kvùli tobì a ostatním,|e se tohle v první øadì stalo.
{9963}{10093}Byl jsem vtaen do tohoto stupidního vztahu|mezi tebou a dvìma mui, kteøí tì milují.
{10112}{10171}A co Edmond Dantés?
{10171}{10209}Proè my...
{10209}{10299}Proè musel ze všech lidí zemøít zrovna Franz?!
{10372}{10404}Kam jdeš, Alberte?
{10404}{10424}Kdo ví.
{10424}{10450}Mám kam jít.
{10466}{10494}Nestarám se...
{10494}{10525}co se se mnou stane.
{10545}{10610}Bylo by lepší... kdybych zemøel.
{10738}{10777}Jestli mì chceš obviòovat,
{10777}{10819}pokraèuj a obviòuj mì po zbytek svého ivota!
{10839}{10869}Ale ty...
{10903}{10987}Prosím, starej se o sebe víc!
{11425}{11439}Co...
{11488}{11514}Vaše povolení?
{11536}{11557}ádné nemám.
{11557}{11607}Vdycky jsem mohl projít, tak...
{11619}{11702}To prostì nejde... Aby si's myslel, e mùeš| pokraèovat jen proto, e jsi aristokrat.
{11734}{11796}U jsi zbavenı svého poøadového èísla.
{11796}{11851}U ti není dovoleno potulovat se okolo, |jak se ti zlíbí.
{11851}{11882}A co s tím?
{11882}{11931}Oh, nic. Je to tak, jak jsi slyšel.
{11931}{12020}Øíká se, e od hloupıch rodièù pøicházejí hloupé dìti.
{12020}{12089}Teï, si jdi pro povolení.
{12089}{12150}Pokud ti ho nìkdo vydá.
{12150}{12177}Jo, správnì.
{12336}{12356}Bastarde!
{12518}{12559}Podvodníku!
{12680}{12702}Nechte toho!
{12702}{12726}Odejdìte od mé motorky!
{12726}{12762}Dejte ruce pryè!
{12762}{12785}Hej!
{12785}{12829}Já jsem ten, co s tebou jedná!
{12904}{12985}Procesor nemusí bıt poøád zatíenı. Huh?!
{13331}{13414}Tento stav se nehodí k tak krásnému| èlovìku jako jste vy.
{13443}{13461}Je mi fajn.
{13461}{13520}Vdy jsem sama.
{13520}{13550}Oh, prosím...
{13567}{13623}Kdy vidím váš smutnı oblièej,
{13623}{13671}cítím se, jako by mi mìlo puknout srdce.
{13697}{13767}Mui mi vdy øíkají takové vìci, |aby mì uklidnili.
{13807}{13878}Jsem vám vdy nablízku,
{13899}{13922}matko.
{13978}{14005}Andreo...
{14095}{14146}Prosím... jen pro dnešek...
{14146}{14204}jen pro teï... øíkejte mi Victorie.
{14227}{14253}Ah, Victorie...
{14745}{14770}Ty bastarde...!
{14994}{15029}Jsi v poøádku, Alberte?
{15071}{15102}Franzi...
{15118}{15146}Jsi to ty, Franzi?
{15146}{15179}Huh, coe?
{15190}{15213}Jsi v poøádku?
{15240}{15264}Franzi!
{15264}{15298}Hej, hej.
{15326}{15351}Jsem šastnı...
{15366}{15396}Jsem šastnı...
{15396}{15423}e jsi v poøádku.
{15445}{15515}Jsi ve stavu, kdy se o mì bojíš.
{15538}{15576}No tak, pojïme domù.
{15653}{15733}Všechno nejlepší, Alberte!
{15797}{15827}Blahopøeju, Alberte.
{15827}{15884}Blahopøeju. Máš pìkné zpodìní.
{15884}{15922}Co jsi dìlal?
{15922}{15960}Celou dobu na tebe èekala, víš?
{15960}{15978}Coe?
{15978}{16009}"Ona"?
{16122}{16145}Eugénie...
{16145}{16173}Alberte...
{16198}{16259}Všechno nejlepší k šestnáctinám.
{16369}{16435}Aw, pøedvádìt se pøede všemi!
{16435}{16491}Nemùete dìlat nìco takového v soukromí?
{16536}{16566}A teï, všichni,
{16566}{16639}zde je náš host a velké finále tohoto veèírku!
{16639}{16688}Albertùv zachránce na Lunì,
{16688}{16734}Hrabì Monte Christo!
{16894}{16967}Nemìl jsi tuhle osobu zvát do Paøíe, Franzi!
{16967}{16992}Proè?
{16992}{17059}Vdy jsme naléhali, aby pøijel, ne?
{17059}{17086}Vidíš?
{17101}{17154}Všichni chtìli Hrabìte poznat.
{17154}{17182}Ne!
{17182}{17271}Je to démon, kterı se vrátil do Paøíe,|aby na nás vykonal svou pomstu!
{17271}{17305}Pøivitáš ho první, drahı?
{17305}{17346}Otèe, matko, utíkejte!
{17346}{17386}Eugénie, Franzi, lidi, vypadnìte odsud!
{17400}{17416}Rychle!
{17416}{17461}Bìte tak rychle, jak mùete!
{17550}{17570}Hrabì...
{17587}{17635}Dìkuji, e jste mì pozval.
{17635}{17673}Ne, ne Franzi...
{17689}{17741}Vezme ti ivot!
{17741}{17775}"Oh? Zajímavé."
{17814}{17830}Prosím...
{17858}{17884}Prosím tì...
{18445}{18472}Tohle je za tebe
{18472}{18504}Franzi!
{18667}{18710}Øekni, Alberte...
{18803}{18820}Ty...
{18820}{18854}jsi mì zabil.
{18902}{18978}Ty jsi ten, co mì zabil, správnì, Alberte?
{19026}{19053}Byl jsi to ty, e?
{19053}{19067}Ne...
{19067}{19107}Chtìl jsem tì zachránit!
{19107}{19178}Lháøi, myslíš jen na sebe.
{19208}{19311}Ani jednou jsi neposlouchal, co jsem ti øekl, ne?
{19311}{19331}To není pravda.
{19331}{19359}To není pravda, Franzi!
{19359}{19394}Proklínám tì.
{19414}{19456}Proklínám tì po zbytek tvého ivota.
{19534}{19555}To bolí...
{19580}{19605}To bolí...
{19630}{19649}To bolí...|/Franzi!/
{19666}{19686}To bolí...
{19686}{19702}Franzi...!
{19702}{19720}To bolí...
{19720}{19737}Franzi...
{19737}{19761}Promiò, Franzi.
{19761}{19777}Franzi.
{19931}{19973}Ne, neumírej Franzi!
{19973}{19997}Prosím neumírej!
{20012}{20065}Musím ti nìco øíct!
{20065}{20135}Tak mì prosím neopouštìj!
{20135}{20153}Ne...
{20153}{20188}Neumírej, Franzi!
{20188}{20220}Franzi!
{20237}{20328}Franzi!!!
{20346}{20391}Hej, Alberte.
{20391}{20421}Jsi v poøádku?
{20432}{20464}Podr si to.
{20464}{20480}Hej!
{20480}{20513}Alberte!
{20513}{20530}Hej!
{20555}{20571}Franzi-
{20571}{20685}Není to nic váného, pokud se nebudeš moc hıbat.
{20703}{20722}Renaude...
{20806}{20826}Kde to jsme...?
{20826}{20904}Vidìl jsem, jak nìkdo jede na tvé motorce.
{20904}{20937}Nedìlej si starosti.
{20937}{20981}Tvoje motorka je v bezpeèí.
{20981}{21029}Ti zlí chlápci byli potrestáni!
{21058}{21076}Promiò.
{21076}{21116}Co to povídáš?
{21116}{21183}Jeden by mìl mít blízké pøátele,|kteøí mají rádi náøadí a mechaniku, ne?
{21183}{21246}Aèkoli, kdy jsem zpanikaøil a spìchal jsem sem,
{21246}{21290}auto skonèilo takhle.
{21353}{21371}Máš vùbec pøedstavu
{21371}{21444}jak moc jsem touil, aby tento den pøišel?!
{21444}{21485}Po zoufalém hledání vzácnıch èástí,
{21485}{21567}a pak procházení nejrùznìjšími obtíemi,|jsem ho nakonec znovu spustil!
{21577}{21609}Byl jsem na dlouhé cestì
{21609}{21666}se srdcem plnım vzrušení a radosti...
{21666}{21709}"Oh?" To je tvoje motorka.
{21709}{21737}Kdo to sakra je?"
{21740}{21818}Pøistoupil jsem k nìmu a zeptal se ho,|proè má tvou motorku, a pak-
{21818}{21841}Podej mi páku s øehtaèkou.
{21877}{21889}Tady.
{22040}{22052}Ooh!
{22052}{22112}Mé milované auto vypadá zotavenì!
{22112}{22139}Jsi jako královna dramatu.
{22139}{22171}Ne, nejsem!
{22171}{22246}Neopravitelné stroje jsou tak ubohé!
{22246}{22341}Bylo hrozné, kdy jsem jel zachránit Valentinu-
{22341}{22376}To auto bylo tvoje?
{22376}{22399}Jo!
{22399}{22469}Boe, bylo to tak bolestivé...
{22485}{22558}Na to jdi myslel, kdy byla Valentina blízko smrti?
{22558}{22581}Nechápej mì špatnì!
{22581}{22642}Udìlal jsem to, protoe jsem slyšel, |e chcete zachránit Valentinu!
{22642}{22662}Co?
{22697}{22790}Abych øekl pravdu, mìl jsem Valentinu trochu rád.
{22803}{22848}Nikdy jsi nic takového neøekl!
{22848}{22877}Hej, Alberte.
{22877}{22965}Pamatuješ si, kdy jsme sem všichni pøijeli na vılet?
{22996}{23006}Jo...
{23047}{23085}Byl to jen další den.
{23085}{23142}Vypadá to jako vzpomínka ze vzdálené minulosti.
{23156}{23229}Lotrinskı koláè, kterı s námi Valentina sdílela
{23229}{23264}chutnal jistì skvìle.
{23359}{23389}A-Alberte...
{23468}{23485}To nic...
{23485}{23553}Jen jsem si na to vzpomìl, to je všechno.
{23620}{23663}Franz je šastlivec.
{23693}{23746}Vdycky bude v tvé mysli.
{23816}{23896}Jen stroje mi teï mohou zhojit stdce!
{23984}{23997}Renaude...
{24041}{24054}No,
{24054}{24091}pojeïme zpátky a najezme se.
{24177}{24192}Jo.
{24325}{24361}Hej, Michéle.
{24375}{24420}Rozprodání se zvyšuje kadou minutu!
{24420}{24448}Co to dìláš?
{24448}{24508}Vykoupila jsem tolik, kolik jsem mohla|nahradit, ale nemùu je udrovat.
{24508}{24569}Pøihoï tolik penìz, kolik je moné!
{24569}{24686}Nicménì, nejsou to jen akcie z naší|banky a našich partnerù, které krachují.
{24716}{24784}Akcie všech našich investicí krachují.
{24803}{24842}Co se to dìje?
{24842}{24899}Nejsem schopna zjistit pøíèinu.
{24916}{24964}Neschopná zjištìní?
{25002}{25037}Hej, dìlej svou práci!
{25037}{25096}Jestli  to bude pokraèovat, zbankrotuju!
{25096}{25196}V souèasné dobì postihl systém neznámı virus...
{25196}{25228}Hej, Michéle...
{25262}{25310}Akcie trhu Vıchodního vesmíru byly taky otevøeny!
{25310}{25348}Evakuuj naše akcie!
{25348}{25390}Prodej všechno, kromì akcií naší banky!
{25390}{25426}Zmìò všechno na hotovost!
{25426}{25485}Dnes je poèasí v Paøíi sluneèné,
{25485}{25502}sluneèné.
{25502}{25542}Teplota okolo 22 stupòù Celsia. Sluneèno.
{25542}{25605}Šance sráek je 10%. Sluneèno.
{25605}{25639}Bude pøíjemnı den. Sluneèno.
{25639}{25668}Dej se dohromady, Michéle!
{25668}{25683}Michéle!
{25683}{25694}Sluneèno.
{25694}{25745}Akcie trhu Vıchodního vesmíru...|/Sluneèno./
{25745}{25756}Sluneèno.
{25756}{25837}Dnes je Paøískı trh s akciemi zavøen|s nišími cenami, ne pøedevèírem.
{25837}{25872}Michéle, rychle s tím nìco udìlej!
{25883}{25896}Sluneèno.
{25883}{25935}Vzhledem k úèinkùm náhlého rozprodání|akcíí Danglars Group...
{25935}{25970}Sám se nemùu udret!
{25999}{26034}Michéle...
{26034}{26054}Sluneèno.
{26054}{26069}Sluneèno.
{26069}{26084}Sluneèno.
{26084}{26124}Michéle!|/Sluneèno./
{26188}{26201}Sluneèno. Sluneèno. Sluneèno.
{26201}{26249}Michéle!
{26398}{26423}Otèe...!
{26444}{26496}Co se dìje? Najednou sem takhle pøijít...
{26617}{26666}Ah, Eugénie,
{26666}{26708}má milovaná dcero.
{26708}{26772}Nìco ti øeknu.
{26772}{26794}Nìco mi øekneš?
{26794}{26846}Ano, nìco skvìlého.
{26865}{26994}No, bylo rozhodnuto, e tvá svatba |s Andreou se bude konat pozítøí.
{27040}{27060}Proè?!
{27060}{27083}Øekla jsem ti!
{27083}{27144}Nemùu to udìlat tak brzo po Franzovì smrti!
{27144}{27169}To je v poøádku.
{27169}{27188}Otèe-
{27188}{27207}Ticho!
{27239}{27296}Øíkáš, e se nestaráš o to, jestli já,
{27296}{27397}ne, jestli celá rodina zemøe u silnice|kvùli tvému sobectví?!
{27397}{27440}Otèe, prosím uklidni se-
{27440}{27472}"Uklidnit se"?!
{27472}{27505}Nepouèuj mì!
{27521}{27554}Mé akcie byly potopeny!
{27554}{27611}Moje bohatství je jako kousky papíru!
{27611}{27684}Jsou to bezcenné šmejdy jako tenhle klavír!
{27737}{27768}To nemùe bıt...
{27768}{27849}Jsi jediná, kdo nás všechny mùe zachránit.
{27849}{27927}Okamitì si vezmi Andreu!
{27947}{27968}A co...
{27968}{27999}mé pocity?
{27999}{28028}Kdo se stará?
{28028}{28121}Pokud se mé peníze vrátí, nestarám se.
{28207}{28318}S tímhle bude všechno Andreovo bohatství moje.
{28337}{28368}Eugénie...
{28368}{28466}Nyní jsi mému srdci nejdraší.
{28828}{28898}Franz je blízko nás.
{28926}{28968}To si myslím.
{28994}{29084}Myslím, e nám øíká, kterou cestou se máme vydat.
{29373}{29391}Renaude...
{29776}{29806}Kam jdete
{29806}{29855}tak pozdì v noci?
{30155}{30173}Ne!
{30173}{30204}Nech toho!
{30204}{30248}Pus mì!
{30279}{30293}NE!
{30435}{30477}NE!!!
{30526}{30561}I dcera aristokrata
{30572}{30649}bude znièena, jestli se jí nìco takového stane.
{30649}{30678}Nesouhlasíš?
{30753}{30833}Pozítøí, budeš moje.
{30851}{30939}Hlavní chod bude muset bıt do té  doby zrušen, huh?!
{31043}{31067}Alberte...
{31067}{31101}zachraò mì!
{31162}{31189}Alberte!
{31470}{31526}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31545}{31589}www.mycolorfullife.blog.cz
