{1}{1}23.976
{69}{158}TaSHee's Gang uvádí
{296}{395}GANKUTSUOU
{2450}{2514}Dobrı veèer, dámy a pánové.
{2531}{2599}Ti, kteøí zfalšovali svùj osud. |Ti, kteøí ve svém osudu zakopávali.
{2610}{2720}Èas kadého nadešel vyrovnanì a nutí je, aby si zvolili budoucnost.
{2742}{2812}Kdy byl svìøen poslední dopis, kterı mladík èetl,
{2833}{2916}tak co pøineseme do budoucna...
{2986}{3025}PRAVÉ JÁ ARISTOKRATA
{3095}{3115}Hrabì!
{3115}{3198}Musím s vámi o nìèem mluvit!
{3198}{3218}Hrabì!
{3341}{3364}Znamená to...
{3365}{3397}e u opustil Paøí?
{3665}{3741}Jako protihodnota akcií Danglars Bank, které nadále klesají,
{3741}{3818}bankovní klienti spìchají k vıplatním|okınkùm, aby vyzvedli své peníze.
{3836}{3932}V této chvíli, je místo pobytu manaerského|tımu, vèetnì pana Danglarse, neznámé-
{3932}{3974}Hlupáci!
{3974}{4036}Vaše nejdraší poklady jsou právì tady.
{4054}{4121}Všechno obrátím v zisk.
{4142}{4209}Dokud mám kapitál, jsem štvanec.
{4250}{4311}Kdybych mìl pìt milionù frankù, mohl bych obchod teoreticky zachránit.
{4311}{4367}No, které akcie mùeme pouít?
{4383}{4394}Sakra.
{4394}{4460}Je to tak nepohodlné, kdy nemám Michéle.
{4581}{4652}Dobrı den, pane Danglars.
{4666}{4715}Hrabì Monte Christo.
{4811}{4917}Tento zvláštní let je náhodou rezervován...
{4917}{4968}Pøijel jsem z Paøíe
{4968}{5008}v honbì za vámi.
{5008}{5055}O-Oh, to je-
{5055}{5132}Rád bych poprosil o pùjèku.
{5132}{5195}Pìt milionù frankù, v hotovosti, okamitì.
{5195}{5241}P-Pìt milionù frankù?!
{5278}{5314}Tato smlouva
{5314}{5410}vıslovnì prohlašuje, e neexistuje ádná horní hranice vıše úvìru.
{5410}{5442}Zapomnìl jste?
{5442}{5487}Oh, vùbec ne.
{5487}{5543}Nezapomnìl jsem, ale...
{5543}{5577}Problematické.
{5577}{5647}Bohuel, nemám takové mnoství|s sebou, kdy cestuju...
{5657}{5714}To nemáte tu penìní èástku v tom kuføíku?
{5715}{5732}To je-
{5732}{5776}No, prosím puste ho.
{5776}{5806}Ne.
{5806}{5835}To je trochu...
{5842}{5867}Teï.
{5919}{5934}Teï.
{5962}{5980}Teï!
{6091}{6169}Nemusel byste zemøít, kdybyste v klidu odešel.
{6169}{6197}Idiote.
{6224}{6273}Musím s ním nìco udìlat.
{6526}{6563}T-Ty  bastarde.
{6688}{6741}Jsi neèestnı jako vdy.
{6767}{6824}Vùbec jsi se nezmìnil.
{6844}{6876}Proè jsi...?
{6876}{6938}Podívej se dobøe na mou tváø.
{6956}{6982}Vzpomeò si.
{7005}{7058}Vzpomeò si na tváø mue,
{7058}{7136}kterého jsi pøed dvaceti pìti lety pohøbil do temnoty.
{7136}{7241}Tváø tvého pøítele, kterı jsi odsoudil k høíchu
{7254}{7290}falšenım obvinìním!
{7330}{7400}E-E-Edmond
{7400}{7445}Dantés!
{7488}{7504}Edmonde...
{7543}{7580}Spoléhám na tebe.
{7593}{7670}Další kapitán... budeš ty.
{7712}{7724}Rozumím.
{7831}{7876}Volal jste, zástupce kapitána?
{7876}{7907}Ah, Danglarsi...
{7907}{7989}Èísla neodpovídají údajùm v obchodních knihách.
{8005}{8142}T-To bylo, kdy jsme zastavili v pøístavu v Alpha Centauri minulı mìsíc-|/Poslouchej mì!/
{8142}{8183}To je zpronevìøování!
{8214}{8257}Tentokrát to nechám bıt,
{8257}{8300}ale jestli tì ještì jednou chytnu...!
{8395}{8477}Aaah, u jedná jako kapitán?
{8506}{8564}Na zdraví našemu Edmondovi!
{8564}{8651}Jsem si jistı, e i Mercédés je do nìj blázen!
{8651}{8727}Ostatní mui honící se za ní, jsou jako odpadky!
{8727}{8758}Odpadky jsem øekl!
{8788}{8889}Zásnubní veèírek  Edmonda a Mercédés|se koneènì uskuteèní pøíští tıden, huh.
{8889}{8914}Šastlivec!
{8940}{9019}Modlím se za jejich štìstí!
{9019}{9066}Velkı...
{9066}{9119}šastlivec...
{9148}{9215}Nikdo není perfektní.
{9234}{9272}Není to tak, Fernande?
{9296}{9373}Kadı má slabost nebo dvì,
{9383}{9434}nemyslíš? Huh?
{9434}{9474}Co tím myslíš?
{9491}{9607}Kdy kapitál Leclére zemøel, dal Edmondovi dopis.
{9627}{9673}Co myslíš, e v nìm bylo?
{9691}{9779}Slyšel jsem, e obsahuje utajované dokumenty |urèené disidentùm v Paøíi.
{9801}{9862}Pìknì zajímavé, ne?
{9887}{9993}Kdy øekneme, "Promiòte, vaše velièenstvo", a oznámíme|králi, co myslíš, e se stane s Edmondem?
{10079}{10091}Edmonde!
{10108}{10132}Edmonde!
{10132}{10166}Mercédés!
{10166}{10208}To musí bıt nìjaké nedorozumìní!
{10208}{10265}Neboj!
{10323}{10369}J-Jsi naivu?
{10431}{10491}T-To jistì pøináší zpìt vzpomínky...
{10508}{10557}o našem ivotì na Pharaon...
{10570}{10667}Cestovali jsme moøem hvìzd spoleènì a...
{10879}{10914}Co po mì chceš?
{10953}{11024}Jestli si myslíš, e jsem to na tebe nalíèil,
{11024}{11067}tak je to nedorozumìní.
{11067}{11141}Všechno udìlal Fernand, protoe chtìl tu enu.
{11141}{11217}Já se jen zmínil, protoe on byl tak deprimovanı,
{11217}{11327}e, kdy oznámíme ten dopis, mohlo by to bıt zajímavé.
{11327}{11376}Byl to jen vtip!
{11578}{11638}Poslal jsi nevinného mladíka do vìzení
{11638}{11718}kvùli árlivosti a nevhodné zášti.
{11718}{11755}Ne?
{11788}{11807}Ne!
{11825}{11859}Tak to nebylo!
{11859}{11898}Byl jsi...
{11898}{11985}mi na obtí!
{11985}{12026}Otravoval jsi mì!
{12026}{12071}Neexistoval ádnı dùvod!
{12071}{12204}Jen jsem se chtìl, aby mi Edmond Dantés zmizel z oèí!
{12385}{12418}To je...?
{12450}{12472}To je úasné.
{12472}{12503}Úasné!
{12503}{12552}Pøijímám tvou upøímnost.
{12552}{12642}To je mùj skromnı zpùsob, jak ti všechno splatit.
{12788}{12807}Poèkej!
{12821}{12852}Prosím poèkej, Edmonde!
{12879}{12906}Raduj se.
{12922}{12972}Všechno, èeho se dotkneš,
{12972}{13019}se stane ryzím zlatem.
{13019}{13055}Hej, poèkej!
{13206}{13228}Teï...
{13565}{13580}Hej!
{13580}{13616}Hej, nenchávej mì tady!
{13640}{13666}Prosím!
{13666}{13755}Prosím poèkej!
{14008}{14042}Jeden padl.
{14261}{14317}Nespi na takovém místì.
{14346}{14368}Kde je Hrabì?
{14368}{14410}Ty celou dobu èekáš?
{14410}{14471}Ale, ale. To pro tebe muselo bıt tìké.
{14471}{14511}Nedìlej si ze mì srandu! Já-
{14511}{14610}"Musím s Hrabìtem o nìèem mluvit",  e?
{14630}{14646}Sklapni!
{14646}{14695}Nemá to co dìlat se sluhou jako jsi ty!
{14695}{14724}Oh?
{14724}{14823}A to jsem ti chtìl øíct, kde je Hrabì.
{14850}{14905}Nedívej se tak.
{14918}{14952}Hrabì je ve vesmíru.
{14952}{15009}Touto dobou, Danglars-
{15009}{15032}To nemùe bıt.
{15032}{15113}No, nemùeš s tím nic udìlat,
{15113}{15154}nehledì na to, jak moc bojuješ-
{15154}{15215}Ty! Jsi pravá ruka hrabìte, ne?
{15215}{15235}Proè?
{15235}{15283}Proè ho nezastavíš?!
{15283}{15362}Proè nerozumíš pravım pocitùm Hrabìte?!
{15362}{15390}Proè?!
{15390}{15454}Nemluv jako bys vìdìl, o co jde!
{15454}{15495}Nemùeš rozumìt, jak se cítí?
{15495}{15563}Pøes to všechno musí vykonat svou pomstu.
{15563}{15668}Pøes to všechno nemùe zapomenout na minulost!
{15701}{15754}Já stále...
{15754}{15782}Já...
{15782}{15844}chci Hrabìti nìco øíct,
{15844}{15894}bez ohledu na to, ne všechno ztratí!
{15954}{16050}Slyšel jsem, e zítra se bude konat první slyšení Villeforta.
{16050}{16067}Coe?
{16067}{16133}No, pro malé kluky je èas jít do postele.
{16133}{16157}Teï jdi domù.
{16316}{16339}Hrabì...
{16361}{16466}Moná je strašlivìjší, ne si myslíte.
{16645}{16696}Nyní zaèneme soud v pøípadì otrávení jedem
{16696}{16830}v sídle Villefortù a následnı pokus|o vradu Hrabìte Monte Christa.
{16891}{16936}Nejdøíve, rád bych pøipomenul,
{16936}{17003}e jsem všechno udìlal pro ochranu mıch vlastních zájmù.
{17003}{17087}Bylo to pro ochranu poøádku a míru Paøíe.
{17087}{17139}V tomto pøípadì tvrdím, e jsem nevinen
{17139}{17229}a budu sám sebe hájit bez studu.
{17305}{17339}Nemùeš vstoupit bez povolení!
{17339}{17364}Jdi domù!
{17390}{17448}Lidé ukazují, e se Héloise, druhá ena obalovaného,
{17448}{17525}pokusila otrávit svou nevlastní dceru Valentinu,
{17525}{17573}aby získala její dìdictví.
{17592}{17716}Pan Villefort byl obvinìn Hrabìtem Monte |Christem a pokusil se ho zabít.
{17738}{17777}Toto nebylo jednání lásky ke své manelce,
{17777}{17841}ale sebezachování, aby si udrel pozici Nejvyšího soudce-
{17841}{17858}Jaká uráka!
{17874}{17976}Hrabì Monte Christo je zdroj neklidu v Paøíi.
{17976}{18040}Eventuélnì, by mohl bıt špión Impéria.
{18118}{18190}Øekl jsem to jako úøedník loajální ke svım odpovìdnostem.
{18190}{18257}Poaduji okamité zatèení Hrabìte Monte Christa!
{18360}{18398}Zajímá mì, jestli je to opravdu proces.
{18398}{18421}Co jste to øekl?!
{18421}{18472}Rád bych pøivolal svìdka,
{18472}{18533}kterı má spojení s minulostí obalovaného.
{18724}{18749}Klid!
{18749}{18785}Kdo je svìdkem?
{18805}{18861}Andrea Cavalcanti, Vaše Ctihodnosti.
{18894}{18931}Nicménì, to je jméno, které pouívám.
{18931}{18992}Svìdek odpovídá na otázky vánì.
{19023}{19096}V sirotèinci jsem se jmenoval "Benedetto" .
{19096}{19159}Ale nevím své pravé jméno.
{19159}{19236}Zdá se, e jsi veøejnosti znám
{19236}{19287}jako hlava zachovalého domu aristokratù.
{19287}{19325}Pøestaòte s tím, prosím.
{19325}{19378}Nejsem aristokrat ani nic takového.
{19378}{19425}Byl jsem opuštìnı jako malé dítì,
{19425}{19466}vyrostl jsem v sirotèinci
{19466}{19528}a kdy jsem odešel, udìlal jsem všelicos:
{19544}{19571}kráde,
{19571}{19595}háøství
{19595}{19638}i vrada.
{19659}{19727}A jakı je tvùj vıznam v tomto procesu?
{19748}{19781}Je to dùleitı vıznam.
{19781}{19860}Pøišel jsem odhalit tajemství za mım narozením.
{19860}{19894}Nìdìlej si srandu!
{19894}{19932}Klid!
{19932}{19976}Pokraèuj ve svìdectví.
{19999}{20050}Narodil jsem se v Auteuil,
{20050}{20144}co je teï vila Hrabìte Monte Christa.
{20184}{20241}Byl jsem pohøben ve chvíli, kdy jsem se narodil,
{20257}{20301}umístìn uvnitø malé rakve.
{20365}{20434}Otec musel panikaøit.
{20434}{20498}Pro soudce není pøípustné, s celou jeho stanovenou budoucností,
{20498}{20586}mít milenku, která porodí jeho dítì.
{20601}{20678}Tak skryl matku v domì v Auteuil, a-
{20678}{20697}Vaše Ctihodnosti.
{20708}{20749}Proè to dnes neoroèíme?
{20749}{20801}Obalovanı by se mìl krotit.
{20842}{20910}Jsi jen zloèinec, kterého si nìkdo najal!
{20910}{20946}Kdo tì najal?
{20946}{20993}Urálivé.
{20993}{21044}Nakonec jsme byli spojeni po sedmnácti letech.
{21044}{21157}Pøedkládáme vısledky analızy DNA obalovaného|a svìdka, stejne jako další dùkaz.
{21467}{21485}A to je?
{21485}{21520}Rakev.
{21520}{21619}Místo kolébky mi rodièe dali rakev-
{21619}{21647}Prosím pøestaò!
{21697}{21737}ádám tì, prosím pøestaò...
{21737}{21783}Dobré naèasování.
{21783}{21827}Nechte mì pøedstavit mou matku:
{21840}{21899}madam Victoria Danglars.
{21964}{22005}Není to pravda, matko?
{22018}{22073}Otec mì nacpal do tého skøíòky
{22073}{22123}a zahrabal mì v zahradì sídla, správnì?
{22539}{22557}Ah, mùj synu...
{22557}{22600}mé dìátko...
{22754}{22778}Prosím odpust mi.
{22778}{22815}Prosím odpust matce!
{22815}{22836}Ticho!
{22836}{22861}Buïte ticho!
{22861}{22905}Je pomatená!
{22905}{22937}Otèe,
{22937}{22977}neøíkej o matce takové špatné vìci.
{22977}{23019}Takové smutné vìci...
{23038}{23059}To je on.
{23059}{23105}To udìlal on, e?!
{23151}{23180}Vaše Ctihodnosti.
{23180}{23240}on udìlal tohle všechno!
{23240}{23265}Mám pravdu, ne?
{23265}{23343}Dítì zemøelo v zemi.
{23354}{23393}Není ádnı zpùsob, jak by tady mohl odhalit-
{23412}{23483}Vaše Ctihodnosti, prosím zaznamenejte toto prohlášení.
{23483}{23505}Ne!
{23505}{23552}Já jen-|/Klid./
{23552}{23570}Prosím posluchejte,
{23570}{23606}to je past.
{23606}{23654}Ty špinavı podvodníku!
{23838}{23949}To je kousek obleèení, kterı zanechal sluha, kterı mi zachránil ivot.
{23964}{24048}Sluha mì do toho pravdìpodobnì zabalil,|abych nemohl umrznout.
{24073}{24155}Bylo to mım pokladem po dlouhou dobu,
{24167}{24187}protoe...
{24202}{24250}to byla jediná vìc...
{24271}{24323}která mì s tebou spojovala, otèe.
{24388}{24444}Ty jsi... opravdu...
{24479}{24510}Promiò, otèe.
{24536}{24567}Kdybych neudìlal nìco takového,
{24567}{24654}nikdy bys nepøijal to, e jsem opravdu tvùj syn, e?
{24702}{24732}Chtìl jsem tì poznat,
{24751}{24771}otèe.
{24922}{24948}Sbohem.
{25022}{25047}Proè...
{25047}{25074}Proè?
{25205}{25240}Sklapnìte!
{25240}{25336}Jen ze zírání na vaše povıšené tváøe se mi dìlá špatnì!
{25346}{25428}Nakonec, vy všichni jste zvíøata jako on a já, ne?!
{25453}{25480}Pod tìmi pìknımi maskami,
{25480}{25530}skrıváte vaše pravé oplzné já!
{25530}{25625}Ty, ty a ty!
{25898}{26011}Vìøím, e zde dávno nìkdo jménem Dantés il.
{26011}{26058}Nevím.
{26058}{26123}Toto místo u je hodnì dlouho prázdné.
{26346}{26367}Edmonde...
{26530}{26557}Mercédés,
{26589}{26644}jsi stále mladá.
{26644}{26678}Já...
{26678}{26778}mám pocit jako by se nikdy nevrátil.
{26793}{26917}Nemùeš se starat o vetchého, starého mue jako jsem já, navdy.
{26931}{26964}Teï, jdi.
{26987}{27046}Tvé léto bude konèit.
{27046}{27072}Ne...
{27072}{27095}Ne!
{27095}{27160}Nevrátí se...
{27323}{27353}T-Ty bastarde...
{27371}{27431}Jak se vám daøí?
{27447}{27455}Kdo jsi?
{27501}{27551}Proè jsi...
{27551}{27607}Zapomìl jsi?
{27627}{27668}Pøed dvaceti pìti lety,
{27668}{27742}kdy jsi byl okresní soudce v Marseille,
{27765}{27831}odsoudil jsi nevinného mue za zloèin.
{27883}{27963}Jakmile jsi našel své vlastní jméno v dopise,
{27975}{28085}rozhodl jsi tajnì odstranit toho mue.
{28104}{28151}Edmond Dantés!
{28165}{28209}Jsi to opravdu ty?
{28225}{28288}Mu, kterému bylo kdysi takto øíkáno
{28288}{28364}zemøel ve vìzení Chateau d'if
{28364}{28431}a znovuzrodil se jako Gankutsuou.
{28485}{28590}Dopis, kterı jsi mìl, byl hodnì nebezpeènı!
{28590}{28624}Kdybych tì nechal jít samotného,
{28624}{28687}vláda by padla do naprostého chaosu!
{28687}{28730}Nemìl jsem na vıbìr!
{28730}{28815}Jsi opravdu vlastenec, lorde Villeforte.
{28815}{28935}Nicménì, dokáeš se opravdu ochránit?
{28981}{29035}Bylo to pro právo a øád!
{29035}{29121}Tvùj souèasnı stav je vısledek toho úspìchu.
{29175}{29209}Jak prázdnı.
{29228}{29317}Mimochodem, byl v tom jed.
{29328}{29347}Coe?
{29347}{29387}Jed je laskavost.
{29387}{29463}Bude ti hnít mozek
{29463}{29553}a propustí tì do svìta, kde nemùe dosáhnout odsouzení.
{29553}{29591}P-Poèkej!
{29607}{29624}Ne.
{29653}{29670}Ne!
{29670}{29758}Villefort, ubohı sluha zákona...
{29758}{29808}Køídla zákona
{29808}{29891}tì budou jemnì ochraòovat a do úplného konce.
{30043}{30096}Další padl.
{30303}{30321}Jdi.
{30438}{30476}Vıchodní flotila, ústup.
{30476}{30530}Chystáte se pøes hranice.
{30530}{30557}Varování.
{30557}{30634}To je porušení vojenskıch-
{31456}{31497}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31527}{31568}www.mycolorfullife.blog.cz
