{1}{1}23.976
{266}{396}U je to pùl roku, co dùm na okraji Rhysu, zvanı Sunlit Mansion...
{396}{432}zmizel v ohni.
{480}{601}Zatímco se oheò šíøil, do Sunlit Mansion vnikla spousta Thanatosù.
{622}{665}A rozšíøili se po celé Arcadii.
{794}{873}Náboenská organizace Silver Tree Knights bojovala |se všemi, s kterımi mohla, ale...
{898}{990}Nebyl ádnı zpùsob, jak pøekonat ohromnı nárùst Thanatosù.
{1079}{1161}U pùl roku jsme nezahlédli slunce...
{1161}{1184}A...
{1184}{1217}Bernarde!
{1296}{1318}Roche!
{1318}{1342}Trvalo ti to dlouho.
{1342}{1357}Promiò!
{1357}{1406}Ale mám dobrou informaci.
{1406}{1419}Jskou?
{1453}{1548}Øíkali, e to byl mladı mu, kdo znièil Thanatose ve vesnici cestou k øece.
{1548}{1584}Avšak je to jen z doslechu.
{1650}{1736}Nemáme jinou volbu, chytneme se i malého vodítka.
{1736}{1753}Jo!
{1947}{1971}To se jí podobá...
{1985}{1997}Ano...
{2036}{2110}Ange, kde právì teï jsi?
{2266}{2418}TaSHee's Gang uvádí
{2579}{2662}NEO ANGELIQUE ABYSS|SECOND AGE
{4651}{4722}ZTRACENÉ SVÌTLO
{4828}{4903}V poslední dobì byl neklid v Arcadii intenzivní.
{4923}{4989}Není ádnı konec, kterı lidé poadují.
{5010}{5103}Queen's Egg je stále nezvìstná.
{5103}{5222}Tudí musíme urychlit korunovaci pravého Head Order.
{5222}{5374}Pro tebe to znamená, e musíš jednat|se všemi, kteøí uzavírají tuto pasá.
{5429}{5445}Je to jasné?
{6212}{6249}Jak krásné je tohle místo...
{6284}{6328}Ode dneška tu budu ít!
{6436}{6472}Pøišel jsi sem znovu?
{6484}{6548}Máš to tu opravdu rád, Matsiasi?
{6548}{6616}Protoe odsud mùu vidìt nejkrásnìjší pohled na Holy Capital.
{6628}{6668}Namáhavì se mi dıchá.
{6668}{6697}Proè?
{6697}{6770}Protoe nikdy nemùu opustit tohle místo.
{6791}{6873}Protoe jsem sem pøišel, abych si uvìdomil, e jsem pták v kleci.
{6888}{6948}Nejsi pták v kleci.
{6960}{7052}Celestizam je základní ochranou Arcadie.
{7052}{7102}A centrem toho jsi ty.
{7151}{7222}Proè jsem to já a ne ty?
{7283}{7341}Já vím. Udìlám, co bych mìl pravdìpodobnì udìlat.
{7341}{7389}Nakonec, je to moje povinnost.
{7421}{7478}Chci tì následovat dokud budeš na mé stranì.
{7555}{7641}Ale bude to Královna, která zachrání Arcadii,  ne já.
{7654}{7773}Nepochybuješ o tom, e ta dívka je Queen's Egg?
{7773}{7855}Nejsme si úplnì jisti, jestli ije nebo ne.
{7877}{7941}Proè si myslíš, e hledám Angelique?
{7985}{8010}Nevím.
{8027}{8076}Protoe je skuteèná.
{8095}{8167}Angelique je bezpochyby Queen's Egg.
{8187}{8258}Vdy stále ije a pøijde jistì sem do Holy Capital.
{8258}{8322}V den, kterı si vybere.
{8339}{8377}Není nic, co bych mohl udìlat.
{8398}{8509}Øíkáš, protoe je skuteèná?
{8648}{8700}Bıvalé umístìní Sunlit Mansion je na druhé stranì.
{8700}{8816}Zdá se, e se Thanatosové rojí okolo umístìní Sunlit Mansion!
{8848}{8981}Pøed pùl rokem, to, e se zvıšil poèet Thanatosù, |byla chyba Artifact Foundation...
{9002}{9088}ovšem, znièili je Orb Hunters.
{9173}{9241}Lidé ili v míru jen krátkı èas.
{9270}{9313}Nicménì, hned ten veèer...
{9428}{9494}Místo, kde ili, nazıvané Sunlit Mansion bylo záhadnì znièeno poárem.
{9514}{9581}Orb Hunters zmizeli...
{9581}{9713}a Thanatosové se rozšíøili znovu zpìt hned, jak Sunlit Mansion shoøelo.
{9751}{9863}Lidé se jednostrannì rozhodli, e Orb Hunters |byli zodpovìdní za zjevení Thanatosù.
{9900}{9995}U je pùl roku po tom... a my poøád nevíme, kde jsou...
{10007}{10034}Moná, e jsou...
{10034}{10055}Pøestaò!
{10055}{10104}Chci tomu taky vìøit, však víš!
{10195}{10276}Pojïme prozkoumat toho mladého  mue, kterı oèistil Thanatose.
{10323}{10341}Dobøe.
{10453}{10470}Prosím!
{10491}{10540}Prosím vezmìte nás za Head Order!
{10540}{10611}Chceme se ho zeptat, jestli se za nás modlí!
{10629}{10727}Head Order nemùe splnit všechny tyto nepozorné poadavky!
{10922}{10931}Zastavte!
{10943}{10974}Nemùete tudy projít!
{11023}{11101}Odstraò všechny pøekáky.
{11101}{11133}Rozumím.
{11133}{11164}Všechny je rozdrtím.
{11508}{11530}Zastavte!
{11530}{11564}Pokraèuj, Jete.
{11606}{11632}Jdìte z cesty.
{11632}{11674}Nebo budete zranìni.
{11714}{11745}Co to je?
{11833}{11869}Je to nebezpeèné! Prosím, jdìte zpátky!
{12006}{12048}Head Order, pøedpokládám?
{12073}{12164}Jsem Erenfried, vìdec z Artifact Foundation.
{12164}{12220}Je tu nìco o èem bych s vámi rád mluvil.
{12267}{12359}A vìøím, e je to nìco prospìšného pro Církevní Organizaci.
{12368}{12410}Co jsi to øekl, ty domıšlivá kryso?!
{12435}{12471}Rozumím.
{12471}{12514}Mathiasi-sama!
{12514}{12540}Je mi to jedno.
{12540}{12610}Nicménì, zadrte tyto lidi.
{12746}{12765}Tudy.
{13284}{13304}Nikdo...
{13539}{13607}Vypadá to jako by všichni utekli a opustili vesnici.
{13607}{13626}Ano.
{13626}{13735}Nemùeme potvrdit zdali zde ten mladı mu znièil Thanatose nebo ne.
{13822}{13850}Povìz, Bernarde...
{13873}{13939}Je nìjaká dívka, kterou máš rád?
{13940}{13978}Proè taková otázka?
{13978}{14084}Nezáleí na tom, jak moc pracujeme, stejnì nevíme, co se zítra stane.
{14096}{14164}Peníze a èest na svìtì nic neznamenají.
{14164}{14235}Takové øeèi se ti nepodobají.
{14250}{14293}Nakonec je to láska!
{14293}{14392}Bıt s dívkou, kterou miluješ je skvìlé.
{14392}{14450}Nakonec jsem o tom vánì pøemıšlel.
{14450}{14501}Jsi zamilovanı do nìjaké dívky?
{14501}{14533}A co ty?
{14533}{14572}No, pochybuju o tom...
{14572}{14607}Nezkoušej to skrıvat
{14607}{14703}My, novináøi, se umíme jen ptát na otázky.
{14703}{14790}Ale kdy jsme dotazování, neumíme srozumitelnì odpovìdìt.
{14834}{14908}Není to odpovìï na tu otázku, ale...
{14908}{15000}jestlie se jednomu z nás nìco stane...
{15000}{15031}Jako co?
{15031}{15115}Není divné všechno, co se na svìtì stane?
{15115}{15140}Myslím...
{15179}{15253}Kdokoli odešel ji musí hledat...
{15253}{15320}A øíkat pravdu po celé Arcadii.
{15320}{15401}To je jediná vìc, kterou teï mùeme udìlat.
{15521}{15559}Tak pojïme rozhodnì hledat!
{15559}{15604}Je urèitì nìkde tady.
{15604}{15664}Byly nìkdy moje informace mylné?
{15677}{15707}Máš pravdu.
{15707}{15742}Urèitì ho musíme najít!
{15742}{15762}Ano!
{15967}{16047}Právì teï se Foundation rozpadá.
{16066}{16137}A ve skuteènosti se hroutí stejnì jako Organizace.
{16181}{16277}Nepotøebujete Organizaci dokud máte rozum.
{16283}{16346}Oh? Vy myslíte, e jste ten rozum?
{16379}{16405}Uzavøeme obchod.
{16423}{16538}Lidé jsou s rozumem v koncích, protoe se zvıšilo mnoství Thanatosù.
{16538}{16625}Drí se pevnì Organizace, aby odvedla jejich |pozornost od jejich nepokojnıch srdcí.
{16625}{16715}Nicménì toto je mez, kterou Silver Tree Knights nemùou pøekroèit.
{16715}{16797}Náš poslední paprsek nadìje, Queen's Egg je aktuálnì pohøešován.
{16811}{16906}Lidé si zanedlouho uvìdomí, e pouhá modlitba nic nezachrání.
{16920}{16972}A budou si zoufat vám.
{16988}{17081}Kdy se to stane, tak vaše Organizace ztratí vıznam.
{17104}{17220}Vyvinul jsem silnìjší Jinx, ne tu pøed pùl rokem.
{17234}{17289}Jestli se rozmístí po celé Arcadii,
{17289}{17347}mohli bychom znièit Thanatose jedním máchnutím.
{17362}{17462}Vyrobím tyto Jinx pro vaši Organizaci.
{17462}{17556}Jestlie mohu vyhladit Thanatose ve jménu vaší Organizace,
{17569}{17626}lidé budou pokraèovat ve vaší podpoøe.
{17663}{17743}Co chcete na oplátku?
{17761}{17839}Pomoci øediteli Yorgovi z Artifact Foundation.
{17839}{17892}Yorgo? Jestli se nemılím, je...
{17906}{17960}Spousta vesnic v Arcadii bylo znièeno.
{17973}{18042}Byl zatèen za obvinìní z rozšíøení Thanatosù.
{18042}{18082}V souèasné dobì je ve vazbì.
{18104}{18203}Je ve vazbì u pùl roku a je opravdu v nepøíznivé situaci.
{18204}{18272}V takové rychlosti je velká pravdìpodobnost, |e bude muset pøijmout velkı trest!
{18298}{18375}Prosím, zachraòte svou mocí øeditele Yorga!
{18375}{18435}Jestlie øeknete, e je nevinnı,
{18435}{18500}nenávist lidí vùèi Foundation se zmírní!
{18500}{18553}Øeditel bude zachránìn, jestlie se zmìní názor veøejnosti.
{18569}{18646}Head Order mùe zachránit øeditele!
{18662}{18704}Mùete to udìlat!
{18786}{18867}Musí si odèinit svùj høích.
{18900}{18944}Jestli je nevinnı èi ne...
{18963}{19033}nám øekne proces, ne?
{19135}{19154}Poèkejte!
{19200}{19285}Jinx jsou nebezpeèné.
{19285}{19325}U byste je nemìl pouívat, ano?
{19339}{19364}Head Order!
{19364}{19395}Prosím vás!
{19395}{19434}Prosím, zachraòte øeditele!
{19434}{19485}Head Order! Prosím vás!
{19485}{19510}Prosím, zachraòte...
{19552}{19613}Nemám tuto moc.
{19613}{19638}Jsem...
{19666}{19702}podvodník...
{20202}{20358}Od teï prosím veï naši organizaci jako Head Order.
{20603}{20754}Tyto knihy obsahují všechno od poèátku Arcadie.
{20793}{20879}Mìl by se's se nauèit zpamìti.
{20879}{20893}Všechny?
{20912}{21030}Ano. Musíš si je zapamatovat perfektnì podle linie.
{21046}{21099}To je nemoné. To nemùu zvládnout.
{21100}{21245}Byl jsi pozván do Holy Capital kvùli tvé mimoøádné pamìti.
{21262}{21371}U nechci slyšet, e to nezvládneš!
{21508}{21608}To je dùkaz, e jsi hlavou Celestizamské Organizace.
{21645}{21743}Prosím, staò se èlovìkem, kterı nepøivede na Silver Tree Knights hanbu.
{21868}{21907}Dokáu to.
{21907}{21964}Vdycky se budu chtít dívat na tuto scenérii...
{21964}{22025}take jsem koneènì Head Order!
{23126}{23148}Jsem hotov!
{23160}{23194}Zabralo to sedm let...
{23194}{23274}Sedm let, ale u je umím všechny nazpamì!
{23274}{23342}Koneènì se mùu stát Head Order!
{23485}{23520}Je to pravda?
{23520}{23534}Ano.
{23560}{23675}Øíkali, e našli narozené dítì svírající list z Great Silver Tree.
{23696}{23784}Oh! A co ta osoba dìlá teï?
{23784}{23899}U ije tøi roky se svou matkou.
{23899}{23964}Musíme ho ještì jednou vzít do Holy Capital!
{23964}{24116}Jestlie se narodil s listem z Great Silver Tree v ruce, musí bıt pravı Head Order!
{24116}{24182}Ale co udìláme s jeho pøedchùdcem?
{24182}{24230}S ním?
{24248}{24265}Ano.
{24265}{24387}Pøedchozí Head Order zemøel a my jsme nemohli najít novou osobu.
{24387}{24526}Take jsme ihned vzali dítì s mimoøádnou pamìtí, ale...
{24526}{24562}byli jsme pøíliš ukvapení.
{24595}{24731}Byl tady, aby zaplnil mezeru do té doby, ne se narodí pravı Head Order.
{24731}{24750}Pak...
{24750}{24823}Je stále ještì mladı.
{24823}{24887}Potøebuje ještì pøed svou korunovací èas.
{24887}{24976}Je tu nìkdo, kdo s ním mùe bıt a asistovat mu.
{24988}{25020}Aha.
{25020}{25101}Take, a vyroste a dostane trùn,
{25101}{25175}co udìláme s tím pøedešlım?
{25193}{25283}Do té doby u pro nás jistì nebude cennı.
{25636}{25725}Vzali jsme tì sem, aby se's staral o Reného-sama do jeho korunovace.
{26629}{26679}René u vyrostl.
{26679}{26727}Je ještì mladı, ale...
{26727}{26821}povede Církevní Organizaci a Arcadii.
{26821}{26864}U mì víc nepotøebuje.
{26916}{26952}Tiše se rozlouèím...
{26988}{27092}Uskuteèni své povinnosti dobøe, René.
{27410}{27433}Jak krásné...
{27457}{27562}Mám rád Holy Capital.
{27562}{27609}Víc ne cokoli na svìtì... Víc ne všechno...
{27641}{27681}Já... já...
{27828}{27906}Zajímá mì, pro co jsem se narodil.
{28377}{28425}Zùstanu tady.
{28521}{28617}Budu ít v tomhle mìstì navìky.
{28672}{28688}U není èas!
{28688}{28732}Musím nìco udìlat!
{28745}{28800}Podej mi papír a tuku, Jete.
{28854}{28912}Proè zacházíte tak daleko?
{28912}{29011}Nerozumím, proè to všechno pro Yorga dìláš.
{29011}{29047}"Rozumím", jsi øíkal?
{29047}{29102}Jak mùe artefakt jako ty rozumnìt?
{29102}{29120}Vypadni!
{29167}{29227}To je pravda. Jsem artefakt.
{29246}{29301}Artefakt jako já nemùe nièemu rozumìt.
{29436}{29454}Øediteli Yorgo!
{29564}{29605}Sakra! Ten je vytrvalı!
{29620}{29669}Budeme pokraèovat a se dìje, co se dìje!
{29688}{29706}He?
{29706}{29726}Bì!
{29740}{29803}Bude to konec, pokud tady umøeme!
{29803}{29872}Musíme øíct všem pravdu! Prosím, bì!
{29909}{29926}Sakra!
{30097}{30138}Bernarde!
{30405}{30420}To je...
{30502}{30534}Rayne-kun...
{30669}{30693}Vítej.
{30693}{30727}Trvalo ti to dlouho.
{30727}{30744}Co se stalo?
{31061}{31076}Ange!
{31130}{31152}Co to s vámi je?
{31152}{31202}Jestli je nakonec v poøádku, staèí jen øíct-!
{31301}{31316}Ona je...
{31316}{31350}Co?
{31460}{31567}Spí... Celıch šest mìsícù...
{31993}{32081}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32122}{32217}www.mycolorfullife.blog.cz
