{1}{1}23.976
{101}{174}Ange spí... u pùl roku.
{196}{228}To je nemoné!
{241}{271}ertuješ?
{369}{443}TaSHee's Gang uvádí
{717}{788}NEO ANGELIQUE ABYSS|SECOND AGE
{2776}{2841}NEOÈEKÁVANÁ MELODIE
{2955}{3003}Èert aby to vzal! Je..
{3046}{3092}Co se pøesnì stalo?!
{3092}{3128}Proè se jí tohle pøihodilo?!
{3233}{3269}Uklidni se!
{3269}{3353}Není správné je obviòovat, dokud neznáme pøíèinu!
{3442}{3470}Omlouvám se.
{3481}{3510}Vysvìtlete nám to.
{3586}{3638}To je Roche, mùj informátor.
{3650}{3688}Mùeme mu vìøit.
{3743}{3755}Aha.
{3790}{3881}Ještì teï stále nemohu uvìøit tomu, co se pøed pùl rokem stalo.
{3897}{3972}Ne... Mìl bych øíct, e tomu nechci vìøit.
{4016}{4106}Ne jsme si to uvìdomili, Sunlit Mansion byla zaplavena plameny.
{4124}{4243}Dostat Ange z nebezpeèí bylo na prvním místì.
{4334}{4400}Obrame se v prach s tímto domem!
{4424}{4486}Neøíkejte mi, e...
{4497}{4590}Dìlali jsme, co jsme mohli, abychom unikli ohni, ale...
{4611}{4698}Nemohli jsme zastavit ani zùstat, protoe| Thanatosové nepøestávali útoèit.
{4931}{4957}Ale jakmile...
{4957}{5064}jsme kráèeli podél zátoky, narazili jsme na tohle místo.
{5202}{5246}A od toho dne se Ange...
{5246}{5294}Tak tohle se stalo...
{5362}{5471}Musí bıt teï opravdu v šoku, protoe ji její pøítel zradil.
{5492}{5571}Nemùeš bıt tak slabá.
{5571}{5617}Honem! Probuï se!
{5664}{5681}Dobøe?
{5769}{5797}Je studená.
{5821}{5860}To je... To nemùe bıt...
{5887}{5994}Nicménì, nemùeme najít na jejím tìle ádnou nenormální reakci.
{5994}{6047}Ale kadı den s ní mluvíme...
{6099}{6168}Vìøím, e je to  kvùli emocionálním problémùm.
{6185}{6205}Depresivní!
{6226}{6340}S našimi omezenımi vìdomostmi s tím nemùeme nic udìlat.
{6365}{6412}Jakı je váš úmysl, e jste si mì vyádal?
{6434}{6482}Tvùj vztek je pochopitelnı.
{6482}{6537}Jen se ti chci omluvit za to, co se stalo pøed pár dny.
{6559}{6658}Take jste si mì vyádal, abyste se omluvil za to, co jste pøedtím øekl?
{6688}{6806}Vısledek soudu øeditele Yorga by mìl bıt brzy oznámen.
{6850}{6906}Take to musíme projednat.
{6906}{6969}Myslím, e pøijmu váš návrh, kterı jste mi pøedtím pøeloil.
{7014}{7077}Církevní Organizace øekne...
{7094}{7201}e øeditel Yorgo není zodpovìdnı za chaos v Arcadii.
{7218}{7243}Ale...
{7260}{7318}øíkal jste, e musí platit za své høíchy!
{7333}{7438}Samozøejmì, e musí. Nenabízím tohle pro nic, za nic.
{7552}{7564}To je...
{7594}{7669}Èip vyvynutı profesorem Raynem,
{7669}{7731}kterı vyuíval pracovník ve Foundation.
{7731}{7771}Mùe zesílit schopnosti Purifiera.
{7841}{7909}Jsem si jistı, e to víte. Prosím, vytvoøte pro mì jeden.
{7909}{7980}Na oplátku za podporu, kterou vám dáme.
{7980}{8048}Proè? Jak mùete mít nìco takového?
{8139}{8225}Našli jsme to v tìle Carlyla.
{8279}{8307}Prosím, podívejte se.
{8409}{8545}Kdy byl èip zkontrolovanı, dozvìdìli jsme se, |e ho nìjaká technologie Foundation zatavila.
{8592}{8643}To je všechno, co víte?
{8661}{8775}Ano, mùete mi ho vyrobit?
{8775}{8802}Nebo ne?
{9051}{9150}Proè ne! Ihned mi pøipravte laboratoø.
{9230}{9337}Upøímnì øeèeno, je opravdu tìké vám èelit.
{9359}{9439}Ruiny Sunlit Mansion se zaèínají stávat hnízdem Thanatosù.
{9464}{9626}Take lidé vìøí, e to byli Orb Hunters, kdo zamoøil Arcadii Thanatosi.
{9626}{9762}A kvùli Ange nemùeme nic dìlat jen se v souèasné dobì skrıvat.
{9777}{9845}Všechny dohady se toèí okolo málo dùleitıch detailù.
{9858}{9950}Jako, e Nyx ije s Thanatosi v ruinách Sunlit Mansion.
{9967}{10028}Zatracenì, všechny tyhle povídaèky jsou otravné.
{10063}{10077}Co?
{10089}{10242}Asi se nikdy nedozvíme, proè Sunlit Mansion zapálil.
{10254}{10328}Je pravda, e je to záhadnı mu...
{10329}{10352}Ano...
{10352}{10374}A vy?
{10389}{10501}Nevíte, proè to udìlal? Stále nemùu najít odpovìï.
{10521}{10567}Moná bychom ti nemìli øíkat proè.
{10577}{10644}Nezáleí na tom, kdo se stane nepøítelem Angelique...
{10665}{10690}I kdy je to Nyx...
{10722}{10747}Budu s ním bojovat se svım kopím.
{10777}{10862}A ho pøíštì potkáme, bude to náš nepøítel.
{11028}{11081}Mìli bychom se spíš starat o ni.
{11081}{11143}Mìli bychom tento problém vyøešit jako první.
{11171}{11266}Nemìli bychom zkušet Ange probudit za kadou cenu?
{11266}{11324}Budu od vás potøebovat podporu, lidi.
{11337}{11363}Jakou podporu?
{11395}{11475}Myslíš dùkladnou kontrolu Nyxe?
{11475}{11495}Ano.
{11495}{11581}On je klíèem k vyøešení tohoto problému.
{11581}{11692}Bìhem našeho prùzkumu moná najdeme zpùsob, jak Ange zachránit.
{11704}{11725}Aha.
{11753}{11770}To je opravdu skvìlé.
{11783}{11886}Udìláme, co bude v našich silách!
{11908}{12050}A se Ange probudí, svìt se opìt zaplní usmívajícími se tváøemi.
{12081}{12154}Máme schopnosti bojovat proti Thanatosùm...
{12154}{12212}Schopnosti, které také dokáou zachránit lidi!
{12212}{12273}Jsi tak horlivı , kdy o tom mluvíš!
{12273}{12365}Nechci bıt tím, co nic nedìlá.
{12365}{12388}Roche...
{12399}{12494}Je povinností mue, probudit Šipkovou Rùenku.
{12494}{12541}Je to osud.
{12571}{12652}Opravdu chceš bıt probuzena mımi teplımi rty?
{12652}{12769}Hej, nikdy ti neodpustím, jestli to udìláš!
{12786}{12854}To je dìsivé! Proè jsi tak vánı?
{12869}{12902}No, musím jít!
{13118}{13212}Prosím, vzbuï se brzy. Ange...
{13283}{13337}Dovolte mi, abych vám ukázal okolí.
{13443}{13465}Poèkejte.
{13485}{13506}Co ještì chcete?
{13531}{13567}To je váš podøízenı?
{13589}{13617}Mùj podøízenı?
{13617}{13671}Je to artefakt.
{13671}{13705}Mùj nástroj.
{13719}{13756}Artefakt?
{13805}{13910}Od teï je pod kontrolou Organizace.
{13910}{13981}Nechci tady vidìt ádné chaotické situace.
{14153}{14232}Od teï jsi strácem Head Order.
{14245}{14318}Je to váš pøíkaz?
{14343}{14357}Ano.
{14379}{14416}Dobøe, tak souhlasím.
{14416}{14475}Zmìním si program.
{14501}{14596}Program byl zmìnìn.
{14596}{14662}Mathiasi, Head Order z Celestizamu...
{14662}{14739}od teï pøijímám vaše rozkazy.
{16528}{16544}Stále si mi to nepodaøilo.
{16640}{16758}Profesore Rayne, plnì rozumím teorii a to je základ.
{16758}{16817}A pak, jakmile analyzuju materiál...
{16915}{16999}Jedinı kdo mùe zachránit øeditele Yorga... jsem já!
{17086}{17162}Toto je plán vızkumu, kterı jsi navrhnul pøed pár dny.
{17211}{17326}Myslím si, e by's mìl odloit èást penìz na další konferenci.
{17345}{17466}Ale to je zbyteèné... Pøijmu plán profesora Rayneho.
{17545}{17643}Øediteli Yorgo, mohl byste mi pomoct místo |toho s podporou profesora Rayna.
{17667}{17740}Já vás dva nesrovnávám.
{17762}{17866}Jako vìdec cítím, e tvùj nápad je proveditelnı.
{17888}{17919}Øediteli Yorgo...
{17962}{17989}Èekám od tebe hodnì.
{18008}{18024}Ano!
{18194}{18235}Jete. Podej mi papír a tuku!
{18562}{18622}Nic nebezpeèného se uvnitø neschovává.
{18622}{18666}Vracím ti tohle.
{18746}{18763}Omlouvám se.
{18957}{19070}Proè... se tyhle nesmyslné informace zkopírovaly do mé pamìti?
{19121}{19144}Co to dìláš?
{19144}{19216}Jste zranìnı.
{19257}{19320}Tyto informace jsou pro mou pamì bezcenné.
{19338}{19382}Je nesmyslné je skladovat.
{19405}{19483}Vy a J.D.-san jste bratøi, ne?
{19549}{19594}Co to je?
{19610}{19684}Proè se obraz té dívky znovu objevil?
{19727}{19761}Angelique...
{19775}{19872}Queen's Egg, vlastní zvláštní schopnosti.
{20458}{20482}Slunce...
{20503}{20536}Po pùl roce...
{20584}{20716}Tohle svìtlo mùe vrátit nadìji lidem, kteøí ji u ztratili.
{20824}{20901}U je to dlouho. Vdycky jsem tì chtìl vidìt.
{21414}{21431}To je nemoné!
{21469}{21512}Naše hlasy k ní koneènì dosáhly!
{21932}{21955}Vıborné!
{21972}{22086}Udìlal jsem toho hodnì, aby se ti vrátily síly.
{22086}{22172}Sakra, ty vdycky tak rychle reaguješ.
{22240}{22296}Ale je to úasné...
{22319}{22363}Cítíte nìkde na tìle bolest?
{22363}{22439}Ne! Je mi dobøe!
{22452}{22502}To proto, e jste byla pùl roku nehybná.
{22513}{22605}Take byste mìla pomalu cvièit chùzi.
{22701}{22800}Ze Sunlit Mansion jsou ruiny, e?
{23010}{23044}Aha...
{23044}{23120}Celı svìt je v nepoøádku.
{23134}{23254}Právì jsi se probudila. Teï od tebe nechceme slyšet nic takového.
{23271}{23352}Proè bych mìla dìlat?
{23367}{23455}Jste stále naplnìná svım posláním jako Queen's Egg.
{23464}{23539}Mìla byste se uklidnit a zamyslet se nad budoucností.
{23554}{23596}Teï si na chvíli odpoèiò.
{23611}{23695}Zajdu pro potøebné vìci a udìlám úasné jídlo.
{23695}{23708}Dobøe?
{23797}{23816}Dobøe!
{24053}{24142}Od té události u uplynulo pùl roku.
{24307}{24380}Nyxi-san... Proè jste to udìlal?
{24520}{24543}Ta melodie!
{24820}{24842}Tohle místo...
{24948}{24964}Támhle!
{26036}{26058}Proè?
{26124}{26210}Nyxi-san! Proè jste to udìlal?!
{26222}{26280}Aèkoli jste mì opustil se smutnou vzpomínkou.
{26306}{26364}Jsem šastná, e vás vidím!
{26364}{26416}Byl jste jedinı, kdo mi dával nadìji...
{26416}{26472}A pak jste ji rozšlapal a vzal ji pryè!
{26492}{26527}Jste krutı!
{26588}{26630}Koneènì jsem našla to místo...
{26642}{26723}Domov, kde se mùu vrátit...
{26745}{26822}Kde ijí spoleènì moji pøátelé a je naplnìno usmívajícími se tváøemi!
{26841}{26871}Sunlit Mansion!
{26925}{26992}Nebylo nic, co jsem mohla udìlat...
{27007}{27068}Kdy jsem ztratila svùj milovanı domov, nemohla jsem nic dìlat.
{27084}{27102}Nic...
{27330}{27360}Opravdu se omlouvám.
{27402}{27487}Musíš bıt stále lapena v hrozné prázdnotì.
{27505}{27611}Na prahu konce svìta...
{27628}{27691}Prosím, nenáviï mì...
{27691}{27788}Nenávist se stane schopností, která tì poene vpøed.
{27833}{27853}A taky...
{27872}{27914}Zabij mì.
{27955}{28037}Má existence ti pøinese nekoneèné neštìstí.
{28050}{28141}A nechci tì dìlat více nešastnou.
{28170}{28213}Tak prosím...
{28213}{28234}zabij mì...
{28401}{28419}Nyxi-san!
{28828}{28860}Ange!
{28992}{29013}Erwine...
{29063}{29152}Skvìlé! Ihned jsme tì probudili...
{29173}{29260}Nebyla jsi v posteli... Vydìsilo nás to!
{29275}{29314}Co se stalo, Angelique?
{29357}{29409}To nebyl... sen?
{29487}{29503}To je...
{29661}{29743}Aèkoli si nejsem jistá, co mìl ten sen znamenat,
{29760}{29843}Nyx-san chtìl mou pomoc!
{30026}{30046}Pane Nyxi..
{30161}{30200}Ange se probudila.
{30212}{30245}Myslíš to vánì?
{30245}{30292}Rychle, pøeèti to!
{30323}{30449}Mimochodem, kdy ètete tenhle dopis... Vyráíme na cestu.
{30466}{30625}Aèkoli si pøejeme, aby Ange ještì zùstala v chatì, aby nabrala síly...
{30639}{30723}Musíme odejít, jinak vesnièané objeví, e tu jsme.
{30754}{30820}Zùstat déle by mohlo pøinést Ange nebezpeèí.
{30838}{30906}Tak jsme se rozhodli jít na Holy Capital.
{30906}{30972}Církevní Organizace by nám mìla poskytnout ochranu.
{30972}{31015}Holy Capital?
{31027}{31079}Pojïme, Bernarde!
{31079}{31095}Ne...
{31095}{31184}Je nìco jiného, co musíme udìlat.
{31303}{31350}Ty jsi vdycky tak tvrdohlavı.
{31441}{31533}Pamatuj si, e s sebou musíš vzít dárek, kdy jdeš navštívit dívku!
{31779}{31797}Ange!
{31986}{32085}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32137}{32232}www.mycolorfullife.blog.cz
