{1}{1}23.976
{190}{208}Ten motıl...
{328}{363}Spirit Illusion Tower.
{513}{623}TaSHee's Gang uvádí
{855}{934}NEO ANGELIQUE ABYSS|SECOND AGE
{2912}{2989}SPIRIT ILLUSION TOWER
{3072}{3140}U jsme blízko Holy Capital.
{3140}{3212}Je to díky tomu, e jsme jeli pøes moøe.
{3386}{3414}Prší...
{3478}{3515}Nemám apetit, kdy je takové poèasí.
{3528}{3592}Thunder Village je opravdu zaslouilı název téhle vesnice.
{3623}{3658}Pùjdu si trochu odpoèinout.
{3730}{3755}Hyuugo-san...
{3998}{4022}Spirit Illusion Tower...
{4037}{4138}Duše zesnulıch mohou vstoupit do snù lidí ijících na tomto svìtì.
{4155}{4204}Carlyle... Ty jsi...
{4278}{4299}Angelique.
{4372}{4437}Ehm... Obávala jsem se...
{4463}{4586}A pøijdeme k Holy Capital, pùjdete s námi Hyuugo-san?
{4620}{4658}Mìl jsem vám to øíct døíve.
{4658}{4752}S mımi zranìními nemùu do Holy Capital vstoupit.
{4811}{4853}No, myslím si, e je èas jít spát.
{4867}{4893}Musíte bıt vyèerpaná, ne?
{4893}{4934}Hyuugo-san...
{4949}{5051}Nechcete mi øíct o všem, co vás obtìuje?
{5051}{5111}Jste mùj drahı pøítel.
{5129}{5253}Take chci sdílet vaše dojmy bez ohledu |na to jestli jsou šastné nebo smutné.
{5335}{5360}Angelique-sama.
{5402}{5478}Je mojí osobní volbou nikdy nevkroèit do Holy Capital.
{5489}{5538}Tak se tím prosím neznepokojujte.
{5657}{5682}Hyuugo-san...
{5820}{5892}Hyuuga-san je poøád takovı...
{6107}{6176}Kolem Spirit Illusion Tower se objevili Thanatosové...
{6176}{6193}Strašné!
{6214}{6241}Thanatosové...
{6241}{6337}Bylo by katastrofální, kdyby Thanatosové sešli do vesnice!
{6337}{6387}Pojïme hned do Spirit Illusion Tower.
{6406}{6417}Kde je Hyuuga-san?
{6427}{6529}Kdy jsem se probudil, tak nebyl ve své posteli.
{6529}{6564}Proè je kolem toho takovı rozruch?
{6585}{6653}Silver Tree Knights! Kolem Spirit Illusion Tower se objevili Thanatosové!
{6688}{6735}Co budeme dìlat, kdy pøijdou do vesnice?
{6735}{6796}Pánové Rytíøi, prosím pomozte nám!
{6796}{6819}Dione-san!
{6847}{6859}Vy jste...
{6913}{6959}Bylo by lepší, kdybychom nemluvili tak hlasitì.
{6975}{7030}To je dobrá zpráva, e jste naivu.
{7094}{7135}Nevidím Hyuugu...
{7147}{7254}Ano, odešel pøed námi.
{7268}{7333}Hyuuga-san se poslední dobou choval divnì.
{7405}{7436}Spirit Illusion Tower...
{7462}{7491}Carlyle...
{7509}{7545}Hyuugo! Neøíkej mi, e...
{7574}{7606}Jdu do Spirit Illusion Tower!
{7619}{7667}Vy... vy zùstaòte ve vesnici!
{7667}{7695}Rozumíme!
{7695}{7717}Dione-san!
{7747}{7793}Jdeme s vámi!
{7976}{7991}Carlyle.
{8016}{8040}Jsi to ty?
{8166}{8215}Øeknìte... Dione-san?
{8215}{8236}Copak je?
{8236}{8299}Co se stalo s Hyuugou-san ne jsme sem pøišli?
{8352}{8444}Pøed naším pøíchodem do vesnice byl zvláštní.
{8456}{8596}Má to nìjakou spojitost s tím, e nesmí vstoupit do Holy Capital?
{8672}{8736}Nemùu nic øíct.
{8750}{8812}Chci jít do Holy Capital se všemi mımi pøáteli!
{8812}{8837}Tím myslím i Hyuugu-san...
{8849}{8903}Øeknìte mi všechno, prosím!
{8948}{9030}Hyuuga má štìstí, e má takové pøátele.
{9056}{9122}Moná vám to mùu øíct.
{9170}{9255}Kdy byl ještì u Silver Tree Knights, Spirit Illusion |Tower se stala dìjištìm velké tragédie...
{9255}{9390}Rytíø jménem Carlyle se promìnil v Thanatose| a pøišel o ivot, kdy byl oèištìn.
{9410}{9446}Rytíø se promìnil na Thanatose?!
{9446}{9511}Èlovìk ovládanı Thanatosem?
{9511}{9539}A co Hyuuga?
{9555}{9693}Kdyby ho Hyuuga ochránil pøed Thanatosem, |nemusel Carlyle pøijít o ivot.
{9750}{9762}Carlyle!
{9788}{9878}Carlyle byl zvyklı bıt naším konkurentem.
{9878}{9938}Ne, byl to pøítel, kterı nemùe bıt nahrazen.
{9955}{9983}Pøítel...
{10079}{10141}Odpovìz, jestli stále iješ, Carlyle!
{10313}{10330}Teï, Carlyle!
{10635}{10676}Jak jsi si myslel, Hyuugo.
{10691}{10748}Ano... Bylo to excelentní.
{10903}{11084}Hyuugo, Dione, je mi ctí, e mùu bojovat s vámi dvìma za Královnu.
{11084}{11123}Mì taky.
{11143}{11237}Ochraòujme Arcadii pro budoucí Královnu!
{11273}{11300}Pro Královnu!
{11377}{11572}Teï je Carlyle absolutnì zbaven obav a odpoèívá |v pokoji na kopci naproti Holy Capital.
{11672}{11733}Kdy byl Hyuuga u Silver Tree Knights...
{11770}{11802}Hyuugo, Dione!
{11869}{11901}Slyšeli jste tu zvìst?
{11901}{11911}Ano.
{11912}{12023}Jednomu z nás moná bude udìlen titul Sacred Knight!
{12041}{12077}Sacred Knight?
{12077}{12187}Carlyle, Hyuugo... oba máte velkı potenciál.
{12198}{12296}Pokud jde o umìní s meèem, je Carlyle |absolutnì nejlepším z Organizace.
{12311}{12343}Carlyle je nejlepší volba.
{12397}{12456}Moná v tréninku...
{12456}{12534}Ale ty jsi odvánìjší ve skuteènıch bojích.
{12548}{12583}To je pravda.
{12583}{12617}Hyuuga je skvìlı.
{12633}{12727}Aèkoli jsem se k Organizaci pøidal pøed ním, jsem stále...
{12748}{12797}Ne! Nic jsem neøíkal!
{12831}{12927}Hyuuga se narodil v Orientu a byl vybrán do Organizace |pro jeho excelentní schopnosti.
{12953}{13060}A Carlyle, pøicházející z rodiny rytíøù, cvièil své schopnosti u v mládí.
{13072}{13162}Oba vdycky soutìili o nejlepší místo v Organizaci.
{13162}{13236}Carlyle mìl nejlepší plány v technické rovinì.
{13257}{13350}Ale ty nemohly bıt pouity ve skuteènıch bitvách.
{13385}{13460}Ale teï nevíme...
{13752}{13842}Carlyle se trápil vlastní slabostí.
{13856}{13918}Kdybychom si to uvìdomili...
{13944}{14010}ta tragédie se nikdy nemusela stát.
{14231}{14277}Abych se mohl stát Sacred Knight...
{14331}{14388}musím tìce pracovat a procvièovat se!
{14388}{14420}Rytíøi Carlyle!
{14431}{14485}Proè cvièíte tak brzo ráno?
{14485}{14551}Naèasování nemá nic spoleèného se zlepšováním dovedností s meèem.
{14551}{14636}Thanatosové si nevybírají místo a èas, kde se objeví.
{14636}{14669}To je pravda.
{14669}{14724}Jste opravdu pøíklad pro všechny rytíøe.
{14724}{14795}Slyšel jste to?
{14821}{14907}Øíká se, e se rytíø Hyuuga stane Sacred Knight.
{15051}{15123}Tentokrát bude Sacred Knight urèitì Hyuuga.
{15123}{15200}Vlastnì jsem si myslel, e ten titul dostane Carlyle.
{15214}{15305}Hyuuga je zvıhodnìnı pro své schopnosti ve skuteènıch bitvách.
{15376}{15449}Ještì to není oficiální!
{15467}{15544}Ještì nic nevyluèuje, e se neobjeví Thanatosové!
{15565}{15667}Carlyle chtìl titul Sacred Knight víc, ne kdokoli jinı.
{15667}{15685}Ale...
{15771}{15790}Carlyle!
{15826}{15838}Sakra!
{15973}{15997}Hyuugo!
{16134}{16224}Zvìsti byly pravdivé... Hyuuga byl vybrán na post Sacred Knight.
{16306}{16367}Den pøed ceremoniálem...
{16367}{16386}On...
{16432}{16531}Tentokrát jsi titul vyhrál Hyuugo. To ti náleí.
{16531}{16618}Nemùu zde víc ít. Prosím, ochraòuj Arcadii dobøe.
{16618}{16650}O èem to mluví?
{16695}{16747}Mìli bychom to øíct Head Order, ne?
{16761}{16812}Chci pozdret zítøejší ceremoniál.
{16847}{16861}Hyuugo!
{16882}{16986}Nakonec jsme Carlyla nemohli nikde najít.
{17029}{17131}Ceremonie šla nakonec podle plánu.
{17143}{17225}A našli jste ho èasem?
{17237}{17275}Ano. Dva roky  potom.
{17275}{17308}Dva roky...
{17337}{17392}To Hyuuga-san opustil Organizaci..
{17414}{17476}Ale pro Carlyla to bylo pozdì...
{17546}{17572}Carlyle...
{17640}{17671}Hyuugo... Nedívej se!
{17696}{17708}Carlyle!
{17861}{17937}Carlyle se promìnil na Thanatose pøímo pøed Hyuugou.
{17989}{18002}Carlyle!
{18012}{18030}Proè?
{18048}{18130}Pomoz mi... Hyuugo!
{18130}{18178}Rychle mì oèisti!
{18451}{18521}Thanatos pobıval uvnitø èlovìka.
{18521}{18598}To je neslıchané.
{18598}{18737}Kdybychom nezabili èlovìka, ve kterém pobıval |Thanatos, u by se nemohl oddìlit od jeho tìla.
{18751}{18921}Take, naše pøátelství z dìtství... |V tom pøípadì nebyl jinı zpùsob ne ho oèistit.
{18932}{18989}Proè to takhle skonèilo?
{19003}{19041}Nevím.
{19041}{19174}V temntotì se skrıvala bezradnost.
{19177}{19269}Take, aby našel pravdu, Hyuuga...
{19325}{19353}Poèkej, Hyuugo!
{19369}{19413}Opravdu opouštíš Organizaci?
{19424}{19484}Zahodil jsi svou identitu jako rytíøe?!
{19538}{19614}Jsme rytíøi, kteøí jsou pøedurèeni ochraòovat Arcadii, Dione.
{19614}{19683}Take musíme splnit naši povinnost, a je, kde je.
{19885}{19956}Hyuuga je mu se silnım smyslem pro odpovìdnost.
{19966}{20062}Stále se obviòuje za to, e nedokázal zachránit Carlyla.
{20062}{20143}Ale svımi schopnostmi nedokáe oèistit Thanatose sám.
{20143}{20269}Ano, to proto... Kdy se Thanatosové objevili kolem Spirit Illusion Tower,
{20269}{20357}moná si myslí, e Carlyle oil.
{20357}{20514}Slyšel jsem od vesnièanù, e Thanatos, kterı se objevuje |u Tower je jako èlovìk s ïábelskımi schopnostmi.
{20514}{20593}Take jestli Thanatos opravdu Carlyla oivil...
{20593}{20651}Hyuuga ho chce oèistit sám.
{20675}{20696}Ano.
{20851}{20867}Ange?
{20879}{20901}Co je to?
{20901}{20934}Ten motıl!
{20952}{20969}Poèkej!
{20993}{21008}Ange!
{21029}{21118}Jsem si jistá, e se jeho srdce ještì neupokojilo.
{21241}{21263}Carlyle!
{21277}{21312}Jsi tu?
{21493}{21522}Carlyle!
{21534}{21557}Jsi to ty, Carlyle?
{21713}{21749}Hyuugo...
{21769}{21933}Jako Sacred Knight jsi nejvhodnìjší na ochranu Královny...
{21947}{22054}To je pro Rytíøe nejvìtší èest!
{22096}{22163}Nemùu tomu rozumìt,
{22186}{22266}ale je úasné, e jsi získal ten titul.
{22266}{22308}Opravdu je to tak!
{22349}{22417}Byl jsem ovládanı Thanatosem,
{22430}{22521}ale nemohl jsem bıt úplnì oèištìn.
{22541}{22623}Tenkrát jsem tì poádal, a mì zachráníš...
{22637}{22664}Øekl jsem "pomoz mi".
{22688}{22711}Carlyle...
{22734}{22777}Omlouvám se... Carlyle.
{22957}{23066}Pøidej se ke mì, Hyuugo!
{23116}{23131}Hyuugo-san!
{23227}{23279}Zùstaò vzadu, Ange!
{23507}{23571}Hyuuga moná brzo ztratí své schopnosit Purifiera...
{23658}{23687}Hyuugo-san!
{23802}{23921}To je hezké. Znièil jsi svìt, kterı jsem chtìl ochraòovat.
{23921}{23979}Královna bude klam.
{23979}{24063}Take je jedno, co chceš, je to zbyteèné.
{24063}{24089}Královna...
{24191}{24259}Královna není klam!
{24287}{24374}Byl jsi skvìlı rytíø, zapøísáhlı chránit Královnu!
{24392}{24449}Carlyle by nikdy Královnu nezradil!
{24449}{24476}Hyuugo-san!
{24517}{24538}Angelique!
{24713}{24730}Hyuugo.
{24785}{24806}Carlyle...
{24849}{24923}Nemùu tì po tom všem nenávidìt.
{24923}{25034}Jen jsem chtìl více síly od Foundation, protoe jsem chtìl bıt lepší.
{25045}{25121}Cítíl jsem se jako obì vlastní slabosti.
{25171}{25225}Neobviòuj se, Hyuugo.
{25250}{25349}Nechci tì takhle kvùli sobì vidìt.
{25370}{25404}Carlyle...
{25404}{25482}Vdycky jsi mìl hlavu vzhùru a šel jsi vpøed.
{25482}{25586}Mám rád tu hrdou tváø.
{25603}{25687}Take, prosím, odpust mi.
{25730}{25745}Carlyle!
{25913}{25977}Nemám co odpouštìt!
{26020}{26043}Hyuugo-san!
{26143}{26167}Angelique.
{26167}{26215}Bohudík, Hyuugo-san!
{26229}{26292}Proè jste sem pøišla?
{26304}{26365}Ten záøící motıl mì sem zavedl.
{26365}{26392}Záøící motıl?
{26392}{26479}Ano. Kdy jsme se vidìli poprvé, létal okolo vás.
{26493}{26558}Je to jako by vás ochraòoval.
{26608}{26721}V legendì z Orientu, se duše zemøelıch lidí mohou stát motıli.
{26738}{26824}Jsem si jistá, e ten motıl byl Carlyle.
{26836}{26853}Carlyle...
{26873}{26958}Moná nemùete vrátit Carlyla do svého srdce, ale
{26971}{27058}teï jste náš pøítel, Hyuugo-san.
{27058}{27171}Tak to prosím nezapomìòte a zùstaòte s námi.
{27191}{27217}Angelique.
{27445}{27480}Hyuugo-san!
{27480}{27617}Slibuji... Budu na vaší stranì do posledního dechu!
{27664}{27745}Ten Thanatos nebyl Carlyle?
{27769}{27839}Carlyle mì nemùe nenávidìt.
{27852}{27882}Aha.
{27882}{27931}Je tu jedna vìc, na kterou bych se rád zeptal, Rayne.
{27947}{28067}Carlyle mi øekl, e chtìl dostat od Foundation sílu.
{28086}{28124}Od Foundation?
{28124}{28156}Víš o tom nìco?
{28179}{28203}Neøíkej mi, e...
{28203}{28217}Rayne?
{28245}{28398}Kdy jsem byl ještì ve Foundation, |vyvinuli jsme stroj na zvìtšení síly Purifiera.
{28398}{28499}Nìkteøí lidé, pak mohli bıt Purifiery.
{28499}{28614}Jestlie mu zvìtšila sílu Foundation, |Thanatos mìl vìtší šanci se v nìm usadit.
{28614}{28684}Vynaloil jsem velké úsilí k vynaleznutí toho èipu.
{28724}{28877}Take ten èip má schopnost dovolovat Thanatosùm, aby ili uvnitø lidí.
{28894}{29067}Znièil jsem èip, kdy byl ve vırobì a smazal jsem i data.
{29067}{29108}Ale nepovolil jsem zálohování.
{29108}{29146}A... Navíc...
{29162}{29238}Ten èip je moná uvnitø Carlyla...
{29238}{29306}Vy jste na Carlylovi experimentovali?
{29306}{29367}Foundation...
{29401}{29439}O èem to mluvíš?
{29439}{29493}Jsi ironizující dokonalost vaší Organizace?
{29515}{29544}Všechno je moje chyba.
{29556}{29572}Omlouvám se.
{29618}{29644}To staèí.
{29644}{29661}Hyuugo!
{29668}{29764}Jesli byl Carlylùv úmysl vloit si to do tìla...
{29777}{29804}Hyuugo!
{29823}{29919}Znáš nièivé schopnosti toho èipu, tak ho zniè.
{29938}{30016}Skuteènı zloèinec je nìkdo, kdo ho chtìl navzdory tomu obnovit.
{30041}{30087}Uznávám, e jsi to nemohl bıt ty.
{30110}{30150}Take tì neodsuzuji...
{30180}{30214}Pojïme spolu k Holy Capital.
{30231}{30250}Hyuugo-san!
{30263}{30288}Hyuugo!
{30288}{30317}Skvìlé.
{30356}{30407}Ale nevracím se k Silver Tree Knights.
{30408}{30552}Musím ochraòovat své drahé pøátele.
{30552}{30581}Hyuugo-san!
{30734}{30748}Carlyle...
{31357}{31407}U je èas, Mathiasi?
{31407}{31419}Ano.
{31440}{31528}Po tajném nástupu na trùn u to bude jen tvá cesta.
{31528}{31550}Rozumím...
{31570}{31659}Budeš mi dál pomáhat?
{31659}{31771}Jistì. Vdycky budu ít v míru v okolí Holy Capital.
{31804}{31888}Angelique se koneènì vrátí.
{32006}{32119}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32184}{32327}www.mycolorfullife.blog.cz
