{1}{1}23.976
{304}{376}Na obloze musí bıt skuteèná svoboda.
{391}{486}Bude to naposledy, co na to myslím?
{524}{606}Pøípravy na ceremoniál jsou hotovy, René.
{630}{643}Dobøe.
{662}{684}Vím.
{833}{918}TaSHe's Gang uvádí
{1166}{1248}NEO ANGELIQUE ABYSS|SECOND AGE
{3234}{3303}POVSTÁNÍ V HOLY CAPITAL
{3433}{3482}Jak úasnı poèet poutníkù!
{3497}{3630}Všichni chtìjí vidìt korunovaci Reného-sama.
{3671}{3751}Detaily musí bıt oznámeny v novinách.
{3763}{3854}Jak jsem si myslel, je tu mnoho pøísnıch vstupních poadavkù.
{3854}{3889}Nemùu tì dál doprovázet.
{3889}{3981}Omlouvám se. Aèkoli jsi u v Holy Capital byl...
{4003}{4075}A Erwine, chovej se slušnì, ano?
{4139}{4182}Oh, Erwine!
{4224}{4290}Vypadá, e chce zùstat s tebou, Ange.
{4345}{4378}Teï kdy jsi se zmínila...
{4440}{4483}Dìkuji mnohokrát.
{4483}{4530}Není zaè!
{4530}{4630}Bıt obeznámenı s krásnımi sleènami mì dìlá sastnım.
{4645}{4663}Neøíkejte to...
{4683}{4747}Ehm... Vlastnì je tu nìco co byste chtìl na oplátku?
{4762}{4813}Oh, nechte mì pøemıšlet...
{4813}{4909}Aèkoli jsme se sotva poznali, zní to dost lákavì...
{5008}{5034}Ehm...
{5034}{5090}Promiòte, musím u jít!
{5090}{5146}O dárku si promluvíme pozdìji!
{5146}{5181}Nashle!
{5236}{5355}Chybìla mi ta doba, kterou jsem mohla strávit s Bernardem-niisan!
{5355}{5452}Ano, byla jsi krásná dívka a zvíøata tì zboòovala.
{5452}{5507}Pamatuju si velkého psa ze sousedství.
{5537}{5650}Chtìl si se mnou jen hrát a já si myslela, e mì chce sníst.
{5660}{5698}Taky jsem se bál.
{5698}{5778}Plakala jsi a bìela za mnou, abych tì ochránil.
{5916}{5958}U je èas!
{5986}{6075}Mùeš nám o korunovaci povìdìt pozdìji.
{6091}{6107}Jistì.
{6118}{6196}Moná bych s tebou mohl udìlat speciální interview, Ange.
{6685}{6735}Brzy to zaène.
{7254}{7349}Odpoèívejte v pokoji, Mathiasi-sama.
{7364}{7459}Novı Head Order udìlá tento svìt jistì lepším místem.
{7459}{7543}Mohou všichni prosebníci dosáhnout na oblohu?
{7543}{7593}Pùjde všechno dobøe?
{7593}{7635}Øekni, co myslíš?
{7723}{7822}Pøedchozí Head Order, Mathias-sama, zemøel.
{7822}{7939}Vyèkávali jsme s korunovaèním ceremoniálem pro nového Hear Order, Reného.
{8433}{8513}Mathias je stále naivu.
{8529}{8631}Povede takovı ivot, aby vypadalo, e neexistuje.
{8959}{9030}Nemyslíš si, e  bych opustil Holy Capital kvùli tobì?
{9048}{9064}Kdo jsi?
{9113}{9211}Jak jste bezcitní. Tak brzo jste zapomemout mùj hlas.
{9344}{9360}Mathiasi!
{9417}{9524}Head Order z Celestizamu, Mathias, je stále naivu!
{9524}{9613}A nepøipouští korunovaci nového Head Order!
{9630}{9658}Co se dìje?
{9658}{9704}Nemùu uvìøit svım oèím!
{9704}{9786}P-proè jsi tady?!
{9786}{9841}Co chceš, Mathiasi?
{9857}{9917}Neodpustím ti, jestli se budeš takhle chovat!
{9934}{9949}René...
{9977}{10083}Dobøe se na mì podívej. Vidíš nìjaké zaváhání?
{10083}{10138}Bylo to nedorozumìní.
{10152}{10329}Ale dovol mi tento zpùsob. Od teï se zbyteènì |nebudu obávat o tvou budoucnost.
{10342}{10406}O èem to mluvíš, Mathiasi?
{10406}{10449}Nerozumím tomu.
{10466}{10523}Moná by se's mìl zeptat Holy Capital.
{10523}{10628}Kdo je dùleitìjší, ty nebo já?!
{10706}{10722}To je...
{10722}{10762}Co to je?
{10762}{10831}Proè... Jakto, e je tady?
{10845}{10891}Co se dìje, Rayne?
{10891}{11006}Znièil jsem to ve Foundation... Nemìlo by to existovat!
{11041}{11093}Èip zvyšující sílu Purifiera!
{11110}{11169}Neøíkej mi, e tohle bylo uvnitø Carlyla?!
{11215}{11266}To staèí, Mathiasi-dono!
{11285}{11309}Ten artefakt je...
{11322}{11360}Vím.
{11360}{11505}Bylo tím zaplaveno Carlylovo slabé srdce, ale já to nemùu vydret.
{11515}{11542}Mathiasi-sama...
{11559}{11589}Mathiasi...
{11589}{11650}Byl jsem vybrán Holy Capital...
{11670}{11723}Musím mít schopnosti Purifiera a chovat se podle oèekávání!
{12062}{12094}Mathiasi!
{12267}{12309}Na co èekáte?!
{12309}{12363}Teï! Chyte toho zrádce!
{12389}{12405}Poèkejte!
{12405}{12435}Nepøibliujte se k nìmu!
{12680}{12695}To je...
{12853}{12928}Nìjaká temná síla...
{12955}{13073}A od teï mám v rukou nejsilnìjší moc!
{13113}{13129}Mathiasi!
{13161}{13182}Stojíš mi v cestì.
{13237}{13287}Proè? Proè to?!
{13435}{13501}Holy Capital si mì vybrala.
{13521}{13657}Jsem nejvhodnìjší pro ochranu tohoto mìsta!
{13758}{13784}Ange!
{13784}{13799}Sakra!
{13990}{14033}Postarám se o Queen's Egg.
{14131}{14143}Ange!
{14306}{14319}Jete!
{14319}{14336}Sakra!
{14376}{14471}Neodpustím nikomu, kdo jedná s Ange jako s nepøítelem!
{14591}{14620}Pøátelé...
{14826}{14857}Hej!
{14857}{14924}Buï v klidu! Co se to s tebou dìje?
{14924}{15017}Slyšel jsem hluk, jako by se rozbilo okno.
{15017}{15094}Neøíkej mi, e se nìco objevilo?!
{15114}{15160}Doufám, e to nic není...
{15275}{15293}René...
{15437}{15499}O Queen's Egg je postaráno.
{15528}{15600}ádám tì. Nezahrnuj do toho Angelique!
{15622}{15781}Nevím o tvıch zámìrech, ale jestli nìco chceš, prober to s Eldery!
{15804}{15869}Opravdu ti dám, co chceš!
{15869}{15932}Nech ji jít!
{15932}{15958}René-san...
{16028}{16134}Kdy? Kdy jsi vyrostl?
{16184}{16223}Øekl jsem ti to.
{16245}{16377}A se mùj úkol Head Order bude blíit ke konci, jakı osud mì èeká?
{16440}{16463}To je...
{16628}{16661}Ta dıka z toho dne...
{16680}{16801}Ta dıka pøedstavovala zprávu od High Eldera.
{16838}{16960}"Je nevhodné pro falešného Ordera jako jsi ty, ít uvnitø Organizace.
{16979}{17056}Vem si svùj ivot poté, co vykonáš svou povinnost."
{17079}{17110}Nemoné!
{17110}{17174}Tak kruté! Nemùu tomu uvìøit!
{17211}{17270}Je to mùj osud, ne?
{17286}{17373}A shodou okolností jsi to byl ty, kdo mì minul.
{17373}{17514}No, je to High Elder, komu skonèil osud.
{17514}{17546}Neøíkejte mi, e...
{17546}{17606}To není...
{17647}{17726}Chceš opustit Holy Capital? Jsi jako pták v kleci?
{17726}{17771}Nechtìj mì rozesmát.
{17784}{17863}Nemáš ádnou pøedstavu o tom, jak hnusnı je svìt venku.
{17863}{17918}Jsi vdycky chránìnı.
{17918}{17983}Vìøíš, e bys venku pøeil?
{18000}{18007}Mathiasi-sama!
{18095}{18124}Nezabiju tì.
{18137}{18169}Ne teï...
{18212}{18271}Tvé znalosti by mohly bıt uiteèné.
{18289}{18404}Správnì! Proè nezùstaneš vedle mého trùnu jako opìrka na ruce?
{18425}{18496}Udìlám tì opravdovım ptákem v kleci!
{18515}{18538}Jak mùete nìco takového udìlat?!
{18578}{18608}Queen's Egg...
{18628}{18749}Takté tvoji pomoc potøebuju k øízení Holy Capital.
{18794}{18817}Co to je?!
{18828}{18887}Nemùu jen tiše stát a dívat se na to!
{18887}{18921}Ano, pojïme!
{18921}{18968}Já se postarám o Jeta!
{19033}{19165}Dobré naèasování. Dám vám ochutnat mé nové získané schopnosti.
{19300}{19334}Jak mocné!
{19480}{19494}Thanatosové!
{19515}{19600}Má moc mùe pøivolat Thanatose?
{19622}{19642}Dobøe, dobøe...
{19661}{19675}To je docela zábava.
{19742}{19773}Co to znamená?!
{19773}{19848}Slyšel jsem, e ten èip dovolí, aby tì Thanatos ovládal!
{19848}{19945}Vypadá to, e má víc skrytıch schopností.
{19945}{20018}Ano... To je schopnost, kterou neznám.
{20018}{20052}Ale vím, e nakonec...
{20068}{20143}Není dlouho osobou, kterou byl.
{20295}{20341}V-Všichni utíkejte!
{20500}{20548}Hej, hej! Co je to za vtip?
{20691}{20754}Sakra... Co se v té katedrále stalo?
{20769}{20812}Takhle se nemùeme pøiblíit!
{20812}{20833}Ange...
{21389}{21411}Je jich moc!
{21458}{21519}Osm Thanatosù.
{21519}{21571}Èas dosaení Ange, kdy pobìím je deset sekund.
{21571}{21588}Mùu to udìlat.
{21673}{21709}Kryju tì, J.D.!
{21893}{21921}Nech zbytek na mì!
{22109}{22122}J.D.-san!
{22138}{22158}Ange!
{22417}{22473}Nenechám tì udìlat další krok.
{22496}{22543}Omlouvám se, ale musím ten další krok udìlat.
{22543}{22596}Má drahá osoba je toti za tebou!
{23136}{23193}Poèkej na mì, Ange.
{23193}{23215}Hned pøijdu.
{23231}{23259}J.D.-san...
{23305}{23330}Zkoušíš mì odstrèit...
{23482}{23554}Proè bojuješ tak neúèinnì?
{23554}{23677}My zbranì bychom mìli dávat pøednost kompletnímu odstranìní nepøátel!
{23691}{23736}Nechci nikomu ubliovat.
{23752}{23780}I ty...
{23838}{23909}Ten den ve vızkumném centru Foundation...
{23909}{23999}Se stala nehoda... Na zaèátku experimentu.
{23999}{24088}Z mého tìla unikla neuvìøitelná síla.
{24165}{24208}Byla to moje chyba, e se to stalo.
{24234}{24375}Aèkoli jsem si pøál všechny zachránit, mé |tìlo se nebıbalo, jak jsem chtìl.
{24398}{24538}Všichni lidé kolem mì zemøeli.
{24597}{24673}Vìdìt, jak bolestné je nìkomu ublíit...
{24691}{24776}A jak tìké je udret bolest ve mì...
{24873}{24952}Nechci udìlat tu samou chybu!
{24952}{25013}Uvìdomil jsem si jaká chyba...
{25013}{25120}Ve Foundation, kdo nemùe vykonávat pøíkazy velitele...
{25138}{25201}To znamená, ty!
{25304}{25370}Foundation nepotøebuje emoce!
{25437}{25537}Srdce se uvnitø mì narodilo, kdy jsem potkal drahocenné osoby.
{25537}{25621}Ty jsi pro mì jako bratr...
{25639}{25772}Vùdce tvé podøízenosti mì, je tvé srdce.
{25785}{25923}Váhat nad znièením nepøítele znamená, e jsi vadná zbraò!
{25976}{26056}Jete... Jsem si jistı, e máš taky srdce.
{26070}{26128}A kdy potkáš drahocenné osoby, tak...
{26140}{26231}Všechno co potøebuju, jsou pøíkazy velitele!
{26365}{26383}J.D.-san!
{26653}{26714}Znièit vadného.
{26760}{26781}Stop!
{26859}{26888}Nemoné!
{26888}{26963}Znièit nepøítele je hlavním zámìrem...
{26964}{27058}Jsem perfektní artefakt a toto je základ mého jednání.
{27075}{27179}Jste jedinı, kdo bude zranìn, pokud to udìláte!
{27487}{27572}Vdycky kdy tì potkám, dìjí se divné vìci!
{27744}{27822}Jsem ovlivnìn slovy, která vysloví...
{27838}{27879}nìkdo jinı, ne mùj vùdce!
{27944}{28002}Nepøijatelné... Proè?!
{28013}{28040}Proè?!
{28040}{28192}Jak mì mùou tvá slova a èiny pøimìt, |abych cítil nìco hluboko v mé mysli!
{28244}{28266}Mathiasi!
{28266}{28294}Zastav ho!
{28314}{28360}Dívejme se, co se stane.
{28360}{28479}Nechám ji jít, pokud je opravdu schopná.
{28479}{28502}Nemoné!
{28608}{28638}Musím ji zachránit...
{28654}{28687}Má drahá pøítelkynì...
{28731}{28743}Ange!
{28759}{28790}Pryè z cesty!
{29404}{29417}To je...
{29428}{29456}Proè... je tady?
{29476}{29520}Nemoné! To nemùe bıt...
{29726}{29793}Jsi v poøádku, Angelique?
{29872}{29903}Nyxi-san...
{30114}{30143}Ehm... Proè?
{30178}{30220}Pojï se mnou.
{30299}{30362}Nemám moc èasu.
{30574}{30645}Všichni uvnitø ještì bojují...
{30666}{30682}Ale...
{30769}{30831}Jestli teï uchopím jeho ruku...
{31122}{31136}Ange!
{31152}{31188}Co to dìlá?!
{31203}{31233}Uklidni se!
{31233}{31296}Pøijdeš o ivot, jestli odsud odejdeš!
{31296}{31331}Pojïme!
{31473}{31498}To je...
{31525}{31580}Roche, ty...
{31609}{31651}Sakra! Nevím proè!
{31733}{31758}Nyxi-san...
{31778}{31849}Øeknìte mi, co se ten den stalo!
{31985}{32136}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32245}{32386}www.mycolorfullife.blog.cz
