{1}{1}23.976
{34}{80}Pojï se mnou.
{159}{226}Nemám moc èasu.
{315}{422}TaSHee's Gang uvádí
{665}{743}NEO ANGELIQUE ABYSS|SECOND AGE
{2739}{2796}NOC PRAVDY
{2924}{2942}Nyx!
{2942}{2982}Co sakra...
{2999}{3044}Co to znamená?
{3154}{3214}Nerozumím svım vlastním myšlenkám...
{3238}{3263}Jete.
{3263}{3340}Pøiveï zpátky Queen's Egg.
{3362}{3395}Rozumím!
{3429}{3445}Poèkej!
{3570}{3607}Nenechám vás jít.
{3768}{3804}Proè?
{3804}{3886}Proè jsou mé èiny omezeny jejími slovy?
{3902}{3949}Jsem si jistı, e máš taky srdce.
{3967}{4023}A a potkáš drahocenné osoby...
{4061}{4098}Drahocenné osoby?!
{4153}{4236}Není nikdo dùleitìjší ne mùj pán!
{4345}{4409}Proè se mi pøehrává pamì?!
{4593}{4642}Pojedeme, Angelique.
{4642}{4650}Dobøe.
{4854}{4901}Cíl zamìøen.
{4901}{4928}Queen's Egg.
{4952}{5001}8 sekund do chycení.
{5463}{5511}Na tuto vzdálenost je chycení nemoné.
{5527}{5581}Mise neúspìšná.
{5866}{5887}Nyxi-san...
{6000}{6019}Pozor!
{6056}{6070}Tudy!
{6081}{6148}Poslouchejte! Tady se Thanatosové nedostanou!
{6148}{6182}Teï, rychle!
{6341}{6368}Dìkuji mnohokrát!
{6368}{6397}Dávejte pozor, ano?
{6397}{6425}A-Ano!
{6455}{6498}Dobøe, pojïme!
{6498}{6582}Máš pravdu... Bojím se o Ange.
{6598}{6616}Erwine!
{6714}{6758}Chce, abychom ho následovali?
{6758}{6792}Vypadá to tak.
{6792}{6817}Pojïme.
{6817}{6893}Moná se tu nìco objeví.
{6893}{6910}Ano.
{7268}{7298}Nikde to nekonèí!
{7298}{7341}Musíme si pospíšit a sledovat Ange!
{7341}{7423}Mùete vzdorovat tolika Thanatosùm?
{7770}{7792}Co tohle?
{7792}{7898}Holy Capital potøebuje mou moc.
{8016}{8053}Touhle rychlostí to dokáeme!
{8053}{8133}Jestli nebudeme rychlí, tak Ange nìco udìlá!
{8133}{8221}Rayne! J.D.! Zachraòte Reného-sama.
{8221}{8245}Teï ustupte.
{8254}{8337}Ano... Teï jsme opravdu v taktické nevıhodì.
{8337}{8385}Dobøe, jdu.
{8385}{8414}Poèítám s tebou!
{8414}{8426}Rozumím!
{8541}{8584}Znièím Thanatose!
{8652}{8676}Smìšné.
{8861}{8869}Nenechám tì jít!
{9065}{9099}Mathiasi...
{9112}{9134}René...
{9183}{9226}Jdi, kam si pøeješ.
{9226}{9307}U tu není ádná klec, která by tì drela.
{9626}{9657}Jste v poøádku?
{9657}{9678}Ano...
{9695}{9725}Mathiasi...
{9757}{9769}René-sama...
{9787}{9862}Zdá se, e budeme muset jít skrz nì, abychom se dostali k bránì.
{9862}{9879}Ano.
{9975}{9988}Jete!
{10029}{10075}Zùstaòte za mnou, René-sama.
{10092}{10150}U s tebou nechci bojovat.
{10188}{10228}Mìl jsem ti to øíct.
{10228}{10280}Jsem jinı ne ty.
{10280}{10425}Poslouchám pøíkazy. Teï nemám pøíkaz abych tì zabil.
{10504}{10542}Pak nás nech jít.
{10542}{10586}René-sama, pojïme.
{10771}{10826}Vzít nìkoho jiného s sebou je pod úroveò.
{10867}{10879}Jete!
{11247}{11270}Tohle místo...
{11326}{11405}Nemyslel jsem si, e bych se sem nìkdy vrátil.
{11440}{11485}Tohle je dùm mé rodiny.
{11485}{11564}U je to dlouho, jezdil jsem sem se svou rodinou.
{11657}{11767}Ano... Naposledy co jsme tu byli, mìla matka narozeniny.
{11806}{11931}Vyrobil jsem to pro ni jako dárek.
{12009}{12046}Je zima.
{12046}{12091}Pojïme dolù do vnitøní místnosti.
{12920}{12975}Nemohu najít slova...
{12994}{13048}Jak bych se mìl omluvit?
{13048}{13079}Bohudík...
{13133}{13177}Jste naivu...
{13214}{13246}Angelique...
{13246}{13342}Prosím, øeknìte mi, co se pøedtím stalo.
{13496}{13563}Nechcete se stát prachem s tímto sídlem?
{13577}{13648}Proè... je to...
{13804}{13951}Nebyl jste ten Nyx-san, kterého jsem znala.
{13978}{14083}Ve skuteènosti jsem to byl já a nebyl jsem to já.
{14110}{14193}Znáš Erbose, e, Angelique?
{14214}{14306}Ano. Kvùli nìj byl náš mír narušenı...
{14333}{14407}A je to on, kdo na tento svìt posílá Thanatose.
{14434}{14480}Moná tomu neuvìøíš, ale..
{14509}{14617}ve mì bijí dvì srdce.
{14670}{14732}To první jsem já teï.
{14758}{14836}A to druhé je Erbos.
{14893}{14984}Moji svobodu mi ukradl Erbos.
{14984}{15103}Nepøítel, kterého musíš znièit, je teï pøímo pøed tebou.
{15103}{15163}Ne! Proè?!
{15184}{15233}Proè vám to Erbos udìlal?
{15262}{15317}Je to všechno kvùli mé slabosti...
{15338}{15443}Má touha ít pøivolala Erbose.
{15498}{15576}Stalo se to, kdy jsem byl mladı.
{15725}{15828}Kdy jsem cestoval s rodièi, loï byla vtaena do bouøky.
{15864}{15913}Mohli jsme se jen modlit.
{15943}{16012}Ale naše modlitby nebyly vyslyšeny.
{16156}{16263}Jediná vìc, kterou jsem si pøál z celého srdce, kdy jsem byl smeten do oceánu, byla...
{16285}{16376}Zachraòte mì! Nechci takhle umøít!
{16408}{16444}Chci ít!
{16444}{16506}Udìlám cokoli, abych byl zachránìn!
{16506}{16536}Kdokoli!
{16557}{16616}Poté co jsem to øekl, bylo mé pøání splnìno.
{16678}{16742}A všechno to udìlal Erbos.
{17115}{17218}Erbos ije ve mnì.
{17243}{17397}Od té nehody nenávidím moøe a hluk vln.
{17397}{17526}Protoe mi to pøipomíná odpornı èas, kdy do mì Erbos vstoupil.
{17554}{17605}Musí to bıt Erbosova moc...
{17605}{17674}e je mé tìlo neschopné zemøít.
{17691}{17806}Po dvì stì let jsem se toulal jako vìzeò èasu.
{17823}{17856}Dvì stì let?!
{17856}{17887}Take...
{17916}{18049}"Dívat se na vás mi pøipomíná, jak hrál pøed 50 lety na piano."
{18099}{18173}Mùj dìdeèek by byl rád, kdyby to slyšel.
{18230}{18327}Je to tak, jak øekl pan August.
{18346}{18444}Po té nehodì mì Erbos ovládá kdykoli má monost.
{18514}{18676}Pouil mì jako hlavního, kdo posílal do Arcadie |Thanatose a odvádìl lidem ivotní sílu.
{18725}{18804}Erbosovo ovládání se kadım dnem zvyšovalo.
{18804}{18866}Bylo jasné, e jednou se u nebudu moct kontrolovat.
{18895}{18985}Tak jsem vytrvával do posledního zlomku nadìje...
{19105}{19158}Královna, která mùe znièit Erbose.
{19336}{19444}Tak jsem projel celı svìt a našel jsem tì.
{19546}{19646}Jsem opravdu šastnı, e jsi Queen's Egg.
{19945}{20002}Musíme dostat poutníky do bezpeèí!
{20030}{20118}Zdá se, e René-sama utekl s Orb Hunters.
{20126}{20155}Tak se také vrame!
{20155}{20168}Rozumím!
{20273}{20316}Velmi dobøe, e jsme tady.
{20316}{20397}To je pravda. Erwin našel tajnı prùchod.
{20412}{20502}Byli jsme zachránìni! Nakonec, sem Thanatosové nemùou!
{20536}{20607}Nás sem pøivedl René.
{20607}{20704}Zdá se, e se Thanatosové nemohou pøiblíit díky Silver Tree.
{20734}{20775}To je poprvé, co tady jsem.
{20786}{20809}Kde je J.D.?
{20809}{20884}Øíkal, e se k nám pøidá pozdìji a nìkam odešel.
{20884}{20900}Aha...
{21219}{21246}Erenfried.
{21279}{21438}Našel jsem tì, a tak mohu zemøít a ukonèit svùj osud.
{21575}{21690}Ale... Má touhla zemøít po dvì stì let
{21690}{21825}byla lehcec rozptılena, kdy se's chtìla stát Královnou.
{21962}{22036}Ah.. Ty jsi...
{22100}{22235}Chápeš, jak drahocennı èas jsem s tebou strávil?
{22235}{22314}Jsi boská a oslnivá.
{22345}{22413}Rád bych s tebou il, kdybych mohl.
{22441}{22473}Nyxi-san...
{22546}{22686}Ale Erbosova moc sílí, kdy si pøeju ít.
{22712}{22834}Nemám moc èasu se sebou strávit.
{22834}{22923}Take jsem ti to chtìl øíct teï.
{22944}{23010}Vím, e je to sobecká ádost.
{23093}{23248}Prosím, dopøej mi klidnou smrt, a budeš Královnou.
{23334}{23366}Jak bych mohla...
{23399}{23490}Není jiná monost jak zachránit Arcadii.
{23511}{23525}Proè?
{23613}{23668}Nemohu potlaèit své pocity.
{23716}{23906}A døív ne se staneš Královnou, se Erbosova síla zvıší a všechno potlaèí.
{23906}{23989}Má mysl bude nakonec Erbosem pohlcena.
{24008}{24091}Ale i tak, nemùu vás obìtovat...
{24297}{24357}Dìkuji, Angelique.
{24384}{24443}Jsem šastnı, kdy vím, jak se cítíš.
{24472}{24537}Ale budoucnost je nevyhnutelná.
{24563}{24601}Nedá se zmìnit.
{24632}{24725}Vzal jsem ti tolik vìcí.
{24775}{24840}Tvoje rodièe, tvùj domov,...
{24866}{24906}Jak jsem øekl, je toho hodnì.
{24968}{25005}Mılíte se.
{25037}{25131}Jedinı, kdo mi vzal mého drahého pøítele, je Erbos.
{25131}{25229}Vy jste osoba, která mi dala spoustu vìcí!
{25268}{25412}Kdy jsem ztratila rodièe, byla jsem osamìlá.
{25432}{25575}Byl jste to vy, kdo mi dal drahocennı domov a pøátele!
{25598}{25674}Koneènì jsem našla místo, kde chci ít!
{25743}{25823}Sunlit Mansion byla znièena, ale...
{25823}{25928}Mùeme postavit novou s vámi i s našimi pøáteli!
{25928}{25990}Take... Nyxi-san...
{26023}{26105}Zùstaòte s námi!
{26122}{26156}Angelique!
{26290}{26304}Nyxi-san!
{26465}{26530}Angelique... Uteè!
{26734}{26807}Nepotøebuju tì, abys mì zabila.
{26821}{26866}Já tì zabiju.
{26920}{26961}Promiòte, e jsem vás nechal èekat.
{27058}{27092}Erenfried!
{27258}{27268}René-sama.
{27295}{27390}Myslel jsem si, e vím o tomhle místì všechno.
{27425}{27501}To byla má domıšlivost.
{27524}{27592}I kdy byl Mathias jedinı mùj blízkı...
{27592}{27617}René-sama...
{27617}{27670}Na chvíli opusme Holy Capital.
{27699}{27754}Head Order nemùe Holy Capital opustit.
{27769}{27872}Znám pravidla Organizace, ale vaše bezpeèí pøedevším.
{27892}{27905}Ale...
{27921}{27997}A musíme hledat Angelique.
{28062}{28159}Znám tajnı prùchod, kterım se odsud dostaneme.
{28159}{28183}Pojïme k nìmu!
{28436}{28523}Dobøe, uvolni se...
{28523}{28568}Bude to pro tebe jednodušší.
{28769}{28814}Dobøe, velmi odváné.
{28837}{28893}Zabiješ mì?
{28908}{29027}Nemám v úmyslu zabít Nyxe-san!
{29073}{29115}Vy nejste on!
{29115}{29145}Jste Erbos, ne?
{29168}{29239}Nyx-san by mi neublíil!
{29257}{29318}Slyšíte mì, Nyxi-san?
{29318}{29389}Zachráním vás od Erbose!
{29460}{29542}Nevzdávejte to!
{29542}{29559}Nyxi-san!
{29683}{29732}Myslíš si, e to mùeš udìlat?
{29860}{29880}Nyxi-san...
{30033}{30078}Nyxi-san... Prosím...
{30372}{30403}Angelique...
{30509}{30532}Nyxi-san!
{30566}{30627}Jsi opravdu silnìjší, Angelique.
{30643}{30723}Tìším se, a se potkáme pøíštì.
{31236}{31300}Thanatosové mizí!
{31454}{31478}Zmizeli?
{31991}{32203}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32268}{32396}www.mycolorfullife.blog.cz
