{1}{1}23.976
{365}{423}Je tohle je úèinek èipu?
{575}{598}To jsi ty, Jete?
{697}{752}Co se stalo s Queen's Egg?
{783}{835}Jsem si jistı, e jsem ti pøikázal pøivést ji zpìt.
{943}{1016}Nepotøebuju nìkoho, kdo neplní rozkazy.
{1061}{1108}Nepotøebuju vadné.
{1108}{1129}Vadné?
{1150}{1163}Ano.
{1176}{1286}První pravidlo artefaktù je perfektnì poslouchat pøíkazy, ne?
{1317}{1397}Take, co ti pøekazilo vykonat tvùj úkol?
{1448}{1501}Jdi kam si pøeješ.
{1521}{1555}Je to váš pøíkaz?
{2250}{2269}Mathiasi...
{2341}{2386}Jste v poøádku?
{2415}{2465}Musíte bıt po tak dlouhé cestì unavenı.
{2465}{2505}Pokud chcete, udìláme si na chvíli pøestávku.
{2505}{2552}Jsem v poøádku.
{2591}{2605}Bernarde...
{2605}{2628}Kde je Roche?
{2628}{2647}Roche?
{2672}{2711}Eh? Odkdy je...
{2890}{2908}Jete...
{3005}{3033}Erwine!
{3042}{3101}Díkybohu! Nic ti není!
{3168}{3184}Angelique!
{3239}{3265}Pøátelé!
{3321}{3433}TaSHee's Gang uvádí
{3668}{3742}NEO ANGELIQUE ABYSS|SECOND AGE
{5733}{5799}ROZHODNUTÍ CHLAPCÙ
{5848}{5880}Nyxùv dùm?
{5904}{5945}Myslet si, e by taková vìc...
{5961}{5996}Momentálnì je to skvìlá pomoc!
{6011}{6062}Obávám se o Erenfrieda.
{6062}{6079}Ano...
{6192}{6209}Ange.
{6232}{6272}Jsem opravdu rád, e ti nic není.
{6321}{6388}Promiòte, e jsem udìlala takovou sobeckou vìc.
{6424}{6489}No, docela jsme se báli.
{6502}{6559}Není to problém dokud jste v bezpeèí.
{6581}{6621}Pøátelé...
{6621}{6686}Opravdu se omlouvám!
{6753}{6793}Nyx je ovládán Erbosem?
{6806}{6824}Ano.
{6840}{6860}Jak se to stalo?
{6882}{6913}Nyx-san je...
{7140}{7167}Nemoné!
{7167}{7210}Nemùu tomu uvìøit!
{7288}{7381}Rozumím tomu, jak se Nyx cítil jako chlapec.
{7381}{7460}Nemìl by se obviòovat, ale Erbos.
{7460}{7581}Take Nyx il sám asi 200 let?
{7581}{7653}Co teï vlastnì plánuje?
{7669}{7804}Prosím, dopøej mi klidnou smrt a se staneš Královnou.
{7869}{7919}Nechci ho nechat zemøít!
{7968}{8040}Chci ho zachránit!
{8060}{8161}Jistì Erbose z Nyxe-san vyenu!
{8293}{8307}Ange...
{8322}{8363}Zmìnila se.
{8363}{8434}Je opravdu zralejší ne pøedtím.
{8434}{8513}Je o krùèek blí k tomu, aby se stala Královnou!
{8513}{8599}Máš pravdu, zachráníme Nyxe.
{8599}{8643}Ano, to je jasné!
{8643}{8706}Nemám ádné námitky pro záchranu pøítele.
{8706}{8752}Dìkuju, pøátelé!
{8752}{8840}No, pùjdu ven.
{8840}{8866}Kam jdeš?
{8866}{8895}Bernarde-niisan?
{8911}{8996}Pùjdu do vesnice na úpatí hory, a pak znovu doplním své zásoby jídla
{8996}{9038}a taky shromádím nìjaké informace.
{9049}{9094}Taky musím kontaktovat svou kanceláø.
{9118}{9182}A taky se bojím o Rocheho.
{9182}{9198}Roche...
{9217}{9381}Myslím si, e sešel z hory, aby shromádil nìjaké pomocné informace.
{9381}{9452}Ale jestli teï pùjdeš, ne se vrátíš, bude tma.
{9452}{9492}Je to nebezpeèné, pokud pùjdeš sám.
{9492}{9582}V poøádku! Pro novináøe je jedno, jestli je poledne nebo noc.
{9582}{9688}Navíc jsem zvyklı cestovat a jednat sám.
{9711}{9747}Ochraòujte Ange.
{9787}{9808}Pardon.
{9808}{9840}Postaráme se o ni, dobøe?
{9840}{9850}Ano!
{9940}{10013}Bylo by dobré, kdybychom vìdìli nìco o dìní v Holy Capital...
{10030}{10058}Mathiasi...
{10083}{10193}Já... stále nerozumím.
{10242}{10282}Vdycky jsi byl na mé stranì...
{10302}{10378}Byl jsem mu tak blízkı.
{10396}{10423}Já...
{10798}{10891}Byl jsem vyvolenım Holy Capital!
{10910}{10959}To je závazné!
{10959}{10991}Bolí to?
{11141}{11227}Víš, kdo jsem, ne?
{11273}{11323}Er... bos...
{11323}{11406}Ano, jsem Erbos.
{11406}{11481}Skrıval jsem se v temntotì a vychutnával si záš jako pokrm.
{11578}{11684}Pøejete si naplnit tento svìt svımi zlovìstnımi myšlenkami, e?
{11699}{11836}A teï kvùli Foundation, je polovina tvého tìla kontrolována Thanatosi...
{11868}{11998}Slibuju, e tì Holy Capital neodmítne.
{12032}{12178}Myslíš tím, e si tu sedneš a budeš se na mì od teï dívat, jak se ti zlíbí?
{12178}{12195}Jak chcete.
{12218}{12297}Ale, ale... jak Celestizamská Organizace upadá...
{12311}{12369}Je na èase.
{12369}{12388}Oh?
{12388}{12438}Pøipomínka?
{12473}{12571}Od narození Reného, pravého Head Order...
{12571}{12630}zaèaly stroje vyšilovat.
{12669}{12703}Mám prosbu.
{12730}{12821}Prosím, nechej krásné Holy Capital mì.
{12821}{12952}Stále jsi fixován na Holy Capital, i kdy tvé tìlo neodpovídá?
{13034}{13128}Nemùeš zastavit ty šílené stroje?
{13128}{13147}Pak...
{13238}{13309}Dáš mi své tìlo a jednou vezmeš za své?
{13490}{13559}Silver Tree... usychá...
{13589}{13607}Coe?
{13688}{13706}To je...
{13706}{13795}Vìdìl jsem to! Zaèíná to bıt odporné!
{13820}{13879}Bude to horší, Ange!
{13923}{14029}To je nejvíc, co bez Purifierù dokáu, ale...
{14112}{14168}Je tu ještì nìco, co bych mohl udìlat!
{14267}{14299}Tak se to stalo!
{14311}{14351}Právì teï, v Holy Capital...
{14351}{14416}Nemyslím si, e je tam ještì nìkdo jinı kromì Mathiase.
{14416}{14452}Nikdo jinı?
{14452}{14542}Plánuju návrat do Holy Capital...
{14542}{14590}To není nejlepší se tam teï vracet.
{14590}{14668}Mathias je momentálnì opravdu nebezpeènı.
{14668}{14697}Mathias-dono má...
{14697}{14794}To ty jsi vyrobil ten èip pro Mathiase?
{14926}{14986}Vyrobil jsi ten èip, i kdy jsi vìdìl, co je zaè!?
{15007}{15066}Víš co jsi tím zpùsobil?!
{15082}{15114}Hyuugo-san!
{15220}{15259}Jdu se uklidnit.
{15282}{15308}Hyuugo-san...
{15363}{15464}Je pravda, e ten èip zvìtšuje sílu Purifiera.
{15481}{15613}Ale uivatel riskuje, e bude ovládán Thanatosem.
{15637}{15778}Potvrdil jsem to na sobì a nakonec jsem získal schopnosti Purifiera.
{15778}{15942}Ale uvìdomil jsem si, e je to nebezpeèné, tak jsem| smazal všechna data a opustil Foundation.
{15960}{16020}Nemoné... Mathias-dono...
{16046}{16093}Co jsem to udìlal?
{16156}{16251}Na takovém místì nemùeme ten èip zkoumat.
{16264}{16283}Co mám dìlat?
{16300}{16372}Jen jsem chtìl zachránit øeditele Yorga!
{16454}{16490}Oh, co se dìje?
{16518}{16570}Bernarde-niisan! Kde je Roche?
{16570}{16656}Ah, zkoušel jsem ho nìkolikrát hledat, ale nikde jsem ho nepotkal.
{16656}{16747}Ale je to èlovìk, kterı nìkolikrát prošel peklem...
{16747}{16792}Myslím, e se o nìj nemusíme bát.
{16804}{16875}Musíme dokonèit diskuzi o téhle situaci.
{16875}{16893}Aha.
{16893}{16923}Musím...
{16955}{16985}Musím vidìt øeditele Yorga!
{17003}{17071}Moná mi to teï neodpustí, ale...
{17085}{17171}Musíme najít zpùsob, jak zastavit èip všemi zdroji Foundation.
{17182}{17237}Ale, on je...
{17237}{17330}Vlastnì, slyšel jsem to, kdy jsem kontaktoval novináøskou kanceláø...
{17369}{17399}Zdá se, e...
{17418}{17452}dostal trest smrti.
{17492}{17505}Coe?!
{17526}{17613}Uíváním Jinx zpùsobi kritickou destrukci.
{17613}{17660}A jako osoba, která má Foundation na starosti...
{17660}{17710}Coe?! Neøíkej mi, e je u...
{17710}{17775}Omlouvám se, ale nevím o tom víc.
{17775}{17810}Nemoné...
{17810}{17856}Øediteli Yorgo...
{17856}{17881}Trest smrti?
{18102}{18154}U se Erenfried uklidnil?
{18154}{18227}Ano. Ange se na nìj právì teï dívá.
{18258}{18280}Yorgo...
{18680}{18774}Opravdu musíte repektovat pana Yorga, e?
{18774}{18860}Jsem tak bezmocnı...
{18890}{18992}Byl jsem na sebe pyšnı, e jsem byl èlenem Foundation.
{19026}{19160}Dal mi domov, Foundation, a zpøístupnil mi mé vlastní zkoumání.
{19160}{19251}A aèkoli jsem kvùli tomu dìlal co jsem mohl...
{19271}{19338}Ale to já jsem ho dostal do tìch problémù!
{19365}{19496}A byla moje chyba, e byla Foundation zavøena a øeditel Yorgo zatèen!
{19515}{19584}Trest smrti... To je...
{19584}{19618}Erenfriede-san...
{19819}{19888}Vzchopte se!
{19888}{19984}Nic nezachráníte, pokud tu jen budete plakat!
{20044}{20148}Ale co mám dìlat, Angelique?
{20175}{20224}Co chcete udìlat?
{20241}{20294}Co já... chci udìlat?
{20354}{20422}Ano! Zamyslete se nad tím!
{20459}{20474}Já...
{20537}{20579}Chci zachránit øeditele Yorga.
{20598}{20669}Chci najít zpùsob, jak zastavit úèinky èipu.
{20693}{20793}Pak je to to,co byste mìl teï udìlat.
{20793}{20871}Myslete na to, e to udìláme spoleènì!
{20871}{20942}Co bych mìl teï dìlat...
{20942}{21022}Co bych... mìl teï dìlat...
{21108}{21136}Erenfriede-san!
{21153}{21201}Jste unáhlenı! V takovém stavu nemùete odejít!
{21201}{21248}Nezáleí mi na mém zdraví!
{21248}{21300}Musím rychle zachránit øeditele Yorga!
{21300}{21335}Yorga?
{21335}{21348}Teï?
{21348}{21399}Ano! Nezastavíte mì!
{21428}{21439}Nech mì jít!
{21455}{21524}Ne. Nemùu tì nechat jít.
{21524}{21584}To je pravda, u je pozdì.
{21584}{21634}Je nebezpeèné cestovat v noci.
{21634}{21681}A taky je to ve snìhu tìší.
{21697}{21765}Erenfriede, uklidnìte se!
{21765}{21864}Kdo zachrání øeditele Yorga, kdy budete mít nehodu?!
{21911}{21952}Stále bys mìl odpoèívat.
{21973}{22037}Zítra vymyslíme plán akce.
{22124}{22178}Vrate se do pokoje!
{22238}{22283}Je tu chladno, ne?
{22283}{22317}Znovu zatopím!
{22331}{22354}Angelique.
{22384}{22451}Musím se ti omluvit.
{22485}{22548}Vím, e omluva nic nevyøeší...
{22564}{22653}Byl jsem na tebe krutı...
{22671}{22699}Omlouvám se.
{22699}{22733}Erenfriede-san...
{22755}{22848}Umím dìlat jen nenapravitelné vìci!
{22848}{22867}Jsem...
{22935}{22965}Angelique...
{23398}{23419}Já...
{24202}{24256}Vìdìl jsem, e budeš chtít utéct.
{24283}{24314}Profesore Rayne!
{24326}{24360}Je zbyteèné mì zastavovat.
{24380}{24463}Nesu odpovìdnost, za to, co jsem udìlal.
{24463}{24552}Napsal jsem ti krátkou trasu do Wodon.
{24552}{24581}Profesore Rayne...
{24595}{24684}Teï nemùu zbloudit ze strany Ange.
{24684}{24757}Nevíme, kdy ji nakonec Erbos napadne.
{24809}{24836}Nechávám Yorga na tobì.
{25485}{25509}Poèkejte!
{25526}{25544}Ty...
{25619}{25692}Nemyslíš, e je nezodpovìdné jít sám?
{25723}{25774}Nech mì bıt.
{25792}{25849}Opravdu si myslíš, e nìco mùeš udìlat?
{25849}{25907}Nenapadá mì, co øíct.
{25907}{25940}To je pravda...
{25970}{26075}Ale nejsi jedinı, kdo chce Mathiase zmìnit.
{26088}{26109}Já také.
{26148}{26250}Moná z nìj tohle udìlal ten èip...
{26250}{26343}Ale jsem jedinı, kdo mùe vstoupit za jeho zeï.
{26403}{26454}Nìco s tím udìlám.
{26485}{26568}To je to, proè jdu zachránit øeditele Yorga.
{26602}{26647}Opravdu tam jdeš?
{26681}{26714}Nevzdám to.
{26737}{26789}Vím, co musím udìlat.
{26789}{26821}Co musíš udìlat?
{26910}{26942}To je "nosiè-štìstí".
{26942}{26985}Mùe ti bıt uiteènı.
{27006}{27056}Dobøe...
{27073}{27096}Dávej pozor.
{27116}{27133}Dìkuju.
{27157}{27187}Toto je pro mì poprvé.
{27233}{27309}Kolem mì byli do teï jen samí dospìlí.
{27335}{27357}Kolem mì taky.
{27546}{27568}René-san!
{27632}{27649}Erene...
{27665}{27732}Doufám, e se mu bìhem cesty nic nestane.
{27744}{27790}Bude v poøádku.
{27864}{27947}Jde udìlat, co musí.
{27947}{27975}Take...
{28007}{28043}U nikdy neuteèu.
{28094}{28139}Budu dìlat, co musím.
{28175}{28238}Touil jsem po venkovním svìtì, ale...
{28238}{28293}Uvìdomil jsem si to.
{28318}{28357}Stále mám co zanechat.
{28378}{28396}René-sama...
{28408}{28479}Jsem si jistá, e budeš v poøádku, kdy pùjdeš po cestì, kterou si vybereš!
{28506}{28537}Vrátím se do Holy Capital.
{28556}{28611}A budu Head Order z Celestizamu.
{28650}{28685}Zachráním Mathiase!
{28702}{28748}Zachráním Nyxe-san!
{28748}{28828}Tohle je mùj zpùsob záchrany Arcadie!
{28842}{28919}Budu tì podporovat, jak jen budu moct, Angelique.
{28941}{28968}René-san!
{29160}{29203}Giant Silver Tree zaèal vadnout.
{29240}{29321}Taky jsem neklidná.
{29352}{29428}Silver Tree je spojenı se vším ivım.
{29450}{29559}A protoe vadne, ivotní síla Arcadie klesá.
{29592}{29673}Já, Head Order, jsem jedinı, kdo dokáe Silver Tree zachránit!
{29693}{29748}Vracíme se do Holy Capital!
{29748}{29824}Ano! Vìdìl jsem, e to øekneš!
{29824}{29885}Pùjdeme s tebou, kam budeš chtít.
{29885}{29935}Ochráníme vás.
{30015}{30056}Prosím, nechte mì jít taky.
{30056}{30090}Bernarde-niisan!
{30090}{30178}Je mojí prací sepsat všechno, co se od teï stane.
{30195}{30233}Chci bıt svìdkem a do konce.
{30248}{30265}Dobøe.
{30300}{30326}Angelique.
{31450}{31468}Kde...
{31499}{31524}chci jít?
{31757}{31787}Nyxi-san...
{31787}{31860}Zachráním vás!
{31988}{32173}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32253}{32444}www.mycolorfullife.blog.cz
