{1}{1}23.976
{70}{121}Brzo budeme v Holy Capital, ne?
{121}{130}Ano.
{151}{242}Musím ti to pøipomenout, ne pøijdeme do Holy Capital, Angelique.
{284}{365}Rozhodnì tam teï nejsi vítána.
{391}{434}Erbos tì sleduje...
{635}{735}TaSHee's Gang uvádí
{981}{1061}NEO ANGELIQUE ABYSS|SECOND AGE
{3040}{3115}CENA ZA ZLOÈIN
{3351}{3373}Proè?
{3399}{3445}Mìsto je tak tiché...
{3445}{3518}Ale proè se cítím jako by mé srdce bylo roztreno?
{3573}{3613}Osamìlı král...
{3633}{3714}Je víc jako Thanatos, ne jako lidská bytost.
{3714}{3785}Má stále víru ve své schopnosti?
{3785}{3841}Nebo taky sám sebe podezøívá...
{3869}{3911}Proè jsem tam zmatenı?
{3932}{4005}Holy Capital je v mıch rukou.
{4032}{4053}Ale to je vše.
{4207}{4223}René!
{4383}{4456}Krásnı noèní vıjev se nezmìnil.
{4472}{4562}Ale proè to se mnou nic nedìlá?
{4562}{4655}Holy Capital je smyslem mého ivota...
{4670}{4697}Nebo ne?
{5015}{5149}Erbos pøišel z pradávnıch èasù, aby pøinesl |Arcadii katastrofu. Je opravdové zlo.
{5165}{5264}Ale jsou tu další, kteøí pomáhají jeho síle rùst.
{5287}{5353}Jsou jako Angelique...
{5353}{5440}Dívky, které vìøí, e se stanou Královnou a zachrání svìt.
{5470}{5575}Jak nestydatı úsudek. Není to vùbec pøesvìdèivé.
{5599}{5639}Cítím, e je to rozumné.
{5674}{5762}Dal jsem zkoumat Queen's Egg v minulosti.
{5762}{5879}Slyšel jsem ve vesnicích zvìsti a èetl pøíbìhy v novinách.
{5879}{5972}Je tu mnoho magickıch dívek jako právì teï Ange.
{6006}{6129}Jako Angelique, všechny z nich vlastní silné oèistné schopnosti.
{6156}{6287}Tak se zamìøily na to, aby se staly Královnou a pøinesly svìtu záchranu.
{6309}{6443}Zøejmì, co je èeká... je krutı osud.
{6473}{6555}Nìkteré z nich byly oznaèeny za zrùdu a zabity.
{6638}{6726}Nìkteré z nich byly zrazeny pøáteli.
{6743}{6850}Jsou tu další, které nemìly dost sil.
{6941}{7071}Erbose pøitahovalo jejich zoufalství a stával se silnìjším a silnìjším.
{7071}{7251}Teï je to dost jasné. To je opravdovı Erbosùv dùvod napadat Arcadii.
{7251}{7401}Erbos udruje svùj ivot bìhem dívèiny touhy, zlosti a nenávisti a do konce jejich ivota.
{7412}{7524}Riskují své ivoty pro Arcadii a bojují s Erbosem.
{7524}{7640}Ale jsou pro Erbose vlastnì vıhodou.
{7657}{7705}To je kruté...
{7721}{7831}Jejich utrpení je i tvım,  e Ange?
{7901}{7935}Omlouvám se, Ange.
{7948}{8034}Nevím jak bych mohl utišit tvou bolest.
{8075}{8163}Mùu ti pouze setøít slzy.
{8190}{8216}J.D.-san...
{8239}{8291}Omlouvám se!
{8291}{8324}Jsem v poøádku!
{8343}{8378}Díkybohu.
{8378}{8467}Mùeš pokraèovat ve vyprávìní, René-san?
{8480}{8492}Ano.
{8616}{8633}Kdo je tam?
{8789}{8810}Objevil mì!
{9195}{9270}Zloèin, kterı jsem spáchal...
{9296}{9364}Tohle je cena za nìj?
{9379}{9403}Proè ne?
{9419}{9519}Nic mì nemùe obtìovat dokud nesu tíhu trestu.
{9543}{9636}Erbosovım jedinım cílem je napadení Queen's Egg.
{9652}{9741}Co prokáe, e se Královna narodí v Arcadii.
{9788}{9844}Erbos je znepokojenı.
{9860}{9975}Musíš pøekonat mnoho pøekáek, Angelique. |Brzy budeš opravdová Královna.
{10011}{10086}Ale svìt pohltil chaos kvùli mì...
{10086}{10113}To není pravda.
{10130}{10188}Arcadia potøebuje Královnu.
{10198}{10291}Jednou bude Erbos znièen a znovu bude vládnout mír.
{10307}{10400}Bez Královny by poøádek svìta nikdy nebyl udrován.
{10400}{10478}A u bude znièen døíve nebo pozdìji.
{10492}{10568}Erbos je slouèením všech zlıch myšlenek.
{10568}{10634}Nemá tìlo.
{10634}{10700}Zmìnil Nyxe na svého hostitele.
{10700}{10826}Queen's Egg Angelique zachrání svìt.
{10882}{11035}Hledal jsem tì, protoe jsem doufal, e ukonèíš |mùj osud v tomto nesmrtelném tìle.
{11068}{11145}Nyx-san bojoval s Erbosem kadı den...
{11145}{11230}Ale teï je jeho vìdomí kompletnì ovládáno Erbosem.
{11254}{11313}Ale kde je skuteèné Erbosovo tìlo?
{11343}{11392}To je nevyøešená hádanka.
{11420}{11470}Nechci na tebe tìmito slovy tlaèit, ale...
{11491}{11530}je to tvùj osud.
{11569}{11599}Ano.
{11814}{11829}On...
{11856}{11927}Zdál se bıt utrápenı za to, co udìlal.
{11951}{12013}Moná je to monost ukonèit bitvu, Ange.
{12134}{12189}Myslím, e je skvìlé tì vidìt.
{12201}{12264}Ty malá kryso.
{12278}{12307}Nyx!
{12339}{12427}Promiò, ale nemám èas se tebou zabıvat.
{12427}{12493}Jsem na cestì na rande s Ange.
{12618}{12664}Pak prosím rande zruš.
{12680}{12785}Chci znièit Mathiase a Angelique spoleènì.
{12797}{12826}Oh ty...
{12883}{12969}Nevím co se stalo po tom, co jsme odešli.
{12985}{13021}Pevnì vìøím, e...
{13021}{13140}lidé mají právo znát pravdu a jsou, kde jsou.
{13140}{13235}Take musím splnit svou povinnost a nechat je to vidìt.
{13235}{13259}Bernarde-niisan!
{13281}{13314}Pojïme, Ange.
{13339}{13357}Ano!
{13482}{13531}Musím pøesvìdèit Mathiase a pøivést ho k rozumu.
{13557}{13621}A oba obnovíme Holy Capital do pùvodní formy.
{13634}{13714}Všechno zaznamenám ve Wodon Times.
{13714}{13830}Nechám lidi, aby vìdìli, e Queen's Egg je zdravá a v bezpeèí.
{13830}{13938}A znovu pøinese nadìji do srdcí obyvatel Arcadie.
{14136}{14212}Nezáleí na tom co se stane, ochráníme Ange!
{14212}{14280}A pak zachráníme Nyxe od Erbose!
{14340}{14362}Nyxi-san...
{14587}{14628}Je to nelehké, e?
{14646}{14737}Pamatuj si to, ty nesmrtelná kreaturo.
{14737}{14866}Nikdy se nehádej s malou krysou!
{14922}{14984}To staèí. Co kdybys to vzdal?
{14984}{15131}Èelící mocnému soupeøi... Ten bez schopností| by si mìl lehnout na bøicho.
{15203}{15245}Promiò, to není moje ivotní filozofie.
{15339}{15405}Je pravda, e nemáme ádné schopnosti.
{15420}{15586}Podívej se na sebe, potuluješ se kolem |za úèelem záchrany svého ivota.
{15586}{15616}Ale...
{15616}{15831}My stále vìøíme! Dìláme co mùeme, nezáleí jakım pøekákám èelíme. Mùeme mít krásnı zítøek.
{15883}{15934}Ale ty u nebudeš mít ádnı zítøek.
{15934}{16042}Jen takovı cvok jako ty, by mohl chtít znièit tak jednoduché pøání!
{16057}{16095}Znièím tì!
{16217}{16317}Vytvoøit svìt, kde nikdo nebude zranìn.
{16317}{16378}Ange mi to slíbila!
{16378}{16457}Tak jsem se jí rozhodl pomoct, jak jen mùu!
{16528}{16598}Dobøe... To je konec?!
{16972}{17043}Silver Tree se trápí kvùli mì.
{17099}{17122}René-san...
{17142}{17232}Bude to v poøádku. Silver Tree brzy obnoví svou slávu.
{17232}{17375}Tak dìlejme co mùeme, abychom obnovili |nìkdejší svìt. A pak bude...
{17395}{17413}Ano...
{17464}{17511}Chci se stát Královnou.
{17511}{17577}U je èas øíct sbohem.
{17577}{17607}Ange.
{17631}{17722}Naše srdce budou stále s vámi, Angelique.
{17722}{17822}Kdy se mír vrátí na tento svìt, budeme spolu navdy.
{17839}{17954}Ano. Kdy budeš Královnou, budeme stále na tvé stranì.
{17967}{17998}Tak nás neodmítej.
{18025}{18040}Ano.
{18064}{18078}Ange...
{18107}{18175}Jsem šastná za tvou laskavost.
{18203}{18243}Ale jsem....
{18328}{18347}Co je to?
{18368}{18464}Proè jsi neøekla ostatním, e jdeš do Sacred Land sama?
{18485}{18612}Nìco je skryto v tvıch pøátelích, Queen's Egg.
{18612}{18732}Sdílíš stejnı osud jako my.
{18774}{18790}Ne!
{18873}{18896}Dost!
{18931}{18959}Ange!
{19005}{19050}Co se dìje, Ange?
{19110}{19157}Byla to iluze?
{19232}{19353}Neuvìdomil jsem si, e jste se dostali do Holy Capital.
{19501}{19519}Angelique.
{19582}{19612}Co se stalo?
{19759}{19840}Chci to víc, ne svùj ivot.
{19860}{19939}Angelique je právì u Silver Tree.
{19939}{19969}Rychle ji najdi.
{20076}{20124}Silver Tree?
{20145}{20285}Ange, zdá se, e jen ty mùeš zachránit Nyxe.
{20445}{20486}Všichni, slote zbranì!
{20505}{20538}René-sama!
{20538}{20554}Mathiasi.
{20580}{20629}Jsem tu, abych se ti omluvil.
{20655}{20699}Omluvil? Mì?
{20722}{20854}Po dlouhı èas, jsem myslel jen na sebe a svùj osud.
{20906}{20962}Nemùu zapomenout své chyby...
{20962}{21017}Tak co teï mùu udìlat...
{21070}{21132}Je tu spousta vìcí, které nevím.
{21132}{21228}Mùeš bıt znovu mım uèitelem a vést mì?
{21228}{21249}René...
{21393}{21434}Nemùu se vrátit.
{21453}{21479}Mathiasi!
{21536}{21551}René-sama!
{21692}{21709}Hyuugo!
{21791}{21802}Co?!
{21821}{21883}Mìl bys zmizet!
{21927}{21971}Ne! Ange!
{22074}{22100}J.D.-san!
{22121}{22191}Nechci nikomu ublíit!
{22512}{22525}Ange!
{22579}{22616}Bernarde-niisan!
{22636}{22694}Nejsi zranìná, Ange?
{22694}{22722}Ne!
{22722}{22756}Díkybohu...
{22756}{22821}Budu tvım štítem...
{22846}{22871}Bernarde-niisan!
{22975}{22999}Mathiasi!
{23040}{23053}René.
{23080}{23099}Sakra!
{23099}{23165}Ne... Nemùu to tak nechat!
{23207}{23223}Mathiasi-sama?
{23245}{23347}René... Všechny ty høíchy... Znièím je!
{23404}{23455}Pøinejmenším to ukonèím...
{23642}{23661}Pøestaò!
{23676}{23752}Tahle bitva nemá smysl!
{23766}{23795}Roche!
{23817}{23836}Máš pravdu!
{23853}{23896}Nestùj v cestì!
{24080}{24094}Mathiasi!
{24143}{24173}Mathiasi...
{24174}{24230}To je jeho limit.
{24252}{24329}Mathiasi, ádám tì. Zastav to!
{24392}{24431}Budu mít list ze Silver Tree!
{24431}{24461}Mathiasi!
{24461}{24549}Stop! Jste vánì zranìnı! Nedìlejte to!
{24571}{24650}Ale kdy to dostanu, mohl bych prokázat, e jsem opravdovı Order!
{24838}{24894}Díky tomu, mùu...
{25014}{25075}Silver Tree pláèe?
{25096}{25217}Proè? Proè si mì Holy Capital nevybralo?
{25502}{25549}Ustupte, René-sama!
{25569}{25599}Nepøibliuj se k Mathiasovi!
{25729}{25746}René-sama!
{25762}{25784}Co to dìláš?!
{25784}{25907}Není to jeho chyba, ale moje. Já jsem Head Order!
{25920}{25968}Ponesu jeho høíchy!
{26021}{26047}Proè?
{26094}{26224}Po tom, co jsem odešel z Celestizamu. Cítil jsem, |e èelím svému ivotu poprvé tak vánì.
{26241}{26277}Koneènì jsem si uvìdomil, e mùj úkol je...
{26300}{26403}A taky jsem se rozhodl. Nemùu utéct z reality.
{26403}{26504}Jako Head Order vrátím svìt do pùvodního stavu!
{26517}{26537}René...
{26537}{26621}Nemùu dovolit, aby se tahle tragédie znovu opakovala.
{26621}{26696}Zmìním Organizaci!
{26813}{26933}Myslel jsem si, e má existence je zbyteèná...
{26948}{26965}Ale...
{27617}{27699}Budeš stále na mé stranì, e?
{27713}{27794}Mùu dosáhnout èehokoli dokud jsi se mnou.
{27868}{27940}René... Dítì vyuèeno mnou...
{27971}{28006}Je smyslem mého ivota.
{28026}{28088}A teï je pøede mnou.
{28142}{28222}Chci zachránit Arcadii, Mathiasi.
{28244}{28278}Pomùeš mi?
{28298}{28420}Ale spáchal jsem mnoho zloèinù.
{28435}{28504}Jedinı zpùsob, jak je odpykat, je smrt.
{28533}{28594}Neøíkejte to.
{28611}{28725}Nevímv jak bych to mohla ukonèit... Nemùu to vyøešit lepším zpùsobem.
{28725}{28806}Ale... ádám vás, zùstaòte tady!
{28806}{28890}Zùstaòte vdycky na Reného-san stranì!
{28907}{28929}Prosím!
{28948}{28977}Angelique...
{29036}{29137}René-sama, nechte mì poskytnout Arcadii...
{29152}{29248}Aèkoli je mé tìlo plné høíchù a mùj ivot se rozpadá...
{29268}{29286}Rozumím.
{29329}{29355}Angelique!
{29380}{29410}Slibuju.
{29427}{29501}Jako Head Order ti dávám mou plnou dùvìru.
{29501}{29522}René-san!
{29541}{29672}Myslím, e jsme v nìèem podobní, Angelique.
{29799}{29848}Oba jsme ztratili naše domovy...
{29848}{29978}Ale ty jsi nikdy neskrıvala nenávist k ubliování lidem.
{29978}{30128}Ne. Kdy jsem ztratila Sunlit Mansion, byla jsem uvìznìna v beznadìji.
{30128}{30266}Nicménì je to pryè. Uvìdomila jsem si, e je mi nìco draší...
{30411}{30435}A...
{30580}{30725}Mathias a všichni jsou zdraví a v bezpeèí. To je pro mì to nejlepší.
{30741}{30811}Tomu rozumím.
{30811}{30989}Èas, kterı jsem strávil s Reném a ostatními v Holy Capital se nedá nahradit.
{31171}{31231}Jsi zrádce, Mathiasi!
{31372}{31404}Nyxi-san...
{31429}{31525}No, nemìl by se's tìšit na nic.
{31782}{31916}Zatanèeme si poslední waltz, Mademoiselle.
{32004}{32123}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32201}{32312}www.mycolorfullife.blog.cz
