{1}{1}23.976
{1}{127}Zatanèeme si poslední waltz, Mademoiselle.
{181}{197}Nyxi!
{567}{598}Proè to dìláš?!
{598}{632}Nech toho!
{632}{676}Ještì nás nepoznáváš?
{688}{722}To je zbyteèné.
{722}{775}Je pod Erbosovou kontrolou.
{775}{824}Naše hlasy k nìmu nedosáhnou.
{857}{911}Díky za vaše pochopení!
{911}{976}Nicménì, nemám náladu si s vámi povídat.
{994}{1109}Take Mathiasi, zradil jsi mì, take je èas za to zaplatit.
{1149}{1276}Take zaènu nièit místo, které máš na svìtì nejradìji.
{1747}{1803}Holy Capital... bude znièeno!
{1853}{1958}Prosím Mathiasi, naposledy se podívej na své Holy Capital.
{1980}{2004}Jak kruté!
{2078}{2179}TaSHee's Gang uvádí
{2417}{2499}NEO ANGELIQUE ABYSS|SECOND AGE
{4485}{4536}OSPALİ CELESTIZAM
{4639}{4719}To je cena za tvùj zloèin.
{4733}{4877}Ten kdo pøinesl Holy Capital katastrofu, uvidí jak |mìsto lehne popelem, na vlastní oèi.
{4890}{4925}Mathiasi...
{4931}{4981}Zùstal jsi jako z kamene...
{4981}{5047}Jsi k tomu opravdu tak lhostejnı?
{5132}{5252}Já... najednou. Nemohl bych nic vidìt.
{5252}{5287}A cítil jsem, e mé srdce pøestalo bít.
{5309}{5359}Ale teï je to jiné...
{5397}{5479}Kdy jsem byl s Reném...
{5495}{5630}Vìci, které jsem vidìl v míru a Holy Capital pøetékalo vitalitou.
{5720}{5781}Holy Capital je mojí nejvìtší láskou!
{5781}{5816}Nedovolím ti se do toho vloit!
{5946}{5966}Imbecile.
{6089}{6113}Mathiasi!
{6194}{6330}Schopnosti vyrobené Foundation na mì nemají ádnı efekt.
{6330}{6378}Zùstaòte vzadu!
{6394}{6462}Vemte Mathiase-dono daleko odsud, René-sama!
{6570}{6642}Jsi stále naivu, Mathiasi.
{6642}{6711}Moná zemøeš po tom, co uvidíš znièení tohoto místa.
{6711}{6759}Nenechám tì to udìlat!
{6820}{6858}Kam se to díváš?
{6969}{6993}Oh, ty!
{7028}{7141}Jestli mì zabijete váš pøítel Nyx zemøe taky.
{7558}{7621}Proè nejsou vaše útoky upøímné?
{7638}{7673}Vypadáte tak odvánì...
{7673}{7758}Ale chcete se mnou bojovat?
{7800}{7824}Jste nerozhodní.
{7833}{7917}Tak vás znièím jednoho po druhém.
{8196}{8235}Zaènìme u Head Ordera,
{8235}{8269}abychom oslavili jeho nastolení!
{8342}{8355}René!
{8920}{8966}Jsem si jistı, e jsem ti to øekl..
{8966}{9052}Nenechám tì to znièit pøed mıma oèima...
{9110}{9137}Mathiasi...
{9174}{9190}Mathiasi!
{9256}{9294}Jak jste to mohl udìlat?!
{9294}{9319}Mathiasi-dono!
{9360}{9388}Co si myslíte?
{9403}{9450}Pouze zemøel o trochu døív ne se oèekávalo.
{9475}{9496}Ne...
{9518}{9558}Mathias-sama je...
{9767}{9834}Nakonec... Mìl bıt stále naivu.
{9850}{9906}Jak komické...
{9906}{10043}Mìl kurá, kdy si myslel, e mì mùe oklamat. Zvláš po tom, co pøísahal oddanost tomu mladému mui.
{10074}{10096}Ticho!
{10175}{10186}Erbosi...
{10309}{10461}Mathias-sama byl vdy kontrolován jinımi. |Nakonec si uvìdomil svùj skuteènı osud, ale...
{10492}{10580}Ten mu odhodil své tìlo i duši!
{10580}{10637}To je osud, kterı chtìl.
{10651}{10663}Neodpustitelné!
{10815}{10854}Jak mocné!
{10925}{11001}Angelique, pøíštì si vyrovnáme úèty!
{11238}{11257}Thanatosové jsou...
{11294}{11322}Mizí...
{11518}{11533}Ange!
{11533}{11551}Jsi v poøádku?
{11621}{11637}Ano...
{11734}{11766}Mathiasi!
{11846}{11878}Probuïte se, prosím!
{11878}{11928}Vyléèím vás!
{11928}{11960}Angelique...
{11975}{11991}Zbyteèné.
{12032}{12078}To ten èip.
{12078}{12137}Byl velkou námahou pro jeho tìlo.
{12137}{12163}Nemoné!
{12179}{12263}Neupouštìj mì! Neopouštìj mì, Mathiasi!
{12287}{12400}Budeš stále na mé stranì, ne?
{12580}{12672}Od teï mì musíš podporovat!
{12672}{12694}René...
{12717}{12761}Tohle je souèást ivota...
{12774}{12837}Øekl jsi si, e odsud nemùu utéct,ne?
{12837}{12861}Ale...
{12878}{12948}Ale bez tebe nemùu nic vrátit!
{12981}{13018}Špatnì.
{13046}{13188}Pøesvìdèil jsi mì, e budeš skvìlım Orderem, to mì utìšuje.
{13206}{13223}A tohle...
{13280}{13321}Vracím vlastníkovi.
{13490}{13570}Jsi skuteènı Head Order...
{13570}{13602}Mathiasi!
{13718}{13780}René... Dìkuju.
{13915}{14016}To ty jsi mi dal...
{14050}{14080}smysl mého ivota.
{14291}{14386}Mathiasi!
{14567}{14602}René-sama.
{14615}{14635}Ehm...
{14665}{14684}Jsem v poøádku.
{14728}{14812}Bitva s Erbosem skonèila remízou.
{14812}{14861}Udìlám to, co musím.
{14861}{14886}René-san...
{14906}{14981}Mathias bude spokojenı, kdy to udìlám.
{15033}{15099}Vrátím tento klíè na to místo.
{15116}{15164}A vím, jak toho dosáhnu.
{15428}{15475}Kdy stíny pokryjí svìt,
{15489}{15522}vezmi tento klíè.
{15535}{15583}Z velkého mìsta u moøe,
{15583}{15629}a dosáhneš vrchoviny,
{15648}{15692}tak vyslanec Svìtla...
{15692}{15775}zapoène svou cestu a odstraní koøeny temnoty.
{15886}{15925}Co se stalo?
{15925}{15993}Velké mìsto u moøe...
{16019}{16033}Pharian!
{16058}{16167}To místo je koøenem temnoty. Tam by mìlo bıt doupì Erbose, ne?
{16186}{16197}Ano.
{16232}{16262}Ale co máme dìlat?
{16281}{16313}Je to jasné.
{16356}{16386}Stellar Vessel!
{16402}{16442}Nakonec odjídíme.
{16442}{16467}Ano.
{16467}{16485}Kde je Ange?
{16497}{16557}Šla se rozlouèit s Reném.
{16557}{16629}Jen tak se nevrátíme.
{16660}{16697}Zùstanu tady.
{16718}{16855}Musím ochránit Arcadii a bıt Head Orderem za pomocí Silver Tree.
{16912}{16970}To je klíè k aktivování Stellar Vessel.
{17051}{17167}Koneènì znièím Erbose a stanu se Královnou.
{17183}{17322}A budeš Královnou, jako Head Order ti musím popøát vše nejlepší.
{17322}{17339}Ale...
{17419}{17471}Nemùu se za tebe modlit z hlouby mého srdce!
{17484}{17642}Kdy vidím nìkoho tak vzácného jako jsi ty, Angelique. Nemùu to pøijmout.
{17795}{17814}René-san!
{17885}{17922}Nespìchej, Ange!
{17968}{18033}U je èas, abys o tom všem øekla.
{18071}{18131}Brzy budete rozdìleni.
{18145}{18162}Ano...
{18183}{18277}Nikdo kromì tebe nemùe vstoupit do Sacred Land.
{18277}{18377}Budeš se modlit sama na dalekém místì po dlouhou dobu.
{18636}{18685}Dìje se nìco, Ange?
{18685}{18705}Ne!
{18718}{18769}Aha... Vıbornì.
{18852}{18913}Tahle vesnice je opuštìná.
{18934}{18971}Za to mùou bezpochyby Thanatosové.
{18983}{19106}Ale jestli najdeme jídlo a vodu, odpoèineme si tady.
{19131}{19149}Koèka!
{19221}{19252}Máš rád koèky?
{19252}{19285}Ano, hodnì!
{19317}{19362}Dìti jsou tak nevinné.
{19362}{19426}Podívejte! Queen's Egg!
{19443}{19500}Proè jste tady?
{19555}{19617}Ztratili jsme naši rodinu a pøátele
{19617}{19659}kvùli vám!
{19690}{19745}Hej! Jak to mùete øíct?
{19745}{19803}Ona dìlá co mùe jako Queen's Egg!
{19803}{19905}Queen's Egg nepøišla, kdy jsme ji potøebovali!
{19905}{19986}Dali jste nám jen falešné nadìje!
{19986}{20049}Tak to není! Ona...
{20049}{20099}Odejdìte odsud!
{20099}{20148}U vás nechci vidìt!
{20148}{20172}Odejdìte!
{20272}{20290}Sakra!
{20337}{20424}Neznepokojuj se tím, Ange.
{20445}{20488}Bylo jim hodnì ublíeno...
{20511}{20542}Já vím.
{20542}{20571}Ale kvùli tomu...
{20571}{20659}Se stanu Královnou a zachráním Arcadii.
{20775}{20801}Nikdo tu není.
{20801}{20871}Moná šli hledat útoèistì.
{20871}{20918}Koneènì jste tady.
{20937}{20949}Ty!
{20968}{21009}Erenfriede!
{21009}{21053}Oèekával jsem vás.
{21129}{21199}Vìc kterou hledáte, je tady.
{21240}{21267}Dívejte se dobøe.
{21349}{21407}Vìdìl jsem to... Stellar Vessel!
{21421}{21465}Opravil jsi ji?
{21479}{21608}Dostal jsem dopis z Organizace, kterı øíkal, |e vlastníte klíè k aktivaci Stellar Vessel.
{21624}{21679}Vlastnì je v poslední fázi pøíprav.
{21692}{21751}Brzo bude moct vzlétnout.
{21751}{21797}Jste pøekvapení?
{21857}{21925}U je to dlouho, Rayne.
{21959}{22003}Jsi naivu.
{22038}{22073}Mathias je...
{22073}{22138}Ano... Chtìl ochránit Reného-san.
{22138}{22232}Nemoné! Mìl jsem to zastavit!
{22256}{22283}Bylo to pozdì.
{22296}{22481}V porovnání s vırobou èipu, byla oprava lodi |hlavní prioritou. Dal jsem ti takovı pøíkaz.
{22525}{22595}Znièení Erbose je našim jedinım pøáním,
{22595}{22671}tak jsme opravili Stellar Vessel.
{22671}{22691}Øediteli Yorgo...
{22702}{22873}Stellar Vessel je legendární artefakt vyrobená |k plavbì mezi galaxiemi v pradávnıch dobách.
{22873}{22993}Stellar Vessel je pøedurèena k záchranì Arcadie a já v to vìøím.
{23006}{23041}To proto...
{23041}{23156}jsem pracovali na opravì s pomocí Foundation.
{23156}{23230}Mùeme ji vzít a najít Erbosovo doupì.
{23230}{23283}Jaká je situace?
{23283}{23351}Stellar Vessel je starı typ artefaktu.
{23351}{23463}Našim technologiím trvalo dlouho, ne ji analyzovali, proto je pokrok tìkı.
{23463}{23488}Aha.
{23516}{23628}Ale tentokrát, musí Foundation Arcadii ochránit.
{23628}{23691}Udìlám co mùu, abych ji opravil a se dìje cokoli!
{23691}{23729}Také pro Mathiase-dono!
{23768}{23822}Pomùeš nám, Rayne?
{23940}{23951}Ano.
{23966}{24016}Jestli je nìco,co mùeme udìlat...
{24016}{24043}Pomùeme.
{24196}{24236}Mùu to vzít?
{24236}{24288}D-Dìkuji, e nám pomáháte!
{24351}{24370}Skvìle.
{24370}{24448}Svaøíme je dohromady, a pak to udìláme.
{24448}{24502}Pøiznáváme to, profesore Rayne!
{24557}{24605}Ah ne, to ne! To je...
{24628}{24645}Aha.
{24721}{24817}S pomocí profesora Rayneho se naše práce stává úèinnìjší.
{24817}{24873}Bude to hotové za pár dní!
{24909}{24959}Za... pár dní!
{24984}{25032}No, myslím si...
{25063}{25170}Aby znièili Erbose, musí do toho dát všechno, ne?
{25186}{25298}Nìjak cítím, e do té bitvy dávají všechno.
{25316}{25358}Teï je to buï a nebo...
{25376}{25445}Bez oèistnıch schopností nemáme na vıbìr, ale zùstaneme tady.
{25499}{25518}Ano.
{25554}{25590}Ange...
{25766}{25804}Erenfriede.
{25820}{25856}T-Ty!
{25905}{25930}Jete!
{25988}{26029}Proè jsi sem pøišel?
{26044}{26090}V mém systému je pár vad.
{26114}{26138}Co to øíkáš?
{26138}{26207}Kdy se podívám na tu dívku, Angelique.
{26207}{26292}Mé schopnosti splnit úkol nejsou efektivní.
{26312}{26363}To se nikdy pøedtím nestalo.
{26363}{26395}Co je to za jev?
{26466}{26507}Rozeberte mì.
{26522}{26569}Vady musíte opravit.
{26598}{26653}Øíkáš, Angelique?
{26691}{26752}Nemùu tì kvùli tomu rozebrat.
{26799}{26820}Proè?
{26857}{26926}To je srdce.
{26926}{26952}Srdce?
{26966}{27084}Vdycky jsem si myslel, e artefakty nemùou mít srdce.
{27084}{27095}Ale...
{27135}{27247}Byl to J.D., kdo mì zachránil z vìzení.
{27247}{27373}Ale to ty jsi øekl J.D., aby mì zachránil, ne?
{27392}{27467}Po tom jsem své mínìní zmìnil.
{27481}{27544}Je hezké, kdy srtefakty také mají srdce.
{27566}{27660}Od teï jednej podle své mysli a pøání.
{27660}{27712}Tak kdo je mùj pán?!
{27730}{27790}Ty sám, Jete... Ty sám.
{27857}{27971}Pomohl bys nám s opravou Stellar Vessel?
{27985}{28029}Je to pøíkaz?
{28029}{28063}Ne.
{28063}{28102}Je to jen mé pøání.
{28294}{28341}Proè je tady?
{28387}{28410}Jete!
{28410}{28436}Pomáháš nám?
{28460}{28478}Ano.
{28523}{28560}Aha!
{28560}{28616}Jsem rád, e tì tu vidím.
{28637}{28670}Není to moje povinnost.
{28670}{28712}J.D., buï opatrnı...
{28758}{28782}Jete...
{28797}{28887}Øíká se, e to bude za pár dní hotové.
{28887}{28925}Je skoro èas odejít.
{28949}{29032}Je to opravdu škoda, e s tebou Roche a já nemùeme jít.
{29048}{29117}Ale je tu nìco, co musíme udìlat.
{29117}{29242}Budeme se modlit za tvé bezpeèí pocelou dobu, |co budeš plnit svùj úkol a ne se k nám vrátíš.
{29304}{29322}Ange...
{29393}{29484}Mùj ivot s mımi pøáteli za pár dní skonèí...
{29508}{29601}Naše srdce budou stále s vámi, Angelique.
{29601}{29714}A se na svìt vrátí mír,budeme spolu ít navdy.
{29714}{29841}Ano, a budeš Královnou, budeme stále na tvé stranì.
{29841}{29874}Tak nás neodmítej!
{29898}{29986}Byla jsem s nimi tak šastná!
{30239}{30303}Oprava probíhá dobøe, Rayne?
{30320}{30340}Ano.
{30365}{30404}Dìje se nìco, Ange?
{30446}{30475}Bojíš se?
{30475}{30551}A se stane cokoli, budeme s tebou.
{30675}{30695}Omlouvám se!
{30730}{30770}Nemohla jsem vám to øíct,
{30770}{30840}ale byla jsem s vámi šastná!
{30840}{30900}Teï vám to musím øíct!
{30900}{30928}Nechci to slyšet!
{31844}{31907}Ange musí... odejít...
{32015}{32151}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32222}{32395}www.mycolorfullife.blog.cz
