{1}{1}23.976
{396}{481}TaSHee's Gang uvádí
{764}{904}NEO ANGELIQUE ABYSS|SECOND AGE
{1243}{1272}To je...
{1371}{1395}Arcadie.
{1449}{1468}Angelique.
{1823}{1864}Je Nyx tady?
{1864}{1909}Ano, bezpochyby.
{1909}{1951}Odvedl opravdu dobrou práci.
{2008}{2036}Jsem v poøádku.
{2054}{2090}Pojïme.
{2090}{2151}Naše shledání s Nyxem-san.
{2203}{2278}ARCADIA NAVÌKY
{2936}{2981}Buï opatrná, Ange.
{3010}{3032}Nebuïte nedbalí.
{3064}{3103}Musí bıt nìkde schovanı.
{3152}{3166}Pozor!
{3399}{3423}Pøátelé!
{3818}{3910}Vítej v Sunlit Mansion, Mademoiselle.
{3947}{3981}Nyxi-san...
{4139}{4174}Angelique!
{4189}{4217}Ange!
{4242}{4285}Ange! Kde jsi?!
{4712}{4737}To je...
{4827}{4900}Vrate se s námi do Arcadie, Nyxi-san!
{4919}{4995}Jsme tady, abychom vás našli!
{5022}{5070}Toto místo také náleí Arcadii.
{5199}{5274}Pro mì je tohle Utopie.
{5297}{5350}Den, kdy se mé ideály odvrátí od reality se blíí.
{5350}{5406}Nenechám vás to udìlat!
{5427}{5446}Oh?
{5460}{5544}Budu Královnou, protoe chci Arcadii ochránit!
{5613}{5647}Královna...
{5833}{5855}Angelique...
{6061}{6074}Ange...
{6088}{6151}Povìz, J.D.-san... prosím...
{6239}{6338}Rayne... Já.. nechci bıt Královnou...
{6406}{6462}Hyuugo-san, já...
{6494}{6589}Nechci jet sama do Sacred Land...
{6734}{6751}Neøíkejte to.
{6795}{6875}Má nejdraší Ange, neøíkej to.
{6927}{7009}Známe Ange víc, ne kohokoli jiného.
{7009}{7067}Nevydávej se za Angelique!
{7290}{7342}U se nemùete dávat pozor na Angelique?
{7360}{7456}Necháte ji jít samotnou do Sacred Land?
{7529}{7611}Necháte Angelique nést její odpovìdnost samotnou?
{7673}{7775}Jestli zùstaneš, mùeš opìt se všemi ít.
{7900}{7935}Pamatujete si to?
{7935}{7990}Naše drahá Sunlit Mansion...
{8003}{8074}Chcete se tam vrátit, ne?
{8182}{8290}Sunlit Mansion... Sídlo, kde všichni...
{8553}{8584}Nostalgické...
{8748}{8792}Byli jsme tam šastní...
{8909}{8944}Jestli se mùeme vrátit...
{9159}{9185}Chci se do toho domu vrátit...
{9200}{9269}Do našeho schraòovaného sídla!
{9315}{9369}Noblesse oblige.
{9402}{9500}Je høích nepouívat schopnosti, které vlastníš.
{9537}{9596}To jsem ti chtìl øíct, Angelique.
{9639}{9667}Nyxi-san...
{9770}{9871}Ange se stane Královnou, aby ochránila Arcadii!
{9923}{9970}To je její pøání.
{9970}{10076}Pøijeli jsme sem, abychom ho uskuteènili.
{10103}{10165}Nemùeme dovolit, aby nìkdo brzdil její cestu!
{10220}{10314}Nepotøebuju tuhle kopii Sunlit Mansion!
{10314}{10430}Ta opravdová je v srdci kadého z nás.
{10821}{10907}Tohle je tvá poslední monost zùstat na tomto místì, Angelique.
{11395}{11514}Dobøe. Dáme si duel, Mademoiselle.
{11649}{11697}Teï, tancuj!
{11886}{11993}Zranìná Queen's Egg by mohla bıt ještì krásnìjší.
{12063}{12111}Ještì mùeš vstát?
{12111}{12201}Vlastnì, jestli to vzdáš a zùstaneš tady, budeš ít v míru.
{12201}{12276}Šlechetnı... závazek...
{12291}{12365}Od toho momentu jsem zapoèala svou cestu.
{12365}{12480}A kvùli tomu jsem mìla monost potkat mé drahé pøátele.
{12487}{12599}Pøedpokládám, e tì tví drazí pøátelé nechají |na tomto místì samotnou, ne?
{12672}{12755}Je pravda, e budeme oddìlení.
{12755}{12879}Ale i tak, døíve nebo pozdìji....
{12879}{12955}všichni splníme naše úkoly o navrácení míru do Arcadie.
{12955}{13036}Naše srdce jsou úzce propojena.
{13074}{13103}Zní to dobøe.
{13130}{13247}Byla jsem opravdu smutná, kdy jsme ztratili Sunlit Mansion.
{13247}{13271}Ale...
{13304}{13439}Aèkoli je Sunlit Mansion pryè, stále iju spoleènì s mımi pøáteli!
{13439}{13492}Nyxi-san...
{13492}{13578}Vy jste také mùj vzácnı pøítel!
{13618}{13637}Pøítel?
{13659}{13680}Je to pravda!
{13711}{13735}Pøátelé!
{13757}{13806}Ty jsi také náš pøítel, Nyxi!
{13806}{13904}Ano! Teï... a navdy!
{13915}{13996}Nezáleí na tom, jestli ijeme v Sunlit Mansion nebo ne!
{14023}{14106}Spáchal jsem mnoho høíchù...
{14128}{14209}A stále mì uznáváte za svého pøítele?
{14260}{14358}Pan Nyx je pro mì dùleitı.
{14377}{14458}Dal mi dùleitou vìc.
{14458}{14515}Od teï je to má cesta!
{14541}{14588}To je... moje?
{14636}{14776}Nyxùv smutek a Erbosovy zloèiny... nechte mì je nést.
{14776}{14928}Nechte mì ochránit naši krásnou Arcadii!
{14965}{15029}Naši krásnou Arcadii...
{15106}{15134}Nyxi-san!
{15158}{15234}Arcadia musí bıt znièena!
{15263}{15279}Ange!
{15540}{15560}Nyxi!
{15560}{15588}Ta pøemìna...
{15610}{15667}Vzdej se mi, Arcadie.
{15667}{15716}Nech mì trpìt v agónii
{15735}{15787}a zmìò mì do této formy.
{15811}{15841}Ty dívky...
{16016}{16042}Nyxi-san...
{16074}{16123}Je absolutnì pod Erbosovou kontrolou.
{16237}{16292}Oèistím tì, Erbosi!
{16321}{16399}Nenechám tì nikoho zranit!
{16419}{16480}Nevzdávejte to, Nyxi-san!
{16480}{16523}Bojujte s námi!
{16523}{16587}Nepodléhejte Erbosovì kontrole!
{16587}{16648}Vrame se spoleènì, Nyxi!
{16648}{16681}Vra se  k nám!
{16681}{16718}Do naší Arcadie!
{16718}{16840}Myslíte si, e mì mùete ohrozit?
{16840}{16908}Vra nám Nyxe-san, Erbosi!
{16922}{17044}Právì teï všechno znièím! Vás i Arcadii!
{17148}{17163}Pøátelé!
{17204}{17230}Vra se!
{17230}{17276}K nám!
{17288}{17346}Nech bıt svou nenávist!
{17426}{17482}Znièím tì! Queen's Egg!
{17566}{17634}Nenechám tì to udìlat.
{17662}{17681}Angelique!
{17681}{17713}Nyxi-san!
{18327}{18356}Oh, Svìtlo Oèisty...
{18386}{18462}prosím, dej všem své vøelé poehnání.
{19051}{19107}Sbohem, Erbosi.
{19230}{19406}Na tuto chvíli jsem èekal tak dlouho.. potulující se ve vìzení èasu.
{19436}{19495}Dìkuji, Angelique.
{19495}{19531}Teï mùu odejít.
{19531}{19551}Ne.
{19577}{19650}ijte, Nyxi-san.
{19650}{19792}Bıt iv 200 let... nemùu vydret více bolesti.
{19792}{19825}Tak to není.
{19840}{19907}ijte pro štìstí.
{20008}{20035}Angelique...
{20091}{20144}Jednou se opìt shledáme.
{20258}{20284}Ty jsi...
{20554}{20568}Ange!
{20568}{20612}Kam šel Nyx?
{20690}{20760}Je v poøádku.
{20873}{20889}Ty...
{20889}{20924}Co tu dìláš?
{20956}{20975}Erwine!
{21191}{21224}Tohle místo je...
{21294}{21335}Angelique.
{21335}{21367}Vy jste...
{21367}{21512}Jsem sjednocení veškerého vìdomí, které existuje ve vesmíru.
{21512}{21554}Èekal jsem na tebe.
{21599}{21773}U dlouhı èas bylo vybíráno spousta dívek, |aby kráèely tou samou cestou.
{21804}{21891}Zachránit Arcadii a stát se Queen's Egg.
{21891}{21918}To je pravda.
{21942}{22053}Nícménì, vìtšina znich pøišla bìhem své cesty o ivot.
{22053}{22146}A jejich nenávist a smutek sbíral Erbos.
{22176}{22345}Ale tvá silná duše a jemná osobnost zhojili jejich srdce.
{22345}{22407}A nakonec jsi oèistila Erbose.
{22433}{22547}Jsi dívka, která miluje Arcadii víc, ne cokoli jiného, Angelique.
{22547}{22670}Byla jsi vybrána, aby se's stala Královnou, díky síle svıch citù.
{22670}{22694}Dìkuji mnohokrát.
{22712}{22809}Budu tady, abych podporovala své pøátele.
{22853}{22933}A vy mi musíte také pomoct.
{22964}{23000}Èas nadešel.
{23025}{23148}Jsi ochotná se mnou jít do Sacred Land, |aby se's stala Královnou a ochránila Arcadii?
{23203}{23222}Ano.
{23239}{23334}Stanu se Královnou a ochráním mou milovanou Arcadii.
{23351}{23434}Vìdìl jsem, e to øekneš.
{23462}{23541}Pojïme spolu, Angelique.
{23688}{23713}Angelique!
{24056}{24079}Aurora...
{24103}{24123}Ange...
{24145}{24167}Poèkej!
{24191}{24235}Neodcházej, Ange!
{24235}{24270}Neodcházej!
{24389}{24413}Neodcházej!
{24496}{24599}Ange!
{25457}{25532}Dìkuji, moji drazí pøátelé.
{25571}{25674}Ah, jak krásná Arcadie!
{25693}{25755}Má vlast!
{26116}{26135}Yo.
{26135}{26209}Jsi stále tady, profesore Rayne?
{26229}{26290}Øekl jsem ti, a mi neøíkáš profesore, ne Erene?
{26303}{26330}Ty taky.
{26330}{26431}Øekl jsem ti, e mi máš øíkat Erenfriede.
{26506}{26565}Tohle je urèitì speciální zpráva!
{26565}{26657}Od tebe vdycky dostávám skvìlé informace!
{26657}{26761}No, pouívám nìjaké triky, kdy nejsem elitní novináø jako ty.
{26761}{26840}Vlastnì, máme málo zamìstnancù.
{26840}{26940}To je èas pro tebe stát se novináøem v tomto mìstì a pøidat se ke mì.
{26980}{27039}Mé sluby jsou drahé, to víš!
{27181}{27210}Podívej, Mathiasi...
{27246}{27328}Tvé milované Holy Capital je pøekrásné.
{27366}{27393}Vaše excelnce...
{27410}{27437}Je tady?
{27437}{27451}Ano.
{27464}{27500}Dobøe... U jdu.
{27614}{27634}René...
{27647}{27729}Jsem v Holy Capital stále s tebou.
{27729}{27774}Ochraòuju tì.
{27815}{27859}Kam pojedete?
{27859}{27902}Budu pokraèovat v mé cestì.
{27902}{27981}Nezapomìòte nám øíct pøíbìhy ze své cesty!
{27981}{28014}Ano, sbohem.
{28092}{28153}Vítej, Hyuugo.
{28170}{28241}Vracíš se k Organizaci?
{28255}{28273}Ne.
{28273}{28326}Budu pokraèovat ve své cestì.
{28343}{28378}Hyuugo! Proè?
{28396}{28488}Chci stráit Arcadii, protoe ona ochraòuje toto místo.
{28503}{28533}Prosím, dejte mi povolení.
{28569}{28592}Rozumím.
{28607}{28740}Všichni jsou schopni pøekonat kadou tìkost svımi schopnostmi.
{28754}{28837}Tak ti dávám mùj slib.
{28912}{28959}Nevzdám se.
{28959}{29030}Musím najít zpùsob, jak tì vidìt.
{29030}{29078}Oèekávej mì!
{29126}{29165}Pùjèím si to.
{29165}{29213}Dobøe.
{29213}{29330}A to ukonèím, pøidám se k tvım vızkumùm.
{29330}{29361}Poèítám s tebou!
{29399}{29497}Najdu zpùsob, jak ji vidìt!
{29510}{29533}Rozhodnì...
{29702}{29734}Angelique.
{29777}{29834}Budu stále v Holy Capital.
{29834}{29961}Vra se rychle zpátky.
{30031}{30137} Ne se opìt shledáme, budu pokraèovat ve své cestì.
{30137}{30166}Neunávnì...
{30232}{30288}Cesta pøed námi je volná.
{30322}{30357}Kterou cestou mám jít?
{30385}{30425}Vím, e jedna z nich mì k tobì dovede.
{30483}{30547}Jsem si jistı, e nìkde dìláš co mùeš.
{30547}{30640}Najdu zpùsob, jak se k tobì pøidat.
{30653}{30673}Rozhodnì.
{31256}{31287}Královna?
{31314}{31502}Dùvodem, proè je teï Arcadie tak krásná je to,| e se Královna modlí daleko v Sacred Land.
{31575}{31597}Královna!
{31983}{32140}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{32228}{32380}www.mycolorfullife.blog.cz
