{1301}{1430}Jestli z toho vyšlo nìco dobrého nebo zlého?|To opravdu nedokáu øíct.
{1453}{1563}Ale stejnì jako vìtšina lidí si myslím...
{1570}{1646}...vyrùstal jsem v kraji, kde jsem se narodil.
{1682}{1802}Moje rodina byla ze støední tøídy,|prostì prùmìrná.
{1844}{1916}A tak jsem nikdy nepoznal potíe bohatıch...
{1917}{1968}...nebo strádání chudıch.
{1970}{2038}Abych øekl pravdu, mìl jsem bezstarostnı ivot.
{2108}{2181}Kdy jsem byl malı,|chtìl jsem bıt vojenskım pilotem.
{2216}{2289}Musíš se pøihlásit k vojenskému námoønictvu,|jestli chceš létat se stíhaèkou.
{2363}{2420}Jsou tak rychlé...|Létají tak vysoko...
{2421}{2506}Chtìl jsem létat víc ne cokoliv jiného.
{2519}{2644}Ale dva mìsíce pøed ukonèením školy...
{2646}{2758}...jsem si uvìdomil, e moje známky|nejsou k tomu dostateènì dobré.
{2795}{2878}A tak... Nakonec jsem vstoupil do Vesmírnıch sil...
{2930}{3030}Køídla Honneamise|Pøeklad: Translation ManiaCZ.
{3040}{3130}Toto je nekomerèní pøeklad.|Není urèen k prodeji!
{3140}{3230}#manga.cz@IRCNet
{7190}{7251}Chci vìdìt pouze dvì vìci.
{7252}{7356}Kde jsi doposud byl?! A proè nejsi ve slavnostní uniformì?
{7358}{7459}Mohl bych pøedpokládat, e první otázka|se tıká mé minulosti?
{7460}{7555}Pøestaò, zatracenì!|Chci vìdìt, proè jsi pøišel pozdì!
{7557}{7641}Proè ze sebe musíš vdycky dìlat blázna?
{7643}{7731}Nemáš dojem, e tohle váná vìc?|Opozdit se na pohøeb kamaráda!
{7733}{7783}Zdøímnul jsem si na støeše a zaspal jsem, pane!
{7832}{7902}Èlovìk z tvé jednotky je mrtvı, a ty...
{7932}{7980}To si øíkáš voják?
{8068}{8117}Zapomeò na to, zaøaï se.
{8287}{8332}- Ahoj...|- Zdar.
{8334}{8388}Kde jsi byl?
{8390}{8445}Nìco jsem si musel promyslet.
{8447}{8501}Proè nejsi ve slavnostní uniformì?
{8503}{8575}Neøeš to.|Mohu se obléct, jak chci.
{8611}{8675}No, generála to docela vzalo.
{8677}{8753}"Pøijít pozdì na pohøeb kamaráda!"|To on ho zabil!
{8762}{8805}Byla to nehoda bìhem testu, ne?
{8807}{8865}Ano, slyšel jsem, e policie pøijede dnes.
{8867}{8937}Pravdìpodobnì protekl zásobník na moè ve skafandru...
{8939}{8977}...a to zpùsobilo tu nehodu.
{8979}{9043}Skafandr? Co to je?
{9044}{9108}Nevíš? Takové to nìco, co musíš nosit v kosmu.
{9110}{9174}On tam opravdu chce nìkoho dostat.
{9194}{9252}Umìlı satelit s lidskou posádkou.
{9261}{9292}To je jen hromada sraèek.
{9294}{9355}Ano, jako všechny jeho plány.
{9357}{9438}No rozhodnì to neplánuje vzdát.|Dalším krokem bude...
{9621}{9686}Hymna Vesmírnıch sil, - pøipravit!
{9845}{9919}Vesmírné síly!|Hymna! Všichni jednotnì!
{9945}{10074}{Y:i}"Unášeni vysoko na sluneèním vìtru,|roztahujeme k letu naše køídla."</i>
{10087}{10219}{Y:i}"V temnotu vìèného kosmu,|do míst ještì neznámıch."</i>
{10232}{10339}{Y:i}"Kam zanese nás naše pou,|neví nikdo z nás."</i>
{10367}{10469}{Y:i}"Èas zaèít let a vydat se v neznámo,</i>|je stále blí."</i>
{11154}{11238}Majaho dostal poštou chleba.|Velkou krabici.
{11240}{11287}Proè chleba?
{11308}{11378}Protoe jeho rodina vlastní pekárnu.
{11436}{11466}Chleba, jo?
{11468}{11566}Ano. Pekára je fajn.|Myslíš, e by mì zamìstnali?
{11596}{11689}Se mnou nepoèítej. Pravdìpodobnì|bych nemohl venku dostat jinou práci.
{11709}{11764}Tohle místo je skvìlé.
{11766}{11838}Pøinejmenším se tu nemusíš starat o jídlo.
{11866}{11950}Máme hlad, protoe ijeme.|Jíme, abychom ili...
{11989}{12046}Nechci tady zemøít.
{12125}{12190}Hodnì volného èasu, co, Shiro?
{12213}{12310}Nemyslel jsem si, e tvojí prací tady je spaní!
{12339}{12427}Víš, co je tohle?|Mince, jeden deem.
{12429}{12508}Mùeš si za to koupit bochník chleba nebo láhev oleje.
{12510}{12598}Ale øíkají, e bandita z Khozel by pro tohle zabíjel.
{12623}{12669}Tak, kdy o tom popøemıšlíš, má to celkem velkou cenu.
{12671}{12771}Plat pøesèas. Mìl bys z toho plakat štìstím.
{12773}{12836}A teï chci, abys udìlal 300 klikù.
{12838}{12886}A potom ještì 500 sedlehù!
{13370}{13435}Další! Další!|Berte si, dokud jsou horké!
{13779}{13842}Proè jsi ještì v uniformì?
{13862}{13948}Musel jsem. Pøes tu dodateènou práci jsem nemìl èas se pøevléct.
{13950}{14020}Hanebné.|Dr se ode mì dál.
{14022}{14107}Kadı, kdo tì v tom uvidí,|se ti vysmìje.
{14124}{14198}Kadé dìvèe, které uslyší|o Vesmírnıch silách, praskne smíchy.
{14200}{14252}Piloti, kteøí sedí stále jen na zemi...
{14254}{14298}Do háje, sám bych se tomu smál,|kdyby o tom nìkdo vyprávìl.
{14470}{14527}Na kosmickou loï a našeho kamaráda,|kterı pro ni zemøel!
{14813}{14875}Myslíš, e staroušek to celé myslí vánì?
{14876}{14922}Lidé neumírají jen tak pro zábavu.
{14926}{14989}Ale dost lidí pøemıšlí o pilotovaném kosmickém letu...
{14991}{15037}...jako o nìèem, co je hodnì daleko v budoucnosti.
{15039}{15102}Nevsadil bych se, e naše Vesmírné síly vydrí do té doby.
{15128}{15199}Doufám, e vydrí aspoò tak dlouho, ne si najdu novou práci.
{15213}{15251}Øekni si Majahovi o nìjakou.
{15253}{15319}Tak hraj! Hraj! Ètyøi, tøi.
{15320}{15414}Ty šmejde!|Ohh, tak ještì dva.
{15510}{15558}To je ale divná uniforma.
{15678}{15723}To je uniforma Vesmírnıch síl.
{15724}{15798}Vesmírné síly? Coe, zaútoèili na nás kosmonauti?
{15850}{15877}Take, podplukovníku?
{15879}{15950}Dávej! Jseš pøece major proboha!
{15958}{16031}HA-HA! Dva, tøi, dva, jeden, dva!
{16043}{16118}Dìlej, Matti! Vyber si pro vımìnu nìkoho jiného!
{16120}{16167}Och, no tak, vzdávám to.
{16182}{16279}Uklidni se. Noc teprve zaèala, ne?
{16492}{16598}Héj, koèko! Koukej semhle!
{16630}{16710}Héj, dìvèe! Neslyšíš mì? Héj!
{17066}{17114}Pojï!
{17127}{17174}Tudy.
{17204}{17276}A nestarej se o peníze, to je mùj problém.
{17277}{17324}Chci jen jít spát.
{17325}{17356}Och, ty jsi pøišel!
{17358}{17404}Tohn! Tohn! Tady jsi!
{17406}{17437}Ne, Matti! Myslíš Matti!
{17439}{17508}Matti, Mattimattimatti. Jsem ráda, e jsi pøišel.
{17510}{17572}Líbí se mi tvùj dnešní parfém. Hmm, skvìlé.
{17574}{17638}Pojï, zavolala jsem  kámošce, aby mi pomohla.
{17640}{17684}Pojï! Dìlej!
{17686}{17735}Ach, héj! Øíkal jsi, e zveš...
{17754}{17825}- Kámoška, jo?|- Mimi! Tohn je tady!
{17925}{17982}No, je èas jít, "Tohne".
{18519}{18582}Den soudu se blíí!
{18611}{18684}Ti, co ijí v høíchu, budou jistì posláni do pekel!
{18722}{18787}Kadı, kdo ignoruje cestu spravedlnosti...
{18788}{18845}Ten, kdo odmítá odpovìdnost za své høíchy...
{18847}{18908}A nestydí se za své høíchy.
{18910}{18966}Všichni jsou høíšníci v boích oèích!
{19014}{19048}Dìkuji ti.
{19050}{19096}Bùh nad námi pláèe.
{19098}{19192}Den posledního soudu, kterı byl pøedpovìzen po té,...
{19194}{19290}...kdy lidskı rod poprvé vyrve plameny z oblohy, a ten den se blíí...
{19300}{19374}Všichni musíme bıt na tento den pøipraveni...
{20158}{20211}Och, to jsi ty. Kde jsou ostatní?
{20213}{20284}Jsou svátky. Myslíš, e se teï vrátí?
{20285}{20380}"Pøijï prosím?"|Co? Otevøeli novı nevìstinec?
{20381}{20428}Ooch, je tu i adresa!
{20430}{20478}Nech toho.
{20620}{20652}Mùu si pùjèit tvoji pìnu na holení?
{20654}{20718}"Èlovìk, kterı musí ebrat o pìnu na holení, je prokletı a bude ebrákem."
{20750}{20812}A kdy u jsme u toho, nemìl bys spát v posteli mrtvého.
{20814}{20862}Nosí to smùlu.
{21914}{21966}Èau, kluku.|Bydlíš tady?
{22551}{22628}Promiòte mi? Pøišel jsem, protoe jsem èetl váš leták...
{22781}{22846}Pojïte dál! Pojïte dál! Pojïte dál! Pojïte dál!
{22885}{22979}Pojïte, jen pojïte !|Jste tady ve správnou chvíli.
{22980}{23036}Právì jsem zaèala pøipravovat èaj.
{23038}{23116}Tady prosím! Sednìte si!
{23118}{23170}Zrovna pøipravuju nìco k snìdku.
{23188}{23246}Nemìl jste problém to tady najít?
{23262}{23323}Ne.|Pøijel jsem trolejbusem.
{23325}{23398}Jmenuji se Riqunni Nonderaiko.
{23406}{23454}Shirotsugh Lhadatt.
{23456}{23509}Ráda vás poznávám, pane Lhadatte.
{23511}{23548}Øíkejte mi prostì Shirotsughu.
{23550}{23613}Dobøe, Shirotsughu.|To je vıborné.
{23615}{23683}Koneènì nìkdo pøišel!|Jakı chceš èaj?
{23687}{23734}Silnı prosím. Nic víc.
{23797}{23844}Kolik ti je let, chlapèe?
{23845}{23922}Och, Manna je dìvèe.
{23926}{24002}Manno, podej tomu milému pánovi talíø...
{24200}{24251}Díky...
{24253}{24339}Ještì jsem nevidìla, e by si Manna tak rychle zvykla na nìkoho cizího.
{24341}{24389}Hotovo.
{24418}{24475}Myslím, e mì dìti mají rády.
{24477}{24574}Tady to máme.|Mùe to bıt trochu pøepeèené. Omlouvám se za to.
{24590}{24676}Ne, ne, to je v poøádku, trochu pøepeèené chutná nejlíp.
{24678}{24742}Opravdu, vypadá to dobøe.|Dobrou chu!
{24910}{24971}Èaj voní taky pìknì...
{25101}{25142}To byl ale dobrı èaj.
{25144}{25219}Ale máš pravdu, poslední dobou máme strašné èasy.
{25221}{25299}Lidé neumí rozpoznat, co je správné a co nesprávné.
{25301}{25372}Pøesnì tak! A také nedokáou správnì vychovávat své dìti.
{25374}{25427}Celı svìt se zbláznil.
{25429}{25531}Bùh to všechno pøedpovìdìl... Och, tak mì napadá.
{25542}{25566}Ano?
{25568}{25616}Neøekl jsi, co tì trápí.
{25618}{25746}Ano, take... Tam, kde pracuji, byla nehoda.
{25748}{25780}Och!
{25782}{25861}A zemøel pøi ní mùj kamarád.
{25863}{25939}To je strašné.|Musíš z toho bıt opravdu znièenı.
{25941}{26046}Ano, nemohu poøádnì jíst, pít a dokonce ani pracovat...
{26138}{26184}Tak, jakou máš tedy práci?
{26206}{26288}Ehm, no, take... Slyšela jsi nìkdy o Vesmírnıch silách?
{26304}{26333}Je mi líto, ale...
{26335}{26416}Nikdy jsi o nich neslyšela. Ani mì to nepøekvapuje.
{26418}{26515}- Take jsi voják?|- No, ne tak, jak si myslíš, my neválèíme nebo tak nìco.
{26517}{26581}Jen trénujeme, abychom mohli letìt do vesmíru.
{26583}{26665}Och, do vesmíru? To myslíš ke hvìzdám?
{26695}{26740}No, tak daleko a ne.
{26742}{26783}Máš hezkou práci!
{26784}{26836}Hm? To si myslíš?
{26838}{26891}Ano! Myslím, e je to skvìlé.
{26893}{26948}Oprostit se od starostí tohoto svìta...
{26950}{27028}...a jít do nezkaeného svìta hvìzd...
{27030}{27086}Nemyslíš, e je to skvìlé?
{27134}{27220}No, vlastnì... Víš, jsme jediná jednotka tohoto druhu na svìtì.
{27222}{27292}Nikdy jsem nemìla tak hezké svátky.
{27293}{27360}Kdy pomyslím, e mì pøišel navštívit nìkdo tak úasnı.
{27362}{27431}Myslíš, e bys mi mohl jednou povídat o hvìzdách?
{27432}{27476}Jasnì. Bude mi potìšením.
{27478}{27591}Naše dìti budou jednou ít uprostøed hvìzd, v míru.
{27600}{27712}Ano. A vesmír je tak obrovskı...|Hranice pøestanou mít smysl!
{27716}{27810}To je fantastické!|Vojáci, kteøí neválèí!
{27812}{27867}Ano, máme trochu odlišné poslání,...
{27868}{27922}...ne ti, které vídávám cvièit nad jezerem.
{27924}{27962}Máme vyšší cíl.
{27964}{28051}Pøipravujeme cestu míru pro celé lidstvo.
{28052}{28107}Tento svìt je pro lidstvo pøíliš malı.
{28108}{28182}Brzy nastane éra kosmickıch letù!
{28423}{28500}Jsou dva hlavní dùvody nepovedenıch startù:
{28502}{28596}Lidská chyba a mechanická závada.
{28624}{28691}Ach, filmy z dopoledních testù.
{28693}{28766}To jsou taky jedinné zábavné filmy, co tu uvidíme.
{28821}{28873}Hele, pùjèil sis mojí motorku minulou noc, e?
{28875}{28960}Ano, pùjèil.|Noèní vzduch byl krásnì svìí.
{28962}{29020}A ubylo by tì, kdybys ji pak aspoò natankoval?
{29022}{29084}Upøímnì, staráš se o drobnosti.
{29086}{29152}Jsme hrdí dùstojníci Vesmírnıch sil.
{29154}{29213}A on se stará o blbosti!
{29215}{29286}Dìláme tu velké a dùleité vìci!
{29311}{29390}Myslím, e minulou noc upadl na hlavu.
{29406}{29440}Taky mám ten pocit.
{29513}{29596}Pánové, jste hrdí èlenové Vesmírnıch sil!
{29598}{29680}Kníka Khi Lei Karessa,|"Monost cestování vesmírem",...
{29682}{29740}...byla poprvé vydána pøed 30 lety.
{29742}{29860}20 let pøed stvoøením naší jednotky.|Tedy celkem nedávno!
{29862}{29968}A za tìch 20 let jsme o hodnì pokroèili.
{29981}{30052}To byla jen taková drobnost...
{30054}{30092}Naše první druice!
{30094}{30159}Nemyslíš, e mohli poslat nìco víc uiteèné?
{30165}{30284}Neúspìšnı start našeho pátého satelitu, Ghida, pøed rokem...
{30286}{30340}...dost drasticky omezil monosti našeho programu.
{30342}{30417}Stále více hlasù v "Domì vznešenıch" ádá o naše zrušení.
{30419}{30518}U jsme ztratili polovinu našeho roèního rozpoètu!
{30557}{30650}Slyšel jsem, e jsme pøišli o nìkteré budovy a dotace.
{30652}{30691}To je to.
{30693}{30758}Mùeme si zaèít hledat novou práci.
{30795}{30893}Kadopádnì, pánové, kadopádnì!|Nadešel èas jim všem ukázat!
{30895}{30977}Ukázat jim, e vlastníme prostøedky umoòující lidstvu...
{30979}{31080}...podniknout plavbu v nekoneènost vesmíru!
{31094}{31190}Jak to mùeš pojmenovat vojenskou kosmickou lodí,|kdy to slouí jen k pøepravì lidí?
{31214}{31252}Generál tomu tak øíká.
{31254}{31340}Vesmír je obrovskı!|Tam venku je naše budoucnost!
{31342}{31439}Svìt míru, kterı musíme otevøít pro naše potomky.
{31470}{31547}Co? Jak chcete odstartovat s nìèím tak tìkım?
{31605}{31640}To je nemoné.
{31642}{31727}Jestli to tam nechceme znièit, nemáme právo tam vùbec letìt.
{31733}{31847}Jen jsem dal do pohybu závod|o první pilotovanı kosmickı let.
{31921}{31956}Všichni jednou zemøeme.
{31958}{32022}Ano, máme obìti.
{32024}{32094}Kadopádnì, musíme se pøes ten zármutek pøenést!
{32096}{32158}Èeká nás budoucnost!
{32160}{32260}Jsem tu dnes, abych se zeptal, kdo chce bıt|dobrovolníkem na prvního kosmického pilota.
{32262}{32299}Nebudu nikoho nutit.
{32301}{32344}Copak mezi vámi není nikdo tak stateènı,...
{32346}{32406}...aby byl ochoten pøijmout vızvu hvìzd?
{32588}{32633}Hlásím se, pane!
{32714}{32758}Zbláznil ses?
{32854}{32940}Uh, ahhh... A ty jsi?
{32942}{33011}Shirotsugh, pane!|Shirotsugh Lhadatt, pane!
{33029}{33127}Ach tak,|vzpomínám si na tebe. Nikdo jinı?
{33190}{33256}Velmi dobøe.|Jsem potìšen, e jsi se pøihlásil.
{33258}{33308}Pozdìji pøijï do konferenèního sálu.
{33310}{33356}Nìkdo další? ...
{33358}{33412}No nevadí.
{33414}{33451}Rozchod!
{33453}{33508}Proè jsi to udìlal?
{33510}{33571}- Ty mu vìøíš?|- Nesna se do toho zaplést!
{33573}{33628}Nedìlej to prosím! Mysli na svou rodinu!
{33630}{33684}Zemøeš, chlape!|Prostì zemøeš!
{33686}{33756}Promysli si to! Kolik klukù je tu z doby, kdy jsme se pøihlásili?
{33758}{33846}Jen ty a já, správnì?
{33852}{33963}Matti, ádají nás, abychom dali naše ivoty na oltáø vìdì.
{33990}{34078}Tvoøíme tady dìjiny!|Copak nejsme povinni dát ze sebe to nejlepší?
{35162}{35244}Abych byl upøímnı,|neèekal jsem od tebe nìjaké zázraky,...
{35246}{35334}...ale jde ti to líp, ne jsem pøedpokládal.
{35346}{35406}Ale to neznamená, e ti to jde nejlíp.
{35428}{35484}No, ale to nevadí.
{35486}{35573}Jestli to tak pùjde dál, tento projekt se brzy stane realitou.
{35575}{35620}Brzo odjedu do hlavního mìsta nìco zaøídit.
{35622}{35668}Abych èelil lvùm v jejich doupìti, abych tak øekl.
{35670}{35700}Take budu mít moc práce,...
{35702}{35783}...ale koneènì budeme mít naši|vojenskou kosmickou loï.
{35794}{35852}Aha? Take bude mít i namontované zbranì?
{35854}{35907}Ano, myslím, e mùe nést i takové vybavení.
{35909}{35956}Mnohem dùleitìjší ale je, e bude plná chytrıch mašinek
{35957}{36012}vymyšlenıch tak, aby tì udrely naivu.
{36014}{36084}Aèkoliv na tom mùeme trochu ušetøit...
{36086}{36156}Hm, co jestì jsem ti mìl øíct?
{36157}{36222}Nevzpomenu si! Mùeš odejít!
{36225}{36274}Rozkaz...
{36301}{36357}Ach, poèkej!|Právì jsem si vzpomnìl.
{36366}{36430}Co to jen bylo?
{36486}{36545}Ach! Zajisté! Létání!
{36558}{36660}Tréning na pøetíení v letadle.|Nikdy jsi nesedìl v letadle, e?
{36662}{36708}Kde seenu letadlo?
{36710}{36748}Pùjèíme si ho.
{36750}{36787}Kde chcete pùjèit letadlo?
{36788}{36839}Idiote...|Od vojenského letectva, odkud jinud?
{37902}{37964}Páni, koukejte na tu fantastickou kombinézu.
{37966}{38028}Mám dojem, jako bych mìl nohy ve svìráku!
{38030}{38091}- To je padák, ne?|- K èemu to je?
{38093}{38131}Nechte toho! Nehrejte si s tím!
{38133}{38214}- Ups!|- Dej to tam zpátky!
{38253}{38280}Hej!
{38325}{38372}Joo, jasnì...
{38466}{38501}Tady ne. Dopøedu!
{38503}{38543}Eh... Jasnì.
{39318}{39435}{Y:i}Greto 32, máte povolení ke startu!</i>|Opakuji, máte povolení ke startu!</i>
{42350}{42383}U jsou zpátky.
{42582}{42625}Jsi v poøádku?
{42627}{42700}- Nevypadáš moc dobøe.|- Myslím, e se pozvracím.
{42702}{42780}Co je?|Snìdl jsi nìco špatného?
{42782}{42839}Poté, co zašel tak daleko, aby si tady také hrál.
{42894}{42942}Hej, poèkej. Matti!
{42950}{43040}Hej...|Øekl jsi "hrál"?
{43042}{43086}Co je?
{43183}{43222}Pro nìj je to práce!
{43238}{43326}Co, bude v tom vesmíru nìkdo, s kım byste válèili?
{43356}{43424}Nezapomeòte nám øíct, jestli tam|potkáte nìjaké nepøátelské mimozemšany.
{43426}{43470}My je pak budeme moct sestøelit!
{43533}{43604}Hej, hej. Chtìlo by to trochu respektu, pánové.
{43605}{43700}Tihle dva sráèi jsou dùstojníci,|podplukovník a major.
{43702}{43819}Och?! Vy jste vojáci? |Ó jé, jak jsem byl nevychovanı.
{43820}{43884}Myslel jsem si, e je to jen skupina|dìtí, co si hraje s našima hraèkama!
{44006}{44071}Ty šmejde...
{44374}{44450}Chlapi, já opravdu u nemùu... Opravdu nemyslím, e to ještì vydrím...
{44598}{44670}Poèkej chvíli... Poèkej!... Prosím...
{44685}{44732}U to nevydrím...!!!
{45226}{45307}Špatná nálada, Matti?|Je toho prakticky plné mìsto.
{45308}{45374}Slyšel jsem, e tì nìjakı|serant nakopal do zadku.
{45404}{45484}Jestli musíš s nìkım válèit,|ujisti se, e je to taky dùstojník.
{45486}{45516}On mì nezmlátil!
{45518}{45563}Vidìl jsi, jak vypadá?
{45565}{45612}Heh-heh-heh, mìl štìstí.
{45613}{45675}A je to všechno tvoje chyba!
{45677}{45778}Dobøe, vy dva. Tohle je tajná továrna Vesmírnıch sil.
{45787}{45846}Zamilujete si to tady, slibuji.
{46164}{46259}Páni, to je úasné!|Neuvìøitelné!
{46261}{46364}Ti chlapi z letectva by se posrali,|kdyby tohle vidìli!
{46366}{46467}Jo, to je ono.|V téhle pøíšeøe tì pošleme vzhùru.
{46469}{46523}Jdi a zemøi!|Jdi a zemøi s poøádnım rámusem!
{46541}{46595}To je Sdruení Kosmickıch Letù?
{46597}{46655}Ano, u se v tom rıpou nìjakou dobu.
{46656}{46726}Co? To chceš øíct, e ti staøí páprdové vytvoøili tohle všechno?
{46776}{46823}Staøí páprdové?|Staøí páprdové?
{46940}{47011}A èím se mùeš pochlubit ty, ty malı sráèi?
{47012}{47096}To je Dr. Gnomm. Právì se vrátil z vıpravy na severní pól.
{47098}{47137}Vystøeloval jsem rakety...
{47139}{47218}...ještì døíve, ne jsi ty|hopsal svému otci na klínì.
{47252}{47310}Doktor je prùkopník v konstrukci raketovıch motorù.
{47460}{47508}Prosím, shromádìte celı personál, ano?
{47540}{47609}Našel jsem tady problém,|vánou chybu v tìch vıkresech.
{48019}{48059}Take?|Uka nám to!
{48061}{48172}Je to tøetí stupeò. Slyšel jsem, e jste sem umístili vodíkové motory.
{48174}{48236}Copak máme nìjakı funkèní model?
{48238}{48319}Ještì ne.|Tady je všechno první svého druhu.
{48341}{48412}Nemùete dìlat zkoušky motoru|podle tìchto vıkresù!
{48414}{48472}Myslíme, e vodíkovı motor bude nejlepší...
{48474}{48532}...pro zrychlení tøetího stupnì.
{48534}{48563}To je unáhlené!
{48565}{48676}Ticho! Vùbec netušíš, o èem mluvíš! Pøišel jsi pozdì a víš houby!
{48678}{48747}To on v tom poletí.|On by mìl rozhodnout.
{48748}{48796}Och, a co on o tom ví?
{48797}{48868}Já jsem pro nejbezpeènìjší variantu.|Nechci zemøít tak mladı.
{48870}{48925}Ach, ta mláde!|Mláde je pøeceòována!
{48927}{48971}Nemìla by bıt ani nedoceòována!
{48973}{49060}Dobøe, co bys teda udìlal?|Nemùeme kompletnì pøedìlat nic od tøetí sekce níe.
{49062}{49148}Všechno odsud do zaèátku ètvrté sekce je zastaralé.
{49150}{49205}Mohu vám ukázat jak zredukovat váhu konstrukce...
{49207}{49260}...a zvìtšit vıkon spalování motorù.
{49262}{49300}Kdy to mùe bıt hotové?
{49302}{49337}Pøíští mìsíc.
{49339}{49374}Kdy pøíští mìsíc?
{49376}{49424}Ètvrtého.
{49426}{49523}Vıbornì, poèkáme do té doby.|Dobøe. A s tím pro teï skonèíme.
{49525}{49596}Konec!|Všichni zpìt do práce!
{49695}{49796}Kdy hodíš kamenem,|tak spadne zpìt na zem. To je známı fakt.
{49798}{49887}Jestlie ho hodíš opravdu silnì,|smìrem k horizontu,...
{49916}{49980}...tak spadne opravdu daleko.
{49982}{50049}Jestli s ním budeš házet stále silnìji a silnìji,...
{50051}{50116}...mùe dosáhnout kritickou rychlost,...
{50118}{50205}...kdy poletí k horizontu, ani by spadnul.
{50222}{50282}A máš umìlı satelit.
{50295}{50329}Nebude více stoupat,...
{50331}{50404}...ale bude dále obíhat po obìné dráze planety.
{50406}{50492}Protoe atmosféra bude bránit v dosáhnutí této rychlosti,...
{50494}{50556}...musíš se vznést mnohem vıš, abys se dostal z jejího vlivu.
{50558}{50636}Kdy nadejde èas návratu,|jen klesneš do atmosféry a snííš rychlost.
{50638}{50731}To je všechno,|jen chvíli budeš brzdit a spadneš zpìt k zemi.
{50732}{50827}Struènì øeèeno, pracujeme dnem a nocí,|abychom postavili první stroj,...
{50829}{50888}...navrenı k tomu, aby mohl vzlétnout a pak spadnout zpátky.
{50890}{50940}Podle tohoto popisu to vypadá smìšnì jednoduše,....
{50942}{51031}...ale myslím,|e se mi právì ta jednoduchost líbí.
{51076}{51124}Starouškové a jejich "Sdruení Kosmickıch letù"...
{51154}{51214}Vùbec se s nima nedá o nièem rozumnì mluvit.
{51229}{51310}Ale doktor Gnomm,|ten je jinı...
{51330}{51388}Mezi tìmi starci je on jedinı,|s kım se dá mluvit.
{51415}{51482}Nevím, co bychom dìlali bez nìj.
{51509}{51606}Torom, Marhida, Gana, Moraa.|Mí pozoruhodní dobrodruzi.
{51629}{51693}- To jsou stroje.|- Oh, co je zase?!
{51695}{51787}Nebereš vánì továrnu?|To továrny pøinesly rovnost masám...
{51789}{51872}...zvìtšením rozdìlovaného majetku!
{51874}{51908}Tak odkud pochází ta jména?
{51910}{51989}Torom je ryba z moøe Eska,|které se nachází pøímo na rovníku.
{51991}{52045}Marhida je lidoravá verlyba ze Severního moøe.
{52047}{52101}Gana je jedovatı had z øeky Yvsak.
{52103}{52132}Pøipraveno!
{52134}{52165}Dobøe!
{52167}{52213}Vidíš, všechny jednou byly smrtelnì nebezpeènımi nepøáteli.
{52215}{52286}Ale teï jsou mí synové.
{52302}{52352}Mìl jsem dojem,|e byla i dívèí jména.
{52354}{52400}Och, pár takovıch je.
{52454}{52516}A teï,|narodil se Dhotonridl.
{52518}{52605}Protoe jsem se zabıval všemi èástmi,|pojmenoval jsem je všechny.
{52607}{52711}Vypadá to tak, e jedinı díl, co nemá jméno, jsi ty.
{53298}{53351}Kdo...|Kdo je tam?
{53358}{53442}"Princ Vesmíru se rozhodl zazvonit."
{53474}{53510}Aah...|Shirotsugh...
{53764}{53803}Dobrı veèer!
{53805}{53852}Dobrı veèer, Shirotsughu.
{53854}{53908}Co se dìje?|Proè je tu taková tma?
{53910}{53952}Vypli mi pøívod elektøiny.
{53954}{54004}Coe? To je strašné!
{54006}{54089}Ale to je v poøádku.|Svìtlo svíèek je stejnì hezèí.
{54091}{54196}A Manna si mùe hrát se stíny.
{54198}{54283}Mùeš jít ven?|Dnes veèer je nebe plné hvìzd.
{54340}{54411}Mohu ti povídat o hvìzdách, jak jsi chtìla.
{54413}{54460}Poèkej.
{54541}{54601}Pojï Manno.|Pùjdeme se podívat na hvìzdy!
{54775}{54820}Vidíš támhle hvìzdu Prow?
{54822}{54918}Je od nás daleko 70 svìtelnıch let.
{54949}{55027}Take svìtlo, které nyní vidíme, opustilo hvìzdu pøed 70 lety.
{55029}{55097}Kdybych mìl 70 let,|tak svìtlo, co opustilo hvìzdu...
{55099}{55173}...v den mého|narození, by sem dorazilo právì teï.
{55187}{55220}Hvìzdy!
{55222}{55276}Ano, hvìzdy.
{55278}{55390}Pøemıšlím, jak vypadá náš svìt,|tam odtud z hvìzd...
{55406}{55481}Ach ano, vidíš! Chtìl jsem ti nìco ukázat.
{55483}{55542}To je satelitní fotka našeho svìta.
{55660}{55699}Je celá èerná...
{55701}{55756}Ne, ne.|Bílé èasti jsou zemì.
{55758}{55836}To je obrázek z radaru,|take není pøíliš jasnı.
{55838}{55904}Ale, z té vıšky...
{55906}{55966}...by svìtla mìst mìla vypadat jako hvìzdy.
{56004}{56051}Ohnì našich válek stejnì tak.
{56070}{56140}Tolik høíšnıch svìtel,...
{56142}{56206}...míchajících se s èistım svìtlem hvìzd...
{58052}{58124}Všichni u nastoupili!
{58133}{58167}Pozdravte!
{58638}{58700}Svatá kniha?|Ale, já...
{58702}{58781}Vím. Ale stejnì chci, abys ji mìl s sebou.
{58783}{58862}Nìco ke ètení, kdyby ses z nìèeho cítil mizernì.
{58883}{58978}Byl bych radìji, abys byla|se mnou, kdy ji budu èíst.
{59125}{59172}Dáme si trochu èaje.
{59173}{59206}Manno.
{59277}{59347}Nepovolíš si ádnou zábavu, e?
{59349}{59427}Copak ty a bùh nemùete najít nìjakı kompromis?
{59428}{59478}Kompromis?!
{59486}{59531}Myslím bıt aspoò trošku racionální.
{59533}{59584}Jsem dostateènì "racionální"!
{59586}{59651}A ten, ten "kompromis", o kterém mluvíš,...
{59652}{59700}...dovedl svìt do stavu, v jakém je dnes!
{59702}{59762}Mnohem lépe se v nìm ije.
{59894}{59950}Manno! Øekla jsem, e si dáme èaj!
{60069}{60148}Co se dìje?|My se nehádáme.
{60150}{60246}Promiò mi.|Vidíš, u je po všem.
{60357}{60425}Pozor! Malı dárek od Táty.
{60431}{60482}Skuteènı simulátor.
{60630}{60675}První já!
{60677}{60739}Ta vìc je skvìlá.
{60741}{60813}85 milionù radekù!|85 milionù!
{60815}{60867}To je hromada penìz, take to nezniè.
{60868}{60919}Je fakt, e na to vlastnì nemáme. Bude legrace...
{60921}{60972}...pøesvìdèit Shromádìní, aby schválilo tuto dotaci.
{60974}{61033}Eh, poøád to jestì neschválili?
{61035}{61085}Tak odkud na to bereme peníze?
{61087}{61131}No, tu a tam.
{61133}{61170}Tu a tam?
{61172}{61230}Nevíš?
{61261}{61307}Víš, jako šlechtic má generál...
{61308}{61380}...vazby na královskou rodinu.
{61381}{61458}Je v tom trochu nelegálního obchodu.
{61460}{61532}- A to vše jedním telefonátem?|- Jeden telefonát je vše, co potøebuje.
{61534}{61593}A tam nikdo jen tak nebere telefonáty.|Uvidíš letos, všechna...
{61595}{61652}...sluební auta královské rodiny budou z Miguren Motors.
{61654}{61729}Take vlastnì Miguren Motors nám financují kosmickou raketu.
{61759}{61796}Takhle to funguje.
{61798}{61867}Jasnì. Take takhle to funguje. Hahaha...
{61869}{61905}Vùbec tomu nerozumíš, co?
{61907}{61945}Idiote!
{62324}{62418}Jsem tu dnes, abych oznámil plány|Vrchního velení Vesmírnıch sil...
{62420}{62515}...o konstrukci první vojenské kosmické lodi!
{62557}{62635}{Y:i}A to bylo vše co prohlásil|velitel Vesmírnıch sil.</i>
{62637}{62700}{Y:i}Na oslavì byl také pøítomen|Královská vısost Princ Toness,...</i>
{62702}{62760}{Y:i}...kterı krátce promluvil ke shromádìnım.</i>
{62762}{62868}{Y:i}Jako ochránce obyvatel...</i>
{62870}{62977}{Y:i}...Království Honneamano-Jikein-Minadhan, jsem se rozhodl...</i>
{62823}{62919}{Y:i}...podìkovat za tyto úspìchy vìdy.</i>
{62979}{63026}Nestùj tam!
{63076}{63100}Tak, vrací se obraz!
{63102}{63150}Ty seš ale balík!
{63159}{63231}{Y:i}Postup vìdy ukázal sílu ke sjednocení Vıchodní Federace Pitsubo...</i>
{63255}{63357}Nejdùleitìjší vybavení celé kosmické lodì jsi ty.
{63360}{63392}Vzduch, voda, chlazení...
{63394}{63456}Vše proto, aby ti to zabezpeèilo podmínky,...
{63458}{63523}...které se pøíliš neliší od tvé lonice.
{63540}{63620}Na oplátku za to musíš lodi dávat pøesné povely.
{63622}{63682}Bude to vzájemnı vztah mezi tebou a strojem.
{63684}{63724}Nesna se za kadou cenu prosazovat svoji vùli silou.
{63726}{63775}Jednej klidnì, jako bys byl souèástí stroje.
{63788}{63847}Tak delikátnì, jak je to moné, tak intimnì, jak je to moné...
{63854}{63878}6000,
{63878}{63926}6500,
{63926}{63950}7000,
{63950}{63998}7500.
{63998}{64070}Odpálení druhého stupnì.
{64070}{64094}Vše normální!
{64094}{64142}8000,
{64142}{64190}8500,
{64190}{64286}9000, 9500!
{64383}{64451}Hlavní velení Vesmírnıch sil...|Ano?
{64542}{64613}Máš telefon.|Je to dìvèe.
{64854}{64901}Ano, slyším. Haló?
{64903}{64986}Shirotsugh? Proboha, rychle pøijeï! Pomoz mi!
{65333}{65388}Co je?|Právì jsem s tím skonèil.
{65390}{65439}Dobré, e?|Chceš si poslechnout motor?
{65441}{65509}Chceš ji provìtrat?|Trochu jsem si pohrál se zapalováním.
{65511}{65566}Co si o tom myslíš?|Zní dobøe, ne?
{65645}{65697}Kosmickı jezdec!|Super!
{67134}{67217}Lidé z elektrárny sem poøád chodili, den za dnem...
{67238}{67347}Dùm patøil mé tetì, take jsem|myslela, e je všechno v poøádku.
{67349}{67404}Ale lidé...
{67406}{67484}Moje teta mìla dluhy, víš.
{67486}{67582}Ach? Ano? Ale to neznamená, e udìlala dobøe.
{67717}{67758}Elektrárna...?
{67794}{67887}Dobøe, pøedvoláme je pøed soud!|Vláda bude platit za proces!
{67904}{67972}Nebo já, jestli chceš.|Jestli potøebuješ právníka...
{67974}{68046}Ne, to je v poøádku.|Opravdu, je to v poøádku.
{68062}{68140}Nechci, aby to dítì vidìlo další hádky.
{68142}{68206}Její rodièe byli takoví.
{68246}{68275}Jen se hádali, den za dnem.
{68277}{68331}Pøestaòte!|Pøestaòte, prosím!
{68395}{68478}Je mi to líto, nemìla jsem tì sem kvùli tomu volat.
{68502}{68583}Kvùli tomuhle? Ale to je ...
{68619}{68677}Nedaleko odsud je kostel.
{68679}{68758}Jsou tam lidé, kteøí pomohou.
{68774}{68846}Myslím, e tam mùeme nìjakou dobu pøebıvat.
{68866}{68943}A Manna tam moná najde nìjaké kamarády...
{68999}{69027}Dobøe...
{69068}{69126}Pojï, vyhrabeme vaše vìci.
{69134}{69255}{Y:i}...Splendor je zajisté nejznámìjší zámek v Nedens. Tato krása...</i>
{69304}{69416}{Y:i}Dnes bude jasno, pouze k veèeru je objeví oblaènost...</i>
{69596}{69675}Vìk Ohnì.|Kdy bùh stvoøil èlovìka,...
{69677}{69796}...èlovìk byl jako zvíøata a neumìl ovládat oheò.
{69819}{69878}Tak jako oheò i Bùh ije vìènì.
{69880}{69999}Èlovìk Dao ukradl planoucí vìtev a utíkal tak rychle, jak dokázal.
{70001}{70079}Ale boskı ochránce ohnì to pøedpovìdìl...
{70081}{70128}...a tento oheò proklel.
{70163}{70263}Kdy se Dao vrátil domù, snail se oheò, kterı pøinesl, pouívat jako sám Bùh.
{70264}{70336}A tak bylo zabito sedm synù Daa.
{70348}{70420}To byla první umrtí lidstva.
{70432}{70524}A tehdy se Bùh objevil pøed Daoem i dal mu proroctví.
{70530}{70611}"Èlovìèe,", øekl,|"byl jsi proklet."
{70613}{70712}"Tvé dìti budou spolu válèit, hádat se a ít ve smutku."
{70725}{70795}"Jejich neštìstí bude trvat a do konce svìta."
{70796}{70863}"Budou se tak dlouho zabíjet, dokud nezùstane nikdo ivı."
{70955}{71035}Jsi si jistı, e je bezpeèné bıt tak blízko?
{71036}{71116}Jasnì, nic se nám nestane.
{71118}{71204}Ty staré motory byly vdycky na rozsypání,|kdy se víc zatíily.
{71228}{71332}Dìlají to tak u 20 let.|Jsou jako skuteèní synové.
{71371}{71430}Drzí a pøipravující èlovìka o nervy.
{71432}{71514}To je posíláte spát bez zákusku,|kdy se chovají neslušnì?
{71516}{71563}Ovšem. Navíc kdy dìlají starosti starouškovi,...
{71564}{71643}...nedìlají je jen tak neèekanì.|Obvykle dají napøed nìjaké varování...
{72304}{72355}Jedna, ètyøi, pìt.
{72357}{72436}Jedna... ètyøi... pìt...
{72560}{72619}Ano. Netrefila tì nìjaká støepina?
{72621}{72658}Ne, ani jedna.
{72660}{72714}Ach, ovšem, dostaneš se odtud ivı a zdravı...
{72716}{72772}...a doktor skonèí ve špitálu.
{72836}{72884}Zaslouil si to, kdy mì tam tak nechal.
{72886}{72915}Následující pìt, šest.
{72917}{72954}Pìt, šest.|Díky tomu...
{72956}{73003}...lépe zabezpeèí vstup a vıstup do továrny.
{73005}{73066}Jedna, tøi, ètyøi.|Proè?
{73068}{73140}Protoe si myslí, e to zapøíèinili|pravdìpodobnì politiètí radikálové.
{73148}{73186}Politiètí radikálové?
{73188}{73251}Lidé, co nesouhlasí s rozhodnutími krále.
{73252}{73315}Ostatnì bylo dost protestních dopisù.
{73316}{73351}To jsem nevìdìl.
{73353}{73419}Doutná to den za dnem.
{73420}{73508}Bylo by hloupé si myslet, e ta exploze byla jen nehoda.
{73523}{73555}Další.
{73556}{73607}Uhh, tøi, ètyøi, pìt.
{73620}{73706}Coe? Dej to sem...
{73708}{73772}Hej, tohle je druhı øádek!
{73828}{73866}Nepravdìpodobné.
{73868}{73899}Omlouvám se.
{73900}{73969}Dìlej to, jak to má bıt,|nebo to nebude fungovat...
{73971}{74075}Hej, a nìkdo uklidí toho kocoura a jeho|hlídaèe z toho elektronického mozku!
{74077}{74122}Nemáš co dìlat?
{74124}{74236}Minulou noc jsem vùbec nespal.|Staroušci tam byli znova...
{74316}{74355}Mám toho dost!
{74356}{74417}Doktor, on...|...je mrtvı!
{74419}{74442}Kdy?!
{74444}{74507}Pøed chvílí v nemocnici.
{76660}{76706}{Y:i}Z hlavního mìsta. Královská rodina pøivítala všechny...</i>
{76708}{76775}{Y:i}...spojené s propagaèní slavností Vesmírnıch sil.</i>
{76776}{76866}{Y:i}Podplukovník Shirotsugh Lhadatt, první astronaut...</i>
{76868}{76915}{Y:i}...se zde objevil dnes veèer.</i>
{76916}{76971}{Y:i}Ta slavnostní uniforma mu skuteènì sluší.</i>
{76972}{77058}{Y:i}Na dotaz kníete Tonesse "Jestli se nebojí té cesty do vesmíru?"...</i>
{77060}{77186}{Y:i}...klidnì odpovìdìl "Opravdu mì to netrápí".</i>
{77300}{77403}Héj, ty! Copak ses nìkdy musel starat o peníze?
{77404}{77523}Víš jaké to je bıt zapomenutı svìtem?
{77525}{77593}Je nám stále hùø a vìtší zima.
{77595}{77665}Kdy pøijde zima, tak se omotáváme pøikrıvkami...
{77667}{77739}...a tøeseme se zimou.|Nemáme kde spát, co jíst!
{77768}{77810}Uhnìte z cesty! Nechte mì projít!
{77812}{77850}Komu tento projekt pomáhá?
{77852}{77898}Spíš se mìlo stavìt více mostù!
{77900}{77979}Pøinejmenším by stavitelé takto dali práci muùm a enám!
{77980}{78051}Co se tam vepøedu dìje?
{78052}{78098}Protestují. To ráno bylo opravdu strašné,...
{78099}{78170}...se všemi tìmi šarvátkami a ebráním venku.
{78171}{78227}Take co po nás chce to hnutí nezamìstnanıch?
{78228}{78283}Ne, ne. To je hnutí proti válce.
{78284}{78347}Øíkají, e bychom mìli stavìt mosty a ne rakety.
{78348}{78410}Jak jsem øekl, hnutí nezamìstnanıch!
{78412}{78476}Take jsme povinni vyhodit všechny naše peníze|na nìkolik mostù, které nepotøebujeme?
{78478}{78569}V mojí zemi doposud pouíváme pøívozy!
{78571}{78636}Vybral bych mosty místo váleèné kosmické lodì.
{78668}{78715}Alespoò by nemohly nikoho zabít...
{78780}{78837}Hej, hej, hej, nedej se tím zblbnout.
{78839}{78907}Øíkají to, protoe chtìjí práci.
{78908}{78964}Ta raketa bude pouita ve válce.
{78990}{79044}Mosty mùes taky pouívat ve válce.
{79099}{79148}Ty jsi to všechno zaèal!
{79171}{79232}Já? Pochybuju o tom.
{79248}{79304}Tak kdo to všechno zaèal?
{79320}{79346}Hej!
{79725}{79819}{Y:i}Podplukovník Lhadatt zaèíná ráno|sklenicí èerstvého ovocného dusu.</i>
{79828}{79898}{Y:i}Po lehkém tréniku jí zdravou|snídani z mìkkého chleba...</i>
{79899}{79971}{Y:i}...a opeèenıch jahod kress.</i>
{79980}{80042}{Y:i}Správnì, protoe je to zdravé.</i>
{80044}{80092}{Y:i}Dámy a pánové, Shirotsugh Lhadatt.</i>
{81148}{81185}Co?|Sráè!
{81444}{81480}Hej!|Co je...?!
{81618}{81643}Matti! Ty...!
{81645}{81699}Tady jseš.|Právì jsem èetl noviny....
{81701}{81777}Jsi celı mokrı.|Budou problémy!
{81764}{81860}Co je?
{81900}{81955}Tady píšou, e start bude z Kanea.
{81976}{82067}Kdy se pøesunulo místo startu tak daleko na jih?
{82068}{82111}Nevìdìl jsi to?
{82112}{82184}Po tom všem bychom nemohli pouít vojenskou startovací rampu.
{82240}{82312}600 ren na západ od Kanea?!|To je za hranicemi!
{82357}{82442}Ne, ne, všechno je v poøádku.|Tady je mapa...
{82700}{82748}Je to pøesnì v demilitarizované zónì!
{82771}{82875}Ne, ne. Takto to je o 3000 ren blíe rovníku.
{82876}{82952}Bude jednodušší se dostat na orbitu, uvidíš...
{82960}{83058}Ano, vím!|Mùj Boe, jak to mohli udìlat?
{83060}{83105}Posílají nás na sudu se støelnım prachem,...
{83107}{83178}...aby udìlali nejvìtší ohòostroj na svìtì.
{83180}{83247}To se nikdo nepokoušel je zastavit?!
{83248}{83315}To nebylo naše rozhodnutí.|To bylo ministerstva.
{83317}{83409}Ministerstva? Jaké minis...?|Ministerstvo Obrany?
{83716}{83820}...norinosska, zuiben mattoishi|suru rekujishieto.
{83836}{83935}Uh, kurufateeji onla|laku... lakure...
{83955}{84002}Lakuretoria!
{84003}{84079}Mluv místním jazykem. Buï sám sebou.
{84132}{84179}Ehm... Díky, cením si toho.
{84180}{84252}Ale u nemám nic víc, co bych øekl.
{84348}{84429}Nic víc?|Take mi dovol mluvit.
{84431}{84547}Jak jsme øekli, nemáme v plánu|likvidovat tvou raketu.
{84568}{84671}Cestování kosmem? Tady se probírá armáda.
{84672}{84746}Kdo by investoval do nìèeho,|co dokáe jen letìt do vesmíru?
{84748}{84835}To nemá ádnı vojenskı uitek.
{84836}{84911}Samotná existence Vesmírnıch sil je podivná!
{84928}{85043}Tak ... proè jste nechali projekt dojít tak daleko...?
{85044}{85118}Musíme najít zpùsob, jak správnì|ukonèit tento program.
{85120}{85179}Královská rodina, Ministerstvo dopravy...
{85180}{85239}Koøeny Vesmírnıch sil zasahují do mnoha oblastí.
{85240}{85313}Všichni zaèínáme litovat toho,|e byly pøed deseti lety vytvoøeny.
{85315}{85403}Bylo také u zapomenuto, proè vlastnì byly vytvoøeny.
{85405}{85474}Ten program se pøedevším nikdy nemìl zahajovat,|nyní ho musíme ukonèit.
{85476}{85571}Jene tento projekt pøitahuje pozornost všech národù.
{85573}{85658}Dokonce Republika chce naší raketu.
{85660}{85740}Vypustit raketu právì na hranici|nepøítelem okupované Rimady...
{85742}{85826}Tak to udìlej! Vypus ji,|nebo cokoliv chceš udìlat....
{85828}{85900}Chceme, aby ji vidìly|okupaèní síly Republiky v Rimadì.
{85902}{85985}A co myslíš, e udìlají s tvojí milovanou raketou,|kterou budou mít pøímo na oèích?
{85987}{86010}Zkusí ji ukrást!
{86012}{86122}Ukrást ji! Aspoò bude mít nìjakı uitek.
{86124}{86174}Pøekroèení hranice ozbrojenımi silami.
{86176}{86255}A otevøená kráde tak cenné vìci...
{86256}{86318}Náklady se od nìkud vrátí, tak jako tak.
{86324}{86416}Jediná podstatná otázka je,|jestli opravdu zaútoèí nebo ne.
{86448}{86475}O to se nestarej.
{86477}{86580}Oni taky investovali pomìrnì dost|do tvé rakety, e?
{86732}{86779}- Pøipraven?|- Ano, pane!
{86781}{86858}{Y:i}Zaèínáme. Právì køiuješ na orbitì|a snaíš si uít odpoèinku.</i>
{86859}{86975}{Y:i}Tvá vıška je 3000,|rychlost 200 ren za sekundu...</i>
{86988}{87100}...A další kontrola spojení je daleko za horizontem...
{87176}{87235}Abnormální tlak v kyslíkové nádri èíslo 1!
{87236}{87298}Hlavní potrubí uzavøeno. |Aktivován pøídavnı pohon.
{87299}{87379}Tøi!|Pøerušuji dodávku dusíku!
{87380}{87457}Systémy setrvaènosti vykazují|abnormální zrychlení.
{87459}{87554}Restartuji nefunkèní systémy.|Tlak v kabinì, v poøádku!
{87616}{87699}Dobøe, vydìlal sis svoji vıplatu.
{87700}{87761}{Y:i}Dále, krizová situace #5-7-5.</i>