{1}{1}25.000
{45}{134}{C:$24FFFF}Volám sa Kazuki Shikimori a mám 17 rokov.
{134}{197}{C:$24FFFF}Som normálny stredoškolák chodiaci na školu Aoi,
{197}{282}{C:$24FFFF}ktorého gény však jedného dòa privedú na svet|toho najmocnejšieho èarodejníka v dejinách!
{282}{409}{C:$24FFFF}Avšak ... Vyèerpal som celú svoju èarovnú moc a |moje telo sa rozplynulo prach.|
{438}{498}{C:$24FFFF}Stal sa zo mòa DUCH.
{569}{706}{C:$24FFFF}No i napriek tomu Yuna, Kuriko, a Rin zostali i naïalej po mojom boku.
{683}{756}{C:$24FFFF}Dokonca aj teraz, keï som úplne bezmocnı.
{851}{1048}{C:$FF62FF}{Y:i}Som si istá, e jedného dòa budeme spútaní kúzlom zvanım láska.
{1048}{1223}{C:$FF62FF}{Y:i}A ja budem stá.
{1223}{1310}{C:$FF62FF}{Y:i}Navdy po tvojom boku.
{1481}{1636}{C:$FF62FF}{Y:i}Ty vieš, e a milujem. A to je jediné na èo kadodenne myslím.
{1636}{1841}{C:$FF62FF}{Y:i}Avšak ty si akoby na pochybách. Èo sa snaíš zakryt svojim nesmelım úsmevom.
{1841}{1997}{C:$FF62FF}{Y:i}No ja a milujem takého akı si.
{1997}{2190}{C:$FF62FF}{Y:i}A chcem a chráni kadı deò i noc, yeah yeah
{2190}{2390}{C:$FF62FF}{Y:i}Som si istá, e jedného dòa budeme spútaní kúzlom zvanım láska.
{2390}{2547}{C:$FF62FF}{Y:i}Nezáleí na tom aké strašné veci ...
{2547}{2703}{C:$FF62FF}{Y:i}a poloia na kolená. Bude to v pohode. Ver mi.
{2703}{2881}{C:$FF62FF}{Y:i}Ja budem vdy TU.
{2881}{2966}{C:$FF62FF}{Y:i}Stá po tvojom boku.
{3159}{3205}{C:$24FFFF}Pripravila som desiatu!
{3205}{3247}{C:$24FFFF}Páni! ... Vyzerá to úasne!
{3247}{3275}{C:$24FFFF}Môem ochutna tvoju omeletu?
{3275}{3294}{C:$24FFFF}Jasné!
{3459}{3504}{C:$24FFFF}Ty nebudeš jes?
{3512}{3589}{C:$24FFFF}Niè nepotrebujem. Som predsa duch.
{3589}{3623}{C:$24FFFF}Vlastne áno.
{3672}{3788}{C:$24FFFF}Elizabeth povedala, e je toto pre duchov ve¾ká pochúka, take ...
{3847}{3951}{C:$24FFFF}Si si istı, e nechceš niè jes? Po obede vyuèovanie pokraèuje.
{4036}{4063}{C:$24FFFF}Kazuki ...
{4175}{4219}{C:$24FFFF}Èo sa deje?
{4219}{4296}{C:$24FFFF}Som si istá, e existuje spôsob ako sa staneš znovu èlovekom.
{4296}{4402}{C:$24FFFF}Nemusíš by kvôli tomu takı skleslı.
{4402}{4432}{C:$24FFFF}Som v poriadku.
{4465}{4512}{C:$24FFFF}Len ma nechaj chví¾ku osamote.
{4591}{4632}{C:$24FFFF}Kazuki ...
{4684}{4771}{C:$FFB062}"Chytil sa"|alebo|"Ako sme padil do pasce"
{4774}{4808}{C:$24FFFF}To ako váne?!
{4808}{4848}{C:$24FFFF}Áno, váne!
{5338}{5381}{C:$24FFFF}È ... Èo to?
{5525}{5599}{C:$24FFFF}Ako som sa sem dostal?
{5820}{5849}{C:$24FFFF}Yuna ...
{5866}{5900}{C:$24FFFF}Shikimori ...
{5913}{5966}{C:$24FFFF}Ten hlas ...Ty si to dievèa z minula!
{6016}{6055}{C:$24FFFF}Pamätáš si ma? Aké milé.
{6075}{6153}{C:$24FFFF}Nemusíš byt nervózny. Všetko je v poriadku.
{6153}{6203}{C:$24FFFF}Práve som si a pridala do svojej úasnej zbierky.
{6203}{6269}{C:$24FFFF}Lene ja o to nestojím!
{6282}{6337}{C:$24FFFF}A nie je na to u trochu prineskoro?
{6390}{6472}{C:$24FFFF}Tomuto miestu sa hovorí "Motel duchov".
{6472}{6521}{C:$24FFFF}Celkom efektívne, nemyslíš?
{6537}{6584}{C:$24FFFF}Nemáš dôvod sa nieèoho bá.
{6587}{6690}{C:$24FFFF}Keï sa tak snaíš sta sa znovu èlovekom, ...|Je snáï nejakı konkrétny dôvod, preèo to robíš?
{6690}{6761}{C:$24FFFF}Veï duchovia majú svoj vlastnı druh potešenia.
{6761}{6839}{C:$24FFFF}V ... Vlastnı druh potešenia?
{6894}{6940}{C:$24FFFF}U èoskoro na to prídeš sám.
{7143}{7204}{C:$24FFFF}Èo to robíš, Kazuki?
{7204}{7261}{C:$24FFFF}Eh ... No ... Ja ...
{7261}{7305}{C:$24FFFF}Zasa ty?
{7305}{7371}{C:$24FFFF}Ty teda dokáeš ¾uïom liez na nervy.
{7371}{7404}{C:$24FFFF}Si dos zlomyse¾ná.
{7408}{7504}{C:$24FFFF}To nie je tvoja vec!
{7553}{7623}{C:$24FFFF}Oh, práve si všetko znièila.
{7631}{7722}{C:$24FFFF}A to som ti práve chcela prezradi aké potešenia prináša by duchom.
{7744}{7802}{C:$24FFFF}Prosím poèkaj chví¾u!
{7821}{7867}{C:$24FFFF}Ešte sa uvidíme, Shikimori ...
{7867}{7916}{C:$24FFFF}Teda ... Kazuki.
{8205}{8267}{C:$24FFFF}Si v poriadku, Kazuki?
{8351}{8388}{C:$24FFFF}Áno.
{8400}{8440}{C:$24FFFF}Som rada, e si v ...
{8452}{8493}{C:$24FFFF}To je ...
{8523}{8592}{C:$24FFFF}Eh, ...Nie ... To ...
{8592}{8661}{C:$24FFFF}Hovoril si, e iadnu cukrovú vatu nechceš.
{8661}{8743}{C:$24FFFF}To je od teba podlé Kazuki.|Ty podvodník!
{9111}{9213}{C:$24FFFF}Aj keby sa mi podarilo sta sa znovu èlovekom. Èo bude potom?
{9297}{9380}{C:$24FFFF}Moja èarovná moc sa mono naèisto vytratila.
{9397}{9429}{C:$24FFFF}A to aj s mojimi génmi ...
{9451}{9482}{C:$24FFFF}Kazuki ...
{9500}{9531}{C:$24FFFF}Shikimori ...
{9547}{9579}{C:$24FFFF}Kazuki ...
{9608}{9674}{C:$24FFFF}Má vôbec cenu sta sa znovu èlovekom?
{9669}{9714}{C:$24FFFF}To ja neviem.
{9759}{9799}{C:$24FFFF}U zas?!
{9794}{9855}{C:$24FFFF}Odpust, e som a svojim neèakanım príchodom to¾kokrát prekvapila.
{9905}{9967}{C:$24FFFF}A prepáè, e som aj sem vstúpila neohlásene.
{9967}{10055}{C:$24FFFF}Ve¾mi ma to mrzí. Naozaj.
{10055}{10120}{C:$24FFFF}Èo vlastne so mnou chceš?
{10120}{10185}{C:$24FFFF}Nechcem sa sta súèasou tvojej zbierky duchov.
{10197}{10243}{C:$24FFFF}Preto tu nie som.
{10243}{10350}{C:$24FFFF}Chcem len vedie, èi sa stále túiš sta znovu èlovekom.
{10350}{10393}{C:$24FFFF}Myslíš tım, e môem?!
{10403}{10454}{C:$24FFFF}Èisto hypoteticky ...
{10454}{10504}{C:$24FFFF}Aj keby si sa stal znovu èlovekom.
{10504}{10567}{C:$24FFFF}Nejestvuje záruka, e všetko bude také, aké bolo predtım.
{10567}{10653}{C:$24FFFF}Môu a tak èaka aj horšie veci, ne by duchom.
{10662}{10737}{C:$24FFFF}Plus. Taktie nejestvuje záruka,|e vôbec nájdeš spôsob ako sa vráti spä.
{10737}{10784}{C:$24FFFF}A tak radšej, ne sa zbytoène namáha .
{10784}{10866}{C:$24FFFF}Nechceš zvái potešenia by duchom?
{10890}{10944}{C:$24FFFF}Nemám v úmysle a obaova.
{10944}{11019}{C:$24FFFF}Keï budeš chcie, nájdeš ma tu.
{11019}{11061}{C:$24FFFF}Zastav sa kedyko¾vek na kus reèi.
{11399}{11445}{C:$FFB062}Kazetsubakiho cukráreò
{11496}{11549}{C:$24FFFF}Jediné èo bolo treba urobi, bolo zafarbi ich!
{11571}{11645}{C:$24FFFF}Toto Kazukiho urèite rozveselí!
{11732}{11764}{C:$24FFFF}Vynikajúce!
{11774}{11812}{C:$24FFFF}Yuu! Chceš, aby sme išli na stanicu spolu?
{11812}{11861}{C:$24FFFF}Ve¾mi sa ponáh¾am! Prepáè!
{11861}{11906}{C:$24FFFF}Uvidíme sa! Ahoj!
{11978}{12032}{C:$24FFFF}Chceš nieèo vedie o tej ene?
{12032}{12090}{C:$24FFFF}No... Kazuki zaèína by hroznı.
{12090}{12192}{C:$24FFFF}To¾ko som sa natrápila pri vırobe cukrovej vaty,|a on ju nechcel ani dnes.
{12192}{12240}{C:$24FFFF}A to som ich urobila v to¾kıch farbách.
{12262}{12335}{C:$24FFFF}Mám pocit, e v tomto ten problém nebude.
{12335}{12486}{C:$24FFFF}Práve preto! Musím vedie,|preèo mu cukrová vata od tej eny chutí a moja nie!
{12486}{12586}{C:$24FFFF}Mono na to pouíva nejakı ve¾mi |dobrı cukor, alebo také nieèo!
{12586}{12642}{C:$24FFFF}Náš cukor je vysoko kvalitnı, ako iste vieš.
{12642}{12691}{C:$24FFFF}Tak èím to potom je?
{12737}{12831}{C:$24FFFF}Tie ma zaujíma, kto tá ena vlastne je.
{12831}{12922}{C:$24FFFF}Vyšetrujem ju cez nieko¾ko rôznych inštitúcií.
{12922}{13008}{C:$24FFFF}Èudné však je, e o nej nie som schopná zisti jedinú malièkost.
{13008}{13041}{C:$24FFFF}Nejestvujú nijaké stopy.
{13041}{13082}{C:$24FFFF}To snáï ...
{13092}{13155}{C:$24FFFF}V kadom prípade to nie je normálne.
{13155}{13236}{C:$24FFFF}Mohla o sebe všetky informácie úmyselne zatajit, alebo ...
{13236}{13277}{C:$24FFFF}Alebo?
{13303}{13382}{C:$24FFFF}Tie informácie jednoducho neexistujú.
{13382}{13441}{C:$24FFFF}Nieèo však predsa len máme.
{13441}{13460}{C:$24FFFF}Rin.
{13460}{13510}{C:$24FFFF}Ty si nieèo našla?
{13572}{13739}{C:$24FFFF}Existujú svedkovia, ktorí tú enu videli |vojst do starého kaštie¾a mimo mesta.
{13746}{13819}{C:$24FFFF}Všetci ju dokonale popísali. Take si nemyslím, e by klamali.
{13819}{13840}{C:$24FFFF}Hm ...
{13840}{13896}{C:$24FFFF}Ten dom rozhodne vyzerá zlovestne.
{13896}{13950}{C:$24FFFF}Nie je to ten typ, ktorı by sa dal nazva "malebnım".
{13952}{13988}{C:$24FFFF}Avšak ...
{14004}{14046}{C:$24FFFF}(Prázdna plocha)|Èo sa deje?
{14084}{14210}{C:$24FFFF}Bez oh¾adu na to, ako teraz vyzerá.|Nezdá sa, e by tu ten dom mal stá celıch šesdesiat rokov. |
{14598}{14658}{C:$24FFFF}Len sa s òou pôjdem porozpráva.
{15370}{15397}{C:$24FFFF}Tak ako?
{15397}{15454}{C:$24FFFF}Je to beznádejné. Takto niè nezistím.
{15454}{15513}{C:$24FFFF}Navyše je tam bariéra, ktorá chráni vstup.
{15513}{15566}{C:$24FFFF}Ale to je dôkaz, e vo vnútri predsa len nieèo je.
{15566}{15593}{C:$24FFFF}To je fakt!
{15604}{15674}{C:$24FFFF}Je jasné, e ide o velkolepú fabriku na cukrovú vatu!
{15674}{15741}{C:$24FFFF}V takom prípade odhalím ich tajomstvo, a ...
{15741}{15802}{C:$24FFFF}Oh! Yuna, poèkaj!
{15804}{15867}{C:$24FFFF}To nesmieš! Takto nás prezradíš. |Musíme sa najprv pripravi.
{15867}{15921}{C:$24FFFF}Oh, ale preèo?!
{15921}{15961}{C:$24FFFF}Nie, nie, nie!
{15961}{15997}{C:$24FFFF}Hej, Kuriko.
{16106}{16151}{C:$24FFFF}K ...Kazuki!
{16249}{16304}{C:$24FFFF}Prosím poèkaj! Kazuki!
{16320}{16366}{C:$24FFFF}Poèkaj ... Yuna!
{16376}{16400}{C:$24FFFF}Kazuki!
{16432}{16464}{C:$24FFFF}Nie je tu.
{16490}{16534}{C:$24FFFF}Èo je toto za miesto?
{16685}{16751}{C:$24FFFF}Kazuki a tá cukrová vata sú niekde tu!
{16769}{16829}{C:$24FFFF}Yuna! Je nebezpeèné vojs dnu sama!
{17258}{17307}{C:$24FFFF}Som rada, e si prišiel.
{17460}{17511}{C:$24FFFF}Rozmıš¾al si nad tım, èo som ti hovorila?
{17521}{17580}{C:$24FFFF}Nie celkom.
{17580}{17649}{C:$24FFFF}By duchom je úasná vec, nemyslíš?
{17649}{17697}{C:$24FFFF}Nemáš telo, take sa musíš cíti pohodlne.
{17703}{17757}{C:$24FFFF}Ani to nie.
{17757}{17827}{C:$24FFFF}Cítim sa, akoby som plával v povetrí a tak sa nemôem uvo¾ni.
{17862}{17964}{C:$24FFFF}A musím sa ve¾mi sústredi, aby som v rukách nieèo takéto udral.
{17984}{18051}{C:$24FFFF}Sú to snáï tie dôvody, preèo sa chceš sta znovu èlovekom?
{18218}{18260}{C:$24FFFF}Èo to doèerta bolo?
{18260}{18335}{C:$24FFFF}Nejakı hrubı spôsob ako privíta hostí?
{18335}{18415}{C:$24FFFF}To znamená, e ak chceme pokraèova, musíme by opatrné.
{18423}{18472}{C:$24FFFF}Nemáme na vıber.
{18553}{18586}{C:$24FFFF}Èo je to za zvuk?
{18772}{18812}{C:$24FFFF}T ... To snáï ...
{18843}{18873}{C:$24FFFF}Rıchlo! Bete!
{18922}{18974}{C:$24FFFF}Èo sa to tu dokelu deje?!
{19035}{19080}{C:$24FFFF}Pre tvoju zaujímavos ...
{19080}{19125}{C:$24FFFF}By duchom je úasná vec.
{19125}{19216}{C:$24FFFF}Nikdy neochorieš, a samozrejme ... Nikdy nezomrieš.
{19216}{19306}{C:$24FFFF}Taktie si nadobro oslobodenı od svojich pozemskıch záväzkov.
{19306}{19362}{C:$24FFFF}To všetko je mono pravda, ale ...
{19362}{19432}{C:$24FFFF}By èlovekom neznamená niè viac ne utrpenie.
{19432}{19522}{C:$24FFFF}Je to ivot nudnıch a bolestivıch medzi¾udskı vzahov.
{19522}{19622}{C:$24FFFF}Z håbky srdca si kadı uvedomuje, e sú tie veci nepríjemné.
{19622}{19696}{C:$24FFFF}Neby nimi suovanı, je jedna z mála vıhod by duchom.
{19701}{19790}{C:$24FFFF}Ale ... Jediní, kto to môu skutoène vedie,| sú ¾udia, ktorí sa u stali duchmi.
{19790}{19902}{C:$24FFFF}Oh! Ty si snáï myslíš, e ti to tvrdím bez vlastnıch skúseností?
{19902}{19927}{C:$24FFFF}Take si ...
{19927}{19979}{C:$24FFFF}No ... Èo myslíš?
{20021}{20086}{C:$24FFFF}V situácii ako je táto, je vdy problém v tom ...
{20086}{20135}{C:$24FFFF}Ktorım smerom sa vybra.
{20144}{20181}{C:$24FFFF}Doprava ...
{20212}{20248}{C:$24FFFF}Do¾ava ...
{20282}{20322}{C:$24FFFF}Èo urobíme?
{20322}{20370}{C:$24FFFF}Ja pôjdem tadia¾to.
{20401}{20481}{C:$24FFFF}Ak Shikimoriho nájdem, budem vás kontaktova telepaticky.
{20481}{20547}{C:$24FFFF}Ak sa nieèo stane na vašej strane, dajte mi prosím vedie.
{20645}{20703}{C:$24FFFF}Rin je skutoène odvána.
{20748}{20801}{C:$24FFFF}Skôr má hrošiu kou.
{20853}{20884}{C:$24FFFF}Elizabeth.
{20886}{20957}{C:$24FFFF}Si predsa duch. Take choï napred.
{20957}{21052}{C:$24FFFF}Nie! Dokonca aj duchovia sa boja temnıch miest,|v ktorıch sú úplne bezmocní.
{21052}{21121}{C:$24FFFF}Tak potom preèo si šla s nami?
{21234}{21258}{C:$24FFFF}Kuriko?
{21349}{21427}{C:$24FFFF}Tak sa mi zdá, e tu niekto nastrail zopár pekne trápnych pascí!
{21455}{21504}{C:$24FFFF}Povedz, Kazuki.
{21515}{21627}{C:$24FFFF}Nie je to tım, e by som a chcela dosta do svojej zbierky.
{21630}{21723}{C:$24FFFF}Ale ak mi s¾úbiš, e u nebudeš túi sta sa znovu èlovekom,
{21723}{21808}{C:$24FFFF}môeme i v tomto dome spolu.
{21808}{21862}{C:$24FFFF}Len my dvaja. Navdy.
{21878}{21921}{C:$24FFFF}Preèo ma tak ve¾mi túiš ma?
{21921}{21963}{C:$24FFFF}Len tak ...
{21990}{22022}{C:$24FFFF}Ja ...
{22521}{22567}{C:$24FFFF}Aké nechutné.
{22692}{22742}{C:$24FFFF}Sek deštrukcie!
{23275}{23302}{C:$24FFFF}Èo sa deje?
{23302}{23368}{C:$24FFFF}Akoby som poèula Rin krièa. Ty snáï nie?
{23368}{23427}{C:$24FFFF}Niè som nepoèula.
{23427}{23472}{C:$24FFFF}Taktie nás ešte telepaticky nekontaktovala.
{23472}{23502}{C:$24FFFF}Áno, ale ...
{23640}{23686}{C:$24FFFF}Poèka. Èo má by zas toto?
{23686}{23726}{C:$24FFFF}Ah, falošnı strop.
{23726}{23796}{C:$24FFFF}Je to bená pasca v komiksoch a filmoch.
{23796}{23848}{C:$24FFFF}Teraz nie je èas, aby si hrala najmúdrejšiu!
{23881}{23924}{C:$24FFFF}Tak teda ...
{24047}{24112}{C:$24FFFF}Èo budeme teraz robi?!
{24112}{24153}{C:$24FFFF}Kuriko! Tadia¾to!
{24185}{24217}{C:$24FFFF}Rıchlo, rıchlo!
{24217}{24247}{C:$FFB062}Ïalšia pasca
{24251}{24302}{C:$24FFFF} U ma to štve. U ma to váne ...
{24302}{24345}{C:$24FFFF}ŠTVE!!!
{24467}{24525}{C:$24FFFF}Tak, aká je tvoja odpoveï?
{24578}{24641}{C:$24FFFF}Myslím, e máš pravdu.
{24641}{24718}{C:$24FFFF}Neviem, èi sa môem sta znovu èlovekom.
{24718}{24799}{C:$24FFFF}A keby aj áno, nebude z toho niè iné ne utrpenie.
{24799}{24848}{C:$24FFFF}Presne tak! Take ...
{24848}{24876}{C:$24FFFF}Ale ...
{24900}{24934}{C:$24FFFF}Ja mám ...
{24948}{25042}{C:$24FFFF}¼udí, ktorí pri mne vdy stoja.
{25042}{25132}{C:$24FFFF}A pokım ona ... Pokım ony všetky budú pri mne stá i naïalej,
{25132}{25227}{C:$24FFFF}Nemôem to len tak vzda.
{25236}{25278}{C:$24FFFF}Skutoène?
{25351}{25433}{C:$24FFFF}Tak v tom prípade sa ti toto asi páèi nebude.
{25727}{25805}{C:$24FFFF}Yuna! ... Kuriko! ... Elizabeth!
{25834}{25862}{C:$24FFFF}Kazuki!
{25865}{25911}{C:$24FFFF}Vydrte! Zachránim vás!
{26002}{26080}{C:$24FFFF}Okolo celej miestnosti je vytvorená silná bariéra.
{26096}{26160}{C:$24FFFF}Nezáleí na tom, akú èarovnú |moc pouiješ, alebo èi si duch.
{26160}{26214}{C:$24FFFF}Je nemoné z tadia¾ uniknú.
{26214}{26255}{C:$24FFFF}Preèo to všetko robíš?
{26255}{26351}{C:$24FFFF}Pretoe si nerozvány.|Tvrdohlaví ¾udia sú takí blázni.
{26410}{26474}{C:$24FFFF}U bolo dos reèí.
{26474}{26597}{C:$24FFFF}Shikimori Kazuki, podvolíš sa mi a staneš sa súèasou mojej zbierky.
{26597}{26664}{C:$24FFFF}Ak to urobíš, Nechám tie dievèatá odís.
{26664}{26701}{C:$24FFFF}To predsa ...
{26701}{26796}{C:$24FFFF}Èím dlhšie budeš váha, tım ašie to pre nich bude.
{26969}{27019}{C:$24FFFF}Prosím prestaò!
{27028}{27080}{C:$24FFFF}Prestanem, ak sa rozhodneš správne.
{27083}{27124}{C:$24FFFF}To nesmieš, Kazuki!
{27138}{27199}{C:$24FFFF}Nezáleí na tom, èo sa so mnou stane!
{27218}{27297}{C:$24FFFF}Aj keï ... Stále myslím na našu spoloènú budúcnos.
{27297}{27354}{C:$24FFFF}Preto by som radšej chcela by zachránená.
{27354}{27392}{C:$24FFFF}Ah, preber sa!
{27831}{27859}{C:$24FFFF}Oh nie!
{27859}{27912}{C:$24FFFF}Istım spôsobom, je to dos trápne!
{27912}{27957}{C:$24FFFF}Na také reèi teraz vôbec nie je èas!
{28105}{28154}{C:$24FFFF}Take, èo budeš robi?
{28173}{28255}{C:$24FFFF}Prosím, zachráò Yunu a ostatnıch.
{28263}{28313}{C:$24FFFF}Pridám sa do tvojej zbierky. Urobím èo budeš ...
{28313}{28359}{C:$24FFFF}Nerob to Shikimori!
{28359}{28383}{C:$24FFFF}Rin!
{28416}{28470}{C:$24FFFF}Oh! Prestaòte sa na mòa veša!
{28692}{28731}{C:$24FFFF}Rin! Dievèatá!
{28945}{28989}{C:$24FFFF}Ste všetky v poriadku?
{29019}{29043}{C:$24FFFF}Yuna!
{29069}{29105}{C:$24FFFF}Som v poriadku.
{29122}{29154}{C:$24FFFF}Ale teraz ...
{29189}{29282}{C:$24FFFF}Páni. Tvoje naèasovanie bolo lepšie, ne som oèakávala.
{29282}{29375}{C:$24FFFF}No sila a poèet "zombi" napokon splnili svoj úèel!
{29392}{29421}{C:$24FFFF}Èo to má znamena?
{29421}{29527}{C:$24FFFF}Ako hovorím. Dala som vám všetkım šancu.
{29527}{29600}{C:$24FFFF}Nie som ve¾kım fanúšikom jednostrannıch hier.
{29600}{29641}{C:$24FFFF}Kto dopekla ste?
{29641}{29673}{C:$24FFFF}Toto vám neodpustím!
{29705}{29750}{C:$24FFFF}Na vašom mieste by som to nerobil.
{29856}{29886}{C:$24FFFF}Doktor Akai?
{29886}{30000}{C:$24FFFF}Aj keby ste bojovali všetky spolu.|Nemyslite si, e by ste Shino dokázali porazi.
{30000}{30069}{C:$24FFFF}Nebolo potrebné, aby si zasahoval. Braèek.
{30074}{30108}{C:$24FFFF}Braèek?!
{30108}{30156}{C:$24FFFF}Oh. Vy ste to nevedeli?
{30156}{30205}{C:$24FFFF}Toto je moja mladšia sestra, Shino.
{30224}{30295}{C:$24FFFF}A teraz u poïme. Neplytvaj mojim èasom.
{30295}{30327}{C:$24FFFF}Dobre ... Dobre ...
{30356}{30414}{C:$24FFFF}Oh ... Skoro by som zabudol.
{30414}{30476}{C:$24FFFF}Bolo by najlepšie, keby ste taktie èo najskôr odišli.
{30602}{30680}{C:$24FFFF}Take sú pokrvní príbuzní? Tım sa ve¾a vysvet¾uje.
{30702}{30737}{C:$24FFFF}È ... Èo to?
{30737}{30776}{C:$24FFFF}To nie je dobré. Celá izba sa ...
{30776}{30809}{C:$24FFFF}Poïme rıchlo!
{31152}{31196}{C:$24FFFF}Èo má by zas toto?
{31196}{31234}{C:$24FFFF}Nemáme èas otá¾a!
{31319}{31368}{C:$24FFFF}Hıbe sa to!
{31705}{31767}{C:$24FFFF}Mono si sa s nimi zabávala a prive¾a.
{31767}{31816}{C:$24FFFF}Ale. Ty snáï iarliš?
{31816}{31919}{C:$24FFFF}Miyama Yuna, Kazetsubaki Kuriko, Kamishiro Rin.
{31919}{31976}{C:$24FFFF}Sú celkom podarené.
{32295}{32340}{C:$24FFFF}Èo sa stalo?
{32592}{32656}{C:$24FFFF}O èo vèera vlastne išlo?
{32656}{32711}{C:$24FFFF}Mám pocit, akoby to všetko bol len sen.
{32711}{32790}{C:$24FFFF}Nemôem uveri, e to miesto nebola továreò na cukrovú vatu.
{32790}{32815}{C:$24FFFF}Ty si ...
{32815}{32862}{C:$24FFFF}Dobré ráno, študenti.
{32929}{32974}{C:$24FFFF}S ... Shino!
{33013}{33043}{C:$24FFFF}Èo tu chceš tentoraz?!
{33043}{33156}{C:$24FFFF}Som na škole Aoi zamestnaná ako asistentka môjho brata.
{33156}{33235}{C:$24FFFF}Teda ... Doktora Akaia. Volám sa Shino Akai.
{33235}{33331}{C:$24FFFF}A zdá sa, e odteraz budeme spolu kadı deò.
{33364}{33398}{C:$24FFFF}Asistentka?
{33514}{33584}{C:$24FFFF}Èo len so mnou bude ...
{35766}{35958}{C:$FFB062}Preklad, úprava a èasovanie - John Sedrik||(18. 2. 2008)
{35971}{36024}{C:$24FFFF}A tak sme padli do pasce.
{36021}{36093}{C:$24FFFF}Ako som sa len mohla necha takto poníi ...
{36093}{36141}{C:$24FFFF} Shino Akai je skutoène hrozivım protivníkom.
{36143}{36174}{C:$24FFFF}Áno, to je ...
{36174}{36231}{C:$24FFFF}Asi bude najlepšie, ak sa odteraz k ošetrovni nepriblíime.
{36231}{36308}{C:$24FFFF}No kadopádne. Ïalšia èas Maburaha sa volá, "Vzniesol sa"
{36315}{36343}{C:$24FFFF}Èo sa deje, Rin?
{36343}{36391}{C:$24FFFF}A ... Ale niè.
