{1}{1}23.976
{45}{112}{C:$28FFFF}Volám sa Kazuki Shikimori a mám 17 rokov.
{112}{176}{C:$28FFFF}Som normálny stredoškolák chodiaci na školu Aoi,
{176}{257}{C:$28FFFF}ktorého gény však jedného dòa privedú na svet |toho najmocnejšieho èarodejníka v dejinách!
{257}{380}{C:$28FFFF}Avšak ... Vyèerpal som celú svoju èarovnú moc |a moje telo sa rozplynulo prach.
{402}{459}{C:$28FFFF}Stal sa zo mòa DUCH.
{526}{657}{C:$28FFFF}No i napriek tomu Yuna, Kuriko, a Rin zostali i naïalej po mojom boku.
{667}{726}{C:$28FFFF}Dokonca aj teraz, keï som úplne bezmocnı.
{813}{1002}{C:$FF62FF}{Y:i}Som si istá, e jedného dòa budeme spútaní kúzlom zvanım láska.
{1002}{1170}{C:$FF62FF}{Y:i}A ja budem stá.
{1170}{1252}{C:$FF62FF}{Y:i}Navdy po tvojom boku.
{1417}{1566}{C:$FF62FF}{Y:i}Ty vieš, e a milujem. A to je jediné na èo kadodenne myslím.
{1566}{1762}{C:$FF62FF}{Y:i}Avšak ty si akoby na pochybách. |Èo sa snaíš zakry svojim nesmelım úsmevom.
{1762}{1912}{C:$FF62FF}{Y:i}No ja a milujem takého akı si.
{1912}{2097}{C:$FF62FF}{Y:i}A chcem a chráni kadı deò i noc, yeah yeah
{2097}{2288}{C:$FF62FF}{Y:i}Som si istá, e jedného dòa budeme spútaní kúzlom zvanım láska.
{2288}{2439}{C:$FF62FF}{Y:i}Nezáleí na tom aké strašné veci ...
{2439}{2589}{C:$FF62FF}{Y:i}a poloia na kolená. Bude to v pohode. Ver mi.
{2589}{2759}{C:$FF62FF}{Y:i}Ja budem vdy TU.
{2759}{2842}{C:$FF62FF}{Y:i}Stá po tvojom boku.
{2920}{2954}{C:$28FFFF}Maj sa!
{2987}{3021}{C:$28FFFF}Haló?
{3021}{3093}{C:$28FFFF}Áno. |Áno, rozumiem.
{3093}{3158}{C:$28FFFF}Stretneme sa na rovnakom mieste, ako predtım.
{3177}{3198}{C:$28FFFF}Take ...
{3203}{3242}{C:$28FFFF}Kam chceš ís?
{3264}{3312}{C:$28FFFF}Do toho a niè.
{3312}{3370}{C:$28FFFF}V poslednej dobe vyzeráš by taká zaneprázdnená.
{3370}{3421}{C:$28FFFF}Je dobré takto zanedbáva Shikimoriho?
{3432}{3505}{C:$28FFFF}Chceš predsa jeho gény, nie je tak?
{3512}{3546}{C:$28FFFF}Áno. |Avšak ...
{3559}{3590}{C:$28FFFF}P ... Poèkaj ...
{3681}{3711}{C:$28FFFF}Prepáè.
{3752}{3807}{C:$28FFFF}Mám ešte ve¾a práce.
{3894}{3976}{C:$28FFFF}Som ti snáï na archu?
{4016}{4101}{C:$28FFFF}"Špehovali sme"
{4568}{4597}{C:$28FFFF}Kazuki...
{4652}{4747}{C:$28FFFF}Kazuki?| Èo by si si dal dnes na veèeru?
{4770}{4826}{C:$28FFFF}Japonskú, západnú, èínsku kuchyòu ...
{4826}{4894}{C:$28FFFF}Oh, áno!| Ani talianska by nebola zlá.
{4894}{5007}{C:$28FFFF}V takom prípade by boli cestoviny najlepšie.| Èo myslíš, Kazuki?
{5063}{5111}{C:$28FFFF}Nechutí ti talianska kuchyòa?
{5119}{5164}{C:$28FFFF}Tak to nie je ...
{5164}{5234}{C:$28FFFF}Si nerozhodnı ako vdy.
{5243}{5312}{C:$28FFFF}Shikimori. Nevidel si Kuriko?
{5318}{5368}{C:$28FFFF}Nie ... Nevidel.
{5368}{5396}{C:$28FFFF}Aha ...
{5396}{5441}{C:$28FFFF}Deje sa snáï nieèo?
{5441}{5513}{C:$28FFFF}Študentská rada ma poiadala, aby som ju našla.
{5513}{5607}{C:$28FFFF}Vyzerá to, e sa Kuriko v poslednej dobe po vyuèovaní v škole u nezdriava.
{5607}{5669}{C:$28FFFF}To by mohlo znamena problémy, |ak nie je Kuriko na blízku, však?
{5669}{5742}{C:$28FFFF}Vlastne. Nie je to len študentská rada, ktorá si robí starosti.
{5742}{5775}{C:$28FFFF}Mne taktie ...
{5803}{5866}{C:$28FFFF}to zaèína robi starosti.
{5938}{6002}{C:$28FFFF}Ja viem, kde by mohla by.
{6002}{6073}{C:$28FFFF}Tak? |Pôjdete ju so mnou h¾ada?
{6394}{6437}{C:$28FFFF}Mešká.
{6474}{6522}{C:$28FFFF}Necha ma tak dlho èaka ...
{6566}{6626}{C:$28FFFF}Nie je správne, e ju takto sledujeme.
{6626}{6697}{C:$28FFFF}Take sme ju našli.| Ale èo tu vlastne robí?
{6704}{6770}{C:$28FFFF}Zdá sa, e na niekoho èaká.
{6770}{6836}{C:$28FFFF}Mono má rande.
{6836}{6931}{C:$28FFFF}Take je to rande. Dajme jej teda u pokoj.
{6957}{6980}{C:$28FFFF}Zdravím.
{7011}{7054}{C:$28FFFF}Rozhodne mešká.
{7074}{7101}{C:$28FFFF}Odpus!
{7123}{7158}{C:$28FFFF}Pán Taki!
{7190}{7222}{C:$28FFFF}Èakáš dlho?
{7222}{7256}{C:$28FFFF}Nie, vôbec!
{7256}{7299}{C:$28FFFF}Tak predsa je to mu!
{7414}{7442}{C:$28FFFF}Peniaze?!
{7442}{7540}{C:$28FFFF}Vyzerá to, akoby sme ju fakt špehovali.| Nemali by sme s tım presta?
{7540}{7570}{C:$28FFFF}To nesmieme!
{7570}{7630}{C:$28FFFF}Presne. |Ak jej nebudeme kry chrbát,
{7630}{7701}{C:$28FFFF}dostane sa v študentskej rade do poriadnych problémov.
{7713}{7744}{C:$28FFFF}Snáï nechceš poveda, e je Kuriko ...
{7752}{7781}{C:$FFB062}"Kabukicho ulica"|
{7788}{7822}{C:$28FFFF}e robí toto!
{7822}{7861}{C:$28FFFF}A tie tamto!
{7934}{7962}{C:$28FFFF}To nie!
{7962}{8007}{C:$28FFFF}Nesmieš tie peniaze prija, Kuriko!
{8007}{8050}{C:$28FFFF}Má pravdu, Kuriko!
{8158}{8211}{C:$28FFFF}¼udia, toto naozaj nie je správne.
{8298}{8384}{C:$FFB062}"Nákupné stredisko Tokimeki"
{8514}{8633}{C:$28FFFF}Hm ... Nebolo by lepšie sa s òou porozpráva, |ne ju takto prenasledova?
{8675}{8732}{C:$28FFFF}Kam má asi Kuriko namierené?
{8741}{8828}{C:$28FFFF}Viac sa obávam toho, e sme príliš nápadní. |Takto nás ¾ahko odhalí.
{8835}{8961}{C:$28FFFF}To všetko kvôli nemu ... |Kvôli tomu chlapovi, mi u nevenuje pozornos!
{8974}{9020}{C:$28FFFF}Rozhodne sme a príliš nápadní.
{9020}{9058}{C:$28FFFF}Eh ... Zdravím.
{9058}{9088}{C:$28FFFF}Pozri mama ...
{9088}{9111}{C:$28FFFF}Nedívaj sa tam!
{9124}{9193}{C:$28FFFF}Váne by bolo lepšie sa s òou porozpráva.
{9193}{9255}{C:$28FFFF}Èo robíme, nie je správne.
{9255}{9286}{C:$28FFFF}To je pravda ...
{9286}{9324}{C:$28FFFF}Zadr!
{9324}{9389}{C:$28FFFF}Ešte stále sme nezistili o èo vlastne ide.
{9409}{9492}{C:$28FFFF}Ak sa náhodou mılime, mohlo by to zle skonèi.
{9503}{9538}{C:$28FFFF}Take ...
{9542}{9621}{C:$28FFFF}"Reštaurácia"| Najlepšie bude, keï ich budeme sledova o nieèo dlhšie.
{9625}{9660}{C:$28FFFF}"Reštaurácia"| Mama!
{9890}{9961}{C:$28FFFF}Zdá sa, e sa celkom dobre bavia. Nemyslíte?
{9961}{10004}{C:$28FFFF}Mono sme naozaj zašli priïaleko.
{10004}{10100}{C:$28FFFF}Lene Kuriko si vzala peniaze od toho mua.
{10100}{10137}{C:$28FFFF}Presne tak.
{10198}{10240}{C:$28FFFF}Musíme pátra ïalej.
{10350}{10415}{C:$28FFFF}Èoraz viac mi to pripadá ako celkom obyèajné rande.
{10429}{10500}{C:$28FFFF}Naozaj sme zašli priïaleko.
{10509}{10544}{C:$28FFFF}Vyzerá to tak.
{10544}{10666}{C:$28FFFF}Nie. Stále to niè nedokazuje.| Kuriko si od toho podozrivého chlapa vzala peniaze.
{10666}{10753}{C:$28FFFF}Špinavé peniaze nasiaknuté chlipnosou!
{10978}{11029}{C:$28FFFF}Stále tvrdím, e je to len normálne rande.
{11029}{11055}{C:$28FFFF}Zdá sa to tak.
{11055}{11138}{C:$28FFFF}Pod¾a mòa sa tí dvaja k sebe celkom hodia.
{11138}{11198}{C:$28FFFF}Hovorím, e by bolo najlepšie u ís domov.
{11198}{11263}{C:$28FFFF}Súhlasím. Vysvetlím to aj študentskej rade.
{11263}{11390}{C:$28FFFF}Nie! Nie!!! |Ten chlap jej dal špinavé peniaze, aby s Kuriko ...
{11410}{11477}{C:$28FFFF}Vrá mi moju Kuriko!!!
{11494}{11584}{C:$28FFFF}Kuriko! Kuriko! Tu som!
{11671}{11734}{C:$28FFFF}Tak predsa len došli na podozrivé miesto.
{11746}{11833}{C:$28FFFF}Teraz nadíde ten okamih, |ktorı nám odhalí pravú tvár toho chlapa!
{11833}{11881}{C:$28FFFF}Je to len planina starého parku.
{11881}{11967}{C:$28FFFF}Park je predsa normálnym miestom na rande.
{11967}{12051}{C:$28FFFF}Nemyslím, e sa máš èoho obáva, Elizabeth.
{12051}{12138}{C:$28FFFF}Vzala som to so sebou pre kadı prípad, no ...
{12157}{12204}{C:$28FFFF}Všetci ste naivní!
{12204}{12262}{C:$28FFFF}Vezmite si napríklad fontánu v tomto parku.
{12262}{12326}{C:$28FFFF}Chodia tam mladé páry, aby tam za bieleho dòa robili ...
{12394}{12485}{C:$28FFFF}Boe! Stratili sme ich len preto, e a napadla taká hlúpos!
{12499}{12551}{C:$28FFFF}Som si istá, e zamierili priamo k fontáne.
{12551}{12599}{C:$28FFFF}Take ... Kadia¾ máme ís, aby sme sa tam dostali?
{12612}{12665}{C:$28FFFF}Som tu prvı raz.| Ako to mám vedie?
{12665}{12688}{C:$28FFFF}Èoe?
{12822}{12861}{C:$28FFFF}A mám a!
{12930}{12950}{C:$28FFFF}Kazuki!
{12950}{12972}{C:$28FFFF}Èo?
{13153}{13260}{C:$28FFFF}Ale nie. U som ho koneène mala |a vy sa do toho zasa musíte plies.
{13270}{13325}{C:$28FFFF}Èo sa to snaíš Kazukimu urobi?
{13325}{13368}{C:$28FFFF}O èo ti vlastne ide?
{13368}{13411}{C:$28FFFF}Sleèna Akai ...
{13426}{13467}{C:$28FFFF}To je dobrá otázka.
{13470}{13577}{C:$28FFFF}Prišla som si chyti jeden vzácny exemplár na blišie pozorovanie.
{13588}{13630}{C:$28FFFF}Tomu snáï rozumieš, nie?
{13630}{13665}{C:$28FFFF}Shikimori?!
{13710}{13752}{C:$28FFFF}Nie, ani trochu!
{13754}{13792}{C:$28FFFF}Shikimori!
{13792}{13837}{C:$28FFFF}Kam to beíš?
{13837}{13890}{C:$28FFFF}Sleèna Akai. |Prosím prestaòte!
{13890}{13921}{C:$28FFFF}Ak tak neurobíte ...
{13952}{14019}{C:$28FFFF}Dobre. Dobre. |Nie je dôvod tvári sa tak naštvane.
{14170}{14231}{C:$28FFFF}Zdá sa, e má pre teba slabos.
{14244}{14283}{C:$28FFFF}Ani nevieš akú.
{14478}{14513}{C:$28FFFF}Ty jeden ...
{14513}{14577}{C:$28FFFF}Ako sa opovauješ by takı trúfalı k mojej Kuriko?!
{14577}{14648}{C:$28FFFF}Zadr! Elizabeth!
{14653}{14737}{C:$28FFFF}Nenechám a poloi jedinı prst na jej poprsie!
{14737}{14764}{C:$28FFFF}Èo to?
{14933}{14958}{C:$28FFFF}Kuriko ...
{14958}{14987}{C:$28FFFF}Áno?
{14987}{15041}{C:$28FFFF}Vezmeš si ma?
{15366}{15393}{C:$28FFFF}Áno.
{15554}{15613}{C:$28FFFF}Take takto to je.
{16098}{16161}{C:$FFB062}"Hamburger-Wok"
{16202}{16257}{C:$28FFFF}Bolo to dos neèakané vyvrcholenie, nemyslíte?
{16257}{16324}{C:$28FFFF}Si v poriadku, Elizabeth?
{16338}{16394}{C:$28FFFF}Som v pohode. |Neboj sa o mòa.
{16394}{16421}{C:$28FFFF}No ... Dobre.
{16427}{16474}{C:$28FFFF}Tım sa všetko vyjasnilo.
{16474}{16550}{C:$28FFFF}Od zaèiatku sme sa mılili.
{16550}{16606}{C:$28FFFF}Neveril som, e by Kuriko robila nieèo èudné.
{16606}{16678}{C:$28FFFF}Alebo, e by sa stretávala s cudzími mumi.
{16678}{16708}{C:$28FFFF}Samozrejme, e nie.
{16708}{16751}{C:$28FFFF}Ona nie je ako ty, Shikimori.
{16782}{16825}{C:$28FFFF}Ale i tak ma to prekvapilo.
{16825}{16866}{C:$28FFFF}Nikdy by ma nenapadlo, e by sa zasnúbila.
{16866}{16930}{C:$28FFFF}To by vysvet¾ovalo, preèo sa prestala stretáva so študentskou radou.
{16930}{16994}{C:$28FFFF}Veï napokon ... Toto naèisto ovplyvní aj zvyšok jej ivota.
{16994}{17018}{C:$28FFFF}Ale ...
{17018}{17068}{C:$28FFFF}Viem, èo chceš poveda.
{17068}{17138}{C:$28FFFF}Kuriko sa s tebou nato¾ko chcela zblíi,
{17138}{17186}{C:$28FFFF}a teraz je tomu všetkému koniec.
{17186}{17222}{C:$28FFFF}Mono sa dokonca cítiš osamelo.
{17222}{17277}{C:$28FFFF}Nie. Tak to nie je ...
{17311}{17363}{C:$28FFFF}Nie si moc dobrı klamár, vieš to?
{17374}{17462}{C:$28FFFF}Ale. Je naozaj správne, e sa Kuriko zasnúbila?
{17462}{17570}{C:$28FFFF}Som si istá, e rodina Kazetsubaki má svoje dôvody, preèo tak rozhodla.
{17570}{17618}{C:$28FFFF}Hej! To je moje!
{17647}{17681}{C:$28FFFF}Hm?
{17690}{17747}{C:$28FFFF}Musíš sa sústredi.
{17747}{17870}{C:$28FFFF}Ak tak neurobíš a budeš myslie na hlúposti, |tvoje telo bude naïalej prechádza skrz všetky veci.
{17881}{17915}{C:$28FFFF}Stále máš pred sebou ešte dlhú cestu.
{17915}{17977}{C:$28FFFF}Ty tie neustále myslíš na Kuriko, take ...
{17994}{18056}{C:$28FFFF}To vôbec nie je pravda! Sleduj.
{18056}{18141}{C:$28FFFF}Vidíš? Ide mi to preto, |pretoe nemyslím na hlúposti.
{18407}{18451}{C:$28FFFF}E ... Elizabeth!
{18451}{18487}{C:$28FFFF}Prosím, neplaè.
{18487}{18610}{C:$28FFFF}Tie som z toho smutná. |No ak to urobí Kuriko šastnú, tak...
{18610}{18675}{C:$28FFFF}Odteraz by sme sa im u nemali plies do ivota.
{18849}{18890}{C:$28FFFF}Oh, aké prekrásne!
{18890}{18943}{C:$28FFFF}Sú v to¾kıch monıch dizajnoch.
{18943}{18993}{C:$28FFFF}Ktoré sa ti najviac páèia, Kuriko?
{18993}{19032}{C:$28FFFF}Hm? Ktoré sa mi páèia?
{19032}{19075}{C:$28FFFF}Kúpim ti ktoré len budeš chcie.
{19075}{19142}{C:$28FFFF}Èi vlastne, a sa nasahujeme do nášho nového domu.
{19142}{19171}{C:$28FFFF}Áno ...
{19175}{19220}{C:$28FFFF}Pôjdeme si prezrie i ïalšie poschodie?
{19220}{19256}{C:$28FFFF}Máme dos èasu.
{19256}{19280}{C:$28FFFF}Èas?
{19280}{19367}{C:$28FFFF}Rezervoval som pre nás stôl v úasnej reštaurácii.
{19387}{19437}{C:$28FFFF}Ïakujem. Pán Taki.
{19437}{19484}{C:$28FFFF}Môeš ma vola Koichi.
{19616}{19650}{C:$28FFFF}Prepáète.
{19665}{19738}{C:$28FFFF}Pouitím ochrannej mágie sme zabránili tomu, aby sa niekto zranil.
{19738}{19787}{C:$28FFFF}No ak máme zaplati za škody ...
{19787}{19853}{C:$28FFFF}Budeme si musie poièa od Kuriko.
{19853}{19912}{C:$28FFFF}Urèite sa teraz niekde dobre baví.
{19912}{19968}{C:$28FFFF}Neteší ma, e jej to teraz skazíme.
{19968}{20036}{C:$28FFFF}Porozprávame sa s òou o tom zajtra.
{20036}{20114}{C:$28FFFF}Ale i tak by sme sa k nim u nemali pribliova.
{20114}{20174}{C:$28FFFF}Áno. Nesmieme jej spôsobi ïalšie problémy.
{20174}{20198}{C:$28FFFF}Správne.
{20198}{20241}{C:$28FFFF}Elizabeth, èo budeš ...
{20241}{20268}{C:$28FFFF}Hm?
{20286}{20322}{C:$28FFFF}Je preè.
{20355}{20394}{C:$28FFFF}Oh, aké úasné!
{20422}{20531}{C:$28FFFF}Rád by som si raz z takıch pohárov pripil na nás dvoch.
{20535}{20591}{C:$28FFFF}U èoskoro sa toho doèkáme, ...
{20622}{20654}{C:$28FFFF}Stalo sa nieèo?
{20654}{20702}{C:$28FFFF}Nie, ja len ...
{20702}{20742}{C:$28FFFF}Poïme sa pozrie ešte tamto.
{20742}{20766}{C:$28FFFF}Dobre.
{20899}{20934}{C:$28FFFF}Kuriko ...
{20958}{20997}{C:$28FFFF}Mama! Poïme tam!
{21413}{21478}{C:$28FFFF}Naozaj som jej len na archu?
{21478}{21561}{C:$28FFFF}Ale ja taká nechcem by, Kuriko!
{21968}{21999}{C:$28FFFF}Elizabeth...
{22028}{22059}{C:$28FFFF}Shikimori...
{22126}{22157}{C:$28FFFF}Shikimori.
{22186}{22249}{C:$28FFFF}Poïme domov, Elizabeth.
{22345}{22392}{C:$28FFFF}Shikimori...
{22497}{22528}{C:$28FFFF}Si v poriadku?
{22606}{22685}{C:$28FFFF}Elizabeth, nie je ti niè?
{22778}{22837}{C:$28FFFF}Tu je váš aperitív.
{22845}{22893}{C:$28FFFF}Ospravedlòte ma prosím.
{22893}{22994}{C:$28FFFF}Uvedomujem si, e momentálne alkohol ešte pi nemôeš. |Avšak ...
{23005}{23048}{C:$28FFFF}Ah. Áno.
{23128}{23167}{C:$28FFFF}V takejto chvíli.
{23173}{23204}{C:$28FFFF}Prepáè.
{23216}{23256}{C:$28FFFF}Musím si vybavi jeden hovor.
{23256}{23319}{C:$28FFFF}To je v poriadku. Poèkám, kım sa vrátiš.
{23415}{23536}{C:$28FFFF}To pretoe si sa nesústredil. |Preto som tebou preletela!
{23549}{23597}{C:$28FFFF}Mrzí ma to.
{23723}{23779}{C:$28FFFF}Nevolaj mi, keï som v práci.
{23784}{23847}{C:$28FFFF}Tak to bolo od teba kruté.
{23847}{23909}{C:$28FFFF}Kedy mi vrátiš moje peniaze?
{23909}{23989}{C:$28FFFF}Povedal som, e èoskoro. Ešte krôèik a dostanem sa k ohromnım prachom.
{24023}{24078}{C:$28FFFF}Hovorím o bohatstve rodiny Kazetsubaki.
{24080}{24169}{C:$28FFFF}To je jedno. Hlavne sa ku mne èo najrıchlejšie vrá.
{24169}{24268}{C:$28FFFF}Peniaze, èo som ti dala som si poièala od dos nepríjemnıch ¾udí.
{24268}{24328}{C:$28FFFF}No nie som jediná, ktorá si poièiava, však?
{24345}{24377}{C:$28FFFF}Odhalila si ma, vieš to?
{24377}{24424}{C:$28FFFF}Teraz váne. Rátam s tebou.
{24424}{24537}{C:$28FFFF}Ak to pokašleš, nabudúce to budú naštvaní chlapi, |èo a prídu navštívi. A nie ja.
{24553}{24604}{C:$28FFFF}Iste. Pochopil som.
{24642}{24701}{C:$28FFFF}To som rada.| Tak zatia¾!
{24813}{24908}{C:$28FFFF}Tak, ... |Je naèase zarobi ve¾ké peniaze.
{25032}{25073}{C:$28FFFF}Ty hnusnı ...
{25073}{25134}{C:$28FFFF}Take takto to je.
{25134}{25173}{C:$28FFFF}Strašné ...
{25183}{25218}{C:$28FFFF}Váne.
{25218}{25281}{C:$28FFFF}Cigarety sa predsa zahadzujú do popolníka.
{25350}{25468}{C:$28FFFF}Kuriko. Ve¾mi ma mrzí, e to prišlo tak náhle, no ...
{25478}{25502}{C:$28FFFF}A èo?
{25502}{25598}{C:$28FFFF}No. Ten hovor bol ...|Nie. Zabudni na to.
{25598}{25638}{C:$28FFFF}Èo sa stalo?
{25638}{25694}{C:$28FFFF}Hm ... No ...
{25694}{25751}{C:$28FFFF}Nieèo váne?
{25751}{25786}{C:$28FFFF}No. Vlastne áno.
{25786}{25834}{C:$28FFFF}Pravdou je ...
{25834}{25934}{C:$28FFFF}e naliehavo potrebujem peniaze ...
{25934}{26028}{C:$28FFFF}Ve¾mi ve¾a peòazí.
{26036}{26062}{C:$28FFFF}Páni.
{26251}{26294}{C:$28FFFF}Kuriko!
{26340}{26388}{C:$28FFFF}Èo ste zaè?
{26388}{26429}{C:$28FFFF}Buï ticho ty suknièkár!
{26450}{26510}{C:$28FFFF}Kuriko, snaí sa a podvies!
{26510}{26571}{C:$28FFFF}Prahne po tvojich peniazoch!
{26571}{26638}{C:$28FFFF}Toto ti neodpustím.| Za to a rozsekám!
{26638}{26695}{C:$28FFFF}Èo to trepete?!
{26695}{26779}{C:$28FFFF}A kto dopekla vôbec ste?!
{26790}{26845}{C:$28FFFF}Som dcéra Kuriko!
{26899}{26942}{C:$28FFFF}Dcéra?
{26995}{27055}{C:$28FFFF}Èoe? Znamená to, e si sa u raz vydala?
{27078}{27173}{C:$28FFFF}Vôbec tıch ¾udí nepoznám.
{27186}{27245}{C:$28FFFF}Neviem kto ste a odkia¾ ste sem prišli.
{27245}{27318}{C:$28FFFF}No robíte zbytoènı rozruch a rušíte ostatnıch hostí.
{27318}{27373}{C:$28FFFF}Prosím, odíïte.
{27394}{27422}{C:$28FFFF}Kuriko!
{27422}{27497}{C:$28FFFF}Oh, Kuriko! |Robíš ve¾kú chybu, Kuriko!
{27497}{27524}{C:$28FFFF}Kuriko!
{27528}{27555}{C:$28FFFF}Kuriko!
{27563}{27590}{C:$28FFFF}Kuriko!
{27599}{27626}{C:$28FFFF}Kuriko!
{27652}{27707}{C:$28FFFF}Ak nie je iná monos, potom musím poui násilie!
{27707}{27730}{C:$28FFFF}Áno!
{27764}{27798}{C:$28FFFF}Ste takí hlúpi!
{27858}{27958}{C:$28FFFF}Hovorím, e si to celé zle vysvet¾ujete.| Choïte domov!
{27958}{27994}{C:$28FFFF}Sekni po òom!
{27994}{28030}{C:$28FFFF}Je to pre tvoje dobro, Kuriko!
{28030}{28066}{C:$28FFFF}Presne tak. Nechaj to na nás!
{28066}{28094}{C:$28FFFF}Kuriko!
{28094}{28142}{C:$28FFFF}Odchádza preè. Zdrhá!
{28142}{28241}{C:$28FFFF}Oh, umlète ich u niekto!
{28614}{28655}{C:$28FFFF}Èo sa deje?
{28655}{28696}{C:$28FFFF}Pustite ma úchyláci!
{28696}{28744}{C:$28FFFF}Èo ste vlastne zaè?
{28907}{28941}{C:$28FFFF}Metropolitná polícia?
{28960}{28999}{C:$28FFFF}Presne tak! Sme od polície.
{29063}{29106}{C:$28FFFF}Inšpektor!
{29154}{29207}{C:$28FFFF}Ah, skvelá práca!
{29207}{29262}{C:$28FFFF}Toto je nahrávka s celou tvojou vıpoveïou.
{29287}{29330}{C:$28FFFF}Zašiel si priïaleko.
{29390}{29445}{C:$28FFFF}Eh ... Kuriko ...
{29447}{29540}{C:$28FFFF}Išli sme okolo z reštaurácie rıchleho obèerstvenia, ...
{29556}{29603}{C:$28FFFF}Aby ste to tu znièili, chcela si poveda.
{29628}{29675}{C:$28FFFF}Nemôem uveri, èoho ste sa dopustili!
{29675}{29751}{C:$28FFFF}Mrzí ma to. |Pokúsim sa rıchlo zohna peniaze a ...
{29751}{29782}{C:$28FFFF}Tak som to nemyslela.
{29790}{29854}{C:$28FFFF}Hovorím o tom muovi, s ktorım som bola.
{29854}{29936}{C:$28FFFF}No my sme mysleli, e si sa ním nechala oklama ...
{29936}{29971}{C:$28FFFF}Mılili ste sa.
{29985}{30119}{C:$28FFFF}Bol to známy podvodník. A polícia ma poiadala, aby som im ho pomohla dolapi.
{30119}{30262}{C:$28FFFF}Staèilo len získa dôkaz o tom, e chce peniaze. |Potom ho mohli zatknú.
{30262}{30287}{C:$28FFFF}Èoe?!
{30287}{30370}{C:$28FFFF}Ale Kuriko. Èo tie peniaze, ktoré si od neho dostala?
{30370}{30441}{C:$28FFFF}Oh, tie? To len ...
{30445}{30485}{C:$28FFFF}Nemuseli ste mi ich vráti tak náhle.
{30485}{30533}{C:$28FFFF}Bolo by to v poriadku.
{30533}{30583}{C:$28FFFF}Mu by mal vdy plati za svoje rande.
{30583}{30633}{C:$28FFFF}Dokonca, aj keï som zabudol svoju peòaenku,
{30633}{30711}{C:$28FFFF}nemôem dopusti, aby za mòa platila dáma.
{30833}{30918}{C:$28FFFF}A ty si nemusela Rin spôsobi to¾ké problémy.
{30949}{30984}{C:$28FFFF}Kuriko...
{31015}{31055}{C:$28FFFF}Kuriko...
{31055}{31102}{C:$28FFFF}Take ti u nie som na archu?
{31109}{31204}{C:$28FFFF}Robi problémy mne bohato staèí, nemyslíš?
{31234}{31306}{C:$28FFFF}Váne. Èo mám s tebou robi?
{31314}{31347}{C:$28FFFF}Kuriko!
{31350}{31391}{C:$28FFFF}Kuriko!
{33580}{33760}{C:$FFB062}Preklad, úprava a èasovanie - John Sedrik||(8. 8. 2008)
{33805}{33850}{C:$28FFFF}A tak sme špehovali.
{33850}{33898}{C:$28FFFF}Ten chlap bol váne úbohı!
{33898}{33944}{C:$28FFFF}Hej. Ja som tá, ktorá by mala by naštvaná!
{33944}{33981}{C:$28FFFF}Ale váne. Vïaka vám ...
{33981}{34024}{C:$28FFFF}Mimochodom Yuna, èo bude v ïalšej epizóde?
{34024}{34112}{C:$28FFFF}Správne! Ïalšia epizóda Maburaha má názov "Rozhodli sa"
{34112}{34136}{C:$28FFFF}Prosím, poz ...
{34136}{34176}{C:$28FFFF}Nesna sa meni tému!
