{1}{1}29.970
{102}{162}TaSHee's Gang uvádza
{577}{776}GUNSLINGER GIRL
{3676}{3822}Povedz Eleonora, môeme na Sicíliu vstúpi autom, však?|
{3925}{3963}Hmm, pozrime sa....
{3963}{4092}Áno, môeme. Trajekt odchádza z Reggio di Calabria.
{4092}{4195}Ïakujem za tvoje organizaèné zruènosti, |vdy môem bra veci na¾ahko.
{4270}{4460}Táto cesta bola tie pouitá Románskou Armádou| na napadnutie Gréckeho mesta na Sicílii.
{4531}{4637}No teraz dúfam, e tam nemáš farbu mojich trenírok...
{4814}{4912}FEBBRE ALTA
{4979}{5140}Ostaneme v hotelovej izbe tak ak sa| nieèo stane budeme tu okamite.
{5154}{5221}Nemusíš si robi starosti Fella. 
{5239}{5355}Spomínaš na Elsin prípad?| Potrebujeme aby si bol extrémne opatrnnı.
{5371}{5487}Henrietta, ochráò Joseho-san.
{5487}{5513}Áno.
{5632}{5682}Je to nádhernı dom.
{5716}{5843}Nie je správne obdobie, ale s rodinou sem jazdíme cez leto.
{5879}{5966}Rodina? S Jeanom-san?
{5991}{6040}Áno, nii-san tu bol tie...
{6138}{6204}ale teraz som s tebou Henrietta.
{6263}{6307}Poïme na terasu.
{6775}{6888}Vrátime sa v inom období.| Sicília je cez leto nádherná.
{6910}{6991}Vezmeš ma sem znova?
{7010}{7066}Vezmem a sem to¾ko krát ko¾ko budeš chcie.
{7206}{7228}Henrietta.
{7290}{7368}Odlo púzdro a SIG za tvojou koše¾ou.
{7421}{7437}Tu.
{7465}{7581}Nie! Potrebujem to na tvoju ochranu José-san!
{7603}{7732}Toto sú prázdniny a sme tu iba ako reportér a jeho neter.
{7791}{7883}Obyèajné dievèatá to nenosia.
{7939}{7990}Obyèajné dievèa?
{8027}{8046}Áno.
{8455}{8607}Bóe toto nie je nieèo kde by sme mali ís za prácou.
{8628}{8758}Áno, keï sme tu cítime sa ako by sme boli v centre sveta.
{8781}{8859}Mono môeš zmeni svoje zamestnanie a| pracova pre cestovnú kanceláriu.
{9009}{9211}Sme ochraòovaní prístrojom...|a teraz prístroj ochraòujeme....aké ironické.
{9235}{9384}Nemáme èas na zbytoèné kecanie.| Vdy sa uisti o opatrnosti.
{9399}{9432}Áno, viem.
{9612}{9783}Tí dvaja ...sú zo sekcia dva. Nemyslím,| e sme sa potrebovali skry.
{9799}{9926}Pre prípad. Je lepšie sa vyhnú monım problémom.
{10197}{10232}Mohli by by vonku?
{10449}{10567}Hej, hej nestrie¾aj nás. Sme |z Korporácie Sociálneho Zabezpeèenia.
{10611}{10709}Sme zo sekcie 1. Som Pierto Fermia.  |Toto je Eleonora Gabrieli.
{10741}{10787}Triela nás predstavila.
{10802}{10829}Povedal Sekcia 1?
{10845}{10892}Yo, pán reportér.
{10941}{11008}Èo od nás chcete? Sme na prázdninách.
{11027}{11157}Zobrali sme si prípad tıkajúci sa Elsy,| tak sme vám prišli poloi pár otázok.
{11172}{11213}Môem ís dnu?
{11251}{11299}Áno, vstúpte.
{11405}{11427}Henrietta.
{11529}{11619}Oh, v tomto dome nepovo¾ujem iadne zbrane.
{11634}{11666}Dajte ich sem.
{11720}{11826}Ako som povedal sme na prázdninách.| Nechcem cíti iadnu zbraò.
{11882}{11971}Dúfam, e sa mi nechystáte vzia moju vzácnu "zbraò."
{12005}{12075}Potom nech to tu opustia vaše ústa.
{12164}{12231}Elsin prípad bol dokonèenı však?
{12252}{12272}Áno.
{12296}{12390}Potom všetko èo ostáva je chyti teroristov.
{12416}{12487}Dobre to èo sa môe sta...
{12545}{12657}ale stále nie som dos spokojnı,| tak som sem prišiel utajene.
{12673}{12761}Fermi-san, nie sme tu na šéfov príkaz?
{12778}{12869}Povedal som šéfovi, e moja stará mama skolabovala.
{12884}{12946}Tak sme tu na poloviènı úväzok.
{12991}{13026}Preèo ste nás prišli pozrie?
{13102}{13267}Povedal som to triela, ak chcem viac vedie o Fratelle,|potom by som sa mal porozpráva s vami.
{13292}{13318}Rozumiem.
{13401}{13518}Henrietta, môeš pripravi veèeru?
{13518}{13543}Áno.
{13644}{13715}Vie urobi všetky dievèenské práce?
{13741}{13884}Zdá sa, e trénovala v Korporácii,|ale pochybujem, e môeme dúfa pokia¾ ide o chu.
{13922}{13949}Eleonora.
{13973}{14041}Áno, áno. Idem sa prizera.
{14199}{14328}Tak , získal si jej obdiv cez aplikáciu zvaná "stabilizovanie?"
{14346}{14496}Stabilizovanie je vyíté pre mechanické telo. |Henrietta nie je vınimka.
{14536}{14752}Nemenil som jej obdiv, ani to ako ma má |ve¾mi rada cez "stabilizovanie."
{14786}{14825}Si odlišnı?
{14863}{14940}Nezáleí ma odpustené ak je stupeò stabilizovania slabı.
{14978}{15014}To pripúšam.
{15052}{15143}Viem èo s òou robi pre svoje dobro a Korporáciu...
{15187}{15219}Viem to.
{15333}{15375}Èo chceš pripravi?
{15391}{15475}Umm...paradajkovú polievku.
{15558}{15583}To je všetko?
{15606}{15619}Áno.
{15720}{15779}Dobre, poïme spestri menu.
{15812}{15904}Ale neviem urobi niè, ak nemám recept.
{15904}{16020}Som si istá, e tu niekde mám vystrihovaèku...|tu našla som to.
{16053}{16143}Pre cestoviny musia paradajková omáèka a tuniak vrie.
{16172}{16313}Marináda z kalmárov, krátko krké mušle, |mušle a ostatné morské jedlo.
{16332}{16366}Máš to?
{16378}{16460}Skvelé je to ako magická vrecková kniha.
{16474}{16524}Nie je to niè také, iba mám zlú pamä.
{16524}{16613}Ak by som nemala nieèo takéto,| vyhodili by ma z Korporácie.
{16638}{16696}Vykona dobrú prácu je...
{16709}{16808}je nahromadená z jednoduchıch úloh.
{16826}{16847}Správne.
{16866}{16917}Kde si to poèula?
{16940}{17005}Huh? Kde som to poèula?
{17041}{17078}Zrazu som zabudla.
{17134}{17156}Oh, dobre.
{17175}{17241}Dobre pre zaèiatok poïme nakupova.
{17259}{17276}Áno.
{17322}{17381}Skutoène vyzeráš ako on.
{17381}{17439}Aká je to láska, ktorú cítiš?
{17439}{17553}Cítiš to niekedy akoby to mohlo by ovplyvnené korporáciou?
{17568}{17698}Práve teraz som ve¾mi šastná,| tak sa skutoène nestarám...
{17718}{17819}Ale keï dostaneme prípad z korporácie,
{17845}{17964}cítim, e to musím urobi, vzh¾adom |k tomu, chcem to urobi.
{17987}{18051}Je totálne zamilovaná.
{18067}{18163}Gabrieli-san, si milenka Fermiho-san, však?
{18217}{18235}Èo?
{18235}{18401}Vieš, i keï mu a ena spolupracujú nemusia by milenci.
{18401}{18568}Ale, Gabrieli-san, ste vysoká a vyzeráte ako modelka.|Vyzerali by ste dobre s Fermim-san..
{18635}{18719}Hodí sa k drsne vyzerajúcim enám.
{18747}{18768}Nie.
{18793}{18820}Áno, hodí.
{18928}{18947}Henrietta!
{18992}{19101}Tvoje mechanické telo je nepouite¾né keï sa nekoncetruješ.
{19124}{19144}Tu.
{19187}{19215}Ïakujem.
{19232}{19280}Nemala si tašku?
{19346}{19365}Chytím ho.
{19365}{19393}Poèkaj.
{19978}{19992}Našla som ho.
{20523}{20557}Vrá mi to.
{20607}{20624}Ty...?
{20690}{20805}Moja taška. Prosím vrá mi ju.
{20851}{20959}Moja taška. Prosím vrá mi ju.
{20959}{21042}Èo je s tebou? Stra sa!
{21345}{21381}P-prestaò!
{21534}{21553}Prestaò!
{21569}{21661}Taorminská polícia. Vrá jej ju spä.
{21678}{21789}Neviem o èom hovoríte. |Dôleitejšie je èo robí to decko.
{21811}{21854}Henrietta, nechaj ho.
{21953}{22001}Rıchlo, daj jej to.
{22020}{22057}O èom hovoríte?
{22069}{22107}Oh? Snaíš sa oklama sám seba?
{22107}{22211}Ak to naozaj máš èestne jej to, nechám a ís, ale...
{22225}{22322}Chceš aby som a dôkladne preskúmala?
{22386}{22455}Páchneš od marihuany.
{22680}{22746}Je to pre teba tak dôleité?
{22787}{22901}Je to fotoaparát, ktorı mi Jose-san dal.
{22917}{22939}Ahá.
{22977}{23061}Gabrieli-san, tá vrecková kniha...
{23086}{23136}Yup, magická vrecková kniha.
{23167}{23278}Predtım ste bola ve¾mi drsná.
{23305}{23397}Predtım si bola ve¾mi desivá Henrietta.
{24126}{24227}Naozaj nemáte otázky o Elsinej smrti?
{24227}{24295}Èo tım myslíte?
{24360}{24402}Pozrime sa...
{24505}{24616}Ak by som mal poui jedno slovo, |povedal by som príliš "èistá."
{24649}{24724}Oh, nevedel som, e veríte konšpiraènım teóriam.
{24724}{24860}Super mechanizované telo a jej dozorca bol zabitı |a hneï potom, sa našiel vrah.
{24906}{24939}Èo myslíte?
{24975}{25105}I keï majú mechanické telá vlastné| fyzické schopnosti a city,
{25105}{25184}ale neaktivujú sa ak majú nedostatok zamerania.
{25201}{25301}Tí dvaja boli prepadnutí v noci v parku však?
{25336}{25483}Ale....Jean povedal, e keï sú so svojím |dozorcom sú citlivé na nebezpeèenstvo.
{25503}{25622}Skutoène, keï som vèera videl Rico,|ochraòovala ho ak keby mala štít Aegis.
{25650}{25823}Pravdepodobne bola ostraitá na útok,|ale nebolo moné kona v tom èase, |tak pravdepodobne konala pod "štítom" pre Laura.
{25837}{25887}Nemám to rád.
{25887}{26019}Preèo ¾udia akceptujú nieèo ako |" prístroje ochraòujú ich dozorcov" ?
{26031}{26134}Môe to by pravda, ale nie je to správne.
{26192}{26294}Po prvé, rozmıš¾al som nad tım, |e mechanické telá sú nechutné....
{26308}{26468}Viac ako 50 % z ich tela je vyrobená z uhlíkovej stavby |a uhlíkovıch vlákien... a syntetickıch svalov.
{26485}{26606}Ale nakoniec, obe z nich Triela aj Henrietta |sú deti zaívajúce pubertu.
{26620}{26686}Je len krpec, ktorı sàka pri varení.
{26707}{26830}A taká je, keï a ochraòuje a zomrie,|iba pôjdeš a povie "nemôe to pomôc" ?
{27077}{27147}Boli šastní z môjho varenia.
{27163}{27252}Aj keï preto narobili sme si ve¾a problémov.
{27280}{27408}Henrietta, nemôeš znova tak šialene vyrazi.
{27501}{27636}Si dievèa, tak by si nemala by si pouíva |násilie. Rozumieš?
{27677}{27734}Ty tie, Gabrieli-san?
{27794}{27900}I keï sa zo mòa snaíš urobi dievèa...
{27900}{27943}Ale ty naozaj si...
{27962}{28077}Keï sme prišli, José-san vzal moju zbraò a povedal,
{28134}{28215}"Obyèajné dievèatá nenosia takéto veci."
{28243}{28451}Je to pravda, ale...som obyèajné dievèa?
{28470}{28571}Mám obrovskú silu a môem| zabíja ¾udí s holımi rukami.
{28587}{28700}I cez to môem krváca,| boles ma prejde takmer okamite.
{28734}{28943}Pre stroj ako som ja na pouitie pre Josého-san, |nemôem by obyèajné dievèa.
{28943}{28969}Mıliš sa!
{29010}{29201}Povauje a za dôleitú a chce aby si sa usmievala.
{29224}{29441}Gabrieli-san, ja...viem preèo Elsa zomrela.
{29483}{29637}Prosím zavolaj Josého-san a prines mi moju zbraò.
{30169}{30213}Prosím daj mi zbraò.
{30213}{30277}Poèkaj, najprv to vysvetli.
{30370}{30489}Fermi-san, Elsa milovala Laura, správne?
{30489}{30530}Vyzeralo to tak.
{30548}{30664}José-san bol k nej Lauro-san milı?
{30677}{30768}Nie, nevenoval jej iadnu pozornos ne poèas práce.
{30799}{30909}Áno. Stalo sa pravdepodobne toto:
{30931}{31161}Ak ho ve¾mi milovala a jej láska |nemohla nikdy vykvitnú, potom...
{31404}{31432}Keby som bola òou,
{31542}{31618}zabila by som svoju lásku a...
{31787}{31811}urobila toto.
{32574}{32633}V poriadku, nechcela som strie¾a.
{32675}{32831}V iadnom prípade by som ti nechcela ublíi,| tak aby som mohla spácha sebevradu.
{33084}{33219}To dievèa....bolo váne?
{33428}{33469}Bola to celkom fraška.
{33508}{33617}Vedela si dôvod pred Elsinou smrou, však?
{33638}{33708}Preto, keï som sa jej snaila da zbraò...
{33772}{33873}Tak to bola pravda tıch dvoch guliek.
{33915}{34009}Toto je horšie ne zomrie pri ochrane jej dozorcu.
{34090}{34118}Dáte to do správy?
{34118}{34248}artuješ? Sekcia dva by po tomto prípade |bola pravdepodobne vyradená.
{34266}{34315}Teraz je to len hypotéza.
{34427}{34483}Predtım Henrietta bola...
{34497}{34557}Bolo to ako, e ti nevedome ubliovala.
{34581}{34676}Je to ako poveda "Ak ma nemiluješ, zastrelím a."
{34694}{34757}Cez to poèas toho dòa bola taká nevinná.,..
{34772}{34830}Nemôeme ju kontrolova pretoe je nevinná.
{34936}{35053}Oh áno, toto som našiel v Elsinej izbe.
{35084}{35121}Je to Laurova fotka.
{35174}{35302}Tak nakoniec, èo mala od neho bola táto fotka a jej meno... 
{35453}{35518}Pravdepodobnı ¾udia by pravdepodobne nezvládli takúto vec.
{35650}{35845}Vdy musím by niekto koho môe obdivova, |ale je to minimálne mnostvo lásky, ktoré jej vraciam.
{36206}{36291}A ? Èo chceš? Privies ma sem.
{36309}{36401}Lauro-san, pamätáš si tento park?
{36522}{36652}Tu si mi dal meno, Elsa de-Sica....
{36670}{36723}Oh, dal?
{36743}{36818}So prekvapenı, e si nieèo také pamätáš.
{36835}{36921}Je to nieèo dôleité èo nikdy nezabudnem.
{36937}{37036}Je to vzácny poklad, ktorı som od teba| dostala Lauro-san. Nikdy to nezabudnem.
{37058}{37096}To bolo to o èom si sa so mnou chcela rozpráva?
{37096}{37170}Vráme sa. Zajtra skoro vstávame.
{37221}{37285}Tu som dostala meno...
{37913}{37966}Ahoj, Henrietta.
{37992}{38021}Dovidenia.
{38037}{38056}Uvidíme sa.
{38065}{38077}Áno.
{38426}{38498}Dobre, kam chceš ís najskôr?
{38540}{38611}Je ve¾a miest k obhliadnutiu na Sicílii.
{38646}{38676}José-san!
{38691}{38796}Zavediem a tam hneï. |Uisti sa, e si si nezabudla foák.
{38822}{38840}Áno.
{39337}{39422}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime
{39453}{39515}www.mycolorfullife.blog.cz
