{1}{1}29.970
{78}{143}TaSHee's Gang uvádza
{578}{787}GUNSLINGER GIRL
{4360}{4443}Henrietta, máš ve¾kú chu na sladké?|
{4472}{4591}Nie.... Ale v poslednej dobe to nechutí sladko.
{4613}{4683} Tak mám sklon si tam da viac cukru.
{4737}{4841}V poriadku Henrietta, od teraz a |budem vola "cukrové dievèa"!
{4916}{4953}Bóe, Triela....
{4953}{5013}Iba artujem, len artujem.
{5576}{5597}U to viete, e?
{5641}{5679}Èoskoro zomriem napriek tomu...
{5703}{5800}Všetko zabudnem a zomriem!
{5821}{5960}Ak ku mne bude Marco-san takıto chladnı navdy,|chcem zomrie! Teraz!
{6031}{6118}Ak chceš zomrie, rob ako chceš.| Ja a nemôem zachráni.
{6697}{6768}STELLACADENTE
{6800}{6912}Henrietta dohodla si sa s tvojím dozorcom?
{6999}{7146}Spomínaš? Bola si jediná kto chcel sledova| meteorickı dáï na tréningovom poli, však?
{7178}{7298}Povedala si, e to odtia¾to nemôeme dobre vidie...|kvôli Rímskym mestskım svetlám v ceste, tak....
{7298}{7344}Oh, áno.
{7415}{7464}Oh, prepáè, teraz musím ís.
{7479}{7521}A? Bolo to v poriadku?
{7547}{7712}Yup. U som sa pıtala Josého-san.
{7813}{7848}Tu, pozri sa.
{7865}{7890}Áno.
{8018}{8098}Vidíš dvojité hviezdy, však? To je Rigel.
{8098}{8194}Tie hviezdy ¾udia nazıvajú "Nohou Oriona".
{8418}{8564}José -san, bude Angelica v nemocnici znova dlho?
{8590}{8608}Áno....
{8691}{8755}Všetci sú ustarostení.
{8787}{8850}Èo povieš na jej zajtrajšiu návštevu?
{8955}{8967}Áno...
{9005}{9216}Mono je to pre mestské svetlá z Rímu,|ale viem, ktoré môem vidie sú slabšie ne minule.
{9295}{9438}Zajtra, budeme na tréningovom poli,|tak ich uvidíme lepšie, však? Myslím meteorickı dáï.
{9464}{9515}Umm...Henrietta...
{9536}{9588}Áno?
{9663}{9914}Prepáè, mám neoèakávanú prácu a |...tak zajtra nemôem prís.
{9946}{10157}To je v poriadku nerob si s tım starosti, |som si istá, e sa niekoho môeme spıta.
{10241}{10274}To preto som ti povedala....
{10306}{10421}Ale povedal do vèera bolo všetko v poriadku...
{10421}{10490}Odvoláme zajtrajšie pozorovanie hviezd?
{10561}{10651}Hmm som si istá, e nejaké môeme vidie zo strechy ubytovne, ale...
{10783}{10926}V poriadku, na zajtra nájdem iného dozorcu.
{10926}{10951}Naozaj?
{10986}{11069}Yup. Kadı sa na to pozeral, tak...
{11069}{11102}Nie je to skvelé?
{11142}{11162}Áno...
{11207}{11270}Dobrú noc.
{11605}{11738}Bude to v poriadku. |Som si istá, e Triela s tım nieèo spraví.
{11774}{11794}Uhm...
{11951}{12142}Chcela som pozorova meteorickı dáï....s Josém-san...
{12972}{13002}U to viete však?
{13050}{13085}Èoskoro zomriem...
{13104}{13196}Chystám sa zabudnú a zomrie!
{13234}{13377}Ak ku mne bude Marco san takıto |chladnı navdy, chcem zomrie!
{13821}{13913}Bóe, Henrietta je taká pría...
{13938}{13983}Je to pretoe ju kazíš.
{14010}{14131}"Triela s tım nieèo urobí." To si myslí.
{14253}{14346}Oh, dobre hádam splním jej oèakávania.
{14509}{14562}Pravdepodobne ide navštívi Ange, však?
{14712}{14747}To bolo akceptovate¾né.
{14781}{14802}Áno.
{14954}{14980}Umm...
{14980}{14999}Èo je?
{15053}{15173}Chytá sa...Angelica zomrie?
{15215}{15253}Pravdepodobne nechce i príliš dlho.
{15350}{15400}Èas ivota mechanizovanıch tiel je obmedzenı.
{15438}{15489}Problém je ako to vyui.
{15556}{15625}Netráp sa. Stále máš nejakı èas.
{15667}{15693}Áno.
{15894}{15912}Ange?
{16186}{16297}Henrietta. Prišla si ma navštívi. Ïakujem.
{16354}{16392}Aké krásne kvetiny...
{16456}{16477}Ako sa cítiš?
{16514}{16679}Som trocha unavená a tie cítim závrate| a istı druh nestability.
{16751}{16808}Ale som v poriadku.
{16825}{16923}Som si istá, e sa èoskoro vrátim do práce.
{16944}{16983}Dúfam, e to bude èoskoro.
{17000}{17015}Yup.
{17161}{17243}To musí by šéfov pes.| Stretla som ho na ceste sem.
{17376}{17391}Ange..
{17499}{17566}Èo sa deje? Si v poriadku?
{17656}{17676}Pero?
{17707}{17727}Èo sa deje, Ange?
{17816}{17928}Meno...Meno môjho psa bolo pouité pre...
{18040}{18054}Ange?
{18076}{18092}Pero...
{18277}{18376}Henrietta? Kedy si prišla?
{18442}{18541}Aké prekrásne kvetiny. Ïakujem ti ve¾mi pekne.
{18717}{18773}Kde je Marco-san? Ešte neprišiel?
{18793}{18916}Nie, ešte tu nebol.|Som si istá, e je zaneprázdnenı prácou.
{19553}{19564}Claes...
{19658}{19846}By hospitalizovaná nie je príliš zlé, keïe ma ¾udia| chodia navštevova nieko¾ko krát za deò.
{19914}{19948}Niekto predtım prišiel tie...
{19969}{19994}Umm...jej meno bolo...
{20091}{20111}Áno...
{20196}{20367}Angelica, prepáè, e som ti predtım hovorila také tvrdé slová ...
{20384}{20657}Nie, ja sa ospravedlòujem.|I cez to si ma zachránila...|elám si by taká silná ako ty, Claes.
{20732}{20794}Nie som silná.
{20836}{20911}Nenávidím boles a tie sa bojím smrti.
{20939}{21309}Ale èítanie kníh a kreslenie obrázkov, pravdepodobne mi to len |hovorí, e neijem nepotrebnı ivot a nièoho ne¾utujem.
{21566}{21636}Povedz môeš dnes v noci bdie?
{21653}{21679}Preèo?
{21698}{21754}Dnes bude meteorickı dáï.
{21781}{21834}Pravdepodobne to odtia¾to budeš môc vidie.
{21870}{21889}Oh?
{21941}{22029}A ak to bude moné poèúva túto hudbu a pozoruj to.
{22054}{22071}Môeš?
{22108}{22123}Áno.
{22365}{22387}Hilsher-san.
{22454}{22482}Yo, Triela.
{22600}{22622}Èo sa deje?
{22647}{22768}Chcem aby si na nás dozeral, keï |budeme pozorova meteorickı dáï.
{22818}{22895}José-san nemôe prís keïe je zaneprázdnenı.
{22924}{23002}Prepáè, ale dnes som trochu zaneprázdnenı.
{23025}{23156}Celı zajtrajšok prekladáme tieto verejné |ochranné dokumenty do talianèiny.
{23190}{23335}Potom budem môc pomôc keïe môem preklada |ak to bude po Francúzky alebo Nemecky.
{23815}{23834}Marco-san.
{23942}{23963}Um...
{24012}{24032}Èo sa deje?
{24104}{24328}Ráno, keï som navštívila Ange,|si zrazu spomenula na svojho psa.
{24389}{24408}Chápem.
{24478}{24615}Keï to poviem aplikátorom budú super štastní a |navštívia ju pre získanie nejakıch dát.
{24689}{24776}Umm, kde je ten pes teraz?
{24806}{24827}Neviem.
{24855}{24907}Je nemoné ho násj?
{24974}{25089}Nemá to zmysel, ak ho nájdeme.
{25365}{25393}Marco-san!
{25550}{25603}Èo teraz? Stále je nieèo èo odomòa chceš?
{25688}{25767}Prosím choïte za Ange.
{25867}{25934}Doktori neustále èakajú na telefonát.
{25950}{26025}Ak sa nieèo stane budem informovanı.
{26090}{26124}Prosím.
{26173}{26268}Nie je niè èo pre òu môem urobi.
{26302}{26363}Nemusíte robi niè.
{26416}{26477}Všetko èo musíte urobi je by pri nej.
{26638}{26655}Prosím!
{26795}{26942}Henrietta, nebojíš sa smrti?
{26983}{27085}Nie ak zomriem pri ochrane Josého-san.
{27193}{27394}Nemáš iadny názor na dostanie mechanického| tela, zbrane a krátkej ivotnosti?
{27449}{27696}Ak s nami cítite alebo nás ¾utujete potom sa mılite.
{27840}{28029}Toto môe by podmienka , ktorú dostali, |ale ja som s tım vyrovnaná...
{28056}{28110}Stále...som s tım vyrovnaná.
{28303}{28365}Som si istá, e Ange tie.
{30360}{30386}Marco-san.
{30412}{30460}Bola si hore?
{30507}{30637}Nie, som v poriadku. Nabudúce budem pracova tvrdšie.
{30668}{30698}Nemusíš vstáva.
{30751}{30767}Áno.
{31261}{31294}Hmm...nevidím iadne padajúce meteory.
{31317}{31374}Mono ešte nieje èas.
{31399}{31480}Bude to èoskoro, pozerajte sa pozorne.
{31480}{31599}Bolo by to lepšie ak by toto miesto bolo ïalej od Ríma.
{31599}{31696}Ale máme dobrı zrak, tak...
{31753}{31781}Oh, videla som záblesk!
{31794}{31840}Naozaj? Kde? Kde?!
{31857}{31942}Videla som záblesk! Tam!
{32003}{32062}Vidíš Triela? Znova to preblesklo!
{32084}{32141}Hej Rico, upokoj sa.
{32160}{32245}Ale prvı krát vidím nieèo ako toto!
{32479}{32587}Som šastná, e si prišiel.
{32656}{32731}Poèula som, e v noci bude meteorickı dáï.
{32766}{32866}Claes mi povedala, e ho môem vidie aj keï budem tu.
{32952}{33030}Cítila by som sa sama, keby som sa pozerala sama, tak...
{33188}{33215}Rozumiem...
{33371}{33398}Je to také tiché...
{33520}{33660}Svet sa stal komplikovanım miestom a| my toho máme ve¾a na premıš¾anie.
{33675}{33787}Raz za èas, potrebujeme na to všetko zabudnú.
{33909}{33962}Keby som to mohla ukáza Ange!
{34018}{34141}Pravdepodobne sa pozerá a práve poèúva Deviatu Symfoniu.
{34183}{34236}Myslíš Deviatu Symfóniu od Beethovena?
{34236}{34266}Yup.
{34307}{34407}Je to perfektná symfónia pre noc ako je táto.
{34445}{34505}Deviata symfónia je pieseò èo znie ako...
{34638}{34667}Správne?
{35016}{35033}Poï spievaj.
{35659}{35679}iari to!|
{35723}{35745}Tak sa na to môeš pozera.
{36256}{36287}Je to krásné...
{36328}{36345}Áno.
{36440}{36469}Marco-san.
{36494}{36509}Èo sa deje?
{36567}{36608}Cestovinovı príbeh...
{36645}{36734}Môeš mi znovu poveda cestovinovı príbeh?
{36734}{36812}Oh! Áno iste vydr sekundu.
{36909}{37009}Dávno, tu bolo Cestovinové Krá¾ostvo.
{37026}{37188}V tom krá¾ovstve il princ, ktorı miloval |cestoviny a jedol ich kadı deò.
{37247}{37306}Èo je Alfonso?
{37328}{37452}Dievèata, ktoré normálne vradia teroristov |a hovoria tromi odlišnımi jazykmi,
{37466}{37558}spievajú Beethovena v prekliate chladnom poèasí.
{37638}{37705}Je to  nimi také plytvanie ako mechanickımi telami.
{38200}{38334}Cestovinovı princ povedal Princezne Pizza, |"Tento drak je..."
{38410}{38428}Angelica?
{38546}{38633}Zaspala si, Angelica?
{39166}{39240}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime 
{39274}{39433}/Dúfam, e sa vám príjemne sledovalo a chcem poïakova obom| mojim trpezlivım èasovate¾kám aj Myii aj WelWetce za trpezlivos.|A extra poïakovanie DeathTheKidovi, e sa mu chcelo pomáha mi :)/
{39489}{39552}Tìštì se na 2. øadu ;)|www.mycolorfullife.blog.cz
