{1}{1}29.970
{66}{120}Tashee´s Gang uvádza|
{578}{779}GUNSLINGER GIRL
{3920}{3991}Keï skonèíme s tım policajtom a zabiješ ho?
{3991}{4014}Áno.
{4014}{4149}Na chví¾u ste zachránení, keïe ešte nepoznajú vaše tváre.
{4149}{4229}Ale nezniujte pozornos.
{4229}{4317}Uistite sa, e ste vzali fotografie, tak| môeme neskôr vydiera Provinènú políciu.
{4331}{4358}Rozkaz.
{5092}{5142}Lauro-san, tu je Elsa.
{5142}{5209}Ako to vyzerá?
{5209}{5342}Je to rovnaké ako vèera, jeden policajt pred dverami.
{5342}{5467}Oh, áno? Môeš poui tvoju zbraò, tak sa nedr spä.
{5467}{5501}Áno.
{5501}{5549}Nezabudni vzia fotografie.
{6417}{6513}LYCORIS RADIATA HERB
{7609}{7667}Hej pán direktor....
{7667}{7837}Zaèali ste uvaova èi je lepšie pracova| s vládou alebo teroristami?
{7837}{7954}Ak to chcete saova, zabijem vás.
{7954}{8030}Som tie pekne zaneprázdnenı.
{8143}{8166}Lauro-san.
{8215}{8237}Skonèila si?
{8237}{8331}Áno. Bolo to ¾ahké...
{8331}{8379}Vzala si obrázky?
{8393}{8421}Áno.
{8519}{8638}Hej, ostal ti jeden vo¾nı. Mohla si ich poui všetky.
{8784}{8803}Hotovo.
{8839}{8921}Vytlaè ich, keï sa vrátime do korporácie.
{8921}{8971}Ah, áno.
{8971}{9029}Fajn, èas sa pohnú.
{9353}{9491}200...20...3.
{9571}{9596}Euro?
{9596}{9719}Oiro. Nemecká mena sa èíta Oi.
{9719}{9748}Ok.
{9770}{9949}23 tie môeš èíta po jednotkách |tak to znie "drei hundert zwanzig."
{9969}{10032}Tieto èísla sa zvládneš nauèi rıchlo.
{10032}{10135}5.56 je "fuenf komma fuenf sechs."
{10135}{10249}7.62 je "sieben komma sechs zwei."
{10249}{10378}Elsa, potrebuješ s nieèím pomôc?
{10478}{10500}Nie.
{10532}{10563}Fajn.
{10704}{10894}Ak tam bolo 10 ¾udí všetci sa nemohli by znáša. |Platilo to pre oboch deti aj dospelıch.
{10894}{10982}Záhàòa to nás, ktoré sme boli kontrolované |stabilizáciou mentálnych odpovedí.
{11009}{11185}Elsa ila na ko¾aji sama a s nikım z nás sa nerozprávala.
{11304}{11304}Nechcela som dosiahnu rozhovor s òou, ale...
{11491}{11602}Triela, rozprávala si sa s Elsou, však?
{11602}{11710}Iba som jej povedala dôleité správy a veci.
{11732}{11827}Mám problém s òou zaèa komunikova.
{11845}{12079}Je úplne mimo z Laura, preto ju nemám |rada. Keï má iba kúzlo ako vy.
{12104}{12209}Rozprávala si sa s òou aj cez to, e ju nemáš rada?
{12209}{12433}Ako by som to mala poveda...je ¾ahké vyhnú| sa ¾uïom, ktorıch nemáš rada a je to...
{12433}{12496}pohodlné ale ... myslím ...je to moja cesta.
{12589}{12687}Mimochodom odkedy priviedli Elsu,
{12687}{12810}... obe z vás ty a Claes ste ma desili pretoe ste boli rovnaké.
{12833}{12895}Tak poïakova sa Triele...?
{12895}{12952}Hej, nie som namyslená.
{13006}{13096}Všetko to závisí na na šarme èloveka a |stabilizovaní mentálnych odpovedí.
{13145}{13186}Šarm èloveka....
{13372}{13544}Claes je Ok, ale Elsa? Dobre Claes je tie pekne otvorená.
{13544}{13711}Èudujem sa....myslím, e je to nieèo odlišné.
{13836}{13940}Bála si sa ma, Triela?
{14002}{14128}Uh, hehe. Tu. Dnešnı koláè je Ricotta Tarte.
{14128}{14151} Je dobre upeèenı.
{14166}{14241}Ïakujem ti za vèetko èo robíš. Claes-sama.
{14241}{14323}Èo? Aké nemilé.
{14724}{14749}Marco.
{14749}{14859}Ah, Jose. Tie trénuješ?
{14859}{14901}Nieèo také.
{14901}{14980}Ako sa máš Angelica?
{14980}{15070}Moje zmysli sa vrátili.
{15099}{15194}Chápem. Netlaè na seba príliš tvrdo.
{15194}{15216}Áno.
{15692}{15783}V strie¾aní som stále lepší ako ty.
{15783}{15869}Ako sa v tom môem sta lepšia?
{15891}{15985}Ak by niekto vedel ako, rád by som to tie vedel.
{15985}{16086}Ak budeš ve¾a cvièi zlepšíš sa v tom.
{16086}{16116}Áno.
{16216}{16258}Yo Jose.
{16258}{16389}Lauro? Myslel som, e si šiel po Republikánoch v Toscane.
{16403}{16537}U som tam skonèil. Len prefektúra polície ich ochraòovala.
{16557}{16638}Tak iba potrebujeme k dokonèeniu prida nejaké hmaty.
{16638}{16685}Chápem.
{16685}{16837} Ak by ste mali tento tıdeò èas bol by som |rád, keby ste mi pomohli ak to nevadí.
{16863}{16923}Poviem ti o tom v noci.
{16923}{16950}V poriadku.
{16950}{17004}Ok uvidíme sa neskôr.
{17159}{17227}Budeme pracova s Elsou?
{17227}{17281}Myslím, e je to moné.
{17386}{17404}Poïme.
{17404}{17444}Ah, áno.
{18746}{18776}Kto je tam?
{18971}{18998}Èo chceš?
{19061}{19169}Myslela som, e by sme sa nachví¾u mohli porozpráva.
{19280}{19397}A kadı v celom meste vrátane polície ochraòuje teroristov....
{19397}{19578}...tak som pred pár dòami zabil pár policajtov ako| varovanie, ale riadite¾ nemôe stále robi všetko.
{19609}{19784}Namieste kde sa mi prestal vyhráa odhalil existenciu Korporácie.
{19784}{19890}A nakoniec som dostal povolenie od šéfa na jeho zabitie.
{19890}{20007}Hlavnı riadite¾ polície...nejaké plány?
{20007}{20116}Hej. Pripravil som sa predtım ako som prišiel.
{20133}{20221}Ústredie polície zabezpeèuje najlepšia ostrelovacia lokácia.
{20221}{20287}Jednoduché vyhra ak máme dvoch sniperov.
{20315}{20358}Strie¾anie ...
{20358}{20481}Èo sa deje? Je v tom Henrietta slabá?
{20481}{20581}Nie, je dobrá.
{20581}{20774}Ale ak som naokolí ja alebo iné mechanické telá |môe by príliš vystresovaná na to aby sa pokúšala vystreli.
{20989}{21118}Urobme to. Chcem Henriette doda nejaké sebavedomie.
{21167}{21198}Hej Jose.
{21219}{21359}Vdy sa takto obávaš o mechanické telo?
{21359}{21401}Áno.
{21401}{21500}Ak je to tak, sú fámy pravdivé?
{21500}{21552}Aké fámy?
{21552}{21569}Bojové fámy.
{21605}{21707}Kto vie. Polovica z nich môe by pravdivá.
{21777}{21917}Hej, vdy som sa na teba znechutene pozeral.
{21917}{22036}Nikdy som nemal rád ¾udí s krivou mys¾ou.
{22036}{22149}Èo? Potom ma nepozıvaj na drink.
{22149}{22253}Idiot. Pozıvaš ¾udí pretoe ich nemáš rád.
{22253}{22403}Ak sa nevieš obratne vyhıbaš ¾udom, ale namiesto| úprimného rozprávania ako je toto môeš premıš¾a.
{22403}{22551}"Oh on je takıto druh èloveka."
{22569}{22674}Potom môeš porozumie tomu èloveku...
{22691}{22794}a veci, ktoré nemáš rád na òom zaènú by fajn.
{22822}{22979}Po rozhovore si myslím, e si dos dobrı chlap, Jose.
{22979}{23032}Preèo, ïakujem.
{23080}{23218}I Kennedy uvádza " Poïme prizna, e obaja sme odlišnı."
{23259}{23301}Nemáme sa o èom rozpráva.
{23328}{23448}Ale nabudúce spolu môeme pracova.
{23504}{23691}Potom ma nechaj poveda toto:|Ak sa pripletieš Laurovi-san do cesty, nikdy ti neodpustím.
{23903}{24032}Preèo? Preèo nemôeš by s ostatnımi?
{24062}{24227}Èo je pre teba viac dôleité: èlovek, ktorı je platenı |za teba alebo ostatné mechanické telá.
{24287}{24396}Lauro-san je pre mòa najdôleitejší.
{24396}{24503}O niè iné sa nestarám.
{24566}{24697}Míòam všetok èas pre Laura-san.
{24758}{24917}Ako uvaujem o Laurovi -san a èistím túto pušku....|Pre Laura-san.
{25069}{25171}Ešte neviem ako dlho môeme i.
{25203}{25278}Nemáš dostatok lásky!|
{25528}{25677}To nie ... To nie je pravda!
{25677}{25847}Ja.. Jose san milujem. Ve¾mi!
{25969}{26155}Je to tak? Potom sa s tebou nemám o èom rozpráva. Odíï.
{26682}{26719}Hej Lauro.
{26754}{26815}Hmm? Èo je?
{26878}{26995}Rozumiem, e si niekto kto si cení ¾udské vzahy.
{26995}{27113}Ïakujem. To je horšie na pití spoloène.
{27174}{27239}Ale nie si chladnokrvnı k Else?
{27294}{27412}Nemiešaj dokopy kolegov a mechanické telá.
{27502}{27606}Narozdiel od teba, nechcem by zapojenı v nieèom takom.
{27799}{28013}Súhlasím mechanické telá sú skvelé.
{28013}{28048}Budú dra tvoju zbraò ale pre teba pôjdu |kúpi Panini ak im to povieš urobia to.
{28048}{28361}Ale niè od nich nemáš. Nechcem pracova,| keï sa budem cíti zle pre všetky deti zo Sekcie Dva.
{28497}{28670}Oh, toto je len môj názor.|Môeš si myslie, e je to pre teba najlepšie.
{28723}{28753}Povedz, Lauro...
{28775}{28854}Preèo si prišiel do Korporácie?
{28854}{28900}Pretoe dobre platia.
{28952}{29046}Šiel som pretoe som èo najskôr potreboval peniaze.
{29202}{29331}Mechanické telá znamenajú ve¾a nepríjemností....|Prevedú nás všetkım druhmi problémov, nemyslíš?
{29397}{29490}Nemáme dos ¾udí, ktorí by sa o ne starali.
{29520}{29558}Heh, správne.
{29895}{29947}Si pripravenı, Jose?
{29947}{29987}Hej.
{29987}{30069}U som poslal všetko objemné vybavenie.
{30092}{30156}Si inteligentnejší ne som si myslel.
{30156}{30192}Hádam.
{30810}{30846}Henrietta.
{30846}{30879}Áno?
{30879}{30929}Si prvı krát v Siene?
{30947}{30984}Áno. Prvı krát.
{30984}{31100}Potom sa po zajtrajšej práci môeme porozhliadnu po meste.
{31221}{31244}Áno.
{31862}{31900}Lauro-san.
{31979}{32110}Na tejto misii zo seba vydám všetko.
{32190}{32254}Oh, potom to urob správne.
{33128}{33344}Ak je hlavnı riadite¾ zabitı v hlavnom stane...|Bude to skvelı k-kód pre perfektnú políciu.
{33345}{33448}Mimochdom preèo si vybral takéto miesto?
{33448}{33657}Mám dobre spojky. Plus ak dos tvrdo kopeš| ve¾mi pekné múzeá patria vláde.
{33657}{33776}Lauro-san môem striela s Hecate?
{33776}{33871}Pre prípad si priprav tvoj SIG.
{33871}{33959}Bude lepšie ak to nebudeme musie poui.
{33959}{33979}Áno.
{34152}{34251}Lauro, ako je na tom Elsa?
{34296}{34369}Huh? Èo myslíš tım "Ako je na tom?"
{34369}{34484}Niè, iba to vyzerá akoby bola príliš horlivá.
{34484}{34571}Èasto im chıba cie¾, keï sú takéto.
{34630}{34770}Elsa nikdy predtım nezlyhala. |Nie je na to stabilizovanie mentálnych reakcií?
{34770}{34880}Tvoja nevinnos odíde príliš rıchlo a stane sa sarkazmom.
{34880}{34921}Hádam.
{35448}{35550}Prišli. To je auto hlavného riadite¾a.
{35550}{35608}Cie¾ by mal by v druhom aute.
{35608}{35703}Zamierte na neho, keï vystúpi z auta kım vystúpi po schodoch.
{35723}{35761}Pripravte si èasovanie.
{36141}{36192}Á-áno!
{36192}{36285}Hej! Tvoja bezpeènos je prvoradá.
{36285}{36358}Ah, ospravedlòujem sa!
{36450}{36560}Jose, vezmi si Elsine miesto. |Dnes to pravdepodobne Elsa nezvládne.
{36560}{36618}- Nie som v poriadku. |- Dobre.
{36682}{36725}Lauro-san!
{36752}{36814}Prepáè Elsa.
{36814}{36902}Rıchlo! Cie¾ vychádza z auta.
{37138}{37155}Vporiadku.
{37689}{37734}Ok. Dobrá práca.
{37788}{37833}Rıchlo, vypadnime odtia¾to.
{37898}{37938}Elsa nebuï neopatrná!
{38244}{38291}Aká neuitoèná.
{38690}{38734}Henrietta.
{38734}{38769}Áno.
{39364}{39448}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime
{39490}{39569}www.mycolorfulliufe.blog.cz
