{1}{1}23.976|Do.You.Like.Spring.Bear.DVDrip.XviD.AC3-RF
{964}{1057}{Y:i}TUBE Entertainment presents
{1072}{1155}{Y:i}An Ison film production
{1171}{1267}Nedávno jsem zaèala |pùjèovat knihy o umìní...
{1269}{1364}tátovi, kterı je |podøadnı spisovatel.
{1403}{1457}{Y:i}Èást 1 [První zpráva]
{1458}{1568}Svaèina, sušené chobotnièky, pití...
{1605}{1736}Svaèina, sušené chobotnièky, pití...
{1840}{1925}Pane? Nenašly by se |tam vaøená vejce?
{2897}{2977}Mám tì tak rád.
{2978}{3043}Jako medvìd zjara.
{3062}{3164}Znám tvá tajemství.
{3166}{3310}Jsi jak roztomilı medvídek.
{3312}{3441}Moje láska k tobì |teprve zaèíná.
{3542}{3653}Další kniha je od Gustava Caillebotta...
{3654}{3727}"Mladı mu u okna"
{3731}{3880}MÁŠ RÁDA MEDVÌDY NA JAØE?|(JARO, MEDVÌDI, LÁSKA)
{3918}{3950}- Hyun-chae?|- Ano?
{3952}{4033}- Zajdeme se najíst.|- Dobøe..
{4086}{4126}Pospìš si!
{4286}{4373}- Ty jsi tak ubohá...|- Ne, on mì neodkopnul!
{4374}{4441}Zkoušky... taková ubohá vımluva!
{4443}{4528}Øíkal, e ho èekají zkoušky |ohlednì pracovního povıšení.
{4530}{4662}Coe? Ty jsi ale osel.|Neudìlala jsi nìco špatnì?
{4664}{4739}- Dìlala jsi všechno tak, jak jsem ti øekla?|- Jasnì.
{4741}{4836}Take jste se potkali u kavárny a pak?
{4875}{4955}Šli jsme na "Jeden pìknı jarní den", |jak jsi mi radila.
{4957}{4996}Nekoupila jsem si popcorn, protoe...
{4998}{5095}jsi øíkala, e vıkám moc nahlas.
{5180}{5219}A co obleèení?
{5227}{5283}Elegantní podle plánu!
{5285}{5416}Dokonce jsem si stoèila |vlasy na stranu.
{5434}{5497}Není to Sokcho? |Tam to znám!
{5498}{5571}Byla jsem tam jednou s tátou.
{5573}{5655}Mají tam vıborná jídla z chobotnic.
{5657}{5694}Aha, chápu.
{5954}{6041}Hele, podívej! Budou se líbat.|e se budou líbat?
{6143}{6209}Jestlipak si herci vyèistili zuby...
{6210}{6295}Myslím ne se políbili.
{6306}{6353}Vsadím se, e jo.
{6443}{6574}Proboha! |Poškrábal jí nové auto.
{6738}{6794}Díky.
{6822}{6914}Divné...|Ten film vypadal zajímavì.
{6915}{7014}Taky byl.
{7016}{7068}Líbí se ti tahle píseò?
{7105}{7157}Ano...
{7167}{7226}Ta melodie je pøekrásná...
{7227}{7319}Tahle píseò mi strašnì pøipomíná |film "Baghdad Cafe".
{7321}{7426}Holá pouš, bumerang letí oblohou...
{7460}{7528}Tuhle písnièku znám. Je skvìlá...
{7530}{7581}hlavnì tahle èást.
{7944}{7998}Pøesnì tak..
{8045}{8129}Obèas pozdì v noci slyším, |jak ji hrají v rádiu...
{8131}{8173}a nemùu se ubránit pocitu.
{8174}{8235}Vdy víš...
{8241}{8281}Pocitu?
{8285}{8342}Tak pitomì smutnému!
{8447}{8546}- Je to fakt divné...|- Copak?
{8548}{8659}Nejsi zase tak ošklivá.
{8661}{8769}Máš snad nìjaké strašlivé tajemství...
{8771}{8854}o kterém jsi mi neøekla?
{8882}{8925}Nemohly jste na mì poèkat?
{8927}{9005}My èekaly.
{9059}{9144}Proto jsme ještì |nezaèaly jíst.
{9146}{9182}- Co se dìje?|- Tady táta.
{9184}{9237}Nejdøív se najíme a...
{9238}{9299}Nemùu, protoe musím |od zítøka nastoupit na noèní...
{9301}{9366}Strašnì potøebuju tu kníku.
{9368}{9480}Tak si øekni nìkomu jinému.|To tam nemáte knihovny?
{9512}{9565}Tati!
{9567}{9616}- Slyšela jsi to?|- Co?
{9618}{9686}Ve škole hrála strom...
{9687}{9734}ve høe...
{9735}{9857}Víla a døevorubec...
{9870}{9925}kousek od chlapce, |kterého mìla ráda.
{9927}{9981}Ale kdy víla zaèala...
{9982}{10018}s chlapcem flirtovat...
{10020}{10071}úplnì jí pøeskoèilo.
{10073}{10107}Strašidelnı, e?
{10109}{10174}Vypadá poslušnì...
{10176}{10230}ale je pìknì vıbušná.
{10246}{10287}Na støední to bylo ještì horší.
{10289}{10311}Co se stalo?
{10313}{10395}Líbil se jí takovej |krátkonohej nadhazovaè...
{10397}{10448}- Krátkonohej nadhazovaè?|- Jo.
{10450}{10496}Take poøád nosila na hlavì |baseballovou èepici...
{10498}{10563}aby mohla bıt s tımem.
{10565}{10623}Ještì teï má na hlavì |ztvrdlou kùi.
{10625}{10754}Nedivím se, e je tak silná.
{10830}{10882}Ten byl dobrej!
{10898}{10954}Pozor na druhé metì!
{11025}{11049}{Y:i}Chci bıt tvùj zadák navìky!
{11051}{11105}A co se stalo?
{11106}{11156}No...
{11169}{11253}Promiò, pøestupuju k fotbalistùm.
{11255}{11317}Hej, Chanho!
{11354}{11405}- Dìlej, pojï sem.|- Pìknì ji odkopl, uboaèku.
{11406}{11446}Pozor, u se vrací.
{11517}{11581}{Y:i}Mohly bychom si o víkendu |vymìnit smìnu?
{11583}{11630}- To místo je hroznı!|- Ale není, je fajn!
{11631}{11670}- To teda ne!|- No, rıovı koláèky tam jsou dobrı.
{11672}{11745}- Ne.|- Ale...
{11790}{11851}To si øíkáte kamarádky?
{11919}{12046}{Y:i}BAE DOO NA
{12090}{12214}{Y:i}KIM NAM JIN
{15487}{15550}Knihy o umìní jsou u okna.
{15552}{15601}Dìkuji.
{16082}{16153}Další zastávka je Chongda...?!...
{16257}{16306}Sakra!
{16390}{16537}Další zastávka je... Chongdam.|Stanice Chongdam.
{16539}{16653}Vystupujte na pravé stranì.
{16846}{16882}Jung Hyun-chae!
{17590}{17637}Jsi to ty!
{17659}{17713}Moje medvídì!
{17755}{17802}Moje medvídì!
{17827}{17888}Našel jsem tì!
{17890}{17945}A co ta kniha?
{17947}{17988}Kde ji máš?
{17990}{18053}Hups, zapomnìl jsem ji vzít.|Vydr. Ani se nehni!
{18112}{18169}Proboha, co teda našel?
{18381}{18444}Ty jsi opravdu øidiè metra, e?
{18446}{18523}Jo. Nikdo neøídí draší auto...
{18525}{18560}ne já.
{18592}{18677}Ani trošku ses nezmìnil.|Poøád se vytahuješ.
{18678}{18751}- Kdy tì propustili z armády?|- Minulı rok.
{18753}{18809}Od té doby jsem byl v Busanu.
{18994}{19038}Je to ještì daleko?
{19040}{19094}Kdo øíkal, e chci doprovod?
{19119}{19243}- Kde bydlíš?|- A nahoøe. Sbohem.
{19323}{19358}Hyun-chae.
{19443}{19548}Pøijel jsem do Soulu, abych mohl |bıt blízko tebe. Je to osud.
{19622}{19679}Bıt blízko tebe. Je to osud.
{20426}{20484}Nemùeme se takhle rozejít.
{20486}{20551}Jsi pro mì ten pravı.
{20553}{20664}Hyun-chae! |Nemùe to fungovat!
{20666}{20703}Proè?
{20728}{20799}Proè ne?
{20848}{20897}Protoe...
{20918}{21049}Protoe nejsi èlovìk...
{21906}{21954}Hyun-Chae je tady?
{21956}{22000}Kdy jsi dorazila?
{22039}{22069}Pojï sem.
{22070}{22157}Kdy jsi to øíkal, |znìlo to tak vánì.
{22159}{22215}Netušíš, co jsem musela podstoupit, |abych ti tu knihu donesla.
{22217}{22269}Opravdu?
{22294}{22373}Na co ti vlastnì je?
{22375}{22599}U jsem ti to øíkal mockrát. Opravdovı |spisovatel musí bıt dobrı ve všech oblastech umìní.
{22601}{22664}Co øíkal doktor?
{22666}{22753}Spraví to menší operace.
{22754}{22877}Vidíš, øíkala jsem ti, |e máš pøestat kouøit.
{22878}{22951}Musíš pochopit, e kouøení je...
{22953}{23198}pro umìlce... jako vıchod.
{23200}{23259}Jo, umìní, jasnì...
{23464}{23565}- Tohle je tvoje?|- Právì mi to vydali.
{23567}{23620}Zaèíná se prodávat.
{23622}{23687}"Mu, kterı zvednul rùi"?
{23689}{23806}To je lacinı název...
{23828}{23893}To je pøesnì ono. Lacinost.
{23895}{24053}Velké filosofické myšlenky ukryté |uvnitø základní slovní zásoby.
{24152}{24311}V jeho rukou byla zvadlá rùe...
{24313}{24472}a z jejích oèí stékala pomalu slza.
{24554}{24676}Jak ti to zní? |Nedotıká se to tvého srdce?
{24703}{24762}Radši si dej obìd!
{25039}{25117}Je krásná, e?
{25118}{25172}Je hluchonìmá?
{25194}{25289}Je to krásná øeè. A neøíká se hluchá, |ale sluchovì postiená.
{26002}{26078}Myslíte... ty jsou pro mì?
{26463}{26513}Dìkuji vám!
{26547}{26709}{Y:i}Èást 2 [Druhá poznámka]
{26737}{26777}Hlupaèko...
{26779}{26864}Moje bláznivá, moje lásko.
{26866}{26993}Ty netušíš, kde jsem.
{26995}{27080}Jsem ti tak nablízku, tak blízko...
{27082}{27202}e bych do tebe mohl narazit.
{27204}{27328}A ty se zajímáš jen o obrazy.
{27367}{27484}Musíš mít ráda èervenou?
{27690}{27761}Take... úsmìv.
{27762}{27801}Nikdo nedokáe øíct "Ne" úsmìvu.
{27803}{27850}Ano, pane.
{27890}{27972}To je pro dnešek všechno.|Pøeji vám pìknı den.
{28240}{28277}Co to dìláš?
{28278}{28368}Co? Ale nic.
{28414}{28461}Zíráš na Yoona?|Øíkala jsem ti, aby ses nepoutala.
{28462}{28535}Jakmile nám skonèí |vıuka, tak odjídí.
{28537}{28576}Já se nepoutám.
{28578}{28637}Neli!
{28659}{28770}Obì jste nenapravitelné.
{28969}{29035}Pìknı zadek.
{29268}{29341}Kam jen jsem je dala?
{29390}{29477}Hledáš tohle?
{29479}{29567}Všimnul jsem si, e jsi je zapomnìla, |tak jsem ti je schoval u sebe.
{29592}{29639}Dìkuji.
{29928}{30017}Ty jsou ruènì pletené, e?
{30117}{30271}Kdykoliv tì vidím procházet stromoøadím |s tvımi èervenımi rukavicemi...
{30273}{30338}moje srdce se tøepotá dìtskou...
{30340}{30417}nadìjí, e tì uvidím.
{30419}{30514}Máš studené ruce?
{30539}{30622}Jak bych ti mìl vyznat svoji lásku?
{30623}{30698}Ani se na mì nepodíváš.
{30700}{30782}Neslyšíš mùj hlas.
{31052}{31161}Poøád ještì netušíš kdo jsem, e?
{32258}{32288}- Opravdu?|- Ano.
{32290}{32407}Pøíští tıden se vrátí na øeditelství. |Tohle je jeho poslední tıden.
{32409}{32472}Chudinko... Neboj.
{32474}{32527}Je to souèást dospívání.
{32529}{32583}Hele, kdy já byla mladší..
{32680}{32739}No ne, ona to asi myslí vánì.
{33380}{33443}Dobrı den! |Zkuste tyhle!
{33445}{33513}Nová znaèka "Dobrı pocit"...
{33514}{33549}je èistì z bavlny a povrch je...
{33550}{33666}na omak lepší ne jiné znaèky.
{33668}{33748}- Hyun-chae!|- Ano, jak vám mùu...
{33750}{33796}Aha, to jste vy, pane Yoon.
{33798}{33870}Máš minutku?
{33872}{33897}Ano.
{33920}{33973}Poèkám u lavièek.
{33974}{34016}Dobøe.
{34018}{34061}A co tyhle, sleèno?
{34063}{34134}Madam, všechny jsou stejné.
{34279}{34338}Prosím...
{34471}{34549}- Tohle je..|- Já nemohu.
{34550}{34625}Nemùu zradit kamarádku...
{34627}{34688}ale pokud na tom trváte, |já to pøijmu.
{34690}{34738}Prosím, dej tenhle dopis...
{34740}{34789}So-hee.
{34876}{34950}{Y:i}Èást 3 [Volání o pomoc]
{34984}{35030}Take tys to opravdu |zkusila na Yoona?
{35032}{35115}Ne, ale myslela jsem si, |e by to mohl bıt on.
{35145}{35258}- Tvùj poznámkovı chlap je divnı problém.|- Taky si to myslíš?
{35260}{35352}Ne, mám na mysli - kdo by |se do tebe zamiloval?
{35354}{35399}Nìco jiného by bylo, |kdyby šlo o mì..
{35454}{35525}Musí to bıt malíø.
{35526}{35565}Moná.
{35617}{35682}Mám to. Vincent!
{35684}{35740}Vincent?
{35742}{35802}Ty neznáš toho slavného malíøe?
{35804}{35909}Vincent. Vincent van Gauguin?!
{36058}{36102}Máš nìjakou pøedstavu, |kdo by to mohl bıt?
{36104}{36156}- Kdo?|- Tenhle Vincent?
{36248}{36292}Nemám tušení.
{36294}{36370}Dobøe. Mohl by to bıt nìkdo, |koho vùbec neznáš.
{36372}{36474}Nìkdo, kdo se do tebe |zamiloval zpovzdálí.
{36766}{36838}Nebo by to mohl bıt nìkdo, |koho znáš dobøe.
{36840}{36877}Jako kdo?
{36878}{36941}Vidìl tì nìkdo s tou knihou?
{36943}{36987}- Ano.|- Kdo?
{36989}{37062}- Mùj táta...|- Vánì... kromì nìho...
{37147}{37184}Dong-ha?
{37526}{37611}Ale ne! |Ten to bıt nemùe.
{37662}{37735}No tak, pøemıšlej. Musel tì...
{37737}{37853}vidìt v knihovnì.
{37854}{37887}V knihovnì?
{38216}{38308}To je pravda.|Proè mì to nenapadlo døív?
{38310}{38358}Kdo?
{38360}{38452}Je tam.. nemùu ti to øíct.
{38454}{38531}To u nepotøebuješ moji radu?
{38533}{38640}Podívejme na tu šastnou tváøièku!
{38911}{38956}Omlouvám se.
{39036}{39097}Aha, umìlkynì.
{39250}{39328}To jsou moje rukavice.
{39374}{39491}Jsou tak hebké.|Zdají se bıt sobolí.
{39633}{39754}Pamatuji si chvíli, |kdy jsme kolem sebe prošli.
{39820}{39880}Je to jen má pøedstavivost?
{39882}{39997}Ve chvíli, kdy se naše oèi setkaly...
{40026}{40204}jsme do sebe narazili a |tiše se na sebe podívali.
{40206}{40332}Kdy jsi se na mì podívala |svım nìmım pohledem...
{40334}{40437}vzalo mi to dech.
{40438}{40474}Hlupáèku...
{40926}{41034}Goya musí bıt ten |nejšastnìjší mu na zemi...
{41036}{41161}e se mùe na tak krásnou |enu dívat tak dlouho.
{41162}{41309}Chci se na tebe dívat |stejnì dlouho, jako Goya.
{41311}{41353}{Y:i}Máte rád medvìdy v "Rozpuku jara"?
{41874}{41904}{Y:i}Jde jen o medvìdy na jaøe?
{41906}{41957}{Y:i}Èást 4 [Medvìdí potøeby]
{42006}{42086}Medvìdi patøí mezi všeravé |savce rodu Ursidae.
{42088}{42182}Mají sklon k osamìlému ivotu.
{42184}{42259}Tohle je manchurianskı èernı medvìd.
{42261}{42365}Medvìdùm se daøí nejlépe na jaøe.
{42366}{42489}Byl jsem tak rád, |kdy jsem se dozvìdìl..
{42491}{42565}e máš ráda medvìdy.
{42602}{42634}Hyun-chae.
{42657}{42794}Podíváme se na pštrosy?
{42855}{42895}Hyun-chae, pospìš si!
{42932}{43012}To je mraveneèník!
{43014}{43060}No tak, honem!
{43062}{43101}Pojï.
{43138}{43201}Zrovna jí mravence! |Pojï se podívat!
{43203}{43289}Dìlej! Rychle! 
{43340}{43370}Támhle!
{43410}{43458}Ten musí mít hlad.
{43460}{43590}Mládì a matka jedí mravence!
{43711}{43765}Zvíøecí øíše je nekoneèná a
{43766}{43861}my jsme její souèástí.
{43862}{43996}Vìtšinu ivota si to |ale neuvìdomujeme.
{44088}{44164}- Ji-seoku.|- Ano?
{44184}{44247}Proè jsi mi psal ty vzkazy?
{44249}{44291}Vzkazy?
{44316}{44424}Poznámky v knihách.|To jsi nebyl ty?
{44426}{44489}Nìkdo psal do knih?
{44490}{44599}Kdo by to dìlal?|Jakı bezostyšnı grázl!
{44601}{44720}Kdo by takhle nièil veøejnı majetek?
{44742}{44820}To je neotesané!|Jak by mohl nìkdo jen pomyslet...
{44822}{44911}Vyprávìl bys mi ještì o medvìdech?
{44913}{44988}Ehm, dobøe.
{44990}{45079}Lidé øíkají, e medvìdi |jsou nemotorní, ale...
{45081}{45151}oni jsou neohrabaní... ale...
{45250}{45330}Jsou ty poznámky opravdu pro tebe?
{45332}{45378}Jak to myslíš?
{45380}{45414}Mohly by bıt pro nìkoho jiného.
{45416}{45481}Nejsi jediná, kdo chodí |do knihovny, ne?
{45483}{45556}Ne, jsem si jistá, e jsou pro mì.
{45558}{45597}Jak si tím mùeš bıt tak jistá?
{45598}{45673}Nedokáu to popsat.
{45675}{45743}Je to pocit, cit lásky.
{45745}{45803}Lásky?
{45805}{45873}Hele holka, vzpamatuj se.
{46018}{46064}Co tady dìláš?
{46066}{46097}Jak se máš?
{46099}{46143}Právì mi skonèila noèní, |tak jsem vyrazil nakupovat.
{46145}{46237}To nemáte supermarket |nìkde poblí?
{46238}{46298}Pøišel jsem za tebou.
{46346}{46412}No tak.|Jsme pro sebe stvoøení!
{46414}{46541}Ale! Slyšela jsem, e tì sem poslali, |aby mìli záskok v pøípadì stávky.
{46543}{46650}Pro sebe stvoøení, |takovı nesmysl!
{47265}{47366}Jsi moc línej, abys loupal ovoce?
{47368}{47460}Tyhle ti budou staèit.|Vezmi si pomeranèe.
{47462}{47489}Coe?
{47505}{47579}Nevypadáme jako novomanelé?
{47581}{47632}Tobì pøeskoèilo!
{47634}{47685}Hyun-chae!
{47686}{47746}- Ahoj.|- Ahoj!
{47833}{47869}- Kdo je to?|- Kamarád.
{47871}{47952}Ty lháøko!|Znám všechny tvoje kamarády!
{47974}{48016}Hele, je pìknej.
{48018}{48093}Nìkteøí lidi nemají nikdy dost.
{48094}{48185}Èím víc, tím líp.
{48308}{48433}Tohle je tvá pøedstava velké hostiny?
{48463}{48536}Já myslel, e máš ramen ráda.
{48538}{48610}To u je dávno.
{48612}{48680}Vıvar je tak dobrı. Zkus.
{48682}{48730}Tohle místo je známé díky polévce.
{48732}{48771}Slavné, to urèitì!
{48773}{48947}Kdyby tohle bylo opravdovı rande, |u bys tady sedìl sám.
{48979}{49054}Promiò, je tak ubohej.
{49056}{49110}Já zboòuju ramen.
{49163}{49239}Díky, Dong-ho.|Má moc dobrou chu.
{49314}{49368}Zdá se mi, e vy dva |jste si dost blízcí.
{49370}{49397}- Jo.|- Ani ne.
{49497}{49604}Tak jak pokraèují vìci s Vincentem?
{49619}{49661}Docela dobøe.
{49662}{49701}Kdo je Vincent?
{49703}{49750}Do toho ti nic není.
{50072}{50150}Tady máš. Napij se.
{50242}{50308}Ty to ještì poøád |nedokáeš otevøít?
{50310}{50385}Tvoje prsty jsou k nièemu.
{50408}{50493}Jediná èást tvého tìla, |která je k nìèemu, jsou prsty.
{50605}{50656}Dobrı den! Vítejte!
{50658}{50728}Dobrı den! Vítejte!
{50730}{50825}Èím vám mohu poslouit?
{50827}{50915}- Dìkuji vám.|- Dìkuji vám.
{50938}{50962}- Dobrı den.|- Pøíštì pøijïte zas.
{50964}{50993}- To jsem já, Dong-ha.|- Pøíštì pøijïte zas.
{50995}{51075}Víš kolik je hodin?|Øíkala jsem ti, abys mi nevolal do práce.
{51077}{51157}Konèíš ve tøi, e?|Pøijï a jeï mım vlakem.
{51158}{51221}To není tvùj vlak.
{51223}{51289}Pùjdu jedinì pokud |pojedu v kabince øidièe.
{51290}{51361}Víš pøece, e tì tam nemùu vzít. |Chceš, aby mì zavøeli?
{51362}{51416}Ty jsi ale srab.
{51418}{51457}Chcete se zabít?
{51458}{51514}Chcete se zabít?
{51516}{51584}- Dìkuji vám.|- Dìkuji vám.
{51647}{51763}Doktor øíkal "ádnı alkohol".
{51765}{51837}Mìl jsem jen trochu.
{51839}{52013}Pøísahám, e mùj nakladatel |na tom trval.
{52041}{52154}Kolikrát ti to ještì mám opakovat?
{52156}{52226}ádné kouøení, ádnı alkohol!
{52228}{52312}Nebo zase onemocníš.
{52314}{52373}Kdyby tady mohla bıt tvoje máma...
{52407}{52499}Rozhodnul jsem se.
{52501}{52542}O èem?
{52544}{52624}e ti seenu novou mámu.
{52626}{52717}- Hloupá vımluva..|- Sakra, ty máš sílu.
{52719}{52828}Proto jsem pøece tvùj medvídek.
{52830}{52965}Jasnì. Víš, jak ji mám rád?|ádnou instantní kávu!
{53077}{53189}Pamatuješ na tu enu v nemocnici?
{53191}{53231}Co si o ní myslíš?
{53268}{53334}Copak, tobì se nelíbila?
{53374}{53456}Nemùe slyšet ani mluvit.
{53458}{53521}Na tom pøece nezáleí.
{53522}{53626}Láska není o mluvení.
{53628}{53725}Láska proudí kadièkım...
{53750}{53879}pórem tvého tìla...
{54006}{54048}Co se dìje?
{54050}{54185}Hyun-chae... |Tady je krysa.
{54303}{54376}{Y:i}Èást 5 [Poctivá vımìna]
{54378}{54437}Chytni pro mì krysu.
{54438}{54530}A neubli jí.
{54532}{54614}- Pokus se ji vyhnat ven.|- Coe?
{54616}{54728}Proto mi voláš?|Abych vyhnal krysu?
{54740}{54816}Celou noc jsem nespal a |zrovna mi skonèila smìna.
{54836}{54914}No tak, ty malá mrško.|Hodná myšièka.
{55045}{55110}Jo, jsem venku.|Chytil jsi ji?
{55112}{55190}Samozøejmì, e jo.
{55213}{55375}Klíèe?|Jsou pod rohokou.
{55381}{55533}Musím bìet. |Jsem v práci.
{55601}{55633}Tak zaèneme.
{55658}{55701}Sbohem!
{55735}{55804}- Nìco se dìje?|- Coe? Nic.
{56119}{56218}Celı den na nohou a teï |ještì vıstup na takovı kopec!
{56220}{56281}Nedivím se, e máš tak silná lıtka.
{56380}{56425}Vezmi si tyhle.
{56656}{56740}- Máme dohodu, jasné?|- Coe?
{56742}{56782}Poctivá vımìna.
{56819}{56868}Dong-ha není vìc.
{56870}{56945}- Neøíkej to tak.|- Je to jenom fráze.
{56946}{57033}Take tì mám pøedstavit?
{57035}{57103}Jo a zbytek nech na mnì.
{57105}{57223}Neøíkej mi, e mezi |vámi dvìma nìco je?
{57243}{57381}Nic mezi náma není.|On ve mnì nevidí enu.
{57382}{57472}No, kdo by mohl?
{57474}{57513}Coe?
{57548}{57583}Dìlám si legraci!
{57630}{57657}- Nech toho!|- Tahle moje ponoka...
{57658}{57707}mìla jsem ji na sobì celı den.
{57709}{57755}Zkus, je dobrá.
{57757}{57811}To smrdí!
{57903}{57994}Hej, nezpívej tu písnièku!
{57996}{58085}Nesnáším ji!
{58087}{58210}Tak jak plánuješ najít Vincenta?
{58212}{58282}Vdycky se najde zpùsob.|Napsal, e...
{58284}{58416}pøíští kniha bude Michel Roy.|- Jo, ale ta u je zamluvená.
{58418}{58496}Opravdu? |Vsadím se, e to je Vincent.
{58498}{58520}Coe?
{58522}{58664}Pøemıšlej trochu. Musí si tu |knihu pùjèit, aby do ní mohl psát.
{58666}{58698}To dává smysl.
{58721}{58773}Dobøe. |To je teprve zaèátek.
{58775}{58882}Zaøídím, abyste se potkali,|ty a tvùj Vincent.
{58898}{58953}- Zatím!|- Uvidíme se zítra v knihovnì.
{58955}{59005}Ahoj!
{62245}{62390}Hele, co tady dìláš?
{62462}{62534}Vypadni! Vypadni!
{62624}{62663}Uklidni se. |Nic se nestalo.
{62665}{62732}Byl jsem tam schovanı, |abych tì vystrašil, ale usnul jsem.
{62734}{62792}Jak tam mùeš spát |celı den, ty blázne?
{62794}{62883}A kde ses vzal v mé posteli, |kdy jsi spal ve skøíni?
{62885}{62924}Nevím, jak se to stalo.
{62926}{63003}Mohla bych tì zaalovat |za vloupání a sexuální harašení!
{63005}{63066}Au! Ty bys to udìlala?|Chytil jsem ti tu krysu!
{63422}{63471}Sejdeme se v sobotu.
{63473}{63507}Proè?
{63509}{63591}- Chtìl bych ti nìco øíct.|- Øekni mi to teï.
{63635}{63689}Nemùu to øíct teï, jasné?
{63690}{63777}Dávej si pozor, jak se mnou mluvíš.
{63779}{63830}Ty si dávej pozor, jinak...
{63832}{63886}Jinak co?
{63926}{63989}Øeknu lidem, e jsme spolu spali.
{64089}{64150}Já tì zabiju!
{64187}{64227}Jsi mrtvej!
{64253}{64388}{Y:i}Èást 6 [Pravidla hry]
{65062}{65152}- Promiòte, ale já jsem enatı.|- Coe?
{65215}{65273}Ale to pøece nevadí.
{65275}{65303}{Y:i}Michel Roy
{65326}{65384}Mohla bych tohle vrátit?
{65386}{65461}Teï není èas se vracet.
{65462}{65521}Lidé èekají.
{65522}{65571}Nezáleí na tom, e jsi enatı...
{65573}{65650}nebo e lidé èekají.
{65652}{65736}Mimochodem, odkud mì vlastnì znáte?
{65738}{65849}Sleduji tì u dlouhou dobu...
{65851}{65979}a nemohu si pomoct.
{66004}{66057}Je mi líto, ale musím u jít.
{66059}{66164}Poèkej! |Máš rád medvìdy?
{66776}{66852}Já jsem Kim Jin-seob.
{66997}{67029}Aha! Omlouvám se.
{67030}{67109}To je v poøádku.|To se stává.
{67126}{67247}- Je to ta kniha?|- Ano.
{67249}{67357}Nejdøív jsem si také myslela, |e ty zamilované vzkazy jsou pro mì.
{67359}{67490}Ta ena na obraze vypadala jako já...
{67560}{67671}- Byla jste to vy, sleèno?|- Ano, ještì nejsem vdaná.