{1}{1}29.970
{94}{216}Amazonské Trio si uvìdomilo,|e nejsou lidé.
{217}{339}Pokud nenajdou Pegasùv|roh, kouzlo pomine...
{353}{487}A v takové kritické dobì Rybí Oko|pocítí lásku k Mamorovi. Ale já se nevzdám!
{487}{586}Ze všech muù na svìtì, Mamo-chan...
{586}{627}...je ten nejlepší!
{3637}{3686}Vstanete?
{3759}{3882}Pro mì nejste soupeø, má rivalko.
{4234}{4376}Epizoda #149|"Zrcadlo snù!|Poslední vıstup Amazonského tria"
{4709}{4766}Nechcete se pøevléci?
{5000}{5123}Tady! Vysušte si vlasy.
{5229}{5319}Jak jste stará?
{5370}{5434}Do které školy chodíte?
{5434}{5589}Slyšela jsem, e máte spousty snù...
{5603}{5673}Øekl mi to Mamo-chan.
{5717}{5829}Zase jste ho vidìla? Kdy? Kde?
{5885}{6035}Sedìla jste zmáèená v dešti, protoe vám|váš pokus u Mamo-chan nevyšel?
{6073}{6183}No tak, no tak! Co má|znamenat to podezøelé ticho?
{6205}{6297}Vám jde všechno tak snadno, e?
{6356}{6486}Skuteènì vám závidím,|protoe máte spousty snù!
{6486}{6729}{Y:i}Vidíte? Nejste lidé. Kouzlo vás|zmìnilo, take jen jako lidé vypadáte.
{6748}{6872}{Y:i}To je ten dùvod proè|nemáme pøekrásné sny?
{6912}{7034}Proè si nevezmete šálek èaje?|Ten vás trochu zahøeje!
{7100}{7222}Prosím, povìzte mi...|Jakı je váš nejlepší sen?
{7222}{7409}No... to neumíte uhodnout ani|takovou jednoduchou vìc, mùj rivale?
{7603}{7803}Ach, ano... To je pravda.|Tak to je váš pøekrásnı sen...
{8011}{8167}Mamo-chan se tak usmívá,|kdy vy dva jste spolu.
{8180}{8321}Hele! Takhle mu neøíkejte,|kdy nejste jeho blízká pøítelkynì!
{8321}{8450}Vzdejte to èistì a u|se k nìmu nepøibliujte!
{8450}{8542}Neøíkám e váš vıbìr není dobrı...
{8542}{8613}...protoe ze všech muù|na svìtì je on ten nejlepší!
{8613}{8847}{Y:i}...Mùj Boe, zaútoèili jste ze všech muù svìta|na toho nejlepšího! Dokáete si vybrat!
{8847}{8970}{Y:i}Tahle dívka je Sailor Moon...
{9039}{9126}Usagi! Mùeš mi pro nìco skoèit?
{9126}{9156}Sakra! Ano!
{9229}{9424}Prosím, poèkejte tu! Chtìla bych|si vyjasnit vìci kolem Mamo-chan!
{9840}{9901}Sailor Moon!
{9901}{10015}{Y:i}Co je tak atraktivní na té dívce, Usagi?
{10061}{10149}{Y:i}Ona má spousty snù...
{10252}{10329}{Y:i}Tak proto je tolik silná?
{10659}{10747}Prosím, pøijï Pegasi!
{10771}{10812}{Y:i}Volala jsi mì?
{11073}{11149}Je nìco pro co se musím rozhodnout...
{11149}{11185}{Y:i}Co je to?
{11185}{11280}{Y:i}Pegas! Tohle dìvèe je hostitelem?
{11280}{11427}{Y:i}Chytit Pegase mùete tak,|e se zmocníte jeho hostitele...
{11512}{11656}{Y:i}To je jedinı zpùsob, jak si|mùete podret lidské tvary...
{11672}{11955}{Y:i}Pegas! Dokáete to pokud pouijete|sílu z jeho rohu, Zlatého Krystalu!
{11986}{12054}Je to pravda?
{12123}{12162}Jsem doma!
{12162}{12270}Ach? Nevíš kam šla Chibi Usa?
{12315}{12413}U jsem ji nìjakı èas|nevidìla. Kde jen mùe bıt?
{12414}{12512}Myslím ona odešla nìkam|za zábavou jako obvykle.
{12669}{12825}Coe? Našli jste Pegasova hosta?|Kdo to je?
{12895}{12984}Co se dìje? Proè neodpovídáte?
{13046}{13170}Pøed tím, ne odpovím, prosím, øeknìte|mi jednu vìc, Zirkonia-sama!
{13226}{13359}Mùeme se skuteènì stát lidmi?
{13376}{13433}Co tím myslíte?
{13433}{13537}I kdy máme lidskı vzhled...
{13537}{13785}...je moné bıt èlovìkem|bez pøekrásného snu?
{13882}{13974}Prosím, odpovìzte, Zirkonia-sama!
{14444}{14525}Prosím, nechte toho, Zirkonia-sama!
{14648}{14749}Nejste nenahraditelní!|Nedovolujte si takové drzosti!
{14793}{14908}Jste jen zvìø!|Neotevírejte si své velké huby!
{15061}{15213}Nemáte co se ptát!|Pravda, Zirkone?
{15518}{15633}Vím e tahle dívka je hostitelem...
{15633}{15749}Ne! Mılíte se! Nechte ji bıt!
{15781}{15836}Jestøábí Oko! Jdìte!
{15836}{15876}Ano!
{15944}{16072}Tato koule je èást kouzla,|které drí vaše lidské postavy.
{16072}{16200}Mùe vám pomoci,|ale jen jednou.
{16200}{16328}Ale kdy pøidáte sílu z Pegasova rohu...
{16328}{16471}...Zlatého krystalu, do téhle koule,|udríte si svùj vzhled navdy!
{16524}{16570}Ano!
{16570}{16630}Jestøábí Oko!
{16737}{16839}Tygøí Oko! Hlídej Rybí Oko!
{16839}{16908}A... ano...
{16908}{16938}Jsem v poøádku. Mohu se postavit sám...
{17104}{17181}Jdeme. Dr se!
{17181}{17231}Rybí Oko!
{17294}{17355}Poèkej, Rybí Oko!
{17420}{17527}Tohle je konec Amazonského Tria.
{17660}{17774}Já vím. Jdìte a udìlejte|si s nimi co chcete!
{18489}{18580}http://umino.gurio.sweb.cz
{19146}{19274}A u se nevrátila...
{19639}{19697}{Y:i}Kdo to byl?
{19697}{19807}A Chibi Usa odešla s ní?
{19830}{19938}A... Ach... nemyslím si to...
{19938}{20097}Tak? Nemyslíš si to tak? Tak proè|ji s tebou máme hledat?
{20149}{20198}Prosím...
{20199}{20248}Ach klid!
{20248}{20347}No, rozdìlíme se!
{20629}{20685}Promiòte!
{20717}{20786}Ach ano, vím!
{20786}{20808}Coe?
{20808}{20896}Nejste jako nìkdo koho bych si vybral!
{20896}{20926}{Y:i}Boe co to øíká?
{21117}{21159}Jedna!
{21187}{21223}Dva!
{21269}{21310}Tøi!
{21532}{21606}Stùj! To je omyl!
{21795}{21851}Co chceš dìlat, Rybí Oko?
{21851}{21966}Nech toho Jestøábí Oko! Pus, Sailor Moon!
{21966}{22009}Sailor...
{22009}{22052}Moon...
{22052}{22282}Takové pøekvapení! Tohle je Sailor Moon?|Tak to se musím podívat poøádnì!
{22657}{22800}Rád vás poznávám! Jsem Mister-Magic-Pierot!
{22800}{22879}Mister-Magic-Pierot?
{23230}{23374}Ach to je velkolepé! Ale Pegas tam není!
{23374}{23447}Co to øíkáte?
{23447}{23619}Pøišel jsem zlikvidovat neuiteèné|vìci na pøíkaz Zirkonie-sama!
{23635}{23675}Neuiteèné vìci?
{23675}{23756}Správnì! Neuiteèné vìci!
{23756}{23923}Prosím pozor! Vyletí ptáèek! Ptáèek!
{23976}{24012}Tady!
{24125}{24165}Co to dìláš?
{24165}{24291}To je jasné. Zbavuji se|neuiteènıch vìcí! Tady!
{24741}{24854}Boe! Ne... její sny...
{24854}{25039}{Y:i}No... to neuhodnete ani tak|jednoduchou vìc, mùj rivale?
{25473}{25525}Tady!
{25911}{25991}Hurá! Jednu vìc mám!
{26297}{26344}To staèí.
{26444}{26481}Jestøábí Oko!
{26482}{26519}Jestøábí Oko!
{26519}{26562}Proè?
{26591}{26862}Nakonec se zase vracíme... chtìl bych|dostat Pegase... bıt èlovìkem...
{26899}{27014}Je to smutné, kdy teï|zùstanu takhle..
{27057}{27097}Jestøábí Oko!
{27097}{27137}Nevzdávej to!
{27233}{27293}Tady...
{27489}{27573}Jestøábí Oko!
{27691}{27735}K èertu!
{27948}{27985}Tak!
{28123}{28162}Coe?
{28362}{28541}Ach drazí... to je všechno co Amazonské Trio,|špièkové hvìzdy Mrtvého Mìsíce, dokáí udìlat?
{28610}{28703}Je silnı, nemyslíš?|Co teï udìláme?
{28836}{29023}Tygøí Oko! Opravdu jsem našel Pegasova Hosta...
{29084}{29216}Pokud pouiji tuhle kouli, staneme se lidmi...
{29231}{29415}Ale za tìhle okolností zemøeme|a nedokáeme pomstít Jestøábí Oko.
{29431}{29544}Prosím! Nech mì|pouít sílu téhle koule!
{29720}{29822}Myslíš, e ho Sailor|Moon porazí?
{29822}{29887}Vìøím tomu.
{29949}{30146}Dobøe. Dáme se do posledního|pøedstavení Amazonského Tria!
{30194}{30240}Tygøí Oko!
{30267}{30404}Pokud se znovu narodíme, pøáli|bychom si pro zaèátek lidské tìlo, viï?
{30404}{30488}Je to vaše poslední sbohem?
{30488}{30538}Ne ještì ne!
{30772}{30813}Co chcete dìlat?
{30844}{30916}Prosím, naše pøání staò se skutkem!
{31435}{31471}Usagi!
{31472}{31508}Chibi Uso!
{31552}{31633}Rychle! Transformujte se, Sailor Moon!
{31797}{31943}Proè neuiteèné vìci|pomáhají nepøíteli...
{31959}{32010}Chibi Usa! Transformujem se!
{32010}{32043}Ano!
{32043}{32162}Moon Crisis...
{32162}{32281}...Make Up!
{33209}{33316}Zlikviduji všechno,|co je neuiteèné!
{33352}{33430}Fire Soul!
{33522}{33570}Ani hnout!
{33570}{33738}Pegasi, prosím!|Ochraò sny všech!
{33840}{33936}Twinkle Yell!
{34541}{34633}Moon Gorgeous...
{34633}{34725}...Meditation!
{35145}{35218}Stage Out!
{35751}{35883}Pomohl jste nám. Proè?
{35942}{36094}Skuteènì vám závidím,|protoe máte tolik snù...
{36145}{36229}Vy jste... to dìvèe?
{36685}{36733}Pegasi...
{37152}{37217}Zrcadla snù!
{37255}{37402}Nakonec jsme lidé!
{37737}{37874}Duše která sní bude|najisto zachránìna.
{37874}{38011}Tyhle tøi zvíøata...|lépe lidé... taky.
{38592}{38678}Teï to zmìníte!
{38939}{39208}Zùstaòte v tomhle lese! Protoe tento|temnı les se znovu jednou rozzáøí.
