{1}{1}15.000000
{76}{124}Slyšel jsem, že Tygří Oko selhalo!
{125}{176}A já slyšela, že Pegas opět uletěl!
{176}{249}A já slyšel, že nedokázal|zabít překrásného snílka!
{250}{307}Doufám, že se Zirkonie-san nerozzuří!
{461}{518}Zmlkněte! Všichni, koukejte zmlknout!
{569}{604}Kde jste, Amazonské Trio?
{622}{689}Nesmíme promeškat šanci, která|se objeví jednou za stovky let!
{689}{767}Polapení Pegase je náš první krok, před|získáním kontroly nad světem!
{771}{887}Musíte najít toho snílka s překrásným snem|ve kterém se ON skrývá a polapit HO!
{959}{1043}Epizoda #129|"Supertransformace!|Druhé uvolnění Pegasovy síly."
{1067}{1133}Ach, k čertu! Jsem tak vzteklý! Všechna|ta blamáž kvůli mému selhání!
{1133}{1193}A šlo to tak pěkně, zachytil|jsem dívčinu mysl.
{1223}{1279}Dokud se ta verbež, Sailor Senshi,|neobjevila a nevyrušila mě!
{1279}{1338}Nemohlo být příčinou toho selhání to, že jsi|do své práce přimíchal i osobní zájem?
{1339}{1358}Cože?
{1358}{1385}Pravda, pravda!
{1385}{1428}Hele, Rybí Oko, co to máš?
{1428}{1503}Ach tohle? Našel jsem to někde|v koutě stanu. Nemyslíš, že je nádherné?
{1503}{1563}Až chytíme Pegasa, osedlám ho a projedu se.
{1564}{1624}To je nádherný nápad! Mohlo by to být pěkné!
{1646}{1685}Ach podívejte! Tohle je velmi pěkné děvče!
{1686}{1750}Cože? Tahle se ti líbí?|Mohla by to být perfektní volba.
{1763}{1782}Tak do toho!
{1782}{1835}No, to tedy máš odvahu po té blamáži.
{1845}{1903}Neurazil jsem tě?|Chováš se tak divně!
{1903}{1975}Teď už máš určený další cíl, že?
{2047}{2073}Myslím, že se to stalo někde tady.
{2073}{2109}No nezůstala tu ani stopa.
{2119}{2165}Ti noví nepřátelé a tajemný Pegas...
{2172}{2232}Chibi Uso, určitě nic nevíš?
{2336}{2396}Prosím, nikomu neříkej o tomhle setkání.
{2435}{2472}Ne o tom nic nevím.
{2510}{2546}No, snad ho zas uvidím...
{2590}{2616}Chibi Uso, kam letíš?
{3094}{3111}Reika-san?
{3111}{3151}Tak to už je z Afriky zpátky?
{3152}{3172}Vy ji znáte?
{3173}{3223}Jo, je to Motokiho milá.
{3230}{3275}Nemůžeme ztrácet čas čekáním!|Pojďte za ní!
{3309}{3362}Reiko-san, nevyrušujeme vás?
{3362}{3450}Ale ne, nevyrušujete. Stejně se|nemůžu na trénink soustředit.
{3450}{3516}Nebo možná ten kůň dnes nechce trénovat.
{3517}{3597}No, teď mám s něčím starosti.|Snadno podlehnu depresi.
{3614}{3658}Můžu se zeptat co vás trápí?
{3658}{3690}No, řeknu vám pravdu...
{3690}{3738}...moje studie na fakultě přijali|dobře. A doporučili mi...
{3738}{3786}...pokračovat ve studiích na|některé evropské univerzitě.
{3786}{3866}Ale tohle by mělo trvat přes deset let.
{3875}{3920}Co na to říkal Motoki?
{3926}{4026}No, opravdu se jen usmál|a řekl, 'To je velkolepé!'...
{4055}{4134}...ale nedívá se na mě,|když ho navštívím.
{4182}{4266}Možná už mě nemiluje...
{4331}{4426}Hele, Reiko-san! Pomůžeme vám, aby jste|se ho mohla zeptat co si skutečně myslí.
{4427}{4445}Ale...
{4445}{4524}Ach, já naprosto chápu jak se cítíte,|když jste tak dlouho od sebe.
{4524}{4569}Nemusíte se bát, o vaši lásku|protože mi sami si to...
{4570}{4609}...vezmeme na starost!
{4622}{4645}Děkuji.
{4677}{4704}Poslouchej, Motoki-onisan!
{4704}{4737}Reika se teď rozhoduje, kterou cestou se dá!
{4738}{4767}No ten váš návrh je milý...
{4768}{4870}...ale já ji teď nechci vidět. Je to její|volba, zda odjede do Evropy nebo ne.
{4871}{4933}Omlouvám se děvčata, musím|jít zpátky do práce. Uvidíme se.
{4947}{4970}Co to bylo?
{4970}{5020}Nikdo by takhle nemluvil.
{5021}{5053}Vy dvě strkáte své nosy do|něčích osobních záležitostí...
{5053}{5070}Cože?
{5070}{5120}Tak ty říkáš, že nemůžeme být Kupidy i když|pracujeme pro lásku a spravedlnost?
{5120}{5148}To teda ne!
{5184}{5256}Usagi, měla bys raději myslet|na naše nové nepřátele.
{5256}{5323}Ami-chan! Tobě Reika a Motoki|nedělají starosti?
{5323}{5354}No, no!
{5354}{5390}Ale samozřejmě, že ano.
{5390}{5470}Doufám, že nikdy nebudeme jako ona.
{5501}{5528}Hej vy dvě.
{5528}{5621}Můj bratr je trochu paličatý.|Myslím, že teď má těžké časy.
{5630}{5723}No to má! Pro žádnou dvojici to není snadné,|když jsou od sebe odděleni.
{5723}{5783}Usagi, snad se něco nestalo|mezi tebou a Mamorem?
{5784}{5842}Ach, ještě tak! Když nezáleží na faktech...
{5843}{5865}Neboj se!
{5866}{5938}Jen říká že neví, kde Mamoru byl včera.
{5939}{5974}Rei! Jak to můžeš vědět?
{5975}{6022}No, včera mi volala a ptala se,|jestli nevím, kde je.
{6023}{6049}Ach, mě taky volala!
{6050}{6063}A mě taky.
{6063}{6128}Mě taky! Nakonec nás obvolala všechny!
{6128}{6175}Hele, Usagi, jak můžeš|chápat, jak se Motoki cítí...
{6175}{6271}...když začneš fňukat, pokud|svého milého nevidíš jen jeden den?
{6271}{6336}No... To protože...|Cítím se tak opuštěná!
{6393}{6424}Tady máš!
{6425}{6460}Chibi Uso, tobě se líbí koně, že?
{6461}{6588}Ano! Óch, taková dlouhá tvář!|A má velmi krásné oči.
{6589}{6710}Jo to má. Ty oči jsou božsky čisté. Nikdo|by takovému zvířeti nemohl lhát.
{6710}{6758}Snadno vycítí tvé problémy.
{6827}{6926}Reiko, když se tak dobře z koňmi znáš, není|nějaký, který má na čele roh? Jako... takhle!
{6926}{6990}To musí být stvoření,|které žije v našich snech.
{6990}{7024}V našich snech?
{7032}{7115}Tvor který vytváří|naše překrásné sny.
{7115}{7235}Můžeš uvidět tak nádherné stvoření jen pokud|jsi naplněna překrásným snem.
{7235}{7356}Ach ne. Nejsem si jistá, zda mám krásný sen.|Ale myslím, že vy takových snů máte mnoho.
{7369}{7511}Mé sny? Nevím, zda jim mohu říkat překrásné, když|jsou naplněné takovou úzkostnou láskou.
{7588}{7675}Poslouchej, Minako-chan, půjdeme zítra|do Koruny a zjistíme jak se Motoki cítí.
{7675}{7729}Ty, Luno, co se to stalo|mezi Reikou a Motokim?
{7730}{7813}No, deset let je trochu moc.|Motoki nemusí celou tu dobu vydržet.
{7813}{7884}...a Mamoru? Mamoru mi ještě nezavolal...
{7884}{7955}Nakonec, se všechny páry roztrhnou, když|jsou od sebe příliš dlouho, nemyslíš?
{7955}{8044}Když jsou na vzdálených místech, jsou|oddělené i jejich myšlenky. Nevím...
{8045}{8068}Chibi Uso-chan...
{8082}{8111}Uvidíme se zítra. Čau.
{8128}{8251}Haló... Mamoru! Kde jsi teď|poletoval? Proč jsi mi nezavolal?
{8259}{8291}Volal jsem ti tolikrát!
{8292}{8337}Chtěl jsem říct, že mám nějakou práci ve|své pracovní skupině na univerzitě!
{8337}{8406}Ale ty jsi měla vždycky obsazeno, kdykoli jsem to zkoušel.|Příště do telefonu nemluv tak dlouho.
{8423}{8469}Tak a co mi teď povíš?
{8491}{8529}Kolem nových nepřátel!
{8530}{8568}Ach, ano! Ta věc...
{8569}{8622}...teď se s tím zkoušíme vypořádat...
{8622}{8667}Ach, ano... jsem si jistá že to zakončíme zítra...
{8667}{8730}...pak se uvidíme. Ahoj.
{8800}{8818}Mamo-chan!
{8865}{8970}Luno, pořád mám ráda svou maminku i tátu,|i když jsem tak daleko od domova.
{8971}{9066}A vím, že protože mě tolik milují,|tak mne poslali sem do učení.
{9066}{9113}To je pravda! Můžete mít tolik snů...
{9113}{9167}...kolik si vymyslíte, i když|jste tak daleko od sebe!
{9218}{9257}http://umino.gurio.sweb.cz
{9595}{9652}No tak, hodná holka!|Tohle není tvá chyba.
{9755}{9842}Ach, můj Bože. Myslel jsem, že to Venuše|přijela na koni zpět mezi nás!
{9907}{9952}Co asi teď Reika dělá?
{10076}{10144}Snad pokud  se dostanu|blíž budu mít lepší šanci.
{10165}{10201}Trénujete tak tvrdě, že?
{10201}{10243}Ano. Myslím, že ji zneklidňují mé problémy.
{10244}{10308}Je těžké trénovat, když se|sám nemůžete soustředit.
{10309}{10351}Nemohu vám s něčím pomoci?
{10364}{10458}Vidím, že ty velké problémy|se zrcadlí ve vašich překrásných očích.
{10538}{10618}Dívky jsou velmi šťastné, když si uvědomíte|jejich problémy a nabízíte jim pomoc.
{10618}{10654}Teď, tahle dívka bude MÁ!
{10685}{10736}Nemůžu slyšet, o čem si povídají.
{10745}{10804}Prosím, nech toho špehování, Chibi Uso.
{10804}{10855}Jsem tolik zvědavá.
{10855}{10915}No, musela jsi se od Usagi|naučit nějaké její špatné zvyky.
{10916}{10953}Tak vy odjíždíte do zámoří...
{10963}{10990}Ale ještě jsem se nerozhodla...
{10990}{11069}...protože když půjdu za svým snem, budu|muset nechat svou lásku tady.
{11069}{11101}Jsem tak zvědavý...
{11147}{11227}...na ten váš sen. Je nádherný?
{11249}{11299}Ano, povězte mi o tom!
{11417}{11487}Pozor! Nechtěl bych vás|zranit, překrásná dívko.
{11503}{11532}Co jste zač?
{11618}{11638}Jedna!
{11638}{11660}Dva!
{11661}{11682}Tři!
{11812}{11843}Transformuj se Chibi Uso!
{11872}{11944}Moon Prism Power... Make Up!
{12238}{12263}Stůj!
{12276}{12346}To není fér! Takhle zneužít dívčí sen, zloduchu!
{12346}{12422}Za lásku a spravedlnost, začínající|půvabná bojovnice v námořnickém...
{12423}{12458}Sailor Chibi Moon!
{12466}{12526}Ve jménu budoucího Měsíce,|ztrestám vás!
{12532}{12616}Ach ne. Zas ta vydlabaná hlava!|Ke mě, má Lemure, překrásná...
{12744}{12795}...krotitelko divoké zvěře, Kjokubo Danko-chan!|Prosím, vezmi si ji na starost.
{13000}{13055}Tak teď mi ukážete svůj překrásný sen.
{13090}{13193}Ach ne! Ne! Ne! Zastavte! Prosím ne!
{13231}{13311}Ach to je smůla. Nenašel|jsem HO v jejím snu.
{13311}{13347}Hej, Kyokubo Danko-chan!
{13368}{13431}Nemohu ji nechat naživu, protože ON by se|mohl později v jejím překrásném snu skrýt.
{13432}{13466}Zab je obě!
{13466}{13493}Tohle nesmíte!
{13493}{13520}Sailor Moon!
{13520}{13608}Ahoj! Dokud se na tomhle světě objevují zločinci,|tak já si to beru na starost, jako dovážku pizzy.
{13608}{13669}Za lásku a spravedlnost, půvabná|bojovnice v námořnickém...
{13670}{13691}Sailor Moon!
{13713}{13770}Ve jménu Měsíce,|ztrestám vás!
{13778}{13833}Ale ne, zase! Skupina dutohlavců!
{13843}{13864}Skupina?
{13875}{13900}Ach, všechny, ahoj.
{13900}{13959}Hele, proč jsi se neukázala v Koruně?|Čekali jsme na tebe.
{13959}{13997}A nakonec nás napadlo,|že musíš být tady!
{13997}{14050}Také máme starost o Reiku-san.
{14051}{14143}Opravdu nenávidím dívčí klábosení, obzvlášť,|když si mě nevšímají. Hej, Danko-chan!
{14166}{14216}Nejprve vás naučím, jak pozdravit!
{14245}{14299}Hej, vy! Při příchodu pozdravíme!
{14315}{14331}Tady máš!
{14344}{14391}Burning...
{14411}{14439}...Mandala!
{14467}{14512}Dobře! Tak přeskočíme pozdravy|a přejdeme rovnou k drezůře!
{14645}{14696}Danko-chan, příště mi ukážeš|ještě zábavnější hru!
{14725}{14768}Tak, ty vyskoč a připoj se!
{14798}{14842}Pro začátek, dámská volenka!
{14860}{14887}Tancuj! Tancuj! Tancuj!
{15059}{15121}Pomoc! Pegasi, pomoc!
{15232}{15253}To je...
{15657}{15700}Stage Out!
{15831}{15861}Tak, vy holky jste zase vyhrály!
{15942}{15958}Reiko-san!
{16030}{16057}To musí být...
{16057}{16089}O tomhle nám Usagi říkala...
{16089}{16108}Pegas!
{16293}{16320}Pegasi...
{16335}{16373}Tak vidíš, Motoki-onísan...
{16373}{16429}Musíš si zas promluvit z Reikou!|Nakonec...
{16430}{16464}No...
{16465}{16536}Motoki, vysvětli mi, proč|se s ní nechceš vidět.
{16536}{16580}Vždyť nic nemůže pochopit.
{16580}{16717}No protože... nechci se s ní vidět, dokud|se sama nerozhodne, co chce dělat.
{16718}{16853}Nechci, aby si kvůli ohledům zničila své sny.|Nakonec, já mohu počkat až se vrátí.
{16854}{16899}To se mi ulevilo, když tohle slyším!
{16907}{16934}Tak co s tebou, Reiko?
{16957}{16979}Reiko!
{16985}{17119}No, myslela jsem, že už mě nemiluješ,|protože jsem se dívala jen na sebe...
{17171}{17264}Ne, to není pravda! Jsi má speciální|dáma! Vždycky tě budu milovat!
{17291}{17362}Odjeď do Evropy! Jdi|a studuj. Naplň své sny!
{17387}{17410}Motoki!
{17425}{17457}To jsem čekala, bratříčku!
{17469}{17503}To je muž!
{17520}{17584}Když bude osamělý, můžeme mu pomoct!
{17584}{17635}Ty víš co? Nesmíme do|takových věcí strkat své nosy!
{17636}{17715}Každé jejich rozhodnutí bude v pořádku. Pokud|láska mezi nimi vydrží, bude to v pořádku.
{17727}{17810}Láska není tak slabá, aby ji narušila vzdálenost.
