{1}{1}15.000000
{66}{135}Epizoda #131|"Zajetí Pegase!|Amazonská past."
{600}{654}Ticho! Buďte zticha!
{882}{920}Je tu Amazonské Trio?
{921}{977}Volala jste, Zirkonia-sama?
{993}{1068}Ne jednou, ne dvakrát, ale|třikrát jste stáli před Pegasem...
{1071}{1120}...ale nebyli jste schopní ničeho...
{1171}{1226}Trochu k vám začínám ztrácet důvěru.
{1253}{1299}Nepatří k mým způsobům někomu skočit|do řeči, ale Zirkonia-sama...
{1299}{1331}Co chceš, Jestřábí Oko?
{1331}{1405}Doufám, že naše síly nepodceňujete.
{1412}{1428}Cože?
{1438}{1473}Dosud jsme věci jen zkoumali.
{1474}{1546}Když se teď do toho všichni tři dáme,|jako by už Pegas byl před vámi.
{1557}{1598}A je to skutečně pravda?
{1616}{1632}Ale jistě.
{1731}{1775}Už jsi určil další cíl, Tygří Oko?
{1787}{1837}No, myslím, že tahle dívka...
{1910}{1921}Ach?
{1922}{1974}Vypadá tak čistě, ale|jistě bude normální.
{1975}{2027}Myslíš, že se Pegas skrývá v jejím snu?
{2038}{2067}Ať už vím, nebo ne...
{2067}{2098}...nemůžeme mít ještě|větší problémy, nemyslíš?
{2106}{2128}Ach, to je strašné!
{2129}{2181}Snad nejsi trochu rozzuřený?
{2196}{2260}Jsem tolik rozzuřený!|Málem jsem vybuchl když jsem slyšel ten slib!
{2260}{2305}Pokud brzo nechytíme Pegase...
{2312}{2365}...jsem zvědav jak zmírníš Zirkonin hněv!
{2370}{2431}Skutečně! Málem mi vyskočilo srdce,|když jsem slyšel ten tvůj slib.
{2431}{2454}To je v pořádku...
{2455}{2488}Už mám vítěznou taktiku.
{2489}{2541}Určitě tentokrát dokážeme Pegasa chytit...
{2552}{2581}Vítěznou taktiku?
{2581}{2641}No, jste připraveni mě vyslechnout?
{2652}{2714}Skutečně Zirkonii-sama rozzuříme,|když se budeme v práci flákat.
{2726}{2746}Začíná to pěkně...
{2746}{2778}Co s tím?
{2811}{2839}Tady, čokoládová zmrzlina.
{2873}{2912}Sakra... Umino se určitě opozdil...
{2989}{3007}Perfektní...
{3008}{3090}Jsem vždycky tak úžasný, kdykoli se|sám na sebe podívám. Vždy perfektní.
{3090}{3121}A teď... cíl.
{3167}{3193}Tamhle je...
{3227}{3260}Grr... co může dělat...
{3270}{3296}Hele! Jdeš poz...
{3309}{3328}Omlouvám se...
{3328}{3366}Myslela jsem, že je to někdo jiný...
{3378}{3402}I když jste se zmýlila...
{3402}{3479}...jsem potěšen, že mě někdo|tak překrásný oslovil.
{3556}{3592}Nemůže si pomoci, ale je polapena mou krásou!
{3592}{3645}Takové jednoduché děvče...|No, tohle jsem očekával, ale...
{3660}{3706}Pokud vám to není proti mysli,|co byste řekla na šálek čaje?
{3706}{3733}Ach, Umino!
{3759}{3784}Sakra...
{3792}{3805}Naru-chan!
{3805}{3826}Naru-chan, omlouvám se!
{3826}{3866}Teda! Co je to za nevychovanou a šerednou věc?
{3866}{3895}Jdeš pozdě.
{3932}{3955}Musela jsem chvilku čekat!
{3991}{4015}Omlouvám se, zaspal jsem.
{4015}{4038}Tak to mi koupíš nějakou zmrzlinu!
{4073}{4134}Vybrala si takového šeredu místo mě!
{4134}{4180}Co to znamená?
{4180}{4225}Co tohle... všechno... znamená?
{4295}{4341}Takový krátký flirt, to je skoro jako poprava.
{4342}{4359}Sklapněte!
{4360}{4399}To je strašné...
{4407}{4452}V poslední době se ti nedaří.|Nejsi vyčerpaný?
{4452}{4473}Buď zticha!
{4474}{4515}Pokud ona nepochopila mou krásu...
{4515}{4571}...pak neexistuje možnost, že by|se Pegas skrýval v jejím snu!
{4581}{4611}Tohle není jisté, ne?
{4611}{4640}Vezmeš na sebe odpovědnost,|pokud tam Pegas je?
{4641}{4693}No, pokud se v ní Pegas neskrývá,|můžeme ji využít jiným způsobem...
{4708}{4729}Co plánuješ?
{4729}{4799}Ty myslíš... tu vítěznou taktiku,|kterou jsi tuhle vzpomínal?
{4800}{4829}Jo. Chcete to vidět?
{4838}{4881}No tolik mě to nezajímá, ale...
{4881}{4904}A co ty, Tygří Oko?
{5041}{5076}Tohle je... vítězná taktika?
{5089}{5103}Hoplá!
{5183}{5207}Tohle není obyčejná klec.
{5207}{5226}Skutečně?
{5243}{5273}Určitě víš...
{5273}{5355}že Pegas v hmotném světě nemá skutečné tělo.
{5414}{5443}No a když jsem o tom přemýšlel...
{5443}{5489}...tak mě napadlo nabít materiál|klece negativní energií.
{5490}{5566}Pak, když se objeví něco z jiné dimenze,|musí se to tady zachytit.
{5566}{5585}Chápu.
{5585}{5668}I když nedokážeme najít vlastníka překrásného|snu, přesto dokážeme Pegase chytit.
{5668}{5711}Ale jak ho dostaneme dovnitř?
{5724}{5741}Musíme mu předhodit nějakou návnadu.
{5751}{5766}Návnadu?
{5778}{5837}Když je někdo s překrásným snem v nebezpečí...
{5843}{5887}...objeví se z neznáma Pegas.
{5900}{5950}Tak použijeme překrásný sen jako návnadu.|Nalákáme ho přímo dovnitř.
{5960}{5979}Jasně.
{5993}{6052}Osako Naru, ty budeš naší|návnadou na Pegase.
{6227}{6287}Tebe jsem hledala tak dlouho!|Jsem ráda že jsem tě našla.
{6287}{6348}Chce být ošetřovatelkou...|to jsem mohl tušit.
{6348}{6382}Teď to bude snadné.
{6382}{6471}Dívka, jako tahle, naletí na mladého|muže, kterému nezbývá moc života...
{6654}{6684}Tak se zase potkáváme...
{6696}{6704}Zase?
{6715}{6747}Už jsme se snad někdy setkali?
{6758}{6784}Cože?
{6784}{6832}Říká, že si na mě nevzpomíná?
{6848}{6907}No nevím, ale|vypadá jako v horečce.
{6932}{6967}Možná, že si vy nevzpomínáte...
{6967}{7076}Ale když jsem s vámi promluvil na|ulici, nemohl jsem zapomenout.
{7094}{7151}Neuvědomila jsem si to, ale když|se pořádně podívám, je pěkný...
{7225}{7257}No je to náhlé...
{7258}{7306}...ale zbývají mi jen tři měsíce života.
{7337}{7368}To je co?
{7386}{7417}Jste jistě překvapená jak někdo,|koho jste nikdy neviděla...
{7418}{7477}...nebo nepotkala,|může říct takovou věc.
{7477}{7519}Tři měsíce...
{7557}{7595}Co se děje?|Jste v pořádku?
{7595}{7623}Dostal jsem ji!
{7623}{7658}Takhle se pozná pravý umělec!
{7701}{7735}No moc času nezbývá...
{7735}{7827}Myslím, že je kruté, když ukončím svůj|mladý život, aniž bych poznal milostný cit...
{7827}{7853}Nemyslíte?
{7878}{7912}Ano, ale...
{7931}{7969}Nemůžete mi pomoci?
{7970}{8007}Co tím myslíte?
{8021}{8072}No, přál bych si, abyste|byla mou přítelkyní.
{8109}{8205}Pokud budete mou přítelkyní,|pak už mě nic špatného nepotká...
{8231}{8270}Uhm... hmmm.. Já...
{8414}{8428}http://umino.gurio.sweb.cz
{8655}{8705}Tři měsíce života?|To je pěkně dramatický začátek...
{8705}{8738}To je jako z televizního seriálu.
{8738}{8779}Ale... kdo je ten mladík?
{8779}{8815}No nevím to jistě...
{8816}{8871}A? Řekneš mu, že to nemůžeš udělat?
{8885}{8918}Ale... skutečně...
{8918}{8940}Nemůžeš!
{8941}{8963}...no...
{8963}{9009}A co bude s Uminem?
{9036}{9081}No, řekla jsem mu, že už přítele mám...
{9081}{9110}Ale když on odpověděl,|že je to jen na tři měsíce...
{9119}{9137}Jsem tak nadšená...
{9138}{9182}...využít čas, který mu zbývá na lásku...
{9183}{9203}Přála bych si něco takového!
{9203}{9230}Pochopila jsi skutečně, co to znamená?
{9238}{9288}Naru, láska a sympatie|jsou dvě odlišné věci...
{9295}{9330}Tohle já... vím.
{9330}{9378}Ale cítila jsem nad ním takovou lítost,|že jsem nemohla říct ne.
{9378}{9411}Naru, jsi tak milá...
{9412}{9443}Úplně jiná než Usagi.
{9444}{9475}Co zas tohle znamená?
{9482}{9508}-Ach lidi.|-Nemám co bych řekla
{9509}{9535}Hele, vy dvě, necháte toho...
{9536}{9563}Odcházím domů...
{9563}{9590}Uvidíme se. Bye-bye.
{9590}{9625}To vidím jako... má z nás depresi.
{9626}{9660}Neřekli jsme jí něco špatného?
{9661}{9701}Ale něco se mi na tom zdá podezřelé...
{9701}{9726}Mám z toho špatný pocit.
{9734}{9778}Musím si s Naru-chan ještě promluvit.
{9778}{9802}Neměli bychom jít taky?
{9802}{9815}Jo.
{9815}{9831}Hej, počkejte!
{9838}{9881}Tohle vypadá jako něco, co už jsme viděli.
{9882}{9899}To vypadá.
{10040}{10060}Tři měsíce...
{10061}{10109}Kdybych to byla já, nemohla bych to snést...
{10135}{10184}Pokud bych něco mohla|udělat, pomoci mu...
{10206}{10245}Ale co řeknu Uminovi?
{10246}{10261}Naru-chan?
{10261}{10276}Umino!
{10276}{10330}Co se děje?|Máš takovou vážnou tvář.
{10331}{10387}No skutečně je něco, co bych|s tebou chtěla probrat, Umino...
{10511}{10564}Nevím, co mám dělat...
{10575}{10623}Ale já opravdu vím,|že jsi tak milá, Naru.
{10636}{10683}Naru, a její lidské stránky!
{10683}{10709}Já... já...
{10709}{10735}Počkej, Umino!
{10736}{10760}Zmizím na několik dní v horách!
{10761}{10785}Sakra, Umino...
{10785}{10804}Naru-chan!
{10804}{10823}Usagi!
{10824}{10865}Umino má docela živou představivost...
{10865}{10888}To přináší potíže.
{10896}{10920}Ale je Naru v pořádku?
{10920}{10942}No vypadá v pořádku.
{10943}{10964}Ale jistě ji to bolí.
{10975}{11016}Ale mám trochu obavy o Umina.
{11093}{11109}To je Umino...
{11110}{11147}Dal se na chlast, ne to je mléko...
{11158}{11227}1, 2, 3, 4... podívejme... 15?
{11227}{11248}Patnáct plechovek?
{11248}{11295}Ach, chce se mi zvracet, jen když to vidím...
{11295}{11314}Budu z toho nemocná...
{11375}{11455}Jsem tak šťastný...|že jste mě přišla vyslechnout...
{11455}{11499}Ve skutečnosti bych vám chtěla něco říct.
{11499}{11537}Co se děje...|Vypadáte přepadle...
{11543}{11590}Taková vážná tvář se k vám nehodí.
{11591}{11639}Už jsem vám to říkala,|mám přítele.
{11639}{11662}A co s tím?
{11663}{11719}Je to někdo, kdo pro mě|hodně znamená.
{11731}{11767}A když na něj myslím...
{11792}{11833}No z něčeho takového|nemusíte mít obavy.
{11845}{11898}Všechno co chci, je mít se|s vámi na chvíli dobře...
{11925}{11966}Právě myslím na věci, která jsou tak dobré...
{11966}{11995}Tady není nic takového...
{12034}{12055}Stůjte!
{12055}{12087}Omlouvám se! Já...
{12087}{12125}...já nemůžu být vaší přítelkyní...
{12143}{12175}Teď to skutečně nemá význam, nemyslíte?
{12215}{12287}Snad si skutečně nemyslíte, že bych se|opravdu zahazoval s někým jako jste vy?
{12326}{12338}Co je to?
{12338}{12394}Jediná věc, kterou potřebuji je váš sen!
{12413}{12428}Sen?
{12428}{12472}Ale ne, musím zavolat Usagi a ostatní!
{12482}{12493}Jedna!
{12510}{12521}Dvě!
{12542}{12554}Tři!
{12626}{12650}Teď se podívám...
{12651}{12675}...na váš sen.
{12675}{12723}Patnáct! Z toho budu nemocná!
{12724}{12769}Hele... je to konec mezi Naru a Uminem?
{12769}{12819}Ty se vždycky zajímáš|o věci jako je tahle!?
{12819}{12835}Ale...
{12836}{12850}Usagi-chan, zavolej všechny!
{12854}{12907}Na Naru zaútočil nový|nepřítel! Rychle!
{12907}{12923}Naru?
{12960}{13010}Moon Crisis...
{13010}{13044}Make Up!
{13617}{13640}To co bych si přál...
{13641}{13664}Pegas tam není...
{13664}{13714}Proč jsou tyhle dívčí sny tak překrásné?
{13714}{13730}Žárlím!
{13730}{13746}Stůj!
{13747}{13763}Cože?
{13763}{13801}Tak, vy jste skutečně oklamal Naru-chan!
{13810}{13846}Nemůžeme dovolit, abyste|si takhle zahrával s jejími city...
{13847}{13887}...a za její přízeň vracel pomstu!
{13903}{13920}Za lásku a spravedlnost!
{13920}{13947}Půvabné bojovnice v námořnickém!
{14003}{14035}Sailor Moon!
{14049}{14085}Sailor Chibi Moon!
{14102}{14126}Ve jménu Měsíce...
{14126}{14151}...ztrestáme vás!
{14164}{14203}Má milovaná Lemure...
{14203}{14249}...přijď a vyřiď tyhle|obtěžující věci.
{14258}{14289}Juggler, Otedamako!
{14289}{14334}Tady, tady, tady.|Tady, tady, tady.
{14388}{14447}Tady, tady, tady.|Tady, tady, tady.
{14447}{14473}Tady! Tady!
{14473}{14526}Nechci dělat něco takového!|Kdokoli, pomozte!
{14526}{14549}Stůj!
{14595}{14623}Tady! Tady! Tady!
{14624}{14642}Pálí!
{14660}{14677}Pálí, pálí!
{14683}{14715}Co budeme dělat?|Nejsme dost silné...
{14715}{14779}Kdykoli budeš v potížích,|zavolej mé jméno...
{14779}{14814}Kdekoli budeš, objevím se u tebe.
{14815}{14855}Pegasi, prosím!
{14855}{14896}Ochraň sny všech!
{14954}{14997}Twinkle Yell!
{15273}{15312}Jak snadno jste udělali|co jsem si přál!
{15365}{15384}Co je tohle za věc?
{15384}{15411}Klec, která má někoho chytit?
{15418}{15442}To snad ne... Pegasa?
{15505}{15531}Pegasi! Ne! Prosím, uteč!
{15683}{15709}Ach, Pegas je...
{15941}{16005}Jsem hlupák, že jsem skutečně|uvěřil Jestřábímu Oku!
{16005}{16066}Pegase nemůže chytit nějaký takový stroj!
{16067}{16098}Rozbiju to na kusy!
{16120}{16167}Otedamako, jsou tvoji!
{16167}{16209}Tady, tady, tady, tady, tady, tady.
{16210}{16226}Tady!
{16239}{16280}Můžeme zemřít, pokud nás|praští něco takového!
{16287}{16315}Tady, tady, tady, tady!
{16389}{16463}Já, Tuxedo Kamen, neodpouštím|takové zneužití čistých dívčích emocí!
{16470}{16535}Nikdy bych nechtěl odpuštění|od někoho takového!
{16536}{16555}Hleďte si svého!
{16567}{16597}Nemáme čas na žerty!
{16605}{16630}Teď, Sailor Moon!
{16630}{16649}Dobře!
{16874}{16917}Moon Gorgeous...
{16917}{16961}...Meditation!
{17153}{17170}Tady!
{17170}{17208}Stage Out!
{17432}{17447}Naru!
{17473}{17506}Ach, Pegas...
{17620}{17641}Zmizel...
{17641}{17688}Co to k sakru může být...
{17704}{17730}"Umino"
{17749}{17770}Ty jsi takový hlupáček...
{17770}{17814}Každému by se zvedl žaludek,|pokud by vypil patnáct plechovek.
{17853}{17905}Ale jsem ráda, že máš mléko rád, Umino.
{17917}{17942}Tady, jedno pro tebe.
{17942}{17976}Ale NE!
