{1}{1}15.000000
{66}{127}Epizoda #132|"Hledej si jiného!|Láska Usagi a Mamora"
{175}{191}Saori-chan.
{191}{224}Tohle je poprvé co jdeš|na takové místo, že?
{225}{241}Ano, je to poprvé.
{241}{292}No myslím, že tam bude trochu nepořádek.
{292}{306}Co říkáš?
{307}{349}Nevím.|Proč si to myslíš?
{350}{418}Protože drobný nepořádek|je v mládeneckém pokoji vždycky.
{476}{547}Kobajaši... Mám tomu rozumět tak,|že máš ve svém pokoji skutečný nepořádek?
{547}{605}No pokud ho vyrušíme s přítelkyní...
{634}{652}Promiňte.
{653}{692}Ach, děkuji za návštěvu!|Pojďte dál, pojďte dál.
{736}{756}Je tu čisto.
{756}{808}Jo... málo jsem mu věřil.
{818}{844}O čem to mluvíte?
{845}{872}Ach, o ničem.
{885}{904}Jsi příšerný mladík.
{912}{948}No, Saori, dokončila jsi svou zprávu?
{948}{975}Vrátila jsem ji už dávno.
{975}{1018}Ano... figurky.
{1046}{1069}Kobajaši?
{1069}{1093}Něco se děje?
{1093}{1142}Nemáš tu nějaké fotografie nebo něco?
{1143}{1164}Obrazy? Proč?
{1164}{1220}No přeci tvé přítelkyně, samozřejmě!
{1231}{1270}Ach, tohle myslíš.|Nemám je vystavené...
{1270}{1294}Co si to myslíš?
{1294}{1315}Proč se tak vzrušuješ?
{1316}{1350}Na tom skutečně nezáleží...
{1350}{1398}Přijde snad dneska?|Tvá přítelkyně?
{1398}{1438}Jo přijde brzo.
{1455}{1476}Mluvící čert.
{1477}{1507}Promiňte na chvíli.
{1532}{1568}Přítelkyně sem, přítelkyně tam.|Začínáš být trochu průhledný.
{1568}{1610}Sakra, to kvůli tobě, Saori.
{1610}{1651}Co s tím mám společného?
{1652}{1673}Saori...
{1674}{1749}Od toho dne, kdys viděla Chibu,|používáš jinou rtěnku.
{1749}{1794}Koukáš, ne?
{1794}{1832}Ty jsi... pěkně zlý chlapík.
{1832}{1879}To není pravda.
{1879}{1926}Ahoj, Mamo-chan!
{1926}{1954}Co je to?
{1961}{1994}Teď obě, pryč ode mne!
{1995}{2028}Co...? Nejsem unavená!
{2028}{2074}Nepřeji si to!|Usagi, pryč od něj!
{2074}{2086}Cože?
{2086}{2116}Protože to je MŮJ Mamo-chan!
{2117}{2140}T-t-ty!
{2140}{2164}Můj-můj-můj!
{2165}{2189}Hele! Ne, ne, ne, NE!
{2189}{2228}To je mé místo!|Pryč odsud!
{2228}{2251}Ne, nehnu se!
{2252}{2276}Příště tě nevezmu!
{2276}{2301}Můžu přijít sama!
{2307}{2328}-Ty jsi skutečně odporná holka!|-Uhm...
{2346}{2397}Omlouvám se za tu strašnou scénu...
{2397}{2417}Dobrý den.
{2433}{2483}Tohle je Saori, moje známá z univerzity|a Kobajaši, který graduoval po nás.
{2495}{2559}Tohle je Tsukino Usagi a tady|naproti Chibi Usa.
{2560}{2587}-Ach, ráda vás poznávám.|-Dobrý den.
{2587}{2629}Hm.. tak tvá přítelkyně je...
{2629}{2695}Jsem Mamo-cha... Mamorova dívka...
{2696}{2731}Já jsem jeho skutečná přítelkyně!
{2732}{2764}Toho bylo dost!
{2772}{2813}Proč nejdeš domů?
{2864}{2880}Usako!
{2958}{3003}-To je tvá chyba!|-Ztichnete vy dvě někdy?
{3003}{3020}Dobře.
{3020}{3040}Omlouvám se.
{3041}{3071}To jsou velmi milé přítelkyně.
{3071}{3094}Tady, něco mám.
{3094}{3110}Huráá!
{3110}{3145}Přítelkyně... no vidím.
{3186}{3210}Kolik máte, Usagi?
{3210}{3271}No budu mít nějakou|jednu, pokud myslíte...
{3272}{3293}Ptal jsem se na váš věk.
{3328}{3356}Je mi patnáct, prvotřídních.
{3364}{3384}Patnáct, co...
{3385}{3396}Ano.
{3396}{3416}To je pěkný věk...
{3417}{3432}Myslíte?
{3432}{3447}Vaše sny i láska kolem vás.
{3469}{3512}Ach myslím, že máte bod.
{3512}{3586}Ačkoliv jsem úplně spokojená|s Mamo-chan láskyplným vztahem.
{3701}{3715}Saori-san.
{3715}{3732}Ano?
{3732}{3779}Jaký je vztah mezi vámi a Mamo-chan?
{3846}{3871}S Mamorem?
{3871}{3907}No byli jsme ve stejné třídě|od začátku vysoké školy...
{3993}{4043}A až dosud je to vztah jen akademický.
{4043}{4063}To není pravda...
{4063}{4083}No možná to teď tak vypadá...
{4084}{4129}...ale Saori se chce po ukončení|studia stát policejní důstojnicí.
{4129}{4171}No... žena důstojníkem?
{4177}{4231}Ne, ne... jejím snem je být první|policejní komisařkou v Japonsku.
{4231}{4245}Neroznášej takové drby.
{4246}{4287}Nejsou to žádné drby.|Skutečně to o tobě vím.
{4287}{4323}Policejní komisařka!
{4323}{4377}To je vznešené!|Snad bych také měla...
{4393}{4461}Myslím, že ví trochu moc na|to, aby to byla jen spolužačka...
{4526}{4558}Dobrý student, se žádnými komplikacemi.
{4559}{4591}Vážná, se silným citem pro spravedlnost...
{4591}{4632}...a vždycky byla mluvčím třídy.
{4632}{4682}Jo, vím. Tyhle typy se vždycky opravdu|připravují na výuku a opakují si učivo.
{4682}{4726}Tyhle poslouchají přesně|co jim dospělí řeknou...
{4726}{4770}Tenhle typ učitelky|preferují víc než ostatní.
{4770}{4823}A také donášejí učitelkám|a pomáhají uklízet třídu!
{4834}{4880}Ale tenhle typ je skutečně bezbranný,|když se dostane k romanci.
{4880}{4942}A tak, navzdory tomu co|říkáš, není to tvůj typ?
{4943}{4968}To je práce.
{5008}{5044}Co je to?|Áá, jsou tak pěkní!
{5044}{5077}Chtěla bych oba!
{5089}{5139}Ale mám malé kapesné, tak si|mohu koupit jen jednoho!
{5151}{5179}Tohle rozmýšlení...
{5180}{5219}Co mám dělat, Chibi Uso?
{5220}{5268}Nemůžeš mít alespoň jednou nějaké starosti?
{5284}{5303}Co tím myslíš?
{5314}{5351}Jako "Je způsob, kterým žiji v pořádku?"...
{5352}{5397}...nebo "Jsem skutečně šťastná,|když takhle právě teď žiji?"...
{5397}{5423}Nebojíš se nějaké takové věci?
{5430}{5457}Co tak nenadále?
{5457}{5489}Ale ano, bojím se mnoha věcí.
{5489}{5520}Například, právě teď se rozmýšlím|zda odejít s hrochem...
{5521}{5538}...nebo koněm.
{5539}{5599}Nevím, který z nich mě učiní šťastnější!
{5600}{5618}Hej!
{5631}{5654}Říkáš pořád jednu a tu samou věc!
{5654}{5677}A nemyslím si, že jsou pěkní!
{5690}{5744}Ty nechápeš tohle|intelektuálské hobby!
{5753}{5805}No víš, myslím, že jsem pochopila|proč Mamo-chan chce poznat ženu sobě rovnou.
{5817}{5851}To s ní tluče tohle dospívání?
{5982}{6043}Tady je...|sladká kůstka...
{6300}{6334}Ach! Skutečně je tak pozdě!?
{6335}{6377}Mám malý problém...
{6377}{6406}Co se stalo?
{6406}{6475}Měl jsem se tady setkat|se svou skupinou o páté!
{6475}{6545}Bez průvodce se|nedostanu do restaurace!
{6588}{6610}Jaké je vaše jméno?
{6647}{6678}Jste velmi krásná.
{6679}{6713}Skvělá, úžasná, nejlepší!
{6714}{6768}Prosím, prosím, doprovoďte mě na večeři!
{6779}{6825}Právě teď na někoho čekám.
{6826}{6847}No, omlouvám se.
{6937}{6951}Jo!
{6951}{6977}Ach, Mamoru!
{6993}{7014}Omlouvám se, žes musela čekat.
{7014}{7034}Bez problémů.
{7034}{7050}Sbohem.
{7143}{7172}Je to jiný příběh, pokud má chlapce.
{7172}{7203}V tom případě, to bylo...
{7203}{7253}...trochu jako podezřelý mladík co|zkouší urvat nějakou holku.
{7253}{7273}Mlčte!
{7274}{7333}V takovém případě ji dostanu silou!
{7379}{7419}Chtěl bych se rozejít, Usako.
{7434}{7447}Mamo-chan...
{7456}{7488}Opravdu... teď miluji Saori.
{7488}{7520}Konečně jsem si to uvědomil.
{7529}{7543}Nemožné!
{7543}{7578}Vidíš? Tolik ji miluji!|Vidíš? Vidíš?
{7578}{7600}Ne, to je lež!
{7600}{7622}Odpusť mi.
{7622}{7648}Počkej, Mamo-chan!
{7648}{7678}Není proč čekat.|Řekni Chibi Use ať si na sebe dává pozor.
{7684}{7748}Pokud se se mnou neoženíš, Mamo-chan,|Chibi Usa se nikdy nenarodí!
{7795}{7815}Tohle není dobré...
{7815}{7879}Možná tohle je úder té největší|krize pro mě, Chibi Usu?
{7958}{7972}To... to je...
{8039}{8067}NÉÉÉÉÉ!
{8200}{8215}Ahoj.
{8216}{8256}Do-do-dobrý den.
{8366}{8394}http://umino.gurio.sweb.cz
{8616}{8642}Omlouvám se, ale nezdržuji tě?
{8643}{8658}Ne.
{8658}{8688}Prosím, klidně mi řekni|pokud bych ti dělala potíže.
{8688}{8722}Cože? Je to v pořádku|ničeho se neboj.
{8730}{8747}Ano...
{8753}{8786}Co to chceš kupovat,|že musím jít s tebou?
{8823}{8863}Není to něco pro nějakého chlapce?
{8863}{8904}Tihle dva jsou proteskní pár...
{8904}{8947}A to byli zvoleni jako nejlepší|pár na univerzitě.
{8947}{8989}Skutečně byli stvořeni jeden pro druhého...
{9054}{9091}No, snad mohu mít ještě šanci...
{9097}{9156}...pokud má Mamoru skutečně dobrou přítelkyni...
{9174}{9212}Ještě to nevzdávejte!
{9222}{9258}Pomohu vám!
{9264}{9296}Bojujte, Kobajaši!
{9296}{9330}Vydejte ze sebe to nejlepší co máte, Kobajaši!
{9331}{9365}-Děti jsou tak jednoduché...|-Bojujte, Kobajaši!
{9366}{9400}Vydejte to nejlepší, dejte všechno, Kobajaši!
{9460}{9489}Tohohle?
{9498}{9528}Ne, tohohle.
{9540}{9557}Hej!
{9569}{9605}Co je? překvapila jsi mě!
{9605}{9673}Jak víš, že pokud se budeš chovat takhle, tak se|Mamo-chan skutečně bude plazit u tvých nohou?
{9687}{9703}Cože?
{9703}{9753}Jsi tak nechápavá... co takhle Saori?
{9753}{9815}Když vás porovnám, je to jak|Měsíc a želva a ty jsi ta želva!
{9824}{9886}Pokud neudeříš tvrdě, ty domýšlivá,|tak tvá láska k Mamo-chan nemá šanci.
{9886}{9919}Protože Saoiri je víc krásnější...
{9919}{9980}a dospělejší, přitažlivější|a vypadá mnohem inteligentněji!
{9980}{10050}Když nad tím přemýšlím, bylo by mnohem|lepší, kdyby Saori byla má matka!
{10050}{10080}Ačkoli bych si to nechtěla připustit...
{10080}{10141}...pokud to nedotáhneš s Mamo-chan|do konce, tak se nikdy nenarodím!
{10158}{10204}Tak teď, už máš o trochu větší obavy?
{10204}{10249}Mamo-chan, mě nemůže nenávidět!
{10250}{10277}Konečně jsi pochopila.
{10277}{10305}No potom trochu dospělejší...
{10305}{10341}Jen žertuju!
{10359}{10410}Nikdy jsem nepochybovala|o lásce Mamo-chan!
{10410}{10433}Ty ho nemůžeš dostat, ne?
{10433}{10483}Proti tomu je tenhle hrocho-koňský|problém trochu luxus.
{10517}{10548}Měl bych něco vědět?
{10549}{10593}Chceš tu vázanku dát|nějakému chlapci jako dar.
{10603}{10622}Chceš to vědět?
{10622}{10677}No, jo. Nemohu si představit chlapce,|který by se k tobě hodil, Saori.
{10677}{10700}Co tím myslíš?
{10700}{10722}Omlouvám se.
{10772}{10806}To nemůžeš, jak bych to řekl...
{10806}{10831}Je to příšerné...
{10832}{10856}Co? Tahle kravata?
{10857}{10896}Ne to ne, ale někdo vedle mě...
{11084}{11100}Teď je...
{11219}{11232}Jedna!
{11247}{11258}Dva!
{11278}{11289}Tři!
{11364}{11375}Saori!
{11522}{11542}Co k čertu chcete?
{11542}{11567}Tohle je omezování osobní svobody!
{11567}{11586}Ach, skutečně?
{11587}{11631}Zastavte se! Pokud skončíte|teď, bude to jen přečin.
{11640}{11660}Přečin?
{11699}{11758}Teď se podívám, jaký|překrásný sen skrýváte!
{11800}{11858}Je tady?|Je tu Pegas?
{11871}{11916}Hej, kam mě to táhneš?|Klid, Chibi Uso...
{11962}{11974}To je...
{11975}{12004}Mamo-chan a Saori!
{12073}{12113}Moon Crisis...
{12114}{12147}Make Up!
{12678}{12755}Tak vidím, že ve vašem snu ještě není, ač|máte nekonečný cit pro spravedlnost.
{12797}{12814}Stůj!
{12829}{12884}Nemohu odpustit chytání nevinných|žen pro vaše ďábelské plány!
{12892}{12915}Za lásku a spravedlnost!
{12916}{12944}Půvabné bojovnice v námořnickém!
{13002}{13031}Sailor Moon!
{13042}{13082}Sailor Chibi Moon!
{13096}{13122}Ve jménu Měsíce...
{13122}{13147}...ztrestáme vás!
{13156}{13195}Sailor Moon...?
{13219}{13249}Ke mě, má Lemure...
{13250}{13291}...balónková dívko, Puko-chan!
{13466}{13496}Puko-chan!
{13583}{13615}-Co...|-Uch, cože?
{13665}{13694}Sailor Chibi Moon!
{13694}{13754}Věřím, že si je vezmete na starost, Puko.
{13843}{13881}Tahle není krásná!
{13893}{13914}Chibi... Moon...
{13995}{14027}Saori! Pozor!
{14100}{14139}Ach já, myslím že půjdu k němu!
{14356}{14407}Na stranu, Sailor Moon!
{14447}{14501}Chcete ho chránit a použila jste|vlastní tělo jako štít!
{14501}{14538}Překrásné! To je opravdu překrásné!
{14591}{14618}K čertu, nech toho!
{14627}{14693}To je v pořádku. Hned po tom,|co ji zabiji, zabiji i vás.
{14841}{14860}Usako!
{14860}{14879}Usako!!
{14912}{14925}Usako?
{15062}{15091}Chápu...
{15227}{15239}Usako!
{15260}{15298}Vstávej!
{15319}{15341}Jsem v pořádku...
{15407}{15439}Sakra, co jste to udělali?
{15439}{15462}Chibi Moon, TEĎ!
{15501}{15560}Pegasi, prosím!|Ochraň sny všech!
{15612}{15662}Twinkle Yell!
{15745}{15780}Tohle mě tak rozhodilo!
{16019}{16061}Moon Gorgeous...
{16062}{16104}...Meditation!
{16308}{16343}Stage Out!
{16668}{16704}Děkuji...
{17121}{17160}Saori-san...
{17177}{17200}Jak bylo včera?
{17221}{17235}Proč se ptáš?
{17241}{17265}Nehraj si se mnou.
{17265}{17305}Mluvil jsem o Chibovi.
{17305}{17344}Řekla jsi mu co cítíš, ne?
{17361}{17380}Proč?
{17408}{17424}Ty víš...
{17424}{17438}Ano?
{17450}{17490}Dávám ti tohle. Je to|lepší než to vyhodit.
{17499}{17532}Tohle...
{17533}{17560}Tys mi dala přednost...
{17561}{17588}Není to trochu nezvyklé,|aby začala žena...
{17588}{17648}...zvlášť ta, co by se chtěla|stát policejní komisařkou?
{17648}{17708}Ale ne, že bych se necítil|tak nějak dobře... ale... uhmm...
{17755}{17815}Není způsob jek bych mohla zvítězit nad|dívkou, která udržuje klid na celé zemi...
{17861}{17883}Hej, pojď trochu blíž!
{17883}{17905}Proč by měl jít k tobě blíž?
{17906}{17932}Překážíš tady, překážíš,|překážíš, ty špunte!
{17932}{17976}Musíš se jít domů učit!
