{1}{1}15.000000
{37}{76}To je skutečně pěkný příběh...
{77}{104}"Pegas v záři Luny...
{105}{190}Neopětovaná láska mezi pegasem|a lidskou ženou...
{224}{278}Nezáleží, kolikrát si to přečtu,|na konci jsem tak rozervaná!
{278}{307}Ach, četla jsem to!
{307}{357}A pochopila jsem proč se mohlo|prodat přes milión výtisků.
{357}{381}Jo, jo, jo.
{381}{448}Ale stejně... vidět Usagi, která si|prohlíží jen komisy, číst román...
{448}{481}Není to na tebe náročné?
{481}{499}O čem to mluvíš?
{499}{557}Rei-chan, ty jsi snad tuhle knihu|ještě nečetla... Nemám pravdu?
{581}{637}Když jsem tuhle knihu četla,|brečela jsem snad desetkrát!
{638}{688}Taky bych chtěla prožít|tak vášnivý románek...
{689}{741}Opravdu, tohle je příběh, který|dokáže stisknout tvoje srdce.
{751}{769}I Ami-chan?
{769}{800}To musí být něco!
{800}{831}Kde na to vezmu čas?
{841}{856}Je to úžasné...
{856}{905}Chtěla bych vědět, jestli tahle osoba|zná toho samého Pegase jako já.
{1063}{1129}Epizoda #134|"Přítelkyně Makoto-chan!|Dívka, co zbožňuje Pegase."
{1152}{1177}Ne, skutečně nic.
{1184}{1235}No, autorka tohohle|románu, Takase Tomoko...
{1235}{1304}...byla má spolužačka na staré škole.
{1313}{1358}Ach, opravdu?|Je stejně stará jako ty?
{1368}{1414}Tak to musí být rozdíl mezi někým|s talentem a bez talentu!
{1415}{1437}Nechte toho!
{1437}{1466}A Mako-chan, ty taky!
{1466}{1514}Tajit před námi takovou důležitou věc!
{1514}{1616}No, kdybych to roznášela, vypadala bych jako|někdo, kdo se chlubí cizí slávou...
{1625}{1679}No, když je to tak, ale...
{1679}{1728}Kdyby to byla Usagi, určitě by|to vytrubovala všude kolem.
{1728}{1744}Jo, jo.
{1763}{1789}Tohle nebylo nutné, Luno.
{1789}{1839}Úplně na začátku jsem to byla|já, kdo podněcoval Tomoko...
{1840}{1889}...a donutil ji odeslat|ten příběh do časopisu.
{1906}{1962}Když to napsala, četla jsem to první|a řekla, co si o tom myslím.
{1980}{2034}A Tomoko vždycky říkala, že ji to povzbudí,|když je při psaní zoufalá.
{2050}{2078}A co já vím, tak beze mne by to třeba ani neposlala!
{2078}{2122}Byl to román...|"Pegas v záři Luny"
{2141}{2197}Tak... důvod, proč dnes|můžeme číst Tomokino novelu...
{2197}{2262}...je ten, že jsi v ní našla|talent, Mako-chan!
{2262}{2295}No myslím, že to trochu převracíš, ne?
{2296}{2337}Sakra, tak nakonec jsi vejtaha.
{2338}{2408}Ale to všechno je minulost.|Teď, když je super populární...
{2418}{2468}Když jsem změnila školu a byla|zaneprázdněná ostatními úkoly...
{2468}{2529}...nestihla jsem jí ani k tomuhle pogratulovat...
{2562}{2598}Mako-chan...
{2608}{2623}Hele, Mako-chan!
{2624}{2694}V neděli ji navštívíme a požádáme o autogram!
{2716}{2734}Ale...
{2746}{2773}No tak, bude to fajn!
{2774}{2825}Tomoko tě určitě ráda uvidí, Mako-chan!
{2826}{2876}Hej, Usagi, jen protože si přeješ...
{2876}{2908}Já bych ji chtěla taky vidět!
{2908}{2963}Chtěla bych taky navštívit tu milou|osobu, která napsala tenhle román.
{2963}{2989}Mako-chan, prosím!
{3061}{3106}No myslím, že ji nejdřív|navštívím jen na chvilku.
{3122}{3138}Dobře!
{3158}{3243}Tak opravdu mi dokážete chytit Pegase?
{3255}{3280}Samozřejmě, Zirkonia-sama...
{3280}{3294}Mlčte!
{3318}{3370}Dívám se na vás... a vy se|staráte jen o zjevení.
{3371}{3423}Co je to platné, když máte|mozek prázdný jako míč!
{3446}{3475}Vítej zpátky, Zirkone.
{3543}{3569}Tentokrát půjdete za touhle dívkou!
{3627}{3654}Ach, tuhle dívku znám.
{3655}{3690}Není to ta super populární spisovatelka?
{3697}{3769}Taky jsem četl knihu, kterou napsala!|Úplně mě to sebralo!
{3770}{3810}Jo, jo! Zvlášť to, jak pegas skočí...
{3810}{3851}A obětuje svůj život za|hrdinku... To je tak stupidní...
{3851}{3878}Nechte toho!
{3879}{3932}Příběh jak pegas může|zachytit lidské srdce...
{3932}{4015}Tahle autorka... to je Takase Tomoko?|Snad ví něco o Pegasovi.
{4016}{4061}Nechte to na mě.
{4068}{4119}Spisovatelce nemohu pomoci, ale mohl|by to být prchavý románek...
{4119}{4179}...ve kterém se mohu|rozpustit, pokud to zkusím.
{4199}{4282}V tomhle případě, myslím, Mako-chan|je přítelkyně Tomoko-san!
{4282}{4336}Nakonec, proč počítat celebrity...
{4336}{4366}Nemyslíš přítele?
{4386}{4433}Vzala jsem extra výtisk na autogram.
{4433}{4459}Tohle není dost, Usagi.
{4459}{4512}Když chceš autogram, potřebuješ|nejméně tři výtisky!
{4513}{4528}Proč?
{4529}{4582}Jeden pro sebe doma,|jeden pro bezpečné uložení...
{4582}{4628}...a třetí na chlubení se druhým!
{4650}{4663}Rei-chan...
{4663}{4711}Tak se zase ukázala jedna|její špatná vlastnost...
{4718}{4757}Pokud si pamatuji, je to někde tady...
{4767}{4806}Když zahneme, budeme stát|právě před jejím domem!
{4838}{4872}Makoto-san vypadá skutečně šťastná.
{4873}{4907}Ale jistě!|Vždyť může dostat autogram!
{4908}{4937}Tohle to není, Mino...
{4971}{5019}Již brzo potkám osobu,|která napsala tuhle knihu...
{5084}{5099}Co... co je tohle?
{5099}{5126}Takase-sama, pokud mi|nedodáte do zítřka rukopis...
{5127}{5151}Prosím, ukažte se!|Vím, že nás slyšíte!
{5254}{5303}Spisovatelka jako ona tíhne|k fanouškům stejného pohlaví...
{5304}{5355}A tak jsem si jistý, že mezi svými fanoušky|nemá tak pěkného muže jako jsem já!
{5355}{5380}Zahledí se do mě na první pohled!
{5459}{5506}To je snad žert!|To mám TOLIK soupeřů?
{5507}{5529}Nesmím se vzdát!
{5565}{5589}Pusťte mě!|Stranou, pusťte mě!
{5590}{5614}-Nepředbíhejte!|-Vraťte se jindy!
{5615}{5656}-Takové prase k ní nepustíme!|-Co jste za vydavatele?
{5668}{5688}Co se děje?
{5699}{5732}No vypadá to, že|Tomoko-san nenadále zmizela.
{5732}{5768}A její dlouho očekávaný rukopis taky...
{5794}{5806}Nemožné!
{5807}{5856}Možná utekla před svou prací?
{5869}{5946}Ona by takovou věc nikdy neudělala!
{5946}{5978}Tomoko žije jen svými příběhy!|Jen svými příběhy!
{5978}{5997}Mako-chan!
{6135}{6147}Tomoko!
{6161}{6196}Mako-chan...
{6228}{6254}Tak nakonec jsi tady...
{6255}{6281}Ani trochu ses nezměnila.
{6325}{6353}Proč jsi utekla?
{6354}{6418}Myslela jsem, že tvým snem bylo|psát knihy, které miluješ psát!
{6434}{6456}Nemohu psát...
{6457}{6478}Nemohu psát!
{6479}{6544}Když si sednu před prázdný papír, ani|jedno slovo se neobjeví v mé hlavě!
{6552}{6576}Tomoko...
{6576}{6645}Skutečně nedokážu napsat příběh|lepší než "Pegas ve světle Luny"...
{6645}{6693}Všechny mé sny jsou pryč!
{6693}{6717}Počkej, Tomoko...
{6801}{6854}Tak vidím, že spisovatelka je v krizi...
{6854}{6879}Tohle si žádá změnu plánu.
{6880}{6922}Téhle perfektní příležitosti musím využít!
{6922}{6944}Ale...
{6944}{6978}Mé pozadí je trochu chladné...
{7148}{7171}Něco se stalo?
{7172}{7196}Jo, tak trochu...
{7196}{7250}Co se to sakra stalo?
{7250}{7293}Tomoko tolik milovala psaní románů...
{7301}{7339}Tady, tady, právě tady!
{7349}{7374}Nechte toho! Vraťte mi to!
{7374}{7387}Právě tady!
{7387}{7410}Nechcete zkusit něco tvrdšího?
{7411}{7446}-Jo, jo, právě tady, tady!|-Vraťte to!
{7446}{7465}Tak to bylo dost!
{7511}{7524}To... to je...
{7525}{7545}K čertu, to je Makoto!
{7545}{7562}Rychle pryč!
{7595}{7623}Uhm... děkuji.
{7623}{7681}Když můžeš říct děkuji, proč|jsi je nemohla nakopat?
{7703}{7736}Ach, ty jsi z mé školy?
{7736}{7769}Jo, jsme spolu ve třídě...
{7769}{7843}Ach, promiň... Nevzpomněla jsem si,|protože právě měním školu.
{7853}{7883}Co je to?|Domácí úkoly?
{7883}{7912}Ne, to ne.
{7912}{7949}To je... můj rukopis.
{7949}{7987}Rukopis?
{8005}{8024}Nech toho! Vrať mi to!
{8024}{8043}Jen si to přečtu.
{8043}{8092}Právě jsem to dopsala|a ještě nikomu neukázala...
{8093}{8115}Tiše!
{8270}{8283}To je nádherné!
{8310}{8348}Tvůj příběh miluji!
{8348}{8384}Nevypadám na to, ale|miluji takové příběhy...
{8384}{8420}Ale tohle je poprvé,|kdy mě ten příběh vtáhl.
{8431}{8467}Ach, děkuji...
{8468}{8494}Něco takového ráda slyším,|pokud to ovšem nebyla zdvořilost.
{8494}{8537}K lidem které neznám nejsem zdvořilá.
{8537}{8585}Když zase něco napíšeš,|dej mi to přečíst.
{8591}{8604}Děkuji!
{8642}{8664}http://umino.gurio.sweb.cz
{9196}{9207}Jo!
{9207}{9225}Mako-chan...
{9226}{9240}Děkuji.
{9241}{9256}Vidím...
{9256}{9310}Tomoko, tobě se líbí takový, jako tenhle mladík?
{9336}{9412}Když se na něj dívám, vidím|obrazy ze svého dalšího příběhu...
{9413}{9437}Tak ty...
{9450}{9463}...zeptala jsi se ho?
{9477}{9515}Nemůžu... je tolik populární...
{9515}{9544}Nikdy se na mě nepodívá...
{9545}{9583}V tom případě, co zkusit být trochu odvážnější...
{9584}{9621}...a poslat svůj příběh do časopisu nebo tak.
{9621}{9653}Možná si přečte tvůj příběh!
{9653}{9685}Pokud ho vydají v nějakém časopise a...
{9686}{9721}...začne se o něm po městě mluvit,|určitě se na tebe podívá!
{9741}{9772}A vyjde mi taková věc?
{9773}{9804}Musí!|Zaručuji to!
{9919}{9935}Mako-chan...
{9935}{9969}Hej, kde je Chibi Usa?
{9994}{10016}To není možné...
{10114}{10155}"Pegas v záři Luny"|"Autogramiáda Takase Tomoko"
{10187}{10203}Děkuji!
{10203}{10230}Další, prosím...
{10247}{10263}Ahoj!
{10389}{10436}Nezáleží na tom, kolik|příběhů napíši, nikdy...
{10436}{10466}Nikdo mě nakonec nepochopí!
{10466}{10487}Nikdo...
{10487}{10507}Tomoko-chan!
{10563}{10591}Viděla jsem Pegase!
{10622}{10684}Koně s překrásnými křídly, právě|jako ten, o kterém je váš příběh!
{10684}{10715}Váš příběh mě skutečně zasáhl!
{10715}{10761}Protože teď vím, že někdo|viděl ten samý sen jako já!
{10762}{10784}Stejný... sen?
{10784}{10806}Tak, prosím...
{10806}{10860}Chtěla bych si přečíst víc|příběhů, které napíšete!
{10886}{10907}Ne, nemůžu psát!
{10907}{10932}Nevidím způsob, jak bych mohla psát!
{10932}{10953}Chceš...
{10953}{10983}...snad všeho nechat?
{10983}{11007}Mako-chan...
{11007}{11031}Usagi-san.
{11048}{11078}Právě teď to nech na Mako-chan.
{11088}{11181}Stane se z tebe zase zbabělec, co skrývá všechny|své příběhy hluboko do zásuvky...
{11181}{11234}...jen protože je vyděšený,|že by si je mohli druzí přečíst?
{11242}{11320}Pokud existuje alespoň jedna osoba, která čte tvé příběhy,|pak musíš psát pro toho jediného čtenáře!
{11320}{11354}Nebyl to snad tvůj sen?
{11370}{11421}Tomoko, snění o psaní|teď už není jen tvá věc!
{11459}{11480}Mako-chan...
{11691}{11736}Jak to jde slečno?|Jak jste daleko s rukopisem?
{11758}{11769}Kdo jste?
{11769}{11796}Ach, omlouvám se za ten pozdní vpád.
{11796}{11838}Jsem váš nový vydavatel.
{11838}{11892}Taiga za Dead Publishing.|Rád jsem vás poznal.
{11893}{11947}Dead Publishing?|Nikdy jsem o něm neslyšela.
{11965}{12041}Autoři, kteří pracují uzavřeni doma, mají tendenci|vzplát láskou ke svým vydavatelům.
{12049}{12111}Nyní plameny lásky|spálím vaše srdce!
{12238}{12276}Jupiter Star Power...
{12276}{12305}...Make Up!
{12581}{12619}Moon Crisis...
{12620}{12658}...Make Up!
{13194}{13250}Jsem si jistý, že jste|přeplněná zázračnými sny...
{13250}{13290}Musím je všechny vidět!
{13290}{13318}Jedna!
{13327}{13351}Dva!
{13352}{13375}Tři!
{13482}{13500}Sparkling...
{13501}{13535}...Wide Pressure!
{13580}{13596}Co... co to bylo?
{13596}{13635}Tomoko se nedotknete ani prstem!
{13636}{13650}Cože?
{13651}{13674}To je pravda!
{13683}{13748}Ty zločinecká jedničko, hrající si na editora|a pokoušející se slupnout autorčiny sny!
{13756}{13778}Za lásku a spravedlnost...
{13778}{13809}Půvabné bojovnice v námořnickém!
{13866}{13898}Sailor Moon!
{13909}{13946}A Sailor Chibi Moon!
{13962}{13988}Ve jménu Měsíce...
{13988}{14015}...ztrestáme vás!
{14016}{14042}Tak jste tu zase.
{14042}{14069}Ke mě, má Lemure.
{14069}{14151}Panenko Tenko, utíkající před ohrožením života|artistko s časovanou bombou, Tenko-san!
{14151}{14225}Tenko!
{14225}{14265}Tenko, tenhle problém nechávám na vás.
{14266}{14294}Tenko!
{14324}{14341}Dobře!
{14342}{14396}Nejdříve vás spoutám řetězy!
{14540}{14558}K čertu...
{14559}{14576}Supreme...
{14577}{14615}Nech toho, jinak...
{14624}{14652}...Thunder!
{14733}{14757}Říkala jsem, abys počkala...
{14774}{14803}To je pohled.
{14804}{14833}No, mezitím se...
{14834}{14852}Stůj!
{14885}{14902}Překrásné!
{14903}{14934}Ale kde je Pegas?
{14969}{15039}No nic, stejně jsem tu|na rozkaz Zirkonie-sama!
{15049}{15092}Tenko, vyřiď je všechny!
{15092}{15109}Tenko!
{15109}{15154}Teď nastavím časovač!
{15229}{15246}Co je tohle?
{15246}{15263}Časovaná bomba.
{15263}{15295}Za dvě minuty... BUM! Jasné?
{15296}{15331}-Co, my budeme BUM?!|-Nežertujte!
{15351}{15377}Můžete zkusit uniknout!
{15441}{15454}K čertu!
{15471}{15499}To je marné! Marné!
{15716}{15755}Řetězy nejsou pro panny dost půvabné.
{15755}{15814}Jediní, kdo řetězy potřebují jsou zločinci a vzteklí psi!
{15824}{15853}Tuxedo Kamen-sama!
{15854}{15884}Tohle vám vrátím!
{15999}{16025}Teď Chibi Moon!
{16050}{16105}Pegasi, prosím!|Ochraň sny všech!
{16164}{16211}Twinkle Yell!
{16312}{16346}To je... pegas...
{16346}{16403}K čertu s vámi...|Tak, další útok...
{16623}{16678}Moon Gorgeous...
{16688}{16717}...Meditation!
{16919}{16973}Stage Out!
{17107}{17131}Tohle snad ne!
{17193}{17218}Jsi v pořádku Tomoko?
{17218}{17231}Jo...
{17231}{17290}Mako-chan, viděla jsem ho!|Skutečného pegase!
{17318}{17386}Když mohu vidět takové zázračné věci...|pak mohu zas chvíli psát!
{17386}{17431}Ne mohu napsat spousty věcí!
{17431}{17485}Tentokrát ne pro sebe,|ale pro všechny!
{17523}{17550}Uvidíme co uděláš!
{17550}{17577}-Sbohem!|-Bye-bye!
{17594}{17608}Mako-chan...
{17627}{17670}Až zakončím nový příběh, můžeš ho zase přečíst?
{17682}{17701}Ale jistě!
{17702}{17742}Jsem tvůj první čtenář!
{17838}{17884}"Fantazie s Pegasem"
{17891}{17961}Věnováno mé drahé přítelkyni|Makoto a všem, kteří mají sen...
