{1}{1}15.000000
{42}{133}Epizoda #144|"Zářivé letní dny!|Ami, dívka v oceánské bríze."
{424}{473}Tihle kluci jsou tak absolutně nádherní!
{481}{536}Ach, máš pravdu!|Ale s Mamo-chan se nemohou měřit...
{536}{568}Ukaž.
{568}{600}Ach, ten mladík tamhle!
{600}{613}Kde?
{613}{631}Kde? Kde? Kde? Kde? Kde?
{632}{656}Hledám ho...
{657}{704}Přišli jsme si sem na pláž|odpočinout a co u ďasa dělají?
{704}{726}Opravdu...
{810}{835}Hej, slečny!
{836}{874}Nešli byste si s námi zaplavat?
{874}{913}Víme toho o tomhle místě dost.
{967}{988}Máme na lepší...
{989}{1010}...mnohem lepší...
{1011}{1033}Šingo, prosím!
{1082}{1122}Hej, hej, hej... chcete snad|něco mým děvčatům?
{1123}{1146}Co je to k čertu za kluka?
{1146}{1169}Ty víš, je tu trochu horko...
{1169}{1199}Jdeme!
{1231}{1266}Sakra...
{1277}{1321}Proč musím dělat něco takového?
{1321}{1345}Nemůžeme si pomoct!
{1345}{1397}Mamo-chan se dnes nemůže|utrhnout z univerzity.
{1397}{1455}Tak je to tvá práce dělat strážce|těmhle mladým a křehkým dívkám.
{1455}{1495}Kde tu jsou nějaké mladé|a křehké dívky?
{1496}{1535}Ty máš tolik zodpovědnosti, Šingo-kun.
{1586}{1627}Teď se o nás nemusíš bát,|tak co si neskočit...
{1628}{1673}...na chvíli si zaplavat?|Je to pěkné.
{1691}{1723}Jen pojď, Šingo.
{1735}{1764}To je v pořádku, můžu jít sám...
{1764}{1783}Co to bylo?
{1783}{1827}Ami je divně příjemná na Šinga...
{1828}{1872}To musí být ten šarm starší ženy!
{1873}{1907}No, taky to tak vidím...
{1908}{1942}Co je?|O čem to melete?
{1942}{1969}Klid!
{1970}{1998}Mám to!
{2044}{2068}Amazonské trio...
{2068}{2103}Stále ještě nemáte Pegase?
{2104}{2136}Musíme najít toho,|který má překrásný sen...
{2137}{2156}Ale Pegasovi je těžký přijít na...
{2156}{2188}Žádné výmluvy!
{2276}{2318}Jděte za tímhle dalším cílem!
{2419}{2474}No to je pěkný objev...
{2474}{2506}Ale vypadá jako ten|typ s velkým mozkem...
{2507}{2538}...a jasně ví co se jí líbí a nelíbí...
{2538}{2569}Navázání kontaktu bude asi těžké...
{2569}{2626}Bude to opravdu těžké přinutit nějakou takovou,|aby se do tebe zakoukala...
{2626}{2683}Už jsem domluvila, tak proč|se neřídíte mými příkazy!?
{2692}{2733}Ne, jen jsme se připravovali...
{2733}{2774}Už nic víc nechci slyšet!
{2774}{2828}Proč by měl někdo|s vámi flirtovat?
{2829}{2870}Vaše mozky mi nejsou k ničemu!
{2871}{2912}Mozky! Mozky!|K ničemu!
{2912}{2984}Pořád melou, ale jejich mozky|jsou vyplněné červenými boby!
{2985}{3006}Neužiteční!
{3006}{3025}K čemu na světě jsou dobří?
{3026}{3048}Pobláznění playbojové!
{3048}{3067}Mozky, mozky!
{3067}{3095}Nezáleží jak studené srdce má cíl...
{3095}{3178}...já, Tygří Oko ji získám, podle|příkazů Zirkonie-sama!
{3179}{3223}Doufám, že se v těhle|slovech neskrývá lež.
{3223}{3271}Ne, jen hrdost Amazonského tria!
{3413}{3476}Tohle už sám nedělej!|Vždycky mi dopředu řekni!
{3572}{3637}Ty víš, Tygří Oko, je moudré|cpát se takovým blafem?
{3638}{3655}Pravda!
{3655}{3699}Pokud selžeš,|jak si to zodpovíš?
{3741}{3778}Nedělejte potíže, vy dva...
{3778}{3835}A mezitím i když|to bude těžké...
{3835}{3882}...myslím, že každá podlehne|nějaké sladkosti, ne?
{3882}{3929}Smůla na smůlu... a to je hit!
{3930}{3976}Hele, nepřelaďuj to rádio!
{3977}{3991}K čertu s vámi!
{3991}{4031}Nestěžujte si, když poslouchám své rádio!
{4046}{4085}No, no právě to čekám,|tohle se stane...
{4085}{4124}...když se opravdu nechám|unést obchodem!
{4124}{4166}Tady máte, smažené nudle!
{4175}{4202}Chtěla bych třešňový sirup a mléko!
{4203}{4218}Prosím, Modrou Havaj!
{4218}{4251}A já si dám zelený čaj s rudými boby!
{4252}{4285}Ty máš ale pěkně dospělé chutě...
{4375}{4398}Ach, strašně se omlouvám!
{4499}{4551}Omlouvám se, že jsem|vyplýtval váš sněhový krém.
{4552}{4578}Abych to odčinil...
{4579}{4626}...dovoluji si vás pozvat na mou|soukromou pláž... co na to říkáte?
{4741}{4783}Hej, hej, kdo k čertu jste?|Pokud chcete flirtovat, tak zmizte...
{4783}{4813}Soukromá pláž?
{4835}{4899}To je zase ta záletnice!|Proč je tu?
{4913}{4926}Tak úžasný...
{4926}{4973}To je jako sen, že nás zvete...
{4974}{4999}Rády půjdeme!
{5000}{5040}Hele, Usagi!|O tomhle se dozví Mamo-chan!
{5040}{5073}Pak je pak, a teď je teď!
{5073}{5103}Co děláte?
{5114}{5151}Co je to za chtivé malé holky?
{5152}{5186}No víte, jen jedna byla pozvána...
{5186}{5220}Nemohu akceptovat takovou nabídku.
{5220}{5238}Ano?
{5239}{5269}Byla bych příliš bezstarostná...
{5269}{5329}Nemohu jít s někým koho|jsem nikdy nepotkala...
{5329}{5392}Ne, není třeba se bát.|Jen si přeji odčinit svou chybu.
{5392}{5407}To je příjemné nabídka, ale... promiňte.
{5419}{5469}Jdeme.
{5498}{5523}-Hele, Ami, počkej!|-Omluvte mě...
{5598}{5638}Sakra, taková veš!
{5638}{5674}Je tvrdohlavější,|než jsem si myslel!
{5674}{5709}Tak co, říkal jsem že je to nemožné.
{5710}{5758}Hlavně nechce nikoho,|kdo by se jí dotkl.
{5758}{5795}Nebuďte tak necitliví!
{5806}{5842}Oč je těžší se k ní přiblížit...
{5842}{5890}...o to hodnotnější bude až ji získám!
{5890}{5927}Jen počkej, holka!
{6024}{6043}Proč?
{6044}{6068}Byl tak atraktivní...
{6068}{6092}To bylo plýtvání!
{6093}{6129}Ty se definitivně držíš.
{6129}{6166}Jsem si jistý, že ty bys šla, Mino.
{6248}{6299}Nevíme kdo to je|a odkud je.
{6300}{6321}To je co!
{6322}{6389}Pokud nevíme kdo to je|je nemožné si sním vyjít!
{6404}{6452}Nemyslím si, že láska je něco|na co by se mělo pospíchat...
{6464}{6529}Pokud vám partnera přivane bůh|a spojí vás rudou stuhou osudu...
{6529}{6578}...stále je čas potkat toho pravého...
{6579}{6659}A myslím si, že to bude nějak jiné|když potkáte někoho takového.
{6696}{6731}Osudový partner...
{6838}{6880}Osudový partner, uch...
{6880}{6926}Opravdu, když jsem potkala Mamo-chan...
{6926}{6949}Jo, jo, toho máme dost!
{6950}{6965}No jo.
{6965}{7036}Tak nakonec,|to nebyl tvůj typ, Ami-chan?
{7037}{7070}Tak by to mohlo být!
{7070}{7098}-Sakryš, ty máš ale laťku pěkně vysoko!|-Hí, Ami...
{7098}{7117}To tak není...
{7117}{7195}Je trochu těžké najít svůj předurčený protějšek,|když nikdy neuděláš první krok!
{7205}{7263}V tvém případ, Ami-chan... nemyslíš, že bys|mohla být trochu víc rozhodnější?
{7269}{7287}Jo, jo.
{7287}{7304}Snad...
{7471}{7496}Ale, je to překvapení...
{7497}{7509}Co?
{7510}{7536}Slyšel jsem od té hlupač...
{7537}{7639}...uch, mé sestry, že tvůj jediný|sen je být doktorkou, Ami-chan.
{7647}{7698}Ne, to je jen jeden|sen z mnoha...
{7699}{7750}Ale víš, žiji sama se svou matkou.
{7750}{7835}Snad proto mě to táhne směrem k větší|šťastné rodině, takové jako je Usagina...
{7903}{7981}Pokud někdy někdo úžasný objeví, pak možná budu|muset upřednostnit rodinu před prací.
{8182}{8233}Vypadá to, že ten hlučný přívažek tu není.
{8234}{8284}Ještě musím něco udělat s tou malou vší...
{8456}{8490}http://umino.gurio.sweb.cz
{8802}{8832}Tady!
{8875}{8904}Omlouvám se! Omlouvám!
{8956}{9001}No, snad se Tygřímu Oku daří.
{9001}{9057}Kdo ví?|Nezajímá mě, co se stane...
{9057}{9113}K čertu, mění se vítr...
{9181}{9197}Shingo...
{9197}{9232}Vypadá to, že nás to odneslo pěkně daleko!
{9358}{9393}Bude to v pořádku, pokud se|otočíme a začneme veslovat.
{9393}{9421}Určitě se dostaneme zpátky.
{9540}{9556}To je...
{9722}{9751}Halo... zas se potkáváme.
{9751}{9773}Vy jste...
{9773}{9814}Trenér delfínů?
{9815}{9856}Ne, to nejsem!
{9856}{9910}Skutečně se, za to co|se stalo, omlouvám...
{9911}{9946}Proč nás stále obtěžujete?
{9947}{9978}Vypadáte jako trochu neústupný mladík, víte!
{9978}{9999}Děti nemohou říkat něco takového!
{9999}{10016}Nejsem dítě!
{10017}{10062}Sklapni!|Nepleť se mi do cesty!
{10135}{10153}Šingo!
{10154}{10199}Teď jste konečně sama...
{10443}{10471}Šingo!
{10484}{10510}Šingo!
{10511}{10537}Ami-chan!
{10558}{10584}Co jste našli?|Nejsou tu někde kolem?
{10584}{10599}Ne...
{10600}{10628}Nikde je nevidím...
{10628}{10679}Sakra... kde ti dva mohou být?
{10680}{10733}Určitě bude v pořádku,|protože je s ním Ami-chan...
{10734}{10757}Usagi-sama!
{10847}{10863}To je...
{10863}{10906}To je člun na kterém byli Ami a Šingo!
{10907}{10929}Šingo...
{10929}{10968}No musíme se rozdělit a podívat se po nich!
{10969}{10982}Jo!
{11096}{11142}Šingo, jsi v pořádku?
{11142}{11157}Hej, Šingo-kun!
{11384}{11427}Počkejte! Co to děláte?
{11445}{11479}Není důležité co se|stane tomu děcku!
{11480}{11525}Proč jste šla pro něj tak daleko?
{11525}{11570}Je možné, že by to byl váš milenec?
{11583}{11626}Je to můj přítel.
{11633}{11657}Přítel?
{11657}{11704}Vy snad máte taky přátele, ne?
{11705}{11767}Nemůžu zahodit životy|lidí, které mám ráda!
{11788}{11813}Co je přítel?
{11813}{11872}Lidé pro které můžete být tak zoufalí?
{11884}{11898}čtyři...
{11923}{11983}Znám snad někoho, koho|bych mohl nazvat přítelem?
{12022}{12041}Šingo-kun!
{12063}{12082}Ami-chan?
{12091}{12106}Díky bohu...
{12107}{12123}Šingo-kun...
{12259}{12292}Tak na mě nezáleží?!
{12293}{12352}Nemusím mít přátele,|až chytím Pegase!
{12427}{12454}Jedna!
{12455}{12482}Dva!
{12490}{12511}Tři!
{12585}{12651}Teď se podívám na váš překrásný sen!
{12882}{12905}Šingo-kun!
{12979}{12996}K čertu!
{13031}{13047}Stůj!
{13048}{13063}Kdo je to?
{13063}{13121}Románky z horké letní pláže jsou|překrásné protože jsou tak křehké!
{13121}{13164}Když šmírujete takové|milence, cítím, že jste úchyl!
{13178}{13195}Co to melete?
{13205}{13224}Za lásku a spravedlnost...
{13224}{13253}...půvabné bojovnice v námořnickém!
{13309}{13341}Sailor Moon!
{13352}{13392}Sailor Chibi Moon!
{13401}{13431}Ve jménu Měsíce...
{13431}{13462}...ztrestáme vás!
{13463}{13493}Sa... Sailor Moon...
{13504}{13544}A my vám také neodpustíme!
{13554}{13617}Zas a znovu, pořád mě|obtěžujete v té nejlepší chvíli!
{13618}{13681}Ke mě, má Lemure...|křičící lidská pumpo, Ponko-chan!
{13921}{13941}Co to dělá?
{13979}{14022}Tak, rudá nebo bílá?
{14022}{14045}Rudá nebo bílá?
{14069}{14090}Bílá?
{14091}{14112}Špatně!
{14136}{14167}Rudá!|"Nezkoušejte to doma!"
{14168}{14210}Úžasné! Velmi pěkné!
{14211}{14227}Úžasný trik!
{14339}{14373}Tak, rudá nebo bílá?
{14373}{14403}Rudá nebo bílá?
{14403}{14433}Nestarám se o to!
{14433}{14489}Pokud nemáte odpověď,|mám tu super velký míč!
{14600}{14620}Sailor Moon!
{14639}{14692}Teď se konečně podívám na váš sen...
{14716}{14755}Nádhera! Nádhera! Je to nádhera!
{14755}{14773}Ami-chan!
{14789}{14814}Překrásné!
{14814}{14863}Ale Pegas tu zase není!
{14874}{14912}Nechávám ti to tu všechno, Ponko-chan!
{14938}{14972}Sakra, tohle je průšvih!
{15064}{15099}Tak a jsme blízko vyvrcholení!
{15118}{15186}Na závěr udeří míč ze stříbra...|Také známý jako stříbrný balón! Utište se!
{15228}{15255}Stříbrný balón, stříbrný balón...
{15348}{15405}Bomby nejsou na letní pláž vhodné,|na tu přehlídku krásek v plavkách!
{15406}{15478}Velké dávky střelného prachu patří do|úžasných ohňostrojů ozařujících noční nebe!
{15480}{15507}Tuxedo Kamen-sama!
{15507}{15532}Přišel jste nás zachránit!
{15533}{15605}Nezáleží jak daleko vzdálena|je má láska, překonám všechno...
{15616}{15639}K čertu!
{15640}{15724}Tak je použiji ultra super de luxe speciální|bombu za zlata, také známou jako...
{15757}{15804}Ne, ne! Nikdy jsem neměla říct takovou věc!
{15804}{15833}Nicméně, klid!
{15833}{15862}To je zas nějaký trik!
{15863}{15892}Ústa! Ucpěte jí ústa!
{15919}{15950}Proč si ucpáváš svou hubu?
{16070}{16102}Chibi Moon, Sailor Moon, teď!
{16125}{16182}Pegasi, prosím!|Ochraň sny všech!
{16240}{16284}Twinkle Yell!
{16588}{16637}Moon Gorgeous...
{16644}{16679}...Meditation!
{16880}{16934}Stage Out!
{17149}{17167}A... Ami-chan!
{17177}{17191}Šingo!
{17191}{17218}Sakra, nahlas nám strachu!
{17218}{17243}Hej, kde je?
{17243}{17268}To je v pořádku.
{17268}{17302}Sailor Moon ho porazila.
{17302}{17351}Nakonec jsem selhal v té roli ochránce...
{17351}{17391}Myslel jsem si, že mám větší ránu...
{17391}{17431}Pokud bys nebyl tak odvážný, Šingo...
{17431}{17470}...mohla Sailor Moon přijít pozdě.
{17470}{17499}Děkuji.
{17605}{17673}No jo, teď bychom měli být zavěšené|do nějakých nádherných chlapců...
{17673}{17716}Co se stane když to bude příští rok stejné?
{17716}{17749}Příště půjdu s Mamo-chan!
{17749}{17782}Já s ním půjdu příště!
{17782}{17815}Nemůže mi na něm pořád viset!
