{1}{1}15.000000
{28}{41}To je nádherné...
{42}{79}Poslední móda... vždyť, o tom je balet!
{80}{103}Podívej...
{103}{156}"Lekce zdarma pro začátečníky"
{156}{208}"Hledáme nové členy|k nastudování Gizely"
{209}{232}No... to znamená...
{232}{246}Jo!
{247}{280}Že konečně máme...
{291}{315}...šanci...
{315}{354}...začít!|"Jsem hvězda"
{375}{391}Jdem na to?
{391}{408}Jdeme!
{454}{522}Epizoda #145|"Směr na vrchol!|Usagin balet."
{540}{565}Ty chodíš do baletu?
{566}{599}Ty, Usagi-chan?
{600}{625}Budu tančit v Gizele!
{625}{666}Gizela... to je příběh kdy|Gizela zemře hned na začátku...
{667}{710}...ale je tolik zamilovaná,|že se změní na ducha...
{710}{754}...a pomáhá své lásce. Nakonec|je i po smrti prokletá...
{754}{790}...od ostatních duchů, že?
{791}{827}A ty tančíš rolu Gizely?
{827}{843}Ne, ne!
{843}{913}Ale je tam úžasný výstup v záři reflektorů.|Říkali, že jsem na to jedinečná!
{913}{928}A co ty Chibi Uso-chan?
{934}{984}Ne, říkali, že pro děti tam role není.
{984}{1012}To je pěkné, Usagi...
{1013}{1040}Ale... je to trochu divné.
{1041}{1087}Když si pomyslím, že Usagi vystupuje|v takovém romantickém příběhu...
{1088}{1114}Talent je talent.
{1114}{1144}Lovci talentů to musí vědět...
{1144}{1170}Lovci talentů našli...
{1171}{1192}...Usagi?
{1246}{1273}"Jamagišiho baletní skupina."
{1362}{1386}Usagi, rychle!
{1407}{1483}Potřebuji už jen obout své baletní střevíčky...
{1494}{1516}Nemožné...
{1527}{1546}To snad ne...
{1567}{1590}To je strašné!
{1591}{1646}Jen protože mám takový talent...
{1646}{1682}Nevím, proč ten kdo|žárlí dělá takové věci...
{1683}{1717}Ne, nesmím se vzdát!
{1718}{1767}Překonám tuhle|překážku a stanu se...
{1767}{1825}...nejlepší primadonou v Japonsku...|Ne na světě!
{1836}{1852}Usagi...
{1852}{1891}Napodobuješ náhodou poslední|noční epizodu z "Hvězdy Baletu"...
{1891}{1928}...a nedala sis ten napínáček|do střevíce sama?
{1955}{1979}Je to... takhle?
{1979}{2003}Nebo spíš takhle?
{2004}{2033}A když udělám tohle...
{2033}{2072}Usagi, máš spousty faldů...
{2072}{2093}Nežertuj!
{2093}{2121}Špatně! Co to děláte?
{2121}{2150}Omlouváme se!
{2150}{2178}To ne to, Kiriko.
{2179}{2221}Kolikrát vám to budu říkat?|Gizele je duch!
{2222}{2250}Nemůžete tančit tenhle part|a přidávat do toho tolik tělesnosti...
{2257}{2286}To by nevypadalo dobře.
{2296}{2323}Tu poslední část ještě jednou!
{2323}{2335}Ano.
{2336}{2348}No...
{2348}{2377}-Vypadá tak dobře a ještě...|-Un, deux, trois...
{2378}{2406}-Příprava je vždycky tvrdá, říkali.|-Lehčeji!
{2426}{2466}Vždycky jsem chtěl jednou zkusit trikot.
{2477}{2512}A teď, budu primadonou!
{2532}{2567}Teď začneme začátečnickou třídu.
{2567}{2621}Kiriko, zkusíme si poslední část|znovu později, počkejte vedle.
{2621}{2635}Ano.
{2635}{2666}Tak vy dvě, právě tam, přistupte.
{2667}{2691}Dobře!
{2699}{2740}Představím vám lidi,|kteří se přihlásili později.
{2740}{2761}Tak, přistupte.
{2762}{2775}Jistě!
{2784}{2798}Všechny!
{2798}{2812}Proč?
{2813}{2852}Nebylo by fér kdybys ty jediná|byla primadonou, Usagi!
{2853}{2888}Tak se k tobě připojíme.
{2888}{2929}Pro tělo je mírná|zátěž dobrá.
{2929}{2952}Ukážu to nejlepší!
{2952}{2982}To vypadá, že to bude fajn!
{2983}{3011}Primadona budu já!
{3026}{3068}Ó ano, ještě je tu jedna.
{3068}{3090}Ráda vás poznávám.
{3100}{3125}Ráda vás poznávám!
{3135}{3159}Ráda vás poznávám...
{3159}{3202}Tohle jsou tak divoce vypadající dívky...|Tolik mne unavují...
{3219}{3236}Tak začneme.
{3236}{3270}Uchopte zábradlí.
{3270}{3306}První pozice, plié...
{3306}{3341}Natáhnout a návrat.
{3341}{3368}Znovu plié.
{3388}{3427}Narovnejte záda.
{3427}{3443}Promiň.
{3444}{3502}Natáhněte nohu nahoru k mantlu a sklouzněte dolů.
{3514}{3530}Arasgon.
{3543}{3564}-Nekrčte kolena!|-Dobře!
{3564}{3590}Omlouvám se...
{3590}{3610}Ne, to je v pořádku...
{3796}{3814}Úžasné!
{3815}{3833}Nádherné!
{3843}{3868}Je dobrá...
{3869}{3893}Úžasná...
{3894}{3943}Ale tak nějak... chladná...
{3944}{3998}Jako by nebyla z tohoto světa...
{4082}{4104}Gizela...
{4104}{4125}Vy...
{4126}{4147}Ano?
{4148}{4194}Můžete tu po lekci chvíli zůstat?
{4194}{4216}To myslíte mě?
{4216}{4240}Ano.
{4240}{4262}Když se na vás dívám...
{4263}{4307}...cítím že jste velice|podobná Gizele.
{4338}{4381}Pokud mohu nějak pomoci,|pomohu ráda.
{4382}{4406}Oceňuji vaši|pomoc!
{4407}{4439}Počkejte, co to má znamenat?
{4440}{4478}Necháte ji tančit roli Gizele, že?
{4478}{4493}Hej!
{4494}{4543}Počkejte chvíli.|Poslouchejte co říkám...
{4543}{4560}Ne, nechci nic slyšet!
{4560}{4601}Už je toho dost!|Jsem na tom stejně jako Gizele!
{4602}{4643}Jsem zrazena k smrti,|zrazena tím komu věřím!
{4644}{4661}Kiriko!
{4692}{4715}Kiriko...
{4726}{4742}To zlé!
{4742}{4765}Primadonou budu já!
{4765}{4805}A Jakagišiho srdce získám také...
{4848}{4867}Pokračujeme...
{4895}{4910}Bože, jsem hotová!
{4910}{4942}Usagi, pokud si nepospíšíš,|necháme tě tady!
{4942}{4966}Proč bychom nepočkali v Koruně?
{4967}{4990}Ach, dobrý nápad!|Půjdeme napřed!
{4990}{5015}Počkejte chvíli!
{5015}{5056}Počkám na tebe, pospěš si!
{5056}{5073}Slyšela jsem...
{5073}{5106}Tak ona bude hrát Gizelu?
{5106}{5138}Ale pak, co bude s Kiriko?
{5139}{5153}Kdo ví?
{5153}{5213}Kiriki a Jamagiši-sensei|se vždycky dohadují...
{5229}{5260}Usagi, tudy! Tudy!
{5260}{5291}Pospěš! Jdeme!
{5316}{5333}Hele...
{5334}{5375}...je z kurzu, že?
{5439}{5488}Teď si myslím, že to možná ode|mne bylo trochu hloupé...
{5499}{5534}No myslím si, že to byl trochu|vztek, na to, že hlavní roli...
{5534}{5574}...odnesl pryč vrtoch mistra.
{5575}{5615}Ne i když se spolu stále přeme...
{5615}{5667}...přesto Jamagiši není|z těch, kdo mají vrtochy.
{5667}{5696}Hlavní důvod proč mi vzal hlavní roli...
{5697}{5733}...je to, že nejsem dost obratná...
{5733}{5773}Ještě z toho mít hysterii...|To bylo špatné.
{5782}{5795}Ale...
{5795}{5828}...jste úžasná Kiriko-san.
{5828}{5902}Nevím dost, ale když tančíte|je to takové teplé a milé...
{5902}{5933}Když vás vidím, cítím se šťastná...
{5934}{5964}To je tak úžasná věc.
{5964}{5988}Děkuji...
{5988}{6062}Jamagiši nemůže vidět nic|jiného když připravuje balet.
{6079}{6120}Jeho zaujetí baletem je skutečně úžasné.
{6121}{6169}Kiriki-san, vy máte ráda|Jamagišiho-sama, že?
{6201}{6247}Gizele zemřela a stala se|duchem, byla zrazena...
{6248}{6297}...svou láskou, ale stále se pokoušela|toho muže zachránit...
{6297}{6336}Opravdu ho milovala.
{6337}{6376}Chci být jako Gizela...
{6376}{6439}Chci mu pomoci, i když|neodpovídá na mou lásku.
{6440}{6457}Ale...
{6457}{6500}Tak musíte zkusit vydat|ze sebe to nejlepší.
{6500}{6523}Ty... myslíš tak?
{6523}{6564}Jo! Myslím, že dobrou odpověď získáte,|když vydáte ze sebe všechno!
{6564}{6617}Když tohle říkáš, Chibi|Uso, cítím se lépe.
{6617}{6656}To je pravda... když bych vydala to nejlepší i při učení...
{6656}{6690}Možná bys dosáhla lepších|výsledků v testech, Usagi!
{6693}{6708}Jo, jo...
{6708}{6747}A ty vždycky říkáš něco,|co není třeba!
{6773}{6785}Máte pravdu!
{6785}{6822}Vydám ze sebe to nejlepší|mnohokrát, nevzdám se!
{6823}{6860}Jsem si jistá že vy|to dokážete, Kiriko-san!
{6874}{6899}Děkuji...
{6933}{7005}Kiriko-san je tak zaujatá|Jamagašim-sensei a baletem...
{7005}{7054}...že nic nepochopí.
{7075}{7120}I když nepochopí|správnou právě teď...
{7120}{7165}...určitě jednoho dne pochopí.
{7174}{7209}Ty si to myslíš?
{7220}{7286}Něco takového je dost těžká výzva|pro lidi, kteří jdou zrovna dolů.
{7286}{7315}Ale důvod, proč skutečně|chápou toho druhého...
{7316}{7346}...je ten, že ví jak druhý myslí...
{7356}{7398}Dospělost je skutečně komplikovaná...
{7398}{7457}Jamagiši-sensei určitě|také myslí na Kiriko-san.
{7461}{7533}Jo! Doufám, že Kiriko-san|bude nakonec šťastná.
{7590}{7654}http://umino-gurio.sweb.cz
{8015}{8038}Myslím že teď to bylo výborné.
{8038}{8062}Děkuji za těžkou práci.
{8062}{8077}Jo...
{8086}{8116}Začínám z toho mít|skutečně dobrý pocit.
{8117}{8156}Snad bychom mohli přejít ke zkoušce na jevišti,|i když se mi zdá, že je to dost brzo.
{8156}{8170}Jistě!
{8170}{8206}No, děkuji vám za vaši těžkou práci.
{8327}{8382}Jamagiši-sensei, co|si myslíte o Kiriko-san?
{8382}{8397}No...
{8399}{8460}Omlouvám se, pokud cítíte vinu|za to co se ten den stalo.
{8460}{8496}Ach, nemusíte se na mě ohlížet...
{8496}{8532}Ale cítím trochu trapně za Kiriko-san.
{8533}{8607}Jamagiši-san, vy se skutečně|nedokážete vcítit do dívčích citů.
{8615}{8671}Dívky vždy chtějí, aby|byli středem pozornosti.
{8671}{8688}Chápete, že?
{8697}{8710}Vy...
{8719}{8802}Tak a dívá se jen na mě.|A ukáže mi...
{8802}{8828}...své sny.
{8828}{8868}Pojďte prosím...
{8917}{8940}Ach, helo...
{8940}{9016}Dobrý večer, zapomněla jsem si baletní střevíce...|Určitě jsme se nekoukali co...
{9017}{9060}To je pravda, jen jsme nahlíželi zpoza rohu.
{9061}{9082}Hlupačko!
{9102}{9146}No vypadá to, že nic... omlouvám se.
{9146}{9189}Sakra, takové vyrušení!
{9189}{9244}Tak můžete také domů.|Trochu se zdržím.
{9244}{9257}Ano!
{9258}{9274}Promiňte!
{9274}{9294}Ach, Tsukino-san...
{9295}{9312}Ano?
{9312}{9351}Můžete přijít zítra do divadla?
{9351}{9390}Můžete si zkusit svou roli!
{9390}{9405}Jistě!
{9405}{9420}V pořádku!
{9420}{9451}První krok k primabaleríně!
{9452}{9483}Už se nemůžu zítřka dočkat!
{9581}{9600}Tak jsem nakonec tady...
{9600}{9628}...ačkoli nebudu hrát Gizelu..
{9628}{9662}Chci mu nabídnout pomoc, nějakou pomoc...
{9662}{9688}...pro Jamagišiho Gizelu!
{9903}{9935}Děkuji. Skutečně oceňuji vaši pomoc.
{9935}{9979}Ale ne, ráda jsem vám pomohla.
{9987}{10045}Děkuji vám. Takhle bude|Kirikina Gizela mnohem úplnější.
{10045}{10081}Kirikina Gizela?
{10082}{10118}Nebudu hrát?
{10141}{10156}Ach, omlouvám se...
{10157}{10193}To byla chyba, když jsem vám to|na začátku pořádně nevysvětlil...
{10194}{10238}O začátku jsem věděl,|že Kiriko bude hrát Gizelu.
{10239}{10279}Žertuje!|Oklamal a využil jste mě!
{10279}{10314}Byla jsem přesvědčena,|že já budu Gizela!
{10314}{10340}-Jste tak krutý!|-Omlouvám se.
{10341}{10367}Mám pro vás jinou|důležitou roli...
{10368}{10381}Nechte toho!
{10381}{10427}Pokud nebudu primabalerína...|ve hlavní roli... tak mě to nezajímá!
{10427}{10472}Jsem mnohem lepší|tanečnice než ta dívka!
{10472}{10517}Myslím si, že technikou|jste lepší než ona.
{10517}{10594}Ale vím, že Kiriko bude lepší baletka|v úplnosti té role.
{10604}{10627}Určitě vím, že to Kiriko dokáže!
{10628}{10687}Opravdu... víc jak|perfektní duch Gizely...
{10688}{10769}...bude nedokonalá Gizela, která pokračuje v růstu|a má sílu okouzlit lidská srdce.
{10779}{10811}Rozhodně nepotřebuji|Gizelu se studeným srdcem!
{10812}{10830}O čem to mluvíte?
{10830}{10893}To je hloupost! Není pravdou to|co jako pravda vypadá?
{10894}{10925}Tohle není dost.
{10926}{10981}Nejste schopná se dotknou srdcí lidí!
{10988}{11039}Chci aby lidem z baletu|něco v srdcích zůstalo!
{11039}{11068}To je můj sen!
{11069}{11097}Jamagiši-sensei...
{11098}{11124}Kiriko...
{11124}{11141}Omlouvám se...
{11141}{11176}Nevěděla jsem, co cítíte...
{11177}{11211}Přemýšlel jsem celý ten čas...
{11211}{11252}...jak upravit balet tak,|aby vám ta role seděla.
{11252}{11279}Teď už vím jak.
{11280}{11307}Sensei!
{11484}{11499}Co je to!
{11499}{11528}Úplně mě ignorují!
{11528}{11554}Rozčílili mě!
{11604}{11639}Jak se odvažujete mě vynechat!
{11639}{11677}Ukážu vám, hlupáci!
{11677}{11698}Tady!
{11721}{11734}Kiriko!
{11735}{11754}Obtížná malá otravo, pryč z mé cesty!
{11754}{11774}Jedna!
{11793}{11824}Dva!
{11834}{11855}Tři!
{11998}{12038}Moon Crisis...
{12039}{12079}...Make Up!
{12557}{12596}A teď konečně...
{12670}{12700}Tak, Pegas tu není.
{12717}{12753}Omlouvám se, ale zemřete.
{12753}{12772}Stůj!
{12811}{12838}Zločinče pošlapávající srdce|hořící vášní k umění...
{12839}{12878}...a hasící plameny vášně!
{12878}{12917}Za lásku a spravedlnost!
{12917}{12945}Půvabné bojovnice v námořnickém!
{13002}{13033}Sailor Moon!
{13043}{13082}Sailor Chibi Moon!
{13093}{13119}Ve jménu Měsíce...
{13120}{13147}...ztrestáme vás!
{13147}{13177}Sakra, už jste tu zase?
{13178}{13213}Dneska mám skutečně špatnou náladu!
{13213}{13243}Ke mě má Lemure...
{13244}{13293}Louskáčku, Kurumiwario-kun!
{13294}{13343}Louskáček, Kurumiwario-kun!
{13353}{13386}Vypadá že jsme se dostali|do nějaké podivné role.
{13387}{13420}Jo. Nemohu hrát něco|tak složitého a navíc...
{13420}{13447}Hej! Nechte tlachání!
{13447}{13486}Kurumiwario, odcházím. Je to tu vaše!
{13486}{13497}Ano!
{13497}{13542}Jsem si jistý, že z nich udělám|perfektní primabaleríny.
{13543}{13573}No, snad jsem zvolil správně...
{13574}{13601}Tak, spoléhám na vás!
{13653}{13671}V pořádku!
{13671}{13692}Podmínka pro marnivou primabalerínu...
{13697}{13727}...je 90% potu a 10% talentu!
{13728}{13744}Co to?
{13757}{13796}Ukážu vám právě teď úžasné číslo!
{13797}{13820}Nohu dám takhle.
{13820}{13844}Chceš to udělat?
{13844}{13868}Ty to chceš dělat?
{13868}{13893}Malé dívky! Hej!|Zaplatíte pozornost a čekejte!
{13893}{13900}-Ano!|-Ano!
{13900}{13973}Speciální útok - Grand fette!|Un, touman!
{13983}{14018}8, 9, 10, 11...
{14044}{14073}Úžasné!
{14073}{14102}30, 31, 32!
{14123}{14148}Tak co, bojíte se mé síly?
{14148}{14167}Úžasné!
{14167}{14191}Jste velmi dobrý!
{14191}{14235}Tak, teď vy.
{14248}{14272}Tak teď spolu...
{14273}{14300}Společně?
{14300}{14324}Směrem k Hvězdě Baletu...
{14324}{14343}Hvězda Baletu?
{14353}{14387}Odporujete!
{14403}{14415}Budete poslouchat!
{14497}{14510}Co je to?
{14511}{14524}Pěkné!
{14525}{14546}Hele! Ty velká právě tam!
{14557}{14600}Jste tlustá!|Vždyť vám faldy přetékají!
{14600}{14621}Mlč!
{14622}{14646}Skutečně to vypadá těsné...
{14647}{14657}Hleď si svého!
{14657}{14700}Selžete jako primadona pokud|neudržujete svou postavu!
{14701}{14735}Zatočím s vámi kolem dvakrát, abych viděl všechno!
{14735}{14765}Začínáme!
{14766}{14795}Sailor Moon!
{14823}{14840}Otáčet! Otáčet!
{14864}{14894}Nech toho!
{14933}{14961}Mám závrať a zvedá se mi žaludek!
{14961}{14977}Zachráněny...
{14978}{15022}Nejste dost trénované,|pokud se vám točí hlava!
{15022}{15046}Co je to za trénink?
{15046}{15094}Pokud jste zapomněla, připomenu vám to...
{15108}{15128}Toho bylo dost!
{15129}{15178}Hlupáci! Snad si nemyslíte, že takhle|z vás budou zázračné primabaleríny?
{15178}{15210}Tak, čas na tohle!
{15210}{15242}Grand bateman!
{15289}{15308}Mozek?
{15308}{15343}Ne... ořech!
{15353}{15382}Hej, nespěte!
{15383}{15412}Já nespím!
{15413}{15433}Zvedejte nohy pěkně vysoko!
{15433}{15447}Začínáme!
{15493}{15520}Zvedněte svou čáru osudu pěkně vysoko!
{15588}{15625}Vidíte, nic se nestane,|když to zkusíte!
{15625}{15662}Už vás nic dalšího nenaučím!
{15676}{15686}Dobře!
{15687}{15713}Tak to je konec?
{15713}{15750}Zatančíte si v pekle!
{15810}{15877}Podezřelá panenko ztratíš se za oponou,|posedlý s večerem slunovratu.
{15877}{15911}Já Tuxedo Kamen neodpouštím!
{15911}{15932}Taxi do kamen?
{15932}{15960}Říkal jsem Tuxedo Kamen!
{15977}{16032}Pegasi, prosím!|Ochraň sny všech!
{16088}{16131}Twinkle Yell!
{16435}{16480}Moon Gorgeous...
{16492}{16527}...Meditation!
{16739}{16774}Stage Out!
{16968}{16992}Kiriko, je všechno v pořádku?
{16992}{17019}Jamagiši-sensei...
{17039}{17063}Taky všechno v pořádku...
{17063}{17078}Tuxedo Kameni-sama!
{17091}{17108}Sailor Moon...
{17109}{17122}Ano?
{17122}{17172}Nemyslíte, že by byla|vhodná menší dieta?
{17214}{17250}Ačkoli zachránit vás...
{17250}{17298}Pokud jste se díval,|proč jste nezasáhl dříve?
{17298}{17354}Vždycky počítáš s pomocí druhých.|Jsi skutečně hrdinka spravedlnosti?
{17355}{17375}Co to bylo?
{17375}{17411}Na prvním místě bys měla|vynechat všechny sladkostí!
{17411}{17439}-Nepřeji si to slyšet!|-Ne, zase...
{17598}{17635}Tohle je skutečně tak pěkný pár!
{17635}{17668}Ale kde je Usagi?
{17668}{17701}No nevím, nikde jsem|ji tom neviděla... že?
{17701}{17730}Co může mít za roli?
{17737}{17803}Vy víte... povím vám to,|když to na mě neprozradíte...
{17881}{17927}Tak tohle bylo to co on myslel|tou pravou rolí právě pro mě?
{17928}{17956}To je tak strašné!
