{142}{198}V den, ve kterém mi cesta vlakem zabrala 7 hodin, jsem pøijel...
{198}{237}...z pøedmìstí Hiroshimi do Tokia
{252}{320}a do zaèátku školního roku mi zbıvalo nìkolik dní...
{552}{645}...jsem potkal dívku se kterou jsem mìl zaèít chodit na støední školu...
{815}{865}...byla prostì úasná...
{885}{970}...a krásnìjší ne kdokoliv, koho jsem do té doby vidìl.
{3610}{3665}Yamato má zpodìní...
{3690}{3740}Miho, takhle se nachladíš.
{3748}{3775}Poèkej na nìho uvnitø.
{3783}{3862}Ale on øíkal, e pøijde ve dvì!
{3870}{3995}Neøíkala tetièka proè je proti jeho pøíchodu do školy tady v Tokyu?
{4000}{4029}Nedìlej si starosti.
{4038}{4110}Sestøièka øíkala, e pokud bude bydlet s námi, souhlasí s tím.
{4130}{4165}Pravdìpodobnì je u blízko.
{4180}{4240}On je opravdu nezodpovìdnı, nemám pravdu Gorou?
{4265}{4335}Omlouvám se, za zpodìní.
{4370}{4431}Akitsuki Yamato, hlásí svùj pøíchod.
{4484}{4525}Jdeš pozdì Yamato.
{4530}{4570}Naše princezna se zlobí. 
{4580}{4592}Ano.
{4626}{4690}Jdeš pozdì Yamato!
{4697}{4732}Ty jsi ale vyrostala Miho.
{4745}{4783}Teï jsi v sedmé tøídì, viï?
{4790}{4805}Osmé!
{4818}{4880}To øíkáš naschvál aby jsi mì naštval bratránku.
{4899}{4945}Vím to, vím to, opravdu to vím.
{4990}{5070}Wow, tohle místo bylo, ale pìknì pøestavìno.
{5095}{5120}Nemùeš to tady poznat, viï?
{5135}{5203}Dokonce láznì byli pøedìlány na lázeòskı komplex, to je teïka populární.
{5225}{5270}Od teï je to mùj novı domov, eh?
{5300}{5343}Mùj novı ivot zaèíná právì tady.
{5408}{5479}Dobrá tedy, tetièko Ayano, prosím veïte mì.
{5485}{5531}Oh, jak to?
{5540}{5587}Protoe jste správce.
{5595}{5658}Chovej se jako doma, jsme pøece pøíbuzní.
{5665}{5723}Ah, tvoje zavazadla jsou u ve tvém pokoji.
{5745}{5780}Bratránku, jsi unavenı, viï?
{5783}{5810}Necháme tì aby jsi si odpoèinul.
{5815}{5835}Pojï honem.
{5855}{5985}OÈEKÁVÁNÍ.
{6062}{6102}Budeš bydlet v pokoji 301, pøímo nad námi.
{6108}{6180}Aèkoliv je zde chlapcùm vstup zakázán...
{6190}{6245}Nesmíš dìlat problémy, brácho.
{6265}{6300}Co tím myslíš, jaké problémy?
{6312}{6362}To je v poøádku Yamato.
{6373}{6462}Pro nìkoho jako jsi ty je lepší, kdy tu nebude mít ádné další pomocníky.
{6490}{6524}Vy nemáte ádnou dùvìru v mue...
{6538}{6580}Kdy budu moc nìco udìlat, udìlám to.
{6585}{6650}Take nemusím platit nájemné a ještì dostanu za práci zaplaceno,
{6668}{6707}take kdy budu tøeba èistit láznì, budu to dìlat jak nejlépe umím.
{6720}{6783}Èištìní lázní je velmi tìké.
{6787}{6823}Neøíkej dvakrát?
{6845}{6867}To je hraèka.
{6874}{6917}Mám dùvìru ve vlastní sílu.
{7147}{7190}Vypadá to, e jsem to trochu podcenil...
{7196}{7232}Jsem z toho unavenı.
{7250}{7325}Ale mají tu i víøivky a vlastní saunu.
{7350}{7467}Nevypadá to staøe, navíc sem chodí urèitì i dìvèata.
{7498}{7535}A ona by jsem mohla také pøijít...
{7544}{7583}Ah! Ještì jsi nezaèal s láznìmi!
{7602}{7652}Neøíkal jsi e èistìní lázní je snadná vìc?
{7666}{7706}Jestli jsi to øekl, tak to dìlej poøadnì, Ok?!
{7719}{7795}Oh! Skonèím bìhem sekundy!
{7824}{7845}Trochu tady...
{7895}{7930}Nepospícháš moc...
{8030}{8040}Nìkdo jde!
{8060}{8072}Klienti?
{8090}{8135}Tady je enská ubytovna.
{8150}{8220}Musíš bıt opatrnı, protoe oni jsou OPRAVDU nebezpeèné.
{8230}{8253}Nebezpeèné, jak?
{8295}{8350}Láznì u jsou zavøené?
{8364}{8405}Eh, opravdu?
{8460}{8530}Ty jsi Yamato? Ten, o kterém povídala správkynì?
{8545}{8585}Eh? Yamato je tady?
{8590}{8623}Oh ne, a já mám na sobì jenom ruèník?!
{8630}{8710}Hmm, vypadáš sladce, no né?
{8735}{8762}NÉÉÉÉÉ!
{8810}{8850}Brácho, pospìš si odtud!
{8990}{9020}O-Oml...
{9135}{9180}Ah, ne, to...
{9235}{9265}N-ne!
{9335}{9370}To je nedorozumìní!
{9400}{9450}Ze všech chvil, kdy mohla pøijít, pøijde v momentì kdy...
{9455}{9505}Myslel jsem si, e by bylo dobré kdyby pøišla...
{9540}{9580}Musí mì nenávidìt.
{9925}{9942}Bratránku?
{9947}{9966}Co se stalo?
{9978}{10000}Ten kluk náhle...
{10040}{10117}Ne, já jí takhle našel ve svém pokoji...
{10122}{10175}Bratránku, podívej se poøádnì na štítky!
{10205}{10277}To je pokoj Asahiny Suzuky
{10310}{10346}Yamato, tvùj pokoj je támhle.
{10520}{10580}Právì jsem pøišel a spletl si pokoj...
{10610}{10660}Ty jsi tak neopatrnı.
{10675}{10730}Právì jsme ti øíkali, e nemáš dìlat problémy!
{10818}{10860}Omlouvám se Asahino.
{10874}{10921}Dìlej, omluv se Yamato.
{10930}{10970}O-Omlouvám se...
{10990}{11015}To bylo pøekvapení.
{11027}{11070}Nikdy jsem nemyslel, e by mohla bıt moje sousedka.
{11190}{11250}Ayano tvoje jídlo je nejlepší!
{11287}{11340}Jestli by jsme tì nechali samotného, nevím co by jsi jedl.
{11365}{11390}To bolí.
{11395}{11418}Já nejsem pes nebo jiné zvíøe.
{11425}{11450}Nejsi moc jinı.
{11457}{11495}Chodíš si do cizích pokojù.
{11515}{11547}Já jsem nevešel!
{11575}{11667}Omlouvám se za starosti s mojí veèeøí.
{11674}{11730}Nedìlej si starosti Asahino, to je v poøádku.
{11755}{11810}Co je to za rùzné postoje?
{11824}{11850}Samozøejmì!
{11855}{11950}Na rozdíl od tebe brácho je Suzuka talentovaná.
{12055}{12095}Asahina je vıjimeèná!
{12106}{12180}Aèkoliv jste oba novımi studenty støední školy Aoba,
{12180}{12258}ty jsi byl pøijat jako jeden z posledních na seznamu,
{12262}{12315}ona byla vybrána do sportovního drustvo.
{12330}{12380}Vybrána. To je ohromnı.
{12390}{12450}Tak proto trénovala skákání.
{12476}{12545}Dokonce by mohla reprezentovat Japonsko na olympiádì.
{12565}{12665}Pak mùu bıt pyšná, protoe mùu øíct "e tady bydlela"
{12671}{12707}Ano, udìlám co budu moct.
{12772}{12795}Umìl bych jí taky skvìle popsat?
{12800}{12840}Ona je dokonalá.
{12855}{12895}Jsme opravdu stejnì staøí?
{12898}{12940}Chceš ještì pøidat, Asahino?
{12943}{12982}Oh ne, dojedla jsem.
{12990}{13040}Jíš nìjak málo, Asahino.
{13045}{13060}Ještì, prosím!
{13085}{13120}Bratránku, ty mùeš ještì jíst!
{13140}{13170}To proto, e jsem ve vıvinu.
{13180}{13235}Ale, je ohromné e jsi byla vybrána.
{13250}{13317}Na støední škole jsem byl v baseballovém tımu,
{13330}{13397}Moje odpaly nebo hra v poli nebyla moc dobrá.
{13406}{13460}Tak jsem øekl všem, e pokud bìhem hry neodpálím...
{13465}{13512}tak koupím kadému pití.
{13540}{13590}A kdy jsem to udìlal, tak jsem odpálil.
{13595}{13630}Moná mam ještì šanci.
{13645}{13670}To jsi celı ty, brácho.
{13695}{13725}Vdy tak svéhlavı...
{13767}{13817}Co bys udìlal kdyby jsi se netrefil?
{13837}{13890}Dobøe, nemyslel jsem to vánì.
{13900}{13928}Mohl bych se omluvit.
{13937}{14005}Nemám ráda takové nezodpovìdné chování.
{14050}{14070}Dìkuji za veèeøi
{14220}{14255}To mìl bıt vtip.
{14260}{14298}Nebere to nìjak vánì.
{14730}{14745}Stalo se nìco?
{14990}{15050}Nemyslíte si o mém bratru Yamatovy to nejhorší?
{15075}{15140}Vím, e bratr je nemotornı a nezodpovìdnı,
{15145}{15175}ale má také dobrou stránku.
{15185}{15245}Je milı a velmi dobøe dìla okonomyaki.
{15270}{15350}Takovı je od chvíle, co naletìl na Saotomin ert,
{15355}{15397}a co potom odešel.
{15420}{15465}Není to všechno bratrova vina.
{15485}{15510}Pøišla jsi abys mi tohle øekla?
{15567}{15600}Dìláš si o bratra starosti, viï?
{15625}{15670}On je typem èlovìka, kterého nemùete nechat samotného.
{15680}{15710}Myslíte si, e se tomu øíká mateøskı instinkt?
{15800}{15817}Myslím.
{15830}{15850}Díky bohu!
{15915}{15985}Ten kluk je váš bratr?
{16000}{16040}Uh, on je nìkdo jinı...
{16055}{16100}Ach, rozumím, nìkdo koho si váíte.
{16145}{16185}Vypadá trochu jako bratr.
{16225}{16245}Ah, nezlobte se.
{16280}{16350}Dobøe, nezlobte se prosím pøíliš na bratránka.
{16610}{16650}Nejsou si vùbec podobní!
{16745}{16785}Co je to s Asahinou?
{16805}{16835}Udìlal jsem nìco špatného?
{16860}{16930}Dobøe, udìlal, ale...
{16930}{16975}ale nemusela pouít takovı tón.
{17075}{17110}e by... Asahina?
{17175}{17227}Pøišla se omluvit, protoe byla pøíliš hrubá?
{17285}{17340}Dobrej veèír Yamato!
{17345}{17395}Tohle bys nemìla dìlat Saotome!
{17440}{17465}Coe?
{17480}{17515}Pobavíme se!
{17515}{17550}Poèkej. Jsi opilá?
{17550}{17570}Ne, nejsem opilá!
{17578}{17613}Sakra, je z tebe cítit alkohol!
{17617}{17635}Kam jdeš!
{17678}{17765}Saotome! Pøestaò dìlat blbosti!
{17771}{17867}O èem to mluvíš? Nedìlám ádné blbosti!
{17870}{17925}Tenhle pokoj vypadá strašnì!
{18132}{18157}Napij se, Yamato!
{18163}{18200}Prosím pøestaò!
{18204}{18250}Omlouvám se, Yamato.
{18260}{18290}Já jí hned odvedu.
{18295}{18325}S tím poèítám.
{18335}{18435}Megumi, ty...
{18440}{18485}Nemám vùbec ponìtí, co øíkáš!
{18500}{18540}Proto, se víc napij!
{18625}{18650}Jsi v poøádku?
{18657}{18700}Hmmm, moc toho nezùstalo...
{18710}{18750}Ty! Ty jsi ještì nepil, viï?
{18772}{18805}Ta osoba je nepøíèetná...
{19046}{19085}Prosím udìlej na škole to nejlepší!
{19105}{19150}Budeme ti fandit!
{19161}{19230}Pøekvapila jsi svého uèitele.
{19235}{19290}Skoèíš 169 cm?
{19300}{19345}Jsi nejlepší v Kanagawì?
{19350}{19395}Øeditel byl velmi potìšen!
{19410}{19445}Jsi pıcha naší školy!
{19555}{19615}Jen jeden skok a jsem v oèích celé školy
{19620}{19650}a mnoho lidí se na mì ptá.
{19680}{19720}A kadı ode mì èeká velkı vısledek.
{19745}{19845}Potøebuji skoèit ještì vıš, ne...
{19920}{19955}Posloucháš mì Yamato?
{19955}{20010}Jo, jo, poslouchám, poslouchám.
{20025}{20070}Všichni chlapy na které narazím jsou stejní.
{20078}{20135}Zajímají se jen o "prsa, prsa, prsa, prsa"
{20145}{20225}Jmenuji se Matsumoto Megumi, ne prsa!
{20240}{20295}Ohromnı, obtìuje mì opilá.
{20315}{20340}Poslouchej mì, zatracenì!!
{20345}{20360}Ano, sleèno!
{20390}{20480}Vsadím se, e zíráš na má prsa, e jo?
{20495}{20527}T-To je...
{20545}{20590}Jen se klidnì podívej.
{20625}{20650}P-Poèkej Megumi!
{20655}{20685}Na co se k èertu díváš?
{20745}{20798}Potøebuji shodit víc...
{21050}{21100}Sláva, koneènì usnuli.
{21110}{21140}Co s nimi teï budu dìlat?
{21180}{21215}Sakra, to u je pùlnoc!
{21220}{21245}Musím uklidit láznì!
{21285}{21345}Asahina musela všechen ten køik slyšet.
{21360}{21410}Ale koho to zajímá, stejnì mì nenávidí.
{21533}{21595}Sakra, svítilo se tady celou tu dobu.
{21647}{21697}Ayané se urèitì zas naštve.
{21710}{21745}Ahh, v saunì navíc taky.
{21996}{22030}Hej, jsi v poøádku?
{22105}{22140}Jak to, e nejdou otevøít?
{22265}{22295}V tom pøípadì...
{22295}{22340}se omlouvám...
{22390}{22415}Omlouvám se, Ayano!
{22495}{22535}Asahina, probuï se!
{22663}{22693}Nedìlej si starosti.
{22697}{22737}Má jen symptomy dehydratace,
{22737}{22765}musí se jí obnovit hladina vody v tìle,
{22765}{22810}pak jí klesne teplota a bude zase v poøádku.
{22810}{22830}Aha.
{22867}{22905}Byla jsem vystrašená.
{22915}{22995}Kdy jsi køièel, e je Asahina mrtvá.
{23005}{23065}Jene, ona neodpovídala ani kdy jsem køièel.
{23070}{23115}Navíc jsem zpanikaøil.
{23130}{23210}Já zpanikaøila také potom, co jsem slyšela o vyraenıch dveøích u sauny!
{23215}{23285}Nešli otevøít ani kdy jsem na nì tlaèil.
{23295}{23355}Kdyby jsi zatáhl z druhé strany, otevøeli by se.
{23382}{23410}Byl jsem zaskoèenı...
{23415}{23455}a myslel jsem jen na to, jak jí zachránit.
{23510}{23590}Dobøe, teï u mì nepotøebuješ.
{23645}{23681}Pùjdu vyèistit láznì.
{23700}{23760}A se vzbudí, tak ji dej napít vody.
{23840}{23875}Omlouvám se Asahino.
{23890}{23945}Kdybych šel uklidit v èas...
{23955}{23990}tak by se to nestalo.
{24025}{24050}Byla jsi vzhùru celou tu dobu?
{24057}{24095}Vzbudil jsi mì, protoe jsi hluènı.
{24110}{24143}Nemusel jsi rozbíjet ty dveøe.
{24160}{24188}Jsi blbec.
{24260}{24295}Sama jsi blbá!
{24310}{24355}Kvùli komu myslíš, e jsem je rozbil?
{24362}{24392}Co si k èertu myslíš,
{24400}{24440}zùstat v saunì tak dlouho dokud neomdlíš...
{24450}{24495}Neøíkej, e jsi tam byla jen 12 minut.
{24505}{24545}Èetla jsi zatracenì varování!
{24550}{24580}Èetla!
{24587}{24620}Pak jsi asi vymaštìná!
{24635}{24665}Lidi jako ty mám rád...
{24668}{24725}OMLOUVÁM SE!! JA TO VÍM!!
{24735}{24745}Ano?
{24775}{24870}Myslela jsem, e skoèím vıš kdy trochu shodím.
{24915}{24986}Moji kolegové, starší kolegové, škola, moji rodièe...
{25000}{25095}všichni mi øíkají, e kdy budu tvrdì trénovat, skoèím vıš...
{25115}{25185}Není snadné skoèit 169 cm...
{25200}{25260}Sama jsem byla zaskoèená tím rekordem.
{25275}{25340}Ale všichni hodnotí mé schopnosti vıše ne jsou.
{25355}{25407}Laka je vyš a vyš...
{25415}{25442}To je pak...
{25447}{25470}strašné.
{25616}{25629}Já..
{25645}{25695}nevím nic o atletice...
{25705}{25765}...ani o skoku do vıšky...
{25845}{25925}Ale kdy jsi to skoèila jednou, mùeš to skoèit znova!
{25960}{25995}Ty jsi opravdu lehkomyslnı.
{26000}{26090}A co je nejdùleitìjší, ignoruj lidi kteøí ti to øíkají!
{26105}{26185}Skáèeš, protoe to máš ráda, e jo?
{26200}{26245}To je pravda, ale...
{26255}{26300}Tak si to víc uívej...
{26300}{26385}a nedìlej takové oblièeje.
{26393}{26430}Nedìlám takové oblièeje!
{26445}{26480}Hej, vypadáš u v poøádku.
{26489}{26550}Take jdu pomoc Ayané.
{26565}{26580}Poèkej!
{26606}{26695}Neøekneš nikomu, e jsem breèela, viï?
{26700}{26725}No já nevím.
{26730}{26770}Ty jsi o mì øíkala taky rùzné vìci.
{26775}{26790}Poèkej!
{26795}{26845}Slib mi, e to neøekneš!
{26870}{26890}Dobøe, dobøe.
{26900}{26940}A podal by jsi mi sklenici vody.
{26947}{26962}Ano, ano.
{26973}{26987}Vymìò mi obklad.
{26995}{27027}Hej, nechceš toho trochu moc!
{27080}{27115}A to jsem si myslel, e to je "tvrdá" holka,
{27130}{27190}ale ona má také své problémy.
{27222}{27297}Vypadá to, e si teï s Asahinou víc rozumím.
{27356}{27402}Jsem ještì ospalı, Asahino.
{27415}{27475}Proè s tebou musím na ranní trénink?
{27515}{27570}Yamato, øíkal jsi, e to mùu skoèit, viï?
{27584}{27660}Pak by jsi mìl dodret své slovo a podívat se jestli to skoèím nebo ne.
{27675}{27730}Neøekl jsem, e to neudìlám...
{27760}{27793}Co to dìláš?!
{27798}{27810}Kruci...
{27830}{27885}Promiò, jaká tam byla vıška?
{27892}{27955}První skok je na 164 cm.
{28050}{28100}Je to naklonìné.
{28104}{28140}Pøestaò dìlat nesmysly!
{28155}{28186}Sakra, ta je ale háklivá.
{28260}{28320}Tak, mùeš skákat.
{28336}{28370}Vypadá to vıš, ne jsem myslel.
{28497}{28522}Nepodceòuj mì!
{28630}{28680}Tuhle vıšku... skoèím v pohodì...
{28726}{28745}pokadé!
{28900}{28928}Vypadá fakt dobøe.
{29056}{29105}Hej, dotkla jsi se laky.
{29108}{29130}Sotva jsi to pøeskoèila.
{29136}{29150}To není moné...
{29175}{29217}Doteï jsem to skákala snadno.
{29240}{29280}Dobøe, ale byli, umm...
{29285}{29310}i jiné dny ne tento.
{29312}{29322}Správnì?
{29335}{29390}Nikdy jsem nemìla den jako tento!
{29405}{29430}Ro-rozumím...
{29455}{29490}Moná jsi ještì unavená ze vèerejška.
{29499}{29510}To je dobrı.
{29518}{29560}Pøestaò mì utìšovat, to je zbyteèné.
{29575}{29590}Co mám dìlat?
{29605}{29685}Zapomeneme na 169cm, nemùu skoèit ani 164cm.
{29695}{29745}Tímto tempem, budu...
{29865}{29915}Po-poèkej, kam jsi dal tu laku?
{29925}{29975}Kam? Na 164 cm samozøejmì.
{29985}{30060}Ne! Vrchní èást laky má bít na 164 cm.
{30066}{30078}Ty blbeèku!
{30102}{30150}Jak jsem to mìl vìdìt?
{30157}{30190}Ty jsi opravdu neschopnı!
{30197}{30224}Jak to chceš omluvit?
{30305}{30336}To je všechno kvùli tobì Yamato...
{30410}{30470}...e jsem zlomila svùj vlastní osobní rekord bez jakékoliv radosti...
{30898}{30938}Dnešní skok je neoficiální,
{30945}{31045}ale øadí se mezi 12 nejlepších skokù na støedních školách.
{31080}{31150}Ale dùleitìjší bylo, e Asahina...
{31162}{31220}na rozdíl od tvrdého postoje, kterı obvykle má,
{31270}{31370}mìla na oblièeji úsmìv, sladší ne jakı jsem kdy vidìl.
