{2830}{2858}Dobré ráno!
{2870}{2886}Dobré ráno.
{2913}{2956}Máš rozèepıøenı vlasy,
{3095}{3116}jako obvykle.
{3143}{3175}Co?
{3196}{3223}To se mi prostì obèas stane.
{3357}{3374}Co s ní zas je?
{3442}{3579}JARNÍ BOUØKA
{3665}{3733}Nebuïte líní! Tímto zpùsobem mùe kadı posílit!
{3910}{3991}Moná vezmu tento test trochu vánì | P.E. - nìco jako osobní vıkonnost.
{4025}{4050}Co se s tebou dìje?
{4055}{4106}Nevyhıbáš se obvykle takovımhle vìcem?
{4135}{4191}Obvykle jsem v takovıch to situacích nervózní.
{4210}{4300}Kromì toho, na niší støední jsem byl v tìchto testech nejlepší,
{4313}{4352}a na jednu vıjimku.
{4398}{4426}A co byla ta jedna vıjimka?
{4437}{4473}To je jedno.
{4515}{4570}Pojïme nejdøíve skákat do dálky.
{4575}{4595}Vypadá to, e je tam volno.
{4611}{4664}Pojïme skákat do vıšky.
{4677}{4711}Tam je taky volno.
{4890}{4915}Je mi to jasnı...
{4959}{5011}Hej, takhle to není.
{5108}{5175}Suzuko, ty jsi ve dvojici se Sakuraiou?
{5182}{5231}Co kdyby jsme se mi dva k vám pøipojili?
{5249}{5277}Mì je to jedno.
{5305}{5328}Mì to taky nevadí.
{5340}{5357}Slyšel jsi co øíkali.
{5362}{5397}To jsou dobré zprávy, e jo Yamato?
{5410}{5458}Já... nìjak nevím.
{5602}{5645}No tak se nám uka,
{5655}{5698}nejlepší atlete z niší støední.
{5725}{5754}Nejlepší atlet z niší støední?
{5767}{5848}Pravdìpodobnì byl doma velkım hrdinou.
{5879}{5891}e jo?
{5904}{5952}H-hrdina je trochu moc.
{6040}{6105}Pøestaò se podceòovat a radši se nám pøedveï.
{6125}{6148}Mùeme tu nabrat pár bodíkù.
{6271}{6308}Tak, dobøe...
{6351}{6381}Zapíšu ti tvùj pokus.
{6435}{6505}Yamato byl opravdu nejlepší na niší støední?
{6515}{6594}Yeah, øekl mi, e a na jednu vıjimku prı ano.
{6605}{6630}Na jednu vıjimku?
{6639}{6689}Hmm? Nechtìl mi øíct jakou.
{6727}{6796}Fajn, uvidíme co nám pøedvede.
{7119}{7133}Skvìlı!
{7144}{7171}To je mùj novı rekord!
{7184}{7200}Co si o tom myslíte?
{7205}{7223}není to skvìlı?
{7350}{7441}Oèekávala jsem o nìco víc, kdy jsi øíkal, e jsi byl nejlepší na niší støední.
{7468}{7487}C-Co?
{7762}{7827}Wow! Suzuka skoèila 84cm.
{7851}{7895}Osm-osmdesát ètyøi?
{7920}{7990}Od nìkoho kdo skáèe do vıšky se to dalo oèekávat.
{8106}{8150}Skvìlı, taky mám 84cm.
{8170}{8227}Jsi dobrı, Hattori!
{8233}{8280}To nebylo špatnı.
{8599}{8653}Zatracenì, jsi dobrá Suzuko.
{8655}{8697}Taky jsi dobrı Hattori.
{8707}{8733}Jsi plnı pøekvapení.
{8754}{8797}Nechtìl by jsi vstoupit do nìjakého klubu.
{8820}{8836}Kdepak, kdepak.
{8848}{8886}Nemùu to udìlat.
{8896}{8959}Tahle škola je plná talentù.
{8971}{9011}Hmm, jaká škoda.
{9052}{9082}Na druhou stranu...
{9121}{9160}Pojï, Akitsuki.
{9160}{9185}Usmìj se.
{9220}{9340}Myslela jsem, e bude lepší kdy pøišel na sportovní školu,
{9345}{9368}ale on v nièem nevyniká.
{9375}{9471}Tøeba, na niší støední | by to byl velkı rekord.
{9494}{9570}Akitsuki, zbıvá ještì poslední disciplína.
{9580}{9620}Ah, no jo, no jo.
{9641}{9681}Ještì zbıvá bìh na 50m, viï?
{9695}{9721}Jsem bez šance.
{9743}{9795}Neznamená to, e jsi špatnı...
{9846}{9907}Na základní škole jsem byl nejlepší.
{9920}{9961}Potom bìhem léta v sedmé tøídì,
{9975}{10065}jsem se zúèastnil mìstského závodu.
{10083}{10149}Naše škola nemìla sprinterskı štafetovı team,
{10164}{10214}tak mì vzali aby mohli na závody.
{10229}{10259}A jak to dopadlo?
{10289}{10340}Byl jsem hroznej,
{10357}{10396}skonèili jsme úplnì poslední a všichni se mi smáli.
{10421}{10478}Od té doby jsem nikdy sprint nebìel.
{10488}{10564}A do teï jsem se pokadé vymluvil abych nemusel bìet.
{10636}{10673}Asi se vymluvím i teï.
{10691}{10721}T-to nemùeš pøece udìlat!
{10725}{10750}Pojï, aspoò to zkus.
{10970}{11011}Já u to nemùu vidìt.
{11020}{11046}Jen, pojï.
{11057}{11111}Mùe se stát nìco neoèekávaného.
{11120}{11165}Co tím chceš øíct,
{11181}{11224}vdy pobìí proti Kobayakawaovy.
{11240}{11310}Ten kluk je tady kvùli tomu, e dobøe bìhá, viï?
{11330}{11356}Pak je to ještì víc zajímavìjší.
{11381}{11418}V poøádku, na znaèky!
{11679}{11731}Yamato zkusí rychlı start?
{11750}{11850}Asi zkusí pouít obì nohy k odrazu aby mohl rychleji bìet.
{11862}{11883}To je imbecil.
{11919}{11990}Mìl bych bìet rychleji, pokud se odrazím obìma nohama.
{12173}{12233}Jsi nejlepší, Akitsuki!
{12339}{12366}V tom pøípadì...
{12451}{12468}Pøipravte se!
{12492}{12524}do toho  dám všechno!
{12683}{12708}T-to není moné.
{13583}{13617}To je dobrı?
{13641}{13673}Zatracenì dobrı!
{13686}{13727}Ty jsi bìhal na niší støední?
{13773}{13802}Jsi v nìjakém klubu?
{13819}{13847}Pøejdi na bìhání.
{13847}{13896}Ne! Ty nohy jsou stvoøené pro baseball!
{13912}{13953}Tak co? Není tohle zajímavé?
{13967}{14011}H-Hattori tys to vìdìl celou dobu?
{14020}{14100}Jo, kdy jsme byli ještì dìti, tak jsem si z nìj dìlával legraci,
{14105}{14151}on byl vdy takhle rychlí.
{14175}{14236}Ale ten závod na niší støední...
{14255}{14315}To bylo asi kvùli tomu, e s ním bìeli další tøi.
{14340}{14398}Vypadá to, e byl náhradníkem v baseballovém teamu na niší støední,
{14409}{14444}ale kdy potøebuje tak se umí ukázat.
{14510}{14557}Øíkají, e jsem dobrej.
{14570}{14638}Wow! Akitsuki-kun,ty máš ale rychlé nohy!
{14673}{14690}Snad.
{14716}{14746}Co myslíš, Asahino?
{14761}{14808}Myslím, e dìlají chybu.
{14843}{14871}Jdeme Sakuraio.
{14884}{14923}Také potøebujeme bìet.
{14944}{14959}Po-poèkej.
{15047}{15065}Co to...
{15086}{15120}To byla divná odpovìï.
{15131}{15177}No, jsi dobrej, jsi dobrej.
{15187}{15238}Pár bodù za to dostaneš.
{15254}{15326}K-kvùli tomu jsem nebìel.
{16170}{16182}Co je?
{16252}{16294}Mám nìco na tváøi nebo co?
{16318}{16353}N-nic.
{16370}{16482}Slyšela jsem brácho, e jsi vyhrál nad nìkım kdo se dostal na školu jako sprinter.
{16500}{16530}To je skvìlé.
{16538}{16558}Jsem z toho pøekvapená.
{16567}{16600}Opravdu?
{16608}{16657}Ano. Slyšela jsem to od Hattoriho.
{16672}{16765}Pravda je, e já sám jsem z toho nejvíc pøekvapenı.
{16785}{16815}Na konci se ke mnì všichni sebìhli....
{16823}{16844}To bylo nìco.
{16854}{16923}Hej, opravdu byl bratránek tak rychlí?
{16942}{16999}No... tak normálnì.
{17013}{17051}O èem to mluvíš, Asahino?
{17063}{17081}Mohla by jsi...
{17081}{17105}Dìkuji za jídlo.
{17282}{17307}Co to bylo?
{17615}{17628}Dobré ráno.
{17646}{17659}Dobrı ráno.
{17739}{17787}Podívej, dneska je perfektní den, viï?
{17835}{17856}Hmm, snad.
{18152}{18188}To je divnı.
{18298}{18322}Dobré ráno, Suzuko.
{18358}{18384}Dobré ráno.
{18395}{18440}Slyšela jsem, e má odpoledne pršet.
{18450}{18490}Vzala jsi si deštník.
{18593}{18614}"Naschle".
{18821}{18839}On je opravdu...
{19050}{19100}Suzuka se chová divnì?
{19112}{19178}Jo, jako by na mì furt zírala.
{19200}{19236}Ráno byla taková chladná.
{19265}{19330}Asi jsem udìlal nìco za co se na mì zlobí?
{19330}{19348}Imbecile.
{19360}{19426}Je jasnı, e kdy se tak dívka chová, tak je zamilovaná.
{19464}{19480}O èem to mluvíš?
{19500}{19606}Koukal jsi nìkdy na nìkoho kdo se ti líbil, e jo?
{19633}{19680}N-no, já....
{19697}{19814}Jinımi slovy, pro takovıho lossera jako ty je tìké tìmhle pocitùm rozumìt.
{19847}{19945}Prı jsi dostal hodnì bodù ze vèerejšího P.E. testu.
{19960}{20036}Dokonce i já sám jsem pøekvapenı jak jsi bìel rychle.
{20200}{20296}Opravdu myslíš, e se jí líbím kvùli takové malièkosti?
{20341}{20382}Láská se objeví znenadání.
{20395}{20428}Take, hodnì štìstí.
{20541}{20580}Znenadání, eh?
{20770}{20867}Faktoriál X^3 a Y^3...
{20890}{20933}Rozumíte tomu? Je to dùleité.
{20933}{20955}Dávejte pozor.
{21053}{21110}...oèividnì zamilovaná dívka...
{21308}{21331}To je vtip.
{21373}{21427}Asahina... mì miluje?
{21586}{21606}Uvidíme se!
{21749}{21825}Ahh... v tomhle nemùu jít domù.
{21830}{21858}Co mám dìlat?
{22044}{22106}Ahh, jestli pak mì nìkdo nechá podìlit o svùj...
{22212}{22256}Protoe dneska prší jdeme trénovat...
{22270}{22298}do posilovny.
{22318}{22327}Rozumím.
{22341}{22368}Fajn, budeme tedy posilovat.
{22436}{22456}Zapomnìl jsem.
{22476}{22512}e je zaneprázdnìná trénováním.
{22605}{22639}Nevzal jsi si deštník, viï?
{22651}{22712}Jestli chceš, tak se s tebou podìlím o svùj.
{22773}{22824}Jestli pøijdeš domù mokrı, mohl by jsi znova onemocnìt.
{22875}{22925}Ještì nìco mám.
{22942}{22950}A co?
{22969}{22997}Mùu poèkat.
{23005}{23126}Není to nic dùleitého, |mùe to poèkat do zítøka, ale...
{23150}{23185}Ah, Sakuraio jsi úasná jako vdy.
{23185}{23210}Vzala jsi si deštník.
{23245}{23294}Jsem zachránìnı, jsem zachránìnı..
{23310}{23370}Øeknu vám pravdu, byl jsem se vèera dlouho bavit
{23380}{23410}a zapomnìl jsem si deštník.
{23430}{23510}Necháš mì se schovat, ne dojdeme k zastávce.
{23515}{23552}Byl bych za hlupáka kdybych zmoknul.
{23552}{23564}Prosím.
{23581}{23608}Ah, ale...
{23613}{23634}Tak fajn, Yamato.
{23634}{23677}Necháš mì s ní jít.
{23693}{23707}C-co...
{24210}{24265}Co to pro všechno na svìtì dìlám...
{24491}{24558}Jak dlouho bude ještì posilovat?
{24590}{24620}To chce vypadat ještì líp nebo co?
{24680}{24750}Nemusí to dìlat, u tak je dost pìkná.
{24788}{24826}K èertu na co to myslím?!
{24855}{24892}Je mi to jedno! Jdu domu!
{24910}{24941}Kdo by na ní chtìl èekat!
{25150}{25197}Bude pøirozenìjší, kdy poèkám tady..
{25212}{25257}Ok, trochu potrénuju.
{25301}{25377}A-Asahina! Zapomnìl jsem deštník.
{25385}{25410}Mohla by jsi se podìlit o svùj?
{25434}{25462}Jestli nechceš, tak nevadí.
{25546}{25588}Eh, co je to s ním?
{25588}{25625}Moná je to nìjakı chlívák!
{25625}{25647}To je to nejhorší!
{25647}{25688}To je hnusné!
{25670}{25699}Asi bude lepší, kdy pùjdu domù.
{25887}{25934}Ne, ještì chvíli poèkám.
{26100}{26145}Myslela jsem, e u jsi šel domù
{26175}{26244}No, nemohl jsem otevøít box na boty.
{26259}{26277}Teï je, ale otevøenı, není to tak?
{26297}{26338}No, vlastnì jsem ho teï otevøel.
{26347}{26366}Díky bohu!
{26426}{26471}Yamato, ty nemáš deštník, viï?
{26487}{26514}Jestli chceš, mùu se podìlit o svùj?
{26532}{26569}Zapomnìl jsem svùj deštník.
{26583}{26613}Mohla by jsi se podìlit se mnou o svùj?
{26623}{26667}jestli nechceš, tak nevadí.
{26740}{26752}Vánì?
{27997}{28035}Ten vítr je nìjakı silnı, viï?
{28205}{28266}Neøíká se tomuhle jarní bouøka?
{28494}{28515}Co se dìje?
{28520}{28578}Tváøí se hùø ne obvykle.
{28607}{28664}Nemyslím si, e je to tak jak øíkal Yasunobu.
{28840}{28889}...bìel jsi opravdu rychle...
{28923}{28943}Asi.
{28960}{29075}Prı jsi dostal hodnì bodu z vèerejšího P.E. testu.
{29103}{29130}Neøíkej mi, e...
{29222}{29275}B-byl jsem skvìlı, viï?

