{2818}{2870}Dìkuji za jídlo, Ayané.
{2890}{2907}Bylo to dobré.
{2920}{2936}Díky za poklonu.
{2960}{3004}Nádobí tam mùeš nechat.
{3067}{3114}Odcházím na ranní trénink.
{3129}{3155}Další ranní trénink?
{3169}{3217}Tvùj team má nìjak na pilno.
{3248}{3300}Zítra je toti školní slavnost,
{3310}{3342}tak máme den volno.
{3352}{3390}Jsi nejlepší Suzuko!
{3400}{3432}Yea, díky.
{3487}{3507}Den volno, eh?
{3561}{3600}Je pátek ráno, 7:30
{3605}{3639}a horoskopy pro dnešek...
{3692}{3828}VYZNÁNÍ
{3918}{3984}To je pro ní vzácnost, dostat den volna...
{4001}{4080}Chtìl bych s ní nìkam jít,
{4103}{4146}ale na nákupech jsme byli zrovna vèera.
{4230}{4277}A v karaoke klubu asi zpívat chtít nebude...
{4325}{4404}A navíc, kdo by chtìl trávit den volna v karaoke klubu?
{4429}{4467}Moná kino nebo zábavní park...
{4500}{4529}To jsou spíš místa na rande.
{4620}{4719}Ale moje úmysly by jí byli zøejmé, kdybych se jí zeptal jestli by se mnou nìkam nešla.
{4802}{4858}Je tìké se jí zeptat...
{4911}{4932}e by Ayané?
{4977}{5052}Dobrı den! Jsem z Maisa Shinbun!
{5065}{5103}Nechtìl by jste si pøedplatit naše noviny?
{5115}{5161}Jestli-e si pøeplatíte naše noviny teï,
{5165}{5222}dostanete dvì volné vstupenky do Fantasy Landu!
{5330}{5396}Tohle jsou poslední dva lístky, zítra konèí platnost!
{5412}{5440}Take, jak se rozhodnete?
{5450}{5480}To je ono!
{5492}{5524}Dobøe, beru to!
{5535}{5569}Pøedplatím si to,kdy dostanu ty vstupenky!
{5573}{5592}Plácneme si?
{5600}{5628}Dìkuji vám!
{5635}{5689}Noviny zaènete dostávat od dnešního veèera!
{5696}{5723}Dobøe, pošlete je.
{5840}{5879}Díky, "novináøko"!
{5891}{5938}Díky, to mi pomùe!
{6079}{6126}Dostal jsem to od èlovìka od novin,
{6138}{6173}nechceš jít?
{6185}{6224}Byla by škoda je zahodit.
{6240}{6279}Fajn. To zní normálnì.
{6287}{6317}To zní skuteènì normálnì.
{6333}{6370}Co je to s ním?
{6502}{6543}Teï u se jen musím zeptat Asahiny.
{6550}{6587}Mùu to øíct klidnì a normálnì.
{6605}{6615}Skvìlı!
{6924}{6948}Nemùu to øíct...
{6965}{7015}...byla by chyba zeptat se jí ve škole.
{7224}{7263}Okay, pùjdu se jí zeptat.
{7285}{7355}Zeptám se jí ne pùjdeme na veèeøi.
{7641}{7694}Ayané øíká, e veèeøe je hotová.
{7815}{7845}Zase ti není dobøe?
{7879}{7926}Ne, tak to není.
{8102}{8138}Trénoval jsem si to,
{8145}{8188}ale nemùu to øíct.
{8264}{8286}Pospìš si, okay?
{8359}{8389}Jsem zbabìlec!
{8615}{8689}Zatracenì, bylo by blbı, zeptat se jí na to pøed všemi...
{8700}{8743}Asi budu muset jít a k ní do pokoje.
{8753}{8792}Ah, tady jsi, tady jsi!
{8844}{8918}Nemìla by jsi tolik pít Saotome.
{8925}{9019}Èekala jsem na tebe, Ya-ma-to.
{9046}{9060}Co tady ta...
{9064}{9097}zatracená enská dìlá...
{9204}{9220}Co je to?
{9256}{9318}Volné vstupenky do Fantasy Landu?
{9325}{9350}Hej, koukej mi to vrátit!
{9355}{9360}Pozdì!
{9375}{9478}Jeliko jsou dvì, tak se chystáš zeptat Suzuky viï?
{9485}{9525}Samozøejmì, e ne!
{9535}{9550}Opravdu?
{9555}{9587}Pak by jsi teda mohl jít se mnou?
{9635}{9695}Není to klika, zítra mám volno.
{9700}{9748}Jestli chceš budu ti dìlat spoleènost.
{9755}{9786}Kdo øíkal, e chci jít s tebou?!
{9799}{9815}Vra mi je!
{9853}{9880}Megumi chytej!
{9925}{9959}Zatracenì, vrate mi je!
{10086}{10102}Sakra!
{10117}{10166}To je dìs!
{10173}{10205}Co jsi tak nervní?
{10210}{10252}Jen mi je vra!
{10273}{10332}To je moje poslední šance.
{10347}{10382}CO je to s tebou?
{10386}{10408}Jseš protivnej.
{10426}{10471}Saotome, tak mu je u vra.
{10483}{10525}Vypadá to, e jsou pro nìho dùleité.
{10533}{10564}Myslím, e...
{10568}{10624}Yamato, budeš muset chvíli poèkat, leda e by...
{10952}{10999}Oh, ta koèka je roztrhala...
{11086}{11137}Co to dìláš Gorou?!
{11166}{11212}Moje poslední nadìje...
{11260}{11295}Jak my to chceš zaplatit?
{11302}{11354}Co? To není moje vina.
{11374}{11424}Radìji mi bì  koupit senbei!
{11433}{11451}To jako já!
{11462}{11525}Mám tu toti na tebe jeden inkriminující film.
{11535}{11598}Tady tì mám Yamato, jak obtìuješ studentku!"
{11610}{11622}Víš co to znamená?!
{11666}{11706}Zatracenì! Všechno je v háji.
{11735}{11770}Nic u nemám.
{11805}{11871}Kdybych tušil co se stane, zeptal bych se Asahiny pøed veèeøí.
{11909}{11960}Další vstupenky u neseenu.
{12068}{12103}Potøebuji jít do sklepa,
{12125}{12185}ale neprojdu kdy tady budeš takhle sedìt, viï?
{12280}{12318}Teï u je pozdì..
{12384}{12445}Vidìla jsem ve tvojí schránce noviny.
{12455}{12485}Ty je máš pøedplacené?
{12543}{12583}Nìjaká ena mi zaklepala na dveøe.
{12595}{12628}Tak jsem si je na mìsíc pøedplatil.
{12635}{12670}U mì byla také,
{12675}{12694}ale odmítla jsem.
{12700}{12774}Nicménì jsem dostala vstupenky do Fantasy Landu.
{12805}{12827}Dostala?
{12835}{12886}Yeah, dala mi dvì vstupenky jako reklamní dárek.
{12910}{12932}Ta potvora!
{12935}{12969}Mìla jich víc, no jasnì?
{12981}{13025}Fajn, i kdy jsou zadarmo,
{13035}{13112}bylo by nehospodárné je vyhodit.
{13177}{13198}Stalo se nìco?
{13210}{13243}Ne, já...
{13267}{13300}Teï jí to mohu v klidu øíct.
{13321}{13343}V klidu...
{13381}{13458}"Chtìla by jsi jít se mnou?" Zní to jako vtip.
{13470}{13484}Øekni to!
{13488}{13517}Tak u to koneènì øekni.
{13525}{13555}Tohle je opravdu moje poslední šance.
{13641}{13730}Um... Mùu jít s tebou jestli chceš.
{13765}{13842}Sakra, zní to jako bych o to prosil.
{13876}{13926}Sakra, asi se naštve.
{13949}{14029}No, ummm... omlouvám se.
{14038}{14075}Ty jsi jak dìcko.
{14092}{14103}Co?
{14136}{14191}Jestli chceš jít, øekni mi to rovnou.
{14230}{14245}Ale...
{14268}{14336}Nevadí mi to, mùu s tebou klidnì jít.
{14392}{14452}Ostatnì nedìlám nic jiného, ne e trénuji,
{14456}{14486}take trochu zábavy mi neuškodí.
{14510}{14550}Co? Ty nechceš?
{14565}{14586}Eh, ne...
{14598}{14626}Pùjdu!
{14635}{14660}Pokud teda chceš jít!
{14707}{14745}Tak tedy v osm ráno.
{14759}{14806}Budu naštvaná jestli zaspíš.
{14901}{14929}Dokázal jsem to.
{14941}{14963}Dokázal jsem to!
{15031}{15052}Skvìlı!
{15642}{15666}Do háje...
{15680}{15717}Proè musí pršet zrovna dnes?
{15894}{15920}Horší to snad bıt nemùe.
{15925}{15965}Do veèera se to asi nezlepší.
{15983}{16025}To bude dobrı.
{16040}{16093}Budeme prostì chodit po krytıch atrakcích
{16005}{16131}Jen tak?
{16145}{16205}Bude lepší kdy si udìláme nìjakı plán.
{16215}{16230}A na co?
{16235}{16311}Prostì pùjdeme tøeba tamhle.
{16395}{16443}Bez plánu, prostì pùjdeme...
{16469}{16506}Yamato ty jsi opravdu...
{16520}{16535}Co?
{16540}{16557}Nic!
{16826}{16878}A to jsem si myslel, e se budeme dobøe bavit...
{16893}{16916}Je to dìs...
{16941}{16997}Další prosím!
{17094}{17113}Co zase dìláš!
{17125}{17161}Po tomhle jdu domù.
{17200}{17253}Kdybych vìdìl co se stane, tak bych sem vùbec nešel.
{17342}{17400}Vypadá to, e všechny tyhle atrakce jsou nudné...
{17605}{17661}Co je tohle za atrakci?!
{17741}{17789}Podívej, tamhle dole je mìsto!
{17831}{17845}Tamhle dole!
{17850}{17880}Vidíš to mìsto?
{17921}{17956}Mìsto, mìsto!
{18055}{18119}Vypadá to, e jsem ty atrakce nìjak podcenil.
{18141}{18181}Tohle je strašnı,
{18185}{18223}zábavnı park...
{18260}{18329}Ale byla to sranda.
{18398}{18431}Asi se ještì zlobí.
{18452}{18497}Patrnì se vydáme na cestu domù.
{18541}{18564}Podívej se na tohle!
{18588}{18630}Ty se, ale tváøíš sladce Yamato.
{18635}{18677}Hej, za to já nemùu!
{18681}{18709}bylo to strašnı!
{18727}{18795}Zatracenì, kdy to udìlali?
{18839}{18917}Fajn, pojïme na další atrakci.
{18949}{18980}Ale øíkala jsi, e pùjdeme domù.
{18990}{19005}Pospìš si!
{19015}{19051}Èas je drahı!
{19099}{19180}Tak tedy pojïme obejít všechny kryté atrakce!
{19190}{19241}Myslíš, e to všechno stihneme?
{19526}{19628}Nakonec jsme stihli jen polovinu atrakcí.
{19635}{19684}Máš hodnì energie...
{19703}{19760}Nemyslím si, e tohle místo je dobré.
{19768}{19807}Je to tady jako ve mìstì!
{19850}{19881}Jak zaráející.
{19886}{19910}Málo cvièíš!
{19915}{19936}Jsi beznadìjnı pøípad.
{19950}{19983}Pojïme na nákupy a pak domù.
{19987}{20030}Zábavnı prùvod kvùli dešti asi nebude.
{20066}{20106}Mohl bych si ještì chvíli odpoèinout?
{20113}{20130}Ne.
{20140}{20170}Potøebuji se na to podívat a nìco vybrat
{20175}{20199}a to zabere hodnì èasu.
{20210}{20241}Oh, vánì?
{20255}{20319}Nakupováním zabije hodnì èasu.
{20335}{20425}Ostatnì do zábavného parku se zase dlouho nedostaneš viï?
{20468}{20489}Máš s tím nìjakı problém?
{20503}{20552}Ne, ádnı.
{20560}{20597}Tak dìlej, stávej u!
{20605}{20635}Ano, madam!
{20650}{20748}Vdy kdy jdeme ven tak skonèíme takto.
{20839}{20878}Tady, to je dobrı.
{20891}{20931}Ne, to není dobré.
{20957}{20990}Vdycky mì táhne sebou,
{21005}{21063}a pak mì donutí nést všechny vìci...
{21102}{21144}To vypadá úplnì jako Gorou!
{21156}{21192}To jé pìkné!
{21205}{21318}Vztah, kterı jsme do teï mìli, vypadá jako kamarádství mezi pøáteli.
{21564}{21588}Podívej, Yamato!
{21595}{21620}Pøestalo pršet!
{21643}{21665}Máš pravdu.
{21715}{21766}Teï u je pozdì...
{21831}{21841}Jdeme!
{21850}{21891}Moná bude zábavnı prùvod!
{22542}{22565}To je nádherné!
{22615}{22663}Stále jí drím za ruku...
{22760}{22850}Èím víc s ní jsem, tím víc ji miluji.
{22919}{22993}Moná by bylo nejlepší kdyby náš vztah zùstal takovı jakı je teï.
{23020}{23103}Jestli se jí vyznám, tak náš vztah znièím.
{23134}{23186}Budu šastnı pokud to tak zùstane na vdy.
{23420}{23474}Budu šastnı pokud to tak zùstane na vdy.
{23579}{23594}Já...
{23636}{23669}tì miluji Asahino.
{23927}{23955}Co to povídáš?
{23965}{24024}Myslíš, e mì zaskoèíš takovım ertem?
{24053}{24076}Ty jsi naivní.
{24090}{24125}Ne, já...
{24135}{24191}To není dobrı, co povídám.
{24229}{24263}Jestli se zastavím bude to vypadat jako ert.
{24302}{24357}A budeme moci zùstat pøáteli jakımi jsme do teï byli.
{24386}{24410}To nebyl ert!
{24420}{24457}Miluji tì od chvíle co jsem tì potkal!
{24490}{24526}Od chvíle kdy jsem tì poprvé uvidìl!
{24538}{24558}Hned od zaèátku!
{24629}{24661}Prosím, buï mojí dívkou.
{24678}{24750}T-to je moc náhle.
{24779}{24835}Známe se tak velmi krátkou dobu.
{24840}{24883}To pøece nevadí!
{25012}{25070}Myslíš... to vánì?
{25809}{25825}Promiò.
{25909}{25955}Rozumím.
{25965}{25999}T-to je v poøádku.
{26005}{26053}Chtìl jsem ti to jen øíct.
{26089}{26109}Omlouvám se.
{26300}{26340}Vrátíme se.
{26350}{26377}Prùvod u skonèil.
{26413}{26457}Vezmu si tašku.
{26490}{26525}To je v poøádku, není tìká.
{26535}{26594}Radši si jí vezmu...
{26615}{26644}Rozumím...
{27125}{27159}Dobrou.
{27376}{27415}Dobrou, eh?
{27444}{27472}Vítám tì.
{27476}{27507}Nabídl jsem si chippsy.
{27580}{27610}Dveøe nebyli zamèené?
{27660}{27720}Pøedplatil jsi si noviny?
{27790}{27850}Chtìl jsi se podívat na to, kdy dávají v TV sportovní pøenosy?
{27855}{27881}Je to škvár.
{27890}{27909}Dr hubu.
{28000}{28085}Dnes jsem byl s Asahinou v zábavnım parku.
{28120}{28155}Ptala se mì, jestli bych s ní šel,
{28165}{28209}myslíš, e to øekla?
{28238}{28256}Nevím.
{28270}{28327}"Jestli chceš, tak s tebou pùjdu".
{28365}{28395}Není tak upøímná, viï?
{28399}{28440}Vlastnì jít nechtìla.
{28465}{28564}Kdy jsme tam pøišli, zaèala si stìovat na déš a e atrakce budou zavøené atd...
{28575}{28620}Nebyla to moje vina, e pršelo.
{28710}{28820}Pak øekla, e po svezení na horské dráze pùjde domù.
{28830}{28885}Bylo to jako kdy jsem sem pøišel.
{28895}{28966}Ale myslel jsem si, no dobøe..."
{29020}{29077}Pak najednou øekla, pojïme na další atrakci.
{29090}{29144}Vùbec jsem jí nerozumìl.
{29210}{29260}Pak mì táhla po všech èertech
{29266}{29303}a ukecala mì táhnout její nákupy...
{29315}{29366}Potom pøestalo pršet a chtìla se jít podívat na zábavnı prùvod.
{29392}{29452}Co je tak dobrého na prùvodu?
{29471}{29510}Je to jen mrhání elektøinou.
{29534}{29556}Je to blbost!
{29621}{29661}Líbilo se jí to!
{29788}{29858}No, radši pùjdu.
{29950}{29992}Dostal jsem je na zastávce.
{30048}{30065}Vezmi si je.
{30107}{30124}Tak pozdìji.
{30138}{30169}Zamkni za mnou dveøe.
{30447}{30505}Hmph, nepotøebuju to.
{30684}{30728}Nepotøebuju to, ty magore!
{30885}{30922}Bojuj s tím.
{31035}{31086}Ne, je to horská dráha!
{31311}{31329}Nejde to!
{31382}{31435}Proè pláèu?
{31505}{31553}Dy je to trapnı...
