{2777}{2816}Take s ní chodíš...
{2825}{2884}... ale zatím ti Sakurai nedala?
{2891}{2921}Tak to není.
{2936}{2978}My na tyhle vìci nespìcháme.
{2996}{3063}Tak na to pùjdete hned jak budete moct. 
{3077}{3095}Dobøe?
{3101}{3164}Holky berou tyhle vìci dost vánì.
{3173}{3215}Navozením odpovídající atmosféry...
{3215}{3265}To staèí, øíkal jsem, e se o tom nechci bavit.
{3277}{3303}Jen poslouchej!
{3303}{3326}Dr u hubu!
{3335}{3383}Prostì na to jdeme pomalu.
{3404}{3455}Koukám, e se dobøe bavíte.
{3481}{3505}Mohu si pøisednout?
{3514}{3541}Tak o èem se bavíte?
{3550}{3598}Jo jasnì, tak jí to øekni, woe.
{3604}{3636}Co mi má øíct?
{3646}{3715}Tenhle loser je zoufalej, protoe mu Sakurai ještì nedala.
{3720}{3750}Co? Dr hubu, idiote!
{3801}{3873}Radím mu jak vytvoøit správnou atmosféru...
{3882}{3937}... aby na to mohl vlítnout.
{4088}{4129}Úchyle, úchyle
{4102}{4136}Au, pøestan, sakra!
{4140}{4171}Co ty seš za kreténa?
{4170}{4200}Jsi nadrenej jak nìjakej starej dìdek!
{4161}{4200}Au, to bolí!
{4211}{4312}Ty seš tady jedinej loser, ty sexuální chlíváku.
{4332}{4390}Tak hele, u všech holek krom tebe to zabírá.
{4409}{4439}Jdeme, Akitsuki!
{4445}{4472}Nebo se od toho imbecila nakazíš.
{4475}{4520}Ještì jsme neskonèily, Yamato.
{4535}{4574}Boe... nechte mì bejt.
{4605}{4743}PØÍTEL
{4936}{4981}Dobøe, pro dnešek to staèí.
{5093}{5135}Dobrá práce, Akitsuki.
{5147}{5198}Páni, jak dokáeš zvednout nìco tak tìkého?
{5204}{5258}To nic není, není to tak tìké.
{5264}{5306}Vypadá to, e je to pro tebe lehké
{5368}{5410}K èertu, u je tady zase.
{5446}{5539}Jako sprinter potøebuješ víc zesílit.
{5551}{5599}Take, si dej ještì tøi série.
{5619}{5641}M-Moment.
{5668}{5692}Øíkal jsi nìco?
{5710}{5768}Udìlám to, udìlám, jen mì prosím puste.
{5768}{5795}Ovšem, kdy si to pøeješ.
{5821}{5866}A teï se do toho pus.
{5896}{5920}To se mi snad zdá.
{5929}{5962}Umm... Akitsuki.
{5969}{6041}Na dnešek mám u nìco domluveného, take...
{6050}{6083}Och, to je v poøádku.
{6095}{6137}Nedìlej si starosti a klidnì bì.
{6177}{6216}Ale venku prší.
{6225}{6283}A ty sis urèitì nevzal sebou deštník, viï Akitsuki?
{6287}{6312}To nic, to nic.
{6322}{6350}Ten déš je stejnì slabı.
{6359}{6413}A v nejhorším pøípadì mùu jít s Miho.
{6425}{6438}Opravdu?
{6495}{6545}Pojïme u domù, Suzuko.
{6551}{6590}Ech, ovšem.
{6734}{6755}Hele, Suzuko...
{6768}{6798}... nezastavíme se cestou v cukrárnì?
{6810}{6903}Mont Blanc i kaštanové koláèe by mìli tentokrát mít.
{6912}{6930}Nechceš to jít ochutnat?
{6939}{6969}Ani ne.
{7007}{7100}Ach, teï jsem si vzpomìla. Nechala jsem ve tøídì telefon.
{7104}{7146}Promiò, musím se pro nìj vrátit.
{7152}{7203}Ach, jestli chceš, tak bì napøed, Miki.
{7230}{7260}Kdepak, poèkám na tebe.
{7272}{7326}Kdy jím sama, tak si to tak nevychutnám.
{7333}{7408}Neøíkala jsem ti snad, e nemám chu?
{7412}{7478}Koho to zajímá, jednou za rok se snad mùem trochu nadlábnout.
{7611}{7653}Dobrá, u jenom dvì série.
{7660}{7700}Nepolevuj v koncentraci!
{7704}{7722}Jo, jo.
{7755}{7779}To se mi snad zdá.
{7794}{7815}Boe.
{7815}{7908}To snad není monı, chceš mi øíct, es ho mìla celou tu dobu v tašce?
{7912}{7933}Promiò.
{7939}{7999}Myslela jsem, e jsem se do ní dívala.
{8008}{8057}Prober se u, Suzuko.
{8063}{8108}Take, teï kdy jsi ho našla...
{8114}{8141}... mùeme u jít.
{8185}{8233}Musím ještì odevzdat jeden referát.
{8242}{8275}Úplnì jsem na to zapomnìla
{8281}{8305}Referát?
{8312}{8371}Jo, musím ho tu napsat ještì ne pùjdu domù.
{8398}{8440}Vykašli se na to.
{8440}{8490}To nejde, tøídní by se zlobil.
{8496}{8526}Tak jo, tak jo.
{8551}{8593}Pùjdu teda domù sama.
{8593}{8641}Uá, koneènì konec.
{8767}{8820}Vy jste ještì tady?
{8826}{8847}Co tady dìláte?
{8856}{8874}Èekáme.
{8880}{8889}Co?
{8952}{8988}Déš nìjak zesílil.
{9035}{9077}Ach jo, budu muset zavolat Miho.
{9106}{9145}Hele... Yamato.
{9206}{9218}No...
{9265}{9277}Co?
{9349}{9364}Vlastnì...
{9387}{9444}Jestli chceš, pùjèím ti svùj deštník?
{9466}{9532}Ech, ale... co potom ty, Asahino?
{9560}{9590}To je v poøádku.
{9590}{9670}Stejnì jsme chtìli jít s Miki spoleènì, zmáèkneme se obì pod jeden.
{9697}{9709}Rozumím.
{9835}{9887}Dobøe, potom si ho teda pujèím.
{9956}{9971}Zatím.
{10241}{10284}Hele, Suzuko.
{10313}{10394}Ty máš... Akitsukiho opravdu ráda, viï?
{10462}{10502}Proè myslíš?
{10521}{10533}No...
{10542}{10620}... od té doby, co jste se s Akitsukim spoleènì vrátili, se chováš divnì.
{10632}{10728}A teï jsi podlì mì na nìho èekala abys s ním šla spoleènì domù.
{10750}{10780}Tak to není.
{10834}{10861}Já, vánì...
{10912}{10973}... nechci mít s Yamatem nic spoleèného.
{11060}{11075}Rozumím.
{11084}{11114}Fajn, myslím...
{11123}{11144}Jdeme, Miki.
{11147}{11210}Zrovna jsem dostala chu na nìco dobrého.
{11271}{11367}Dobøe, dneska sem se k tobì chovala hroznì, take mùeš sníst co chceš, zvu tì.
{11376}{11391}Miki.
{11420}{11432}Dobøe?
{11469}{11487}Dìkuju.
{11712}{11751}Fajn, pro dnešek to staèí.
{11760}{11789}Dejte si voraz, a bìte domù.
{11795}{11831}Jasnı.
{11991}{12049}Nechceš pøinést nìco k pití, Akitsuki?
{12073}{12097}Ach, ano.
{12106}{12163}Ještì, e se tu dneska neukázal, urèitì by mì zas šikanoval.
{12260}{12322}T-Ti dva si jsou nìjak moc èasto spolu.
{12331}{12385}Jasnì, protoe spolu chodí.
{12409}{12447}Co, ty jsi to nevìdìl?
{12471}{12486}To snad ne.
{12600}{12630}Och, vánì?
{12630}{12661}Taky sem byl pøekvapenı.
{12671}{12725}Hele, hele, pojï, pojï, Suzuko.
{12731}{12770}Ach... ano...
{12779}{12827}Ach, jdeme na karaoke.
{12836}{12890}Moná budou mít i novou písnièku od Nany.
{12896}{12914}A to je kdo?
{12920}{12944}To myslíš vánì?
{12950}{12983}Dy je to akutálné Popstar èíslo jedna!
{12996}{13017}To sem netušila.
{13140}{13185}Já se z toho Kinagusy zblázním.
{13191}{13239}Co proti mì vùbec má?
{13248}{13289}Asi si od tebe hodnì slibuje.
{13299}{13326}Moná...
{13353}{13413}Poslechnìte si novı song od Nany v nejlepší kvalitì.
{13499}{13524}Vypadá dobøe.
{13622}{13679}Tobì se líbí Nana Shirakawa, Akitsuki?
{13709}{13820}N-Ne, já mìl namysli ten pøehrávaè.
{13842}{13857}Opravdu?
{13874}{13898}Vánì, vánì.
{13910}{13943}Ale je moc drahı.
{13955}{13976}Takhle sem to nemyslel.
{13991}{14003}Rozumím.
{14155}{14179}Vítejte.
{14312}{14333}Vítejte.
{14375}{14405}Dìje se nìco, Honoko?
{14440}{14488}Vypadáš rozrušenì.
{14504}{14537}A-Abych pravdu øekla...
{14549}{14643}... jedna moje pøítelkynì, by tì ráda poznala, Akitsuki.
{14656}{14689}M-Mì?
{14717}{14768}Poslala jsem jí sms, e dnes konèím døív...
{14780}{14810}... a ona mi odpovìdìla, e se tu zastaví.
{14819}{14834}Rozumím.
{14840}{14873}Tak proto jsi tak nervózní.
{14885}{14900}Promiò.
{14912}{15002}Urèitì ti to musí vadit, Akitsuki.
{15008}{15065}Ne, to je v poøádku...
{15074}{15122}... ale nevadí, e jsem takhle obleèenej?
{15131}{15149}Ach, tady jste.
{15213}{15235}Omlouvám se.
{15253}{15286}Jdu sem rovnou zpráce.
{15335}{15356}C-Co?
{15419}{15439}C-Co?
{15446}{15524}Hmm... tak tohle je tvùj pøítel, Honoko?
{15533}{15617}Mìla jsi se alespoò pøevléci, Nano.
{15626}{15659}Jenom klídek, jo.
{15672}{15740}To je tvoje pøítelkynì, Honoko... no...
{15753}{15828}Ach, ráda tì poznávám... já jsem Shirakawa Nana.
{15837}{15859}Tìšímì.
{15867}{15918}T-Taky mì tìší.
{15924}{15945}Ach... jsem váš velkı fanoušek.
{15956}{16007}Já... vidìl jsem všechny vaše filmy.
{16013}{16049}Já sem v ádnem filmu, ale nehrála.
{16055}{16084}S-Samozøejmì.
{16091}{16155}Promiò, urèitì jsi zaskoèenı, viï?
{16180}{16208}No já...
{16273}{16297}Ostatní nás pozorují.
{16327}{16351}Tak pojïme jinam.
{16436}{16503}Hmm, take vy dvì jste kamarádky u od základky?
{16534}{16555}Správnì.
{16561}{16604}Jsme nejlepší kamarádky.
{16611}{16698}U na základce jsem byla populární...
{16705}{16786}... a podle toho se mnou lidé i zacházeli.
{16801}{16879}Nebyl tu nikdo s kım bych si mohla normálnì promluvit.
{16917}{16932}Rozumím.
{16938}{16983}Lidi z tıhle brane to musí mít asi tìké.
{17038}{17122}Jednou kdy jsem se ve škole rozèílila...
{17134}{17203}... jsem se cestou domù schovala a chtìla si zakouøit.
{17391}{17467}Ale pøistihla mì tam jenda Miko-san.
{17391}{17467}Miko-san = dívka ve slubách svatynì Shinto.
{17475}{17535}Hele, nemìl bys kouøit cigarety!
{17556}{17577}Nech mì bejt.
{17586}{17610}Nenechám.
{17616}{17655}Podle té uniformy chodíš do stejné školy jako já.
{17664}{17688}Jak se jmenuješ?
{17695}{17755}Co? Ty nevíš kdo jsem?
{17755}{17797}To bych se asi neptala.
{17812}{17888}Mé ego bylo v tu chvíli zralé na umìlé dıchání.
{17892}{17916}C-Co?
{17925}{17961}Co to máš vùbec za kostım?
{17970}{17979}Co?
{17985}{18033}To není kostım abys vìdìla!
{18039}{18084}A koukej sem navalit ty cigará!
{18090}{18105}Zapomeò.
{18105}{18140}Dìlej, naval je!
{18105}{18207}To bylo poprvé, co se se mnou nìkdo bavil normálnì.
{18140}{18164}Zapomeò!
{18170}{18187}Dìlej!
{18192}{18207}Nedám!
{18237}{18312}A ne sem se nadála byli jsme pøítelkynì.
{18343}{18373}T-Takhle to opravdu bylo?
{18385}{18487}Take dnes jsem sem pøišla jako pøítelkynì Honoky, abych øekla nìco jejímu pøítely.
{18498}{18532}Co? Mì?
{18539}{18581}Ona nemá ádné zkušenosti s klukama...
{18587}{18638}... a neví co opravdu znamená s nìkım chodit.
{18646}{18670}Poèkej, Nano!
{18676}{18754}Take jestli s ní chceš nìco mít...
{18766}{18812}... jdi na to velmi opatrnì, dobøe?
{18874}{18913}Nech toho, Nano!
{18919}{18971}Pøestaò u øíkat, takové vìci!
{18975}{19053}Ne! V tìchhle vìcech musí bejt jasno!
{19059}{19071}Boe.
{19083}{19124}Kam to jdeš, Honoko?
{19131}{19148}Na záchod.
{19165}{19235}Pokadı kdy se cítí trapnì, uteèe.
{19260}{19300}Taky se cítím hodnì trapnì...
{19310}{19322}Tak jo.
{19337}{19381}Zazpívej nìco, Yamoto.
{19432}{19495}Hele, hele, nebude ti vadit, kdy si zazpívám nìjakı písnièky?
{19507}{19574}Maj tady nìkolik písnièek, kterı bych chtìla zkusit, ale nevím jestli je zvládnu.
{19599}{19677}Do toho, do toho, do toho, Hiroshimo!
{19682}{19755}Do toho, Hiroshimo!
{19708}{19755}Co je to?
{19776}{19852}Plujíc oblohou, øíkááá...
{19867}{19938}... otvírám své srdcééé...
{19957}{20027}Dnes, je to svkìlééé...
{20038}{20065}Co to, k èertu, dìláš?
{20138}{20171}A-Asahino?!
{20184}{20220}Ty seš opravdu nechutnej!
{20229}{20303}Chodíš s Honokou teprve mìsíc a u jí seš nevìrnej.
{20318}{20341}Tak to není!
{20345}{20369}A jak to teda je?
{20375}{20417}Co to tady vyvádíš, Suzuko?
{20423}{20450}Se podívej!
{20534}{20579}Ach, Shirakawa Nana.
{20604}{20626}Co to znamená?
{20632}{20680}Proè jsi tady s Nanou?
{20692}{20726}No, to proto...
{20732}{20756}Tak moment, Yamato.
{20768}{20798}Neøíkej mi, e chodíš se všema tøema?
{20810}{20831}NE!
{20831}{20878}Kdo potom teda jsou ty holky?
{20882}{20915}To jsou...
{20915}{20981}Neøíkej mi, e chodíš s Nanou, Akitsuki.
{20981}{21011}Jasnì, e ne!
{21011}{21053}Co to potom teda znamená?
{21026}{21071}C-Co se tu dìje?
{21137}{21188}Och, take ty dívky jsou jen kamarádky z bìeckého teamu.
{21200}{21221}Trochu mì to zaskoèilo.
{21233}{21338}Nevìdìla jsem, e Shirakawa Nana, je kamarádka Honoky.
{21347}{21368}O-Opravdu?
{21372}{21393}Promiò.
{21399}{21438}Nic se nestalo.
{21442}{21502}Dobøe, tak teï kdy nás je tady tolik...
{21514}{21544}... proè si spoleènì nezazpíváme?
{21554}{21584}Ech, mùem?
{21590}{21644}Jdu to domluvit.
{21676}{21727}Tak pojïte, sednìte si, sednìte si!
{21801}{21849}Ještì pøíjde Miki, take se musíme trochu smrsknout.
{21930}{22005}Ach, taky se trochu posuò, Akitsuki.
{22291}{22364}Tak jo, zazpívám vám svùj novej song.
{22409}{22439}Boííí.
{22439}{22520}Zpívá nám tu opravdová zpìvaèka, to je neuvìøitelnı.
{22530}{22574}Do toho, Nano.
{22581}{22611}Nana je skvìlá.
{22626}{22660}Díky.
{22712}{22775}Honem, honem, Suzuko, zpíváš jako další.
{22830}{22874}A ty budeš zpívat taky, Akitsuki!
{22875}{22899}No, já...
{22985}{23072}Neøíkej mi, e umíš jen tu písnièku o baseballu, Yamato.
{23106}{23157}Do teï jsi nic jiného nezazpíval.
{23166}{23191}To proto, e nemáš hudební sluch.
{23240}{23306}Fajn, zazpívám nìco od srdce.
{23312}{23363}D-Do toho, Akitsuki.
{23370}{23424}To jí nedaruju, já e nemám hudební sluch.
{23484}{23499}Dobøe, jdu na to!
{23545}{23616}Ale tuhle písnièku jsem si u vybralá já, Yamato.
{23627}{23647}Opravdu, Asahino?
{23651}{23675}Sakra, tak jinou.
{23687}{23741}No jo, ale jakou?
{23745}{23766}Dy je to jedno.
{23766}{23791}Zazpívejte to spoleènì.
{23795}{23881}No, já... pokud to teda nevadí.
{23891}{23945}No, mì to nevadí.
{24007}{24028}Tady máš mikrofon.
{24037}{24085}A né, abys to zmrvil hned na zaèátku.
{24088}{24112}Zklapni!
{24115}{24143}Hned jak mì uslyšíš, padneš na kolena.
{24315}{24354}S-Spletl jsem si písnièku.
{24363}{24399}Zpívej sama, Asahino.
{24477}{24492}Dobøe.
{24503}{24530}O-Omlouvám se.
{24539}{24566}Spletl jsem si èísla.
{24575}{24623}Umm, Akitsuki.
{24797}{24809}Správnì.
{24824}{24881}Musel jsem to udìlat, abych neranil, Honoku.
{25089}{25129}Jsem hotová, hotová.
{25129}{25153}Byla to sranda.
{25162}{25227}Tak jo, Suzuka a já máme ještì nìco na práci.
{25251}{25293}Tak zase nìkdy.
{25305}{25325}Mìjte se.
{25338}{25362}Pá, pá.
{25372}{25402}Pá, pá.
{25419}{25467}Potom teda, pùjdeme taky domù.
{25494}{25524}A co ty, Nano?
{25536}{25554}Jo, jasnì.
{25560}{25623}Dlouho jsem se s Honokou nevidìla, take jí doprovodím.
{25635}{25711}Ty bys s ní cestou, urèitì dìlal nìjakı èuòárny, viï, Yamato?
{25715}{25745}N-Nedìlal! 
{25861}{25894}Dìkuji, Nano...
{25909}{25942}... e jsi mì doprovodila.
{25966}{25985}To je v poøádku.
{25992}{26067}Cestou si chytnu taxíká a ten mì odveze domù.
{26074}{26113}Nìkdy ti zase zavolám.
{26125}{26176}A ty na sebe dej také pozor, Akitsuki.
{26191}{26215}Jo, ahoj.
{26224}{26254}Mìj se, Honoko.
{26380}{26446}Jsi opravdu dobrı pøítel, Yamato.
{26474}{26507}Celou dobu jsem tì sledovala.
{26516}{26570}Jsi opravdu milı a seriózní èlovìk.
{26676}{26788}Honoka má štìstí, e jsi její pøítel, Yamato.
{26792}{26828}N-Nepøeháníš to trochu?
{26843}{26906}Honoka je pìkná, milá, dobøe vaøí...
{26922}{26973}Je to opravdu skvìlá holka.
{26996}{27083}Jsem opravdu rád, e jí mám.
{27098}{27216}Nerad bych udìlal nìco, co by jí mohlo ranit.
{27255}{27291}Nejsi blbej?
{27333}{27413}Co? Dobrı pøítel, kterı nechce ranit Honoku?
{27425}{27462}To myslíš vánì?
{27468}{27501}O co ti, k èertu, jde?
{27513}{27576}Nejdøív mì vychvaluješ a pak uráíš.
{27613}{27631}Pøedtím v Karaoke klubu...
{27643}{27720}... nechtìl jsi zpívat se Suzukou aby jsi neranil, Honoku, je to tak?
{27780}{27825}A potom jsi vzal Honoku za ruku...
{27843}{27891}Take ti nejde o nic víc, ne bıt dobrım pøítelem, Yamato?
{27909}{27970}Dìláš to jen kvùli, Honoce?
{27974}{28013}Co po mì vlastnì chceš?
{28022}{28088}To sem mìl s Asahinou zpívat a Honoky si nevšímat?
{28097}{28136}Nic takovıho jsem neøekla.
{28145}{28229}Jen øíkám, e si myslíš, jak nejseš dobrej pøítel, kdy si to takhle zahrál do autu, Yamato.
{28235}{28265}Ve skuteènosti seš, ale blbec.
{28277}{28310}Dr hubu!
{28324}{28383}Ten kdo nìkomu øíká, e je blbec, je sám blbec!
{28398}{28445}Jen proto, e seš slavná, ti nedává právo mì uráet!
{28448}{28464}Krávo!
{28553}{28633}Jen nìkdo nezodpovìdnı se dokáe tak snadno naštvat.
{28647}{28704}Chováš se jak dìcko, Yamato.
{28734}{28794}To jak se chováš pøed Honokou...
{28806}{28871}... to nejsi ty, ale jen tvùj smyšlenı ideál.
{28875}{28935}T-Tak to teda ne!
{28947}{28976}Jsem jakej jsem.
{28989}{29004}Vánì?
{29019}{29082}Vypadals, jako by ses do toho musel nutit.
{29094}{29118}Ne, nevypadal.
{29125}{29224}Víš vùbec co má Honoka rádá? Co dìlá ráda?
{29239}{29281}A co její datum narození, znáš ho?
{29368}{29431}Máš pravdu... nic z toho nevím.
{29440}{29512}Hele, ty máš Honoku opravdu rád?
{29535}{29601}Ale vùbec to tak nevypadá.
{29613}{29713}Ty jsi opravdu spokojenı s tím, e se chováš jen jako dobrı pøítel, viï?
{29769}{29823}U teï vidím jak Honoku zraòuješ...
{29838}{29900}... a jestli chceš takhle pokraèovat, tak se s Honokou radši rozejdi!
{30034}{30091}Opravdu...
{30091}{30160}... o Honoce nic nevím.
{30179}{30245}A ani sem se nesnail to zjistit.
{30383}{30398}Proè?
{30410}{30449}Vdy jsem její pøítel.
{30470}{30497}16. záøí.
{30522}{30582}Pamatuj si to, to má Honoka narozeniny.
{30594}{30672}Jestli si nepospíšíš, tak jí nestihneš koupit dárek.
{30772}{30868}Hej, nebuï z toho hotovej.
{30877}{30905}Seber se!
{30977}{31091}Místo toho pøemıšlení, se víc zajímej o Honoku.
{31176}{31209}To je všechno.
{31230}{31239}Mìj se.
{31420}{31438}Víc...
{31484}{31514}... se zajímej o Honoku.