{2671}{2716}Ona si ten dárek nevzala?
{2752}{2773}Jo, nevzala.
{2782}{2880}I kdy mi øekla, e jí nevadí, e sem ho vybíral s Asahinou.
{2891}{2965}Ale jak jsem se zmínil, kde všude jsme kvùli tomu byli, tak se naštvala.
{3057}{3087}Tak co myslíš?
{3087}{3114}Já to nechápu.
{3126}{3196}Øíkaš, e jí nevadilo, e jsi to vybíral se Suzukou?
{3227}{3239}Jo.
{3251}{3287}To není monı.
{3325}{3374}Musela ti to øíct naschvál.
{3393}{3411}Naschvál?
{3423}{3447}No, jasnì.
{3459}{3548}Nebo myslíš, e jí je jedno, e chodíš po obchodech se svoji ,,bejvalou´´.
{3563}{3643}Tohle je nìco jinıho, ne kdy jdeš s Hashibou nebo Yuuko.
{3652}{3688}T-Tak moment.
{3700}{3755}Já s Asahinou vùbec nic nemám.
{3765}{3819}Jene Sakurai to vidí jinak.
{3831}{3886}Ještì nedávno si po ní toti jel.
{3914}{3929}Ale...
{3953}{4019}To, e jí to nevadí, ti øekla jen tak.
{4031}{4120}Nìkdy je lepší dret hubu, ne vanit, vanit a vanit kupu cypovin.
{4158}{4182}Vìøím ti.
{4188}{4269}Snail jsi se vybrat nìco pìkného, viï?
{4327}{4449}Tak jako tak, do toho zapoj i hlavu.
{4463}{4514}T-Tak to není.
{4524}{4658}Ten dárek jsme vybírali strašnì dlouho a kdy jsem ho koneènì našel, mìl jsem z toho radost.
{4672}{4717}Dìlal jsem co jsem mohl.
{4746}{4809}To je pøesnì to, o èem mluvím.
{4824}{4891}Tímhle si Sakurai akorát nasral.
{4898}{4934}Mìl by ses jí co nejrychlej omluvit...
{4940}{4988}... nebo to bude horší a horší.
{4997}{5033}Fajn, tak u dr hubu.
{5045}{5122}A do teï mi všechny tvı rady byli úplnì k hovnu.
{5122}{5145}Yamato.
{5191}{5227}Vyøeším si to sám.
{5242}{5267}Podle sebe.
{5273}{5291}No, jasnì.
{5312}{5349}Take pùjdeš a omluvíš se.
{5365}{5383}Dr hubu.
{5439}{5580}ROZCHOD
{5616}{5667}Fajn, zaèneme s rozbìhy.
{5670}{5708}Jasnı.
{5774}{5861}Ze všeho nejdøív bych se mìl omluvit.
{5958}{5967}Támhle.
{6002}{6020}Honoko.
{6032}{6062}Umm, já...
{6074}{6092}Vèera...
{6136}{6209}Ech, p-poèkej.
{6258}{6318}Za ten vèerejšek... se...
{6330}{6423}Promiò, ale nechci se s tebou bavit, Akitsuki.
{6453}{6507}A-Ale proè?
{6519}{6552}Tak aspoò poslouchej co ti chci øíct.
{6555}{6577}Nechci to slyšet.
{6658}{6724}Hej, servismene, mùeš na chvilièku?
{6733}{6760}A-Ano.
{7586}{7665}Co tady dìláš, Asahino?
{7672}{7785}Tak co, udobøil jsi se s Honokou, Yamato?
{7789}{7837}Ach... ne...
{7849}{7885}Øekla, e se se mnou nechce bavit.
{7928}{7994}Chtìl jsem se omluvit.
{8021}{8053}Ale nechtìla o slyšet.
{8102}{8124}Promiò.
{8161}{8207}Za co se omlouváš, Asahino?
{8232}{8319}Kdybych.... s tebou nešla nakupovat...
{8343}{8392}... vy dva byste se nepohádali.
{8411}{8441}O èem to mluvíš?
{8456}{8495}Byl jsem to já, kdo tì o to poádal.
{8516}{8561}Nemùeš za to, Asahino.
{8590}{8605}Ale...
{8628}{8661}Yasanobu mi øekl...
{8679}{8733}... e je to všechno moje chyba.
{8745}{8797}Tak si s tím nelam hlavu.
{8858}{8905}Ale, co budeš dìlat?
{8953}{9029}Pøece... ti øekla, e se s tebou nechce bavit.
{9039}{9087}No, nemám páru.
{9099}{9177}Neèekal jsem, e se tak naštve, kdy jí øeknu pravdu.
{9204}{9285}Zrovna teï mì asi nenávidí.
{9309}{9339}To urèitì ne.
{9372}{9438}I kdy se teï s tebou nechce bavit...
{9467}{9521}... mìl by sis s ní znova promluvit.
{9536}{9551}Odpustí ti.
{9563}{9602}M-Myslíš?
{9658}{9698}Alespoò, si to myslím.
{9708}{9750}F-Fakt?
{9759}{9781}Jasnì.
{9791}{9890}Moná bys jí mohl zavolat na mobil.
{9902}{9920}Zkus to.
{9950}{9986}Rozumím.
{10001}{10022}Zkusím to.
{10043}{10097}Díky za pomoc.
{10161}{10221}Doufám, e se s ní udobøíš.
{10441}{10453}Co?
{10510}{10546}Vdy já vim.
{10552}{10582}Vánì?
{10582}{10652}Já tì znám líp ne ty sama, Honoko.
{10659}{10754}Yamato se ti jen snail koupit nìco pìknıho...
{10760}{10807}... nehledej v tom nìco jinıho.
{10814}{10904}Pøece jsem ti øíkala, e je to... mamlas?
{10916}{10969}A to, e ho doprovázela Suzuka...
{10981}{11020}... to jenom potvrzuje.
{11059}{11095}To bych neøekla.
{11110}{11119}Co?
{11192}{11282}Jsem si jistá, e Akitsuki, Asahinu poøád miluje.
{11347}{11371}To je divnı...
{11389}{11423}Poøád má obsazeno.
{11463}{11542}Má ten náš vztah ještì vùbec smysl?
{11729}{11732}x
{11752}{11805}Podívej, tvoøí pár.
{11832}{11865}Takhle budeme spolu spojeni.
{11915}{11983}I kdy se teï s tebou nechce bavit...
{11996}{12050}... mìl by sis s ní znova promluvit.
{12056}{12077}Odpustí ti.
{12116}{12184}Musim... s ní mluvit.
{12227}{12278}Prostì s ní, musim mluvit.
{12453}{12486}Ach, bratránku.
{12505}{12538}Veèeøe je na stole.
{12549}{12603}Promiò, teï nemùu.
{12618}{12627}Co?
{12644}{12659}Aha.
{12668}{12708}Asi ještì nìco má.
{13254}{13343}Promiò, ale nechci se s tebou bavit, Akitsuki.
{13398}{13428}Nemá cenu nad tím pøemıšlet.
{13440}{13467}Prostì zazvoním.
{13526}{13541}Ano.
{13698}{13735}A-Ahoj.
{13757}{13782}Akitsuki.
{13792}{13837}Co tady dìláš?
{13849}{13918}Já, nemohl jsem se ti dovolat.
{13947}{14045}Prosím... vezmi si... ten mùj dárek.
{14117}{14147}Øekla jsem, e ne!
{14173}{14232}Jestli je to všechno, mìl bys jít.
{14240}{14255}Poèkej!
{14266}{14386}Hele, dalo mi spustu práce vybrat ti nìco pìkného k narozeninám, Honoko.
{14397}{14470}Take, bych rád slyšet, proè to nechceš.
{14480}{14534}Jestli mi chceš nìco øíct, tak to øekni!
{14540}{14578}Nemám páru o co tady ti jde.
{14591}{14618}Chtìla bych si to vzít...
{14666}{14817}... ale nejde to, kdy sis pøi jeho vybírání uíval s Asahinou.
{14821}{14848}O èem to mluvíš...
{14866}{14952}... nevìdìl jsem co ti koupit, nešlo to jinak.
{14970}{15022}Mohl si øíct nìkomu jinımu.
{15034}{15073}Proè jsi musel øíkat zrovna Asahinì?
{15109}{15198}Pravdou je, e hledáš dùvod, k tomu, abys s ní byl!
{15202}{15238}To není pravda!
{15247}{15269}To teda je!
{15273}{15324}Nejsem slepá, abych to nevidìla.
{15333}{15420}Jedinı na co poøád myslíš je Asahina, Akitsuki.
{15432}{15503}A a u øíkáš cokoliv, prostì to tak je.
{15531}{15588}Poøád Asahinu miluješ nebo ne?
{15600}{15633}Miluješ jí víc ne mì!
{15644}{15674}Nepøeháníš to trochu?
{15680}{15701}Seš úplnì cáklá.
{15710}{15771}Ty seš tou Asahinou úplnì posedlá.
{15778}{15794}Nech mì bejt!
{15826}{15856}P-Poèkej!
{15916}{15950}Neslyšíš? Poèkej!
{16157}{16181}Nešahej na mì!
{17042}{17135}Jedinı na co poøád myslíš je Asahina, Akitsuki. 
{17171}{17315}Moná má pravdu, moná to tak podle mıho chování vypadá.
{17398}{17514}Kdy se to tak vezme, tak s Asahinou jsem dost èasto...
{17535}{17606}... moná to pak vypadá, e si od toho nìco slibuju.
{17842}{17935}Nenapadlo mì, e to bude Honoce vadit.
{17991}{18119}Nemá to smysl, jestli spolu budem dál chodit, tak se tohle bude opakovat.
{18141}{18159}Poøád dokola.
{18224}{18272}Asi...
{18272}{18315}... bysme se mìli rozejít.
{18358}{18376}Asi.
{18432}{18447}Dobøe.
{18666}{18678}Blbeèku.
{18723}{18802}Ani jsi mì nepozval na rande, blbeèku.
{18824}{18836}Promiò.
{18869}{18950}Tys se mnou zaèal chodit kvùli tomu polibku?
{18959}{18993}T-To ne.
{19003}{19030}Tak proè?
{19054}{19093}Protoe seš pìkná.
{19122}{19207}A opravdu se mi moc líbíš... fakt moc.
{19218}{19251}C-Coe?
{19263}{19297}A to je celı?
{19306}{19428}Kdy jsem s tebou, nenutí mì to myslet na Asahinu.
{19470}{19515}Stejnì tak, kdy jdeme do školy...
{19536}{19584}Kdy spolu jíme...
{19610}{19625}A...
{19655}{19734}... ani kdy jsem ti kupoval tvùj narozeninovı dárek.
{19741}{19831}Opravdu jsem myslel, e tì mám rád, Honoko.
{19846}{19900}A proè mi to øíkáš a teï?
{19930}{19942}Protoe...
{19962}{20045}... nechci, aby ses na mì zlobila kdy jsme se teï rozešli.
{20108}{20117}Hele...
{20150}{20223}... ten dárek... poøád mi ho chceš dát?
{20230}{20275}Jo, to chci.
{20290}{20302}Proè?
{20340}{20355}Protoe...
{20400}{20504}... si chci uchovat památku na náš vztah, i kdy trval tak krátce, Akitsuki.
{20527}{20554}Dìkuju za dárek.
{20572}{20598}Budu ho ochraòovat.
{20686}{20705}Honoko...
{20897}{20936}No já...
{21147}{21177}To je tvùj dárek.
{21278}{21290}Mìj se.
{21358}{21397}Mìj se.
{22445}{22461}Mìj se.
{22814}{22838}U ses vrátil, bratránku.
{22912}{22928}Vrátil.
{22947}{23015}Hele, líbil se Sakurai ten dárek?
{23109}{23131}Ty nebudeš jíst?
{23144}{23156}Ne.
{23204}{23222}Bratránku.
{23358}{23452}Jedinı na co poøád myslíš je Asahina, Akitsuki.
{23548}{23575}Opravdu?
{23603}{23627}To není pravda.
{23714}{23777}A jak se teï mám k Asahinì vlastnì chovat?
{23866}{23898}Vítej doma.
{23904}{23931}Jdeš pozdì.
{23943}{23993}O-Omlouvám se.
{24047}{24147}Støedoškolák by nemìl zùstávat venku tak dlouho do noci.
{24157}{24211}Dneska na to nemám náladu.
{24227}{24273}Promiò, Yamato.
{24280}{24340}Saotome mì k tomu donutila.
{24358}{24421}To je dobrı, u se stalo
{24436}{24457}Co se stalo?
{24463}{24493}Nevypadáš zrovna nejlíp.
{24502}{24560}Sedni k nám a napij se.
{24582}{24607}Chci bejt sám.
{24617}{24695}Co je? Pohádal jsi se s Honokou, nebo co?
{24801}{24846}Právì jsme se rozešli.
{24898}{24917}A proè?
{24924}{24978}Co? Ona tì odkopla, Yamato?
{24990}{25035}Ach, boe, zklapnìte!
{25077}{25156}Není to tak, e by mì nechala nebo já jí.
{25175}{25208}Nejseš ty, kterén?
{25217}{25301}Rozejít se s tak milou holkou... taková škoda.
{25360}{25383}Já vím.
{25388}{25422}A víš to opravdu jistì?
{25434}{25529}ádnou takovou milou a hodnou holku u nikdy nenajdeš.
{25604}{25682}Protoe nejseš ani pìknej ani bohatej.
{25691}{25740}Jenom se na sebe podívej...
{25747}{25783}Seš úplnì neschopnej...
{25845}{25908}Hele, hele, on natahuje.
{25917}{25950}Nech toho, Saotome!
{25956}{25994}Na tom není nic zabavného.
{26003}{26051}Podívej, jak je alostnej.
{26075}{26129}Teï sem se rozešel, tak mi dej pokoj!
{26200}{26288}Myslím, e se mezi bratránkem a Sakurai nìco stalo.
{26334}{26403}Musí to bıt asi vánì, kdy nepøišel ani na veèeøi.
{26433}{26475}e by se zase rozešel?
{26493}{26515}Moná.
{26550}{26611}Urèitì chce bıt teï sám.
{26643}{26661}Já vím.
{26710}{26764}Take, jí se nelíbil tvùj dárek?
{26770}{26800}Nemám slov.
{26825}{26883}Takhle to, ale není.
{26890}{26935}Tak já ti nìco povim.
{26947}{27090}Za celej svùj zasranej ivot jsem nedostala narozeninovej dárek od kluka, nikdy!
{27195}{27235}Ušetøi mì toho, jo.
{27242}{27305}Hele, ani jednou... vánì?
{27314}{27460}Narozeniny... narozeniny... narozeniny by se mìli úplnì zrušit.
{27518}{27570}Dobøe, pojï, pùjdeme, Megumi.
{27592}{27629}Moná je to tak pro tebe lepší.
{27669}{27724}Beztak jsi s ní chodil jen tak, nebo ne?
{27781}{27910}Jsi strašnì nezodpovìdnı a ani vlastnì nevíš, co to znamená s nìkım chodit.
{27959}{28034}No, moje vìc to není, tak toho nechám.
{28047}{28081}Tak jo, dobrou.
{28248}{28263}Máš pravdu.
{28287}{28311}Je to dobøe.
{28413}{28431}Yamato.
{28448}{28463}Asahina.
{28476}{28538}Mùu s tebou na chvíli mluvit?
{28553}{28598}Jo, pojï dál.
{28689}{28746}Slyšela jsem, jak se bavíte.
{28770}{28803}Ty ses s ní doopravdy rozešel?
{28859}{28874}Proè?
{28892}{28940}To ti neodpustila anii pøes tvojí omluvu?
{28988}{29033}Mùu za to já?
{29086}{29214}... ale nejde to, kdy sis pøi jeho vybírání uíval s Asahinou.
{29238}{29262}Mùu za to já, viï?
{29283}{29334}Je to proto, e jsem s tebou byla nakupovat.
{29361}{29382}Nechal jsem jí.
{29414}{29459}Prostì, jsem jí nechal.
{29477}{29504}Co se stalo?
{29531}{29579}Nebavila mì.
{29600}{29643}Tak jsem jí nechal.
{29647}{29703}Co tím chceš øíct?
{29715}{29783}U od zaèátku nám to neklapalo.
{29804}{29863}U mì nebavilo bejt s ní kadej den.
{29889}{29971}Tak poèkej, to myslíš vánì?
{30005}{30035}Och, jistì, jistì.
{30042}{30063}Jak, jistì?
{30075}{30159}I potom všem, co jsi s Honokou zail, Yamato?
{30177}{30201}Vím.
{30213}{30258}Právì, proto jsem jí øekl, e u mì to nebaví.
{30291}{30363}Tak jsem se rozhodl... to s ní ukonèit.
{30381}{30412}Je to tak lepší.
{30440}{30471}Tomu nevìøím.
{30553}{30578}Nenávidím tì!
{31104}{31119}Jsem tak blbá...
{31160}{31235}Jsem tak blbá kdy jsem myslela na takovıho kluka.
{31262}{31277}Debil.