{2634}{2684}No, a tím nìco myslíš co?
{2712}{2810}Chci bejt nejlepším sprinterem... v Japonsku!
{3017}{3078}Co se ti stalo, e se tak mraèíš?
{3088}{3118}Proè se neraduješ?
{3124}{3160}Je z tebe jednièka roku.
{3193}{3221}Jen na chvíli.
{3337}{3346}Tady.
{3396}{3420}D-Druhej.
{3435}{3468}Mùj èas je 10,68.
{3477}{3516}Emersonùv 10,50.
{3554}{3621}Ten parchant mì totálnì pøejel.
{3628}{3655}N-No...
{3685}{3718}Ale i tak seš dobrej.
{3721}{3813}Skonèil jsi druhej a kvalifikoval jsi se na mìstskı závod.
{3832}{3877}Bejt druhej nebo tøetí mì nezajímá!
{3957}{4047}Já... chci bejt nejlepší!
{4092}{4155}Proè tak najednou zvánìl?
{4162}{4304}VİZVA
{4457}{4475}Fajn.
{4490}{4529}Mùeš na chvíli, Akitsuki?
{4557}{4670}Zmiòoval ses o tom, e za pùlkou hladké stovky ztrácíš rychlost, je to tak?
{4678}{4699}Ach, ano.
{4713}{4780}Potom bych ti s tím moná mohl pomoci.
{4834}{4867}Co je to za graf?
{4885}{4968}To je tvoje a Arimová rychlost mìøená po dvaceti metrech.
{5013}{5087}Ta èerná køivka patøí nejlepšimu svìtovımu sprinterovy.
{5098}{5154}Arimá má tu modrou a ikdy se èasovì neshodují...
{5163}{5207}... jsou si ty køivky hodnì podobné.
{5275}{5372}Take, Arima má v sobì pøedpoklad, stát se nejlepším sprinterem na svìtì. 
{5385}{5406}Svìtovou jednièkou?
{5423}{5484}Na druhou stranu, tvoje èervená køivka ukazuje...
{5494}{5536}... e rychlostnì seš na tom sice jako Arima...
{5545}{5628}... ale svojí maximální rychlosti dosáhneš moc brzo a rychleji jí potom taky ztratíš.
{5642}{5783}Take chceš øíct, e potøebuju prodlouit dobu, po kterou beím maximální rychlostí?
{5808}{5848}Tohle je prakticky nemonı.
{5875}{5959}Ani ten nejlepší sprinter neudrí max. rychlost na dıl jak 6 sekund.
{5985}{6054}Chceš øíct, e toho parchanta nikdy neporazím?
{6059}{6091}P-Poèkej chvíli.
{6111}{6165}I kdy nemùeš prodlouit dobu, po kterou beíš max. rychlostí...
{6182}{6231}... mùeš posunout okamik kdy jí dosáhneš.
{6259}{6295}Zmìnou tvé sprinterské techniky...
{6304}{6343}... v kombinaci s postupnım zrychlováním...
{6355}{6424}... by mìlo jít sníit èasovı interval, po kterı ztrácíš svou rychlost.
{6442}{6506}A to mi umoní bìet rychlejc?
{6513}{6546}Ano, umoní.
{6584}{6665}Ale, je velmi tìké zmìnit naráz styl, kterım bìháš.
{6751}{6807}Navíc, mìstskı závod se u kvapem blíí.
{6821}{6879}Moná by bylo lepší, nechat ten plán zatím uleet.
{6885}{6906}To je v pohodì.
{6937}{6949}Rozumím.
{6973}{7006}Potom s tím teda zaèneme hned.
{7012}{7043}Pøipravím ti novı treninkovı plán.
{7056}{7130}Tak jo, a skonèíš s rozbìhama, tak se za mnou stav.
{7155}{7182}Díky za pomoc.
{7210}{7222}Jo.
{7484}{7496}Asahino.
{7540}{7595}Tak se mi to u povedlo vyøešit.
{7608}{7629}Uch,  aco?
{7635}{7712}Dy víš, to jak na stovce ztrácím za pùlkou svou rychlost.
{7722}{7786}Jo, o nìèem takovım si vlastnì mluvil.
{7793}{7847}Vypadá to, e moje sprinterská technika není nic moc...
{7856}{7929}... ale kdy na ní zapracuju, mìl bych pak bìhat rychlejc.
{7934}{7973}V-Vánì?
{7985}{8013}To ale nejde jen tak.
{8020}{8038}Jo, já vim.
{8050}{8088}Miyamoto mi to taky øíkal.
{8097}{8196}A øíkal ti, e zaèátku závodù zbıvají u jen dva tıdny?
{8205}{8271}Nemyslíš, e je na to trochu pozdì?
{8291}{8363}Na zmìnu stylu, potøebuješ víc ne jen dva tıdny.
{8374}{8418}Tohle prostì nemùeš zvládnout.
{8446}{8473}Co je zas s tebou?
{8494}{8518}Seš naštvaná?
{8624}{8636}Hele...
{8683}{8710}Buï zticha!
{8716}{8744}A nech mì bejt, blbeèku!
{8783}{8816}Dìlej si co chceš.
{8831}{8864}Je mi to jedno.
{9044}{9086}H-Hej, Asahino.
{9104}{9117}Já...
{9262}{9301}Kua, co je to s ní?
{9560}{9597}Všichni tak tvrdì trénují...
{9604}{9625}Pøipravit!
{9711}{9723}Start!
{9886}{9937}Fajn, tøi minuty pauza.
{9994}{10030}Ach, to je šílenı.
{10041}{10092}Akitsuki, tady...
{10062}{10089}Dìlej, Akitsuki!
{10112}{10158}Neøíkej mi, e u nemùeš.
{10160}{10205}To seš taková troska?
{10217}{10317}Kdy u jsme u toho, co mìla znamenat ta štafeta, ty chcípáku?
{10325}{10412}Nemysli si, e se z toho vykroutíš tím, e jsme se kvalifikovali dál.
{10425}{10470}T-To bolí...
{10478}{10544}Ale pøedávka byla bez problémù, viï, Akitsuki?
{10550}{10575}J-Jo, jasnì.
{10591}{10646}Moná to bylo i díky mì.
{10697}{10724}Vy dva spolu nìco máte?
{10736}{10763}Ach, vlastnì...
{10769}{10807}Nic takovıho.
{10816}{10849}Arima pobìí štafetu taky.
{10855}{10879}Tvrdım tréninkem...
{10879}{10900}... zlepším svùj styl.
{10906}{10921}Správnì.
{10956}{11001}A proto, musíš víc trénovat!
{11004}{11013}Ano.
{11524}{11596}Zajímalo by mì, jestli Akitsuki ještì trénuje.
{11702}{11732}11.23.
{11746}{11764}Dìláš si prdel?
{11812}{11885}Boha, spíš zpomaluju, ne zrychluju.
{11893}{11926}To je, samozøejmı.
{11926}{11979}Musíš ještì hodnì trénovat.
{11985}{12017}Dnes u ale skonèíme.
{12090}{12117}Ještì jednou.
{12132}{12148}Jo?
{12152}{12173}Boe.
{12185}{12237}Dobøe, ale u naposled, jo?
{12244}{12277}Promiò, e tì s tím otravuju.
{12286}{12331}Byla si jediná, koho sem mohl poádat.
{12334}{12391}Opravdu se cítí provinile?
{12400}{12424}No, ovšem.
{12459}{12505}Fajn, tak naposled.
{12610}{12636}Hele, co je to s tebou?
{12654}{12670}Co tím myslíš?
{12683}{12737}Chováš se teï úplnì jinak.
{12749}{12807}S tím jak jsme trénovali tu pøedávku se to nedá srovnat.
{12808}{12826}Vánì?
{12855}{12888}Nevím jak...
{12897}{12942}... ale našel sem svùj cíl.
{12957}{12975}Cíl?
{13004}{13058}Jo, chci bejt nejlepší.
{13079}{13122}Chci porazit Arimu a bejt nejlepší v Japonsku.
{13131}{13197}Moná, e na to máš, Akitsuki.
{13239}{13305}Ale proè si zaèal najednou tak tvrdì trénovat?
{13323}{13372}K-Koho to zajímá?
{13477}{13525}Je to kvùli tomu, e miluješ, Suzuku?
{13588}{13606}Je to tak?
{13826}{13835}Jo.
{13865}{13907}Proto, chci bejt nejlepší...
{13913}{13968}... abych jí to mohl zase øíct.
{14017}{14142}Nikde není napsánı, e kdy budeš nejlepší, e se do tebe Suzuka zamiluje.
{14142}{14168}Já vím.
{14219}{14281}Vím, e Asahina taková není...
{14293}{14352}... a takhle sem to taky nemyslel.
{14359}{14449}Prostì... si nedám pokoj, dokud to nedokáu. 
{14469}{14511}Nedìlám to, abych tím Asahinu oblbnul.
{14549}{14567}Jo tak.
{14575}{14607}Potom teda nevím, proè ti pomáhám.
{14622}{14678}Z tohodle mì laskavì vynech.
{14684}{14699}Hashibo.
{14722}{14763}A za tohle mì zveš na jídlo...
{14769}{14806}... nebo pro tebe u nehnu ani prstem.
{14810}{14837}Jasnì, jasnì.
{14843}{14897}Potom teda zajdem na okonomiyaki, jo?
{14897}{14938}Ne! Chci nìco lepšího.
{14938}{14986}Co seš zas naštvaná?
{14987}{15026}Yakiniku!
{14987}{15026}Yakiniku - grilované maso
{15032}{15077}Velkı Yakiniku pro tøi lidi.
{15112}{15175}Akitsuki to všechno dìlá kvùli Asahinì.
{15277}{15335}Myslím, e bratránek ještì asi trénuje.
{15348}{15426}Øíkal, e musí teï tvrdì trénovat, protoe závody jsou u za pár dní.
{15443}{15520}Ale je zvláštní vidì, e bere nìco vánì.
{15530}{15575}Mohl by bıt, ale víc veselı.
{15586}{15604}To ano.
{15616}{15686}Moná bychom mu mohli den pøe závodem uvaøit nìco dobrého.
{15699}{15714}Viï, Suzuko?
{15741}{15762}Ach, ano.
{15778}{15799}Co bych mìla uvaøit?
{15814}{15856}Co nìjaké zdravé, netuèné jídlo?
{15865}{15892}Dìkuji za jídlo.
{15901}{15934}To u jsi dojedla?
{16358}{16413}Boe, co je to s ním?
{16432}{16515}Já... chci bejt nejlepší.
{16645}{16666}Co je to...
{17281}{17299}Nano?
{17318}{17396}Promiò, e tì ti zas volám.
{17413}{17458}Pracuješ ještì, Nano?
{17472}{17508}Ne, právì jedu autem.
{17517}{17543}Take, o co jde?
{17557}{17645}No, jen bych s tebou chtìla o nìèem mluvit.
{17659}{17673}Je to...
{17695}{17719}... o Yamatovy? 
{17827}{17858}Za chvíli jsem u tebe.
{18026}{18074}Promiò, e tì poøád otravuju.
{18080}{18107}Nic se nedìje.
{18119}{18158}Stejnì sem byla na cestì domù.
{18181}{18265}A navíc, kvùli práci jsem tì teï dlouho nevidìla, Honoko.
{18284}{18329}Take, sem si u zaèínala dìlat starosti.
{18431}{18485}Ještì poøád si se z toho neoklepala?
{18513}{18564}Nano, já...
{18602}{18717}Myslela jsem, e jakmile získám víc sebedùvìry, opìt se Akitsukimu vyznám.
{18727}{18840}Ale Akitsuki trénuje tak tvrdì kvùli Asahinì...
{18852}{18919}... a Asahina má Akitsukiho asi také ráda.
{18988}{19101}A na mì u prostì nezbıvá ádné místo.
{19136}{19154}Potom na nìj zapomeò.
{19206}{19284}Na nìkoho kdo ti nevìnuje pozornost, bys mìla rychle zapomenout.
{19307}{19331}To bude v poøádku.
{19337}{19397}Vím jistì, e si brzy nìkoho najdeš.
{19409}{19415}Co?
{19429}{19450}Nano...
{20373}{20428}Døeš jak starej fotr.
{20435}{20539}Vím, e chceš bejt jednièka, ale trénovat od nevidim do nevidim...
{20546}{20583}Hm, no jo.
{20587}{20620}Není za tím nìco jinıho?
{20631}{20683}Tvoje zapálení pro tu vìc mì pøímo fascinuje.
{20695}{20744}Chci jen zjistit jestli na to mám.
{20766}{20827}A jestli jo, udìlám proto cokoliv.
{20906}{20964}Takovı odhodlání jsem u tebe ještì nevidìl, Yamato.
{20989}{21040}Doufám, e ti to vydrí.
{21090}{21096}Jo.
{21146}{21170}Naposled.
{21176}{21215}Vzchop se, Akitsuki!
{21215}{21225}Ano.
{21435}{21502}Fajn, tøi minuty pauza.
{21509}{21575}Ach, díky bohu.
{21584}{21623}Mùeš na moment, Akitsuki?
{21632}{21645}Jo.
{21652}{21733}Mám tu graf prùbìhu tvojí stovky z minulıho tıdne...
{21771}{21831}... a taky graf tvojí stovky ze vèerejška.
{21840}{21897}Poøád je tam ten problém s mım stylem?
{21906}{21933}Ne, o to nejde.
{21936}{21945}Podívej.
{21962}{22025}Kvùli tréninku je tvùj èas pomalejší...
{22033}{22110}... ale tvoje køivka se u pøibliuje prùbìhu té Arimovy.
{22114}{22138}Co, fakt?
{22147}{22251}Jo, touhle rychlostí, dosáhneš jeho úrovnì ještì pøed závodem.
{22258}{22297}Jo, zvládnu to.
{22341}{22364}Zas to tak nepøehánìj.
{22380}{22389}Jo.
{22419}{22463}Ach, Asahino.
{22539}{22647}Miyamoto mi teï øíkal, e mùj sprinterskej styl se u zaèíná zlepšovat.
{22680}{22692}Asahino?
{22793}{22838}To e se ti daøí na tréninku...
{22844}{22890}... neznamená, e se ti bude daøit i na závodech.
{22897}{22956}Ech, no, ale...
{23027}{23066}Nebuï hned hotovej z toho...
{23075}{23111}... e ti to zrovna jde.
{23123}{23158}H-Hej, Asahino.
{23224}{23260}Co to s ní zas kua je?
{23269}{23305}Nemusela bejt zas a tak vostrá.
{23334}{23431}Kvùli komu si myslí, e tohle všechno dìlám?
{23448}{23579}Nikde není napsánı, e kdy budeš nejlepší, e se do tebe Suzuka zamiluje.
{23599}{23626}Jo, já vím, ale
{23655}{23721}J-jo, trénovat a trénovat.
{23733}{23757}Nic víc teï udìlat nemùu.
{23925}{23967}Fajn, pro dnešek to staèí.
{23967}{24014}Dobøe.
{24026}{24062}Koneènì konec.
{24068}{24118}Hele, nepùjdem se nìkam najíst?
{24118}{24173}Nechceš se jít nìkam najíst, Akitsuki?
{24191}{24206}Zvu tì.
{24229}{24308}Ach, promiò, potøebuju ještì trénovat.
{24312}{24327}Rozumím.
{24339}{24381}No, závody u klepou na dveøe.
{24395}{24451}Take ten tréninkovej plán nepøeeò nebo se zbyteènì zraníš.
{24458}{24479}Nedìlej si starosti.
{24500}{24515}Tak se mìj.
{24539}{24564}Díky za pomoc.
{24625}{24683}Tak jo, jdeme na to.
{24723}{24780}Ach, taky budeš ještì trénovat, Asahino?
{24786}{24802}Tak se dr.
{24806}{24892}To máš tolik èasu, e jím plıtváš na povzbuzováním ostatních?
{24905}{24939}Bì trénovat, Yamato!
{24981}{25023}Svùj styl si zmìnil moc rychle...
{25035}{25113}... take jestli polevíš v koncentraci, vrátíš se zpátky k svımu pùvodnímu stylu.
{25139}{25160}J-Jo.
{25252}{25282}Nechápu.
{25294}{25334}Co sem zas udìlal?
{25788}{25845}Kua, no to mi ho vytáhni.
{25860}{25917}Proè musí furt mlít ty nesmysly?
{25943}{26000}Ach, to staèí, ztrácím koncentraci.
{26035}{26044}Hej!
{26171}{26194}Chceš nìco?
{26198}{26231}Jak dlouho budeš ještì trénovat?
{26237}{26265}Chci jít u domù.
{26290}{26373}Pøilišnı bìhání má na tebe negativní efekt.
{26388}{26405}To seš blbej nebo co?
{26414}{26473}M-Mám to pod kontrolou.
{26487}{26511}Opravdu?
{26538}{26588}Podle mì to vùbec nechápeš.
{26600}{26635}Nevìøím ti ani slovo.
{26688}{26725}Neser se do mì!
{26737}{26778}Co máš se mnou za problém?
{26903}{26960}Nemá ani páru o tom, jak tvrdì trénuju...
{26974}{27004}... a ještì se do mì bude srát.
{27061}{27073}Zapomeò na to.
{27085}{27097}Mizim.
{27103}{27161}Ech, p-poèkej pøece.
{27167}{27185}Poèkej!
{27229}{27262}Hej, já...
{27528}{27546}Poèkej.
{27587}{27602}Promiò.
{27611}{27671}Tohle jsem nechtìla.
{27725}{27776}Nezlob se na mì.
{27801}{27858}Ne, já se na tebe nezlobím.
{27876}{27897}To sem ráda.
{27921}{27953}Jo, v pohodì.
{28017}{28032}Asahino?
{28080}{28140}Kadopadnì, hodnì štìstí pøi závodì.
{28147}{28165}H-Hej.
{28322}{28361}Hodnì štìstí?
{28485}{28512}Nepotøebuju abys mi to øíkala...
{28578}{28627}... protoe já chci bejt nejlepší.
{28919}{28969}Smaená vajíèka...
{29089}{29101}Vypadá to skvìle.
{29351}{29422}Ach, jsem vzrušená jako nikdy pøedtím.
{29429}{29474}A z èeho seš jako vzrušená?
{29483}{29517}Tohle je pøece mìstskı závod.
{29533}{29629}Zajímá mì, jaké to je, bìet na takovém závodì.
{29635}{29686}U tebe to kvalifikace jistí.
{29704}{29756}Ty seš fakt hnusnej!
{29766}{29844}Nìco ti øeknu, tohle je jedna z mıch lepších vlastností.
{29858}{29876}Blbeèku.
{30032}{30059}Tak je to tady.
{30071}{30083}Jo.
{31361}{31367}Fajn.