{2665}{2729}Poøád tì Asahino miluju.
{2795}{2810}Chápu.
{2846}{2903}Nemusíš mi odpovídat hned teï.
{2978}{3021}Nemusíš mi odpovídat hned teï.
{3103}{3174}A se vrátím jako nová jednièka...
{3182}{3239}A vyhraju další závod...
{3254}{3284}Pokud to dokáu, pak mi...
{3345}{3380}... na to odpovíš.
{3402}{3422}Pøestaò!
{3495}{3509}Asahino!
{3534}{3561}Hej, Asahino!
{3718}{3736}Suzuka?
{3766}{3802}Ne, není tady.
{3811}{3835}Stalo se nìco?
{3864}{3935}Pøed dvìma hodinama odešla a ještì se nevrátila.
{3953}{4022}Tak sem myslel, e by mohla bejt u tebe, Hashibo.
{4051}{4090}Co, zas jste se chytli?
{4093}{4099}Ne.
{4125}{4175}Co si kua myslí, e dìlá?
{4190}{4264}Pøece nezmizí kvùli tomu, co jsem jí øekl.
{4327}{4470}ZTRÁTA
{4481}{4555}Co? Yamato ani Suzuka nejsou doma?
{4573}{4585}Ano.
{4600}{4645}Dostala jsem od sestry trochu hrušek...
{4645}{4690}... tak jsem myslela, e je sníme spoleènì.
{4713}{4764}To by mì zajímalo kde mùou bıt.
{4803}{4912}Jestli jde o Suzuku, tak ta vybìhla z Yamatova pokoje se slzamy ve tváøi.
{4954}{5006}Dám krk na to, e se zase pohádali.
{5016}{5084}Take Yamato šel Suzuku asi hledat.
{5095}{5169}To by vysvìtlovalo, proè se brátránek choval tak divnì.
{5186}{5221}Co se asi mohlo stát?
{5228}{5303}Nepochybnì se jí vyznal a Suzuka ho zase odmítla.
{5348}{5393}Tohle on urèitì neudìlal!
{5417}{5448}Co budeme dìlat, Mami?
{5455}{5485}Jen je nechte bejt.
{5485}{5524}Døív nebo pozdìji se vrátìj.
{5531}{5587}To je fakt, tohle je u nich normální.
{5591}{5606}Máš pravdu.
{5618}{5658}Pojïme dojíst tu veèeøi.
{6052}{6105}Akitsuki musí bıt šastnı.
{6553}{6592}Asahina je teï s ním.
{6682}{6722}Kam kruci mohla ta Asahina jít?
{6974}{6991}Suzuko.
{7020}{7083}A se vrátím jako nová jednièka...
{7098}{7136}... pak mi na to odpovíš.
{7272}{7284}Tsuda?
{7296}{7305}Jo.
{7314}{7365}Zítra startuje na národním šampionátu.
{7374}{7409}Hm, no a?
{7426}{7447}Jak, no a?
{7456}{7510}Nemyslíš, e je to skvìlı, segro?
{7523}{7586}Vdy to není poprvé, co tam je.
{7601}{7652}Nechápu, proè seš z toho tak hotová.
{7658}{7689}To proto...
{7742}{7796}... e jeho èasy, jsou teï opravdu dobré.
{7816}{7885}A sám mi øekl, e ten závod vyhraje a...
{7914}{8008}Snaíš se mi neøíct... e ses do Tsudy zamilovala?
{8015}{8072}Och, jasnì, e ne!
{8088}{8157}Je to pravda, no není to legraèní?
{8166}{8232}ádnej manekın to zrovna není.
{8241}{8331}A-Ale, kdy bìha, tak je úasnı.
{8344}{8359}Tak podívej.
{8367}{8390}Co?
{8398}{8437}Ty ho prostì miluješ.
{8446}{8484}Je to na tobì vidìt.
{8514}{8595}Mami, Suzuka prej miluje Tsudu.
{8604}{8632}T-To teda ne!
{8633}{8660}Nenávidím tì, ty krávo!
{8735}{8774}Poèkej, kam to jdeš, Suzuko?
{8780}{8801}Vdy bude veèeøe!
{8804}{8819}Nic nechci!
{8970}{9015}Boe, to je, ale kráva.
{9236}{9314}Já... já tì miloval celou tu dobu.
{9441}{9509}Doufám, e ten nároïák vyhraje.
{9728}{9770}Za chvíli to u zaène.
{9838}{9877}To co mu ale øeknu, to neovlivní...
{9901}{9970}... ale i tak si z nìho udìláme legraci.
{10034}{10055}Ještì, ale ne.
{10147}{10195}To sem se lekla, kdo to zas je?
{10284}{10320}Ano, tady Asahina.
{10332}{10392}No, tady Miyamato.
{10398}{10413}Je tam Suzuka?
{10422}{10494}Miyamoto? Vdy... to jsem já.
{10514}{10562}Och, ovšem.
{10571}{10626}Stalo se nìco? Nevoláš nìjak brzy?
{10641}{10695}Ach, co Tsuda?
{10740}{10755}Senpai?
{10740}{10755}Senpai - oznaèení kamaráda.
{10779}{10856}Kazuki zemøel pøi dopravní nehodì.
{11077}{11125}Na pøechodu ho srazil... náklaïák.
{11174}{11255}Jak mohl ten vùl zaspat.
{11286}{11328}Asi si nevšiml znaèky na semaforu...
{11352}{11421}... a pøebíhal tu køiovatku na èervenou.
{11665}{11680}Sentpai.
{11737}{11749}Proè?
{11786}{11905}Proè necítím ádnı smutek ani bolest kdy koukám na tvojí fotku?
{12091}{12139}Všichni tu pláèí.
{12163}{12219}Také bych chtìla plakat...
{12280}{12331}... ale nemohu uronít jedinou slzu.
{12434}{12491}Musím bıt bezcitnı èlovìk.
{12514}{12544}Dobrı, Miyamoto?
{12679}{12770}Skoèím do šatny a odnesu odtamtud Tsudovy vìci.
{12782}{12794}Dobøe.
{12809}{12845}Necháme to na tobì.
{12858}{12867}Dobøe.
{13366}{13392}Zatracenì, Suzukaze.
{13402}{13428}To nemùeš nejdøív zaklepat?
{13685}{13750}Asahina Suzuka. Tsuda Kazuki!! Jednièky v Japonsku!!
{13868}{13920}Co to tam èmáráš na ten stùl?
{13928}{14011}Co? Nic neèmáøu! Tvoøim, tvoøim!
{14022}{14071}To je fuk, stejnì to na tebe povim profesorovy.
{14090}{14111}Kdepak, jedeš v tom se mnou.
{14126}{14162}Tvoje jméno tu je taky.
{14177}{14196}Teï seš mùj komplic.
{14203}{14255}P-Poèkej, tohle pøece nejde smazat!
{14450}{14465}Senpai.
{14577}{14592}Jenom...
{14804}{14861}... sem ti... napsala svou odpovìï.
{14983}{15058}Proè si... musel zemøít?
{15153}{15263}Teï u ti to toti øíct nemùu!
{15361}{15412}Nemohla jsem ti to øíct.
{15439}{15499}Nedal si mi šanci, ti to øíct.
{15991}{16057}Skoèím si pro nìco do obchodu, mami.
{16081}{16141}Potom tedy zamkni svatyni.
{16155}{16164}Dobøe.
{16295}{16301}Co tu...
{16405}{16429}Asahina.
{16463}{16502}Co tady dìláš, Asahino?
{16599}{16671}Och, jasnì, ty tady vlastnì bydlíš, Honoko.
{16732}{16801}Promiò, asi ti tu pøekáím.
{16819}{16884}N-Ne, nepøekáíš mi, ale...
{16902}{16920}... stalo se ti nìco?
{16943}{16955}Nic.
{16974}{17037}Ale vapadalo to, jako bys plakala.
{17058}{17100}Jen mi nìco spadlo do oka.
{17125}{17134}Dobøe.
{17202}{17229}Vlastnì...
{17257}{17322}Ach, za chvíli u bude turnaj Kantou, viï?
{17363}{17411}Jsi skvìlá, Asahino.
{17420}{17476}Seš jediná holka z prváku co se na ten turnaj kvalifikovala.
{17503}{17506}Jo.
{17535}{17595}Myslela jsem, e Akitsukimu se to taky podaøí...
{17610}{17634}... ale neprošel kvalifikací.
{17655}{17736}Myslím, e ho to hodnì sebralo.
{17962}{17971}Já...
{17989}{18041}Promiò, musím u domù.
{18050}{18068}Ach, poèkej!
{18106}{18166}Stalo se nìco mezi tebou a Akitsukim?
{18200}{18263}Yamato s tím nesouvisí.
{18278}{18299}Proè se...
{18302}{18311}Protoe...
{18336}{18415}... miluješ Akitsukiho, Asahino?
{18771}{18795}U sem ti to øíkala.
{18810}{18848}Nic mezi námi není.
{18889}{18939}Yamato je jen pøítel.
{18989}{19001}Leš.
{19056}{19089}Proè se tedy tak nechováš?
{19115}{19127}Øíkám...
{19138}{19222}Jen si to nalháváš a utíkáš pøed tím.
{19261}{19288}U toho nech!
{19306}{19398}Víš vùbec, kolik problémù tím ostatním zpùsobuješ?
{19452}{19473}O èem to mluvíš?
{19479}{19536}Do nièeho se nikomu nepletu!
{19545}{19570}Samozøejmì, e pleteš!
{19580}{19665}Pleteš se tøeba mezi Akitsukiho... a mì!
{19690}{19764}Kvùli tomu, e nevíš, jestli Akitsukiho miluješ, Asahino...
{19788}{19836}... mi zpùsobuješ jen a jen bolest.
{19854}{19905}Já nejsem vaše hraèka.
{19926}{19965}Øíkám ti, e...
{19981}{20032}Ty mùeš bejt s Akitsukim kdykoliv...
{20047}{20087}... tak proè tohle všechno dìláš?
{20142}{20182}Tohle prostì nepochopíš...
{20221}{20269}... dokud toho koho miluješ, neztratíš.
{20441}{20535}Ty zas nemùeš rozumìt tomu, kdy ti osobu, kterou miluješ, nìkdo ukradne!
{20796}{20814}Bì za ním.
{20868}{20976}Akitsuki na tebe èeká u velmi dlouho, Asahino.
{21100}{21109}Ano?
{21209}{21232}Ach, poèkej!
{21444}{21462}Asahino...
{21648}{21669}Akitsuki?
{21713}{21760}Co se dìje? Jsi celı spocenı.
{21765}{21831}Uch, ach, já jen...
{21843}{21888}Asahina z nièeho nic zmizela.
{21912}{21957}Nemùu jí nikde najít.
{21984}{22038}Asahina tady pøed chvílí byla.
{22044}{22078}Uch, Opravdu?
{22085}{22169}Umm, jsi v poøádku, Akitsuki?
{22184}{22211}Nevypadáš moc dobøe.
{22229}{22243}Kde je?
{22253}{22271}Kam šla?
{22328}{22343}Takj Je to pravda.
{22358}{22397}Mezi nimi pro mì není místo.
{22436}{22454}Šla smìrem k parku.
{22469}{22504}Pospìš si za ní.
{22511}{22526}Díky.
{23007}{23031}Bì za ním.
{23053}{23163}Akitsuki na tebe èeká u velmi dlouho, Asahino.
{23243}{23261}Nemùu.
{23288}{23326}Ne abych to znova prošla...
{23344}{23392}... radìji si s ním nic nezaènu.
{23433}{23471}Nic nezaènu.
{23991}{24062}Poøád tì Asahino miluju.
{24095}{24110}Promiò.
{24131}{24167}Za ten vèerejšek se omlouvám...
{24232}{24289}... mohli bysme bıt zase pøáteli?
{24535}{24565}Koneènì sem tì našel.
{24837}{24871}Yamato.
{24882}{24949}Co to tady proboha dìláš?
{25018}{25048}Kdy prší?
{25060}{25086}Pojïme zpátky domù.
{25118}{25148}Hej, poèkej pøece!
{25238}{25259}Nech mì bejt!
{25271}{25316}Uch, co zas máš?
{25316}{25340}Kam to bìíš?
{25351}{25381}Do toho ti nic není!
{25387}{25405}Nech mì bejt!
{25421}{25443}Nenechám!
{25629}{25643}Není ti nic?
{25699}{25743}V tìchhle botách bys bìhat nemìla.
{25806}{25818}Co je?
{25830}{25851}Nemùeš vstát?
{25974}{25995}Hej, Asa...
{26033}{26074}Co je to s tebou?
{26131}{26190}Mùu si snad co chci a kdy chci.
{26211}{26260}Nic ti do toho neni, Yamato!
{26273}{26327}Pøestaò za mnou furt lízt.
{26348}{26369}Seš snad vadnej?
{26388}{26406}Nenávidím tì!
{26421}{26446}Nech mì u koneènì napokoji.
{26502}{26553}O nic sem se tì neprosila!
{26559}{26591}Lezeš mi na nervy!
{26744}{26753}Promiò.
{26765}{26810}Jen sem mìl o tebe starost.
{26932}{26944}Pøestaò u.
{26971}{27028}Jestli budeš na mì dál milı...
{27062}{27116}... pøestaneme se vıdat.
{27234}{27243}Já...
{27267}{27288}Já u to znovu nechci.
{27311}{27335}Co nechceš?
{27390}{27480}Nechci to u znovu zaít.
{27666}{27720}Tsuda Kazuki.
{28000}{28009}Promiò.
{28033}{28077}Já u nechci mít nìkoho ráda.
{28208}{28228}Jak mùeš...
{28243}{28287}Jak mùeš vìdìt co se stane?
{28304}{28388}Proè poøád mluvíš o vìcech, které se stali u dávno?
{28406}{28448}To co se stane nemueš vìdìt!
{28462}{28509}To øíkáš jen proto, e si nic takového nezail.
{28528}{28576}Kdy to nechápeš, tak buï zticha!
{28587}{28602}Nemáš pravdu.
{28618}{28648}To je fuk, pus mì!
{28657}{28681}Nech mì bejt!
{28690}{28700}Já...
{29362}{29377}Já...
{29534}{29591}... nikdy sice nic takovıho nezail...
{29645}{29651}Po...
{29867}{29893}Hajzle!
{30185}{30200}Asahino.
{30397}{30423}To je dobrota.
{30432}{30450}To je.
{30454}{30508}Hej, u jste jich snìdli dost!
{30517}{30598}Nechte nìco taky pro bratránka a Suzuku!
{30612}{30627}To je v poøádku.
{30642}{30678}Ještì jich máme dost.
{30706}{30763}Kdy u o tom mluvíme, ještì se nevrátily.
{30771}{30831}Nedìlej si starosti, nejsou to u dìcka.
{30843}{30952}Moná jsou u nahoøe a udobøují se.
{30956}{30971}To je moné.
{30983}{31028}Co se škádlívá, rádo se mívá.
{31043}{31083}Viï, Gorou?
{31137}{31158}Pak je to v poøádku.
{31342}{31354}Konec.
{31375}{31420}To je absolutní konec.