{1}{1}23.976 fps
{990}{1028}Vezmìte si prosím s sebou|všechny své vìci.
{1028}{1128}Toto je poslední vlak jedoucí do Asakusy.
{3725}{3975}KREV|POSLEDNÍ VAMPİR
{4654}{4790}Za chvíli dorazíme do Asakusy.|Bude to koneèná stanice.
{5752}{5802}Sayo!
{5860}{5909}Kde je?
{5909}{5972}Uvnitø.
{5972}{6023}Meè vypadá, e je tupı.
{6023}{6109}Nevysouvá se z pochvy|tak snadno, jak by mìl.
{6109}{6165}Seeò mi okamitì novı.
{6165}{6228}To není moné.|Nemáme na to teï èas.
{6228}{6298}Pravì jsme identifikovali dalšího z nich.
{6298}{6398}Je dost tìké sehnat meè takové kvality.
{6755}{6787}Co je k èertu?
{6787}{6875}To není on.|Dostali jsme toho, co bylo tøeba?
{6875}{6937}Nezmìnil prostì svoji podstatu, Lewisi.
{6937}{6990}A teï sklapni.
{6990}{7090}Poèkat, nemìlo by to bıt ve tvé pravomoci ?
{7099}{7156}Jsou tam ostatky obyèejného èlovìka.
{7156}{7281}U jsem zkontroloval všechen vojenskı personál,|stejnì tak i civilní zamìstnance.
{7303}{7361}Co tím chceš øíct?
{7361}{7426}U pronikli mezi obyèejné lidí.
{7426}{7509}Øíkáš mi tedy, e se o to mám postarat?
{7509}{7568}Hej, pojï se podívat dovnitø!
{7568}{7613}Nech toho.
{7613}{7675}Jeíši!
{7739}{7804}Sayo! Ovládej se.|Hned!
{7804}{7849}Jen ne znovu toté.
{7849}{7928}Chceš to ohlásit celému svìtu?
{7928}{7986}Nemùu s tím nic udìlat.
{7986}{8032}Sama víš, jak to teï chodí.
{8032}{8132}Rozkazy shora øíkají, ¿e je potøeba|je zabít a na nic se neohlíet.
{8168}{8268}Já opravdu nic nevím.
{8349}{8449}Všechno u je pøipraveno.|Mùeš jet zítra ráno.
{8450}{8550}Zatím ti nachystám školní uniformu a identifikátor.|Bude to na tebe èekat ve skøínce.
{8551}{8606}Bude lepší, kdy si dùkladnì proèteš akta.
{8606}{8646}Víme, ¿e je jich víc.
{8646}{8700}Hej! Sayo!
{8970}{9050}O co jí doprdele šlo?
{9077}{9130}Ty idiote!
{9130}{9160}Co jsem zase udìlal?
{9160}{9225}- Nikdy u ji neprovokuj.|- Ale...
{9225}{9325}Poslouchej mì! Z toho co víme, ona je|poslední ijící z Prvních.
{9390}{9490}Z Prvních...
{10477}{10577}Take z kohoutku stále tekla voda,|kdy jsi ji našla?
{10603}{10703}Uklidni se.|Nemusíš plakat.
{10770}{10870}Nejsem si jistı, ale slyšel jsem,|e Mari šla na rande s nìjakım americkım vojákem.
{11010}{11077}Mari od Charada spáchala sebevradu.
{11077}{11176}Hloupá holka.|Nemusela se zabít.
{11176}{11276}Moná dostala kopaèky.
{11280}{11326}Nemùete se nervovat z malièkostí...
{11326}{11394}kdy dìláte obchod s americkımi vojáky.
{11394}{11494}Slyšeli jste o sebevradách ve škole,|na základnì tak zhruba pøed mìsícem?
{11501}{11597}Zdá se, e jich bylo poslední dobou celkem dost.
{11597}{11673}Jak se zdá, lidé jsou tím velmi znepokojeni.
{11673}{11759}Strašné.|Doufám, e to nebude mít vliv na obchod.
{11759}{11859}Nemùeme s tím nic dìlat,|dokud ijeme mimo základnu.
{11882}{11913}Coe?
{11913}{12038}Nemùeme s tím nic dìlat,|dokud ijeme mimo základnu.
{12481}{12581}STAROITNOSTI A DARY
{12880}{12965}NENÍ NA PRODEJ
{13662}{13762}STØEDNÍ ŠKOLA V YOKOTÌ
{13847}{13947}- Dobrı den.|- Dobrı den.
{14456}{14556}Mladá dámo...
{14563}{14675}Jsi Japonka?|Ty nejsi místní studentka, viï?
{14710}{14770}U jsi byla v kanceláøi?
{14837}{14910}Poèkej chvíli.
{14954}{14993}Kde je kanceláø øeditele?
{14993}{15030}He?
{15102}{15168}Prosím vstupte.
{15168}{15268}- Pane øediteli, tato mladá dáma...|- Á, Sayo, jdeš pozdì.
{15268}{15368}Chtìl bych, aby ses seznámila s øeditelem školy.
{15405}{15465}Vítám tì tady. Mluvíš zajisté anglicky.
{15465}{15513}Samozøejmì.
{15513}{15601}V tom pøípadì si mùeš odpoledne|prohlédnout nìkteré tøídy.
{15601}{15701}Díky pøípravám na nadcházející svátek Halloween,|toho stejnì moc neudìláme.
{15766}{15866}Mnohokrát dìkuji za pomoc.|Nashledanou.
{16030}{16063}Co to bylo za dìvèe?
{16063}{16185}Pøijela na inauguraci. Chce se úèastnit|hodin v nìkolika tøídách. Jen na pár dní.
{16217}{16294}- Prosím o prominutí pane.|- Ano?
{16294}{16430}- Jde o zítøejší ples|- U zase? Myslel jsem, e je to téma u za námi.
{16450}{16545}To je pravda, ale od té strašné nehody|uplynulo teprve pár dní.
{16545}{16626}Nejsem si jistá, jestli se studenti|u vzpamatovali ze smrti jejich spoluaèky.
{16626}{16684}Právì proto organizujeme ten ples.
{16684}{16784}U toho mám akorát dost.|Vrate se zpátky do práce.
{17038}{17096}Co je to za pøiblbé obleèení?
{17096}{17196}Nevím jistì. Mìla by to bıt školní uniforma,|jaká se nosí na japonskıch støedních školách.
{17199}{17296}Další mtrvoly byly nalezeny|ve stavu jako ty minulou noc.
{17296}{17342}Všechno se stalo stejnì jako vdy..
{17342}{17422}Dìje se to pøíliš rychle...
{17422}{17479}Øíkal jsem ti, e je jich víc ne jeden.
{17479}{17548}Jestli se jim podaøí pøejít do stavu hibernace,|u je nikdy nenajdeme.
{17548}{17628}Musíme je najít, ne zabijí nìkoho dalšího.
{17628}{17728}Musíme se do nich vít.|A seeò mi ten meè.
{17749}{17849}Já vím...
{18494}{18594}V poøádku, to bylo pro dnešek vše.|Zítra budou jen dopolední hodiny.
{18617}{18717}Ještì jsem neskonèil|Ti z vás, kteøí se podílejí na organizaci plesu...
{18719}{18819}...mají sraz ve sborovnì.|Zbytek z vás mùe zùstat ve tøídách a pøipravit se na ples....
{18848}{18925}Hej, ty jsi Japonka?
{19045}{19108}Nech mì napokoji.
{19108}{19157}Huso!
{19158}{19215}Pojï Lindo, jdeme.
{21848}{21948}Take tohle je jejich "jídelna".
{22312}{22379}Vylekala jsi mì.
{22379}{22441}Co tu dìláš?
{22441}{22522}Nic. Mìla jsem dojem,|e mì bolí hlava.
{22522}{22580}Ale u to pøešlo.
{22580}{22630}Ach. Poèkej...
{22677}{22750}Poèkej chvíli!
{24701}{24801}Pospìšte si. Kapela zaène hrát kadou chvíli.
{24870}{24901}Pane uèiteli?
{24901}{25001}O co jde, Sharon?|Nebudete se pøevlékat do kostımu?
{25019}{25098}Linda mi øekla, e se necítí moc dobøe.
{25098}{25159}To mùe mít souvislost s anémií,|kterou trpí.
{25159}{25259}Myslím, e s ní pùjdu|na ošetøovnu.
{25282}{25368}Zase? Nu co.|Doufám, e mì k tomu nepotøebujete?
{25368}{25393}Ne, pane.
{25393}{25450}V tom pøípadì se k nám pøipojíte,|jakmile se jí udìlá líp.
{25450}{25478}Buïte opatrné.
{25478}{25578}Dobøe.
{25620}{25720}Je všechno v poøádku?|Nepotrvá to pøíliš dlouho.
{26296}{26369}Jednou za èas se snaím to všechno nebrat moc vánì.
{26369}{26469}A zvláštì v den, jako je tento.
{26511}{26577}To není zrovna pohádkovı zpùsob|na strávení Halloweenu.
{26577}{26630}Liso...
{26740}{26821}Nestrachuj se.|Je to jen slabá anémie (chudokrevnost).
{26821}{26907}Za nìjakou dobu by jí mìlo bıt líp.
{26907}{27007}Nemìla by ses tím tak nervovat.|Spíš se sna nìèím zabavit.
{27054}{27128}Za co se plánujete holky pøevléct?
{27128}{27228}Za èarodejnice? Nebo upíry?
{27343}{27420}Aha, tady jsi.
{27420}{27520}Sharon? O co jde?|Co se dìje?
{27569}{27625}Ty...
{28376}{28442}Hej!
{28442}{28500}Hej!
{28535}{28572}Poslouchej mì!
{28572}{28672}Zapomeò na to, co jsi tu vidìla.
{28975}{29075}Proè... Co to je...|Ty jsi...
{29082}{29200}Linda se necítila nejlépe.|Ona jen spala...
{29219}{29319}Lindo...
{29796}{29892}Co? Co to je?
{29892}{29992}Lindo...
{29992}{30092}Sharon...|Sharon!
{30959}{31059}Hej, mama-san,|kde je moje pivo?
{31060}{31160}Ach, omlouvám se.
{31194}{31294}Omluvte mì, za chvíli jsem zpìt.
{32572}{32620}Nemùu tomu uvìøit!
{32620}{32673}Take opravdu jsou tøi.
{32673}{32714}Zahni tady doleva.
{32714}{32763}Jedeme zpìt na základnu?
{32763}{32791}Tady je další...
{32791}{32825}Co?!
{32825}{32925}Jestli ho ztratíme, bude po všem.|Šlápni na to!
{35122}{35175}Tede, vidìl jsi Sharon?
{35175}{35230}Ne, nevidìl.
{36950}{37015}To je maketa!
{37671}{37715}Co to dìláš?
{37715}{37865}Utíkej!
{38131}{38174}Ten taky míøí na základnu.
{38174}{38229}Rozka vojákùm, a se do toho nepletou, doprdele.
{38229}{38329}A Lewisi, najdi Sayu.
{39008}{39108}Omlouvám se madam,|ale chcete mì vylekat?
{39120}{39180}Vy jste uèitelka.|Co tu dìláte?
{39180}{39237}Nemìla byste bıt na plese u pøíleitosti Halloweenu?
{39237}{39323}Pomóc!|Studentka se zmìnila v obludu!
{39323}{39423}Tak to vám nevìøím,|i kdy je dnes Halloween.
{39427}{39512}Ne, je to pravda!|Ona mì tam napadla!
{39512}{39612}Ach ty dìti.|Dokáí teï dìlat kdejaké triky.
{39617}{39717}To nebyl trik!|Prosím, vìøte mi! Pomoc!
{39791}{39891}Paní, snate se uklidnit.
{39944}{40029}Ve škole jsme dìlali rùzné psí kusy tohoto|druhu, které jsme nemìli rádi.
{40029}{40106}Je moné, e kdosi mohl nenávidìt,|nìkoho takového jako jste vy.
{40106}{40206}Dost pravdìpodobné je, e dítì na sebe| chce jen upozornit.
{41201}{41260}Utíkej!
{41457}{41557}Hej, stùjte! Kam jdete?|Tady je zakázáno chodit.
{41650}{41724}Prosím! Pane, pomozte nám!
{41724}{41768}Kdo jste paní?
{41768}{41825}A co to je s vámi za dìvèe?
{41825}{41917}- Ona je...|- Hej... Co se ti stalo?
{41917}{41988}Ty krvácíš!
{41988}{42036}Vlastnì na nás zaútoèili!
{42036}{42136}Poèkejte tady.|Musím zavolat nadøízenému.
{42466}{42566}Jdi dovnitø.
{42648}{42713}Co jsi to pøed chvílí udìlala?
{42713}{42790}Co tu chceš dìlat?
{42790}{42890}Zmlkni!
{43078}{43154}Poslouchej! Kadı, koho oznaèili...
{43154}{43254}...kadı, kdo vidìl jejich skuteènou podstatu,|nemá právo ít.
{43254}{43354}Take je musíme zabít,|ne oni zabijí nás.
{43368}{43450}Kdo jsou "oni"?
{43450}{43550}Démoni. iví se lidskou krví.
{43979}{44079}Doprdele! Nic tu není?
{44122}{44147}Co hledáš?
{44147}{44247}Zbranì.
{44332}{44397}To je nezabije.
{44397}{44497}Zemøou teprve kdy ztratí najednou|dostateèné mnoství krve.
{44537}{44593}Take k èemu bude pistole?
{44593}{44693}Mùeš ji potøebovat.
{44718}{44818}Jako poslední monost mùeš|zabít sama sebe.
{44844}{44909}Pomoz mi, Boe.
{44909}{45009}Nedìlej to!
{45087}{45160}Proè já?
{45160}{45250}Kdo jsi?
{45250}{45350}Proè jsi mi pomohla?
{45377}{45477}Maš štìstí.|Nemùu zabíjet lidi.
{46130}{46200}Mlè!
{46531}{46631}Poèkej! Nestøílej!
{47339}{47383}Davide!
{47383}{47454}Sayo...
{47454}{47554}Sayo, jsi to ty?
{47577}{47677}Otevøi dveøe!
{48393}{48493}A kurva!
{48658}{48758}Sayo!
{48901}{49001}U to dále nezvládnu...
{49036}{49077}Nevzdávej to!
{49077}{49177}Najdi auto a zataras dveøe!
{50048}{50148}Sayo!
{50184}{50234}Meè!
{50485}{50555}Jsi celá?|Sayo!
{51048}{51111}Nedìlej to.|Pøiprav se k letu.
{51111}{51211}Vem auto.
{51463}{51563}Za chvíli se vznese do vzduchu.
{51674}{51774}Pospìš si!
{51819}{51899}- Tady Lewis.|- Cíl se blíí k letištní dráze.
{51899}{51946}V západní èásti Northernpool hoøí.
{51946}{52037}Musíte dorazit k enì, která vidìla tu|zrùdu døív, ne ji najde policie.
{52037}{52137}Rozumím.
{52421}{52500}Doprdele. Chce na nìho vyskoèit.
{52500}{52600}Zapomeò na nìj.
{53202}{53302}- Pøijeï blí!|- Øíkaš to tak, jako by to bylo tak snadné.
{54968}{55068}Kam jdeš, Sayo?|Nemùeš odejít.
{55078}{55150}Sayo!
{57388}{57452}To je všechno, co vím.
{57452}{57552}Øekla jsem vám o všem,|co jsem vidìla.
{57569}{57664}Mimoto, u si nejsem jistá,|e mi vìøíte.
{57664}{57764}Klid, uklidnìte se...|Chceme jen vìdìt, co se vlastnì stalo.
{57780}{57861}Sama si u nejsem jistá,|co se opravdu stalo.
{57861}{57961}Kdy jsem se vrátila na ošetøovnu,|zbytky po Lindì...
{57970}{58070}...to znamená po té obludì, zmizely.
{58070}{58170}ádná stopa zápasu.|Všechno bylo vyèištìné a uklizené.
{58204}{58269}Øeditel, uèitelé...
{58269}{58369}Nikdo by mi neuvìøil,|kdybych vyprávìla co se vlastnì stalo.
{58434}{58534}U vím. Mue, kterı s ní byl,|nazıvala David.
{58540}{58601}Copak on nepracuje v té budovì?
{58601}{58659}On by vìdìl, co se stalo.
{58659}{58730}Kde je?
{58767}{58841}Obávám se paní, e nikdo|odpovídající vašemu popisu...
{58841}{58901}zde nepracuje, ani není evidován|mezi personálem základny.
{58901}{59001}- To není moné...|- Je mi to líto, ale nemáme ádné informace o jeho osobì.
{59186}{59254}Paní, ne odejdete... to dìvèe,|které jste vidìla...
{59254}{59354}Vypadala nìjak takhle?
{61615}{61740}Potom všem jsem nikdy nepochopila,|co jsem tehdy opravdu vidìla.
{61773}{61873}To dìvèe, Saya, a všechny ty obludy,|které zabila, zùstaly nevyjasnìnou záhadou.
{61922}{62022}Jen dva studenti byli pøeøazeni do jinıch škol.
{62052}{62152}Je moné, e stále pøebıvá|nìkde v blízkosti základny?
{62176}{62276}e poøád válèí s tìmi potvorami?
{62277}{62377}Stejnì tak, jako se my lidé|stále zabíjíme navzájem?
{62413}{62513}To je hezkı, ale nebezpeènı ivot.
{62586}{62700}Osvobozenecká armáda zaútoèila na americkou základnu.|Bombardéry B-52 ze základny Yokoto v Japonsku...
{62705}{62830}byly v odvetì nasmìrovány na Dan Hoi|v severním Vietnamu.
{62940}{63050}Pøeklad z polštiny: TomG|Korekce: Yanna a Mipix