{40}{141}Hluboko v opuštìnıch horách je slyšet hlas zvonu...
{145}{220}Škola, izolovaná od módy a spoleènosti...
{223}{302}... se stala pro mue posledním rájem na zemi.
{305}{352}Nìkteøí s obavami...
{369}{479}... jiní s nostalgickou vzpomínkou na mládí, vyslovují její jméno:
{498}{561}Kanenone Gakuen!
{3168}{3216}Kdysi dávno...
{3223}{3337}... il pár, kterı se hluboce miloval.
{3361}{3508}Tato láska, byla ovšem v té dobì zakázána.
{3557}{3637}Proto si pøísahali, e a se znovu narodí, budou opìt spolu...
{3646}{3726}... a šastní a do smrti.
{3799}{3880}Ranní koupel pro všechny
{4405}{4435}Horko...
{4769}{4829}Hlášení ohlednì pohybu objektu M...
{4833}{4902}Podávám pøedbìnou zprávu.
{4910}{4958}Agent: R.
{4981}{5042}Ihned po transportu...
{5046}{5131}... navázal objekt M kontakt s objektem Y.
{5313}{5345}Yuusuke!
{5366}{5422}Našla jsem tì!
{5487}{5575}Koneènì se setkáváme!
{5734}{5837}Yuusuke!
{5950}{6085}Navzdory setkání s objektem M, se u objektu Y vyskytla pamìová anomálie.
{6101}{6170}Objekt M se proto pokusil o políbek...
{6173}{6241}... bez udání blisího dùvodu.
{6255}{6320}Objekt M je opravdu zvrhlá dívka.
{6437}{6468}Yuusuke!
{6573}{6642}Yusuuke! Tolik si mi chybìl.
{6645}{6750}Teï kdy jsme spolu mùeme koneènì zmìnit naší budoucnost.
{6759}{6814}Uááá! Poèkej, poèkej! Pøestaò!
{6823}{6848}Kdo jsi?
{6879}{6972}Naneštìstí, nabízenı polibek byl objektem Y odmítnut...
{6975}{7021}... a tento zámìr selhal.
{7028}{7076}Subjekt M se proto...
{7078}{7131}... opakovanì pokusil navázat se subjektem Y kontakt.
{7156}{7229}Vzpomnìl sis u na nìco... z naší minulosti?
{7257}{7362}Nicménì, pamìt objektu Y, nevykazuje ádné záznamy ohlednì objektu M.
{7366}{7443}Navíc se objevil novı objekt.
{7457}{7496}Já, neprohraju!
{7518}{7552}Start!
{7652}{7674}Mám ho!
{7745}{7770}Och, sakra!
{7860}{7901}Vyhrál jsem.
{8049}{8119}Ani by o tom objekt F vìdìl...
{8123}{8201}... je kadım dnem k objektu Y víc a víc pøitahován.
{8294}{8376}Neøekneš o tom nikomu, viï, Takasaki?
{8409}{8464}To... e jsem breèela.
{8498}{8532}Nikomu to neøeknu.
{8535}{8561}Díky.
{8593}{8704}Vìdom si pøítomností nového objektu, pokraèoval objekt M v navazování kontaktu s objektem Y...
{8707}{8776}... ve snaze získat ho, jen pro sebe.
{8780}{8885}Tím došlo ke zjevnému sblíení, pøesto...
{8888}{8913}Dobré ráno!
{8928}{8954}Dobré ráno.
{8957}{9029}Uch, dobrı ráno.
{9033}{9081}Mohl bys mi to zkontrolovat?
{9110}{9165}Hrùzostrašné.
{9597}{9665}Take, o èem si se mnou chtìla mluvit?
{9669}{9736}Já tì... já tì...
{9745}{9801}... s ní vidìla Yuusuke.
{9820}{9873}Vìøím tí, ale...
{9876}{9895}Huh?
{9902}{9971}Mezi tebou a Futabou se nic nestalo, e ne?
{9974}{10016}P-Poèkej chvily!
{10019}{10136}Ptám se proto, e od té noci se Futaba chová... divnì.
{10212}{10249}Nic se nestalo.
{10251}{10290}Vánì? Opravdu?
{10304}{10347}Díky bohu.
{10350}{10457}Och, boe, u jsem si myslela, e jsi s ní nìco mìl...
{10460}{10509}... nebo tak nìjak.
{10513}{10632}Oh... promiò, e jsem o tobì pochybovala Yuusuke, ale dìlala jsem si starosti.
{10637}{10686}Dej u mi sakra pokoj!
{10703}{10744}Um...Yuusuke?
{10747}{10826}I kdyby se tu mezi mnou a Kutsuki nìco stalo...
{10829}{10886}A i kdyby se Kutsuki chovala divnì...
{10889}{10960}Co ti je, k èertu, potom?
{10963}{11006}A-Ale...
{11025}{11077}Co je to poøád s tebou?
{11081}{11161}U jsem ti pøece øíkal, e tì neznám!
{11399}{11450}Ach, je to divnı.
{11459}{11532}Moùu se tady schovat? Potom to vysvìtlím.
{11546}{11578}Yuusuke!
{11594}{11668}Co? CO? To je tvùj pokoj?
{11758}{11789}Jsem tak šastná...
{11791}{11809}Co?
{11813}{11921}To je poprvé, co jsi za mnou pøišel, Yuusuke.
{11926}{11941}Co?
{11945}{11969}Yuusuke!
{12008}{12063}Taky bysme se tu mohli nasvaèit.
{12065}{12081}Jo.
{12085}{12133}A trochu si odpoèinout.
{12136}{12229}Ach! Je mi tak dobøe.
{12260}{12317}Vzala jsem nám svaèinu... uch?
{12319}{12356}Hej! Yuusuke!
{12394}{12482}Úasné! To je horkı pramen, Yuusuke.
{12502}{12551}Pojï me tam.
{12690}{12805}... si objekt M vıznam jeho existence neuvìdomuje.
{12839}{12940}Na závìr této pøebìné zprávy chci øíct...
{12945}{13058}... e snaha objektu M, zmìnit budoucnost, je marná.
{13069}{13137}Ve své pozorovatelské misi budu nadále pokraèovat.
{13140}{13231}Tímto má zpráva konèí. Agent R, konec.
{13238}{13314}Vzdorovat osudu je tìké.
{13342}{13380}Morimuro.
{13555}{13609}Jsi odhalená.
{13704}{13758}Také jste pøišla na ranní koupel Prof. Chiguso?
{13762}{13843}Já se sem dostanu, protoe mám klíè, ale co ty?
{13846}{13896}No, jsem tady tajnì.
{13899}{14002}Studenti sem mají pøístup pouze veèer, mìla bys to dodrovat.
{14010}{14043}Omouvám se.
{14055}{14071}Huh?
{14162}{14204}Dobré rano!
{14210}{14292}Dobré ráno, Prof. Chiguso, Morimuro.
{14295}{14358}Dobré ráno, Minami, Kutsuki.
{14362}{14435}Byla jsem pomoct, Wakabì, s kvìtinami...
{14438}{14538}... a zahlédla jsem vás, jak jdete sem, paní Profesorko.
{14550}{14635}Je mi líto, Togemuro, ale musíš zùstat tady.
{14678}{14802}Dost jsme se spotili, tak jsme si øekly, e se pùjdeme také vykoupat, Prof. Chiguso.
{14861}{14898}Ach, skvìlé, skvìlé.
{14907}{14997}Máš mnohem lepší barvu, Minami.
{15000}{15041}Ten èerstvı vzduch ti urèitì pomohl.
{15041}{15105}Ano, myslím, e mi dìlá dobøe.
{15114}{15174}Mám lepší barvu i na svıch tajnıch místech.
{15177}{15237}Na jakıch tajnıch místech?
{15245}{15268}Vdy víš.
{15310}{15409}Um, nechme u toho. A co ty, Kutsuki?
{15413}{15465}Togemurovy to také svìdèí.
{15468}{15509}Och? To jsem ráda.
{15512}{15595}Och, ano! Od chvíle co jsme pøijeli vyrostla.
{15598}{15669}To je normální, lidé se prolomením své blány, také stávají dospìlími.
{15672}{15691}Blány?
{15734}{15803}Uch, máme obì na mysli to samé?
{15807}{15820}Ano.
{15823}{15927}Není snad pravda, e prolomení blány se stáváme dospìlími?
{15962}{16021}O èem to proboha mluvíte?
{16062}{16100}O našich tajnıch místech.
{16102}{16138}A taky blanách.
{16141}{16193}Nechme to u bıt.
{16306}{16376}Tady je tak teké se poøádnì vyspat.
{16379}{16421}Pokadé se vzbudím zpocená.
{16424}{16513}Nemohla byste nechat ty láznì otevøené i po ránu, paní Profesorko?
{16518}{16581}No, pokud to zùstane našim tajemstvím...
{16585}{16647}Ach, tak tady jste.
{16652}{16721}To není fér, jít sem sama, Reiko.
{16724}{16800}Tvoje chyba, es nechtìla vstávat.
{16810}{16868}Tak, jdeš sem nebo ne?
{16879}{16925}Samozøejmì, e jdu.
{17666}{17765}Teï u kdy tu nìjakou dobu jsme, co si myslíte o Kanenone Academy?
{17768}{17805}Podle mì je to tu nádherné!
{17809}{17841}Dìláš si srandu?
{17862}{17929}Mobily tu nemají signál...
{17933}{17973}... klimatizace tady není...
{17976}{18038}... a musíme pouívat stejné místnosti jako kluci.
{18041}{18113}Zdejší prádelna zaila s námi svou premiéru...
{18117}{18201}... a co mì totalnì dostalo, byly pøes dva roky nepouitı praèky.
{18204}{18306}Všechno je to tady strašné, vèetnì tìch lidí co zde ijí.
{18369}{18444}Tahám.
{18555}{18614}Futabo!
{18853}{18941}Dnes veèer jsem pøipravil Sekihan.
{19263}{19385}Tvému velkému bráškovy ještì nikdy tak rıe nechutnala.
{19389}{19410}Na hlavì.
{19413}{19432}Na zadeèku.
{19436}{19461}Mitsuko.
{19545}{19596}Tady jsem!
{19677}{19725}Pojïme na to!
{19738}{19790}Mrkej na drát.
{19889}{19972}Och, prosím... nedívej se tak na mì!
{20064}{20153}Proniknu pøímo do tvého srdce, BANG.
{20267}{20341}Tak co øíkáš? Nejsem k nakousnutí?
{20353}{20401}Boe, je to tu hrozné!
{20704}{20757}Ach, jsem v nebi.
{20871}{20948}Teï kdy o tom mluvíš, tak mì ti kluci pøímo dìsí.
{20950}{20981}Opravdu?
{21139}{21173}Togemuro...
{21205}{21257}Och, u je to v poøádku.
{21386}{21499}Nahoru, dolù, nahoru, dolù, nahoru, dolù...
{21505}{21599}Uch, Prof. Chiguso, to máte od komárù?
{21611}{21676}Nemìla bys koukat tolik dolù.
{21679}{21764}Och, mùj boe, zaè mòa trestáš?
{21766}{21865}Naše infiltrace byla úspìšná... i naše maskování je dokonalé...
{21875}{21929}... ale není odtuï nic vidìt!
{21933}{21958}Futabo.
{21962}{22069}Stojíš za mnou v celé své kráse, ale já se nemohu otoèit abych se podíval.
{22073}{22173}Zapomnìli jsme si zamaskovat oblièeje... jestli se otoèíme, odhalí nás!
{22176}{22267}Och, sestøièko Sanae, tvùj velkı bráška je tu taky.
{22270}{22349}A aèkoliv tì velkı bráška nemùe vidìt...
{22352}{22452}... bude na tebe myslet a trpìt pøi pojídání té spousty porcí rıe.
{22455}{22519}Kdybych tu tak mìl jen nìjakou rıi!
{22528}{22594}Máš tak pìknou a hladkou ple, Wakabe.
{22598}{22710}To proto, e pouívám kondicioner z vıtakù Togemury.
{22753}{22871}Och, ale tvá ple je také hladká, Sanae. Jak na zádech, tak i tam dole.
{22881}{22917}Dole?
{23024}{23097}CO? Co je tak hladké TAM DOLE?
{23105}{23210}Má velká sestøièka Futaba je také hladká! Jak na zádech tak i vepøedu.
{23223}{23302}Kde e mám co hladkı?
{23313}{23354}Musím...
{23358}{23406}Musím to vidìt!
{23409}{23488}Och... zašprajcl se mi ve skále...
{23491}{23569}Tøemi prsty to nejde, Sanae.
{23571}{23608}TØEMI PRSTY?!
{23612}{23695}Ale myslím, e dvìma prsty to pùjde!
{23750}{23822}Zkus se uvolnit. Poprvé to vdy bolí.
{23824}{23841}COE...
{23841}{23904}Co to tam kurva dìlají?
{23929}{24036}Velkımu bráškovy ho u zaèíná skala drtit!
{24080}{24111}Mì taky.
{24190}{24245}Co to zase dìláte?
{24249}{24279}Co tím myslíš?
{24282}{24317}Co by mìli dìlat?
{24541}{24630}Ješte to musíte chvíli vydret.
{24638}{24714}Zkuste bıt na ty chlapce víc milejší,
{24722}{24796}Nikdy! V ivotì jsem nevidìla takovı úchyláky...
{24800}{24870}... vùbec bych se nedivila kdyby nás teï šmírovali.
{24877}{24912}Jsou nechutnı!
{24914}{24979}Takhle bys o nich mluvit nemìla.
{24982}{25059}Správnì, tohle místo je skvìlé.
{25062}{25089}Proè myslíš?
{25092}{25145}Protoe je tady Yuusuke.
{25406}{25453}Hoïte mi nìkdo ruèník!
{25494}{25521}Kutsuki...
{25578}{25646}Ano... on je jinı!
{25650}{25679}Au, au!
{25884}{25913}Kutsuki?
{25917}{25966}Tolik jsem se bála.
{25970}{26005}Rozumím.
{26099}{26134}Jsi v poøádku?
{26203}{26229}No...
{26252}{26291}Dobrou noc.
{26305}{26337}Dobrou noc.
{26559}{26588}Tak.
{26602}{26628}Tady!
{26934}{26987}Ten mìsíc je obrovskı.
{27007}{27099}Och, rozumím... musí ti to pøipadat pìkné.
{27179}{27214}Togemuro...
{27474}{27558}Togemurin kop.
{27597}{27671}Togemurin úder.
{27719}{27820}Togemurin zázraènı útok rotujícího hromu.
{27884}{27962}Zùstaò tady prosím se Sanae
{27966}{28045}Jednou si zaplaveme spolu, Togemuro.
{28059}{28105}Uch, Coe?
{28194}{28235}Prof. Chiguso...
{28243}{28344}... moná bysme na nì mohli bejt opravdu trochu milejší.
{28349}{28409}Také si to myslím.
{28413}{28469}To je jasnı, e jo?
{28498}{28553}Dobrá, mìli bysme u jít.
{28560}{28606}Nebo pøíjdeme pozdì.
{28606}{28641}Máte pravdu, pojïme, nebo nestihneme snídani.
{28644}{28679}Jsem u hladaová.
{28682}{28715}Jdeme?|Jdeme.
{28718}{28759}Jdeme?|Pojïme.
{28778}{28837}Och, ne... odcházejí!
{28921}{29008}Musíme se podívaj aspoò jedním oèkem ikdy nám ta skála drtí ptáky.
{29013}{29059}Jdu na to!
{29135}{29180}A he to tu.
{29230}{29259}Dokázal jsem to.
{29432}{29523}Není nic zdravìjšího ne se napít po koupeli mléka.
{29552}{29590}Tak proto jsme si je mìli vzít?
{29594}{29609}Ano.
{29615}{29715}Pøinesla jsem je proto, avy to podpoøilo úèinek koupele.
{29718}{29793}Dobrá, a máme tedy dnes všichni úspìšnı den.
{29796}{29819}Na zdraví!
{29825}{29849}Na zdraví!
{30785}{30832}Dobré ráno.|Dobré ráno.
{30958}{31022}Och, Yuusuke!
{31041}{31099}Dobré ráno!
{31152}{31239}Togemuro, Togemuro, Togemuro.
{31308}{31411}Yuusuke...
{31430}{31480}... miluju tì.