{40}{141}Hluboko v opuštìnıch horách je slyšet hlas zvonu...
{145}{220}Škola, izolovaná od módy a spoleènosti...
{223}{302}... se stala pro mue posledním rájem na zemi.
{305}{352}Nìkteøí s obavami...
{369}{479}... jiní s nostalgickou vzpomínkou na mládí, vyslovují její jméno:
{498}{561}Kanenone Gakuen!
{3168}{3216}Kdysi dávno...
{3223}{3337}... il pár, kterı se hluboce miloval.
{3361}{3508}Tato láska, byla ovšem v té dobì zakázána.
{3557}{3637}Proto si pøísahali, e a se znovu narodí, budou opìt spolu...
{3646}{3726}... a šastní a do smrti.
{3800}{3904}Maximálnì nahrocená stezka odvahy
{3957}{4071}Dlouho, pøedlouho, v období éry Sengoku...
{4092}{4166}... byla nedaleko odtud, svedena bitva neskuteènıch rozmìrù
{4174}{4229}Bitva, jen pohnula zemí...
{4233}{4334}...a která po sobì zanechala statisíce mrtvıch vojákù.
{4378}{4505}Z úcty k padlím, zde místní lidé postavily svatyni...
{4521}{4633}... ale ještì dnes, je tam  moné slyšet køik umírajících vojákù.
{4641}{4744}Duše mrtvıch vojákù dodnes nenalezli svùj klid.
{4765}{4856}A proto jsem zvolila za váš cíl, právì tuto svatyni.
{4860}{4904}Coe???
{4911}{4955}Ale no tak, pøestaòte naøíkat.
{4958}{5039}Letní noc jako je tato, je pro stezku odvahy pøímo stvoøená.
{5042}{5107}A pokud zjistím, e se na to nìkdo, tak øíkajíc, vykašlal...
{5110}{5176}... tak mu to v závìreèném hodnocení pìknì spoèítám.
{5179}{5261}Co budeme jenom dìlat, sestøi?
{5402}{5489}No, je to souèást celkovıho hodnocení, take asi nemáme na vybranou.
{5493}{5514}Myslíš?
{5526}{5622}Do svatynì se vydáte ve smíšenı dvojicích, jen budou náhodnì vylosovány.
{5627}{5682}Uvnitø svatynì naleznete speciální amulet.
{5685}{5760}Ten bude slouit jako dùkaz, e jste ve svatyni skuteènì byli.
{5763}{5814}Pokud ho nedonesete bude diskvalifikováni.
{5842}{5907}Ta stezka odvahy je moje pøíleitost.
{5922}{6040}Snad si vytáhnu partnerku, se kterou proiju nezapomenutelné chvíle.
{6044}{6096}Chvíle na kterou èekám...
{6108}{6208}Boe, buï milosrdnı a vyber mi za partnerku Sanae.
{6270}{6337}Hele, od kdy se k tı sošce modlíš, Tenjine?
{6345}{6398}Dobrá, pøišel èas vylosovat dvojice.
{6454}{6560}Chigusa vypadá v yukatì úplnì mrdoidnì.
{6564}{6670}Hele woe, øíká se, e kdy má enská na sobì yukatu, tak je nahoøe bez.
{6673}{6754}Samozøejmì!|A to není všechno, cucáku.
{6758}{6810}Nikde nemá stopy od provázkù od kalhotek!
{6813}{6882}Uá! Myslíš, e je úplnì na vostro?!
{6885}{6927}Bez kalhotek, bez podprsenky.
{6930}{7033}Pod tím kusem hadru nemá profesorka Chigusa absolutnì nic.
{7129}{7171}Zmocni se mì.
{7245}{7309}Jdu na to!
{7422}{7529}Vyberte si mì! Jako mu, já, Tadatomo ljyuuin...
{7532}{7606}...budu dnes veèer, pokud mi to dovolíte, Váš partner.
{7610}{7626}Co?
{7630}{7674}Právì vyráím na cestu!
{7677}{7752}Omlouvám se, ale jako uèitelka se nemohu této akce zúèastnit.
{7769}{7809}Take tenhle je mùj!
{8201}{8248}Ten poslední je tvùj, Reiko!
{8250}{8353}Uch, jenom jeden? Kdy si ho vezmeš, na mì u ádnı nezbyde, Reiko
{8356}{8412}Och, jasnì! Jako organizátorka se losování neúèastním.
{8414}{8475}Zøejmì budu ve dvojici s Yusukem.
{8483}{8533}Ne, na mì tu jeden zbil.
{8536}{8601}Coe? Potom se tedy udìlalo málo lístkù.
{8604}{8687}Tenhle je tvùj, já mám za úkol všechny pìknì postrašit.
{8689}{8710}Coe?
{8718}{8795}Správnì, Morimura se nabídla, e se toho ujme.
{8798}{8869}Úplnì jsem zapomnìla, e nìkdo musí úèastníky této akce...
{8872}{8913}... taky trochu postrašit.
{8917}{8987}Kadıho chci vystrašit k smrti, tak buï na to pøipravená.
{9002}{9097}Byla bych blbá, kdybych tıhle pøíleitosti nevyuila.
{9105}{9191}Poslední co musím udìlat je, aby se Yusuke sblíil s nìjakou holkou.
{9206}{9260}Sice na mì ádnı lístek nezbyl, ale pamatuj si...
{9263}{9347}... e já a Yusuke budeme stejnì spolu.
{9357}{9443}Dobrá, kadı by teï mìl mít papírek s èíslem, nue, otevøete je.
{9454}{9516}Jaké máš èíslo, Yusuke?
{9518}{9559}Um... mám devítku.
{9561}{9622}Tìsnì vedle, mám tøináctku.
{9701}{9745}To snad ne.
{9747}{9783}Øíkals nìco?
{9783}{9808}Och, kdepak, vùbec nic.
{9811}{9846}Vlastnì, jak to jde?
{9927}{9950}Máš se?
{9950}{9965}Ano.
{10064}{10109}Spoléhám na to, e mì ochráníš.
{10119}{10186}Dobrá, první páry se mohou vydat na cestu.
{10190}{10261}Doufám, e se všichni vrátí zpìt pøed pùlnocí.
{10451}{10560}Promiò, Tenjine, ale sám osud zapøíèinil, e jsem skonèil se Sanae.
{10565}{10617}Buï jí získám nebo zemøu.
{10732}{10824}Jak to, e nejsem ve dvojici se Sanae?
{10829}{10877}Och, Sanae!
{10969}{11096}Ááá! Arisa je vystrašená! Jak to, e s tím nic nedìláš?!
{11280}{11342}Je docela tma, mìla byses dret víc u mì..
{11345}{11370}Hm..
{11391}{11476}Myslíš, e je dobøe, kdy ses rozhodla tıhle akce zúèastnit?
{11490}{11521}Co tím myslíš?
{11526}{11583}Vypadáš jako bys byla vystrašená k smrti.
{11586}{11625}To je v pohodì! Och...
{11648}{11727}Hele, ještì poøád je èas se vrátit.
{11755}{11808}Øíkám, e je to v pohodì.
{11992}{12079}Och, kámo, tolik bych si pøála jít s Yusukem.
{12104}{12176}Kdy jsem nemohl jít s Chigusou, byl jsem zdrcenı...
{12182}{12271}... ale tyhle cecíky taky nejsou k zahození.
{12290}{12358}Co je vlastnì ta stezka odvahy zaè?
{12361}{12440}Coe? Chceš øíct, e o tomhle vùbec nic nevíš?
{12443}{12465}Jo..
{12467}{12579}Stezka odvahy je zkouška pøi které kluk a holka jdou k nìjakımu hrùzostrašnımu místu a probíhá to nìjak takhle.
{12593}{12644}"Já se tak bojím."
{12648}{12702}"To nic, jsem tu abych tì ochránil."
{12705}{12724}"Ale..."
{12728}{12800}V tom nìco zašelestí v køoví.
{12803}{12861}"Ááá! Ááá! Ááá!"
{12865}{12943}"Hahaha! To nic není... podívej, je to jen zajíc!"
{12946}{12987}"Och, já se tak bojím."
{12990}{13031}"Nedovolím aby se ti nìco stalo."
{13035}{13093}"Mohl byses ke mì víc pøitisknout?"
{13096}{13124}"Pokud si to pøeješ."
{13126}{13191}Mladá propocená tìla se tøou o sebe...
{13194}{13254}...a nic u nedokáe zastavit nutkání pøírody.
{13258}{13349}To snad ne! Take o tomhle je stezka odvahy?
{13353}{13402}Potom tedy, Yusuke a Futaba...
{13405}{13461}Ani Kutsuki se nìèemu takovému neubrání...
{13464}{13521}Je jen otázka èasu kdy podlehne hlasu pøírody.
{13524}{13554}Ááá!
{13562}{13619}Dr mì... dr mì, prosím
{13621}{13662}Drím, drím, drím.
{13709}{13738}Nìco takého nemùu pøipustit.
{13738}{13776}Tam dolu, ne!
{13779}{13868}Yusuke a Futaba jsou spolu sami, to je nepøijatelné.
{13872}{13978}Reika to musela plánovat celou tu dobu. Vydr, Yusuke, zachráním tì.
{13981}{14061}Tak takhle nìjak to chodí...chápeš, Midori?!
{14065}{14155}Take jestli chceš, mùeš pokraèovat a skonèit v mojí náruèi!
{14209}{14260}Uch? Midori?
{14331}{14452}Dobrá, je na èase abych ji oslnil svou romantickou konverzací.
{14473}{14557}Och, podívej, Sanae!|Nejsou ty hvìzdy pøekrásné?
{14576}{14631}Uch? Och? Coe?
{14686}{14735}Copak? Øíkal jsi nìco?
{14738}{14785}Ne... to ne, to ne...
{14788}{14848}Pro nìkoho s pøíruèkou Dr. Tanaky...
{14851}{14912}... je sbalení holky jen otázkou èasu.
{14915}{15001}Pøi noèní procházce, dívku dentlmensky doprovázejte.
{15005}{15078}To vám umoní získat body navíc.
{15082}{15099}Jasnì.
{15111}{15194}Sanae? Radši se mì chytni, je to tu kluzké.
{15201}{15285}Omlouvám se, ale jsem trochu unavená, mohli bysme si na chvíli odpoèinout?
{15288}{15318}Pomoc, padám!
{15332}{15418}Dalším krokem je sloit dívce kompliment
{15421}{15497}Tím na sebe strhne její pozornost
{15501}{15528}Jasnì!
{15537}{15664}Ach, tvé oèi záøí jsou tak nádherné, Sanae. Pøipomínají mi záøivı lesk smaragdù.
{15668}{15701}Smaragdù?
{15722}{15833}A tvé pøekrásnì èerné vlasy se lesknou jako samet
{15836}{15894}Jako samet?
{15913}{16016}A tvá prsa ve mì zapalují plameny.
{16019}{16044}Coe?
{16062}{16141}A tvé pùvabnì dlouhé a hebké nohy...
{16145}{16169}Co?
{16193}{16253}Och, boe... Sanae!
{16333}{16389}Tenjin vypadá sklíèenì..
{16392}{16458}Navzdory své postavì to bude asi strašpytel.
{16461}{16565}Neboj se! Jestli cestou narazíme na nìjakého ducha, Togemura se o nìj postará.
{16583}{16602}Hele.
{16673}{16729}To je ten samej kaktus jako onehda?
{16732}{16837}To je v poøádku, Togemura bezdùvodnì neútoèí.
{16840}{16877}Víš to jistì?
{16889}{16940}Je to tak, Togemuro?
{17035}{17120}Och, trpím Togemurofóbií.
{17265}{17357}Poèkej, pøece! Nenechávej chudineèku Arisu samotnou!
{17490}{17610}U-Uááá!
{17692}{17795}Nechápu proè tak øve, vdy jsem ji ani nestihla vystrašit.
{17931}{17987}Hra zaèíná.
{18467}{18548}Hele, ses v pohodì? U dlouho jsi nic neøekla.
{18551}{18623}To nic. Koukám prostì na cestu.
{18632}{18651}Ok..
{18725}{18767}U jdou.
{18882}{18926}Co se dìje.?
{18930}{19004}N-Nìco se mi spadlo ze stromu na tváø.
{19007}{19035}Co?
{19075}{19098}Nic nevidím
{19114}{19137}Ale...
{19188}{19210}Vstávej.
{19293}{19314}Hej!
{19319}{19383}Sklapni... jen se tì na chvíli chytnu.
{19433}{19487}To nic... to nic...
{19582}{19628}Tohle se povedlo.
{19632}{19696}Èas pøejít k další èásti mého plánu.
{19706}{19834}Kampak si utekla, Midori?
{19842}{19939}Já se tu bojím. Nechci tu bejt sám.
{19981}{20084}Díky bohu, ta obrovská silueta, to musí bejt urèitì Tenjin.
{20095}{20147}Tenjine!
{20173}{20220}Tak rád tì vidím.
{20224}{20324}Uch, ty ses pøestal holit, Tenjine?
{20434}{20493}Áááá!
{20534}{20606}Kde jenom mùeš bıt, Yusuke?
{20696}{20724}C-Co to...
{20746}{20780}Opice?
{20807}{20849}Ty jsou, ale hnusnı.
{20886}{20912}Och, boe!
{20917}{21008}Na tohle nemám èas, musím najít Yusukeho.
{21046}{21093}Koukejte mazat
{21097}{21145}Yusuke!
{21158}{21234}Take, jakmile se objeví duch...
{21264}{21349}Togemuro... bouchni!
{21393}{21472}A hned potom, Togemuro...
{21482}{21508}... kopni!
{21525}{21576}Ten kaktus jde po mì.
{21580}{21666}A nakonec, Togemuro, udeø!
{21686}{21780}Tohle udìlá z kadıho ducha fašírku. Teï u se cítíš bezpeènì, viï?
{21817}{21876}Jak elegantní máš nos..
{21881}{21906}Elegantní?
{21938}{22036}Tvá malá ouška jsou umìleckım dílem srovnatelnım s øeckımi sochami.
{22040}{22076}Sochami?
{22092}{22191}Ladné køivky tvıch oboèí musí okouzlit kadého.
{22194}{22220}Jaké køivky?
{22324}{22417}Co jenom dìlám špatnì, Dr. Tanako?
{22537}{22609}Koneènì jsme tady.
{22788}{22840}Kde mají ty amulety bıt?
{22893}{22940}Vítejte.
{22972}{23019}Áááá!
{23033}{23060}Co to...
{23064}{23162}Áááá!
{23169}{23213}Co to proboha je?
{23248}{23330}Áááá! Zachraò nás, Togemuro!
{23390}{23426}Duch!
{23432}{23535}Tvá kolena... ne, ne... tvá stehna a tvá kolena...
{23538}{23552}Uch.
{23555}{23599}Z cesty!
{23669}{23715}Zachraòte mì... nìkdóóó!
{23715}{23747}Z cesty!|Zachraòte mì... nìkdóóó!
{23747}{23754}Z cesty!
{23754}{23768}Z cesty!|Já tvoje holka nebudu!
{23768}{23807}Já tvoje holka nebudu!
{23925}{24030}Hmm, mìla jsem skvìlı nápad. Všichni se pøíjemnì baví.
{24179}{24199}Uch?
{24223}{24243}Co?
{24253}{24301}MONSTRUM!
{24385}{24416}U to pøestalo?
{24420}{24503}Asi jo, ale zajímalo by mì kdo tak strašnì køièel.
{24641}{24690}Támhle, TO!!!
{25117}{25181}O-Och, Jeíši..
{25183}{25198}To bolí.
{25202}{25216}Co?
{25221}{25268}Tvoje ruka.
{25281}{25321}Och... promiò.
{25354}{25413}Hele, to bude asi ta svatynì.
{25480}{25532}Vypadá to tak.
{25710}{25825}Au,  ta Arisa øve jako zvíøe.
{25835}{25876}Co tady vlastnì dìláte?
{25879}{25921}Hej! Bìte od sebe!
{25925}{25977}Jsem tady abych na vás dohlíel.
{25979}{26052}Chlapci a dívky, v tak pozdní hodinu, na takovém místì...
{26056}{26113}... nemohou bıt ponecháni bez dozoru.
{26116}{26175}Co to jenom profesorku Chigusu napadlo.
{26178}{26233}Uspoøádat nìco takového byla chyba.
{26237}{26257}Pane?
{26268}{26287}Co zas?
{26290}{26324}No, co ty amulety?
{26324}{26361}Och, jistì!|No, co ty amulety?
{26403}{26444}Tady jsou.
{26456}{26476}Na te!
{26521}{26628}Všechny jsem je udìlal vèera v noci.
{26633}{26700}Øeknìte, není to snad mistrovské dílo?
{26703}{26800}Dobrá, za chvíli tu bude další dvojice, tak u bìte.
{26806}{26889}A ne, abyste cestou dìlali nìjakı nemravnosti!
{26893}{26924}Ano, ano!
{26959}{26993}Jdeme, Kutsuki
{26997}{27019}Um, pane?
{27019}{27050}Co je?|Um, pane?
{27054}{27110}Mohla bych také dostat jeden?
{27192}{27241}To se ti ten amulet tak líbí?
{27245}{27291}Nelíbí se mi ani trošku.
{27297}{27349}Tak proè sis o nìj øekla? Staèí nám jen jeden.
{27353}{27448}Vzala jsem si ho jen tak pro jistotu.
{27454}{27483}Pro jistotu?
{27699}{27748}Ok, ok... všechno podle plánu.
{27752}{27810}Co jsem zaèala, musím také dokonèit.
{27813}{27837}Reiko!
{27845}{27869}Midori!
{27874}{27913}Co to tady dìláš?
{27917}{28002}A co tu dìláš ty?! A kde máš svıho partnera?
{28009}{28077}Hledám Yusukeho, tak sem ho nechala samotnıho.
{28080}{28142}Seš normální? Tohle pøece nemùeš!
{28145}{28230}Och, kdybys nebyla tak vypatlaná nikdy bysme v tomhle století nezkejsli!
{28233}{28259}Co tím myslíš?!
{28268}{28342}Nikdy s Yusukem chodit nebudeš!
{28345}{28404}To není pravda! Jednou budeme spolu!
{28407}{28468}Tohle je vìc osudu. Prostì se s tím vyrovnej.
{28472}{28489}Nikdy!
{28492}{28534}Osud prostì nezmìníš!
{28537}{28598}Co? To se ještì ukáe!
{28601}{28649}Prostì si to pøipus!
{28667}{28710}C-Co to, k èertu, je?
{28715}{28747}Och, to jste vy?
{28753}{28799}Èau bejby, bude nám ctí...
{28801}{28834}... ji ochránit!
{28837}{28876}Jasnì, ochráníme ji!
{28880}{28909}Si piš.
{28914}{28961}Ok, spoléhám na vás.
{28965}{29011}Musím jít hledat Yusukeho.
{29017}{29045}Poèkej pøece!
{29050}{29076}Hej, co to...
{29086}{29129}Nešahejte na mì!
{29129}{29145}Nešahejte na mì!
{29149}{29165}Hej! Slezte ze mì!
{29165}{29201}Hej, Vylezte odtamtud!
{29201}{29260}Hej! Hned odtamtud vylezte! Uááá!
{29362}{29413}Uch, koneènì jsme zpátky.
{29493}{29575}No tohle, vrátili jsme zpátky jako poslední.
{29578}{29602}Asi..
{29606}{29676}Och, Yusuke!
{29697}{29774}Všude jsem tì hledala.
{29777}{29817}A proè jsi mì hledala?
{29823}{29862}Hele, co je to?
{29866}{29966}Uch, to je amulet. Bez nìho jsme se nemìli vracet.
{29970}{30049}Co? Ale já ádnı nemám!
{30053}{30124}No, tak to máš asi velkej problém.
{30128}{30174}Prosím, prosím, dej mi ho.
{30177}{30269}Ne, to nejde! Jestli ti ho dám, tak mì a Kutsuki diskvalifikujou.
{30275}{30308}Moment.
{30341}{30380}Fajn! Vem si ho.
{30383}{30405}Vánì?
{30413}{30481}Och, jùùù! Díky, Yusuke!
{30496}{30544}Hele, podívej co jsem dostala.
{30547}{30582}Pøeji ti to..
{30589}{30657}Ještì, e sis ten amulet vzala, Kutsuki?
{30661}{30683}Hmm.
{30757}{30809}Ti mládí.
{30883}{30976}Okamitì toho nechte! No tak, neslyšíte?!
{30988}{31055}Jsi v poøádku, Tenjine?
{31077}{31106}Áááá.
{31112}{31195}Má milovaná Futa... Sanae...
{31203}{31261}Má spanilá dívko...
{31265}{31334}... s hebkım tìlem a opálenou kùí..
{31353}{31418}Co?! Tam ne! Pro všechno na svìtì, jenom tam ne!
{31422}{31514}Au! Au! Au! Au! Au!|Au!
