{1}{1}23.976
{46}{89}TaSHee's Gang uvádí
{226}{310}PRINCESS LOVER!
{338}{472}-"Pojï a povzbuï mì", mumlala jsem.-
{490}{593}-Vzdychala jsem pro tebe a volala jsem tì.-
{621}{834}-Necítím se tak trapnì, abych sama otevøela dveøe.-
{900}{1039}-Zabal mì do pìkné malé kulièky a budu skvostnìjší, ne šperk.-
{1039}{1214}-Chci tanèit a záøit dnes veèer u waltzu!-
{1229}{1375}-Sdílet tento èas na lásku s tebou. Mùj nejlepší partner jsi ty.-
{1375}{1507}-Chci potvrdit, e cítíš to samé, ale mùj hlas se tøese.-
{1507}{1659}-Tak jen zavøi oèi a dej mi svou ruku.-
{1659}{1818}-Zakøième nahlas "Zastavte èas!"-
{1853}{2098}-U jsi mi øekl všechno, co chceš, ne?-
{2434}{2459}MEÈ A PLES
{2459}{2491}Ten Arima bojuje?
{2491}{2547}Ano. S van Hossesn-sama.
{2547}{2588}Okamitì tam jdeme.
{2588}{2615}Take, kde je?
{2615}{2643}V hale na šerm.
{2677}{2690}Arima...
{2706}{2723}...bojuje?
{2788}{2807}Tady Fujikura.
{2807}{2841}Je to naléhavé.
{3034}{3050}Kendo?
{3335}{3364}Co to s ním je?
{3364}{3390}Jasnì, e nevyhraje.
{3390}{3425}Zbyteèné pokoušet se ovládat meè.
{3442}{3458}Na tom nezáleí.
{3560}{3623}Vítìzství mım stylem mì neudìlá šastnou.
{3649}{3691}Nebudeme se obtìovat pravidly šermu.
{3712}{3757}Mohli bychom bojovat v tvém "dojo" stylu.
{3779}{3804}Øíkala jsi to.
{3804}{3825}Teppei-sama!
{3952}{3974}Jak jsem se domnívala.
{3974}{3994}Jo.
{4064}{4080}Úasné!
{4094}{4120}Má ostré hrany?
{4146}{4178}Ne. Nemá ostré hrany.
{4204}{4242}Co vaše maska, van Hossen-sama?
{4242}{4262}Nepotøebuji ji.
{4279}{4302}On taky ádnou nemá.
{4302}{4349}Zdá se, e se bavíte.
{4361}{4380}Opravdu?
{4461}{4512}První zásah tìla vyhrává.
{4512}{4528}Jistì.
{4543}{4562}ádné tlaèení.
{4582}{4629}Jestli pøíliš zalaèíš, mùeš nìkoho zranit.
{4629}{4658}Mùeš pøestat jakmile se dotkneš?
{4677}{4712}Nedívej se na mì tak moc shora.
{4737}{4762}Promiò.
{4774}{4795}Ok.
{4815}{4899}A mince, kterou hodím, dopadne na podlahu, souboj zaène!
{4909}{4919}Jistì.
{4942}{4971}Hala se bude brzo zavírat.
{5016}{5043}Pojïme s tím rychle zkoncovat.
{5058}{5136}V poøádku. Jdeme na to.
{5159}{5206}Co to má Arima za postoj?
{5206}{5239}Swift Draw.
{5262}{5375}Technika pomocí které je meè rychle vytaen|z pochvy a v okamiku vrácen zpìt.
{5400}{5419}Minulou noc,
{5440}{5478}mi jeho koneènı pohyb ukázal...
{5493}{5555}...zajímá mì, jestli to byl opravdovı útok jednoho úderu.|/pøekl. - fakt nejsem šermíø, tak se omlouvám za pøeklad :)/
{5574}{5624}Tento boj se rozhodne mrknutím oka.
{5655}{5672}To je zajímavé.
{5689}{5728}Tak, zaèneme!
{5744}{5776}Jedna, dva...!
{6088}{6113}Vypadá to jako remíza.
{6132}{6143}Ne.
{6163}{6178}Coe?
{6178}{6212}Prohrál jsem.
{6237}{6261}Byla jsi rychlejší.
{6294}{6341}Kdyby to bylo skuteèné, u bych byl mrtvı.
{6425}{6482}Ještì toho jeden o druhém moc nevíme.
{6499}{6560}Co øíkáš na to, kdybychom se tímto zpùsobem zaèali poznávat?
{6579}{6629}Plánuješ jít proti slovùm svého otce?
{6641}{6661}To nemyslím.
{6677}{6708}Je to má volba, takto se rozhodnout.
{6722}{6799}Ale kdybych proti nìmu šel od zaèátku,
{6817}{6838}bylo by to pøíliš nudné, ne?
{6941}{6989}Silvie, Teppei! Jste úasní!
{6989}{7014}Miluju vás!
{7138}{7153}Pojïme.
{7183}{7197}Seika-sama!
{7211}{7314}Ten pitomec Arima by mìl utrpìt|více poniující poráku!
{7328}{7366}Hej, nech mì se podívat!
{7366}{7388}Je to nebezpeèné.
{7388}{7428}Nemá to ostré hrany, správnì?
{7428}{7460}Stále je to nebezpeèné!
{7630}{7658}Jak vulgární!
{7670}{7730}Proè jsi tak rozzlobená, Silvie?
{7730}{7788}Protoe se na mì vozíš, proto!
{7799}{7871}Eh? Ale je to zábava jezdit na tobì jako na koníèkovi!
{7871}{7912}Proè jsi tím tak rozrušenı?
{7932}{7953}Hej Charlotte!
{7953}{7989}Co kdy vás uvidí uèitel!?
{7989}{8019}Pøestaò se hıbat!|Co kdy vás uvidí uèitel!?
{8019}{8054}Øekl jsem ti, pøestaò!
{8169}{8213}Co si myslíš o Spoleèenském Klubu?
{8234}{8325}Silvie mi øekla, e bych se mìl pøidat.
{8325}{8367}Myslím, e je to dobrı nápad.
{8367}{8497}Spoleèenskı Klub je v celé škole populární|a setkávají se tam pøíjemní lidé.
{8521}{8570}To zní jako další z tìch strnulıch ceremonií.
{8586}{8631}A co ty? Nejsi ve Spoleèenském Klubu?
{8631}{8688}Nejsem kvalifikovaná.
{8706}{8746}Èlenové klubu by se na mì dívali shora.
{8746}{8840}I kdybych se nìkdy zkusila pøidat, byla by to pro vás hanba, Teppei-sama.
{8851}{8868}Vùbec!
{8889}{8952}Charlotte a Silvie øíkaly, e by mì doporuèily.
{8979}{9044}Jakı druh klubu potøebuje doporuèení k pøipojení?
{9129}{9164}Místnosti Spoleèenského Klubu je...
{9186}{9196}...tohle?
{9217}{9251}Ne pokoj v této místnosti, ale...
{9252}{9290}...celá tahle vìc!?
{9290}{9323}Je pìkná, ne?
{9323}{9374}Byla renovována.
{9374}{9472}Nehledì na to, jestli je krásná nebo  ne, je potøeba,|aby klub zabíral celou budovu?
{9491}{9510}Pojïme dovnitø.
{9755}{9818}Oh, jestli tohle není Charlotte-san a Silvia-san.
{9830}{9852}Jak se máte?
{9865}{9887}Jak se máš?
{9906}{9930}To byla doba.
{9946}{9985}Huh? Tahle osoba je...
{10013}{10059}Chtìly jsme, aby se pøipojil ke klubu!
{10071}{10112}Silvia a já jsme jeho osvìdèení.
{10148}{10176}Jsem Arima Teppei.
{10194}{10253}Tenhle èlovìk je Arima?!
{10253}{10288}Ah...to je Arima!
{10288}{10372}Ah! Pøekvapuje mì, proè je ten hlas tak dùvìrnì známı.
{10372}{10420}Super, jestli on to není Arima-san!
{10436}{10465}Ah. A ty jsi...?
{10465}{10509}Jsem Mezu Haruhiko!
{10532}{10563}Ty jsi také v klubu?
{10598}{10713}Spoleèenskı Klub Akademie Shuuhou|je místo,kde se shromaïuje elitní elita!
{10713}{10808}Pro mì to není nehoda bıt tady---
{10837}{10860}Oh, ty jsi...
{10875}{10899}...dívka z jídelny!
{10899}{10946}Proè je tady sakra Arima!?
{10972}{11032}Tohle místo je zakázáno tìm, kdo nejsou èleny klubu.
{11032}{11077}Toto bídné chování je problematické.
{11096}{11135}Jistì máš zpùsob, jak to vysvìtlit.
{11147}{11201}To tak moc nechceš vidìt tváø Arimi-dono?
{11211}{11250}To nikdo neøekl!
{11250}{11297}Moc mluvíš.
{11297}{11436}Ty, která jsi nikdy nepøišla do klubu, mùu se zeptat| jakı vítr tì sem dnes spoleènì s Arimou pøivál?
{11453}{11476}Co se to pokoušíš øíct?
{11488}{11531}Pøesnì to.
{11542}{11612}Lichotíš mu a v momentì, kdy uslyšíš jméno|Arima hned kroutíš ocasem smìrem k nìmu.
{11623}{11660}Nejsi odlišná od obyèejnıch lidí.
{11674}{11780}Doprovázím blízké pøátele mého otce.
{11780}{11822}Kvùli èemu bych se mìla cítit trapnì?
{11822}{11850}To je divné!
{11850}{11913}Proè jsou najednou všichni tak nepøímí?
{11951}{11968}Arimo!
{11989}{12071}Náhle jsi si naklonil dva z našich |èestnıch hostù. Jak nestoudné.
{12071}{12174}Plánuješ udìlat v klubu nìjakı|zmatek a proto jsi sem vstoupil?
{12194}{12252}Kdy jsem se "naklonila" Arimovi-dono?
{12267}{12322}Prosím zdrte se vytváøení nerozumnıch a nepodloenıch obvinìní.
{12322}{12350}Jen se poniujete.
{12350}{12502}Jako Hlava pøedstavující Spoleèenskı klub, je mou |odpovìdností ochránit vysoké spoleèenské postavení klubu.
{12542}{12608}Nemùu mu dovolit, aby byl doporuèen blízkımi pøáteli.
{12626}{12664}Hezky øeèeno, Seika-sama.
{12684}{12738}To jsou poadavky pøed tím, ne mùeš vstoupit do klubu.
{12757}{12857}Soudící z tvého souèasného stavu, vìøím, e|tentokrát mùu pøehlédnout tvé zhanobení.
{12870}{12916}Jestli rozumíš, za tebou jsou dvìøe, Arimo.
{12932}{12975}Prosím, ujisti se, kde je tvé místo.
{13027}{13051}Moje místo, eh...
{13069}{13220}Mimoto, zvìsti øíkají, e jsi ještì nedávno byl|synem majitele obchodu s nudlemi.
{13220}{13254}To s tím nemá co dìlat!
{13254}{13295}To je to, o èem mluvím!
{13295}{13341}Okamitì zvyšuješ svùj hlas...
{13341}{13408}Zajímá mì, jestli jsi nìkdy zvaoval poslouchat|všechno, co ti ostatní lidé øíkají.
{13421}{13544}Od teï zmìò svùj ivotní styl a staò se nìkım, kdo si |zaslouí bıt privilegovanım hostem Akademie Shuuhou, ne sem pøijdeš.
{13585}{13641}Co je s obchodem s nudlemi.
{13663}{13687}Obchod s nudlemi...
{13705}{13747}Je špatná vìc mít obchod s nudlemi?
{13767}{13865}Fajn! Udìlám všechno a stanu se nìjakım tím|nesmyslem "privilegovanım hostem" a ukáu vám, správnì?
{13900}{13936}Ano, samozøejmì.
{13990}{14032}Oh ano, perfektní naèasování.
{14048}{14118}Spoleèenskı klub bude tento tıden poøádat veèírek.
{14132}{14163}Jsi pozvanı.
{14182}{14309}Jestli vykonáš nìco úasného, nechám tì vstoupit.
{14309}{14331}Rozumím.
{14349}{14384}Nezapomeò na to, co jsi øekla.
{14398}{14429}Zmìním se tak moc, e budeš breèet a mì uvidíš.
{14454}{14508}A uvidíš mé nové já, neodváíš se èurat ve své sukni!
{14517}{14546}Èurat?!
{14546}{14608}Øíkám ti, abys spravil svùj surovı postoj!
{14608}{14624}Fajn.
{14643}{14667}Neodvauj se zapomenout.
{14684}{14722}Zapomnìl jsem...
{14989}{15013}Jak se máte?
{15013}{15036}Teppei-dono.
{15071}{15130}Prosím nedìlej ádné zvuky, kdy piješ.
{15279}{15307}Jak se máte?
{15307}{15364}Zkus mluvit pøirozenìji!
{15520}{15567}Narovnejte záda, kdy chodíte!
{15567}{15580}Ano!
{15766}{15817}Právì jsi zívl, e?
{15847}{15952}Jak mùeš myslet na pøijetí do Spoleèenského |Klubu, kdy jsi tak bezstarostnı?
{15962}{15999}Fajn! Nebudu zívat!
{16077}{16094}Správnì.
{16108}{16159}Raz, dva, tøi!
{16159}{16211}Raz, dva, tøi!
{16223}{16283}Tvá práce nohou u je lepší.
{16283}{16312}Opravdu? Pa---
{16348}{16373}Ne, tak ne!
{16373}{16433}Kdy se pohneš dopøedu, pohni nohama stejnì!
{16433}{16480}Myslíš takhle?
{16510}{16549}Ne! Proè se pøedkláníš?
{16549}{16583}Improvizace není dovolena!
{16594}{16626}To nebyla improvizace...
{16626}{16673}Tanec musí bıt elegantní, jednoduchı a zábavnı!
{16687}{16735}Oh ano, teï kdy jsi se zlepšil...
{16749}{16762}Zlepšil...?
{16777}{16805}Za odmìnu
{16805}{16833}tì políbím!
{16833}{16858}Polibek!?
{16951}{16993}Polibek za odmìnu byl dán!
{17042}{17062}Co se dìje?
{17062}{17096}No, to je jen, um...no...
{17096}{17122}Je to tìké vysvetlit, ale...
{17122}{17144}Bolí tì aludek?|Je to tìké vysvetlit, ale...
{17144}{17177}Ne, to není ono.
{17177}{17194}Co se dìje?
{17194}{17235}No, tohle je...!
{18488}{18517}Omlouvám se za èekání.
{18551}{18564}Dìkuju.
{18564}{18591}Není zaè.
{18591}{18624}Nemùete spát?
{18668}{18723}Mám toho hodnì na práci.
{18738}{18776}Nemyslím, e bych byl nakonec schopnı spát.
{18787}{18851}Kdy budete pít kávu, vùbec nebudete moct spát.
{18861}{18911}No, stejnì nemùu spát.
{18911}{18963}V poslední dobì pøemıšlím o všelijakıch vìcech.
{19016}{19071}Kdy budeš pít èaj, nebudeš schopnı spát.
{19084}{19146}No, dnes nemám èas spát.
{19167}{19217}Mám spoustu vìcí k pøemıšlení.
{19217}{19258}Spoustu vìcí k pøemıšlení?
{19267}{19290}Jako perverzní vìci?
{19290}{19323}Ne tyhle vìci!
{19382}{19397}Copak je?
{19414}{19428}Nic.
{19428}{19496}Jen jsem si vzpomnìl na svou matku.
{19540}{19602}Také jsem ji uprostøed noci ádal o pití.
{19613}{19656}I kdy to nebyla káva.
{19656}{19676}Byl to èaj.
{19739}{19782}Jakı má smysl, e jsem sem pøišel?
{19801}{19856}Na zaèátku byly moje motivy rozdílné.
{19869}{19967}Ale nìjak jsem byl uchvácen vstupem do Spoleèenského Klubu.
{19980}{20020}Milord u to øekl.
{20031}{20084}Mìl byste si nejdøíve udìlat spojence.
{20084}{20173}Zajímá mì, jestli to budu schopnı udìlat dobøe.
{20187}{20244}Jsem váš spojenec, Teppei-sama.
{20257}{20322}Charlotte-sama a Silvia-sama jsou také.
{20346}{20434}Vyrostla jsem v sirotèinci vybudovaném Milordem.
{20447}{20487}Kdy jsem si byla koneènì vìdoma svého okolí,
{20487}{20545}u jsem ztratila svého otce a matku.
{20566}{20675}V tu dobu, pøišel Milord, vychoval mì a udìlal ze mì sluebnou.
{20704}{20761}Milord mi øekl,
{20771}{20839}"Je v poøádku, kdy si myslíš, e mùeš všechno udìlat okamitì."
{20859}{20928}"Zaèni s tím, co mùeš udìlat nejdøív a odtamtud se pomalu pohybuj."
{20959}{21049}Vìøila jsem v nìj a snaila jsem se, jak jen to šlo.
{21074}{21144}"Jednou budeš schopná, pøijdeš a nabídneš|své sluby rodinì Arima."
{21165}{21224}Jsem Milordovi velmi vdìèná...
{21247}{21323}...protoe mi byla dána monost slouit jeho následníkovi.
{21349}{21442}Pochybuju, e stát se mou sluebnou je opravdu taková èest.
{21462}{21545}Milord od vás hodnì oèekává, Teppei-sama.
{21568}{21642}Èekal na vás a vyrostete do dospìlosti.
{21665}{21765}Jsem velmi šastná, e vás doprovázím na vaší cestì.
{21782}{21880}Vìøím, e bıt nìkım potøebován...znamená, e mám dùvod existovat.
{21895}{21985}Jestli to bylo pro nìco velkého nebo nìco malého...
{22008}{22091}Byla jsem na vás drzá. Prosím, odpuste mi.
{22105}{22146}Ne, není za co. Dìkuji.
{22168}{22187}Máte pravdu.
{22204}{22291}Není ádnı jinı zpùsob, ale dáme do toho všechno!
{22312}{22322}Ano!
{22346}{22394}Dobrá, znovu si procvième drení tìla pøi chùzi!
{22394}{22444}Ah...fajn...
{22482}{22498}Jak se máte?
{22498}{22517}Onee-sama!
{22517}{22536}Jak se máte?
{22536}{22560}Dobré ráno.
{22620}{22644}Dnes jdeš brzo.
{22764}{22777}Správnì.
{22777}{22828}Raz, dva, tøi!
{22828}{22862}Raz, dva, tøi!
{22911}{22944}Proè jsi znovu nevykroèil?
{22960}{23018}Ah! Mohl by to bıt Bon Festival Dance?
{23018}{23057}Jak japonské!
{23057}{23088}To není ono!
{23114}{23184}Co to s ním je, tak tìce pracovat, rozhodnì...
{23199}{23313}Zdá se, e na dalším veèírku Spoleèenského Klubu bude |stanoveno, jestli se pøidá dìdic rodiny Arima.
{23314}{23409}Jo, Houjouin-san vypadá, e skuteènì nenávidí Arimu-ki, e?
{23422}{23440}To je...
{23494}{23619}Je to jako kdybych tu já byla nièema.
{23650}{23720}Hej, co máš v kapse?
{23720}{23741}vıkaèku.
{23741}{23789}To je pìknì velkı balíèek vıkaèek.
{23824}{23844}Docela velká vıkaèka.
{23863}{23902}Charl! Teppei-dono!
{23927}{23950}Vítejte zpìt!
{23950}{23984}Prosím nechoïte sem.
{23984}{24018}Je èas na "cvièení s èajem".
{24018}{24052}Prosím, jen o chvilku déle!
{24142}{24192}J...jak se máte?
{24213}{24224}Jaké to je?
{24235}{24278}Nemùeš jednat trochu elegantnìji?
{24278}{24328}Lidé mají hranice.
{24419}{24438}Proè nemùeš zmìnit náladu?
{24438}{24474}Proè si nedáme pøestávku?
{24474}{24508}Udìlejme to.
{24508}{24538}Víc cvièení?
{24551}{24642}No, nemùu v akademii najít pro Teppeie ádného protivníka.
{24642}{24663}Takté tady.
{24663}{24698}Útìk z reality, huh?
{24698}{24735}Ne, ne. Jen mluvíme o pøestávce.
{24747}{24792}Silviino šermování je úasné.
{24792}{24818}Je tak rychlá.
{24818}{24885}Ne, Teppei-dono. Tvùj Swift Draw je mnohem zajímavìjší.
{24900}{24944}Vıchodní šerm je úasnı.
{24944}{25011}Síla, moc a elegance, všechno v jednom "balíèku".
{25031}{25048}To je ono!
{25096}{25187}Teppei-sama se ve váleèném umìní uèil také etiketu , správnì?
{25216}{25387}Místo uèení spousty novıch vìcí, všechno co jste zatím| nashromádil o eleganci a etiketì, by na vás mìlo vypadat pøirozenì.
{25406}{25418}Chápu.
{25428}{25451}To je moná ono!
{25471}{25488}Aha.
{25507}{25529}Dìkuju, Yuu-san!
{25573}{25630}Tak je rozhodnuto, pøepracujme to od zaèátku!
{25676}{25704}Dobrá, jdeme na to!
{25858}{25893}Ten den koneènì pøišel!
{25906}{25966}Ukáeme vısledky našeho tréninku a mìlo by to bıt v poøádku!
{26016}{26075}Chválím tì, e jsi se dostavil vèas.
{26098}{26190}Nech nás dosvìdèit jestli jsi dosáhl vyššího charakteru.
{26190}{26341}Jestli ukáeš, e jsi neschopnı, ujistím tì, e budeš vypadat hloupì.
{26358}{26440}Podmínkou je udìlat dojem na Seiku-sama. Souhlasíš s tím?
{26440}{26470}Samozøejmì!
{26470}{26580}Jako Pøedstavitelka Spoleèenského Klubu si|nemyslím, e byste udìlaly nìjaká špatná rozhodnutí.
{26595}{26654}Fajn. Pojïme dovnitø.
{27100}{27119}Je to jen o èase, eh?
{27119}{27199}Arima-san! Dobrı veèer!
{27255}{27411}Dìkuji za návštìvu sto padesátého prvního plesu Akademie Shuuhou.
{27430}{27502}Jsem Pøedstavitelka Spoleèenského Klubu, Houjouin Seika.
{27524}{27588}Obèerstvení je v západní èásti budovy.
{27588}{27633}Prosím, neváhejte si ho uít.
{27655}{27738}Teï pro vás bude hrát školní Hudební Klub.
{27738}{27791}Prosím, dejte si na èas a uijte si hudbu.
{28849}{28913}Oh Teppei, teï jsi opravdu dobrı.
{28925}{28936}Opravdu?
{28936}{28955}Jo!
{28971}{29013}A tvá ruka je tak høejivá.
{29064}{29157}To byla ruka, která mì pøedtím zachránila, správnì?
{29228}{29272}Tak to je následník rodiny Arima, eh?
{29272}{29296}Je bájeènı!
{29316}{29366}Ale já jsem slyšela, e u má snoubenku!
{29366}{29387}Ale ne...
{29472}{29481}Proè...?
{29541}{29557}Jsem...
{29597}{29613}Seika-sama?
{29613}{29653}Necítíš se dobøe?
{29667}{29718}To je nemoné! Tohle nikdy!
{29743}{29798}Já...Houjouin Seika a on...?!
{29812}{29834}On je jen Arima...
{29936}{30097}Dìkuji, e jste pøišli na dnešní veèírek|organizovanı naší školou, Akademií Shuuhou.
{30115}{30135}Organizace tohoto veèírku|Zdá se, e je koneènì konec.
{30135}{30148}Organizace tohoto veèírku|Jo.
{30148}{30233}by nebyla úspìšná bez pomoci tìch, co se zúèastnili.|Dál uvidíme jaké rozhodnutí Houjouin udìlá.
{30244}{30289}Proto já, Houjouin Seika, Pøedstavitelka Spoleèenského Klubu,|Udìlali jsme, co jsme museli.
{30289}{30320}vám dìkuji z hloubi svého srdce.
{30377}{30389}Arimo.
{30400}{30470}dostateènì jsi mi ukázal vısledky svého tréninku.
{30486}{30575}V krátkém èase, jsi se nauèil ukazovat| dùstojnost po tobì poadovanou.
{30584}{30612}Dìlal jsi to dobøe.
{30626}{30668}Není to skvìlé, Teppei?
{30771}{30784}Ale!
{30855}{30914}Ale...musím øíct, e máš pøed sebou stále dlouhou cestu.
{30927}{31011}Eh? Ale všichni ho chválili!
{31011}{31137}Charlotte-san, mám dojem, e jsem jediná,|kdo rozhoduje jestli je kvalifikovanı nebo ne.
{31153}{31204}To je pravda...ale, myslím...
{31230}{31254}Arimo Teppei.
{31272}{31366}Jako student Akademie Shuuhou musíš|udìlat víc, ne navštìvovat veèírky.
{31377}{31423}Poøádat je je také dùleité!
{31441}{31523}Budeš poøádat veèírek pøíští tıden.
{31533}{31618}Podle toho, co uvidím na veèírku, se rozhodnu zdali|schválit nebo neschválit tvé èlenství v klubu.
{31646}{31681}Veèírek...?
{31713}{31759}Tím myslíš, e mám poøádat veèírek!?
{31813}{31884}Pøeklad + korekce + èasování: WelW(etkaAa)-hime|www.mycolorfullife.blog.cz
{32120}{32245}-V barvách rána a v noèním snìní,-
{32245}{32300}-jsme se smáli jeden na druhého.-
{32300}{32418}-Èas, kterı jsem strávila spoleènì s tebou,-
{32418}{32469}-byl tak plnı lásky.-
{32469}{32625}-Ah, ale od teï u tu nebude nic takového.-
{32625}{32807}-Chci se opìt shledat s tìmi vzácnımi dny, hned teï!-
{32807}{32833}-Sluncem jasnı den-
{32833}{32990}-Celı svìt pøetéká láskou.-
{32990}{33076}-Tak jestli je tu nìco nepøíjemného,-
{33076}{33157}-tak na to zapomeò.-
{33157}{33361}-Kvùli dalšímu sluncem jasnému dni a jasnému zítøku,-
{33361}{33444}-nezáleí na tom, jestli je tohle konec cesty.-
{33444}{33637}-Chci se jen postupnì pøesunout dopøedu.-
{33952}{33971}Jedna, dva,|Otázka!
{33971}{33993}tøi.|Co se dìje?
{33993}{34053}Jedna, dva, tøi.|Zajímá mì, kdy se znovu objeví Maria-chan?
{34053}{34096}Onii-chan, udìlejme to spoleènì!|Zdá se to jako by mìla pøijet pøíští tıden.
{34096}{34135}Pøíští Princess Lover!
{34135}{34164}Rùe a støevíc!
{34164}{34215}Tak jakı pøíbìh bude pøíští tıden?
{34215}{34242}Jedna, dva,|Bude to mùj pøíbìh!
{34242}{34274}tøi.|Ujistìte se, e jste na nìj naladìni!
