{1}{1}23.976
{49}{93}TaSHee's Gang uvádí
{225}{311}PRINCESS LOVER!
{3859}{3887}Proè?
{3887}{3942}Proè ho nemùu vypudit ze své mysli?
{3988}{4036}RÙE A STØEVÍC
{4184}{4217}Co je to?
{4217}{4346}Prototyp motorky speciálnì vyroben|jen pro vás Arima Motors Research Lab.
{4346}{4459}Ano. Slyšeli jsme, e Teppei-sama chtìl spolehlivou motorku.
{4459}{4532}Dali jsme do toho veškeré naše úsilí!
{4545}{4576}Spolehlivá motorka...
{4576}{4620}Zmínil jsem se o tom pøedtím?
{4652}{4673}Dobøe tedy.
{4690}{4738}Co jízda na spolehlivé motorce?
{4738}{4825}Mùj dìda je tak vynalézavı. Mùe vyrobit takovou vìc, správnì?
{4852}{4877}Myslím, e ano.
{4898}{4929}Vzpomnìl jste si?
{4939}{5008}Mluvila jsi vánì, kdy jsi øíkala "Myslím, e ano"?
{5008}{5108}Proè bych nemìla brát na vìdomí vaše slova?
{5108}{5151}Ne, samozøejmì nemùu.
{5151}{5187}Jsi tak jízlivá...
{5228}{5262}Je opravdu spolehlivá?
{5262}{5287}Samozøejmì.
{5287}{5342}Toto je vırobek totálního úsilí spoleènosti Arima!
{5342}{5430}Prosím otestujte ji, silnì kopnìte z boku.
{5430}{5460}Takhle?
{5460}{5475}Ano.
{5536}{5624}Hurá! Dokázali jsme to!
{5624}{5673}Je to docela nechutné. Nechci ji.
{5798}{5850}Øekni, Teppei. Pøemıšlel jsi nad nìèím?
{5850}{5884}Vùbec.
{5884}{5957}Mimo to, moc veèírkù jsem nenavštívil.
{5957}{6046}Vùbec nevím, jak nìjakı organizovat.
{6046}{6134}Ne jsi sem pøišel, vùbec jsi nenavštìvoval veèírky?
{6134}{6244}No, chodil jsem na narozeninové veèírky a na vánoèní taky.
{6244}{6281}To není špatné!
{6281}{6375}Víš, tyhle jsou jiné od tìch, které máš na mysli.
{6375}{6411}Jakı je v tom rozdíl?
{6436}{6491}Jsou úplnì odlišné.
{6491}{6510}Mimochodem,
{6529}{6592}Seika-san tu poslední dobou nebıvá.
{6592}{6651}Jako prezidentka by nemìla bıt nedbalá.
{6651}{6744}Nepøejeme si bıt zesmìšòovány neèleny,|kteøí tráví èas otálením v klubové místnosti.
{6744}{6793}Rozumíš, praseèí hlavo?
{6809}{6835}P-Prase?
{6851}{6950}Seika-sama je jedinou dcerou|Houma-dono, majitele velké agentury.
{6950}{7045}Je také èíslo jedna návrháø-vèetnì-modelu mezi všemi nováèky.|/to slovní spojení jsem vánì nikde nenašla... :(/
{7056}{7086}Ne, opravdu?
{7086}{7116}Nevìdìl jsi to?
{7116}{7177}Je to znaèka nazıvaná "Saint Rose".
{7177}{7211}Oh, o tom jsem slyšel.
{7211}{7250}Je to znaèka, která patøí rodinì Houjouin.
{7250}{7274}Opravdu?
{7274}{7309}To jsem vùbec nevìdìl.
{7309}{7357}Take, ona je vlastnì skuteènì úasná.
{7374}{7433}Má právo bıt povıšenìjší ne je.
{7433}{7533}Seika-sama se nikdy nebude chlubit svımi úspìchy.
{7533}{7609}To je pravda. Toto je dobrá vlastnost Seiki-san.
{7609}{7652}S tím souhlasím.
{7652}{7685}Jo.
{7685}{7765}No, kdy nebyla taková "hrstka", byl bych ji víc respektoval.
{7765}{7797}Co jsi to øekl?
{7808}{7888}Neøíkej takové kecy za mımi zády!
{7888}{7905}Mezu?
{7905}{7943}Ano madam, jsem tady.
{7943}{7995}Zítra na tebe spoléhám.
{7995}{8051}Je mi ctí vám bıt k slubám.
{8051}{8133}Vskutku, naše osudy jsou propleteny hvìzdami-
{8133}{8150}Boe.
{8150}{8252}Mùu si jen vypùjèit tohoto chlapíka ze Spoleèenského Klubu?
{8252}{8293}Jste skuteènì ohleduplná.
{8307}{8377}Prezidentko, jste opravdu charakteristická pro krevní skupinu AB-
{8377}{8505}Jestli øekneš takové vìci pøed kamerou, udìlám co budu moct, |abych ti znièila ivot, take je pro tebe lepší bıt oparnìjší!
{8517}{8560}Na co se koukáš, Arimo?
{8560}{8614}H-Heh, nedívám se na nic.
{8614}{8628}Meow-
{8628}{8704}To je škoda. Nepotøebuju od tebe ádnou pomoc.
{8704}{8771}Nechápu, o èem to mluvíš.
{8771}{8848}Proè ti musím oznamovat všechno, co dìlám?
{8848}{8907}Proè si na mì vdycky zasedne?
{8907}{8936}Máš pravdu.
{8936}{8963}Opravdu.
{8985}{9185}Vlastnì, jsem byl poádán, abych navštívíl módní pøehlídku|Saint Rose konající se zítra v hotelu Elgrand.
{9185}{9240}*Zvukové efekty*|Poèkejte prosím chvíli
{9240}{9321}Vydáváš zvuky jako by tì poádali, aby se's stal modelem.
{9321}{9351}Ne?
{9351}{9369}Ne!
{9387}{9474}Bude to jen interview po módní pøehlídce.
{9474}{9587}Druhá strana chce slyšet o mém školním ivotì|od jednoho z mıch spoluákù.
{9587}{9624}Spoluáci...
{9625}{9654}Myslíš toho kluka...
{9654}{9676}Nemám na vıbìr!
{9676}{9755}Nemám ádné obavy bıt pøedstavitelem tvého spoluáka.
{9755}{9793}Pøi této jedineèné ivotní šanci,
{9793}{9875}já, Mezu Haruhiko, odvedu vıjimeènı vıkon.
{9885}{9962}Oh opravdu? Pozdìji si projdu pøedpokládané otázky a vzorové odpovìdi.
{9962}{10002}Dostaneme je do tvojí hlavy.
{10002}{10049}Nemusíte o mì mít starosti.
{10049}{10082}Já, Mezu Haruhiko-
{10082}{10106}*Zvukové efekty*|Prosím poèkejte chvíli
{10130}{10162}Nemám starosti o tebe.
{10162}{10198}Bojím se o sebe.
{10231}{10249}Pøestaò se smát!
{10249}{10283}Oh, promiò!
{10361}{10470}Zajímá mì, proè mì Seika-san vidí jako trn v oku.
{10470}{10537}Vy, jste jí trnem v oku?
{10537}{10592}Nezdá se mi, e by to tak bylo.
{10592}{10636}Ne, je to pravda.
{10675}{10767}Nemyslím si, e mì doopravdy nenávidí.|Je to spíš tak, e nenávidí jméno "Arima".
{10783}{10809}Nemáš tušení proè?
{10809}{10866}Nemyslím si, e bych vám mohla dát dobrou odpovìï.
{10866}{10954}Myslím, e bude nejlepší, kdy se na to zeptáte dìdeèka.
{10969}{10994}Zeptat se mého dìdy?
{10994}{11009}Ano.
{11053}{11096}Mùu se ho zeptat teï?
{11114}{11175}Jestli je to vaše pøání, pak...
{11243}{11284}Mùete mì zavézt k bydlišti mého dìdy?
{11298}{11318}Rozumím.
{11454}{11494}Jak jde škola?
{11494}{11535}Jde všechno dobøe?
{11535}{11603}Nevím jestli jdou dobøe nebo ne,
{11603}{11658}ale stejnì, zaèínám ty záleitosi pomalu chápat.
{11658}{11689}Chápu.
{11735}{11789}Jak to jde s dcerou van Hossena?
{11804}{11829}Je to hodná dívka, ne?
{11829}{11910}Sylvie? Ještì opravdu nejsme pøipravení na manelství,
{11925}{11966}ale stali se z nás pøátelé.
{12005}{12049}Pøátelé, huh?
{12049}{12084}Jde to skuteènì pomalu.
{12084}{12142}Je to okay. Jdu svım vlastním tempem.
{12142}{12212}Take, proè jsi za mnou pøijel?
{12235}{12331}Nemyslím si, e jsi pøijel celou cestu, aby si's se mnou pokecal.
{12351}{12445}Víš o dívce jménem Houjouin Seika?
{12466}{12507}Houjouin...
{12775}{12801}Teppei-sama.
{12841}{12881}Právì to pøišlo.
{12881}{12915}To je fajn, ne?
{12915}{12939}Díky.
{13028}{13080}Nenávidí mì tak moc.
{13080}{13127}Jak jí to mám ukázat?
{13210}{13227}Omluvte mì.
{13227}{13324}Jak mrazivé ráno.
{13445}{13498}Mìl bych nosit bundu.
{13498}{13570}Tvùj hlas zní podivnì.
{13570}{13613}To není ta vìc.
{13613}{13672}Nachladil jsi se?
{13688}{13767}Jak je to moné?
{13767}{13850}Pravdìpodobnì jsem vèera zùstal vzhùru pøíliš dlouho.
{13862}{13942}A mé tìlo je trochu nepouitelné, to je všechno...
{13942}{13977}Nejen trochu, správnì?
{13977}{14030}ádné starosti.
{14030}{14128}Dnes je má ivotní šance-
{14249}{14275}Objevila se duha!
{14353}{14406}Chladno...Koleno...Bolí-
{14406}{14466}Neøíkejte mi, e je to náhlı vzrùst?
{14466}{14523}Já se bojím, Teppei-sama!
{14538}{14574}Myslím, e brzo dostanu horeèku.
{14697}{14764}Oh, škola konèí?
{14764}{14821}Dnešek utekl tak rychle!
{14821}{14861}To protoe jsi celı den spal.
{14901}{14963}Jestli brzo nepùjdu-
{15004}{15023}Umm...
{15023}{15070}Mám tì tam doprovodit?
{15070}{15091}Oh!
{15091}{15161}U je èas? Rozumím!
{15161}{15263}Prezidentka je hodnì dùvìryhodná a respektována celou|školou díky svému morálnímu charakteru.
{15263}{15340}Je jako ztìlesnìní andìla!
{15340}{15393}Interview ještì nezaèalo, víš.
{15416}{15427}Oh?
{15427}{15500}Kdy jsem se podíval na osobní profil její domovské stránky,
{15500}{15585}byl jsem udeøen bleskovım impulzem.
{15586}{15672}Lev. Krevní skupina AB. Rozenı vùdce.
{15672}{15744}Je naším vùdèím svìtlem!
{15744}{15834}Ona je jediná, která protlaèí novı svìt!
{16051}{16091}Proè se vìci takhle obrátily?
{16104}{16179}Ale nakonec mám šanci jí to ukázat. Není to tak špatné.
{16265}{16292}Princess Lover.
{16407}{16545}Všichni, dìkuji, e jste pøišli na módní pøehlídku Saint Rose.
{16571}{16622}Jsou zde pohromadì procítìné sezónní návrhy.
{16622}{16745}My, Saint Rose, pøedstavujeme "jaro" všem našim enskım pøítelkyním!
{16745}{16831}Prosím uijte si "jaro" na našich okouzlujících sleènách-
{16908}{16929}Arima?!
{16995}{17075}Všichni, uvidím vás potom!
{17108}{17142}Proè jsi tady?
{17142}{17186}No, Mezu-kun...
{17186}{17228}se zaèal cítit špatnì a zkolaboval.
{17228}{17261}MEZU!
{17261}{17336}Nebyl èas najít náhradu, tak...
{17336}{17383}Nebyla jiná monost, tak jsem pøišel!
{17431}{17451}Houjouin-san.
{17451}{17494}Je èas. Pojïte prosím na pódium.
{17494}{17528}Oh dobøe.
{17528}{17589}Zastoupíš Mezua.
{17589}{17628}U mì je to v poøádku.
{17628}{17661}Ale co mi chceš øíct?
{17661}{17681}Houjouin-san?
{17681}{17710}Jsem na cestì.
{17710}{17763}Není èas na diskuzi.
{17763}{17791}Nechám to na tobì.
{17791}{17859}Jestli to zpackáš, jsi synem smrti.
{17859}{17894}"Jestli to zpackám", huh?
{17894}{17922}Houjouin-san!
{17922}{17962}Okay. Hned se pøevleèu.
{17962}{17990}Um- Hej!
{18156}{18192}Strašnì se omlouvám!
{19031}{19059}Omlouvám se, e jsem vás nechala èekat.
{19081}{19150}Omlouvám se za tak nerozumnou ádost.
{19150}{19222}Je to kvùli všeobecné ádosti ètenáøù.
{19247}{19367}Toto bude speciální vıjimka.|Nemohu nakonec ignorovat návrh od John-John.
{19367}{19444}Pro doplnìní zprávy o této módní pøehlídce,
{19444}{19529}bych ráda vìdìla nìco o vašem soukromém ivotì.
{19529}{19557}Omluvte mì.
{19557}{19607}Mohu vás vyfotit?
{19607}{19628}Jistì.
{19773}{19821}Zdá se, e je ve fotoaparátu hmyz.
{19967}{20000}Omlouvám se za to.
{20000}{20084}Arima-san není pøíliš zvyklı na takové situace.
{20084}{20122}Ne, já bych se spíše mìla omluvit.
{20122}{20214}Arima-san, prosím omluvte mì za to, e se vás tolik ptám.
{20237}{20280}To je naprosto v poøádku, opravdu!
{20297}{20375}Pak tedy zaèneme s interview.
{20375}{20414}Podívejme. Arima-san?
{20414}{20431}Ano!
{20445}{20607}Slyšela jsem, e Houjuoin-san je pøedstavitelkou |tradièního Spoleèenského Klubu v Akademii Shuuhou?
{20607}{20637}Eh, jo.
{20695}{20769}Ano, je opravdu vıjimeèná.
{20769}{20828}Oh, tvá slova oplıvají mravy.
{20828}{20864}Kdy pøestaneš kopat?
{20864}{20958}Arima-san je také ve Spoleèenském Klubu?
{20958}{20973}Huh?
{20989}{21031}Oh, já...
{21031}{21064}Já jsem...
{21064}{21114}Stále ještì nejsem schopnı.
{21114}{21171}Ještì jsem nezískal souhlas od Seiki-san.
{21206}{21335}Oh, ne! Vydáváš zvuky jako bych tì odmítla, ne?
{21335}{21439}Nicménì, pro nás a také pro ètenáøe,|není tento klub pøíliš známı.
{21439}{21510}Co obvykle Spoleèenskı Klub dìlá?
{21528}{21567}Oh, Spoleèenskı Klub...
{21567}{21584}No...
{21619}{21675}Jako zástupce studentù,
{21675}{21733}na nì dáváme pozor.
{21733}{21828}Nìkdy, jednáme jako "bliníci",
{21828}{21885}necháváme uèitele vìdìt, co si studenti myslí.
{21885}{21935}Je Spoleèenskı Klub nìco jako Studenstká Unie?
{21935}{22035}Ne, Spoleèenskı Klub nakonec nemá opravdovou moc.
{22035}{22114}Je to nìco jako školní symbol.
{22114}{22143}Chápu.
{22143}{22295}Arimo-san, jakı dojem dìlá Seika-san ve škole?
{22309}{22343}Dojem?
{22396}{22457}Bìhem klubovıch aktivit,
{22457}{22537}s ní pravdìpodobnì pravidìlnì pøicházíte do kontaktu.
{22537}{22605}Ráda bych vìdìla, jakı je váš pocit z ní.
{22605}{22658}Chápu!
{22658}{22779}Seika-san je typ "sklapni a pojï se mnou!".
{22823}{22868}Ne, to opravdu nic není.
{22917}{22948}Umm...
{22988}{23061}Tím myslíte, e je nìkdo, kdo |všechny motivuje, aby se pohnuli vpøed?
{23061}{23172}Ale nìkdy, to pøehání a zaène spor.
{23229}{23307}Ale nakonec, stále následujeme Seiku-san.
{23326}{23411}To protoe víme, e svou práci bere opravdu vánì.
{23448}{23496}Není zaujatá vùøi osobním ziskùm nebo prohrám,
{23496}{23558}jen se zamìøuje na svou povinnost.
{23582}{23639}Lidé neøíkají èasto vìci jako "pojï se mnou!".
{23652}{23694}Ale, Seika-san to øekne.
{23694}{23795}To protoe vìøí, e nás vede správnou cestou.
{23812}{23893}A, má schopnost, aby ji lidé kolem ní respektovali.
{23909}{23976}Je to studentka, ještì v ten samı èas |pracuje také jako návrháøka a modelka.
{23994}{24047}I tak, nakonec není arogantní.
{24376}{24437}AUUUU!
{24452}{24483}Jsi tak odpornı.
{24483}{24538}Otázka byla poloena bez pøedvídání.
{24538}{24614}Ale ty jsi tak zklamal.
{24614}{24660}Promiò.
{24721}{24748}Co se dìje?
{24748}{24775}Nemáš chu?
{24803}{24836}Slyšel jsem o tvé situaci.
{24836}{24853}Situaci?
{24864}{24968}Dùvod, proè tak moc nenávidíš rodinu Arima.
{25054}{25176}Houdou, reklamní agentura ovládaná rodinou Houjouin,
{25176}{25249}byla pùvodnì pøiøazená k Arima Financial Combine.
{25249}{25302}Byla zodpovìdná za plánování akcí a dalších souvisejících vìcí.
{25331}{25359}Bìhem skvìlého vzestupu ekonomiky,
{25375}{25467}se mùj dìda stal posedlı svou prací a zanedbával svou rodinu.
{25488}{25553}Bıt opuštìnı, jeden by se urèitì cítil osamìle.
{25585}{25677}A tak, jeho manelka mìla pletky s dìdou Seiki-san.
{25705}{25786}Kdy ty pletky prokouknul, zahnal svou enu pryè.
{25809}{25874}Poté, odøízl všechny pouta s Houdem.
{25920}{25941}Vìdìla jsem to.
{25941}{25994}Slyšela jsem tu historku u mnohokrát.
{26007}{26045}Jakı je smysl toho, e to teï vytahuješ?
{26066}{26216}Slyšel jsem, e jsi chtìla prodat svou znaèku|Arima Megastores, ale byla jsi hanebnì odmítnuta.
{26232}{26283}To je všechno kvùli tomu starému bláznovi.
{26302}{26416}Øíkat vìci jako "podøadné obchody vedené malou holkou|budou jen sniovat povìst Arima Megastores".
{26451}{26537}Vlastnì takové vìci prohlašoval do celostátních prohlášení!
{26754}{26862}Kdy u rodinu Arima pustí záš vstøíc nám?
{26862}{26938}Nakonec, je to všechno chyba tvého dìdeèka.
{26957}{27025}Oko za oko. To je mùj styl.
{27038}{27141}Budu oznamovat jeho pošetilost celému svìtu!
{27156}{27195}Opravdu to plánuješ udìlat?
{27195}{27219}Ano.
{27241}{27296}Myslet na hanbu, trpìla jsem.
{27296}{27372}Neustoupím tomu starému hlupákovi!
{27505}{27528}Co je to?
{27561}{27594}Prosím podívej se.
{27747}{27799}Poradce - Arima Teppei?
{27825}{27863}Vèera jsem usilovnì prosil svého dìdu
{27863}{27904}a v poledne jsem se stal øeditelem.
{27925}{27973}Co jsi tím myslel?
{27989}{28093}Mùj dìda lituje toho, co udìlal tvému dìdeèkovi.
{28108}{28193}Ale, tohle se stalo dávno. Je nemoné se omluvit.
{28209}{28310}Navíc, kdy se plány vedoucího finanèní skupiny tak lehce mìní,
{28310}{28360}povìst celé skupiny bude ovlivnìna.
{28390}{28454}Take, mùeme tento spor ukonèit?
{28503}{28559}Potom, co jsem se dozvìdìl o tom, co se stalo v minulosti,
{28572}{28637}jsem zaèal pøemıšled nad tím, co bych mohl udìlat.
{28637}{28679}Po tom všem, jsem se cítil neklidnı.
{28698}{28782}Byl jsem tebou nenávidìn kvùli vìcem, o kterıch jsem nevìdìl.
{28802}{28905}Provdìpodobnì by to zatíilo velkoobchodní zamìstnance,
{28918}{28937}ale, takhle-
{28962}{29037}Takhle, bude tvá znaèka prodávána v našich velkoobchodech.
{29127}{29145}Jsi idiot?
{29172}{29187}Dobrá!
{29187}{29231}Souhlasím s tím.
{29245}{29296}Chci slevu na poplatky cokoliv-si-poádáš!
{29331}{29375}Spoléhám na tebe, Pane Øediteli.
{29421}{29442}Dobøe.
{29442}{29534}Mimochodem, nemyslím si, e jsem ti za tohle vdìèná.
{29550}{29617}Stále musíš organizovat veèírek.
{29617}{29659}Jaj. Myslel jsem si to.
{29673}{29794}Nakonec, bys to nemohl udìlat bez pomoci svého dìdy.
{29810}{29845}No, myslím e ano.
{29866}{29897}O tıden víc.
{29897}{29963}Veèírek musíš organizovat ty!
{29986}{30007}Dobøe.
{30223}{30255}Díky za tvou dnešní tvrdou práci.
{30255}{30347}Chci ti podìkovat zvláštì za to, e jsi  mì pøišel zachránit.
{30566}{30604}Jsi úasnı, Teppei!
{30623}{30676}No tak, nelep se na mì tak najednou.
{30676}{30715}Aèkoli to bylo ponìkud prudké,
{30715}{30777}nakonec jsi ukonèil dlouhotrvající spor.
{30795}{30857}Za takovıch okolností jsem byl pøinucen vstoupit do toho svìta.
{30873}{30984}Zaèal jsem cítit, e jsem moná schopnı udìlat i víc vìcí.
{30984}{31026}Máš pravdu, Teppei!
{31026}{31085}To musí bıt takzvanı "smysl pro uspokojení"?
{31085}{31143}Ale, stále musíš udìlat to nejlepší pro ten veèírek!
{31143}{31198}Oh, máš pravdu...
{31680}{31695}Okay!
{31825}{31869}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31890}{31930}www.mycolorfullife.blog.cz
{33947}{33973}Mám otázku!
{33973}{34015}Co je "moèová hra"?|/taky se tomu divím, nedivte se :D/
{34015}{34031}Eh?
{34064}{34131}Umm... Co je "moèová hra"?
{34146}{34177}Pøíští Princess Lover!,
{34177}{34204}Západ slunce a Ruské kolo.
{34204}{34244}Hej, co je "moèová hra"?
{34244}{34274}Tìšte se na to!
