{1}{1}23.976
{82}{110}Mario-chan!
{117}{172}Nechoï! Mario-chan!
{215}{255}Prosím postarej se o mého otce a sestru.
{324}{343}Mario-chan!
{369}{446}Pitomı fracku! Seer si to!
{944}{986}To je úasné, Mario-chan!
{1002}{1052}Svi, Falcon Crystal!
{1073}{1096}Pøiprav se!
{1096}{1124}Teï to zkonèí!
{1441}{1480}Pøekvapilo vás to, gentlemani?
{1480}{1550}Vdycky jsem chtìl jednou vyzkoušet tohle uvedení.
{1550}{1579}S kım to mluvíš?
{1579}{1647}Ah, zajímá mì, s kım to mluvím...?
{1647}{1673}Neptej se mì.
{1673}{1783}Jsem si jistı, e byste rádi vìdìli, jak jsem na to pøišel, e?
{1794}{1839}Dovolte mi to trochu pøetoèit zpìt.
{1853}{1890}Jakl jsem øekl, s kım to mluvíš?
{1941}{1962}Co se dìje?
{1975}{2038}Jen jsem dostal nápad na veèírek, kterı organizuju!
{2038}{2058}Opravdu?
{2095}{2164}Aby se všichni bavili. Zorganizuju veèírek,|kterı ještì nikdo nezorganizoval.
{2180}{2297}Dobrá, jen mì sleduj! Zorganizuju|úasnı veèírek a všechny pøekvapím!
{2334}{2382}Je to...veèírek?
{2382}{2459}Skvìlé, to je prostì skvìlé! U se tìším, a pøijdu!
{2516}{2562}To ti je opravdu podobné, Teppei-dono.
{2562}{2579}Aha.
{2605}{2645}Eh? Strávíme noc?
{2645}{2679}P-Poèkej chvíli!
{2679}{2702}P-Program...
{2726}{2795}Budu taky pozvanı, správnì?
{2847}{2926}PÁRA, PLÁÈ A ŠASTNİ PERVERZÁK
{3019}{3050}Je tu tolik lidí.
{3050}{3114}Máš pravdu. Zajímá mì, jestli ijí v zahranièí.
{3114}{3178}Jak jsem øekla, vrátím se zítra!
{3178}{3212}Budu v poøádku!
{3252}{3281}Okay, zkouška.
{3295}{3325}Dobré ráno vám všem.
{3325}{3413}Jsem Arima Teppei, hostitel tohoto veèírku.
{3430}{3592}Ti z vás, dnes shromádìni |budou ubytováni spoleènì v horkıch pramenech.
{3592}{3648}Rád bych, aby si všichni odpoèinuli jak to dìlají obyèejní lidé.
{3658}{3691}Teppei-dono! Mám otázku.
{3691}{3726}Ano, van Hossen-san.
{3746}{3835}Nemám ádné námitky, ale proè horké prameny?
{3858}{3907}Není to trochu podivné na veèírek?
{3946}{3963}To je...
{3979}{3997}"To je"?
{4039}{4134}Jen jsem cítil, e bych mìl udìlat nìco speciálního.
{4134}{4162}"Speciálního"?
{4162}{4184}To je správnì.
{4204}{4235}Ah, ne!
{4249}{4280}To se nebude hodit!
{4280}{4339}N-Na místì jako je tohle...
{4346}{4354}J...
{4365}{4380}Jak...
{4409}{4434}Jak tímhle projdu?
{4448}{4492}Jak dlouho by mìl trvat náš vstup?
{4509}{4531}Co to dìlají?
{4531}{4621}Nemyslím, e by nìkdy pøedtím pouivaly vchod na nástupištì.
{4638}{4664}Celebrity...
{4891}{4909}Oh!
{4909}{4928}Úasné!
{4943}{5041}Cestuju docela èasto, take tohle není ádnı problém.
{5066}{5099}Jak oèekávané od Seiki-sama!
{5099}{5175}Vaše tváø, kdy jste procházela skrz bránu, byla tak nádherná!
{5175}{5244}Jestli ta holka jedná tak vyzıvavì jen pøi jediném prùchodu,
{5244}{5316}pak bych mìl bıt Prezident pro objednávání rezervace jízdenek.
{5316}{5417}Kaisuke? Prezident nastupuje do vlaku jako Kaisuke?
{5514}{5596}Seika-sama, vyfote se se mnou. Ah, úasné!|/Seiko-sama, jízda vlakem je tak bájeèná!/
{5623}{5683}Jsi docela klidná, e, Charlotte-san?
{5683}{5749}Docela jsem v mé zemi vypomáhala.
{5764}{5810}Kvùli tomu, jsem docela èasto jezdila na cesty.
{5810}{5880}Hmm? To vypadá neoèekávanì jako prostı obèan.
{5880}{5978}Co Chalr øíká je to, e èasto cestovala pøes |kontinent jako posel královské rodiny.
{5978}{6045}Ty jsi cestovala jako posel královské rodiny?
{6056}{6133}Vsadil bych se, e jízdenka cestujících stojí majlant!
{6133}{6174}Budu mít hovìzí.
{6182}{6191}Ano.
{6211}{6264}Jestli je to dùvod, znamená to, e |nemùeš jíst nic jiného jen cibulovı ramen?
{6264}{6353}Není to "nezu", ale negi!"|/negi - jarní cibulka; omlouvám se za pøetvoøení jména na Mezu, ale|na zaèátku se mi v titulkách objevoval jako Mezu, ale ve skuteènosti |je to Nezu, take pardon, buï neumím èíst, nebo nevím ;)/
{6400}{6443}Hej, u to zaèíná?
{6462}{6503}Stále mám toho tolik co øíct!
{6503}{6551}S kım to mluvíte?
{6551}{6645}TaSHee's Gang uvádí|PRINCESS LOVER!|/S kım to mluvíte?!/
{6664}{6801}-Stojící sama, šeptala jsem, "Pojï a povzbuï mì!",-
{6815}{6915}-a slzy stékají jak vzdychám.-
{6948}{7157}-Necítím se tak trapnì, abych se sama pokusila otevøít dveøe.-
{7229}{7363}-Leštìná kousek po kousku, budu skvostnìjší, ne šperk,-
{7363}{7539}-chci záøit a tanèit dnes veèer u waltzu!-
{7556}{7700}-Nejlesklejší partner pro tebe, mùj nejlepší partner jsi ty.-
{7700}{7834}-Necítíš to stejnì? Chci to potvrdit, ale mùj hlas se chvìje...-
{7834}{7984}-Zavírám oèi a podávám ti ruku,-
{7984}{8142}-a èas se zastavil. Teï, pojï, co chceš dìlat?-
{8183}{8421}-Je to jen na tobì! Nakonec, u jsem zprostøedkovaná, ne?-
{8884}{8944}Toto je dámskı pokoj pro hosty.
{9000}{9060}Úasné! Jak japonské!
{9060}{9115}Ano, jsem trochu znepokojená...
{9139}{9171}Hmm.. Je to jak-tak.
{9200}{9244}Pánskı pokoj je tudy.
{9272}{9300}Poèkej!
{9329}{9377}Yuu-san, proè mì následuješ?
{9377}{9468}Eh? Mùj pokoj ještì nebyl oznámenı.
{9485}{9520}Teï bylo rozhodnuto.
{9532}{9595}Tudy...tvùj pokoj je tudy.
{9595}{9609}Eh?
{9625}{9652}T-To je...
{9669}{9732}Teppei-sama, jsem jen sluebná.
{9732}{9815}Nemìla bych sdílet pokoj s tìmi ze Spoleèenského Klubu.
{9826}{9854}Be, teï.
{9854}{9988}ádné otravování s tím a buï schopná|se bavit a  vycházet s ostatními,
{9988}{10017}to je to, o èem je mùj veèírek.
{10050}{10067}A-Ale...
{10087}{10131}Mimo to, zarezervoval jsem jen dva pokoje.
{10156}{10193}V tomto pøípadì bychom rádi zùstali v tom samém pokoji.
{10193}{10224}T-To je...
{10224}{10249}Teï rozumíš?
{10266}{10338}Mimo to, co tvùj pán øekne je bezpodmíneèné, správnì?
{10352}{10385}To není fér, Teppei-sama.
{10385}{10428}Dovolávat se své autority v dobu jako je takhle...
{10440}{10467}Øekl jsem, e to bude fajn.
{10541}{10582}A tak to je.
{10582}{10622}Jak jsem øekl, s kım to mluvíš?
{10666}{10709}Dokonèil jsem svou zprávu.
{10725}{10762}Pøísahám, e tì nìkdy nechápu...
{10853}{10867}Arima-sama.
{10867}{10889}Arima-kun.
{10902}{10918}Arima-kun.
{10934}{10983}Tohle je úasnı veèírek.
{10983}{11024}Ano. Jak se chlapci cítíte?
{11038}{11156}Nikdy jsem nesnil o zaití takové objevné cesty!
{11156}{11203}Jak se dalo èekat od rodiny Arima.
{11203}{11234}Vaše srdce je pøekvapivì milé!
{11286}{11384}Bıt schopnı se stıkat s ostatními bez pravidel a kritiky
{11397}{11431}je to, o èem mùj veèírek je.
{11450}{11480}Jízda rychlovlakem,
{11498}{11545}jíst místní kuchyni,
{11568}{11623}horké prameny, které oèistí tìlo i duši.
{11646}{11661}A...
{11678}{11693}..."to".
{11730}{11743}Arima-sama.
{11743}{11755}Co je?
{11774}{11842}Necítíte se trochu hloupì udìlat "to"?
{11842}{11941}Budu v poøádku. To proto jsem vás poádal o asistenci pøi "tom".
{11953}{11976}"To" bude v poøádku.
{11976}{12024}Oh, sláva "tomu".
{12024}{12100}Stále, Arima-kun. "To" je zloèin, ne?|/co jim to chcou proboha dìlat?! :D/
{12100}{12190}Je pravda, e to záleí na názoru ostatních,
{12190}{12260}mohlo by se to samozøejmì zdát jako zloèin.
{12260}{12313}Mezi tìmi, co jsou zde,
{12327}{12423}urèitì vypadáme jako nejvhodnìjší lidé k obvinìní, ne?
{12423}{12535}Jak jsem si myslel. Pravdìpodobnì dìlat pohyb bez|porozumnìní druhé strany je špatnı nápad?
{12547}{12588}Bude to v poøádku. Jen to nechte na mnì!
{12606}{12659}Ah, to znamená...
{12688}{12729}Jsem "šastnı Perverzák"!
{12729}{12817}Tyto malé detaily jsou pro mì nic.
{12837}{12869}Neeee!
{12897}{12994}Ah, pardon, pardon. Pøišel jsem sem náhodou.
{13034}{13100}Boe Teppei, ty zvrhlíku...
{13117}{13204}Jak nenapravitelnı chlap.. jen pro tentokrát, okay?
{13225}{13305}Teppei-kun? Myslím, e tomu není pomoci, správnì?
{13320}{13349}Správnì!
{13370}{13449}To je pravda...bylo to jen náhodou.
{13476}{13511}Omlouvám se, všichni!
{13552}{13594}Opravdovı, "šastnı perverzák"!
{13607}{13701}Arima-sama! Prosím sdílejte svùj osud a moc se mnou!
{13701}{13802}Nemám ádnı nápad, jak to udìlat, ale nìjak to zkusím!
{13837}{13863}Jaaaaaaj!
{13877}{13926}Pouijte 70% a já pouiju 30%.
{13941}{13983}Ne, bylo by to proti mım principùm.
{13983}{14003}Bude to fifty-fifty.
{14019}{14083}Dnes veèer, se ty a já staneme Dvojitımi Šastnımi Perverzáky!
{14084}{14116}Nezu-kun, to není fér.
{14116}{14185}Pak tedy, chceme bıt Šastní Perverzáci!
{14185}{14239}Dobrá!
{14259}{14335}Vana pod širım nebem. Orientální styl je úasnı!
{14335}{14398}Jestli se Teppei a ostatní podívají, ubijeme je k smrti, okay?
{14411}{14431}Bude to jistá smrt.
{14431}{14463}Explozivní smrt.
{14480}{14503}Bude to masakr.
{14532}{14583}Máš to vdycky s sebou?
{14583}{14610}Samozøejmì.
{14619}{14682}Fujikura-san je tak vydìšená, e se schovává v rohu!
{14713}{14800}Myslela jsem, e to bylo proto, e byla najednou |osvobozená od svıch povinností sluebné.
{14800}{14851}Yuu-san, pojï sem!
{14928}{14951}Horké prameny, jo?
{14965}{15014}To je poprvé co navštìvuju horké prameny s pøáteli.
{15014}{15038}Opravdu?
{15038}{15124}Myslím, e bys na to mìla zapomenout a tam vstoupíš.
{15149}{15163}Proè?
{15163}{15191}Proè, øíkáš...?
{15327}{15375}Je to opravdu v poøádku?
{15401}{15479}Dnes bezáleí na tom, jestli jsi šlechtièna nebo vznešená, nebo sluebná.
{15479}{15525}Jsme mezi dìvèaty, tak pojï!
{15546}{15581}Buïme hrubé!
{15581}{15629}Nemyslíš, "pojïme zrušit kategorie"?
{15643}{15706}Nicménì, tento meè je pıcha mé zemì...
{15706}{15759}Dìlej jak chceš, ale stále je to dost divné.
{15759}{15779}Jsi jako Razoku.|/V manze Nihou no Razoku skupina se skupina|nudistù pokusila pøevzít Japonsko silou zbraní./
{15790}{15809}Razoku?|/V manze Nihou no Razoku skupina se skupina|nudistù pokusila pøevzít Japonsko silou zbraní./
{16254}{16268}Úasné!
{16341}{16409}Seiko-san, tvoje vlasy vypadají |pøirozenìji, kdy je máš spuštìné!
{16409}{16474}Opravdu? Nemám to moc ráda.
{16491}{16528}Opravdu? Myslím, e to vypadá skvìle!
{16528}{16594}Cítím to stejnì. Obdivuju tvoje tmavé vlasy.
{16611}{16715}Naopak je to taky pravda. Japonci|obdivují ty se zlatımi a støíbrnımi vlasy.
{16715}{16775}Obì strany si nakonec pøejí tak moc.
{16797}{16827}"Pøejí tak moc," huh?
{17209}{17288}Máš krásné, štíhlé tìlo! Chceš bıt modelka?
{17288}{17322}Ah, mùu?
{17322}{17392}Jsi tak lstivá, Eriko! Pozvìte mì taky!
{17428}{17475}To je vıluènì pro ty s malımi prsy!
{17499}{17562}To je strašné, neodpustím ti...
{17592}{17647}Ah! Omlouvám se, Ayano!
{17667}{17751}Silvie, mìla jsem vùèi tobì velké nadìje!
{17765}{17841}Opravdu? Ty taky, Charl.
{17841}{17886}Ani trochu jsi se nezmìnila.
{17921}{17981}Co se dìje? Proè jsi tak napjatá?
{17995}{18019}Ah, ale...
{18031}{18100}Je to okay. Není tu èeho se bát.
{18123}{18162}Nìco takového.
{18179}{18222}Jsi maniak.
{18240}{18273}Dost jsem o tom pøemıšlel, ale poslouchejte!
{18273}{18313}Realita leí za touto zdí.
{18313}{18376}Uijeme si nejdøív jejich hlasy?
{18376}{18419}Ten kluk je taky maniak...
{18445}{18538}Charl, nejsou trochu velké? Jsou|tøikrát vìtší, ne si pamatuju...
{18538}{18585}Neeee! Nejsou!
{18622}{18683}Fujikura-san, máš dobré proporce!
{18683}{18748}N-NE, ne opravdu...
{18748}{18789}Mùu se jich dotknout?
{18873}{18927}T-Takové slova...chováte se dneska dost divnì...
{18985}{19054}U to nemùu vydret! Nechte mì jít!
{19071}{19098}Poèkej! Nevbìhni tam takhle!
{19160}{19187}Ta-Takhle...!
{19391}{19409}/Na jeho èele "blbec"/
{19495}{19593}Dosáhl jsem konce. Zbytek nechávám na vás.
{19633}{19684}Nemohl by se stát šastnım perverzákem.
{19702}{19716}Zasalutujme!
{19778}{19834}Jak jsem si myslela, pøinést mùj meè s sebou bylo správné rozhodnutí.
{19834}{19888}Hmpf, vsadím se, e to bylo celou dobu jejich cílem.
{19906}{19985}Je to okay, ne? Tam je trochu mlhy...
{20004}{20034}Zajímá mì, jestli se zkazí poèasí?
{20051}{20114}Pøedpokládá se, e bude celı den jasno.
{20128}{20161}Nezaèíná bıt chladno?
{20173}{20208}Mohla by to bıt pravda.
{20234}{20301}No, poèasí na horách se mìní rychle.
{20429}{20514}Na další operaci se dáme oklikou. Pøipravte se.
{20533}{20562}Kapitáne, mám otázku!
{20562}{20594}Jistì, poslouchám.
{20608}{20700}Ano! Proè máme kadı obleèenı jen ruèník?
{20700}{20768}U je podzim a je chladno!
{20768}{20821}Také se obávám, e se bude brzy stmívat!
{20841}{20923}Toto je spoleèenskı bojovı odìv! Jestli je ti chladno, skoè do vany!
{20923}{20952}Toto uzavírá schùzi!
{20952}{20967}Ano, pane!
{20985}{21022}Mám taky otázku!
{21022}{21056}Dobrá, poslouchám!
{21056}{21190}Kdy jsem se najednou stal hlavní postavou její jméno|zùstává neznáme, budu tentokrát obì?
{21190}{21255}Máš pravdu! Rád pro nás poloíš ivot!
{21255}{21271}Ano pane!
{21421}{21435}Kapitáne!
{21435}{21461}Co se dìje?
{21461}{21535}Odírám si bradavky, bolí to!
{21535}{21621}Imbecile! Kdy to øekneš, všichni ztratí dùvìru!|/tak je na nìj podívej, jak ho to chudáka bolí... :D/
{21621}{21633}Podívej.
{21672}{21688}U jsme skoro tam.
{21773}{21784}Huh?
{21860}{21936}Kapitáne, mlha houstne!
{21973}{22042}Máš pravdu! Taky jsem si myslel, e to bylo divné. Je to pravdìpodobnì...
{22056}{22079}Pravdìpodobnì...?
{22100}{22159}Tvùj èas brzy nastane.
{22218}{22278}Aha... Myslel jsem, e to moná bude...
{22341}{22365}Aaaah!
{22392}{22495}Myslím, e jsem se mohl dostat tak daleko. Zbytek nechávám na vás.
{22513}{22553}Aaaah!
{22581}{22681}Nezu-kun...nemùeme nechat jejich obìti pøijít nazmar! Pojïme!
{22800}{22836}/Naše nejhlubší omluva/|Spadl.
{22893}{22917}Aaaaah!
{22917}{22995}Jakmile se to otoèilo, Nezu spadl.
{23028}{23185}Aby nedošlo k vyrušení Teppeie, pravdìpodobnì |zadroval vıkøik a tiše spadl.
{23225}{23330}Ten zbabìlı Nezu nìco sdìlil Teppeiovi.
{23341}{23447}/Naše opravdu nejhlubší omluva.../|Nìco uvnitø nìj vykøiklo, "Pokraèuj! jdi dál!"
{23475}{23570}"I kdy nedosáhneš konce, musíš padnou stateènì."
{23663}{23690}Ah! Padající hvìzda!
{23690}{23734}Kde je, Charlotte-sama?
{23790}{23820}Padající hvìzda, eh?
{23843}{23882}Chceš si zkusit nìco pøát?
{23882}{23906}Pøání?
{23906}{24001}Øíká se, e kdy pøedneseš své pøání tøikrát|smìrem k padající hvìzdì, stane se to skuteèností.
{24022}{24054}Ah! Další!
{24256}{24344}Jak staøí vlastnì jste? Nejste studenti vyšší støední!
{24344}{24422}Vánì. Byly jste chyceni pøi èinu.
{24422}{24449}Páchnou.
{24449}{24469}Prasata.
{24484}{24582}Teppei-sama, kdybyste se zeptal,|kdykoli bych vám ukázala...
{24606}{24674}Stále, jsou pìknì odvání, e?
{24674}{24713}Co myslíš tím "odvání"?
{24713}{24758}Budete tu sedìt a do zítøejšího rána!
{24758}{24780}Eh?
{24780}{24819}Máte nìjaké námitky?
{24819}{24836}Ne.
{24836}{24952}Seika-san, dokud jsou všichni tady,|nemìly bychom plıtvat takovou šancí.
{24952}{24967}Ale...?
{24970}{24985}Okay?
{25039}{25110}Fajn. Kdy na tom trváš.
{25158}{25305}Jestli vyhrajete tuhle hru, já, Houjouin Seika, pøedstavitelka|Spoleèenského Klubu, se pøed vámi skloním.
{25318}{25407}Avšak, Houjouin...Tuhle vìc jsem pøedtím nikdy nedìlala.
{25423}{25463}Nehrála jsi tenis?
{25483}{25527}Hmmm...Pamatuju si, jak se hrál.
{25536}{25627}Tohle je to, èemu se øíká....Stolní Tenis!
{25670}{25733}Arima-san, ukate nám pìknou show!
{25733}{25784}Proè hrajou Teppei a Silvie?
{25800}{25830}Teppei má  moná víc síly,
{25842}{25952}ale Silvia zøetelnì lépe ovládá techniku a rychlost.
{25964}{26019}Øekni, je v poøádku, kdy hrajeme obyèejnı stolní tenis?
{26036}{26070}"Obyèejnı stolní tenis"?
{26086}{26169}Je mi to jedno. Bez ohledu na to jak|hrajeme, moje vıhoda se nemìní.
{26169}{26181}Velmi dobøe.
{26209}{26247}Bez dalších okolkù, zaènìme tento souboj.
{26357}{26394}Ah! Vincent-san!
{26427}{26470}Ah! Takové podvádìní!
{26522}{26633}Tohle je "obyèejnı stolní tenis". Jestli ho|shledáš nesnesitelnım, proè nešvindlovat?
{26690}{26751}Velmi dobøe, pùjdou ven!
{26797}{26813}To je podvádìní!
{26813}{26843}Co je?
{26843}{26917}Ne, to nic. Mùeme pokraèovat?
{27521}{27636}Nevím proè, ale mám náhlé nutkání|obejmout tyhle kluky pøede mnou...
{27715}{27741}To je tak divné...
{27762}{27892}Nespala jsem s nikım jinım od té|doby, co jsem vyrostla.
{27905}{27923}Já taky.
{27923}{28012}Vyrostla jsem v sirotèinci, tak je pro mì tohle normální.
{28032}{28045}Opravdu?
{28045}{28134}Aèkoli, u je to nìjakou dobu, co jsem šla|do postele v takové zábavné atmosféøe.
{28150}{28196}Jaké to bylo? Teppeiùv veèírek, myslím.
{28208}{28249}Nakonec to není veèírek.
{28270}{28317}Avšak, uila jsem si to.
{28332}{28388}Pak tedy, vstup Teppeie-sama do klubu...?
{28407}{28507}Formálnì udìlám oznámení oficiálního pøijetí pøíští tıden.
{28521}{28574}Vidím, e u jsi docela pøátelská, Houjouin.
{28574}{28613}To...
{28634}{28660}...moná je to pravda.
{28678}{28729}To musí bıt vliv toho prasete.
{28745}{28818}Jistì se zdá, e se Seika-sama trochu zmìnila.
{28833}{28938}Teppei je tak záhadnı, pøivést nás sem takhle spoleènì.
{28938}{29124}I kdy to nechci pøipustit, jsem ráda, e Arima |vyøešil záleitost, která mì znepokojovala tolik let.
{29138}{29284}Je to skvìlı následník rodiny Arima.|Našel tak rychle mnoho spojencù.
{29297}{29363}I beze slov, mùeme rozumnìt|jeden druhému bìhem šermu.
{29375}{29422}Takovı druh mue nejde kolem tak èasto.
{29458}{29501}Všichni mají rádi Teppeie.
{29522}{29544}I kdy je to zvrhlík.
{29569}{29631}Není to neobvyklé pro kluka v jeho vìku.
{29642}{29664}To mi pøipomíná,
{29664}{29732}døív jsi øíkala, "Jen poádejte a já vám ukáu..."
{29732}{29775}Zacházejí sluebné opravdu tak daleko?
{29775}{29839}To je...Nebudu to vìdìt dokud ten èas nepøijde...
{29858}{29911}Silvie, vezmeš si Teppeie?
{29924}{29943}Nevím.
{29958}{29996}Vìci jdou dobøe, tak jak jsou.
{29996}{30074}Nechtìla bych znièit naše pøátelství nìèím tak triviálním.
{30105}{30160}Aha. Tak takhle to je.
{30197}{30249}Všechny máme rády Teppeie.
{30264}{30331}Teppei nakonec taky bude mít nìkoho rád.
{30350}{30427}Ta osoba moná není jednou z nás.
{30452}{30559}Kohokoli si Teppei vybere, ádnı odpor|nebo nenávistné chování, okay?
{30587}{30661}To je vìc, kterou Teppei-sama nejvíc nenávidí...
{30672}{30749}Moná by mohl dávat pøednost nìkomu, kdo se chová víc ensky?
{30749}{30832}"ensky", myslíš starší enu?|Nemyslím, e je to...
{30832}{30890}Tak tedy, udìlejme "Smlouvu Horkıch Pramenù"!
{30905}{30965}"Smlouva Horkıch Pramenù"...to zní zajímavì!
{31037}{31093}Jdu spát, zítøek pøijde rychle.
{31093}{31119}Máš pravdu.
{31119}{31139}Dobrou noc!
{31139}{31172}Dobrou noc!
{31827}{31872}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31887}{31920}www.mycolorfullife.blog.cz
{32123}{32290}-V barvách rána a v noèním snìní, jsme se smáli jeden na druhého.-
{32290}{32462}-Èas, kterı jsem strávila spoleènì s tebou, byl tak plnı lásky.-
{32474}{32617}-Ah, ale od teï u tu nebude nic takového.-
{32617}{32794}-Chci se opìt shledat s tìmi vzácnımi dny, hned teï!-
{32794}{32818}-Sluncem jasnı den-
{32834}{32982}-Celı svìt pøetéká láskou.-
{32997}{33150}-Tak jestli je tu nìco nepøíjemného, tak na to zapomeò.-
{33150}{33355}-Kvùli dalšímu sluncem jasnému dni a jasnému zítøku,-
{33355}{33633}-nezáleí na tom, jestli je tohle konec cesty. |Chci se jen postupnì pøesunout dopøedu.-
{33943}{34004}Otázka! Co je myšleno "woohoo"?
{34004}{34069}"Woohooo", je to. V pùvodní práci...
{34093}{34121}Pøíští, Princess Lover!
{34121}{34166}SNOUBENKA A OKVÌTNÍ LÍSTEK
{34166}{34223}Jinımi slovy, pùvod "woohoo" je...
