{1}{1}23.976
{53}{96}TaSHee's Gang uvádí
{207}{298}PRINCESS LOVER!
{316}{458}-Stojící sama, šeptala jsem, "Pojï a povzbuï mì!",-
{473}{576}-a slzy stékají jak vzdychám.-
{606}{817}-Necítím se tak trapnì, abych se sama pokusila otevøít dveøe.-
{886}{1022}-Leštìná kousek po kousku, budu skvostnìjší, ne šperk,-
{1022}{1194}-chci záøit a tanèit dnes veèer u waltzu!-
{1202}{1360}-Nejlesklejší partner pro tebe, mùj nejlepší partner jsi ty.-
{1360}{1490}-Necítíš to stejnì? Chci to potvrdit, ale mùj hlas se chvìje...-
{1490}{1644}-Zavírám oèi a podávám ti ruku,-
{1644}{1799}-a èas se zastavil. Teï, pojï, co chceš dìlat?-
{1842}{2076}-Je to jen na tobì! Nakonec, u jsem všechno zprostøedkovala, ne?-
{2436}{2458}RÁJ A REALITA|A co hosté?
{2472}{2555}RÁJ A REALITA|ádnı problém. Všichni hosté šli domù.
{2567}{2626}Dobrá, zavøete okenice!
{2636}{2664}Dobrá!
{2731}{2765}Hej! Co se dìje?
{3373}{3412}Hartmane Vezelheime
{3412}{3443}Hartman Vezelheime, Vincent van Hossene
{3443}{3474}Hartmane Vezelheime, Vincente van Hossen, Arimo Isshine!
{3474}{3515}Byli bychom rádi, kdybyste zùstali potichu.
{3620}{3640}Josephine?!
{3675}{3693}To je...
{3807}{3832}Tady Fujikura.
{3844}{3962}Smìšné! Myslet si, e by Hills|mohlo bıt napadnuto tak jednoduše...
{3962}{4024}Josephine! Neøíkej mi, e ty...
{4024}{4074}Nepøátelé jsou obvykle na tvé stranì.
{4074}{4169}Neøíkala jsem ti obèas, abys byl ostraitı|vùèi lidem, kteøí jsou ti nablízku?
{4204}{4220}Milorde!
{4243}{4354}Yuu, eh? Vypadá to e jsme chycení,|ale nezranìní.
{4354}{4397}Nechávám Teppeie tobì.
{4397}{4460}Ten chlap! Má zavedenou komunikaci!
{4471}{4494}Pak ho umlète!
{4537}{4581}Dobøe, dobøe.
{4581}{4713}Jsem starı mu. ádám vás, abyste se prosím krotili.
{4757}{4789}Øekl jsem to, ne?
{4789}{4914}Vlastnìním penìz a moci, jste|stále krùèek od nebezpeèí.
{4955}{5057}Tady Fujikura, jednám pod pøímım dohledem |Arimi Teppeie, skuteènım dìdicem Arima Foundation.
{5057}{5088}Podejte mi stavovou zprávu.
{5097}{5243}ádné neregulérní existence uvnitø a venku|zemì, kromì Arima Hills.
{5257}{5297}Jaká je situace v Arima Hills?
{5314}{5436}Právì teï je izolovanı. Protoe systé, spadl, |funkce v budovì nejsou pøístupné.
{5436}{5509}Podejte mi stav Arima SP.
{5520}{5619}Mito, Saitama, Yokosuka, Hachoiji, všechny zóny zabezpeèeny.
{5655}{5684}Souvisí to nìjak s Charl?
{5896}{5968}Buï potichu. Nemáme v úmyslu ti ublíit.
{6069}{6098}Pomalu se posaï.
{6284}{6328}J-Je roztomilá!
{6328}{6369}Jako panenka!
{6383}{6463}Jsme tu jen proto, abychom vykonali náš cíl.
{6463}{6517}Kdy nebudeš vzdorovat, nic špatného se nestane.
{6531}{6575}Wow, jsou ohromné!
{6575}{6613}Vypadají tak mìkce!
{6613}{6662}Jste otravní! Zavøete na chvilku huby!
{6662}{6679}A-Ano!
{6706}{6747}Mùeš zaruèit, e nebudeš vzdorovat?
{6801}{6834}Dobøe, pøivate ji.
{6834}{6878}Huh? Jak?
{6878}{6924}Dìlat takové vìci...
{6924}{6984}Normální! Udìlat to je normální!
{6984}{7049}Pff, "normální", byl jsem šokován...
{7049}{7104}Je tak roztomilá, myslel jsem, e...
{7104}{7147}Vy idioti! Jsme na misi!
{7161}{7201}Bohudík. Jste dobøí lidé.
{7201}{7234}Heh...
{7249}{7311}Jak jsem sakra mohl skonèit|ve stejném tımu jako tihle idioti?
{7334}{7407}Vy jste zpùsobili tenhle vıpadek proudu, správnì?
{7407}{7456}Proè  byste dìlali nìco takového?
{7456}{7572}Je tu spousta lidí, kteøí nesmıšlí|o Arima Foundation dobøe.
{7572}{7684}Tak je to. Tohle ublíí jejich povìsti.
{7684}{7696}Au!
{7696}{7740}Ah, omlouvám se!
{7740}{7808}Byli jste taky ti, kteøí mì sem zavolali?
{7826}{7860}Nemùu o tom nic øíct.
{7874}{7952}Dìlámu tuhle práci pro naše pøátele.
{7966}{8031}Nemáme v úmyslu ti ublíit,|leda e bys nám vstoupila do cesty.
{8031}{8124}Nicménì, jestli nìkdo zasáhne, |zastavíme je jakımkoli zpùsobem.
{8175}{8192}U je skoro èas.
{8206}{8246}Dobøe. Uka mi monitor.
{8306}{8422}Média mají opravdu rády takové vìci.|Take, plán je docela jednoduchı.
{8450}{8512}V Roppongi nastal rozsáhlı vıpadek proudu.
{8522}{8636}Pøíèina je momentálnì stále neznámá. Nevíme, |kdy bude proud opìt obnoven.
{8652}{8745}Co tohle znamená? Ohlašují|to jenom jako zástavu elektøiny.
{8745}{8791}To je podivné.
{8831}{8868}Díky, dìdo.
{8868}{8900}Zachránil jsi mi ivot.
{8931}{8974}Dokonèili jsme pøípravy!
{8994}{9015}Díky!
{9015}{9075}Dobrá tedy, dovolte nám uštìdøit jim další ránu!
{9101}{9131}Co to znamená?
{9131}{9187}Nìkdo o našem plánu vìdìl a vyzradil informace.
{9199}{9265}Naše informace byly zachyceny!
{9277}{9317}Houjouin, eh?
{9317}{9373}Jakı neoèekávanı bonus.
{9386}{9417}Co je to?
{9417}{9439}Co se dìje?
{9439}{9554}Nìkdo z venku zpøístupòuje síové |informace Hills! 
{9717}{9760}Nevìdìl jsem, e bychom mìli pokoj jako je tenhle...
{9760}{9830}...a Yuu, co je s tvımi schopnostmi sluebné?
{9842}{9896}To je pro sluebné pøirozené.
{9896}{9931}Aha.
{9967}{10004}Ah, zdá se, e byli zpozorováni.
{10004}{10028}Co tím myslíš?
{10028}{10136}Byli zpozorováni, kdy jsem zpøístupòovala|síové informace Hills.
{10150}{10184}Protiútok se blíí.
{10196}{10232}Protiútok?
{10232}{10281}Znamená to, e jsme pod útokem.
{10281}{10324}Co se stane?
{10324}{10445}Jestli jsou schopní prorazit skrz, všechny kontrolní|systémy Arima Hills padnou do nepøátelskıch rukou.
{10445}{10525}Navíc, zamìøí se tady na nás. 
{10525}{10635}Samozøejmì, nenechám je proniknout....tak jednoduše!
{10963}{11030}Znovu jsme získali kontrolu nad sledovacími kamerami.
{11114}{11190}Ah, Milord! A taky van Hossen-sama!
{11202}{11249}Yuu-san, zvìtši pohled v téhle kameøe!
{11340}{11364}Charl!
{11412}{11467}Uf, to bylo tìsné.
{11467}{11489}Získal jsi znovu kontrolu?
{11489}{11510}Jo.
{11523}{11615}Kdokoli to byl, jsou opravdu|zkušení. Mìl jsem to brát vánì.
{11681}{11787}Omlouvám se! Byli jsme infikováni poèítaèovım|virem vyrobenım z DNA!
{11787}{11852}Promiò, opravdu nerozumím tomu, co øíkáš.
{11852}{11895}Tenhle typ viru...
{11895}{11932}Ah, vysvìtli mi to dvaceti pìti písmeny!|/Poznámka: japonskı vıraz pro "vysvìtli to pro mì krok za krokem"./
{11932}{11955}Ah, ano.
{11955}{12047}Vyèištìní tohoto viru zabere èas.
{12047}{12085}Zabere èas? Jak dlouho?
{12097}{12161}Dvacet...ne, deset minut!
{12236}{12262}Jedu do Hills.
{12291}{12316}To je nebezpeèné!
{12340}{12391}Nevíme, kdo je protivník nebo co chtìjí.
{12391}{12471}Ale, jestli udìláme tah, moná to budeme schopni to zjistit.
{12471}{12497}Jedu do Hills.
{12506}{12533}Teppei-sama!
{12533}{12705}Jsou tam zamìstanci Arima Group, |dìda, otec Silvie a Charl.
{12705}{12733}Urèitì je zachráním.
{12783}{12818}Rozumím.
{12818}{12966}Informuji Arima SP agragát a zajistím|tam všem bezpeèí.
{12984}{13008}Spoléhám na tebe.
{13103}{13164}Myslet si, e Teppei-sama tohle bude øídit...
{13164}{13258}Jak mùu vajádøit vdìènost celého personálu?
{13277}{13313}Dìlejte cokoli chcete...
{13404}{13417}Poèkej.
{13449}{13505}Slyšela jsem o tom, co se dìje od Fujikuri-dono.
{13505}{13539}Zavání to problémy.
{13584}{13644}Pùjdu s tebou, i kdy mi øekneš ne.
{13706}{13750}Máte náhradní helmu?
{13866}{13894}Silvie, rychle!
{13894}{13926}Já vím!
{13978}{14012}Odjeli! Pronásledujte je!
{14225}{14268}Tahle motorka nespadne, správnì?
{14268}{14279}Jo!
{14476}{14492}Zatracenì!
{14509}{14524}Teppei-sama?
{14524}{14549}Yuu-san?
{14561}{14638}Èlenové vızkumného tımu vám|radí zmáèknout modré tlaèítko.
{14649}{14673}Modré tlaèítko?
{14708}{14723}Tohle?
{14919}{14980}C-Co to sakra bylo? Zatracenì s nima!
{14998}{15015}Teppei-dono!
{15031}{15073}Uh...tynhle taky?
{15128}{15162}Jako kdybych skoèil na ten samı trik!
{15401}{15461}Technologie Arima je úasná...
{15481}{15551}Jsem rád, e jsme se zbavili tìch nohou pøed vjezdem do mìsta.
{15805}{15875}Proè se pokoušíte pøevzít Arima Group?
{15892}{15947}Dobrá, odpovím na to.
{15947}{16021}Nicménì, zajímá mì jestli ti moje slova postaèí?
{16021}{16054}Co tím myslíte?
{16085}{16144}Narodil jsem se v chudinské ètvrti.
{16144}{16242}Mohla bys vidìt Arima Hills z mého domu velice dobøe.
{16262}{16369}Z mého domu se zdálo jako by ta budova byla v nebi.
{16369}{16434}Ve srovnání s tím byl mùj ivot peklo.
{16458}{16567}Kadı den jsem se díval na nebe z pekla.|Umíš si to pøedstavit?
{16624}{16708}Od chvíle, co jsi se narodila a|do dne, kdy zemøeš, budeš ít v nebi.
{16708}{16772}Pøevrátíme vaše nebe v peklo...
{16772}{16845}Je to vlastnì neèekanì zajímavá práce.
{16864}{16891}Co to dìlají?
{16891}{16930}Zvrhlé vìci?
{16930}{17010}Ah, nemìl bys myslet na takové vìci!
{17010}{17025}Promiò.
{17080}{17146}Aha. Tahle cesta jistì vypadá dobøe osvìtlená.
{17146}{17238}Ano. To protoe hlavní brána je hlídaná.
{17275}{17290}Co udìláme?
{17290}{17324}Mùeme jedinì pokraèovat.
{17324}{17394}To není jedna z tvıch špatnıch vlastností.
{17500}{17570}Aha. Jako kdybychom se opravdu potøebovali plíit.
{17608}{17675}Sakra, pít v domì nìkoho jiného?
{17683}{17709}Mùete je zaznamenat? 
{17723}{17759}Jo. Je jich dvojnásobek.
{17785}{17802}Teppei-sama,
{17818}{17887}neutralizovali jsme virus ze sítì Arima Hills,
{17887}{17979}Znovu jsme pøevzali kontrolu nad dvìma monitory,|elektøinou a hlavním vjezdem.
{17993}{18055}Rozámím. Øekni mi, kde se všichni nachází.
{18055}{18186}Ano. Milord, van Hossen-sama a Vezelheim-sama|jsou stále v konferenèní místnosti.
{18199}{18280}Charlotte-sama je v apartmánu ve tøicátém šestém patøe.
{18287}{18304}Díky.
{18304}{18314}Pojïme!
{18314}{18341}Jo.
{18610}{18666}Teppei-sama, nepøítel se zaèal pohybovat.
{18788}{18869}Nemùu najít ádnou jinou cestu do budovy.
{18892}{18906}Do prdele!
{18906}{18922}Poèkej!
{18933}{18976}Jestli vylezeš tak bezhlavì, je konec!
{19020}{19059}Není pomoci. Teï ustupme.
{19316}{19478}Arimo Teppei-sama, jsem Katayama |z Arima SP agregátu. Omlouvám se za zpodìní.
{19512}{19543}Tihle lidé...
{19543}{19568}Dìkuji.
{19583}{19624}Pardon, ale musím jít nìkomu pomoci!
{19758}{19781}Co je to?
{19848}{19953}Rozumíš? Nenech je Hills zachytit na video!
{20012}{20081}Veškeré obsluze Arima Hills!
{20098}{20129}My jsme...
{20140}{20178}...sem pøijely debutovat...
{20198}{20275}...ve velkém náklaïáku!
{20387}{20416}Co se to dìje?
{20484}{20540}Slyšela jsem všechny detaily od Yuu.
{20563}{20629}Pøijeli jsme zachránit nešastnou princeznu.
{20665}{20689}Houjouin!
{20764}{20814}To je...? Co se dìje?
{20839}{20917}Toto se docela dost odchyluje od vašeho|pùvodního plánu, sleèno Josephine.
{20937}{20990}Ne, poèkej. Je tu ještì jedna vìc.
{21003}{21067}Ah, teï máš špatnou náladu?
{21083}{21141}Buï zticha a poslouchej své pøíkazy.
{21304}{21369}Vincente-san, Isshine-san! Teï je èas!
{21369}{21403}Ne! Hartmane!
{21403}{21431}Rychle!
{21524}{21639}Je pravda, e nevím jakı ivot jsi il.
{21659}{21699}Ani si to neumím pøedstavit.
{21699}{21783}Stejnì, všechno z toho není naše chyba.
{21800}{21841}Není to tvoje chyba.
{21859}{21960}Proè si nemùou obì strany rozumìt navzájem?
{21972}{22063}Proè musíme bıt nepøátele?
{22164}{22326}Rozumìt si navzájem? Jen jsi mi øekla,|e si neumíš pøedstavit náš zpùsob ivota!
{22336}{22437}Co je tu k porozumìní? Proè|lpíš na takové iluzi?
{22472}{22580}Tak to není! Kdyby jsi to zkusil,|nakonec bych mohla odpovìdìt!
{22613}{22660}Co by se stalo, kdybych to zkusil?
{22705}{22789}Udìlalo by to naši pekelnou|situaci ještì víc uboejší.
{22789}{22888}Nakonec, co øíkáš je èistı nesmysl!
{22980}{23028}Jsem ráda, e jste jednali první.
{23028}{23073}Já nevím, kdo je nepøítel,
{23073}{23135}ale tohle by mìlo zhatit jejich plány,
{23135}{23262}Ano. Média mùou zprostøedkovat dìní v Arima Hills,
{23276}{23350}ale všichni ti lidé budou vidìt|ty eny tam dole.
{23350}{23411}Neøíkej jim "ty eny"!
{23425}{23500}Jako producentka je to moje první skupina,
{23500}{23583}take mì ujisti, e si koupíš CD a bude vydané, okay?
{23654}{23708}Znovu jsme získaly kontrolu nad obrannım systémem!
{23731}{23839}Bezpeènostní okenice zavøeny. Zamkneme|nepøátele a dovolíme agregátu SP vstoupit.
{23889}{24001}Monitory neukazují ádné abnormality|na cestì ze støechy do apartmánu,
{24001}{24059}tak prosím pouijte VIP vıtah, abyste se tam dostali.
{24059}{24154}Potom, byste mìli bıt schopni|se spojit z nákupního støediska.
{24154}{24170}Rozumím.
{24185}{24205}Prosím otevøi dveøe.
{24205}{24238}Je moc brzo!
{24238}{24333}Právì teï jsme byli nuceni odstoupit od støelby.
{24373}{24417}Boooe. Otevírám je.
{24741}{24809}Neøíkej mi, e je opravdu dostala?
{24809}{24843}Vyøídila je.
{24864}{24919}Hej, co se dìje?
{24919}{24969}Jacku, co se dìje?
{24987}{25072}Naše helikoptéra pøistála bezpeènì. |Jack.-san tu spí.
{25072}{25099}Ty...!
{25099}{25148}Jsi si pro tebe, jen poèkej!
{25165}{25176}Sakra!
{25201}{25266}Pokoušet se pøekazit mùj plán?
{25266}{25365}Hej, teï. To není moc enské.
{25387}{25473}Hartman byl mùj uèeò.|Musíš s ním zacházet dobøe.
{25516}{25550}Oh, omluvte mì.
{25575}{25611}Nechte ho spát ve vedlejším pokoji!
{25611}{25626}Ano, madam!
{25648}{25727}U je èas nám øíct tvùj dùvod, proè jsi sem pøišla.
{25788}{25806}Velmi dobøe.
{25833}{25884}My jsme "Pravda"!
{25884}{25927}Pravda?
{25932}{25953}Opravdu.
{25968}{26023}Náš cíl je bás ztrapnit.
{26023}{26056}Ztrapnit?
{26056}{26075}Tak to je.
{26096}{26200}Pùsobivé, mobilizovat tolik|muské síly na takovou vìc.
{26200}{26283}I tak, toto je náš tribut.
{26312}{26350}Ústup!
{26416}{26453}Ah, to je konec.
{26467}{26530}Boooe, zrovna kdy vìci zaèínaly bıt zajímavé.
{26530}{26572}Pùjdeme domù.
{26592}{26652}Ukryli jsme v Hills bombu.
{26683}{26766}Vzdáváme to. Jen chvilièku a...
{26766}{26798}...v poøádku.
{26835}{26870}To je divné.
{26870}{26906}Taky jsem si to myslel.
{26930}{26998}Všichni mui okamitì zmizeli.
{27014}{27044}Co se stalo?
{27044}{27072}Nevím.
{27072}{27110}V kadém pøípadì, musíme jít.
{27125}{27140}Jo.
{27140}{27251}Obchodní patro, hotelové patro...znovu získáváme|kontrolu, jedno po druhém.
{27263}{27290}Všichni zamìstnanci jsou v bezpeèí.
{27391}{27410}Otèe!
{27423}{27456}Dìkuji ti, Silvie.
{27456}{27501}Omlouvám se za to, e jsem ti tohle udìlal.
{27522}{27571}Ah, jak nepøíhodná situace...
{27640}{27660}Kde je Hartman?
{27839}{27934}Silvie! Nechávám je tobì! Jdu zachránit Charl!
{27951}{27966}Dobøe.
{27989}{28002}Charl...
{28002}{28035}Charl...Charl!
{28365}{28407}Co by se stalo, kdybych to zkusil?
{28443}{28530}Udìlalo by to naši pekelnou|situaci ještì víc uboejší.
{28558}{28649}Nakonec, co øíkáš je èistı nesmysl!
{28665}{28687}To není...
{28737}{28756}To je...
{28819}{28831}Charl!
{28886}{28905}Charl!
{29058}{29101}Teppei!
{29166}{29194}Charl!
{29212}{29253}Teppei!
{29545}{29568}Teppei!
{29701}{29721}Charlotte.
{29800}{29880}Teppei...Byla jsem tak vystrašená.
{29897}{30015}U je to v poøádku. Všechno bude fajn.
{30116}{30165}Aha. Dovolte mi vyjádøit mou vdìènost.
{30175}{30220}Dìkuju vám, Houjouin.
{30238}{30312}Prosím kontaktujte mì, jestli budete potøebovat pomoct s vaší spoleèností.
{30377}{30408}Ne, díky nepotøebuji.
{30408}{30468}Jen jsem chtìla pomoct Arimovi.
{30507}{30576}Tím "Arima" jsem nemyslela Arima Group!
{30576}{30600}Myslela jsem Arimu Teppeie!
{30652}{30708}P-Proè se smìješ?
{30708}{30743}No, zajímá mì to?
{30753}{30796}Udav se!
{30872}{30887}Teppei.
{30927}{30960}Ten mu nìco øekl.
{30960}{30980}Ten mu?
{30997}{31053}Øekl, e nastavili v Arima Hills bombu!
{31279}{31309}Takovı druh elektrického záøení...
{31469}{31534}Neøíkejte mi...s nìèím tak jednoduchım, oni...
{31801}{31865}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31874}{31916}www.mycolorfullife.blog.cz
{32111}{32280}-V barvách rána a v noèním snìní, jsme se smáli jeden na druhého.-
{32280}{32450}-Èas, kterı jsem strávila spoleènì s tebou, byl tak plnı lásky.-
{32462}{32607}-Ah, ale od teï u tu nebude nic takového.-
{32607}{32782}-Chci se opìt shledat s tìmi vzácnımi dny, hned teï!-
{32782}{32824}-Sluncem jasnı den-
{32824}{32970}-Celı svìt pøetéká láskou.-
{32981}{33141}-Tak jestli je tu nìco nepøíjemného, tak na to zapomeò.-
{33141}{33339}-Kvùli dalšímu sluncem jasnému dni a jasnému zítøku,-
{33339}{33618}-nezáleí na tom, jestli je tohle konec cesty.|Chci se jen postupnì pøesunout dopøedu.-
{33927}{34024}Otázka! Nosí s sebou Silvie poøád ten meè?
{34024}{34099}Samozøejmì. Tohle je dìdictví, které|jsem dostala od Císaøe!
{34099}{34164}Kdy spím, kdy jsem ve vanì, kdy cvièím,|kdy jím, kdy se dívám na film...
{34164}{34221}/Kdy spím, kdy jsem ve vanì, kdy cvièím,|kdy jím, kdy se dívám na film.../|Pøíštì v Princess Lover! ÈERVENÁ A MODRÁ!
{34221}{34254}/Hej, ještì jsem neskonèila!/|Uvidíme se pøístì!
