{1}{1}23.976
{26}{95}TaSHee's Gang uvádí
{209}{300}PRINCESS LOVER!
{319}{461}-Stojící sama, šeptala jsem, "Pojï a povzbuï mì!",-
{472}{575}-a slzy stékají jak vzdychám.-
{607}{818}-Necítím se tak trapnì, abych se sama pokusila otevøít dveøe.-
{887}{1023}-Leštìná kousek po kousku, budu skvostnìjší, ne šperk,-
{1023}{1197}-chci záøit a tanèit dnes veèer u waltzu!-
{1197}{1362}-Nejlesklejší partner pro tebe, mùj nejlepší partner jsi ty.-
{1362}{1491}-Necítíš to stejnì? Chci to potvrdit, ale mùj hlas se chvìje...-
{1491}{1645}-Zavírám oèi a podávám ti ruku,-
{1645}{1802}-a èas se zastavil. Teï, pojï, co chceš dìlat?-
{1843}{2080}-Je to jen na tobì! Nakonec, u jsem všechno zprostøedkovala, ne?-
{2271}{2386}Celı tım automobilového vızkumu Arima |prolil do tohoto svá srdce i duše!
{2398}{2450}Tato motorka rozhodnì nemùe spadnout!
{2450}{2523}Mimoto, by nemìla vypadat pro |Teppeie-sama tak hrùzostrašnì,
{2523}{2577}tentokrát jsme pøidali "nohy"!
{2612}{2653}To je zbyteèné a nechutné!
{2685}{2738}SNOUBENKA A OKVÌTNÍ LÍSTEK
{3034}{3043}Ah!
{3056}{3076}Hádej kdo?
{3100}{3151}Podívejme...Teppei!
{3151}{3204}Huh? Jak jsi to mohla øíct hned správnì?
{3240}{3263}Øekla jsem ti to, ne?
{3263}{3312}"Víš to okamitì, jestli je to tvá pøedurèená osoba".
{3342}{3364}Dìlám si legraci!
{3375}{3409}C-Co to má znamenat?
{3459}{3514}Všechny máme rády Teppeie.
{3526}{3594}Teppei nakonec bude mít taky nìkoho rád.
{3613}{3695}Ta osoba moná není jednou z nás.
{3710}{3825}Kohokoli si Teppei vybere, ádnı odpor|nebo závistivé chování, okay?
{3849}{3927}To je vìc, kterou Teppei-sama nejvíc nenávidí...
{3927}{4010}Moná preferuje nìkoho, kdo se chová víc ensky?
{4010}{4094}Tím "ensky", myslíš starší enu?|Nemyslím si, e je to...
{4094}{4154}Pak tedy, udìlejme "Smlouvu Horkıch Pramenù"!
{4366}{4405}Dostal jsem oznámení.
{4420}{4475}Kdy nemùe bıt Princezna nalezena...
{4491}{4529}Je zøejmé, kdo je obvinìn!
{4553}{4639}Abych mohl Princeznu ochraòovat |od odporného hmyzu jako jsi ty, 
{4648}{4716}já, Alf, jsem pøipraven kdykoli poloit svùj ivot.
{4716}{4758}Neøíkej mu odpornı hmyz!
{4773}{4818}Teppei je mùj milenec!
{4831}{4860}Milenec!
{4870}{4898}Milenec!
{4907}{4931}Milenec!
{4968}{5005}"Milenec", øíkáš?!
{5022}{5037}To je pravda.
{5056}{5180}Milady, myslím, e jsem vám nìjak nerozumìl...
{5180}{5213}To není nedorozumìní!
{5229}{5280}Milenec je milenec, správnì Teppei?
{5344}{5411}Jako kdybych mohl zapomenout na toho, kdo|vyuívá vıhodu Miladiny nevinnosti!
{5411}{5510}Poèkejte chvíli! Nikdo tady nezkouší|vyuívat vıhody Charl!
{5532}{5570}Ticho, ty...
{5591}{5636}...zbloudilı pse!
{5680}{5702}Uteèeme, Teppei?
{5702}{5727}J-Jo!
{5751}{5782}Poèkej!
{5827}{5901}Milady, od té doby, co jste se narodila,
{5917}{5976}jsem pokraèoval ve vašem hlídání.
{5990}{6097}Dokud nepøijde den, kdy z mıch oèí zmizí svìtlo!
{6097}{6125}Milady...
{6125}{6160}M-Milady...
{6286}{6312}Myslím, e teï bychom mìli bıt v bezpeèí.
{6322}{6350}Bohudík.
{6373}{6421}Boe, je tak neodbytnı.
{6439}{6494}Soudím z toho, e bude ít a do sta.
{6507}{6565}Vsadím se, e do sto dvaceti.
{6582}{6664}"Prosím buï zdravı dokud má dcera|nebude pøipravená vstoupit do politiky."
{6729}{6777}Chceš tady strávit nìjakı èas?
{6791}{6801}Jo.
{6844}{6856}Co se dìje?
{6885}{6954}To nic, myslím, e jsem si trochu vyvrtla kotník.
{6973}{7028}Ah, promiò. Bylo to kvùli tomu, e jsem tì s sebou táhnul?
{7028}{7083}Ne, není to tvoje chyba.
{7117}{7127}Ah!
{7203}{7236}Pojïme na ošetøovnu.
{7256}{7271}Teppei?
{7308}{7329}Opravdu se omlouvám.
{7389}{7431}Není to tvoje chyba.
{7511}{7531}Arima Hills...
{7531}{7546}Hm?
{7572}{7649}Vdycky jsem chtìla zkusit jídlo v Arima Hills.
{7649}{7691}Jídlo v "Arima Hills"?
{7703}{7716}Tak je to.
{7716}{7776}Mùeš to pro mì udìlat za tohle. Co myslíš?
{7776}{7793}Okay?
{7811}{7824}Dobøe.
{7884}{7911}/Ošetøovna/
{7963}{7989}To by mìlo staèit.
{8006}{8058}Jen buï opatrná a vyléèí se to rychle.
{8137}{8148}Coe...?
{8761}{8785}Parašutista?
{8799}{8823}Zajímá mì, kdo to je...
{8823}{8847}Pojïme.
{9195}{9211}To musí bıt osud.
{9488}{9553}Hej! Studenti Akademie Shuuhou!
{9568}{9598}Dìkuji, e jste mì pøišli pøivítat.
{9636}{9682}Nìní to tak, e jsme ho pøišli pøivítat...
{9700}{9736}Hartman Vazelheim.
{9750}{9774}Silvie, ty ho znáš?
{9799}{9814}Hartman?
{9828}{9837}Ano.
{9854}{9917}Je to podnikatel z Kníectví Hazelrink.
{9927}{9988}Hazelrink? Myslíš ze Charlottiny zemì?
{10012}{10036}Charlotte!
{10053}{10068}Hartmnane...
{10231}{10268}Zdá se, e se znají.
{10282}{10295}To je pravda.
{10310}{10344}Má styky s královskou rodinou.
{10355}{10404}Myslím, e jsem o nìm slyšela.
{10427}{10462}Hartman Vazelheim.
{10473}{10521}/Je potešení vás všechny poznat./|Obchoduje s Arima Group.
{10538}{10556}Opravdu?
{10576}{10678}Vezelheim-sama má v souèasné dobì|u Arima Group velké investice.
{10701}{10744}Ty musíš bıt Arima Teppei-kun?
{10767}{10804}Jak o mì víte?
{10816}{10841}Samozøejmì, e o tobì vím.
{10862}{10912}Jmenovanı dìdic Arima Group.
{10959}{11057}Zdá se, e si dobøe rozumíš s Charlotte.
{11071}{11082}Jo.
{11082}{11101}Hartmane.
{11112}{11170}Z toho jak to vypadá nevíš, kdo jsem.
{11193}{11229}Jsem její snoubenec.
{11260}{11309}Od Charlotte Hazelrink.
{11618}{11690}Sleèno Houjouin, dìkuji vám, e|jste mì provedla po akademii.
{11702}{11780}Jsem šastnı, e jsem vidìl, kde moje snoubenka studuje.
{11798}{11845}Ne, to nic nebylo.
{11860}{11905}Budu v této zemi docela dlouho.
{11939}{11961}Arimo Teppei-kun.
{11979}{12015}Jsem si jistı, e se znovu setkáme.
{12034}{12105}Tìším se a proberu spoustu dùleitıch|záleitostí s Arimou Isshinem-san.
{12135}{12154}Chápu.
{12200}{12236}Dobrá, Charlotte.
{12419}{12438}Zase pøijedu.
{12613}{12625}Charl.
{12664}{12726}Nìvìdìla jsem, e máš snoubence.
{12765}{12880}Omlouvám se...Nechci o tom teï mluvit.
{13102}{13169}Charl, nemluvili  jsme o veèeøi?
{13218}{13325}V apartmánu Arima Hills ti|mùou pøipravit cokoli bys ráda!
{13325}{13361}Teppei!
{13383}{13439}Kdy? Kdy mì tam vezmeš?
{13467}{13484}Dám ti vìdìt.
{13517}{13532}Budu èekat!
{13553}{13591}Poøád budu èekat!
{13669}{13695}"Smlouva Horkıch Pramenù"!
{13718}{13768}To není to o èem jsem pøemıšlela...
{13785}{13813}Dobrá, dobrá.
{14271}{14287}Co tím myslíš?
{14327}{14398}Jestli je to pravda, Filmish|bude státem zmatku!
{14419}{14442}A nejen to.
{14451}{14493}Nemìlo by bıt nemyslitelné,|aby zemì zmizela!
{14518}{14553}Jsi si jistı, e je to spolehlivá informace, e?
{14573}{14617}Ví o tom Hazelrink?
{14640}{14661}Onee-chan?
{14703}{14718}Mario.
{14734}{14782}Co je? Spor?
{14914}{14929}Neøíkej mi...
{14951}{14967}To je...
{15433}{15455}Yoo-hoo!
{15506}{15552}Huh? Jen ty, Silvie?
{15567}{15601}Ano. Jen já.
{15621}{15637}Aha.
{15710}{15748}Není nìco, co bys mi mìla øíct?
{15767}{15778}Eh?
{15797}{15856}Ptám se tì, jestli nìní nìco o èem bys mi mìla øíct?
{15880}{15901}O èem?
{15930}{16050}Hmm...dnes ráno, mìla jsem míchaná|vajíèka a croissant!
{16050}{16092}Nemluvím o tvé snídani!
{16160}{16195}O Hartmanovi?
{16272}{16319}Promiò, e jsem o tom mlèela.
{16349}{16364}To je to?
{16371}{16381}Eh?
{16419}{16466}Opravdu se nestarám o Hartmana.
{16489}{16557}Aèkoli jsem byla pøekvapena, vím e takové vìci|se na tomto svìtì stávají èasto.
{16574}{16591}Dùleitìjší...
{16610}{16690}Uvìdomovali jste si, e Kníectví Hazelrink,|stejnì jako má vlast, Kníectví Filmish,
{16690}{16771}tajnì budovalo bunkr jadernıch øízenıch støel?
{16825}{16848}Coe?
{16875}{16918}Mùj otec o tom nic nevìdìl.
{16953}{16984}Co Hazelrink?
{16998}{17039}Není ádnı zpùsob, jak bych to vìdìla!
{17062}{17080}Je to pravda?
{17085}{17187}Samozøejmì! Nemyslím, e by to mùj otec vìdìl...
{17201}{17304}Podle konverzace mého otce, to bylo|pravdìpodobnì podníceno tøetí zemí.
{17304}{17337}Kterou zemí?
{17369}{17406}Nevíme, to je problém.
{17418}{17448}Také neznáme jejich cíle.
{17466}{17565}Moná zamıšlejí znièit spojenectví mezi našimi národy.
{17580}{17650}Moná je to naprosto nìco jiného.
{17709}{17749}Neuznávám tvé odposlouchávání.
{17848}{17870}Houjouin.
{17880}{17949}Nemohla jsem najít správnou dobu, abych vstoupila.
{17968}{18007}Nakonec jsem všechno slyšela.
{18031}{18074}Domnívám se, e není nic, co s tím mùeme udìlat.
{18089}{18154}Vím. Nemám v úmyslu to nìkomu øíct.
{18181}{18241}Nikdy si nemùete bıt jisté, kdo se dívá.
{18259}{18292}To zní dìsivì.
{18326}{18435}Mám nìjaké informace od mého strıce,|musím vám to tajemství øíct taky.
{18457}{18508}Øeknu vám to jako omluvu za to odposlouchávání.
{18580}{18628}I kdy to mùe bıt nespolehlivá informace,
{18642}{18764}je tu bulvární plátek, kterı øíká, e se |dnec veèer nìco stane v Arima Hills.
{18780}{18803}Jakı je jejich cíl?
{18809}{18852}Pokud jde o tohle, tak mì nic nenapadá.
{18852}{18906}Stejnì, mám z toho špatnı pocit.
{18906}{19008}Boe, o èem to mluvíš?|Pøestaò øíkat divné vìci!
{19216}{19268}/Od: Arima Teppei|Je tu nìco o èem s tebou musím mluvit.|Pøijï dnes veèer do Arima Hills./
{19283}{19308}Teppei?
{19355}{19408}To je pravda...jestlie je Teppei...
{19431}{19479}Jestli je to Teppei, jsem si jistá, e s tím mùe nìco udìlat.
{19785}{19916}Teppei-sama, mùete si zavolat pokojovou slubu vytoèením|èísla sedm na vašem pokojovém telefonu,
{19916}{19996}spíše, ne pøijít k tomuto stolu.
{20010}{20031}Ah, opravdu?
{20039}{20052}Ano.
{20059}{20196}Stejnì si nemùu zvyknout na tyhle vìci,|jen pouívání telefonu na všechno.
{20211}{20279}Není lepší se potkat a mluvit v tváøí v tváø jako takhle?
{20279}{20344}Jestlie je to pro vás tak lepší, Teppei-sama.
{20361}{20416}Pak tedy, kdy byste rád, aby pøišli?
{20451}{20524}Dùleitìjší, dávám pøednost japonské kuchyni...
{20541}{20633}Hmm? Ale, jestli to není Arima Teppei-kun.
{20656}{20714}Josephine, mohla bys na mì chvíli poèkat?
{20726}{20795}Máme menu. Prosím jen chvíli poèkejte.
{20802}{20817}Dìkuji.
{20855}{20878}Arima Teppei-kun.
{20949}{20976}V-Vy jste...
{21003}{21038}Prosím, øíkej mi Hartman.
{21095}{21129}Rande s pøítelkyní?
{21144}{21202}Ah, ne, není to rande...
{21220}{21258}Jen ji zvu k sobì domù, to je celé.
{21341}{21401}Ah, to je pravda, tohle místo je taky tvùj dùm.
{21416}{21442}Máte jednání s dìdou?
{21455}{21544}Velmi mnoho. Myslel jsem, e bych ti øekl|ahoj, dokud tì vidím.
{21556}{21579}Ruším tì?
{21594}{21627}Ah, vùbec ne.
{21646}{21681}Dobrá tedy, prosím omluv mì.
{21704}{21757}Pøeju ti, aby tvé rande bylo úspìšné.
{21770}{21802}Jak jsem øekl, není to rande...
{21910}{21923}Teppei-sama?
{21956}{21981}Ah, pardon, pardon.
{22012}{22032}Našla jste menu?
{22066}{22110}Co Teppei dìlá?
{22147}{22158}Ah!
{22195}{22252}Budu èekat v apartmánu za hodinu.
{22292}{22323}Hurááá!
{22461}{22484}Omlouvám se za èekání.
{22529}{22588}Upøímnì se omlouvám za zabrání vašeho èasu.
{22610}{22668}Josephine, vydilo by ti, kdyby jsi nás opustila?
{22770}{22839}Dobrá tedy, prosím dovolte mi zaèít konverzaci.
{22852}{22925}Ah, omlouvám se. Mùete ještì chvíli poèkat?
{22957}{23011}Je tu ještì jedna osoba, která se k nám pøidá.
{23023}{23044}Ještì jedna?
{23106}{23135}Ah, zdá se, e je tady.
{23154}{23170}Vstupte!
{23277}{23380}Znáte ho? To je Sir Vincent van|Hossen z Kníectví Filmish.
{23411}{23519}Na této schùzce, bude jednat|jako filmishskı zástupce.
{23564}{23596}To je poprvé, co mám |potìšení ze schùzky.
{23614}{23652}Slyšel jsem o vaší skvìlé povìsti.
{23670}{23716}Pøední hazelrinkskı podnikatel,
{23735}{23787}a také snoubenec Princezny Charlotte.
{23811}{23852}Je to jen otázkou èasu ne se stanete |èlenem královské rodiny.
{23904}{23936}Dobrá tedy, zaèneme?
{23995}{24151}Oblast na dosah ruky je spolupracující dohoda|mezi Hazelrink, Filmish a Arima Group.
{24173}{24268}Originální plán byl vybudovat velké letovisko|v sousední oblasti, správnì?
{24280}{24288}Ano.
{24312}{24429}I tak, se mùj blízkı poboèník |spikl s tøetí zemí.
{24439}{24481}Jaká je ta tøetí zemì?
{24496}{24553}Nepøiznal by, pro koho pracuje.
{24576}{24626}Dává svùj vlastní ivot v sázku?
{24626}{24690}Nebo se vymlouvá?
{24690}{24701}Ano.
{24734}{24805}Jejich cílem je vybudovat jaderné zbranì |na venkovì blízko letoviska.
{24821}{24938}Následkem toho, míní znièit pøátelskı|vztah mezi tìmi dvìma zemìmi.
{24964}{25112}Jako zodpovìdná osoba a snoubenec Princezny|Charlotte, vyšetøujete to?
{25126}{25226}Nejdøívì se budou snait zasít semínka|posezøení ve Filmish.
{25243}{25255}To je správnì.
{25272}{25356}Pak si lidé budou myslet, e Hazelrink |pokraèuje v budování své armády.
{25371}{25390}To je naprostá pitomost.
{25413}{25464}To je podcenìní Kníectví Filmish!
{25475}{25540}Vlastnì, by jejich plán oklamalo dítì.
{25567}{25697}Ale byl jste to vy, kdo jim dovolil, |aby uchopili tuto monost,
{25707}{25724}Hartmane.
{25741}{25790}Ano. Jsem si toho plnì vìdom.
{25804}{25926}Jako zpùsob omluvy, |vyšetøování u zaèalo.
{25939}{26046}Jste èestnı a jednoduše oklamatelnı. Dávejte pozor.
{26062}{26194}Vlastnìním penìz a moci, jste vdycky|jen krùèek od nebezpeèí.
{26209}{26233}Nezapomeòte na to.
{26265}{26274}Ano.
{26336}{26352}Milady!
{26372}{26406}Milady, kde jste?
{26463}{26483}Vezmìte mì k Arima Hills.
{26496}{26519}Ano, madam.
{26531}{26565}Ah, Milady!
{26600}{26611}Rychle!
{26654}{26685}Milady!
{26685}{26713}Pospìšte si a jeïte!
{26713}{26736}J-Je to v poøádku?
{26736}{26760}Je to fajn!
{26848}{26916}M-Milady!
{26944}{26970}Jestlie je Teppei...
{26970}{27017}Jestli je to Teppei, bude schopnı s tím nìco udìlat!
{27067}{27215}Nejdøíve, se potøebujeme ujistit, e mùeme vìøit|celémù personálu Arima Group z Japonska.
{27255}{27358}Máte podezøení, e je za tím|nìkdo z Group?
{27384}{27457}Rád bych slyšel názor Sira|van Hossen.
{27478}{27530}Na mém názoru nesejde.
{27547}{27704}Dùleitìjší je, jestlie o tom uslyší obèané buï z Filmish |nebo Hazelrink, nastane veøejnı nepokoj.
{27722}{27816}Mìl jsem plány zabránit médium|v roznášení informací.
{27842}{27872}Vyzradilo se to, huh?
{27892}{27942}U je nemùeme dret stranou.
{27994}{28024}Mario, kde je otec?
{28049}{28102}Táta øíkal, e jde do dìdeèkova domu.
{28120}{28141}Je v Arima Hills?
{28155}{28248}Pak øekl, e by onee-chan mìla |jít k onii-chanovi.
{28264}{28294}Jít k Teppei-dono?
{28532}{28582}Hmm...ty vpravo?
{28613}{28657}Uka mi je s tìmi punèochami pøedtím, okay?
{28739}{28755}Díky.
{28785}{28850}Není mım stylem se jen dívat|a nejednat.
{29200}{29226}Promiò, e jsem tì nechala èekat!
{29226}{29255}H-Huh?
{29391}{29407}Teppei?
{29516}{29524}Hmm?
{29561}{29602}Teppei-sama, máte telefonní hovor.
{29614}{29671}Oh sakra, zapomnìl jsem ho nastavit na vibrace.
{29764}{29774}Charl?
{30134}{30140}Ah!
{30628}{30645}Neodpovídá...
{30879}{30956}/Od: Neznámı|Následníku Arimi Isshina, navíc ti kromì|obou rodièù, teï vezmeme tu, kterou miluješ./
{31560}{31604}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31618}{31657}www.mycolorfullife.blog.cz
{31873}{32042}-V barvách rána a v noèním snìní, jsme se smáli jeden na druhého.-
{32042}{32210}-Èas, kterı jsem strávila spoleènì s tebou, byl tak plnı lásky.-
{32226}{32368}-Ah, ale od teï u tu nebude nic takového.-
{32377}{32547}-Chci se opìt shledat s tìmi vzácnımi dny, hned teï!-
{32547}{32584}-Sluncem jasnı den-
{32584}{32732}-Celı svìt pøetéká láskou.-
{32749}{32901}-Tak jestli je tu nìco nepøíjemného, tak na to zapomeò.-
{32901}{33103}-Kvùli dalšímu sluncem jasnému dni a jasnému zítøku,-
{33103}{33382}-nezáleí na tom, jestli je tohle konec cesty. |Chci se jen postupnì pøesunout dopøedu.-
{33696}{33767}Otázka! Co bys doporuèila|jako suvenır z Arima Hills?
{33767}{33811}Doporuèuju masovı bochánek Arima|s extra stehnem, které se pohybuje!
{33811}{33854}Moná keramická váza, která se pohybuje!
{33854}{33875}Ah, leze to na mì!
{33875}{33897}Ah, hıbe se to!
{33897}{33921}Vy u jste celou tu vìc snìdly?
{33921}{33966}Pøíštì v Princess Lover!
{33966}{33995}RÁJ A REALITA!
{33995}{34025}Jste nevychovaní!
