{1}{1}23.976
{53}{115}TaSHee's Gang uvádí
{209}{302}PRINCESS LOVER!
{323}{459}-Stojící sama, šeptala jsem, "Pojï a povzbuï mì!",-
{469}{575}-a slzy stékají jak vzdychám.-
{605}{820}-Necítím se tak trapnì, abych se sama pokusila otevøít dveøe.-
{885}{1021}-Leštìná kousek po kousku, budu skvostnìjší, ne šperk,-
{1030}{1197}-chci záøit a tanèit dnes veèer u waltzu!-
{1197}{1356}-Nejlesklejší partner pro tebe, mùj nejlepší partner jsi ty.-
{1356}{1491}-Necítíš to stejnì? Chci to potvrdit, ale mùj hlas se chvìje...-
{1491}{1644}-Zavírám oèi a podávám ti ruku,-
{1644}{1802}-a èas se zastavil. Teï, pojï, co chceš dìlat?-
{1843}{2071}-Je to jen na tobì! Nakonec, u jsem všechno zprostøedkovala, ne?-
{2604}{2650}Ah, takovı druh elektrického záøení...
{2804}{2872}To nemùe bıt...s tak jednoduchım obvodem...
{3149}{3183}ÈERVENÁ A MODRÁ|Bomba?!
{3195}{3274}Ano, nejspíše. Zdá se, e|tam nemusí bıt jen jedna.
{3274}{3381}Princezna Charlotte a Teppei jsou stále uvnitø, správnì?
{3381}{3403}Správnì.
{3413}{3596}Virus, kterı byl pouit na náš systém byl potlaèen|protiúderem, kterı jsme udìlaly a vìtšina byla znièena,
{3616}{3763}ale zdá se, e vir zmutoval|a teï zdivoèel.
{3778}{3812}To je odmìna za mou nedbalost.
{3826}{3877}Další neoèekávanì sloitá diskuze, eh?
{3877}{3924}Úplnì tomu nerozumím.
{3924}{3983}Pøestaòte se obviòovat.
{3983}{4088}Kdybyste nejednaly, stále bychom byli uvìznìní v Hills.
{4102}{4148}Co pøesnì mùeme udìlat?
{4167}{4242}Mùu mluvit s Teppeiem-sama jen pøes vysílaèku.
{4253}{4339}Aktuálnì jsem neschopná pøekopat systém Hills.
{4357}{4409}Mùeš ovìøit, kolik bomb tam je?
{4422}{4460}Nakonec, pìt.
{4478}{4521}Arima Hills se zøítí.
{4521}{4635}Jestli se to stane, nebudeme schopni krmit|falešnımi informacemi média...
{4635}{4730}To ne...Jestli Hills exploduje...Vra se!
{4730}{4841}Uklidni se, Houjouin! Jestli tady|zpanikaøíš, nic dobrého z toho nevzejde.
{4841}{4894}Take mi øíkáš, abych tam ty dva nechala?
{4894}{4928}Nikdy jsem neøekla nic takového!
{4928}{4977}Pøestaòte, vy dvì.
{4977}{5041}Nejdøíve se musíme soustøedit na to, jak tìm dvìma pomoct.
{5208}{5249}Zatracenì, tady taky?
{5272}{5317}Teppei...já...
{5352}{5426}Je docela legrace se s tebou takhle dret za ruku!
{5426}{5450}Huh?
{5450}{5520}"Rande v Hills". Jako náš slib, správnì?
{5520}{5574}P-Poèkej chvilièku, Charl. Chápeš|naší situaci?
{5586}{5639}V Hills byla nastavena bomba, správnì?
{5639}{5674}Chápeš, a stále...
{5674}{5779}Bude to okay! Urèitì budeš schopnı nìco udìlat!
{5805}{5832}Oh, boe.
{5832}{5907}Mùete mì slyšet? Syne Arimi Isshina.
{5932}{6002}Co si myslíte o naši veèeøi?
{6002}{6028}Ty...
{6039}{6067}Co to dìláš?
{6078}{6113}Proè nám tohle dìláš?
{6129}{6156}"Proè?"
{6198}{6225}Protoe jste bohatí.
{6280}{6364}Pøejeme si jen staení |z bank známıch jako "poøádné bohatství":
{6378}{6405}To je celé.
{6405}{6482}Dobrá tedy, pøeji vám dvìma úasnı veèer.
{6482}{6524}Hej! Hej!
{6740}{6764}Co se dìje?
{6764}{6788}To není dobré.
{6803}{6846}Není ádnı jinı zpùsob?
{6868}{6899}Je jeden.
{6899}{6924}Opravdu?
{6931}{6957}Jakı "zpùsob" to je...?
{6978}{7139}Pøeformátovat celı server Arima Group,|vèetnì toho v Arima Hills.
{7139}{7195}Nicménì, kdy to udìláš...
{7234}{7291}Ano. Kompletnì bychom vymazali virus,
{7291}{7366}ale všechny data Arima Group by také zmizely.
{7497}{7529}Yuu.
{7578}{7595}Ano.
{7599}{7778}Jednou jsi vyèistila servery od viru, kolik èasu|potøebujeme do pøevzetí kontroly systémù Hills?
{7808}{7841}Dvacet minut...
{7841}{7882}...ne, patnáct!
{7882}{7929}Pak je pøeformátuj.
{7929}{7971}Sni vıkon.
{7971}{8007}Ale, Milorde!
{8007}{8035}Je mi to jedno!
{8064}{8154}Data Arima Group teï nejsou dùleitá.
{8154}{8224}Všechno zálohování bude tady,
{8252}{8326}a v hlavách všech, kteøí pracují |pro Arima Group.
{8426}{8446}Rozumím.
{8502}{8550}Jedna z bomb byla nalezena.
{8556}{8623}Je to èasovaná bomba, zpoèátku nastavena na jednu hodinu.
{8623}{8657}Je to standartní drátovı typ.
{8671}{8731}Zbıvá dvacet pìt minut a tøicet sekund!
{8843}{8922}Ty èervené koleèka...jsou lokality bomb?
{8931}{9045}Pro jednoduché zaøízení jako tyto, nebude|jejich odzbrojení tak tìké.
{9055}{9112}Problém je, e závidíme proti èasu.
{9112}{9146}Dej nám detailní vysvìtlení.
{9146}{9278}Mnoství èasu, které máme mezi sníením|proudu do znovuzískání kontroly je deset minut.
{9278}{9363}Potom, bude zbıvat jen deset|minut do té doby, ne se bomby spustí.
{9363}{9432}Bomby v umìlecké galerii a nákupním støedisku,
{9432}{9498}personál SP je poblí a mùe to zvládnout vèas.
{9498}{9647}Nicménì, nebudou se schopni vèas dostat k zaízením|lokalizovanım v hotelovém patøe a nákupním patøe.
{9662}{9717}Dobrá, pùjdu do hotelového patra.
{9717}{9740}Eh?!
{9760}{9817}Jestlie tam vstoupíš pøes støechu, mùeš to zvládnout vèas.
{9817}{9844}Silvie!
{9844}{9937}Otèe, Charlotte je moje vzácná kamarádka z dìtství,
{9948}{10089}a Teppei je mùj dùleitı pøítel a taky mùj snoubenec.
{10089}{10118}Silvie...
{10159}{10178}Jdu.
{10210}{10268}Hej, poèkej!
{10281}{10363}Jako kdybych tì nechala jít samotnou a jednat cool!
{10363}{10392}Jdu taky!
{10552}{10602}Poslední byla lokalizována tady.
{10610}{10653}Personál SP není v této oblasti,
{10664}{10760}a a jednou znovu získáme kontrolu,|nebudeme mít èas se k ní dostat.
{10773}{10795}Teppei-sama.
{10827}{10861}Slyšel jsem všechno.
{10861}{10980}Umístìní vás do tohoto nebezpeèí, Teppei-sama,|odpykám si to tak moc, jak bude nezbytné.
{10980}{11155}Prosím, postarejte se o poslední bombu, která je v nákupním patøe!
{11155}{11228}Rozumím. Udìlám, co øíkáš, Yuu-san.
{11228}{11261}Teppei-sama...
{11320}{11340}Formátování!
{11340}{11386}Zaèíná formátování.
{11758}{11814}Ah, zùstali jsme vzadu.
{11814}{11846}Zajímá mì, kde to jsme?
{11846}{11896}Idioti! Pospìšte si a odejdìte odtamtud!
{11909}{11926}Ano.
{11942}{11960}Omlouvám se.
{11984}{12012}Hej, to je Arima Teppei!
{12012}{12065}Eh, spoleènì s tou zvrhlou princeznou!
{12065}{12141}Huh? Vy jste ti dva z døívìjška?
{12141}{12166}Znáš je?
{12166}{12213}Ani náhodou, jsou to zlí hoši.
{12213}{12228}Eh?!
{12228}{12279}Pøesto jsou velmi milí.
{12279}{12314}Kterı z nich?
{12345}{12438}Rande s dobøe vypadajícím|klukem a princezna ho drí za ruku?
{12438}{12517}Taková situace v realitì nikdy nenastane!
{12517}{12545}Jsi neomluvitelnı!
{12562}{12650}Pøestaòte! Prosím, nechte náš jít!
{12650}{12768}Je tak roztomilá! Chci si ji vzít domù!
{12768}{12824}Umím si ji pøedstavit v zástìøe...
{12838}{12946}Oh, to je skvìlé. Rád bych ji vidìl|v národních šatech mé zemì.
{12956}{13055}Jsi cvok. No, pak, pak by mohla bıt nahá v zástìøe!
{13110}{13142}Nemyslete na ni takhle!
{13142}{13206}Pardon! Papaaa!
{13229}{13318}Sakra, zaútoèit na nás, kdy jsme |byli uprostøed konverzace...
{13318}{13402}Stejnì, bylo by hezké, kdybyhom ji znovu potkali.
{13494}{13572}Zatracenì! Tady to není dobré! Okenice jsou stále zavøené!
{13572}{13662}Teppei-sama, jestli nemùete projít,|nezvládnete to vèas!
{13662}{13719}Prosím, pokuste se nìjak proniknout!
{13734}{13751}Proniknout?
{13766}{13805}Není ádná jiná cesta!
{13826}{13853}Charl, zùstaò vzdau.
{13868}{13881}Okay!
{14046}{14067}Teppei!
{14076}{14125}Co je s tou vìcí? Ani se nepohne!
{14134}{14232}Byla navrena tak, aby ji nezboøilo ani zemìtøesení.
{14245}{14306}Øekla jsi mi, udìlejte s tím "nìco", víš co?
{14306}{14316}Ano.
{14325}{14381}I kdy mi to øekneš, tak...
{14409}{14429}Moná bych mìl zkusit tohle?
{14463}{14493}Èekala jsem na to!
{14493}{14526}Jsem vzrušená, vzrušená, vzrušená!
{14526}{14556}Proè vypadá tak šastnì?|/Jsem vzrušená, vzrušená, vzrušená!/
{14574}{14657}Huh? Ten meè je vyrobenı ze døeva, správnì?
{14668}{14694}Er, jo.
{14706}{14724}Mùe øezat?
{14724}{14799}Myslím, e to nebduu vìdìt, dokud to nezkusím!
{14845}{14862}Jaké to je?
{15026}{15040}Charl!
{15121}{15162}Ah, Charl! Omouvám se! Omlouvám se!
{15162}{15168}Jsi v poøádku?
{15168}{15216}Nejsi zranìná, e? Jsi v poøádku, správnì?
{15216}{15254}Oh, pane boe. Moc se omlouvám!
{15507}{15575}Hej, je v poøádku, kdy s tebou teï mluvím?
{15575}{15631}Nemluvila jsi se mnou u?
{15644}{15678}No, myslím, e je to pravda.
{15693}{15710}Co je?
{15710}{15768}Jen, teï, jsi øekla,
{15779}{15819}"Teppei je mùj snoubenec," správnì?
{15848}{15965}Nejednala jsi trochu drze? To je|proti "Smlouvì Horkıch Pramenù", víš.
{15995}{16052}Ani nevím, já.
{16158}{16218}Milovala jsem svou matku.
{16218}{16299}O èem to mluvíš? Souvisí to s naší konverzací?
{16299}{16376}Pocity, které cítím k Teppeiovi jsou |stejné, jako jsem cítila k matce.
{16402}{16479}Kdy máma umøela, neplakala jsem.
{16506}{16610}Smutek byl tak ohromující, ale slzy nestékaly.
{16622}{16739}I tak, vdycky jsem ve svém|srdci volala mámino jméno.
{16752}{16836}Myslíš, e miluješ Teppeie|tak moc, jakou svou matku?
{16864}{16937}Nechci znovu zaívat ty pocity.
{16958}{17047}Byla jsem tehdy malá, tak jsem nemohla nic udìlat.
{17047}{17139}Nicménì, je tu nìco, co teï mùu udìlat.
{17139}{17198}Jinımi slovy, ho máš ráda.
{17254}{17307}Mám ráda Teppeie.
{17307}{17388}Provokuje me a je tak beznadìjnı v tolika vìcech...
{17404}{17481}Ale, zamilovala jsem se do nìj døív, ne jsem si to uvìdomila.
{17553}{17628}Jsi schopná stát za svımi pocity tak jasnì. árlím na tebe.
{17653}{17786}Já opravdu neárlím na to, e jste ty|a Charl urozené a vznešené, ale...
{17802}{17885}...musí bıt bolestné nebıt si schopná pøipustit, koho máš ráda.
{17912}{17937}Pravdìpodobnì máš pravdu.
{18003}{18046}Do toho, do toho, Teppei!
{18046}{18086}Zvládneš to, Teppei!
{18086}{18127}Jaj, jaj, Teppei!
{18127}{18172}Charl, pomohla bys mi trochu?
{18172}{18203}Okay!
{18315}{18366}Charl, kde jsi to sehnala?
{18392}{18447}Támhle, z exteriérového obchodu Danhel.
{18457}{18500}Vánì, tak prodávají takové vìci?
{18529}{18570}Hej, poèkej!
{18625}{18686}/Omlouvám se, Arima Teppei zaplatí|za škody, Charlotte/
{18733}{18818}Hartman byl snoubenec Princezny Charlotte, správnì?
{18828}{18847}To je pravda.
{18847}{18912}Vzhledem k Hazelrink...
{18923}{18998}Samozøejmì. Je to nìco, co jim musíme øíct.
{18998}{19116}Pøed tím, je logické dovolit|Princeznì, aby s nimi mluvila první.
{19147}{19305}Dìtské pouto Lady Silvie a |Princezny Charlotte je silné.
{19339}{19370}I kdyby byl stále naivu,
{19387}{19487}jistí lidé by se na nìj zlobili,|e ije tak èestnı ivot,
{19513}{19543}je smutné to øíkat.
{19543}{19615}Nemùu vystát, jak krùtı mùe bıt místy svìt.
{19637}{19652}Máte pravdu.
{19664}{19703}Èištìní viru, kompletní!
{19722}{19769}Obnovení elektøiny v Arima Hills.
{19769}{19828}Zbıvá deset minut ne vyprší èas!
{19905}{19999}Dobøe, jsou na kadém programu!|To je na zaèátek dost dobré.
{19999}{20048}Ty eny mùou poèkat a potom, co to udìláme!
{20048}{20110}Jak jsem øekla, nenazıvej je "tìmi enami"!
{20124}{20146}Dobøe, dobøe!
{20199}{20253}Znovu jsme získali kontrolu nad všemi systémy!
{20267}{20323}P-Poèkej! Bìíš moc rychle!
{20352}{20370}Dostali jsme se dovnitø!
{20370}{20472}Teppei-sama, jdìte rovnì a k zatáèce!
{20472}{20488}Dobøe!
{20488}{20510}Pojïme, Charl.
{20521}{20534}Jo!
{20871}{20912}Tady Umìlecká Galerie, bomba byla znìškodnìna.
{20924}{20966}Nákupní Støedisko, bomba je zneškodnìna.
{20986}{21002}Tady je to.
{21002}{21063}Hej, zbıvají u jen dvì minuty!
{21063}{21136}Našly jsme bombu. Prosím, dej mi instrukce!
{21144}{21189}Nejdøív, prosím odstraòte kryt.
{21210}{21270}To je typ bomby, kterou byste mohly|nazıvat "drátové dilema".
{21270}{21355}"Drátové dilema"? Hej, nakonec se bojíš?
{21355}{21415}U jsme došly tak daleko, bıt vystrašená je teï nesmyslné.
{21415}{21484}Ah, mám z toho opravdu špatnı pocit.
{21497}{21618}Mìly by tam bıt tøi dráty. Absolutnì nesmíte|odstøihnout ten lutı, protoe je to nepravı drát.
{21618}{21730}Problém je: èervenı nebo modrı. Dokud jeden z nich neodøíznete,|není ádnı zpùsob, jak bychom vìdìli, kterı je ten správnı.
{21730}{21816}Jak jsem si myslela! Proè nám to øíkáš a teï?!
{21816}{21885}Aha. Tak proto se to nazıvá "drátové dilema".
{21929}{21942}Podr to.
{21942}{22016}Díky. Poèkej, proè to mám dret?!
{22016}{22089}Podr to, prosím. Pøemıšlím, |kterı z nich bych mìla vybrat.
{22089}{22134}Pøemıšlíš? Jak?!
{22190}{22219}Proè se díváš pryè?!
{22228}{22291}Pøestaò jeèet a nech mì se soustøedit.
{22291}{22375}Modrı. Modrı, správnì? Je pouívanı v poulièních svìtlech!
{22489}{22525}Ty jsi Arima Teppei, správnì?
{22546}{22567}Další, kdo bude chycen.
{22583}{22626}Neutekl jsi od svıch pøátel?
{22647}{22816}Dostal jsem informace od mıch pøátel. øekli mi,|e Arima Teppei byl s Princezou.
{22832}{22851}Slyšel jsem o tobì.
{22867}{22947}Stal jsi se dìdicem Arima|Foundation skoro pøes noc.
{22947}{23060}A pøišel jsi, abys zachránil Princeznu|s jedinım døevìnım meèem...
{23093}{23143}Je to vskutku fascinující pøíbìh.
{23160}{23215}Tak proè na nás ukazuješ tou zbraní?
{23231}{23277}Protoe nesnesu pohled na tebe.
{23277}{23324}Jsi na tom lépe, ne já!
{23324}{23358}Jsi milovanı víc, ne já!
{23358}{23431}Nemùu vystát nikoho ve støedu veøejného zájmu!
{23447}{23497}Šéf mi øekl abych nezasahoval,
{23511}{23590}ale kdy jsi se objevil pøede|mnou, jsem trochu znepokojenı.
{23608}{23640}Mùj další vıstøel tì dostane.
{23670}{23712}Pouívání nìèeho jako je pistole...
{23730}{23796}Co oèekáváš, e udìláš|s tím zlomenım døevìnım meèem?
{23810}{23845}Nemùe vyhrát proti zbrani.
{23866}{23900}Charl, schovej se.
{23915}{23932}Teppei?
{23951}{23987}Budu v poøádku, neboj se.
{24116}{24137}Sakra!
{24360}{24392}Nepotøebuju døevìnı meè, abych to s tebou skonèil.
{24392}{24525}Opravdovı mu vyjadøuje své pocity svımi pìstmi!
{24593}{24612}Omlouvám se.
{24647}{24751}Chtìl jsem øíct nìco jiného,|ale moje hlava je teï trochu popletená.
{24824}{24839}Pojïme.
{24849}{24889}Všechny zachráníme.
{24905}{24914}Jo.
{25005}{25042}Hej, u nezbıvá ádnı èas!
{25055}{25066}Je to beznadìjné!
{25143}{25195}U to nemùu dret!
{25366}{25388}Kterı jsi odízla?
{25407}{25421}Èervenı.
{25469}{25498}Nezastavilo se to!
{25513}{25562}Øekla jsem ti, "modrı", ne?
{25586}{25607}Huh?
{25623}{25665}Z-Zastavilo se to.
{25673}{25699}Jak jsem si myslela.
{25699}{25758}"Jak jsem si myslela"? Co tím myslíš?
{25767}{25806}Je to moje šastná barva pro dnešek.
{25806}{25842}Jinımi slovy jsi hádala?
{25860}{25884}Nebylo to háfání.
{25902}{25980}Shodou okolností, je spodní prádlo,|které mám dnes na sobì taky èervené.
{25995}{26010}Aha.
{26034}{26077}Coe?! Jenom deset sekund!?
{26101}{26116}Zatracenì!
{26116}{26133}Teppei!
{26250}{26302}Odpadková šachta!
{26525}{26549}Jsme zachránìni.
{26549}{26578}Teppei-sama?
{26593}{26650}Hodil jsem to do odpadkové šachty...
{26663}{26697}To bylo rozumné rozhodnutí.
{26707}{26820}Odpadkové šachty Arima Hills jsou vyrobeny|z tuhé oceli sedm palcù silné.
{26846}{26873}A co s tím?
{26907}{26932}Teppei!
{26949}{27006}Byl jsi úasnı! To je mùj Teppei!
{27006}{27072}Charl, tohle jsou pánské záchodky.
{27267}{27347}Vedla sis skvìle. Všechno díky tobì.
{27360}{27413}Nezaslouím si taková slova.
{27413}{27481}Mimo to, ti, kteøí dìlali co mohli jsou
{27481}{27516}Silvia-sama,
{27516}{27550}Silvia-sama, Houjouin-sama,
{27582}{27641}Teppei-sama a Charlotte-sama
{27662}{27729}a všichni z Arima SP.
{27743}{27838}Ano. Všichne jste byly vynikající. Dìkuji vám.
{27838}{27955}Já, Arima Isshin, jsem vám vdìènı z hlouby srdce.
{27982}{28053}Teï je všechno v poøádku. Prosím, odpoèívej.
{28125}{28165}Dìkuji vám mnohokrát.
{28188}{28231}Všichni jsou v bezpeèí a zdraví!
{28231}{28249}No, jo.
{28276}{28339}Jsem ráda, jsem opravdu ráda!
{28362}{28391}Bohudík. Bohudík. Bohudík. Boh---
{28391}{28408}Charl.|/Bohudík. Bohudík. Bohudík. Boh---/
{28408}{28434}Bohudík. Bohudík. Bohudík. Boh---
{28450}{28482}Prosím uklidni se a poslouchej mì.
{28493}{28520}Co je?
{28542}{28601}Hartman...
{28601}{28628}Hartman...zdá se, e byl zabit.
{28719}{28783}Hej, proè to teï vytahuješ...?
{28804}{28878}Pokoušel se zachránit mého otce a Arimu Isshina.
{28931}{28985}Aha.
{29036}{29143}Pokoušel se zachránit tvého otce a Isshina-sama.
{29159}{29172}Ano.
{29195}{29225}To mi dìlá radost.
{29281}{29375}Abych øekla pravdu, vlastnì jsem se do nìj nikdy nezamilovala.
{29397}{29451}Ale dokud byl nìkdo, koho jsem si mìla vzít,
{29461}{29545}snaila jsem se ze všech sil k nìmu nìco pocítit.
{29564}{29761}Fakt, e se pokoušel zachránit otce Silvie a|Isshina-sama mi nakonec dìlá radost.
{29778}{29803}Nakonec...
{29818}{29919}...jsem ho zaèínala mít ráda.
{30121}{30154}Charlotte-sama.
{30181}{30238}Slyšeli jsme detaily od Arimi-sama.
{30252}{30309}Nyní, kdybyste se prosím vrátila do sídla.
{30325}{30367}Um...kde je Alf?
{30380}{30458}Plániovali jsme e Alfredovi-sama|neøekneme nic o tom, co se dnes stalo.
{30466}{30529}Nemusíte se o nìj bát.
{30542}{30576}Aha.
{30587}{30609}Dìkuji.
{30658}{30688}Tak, uvidíme se pozdìji.
{30688}{30719}Zítra ve škole, jako obvykle?
{30729}{30748}Jo.
{30748}{30776}Uvidíme se.
{30793}{30818}Buï opatrná.
{30835}{30878}Teppei,
{30878}{30912}Teppei, moc dìkuju!
{31048}{31123}Nakonec ho zaèala mít ráda, po tom co zemøel.
{31151}{31205}To je...docela smutné, ne?
{31319}{31411}Bylo to od ní moudré øíct to s úsmìvem.
{31428}{31500}Charl není typ èlovìka, kterı mùe nìkoho nenávidìt.
{31811}{31869}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31881}{31920}www.mycolorfullife.blog.cz
{32114}{32283}-V barvách rána a v noèním snìní, jsme se smáli jeden na druhého.-
{32283}{32449}-Èas, kterı jsem strávila spoleènì s tebou, byl tak plnı lásky.-
{32464}{32612}-Ah, ale od teï u tu nebude nic takového.-
{32612}{32785}-Chci se opìt shledat s tìmi vzácnımi dny, hned teï!-
{32785}{32815}-Sluncem jasnı den-
{32815}{32970}-Celı svìt pøetéká láskou.-
{32989}{33140}-Tak jestli je tu nìco nepøíjemného, tak na to zapomeò.-
{33140}{33340}-Kvùli dalšímu sluncem jasnému dni a jasnému zítøku,-
{33340}{33619}-nezáleí na tom, jestli je tohle konec cesty.|Chci se jen postupnì pøesunout dopøedu.-
{33930}{33955}Otázka!
{33955}{34057}Okenice a odpadkové šachty Arima Hills|jsou vyrobeny z oceli sedm palcù silné,
{34057}{34104}ale co kdyby exploze opravdu nastala?
{34104}{34152}Zùstaly by jen okenice a odpadkové šachty.
{34152}{34213}Pøíštì v Princess Lover! ZTRÁTA A ZNOVUZROZENÍ!
{34213}{34267}To a maso rozsekané na kousky s rıí|by mohlo bıt všechno, co zbyde.|/Poznámdka: hayashiraisu je rozsekané maso s rıí./
