{1}{1}23.976
{36}{90}TaSHee's Gang uvádí
{201}{295}PRINCESS LOVER!
{329}{460}-Stojící sama, šeptala jsem, "Pojï a povzbuï mì!",-
{475}{576}-a slzy stékají jak vzdychám.-
{606}{817}-Necítím se tak trapnì, abych se sama pokusila otevøít dveøe.-
{887}{1023}-Leštìná kousek po kousku, budu skvostnìjší, ne šperk,-
{1023}{1205}-chci záøit a tanèit dnes veèer u waltzu!-
{1205}{1359}-Nejlesklejší partner pro tebe, mùj nejlepší partner jsi ty.-
{1359}{1493}-Necítíš to stejnì? Chci to potvrdit, ale mùj hlas se chvìje...-
{1493}{1644}-Zavírám oèi a podávám ti ruku,-
{1644}{1799}-a èas se zastavil. Teï, pojï, co chceš dìlat?-
{1843}{2076}-Je to jen na tobì! Nakonec, u jsem všechno zprostøedkovala, ne?-
{2115}{2153}TOTO JE NECENZUROVANÁ VERZE ;)
{2270}{2304}Vincente-san! Isshine-san!
{2304}{2337}Ne! Hartmane!
{2349}{2361}Rychle!
{2432}{2448}Charl.
{2448}{2474}Bohudík.
{2491}{2526}Prosím uklidni se a poslouchej mì.
{2526}{2550}Co je?
{2583}{2640}Hartman...
{2640}{2672}Hartman...zdá se, e byl zabit.
{2833}{2895}Tak, uvidíme se pozdìji. Zítra ve škole, jako obvykle?
{2906}{2920}Jo.
{2934}{2951}Uvidíme se.
{2972}{2987}Buï opatrná
{3344}{3388}ZTRÁTA A ZNOVUZROZENÍ
{3444}{3469}Teppei-sama!
{3494}{3525}Yuu-san.
{3567}{3630}Hej, jak dlouho ho budeš objímat?!
{3658}{3673}Otèe.
{3685}{3702}Silvie.
{3734}{3755}Bohudík.
{3777}{3877}S pomocí všech jsme byli schopní ochránit Arima Hills.
{3889}{3949}Já, Arima Isshin, vìnuji vám vdìènost z hlouby mého srdce.
{3997}{4087}Hazelrinkská eskorta pøijede brzy.
{4108}{4130}Kde je Princezna?
{4130}{4192}Pro Charl pøijelo pøed chvílí auto.
{4205}{4261}Slyšela jsem, e jste poslali auto.
{4275}{4286}Coe?
{4309}{4346}Byl to Alfred?
{4346}{4407}Jedinı, koho jsem kontaktoval, byl Alf.
{4628}{4668}To ne...øeknìte mi, e to není pravda.
{4714}{4729}Charl...
{5574}{5674}Je to v poøádku, e váš plán je jen z poloviny úspìšnı, Hartmane-sama?
{5713}{5744}Tak to chodí.
{5751}{5774}Hartmane!
{6207}{6269}Co se dìje s onee-chan? Má dìsivı vıraz.
{6462}{6501}Je to úspìch.
{6513}{6591}Je jen otázkou èasu a udeøí do hitparád.
{6684}{6700}Televize...
{6700}{6762}Seiko-sama, v èem je problém?
{7133}{7177}Poèkej, Charl, chápeš naši situaci?
{7190}{7212}Všechno je fajn.
{7222}{7284}Jsem si jistá, e s tím nakonec Teppei bude schopnı nìco udìlat.
{7356}{7389}Co jsi myslela tím "nìco s tím udìlá"?!
{7409}{7452}Nakonec bych ji nemohl zachránit!
{7485}{7583}Lidé, kteøí unesli Charl jsou pravdìpodobnì|ti samí lidé z toho dne.
{7616}{7726}Jedna z kamer zachytila|obrázek podezøelé osoby.
{7792}{7813}Nemoné!
{7828}{7868}Myslel jsem, e zemøel, kdy byl postøelenı.
{7883}{7945}To znamená, e to všechno bylo pøedstírané.
{7970}{8060}Znamená to, e jsme byli jednoduše oklamaní.
{8075}{8155}Jestli je to pravda, Princezna Charlotte...
{8175}{8206}Pravdìpodobnost je vysoká.
{8219}{8239}Já...
{8239}{8363}Teppei-kun, chápu tvé pocity, ale|toho u je mezinárodní záleitost.
{8363}{8460}Je hranice, kd yu ji nemùeš zachránit.
{8460}{8524}Take øíkáte, e bychom mìli jen stát opodál a dívat se?
{8537}{8607}Otèe, myslím na tu samou vìc jako Houjouin.
{8624}{8689}Toto je situace, kde jsme nejistí |v tom, kolika nepøátelùm èelíme.
{8706}{8751}Co byste mohli na takovém místì dìlat?
{9045}{9060}Teppei...
{9092}{9128}Ano, co je?
{9188}{9229}Prosím, nezapomeò na mì.
{9239}{9248}Huh?
{9277}{9361}Prosím, nevyma vzpomínky na mì, ze svého srdce.
{9487}{9527}Co se stalo?
{9527}{9595}To nejste vùbec vy, Arima-sama.
{9595}{9630}Prosím øeknìte mi všechno!
{9630}{9718}Jestli máte nìjaké problémy, sdílejte je|se mnou, Nezu Haruhikem!
{9781}{9797}A-Arima-sama?
{10460}{10489}Oh, dobré odpoledne!
{10503}{10552}Zajímá mì, jestli je moc brzy øíct dobrı veèer.
{10569}{10596}Kde to jsem?
{10626}{10676}Ah! Jak se jmenuju?
{10676}{10689}To ne!
{10716}{10732}Lhala jsem.
{10742}{10761}Charlotte,
{10778}{10822}Charlotte Hazelrink.
{10838}{10855}Ráda tì poznávám.
{10870}{10902}Hádej kdo?
{10902}{10999}Øíkal jsem ti! Jsem novı pøeloenı student!
{11060}{11091}Ty jsi...
{11098}{11130}Jsi nudnı.
{11146}{11226}Jestli mì nemùeš poznat poøádnì|jednou, nemyslím si, e je to osud.
{11275}{11292}Dìlám si legraci!
{11308}{11344}Jsem Charlotte Hazelrink.
{11364}{11387}Znovu se setkáváme!
{11575}{11615}Charl...Charl!
{11936}{11949}Charl!
{12005}{12019}Charl!
{12177}{12219}Teppei!
{12279}{12310}Charl!
{12332}{12375}Teppei!
{12670}{12693}Teppei!
{12815}{12838}Charlotte.
{12961}{12980}To je pravda...
{13019}{13117}Pøedtím ne jsem si to uvìdomil...bylo místo v mém srdci...Charlottino.
{13542}{13597}Probudila se's, má snoubenko.|/teï vypadá ale kuròa líp, co?!! ;)))/
{13597}{13655}Hartmane, øíkali, e jsi mrtvı...
{13701}{13786}Ale, ale, to je tvùj trest za princeznovské chování.
{13821}{13948}Bohuel, odstraním tvého vzácného pøítele.
{13967}{13988}Arimu Teppeie.
{14009}{14048}Rozdrtím rodinu Arima, uvidíš.
{14073}{14103}Proè Teppeie?
{14143}{14194}Protoe se stal následníkem Arimi.
{14229}{14303}To proto ho znièím.
{14318}{14384}A s tím, bude vedení Arimi Isshina beznadìjné.
{14393}{14478}N-Neøíkej mi, Arima Hills byl tvùj...?
{14493}{14507}Správnì.
{14591}{14624}P-Proè bys to dìlal...?
{14645}{14694}Arima Isshin dluí velkı dluh.
{14724}{14769}Jen zahanbit ho nestaèí.
{14796}{14917}To proto vystavím jeho hanbu všude|na celém svìtì, a pak mu vezmu všechno.
{14931}{14957}O èem to mluvíš?
{14957}{15008}Je to v poøádku, jestli to nechápeš.
{15030}{15064}Nespuste z ní oèi!|/Hartmane! Hartmane!/
{15064}{15075}Nespuste z ní oèi!|Ano pane!|/Hartmane! Hartmane!/
{15169}{15191}Omluvte mì...
{15211}{15242}U je to nìjakou dobu.
{15262}{15308}Vy chlapi jste ti z Hills...
{15308}{15355}Ubliuje ti ten provaz?
{15382}{15440}Bolí to! Bolí to! Opravdu to bolí!
{15440}{15480}Strašnì se omlouvám, je tak tìsnı.|Bolí to! Bolí to! Opravdu to bolí!
{15480}{15531}P-Poèkejte, uvolním ho.|Bolí to! Bolí to!
{15531}{15561}Prosím, drte to v tajnosti.
{15586}{15645}Dìkuji, jste opravdu dobøí lidé.
{15645}{15734}T-To je okay. Je nìco co byste chtìla jíst?
{15744}{15793}Takoyaki. Takoyaki!
{15793}{15893}Takoyaki, takoyaki! Chci vidìt Teppeie!
{15923}{15956}Dostali jsme nìjaké informace.
{15965}{16054}Charlotte-sama byla drena ve vlaku velvyslance.
{16068}{16103}Je to Grand Hazelrink?
{16114}{16175}Ano, mysleli jsme si, e byl pohøešován.
{16185}{16314}Ale byl zapsán na plnou moc Charlotte-sama.
{16328}{16405}Aha. Její vlastné zemì nemùe udìlat prohlášení.
{16433}{16499}Je to informace od spolehlivého zdroje?
{16515}{16549}Nemùu se za to zaruèit.
{16565}{16656}Nicménì, jsou to opravdu všechny informace, které máme.
{16675}{16732}V kadém pøípadì, Teppei-dono je klíè?
{16770}{16824}Ale Teppei-sama je...
{16876}{16899}Já vím.
{17112}{17133}Jak jsem si myslela.
{17168}{17183}Seiko-san.
{17183}{17236}Co to máš za depresivní vıraz?
{17254}{17306}Co si myslíš, e se vytratíš se tøídy?
{17319}{17369}Pøemıšlíš o zpùsobu, jak zachránit Charl?
{17404}{17421}To je nemoné.
{17438}{17501}Charl u teï smìøuje k Hazelrink.
{17523}{17611}Vincent-san øekl, e není nic co bych mohl udìlat.
{17611}{17637}Jsi blbı?!
{17652}{17688}Take, co kdy je v Hazelrink?
{17697}{17721}Nic co bys mohl udìlat?
{17721}{17742}Co s tím?
{17757}{17857}Kde je ta odhodlanost, kterou jsi ukázal|bìhem tréninku na ples a veèírek?
{17889}{17934}T-To je úplnì odlišné od této situace, ne?
{17942}{17962}Je to to samé!
{17973}{18047}Neil jsi vdycky nedbale?
{18068}{18144}Jestli chceš opravdu zachránit Charl, pak|nezáleí na tom, co øíkají ostatní...
{18144}{18205}...i kdyby to byl prezident, nezáleí na tom.
{18213}{18229}Co chceš udìlat?!
{18357}{18417}Já.. Já...
{18838}{18916}I tak, je to ten Arima Teppei, do kterého jsem se zamilovala?
{18945}{18987}Se-Seiko-san...
{19166}{19206}Vypadá to, e myslíme na stejnou vìc.
{19242}{19291}Nikdy jsem neèekala, e zajdeš tak daleko.
{19301}{19326}Vidìla jsi...?
{19335}{19346}Sil---
{19382}{19410}Co to dìláš?!
{19410}{19503}Ubohé! Jsi "ten" Arima Teppei?!
{19527}{19564}A to si øíkáš následník?!
{19580}{19650}Stejnı Arima Teppei, kterı se mnou skøíil meèe?
{19665}{19809}Arima Teppei, kterı rozluštil nenávist|trvající pùl století mezi Arimou a Houjouin?!
{19809}{19850}To je úplnì jinı pøíbìh!
{19893}{19941}Mùeš jen fòukat, jestli chceš.
{19970}{20001}Já jdu zachránit Charl.
{20023}{20095}Charl se teï pohybuje napøíè Ruskem.
{20095}{20158}Koneènı cíl je Hazelrink.
{20179}{20208}Jak jsem èekala.
{20223}{20314}Ano. Abych zachránila Charl, vrátím se do své zemì.
{20330}{20399}Pøemıšlela jsem, e se tì zeptám jestli pùjdeš se mnou, ale, velmi špatnì.
{20633}{20656}Pøedávka štafety.
{20695}{20733}Od teï, je to tvá práce.
{20746}{20799}Teppei potøebuje bıt nìkım ukonejšenı.
{20816}{20844}Prosím, zacházej s ním jemnì.
{20844}{20902}Jestli je to tak, pak by byla Seika-sama lepší...
{20902}{20935}Jsi nejvhodnìjší osoba pro tenhle úkol.
{20947}{21024}Aèkoli mi láme srdce to pøiznat, není to práce pro mì.
{21041}{21067}Jedu zpìt do mé zemì.
{21095}{21115}Chci zachránit Charl.
{21137}{21150}Rozumím.
{21162}{21214}Tak, prosím udìlej nìco s tím zabednìncem.
{21241}{21257}Spoléhám na tebe.
{21286}{21307}Budu na tebe spoléhat.
{21307}{21341}U-Umm...
{22335}{22349}Yuu-san...
{22376}{22386}Pøest---
{22423}{22439}Teppei-sama...
{22662}{22769}Muselo to bıt tìké, vzít vám Charl.
{22805}{22833}Pro mì je to stejné.
{22848}{22893}Vèetnì Silvie-sama a Seiki-sama.
{22929}{22945}Ale,
{22945}{23053}stále ještì nìjakı èas zbıvá.
{23072}{23094}Stále je šance.
{23305}{23321}Sakra...
{23344}{23382}Yuu-san, jsi milá...
{23399}{23417}Teppei-sama.
{23442}{23523}Ve srovnání se Silvii a Seikou-san, jejich tón je tak krutı.
{23535}{23554}Tak drzı.
{23620}{23634}Yuu-san.
{23652}{23727}Mluvení o tom, kde se Charl nachází, mùeš mi øíct detaily?
{23737}{23749}Ano.
{23790}{23811}A...
{23812}{23828}Ano?
{23863}{23916}Mùu, zùstat takhle...ještì chvíli?
{23970}{23984}Ano.
{24501}{24530}Hartmane-sama...
{24554}{24590}Kdy jsme tu jen my dva, øíkej mi Hartman.
{24635}{24725}U bychom nemìli dlouho potøebovat tu holku, správnì?
{24773}{24845}Informace by teï nemìly k Arimovi dosáhnout.
{24861}{24976}Kdy Arima pøijde, ta dívka bude pøekákou.
{24998}{25029}Stále to má cenu.
{25029}{25088}Stále myslíš na svatbu s ní?!
{25132}{25150}Jdu do postele.
{25254}{25339}Budu poøád na tvojí stranì, Hartmane-sama.
{25380}{25445}Neøíkal jsem ti, e mi máš øíkat Hartmane,|kdy jsme tu jen my dva?
{25494}{25525}Dobrá, dobrou noc.
{25688}{25736}Hej, kam ten vlak jede?
{25750}{25818}Zdá se, e jedeme napøíè Ruskem.
{25818}{25838}Ruskem?
{25853}{25900}Pak to znamená, e se vracíme do Hazelrinku?
{25914}{25937}Zdá se, e ano.
{25955}{25972}Co mám dìlat?!
{25972}{26009}C-Co se dìje?
{26029}{26134}Jestli smìøujeme k Hazelrinku, pak|to zabere hodnì èasu, správnì?
{26134}{26170}T-To je pravda.
{26181}{26221}Chci se vykoupat!
{26240}{26302}Nekoupala jsem se od vèerejška!
{26302}{26383}Chci se vykoupat! Vykoupat, vykoupat!
{26421}{26466}Opravdu to máte s sebou, e?
{26466}{26551}Teï je na to èas! Jestli chcete, vykoupejte se...
{26576}{26594}M-Myslím e...
{26594}{26639}Mimo to, právì teï jsme uvnitø vlaku...
{26639}{26681}Je to definitivní ne!
{26682}{26745}S-S-S-Sprchu si dát mùete!
{26766}{26815}Sprchu, máte takovou vìc, huh?
{26815}{26882}Ano! Je-Jestli si chcete dát sprchu, pak prosím---
{26927}{26965}Dìkuji vám, zachránili jste mi ivot.
{26965}{27006}-ádnı problém!
{27177}{27190}Otèe...
{27241}{27308}Slyšel jsem to od hlavní sluebné Teppeie.
{27338}{27385}Vrátím se zpátky do naší zemì a pøevezmu velení.
{27401}{27421}Pùjdu taky!
{27435}{27481}Nemùu to dovolit, Silvie.
{27500}{27533}Zùstaò v Japonsku.
{27552}{27616}Velmi, velmi se o tebe a Mariu bojím.
{27636}{27674}Proto tedy, by ses mìla vrátit k Teppeiovi---
{27674}{27752}Ne...on urèitì zachrání Charl.
{27778}{27851}Chci bıt jeho podpora a pomoc pøi záchranì Charl.
{27874}{27894}Silvie...
{27909}{28007}Chci zachránit mou vlast mıma vlastníma rukama.
{28041}{28100}Maria by mìla jet taky, Filmish je skvìlá zemì.
{28121}{28180}Ty taky jednou najdeš štìstí |s lidmi ze svého národa.
{28206}{28221}Jistì!
{28221}{28241}Mario...
{28287}{28328}Kdy budu s onee-chan, budu v poøádku.
{28348}{28393}Mimo to, Teppei pojede taky, správnì?
{28479}{28530}Poslouchej dobøe...Je to jen jednou.
{28565}{28616}A potom, budeme pokraèovat v ivotì v Japonsku.
{28616}{28651}Nevzdám to, okay?
{28687}{28730}To je to, co mám na mysli, otèe!
{29164}{29221}Dìkuji vám, cítím se skvìle!
{29237}{29266}O-Opravdu?
{29281}{29347}Jestli to øíkáš, rád pùjdu dovnitø.
{29347}{29386}Potøebuješ nìco?
{29402}{29430}Nekoukejte!
{29654}{29733}Zdá se, e nerozumíš své pozici.
{29817}{29874}To bolí! Pøestaò! To bolí!|/Øíkám, abys nebyla tak nafoukaná!/
{30022}{30102}Já...Nikdy neuteèu ani se neschovám.
{30177}{30198}Ty malá dìvko!
{30471}{30494}Kam jsi šla?
{30556}{30575}No, kamkoli.
{30575}{30664}Stejnì, vyzradila jsi informace|o tomhle vlaku, Josephine?
{30697}{30781}Ano, ale je moné, e to bude znít podezøele...
{30781}{30886}To je v poøádku. I kdyby to bylo podezøelé,|nemají jinou monost ne pøijet.
{30922}{31021}Dobrá tedy, pospìš si a vezmi si mou návnadu...Arimo Teppei.
{31111}{31149}Tati, mami.
{31170}{31236}Jdu to udìlat, jak jsem slíbil.
{31251}{31279}Nìjak to zvládnu.
{31571}{31613}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31628}{31670}www.mycolorfullife.blog.cz
{31880}{32045}-V ranním slunci a noci naplnìné sny, jsme se smáli jeden na druhého.-
{32045}{32213}-Èas, kterı jsem strávila s tebou, byl pro mì tak vzácnı.-
{32229}{32371}-Ah, to je nìco, co u se znovu nestane,-
{32371}{32553}-take se chci opìt shledat s tìmi vzácnımi dny, hned teï!-
{32553}{32588}-Sluncem jasnı den-
{32588}{32736}-Celı svìt pøetéká láskou.-
{32752}{32905}-Tak jestli je tu nìco nepøíjemného, tak na to zapomeò.-
{32905}{33104}-Kvùli jasnému zítøku,-
{33111}{33380}-i kdyby to byla cesta oklikou, jdu napøed krùèek po krùèku.-
{33702}{33721}Nicménì, mám otázku.
{33721}{33764}Co znamenají ty nohy na motorce Teppeie-dono?
{33764}{33823}Jsou to vlastnì repliky nohou Charlotte-sama.
{33823}{33872}Teï, kdy se o tom zmiòuješ, to vypadají, jako kdyby byly ukradeny.
{33872}{33934}Pøíštì v Princess Lover! JÍZDA NA KOÒSKÉM HØBETU A VLAKY!
{33934}{34002}Shodou okolností, jsou teplé jako lidské a zvládnou støední vítr.
{34002}{34029}Aèkoli jsou to øízené støely?
