{1}{1}23.976
{70}{160}Nejdøív zasnoubení s Charlotte. Pak jsem pracoval s Arima Foundation...
{177}{323}Mùj plán kompletnì oškubat Arimu Isshina byl skoro kompletní.
{323}{399}Ale ty jsi se objevil v rozhodující chvíli.
{413}{436}Arimo Teppei!
{615}{630}Charl!
{657}{686}Teppei!
{743}{758}Teppei!
{854}{955}Teppei!!!
{1018}{1061}TaSHee's Gang uvádí
{1190}{1279}PRINCESS LOVER!
{1324}{1445}-Stojící sama, šeptala jsem, "Pojï a povzbuï mì!",-
{1470}{1572}-a slzy stékají jak vzdychám.-
{1599}{1807}-Necítím se tak trapnì, abych se sama pokusila otevøít dveøe.-
{1882}{2019}-Leštìná kousek po kousku, budu skvostnìjší, ne šperk,-
{2019}{2198}-chci záøit a tanèit dnes veèer u waltzu!-
{2198}{2354}-Nejlesklejší partner pro tebe, mùj nejlepší partner jsi ty.-
{2354}{2487}-Necítíš to stejnì? Chci to potvrdit, ale mùj hlas se chvìje...-
{2487}{2637}-Zavírám oèi a podávám ti ruku,-
{2648}{2794}-a èas se zastavil. Teï, pojï, co chceš dìlat?-
{2837}{3076}-Je to jen na tobì! Nakonec, u jsem všechno zprostøedkovala, ne?-
{3089}{3139}TENHLE OPENING U JSEM VÁNÌ NEPØEKLÁDALA,|NÌKOLIKRÁT MI TO STAÈILO ;))
{3483}{3528}Cítím se osamìle.
{3528}{3564}Seika-sama je na støeše?
{3588}{3655}Ano. Mìly bychom ji nechat o samotì.
{3684}{3723}Ah, u nemùu pokraèovat.
{3723}{3742}Je to pøíliš namáhavé.
{3759}{3815}Co je, Eriko? Vypadáš tak ochable.
{3815}{3838}Vzchop se.
{3878}{3907}To je pravda.
{3907}{3964}Prezidentka je momentálnì velmi nervózní.
{3964}{3996}Musíme bıt pozornìjší.
{4011}{4106}Musíme vzít na svá bedra provoz Spoleèenského Klubu.
{4146}{4165}Kdo jsi?
{4165}{4184}To je to prase.
{4184}{4231}Já jsem Nezu Haruhiko!
{4245}{4309}V tuto chvíli, na druhém konci svìta,
{4309}{4379}zaèala záchrana Charlotte-sama Hazelrink!
{4394}{4462}Kdy o tom pøemıšlím, Arima-sama vede tuto operaci se silnım tımem,
{4462}{4497}mé srdce je plné obdivu!
{4497}{4536}/Dìkujeme za chvíli strpení/
{4536}{4599}Neøíkaly jsme ti, e je to tajemství?!
{4599}{4643}Ukecané prase!
{4656}{4700}U to vím.
{4700}{4733}Já taky! Já taky!
{4827}{4859}Nezu!
{4859}{4916}P-Prosím, buïte jemné, dìvèata!
{4916}{4968}Mìl jsem svoje dùvody!
{4981}{5045}Ptali jsme se ho.
{5045}{5151}Protoe Seika-sama se nechová jako obvykle.
{5151}{5187}Bylo to pochopitelné.
{5236}{5303}Je kruté nechat ji to bøemeno nést samotnou.
{5321}{5377}Kdy èelíme dùleitım zkouškám a vìcem,
{5377}{5449}jedinì lidé, kteøí sdílejí bøímì jsou hodni nazıvat se pøáteli.
{5460}{5525}Toto ke Spoleèenskı Klub Akademie Shuuhou.
{5588}{5626}Hezky øeèeno!
{5683}{5735}Toto je poslední epizoda!
{6080}{6144}Mìla bych jít...?
{6215}{6261}Je obtíné bıt enou, kterou oèekávají...
{6281}{6367}PRINCESS LOVER!|/PRINCEZNIN MILENEC!/
{6503}{6527}Teppei...
{6769}{6810}Nemìl jsem na vıbìr,
{6810}{6832}ale to nevadí.
{6850}{6903}Co bych mìl øíct Isshinovi?
{6926}{7009}Co mám udìlat, Charlotte?
{7155}{7249}V kadém pøípadì, to a poté, co dorazíme do Kníectví Hazelrink,
{7249}{7294}budeme mít èas na pøemıšlení.
{7294}{7328}Musí to bıt tìsné.
{7328}{7386}Uvolním pro tebe ten provaz.
{7466}{7529}Nemìj tak dìsivı vıraz.
{7553}{7670}Znièím dìdice Arima Group, kterı tì unesl, Hazelrinkskou Princeznu.
{7670}{7754}Já, Harman, se vrátím jako vítìz.
{7778}{7807}Co to øíkáš?!
{7807}{7847}Nikdo nebude vìøit takovım lím!
{7867}{7978}Lidé na svìtì se nestarají zdali nìkdo le.
{7978}{8043}Lidé vìøí tomu, èemu chtìjí vìøit.
{8043}{8137}Jestli jsou lidé ochotni vìøit, li se stanou pravdou.
{8137}{8221}Navíc, je jednoduché, aby lidé uvìøili.
{8233}{8329}Je to pravda, je to bìné.
{8357}{8435}Vskutku, lidé vìøí ostatním.
{8435}{8474}Ale to protoe jsou ochotni vìøit!
{8495}{8542}Lidé jsou krásná stvoøení.
{8542}{8597}Nemìli by bıt zlí.
{8597}{8649}Vdycky jsem tomu chtìla vìøit!
{8649}{8692}Jsi opravdu princezna.
{8692}{8754}Všechno co øíkáš, nechává lidi v respektu.
{8754}{8823}Pravdìpodobnì nemáš zkušenosti se zklamáním z vìcí, kterım vìøíš.
{8839}{8855}Ne.
{8879}{8931}Dìkuji za tvou upøímnost.
{8955}{9029}Ale tvá slova na mì nepùsobí.
{9265}{9396}Já, První Princezna Kníectví Hazelrink, Charlotte Hazelrink,|pokornì ádám.
{9427}{9461}Prosím, zachraò tu osobu.
{9483}{9537}Pokornì odmítám.
{9537}{9597}Ona tì opravdu miluje.
{9597}{9623}Vìøila v tebe.
{9623}{9651}Já vím.
{9651}{9671}Take...
{9671}{9743}Proè ji nezachráníš sama, Princezno?
{9757}{9777}Dobøe.
{9949}{10077}Oh, to je poprvé co neseš nìco tak tìkého?
{10090}{10185}Hartmane, víš proè chci tu osobu zachránit?
{10185}{10202}Ne.
{10234}{10327}Kdyby osoba, které vìøím nejvíc byla tady,
{10327}{10396}jistì by udìlala tu samou vìc.
{10412}{10474}Arima Teppei by to jistì udìlal.
{10672}{10715}Oh, jsi koneènì zpátky?
{10715}{10734}Promiò.
{10756}{10793}Èekali jsme na tebe.
{10793}{10847}Boooe. To je rozhodující moment.
{10850}{10912}Mìl bys bıt na její stranì.
{11119}{11149}Pìknı úlovek!
{11149}{11192}Myslel jsem, e jsem mrtvı.
{11192}{11262}Omdlel jsi kvùli nìjakému škrábnutí?
{11262}{11277}Kde je Charlotte?
{11291}{11363}Je s Hartmanem v prvním vagónì.
{11373}{11396}Dobøe, následujme je.
{11412}{11456}Alfrede-dono, rychleji.
{11456}{11481}To je nemoné.
{11481}{11491}Heh?
{11509}{11601}S tøemi osobami na tomhle vozidle, je nemoné je dohonit.
{11601}{11641}Kluku, sesedni.
{11641}{11666}Vánì?
{11666}{11693}Vánì!
{11717}{11758}Kámen je první!
{11758}{11800}Nùky, papír, kámen!
{11800}{11824}Johoo!
{11863}{11968}Mìl jsi zpodìní! Moc pomalu, to se nepoèítá!
{11968}{12017}Nesouhlasíme ještì s jedním pokusem?
{12017}{12051}Beru zpìt, co jsem øekl!
{12051}{12104}Boeee, vánì...
{12117}{12145}Jedna, dvì...
{12145}{12166}Nùky, papír...
{12175}{12215}Nemoné!
{12215}{12231}To je...
{12231}{12276}nevìøím tomu!
{12392}{12420}Co mám dìlat?
{12497}{12518}Princezno!
{12518}{12539}Pomùeme vám.
{12539}{12572}Vy dva...
{12572}{12625}Oba dva jsme studovali medicínu.
{12625}{12648}Pomùeme vám ji ošetøit.
{12719}{12738}Dìkuji!
{12763}{12829}Jestli je nìco, co mùu udìlat, prosím, øeknìte mi to.
{12935}{12965}Yuu-san, to jsem já!
{12965}{12980}Slyšíš mì?
{13016}{13032}Yuu-san!
{13056}{13097}Teppei-sama, jste v poøádku?
{13110}{13150}Omlouvám se, ztratili jsme je.
{13150}{13198}Prosím najdi mi cestu, díky které je dohoním.
{13221}{13271}Ano, Pane.
{13284}{13346}Teppei-dono, mùu vystoupit jestli chceš jet rychleji.
{13346}{13368}Ne!
{13831}{13848}Teppei-sama?
{13848}{13866}Poslouchám tì!
{13879}{13896}Povedu vás.
{13896}{13963}Na tøetí køiovatce, zahnìte doprava.
{13963}{14033}Cesta není moc dobrá, ale motorka  by ji mìla bıt schopná zvládnout.
{14033}{14046}Rozumím!
{14341}{14370}Berou to zkratkou!
{14370}{14419}Ihned informuj Hartmana-sama!
{14488}{14533}Jak oèekávané od královského vlaku.
{14533}{14563}je tu opravdu všechno.
{14563}{14624}S tím ji mùeme nìjak zachránit.
{14624}{14660}Proè jste pøestali studovat?
{14660}{14725}Oh, nemohl jsem zaplatit vıdaje.
{14725}{14776}A já jsem nezískal stipendium...
{14776}{14842}Tak jsem si našel tuhle práci na internetu.
{14842}{14908}Vlastnì je to trochu trapné.
{14908}{14986}Omlouvám se... Nemùu nic dìlat...
{14986}{15030}To neøíkej .
{15045}{15130}Aèkoli jsou naše záchranné schopnosti dùleité,
{15130}{15229}lidé jako ty, kteøí stojí po boku jsou také dùleití.
{15229}{15282}Oh, hezky øeèeno!
{15282}{15304}Já vím.
{15327}{15349}Dìkuju.
{15372}{15402}To je Arima Teppei!
{15415}{15447}Teppei!
{15447}{15469}Coe?!
{16267}{16283}Pojïme!
{16373}{16390}Nestøílejte!
{16408}{16423}To je Charlotte!
{16423}{16440}Vıbornì!
{16472}{16488}Teppei!
{16510}{16523}Charl!
{16538}{16585}Vìdìla jsem, e jsi v poøádku!
{16708}{16756}Silvie, postarej se o motorku!
{16811}{16839}Poèkej na mì, Charl.
{16839}{16868}Zachráním tì!
{16993}{17033}Vrátím se potom, co zachráním Charl.
{17033}{17048}Poèkej na mì!
{17063}{17102}Jsi tak unáhlenı...
{17121}{17196}Ale to mám na tobì ráda.
{17242}{17266}Silvie!
{17266}{17298}Ignorujte tu enu!
{17298}{17343}Arima! Chyte Arimu Teppeie!
{17424}{17512}Kam mùeš utéct v tomhle úzkém vagónu?
{17541}{17590}Teppei! Teppei!
{17628}{17645}Je tam!
{17766}{17795}Zabijte ho!
{17826}{17839}Huh?
{17854}{17873}Proè rychlost...?
{17888}{17947}Oh ne, znovu jsme byli opuštìni!
{17947}{17991}Co budeme dìlat?
{18157}{18174}Rozèiluješ mì.
{18174}{18237}Neutíkej volnì, kdy jsi rukojmí.
{18518}{18547}Jaké pøekvapení.
{18547}{18599}Mìl bys bıt mrtvı.
{18615}{18658}Moji pøátelé mì zachránili.
{18677}{18745}Ale tentokrát, tì ani pøátelé nezachrání.
{18804}{18850}Zkoncuju to s tebou.|/ach, ach, aaaaach... on je tak coooool :D/
{18850}{18870}Teppei!
{18887}{18925}Je to v poøádku, Charl.
{18939}{18978}Lhal jsem ti nìkdy døív?
{19041}{19073}Zachráním tì!
{19073}{19096}Vrátíme se spoleènì!
{19112}{19122}Ano!
{19181}{19197}Hartmane.
{19223}{19293}Pøemıšlel jsem o tom, co jsi øíkal.
{19293}{19326}Na co naráíš?
{19344}{19432}Na incident v hotelu a mım dìdou|vzhledem k tvojí èinnosti kapsáøe.
{19474}{19535}Nepokoušel se tì urazit.
{19564}{19591}O èem to mluvíš?
{19591}{19647}Opravdu jsem byl uraen!
{19647}{19668}Pleteš se!
{19668}{19693}Jak?!
{19798}{19865}Vím na co v ten moment dìda myslel.
{19881}{19920}Vìøil ti.
{19920}{19964}Chtìl aby se's stal èestnìjším!
{19964}{20010}To je nìco, co øeknou jen bohatí lidé!
{20060}{20076}Teppei!
{20092}{20155}Další vıstøel bude v tvojí hlavì.
{20170}{20248}To nemá nic spoleèného s bohatstvím.
{20248}{20282}Lidé jsou lidé.
{20282}{20324}Jsou dobøí i špatní.
{20324}{20377}Tak to vidím.
{20396}{20448}Ale mùj dìda ti vìøil.
{20448}{20488}Myslel si, e se mùeš bıt lepší.
{20508}{20587}Myslel jsi, e si vybereš správnou cestu.
{20587}{20604}Ticho!
{20604}{20651}Øekl jsem ti, pøestaò s tou okázalou rozmluvou!
{20683}{20713}Yuu-san mi øekla...
{20749}{20840}Cokoli co na tomto svìtì existuje je nezbytné!
{20861}{20922}Sám si vybíráš vlastní cestu!
{20954}{20990}Seika-san mi øekla...
{21015}{21111}Jak tvoje postavení stoupá, budeš potøebovat |charakter, kterı to splòuje.
{21129}{21177}Silvie mi øekla...
{21193}{21294}Mùeme pøenášet pocity bez toho, abychom cokoli øekli.
{21294}{21418}To je dùvod, proè Hartman, pøemıšlet o tom, proè jsi tady.
{21449}{21568}Najdi pøátelé s vysokım charakterem a pøátele, |kteøí mùou pøenášet pocity bez vyøknutí slova!
{21579}{21600}Jak jsem øekl..
{21600}{21648}pøestaò s tou okázalou rozmluvou!
{21778}{21792}Co se stalo?!
{21792}{21813}Vıbuch?
{21840}{21911}Já, Hartman, nebudu potlaèen Arimou!
{22114}{22150}To není dobré!
{22150}{22184}Charl, utíkej!
{22184}{22211}A Hartman?
{22211}{22237}Oh, to je pravda.
{22253}{22282}Ty taky!
{22331}{22397}U je moc pozdì, pro mì nebo pro vás.
{22418}{22486}Nechte mì øíct nìco zábavného.
{22527}{22589}Ten, kterı zabil tvé rodièe...
{22589}{22620}Jsem byl já!
{22669}{22716}V ten moment jsem nevìdìl...
{22716}{22782}e Isshinova dcera je stále naivu.
{22799}{22847}A e porodila syna.
{22847}{22892}To mì docela nudilo.
{22968}{22984}Charl mi øekla...
{23023}{23062}Kdy jsem naivu...
{23080}{23162}Kdy stále myslím na osoby mì drahé...
{23162}{23204}Tak jsou ti lidé stále naivu!
{23220}{23255}To je to, co jsi mi øekla!
{23255}{23283}Teppei...
{23301}{23367}Máma a táta ijí v mém srdci!
{23385}{23452}To proto omlouvám tvé zloèiny!
{23694}{23733}Znovu se zvedni!
{23733}{23802}Pøemıšlej o tom, zdali dìláš dobré nebo špatné vìci!
{23802}{23827}Teppei!
{23827}{23842}Charl!
{23883}{23937}Nebuï tak nafoukanı, spratku!
{23937}{23980}Stejnì u všechno skonèilo!
{24068}{24127}Øekl jsem ti, a zaèneš znovu!
{24141}{24154}ij!
{24755}{24775}Silvie!
{24775}{24842}Pìknì chyceno, e?
{24842}{24896}Pìknì chyceno!
{24929}{24961}B-Byl jsem zachránìn!
{24978}{25036}To není Milady!
{25053}{25076}Co to dìláte?!
{25076}{25132}Partyzánskı hod!
{25751}{25806}P-Promiò, Mario-sama.
{25841}{25865}U je konec?
{25885}{25897}Ano.
{26012}{26043}To jsem já.
{26043}{26074}Všechno skonèilo mírumilovnì.
{26074}{26194}Vypadá to, e se budu ještì hodnì hádat se Silvii|ohlednì otázky, jestli zùstat v naší vlasti.
{26194}{26221}Chápu.
{26221}{26316}Take v rodinì van Hossen právì zaèal zápas?
{26437}{26456}Teppei!
{26456}{26483}Charl!
{26560}{26597}Jak jsem øekl...
{26597}{26674}Ale, ty jsi opravdu pøijel!
{26694}{26740}Teppei!
{26755}{26783}C-Charl?!
{26783}{26806}Co to dìláš?
{26843}{26866}To je dík.
{26866}{26889}Dík...
{26889}{26949}Ano ale, nezacházíš moc daleko...?
{26949}{26992}Ale já jsem tak šastná!
{26992}{27028}To vidím!
{27028}{27055}Jsem taky šastnı!
{27055}{27102}Take, v èem je problém?
{27102}{27169}Teppei, pojeï. Takhle. Takhle. Takhle.
{27188}{27200}Charl!
{27200}{27217}Tam ne...
{27217}{27267}Oh, tìší mì!
{27284}{27329}Nestydaté!
{27387}{27429}Všem èlenùm Spoleèenského Klubu...
{27459}{27523}Dnes ráno mi bylo øeèeno, e jste všichni v poøádku.
{27542}{27571}Budeme zaneprázdnìni!
{27643}{27666}Díkybohu.
{27666}{27721}Seika-sama se objevila s dobrou náladou!
{27951}{27978}Hartmane-sama...
{28182}{28235}Zdá se, jako bych tu nebyl vìènost!
{28235}{28254}Jdete pozdì.
{28254}{28312}Hosté èekají!
{28312}{28394}Vítejte zpátky, Arimo-sama!
{28408}{28465}No... Na zpáteèní cestì se toho tolik stalo...
{28465}{28498}Pøestaò se omlovat.
{28520}{28533}Charl.
{28545}{28566}Vypùjèím si ho na chvilku.
{28586}{28612}Jen do toho.
{28629}{28688}Huh? Poèkej... Co?
{28688}{28708}Seiko-san?
{28722}{28803}Vánì, chtìl jsi ztrapnit enu, která na tebe èekala?
{28803}{28874}Navíc, vy dva jste se dreli za ruce pøímo pøede mnou.
{28874}{28914}To nic...
{29030}{29074}Myslel jsem si, kdyby...
{29093}{29168}Kdyby máma a táta byli stále naivu...
{29187}{29272}Kdybych tehdy uvidìl Charl v tom koèáru...
{29297}{29321}Kdybych...
{29342}{29440}Ano, udìlal jsem spoustu rozhodnutí.
{29440}{29483}To proto jsem tady.
{29483}{29564}Je to zázrak.
{29564}{29643}Místo, kde jsme. To není "kdyby".
{29663}{29785}To místo kde jsi, je také naše volba.
{29785}{29850}Ano, toto je zemì zázrakù.
{29850}{29912}Nemùeme se vrátit zpátky.
{29912}{29963}Nemùeme litovat.
{29963}{30035}Realita ve jménu zázrakù.
{30035}{30143}Ty a já, svìdèíme této realitì.
{30143}{30171}Navìky.
{30171}{30229}Ano, navìky.
{30229}{30290}Dokud naše ivoty neskonèí.
{30290}{30345}Take, úsmìv.
{30345}{30398}Dej do toho všechno a usmìj se...
{30398}{30453}A potom, tancuj.
{30471}{30535}Na pódiu zázrakù!
{30535}{30565}Navìky!
{30565}{30616}Ano, navìky!
{30828}{30842}Coe?!
{30854}{30902}Vykládáš si to stejnì?!
{30902}{30999}Ano, Grand Hazelrink byl znièen.
{30999}{31102}Filmishská vinná réva byla také poškozena.
{31102}{31146}Ale nebojte se.
{31146}{31231}Zaplatit to není pro Arima Foundation problém.
{31231}{31269}Všechny ztráty byly zaplaceny.
{31279}{31347}No... Platit hotovì, to je docela...
{31347}{31528}Moná byste se mohl omluvit a podìkovat zasaenım lidem osobnì?
{31734}{31789}Nakonec si opravdu neumím zvyknout na veèírky.
{31789}{31812}Au...
{31988}{32028}Nemohl bych vzdorovat...
{32052}{32104}Kdybych to vìdìla, oblékla bych si nìjaké hezèí.
{32104}{32116}Huh?
{32116}{32154}Nic, to nevadí!
{32167}{32187}Oh, to je pravda.
{32243}{32265}Omluv se a podìkuj.
{32265}{32334}Nemysli na to tolik. Pokecej si s nima.
{32334}{32364}Není to tvùj styl?
{32380}{32423}Styl, huh?
{32508}{32545}Omlouváš se? Dìkuješ nám?
{32545}{32571}Dárek?
{32571}{32618}V tomto pøípadì,
{32618}{32678}bychom mìly bıt ty, které ti dìkují.
{32678}{32748}No, syšel jsem, e vinná réva byla hodnì ponièená...
{32748}{32821}A myslel jsem si, e jsem pøidìlal Filmish problémy...
{32846}{32909}Maria chce od onii-chan dárek!
{32909}{32932}Hej, Mario!
{32956}{33027}Teppei-dono, je tu vhodnìjší osoba k hovoru, správnì?
{33169}{33200}Proè jsi tak vzteklá?
{33200}{33262}Protoe jsem byla poslední osoba, ke které jsi se obrátil.
{33262}{33358}Ale, tvoje zemì mìla nejvìtší ztráty, správnì?
{33369}{33449}Jeden nebo dva vlaky jsou nic.
{33449}{33509}Nakonec nerozumím ekonomické situaci.
{33509}{33577}Jsem poslední!
{33577}{33623}No... Promiò.
{33664}{33694}Dìlám si legraci.
{33694}{33742}U by jsi mìl znát odpovìï.
{33742}{33765}Opravdu?
{33783}{33861}Všechno je jen na tobì!
{33873}{33929}KONEC|/Všem, kteøí to zvládli a sem patøí mùj velkı dík ;) |Nakonec to nebylo tak špatné, jak jsem si ze zaèátku myslela.|Tìším se u pøíštího projektu./
{33929}{33984}Pøeklad + korekce + èasování: WelW(etkaAa)-hime|www.mycolorfullife.blog.cz
