{1}{1}23.976
{450}{509}Teppei! Pojï sem a pomoz mi!
{509}{548}Jo. U jdu.
{710}{746}Ah, skonèil jsi s kadodenní praxí?
{746}{791}Jsem na cestì do sprchy.
{839}{882}Tak pojï, u je to dlouho.
{882}{927}Jsi si jistı, e jsi pøipravenı?
{962}{1061}Samozøejmì! Jestlie nade mnou chceš uspìt,|mìl bys radši jít a pomáhat!
{1061}{1112}Co tím myslíš, uspìt nad tebou?
{1112}{1159}Mám spoustu vìcí, které chci taky dìlat!
{1194}{1230}Myslíš sprosté vìci?
{1230}{1273}No, myslím na nì.
{1319}{1364}Co máte vy dva za lubem!?
{1364}{1417}Teppei, øekla jsem ti, abys mi pomohl!
{1417}{1486}Zlato, co to sakra dìláš s vìcmi na prodej?!
{1486}{1573}Vánì, je to jako kdybych mìla v domì dvì malé dìti.
{1704}{1741}Itadakimasu!
{1857}{1918}Minulou noc kolem 7 veèer, na ulici ètvrti Shibuja,
{1918}{1963}se zùèastnil padesáti pìti letı Saeko, také z té samé ètvrti,|tragické dopravní nehody, která se tu noc stala.
{1963}{2005}Zdá se, e jich v poslední dobì bylo hodnì.
{2005}{2046}Jediní postiení jsou bohatí lidé.
{2046}{2126}Podle policie, byl incident byl podobnı| jako loòskı pokus o vradu ve mìstì.|/Nemá to s náma nic spoleèného./
{2210}{2310}Teppei, kdyby se stalo, e bys byl|zapojenı do takové vìci, co bys dìlal?
{2350}{2416}Co tím myslíš? Jediní, kdo jsou|zamìøení jsou boháèi.
{2416}{2446}Povídám, "co kdyby".
{2477}{2517}Co kdyby, eh...?
{2615}{2670}No,  nìjak bych se s tím vypoøádal.
{2756}{2790}"Nìjak se s tím vypoøádat", eh?
{2829}{2870}Co bys dìlal v takovém pøípadì ty?
{2870}{2901}Není to jasné?
{2917}{2925}Nìjak se s tím vypoøádat.
{2984}{3075}Jeez. Jsou opravdu jako dvì dìcka v domì.
{3075}{3109}Oh, sakra!
{3126}{3155}Zase máš zpodìní?
{3155}{3194}Ještì to nevíš!
{3255}{3311}Teppei! Nedovolím ti jet na motorce!
{3311}{3390}Tvoje uèitelka mi poslednì vynadala.
{3390}{3449}Jedu jenom k místu blízko školy!
{3449}{3486}Neodmlouvej mi!
{3486}{3509}Promiò!
{3574}{3621}Aaaah. Komu se vlastnì podobá...?
{3635}{3660}Jeho matce, správnì?
{3671}{3734}A co ty poøád dìláš s vìcmi, |které jsme pøedpokládali prodat!?
{3734}{3754}Omlouvám se!
{4004}{4107}To bylo skuteènì naposledy, co jsem vidìl mámu a tátu.
{4282}{4333}TaSHee's Gang uvádí
{4441}{4538}PRINCESS LOVER!
{6643}{6740}EPIZODA PRVNÍ|UROZENÁ DÍVKA V KOÒSKÉM POVOZE
{6910}{7074}Tati, mami, bìhem tìchto dvou mìsícù,|jsem pochyboval...
{7074}{7098}/Rodina Kobayashi/
{7123}{7195}Myslím, e pùjdu do sídla pana Isshi.
{7240}{7293}Zajímá mì, proè èekal a do teï,|aby se pøede mnou objevil.
{7312}{7353}No, nìjak se to vyøeší.
{7679}{7727}Neuteèeš!
{7751}{7807}Tragická dopravní nehoda, která se stala...
{7857}{7923}Co budeš dìlat, Teppei?
{7956}{7976}Udìlám...
{8376}{8505}Milady, dokud jsem já, Alfred, stále|s vámi, nemusíte se nièeho bát.
{9068}{9091}Seer si to!
{9137}{9183}Jak nezdvoøilı mladík.
{9183}{9242}Ale opuštìní téhle hory bude...
{9243}{9287}Ty, vylez ven!
{9450}{9513}Wow! Tohle je vítìz.
{9577}{9604}Jsi v poøádku?
{9640}{9662}Ty jsi...
{9676}{9702}Kobayashi Teppei!
{9702}{9753}Neptal jsem se na tvoje jméno!
{9753}{9762}Dr se!
{9762}{9806}Nìjak se s nimi vypoøádám!
{9819}{9857}Správnì, tati?
{9942}{9994}Co je s tím klukem, myslí si, e je Mark Sullivan?
{9994}{10041}Pìknou cestu!
{10311}{10328}Seer si to!
{10386}{10402}Zatracené dìcko!
{10460}{10493}Drahı, ten èlovìk je...
{10493}{10585}Milady! Tady to bude trochu drsné,|prosím zùstaòte v koèáøe!
{10605}{10645}Jdeme na to.
{10645}{10706}Hej, zbavte se rychle toho spratka!
{10810}{10859}Ty bastarde, u toho mám dost, jdi k èertu!
{10945}{10966}Milady!
{10966}{11009}Pøestaò ty zatracenı...
{11040}{11062}Oops.
{11073}{11130}Tvoje pøedstavení u konèí.
{11151}{11177}Mám tì dost.
{11196}{11228}Bezcennı šupáku.|/To je ten dìdula?! :D/
{11243}{11270}Pryè s tebou!|/Fakt je to on :D/
{11502}{11535}Co to sakra je...?
{11535}{11555}Drahı!
{11698}{11732}Milady!
{12128}{12159}Drahı!
{12441}{12459}Milady!
{12940}{13009}Wow. To jim patøí.
{13110}{13150}Nepouštìj svého støáce dolù, staøíku.
{13150}{13225}Vdycky jsem si myslel, e bych mohl Milady ochránit.
{13225}{13312}Ale po tom všem, u nemám dùvod déle ít.
{13312}{13383}Pak ti vyplatím poslední pomazání.
{13457}{13537}Ale já nesmím odejít bez placení.
{13537}{13682}Ti, kteøí vztáhnou ruku na rodinu Hazelrink, spáchají |zloèin tak tìkı, e jej mùe splatit jedinì smrt!
{13975}{13989}Au...
{14045}{14100}Byl jsem zachránìn, protoe jednaly jako polštáøe?
{14300}{14343}Tady je taky jeden polštáø...
{14482}{14549}Hej, probudila jsi se, to je skvìlé!
{14561}{14593}Oh, dobré odpoledne.
{14614}{14658}Zajímá mì, jestli je moc brzo øíct "dobrı veèer".
{14674}{14702}Kde to jsme?
{14722}{14766}Proè jsem na takovém místì?
{14777}{14838}Neøíkej mi, e si nic nepamatuješ?
{14850}{14924}Pamatuju se do toho bodu, kdy|jsme se øítili dolù po horské silnici.
{14938}{15008}Ah! Stejnì, jak se jmenuju?
{15008}{15024}To ne!
{15049}{15067}Lhala jsem.
{15067}{15096}Charlotte.
{15113}{15157}Charlotte Hazelrink.
{15171}{15191}Ráda tì poznávám.
{15191}{15252}Stejnì, proè bys mìla vymıšlet takové li?
{15271}{15310}Jsem Kobayashi Teppei.
{15324}{15393}Charlotte Ha...zel...ri..nk?
{15405}{15417}Zní to jako jméno pro princeznu.
{15452}{15501}Ano! Protoe já jedna jsem.
{15511}{15571}Stejnì, jak mùeš poøád takhle lhát?
{15733}{15794}Ah! Promiò, neuvìdomil jsem si to.
{15805}{15852}Nejsem na takové vìci zvyklı.
{15863}{15947}A jsi zvyklı dotıkat se òader spící dívky?
{15974}{16005}Není to tak, jak si myslíš!
{16005}{16066}Nehoda! Jo, byla to nehoda... náhoda!
{16199}{16257}V poøádku, vìøím ti, Teppei.
{16271}{16339}Ponìvad nakonec jsi jedinı, kdo mì zachránil.
{16339}{16389}Co... take si's nakonec vzpomìla!
{16389}{16433}Jaké byly moje prsa na omak?
{16460}{16526}Nemám tušení o jakém "omaku" to mluvíš...
{16536}{16646}Mluvím o tom, jestli mají mui|opravdu rádi holky s velkıma prsama?
{16646}{16717}No...um...
{16730}{16805}Myslím, e to závisí na jednotlivci.
{16876}{16911}Tvoje motorka je rozbitá?
{16911}{16971}Ne, vlastnì je v lepším stavu, ne jsem si myslel.
{16984}{17003}To je úleva.
{17025}{17060}Milady!
{17122}{17146}Teï musím jít.
{17146}{17213}Dostanu vynadáno, kdy budu s neznámım klukem.
{17227}{17271}Aha. To je pìknì dìsivé.
{17287}{17338}Ale i tak, pouívat koòskı povoz je...
{17463}{17499}Dìkuji ti, Teppei!
{17914}{17935}/14 zpráv v hlasové poštì/
{17947}{18000}Oh sakra, musím pøinést mé zavazadla do toho domu!
{18426}{18455}Stále nikdo?
{18455}{18466}Ano.
{18493}{18571}Arima Isshin èeká, eh?
{18587}{18670}Jak jsem oèekával od syna své dcery.
{18715}{18793}Øekl jsem vám, e jsem byl zavolán Arimou Isshinem.
{18809}{18848}To je pìknì velké.
{18859}{18909}Ta vìc na tvıch zádech. To je katana, správnì?
{18941}{19000}Prosím zavolej policii. Tohle je zneuctìní|Swords and Firearms control.
{19000}{19016}Ano pane!
{19016}{19072}Huh!? P-Poèkejte chvíli!
{19072}{19088}Ty zùstaneš tady!
{19113}{19157}Poslouchejte mì!
{19157}{19177}Poèkejte!
{19226}{19293}Ta osoba je mım èestnım hostem.
{19314}{19359}Pobavte ho tak velkolepì, jak jen mùete.
{19371}{19430}H...Host pana Isshina...
{19444}{19513}H...Hej! Dostaòte ho!
{19525}{19544}Teppei.
{19557}{19585}Pojï se mnou.
{19656}{19698}Promiòte pane Isshine, jdu pozdì.
{19777}{19818}Nebudeš mi øíkat dìdeèku? /= grandpa/
{19857}{19898}Je to pro mì trochu náhlé.
{19911}{19937}Jak zní dìda? /= grandfather/
{19950}{19986}Dobøe, je to v poøádku.
{20012}{20028}Dìdo.
{20059}{20091}Rád bych se tì znovu zeptal.
{20107}{20124}Øekni to.
{20152}{20177}Je to pravda, ne?
{20239}{20298}Táta a máma nemìli nehodu.
{20423}{20474}Co budeš dìlat, kdy najdeš viníka?
{20486}{20507}Pomstím je.
{20531}{20564}A pak co?
{20582}{20649}Skonèíš jako další, kterı pøijme pomstu.
{20670}{20794}Opravdu chceš ít v tom nekoneèném|øetìzci utrpení a smutku?
{20807}{20882}Je tohle pro tebe poslední pøání Kanae a toho mue?
{20882}{20964}Nejsi smutnı, e tvá vlastní dcera zemøela?!
{20975}{20994}Hmm.
{21005}{21046}Teï mám tebe.
{21061}{21095}Nemám nikoho, ale tebe.
{21160}{21214}Um, budete veèeøet.
{21234}{21314}Jestli pùjdete takhle, vyplašíte hosty.
{21329}{21376}Oh ano, pøišel jsi pozxdì.
{21376}{21429}Co jsi dìlal, e jsi skonèil pozdì?
{21429}{21463}Nìkoho jsem zachraòoval.
{21483}{21512}Nìkoho jsi zachránil?!
{21596}{21649}V poøádku! Jdi dovnitø takhle!
{21667}{21743}Máš na sobì špinavé vìci, protoe jsi dìlal správnou vìc.
{21743}{21781}Není to nic ke skrıvání!
{21851}{21871}Je to opravdu ok?
{22245}{22315}Moji hosté, ti, kteøí setrvávají,|aby podporovali Arima Group,
{22315}{22445}Torishimiya a Onmyougi, funkcionáøi, dámy|a pánové, omlouvám se za èekání.
{22445}{22492}Dovolte mi vám pøedstavit
{22492}{22587}mého syna, Arimu Teppeie,
{22587}{22669}a následníka vedení Arima Group.
{22680}{22714}Huh!? Následník?!
{22781}{22858}Moná jste byli pøekvapeni jeho nepoøádností,
{22871}{22963}ale pøedtím, ne sem pøišel, nìkoho zachraòoval.
{22998}{23053}Oh ano, koho jsi zachránil?
{23065}{23115}Nìkoho jménem Charlotte Hazelrink.
{23217}{23297}Aha! Její vısost, Hazelrinkova dcera, eh?
{23297}{23343}Ta osoba je pøíliš mnoho.
{23343}{23381}Její vısost...?
{23403}{23447}Kníectví Hazelrink!?
{23447}{23476}Ona je opravdu princezna?!
{23476}{23526}Ah, jsem šastnı, e je tu tolik rozruchu.
{23526}{23600}Budi, i tak, s ohledem na jeho|momentální obleèení, které všichni vidíte,
{23600}{23649}bych se rád omluvil za jeho vzhled.
{23649}{23708}Prosím, dejte mu nìjakı èas, aby se obèerstvil.
{23708}{23767}Mezitím, si  prosím uívejte sebe.
{23848}{23900}Co je s tím vedoucím následnickım nesmyslem?!
{23924}{23997}Jen jsem pøijal adopci, abych se mohl pomstít!
{23997}{24042}Pak se sna.
{24065}{24165}Jsou tam lidé, kteøí tì neshledávají|zábavnım následníkem.
{24183}{24274}Chtìl jsem vìdìt, kteøí to jsou, tak jsem udìlal ten vtip.
{24288}{24308}Co tím myslíš?
{24326}{24364}Ty nevíš
{24377}{24442}Kanae byla opravdovou následnicí...
{24459}{24509}Opravdovou následnicí...
{24509}{24537}...take...?
{24537}{24609}Nepøítel se objeví ve správnı èas.
{24609}{24653}Musíš si první získat spojence.
{24666}{24718}Nestarej se o to, co se stalo.
{24729}{24802}Buï pøítel s tìmi, kteøí ti budou první nejblí.
{24880}{24953}Jak jsem èekal, Teppei-kun, vypadáš jako tvùj otec.
{24998}{25061}Dovol mi se ti taky pøedstavit.
{25061}{25118}Jsem Todomura z odborné komise|Arima Group!
{25118}{25146}Rád vás poznávám.
{25146}{25189}J-Já také.
{25250}{25278}Nìkde tady...
{25278}{25295}Omluvte mì.
{25295}{25376}Je tu mnoho dospìlıch. Není nutné,|aby byl takovı dav na jednom místì.
{25376}{25405}Má stále strach.
{25405}{25439}Sire Hossene!
{25439}{25473}Sir Hossen?
{25482}{25591}Jako osobní doprovod pana Arimi, se ptám, jestli|je nìco, o èem byste rádi mluvili?
{25591}{25671}Oh, nic, co by vás mohlo zajímat, sire Hossene.
{25722}{25769}Jak nevzhlední, eh?
{25769}{25866}Kadı za vámi pøijde a doufá,|e Isshin rychle zemøe.
{25881}{25927}Nepøedstavil jsem se, e?
{25937}{25973}Jsem Vincent van Hossen.
{25984}{25999}Rád vás poznávám.
{26018}{26071}Byl byste rád, kdybych vám pøedstavil své dcery?
{26086}{26098}Jistì.
{26177}{26254}Tati, to je ten mladík, kterı se stal strıèkovım synem?
{26254}{26296}Neøíkej mu strıèek!
{26296}{26382}Omlouvám se, roste tak rychle, ale|stále si neuvìdomuje své manıry.
{26393}{26414}To je ok.
{26490}{26512}Ahoj.
{26521}{26560}Jmenuji se Maria van Hossen.
{26583}{26613}Jsem Arima Teppei.
{26613}{26633}Rád tì poznávám.
{26633}{26686}Vypadáš nervóznì.
{26695}{26737}Heh, opravdu?
{26749}{26786}Kde je Silvie?
{26786}{26840}Onee-chan nìkam šla.
{26840}{26898}Eeeh?! Beznadìjné.
{26898}{26950}Omlouvám se Teppei-kun, dnes...
{27019}{27074}Kdy pøichází pan Isshin, atmosféra se |kompletnì mìní.
{27074}{27115}Má úasné charisma.
{27115}{27135}Máte pravdu.
{27135}{27183}Také cítíme to samé i k tobì.
{27183}{27195}Eh?
{27208}{27245}No, mìl by sis na to teï víc zvykat.
{27245}{27282}Budu se pohybovat kolem.
{27295}{27321}Uvidíme se pozdìji, onii-chan!
{27376}{27407}Teppei-sama, mohu já?
{27426}{27472}Ah, poèkejte, pøestaòte!
{27498}{27574}Ne, nechápu ty lidi.
{27584}{27634}Jen mluvit s nimi mi bere všechno, co mám!
{27658}{27676}Ah, dìkuju.
{27687}{27730}A do teï jsi byla opravdu milá.
{27757}{27782}No, jsem sluebná.
{27801}{27840}Sluebná? Opravdu?
{27851}{27885}Jak jinak mì vidíte?
{27899}{27989}No, je pravda, e nevidím nic jiného, ale sluebná...
{28013}{28044}Opravdová sluebná, huh...?
{28476}{28504}Teppei-sama, kam jdete?
{28504}{28596}V dobách, kdy nevíš, co dìlat|je nejlepší protáhnout si tìlo!
{29241}{29265}Nahání to hrùzu.
{29317}{29384}Vdycky jsem chtìl zápasit se Západními šermíøi!
{29384}{29407}Ty ohavnı chlape.
{30328}{30349}Tady pøestaòte!
{30463}{30480}Otèe!
{30480}{30499}Huh?
{30511}{30549}Jsou perfektní soupeøi, ne?
{30582}{30600}Perfektní soupeøi?
{30633}{30713}Onii-chan je stejnì silnı jako Onee-chan, e?
{30726}{30798}Je trochu brzo øíkat mu Onii-chan, Mario.
{30798}{30861}Zachránil jsi mì pøed pár problémy, Teppei.
{30946}{31041}Mìl bys znát kadého, s kım bojuješ, Teppei.
{31069}{31129}Ona je Sylvia van Hossen.
{31147}{31184}Je to tvá snoubenka.
{31197}{31245}Eh? Snoubenka?!
{31810}{31879}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{31907}{31952}www.mycolorfullife.blog.cz
