{1}{1}23.976
{3129}{3160}Salonek pro uèitele
{3182}{3197}Tady.
{3221}{3254}Summit pro nejlepší studenty základní školy.
{3256}{3280}Summit?
{3288}{3387}Ano. A vy dva bude reprezentovat naši školu.
{3387}{3471}Nejsem si jistá jestli to zvládnu…
{3471}{3549}Jestli se bude diskutovat o nìèem komplikovaném…
{3558}{3660}Není to nic sloitého. Berte to spíš jako exkurzi.
{3672}{3725}Eh, to je na dva dny a jednu noc.
{3745}{3784}Take tam budeme nocovat?
{3793}{3826}Je to u jezera.
{3874}{3920}Vılet s Tadase-kun?
{3996}{4064}Ah ne! Prosím,nech toho, Tadase-kun.
{4064}{4085}Je to zábava.
{4136}{4195}Dívej, Sirius.
{4211}{4282}Jsi tak chytrı, Tadase-kun!
{4403}{4446}Hej, Hinamori-san…
{4460}{4475}Ano!
{4493}{4532}Take…pojedete?
{4532}{4566}Samozøejmì!
{4802}{4844}Take nás budeš reprezentovat na summitu?
{4877}{4920}Hodnì štìstí, pøedsedo.
{4946}{4966}Ano.
{5088}{5126}Budeš mít šanci je znovu vidìt.
{5139}{5176}Mysli na to,Kairi.
{5210}{5247}Hinamori-san ...
{5270}{5287}Tady?
{5310}{5408}{C:$0000FF}{Y:bi}Pevná cesta soudrnosti! Kairi se vrací!
{5542}{5611}Všichni pojïte prosím sem.
{5624}{5722}Poté,co si dáte kufry do pokoje, jdìte prosím do prvního patra.
{5763}{5801}Pojïme!
{5816}{5867}To bude legrace!
{5867}{5890}Ano!
{5910}{5972}Nikoho tu neznám, bude to dobré?
{5988}{6054}Neboj se, skamarádíme se raz dva.
{6063}{6100}Uvidíme se za chvíli, ano?
{6100}{6118}Ano.
{6118}{6148}Pøedsedo!
{6183}{6199}Co se dìje?
{6199}{6251}Kterı pokoj je mùj?
{6265}{6284}Oh, chápu.
{6297}{6330}Co se dìje?
{6344}{6448}Kdy jsem slyšela volat ,,pøedsedo'', myslela jsem si, e by to mohl bıt Kairi.
{6459}{6567}Ah, protoe tu jsou studenti z mnoha škol, nebylo by divné kdybychom se tu s ním potkaly.
{6576}{6663}Sanjou-kun,co? Zajímalo by mì, jak se má.
{6672}{6749}Sanjou-kun, také známı jako pøedseda!
{6770}{6857}Byl na pozici Jacka pøed Nagihiko, jeho Shugo Chara je Musashi.
{6874}{6975}I kdy je mladší, je cool, inteligentní a nìkdo,| na koho se mùeme spolehnout.
{6980}{7136}Byl špeh Easteru, ale v koneèném boji se k nám pøipojil.
{7148}{7243}Ale pak se najednou vrátil do této základní školy.
{7271}{7329}Miluji tì, Hinamori-san! 
{7381}{7439}Nyní i do budoucna. 
{7455}{7489}Vdycky a navdy. 
{7502}{7537}Miluji tì.
{7574}{7599}Jednoho dne,
{7613}{7675}a se ze mne stane dobrı mu,
{7687}{7754}vrátím se pro tebe.
{7878}{7946}Amu-chan se èervená!
{7967}{7990}Neèervenám!
{7990}{8055}O co, e vím, na co sis vzpomìla?
{8064}{8095}Nechte mì u bıt!
{8132}{8166}Nestyï se!
{8200}{8215}Co je?
{8256}{8308}Cítíš tu pøítomnost?
{8320}{8339}Pøítomnost?
{8458}{8525}Páni, co tvé povinnosti summitního vıboru?
{8525}{8574}Udìlám je!
{8634}{8685}Jsi Saito-kun z Umesato základní,e?
{8699}{8761}Tvùj pokoj je ve støedu haly, hned za tebou.
{8773}{8823}Díky moc!
{8884}{8960}Nauèil ses nazpamì jména všech úèastníkù.
{9000}{9026}Hinamori-san…
{9043}{9131}Kairi, pokud ji chceš vidìt, neváhej a jdi za ní!
{9165}{9216}Nemohu se jí ukázat.
{9245}{9352}Takovı, jakı teï jsem, ji nemám právo vidìt.
{9370}{9433}Já to vìdìla! Je to Kairi a Musashi!
{9433}{9452}Amu-cha-!
{9464}{9543}P-Prosím,neøíkej jim, e jsem tady!
{9560}{9597}Pozdì...
{9620}{9647}Vìrní poddaní!
{9658}{9705}Kairi a Musashi jsou tady!
{9796}{9819}Kairi...
{9857}{9912}D-Dlouho jsme se nevidìli…
{10157}{10196}To je trapné.
{10207}{10271}Moná jsou tak nervózní, protoe je to tak dlouho?
{10271}{10353}Je to trochu sloitìjší…
{10400}{10462}Správnì! Vzmume se,poddaní!
{10539}{10643}Plíil jsem se a špehoval je. Jak hluboko jsem klesl?
{10672}{10785}Jsem najednou tak rozpaèitá po tom, co mi pøed odjezdem øekl…
{10800}{10883}Oh, to je zelenı èaj, e?
{11005}{11049}Jsi TO, Kiseki!
{11058}{11109}Nikdy mì nechytíš, pane TO!
{11109}{11133}Zastavte!
{11142}{11183}Myslíte si, e mùete uniknout od svého krále?!
{11220}{11241}Zastavte!
{11264}{11336}Kdy poprosíš, udìláme co chceš!
{11438}{11464}Vy…
{11464}{11484}Pøestaòte blbnout!
{11484}{11510}Pøestaòte!
{11798}{11863}Nervozita koneènì zmizela.
{11872}{11911}Ti tøi nám ale dali zabrat.
{11954}{12023}Aha, take ty ses stal prezidentem studentské rady?
{12023}{12098}Není to pro tebe tìké? Pøeci jen, jsi ve ètvrtém roèníku.
{12098}{12196}Trošku. They povídal, e jsem nejmladší prezident v historii školy.
{12207}{12233}To je super, Kairi!
{12246}{12293}Není to nic velkého.
{12306}{12409}Vzhledem k tomu, e máš tu pásku, znamená to, e jsi také souèástí Summit vıboru?
{12414}{12438}Ano.
{12438}{12518}Vdy jsi byl spolehlivı, Kairi.
{12533}{12597}Prosím, licho mi dál!
{12617}{12639}Pøíliš svìtlı!
{12658}{12761}Oh, Kairi… nikdy jsi nebyl schopen zabránit pøetékání hrdosti z chvály.
{12761}{12797}Eh, ani s brılemi?
{13047}{13072}Není dùvod k pláèi.
{13131}{13196}Zvedni to a dojdeme se pro nìco na vytøení.
{13196}{13221}Dobrá.
{13475}{13553}Nyní zaèíná summit. Doufám, e se vám všem bude líbit!
{13566}{13652}Pojïme poznat jeden druhého pomocí spousty zábavnıch her!
{13869}{13909}Kairi tvrdì pracuje.
{13922}{13963}Musím se od nìj hodnì nauèit.
{13976}{14004}Tohle bude zábava!
{14004}{14046}U se tìším!
{14129}{14208}Prosím, poslouchejte!
{14261}{14279}Co budeme dìlat?
{14301}{14341}Nemùeme hrát hry jako je tato.
{14376}{14400}Zdá se, e mají problémy.
{14419}{14450}Ano.
{14468}{14506}Nikaido-sensei?
{14613}{14672}Musíme se všichni soustøedit na Sanjou-kun…
{15253}{15287}Ran,zatoè vpravo!
{15287}{15313}Snaím se!
{15344}{15394}Musím upoutat spoustu srdcí!
{15413}{15491}To je sice krásné, ale teï øiï!
{15546}{15573}Tady jsme, Kairi!
{15573}{15616}Chy nás!
{15784}{15822}Èlen vıboru je tak cool!
{15822}{15855}Bylo to kouzlo? Krásné!
{15961}{16005}Jejich vtip pøišel akorát vèas,ne?
{16328}{16433}Nevím,jsem tu poprvé, ale je skvìlé, e to vše takhle dopadlo,e?
{16470}{16575}Ano,ale to vše bylo jen díky vám.
{16589}{16686}Ne tak docela, tys je vlastnì všechny usadil, Kairi.
{16686}{16711}To je pravda.
{16808}{16893}H-Hej, Pojïme zítra všichni k jezeru.
{16906}{17018}A-Ano! Máme zítra celı den volno, take ani èlen vıboru nemusí pracovat, e?
{17059}{17101}Pùjdeš s námi,souhlasíš?
{17218}{17286}Jdu si pro nìco k pití.
{17453}{17490}Proè jsi odešel?
{17504}{17544}Nemám na to.
{17544}{17629}Staèí trocha chvály, a jsem hned nadšenı.
{17641}{17676}Teï nad tím nepøemıšlej.
{17726}{17797}Co je s Kairim? Vypadá to, e se trápí.
{17832}{17887}Zajímalo by mì,jestli je tìké bıt ve vıboru?
{17954}{18006}To je celkem dobrá atmosféra, co se tam asi dìje?
{18006}{18047}Nemìli bysme je otravovat.
{18047}{18083}Vypadají spolu perfektnì, nemyslíš?
{18143}{18173}A mùeme jít také na loï!
{18173}{18193}JistÌ.
{18193}{18256}Dobrá, a tentokrát budu øídit, jak nejlépe to pùjde.
{18320}{18373}Hinamori-san, poèkáš tu na moment?
{18386}{18408}Ovšem.
{18497}{18564}Take jdeš do svého pokoje, ani bys nìco øekl?
{18574}{18597}To je v pohodì.
{18597}{18632}Poèkej, Sanjou-kun!
{18704}{18722}Kairi...
{18739}{18788}Myslí si, e mùe pøedstírat e nás neslyší?
{18796}{18821}Neodpustitelné!
{18870}{18905}Poèkej, bıvalı Jacku!
{18955}{18992}Mám ízeò!
{19000}{19048}Obslu svého krále nápojem!
{19076}{19118}Prosím, tady máte, mùj králi.
{19129}{19152}Kairi...
{19190}{19268}Zdá se, e tvé tìlo stále neodvyklo na úlohu, na kterou bylo navyklé.
{19322}{19367}O-Omlouvám se!
{19370}{19392}To je v poøádku.
{19479}{19511}Kde jsou?
{19547}{19572}Nechci...
{19586}{19629}vidìt Hinamori-san.
{19640}{19759}Mé nedostatky... nemám právo ji vidìt.
{19778}{19811}Nemìl bys takhle mluvit.
{19834}{19888}Ne, musím…
{19905}{20022}Dokud všechny mé pochyby, |e jsem na té správné cestì, nebudou pryè, nemohu ji vidìt.
{20022}{20046}Ale...
{20213}{20232}Hinamori-san…
{20244}{20288}A pøesto ji vidí vzápìtí…
{20315}{20355}Prosím, nezasahujte do toho.
{20382}{20450}Proè? Proè mì nechceš vidìt?
{20464}{20506}Protoe mi momentálnì chybí-
{20506}{20523}Na tom nezáleí!
{20556}{20621}Chci zjistit cestu pravdy!
{20621}{20717}V poøádku! Ale øekni mi, jak to chceš udìlat?
{20730}{20818}Myslím, e je obdivuhodné, e se snaíš, abys byl tím,kım chceš.
{20827}{20903}Ale nechápu, proè to znamená, e se nemùeme vidìt!
{20916}{20955}Co s tím, co se právì teï dìje?
{21062}{21111}Prosím, nech mì na pokoji.
{21347}{21408}Jdu se všemi do lesa!
{21408}{21476}Uvidím veverky a králíky!
{21495}{21557}Sanjou-san, jdeš nìkam?
{21654}{21686}Já...
{21796}{21845}Kairi nepøijde?
{21857}{21877}Ne.
{21919}{21995}Slunce je pryè.
{22027}{22055}Máme problém!
{22080}{22116}nìco se stalo!
{22163}{22197}Musíme to øíct vıboru!
{22402}{22492}Jsi si jistı? Všichni èekají u jezera.
{22544}{22631}Propána, aspoò si chvíli odpoèiò.
{22695}{22723}Budu muset odhodit mé váhání.
{22762}{22807}Proè mì nechceš vidìt?
{22856}{22926}Stal jsem se vhodnım muem pro tebe.
{22950}{23013}A proto musím zjistit cestu pravdy.
{23033}{23126}V poøádku! Ale øekni mi, jak to chceš udìlat?
{23158}{23177}Nevím...
{23193}{23218}Ale..
{23314}{23392}U jí nemohu ukázat svou ubohou tváø!
{23450}{23501}Co s tím, co se právì teï dìje?
{23672}{23742}Já jsem… právì teï…?
{23766}{23794}Kairi.
{23820}{23885}Úcta k ideálu druhıch je nezbytná, opravdu.
{23909}{24071}Nicménì, za tímto úèelem, není nutné nejprve pøijmout ty své,pøesnì takové,jaké jsou?
{24277}{24375}Samuraj…by se nestydìl za to co mu chybí.
{24387}{24511}Spíše by následoval své srdce,protoe by mohl vidìt Hinamori-san!
{24542}{24567}Dobøe øeèeno!
{24581}{24614}Jdeme k jezeru!
{24656}{24752}Sanjou-kun,problém! Saito-kun se ztratil v lese!
{24819}{24897}Dìti ze Seiyco akademie ho šli hledat, ale…
{24952}{24982}Musasi! Zmìna charakteru!
{24982}{25002}Ano!
{25205}{25245}Poèkej! Poèkej!
{25337}{25382}Ah, utekl.
{25462}{25482}Huh?
{25619}{25656}Saito-kun!
{25717}{25745}Amu-chan, Poèkej!
{25667}{25706}Jestli tu jsi,odpovìz!
{25755}{25802}Su shání informace!
{25822}{25841}Shání informace?
{25841}{25901}Ano, to je pravda, chlapec.
{25919}{25971}Vidìl jsi ho?
{26074}{26114}Musíme si pospíšit a najít ho døív, ne se zmìní poèasí!
{26158}{26229}Jelen?!
{26265}{26374}Zdá se, e Saito- kun honil králíka a zabìhl hloubìji do lesa!
{26374}{26435}Amu-chan tam u jde!
{26506}{26534}Šel tudy!
{26612}{26642}Saito-kun!
{26779}{26846}Saito-kun! Poèkej! Jdu za tebou!
{27091}{27112}Tadase-kun!
{27131}{27174}Jsi v poøádku, Hinamori-san?
{27219}{27251}Tolik jsem se bál!
{27260}{27300}U je to dobré!
{27310}{27337}Jsi zranìnı?
{27370}{27403}Ne.
{27517}{27554}Amu-chan!
{27564}{27594}Pojïme rychle zpátky!
{27597}{27615}Ano.
{28683}{28703}Kairi...
{28747}{28798}Jsem rád, e jsem to stihl vèas!
{28962}{28999}Jdeme, Sanjou-kun!
{28999}{29031}Ano, králi!
{29042}{29060}Já taky!
{29066}{29079}Ne.
{29132}{29192}Nech to na nás.
{29220}{29242}{C:$0000FF}{Y:bi}Mé srdce.
{29259}{29284}{C:$0000FF}{Y:bi}Mé srdce.
{29291}{29326}{C:$0000FF}{Y:bi}Odemknout!
{29591}{29634}{C:$0000FF}{Y:bi}Pøemìna charakteru  :  Platinum royal!
{29709}{29751}{C:$0000FF}{Y:bi}Pøemìna charakteru  :  Duše samuraje!
{29911}{29975}{C:$0000FF}{Y:bi}Svatá koruna speciál!
{30013}{30047}{C:$0000FF}{Y:bi}Èepel hromu!
{30610}{30646}Cool!
{30785}{30868}Byli vánì cool!
{30868}{30890}Ano. Ano.
{30893}{30956}Pøíštì se u do hor sám netoulej,ano?
{30961}{30979}Ano!
{31074}{31105}Odpus mi!
{31105}{31203}P-Proè se mi omlouváš? Zachránil si mì!
{31222}{31336}Protoe jsem se mılil kdy jsem øekl, e tì nechci vidìt, dokud se ze mì nestane vhodnı mu pro tebe.
{31375}{31506}Odteï budu ménì nervózní. Pokud mám pocit e tì chci vidìt, uvidím tì!
{31538}{31603}S-Správnì! To je to co znamená bıt pøáteli!
{31690}{31745}Amu-chan! Proè se èervenáš?
{31745}{31765}Sklapnìte!
{31816}{31913}Králi, jen proto, e jsi blízko ní, nepolevím.
{31955}{32003}C-Co jsi to právì øekl?
{32009}{32077}Je to jen chlapská vìc, e králi?
{32094}{32120}A-Ano.
{32127}{32195}To není fér! Øeknete mi to! Chci to vìdìt!
{32217}{32241}To je tajemství.
{32241}{32286}Hej! Kairi!
