{1}{1}23.976
{3277}{3303}Dobré ráno.
{3423}{3519}Nemùu uvìøit tomu, e jsem to udìlala. Co to se mnou je?
{3585}{3651}Víš, mìl bys spát na podlaze!
{3667}{3717}Jsem nemocnı a kromì toho…
{3717}{3783}to ty jsi mì sem dotáhla.
{3875}{3935}Dotáhla ho sem?
{3935}{3969}Nepleteš se?
{3969}{4022}Zachránila ho!
{4038}{4071}Ikuto!
{4071}{4113}Ikuto je ve velkém maléru!
{4248}{4287}Ikuto, co se dìje?
{4306}{4322}Amu…
{4322}{4345}Ikuto!
{4345}{4398}Je to špatné, nedıchá nya!
{4432}{4472}Neumírám…
{4591}{4654}Nemùu tì tu takhle nechat.
{4669}{4731}Pokud nemáš kam jít, pùjdeme zpátky ke mì domù.
{4775}{4817}To jsem øekla, ale…
{4888}{4940}Opravdu jsem ztracená, e?
{4969}{5071}{C:$0000FF}{Y:bi}Vzrušující bílı den!
{5098}{5145}Díky za jídlo!
{5165}{5240}Mmm! Dnešní snídanì je vynikající!
{5240}{5280}Mòam-
{5299}{5353}Nesnáším zelené papriky! 
{5353}{5428}Pokud nebudeš jíst zelené papriky, nevyrosteš!
{5428}{5530}Nevadilo by mi, kdyby má Ami-chan zùstala stejná jakou je teï.
{5562}{5599}Tatínku!
{5599}{5632}O-Omlouvám se!
{5632}{5662}Skonèila jsem.
{6067}{6092}Amu-chan
{6109}{6131}Ano?
{6155}{6183}Dìje se nìco?
{6183}{6326}Ah, nic, jen mì snídanì moc nenasytila. Take, mùu si to vzít?
{6326}{6406}Ovšem, ale banán a sušené sardinky?
{6413}{6450}Ano, vápník!
{6466}{6541}Slyšela jsem, e Japonci nemají v této dobì dostatek vápníku, víte!
{6748}{6779}Sušené sardinky,nya!
{6943}{6971}Tady, banán.
{6971}{7022}Mùeš jíst, ne?
{7084}{7111}Nebudeš jíst?
{7120}{7190}Myslíte, e ještì nikdy nejedl banány?
{7190}{7245}Musíš ho oloupat.
{7245}{7291}On mùe jíst banány nya.
{7291}{7404}Ale banány nejsou pro koèky moná moc dobré.
{7771}{7831}Nemáš hlad? Je ti dobøe?
{7831}{7890}Jistì, mìl jsem dobrı spánek.
{7887}{7907}Ale...
{7960}{8032}Jen nechci skonèit tak tlustı a vlnící se jako ty.
{8055}{8108}Nejsem tlustá!
{8218}{8242}Tadase.
{8281}{8363}Je tady ještì stále dost valentınskıch èokoládek.
{8363}{8438}Protoe jsem je pøijal, musím je všechny sníst.
{8972}{8989}Hej.
{8989}{9006}Co?!
{9006}{9049}Nemáš ještì nìjaké?
{9049}{9098}Ne! To vychází jen jednou mìsíènì!
{9112}{9174}Amu-chan. Je Ikutem posedlá, ne?
{9174}{9254}Nemùe se soustøedit ani na studium.
{9254}{9325}Myslím, e není správné, e je Ikuto tady…
{9362}{9382}Co je?!
{9404}{9442}Co se dìje, Amu-chi?
{9442}{9464}Zlobíš se?
{9496}{9513}Promiò, Yaya.
{9513}{9548}Stalo se pár vìcí.
{9581}{9611}Take, co potøebuješ?
{9620}{9709}Chystala jsem se jít podívat do pár obchodù a napadlo mì, jestli bys nechtìla jít se mnou.
{9709}{9737}Obchodù?!
{9790}{9823}Dnes se mi to nehodí…
{9830}{9909}Ehh! Ale vèera si ještì chtìla jít!
{9909}{9948}J-J á vím…
{9960}{10007}Ale...Existují polehèující okolnosti…
{10094}{10136}Huh? Co? Co?
{10141}{10243}Tak to je! Omlouvám se, pa!
{10345}{10373}Co je?
{10373}{10411} Nic!
{10452}{10490}S-Strašidelné!
{10661}{10749}Kiseki,nemyslíš si, e dnešní pohled je naprosto geniální?
{10749}{10815}Opravdu? Podle mì to vypadá stejnì jako jindy.
{10877}{10929}Hotori-kun, nìkam jdeš?
{10945}{10967}Fujisaki-kun.
{10978}{11022}Ano, já jen…
{11095}{11146}To mùe bıt pro bílı den?
{11221}{11291}Ehm, pokud se nepletu, tímto smìrem je to k …
{11291}{11342}Nech toho! Tak to není!
{11347}{11372}Rád jsem tì vidìl!
{11646}{11691}Tak ses nakonec rozhodl…
{11934}{11972}Tak a dost-!
{11972}{11995}Sestøi!
{11995}{12019}Rychle
{12034}{12071}C-Co?
{12178}{12217}Našla jsem tì!
{12217}{12276}Je to super koèièí charakter!
{12369}{12402}Našla jsem tì!
{12402}{12451}Stop, nya! Nech mì jít!
{12451}{12513}Um, Ami, cos chtìla?
{12513}{12554}Oh, ano!
{12557}{12630}Amu-chan, ty jsi pozvala kluka k nám domu?
{12630}{12665}O èem to mluvíš?!
{12877}{12932}Amu-chan, máš hosta!
{12950}{12971}Tadase-kun…
{12971}{12993}Ahoj.
{13009}{13055}Je to host, vidíš?
{13055}{13093}Take jsi ho pozvala!
{13093}{13170}N-Ne! To nedovolím!
{13170}{13232}Tatínku, Amu-chan u je v tom vìku.
{13232}{13281}V jakém vìku?!
{13281}{13326}Já to nedovolím! Je to moc brzy!
{13337}{13412}Radši umøu ne bych mu øekla o Ikutovi!
{13443}{13478}Proè jsi pøišel tak najednou?
{13478}{13528}Uhm…
{13547}{13662}No, proè si nejdete povídat k Amu do pokoje nad šálkem dobrého èaje?
{13682}{13710}Co tím chceš øíct, miláèku?!
{13728}{13775}Jsem na obtí, e?
{13775}{13893}Huh? Ne, ani v nejmenším!
{13893}{13917}Ale...
{13954}{13973}Kam jdeš!
{13973}{14008}Uklidit si pokoj!
{14224}{14250}Co to dìláš?
{14259}{14289}Nekoukej!
{14474}{14545}P-Prosím, pojï dál, Tadase-kun. Omlouvám se za ten nepoøádek.
{14705}{14792}Tvùj pokoj je roztomilı.
{14792}{14829}M-Myslíš?
{14831}{14870}Ano, je opravdu skvìlı.
{14870}{14916}Zajímalo by mì, proè pøišel.
{14916}{14976}Mohlo by to koneènì bıt…
{14981}{15041}Myslíš, vzrušující vıvoj?
{15041}{15098}Co je tak vzrušující? O èem to mluvíte?
{15164}{15319}To nemùe bıt pravda! Mùj milovanı princ u mì v pokoji!
{15319}{15357}To je jako sen!
{15386}{15442}Ale! Nemùu si odpoèinout ani vychutnat si dokonce ani chvilku…
{15956}{15987}Co je tátovi?
{15987}{16071}Nemùe nic dìlat, tak aspoò bìhá kolem dokola.
{16071}{16162}Nemùu uvìøit, e je u Amu v pokoji kluk!
{16694}{16734}To byla koèka?
{16734}{16786}Uf, to jen vydávají zvuky zvíøat!
{16786}{16818}Ran, jsi dobrá!
{16873}{16893}Slabé, slabé!
{16985}{17027}Køièet budu pozdìji…
{17027}{17059}Stalo se nìco?
{17059}{17110}N-Ne, všechno je v poøádku!
{17110}{17175}Tak jako tak, proè jsi dnes pøišel, Tadase-kun?
{17186}{17207}Pravda.
{17303}{17317}Tady.
{17334}{17370}Pro mì?
{17370}{17389}Ano.
{17454}{17500}Dnes je 14.bøezna!
{17500}{17543}Je bílı den!
{17574}{17653}Ale…tehdy na Valentına…
{17675}{17744}No, vlastnì…udìlala jsem nìjaké èokolády…
{17757}{17816}A myslela jsem, e je dám tobì, Tadase-kun.
{17852}{17987}Ale kdy jsem chytala Yukina-chan, nìkde mi vypadly.
{17987}{18037}To je škoda.
{18064}{18125}Tìšil jsem se na èokoládu od tebe, Hinamori-san.
{18161}{18192}O-Opravdu?
{18192}{18208}Ano.
{18249}{18307}Tak dnes nemusíš…
{18337}{18412}Chtìl jsem jen ukázat uznání za plán podarovat mì.
{18530}{18561}D- Dìkuji.
{18661}{18774}Popravdì, ona opravdu chtìla, aby Tadase-kun mohl sníst tu èokoládu.
{18774}{18842}Dokonce jej ozdobila písmenem K jako pro krále.
{19088}{19148}Ale bílı den je jen vımluva.
{19203}{19309}Hinamori-san, vzpomínáš si na…
{19350}{19453}Jsou dvì vìci, o kterıch jsem s tebou chtìl mluvit po bitvì s Utau-chan.
{19453}{19544}První bylo o mì,Utau a Ikutovi. 
{19556}{19589}A to druhé…
{19632}{19671}Tehdy…
{19702}{19756}U je to docela dlouho, skoro jsem zapomnìla.
{19757}{19789}Nikdy jsem neøekl to, co jsem chtìl.
{19813}{19940}A pøesto, e mì Sanjou-kun pøedbìhl… 
{19940}{19975}Kairi?
{20000}{20136}Nikdy se mi nezdálo správné naèasování. Jak jsem se snail pøijít na to, kterı den by byl nejlepší…
{20153}{20205}se stávalo stále tìší a tìší nìco øíct.
{20521}{20620}Nevím, jestli zvládnu se správnì vyjádøit, ale byla bys ochotna vyslechnout mì?
{20620}{20652}Urèitì…
{20716}{20881}Jak jsem ti tehdy øekl, e jsem se zamiloval do Amuletu srdce, pamatuješ?
{20929}{20993}Náhle se pøede mnou objevila.
{21003}{21090}Oba jsme stráci, tak jsem si myslel, e se mılím.
{21105}{21155}Ale nemohu na ni zapomenout.
{21174}{21219}Mohlo by to bıt…
{21238}{21295}Chtìl jsem jen øíct, Hinamori-san.
{21295}{21330}A-Ano!
{21330}{21479}Bylo to poprvé, co jsem uvidìl tak jasnou, veselou a silnou dívku!
{21487}{21534}Dívka jako amulet srdce!
{21597}{21626}Co?
{21636}{21714}Ach ano,tak se to stalo, e?
{21720}{21896}Tehdy byl amulet srdce tak jasnı, a mì zaslepil.
{21896}{22014}Nemohl jsem vidìt spojení mezi ní, a Hinamori Amu.
{22063}{22154}I kdy je to jedna a ta samá dívka…
{22185}{22296}Nedokázal jsem si to uvìdomit, ale teï u je mi to jasné.
{22303}{22457}Ale, jak jsem s tebou trávil víc èasu, pochopil jsem.
{22491}{22588}Amulet srdce je ve skuteènosti souèástí tebe.
{22686}{22753}Kdy ses mi první den vyznala….
{22753}{22781}Miluji tì, mùj princi!
{22781}{22829}Odmítl jsem tì.
{22888}{22994}A poté se zamiloval to tvé souèásti.
{23011}{23071}Dvakrát jsem ti ublíil.
{23100}{23177}Take… omlouvám se.
{23177}{23278}O-Oh, ale to všechno je u dávno!
{23345}{23368}Na tom nezáleí!
{23368}{23401}Teï je vše jinak.
{23414}{23563}Bez ohledu na to, jak toho dosáhnu, chci se na tebe dívat stejnım zpùsobem.
{23687}{23785}Právì teï, nejsem silná osobnost, kdy jsem se zmìnil.
{23785}{23864}Ale to, co chci øíct… prosím, nepøerušuj mì!
{23994}{24031}Dokonce právì teï…
{24045}{24107}Necháš mì milovat tì?
{24471}{24527}Dobøe øeèeno, Tadase!
{24541}{24656}O-Omlouvám se! Vyhrkl jsem to…Byl jsem na obtí, e?
{24656}{24690}V-Vùbec ne!
{24731}{24789}Jen jsi mì trochu pøekvapil, to je vše. 
{24789}{24874}Je to tak… vdy jsem tì obdivovala.
{24905}{24935}I poté, co jsi mì odmítl.
{24947}{24997}Abych byla upøímná…
{25030}{25081}Jsem opravdu šastná.
{25090}{25116}Vánì?
{25147}{25183}Ano.
{25492}{25574}Pak jsem také šastnı.
{25618}{25638}Ano…
{25723}{25753}Já také.
{25827}{25901}Dìkuji ti za vyslechnutí.
{25937}{25965}Dìkuji.
{26092}{26140}Dobrou noc!
{26155}{26215}Je Amu v poøádku?
{26234}{26268}Jsem v poøádku.
{26296}{26359}Není divu, po tom, co se dnes stalo.
{26360}{26392}To je pravda.
{26392}{26470}Tak jako tak, proè spíš s námi, Yoru?
{26470}{26508}Proè ne, nya?
{26575}{26665}Tadase-kun mi øekl nìco krásného.
{26710}{26752}Dokonce právì teï…
{26789}{26843}Necháš mì milovat tì?
{26868}{26920}Poslouchal jsi?
{26929}{26963}Nemohl jsem si pomoct.
{26963}{27051}I tady se zasekl, kdy to vyhrkl.
{27051}{27116}V-Vyhrkl? Bylo to neformální!
{27116}{27173}Dobøe… Kdy myslíš.
{27190}{27265}Dobøe. Hej, proè jsi v mé posteli?!
{27265}{27294}Spíš na zemi!
{27294}{27335}Ale na zemi je zima.
{27335}{27384}To mì nezajímá! Na zem!
{27392}{27462}Kdy to øekneš takhle, já nechci.
{27563}{27588}Tak teplá…
{27588}{27643}Tvá tìlesná teplota je tak vysoká…
{27643}{27702}Jako láhev teplé vody…
{27759}{27797}Ven!
{27806}{27827}Ikuto!
{27829}{27857}Jsi v poøádku?
{27883}{27930}Dobrou noc! Ran, zhasni!
{27930}{27967}Dobøe.
{28291}{28386}Dnes se toho tolik stalo…motá se mi z toho hlava!
{28605}{28665}Nemáš spát na zemi?
{28665}{28725}Ale podlaha je tvrdá a studená.
{28725}{28768}Dej mi pokoj! Jdi pryè!
{28777}{28830}Jsem nemocnı….
{28889}{28921}Máš studené nohy!
{28921}{28973}Poèkej jen chvilku!
{29041}{29074}Nepoèkám!
{29181}{29289}Tvé housle jsou pro tebe dùleité, e?
{29289}{29330}Je to památka na rodièe.
{29330}{29426}Myslela jsem si, e pro tebe hodnì znamenají.
{29426}{29470}Ani si nepamatuju jejich tváøe.
{29486}{29581}Protoe je mùj nevlastní otec nepøíjemnı, je lepší, e není pøíbuznı.
{29606}{29712}Bıt spøíznìnı krví je jen na obtí, podle mì.
{29721}{29779}Dùvod proè jsem vdy pøipoután k Easter,
{29779}{29848}je kompenzovat jim, co mùj pravı otec provedl.
{29858}{29889}Tak je to?
{30085}{30155}Ikuto, tvùj otec je prostì…
{30221}{30281}Co klíè? Je Humtyho klíè také jen vzpomínka?
{30281}{30385}Páni, to je nuda. Kdo se o nìco takového stará?
{30444}{30526}Myslím, e jsi jen vzpurné dítì.
{30555}{30648}Ke mì ses vdy choval jako k dítìti, ale sám jsi dítìtem.
{30773}{30851}Tak, Tadase tì miluje?
{30853}{30905}Huh? Záleí na tom?
{30905}{30948}Taky nìkoho máš, ne?
{30948}{30995}Nìkoho, koho máš rád.
{31015}{31039}Mám rád...
{31058}{31078}Tebe.
{31206}{31248}Nesnáším lháøe.
{31253}{31325}Aww. To zní, jako bys mi to nevìøila.
{31336}{31413}Samozøejmì nevìøím! Vdy si ze mì dìláš jen legraci!
{31414}{31472}Asi jsem jen kluk, co je svùdník.
{31671}{31698}Hej, 
{31716}{31745}Co?
{31830}{31882}To nic. Zastavím to.
{31911}{31949}Rychle dospìj.
{31973}{32007}Co to má znamenat?
