{1}{1}23.976|www.titulky.com
{53}{100}Pøekládala z polskıch titulkù|Kozi (gg#1778554) Halka a Alena. 
{101}{150}Tento pøeklad je pouze amatérskou|interpretací anglickıch nápisù,
{151}{200} adresován skuteènım|filmovım maniakùm.
{203}{353}Korekce, komentáø a konstruktivní|kritika jsou vítané.
{1285}{1413}13 kvìtna, roku 1630
{1413}{1459}Rozptylové podmínky : dobré.
{1461}{1556}Horko narùstá z hodiny na hodinu.
{1572}{1665}Hodina 10:00. Dìdic Bennosuke
{1679}{1778}pøichází k pozemku Lorda Doi,
{1785}{1880}z dùvodu ukázky zdaøilého úlovku.
{1982}{2077}ádnı incident hodnı pozornosti.
{2077}{2113}Avšak 
{2116}{2176}kolem poledne
{2186}{2332}bıvalı voják, kdysi|slouící Lordu Geishu,
{2333}{2416}se zastavil pod naší bránou.
{2821}{2988}HARAKIRI (SEPPUKU)
{5741}{5793}Oficiální rezidence Lorda Iyi
{6009}{6122}Slouil jsi u Lorda Geishu?
{6125}{6166}Ano.
{6167}{6278}Jmenuji se Hanshiro Tsugmo.
{6279}{6367}Tsu jako Ohtsu,
{6370}{6459}a Gumo jako mrak na obloze.
{6462}{6545}S èím pøicházíš.
{6546}{6665}Mùj pán byl poraen|kolem roku 1619.
{6666}{6744}Od té doby bydlím v Edo,
{6746}{6871}vedu spíše skromnı ivot
{6874}{7004}a hledám zamìstnání|u nového mistra.
{7026}{7123}Ale všechno snaení|marné, nebo máme mír.
{7126}{7206}Ztratil jsem veškerou nadìji.
{7207}{7338}Roky utekly a stále ádné vyhlídky.
{7339}{7468}ivot na pokraji nouze|se stal utrpením.
{7470}{7587}Místo toho vést dál|takovı ivot, v hanbì,
{7588}{7686}radìji by zemøel èestnì|a spáchal harakiri.
{7688}{7819}ádá, aby mohl provést|tento rituál zde.
{7820}{7884}Taková je jeho ádost.
{7931}{8014}Ještì jeden?
{8015}{8092}Copak to nikdy neskonèí?
{8112}{8178}Jaké je v tomto pøípadì|tvé pøání, pane?
{8256}{8319}Pøiveï mi ho.
{9770}{9939}Jsem bıvalı sluha Lorda Geishu.
{9941}{10029}Mé jméno je Hanshiro Tsugumo.
{10031}{10122}Poníenì ádám|o malou laskavost.
{10124}{10225}Jsem Kageyu Saito, èlen|rady starších v domì Iyi.
{10227}{10335}Jsem ti nesmírnì vdìèen za pøijetí.
{10339}{10374}Mım dùvodem...
{10376}{10462}Byl jsem o všem informován.
{10464}{10540}Místo abych il na pokraji nouze,
{10542}{10647}radìji èestnì zemøeš
{10648}{10705}a spácháš harakiri.
{10707}{10767}Souhlasí?
{10769}{10823}Ano.
{10825}{10942}Uvaování hodno úcty.
{10944}{11051}Mám ten dojem.
{11052}{11187}Zmínil jsi se, e jsi|slouil u Lorda Geishu?
{11188}{11292}Moná jsi znal Motome Chijiiwu?
{11294}{11362}Chijiiwa?
{11364}{11437}Nepamatuješ…?
{11493}{11556}On také slouil u Lorda Geishu.
{11558}{11674}V dobì své slávy mìl klan|Geishu kolem 12.000 èlenù.
{11676}{11765}Nerad to øíkám….
{11767}{11960}Opravdu? Stejnì to|nemá ádnı vıznam.
{11972}{12142}Poèátkem roku…|snad koncem ledna…
{12145}{12254}bıvalı voják… Motome|Chijiiwa… pøišel k nám,
{12256}{12342}a stejnì jako ty,
{12344}{12473}ádal o dovolení spáchat harakiri
{12656}{12786}Chceš vìdìt jak skonèil?
{12814}{12862}Poslouchám…
{12868}{12997}Slouil jsi u Lorda Geishu?
{12998}{13124}To souhlasí! Jsem|bıvalım èlenem klanu.
{13126}{13210}Známı jako Motome Chijiiwa.
{13212}{13296}Proè k nám pøicházíš.
{13298}{13461}Úpadek našeho klanu mnì pøinutil|hledat si skromné pøístøeší v Edo.
{13462}{13534}Tam jsem il nìjakou dobu v bídì,
{13535}{13659}hledajíce nového mistra.
{13662}{13846}Ale v dobì míru|to bylo beznadìjné.
{14093}{14178}Èekal jsem to.
{14238}{14275}A co udìláš?
{14278}{14342}Pouvaujme…
{14374}{14450}Opravdu, smutná situace….
{14453}{14518}Klan Sengoku se spletl…
{14519}{14566}Vymysleli si ten preceneds…
{14567}{14634}S tím nesouhlasím.
{14635}{14673}Proè?
{14683}{14810}Bıvalı voják, kterı pøišel do rezidence|Sengoku nepùsobil falešnì.
{14811}{14911}Doopravdy chtìl zemøít,
{14914}{14971}a klan, dojatı jeho upøímností,
{14974}{15038}ho tajnì k sobì pøijal.
{15039}{15206}Udìlali dobøe.
{15222}{15370}Teprve jiní ho následovali,|ti kteøí na nás vrhli hanbu.
{15372}{15443}Místo smrti, hledají prostì peníze.
{15446}{15578}To jsou obyèejní vydìraèi.
{15579}{15626}Jestli chce èestnì zemøít,
{15627}{15710}pøed našimi dveømi,
{15711}{15864}dej mu pár drobnıch, jak to dìlají|jiné klany a a jde svou cestou.
{15882}{15978}Ne ! To nikdy neskonèí !
{16019}{16079}Dáš nìjaké peníze jednomu,
{16080}{16152}a hned tu máš davy takovıch.
{16154}{16334}Slítnou se jak vèely na med.
{16338}{16478}Od té doby, kdy skonèila obèanská válka,|je tu po èertech bıvalıch vojákù,
{16479}{16611}ebrajících o jídlo jako zvíøata !
{16626}{16732}Dùm Iyi pøíliš spoléhá|na svùj rozum.
{16775}{16826}Vaše reputace je v troskách.
{16827}{16972}Døív jste si dreli bıvalé|vojáky dál od tìla,
{17026}{17092}ale teï…?
{17094}{17304}Znalost umìní války|je dnes pøeitkem…
{17333}{17422}všechno po dobu míru.
{17424}{17495}Takovéto øeèi koluji mezi lidmi.
{17496}{17547}Šíøení takovıch øeèí
{17549}{17663}v dobì , kdy není|pøítomen náš lord…
{17665}{17735}A se to ji neopakuje!
{17736}{17822}Myšlenka na jeho svrení|mnì ani nenapadla!
{17824}{17943}Bez nejmenší chuti k umírání…
{17944}{18082}pøinejmenším pøedstírá…..
{18083}{18140}Boe Saito!
{18208}{18262}Dovol na chvilku…
{18943}{18993}Promiò…
{19207}{19311}Jsem Umenosuke Kawabe.|Èlen doprovodu lorda.
{19313}{19409}Motome Chijjiwa…|bıvalı voják Geishu.
{19411}{19479}Vstaò a pojï za mnou, 
{19521}{19588}do koupelny, samozøejmì. 
{19683}{19763}Jeliko jeho lordstvo|není pøítomno,
{19765}{19922}Saito popsal tvou situaci|dìdicovi Bennosuke.
{19924}{20076}Náš mladı pán je velmi dojat|a chce s tebou promluvit.
{20111}{20230}Mám… dovolení promluvit|s dìdicem Bennosuke?
{20230}{20270}Ano máš.
{20297}{20445}Ale… ne v tìch hadrech.
{20446}{20517}Nejdøív se musíš vykoupat.
{20518}{20633}Naší lidé zrovna pro tebe|pøipravují vhodné obleèení.
{20634}{20720}Jsem ti k dispozici.
{20722}{20776}Stydím se.
{21102}{21242}To není moné! To se mi jen zdá.
{21248}{21353}Neskuteèné… opravdu…
{21357}{21410}Dobrı den!
{21697}{21770}Promiòte mi to malé zpodìní.
{21810}{21894}Musíš se pøevlíknout.
{21901}{21957}Do tvého posledního odìvu…
{22661}{22707}Divíš se ?
{22710}{22803}Nemìl jsem se setkat s dìdicem?
{22858}{22935}Tak to bylo dohodnuto.
{22938}{23022}To je divné! Zøejmì|nìjaké nedorozumìní.
{23025}{23082}Ne!
{23085}{23178}Takhle mi to øekl|pan Umenosuke…
{23181}{23274}Kawabe?
{23282}{23454}Zaèínám chápat…|jooo… to je moné
{23470}{23566}Take… víš o co jde?
{23569}{23630}Ano. Je to celkem jasné.
{23686}{23868}Saito popsal tvou situaci dìdicovi,
{23870}{23950}kterého dojala tvoje|odvaha tak dalece,
{23951}{24083}e z tebe chtìl udìlat|jednoho z nás.
{24099}{24234}"""Ale samuraj, kterı|chce spáchat harakiri"
{24236}{24363}má urèitì pevnou vùli.
{24366}{24450}Jeliko nic nezmìní jeho názor
{24452}{24678}dovolíme mu splnit|jeho poslední pøání.
{24679}{24700}Rád bych s nim promluvil,
{24702}{24818}ale Lord Doi mnì oèekává.
{24818}{24910}A pozná mou pohostinnost.
{24912}{25035}Mí lidé budou svìdky rituálu.
{25038}{25107}"A je z toho ukázkovı pøíklad."""
{25110}{25234}Pøesnì takhle to øekl.
{25602}{25689}Tak co? Líbilo se ti to?
{25690}{25759}Velmi zajímavı pøíbìh.
{25761}{25945}Pøíbìh o velkolepıch|tradicích Domu Iyi.
{25954}{26054}Jaké máš tedy plány?
{26056}{26200}Aa…o to ti jde?
{26202}{26257}Pøesnì!
{26342}{26405}Nemusíš se bát…
{26407}{26530}To bych sem nepøišel.
{26532}{26591}Vıborná øeè!
{26593}{26705}Take tvoje rozhodnutí|je nezvratné
{26746}{26813}…pane Tsugumo.
{26815}{26971}Moná bych mìl dokonèit svùj|pøíbìh o Motome Chijiiwovi.
{26988}{27017}Povídej…
{27042}{27090}Pojï, èasu ubıvá!
{27092}{27199}Musíš se pøevlíknout.
{27201}{27342}Vše je pøipraveno pro rituál.
{27464}{27520}Mám prosbu!
{27556}{27613}Dejte mi ještì trochu èasu.
{27678}{27731}Neuteèu!
{27733}{27780}Slibuji, e se sem vrátím.
{27782}{27864}Jenom na nìkolik dní!
{27882}{27951}Na to je ji pøíliš pozdì.
{27959}{27997}To není spravedlivé!
{28001}{28123}A na  èí ádost.
{28125}{28179}jsme vše pøipravili?
{28181}{28283}Odvolávám se na vaší laskavost!|Jenom den, snad dva…
{28285}{28337}a vrátím se!
{28343}{28470}Slovo samuraje je svaté.|Nemohu to dovolit!
{29478}{29578}Náš mistr, Hayato Yazaki,|mladı a chtivı boje!
{29581}{29746}Jeden pohyb... a jsi mrtev.
{30009}{30050}Jsou ještì jiní…
{30052}{30125}Radím ti, abys místo|rozsekanej jako pes,
{30126}{30216}zemøel se ctí…
{30218}{30257}Pojï, pøevlíkni se.
{30993}{31089}Pozor, ctihodní pøedkové!
{31090}{31201}Promiòte nehodnému ex-vojákovi,
{31202}{31274}kterı kráèí naší svatou zahradou.
{31597}{31771}Rodinná èest je ohroená,|podobnì jako 
{31774}{31929}budoucnost Klanu Tokugawa a|také náš svatı kodex samurajù.
{31930}{32024}Vyzıvám vás za svìdky,|bìhem tohoto rituálu!
{33112}{33171}Obì ostøí ?
{33178}{33214}To nemá smysl!
{33227}{33331}Tím nerozøízneš ani øedkvièku!
{33354}{33411}Meè samuraje je jeho duší!
{33414}{33471}Bambusové ostøí…
{33474}{33532}a on chce ještì spáchat harakiri?
{33540}{33602}Nestyda!
{33673}{33746}Vše hotovo…
{34137}{34201}Motome Chijjiwa… 
{34244}{34329}Ne vést nuznı ivot,
{34331}{34420}vybral jsis smrt harakiri.
{34422}{34491}Skutek hodnı chvály.
{34493}{34622}Jak se sluší na|opravdového vojáka.
{34624}{34749} S hanbou musím uznat, e ani tento|Dùm, se všemi dlouhımi tradicemi,
{34751}{34929}se mue pochlubit jen|pár tak èestnımi lidmi.
{34961}{35059}Všichni èlenové Domu byli pozváni,
{35061}{35225}aby byli svìdky té|neopakovatelné ceremonie.
{35265}{35391}Bì v míru.
{35433}{35477}Mám ádost pane!
{35493}{35534}Copak?
{35536}{35656}Den nebo dva.. prosím!
{35667}{35750}Nechci utéct! Vrátím se.
{35752}{35823}Proboha... prosím!
{35853}{35925}Opravdu, podivná ádost.
{35927}{36017}Jsem informován, e v Edo je plno|takovıch bıvalıch vojákù, kteøí,
{36019}{36113}vrhají hanbu na samuraje, vyhrùkami,|e spáchají harakiri na nìèím panství,
{36114}{36246}pokud nedostanou pár drobnıch.
{36248}{36411}Neøíkej…. e ty…
{36435}{36509}Ja nikdy…
{36511}{36615}Vìøím, e ne…
{36617}{36678}Èlovìk s tvım chatakterem
{36680}{36845}by nebyl schopen takového konání.
{36854}{36947}Take… pokraèuj!
{37332}{37436}Je to pro mne èest,|bıt tvım sekundantem.
{37448}{37548}Jsem zástupcem školy|Shindo-Munen.
{37638}{37757}Jakkoliv to není nezbytné,|zopakuji, e
{37758}{37876}se bìhem let zmìnilo|provedení harakiri.
{37877}{37962}Od nedávná se tento svatı rituál
{37964}{38045}stal pouhou formalitou.
{38046}{38154}Málokdo sáhne po meèi,
{38157}{38234}pøed utìtím hlavy.
{38237}{38276}Nejsou u vyhøezlé vnitønosti,
{38277}{38352}v nìkterıch pøípadech|se na tácy, místo meèe,
{38354}{38426}pokládá vìjíø.
{38436}{38549}Avšak dnes nebudeme tolerovat
{38550}{38626}takovou ubohou formu.
{38629}{38726}Vše provedeme podle tradice.
{38767}{38821}Rozumìls?
{38838}{38974}Jistì… do køíe…|otevøeš své vnitønosti!
{38987}{39118}Jedinì tehdy splním svùj závazek.
{39181}{39313}Zareaguji teprve tehdy,|a uznám, e to staèí.
{39314}{39369}Je ti to jasné?
{39370}{39414}Zaèni!
{40274}{40382}Toto je tvùj meè….jim zemøeš.
{40442}{40542}Meè samuraje je jeho duší!
{40547}{40655}Nakonec, jaké ostøí|by bylo vhodnìjší?
{41380}{41466}No… co tì zdruje?
{41499}{41554}Zaèni!
{43400}{43433}Skonèi!
{43685}{43784}Sekni!
{43790}{43899}Ještì ne! Rozsekni do konce.
{44433}{44511}Táhni meèem!
{44512}{44563}Vpravo!
{45690}{45776}Ano… ukousnout si jazyk…
{45778}{45833}z bolesti, z posledních sil…
{45834}{45897}Jakı to hanebnı skutek!
{45942}{46126}A nakonec… dokázal spáchat harakiri|za pouití bambusovıch meèù.
{46176}{46317}A pøi té pøíleitosti…|jaké máš plány?
{46377}{46506}Je to pro tebe dùleité?
{46566}{46770}Vyloil jsem ti osud toho mládence|pøesnì tak, jak se to stalo.
{46789}{46954}Pane Tsugumo…radím ti dobøe,|rozmysli si znova svùj úmysl.
{46957}{47062}Ne! Nepøesvìdèuj mnì.
{47088}{47183}Na rozdíl od toho Chijjiwy,
{47223}{47319}já nemám bambusové meèe.
{47322}{47377}Spáchám harakiri 
{47378}{47530}a mùj jazyk zùstane v celku.
{47577}{47623}Tak dobøe!
{47627}{47730}Pane Tsugumo… postarám se o to,
{47731}{47782}abych ti umonil splnit tvé pøání.
{47783}{47821}Sluho!
{47955}{48045}Hanshiro Tsugumo,|bıvalı voják Geishu,
{48046}{48150}hledá smrt zpùsobem harakiri.
{48183}{48314}Jeho obleèení je nevhodné a|proto mu pøines rituální šat…
{48315}{48350}Co to?
{48351}{48418}Nepotøebuji takové ohledy.
{48419}{48621}Moje obleèení víc odpovídá|zahanbenému vojákovi,
{48622}{48733}odcházejícímu na onen svìt.
{49143}{49290}Jsem vám vdìèen za vaší|nesmírnou laskavost,
{49292}{49364}jaké se mi dnes dostalo.
{49366}{49478}Hanshiro Tsugumo nenalézá slov,|které by popsaly jeho vdìènost.
{49480}{49558}Zaèínám…
{49650}{49806}A propos, pane Saito…|kdo bude mım asistentem?
{49840}{49942}Ichiro Shinmen byl vybrán.
{50142}{50196}Máš nìjaké poadavky?
{50198}{50350}Ano… Chtìl bych aby mi poskytl|své sluby Hikokuro Omodake.
{50351}{50402}Hikokuro Omodake…
{50404}{50575}Ten šermíø ze školy Shindo-Munen|je v okolí dobøe známı.
{50577}{50707}Pravda! Hikokuro získal vìhlas.
{50708}{50755}Hikokuro…
{50815}{50918}Omodaka je propuštìn.
{50920}{51036}Poslal oficiální dopis se ádostí|o 4-5 dnù volna na odpoèinek.
{51038}{51136}V tomto pøípadì se nedá nic dìlat.
{51138}{51246}Pane Tsugumo… jak jsi|pøed chvíli slyšel,
{51248}{51314}Omodaka není pøítomen.
{51327}{51382}Snad nìkdo jinı…?
{51384}{51485}Ty mnì pøekvapuješ!
{51519}{51618}Doufal jsem, e pan Omodaka|bude mım sekundantem.
{51620}{51729}Mùu ho poádat o to, aby|se mimoøádnì dostavil?
{51755}{51902}Snad ano. Nevypadal vèera|nìjak mimoøádnì unaven.
{51903}{51978}Take to nebude nic váného.
{52010}{52050}Sluha!
{52275}{52327}Bì k Omodakovi a øekni mu,
{52329}{52448}e ho ádám, aby se dostavil.
{52450}{52496}Pospìš si!
{52666}{52766}Jsem ti vdìèen za tvé sluby.
{52805}{52915}Poèkáš na Omodaku zde,
{52927}{52978}nebo radìji pùjdeš dovnitø?
{52980}{53070}Jestli vstoupím,
{53071}{53143}moje rozhodnutí by mohlo polevit.
{53145}{53311}To nebyl cíl mé cesty.
{53319}{53390}Poèkám tady.
{53402}{53501}Samozøejmì, tvoje|urputnost je imponující.
{53515}{53567}Pane Saito,
{53587}{53698}to nudné èekání je k nièemu.
{53745}{53877}Dovol mi, abych ti povìdìl moji ivotní|historii, a si zkrátíme èas èekání.
{53888}{54018}Historii tvého ivota?
{54026}{54186}Ano. Pøíbìh ubohého, bıvalého|vojáka mùe se zdát nudná,
{54189}{54260}ale za nedlouho
{54262}{54354}jiní mohou sdílet mùj osud.
{54378}{54489}Pozorní posluchaèi
{54490}{54530}snad v tom najdou
{54532}{54628}ukryté poselství.
{54636}{54752}Tvùj osud … osudem druhıch?
{54866}{54946}Zní to zajímavì!
{55044}{55118}Pozornì naslouchejte|mému vyprávìní,
{55120}{55229}nebo je to pøíbìh èlovìka|ubírajícího se na vìènost.
{55238}{55330}To je nìco víc,|ne obyèejná poslední vùle.
{55349}{55442}Myslím, e se z nìho|mùeme trochu pouèit.
{55481}{55540}Pane Saito…
{55654}{55858}Pøíbìh, kterı si mi pøedtím|vyprávìl je celı pravdivı?
{55970}{56009}Ano.
{56042}{56146}Bıvalı voják Geishu,|Motome Chijiiwa,
{56147}{56243}byl trochu roztritım klukem.
{56694}{56782}Motome Chijiiwa…
{56803}{56933}Ano… roztritı mládenec…
{57818}{57924}Motome byl hezkı 15-letı chlapec.
{57926}{58050}Moje dcerka, Miho|tehdy mìla 11 rokù.
{58051}{58126}Pøed jedenácti léty…
{58148}{58223}Ještì teï, kdy zavøu oèi,
{58226}{58386}všechno se to vrací, jakoby|se to stalo teprve vèera.
{58826}{58859}Ještì jednu rundu?
{58862}{58914}Není tøeba…
{58914}{58989}Našim cílem je pøestavba.
{58991}{59052}Luèišnictvo nám|tady moc nepomùe.
{59054}{59181}Mír, ach, skvìlı mír!
{59201}{59344}A propos, 22-ého bude sedmé|vıroèí úmrtí mé eny.
{59346}{59429}Vím pamatuji kdy…
{59431}{59470}ale u sedmé?
{59472}{59585}Ano…plánují pøi té pøíleitosti|malou oslavu v mém domì.
{59587}{59635}Ale nechci se vnucovat…
{59637}{59676}Rozumím.
{59678}{59800}Ale nemohu tomu uvìøit!|To u je sedm let?
{59834}{59920}Co víc,
{59922}{60015}takovı veterán jako ty,
{60017}{60076}sám vychovává tu|krásnou drobotinu?
{60078}{60182}Ty také…koukni se na sebe!
{60184}{60298}Kdy Yuki zemøela,
{60300}{60405}uvauji o tom jak si s tím radíš.
{60407}{60481}A dnes…
{60483}{60540}Hospodyòka ve lví kùi!
{60542}{60645}Ovdovìlı staøec vyhovující|svého jedináèka,
{60647}{60689}A syn zanedlouho
{60690}{60763}pøedèí otce.
{60765}{60808}Statnı mládenec!
{60810}{60853}Hloupost!
{60865}{60949}On roste pouze zevnitø.
{60951}{61065}Ještì má daleko|do skvìlıch vojákù.
{61094}{61169}Víš co? Vdycky jsem si myslel, e
{61171}{61229}mimo bitevní pole budu k nièemu,
{61234}{61302}ale nìjak se mi povedlo.
{61478}{61543}A kdyby se mi ivot toèil tak dál,
{61545}{61613}Všechno by bylo dobré.
{61646}{61745}Bohuel!
{61766}{61812}Náš ivot lze srovnat s domem,
{61850}{61948}kterı je postaven na písku,
{61950}{62032}nejmenší vánek pøinese katastrofu.
{62081}{62241}Co pøispìlo k úpadku tak|velkého klanu jako klan Geishu?
{62275}{62320}Mám se zabıvat detaily?
{62322}{62384}Všichni to musíte vìdìt.
{62445}{62521}Oprava zámku Hiroshimy|byla zrušena
{62522}{62622}jako vıstraha pro|šogunat Tokugavy.
{62654}{62717}V èervnu 1619…
{62724}{62820}bylo svreno sídlo našeho klanu.
{62822}{62949}12000 jeho èlenu,
{62950}{63026}pøišlo o práci a prostøedky|na ivobytí.
{63784}{63834}Jinnai!
{64105}{64158}K Hanshiro Tsugumo.
{64159}{64246}Poslední ádost od|dlouholetého pøítele:
{64254}{64371}Smrt stavebního Komisaøe.
{64374}{64478}Zanedlouho nastoupí.
{64479}{64591}A moje smrt,
{64594}{64687}mu pøipraví cestu na onen svìt.
{64690}{64799}Prosím tì zachovej klid.
{64802}{64882}Mùj syn,
{64885}{64999}Motome, je sotva|15-ti letım dítìtem.
{65003}{65081}Prosím tì abys ho vzal|pod svoji ochranu.
{65398}{65527}Ó nedoèkavı! Mohl alespoò|poèkat na mnì!
{65530}{65619}Hanshiro.. Zakazuji ti!
{65622}{65712}Nemùeš jít za mnou.
{65714}{65788}To všechno u nemá cenu!
{65830}{65882}Smrt Jinnai staèí!
{65884}{65955}Nebuï nerozvánı!
{65958}{66070}Jinnai se obìtoval jako první,|jen proto abys nepokoušel.
{66090}{66178}Bude mnì doprovázet|tvım jménem.
{66179}{66306}Od teï Hanshiro,
{66308}{66343}máš povinnost jít dál ivotem…
{66346}{66383}Vzít na sebe jeho závazky…
{66474}{66588}Kdo jinı se postará|o jeho syna - Motome?
{66718}{66840}Jdu… pøidat se k Jinnai.
{66842}{66978}Nemáš nic co bys|mu chtìl vzkázat?
{67038}{67114}Vùbec nic?
{67116}{67226}Øekni… øekni Jinnai… e…
{67308}{67462}Hanshiro se postará o vıchovu|jeho syna a bude ho chránit,
{67464}{67607}tak jako by to byl syn Hanshira!
{67634}{67732}Pane Tsugumo.
{67839}{67862}Poslouchám?
{68038}{68072}Tak jak?
{68094}{68176}Pane … je to tak váné,|e se nemohl dostavit.
{68177}{68232}A co mu chybí?
{68233}{68399}Jeho rodina tvrdí, e má vysokou|horeèku a hroznì trpí.
{68401}{68511}Chtìl jsem pøistoupit k jeho loi,
{68513}{68587}ale z dùvodu pøíšernıch|bolestí, které ho trápí,
{68589}{68676}mi to nedovolili.
{68678}{68768}Kdy jsem odjídìl, pøedal|jsem jim tvùj vzkaz.
{68769}{68842}V tom pøípadì nemáme na vıbìr.
{68844}{68900}To horko…
{68902}{68976}musel se kvùli tomu nìèím nakazit.
{69044}{69107}Pane Tsugumo…
{69109}{69162}slyšel jsi jeho hlášení.
{69164}{69272}Musím tì poádat aby sis|vybral jiného asistenta.
{69281}{69470}Ach… to je smùla!|Take je indisponován…
{69479}{69681}V tom pøípadì ádám aby byl|mım sekundantem Hayato Yazaki.
{69713}{69751}Hayato? Ten Hayato?
{69852}{69944}Inabo…neomlouval se|poslednì také Yazaki?
{69945}{70099}Ano pane, ádal o volno, jeliko|v poslední dobì tìce pracoval.
{70117}{70216}Pane Tsugumo…je mi to líto,
{70218}{70297}ale Yazaki se také|nemùe dostavit.
{70299}{70428}Pan Yazaki je rovnì|indisponován?
{70429}{70496}To je ale zvláštní shoda náhod!
{70584}{70657}Pøesnì tak se vìci mají,
{70659}{70766}poprosím Umenosuke|Kawabe o tu laskavost.
{70865}{71026}Pane Saito…mùu poádat aby|mım asistentem byl Kawabe?
{71029}{71093}On snad také…?
{71430}{71585}Ach… take on také nemùe pøijít.
{71598}{71768}Zajímavé, e všichni tøi|jsou dnes indisponovaní…
{71773}{71858}To je zvláštní náhoda.
{71905}{71950}Hodnì zvláštní!
{72148}{72217}To není v poøádku…
{72232}{72302}Hikokuro vyvíjel nejvìtší nátlak
{72305}{72419}a donutil Motome Chijiiwu|ke spáchaní sebevrady.
{72433}{72603}Hayato Yazaki zjistil, e ostøí|bylo vyrobeno z bambusu…
{72606}{72663}Ne…toho si všiml Umenosuke.
{72665}{72741}Bylo, nebylo, varoval jsem je!
{72742}{72787}Teï u to nemá vıznam!
{72790}{72837}Pravda.
{72889}{72951}Co sním udìláš?
{72954}{73034}Hm, on sem nepøišel|obyèejnì umøít.
{73037}{73155}Urèitì nìco chystá…
{73174}{73302}A jsou jeho úmysly jakékoliv,
{73335}{73427}donutím ho aby dokonèil rituál.
{73450}{73518}Jestli ustoupí, mí lidé
{73526}{73618}ho rozsekají na kusy.
{73735}{73847}Cokoli se tu semele,
{73857}{73955}tady zùstane.
{74035}{74154}A jsou pøipravení na mùj pokyn.
{74190}{74304}Napadá mnì, co se dìje|s Hikuro a ostatními.
{74340}{74468}Mìl bych k ním nìkoho poslat,|ale vzhledem k okolnostem,
{74470}{74554}chci abys k ním zajel osobnì.
{74878}{74966}Pane Tsugumo.
{75019}{75182}"""Èas jsou peníze"" take|i kdy jsou dny dlouhé,"
{75235}{75335}ádám abys nakonec udìlal|to pro co jsi pøišel.
{75356}{75426}Pane Saito! Rituál nemùeme|provést bez asistenta.
{75428}{75564}Vím, prodiskutoval jsem|to s ostatními èleny rady.
{75566}{75678}Protoe lidé, o které jsi|ádal jsou nedostupní,
{75680}{75765}vyberu za tebe.
{75771}{75827}Ichiro Shinmen!
{75838}{75951}Budeš sekundantem tohoto bıvalého|vojáka Geishu - pana Tsugumo.
{75952}{76011}Splò pøíkladnì své závazky.
{76123}{76188}S prominutím,
{76190}{76278}vyjmenoval jsem tøi|osoby a chtìl bych,
{76280}{76383}aby se mohla dostavit|alespoò jedna z nich.
{76408}{76474}Neslyšel jsi?
{76560}{76670}Všichni tøi jsou|dnes indisponování!
{76677}{76802}Nemluvím snad jasnì?|Anebo jsi snad hluchı?
{76821}{76898}V tom pøípadì,
{76900}{76972}nemohu nic dìlat.
{76974}{77064}Obavám se e rituál|budeme muset odloit.
{77077}{77123}Zmlkni!
{77161}{77253}Zacházíš moc daleko!
{77260}{77378}Nejprve ádáš o pøípravu obøadu.
{77380}{77459}Teï se ti nelíbí vıbìr asistenta.
{77466}{77542}Nikdy si nechtìl spáchat harakiri!
{77544}{77591}Pøišel jsi pro peníze!
{77592}{77715}Kdybych byl obyèejnı vydìraè,
{77717}{77825}copak bych tu sedìl tak klidnì?
{77827}{77907}Pøišel jsem pøipraven na smrt.
{77912}{77979}Ale harakiri osamotì
{77980}{78057}nezajistí lehkı odchod|na onen svìt.
{78059}{78149}Asistenta potøebuješ|k useknutí… toho,
{78151}{78246}Má to bıt kvalifikovanı šermíø.
{78254}{78350}A navíc nejsem zloèinec,
{78352}{78435}take mám právo vybrat si|sekundanta podle svého mínìní.
{79003}{79186}Buï proklet, podvodníku.
{79658}{79750}Nepøišel jsi z dùvodu harakiri…
{79752}{79814}Drzı pse!
{80696}{80730}Poèkat!
{80749}{80796}Uklidnìte se!
{81478}{81570}ádám vás všechny…
{81571}{81606}aby jste se ovládli!
{81622}{81767}Co teï? U je pozdì na rozhovor.
{81770}{81818}Ne. Ještì ne!
{81819}{81882}Ještì jsem neskonèil…
{81883}{81950}vyprávìt svùj pøíbìh.
{81970}{82082}Nemám v úmyslu poslouchat|takové báchorky!
{82083}{82126}Saito.
{82174}{82238}Jestli jim dáš rozkaz aby zaútoèili,
{82241}{82334}budu se bránit ze všech sil.
{82375}{82498}Pravdìpodobnì bude zranìno|mnoho tvıch nevinnıch lidí.
{82502}{82575}A nìkteøí by mohli i zemøít!
{82610}{82698}Copak by nebylo pro všechny lepší,
{82698}{82758}kdybys vyslechl mùj|pøíbìh do konce?
{82808}{82918}A skonèím, rozøíznu si bøicho, jak|se sluší na opravdového samuraje.
{82926}{82991}Pokud budu zdrovat,
{82994}{83080}poštveš na mnì svoje lidi.
{83124}{83295}Ale teï… prosím vyslechnìte|mnì do konce.
{83490}{83610}Urèitì se zachováš|tak jak povídáš?
{83619}{83678}Pøísahám!
{83706}{83772}Na èest samuraje?
{84142}{84240}Dobøe ale neprotahuj to.
{84242}{84361}Nechci slyšet dlouhé|absurdní historie.
{84392}{84449}Ustupte!
{84834}{84897}Kde jsem to skonèil?
{85001}{85135}Jo, tak…sídlo našeho|mistra bylo svreno.
{85137}{85226}Jinnai Chijiiwa zemøel,
{85228}{85401}a já skonèil u toho jak mi|svìøil svého syna do mé péèe.
{85502}{85603}Po úpadku mého klanu
{85605}{85722}pøestìhoval jsem se do Edo.
{85727}{85881}Konec obèanské války zpùsobil|drastickı nárùst nezamìstnanosti.
{85883}{85998}Za lepších èasù, by nìjakı klan
{85999}{86085}rád pøijal takové lidi.
{86087}{86263}Ale v dobì míru, nebylo|takovıch lidi potøeba.
{86265}{86367}Bali urèení jen pro svùj osud.
{86369}{86483}S hanbou vám pøidávám pøíbìh
{86485}{86563}posledních 8-9 let mého ivota.
{86638}{86758}Avšak uprostøed té bídy,
{86760}{86865}dorùstala moje dcera, Miho.
{86867}{86949}Brzo mìla slavit své|sedmnácté narozeniny…
{87614}{87658}Otèe…
{87674}{87734}Pokud se nevrátím pøed polednem,
{87736}{87802}obìd máš pøipravenı.
{87804}{87938}Nejlepší pokrm tratí hu,|kdy ho èlovìk jí sám.
{87940}{87990}Poèkám…
{88009}{88128}V tom pøípadì, jak dostanu|vıplatu, koupím sušenou rybu.
{88170}{88214}Promiò.
{88248}{88316}Zaneprázdnìna? Nìkam jdeš?
{88318}{88378}Ano, do elezárny.
{88380}{88422}Do Mikawa´i?
{88422}{88458}Nashledanou.
{88653}{88782}Trénink dìlá mistra! U ti to jde.
{88786}{88838}Promiò mi…
{88838}{88894}e tì poøád ádám,
{88897}{88993}ale mùj vıdìlek je stále malı.
{88994}{89106}Tvoje upøímnost je|zkrátka odzbrojující.
{89108}{89198}Chtìl jsem to vzít na sebe,
{89201}{89314}Øíct pár slov… ale zavøel si mi ústa.
{89317}{89382}Klaním se.
{89393}{89535}A propos…pamatuješ na mùj návrh?|To, o èem jsem ti tehdy povídal…
{89629}{89723}Pøemıšlel jsi o tom?
{89787}{89834}Ano.
{89834}{89902}To je dobøe.
{89905}{89999}Ano…to mi spadl kámen ze srdce.
{90002}{90157}Ne. Tvùj návrh,|kterı se tıká Miho…
{90169}{90243}Musím odmítnout.
{90390}{90569}Obecnì, byla by to jen záminka.
{90570}{90701}Rodina Sakakibara by|z ní udìlala konkubínu.
{90753}{90870}Tsugumo…pøece to|je velmi silnı klan.
{90870}{90943}Kdybys tam poslal svoji dceru,
{90946}{91022}byl by jsi uznáván do konce ivota.
{91024}{91090}Ano, a právì toho se bojím.
{91094}{91212}Nemám v úmyslu obìtovat|ivot své dcery
{91214}{91292}abych si zajistil pohodlí.
{91294}{91402}Rozumím… pøemıšlí.
