{1}{1}29.970
{144}{322}/Toto je FANSUB od fanouškù pro fanoušky.|Ne na prodej nebo pronajímání./
{322}{556}TaSHee's Gang uvádí
{1205}{1227}Dobré ráno.
{1573}{1643}Dobøe lidi, teï je to na vás!
{1774}{1817}/Místnost Studentské Rady/
{2210}{2303}Bojuj dál!
{2992}{3071}Promiò mi, ale mohla bys mi hodit ten míè?
{3293}{3311}Hej!
{3311}{3337}Co se dìje?
{3337}{3391}To je starší studentka Sakasegawa!
{3392}{3508}Sakra! Je vdycky taková koèka!
{3531}{3595}Kdybych mìl pøítelkyni jako je ona...
{3595}{3731}Blbèe. Je v nejvyšší tøídì a mít |tak perfektní tìlo je umìní.
{3731}{3823}Jak by si mohla vyjít s nìkım jako jsi ty?
{3823}{3857}Co jsi to øekl?
{3886}{3908}Pozor!
{4692}{4767}Hej, omlouvám se! Jsi v poøádku?
{4784}{4811}Oh, wow!
{4953}{5003}Jsi v poøádku?
{5163}{5187}Tady máš!
{5261}{5330}Um... dìkuju.
{5351}{5439}Dobøe, e nejsi zranìná.
{5461}{5562}Musím ti to podat, Shizuko!|Vdycky všechno dìláš se zalíbením!
{5562}{5610}Promiòte, lidi!
{5663}{5701}Omlouvám se za to!
{5799}{5845}Jsi zachránce ivota, Shizuko!
{5876}{5900}Sakuro.
{6256}{6403}Tenhrát, jsme nic nevìdìli, nic jsme neøekli...
{6436}{6570}Všechno co jsme udìlali bylo to, e jsme se setkali |a rozdìlili se, setkali a rozdìlili se bez tolika myšlenek.
{8622}{8717}Nìkdy jsem unavenı na to, abych|automaticky nasadil na cizince laskavı vıraz.
{8717}{8760}Je to tam, kde tì to udeøilo?
{8803}{8849}J-Jo, pøiblinì.
{8849}{8889}Kde je Junpei?
{8889}{8939}Ve videopùjèovnì.
{8939}{8993}Je to video-cvok.
{9035}{9050}Tady!
{9487}{9529}Pouij to, abys to zchladil.
{9651}{9668}J-Jo.
{9995}{10050}S... Sakuro?
{10152}{10195}Uh, no...
{10242}{10267}...dìkuju.
{10948}{11105}Vìc, e èíslo jedna v mojí mysli|není škola nebo nadcházející zkoušky.
{11119}{11234}Abych byl upøímnı, zdá se, e já, Morifuji Shizuka...
{11234}{11368}...to chci dìlat se Sakurou Ichitarem.
{11417}{11553}LESSON XX
{11825}{11918}Hej, Shizuko... Nemìl bys to brát tak jednoduše?
{11952}{11993}To nic, opravdu.
{11993}{12088}Ale v domì jsi mìl velké bolesti...
{12170}{12255}Rád bych šel spát do svého pokoje, ale je moc teplı.
{12255}{12298}No, to je pravda.
{12768}{12787}Co je to?
{12822}{12895}Tohle! Bylo to taky minulı rok?
{12895}{13001}Oh, ohòostoje? Myslím, e mají kadı rok jeden.
{13055}{13142}Vdycky jsme se vrátili domù, kdy se konaly.
{13142}{13195}Oh, to by to mohlo vysvìtlovat.
{13228}{13275}Rád bych je jednou pro zmìnu vidìl.
{13335}{13367}Teï co?
{13387}{13414}Profesionální wrestling!
{13414}{13446}Profesionální wrestling...?
{13446}{13571}Zapomnìl jsem si nastavit video!|Promiò, musím rychle domù!
{13633}{13658}Promiò mì...
{13768}{13835}Myslela jsem si, e jsi to byl ty,|Morifuji-kun! To je úleva!
{13850}{13886}A, ty jsi...?
{13903}{14016}Sakesegawa Bisaki. Díky, e jsi za mì chytil ten úder.
{14016}{14071}Oh... To nic nebylo...
{14071}{14156}Jsi po škole pìknì známı.
{14156}{14226}Kdy máš reputaci nejelegantnìjšího|studenta ve škole...
{14226}{14338}...a øeditel studentské rady, to by mohl|bıt Morifuji Shizuka ze tøídy A.
{14357}{14472}Ne vùbec. Dnes, jsem bıvalı prezident|studentské rady.
{14472}{14562}Mimochodem, co tady dìláš v tuhle hodinu?
{14618}{14728}Chtìla jsem ti podìkovat... a dát ti tohle.
{14739}{14764}Ahoj!
{14764}{14828}Coe? H-Hej, ty!
{14865}{14910}Jméno je Sakasegawa!
{14910}{15004}Bylo by v poøádku, kdybych pøišla |obèas do tvého penzionu?
{15320}{15392}/Taška plná léèibıch krémù na modøiny/
{15961}{16052}Jestli chceš kouøit, mìl bys radši |na celou dobu otevøít okno.
{16117}{16158}Pach bude mít kam jít.
{16287}{16375}Vypadá to, e Sakura tu pro tebe ještì není.
{16419}{16498}C-Co tím myslíš, Masato?
{16566}{16641}Jsi do nìj zamilovanı, ne? Do Sakury Ichitara.
{16746}{16904}Uklidni se. Není to nic trapného.|Je to úplnì pøirozené.
{16904}{17043}Je to dost NEpøirozené!|Co s ním chci sakra dìlat?
{17112}{17198}Ohó... Jsi ten typ, kterı dostává pøímo k vìci.
{17227}{17265}Jo, jsem špatnı jako zúètování.
{17306}{17441}Nemùu ti nic skrıt. Ale, jsem úplnì zašpinìnı...
{17441}{17566}...myslet si, proè hernajs tohle cítím ke klukovi.
{17599}{17683}Moná se jen rvou ven tvoje emoce a tvùj smysl pro úsudek.
{17710}{17727}Jo.
{17773}{17895}Taky, vrcholem to všechno je, e nevím|jestli ho opravdu miluju nebo ne...
{17895}{18038}...protoe úplnì první vìc, o které|jsi pøemıšlel bylo dìlat to s ním, huh?
{18076}{18170}Jedna vìc... Kdo byla ta dívka, se kterou jsi døíve mluvil?
{18170}{18265}Oh, myslíš Sakasegawu ze tøídy C?
{18280}{18351}Ona je nic. Jen jsem do ní narazil, to je celé.
{18440}{18514}Moná to máš na obì strany.
{18820}{18877}Hej, lidi! Podívejte se na tohle!
{18877}{18919}Ne, vra to zpátky!
{18919}{19024}Podívejme, co je ve školním balíèku Maekawy!
{19024}{19084}Pøestaò s tím, Takahashi!
{19124}{19153}Vra to zpátky!
{19172}{19239}Jee! Jsi pìknì odváná!
{19239}{19275}Kdo je ten šastnı hoch?
{19275}{19317}Vra to zpátky...
{19346}{19410}...prosím, vra to zpátky!
{19464}{19506}Èekáme na tvou odpovìï!
{19506}{19553}Vra to zpátky...
{19580}{19653}Vysyp to. Je to nìkdo z naší tøídy?
{19692}{19758}Prosím! Vra to zpátky...!
{19758}{19825}Øekni nám, kdo to je!
{19911}{19997}Co to dìláte kluci? To patøí Maekawì, správnì?
{20054}{20103}Tady máš, Maekawo.
{20252}{20312}Maekawo...? Tady!
{20454}{20548}Idiote... Nenávidím vás všechny!
{20548}{20596}Co se dìje?
{20689}{20731}Podlézavec!
{20731}{20811}Má v hlavì jen kousek mozku?
{20860}{20930}Víš, co to je?
{21024}{21081}H-Hej... Není to...
{21101}{21179}K-Kondo...?
{21195}{21258}Jo! Je to Pan Kondo!
{21258}{21329}Co bys s tím rád dìlal?
{21367}{21478}Podle vırazu Maekawy si nemyslím, |e to od tebe bude chtít zpátky.
{21496}{21538}Vem si to.
{21538}{21617}C-Coe? A-Ale to je na...
{21639}{21684}Co tì tak vyvádí z míry?
{21684}{21782}Mohlo by to znamenat, e jsi úplnì nezkušenı?
{21806}{21856}BLBÈE! O èem to vaníte?
{21856}{21947}Víš, v dnešní dobì je bìnı smysl pouívání tohoto.
{21947}{22000}Je zdvoøilá vìc, to udìlat.
{22000}{22104}Jestli to nechceš pouít, vezmu si to z tvıch rukou!
{22141}{22169}Já...
{22189}{22282}...nikdy jsem nepøemıšlel o takovı vìcech.. vùbec!
{22374}{22424}Huh!? Mohlo by to bıt...?
{22449}{22513}...nikdy jsi nepøemıšlel o dìlání to s holkama?
{22513}{22544}Nemùeš bıt vánı!
{22544}{22623}Znamená to, e se vychyluješ jinudy?
{22689}{22730}Slyšeli jste to?
{22946}{23035}C-Coe? Øekl jsem nìco smìšného?
{23181}{23231}HEJ! VY!
{23231}{23303}Zvonek zvonil dávno!
{23927}{24064}Au... Ten parchant uèitel mì donutil |kleèet dokud moje nohy skoro neumøely!
{24080}{24108}Sakuro-kun?
{24214}{24248}Maekawo.
{24370}{24509}Jej, omlouvám se za to. |Udìlal jsem to pro tebe ještì trapnìjší.
{24536}{24626}Oh, to je okay. Jsem ta, která by se mìla omluvit.
{24682}{24752}Uh... To.. vzal to uèitel.
{24774}{24848}Hádám, e jsi byl pøekvapenı, e nosím nìco takového.
{24848}{24901}Uh... No, jo...
{24939}{25042}Nechápej mì špatnì. Je to jen talisman.
{25042}{25085}Talisman?
{25106}{25228}Jo! Je to kouzlo, které mi pomùe najít |pøítele. Všechny dívky to dìlají!
{25228}{25297}Huh... Najít pøítele, huh?
{25396}{25444}Take? Jakı je tvùj typ?
{25460}{25492}Sakura...!
{25492}{25554}Oh...! To je tajemství, hlupáku!
{26132}{26184}Opravdu nìkdy nìco zvru!
{28259}{28288}Co jsem...
{28617}{28733}Co to dìlám, vyvedenı z míry nìèím takovım?
{28808}{28889}Nezáleí na tom, s kım se Sakura rozhoduje potloukat se!
{29452}{29512}ádné kouøení dokud ti není dvacet!
{29512}{29553}Sakuro!
{29587}{29718}Tvoje kolo bylo pryè, tak jsem poèítal|s tím, e budeš pravdìpodobnì tady.
{29770}{29871}Dostal jsi moje spoleèenské chování smìrek k vìdì.|/pokud tu vìtu nechápete, nejste sami :D/
{30031}{30132}Shizuko, co si myslíš o holkách?
{30132}{30170}Holkách?
{30170}{30239}Oh, no... Myslím, e jsou roztomilé.
{30269}{30342}Pak, myslím... nemyslel bys na ty vìci....
{30372}{30416}...jako dìlat to?
{30446}{30472}HUH?
{30512}{30610}Zase tì ve škole uèili divné vìci?
{30638}{30732}Kluci z mojí tøídy, mi dneska opravdu vlezli do tváøe...
{30732}{30896}...potom, co jsem jim øekl, e jsem opravdu|nikdy nepøemıšlel o dìlání to s holkama, smáli se.
{30957}{31060}Nìkdy taky pøemıšlím o tom, e chci dìlat takové tvìci.
{31110}{31179}Ty, taky? Vìdìl jsem to.
{31229}{31294}Moná jsem jinı ne ostatní.
{31367}{31410}Jen to nemùu pochopit!
{31429}{31554}To není nic takového. Jednou tomu porozumíš.
{32215}{32317}Proè na mì tak zíráš?
{32317}{32381}Mám nìco na oblièeji?
{32381}{32460}N-Ne... To nic.
{32500}{32596}Vlezl do hlavy podivnı nápad, to je celé.
{32618}{32652}Podivnı nápad?
{32668}{32718}Jakı? Øekni mi to.
{32802}{32843}Kdybych ti to øekl, byl bys naštvanı.
{32843}{32893}Tak u mi to øekni!
{32936}{32963}Co kdy øeknu...
{33000}{33077}...e jsem tì právì teï chtìl políbit?
{34171}{34226}Proè chceš políbit MÌ?
{34244}{34281}Jsem kluk!
{34406}{34478}Dìlám si legraci! Byl to jen vtip!
{34503}{34549}Co jiného by to mohlo bıt...?
{34549}{34577}To...
{34635}{34708}Je to tvoje chyba, e øíkáš takové podivnosti!
{34708}{34733}To je špatné!
{34889}{34917}Jednou...
{34944}{34984}Mùeš mì políbit jen jednou!
{35010}{35064}Ale byl to vtip!
{35303}{35357}Uh... Tak pojï, udìláme to.
{35381}{35413}Pohni u!
{35436}{35484}Co kdy nìkdo pøijde?
{35485}{35589}Co se to v tvé hlavì dìje? Zapomeò na to!
{36812}{36951}Mohlo by to bıt... e moøskı vánek letìl nad našimi hlavami...
{37013}{37100}Ne... Myslím, e jsou to hvìzdy...
{37454}{37557}Dobrá... To je ten samı proslov, kterı |dávám mladım lidem kadı rok...
{37557}{37685}..ale já chci, abyste nebyli pokoušeni|se flákat jen proto, e jsou letní prázdniny.
{37695}{37841}Dìlejte co mùete a zbyteènì|neplıtvejte tímto mimoøádnım èasem!
{37841}{37977}Prosím kadı váš den dobøe|zvate, oèištìte ivotní styl.
{37995}{38175}Také, studenti vyšší støední chovejte|se v pracovním svìtì stejnì jako dospìlí!
{38175}{38385}Jestli si toto léto berete brigád, buïte|velmi opatrní, do èeho se pouštíte!
{38778}{38805}Morifuji-kun!
{38882}{38908}Oh, to jsi ty.
{38964}{39102}Morifuji-kun, ty... dìláš obzvláštì po tomhle nìco?
{39124}{39167}No, vlastnì...
{39222}{39314}Dnes neunikneš, Sakuro!
{39328}{39409}Ale øíkal jsem ti, e dneska musím nìkde bıt!
{39409}{39466}No tak, nech mì jít... prosím?
{39486}{39530}Nemyslím si to!
{39551}{39642}Pokud se do toho dáš, úklid tøídy nezabere ádnı èas!
{39642}{39721}Prosím! Slituj se! Jen tentokrát!
{39721}{39779}Ne, nikdy!
{39813}{39877}Posloucháš, Morifuji-kun?
{39932}{39986}Uh, jo! Okay, pojïme!
{40025}{40048}Skvìlé!
{40984}{41046}Opravdu oceòuju tvoji pomoc.
{41080}{41128}Myslíš, e budeš dìlat tuhle práci?
{41128}{41193}Jsem si jistá, e to otec miluje!
{41224}{41348}Jsem hrozná ve vybírání dárkù pro mue.
{41348}{41377}Chápu.
{42138}{42202}Sakura má jistì zpodìní!
{42243}{42301}Hladovím!
{42320}{42402}Ale, ale. Jen poèkej trochu déle.
{42421}{42535}Moná se zaèal starat o to, aby vypadal hezky?
{42565}{42602}Padron, pardon!
{42602}{42643}Jdeš pozdì!
{42785}{42921}Hej, Sakuro! Zpozdil se's, protoe|si se nemohl odtrhnou od zrcadla?
{42921}{42981}Huh? O èem to mluvíš?
{43015}{43074}Máš pøítelkyni nebo nìco?
{43074}{43123}Nech toho, Junpei!
{43188}{43296}C-Co máš za problém? Jen si dìlám legraci...
{43318}{43421}Mimo to, co jsem øekl takového, e jsi se naštval?
{43421}{43482}N.... Nic. Koho to zajímá?
{43503}{43587}No tak, vy dva. Zaènìte jíst, ne to vystydne!
{43761}{43843}Shizuko...? Mùu jít na vteøinku dovnitø?
{43843}{43873}Je otevøeno.
{44146}{44237}Co se dìje, Sakuro? Vypadáš vydeprimovanì.
{44331}{44407}Nemùu pochopit, co se dìje,...
{44444}{44488}...protoe tì miluju.
{44594}{44633}Nakonec, Myslím, e ano.
{44678}{44737}Je to šílené, e?
{44979}{45035}Moná je to jen zvìdavost?
{45081}{45167}Ale mùu udìlat nìco takového jen ze zvìdavosti?
{45232}{45339}Spousta dìtí v našem vìku experimentují|s šílenımi vìcmi jako je tohle.
{45339}{45379}Ale, já...
{45418}{45508}...myslím to opravdu vánì! Shizuko!
{46398}{46424}...Sakuro!
{46470}{46524}Musel jsi bıt nervózní,|protoe to bylo tvoje poprvé!
{46590}{46676}Nebo moná, chceš zkusit nìco jiného?
{46723}{46757}Co tím myslíš?
{46776}{46851}Nìco více vzrušujícího ne líbání.
{46880}{46898}Ty...!
{47054}{47082}Bastarde!
{47263}{47299}Sakuro, poèkej!
{47404}{47431}Sakuro-kun?
{47474}{47510}SAKURO!
{48578}{48630}Bylo to nejlepší.
{49231}{49349}Bude to pro nás oba dva dobré, kdy|od sebe budeme na chvíli pryè.
{51093}{51165}Ubìhly dva tıdny po tom zmatku...
{51165}{51300}...a pøedtím, ne jsem se nadáll, byl vrchol léta.
{51334}{51549}Myslel bys, e bychom mohli jeden od druhého utéct |bìhem letních prázdnin, ít pod stejnou støechou s všechno...
{51563}{51697}...ale díkybohu, moje záminka uèení se|na zkoušky udrovala setkání na minimum.
{51895}{51980}Shizuko-kun, jsi slušnı? Jdu dovnitø.
{51999}{52038}Uh, jistì! Pojï dál!
{52076}{52155}No? Vyhráváš boj s knihami?
{52173}{52193}Více ménì.
{52214}{52271}Tady máš. Na posilnìnou.
{52271}{52355}Díky. Mimochodem, kde jsou všichni?
{52355}{52404}Myslím, e šli všichni na plá.
{52404}{52472}Boe, mají štìstí, e nemusí dìlat tohle!
{52472}{52571}Jo... Všichni Masatové se potloukají kolem domu.
{52571}{52646}Kdybych mìla mladšího bratra, vyrazila bych ho ven!
{52674}{52757}Rozhodl se's na jakou univerzitu bys rád šel?
{52784}{52797}Jo.
{52826}{52912}Myslel jsem, e bych chodil na univerzitu do Tokya.
{52933}{52988}Oh... To znamená, e odsud odejdeš...
{52988}{53030}Bude to tu bez tebe osamìlé.
{53064}{53122}Pokud to udìlám!
{53167}{53251}Jedinì lidé, kteøí øíkají takové vìci se zmìní v ty šastné!
{53324}{53434}Hej, Shizuko-kun... Je to to, co tì poslední dobou trápí?
{53502}{53606}Vdycky hromadíš všechny své problémy uvnitø sebe.
{53636}{53716}Ale nemyslím si, e se toho musíš tolik obávat.
{53728}{53871}Dostalas mì. Byl tvùj hlavní pøedmìt |psychologie nebo nìco, Haruno-san?
{53890}{53993}Jen jsem mìla ten pocit, to je celé. |Myslím, e vím, co proíváš.
{54018}{54165}Jo... Je tu hodnì vìcí mimo zkoušky, |co se cpou do starostí v ivotì...
{54189}{54259}...jako vìci, o kterıch nemùeš mluvit.
{54283}{54394}Jistì jsi hodnì vyrostl, Shizuko-kun.
{54482}{54640}Vím, e nìco pøináší smutek, ale mìj na pamìti...
{54640}{54742}...e problémy se kterımi se teï potıkáš jsou|ty, které pøijdou jen jednou za ivot.
{54771}{54910}Poslouchej. Nepropadej zoufalství nebo tì to srazí k zemi.
{54910}{55035}Nezáleí na tom, jak se to obrátí, bì se svımi obavami.
{55078}{55165}Jsem si jistá, e tahle malá lekce ti bude k uitku.
{55205}{55313}To je pravda. Dìkuju, Haruno-san.
{55489}{55537}Nìkdy si øíkám...
{55567}{55647}...proè jsem se nezamiloval do téhle osoby?
{56693}{56719}Sakuro-kun?
{56754}{56778}Maekawo!
{56803}{56835}Mùu si tu sednout?
{56835}{56861}Jistì.
{56922}{56997}Vypadáš vydeprimovanì. Dìje se nìco?
{56997}{57048}Oh, ne opravdu.
{57048}{57169}Oh? Doufám, e to jde. Já...
{57203}{57353}Nìco ti dluím, take i mùeš øíct všechno, okay?
{57374}{57423}Jo. Díky.
{57446}{57556}Dobøe, jdu na cvièení! Uvidíme se pozdìji!
{57556}{57616}Uh... Maekawo?
{57721}{57921}Je to jen... Moná si myslíš, e jsem úplnı podivín,|ptát se tì na nìco takového, ale...
{57987}{58133}Povìz mi... Mùu nìkoho políbit jen ze zvìdavosti?
{58133}{58159}Coe?
{58246}{58351}Omlouvám se. Byla hloupost se ptát.
{58374}{58480}Sakuro-kun... políbil jsi nìkoho?
{58480}{58508}Jo.
{58535}{58617}Ale moc dobøe tomu nerozumím.
{59165}{59265}Kdybych tì právì teï poádala, abys mì políbil...
{59293}{59328}...chtìl bys?
{59734}{59781}Nejedeš domù, abys vidìl svou rodinu?
{59848}{59871}Ne!
{59895}{59968}U jsem jim volal, abych jim øekl, e nepøijedu.
{59983}{60135}Øíkáš, e se uèíš na zkoušky, ale vlastnì|jsi jen chtìl nìjakı èas pro sebe?
{60151}{60166}Jo.
{60217}{60336}Pøíleitostnì, je to dobrá vìc oddat|se sám starostem ivota.
{60486}{60606}Tvoje sestra mi pøed pùl minutou øekla tu samou vìc!
{60606}{60643}Oh, ona?
{60672}{60702}Ona.
{61560}{61595}Maekawo...
{61595}{61632}Sakuro-kun...
{62179}{62220}Nemùu to udìlat!
{62272}{62311}Nìco je jiné!
{62400}{62430}Není to správné!
{62456}{62497}Myslela jsem si to.
{62583}{62742}Nejsi ten typ èlovìka, kterı by nìkoho |políbil jen pro zábavu nebo ze zvìdavosti.
{62845}{62888}Teï, vidíš?
{62888}{62918}V-Vidìt co?
{62920}{62960}Myslím...
{63045}{63075}...e ty...
{63105}{63159}...miluješ toho, kdo to je!
{63179}{63203}Miluju?
{63319}{63380}...jsi zamilovanı...!
{63522}{63559}Miluju Shizuku...?
{63586}{63635}Hej, co dìláš?
{63635}{63664}Nic!
{63729}{63763}Co to sakra JE?
{63817}{63940}Oh, jen jsem si myslel, e bych mìl naposledy|podívat okolo, pøedtím, ne se vrátím domù!
{63959}{64023}Boe! Jsi totální pošuk, Junpei!
{64023}{64073}Pojï a zaobli se se mnou!
{64073}{64133}Oh, hej... Ohòostroje...
{64150}{64237}Oh, jo! Shizuka je letos bude moct vidìt!
{64263}{64291}Co tím myslíš?
{64291}{64435}Coe, neslyšel jsi? Shizuka letos nejede domù ke své rodinì.
{64435}{64463}Opravdu?
{64463}{64562}Jo. Je zamìstnanı studiem na zkoušky.
{64665}{64737}/Ukázka Ohòostrojù Nakkyou/
{65032}{65101}Hej, Ichitaro! Pøiprav se prùvod pøenosné svatynì!
{65121}{65149}Pøenosné svatynì?
{65527}{65567}OHÒOSTROJE!
{65639}{65664}H-Hej!
{65902}{65965}Ichitaro, co to do tebe vjelo?
{66005}{66038}Promiò, mami!
{68649}{68681}Shizuko...!
{69643}{69661}Hej, tady!
{69838}{69854}Coe?
{69874}{69910}Od kdy?
{69910}{69934}Huh?
{69934}{69986}Nemìla jsem ponìtí!
{70235}{70278}Oh! Zaèaly!
{70278}{70357}Pojïme nìkde, kde je uvidíme lépe.
{70406}{70424}Správnì...
{72160}{72186}Urèitì je divnı.
{72207}{72301}Slzy se objevují v poslední dobì tak snadno.
{72640}{72663}Coe...?
{72976}{73030}Myslel jsem si, e bys mìl bıt tady!
{73045}{73066}Sakuro!
{73139}{73252}Bylo trochu kruté jet na tomhle kousku |šrotu celou cestu z mého domu!
{73252}{73306}Z tvého domu...?
{73306}{73341}To nemùeš myslet vánì, ty...?
{73401}{73440}Jen jsem se na to cítil.
{73683}{73726}Proè jsi se vrátil zpátky?
{73848}{73926}Protoe mi nìco tíilo mysl.
{73968}{74037}Byla jedna vìc, kterou jsem chtìl øíct...
{74112}{74150}...chtìl jsem se ti omluvit.
{74427}{74520}Omlouvám se. Mìl jsem strach.
{74536}{74711}Cítil jsem, e kdybych tak zùstal, |nakonec bychom si ublíili navzájem.
{74711}{74735}Shizuko?
{74770}{74874}Moná jsem se jenom bál, abych se nezranil.
{74914}{74938}Shizuko!
{76427}{76562}Myslím, e mizernì líbám...
{76786}{76913}Nìco takového závisí na tom, jak|to kadı jednotlivec cítí.
{76937}{76955}Vidíš?
{77133}{77300}Jsi jedinı, kdo mi mùe udìlat|takovı pocit polibkem, Sakuro.
{77836}{77855}Shizuko!
{77933}{77955}Sakuro...
{78078}{78200}Sakuro, myslím, e ztrácím kontrolu...!
{78239}{78258}Já, taky.
{78350}{78446}P... Poèkej vteøinku!
{78479}{78564}Nevadí mi, kdy mì líbáš, ale...
{78590}{78646}...nestrkej mi tam pøíštì jazyk!
{78646}{78666}Huh?
{78689}{78768}Strèil jsi mi tam jazyk naposledy!
{78782}{78867}V šoku jsem zadrel dech a polkl sliny.
{79000}{79074}To není nic k smíchu! Opravdu.
{79074}{79123}Okay, okay.
{79162}{79252}Take jakı druh polibku máš rád?
{79283}{79386}Ten jako poprvé. Ten bez jazyka.
{79402}{79416}Jako takovı?
{79493}{79558}Mùeš ho udìlat delší, to víš.
{80982}{81121}Shizuko... Myslím, e tì miluju...
{81151}{81241} Na zaèátku, nemusíme to dìlat, jestli nechceš.
{81800}{81824}Sakuro...
{81872}{81993}Naše láska se ubírá prvními nejistımi kroky.
{82038}{82125}Budu schopnı dret tvou ruku navdy?
{82144}{82231}Sakuro, já...
{82340}{82535}-Ne jsem se nadál, jako by to byla tvá pravda-
{82580}{82765}-Usmíval jsi se na tomto sluneèném místì-
{82786}{82910}-Doba, kdy slzy pøetékaly-
{82910}{83032}-I doba, kdy jsme si navzájem ubliovali-
{83032}{83202}-byla pro mì slast-
{83297}{83483}-Èerné klobouky a bílé vzory-
{83536}{83734}-Se zdvihají v jemném vánku-
{83749}{83998}-Chci tì dret a pohrávat si s tebou navdy-
{83998}{84157}-A vùbec, jakkoli...-
{84226}{84332}-Modrá obloha, bílé mraky-
{84332}{84485}-Byl to jen další svìt, kterı nepatøil-
{84485}{84691}-nikomu, ale nám-
{84691}{84809}-Sbohem je pro tebe "znovu ahoj!"-
{84809}{84955}-U tì znovu nechci vidìt plakat-
{84955}{84985}-Tak se neotáèej-
{85219}{85405}-Pøijel na konci snu-
{85455}{85649}-Nìkdy ráno a do tohoto malého pokoje-
{85667}{85778}-Ze všech co milují mùu spoèítat na mıch prstech-
{85778}{85890}-Jedinı, píšící graffity na zdi-
{85890}{86088}-jsi byl vdycky ty-
{86735}{86999}-ádnı strach, nenechám to zaplavit nostalgií-
{86999}{87161}-Tak do toho a napiš mi-
{87226}{87403}-Naše období je vdycky plné-
{87403}{87672}-sobeckého rozmaru a konzervovaného dusu-
{87716}{87928}-Poté, co jsem to vyèerpal, mé srdce-
{87947}{88144}-se zachvìlo jako bych se usmál-
{88187}{88296}-Modrá obloha, bílé mraky-
{88296}{88447}-Byl to jen další svìt, kterı nepatøil-
{88447}{88649}-nikomu, ale nám-
{88649}{88770}-Sbohem je pro tebe "znovu ahoj!"-
{88770}{89031}Pøeklad + korekce + èasování: WelW(etkaAa)-hime|www.mycolorfullife.blog.cz|/Tohle mì málem zabilo, tak si toho vate :D/
