{1}{1}29.997
{0}{95}23.976 FPS, SChiZO DVD Rip version
{95}{140}To proto by bylo dobré,|kdyby všichni zemøeli...
{1440}{1500}Neon Genesis Evangelion filmová verze|- Vzduch & Mé opravdové srdce pro tebe
{1501}{1780}Tak povìz,|proè jsi tady?
{1781}{1885}Je stále dobré tu bıt?
{1886}{1960}V kinech 17. Èervence. Pøedobjednané|lístky vèetnì plakátu, ji v prodeji!
{1961}{2027}Vstupné: 1500 Yenù, Studenti: 1200 Yenù.|Vyrobeno Produkèním vıborem Eva. Distribuce/Toei.|Tento film je animovanı.
{4283}{4353}Neon Genesis Evangelion|Filmová verze
{5255}{5366}2. a 3. oddìlení se uzavøe v 18:00.
{5379}{5481}Celı personál musí bıt evakuován do 16:30.|*Asuka Langley*
{5490}{5562}Mám strach z Misato a Ayanami...
{5609}{5686}Pomoz mi...|Pomoz mi, Asuko.
{5791}{5876}Hej...vzbuï se.|Hej!
{5919}{5955}Vzbuï se!
{5991}{6035}Hej...hej...
{6050}{6145}Asuko...Asuko...|Asuko!
{6294}{6319}Pomoz mi.
{6346}{6379}Pomoz mi prosím.
{6405}{6438}Pomoz mi.
{6455}{6486}Pomoz mi.
{6530}{6556}Pomoz mi!
{6567}{6662}Øekni mi "pitomèe", tak jako vdycky!
{6686}{6710}Hej!
{7811}{7858}Jsem fakt odpornej.
{1870}{7920}Epizoda 25: Vzduch
{7943}{8011}Jak to, e je velitelství uzavøeno?|Nepustí nás ven?
{8018}{8069}Je poplach prvního stupnì.
{8076}{8159}Proè poplach?|Nebyl u Kaoru poslední Andìl?
{8163}{8231}Byl.|Všichni Andìlé byli poraeni.
{8234}{8295}Nemìl by teï nastat mír?
{8300}{8370}Co NERV?|A co se stane s Evami?
{8372}{8412}Ké by tu byla sleèna Ritsuko.
{8415}{8472}Organizace NERV|bude zøejmì rozpuštìna.
{8488}{8550}Nicménì netuším, co bude s námi.
{8562}{8660}Jediné co mùeme dìlat,|je èekat ne zaène projekt Zdokonalení.
{8763}{8834}Take lidstvo, rasa beznadìjnıch,|nedokonalıch jedincù,
{8836}{8931}dosáhla hranic svého|evoluèního potenciálu.
{8934}{9023}Projekt Zdokonalení má|za úkol zahájit...
{9027}{9099}pøemìnu mnoha jedincù|v jednu jedinou bytost.
{9102}{9153}Vıbor SEELE k tomu nepouije|NERV ani Adama.
{9155}{9191}Pouijí Evy.
{9193}{9240}Pøesnì jak Kaji pøedpovìdìl.
{9250}{9295}Stanovenı èas nadešel.
{9302}{9360}Bez Longinusova kopí
{9363}{9419}nemùeme pouít Lilith|k dokonèení projektu.
{9423}{9512}Jediná monost je pouít|Lilitina jediného pravého potomka,
{9515}{9547}jednotku EVA 01.
{9551}{9612}To nebylo v|pùvodním plánu SEELE.
{9626}{9711}Vytvoøení Evy bylo|vyvrcholením lidské existence.
{9723}{9795}Lidé se musí vyvinout|a vytvoøit novı svìt.
{9805}{9858}Proto jsme vytvoøili sériové EVy.
{9863}{9912}Nepotøebujeme se vzdát|naši lidské formy...
{9915}{9978}k nástupu na naši Archu|zvanou Eva.
{9983}{10110}Je to pouze pøechodovı obøad ke|znovuzrození tìch, kdo jsou uvìznìni.
{10116}{10193}V osudu znièení je také|radost znovuzrození.
{10195}{10255}Bùh, lidé a všechny ostatní|formy ivota uijí smrti,
{10258}{10323}aby byly znovuzrozeni|jako jedna bytost.
{10332}{10382}Smrt nedává zrodit nièemu.
{10387}{10448}Ty si ale smrt zaslouíš.
{10495}{10581}Lidé ijí, protoe chtìjí,|aby jejich ivot mìl smysl.
{10596}{10699}To proto zùstala v Evì.|Bylo to její pøání, e?
{12213}{12314}Aha...to je to, co se opravdu|stalo pøi Druhém Úderu.
{12335}{12368}Nìkdo mì zachytil?!
{12455}{12499}Ne to nebylo ono...
{12541}{12568}U to zaèalo.
{12611}{12666}Došlo k nepøátelské invazi!
{12668}{12739}Zapnìte nouzovou pohotovostní|komunikaci v levém køídle!
{12741}{12780}Pouijte satelit,|pokud bude tøeba!
{12783}{12827}Jaká je situace|na pravém køídle?
{12833}{12911}Všechny odchozí hovory|jsou blokovány!
{12941}{12978}Nepøítelùv cíl je MAGI!
{12999}{13040}Data jsou pøenášena|ze všech okolních sítí.
{13051}{13106}Hackují se do systému MAGI.
{13108}{13135}To se dalo èekat.
{13139}{13188}Je to místní invaze z|MAGI2 v Matsushiro?
{13191}{13243}Ne.|Je to 5 MAGI pracujících dohromady.
{13246}{13315}Identifikovali jsme MAGI z Nìmecka,|Èíny, Spojenıch státù...invaze potvrzena.
{13318}{13378}SEELE pouilo všechnu svou sílu.
{13386}{13466}Pomìr 5:1.|To je velmi špatné.
{13484}{13527}Ètvrtı firewall prolomen.
{13535}{13582}Zamykám hlavní databázi!
{13586}{13633}Bezvıslednì!|Nabourali se do systému!
{13637}{13719}Vstupuje do niší úrovnì.|Záloní systém nefunguje.
{13736}{13769}To je špatné.
{13771}{13863}Jestli zajmou MAGI,|mùou ovládat celé velitelství.
{14095}{14131}Nechte mì hádat.
{14134}{14194}Potøebují pomoct|s obrannım systémem MAGI.
{14196}{14242}Ano. Ohlednì detailù...
{14245}{14300}se zeptejte Ibuki|v kontrolní centru.
{14304}{14388}Klidnì vyuije enu,|kterou opustil.
{14391}{14441}Tomu se øíká egoismus.
{14454}{14513}Poplach 2. stupnì v platnosti.
{14520}{14546}Jaká je situace?
{14554}{14656}Dobré ráno. Tokyo 2 právì vydalo|speciální naøízení A801.
{14664}{14689}801?
{14691}{14755}NERV byl zbaven právní ochrany|a jeho soudní pravomoce byly anulovány.
{14759}{14828}Naøízení bylo zasláno|japonské vládì.
{14868}{14943}Bylo to zatím první varování.|Zkoušeli ovládnout MAGI,
{14947}{15023}ale zatím to máme pod kontrolou.
{15040}{15063}Tady je Ibuki.
{15066}{15156}Doktorka Akagi pracuje|na vylepšení ochrany MAGI.
{15226}{15265}Ritsuko?!
{15490}{15548}Dìlám nìco hloupého?
{15569}{15658}Ve vztahu mezi muem|a enou není ádná logika.
{15707}{15752}Není to tak,
{15775}{15807}mami?
{15827}{15909}Obvod Goura obnoven o 0,2%.
{15911}{15938}Jak dlouho?
{15952}{16023}Zvládneme to vèas.|Doktorka Akagi je ohromná!
{16039}{16095}Jenom infiltrují MAGI?
{16097}{16170}Pochybuji,|e nás hodlají tak šetøit.
{16176}{16217}Ovládnutí MAGI je jen první vlna.
{16219}{16294}Cíl tìch parchantù je|obsadit základnu...
{16296}{16355}a zajmout dvì zbıvající Evy, e?
{16367}{16462}Samozøejmì.|Lilith a Adam jsou v našich rukách.
{16491}{16535}Není divu,|e to starouše tak znepokojuje.
{16627}{16674}Invaze do MAGI|byla zastavena.
{16687}{16732}Obrana typu B-7 Danang provedena.
{16738}{16802}Pøístup zvenku je zastaven|na dalších 62 hodin.
{16985}{17030}Uvidíme se brzy,|mami.
{17044}{17147}Ikari pouil v MAGI|obranı program 666.
{17151}{17201}Není lehké se pøes nìj dostat.
{17203}{17284}Zdá se, e musíme|upustit od obsazení MAGI.
{17291}{17400}Chtìl jsem to vyøešit mírumilovnì,|ale teï je to nemoné.
{17406}{17475}Zahajte invazi celé základny!
{17711}{17760}Všem jednotkám -|proveïte plán!
{18467}{18530}Ztratili jsme kontakt|s radary 8-17!
{18533}{18577}Velká armáda speciálních jednotek...
{18579}{18621}napadla vnìjší obranou linii!
{18623}{18683}Dvì další postupují zpoza hory!
{18695}{18786}Take po tom všem èím jsme prošli,|je èlovìk tím posledním nepøítelem.
{18793}{18856}Všichni pøejdìte do|prvního bojového stupnì.
{18859}{18907}Bojovı stupeò?
{18920}{19003}Ale jsou to pøeci lidé,|ne Andìlé!
{19014}{19059}Ké by tak uvaovali i oni.
{19639}{19678}Hej, co se dìje?|Hej!
{19680}{19705}O co jde?
{19707}{19761}Vysílání z jiní brány je ---
{20038}{20079}První bránu není moné pouít!
{20082}{20128}Poár v 5. vıchodní bránì!
{20131}{20190}Útoèící armáda vstoupila|do první bojové úrovnì!
{20203}{20247}The west side attack is a decoy!
{20257}{20325}Pokud mají za cíl ovládnout EVy,|pak pùjdou nejdøív po pilotech.
{20330}{20403}Øekni Shinjimu a je pøipraven v Jednotce 01.|- Rozumím.
{20406}{20453}Kde je Asuka?|- V nemocnièním pokoji 303.
{20485}{20531}Dostaòte ji do Evy 02!
{20535}{20611}Ale její synchronizace s Evou|se zatím nezlepšila!
{20621}{20676}Pokud ji najdou,|zabojou ji.
{20679}{20736}Kdy ji dáme do Evy 02,|aspoò bude v bezpeèí.
{20739}{20779}Rozumím.|Zastavte léèení pilota...
{20780}{20863}A bude Asuka uvnitø,|ukryjte Evu 02 na dno jezera.
{20866}{20926}I kdy ji mohou snadno najít,|je to lepší ne bıt zastøelen.
{20929}{20970}Kde je Rei??|- Nemùu ji najít.
{20972}{21007}pilot EVy 00 chybí!
{21032}{21087}Zabijou ji...|Najdìte ji! Rychle!
{21523}{21563}Eva 02 odpálena z tunelu èíslo 8.
{21566}{21622}Zùstane pod vodou|v hloubce 70 metrù.
{21624}{21708}Odpalte Evu 01 hned po ní.|Umístìte ji v Geofrontu!
{21711}{21770}Nemùeme!|Shinji tu ještì není!
{21832}{21863}Paneboe...
{21872}{21939}Druhá úroveò byla kompletnì uzavøena.
{21941}{22026}Všechen nebojovı personál musí|evakuovat trasou 87, opakuji...
{22149}{22200}3. podzemní barikáda znièena!
{22203}{22259}Nepøátelé napadají úroveò 2.
{22261}{22320}Nemáme monost,|jak je udret.
{22323}{22371}Je jen otázka èasu,|ne ovládnou všechno.
{22411}{22483}Postarejte se o to,|profesore Fuyutsuki.
{22486}{22555}Rozumím.|Pozdravujte ode mì Yui.
{23138}{23178}Druhá úroveò bez odezvy!
{23182}{23234}Ztratili jsme kontakt|s kontrolní místností 77!
{23246}{23307}Jednokolejová tra 57 znièena!
{23310}{23379}To je strašné!|Radši bych bojoval s Andìly.
{23393}{23487}Samozøejmì.|Nejsme vycvièení pro boj s lidmi.
{23739}{23778}Zbavte se nejdøív èervené jednotky.
{23943}{24025}Oblast B na tøetí úrovni byla obsazena!|Celá oblast byla ovládnuta!
{24027}{24068}Nepøátelé jsou také v oblasti F!
{24071}{24116}Hlavní obchvat je pod palbou.
{24128}{24202}Uzavøete úrovnì 1-3.|Útoèné tımy, naøizuji ústup!
{24207}{24299}Vypuste bakelit do všech vstupù|a po sekci 803.
{24302}{24327}Rozumím!
{24330}{24395}Zahájeno vypuštìní|bakelitu v sekci 703,
{24398}{24431}30 sekund na dokonèení.
{24443}{24504}Zahájeno vypuštìní|bakelitu v sekci 737,...
{24515}{24573}Doufejme,|e to nepøítele zpomalí.
{24575}{24638}Majore Katsuragi,|trasa 47 byla odpojena!
{24641}{24722}3. jednotka nemùe postoupit.|Shinji je od nás odøíznutı!
{24887}{24951}Všechen nebojovı personál,|prosím vyhıbejte se boji.
{24985}{25016}Nepøátelé jsou profesionálové,
{25020}{25066}pokud se nedostanete do Centrálního Dogma,
{25068}{25123}je lepší se vzdát.
{25126}{25186}Postarej se tady o to za mì.|- Dobrá.
{25242}{25280}Hora Futagoyama je zajištìna.
{25283}{25327}Je to teší,|ne jsme mysleli.
{25329}{25388}Nikdy nedostaneme lehkou práci.
{25406}{25543}To je šílenství!|Velitelství není stavìné proti invazi armády...
{25555}{25599}Tìko se ubráníme teroristùm.
{25601}{25700}Pokud je to skuteèná válka,|tohle vybavení nestaèí.
{25714}{25789}Postupnì sníili vıdaje|na obrannı systém.
{25791}{25856}Moná to plánovali u od zaèátku.
{25859}{25897}Velmi pravdìpodobnì...
{26163}{26192}Odjisti pojistku.
{26233}{26311}Já...|já z toho neumím støílet.
{26314}{26367}Ale umíš!|Dìlej to jako v tréninku!
{26370}{26440}Ale to byly terèe,|ne lidi!
{26465}{26514}Idiote!|Buï vystøelíš ty nebo oni!
{26520}{26595}Epizoda 25: Láska je destruktivní
{26899}{26922}Rei.
{27092}{27136}Vìdìl jsem,|e tì tu najdu.
{27303}{27386}Èas nadešel.|Pojïme.
{27447}{27508}Úroveò 1 je zajištìna.|Pøepínám.
{27511}{27594}Rozumím. Postupujeme k MAGI a vstupujeme|do velitelského centra oblasti 2...
{27597}{27648}Naráíme na odpor.
{27651}{27746}Zahajte okamíté chlazení 5. sektoru.
{27857}{27900}Kdy najdete piloty Ev,|zabte je.
{27903}{27966}Eliminace nebojového personálu povolena.
{27968}{28040}Speciální jednotky,|postupte do niší úrovnì.
{28174}{28230}Našli jsme Tøetí dítì.|Zahajuji likvidaci.
{28298}{28354}Promiò chlapèe,|nemùu za to.
{28558}{28606}Ani já za to nemùu.
{28701}{28778}Fajn.|Nastup do jednotky 01.
{28884}{28933}Rozumím.|Obklíèili jsme purpurovou jednotku.
{28935}{28986}Ten bakelit pro nás|nebyl ádnou pøekákou.
{29082}{29215}Sakra...Chtìjí zabránit|kontaktu Shinjiho s Evou 01.
{29221}{29272}Dochází nám èas.
{29276}{29324}Rychle Shinji.
{29366}{29484}Chceš odtud utéct|nebo pilotovat Evu?
{29499}{29556}Jestli tu budeš sedìt|a nic nedìlat, zemøeš!
{29569}{29627}Pomoz mi Asuko...|pomoz mi...
{29634}{29734}V takovou chvli se schováváš|za sukni malé holky?!
{29737}{29811}Vzdát se v pùli cesty je|horší ne nedìlat nic!
{29825}{29866}Vstávej!
{29895}{29922}Hni sebou!
{29939}{30034}Chci umøít.|Nechci nic dìlat.
{30041}{30089}Pøestaò vanit|jako malej parchant!
{30091}{30141}A se ti to líbí nebo ne,|jsi poøád naivu!
{30143}{30218}Take se pohni a dìlej nìco.|Umøít mùeš potom.
{30303}{30327}To není dùleité.
{30331}{30401}Izolace Koneèného Dogma|má teï prioritu.
{30514}{30547}Ze všeho jsou trosky!
{30550}{30597}Tak proè u to rovnou|nevyhodí do vzduchu celé?
{30599}{30678}Chtìli nás dostat jedinım úderem,|ale pod námi je pùvodní MAGI.
{30680}{30714}Jinak by to asi u udìlali.
{30730}{30790}Snaí se ho získat nedotèenı,|e?
{30795}{30849}Snad nepouijí biochemické zbranì.
{30851}{30888}To by dopadlo špatnì.
{30891}{30926}Buï to a nebo N2 miny.
{31487}{31518}My o vlku...
{31520}{31568}Nezastaví se pøed nièím.
{31571}{31611}To trochu pøehnali!
{31771}{31834}Proè chtìjí Evy tak moc?
{31855}{31911}Chtìjí zahájit Tøetí Úder...
{31914}{31966}Ne pomocí Andìlù,|ale pouitím sériovıch Ev.
{31994}{32092}Druhı Úder pøed 15 lety byl|umìle vyvolán lidskım zámìrem,
{32103}{32183}protoe to byla jediná monost|jak minimalizovat nièivé následky.
{32190}{32258}Museli redukovat Adama|do stádia embria døíve,
{32261}{32323}ne se probudí ostatní Andìlé.
{32355}{32472}Shinji, my lidé jsme zrozeni|z ivotní formy zvané Lilith,
{32475}{32545}tak jako byl zrozen Adam.
{32554}{32606}To my jsme 18-tı Andìl.
{32614}{32676}Ostatní Andìlé jsou jen další formy ivota,
{32683}{32734}ve které jsme se mohli zrodit.
{32747}{32818}Je smutné,|e nemùeme vzájemnì existovat,
{32821}{32903}tøebae jsme v podstatì|stejná stvoøení.
{32931}{33026}Poslouchej Shinji.|Musíš znièit sériové Evy.
{33039}{33098}Je to jedinı zpùsob jak pøeít.
{33127}{33178}Linky jsou mrtvé.
{33181}{33202}*Prefektura Nagano nové Tokyo 2*
{33202}{33252}*Prefektura Nagano nové Tokyo 2*|Ano. Pøed tøemi minutami jsme...
{33252}{33297}*3. kanceláø ministerského pøedsedy*|zjistili explozi nukleárních hlavic.
{33297}{33402}Take NERV tajnì vyvíjel tento projekt zdokonalení lidstva,
{33405}{33518}za úèelem zahájit Tøetí úder ke znièení celého lidstva.
{33523}{33563}Je mi z toho zle.
{33569}{33624}Lidé jsou zøejmì jediní tvorové,
{33627}{33675}schopni nenávidìt|jedince svého druhu.
{33678}{33737}Myslím, e jediné, co nám zbıvá,
{33739}{33787}je znièit celou základnu NERVu.
{33791}{33856}Pøejete si pøestavbu|Nìmecka a Èíny?
{33863}{33914}Nebudeme opakovat|tu samou chybu.
{33918}{34016}Zapeèete je alespoò na 20 let.|Tak jako Staré Tokyo.
{34088}{34120}Radiaèní teplota horní|úrovnì se ochlazuje.
{34123}{34186}Vzduch je také v poøádku.
{34188}{34238}Pøemístìní všech tımù kompletní.
{34251}{34343}Fialová jednotka a 3. úroveò|Terminálního Dogma zajištìny.
{34348}{34377}A co èervená?
{34384}{34443}Našli jsme ji v jezeøe,|asi 70 metrù pod hladinou.
{34446}{34496}Nevíme, jestli je pilot naivu.
{34799}{34837}Já stále iju?
{35626}{35718}Nechci umøít.|Nechci umøít.
{35727}{35812}Nechci umøít.|Nechci umøít.
{35821}{35947}Nechci umøít.|Nechci umøít.
{35955}{35988}Jsi stále naivu...
{36035}{36110}Nemùeš teï umøít...
{36125}{36174}Musíš ít...
{36218}{36261}Nenechám tì umøít...
{36266}{36317}Ochráním tì...
{36319}{36396}Jsi stále naivu...
{36399}{36459}Nenechám tì umøít...
{36462}{36543}Nesmíš umøít...
{36546}{36591}Prosím zemøi se mnou!
{36593}{36627}Nezabíjej ji...
{36630}{36717}Nechci umøít.|Nechci umøít.
{36726}{36826}Nechci umøít.|Nechci umøít.
{36829}{36871}Musíš ít...
{36899}{36959}NECHCI UMØÍT!!!!
{37089}{37152}Mamá!|Ty jsi byla stále se mnou?
{37307}{37331}Mamá!
{37518}{37563}To...to je...!|- Paneboe!
{38290}{38369}Mamá... Mamá!|U to chápu!
{38419}{38458}Vıznam AT pole!
{38523}{38562}Vdy mì chráníš!
{38640}{38678}Hlídáš mì!
{39047}{39146}Byly jsme vdy spolu!|Mamá!
{39224}{39302}Eva 02 se aktivovala!|Asuka je v poøádku! Je naivu!
{39310}{39333}Asuka?!
{39427}{39452}Kabel!
{39458}{39535}Zahajte palbu na ten kabel!
{39649}{39697}I bez pupeèního kabelu,
{39724}{39795}mám na sobì 12 tisíc vrstev opevnìného pancíøe!
{39867}{39918}A mám své AT pole!
{40019}{40070}NEMÙU PROHRÁT...
{40135}{40184}...S TAKOVİMI ŠMEJDY!!
{40719}{40786}Odporná Eva.
{40789}{40856}Náš plán se zase|jednou nesplní.
{40863}{40967}Jed mùe bıt zastaven|pouze jedem.
{41678}{41714}Sériové Evy?
{41716}{41751}U byly dokonèeny?
{41931}{42033}Vyslali všech 9 Jednotek|s S2 systémem?
{42035}{42067}Není to trochu pøehnané?
{42085}{42144}Tedy...|pokud se nesnaí zaèít TO tady?!
{42616}{42707}Poslechni Asuko,|chci abys znièila ty sériové Evy.
{42721}{42764}Shinji ti pøijde napomoc,|hned jak bude moci,
{42767}{42799}tak to zkus vydret.
{42806}{42894}Take se dostaneme k Evì 01|skrz pohotovostní trasu 20?
{42896}{42955}Potvrzuji.|Zdroj energie je pod naši ochranou.
{42957}{43005}Pokud to stihnete|do tøí minut,
{43007}{43043}mùete dorazit|pøímo k bránì 7.
{43395}{43446}"Znièit ty sériové Evy",|jo?
{43473}{43544}Takhle Misato jedná s|èerstvì uzdravenım pacientem?
{43579}{43631}Devìt Jednotek za|tøi a pùl minuty...
{43634}{43691}to mám 20 sekund na kadou z nich.
{44185}{44208}První!
{44406}{44430}Tady to je.
{44635}{44667}Zmizeli.
{44669}{44748}Minuli jsme cíl.|Máme je pronásledovat?
{44751}{44774}Zamítnuto.
{44776}{44817}Zmizte.|To místo bude za chvíli zdemolováno.
{44819}{44843}Okamitì se stáhnìte.
{44852}{44875}Rozumím.
{44935}{45017}Takhle je snad mùeme|na chvíli zadret.
{45122}{45215}Neboj.|Není to tak vánı, jak to vypadá.
{45366}{45435}Je tady poøád proud.|Stále máme èas.
{45582}{45631}Poslouchej Shinji...
{45634}{45684}odteï jsi na to sám.
{45687}{45757}Budeš se muset|sám rozhodovat.
{45798}{45901}Já...já nemùu,|jsem k nièemu.
{45917}{46059}Nemùu pilotovat Evu,|kdy tím jen ubliuju lidem.
{46095}{46176}Myslel jsem, e nemám na|vıbìr a musím Evu pilotovat,
{46179}{46226}ale lhal jsem sám sobì.
{46228}{46314}Nemám na to pilotovat Evu,|vdy nièemu nerozumím!
{46316}{46387}Jsem neschopnı udìlat|cokoli dobrého pro ostatní.
{46439}{46489}Udìlal jsem Asuce|nìco strašného.
{46504}{46552}A Kaoru zemøel mıma rukama.
{46560}{46641}Nemám pøívìtivou, laskavou stránku.|Jsem slaboduchı, otravnı kluk.
{46643}{46744}Umím jen ubliovat ostatním!|Bude lepší kdy nebudu dìlat nic!
{46760}{46803}Já tì tu litovat nebudu.
{46807}{46906}Jestli nechceš ubliovat ostatním,|nedìlej nic a umøi si tu!
{46931}{47006}A breèením taky|nic nespravíš!
{47059}{47139}Nenávidíš se, viï?|Proto ubliuješ ostatním.
{47141}{47199}Hluboko v sobì cítíš,|e trpíš víc,
{47201}{47310}kdy ubliuješ ostatním,|ne bys nechal ubliovat sám sobì.
{47313}{47415}Ale Shinji,|bylo to tvé svobodné rozhodnutí.
{47419}{47518}Vybral sis, co jsi sám chtìl,|na to máš právo.
{47523}{47618}Pøestaò u lhát sám sobì a uvìdom si,|e MÁŠ monost se rozhodnout.
{47620}{47687}Pak se smiø s volbou,|kterou sis vybral.
{47690}{47755}Ty ale nejsi taková jako já.
{47758}{47810}Nièemu nerozumís!
{47845}{47893}No a co,|e nejsem jako ty?!
{47898}{47998}To neznamená,|e se máš vzdávat!
{48015}{48120}Pokud se vzdáš, NIKDY ti to neodpustím,|dokud budu naivu!
{48123}{48172}Ani já nejsem dokonalá.
{48179}{48254}Udìlala jsem spousty hloupıch|chyb a pozdìji jich litovala.
{48258}{48322}Jene, opakovala jsem je|znovu a znovu.
{48326}{48396}Byl to kolobìh falešné radosti a|kruté nenávisti k sobì samotné.
{48399}{48474}Ale pøesto jsem se pokadé|o sobì nìco nového dozvìdìla.
{48511}{48546}Prosím Shinji,
{48553}{48658}vlez znovu do Evy a ukonèi|to jednou provdy.
{48679}{48763}Pøijï na to, proè jsi sem pøišel.
{48766}{48845}Proè vlastnì existuješ.
{48858}{48928}Najdi své odpovìdi.|A a je najdeš,
{48943}{48987}vra se ke mì.
{49165}{49205}Slibuješ?
{49275}{49307}Šastnou cestu.
{49678}{49726}Takhle se líbají dospìlí.
{49736}{49791}Dokonèíme to,|a se vrátíš.
{50146}{50215}Kdybych vìdìla, e to tak dopadne,
{50218}{50360}vymìnila bych koberec,|jak to navrhovala Asuka.
{50387}{50437}e, Pen Pene?
{50486}{50595}Kaji...|Udìlala jsem správnou vìc, e?
{52611}{52674}Sakra,|ti maj tuhej koøínek!
{52677}{52752}A samozøejmì ten pitomec|Shinji se toulá bùhvíkde!
{53595}{53637}Èekala jsem na tebe.
{54588}{54618}Promiò...
{54654}{54767}Pøeprogramovala jsem MAGI|bez tvého vìdomí.
{54792}{54843}Poslední pøání milující dcery...
{54858}{54926}Mami, ukonèeme to spolu.
{55111}{55146}Co...?|Neaktivováno!?
{55149}{55174}PØÍSTUP ZAMÍTNUT
{55194}{55223}Casper mì zradil!?
{55236}{55334}Matko...jak sis mohla vybrat|svého milence místo mì?
{55379}{55418}Akagi Ritsuko,
{55435}{55474}já opravdu...
{55651}{55674}Lháøi.
{55906}{55934}Jak to venku vypadá?
{55936}{56004}Dosáhne svého aktivního limitu|za ménì ne minutu!
{56010}{56047}S takovou Asuka --
{56155}{56192}Nemùu prohrát!
{56207}{56246}Mamá mì ochraòuje!
{56327}{56351}Mamá?
{56380}{56411}Máma!
{56535}{56601}Tahle je poslední!
{57173}{57215}Longinusovo kopí?
{57786}{57884}Vnitøní zdroj energie vyèerpán.|Dosáhl svého aktivního limitu.
{57887}{57950}Jednotka 02 utichla.
{58007}{58036}Co je --
{58055}{58106}Znièené sériové Evy...
{58471}{58518}Sériové Evy jsou|znovu aktivní!
{58717}{58759}Chtìjí ji dodìlat?
{59089}{59114}Co se dìje?!
{59119}{59202}Já to nechci vidìt!|Nemùu se dívat!
{59207}{59251}To je jednotka 02?
{59599}{59682}Všechny vás zabiju.|Všechny vás zabiju.
{59734}{59842}Všechny vás zabiju. Všechny vás zabiju.|Všechny vás zabiju. Všechny vás zabiju.
{59845}{59874}Zabiju vás.
{60002}{60087}Zabiju vás.|Zabiju vás. Zabiju vás.
{60090}{60198}Zabiju vás. Zabiju vás.
{60208}{60233}Berserk!
{60235}{60306}Asuko, pøestaò!!
{60312}{60388}Zabiju vás. Zabiju vás.
{60391}{60487}Zabiju vás.|Zabiju vás. Zabiju vás.
{60490}{60598}Zabiju vás. Zabiju vás.
{60749}{60811}Shinji!|Jednotka 02...!!
{60815}{60872}Asuka je -- Asuko!!
{60877}{60935}Nemùu se dostat do Evy...
{60938}{60982}Memùu nic dìlat.
{61261}{61291}Matko.
{61386}{61431}Jednotka 01 se|koneènì brobudila.
{61874}{61920}Jednotka Evangelion 01!
{61923}{61955}Je to sám démon!
{62239}{62262}Asuko...
{62646}{62720}Pokraèování...
{69617}{69687}Chtìl bych z celého svého srdce|podìkovat štábu, hercùm, pøátelùm
{69689}{69758}a také pìti enám,|kteøí všichni dovedli do konce tento snímek.
{69760}{69790}Dìkuji.|Hideaki Anno
{69883}{69958}S Adamem jsem se u spojil.
{69960}{70031}Tohle je jedinı zpùsob,|jak se znovu setkat s Yui...
{70034}{70137}Zakázané splynutí|Adama s Lilith...
{70180}{70218}Nezbıvá nám moc èasu.
{70221}{70294}Tvé AT pole u déle|neudrí tvou podobu.
{70315}{70361}Zaènìme, Rei.
{70373}{70451}Otevøi své AT pole...|bariéru svého srdce.
{70454}{70530}Opus své nepotøebné|tìlo a propus svoji duši...
{70531}{70618}A spoj naše nedokonalé|duše znovu dohromady.
{70625}{70704}A pak mì zaveï tam,|kde je Yui.
{71036}{71110}Epizoda 26: Mé opravdové srdce pro tebe...
{71352}{71385}Asuko...
{71663}{71686}Ikari.
{71888}{71962}Z orbitu se nìco blíí|vysokou rychlostí.
{71965}{71999}Co ksakru?!
{72054}{72102}To svìtlo...|Longinusovo kopí?
{72341}{72404}To v co jsme doufali,|koneènì zaèalo.
{72408}{72499}Longinusovo kopí nám|bylo navráceno.
{72505}{72589}Máme míò jednotek, ne jsme èekali,|ale to nám musí staèit.
{72607}{72685}Odhalte pravou podobu|sériovıch Ev.
{72705}{72820}Tato skuteèná podoba|evangelizuje lidstvo.
{72837}{72906}Skrze nevyhnutelnou smrt a modlitby,
{72908}{72972}vrame se do pùvodního stavu.
{72975}{73045}To je stav,|kdy mohou duše odpoèívat v pokoji.
{73055}{73111}Nech svátost zaène.
{73459}{73512}Zajali Jednotku 01!
{73517}{73590}Její vıška je 12 000 metrù!|A stále stoupá!
{73599}{73625}Ti mizerové v SEELE.
{73627}{73704}Chtìjí pouít Evu 01|jako prostøedníka?
{73923}{73994}Eva 01 byla oznaèena|svatımi stigmaty.
{74003}{74081}Obnovme Strom ivota!
{74093}{74159}Sériové Evy byli|naši vìrní sluhové.
{74179}{74237}Byli stvoøeny pro|tento okamik.
{74449}{74500}Sériové Evy nastartovaly|svùj S2 systém.
{74504}{74570}Mìøitelné dimenzionální|hodnoty pøevrácené!
{74580}{74633}Všechny èíselné vırazy a hodnoty|jsou nemìøitelné!
{74648}{74693}Anti-AT pole.
{74812}{74933}Stejné jako pøed 15 lety.
{74935}{74986}Take...tohle je skuteènì|pøedehra k Tøetímu Úderu!
{75131}{75172}S2 systémy dosáhly|limitního bodu!
{75175}{75248}Nemùeme udret kontrolu|nad gravitací.
{75271}{75332}Naše mise selhala.
{75523}{75581}Pøímı zásah!|Otevøeny všechny štíty proti pozemním útokùm!
{75583}{75646}Druhá nárazová vlna narušuje|okolí velitelství!
{75652}{75694}Vnìjší štít je otevøenı!
{75803}{75859}Jsou to jen fyzické|nárazové vlny.
{75861}{75913}Pøepnìte tlumièe na maximální stupeò.|Mìlo by to vydret.
{76255}{76311}A zde, jako symbol vìènosti...
{76313}{76367}Obøad oèištìní Rudé Planety.
{76383}{76428}Nejprve se Geofront navrátí...
{76435}{76477}do své skuteèné podoby.
{76686}{76790}Lilithino vejce,|zdroj všeho ivého.
{76797}{76828}Èernı mìsíc.
{76847}{76945}U se nechceme vrátit|do její skoøápky,
{76963}{77034}ale to záleí na vùli Lilith.
{77073}{77116}U to zaèalo.
{77135}{77246}Tak, Rei, u je èas.|Sjedno mì znovu s Yui.
{77263}{77287}Co?!
{77303}{77359}Nejsem tvá loutka.
{77406}{77429}Proè?
{77431}{77486}Protoe nejsem ty.
{77548}{77580}Rei!
{77698}{77733}Prosím,
{77735}{77774}poèkej na mì!|Rei!
{77787}{77850}Ne, nemohu.|Ikari mì volá.
{77871}{77896}Rei!
{78017}{78040}Jsem doma.
{78044}{78079}"Vítej doma"
{79240}{79264}Rei...
{79266}{79330}Neidentifikovanı objekt vysoké|energie v Koneèném Dogma...
{79333}{79375}se blíí vysokou rychlostí!
{79379}{79443}AT pole potvrzeno!|Modrı vzorek!
{79456}{79483}Nemoné!|Je to Andìl?
{79490}{79555}Ne není!|Je to ... èlovìk!
{80336}{80426}Sakra...Sakra...
{80928}{80952}Ayanami?!
{81009}{81041}Rei...
{81240}{81328}Destrukcí osobnosti|pilota Jednotky 01,
{81331}{81395}budi lidstvo zkompletováno.
{81405}{81479}Tøetí odplata nastává.
{81677}{81742}AT pole sériovıch Ev resonují!
{81748}{81783}Resonance se rozšiøuje!
{81793}{81838}Zaèali se sjednocovat s Rei?
{82390}{82426}Psychograf je nestabilní.
{82434}{82483}Zaèíná se projevovat|pilotùv nestabilní stav!
{82496}{82582}Tohle jeho osobnost|nemùe dlouho vydret.
{82717}{82764}U to nevydrím.
{82782}{82911}Nevydrím to.|Nevydrím to.
{82918}{83003}Nevydrím to.|Nevydrím to.
{83015}{83046}U je to lepší?
{83113}{83173}Byl jsi tu celou dobu,|Kaoru?
{83748}{83841}Graf solenoidu je obrácenı!|Jeho bariéra osobnosti slábne!
{83848}{83898}AT pole dosahuje èervené zóny!
{83916}{83967}S plodem ivota vlastnìnım Andìli...
{83984}{84029}a plodem moudrosti vlastnìnım lidmi...
{84044}{84186}se Eva 01, s obìma ve svıch rukou,|stává Bohem.
{84215}{84267}Nyní se zdroj všech duší,
{84269}{84352}Strom ivota,|znovu formuje.
{84355}{84479}Stane se Noemovou archou, která spasí|lidstvo pøed vakuem z Tøetího Úderu?
{84482}{84546}Nebo se stane démonem,|kterı nás všechny znièí?
{84559}{84630}Osud lidstva je v rukou|Ikariho syna.
{84637}{84703}Povìz,|dìlali jsme správnou vìc?
{84711}{84738}Jak to mám vìdìt?
{84843}{84921}Tahle Rei je tvé srdce.
{84937}{85006}Zosobòuje tvé nadìje a sny.
{85022}{85063}Po èem teï touíš?
{85683}{85711}To je...
{85741}{85819}To je úplnì jako v dobì,|kdy jsem zaèal hrát na èelo.
{85826}{85859}Myslel jsem,|e kdy tam pùjdu,
{85880}{85939}najdu to,|co hledám.
{85962}{85999}Pojï si s námi hrát,|Shinji!
{86004}{86072}Postavíme si píseènı hrad!
{86475}{86504}Hele, mamka je tu!
{86507}{86531}Musíme u jít domù!
{86542}{86573}Ahoj!
{86578}{86610}Mami!
{86651}{86674}Mami!
{89280}{89319}U dost!
{89326}{89389}Lezeš mi na nervy,|jen co tì vidím!
{89396}{89427}Protoe jsem úplnì jako ty?
{89430}{89453}Mamá!
{89468}{89499}Mamá.
{89504}{89523}Mamá?
{89532}{89622}Take nakonec nemohu bıt|Shinjimu matkou.
{89657}{89706}Mmmm,|pojïme na to.
{89720}{89814}U zase? Myslel jsem,|e se máš dnes sejít s kámoškou.
{89829}{89935}Aha, s Ritsuko.|Neboj, mám spoustu èasu.
{89944}{90020}U tu jsme zavøení celı tıden.
{90023}{90099}Jo, ale myslím,|e u mi to zaèíná jít.
{90101}{90145}No tak, pojï.
{90250}{90365}Asi dìlám takovéhle vìci,
{90368}{90426}abych prokázala vlastní existenci.
{90436}{90471}To je pitomost!
{90474}{90555}Jsou to jen dva osamìlí dospìlí,|co si líou rány.
{90557}{90619}Je pøíjemné cítit se potøebnı,|tøebae jen fyzicky.
{90622}{90698}Cítím se potøebná|a proto jsem šastná.
{90700}{90755}Je to jednoduchı zpùsob,|jak pøesvìdèit sám sebe,
{90758}{90803}e za nìco stojíš.
{90832}{90912}Dìlá Misato skuteènì|takové vìci?
{90920}{90986}Ano, to jsem také já.
{91006}{91083}Mé já, které existuje,|kdy se dvì srdce spojí v jedno.
{91086}{91132}To já,|které Shinji nikdy neznal.
{91134}{91187}Realita mùe bıt bolestivá,
{91190}{91271}ale musíš se nauèit|ji akceptovat.
{91284}{91380}To znamená, e a vyrostu,|budu dìlat stejné vìci jako Misato?
{91416}{91462}Chceš mì políbit?
{91464}{91484}Nedìlej to!
{91487}{91515}Proè? Máš strach?
{91526}{91568}To není nic pro dìti.
{91577}{91609}Tak jdeme na to.
{91657}{91705}Nièemu nerozumíš!
{91709}{91747}Jen tu stojíš jak pitomec.
{91758}{91784}Já tomu rozumím...
{91792}{91837}Asi tìko,|ty pitomèe!
{91847}{91907}Myslíš si,|e mì znáš?
{91920}{91979}Myslíš,|e mi nìkdy mùeš pomoct?
{92003}{92062}To je ta tvá|sobecká povaha!
{92069}{92108}Ty to nikdy nepochopíš!!
{92147}{92226}Jak chceš abych ti porozumìl,|kdy nikdy nic neøekneš?
{92234}{92296}Nemluvíš se mnou a myslíš si,|e ti budu rozumìt.
{92299}{92322}To je nemoné!
{92336}{92379}Ikari, zkoušel jsi nìkdy|opravdu porozumìt?
{92401}{92424}Samozøejmì, e jsem chtìl.
{92428}{92459}Pitomèe!
{92462}{92547}Ale já vím co se mnou chceš dìlat...
{92550}{92609}Proè se nesnaíš to udìlat?|Chci tì vidìt taky se snait.
{92612}{92656}Budu se na tebe odtud dívat.
{92677}{92802}Kdy tì nemùu mít pro sebe,|nepotøebuju tì!
{92819}{92862}Tak se ke mì zkus|chovat líp.
{92876}{92918}Jsme na tebe hodné.
{92920}{92937}Lete!
{92952}{92991}Všechny lete svım úsmìvem!
{92994}{93043}Schválnì mluvíte dvojznaènì!
{93059}{93118}Protoe pravda jenom ubliuje ostatním...
{93124}{93177}to je hoøká stránka všeho.
{93184}{93252}Ale ta nejistota mì akorát|pùsobí vìtší bolest.
{93255}{93286}To je jen vımluva.
{93288}{93332}Mám vánì strach.
{93337}{93399}Protoe nevím,|kdy mì ostatní pøestanou potøebovat.
{93402}{93497}Cítím se tak trapnì a nejistì.|Prosím mluvte se mnou!
{93503}{93536}Neopouštìjte mì!
{93544}{93571}Starejte se o mì!
{93868}{93959}Chci ti pomoct|a zùstat s tebou.
{93962}{94017}Tak nic nedìlej.
{94020}{94053}Nechoï u ke mì.
{94070}{94136}Jenom mi ubliuješ.
{94140}{94178}Asuko pomoz mi!
{94190}{94265}Jen ty mi mùeš pomoct!
{94278}{94304}Leš.
{94355}{94409}Staèí ti kdokoliv.|Je ti jedno, kdo to je!
{94412}{94454}Máš strach|z Misato a Rei.
{94457}{94501}Máš strach taky|z táty a mámy.
{94504}{94557}A teï utíkáš za mnou,
{94560}{94616}protoe je to nejjednodušší monost,|jak se sám nezranit!
{94619}{94656}Potøebuju,|abys mi pomohla!
{94659}{94713}Nikdy jsi nemiloval|ani sám sebe!
{94771}{94889}Jsi jediné, co máš a ani to|jsi se nenauèil milovat.
{95028}{95066}Ubohé...
{95156}{95190}Pomoz mi...
{95237}{95380}Pomozte mi nìkdo.
{95424}{95450}Pomozte mi.
{95489}{95515}Pomozte mi.
{95540}{95592}Prosím pomozte mi!
{95608}{95639}Neopouštìjte mì!
{95644}{95678}Pøestaòte mì ignorovat!
{95688}{95733}Prosím nezabíjejte mì!
{95892}{95925}Ne.
{96748}{96750}Epizoda 1: Andìlé dorazili
{96750}{96752}Epizoda 2: Neznámı strop
{96752}{96754}Epizoda 3: Telefon, kterı nezvoní
{96754}{96756}Epizoda 4: Déš, po útìku pryè
{96756}{96758}Epizoda 5: Za srdcem Rei
{96758}{96760}Epizoda 6: Nové mìsto Tokyo 3
{96760}{96763}Epizoda 7: Vìci stvoøené èlovìkem
{96763}{96764}Epizoda 8: Asuka dorazila
{96764}{96767}Epizoda 9: S jedním akordem v tìle
{96767}{96768}Epizoda 10: Potápìè v lávì
{96768}{96771}Epizoda 11: V zastaveném tichu
{96771}{96772}Epizoda 12: Hodnota zázrakù
{96772}{96775}Epizoda 13: Invaze Andìla
{96775}{96776}Epizoda 14: SEELE, trùn duší
{96776}{96779}Epizoda 15: Li a ticho
{96779}{96780}Epizoda 16: Nemocí k smrti a...
{96780}{96783}Epizoda 17: Ètvrté dítì
{96783}{96784}Epizoda 18: Rozsudek nad ivotem
{96784}{96786}Epizoda 19: Boj muù
{96786}{96788}Epizoda 20: Obrys srdce, obrys èlovìka
{96788}{96791}Epizoda 21: Zrození NERVu
{96791}{96792}Epizoda 22: Buï alespoò lidskı
{96792}{96795}Epizoda 23: Slza
{96795}{96799}Epizoda 24: Poslední posel
{96799}{96800}Epizoda 25: Konec svìta
{96800}{96803}Epizoda 26: V srdci svìta
{96820}{96855}Nikdo mi nerozumí.
{96860}{96902}Nikdy jsi nièemu nerozumìl.
{96906}{96960}Myslel jsem,|e to mìl bıt perfektní svìt,
{96963}{96994}bez bolesti a nejistoty.
{96996}{97083}To protoe sis myslel,|e to tak cítí kadı...
{97086}{97158}Zradila jsi mì!|Zradila jsi mé pocity!
{97165}{97211}Nerozumìl jsi|od samého zaèátku.
{97213}{97267}Vìøil jsi jen tomu,|èemu jsi chtìl.
{97270}{97352}Nikdo mì nechce.|Take mùou všichni zemøít!
{97355}{97411}Tak ale k èemu|je tvá ruka?
{97419}{97485}Všem je jedno,|jestli existuju nebo ne.
{97490}{97555}Nic se nezmìní,|take mùou všichni zemøít!
{97557}{97632}Ale k èemu je|pak tvé srdce?
{97636}{97685}Bylo by lepší,|kdybych nikdy nebyl.
{97688}{97726}Mìl bych prostì|zemøít taky.
{97734}{97780}Tak proè jsi tady?
{97804}{97846}Mám tady zùstat?
{97884}{97907}(ticho)
{98047}{98111}Pilotovy reakce se blíí|absolutní nule!
{98122}{98195}Sériové Evy a Geofront|se blíí k vrstvì E...
{98197}{98223}a stále stoupají.
{98332}{98396}Momentální vıška je|220 000 km.
{98399}{98434}Vstupují do vrstvy F.
{98436}{98468}Všechny Evy stále funkèní!
{98478}{98584}Lilitino anti-AT pole se stále šíøí!|Zaèíná se zhmotòovat!
{99144}{99202}Anti-AT pole|pøekroèilo limit!
{99208}{99232}Pokud to bude tak pokraèovat,
{99234}{99307}ivé bytosti si nebudou moci|uchovat svoji jednotlivou formu!
{99478}{99511}Gufova Komnata|je otevøená.
{99526}{99603}Dveøe zaèátku|i konce svìta...
{99622}{99671}se pøece jen otevøely.
{99834}{99903}Tento svìt pøetéká alem.
{99914}{99975}Jeho lidé se|topí v prázdnotì.
{99996}{100063}Osamìlost naplòuje|jejich srdce.
{100367}{100451}Ikari, u jsi koneènì|taky vidìl Yui?
{100529}{100634}AT pole...|AT pole všech lidí mizí.
{100636}{100719}Je to odpovìï?|Je to to, co jsem hledala?
{100808}{100835}Sleèno Ritsuko?
{100863}{100887}Mayo.
{100926}{100988}Sleèno Ritsuko...Sleèno Ritsuko!
{100991}{101014}Ritsuko!!
{101073}{101146}Zaèátek a konec|jsou jeden a tentı.
{101157}{101233}Ano, se svìtem je|vše v poøádku.
{101403}{101500}Èekal jsem na tuto|chvíli tak dlouho.
{101516}{101579}Koneènì mohu bıt|zase s tebou, Yui.
{101606}{101699}Kdy je se mnou Shinji,|dokáu mu jen ubliovat.
{101726}{101786}Bylo lepší,|kdy jsem nedìlal nic.
{101807}{101842}Bál jsi se Shinjiho,|e?
{101865}{101932}Nevìøil jsem,|e mì mohou ostatní milovat.
{101960}{102004}Nezaslouím si to.
{102020}{102068}Jenom jsi utíkal|pøed skuteèností.
{102087}{102175}Odmítal jsi ostatní,|aby ti nemohli ublíit.
{102190}{102290}Bál jsi se neviditelnıch pout,|která lidé vytváøejí.
{102296}{102386}Ze strachu jsi prostì uzavøel|své srdce pøed ostatními.
{102411}{102458}Proto je tohle|mùj trest?
{102474}{102535}Promiò,|Shinji.
{104944}{104999}Ayanami Rei.
{105094}{105117}Nenávidím tì.
{105120}{105183}U mi nevolej.
{105185}{105241}Otravuješ mì.
{105244}{105280}Paneboe,|ty jsi neodbytnı.
{105283}{105306}Sbohem!
{105308}{105402}Pøeji si,|abys odešel.
{105404}{105481}Nechci bıt|znovu s tebou.
{105484}{105556}Buïme jen pøátelé.
{105559}{105624}Znám tì vùbec?
{105627}{105674}Podívej se na sebe!
{105676}{105738}U mi vánì|lezeš na nervy.
{105740}{105805}Kdo sakra jsi?
{105808}{105881}Je mi jedno jestli|iješ nebo ne.
{105884}{105971}Nemám tì ráda 'takhle'.
{105974}{106027}Nechci tìve svém ivotì.
{106030}{106097}Abych øekl pravdu,|lezeš mi na nervy.
{106100}{106148}Pøestaò mì pronásledovat.
{106151}{106206}U to nemùu dìlat.
{106208}{106267}Rozejdìme se.
{106269}{106314}U tì nepotøebuju.
{106316}{106371}Kdo by taky chtìl|chodit s tebou?
{106373}{106439}Nepotøebuju tì|a nikdy døív jsem nepotøebovala.
{106442}{106482}Jdi pryè.
{106495}{106518}Blbeèku.
{106603}{106698}Pokud je to tak bolestivé,|vdy to mùeš zastavit.
{106712}{106806}Jestli se ti to nelíbí,|mùeš utéct pryè.
{106831}{106877}Chceš mít pohodlí?
{106883}{106934}Chceš cítit mír v duši?
{106944}{106997}Chceš se se mnou spojit?
{107011}{107098}A spojit naše tìla|i duše v jedno?
{107105}{107216}Radši umøu ne to|udìlat s tebou!
{108774}{108797}Hej...
{108804}{108829}Co je?
{108887}{108952}Co jsou to sny?
{108960}{108986}Sny?
{109012}{109071}Ano, sny.
{109636}{109698}[Je to dobrı pocit?]
{109722}{109749}Nerozumím...
{109781}{109841}Nerozumím realitì...
{109860}{109948}Nemùeš postavit most pøes|propast mezi tvou pravdou...
{109951}{110005}a realitou ostatních.
{110019}{110099}Kde mùu najít štìstí?
{110120}{110208}Štìstí se nalézá|pouze ve snech.
{110226}{110323}Proto to není realita - svìt,|kde nikdo neexistuje.
{110327}{110372}Ano, je to jen sen.
{110380}{110443}A já tam tedy|také neexistuji.
{110445}{110556}Ten tvùj vymyšlenı svìt je|jen pokus, jak zmìnit realitu.
{110559}{110591}A to je špatné?
{110593}{110675}Vyuíval jsi fantazii,|abys unikl realitì.
{110686}{110743}Proè nemùu snít o tom,|e jsem sám?
{110753}{110797}To by nebyl sen.
{110805}{110856}Jen náhraka reality.
{111284}{111351}Take...|kde je mùj sen?
{111359}{111419}Je to pokraèování reality.
{111444}{111499}Ale kde je má realita?
{111530}{111582}Na konci tvého snu.
{111584}{111588}"Chcípni, Anno!"
{112204}{112235}Ayanami.
{112268}{112301}Kde to jsme?
{112304}{112371}Tohle je moøe LCL.
{112373}{112428}Prapùvodní tekutina ivota.
{112450}{112548}Je to svìt bez AT polí,|kde individuální formy neexistují.
{112564}{112603}Nejasnı svìt...
{112605}{112697}kde nemùeš urèit,|kde konèíš a ostatní zaèínají.
{112712}{112772}Jsi všude v tomto svìtì...
{112775}{112842}a zároveò nikde,|vše zároveò.
{112878}{112908}Je to smrt?
{112926}{112997}Vùbec ne. Tohle je svìt,|kde jsme všichni jako jedna bytost.
{113040}{113128}Tohle je svìt,|kterı sis pøál.
{113303}{113383}Ale...to není správné.|Nemyslím, e je to ono...
{113407}{113468}Pokud touíš,|aby ostatní znovu existovali,
{113471}{113550}zdi jejich srdcí|je znovu rozdìlí.
{113561}{113625}Znovu budou cítit strach.
{113667}{113690}To nevadí.
{113892}{113928}Díky.
{114047}{114127}Kdy jsem existoval v té realitì,|cítil jsem jen bolest.
{114156}{114223}A tak jsem myslel,|e je v poøádku utíkat od reality.
{114247}{114342}Ale ani tam, kam jsem utíkal,|nebylo nic dobrého.
{114344}{114484}Protoe jsem tam neexistoval|a tudí neexistoval nikdo.
{114515}{114619}Nevadí, e bude AT pole|znovu zraòovat tebe i ostatní?
{114641}{114664}Nevadí.
{114682}{114760}Ale co jste vy dva|uvnitø mého srdce?
{114784}{114812}Jsme nadìje...
{114815}{114928}v to, e budou nìkdy lidé|schopni porozumìt jeden druhému.
{114931}{114992}A jsme dvì slova,|"Miluji tì".
{115000}{115046}Ale to je jen pøetváøka.
{115061}{115104}Sobecká víra.
{115128}{115170}Jako nìjaká motlitba.
{115185}{115227}To nemùe trvat navìky.
{115248}{115367}Nakonec budu jednoho dne zrazen|a ta víra mì opustí.
{115389}{115462}Ale...|chci je znovu vidìt,
{115472}{115570}protoe vím, e tenkrát byly|mé pocity skuteèné.
{117121}{117232}Realita existuje na neznámém místì|a sny uvnitø ní.
{117235}{117317}A pravda je ve tvém srdci.
{117338}{117444}Je to srdce,|co vytváøí lidskou podobu.
{117469}{117612}A nové pøedstavy zmìní|tuto podobu i srdce samotná.
{117638}{117746}Síla pøedstavivosti je klíèem k|monosti vytvoøit si svoji budoucnost,
{117752}{117828}a vytvoøit svùj vlastní|tok èasu.
{117859}{117947}Ale pokud lidé nejednají|ze své svobodné vùle,
{117952}{117995}tak se vùbec nic nezmìní.
{117998}{118114}Take musíš získat zpìt svou|ztracenou formu svou vlastní vùlí.
{118116}{118187}I kdy riskuješ,|e tvá slova budou vyøèena naprázdno...
{118190}{118260}nebo se nebudou shodovat|se slovy ostatních.
{118801}{118850}Všichni se mohou vrátit|do své lidské formy...
{118853}{118975}pokud si dokáí pøedstavit sami|sebe svım vlastním srdcem.
{119117}{119153}Nemìj obavy.
{119172}{119279}Kadá ivá bytost má|sílu bıt oivena...
{119282}{119342}a má také vùli|v ití pokraèovat.
{119362}{119476}Ráj mùe bı kdekoliv,|pokud máš vùli ít.
{119482}{119544}Pøeci jen,|jsi poøád naivu,
{119622}{119713}take máš vdy|šanci bıt štastnı!
{119974}{120054}Dokud Slunce, Mìsíc a Zemì existují,
{120112}{120160}vše bude v poøádku.
{120737}{120774}Budeš v poøádku?
{120844}{120945}Stále nevím,|kde najdu štìstí.
{120962}{121039}Stále budu pøemıšlet,|proè jsem tu,
{121041}{121139}a proè bylo èi nebylo dobøe,|e jsem se vrátil.
{121175}{121269}Ale to jen opakuju|samozøejnou vìc stále dokola.
{121284}{121332}Já jsem já.
{121423}{121455}Ale mami...
{121501}{121551}Co budeš dìlat ty,|mami?
{121652}{121713}Kdy lidé vytvoøili Evu,
{121716}{121805}pokoušeli jsme se vytvoøit|napodobeninu boha?
{121808}{121893}Ano. Lidé mohou ít na|této planetì pouze smrtelnì,
{121908}{121978}ale Eva mùe ít vìènì...
{121985}{122061}spolu s lidskou duší ijící|uvnitø jejího tìla.
{122084}{122136}I po 5 miliardách let,
{122139}{122263}a Zemì, Mìsíc a Slunce zmizí,
{122287}{122339}Eva bude stále existovat.
{122358}{122399}Bude velmi osamìlá,
{122402}{122455}ale dokud alespoò|jedna osoba ije,
{122460}{122554}bude to vìènı dùkaz toho,|e nìkdy lidstvo vùbec existovalo.
{122598}{122656}Sbohem, Mami.
{122688}{122780}Ještì nìco: Potøebuji tì.
{127096}{127137}To je nechutnı.
{127140}{127231}Konec
{127245}{127320}Pøeklad :|pej@centrum.cz & radvit@tiscali.cz
