{48}{144}Pøeložila Rosie182
{671}{767}Psychic Academy Aura Banshou - epizoda 3
{3323}{3453}To bylo trochu hloupé, takhle spadnout.
{3548}{3587}Co se dìje?
{3599}{3632}Ta holka...
{3740}{3776}Dìlá ti starosti?
{3798}{3824}Ne...
{3848}{3884}Její kód aury je Myuu.
{3920}{3956}Myuu?
{3968}{4004}Ano.
{4004}{4040}Je také v naší tøídì víš.
{4052}{4112}Její speciální schopnost je "Skok".
{4124}{4184}Ale vìtšinou není ve tøídì
{4191}{4256}a není pøíliš spoleèenská.
{4263}{4364}Je to pravdìpodobnì tìžké, pøijmout ten pocit, že jsi daleko od domova.
{4376}{4400}Ai-kun!
{4543}{4651}Epizoda 3: Myuu
{4663}{4699}Tady.
{4735}{4771}Tvùj studentský prùkaz.
{4774}{4855}Ztratila jsi to dneska ráno.
{4867}{4939}Chápu, promiò že ses musel obtìžovat.
{4963}{5035}Um... totiž...
{5071}{5095}Co je?
{5095}{5131}Ještì jsi neskonèil?
{5167}{5263}To dítì, které jsi zachránila... teï už je to v poøádku.
{5335}{5419}Je možné že... ty opravdu nevíš co se stalo?
{5491}{5538}To je trochu pøekvapivé.
{5538}{5634}Takže jsi kolem toho opravdu jen tak blbì nekecal?
{5634}{5682}O èem to mluvíš?
{5706}{5826}<i>Já to dítì nezachránila. Byls to ty.<i>
{5826}{5850}Co?!
{5910}{6054}Pøedtím než jsem dnes ráno skoèila, jsi to vlastníma rukama zpomalil.
{6061}{6090}Zpomalil...
{6138}{6234}Jen díky tomu, že jsi to na malý okamžik zastavil, se tomu dítìti nic nestalo.
{6246}{6342}Byla to tvoje aura, co na nìj pùsobilo.
{6354}{6390}To..to není možné.
{6402}{6438}Pøesnì, jak jsem si myslel.
{6438}{6486}C-co si o tom myslíš?
{6486}{6557}Vìøím, že má pravdu.
{6569}{6617}T-takže jinými slovy...
{6617}{6689}To dítì zachránila moje aura?!!
{6689}{6725}Nemožné!!
{6725}{6761}To není nemožné!
{6809}{6869}Co je to s tím divnì vypadajícím králíkem?
{6881}{6953}Ï...Di...Divnì vypadajícím?!
{7013}{7109}Ty jsi opravdu jiný...
{7157}{7217}Když se smìje, je tak roztomilá...
{7588}{7624}<i>Ai-kun...<i>
{7624}{7696}<i>O èem sis to s Myuu povídal?<i>
{7696}{7720}Je možné že...?!
{7742}{7768}Ne!
{7790}{7864}Na co to myslím...
{7864}{7960}Sotva pøišel na Psychologickou Akademii...
{7972}{8044}Tak jak by mohl...
{8116}{8212}<i>Mìla jsem se ho na to zeptat už døív...<i>
{8224}{8296}<i>Zajímalo by mì, co dìlá zrovna teï...<i>
{8344}{8356}Sáro?
{8392}{8428}Myuu!
{8440}{8488}Proè jsi sem tak náhle vpadla?
{8499}{8547}Koupeš se už dlouho, pospìš si.
{8559}{8607}U-už to vím.
{8631}{8691}Dobøe, to je všechno.
{8787}{8931}Proè musíme být nìkdy já a Myuu spolubydlící...
{9003}{9039}Pøedpokládám že už to zaèalo.
{9051}{9087}Mùj studentský život.
{9099}{9159}Je docela roztomilá nemyslíš?
{9183}{9243}Eh? Koho tím myslíš?
{9243}{9303}Orinu-chan pøece!
{9327}{9459}Mimochodem "Mistøe", jak dlouho mì míníš takhle doprovázet?
{9459}{9602}Nedìlej si s tím starosti. Èeká tì dlouhá cesta, než se staneš skvìlým Mistrem aury.
{9626}{9722}Nikdo se nikdy neptal! Na takovou vìc.
{9962}{10010}C-co to dìláš?
{10022}{10070}Trénuju výdrž.
{10065}{10190}Když tohle dìlám, moje aura se pak stává silnìjší.
{10370}{10501}Psychologická Akademie má pokojový systém a tohle je mùj spolubydlící.
{10506}{10597}Jeho kód aury je Teruha-Shanaha-Kuga.
{10633}{10789}Je to trošku divné, ale mùj studentský život definitivnì zaèal.
{11029}{11101}No tak, co tam vidíš tentokrát?
{11137}{11173}Osudovou lásku.
{11185}{11221}Kdo s kým?
{11221}{11281}Ten nový student.
{11317}{11353}Ai-kun...
{11449}{11485}No?
{11520}{11556}Myuu!
{11561}{11592}Myuu?!
{11592}{11664}Oh! Myuu a ten kluk...
{11664}{11736}Jejich souboj aur je úžasný!
{11736}{11772}U-úžasný?
{11784}{11856}Je to jaksi...100%!
{11892}{11928}Jakto?!
{11930}{12024}Jakto? Nevím, je to jen to, co jsem vidìla...
{12024}{12072}Tak tos musela vidìt špatnì!
{12132}{12180}Když to øíkáš...
{12324}{12396}<i>100%....100%...!<i>
{12408}{12444}Co je?
{12451}{12515}Mám snad nìco na oblièeji?
{12551}{12587}Dobré ráno, Orino.
{12611}{12647}A..Ai-kun...
{12659}{12719}Oh, dobré ráno, Myuu.
{12731}{12839}Ai-kun, promiò, ale potøebuju s tebou na chvilku mluvit.
{12911}{12971}Eh? Vèera?
{12966}{12995}N-no víš...
{12995}{13115}Jen jsem pøemýšlela, o èem jste vy dva mluvili...
{13127}{13211}Aha, jen jsem našel nìco, co Myuu nìkdy døív ztratila
{13213}{13259}tak jsem jí to chtìl vrátit.
{13259}{13307}Opravdu? A to je všechno?
{13343}{13391}Jsi si jistý?
{13415}{13475}.... Co se dìje?
{13534}{13594}A-ale to nic! Opravdu!
{13618}{13714}No... tak už bysme mìli jít zpátky do tøídy, první hodina skoro zaèíná.
{13810}{13846}Poslouchejte!
{13858}{13930}V tomto pøípadì dva svatí obìtují jídlo Bohùm
{13932}{13978}a skrze to se v nich usídlila aura.
{13980}{14050}A teï to nezapomeòte!
{14062}{14146}Takže! Co je aura obìti?
{14148}{14242}Zaprvé, musíte být schopni to vidìt. Aura je na stejné cestì jako...
{14369}{14458}<i>Budu na tebe èekat po škole - Myuu.<i>
{14458}{14529}Mohlo by to být...
{14577}{14673}Eh-ya, to nic.
{14829}{14889}Milostný dopis, že jo?
{14901}{14961}Mylíš se!
{14961}{14985}Co prosím?!
{15023}{15064}Shiomi!
{15067}{15105}V èem se jako mýlím?
{15107}{15177}Ne, já to tak nemyslel! V nièem se nemýlíte!
{15405}{15512}Mohlo by.. tohle být... vyznání?
{15560}{15584}Shiomi-kun.
{15692}{15752}P-Poèkej.
{15755}{15872}Od doby co jsem tì potkala na tebe stále myslím.
{16100}{16184}Ne-nevzala jsi to trochu hopem?!
{16208}{16280}Nikdo nás tu nenajde...
{16460}{16519}Myslím, že je to jedinì pro moje dobro.
{16519}{16591}Zase se na mì takhle nalepit... ale nedìlej si o mì starosti!
{16975}{17023}Eh! M-Myuu?
{17035}{17095}Shiomi-kun, že?
{17167}{17311}Od doby co jsem tì potkala pøemýšlím o mnoha vìcech.
{17313}{17407}Proè? Proè nemùžu vidìt tvojí auru?
{17431}{17502}Chci znát tvojí pravou auru!
{17550}{17634}Chci s tebou bojovat, v opravdovém souboji.
{17666}{17730}O-Opravdovém souboji?!
{17754}{17802}Myslíš jako...duel?!
{17946}{17994}Budu èekat...
