{48}{144}Pøeložila Rosie182
{671}{767}Psychic Academy Aura Banshou - epizoda 4
{3560}{3596}Eh! M-Myuu?
{3608}{3668}Shiomi-kun, že?
{3740}{3860}Od doby co jsem tì potkala pøemýšlím o mnoha vìcech.
{3882}{3980}Proè? Proè nemùžu vidìt tvojí auru?
{3982}{4064}Chci znát tvojí pravou auru!
{4100}{4196}Chci s tebou bojovat, v opravdovém souboji.
{4220}{4292}O-Opravdovém souboji?!
{4294}{4352}Myslíš jako...duel?!
{4436}{4484}Po-Poèkej chvilku!
{4495}{4603}Nemám tak velkou sílu jako ty!
{4615}{4651}Zaèínám!
{4711}{4747}Co-Cože?!
{4771}{4831}Moje speciální aura je...
{4843}{4879}Planoucí
{4891}{4927}RÙŽE!
{4999}{5107}Epizoda 4: Souboj aur
{5203}{5251}Dívej se pozornì.
{5275}{5347}Vytvoøit nepøetržitý tok aury je dùležité.
{5349}{5407}T-to nezvládnu... co mám dìlat?
{5419}{5479}To nevadí, prostì se dívej!
{5802}{5838}Vy-Vyhnul se tomu?
{5898}{5946}To je správné!
{5948}{6018}A teï se dívej na Myuuinu auru.
{6354}{6390}Vi-Vidím ji!
{6394}{6430}Jakou má barvu?
{6433}{6497}Koneènì ji vidím... je zelená.
{6507}{6545}Tak to si radìji dej pozor!
{6548}{6617}V tomhle stádiu Myuuina síla brzy vypálí!
{6622}{6661}T-To ne!
{6665}{6749}Barva aury ukazuje koncentraci jejího majitele.
{6756}{6893}Když je barva zelená, signalizuje to, že síla je už neudržitelná a má mnohem vìtší efekt.
{6953}{7013}Ai! Dívej se poøádnì!
{7157}{7181}Nemožné...
{7481}{7528}Hej! Uhni!
{7576}{7612}Á, pálí!
{7768}{7804}Utíkej!
{8068}{8128}Má ochranu pøed mojí aurou?
{8152}{8200}Dobrá práce, Ai.
{8262}{8286}Tak dobøe!
{8344}{8368}Z...Zmizela!
{8370}{8404}Za tebou!
{8859}{8883}Proè?
{8895}{8955}Proè jsi uhýbal?
{8967}{9096}Øíkal jsem ti pøece, že nemám takovou sílu jako ty.
{9135}{9207}Ale mìl jsi ochranu proti mé auøe.
{9214}{9279}To-To bylo jenom štìstí!
{9363}{9447}Nerozumím tomu. Co to s tebou jenom je?
{9734}{9806}O-Opravdu nedokážu vidìt tvou auru.
{10094}{10118}Ai-kun!
{10130}{10166}O-Orina?
{10645}{10693}Proè tohle dìláš?
{10705}{10789}Ai-kun jsem sotva pøišel!
{10825}{10885}Holèièí rvaèka, holèièí rvaèka!
{10897}{10933}Sáro?
{10969}{11005}Klíè.
{11007}{11046}Klíè?
{11048}{11101}Klíè od našeho pokoje, ty ho snad nemáš?
{11125}{11173}Ah, ano.
{11206}{11230}Shiomi-kun?
{11233}{11293}Nìkdy si dáme zase souboj.
{11520}{11556}Myuu...
{11748}{11772}Ai-kun!
{11820}{11844}Orino...
{11964}{12024}Nehýbej se, jsi zranìný!
{12204}{12396}<i>lubella appa aberuka, sabba lendus buran len<i>
{12587}{12623}Léèivá aura...
{12626}{12671}Léèivá aura?
{12695}{12863}Proslulý kód aury, tahle dívka je schopná léèit skrze svou auru.
{13091}{13139}V-Víly?
{13427}{13475}Eh! Studí!
{13642}{13714}To zranìní... kam se podìlo?
{13762}{13834}Hmm... Podívám se, podívám se...
{13882}{13990}Už to chápu. Tahle dívka má jako charakteristickou auru vodu.
{14062}{14146}Díky bohu, nebylo to nic vážného.
{14242}{14290}Dì-dìkuju ti.
{14326}{14434}Ale jsi... opravdu úžasná.
{14446}{14529}Vždycky jsem si to myslel. Už od doby co jsme byli dìti.
{14541}{14613}Po tom co jsem vidìl tvou zvláštní sílu...
{14757}{14781}Ai-kun...
{14817}{14889}To by bylo pìkný, kdybych mìl taky takovou sílu...
{14891}{14961}Bylo by to dobrý, kdybych byl silnìjší než jsem teï.
{14985}{15057}Dneska je to poprvé, co jsem o tom zaèal pøemýšlet.
{15059}{15177}Tím myslím, že mi jinak poøád pomáháš.
{15297}{15321}Ai-kun.
{15465}{15512}Nemusíš se stát silnìjším.
{15548}{15572}Orino...
{15608}{15704}Jsi dobrý takový jaký jsi.
{16424}{16495}Dívejte se pøíštì!
