{48}{144}Pøeložila Rosie182
{647}{719}Psychic Academy Aura Banshou - epizoda 7
{3093}{3141}Škola je koneènì u konce.
{3153}{3249}Už zbývá jen poslední vìc...
{3285}{3345}První období zkoušek zaèalo.
{3405}{3524}Epizoda 7: Zkouška I.
{3728}{3788}Ó, to vypadá že se opravdu snažíš.
{3824}{3932}Jdi pryè Mistøe! Jsem uprostøed zkoušky.
{3939}{4052}Co je tohle? Ty nerozumíš tìmhle otázkám?
{4054}{4196}Klást nìkomu na srdce aby se uèil, to vyžaduje respekt. Psát test bez tahákù to je...
{4208}{4256}Jo a ještì jsem zapomnìl!
{4258}{4304}Po tomhle následuje praktická zkouška.
{4316}{4385}Znovu tì nauèím víc o aurách.
{4412}{4436}Praktická zkouška...
{4484}{4531}Užijeme si zase spoustu zábavy!
{4551}{4567}Eh?
{4594}{4663}Buu-Beruka-Rasha-Puda-Arapa?
{4668}{4711}Prosím jdi ven.
{4716}{4747}Hej, co je?! Nech mì!
{4750}{4807}Já jsem Aiùv Mistr!
{4843}{4903}A teï už nevyrušuj, hmm?
{4905}{4929}Mistøe...
{5059}{5131}Dobøe, všichni se ztiší.
{5133}{5179}Ještì poøád píšete svojí zkoušku.
{5275}{5371}<i>Problém je praktická zkouška, která bude po tomhle...<i>
{5383}{5467}<i>Pokud jí neudìláte, propadnete.<i>
{5491}{5562}Tahle praktická zkouška, všichni víte co bude ne?
{5586}{5730}Jasnì, chceš trošku pocuchat to dìcko z tøídy B, že?
{5742}{5778}Mám s ním nevyøízený úèet.
{5790}{5874}Je to všechno vina toho Shiomiho Aie.
{5898}{5946}To mu neprojde.
{5946}{6054}V tom pøípadì, nebude ti vadit, když ti s tím pomùžu?
{6066}{6090}Pasu!
{6114}{6234}Ostatnì, je tam i nìkdo, koho absolutnì nemùžu vystát.
{6258}{6294}Ve stejné tøídì.
{6414}{6486}Míøíme k naší základnì pro praktickou zkoušku.
{6509}{6545}Je to velmi dùležitá zkouška,
{6548}{6641}takže se ujistìte, že jste na to správnì pøipraveni duševnì i fyzicky.
{6689}{6737}<i>Praktická zkouška trvá 2 dny.<i>
{6740}{6833}<i>Místo, kde se zkouška koná i podrobnosti o zkoušce jsou udržovány v tajnosti.<i>
{6857}{6881}<i>Ale...<i>
{6929}{6953}Na.
{6955}{6977}Eh?
{6979}{7025}Pøipravila jsem malý obìd.
{7061}{7097}A...Ale...
{7181}{7217}No tak.
{7219}{7277}Nemìl jsi pøece ani snídani.
{7337}{7397}Tady. Áááá....
{7409}{7423}Áá...
{7469}{7492}Je to dobré?
{7504}{7528}Ano.
{7540}{7576}To ráda slyším.
{7600}{7672}T-To je dobrý. Sním to sám.
{7900}{7996}E-Ehm, nekoukej tak na mì...
{8032}{8056}Pro-Promiò.
{8152}{8188}Co se dìje, Ai-kun?
{8260}{8320}Opravdu si nejsem jistý...
{8339}{8488}Už od chvíle co jsem tady se snažím i ve svém volném èase,
{8490}{8559}ale poøád si myslím, že nemám na to projít dál.
{8751}{8775}To bude v poøádku.
{8799}{8871}Urèitì projdeš.
{8890}{8931}M-Myslíš?
{8943}{8967}Urèitì.
{9099}{9159}Ha, rýžové zrnko!
{9195}{9231}<i>E-Ehm.<i>
{9267}{9375}Eh? Te-T-Teruda-kun, ty jsi vzhùru?
{9818}{9878}Tohle je místo praktických zkoušek?
{9881}{9926}Je to starý chrám...
{9938}{10022}Myslela jsem, že to bude nìco modernìjšího...
{10178}{10262}Ale vypadá to jako krásné a tiché místo, ne?
{10427}{10454}Co se dìje, Myuu?
{10490}{10537}Nic. To byla pravdìpodobnì jen moje pøedstavivost.
{10621}{10693}Jsem knìzem tohoto chrámu.
{10705}{10741}Jmenuji se Doushin.
{10753}{10873}Praktické zkoušky Psychologické akademie se znovu konají zde.
{10921}{10981}<i>Jakou silou disponuje.<i>
{11089}{11161}Právì teï... jeho aura...
{11197}{11233}Ji-Jistì!
{11437}{11473}<i>Køídla?<i>
{11485}{11501}Ai-kun?
{11520}{11544}Ai-kun?
{11556}{11580}Ai-kun!
{11585}{11600}Eh?
{11724}{11760}E-Em...
{11844}{11880}Co jsi vidìl?
{11916}{11940}Svýma oèima.
{11952}{12036}Chci slyšet, co jsi vidìl.
{12048}{12204}N-No, na vašich zádech jsem vidìl nìco jako... mnoho ptaèích per.
{12216}{12288}Cosi jako hoøící køídla...
{12336}{12396}To je forma Fénixe.
{12400}{12420}Eh?
{12451}{12475}Má snad na mysli...
{12480}{12503}Poslouchejte!
{12515}{12563}Zkouška zaèíná ve 4 hodiny.
{12575}{12623}Pozdní pøíchod nebude tolerován.
{12791}{12863}<i>Letošní praktická zkouška bude opravdu zajímavá.<i>
{13007}{13043}To bylo o fous!
{13307}{13343}Hej, Terudo-kun.
{13355}{13415}Co si myslíš o zítøejší zkoušce?
{13486}{13534}Ï-Dìje se nìco?!
{13606}{13630}Jsem v poøádku...
{13654}{13702}Tohle je kvùli...
{13707}{13731}...zítøejším zkouškám...
{13786}{13846}Co to bylo? Teï...
{14026}{14110}Zajímalo by mì co to mìlo být...
{14146}{14182}Možná jen moje pøedstavivost.
{14314}{14350}Z-Zase?!
{14613}{14688}Pøesnì jak jsem si myslel... Myuu.
{14733}{14769}Shiomi-kun...
{14791}{14815}Co se dìje?
{14829}{14937}J-Já jen... pøemýšlel jsem, jak krásná je hvìzdnatá obloha.
{14985}{15021}<i>Zase ticho.<i>
{15057}{15081}Proè...
{15083}{15105}Eh?
{15114}{15208}Proè jsem myslela na to, že bych tì tu mohla potkat...
{15237}{15273}Takže ty taky?
{15309}{15333}Shiomi-kun.
{15357}{15381}Citíš to?
{15419}{15496}Dech tohoto horského lesa.
{15512}{15536}Dech?
{15572}{15656}Cítím se tu velmi klidná.
{15692}{15740}Cítím se lehèí.
{15788}{15812}Chápeš?
{16028}{16076}Ne, to...
{16148}{16232}Z tìch lesù vychází velmi silná aura.
{16268}{16304}Teï když jsi to zmínila...
{16323}{16359}Nìjak to taky...
{16383}{16426}Trochu jakoby skrz mì...
{16448}{16591}Dech toho lesa... slabì ho slyším.
{17011}{17028}Ai!
{17066}{17107}Pojï sem. Rychle!
{17119}{17143}M-Mistøe!
{17179}{17215}Um...
{17239}{17287}Nìco si musím vyøídit.
{17622}{17646}Mistøe?
{17658}{17682}Pšššt!
{17706}{17766}Co se dìje, proè jsme tady?
{17836}{17874}Tady, tady!
{17910}{17946}Co je to tentokrát?
{17958}{18016}Neptej se a koukej!
{18186}{18210}O-Orina!
{18342}{18414}Budu èekat.
