{48}{192}Pøeložila Rosie182
{623}{731}Psychic Academy Aura Banshou - epizoda 12
{3405}{3441}Oèekávali jsme tì.
{3453}{3512}Takže tvoje domácí vìzení je už u konce.
{3656}{3752}Tak co ten nevyøízený úèet s tím novým studentem? Co je vùbec zaè?
{3776}{3872}Je to hroznej týpek. Používá netradièní triky.
{3884}{3951}Prosím, vyøiï ho.
{4028}{4076}Prvnì si ho chci sám ovìøit.
{4088}{4148}Protože mì zajímá, jestli je opravdu tak hrozný.
{4232}{4340}Epizoda 12: Faafa
{4495}{4531}Nemùžu uvìøit, že jdu pozdì!
{4543}{4627}Tak pohni! Orina bude bezpochyby naštvaná.
{4639}{4699}Nemusíš to tak rozmazávat.
{4711}{4855}Mimochodem, zaspal jsem kvùli tvému chrápání! Nemohl jsem vùbec spát!
{4858}{4884}Idiote!
{4886}{4958}Neptal jsem se tì na názor!
{4963}{4987}Možná... ne, ne,
{4989}{5047}králíci jsou od pøírody jemná stvoøení!
{5049}{5107}Taková lež o mém spaní je naprosto vylouèená!
{5073}{5107}Mùžeš to øíkat, ale...
{5299}{5335}Á, promiò.
{5347}{5371}Jsi v poøádku?
{5443}{5526}Jsi studentem Psychologické akademie, že?
{5538}{5598}Eh? Proè se ptáš?
{5646}{5718}Tušila jsem to! Mìla jsem pocit, že jsi.
{5730}{5850}Mìj se na pozoru, z téhle holky cítím silnou auru.
{5948}{5972}Perverzáku.
{6013}{6078}Zkoušel ses dívat na mojí auru.
{6102}{6126}Já...
{6294}{6318}Co se dìje?
{6330}{6366}Dala bych si zmrzku!
{6402}{6426}To snad ne...
{6428}{6462}Já bych si nìjakou dala!
{6474}{6521}No tak, no tak! Zmrzku!
{6533}{6593}Koupíš mi ji? Opravdu bych si dala!
{6665}{6689}Výborná.
{6713}{6797}Podívej, promiò, ale spìchám, takže už pùjdu.
{6917}{6941}Poèkej.
{6943}{6991}C-Co ještì?
{7001}{7049}Chci jít s tebou.
{7097}{7133}Se mnou, ale...
{7157}{7205}No tak, mùžu, že jo?
{7229}{7301}Hele, byl by to trochu problém, promiò, ale ne.
{7756}{7787}To je zlé.
{7804}{7883}Orina se asi naštvala a šla domù.
{7924}{7960}Hej, podívej támhle.
{7984}{8032}Nechceš jít do zábavního parku?
{8104}{8128}Pøestaò už.
{8284}{8351}Ty mì nesnášíš?
{8368}{8428}T-Tak to není!
{8430}{8464}To není vùbec tak, že bych tì nesnášel.
{8476}{8519}Opravdu?!
{8559}{8583}No víš...
{8595}{8619}Ai-kun!
{8655}{8679}Orino!
{8691}{8811}Tolik jsi se opozdil, že jsem se bála a šla jsem tì hledat.
{8823}{8919}Promiò, pár vìcí mì zdrželo.
{8991}{9027}Kdo je to?
{9039}{9171}N-No... je to trochu složitìjší na vysvìtlení, ale...
{9159}{9243}Už chápu! Šel jsi na rande, co?
{9255}{9351}Abych pravdu øekl, tak ano. Takže se omlouvám a...
{9363}{9435}Tak já pùjdu s vámi!
{10118}{10190}Hej! Pojïme se svézt všichni dohromady!
{10238}{10298}Co to s tou holkou je?
{10322}{10382}Nemám nejmenší tušení.
{10406}{10501}Takhle spolu nemùžeme být ani na chvíli sami.
{10513}{10537}Promiò.
{10561}{10597}Asi není jiná možnost,
{10600}{10681}je mi jí líto, ale mìli bychom se jí nìjak zbavit.
{10693}{10717}To nevyjde.
{10729}{10777}Proè ne? Teï by mohla být naše šance.
{10789}{10842}Co by mohla být vaše šance?
{10885}{10952}Ale ne... já... no...!
{10969}{11017}Skvìle! Tak pojïme na další atrakci!
{11137}{11185}Co chcete? To bolí.
{11221}{11317}Takhle mezi nás vrazit.
{11317}{11496}Nechámì tì jít, pokud nás budeš chvíli poslouchat, sleèinko.
{11520}{11544}Ta holka...
{11568}{11592}Má potíže.
{11664}{11712}Vy asi nemáte moc dùvtipu, co?
{11724}{11760}Co jsi to øekla?
{11772}{11832}Byla jsi to ty, kdo si zaèal!
{11856}{11880}Dumdee...
{11916}{11952}Mráz!
{12048}{12072}Co to je?
{12084}{12168}Hm? To je mrazivá aura!
{12180}{12197}Mrazivá?
{12587}{12611}Pøestaò!
{12623}{12647}Proè?
{12659}{12803}Proè? Když tohle dìláš obyèejným lidem, mùžou zemøít!
{12815}{12851}A to je špatné?
{12863}{12923}Tihle lidé jsou stejnì zlí.
{12935}{12971}Na tom nezáleží!
{12983}{13019}Jsou to lidé jako ty!
{13031}{13067}Oh...Vážnì?
{13079}{13187}A mimoto jsi do nich vrazila.
{13235}{13319}Hmm, to uznávám, takže...
{13331}{13355}Omlouvám se.
{13367}{13451}N-Ne, to je dobrý...
{13453}{13475}N-Nashle...
{13726}{13858}Hej, když umíš využívat svojí auru, možná bys taky...
{13894}{13942}Dnešek byl zábavný!
{14002}{14074}Opravdu jsem se nudila,
{14086}{14134}bez žádných pøátel...
{14218}{14278}Jmenuji se Faafa.
{14326}{14398}Tak, chcete být mými pøáteli?
{14410}{14458}Eh? Jistì.
{14482}{14505}Proè ne?
{14529}{14553}Dìkuju!
{14565}{14613}Super!
{14661}{14745}Tak zatím! Ai-kun, Orino-chan, ahoj!
{14757}{14817}Ah, ahoj!
{14841}{14865}Ai-kun.
{14877}{14937}Co to bylo za holku?
{14949}{15009}Taky by mì to zajímalo.
{15011}{15069}Ve škole jsem jí nikdy nevidìla.
{15129}{15177}<i>Každopádnì to byla divná holka.<i>
{15333}{15381}Hm? Pøichází.
{16088}{16136}Hej! Dávej pozor!
{16412}{16436}Ren-sama!
{16448}{16472}Èekali jsme na tebe!
{16915}{16987}Dívejte se pøíštì!
