{48}{144}Pøeloila Rosie182
{647}{736}Psychic Academy Aura Banshou - epizoda 15
{3105}{3153}Políbíme se?
{3261}{3321}T-Tohle asi není nejlepší nápad!
{3323}{3347}No tak!
{3357}{3381}Proè ne?
{3383}{3429}Ty mì nemáš rád?
{3431}{3477}Tak to není...
{3500}{3572}Ah! Take máš rád nìkoho jiného.
{3596}{3644}Jsi celı èervenı!
{3647}{3692}Je to Orina-chan, e?
{3728}{3764}Nebo se pletu?
{3776}{3836}Vidím tváø další dívky...
{3932}{4040}Epizoda 15: Zbìsilost
{4047}{4100}D-Další tváø...
{4124}{4208}Kdybych mohla vidìt auru toho èlovìka, vìdìla bych to jistì.
{4225}{4249}Shiomi-kun?
{4275}{4299}Myuu?!
{4328}{4376}Proè jsi sem pøišla?
{4484}{4543}Vrame se, Shiomi-kun.
{4603}{4699}To teda ne! Ai-kun bude se mnou!
{4855}{4879}A vùbec...
{4882}{4963}Jak si nás mohla tak rychle najít?
{4973}{5045}Nemáš takovou schopnost.
{5078}{5107}Prostì nìjak.
{5143}{5191}Hádám, e je to kvùli Shiomimu-kun.
{5215}{5311}Moná, e ho miluješ?
{5514}{5538}Hej, co to...
{5574}{5634}Co si myslíš, e dìláš mımu Ai-kunovi?!
{5646}{5778}Shiomi-kun, poèkej. Za okamik budeme zpìt.
{5838}{5898}To ti neprojde!
{5908}{5932}DUMDEE!
{5958}{5994}Shiomi-kun, dr se dál.
{6006}{6030}RÙE!
{6090}{6138}A co tohle!
{6234}{6258}Myuu!
{6593}{6677}Nenechám tì jen tak utéct.
{6905}{6965}Myuu, máš led...
{6977}{7001}Bolí to...
{7013}{7037}Myuu!
{7373}{7409}Pomohlo to.
{7421}{7469}D-Díky bohu...
{7936}{8056}N-Nemìla bys chodit venku takhle.
{8296}{8344}Co-Co je?
{8346}{8392}Po tom, jak jsem k tobì milı a vùbec.
{8418}{8440}Dìkuji ti...
{8583}{8643}<i>Proè se na lidi nedívá, kdy tohle øíká?<i>
{8691}{8763}Ehm... Shiomi-kun?
{8799}{8835}Co se dìje?
{8871}{8931}Vodu... Potøebuju se nìjaké napít...
{8955}{8979}Vodu?
{9243}{9279}Další láhev.
{9315}{9423}A... vdy kdy vyuíváš svou ohnivou auru, máš pak takovou ízeò?
{9590}{9662}Je to proto, e jsem jiná...
{9674}{9698}Jiná?
{9722}{9818}Pokud si nepospíšíme do školy, Faafa nás najde.
{9830}{9902}Myuu, vy dvì se znáte?
{9926}{10046}Obì jsme byli ve Vıvojovém centru aury.
{10058}{10118}Vıvojové centrum aury?
{10130}{10226}Breèívala tam kadı den.
{10274}{10346}To zpùsobilo, e má ve své auøe jeden nebezpeènı prvek.
{10370}{10394}Nebezpeènı prvek?
{10442}{10549}Pokud jí nìjaká z jejích emocí ovládne, její aura se stává zbìsilou.
{10585}{10669}Pokud se tak stane, nikdo jí nedokáe zastavit.
{10741}{10789}A ta emoce je...
{10837}{10873}Hlubokı smutek.
{11017}{11137}Ehm... Je moné, e ty a Faafa jste byly kdysi kamarádky?
{11149}{11209}Jen jsme byli obì tam.
{11269}{11293}Shiomi-kun.
{11341}{11413}Kdyby... ale jen kdyby...
{11425}{11520}jsem se nebyla schopná zastavit...
{11544}{11592}Zastavil bys mì prosím?
{11616}{11664}Za-Zastavit?
{11676}{11700}Co tím...
{11784}{11808}Ale nic.
{11868}{11928}Prosím, zapomeò na to, co jsem teï øekla.
{12216}{12240}Jsi v poøádku?
{12242}{12312}Vypadáš vyèerpanì.
{12336}{12432}Jsem v pohodì. Jen se musíme dostat zpátky do školy.
{12468}{12527}Tak mùeme jít pomaleji.
{12551}{12587}Škola je blízko.
{12611}{12659}Oh? Co to je?
{12683}{12755}Poøád se to vznáší pøímo nad námi.
{13091}{13115}Led?
{13127}{13223}Sakra, tohle je Faafina souèást aury.
{13225}{13271}Je to útvar, do kterého se mùe pøemístit.
{13295}{13391}U ví, kde jsme.
{13415}{13439}Mám vás!
{13558}{13582}Faafo.
{13606}{13702}U tì nenechám znovu uniknout, mùj Ai-kun.
{13726}{13798}Faafo, zkus se chovat trochu dospìleji.
{13801}{13906}Neple se do toho, nejlepší by bylo, kdybys teï ztichla.
{13930}{13954}Tumáš!
{14074}{14122}Jaká hrozná vìc...
{14230}{14350}Tak a teï mùeme jít a udìlat si malı spoleènı ráj.
{14352}{14446}Zbavím se kadého, kdo se nám pokusí stát v cestì.
{14505}{14541}Mùeš toho u nechat?
{14553}{14637}Nemysli poøád jen na sebe.
{14673}{14757}Ai-kun... to znamená, e mì nemáš rád?
{14760}{14841}Jo, nemám tì rád, kdy dìláš takovéhle hrozné vìci.
{14877}{14925}Nemáš rád...
{14961}{15009}Z-Zlobíš se?
{15033}{15129}Všichni... mì zaènou nenávidìt...
{15177}{15213}Uh... hej...
{15081}{15357}Faafo?
{15429}{15465}Je moné, e... ?!
{15500}{15584}Všechny nenávidím... Nenávidím!
{15740}{15824}To-Tohle je zbìsilost aury?
{15836}{15920}Sakra, co mám dìlat, abych jí zastavil?
{15932}{15968}Vypuklo to.
{15992}{16064}Musíme to nìjak zastavit.
{16076}{16112}Ale... Ale jak?
{16136}{16172}Tak to...
{16208}{16232}Nevím!
{16280}{16376}Musíme jí nìjak kompletnì zmrazit.
{16378}{16448}J-Jak to k èertu dokáeme?
{16594}{16639}<i>T-To je ono.<i>
{16642}{16687}<i>Pøedtím, Faafa øíkala...<i>
{16690}{16795}<i>Pokud zaène moje srdce bít trochu rychleji, Ren se probudí.<i>
{16831}{16867}Jestli je to pravda, tak...
{16879}{16915}Všechno nebo nic!
{17023}{17107}Omlouvám se za to, e jsem tì rozbreèel.
{17598}{17634}Co to k èertu dìláš?!
{17658}{17730}Nìco takovıho nemùu vystát!!!
{17766}{17826}Díky bohu...
{17922}{17994}<i>A tak byl problém vyøešen.<i>
{18018}{18042}<i>Ale...<i>
{18066}{18150}Ai-kun, kde jsi pøišel k tomu zranìní?
{18152}{18234}To jen... stalo se pár vìcí.
{18270}{18354}<i>Nemùu Orinì øíct, co se doopravdy stalo.<i>
{18390}{18426}<i>A také...<i>
{18428}{18497}<i>Kdyby... ale jen kdyby...<i>
{18509}{18617}<i>jsem se nebyla schopná zastavit...<i>
{18641}{18677}<i>Zastavil bys mì prosím?<i>
{18701}{18749}Vıznam tìch slov...
{18752}{18845}Dokonce ani teï, mì to nenechává v klidu.
{19001}{19085}Budu èekat.
