{48}{192}Pøeloila Rosie182 (Excel.Saga)
{216}{312}www.excel.saga.sblog.cz
{671}{767}Psychic Academy Aura Banshou - epizoda 17
{3285}{3357}<i>Hodnì štìstí a zdraví milı Ai-chan<i>
{3453}{3517}Dnes se o tebe postarám.
{3548}{3664}Epizoda 17: Narozeninovı dárek
{3728}{3752}Ano!
{3848}{3896}<i>*"Ojama shimaru" se bìnì øíká, kdy vstoupíme do nìèího domu.*<i>
{3908}{3992}Pojïte dál! Vítejte sleèno Chiroro,
{3994}{4028}na téhle mé párty.
{4052}{4112}Ale? Kde jsou studenti?
{4136}{4256}Popravdì, pro vás mám nìco speciálního.
{4292}{4340}Nìco speciálního?
{4352}{4436}Párty zaèíná o nìco málo pozdìji,
{4448}{4555}take my spolu mùeme strávit... nìjakı ten èas jako dva dospìlí lidé.
{4567}{4603}Profesore Zero Daimu,
{4615}{4675}pøestaòte prosím ertovat...
{4678}{4711}Myslím to vánì.
{4723}{4759}Sleèno Chiroro...
{4771}{4879}Právì teï jsem já vlk a vy jste ustrašené jehòátko.
{4891}{4951}A teï se pojïme my dva...
{4953}{4987}vydat spoleènì do svìta dospìlıch...
{5107}{5131}Poèkat!
{5239}{5263}Fakt!
{5275}{5299}Je nejhorší!
{5371}{5443}Nechtìla asi zajít tak daleko.
{5479}{5502}Dobrı den!
{5514}{5550}Jdeme dál.
{5562}{5598}Tak jsme tady!
{5634}{5694}Tak pojïte, pojïte!
{5874}{5910}Mùj malı bráška!
{5912}{5946}Tolik jsem se tìšil, e se uvidíme!
{5948}{5994}Mám pro tebe pár dárkù!
{6126}{6234}A navíc, Zerùv luxusní super speciální energetickı nápoj!
{6258}{6282}Tak.
{6342}{6426}Take, na Ai-chanovo zdraví a naše sjednocení!
{6438}{6474}Kampai!
{6486}{6533}*Kampai!*
{6785}{6833}Co se dìje, Ai-kun?
{6845}{6869}Nic.
{6881}{6905}Nechceš si se mnou dát tohle?
{6917}{6941}Ani ne.
{6965}{7037}Je to u dlouho, co jsi byl se Zerem.
{7049}{7121}O èem to mluvíš?
{7145}{7205}Nechal mì samotného kdo ví jak dlouho.
{7207}{7277}A teï se najednou objeví pøímo pøede mnou.
{7293}{7317}Ai-kun...
{7349}{7397}Vdycky mì srovnávali s bratrem.
{7433}{7481}Vdycky jsem se cítil na druhém místì.
{7516}{7624}Ale bratr se na mì dívá svım zvláštním úhlem pohledu.
{7744}{7768}Orino?
{7804}{7840}Neøíkej mi, e...
{7852}{7912}Je to kvùli bratrovu speciálnímu nápoji?
{7914}{7960}Jak roztomilı!
{7996}{8032}Mùj malı bratr, Ai-chan...
{8034}{8104}Krásnì roztomilı moment jeho ivota.
{8164}{8272}A do 3. tøídy základní školy mìl na zadku znaménko.
{8284}{8368}Tohle je nepochybnì jedno z jeho nejvìtších tajemství.
{8416}{8464}Pokraèujeme, další je...
{8511}{8535}Bratøe!
{8540}{8564}Ai-chan!
{8583}{8631}Pøestaò u s tím!
{8634}{8679}Ai-chan, tohle je nedorozumìní.
{8691}{8751}Já jenom pøedstavuju tvoje dobré stránky.
{8799}{8919}Tak, vypij si další speciální nápoj, aby jsi pøišel trochu k sobì.
{8979}{9027}Nezranil jsi se, e ne?
{9039}{9135}Tímhle chováním mi zpùsobuješ akorát problémy!
{9147}{9171}Ai-chan...
{9231}{9267}Jsi tak nesnesitelnı!
{9770}{9794}Bratøe...
{9797}{9914}Ai-chan, jsem opravdu tak nesnesitelnı?
{9998}{10130}Dobøe, jestli to tak cítíš, chápu to.
{10202}{10310}Dokonce i kdy jsme bratøi, nikdy jsme si moc nerozumìli.
{10322}{10430}Zvláš od té doby, co pøišli na moje speciální schopnosti.
{10442}{10525}Moná to pro tebe bylo tìké, nevím.
{10590}{10614}A proto...
{10645}{10717}Pamatuješ si, co se tenkrát stalo?
{11209}{11281}Tenkrát jsem tì nemohl zachránit.
{11305}{11401}Chtìl jsem tì jen chránit.
{11425}{11496}Teï u mì nemusíš chránit.
{11556}{11628}Chci bıt silnìjší.
{11676}{11844}Jednoho dne budu chránit tebe... i Orinu...
{11892}{11928}Vìøím, e to dokáeš.
{11976}{12036}Hej, Ai-chan?
{12048}{12156}Neøíkej mi, e to je mım energetickım nápojem.
{12295}{12319}Zero.
{12324}{12348}Myuu.
{12372}{12420}Pøišla sis sem nìkoho vyzvednout?
{12422}{12491}T-To ne...
{12515}{12551}U je to nìjaká doba.
{12587}{12611}Ano.
{12619}{12683}Od zavøení ADC, e?
{12619}{12707}<i>*ADC = Vıvojové centrum aury*<i>
{12719}{12767}Vypadáš poøád dobøe.
{12851}{12899}Myuu, omlouvám se,
{12901}{12971}ale mùeš vzít Ai-chan do lonice?
{12973}{13019}Proè bych mìla já?
{13175}{13259}Ber to jako péèi o mladšího brášku, kterého jsi nikdy nemìla.
{13261}{13307}Tak to vùbec není!
{13319}{13403}No, take já u pùjdu zpátky.
{13405}{13439}Postarám se o Sáru.
{13463}{13510}Poèkej chvíli!
{13534}{13570}Místo nìj,
{13573}{13606}bych radìji brala Sáru!
{13966}{14002}Jsi v poøádku?
{14026}{14074}Shiomi-kun, seber se trochu.
{14314}{14362}No tak, vstávej.
{14434}{14493}Shiomi-kun, no tak.
{14553}{14589}N-Ne!
{15261}{15285}Shiomi-kun...
{15297}{15321}Orino...
{15656}{15680}Pøeju ti...
{15704}{15740}hodnì štìstí.
{15776}{15800}Myuu.
{16124}{16148}Pravdou je...
{16172}{16256}e si ze vèerejška nic nepamatuju.
{16280}{16400}Já taky ne. Kdy jsem se probudila, byla jsem ve své posteli.
{16424}{16519}Take jsem... zapomnìla nejdùleitìjší vìc.
{16531}{16603}Eh? Nejdùleitìjší vìc?
{16639}{16711}Tvùj narozeninovı dárek.
{16747}{16771}Vdy jsem øíkal, e nemusíš.
{16783}{16867}Ale já ti to chci dát.
{16879}{16915}Opravdu?
{16927}{17011}Dobøe, v tom pøípadì chci prvnì tvùj polibek.
{17013}{17047}Jen ertuju.
{17526}{17610}Tvùj narozeninovı dárek...
{17694}{17730}U ti ho mùu dát, ne?
{18006}{18090}Dívejte se na nás prosím i pøíštì.
