{48}{192}Pøeloila Rosie182 (Excel.Saga)
{216}{312}www.excel.saga.sblog.cz
{695}{767}Psychic Academy Aura Banshou - epizoda 18
{3536}{3584}Mìla bych si pospíšit, nebo pøijdu pozdì.
{3608}{3764}První roèník, tøída B, tøídní pøedsedkynì, kód aury "Hiime Iren".
{3800}{3824}Kdo jste?
{3908}{3944}Lovci aur.
{4040}{4088}Tihle lidé jsou obyèejní lidé.
{4112}{4160}Nevyzaøují auru.
{4162}{4220}Znièit auru...
{4352}{4472}Epizoda 18: Lovci aur
{4495}{4567}Dobré ráno!
{4639}{4663}Dobré ráno.
{4687}{4723}Dobrı ráno.
{4726}{4759}Dobré ráno, Shiomi-kun.
{4855}{4939}A... Ai-kun... dobré ráno.
{4951}{5011}Do-Dobré ráno.
{5035}{5059}Tak nìjak se...
{5107}{5143}C-Co?
{5155}{5179}vy dva...
{5203}{5287}chováte trochu divnì.
{5289}{5335}To se ti jen zdá.
{5383}{5479}Pravda. Chováme se stejnì jako obvykle.
{5491}{5514}e jo?
{5550}{5586}To je opravdu podezøelé.
{5598}{5658}Stalo se snad mezi nimi nìco?
{5661}{5730}Coe? Se Sárou?
{5766}{5814}Ty u to máš za sebou?!
{5826}{5862}Vùbec ne!
{5874}{5934}Tak daleko jsme se ještì nedostali...
{5936}{5994}"Tak daleko"?!
{6006}{6066}Tak jak daleko chceš øíct?
{6078}{6102}Poèkej!
{6114}{6150}Tohle mì bolí!
{6152}{6234}Nech mì! Hej! Hej! Hej!
{6198}{6234}Stalo se nìco hrozného!
{6236}{6270}Pøedsedkynì tøídy byla...
{6282}{6318}Co se dìje?
{6330}{6366}Stalo se nìco Hiime?
{6378}{6414}Chytili jí Lovci aur.
{6605}{6797}Byla tma, take si nejsem jistá, ale jejich hlasy znìly...
{6809}{6857}jako hlasy støedoškolákù.
{6905}{6929}Take je to pravda.
{6965}{6989}K èertu.
{7001}{7037}To dìlá tøi.
{7061}{7133}Jakı je jejich cíl?
{7135}{7313}Tenhle druh vìcí se obvykle dìlá, aby si nìkdo potvrdil nadøazenost nad tìmi, kdo mají auru.
{7337}{7445}Mùou to bıt lidé, kteøí jsou proti této škole zaujatí.
{7469}{7492}Zaujatí?
{7495}{7564}Nemyslíš snad lidi, kteøí pouívají svou auru venku?
{7567}{7600}Jako v soubojích?
{7612}{7708}Kadopádnì, abychom pøedešli dalším zranìním,
{7711}{7780}je dùleité, aby byli studenti odteï mnohem opatrnìjší.
{7912}{8008}Je to hrozné, e... ti Lovci aur.
{8032}{8128}Ano. Ale vypadá to na normální lidi.
{8140}{8248}Z jejich pohledu to moná vypadá, e máme zbraò, kterou oni nemají.
{8250}{8380}To neøíkej. My jsme taky normální lidé.
{8404}{8440}To bude v poøádku.
{8476}{8595}Já... Já tì budu ochraòovat.
{8727}{8751}Opravdu?
{8859}{8883}Dìkuju ti.
{9027}{9087}HEJ VY DVA!
{9123}{9219}Kdy se schyluje k polibku, problém vás dìtí je, e nevíte jak to udìlat!
{9231}{9291}Jsi chlap, tak se podle toho chovej!
{9303}{9339}Mistøe!
{9494}{9518}Ano!
{9521}{9566}Sáro, mùu s tebou na chvíli mluvit?
{9578}{9602}Kyaaru?
{9662}{9698}Kde je Myuu?
{9710}{9758}Právì se koupe.
{9770}{9794}Na.
{9830}{9878}To je skvìlé.
{9890}{9938}Eh? O èem to mluvíš?
{9940}{10010}Mimochodem, jak to jde s Shiomim-kun?
{10012}{10070}J-Jak to jde...
{10082}{10118}Jak daleko jste se dostali?
{10142}{10209}Nikam! Nic jsme nedìlali.
{10211}{10250}Ještì jsi mu nevyznala lásku?
{10252}{10286}V ádném pøípadì!
{10298}{10334}Oh.... chápu.
{10346}{10418}Dobøe, v tom pøípadì, chceš abych ti øekla o nìèem dobrém?
{10420}{10478}Eh? O nìèem dobrém?
{10501}{10549}O Shiomim-kun.
{10561}{10645}Eh? Ai-kunovi se nìco stalo?
{10657}{10693}Popravdì...
{10729}{10753}On...
{10861}{10897}O-Opravdu?
{10909}{11017}Take by to bylo v poøádku, kdyby jsi mu vyznala lásku, nemyslíš?
{11019}{11043}To nemùu udìlat...
{11077}{11125}Kdybych to udìlala teï, tak...
{11127}{11144}Eh?
{11173}{11233}Eh? Ehm...
{11245}{11401}Jestli jde o tohle, radìji bych to slyšela od nìj.
{11403}{11437}To nemùeš.
{11439}{11556}Jestli nebudeš opatrná, Myuu ti ho pøebere.
{11583}{11736}Vdy víš, e Ai-kun a Myuu mají sluèitelnost aur 100% ne?
{11772}{11892}Mluvíme o chladné uzavøené Myuu, take by to nemìl bıt takovı problém, ale...
{11894}{11976}nemùeme øíct, jaké má Myuu city.
{11988}{12024}Slyšela jsem tvou úvahu.
{12048}{12096}My-Myuu!
{12098}{12168}Já u radši pùjdu.
{12180}{12204}Dobrou noc!
{12348}{12396}He-Hele Myuu.
{12468}{12539}Slyšela jsi ten rozhovor?
{12611}{12707}No... Já si myslím, e Kyaaru si jen dìlala srandu.
{12719}{12743}Take...
{12803}{12839}Rozumím.
{12863}{12899}Tak trochu.
{12911}{13019}Kdy jsem blízko Shiomimu -kun, vypadá pøátelsky. 
{13043}{13187}A navíc, myslím si e by vám to spolu slušelo.
{13199}{13223}Opravdu?
{13247}{13379}Protoe jste to vy dva, nevadí mi to.
{13391}{13415}Myuu...
{13417}{13534}A proto, mezi námi dvìma se nic nezmìní.
{13582}{13738}Protoe... jsme kamarádky.
{13822}{13846}Myuu...
{13863}{13887}Dìkuju ti.
{13906}{13930}Mám tì ráda!
{13966}{14074}Hej! Pøestaò mi hladit prsa!!!
{14098}{14122}Ty!!!
{14290}{14338}Moje panenka Ai-kuna...
{14364}{14386}Miluji tì.
{14410}{14434}Ai-kun...
{14697}{14757}lutá aura...
{14805}{14925}Barva zlomeného srdce...
{15177}{15225}Ha, studentskı pøedseda!
{15285}{15369}Je tu nìkde Shiomi Ai?
{15405}{15500}Ehm, já jsem Shiomi Ai.
{15503}{15632}Jsem ze tøetího roèníku, tøída B, kód aury "Chouza Ruuru".
{15716}{15752}Buï opatrnı.
{15764}{15836}Lovci aur jdou po tobì.
{15848}{15908}Lovci... aur?
{16064}{16136}Pojïme si to uít i pøíštì.
