{48}{192}Pøeložila Rosie182 (Excel.Saga)
{216}{312}www.excel.saga.sblog.cz
{695}{767}Psychic Academy Aura Banshou - epizoda 20
{3105}{3117}Myu...MYUU!
{3153}{3225}Mìl bych jí donést na školní ošetøovnu.
{3273}{3345}Vypadá jakoby jen podøimovala.
{3357}{3453}A tahle jemnost je celkem pøíjemná...
{3524}{3572}Eh, na tohle není èas!
{3759}{3824}Když mì drží takhle tìsnì...
{3884}{3956}Je...Její prsa se mì dotýkají...
{4076}{4184}Epizoda 20: Únos
{4400}{4436}Myuu, jsi v poøádku?
{4507}{4651}<i>Teï když o tom pøemýšlím, Kyaaru øíkala, že máme sluèitelnost aur 100%.<i>
{4675}{4723}<i>To mì pro ni dìlá blízkým.<i>
{4735}{4795}<i>A taky mi díky tomu dìlá starosti.<i>
{4999}{5047}<i>Co to dìlám.<i>
{5167}{5263}Shiomi-kun. Co se stalo té dívce?
{5275}{5419}Popravdì, Myuu náhle omdlela, takže jí teï nesu na ošetøovnu.
{5431}{5479}To je opravdu zlé.
{5514}{5622}Mimochodem, ty jsi velmi blízký Myuu Bauøe, že?
{5625}{5682}No... vlastnì...
{5850}{5886}Dìje se nìco?
{5889}{5922}Eh... Ne.
{5958}{6078}<i>Jsem si jistý, že jsem teï vidìl, jak z nìj nìco vychází.<i>
{6138}{6186}Mimochodem, Shiomi-kun.
{6198}{6222}Ano?
{6234}{6378}Tvùj bratr je ten velkolepý Zero Daimu, že?
{6402}{6450}To je pravda.
{6474}{6521}Vážnì ti závidím, víš.
{6524}{6617}Výsadu mít za bratra nìkoho tak skvìlého.
{6764}{6809}Co se probùh stalo?
{6821}{6893}Jen znièehonic omdlela.
{7121}{7178}Prozatím bychom mìli...
{7385}{7433}Jak dlouho se míníš takhle koukat?
{7435}{7469}O-Omlouvám se!
{7780}{7816}Už jsi vzhùru?
{7840}{7864}Tohle je...
{7876}{7900}Školní ošetøovna.
{7912}{8020}Shiomi-kun se o tu o tebe celou dobu staral.
{8032}{8068}Shiomi-kun?
{8104}{8176}Máš opravdu vážnì poškoženou auru.
{8248}{8344}Myuu, stává se tohle èasto?
{8346}{8416}Ne, možná tak jednou za mìsíc.
{8440}{8559}Možná je problém v tvé síle.
{8619}{8751}Piješ vodu aby jsi znovu nabyla síly k použití své aury,
{8754}{8847}ale tvoje tìlo i pøesto trpí.
{8895}{8977}Sleèno Chiroro, jsem v poøádku.
{8991}{9039}Myuu, mùžu?
{9144}{9168}Shiomi-kun.
{9207}{9243}Jak se cítíš?
{9255}{9375}Myuu, celou dobu byl u tebe.
{9447}{9471}Dìkuji.
{9494}{9518}<i>A zase...<i>
{9542}{9602}Myuu, já jsem se rozhodl.
{9650}{9710}Používat svou auru mnohem víc.
{9729}{9902}Nemohl bych ochraòovat tebe a Orinu, kdybych ji víc nepoužíval, že?
{9938}{10010}Takže za tímhle úèelem budu odteï mnohem víc trénovat.
{10082}{10154}Tak, zatím odpoèívej, jo?
{10166}{10250}Být takhle zesláblá - to nejsi ty.
{10334}{10358}Shiomi-kun!
{10501}{10525}Copak?
{10549}{10609}No... Hodnì štìstí.
{10729}{10753}Tak ahoj.
{10885}{10945}To jsem opravdu... nebyla já.
{11161}{11233}Tak jsi koneènì pøišel na své cvièení.
{11257}{11317}Ano, mistøe. Prosím, udávej mi instrukce!
{11341}{11365}Výbornì!
{11367}{11485}Zaèneme užíváním tvého druhého kódu aury.
{11496}{11556}Mého druhého kódu aury?
{11568}{11688}Co? Bylo ti to øeèeno bìhem testování tvé aury.
{11691}{11724}Testování aury...
{11772}{11916}Podívejme se. Mám výsledek tvého testování aury, ale...
{11928}{11976}Je to trochu divné.
{12000}{12048}Co je na tom divného?
{12050}{12192}Ale nic, jen máš pomìrnì silnou promìnu aury,
{12216}{12336}ale ta schopnost se sama o sobì projevuje pozdì...
{12360}{12432}To je tak trochu neobvyklé.
{12491}{12611}Každopádnì se to prokázalo teï na druhém a ètvrtém...
{12623}{12695}Jedna hlavní leží na druhé,
{12707}{12815}abys zaèal používat svojí auru, musí se to takhle "zapnout".
{12851}{12935}Ehm, co to znamená?
{12947}{13127}Jinými slovy, díky tomu kódu mùžeš vyvolat svojí auru.
{13139}{13211}Je to jako klíèové slovo.
{13247}{13283}A to bylo...
{13391}{13451}"Daudo" myslím...
{13453}{13486}Správnì.
{13498}{13582}Takže teï to zaøvi.
{13594}{13630}A-Ano.
{13633}{13666}Daudo!
{13678}{13786}Idiote! To nic nebylo, znova!
{13798}{13834}Když to øíkáš.
{13870}{13918}Tak ještì jednou.
{13942}{13990}DAUDO!
{14086}{14146}Idiote! Idiote! Idiote! Idiote! Idiote!
{14158}{14194}Co to zkoušíš?!
{14206}{14266}Kód aury je klíèové slovo!
{14268}{14302}Tohle je postupný proces,
{14304}{14350}KE KONCENTRACI!
{14673}{14709}Kdo je tam?
{14721}{14745}Shiomi-kun?
{15033}{15081}Daudo!
{15165}{15237}Mistøe! Právì teï, nìco bylo...
{15239}{15357}Hmm, není pochyb, to byla specializace tvé aury.
{15369}{15488}Mistøe, jakého druhu je moje aura?
{15512}{15596}Promiò, ale takhle brzy to ještì øíct nemùžu.
{15599}{15740}Ale teï už cítím, jak z tebe aura vyzaøuje.
{15764}{15800}Vyzaøuje?
{15860}{15884}<i>Myuu!<i>
{15908}{15932}Co je?
{15956}{15992}Jsem si jistý, že teï...
{16160}{16232}Je možné, že... se nìco stalo Myuu?
{16591}{16627}Jak nehezká.
{16630}{16651}Myuu Baura.
{16675}{16771}Tušila jsem, že jsi to ty.
{16774}{16843}Neøíkal jsem ti, aby sis dávala pozor?
{17371}{17455}Dívejte se i pøíštì.
