{48}{192}Pøeložila Rosie182 (Excel.Saga)
{216}{312}www.excel.saga.sblog.cz
{671}{767}Psychic Academy Aura Banshou - epizoda 22
{3273}{3321}Letní tréninkový tábor u moøe?
{3333}{3441}Ano. Po pøijímacím obøadu jedou všichni.
{3453}{3548}Myslíš kluci A holky?
{3596}{3620}Jistìže.
{3644}{3692}<i>Jedou i holky.<i>
{3695}{3728}<i>To znamená...<i>
{3781}{3805}<i>Plavky.<i>
{3925}{3949}<i>Ai-kun.<i>
{3973}{4004}<i>O-Orino.<i>
{4064}{4148}<i>Tady nás nikdo nenajde.<i>
{4352}{4388}Po-Poèkat!
{4400}{4448}Co to sakra dìláš?
{4615}{4711}Epizoda 22: Tréninkový tábor
{4819}{4939}<i>A také bych rád øekl, že jste se tento rok všichni velmi snažili.<i>
{4941}{5011}<i>Avšak, nemyslete si, že teï mùžete jen odpoèívat.<i>
{5013}{5083}<i>Aby jste byli poøád tak vynikající, na tomto letním tréninkovém táboøe<i>
{5085}{5155}<i>se prosím také snažte.<i>
{5059}{5203}Na tomhle blížícmí se tréninkovém táboøe musím nìco udìlat.
{5227}{5251}<i>Tentokrát...<i>
{5275}{5359}<i>Moje pravé city k Orinì...<i>
{5742}{5790}<i>Moøe... plavky...<i>
{5802}{5862}<i>Moøe... plavky...<i>
{5874}{5898}Ai-kun?
{5910}{5946}Dáš si?
{6102}{6150}Ai-kun, co se dìje?
{6198}{6246}J-Jen trochu divné myšlenky.
{6665}{6749}Takže, kde jsou holky...
{6752}{6795}Plavky, plavky!
{6857}{6905}Hej vy!
{6953}{7001}To je pan Goa.
{7003}{7133}Nepøišli jsme si sem hrát, pøišli jsme sem, abychom vypracovali sílu našich aur!
{7135}{7181}Pamatujte, tohle je tréninkový tábor!
{7265}{7313}Nejdøív protahovací cvièení.
{7325}{7373}Takže! Raz, dva,
{7375}{7409}tøi, ètyøi...
{7433}{7481}Pøedpokládal jsem, že se pøidáte!
{7648}{7696}S-Sleèno Chiroro!
{7708}{7792}J-Je vskutku docela sexy...
{7840}{7864}Pane Goa?
{7867}{7924}A-A-Ano sleèno Chiroro?
{7936}{8032}Každou chvíli by se tu mìl objevit další uèitel, který tu s námi bude.
{8044}{8152}Další uèitel? Kdo ksakru?
{8212}{8248}Co to...?
{8308}{8344}To je... !
{8835}{8919}Legendární muž Zero Daimu právì dorazil!
{8921}{8943}Bratøe!
{9219}{9291}Omlouvám se za zpoždìní, sleèno Chiroro.
{9339}{9411}Chtìl jsem vás vidìt tak rychle jak jen to bude možné.
{9423}{9483}Takže jsem pøemýšlel o speciálním transportu.
{9506}{9530}Ehm...
{9578}{9674}Tak a nyní se oba...
{9686}{9734}vydejme do svìta dospìlých.
{9768}{9792}Vážnì.
{10022}{10046}Plavky!
{10166}{10202}Kde je Orina?
{10370}{10394}Myuu...
{10430}{10478}Uau, nádherný tìlo!
{10645}{10705}Eh? Myuu nejde plavat?
{10717}{10801}<i>No jasnì, Myuu je slabá poblíž vody.<i>
{10825}{10885}No tak, na co se to koukáš?
{10957}{10993}Ai-kun?
{11005}{11029}Orino.
{11041}{11084}Vypadáš roztomile...
{11101}{11173}Nekoukej se na mì takhle...
{11185}{11221}Stydím se.
{11329}{11389}Mimochodem, Orino.
{11401}{11473}C-Copak, Ai-kun?
{11508}{11556}N-No já...
{11712}{11760}C-Co má tohle znamenat?
{11763}{11796}Támhle, pojïme!
{12384}{12420}Profesore Zero Daimu?
{12432}{12491}Co to tam dìláte?
{12515}{12551}Necítíte to?
{12683}{12731}Na tom ostrovì nìco je.
{12923}{12971}Sem nikdo nepøijde.
{12983}{13091}Ah, t-tím jsem nic nemyslela!
{13367}{13439}Hele, pamatuješ?
{13510}{13558}Ten den na pláži.
{13582}{13666}Slunce zapadalo, mìsíc se pomalu objevoval.
{13714}{13774}Bylo tam nekoneèné ticho života.|
{13810}{13870}Tenkrát jsem tì poprvé potkal.
{13882}{13942}Tak to bylo, že?
{13966}{14117}Víš, já se vždy snažím skrývat svojí sílu.
{14170}{14314}Jednou na základní škole jsem pøedstírala, že je mi špatnì...
{14386}{14482}Protože jsem od tebe nechtìla odejít.
{14589}{14685}Ale jsem ráda, že jsme takhle znovu spolu.
{14829}{14865}E-Ehm...
{14987}{15035}Nádherná mušle!
{15465}{15488}Ne...
{15520}{15544}Orino...
{15800}{15824}Promiò!
{15836}{15896}Nenaštvi se...
{16388}{16472}Pojïme si to užít i pøíštì.
