{48}{192}Pøeloila Rosie182 (Excel.Saga)
{216}{312}www.excel.saga.sblog.cz
{635}{738}Psychic Academy Aura Banshou - epizoda 24
{3489}{3548}Jsi to ty, jak jsem pøedpokládal.
{3560}{3596}Zero Daimu?
{3608}{3656}Dlouho jsme se nevidìli.
{3692}{3776}Vdycky jsem vìdìl, e máš bloudící auru.
{3800}{3860}Eh, vypadalo to na to.
{3944}{4040}Epizoda 24: Para-sen
{4042}{4112}Promiòte, ale co se to dìje?
{4124}{4172}A kdo je tenhle chlapec?
{4184}{4220}Mùj mladší bratr.
{4232}{4268}Mladší bratr?
{4280}{4304}E...Ehm...
{4316}{4400}Byla pouita svìtelná aura...
{4424}{4495}To bylo poprvé, co jsem nìco takového vidìl.
{4555}{4615}Urèitì máte hlad,
{4618}{4675}snìzte kolik mùete,
{4678}{4747}i kdy to nepatøí zrovna mezi nejchutnìjší jídla.
{4759}{4783}Pravda.
{4843}{4903}Není to moc decentní.
{4905}{5059}Eh, ten kdo má velkou pusu musí mít vdy chytré poznámky.
{5107}{5179}Kadopádnì, proè ten ohoz?
{5203}{5263}Omlouvám se, jestli jsem vás vystrašil.
{5311}{5443}Bylo to nezbytné k ochranì téhle scenérie.
{5445}{5479}Téhle scenérie?
{5481}{5634}Tohle je ta stejná scenérie, jakou jsem vidìl já a nìkdo z vás ve snu u kdysi dávno.
{5694}{5766}Máš na mysli Para-sen.
{5802}{5886}<i>"Slunce zapadalo, mìsíc se pomalu objevoval."<i>
{5946}{6018}<i>"A bylo tam nekoneèné ticho ivota."<i>
{6090}{6162}Sen všech lidí mající auru má stejnı rys.
{6186}{6246}U jsem na to skoro zapomnìl.
{6270}{6390}Pamatuji se, e jsem cítil nìco zvláštního a mocného uvnitø své aury.
{6402}{6497}Jakı smysl mùe ten sen mít,
{6500}{6617}a proè mají všichni lidé mající auru, stejnı sen...
{6620}{6665}na to jsem chtìl právì pøijít.
{6668}{6833}Take proto jsi zmizel z ADC pøed 12 lety?
{6869}{7121}Myslel jsem si "proè nevyuít auru k nalezení mé vysnìné scenérie oceánu".
{7169}{7258}A potom jsem pøišel sem...
{7265}{7325}Take, tohle místo...
{7349}{7433}Vypadá to tak, ale tady to není.
{7435}{7457}Ehm...
{7481}{7552}Také jsem to vidìl, tuhle scenérii.
{7588}{7660}Opravdu to byl sen?
{7663}{7684}Ano.
{7696}{7840}Síla té scenérie dokonce ani neexistuje.
{7843}{7948}Proto jsem chtìl ochraòovat pøinejmenším tohle místo.
{7950}{8032}Scenérii tak nádhernou jako je tahle.
{8068}{8104}Jenom sám?
{8128}{8219}Ve svém snu jsi vdycky sám!
{8272}{8296}Sám?
{8320}{8344}Správnì.
{8346}{8464}Z nìjakého dùvou jsou tam všichni sami.
{8466}{8523}Tak jako jsem teï já.
{8643}{8667}Myuu?
{8715}{8787}Jdu zpátky na loï.
{8835}{8871}Ta dívka...?
{8883}{8991}Popravdì, ona byla také v ADC.
{9015}{9051}Opravdu?
{9255}{9279}Ai-kun.
{9291}{9351}Ah, to u se vracíme zpátky?
{9399}{9471}Pamatuji se, ale...
{9506}{9638}Øíkal jsi, e jsi mì potkal ve snu, ale...
{9662}{9794}ten mu mìl pravdu, také jsem tam byla sama.
{9914}{10010}Ta dívka byla tvoje první láska, viï?
{10142}{10226}Na tom u nezáleí.
{10238}{10262}Ai-kun...
{10286}{10406}Pro mì jsi teï nejdùleitìjší vìcí ty.
{10418}{10501}Pro mì jsi moc dùleitá.
{10521}{10545}Ai-kun!
{10573}{10597}Orino...
{10633}{10717}Já... Já...
{10729}{10753}Ai-chan.
{10777}{10849}Brácho? Co to má bıt?!
{10861}{10957}Myuu se nevrátila na loï.
{11041}{11101}Kam ta Myuu mohla jít...
{11508}{11532}Shiomi-kun.
{11580}{11604}Myuu.
{11616}{11652}Co tady dìláš?
{11676}{11748}Celou dobu pøemıšlím.
{11772}{11820}O moøi v mém snu.
{11880}{11964}To jsem mohl èekat, ty jsi mìla taky ten sen?
{11966}{12156}Kdy jsem byla v ADC, odmítla jsem pokraèovat v pouívání své síly.
{12192}{12252}Nenávidìla jsem tu sílu, kterou jsem mìla.
{12312}{12336}<i>Proè!<i>
{12338}{12432}<i>Proè nepouíváš tu sílu, kterou máš!<i>
{12444}{12468}<i>Myuu!<i>
{12587}{12755}Ale byly i doby, kdy jsem ji sama od sebe pouívala,
{12779}{12851}kdy jsem mìla sen, potkala jsem toho chlapce...
{12923}{12947}<i>To není moné...<i>
{13031}{13115}<i>Tenkrát tam byla plaèící dívka.<i>
{13199}{13259}Hej ty, co se dìje?
{13367}{13403}Proè pláèeš?
{13415}{13451}Jak se jmenuješ?
{13486}{13570}Já... nemám jméno.
{13594}{13666}Urèitì proto, e nejsem hodná holèièka.
{13882}{13930}Ah! To je krásné!
{13954}{13990}Víøí to a  tøepetá se to,
{13992}{14038}úplnì jako èervená mušle.
{14050}{14110}Ty se ani trochu nebojíš?
{14112}{14146}Vùbec ne!
{14158}{14194}Aah! To je skvìlé!
{14206}{14278}Také bych to chtìl jednou umìt!
{14290}{14326}Tak jako ty!
{14374}{14422}Hele, pojïme si hrát!
{14505}{14601}<i>To nebyla èervená mušle...<i>
{14973}{14997}Tady jsi!
{15033}{15069}Našla jsi mì!
{15177}{15261}Jsi opravdu roztomilá, kdy se usmíváš.
{15273}{15297}Vánì?
{15333}{15405}<i>A ta dívka byla...<i>
{15548}{15572}Ai-kun?
{15656}{15680}Orino...
{16088}{16220}<i>Po letních prázdninách zaèal opìt normální školní ivot.<i>
{16328}{16376}Dobré ráno, Ai-kun.
{16378}{16424}Ah, dobré ráno, Orino.
{16472}{16579}<i>A ta dívka tenkrát byla kdokoliv, teï je pro mì definitivnì...<i>
{16603}{16651}DOBRÉ RÁNO!
{16654}{16683}Faafo!
{16711}{16771}Koneènì u nikdy nebudu uvìznìná!
{16774}{16819}Uvìznìná?
{16831}{16879}Myslíš jako e Ren-san...
{16927}{17035}No tak, pøemìò se zpátky na Ren-sana. U jsi zase otravná.
{17037}{17143}V ádném pøípadì, nejela jsem na tréninkovı tábor,
{17145}{17215}take odteï budu s Ai-kunem poøád!
{17239}{17311}Zapomnìla jsi, e Shiomi-kun u má teï Sáru?
{17313}{17371}Sáru mám ráda taky, take je to v poøádku!
{17383}{17467}Mimochodem, u jsi našla nìjakou lásku-lásek?
{17479}{17490}Eh?
{17526}{17574}Já vím!
{17577}{17634}Máš ráda nìjakého kluka!
{17706}{17742}Je to pravda, Myuu?
{17754}{17826}No... Vlastnì...
{17838}{17922}To je skvìlé! Take? Jakı ten kluk je?
{17924}{18018}Øekni, øekni! No tak, Myuu!
{18030}{18090}Hej! Pozor! Moje prsa...
{18126}{18234}Tak dost. Já chci taky! Já taky!
