{300}{350}Tenchi Muyo
{2726}{2811}Princezná Ayeka,|nad èím uvauješ ?
{2936}{3005}Svadobné pytaèky,|akoby vás úplne vyèerpali ...
{3008}{3052}Princezná Ayeka.
{3055}{3173}Môem vám navrhnú odpoèinok,|dokım nedorazíme na planétu Jurai?
{3176}{3220}A akonáhle sa vrátime|z planéty Jurai ...
{3221}{3259}Budem musie okamite|zase odcestova ...
{3261}{3316}na ïalšie pytaèky,|však?
{3318}{3351}Áno, princezná, ale ...
{3353}{3447}Ja viem. Je to moja povinnos|ako prvej princeznej ...
{3449}{3496}z Juraiskej krá¾ovskej rodiny .
{3557}{3644}Viem to a moc dobre.|Áno, viem.
{3822}{3876}Hej, Tenchi.
{3877}{3908}Skonèime s tou|nudnou prácou .
{3909}{3952}Poï sa hra a zabáva so mnou !
{3954}{3998}Hej, nechaj ma.
{4001}{4036}Dedko je ve¾mi úzkostlivı ...
{4038}{4087}kvôli zachovaniu èistej zemi|pred svätyòou.
{4089}{4191}Hmm, tu a tam.
{4193}{4240}Mihoshi, èo je to?
{4241}{4327}To je špeciálne zariadenie vıhradne|pre Galaktickú Políciu.
{4329}{4401}Tu otoèím, |a ešte tu.
{4404}{4474}Tam! Môeš vysla teraz|núdzovı signál.
{4477}{4528}Váne môeš poèíta s tım,|e taká hraèka ako táto ...
{4529}{4565}v tom vzdialenom regióne|vesmíru?
{4567}{4616}S oh¾adom na štatistiky ...
{4619}{4675}jeden prípad za 200 rokov je|zaznamenanı ...
{4677}{4717}ako úspešná záchrana.
{4720}{4782}Vidíš,|to znamená to èo si myslím.
{4877}{4917}Ale stále je to lepšie ako|tu len tak sedie ...
{4934}{4953}a niè nerobi!
{5000}{5027}Èo je, Azaka?
{5029}{5109}Princezná Ayeka,|zachytili sme núdzové volanie.
{5126}{5139}Z kade ?
{5141}{5180}Hneï to zistím.
{5192}{5288}Hmm, z tretie planéty|pri najblišej stálici.
{5290}{5322}Èo s tım môeme robi?
{5325}{5392}Nemôeme to len tak ignorova,|Odhadujem, 
{5393}{5434}e nám zostáva ešte trochu èasu ...
{5437}{5504}pred dohodnutou schôdzkou|so Sasami, však?
{5505}{5549}Áno, naša vısos.
{5552}{5599}Tak potom priamo k planéte.
{5601}{5628}Áno, sleèna!
{6085}{6109}È-èo to je ?
{6111}{6134}To nemôe by pravda
{6137}{6199}Hurá ! Tu som !
{6201}{6281}Yu-hú!
{6282}{6373}Ta vesmírna loï mi vyzerá|dos povedome .
{6376}{6429}Hmm, nevadí .
{6613}{6662}Èakala som na vás!
{6665}{6728}Yu-hú!
{7222}{7253}Si to ty?!|-Si to ty?!
{7255}{7276}Èo ?!|-Èo ?!
{7279}{7358}Ty si stále naive,|sleèna Ryoko!
{7361}{7448}Galaktická polícia sa v poslednom èase|stala celkom nespo¾ahlivá.
{7451}{7501}Predpokladám, e a naháòali|a na túto vzdialenú planétu.
{7504}{7578}Si na vyhnanstve|z Juraiskej krá¾ovskej rodiny ...
{7580}{7620}alebo padlo vaše krá¾ovstvo?!
{7697}{7736}Ah, si strašne vtipná.
{7738}{7781}Všeobecne slávna Juraiská|královská rodina ...
{7784}{7808}je veèná, navdy!
{7811}{7888}Èo? Juraiská krá¾ovská rodina|je stratená, navdy?
{7889}{7915}Ja som povedla veèná, navdy!
{7917}{7961}To je dos zlé !
{8001}{8068}Prepáète, ale ...|vy sa navzájom poznáte?
{8069}{8143}Ve¾mi pekne ïakujem, e ste|dorazili pre mòa .
{8145}{8216}Vidíte,|ja som tá v núdzi.
{8217}{8259}Haló ? Prepáète?
{8261}{8380}Ja som sem dorazila|niekoho zachráni ...
{8381}{8453}a ja tu narazím len na takú|príšeru ako si ty.
{8456}{8526}Ccc!|Nikdy som ti nevolala aby si prišla..
{8541}{8610}Fajn, to som bola ja,|èo poslala núdzové volanie.
{8612}{8682}Aké protivné ! Azaka!|Kamidake! Odchádzame!
{8685}{8717}Áno, sleèna !
{8733}{8752}Jasne, choï preè. Zmizni !
{8754}{8820}Prosím ! Nechoïte preè|bez môjho povolenia!
{8821}{8861}Dobre oslobodenie !
{8864}{8885}H-hej...
{8916}{8961}Èisté mrhanie môjho èasu.
{8964}{9010}Ach, prosím!
{9013}{9077}Neodchádzajte !
{9080}{9131}È-èo to robíš ?!
{9133}{9208}Ja som v núdzi,|hovorila som vám to!
{9210}{9251}Nechaj ma!
{9253}{9344}Ak ma teraz opustíte,|tak ja ... ja ...
{9377}{9467}V poriadku ! Rozumiem !|A teraz ma nechaj tak!
{9469}{9514}Prosím.
{9608}{9704}Take ty si prišla z planéty|nazvanej Jurai, však?
{9705}{9729}Áno.
{9731}{9834}Môeš mi prosím porozpráva|o tvojej planéte ...
{9837}{9956}o pohoriach, dolinách,|¾uïoch a rastlinstve na Jurai?
{9957}{9992}Samozrejme .
{9994}{10040}Nemôeš by taká hrubá...
{10041}{10109}na niekoho, kto ju prišiel|zachráni !
{10110}{10132}Má pravdu !
{10134}{10240}Skoro odišla,|a to len kvôli tebe!
{10241}{10267}Teraz, poèúvajte.
{10269}{10331}Ani neviete aká je to|v skutoènosti nehorázna krava .
{10333}{10384}Ako môeš nieèo také poveda !?
{10387}{10447}Ako to, e poznáte jedna druhú ...
{10449}{10504}princezná|z Juraiskej krá¾ovskej rodiny ...
{10507}{10547}a najznámejšia h¾adaná|kriminálnièka ?
{10549}{10590}Bolo to keï ...
{10593}{10668}áno, keï som bola ešte malá,|nevinné diea.
{10742}{10854}Jedného dòa, som robila|kvetinovı veniec na planéte.
{10857}{10926}Mnostvo kvetov v rôznych|farbách boli v rozkvete.
{10929}{10964}Ach, to bola krása.
{10976}{11071}Hej!|Èo tu robíš ?!
{11073}{11157}Toto je územie|Juraiskej krá¾ovkej rodiny.
{11174}{11219}Kto ti dal povolenie |sa tu hra ?!
{11221}{11272}Ja--Ja som len...
{11311}{11373}A teraz vypadni, rıchlo !
{11390}{11411}OK.
{11441}{11489}Ty si ich nemôeš|zobra so sebou.
{11491}{11514}Ale...
{11517}{11552}Ako som hovorila ...
{11554}{11625}táto planéta je územie|Juraiskej krá¾ovkej rodiny.
{11626}{11704}A všetko tu|patrí mne!
{11705}{11752}Ty si lakomá.
{11781}{11874}To bolo moje prvé stretnutie|s Ayekou.
{11920}{11971}Správne.  Rozumiem.
{11973}{12100}Táto rana v tvojom malom srdieèku|zostala navdy.
{12101}{12158}Tak koneène mi rozumieš,|Mihoshi ?!
{12161}{12220}Áno ! Teraz chápem|èo a priviedlo na zlú stranu ...
{12222}{12247}v prvom rade !
{12249}{12296}Potom si sa stala|mladou delikventkou ...
{12297}{12364}ís stále nišie a nišie|na cestu zla !
{12366}{12421}Ach, aká škoda!|¼utujem a.
{12489}{12616}Vidím, e Jurai znie|ako prekrásne miesto.
{12617}{12689}Áno. Ja musím chráni|a pokraèova ...
{12691}{12777}Juraiskıch tradíciách|za kadú cenu.
{12829}{12881}Dokonca aj ...
{13005}{13037}Kto je to ?!
{13040}{13109}Ach, to si ty.
{13112}{13170}No, doniesol som vám|zopár koláèikov.
{13197}{13233}A práve vèas, tie.
{13234}{13290}Tenchi, preèo nevezmeš |sleènu Ayeka von na prechádzku ...
{13293}{13328}poukazova jej okolie ?
{13357}{13408}Pohoria a polia|na tejto planéte ...
{13409}{13476}majú svoje vlastné èaro,|iné od Juraiskıch.
{13477}{13548}Špeciálne v tom èase|roka ...
{13549}{13589}Je tam dos toho|k videniu.
{13592}{13627}Ale ...
{13630}{13713}Je dobré i |pre úlohy princeznej ...
{13715}{13770}ale niekedy to znamená,|e nemáš vo¾nı deò...
{13773}{13808}z èasu na èas.
{13810}{13880}Nejaké šastie a prinieslo|na túto planétu ...
{13882}{13963}môeš vyui vıhodu z toho|a vyskúša relaxova ...
{13965}{14026}zabudnú na všetky trápenia|aspoò na tento deò.
{14029}{14058}Postaráš sa o to Tenchi?
{14060}{14097}Ach, jasne.
{14422}{14461}To je krása.
{14464}{14511}Tie si to myslíš ?
{14514}{14539}Áno.
{14541}{14598}No, tieto kopce|vyzerajú najlepšie ...
{14600}{14672}v tomto období, domnievam sa,|ale, e sú to len prosté kopce.
{14674}{14716}Ach, nie.
{14718}{14776}Urèite majú svoju|odlišnú krásu...
{14777}{14836}z toho èo som videla na Jurai.
{14837}{14894}To je zaujímavé.
{14897}{14966}My nie sme schopnı si|uvedomova ...
{14968}{15065}krásu alebo šastie|dokım nám to niekto nepovie.
{15131}{15179}Môeme sa pomaly vráti ?
{15181}{15205}Áno .
{15404}{15452}Si v poriadku ?!
{15571}{15628}Ach! S-sorry!
{15629}{15659}Ach, hmm...
{15661}{15687}Tennnchi!
{15689}{15715}Tennnchi!
{15717}{15798}Tenchi? Nevidel som ho.
{15838}{15892}Kde je ?
{15909}{15929}Tennnchi!
{16001}{16062}Do riti ! Môe to by Ayeka?
{16080}{16290}Titulky by Macardur /macardur@hotmail.com/
{16329}{16444}Ešte som takto nespadla|v ivote.
{16447}{16495}Èo? Povedala si nieèo ?
{16497}{16541}Ani, nie.
{16544}{16599}No, tam je pekná|malá vyvıšenina.
{16601}{16640}Nechceš si to |ís tam pozrie ?
{16643}{16668}Áno.
{17133}{17169}Ako sa ti to páèi?
{17172}{17217}Nie je to úasnı vıh¾ad?
{17411}{17477}Èo-èo je zle ?
{17480}{17565}Tvoj dedko|mal asi pravdu.
{17582}{17698}Dnes to vyzerá|na perfektnı deò pre mòa.
{17701}{17740}Skutoène.
{17968}{18018}Tam ! Našla som a !
{18053}{18124}Kde ste sa vy dvaja schovávali|po celı ten èas ?!
{18125}{18187}Èo ? My sme boli|vonku na prechádzke.
{18189}{18274}Hej, ty,  Ako si sa mohla odvái|takto flirtova s Tenchim !
{18276}{18351}Flirtova ? Ty myslíš mòa ?|Èo a to napadlo ?
{18353}{18427}Take ty urèite nemáš|oòho záujem.
{18429}{18521}Sam-Samozrejme, e nie !|Ako môem ja ?
{18523}{18557}Nie, nikdy !
{18560}{18592}Ty si ale dobrá klamárka .
{18595}{18669}Èo tım chceš naznaèi ?|Nemôem to len tak necha!
{18686}{18725}Teraz, hneï, vy dve.
{18728}{18831}Musíme spravi opatrenia| a vzdiali ich.
{18833}{18893}Pán Tenchi,|prosím vypoèujte ma.
{18894}{18999}Príšera zvaná Ryoko|je zlá skrz na skrz.
{19001}{19062}Vdy bola.
{19065}{19132}No, domnievam sa, e máš pravdu.
{19133}{19164}Stalo sa to, áno.
{19167}{19253}Stalo sa to, keï som bola|ešte malá a krehká.
{19256}{19336}Jedného dòa, som sa hrala|na území...
{19337}{19373}Juraiskej krá¾ovskej rodiny.
{19376}{19410}Je to najkrajšie miesto ....
{19412}{19495}s mnostvom kvetov v rozkvete.
{19497}{19579}Hej, zabávaš sa, však ?
{19649}{19693}Kto si ?
{19696}{19756}Spravila si to úplne sama ?
{19758}{19780}Áno.
{19782}{19853}Hmm, máš docela talent .
{19880}{19963}Teraz je to celé moje !|Zbohom !
{19965}{20025}Ako si to predstavuješ.
{20027}{20120}Toto bolo moje prvé stretnutie|s Ryoko.
{20122}{20195}To je úplne inı príbeh|ne nám povedala Ryoko.
{20198}{20264}Chcel by som vedie,|ktorı príbeh je pravdivı.
{20265}{20337}Hej, chceš poveda,|e som ti nehovorila pravdu?
{20340}{20411}Dala si im znova|jeden z tvojich vymyslenıch príbehov ?
{20413}{20464}Tvoj príbeh je |úplne vymyslenı.
{20465}{20549}Èo ? Ja viem, e ty si bola|odsúdená za podvod ...
{20552}{20608}a ty chceš nazva|môj príbeh za vımysel ?!
{20609}{20672}Ale, prosím upokojte sa,|sleèna Ayeka.
{20674}{20702}Ach, Tenchi!
{20704}{20802}Táto hysterická enská|je na mòa zlá.
{20804}{20836}Hej, stoj !
{20837}{20897}Èo si myslíš, e robíš?|Nechaj ho tak!
{20899}{20937}Èo a tak rozrušilo ?
{20940}{21020}Nepovedala si náhodou, e |nemáš záujem o Tenchiho ?
{21021}{21128}Hej, Tenchi, pochvá¾me sa jej|ešte viac .
{21130}{21182}Ukáme jej našu lásku.
{21184}{21225}Skonèi to !
{21228}{21296}Ale, ale, nebuï plachı.
{21298}{21333}Hej, zbláznila si sa ?!
{21350}{21396}To staèí !
{21437}{21472}Pre všeobecnı mier ...
{21500}{21573}Skonèím to tu a navdy !
{21590}{21605}Skvele .
{21608}{21652}Poï, ak môeš .
{21742}{21904}No, a preèo nechceš bojova|a potom, èo ma zachrániš ?
{21956}{22015}Ehm, prepáè mi,|ale poèúvaš ma ?
{22017}{22061}Azaka, Kamidake,|otvor dvere !
{22064}{22144}Budeme bojova s Ryu-oh !
{22146}{22186}Poèkaj, prosím.
{22189}{22288}Ne zaèneš bojova, prosím|postaraj sa o mòa !
{22390}{22431}Poï sem, Ryo-ohki !
{22797}{22844}Vezmi nás.
{22925}{22963}Preèo mòa ?
{23513}{23576}Toto bude súboj na ivot a na smr,|Ryo-ohki.
{23609}{23731}Azaka, Kamidake, nenechajte|Ryoko nikdy ivú!
{23733}{23800}Násilie je zlé!
{23869}{23944}Hej, zastav to !|Poèuješ ma ?
{23945}{23988}Strie¾aj !|- Strie¾aj !
{24152}{24187}Strie¾aj ! Pa¾ba!
{24189}{24220}Vypusti ma !
{24221}{24270}Zomri v pokoji, Ayeka!
{24381}{24428}Ty zomri v pokoji,|sleèna Ryoko!
{24429}{24484}Umriem !|Umriem !
{24485}{24580}Prosím zastav to, Ayeka!
{24581}{24620}Ach!
{24621}{24667}Èo ty tu robíš ?
{25024}{25060}Cítiš sa lepšie ?
{25061}{25112}Ccc ! Ešte sme ani nezaèali.
{25115}{25147}Dos toho bolo !
{25149}{25211}Pán Tenchi,|èo tam robíte ?
{25259}{25284}Kde inde by mal by?
{25287}{25400}Tenchi a ja sme zviazanı|prísahou, e zomrieme spolu .
{25402}{25457}Èo ! Nie, my nie sme.|My nie sme.
{25498}{25522}Vy-vy ste ...
{25618}{25641}Ach, nie, pán Tenchi...
{25644}{25722}zviazanı s takouto enskou.
{25725}{25788}Nezostáva mi u niè.
{25791}{25835}Je to klamstvo, povedal som ti to !
{25837}{25890}Teraz, Tenchi, bojujme|proti zlej princeznej ...
{25892}{25928}s našou silou lásky.
{25930}{25953}Hovorím ti, zastav to !
{25955}{26007}No, pre tento krát ...
{26077}{26100}Skonèím to !
{26103}{26124}Sleèna Ryoko!
{26151}{26176}Pán Tenchi!
{26178}{26261}Poïme všetci traja spolu|do pekla !
{26300}{26357}No, myslím, e ste zabudli na mòa.
{26602}{26644}Prosím, skonèi to,|sleèna Ayeka!
{26647}{26742}Sleèna Ayeka|stratila svoju krehkos !
{26745}{26780}Stratila rozum !
{28229}{28303}No, nikto sa nezranil,|a to je všetko èo sa stalo.
{28305}{28398}Môeš s nami zosta|tak dlho ako chceš.
{28401}{28476}Váime si toho, páni.
{28477}{28522}Berieme vašu ponuku s vïakou.
{28524}{28595}Skutoène ma hnevá ako rastie|poèet takıchto parazitov.
{28597}{28649}Je to tvoja chyba|a ty to dobre vieš.
{28652}{28783}Hej, môj Ryo-ohki bol|tie znièenı ?
{28785}{28886}Povedala som vám,|aby ste bojovali neskôr !
{28888}{28951}Mimochodom,|kde je sleèna Ayeka?
{28954}{29010}No, ona je ešte stále v šoku ...
{29012}{29047}po vzhliadnutí|horiacej lodi Ryu-oh.
{29097}{29121}Sleèna Ayeka?
{29124}{29175}Áno.
{29444}{29531}No, priniesol som ti obed.
{29574}{29632}Mono by som mal poèka.
{29633}{29679}Áno.
{29681}{29717}V poriadku, potom.|sa vrátim neskôr...
{29719}{29751}s trochou horúcej polievky,|alebo s nieèím podobnım ...
{29753}{29789}ako tvoje veèerné obèerstvenie .
{29790}{29852}Medzitım,|si odpoèiò.
{30150}{30180}No, je to OK.
{30182}{30294}Predpokladám, e si dám|dlhú dovolenku .
{32970}{32992}Tenchi Muyo!
{32994}{33054}Ïalší u štvrtı|prisahovalec ...
{33056}{33107}je najmladšia sestra Ayeky,|Sasami!
{33109}{33180}Krásna a zlatá, Sasami prišla|sem sa pozrie na Ayeku ...
{33181}{33233}Ktorá chıba vo vesmíre.
{33236}{33283}Wou ! Èo je to za|maèaciu príšeru ?
{33285}{33328}Èo ? Ryo-ohki ?!
{33331}{33395}Myslím, e to bolo meno|Ryokinej lode.
{33397}{33459}Ïalšia epizóda je :|Nepotrebujeme trápenie !
{33461}{33511}Je to nesporne zlaté !
