{310}{360}Tenchi Muyo !
{1700}{2000}Titulky by Macardur /macardur@hotmail.com/|02/2003
{2450}{2486}Odchádzam!
{2683}{2761}Oh, Tenchi,|nie je to krása?
{2763}{2854}Je to ako kadodennı bál.
{2857}{2926}Túim po tom, aby dni mohli|by ako tento ...
{2929}{2998}kedyko¾vek ...Tenchi.
{3543}{3637}Domnievam sa, e takéto dni by|mohli trva navdy ...
{3639}{3710}nikdy nekonèiaci bál.
{3713}{3769}Potom to celé zaèalo.
{4050}{4140}Netreba o tom hovori !
{4740}{4787}Èooo je to?
{5013}{5104}Som si istı, e to pristálo |niekde blízko.
{5155}{5178}Èo je to?
{5439}{5486}Hej! Si v poriadku?
{5489}{5510}No tak, poï!
{5587}{5629}Zápach alkoholu?
{5631}{5664}Áno! Voda!
{5855}{5904}No, dobre.
{5926}{6029}Umm ... Si zranená?
{6037}{6065}Nie! Kto si?
{6084}{6138}Ah, moje meno|je Tenchi Masaki.
{6140}{6194}Èo do pekla je toto?!
{6222}{6251}Ah! Mám strach z toho!
{6289}{6303}Ja som  Ryoko!
{6305}{6350}Vesmírni piráti|sú mi v pätách!
{6352}{6398}Prosím! Ja a prosím! Pomô mi!
{6400}{6480}Poèkaj ...|Ja tomu celému nerozumiem!
{6519}{6541}Èo?
{6543}{6579}Mám strach!
{6588}{6616}H-hej!
{6619}{6682}Prosím! Ve¾mi prosím!|Zachráò ma!
{6684}{6724}Hej ! Ah...huh?
{6857}{6927}To je jeden z nich!|To je vesmírny pirát!
{6937}{6972}Ale-e, ja tomu stále nerozumiem !
{7012}{7034}Upss !
{7094}{7124}Vypadnime z tadeto !
{7562}{7668}Preèo ? Preèo by som mal|by v problémoch ?
{7873}{7920}Je to ve¾ká vzdialenos, |príchod je vèas ...
{7922}{7992}ale je to trochu ve¾a .
{8154}{8184}Ah! Slepá ulièka !
{8187}{8227}Èo budeme robi ?
{8269}{8350}Hej ! Èo si povedala ?|Povedz aj mne !
{8353}{8401}Prosímm poèúvaj ma !
{8403}{8461}Nemám ani tušenie|èo je tvoj problém, ...
{8463}{8516}ale viem urèite, e to vieš vyrieši|aj civilizovanejšie.
{8518}{8568}T-y pozri, môeme si porozumie|lepšie navzájom ...
{8570}{8609}Potrebujeme èas,|porozpráva si  o tom všetkom.
{8611}{8675}Nie ! On je divokı zloèinec !
{8677}{8710}Ani sa nepokúšaj|hovori s ním!
{8713}{8748}To snáï nie !
{8750}{8821}Toto je osud, |ktorı musíme my dvaja zdiela.
{8824}{8897}S¾úbili sme si, e zomrieme spolu,|pamätáš ?
{8905}{8940}Nie, ja si nepamätám|takı s¾ub! Nikdy !
{8941}{9015}Staneme sa jasnımi hviezdami|na nebi, ty a ja.
{9017}{9052}Ty si robíš srandu !!
{9408}{9460}Hmm ! Nie je schopnı sa postavi, |všake?
{9468}{9484}On urèite môe !
{9907}{9929}Môeme teraz ís.
{9931}{9972}Ah, jasne.
{10071}{10102}Hej, Nobuyuki.
{10105}{10144}Èo, tati?
{10147}{10237}Tenchi prichádza ve¾mi neskoro|dnes domov, však?
{10239}{10270}No, musel by zaneprázdnenı ...
{10273}{10308}balením dievèat|na ulici, alebo tak nejak.
{10310}{10389}Nie ! On nie je ako ty !
{10404}{10453}Myslíš na mòa,|však, tati ?
{10486}{10533}Je pravda, e|sa uvo¾nil ...
{10536}{10585}trochu viac v poslednıch dòoch.
{10587}{10647}Mono by som mu mal vynada !
{10649}{10700}Hmm. Zdá sa, e|prichádza domov !
{10755}{10838}Kde si sa túlal,|tak neskoro veèer ?
{10841}{10888}Túla sa neskoro|je len prvı krok ...
{10890}{10932}smerom|mladistvej delikvencii --hmm?
{10989}{11016}Ahoj !
{11083}{11152}Kto je táto pôvabná|mladá sleèna s tebou ?
{11231}{11278}Hmm. Vyzeráš |ve¾mi rozrušenı.
{11280}{11325}Vy dvaja ste utiekli, |alebo tak nejak ?
{11327}{11368}Ah, ako to viete ?
{11371}{11416}Nerobil by som niè také.
{11436}{11493}Tak o èom je toto celé ?
{11496}{11545}Tak vy nie ste |zo zeme ?
{11548}{11631}Ano, bola som napadnutá|divokım vesmírnym pirátom...
{11634}{11665}poèas mojej cesty.
{11667}{11713}Zúfalo som sa pokúšala|uniknú ...
{11715}{11751}ale moja loï|bola stále...
{11754}{11798}dobiehaná druhou loïou|a padla priamo dolu ...
{11800}{11830}na túto planétu.
{11833}{11893}Urèite neèakáš, e|takı obyèajnı ¾udia ako sme my ...
{11896}{11926}uveria tvojmu príbehu !
{11994}{12063}Vy ste prešli cez|obrovské utrpenie ...
{12065}{12097}mladá sleèna z vesmíru.
{12099}{12140}Také nebezpeèie !
{12193}{12214}Hej, Tenchi!
{12217}{12252}Preèo tu len tak posedávaš ?
{12255}{12299}Preèo jej neponúkneš zopár|cukríkov, alebo tak nejak ?
{12301}{12327}Poèkaj !
{12329}{12401}Ako môeš uveri jej príbehu|tak ¾ahko?
{12403}{12453}Povaujem jej príbeh|za ove¾a viac pravdepodobnı...
{12455}{12529}ako príbeh o tom, e si sa zoznámil|s takım peknım dievèaom.
{12531}{12556}Jaj, vidím. 
{12570}{12605}Muselo by ve¾mi chladno
{12618}{12645}vo vesmíre|túto roènú dobu.
{12647}{12708}Tu máte trochu|horúceho èaju.
{12711}{12755}Ah, aké zlaté od vás
{12757}{12827}rozpráva tak milo|s cudzincom z vesmíru.
{12829}{12959}Avšak ak tu zostanem|budem pre vás znamena len problémy.
{12961}{13006}Vesmírny pirát|sa vráti pre mòa !
{13009}{13044}Som si tım istá !
{13046}{13149}Ubezpeèím vás, mladá sleèna !|My sme na vašej strane.
{13151}{13181}Ale ...
{13194}{13218}Nemusíte sa teraz|nièoho obáva.
{13221}{13265}My vás ochránime.|To vám s¾ubujem.
{13267}{13335}Ïakujem vám ve¾mi pekne|ctihodnı otèe !
{13337}{13393}Vy ste ma nazvali otcom ?
{13395}{13481}Áno, ja budem vaša|oddaná dcéra.
{13483}{13537}Ah, Tenchi, máš pre seba|úasnú nevestu.
{13539}{13575}Èoo?!
{13577}{13669}Tvoja mama v nebi |musí by teraz na teba hrdá.
{13681}{13709}Otec!
{13722}{13750}Moja dcéra!
{14688}{14772}Sakra ! Toto mono robia|proti tajfúnom...
{14775}{14822}ale urèite nie proti|vesmírnym pirátom.
{14825}{14893}Myslím, e len|mrháme našim èasom.
{14895}{14920}Prestaò sa rozèulova|a pracuj tvrdšie.
{14922}{14954}Nevieš èo som hovoril ...
{14956}{15026}"Cena uspokojenia|je veèná pozornos"?
{15028}{15113}Fajn, myslím, e pôjdem teraz|naspä do svätyne.
{15116}{15160}Zavolajte ma ak sa nieèo bude dia.
{15162}{15226}Ah, dobrú noc dedko !
{15228}{15274}Mono by sme sa mali teraz|vráti dnu.
{15276}{15301}Jasne.
{15425}{15469}Ah! Mám strach.
{15471}{15499}Dnes veèer sa neboj.
{15501}{15590}Budem celú noc na strái|a ochránim a.
{15766}{15888}Áno ! Tam ! No tak, |dobré !
{15889}{15906}Ešte raz ! Blišie !
{15909}{15978}Áno ! Tam, tam !|To je ono !
{15980}{16057}Ah ! Nie, nie ! Nie !
{16059}{16091}Èo to robíš ?
{16093}{16125}Idem do druhej izby.
{16127}{16153}Preèo ?
{16156}{16226}Pretoe sa nemôem uèi|v takom hluku !
{16229}{16305}Aha ! Tak ty ma chceš opusti,|všake?!
{16321}{16344}Hej ! Nechaj ma tak !
{16346}{16411}Nechoï !|Nenechávaj ma tu samu !
{16413}{16461}O èom to hovoríš ?
{16463}{16527}Fajn, pozri , Tenchi...
{16530}{16581}Nechaj ma tak !
{16698}{16721}Áno ?
{16934}{16981}On-On je tu !
{16984}{17065}Ach! A ja som ti chcela |da dobrú noc.
{17067}{17125}Kto to môe by |tak neskoro ?
{17127}{17177}Ty krava !|To je vesmírny pirát !
{17180}{17233}Ah! To je dobré .|To je fajn .
{17235}{17316}Hej ! Ty si naòho úplne zabudla ?
{18027}{18061}Poïme tadeto !
{18063}{18095}Kam ? Kade ?
{18581}{18610}Èo sa deje ?
{18612}{18665}Takı ve¾kı hluk|v noci !
{18667}{18713}Dedko !
{18942}{18984}Ach ! To je ale otrava .
{19127}{19149}Dedko !
{19151}{19193}Len to nechajte na mòa !
{19747}{19781}Super !
{19802}{19820}Skvele, dedko !
{20054}{20115}Vzdaj sa,|vesmírna pirátka, Ryoko!
{20118}{20170}Tvoja hrozné èiny|skonèia tu a teraz !
{20172}{20236}Èo ? Hej, poèkaj !
{20244}{20295}Myslel som si, e vy ste|vesmírny pirát !
{20297}{20329}Ja som prvotriedny|detektív Mihoshi...
{20331}{20366}z galaktickej polícii!
{20369}{20414}Som na dlhej ceste|k tejto planéte ...
{20417}{20462}v prenasledovaní Ryoko,|smutne známej kriminálnièky ...
{20465}{20497}h¾adanej po celom |vesmíre.
{20499}{20606}Klame ! Vyzerám ako|nejaké neposlušné dievèa ?!
{20608}{20682}Tak ty máš takı dojem|aj napriek tomu, e nie je dôkaz!
{20685}{20730}Samozrejme je dôkaz.
{20776}{20848}Tu je !!|Ah, nie ! To nie !
{20851}{20894}Tu ! Tento jeden ! |To taktie nie je on.
{20897}{20968}Ah ! Kde je teraz ?
{20970}{20994}Nie ani tento nie !
{20997}{21052}Hmm! To je divné
{21121}{21140}eby som zabudla ...
{21142}{21191}Tu ! Našla som ho !
{21240}{21266}Tu !
{21269}{21338}Tu je moje I.D.
{21413}{21493}A vidíte? Toto je |zatykaè!
{21641}{21710}Vidím, e u viete|kto som v skutoènosti.
{21712}{21759}Vidíš. Mala som |strašnú opicu ...
{21762}{21827}keï som utekala|pred touto sprostou policajtkou.
{21829}{21875}Inak,|by som v ivote ...
{21877}{21932}nespravila takú chybu,|urèite nie ja.
{21934}{22028}Fajn, a ako vás môem |upiec ?
{22092}{22138}Ne-Nehıbte sa, prosím.
{22140}{22226}Ináè vás strelím.|A bude to bolie!
{22274}{22312}No skús !
{22677}{22707}Povedala som ti !
{22709}{22804}Som ve¾kı súper pre|takého slabého lovca ako si ty!
{22818}{22870}Prišiel èas na odplatu !
{23038}{23088}Ty mi neunikneš !
{23117}{23182}Ukázalo sa to na vlastne celkom|hluènı prípad.
{23485}{23542}Hej, nemôeš nieèo s tım urobi ?
{23544}{23578}Si policajtka, však ?
{23580}{23644}Vlastne áno ! Ja som , ale...
{23691}{23740}mám strach !
{23748}{23772}To nie je od nej pekné!
{23928}{23950}Au!
{23952}{23974}Rıchlo !
{23976}{24041}Poèkaj ! Nemôem sa postavi !
{24147}{24202}Pripravte sa na smr !
{24204}{24241}Do riti ! 
{24338}{24373}Poï ! Som pripravenı !
{25032}{25073}Ah! Zaèína to by skutoène zábavné !
{25124}{25194}Nikdy som a nechcela zrani|po tom všetko.
{25196}{25258}Vidíš,|ja som a len provokovala.
{25260}{25337}Tak sa vzdávaš ?
{25340}{25389}No, ja to môem spravi|pre teba.
{25392}{25499}Poèkaj. Preèítam ti najprv|tvoje práva.
{25530}{25585}"Galaktické policajné právo,|paragraf 2546, strana 937...
{25587}{25628}" z novelizovaného oddielu .
{25631}{25701}"Podozrivı má právo|nevypoveda ...
{25703}{25780}" èoko¾vek povie môe|by pouité proti nemu ...
{25788}{25828}a má právo na právneho zástupcu --"
{25836}{25852}Ach!
{25932}{25957}A?
{25959}{26050}Ja--Ja si myslím, e u viem|právo zpamäti.
{26052}{26177}No, Galaktické policajné právo|paragraf 2564 -- Ups.
{26179}{26281}Bol to paragraf 2456 alebo 2654?
{26283}{26349}Nie, nie. 2464.
{26352}{26404}Nie to tie nie je on !
{26412}{26465}Ach! Èo budem robi?!
{26467}{26510}2446? Nie!
{26513}{26587}Som zmätená !
{26589}{26663}No, nejako sa mi |ve¾mi zapáèilo toto miesto.
{26665}{26725}Mono ti môem spravi láskavos|a zosta tu nachví¾u.
{26727}{26774}Èo ?!
{26775}{26825}Si šastnı, však?
{26833}{26842}Neblázni !
{26844}{26929}Keï si ma prvıkrát zachránil...
{26932}{26969}bol si skutoène udatnı.
{27306}{27404}Ach! A tá zábava|poslednú noc !
{27406}{27481}A pre mòa to¾ko otravy,|vlastne!
{27523}{27580}Milujem toto jedlo !
{27588}{27638}Špeciálny recept|od mojej zosnulej manelky.
{27641}{27690}Daj si ešte !
{27693}{27747}Vau! Ïakujem.
{27749}{27819}Hej! Ako to, e s nami|teraz raòajkuješ?
{27822}{27852}Ty máš ale iné nervy !
{27855}{27904}Mám to poveda aj ja tebe ?
{27986}{28004}Sorry !
{28007}{28061}Moja loï je totálne znièená ...
{28074}{28146}a nemám sa ako |vráti domov.
{28179}{28247}Ach, nie.|Teraz nám tu neplaè.
{28249}{28313}Ach to je dos zle, hlavne|preto, e som oèakávala ...
{28315}{28361}e sa ti u koneène vzdám .
{28412}{28488}Galaktické policajné právo,|paragraf 2,500...
{28490}{28539}Nie ! Nemôem si spomenú !
{28626}{28674}Èo chceš teraz robi ?
{28676}{28756}Nemohla by som prosím|zosta tu nachví¾u ?
{28764}{28860}Nikoho iného nepoznám|na tejto planéte.
{28862}{28921}Hmm. To nie je zlı nápad
{28923}{28969}Vau ! To rozjasní naše ivoty ...
{28971}{29019}ma dievèatá|v tejto chlapskej rodine.
{29063}{29159}No, môem sa ešte nieèo spıta ?
{29162}{29218}Èo ?
{29220}{29292}Môem dosta ešte jednu porciu ?
{29628}{29682}Tak tu si Tenchi !!
{29685}{29752}Kto si myslíš, e je za toto|všetko zodpovednı ?
{29754}{29801}Neobauj sa sám|s takımi triviálnymi úlohami.
{29803}{29834}Skutoène !
{29836}{29881}Skutoène chceš s nami tu|zosta?
{29883}{29945}Ach, ja chcem,|ak a to urobí šastnım.
{29948}{29974}Hej --
{30036}{30084}Nepotrebujeme o tom diskutova.
{32993}{33049}Ako vidíte,|zaèal zmätok!
{33052}{33137}Tretí votrelec|sa objaví nabudúce --
{33140}{33184}Vau! Èo to je za prekvapenie !
{33187}{33251}Najznámejšia princezná|v celom vesmíre !
{33253}{33312}Ale niekto má zlú povahu|ako Ryoko...
{33315}{33400}tak zaènú navzájom|bojova vo vesmíre !
{33403}{33448}Ïalšia epizóda je :|Nepotrebujeme princeznú!
{33450}{33523}Pekná a pohodová dovolenka|pre princeznú.
{33525}{33588}Neskutoèná zábava !
