{1}{100}- titulky - GeXeS -
{148}{249}Tak dlouho, jak jen si pamatuji,|poøád jen prší.
{305}{450}Legendy vyprávìjí o rozlehlıch kontinentech a|obrovskıch mìstech pøed katastrofou,
{486}{546}ale to vše je pouze|vybledlá sláva minulosti.
{617}{717}Naši pøedkové, pøedpovídající katastrofu,|uprchli na ostrov Sisil v Pacifiku
{742}{841}a postavili další Noemovu archu,|sobìstaèné mìsto.
{894}{995}Mìsto ECOBAN, které se íví neèistotami a špínou.
{1067}{1153}Lodì tisícù uprchlíkù pøijídìly,
{1181}{1248}ale ECOBAN nedovolil
{1278}{1392}vstup zamoøenım lidem|do mìsta.
{2995}{3042}Bezpeènost dìlníkù na spodní palubì|je ohroena.
{3043}{3082}Poaduji okamité zastavení prací!
{3084}{3169}Koho to zajímá? Jsou to jen zvíøata|na práci, ne na mazlení!
{3787}{3816}Zatracenì!
{3818}{3869}Nemají cenu ani toho jidla,|které jedí!
{4379}{4419}Je to jen ztráta èasu.
{4421}{4473}Mìli bychom to všechno spálit na prach!
{4493}{4565}Pane! Prosím, pomozte nám, rychle!
{4566}{4615}Všichni tam zemøou!
{4617}{4687}Nièíte drahé vybavení.
{4690}{4721}Odpojte palubu!
{4724}{4784}Coe?|Ani za nic!
{4789}{4846}Dole jsou poøád lidé!
{4983}{5034}Nepamatuji si,|e bych se ptal na váš názor.
{5038}{5079}Pøehoïte ten vypínaè!
{5081}{5117}Jen pøes mou mrtvolu!
{5122}{5165}Pøes vaši mrtvolu, hm?
{5170}{5240}Jay, dej mu, co si pøeje.
{5266}{5321}- To není moje práce, pane.|- Coe?
{5561}{5605}Odpojte to, rychle!
{6210}{6308}Vaší prací je|poslouchat moje rozkazy!
{6319}{6365}Vrate se okamitì na ECOBAN!
{8000}{8100}Wonderful Days
{8500}{8600}--pøeklad Sinuhet a Kubys, finální úpravy GeXeS--
{8610}{8710}--z 2CD verze na 1CD verzi pøedìlal--|                  Corvik
{11150}{11303}-reie-|Kim Moon-syang
{11458}{11503}Co si poboèník myslí?
{11556}{11618}Zkouší snad vyprovokovat povstání?
{11624}{11742}Nebo snad skuteènì zkouší|zmasakrovat Marriánce?
{11767}{11832}On pouze dìlá|co mùe, aby zvıšil...
{11841}{11896}...zneèištìní pro systémy DELOS.
{11927}{12003}Nicménì je pravda,|e jeho metody jsou nebezpeèné.
{12021}{12089}Podám návrh vládì,|aby zakroèila.
{12094}{12129}Z toho nevzejde nic dobrého.
{12130}{12239}Pro nì jsou Marriánci jen|o trochu víc ne hmyz.
{12260}{12318}Tys tak vymìkla, Jay!
{12338}{12394}ECOBAN je v krizové situaci.
{12419}{12514}Ty víš, e slitování|je zakázáno...
{12538}{12588}Stejnì jako je dùleité uchování|našeho ECOBANU.
{12615}{12704}Uvolni se! Pojïme dolù,|uívat si oslavy stého vıroèí.
{13493}{13537}Poøád nad tím dumáš?
{13562}{13611}Jsem jen unavená...
{13662}{13733}Víš co?|Pøevelím tì ke zdejším hlídkám.
{13742}{13810}Tady uvnitø nejsou vìci tak tìké.
{15531}{15563}Co je to?
{15566}{15608}Poplach, vetøelec v kontrolním centru!
{15610}{15657}- Coe?|- Bezpeènostní snímaè byl zapnut.
{15671}{15727}Pošlete tam okamitì hlídku!
{15730}{15771}Jsem na cestì.
{15920}{15978}Hlídka 1 do centra DELOS!
{16813}{16844}Tady jsi!
{16846}{16892}Nìkdo se naboural na plošinu, pane.
{16893}{16949}- Nìjaká další plošina?|- Ne, pane.
{16962}{17005}Pobìí do stran.
{17010}{17061}Zapnìte ventilátory v oblasti 3!
{17113}{17164}Ano, tak je to správnì.
{17201}{17263}Alpha na 330, Bravo na 348!
{17266}{17308}Charlie na 353!
{17874}{17904}Támhle!
{18038}{18132}Cíl spatøen v zónì 3.|Alpha, pøesun na 33!
{19996}{20061}Ztratili jsme jeho stopu, pane.
{20065}{20113}Tady taky nic, pane!
{20461}{20529}Kontrolní místnost, zastavte ventilátor 31!
{20582}{20642}To je práce Dr. Noaha...
{20741}{20825}Kontrolní místnost, tady Jay.|Ukate mi cestu k muzeu minulosti.
{21974}{22064}Co teï, ta krysa má snad køídla?!
{23229}{23269}Jay, nahlas svou pozici!
{23271}{23344}Jsem v muzeu minulosti.|Myslím, e je tady.
{24527}{24575}Jay!|Jay, ohlas se!
{25727}{25767}Jay, jsi v poøádku?
{25770}{25799}Ano...
{25806}{25845}Co se stalo?
{25852}{25917}Promiòte, skoro jsem ho dostala...
{25926}{25975}Jak jen se mohl dostat tak daleko?
{26032}{26109}Povaovali jsme naši ostrahu|za neproniknutelnou,
{26133}{26201}...ale dnes... DELOS Centrum,|nejdùleitejší z míst, bylo infiltrováno!
{26204}{26271}A èlovìk, kterı to udìlal,|unikl. Zmizel!
{26295}{26377}Zjevnì znal systém DELOS|jako svou vlastní ruku.
{26391}{26489}Jen o nìkolik minut déle a pøipojil|by se k hlavnímu poèítaèi.
{26502}{26562}Co by mu umonilo|vypuštìní energie z DELOSU.
{26588}{26635}Vypuštìní energie z DELOSU?
{26638}{26673}Ano, pøesnì tak!
{26678}{26749}Jako porušení pøed deseti lety.
{26762}{26889}Myslíte, e je poøád naivu?|Dr. Noah?
{26898}{26949}O tom není dùvod pochybovat.
{26962}{27059}Ti hloupí Marriánci by nikdy|nedokázali rozluštit náš systém,
{27064}{27113}a to i kdybychom jim k nìmu dali plány.
{27134}{27202}Všichni známe naši souèasnou situaci.
{27211}{27285}Úroveò energie DELOSU|neustále klesá...
{27298}{27392}Proto ECOBAN musel zpomalit|svùj rùst.
{27428}{27501}Pokud toho mue necháme naivu,
{27506}{27551}bude neustále napadat náš systém|a pùsobit škody.
{27574}{27641}Nemùeme si nadále dovolit|odkládat naše rozhodnutí.
{27670}{27773}Musíme zapálit olejová pole
{27781}{27837}a rozšíøit tak zneèištìnou oblast!
{27864}{27971}To samo o sobì nám dá energii|minimálnì na dalších 50 let.
{27999}{28080}Na tom jsme se pøeci dohodli|u pøed deseti lety.
{28089}{28181}Není ádnı další dùvod, proè bychom mìli|své plány pro operaci Marr odkládat.
{28213}{28319}Zapálit olejová pole,|jen abychom chytili nìkolik krys?
{28335}{28394}Dobrá, jedna krysa se dostala dovnitø,|ale nakonec pøece nic nedokázala.
{28396}{28446}Naše bezpeènost je spolehlivá.
{28466}{28516}Moná, e Marriánci nejsou|nic víc ne zvíøata...
{28520}{28575}Ale my je potøebujeme na práci.
{28583}{28645}Pøíliš mnoho útisku povede ke vzpouøe.
{28668}{28715}Více zneèištìní, více energie!
{28718}{28783}To je naším hlavním cílem.
{28798}{28855}Ano, dostávat více energie...
{28862}{28946}Musíme rošíøit zneèištìnou oblast.
{28965}{29021}Ale pokud zabijeme Marriánce,|kdo bude dìlat všechnu práci?
{29034}{29081}A i kdy je to nepravdìpodobné,
{29084}{29134}co kdyby došlo ke vzpouøe?
{29154}{29246}Marriánci pøevyšují poèetnì|ECOBAN deset ku jedné.
{29259}{29360}Jsi stejnì slabı a neschopnı|jako ta tvoje ostraha.
{29364}{29430}Pokud navıšení zneèištìní,
{29432}{29482}...nebudeme potøebovat ani olejová pole,|ani dìlníky.
{29525}{29631}Nejdøíve zesilte ostrahu na Marru|a na ECOBANU.
{29638}{29700}Pak najdìte toho narušitele|a zjistìte vše o jeho minulosti.
{29704}{29775}Tato záleitost je pro nás velmi dùleitá.
{30014}{30043}Poboèníku...
{30062}{30128}Pøipravte se k akci.|Jen pro jistotu.
{30422}{30515}Copak nedokáeš udìlat tak jednoduchou vìc,|ani bys zpùsobil problémy?
{30518}{30607}Kdy jsi tak chytrı, bì si to udìlat sám, starouši!
{30616}{30681}Tím, e jsi dnes zapnul alarm,
{30683}{30728}jsi zpùsobil zdvojnásobení ostrahy!
{30738}{30794}Teï je nemoné se dostat dovnitø
{30798}{30839}a zastavit systém DELOS.
{30856}{30893}Podej mi ty informace!
{30941}{31006}Tak se na to podíváme...
{31018}{31097}Copak je nového|v tom starém skalním mìstì?
{31290}{31363}Hmm... take DELOSU dochází energie, chápu.
{31367}{31426}Zneèištìní zaèíná mizet...
{31438}{31513}Systému dochází dech.
{31560}{31638}Kdy se systém DELOS zastaví,|co se pak stane s ECOBANEM?
{31655}{31701}Zase uvidíme modrou oblohu!
{31702}{31791}Nemyslím nebe, myslím ECOBAN.
{31827}{31891}Hmm, nebude se jim to sice líbit,
{31893}{31971}ale budou muset zase pouívat|solární energii, jako ve 21. století.
{31979}{32038}ECOBAN bude obrovskı nesmysl.
{32042}{32112}Pak budou muset zaèít pracovat venku|na denním svìtle,
{32114}{32165}bok po boku s Marriánci.
{32167}{32204}Bok po boku?
{32249}{32328}To nás radši nejdøív zabijí.
{32330}{32370}Kde je sakra Woody?
{32392}{32477}Jo... potkal jsem ji tam.
{32485}{32520}Koho?
{32535}{32575}Starou známou.
{32583}{32677}Staøí známí jsou jen pro ijící lidi.
{32682}{32727}Ty jsi mrtvı mu.|Zapomeò na to!
{32738}{32810}Pøemıslej radši nad tím|jak se dostat znova dovnitø
{32813}{32887}a jak zastavit systém DELOS.
{32898}{32954}A zapomeò na ten svùj kluzák...
{32960}{33012}To je pøíliš nebezpeèné.
{33117}{33166}Nechte ho projet.
{33374}{33425}Hej, dej to dál!
{33481}{33556}A ty!|Pøestaò s tou pohøební hudbou!
{33558}{33596}Neznáš nìco veselejšího?
{33822}{33877}Woody, dáš si práska?
{33881}{33925}Je to jemòouèkı!
{34090}{34121}Sakra, horkı horkı horkı!
{34674}{34718}Ha... Shua!
{34746}{34804}Proè jsi tady?
{34882}{34926}Woody, pojeï!
{34965}{35011}Shua!
{35197}{35258}Nesnáším ho, toho odpadlíka z ECOBANU!
{35261}{35344}Kdyby nebylo Woodyho,|tak bych mu urazil palici.
{35414}{35489}Hej Joe, nevidìl jsi nìkde moji vrtuli?
{35511}{35543}Tohle?
{35546}{35628}Dìláš si snad srandu?|Takovou tu malou.
{35652}{35712}Øíkal jsi, e tohle potøebuješ?
{35776}{35871}Brzdi. Nejdøív se s tìmi grázly scházíš|a teï ještì navíc kradeš?
{35875}{35975}Já to neukradl.|Já jsem to... našel.
{35977}{36049}Øíkal jsi,|e to potøebuješ pro svùj kluzák...
{36099}{36150}U se s nimi nescházej.
{36154}{36213}Je to moc nebezpeèné, jasné?
{36342}{36385}Dej mi harmoniku.
{36481}{36515}Hej, poèkej!
{36536}{36589}To je skvìlı. Co je to?
{36590}{36633}Náramek.
{36636}{36682}Kde jsi ho dostal?
{36685}{36727}Do toho ti nic není, chlapèe.
{36730}{36780}Kdo je to?
{37267}{37353}Dr. Noah øíká, e obloha je modrá.
{37356}{37423}e lidé kdysi øíkali "modré jako nebe".
{37439}{37551}A na místì jménem Gibraltar|je modré nebe i moøe.
{37553}{37606}Pøedstav si to!
{37906}{37951}Pojï se mnou!
{37953}{37986}Kam?
{38346}{38395}Sem se nesmí.
{38398}{38449}Pojïme zpátky!
{38450}{38485}Bojím se...
{38488}{38554}Neboj se!
{38556}{38626}Jen zavøi oèi|a dr se mé ruky.
{38631}{38689}Ukáu ti nìco nádherného!
{39014}{39064}A teï otevøi oèi!
{39171}{39250}Páni, to je nádhera!
{39290}{39352}Ale jak jsi o tomhle vìdìl?
{39355}{39406}Dr. Noah mi o tom øekl.
{39410}{39502}Øíkal taky, e na Gibraltaru|mùeš tohle vidìt kadı den!
{39526}{39597}Jay, slib mi,|e tam jednou pojedeme spoleènì!
{39990}{40045}Bylo to tak nádherné,|tak oslepující...
{40055}{40125}Nazvali jsme to našim Dnem Zázrakù.
{40142}{40212}Ale netrvalo to dlouho.
{40230}{40284}Ztratilo se to za temnımi mraky noci.
{40291}{40347}A od toho dne jsem to znovu nevidìla.
{40433}{40521}Èí je tato zemì?
{40522}{40647}Kdo se stará o pùdu|a kdo postavil mìsto?
{40650}{40780}Èí krev a pot tekly pøi stavbì Marru?
{40782}{40853}Byla to krev ECOBANU? Ne!
{40854}{40887}Byla to naše krev!
{40890}{40937}Hej, zaèíná to bıt drsné!
{40939}{40984}Urèitì dojde ke vzpouøe.
{40987}{41073}To tìko. Mùj bratr Shua by o tom vìdìl
{41076}{41130}a øekl by mi to.
{41139}{41196}Tse, on je z ECOBANU,
{41199}{41283}nemùe bıt tvùj bratr.
{41286}{41341}Je to jenom hloupı blázen!
{41344}{41388}Je to mùj bratr!|Proè by mìl bıt blázen?
{41390}{41466}Poøád vaní o nìjakém Gibraltaru...
{41468}{41504}Nic takového na svìtì neexistuje!
{41507}{41578}Musíš ít tady.
{41582}{41640}A já tì nauèím,|jak se stát bojovníkem
{41689}{41731}Woody! Kam to...?
{41845}{41901}- Woody!|- Pospìšte si!
{42078}{42141}Takhle brzy ráno a u se bouøí...
{42145}{42207}Zdá se, e dnes u nebudu mít|ádnou další práci.
{42210}{42260}Nevidìl jste náhodou dneska Woodyho?
{42264}{42366}Woody? Myslím, e jsem ho vidìl|s tím skøetem.
{42368}{42425}Jak jen se jmenuje?
{42436}{42500}Podal bys mi tamto?
{42578}{42642}Pøijídìjí!|Rychle na køiovatku!
{43626}{43673}Co to sakra dìláš?
{43674}{43725}- Zbláznil ses?|- P-Poèkej chvilku...
{43738}{43779}Co to sakra...
{43815}{43849}Hej! Hej!
{44364}{44464}Jestli uvidíte Woodyho,|øeknìte mu, aby šel domù.
{44640}{44751}Jay, na trišti jsou povstalci.|Vra se zpátky!
{44780}{44824}Táhni k èertu!
{45273}{45322}Jay! Jsi v poøádku?
{45325}{45372}Jay? |Odpovìz!
{49481}{49521}Shua?
{49540}{49575}Ty jsi Shua, musíš bıt!
{49652}{49718}Poslouchej, na území Marru pro tebe není bezpeèno.
{49766}{49822}Myslela jsem, e jsi mrtvı!
{49890}{49968}Shua, kterého jsi znala, je mrtvı.
{50006}{50073}Teï jsme ty a já nepøátelé.
{50093}{50182}Marriánci nejsou mımi nepøáteli.
{50185}{50254}Tak to vidíš ty...|Marriánci to vidí jinak.
{50310}{50365}Sakra!
{50421}{50466}Vlezlí magoøi...
{50477}{50516}Musím tì schovat.
{50567}{50661}Schody by mìly bıt širší a pøístupnìjší!
{50662}{50725}Tohle je jak horolezectví!
{50728}{50806}A hele, Shua! Tady jsi!
{50867}{50908}Boss tì chce vidìt.
{50911}{51021}Musíme si naplánovat strategii|pro naši zítøejší misi.
{51090}{51169}Bude to drsnı!|Chystáme se napadnout stanovištì ECOBANU.
{51346}{51464}Jsem tak šastná, e jsi naivu, Shuo!
{51512}{51555}Ani nevíš, jak!
{51577}{51650}Chybìl jsi mi,|tak jako tobì chybí
{51672}{51718}ta tvá modrá obloha...
{52140}{52233}Odjeï zpátky.|A u se sem nikdy nevracej.
{53104}{53158}Helen, jestli neumøu hned...
{53174}{53239}...tak vybuchnu za chvilièku!
{53242}{53282}Probuï se.
{53285}{53328}Je dvakrát vyšší ne ty!
{53331}{53385}- Nenu mì nakopat ti prdel!|- Coe?
{53406}{53466}Sklapni a poslouchej!
{53469}{53582}ECOBANOVÉ pøiváejí kadı den|náklaïáky plné balíèkù.
{53594}{53649}Nejsou to ledajaké balíèky,|jsem si jistı e jsou urèeny pro nás.
{53652}{53713}Já chci Helen, nic víc.
{53738}{53816}Ty balíèky bychom mìli pøijmout...
{53825}{53885}A ukázat jim naši vdìènost.
{53889}{53927}O èem to mluvíš?
{53928}{54008}Zítra napadneme stanovištì ECOBANU.
{54019}{54080}Vezmeme si naše balíèky
{54084}{54141}a dáme jim naše díky.
{54143}{54177}Vánì?
{54204}{54280}Co bychom to byli za kamarády,
{54282}{54334}kdybychom tì nepozvali na tak velkou akci?
{54346}{54397}Pøátelé?
{54406}{54486}Pøátelé Odporu!
{54501}{54582}Vyuívaš Odporu k ospravedlnìní
{54586}{54637}neèeho, co není víc ne kráde?
{54643}{54732}Drte se zpátky|nebo špatnì skonèíte.
{54758}{54812}Ty zkurvys...!
{54884}{54949}Kdybys víc pouíval mozek ne svaly,
{54950}{55002}vìdìl bys, co musíš doopravdy udìlat.
{55017}{55077}Chovat se stupidnì a nechat se zabít|je jen tvoje rozhodnutí.
{55087}{55137}Ale netahej do toho Woodyho!
{55140}{55223}Jestli se mu nìco stane,|tak se domu vrátíš po kouscích!
{55338}{55408}Hej! Kdo asi zachránil Woodyho dneska?
{55411}{55457}Ty nevdìènej malej skrèku!
{55460}{55516}Øíkám ti, e má srdce|ECOBANÙ!
{55518}{55561}Namyšlenej ocas!
{55563}{55615}No tak, hudba!
{55790}{55865}Ty chceš vánì bıt s nimi?
{55883}{55964}Proè? Jsi na mì naštvanı?
{55983}{56037}Jsem. Mìl jsi mì poslechnout.
{56066}{56124}Take mì opouštíš?
{56148}{56189}Budu tì sledovat!
{56192}{56235}Kdo øíká, e nìkam jdu?
{56239}{56338}Vím, e opravíš kluzák a...
{56369}{56440}...opustíš mì.|Pak se zabiju!
{56506}{56539}Pøestaò!
{56580}{56631}Co ti to sakra nakecali za blbosti?
{56636}{56692}A nevtipkuj o smrti.
{56701}{56732}Tady...
{56761}{56799}Vezmi si to.
{56807}{56851}Nebudu to potøebovat.
{56856}{56926}Ale... to je od tvojí pøítelkynì!
{56935}{56974}Není to moje pøítelkynì.
{56978}{57064}A nikam neodcházím.
{57066}{57135}Fakt? Zùstaneš se mnou?
{57145}{57212}Slib mi, e mì nikdy neopustíš!
{57215}{57253}Uvidíme.
{57377}{57434}Jste si jistá, e to byla Jay?
{57440}{57512}Ano pane, naprosto.
{57525}{57566}Dobrá, to je vše.
{57641}{57736}Etho, zatím si to necháme|pro sebe.
{57754}{57787}Ano, pane.
{59344}{59433}Nášim cílem je osoba, která pronikla|do systému DELOS.
{59434}{59515}Schovává se ve znièeném tankeru|v pobøení oblasti èíslo 5.
{59546}{59618}Jestlie bude klást odpor...|Zastøelte ho.
{61186}{61238}Alpha 1, nikdo tu není!
{61246}{61298}Alpha 2, nikde nikdo!
{62178}{62225}Proè jsi mi nic neøekla?
{62502}{62571}Spáchal vradu|a pak utekl z ECOBANU!
{62574}{62653}Nedovol vzpomínkám, aby tì ovládly!
{63137}{63192}Támhle! To je ono!
{63216}{63255}Kde?
{63317}{63357}Aha, u to mám!
{63644}{63709}Dobré odpoledne, stráníku.|Omlouvám se za zpodìní.
{63732}{63762}Kdo sakra jste?
{63775}{63811}Ukate mi papíry!
{63820}{63909}Jo, papíry?|Asi mi nìkde vypadly...
{63927}{63999}Take nemáte papíry?
{64021}{64043}Vystupte si z vozu.
{64093}{64149}Moment...|Kam jsem je jenom dal?
{64152}{64214}Co to dìláte?|Vystupte!
{64217}{64264}Dobrá! Papíry...
{64752}{64780}Zkurvysynu!
{64899}{64932}Nastupte!
{65463}{65499}Jeï, rychle!
{65611}{65648}To je v poøádku. Nechte je jet!
{65756}{65811}Jdem to oslavit!
{66134}{66187}Bylo mi oznámeno, e došlo k loupei.
{66209}{66255}Proè jste s tím nic neudìlal?
{66258}{66340}Kde jste mìl hlídky, kdy kradli naše vìci?
{66373}{66453}Jak jsem mohl ochránit nìco
{66454}{66497}o èem jsem ani nevìdìl, e existuje?
{66498}{66560}Vy jste jen samá vımluva|a ádné vısledky.
{66565}{66635}Kdyby na vás bylo spolehnutí,|nemusel bych tu vùbec bıt.
{66651}{66712}Sledovanı objekt zmìnil kurs|a smìøuje nyní k pobøení oblasti 2.
{66726}{66766}Jakmile bude pøesnì urèena jejich poloha,
{66767}{66837}vyrazíte tam a celé to vyèistíte.
{66988}{67042}Co to je za kravál?
{67044}{67084}Vdy jsem|Psancùm øíkal, aby nic nepodnikali!
{67096}{67155}Zdá se, e mají nìco velkého.
{67181}{67242}Nehodláš|pouít kluzák, e ne?
{67273}{67323}Jen ho opravuji, to je vše.
{67345}{67431}Vletìt do ECOBANU|znamená jistou smrt.
{67453}{67500}Neboj se, mám svùj ivot rád.
{67514}{67606}ECOBAN nìco plánuje...
{67609}{67640}Neustále nìco vozí do Marru.
{67661}{67697}Nejspíš chtìjí celı Marr zapálit.
{67720}{67768}Systém DELOS potøebuje nové zdroje.
{67773}{67840}Pravdìpodobnì zapálí a zamoøí celou oblast.
{67877}{67934}Urèitì neplánuješ nìjakou hloupost?
{67946}{68017}Myslíš si, e existuje lepší zpùsob?
{68029}{68072}Potøebujeme nìkoho, kdo se dostane do
{68073}{68126}centra DELOSU,|ani by vzbudil podezøení.
{68149}{68188}Take mám vyuít Jay...
{68191}{68286}...nebo mám èekat, a vypálí celı Marr do základù?|Nemám v plánu ani jedno.
{68290}{68340}Pak u se nemáme o èem bavit!
{69240}{69301}Bylo jich tam hodnì, odkud to asi vozí?
{69303}{69382}Koukám, e jste pøivezli nové zboí!
{69394}{69431}Uau, co je to?
{69619}{69655}Hele - co to má bıt?
{69735}{69773}Proè to bliká?
{69785}{69831}Je to maják!
{70025}{70080}- Ani hnout!|- Odhoïte zbranì!
{70083}{70133}- Na podlahu!|- Ruce za záda!
{71083}{71117}Neblázni!
{71249}{71282}Pryè odtud!
{71391}{71432}Buïte tu potichu!
{71443}{71508}A za ádnıch okolností|nevycházejte ven!
{72209}{72285}No skvìlı,|zrovna teï mi dojdou náboje!
{72299}{72344}Pøebìhnu na druhou stranu.
{72345}{72384}Sleduj a uè se!
{72387}{72438}Dívej!
{72558}{72577}Joe!
{72589}{72634}Máma mi vdycky øíkala - neøíkej hop!
{72657}{72705}Ti hajzlové!|Joe, jdu za tebou!
{73147}{73174}Dave!
{73178}{73253}Dave!
{73447}{73511}W-Woody, je mi zima...
{73624}{73651}Pùjdu ven a najdu Shua.
{73673}{73733}Neodcházej.|Bojím se.
{73747}{73777}Neboj se!
{73791}{73882}- Je mi zim...|- Pst! Hned jsem zpátky.
{73913}{73957}Neodcházej...
{74008}{74028}Neboj. Vrátím se
{74035}{74071}A nezpívej si, jasnı?
{74572}{74624}Pššššt!
{74666}{74707}Ruce na zeï!
{74708}{74747}Jeden krok zpátky!
{74759}{74821}Odvezte je a prohledejte budovu!
{74821}{74861}Ano, pane!
{75944}{75981}Kde máš Karen?
{76487}{76523}Woody?
{76525}{76559}Boe...
{76562}{76599}Pojïme pryè.
{76655}{76711}Øekl mi, abych nikam nechodila...
{76757}{76814}Woody mi øekl, abych na nìj èekala...
{79086}{79134}Proè zkrátka neumøeš,
{79164}{79224}ty mizernı švábe!
{79233}{79294}Vstaò!|Tentokrát to dokonèím!
{79299}{79385}Mìl bys mi podìkovat,|e jsem šel ke dnu místo tebe!
{79399}{79449}Mìl jsi umøít u tenkrát,
{79461}{79511}bylo by to lepší.
{79524}{79604}Chceš øíct - aby se Jay nedozvìdìla pravdu.
{79627}{79668}Pøesnì tak!
{79682}{79758}Teï zemøeš znovu.|Pro Jay a pro mì!
{80047}{80096}Shuo...
{80306}{80358}Woody!
{80404}{80458}Woody!
{80654}{80713}Zmiz! Jdi mi z cesty!
{82529}{82654}Myslel jsem, e se starám já o nìj,
{82676}{82793}ale bylo to obrácenì.|Woody dával pozor na mì.
{82913}{82971}Chtìl jsem mu jednou ukázat modrou oblohu...
{83175}{83224}Je nám to líto, Dave.
{83337}{83392}Pùjdu do ECOBANU.
{83399}{83440}Nemusíte jít se mnou,|pokud nechcete.
{83583}{83643}Dìkuji vám za vše, co jste dokázali.
{83668}{83735}Nejdøív potøebujeme,|aby nám Noah pomohl.
{83799}{83869}Marriánští psanci jsou rozprášeni,
{83888}{83974}ale Dr. Noah a jeho agent|jsou stále nebezpeèím.
{84029}{84105}Plánují jistì brzkı pád ECOBANU.
{84141}{84181}Neobviòujme ostrahu
{84183}{84233}a neplıtvejme dále èasem.
{84265}{84335}Operace Marr je pøipravena.
{84364}{84440}S vaším svolením|mùe ihned zaèít.
{84473}{84531}Prospìšnost této akce je jistá.
{84539}{84599}Nemùeme dále ít ve spoleènosti s Marriánci...
{84627}{84678}a pokud úroveò energie bude dále klesat,
{84680}{84739}pak mnoho systémù ECOBANU sele.
{84744}{84823}Co zpùsobí ještì vìtší obtíe|pøi potlaèování povstání Marriáncù.
{84833}{84938}Navíc, Dr. Noah a jeho agent|u pravdìpodobnì nìco chystají.
{84945}{85020}Musíme zaútoèit na jádro problému.
{85436}{85488}Je i tvou povinností chránit ECOBAN!
{85511}{85584}Jediná vìc, ohroující ECOBAN,|je ECOBAN sám.
{85629}{85708}U je mi to jedno.|Je konec.
{85723}{85786}Zítra budou všichni Marriánci mrtví,
{85801}{85867}vèetnì toho zrádce Shua.
{85926}{85992}I oni mají právo se bránit.
{86046}{86083}Kam chceš jít?
{86099}{86128}Jay.
{86156}{86175}Jay!
{86210}{86254}Tak jako se nevzdáváme my,
{86265}{86308}nevzdá se ani on.
{90899}{90974}Je mi špatnì z téhle pusté osiøelé budoucnosti.
{90997}{91085}Chci zase vidìt jasné nebe...
{91086}{91173}...tak jako tenkrát....
{91200}{91249}...a proto musím odejít...
{91269}{91339}...nevím, kde budu...
{91360}{91433}...ale vím, e budeš se mnou|v mém srdci.
{91473}{91540}Jay, postarej se o Woodyho.
{92761}{92831}Všichni vojáci nastoupeni!
{92841}{92890}Vojsko je pøipraveno k posílení|vnitøní ostrahy.
{92895}{92941}Mui - na svá místa.|Buïte pøipraveni a okamitì hlaste
{92944}{92973}jakékoliv podezøelé aktivity!
{92996}{93067}Kdo zmìnil rozkaz|a stáhnul vojáky z Operace Marr?
{93105}{93150}Velitel Cade, pane...
{93153}{93199}Dal rozkaz zesílit zdejší ostrahu.
{93202}{93235}Kde je?
{93257}{93306}Šel do kontrolní vìe DELOSU, pane.
{93336}{93358}Coe?
{93360}{93443}Pošlete okamitì vojáky na Marr.|To je rozkaz!
{93445}{93483}Ano, pane!
{93486}{93531}Jednotko, na vozy nástup!
{93930}{94045}Tahle válka neskonèí, dokud|nevypneme systémy DELOSU.
{94043}{94105}Je tøeba odpojit bezpeènostní okruhy...
{94115}{94193}Pak bude moci Shua nahrát data do systému.
{94228}{94258}To je naše práce.
{94869}{94899}Támhle! Vstup je pøed námi.
{94975}{94990}Pøiprav se!
{95015}{95039}Pal!
{95584}{95644}Guvernére, operace Marr|u zaèala.
{95645}{95693}Pøeji vám hodnì štìstí.
{95695}{95751}Udìlám, co bude v mıch silách, guvernére!
{98855}{98895}Jedeme správnì, je to tudy!
{98965}{99008}Hej hej hej, nejedeme moc rychle?
{99019}{99089}Èím døív tam budeme,|tím døív se pomstíme!
{99509}{99577}Co? Co to sakra je?
{99579}{99632}Ja tam mezera! Do prdele!
{99641}{99690}Ten starej...
{99713}{99754}Hej! Zastav!
{99756}{99801}Øíkal, a jedem na plnı plyn!
{101045}{101132}Sakra! Musím bıt nesmrtelnej,|e jsem to pøeil!
{101137}{101224}Asi mám stránıho andìla|a z pekla štìstí!
{101260}{101301}Ha, Shua! Nechceš svézt?
{102199}{102248}Hoï sebou!
{104999}{105075}Jen poèkejte.|A tohle vypnu, máte po srandì!
{107480}{107555}Take jsi to nakonec dokázal...
{107745}{107804}Dostaneš jen to, co si zaslouíš!
{107830}{107925}Tohle - je pro dobro Marru, ECOBANU,|a celého zbylého svìta.
{107945}{107962}To tìko.
{107964}{108037}Marr je jen špinavá díra!
{108040}{108086}Chceš znièit budoucnost mnì a Jay!
{108110}{108195}Proè bys ji mìl mít ty?|Proè by mìla bıt Jay právì s tebou?
{108611}{108631}Zadr.
{108723}{108749}Jay, zadr!
{108849}{108899}Nenu mì to udìlat!
{109013}{109046}Jay...
{117959}{118042}Dìdo, vidím hroznì jasné svìtlo!
{118049}{118147}Ó, to je dobøe.|To je dobøe...