{1}{1}23.976
{312}{412}Zámerne sa oneskori je staromódne.
{806}{880}Prepáè .... Èakal si dlho?
{880}{946}Eh...Nie...Umm...!!
{2870}{2909}Dnešok bol skvelı , však?
{2909}{2941}Á... Áno.
{2941}{2974}Dobre potom...!
{3459}{3516}TaSHee's Gang uvádí...
{3617}{3735}SCHOOL DAYS
{6010}{6092}Keby len trochu neskôr.....
{6096}{6140}MAKOTO! TY IDIOT!!!
{6222}{6259}Nezáleí na tom ako to cítiš, ty si iba splašenı.
{6259}{6358}Necha Katsuru-san osamote.
{6358}{6423}Eh?! Nezamıš¾al som ju...
{6423}{6443}Urobil si to!
{6459}{6489}To je zvláštne...
{6539}{6624}Naozaj...... by si sa mal nauèi viac o dievèenskıch pocitoch.
{6624}{6653}Ja viem!
{6678}{6722}Tak...ummm...
{6749}{6795}Vieš..predtım...
{6894}{6922}I-Idiot!
{6922}{6970}Rozmıš¾aj o ostatnıch!
{6970}{7034}My sme priatelia! Rozumieš?
{7049}{7064}Á-Áno.
{7073}{7132}Tak to bolo len lúèenie!
{7132}{7198}Myslel si to váne pri zblíení s Katsurou-san nie?
{7198}{7284}Eh?! Lúèenie?! Toto je Japonsko!!!
{7284}{7345}Napriek tomu ! Nabudúce to urob dôkladne.
{7359}{7377}Á....Áno....
{7377}{7439}Skvelé. Potom ti tam toto.
{7493}{7512}Toto sú....
{7512}{7545}Lístky do kina.
{7568}{7668}Nabudúce nechaj Katsuru-san ui si. Ak to pôjde dobre...
{7683}{7714}Ja....Ak to pôjde dobre...?
{7714}{7787}Skvele naladení spoloène v tme...
{7816}{7853}Prirodzene poloíš ruky,
{7865}{7985}nebudeš hladie na strieborné plátno, ale zaènete vzájomne...a potom...
{7985}{8008}A  potom?!
{8008}{8036}SMOOCH!!!
{8036}{8102}V...váne?!
{8116}{8153}Dobre, sna sa èo najviac...
{8197}{8220}V...v poriadku!
{8266}{8329}Váne, Makoto je decko. Je problematickı.
{8329}{8350}Sekai.
{8350}{8382}Tie lístky....
{8382}{8418}Ah...chcela si ís?
{8431}{8475}Nechcela si Itoua-kun pozva?
{8730}{8776}Nemám ve¾a vo¾ného èasu!
{9027}{9087}Hmmm...film, huhu.....|/"Randiaci zaèiatoènícky super štandart."/
{9087}{9246}"Romantická atmosféra privedie tvoje dieèa do oèakávania."
{9288}{9392}A vtedy...P...Pobozkám....
{9506}{9561}Problém je uhol poh¾adu...
{9571}{9613}Bolo by dobré sa k nej nakloni...?
{9613}{9681}Ale Katsurino naahovania ku mne je tie pekné !
{9718}{9780}Nie-Nie-Nie...  Hluk je zákázanı, mu!
{9780}{9884}Najprv, dobre, ju objímem a potom vezmem jej ruku..! Nie! Èo bolo druhé?
{9884}{9923}Nie, to nie je to!
{9923}{9982}Oh správne, Potrebujem si umy zuby a obliec si èisté spodné prádlo---
{9982}{10019}---a ostriha nechty.
{10040}{10085}Lístok platí len do zajtra?!
{10487}{10507}Itou-kun.
{10573}{10632}Pre "randenie", èudujem sa ak je to dobré...
{10657}{10710}Oneechan, zvoní ti mobil!
{11099}{11142}Zdá sa, e si môeme pozrie , ktorı ko¾vek sa nám bude páèi.
{11142}{11165}Ktorı je dobrı?
{11184}{11207}Ummm...
{11319}{11374}Umm..Itou-kun, Ja---
{11374}{11454}Áno. Je to ten jeden, dobre!
{11703}{11743}Amelia, si urèite bojazlivé maèiatko.
{11743}{11797}Ah Peter,  si tak zlıı!
{11837}{11886}Ahoj!  Idem ruši!
{11900}{11917}Huh..? Chris?!
{11934}{12003}Po všetkom, keï si povedala rande bol to ¾úbostnı príbeh..
{12051}{12069}Eh....? Á-Áno.
{12156}{12222}Ïakujem Chris za tom e si ma predstavila Petrovi.
{12240}{12320}Ve¾a šastia. Je idiot, ale je dobrı chlap.
{12337}{12374}Ale, Chris, je to pravda?
{12385}{12450}Nemusíš sa bá! Tak potom, dobrú noc!
{12450}{12468}Áno.
{12506}{12571}Nejako.... mi to pripomína nás dvoch.
{12605}{12673}Chris je Saionji-san a Amelia som ja.
{12697}{12732}Potom som Peter?
{12741}{12756}Áno.
{12767}{12827}Dobre... ¾udské vzahy sú  dos rozdielne.
{12840}{12956}A akosi èlovek hrá  Petra podobne ako ty...
{12956}{12980}Eh??
{13002}{13040}Je svojím spôsobom úasnı....
{13040}{13093}Eh...! N-Naozaj....?
{13108}{13190}Ale Amelia ti nie je ve¾mi podobná.......
{13217}{13344}Uh... ty si... viac ako Amelia... si zlatšia.
{13499}{13527}Peter, Ja....!
{13527}{13559}To je fajn ak nepovieš niè.
{13570}{13602}Peter?!
{13651}{13711}Ako rozmıš¾am Katsura je naozaj zlatá...
{13732}{13782}Skvelé! Dnes to urobím!
{14305}{14344}Svetlá...vypni ich...
{14438}{14491}Katsurine prsty....sú krásne....
{14518}{14583}Skvele naladení spoloène v tme...
{14583}{14629}prirodzene vezmeš jej ruky.
{14629}{14760}Zaènete vzájomne...a potom...
{14760}{14780}A-A potom...?
{14780}{14846}Smoooch!
{14856}{14878}Amelia...!
{14878}{14941}Ah , nie! Peter to sú moje prsia....!
{14974}{15009}Si nádherná , Amelia!
{15009}{15037}Nie! To je trápne!
{15037}{15059}Ak to nemáš rada....
{15082}{15117}Nehovor takéto veci!
{15138}{15191}Katsurina hruï je ve¾ká....
{15208}{15271}Správne. Nepovedala Sekai....
{15281}{15333}tak Katsura je iba hanblivá!
{15348}{15392}Som si istı urèite na mòa èaká!
{15392}{15445}Prepáè Katsura! Ja to nezvládnem!
{15470}{15509}Ja.. teraz....!
{15574}{15609}Si nádherná Katsura!
{15641}{15665}Si horúca!
{15689}{15708}Uh...umm...
{15733}{15751}Ummm...
{15751}{15767}moja ruka...!
{15799}{15814}Moja ruka.....
{15814}{15843}Príliš ju stláèaš!
{15967}{15982}Katsura...
{15998}{16046}Na tvoje pery, dám ti smoooch.
{16303}{16392}Nevedela si, e randím s Petrom?
{16411}{16434}To nemôe by....!
{16461}{16545}Zbohom, Amelia. Buïme priate¾ky aj potom ako absolvujeme.
{16563}{16588}Chris...!
{16873}{16928}Prepáè...Sekai povedala...
{16946}{16977}Saionji-san?
{17050}{17086}Ako som povedal toto ...
{17102}{17163}tamto...Katsura je iba hanblivá...
{17209}{17277}Pravda je , e lístky na film mi dala tie Sekai.
{17289}{17336}Je naozaj zvedavı èlovek, nie je?
{17354}{17380}Itou-kun mal....
{17431}{17518}Itou-kun má ...so Saionji-san...um...
{17571}{17616}dobrı vzah.
{17627}{17668}Áno....sedíme ved¾a seba.
{18357}{18393}Teda..budem vystupova.
{18393}{18457}A-Ah....á-áno...
{18492}{18508}Ummm...
{18508}{18518}Huh?
{18596}{18615}Prepáè.
{18670}{18691}Ah...! Katsura?!
{18806}{18871}Pøeklad + korekce: Kirosaku Ayra
{18920}{19005}Èasování: WelW(etkaAa)-hime
{19179}{19219}Ach, U viac nechcem!
{19231}{19283}Ak rozmıš¾am  èo si mi povedala....
{19309}{19348}Makoto , SI VE¼Kİ IDIOT!!!!
{19348}{19383}Vzadu buïte ticho!
{19394}{19442}Prepáète....
{19472}{19521}Zdá sa, e tam majú zábavu, tí dvaja....
{19614}{19672}Si príliš hluèná , idiotka!
{19672}{19746}Idiot,Idiot, Idiot,Idiot.....
{19825}{19845}Ako diea....
{19845}{19866}Kto?
{19968}{20033}Po tom, spravili ste to správne?
{20051}{20082}Ešte nie.
{20194}{20285}Katsura o tom rozmıš¾a, nedokáem to.
{20298}{20363}Potom mono ešte nikoho nemala.
{20363}{20417}To je problém?
{20428}{20482}Áno, iba zaèína.
{20495}{20549}Ideš na to prirıchlo.
{20549}{20634}Pretoe Katsura-san je citlivá.
{20644}{20694}Ale kniha hovorí....
{20732}{20774}Kniha?
{20789}{20848}Kúpil som knihu Návod na Lásku na skúšanie.
{20860}{20887}Si váne IDIOT?!!!
{20891}{20938}Idiot si ty , Saionji!
{20951}{20984}Ah....ospraved¾òujem sa....
{21034}{21057}Preèo len ja?
{21057}{21089}Ako keby som vedel.
{21198}{21241}Avšak poriadne sa ospravedlò a urob to.
{21289}{21327}To by som urobil rád, ale...
{21374}{21484}Ak máš dos èasu na èítanie z tej knihy, vezmi si trocha snahy a daj o nej vedie Katsure-san.
{21484}{21536}Máš rád Katsuru-san, e?
{21736}{21817}Ve¾a šastia, mladı mu.
{22137}{22163}Oh, Itou?
{22176}{22189}Katou!
{22202}{22287}Èo sa stalo? To, e si prišiel do tejto triedy je pekne nezvyèajné.
{22311}{22357}Mám tu prácu  s mojou známou...
{22357}{22400}Kto? Ja?
{22400}{22448}Preèo by som mal prís na to aby som a videl?
{22448}{22500}Si neslušnı ako vdy.
{22500}{22567}Tak kto to je? Zavolám ju sem.
{22595}{22618}Katsura.
{22629}{22656}Katsura Kotonoha!
{22708}{22752}Eh.. Tak ona je tvoja známa.
{22752}{22787}Áno tak trocha.
{22804}{22857}Hmmm... Katsura, eh.
{22864}{22912}Prišel si jej nieèo povedat alebo nieèo iné?
{22932}{22957}Preèo?
{22957}{22991}Pretoe sa tváriš smutne.
{23025}{23058}T-to je tvoja predstava!!
{23065}{23113}Ak je tu monos môem to urobi pre teba?
{23139}{23216}Odkedy sme priatelia na strednej škole, urobím to lacnejšie!
{23216}{23255}Ako som povedal to nie je to!
{23255}{23294}Ah, zvoní. Neskôr!
{23333}{23350}K-Katou!
{23453}{23483}Preèo odchádzaš?
{23483}{23523}Stalo sa dnes nieèo?!
{23532}{23555}Nieèo dôleité!
{23555}{23597}Váne?! A èo ja?
{23597}{23624}Nemá to s tebou èo robi!
{23658}{23724}Ah, niekedy ku mne nie je rovno priate¾skı.
{23801}{23821}Tentoraz urèite....!
{23865}{23879}Katsura!
{23952}{23973}Môeš chví¾u poèka?
{24023}{24037}Ja...
{24037}{24074}Ja mám stretnutie vıboru.
{24074}{24098}Kedy konèí?
{24109}{24137}Bude to neskoro...
{24137}{24159}Poèkám.
{24170}{24198}Ale môj zákaz vychádzania je...
{24198}{24268}Aj keï iba na chví¾u iba na malú chví¾u to bude dobré!
{24314}{24366}Ja u.... nechcem robi nieèo ako tamto.
{24446}{24494}Myslím, e to ve¾mi nenávidíš.
{24538}{24587}Pravda je , e chcem vzia tvoju ruku,
{24598}{24682}a pravda  premıš¾al som osta pri tom je v poriadku...
{24722}{24783}Ale nechcem robi veci, ktoré nemáš rada!
{24798}{24831}Chcem ti iba rozumie.
{24862}{24919}Tak preto... chcem zaèa od zaèiatku.
{24935}{24994}Chcem...o tebe vedie viac!
{25050}{25065}Katsura!
{25093}{25132}Moje stretnutie vıboru zaène....
{25181}{25192}Stanica!
{25206}{25233}Budem na teba èaka na nástupišti!
{25252}{25276}Budem èaka!
{25768}{25791}Ideš teraz domov?
{25791}{25825}Á-áno...
{25854}{25897}Stanica nie je touto cestou.
{25935}{25965}D-dnes pôjdem atobusom--
{25965}{25979}Preèo?
{25988}{26019}Zvyèajne chodíš vlakom, nie?
{26029}{26086}Obèas môe by autobus dobrı.
{26095}{26135}Nechceš ís vlakom?
{26166}{26199}T-tak to nie je!
{26212}{26266}Dnes sa cítim na cestu autobusom...
{26266}{26308}Pretoe Makoro je na stanici?
{26531}{26589}Som si istá, e stále èaká.
{26630}{26652}Pretoe je idiot.
{26816}{26847}Nemáš ho u viac rada?
{26879}{26950}Ak je to tak môeš mu to poveda priamo.
{26965}{26993}Pretoe je idiot.
{26993}{27044}Prosím nehovor mu idiot!
{27061}{27096}Itou-kun nie je idiot!
{27115}{27162}Iba je trocha aktívny to je všetko....
{27375}{27427}Skvelé, obaja ste idioti.
{27557}{27626}Ak povieš èo si myslíš bude to fajn.
{27693}{27726}Myslíš to váne?!
{27735}{27775}Môem si to vzia? Je to v poriadku?
{27775}{27826}Nechcem ti to vráti.
{27826}{27888}Tá kniha je nepouite¾ná.
{27912}{27962}Nie je to tak, e by som ho nenávidela.
{28013}{28055}Ja... bojím sa.
{28085}{28119}Chlapcov - všetkıch.
{28157}{28313}Vdy odkedy som bola na základnej som mala najväèšie prsia v triede.
{28325}{28352}J-Ja vidím....
{28365}{28437}Tak som èasto bola šikanovaná a vysmievali sa mi...
{28452}{28508}Ale s Makotom je to odlišné, však?
{28516}{28585}Ja viem, Ja to viem, ale...
{28613}{28639}Povedz, Katsura-san,
{28651}{28757}myslím, e Makoto sa chce o teba naozaj stara.
{28770}{28792}Je to naozaj tak?
{28804}{28877}Pozri, nikdy si s tım neskúsila zaèa.
{28905}{29049}Ale ak vyzeráš jednostranná urèite nebudeš sama ak sa o teba Makoto bude chcie stara.
{29071}{29150}Katsura-san èo si myslíš o Makotovıch citoch?
{29183}{29223}Ako èo chce robi.
{29242}{29308}Pozri, chlapec, dievèa je to rovnaké , nie?
{29308}{29319}Itou?
{29333}{29369}Ako zdie¾anie pocitov.
{29369}{29394}Pojedeme spolu domù?
{29394}{29437}Chlapec...dievèa....
{29477}{29566}Pointa je Makoto je niekto kto myslí na pervérzne veci ako tie.
{29573}{29614}Ale ve¾mi sa obmedzuje.
{29645}{29678}Pervérzne veci?
{29695}{29747}Pre chlapcov je to normálne.
{29766}{29822}Myslím, e je niekto kto sa snaí naozaj tvrdo.
{29836}{29871}V-váne...?
{29880}{29976}Áno naozaj. Ak by to bolo nieèo iné,  on urobí toto.
{30025}{30150}Achh, toto môe by plytvanie na Makotovi!|/Saoionji-san.../
{30200}{30266}Dobre teda, prestanem so zasahovaním.
{30294}{30449}Saionji-san? Vieš ve¾a o Itou-ovi-kun, však?
{30475}{30508}Cítim sa tocha ialirvá.
{30520}{30662}T...To tak nie je. To preto, e sedíme spolu a èasu, ktorı sme spolu je ve¾a to je všetko.
{30687}{30785}To je v pohode. Pozri sa na neho trocha viac.
{30810}{30847}Ak to urobíš som si istá, e mu  urèite porozumieš.
{30867}{30955}Uhmm...pravda je Saionji san, o Itou-kun...
{30955}{31000}Hmm... Dúfam.
{31358}{31406}Tak idem teraz.
{31424}{31439}Autobusom?
{31464}{31477}Vlakom?
{31768}{31778}Katsura...
{31890}{31947}Vïaka bohu. Myslel som, e neprídeš.
{31981}{32059}Nie... veril  som, e prídeš, ale... poviem toto...
{32147}{32160}Katsura.
{32194}{32285}Prisám u nebudem chcie robi niè èo nemáš rada!
{32300}{32316}Prepáè mi!
{32350}{32436}Chcem o tebe vedie viac Itou-kun!
{32537}{32613}Preto... sa budem snai èo najviac.
{33323}{33376}Pretoe som tvoja priate¾ka ...
{33391}{33434}Budem sa snai viac a viac.
{33477}{33490}Já taky ...
{33560}{33622}www.mycolorfullife.blog.cz
