{1}{1}23.976
{124}{144}Haló?
{144}{182}Oh, Katsura?
{196}{286}K zajtrajšku.... Ak pôjdeš preè môeme ís spolu...
{286}{341}Katsurou myslíš onee-chan?
{369}{431}Si sestrin priate¾?
{443}{479}Máte zajtra rande?
{519}{615}Práve teraz si onee-chan dáva kúpe¾ na zajtra.
{615}{639}Kokoro!
{666}{707}Hej, onee-chan!
{857}{892}TaSHee's Gang uvádí...
{1025}{1158}SCHOOL DAYS
{3373}{3413}Hej, onee-chan!
{3428}{3479}Chcem sa tie rozpráva!
{3479}{3530}Staèilo. Teraz choï preè!
{3530}{3600}Je to chlapec na tvojej ploche e?
{3600}{3646}Je to Itou-kun však?
{3979}{3992}Katsura?
{3992}{4009}Áno.
{4009}{4049}Vïaka bohu.
{4049}{4085}Bol som prekvapenı.
{4104}{4148}Ospraved¾òujem sa za svoju mladšiu sestru.
{4148}{4194}Oh, to bola tvoja mladšia sestra.
{4205}{4260}Áno, volá sa Kokoro.
{4270}{4336}Mená vás oboch sú nezvyèajné.
{4336}{4399}Áno to je pravda.
{4412}{4482}¼udia to vdy hovoria. Myslím,  e tvoju malú sestru budem vola Kokoro-chan.
{4528}{4545}Áno.
{4545}{4627}Katsura je tie zvláštne meno.
{4644}{4677}Áno, to je.
{5285}{5299}Itou-kun?
{5338}{5361}Èo sa deje?
{5361}{5432}Ospravedlòujem sa za moju malú sestru.
{5432}{5490}Za jej odpovedanie na tvoj telfón?
{5501}{5538}Nerob si s tım starosti.
{5561}{5577}Okey.
{5628}{5677}Um, vlastne...
{5713}{5768}Vlastne povedala, e a chce stretnú Itou-kun.
{5799}{5867}To  znamená , e môem ís k tebe domov, Katsura?
{5905}{5962}Makoto, si príliš rıchly.
{6005}{6031}Váne?
{6039}{6055}Um...
{6080}{6138}To si skutoène nemyslím.
{6138}{6195}Vidíš Sekai? Katsura povedala, e je to v pohode.
{6281}{6336}Katsura-san, nemôeš ho rozmaznáva.
{6336}{6383}Nie, ale...
{6393}{6457}Tento mu je so zaèínaním bezradnı.
{6457}{6525}Ak sa na to necítiš môeš odmietnu.
{6525}{6575}Um, Sekai-san,
{6575}{6666}môeš sa zdra zastavovania vecí, ktoré prebiehajú hladko?
{6681}{6751}Ty idiote!
{6751}{6785}Ow, Ow, Sekai to bolí.
{6790}{6815}Idiote!
{6815}{6847}Idiote!
{6952}{7011}Katsura, kde si bola poèas obednej prestávky?
{7055}{7153}Pretoe si nebola v triede, som bola nútená do tohto.
{7191}{7214}Achjo...
{7235}{7339}Si jeden z vedúcich èlenov  školského festivalu, tak toto je naozaj nepohodlné.
{7356}{7379}O-Ospravedlòujem sa.
{7412}{7481}Mohla si sa stretnú so svojím priate¾om?
{7536}{7588}N-Nie.
{7607}{7651}Tak je to chlapec!
{7651}{7716}Nie je divu, e si odišla tak rıchlo.
{7732}{7776}Hej,hej akı typ èloveka je?
{7784}{7815}Tvoj priate¾.
{7836}{7890}On...um...
{7890}{7963}Toto nemieri k vypytovaniu.
{7963}{8000}Pravda, ale....
{8000}{8106}Èo? Tak tvoj priate¾ je dôleitejší ako práca vedúceho èlena?
{8126}{8167}To nie je pravda.
{8167}{8219}Potom buï pozornejšia.
{8219}{8235}Áno.
{8464}{8523}Dobre, tak sa postataj o ostatné.
{8524}{8535}Áno.
{8546}{8562}Ideme.
{8803}{8886}Rozprávanie o školskıch festivaloch, rozhodla si sa , Otome?
{8909}{9049}Áno. Ale ešte na mòa nemá èas. Zo zaèiatku to nebolo dobré.
{9049}{9104}Ty si taká nevinná.
{9664}{9675}Katsura!
{10039}{10066}Stalo sa nieèo?
{10113}{10143}Vyzeráš by unavená.
{10167}{10190}Som v pohode.
{10210}{10234}Potom je to dobré.
{10418}{10432}Katsura.
{10457}{10548}Ak a nieèo trápi povedz mi to bez zábran. Odkedy spolu randíme.
{10574}{10586}Um...
{10638}{10701}My randíme správne?
{10723}{10739}Správne.
{11086}{11097}Katsura.
{11937}{11986}Dobre, teda odchádzam!
{12188}{12246}Zdá sa, e tvoj priateš má èas na tiché dievèa z D triedy.
{12324}{12364}Nie, nie. On nie je môj priate¾.
{12364}{12387}/Správa odeslana/
{12577}{12591}Haló?
{12605}{12639}Makoto!
{12655}{12684}Èo sa deje tak náhle?
{12699}{12762}Znova si robil znepokojujúce veci Kasure-san, však?
{12762}{12799}Èoe?
{12799}{12911}Nehovor "èoe" mne. Dotıka sa jej spredu medzi ¾udmi, klesol si.
{12925}{12978}Tak to nie je. Iba som ju objal.
{12978}{13022}Rozmıš¾aj o tom kde si bol!
{13034}{13074}Randíme, tak kto sa stará?
{13163}{13284}Pozri, dievèatá sú hanblivé a èasto potrebujú správnu náladu.
{13309}{13427}Nemôeš robi hocièo na hocijakom mieste! I keï spolu chodíte.
{13446}{13456}Eh?
{13470}{13602}Nerob na mòa "eh". Ak ju budeš núti do èoho chceš, Katsura-san sa znova nahnevá.
{13660}{13785}Poèúvaj, keï robíš veci ako tamtie najprv rozmıš¾aj o pocitoch ostatnıch ¾udí a potom ich opatrne urob.
{13807}{13843}To je nepríjemné.
{13866}{13947}Budeš tak veci robi aj keï je to nepríjemné. To je èo robia všetci ostatní!
{13960}{14049}Spôsobenie minulé drádivé fázy bolo z nevedomosti o pocitoch ostatnıch.
{14049}{14136}Vedie k pocitom vás dvoch budete šastnejší, keï tie pocity budete zdie¾a.
{14151}{14190}O tom je chodenie.
{14202}{14242}Je to o èom chodenie naozaj je?
{14242}{14277}O tom to je !
{14287}{14377}Tak sa zlepši a ospravedlò sa jej za dnešok. Rozumieš?
{14415}{14438}ROZUMIEŠ?!
{14454}{14494}Hej, rozumiem. Maj sa.
{14505}{14527}Hej...
{14611}{14621}Aaa...
{14773}{14847}Tak to znamená, e sa jej zajtra ospravedlním.
{15471}{15485}Katsura...
{15792}{15896}Pøeklad + korekce: Kirosaku Ayra
{15919}{16012}Èasování: WelW(etkaAa)-hime
{16159}{16193}Bré ráno, Makoto.
{16193}{16221}Dobré ráno.
{16221}{16255}Ospravednil si sa Katsure-san?
{16292}{16357}Vlastne, nešli sme rovnakım vlakom.
{16362}{16456}Èo to robíš?! Choï do D triedy...
{16532}{16568}To pretoe si spomalenı!
{16607}{16668}Achjo, komediantskı pár tak skoro ráno.
{17780}{17836}Vieš èo máš robi? Musíš sa jej ospravedlni.
{17867}{17931}Hej, môeš ís so mnou, Sekai?
{17931}{18005}Ak pôjdem s tebou môe sa to vyvinú naopak.
{18021}{18037}Naozaj?
{18055}{18084}Ty s òou chodíš , e?
{18182}{18273}Sekai. Hikari dnes chcela jes obed spoloène.
{18287}{18346}Urèite. Musím obèas prís.
{18381}{18411}Dobre, tak to je.
{18425}{18451}Ve¾a šastia.
{18662}{18702}Preèo sa usmievaš?
{18719}{18780}Chcem nejaké rady k školskému festivalu.
{18793}{18838}Otome dosiahni svoju lásku.
{18838}{18870}Prestaò.
{18870}{18912}Si tak zlatá, Otome-chan!
{19313}{19329}Katsura...
{19816}{19872}Prepáè, e idem neskoro.
{19905}{19950}Ako hovorím, nie je dobrı.
{19950}{19996}Aj keï si to povedala.....
{20030}{20091}Budeš nešastná, keï budeš randi chalanom ako je on.
{20091}{20140}Ako som povedala je to nedorozumenie.
{20140}{20164}Èo?
{20173}{20275}Tak to je dôvod preèo nie si s nami je Itou?
{20275}{20345}Nie , Makoto s tım nemá niè spoloèné.
{20360}{20383}Makoto, eh?
{20396}{20450}Cítim tu dôveru.
{20450}{20505}Dobre to pretoe sedíme spoloène.
{20530}{20630}Tak je to on. Zaèal po tebe ís, keï sa vaše miesta vymenili.
{20630}{20670}To tak nie je!
{20682}{20764}Kadı hovorí o tejto záleitosti, keïe školskı festival bude èoskoro.
{20780}{20794}Váne?
{20794}{20903}Vieš, e ak prejdete okolo školy na festivale spolu stanete sa oficiálnym párom.
{20915}{20972}Nejakı uponáh¾anı ¾udia u na niekoho myslia.
{20981}{21054}Pravda. Školskı festival, huh?
{21068}{21121}Idú prípravy dobre, triedna predsedkyòa?
{21156}{21232} Èoskoro rozhodnem o tom èo bude naša trieda robi.
{21232}{21250}Skvelé.
{21278}{21325}Áno. Tak, èo myslíš, e budeme robi?
{21325}{21378}Som si istá, e sa to bude rozhodova hlasovaním.
{21390}{21438}Chcela by som nieèo jednoduché.
{21438}{21522}Klasické sú kaviarne a strašidelné domy.
{21565}{21607}Zdá sa, e obe sú aké.
{22062}{22102}Stále sa hneváš Katsura?
{22129}{22157}Um,
{22157}{22198}za to èo som urobil vèera vo vlaku.
{22285}{22298}Katsura.
{22407}{22451}Nie, neobaovalo ma to.
{22463}{22497}Skutoène?
{22662}{22742}Dobre. O Kokoro-chan.
{22766}{22779}Áno?
{22793}{22828}Môem ju dnes navštívi?
{22851}{22912}Um, je to trocha náhle...
{22930}{22978}Máš pravdu, prepáè...
{23104}{23114}Um...
{23114}{23149}Èo sa deje?
{23173}{23208}Ak ti nede¾a vyhovuje...
{23230}{23244}Naozaj?
{23244}{23286}Áno.
{23335}{23430}S radosou prídem! Ako ïaleko je tvoj dom od stanice?
{23430}{23497}Choï z ...um...
{23507}{23579}Pozerám sa na to dopredu! Èo si mám obliec?
{23579}{23650}Mono by som si mal kúpi nové obleèenie. Èo myslíš?
{23951}{23975}Vitajte!
{24017}{24030}Huh?
{24153}{24222}Je nezvyèajné, e si tu, Setsuna.
{24235}{24256}Obaujem a?
{24265}{24322}Nie urèite. Bola som unavená.
{24334}{24346}Vidim.
{24378}{24392}Èo sa deje?
{24419}{24460}Iba som sa prišla pozrie na tvoju tvár.
{24472}{24491}Na mòa?
{24504}{24539}Sú dni ako tie.
{24553}{24577}Ty si špeciálna Setsuna.
{24611}{24703}Konèím za hodinku. Chceš ís domov spoloène?
{24756}{24821}Tak, èo by ste si dali, sleèna?
{24976}{25118}Iba limitované, ve¾a práškového zeleného èaju s a ryu z kvetu anmitsu. |A ¾adovú kávu na pitie. Nesladenú.
{25267}{25305}Prepáè, e som a nechala èaka.
{25307}{25325}To je v pohode.
{25347}{25408}Tak, preèo si ma naozaj prišla pozrie?
{25463}{25533}Achjo, vieš ako dlho sme priate¾ky?
{25636}{25661}Potom sa a spıtam.
{25689}{25740}Naozaj nechodíš s Itou-om?
{25740}{25759}Nie.
{25772}{25789}Skutoène?
{25789}{25821}Skutoène.
{25896}{25951}Achjo , ani ty nerozumieš niektorım veciam však?
{25970}{25998}Tak to nie je.
{26015}{26066}Ja váne nechcem ma niè s Makotom.
{26341}{26360}Chápem.
{26804}{26877}To je skvelé, e a pozvala.
{26917}{26930}Ja?
{26952}{27096}V ten deò pracujem. Prajem si pre vaše šastie aby ste to chví¾u zvládli bez pomoci.
{27390}{27424}Wow, je to skutoèná vec!
{27443}{27470}Hej, Kokoro!
{27496}{27539}Pekné a spozna, Onii-chan!
{27550}{27589}Onii-chan?!
{28386}{28441}Si vytrvalá, Kokoro-chan.
{28458}{28533}Chcel by si citrón alebo mlieko, Itou-kun?
{28572}{28593}Mlieko prosím.
{28627}{28674}Ospravedlòujem sa, e Kokoro bola hluèná.
{28690}{28756}To je v poriadku. Ïakujem Katsura.
{28786}{28824}Hej, hej, Onii-chan.
{28835}{28851}O èo ide?
{28851}{28960}Preèo hovoríš onee-chan "Katsura", Onii-chan.
{29473}{29538}Ospravedlòujem sa, e sa Kokoro spıtala nieèo také.
{29557}{29597}Prepáè...
{29618}{29704}Nerozmıš¾al som nad tvojím poh¾adom, Katsura.
{29918}{29981}Je pre teba meno naozaj dôleité?
{29981}{30008}Je!
{30074}{30109}Um... Katsura.
{30109}{30196}Prepáè. Netráp sa tım.
{30210}{30223}Potom...
{30308}{30326}Kotonoha...
{30423}{30454}Je to trocha trápne.
{30487}{30512}Som šastná.
{30512}{30548}S-Skutoène?
{30610}{30624}Um...
{30624}{30636}Eh?
{30728}{30757}Makoto-kun...
{30771}{30803}Moje prvé meno.
{30912}{30998}Teraz sa zaèíname cíti to, e spolu chodíme, huh?
{31015}{31026}Áno.
{31063}{31079}Som šastnı.
{31400}{31423}Dobre.
{31442}{31454}Á-Áno.
{31582}{31598}Makoto-kun...
{31598}{31634}Èo sa deje?
{31702}{31755}Môeš na chví¾u zavrie oèi?
{31836}{31851}Takto?
{32463}{32484}Dobrú noc.
{32837}{32878}Tak, išlo to dobre, huh?
{32894}{32968}Dobre, áno. Nebolo to niè strašné.
{32978}{33048}O èom to hovoríš? Vyzeráš akoby to bolo o plakaní.
{33084}{33155}Ale zdá sa, e to zaèalo.
{33176}{33196} Ve¾a šastia.
{33253}{33274}Zaèiatok, huh?
{33285}{33320}Áno, zaèiatok.
{33349}{33369}Hej, Sekai...
{33386}{33397}Hm?
{33414}{33473}By v okolí Kotonohy je....
{33545}{33563}únavné.
{33619}{33677}www.mycolorfullife.blog.cz
