{1}{1}23.976
{220}{279}Nemôeme to robi tu.
{279}{346}Môeme ís na moje miesto, keï skonèíš v práci.
{371}{409}Dnes.... tie?
{440}{457}Nemáš to rada?
{535}{594}To je znova prax, správne?
{666}{722}Potom niet na vıber.
{1163}{1208}Dúfam, e spí.
{1421}{1482}TaSHee's Gang uvádí...
{1576}{1700}SCHOOL DAYS
{3912}{3959}Dnes bude slneèno a potom zamraèené.
{3959}{4023}Je tu 30 % šanca na dáï.
{4023}{4067}Cez víkend bude...
{4067}{4105}Chcem tie teplú limonádu.
{4119}{4198}Chcem aby som a nauèila ako sa to robí, Kokoro?
{4198}{4231}Wow, si naozaj dôverivá.
{4231}{4287}To je dôvod preèo sú chlapci nepríjemní.
{4287}{4320}Èo tım myslíš?
{4320}{4403}Uzuki-chan tie hovorí, e ma ide nauèi tıch pár vecí.
{4414}{4480}Ak iarliš, môeš si nájs priate¾a, Kokoro.
{4506}{4564}Onee-chan, zmenila si sa.
{5356}{5422}Bude to zlé, ak nás tu niekto uvidí.
{5422}{5462}Nikto tu nie je.
{5462}{5494}To je pravda, ale...
{5494}{5527}Budeme meška.
{5527}{5557}Ale...
{5571}{5645}Katsura-san na teba pravdepodobne znova èaká.
{6406}{6540}Je to plné spomienok, keï moja mama randila s mojím otcom.
{6540}{6562}Aha.
{6629}{6750}Nauèila ma poveda : "Si rovnakého veku, huh?"
{7084}{7117}Hej, pozri na to.
{7117}{7227}Vraj jedna noc na Sakakino Hills stojí 400,000 yenov.
{7259}{7284}To je tak drahé.
{7284}{7353}Ak ma chceš vzia vonku môeš ma tam vzia.
{7353}{7392}Prepáè, je to nemôné.
{7392}{7439}Achjo, neber to tak váne.
{7656}{7680}Ránko.
{7840}{7864}Aj tebe!
{7864}{7918}Èo taká ospalá tvár?
{7918}{8040}Som unavenı z robenia raòajok pre dvoch ¾udí.
{8056}{8082}Idiot!
{8097}{8124}Èo je?
{8152}{8200}Je nieèo na mojej tvári?
{8200}{8223}Nie váne.
{8223}{8265}M-Naozaj?
{8265}{8282}Uvidime sa.
{8359}{8418}Sekai, bola si s Itouom dnes ráno?
{8430}{8464}Tak mám pravdu.
{8464}{8570}Itou sa rozišiel s Katusurou sa z D triedy správne?
{8598}{8635}Á-Áno.
{8663}{8691}Potom je to fajn.
{8765}{8848}Kekichi bol šastnı tak prišiel do ako ivı do mesta.
{8848}{8939}Po prejdení ulièky našiel obchod a zacítil jedlo.
{8939}{9052}Ve¾a ¾udí èakalo rameno na ramene na nákup.
{9186}{9214}Povedz o nás Katsure-san.
{9264}{9292}Preèo?
{9437}{9552}Ak to bude takto pokraèova.
{9609}{9637}Poèkaj.
{9704}{9746}Èo je s tebou tak zrazu?
{9746}{9815}Nebude viac iadna prax.
{9830}{9879}Dobre, to je.....
{9879}{9943}Budem sa cíti zle kvôli Katsure-san ak to bude pokraèova.
{9969}{10015}Kotonoha sa nahnevá.
{10015}{10048}Samozrejme, e sa nahnevá!
{10091}{10147}Tak preèo si jej to nepovedal skôr?
{10167}{10236}Naozaj sa cítim previnilo.
{10484}{10504}Vezmi si trocha.
{10504}{10537}Je to teplé.
{10537}{10572}Oh, ïakujem.
{10592}{10621}Itadakimasu.
{10897}{10935}Deje sa nieèo?
{10957}{10987}Nie, váne nie.
{10987}{11043}Môe to chuti zle?
{11043}{11067}O to nejde.
{11072}{11096}Prepáè.
{11107}{11191}Mama povedala, e sladšie to bude perfektné.
{11191}{11215}D-dobre.....
{11212}{11297}Skúšim to znova tak ti to bude vyhovova.
{11297}{11329}Je to okej.
{11329}{11374}Chutí to naozaj dobre.
{11390}{11483}Chutí to skvelo Makoto musí by bez slov.
{11513}{11534}Áno.
{11534}{11563}Naozaj?
{11563}{11635}Je to perfektne sladké,
{11635}{11682}a zohrieva to moje telo.
{11682}{11725}Áno, áno.
{11725}{11768}To je dobre.
{11787}{11924}Um, to je tajomstvo maminej horúcej limonády nauèila ma ako ju robi,
{11924}{11973}a poveda "Urob mu vlastnú."
{12013}{12050}T-tak je to?
{12050}{12074}Ahaa.
{12345}{12399}/Chcel by si ís po škole nakupova?/
{12544}{12651}/Moja malá sestra dnes príde./
{12965}{12988}Sekai,
{12988}{13036}môem ís dnes k tebe?
{13051}{13090}Ale Makoto, ty...
{13090}{13114}Oh, to...
{13134}{13149}bolo klamstvo.
{13149}{13214}Moja malá sestra je v byte môjho rozvedeného otca.
{13214}{13275}Myšlienka, e nás obèas navštívi je pravdivá.
{13275}{13354}Znova si klamal Katsure-san.
{13354}{13381}Pretoe...
{13381}{13468}Ešte si jej o nás nepovedal.
{13468}{13531}Ako som povedal raz jej to poviem.
{13548}{13624}Ale nemôe jej to poveda teraz.
{13624}{13678}Nemyslíš si to tak tie , Sekai?
{13678}{13706}To...
{13724}{13792}môe by pravda...
{13792}{13820}ale...
{13820}{13860}Tak preèo.
{15369}{15434}Nemohlo to...
{15602}{15696}Pøeklad + korekce: Kirosaku Ayra
{15729}{15823}Èasování: WelW(etkaAa)-hime
{15981}{16003}Je to v pohode.
{16003}{16046}Vyzerá to, e Setsuna odišla.
{16076}{16096}Potom.
{16305}{16361}/Prepáè zaspal som. Choï bezomòa./
{16678}{16698}Itou.
{16768}{16789}Dobré ráno.
{16834}{16861}Dobré ráno.
{16896}{16923}Poïme.
{16923}{16953}Zachví¾u bude zvoni.
{17375}{17421}Èo je, Minami?
{17450}{17495}Achjo, u som tu.
{17495}{17558}Èo sa deje v triede?
{17684}{17706}Boe.
{18623}{18655}Èo chceš dnes robi?
{19095}{19134}Pôjdem napred.
{19188}{19213}Sekai.
{19239}{19304}Tvoja priate¾ka je Katsura-san, Makoto.
{19324}{19360}To je...
{19360}{19389}um...
{19403}{19492}To pre dôvod preèo by si mal ís domov s Katsurou -san.
{19512}{19539}Uvidíme sa zajtra.
{20720}{20741}Èo je to?
{20766}{20823}Nemyslíš , e toto je dobrá dohoda?
{20960}{21037}Môe to by pekné dvaja najnovšie modely a spárované.
{21083}{21108}Ale...
{21291}{21311}Um,
{21311}{21376}kúpim ich a dám ti to ako darèek.
{21398}{21440}Chcem aby si to pouíval.
{21440}{21495}Rovnakı mobil ako ja.
{21608}{21631}To je v pohode.
{21631}{21694}Budem sa cíti zle ak to pre mòa urobíš.
{21694}{21716}Poïme.
{22113}{22132}Si v poriadku?
{22180}{22214}Prepáè.
{22239}{22286}Netreba sa mi ospravedlòova.
{22316}{22385}Nevedel som, e vieš plies, Kotonoha.
{22385}{22420}U-Um...
{22451}{22494}Iba som zaèala.
{22494}{22553}Zas ma to èoskoro prejde,
{22553}{22639}tak dúfam, e nieèo upletiem do Vianoc.
{22639}{22777}Šál alebo sveter na obleèenie ako pár.
{23036}{23056}Sekai.
{23068}{23094}Spíš?
{23123}{23183}Cítiš sa zle?
{23183}{23203}Áno.
{23218}{23236}Aha.
{23251}{23301}Potom dnes pôjdem domov.
{23301}{23321}Áno.
{23361}{23388}Buï opatrná.
{23597}{23669}/Rozhodne a mám viac rád./
{24483}{24515}Sú tam nejaké ïalšie myšlienky?
{24515}{24535}Áno!
{24535}{24609}Všetci enskí zákazníci ma dostanú ako sprievod.
{24609}{24634}Zamietnuté.
{24634}{24708}Poviem zlatım dievèatám svoje telefónne èíslo.
{24708}{24730}Zamietnuté.
{24730}{24784}A horúci bozk príde s tım.
{24784}{24808}Zamietnuté.
{24808}{24871}Preèo?!
{24956}{24994}To je skvelé.
{25052}{25095}Sadni si.
{25562}{25636}A potom ich pozveš takto.
{25654}{25678}Dievèa?!
{25678}{25731}Ak chlapec vezme ruku dievèaa,
{25731}{25782}to znamená, e akceptuje vyznanie.
{25834}{25877}Tak,
{25877}{25931}Otome, ve¾a šastia.
{25931}{25960}Áno.
{25979}{26057}U nám povedz komu sa ideš vyzna.
{26057}{26100}Ani náhodou, nepoviem.
{26100}{26150}Môeš nám da najmenšiu nápovedu. Prosím?
{26178}{26224}Rozhodne chcem nápovedu.
{26224}{26275}Èo je zlé na malej nápovede?
{26275}{26327}Nápovedu.
{26425}{26477}Chodili sme na rovnakú strednú školu.
{26498}{26578}Tak ho máš odvtedy rada?
{26578}{26613}Á-Áno.
{26636}{26670}Kto je to? Kto je to?
{26670}{26732}Chodila si na Harami strednú školu, však Otome?
{26732}{26791}S-Správne.
{26791}{26882}Nie je tu ve¾a chlapcov z tej školy.
{26882}{26906}Èo je?
{26906}{26932}Um.
{26948}{26974}Èo sa dìje?
{26987}{27082}Vyzerá to ako èlen komisie pozerá sem celı èas.
{27082}{27108}Èo je, Katsura?
{27108}{27141}Máš problém?
{27141}{27162}Um,
{27162}{27249}chcem aby prestali ¾udia hovori odkedy som prišla do miestnosti.
{27249}{27307}Nie sme jediné, ktoré rozprávajú.
{27307}{27340}Všetci kecajú.
{27340}{27368}Ospravedlòujem sa.
{27368}{27421}Preèo sa ospravedlòuje?
{27421}{27461}Ospravedlòujem sa.
{27461}{27497}Boe.
{27497}{27539}Stratila som všetku motiváciu.
{27539}{27603}Zamerala sa na nás.
{27603}{27649}Tak to nie je. Som urèená.
{27649}{27682}Tie,
{27682}{27751}strašidelnı dom nie je v tıchto dòoch populárny.
{27751}{27795}Preèo to neurobíš sama, Katsura?
{27795}{27843}To je nemoné.
{27843}{27928}Vyzerá to, e ti nikto nechce pomôc.
{27928}{28060}Nechcem sa rozpráva s dievèaom, ktoré sa snaí zbali všetkıch chalanov.
{28060}{28093}Zbali?
{28093}{28186}Vèera si sa lepila na Itou-a z C triedy.
{28186}{28212}To je...
{28231}{28284}Nemyšlíš , e Itou-a otravuješ?
{28284}{28343}Prestaò s tım.
{28343}{28423}Hej, nechodil Itou na Harami strednú školu?
{28423}{28511}Tak môe by on ten koho má Otome-chan rada?
{28554}{28605}Je to pravda?
{28632}{28656}Katou-san,
{28656}{28718}máš rada Makota-kun?
{28736}{28776}Nemá to s tebou èo robi.
{28776}{28797}Má.
{28823}{28884}Som jeho priate¾ka.
{28901}{28975}Makoto-kun sa mi vyznal a chodíme spolu.
{28975}{29051}Nesnaím sa zbali alebo sa lepi na nikoho.
{29051}{29074}Klameš.
{29074}{29108}Neklamem.
{29108}{29137}Je to pravda.
{29171}{29196}Otome.
{29219}{29288}Pretoe máš rada Makota-kun, Katou-san,|/elám si pre/ 
{29288}{29348}napadala si ma ale nebude ti to k nièomu.|/elám si pre/
{29430}{29471}Je tu èlen komiesie festivalu?|/Tieto opakujúce slová sa k tebe naahujú./
{29471}{29502}Á-Áno.|/Tieto opakujúce slová sa k tebe naahujú./
{29502}{29567}Choï do klasickej triedy poda hlásenie.|/Tieto opakujúce slová sa k tebe naahujú./
{29567}{29608}Budeme tam robi papierovanie.|/Tieto opakujúce slová sa k tebe naahujú./
{29608}{29627}Áno.|/Tieto opakujúce slová sa k tebe naahujú./
{29627}{29655}Rozumiem.|/Tieto opakujúce slová sa k tebe naahujú./
{29655}{29808}/Svet sa zaèa trias v nejakom èase./
{29808}{29981}/Cez ktorú prechádzajú naše pocity./
{29994}{30189}/elám si  hviezdnu oblohu , dúfam na zemi./
{30189}{30354}/S¾ubujem je to neumierajúca láska./
{30354}{30396}/Poèula  som, e hovorí  ¾uïom nie som si istá , ale nie je nieèo zlé?/
{30396}{30570}/Chcem a, Chcem aby si ma iba dral./
{30570}{30669}/Môeš mi trocha pomôc?/|/Drím svoje sebecké ruky pevne./
{30669}{30747}/Prosím o boles./
{30747}{30947}/Iba ty, iba ty si naive po poití./
{30947}{31050}/Je jeden èlovek na konci mora/
{31050}{31183}/stále sa topí./
{31381}{31649}/Chcem zhrnú zachvenie svetla ešte raz./
{31649}{31684}Nemôeme.|/Chcem zhrnú zachvenie svetla ešte raz./
{31697}{31733}Iba na chví¾u.|/Obloha plaèe smeje sa zafú¾anım tancom s kvetmi./
{31733}{31754}Je to v poriadku však?|/Obloha plaèe smeje sa zafú¾anım tancom s kvetmi./
{31754}{31780}Ale...|/Obloha plaèe smeje sa zafú¾anım tancom s kvetmi./
{31780}{31814}Nebudem ho.|/Obloha plaèe smeje sa zafú¾anım tancom s kvetmi./
{31850}{31868}Okej.|/Obloha plaèe smeje sa zafú¾anım tancom s kvetmi./
{31912}{31931}Prepáète!|/Obloha plaèe smeje sa zafú¾anım tancom s kvetmi./
{31943}{32026}/Zbohom to èo si zanechal./
{32026}{32046}Trocha viac.|/Zbohom to èo si zanechal./
{32075}{32111}Nemôeš.|/Zbohom to èo si zanechal./
{32145}{32186}Áno teraz môeš ís.|/Som jedná, Som jedná kto a môe chráni./
{32186}{32204}Áno.|/Som jedná, Som jedná kto a môe chráni./
{32215}{32313}/Som jedná, Som jedná kto a môe chráni./
{32330}{32353}Makoto-kun...|/Pocity, ktoré nevyslovím, plaèem./
{32366}{32388}Makoto-kun.|/Pocity, ktoré nevyslovím, plaèem./
{32425}{32481}Milujem a Makoto.|/Pocity, ktoré nevyslovím, plaèem./
{32520}{32612}I keï chodíš s niekım inım,|/Pretoe si to ty, pretoe si to ty, my budeme veri./
{32612}{32634}Milujem a!|/Pretoe si to ty, pretoe si to ty, my budeme veri./
{33024}{33050}Sekai,
{33075}{33099}milujem a.
{33129}{33160}Ja tie.
{33534}{33550}Ani náhodou.
{33550}{33613}www.mycolorfullife.blog.cz
