{1}{1}23.976
{24}{58}/Školskı festival/
{276}{338}Katsura-san znova neprišla.
{354}{418}Musí by na jej stretnutí komisie.
{418}{452}Váne?
{452}{486}Pravdepodobne...
{486}{578}Je to naozaj v poriadku?
{578}{603}Èo je v poriadku?
{624}{758}Je to iba to.... Byhovil si sa jej tie ráno.
{769}{851}Bol by som radšej s tebou, Sekai.
{851}{923}Som šastná, keï to hovoríš, ale...
{923}{969}Potom je to v pohode však?
{969}{1003}Ale...
{1003}{1037}Je to fajn.
{1280}{1341}Je urèite chladnejšie.
{1341}{1478}Máš pravdu. Mono je èas presta jes na streche.
{1537}{1589}TaSHee's Gang uvádí...
{1690}{1809}SCHOOL DAYS
{4208}{4332}Preèo Makoto-kun robí nieèo také so Saionji-san?
{4373}{4468}Mono ma Makoto-kun viac nemá rád.
{4571}{4665}Mono sa musím viac snai.
{4787}{4825}Preèo?
{4918}{5005}Onee-chan, poèula som, e školskı festival je skoro tu.
{5029}{5077}Áno, to je.
{5077}{5132}Môem sa prís pozrie?
{5132}{5186}Chceš prís?|/Áno./
{5186}{5237}Makoto-kun tam bude tie, však?
{5265}{5299}Áno...
{5405}{5463}Nemyslel som si, e si to naozaj poièiaš.
{5508}{5563}Hej, hej, hej!
{5563}{5609}O èo ide?
{5609}{5749}Poèula som o tom práve teraz. |A trieda maju sestrerskú kaviareò a B trieda zombie kaviareò.
{5749}{5797}Malé sestry a zombie?
{5845}{5885}Onii-chan!
{5895}{5970}Vítajte.
{6009}{6052}Èo je to?
{6052}{6129}Vyzerá to akoby B trieda ukradla myšlienku našej a D triedy.
{6129}{6200}Povedali, e je to kombinácia strašidelného domu a kaviarne.
{6200}{6287}Nechystajú sa na boj iba robením kávy?
{6287}{6327}Dobre vezmeme tú vızvu.
{6327}{6361}Setsuna...
{6361}{6442}Sekai, nauè všetkıch ako obslutova zákazníkov.
{6471}{6586}Dobre, ak je v poriadku, e pouijem návod na pracovisku v zamestnaní.
{6586}{6655}Poui to na trénovanie, kım z toho nebude reálna vec.
{6655}{6679}Uvítaè si obleèenie nieèo zlaté a ponúkneme skvelı servis...
{6756}{6844}nechceme strati sex appeal.|/S-Setsuna?/
{6873}{6910}Porazíme triedy A a B.
{6963}{6998}Máme problém!
{6998}{7070}Èo je? Ak je to o malıch sestách a zombie, práve som...
{7070}{7148}O èom to hovoríš?|O to nejde. Tanaka je...
{7148}{7184}Tanaka?
{7184}{7284}Zlomil si ruku minulú noc poèas jeho tréningu.|Je mimo na dva tıdne.
{7361}{7424}Ten chalan s telom ako akı tank?
{7424}{7514}Pomysli na to , e je nádejná hviezda judo klubu, je stále èlovekom.
{7514}{7576}Potom je vıkonná komisia....
{7576}{7622}Setsuna tam bude sama.
{7691}{7775}Kotonoha tam je sama ,nie?
{7789}{7834}Itou, máš vo¾nı èas správne?
{7853}{7919}Zastúpiš Tanaku.
{7919}{7980}Ja?|Pretoe nemáš iadne lubové aktivity.
{7980}{8038}T-Taisuke je na tom rovnako.
{8038}{8121}Pouívame Sawanagu v našej skupine.
{8137}{8182}Váne?
{8182}{8255}P-Potom urobím nieèo pre triedu.
{8255}{8302}Trápiš sa kvôli Katsure-san?
{8316}{8364}Preèo? Hádáte sa?
{8364}{8405}N-Nie...
{8405}{8441}Rozišli sa.
{8441}{8466}Èoe?!
{8466}{8511}Kiyoura, èo to hovoríš?
{8511}{8567}Chodíš so Sekai, správne?
{8567}{8602}Èo?!
{8602}{8641}Setsuna!
{8641}{8675}Nechaj to na mòa.
{8675}{8719}Setsuna!
{8792}{8901}Ako som povedala, iba potrebujeme tri a viac listov z preglejky.
{8901}{8996}Nemôeme. Keïe kadá trieda má pridelenú rovnakú sumu.
{8996}{9047}Som si istá, e sú zvyšky.
{9047}{9097}To môe by pravda, ale....
{9097}{9163}Poï, pomôeme ti.
{9163}{9282}Ak nemôeme nazbiera material, nemôeme pokraèova ïalej.
{9282}{9372}Si jedinı èlen vıboru z našej triedy.
{9372}{9439}Tak je správne, e s tebou poèítame.
{9564}{9596}Rozumiem.
{9617}{9662}Èo to bol za zvuk, Minami ?
{9681}{9713}Okej!
{9843}{9934}/Hala/
{10165}{10206}Pozdvihni tvoju myse¾.
{10239}{10291}O to nejde.
{10361}{10387}Poïme.
{10867}{10911}Itou to urobil?
{10911}{11002}Myslím, e Katsura je do neho jednostranne zamilovaná.
{11002}{11037}Vedela som to.
{11133}{11220}Vypneme silu ak je nezapojená a je tu ve¾a spomienok.
{11220}{11258}Potom je to rozhodujúce.
{11258}{11296}Ideme to naozaj nahráva?
{11296}{11329}Samozrejme.
{11329}{11446}Budeme ma pôitok, keï budeme kontrolova príleitostnú izbu.
{11446}{11487}Poitok, huh?
{11559}{11581}Ïakujem za vašu tvrdú prácu.
{11676}{11703}Makoto!
{11703}{11747}Hej...
{11776}{11827}Teraz si èlenom vıboru?
{11827}{11884}Áno, nachví¾u.
{11884}{11918}Vïaka bohu.
{11918}{11993}Nebıvame spolu ráno.
{11993}{12060}Ale teraz môeme by spolu po škole.
{12060}{12100}Itou, ideme.
{12166}{12189}Makoto!
{12189}{12253}Máš dnes nejakı èas?
{12253}{12289}Nie.
{12304}{12328}Kiyora!
{12328}{12430}Zabudol si? Máš sa stretnú so Sekai v Pure Burger.
{12481}{12548}Ideme.|/Poèkaj!/
{12548}{12599}Kotonoha, prepáè.
{12599}{12660}Pošlem ti neskôr e-mail.
{12849}{12898}Nikdy som nedával iadne s¾uby.
{12898}{12932}Dal.
{13017}{13080}/Privediem Itoua, tak na mòa èakaj./
{13091}{13122}Kedy si...
{13221}{13316}/Chcela by som s tebou zajtra obedova na streche./
{13332}{13371}Kto je to?|/Um, to je..../
{13371}{13406}Katsura-san?
{13450}{13485}Preèo ju nedáš do ignorovanıch kontaktov?
{13504}{13548}Nemôem zájs tak ïaleko.
{13548}{13579}Nechaj ma pozrie sa.
{13597}{13629}/Základní nastavení -> Soukromí -> Blokovaná èísla -> ZAPNOUT/ 
{13629}{13689}Kiyoura, Prestaò!
{13689}{13724}PIN?
{13769}{13830}1 - 0 - 1 - 6
{13870}{13934}Poui tvoj dátum narodenia nie je kreatívne.
{13934}{13977}Kiyora!
{13977}{14021}/Data telefonního èísla uloena/
{14021}{14046}Vykonáno.
{14046}{14117}Nerob to...|/To je pre Sekai./
{14206}{14247}To je pre Sekai.
{14275}{14376}Pøeklad + korekce: Kirosaku Ayra
{14408}{14503}Èasování: WelW(etkaAa)-hime
{14745}{14781}Pomılila som sa.
{15299}{15350}Dala si ju do ignorovanıch hovorov?
{15350}{15409}Nemala si zachádza a tak ïaleko.|/Mal to urobi./
{15443}{15480}Setsuna...
{15497}{15542}Itou je tvoj chlapec.
{15931}{15990}Onee-chan do toho dáva jej najlepšie.
{17090}{17145}/Mail neodeslán/
{17340}{17485}Nemôete sa dovola na toto èíslo pretoe zákazník je nedostupnı.
{17485}{17552}Nemôete sa dovola na toto èíslo...
{17698}{17789}- SEZNAM BLOKOVANİCH -|1. Katsura Kotonoha|2. Pøidat novı)
{17844}{17884}Dobré ráno!
{17884}{17908}Bóe, nestraš ma.
{17937}{17976}Nechcela som.
{18003}{18058}Poèula som èo Setsuna urobila.
{18058}{18104}Správnì, áno...
{18417}{18454}Sekai.
{18688}{18728}Nemusíš sa kvôli nej trápi.
{19520}{19631}/Mail neodeslán/
{19796}{19822}Makoto.
{20848}{20910}Listov, hovoríš?
{20910}{20964}A robustnú platformu.
{20964}{21023}Nieèo dos ve¾ké tak aby ¾udia mohli lea dole a ís na to.
{21023}{21074}Minami, povedala si príliš.
{21105}{21142}Na èo to bude?
{21142}{21201}Iba mlè a priprav to pre nás.
{21201}{21307}Áno, Áno. Nemôeme pomôc, ak to pre náš neurobíš.
{21307}{21385}Ale mám stretnutie vıboru...
{21385}{21446}Ak na to budeme èaka, nemôeme ís domov.
{21446}{21544}Be sa po nieèom pozrie teraz.| Všetko èo máš urobi na stretnutí komisie je dosta sa s nimi do kontaktu.
{21544}{21604}Pre toto vynechávam moje klubové aktivity.
{21604}{21701}Huh? Nie je dievèenskı basketbalovı tím mimo pre prípravy príleitostnej izby?
{21701}{21737}Idiotka.
{21811}{21848}Rozumiem.
{22072}{22104}Ideme.
{22104}{22151}Daj mi malú chví¾u dobre?
{22282}{22334}Pozera sa na òu.... Ja skutoène...
{22372}{22408}Makoto?
{22464}{22507}Deje sa nieèo?
{22508}{22602}N-Niè, rozmıš¾al som aké je zvlášne, e nemáš obleèené sako.
{22658}{22754}Zmokla som dadi. Tak sa suším.
{22776}{22832}Ah tak je to?
{22832}{22892}Itou.|/Viem./
{22912}{23003}Pozerám s apo materiál na stánok s obèersvením.
{23003}{23055}Nemáš stretnutie vıboru?
{23055}{23123}Áno, potrebujeme to práve teraz.
{23123}{23174}Potrebuješ pomoc?|/Itou!/
{23315}{23382}Máš nieèo proti Kotonohe?
{23382}{23422}Nie je to tak.
{23501}{23549}Si priate¾ Sekai, Itou.
{23579}{23607}To je...
{23646}{23682}Ale...
{23682}{23720}Itou!
{23720}{23796}Nie je dobre ju necha samú.
{23811}{23846}Itou!
{24017}{24048}Kotono...
{24300}{24343}Materiály sú tu?
{24343}{24387}Áno, pravdepodobne.
{24429}{24470}Èo to robíš?
{24493}{24546}Nemáš stretnutie vıboru so Setsunou?
{24546}{24585}Neodkladaj to.
{24585}{24628}Nie. Taisuke je...
{24647}{24693}Èo sa deje so Sawanagom?
{25112}{25177}Èo je to? Pozri na jeho tvár.|
{25224}{25297}Um, katsura-san...
{25297}{25322}Áno?
{25322}{25411}Ak... Ak by si chcela....
{25411}{25435}Áno.
{25435}{25522}Chcela by si so mnou tancova na konci festivalu?
{25629}{25664}Ten Taisuke!
{25707}{25738}Nie som si istá èo to bolo.
{25738}{25772}Kto vie?
{25772}{25818}Napriek tomu, èo si myslíš?
{25818}{25889}Vravel si folklórny tanec?
{25889}{26087}Áno, áno. Poèul som od mojej sestry páry, k|toré tancujú na konci festival sa poèas roka nerozídu.
{26087}{26137}Tak je to?
{26154}{26284}Rozmıš¾al som aká si krásna odkedy sme boli na kúpalisku.
{26284}{26405}Bol som pekne šokovanı, keï som poèul, e chodíš s Makotom.
{26405}{26467}Poèul som, e ste sa rozišli.
{26487}{26562}Rozmıš¾al som, e by bola mono šanca, ak je to pravda.
{26562}{26604}Nerozišli sme sa.
{26619}{26689}Nerozišla som sa s Makotom-kun!
{26689}{26750}Preèo si povedal nieèo ako je toto?
{26750}{26842}U-Um, to je, um...
{26842}{26874}Ospravedlò ma.
{27053}{27157}Nestaèilo ti, Keï si dostala Itou-a, ale teraz si tie dostala Sawanagu.
{27157}{27190}Si nahoršia.
{27885}{27989}/Základní nastavení -> Soukromí -> Blokovaná èísla -> VYPNOUT/
{28230}{28271}Preèo trucuješ?
{28302}{28337}Poèula som od Setsuny....
{28337}{28383}O èom?
{28383}{28529}e si nasledoval Katsuru-san,|i keï sa a Setsuna snaila zastavi.
{28630}{28680}Setsuna sa mi ospravedlnila.
{28701}{28777}Pretoe Kiyoura je krutá ku Kotonohe.
{28818}{28917}Vdy hovorí, e sa pre Kotonohu cítiš zle, Sekai.
{28917}{28954}To je pravda, ale....
{29143}{29163}Preèo si....
{29180}{29259}Chcela som a vidie. Chcela som sa porozpráva.
{29341}{29464}Keïe v škole na to nemám šancu a môj telefón nepracuje...
{29464}{29591}P-prepáè. Ten môj je pokazenı.
{29603}{29661}Teraz je to v poriadku.
{29748}{29787}Da ju do ignorovanıch?
{29787}{29864}Nemala si zachádza a tak ïaleko.|/Mal to urobi./
{29889}{29935}Setsuna...
{30028}{30049}Máš pravdu.
{30070}{30133}Tak mi pošli e-mail a základ.
{30169}{30214}Rozumiem. A....
{30243}{30363}Prepáè! Práve sa cítim zle.
{30385}{30418}Tak je to?
{30418}{30500}Naozaj sa ospravedlòujem. Pozval by som a na èaj, ale...
{30558}{30596}U-Um, potom...
{30745}{30806}Potom hádam nemôem pomôc.
{30898}{30952}Um, môem sa a opıta jednu otázku?
{30952}{31006}Áno.
{31025}{31062}Po festivalu....
{31089}{31149}chceš so mnou tancova?
{31210}{31246}Na konci festivalu?
{31246}{31352}Áno. Pozval ma Sawanaga-san.
{31412}{31464}Aha...
{31464}{31583}Sawanaga-san si myslel, e sme sa rozišli.
{31583}{31624}Nie je to vtipné?
{31689}{31769}Som Makotova priate¾ka po celı èas.
{31891}{31918}Tak...
{31918}{31979}Správne. Popremıš¾am o tom.
{32023}{32096}Vïaka bohu. Je to s¾ub.
{32271}{32300}Tie odchádzam.
{32337}{32362}Sekai!
{32495}{32541}Ak odídeš teraz stretneš sa s Kotonohou.
{32541}{32576}Fajn!
{32625}{32649}Sekai.
{33342}{33402}To nie je fér, Saionji-san!
{33551}{33639}www.mycolorfullife.blog.cz
