{1}{1}23.976
{333}{383}Katsura, milujem a.
{604}{619}Èo sa deje?
{634}{664}Niè.
{1625}{1654}TaSHee's Gang uvádí...
{1775}{1915}SCHOOL DAYS
{4379}{4397}Prepáè.
{4423}{4461}e som vèera neprišiel.
{4475}{4511}Makoto?
{4541}{4605}Èakal som pred salónikom.
{4626}{4654}Ako o tom vieš?
{4665}{4734}No, poèul som to od Katou.
{4748}{4773}Katou ti povedala?
{4796}{4832}Nedokáem to dobre vysvetli.
{4832}{4881}Nie je to v poriadku.
{4881}{4901}Ale...
{4901}{5007}Je to v poriadku...som šastná, e si mi to povedal.
{5339}{5373}Si veselı takto skoro ráno.
{5373}{5412}Vazerá to tak?
{5422}{5451}To je odporné.
{5451}{5529}To je hrubé. Povedaj, ako sa ti zapáèi.
{5589}{5612}Stalo sa nieèo?
{5623}{5657}To by som rada vedela.
{5719}{5749}Dobré ráno!
{5776}{5821}Si tie šastnı.
{5857}{5880}Dobré ráno, Makoto.
{5894}{5961}Ah, ráno. Stalo sa mu nieèo?
{5961}{6037}Netuším. Stalo sa nieèo dobré poèas festivalu?
{6071}{6093}"Dobré?"
{6110}{6148}Preèo sa pıtate mòa?
{6158}{6214}Nie, iba keï je to v súvislosti s Taisukem |potom sa pıtam teba, Kuroda.
{6229}{6293}Tak  Kuroda, nakoniec si Taisukeho nepozvala?
{6305}{6367}"Nakoniec?" Èo si tım myslel?
{6367}{6440}Mimochodom, my nie sme na javisku, správne?
{6440}{6480}Oh, to je?
{6480}{6570}To pretoe zákazníci nikdy neodchádzajú| pretoe si tak zlatá, správne?
{6594}{6658}Oh áno. Si nakrajšia èasníèka.
{6658}{6728}Tvoje lichôtky ma ani trocha netešia.
{6728}{6799}Mimo to, ty si flákal prácu väèšinu èasu.
{6799}{6853}H¾ade¾ som si svoju cestu.
{6853}{6918}Drte ho. Kto pozeral po kom?
{6918}{6966}Dobre....
{6966}{7042}Dal si si pauzu, keï som z teba| na moment spustila oèi. Bóe.
{7042}{7097}Neodpoèíval som tak moc.
{7097}{7188}Áno, áno. Folklórny tanec |páru trval do rána.
{7293}{7370}To je problém.
{7370}{7406}Z  èoho ste v rozpakoch?
{7518}{7608}Bol som tak vzrušenı minulú noc, e som nemohol spa.
{7608}{7664}Je to škoda, e sme spolu nemohli tancova.
{7687}{7724}Ale, urobím svoju èas.
{7735}{7788}Nezradím a.
{7849}{7892}Tak potom, ak je to s tebou v pohode.
{7957}{8101}Toto!  Vámena na tri mesiace zlıch obedov, moja sestra |mi dala tieto Vianoce špeciálne stravovacie lístky.
{8115}{8166}Stráv sladké, biele Vianoce so mnou.
{8177}{8204}Iba artujem.
{8249}{8283}Nerozumiem tomu o èom hovoríš.
{8316}{8376}Chodím s Makotom.
{8390}{8450}Èo to hovoríš? On je so Saionji.
{8450}{8569}Ja som Makotova priate¾ka. Preto |nemôem chodi s tebou, Sawanaga.
{8587}{8622}Prosím viac mi to neopakuj.
{8685}{8756}Niè k tebe necítim.
{8794}{8832}Prosím zabudni na vèerajšok.
{8858}{8873}Zbohom.
{9131}{9202}Makoto! Èo to znamená?!
{9212}{9247}Èo sa deje? Zdvihni sa.
{9247}{9318}Plánuješ pokraèova v chodení s Katsurou?
{9345}{9451}Nemám viac. Nemám |Katsuru. Nemám teba!
{9451}{9479}Dopekla kebye viem.
{9489}{9560}Si súèastne so Saionji?
{9627}{9663}Nie, èo to hovoríš?
{9683}{9787}Potom preèo je Katsura tak chladná ku mne |pokia¾ hovorí, e spolu stále chodíte ?
{9798}{9857}Napriek tomu je to nepochopite¾né.
{9872}{9930}Viac nie je niè medzi mnou a Kotonohou.
{9941}{9955}Naozaj?
{9955}{9988}Áno, naozaj.
{9988}{10077}Tak to nebolo klamstvo, keï mi povedala, e ma nenávidí?
{10100}{10147}Je to moné.
{10215}{10282}Èo budem robi?
{10404}{10421}Povedz Katsura.
{10444}{10512}Vèera tvoj priate¾ neprišiel však?
{10512}{10601}Nechceš aspoò pripusti, e si nám klamala?
{10614}{10685}Dobre, ja rozumiem nechceš aspoò poveda,| e a Itou podviedol.
{10714}{10743}Nebola som podvedená.
{10789}{10876}Èo to hovoríš? To je krajne podozrivé. Však Otome?
{10876}{10937}Áno.
{10952}{10975}Tak máš to.
{10985}{11065}Viem o všetkom dobre, e Katou má rada Makota.
{11082}{11159}Ale ospravedlòujem sa. Ja som Makotova priate¾ka.
{11222}{11240}Aha.
{11260}{11291}Je to všetko èo chcete poveda?
{11303}{11336}Potom, pôjdem.
{11336}{11359}Poèkaj.
{11429}{11490}Èo to robíš?
{11490}{11533}Ospravedlòujeme sa Katsura.
{11533}{11621}Aké neporiadne. Vezmeme to spolu okej?
{11917}{11969}Je naozaj v poriadku vyhodi to...
{12143}{12190}/Potom sa uvidíme v skladisku pri telocvièni./
{12259}{12272}Ukonèi pauzu.
{12331}{12357}Prepáè.
{12372}{12391}Neblbnú okolo.
{12558}{12584}Ah ïakujem.
{12608}{12646}Mailuješ s Katsurou?
{12735}{12751}Nie.
{12751}{12809}Si stále s Katsurou?
{12809}{12828}Nie.
{12842}{12896}Potom, k nej stále nieèo cítiš?
{12896}{12932}Povedal som u nie.
{12964}{13038}S Kotonohou som sa u rozišiel.
{13059}{13094}Vèera ma pozvala....
{13129}{13145}...ale nešiel som.
{13164}{13177}Naozaj?
{13177}{13211}Ver mi.
{13231}{13343}Mono sa nevyrovná v semestri s jej |emóciami. Ale èasom áno.
{13353}{13423}Rozíï sa s Katsurou správne a pozeraj sa len na Sekai.
{13452}{13496}Ako som povedal, rozišli sme sa.
{13496}{13514}Itou.
{13558}{13592}Pozeraj len na Sekai.
{13612}{13641}Prosím s¾úb mi to.
{13675}{13692}Kiyora.
{13715}{13747}Nemám pred odchodom iadny èas.
{13747}{13774}Tım myslíš...
{13789}{13858}Zajtra opúšam mesto.
{13872}{13928}Povieš o tom dnes Sekai?
{13953}{13974}Nepoviem.
{13987}{14016}To je naozaj zlé, však?
{14034}{14145}Nepoviem jej to kım mi nes¾úbiš, e Sekai ochrániš.
{14145}{14233}Sekai potrebuje niekoho kto jej pomôe.
{14284}{14378}Brali sme to tak, e je nám udelená aby sme spolu boli navdy.
{14399}{14457}Mysleli sme, e navzájom sme ako dve polovièky vcelku.
{14515}{14537}Preto...
{14589}{14681}Poznám ju len druhı semester.
{14691}{14740}A zaèali sme spolu chodi len nedávno.
{14759}{14820}Poveda mi, e jej mám pomôc teraz je trochu unáhlené.
{14876}{14892}Itou, ty...
{14924}{14992}Naozaj, nie je niè medzi mnou a Kotonohou.
{15045}{15164}Ale preèo bol Taisuke potlaèenı dojmom,| e som stále s Kotonohou?
{15164}{15197}Sawanaga je?
{15210}{15303}Je to nepochopite¾né odkedy sa stále |pıta èi som s Kotonohou alebo nie.
{15303}{15330}Makoto.
{15674}{15745}Vy dvaja ste èlenovia vıboru, tak preèo neupratujete?
{15757}{15803}Kotonoha, snáï toto nerobíš sama?
{15803}{15846}To nie je problém. Nie je toho ve¾a.
{15856}{15906}Nemôeš nies všetko sama.
{15920}{15956}Vezmem to pre teba.
{16102}{16125}Ïakujem ti ve¾mi pekne.
{16148}{16163}Dobre potom...
{16163}{16181}Makoto.
{16212}{16271}Si zajtra vo¾nı?
{16295}{16424}Moja jachta je po údrbe, tak bude |pravdepodobne vyzráaná, ale ak by si chcel...
{16438}{16476}Pozri Kotonoha...
{16491}{16548}Nie, on  má  zajtra stretnutie so mnou.
{16574}{16617}Je to tak. Prepáè.
{16620}{16657}To je pravda.
{16684}{16799}Je to náhle, a ty musíš ma u plány.
{16815}{16852}A èo budúci tıdeò?
{16852}{16915}No. Dobre, neviem ako to poveda, ale...
{16935}{17001}...nemyslím ši, e ešte pôjdeme niekde spolu.
{17028}{17122}¼udia nebudú rozumie ak zvolíme túto cestu naïalej.
{17146}{17224}To je klamstvo. Èo sa s tebou stalo?
{17276}{17366}Kiyora povedala si to? Ona sa spikla s Saionji.
{17378}{17409}Sekai nie je zapojená.
{17419}{17440}Neverím ti.
{17452}{17543}Saionji zariadila to isté.
{17554}{17579}To nemá zmysel.
{17593}{17699}Potom je to s tebou v poriadku? Poviem |èo sa stalo poèas festivalu.
{17728}{17764}Èo sa stalo poèas festivalu?
{17812}{17873}Môe to by problém ak sa to Saionji dozvie však?
{17883}{18006}Saionji  nevie èo cítiš. To preto ti |dávala takı necitlivı príkazy.
{18006}{18025}Tak...!
{18039}{18112}Tvoje city? O èom to hovorí?
{18129}{18257}V ten deò poèas školského festivalu,| keï si spal a Kiyora po....
{18407}{18454}...bozkala.
{18494}{18508}A?
{18556}{18631}Si k nám nepríjemná pretoe robíš takéto veci.
{18645}{18660}To je klamstvo.
{18676}{18752}Nikdy si si to nevšimla poèas stretnutí vıboru?
{18832}{18873}Potom, èo so Saionji?
{18873}{18948}Èo je medzi mnou a Sekai nie je tvoja staros.
{18960}{18971}Ale?
{18985}{19014}Nechoï blišie k nám. Nikdy viac.
{19049}{19111}Je to klamstvo, e Makoto?
{19130}{19172}Myslím, toto ráno, ty...
{19172}{19263}Iba som sa ospravedlòoval pretoe som neprišiel.
{19284}{19308}Prosím pochop to.
{19773}{19785}Ja...
{19800}{19905}a viac nemilujem.
{20668}{20716}Uvidíme sa. Pá pá.
{20752}{20801}Bóe. Kde si Makoto?
{20814}{20904}Nemôe na to pozera takto, ale Itou je pekne populárny. |Usti sa, e ho máš na vodítku.
{20936}{20989}Napriek tomu o zajtrajšku...
{21001}{21045}Rozlúèková párty dievèenského basketbalového klubu?
{21061}{21103}Nie som èlen, je to v poriadku?
{21103}{21204}Staršie študentky chceli aby prišlo èo najviac ¾udí.
{21238}{21295}V práci zaèína zajtra veèer, tak by to mohlo by fajn.
{21295}{21352}Okej, potom prídeš, správne?
{21363}{21429}To dos môe. Setsuna preèo neprídeš tie?
{21453}{21471}Rozlúèková párty?
{21471}{21516}Áno, poï tie, Setsuna.
{21533}{21555}Zajtra...
{21631}{21655}Zajtra nemôem prís.
{21675}{21693}Príliš zlé.
{21693}{21737}Tak ty odchádzaš?
{21755}{21790}Dobre, musím ís do práce.
{21805}{21830}A èo Itou?
{21830}{21946}Èakala som na neho skôr. Oh, áno bola si |s ním vyhodi smeti správne?
{21952}{21961}Áno.
{21982}{22054}Potom si dáva pauzu a pravdepodobne sa niekde zabáva.
{22078}{22106}To nie si ty, Sekai.
{22180}{22221}Nájdem Itou-a pre teba.
{22235}{22288}Naozaj? Ak to nie je príliš ve¾kı problém.
{22338}{22357}Ïakujem velmi peknì.
{22383}{22395}Pápá.
{22539}{22555}Pápá.
{22628}{22670}Heh, volala si ma aby sme robili to èo vèera.
{22684}{22706}Je to obaovanie?
{22706}{22733}Ako by mohlo?
{22744}{22813}Tak sa necítiš na to aby si z toho vycúval?
{22823}{22880}Dobre, je to vzrušujúce a tak to bola zábava.
{22902}{23000}Povedz... Vyzerá to akoby si o nieèom celı deò premıš¾al.
{23055}{23079}Nieèo také.
{23177}{23247}Vyzerá to, e hocièo èo urobím je problém.
{23260}{23286}I ja?
{23286}{23328}Nie, ty si...
{23419}{23460}Iste si prive¾a spal.
{23460}{23484}Tie si myslíš?
{23527}{23573}Som v pohode, keï je to takto.
{23588}{23673}Pretoe som si vdy myslela, |e si ma nikdy nevidel ako enu.
{23690}{23773}Som naozaj šastná, e ma ako enu vidíš.
{24118}{24135}Itou.
{24390}{24453}Onee-chan , èo tu robíš tak neskoro?
{24560}{24578}Onee-chan?
{24736}{24762}Èo môem robi?
{25093}{25116}Áno?
{25128}{25141}Itou?
{25156}{25179}Kiyora to si ty?
{25198}{25223}Si doma?
{25234}{25288}Samozrejme pozri sa ko¾ko je hodín.
{25300}{25318}To je dobre.
{25467}{25578}Èo si hovorila o èase, ktorı strávime spolu. |Rozmıš¾al som, e to bolo iba klamstvo pre Kotnohu.
{25616}{25659}Neodchádzaš v noci?
{25672}{25734}Predtım je tu nieèo èo musím poveda.
{25781}{25866}Itou, vèera po tom èo si robil v skladisku v telocvièni?
{25934}{25994}To nie je tvoja staros, však?
{25994}{26028}Je to o Sekai.
{26048}{26081}I keï som si myslela, e som a prosila.
{26098}{26158}Nie to tak, e som prestal ma rád Sekai.
{26170}{26202}Bolo to ako mám da...?
{26212}{26244}Tie sa s òou rozíï.
{26339}{26386}Ak sa to Sekai dozvie....
{26445}{26480}Dríš to kvôli mne v tajnosti?
{26527}{26550}V iadnom prípade to nemôem poveda.
{26607}{26640}Preèo robíš tak ve¾a?
{26664}{26687}Je to pre Sekai.
{26700}{26723}Pri najmenšom to je tvoje právo.
{26739}{26801}Ale je to pretoe, e ma máš rada však?
{26801}{26834}To nie je pravda!
{26847}{26877}Ale nie je to ani tak, e ma nemáš rada však?
{26911}{26966}V tom vèerajšom bozku som cítil vášeò.
{26980}{26993}Mıliš sa!
{27220}{27254}Rozíï sa s tım dievèaom.
{27281}{27350}Tak ako si sa rozišiel s Katsurou. Prosím.
{27379}{27475}Urobím hocièo ak mi to s¾úbiš.
{27509}{27523}Hocièo.
{27663}{27677}Ja...
{27754}{27798}Tak tu bude rozlúèková párty?
{27812}{27846}Dobre, naša klubová miestnos je príliš malá.
{27895}{27943}Tak zvládla si vèera nájs Itoua?
{27943}{28042}Nekontaktovala som sa s ním. Napriek tomu |Setsuna povedala, e sa po òom pozrie.
{28042}{28076}Tak si ich nemohla zkontaktova.
{28087}{28134}Potom sa do toho musíš dosta.
{28170}{28214}V iadnom prípade to sa nemôe sta.
{28227}{28280}Èo ty Nanami? Ako to ide s tvojim priate¾om?
{28297}{28370}Dobre, veci idú tak ako majú, myslím.
{28370}{28410}Preèo tyyy....!!
{28427}{28497}Tvoj priate¾ je starší tak a musí ohrozova láskavo èo?
{28497}{28531}Èudujem sa.
{28586}{28610}Otome, meškáš.
{28637}{28727}Toto je prvı krát èo sa stretávate?| Od toho èasu na telesnej.
{28727}{28747}Áno.
{28762}{28794}Toto je Saionji Sekai.
{28807}{28870}Starší študenti sa ma pıtala èi nezoeniem |starších ¾udi tak som ju priniesla samú.
{28881}{28892}Teší ma.
{28906}{28923}Áno, teší ma.
{28950}{28984}Dobre, zaèíname.
{29039}{29082}Všetkım ïakujem za èakanie.
{29082}{29190}Dobre teda oèakávaná špeciálna prezentácia ako to zaèalo.
{29212}{29246}Tak nie je to rozlúèková párty?
{29262}{29297}To som poèula.
{29492}{29507}Nanami.
{29548}{29681}Skutoène bola ukrytá kamera v salóniku,| o ktorom ste všetci vedeli poèas festivalu.
{29691}{29750}Senpai, nie je to vulgárne?
{29750}{29766}Áno.
{29797}{29860}NIEE!!!
{29895}{29982}Môeš spomína na tento školskı |festival. Zabávala si sa však?
{30047}{30100}Odchádzame dobre?
{30176}{30241}Wow, Katou to vzala iniciatívne.
{30448}{30462}Nemoné!
{30605}{30617}Makoto!
{30651}{30689}Makoto, zdvihni to!
{31132}{31164}Zdvihni, Makoto!
{31226}{31245}Makoto!
{31427}{31463}Katsura?
{31562}{31578}Katsura.
{31624}{31643}Saionji...
{31692}{31719}Vieš kde je Kiyora?
{31753}{31814}Mono je dnes s Makotom.
{31841}{31927}Odchádzala z Makotovho domu. A nie je u seba.
{31947}{31990}Mono sú niekde spolu.
{32117}{32165}NEVYPÍNAT! :)
{34559}{34573}Kiyora!
{34607}{34631}Kiyora!
{34903}{34926}Kto s tebou sedí Setsuna?
{34965}{34977}Èislo 4.
{34977}{35007}To znamená...
{35086}{35121}Setsuna vymeníš sa so mnou?
{35135}{35150}Sekai?
{35163}{35201}Vymeníš sa prosím so mnou?
{35221}{35264}Sekai nehovor mi....
{35290}{35299}Nie...
{35433}{35487}Nemôeš?
{35559}{35586}Iste to je fajn.
{35803}{35818}Zbohom.
{35841}{35880}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime
{35880}{35910}www.mycolorfullife.blog.cz
