{1}{1}23.976
{1238}{1353}/elám si aby som ti povedala správne prepáè.| Mala som ti to poveda, ale bolo to príliš aké vysvetli.| Namiesto toho som ti poslala mail. Prepáè./
{1772}{1843}Je zima, e? Myslíš, e bude snei?
{1890}{1937}Toto je nezvyèajná situácia, keï o tom premıš¾as nemyslíš?
{1950}{1960}Èo také?
{1980}{2076}Vzal si ma sem namiesto uk¾udòovania Sekai.
{2092}{2156}I keï som s tebou zamotaná v tomto chaose.
{2178}{2218}Preèo to hovoríš tak zrazu?
{2235}{2254}Len tak.
{2269}{2282}Iba to...
{2305}{2380}...pochopila som to èo si robil so Sekai.
{2441}{2493}Tak, nechceš skúsi ju zajtra znova navštívi?
{2537}{2572}Nebojíš sa?!
{2603}{2733}Hej, vieš, e jej dochádzka bola mnoho dní naozaj biedna, e?
{2752}{2781}To je otravné.
{2839}{2855}Tak povedal.
{2881}{2941}Pretoe tebe pravdepodobne staèí stretáva sa s inım dievèaom, e?
{2941}{3031}Iba pretoe Sekai nie je na okolí ty blbneš s kadım.
{3045}{3077}Iba ty, Hikari.
{3077}{3100}BAAAKA!
{3169}{3211}Ty si naozaj najhorší.
{3237}{3278}To isté platí pre teba, e?
{3290}{3310}Hádam.
{3326}{3383}Všetko sa stáva takım otravnım.
{3383}{3414}Hej.
{3673}{3705}TaSHee's Gang uvádí...
{3820}{3964}SCHOOL DAYS
{6492}{6566}Ako som povedal, všetko èo sme robili  je,| e sme sa videli na zastávke.
{6566}{6648}Klamár, Klamár, Klamár! Viem, e klameš!
{6661}{6733}Viem kde si išiel s Katou-san.
{6750}{6792}Preèo? Ako si mohol?
{6811}{6832}Èo som urobil?
{6876}{6914}Nie som pre teba dos dobrá?
{6936}{6987}Všetko si nechal, Makoto.
{7008}{7091}Setsuna odišla teraz. Si všetko èo mi ostalo.
{7132}{7195}Prosím, Makoto!
{7621}{7635}Hej!
{7668}{7743}Itouova malá sestra dnes odišla z toho miesta.
{7763}{7776}Aha.
{7776}{7851}Mám ho donúti aby prišiel?
{7904}{7933}Poèkaj.
{7933}{7956}Prepáè.
{7975}{8029}Necítim sa na rozprávanie. Práve teraz.
{8029}{8139}Dobre. Správne. Nanami sa teraz cíti o dos lepšie.
{8139}{8198}Dokonca sa zdá, e je to dobre aj v klube.
{8209}{8273}Rozumiem to, e Setsuna odišla musel by šok...
{8283}{8396}...ale myslela som, e je èas ukáza tvoju |tvár a tak sa všetci prestanú obáva.
{8424}{8472}Keï nie si v okolí, Itou...
{8483}{8537}...vieš, môe sa sta nevernım.
{8771}{8796}/Pre: Itou Makoto Váš Mail nebol odoslanı./
{9212}{9309}/Máte 30 sekúnd na zanechanie odkazu po pípnutí./
{9326}{9391}Makoto, dopekla kde si.
{9404}{9452}Otome, choï domov.
{9462}{9516}Hej, pomô mi nájs Makota.
{9555}{9602}Nemá to s nami èo robi, však?
{9616}{9660}Ste tie, ktoré ma v tom povzbudzovali nie?
{9660}{9697}To je pravda, ale...
{9697}{9753}Èo s tım môeme robi?
{9753}{9778}Prevzia zodpovednos!
{9778}{9832}Nieèo zaènete a teraz to zahodíte?
{9832}{9879}Neviem kde je.
{9888}{9907}Potom fajn.
{9932}{9985}Špeciálne potom èo bol s Katusrou to vrelo.
{9997}{10013}Bóe.
{10049}{10105}Otome je v poslednej dobe iná, však?
{10105}{10159}Stáva sa podrádenou. Naháòa mi to husiu kou.
{10159}{10192}Od tej doby, správne?
{10206}{10236}Ah, to!
{10261}{10304}To bolo vcelku dos, e?
{10304}{10323}Pozerala si to?
{10345}{10411}Bola som tá, ktorá to natáèala.
{10411}{10458}Ostala si hrozne pokojná.
{10458}{10573}Dobre, samozrejme bola som rozpakoch, |ale ukazovalo sa to len medzi dievèatami a...
{10582}{10602}...on.
{10602}{10662}Áno, áno ïakujeme za varovanie.
{10701}{10777}Bóe rozprávanie o Otome a tom dievèati...
{10819}{10868}.....hádam si nemôe dovoli prehra.
{10887}{10902}Natsumi?
{10944}{11015}Som zvedavá èo ma Itou rád....
{11036}{11071}Èo tım myslíš?
{11142}{11200}Bóe, robi to na mieste ako je toto u znova.
{11200}{11323}Je to v pohode nikto toto miesto nepouíva. |Nemusíme sa bá pristihnutia.
{11323}{11343}Povedz...
{11343}{11397}Èo je? Ïalšie kolo?
{11397}{11447}BAKA! Nie to.
{11460}{11523}Je to naozaj v poriadku nenavštívi Sekai?
{11560}{11644}Ak má èas na blbnutie so mnou potom| ju na chví¾u be pozrie.
{11699}{11714}Bóe.
{11943}{11978}Je to v pohode, nikto sa to nedozvie.
{12075}{12185}Áno, prosím pozvi Saionji a môeme spolu obedova na streche.
{12207}{12279}Dám všetko do obeda.
{12304}{12368}Budú tam všetky veci, èo máš rád, Makoto.
{12401}{12519}Bude to v poriadku. Mama ma pochválila |a povedala, e to robím dobre.
{12532}{12575}Dobre, nechaj to na mòa.
{12822}{12856}/Chcem a vidie Sekai./
{12856}{12915}/Nechcem sa u dlhšie dra spa./
{12915}{12964}/Ty si to jediné èo chcem./
{12964}{13008}/Idem s Makotom, ta prosím poèkaj./
{13318}{13335}Vítaj.
{13454}{13470}Bóe.
{13491}{13520}Ste váni?
{13535}{13571}O to sa neboj.
{13571}{13617}Ty si tá, ktorá to navrhla, nie?
{13621}{13666}Je trocha neskoro zastavi.
{13682}{13712}To je pravda, ale...
{14100}{14188}Strávi  Vianoce na lodi môe by tie pekné, e?
{14214}{14239}Vedel si?
{14259}{14384}H¾adie na slnko a sedie v horizonte nikto |nás nebude otravova na otvorenom mori...
{14398}{14455}...je to naozaj krásne vieš?
{14593}{14618}/ Itou by teraz mal by v tvojom dome./
{14618}{14647}/Odfotila som to. Tu máš./
{14906}{14928}Setsuna....
{14951}{14972}Makoto....
{15590}{15606}To nie je moné!
{15629}{15723}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime
{16145}{16165}Sekai?
{16541}{16580}Musím s tebou hovori.
{16606}{16626}Je to v poriadku?
{16655}{16679}Èo je to?
{16701}{16726}Je to ve¾mi dôleité.
{16758}{16775}Neprišlo to.
{16794}{16833}Èo neprišlo?
{16866}{16908}Moje obdobie...
{16920}{16992}To znamená...to nemôe by.
{17072}{17099}Klameš, e?
{17099}{17158}Akoby by bolo moné klamar alebo vtipkova| o nieèom takomto?
{17198}{17276}Nikdy som to nerobila s nikım okrem teba.
{17292}{17319}Robila som to iba s tebou, Makoto.
{17319}{17370}Take, hovoríš, e je to moje?
{17370}{17420}Je to samozrejmé nemôe by nikoho iného.
{17448}{17504}Ale stále sme študenti...
{17504}{17538}To je pravda, ale...
{17593}{17636}Napriek tomu ako sa to mohlo sta?
{17636}{17696}To preto sa s tebou chcem rozpráva.
{17706}{17778}Ja i tak nebudem vedie ak sa ma pıtaš!
{17800}{17834}Je to tvoje diea, Makoto!
{17854}{17885}Rozmyš¾aj váne preboha!
{18413}{18432}Poèula si to?
{18448}{18486}Vyzerá to naozaj zlé ako predpokladám.
{18874}{18888}Ale...
{18917}{18972}Je to správne, je to Makotove...
{19021}{19037}....diea.
{19122}{19161}My budeme v poriadku správne?
{19175}{19206}Robili sme to starostlivo.
{19221}{19236}Dúfam.
{19249}{19305}Ale èo budeme odteraz robi?
{19319}{19361}Bude to lepšie ak sa s ním chvi¾u |nebudeme stretáva správne?
{19373}{19394}To je pravda.
{19411}{19450}Fajn, je to príliš zlé.
{19450}{19501}Máš priate¾a, tak to nehovor.
{19817}{19854}Pıtala sa ma èo budem robi.
{19869}{19904}Budeš kosi svoju úrodu správne?
{19917}{19952}Vy chlapci to nerobíte poriadne?
{19966}{19992}Tenkrát....
{20008}{20062}...som to nepouil.
{20081}{20112}Ponáh¾al som sa a bol som neopatrnı.
{20169}{20227}Ak si mu, tak prevezmi zodpovednos.
{20239}{20275}Ale èo budem robi?
{20343}{20362}Kam ideš?
{20394}{20527}Cítim, e sa mi stene rovnaká vec ak |sa s tebou budem stretáva.
{20693}{20725}To je on!
{20725}{20745}On?
{20745}{20816}Má takú slušnú tvár. Kto oèakával nieèo také?
{20816}{20848}Práve naopak, správne?
{20848}{20894}Bóe, chlapi to majú dobré.
{20894}{20936}Keï skonèia, je pre nich po všetkom.
{20936}{20983}Dievèatá zachova zodpovednos.
{21052}{21080}/Adresár: Itou Makoto/
{21106}{21127}Odišiel skoro?
{21148}{21213}Dobre vieš. Nie je to neoèkavávané.
{21230}{21274}Je centrom pozornosti po tom všetkom.
{21292}{21318}Èo jeho priate¾ka?
{21331}{21369}Stále je na ošetrovni?
{21902}{21920}Sakra.y
{22001}{22039}Preèo povedala nieèo také?
{22039}{22072}Tá Sekai.
{22225}{22241}Otome?
{22327}{22377}Áno, som teraz vo¾nı.
{22393}{22431}So tak vo¾nı, e sa to stáva problémom.
{22441}{22490}Áno, si vítaná.
{22490}{22524}Prosím príï.
{22758}{22776}Vítaj.
{22887}{22900}Otome?
{22917}{22963}Chcela som sa spıta jednu vec.
{22977}{23032}Ak je to o Sekai potom to nebola moja chyba.
{23121}{23137}Aha.
{23137}{23171}Je to tak.
{23184}{23215}Tak sa tım prosím netráp.
{23236}{23251}Makoto....
{23275}{23324}nie si typ èloveka, ktorı hovorí veci ako tamto, však?
{23382}{23440}Poèas strednej školy, si bol lepšia osoba.
{23440}{23486}Um, ale potom....
{23504}{23519}Nevadí.
{23537}{23559}Odchádzam.
{23594}{23608}Zbohom.
{23923}{23942}Baka.
{24310}{24381}To môe by nešastná udalos pred Vianocami.
{24381}{24416}Nešastná?
{24416}{24489}Správne v tomto èase namiesto Kuminho priate¾a.
{24509}{24538}To môe by dobrá myšlienka.
{24538}{24575}Nie nemôete to robi.
{24575}{24646}Preèo nie? Je zviera.
{24889}{24974}Prepáè, e som ti tie robila starosti, Hikari.
{25005}{25042}Áno, teraz som v poriadku.
{25063}{25118}Makoto? Kúpila som nieèo pre neho.
{25151}{25207}artujem. Potrebujem vıivu. Myslím.
{25265}{25279}Nie.
{25331}{25407}Ah, prepáè. Ïakujem. Ahoj.
{25579}{25593}Odpus mi.
{25614}{25652}U sa k nemu viac nepriblíim.
{25863}{25905}Mala som prive¾a pátrania.
{25923}{26043}Tak to vyzerá, e otec má nejaké spoje s horami Sakakino.
{26043}{26091}Tak myslím, e môeme dosta ¾ahko rezerváciu.
{26132}{26213}Správne môeme sa stretnú pri strome na stanici?
{26230}{26358}Potom sa môeme sta skutoènım párom.
{27348}{27363}Otome....
{27474}{27516}/V tejto chvíli nemôeme uskutoèni tento hovor./
{27533}{27649}/Po pípnutí máte 30 sekúnd na zanechanie odkazov./
{27667}{27684}Sakra.
{27718}{27731}Hikari?
{27840}{27892}/V tejto chvíli nemôeme uskutoèni tento hovor./
{27909}{27935}/Po pípnutí máte.../
{28005}{28059}/V tejto chvíli nemôeme uskutoèni tento hovor./
{28109}{28146}/V tejto chvíli nemôeme uskutoèni tento hovor./
{28200}{28225}Èo je so všetkımi?
{28240}{28288}Preèo nikto nedvíha?
{28353}{28369}Dopekla.
{28398}{28443}Preèo sa toto muselo sta mne?
{28515}{28594}Iba nedávno všetko išlo tak ¾ahko.
{28631}{28667}A ešte, preèo?
{29067}{29107}Kúzlo lásky?
{29118}{29162}Itou, si pekne modernı.
{29228}{29283}Kúzlo lásky, huh?
{29348}{29362}Kotonoha...
{29378}{29399}Makoto-kun?
{29547}{29571}Vïaka bohu.
{29590}{29624}Prišiel si.
{29801}{29854}Èo si robila, keï vyzeráš takto?
{29876}{29903}Èakala som.
{29936}{30010}Èakala som na teba, Makoto.
{30037}{30060}Kotonoha...
{30356}{30377}Makoto...
{30445}{30543}Saionji -san mi povedala, e mi môe pomôc.
{30577}{30730}Tak som sa stala vhodnım dievèaom pre teba.
{30741}{30781}Kotonoha?
{30804}{30870}Vari pre teba, pomáha ti...
{30894}{30941}Musím sa uèi omnoho tvrdšie.
{30976}{31061}Musím uchopi svoju hruï tak môem by po tvojom boku.
{31132}{31154}Kotonoha?
{31168}{31234}Stanem sa tvojou priate¾kou potom sa nemusíš hanbi.
{31286}{31304}Kotonoha!
{31304}{31337}Pre teba Makoto.
{31363}{31383}Hej...
{31400}{31449}Chcem by pre teba uitoèná.
{31449}{31506}Èo sa s tebou stalo?
{31506}{31550}Je to pretoe chcem by s tebou.
{31586}{31621}Ušetri ma tohto...
{31621}{31656}Verím v teba.
{31692}{31730}Prosím prestaò!
{31753}{31825}Pretoe, ja som tvoja priate¾ka.
{31855}{31891}To staèilo...
{31946}{32019}Milujem a.
{32073}{32097}Naozaj a milujem.
{32113}{32234}Ako? Preèo...? Ma chceš?
{32317}{32368}Ja...Ja...
{32391}{32417}Nikdy som nevedel...
{32442}{32458}Odpus mi.
{32522}{32553}Naozaj sa ospravedlòujem.
{32574}{32606}Ja...Ja...
{32663}{32715}Kotonoha, Ja...
{32729}{32764}Kotonoha, Ja...
{33512}{33531}Makoto...
{33567}{33609}www.mycolorfullife.blog.cz
