{1}{1}23.976
{2493}{2548}Pronásledujíc Dillase po jeho|krádei Meèe Svìtla...
{2549}{2603}...jsme skonèili uvnitø|hlavní Valgaavovy základny.
{2604}{2691}A k našemu pøekvapení|tam byl také Almes.
{2709}{2729}A ten...
{2730}{2901}Vıbušná situace!|Ten kdo drí klíè!
{2902}{3040}Co chceš?
{3060}{3189}Nech mì domluvit.|Dùvod proè jsem pøišel za tebou...
{3190}{3318}...je e tì chci pøetáhnout|na stranu rodu Monster.
{3343}{3417}Abys vìdìl, tak smutná|pravda o rodu Monster...
{3418}{3483}...je, e má nedostatek tak|talentovanıch lidí jako jsi ty.
{3494}{3537}Smìøování té bitvy...
{3538}{3600}...povolání pána Nadsvìtí, Darkstara...
{3601}{3668}...se pro nás jeví velmi dùleité.
{3669}{3769}Kdy se naši vysoko-postavení|k tomu pøiklání...
{3770}{3858}...tak naše obvyklé potíe|s Bohy, nám to znemoòují.
{3881}{3960}Proto jsem pøipraven|zaruèit velkı pardon...
{3961}{4047}...kdy dostanu záruku,|e se pøidáte k rodu Monster.
{4049}{4134}A jistì jsme pøipraveni|poskytnou i nìjaké kompenzace.
{4135}{4170}Kompenzace?
{4181}{4259}Pokud budete souhlasit|s pøipojením k nám...
{4290}{4359}...pak osoba odpovídající|za Gavovu smrt...
{4387}{4437}Ano, Lina Inverse...
{4438}{4499}...vám bude mnou|osobnì, doruèena.
{4583}{4631}Co... co to øíká?
{4661}{4694}Ach, boe. To je Filie.
{4695}{4834}Xellosi! Obchoduje s Lininım ivotem,|abyste dostal Valgaavy na vaši stranu?
{4845}{4898}Ach? To obvykle|Knìka Ohnivého Draèího Krále...
{4899}{4951}...poslouchá za dveømi?
{4952}{4993}O to se nestarej.
{4994}{5047}Myslel jsi vánì to,|cos právì teï øekl?
{5048}{5077}Jistìe vánì!
{5078}{5178}Rád zabiji Linu vlastní rukou!
{5205}{5271}Nejste pøítelem sleèny Liny?
{5272}{5363}Ne. Jednoduše s tou|její partou cestuji...
{5364}{5446}...protoe se èasto jejich zájmy|pøekrıvají s mımi vlastními.
{5469}{5522}Prosím, nezapomeò...
{5524}{5576}...jsem Monstrum, víš?
{5601}{5629}Ach, ne...
{5710}{5849}Almesi! Nechceš povolat Darkstara|pro znièení tohoto svìta?
{5860}{5975}Ne. Mım skuteènım cílem|je znièit Darkstara.
{6010}{6038}Co to znamená?
{6049}{6121}Ve skuteènosti jsem|sluebníkem Volphieda...
{6122}{6193}...v jeho nekoneèném|boji proti Darkstarovi.
{6205}{6254}Sluebník Volphieda?
{6255}{6341}To znamená, e bojuješ|na stranì Bohù?
{6350}{6392}No mùeš to i takhle øíct.
{6481}{6564}Uch, och... ale opravdu|nevypadáš jako bùh, víš.
{6643}{6834}Po nepøedstavitelnì dlouhou dobu|jsme bojovali s Darkstarovımi silami.
{6835}{6998}Ta strašná válka|konèila naší zkázou.
{7025}{7153}Darkstarovım skuteènım zámìrem|bylo znièit nás i s naším svìtem.
{7166}{7252}A jak chtìl tak konal.|Mysleli jsme, e náš domov...
{7253}{7293}...naprosto znièí.
{7294}{7416}Ale... energie, kterou získal pohlcením|Volphieda pøi jeho poráce...
{7417}{7476}...se zaèala vymykat jeho kontrole.
{7489}{7569}A tak znièil síly, svıch následovníkù...
{7570}{7648}...bìhem té šílené války démona zkázy.
{7675}{7740}Darkstar zapomnìl na|svùj skuteènı zámìr...
{7741}{7810}...a pustil se do války|proti všem ivım vìcem.
{7811}{7913}A proto na konci zbyla jen mrtvá pouš.
{7970}{8065}Ale proè jsi pøišel na náš svìt?
{8077}{8197}Pøeivší zaèali zoufale hledat|zpùsob, jak znièit Darkstara.
{8198}{8316}Pak jsme se doslechli o pìti|zbraních stvoøenıch Darkstarem.
{8330}{8402}Jedna z nich je Meè Svìtla, Gorun Nova.
{8433}{8501}A také jsme zjistili,|e síla tìchto pìti zbraní...
{8502}{8569}...mùe rozbít na kusy|Darkstarovu vlastní moc.
{8580}{8612}Rozbít na kusy jeho moc?
{8613}{8715}Pøesnì. Stejnì jako byl Shabranigdo na|tomto svìtì roztøíštìn na sedm kusù...
{8716}{8821}...tak bychom mohli pouít tìch pìt zbraní|jako bránu pro rozdìlení Darkstarovi moci.
{8822}{8874}A pak znièit kadou|jeho èást samostatnì.
{8875}{8959}Tento plán jsem pøišel uskuteènit.
{8960}{9042}Hmm... take tohle všechno znamená co?
{9190}{9247}Teï není èas zamıšlet se|nad nepochopitelnımi vìcmi!
{9248}{9301}Máme potíe!|Velké potíe, dobøe?
{9302}{9333}Dobøe! Tomu rozumím.
{9356}{9406}Tak, má ten pøíbìh pokraèování?
{9424}{9520}Pøi hledání pìti zbraní jsme|prošli mnohımi svìty.
{9535}{9593}A nakonec jsem pøišel na tenhle.
{9604}{9662}Zbytek znáte.
{9663}{9740}Pøišel jsem najít dvì poslední zbranì,|ukryté na tomto svìtì.
{9750}{9797}A spojil jsi své|síly s Valgaavem.
{9896}{9939}Teï kdy jsme získali|zpátky Meè Svìtla...
{9941}{9981}...je kadá další minuta|tady nebezpeèná.
{9983}{10034}Musíme najít Linu a ostatní|a vypadnout odtud.
{10035}{10053}Ano!
{10066}{10106}Netahejte mì tak tvrdì!
{10107}{10207}Mlè! Kdybys nedìlal problémy,|mohls bìet s námi!
{10280}{10377}Tak, teï... co odpovíte na mùj návrh?
{10379}{10474}Pøipojíte se k rodu Monster, nebo...
{10475}{10571}Nedìlej to! Valgaave, spojení|s rodem Monster mùe bıt chyba.
{10572}{10661}Ach, tak vy se ho chcete zeptat,|zda by se nepøipojil k vašim lidem, co?
{10691}{10720}No...n..
{10721}{10782}Právì jen plıtváme|naším èasem, nemyslíte?
{10783}{10867}Kdy si uvìdomíme jak zlatí draci...
{10868}{10951}...vyvradili kmen Pradávnıch Drakù.
{10983}{11083}Zlatí Draci se tak báli jejich sil...
{11084}{11160}...e sebrali obrovskou|armádu a vymazali je ze svìta.
{11256}{11311}Mlète! Mlète! MLÈTE!
{11375}{11436}Vy Monstra nejste jiní!
{11437}{11495}Nepokoušel se váš|rod zabít Pána Gaava...
{11496}{11569}...protoe se báli e se jednou|jeho síla otoèí proti nim?
{11570}{11603}No, to je pravda...
{11604}{11679}Tak a Monstrum jako ty nemá|co dávat samolibou lekci...
{11680}{11749}...z dùvodu, e mí lidé byli vyhlazeni!
{11765}{11833}Jedinı, kdo mi pomohl byl Pán Gaav!
{11848}{11960}A já nikdy rodu Monster|neodpustím jeho zabití!
{11972}{12055}Take tomu mohu rozumìt tak,|e o dohodu nemáte zájem?
{12071}{12115}Tohle je má odpovìï!
{12232}{12256}Pøedpokládal jsem to.
{12257}{12327}Od zaèátku jsem vìdìl,|e jen plıtvám dechem.
{12345}{12417}Ale pro poøádek jsem|vám tu nabídku uèinil.
{12432}{12491}Teï je v poøadí další krok.
{12506}{12623}Pokud se nepøipojíte, pak|vás musím nevyhnutelnì zabít.
{12637}{12688}Obávám se, e jsme teï nepøátelé.
{12689}{12739}Tys byl mùj nepøítel|u od zaèátku!
{12869}{12893}Tak poèkej chvíli!
{12894}{12960}Pokud tvım cílem bylo|zabít Darkstara...
{12961}{13039}...proè jsi nepoádal lidi|na tomto svìtì o pomoc?
{13061}{13162}Protoe mi øekli, e mi zaruèenì nikdo nepomùe.
{13182}{13264}Darkstar pøi téhle práci|mùe bıt povolán.
{13275}{13385}A to by pak znamenalo|zaruèenı hrob pro tento svìt.
{13386}{13483}Jak si mùete myslet, e bych našel|nìkoho kdo by mi s tím pomohl?
{13511}{13579}Ne, neøíkám e jste vy lidé špatní.
{13580}{13632}Obvykle neádám o pomoc.
{13633}{13721}To co by mohlo zkomplikovat mé zadání...
{13722}{13798}...by bylo nadìlat si tu nepøátele.
{13829}{13851}Chápu to...
{13880}{13968}My jsme byli urèeni|chránit tento svìt!
{13969}{14052}Pro to my obìtujeme|i Meè Svìtla!
{14066}{14142}V chrámu, i takovı sluebník Boha...
{14143}{14233}...jako Nejstarší, dokáe myslet|jedinì na tento svìt.
{14235}{14323}Není divu, e Almes vycítil,|e na nìm nemùe záviset.
{14324}{14418}Ale teï jsem poznal, e se Valgaav|chystá pøivolat Darkstara...
{14419}{14496}...ještì pøed tím ne bude|shromádìno všech pìt zbraní.
{14497}{14573}Pokud to udìlá, nebudeme|schopní rozdìlit Darkstarovu moc.
{14574}{14612}Musíš s tím nìco dìlat!
{14613}{14684}Pokud se ten sem dostane, pak všechno|pìkné a zdravé na tomto svìtì...
{14685}{14721}...skonèi.
{14722}{14852}Hmm... sice nevím proè, ale|tohle my nemùeme dovolit, co?
{14876}{14913}Nesmíme ztrácet èas.
{14914}{14980}Musíme hned dostat|Meè Svìtla zpátky!
{15546}{15603}Ty... synu...
{15644}{15694}Nemùete mì podceòovat, pøíteli.
{15695}{15773}Navzdory vzhledu, jsem zabil|tisíce vašich dìtí...
{15774}{15873}...ve Válce Pádu Monster.
{15924}{16041}A ty nepodceòuj|moc kterou mám já!
{16087}{16157}A také moc Pána Gaava!
{16285}{16380}Tak tohle je skuteènì všechna|moc, kterou ti Gaav dal?
{16381}{16418}Ticho! K èertu!
{16933}{16953}Co je to?
{16954}{17023}Myslíte, e nìco stalo|Linì a ostatním?
{17024}{17048}Jdeme!
{17049}{17072}Ano!
{17103}{17153}Nechte mì tu!
{17251}{17291}Co, ty!
{17484}{17563}Nezáleí na tom kolikrát|vystøelíš, kdy mì nezasáhneš!
{17564}{17615}Víš...
{17639}{17715}...malı vìtøík mùe zpùsobit i velkou zkázu|pokud nic proti nìmu neudìláš.
{17766}{17798}Valgaave!
{17962}{18001}K èertu s tebou...
{18097}{18144}Ještì jsi nic nepochopil?
{18177}{18203}Ne!
{19205}{19322}Tohle mìlo Valgaava pøekvapit.|Hádám, e to nezabralo.
{19333}{19372}Ty jsi tak odpornı...
{19386}{19456}No, tak co, neskonèíme to?
{19467}{19524}To bych i já rád.
{19582}{19653}Sice nevím co,|ale nìco jistì zaèalo.
{19666}{19723}Vypadá to, e Valgaav bojuje.
{19724}{19763}Radìji si pospíšíme.
{19786}{19823}Svìtlo, vyjdi!
{20255}{20282}Xellosi!
{20296}{20427}Vypadá to, e... e jsem|opravdu tuhle práci zpackal...
{20435}{20504}Varoval jsem tì, abys|mì nepodceòoval!
{20521}{20582}Nenávidím oba vaše rody...
{20583}{20677}Já, se silou Drakù|a pána Gaava.
{20700}{20750}Øekni mi co cítíš!
{20782}{20803}Tudy!
{20814}{20841}Sleèno Lino!
{20842}{20919}Co? Co vy tady?|Proè jste šli sem?
{20939}{20963}Xellosi?
{20964}{21019}Ty jsi bojoval Valgaave?
{21031}{21066}Co se to stalo?
{21067}{21129}Ach boe... nabídl jsem mu|tebe vımìnou...
{21130}{21218}...za jeho pøipojení|k rodu Monster.
{21247}{21321}Rozzuøil se z toho jak|jsem ho zkoušel oklamat.
{21322}{21383}Diskuse èasto plodí neèekané následky.
{21407}{21457}Nìco se dìje?
{21512}{21545}Jej! To bolí!
{21546}{21601}Tohle je všechno co s ním udìláte?
{21602}{21698}Xellos zkoušel prodat|váš ivot Valgaavovi!
{21710}{21787}No, Xellos je Monstrum, tak bych|od nìj nìco takového èekala.
{21801}{21870}Známe se dobøe, tak se chápeme, víš?
{21871}{21916}Co? Och... opravdu...
{21917}{22047}Vımìnnou dostávám k pouití|Xellose, vdy kdy ho potøebuji.
{22064}{22103}Uch... do...bøe..
{22104}{22133}Nicménì...
{22134}{22198}Náš pøítel tady, vidím,|doznal nìkolika zmìn.
{22199}{22300}Ano. Pokud s ním zamıšlíš bojovat,|pak prosím, buï opatrná.
{22315}{22372}Zaplatíš za zranìní Xellose!
{22390}{22422}Ach! Zapomnìl jsem!
{22455}{22489}-Lino!|-Pane Gouury!
{22513}{22542}Zele! Amélie!
{22555}{22600}Vypadá to e jsme tu vèas.
{22601}{22644}Nechte mne jít!
{22645}{22686}Tady, pane Gourry!
{22687}{22780}V poøádku!|Tohle je mùj meè!
{22791}{22825}Tak tentokrát se do toho dáme!
{22826}{22858}U jsem jeden pøíkaz dala!
{23128}{23207}Tak, všichni jste teï tady...
{23234}{23326}Almesi, ty jsi se opravdu obrátil proti mì, e?
{23337}{23441}To není pravda, ale nemohu|vás tohle nechat udìlat.
{23475}{23580}Ne pøijmeš vítìzství,|kdy bych z nìj mìl vıhodu.
{23581}{23603}Coe?
{23770}{23822}Filie, vem Xellose pryè odsud.
{23865}{23891}Ano.
{23908}{23943}Nepøišli jste otravovat.
{24003}{24052}Pøišli jste zemøít.
{24068}{24132}Nikdy bych si nepøedstavil...|e mi pomùeš.
{24133}{24183}O tom teï nebudeme|diskutovat!
{24214}{24258}Pøichází!|Burst Flare!
{24458}{24494}-Vyjdi, Svì...|-Gourry, NE!
{24495}{24534}Nepouívej Meè Svìtla!
{24561}{24585}K èertu!
{24733}{24771}Valgaave!
{25054}{25096}Vezmu si to zpátky!
{25272}{25290}Almesi!
{25291}{25360}Má síla... je opravdu...
{25391}{25457}...nad cokoli s èím mùete bojovat.
{25604}{25669}K èertu! Není nic,|co proti nìmu mùeme postavit!
{25745}{25784}Pokud nemohu pouít tohle...
{25876}{25930}Mùe bıt zbyteèné,|ale proè to nezkusit!
{25944}{26012}"Temnota pøed úsvitem,|karmín èervenìjší ne krev!"
{26013}{26054}To nebude fungovat, Lino Inverse!
{26075}{26122}Lino! Vyjdi, Svìtlo!
{26286}{26313}Ale ne!
{26393}{26435}Nechte mne øíct jen:
{26436}{26528}K otevøení brány staèí dvì zbranì!
{26539}{26563}Udìlá co øíká?
{26574}{26679}Kdy mám tohle, tak se mi na|soustøedìní všech pìti zbraní...
{26680}{26718}...u nechce èekat.
{26728}{26837}Teï si poèkáte a uvidíte jak|Darkstar pohltí vše na tomto svìtì!
{27020}{27202}Musíme ho zastavit za kadou cenu!|Musíte za ním!
{27217}{27259}Co máme udìlat?
{27261}{27301}Vím kam šel!
{27302}{27394}Musíte ho zabít ještì ne|se mu brána vymkne z rukou!
{27395}{27441}Pøed tím ne se mu?
{27442}{27495}Gorun Nova a Ragud Mezegis...
{27496}{27600}Pouije tyto dvì zbranì jako klíèe k bránì.
{27601}{27659}Ale nedokáe ji ovládat!
{27680}{27786}Darkstarova energie, kterou uvolní,|se mu brzo zaène vymykat z rukou.
{27806}{27851}Pokud máme rozbít Darkstarovu moc...
{27852}{27935}...musíme poèkat a shromádíme|další tøi zbranì!
{27936}{27967}Všichni, pohyb!
{27968}{27988}Jasnì!
{27989}{28013}Pane Zelgadisi!
{28037}{28069}Jdeš taky!
{28070}{28101}Tušil jsem to!
{28687}{28717}Co je to za sílu?
{28718}{28757}Magické zaøízení z Nadsvìtí?
{28776}{28803}Nadsvìtí?
{28827}{28913}Pøipojili jste se?|Bozi, Monstra a Lidé...
{28914}{28972}Opona padá v té|nechtìné souvislosti.
{28973}{29030}Audience bez svìdkù by nebyla zábava, e?
{29042}{29089}Valgaave!
{30191}{30234}Kde jsme?
{30346}{30426}Jen otevøení tìhle dveøí dìlí svìt od zkázy!
{30436}{30506}Take, vy všichni... zemøete!
{32446}{32480}Ouha, poèkej, Valgaave!
{32481}{32552}To nemyslíš vánì,|povolat Darkstara, co?
{32553}{32583}Co? Jo?
{32594}{32661}Pøíštì: "Pıcha a pád!|Lamentace bez konce!"
{32662}{32728}Radìji se dívejte, jinak vám utrhnu uši!
