{1}{1}23.976
{2456}{2528}V bitce pøi povolání|Darkstara Valgaavem byla...
{2529}{2582}...naše tlupa rozprášena|na všechny strany.
{2610}{2675}Podivnım øízením osudu|jsem se znovu sekala...
{2676}{2712}...se Zelgadisem a Filií...
{2731}{2834}...ale poøád schází Gourry, Amélie a Xellos.
{2836}{2917}No, o Xellose se nebojím, podle svého hnusnıho|zvyku se ukáe, kdy ho neèekáte...
{2918}{2990}...ale k èertu v kterém pekle|jsou Gourry a Amélie?
{3002}{3097}Hej! Gourry! Amélie!|Kde se to bincáte?!
{3098}{3278}Bezprostøední následky?|Láska s drobnou odlišností!
{4137}{4196}Opravdu jsou tvé vìštby pøesné?
{4209}{4292}Prosím, nechte to na mì.|Bezdìèná kresba...
{4293}{4360}...Ohnivého Draèího Krále je vìštba...
{4361}{4411}...u rodu drakù bìná.
{4412}{4516}No, je to jistì v poøádku,|ale kde jsou Gourry a Amélie?
{4518}{4620}No, jak je znám, tak jsem|si pìknì jistá, e jsou v poøádku.
{4621}{4733}A jak je znám já, tak jsem si jistı,|e zase zakopli o nìjaké problémy.
{4734}{4754}No to beru.
{4755}{4790}Tak, co jsi zjistila?
{4791}{4839}Není to úplnì jasné, ale...
{4866}{4910}Je... je to ryba?
{4911}{5034}Ohnivı Draèí Král by se potøeboval|v kreslení trošku zlepšit, nemyslíš?
{5690}{5718}Já... jsem...
{5719}{5793}Ach, díky bohu!|Koneènì jste procitla.
{5808}{5864}Uhm... hmm...
{5932}{5966}Teï u bude všechno v poøádku.
{6164}{6234}Ry... rybááááá!
{6300}{6379}Co jste zaè?
{6393}{6465}Nebojte se.|Nechceme vám ublíit.
{6466}{6537}Našli jsme vás na|plái v bezvìdomí.
{6629}{6662}Vzpomínám...
{6883}{6965}Všechny nás|to odmrštilo pryè.
{7141}{7238}Promiòte. Mìla|jste vysoké horeèky.
{7239}{7285}Vysvlékli jsme vás z šatù.
{7294}{7352}Ach, tohle se stalo?
{7367}{7453}A kde jsou ostatní?|Sleèna Lina, pan Zelgadis, a...
{7501}{7565}Na plái jsme našli jen vás.
{7579}{7609}No tedy...
{7712}{7744}Boe, to mám hlad...
{7745}{7822}Všichni mì opustili...|Kam zmizeli?
{7833}{7887}Proè se to muselo stát?
{7902}{7970}Proè? Proè já?
{8019}{8089}Tak... jmenujete se Amélie.
{8101}{8175}Mé jméno je Laila,|a zde je mùj otec, Honar.
{8189}{8243}Jsem rád, e jste|koneènì vzhùru.
{8254}{8277}Dìkuji.
{8278}{8351}Spala jste celı tıden,|sleèno Amélie.
{8352}{8407}U jsme o vás mìli strach.
{8408}{8500}Promiòte! Chovám se tak nevychovanì|pøed lidmi, kterım dluím svùj ivot.
{8512}{8562}Ale, ne.|Tohle vás trápit nemusí.
{8563}{8640}Ale jak se to stalo, e jste se objevila|v bezvìdomí na takovém místì?
{8655}{8746}Pravda! Pravdou je, e já|a mí pøátelé jsme se pokoušeli...
{8747}{8784}...zachránit svìt pøed nebezpeèím!
{8820}{8860}Ach, to je strašné.
{8875}{8927}Vy si opravdu na víc nevzpomínáte?
{8928}{8948}A tak...?
{8949}{8998}Ano... vzpomínám si jen na to, kdy...
{8999}{9056}...jsme bojovali s temnım|pánem z Nadsvìtí.
{9066}{9100}Porazil vás?
{9128}{9220}No, abych tak...|Odhodilo nás to pryè, take...
{9237}{9324}Ale... ale svìt|ještì není znièen...
{9325}{9379}...èili Darkstar nebyl povolán.
{9389}{9475}Sleèno Amélie,|nedìlejte si teï takové starosti.
{9476}{9551}Musíte odpoèívat|a obnovovat svou sílu.
{9552}{9644}Máte pravdu. Ale ještì...
{9898}{10015}Sleèna Lina... Pan Zelgadis...|Pan Gourry... Sleèna Filia... Pan Xellos...
{10025}{10098}Chtìla bych vìdìt,|co se s nimi stalo.
{10100}{10172}Snad nejsem jediná,|kdo to pøeila.
{10189}{10243}Auch!|Tak tomuhle nevìøím!
{10244}{10315}Pokud je v poøádku|nejslabší èlen tımu, pak...
{10328}{10422}Oni mì všichni|musí hledat!
{10803}{10852}Sleèna Laila?
{11008}{11034}Kerele!
{11227}{11246}Lailo!
{11259}{11287}Kerele...
{11288}{11314}Lailo!
{11337}{11362}Kerele!
{11384}{11449}Myslel jsem, e dnes|v noci nepøijdeš!
{11450}{11548}Promiò. Nemohla jsem pøijít,|dokud táta neusnul.
{11587}{11693}Tohle vypadá na|pøítele sleèny Laily!
{11706}{11805}Och, Kerele, tohle je|pro nás tak tìké.
{11817}{11931}Jednoho dne tvùj otec|pochopí. Pak...
{11943}{11970}Opravdu?
{11985}{12075}Ano. Do toho dne musíme vydret.
{12077}{12166}Tak èlovìk a ryba? No teda...
{12167}{12217}Co vy dva tady dìláte?!
{12275}{12304}Otèe!
{12305}{12378}Neøíkal jsem ti, aby ses|od nìj drela dál?
{12379}{12445}Pane Honare, prosím,|vyslechnìte mne!
{12457}{12515}Nemáš mi co øíct!
{12576}{12599}Nech mì jít!
{12600}{12629}Lailo!
{12630}{12669}Pùjdu sama!
{12686}{12717}Lailo!
{12880}{12909}Lailo...
{12979}{13009}Poèkejte, prosím!
{13011}{13039}Sleèno Amélie.
{13040}{13117}I kdy jste zachránil mùj ivot,|pøesto musím øíci, e rozdìlování...
{13118}{13168}...dvou zamilovanıch je neomluvitelné.
{13169}{13248}Takovou špatnost,|já Amélie Will Tesla Seyruun...
{13250}{13328}...bojovnice lásky a spravedlnosti,|nemùu strpìt!
{13434}{13521}To je náš problém.|Neplete se do toho.
{13522}{13633}Ne! Teï, kdy jsem to vidìla,|nemohu to ignorovat!
{13642}{13663}Coe?
{13670}{13754}Pane Honare! Proè|nenecháte tyhle dva spolu?
{13768}{13849}Vdy lidé a my|nemùeme spolu ít.
{13861}{13914}Je jasné, e jejich|ivot by nebyl šastnı.
{13915}{13952}To není pravda.
{13953}{13978}Jasnì!
{13979}{14027}Láska pøekoná rozdíly!
{14028}{14074}To je nìco, co musí|bıt oslavováno!
{14075}{14120}Je jasné, e jeden|druhého milují!
{14121}{14164}Jak by mohli bıt nešastní?
{14175}{14253}Kdy øíkám, e tohle|nepøipustím, tak NE!
{14598}{14634}To je kruté!
{14667}{14770}Hej vy! Teï není èas, stát|tu se zlomenım srdcem!
{14771}{14801}Chop se toho!
{14813}{14914}Však pøesvìdèíme pana Honara,|aby souhlasil s vaší láskou!
{15462}{15544}Pane Honare, proè jim|nedovolíte ít spolu?!
{15545}{15619}A nechci slyšet nic o tom,|e jsou kadı jiného druhu!
{15679}{15741}Zaèalo to pøed tøemi mìsíci.
{15743}{15804}Má loï byla zachycena v bouøi.
{15836}{15954}Laila mì zachránila, po tom co jsem|spadl do moøe a ztratil vìdomí.
{16473}{16527}Øekla, e se pro mne zranila...
{16543}{16609}To všechno je pravda, Kerele.|Ale nedìlej si s tím starosti.
{16620}{16649}Lailo...
{16651}{16679}Kerele...
{16709}{16802}No tak, prosím, pøipuste,|e se ti dva zamilovali.
{16812}{16874}Nakonec, ádná láska|nevydrí vìènì.
{16875}{16909}To tedy ne!
{16930}{16993}Láska vybledne i mezi|pøíslušníky stejného druhu.
{17013}{17106}Mezi takhle odlišnımi,|vybledne ještì døív.
{17107}{17175}Naše láska není tak mìlká!
{17176}{17290}Jednou, kdysi dávno, tady|ili dva, kteøí se milovali jako vy.
{17336}{17448}Ale my, rybí lidé musíme strávit|polovinu z kadého dne ve vodì.
{17484}{17553}Nìjakou dobu to|všechno bylo v poøádku.
{17575}{17677}Ale jak roky míjeli,|u spolu nedokázali zùstat.
{17718}{17804}Nevadila vlhkost, ale|chu jídla z moøskıch øas.
{17823}{17889}Kdy byli spolu, nemohli|se od moøe vzdálit.
{17900}{17956}Jak mohli pøekonat rùst odcizení?
{17970}{18012}Øíkáte, e vy...
{18013}{18128}To je starı pøíbìh.|Velmi velmi starı a docela obyèejnı.
{18129}{18212}A já nechci,|aby Laila takhle trpìla.
{18213}{18246}Otèe...
{18247}{18318}Ale tohle se jí|se mnou nestane!
{18332}{18437}Ani vlhká místnost, èi jídlo|z moøskıch øas nejsou dùleité!
{18438}{18497}Nikdy, nikdy bych|Lailu neopustil!
{18498}{18556}Ani kdy tvé lùko bude poøád slizké?
{18557}{18607}Nebo jídlo bude ze slimákù a íal?
{18619}{18661}To je opravdu hrubé.
{18698}{18767}Proè jsem se musela narodit|tak odlišná?
{18780}{18878}Kdybych... kdybych byla èlovìkem,|tak bych takhle nemohla trpìt!
{18879}{18926}To není tvá chyba, Lailo.
{19042}{19103}Snad bychom si teï mìli øíci sbohem...
{19104}{19163}...dokud jsou ještì|naše vzpomínky dobré.
{19179}{19208}Lailo...
{19449}{19493}Je konec, Kerele.
{19494}{19524}Lailo.
{19525}{19634}Poèkejte, prosím! Opravdu|vy dva s tímhle chcete ít?
{19635}{19660}Ale...
{19661}{19725}Nemùete se jen tak vzdát!
{19726}{19788}Vaše láska musí vydret do konce!
{19789}{19823}Sleèno Amélie...
{19833}{19910}Nevzdávejte se, dokud|jste nevyzkoušeli všechno!
{19911}{19977}Kdy vydáte všechno,|dokáete pøekonat jak...
{19978}{20043}...slizkou postel tak|jídlo ze slané vody!
{20055}{20104}Vydáme všechno, Lailo!
{20105}{20142}Kerele...
{20171}{20292}No potom je tu jedna vìc,|kterou mùete zkusit.
{20463}{20508}Našla jsem to! Tady to je!
{20524}{20579}To je pradávnı recept|na promìnu...
{20580}{20618}...zapsanı naším rodem?
{20619}{20636}Ano.
{20637}{20724}S tímhle budeme schopni|zmìnit sleènu Lailu na èlovìka.
{20736}{20833}Existuje tajnı poklad|promìny mezi našimi druhy.
{20846}{20891}Ten kdo získá kámen...
{20904}{20974}...bude schopen svobodnì|zmìnit svou tìlesnou formu.
{20975}{21013}S tímhle...
{21014}{21047}Kerele!
{21048}{21079}Lailo!
{21169}{21227}Dobøe! Teï potøebujeme|získat ten poklad!
{21238}{21324}Ale tady se píše, e potøebujeme|pøekrásnou princeznu...
{21325}{21378}...na kterou vylákáme|stráce pokladu.
{21395}{21437}Pøekrásnou princeznu...
{21541}{21631}Kdy je to tak, sleèno Lailo,|nebude to nic dobrého, co?
{21632}{21670}Musíme to dostat.
{21671}{21763}Sleèna Amélie u udìlala dost.|Teï jsem na øadì já.
{21827}{21865}Pane Gourry!
{21912}{21998}Co se mu stalo?|Proè vypadá takhle?
{22014}{22081}Zhroutil se pøed námi.|Tak jsme ho sebrali.
{22095}{22116}Pane Gourry!
{22117}{22172}Jsem... hladovı...
{22258}{22304}Musel umírat hlady.
{22306}{22351}Ne, vdycky jí takhle.
{22388}{22448}Ale tohle øeší náš|problém, nemyslíš?
{22525}{22587}Proè mi tohle dìláte?
{22602}{22682}Potøebujeme pøekrásnou|enu pro pøilákání stráce...
{22683}{22739}...støeícího poklad rybích lidí!
{22740}{22789}Tak proè vyuíváte mì?
{22790}{22856}Co máte za problém?|Vdy jsem øíkala "pøekrásná ena" ne?
{22857}{22919}Mimochodem, nedali vám|najíst a neubytovali vás, co?
{22920}{22984}Tak se koukejte tamhle|dvou odvdìèit!
{22997}{23036}Poèkat! Hej!
{23037}{23084}Bude to v poøádku?
{23085}{23140}Pan Gourry je velkı a silnı...
{23141}{23223}...take bude v poøádku i kdyby|se do nìj stráce zakousnul.
{23224}{23260}Zakousl?
{23272}{23400}Augh! Hele! Hele, Amélie!|Udìlej nìco, prosím!
{23647}{23728}Co? Co je to?|Proè je tak ticho?
{23743}{23780}Podívej, brzo...
{24035}{24068}Hej, co je to?
{24159}{24201}Poèkej! O tom jsme nemluvili!
{24202}{24226}Tamhle!
{24243}{24288}Tohle je poklad promìny?
{24309}{24367}Pokud spolknu vıluh z toho kamene,|stanu se èlovìkem!
{24423}{24518}Proè musí bıt ty|pitomı øetìzy tak silnı?!
{24579}{24635}K èertu s tím!
{24749}{24825}Ty podìlánku!|Chtìl sis kousnout co?
{24955}{25008}To je naše šance, pan Gourry|odvrátil jeho pozornost!
{25095}{25137}Ne tak rychle!
{25138}{25212}Pane Gourry, nechte|se trochu kousnout!
{25213}{25260}Prosím, a se|na chvíli zastaví!
{25261}{25301}Jsem snad v pekle?
{25310}{25377}Takhle nemùu pøesnì vystøelit!
{25449}{25495}Trošku se to ztíilo!
{25668}{25703}Hotovo!
{25715}{25763}Pane Gourry! No dobøe!
{25770}{25799}Digger Bolt!
{25831}{25864}NE, ty hlupaèko!
{25992}{26033}-Teï!|-Ano!
{26095}{26156}Tady je to. A... nahoru!
{26186}{26204}Máme to!
{26217}{26285}To je ono...|Poklad co jsme chtìli.
{26295}{26325}Dokázali jsme to.
{26340}{26387}Vítìzství!
{26388}{26434}Jen chvilku...
{26502}{26557}Ach, jsem v pekle.
{26700}{26755}Sleèno Amélie! Pane Gourry!
{26757}{26811}Postaráte se o to, ano?
{26847}{26890}Hele, to není fér!
{27129}{27170}Lailo, jsi si jistá?
{27181}{27199}Ano.
{27217}{27281}Teï se sleèna Laila|zmìní na èlovìka.
{27282}{27324}Jakı druh èlovìka pøesnì?
{27448}{27467}Lailo?
{27561}{27587}Co se dìje?
{27588}{27613}Proè já...
{27632}{27669}Jak jsem se obával...
{27692}{27791}Pøesnì podle naší legendy.|Lektvar zaène pùsobit jedinì...
{27792}{27943}...po polibku èlovìka a ryby,|kteøí se navzájem doopravdy milují.
{27966}{28045}Pokud je jejich láska opravdová,|èlovìk stane rybou...
{28046}{28088}...a ryba èlovìkem...
{28089}{28128}...vymìní si své tvary.
{28129}{28226}Znamená to, e se Laila stane|èlovìkem a Kerel rybou?
{28227}{28290}To ten problém|vùbec nevyøeší!
{28340}{28375}Na mì nezáleí.
{28389}{28462}Pokud se stanu rybou, budu|moci ít na tomto ostrovì.
{28463}{28506}Co víc bych si mohl pøát?
{28548}{28594}Všechno co chci, je vìdìt,|jak se Laila cítí.
{28604}{28690}Já... nebojím se|stát èlovìkem.
{28704}{28724}Lailo!
{29459}{29484}Kerele...
{29485}{29509}Lailo!
{29538}{29584}Vypadáš tak úasnì!
{29599}{29626}Ty také.
{29712}{29774}Dokázali svou lásku.
{29775}{29823}Kdy se ohlédnu tak si...
{29824}{29898}...vzpomínám, e jsem ztratil|odvahu stát se èlovìkem.
{29899}{29969}A tolik jsem ztratil,|protoe...
{30001}{30099}Pane Honare, sleèna|Laila je teï šastná.
{30119}{30155}Dost pro dva, tak.
{30386}{30440}Uhm... Byl tohle opravdu|tak dobrı nápad?
{30442}{30495}Pokud jsou oba šastní,|tak je to v poøádku!
{32327}{32379}Co? Staneš se Bojovníkem|Spravedlnosti...
{32380}{32410}...a lovcem démonù?
{32411}{32493}Gourry a Amélie se opravdu pøíštì|zamíchají do pìkné ztøeštìnosti!
{32494}{32538}Pøíštì: "Správná osoba na správném místì!"
{32539}{32570}"Amélie v obèinì Spravedlivosti!"
{32571}{32626}Pokud se nebudete dívat,|zajeèím vám do uší!
