{1}{1}29.970
{403}{474}Kde øádí monstra, pøicházím,|abych je znièila!
{478}{574}Kde se blyští poklady,|tam jsem a pøivlastním si je!
{577}{710}A kde se mi nepøátelé postaví,|tam bude vıhra vdy má!
{801}{909}A je vítr ve tváøi...
{910}{983}...jakkoli silnı...
{991}{1098}...staèí jedno kouzlo...
{1100}{1181}...a hned zrychlím krok!
{1182}{1289}A mi sílu závidí...
{1291}{1370}...a na krásu árlí...
{1371}{1480}pøed soupeøi neváhám...
{1481}{1570}...pláš mi vane ve vìtru.
{1571}{1669}Chci dìlat to i ono.
{1670}{1750}Bıt dívkou.
{1751}{1849}Chybné kroky však peklo znaèí.
{1853}{1962}Proto mi nezkøi cestu!
{1992}{2102}Tak daleko jak jen chci...
{2104}{2202}...budu v cestì pokraèovat.
{2212}{2279}Ve smutnıch dnech...
{2280}{2361}...úsmìv nasadím.
{2371}{2479}Daleko v objetí magie...
{2480}{2587}...za hranicí tohoto dne.
{2590}{2659}Vejít do snu...
{2662}{2799}...a pokraèovat.
{2801}{2896}Bez hranic...
{2897}{3051}Nevzdávej se, zkoušej to znova.
{3836}{3896}Vıbornì, vy opice!|Dobrá práce!
{3944}{4041}Tady je nìco z naší koøisti,|kterou jsme získali!
{4195}{4285}Dni jako tenhle mì naplòují radostí,|e jsem se stal banditou!
{4705}{4755}Co se k èertu dìje?!
{4775}{4824}Šéfe! Tam!
{5103}{5168}Ty... ty... TY!!!
{5184}{5313}Ta prokletá, dìtská,| zabíjeèka banditù...
{5317}{5371}LINA INVERSE!
{5372}{5424}To jsem já!
{5704}{5862}A tak se Lina Inverse,|génius magie...
{5864}{5953}...dala na cestu bojovníka, aby se postavila|tyranii a bandám lupièù.
{5955}{6012}Tato nora podlosti|je znièená.
{6015}{6102}Ale dokud v tomto svìte|bude existovat zlo...
{6105}{6185}...boj Liny Inverse|se nikdy neskonèí.
{6254}{6334}Jen bojuj, Lino!|Nikdy se nevzdávej, Lino!
{6363}{6454}To..to je náš poklad...!
{6458}{6640}ROZLOBENÁ?|Linin rozzuøenı Dragon Slave
{6870}{6926}Nìkdo mì sleduje.
{6941}{7035}Jen jsem si trošku|odebrala z jejich pokladu...
{7039}{7153}...a teï mì u k èertu|nikdy nenechají na pokoji!
{7165}{7244}Vypadá to, e mì obklíèili.
{7304}{7358}Proè u prostì nevylezete?
{7377}{7462}Tak jsme tì koneènì našli, dìvèátko!
{7477}{7557}Myslíš si, e z nás|mùeš dìlat blbce?!
{7558}{7613}Co, ty malá èarodìjnice?!
{7616}{7682}Ach boe, to je|tedy primitiv.
{7686}{7730}Tak se podívej, kámoši...
{7742}{7835}Pøišel jsem si pro pomstu|za to co jsi udìlala!
{7862}{7975}Teda aspoò jsem chtìl... ale já,|vánì s tebou nechci bojovat.
{7996}{8053}Ach, fajn.|Tak v tom pøípadì, mìjte se.
{8056}{8113}Úha! Poèkej chvíli!
{8116}{8234}Všechno je to jen pro to, e v øádném|souboji nemám proti tobì šanci.
{8254}{8293}Take, pøíteli...
{8305}{8372}Take ty nejsi úplnı idiot, e?
{8375}{8442}Ty máš tedy koule, èlovìèe.
{8445}{8554}Ach, samozøejmì, kdy jsi dívka,|nemáš ádné koule!
{8594}{8641}Ten chlap nemá úroveò.
{8644}{8724}Ale od banditù ji|nemùete oèekávat, ne?
{8785}{8864}Byla jsi skuteènı profík!
{8867}{8953}Jen si tak pøiletíš|a vyhodíš nás všechny do luftu!
{8955}{9032}A pak pøedvést na našem veliteli|to èíslo se ivou pochodní.
{9036}{9151}Ukrást všechnu koøist|ne jsme se vùbec stihli vzpamatovat.
{9154}{9252}K èertu, ani my by jsme|nezašli tak daleko!
{9256}{9305}ádná práva pro zloèince.
{9320}{9360}Coe?!
{9384}{9499}Podívej, pùvodní dùvod proè|jsme tì sem sledovali byl...
{9503}{9615}...zabít tì a pomstít tak našeho velitele!
{9624}{9688}Co tím chceš øíct?
{9704}{9806}Ale no tak, Co kdyby si se|k nám, Draèím Tesákùm, pøidala?
{9824}{9864}Draèím Tesákùm?
{9884}{9990}ertuješ?!|S kriminálníky se nespolèuji!
{9992}{10102}Jen nám prostì dej tu koøist|a pøidej se k nám,...
{10105}{10182}...no a my zapomeneme na celı incident.|Všechno bude zase pøi starém.
{10185}{10251}No tak,|není to a tak zlá nabídka.
{10274}{10360}Jsem sice zlá, ale a tak ne,|abych se pøidala k hrstce lupièù.
{10363}{10454}Miluji dívky, které ví|co chtìjí.
{10470}{10540}Co si ten chlap|myslí, e je?
{10544}{10633}SKUTEÈNÍ mui jsou princeznièky,|které pøicválají na bílém koni.
{10653}{10683}Odpovìï je NE!
{10695}{10778}Ty jedna malá kurvo! Já ti|nabízím dohodu a ty...!
{10782}{10834}Pøiprav se na smrt!
{10844}{10884}Tak TO jsou nevkusné vırazy!
{10924}{10971}Pojïte sem, chlapi!
{11263}{11353}To je všechno?|Moc vás teda není, pravda?
{11376}{11451}Co? To ještì nejsme všichni!
{11456}{11521}Poslouchej, v lesích mám chlapy,|kteøí na mé slovo...
{11525}{11621}...vyletí a udìlají|z tebe mleté maso!
{11625}{11725}Omluv se|a moná tì necháme naivu!
{11771}{11851}Ty jedna... nauèíme tì|nezahrávat si s Draèími Tesáky!
{11994}{12042}Tak moment!
{12194}{12301}Nìco takového tedy nezkusíš!|Ty banditská špíno...
{12303}{12372}Proè se radši neotoèíš|a neutíkáš, dokud máš èas?
{12394}{12452}Udìlej to a moná vás všechny|nechám naivu.
{12455}{12577}Sklapni! Tohle se tì netıká!|Kdo jsi, k èertu?!
{12595}{12664}Nebudu se pøedstavovat|primitivùm tvého druhu!
{12685}{12739}CO-O-O?!!!
{12754}{12864}Super, tak je z toho|souboj ukecanıch muù.
{12874}{12942}Ty zkurv...! OK,|nejdøív zaèneme s tebou!
{12944}{12983}Na nìj chlapi!
{13331}{13380}Pomùu mu--
{13383}{13537}Ne, poèkat. Hrdinka v tomhle pøípadì|má bıt vystrašená a ujeèená.
{13540}{13608}Musím zahrát svou roli!
{13610}{13732}ÍÍÍÍÍ! Zachraòte mì!|Pomozte, prosím!
{13965}{14000}Slitování!
{14502}{14543}Ani není moc otrhanı.
{14613}{14662}Jsi v poøádku?
{14924}{14980}Oslnìnı mojí nádherou,|bezpochyby.
{14984}{15020}To mì nepøekvapuje.
{15024}{15080}Pokud je nìco, v èem si skuteènì|fandím, pak je to mùj vzhled.
{15084}{15160}Velké kulaté oèi,|má pìkná tváøièka.
{15164}{15284}A také tohle køehké|extra štíhlé tìlo.
{15410}{15465}Vzdychá obdivem...
{15467}{15531}No super... Je to ještì dìcko...
{15581}{15710}S to veškerou nádherou,|myslel jsem, e to bude nìjaká koèka.
{15713}{15791}A místo toho je to nìjaké okaté,|pøíènì-ploché malé dìcko.
{15844}{15979}No, jsem trochu|malá na svùj vìk...
{15982}{16061}A také trochu|slabì vyvinutá.
{16064}{16151}Sakra, vdycky si najdou vìci,|na které je èlovìk citlivı!
{16154}{16252}A myslel jsem, e bude|mít i pìknou postavu.
{16257}{16410}V takovıch pøípadech bych si pøála,|aby mùj sluch nebyl a tak citlivı.
{16414}{16507}To si myslí, e ho|neslyším brblat?!
{16534}{16590}Ach boe, opustilo mì štìstí.
{16594}{16758}Sakra! Nebyla jsem ani v ádném|nebezpeèí, ale mìla bych mu podìkovat.
{16762}{16866}Byla jsem pøeci vychovaná tak,|abych byla slušná.
{16896}{16983}Éch, dìkuji za záchranu.
{16993}{17082}Och, není tøeba dìkovat.
{17139}{17206}V kadém pøípadì,|nejsi zranìné, dìvèátko?
{17214}{17264}Dìvèátko...?
{17275}{17350}Je nebezpeèné aby se dìvèata potulovali samotné.
{17354}{17440}Byla jsi se svım|otcem nebo s nìkım?
{17444}{17470}Ach boe!
{17474}{17529}Ne, byla jsem sama.
{17544}{17671}To je velmi nebezpeèné. Mùu|tì doprovodit domù?
{17673}{17741}- Kterım smìrem je tvùj domov?|- Promiòte, haló...
{17743}{17810}- Tudy?|- Poèkej!
{17812}{17900}Um, ech, cestuji sama.
{17902}{18050}Mám to namíøené do Atlas City.|Chceš mì doprovodit?
{18053}{18090}To nemùe serat.
{18103}{18185}Rozumím, rozumím!
{18203}{18267}Ach, ty ubohá.
{18324}{18389}Chápu.|Dokonale rozumím!
{18392}{18448}Tolik tìkostí,|které podstupuješ...
{18451}{18490}Ech, já uch...
{18493}{18580}Ne. Není nutné nic|øíkat. Chápu.
{18583}{18607}Tak se podívej!
{18623}{18742}Chci jen trochu cestovat|a rozhlídnout se tady, OK?!
{18764}{18859}OK, doprovodím tì|do Atlas City.
{18861}{18889}Ejha, ej, ej!
{18903}{18999}Ano, dokonale rozumím.|Potøebuješ pøítele.
{19002}{19052}Ach, tomu to pomalu zapaluje!
{19062}{19128}Do Atlas City je to 10 dní cesty!
{19131}{19231}A kdy u strávím s "velkım bratøíèkem"|tolik èasu...
{19233}{19336}...udìlají se mi aludeèní vøedy|s toho veškerého stresu!
{19352}{19436}No, take kdy jsme si to u všechno|vyjasnili, mùeme vyrazit!
{19444}{19529}Vùbec to není je jasné,|je to úplná ÚCHYLKA.
{19531}{19640}Dovol, abych se ti pøedstavil.|Mé jméno je Gourry...
{19644}{19715}...a jak u si mìla monost vidìt, jsem|potulnı bojovník. oldák.
{19733}{19769}Tak se podívej...
{19773}{19902}Ach, kušuj. Vypadá celkem|slušnì a poctivì.
{19910}{20002}A zdá se, e má o mne skuteènı strach.
{20101}{20200}Nedáš si nìco na zub v nejbliší vesnici?|Urèitì budou mít i nìco pro dìti...
{20216}{20318}No, vypadá to, e se s tím budu muset vyrovnat.
{20383}{20493}Och, zapomnìl jsem se zeptat.|Jak se jmenuješ, dìvèátko?
{20552}{20600}Lina.
{20622}{20711}Jmenuji se Lina Inverse!
{21109}{21157}Tak, co bych si dala?
{21167}{21260}Zvu tì.|Objednej si, co chceš.
{21264}{21318}Vánì? OK...
{21324}{21404}Dám si všechno|odshora dolù.
{21408}{21433}Všechno?!
{21436}{21514}A pøidám si ještì tohle,|tohle, tohle, a tohle.
{21518}{21553}Trojité porce.
{21556}{21591}TROJITÉ PORCE?!
{21857}{21946}Nech to! Dej mi!
{23032}{23104}Ach, jsem plná...
{23108}{23193}Ještì zùstalo trochu polévky.| Poslu si.
{23197}{23243}Oh, ani náhodou.
{23246}{23315}Mùj aludek se asi|roztrhne. Vidíš?
{23337}{23422}Hej. U je v pùli cesty|k tvım prsùm.
{23426}{23474}- Coe?|- Ale nic.
{23477}{23551}Promiòte, dobøí lidé.
{23648}{23796}Jmenuji se Savan,|a zastupuji starostu této vesnice.
{23798}{23991}Nejste vy náhodou Lina Inverse,|ta proslavená èarodìjka?
{24006}{24045}Uch, no ano, jsem...
{24047}{24139}ÈOE?!|Ty jsi èarodìjka?!
{24156}{24320}Neumíš ani odhadnout povolání?|Nevypadám snad v tomhle obleèení dost nápadnì?!
{24376}{24458}Myslel jsem, e jsi prodavaèka ryb,|servírka, anebo tak.
{24497}{24613}Jaká servírka by nosila tohle?!|Jsi slepı nebo jen hloupı?!
{24617}{24652}Promiòte.
{24664}{24741}Mùu pokraèovat?
{24757}{24845}Nutnì potøebujeme tu|známou Zabíjeèku Banditù...
{24847}{24985}...Odstrašovaèku Drakù,|Linu Inverse.
{25013}{25061}Jsi nìjak známá, ne?
{25065}{25153}Poèkat, Zabíjeèka Banditù|tomu rozumím...
{25155}{25214}...ale proè Odstrašovaèka Drakù?
{25224}{25285}Je to zkratka pro "Draci kolem ní pøejdou|a utíkají z jejího dosahu".
{25289}{25384}- COE?!|- Vím jak se cítíš, ale nedìlej to!
{25392}{25506}Já jsem si to nevymyslel! Slyšel|jsem to od jinıch lidí, pøísahám!
{25518}{25575}OK, tak|co ode mne chceš?
{25578}{25739}No, vesnice byla nedávno|pøepadnutá bandity.
{25749}{25858}Myslíš ty Draèí Tesáky?
{25864}{25925}Oh, ty o nich víš?
{25929}{25995}No v to pøípadì jsem se o nich|u postarala.
{25998}{26025}Jsi se o nì co?!
{26030}{26167}Vìtšinu z nich jsem vyøídila vèera|a tenhle chlapík se postaral o zbytek.
{26247}{26325}Myslíš ty chlapy,|kteøí tì pøepadli?
{26368}{26477}Podaøilo se vám zabít|Èerného draka!
{26529}{26625}Banditi si ho vychovávali|jako domácí zvíøe...
{26629}{26694}...a vojáci z naší vsi|s ním nemohli bojovat.
{26699}{26774}Museli jsme dìlat všechno,|co si poruèili.
{26778}{26877}Teda...! Jsi|skuteènì vynikající, Lina Inverse!
{26924}{26987}Hned všem oznámím dobré zprávy!
{27068}{27140}Ty jsi zabila draka?
{27168}{27215}Nevìdìla jsem, e tam nìjakého mají.
{27218}{27334}Take ten drak...|je na svobodì a jen tak si poletuje?!
{27336}{27356}Asi ano.
{27376}{27420}Co udìláme?!
{27424}{27494}Nevím.|Náš problém to není.
{27497}{27599}Chceš èíhat na draka,|ktorı je u teï bùhvíkde?!
{27623}{27682}Èernı drak!!!
{27966}{28025}Ty!
{28027}{28151}Ty jsi nezabila toho draka?!|Co to má znamenat?!
{28154}{28251}Nikdy jsem neøíkala, e jsem ho zabila.
{28268}{28354}Øíkala jsem, e jsem se|postarala o Draèí Tesáky.
{28373}{28504}Tak to se mi nechce vìøit!|Jak si ho nemohla nezabít?!
{28507}{28555}Nevìdìla jsem, e tam je.
{28558}{28601}Ó boe...
{28908}{28956}Kolik jste|ochotní zaplatit?
{28985}{29087}Kolik jste ochotní zaplatit,|kdy vám zabiji toho draka?
{29110}{29162}Dvacet zlatıch.
{29182}{29241}- Tøicet.|- To je moc drahé!
{29243}{29331}Chcete, aby jsem ho zabila,|ne úplnì znièí vaši vesnici?
{29333}{29401}- Dvacet pìt.|- V poøádku.
{29403}{29430}Hej, zadr!
{29446}{29500}Tíseò pomáhá|dobrému obchodu.
{29517}{29565}To dìvèe je tedy rafinované!
{30008}{30061}Je obrovskı!
{30137}{30232}Kde proboha tlupa banditù|sehnala takovou vìcièku?!
{30245}{30334}Vùdce Draèích Tesákù ho koupil,|kdy byl ještì malièkı...
{30337}{30454}...v jednom stánku na festivalu.|Za tøi støíbròáky.
{30461}{30511}To tedy musel bıt festival!
{30515}{30629}Byl docela malièkı, ale vidím,|e u pìknì vyrostl.
{30654}{30784}Musel ho milovat jako syna,|kdy ho dochoval k takové velikosti.
{30797}{30893}Drak, kterı dokáe ocenit|lidskou náklonnost...
{30896}{30953}Nemáme momentálnì èas obdivovat!
{31176}{31263}Je to tu nebezpeèné!|Radši se jdìte schovat...
{31266}{31291}Pozdì.
{31377}{31433}Tak do toho Gourry!
{31528}{31576}Fire...
{31646}{31687}...BALL!
{32214}{32301}Ani ho to neškráblo?|No tedy...
{32785}{32843}Hej! Slez ze mne!|Jsi moc tìkı!
{32946}{33003}U pøichází!|Slez ze mne!
{33386}{33452}Ty si tedy opravdu|Odstrašovaèka Drakù.
{33456}{33485}Ty, ty...!
{33501}{33563}Jak si mì dovoluješ|takhle zahanbovat!
{33566}{33615}Odpravím tì jedinım vıstøelem!
{33666}{33745}Levitation!
{33993}{34082}Odveï jeho pozornost,|a se mohu soustøedit na kouzlo!
{34087}{34132}Na nìj, Gourry!
{34495}{34614}"Temnota pøed úsvitem,|karmín krvavìjší ne tekoucí krev."
{34626}{34663}"Pochovanı v pøílivu èasu..."
{34686}{34738}Lina, tak za tohle tì dostanu!
{34746}{34862}"Ve tvém velkém jménì,|zapøísahám se silám temnot."
{34866}{34981}"Všichni blázni, kteøí se nám|postaví do cesty, budou znièení..."
{34985}{35095}"...silou, kterou|spoleènì vládneme!"
{35155}{35224}DRAGON SLAVE!
{35925}{35956}Tak, jak se ti to líbilo?
{35960}{36011}Nejsilnìjší kouzlo|z celé èerné magie!
{36016}{36103}Sila mého nièivého|DRAGON SLAVE!
{36107}{36187}Pøíštì mì na to zkus|radši upozornit!
{36215}{36273}Kouzlo, které øeší|kadı mùj problém.
{36276}{36313}Ty...
{36317}{36384}Tak to máš tedy pekelnı problém!
{36496}{36584}Pane Samane. Nezapomeòte|na peníze, které jste nám slíbil.
{36587}{36671}Èerta starıho vám zaplatím!|A co naše vesnice?!
{36923}{37002}Hej, Dragon Slave|je docela silnı, nemyslíte?
{37007}{37057}A MOC silnı!
{37071}{37187}No, vlastnì ano.|Tak, si myslím... e tohle u radši...
{37191}{37220}Nechám na tobì!
{37223}{37267}H-hej!
{37391}{37441}Nám neuteèete!
{37475}{37525}To je všechno tvoje vina,|Odstrašovaèko Drakù!
