{1}{1}23.976
{319}{367}Tam kde se vyrojí monstra,|objevím se, abych je porazila!
{383}{449}Tam, kde se zatøpytí poklady,|pøicházím, abych se jich zmocnila!
{449}{557}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2631}{2699}Tak, odhalili jsme skuteènou podobu|Reza, Rudého Knìze.
{2699}{2815}A teï mu já, Lina Inverse a Zelgadis...
{2815}{2867}...spoleènì utíkáme!
{2867}{2932}Rezovım touí získat|Kámen Mudrcù...
{2952}{2990}...kterı je ukryt|v Orihalconské sošce.
{3000}{3052}A ten Kámen tak|zesiluje magické pùsobení,...
{3052}{3128}...e mùe klidnì zmìnit|prùbìh samotné historie...
{3128}{3204}...a neustále po nás jde|víc a víc Rezovıch muù!
{3238}{3325}A kromì toho, kde|trèí Gourry?! Kde mùe bıt?!
{3335}{3401}Mùeš si to v hlavì|srovnat, Gourry?!
{3401}{3550}VZDÁM SE!|Ale døív ne se vzdám, zjeví se Meè nadìje!
{3828}{3872}Nemyslíš, e u jich|máš dost?
{3935}{3980}Chci jich ještì pár!
{3980}{4040}Vdy od vèerejška nedìláme nic jiného,|ne e bojujeme s Rezem...
{4040}{4080}...a ani jsme se ještì|poøádnì nenajedli!
{4080}{4170}Pospìš si! Musíme se dostat|do Madiranu pøed západem slunce.
{4181}{4217}No jo.
{4483}{4542}Tøi trollové, ech...?
{4542}{4625}U zase? Chtìla bych|se koneènì najíst!
{4643}{4682}Dieta by ti prospìla.
{4682}{4753}Zkus na mì najít|jedinı kousíèek sádla!
{4765}{4791}U jdou!
{4970}{5049}Lino! Kde jsi?
{5082}{5126}Lino!
{5150}{5176}Kde vìzíš?!
{5246}{5285}Lino! Jsi to ty?!
{5343}{5418}Ne, to urèitì není ona...
{5474}{5559}Ale oba mají|velmi podobnou povahu.
{5691}{5749}Ale kde je k èertu Lina?
{6043}{6122}Moná nejsem zrovna ve formì,|ale mùu to zkusit!
{6201}{6242}Fire...
{6295}{6326}...Ball!
{6574}{6633}No, zdá se, e u se mi|vrací pùvodní síla.
{6633}{6692}Jak vidím, tvé magické|schopnosti jsou zpátky.
{6704}{6773}Tak vidíš, jsem teï na tom|o hodnì líp.
{6774}{6843}Kadopádnì, pojïme si|sníst naše rybièky.
{6912}{6938}Jsou tam.
{7000}{7055}Jsou...|Jsou úplnì na uhel...
{7071}{7131}Vypadá to, e chvíli|byly uvnitø tvého fireballu.
{7131}{7174}Mám hlad...
{7208}{7254}No a teï jsou to Berserkové.
{7293}{7352}Dali byste u koneènì pokoj?!
{7352}{7409}Pokoj! Pokoj!
{7603}{7721}"Zapøísahám se temnotám.|Vzıvám tì!"
{7829}{7908}Tak, nakonec jsi pøišel,|Monstrum Zorom.
{7948}{8016}Je mi ctí,|e jste mì pozval.
{8037}{8096}Ukládám ti dvì úlohy.
{8096}{8155}Za prvé, ukradni|Kámen Mudrcù...
{8155}{8219}...ukrytı uvnitø|Orihalconské sošky.
{8219}{8283}Za druhé, zabij toho,|kdo mì zradil.
{8288}{8324}Nic jednoduššího.
{8324}{8435}Pøi zabíjení zrádcù|si dopøeji trochu èasu.
{8456}{8562}Vaše rasa se vyívá|v lidském strachu.
{8562}{8631}Jen se s nimi nehraj moc dlouho.
{8649}{8706}Udìlám to tak pøesnì,|abychom byli oba spokojení.
{9006}{9091}Jsem hladová. Unavená.|Chci si dát koupel...
{9099}{9141}Dokáeš jít a zároveò mlèet?
{9144}{9233}Myslela jsem, e v tomhle|"mìstì" bude alespoò NÌCO...
{9242}{9303}...ale tohle je jen|obyèejné mìsto duchù!
{9316}{9372}Je to u deset let,|co tu nikdo nebydlí.
{9401}{9487}A kromì toho, jak to,|e nás dokázali najít?
{9499}{9564}Ach...|To kvùli mì.
{9582}{9674}Mé tìlo bylo vytvoøené|Rezovou magií.
{9681}{9758}Nechávám za sebou|stopu, kamkoli se hnu.
{9772}{9840}Rezo mì mùe kdykoliv|lokalizovat.
{9850}{9936}Chápu. Není divu,|e bìháme z maléru do maléru.
{9945}{9993}Pøesnì tak.
{10008}{10063}Take nás vystopují všude,|kam pùjdeme.
{10076}{10119}Tys to øekla.
{10127}{10199}Tak vylezete u koneènì?!
{10242}{10311}Další nepodaøenı pøepad.|Co Dilgeare?
{10382}{10429}Vítej, mùj drahı Zele.
{10660}{10705}Tak tohle je trochu moc...
{10720}{10797}Dokáeš sám porazit|takovou armádu, Zelgadisi?
{10806}{10843}Tak moment!
{10853}{10895}Nepøehlííš nìkoho náhodou?
{10944}{10968}Koho?
{10968}{11007}Mnì, ty hlupáku! Mnì!
{11033}{11085}A co má bıt?
{11085}{11157}Ty slova ti dám serat.
{11157}{11231}Nejsem u ta chudinka,|kterou jsi poznal pøedtím!
{11245}{11294}Šetøi si síly.
{11294}{11384}Kdy se vyèerpáš teï,|nebudeš mít proti Rezovi šanci.
{11408}{11472}A pøesnì toho chce takhle dosáhnout.
{11472}{11516}Pìknı zbabìlec,|nemyslíš?
{11516}{11567}Kdy u, tak budu muset|pouít menší trik.
{11567}{11608}"Zdroj veškeré síly..."
{11633}{11669}Nenechte ji to dokonèit!
{11689}{11752}"Svìtlo, které hoøí|karmínovım plamenem..."
{11770}{11825}"Nech se tvá|síla shromádí v mé dlani!"
{11864}{11912}Fireball!
{11975}{11995}Teï!
{12316}{12364}Vıbornì!|Má síla je zpátky!
{12378}{12427}V tom pøípadì si je|rozdìlíme na pùl!
{12435}{12471}OK!|Nech to na mì!
{12521}{12541}Stùjte!
{12552}{12592}Na co èekáte?!|Tudy!
{12696}{12767}Poèkat, všichni jdou|jen za Zelgadisem!
{12940}{13012}Pøedpokládám, e jsi další|z Rezovıch hrdloøezù?
{13050}{13096}A co kdy jsem?
{13126}{13179}No, tak se podívej...
{13187}{13248}Co jiného? Fireball!
{13257}{13303}Ztráta èasu.
{13338}{13390}To sebevìdomí|tì mùe stát ivot.
{13543}{13588}Nemìl jsi povolit|svou pozornost!
{13824}{13937}Byl jsem nevšímavı.|Vıbornì, srdíèko.
{13937}{13996}Ale ta tvoje|magie mì neporazí!
{14014}{14086}Fireball na nìj neúèinkoval...|Monstrum?!
{14111}{14153}Samas to øekla!
{14300}{14390}Povìz mi, kde je Kámen Mudrcù,|a já tì nechám naivu.
{14393}{14480}Záporòáci tohle|nikdy nedodrí.
{14495}{14545}Mám ti dát své slovo?
{14930}{15000}Je to past! Všichni ven!
{15134}{15156}Hej, staøíku...
{15156}{15209}Promiò, e mám|ty své pøedsudky,...
{15209}{15279}...ale nevypadáš jako nìkdo,|kdo své sliby dodrí.
{15279}{15344}Tak v tom ti bohuel nepomùu.|A teï zemøi!
{15379}{15423}Jdem na to!
{15434}{15482}Digger Bolt!
{15501}{15530}Hlupáku!
{15588}{15611}Coe?!
{15641}{15675}Tomu se nevyhnu!
{15970}{16027}Koneènì se potkáváme, Lino.
{16027}{16061}Gourry!
{16088}{16142}No, take tohle je|tvùj další spojenec?
{16142}{16196}ádnı spojenec.|Já jsem její ochránce.
{16196}{16240}Kdo je ochránce?!
{16240}{16284}Její ochránce, øíkáš?
{16284}{16339}Tak mì nech, abych se tì|na nìco zeptal.
{16375}{16438}Ty víš, kde je ten|Kámen Mudrcù, e?
{16441}{16495}Kámen Mudrcù?|A to je co?
{16495}{16603}Ti chlapíci jdou jen|po této Orihalconské sošce, ne?
{16611}{16650}Neukazuj mu to!
{16666}{16719}Ten Kámen je ukrytı v NÍ!
{16732}{16784}No, ale jak jsem|to mìl vìdìt?
{16827}{16911}Tak u vím všechno.|Vás u nepotøebuji.
{16919}{16947}Zemøete!
{16947}{16982}Ne tak pošetile.
{16982}{17052}Nikdo nezemøe, dokud|nenadejde jeho èas, ne, staøíku?
{17235}{17287}Gourry, poèkej chvíli.
{17287}{17313}Co?
{17313}{17371}Ale nic, pojï sem,|nìco ti chci øíct.
{17392}{17414}Utíkej!
{17475}{17547}Co je to s tebou?!|Co se dìje?!
{17547}{17619}Sklapni a utíkej,|idiote! UTÍKEJ!
{17631}{17712}Útìk je všechno co znají.|Je to o hodnì lepší zábava.
{17990}{18039}Za ním!
{18059}{18107}- To je ale zápach!|- Není divu.
{18122}{18163}Kde to jsme?
{18163}{18215}Vypadá to jako chlívek.
{18230}{18280}Proè se tu|musíme schovávat?!
{18286}{18345}Ty jsi s ním chtìl|bojovat, co?
{18346}{18370}A nemìl bych?
{18370}{18462}Poslouchej, ten chlap je Monstrum.|Èistokrevné Monstrum! Rozumíš?
{18494}{18574}Tím svım meèem|ho ani neškrábneš.
{18592}{18647}- Chápu...|- Nic nechápeš!
{18647}{18702}Èistokrevné Monstrum má|nehmotné tìlo...
{18702}{18785}Jako duch s vysokou hustotou!
{18785}{18912}Nìco takového nemùeš porazit magií,|ani konvenèními zbranìmi!
{18924}{19012}Take tím meèem ho neporaníš.|U rozumíš?!
{19026}{19126}Ale proè pouili chlapíka, jako on,|aby ukradl tu sošku?
{19130}{19165}Pro boha ivého!
{19165}{19233}Protoe ten Kámen Mudrcù|je ukrytı v jejím vnitøku!
{19233}{19258}Vánì?
{19258}{19314}A ne se stihneš zeptat,|tak ten Kámen je úlomek...
{19314}{19384}...z hmoty Bohù, která drí|tenhle svìt pohromadì!
{19384}{19465}A mùe to fungovat jako ultra-silnı|zesilovaè magie!
{19465}{19545}Take to je nìco,|s èím mùeš ovládat celı svìt!
{19548}{19639}Tak podívej, jedné vìci|pøeci jen rozumím.
{19639}{19695}A to je co?!
{19695}{19777}Ty skuteènì nemáš ádná prsa,|jak se tak dívám.
{19809}{19855}Poslouchej, ty...!
{19887}{19914}Co to...?
{20130}{20236}Moná skáèeš dobøe pøes švihadlo,|ale schovávaèku tedy hrát neumíš!
{20254}{20285}To mám radost.
{20285}{20350}Kdy Pán Rezo získá svùj zrak,|první vìc kterou uvidí...
{20361}{20416}...budou vaše pozùstatky!
{20933}{20997}Hádal bych, e teï|jsou síly vyrovnané.
{21000}{21062}K èertu... Co jsi to|za pøíšeru?!
{21075}{21152}Ty jsi ten poslední,|kdo mi bude øíkat pøíšera!
{21248}{21316}Rodimusi! Zolfe!
{21346}{21403}Koneènì jste pøišli!|Jsem zachránìn!
{21512}{21566}Lino, pokus se odvést jeho pozornost-|Aúú!
{21654}{21689}Odvést pozornost?
{21737}{21801}Ty nikdy nikoho|neposloucháš, e?
{21801}{21837}No, dobøe...
{21842}{21896}Flare Arrow!
{22263}{22289}Co?!
{22504}{22548}Uhıbáš dobøe.
{22548}{22619}A to dìvèe èaruje|s velkou zruèností.
{22619}{22721}No tak, asi nadešel èas,|abych si pøestal hrát!
{22846}{22872}A to má bıt co?
{23264}{23336}Jeho vkus nestojí za nic,|nemyslíš?
{23336}{23372}Velmi...divné...
{23423}{23483}Promiòte mi to zdrení!|Jdeme na to!
{23580}{23654}No, zdá se, e šance|u nejsou a tak vyrovnané!
{23654}{23693}Myslím,|e jsme ve vıhode!
{23766}{23838}Uvidíme, jak pøeiješ tohle, Zele!
{23914}{23973}Koneènì jsme vás našli!
{23973}{23995}Rodimusi...
{23995}{24063}Rodimusi, ty...?!|Ty jsi...?!
{24097}{24179}Hlupáku! Má loajalita|patøí Pánovi Zelgadisovi!
{24203}{24269}Nech si ten Rudı Knìz|øíká, co chce...
{24269}{24313}...mé sluby nikdy|nepatøili jemu!
{24331}{24354}Ty jeden...!
{24476}{24561}Rodimusi... ty bastarde...
{24682}{24720}Nezapomeò na mì!
{24755}{24779}Ty...!
{25040}{25150}Aby vás èert vzal!|Nemùete poèkat, dokud znovu neoiju!
{25493}{25559}Hádala bych, e ten|staøík se na nás naštval.
{25559}{25630}Lina, jdu na nìj.|Kryj mì!
{25630}{25710}Nerozumíš tomu?!|Nebude to fungovat!
{25710}{25768}Sklapni a dívej se!
{25768}{25826}Ale... Kam si myslíš,|e jdeš?!
{25998}{26054}Snad si nemyslíš,|e mì tou jehlièkou porazíš!
{26054}{26110}No, nestyï se a aspoò|mi to zkus vysvìtlit.
{26136}{26184}Tímhle tì urèitì|neporazím!
{26200}{26295}No, aspoò je v nìm špetka logiky.|Tak, co s tím budeš dìlat?
{26307}{26345}Udìlám tohle.
{26390}{26425}U rozumíš?
{26440}{26479}Víš vùbec, co dìláš?!
{26479}{26619}Chlapèe, nerozumím ti|jediné slovo.
{26631}{26669}A co teï?
{26702}{26735}Zbláznil ses?!
{26735}{26792}U rozumím,|rozumím dokonale...
{26805}{26859}Jsi ubohı blázen!
{26937}{26988}Oh, u nemám na vybranou!
{26988}{27078}Ukáu ti, jak jsem|ve skuteènosti silná!
{27115}{27204}"Temnota pøed úsvitem,|karmín krvavìjší ne tekoucí krev."
{27241}{27276}"Pochovanı v pøílivu èasu..."
{27293}{27357}Vyjdi, Svìtlo!
{28023}{28058}Meè Svìtla...
{28058}{28118}Legendární meè,|kterı zabil...
{28178}{28280}...slavnou bestii|Zanaffara jedinım úderem!
{28280}{28318}Gourry...
{28359}{28384}Lino!
{28408}{28432}Gourry...
{28432}{28473}Dej mi ten meè!
{28521}{28594}Tak moment, a co takhle povìdìt|"Dìkuji", anebo nìco?
{28594}{28687}Podìkovat ti mùu pozdìji!|Jen mi dej ten meè!
{28687}{28780}No tak, uka!|Dám ti za nìj 500 støíbrnıch!
{28800}{28900}500? To je cena tak akorát|za normální meè!
{28915}{28999}Kterı blbec by prodal|Meè Svìtla za takovou cenu?
{29016}{29102}A vùbec, tento meè je|v první øadì pøedevším rodinnı poklad.
{29102}{29149}Neprodal bych ho|za ádnou cenu!
{29149}{29253}Tak mi ho dej a JÁ si ho|ponechám jako "svùj" rodinnı poklad!
{29253}{29350}Dej mi ten meè! Gourry!|Prosím? Prosím?
{29397}{29455}Zdá se, e jste to|zvládli bez problémù.
{29491}{29515}Zelgadisi!
{29523}{29632}Ne! Gourry, poèkej!|Zelgadis je na naší stranì!
{29632}{29660}Je co..?!
{29660}{29732}Pozdìji ti to vysvìtlím.|Ale teï mi dej ten meè, OK?
{29765}{29847}U jsme toho spolu zaili dost,|ale jsme na stejné stranì.
{29847}{29879}Jak se máte?
{29879}{29915}Wow...
{29944}{29979}Odpouštím vám!
{29999}{30057}No, koneènì jsem se|s Gourrym potkala.
{30066}{30133}Ale stále proti sobì máme Reza,|take nemáme èas na oddych.
{30146}{30221}Musíme zùstat ve støehu,|a se dìje cokoliv.
{30230}{30262}Pokraèování pøíštì.
