{1}{1}23.976
{88}{146}Kde se objeví monstra,|pøicházím, abych je porazila!
{163}{229}Kde se zatøpytí poklady, objevím se,|abych se jich zmocnila!
{229}{336}A kde se mi postaví nepøátelé,|tam vítìzství bude mé!
{2398}{2446}Lina Inverze je tu zas.
{2446}{2527}Potrestala jsem zlé bandity|a pøivlastnila si jejich poklady.
{2527}{2617}Jakısi mu, jménem Zelgadis,|pøede mnou odhalil své zámìry.
{2617}{2704}Vyšlo najevo, e chce vzkøísit|Temného Pána Shabraninga.
{2704}{2792}A nakonec se objevil velkı uèenec,|Rezo, Rudı knìz...
{2792}{2869}...a potvrdil Zelgadisovo nepøátelství.
{2870}{2937}A vidím, e zas utíkám jak cvok...
{2938}{3003}...to dìlám s Gourrym u od zaèátku.
{3003}{3050}Co myslíš tím od zaèátku?
{3118}{3209}ÚTÌK! Utíkejte!|Moje magie nefunguje?
{3339}{3464}Gourry! Ty skuteènì|nevíš nic o Shabranigdovi?
{3659}{3702}Ne, nevím vùbec nic.
{3744}{3810}{Y:i}Legenda o Shabranigdovi|je tak známá...
{3830}{3969}{Y:i}Myslela jsem, e ji znají všichni,|a ne jenom mágové a knìí.
{4034}{4106}OK, tak teda zaènu|od zaèátku.
{4112}{4194}Myslíš, e vydríš poslouchat|ten starı pøíbìh?
{4194}{4219}Jasnì, jasnì.
{4244}{4336}{Y:i}Má to vùbec smysl?|Pochybuji, e by tomu porozumìl.
{4387}{4413}Tak zaèni.
{4413}{4544}Jedna legenda vypráví, e|velmi, velmi dávno...
{4557}{4680}...byl svìt, ve kterém ijeme,|napíchnut na obrovskou hùl.
{4680}{4804}Teï svìt existuje na jejím povrchu,|hladkı a okrouhlı, jako...
{4896}{4976}Vezmi si tohle vejce,|napíchnuté na vidlièce.
{4976}{5030}Pøedstav si to nìjak takhle.
{5149}{5219}A na okrajích našeho svìta...
{5219}{5321}...dvì skupiny svádìli|starovìké bitvy.
{5472}{5568}Na jedné stranì Monstra|a na druhé Bozi.
{5568}{5679}Vedl je Shabranigdo,|Pán Temnoty...
{5679}{5749}...a Ceiphied, Draèí Bùh.
{5980}{6075}Válka zuøila po stovky,|ne po tisíce let.
{6075}{6190}Nakonec se Cephiedovi podaøilo roztrhnout|Shabranigda na sedm kouskù.
{6190}{6255}A ukryl je nìkde|na našem svìtì.
{6330}{6389}Take ho Ceiphied porazil?
{6403}{6481}Ne, jen uvìznil.
{6498}{6581}Povídala si, e ho rozètvrtil|na sedm kusù!
{6581}{6670}Proè by to mìlo Monstru vadit?
{6670}{6760}A i kdy se ho Ceiphiedovi podaøilo uvìznit...
{6760}{6851}...musel k tomu vynaloit|všechnu svou sílu.
{6851}{6895}Ale, ale...
{6895}{6968}A potom, pøed tisíci roky...
{7005}{7090}Jeden ze sedmi Shabranigdovıch|úlomkù znovu oil.
{7117}{7207}Avšak jediná zbıvající|èást Ceiphieda...
{7207}{7286}...ho porazila s pomocí|Vodního draèího krále...
{7286}{7369}...jeho tìlo bylo|zapeèetìno v Zemi.
{7474}{7519}Nesmyslné bitvy...
{7519}{7618}Jejich síly spolu zuøivì soupeøili.
{7618}{7748}A rovnováha míru na našem|svìtì byla narušená.
{7748}{7841}A tak se zaèali objevovat|první monstra.
{7894}{7941}Chápeš to?
{7941}{8023}- Ani trochu!|- Proè mì to nepøekvapuje?
{8023}{8166}Ale došlo mi, e ten Shabra-nìco|je hlavním velitelem tìch pøíšer.
{8195}{8286}No, es pochopil alespoò tohle,|je u tebe velmi pùsobivé.
{8328}{8372}{Y:i}Temnı Pán Shabranigdo...
{8372}{8463}{Y:i}Neznám skuteènou sílu|jeho schopností...
{8463}{8542}{Y:i}...ale vsadím se o všechno,|e s ním budou jen samé potíe.
{8634}{8674}To je moje klobása!
{8700}{8798}Kdy jsi se tak dívala do prázdna,|tak jsem si myslel, e u nechceš.
{8798}{8884}Ale chci! Nikdy|nekraï jídlo druhım!
{8924}{8996}Hele!|Tak tolik jsem ti já nesebral!
{8996}{9024}Pøestaò!
{9051}{9097}Aspoò ti dám lekci.
{9097}{9159}Ty si vdycky najdeš|dobrı dùvod.
{9277}{9343}No, moná byl mùj vıklad|trochu moc jednoduchı...
{9343}{9463}...ale porozumìl jsi z té Shabrianigdovo|legendy alespoò nìèemu?
{9463}{9505}No...
{9505}{9614}Take ten Zelga-nìco|chce pøivést...
{9614}{9746}...tìch sedm úlomkù|Shabranigda k ivotu?
{9769}{9821}Jo, øeks to pìknì dobøe.
{9821}{9957}Pokud vezmeme to, co tvrdil ten|chlapík kterı si øíkal Rezo, jako pravdu.
{10033}{10126}{Y:i}Ano, vlastnì stále nevíme,|zda to skuteènì byl Rudı Knìz...
{10126}{10182}{Y:i}...ale mìli bychom|s ním poèítat.
{10182}{10318}Kdy tak nad tím pøemıšlím, nezdálo se mi,|e tomu Rezovi nìjak zvláš dùvìøuješ.
{10400}{10472}Nemáme jedinı dùkaz,|e to je skuteènı Rezo.
{10506}{10564}Mùe se za nìj jen vydávat.
{10579}{10671}Ten chlap je prakticky legenda.|Kdokoli se za nìj mùe vydávat.
{10671}{10736}A navíc nikdo u o nìm neslyšel|pøes deset let.
{10754}{10831}Mohl ho poslal|ten Zelga-nìkdo...
{10831}{10909}...aby se nám dostal pod kùi.
{10922}{11004}Pøesnì. No, moná to|byla jen atrapa,...
{11004}{11060}...ale urèitì to není jen|tak nìjakı obyèejnı mág.
{11060}{11124}Je èím dál víc podezøelejší...
{11124}{11187}Poèkej! Naznaèuješ, e mi vìøíš?
{11187}{11231}Moná ti nevìøím.
{11261}{11327}- K èertu, to je tak protivné!|-Jen ertuji.
{11327}{11392}Náhodou umím velmi dobøe|odhadnout charakter.
{11422}{11461}Dìkuji, Lino.
{11495}{11565}{Y:i}U jsem si skoro zvykla,|e se ke mì chová jako k dìcku...
{11565}{11622}{Y:i}...e si u toho ani nevšímám.
{11675}{11750}"Ty, kdo plaveš v moøích|Astrálního Prostoru."
{11750}{11818}"Odhal mi stíny, které hledám."
{11858}{11960}Poøád to nefunguje.|Co je dìje?!
{11960}{12062}No? Stále ádná|stopa po našem cílu?
{12077}{12107}Mistøe Zelgadisi!
{12129}{12242}Ne, mùj pane. Køišálová koule stále|nedokázala od minulé noci urèit polohu.
{12275}{12370}{Y:i}To dìvèe ji nemohlo ztratit|mezi vèerejškem a dneškem.
{12370}{12441}{Y:i}Nìco se snad mezi nás vmìšuje?
{12441}{12517}V poøádku Zolfe.|Máme jistou šance.
{12517}{12611}Zkus ještì nìkolikrát to|hledání v køišálové kouli.
{12620}{12683}Ještì jasnou a naposled|s ní zkusíme uzavøít obchod.
{12920}{13026}U mì nudí se|dívat jen na samé stromy.
{13040}{13071}Tak s tím ti nepomùu.
{13081}{13183}Nejlepší cesta do Atlas City|vede pøes tyhle lesy.
{13259}{13312}Hele, Gourry.
{13316}{13415}Pamatuješ se, jak jsem v noci pøipomínala,|e se nás pokusí znovu pøepadnout?
{13442}{13557}Podívej, následujících pár dní|nebudu mít své magické schopnosti...
{13572}{13680}...take se budu pøi boji|dret blízko tebe.
{13690}{13745}Nemùeš pouívat magii?
{13745}{13793}No, podívej.
{13861}{13912}"Zdroj veškeré síly..."
{14052}{14094}Obloha?
{14210}{14233}Vidíš?
{14233}{14293}Úplnì jsi ztratila|své magické schopnosti?
{14311}{14387}Myslím, e po dva èi tøi dny|nevykouzlím ...
{14405}{14445}...nic silnìjšího ne osvìtlovací kouzlo.
{14493}{14524}To je ten èas v mìsíci, co?
{14528}{14558}Nech toho, Gourry!
{14558}{14622}Ten èas, co o nìm dìvèata|tak nerada mluví.
{14630}{14746}Kdy knìky a èarodìjky|ztrácí své magické schopnosti...
{14772}{14837}Odkud proboha ví chlap s mozkem medúzy...
{14837}{14903}...a svaly trolla o tomhle "èase v mìsíci?"
{14915}{14989}Co naznaèuješ tím|mozkem medúzy a svaly trolla?!
{14989}{15040}No, to je popis,|kterı se hodí na nás oba.
{15040}{15100}Tak odkud to víš?
{15100}{15160}No, je to malièkost, opravdu.
{15189}{15256}V dìtství jsem il, nedaleko eny,|která pøedpovídala budoucnost.
{15256}{15323}Ale vdy na pár dní v mìsíci|musela zavøít obchod.
{15344}{15394}Kdy jsem se ptal,|proè to dìlá...
{15409}{15490}...povìdìla mi, e je to|prostì ten "èas v mìsíci."
{15490}{15570}Co to ten "èas v mìsíci"|znamená? Nìco vyjímeèného?
{15609}{15637}Tak poèkej...
{15637}{15718}No, myslím, e by jsme si mìli|v této epizodì odpustit všechen humor a vtipy.
{15718}{15807}Nastal èas na vánıch vìcí.
{16287}{16327}To je on.
{16342}{16412}Tak koneènì jsi nechal hraní|a ukazuješ se osobnì...
{16412}{16464}No, Zegaldisi?
{16464}{16518}Um, nejmenuje se náhodou Zeldigas?
{16518}{16549}Opravdu?
{16597}{16646}Mé jméno je ZELGADIS!
{16646}{16695}- Tak vidíš.|- Oh!
{16739}{16834}A mimochodem, chci tu vìcièku!
{16846}{16915}Pokud proti tomu nìco máte...
{16927}{16996}...tak si ji vezmu silou!
{16996}{17093}Tak, èemu dáte pøednost?|Vyberte si!
{17111}{17178}Bıt vámi tak si to|dobøe rozmyslím.
{17302}{17324}Vlkodlak!
{17434}{17488}Vidím, e máš v sobì|krev trolla i vlka.
{17527}{17597}A nebudu se radši ptát|na to smìšné koené brnìní.
{17648}{17765}Take od ní potøebujeme sošku Orihalcon.
{17765}{17802}Správnì, Pane Zelgadisi?
{17802}{17836}Dilgeare!
{17987}{18107}Ach ano, øíkal jste,|abych nic neprozradil.
{18107}{18227}No, na tom u nezáleí.|Beztak tady oba zemøou!
{18238}{18295}Ty jsi tedy ukecanı!
{18302}{18354}Podívej, nevím sice,|jak jsi silnı...
{18354}{18416}...ale nepøej si mì poznat z té zlé strany!
{18416}{18496}Oh, ta sleèinka|má tedy kurá.
{18496}{18558}OK, tak se podíváme,|co je v tobì!
{18562}{18686}V poøádku, ale a vyhraji,|nebude se ti to líbit.
{18686}{18735}Vyøídím vás dva najednou!
{18871}{18916}Na nì, Gourry!
{18951}{18996}Tak, poèkej chvíli!
{18996}{19054}- Co je?|- Nestydíš se?
{19054}{19112}Hej vy dva! Zadrte!
{19142}{19203}Není se èeho bát!
{19234}{19267}Jsem tu!
{19546}{19599}To je ten chlapík z minulé noci...
{19604}{19671}Hej, tøi na jednoho,|to není fér!
{19686}{19767}Nevím, co jste se mnou|minulou noc udìlali...
{19767}{19827}...ale dneska|to bude jiné!
{19851}{19891}{Y:i}Ten tedy neertuje.
{19891}{19973}{Y:i}Oh boe, to zas budeme|muset zdrhnout?
{19995}{20026}Jste pøipravení?
{20075}{20104}Tak do toho!
{20104}{20134}Flare...
{20248}{20278}...Arrow!
{20662}{20680}Lino!
{21032}{21125}Dovol, abych pøezkoušel tvou zruènost!
{21228}{21247}Tìké!
{21300}{21325}Ty utíkáš?!
{21353}{21381}{Y:i}Je dobrı!
{21401}{21482}{Y:i}Budu potøebovat Gourryho,|aby mi s ním pomohl!
{22732}{22805}Mìl bys brát...
{22805}{22858}...ohled na to, e jsem dìvèe!
{22960}{23041}Kdybys mi dala tu sošku|a nedìlala problémy...
{23041}{23100}...nemusel bych zacházet|tak daleko.
{23166}{23205}Take nakonec...
{23258}{23304}...tohle je všechno co umíš.
{23340}{23398}A teï naval tu sošku.
{23424}{23480}{Y:i}"Zdroj veškeré síly..."
{23489}{23555}{Y:i}" Svìtlo, které hoøí|karmínovım plamenem..."
{23572}{23615}{Y:i}" Nech se tvá|síla shromádí v mé dlani!"
{23628}{23659}Lighting!
{23974}{24043}{Y:i}Osvìtlovací kouzlo sice|ještì zvládnu...
{24043}{24113}{Y:i}...ale podruhé mi na|ten trik nenaletí!
{24433}{24537}Jsi docela dobrı,|kdy nás dokáeš vykrıvat oba!
{24561}{24583}Dìkuji!
{24623}{24702}Podívej, jdeme jen|po té dívèinì.
{24708}{24809}Jdi nám z cesty|a nedojdeš k úrazu.
{24884}{24935}Nebuï netrpìlivı.
{24935}{25026}Zrovna teï ji náš velitel|Zelgadis u asi...
{25093}{25116}Lino...
{25375}{25501}{Y:i}Nevím, zda by mùj meè byl nìco platnı|na tu jeho kamennou kùi!
{25524}{25578}{Y:i}Musím najít zpùsob,|jak se mu ztratit!
{25654}{25739}K èertu! Není tu ádné místo,|kde by se dalo schovat!
{25968}{26003}Ale ne.
{26066}{26093}Hop nebo trop.
{26143}{26198}{Y:i}"Zdroj veškeré síly... "
{26202}{26267}{Y:i}"Vítr, kterı fouká|na západ... "
{26353}{26404}Flare...
{26416}{26453}...Arrow!
{26642}{26680}A to bylo co?
{26680}{26754}Take trop!|Radši zdrhnu.
{26990}{27023}Nemùu se hıbat!
{27086}{27116}{Y:i}Shadow Snap!
{27116}{27220}Chytil jsem tvùj stín.|Nemùeš se hıbat, e?
{27220}{27325}To kouzlo znám...|A je jedno z nejslabších.
{27395}{27447}A jeho slabina je svìtlo!
{27600}{27626}Super!
{27888}{27930}Mono Bolt!
{28631}{28723}{Y:i}Tak nakonec|to pøeci jen bude mé.
{29389}{29442}Take u ji má!
{29627}{29687}Huch, zastavte to!|Nemìla bych se...
{29687}{29746}...válet po zemi,|kdy mi stojí práce!
{29746}{29809}Prober se, Lino Inverse!
