{1}{1}23.976
{317}{400}Tam, kde se vyrojí monstra,|objevím se, abych je znièila.
{400}{470}Tam, kde se zatøpytí poklady,|pøicházím, abych se jich zmocnila.
{470}{572}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2647}{2704}Pak, kdy okolo nás všechno vybuchovalo...
{2704}{2774}...a kdy jsme museli hledat|poslední zbytky sil...
{2775}{2845}...jsme ho koneènì porazili!|Temného Pána Shabranigda.
{2845}{2908}Jsme dobøí, ne?
{2908}{2976}Zel se vydal svou cestou|a já doufám, e...
{2976}{3131}...Gourry a já budeme od teï mít|pìkné a klidné putování.
{3152}{3282}KNOCK OUT!|Spor rodiny Seyruunovcù!
{3500}{3529}Proè jen nejde?!
{3529}{3608}Mùeme tu poèkat, ale pochybuji,|e pøijde na takové místo.
{3608}{3701}Ale pøijde! Podle|mıch informací...
{3701}{3777}...by princ mìl projít tudy!
{3777}{3866}Dobøe, moná je to jen šeptanda,|e princ Piriri-atd...
{3866}{3954}...z království Seyruun|cestuje inkognito po okolí.
{3954}{3982}Princ Philionel!
{3997}{4058}I kdyby ten Phili-nìco|jel tudy...
{4058}{4117}...jak poznáš,|e je to princ?
{4118}{4177}No to bude samozøejmì|úplnì jasné!
{4189}{4272}Princ je|dùstojnı, kultivovanı...
{4272}{4315}A také velmi pìknı!
{4375}{4428}Kdy jsi se jednou narodil|se vznešenou krví...
{4428}{4481}...pøirozenì se to odrazí na|tvé øeèi a jednání!
{4481}{4542}A já chci potkat|nìkoho takového!
{4542}{4623}Dobøe, dobøe... A co se stane,|a se s ním potkáš?
{4623}{4682}Uneseš ho a budeš|poadovat vıkupné?
{4682}{4727}Nebuï smìšnı!
{4727}{4833}Jakıkoliv princ, kterého potkám,|bude tak oèarovanı mou silou...
{4833}{4875}Ach, takhle ne.
{4875}{4958}Na první pohled se mu zalíbím|a hned mi navrhne sòatek!
{4958}{5022}A potom si budu ít v luxusu.
{5022}{5066}To myslíš vánì?
{5066}{5109}SMRTELNÌ.
{5156}{5186}No tak...
{5186}{5251}...jdu do dalšího mìsta.
{5251}{5275}Jdi si!
{5282}{5323}Nebudu tì èekat,|to si piš!
{5323}{5392}Pojedu hned za tebou,|v zlatém koèáøe!
{5392}{5430}Jasnì, jasnì...
{5513}{5567}Nenechám si ujít|takovou šanci!
{5762}{5828}Pomote! Kde jste kdo!
{5914}{6029}Tak poslouchej! Kdy hned|nepøestaneš, zabiju tì!
{6062}{6107}Nechte mì ít,|prosím vás!
{6107}{6161}Vysyp všechny peníze, které máš!
{6161}{6192}Ale, ale...
{6206}{6259}Poslouchej, zloduchu lapenı|v osidlech temnoty!
{6259}{6312}Zasuò zpìt svùj meè,|naplnìnı tvou zlou duší!
{6312}{6346}Kdo je tam?!
{6346}{6421}Poslechni mì, nebo jinak|pocítíš kladivo spravedlnosti!
{6421}{6485}Kde jsi?!|Uka se!
{6485}{6513}Tady jsem!
{6948}{6990}Hej. Hej. Hej!
{7172}{7249}A teï, Pane Ïábelskı Bandito!|Pøiprav se!
{7261}{7366}Oh? Pøiprav se na co?|Neohrabané dìvèe!
{7436}{7474}Diem Wing!
{7627}{7697}Hej! Tohle si odskáèeš!
{7698}{7768}Ty jedna malá èarodìjnice!
{7796}{7832}Burst Rondo!
{7999}{8045}No teda...
{8045}{8155}Spravedlivı konec pro toho,|kdo se postavil proti spravedlnosti!
{8155}{8191}Uch, promiòte...
{8191}{8226}Nemusíte mi dìkovat.
{8226}{8282}Nemohla jsem jen tak|neèinnì pøihlíet.
{8283}{8339}Jeho poráka je pro mì|dostateènou odmìnou.
{8339}{8384}Aha, dobøe...
{8396}{8439}A teï, kdy dovolíte!
{8656}{8717}Uch, nejste náhodou...
{8719}{8759}Ne...neprodáváte zvíøátka?
{8807}{8885}Jak tì mohlo nìco|takového napadnout?
{8885}{8963}Nemìli bychom soudit lidi|podle vzhledu.
{8963}{8992}To by nebylo správné.
{9009}{9087}Take je lepší pøedpokládat,|e prodávám zvíøata, co?
{9101}{9163}Jste tedy opravdovı rytíø?
{9163}{9224}No, ano.|I tak se to dá øíct.
{9224}{9353}Mohl byste mi pomoci?|Samozøejmì zaplatím.
{9353}{9407}No, mùeme si o tom promluvit.
{9407}{9443}Ale ještì nìco mì zajímá.
{9443}{9484}Jistì! A co?
{9484}{9565}Proè jsi se objevila|na tom stromì?
{9566}{9609}Vy to nevíte?
{9609}{9697}Všichni bojovníci za spravedlnost|dìlají takové vìci!
{9697}{9786}- Mìj se.|- Prosím! Poèkejte!
{9947}{9976}Nepøišel...
{10072}{10095}Radši pùjdu.
{10269}{10353}Cítím se jak pitomeèek!
{10436}{10482}U je to trochu lepší...
{10667}{10714}{Y:i}Knìz a bandita spolu?
{10820}{10872}{Y:i}Nìco tu nesedí.
{10897}{10970}Mohu pøedpokládat,|e jste èarodìjka?
{11011}{11120}Díky bohu! Mohu vás poádat|o pomoc pøi jedné práci?
{11158}{11221}Chcete ode mì, abych vás|zbavila toho bandity?
{11221}{11276}Bandity? Oh, ne!
{11288}{11334}Co je to potom zaè? Trpaslík?
{11339}{11404}Mohla byste vyslechnout,|co vám chci navrhnout?
{11504}{11547}{Y:i}Ojojoj!
{11616}{11712}Pøedtím, ne si promluvíme,|chci vám prozradit svou identitu.
{11781}{11840}No ne? Ten erb...!
{11857}{11886}Správnì.
{11962}{12058}Tento mu, kterı cestuje|se mnou na zapøenou...
{12058}{12131}...není nikdo jinı ne korunní princ|Philionel el de Seyruun.
{12203}{12222}Co jste...?
{12222}{12321}Tenhle mu|je princ Philionel.
{12340}{12369}Vánì?
{12384}{12410}Opravdu.
{12434}{12510}Néééé!
{12563}{12599}Jste v poøádku?
{12599}{12635}Ne, to tedy nejsem.
{12635}{12681}Dalo se èekat, e|budete pøekvapená.
{12681}{12765}Princ toti cestuje v tajnosti.
{12811}{12896}Ne, to není to, co|mì pøekvapilo...
{12907}{12952}Já se jmenuji Randy|a jsem knìzem jeho velièenstva.
{12952}{12992}Mùeme poznat vaše jméno?
{13003}{13038}Lina... Lina Inverse.
{13081}{13141}To "oh?"|znamená, e jsem známá?!
{13148}{13210}Ty si ta èarodìjka?
{13210}{13271}Lina Zabíjaèka Banditù?
{13271}{13328}Ano, u jsme o vás|nìco slyšeli.
{13411}{13453}Co?
{13454}{13527}Chcete øíct, e|øeèi o vás nejsou pravdivé?
{13527}{13574}Ne, ne celkem.
{13581}{13670}Kdy chcete, mùete mì|nazıvat Phil.
{13670}{13769}Nemusíme bıt formální,|kdy cestuji potají.
{13807}{13880}Sleèno Lino, chceme od vás,|abyste zabila obludy.
{13895}{13933}Zabít obludy?
{13933}{14005}Nedaleko je jeskynì,|v které ijí pøíšery...
{14005}{14077}...a ty v poslední dobì|ohroují okolní vesnice.
{14101}{14202}Jeho Vısost se o tom na svıch|cestách doslechla...
{14202}{14303}...a z milosti svého srdce se|rozhodla dát je vymítit.
{14303}{14414}Ale Randy je sám|nezvládne.
{14414}{14538}A takové malé vesnice|nemají ádné vojáky.
{14538}{14626}Jene Phile, ty vypadáš, e|se dokáeš otáèet v boji.
{14627}{14661}Proè si to myslíš?
{14674}{14719}Noo, kdy se tak na tebe dívám...
{14730}{14813}Oh, ale to je jen pøevlek|abych mohl cestovat nepoznán.
{14821}{14934}Nezáleí na tom, jak vypadám,|já jsem pacifista.
{14989}{15013}Uch, aha...
{15013}{15123}Jene já musím jít za|svım spoleèníkem.
{15123}{15205}Samozøejmì, za dobrou práci|dostaneš odmìnu.
{15205}{15236}Odmìnu?!
{15274}{15320}V tom pøípadì,|mùj spoleèník ještì poèká!
{15440}{15575}Je mi horko... je mi horko!|Co je tohle za poèasí?!
{15575}{15628}Nìco se dìje,|sleèno Lino?
{15628}{15715}Je horko. Je MI horko,|a nedokái se pøestat potit!
{15715}{15787}To je tím kostımem,|co máte na sobì!
{15787}{15851}Tak mi promiò, e|ho nosím!
{15851}{15905}Musím si dát koupel!
{15905}{15941}Koupel?!
{16349}{16401}Ou! Studená! Ou ou.
{16424}{16470}Fire...Ball!
{16606}{16630}To u je lepší.
{16703}{16755}Aaa, to je pocit...
{16765}{16841}- Sleèno Lino! Dìje se nìco?|- Co to bylo za vıbuch?
{16954}{16988}MEGA BRAND!
{17091}{17132}Uch, promiòte. To je reflex.
{17277}{17301}Jsme tady.
{17310}{17403}Hmm... Vypadá to jako|stará zøícenina...
{17403}{17463}Moná nìjaká hrobka.
{17475}{17563}Slyšel jsem, e teï tady ije|hodnì pøíšer.
{17564}{17650}A jejich vùdce je nìkde|hluboko uvnitø jeskynì.
{17650}{17736}Mohu odsud odpálit|celou horu jedinım kouzlem!
{17742}{17801}Nepouívejte kouzla|tak lehkovánì!
{17801}{17885}Och, stále se hnìváte kvùli tomu,|co se stalo pøedtím?
{17885}{17949}No tak, vdy jsem vás jen|trochu zahøála, ne?
{17949}{18040}Nejde o tohle! Kdy je pouèíme o tom,|co je dobré a co zlé...
{18040}{18099}...moná se ty kreatury vrátí|zpìt na cestu dobra!
{18142}{18244}Nemùu pouít silná kouzla|na takhle úzkém místì.
{18244}{18291}Opravdu?
{18449}{18519}Orkové. Postarám se o nì|jedinım kouzlem.
{18519}{18576}Poèkejte! Promluvím si s nimi.
{18576}{18660}"Promluví si s nimi?"|Phil mluví orkštinou?
{18660}{18695}Ani slovo.
{18721}{18821}Utvoøte koridor a nechte nás projít!|Nechceme vás zabít!
{18821}{18887}Ale kdy neuposlechnete|mé varování...
{18887}{18979}...budete èelit hnìvu té|brutální èarodìjnice za mnou!
{18979}{19037}Hele, dávej si pozor, na to co øíkáš!
{19037}{19110}Tak, co udìláte?
{19110}{19150}Take?!
{19191}{19310}Ha, to by jim mìlo staèit! Èisté a|upøímné srdce vdy zvítìzí!
{19322}{19369}Mnì to znìlo jako|obyèejné vyhroování.
{19418}{19466}Vpøed, pøátelé!|Vpøed!
{19585}{19612}Ustup nám z cesty!
{19672}{19714}Ta proklatá vìc mì neposlouchá!
{19721}{19762}Nechte to na mì.
{19799}{19831}Balus Rod!
{19898}{19950}Øíkejte mi královno!
{19989}{20045}Jsi z nìjaké|královské rodiny?
{20045}{20113}Ale, no tak! To musím|vysvìtlovat kadı hloupı ert?!
{20143}{20188}A teï je tu troll!
{20209}{20247}Damu Bras!
{20247}{20283}Oh, minotaur!
{20283}{20319}Digger Bolt!
{20326}{20365}Salamandr!
{20365}{20404}Ly Breim!
{20426}{20479}-Upír!|-Assha Dist!
{20503}{20575}Èlovìk se pøi ní cítí|tak trochu zbyteènı, e?
{20575}{20630}- Hej...|- Hej, podívejte se na tohle!
{20641}{20678}Nìco je pøímo pøed námi!
{20841}{20887}Tam by mìl bıt šéf.
{20887}{20956}- Nastal èas støetnout se s ním!|- Hej-hou!
{21105}{21127}A po tobì.
{21283}{21353}Èekal jsem vás,|princi Philionele.
{21353}{21423}Ty ïáble!|Odkud znáš mé jméno?!
{21522}{21581}Prosím vás, neøíkejte|mu princi!
{21648}{21744}Mimochodem, vaše cesta|tady konèí!
{21761}{21863}Proè... Proè vyhrouješ|takové jemné duši jako jsem já?!
{21863}{21968}Kdo je tu jemnı?!
{22057}{22125}Protoe jsem ho o to poádal!
{22125}{22159}Coe?
{22159}{22267}Nezapomeò, e jsem tøetí v|poøadí nástupcù na trùn!
{22267}{22375}Ale musel jsem ít ve stínu|svého staršího bratra.
{22435}{22500}Vùbec si nejste podobní.|Je to pravda?
{22500}{22581}Aha, take tohle je jenom|velká rodinná hádka, e?
{22627}{22730}Mùj mág na vás pøipravil|past, a proto jsme tady.
{22730}{22785}Myslíš tím ty pøíšery...?
{22785}{22840}Samozøejmì. Vlastní vıroba.
{22840}{22895}A co udìláš, a bude|království tvé?
{22895}{22974}No... Potom... Chtìl jsem|trochu vládnout a tak...
{22974}{23053}Víš, svìt je plnı takovıch|polo-králù jako ty.
{23053}{23093}Sklapni! Na nì, chlapci!
{23138}{23186}Ty...!
{23204}{23263}Pokud na tomto svìte|existuje zlo...
{23263}{23322}...hnìv spravedlnosti|ho srazí na zem!
{23370}{23453}Proti kadému zloduchovi na svìtì,|a u je z mé vlastní rodiny nebo ne...
{23453}{23505}...moje spravedlivost nebude váhat!
{23505}{23565}- Amélie?!|- Gourry?
{23565}{23638}Oh, boe...|Prosím, nedívej se na mì.
{23639}{23712}Ahoj, otèe!|Koneènì jsem tì našla!
{23723}{23763}O...Otèe?
{23835}{23878}Ale vdy se ti|vùbec nepodobá!
{23878}{23957}Ale ano, je to moje|milovaná dcera, Amélie.
{24009}{24070}Dobøe, všichni!|Pøipravte se!
{24351}{24386}Hej. Hej. Hej!
{24495}{24518}Díky!
{24518}{24628}Take, strıèe Randy! Pokud lituješ|svıch høíchù alespoò trochu...
{24628}{24689}...tak ti mùj otec|moná odpustí!
{24727}{24766}Kuš... Na nì!
{24815}{24841}Fireball!
{24891}{24914}Digger Bolt!
{24974}{25086}Co je zaè? Je to nìjaká|pošahaná hrdinka nebo co?
{25086}{25198}Povídala, e hledá svého otce|a poádala mì o pomoc.
{25198}{25261}Ty jedno mrnì...|Já tì... Pojïme na to!
{25292}{25397}Uka se, spojenèe náš:|Bras Demon! Garundia!
{25491}{25548}Ach, podívej. Dokonce dokázali|vyvolat takovou vìc.
{25548}{25593}- Je silná?|- Tak trochu.
{25600}{25657}Vy, kteøí kontrolujete síly|Monster!
{25657}{25706}Chudáci, jejich srdce|jsou pøeplnìné zlem!
{25706}{25847}Spojili jste se s tìmito|monstry, jen abyste mne zabili?!
{25847}{25929}Ani pacifista jako já|vám tohle nikdy neodpustí!
{25941}{25984}Hej, poèkej!|Tohle ty nezvládneš.
{25984}{26030}Úder Pacifisty!
{26113}{26152}To není moné!
{26155}{26217}Milostivı-kop-Všem-Obludám!
{26226}{26255}Co je, k èertu, tohle?!
{26302}{26337}Náš spojenec, Garundia!
{26337}{26407}Nepanikaø!|Zavoláme si na pomoc další Monstrum!
{26439}{26492}Vyjdìte, spojenci naši!
{26584}{26656}Ti omezenci!|Pojïme, Amélie!
{26656}{26689}Ano, otèe!
{26709}{26744}Diem Wing!
{26846}{26903}Úder Dobré-Vùle-Všem-Lidem!
{27015}{27074}Vy otravní hlupáci!
{27074}{27133}Vyjdi, kdokoliv!
{27142}{27202}Strıèku! Vzdej se|svıch zloèinnıch ambicí!
{27242}{27308}Já... Já jsem|král Seyruunu!
{27333}{27376}Tady máš! Fireball!
{27449}{27477}Fireball!
{27498}{27580}Vy hlupáci! Víte, co se|stane, a se srazí?!
{27784}{27887}Jen jsem chtìl bıt|králem Seyruunu!
{28160}{28189}Randy...
{28189}{28256}Mìl jsi zapomenout na|ty hloupé nápady...
{28256}{28278}Otèe!
{28294}{28322}Polo mì dolù!
{28322}{28389}Aha, dobøe. Promiò.
{28389}{28477}Amélie, co tu k èertu|dìláš?
{28477}{28525}Otèe, jsi tak zlı!
{28525}{28587}Vdy cestuješ|na zapøenou a zaíváš...
{28587}{28640}...všechna ta úasná dobrodruství|beze mì!
{28653}{28700}Take jsi mì šla hledat?
{28700}{28782}Promiò, Phile.|Nerada bych se vmìšovala, ale...
{28782}{28808}Co je?
{28850}{28926}Jen by mì zajímalo,|jak to bude s mou odmìnou.
{28940}{29044}Oh? No, obávám se, e všechny|peníze nesl Randy.
{29085}{29108}A co tvoje dcera?
{29108}{29219}Utratila jsem VŠECHNY peníze|pøi hledání svého otce.
{29219}{29263}U všech bohù!
{29263}{29357}Nehnìvej se! Mùeš jich mít, kolik|chceš, a se vrátíme do Seyruunu!
{29394}{29479}Seyruun! Seyruun|je odsud daleko!
{29479}{29542}A ani jsem se tam nechystala!
{29542}{29610}No, nikdo tì|nenutí.
{29610}{29678}Ale my tì tam|rádi doprovodíme.
{29678}{29725}Ráda vás poznávám!
{29748}{29796}Tak to jsi jediná!
{29893}{29982}A tak se naše malá cestovní|skupinka rozrostla.
{29982}{30070}Jeden z nich je horskı bandita, a|druhá je bláznivá imitátorka hrdinù.
{30070}{30157}Zapomeòte na to. Ve skuteènosti|je to mírumilovnı princ Phil...
{30157}{30204}...a princezna,|temperamentní adeptka magie.
{30204}{30275}Proè já...?
