{1}{1}23.976
{350}{397}Tam, kde se monstra vyrojí,|pøicházím, abych je znièila.
{397}{467}Tam, kde se zatøpytí poklady,|objevím se, abych se jich zmocnila.
{467}{575}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2681}{2744}Souboj s Rezem|spìje ke konci.
{2745}{2830}Jeho skuteènım cílem|je spojit se s Monstry.
{2831}{2910}A navíc, musíme vzdorovat i|Temnému Pánu Shabranigdovi!
{2913}{2978}Nesmíme dopustit jeho znovuzrození!
{2991}{3138}Ale Rezo nás oklamal a|ukradl Kámen Mudrcù.
{3144}{3175}No a teï...
{3177}{3257}Teï pøivolal dokonce|nejtemnìjší z temnıch sil!
{3308}{3451}DOPAD!|Pøedveèer velikého souboje na ivot a na smrt!
{4080}{4126}Vidím!
{4129}{4210}Koneènì vidím!|Mé oèi se otevøeli!
{4547}{4601}Co se to dìje?!
{4680}{4712}Kdo si?!
{4713}{4817}{Y:i}Já jsem ten, jeho|znovuzrození jsi si pøál.
{4819}{4866}NE!
{4945}{4993}"Ten, jeho znovuzrození jsi si pøál..."
{4994}{5119}Shabranigdo! Takhle je to!|Není zakletı ve vìi!
{5809}{5895}Rubínookı Shabranigdo!
{5905}{6000}Správnì! Zakletı v|Rezovıch vlastních oèích!
{6002}{6029}A právì teï znovuzrozenı!
{6225}{6309}Dám vám monost, vybrat si|cestu, kterou chcete jít...
{6313}{6472}...z vdìènosti za to, e|jste mì opìt oivili.
{6489}{6623}Následujte mì|a budete ít dlouho.
{6624}{6752}Ale kdy odmítnete, musíte|bojovat ještì pøed tím...
{6753}{6922}...ne vysvobodím svıch sedm|zbıvajících zakletıch èástí.
{6929}{7007}Proè nám nenabídneš víc?
{7009}{7065}Zemøít nebo slouit ïáblovi!
{7113}{7161}Co si vybereme?
{7193}{7263}Koneènì to pochop. Oivení Temného|Pána zpùsobí ZKÁZU svìta!
{7265}{7312}Ty to vùbec nechápeš, e?!
{7314}{7358}Dobøe, uklidni se. Klid.
{7360}{7408}Co to má znamenat?!
{7448}{7474}Coe?
{7529}{7562}Zolfe, ty-
{7576}{7647}Nebuï smìšnı!.|Lidstvo je dál...
{7650}{7733}...za tìch tisíc let,|cos byl zakletı!
{7735}{7811}Teï uvidíte, jak velkı Zolf|porazí legendárního Temného Pána!
{7816}{7855}Ale ne, takové chvástání!
{7858}{7916}Další, kterı vùbec|nic nepochopil!
{7966}{8057}"Temnota pøed úsvitem,|karmín krvavìjší ne tekoucí krev."
{8064}{8151}Co? Dragon Slave?!|Zolf? Ten tøetiøadı mág...?!
{8160}{8228}"Pochovanı v pøílivu èasu...|Ve tvém velkém jménu,..."
{8233}{8305}Nejsilnìjší kouzlo|celé èerné magie!
{8312}{8380}I tak... Zastav to, Zolfe!.|Nebude to fungovat! Stáhni se!
{8446}{8494}Pøestaò, Zolfe! Pøestaò!
{8506}{8568}"...budou znièení silou,|kterou spoleènì vládneme!"
{8585}{8623}DRAGON SLAVE!
{8762}{8783}Dokázal jsem to!
{8969}{9038}On... On ještì ije!|Uteè, Zolfe!.
{9066}{9083}Rychle!
{9242}{9273}Rodimusi! Zolfe!
{9513}{9584}Shabranigdo...
{9744}{9778}{Y:i}Ne!
{9873}{9977}No tak, jste pøeci mágové!|Nemùete nìco udìlat?!
{9991}{10058}Utíkejme!
{10169}{10304}Ach, jen utíkejte...|Bìte tak daleko, jak jen dokáete.
{10383}{10471}Beznadìjné!|Absolutnì beznadìjné!
{10473}{10518}Vdy jsme dokázali jenom utéct!
{10520}{10567}Èlovìèe, ten Temnı Pán|je opravdu takovı, jak se øíká.
{10569}{10614}Má ohromnou moc!
{10615}{10769}K èertu s tím! Teï jsme unikli,|ale døíve èi pozdìji si nás stejnì najde.
{10872}{10939}Poslouchejte vy dva, nemohli by|jste bıt trochu optimistiètìjší?!
{10969}{11031}Take... V takıch chvílích|je jediné, co mùeme udìlat...
{11032}{11153}...dobøe se najíst|a po jídle se zabavit!
{11200}{11279}Je to Temnı Pán,|take by mìl nám, slabım lidem,...
{11281}{11377}...dovolit vydechnout a nechat|nás poradit se, jak dál.
{11415}{11453}Poslouchej...
{11456}{11535}Jak se teï dokáeš|takhle nacpávat?
{11538}{11582}Deprese nic|nevyøeší.
{11585}{11640}Jídlo ti vrátí všechnu sílu.
{11641}{11696}Mohlo by to bıt taky naše poslední.
{11760}{11841}Hele, já se vás snaím trochu|povzbudit a vy zatím...
{11870}{11913}Na zdraví!
{12017}{12102}Kdy se podívám, jak|je tenhle svìt klidnı...
{12105}{12187}...je nepochopitelné,|e je Shabranigdo znovu volnı.
{12248}{12273}Je rozkošná!
{12281}{12376}Není to dlouho, kdy jsem|i já byla obyèejné dìvèe jako je ona.
{12401}{12485}Kde se stala chyba?! Znovu oivit|Temného Pána!
{12487}{12553}Kdy jsem se dostala|do této noèní mùry?
{12561}{12655}Promiòte,e jsem vás|do tohoto zatáhl.
{12655}{12737}Ne, ne. Neøekla jsem, e|je to tvoje chyba, Zelgadisi.
{12801}{12855}Hej, u zase máte|pochmurnou náladu!
{12857}{12929}Potøebovali byste|nìjak povzbudit!
{12931}{13025}Hej, hospodo! Kuøata k veèeøi|pro deset, a fofrem!
{13185}{13248}Tøes se, svìte.
{13249}{13380}Obávej se mého pøerodu|a své destrukce!
{13856}{13976}Nemìli bychom se|vrátit k vìci?
{14025}{14102}Ještì chvíli. Mùj aludek je|jen z osmi desetin plnı.
{14104}{14121}Ale poslouchej!
{14152}{14257}Chápu. Bøicho i|mysl jsme si uklidnili.
{14263}{14329}Teï, musíme vymyslet|nìjakı plán.
{14393}{14463}Je zøejmé, e moje|specialita, èerná magie...
{14464}{14509}...ho nemùe neporazit.
{14513}{14623}Ale pokud náš plán zaloíme|na tvé síle Šamanství...
{14625}{14703}...pak bychom moná,|MONÁ mìli šanci.
{14704}{14767}- To nepùjde.|- Pøesnì tak, to nepùjde-
{14769}{14807}Hee?! Nepùjde?!
{14808}{14923}Nebude to fungovat. Všimli jste si, co jsem|dìlal, kdy se zrodil?
{14929}{14999}Hele, pouil jsi nìjaké kouzlo,|které jsem ještì nevidìla.
{15001}{15056}Nic mu to neudìlalo, a...
{15056}{15111}Hele, snad to nebylo...!
{15113}{15150}Ra-Tilt.
{15153}{15190}Oh, boe...
{15193}{15215}Co je to?
{15216}{15308}Ra-Tilt je nejsilnìjší|kouzlo Šamanské magie.
{15313}{15408}Je to zpùsob, jak znièit nepøítele|pomocí sil Astrální, tedy duchovní Roviny.
{15409}{15511}A mìlo by bıt tak silné|jako Dragon Slave.
{15534}{15569}Dragon Slave?!
{15577}{15654}Ano. To je to, co Zolf zkusil pouít|proti Shabranigdovi.
{15654}{15704}Nejsilnìjší kouzlo|celé èerné magie.
{15705}{15774}Jeden mudrc s ním velmi, velmi dávno|zabil draka...
{15776}{15841}...a jméno se zkomolilo|z Dragon Slayer na Dragon Slave.
{15849}{15950}Ale proè na nìj|magie nefunguje?
{15952}{15999}Vzdávám to. Zele, pokraèuj.
{16001}{16081}Šamanství vyuívá síly|Astrální Roviny.
{16110}{16205}Ale Temnı Pán je|jako astrální bytost...
{16206}{16241}...mnohem silnìjší ne my.
{16256}{16326}Dokáe velmi silnì rušit|Astrální energii...
{16328}{16449}...a odvrátit lidské útoky|s minimálním úsilím.
{16465}{16616}A proto ho ádná síla z|Astrální Roviny neporazí.
{16649}{16720}Nevím, zda to dobøe chápu,|ale øíkáte, e Temnı Pán...
{16720}{16833}...je vlastnì duch,|take obyèejná magie na nìj neúèinkuje!
{16849}{16929}No, v podstatì|se nemılíš, ale...
{16993}{17088}Dùvod, proè moje èerná magie|nefunguje, je jednoduchı.
{17098}{17169}Zdroj síly|èerné magie...
{17171}{17264}...pochází ze strachu,|nenávisti, nepøátelství...
{17266}{17306}Z temnıch, negativních|sil svìta.
{17306}{17435}A Shabranigdo je ten,|kterı tyhle síly kontroluje.
{17482}{17528}Øíkal to i Zolf,|kdy pouil to kouzlo.
{17532}{17613}"Temnota pøed úsvitem, karmín krvavìjší ne tekoucí krev."
{17615}{17689}Pøesnì to je Shabranigdo!
{17691}{17745}-Skuteènì to tam bylo?|- Ano, bylo!
{17746}{17825}Take, pouívat proti nìmu|èernou magii je jako øíct...
{17826}{17922}"Hej, ty! Mùeš mi pomoct|zabít tì?"
{17953}{18027}A bílá magie je jen na|léèení anebo oèištìní.
{18051}{18163}To znamená, e já|a Zelgadis ho nemùeme porazit.
{18171}{18266}Take naší poslední šancí|zùstává Gourryho Meè Svìtla.
{18785}{18834}Rád bych to tu|zavøel ještì DNESKA...
{18851}{18929}Udìlám to!|Vím, e nemùu vyhrát...
{18930}{19026}...ale Zolf a Rodimus nikdy|nenajdou pokoj, kdy teï uteèu.
{19042}{19097}OK, já se pøidám.
{19098}{19176}I kdyby to nefungovalo,|nemùu jen tak odejít.
{19193}{19225}Dìkuji ti.
{19226}{19317}Za málo. Sám jsi to øekl.|Teï je to u i mùj problém.
{19385}{19474}Já... Já skuteènì|nechci umøít.
{19493}{19542}Nikdo tì nenutí jít.
{19548}{19586}Ale...
{19659}{19712}Je tu ještì hodnì dobrého|jídla, které mohu sníst!
{19714}{19753}A poklady, které mùu mít!
{19755}{19798}A kdy mì pøestane bavit|studium magie...
{19800}{19864}...mùu jít domù a|zaèít podnikat.
{19866}{19942}Bıt pro zmìnu dìvèetem.|Moná se dokonce i zamiluji!
{19994}{20030}Uch, e by se našel..?
{20035}{20114}Podívejte, je hloupé jít|do boje s vìdomím, e zemøeš.
{20116}{20200}Mui to mohou nazvat|"hrdinské" nebo "romantické"...
{20202}{20264}...ale na takové hlouposti|byste mìli zapomenout!
{20267}{20338}Kdy u jsi jednou mrtvı, je konec!|Nemùeš to vzít zpátky!
{20513}{20562}Dìlej co myslíš.
{20691}{20795}Mùeš utéct,|ale nezkoušej se k nìmu pøidat.
{20803}{20913}Kdy to udìláš,|budeme tì muset zabít.
{20915}{20963}Pojïme, Gourry.
{21010}{21058}Ne tak rychle.
{21102}{21163}Kdo øíkal, e nejdu|bojovat?"
{21171}{21241}-Ale, právì jsi øíkala...|-Nedìlej ukvapené závìry.
{21242}{21289}Øekla jsem jenom, e nesnáším...
{21290}{21370}...ty hrdinské øeèièky jako|"Budu bojovat, i kdy urèitì zemøu".
{21377}{21437}To si radši utrhnu|hubu, ne bych mìla fòukat...
{21438}{21503}...a øíkat nìco slabošského jako|"Oh ne, já nechci zemøít."
{21535}{21609}Chápete? Pokud máme alespoò|jednoprocentní šanci vyhrát...
{21611}{21657}...a budeme se pøesvìdèovat,|e prohrajeme...
{21659}{21719}...to jedno procento se|zmìní na nulu!
{21721}{21769}Nech se stane cokoliv,|já nechci umøít.
{21770}{21818}A proto,|kdy s ním budu bojovat...
{21854}{21890}Zvítìzím.
{21915}{21941}Tak dobøe.
{21946}{21992}Jdeme na nìj!
{22600}{22680}Nejdøív Shabranigdo|a teï ještì trollové.
{22706}{22775}Pochybuji, e je poslal|jako své zabijáky.
{22850}{22928}Uch, zapomeò na to.|Nemyslím si, e jdou po nás.
{23007}{23075}Hej! Jsou trollové|normálnì takhle divocí?
{23090}{23170}Obyèejnì neútoèí na vesnièany|pro nic za nic!
{23194}{23238}Co se dìje?
{23257}{23330}Musí na nì pùsobit|Shabranigodovo znovuzrození!
{23347}{23394}Vypadá to tak.
{23890}{23961}Vıbornì! Dobrá práce!|S vašimi dvìma meèi...
{23962}{24033}...nedokáe udret krok ani|jejich léèivá síla!
{24034}{24105}Hej, jenom se nedívej,|ale také bojuj.
{24109}{24158}Promiò, promiò.|Ach, podívej se, tam jsou další.
{24235}{24277}Pøijïte zas!
{24632}{24674}Co je?
{24682}{24745}I troll dokáe|rozeznat chutné dìvèe.
{24779}{24818}To bolí...
{25311}{25404}Ignorovat Linu Inverse!|Vy teda máte nervy!
{25498}{25594}Take vy obludy si myslíte,|e mùete napadnout dívku!
{25610}{25710}Za vaši neodpustitelnou hrubost|vás znièím všechny do jednoho!
{25793}{25830}Tak...
{25835}{25892}Je mi jedno,s kım|bojuji.
{26141}{26178}Dìkuji vám velmi pìknì.
{27235}{27280}K èertu, stále pøicházejí další.
{27282}{27351}Nebudu tu èekat donekoneèna.
{27353}{27393}Jdu na to!
{27409}{27497}"Temnota pøed úsvitem,|karmín krvavìjší ne tekoucí krev."
{27497}{27529}"Pochovanı v pøílivu èasu..."
{27531}{27616}"...Ve tvém velkém jménu, nech všichni,|co nám stojí v cestì, budou znièení!"
{27642}{27694}Dragon Slave!
{28527}{28606}{Y:i}Musím se pokusit ukonèit|to sám.
{28706}{28818}{Y:i}Kdy zemøu, tak Zolf a Rodimus|na mì èekají na onom svìtì.
{28875}{28938}{Y:i}Nebudu osamìlı...
{29186}{29242}Myslíš si, e se|nás zbavíš?
{29257}{29304}Dohodli jsme se, e|se mu postavíme spoleènì...
{29305}{29350}...take ádná sóla, jasné?
{29376}{29405}Lina...
{29410}{29492}Je ménì bolestivé udìlat to tak,|jako Lina øíká.
{29520}{29546}Je to jasné?
{29592}{29674}My tøi zaútoèíme na Shabranigda|spolu. Rozumíte?
{29727}{29798}{Y:i}Mìli bychom ukonèit|tuto šarádu.
{29898}{29938}Shabranigdo!
{30023}{30072}Nakonec se Shabranigdo|pøeci jen objevil!
{30073}{30142}A zaèíná zápas|o osud svìta.
{30142}{30210}Musíme vyhrát za kadou cenu!
{30232}{30282}Takovı je alespoò náš plán...
