{1}{1}23.976
{328}{383}Tam, kde se vyrojí mostra,|pøicházím, abych je znièila.
{399}{465}Tam kde se zatøpytí poklady,|objevím se, abych se jich zmocnila.
{465}{572}A tam, kde se mi nepøátelé postaví,|tak vítìzství bude mé!
{2612}{2667}Lina Inverse se tu zas.|Zelgadis a já jsme...
{2667}{2723}...vybojovali s Rezovımi|poskoky parádní boj.
{2723}{2799}A to Rezo proti nám|poslal i Monstrum!
{2821}{2884}Ale kdo jinı se to objevil pøímo|uprostøed bojù...
{2912}{2955}...pøeci Gourry, náš dlouho postrádanı,|supertalentovanı šermíø!
{2955}{3001}Kde ho našel nebo získal, nevím...
{3001}{3065}...ale vlastní povìstnı Meè Svìtla,|kterı zamordoval...
{3065}{3128}...velkou bestii Zanaffara, a pøestøihl|to Monstrum na dvì pùlky!
{3128}{3219}Ale nemyslím si, e by|se Rezo vzdal tak snadno.
{3235}{3289}Pøemıšlím, co zkusí pøíštì?
{3312}{3439}POMOC!|Shabranigdovo znovuzrození!
{3949}{3997}...a to pokraèuje dodnes.
{3999}{4045}Ok, moná jsem|nìco pøeskoèila...
{4047}{4115}...ale v podstatì to je|celı pøíbìh.
{4223}{4291}Coe, nerozumíte?|Mám to zopakovat?
{4295}{4358}Uh, ne. Myslím,|e situace je celkem jasná.
{4359}{4421}Ale jen...|Dobrı boe, ty jsi ukecaná!
{4423}{4459}Fakt?
{4503}{4573}Teï, kdy jsme se tu tak sešli,|mohu se na nìco zeptat?
{4575}{4644}Dáš mi u|koneènì Kámen mudrcù?
{4646}{4686}Ani za nic!
{4694}{4757}Bylo by to mrhání|pouít ho jen pro tvou pomstu.
{4759}{4825}- Coe?!|- Chcete teï zaèít bojovat?
{4904}{5006}Máte stejnou šanci na získání|jakou má i Rezo. Co, Lino?
{5009}{5086}Uch-huch. Jasné,|nemùeme jim vìøit.
{5087}{5173}Ale je za tím víc,|ne jen to, e si chce uzdravit oèi.
{5175}{5239}Co vlastnì Rezo|ve skuteènosti chce?
{5271}{5310}Tak u je to pøipravenı.
{5327}{5382}A u se pøipravuju i já!
{5384}{5429}Poøádnì jsme se nenajedli,|o té doby co se tím vším zabıváme.
{5432}{5479}U se mi o tomhle zdálo!
{5494}{5532}Tak tomuhle se øíká|smysl ivota.
{5606}{5647}Dejme se do toho!
{5896}{5939}Jez takhle dál|a narosteš.
{5944}{5982}Ale nemám na mysli|tvé prsa.
{6208}{6316}Ach, jsem plná. Další na øadì je,|pìkná mìkká postel na spaní.
{6318}{6427}Rezo mùe kdykoli zaútoèit!|Nemìla by ses takhle uvolòovat.
{6438}{6484}Tak, mi promiò,|e si chci trochu odpoèinout!
{6593}{6634}Oh, jsi v poøádku?
{6640}{6709}Jsi ok? Mùeš ti ublíit, kdy|vrazíš do nìkoho, jako je ona.
{6712}{6744}Hele!
{6810}{6845}Jsem v poøádku.
{6846}{6939}Oh, dobøe. A dávej pozor,|kam šlapeš!
{6940}{6984}Uh-huh. Promiòte-
{7305}{7344}Co... Co to...?!
{7397}{7432}Kámen!
{7456}{7528}Zmìnil se na kámen!
{7592}{7632}Tam nahoøe!
{7724}{7772}Rezovy èáry!
{8032}{8066}Rezo!
{8176}{8234}Odpuste, e nejsem pøítomen|osobnì, drazí pøátelé.
{8240}{8283}Co chceš,|Rudı Knìzi?!
{8287}{8360}To ti urèitì|nemusím pøipomínat.
{8367}{8399}Kámen Mudrcù.
{8400}{8463}Promiò, ale ten kámen|nedostaneš.
{8465}{8596}Ach, takovı projev nepøátelství.|Vdy ho chci dokonce od vás koupit.
{8604}{8700}Oh? A jakou by mohl mít|cenu Kámen mudrcù?
{8701}{8760}Jakou asi? No...
{8783}{8854}ivoty všech|v této osadì.
{8856}{8898}Stálo by to za to?
{9049}{9069}Coe?!
{9073}{9231}Myslím, e udìlat z nich sochy,|jako tohoto chlapce by bylo docela umìlecké.
{9248}{9292}- Pøeskoèilo ti?!|- To je ohavné!
{9296}{9439}Mùete svobodnì pøijít do mé vìe,|pokus si budete pøát uzavøít se mnou dohodu.
{9441}{9536}Jsem si jistı, e Zelgadis|zná cestu.
{9567}{9589}K èertu!
{9889}{9927}Co teï udìláme, Lino?
{9930}{9999}Budeme muset hrát|podle nìj.
{9999}{10080}Nezastavil by se jen tak.|Kdy nepùjdeme...
{10081}{10141}...pak urèitì zamıšlí zabít|lidi i v ostatních vesnièkách.
{10144}{10191}- Tak...|- Hej...
{10192}{10256}Je to jakoby si vzal|nekoneènı poèet rukojmí.
{10376}{10441}Huh?|Co se s vámi dìje?
{10521}{10578}Nic. Ale nic.
{10586}{10639}U je pozdì.|Radši jdi rovnou domù.
{10641}{10715}Hej! Mìjte se, sleèno!|Bye-bye!
{10744}{10806}Fakt máš v úmyslu|vyjednávat s Rezem?
{10808}{10870}Ach, nevím,|co dìlat.
{10871}{10930}Ale, co se mùe stát,|kdy si s ním jen promluvím?
{10936}{10992}On není z tìch, které|by pøesvìdèili fakta.
{11025}{11073}Tím jsem si jistá.
{11216}{11369}Tak, co teï udìláš?|Lino Inverse...
{12408}{12455}Vyèisti si mysl...
{12456}{12602}Vyèisti si mysl a nic tì|nepøemùe. Vyèisti...
{12881}{12932}Je to tak zmatené.
{13047}{13113}Huch? Ach ano,|úplnì s tím souhlasím...
{13737}{13807}Kdy u ty Rezovo|vìe budeme?
{13808}{13857}Kadou chvíli by jsme ji|mìli zahlédnout.
{13882}{13919}Jak vypadá uvnitø?
{13922}{14016}A k hornímu sálu je to vìtšinou|jen prázdnı prostor.
{14019}{14084}Samotná vì vypadá, jako by|ji postavili u pøed tisíci roky.
{14089}{14135}Pøed tisíci roky...
{14137}{14183}To je pøiblinì tehdy, kdy|se znovuzrodila èást Shabranigda...
{14185}{14229}...ve Válce|Vzkøíšení Pøíšer.
{14233}{14280}No asi tak.
{14281}{14320}Tak, u ji mùete vidìt.
{14394}{14420}To je ona?
{14422}{14480}Ano. To je Rezovo vì.
{14482}{14530}Rezovo vì...
{15414}{15496}Rezo! Jsme tady,|jak sis pøál!
{15498}{15554}Proè se neukáeš?
{15731}{15788}- Rezo!|- Další fantóm, jako pøedtím.
{15793}{15857}Všechny vás tu vítám.
{16026}{16066}Nemáš ádnou dùstojnost?!
{16067}{16182}Promiòte mi tuhle podobu, kterou jsem pøijal,|ale právì jsem trochu zaneprázdnìnı.
{16235}{16279}Pøinesli jsme|Kámen Mudrcù...
{16280}{16338}...ale ráda bych|ti ho pøedala osobnì.
{16340}{16410}- A na nìco se zeptala.|- Souhlasím.
{16412}{16508}Odpuste mi, prosím, ale mùete|vystoupit na vrchol vìe?
{16690}{16730}To bude fuška|tam vylézt.
{16731}{16754}Urèitì.
{16804}{16847}Levitation!
{17035}{17105}Dr se pevnì, Gourry.|Jdeme nahoru!
{17346}{17401}Hej, nemùeme spadnout, ne?
{17404}{17451}Jen kdy se pustíš.
{17508}{17570}Hej! Obtìuj mì|a shodím tì!
{17572}{17643}Neertuj?!|Ani já ne jsem TAKOVİ blbec!
{17688}{17727}Padám!
{17756}{17827}Zachraòte mì! Padám!
{17828}{17912}Pøistáli jsme. To chceš na mnì|viset takhle celı den?
{17915}{17968}- Èervenáš se.|- Sklapni!
{18248}{18270}Rezo!
{18292}{18380}U jsem na vás èekal...|drazí pøátelé.
{18693}{18741}Zdá se, e je tentokrát skuteènı.
{18813}{18867}Kámen mudrcù|je uvnitø.
{18875}{18930}Dáš mi ho koneènì?
{18932}{18986}Oh, to nebude|tak jednoduché.
{18988}{19079}No tak, urèitì si nemyslíš,|e mì tady mùeš porazit.
{19084}{19138}Je pár vìcí, na které|se chci nejdøív zeptat.
{19140}{19254}Odpovìz, jinak tuto vìc|rozbiji na malé kousky!
{19293}{19327}Co to zkoušíš?
{19329}{19427}Nechme u toho.|Co ve skuteènosti chceš?
{19436}{19499}Zelgadis ti to|ještì neøekl?
{19500}{19562}To, ohlednì|vyléèení tvé slepoty?
{19564}{19665}Mohl bych ti to vysvìtlit,|ale neporozumìla bys.
{19666}{19698}Nikdo z vás.
{19701}{19770}I kdyby jsem to pøipustila,|pøesto to jednu vìc nevysvìtluje.
{19772}{19884}Proè jsi mi neøekl pravdu,|pøi tom prvním setkání?!
{19893}{20003}Shabranigdo?! Temnı Pán?!|Vzkøísit ho?!
{20004}{20043}Bez pochyby.
{20045}{20147}Zelgadis je smìsí|èlovìka, golema a démona.
{20149}{20187}Stvoøení èirého zla.
{20188}{20292}Pøeje si oivit|Temného Pána a znièit svìt.
{20298}{20340}Proè by dìlal|nìco tak hloupého?
{20341}{20401}To jsem ještì nezjistil.
{20404}{20506}Ale teï je vaším nepøítelem|stejnì tak jako mım.
{20516}{20563}Zelgadis chce získat|klíè k jeho oivení...
{20565}{20618}...kterı osud vloil|do vašich rukou.
{20620}{20709}Aby ho získal, obklopí|vás nepøáteli.
{20716}{20744}Klíè...
{20746}{20786}Proè ho nedáš mnì?
{20787}{20860}Potom bys mohla bıt ušetøená|od všech tìch problémù.
{20924}{20975}To je a|PØÍLIŠ pøehnané...
{20980}{21074}Dokáeš jich tolik|porazit sám, Zelgadis?
{21076}{21116}Tak moment!
{21124}{21165}Nezapomínáš tu|na nìkoho?
{21195}{21234}Nedovolte jí to dokonèit!
{21236}{21270}Vpøed!
{21425}{21492}A co jsi chtìl...
{21494}{21580}...kdy jsi vyslal Dilgeara|a tu Pøíšeru za námi?
{21598}{21651}Kdyby si opravdu chtìl Kámen...
{21653}{21708}...bylo by rychlejší,|kdybys pøišel osobnì?
{21710}{21773}Anebo jsi mìl|nìco jiného na práci?
{21805}{21876}Existuje nìjakı jinı|dùvod, proè to chceš?
{21877}{21932}Moná, e si opravdu chceš|vyléèit svoje oèi...
{21934}{21980}...ale ta metoda, jakou to chceš|pouít mì znervózòuje.
{21981}{22036}- To snad ne...|- Uch, promiò.
{22045}{22122}Mám v tom momentálnì nìjakı|totální zmatek, tak...
{22125}{22190}No, vydr ještì chvilku!|U se pøibliuji k rozuzlení!
{22205}{22254}Tak tedy,|jaké je tvé rozuzlení?
{22266}{22330}Dohodl jsi se s tou Pøíšerou...
{22331}{22414}Vrátí ti tvùj zrak|zpátky vımìnou...
{22415}{22494}...za vzkøíšení Shabranigda,|Temného Pána z rodu Pøíšer!
{22524}{22557}Správnì?
{22604}{22684}COE?!|Vzkøísit Shabranigda?!
{22685}{22772}Tak proto jsi nám nemohl|povìdìt pravdu...
{22773}{22847}...a proto jsi musel strávit|tolik èasu pøípravami.
{22853}{22882}Nevìøím tomu!
{22892}{22947}Kdo by si to myslel?!
{22950}{23026}Dobrá práce! Brilantní|ukáka dedukce!
{23027}{23075}Abych tak øekl.
{23077}{23185}Je to pøesnì tak,|jak pøedpokládáš.
{23213}{23336}Vzkøíšení Shabranigda|je lékem na mou slepotu.
{23338}{23362}To je šílené!
{23364}{23443}Znièil bys svìt jen kvùli|vlastnímu prospìchu?!
{23453}{23521}Kdy síla èlovìka nestaèí,|je nutné se obrátit...
{23522}{23588}...buï na silu|Bohù anebo Pøíšer.
{23589}{23643}Moc Temného Pána|je ze všech nejsilnìjší.
{23645}{23741}A vìøím, e místem, kde je Shabranigdo|uzavøenı, je tahle vì!
{23756}{23794}Ty jsi šílenı?!
{23796}{23843}{Y:i}Oh, ne...
{23845}{23899}{Y:i}Opravdu jsem nemyslela vánì,|co jsem øekla.
{23900}{23939}{Y:i}Fakt jsem ani neoèekávala,|e to bude pravda!
{23941}{23987}{Y:i}Wow, ivot je obèas pøíliš|tajemnı na pochopení...
{23991}{24112}Uch, kadopádnì, teï, kdy to víme,|nemùeme ti ten Kámen dát!
{24156}{24222}No, podívejme se, co se stane.
{24229}{24293}Rozdrtím tuhle vìc,|hned a naráz!
{24373}{24477}"ivot zrozenı z nejtvrdšího kamene,|zformovanı ze slabého masa."
{24495}{24629}"Nech tì kouzlo osvobodí|a navrátí tì do tvého domova."
{24648}{24729}"Sjedno se s mou vùlí,|a buï mùj."
{24742}{24827}Teï tancuj, moje oddaná panenko!
{25038}{25081}Kámen Mudrcù!
{25093}{25144}- Zelgadis!|- Je pod Rezovou kontrolou!
{25152}{25225}A teï, buï tak milı|a pohraj si s tìmito lidmi.
{25501}{25523}Rezo?!
{25525}{25573}Chystá se|vzkøísit Shabranigda!
{25663}{25713}- Zelgadisi!|- Pane Zelgadisi!
{25783}{25842}Získej mi èas, kterı potøebuji.
{26142}{26225}Skuteènı Kámen mudrcù!|S ním...
{26582}{26642}Pane Zelgadisi!|Proberte se!
{26653}{26693}Kruci, tohle všechno|nás zdruje-
{26696}{26748}- Nech to na mnì!|- Co chceš udìlat?
{26750}{26819}Nemáme moc èasu.|Vyøeším to jednou ranou!
{26821}{26870}Chystáš se pouit|magickı útok?!
{26917}{26950}Diem Wing!
{27047}{27102}Vzbuï se!
{27221}{27258}Co se stalo?
{27263}{27302}A ještì jednou!
{27328}{27380}Hej! Myslel jsem si,|e u je normální!
{27383}{27422}Pane Zelgadisi!
{27437}{27500}- Co se to se mnou stalo?|- Byl jsi pod Rezovou kontrolou.
{27502}{27573}Zøejmì tì naprogramoval,|kdy vytváøel tvé nové tìlo...
{27575}{27654}...tak, aby si byl jistı,|e vyplníš jeho rozkazy.
{27733}{27748}Sakra!
{27755}{27847}Na to není èas!|Kdy nezastavíme Reza...
{28223}{28282}Obrovskı magickı kruh!
{28367}{28398}Shabranigdo!
{28422}{28470}Èas tvého|znovuzrození nadešel!
{28589}{28605}Co to...?!
{28615}{28682}- Neuspìl?|- Ne! Nemohl!
{28684}{28732}Ta moc je tu|stále silnìjší!
{28735}{28766}Coe?!
{28909}{28956}Pøišli jsme pøíliš pozdì?!
{29183}{29222}Mılil se!
{29271}{29326}Koneènì!|Koneènì jsem to dokázal!
{29527}{29620}Tahle vì není místem,|kde je Shabranigdo uzavøenı.
{29623}{29692}Je jen místem|pro obøad!
{29696}{29781}Temnı Pán... Temnı Pán|je uzavøenı v Rezovıch vlastních oèích!
{29879}{29950}Zrození Temného Pána|nadchází!
