{1}{1}23.976
{324}{382}Tam kde se vyrojí monstra,|objevím se, abych je znièila!
{397}{464}Tam, kde se zatøpytí poklady,|pøicházím, abych se jich zmocnila.
{464}{571}A tam, kde se mi nepøátelé|postaví, tam vítìzství bude mé!
{2760}{2812}Temnı Pán, Shabranigdo...
{2812}{2888}...zakletı uvnitø Reza,|se znovu narodil!
{2986}{3057}Imunní proti nejsilnìjším|kouzlùm...
{3057}{3128}...s mocí, která mùe znièit svìt!
{3222}{3303}Máme vùbec nìjakou šanci|proti tak mocnému Temnému Pánovi?!
{3344}{3413}Èas pro rozhodující boj|právì nastává!
{3481}{3617}JACKPOT!|Velká hra na ivot a na smrt!
{3752}{3808}-Tak ses ukázal!|-Temnı Pán...
{3808}{3842}Shabranigdo!
{4286}{4367}Take nakonec pøeci jen|stojíte pøed mou tváøí!
{4396}{4506}Ano. A budeš litovat,|e ses s námi zapletl!
{4548}{4654}Jak jen vy lidé dokáete bıt hloupí.
{4683}{4703}Coe?!
{4703}{4765}Pokud se stanete mımi sluhy...
{4765}{4827}...zaruèím vám|dlouhı ivot.
{4827}{4887}Pouštìt se do beznadìjného boje...
{4887}{4956}To je vrchol hlouposti!
{4988}{5008}Pøestaò!
{5018}{5126}Ten mág Zolf a staøec,|kterı zemøel s ním, byli hlupáci.
{5126}{5205}Ale v porovnaní s nimi|jste o hodnì hloupìjší!
{5219}{5254}Jak se odvauješ!
{5426}{5473}Zolf... Rodimus...
{5538}{5580}Øíkat, e byli hlupáky?!
{5580}{5651}Ty obludo! Takhle se|díváš na lidské ivoty?!
{5651}{5711}Budeš litovat, e|jsi tohle øekl!
{5738}{5837}Vaše vlastní smrt bude|vrcholnım dùkazem vaší hlouposti!
{5924}{5967}Kdo je tady hlupák...
{6154}{6196}...to se hned uvidí!
{6562}{6583}K èertu!
{6617}{6673}Kdo se stará o to, zda|to funguje nebo ne!
{6673}{6712}Gaav...
{6823}{6855}...Flare!
{7056}{7111}Och, ono to opravdu nefunguje?
{7156}{7199}Myslím, e tohle je tvoje.
{7488}{7537}Co se dìje, Lino?!
{7556}{7601}Jen zkouším, zda to|funguje anebo ne!
{7668}{7759}"Nekoneèná zemì, matko,|vychovávající vše ivé."
{7759}{7805}"Dovol a tvá síla|vplyne do mıch rukou!"
{7864}{7913}Vlave Howl!
{8598}{8629}Dokázali jsme to?
{8697}{8721}Ne!
{9503}{9532}To není dobré!
{9532}{9690}Zábavnı trik...|Ale láva se pouívá takhle.
{9989}{10010}Jdìte!
{10405}{10439}Tohle bude trvat vìènost!
{10483}{10538}Tak to vyøeším|jednou ranou.
{10538}{10580}Van Rehl!
{10895}{10944}Skvìlé!|Pokraèuj, Zele!
{10976}{10997}Co!
{11097}{11121}Zele!
{11272}{11305}Jdeme na to, Gourry!
{11371}{11411}Freeze...
{11498}{11530}...Arrow!
{11655}{11705}A teï, Ray Wing!
{12007}{12033}A znovu!
{12108}{12186}Fireball!
{12275}{12356}Stále nechápete,|e je to zbyteèné?
{12376}{12420}Teï! Kupøedu, Gourry!
{12459}{12498}Uka se, Svìtlo!
{12568}{12614}Teï jsem na øadì já!
{12927}{12972}To... To není moné!
{12972}{13047}Oh, ne! Meè|Svìtla to nedokáe?!
{13047}{13174}Meè Svìtla, kterı zabil|legendárního netvora Zanaffara...
{13174}{13256}Mnì ale neporazí!
{13378}{13401}Gourry!
{13459}{13551}Nekøiè tolik, Lino.|Ještì ne jsem mrtvı!
{13551}{13592}Ani já!
{13636}{13675}Ještì dokái bojovat!
{13690}{13727}Zele! Gourry!
{13728}{13787}Ještì se dokáete hıbat?
{13978}{14089}Lahodné vıkøiky. Pøesnì|takové, jaké jsem chtìl slyšet.
{14116}{14135}Co to má znamenat?!
{14142}{14191}Moc Monster plyne z...
{14191}{14239}...negativních emocí|v lidském srdci.
{14239}{14315}Hrùza, hnìv,|smutek, beznadìj...
{14315}{14391}Všechno to se stává mou silou.
{14421}{14444}To je...
{14451}{14575}Tisíce a tisíce let|iji v lidskıch duších.
{14575}{14622}Rodím se znovu a znovu.
{14622}{14695}Nakonec jsem našel|tohoto mue, Reza...
{14695}{14767}...jeho tìlo je|pro mnì nejvhodnìjší.
{14767}{14847}Teï musím nashromádit|co nejvíc síly.
{14847}{14931}A na to je nejlepší strach,|kterı najdu...
{14931}{15016}...v lidskıch duších|plnıch takové energie.
{15133}{15222}Chci slyšet vaše vıkøiky!|Nech se stanou mou silou!
{15222}{15293}A s touhle silou brzy|znièím svìt...
{15293}{15364}...a vrátím ho zpìt|do moøe chaosu!
{15365}{15437}Take... Take to je|cílem Monster!
{15452}{15530}Zpùsobím vám to,|po èem touím...
{15530}{15578}Hrùzu a bolest!
{15816}{15843}Je konec.
{15899}{15949}"Hojivá sílo, záøící svìtlo..."
{15982}{16097}Léèivé kouzlo u|nebudeš potøebovat.
{16191}{16217}Lino!
{16417}{16453}Meè Svìtla...
{16645}{16694}-Gourry!|-Pouij ho, Lino!
{16724}{16786}To se ti lehko øekne...
{16865}{16903}Ach, tady je.
{16962}{17018}Poslední zoufalé pokusy.
{17184}{17207}Elmekia...
{17254}{17293}...Lance!
{17499}{17598}To byla Elmekia Lance!|Taková síla!
{17645}{17700}Stále to odmítáte pochopit.
{17700}{17785}Magie vaší úrovnì|na mì neúèinkuje!
{17806}{17839}Je tohle konec?
{18120}{18149}{Y:i}Co mám dìlat?!
{18198}{18245}{Y:i}Co mám dìlat?!|Co mám dìlat?!
{18268}{18367}{Y:i}Poslední šance! Ještì mám jedno|kouzlo. Jene...
{18380}{18473}Nebojte se. Nebudete sami,|kdo zemøe.
{18473}{18566}Zanedlouho vás bude následovat|celı svìt!
{18586}{18619}Pøestaò!
{18637}{18718}Dost! Opravdu chceš|znièit celı svìt...
{18718}{18773}...kterı jsi touil tolik vidìt?!
{18788}{18808}Rezo!
{18962}{18991}REZO!
{19023}{19137}Pøestal. Ale proè?|Co se stalo?
{19267}{19346}{Y:i}Rezova duše... Ještì|ji úplnì nepohltil!
{19346}{19394}{Y:i}Take ještì máme šanci!
{19448}{19477}Dobøe!
{19477}{19546}Kdy se tohle nepodaøí,|vzdám to.
{19568}{19591}Lino?
{19591}{19677}I kdyby jsi pouila|kouzlo silné jako Dragon Slave...
{19677}{19762}...nemùeš porazit mne,|Temného Pána Shabranigda!
{19778}{19838}Nezáleí na tom, jak jsi silnı...
{19838}{19934}...kdy pouiji kouzlo|mnohem silnìjšího Pána...
{19934}{19972}Zemøeš!
{19972}{20010}Coe?!
{20028}{20115}Víš, znám kouzlo ještì|silnìjšího legendárního Temného Pána,
{20115}{20169}Sílu Pána Hrùz!
{20219}{20325}Kouzlo, které vyuívá sílu Pána|mocnìjšího ne Shabranigdo?
{20325}{20374}JE to v lidskıch silách?!
{20374}{20439}Pokud to nìkdo dokáe, tak je to ona!
{20494}{20557}Meè Svìtla, kterı|promìòuje vùli svého pána...
{20558}{20621}...na sílu. A kouzlo|legendárního Temného Pána.
{20631}{20676}Teï ti to ukáu.
{20676}{20725}Nejtajnìjší z mıch tajemství!
{20725}{20788}Giga Slave!
{20864}{20926}Meèi, dej mi svou sílu...
{21142}{21241}"Temnota èernìjší ne uhel,|hlubší ne nejhlubší noc!"
{21259}{21350}"Král Temnot, obklopenı|zlatou záøí nad Oceánem Chaosu."
{21401}{21458}Jedno uklouznutí a|pohltí mì temnota.
{21537}{21584}Otravnı hmyze!
{21592}{21701}"Volám tì!|Zapøísahávám se tebou!"
{21701}{21797}"A blázny, kteøí|se mi postaví, znièí..."
{21797}{21891}"...síla, kterou|spoleènì vládneme!"
{21922}{22016}Meèi! Pøijmi temnotu|a poslechni mùj rozkaz!
{22307}{22363}Rezo, Rudı Knìzi!|Teï si musíš vybrat!
{22376}{22445}Dovolíš, aby tvou duši|pohltil Shabranigdo?!
{22445}{22513}Nebo obrátíš svou pomstu|proti nìmu samému?!
{22513}{22583}Ty...|Ty smìšná hlupaèko!
{22583}{22642}Uvidíme, kdo z nás dvou|je hlupák!
{22658}{22719}GIGA SLAVE!
{23163}{23193}{Y:i}Temnı Pane...
{23584}{23629}Nevmìšuj se!
{23629}{23746}Ne. Musíš bıt znièenı.
{23746}{23800}NEVMÌŠUJ SE!
{24784}{24882}Odvánı pokus.|Ty, obyèejnı èlovìk...
{24960}{25057}Dokázala jsi porazit|Temného Pána Shabranigda...
{25100}{25223}Poskytl jsem tobì a Rezovi|èest zabít mì...
{25223}{25307}Bylo to zábavné...
{25379}{25399}Dokázala to?
{25399}{25456}Shabranigdo u neexistuje.
{25813}{25859}Opravdu jsme ho porazili...
{26024}{26061}Dokázalas to.
{26073}{26118}Hele...
{26130}{26179}Lino, tvoje vlasy...?!
{26192}{26272}To je v poøádku. Jen jsem se|trochu vyèerpala.
{26284}{26315}{Y:i}Dìkuji ti.
{26349}{26383}{Y:i}Omlouvám se...
{26744}{26817}Ale jak jsi|porazila Temného Pána?
{26829}{26850}To nic nebylo.
{26866}{26934}Znamená to, e jsi|silnìjší, jako byl on?
{26946}{27026}Oh, pøestaneš u koneènì?!|Mìla jsem šanci asi jako snìhová vloèka v pekle.
{27034}{27117}Vyhrála jsem jen díky|Meèi Svìtla a Rezovo pomoci.
{27126}{27154}Co tím myslíš?
{27163}{27304}Poslední zbytky Rezovo duše|udreli Shabranigda na uzdì.
{27304}{27361}Chápu... Take Rezo...
{27361}{27487}Take se dá øíct, e|jsem porazila jeho jednu tøetinu.
{27529}{27650}Moná, e znovuoivení Shabranigda a|promìna Zelgadise na Chiméru...
{27650}{27704}...nebyli èiny skuteèného Reza.
{27727}{27808}Pokud byl Shabranigdo v Rezovi|uvìznìnı tak dlouho...
{27808}{27927}...mohl ho kontrolovat|u dávno pøedtím.
{27927}{27980}Chceš, abych tomu vìøil?
{27995}{28093}Pokud by tomu tak nebylo, nemyslím,|e by mi Rezo pomohl.
{28093}{28159}A zda u tomu vìøíš èi ne,|to je tvoje vìc.
{28218}{28277}Hej, a u je to jakkoliv,|odvedla jsi skvìlou práci.
{28277}{28327}Zase se mnou zacházíš|jako s dìckem?!
{28327}{28361}A ne snad?
{28497}{28549}Hej! U vidím Atlas City!
{28549}{28612}To je to mìsto,|kam jsi chtìla jít?
{28612}{28675}Øíkal jsi, e mì doprovodíš|jen sem.
{28703}{28730}Hele? To jsem øíkal?
{28730}{28781}Úplnì na to zapomnìl,|jako obvykle!
{28781}{28867}Take...|Kam odsud pùjdeme?
{28889}{28948}Gourry!|Doufám, e jsi nezapomnìl...
{28948}{29009}...es mi slíbil|Meè Svìtla?
{29009}{29057}Kdy jsem TOHLE øekl?!
{29084}{29110}Take mi ho nedáš?
{29111}{29137}Samozøejmì, e ne!
{29137}{29213}No dobøe, tak u vím,|kam dál pùjdu.
{29213}{29256}Kam?
{29256}{29314}Tam, kam TY!
{29314}{29378}Nalepím se na tebe, dokud...
{29378}{29444}...se koneènì nerozhodneš|dát mi Meè Svìtla!
{29460}{29489}Ach, ty...
{29519}{29573}Take, se tady musíme rozlouèit.
{29573}{29671}Pro mue jako jsem já, by to v tak|velkém mìstì bylo nebezpeèné.
{29687}{29712}Zele...
{29916}{29954}Hej, poèkej! Zele!
{30040}{30079}Tak jak?
{30118}{30151}No pojïme!
{30182}{30252}A vypadá to tak, e|moje cesta s Gourrym...
{30252}{30285}...bude pokraèovat.
{30285}{30357}Take, uvidíme, jak|se to vyvrbí!
