{1}{1}23.976
{319}{383}Tam, kde se vyrojí monstra,|objevím se, abych je znièila.
{383}{466}Tam, kde se zatøpytí poklady,|objevím se, abych se jich zmocnila.
{466}{573}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2638}{2700}Bylo, nebylo,|v jednom mìstì...
{2700}{2779}...dívka jménem Lina Inverse,|vedené rukou osudu...
{2779}{2861}...potkala korunního prince|Philionela z rodu Seyruunovcù.
{2861}{2943}Nikdy bych si nepomyslela, e|rozdíl mezi oèekáváním...
{2960}{3009}...a realitou mùe|bıt tak tvrdı.
{3009}{3051}Dìs a hrùza...
{3051}{3139}A ke všemu jsem se zapletla|do rodinnıch problémù Seyruunovcù.
{3139}{3210}A vìci se nám tak|trochu vymkli z rukou.
{3210}{3303}Philova bláznivá dcera, Amélie,|která mu není vùbec podobná...
{3303}{3395}...se k nám pøipojila, spolu|jsme se pustili do zlotøilcù...
{3395}{3479}...a rozbili jsme|jejich ïábelské ambice.
{3617}{3685}A tak teï, kdy se k nám|pøidal Phil a Amélie...
{3685}{3757}...jsme zmìnili cíl naší|cesty na Seyruun.
{3757}{3833}Kdo ví, co se nám|ještì pøihodí!
{3854}{3981}ROZKOŠNÁ!|Améliin trénink magie!
{4033}{4100}Ach, jsem vyèerpaná...
{4100}{4169}Jdeme a jdeme a|tahle cesta nemá konce!
{4169}{4227}Kde je, k èertu, TEN Seyruun?
{4248}{4315}Neboj se. Se srdcem plnım|lásky a spravedlivosti...
{4315}{4362}..není ten vılet do Seyruunu|vùbec dlouhı!
{4391}{4435}No to urèitì...
{4514}{4593}Zmiz mi z oèí,|nebo z tebe bude kebab!
{4593}{4725}Podle téhle mapy,|by nedaleko mìlo bıt mìsto.
{4750}{4806}Mìsto?!|Kde? Kde? Kde?
{4806}{4895}Jídlo! Koupel! Mìkké postele!
{4895}{4937}Banditi!
{4938}{4980}Banditi?
{5063}{5118}Ale, ne!|Tohle nevypadá dobøe, sleèno Lino.
{5118}{5169}Vıbornì!|U mì zaèínali svrbìt dla...
{5201}{5226}A... Amélie?!
{5325}{5369}Jít po opuštìné cestì|je jako køièet...
{5382}{5438}..."Prosím, pojïte sem a|zabijte mì!"
{5447}{5479}Neber si to osobnì!
{5486}{5510}Poèkej!
{6066}{6093}No dobøe!
{6109}{6179}Zloduchové, co parazitujete|na slabších!
{6185}{6245}Ani nebesa se nad|vámi neslitují!
{6257}{6281}Co k èertu...?
{6302}{6355}Spravedlivost s vámi|zúètuje!
{6553}{6608}Ale ne! Nechtìla jsem|dopadnout sem!
{6644}{6683}Ach, jste v poøádku?
{6723}{6790}Aha, je to rozená vítìzka!
{6796}{6883}Odnauèíme ji plést se|nám do cesty?
{6937}{6983}Dobøe. Dobøe. To staèí!
{6983}{7058}Co je to s tebou?
{7066}{7111}Kdo, k èertu, jsi ty?!
{7111}{7168}Podívej se, pøíteli. Dr|své pazoury dál.
{7188}{7218}Jinak...
{7257}{7303}Bych tì mohla praštit.
{7304}{7350}U sis praštila...
{7455}{7487}Je docela dobrá!
{7487}{7525}Jen tak dál, sleèno Lino!
{7525}{7573}Coe?! LINA?!
{7639}{7713}Vìk, pøiblinì 15 nebo 16...
{7724}{7792}Ostrı jazyk, rychlé ruce,|obleèená jako èarodìjka...
{7792}{7833}Prsa, prakticky ádná...
{7881}{7975}To je ona, pøesnì!|Lina Zabíjeèka Banditù!
{7982}{8049}Pøirozenı nepøítel|všech ivıch?! TA Lina?!
{8049}{8140}Bìte! Zachraòme si holé ivoty!
{8140}{8253}Idioti! Myslíte si, e vás nechám|utéct po tom, co jste øíkali?!
{8261}{8316}U se to nese!
{8316}{8371}DRAGON SLAVE!
{8712}{8746}Vítìzství!
{8777}{8804}Ty...
{8852}{8902}To bylo úasné!
{9229}{9295}Uch, jsem unavená a hladová!
{9309}{9392}Vrchní, je mi jedno, co to bude,|ale doneste hodnì jídla!
{9573}{9632}Co se dìje, Amélie?|Nìjakı problém?
{9647}{9755}Sleèno Lino, nevìdìla jsem...|e jste tak slavná!
{9767}{9811}Jste opravdová bojovnice|proti zlu!
{9849}{9925}Respektuji vás, protoe|bojujete pro spravedlnost!
{9952}{10043}No, ono to tak|DOCELA není, víš...
{10050}{10115}Vùbec to tak není...
{10127}{10197}Rozhodla jsem se!|Pùjdu s vámi a stanu se...
{10197}{10267}...neporazitelnım|ochráncem spravedlnosti!
{10286}{10392}Mohla byste mì, kvùli tomu,|nauèit váš Dragon Slave?
{10426}{10462}COE?!
{10497}{10526}Poèkej! Poèkej chvíli!
{10533}{10592}Víš vùbec, co za|kouzlo je Dragon Slave?!
{10601}{10666}Jasnì! Kouzlo na|potrestání zloduchù!
{10729}{10850}{Y:i}Další pøíklad její schopnosti|vùbec nic nepochopit!
{10883}{10966}Nebojte se, jsem pøipravená|na jakkoli tvrdı trénink!
{10966}{11011}Vynikající, dceruška!
{11011}{11093}Pøipravená obìtovat své|tìlo na oltáø spravedlnosti!
{11093}{11144}To je moje holèièka!
{11144}{11195}- Otèe!|- Dcero!
{11299}{11356}Take, dohodnuto,|sleèno Lino?
{11410}{11464}{Y:i}Co je to s TÌMI dvìma...?
{11848}{11938}Pochopila jsi to? Cesta|spravedlivosti je tvrdá a pøísná!
{11955}{12073}Jene... Jene! Kdy na ni|jednou vstoupíš...
{12073}{12165}...musíš následovat|duch spravedlnosti a do konce!
{12262}{12317}POÏME NA TO!
{12335}{12433}Tak proè ji mám nauèit|Dragon Slave?
{12433}{12505}Hele, Lina. Doufám, e ji|opravdu nechceš nauèit...
{12505}{12554}...nìco tak nebezpeèného|jako je tohle, ne?
{12554}{12669}To víš, e ne! U jen proto,|e Amélie se specializuje na bílou magii.
{12669}{12749}Nemùu ji jen tak nauèit|nejnièivìjší kouzlo èerné magie!
{12749}{12824}Uch, bílá magie...?
{12829}{12930}Magie knìí, pouívaná|na léèení nebo vymítání duchù.
{12930}{12983}Èerná magie zahrnuje|útoèná kouzla a tak.
{12983}{13050}Je to úplnì o nìèem|jiném! Rozumíš?
{13050}{13124}No, já... Ne, ne celkem...
{13124}{13213}A co myslíš, e udìlá|sleèna "Spravedlnost Nadevše"...
{13213}{13293}...ve chvíli, kdy se|nauèí Dragon Slave?!
{13422}{13470}Aha! Našel jsem minci!
{13515}{13575}To je kráde!|Krást je zlé!
{13575}{13651}Stihne tì mùj spolehlivı,|rychlı trest! Dragon Slave!
{13732}{13820}Oh, je to vynikající pocit|triumfovat ve jménu spravedlnosti!
{13820}{13849}To je ono, dìvèe mé!
{13849}{13900}Jen tak dál a|spravedlnost zvítìzí!
{13900}{13950}Ano, otèe!
{14002}{14071}Hmm... to je trochu dìsivé...
{14071}{14155}Vidíš? A to u je|na to celá nahavená.
{14158}{14195}Co mám dìlat?
{14196}{14233}Sleèno Lino!
{14293}{14352}Prosím, zaènìme hned s vıukou!
{14475}{14563}V poøádku, pøiprav se|na opravdovı trénink!
{14563}{14587}Dobøe!
{14593}{14630}Poèkej!
{14698}{14741}Nejdøív udìlej 5000 døepù!
{14741}{14774}Ano!
{14839}{14884}Lino...
{14884}{14963}Nic, co øeknu,|nezastaví Amélii.
{14963}{15028}Take jí ukái|svùj "speciální trénink."
{15047}{15107}Musíme jen poèkat,|dokud to nevzdá.
{15217}{15267}Nikdy se nevzdám!
{15468}{15519}A je trénink jakkoli|tvrdı...
{15561}{15605}Stanu se...
{15775}{15909}...velkou ochránkyní spravedlnosti,|tak jako sleèna Lina!
{16150}{16213}Trénuješ u tøi dni...
{16213}{16276}Máš u trochu potuchy...
{16276}{16344}...jak vykouzlit Dragon Slave?
{16344}{16395}Ne... Zatím ne...
{16395}{16572}Stále...jsem...ještì...|dobøe...nepochopila...základy...
{16616}{16684}Kupuješ jí jídlo,|vaøíš pro ni...
{16684}{16752}Nìco se mi na tom|tréninku nezdá.
{16752}{16801}Nech toho, pomùu ti.
{16801}{16861}Oh, ne! Ne! To je|èást mého tréninku!
{16861}{16915}Nevmìšuj se do toho!
{17241}{17269}Jste v poøádku, babièko?
{17330}{17356}Ano...
{17364}{17440}Pro starou enu to musí|bıt tìké, jít do takového kopce.
{17440}{17510}Proè jej neobejdete?
{17547}{17608}No chápu, co myslíš.
{17608}{17737}Ale obejít horu|trvá celı den!
{17772}{17851}Dostat se na druhou stranu mìsta...
{17851}{17926}...je takhle namáhavìjší,|ale o hodnì rychlejší!
{17938}{17975}Chápu...
{17975}{18048}Bez té hory by|to asi bylo lehèí...
{18083}{18185}Mìla by jsem co?! Proè bych|mìla nìco takového udìlat?!
{18194}{18250}Hora uprostøed mìsta...
{18250}{18306}...pøináší kadodenní trápení|všem lidem...
{18307}{18363}...kteøí se chtìjí dostat|na druhou stranu...
{18363}{18428}U jen proto...|U jen proto...
{18501}{18552}Právì proto!
{18552}{18620}Pro všechen èas, kterı|to lidem ušetøí!
{18620}{18729}Pro všechny lidi,|kteøí nemají sil na vıstup!
{18741}{18816}No tak, není to a TAK zlé.
{18822}{18890}Nemùeš ignorovat utrpení,|které to lidem pøináší!
{18893}{18943}No dobøe...
{18957}{19018}Take to musíš udìlat!
{19018}{19087}Pouij tu svou Dragon vìcièku!
{19093}{19135}Odstraò tu proklatou horu...
{19135}{19206}...a ušetøi tak lidem|jejich kadodenní trápení!
{19245}{19286}Dragon Slave...?
{19382}{19429}Aha, u to chápu jasnì.
{19462}{19561}Jen ty mùeš odstranit|takové hrozné bøemeno!
{19627}{19695}- No dobøe.|- Vıbornì!
{19790}{19830}Jdu na to!
{19867}{19968}{Y:i}Temnota pøed úsvitem,|karmín èervenìjší ne tekoucí krev.
{19988}{20037}{Y:i}Pochovanı v pøílivu èasu...
{20037}{20119}{Y:i}Ve tvém velkém jménu,|zapøísahám se silám temnot!
{20119}{20238}{Y:i}Všichni blázni, kteøí se nám|postaví do cesty, budou znièení...
{20238}{20332}{Y:i}...silou, kterou|spoleènì vládneme!
{20362}{20415}DRAGON SLAVE!
{21064}{21107}To bylo fantastické!
{21129}{21184}U si zjistila, jak to funguje?!
{21294}{21332}Co jste to udìlali?!
{21332}{21404}Dávno, pradávno, mocnı knìz|zaklel zlé duchy...
{21404}{21468}...do svatynì na vrcholu|hory.
{21486}{21538}Proè jste to udìlali?!
{21572}{21640}No, víte...
{21640}{21727}Zaèínám si myslet, e|to moná ani nebyl tak dobrı nápad.
{21942}{22025}Co je to...?|Co se to dìje?
{22025}{22073}Doufám e ne...
{22314}{22365}Ale ano, u pøicházejí!
{22644}{22671}Elmekia Lance!
{22965}{23000}Oh, tohle potrvá vìènost!
{23007}{23055}Tohle tì odnauèí|dìlat bez pøemıšlení!
{23056}{23104}Vdy jsi se ani nepokusil|zastavit mì!
{23167}{23217}Co si myslíš, e|co dìláš, ty...!
{23288}{23320}Co dìláte, sleèno Lino?
{23329}{23369}Mìla byste pouít|svùj Dragon Slave!
{23369}{23471}Teï mì poslouchej! Kdy bych teï|pouila Dragon Slave...
{23471}{23551}...spálila bych celé mìsto na uhel!
{23579}{23629}Nejsilnìjší kouzlo|ti je nanic...
{23630}{23680}...kdy nevíš,|kde a kdy ho pouít!
{23839}{23910}A ty vdycky jeèíš jen|"Dragon Slave! Dragon Slave!"
{23919}{23945}Je to jako...
{24002}{24043}Jako...
{24130}{24162}Lino, co se dìje?
{24162}{24194}Je to jako...
{24194}{24272}Jako kdyby jste si všichni|mysleli, e jsem blbá!
{24272}{24359}Proè jsou na mnì všichni|tak hnusní?!
{24372}{24454}Jste hnusní!|Nechte mì na pokoji!
{24454}{24544}No super. Posedl ji|nìjakı støelenı duch.
{24544}{24583}Lina, zbav se ho!
{24635}{24680}Nìjakı problém, chlape?
{24687}{24744}Nemluv se MNOU jak|rovnı s rovnım, kámoši!
{24744}{24845}Co si myslíš, e|jsi? Co?
{24900}{24999}Amélie, tohle je tvoje|parketa.
{25006}{25038}Mùeš nìco udìlat?
{25051}{25116}Nedokáu jich sama|zvládnout tolik najednou!
{25133}{25196}Bez nìjakého|magického zesilovaèe...
{25331}{25420}Och, takovı chlap.|Jsi pøesnì mùj typ.
{25444}{25490}Mám ráda velké a natvrdlé...
{25505}{25551}Doufám, e to mluví ten duch!
{25558}{25609}Amélie, udìlej nìco!
{25609}{25659}Rozumíte všichni?
{25659}{25759}Všichni lidé by mìli klidnì|pøijmout skuteènost, e jednoho dne umøou.
{25768}{25819}I kdyby se vám nepodaøilo|dosáhnout všeho, co jste chtìli...
{25829}{25861}Otèe, potøebuji trochu pomoct!
{25975}{26013}Mám snad zaèít|znovu?
{26026}{26099}Poslouchejte mì! Skuteènı|smysl ivota je...
{26323}{26428}Poutací Kámen.|Pokud mají legendy pravdu...
{26482}{26586}{Y:i}Vy, co nejste z tohoto svìta.|Ubohá, pokøivená stvoøení.
{26586}{26637}{Y:i}Svìtlem Èistoty,|kterım vládnu...
{26637}{26740}{Y:i}...vás vyzıvám, vrate se|za hranici našeho svìta!
{26790}{26825}{Y:i}Musíš to dokázat, Amélie!
{26825}{26888}Megiddo Flare!
{28268}{28286}Co se...?!
{28343}{28379}Zlí duchové jsou pryè!
{28452}{28493}Co si myslíš, e dìláš?!
{28752}{28793}Vítìzství!
{28923}{29001}Amélie, celı ten cirkus|byl kvùli tobì!
{29018}{29136}Hlavnì, e je to u v poøádku.|Všichni jsme se dnes nìco nauèili.
{29136}{29195}Ty si ten poslední, kdo|TO mùe tvrdit!
{29203}{29247}Tak, a co teï, Amélie?
{29251}{29338}Neøíkej, e se ještì stále|chceš nauèit Dragon Slave.
{29347}{29443}Ne, nauèili jste mì nìco hodnì|dùleitìjšího, sleèno Lino.
{29481}{29549}Kadé mocné kouzlo, které se|nauèím, mi bude nanic...
{29549}{29596}...kdy nevím, kde a kdy ho pouít.
{29596}{29694}To je dùvod, proè|jste mì nenauèila Dragon Slave!
{29702}{29749}Jste tak moudrá, sleèno Lino!
{29815}{29867}Take, konec dobrı,|všechno dobré, co?
{29935}{29956}Kdy myslíš...
{30026}{30130}Oh, sakra, jako dlouho bude|trvat celı tenhle cirkus?
{30139}{30194}Kdy se koneènì dostaneme|do Seyruunu?!
