{1}{1}23.976
{329}{384}Tam, kde se vyrojí monstra,|pøicházím, abych je znièila.
{402}{468}Tam, kde se zatøpytí poklady,|objevím se, abych se jich zmocnila.
{468}{577}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2583}{2662}Prošli jsme dlouhou cestu|nespravedlivì obvinìnıch uteèencù...
{2662}{2716}...a náš cíl, Sairaag je koneènì pøed námi.
{2716}{2805}Šastnì jsme vyklouzli z nástrah|proradného Zanguluse a Vrumuguna...
{2810}{2868}...a jeden mu dokonce Gourrymu...
{2868}{2927}...maskovanému jako veselé|dìvèe, uèinil návrh!
{2950}{3032}No, dost vısmìchu|tomu ubohému mui.
{3032}{3113}Koneènì jsme se dostali do Sairaagu!
{3113}{3191}A teï uvidíme, co nás tam èeká!
{3206}{3344}NÁVRAT!|Rudı Knìz je zpìt!
{3651}{3769}Uch... To je Flagoon, ten proslulı|posvátnı strom Sairaagu?
{3785}{3842}Øíká se, e kdysi dávno,|kdy Rytíø Svìtla...
{3845}{3907}...zabil tady v Sairaagu,|ïábelské monstrum Zanaffara, ...
{3910}{3994}...jeho tìlo zaèalo vyluèovat|krev obsahující nekoneèné zlo...
{3997}{4042}...která zneèistila|všechno kolem.
{4044}{4160}A aby se tato krev vsákla|a proèistila se, tak Rytíø Svìtla...
{4163}{4229}...zasadil semínko|posvátného stromu.
{4233}{4341}A z toho semínka vyrostl|posvátnı strom, Flagoon.
{4358}{4391}No teda...
{4402}{4479}Ty jsi nástupce|toho Rytíøe Svìtla!
{4516}{4644}Matnì si vzpomínám, e jsem ten pøíbìh|slyšel, kdy jsem byl dítì...
{4644}{4696}...jene jsem NIKDY nedával pozor!
{4712}{4752}Ty nikdy nedáváš pozor!
{4771}{4814}Pst, najdou nás!
{4861}{4915}Je tu tolik stráí.
{5080}{5136}A taky pøísné kontroly.
{5146}{5224}Asi budeme muset poèkat a|do setmìní a potom se vkrást do mìsta.
{5224}{5246}Asi ano.
{5263}{5296}- Zatím si pospím.|- Já taky.
{5296}{5318}I já.
{5575}{5604}Levitation!
{5834}{5914}Nemohla jsi mì dret, dokud|jsme nepøistáli?!
{5944}{5993}- Nìkdo pøichází!|- Tudy!
{6035}{6077}To bylo o chlup!
{6089}{6137}Sleèno Lino, co budeme dìlat?
{6154}{6220}No nejlepší by bylo|nìkoho chytit a...
{6220}{6278}...dostat z nìj informace.
{6295}{6349}Ano. Kdy jsme se|dohodli, pojïme!
{6357}{6402}Ne! Ne! Nedìlejte to!
{6402}{6460}Takhle padnete do rukou|nìjakého lovce zloèincù!
{6476}{6510}Nemáme na vıbìr.
{6510}{6582}Pøesnì! Vdy je nechceme|zabít a sníst!
{6633}{6700}U pøemıšlíš jako Lina,|uvìdomuješ si to?
{6704}{6745}Neodvaujte se to zopakovat!
{6764}{6856}Jsou vìci, které se neøíkají|ani ertem!
{6874}{6916}Co je tak špatné na mém|zpùsobu myšlení?
{6916}{6965}Ještì jsem neskonèila!
{6965}{7026}- Poslouchej mì!|- Ne, mnì!
{7030}{7071}Promiòte.
{7141}{7168}Mùeme vám pomoct?
{7177}{7213}Nic jsme neudìlali!
{7221}{7306}Ne, já jen...|Jsi to ty, drahı Gourry?
{7306}{7339}He? Goury...
{7340}{7373}...a drahı?!
{7396}{7417}Kdo...?
{7417}{7485}Drahı Gourry, si to ty!
{7522}{7550}Hee...!
{7601}{7651}Jsem ráda, e tì opìt vidím!
{7656}{7702}- Nejsi ty...|- Sylphiel!
{7703}{7749}Jsem knìkou v chrámu!
{7753}{7826}Sylphiel! Ach, TA Sylphiel!
{7838}{7924}Bála jsem se o tebe, protoe je|na tebe vypsaná odmìna!
{8010}{8092}Pane Gourry, jakı je váš|vztah k té dívce?
{8092}{8165}Proè vám øíká "drahı|Gourry" a chová se tak mile?
{8202}{8300}To je zvláštní. Od kdy si|tak lehce pamatuješ jména?
{8321}{8388}Potkal jsem ji nedávno,|bìhem jedné malé nepøíjemnosti.
{8388}{8435}Je to vynikající kuchaøka!
{8450}{8500}Podle toho si pamatujete lidi?!
{8500}{8566}To jsem si mohla myslet.
{8594}{8677}Pane Gourry! Došli jste|v poøádku a sem!
{8683}{8717}Vypadá to tak.
{8721}{8762}Oh? Kdo jsou tihle lidé?
{8770}{8814}Ahoj! Jsem Lina!
{8815}{8859}A já jsem Amélie!
{8879}{8957}Lina?! To jako Lina Inverse?!
{8961}{9032}Proè všichni vdy reagujou|takhle?!
{9032}{9103}Vlastnì, je na mnì vypsaná|odmìna, e?
{9122}{9259}Je pravda, e vypadáte mladá, ale|ve skuteènosti jste u pøekroèila 90 let?
{9306}{9336}Pøekroèila 90 let?!
{9347}{9367}Pøesnì.
{9368}{9426}To mì nikdy nenapadlo!
{9426}{9524}To je le! Kde jste slyšela|takovou blbost?!
{9563}{9684}Eh, od toho, kdo na vás vypsal|odmìnu. Od dívky jménem Eris.
{9687}{9725}Eris? Hmm...
{9729}{9790}Aha, take to všechno je její vina.
{9804}{9899}Ano, je to tak.|Pøišla sem asi pøed mìsícem.
{9899}{9991}Vyhlásila, e vy a mùj drahı|Gourry jste hrozní zloèinci...
{9991}{10052}...a vypsala na vás odmìnu.
{10065}{10152}Coe?! Nìjaká pøiblblá bába vletí|do mìsta s vymyšlenım pøíbìhem...
{10156}{10228}...a vy hned zaènete|lepit plakáty?!
{10228}{10300}Ne... Tušil jsem, e|je to jen vımysl.
{10300}{10403}Nevìøil jsem, e by pan|Gourry udìlal nìco takového.
{10406}{10475}Ale ona øekla, e|je pod kontrolou...
{10475}{10544}...zlé èarodìjnice,|Liny Inverse.
{10568}{10613}Nìkdo mi opravdu chce|znièit povìst.
{10625}{10693}I kdy o té zlé èarodìjnici|je to pravda!
{10696}{10735}Pøestaò s tím!
{10750}{10884}A sleèna Eris má|nezpochybnitelnı kredit.
{10890}{10916}Opravdu?
{10921}{11012}Ano. Od dobøe známého|mue kterı pobıvá tomhle mìstì...
{11017}{11128}Vypadá to, e to dìvèe má velmi|blízko k Rezovi, Rudému Knìzi.
{11141}{11176}Rudému Knìzi?!
{11176}{11207}Rezo?!
{11225}{11315}Rezo Rudı Knìz, povaovanı za|jednoho z nejmoudøejších lidí své doby.
{11319}{11399}A mu, kterı znovu oivil|Temného Pána Shabranigda...
{11399}{11488}...a tak témìø znièil|celı svìt!
{11502}{11620}Hee? Vy a sleèna Lina znáte|Reza, Rudého Knìze?!
{11648}{11728}Ano. Ty vlastnì nevíš,|co se stalo, Amélie.
{11728}{11789}Mudrc jako on musel udìlat...
{11789}{11849}...je tu nejspravedlivìjší vìc!
{11863}{11920}Lino! Ten Rezo...
{11939}{11971}Kdo je to?
{11994}{12055}Vím, e jsem to jméno|nìkde slyšel...
{12055}{12154}...ale nepamatuji se.|U to mám na jazyku-
{12159}{12195}NEOPOVAUJ SE NA NÌJ ZAPOMENOUT!
{12195}{12239}No tak!|Rezo Rudı Knìz?!
{12239}{12283}- Kterı?|- Je JEN jeden!
{12283}{12369}Ten chlap, co tì témìø|zabil, pamatuješ?!
{12398}{12485}Ty se opravdu nepamatuješ, co?!|Máš mozek medúzy!
{12498}{12566}Drahı Gourry, co se dìje?
{12594}{12650}To nevíme ani my.
{12650}{12711}Bála jsem se, e tady, v|Sairaagu...
{12712}{12773}...se stane nìco|opravdu hrozného.
{12797}{12870}A pokud s tím máš nìco spoleèného,|tak potom...
{12896}{12933}Neboj se o mnì.
{12949}{13016}Dobøe! Jediné, co teï musíme|udìlat, je najít tu Eris...
{13016}{13093}...která na nás vypsala odmìnu|a spoèítat jí to!
{13108}{13161}Take, kde mùeme najít Eris?
{13165}{13240}Bydlí ve velké rezidenci nedaleko odtud.
{13286}{13355}Promiòte, e vás|takhle vyuíváme.
{13355}{13405}To opravdu nestojí za øeè.
{13421}{13484}Drahı Gourry, dávej si na sebe pozor.
{13484}{13597}Jistì. A co nejdøív se zastavím|u tebe na nìjakou dobrotu.
{13611}{13647}Gourry, jdeme.
{13647}{13692}Dobøe!
{13791}{13819}Drahı Gourry...
{13945}{13983}Je to tu dìsivé!
{14001}{14068}Øekla bych, e|tu sídlí zloèinci.
{14068}{14118}Pojïme!
{14175}{14215}Myslím, e bychom mìli vejít.
{14215}{14240}Dobøe.
{14240}{14283}Jene tohle je stìna!
{14441}{14487}- Bravo!|- ádnı problém!
{14508}{14631}Pan Gourry moná není právì|nejmoudøejší, ale meè ovládá dokonale!
{14666}{14705}Amélie, pojï za námi.
{14710}{14732}Ano...
{14931}{14995}Vypadá to tu jako|vızkumná laboratoø.
{14995}{15047}Ale co tady mohou zkoumat?
{15164}{15200}Hm? Co je tohle?
{15272}{15330}Tohle místo je trochu strašidelné.
{15330}{15405}Vypadá to, e tu jsou|jen samé chiméry.
{15410}{15434}Chiméry?
{15434}{15471}Kombinované formy ivota.
{15472}{15564}Napøíklad, kdy zkombinuješ èásti|rùznıch tvorù...
{15565}{15617}...vytvoøíš nìjakého|umìlého tvora.
{15617}{15668}- Ty to taky dokáeš?!|- Celkem dobøe.
{15668}{15756}Osoba s magickımi|schopnostmi...
{15756}{15850}...by dokázala zkombinovat|i èlovìka s jinımi tvory.
{15869}{15956}Nikdo by si nemìl takhle|zahrávat se ivoty jinıch!
{15956}{16044}No, názory èarodìjù na|etiku jsou trošku jiné.
{16044}{16088}Ale mne osobnì tohle nezajímá.
{16109}{16178}Nejdøív musíme najít toho,|kdo stojí za tím vším.
{16517}{16590}Lino, podívej!|To je ten-víš-kterı!
{16602}{16663}Ten portrét dokazuje, e...
{16663}{16764}...majitel této rezidence je|v nìjakém spojení s Rezem
{16775}{16806}Ještì pøesnìji...
{16806}{16841}Kdo je tam?!
{16894}{16967}Tohle je pøímo jedna z|Rezovıch rezidencí.
{16986}{17011}Zangulus!
{17011}{17036}Vrumugun!
{17036}{17098}Tak jste se koneènì ukázala sama!
{17141}{17192}Ty jsi ta, co je|za vším!
{17211}{17293}Pøesnì tak! Ta, která|na vás vypsala odmìnu...
{17293}{17376}...a vyslala za vámi|Zangulusa a Vrumuguna...
{17419}{17489}...to jsem byla já, Lino Inverse!
{17490}{17560}He? V ivotì jsem tì|nevidìla.
{17565}{17607}Kdo jsi?!
{17620}{17669}Jmenuji se Eris.
{17669}{17742}Slouím Rezovi,|Rudému Knìzi!
{17762}{17845}Eris?|Slouí Rezovi, Rudému Knìzi?
{17845}{17928}Ale proè na nás vypsala odmìnu?
{17928}{18053}Proto, abych vás|pøilákala sem, do Sairaagu..
{18075}{18156}Proto jsem tu i zùstala.
{18170}{18239}A proè jsi nás sem pøilákala?
{18239}{18296}Pøesnì! O co ti jde?!
{18312}{18383}Jde mi hlavnì o Meè Svìtla.
{18416}{18486}Chceš Meè Svìtla?!|To jistì! Ten-
{18499}{18533}...patøí mnì!
{18561}{18591}Ne, je mùj!
{18591}{18674}Co tím myslíš?! Øíkals, e|mi ho dáš, nepamatuješ?!
{18677}{18730}Kdy, kde a komu jsem|nìco takového øekl?!
{18730}{18823}Zase jsi zapomnìl! Boe,|máš tak špatnou pamì!
{18824}{18917}A pak? Co udìláš, kdy|dostaneš Meè Svìtla?
{18929}{18983}To tì nemusí zajímat!
{18983}{19086}Kdy mi ho nedáte dobrovolnì,|seberu si ho silou!
{19187}{19233}Je èas s tímhle skonèit.
{19257}{19282}Pojïme!
{19400}{19460}Freeze Arrow!
{19484}{19537}Flare Arrow!
{19605}{19636}Flare Arrow!
{19651}{19678}Freeze Arrow!
{19683}{19761}Flare Arrow! Freeze Arrow!|Flare Arrow! Freeze Arrow!
{19782}{19842}Take ty dìláš pro ni, co?!
{19842}{19902}Zda pracuji pro ni nebo ne...
{19902}{19970}...na tom teï nezáleí!
{20120}{20176}Ve jménu spravedlnosti...
{20176}{20252}...já, Amélie Wil Tesla|Seyruun, tì vyzıvám!
{20290}{20346}Opravdu, kdy jde o nadšení,|jsi pøipravená dobøe!
{20353}{20455}Ale bojím se, e budeš|bojovat s tímhle!
{20545}{20590}Ale to je tak...!
{20856}{20928}Nezapomnìl jsi na jednu vìc?!
{20928}{21004}Nic nemùe zlomit mùj|démonickı Vyjící Meè...
{21004}{21079}...kterı pro mnì vytvoøil|Rezo, Rudı Knìz!
{21084}{21135}Uvidíme.
{21183}{21235}Uka se, Svìtlo!
{21277}{21389}Tak se podíváme, zda Meè|Svìtla dokáe zlomit tvùj meè!
{21488}{21560}Icicle Lance!
{21776}{21825}A pokraèuji s tebou.
{21843}{21923}To se uvidí! Nenechám se|zmìnit na kus ledu!
{21952}{21996}Je èas na nìco vìtšího!
{21996}{22079}"Drak z temnoty pekelnıch hlubin!"
{22079}{22148}"Tvùj øev nech zmìní nepøítele na popel!"
{22152}{22202}GAAV...!
{22234}{22296}Nezbude ti èas! Icicle Lance!
{22392}{22462}K èertu! Nedovolí mi pouít|moje velká kouzla!
{22561}{22612}Nechci bojovat s tak odpornou vìcí!
{22687}{22719}Tady to konèí!
{22858}{22937}Takhle to nepùjde.|Take...!
{23194}{23256}Myslíš si, e porazíš magii meèem?
{23266}{23309}Nech se pøekvapit.
{23495}{23527}Teï zemøeš.
{23854}{23925}Nesoustøedil jsi se a|minul's první ranou.
{23925}{24007}Nepodceòuj meè v rukou Liny Inverse!
{24136}{24202}B-B-B-Blam Blazer!
{24292}{24318}Amélie!
{24318}{24374}To bylo o vlásek!
{24426}{24478}Pøišel èas to skonèit!
{24478}{24530}To je moje replika!
{24696}{24725}Vyhrál jsem.
{24731}{24760}K èertu!
{24785}{24825}Vypadá to, e i ty|jsi u skonèil.
{24825}{24852}V pohodì.
{24852}{24926}No, mám na tebe pár otázek...
{24926}{24947}Ne, nemáš!
{24961}{24999}Vru- Vrumugun?!
{25224}{25288}- To není moné!|- Další Vrumugun?!
{25305}{25343}To jsou dvojèata?
{25356}{25399}Ne celkem.
{25453}{25505}Vrumugune, zachraò mì!
{25514}{25545}T-Trojèata?
{25545}{25598}Ne, to urèitì ne.
{25599}{25652}Jste jen Kopie, e?
{25652}{25693}Kopie?
{25693}{25772}Stejná magie jako s chimérami...
{25772}{25869}...dovoluje vyuít nìèí krev|na vytvoøení tolika kopií, kolik potøebuješ.
{25883}{25988}Take, kdy by nìkdo chtìl, mùe|vytvoøit tisíc kopií tebe, Lino?
{25988}{26019}Správnì.
{26073}{26118}Och, to je hrùza!
{26118}{26190}To by znamenalo konec svìta!
{26190}{26254}Poslouchejte, vy dva...
{26254}{26318}Pøesnì tak.|Jsme Kopie.
{26326}{26428}Není divu, e ti nikdy nevadilo,|kdy jsem tì zabila!
{26446}{26498}Chceš to zkusit a|zabít nás znovu?
{26498}{26593}I kdy se ti to podaøí,|nahradí mì další kopie.
{26678}{26719}Teï u neunikneš!
{26730}{26766}Tady to konèí!
{27177}{27257}Nenech se oklamat!|Ona je ta, kdo je øídí!
{27293}{27336}Kdo, k èertu, jsi?!
{27421}{27480}Co se dìje?|To vám není podobné.
{27480}{27548}- Zelgadisi!|- Dlouho jsme se nevidìli.
{27548}{27616}Zelgadisi?!|Ty nám køííš naše plány?!
{27630}{27719}Vytvoøilo se mezi námi urèité pouto.|A i kdybych tomu nevìøil...
{27719}{27787}...tohle náhlé støetnutí mi ukazuje,|e je nezlomitelné.
{27880}{27928}Nejdøív se postavíš proti|Pánu Rezovi...
{27928}{27990}...a teï i proti mnì,|Zelgadisi?!
{28004}{28098}Tobì ani Rezovi nic nedluím.
{28111}{28224}Zvláš, kdy vím, e|jsi mu pomáhala vytváøet mé tìlo!
{28271}{28329}Poèkej! To znamená, e|ji znáš?!
{28343}{28377}Ano, ona je-
{28378}{28412}Pøesnì tak!
{29183}{29302}Eris a Zelgadis,|oba byli moji následovníci!
{29335}{29408}To... To pøeci...|To ne!
{29548}{29597}Stejnı mu, jako na obraze...
{29597}{29647}Rezo Rudı Knìz?!
