{1}{1}23.976
{324}{383}Tam kde se vyrojí monstra,|pøicházím, abych je znièila.
{399}{465}Tam, kde se zatøpytí poklady,|objevím se, abych se jich zmocnila.
{465}{571}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2615}{2663}Nakonec jsme se dostali do Seyruunu!
{2663}{2712}A mùeme øíct "Sbohem" Amélii.
{2712}{2776}Nakonec to je to,|co byste oèekávali, e udìlám...
{2777}{2877}...ale z nìjakého dùvodu jsme se objevili v tomhle|mìstì na plakátech hledanıch zloèincù!
{2877}{2945}A hned nadto jak jsem øekla...
{2945}{3012}...nás zaèali stíhat "spojenci spravedlnosti".
{3012}{3070}K èertu, Amélie! Ty také?
{3084}{3122}A taky se objevil...
{3122}{3185}Úasnì podezøele vypadající èarodìj Vrumgun...
{3185}{3256}...a jeho partner, lovec zloèincù, Zangulus.
{3256}{3327}Mohli by to bıt ti, kteøí nás falešnì obvinili?
{3339}{3407}Naši noví nepøátelé leí v Sairaagu!
{3410}{3494}Myslím, e se vydáme na novou cestu...
{3494}{3556}...bohuel znovu s novì|motivovanou Amélií.
{3556}{3656}No, u jste napjatí jaká nová|dobrodruství nás èekají?
{3665}{3827}NAVIGACE!|Pozvání do Sairaagu!
{4364}{4485}Hej, hej, hej, hej!|Boe, zas ty rány...
{4636}{4684}Máme je!
{4751}{4851}Došli jste a sem, aby jste|padli do té nejjednodušší pasti!
{4857}{4907}- Opravdu, sleèinko?!|- Jen se uklidni!
{4908}{4980}Jsme vyèerpaní, protoe nás|celé dni pronásledujete!
{4988}{5069}Tak teï vás u máme!
{5108}{5156}Vrumugun!
{5165}{5208}Ještì iješ?
{5217}{5276}U se nedivím, e se|tihle na nás nalepili!
{5277}{5349}Vypadá to, e|máme dalšího nevítaného hosta.
{5353}{5443}No není to pìknı pohled?|Sleèinko. Gourry.
{5454}{5505}Oh... i Zangulus?!
{5511}{5598}Oh, ty tvrdohlavı,|nerozumnı, otravnı...!
{5669}{5724}Ale, ale, ale... Uch...!
{5726}{5785}Mìl by si se nauèit lépe|zacházet s dìvèaty!
{5791}{5890}Pch! Mnì zajímá jen|ten chlapík co je s tebou!
{5942}{6068}Bojovat s nìkım, kdo visí dolù|hlavou, by mi nevylepšilo povìst.
{6070}{6127}Tak, teï je to lepší.|Tas svùj meè!
{6135}{6180}Oh, nemohli byste pøestat?!
{6181}{6252}Takhle otravní chlapíci|si nikdy nezískají dívku!
{6261}{6327}Nezáleí nám, jak jsme|populární mezi dìvèaty.
{6334}{6418}Pùjdete u koneènì s námi|do Sairaagu?
{6423}{6516}Hmm... Je pìkné bıt|pro zmìnu jednou pozvaní.
{6518}{6598}Ale neøekla bych, e|to byl pøíliš vydaøenı ert...
{6599}{6662}...Ty jsi ho pochopil?
{6663}{6698}To byl ert?
{6708}{6766}Mám dost takovıch nudnıch|pastí.
{6768}{6824}Ty hrozivı mágu!
{6857}{6926}I kdy pùjdeme|do Sairaagu anebo jinam...
{6928}{6975}...pùjdeme sami!
{6976}{7045}Proè nás stále|pronásledujete?!
{7048}{7166}Jednoduše proto, e vás|máme dostat do Sairaagu.
{7167}{7235}A proto jsme zvolili ty|nejefektivnìjší prostøedky.
{7238}{7323}Tohle je asi jedinı|monı zpùsob.
{7333}{7398}Aha, tak to byl váš plán|od zaèátku.
{7400}{7457}- Gourry!|- Jsem pøipraven!
{7979}{8016}Jsem fakt hladová.
{8019}{8088}Dobøe, take bychom mìli...
{8122}{8162}UTÉCT!
{8266}{8345}Hej! To není fér, otoèit se|zády k nepøíteli!
{8347}{8385}I kdy technicky jste to neudìlali!
{8387}{8482}Vrate se, vy...!|Za nimi!
{8627}{8660}Jsou smìšní.
{8859}{8918}Kde mùe bıt sleèna Lina?
{8920}{8992}A pøitom jsem koupila|tolik vìcí.
{9036}{9086}Oh! To musí bıt oni!
{9128}{9172}Ahojky!
{9189}{9275}Ahojky, sleèno Lino! Tady jsem!
{9301}{9367}Jídlo! Levitation!
{9389}{9420}To není fér,|jíst sama!
{9427}{9477}Mìj se!
{9484}{9560}Pus, Gourry! Jsi tìkı!
{9565}{9593}Neuteèeš nám!
{9655}{9723}Pojïme, chlapci! Tahejte!
{9723}{9789}PØESTAÒTE!
{9803}{9865}Ejha!|Sleèna Lina má problémy!
{9866}{9909}V poøádku...
{9924}{9966}To snad... To snad!
{10013}{10062}Amélie, ne!
{10100}{10142}To jsem vìdìla...
{10358}{10415}Vítìzství!
{10437}{10502}To se od ní dalo èekat...
{10542}{10667}Umm... Zdá se, e|další mìsto je a za horami.
{10671}{10743}Pùjdeme pøímo a zamíøíme|rovnou k vrcholu.
{10779}{10823}Ehm...
{10863}{10890}Sleèno Lino?
{10982}{11022}Hééj, sleèno Lino!
{11024}{11064}Poslouchám tì.
{11080}{11150}Proè myslíš, e se|takhle vleèu?!
{11168}{11218}Dìsíte mì!
{11231}{11300}Amélie, poslouchej mì.
{11300}{11348}Teï Linu nevyrušuj,|dobøe?
{11356}{11418}He? O èem to|mluvíte?
{11431}{11559}Má problémy. Chápu tu|bolest,co cítí.
{11560}{11600}Já ne.
{11609}{11680}První dùvod: Kvùli tìm|plakátùm...
{11681}{11769}...neexistuje vesnice, do které|bychom mohli riskovat vstup.
{11785}{11922}Druhı dùvod: Dali jsme ti|poslední peníze na nákup jídla.
{11929}{12058}Aha, chápu! A já jsem znièila|VŠECHNO jídlo, ano?
{12136}{12186}Pokoj tvé duši, Amélie.
{12288}{12378}TAKE KDY TO CHÁPEŠ,|ZAVØI HUBU A ŠLAP!
{12386}{12448}LIDÉ JSOU TROŠKU NERVÓZNÍ,|KDY JSOU HLADOVÍ!
{12451}{12519}- U chápu!|- TAK POTOM MLÈ!
{12528}{12547}Ticho!
{12563}{12586}To je...!
{12779}{12870}Cítím nìco dobrého.|Cítím nìco velice chutného!
{12875}{12961}Jsme tak hladoví, e|máme halucinace...
{12963}{13000}Ale mnì je to jedno!
{13009}{13058}Halucinace vùnì?
{13059}{13131}Ale já také cítím|nìco dobrého.
{13140}{13218}Je to peèené kuøe?|Králík? Nebo kaèena?
{13220}{13292}Nìco opravdu chutnì pøipravené,|s èesnekem a koøením.
{13332}{13369}Tady to je!
{13381}{13507}Tady to máme, specialita pana Zabogu,|peèené kuøe!
{13509}{13613}Kdy ucítí tuhle vùni,|máme je!
{13788}{13859}Je..e, tohle je fakt|hluboká jeskynì.
{13861}{13911}Zaujímalo by mì, jak daleko sahá?
{14140}{14172}Tady je to!
{14173}{14241}Ne, poèkejte! Ne!|Je to past!
{14245}{14300}Dobrou chu!
{14586}{14614}Golem!
{14758}{14840}Z cesty!|Rychle! Rychle!
{14972}{15015}Kuøe! Kuøe! Kuøe!
{15025}{15120}P-p-poèkejte! Ten pohled|se mi vùbec nelíbí!
{15122}{15166}Pomoc!
{15168}{15183}Moje!
{15185}{15256}Agh! Co je s tebou, Lino?!|Není fér sníst to všechno!
{15257}{15319}Slyšel jsi nìkdy vıraz|"nejdøív dámy"?!
{15326}{15416}Kdo je tu dáma?! Kdybych tì pustil,|nenechala bys mi ani kosti!
{15730}{15783}Amélie, neple se mi do cesty!
{15786}{15840}Obavám se, e to pro|vás neudìlám!
{15847}{15955}Hej! Gourry, to je moje kuøe!|To není fér! Vra to!
{16035}{16088}Och, ne!|Moje kuøe je na placku!
{16091}{16147}Na kuøe zapomeòte!
{16692}{16793}To teda ne! "Nekoneèná zemi,|matka všech vìcí!"
{16795}{16836}Dug Haut!
{16999}{17019}Ty...!
{17027}{17075}Sleèno Lino, pozor!
{17315}{17380}Myslí to vánì!
{17521}{17580}Flare Arrow!
{17660}{17728}K nièemu. Nemám ádnou sílu,|kdy jsem hladová!
{17885}{17960}Sleèno Lino!|Pan Gourry je tìkı!
{18010}{18058}Sleèno Lino!
{18069}{18122}Prosím, pomozte mi!
{18133}{18170}Diem Wing!
{18352}{18406}Sleèno Lino, vdy|jen utíkáme!
{18406}{18455}A èí je to chyba?!|Èí?!
{18455}{18494}Ray Wing!
{18704}{18776}Takhle to bude rychlejší!
{18997}{19051}Mìli by tu bıt kadou|chvilku!
{19051}{19121}Tentokrát nám neuteèou!
{19362}{19395}Heej!
{19423}{19490}Heej!
{19516}{19561}Bye-bye!
{19569}{19658}Vrate se, vy...!
{19948}{20041}Jsou tak blbí, e se|chytili do vlastních pastí?
{20081}{20150}U ïasa!|Tohle vám nezapomeneme!
{20209}{20316}Juchú! Pøi tomhle tempu jsme|za chvíli v dalším mìstì!
{20336}{20405}Ale sleèno Lino, nemyslíte, e|je pøíliš velké štìstí...
{20405}{20485}...najít vor právì tam,|kde jsme ji potøebovali?
{20486}{20556}Myslíš, e je to zase past?|Trochu to pøeháníš.
{20556}{20629}A hned jak se|dostaneme do mìsta...
{20629}{20701}Jídlo! Koneènì si dáme|poøádné jídlo!
{20763}{20823}Poøádné jídlo, Gourry!
{20823}{20884}Ano, Lino... Jídlo!
{20915}{20952}Tohle nevìští nic dobrého.
{20957}{21015}Jídlo! La-la-la-la!
{21426}{21543}Oh, ty hloupı, tvrdohlavı,otravnı...!|Kdy s tím pøestaneš?!
{21543}{21594}Digger Bolt!
{21720}{21775}Dostala jsem ho tentokrát?
{21775}{21831}Oh, jsem hotová...
{21887}{21932}Teï jsem na øadì já!
{22161}{22228}Tøikrát hurá tvé|brutální síle, Gourry!
{22228}{22272}Oh, sleèno Lino, co je tamhle?
{22477}{22513}To je zase on.
{22513}{22571}Oh, u mám toho dost!
{22612}{22718}Take jste koneènì dorazili!|U jsem se zaèínal nudit!
{23063}{23121}Nebojte se!|Tento trik nikdy nefunguje!
{23351}{23383}- Opravdu.|- Vidíte?
{23495}{23522}He?
{23673}{23714}Tohle je u fakt støelené.
{23730}{23805}Nemyslím, e to chápe.
{23846}{23885}Ne, poèkat! Tady ne!
{23885}{23936}Tohle místo je pøíliš malé!
{23996}{24029}Pøestaòte, nebo nás|zabijete!
{24142}{24187}NESNÁŠÍM RYBY!
{24579}{24627}Proè se tohle stane vdycky jen nám?!
{24888}{24945}Achjaj! Nemùu JI porazit|pod vodou!
{25184}{25259}"Ty, co procházíš mezi|nebem a zemí."
{25259}{25295}"Pokojnì tekoucí voda."
{25295}{25365}"Soustøeï se v mıch rukou|a dej mi svou sílu!"
{25384}{25427}DEMONA CRYSTAL!
{25781}{25865}Zima! Zima! Brr! Zima!
{26017}{26088}Øíká se, e labu na první|pohled plave elegantnì...
{26088}{26180}...ale pod vodou i|tak kope nohama.
{26180}{26219}Tohle nikdy neskonèí.
{26226}{26297}Vìru ne, tohle je jen zaèátek.
{26301}{26374}Mohli bychom ukonèit tuto|smìšnou honièku?
{26374}{26393}Amélie!
{26411}{26435}Sleèno Lino!
{26435}{26567}Buï pùjdete se mnou|do Sairaagu anebo zabiji tohle dìvèe.
{26594}{26687}Ale no tak, brát si|dívku jako rukojmí?
{26693}{26773}To by nedìlal ani|tøetitøídní mág!
{26787}{26854}Myslíš, e jsem mìl na vıbìr?
{26865}{26947}To mì nezajímá!|Teï jsi mì fakt naštval!
{26947}{27018}U si nebudu|vybírat ani já!
{27018}{27091}Správnì, sleèno Lino! Neberte na mnì|ádné ohledy a porazte ho!
{27091}{27174}Dobøe, dobøe! Pro mnì-za mnì!|Udìlám to, jak øíkáš!
{27245}{27367}"Temnota pøed úsvitem,|karmín èervenìjší ne tekoucí krev!"
{27367}{27408}"Pochovanı v pøílivu èasu..."
{27408}{27524}"Ve tvém velkém jménì,|zapøísahávám se silám temnot."
{27524}{27649}"Všichni blázni, kteøí se nám|postaví do cesty, budou znièení..."
{27649}{27730}"...silou,|kterou spoleènì vládneme!"
{27753}{27795}Ajaj! To je...!
{27814}{27867}To je u pøíliš!
{27899}{27956}DRAGON SLAVE!
{28945}{29034}Nemyslete si, e|jste mì porazili!
{29385}{29431}Hele! Lino!
{29431}{29479}Jak daleko je do dalšího mìsta?
{29479}{29520}Jak to mám vìdìt?
{29533}{29583}A jak daleko|je to do Sairaagu?
{29583}{29633}Proè se nezeptáte toho voru?
{29633}{29727}Jsem tak hladová... a dneska|jsem ještì nic nejedla.
{29727}{29806}Moná jsme je mìli nechat,|aby nás sebrali.
{29806}{29912}Byli otravní, Gourry!|Otravní chlapi nikdy nezískají dìvèe!
{29945}{30005}A tak jsme se nechali|unášet nekoneènım tokem øeky...
{30005}{30074}...smìrem k Sairaagu,|našemu koneènému cíli.
{30074}{30142}Je jedno, kam nás|voda zítra odnese...
{30142}{30199}Jsme opravdu hladoví!
