{1}{1}23.976
{330}{387}Tam, kde se vyrojí monstra,|pøicházím, abych je znièila.
{402}{462}Tam, kde se zatøpytí poklady,|objevím se, abych se jich zmocnila.
{477}{574}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2599}{2682}Na naší cestì do Sairaagu jsme se jako uprchlíci...
{2685}{2786}...na chvíli stali herci, vımìnou|za trochu teplého jídla.
{2786}{2861}Problém byl s Amélií, které trochu stouplo|hlavy úèinkování ve høe...
{2861}{2922}..."Smrt odporné Liny Inverse".
{2922}{2975}Kolikrát mám ještì opakovat,|e má odpornost není pravda!
{2975}{3045}No a Zelgadis se pokusil pøekazit naše pøedstavení.
{3045}{3115}To nemìl zkoušet!|Jsem vdycky pøipravená k boji!
{3115}{3176}No a kdy jsem se nemusela dret scénáøe...
{3176}{3236}...tak ta hra skonèila velkım úspìchem...
{3236}{3288}...a zanedlouho jsme zas zamíøili k Sairaangu.
{3288}{3340}No nevím, co nás ještì mùe potkat...
{3340}{3427}Doufám, e se potíím dokáeme vyhnout, ale...
{3427}{3576}OTÁZKA!|On ádá o ruku TU dívku?
{4807}{4837}Fireball!
{4888}{4975}Dobøe, take to je dnes u|desátá skupina hrdinù!
{5140}{5177}No, a tohle byla jedenáctá.
{5177}{5234}Slyš mì, Lino Inverse!
{5234}{5318}Dnes zaplatíš za své zloèiny!|Já, Codan, tì rozdrtím!
{5330}{5394}Dnešní èíslo dvanáct.|Bylo by fajn, kdyby to u vzdali.
{5406}{5466}Vypadají jeden jako druhı.
{5471}{5522}Jsou opravdu trochu stereotypní.
{5522}{5573}Hej! Otoè se a|bojuj se mnou!
{5573}{5627}Dobøe, dobøe.|Kdy chceš právì tohle...
{5627}{5684}Diem Wing!
{5737}{5785}Pøedvèírem jich bylo sedm.
{5786}{5838}Vèera deset.
{5842}{5948}Kdy pùjdeme pøes Sandoriu,|odhaduji to tak na 40 a 50.
{5951}{6052}Mohli by jsme jít pøes|Sandoriu, jene...
{6052}{6153}...kadı bojovník za právo,|hrdina i lovec zloèincù...
{6153}{6254}...tam pøišel zkusit zabít|moøského draka.
{6270}{6370}No vdy mùeme zkusit pøejít|do Sairaagu pøes Pohoøí Slz.
{6370}{6429}Pøes Pohoøí Slz?!
{6608}{6676}Jdou po nás všelijací hrdinové,|lovci zloèincù a zastánci spravedlnosti...
{6676}{6763}...Zangulus, Vrumugun, a|bùhví kdo ještì...
{6763}{6849}...a ty chceš jít pøes|ultra-strmé Pohoøí Slz, Gourry?!
{6896}{6930}- Ee, ne.|- No tak!
{6933}{6989}Tak pøestaò kòourat!
{7017}{7069}Fireball!
{7112}{7156}Bum-bác!
{7172}{7297}Dobøe, dohodli jsme se, e|pùjdeme lodí ze Sandorie.
{7309}{7350}Ale jak to udìláme?
{7886}{7925}Polez, Zangulusi.
{7925}{8044}No dobøe! Budou muset pøejít|Pohoøí Slz!
{8049}{8112}Poèkáme tam na nì|a potom-
{8153}{8182}To bylo o vlásek!
{8182}{8275}Vím, jak jsi nedoèkavı,|jen se dívej, kam šlapeš.
{8283}{8333}Tvo...Tvoje hlava!
{9564}{9627}Je ještì lepší, ne jsem|si myslela.
{9627}{9721}Opravdu! Je z vás nádherná|dáma, pane Gourry.
{9721}{9787}Zacházet s èlovìkem jako s panenkou...
{9787}{9861}Èím jsem si to zaslouil?!
{9861}{9934}A teï druhá fáze. ÁÁááá!
{10103}{10139}Šváb!
{10149}{10187}Ty jeden malı špinavı...!
{10268}{10355}Vidíš? Všichni hrdinové jdou|po èarodìjnici Linì Inverse...
{10355}{10396}...a rytíøi Gourry Gabrievovi.
{10402}{10474}V takovém pøevleku nás|nebude podezøívat nikdo!
{10490}{10535}Jsme pøedci...
{10535}{10580}...tøi pøekrásné...
{10580}{10624}...a milující sestry!
{10624}{10690}Pomoc, prosím!
{10690}{10806}Staèí, kdy se budeš chovat jako|já a Amélie.
{10820}{10867}Tak, a teï další vìc...
{11053}{11129}Ne, pane Gourry!|Buïte víc enskı!
{11129}{11205}He? Øíkala, e se mám|opièit po ní.
{11256}{11299}Tak zdravı apetit.
{11320}{11390}Dìvèata, hledáte|loï do Sanboje?
{11433}{11543}Naše drahá maminka onemocnìla,|právì kdy jsme se vraceli domù...
{11543}{11617}...ale strach z místního draka|nám nedovolí pokraèovat!
{11620}{11683}Maminka, ano? Cítím s vámi.
{11683}{11781}Tak se o ni bojím,|e nedokái ani poøádnì jíst!
{11849}{11902}Sestøièko, nemìla bys tolik jíst!
{11902}{11952}Nech mì na pokoji!
{11974}{12057}Ale ten moøskı drak|utoèí na kadou loï...
{12057}{12140}...take dokud ho nìkterı|z hrdinù nezabije...
{12140}{12204}...ádná loï nevypluje.
{12204}{12251}Ani jediná?
{12251}{12314}No, kdyby byl na palubì|opravdu silnı hrdina...
{12314}{12380}...co by zabil draka,|moná by to šlo.
{12380}{12437}Dovolte mi bıt tím hrdinou!
{12799}{12837}Jste nádherná.
{12975}{13027}Take od nejmladší,...
{13027}{13100}...jste Lulu, Lili, a Lala.
{13115}{13163}Ty jména jsou trošku|narychlo.
{13163}{13186}Myslíš?
{13186}{13254}Take ty jsi Lala?
{13254}{13300}He? Och, ano!
{13300}{13346}Pøesnì tak!
{13346}{13436}Proè tohle musím dìlat?|To ti vrátím, Lino!
{13439}{13532}Máte štìstí, e jste|natrefili na mnì, velkého Voluna!
{13532}{13615}Jsem si jistı, e jste u|slyšeli o velkém hrdinovi Volunovi.
{13615}{13652}Nikdy.
{13685}{13747}Zabiják nespoèetného mnoství|zloèincù a pøíšer...
{13747}{13810}...hrdina Volun, jeho jméno|rezonuje i v nebesích...
{13810}{13847}...to jsem já!
{13847}{13885}Slyšel jsi o nìm?
{13885}{13906}Nic.
{13906}{13947}Já také ne.
{13966}{14080}Víte, e Temnı Pán|Shabranigdo se nedávno znovuzrodil?
{14090}{14170}No a zabít|Shabranigda...
{14170}{14235}...se poštìstilo mì!
{14267}{14304}Opravdu mì pøekvapilo, kdy...
{14304}{14373}...jsem zjistil, e pøíšera,|kterou jsem zabil, byl Shabranigdo!
{14409}{14464}- Ty jeden lháøi...-|- Uklidni se, Lino!
{14480}{14526}V kadém pøípadì...
{14526}{14628}Pro vás, sleèno Lalo,|se postaví moøskému draku...
{14628}{14718}...a doprovodím vás v|bezpeèí do Sanboje!
{14733}{14770}Och, ee, dìkuji vám...
{14785}{14851}Teï jdu najít vhodnou|loï pro naši plavbu!
{14901}{14962}Pro mne? Co tím myslel?
{14962}{15027}Och, tomu to pomalu zapaluje!
{15042}{15097}Pane Gourry, opravdu jste|to nepochopil?
{15097}{15124}Ani slovo.
{15124}{15242}Znamená to, e velikı hrdina Volun|se do tebe zabouchl.
{15242}{15287}Aha, chápu!
{15352}{15410}- Mizím!|- Ani náhodou!
{15410}{15476}Pokud pan Volun zmìní svùj názor,|všechno se zkazí!
{15476}{15517}Pojïme, Lili!
{15517}{15558}Jasnì, Lulu!
{15585}{15650}Odmítám!|Tohle absolutnì odmítám!
{15650}{15711}Je to pro dobro spravedlnosti,|tak se s tím smiøte!
{15711}{15749}Kde je tu spravedlnost?!
{15749}{15810}No, jistì bude nìkde|nedaleko!
{15810}{15871}Nedìláš to nadarmo,|take sklapni!
{16055}{16113}Dobøe! Napnìte plachty!
{16113}{16208}Nebojte se moøského draka!|Skolím ho jednou ranou!
{16208}{16248}Jste si tím jistı?
{16248}{16288}Nechte to na mnì!
{16288}{16392}Neexistuje drak, kterého|bych nedokázal skolit!
{16429}{16514}Ale co budeme dìlat, kdy se|drak opravdu objeví, sleèno Lino?
{16519}{16558}He? No pak...
{16558}{16626}Zdá se, e na to jste|vùbec nepomyslela.
{16626}{16667}Pøesnì tak!
{16667}{16759}Ale kdy nevíme, zda se ukáe|anebo ne, nemusíme se starat.
{16774}{16802}Souhlasím.
{16947}{17020}Toto je nejholèièejší|pokoj, jakı jsem kdy vidìla.
{17020}{17072}Je to váš pokoj, pane Gourry?
{17085}{17138}Moje kajuta.
{17138}{17185}Hele, tohle je moje kajuta!
{17211}{17267}Hej, Gourry!|Zkus si tohle!
{17267}{17320}Pøestaòte!
{17343}{17391}- Proboha...|- Aha, chápu!
{17391}{17437}Preferujete trochu chlapeckı styl, e?
{17472}{17525}Ne, to není|tím! Já jsem-
{17742}{17788}Pøestaò!|Jsme na lodi!
{17788}{17834}I kdyby vìdìl pravdu...
{17849}{17904}Myslím, e mu to vùbec|nebude vadit.
{17908}{17981}Je to takovı slaboch. V ádném pøípadì!
{17981}{18053}Cesta je dlouhá!|Kdy se prozradíš...
{18087}{18141}Uhm, sleèno Lalo?
{18141}{18195}Prosím, napijte se.
{18195}{18226}Och, ne, já...
{18330}{18387}C-Co se dìje, sleèno Lalo?
{18387}{18431}Nic. Jen se cítím...
{18461}{18496}Boe mùj! Odnesu vás|do vaší kajuty!
{18496}{18536}Ne, já jen...!
{18569}{18610}Promiòte mi to.
{18610}{18687}Och, ne. Bylo mi jen|trochu teplo.
{18687}{18758}Pomùe mi, kdy zùstanu na|èerstvém vzduchu!
{18758}{18822}Oh, souhlasím!|Já také upøednostòuji èerstvı vzduch.
{18822}{18880}Dotyk vìtra je tak...
{18971}{19039}Ach! Promiòte! Nic jsem|nevidìl! Vùbec nic!
{19078}{19106}- Sleèno Lalo!|- Ano?!
{19106}{19175}Je tu nìco, na co se vás chci|zeptat, od chvíle co jsme opustili pøístav.
{19221}{19269}Stanete se mou nevìstou?!
{19292}{19342}Mou nevìstou?
{19374}{19397}Mou nevìstou!
{19410}{19455}MOU NEVÌSTOU!
{19675}{19794}Je to láska na první pohled. Mùeme|mít svatbu pøímo tady na lodi!
{19812}{19877}Dostaneme poehnání od vašich sester,|kapitán nám vymìní prsteny...
{19878}{19945}- ...a potom... A potom...!|- Gratulujeme! Gratulujeme!
{19945}{19993}Miláèku!
{20041}{20095}Tvùj obìd!
{20134}{20165}DOST!
{20165}{20262}Nemusíte mi odpovídat hned!|Staèí zítra!
{20364}{20401}Gratulujeme!
{20401}{20451}Nakonec jsi se pøedci|jen rozhodla vdát!
{20451}{20500}Budeš mi chybìt, sestøièko.
{20500}{20521}Buaaaaaaa!
{20551}{20597}Lino...! Amélie...!
{20597}{20649}Byl to jen špatnı vtip.
{20649}{20699}Ale Volun to myslí|vánì.
{20699}{20738}Jak mùete bıt tak klidné?!
{20738}{20777}Jediné, co mùeme udìlat...
{20777}{20813}Jediné, co mùeme udìlat, je...?
{20813}{20876}Vzdát to a nechat tì|vdát se za Voluna!
{20876}{20897}Hej!
{20903}{21013}Ale kdy se Volunovi nìco stane,|mohli by otoèit loï zpìt!
{21013}{21071}Take z toho udìlejme tu|nejkrásnìjší svatbu!
{21071}{21135}To je tak romantické!
{21135}{21158}He?
{21158}{21205}Gourry, poèkej! Nebuï tak nedùtklivı!
{21205}{21252}Pus! Kdy budu muset,|budu plavat!
{21252}{21341}Kdy tady vyskoèíš,|seere tì moøskı drak!
{21341}{21475}Radši a mì seere, ne|bych si mìl vzít chlapa!
{21557}{21598}Moøskı drak!
{21792}{21837}Fakt je tu.
{21837}{21887}Já jsem ho ale nevolal.
{22396}{22444}- Co to má znamenat?!|- Divnı drak.
{22444}{22493}Take jsi se zjevil, moøskı draku!
{22493}{22548}Já, velikı hrdina Volun...
{22548}{22641}...ti ukái svou|sílu dotıkající se nebes!
{22641}{22701}Sleèno Lalo! Dívejte se!
{22701}{22760}Není to zlı chlapík, ale...
{22779}{22811}Pøiprav se na smrt!
{22930}{23026}Zabil jsem moøského draka!|Vidìli jste to, sleèno Lalo?
{23042}{23082}Za tebou! Za tebou!
{23082}{23200}Hmpf! Hlupák! Myslíš si, e|mùeš napadnout velikého Voluna?!
{23244}{23311}Vìdìla jsem e mu ten|kopec øeèí nepomùe.
{23311}{23393}Vìdìl jsem, e je to chvastoun,|ale e je a TAK velkı?
{23418}{23492}Ty idiote! Myslíš si, e to mì|pøesvìdèí, abych si tì vzala?!
{23809}{23892}Lino, ten zenštilı drak...|Je on.
{23900}{23936}Kam se to díváš?
{23955}{23985}Podívej, je naštvanı.
{23985}{24081}Lina, proè jsme vlastnì nemohli|do Sanboje letìt?
{24086}{24175}Mysli! Levitation|mi bere mnoho síly!
{24195}{24257}Amélie, zbav se toho,,hrdiny"|a pomo mi!
{24274}{24333}Chtìla bych,|ale kdybych to udìlala,...
{24334}{24393}...porušila bych|Kodex Spravedlivosti!
{24393}{24435}Och, obèas si tak otravná!
{24459}{24513}Jene kdy nás takhle uvidí|v Sandorie...!
{24521}{24561}Dark Mist!
{24680}{24737}Takhle nás nepoznají!|Dobøe, Amélie!
{24813}{24901}Hele, Lino, nemyslím, e|se mùeme neèinnì pøihlíet.
{24901}{24944}No, tušila jsem, e tohle øekneš.
{24958}{25005}Tak dobøe.|Asi nemáme na vıbìr.
{25005}{25061}Nerada bojuji zadarmo...
{25086}{25119}...ale v tomhle pøípadì...
{25180}{25205}...je to nevyhnutné!
{25231}{25328}Dobøe! Èas vybít si|frustraci!
{25408}{25454}Jsem volnı!
{25454}{25491}To se mu odlehèilo.
{25491}{25557}Muselo to pro nìj|bıt pìknì tvrdı.
{25713}{25760}Flare Arrow!
{25760}{25806}Elmekia Lance!
{25983}{26030}Ta vìc má hroší kùi!
{26037}{26081}Povídej mi nìco o hroší kùi!
{26148}{26212}Co je s ním?!
{26300}{26389}Za pokus to stojí...|Lina, zdvihni mì k jeho tváøi!
{26394}{26411}Chápu!
{26428}{26467}Ray Wing!
{26759}{26842}Buï prokletı, draku! Já,|velkı hrdina Volun, tì skolím!
{26901}{26956}Dobøe, Lino! Propùjèi mému|meèi kouzlo!
{26968}{27027}No... Mùeš bıt víc|pøesnı?
{27035}{27117}Cokoliv, pokud ho to|škrábne!
{27133}{27191}Hmm, nìco, co ho škrábne...
{27218}{27254}To je jedno, jen rychle!
{27254}{27290}Dobøe, u to mám.
{27325}{27376}"Zdroj veškeré síly..."
{27465}{27515}"Vítr vanoucí mezi|nebem a zemí!"
{27515}{27565}"Spoj se v mé dlani|a dej mi sílu!"
{27580}{27629}Digger Bolt!
{28064}{28106}Co to...?
{28106}{28167}Utekl kvùli takové malièkosti?
{28205}{28263}Ha! Pøesnì jak jsem si myslel!
{28390}{28473}Aha, tak proto jsi šel|po jeho tváøi.
{28473}{28525}No, bylo jasné, e je to gay.
{28541}{28610}Napadlo mì, e zranìní ve tváøi|ho odradí od boje.
{28610}{28663}Chápu. Dobrı nápad, Gourry!
{28663}{28688}Nic zvláštního...
{28688}{28722}Musíš s tím mít nìjaké zkušenosti!
{28722}{28752}Já nejsem gay!
{28752}{28806}Mimochodem, co se|stalo s panem Volunem?
{28817}{28856}He? Nebyl s tebou?
{28856}{28955}Nevidìla jsem ho, od chvíle|co na nìj spadl ten pytel mouky.
{28955}{29039}Díky bohu! Doufám, e ho|u nikdy neuvidíme!
{29166}{29223}Asi ho naloili v pøístavu!
{29242}{29328}Sleèno Lalo! Sleèno Lala-o-o!
{29374}{29425}Podívej se na mnì! Já jsem chlap!
{29446}{29528}To není moné!|Kde je moje sleèna Lala?
{29554}{29633}Ty se jí podobáš! Je mi|jedno, e si mu!
{29648}{29719}- Poèkej na mnì!|- Ne, stùj! NE!
{29719}{29811}Vypadá to, e Gourryho problémy budou pokraèovat.
{29812}{29854}Ale u jsme skoro v Sairaagu.
{29864}{29914}Ale stále se mùe|stát všelicos.
{30046}{30088}Poøád nejdou!
{30091}{30131}Èekej dál, Zangulusi.
{30139}{30239}K èertu s tím...|Nepøicházejí!
{30266}{30330}K ÈERTU SE VŠÍM!
