{1}{1}23.976
{330}{385}Tam, kde se vyrojí monstra,|pøicházím, abych je znièila.
{398}{467}Tam, kde se zatøpytí poklady,|objevím se, abych se jich zmocnila.
{467}{573}A kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2619}{2668}Okolnosti vám mohou pøivést podivné spoleèníky.
{2668}{2718}Nejsem si ještì jistá jak|jsem se do toho spadla...
{2724}{2766}...ale cestuji s horkımi hlavami...
{2766}{2827}...se šílenì spravedlivou Amélií,|která chtìla abych ji nauèila...
{2827}{2940}...ten nejsilnìjší útok èerné magie, Dragon Slave.
{2954}{3076}Uèení jsme zakonèili vypuštìním celé hory duchù!
{3076}{3151}Díky Amélii jsme tuhle vìc zase srovnali...
{3151}{3226}...a ji pøešla chu nauèit se Dragon Slave.
{3226}{3302}Jen doufám, e to byla|poslední troška našich potíí.
{3328}{3471}PENÍZE!|Zniète ty lovce odmìn!
{3825}{3934}Jsem zpátky! Jsem zpátky! Jsem|nejvìtší hrdina celého Seyruunu!
{3945}{3992}Tu máš, ty zlı draku!
{4295}{4370}Tak TOHLE je Seyruun?!|Je to tu pìknì rušné!
{4374}{4397}Jasnì, e je!
{4406}{4481}Seyruun je jedno|z nejvìtších mìst svìta!
{4486}{4590}Nechci se chválit,|ale v ádné jiné zemi...
{4594}{4674}...není tak rušno a|zároveò tak bezpeèno jako tady.
{4678}{4737}No... vìøím ti.
{4741}{4776}Co, Lino?
{4854}{4875}Co je?
{4879}{4923}Kašli na to.
{4927}{4955}Och...
{4970}{5035}- Budeš tlustá!|- O to se nestarej.
{5039}{5083}- Mùu ochutnat?|- Ani náhodou!
{5151}{5204}Tak tohle je Lina Inverse, co?
{5250}{5328}Dobøe, Phile! Pùjdem k tobì,|najíme se a pak...
{5329}{5390}Poèkej! Poèkej! Myslíš si, e|mùeš jen tak vtrhnout do zámku?
{5391}{5460}Hele, Lino.|Na tom plakátì jsi ty.
{5495}{5528}Plakát sleèny Liny?
{5536}{5604}No, e bych u byla|TAK slavná?
{5622}{5666}Uvidíme...
{5776}{5828}Co to má znamenat?!
{5832}{5926}Nádhera. Podaøilo se jim|zachytit tvé pravé já.
{5930}{5965}Ano, skvìlá práce.
{5969}{6014}To musel namalovat|nìjakı známı malíø.
{6098}{6161}O èem to mluvíte?!|To je plakát hledanıch zloèincù!
{6163}{6205}Plakát hledanıch zloèincù?
{6227}{6266}Tady je další,|a s tebou, Gourry.
{6304}{6350}A další se Zelem.
{6447}{6495}Sleèno Lino, co jste provedla?
{6504}{6596}Zákon mùe odpustit.|Kdy se hned pøiznáte...
{6624}{6677}Od zaèátku mi byli podezøelí.
{6681}{6738}Sleèno Lina... Jste|opravdovı zloèinec, e?
{6745}{6788}No, já, eé... Poèkejte!
{6792}{6892}Vzpomenu si...
{6895}{6976}Je to OK! V poslední dobì|jsem nic zlého neudìlala, aspoò myslím.
{6986}{7069}A na to jsi vzpomínala tak dlouho?
{7073}{7142}A co myslíte|tím "v poslední dobì?"
{7156}{7209}Ale mlè! A co ty, Gourry?
{7216}{7244}Kdo, já?
{7335}{7389}Ty si myslíš, e já si|vzpomenu, zda jsem nìco neudìlal?
{7391}{7450}No jo...|e jsem se vùbec ptala.
{7454}{7517}Ale pokud s tím nic rychle neudìláme...
{7690}{7739}...objeví se tu plno|TAKOVİCH tıpkù.
{7739}{7772}Vìdìla jsem to.
{7778}{7844}Lino Inverse,|ty zloèinecké monstrum!
{7849}{7893}A ty taky, Gourry Gabrieve!
{7898}{7970}Odvaujete se ukázat|pøed Èernımi eleznımi Rytíøi?!
{7974}{8062}Budete pykat za|všechno zlo, co jste spáchali!
{8067}{8110}- Zlo...|- Zloèinecké monstrum?!
{8134}{8247}Pokud jsou to opravdu zloèinci,|je mou povinností je zastavit!
{8322}{8392}Lino Inverse! A ty také,|Gourry Gabrieve!
{8396}{8442}Navzdory tomu, e jsme|cestovali spolu...
{8451}{8513}...jste teï v podezøení, e|jste zloèinecké monstra...
{8521}{8590}...a moje úloha napravovat køivdy|a ochránit spravedlnost...
{8595}{8640}...nemùe bıt ignorovaná!
{8654}{8692}Se slzami v oèích,|musím bojovat s tìmi,...
{8694}{8741}...kteøí ještì vèera byli|mımi pøáteli!
{8780}{8820}Ocením, pokud se pokojnì vzdáte.
{8824}{8886}Jinak budete èelit|vlastní zkáze!.
{8895}{8940}Zapomeò na to, myslí to vánì.
{8942}{8992}A co bych s tím mìla dìlat?
{8996}{9064}Dost øeèí!|Chyte je, chlapci!
{9116}{9168}Hej! Hej! Hej!|Hej, zavolej je zpátky!.
{9197}{9237}Nemyslím, e je|nìkdo dokáe zastavit.
{9245}{9290}No vıbornì. Vypadá to tak,|e musíme zdrhat!
{9349}{9396}Staré, ale osvìdèené! Lighting!
{9487}{9528}Levitation!
{9661}{9690}Ou...
{9700}{9761}Rytíøi za ní!|Klidnì a na kraj svìta!
{9769}{9807}Zlo musí bıt potrestáno!
{9874}{9918}Jen si neubli!
{9945}{9996}Myslel jsem, e já jsem vùdce!
{10053}{10156}Tu odmìnu za pomoc mi|zatím schovej.
{10159}{10252}Dobøe. Promiò, ale situace|mi nedovoluje bránit tì.
{10256}{10297}Ale i tak, hodnì štìstí.
{10318}{10380}Nevadí, jsem šastná,|e za námi nikoho neposíláš.
{10384}{10428}Pozor, Lino! Pøicházejí!
{10479}{10527}- Tak zatím!|- Bye-bye!
{10529}{10588}Stùj! Vrate se zpátky!
{10737}{10781}- Zbavili jsme se jich.|- Jo.
{10785}{10845}Naše malá princezna se jako|obvykle zas utrhla ze øetìzu.
{10850}{10917}A na nás je vypsaná|odmìna!
{10929}{11036}Kdy to takhle bude pokraèovat, pùjde|po nás poøád víc lidí, Lino.
{11040}{11058}Co budeme dìlat?
{11074}{11150}Co asi? Najdeme toho, kdo|na nás vypsal odmìnu...
{11153}{11177}...a postaráme se o nìho!
{11210}{11247}To se dalo èekat.
{11393}{11477}Jsme Støíbrní Rytíøi, známí|po celém království Lenos!
{11619}{11664}Digger Bolt!
{11819}{11920}Kdy znièíme všechny samozvané|"ochránce spravedlnosti"...
{11924}{11984}...urèitì se ukáe|i sám velkı šéf.
{11989}{12079}Ty nikomu nedovolíš vydechnout, e?
{12085}{12136}"Dovol nepøíteli vydechnout|a vydechneš naposledy."
{12141}{12175}Co to má znamenat?
{12180}{12209}Nic zvláštního.
{12221}{12329}Podívej, zatím co tu kecáme,|pøichází další hosté.
{12398}{12466}Zdravíme. Jsme z|království Edoh...
{12470}{12550}...a jsme známí po celé|zemi jako velcí bojovníci-
{12554}{12589}Dobøe, dobøe. Chápu.
{12753}{12819}Hele, nebyla to u šestá skupina?
{12823}{12876}Myslím, e u|sedmá.
{12925}{13003}No myslím, e velkı|šéf by se u mìl ukázat sám.
{13086}{13155}Ale, no tak! Toto platí|tak maximálnì na tebe, Gourry!
{13159}{13179}Co?
{13181}{13236}Opravdu si myslíte, e|Lina Inverse je tak hloupá?!
{13336}{13370}e by to byl...?
{13375}{13410}Legendární roh jednoroce...
{13413}{13477}...kterı se dá lehko prodat|za tisíc zlatek?!
{13616}{13649}Och, ne!
{13665}{13733}- To je opravdu TAK hloupá?|- Jako jsem mohla na tohle naletìt?!
{13781}{13827}Tak, a koneènì vás mám,|sleèno Lino!
{13827}{13855}Amélie?!
{14010}{14065}Ach, boe...|TO muselo bolet!
{14153}{14250}Pøišel èas zaplatit dluhy,|sleèno Lino! A vy také, pane Gourry!
{14320}{14389}Slyšel jsem, e jsi èarodìjka,|kterou není radno podcenit...
{14389}{14448}...a i tak jsi naletìla na|tak hloupou past!
{14494}{14553}Vy jste ti,|co na nás vypsali odmìnu!
{14579}{14605}Pøesnì tak.
{14620}{14658}A kdo vlastnì jste?!
{14681}{14735}Já jsem Zangulus,|lovec zloèincù.
{14749}{14815}A já jsem Vrumugun, mág.
{14851}{14878}Zangulus...
{14886}{14908}...a Vrumugun?
{14923}{15000}Teï vás odvezeme do Sairaagu.
{15012}{15036}Do Sairaagu?!
{15049}{15097}Nìkdo tam na vás èeká.
{15097}{15127}Nìkdo?
{15136}{15183}Myslíte si, e se tam jen tak|necháme vzít?
{15203}{15262}Poèkat.|Navrhuji, aby jste to vzdali.
{15262}{15291}Coe?!
{15297}{15387}Buï pùjdete po dobrém,|anebo tohle pošlu do klece.
{15450}{15486}Nemá kam utéct.
{15535}{15569}K èertu!
{15676}{15726}Dobøe! Dìlejte si co chcete!
{16180}{16227}Puste mì, hlupáci!
{16227}{16282}Kdy budete takhle jednat se|slabımi dìvèaty...
{16282}{16378}...bohové vás potrestají!|Slyšíte?!
{16401}{16418}Dovnitø!
{16548}{16644}Poèkat! Proè jste mì zamotali|do nìèeho takového?!
{16662}{16770}Protoe kdyby ne,|dìlala bys problémy.
{16793}{16841}Co øíkáš?!
{16853}{16886}Poèkat! Poèkat! Poèkat!
{16905}{16958}Vy... Já vám ukáu,|co jsou to problémy!
{16958}{16991}Roztrhám vás na kusy!
{17033}{17077}Proè mì to toho museli zamotat?!
{17091}{17154}Puste mì! Puste mì!
{17154}{17216}Je jako divoké zvíøe...
{17230}{17261}Proè se s tím nesmíøíš?
{17295}{17363}To teda ne... To v ádném|pøípadì, kamaráde!
{17376}{17443}Kdy si myslíte, e se jen|tak lehce vzdám, tak se pletete!
{17451}{17521}Zdroj veškeré síly,|krvavı oheò jasnì záøící!
{17532}{17573}Flare...!
{17690}{17711}Lino!
{17731}{17766}Ach, zapomnìl jsem ti to øíct?
{17766}{17866}Sna se nepouívat magii a|nepokoušej se odstranit ten kruh...
{17866}{17986}...na hlavì, jinak zaiješ|dost nepøíjemnı šok.
{18049}{18080}Jako Opièí král?!
{18080}{18136}Proè jsi mì na to|neupozornil døív?!
{18136}{18170}Muselo mi to|nìjak vypadnout.
{18170}{18199}Tak si seeò lepší pamì!
{18199}{18276}Ve svém zájmu by ses mìla uklidnit.
{18291}{18329}Nesnáším sarkastické mue!
{18382}{18429}Odmìna|za chycení tìch dvou.
{18440}{18504}Ne, ne. Udìlala jsem to|ve jménu spravedlnosti.
{18504}{18574}Nemùu pøijmout peníze.
{18632}{18704}Èlovìèe, to dìvèe je tak|tvrdohlavé!
{18713}{18757}Hned zkouší utéct!.
{18778}{18820}Neví, kdy se vzdát?
{18847}{18882}Pøesnì!
{18972}{19106}Strašnì mì štve, e|to tomu chlapovi nemùu vrátit!
{19106}{19161}Toho bude ještì litovat!
{19176}{19221}Podívej, mùeš si|stìovat,jak chceš.
{19221}{19293}Ale mnì sebrali meè a ty|nemùeš pouívat magii.
{19293}{19333}Nemùeme s tím|nic dìlat.
{19333}{19381}Není to pravda, e|nemùu pouívat magii.
{19381}{19403}Co? Ale vdy...
{19409}{19468}Jen kdy vyslovím zaklínadlo,|dostanu šok.
{19468}{19531}Dobøe, ale co potom|mùeš dìlat?
{19585}{19636}Pouít zaklínadlo|bez ohledu na následky!
{19649}{19693}{Y:i}Zdroj veškeré síly...
{19855}{19948}Krvavı...oheò|jasnì záøící...!
{20050}{20085}Flare...
{20154}{20186}ARROW!
{20523}{20580}Ve srovnání s tím, co jsem|proila se svou starší sestrou...
{20580}{20631}...je tohle nic!
{20646}{20671}Jdeme, Gourry!
{20773}{20821}Ty máš sestru?
{20841}{20868}Ach, neøekla jsem ti o ní?
{20868}{20914}Jdeme! Jdeme! Jdeme!
{20953}{21014}Ti... Jak to udìlali?
{21203}{21236}O co se pokoušíš?
{21249}{21275}Pokouším se o TOHLE!
{21294}{21320}Flare...
{21543}{21569}Lino!
{21663}{21683}Promiòte!
{21834}{21854}Tady je!
{21873}{21923}- Dobøe, Lino. Nehıbej se!|- Poèkat, nemyslím, e-
{22184}{22236}Hmm... to nebylo zlé.
{22236}{22289}"Nebylo zlé" sakra!
{22294}{22354}Slyšel jsi slovo "jemnìjší"?!
{22401}{22458}Dobøe, ještì musíme|porazit ty dva!.
{22634}{22678}Èekáme tu na vás.
{22678}{22732}Nauèíme vás co je to vypsat|odmìnu na naše hlavy!
{22751}{22809}No to urèitì.
{22813}{22878}- Oh, mlè u!|- Nebudu bojovat s tebou, zlatíèko.
{22935}{23019}Proti tobì budu stát já.
{23038}{23114}Take pøedpokládám,|e já budu bojovat s tebou?
{23125}{23181}Myslím, e jsi to pochopil!
{23489}{23530}Slyšel jsem, e jsi docela dobrı.
{23530}{23586}Doufal jsem, e s tebou jednou|budu moct bojovat.
{23586}{23620}Dávej si pozor, kdy v nìco doufáš.
{23683}{23723}Flare Arrow!
{23770}{23818}Freeze Arrow!
{23919}{23978}A já si myslela, e jsi|jen nìjakı tøetitøídní mág.
{23982}{24024}Vypadá to, e pøeci|jen nìco víš!
{24024}{24089}Tak lehko ho neporazím.
{24100}{24146}Myslím, e tu mám|váného soupeøe.
{24160}{24240}Sleèno Lino, jak jste mohla?|Ze všech lidí, právì vy!
{24327}{24363}Na nì! Na nì!
{24376}{24416}Je èas, aby spravedlnost|znovu zakroèila!
{24644}{24714}Jsi první soupeø, kterı|mì škrábl.
{24730}{24793}Tos musel bojovat ze slabšími.
{24847}{24886}Ale hra skonèila!
{24978}{25016}Vyjící Meè!
{25379}{25421}C... Co to bylo?!
{25505}{25555}Démonickı Vyjící Meè!
{25555}{25633}Jeho síla dokáe|porazit kadého protivníka.
{25648}{25706}No dobøe. Já mám|také speciální meè.
{25790}{25827}Vyjdi, Svìtlo!
{25962}{26032}Ah... Meè Svìtla!
{26048}{26084}Mohlo by to bıt zábavné.
{26137}{26179}U to trvá pøíliš dlouho!
{26257}{26294}Lino Inverse,|nenapravitelnı zloèinèe!
{26343}{26385}Pokud budeš pokraèovat|v páchaní svıch zloèinù i nadále...
{26385}{26443}...pøiprav se na|souboj se mnou!
{26457}{26486}Amélie...
{26498}{26570}Pochopíš to u koneènì?!|ONI jsou ti zlí!
{26570}{26645}To všechno si o nás|vymysleli!
{26658}{26750}Co? Ale... Ale oni|øíkali, e VY jste ti zlí!
{26767}{26869}Amélie, pøemıšlej! Kdo z nás vypadá|jako zloduch?! Dobøe se podívej.
{26999}{27023}Oba.
{27028}{27055}AMÉLIE!
{27085}{27155}Vy øíkáte to|a oni zase ono!
{27179}{27226}Freeze Arrow!
{27226}{27273}Flare Arrow!
{27273}{27353}Lina anebo Vrumugun?|Kdo z nich je opravdovı zloduch?
{27402}{27447}Jak bych to...?
{27447}{27511}Jasnì!|Spravedlnost vdy zvítìzí!
{27511}{27578}Take ten, kdo zvítìzí,|musí bıt ten dobrı!
{27586}{27662}{Y:i}Zdroj veškeré síly,|krvavı oheò jasnì záøící!
{27672}{27714}{Y:i}Nech se tvá síla|shromádí v mıch rukou!
{27722}{27751}Poèkej! Poèkej!
{27751}{27789}Fireball!
{28107}{28154}Amélie, ty jsi úplnì støelená!
{28167}{28223}Vìdìla jsem to!|Vy jste ta dobrá!
{28241}{28272}Vìdìla jsem, e nejste zlá!
{28284}{28337}Oh, já si pamatuji, e nìkdo|øíkal nìco jiného.
{28376}{28420}Hej, to byla bitka!
{28420}{28474}- Gourry!|- Ahoj, Lino.
{28486}{28504}Jsi v poøádku?
{28510}{28582}Pro dnešek staèí.|Ale urèitì se vrátím!
{28618}{28662}Myslím, e bychom|mìli jít do Sairaagu.
{28662}{28733}Pokud nezjistíme, kdo stojí za|tìmito lovci zloèincù...
{28733}{28775}...nikdy nebudeme vìdìt,|co se vlastnì stalo.
{28787}{28860}Co jsou zaè?|A po èem jdou?
{28860}{28890}Správnì!
{28907}{28938}Co? Amélie?!
{28953}{28988}Co tu dìláš?
{28988}{29073}Tahle bitka mi ukázala,e|se tu nìkde plíí zlo.
{29087}{29144}A e jde za vámi.
{29156}{29254}Proto, pocestuji s vámi|a znièím všechny ty ïábelské ambice!
{29267}{29350}Take budu znova cestovat|s vámi. Není to skvìlé?
{29350}{29433}Myslím, e jí to nedokáeme|vymluvit. Myslí to vánì!
{29439}{29514}Amélie, nesnaíš se náhodou vytratit|z mìsta...
{29524}{29589}...protoe Phil zjistil,|e za tu explozi mùeš ty?
{29620}{29669}Pojï sem, Amélie!
{29697}{29834}Jak mohla má vlastní dcera vyhodit|do vzduchu jednu z našich vìí?!
{29840}{29903}Jejky!|No tak, jdeme, jdeme!
{29910}{29951}Poèkej, já, uch... Amélie!
{29951}{29992}Musíme se odtud dostat!
{30007}{30026}Ach, no...
{30041}{30080}Vypadá to tak, e máme|nového spoleèníka na cestu!
{30102}{30166}Pìknì dlouho se nevracej!
{30166}{30226}Mìjte se!|Odcházíme do Sairaagu!
{30226}{30286}Braòte pevnost, dokud|se nevrátíme!
