{1}{1}23.976
{327}{381}Tam, kde se vyrojí monstra,|pøicházím, abych je znièila.
{389}{467}Tam, kde se zatøpytí poklady,|pøicházím, abych se jich zmocnila.
{467}{573}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2648}{2677}Nespravedlivì obvinìní a nyní mimo zákon...
{2677}{2705}...na naší cestì jen utíkáme a utíkáme.
{2705}{2777}Øíkat "Bijte tyhle hrdiny a pošlete je do Sairaagu!"...
{2782}{2833}...vùbec nepomohlo nezkušenım|dobrım samaritánùm jako jsme my.
{2833}{2881}Hrát brid bylo OK...
{2885}{2993}...ale všechny tyhle potíe|co nás potkaly byly opravdu bolestné!
{2993}{3067}Co!? Wrumugn?|Ty jsi ještì naivu?
{3067}{3141}Zangulus má své druhé vytrvalé já!
{3141}{3196}Mùe se nám stát snad nìco horšího?
{3196}{3250}No dobøe, teï nemáme èas na deprese!
{3250}{3298}Vzchop se Lino Inverse!
{3314}{3456}VÁŠEÒ!|Zasvìtíme své ivoty jevišti?
{3695}{3756}To je urèitì zas Linin aludek.
{3758}{3863}øíkal jsem, e jsme mìli pøepadnout|nìjaké bandity a obrat je jídlo.
{3863}{3949}Ale protoe tu nejsou ádní banditi,|tak jsme stále hladoví!
{3977}{4039}Co bys chtìl, Gourry?
{4041}{4095}Jít do mìsta a dát|se zabásnout?
{4096}{4145}No, ne tak úplnì...
{4161}{4220}Váš aludek je moná prázdnı,|ale vaše ústa nikdy.
{4223}{4256}Buï u zticha!
{4266}{4355}Oh, zapomeò na to. Nemùu se|ani hnout. Jsem pøíliš hladová.
{4386}{4439}- Ta vùnì!|- To mùe bıt jen...
{4442}{4490}JÍDLO!
{4547}{4574}Jasnì e je!
{4594}{4632}Dar z nebes!
{4634}{4698}Nebesa nikdy neopustí|ochránce spravedlnosti!
{4751}{4817}Hej! Nechte mi nìco!
{4970}{5022}Ale èí je tohle dušené maso?
{5052}{5106}Ale, tím se nezatìuj.
{5107}{5204}Amélie! Pøestaò vybírat|jenom maso!
{5338}{5395}Hele! To je naše jídlo!
{5396}{5436}He? Co jste zaè?!
{5484}{5529}Bylo to fakt dobré.
{5741}{5844}To jste byli TAK hladoví?|To jste museli mít pìknou smùlu!
{5846}{5888}No, i tak se to dá øíct.
{5890}{5980}Take vy "Herci z Rossburgu"|hrajete divadlo?
{5980}{6051}Jasnì. Hlavní mìsto|umìní, Mosquita...
{6054}{6139}...uspoøádala velkou|zábavnou soutì.
{6140}{6208}Take jedeme do|Mosquity.
{6214}{6252}Do Mosquity, co?
{6253}{6286}LIENA!
{6310}{6363}Liena! Kde je Liena?!
{6364}{6396}CO se dìje?
{6397}{6445}Liena zmizela!|Nevíš, kde je?
{6447}{6477}- Ne.|- Musela utéct.
{6479}{6573}Oh, ne! Co budeme dìlat?|To je u desátá!
{6578}{6614}Nemáme dost hercù!
{6615}{6692}Hercù?|Teï máme hercù dost!
{6702}{6756}Tady. Tady. Tady.
{6767}{6855}Prohlédnìte si scénáø. Zkouška|je odpoledne. A pøijïte vèas!
{6892}{6917}Coe?!
{6919}{6974}Je mi vás líto.
{6975}{7030}Padli jste øediteli do oka.
{7032}{7063}To je øeditel?
{7072}{7119}Ano. Pan Rossburg.
{7120}{7208}Buï je blázen do divadla|anebo jen blázen.
{7209}{7252}Take, zlomte vaz.
{7254}{7321}C...?! Hele!|Teï jsou z nás herci?!
{7336}{7396}Poèkat, moná je to dobrı nápad.
{7421}{7470}Co si to mumláš?
{7472}{7543}Kdy s tìmi herci pùjdem|a do Mosquity...
{7545}{7600}...dostanem se docela blízko Sairaagu.
{7600}{7624}Máš pravdu!
{7626}{7685}A nikdo nás|nepozná!
{7686}{7744}V ádném pøípadì! Co je tohle?!
{7746}{7776}Co se dìje?
{7779}{7819}Koukejte, koukejte!|Název hry!
{7830}{7901}Hmm...? "Dej nám|Spravedlivost a Mír:"
{7908}{7985}"Smrt odporné|zlodušky Liny Inverse."
{7986}{8065}Odporná zloduška|Lina Inverse?! Dej to sem!
{8067}{8161}Podívám se na to... "Zloèinná Lina|Inverse s ïábelskımi schopnostmi..."
{8163}{8210}"...zmìnila svìtovı mír|na chaos..."
{8211}{8259}"...a hrdina bojující za mír|a právo..."
{8260}{8307}"...povstal, aby|zmaøil její plány!"
{8308}{8419}"Do toho, stateènı hrdino! Rozdr|zlou Linu kladivem spravedlivosti?!"
{8419}{8459}CO TO JE ZA VTIP!
{8459}{8538}Já nejsem zloduch!|Na tohle si budu stìovat!
{8546}{8618}P-Poèkej, Lino! Ne tak rychle!
{8618}{8690}Kdy to udìláš, zjistí,|kdo jsme!
{8703}{8744}Ale...! Ale...!
{8751}{8821}Nejsem ádná odporná zloduška!
{8832}{8886}Je to jen hra. Jen hra.
{8891}{8957}Kdy se na to podíváte takhle|je to celkem zajímavé, ne?
{8963}{9032}"Bezcitnı zloduchu prosperující|ze zla na svìtì!"
{9035}{9118}"Teï pocítíš rychlost|meèe spravedlivosti!"
{9125}{9181}Promiò, ale fouklas|do mikrofonu.
{9185}{9225}Coe jsem?!
{9289}{9334}Pane Rossburgu.
{9334}{9378}Pojïte se mnou.
{9409}{9472}Doufám, e nás neodhalil?
{9477}{9521}Coe?! Super!
{9578}{9633}J- Já budu hvìzda?!
{9658}{9689}Fantastické...
{9692}{9757}Hm! Mám ji vzít, anebo ne?
{9759}{9813}Co?! To mi nemùete udìlat!|Hvìzda jsem tu já!
{9847}{9920}Kdy se tak na tebe dívám,|pøipomínáš mi mou mladší sestru.
{9929}{9955}Vaší sestru?
{9955}{10042}Ano, v dìtství jsme byli|rozdìleni.
{10049}{10119}Netuším, kde mùe bıt anebo|co dìlá.
{10119}{10157}Opravdu?
{10199}{10228}Kadı máme nìjakou minulost.
{10233}{10265}Le.
{10270}{10323}Náš reisér má|velkou fantazii.
{10337}{10400}Nerozezná hru|od reality.
{10420}{10505}Radši si dávejte pozor.|Neberte ho pøíliš vánì.
{10512}{10576}Sakra!|Tohle mi nemùete udìlat!
{10604}{10635}Za tohle mi nìkdo zaplatí!
{10645}{10687}A utíká nám další.
{10727}{10796}U chápu! To je|souèást mého osudu!
{10823}{10951}Já, Amélie, uctivì a|pokornì pøijímám tuhle roli!
{11038}{11090}Serala mu to všechno.
{11090}{11141}Tak, co mám dìlat já?
{11156}{11205}Nemùou jen tak ignorovat|takovou krásku, jako jsem já.
{11205}{11271}Ty na ni árlíš,|co?
{11303}{11365}Vy dva budete hrát tohle.|Vkládám do vás velké nadìje!
{11382}{11421}Nevím, co to je,|ale beru to!
{11426}{11446}No, no...
{11446}{11494}Dobøe, take znovu od|zaèátku!
{11498}{11576}Jsem Lina,|ztìlesnìní zla!
{11581}{11626}Zdroj neštìstí!
{11635}{11711}Zloèinná Lina, která|pøináší strach a zkázu svìta!
{11723}{11785}Vylez, mùj poslušnı draku!
{11795}{11867}- Gourry, špatná noha!|- Dìláš to špatnì!
{11883}{11936}- Co dìláš?!|- V poøádku, v poøádku!
{11940}{11988}Ne, ta druhá noha!|Druhá noha!
{11993}{12022}Stop! Stop!|Stop! Stop!
{12045}{12096}Musíte se vít do|své role!
{12103}{12155}A navíc, draci|mají vydechovat oheò!
{12165}{12259}Jak to mám udìlat?!|A proè já hraji pøíšeru?!
{12296}{12336}Zkouška, start!
{12388}{12428}Lino Inverse,|ty zloèinnı ïáble!
{12433}{12511}Slunce záøící na nebesích ti|moná promine tvé zloèiny...
{12511}{12579}...ale já nikdy!
{12609}{12624}Miluji to.
{12640}{12697}Otravná hlupaèko!|Pojï ven, draku!
{12704}{12723}Grrrrr!
{12732}{12774}No tak, dìlej to jako já.
{12775}{12786}A teï, kráèej vpøed!
{12805}{12859}- Pøestaò mì obviòovat!|- Buï u ticho!
{12873}{12943}Teï pocítíš rychlost|meèe spravedlivosti!
{13005}{13023}Au!
{13028}{13089}Stop! Tohle má bıt souboj!
{13094}{13151}Realisticky!|Musíte bıt pøesvìdèiví!
{13156}{13187}Takhle!
{13214}{13275}Hej, neutíkej!|Tohle není scéna s honièkou!
{13405}{13466}Zabila jsem draka!
{13480}{13535}Nemùe si stìovat.|Byli jsme perfektní!
{13545}{13594}Akorát e tam není|ádné "oompf!"
{13603}{13677}To, co tahle hra potøebuje,|je malé oivení!
{13752}{13819}- Ne, pøestaò!|- Zastavte ho nìkdo!
{13882}{13920}On to myslel vánì.
{13935}{13973}Hele, chceš mì zabít, èi co?!
{14069}{14098}Zangulusi, poèkej!
{14111}{14177}Nepracuji pro tebe.
{14189}{14231}Dìlám to, co sám chci.
{14231}{14307}Musíme je dostat ivé.|Je to jasné?
{14688}{14746}Nechci hrát draka!
{14792}{14851}Stop! Stop!|Stop! Stop!
{14851}{14899}Tohle je podle tebe herectví?!
{14929}{14980}U DOST!
{15069}{15152}Ne... Nemùe takhle|dál pokraèovat!
{15178}{15233}Co, vy dva?!
{15265}{15306}Oni se u do toho vili...
{15317}{15404}No tak, zbavme se tohohle|dobu a pojïme do Sairaagu!
{15417}{15469}Ale kdy tahle práce je tak lehká!
{15473}{15514}Máme kopec jídla,|a navíc...
{15530}{15576}U jsem si na nì zvykl!
{15581}{15632}No dobøe. A ty, Amélie?
{15710}{15775}Našla jsem svoje skuteèné poslání.
{15807}{15835}No super.
{15979}{16096}Jsou v tom mìstì, co?|Ti tøi, co ti ukradli roli?
{16102}{16141}A-Ano! Pøesnì tak!
{16160}{16199}Dobøe. Díky za pomoc.
{16216}{16251}Co? Hej, poèkejte! Puste mì!
{16258}{16344}Ale Mosquita je velké mìsto|plné vojákù.
{16354}{16395}Nemùeme tam jen tak vtrhnout|a zaèít bojovat!
{16401}{16473}Neboj se. Mám situaci|pevnì v rukou.
{16896}{16995}Proè máme tak|pošahaného øeditele?
{17164}{17221}Ty plakáty jsou všude!
{17267}{17281}Mìjte se!
{17286}{17322}Poèkej, dìvèe!
{17328}{17384}Já jsem jen trochu...
{17393}{17421}Nesvá.
{17451}{17503}Hele, co tu dìláš?!
{17508}{17560}Odpuste mé dceøi.
{17564}{17579}Coe?
{17579}{17657}Dceøi? Vùbec si nejste podobní.
{17811}{17850}Poøád s tebou jsou nìjaké potíe!
{17892}{17920}C-C-C-C...?!
{17924}{18019}Tvá ubohá mrtvá matka si o|tebe dìlá z nebe starosti!
{18051}{18127}Dceruško, já vím, e kráèíš|tìkou cestou.
{18135}{18218}Ale nemùeme po ní kráèet spolu?
{18220}{18229}Pojï, nech tì otec obejme!
{18237}{18398}Promiò, otèe! Je to...|Je to všechno jen moje chyba!
{18437}{18552}Odpus mi, otèe! Udìlám, co|øekneš a budu tvou dobrou dcerou!
{18558}{18628}Dobøe! Koneènì jsi pochopila!
{18629}{18664}Otèe, to bolí!
{18664}{18696}Dcerko...!
{18696}{18728}Otèe...!
{18739}{18807}Dobøe, dobøe!|Jen spolu dobøe vycházejte!
{18867}{18929}Dobrı trénink pøed vystoupením!
{18941}{19015}Dobrá práce!|Ale skuteèná hereèka z tebe nebude!
{19027}{19082}Vy víte, kdo jsem, e?
{19082}{19138}Proè jste mi pomohl?
{19151}{19199}Nezáleí na tom,|kdo si.
{19204}{19267}Jsi jedna z mıch|drahıch hereèek!
{19284}{19333}Hmpf! No dobøe...
{19333}{19407}Ale i tak jsi to zahrála celkem dobøe.
{19413}{19476}Bylo to, jako by znovu|oila moje mrtvá dcera.
{19488}{19584}Aha, tak teï je to mrtvá dcera?|Tak dobøe,...
{19584}{19649}...e by to byla pravda?
{19649}{19697}D-Dost!
{19710}{19747}Vystoupení zaèíná.
{19870}{19891}Dobøe, pojïme!
{20207}{20257}Kde je zase sleèna Lina?
{20257}{20307}- Promiòte!|- Jdeš dlouho!
{20315}{20377}Dobøe, lidièky!|Jste pøipravení?!
{20377}{20439}Jo!
{20439}{20480}V poøádku, vytáhnìte oponu!
{20595}{20673}Slunce záøící na nebesích ti|moná promine tvé zloèiny...
{20673}{20730}...ale já nikdy!
{20746}{20857}Otravné dìcko!|Uka se, draku!
{20920}{20981}GRRRRR!
{21205}{21290}Ach, další zvíøecí kostımy.|Vıbornı nápad.
{21341}{21384}Kdo je to?
{21384}{21426}Mnì se neptej.
{21475}{21576}Stateèná hrdinko, pøišla jsem|ti pomoci zabít tuto zlodušku!
{21583}{21639}Coe?|Kdo mi to kazí hru?!
{21656}{21713}Nevím, kdo z vás je kdo...
{21713}{21769}...ale na nì, chlapci!
{21847}{21894}P-P-P-P-Poèkat!
{21944}{21972}Opravdovı meè!
{21990}{22027}Jen klid!
{22043}{22083}O tom mi nic neøekli!
{22089}{22129}Nezašlo to pøíliš daleko!?
{22493}{22531}Pøestaòte, nebo-
{22538}{22572}Raketovı Kop!
{22618}{22654}Jste OK, strıèku?
{22672}{22744}K èertu! Nevím, kdo to je,|ale jdou po nás!
{22744}{22816}Kdy zpùsobíme problémy,|pøilákáme sem stráe!
{22816}{22849}Vy idioti!
{22849}{22897}Hra!|Co bude s mou hrou?!
{22897}{22967}Odejít uprostøed pøedstavení!|Jste nejhorší herci všech dob!
{22967}{23019}No poèkat, v prùbìhu hry-
{23024}{23076}To je ono!|Budeme pokraèovat!
{23076}{23128}Co to meleš?|Tenhle souboj je-
{23138}{23218}To je hra, a nikdo si|nedovolí pøerušit hru.
{23233}{23268}Správnì! To je ono!
{23350}{23377}Pøestaòte!
{23412}{23450}Zase ty.
{23460}{23519}Asi zaènu tímto dìvèetem!
{23519}{23564}Ale já jsem spojenec spravedlnosti!
{23619}{23655}Neobvyklá hra.
{23663}{23706}Nemùu øíct,|jak to bude pokraèovat.
{24018}{24085}Sleèno Lino! Pane Gourry!
{24085}{24152}Koneènì jste se objevili!
{24161}{24194}Zangulus!
{24256}{24319}Koneènì se ukázal!|Ïábelskı Král, Zangulus!
{24333}{24367}Co? Ïábelskı Král?!
{24380}{24462}Tvá zlá kouzla zmìnili nás,|svaté bojovníky, v draka!
{24468}{24523}Ovládajíc nás,|vylákal jsi sem..
{24523}{24582}...tuto stateènou hrdinku,|abys ji zabil!
{24597}{24654}- Oh, nová zápletka!|- Jeden zvrat za druhım.
{24668}{24736}Ale teï, kdy jsme získali|spìt svou pùvodní podobu...
{24736}{24795}...se tvùj zloèinnı plán konèí!
{24870}{24941}Hej, Svatı Bojovníku Gourry!|Øekni nìco!
{24944}{24994}Já?! Umm...
{25002}{25071}T-T-Teï budeš èelit|vlastní zkáze, Zangulusi!
{25084}{25118}Je tak rozkošnı!
{25149}{25232}Publikum je miluje!|Kradou mou show!
{25267}{25313}Dost bylo øeèí!
{25317}{25409}Je èas spojit své síly|a znièit opravdové zloduchy!
{25415}{25463}- Pojïme!|- Správnì!
{25492}{25514}Vıborná hra!
{25528}{25607}Znièit mì?!|Nejdøív porazíme my vás!
{25615}{25627}Jdeme!
{25829}{25917}Vidíš?! Sila spravedlivosti|je na naší stranì!
{25934}{25966}Je to TAK zahanbující.
{25986}{26035}Bravo! Vynikající pøedstavení!
{26039}{26064}Líbí se jim to...
{26094}{26139}Skonèeme s tou fraškou!
{26244}{26317}No teda! Kolik je tìch hercù?!
{26348}{26394}Není fér pøivolat|si posily!
{26400}{26479}Udìlám cokoliv, abych|si to vyjasnil s Gourrym!
{26483}{26515}Jsi populární.
{26520}{26555}Chceš si to vymìnit?
{26653}{26698}Oh! Pùsobivé!
{26698}{26739}Prvotøídní speciální efekty.
{26815}{26849}Lino! Amélie!
{26908}{26967}Ty bojuješ se mnou!
{27062}{27100}Pøestaòte!
{27124}{27171}Vypadá to skoro jako opravdová kouzla!
{27177}{27214}Amélie, jdeme!
{27222}{27251}Stùj.
{27298}{27318}Vrumugun!
{27348}{27424}Vìdìl jsem, e se na|Zanguluse nedá spolehnout.
{27494}{27528}Boost Bolt!
{27590}{27617}Kdy ty tak...
{27645}{27690}Freeze...
{27723}{27763}...Arrow!
{27937}{28040}Zbyteèné. A pokud nechceš vyhodit|do vzduchu všechny okolo...
{28044}{28105}...nemùeš pouít|svùj Dragon Slave.
{28105}{28132}He?
{28228}{28250}Díky!
{28268}{28292}K èertu...
{28310}{28357}Fireball!
{28388}{28420}Oh, ne...
{28499}{28551}No teda! Vypadá to, jakoby|ho skuteènì zabili!
{28551}{28572}Úasné!
{28577}{28618}Oni to myslí vánì!
{28618}{28649}Utíkejte!
{28766}{28836}Aha, karta se obrátila!
{28836}{28906}Dobøe! To je dnes|všechno!
{28906}{28956}Diem Wing!
{28956}{29011}Ještì se potkáme!
{29062}{29139}Druhoøadé postavy by mìli zmizet|ze scény, kdy dohráli!
{29147}{29202}Tahle bitva skonèila...
{29202}{29258}...a tøi bojovníci|spojili své síly!
{29258}{29328}Ale dokud nebude poraenı|ten opravdovı zloduch Zangulus...
{29328}{29371}...válka nikdy neskonèí!
{29436}{29481}Vynikající pøedstavení!
{29481}{29560}A zakomponovat do hry i|diváky byl vynikající nápad!
{29565}{29619}Nedokáu rozlišit, zda to|byla hra anebo opravdová bitka!
{29619}{29693}Myslím, e máme|letošního vítìze.
{29707}{29788}Ano, líbilo se jim to!|Líbilo!
{29788}{29851}Muselo se to líbit!|Ti mladí jsou vynikající herci!
{29889}{29940}Ale i tak jste si zabrala|celé pøedstavení pro sebe, sleèno Lino!
{29940}{29971}Pøirozenì. Pøirozenì.
{29977}{30076}- Lino, sejdeme se pozdìji.|- He?
{30076}{30106}Myslím, e mùeme vylepšit|naši roli draka.
{30113}{30161}- Pomùeš mi?|- Pomo si sám.
{30169}{30315}Mám to dìlat sám?!|Grrr! Grrr!
