{1}{1}23.976
{323}{381}Tam kde se vyrojí monstra,|objevím se, abych je znièila!
{383}{459}Tam kde se zatøpytí poklady,|pøicházím, abych se jich zmocnila!
{462}{567}A tam kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{641}{727}A je vítr ve tváøi...
{728}{786}...jakkoli silnı...
{793}{879}...staèí jedno kouzlo...
{881}{945}...a hned zrychlím krok!
{946}{1032}A mi sílu závidí...
{1033}{1097}...a na krásu árlí.
{1098}{1184}Pøed soupeøi neváhám...
{1185}{1256}...pláš mi vlaje ve vìtru.
{1257}{1335}Chci dìlat to i ono.
{1336}{1400}Bıt dìvèetem.
{1401}{1479}Chybnı krok však peklo znaèí.
{1482}{1569}Proto cestu mi nezkøi!
{1593}{1681}Tak daleko, jak jen chci...
{1683}{1761}...v cestì pokraèovat budu.
{1770}{1823}Smutné dni...
{1824}{1890}...úsmìvem pøekonám.
{1897}{1982}Daleko, v objetí magie...
{1983}{2069}...za hranicemi všedního dne.
{2072}{2126}Vejít do snu...
{2129}{2239}...a pokraèovat.
{2240}{2316}Bez hranic...
{2317}{2440}Nevzdávej se, zkus to znova.
{3229}{3270}Velmi pùsobivé, Flagoone.
{3270}{3297}Dokonce i kdy|ovládám takovou sílu...
{3298}{3390}...dokáeš odolat|mému jednoduchému útoku.
{3571}{3670}PORÁKA!|Vítìzství je vdycky mé!
{4087}{4137}Snaí se tohle místo|vyhodit do vzduchu!
{4163}{4209}Dìlá si, co chce!
{4281}{4356}Neexistuje ádnı zpùsob,|jak ho zabít?
{4356}{4378}ádnı!
{4396}{4470}Kouzla neúèinkují a Meè Svìtla|nám taky nebude moc platnı.
{4484}{4558}Jsme úplnì bezmocní.
{4575}{4602}No jasnì...
{4616}{4647}Co to blábolíte?!
{4669}{4758}Poslouchejte, dìcka! Nemùeme se|jen tak vzdát bez boje?!
{4758}{4785}Ph- Phile!
{4799}{4879}No tak nefungují kouzla!|A nefunguje ani Meè Svìtla!
{4879}{4921}To není problém!
{4933}{5015}Ale pokud se nevzdáme,|èasem najdeme nìjaké øešení!
{5021}{5085}Pøesnì tak!|Pane Gourry! Pane Zelgadisi!
{5101}{5162}Kdy se nevzdáme,|spravedlnost nakonec urèitì zvítìzí!
{5173}{5264}No, take mám jen|zatnout pìst a øíct...
{5277}{5349}"Vıbornì!|Pusme se zas do Reza!"
{5349}{5402}To po mnì chcete?
{5440}{5479}Oh, vy nás|asi neberete vánì!
{5479}{5551}Pøesnì tak.|Neøíkám, e bychom se mìli vzdát...
{5551}{5640}...ale kdy nefungují kouzla,|ani meèe, tak nemùeme bojovat.
{5660}{5711}Kdy by tu byla Lina,|mohla by vyèarovat kouzlo...
{5723}{5817}...na zvıšení úèinnosti Meèe Svìtla.
{5849}{5927}Máš pravdu! A já jsem si myslel,|e máš mozek medùzy!
{5927}{6007}Ne, já jen e,|kdy ho minule zakouzlila...
{6007}{6064}...získal neuvìøitelnou sílu.
{6069}{6111}- Mohlo by to fungovat.|- Ano!
{6111}{6161}Ale Lina tu není.
{6194}{6271}Zdá se, e teorii nechápe.
{6292}{6324}Dobøe, jdeme pane Gourry!
{6324}{6348}Huh? A kam?
{6356}{6399}Tak pojïte!
{6422}{6488}Úha, poèkat!|Udìlal jsem nìco špatnì?
{6488}{6537}Ne, nìco fantastického!
{6572}{6634}No, tak by se mìli|mladí mui chovat!
{6876}{6969}Poèkejte na mnì! Ne, e udìláte|nìjakou šílenost, ne se k vám dostanu!
{6997}{7036}Vezmu to zkratkou!
{7051}{7083}Damu Bras!
{7149}{7175}Super!
{7175}{7294}Sleèno Lino,|co kdy to zavalí tunel?
{7298}{7326}Na takové obavy nemáme èas!
{7353}{7371}Ale...
{7371}{7445}A taky nemáme èas na ádné ALE!|Jasné!
{7468}{7498}Bì! Bì! Bì!
{7522}{7567}A další!
{7916}{8023}Pryè s tebou! Všechno,|co mi stojí v cestì, bude znièeno!
{8101}{8170}ivotní prostøedí bychom mìli|chránit, Falešnı Pane Rezo.
{8529}{8600}No, tak jste nakonec vylezli.
{8617}{8680}Škoda, e u nejste k nièemu!
{8699}{8785}To neøíkejte,|dokud nás neporazíte!
{8785}{8871}Um, stále v tom nemám dost jasno.
{8871}{8901}Oh...!
{8911}{9009}Mladá dámo,|ukazovat prstem je neslušné.
{9059}{9115}- U jde!|- Toho budeš litovat!
{9201}{9246}Obranu pøenechejte mnì!
{9407}{9457}Balus Wall!
{9576}{9608}Jdeme Gourry!
{9608}{9640}Uka se, Svìtlo!
{9660}{9708}Elmekia Flame!
{9857}{9906}Na nìj, pane Gourry!
{10300}{10340}Nemìlo to ádnı úèinek?!
{10343}{10383}Ale mìlo!
{10637}{10676}Gourry! Znovu!
{10692}{10709}Pøipraven!
{10728}{10769}Tak to tedy ne!
{10995}{11033}Nezapomínej na mnì!
{11033}{11131}Améliin super speciální útok!
{11196}{11235}RA TILT!
{11353}{11413}To je Ra Tilt?! Taková síla!
{11667}{11730}A úder pùvabu:|Úder Pacifisty!
{11792}{11822}Amélie!
{11822}{11878}To opravdu bolelo!
{11878}{11985}Buï opatrná! Hej, není nic hanebnìjšího,|ne udeøit dìvèe do tváøe!
{11985}{12086}Ne! Uèil jsem drzé dìcko|základùm chování!
{12086}{12140}Ale vedli jste si dobøe.
{12140}{12242}Kdy bych nebyl spojen se Zanaffarem,|mohli jste mne i zabít!
{12242}{12288}Tím chci øíct...
{12319}{12395}...e se vás všech teï zbavím!
{12496}{12536}Štít! Rychle!
{12562}{12623}Dovol! Za tebou!
{12784}{12808}Lino!
{12828}{12923}No, kdy u jsem koneènì tady, tak bych ti radila,|abys se zaèal chovat!
{12941}{13017}To není fér, sleèno Lino!|To je moje fráze!
{13071}{13102}A tohle taky!
{13120}{13160}Nikdy se nevzdáváš.
{13160}{13234}Tak, koneènì jsi se ukázala,|Lino Inverse.
{13239}{13315}Rozhodla jsi se u vyzkoušet|na mì ten Giga Slave?
{13315}{13354}Kdo ví?
{13412}{13456}Chytej, Lino!
{13477}{13513}Dáváš mi ho?!
{13517}{13579}Ne, ty hloupá!|Abys ho mohla zabít!
{13579}{13627}Oh, tak potom ho nepotøebuji.
{13653}{13700}Takhle zacházíš|s mım rodinnım pokladem?!
{13700}{13755}Ta vìc, kterou pouiji...
{13791}{13841}...bude TENTO meè!
{13907}{14021}Tak, u si se pøipravil na nejhorší?|Protoe teï si to vyjasníme!
{14036}{14160}Oh? A co chceš udìlat|s takovou hraèkou?
{14180}{14230}Tak se podíváme, zda je to jen hraèka...
{14512}{14571}- Lino!|- Poslouchejte, tady je plán:
{14591}{14655}Pouiji tento meè, abych se|dostala pøes Zanaffarùv štít.
{14673}{14735}Zele a Amélie, a to udìlám,|zasáhnete ho astrálním kouzlem!
{14735}{14774}Dobøe! Spolehni se!
{14774}{14836}Gourry, pouij Meè Svìtla,|abys znásobil úèinek kouzla!
{14836}{14856}Dobøe!
{14856}{14962}Potom zaujmìte formaci|a tlaète Reza k Flagoonu. Jasné?!
{14962}{14985}Jasné!
{14999}{15104}Tato Posvátná Èepel a svatı strom Flagoon,|jsou klíèe k vítìzství!
{15222}{15302}Mám velkou radost,|e to berete vánì!
{15302}{15337}Jdeme!
{15421}{15452}Gos Vlow!
{15566}{15603}Elmekia Lance!
{15714}{15735}To bolelo!
{15737}{15777}Gourry, èelnı útok!
{15777}{15811}Jasné!
{15925}{15975}Blam Blazer!
{15998}{16041}Blam Blazer!
{16637}{16718}Útoèí úplnì jinak,|ne pøedtím.
{16756}{16814}Je to kvùli ní?
{17380}{17429}Zaèni se modlit, falešnı Rezo!
{17436}{17523}Ne! Nedovolím,|abyste mì porazili!
{17523}{17616}Je to dùvod mé existence!
{17616}{17693}Jedinì já mohu nakládat se svım ivotem!
{17838}{17896}Vysokorychlostní kouzlo! Rozptylte se!
{18094}{18128}Postarám se o obranu!
{18183}{18264}Pouívá tøi ústa k vyvolání|tøí rùznıch kouzel souèasnì!
{18285}{18334}Urèitì je to proto,|e je srostlı s tím Monstrem!
{18358}{18436}Teï u víme, proè je jeho|magická kapacita tak obrovská!
{18456}{18517}Monstrum...|To bychom mohli vyuít.
{18518}{18584}Zele! Gourry! Poslední rozkazy!
{18650}{18687}Ray Wing!
{18780}{18815}Neuteèeš!
{19067}{19148}"Zdroj veškeré síly,|která pøebıvá ve vìènosti i nekoneènu!"
{19151}{19207}"Vdy planoucí modrı plamen!"
{19232}{19287}"Nech síla|ukrytá v mé duši..."
{19287}{19359}"...pøedstoupí pøede mne z øíše nekoneèna!"
{19359}{19406}RA TILT!
{20600}{20693}Ne... Nemoné!|NEMONÉ!
{20725}{20834}Proè jsi nás vyzval|k tomuto souboji?
{20834}{20918}Nejsem si moc jistá proè.
{20963}{21051}Ale vím, e|jsi udìlal dvì chyby.
{21056}{21204}Za prvé, ublíil jsi mnohım lidem,|abys dosáhl svého cíle.
{21243}{21277}A za druhé, e...
{21277}{21358}...sis se mnou vùbec zaèínal!
{21374}{21411}Teï, Sylphiel!
{21411}{21452}Dobøe!
{21486}{21525}"Posvátná, pokorná ruka Boí!"
{21525}{21587}"Dech naší Matky Zemì!"
{21658}{21750}Pøevıším i pùvodního Reza!|Ne, já jsem ho U pøevıšil!
{21750}{21831}Není to tak? NENÍ TO TAK?!
{21914}{21987}"Modlím se k tobì, abys pøedstoupil!"
{21987}{22069}"Uka své velké slitování|tìmto osobám a udìl jim pokoj!"
{22069}{22114}OBNOVA!
{22356}{22422}Pouila kouzlo obnovy|na Flagoon?!
{22620}{22699}Pøesnì tak, Zele. Kdy teï Flagoon znovu ije...
{22699}{22751}...on a Poehnaná Èepel...
{22751}{22821}...z Reza vysají Zanaffarovu duši.
{23747}{23789}Já...
{23851}{23902}...prohrál jsem, e...?
{23943}{23966}Ano.
{23971}{24034}Proè jsem prohrál?
{24034}{24140}Bylo to proto, e kopie|bude vdy jen kopií?
{24159}{24282}Ne... prohrál jsi|z jiného dùvodu.
{24301}{24380}Nevidìl jsi|co je pøed tebou.
{24387}{24454}Co se stane,|kdy pøevıšíš svùj originál.
{24454}{24509}Rozumím...
{24573}{24690}Vdy jsem vidìl|jen Rezova záda.
{24690}{24763}Proklínal jsem svého tvùrce, u jen proto,|e jsem byl jeho kopie.
{24763}{24828}Jediné, pro co jsem il, bylo,|abych ho pøevıšil.
{24828}{24972}A proto jsem nikdy nemohl...
{25042}{25126}Prosím, povìz mi|aspoò jednu vìc...
{25161}{25209}Co vidíš ty?
{25220}{25316}Co vidíš, kdy se|zahledíš kupøedu?
{25339}{25431}Co vidím? Kvìtinu,|její jméno ještì neznám.
{25492}{25550}Jaké jméno máme dát|na tvùj náhrobek?
{25600}{25653}Nechci ádnı pomník.
{25680}{25820}Ale, kdyby to bylo moné,|rád bych byl pochovanı pod Flagoonem.
{25869}{26029}Ten strom...|bude... mım pomníkem...
{26619}{26680}Pracky pryè! To je moje kuøe!
{26680}{26727}No tak! Pøestaò!
{26740}{26777}Ty nebudeš jíst?
{26781}{26847}Oh, n-n-ne, dìkuji.|Budu jen pøihlíet.
{26873}{26919}No, tak v tom pøípadì|na mì zbude víc!
{26930}{26950}Tak, tak!
{27036}{27131}Um, no, mimochodem,|co budete teï všichni dìlat?
{27155}{27196}Nad tím jsme ještì nepøemıšleli!
{27196}{27234}A co ty?
{27234}{27348}Já...? Nejspíš pomùu|s budováním našeho nového mìsta.
{27351}{27402}A vy, pane Zelgadisi?
{27402}{27554}Ne jsem si jistı... Stále musím najít zpùsob,|jak vrátit své tìlo do normální podoby.
{27573}{27668}Tak proè nejít se mnou|zpátky do Seyruunu?
{27668}{27725}Urèitì se nám podaøí|najít zpùsob, jak vám pomoct!
{27725}{27778}S tebou, ech?
{27828}{27882}Otèe! Tady jsme!
{27882}{27928}Oh, Amélie!
{27928}{28013}Hej, nanicovatı Phile!|U je to s tvou nohou lepší?
{28013}{28092}Oh, je to fajn.|Podívejte.
{28099}{28205}Otec sleèny Amélie?|To znamená...? To znamená...?
{28205}{28262}Oh, jasnì!|Ty to ještì nevíš, e?
{28262}{28331}Je mi ctí, e vám mùu|pøedstavit jeho vısost...
{28331}{28398}...korunního prince Seyruunu:|Philionel el de Seyruun.
{28404}{28498}Jinımi slovy, momentálního|prince Seyruunu.
{28510}{28548}Prince?
{28569}{28617}Princové jezdí|na bílıch koních...
{28617}{28683}...a jsou to moudøí|a vzdìlaní intelektuálové!
{28699}{28743}Realita nikdy není tak sladká.
{28749}{28796}Tenhle chlap je...
{28877}{28913}...princ?!
{28938}{29001}Ach, boe. Ten šok byl pro|ni asi trochu pøíliš.
{29001}{29062}Pøestaò naznaèovat,|e mùj otec je monstrum!
{29062}{29123}Ale to chci po tobì|asi trochu pøíliš...
{29448}{29526}Pøekrásná a stylová...
{29527}{29605}Chybièku na mì nenajdeš.
{29605}{29692}Prvotøídní úsmìv...
{29700}{29777}Kulaté oèi,|je to snad høích?
{29797}{29873}I kdy to obèas nejde...
{29873}{29949}...staèí smutná tváø...
{29949}{30026}...a hned všichni zapomenou.
{30026}{30139}To je mùj šarm.
{30165}{30245}Nikdy to nevzdám! Moje srdce.
{30245}{30324}Vdy štìstí se zítra vrátí.
{30340}{30410}Nikdy to nevzdám! Moje srdce!
{30427}{30486}Srdce pøeplnìné nadìjí.
{30486}{30580}Nepodlehnu a nenechám ho odejít.
{30580}{30662}Rozhodnutá následovat...
{30663}{30745}...svùj nekoneènı sen.
{30745}{30876}S klidem v duši, tak to má bıt!
