{1}{1}23.976
{331}{383}Tam, kde se vyrojí monstra,|objevím se, abych je znièila.
{396}{465}Tam, kde se zatøpytí poklady,|pøicházím, abych se jich zmocnila.
{465}{573}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2585}{2618}Lina Inverse je tu.
{2618}{2705}Nemyslela jsem, e se vlámeme do Rezovi laboratoøe za pokladem...
{2705}{2772}...ale museli jsme sestupovat po miliónech schodù.
{2772}{2817}Kdo vymyslel tak podivnou pevnost?
{2817}{2890}Pak jsme se potkali s domovníkem, monstrem jménem Tiiba...
{2902}{2977}...pøed tím ne jsme se dostali do nejhlubší místnosti.
{2988}{3056}Ale která z vìcí je Rezovo dìdictví?
{3085}{3114}Zatímco jsme je zoufale hledali...
{3114}{3183}Tiiba znovuzískal svou plnou sílu a zaútoèil na nás!
{3183}{3252}Nechtìla jsem bıt poraena nìjakou stupidní slepicí!
{3252}{3311}A pak, nenadále, podivná deska s...
{3311}{3368}...mocnou magickou silou padla do mıch rukou.
{3368}{3459}Mohlo to bıt...? Nádhera!|Našla jsem Rezovo dìdictví!
{3459}{3569}Ale mezitím co jsme oslavovali,|se ukázala Eris a vyrvala nám ji!
{3569}{3644}Hej, vy dva!|Zlodìjství není fér!
{3664}{3705}Nakonec je má!
{3734}{3798}Dìdictví pána Reza...|Rukopis bible Claire!
{3973}{4043}Dìdictví pána Reza je mé!
{4264}{4405}VAROVÁNÍ|Erisin hnìv!
{4558}{4648}Hej! Já jsem to našla první!|Vra to!
{4673}{4711}Vrátit?!
{4725}{4835}Nebuï smìšná. Rezo to tu|nenechal pro vás.
{4853}{4916}Nemìlo by se to vrátit|pùvodnímu vlastníkovi?
{4931}{4976}Moná... Tak dobøe!
{4976}{5028}Ale jen kdy ten za tebou je|skuteènı Rezo!
{5059}{5139}Hm? Co tím naznaèuješ?
{5208}{5260}Burst Rondo!
{5277}{5311}Ztrácíš èas!
{5895}{5960}Od té doby co jsme se vidìli|naposled ti nìco pøibylo.
{5960}{6029}Ten drahokam ti sluší...|REZOVA KOPIE!
{6106}{6167}Svımi magickımi pokusy|jsi vytvoøila víc kopií...
{6168}{6229}...a vloila do nich drahokamy,|které je kontrolují.
{6237}{6284}Není to zlé na tøetitøídní|èarodìjnici...
{6284}{6335}...která nic nedokáe sama!
{6335}{6395}Jene, kopie zùstane|vdycky kopií.
{6414}{6469}Nefungoval, tak jak jsi chtìla.
{6521}{6603}A tak, abys vytvoøila|dokonalou kopii...
{6603}{6678}...chtìla jsi najít Rezovo dìdictví.
{6678}{6753}A aby jsi zlomila|ochranu laboratoøe...
{6753}{6829}...potøebovala jsi Meè Svìtla.
{6849}{6895}Je to tak, e?
{6902}{7013}Aha, chápu! Tak proto|šel Zangulus poøád po mnì!
{7027}{7050}NO KONEÈNÌ.
{7059}{7165}A my jsme zlomili ochranu|laboratoøe za tebe.
{7165}{7237}Není to tak,|ty velká panenko?!
{7445}{7537}Bod pro tebe za|správnou dedukci, ale...
{7540}{7646}...kdy to teï víš,|co tím udìláte?
{7646}{7704}Vezmu si svou pomstu!
{7704}{7761}Nedovolím ti vlastnit tu desku!
{7880}{7965}Ještì stále jste nepochopili|sílu této desky!
{8102}{8164}Sleèno Lino!|Sleèno Lino, vstávejte!
{8164}{8205}Co budeme dìlat?!
{8255}{8330}Tato magie byla vytvoøená proti|Temnému Pánu Shabranigdovi!
{8330}{8399}Opravdu jste si mysleli,|e ji pøekonat bude lehké?!
{8579}{8645}Co...Co je to?
{8745}{8796}Zlá síla...
{8825}{8886}Eris! Kdy máš tu vìc...
{8886}{8948}...co s ní chceš dìlat?!
{8969}{9037}"Co" se ptáš?
{9182}{9248}Pouiji ji, abych|vás všechny zabila.
{9277}{9357}Dnes koneènì bude pán Rezo pomstìn!
{9367}{9466}Hej, poèkej! Tohle všechno|bylo jen kvùli pomstì?!
{9486}{9601}Jsem poslední z Rezovıch aèek,|pomsta je má povinnost!
{9601}{9669}To je jediné co chci udìlat.
{9813}{9946}V této laboratoøi jsme já|a pán Rezo zkoumali bílou magii.
{10131}{10207}Následovala jsem ho z|království do království...
{10209}{10260}...a pomáhala mu pøi|konání zázrakù.
{10262}{10363}Celou duší jsem se snaila|uèinit ho šastnım.
{10424}{10459}Jene...
{10478}{10525}Proè?! PROÈ?!
{10559}{10648}Proè...?|Proè se moje oèi neodevøou?
{10688}{10771}Proè musím ít uvìznìnı|v temnotì?!
{10887}{10949}Pán Rezo, obklopenı|vlastním zoufalstvím...
{10954}{11044}...a pološílenı, upnul se|na svou poslední nadìji...
{11044}{11117}...legendární|Kámen Mudrcù.
{11141}{11252}A tak... Opustil mì a|šel ho hledat.
{11282}{11322}A pak...!
{11507}{11572}Zcela zbyteèná záš.
{11581}{11603}Ticho!
{11605}{11690}Nemìní to nic na faktu,|e jste mi vzali pána Reza!
{11692}{11815}Nemùeš pochopit, jak jsem se|cítila, kdy jsem zjistila, e je mrtvı!
{11901}{11948}To u staèí.
{11971}{12027}S dìdictvím pána Reza...
{12028}{12115}A silou, kterou získám z|této desky...
{12117}{12169}Lino Inverse!
{12188}{12244}Zemøeš!
{12834}{12901}Ne... NE!
{12922}{12996}Nesmíš uvolnit sílu|té kamenné desky!
{13022}{13050}Levitation!
{13300}{13368}Rezo!|Tvùj protivník jsem já!
{13595}{13672}Jsi jen otravné zlo!
{13728}{13747}Eris!
{14066}{14158}Myslíš, e kdy jsme porazili|opravdového Reza, podlehneme kopii?!
{14181}{14272}Kdy tomu opravdu vìøíš,|mìl bys trochu pøemıšlet!
{14282}{14304}Coe?!
{14365}{14498}Není nikde psáno, e by|kopie nemohla pøekonat originál.
{14584}{14623}No tak!|Vstávej, Lino!
{14623}{14690}Prosím, sleèno Lino! Musíte|zastavit sílu té desky!
{14725}{14787}Co si myslíte, e zkouším udìlat?!
{14803}{14858}Rychle! Kdy se to nepodaøí,|stane se nìco strašného!
{14953}{14984}"Vzkøíšenı z|hlubin zemì!"
{14984}{15044}"Daruj sílu tomu,|kdo ti pøísahal vìrnost!"
{15094}{15145}DÉMONICKİ NETVORE ZANAFFARE!
{15145}{15195}- Coe?!|- Ne!
{15384}{15445}Démonickı netvor Zanaffar...!
{15817}{15907}Skuteènou mocí té desky|je vzkøíšení Zanaffara!
{16031}{16120}Netvora, kterı znièil|pradávnı Sairaag.
{16132}{16197}Zanaffar, jeho nekoneèné zlo|pøeilo v jeho prolité krvi...
{16197}{16275}...ještì dlouho potom, co|ho Rytíø Svìtla porazil!
{16444}{16542}Je moná silnìjší ne|Shabranigdo.
{16558}{16637}Myslíš si, e opravdu chceš|udìlat takovou vìc?!
{17549}{17623}Ach, ne! Kdy nìco neudìláme,|netvor znovu oije!
{17933}{17968}K èertu!
{17968}{18026}- Poèkej na mnì!|- Drahı Gourry!
{18026}{18066}He? He?
{18417}{18462}U zbıvá jen chvilka!
{18666}{18691}Co?!
{18692}{18737}Máš smùlu!
{18829}{18861}Jasné?
{18954}{18974}Jak?!
{18974}{19063}Tahle èelenka je speciální.|Tvé drahokamy pøes ni neproniknou.
{19114}{19194}No dobøe...|A co tohle?!
{19219}{19249}Zbyteènì ztrácíš èas!
{19310}{19344}Mono Bolt!
{19446}{19509}No, Eris, vzdej to.
{19509}{19572}Zachráníš si ivot.
{19627}{19685}Hele!|Co znamená to šilhání?!
{19696}{19735}Kdy to chceš takhle, tak-
{19834}{19898}Gourry! Co to má znamenat?!
{19928}{19990}Zabít...Linu...
{20033}{20080}ZABÍT!
{20161}{20249}Hej! Hej! Hej!|Pøestaò!
{20249}{20308}Ne, drahı Gourry!
{20362}{20444}No, mùou si chvíli spolu hrát.
{20487}{20548}A já mezitím...
{20802}{20876}Co se dìje?|U nemùeš?
{20914}{20969}Teï pochopíš.
{20969}{21073}Moná jsem jen kopie, ale|mám sílu originálu.
{21073}{21176}Vlastnì teï, kdy mám|i Zanaffarovu sílu...
{21177}{21264}...moje schopnosti daleko|pøekraèují schopnosti originálu!
{21350}{21381}To by staèilo!
{21396}{21419}Diem Wing!
{21548}{21605}Pøeber si vše dvakrát|a na mnì nezapomínej!
{21630}{21653}Dobøe.
{21684}{21767}Ale tìhle slov|budeš litovat.
{21767}{21859}Je èas ukázat vám|mou skuteènou sílu!
{22270}{22314}Co to tam dìlají?
{22314}{22371}Co ty...!
{22372}{22429}Musím zabít!
{22462}{22547}Teï je nejvhodnìjší okamik!|Sylphiel, jeden Flare Arrow, prosím.
{22547}{22613}Hm? Co?|Já? Urèitì?
{22613}{22633}Já to udìlám!
{22633}{22685}- Ty ne.|- Proè?!
{22685}{22737}Sylphiel, rychle!
{22774}{22820}Uff. Uhm...
{22860}{22914}Flare Arrow!
{23068}{23096}Promiò...
{23126}{23183}Vıbornì.|To bude staèit.
{23385}{23449}He? Co?!|Co se mi stalo?
{23449}{23498}Aha, tak PROTO.
{23498}{23570}Poèkat! Gourry...!
{23581}{23635}Hele, Lino!|Co tu dìláš?
{23649}{23686}"Hele, Lino"...
{23686}{23723}...MI NESTAÈÍ!
{23780}{23826}Vzdávám se! Vzdávám se!
{23826}{23884}Sleèno Lino, pøestaòte!|Na tohle nemáme èas!
{23902}{23926}He?
{23926}{23962}Podívejte!
{24141}{24187}Kdy se tam dostali?!
{24399}{24497}Ó ne! Netvor|se právì rodí!
{25620}{25639}To je...!
{25763}{25838}Z laboratoøe se stal|obrovskı magickı kruh!
{26688}{26753}Velkolepé! To je...
{26753}{26804}To je síla|Rezova dìdictví!
{26976}{27017}K èertu s tím!
{27017}{27059}U je pozdì!
{27120}{27203}Démonickı netvor se právì|zrodil, aby pomstil pána Reza!
{27315}{27372}To ne!
{27933}{28011}Obávám se, e tohle|je malé nedorozumìní.
{28011}{28088}Já jsem ten, kdo dal|Rezovi všechnu sílu.
{28088}{28170}Co znamená, e|jsi u zbyteèná.
{28221}{28300}Ne... Proè...?
{29273}{29312}- Coe?!|- To není moné!
{29317}{29384}Odpoèívej v pokoji, Eris.
{29384}{29489}Rezova pomsta se uskuteèní.|Jene...!
{29489}{29558}Uskuteèním ji já sám!
{29854}{29954}Nevìøím tomu! To, co jsme|povaovali jen za Rezovu kopii...
{29954}{30042}...se zmìnilo ve vlastního stvoøitele|ještì pøed Zanaffarovım zrozením!
{30162}{30233}Co se to tu vlastnì dìje?!
