{1}{1}23.976
{329}{383}Tam kde se vyrojí monstra,|pøicházím, abych je znièila.
{398}{466}Tam, kde se zatøpytí poklady,|objevím se, abych se jich zmocnila.
{466}{572}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2586}{2655}Tak jsme se nakonec dostali|dovnitø Rezovo laboratoøe.
{2655}{2736}A jsme jen krùèek od Rezova dìdictví!
{2750}{2816}No vdy jsme pìknì tvrdí.
{2816}{2867}No dostali vtrhli jsme do arény...
{2867}{2971}...a zjeili se nám vlasy, kdy Zangulus|pøedvádìl své triky v souboji s Gourrym!
{2971}{3026}Ale Gourry to skuteènì dokázal.
{3026}{3082}Porazil Zanguluse fér a poctivì!
{3082}{3139}Dobøe Gourry!|Byls dobrı!
{3139}{3194}Teï je to na nás!
{3194}{3248}Dáme se do toho naplno!
{3261}{3400}ŠPATNOST!|Ten, kdo zùstal pozadu!
{3821}{3890}Lino, jak je daleko ta laboratoø?!
{3890}{3932}Jak to mám vìdìt?!
{3946}{4022}Vstávej, musíme tam bıt|døív ne Rezo a Eris!
{4025}{4063}Ale u jsme tak hluboko!
{4085}{4157}Nenapadá mi co by|to Rezovo dìdictví mohlo bıt...
{4157}{4259}...ale kdy je to tak hluboko ukrytı,|musí to bıt nìco vzácného!
{4263}{4303}He? Co tím myslíš?
{4303}{4388}Pøi experimentech v magické|laboratoøi se mùe stát cokoli.
{4400}{4454}Proto je tak hluboko.
{4493}{4557}V pøípadì, e se|experiment vymkne z rukou...
{4557}{4639}...mùe bıt okolí chránìno.
{4663}{4694}Vymkne z rukou?
{4699}{4748}Obèas se to stane.
{4762}{4838}Ano. Jednou jsem takovou|laboratoø vidìla.
{4864}{4913}Úplnì na dnì bylo tìlo mága.
{4918}{4950}A nic jiného.
{4967}{5012}- Nic?|- Jo.
{5016}{5099}Chtìl to mít pìknì hluboko|a pøi stavbì zemøel vyèerpáním.
{5099}{5151}Tak to je fakt smùla.
{5321}{5382}Tady je to!|Tady je to! Tady je to!
{5438}{5484}Koneènì!|Nejhlubší komora!
{5542}{5626}- Vızdoba je opravdu nechutná.|- Máš pravdu.
{5626}{5709}Rezovo dìdictví musí|bıt v této místnosti.
{5783}{5847}- No, otevøu to.|- Dobøe.
{5984}{6029}Poklad!
{6050}{6076}Co je tam?!
{6128}{6185}- Další schody...|- Nikdy to neskonèí.
{6194}{6281}Co je to za nápady?!|Proè jsou tu ty dveøe?!
{6287}{6339}Protoe tohle místo postavil Rezo.
{6352}{6431}Mìli bychom se pøipravit|na takové hloupé vtipy.
{6431}{6504}Hmm, toto asi není|ta nejhlubší komora.
{6511}{6567}- Asi ne.|- Sleèno Lino, podívejte. Další dveøe.
{6628}{6678}Co teï? Které si vybereme?
{6716}{6801}Logicky by to byli ty,|které vedou dolù.
{6808}{6882}Na druhé stranì to|mùe bıt past!
{6883}{6921}Vdy tu mluvíme|o Rezovi.
{6923}{7067}Za kterımikoli dveømi|se mùe skrıvat smrt.
{7075}{7163}Ale já u mám dost|všech schodù!
{7672}{7725}S mou znalostí|vnitøku laboratoøe...
{7727}{7782}...nás nikdy nedokáí pøedbìhnout!
{7796}{7876}Já budu ta, kdo|získá dìdictví pana Reza!
{8075}{8142}Co se stane, kdy tam|bude další schodištì?
{8142}{8191}Zaènu bıt násilnická!
{8216}{8263}Vypadá to, e tu u|ádné schody nejsou.
{8263}{8319}V poøádku,|ovìøme si to!
{8479}{8530}Take to byla past!
{8530}{8565}Rychle!
{8793}{8843}Trochu dlouhá chodba, nemyslíte?
{8843}{8952}Tak velké podzemí a všechno|navrhoval jeden stavitel...
{8954}{9031}...take jen on ví, kde jsou|všechny ty pohodlné zkratky.
{9147}{9217}Och, teï u jsem naštvaná!|Kudy teï?!
{9218}{9244}Hele, klídek!
{9256}{9313}Jasnì!|Vy dvì jste knìky, ne?
{9314}{9367}Nemùete urèit, kudy|máme jít?!
{9369}{9419}No, to se lehko øekne, ale...
{9422}{9514}Nevím, zda to bude fungovat,|ale zkusím to.
{9862}{9901}Hmmm... to je opravdu váné.
{10063}{10115}Udìlala jsem nìco špatnì?
{10167}{10267}Promiòte. Jen jsem si|vzpomnìla na otce.
{10284}{10364}Otec mi dal tohle ezlo.
{10381}{10485}Modlila jsem se k nìmu,|aby mi dal silu.
{10502}{10571}Oh, sleèno Sylphiel!|Ubohá!
{10626}{10673}Pff... beznadìjné!
{10683}{10740}Dobøe, zkusíme to ještì jednou.
{10847}{10913}Cítím nìco z tohoto smìru.
{10916}{10985}To jako...?! To se máme|spolehnout na náhodu?!
{10987}{11027}Uklidni se, klid.
{11107}{11169}Tak, a co teï?
{11171}{11218}No, já, ee...
{11219}{11290}No, já, ee...OSLE!
{11291}{11346}Slepá ulièka!
{11347}{11407}- Zvláštní, co?|- To není veselé!
{11411}{11477}No tak, neudìlala|to naschvál.
{11808}{11864}Hùù, otevírá se to.
{11872}{11921}Vıbornì! Sylphiel,|jsi vynikající!
{11928}{11993}Dobøe, jdeme dál!
{11996}{12099}Je strašnì náladová,|ale není a tak špatná.
{12129}{12165}Já to vím.
{12179}{12217}Co je tohle za místo?
{12219}{12282}Vypadá to, e tu u|nikdo nebyl po celé roky.
{12286}{12347}Proè by tu mìla bıt zkratka?
{12350}{12413}Pøestaò nadávat a hledej.
{12435}{12469}Co je tohle?
{12589}{12639}- Strašidlo!|- Co?
{12671}{12717}Co jste zaè?!
{12741}{12812}Kdo se opovauje rušit|spánek velkého Tiibu?
{12868}{12915}Co je zaè ta slepice?
{12916}{12944}Slepice?!
{12949}{13045}Odvauješ se nazvat slepicí|mne, Monstrum Tiibu?!
{13077}{13103}Monstrum?
{13112}{13217}Podívejte se lépe|a øeknìte, co vidíte!
{13224}{13258}Slepici.
{13261}{13306}Ze všech úhlù|stále slepici.
{13315}{13390}Nejslepiètìji vypadající|slepici, jakou jsem kdy vidìl.
{13461}{13506}A ty si myslíš co?!
{13507}{13559}Ehm, velmi pìkná...
{13566}{13613}...slepice.
{13636}{13683}Co tu dìláš?
{13717}{13789}Nebudu se bavit s bandou|slepıch idiotù!
{13797}{13827}Coe...?
{13829}{13868}Elmekia Lance!
{13908}{13977}Take, co tu dìláš teï,|pane Slepièko?
{13980}{14122}Pán Rezo mì pøivolal, abych mu pomáhal|s vızkumy! Opravdu!
{14125}{14220}Protoe existují kouzla,|které ovládají jen Monstra!
{14229}{14290}Ty jsi nejhorší pøíklad|Monstra, kterı jsem kdy vidìl.
{14293}{14345}Jsi si jistı, e to není slepice?
{14356}{14402}Kdy jsi pomáhal s vızkumem...
{14405}{14457}...potom urèitì víš,|kde je Rezovo dìdictví!
{14461}{14563}To, co asi myslíte, je|tajnı vızkum...
{14565}{14651}...na kterém pán Rezo|pracoval pøe dávnımi vìky.
{14653}{14719}Take nevíš?|Och, to je teda smùla!
{14725}{14796}Uka nám nejrychlejší|cestu do nejhlubší komory.
{14811}{14851}Neukái!
{14853}{14895}Kdy neukáeš...
{14924}{14996}...promìním tì na|slepièí veèeøi!
{15004}{15046}Ukáu! Ukáu!
{15269}{15316}Stráná Monstra?
{15372}{15442}Nemáme èas bojovat|s takovımi vìcmi!
{15444}{15492}Nech to na mnì.
{15540}{15612}Nesmíte nás otravovat.
{15645}{15717}Ihned odejdìte!
{15885}{15997}Samozøejmì... Všechny tahle|Monstra pøivolal Rezo.
{16030}{16087}Pojïme, pospìšme si.
{16324}{16414}Tak? Kde je zkratka|do laboratoøe?
{16438}{16552}Och, ano! Pøesnì tady!|Tohle vede pøímo do laboratoøe.
{16563}{16606}He? Tohle?
{16607}{16666}Dobøe, nastup si,|pane Slepièko.
{16672}{16766}Prosím! Jsem Monstrum, pamatujete?|Jmenuji se Tiiba-
{16768}{16845}Zajímá mì, zda|mùeme jít, Pane Slepièko!
{16848}{16904}Mùete!|Mùete! Tak pojïme!
{17110}{17152}No, jsme tady.
{17173}{17232}Take Rezovo dìdictví|je za tìmito dveømi?
{17349}{17401}Hele, nedají se otevøít!
{17406}{17508}Dokáe je otevøít jen ten,|kdo vládne velkou magickou silou.
{17508}{17609}Pokud potøebujeme velkou magickou sílu,|na øadì jsem já.
{17621}{17672}Po takovém vıroku budeš...
{17674}{17735}...velmi zahanbená, pokud to neotevøeš.
{17735}{17776}Starej se o sebe.
{17808}{17915}"Nehybné dveøe, otevøete se|pod mou magickou sílou!"
{18259}{18312}- Funguje to!|- Otvírají se!
{18312}{18364}To byla malièkost!
{18384}{18478}Teda, ještì jsem nevidìla|tak velkou laboratoø.
{18478}{18567}Bude tìké najít tady|Rezovo dìdictví.
{18626}{18668}Hej, slepice!
{18668}{18719}Nevíš, kde by mohlo|bıt Rezovo dìdictví?
{18719}{18828}Ne. Pan Rezo mi nikdy pøesnì|neøekl, co zkoumá.
{18828}{18911}Opravdu? OPRAVDU to nevíš?
{18924}{18974}Vy mi nevìøíte?
{18974}{19027}Nechci skonèit jako|peèené kuøe-
{19036}{19085}Vlastnì peèenı démon!
{19085}{19149}Pøísahám, e mluvím pravdu!
{19150}{19259}Mùu se tì zeptat,|co to bylo vlastnì za vızkum?
{19275}{19378}Nìco o tom, jak bojovat|se silnımi Monstry.
{19389}{19443}B-Bojovat s Monstry?
{19443}{19496}Zajímalo by mì...
{19506}{19537}Na co myslíš?
{19549}{19656}Rezo oivil Shabranigda,aby|vyléèil své oèi, e?
{19678}{19782}Jene neèekal, e ten|se zrodí v jeho vlastním tìle...
{19849}{19932}...to znamená, e to narození|oèekával nìkde jinde.
{19946}{20042}Kdyby Shabranigda nechal uniknout,|svìt by byl znièenı.
{20042}{20127}Take hledal zpùsob, jak|znièit Shabranigda.
{20190}{20258}Správnì. Pak je jasné,|proè byl pøipravenı...
{20258}{20326}...postavit se Temnému Pánovi|v pøímém souboji.
{20349}{20381}Chápu...
{20381}{20456}Take se pøipravoval na tu bitvu.
{20459}{20485}Je to moné.
{20504}{20546}Hej, Sylphiel.
{20548}{20613}Mohla bys udìlat to, co|pøedtím a najít Rezovo dìdictví?
{20617}{20656}Zkusím to.
{21089}{21137}Sleèno Lino, ta ozdoba!
{21180}{21219}Ta vìc?!
{21219}{21276}Nemyslíte, e je nádhernı?
{21293}{21336}Ne, to si FAKT nemyslím!
{21348}{21494}Promiòte! Ale všechno tu|obsahuje tolik magie.
{21504}{21570}Nevím, co z toho|je Rezovo dìdictví.
{21586}{21666}Proto ještì nemusíš|tak blbnout!
{21666}{21724}- No! No! Uklidni se, Lino!|- Ale...!
{21724}{21829}Nemáme na vıbìr. Musíme|prohlédnout všechno.
{21829}{21878}Vypadá to tak.
{21883}{21927}Tak dobøe. Jdem na to.
{22219}{22279}Na co to tu má,|ten Rudı knìz?!
{22548}{22575}Pane Slepièko?
{22709}{22757}Co to dìlá pan Slepièka?
{22785}{22823}To by mìlo bıt ono.
{23082}{23113}Co se dìje?!
{23145}{23192}Vidìla jsi mì.
{23231}{23263}Drahı Gourry!
{23300}{23335}Sylphiel!
{23398}{23417}Ne...
{23497}{23543}Sylphiel! Co se dìje?!
{23566}{23620}- Drahı Gourry!|- Co je tohle?!
{23620}{23670}Uhm, to je pan Slepièka.
{23719}{23769}Tohle je moje pravá forma!
{23779}{23840}Coe?! Ta slepice je...?!
{23840}{23901}Proè jsi a doteï...?
{23906}{24028}Kdy mì Rezo pøivolal,|zaklel mou sílu do této masky!
{24045}{24104}Bez masky mám tìlo,|které jste vidìli pøedtím.
{24126}{24168}A teï, kdy mám masku zpátky...
{24174}{24241}...nedovolím vám hledat|Rezovo dìdictví.
{24260}{24331}Ne! Nedovolím lidem|vlastnit nìco,...
{24331}{24430}...co by mohli pouít|proti nám!
{24597}{24644}Digger Bolt!
{24745}{24772}Dostali jste ho!
{24866}{24950}Nauèím vás nepodceòovat|mou sílu!
{25014}{25064}Ty jedno velké,|pøerostlé kuøe...!
{25201}{25261}Hele! To není fér!
{25269}{25345}Proè se tam vznášíš|a nepøijdeš sem dolù?!
{25345}{25426}To mùe bıt zábavné! Tak dobøe!
{25453}{25552}Ee, ja... V skuteènosti jsem|nechtìla, abys pøišel...
{25563}{25601}Tady máš!
{25661}{25698}Lino! Nechoï pøímo na nìj!
{25698}{25742}Dík za radu!
{25742}{25832}Tady v podzemí nemùu|pouít Dragon Slave!
{25832}{25872}Co mám dìlat?!
{25940}{26015}Ty...! Elmekia Lance!
{26331}{26349}K èertu!
{26349}{26422}Teï to skonèím!
{26701}{26750}Slabé! Velmi slabé!
{26771}{26823}Myslím, e nás|podceòuješ, slepice!
{26835}{26894}NEØÍKEJ MI SLEPICE!
{26901}{26964}- Slepice!|- Slepice!
{27124}{27160}Vyzkouším Ra Tilt.
{27160}{27221}A já zkusím Elmekia Lance.|Pojïme!
{27303}{27342}- Sleèno Lino!|- K èertu!
{27438}{27481}Nedotıkej se toho!
{27543}{27583}Není to...?
{27595}{27615}To je...!
{27620}{27654}Och, ne!
{27750}{27847}Nevìøím tomu! Jak to mohlo|padnout do vašich rukou?!
{27886}{27946}Zdá se, e mám první cenu!|Ani tvoje útoky...
{27949}{28026}...neprojdou pøes|Rezovo dìdictví!
{28028}{28044}Uff!
{28045}{28117}To je Rezovo dìdictví?|Ta kamenná tabule?
{28126}{28165}Rezovo dìdictví?
{28190}{28229}To je...!
{28253}{28316}"Svìtlo! Soustøeï se|ve mnì a staò se bleskem!"
{28317}{28373}"Protni pøíšernou temnotu!"
{28399}{28459}ELMEKIA FLAME!
{28549}{28574}Zele! Amélie! Teï!
{28582}{28661}"Zdroj všech duší, èíhajících v nekoneènu!"
{28663}{28699}"Nehasnoucí modrı plamen!"
{28703}{28753}"Nech síla ve mnì skrytá..."
{28759}{28827}"...vyjde ven z temnoty!"
{28831}{28859}Ra Tilt!
{29067}{29110}Hotovo!
{29135}{29213}Tahle kamenná tabule|je Rezovo dìdictví?
{29215}{29253}Koho zajímá, jak vypadá?
{29255}{29325}Dùleité je, co|øíkají tyto runy!
{29389}{29515}V tom není opravdová|síla té tabule.
{29606}{29646}Ta tabule!
{29831}{29908}Koneènì je moje!
{29911}{29975}Dìdictví pana Reza...|Rukopis Bible Claire!
{30034}{30126}Koneènì...|Koneènì je mùj!
