{1}{1}23.976
{326}{383}Tam, kde se vyrojí monstra,|objevím se, abych je znièila.
{398}{466}Tam, kde se zatøpytí poklady,|pøicházím, abych se jich zmocnila.
{466}{572}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2609}{2698}A nakonec jsme poznali, e Rezovo dìdictví je stejná vìc...
{2698}{2787}...která znièila Sairaag:|znovuzrození monstra Zanaffara!
{2787}{2860}Najednou se Zanaffar mohl spojit s Rezovo kopií...
{2860}{2932}...a pøinutili mne pouít odmítané kouzlo: Giga Slave!
{2932}{3000}Konec!|Byla jsem pøipravená to zkusit.
{3000}{3062}Ale ještì ne jsem mohla odpálit Giga Slave...
{3062}{3109}...skoèila mezi nás Syphiel!
{3109}{3189}A nakonec jsem byla opravdu zle zranìná,|kdy jsem se ji pokusila ochránit!
{3189}{3254}Vìci vypadají pìknì špatnì, nemyslíte?
{3264}{3405}ANO!|Poslední nadìje: Posvátná Èepel!
{3430}{3503}LINO!
{3929}{3994}Sleèno Lino!|Sleèno Lino, drte se!
{4233}{4303}Amélie, prosím! Pomoz mi!
{4389}{4502}Obìtovat se pro nìkoho|jiného... Jak hloupé.
{4528}{4576}Ty netvore! Jdi do pekla!
{4682}{4765}Prosím, nevmìšujte se|mezi nás.
{4769}{4840}Abych dokázal pøekonat|originálního Reza Rudého knìze...
{4846}{4904}...musím zabít to dìvèe.
{4907}{4964}Sylphiel, Sylphiel!
{4977}{5025}Sylphiel, jak je Linì?
{5027}{5065}Zastavili jsme krvácení...
{5066}{5145}...ale pokud neudìláme|úplné léèivé kouzlo, zemøe!
{5146}{5241}Dobøe, rozumím.|Seber Linu a jdi pryè!
{5258}{5299}Sylphiel...
{5371}{5397}Prosím.
{5399}{5420}Dobøe.
{5458}{5507}Neuniknete!
{5794}{5851}Dobøe! Pokraèuj!
{6026}{6098}Pøekonat Reza?|Taková hloupá ambice.
{6118}{6228}Ano, i já jsem se chtìl|pomstít za tohle tìlo...
{6243}{6322}Ale kdy Reza pøekonáš, co pak?!
{6323}{6376}Co budeš dìlat potom?!
{6385}{6444}Neexistuje ádné potom.
{6447}{6575}Kdy zabiji to dìvèe,|nezajímá mì, co bude dál!
{6575}{6641}- Coe?!|- To je støelené!
{6650}{6705}Take vy mi z cesty neuhnete, co?
{6707}{6772}Kdy neustoupíte,|mùe se vám nìco stát.
{7049}{7091}Uka se, Svìtlo!
{7227}{7270}Dìkuji, pane Gourry!
{7270}{7357}Hlupáku! Co to dìláš?!|Starej se o vlastní kùi!
{7357}{7412}Ale díky...
{7419}{7522}Hele, nestùjte tam a|pomozte mi!
{7727}{7772}Rezo se...
{7972}{8060}Rezo se bojí Flagoonu.
{8408}{8479}Sleèno Lino, za chvíli|budete v bezpeèí.
{8487}{8543}Vydrte.
{8903}{8969}Sleèno Lino, teï vám dám|léèivé kouzlo.
{9309}{9334}Ne!
{9334}{9422}Neumírejte! Neumírejte!
{9453}{9487}Prosím!
{9487}{9620}Prosím! Prosím! Prosím!
{9986}{10034}Ještì poøád není pozdì!
{10042}{10091}"Boí ruko, svatá a pokorná."
{10093}{10138}"Dech Matky Zemì."
{10140}{10249}"Prosím vás o pomoc.|Ukate svou..."
{10275}{10356}Sleèno Lino, prosím, vrate se.
{10357}{10461}"Buïte milosrdní k|této osobì a pomozte jí!"
{11641}{11730}Ne! Nikdo víc nesmí zemøít!|Vy nesmíte zemøít!
{11745}{11830}Prosím!|VRATE SE K NÁM!
{12774}{12888}Flagoone... Všichni...|Otèe...
{12907}{12995}Dejte sleènì Linì...
{12995}{13082}...svou...sílu...
{13588}{13646}K èertu!|Kouzla nefungují!
{13646}{13723}A Meè Svìtla také ne!|Co udìláme?!
{13764}{13833}Prosím, vrate mi Linu Inversi!
{13846}{13932}Bez ní to není|ádná zábava!
{13941}{13989}Co bude s Giga Slavem?
{14010}{14083}Opravdu tolik touí|pøekonat pravého Reza?
{14112}{14197}Nech se dìje cokoliv,|musím ho zastavit!
{14258}{14294}Princ Phil?!
{14294}{14319}Otèe?!
{14400}{14460}Uff, a já jsem byl pøipravenı|na velké finále.
{14480}{14558}Vypadá to, e bez nìj|by show nestála za nic.
{14566}{14648}Zloduchu posednutı netvorem!|Pøiprav se na smrt!
{14731}{14796}Take to ty jsi|byl za tím vším!
{14813}{14875}Ve jménu zákona,|ádám tvoji kapitulaci!
{14955}{15063}- Oh, Phile...|- Co je zase s tvım otcem?
{15081}{15121}Není skvìlı?
{15121}{15161}Nemám rád boj...
{15161}{15265}...ale kdy se nepodøídíš|zákonu, nebudu mít slitování!
{15276}{15319}Och, a co udìláš?
{15361}{15410}Take ty se chceš vzpírat?!
{15427}{15470}Zdá se, e Phil nechápe,|do èeho jde!
{15508}{15519}Otèe!
{15527}{15593}ÚDER PACIFISTY!
{15777}{15806}Otèe!
{15806}{15852}- Amélie!|- Otèe!
{15852}{15878}Amélie!
{15893}{15922}Nepromluvíte si pozdìji?
{15938}{15973}Phile, jsi zranìnı?!
{15990}{16042}Dark Mist!
{16235}{16295}Tak a teï... UTÍKEJME!
{16843}{16870}Díky bohu!
{17382}{17488}Mùj šálek... panenka...
{17492}{17530}Mùj...
{17888}{17936}Tady u nejsme v bezpeèí.
{17979}{18067}Sleèno Lino, ještì|chvíli vydrte.
{18173}{18211}Sbohem!
{18255}{18299}Sleèno Lino! Promiòte!
{18303}{18407}Oh, Boe! Oh, Boe!|Jen a si na to nevzpomene!
{18580}{18662}Dost bylo skrıvaní!|Vyjdìte ven!
{18662}{18730}Nemáte kam utéct!
{18973}{19033}Myslím...e jsme mu utekli.
{19044}{19068}Aspoò na chvíli...
{19076}{19163}No, ošetøila jsem ti to,|ale chvilku se nehıbej.
{19177}{19236}Dobøe, Phile, co tady|vlastnì dìláš?
{19236}{19316}Správnì! Co tu dìláš, otèe?
{19323}{19401}Oh, kdy po vás šlo|tolik lovcù zloèincù...
{19401}{19451}...nebylo tìké vypátrat brzo pravdu.
{19475}{19551}Bál jsem se, e musíte|bojovat o svoje ivoty...
{19551}{19627}...protoe Amélie je|taková jemná duše jako já.
{19638}{19721}Otèe! A tak jsi se|o mnì bál?!
{19731}{19772}Co to øíkáš, Amélie?!
{19772}{19834}Kterı otec by se|nebál o své dítì?
{19843}{19883}Kdo je tu jemnı?
{19894}{19935}Pane Gourry, to je hnusné!
{19942}{19972}A ukazovat prstem|je neslušné!
{19978}{20067}Oh, pøedstavím vás. Tento|strašidelnì vypadající chlapík je Zelgadis.
{20070}{20100}Neukazuj na mnì prstem.
{20109}{20194}Oh, a kde je to dìvèe?|Nevidím ji tady.
{20202}{20228}Li- Lina je...
{20236}{20316}Právì se léèí.|To je vina toho monstra.
{20322}{20397}Coe?! Zranil to dìvèe?!
{20430}{20494}To je opravdu tak silnı?!
{20537}{20574}No ano, ale...
{20574}{20639}Nech to tak. Hlavnì e|to pochopil.
{20799}{20891}Lina bude v poøádku.|Je u ní Sylphiel.
{20908}{20995}Jsem si jistı, e Sylphiel|je schopná ji zachránila.
{21013}{21064}Cítím to.|Lina je v poøádku.
{21158}{21262}Ale pokud její síla a váš|Meè Svìtla nestaèili...
{21262}{21345}...jak se chcete zbavit|toho netvora?
{21362}{21427}Moná kdybychom zkusili|Megiddo Flare zblízka...
{21434}{21527}Nemluvte hlouposti!|Ani ho to neškrábne!
{21534}{21594}Ale jinı zpùsob nevidím.
{21605}{21653}Kdy nefunguje èerná magie...
{21653}{21697}Nemoné!
{21721}{21816}To, co potøebujeme...je|kouzlo všech duchù!
{21902}{21953}Ra Tilt je jediná nadìje!
{21973}{21990}Ra Tilt?
{22009}{22075}"Hele, v téhle epizodì|se Lina témìø neobjevuje!"
{22075}{22141}"Co se stalo s Linou?!|Dejte Linì nìjakı dialog!"
{22141}{22197}To je to, co si teï|všichni øíkáme, ne?.
{22197}{22265}Take pro všechny fanoušky,|dokud Lina odpoèívá...
{22265}{22325}...je tu Magická Škola|Krásné Liny!
{22325}{22393}"Nehasnoucí modrı oheò."
{22393}{22466}"Nech síla ve mnì ukrytá..."
{22466}{22538}"...vyjde navdy z temnoty!"
{22538}{22601}Ra Tilt!
{22636}{22729}Dobøe, "Ra Tilt" ta vìcièka,|kterou právì Zelgadis pouil...
{22729}{22795}...je nejsilnìjší kouzlo|Astrální Roviny...
{22795}{22845}...a vyrovná se Dragon Slavu!
{22860}{22909}Tady! Tohle je dùleité!
{22926}{23009}Kdy takovı vysoce koncentrovanı|magickı vıboj zasáhne protivníka...
{23009}{23054}...èlovìku vùbec neublíí...
{23054}{23105}...ale Monstrum znièí!
{23116}{23173}Pro Monstra, které mají|nehmotné tìla...
{23173}{23226}...to znamená jistı konec.
{23244}{23308}Dìti, to je nebezpeèné,|take doma to nezkoušejte!
{23317}{23337}Jako bychom mohli!
{23343}{23423}Jasnì, vùle! Pokud budeme mít víc|vùle, jak nepøítel...
{23437}{23483}...a zasáhneme ho Ra Tiltem-
{23494}{23566}Gourry!|Asi jsi zapomnìl...
{23577}{23664}...e kdy jsme to zkusili|proti Shabranigdovi, selhalo to.
{23710}{23745}Musíme víc cvièit!
{23775}{23797}Selhalo...?
{23819}{23880}Pane Gourry, nikdy si nic nepamatujete!
{23893}{23950}Myslel sis, e to bude|staèit proti tak velkému soupeøi?!
{24190}{24251}Jsme skoro na místì, sleèno Lino.
{24279}{24394}Moná... Moná tohle|bude schopné zastavit Zanaffara.
{24436}{24505}Èást Flagoonu.|Posvátnı meè.
{24582}{24663}Svatı meè...|Posvátná Èepel!
{25731}{25778}S Posvátnou Èepelí, moná-
{25807}{25851}Chceš jít beze mne?
{25919}{25950}Sleèno Lino!
{26029}{26063}Sleèno Lino!
{26100}{26148}Sleèno Lino, díky bohu!
{26160}{26181}Myslím, e jsem v poøádku...
{26190}{26252}Sleèno Lino, odpuste!|Byla to moje chyba!
{26256}{26300}Chtìla jste mne zachránit a...!
{26309}{26354}Promiò, Sylphiel...
{26442}{26563}Podívej, je to MOJE chyba, e|jsem se pøi tom zranila, jasné?
{26579}{26660}Pøíštì si nehraj na hrdinku,|která zachytí všechny rány, dobøe?
{26670}{26692}Promiòte...
{26699}{26803}A bylo to za to, es|mi praštila hlavou o stìnu!
{26803}{26845}Och, vy se pamatujete?
{26849}{26882}Na to se nedá zapomenout!
{26896}{26948}Asi jsi chtìla sebrat|tenhle meè...
{26960}{27002}...a pomoct Gourrymu a ostatním.
{27034}{27111}Nic proti, ale kdy pùjdeš,|budeš jen pøekáet.
{27123}{27186}Ne, já chci, abyste|si ten meè vzala vy.
{27196}{27312}Kdokoli mi bude pøekáet,|rozdrtím ho na kusy!
{27319}{27368}Abych pøekonal pravého Reza...
{27368}{27418}...pouiji všechny prostøedky!
{27424}{27464}Co to mele?!
{27464}{27505}Moná e Zanaffar...?!
{27510}{27549}Rezo...
{27584}{27617}Co...?!
{28105}{28155}Bolest je pryè.
{28170}{28269}Bolest, kterou jsem cítila, zmizela.|Co je to za meè?
{28273}{28362}Posvátná Èepel, souèást|svatého stromu, Flagoonu.
{28380}{28454}A myslím, e má vlastnost|Flagoonu...
{28458}{28506}...absorbovat Zanaffarovu krev.
{28506}{28543}- Krev?|- Ano.
{28543}{28631}Flagoon roste absorbováním|ïábelské krve, kterou produkuje Zanaffar...
{28631}{28734}...a tak mu brání|v útoku.
{28744}{28828}Myslím, e tohle by mohl bıt klíè|k poráce Zanaffara.
{28828}{28885}- Coe?!|- Vidìla jsem to!
{28900}{28967}Zanaffar se nikdy|nepøiblíil k Flagoonu!
{28967}{29079}Jsem si jistá, e se bojí,|aby ho úplnì nepohltil!
{29091}{29160}Síla, která absorbuje jeho zlo...
{29166}{29246}Tak uvidíme...|Jdeme, Sylphiel!
{29246}{29273}Poèkejte chvíli!
{29289}{29342}Potøebuji tvoji pomoc,|abychom se zbavili Zanaffara.
{29358}{29416}A mìli jsme štìstí, e meè|byl tam, kde byl!
{29424}{29537}Pùvodnì mìl bıt v klášteøe|v Sairaagu.
{29564}{29628}Sebrala jsem ho odtamtud|a ukryla tady.
{29644}{29691}Byla jsem jen dítì!|Bylo to pro zábavu!
{29714}{29757}V mìstì z toho museli|bıt velké problémy!
{29769}{29822}Ano, a já jsem se tak bála,|e jsem ho radši nechala tady.
{29822}{29878}Chodila jsem si sem hrát!
{29887}{29943}Nikdo jinı sem nikdy nechodil!
{29955}{30004}Oh, no tedy...|Dobøe, pojïme!
{30007}{30045}Gourry a ostatní u èekají!
{30045}{30087}Um, sleèno Lino?
{30087}{30137}Udìlala jste v nìkdy dìtství|nìco bláznivého?
{30137}{30199}Uh... He-he-he...|Radši se neptej!
