{1}{1}23.976
{326}{385}Tam, kde se vyrojí monstra,|objevím se, abych je znièila.
{385}{466}Tam, kde se zatøpytí poklady,|pøicházím, abych se jich zmocnila.
{466}{572}A tam, kde se mi nepøátelé postaví,|tam vítìzství bude mé!
{2616}{2656}Lina Inverse je tu!
{2656}{2727}Tak koneènì vyvrcholil ten|závod o Rezovo dìdictví!
{2727}{2790}O-hó! Nakonec, jsme profesionálové...
{2790}{2866}...a Rezo byl jen kopií vytvoøenou Eris!
{2866}{2942}Co? Eris naší smrtí|chtìla pomstít Reza?
{2945}{2980}Tohle je všechno špatnì!
{2981}{3060}Hele! Gourry! Co je to za|velkı nápad, zaútoèit na nás?
{3060}{3116}Pøedpokládá se, e budeš útoèit na jiné!
{3116}{3180}A nakonec jsme zjistili,|e oni ve skuteènosti...
{3196}{3250}...chtìjí znovuzrození legendárního|monstra Zanaffara!
{3268}{3298}A pak... a pak!
{3304}{3358}Jste jen vši.
{3363}{3462}Rezova kopie zaútoèila na Eris!|Co se to tu dìje?
{3482}{3623}DEN-X!|Znovuzrození démonické pøíšery!
{3676}{3772}Odpoèívej v pokoji. Rezova|pomsta bude pokraèovat.
{3775}{3849}Jen ji...|Uskuteèním já!
{3969}{4035}Hele, co se dìje?
{4037}{4108}Je to jen Rezova|kopie, ne?!
{4108}{4144}Správnì...
{4153}{4246}Proè?! Rezo, nebyl|dùvod zabít Eris!
{4246}{4281}Ale byl!
{4298}{4427}Takhle dokái uskuteènit to, co|originální Rezo nedokázal!
{4440}{4491}Co originál nedokázal?
{4510}{4560}Ano. Mohu vás všechny...
{4560}{4610}...zabít vlastní rukou!
{4626}{4691}A tak já, kopie,|pøekonám originál!
{4698}{4740}Pøekonáš originál?
{4740}{4782}Není to úasné?
{4786}{4903}A dokud Eris ila,|nemohl jsem dosáhnout svého skuteèného cíle.
{4919}{4974}A proto jsi zabil|svou stvoøitelku?!
{4987}{5045}Nakonec, je to jen kopie...
{5045}{5079}Eris!
{5153}{5296}Jakkoliv jsem se snaila,|nebyl to opravdovı Rezo...
{5296}{5360}Jen kopie...
{5360}{5424}Ještì ije!
{5424}{5478}Musíme jí pomoct!
{5617}{5709}Pane Rezo, já... já...
{5906}{5988}Je èas zemøít.
{6032}{6112}Pane Rezo,|kam pùjdete...?
{6345}{6366}Eris...
{6385}{6480}Zmizela beze stopy.
{6512}{6530}To bylo nelidské!
{6553}{6600}A nefér!
{6737}{6767}U je to tady.
{6768}{6825}Zanaffarovo znovuzrození!
{7113}{7172}Lino, nemùeme nìco dìlat?!
{7172}{7232}Mùeme doufat v nejlepší!
{7232}{7268}ertuješ?!
{7268}{7327}Pokud jeho síla|poroste...
{7329}{7407}U teï je pøíliš silnı!
{7766}{7804}Sleèno Lino, podívejte!
{7988}{8054}Pøišel èas, aby na scénu|vystoupila hvìzda.
{8103}{8143}Promiòte mi to zdrení.
{8236}{8293}Stále vypadá stejnì, ale...
{8306}{8353}Psychickı tlak|je úasnı!
{8368}{8410}Je to...|Démonickı Netvor Zanaffar?!
{8428}{8525}Moná jste oèekávali|grandióznìjší vzhled?
{8537}{8654}Zanaffar èerpá neomezenou|energii z démonické síly!
{8668}{8718}Ten, jeho tìlo se spojí|se Zanaffarovım...
{8721}{8817}...získá kontrolu nad jeho|neohranièenou silou zla!
{8889}{9019}Neohranièená síla?! Nemoné!|Ach, to je po nás!
{9060}{9138}To urèitì!|Ještì máme jedno eso v rukáve!
{9138}{9191}Gourry, zabij ho!
{9191}{9254}V poøádku! Na tato|slova jsem èekal!
{9283}{9353}Podle legendy,Meè Svìtla...
{9353}{9430}...dokáe zabít démonického|netvora Zanaffara!
{9441}{9496}Na nìj, pane Gourry!
{9540}{9638}Tak to vyzkoušej. Uvidíme,|zda má legenda pravdu.
{9670}{9729}Smìj se, dokud ještì mùeš!
{9881}{9915}Dostal ho!
{10116}{10142}Drahı Gourry!
{10155}{10192}To není moné!
{10201}{10255}Proè Meè Svìtla nefunguje?!
{10290}{10390}Tak ten legendární Meè Svìtla|dokáe jen tohle?
{10409}{10453}Legenda je le!
{10461}{10541}Teï jsem na øadì já! Dívejte se!
{10646}{10675}Pozor!
{10815}{10865}Taková je Zanaffarova síla...?!
{10885}{10967}Dobrı manévr,|ale dokáete ho zopakovat?
{11144}{11164}K èertu!
{11184}{11220}Hraje si s námi|jako koèka s myší!
{11225}{11269}Fireball!
{11447}{11484}Štít?!
{11649}{11705}Takhle nás tu pohøbí zaiva!
{11725}{11781}Nebuï tak pesimistická!
{11990}{12049}Rezo?! Proè?
{12060}{12158}Protoe smrt pod kameny|není pro vás to pravé.
{12170}{12230}A není to, co chci.
{12258}{12327}Tak, bojujte a zemøete v øádném boji!
{12327}{12375}Jako kdyby jsme mohli!
{12375}{12422}Zelgadis má pravdu!
{12468}{12538}Za prvé, nemùeme poøádnì|bojovat...
{12538}{12609}...v takové úzké malé|podzemní jeskyni!
{12617}{12675}Hm, máte pravdu.
{12714}{12818}Tak se pøesuneme na|nìjaké pøijatelnìjší místo.
{12839}{12874}No tedy, opravdu?!
{12889}{12949}Nebuïte tak naivní!
{13038}{13085}Vidíte? Lhal!
{13098}{13147}Ne! Podívej se líp!
{13391}{13438}O co se to pokouší?
{13453}{13538}Nevím, ale a je to|cokoliv, bude to velké!
{13560}{13622}Tak a teï nìco skuteènì|pozoruhodného!
{14115}{14157}Jsme... Jsme nad zemí!
{14167}{14245}Ale vdy ještì pøed chvílí|jsme byli hluboko v podzemí, ne?!
{14425}{14533}Ten ïábel Rezo vyhodil celou|laboratoø do vzduchu!
{14550}{14617}Nemoné... taková síla!
{14688}{14725}Levitation!
{14890}{14937}Sleèno Lino, podívejte!
{15178}{15206}Rezo!
{15246}{15324}Dokáe tohle všechno|a ještì si s námi hraje!
{15324}{15418}Teï, kdy mùeme bojovat,|co udìláme?
{15430}{15484}To je úplnì jasné, co!
{15484}{15511}Nemyslíš...!
{15535}{15565}Ray Wing!
{15671}{15719}Doèasnì se stáhneme.
{16079}{16117}Flagoon!
{16185}{16246}Slyším, jak|Flagoon pláèe...
{16875}{16934}Proè neletíme?!
{16934}{16991}Protoe na zemi jsme|líp schovaní!
{16991}{17032}Hej všichni! Tudy!
{17067}{17156}K èertu! Chce nás|Rezo snad uhnat k smrti?!
{17165}{17232}Proè nás tak moc chce|zabít?!
{17241}{17300}Protoe v okamiku,|kdy nás zabije...
{17301}{17373}...pøekoná originál!
{17492}{17555}Pro nìj je to jen|velká marnotratnost!
{17557}{17602}Pøesnì tak.
{17614}{17699}Pochopila jsi to.|Vdy geniální Lina Inverse.
{17701}{17815}Samozøejmì. Jsem pøeci ta, která|porazila Reza Rudého knìze, ne?
{17827}{17897}Pøesnìji: originál,|a ne kopii!
{17907}{17992}Snaíš se mì rozèílit.|I tak...
{18001}{18080}...kdy neporazíš i mnì,|tvoje vítìzství vyjde naprázdno.
{18086}{18132}Kdo chce koho rozèílit?
{18134}{18237}Abys porazila mne, na to|potøebuješ víc ne obyèejnou magii.
{18250}{18311}Napøíklad...
{18313}{18403}Ano! Nejsilnìjší|útoèné kouzlo na svìtì:
{18406}{18433}Giga Slave!
{18442}{18485}Giga Slave?!
{18654}{18789}Zabila jsi s ním originálního|Reza, ne?
{18806}{18899}Tak proè ho nezkusíš i na mnì?
{18900}{18949}Jak to víš?!
{18966}{19093}Lehko. Sledoval jsem tì|pomocí Eris.
{19093}{19137}Tak to vím.
{19157}{19220}Podívej!|Potom to musíš chápat!
{19222}{19290}Pøi tom kouzlu do mého|tìla vstupuje Temnı Pán!
{19300}{19361}Co kdy nad ním|ztratím kontrolu?!
{19373}{19435}Dùsledky mì nezajímají.
{19437}{19532}Všechno co mne zajímá je v mém srdci.
{19534}{19603}Jsi... Jsi blázen...
{19605}{19739}Moná. Tak ukáeš mi|ten svùj malı trik?
{19740}{19782}Giga Slave!
{19798}{19823}Giga Slave...!
{19837}{19923}Ne, to nesmí!|Kdy nad ním ztratí kontrolu...
{19925}{19988}...celı svìt se zmìní v|prázdnotu!
{19989}{20036}Je to strašné kouzlo!
{20037}{20076}No a co?!
{20078}{20150}Mnì osud svìta nezajímá!
{20158}{20197}Ale ne...!
{20333}{20386}Máme ještì jinou šanci na vítìzství?
{20387}{20463}Vypadá to, e mùj Meè Svìtla|a tvoje magie neúèinkují.
{20470}{20550}Správnì. Je to asi|jediné øešení.
{20585}{20627}Ne! To kouzlo je...
{20629}{20663}Já vím!
{20781}{20805}Tohle je zábavnìjší!
{20893}{20931}Neuteèeš!
{20980}{21042}Tady máš!|Èepel Spravedlnosti!
{21085}{21127}Oh, hloupá Èepel Spravedlnosti!
{21277}{21382}Tak a teï...|Moje dùleitá Lino...
{21468}{21524}R-R-Rezo... Pøiprav se zemøít!
{21605}{21645}REZO!
{21779}{21807}Drahı Gourry!
{21990}{22076}Oh? Stále máš sílu|postavit se proti mnì?
{22079}{22142}Pøijímám tvou vızvu.
{22333}{22429}Je tu nìkdo, kdo si tvou|vızvu zaslouí víc!
{22564}{22611}Velmi hloupé, Rezo.
{22709}{22804}Zanaffarùv štít tì na tak|krátkou vzdálenost neochrání!
{22806}{22853}DRAGON SLAVE!
{23118}{23158}Podaøilo se?!
{23478}{23495}Rezo?!
{23507}{23565}Vıbornì, Lino!
{23566}{23678}Ale pro mnì není problém|absorbovat i Dragon Slave.
{23694}{23717}Absorbovat...?
{23727}{23807}Pouij Giga Slave!|Jinak...
{23990}{24094}Mám pokraèovat, dokud|se nìkomu nìco nestane?!
{24236}{24278}BASTARDE!
{24334}{24366}Gourry!
{24414}{24462}Pøiprav se na smrt!
{24874}{24940}Flagoon? Flagoon je...
{25286}{25326}Sleèno Lino!
{25443}{25491}Tohle ti neodpustím.
{25503}{25571}Koneènì jsi pøipravená.
{25706}{25801}Aspoò si tví pøátelé|oddechnou.
{25803}{25861}Vyøešíme to sami...
{25863}{25897}Jako mu se enou!
{25949}{25996}Pùjèím si tohle, Gourry...
{25998}{26029}Sleèno Lino!
{26031}{26070}Sylphiel...
{26086}{26114}Promiòte!
{26117}{26166}Sleèno Lino, nedìlejte to!
{26247}{26300}Sylphiel...
{26303}{26355}To je hrozné!|Sleèna Lina je...!
{26367}{26395}Lina!
{26480}{26542}Dostaneš, co jsi chtìl!
{26623}{26679}Giga Slave!
{26775}{26833}"Temnota èernìjší ne uhel, "
{26835}{26885}"Hlubší ne nejtemnìjší noc!"
{26888}{26991}"Král Temnot, zlatì záøící|nad Oceánem Chaosu!"
{26998}{27109}"Volám tì! Zapøísahám se ti!"
{27110}{27203}"Nech blázny, kteøí se mi|postaví, znièí..."
{27204}{27303}"Síla, kterou spoleènì vládneme!"
{27479}{27522}To je Giga Slave!
{27556}{27583}Sleèno Lino...
{27598}{27678}Minule to fungovalo.|Prosím, a to vyjde i teï...!
{27797}{27829}GIGA SLA-
{27831}{27878}ZASTAVTE TO!
{28134}{28247}Sleèno Lino, zastavte to, prosím!|Mùe to znièit svìt!
{28261}{28295}Sylphiel...
{28296}{28378}Musí... Musí bıt i jinı|zpùsob, jak porazit Reza.
{28385}{28501}Myslím, e Zanaffar je...|e Zanaffar a Flagoon jsou-
{28503}{28581}Ty malá èarodìjnice!|Za to, e jsi zasáhla...
{28583}{28622}ZEMØEŠ!
{28670}{28711}Pozor!
{29526}{29557}Sleèno Lino!
{29558}{29606}Oh, Boe mùj...!
{29678}{29727}LINO!
{29845}{29895}LINO!
{29974}{30036}Jak se to stalo?|Nevìøím tomu!
{30039}{30147}Falešnı Rezo a démonickı|netvor Zanaffar mì dostali!
{30149}{30229}Oh, moná je krásnım lidem|pøedurèeno zemøít v mládí.
{30231}{30359}Nééé!|JÁ NECHCI ZEMØÍT!
