{1}{1}23.976
{63}{107}Asi mi nebudete vìøit, ale…
{132}{177}… ještì pøed tím ne mi øekl své jméno…
{218}{248}… jsem se cítila jako…
{293}{332}… bych u vìdìla, kdo to je.
{366}{417}Yano.. Motoharu.
{440}{467}TaSHee's Gang uvádí...
{491}{687}BOKURA GA ITA
{726}{869}-Proè nemùou jít vìci dobøe mezi-
{869}{1008}-lháøem, tebou, a uplakánkem, mnou?-
{1008}{1157}-Nevšimneš si mıch stylovıch vlasù-
{1157}{1300}-nebo mého krásného setu nalepovacích nehtù.-
{1300}{1480}-Láska není o nešastnıch slzách, které jsou spolu s tím.-
{1480}{1592}-Tyhle slzy jen zvlhèují moje oèi a zraòují.-
{1592}{1732}-Miluji tohle rozhodnutí-
{1806}{1947}-jen mezi tebou a mnou.-
{1947}{2064}-Chci pøijmout tvoje dychtivé pocity-
{2095}{2236}-a nalézt v tobì navdy zalíbení.-
{2236}{2399}-Navzdory tomu, e nejsi roztomilı, ubreèenému oblièeji a tvojí omezenosti, poøád tì miluji.-
{2614}{2661}Jsem Takahashi Nanami.|/EPIZODA PRVNÍ/
{2661}{2707}Tohle je mùj druhı den na vyšší støední škole.
{2707}{2775}Budu ráda, kdy si najdou hodnì pøátel.
{2775}{2822}T-teï to zkusím…
{2822}{2895}Ehm… Já jsem Takahashi Nanami.
{2929}{2965}R-ráda tì poznávám.
{2965}{3009}Jsem Yamamoto Yuri. Také tì ráda poznávám.
{3043}{3105}N-no, na jaké niší støední jsi byla pøedtím?
{3105}{3126}Asahi.
{3164}{3254}Ah… musíme zmìnit tøídu na rodinou vıchovu, e? Mùu jít s vámi?
{3254}{3307}Oh, ty jsi v první lavici vepøedu, e?
{3307}{3347}Jo. Jsem Takahashi Nanami.
{3347}{3357}Z jaké niší støední jsi?
{3357}{3374}Severní.
{3374}{3406}My jsme obì ze Západní.
{3406}{3488}Nezdá se, e by byly nìjaké dívky z naší tøídy z Asahi, co?
{3488}{3596}Hm, ta dívka, Yamamoto-san, které sedí vedle mì, je z Asahi.
{3596}{3625}No ne! Ty jsi s ní mluvila?
{3625}{3648}Musela jsi o nìm slyšet hodnì.
{3648}{3673}O kom?
{3673}{3709}O Motoharovi!
{3729}{3749}Kdo...?
{3771}{3891}Byly jsme s Motoharem bìhem zimního semestru a je opravdu cool!
{3916}{3976}Byl populární jak mezi dìvèaty, tak mezi chlapci.
{4007}{4055}Dokonce øíkali, e v jeho posledním roce na niší støední…
{4055}{4139}… byly do nìj ve stejnı èas dvì tøetiny dívek ze tøídy zamilované!
{4139}{4206}Take nìkdo jako on je se mnou ve stejné tøídì…
{4206}{4318}Hej, ty jsi ze stejné niší støední jako Yano-kun, co?
{4318}{4332}Jo.
{4332}{4393}Slyšela jsem, e se do nìj dvì tøetiny dívek zamilovali…
{4393}{4439}Nenávidím ho.
{4493}{4537}Hej, Nano, chceš bıt ve tøídním vıboru?
{4537}{4610}Oh, já preferuji snadnı ivot, take…
{4610}{4682}Opravdu tam chci bıt s Motoharem …
{4682}{4753}Jakı je postup pøi pøihlašování? Nìkdo tì nominuje?
{4753}{4793}Take pøihlášení sama sebe je tak nìjak chabé…
{4793}{4844}Co kdybych tì nominovala já?
{4844}{4865}Opravdu to udìláš?
{4865}{4878}Jistì.
{4878}{4957}Er… jaké bylo její jméno…?
{4957}{5002}Mizu… Mizu nìco…
{5002}{5026}Poèítám s tebou!
{5026}{5061}Ah, joo!
{5061}{5090}Vánì se jí nemùu zeptat…
{5109}{5186}U-um, jaké bylo jméno té dívky…?
{5186}{5233}Mizu… Mizu…
{5409}{5423}Mizuhara.
{5479}{5536}Asi mi nebudete vìøit, ale…
{5536}{5585}… ještì pøed tím ne mi øekl své jméno…
{5585}{5647}… jsem se cítila jako…
{5647}{5694}… bych u vìdìla, kdo to je.
{5694}{5732}Yano Motoharu.
{5732}{5764}Budeš tøídním prezidentem.
{5764}{5797}Mìla jsem pravdu…
{5797}{5844}Nemyslíte si, e ta nominace byla tak trochu rychle rozhodnutá?
{5844}{5939}Ale nikdo nenominoval nikoho jiného nebo sám sebe, take…
{5939}{6029}Já nìkoho nominuji. Nominuji sebe jako více prezidenta.
{6029}{6092}To jsi celı ty, volíš z toho lehkou cestu ven…
{6092}{6138}Yano-kun jako více prezident, huh?
{6138}{6228}Ah… umm, také bych ráda nìkoho nominovala…
{6228}{6278}… jako tajemníka, Mizuharu-san.
{6332}{6367}/Mizuhara/
{6386}{6448}Myslela jsi Mizuguchi-san?
{6586}{6671}Take nakonec jsem se stala tøídním prezidentem já…|/Pøiøadím všem úkoly a rozhodnu o tøídních zámìrech./
{6686}{6712}To bylo od tebe pìknì hrubé.
{6712}{6761}Lhal jsi mi pøedtím, nebo ne?
{6761}{6842}Ahh… byl jsem víc hrubı ne ten kdo zapomenul nìèí jméno?
{6875}{6933}Tenhle kluk je jaksi otravnı…
{6933}{7005}Ale nebyla to opravdu moje chyba, e jsem zapomnìla její jméno…?
{7005}{7064}Take, um… ty…
{7064}{7118}Jaké bylo zas tvoje jméno?
{7180}{7255}Hej, zajímám se o to, jestli mìl Yano-kun pøed tím pøítelkyni…
{7255}{7322}Slyšela jsem, e chodil s hodnì rùznımi dívkami…
{7322}{7355}Mladšími i staršími.
{7355}{7380}Opravdu?
{7380}{7426}Já nevím. Øíká se to.
{7426}{7467}Zkusíme se zeptat Yamamoto-san!
{7507}{7596}Vypadá to, e jsem v jiné tøetinì tøídy…
{7596}{7662}Neptejte se mì na nìj. Nevím. Nezajímám se o to.
{7708}{7747}Øekla, e neví…
{7772}{7807}Pøátelé.
{7807}{7822}Hlupáku.
{7880}{7903}Vyšší støední škola…
{7971}{8015}… není to takové zábava, jak jsem si pùvodnì myslela.
{8049}{8106}Nano, u jsi skonèila se svou poraní schùzí ?
{8106}{8117}Jo.
{8117}{8143}Jaké to bylo?
{8143}{8197}Umm… moc jsem tomu nerozumìla…
{8197}{8224}Coe?!
{8224}{8264}Mìj se! |/Èau!/
{8290}{8384}Zajímalo by mì jestli se taky mùu pøihlásit do klubu…
{8384}{8412}Takahashi.
{8432}{8496}Jak dlouho trvala tvoje poradní schùze?
{8516}{8535}Sedm minut.
{8535}{8558}Sedm minut?
{8558}{8582}Deset minut.
{8582}{8616}Ne, zabralo to pùl hodiny.
{8616}{8656}Opravdu, zabralo to jen pìt minut.
{8656}{8693}Jen ertuji, bylo to patnáct.
{8720}{8752}Hlupáku.
{8752}{8805}Vánì to nechci slyšet od tebe.
{8805}{8821}Èau, èau.
{8892}{8910}Èau--
{8981}{9009}Umm, èau, èa---
{9128}{9151}Co?
{9151}{9229}Myslela jsem, e jsi mì neslyšel, tak…
{9251}{9282}Ahoj… èau, èau…
{9369}{9383}Co…?
{9495}{9514}Ahojky.
{9582}{9659}Ne, ne, to nebylo, e moje srdce bilo rychleji pro nìj… jen mì pøekvapil.
{9659}{9741}Já jsi prostì nemyslím, e by na mì mìl takhle volat.
{9741}{9786}To proto… to proto…
{9786}{9804}Máš nìjakı problém?
{9862}{9956}Já jen nerozumím úplnì matematice a tak jsem frustrovaná.
{9956}{9990}Co? Ty plánuješ ve své profesi pouívat matematiku?
{9990}{10042}N-ne, já plánuji jít na soukromou umìleckou školu…
{10042}{10088}Tak proè se trápíš vìdou?
{10088}{10155}Nemyslíš si, e by bylo moudøejší místo toho vyuít tenhle èas na umìní?
{10155}{10240}Ale… kdy jsi v nìèem špatná, tak…
{10240}{10325}Kdy jsi v tom špatná, nic z toho nebude.
{10325}{10377}Vùbec ti to nepomùe.
{10377}{10420}Nechápu, proè lidé dìlají zbyteèné vìci, které nemají stejnì rádi.
{10420}{10461}Hej! Slyšela jsem, e pøíští tıden je školní vılet.
{10461}{10513}Ale máme pøed tím testy…
{10513}{10558}Nevím, co budu dìlat. Ještì jsem se neuèila.
{10558}{10594}To bude pro tebe hraèka, Nano.
{10594}{10702}Vùbec ne! Prakticky jsem se vzdala. Pravdìpodobnì dostanu nula bodù nebo cosi z matematiky.
{10702}{10727}Nula bodù, jo?
{10805}{10875}Neuvìøitelné… Opravdu mám nula bodù…
{10908}{10923}Takahashi.
{10923}{10939}Ano?!
{10939}{11002}Mìli by jsme nejspíše rozhodnout, kdo bude mít na starost blíící se vılet…
{11002}{11045}Ah… lidi do èela tımu, jasnì…
{11045}{11074}A o zakoupení vìcí na vılet…
{11074}{11107}Ah, opravdu? O zakoupení vìcí?
{11107}{11159}Je to námaha, take mùeš se o to s dívkami postarat?
{11159}{11202}Jasné, jas- huh?! Proè?!
{11299}{11315}Je to vidìt, víš?
{11425}{11539}T-to je… umm…! Jen jsem se necítila dobøe, tak…|/ Budu rád, kdy se s holkami postaráte o nakupování./
{11554}{11631}Ne! Proè musíme vdycky dìlat tyhle otravné vìci?
{11674}{11767}Hej, lidi, úasná zpráva! Známka Takahashi z matematiky byla…|/Pùjdeme! Pùjdeme!/
{11767}{11781}Díky.
{12068}{12119}Nebuï podvedená, nebuï podvedená!!
{12119}{12202}Kdy se takhle usmál, bylo to jen protoe hrozil vyzrazením tvojí známky z matematiky.
{12228}{12273}Nemùeš jít na další stupeò s nedostateènou…
{12273}{12298}/Pøekvapená.../
{12298}{12387}Ale Yamamoto-san, neøíkala jsi náhodou, abych se vykašlala na matematiku, kdy míøím na umìleckou školu?
{12387}{12428}Ale nedostateèná není dobrá, samozøejmì.
{12510}{12643}Jak bych to mohla vyjádøit... jsou situace kdy zaènete nenávidìt všechno kolem sebe
{12818}{12838}To je Yano…
{12872}{12925}Co je s mım srdcem, bušit takhle?!
{13228}{13262}Co to dìláš?
{13262}{13355}Ah… chtìla jsem se kouknout na oblohu, take…
{13355}{13408}Kvùli tìm nula bodùm, co?
{13408}{13460}Dostal jsi to samé…?
{13460}{13534}Já? Já mìl 87 bodù.
{13534}{13562}Coe?!
{13562}{13627}V kadém pøípadì, opravdu si myslíš, e má cenu si tímhle zatìovat hlavu?
{13674}{13704}To by mì taky zajímalo…
{13704}{13824}Hm. Kadı je v nìèem dobrı. Bude to v poøádku, kdy jen zkusíš bıt nejlepší v tom tvém oboru.
{13824}{13902}A mimo to, nemyslíš si, e získání nula bodù je pìknì pùsobivé i jinak?
{13959}{14006}Posaï se.
{14057}{14136}Yano, je nìco v èem nejsi dobrı?
{14136}{14151}Já?
{14151}{14182}Vsadím se, e skoro nic.
{14182}{14197}Ale jo!
{14197}{14215}Leš.
{14215}{14244}Ale je, ale je.
{14244}{14286}Jsem moc populární mezi dìvèaty.
{14319}{14344}Jsi na hlavu?
{14426}{14443}Co?
{14469}{14530}Kromì toho, máš problémy s nìèím jinım?
{14530}{14549}Jo.
{14549}{14639}Vyènívám, take mì poøád nìkdo sleduje.
{14639}{14714}Tøebae je to otravné, normálnì mì vybírají do tøídního vıboru.
{14752}{14776}V noci nemùu spát
{14810}{14900}A nesnáším… nevypoèitatelné dívky.
{15016}{15055}To je pìt! Yeah!!
{15055}{15131}Hej… nic z toho není problém.
{15131}{15205}A kdy jsi øekl "nevypoèitatelné", opravdu máš právo takhle mluvit o ostatních?
{15205}{15254}Co? Dìláš si ze mì srandu?
{15254}{15296}Navzdory mému vzhledu, jsem pìknì umínìnı.
{15319}{15340}Nevyhlíím tak?
{15340}{15356}Vùbec ne.
{15389}{15483}Zajímalo by mì, jaké typy dívek se do Yana zamilovávají...
{15514}{15576}Zajímalo by mì, do kterıch typù dívek se Yano zamilovává…
{15627}{15759}Hej… kdy si vyjdeš s holkou, která je nevypoèitatelná, co budeš dìlat?
{15794}{15890}Zajímalo by mì, proè chci znát jeho odpovìï…
{15928}{15946}Yano?
{16007}{16030}Zabiju jí.
{16108}{16136}Jen ertuju.
{16217}{16324}Nejsem si jistá, proè jsem se zeptala…
{16324}{16422}Yano, jestli budeš mít nìjaké problémy, vyslechnu tì.
{16496}{16634}Ano… všechno si vyslechnu. Právì jsi mì poslouchal mluvit dokola a dokola, take…
{16634}{16678}To je špatné. Já nemám ádné problémy.
{16702}{16734}Ten úsmìv je tu zase…
{16825}{16882}Nemùu uvìøit, e se tohle stalo.
{16912}{16992}Tohle se definitivnì stává nejvìtší chybou mého ivota…
{17029}{17129}Yano… Mám tì---
{17129}{17182}Oh, a o tvıch problémech…
{17182}{17219}To je pøece samozøejmé pro ivot, nemyslíš?
{17341}{17399}No… jo.
{17720}{17857}V tu chvíli jsem nevìdìla, co tím Yano myslel.
{17957}{17985}Uh… ummm…
{17985}{18053}Všimnìte si tìchto dùleitıch bodù bìhem našeho pochodového maratónského školního vıletu.
{18053}{18103}Na start se dopravíme autobusem.
{18103}{18192}Celá délka je 42 kilometrù, a… Yano!
{18192}{18250}Vysvìtli kadému tyhle dùleité vìci!
{18250}{18285}Pouívání mobilù je zakázané.
{18285}{18320}A ádné zastavování v obchodech bìhem cesty!
{18320}{18361}Oh, Take.
{18361}{18408}Nepouívej svùj mobil.
{18408}{18443}O-okey.
{18443}{18487}Jaké to bylo?
{18512}{18612}Aaaa…. Cítím se opravdu uboze, zamilovat se do nìkoho tak neuvìøitelnì bezohledného jako je on.
{18688}{18718}Ah, jsme tu!
{18718}{18749}Jdu sesbírat mobily všech!
{18749}{18780}Já ádnı nemám.
{18780}{18828}Opravdu ádnı nemá…?
{18828}{18856}Co je to za úšklebek?!
{18856}{18930}Øíkám vám, e jsem si ho zapomnìl vzít.
{18930}{18988}Co? Yano sebou opravdu ádnı mobil nemá?
{18988}{19036}Ah, venku je opravdu hezky.
{19036}{19073}Mohla by to bıt skuteènì zábava!
{19073}{19111}Zajímalo by mì, jestli budeme schopní zvládnout celıch 42 kilometrù…
{19142}{19211}Hej… já chci opravdu obìdvat spoleènì s Yanem…|/Heh, opravdu?/
{19230}{19264}Nano, mluv s ním kvùli nám!
{19264}{19285}Já?
{19285}{19359}Jasné, jste pøátelé, kdy ty jsi prezident a on více prezident.
{19359}{19389}Prosím! Poèítám s tebou!
{19389}{19470}Ah… myslím, e nemám na vıbìr, co?
{19598}{19624}Hej!
{19624}{19645}Motoharu!
{19694}{19791}Chceš se mnou obìdvat, Yamamoto-san?
{19791}{19845}Co to dìláš, pozvání Yamamoto-san…?!
{19845}{19867}Získej taky Yana!
{19867}{19902}Moje naèasování nevyšlo…
{19902}{19968}Vy nechcete obìdvat s Yamamoto-san?
{19968}{20049}No, ono to není tak e nechceme, ale je dost tìké s ní mluvit.
{20049}{20092}Vychází z ní tmavá aura…
{20092}{20156}T-to neøíkej.
{20156}{20232}Dobøe, to je fajn a vùbec… ale nezapomeò taky pozvat Yana a ostatní.
{20232}{20249}Okej.
{20276}{20325}Nenávidím ho.
{20325}{20359}Ale ne, co budu dìlat?
{20365}{20432}Kdy teï pozvu Yana, bude to vypadat, jako bych chtìla trápit Yamamoto-san…
{20469}{20620}Aèkoliv ho témìø nikdo nenávidí, zajímalo by mì, proè Yamamoto-san ano.
{20657}{20693}Hej… kdo je ten kluk?
{20717}{20760}Jo, to je Takeuchi-kun.
{20760}{20814}Patrnì byli na niší støední ve stejné tøídì.
{20814}{20872}Ještì teï se zdá, e na sobì poøád lpí.
{20905}{20942}To je zastávka v pùlce cesty!
{20942}{20969}Uteklo to rychle!
{20969}{21004}Myslíš, e budeme schopné ujít celıch 42 kilometrù?
{21004}{21055}Jasnì. Hraèka.
{21055}{21083}Dokázaly jsme to!
{21083}{21095}Jo!
{21095}{21137}Yano.
{21137}{21238}Nechtìl by jsi obìdvat se všemi?
{21238}{21327}Jo, jasnì, ale… dokáeš se nás udret s naší rychlostí?
{21371}{21434}Ah… zaèínám bıt unavená…
{21434}{21487}Krajina se nemìní ani trochu…
{21487}{21515}Zaèínám bıt znudìná pøírodou.
{21515}{21572}Mìli bychom si odpoèinout na 20-ti kilometrové zastávce…
{21572}{21645}Hej… chcete si teï sednout a naobìdvat se?
{21645}{21674}Jsem vyèerpaná.
{21674}{21701}Jo...
{21701}{21763}Nakonec,  stejnì jsme ztratili stopu Yana a ostatních.
{21763}{21793}Yamamoto-san?
{21826}{21868}Jsi v poøádku?
{21868}{21893}Chceš napít vody?
{21920}{21967}Huh? O co jde?
{21967}{21992}Takeuchi-kun.
{21992}{22039}Necítí se dobøe…
{22039}{22102}Myslíš, e uèitelé pojedou kolem v autech?
{22102}{22205}Ah… Myslím, e jedí obìd v chatì zpátky od nás 20 kilometrù na pùli cesty...
{22205}{22247}Budou tady tak za hodinu nebo dvì.
{22247}{22282}Hodinu nebo dvì, jo?
{22282}{22365}Teï najdu nìjakého èlovìka, kterı se s nimi mùe spojit a dám jim vìdìt.
{22365}{22385}Díky.
{22385}{22451}Yamamoto-san, mùeš sníst nìjaké ovoce?
{22451}{22480}Tøeba tì osvìí…
{22514}{22553}Vzala jsem s sebou nìjakı studenı dus.
{22575}{22600}Co budeme dìlat?
{22600}{22664}Doufám, e jí bude lépe, kdy si dá na chvíli pauzu…
{22664}{22734}Zajímalo by mì, jestli budeme èekat na uèitele.
{22734}{22844}To není dobré… Jsem jediná, u které se pøedpokládá, e bude uválivá, ale neumím nijak pomoct…
{22844}{22881}Huh? Nìkdo jde zpátky touhle cestou.
{22881}{22914}To je Yano.
{22914}{22960}Huh? Proè?
{22960}{23010}Mluvil jsem s Takem.
{23029}{23045}Mluvil s ním?
{23045}{23094}Hej. Snìdla jsi svaèinu?
{23094}{23134}Máš pøíznaky dehydratace?
{23134}{23167}Lízala jsi nìco slaného?
{23167}{23190}Máš horeèku?
{23391}{23406}Má horeèku.
{23406}{23454}To ne! Co budeme dìlat?
{23454}{23494}Mìli bychom sehnat nìkoho s autem, aby sem pøijel.
{23494}{23548}Ale jak kontaktujeme uèitele?
{23593}{23644}Ah, to jsem já. Kde jste právì teï?
{23644}{23678}Okolo 25-ti kilometrù od nás?
{23678}{23731}Jak ještì dlouho ne se dostanete k cíli?
{23731}{23754}Další dvì hodiny?
{23754}{23837}Uèitelé ještì neprojeli kolem vás, co? Ah, okay.|/Ten kluk… mìl ho ukrytı…/
{23837}{23878}Jdu se vrátit do zastávky, co je v pùlce cesty.
{23878}{23917}Do zastávky v pùlce?
{23917}{23998}Právì obìdvají v domì, kde podávají barbecue, v zadním motelu.
{23998}{24078}Kdybych se k nim teï dostal, mohou bıt za pìt minut zpátky, kdy budou øídit.
{24078}{24111}Vy zùstaòte tady.
{24147}{24195}Hej, má sebou nìjaká z vás mobil?
{24195}{24250}ádná z nás… vzali nám je.
{24250}{24296}Huh? A co vy dvì?
{24296}{24320}Ne...
{24320}{24346}Já ten svùj taky nemám.
{24360}{24434}Proè, vy holky, nemáte kontrolu nad svımi mobily?
{24434}{24481}"Proè?"
{24481}{24510}Já mám svùj…
{24537}{24609}Já mám svùj mobil, take budeme v pohodì…
{24628}{24654}No ne...
{24681}{24717}Ah, pùjdu s tebou.
{24717}{24760}To je v pohodì. Zùstaò vzadu.
{24760}{24821}Ale já jsem opravdu zodpovìdná za tuhle vıpravu, take…
{24821}{24874}Kdy mì zaèneš zpomalovat, nechám tì vzadu.
{24965}{25012}Tvoje èíslo se nezmìnilo, e?
{25172}{25288}Znají svoje èísla na mobil, protoe byli ve stejné tøídì na niší støední, co?
{25288}{25360}Proè jdeš jak šnek? Vánì tì nechám vzadu.
{25360}{25390}Jo...
{25390}{25523}Ah… Jsem opravdu špatnı èlovìk… Starám se o nìco jiného, kdy se Yamamoto-san cítí takhle…
{25546}{25634}Hej, byli jste si s Yamamoto-san blízcí na niší støední?
{25634}{25707}Ani ne. Sotva se mnou mluvila.
{25707}{25752}U je dlouho pìknì tichá.
{25782}{25810}Aha...
{25810}{25858}Take byla dlouho stejná jako teï…
{25858}{25890}Co myslíš tím "jako teï"?
{25890}{26036}Hm, nedává moc najevo svoje pocity… Zajímalo by mì, jestli je jedináèek.
{26036}{26087}Není.
{26087}{26119}Mìla starší sestru.
{26119}{26178}Opravdu?
{26178}{26227}Hm… huh? Minulı èas?
{26227}{26305}Hm, jo. Zemøela minulé léto.
{26410}{26441}Nemìla jsem ponìtí…
{26441}{26491}A není to takhle lepší?
{26491}{26544}Zdá se jako typ, kterı nemá rád, kdy ho nìkdo lituje.
{26584}{26621}Jak zemøela?
{26647}{26698}Byla to autonehoda.
{26698}{26760}Yano… šel jsi na pohøeb?
{26760}{26785}Ne.
{26857}{26890}Pøeci jen byly letní prázdniny.
{26967}{27080}Já… ještì nikdy jsem nezaila nìco jako je tohle, take tomu moc nerozumím,  ale…
{27080}{27151}Musí to bıt opravdu tìké, co?
{27191}{27216}Pravdìpodobnì...
{27314}{27404}Já jsem… opravdu lhostejná holka…
{27404}{27540}Tøebae jsme mìli tuhle diskuzi, mé srdce bilo opravdu rychle kvùli Yanovi…
{27556}{27576}Yamamoto?
{27576}{27626}Vypadá to jako by se sloila s horeèkou.
{27662}{27700}25-ti kilometrová zastávka, e?
{27700}{27718}Ano.
{27718}{27767}Take, pane uèiteli, poèítám s vámi.
{27767}{27828}Ah, ano. Nemìl jsem ádné pivo, take by to mìlo bıt v poøádku.
{27828}{27893}H-hej, nemìli by jsme jet s ním?
{27893}{27935}Není tady nic víc, co by jsme mohli udìlat, ne?
{27935}{27970}Nechme zbytek na nìm.
{27970}{28069}Dvì porce hovìzích ebírek a dva èaje Oolong, prosím!
{28069}{28102}Ohromil jsi mì…
{28125}{28175}Øíká se, e jeden by mìl bıt v ivotì efektivní, ne?
{28175}{28242}Ah… a  také nìjaké kravské jazyky a grilované hovìzí drùbky, prosím.
{28242}{28278}Fajn... cokoliv.
{28320}{28331}Yano.
{28377}{28410}Dneska...
{28410}{28477}Opravdu pomohlo, e jsi tu byl.
{28477}{28533}D-dìkuju.
{28651}{28769}Ještì jsem nikdy nevidìla nìkoho s tak bezstarostnım úsmìvem jako má on…
{28852}{28914}Ah, jdete opravdu pozdì! Co jste dìlali?
{28914}{28973}Uèitel vzal Yamamoto-san domù.
{28973}{29012}Vypadá to, e to byla jen bìná chøipka.
{29012}{29050}Opravdu? Díky bohu.
{29091}{29209}Ummm… autobusy budou opouštìt parkovištì rùznımi smìry, take se prosím ujistìte, e jste nastoupili do toho správného.
{29209}{29234}Rozumìli jste?
{29332}{29471}Aèkoliv jsme rozdìlení…Chci ho znovu vidìt…
{29575}{29603}Takeuchi-kun.
{29603}{29614}Hm?
{29614}{29714}Díky za to pøed tím. Opravdu nám to pomohlo.
{29714}{29749}Ah, jak to vyšlo?
{29749}{29874}Dobøe, získali jsme uèitele s autem a ten jí odvezl domù.
{29874}{29911}Opravdu? To rád slyším.
{29911}{30007}Tak jsem pøemıšlela, e jsi byl opravdu skvìlı… uvaování ve prospìch tvıch pøátel.
{30007}{30032}Huh, opravdu?
{30072}{30117}Jasné… hodnì se toho stalo, take…
{30139}{30166}Hodnì?
{30166}{30214}Zemøela minulé léto.
{30234}{30293}Jo… mám nìjaké tušení…
{30339}{30373}Take jsi o tom slyšela…
{30373}{30387}Jo.
{30411}{30438}Musí to bıt tìké, co?
{30438}{30494}Jo…kdybych to byl já, tak bych nebyl schopnı se z toho dostat…
{30494}{30551}O-opravdu…?
{30551}{30712}Nikdo mì blízkı ještì nezemøel, take to moc nechápu, ale zajímalo by mì, jak se asi musí cítit…
{30712}{30775}Pøemıšlím, jestli èlovìk jen poloí zaráku do svého ivota…
{30775}{30845}Aèkoliv, cítím se, jakoby byli jinı druh osoby…
{30845}{30948}Jo… ale nemùeš to posoudit jen podle vnìjšího vzhledu, take…
{30948}{31002}Jasnì.
{31002}{31071}Ale opravdu… je to nìco zlého.
{31071}{31092}Opravdu?
{31092}{31108}Jo.
{31136}{31306}Nikdy pøed tím jsem je nevidìl breèet… a myslím e je lepší, kdy budou jen breèet nebo je rozptılit…
{31323}{31412}Ale nevím, jestli se u pøes to pøenesli nebo jsou kvùli tomu poøád smutní…
{31412}{31488}… nebo nìco jiného…já prostì nevím.
{31488}{31527}Je to vánì dìsivé.
{31527}{31571}Nemusíš o nich takhle mluvit!
{31592}{31691}Øíkat, e jsou "dìsivı". Já jsi myslím, e jsou opravdu silní.
{31691}{31737}No, jo, ale…
{31737}{31859}Já si myslím, e není dobré to vdycky zadrovat..
{31859}{31962}Mùe to bıt velmi frustrující, protoe jste pøátelé. Nemyslíš?
{31962}{32057}Takeuchi-kun, jsi opravdu tak blízko…?
{32057}{32160}Huh? Aèkoliv jsme v jinıch tøídách, tak jsme poøád pøátelé, ne?
{32213}{32234}Hej...
{32281}{32324}O kom to mluvíš…?
{32384}{32460}Dobré ráno! |/-Zajímalo by mì, jestli se odráím-/
{32460}{32484}Dobré.|/-Zajímalo by mì, jestli se odráím-/
{32484}{32516}Jsi opálená.|/-Zajímalo by mì, jestli se odráím-/
{32516}{32546}Chtìla bych to celé oloupat.|/-Zajímalo by mì, jestli se odráím-/
{32568}{32599}V tomhle smìru máš hezkı oblièej.|/-Zajímalo by mì, jestli se odráím-/
{32599}{32667}Co? Tohle normálnì øíkáš dívkám?|/ve tvıch drahocennıch oèích/
{32667}{32691}Tak co "tohle je docela  hezká tváø".|/ve tvıch drahocennıch oèích/
{32691}{32711}To je tak samá vìc!|/ve tvıch drahocennıch oèích/
{32711}{32737}-ve tvıch drahocennıch oèích-
{32737}{32889}Je opravdu drzı, nafoukanı, bezohlednı a je nemoné s ním jednat, ale…|/Zajímalo by mì, jak mùe bıt vdycky šastná/
{32918}{32977}Opravdu ho miluju...|/Zajímalo by mì, jak mùe bıt vdycky šastná/
{33015}{33037}Co je?|/Zajímalo by mì, jak mùe bıt vdycky šastná/
{33053}{33220}-na okenní øímse, kde vdycky svítí slunce?-
{33241}{33351}Starší sestra Yamamoty-san, ne?|/Schovávám své opravdové pocity a bušící srdce/
{33351}{33392}Jo. To proto.|/Schovávám své opravdové pocity a bušící srdce/
{33392}{33462}To nic.|/bolest z toho, e nejde porozumìt popáleninám toho druhého/
{33481}{33544}-bolest z toho, e nejde porozumìt popáleninám toho druhého-
{33544}{33588}Zemøela minulé léto.|/bolest z toho, e nejde porozumìt popáleninám toho druhého/
{33588}{33637}Pravdìpodobnì...|/Chci se smát, chci se smát, dolù k jádru mého srdce/
{33637}{33674}-Chci se smát, chci se smát, dolù k jádru mého srdce-
{33674}{33709}Ty jeden hroznı lháøi.|/Chci se smát, chci se smát, dolù k jádru mého srdce/
{33709}{33763}-Chci se smát, chci se smát, dolù k jádru mého srdce-
{33763}{33835}Byla... Yanova  pøítelkynì.|/Chci se smát, chci se smát, dolù k jádru mého srdce/
{33835}{33918}-Otevøu se ti-
{33918}{34032}-o tom, jak jsem pøedstírala, e musím bıt silná, o tom jak jsem slabá-
{34032}{34085}-o tom co se stalo vèera,-
{34085}{34164}-o všem co nic neznamená.-
{34164}{34280}Budu pokraèovat s milováním tvé osoby.-
{34280}{34430}-Vezmi mì za ruku a pojïme se projít. Yeah!-
{34598}{34806}-Roèní období jenom mì nechávají pozadu-
{34806}{34968}-a odnášejí pro mì dùleitého èlovìka pryè, e?-
{35045}{35161}-Dívám se na tebe. Dívám se na tebe.-
{35161}{35301}-Vdycky se na tebe dívám,-
{35301}{35428}-ale kdy najdu toho èlovìka, jsi to opravdu ty?-
{35428}{35579}-Jsem opravdu smutná, jsem opravdu smutná-
{35579}{35691}-Mohla bych breèet.-
{35691}{35897}-Jak moc citù musím dát na to, abych tì mohla obejmout?-
{35897}{36023}-Ah, chci se smát, chci se smát.-
{36023}{36099}-Hodit všechno za hlavu.-
{36099}{36135}Yano, já…|/Bokura ga ita, Ukázka z druhé epizody/
{36135}{36205}Myslím, e tì mám asi ráda…|/Otevøu se ti/
{36205}{36239}Tak, chceš si nìkam vyrazit?|/Otevøu se ti./
{36239}{36289}Co? Ty mì máš taky rád?|/O vèerejšku, o zítøku/
{36289}{36337}Odhaduju, e jo.|/O vèerejšku, o zítøku/
{36337}{36394}Ne nìjakı druh "mít rád…"|/o naší budoucnosti a o všem, tak moc, e to ani sama nemùu pobrat/
{36394}{36447}Ptám se tì, jestli mì máš opravdu, opravdu rád.|/o naší budoucnosti a o všem, tak moc, e to ani sama nemùu pobrat/
{36447}{36493}Promiò... já nevím.|/o naší budoucnosti a o všem, tak moc, e to ani sama nemùu pobrat/
{36493}{36532}Co to má znamenat?|/Nemusíš mi nic slibovat/
{36532}{36590}Moje pøítelkynì mì podvádìla.|/Nemusíš mi nic slibovat/
{36590}{36655}Byla s jinım klukem, kdy zemøela.|/Jen udruj krok. Yeah!/
{36655}{36692}Byl to její pøedešlı pøítel.|/Jen udruj krok. Yeah!/
{36692}{36749}Nikdy by je nenapadlo, e se navzájem…|/Jen udruj krok. Yeah!/
{36759}{36826}Pøeklad + korekce: Myia Kurono|Èasování: WelW(etkaAa)-hime
