{1}{1}23.976
{31}{83}Podle všeho, Yano chodil s dívkou, která byla dva stupnì nad tím…
{83}{113}Take má rád starší dívky.
{113}{149}Jak dlouho spolu chodili?
{149}{218}Od jeho druhého roèníku a do léta tøetího.
{218}{297}Ty zvìsti pøišly odnikud a rozšiøovali se jako nièivı poár.|/Jenom pùl roku? To je krátké. Není to dlouho?/
{297}{363}Právì teï proívám opravdu tìké období.
{363}{398}Yamamoto-san!
{398}{457}U je ti na tolik dobøe, abys mohla bìhat pøi tìlocviku?
{457}{473}Jo.
{473}{578}Hej, mìla jsem v posledním testu z matematiky 34 bodù!
{578}{613}Jsem koneènì osvobozená od té nuly!
{613}{697}Odhaduji, e se pøíštì budeš muset dostat nad 56 bodù.
{697}{784}Neuspìješ, kdy budeš mít prùmìr pod tøicet bodù, e?
{784}{817}Co? Opravdu?
{859}{885}U-udìlám vše, co je v mıch silách!
{969}{1046}Yano je poøád stejnı jako vdy…
{1099}{1118}TaSHee's Gang uvádí...
{1118}{1361}BOKURA GA ITA
{1387}{1517}-Proè nemùou jít vìci dobøe mezi-
{1517}{1659}-lháøem, tebou, a uplakánkem, mnou?-
{1659}{1809}-Nevšimneš si mıch stylovıch vlasù-
{1809}{1951}-nebo mého krásného setu nalepovacích nehtù.-
{1951}{2126}-Láska není o nešastnıch slzách, které jsou spolu s tím.-
{2126}{2238}-Tyhle slzy jen zvlhèují moje oèi a zraòují.-
{2238}{2262}-Miluji tohle rozhodnutí-
{2454}{2588}-jen mezi tebou a mnou.-
{2588}{2717}-Chci pøijmout tvoje dychtivé pocity-
{2743}{2879}-a nalézt v tobì navdy zalíbení.-
{2879}{3045}-Navzdory tomu, e nejsi roztomilı, ubreèenému oblièeji a tvojí omezenosti, poøád tì miluji.-
{3262}{3309}To ne! Vùbec si nejsou podobné!|/EPIZODA DRUHÁ/
{3309}{3352}Skuteènì. Opravdu ne.| /Hej, lidi, o èem to mluvíte?/
{3352}{3388}Roèenka Asahi niší støední.
{3388}{3437}Starší sestra Yamamota-san je tady.
{3437}{3470}Vdy víš, tak s kterou Yano chodil.
{3497}{3525}Nano, pojï se kouknout!
{3525}{3611}Hm, já… radši to vynechám…
{3688}{3742}Hele, nemáte nìkdo drobné za 5 tisíc yenù?|(pro pøedstavu je to 38 euro, 1000 korun)
{3742}{3802}Nemáááááám!
{3802}{3819}Fajn...
{3819}{3866}Hej, nemáte nìkdo?
{3866}{3900}Nìjakı z vás drobné za 5 tisíc yenù?
{3967}{4021}Yano se prostì nemìní...
{4021}{4066}Myslím, e je to oèekávané.
{4066}{4123}Od té doby, co jsme se potkali, je poøád takovı.
{4123}{4194}Myslím, e o nìm vùbec nic nevím...
{4194}{4208}Uvidíme se!
{4208}{4228}Mìj se!
{4284}{4332}Ta schùze vıboru trvala déle, ne jsem oèekávala…
{4675}{4716}V jaké tøídì to jen byla…?
{4729}{4755}Tøída 3-5.
{4993}{5044}Omlouvám se ti, Yano…
{5044}{5094}Byla jsem jen zvìdavá…
{5094}{5133}Musí to vypadat opravdu zle…
{5240}{5255}Uka mi to.
{5296}{5374}Ještì jsem se na sebe ani nekouknul.
{5564}{5580}Chceš to vidìt?
{5626}{5646}Ne, opravdu!
{5755}{5786}Myslím, e nakonec chci!
{5786}{5902}Aèkoliv ne za tìhle okolností…
{5902}{5995}Protoe nevím, jakı vıraz mám-
{6034}{6104}Jde jen po hezkıch oblièejích!
{6104}{6173}Je opravdu hezká, co?|/Pøekvapená/
{6173}{6240}Jo, ale to nic neznamená. Jako èlovìk byla ještì lepší.
{6282}{6332}To je konec…
{6332}{6367}Na celé èáøe jsem s ní prohrála.
{6367}{6473}Ona se opravdu… nepodobá Yamamoto-san, co?
{6473}{6523}Myslím, e ne.
{6523}{6584}Kterı z vás se jako první zamiloval do toho druhého?
{6584}{6643}Já do ní. Byla to láska na první pohled.
{6643}{6685}Take si s ní hned zaèal chodit?
{6704}{6794}Ne, chvíli to trvalo. Tenkrát mìla pøítele.
{6794}{6818}Ukradl jsi mu jí?
{6818}{6839}Jo!
{6839}{6887}Er, snaíš se, abych vypadal zle?
{6982}{6998}Co je?
{6998}{7025}Nic...
{7025}{7165}Já jsem jen ještì nikdy nevidìla Yana tak fixovaného na tuhle vìc…
{7165}{7240}Urèitì jsi musel mít rád vychloubání se sní, co?
{7252}{7354}Byla moje první. První, co jsem kdy opravdu miloval.
{7401}{7543}Hruï mì bolela, ale kdy se Yano usmál mezitím, co mluvil, urovnalo se to.
{7543}{7651}Pravdìpodobnì to nechci pøijmout…
{7651}{7715}Existenci nìkoho, koho Yano miloval…
{7893}{7957}Yano, já...
{7957}{8008}Myslím, e tì mám asi ráda…
{8123}{8171}Radši mì ignoruj! Chtìla jsem jen to jen zkusit øí---
{8171}{8204}Take, chceš si nìkam vyrazit?
{8251}{8353}C-co? P-poèkej chví---
{8353}{8401}Ty mì máš taky rád?
{8452}{8470}Jo.
{8470}{8547}P-poèkej vteøinku! Ty jsi váhal!
{8547}{8563}Ale ne.
{8563}{8603}Ale jo! Opravdu jsi váhal!
{8603}{8620}Zapomeò na to!
{8620}{8645}Ne.
{8673}{8705}Opravdu mì máš rád?
{8705}{8752}Jo, myslím.
{8752}{8815}Ne nìjakı druh "mít rád…"
{8815}{8887}Ptám se tì, jestli mì máš opravdu, opravdu rád.
{8944}{9000}Promiò... já nevím.
{9000}{9054}Co to má znamenat?
{9054}{9097}Potom, pojïme na to zapomenout.
{9112}{9154}Nechci nìco jako je tohle.
{9154}{9242}Jestli jsi vyjdeme, chci abys mì mìl taky rád…
{9327}{9351}Fajn.
{9424}{9463}"Fajn"?
{9494}{9561}Pøestoe to bylo první pøiznání, co jsem kdy udìlala…
{9561}{9705}Dostat rychlé a bolestivé "fajn" jako odpovìï…
{9735}{9848}Zajímalo by mì, jestli jsem mìla pøedstírat, e jsem ho neslyšela a øíct "jo…"
{9922}{9943}Yano.
{9984}{10053}Vypadal jsi, jakoby jsi spal.
{10090}{10134}Co? Neumíš to vypoèítat?
{10134}{10156}To je neobvyklé.
{10156}{10216}Yamamoto, uka mi, e umíš doplnit zbytek.
{10216}{10259}Yano, zùstaò tu a dívej se.
{10679}{10739}Yano? Yano.
{10739}{10797}Je ti nìco. Vypadáš bledì.
{10874}{10889}Yano!
{10914}{10952}Tady. Vezmi si to.
{10952}{10992}Je to dobré pro pøípad chudokrevnosti.
{11033}{11057}Jak se cítíš?
{11057}{11114}Je to opravdu vlané a husté…
{11114}{11171}J-je to zbytek mého obìda.
{11171}{11227}Neboj se. Není to prošlé nebo tak.
{11227}{11244}Nejspíš...
{11244}{11264}Hm, jo.
{11264}{11326}Díky bohu… poøád spolu mùeme normálnì komunikovat.
{11326}{11362}Hej...
{11362}{11487}Napøed… budeš mì poøád otravovat, jestli tì mám opravdu, opravdu rád, e?
{11487}{11582}J-jo… Nenazvala bych to "otravováním".
{11582}{11618}Byla jsi docela otrava.
{11637}{11670}Nech mì se tì taky na nìco zeptat.
{11670}{11747}Máš opravdu, opravdu ráda nìkoho jako jsem já?
{11862}{11910}Musíš váhat s odpovìdí, co?
{11910}{11971}Necítíš se, náhodou, stejnì jako já?
{12091}{12129}Hej, jsem opravdu hladová.
{12129}{12174}Chceš si dát nìco sladkého?
{12189}{12213}Huh?
{12213}{12254}Ah, Takeuchi-kun.
{12254}{12317}Obvykle vás tady nevídám.
{12317}{12334}Nakupujete?
{12334}{12407}Ah, mám to. Niší støední Asahi je nìkde tady.
{12407}{12441}Tohle je naše oblíbené místo.
{12441}{12489}To znamená, e Yano sem chodí taky?
{12489}{12523}Moná je tu i teï.
{12523}{12539}Chcete se kouknout dovnitø?
{12564}{12599}To je opravdu dobré.
{12599}{12625}Ah, tady je!
{12672}{12718}Udìlejte místo ještì pro dva.
{12718}{12766}Huh? Kdo to je?
{12765}{12816}Prezidentka mojí tøídy.
{12816}{12844}Tøídní prezidentka?
{12844}{12904}Musí bıt opravdu chytrá.
{12904}{12952}Jo. Speciálnì na matiku.
{12952}{12979}Oh, opravdu?
{12979}{13010}Je dìsivá.
{13038}{13110}Hej, slyšela jsem, e jste ve stejné tøídì jako Yamamoto Yuri, co?
{13110}{13139}To jsme.
{13139}{13202}Musí bıt opravdu temná a otravná.
{13202}{13254}Jo, ona není jako její starší sestra, co?
{13254}{13312}Nejen to, e vùbec není spoleèenská, ale taky je opravdu dìsivá…
{13312}{13369}To je podøízené nìjakému komplexu nebo tak.
{13369}{13423}Ostatnì, ony byly navzájem vdycky srovnávané.
{13423}{13466}Jak to mùete øíct?
{13466}{13501}Co tím myslíš?
{13501}{13616}Nic o ní nevíte. Jen soudíte podle vzhledu. Nechte toho.
{13616}{13702}Huh? Byly jsme ve stejné tøídì tøi roky na støední.
{13702}{13764}Myslím, e o ní víme víc ne ty.
{13764}{13877}Oh, znáte ji tøi roky a to je jediné, co o ní mùete øíct?
{13877}{13917}Ty vùbec nic nevíš.
{13949}{14028}Dokonce ani neumí vyøizovat lidem správnì zprávy…
{14053}{14119}To je proè se zaèali Motoharu a Nana-san hádat.
{14119}{14154}Kdyby se nepohádali,…
{14154}{14243}… tak spolu mohli bıt pøes letní prázdniny a nestalo by s---
{14243}{14278}Nech toho.
{14302}{14368}To není nìco, o èem by jsi tu mìla mluvit.
{14368}{14413}Ah...  p-promiò.
{14487}{14531}Proè jste lidi najednou tak vání?
{14531}{14580}Oh, moje chyba!
{14580}{14646}Neodpustím nikomu, kdo bude oèeròovat Nanu-san.
{14646}{14684}Ah… a o Yamamoty malé sestøièce…
{14704}{14800}Ona je… hm, ona je dobrá, taková jaká je.
{14800}{14834}Není tak špatná, jak všichni øíkáte.
{14834}{14895}Ještì, Takahashi Nano.
{14939}{15001}Tohle není tøída, tak se nechovej jako tøídní prezident. Je to otravné.
{15015}{15040}Au!
{15070}{15100}Umøi, ty blbèe!
{15170}{15201}Co je s ní?
{15475}{15512}Ztratila jsem svojí penìenku.
{15512}{15544}Do háje!
{15772}{15796}Tvoje penìenka.
{15891}{15951}Byla jsi první holka, která mi øekla, abych umøel.
{15951}{15997}Tak mì nech øíct ještì nìco!
{15997}{16069}Debile! Idiote! Blbèe! Zku*vysynu!|/do nìj, do nìj!!! - pozn. èasovatelky :D/
{16069}{16094}Vra mi ji!
{16217}{16287}Stejnì vidíš poøád jen Nanu-san…
{16598}{16638}"Debil, idiot, blbec," jo?
{16675}{16726}A moje mamka není ádná dìvka…
{16762}{16793}Je...
{16840}{16865}prostitutka.
{16904}{16985}A moje pøítelkynì mì podvádìla.
{17126}{17136}Op--
{17136}{17188}Byla s jinım klukem, kdy se stala ta nehoda.
{17226}{17271}Byl to její pøedešlı pøítel.
{17384}{17473}Nikdy by je nenapadlo, e se navzájem…
{17663}{17686}Jen vtipkuju.
{17701}{17773}Já vlastnì nevím, jestli to byla pravda.
{17789}{17813}Aèkoliv, ani nechci.
{17852}{17964}Ale jestli je tady nìjaká vìc, kterou vím jistì, je to takhle.
{17964}{18086}Jestli se takhle cítila, chtìla vidìt jiného kluka, pak…
{18086}{18205}… to musí bıt moje vina, e to tak bylo.
{18270}{18289}Vezmu tì domù.
{18335}{18395}Já… nemùe nalézt ádná slova…
{18436}{18465}Ah, mám SMS.
{18502}{18550}"Kde jsi a co dìláš?"
{18582}{18692}Já… beru… Takahashi… san… domù.
{18692}{18758}Ah… nemusíš mì doprovázet domù.
{18758}{18829}Nemusíš, take proè nezajdeme do fot---
{18845}{18864}Fot...?
{18923}{18994}Proè tøeba nezajdeme do fotobudky se spoleènì vyfotit?
{18994}{19054}Jsem opravdu blbec, kdy se ptám v tuhle dobu. Opravdu poøádnı blbec…
{19072}{19108}Nebyla by lepší nìjaká, které by nás vyfotila celé?
{19108}{19144}Ne… jedna z tìhle bude fajn.
{19144}{19219}Cítím se, jako by to byla vìènost, kdy jsem byl naposled v nìèem takovém.
{19219}{19301}Yano se… usmívá.
{19301}{19362}Kdy tak o tom pøemıšlím… poøád se usmívá.
{19362}{19422}Yano, ty jsi opravdu silnı, co?
{19450}{19518}Normálnì èlovìk nedokáe øíct takové vìci, jaké jsi øekl ty mì…
{19518}{19553}Chystám se stisknout potvrzující tlaèítko.
{19573}{19612}Ah, zamyslel jsem se. Tahle není dobrá.
{19645}{19692}Vypadáš jako ena tisíce tváøí! To je vtipné!
{19711}{19809}A… myslím si, e je mnohem jednoduší svalovat vinu na sebe, ne na nìkoho jiného.
{19809}{19844}Co? Neexistuje z toho jiná cesta ven?
{19844}{19863}Jdeme na to!
{19863}{19918}Není jednoduší obvinit nìkoho jiného?
{19928}{20019}Kdy obviníš nìkoho jiného, jen budeš tvrdohlavı a øíkat, e jim mu neodpustíš.
{20038}{20110}Ale kdy obviníš sebe, mùeš se zase oklepat, do té doby nemùeš ale dìlat nic.
{20110}{20167}A také tímto zpùsobem nebudeš naštvanı.
{20167}{20186}Je to jednoduší.
{20186}{20276}V podstatì, nejsem fér.
{20341}{20386}Mimochodem, zmáèknul jsem potvrzovací tlaèítko.
{20426}{20500}Podívej se na toho òoumu! Vidíš svojí hlavu?!|/Vypadám jako kluk…/
{20518}{20579}A nejenom to… moje hlava je vìtší ne jeho.
{20579}{20638}Vypadám jako nìjaká mimozemská chobotnice nebo jako nìco takového…
{20638}{20682}Jo. Je to roztomilé.
{20682}{20738}Roztomilá…? Jako chobotnice…?
{20738}{20771}Je tu autobus.
{20771}{20804}Take...mìj se.
{21484}{21595}Hej, všichni! Na posledním zasedání rady jsme rozhodli, co budeme dìlat na školním festivale.
{21595}{21703}Bohuel, vìtšina tøíd pøipravuje kavárny, take to dìlat nemùeme. Místo toho…
{21719}{21799}Naše tøetí volba, krátká hra, vyhrála v hlasování!
{21842}{21907}Jak to myslíš "naše tøetí volba"?! "NAŠE"?!
{21907}{21942}Takhashi, spala jsi kdy jsme volili nebo co?!
{21942}{21998}To je protoe jsem prohrála kámen-nùky-papír…
{21998}{22040}Ale je to problém, nebo ne?
{22040}{22107}Protoe si pro tohle vypùjèíš tøídu jako sál…
{22107}{22195}…tak se pøijdou kouknout jen premianti a uèitelé, co?
{22195}{22223}To je trochu chabé…
{22223}{22255}Nemám ádnou motivaci.
{22255}{22384}Poèítala jsem s tím, take jsem myslela na to, co mùu udìlat pro zvıšení návštìvnosti…
{22384}{22440}… a pøišla jsem s perfektním nápadem!
{22440}{22471}A je to…!
{22491}{22523}Hlavní role: Yano Mothoharu (ještì nevíme, co budeme pøedvádìt, ale…)
{22570}{22585}Jak to zní?
{22615}{22637}Tohle je pøivede!|/èasovatelka umøelasmíchy... :D/
{22637}{22668}Pøijdou všechny holky!
{22668}{22686}Do toho!
{22717}{22783}Yano, dneska se rozhodnu, co budeme hrát. Co by jsi chtìl dìlat?
{22783}{22820}Neptej se mì. Dìlej si, sakra, co chceš.
{22820}{22882}N-nemusíš se hned naštvat.
{22882}{22931}Musím po tobì vdycky uklízet nepoøádek?
{22949}{22973}Uklízet po mì…?
{22973}{23007}Co budeš dìlat ty?
{23007}{23112}Já… já jsem pøemıšlela o navrhování kostımù…
{23112}{23156}Musí to bıt pìkné, vdycky si zvolit tu nejlehèí cestu.
{23156}{23229}Nìkdy… umíš bıt vánì parchant.
{23229}{23325}Take kdy nìkdo udìlá cokoliv, co ti není pøíjemné, je to parchant. Chápu.
{23325}{23375}/To je èlovìk, kterı mu pøed mìsícem vyznal lásku…/
{23375}{23496}Jsi jen naštvanı kvùli tomu pøed tím, co? Uznávám, e to bylo trochu ukvapené, ale…
{23496}{23551}Myslím, e nemám dobrı odhad na tyhle vìci.
{23551}{23588}Co jsem øekla pøed tím, byla chyba!
{23588}{23627}O èem to zase mluvíš?
{23627}{23680}Ten malı...
{23680}{23784}K-kdy jsem øekla, e tì mám ráda, mılila jsem se!
{23860}{23891}Øíkal jsem ti to.
{24126}{24242}Já…. u to… prostì nechápu.
{24299}{24340}Ah, jak jsem to mohla udìlat?
{24340}{24417}Má nìjaká z vás pøíbìh zahrnující vradu?! Jeden, kterı nechá hlavního hrdinu umøít?!
{24417}{24463}Milostné pøíbìhy nepøichází v úvahu!
{24484}{24558}Mìla bych ho zabít! Mìla bych ho prostì zabít!|/Vypadá to, jakoby Nana chtìla zabít Yana…/
{24560}{24635}Sakra! Nakreslím tomu ïáblovi  vousy! Jo! Vousy!
{24673}{24694}Takahashi-san.
{24694}{24722}Ano?!
{24742}{24829}Zítra je bìhem obìda studentské shromádìní.
{24829}{24870}Øíkali, e budou pøidìlovat tøídy na festival.
{24870}{24935}O-opravdu? Díky.
{24992}{25039}Hej.
{25039}{25077}Ah, Takeuchi-kun.
{25090}{25125}Promiò za tamten den.
{25125}{25159}Co tím myslíš?
{25159}{25203}Pøestoe jste byli všichni spolu…
{25203}{25284}Ah… to je pro nì denní záleitost.
{25284}{25328}Všichni moc mluví.
{25328}{25378}Mimochodem, slyšel jsem, e vaše tøída pøipravuje hru?
{25378}{25425}Jo. Je to opravdu na nic.
{25425}{25467}Také díky nìmu.
{25467}{25493}Jemu?
{25493}{25519}Yanovi, tomu nièitelovi!
{25574}{25603}Nìco provedl?
{25603}{25695}Nemluvme o nìm, nebo mi upadne pusa.
{25726}{25766}Musel provést nìco, co tì opravdu rozzlobilo, co?
{25766}{25881}Jo! Nìkdy je tak chladnı, e je tìké uvìøit, e mu proudí krev v ilách.
{25881}{25975}Nikdy nemyslí na ostatní! Mìl by bıt trochu víc citlivı!
{25975}{26027}Hlavnì na tebe, e?
{26052}{26176}Pøestoe zkouším to nejobtínìjší, nemám jak mu to vrátit…
{26176}{26251}Kdy se takhle cítím, opravdu mì naštve, kdy vidím nìkoho jako je on…
{26251}{26272}Je nejhorší?
{26272}{26317}Je horší ne to!
{26411}{26477}Ale… lidé stále pøicházejí.
{26515}{26631}Kvùli Yanovi byli všichni nadšení tou hrou.
{26631}{26676}Znáš ten typ lidí, co?
{26676}{26819}Ti, kteøí pøináší fotbalovı míè do vıklenku, take všechny další dìti potìší a jdou hrát na høištì.
{26819}{26860}A kdy tenhle èlovìk odejde…
{26860}{26967}… všichni se jen budou nudit a skonèí s hraním. Ten typ, kterı má opravdu silnı charakter.
{26967}{27055}On je jeden z tìch lidí a já…
{27055}{27117}… opravdu…
{27117}{27205}… obdivuji tuhle jeho èást.
{27246}{27358}Jen vtipkuju! Jestli ještì budu mluvit o tom hlupákovi, nejen moje pusa odpadne, ale i mùj mozek!
{27358}{27381}Mìj se!
{27566}{27606}Take, co si o tom myslíš?
{27606}{27635}Co máš namysli?
{27737}{27844}Od tohoto dne jsme byli opravdu zaneprázdnìní hledáním dobrého scénáøe…
{27844}{27964}…a nemìli jsme ani ponìtí o neuvìøitelné vìci, která se stane za dva dny potom.
{27983}{28052}Co…? Naše… naše…
{28052}{28122}… naše tøída nemá ádnou místnost pro festival.
{28169}{28256}Zítra je bìhem obìda studentské shromádìní.
{28256}{28298}Øíkali, e budou pøidìlovat tøídy na festival.
{28322}{28350}Zapomnìla jsem na to…
{28372}{28432}Slyšel jsem, e naše tøída nejspíš nebude schopná inscenovat tu hru.
{28432}{28491}Opravdu?! To mì ani trochu nerozrušuje.
{28491}{28512}Proè?
{28512}{28607}Slyšel jsem, e Takahashi zapomnìla jít na studentské shromádìní, take jsme nedostali ádnou tøídu.
{28658}{28734}Nejsme kompletnì bez místnosti.
{28734}{28800}Jsou tady ještì otevøené tøídy ve tøetí budovì.
{28800}{28862}Ve tøetí budovì? Ta je od všeho hroznì moc daleko!
{28862}{28917}Nikdo nebude chtít pøijít do téhle chátrající budovy!
{28917}{28954}U se do tohohle nechci plést.
{28954}{28985}Co ta holka dìlala?
{28985}{29102}To není Nanina vina! Slyšela jsem, e èlovìk, kterı rozhodoval o umístìní, zapomnìl na naší tøídu.
{29102}{29176}Nana se snaila tvrdì protestovat, ale øekli jí, e je moc pozdì na zmìnu.
{29176}{29306}Vùbec jí neposlouchali… øekli, e to byla její chyba, kdy zapomnìla na studentské setkání.
{29353}{29394}Takahashi.
{29394}{29427}Kdy je dneska setkání?
{29472}{29517}Mìlo by právì konèit…
{29517}{29574}Myslíš, e tam budou ještì nìjací lidé?
{29574}{29593}Moná.
{29593}{29613}Tak já jdu.
{29613}{29633}Ale...!
{29633}{29716}Bude to v poøádku. Kdy se nìco stane, pøebírám za to zodpovìdnost.
{29716}{29756}U si s tím nemusíš dìlat starosti.
{29831}{29881}U si s tím nemusíš dìlat starosti.
{29947}{29986}O tøídním rozdìlení…
{30094}{30198}Yano a já… jsme jiní.
{30198}{30301}Co? Øíkám ti, e u bylo rozhodnuto. Prostì pouijte jednu ze zbylıch místností.
{30301}{30423}Øíkám vám, e zbylé místnosti nejsou dobré, take to zmìòte.  |/Yano mám jinı zpùsob myšlení ne vìtšina lidí…/
{30469}{30572}Zajímalo by mì, kdy jsem k nìmu zaèala cítit tyhle pocity…
{30612}{30663}Pøestoe je totálnì bezohlednı, je také vánı.
{30663}{30751}Pøestoe si useknul rohy, je spolehlivı.
{30844}{30890}První školní budovu bylo nemoná získat, ale…
{31147}{31273}Proè poøád… popíráš sám sebe, Yano?
{31288}{31387}Myslím tím… u nikdy jsi po mì nechtìl uklízet nepoøádek.
{31563}{31679}Nakonec, já jsem prostì moc hrdá, moc slabá, "kamarád" kadého…|/-Buï tady…. vdycky- /
{31679}{31748}mám moc velkı pocit zodpovìdnosti, ale nakonec nejsem spolehlivá…|/-Buï tady…. vdycky-/ 
{31748}{31788}a jsem jen bláznivı zbabìlec...|/-Buï tady…. vdycky-/
{31788}{31827}Co je s tebou?|/-jsem tu, koukej-/
{31827}{31979}Všechno to vystihuje jednoho èlovìka, kterı je a moc dobrosrdeènı! Nemám o nièem ani ponìtí… Vyznala jsem se moc rychle… Moc se spoléhám na ostatní…|/-jsem tu, koukej-/ 
{31979}{32007}Jinak øeèeno…|/-Buï tu… se mnou-/ 
{32008}{32019}Hlupák?|/-Buï tu… se mnou-/
{32019}{32052}Jo.|/-Buï tu… se mnou-/
{32052}{32113}se taky nesnaím o vtipnou satirickou poznámku!|/-Jako teï, navdy…-/ 
{32166}{32236}Jene já si nemyslím, e je to tak špatné.|/-"Poprvé" cos mi to dal-/
{32236}{32256}Co?|/-"Poprvé" cos mi to dal-/ 
{32256}{32294}Bıt dobrosrdeènı.|/-vypadá to, e bude-/ 
{32294}{32321}A...|/-vypadá to, e bude-/
{32381}{32433}Nemyslím si, e pøiznání…|/-pøetékat v mıch dlaních-/ 
{32433}{32485}… byla chyba.|/-pøetékat v mıch dlaních-/
{32485}{32602}-kdy moje se moje srdce zachvìlo samotou-
{32630}{32709}Co… tím myslíš?|/-Vypadá to jako by se chtìl kadı ztratit-/ 
{32709}{32755}Huh? Kdo ví.|/-Vypadá to jako by se chtìl kadı ztratit-/
{32815}{32949}Proè vdycky odbudeš dùleitou otázku slovy jako je "kdo ví" nebo "já nevím"?|/-Jednoho dne, ty-/ 
{32949}{32998}To nedìlám.|/-sis vzal mì-/
{32998}{33075}Mùeš tomu øíkat bezohlednost nebo nìco jiného.|/-sis vzal mì-/
{33094}{33171}Mùeš tomu øíkat jak chceš, ale…|/pøestoe, pøestoe...-/
{33246}{33263}Ale?|/-jsem hodnì nejistá-/ 
{33294}{33315}Ale...|/-jsem hodnì nejistá-/ 
{33334}{33429}Není to neznalost?|/-jsem hodnì nejistá-/ 
{33476}{33511}Tady je...|/-Ale ty jsi poøád natahoval-/
{33534}{33582}Øíká to znovu...|/-Ale ty jsi poøád natahoval-/
{33582}{33619}Popírá zase sám sebe…
{33666}{33690}Ale...
{33733}{33831}Hm… je nejspíš v poøádku tak jak je…
{33939}{34075}-Buï tady… s tím…-
{34075}{34215}-Buï tady… jemná ruka…-
{34215}{34350}-Buï tady…vaše…-
{34350}{34421}-a obejmi mì.-
{34465}{34610}-Cesta, kterou jsem šla vdy sama-
{34610}{34709}-je moc široká, a jen mì dìlá opuštìnou.-
{34752}{34887}-Kdy pùjdeme spolu. Budu naplnìná-
{34887}{35046}-štìstím a bude to prostì fajn.-
{35089}{35227}-Kdy se smìješ-
{35227}{35363}-chci se smát taky.-
{35363}{35505}-Ještì… ještì…-
{35505}{35652}-To vypadá, e budu jediná, kdo se ztratí-
{35652}{35805}-Vìtøe… prosím, zlehka mu øekni-
{35805}{35882}-o mıch pocitech k nìmu.-
{36105}{36127}Bokura ga ita, Ukázka z tøetí epizody…
{36127}{36189}Øíkají tomu druh "slepoty".
{36189}{36252}Ty jsi se opravdu ještì nezamiloval do nikoho pøed tím!
{36252}{36315}Tìmhle lidem se øíká "nevyspìlí co-ví-všechno".
{36315}{36389}Pospìš a opravdu se zamiluj.
{36391}{36422}Yano!
{36422}{36505}Yano, moná tady není nikdo, koho opravdu miluješ…
{36505}{36576}… a moná tohle pro tebe bude opravdu smutné, ale…
{36576}{36614}… sleduji tì, take…
{36614}{36680}… vdycky tì sleduji, take…
{36680}{36724}Vdycky se po tobì dívám, take…!
{36805}{36830}Pøeklad a korekce: Myia Kurono|Èasování: WelW(etkaAa)-hime
{36830}{36921}Bokura ga Ita, dívejte se pøíštì...
