{1931}{2030}Pøišli jsme o 300 zlaákù|a to jenom kvùli tobì.
{2031}{2115}Nevrátíme se s prázdnıma rukama.
{2116}{2214}Kdy máš prázdnı ruce,|podrel bys mi tohle?
{3059}{3160}Je pravda, e si tì najali|za blbejch 20 zlaákù?
{3161}{3191}Jo.
{3209}{3339}Ten meè, co jsme ukradli,|byl dar od samotnıho Shoguna.
{3340}{3461}A oni ti za jeho vrácení|zaplatìj jenom 20 zlaákù?
{3520}{3550}Ty blázne!
{3551}{3620}Je to malı a chudı klan.
{3622}{3731}Chtít za meè 300 zlatejch...|To vy jste blázni.
{3788}{3851}Dr hubu! Proklínám tì!
{3951}{4028}Vypadá to na nepøíjemnou bouøku.
{4029}{4083}Mìl bych sebou hodit!
{6270}{6339}Oh, to je mi líto.
{6340}{6402}To ale byla zatracená bouøka!
{6403}{6492}Jo to byla! Strhlo mi to støechu|a vystrašilo enu tak,
{6493}{6544}e z toho porodila.
{6545}{6596}Bylo to fakt nìco.
{6597}{6649}To je u tvoje sedmı dítì, co?
{6650}{6698}Ne, devátı.
{6699}{6806}Svatá prostoto!|Ty musíš mít svojí enu vánì rád!
{6848}{6963}Není to Sakichiho dcera z vesnice Shimoda?
{6999}{7059}Co je to s ní?
{7240}{7289}Co se ti stalo?!
{7429}{7509}Všichni... mrtví...
{7530}{7617}Všichni jsou mrtví.
{7644}{7683}Mrtví?!
{7684}{7811}Mor... Ïábel pøichází...
{7984}{8036}Mùj Boe!
{8048}{8129}Tato oblast je uzavøena!|Nikdo tam nesmí!
{8130}{8238}Cesta je uzavøena|dokud epidemie neskonèí.
{8239}{8299}Epidemie?!|K èertu s tím!
{8389}{8438}Co se dìje?
{8440}{8543}Pane, zvìd vèera v noci|vidìl podivnou skupinu muù,
{8544}{8651}jedoucích k vesnici Shimoda.
{8659}{8748}Mohlo by to mít nìco|spoleèného s tou epidemií
{8749}{8834}a tak jsem to pøišel ohlásit,|pane Komoøí.
{8835}{8924}A ty si myslíš,|e to oni rozšíøili mor,
{8925}{9003}kdy projídìli tou vesnicí?
{9004}{9079}To je absurdní!|Proè by to dìlali?
{9107}{9167}Je na tom nìco divného.
{9170}{9219}Nech to bıt.
{9335}{9396}Ale na druhou stranu,|to nemùeme.
{9397}{9468}Toto je rozkaz pro všechny|z tvého Koga ninja tımu.
{9469}{9563}Bìte do vesnice Shimoda a zjistìte,|co se doopravdy stalo.
{9564}{9589}Pane!
{9590}{9693}Ještì jedna vìc.|Jestli se nìkdo z vás nakazí...
{9719}{9768}Rozumím, pane.
{9791}{9873}První skupina pùjde podél|øeky Shirikawa ze severu.
{9875}{9958}Ostatní pùjdou skrz|prùsmyk Taro ze západu.
{9960}{10053}Do vesnice se dostaneme|asi za hodinu. Jasnı?
{10069}{10187}Hikoza je vidìl, bylo jich jen osm.|To pro nás nebude problém.
{10229}{10277}Pamatujte, náš nejvìtší nepøítel je mor.
{10318}{10359}Správnì.
{10687}{10717}Kagero...
{10957}{11039}Chtìli jste mì tady nechat, Hanzo?
{11058}{11148}Máš svoje povinnosti, ne?
{11149}{11250}Zjišování jedù je dùleitá práce.|Na to nezapomeò.
{11265}{11387}Kdy je náš pán mimo panství,|tak mì nepotøebuje.
{11389}{11512}Ne se vrátí...|Jsem jednou z Koga ninjù!
{11555}{11602}Nemùu tì vzít sebou.
{11618}{11693}Všichni tam venku mùete umøít.
{11694}{11748}Jak bych tu mohla
{11749}{11820}jenom tak sedìt a èekat?!
{12312}{12438}Kagero je èím dál tím hezèí.
{12439}{12506}Další dùvod, proè jí litovat.
{12507}{12581}Je to její osud.|Musí to nenávidìt.
{12598}{12688}Staèí. Kde je Hikoza a ostatní?
{12689}{12789}Byli pøímo za náma.|Podívám se po nich.
{13235}{13296}Hej! Co to dìláš?
{13431}{13466}Co to...?!
{14277}{14318}Tam!
{14968}{14987}Kurva!
{15650}{15768}Kagero, vra se a øekni to Komoøímu!
{15845}{15903}Bì, dokud mùeš!
{18213}{18328}Zavøi hubu a budeš ít o nìco dıl.
{18330}{18435}Mì je to vlastnì jedno.|I mrtvá holka mùe dobøe poslouit.
{18535}{18584}To je lepší.
{18964}{19027}Mám tady práci.|Odpal!
{19055}{19114}Neslyšels?
{19501}{19651}Cesta je zavøená, tak jsem šel zkratkou.|No a teï jsem se ztratil.
{19652}{19711}Mùeš mi øíct,|kudy se dostanu do Kakio?
{19814}{19862}Mùj nejlepší klobouk.
{19863}{19944}Snad jsem ti jasnì øek,|abys vypadnul!
{20374}{20448}Dobrej pokus.|Jen co vyøídím toho zmetka
{20449}{20523}udìlám si èas i na tvojí smrt.
{20624}{20774}Copak? Lituješ, e si neutek|dokud to ještì šlo?
{20814}{20929}Ale ne. Jen pøemıšlím|o tvém tìle.
{20983}{21090}Nemùe bıt pøece jako skála,|úplnì všude!
{21254}{21299}Tudy!
{21824}{21864}Tessai!
{21999}{22099}Opravdu nevypadáš dobøe.|Ale není nutné, abys je pronásledoval.
{22118}{22162}Zabiju ho!
{22165}{22263}Ne, to neudìláš.|Nezapomeò na naši misi.
{22264}{22374}Ber má slova, jako pøíkaz Lorda Gemmy.
{22383}{22428}Rozumìls?
{22449}{22499}Mùeme jít?
{22884}{22964}Kdo byl ten magor?
{22985}{23059}Zapomeò na to.|U ho stejnì nechci znovu potkat.
{23095}{23216}Jsem tvım dluníkem.|Jsem Kagero, z Koga ninja tımu.
{23264}{23411}Jubei. Kibagami Jubei.|Jsi v poøádku?
{23439}{23504}Nepotøebuju tvojí pomoc!
{23534}{23644}Mìsto Kakio leí na západì.|Musím jít.
{24864}{24905)Kdo je to zas!?
{24906}{24993}Kagero z Koga tımu, pane.
{24994}{25043}Co se dìje?
{25044}{25147}Dvacet ninjù, které vedl Hanza,|se pøed chvílí pokusilo vniknout
{25150}{25249}do vesnice Shimoda.|Všichni jsou mrtví.
{25274}{25373}Vánì? Všichni?|Kdo je zabil?
{25374}{25489}Nìkdo velice silnı.|Víc nedokáu øíct.
{25510}{25594}Tak zbyteèné, všichni.
{25714}{25793}A tys jediná pøeila?
{25825}{25923}Dokud se nedozvíme,|o koho jde a co chce,
{25924}{26043}namá smysl riskovat|v té vesnici další mue.
{26044}{26153}Nejdøív se tam musíš vrátit|a zjistit o co jde.
{26154}{26251}Potom rozhodnu, co dìlat dál.|Teï jdi.
{27526}{27574}Oh, ahoj!
{27643}{27713}Teï u cestu znám, take...
{27714}{27834}Ne, jdeš špatnì.|Cesta do pekla vede
{27880}{27940}...TÍMHLE smìrem!
{28296}{28460}Au... To bolí.|U jsme si kvit?
{28494}{28584}Ještì ne. Poøád ti nìco dluím.
{28631}{28682}To není moc chytrı.
{28684}{28805}Kdy to takhle pùjde dál,|jeden z nás umøe.
{28832}{28895}Jeden z nás.|ANO!
{28914}{29015}Nemá smysl se navzájem pozabíjet.
{29144}{29224}Kdy to nechceš ukonèit ty...|Já to udìlám!
{29262}{29295}Táhni k èertu!
{29592}{29718}Jsi velice zruènı, ale uvìdom si,|e mì nemùeš ublíit.
{29772}{29814}Vypadá to tak.
{30229}{30348}Co se dìje, zrùdo?|Rozpadá se ti kùe?!
{30444}{30503}CHCÍPNI!
{31544}{31647}Úasné! Tvùj meè byl rychlı jako vítr
{31650}{31814}a znièil tvého nepøítele|jako dotek tornáda.
{31853}{31962}To pro tebe nebyl ádnı soupeø.|Proè se nepøidáš ke mnì?
{31964}{32123}Tvoje zruènost by mi hodnì pomohla|v zabíjení potvor jako je tahle.
{32124}{32263}Dìláš si srandu? Kdo by chtìl|znova bojovat s nìèím takovım?
{32294}{32382}Budeš muset.|Oni ti pokoj nedají.
{32383}{32504}Právì jsi zabil jednoho|z Osmi Ïáblù Kimonu.
{32553}{32684}Ale asi tušíš,|e jsi ho neporazil sám.
{32714}{32854}Ta ena z Koga tımu...|Pouívá zajímavou techniku.
{33343}{33463}Lorde Gemmo.|Všechno jde podle plánu.
{33640}{33764}Zásilka od Shoguna Temnoty|pøijde zítra v šest veèer.
{33815}{33963}Velmi doøe.|Pošli mu odpovìï,
{33964}{34124}e se vrátíme za tøi dny.|A ujisti ho, e se nemá èeho bát.
{34144}{34193}Hned to bude.
{34324}{34398}Tessai se ještì nevrátil?
{34400}{34560}Benisato ho šla hledat.|Jsme úplnì sami.
{34584}{34704}Yurimaru...|Vdycky jsem tì milovala.
{34982}{35061}Nepotøebuju tvoji lásku, Zakuro.
{35063}{35164}Vùbec mì nezajímáš.|Teï bì a dr strá.
{35504}{35564}Take je to pravda.
{35579}{35670}Sníš o pøívìtivé náruèi Lorda Gemmy.
{35671}{35813}Jene, Yurimaru, Gemma uznává|lásku k muùm i enám.
{35814}{35904}Víš, e miluje Benisato?
{35932}{35984}Take asi nevíš.
{37455}{37554}Kam se chystáš, cizinèe?
{37594}{37681}Nikam konkrétnì.|A ty?
{37693}{37884}Nìkoho hledám a ty vypadáš|pøesnì jako on, take...
{37900}{38026}Všichni cizinci vypadaj stejnì.|Jsem Kibagami Jubei, tulák...
{38394}{38463}Urèitì to byl tvùj oblièej.
{38463}{38583}Tessai ještì staèil|zachytit tvojí podobu.
{39072}{39134}Dej mi sakra pokoj!
{39394}{39457}Svlékací kùe.
{39459}{39564}Shodila jí jako had a utekla.
{39623}{39710}Je to ale pìkná banda zrùd.
{39774}{39890}Nemusíš mi dìkovat.|Jen jsem nechtìl, abys u umøel.
{39931}{40010}Co jsou zaè, tìchhle Osm Ïáblù Kimonu?
{40029}{40097}Skupina ninjù, co pracujou|pro Shoguna Temnoty.
{40099}{40173}Znáš Shoguna Temnoty?
{40174}{40263}Chce obnovit Dùm Toyotomi,|bıvalé vládce Japonska.
{40264}{40373}Má podporu 16ti Pánù|a neustále rozšiøuje svùj vliv.
{40374}{40480}Je to nejnebezpeènìjší nepøítel|vlády Tokugawa Shogunaty.
{40481}{40603}Jeho moc je podpoøena|temnım stínem Osmi Ïáblù.
{40605}{40693}Proè jsou tady v Mochizuki?
{40720}{40834}To jsem pøišel zjistit.|Je to tìká práce.
{40854}{40955}Nechtìl bys dìlat pro mì,|za 100 zlaákù?
{40989}{41082}Tokugawùv vládní špión|si chce najmout ninju?
{41130}{41202}Bojím se, e nemám jinou monost.|Jsem v nouzi.
{41202}{41303}Jenom mì se povedlo dostat|a sem, do Mochizuki.
{41305}{41387}Všichni ostatní pøišli cestou o ivot.|Osm Ïáblù je zabilo. 
{41389}{41472}Potøebuju tvojí pomoc,|za kadou cenu!
{41494}{41583}Nikdy se jich nezbavíš.
{41584}{41652}Budeš s nima muset bojovat.|Døív nebo pozdìjc.
{41654}{41754}Pøidej se ke mì.|Zabiješ dvì mouchy jednou ranou, co?
{41773}{41892}Neøek bych.|Proè mi teï prostì nedáš pokoj?
{41965}{42062}Hmm. Moc špatnı.
{42063}{42122}Taková škoda.
{42193}{42334}Pøijdeš o svùj vzácnı ivot.
{42344}{42388}No jo.
{42390}{42503}Na tom, o èem mluvím|závisí tvùj ivot.
{42505}{42638}Víš, hrot té vrhací hvìzdice,|byl otrávenı.
{42639}{42728}Nezabije tì to hned,|ale za jeden den a noc.
{42729}{42819}Kdy jed zaène pùsobit,|tak u smrt nic nezastaví.
{42843}{42973}Teda, jestli nedostaneš protilátku.|A jenom já vím, co to je.
{42975}{43063}Dìlej pro mì a dostaneš|protilátku, zároveò s tìma
{43064}{43145}sto zlaákama.|Hned jak dodìláme tuhle práci.
{43170}{43234}Blufuješ.
{43393}{43441}Øíkám pravdu.
{43442}{43552}Hned mi koukej øíct,|co je ta protilátka?
{43554}{43694}Ne, dokud se nedohodneme.|Zab mì a zabiješ sám sebe!
{43855}{43931}Teï i ty potøebuješ protijed.
{43934}{44022}Ubohı chlapèe...|Musíš se ještì tolik uèit.
{44024}{44104}Tohle není ta, která tì zasáhla.
{44124}{44209}TÉ u jsem se dávno zbavil.
{44304}{44354}Kurva!
{44365}{44495}Kibagami Jubei,|prohrál jsi... amatére!
{44532}{44643}Jmenuji se Dakuan.|Budeme pøátelé.
{44784}{44814}Take, Benisato...
{44814}{44942}Tenhle mu, Kibagami Jubei,|je bıvalı shogunùv zvìd?
{44956}{44998}Nejspíš.
{44999}{45068}Proè jsi ho nezabila?
{45069}{45113}Nìkdo nás vyrušil.
{45114}{45173}ádné vımluvy!
{45244}{45378}Jestli je to vládní špeh,|tak se tady brzy objeví.
{45379}{45443}Tentokrát ho u koneènì zab!
{45448}{45528}To mi øíkat nemusíš.
{45529}{45708}Yurimaru... Promluvím si o tom|s Gemmou v posteli. Nìjaké námitky?
{45768}{45809}Spi sladce.
{45974}{46027}Jubei...
{46028}{46151}O nìèem jsem pøemıšlel.
{46168}{46256}Nejsi ty náhodou ten ninja,|kterı zabil
{46257}{46346}vrchní sluebníky klanu|Yamashiro pøed pìti lety?
{46379}{46482}Byl to prı mistrnı šermíø, jako ty.
{46577}{46666}Ti zabití sluebníci|byli nacpaní zlatem
{46667}{46766}tajnì vytìenım z ukrytého dolu.
{46768}{46856}Ten ninja je musel zabít|na rozkaz svého Pána,
{46857}{46947}kterı chtìl vládu|o tom dole informovat.
{46949}{47036}Protoe, kdyby se o dole|vláda dozvìdìla døív
{47037}{47097}pøišel by Pán o svojí pùdu.
{47118}{47222}Ale jestlipak tenhle ninja ví,|e po zabití sluebníkù
{47223}{47329}vláda ádnou zprávu|o dole neobdrela?
{47359}{47487}A co? Kdy vládní špeh,|jako jsi ty, u o všem ví
{47488}{47568}tak proè s tím nìco neudìlá?
{47588}{47727}Ani vláda nemùe nic podniknout|bez nezvratného dùkazu.
{47728}{47856}U mnohokrát se naši zvìdové|pokoušeli do klanu infiltrovat
{47857}{47936}aby dùkazy získali,|ale ádnı se ivı nevrátil.
{47938}{47993}Shogun Temnoty
{47994}{48079}je zastavil s pomocí Kimon ninjù.
{48097}{48200}Proè Shogun Temnoty pomáhá klanu Yamashiro?
{48216}{48328}To je jasnı. Chce ten|zlatı dùl sám pro sebe.
{48368}{48537}A víš, proè ten dùl našel døív ne vláda?
{48538}{48615}Protoe mu to nìkdo øekl.
{48616}{48725}Ten nìkdo, byl vùdcem ninjù klanu Yamashiro.
{48759}{48806}Himuro... Gemma?!
{48858}{48895}Pøesnì tak.
{48939}{49045}O tom pochybuju.|Ten u není mezi ivımi.
{49058}{49162}Ne, ještì poøád ije.|A sám ho brzy uvidíš.
{49163}{49267}Himuro Gemma toti šéjuje Kimonské bandì.
{49268}{49297}Coe?!
{49298}{49356}Shh! Ne tak nahlas!
{49357}{49412}U mì tak lehce znova nenachytáš!
{49413}{49526}Jen se uklidni.|Brzo se pravdu dozvíš sám.
{49546}{49697}Ale musíš uznat, e ty|a on sdílíte zvláštní osud.
{49876}{49962}Pøestaò!|To zabiješ vlastního pøítele?!
{49964}{50068}- Pán to naøídil!|- Tak jako náš vùdce!
{50110}{50199}Je to trik! Kdy teï víme|pravdu o tom zrádci,
{50200}{50306}tak se nás chtìjí zbavit.|Máme se navzájem povradit.
{50318}{50438}Je to past na nás všechny.|Shinkuro, vìø mi!
{50459}{50517}Jubei... Odpus mi.
{50528}{50562}Shinkuro!
{50593}{50647}Jeho slovo...
{50648}{50703}je zákon!
{51853}{52008}Osobnì jsem se pomstil za Shinkura i|ostatní. Gemma nemùe bıt naivu.
{52046}{52175}U jsme blízko. Tohle|místo je plné duchù a krve.
{52177}{52248}Dál u leí samo peklo.
{52378}{52498}Tuhle mlhu nám snad|na pomoc seslala nebesa.
{52953}{52993}Hej!
{53233}{53283}Zkurvená mlha!
{54004}{54117}Jak se vyhnul Shijimovu paøátu?
{54957}{55026}Co jsi zaè?
{55027}{55097}Slyšel jsem hlas, vzívající sutru.
{55098}{55200}Modlila jsem se za|ty mrtvé vesnièany.
{55228}{55338}Ty nevíš o epidemii,|co zamoøila vesnici?
{55388}{55528}Ubohá duše! U nikdy neopustíš|toto místo ivı.
{55543}{55648}A teï, nech nás jít do|buddhovy zemì pospolu.
{55831}{55948}Nevidìlas kolem procházet poutníka?
{55966}{56122}Brzo se setká s Buddhou.|Ukáu mu cestu.
{56143}{56197}Jak dobrotivá jeptiška...
{56447}{56510}Do prdele!|Další svlíkací kùe!
{56818}{56938}Zmizel...|Musel pouít velice zvláštní techniku.
{57258}{57325}Jako ty.|Opravdu, velice zvláštní!
{57604}{57806}Odpovìz. Je tu s tebou ještì nìkdo,|mimo toho staøíka?
{57839}{57937}To se vsaï.|A ne jen deset nebo dvacet.
{57938}{58030}Ani všichni tví hadi|na nì nebudou staèit.
{58078}{58137}Lháøi.
{58138}{58247}Tak dobøe!|Øeknu ti pravdu.
{58248}{58366}Jsou dva. Jeden je ten staøík.|A ten druhı...
{58367}{58427}stojí pøímo za tebou.
{58483}{58558}Odvolej ty hady.|Do jednoho!
{58750}{58808}Brzy budeš mrtvá.
{58927}{58977}Zbav se jich!
{59508}{59577}Teï nám na pár otázek odpovíš ty.
{59578}{59665}Co dìláte v tıhle vesnici? Mluv!
{60318}{60406}U dvakrát selhala.|Neodpustitelné.
{60408}{60527}Omotal jsem ti drát kolem krku,|ale ani sis toho nevšimla.
{60529}{60628}Skonèilas jako hloupı amatér.
{61176}{61257}Co blbneš?!|Poøád je èas ten jed vysát!
{61277}{61367}Jedy na mì nepùsobí.|Mé tìlo je na nì imunní.
{61448}{61525}Øekla bych, e svùj dluh jsem splatila.
{61526}{61612}Jo. Zachránilas mì.
{61614}{61737}Jmenuješ se Kagero, ejo?|Co teï budeš dìlat?
{61738}{61816}Do toho ti nic není.
{61837}{61898}Kdy mi do toho nic není,|tak co tady sakra dìlám?!
{61938}{62037}Musím odhalit jejich plány.
{62038}{62107}Sama? Nemonı!
{62109}{62187}Jsou moc silnı.|Promysli si to.
{62188}{62236}Neple se mi do cesty.
{62237}{62338}Nemám ádnej dùvod,|posluchat tvoje rozkazy.
{62443}{62508}Momentíèek,|ninja eno z Koga tımu.
{62509}{62666}Jmenuji se Dakuan.|Proè se k nám nepøidáš?
{62667}{62778}Tenhle mu je mùj|dùvìryhodnı spoleèník.
{62790}{62866}Nemìl jsem zrovna v plánu|pomáhat špehovi od vlády.
{62867}{62927}Ále, pøestaò reptat!
{62929}{62977}Co tomu øíkáš, eno?
{62978}{63111}Naše cíle jsou moná odlišné,|ale všichni máme stejného nepøítele.
{63112}{63202}A tøi, jsou lepší ne jeden.
{63203}{63292}Navíc mám jisté informace,|které zrovna sháníš.
{63293}{63396}Jako tøeba, kdo jim dává rozkazy.
{63397}{63457}Povím ti to cestou.
{63577}{63626}Nepotøebuju ádné pøátele.
{63628}{63746}Ale, mohla bych potøebovat|ty informace.
{63749}{63798}Vıbornì.
{63979}{64118}e je to ale rozkošná a sexy|mladá dívenka, co?
{64130}{64211}Co se ti honí tou tvojí|pokøivenou lebkou?
{64229}{64344}To, e se nám tahle ninja|holka mùe sakra hodit.
{64346}{64475}Otráví kadého mue,|co se s ní vyspí.
{64476}{64615}Toho obra, cos ho zabil,|taky otrávila ona.
{64787}{64878}Kadı, kdo se s ní miluje,|zemøe.
{64879}{65019}Dokonalá ena pro|tenhle prokletı svìt.
{66268}{66352}Tvá dovednost je úasná,|jako vdy.
{66354}{66448}Ne... Dokázal zabít i tak silného|ninju, jako byl Tessai.
{66449}{66595}Zùstaòte bdìlí.|Mohli se z toho dostat.
{66596}{66657}Vy ètyøi, provìøte to.
{66658}{66730}Jsi opatrnı, Yurimaru.
{66731}{66888}Máme dùleitı úkol.|Musíme poèítat se vším.
{66889}{66958}Já vím, já vím. Neboj.
{66959}{67008}Tak bìte.
{67090}{67228}Yurimaru, Benisato je mrtvá...|Jaké štìstí pro tebe!
{67507}{67576}Jedinı co zabil, jsou ryby.
{67578}{67647}To je dobøe.|Jinak bysme nedostali svojí šanci.
{67648}{67718}Zaèíná to bıt docela zajímavı, ne?
{68159}{68260}Tak co?|Je to tak, jak jsme mysleli?
{68282}{68377}Otrávili studny a|povradili vesnièany.
{68378}{68456}A pak to svedli na epidemii.
{68457}{68550}Trik, jak vylidnit okolí.
{68576}{68718}Plánují nìco...|velice mimoøádného.
{69046}{69126}Rád bych vìdìl, co to je.
{69137}{69228}V poøádku, jen se do toho moc nezaple.
{69230}{69288}Mohlo by se ti to stát osudnım.
{69927}{69987}To bude jenom pøedvoj.
{70527}{70569}Zdrhejte!
{71228}{71288}Nemùeme jim utéct.
{71357}{71387}Kagero...
{71928}{72007}Take ten pyl je smíchanı s |nìjakou uspávací látkou.
{72008}{72067}Ale jak dlouho je to zdrí?
{72098}{72138}Sakra, ty...!
{72167}{72197}Dìvèe!
{72197}{72267}Musíš je zdret, |ne ho Jubei zabije!
{72268}{72327}Dìlej co mùeš!
{72758}{72835}Odvolej svoje vosy!
{72837}{72918}Obávám se, e mì |nejdøív musíš porazit.
{72978}{73038}Nevíš nic, e jo?
{73039}{73128}Myslíš, e jsem sem bìel, |abych se ti ztratil?
{73148}{73177}Ne, nemyslím.
{73178}{73267}Mám pro tebe hodnì otázek, |ale na to teï není èas.
{73268}{73387}Ne, jenom jednu vìc.|Øekni, je Himuro Gemma naivu?
{73388}{73437}A co kdy je?
{73438}{73516}Protoe jsem ho dávno poslal do pekel.
{73518}{73602}Opravdu?|Tak to bych mìl bıt opatrnı.
{73603}{73735}Nemám dovednost znovuoivení, jako Gemma.
{73747}{73796}Znovuoivení?
{74047}{74118}Hlupáku! Poškodils úl!
{74623}{74708}V momentì kdy se vynoøíš, budeš mrtvı!
{74790}{74896}Je mùj!|Dejte od nìj ruce pryè!
{74897}{74947}Co ta ninja holka a ten mnich?
{74948}{75071}Moje vosy je brzy vyøídí.
{75347}{75461}Jak daleko se snaí utéct?|Jakı uboák!
{75907}{75993}Myslíš e ho dostal šipkou z hrdla?
{76307}{76446}Ne... Vosy z úlu se snaí utéct z vody.
{76447}{76577}Zoufale bodají do jeho tìla ve |snaze utéct... Mushizo je mrtev.
{76928}{77003}Dal si naèas, ale nakonec ho zabil.
{77436}{77608}Reinkarnace? Myslel tím, |e Himuro Gemma vstal z mrtvıch?
{77638}{77688}Nemoné!
{78073}{78193}Reinkarnace?|Slyšel jsem o téhle dovednosti.
{78224}{78382}Musíš umìt ovládat svoje maso |a krev a po ty nejmenší kosti.
{78384}{78472}Kdy máš useklou konèetinu, |nebo dokonce i hlavu...
{78473}{78567}...dokáeš je opìt spojit.
{78568}{78662}Reinkarnace...|To je technika nesmrtelnosti.
{78663}{78741}Tohle nemùe bıt nikdy dosaeno èlovìkem.
{78742}{78821}Dobøe, dobøe...|To je ale zatracenı trik!
{78822}{78952}V kadém pøípadì, Kimon monstra |jdou teï po vás obou.
{78953}{79033}To znamená, e se teï mùu |pohybovat mnohem snadnìji.
{79114}{79193}Kdy budete mít štìstí, |tak se znovu setkáme.
{79273}{79343}Proè ses k nìmu pøidal?
{79361}{79460}Najmul si mì...|Za 100 zlaákù.
{79461}{79542}Jsi nájemnı ninja?|Takovı, co udìlá cokoliv pro peníze?
{79575}{79630}Dá se to tak øíct.
{79631}{79753}Jene on mì do toho vtáhl. Dostal mì.
{79772}{79850}Za pùl dne zemøu na jeho jed.
{79892}{80007}Slíbil mi protijed zároveò s penìzma.
{80008}{80142}Proto pro nìj dìlám.|Teï u nemùu jít zpìt.
{80143}{80251}Mìla bys utéct pryè, hned |jak odvedu jejich pozornost.
{80252}{80344}To nemùu udìlat.|Mám vùèi tobì další dluh.
{80362}{80411}Zapomeò na nìjaké dluhy.
{80412}{80511}A øekla jsem ti, e od |tebe ádné pøíkazy neberu.
{80513}{80583}Mimo to, Jsem pøipravená |kadou chvíli zemøít.
{80585}{80643}Klid. Pøestaò pøedstírat, |e jsi tak drsná.
{80652}{80692}Coe?!
{80730}{80800}To je tímhle vlhkım poèasím!
{80802}{80923}Doufám, e pøijde bouøe, |a schladí tvoji horkou hlavu.
{81058}{81132}Nemusíš se o mì bát.
{81313}{81363}Bouøe...
{81408}{81553}Pøijeli tu noc, kdy |byla ta velká bouøe...
{81678}{81759}Hey, kde je dobrı |vıhled na tuhle oblast?
{81961}{82000}Máš tam nìco?
{82002}{82052}Nic.
{82053}{82102}Hledej dál!
{82473}{82511}Hanza...
{82512}{82542}Poèkej!
{82561}{82597}Hanzo!
{82733}{82823}Pøed tebou je útes! Stùj!
{82841}{82883}Sakra...!
{83293}{83323}Mám vás!
{83324}{83363}Kurva!
{83594}{83733}Hlupáku! Dostali tì tak brzo?|Poøád toho máme dost na práci.
{83882}{83971}Vùnì spáleného masa, dokonale usmaeného...
{83972}{84043}Nádherné aroma.
{84772}{84820}Nehıbej... se...
{84821}{84882}Staèí. Nech mì jít.
{84883}{84958}Je to moje vina.|Chytila jsem se do jejich léèky.
{84959}{85033}Zmlkni! Nemluv!
{85034}{85123}Slez ze mì!|Nepotøebuji tvoji pomoc.
{85124}{85168}MLÈ...!!!
{85422}{85492}Dìlej, chytni se!
{85863}{85953}Budeš se na mì houpat celı den?
{86463}{86593}Jsem Utsutsu Mujuro.|Chci se s tebou utkat.
{86802}{86870}Je tady kvùli mì.|Zùstaò tady.
{87258}{87393}Vlákal jsi mì sem, protoe jsem slepı?|To je tvùj plán?
{87822}{87900}Jestli mì chceš zabít, |tak nedìlej ádnı zvuk.
{87933}{88049}To je nemoné. Ale moná mùu obrátit |tvoji dovednost v mùj prospìch.
{89219}{89281}Øekl jsem ti, aby ses drela zpìt!
{89472}{89532}Tvùj zrak je tvoje slabina.
{89651}{89693}Z cesty!
{90044}{90080}Nemoné...
{90780}{90883}Mohla by ses uklidnit?!|Co sis ksakru myslela, e dìláš?!
{90913}{90982}Co ti tak vadí?
{90983}{91111}Zmlkni! Ty jsi posedlá tím, |e mì musíš na oplátku zachraòovat!
{91112}{91202}Chováš se, jako by jsi chtìla zemøít!
{91233}{91283}Je to kvùli tvému tìlu?
{91398}{91522}Je to pravda, e èlovìk, se kterım |se vyspíš, zemøe na otravu?
{91684}{91741}Zkus to, a zjistíš to sám.
{91918}{91962}Idiote!
{91964}{92041}Moje tìlo je celé nasycené jedem.
{92043}{92163}Je to tak silné, e pouhı |dotek mıch rtù tì okamitì zabije.
{92193}{92353}Nikdo se mì nemùe dotknout.|Kadı kdo se odváí...zemøe.
{92372}{92443}Jed naplnil taky tvoje srdce?
{92454}{92505}Jak se opovauješ!
{92692}{92776}Opovrhuju lidmi, kteøí si |neváí vlastního ivota.
{93345}{93452}Nemáš tušení...|To nemùeš pochopit!
{94674}{94770}Náklad z lodi, která uvázla na |mìlèinì v té bouøi pøed dvìma dny.
{94771}{94832}Proto jsou tady.
{94833}{94933}Pro to povradili |vesnièany jako zvíøata.
{95343}{95414}Kam vede tahle cesta?
{95595}{95621}Komoøí!
{95662}{95740}Lord Hyobu, je to pravda, |e Koga ninja tım...
{95741}{95862}...kterı jel vyšetøovat |do vesnice Shimoda byl znièen?
{95863}{95906}Správnì.
{95908}{96020}Ale jak...?!|Tohle je váné.
{96021}{96091}Okamitì vezmu svoje mue do té vesnice.
{96092}{96122}Ne!
{96125}{96261}Je to dost váné abychom ohrozili...
{96262}{96351}...bezpeèí našho klanu,|proto musíme bıt hodnì opatrní.
{96352}{96430}Takhle mùou malé klany jako náš pøeít.
{96431}{96461}Ale...
{96463}{96573}Ta ena, která pøeila, |pokraèuje ve vyšetøování.
{96574}{96633}Poèkejte na její zprávu.
{97052}{97122}Jsi unavená z toho vìèného napìtí.
{97123}{97172}Spi dál.
{98726}{98836}Ty stopy kol vedou do |pøístavu Kashima.
{98837}{98921}Chystají se odvézt ten |náklad pryè na lodi.
{98923}{98967}Kdy je nezastavím...
{98968}{99059}...tak ti mrtví vesnièani a Koga |ninja nebudou nikdy odpoèívat v pokoji.
{99134}{99232}Budu s tebou spolupracovat,|dokud ta mise nebude splnìna.
{99233}{99357}Ale jestli mì zase urazíš,|Zabiju tì kdykoliv!
{99812}{99932}Poslouchejte dobøe, vy kteøí |pracujete pro Shoguna Temnoty.
{99933}{100051}Tahle mise mùe |rozhodnout o našem osudu!
{100052}{100142}Tahle loï za pár hodin |dorazí do panství Mochizuki.
{100143}{100246}Musíme získat náklad za kadou cenu!
{100248}{100323}Rozumìli jste? Za kadou cenu!
{100913}{100993}Lidé utekli museli |utéct pøed epidemií.
{101011}{101108}Jeden kùò staèil, aby je |všechny vystrašil a vyhnal.
{101243}{101362}Take, jste stále naivu.|Bál jsem se o vás.
{101363}{101423}Taky tì ráda vidím.
{101432}{101537}Èekají na loï, která odveze náklad.
{101550}{101610}Díval ses, co je to za náklad?
{101611}{101752}Ne, Nemohl jsem se tam dostat.|Dokáu si domyslet co to je.
{101753}{101832}Vlastnì jsem to vìdìl, |ještì ne jsem sem pøijel.
{101833}{101862}Coe?!
{101863}{101932}Tys na to nepøišel?
{101933}{102008}Je to nìco, co se tıká tvojí minulosti.
{102032}{102204}Je to zlato, chlapèe. Zlato vytìené |z toho tajného dolu Yashimoro.
{102258}{102321}Ta loï se potopila bìhem bouøe...
{102324}{102452}Nejspíš na cestì k Shogunovi |Temnoty s cihlami zlata.
{102453}{102590}Zlato, které asi bylo |schované minulıch pìt let.
{102591}{102660}Jestli se mu dostane do rukou,|tak bude dostateènì silnı,...
{102660}{102740}...aby svrhl vládu Tokugawy...
{102741}{102807}...a uvrhl zemi do další obèanské války.
{102808}{102877}Musíme to zastavit za kadou cenu!
{103003}{103082}Dakuane, Nìkdo tì sledoval.
{103084}{103118}Coe?!
{103423}{103483}Dìvèe, Co to dìláš?!
{103484}{103604}Volám ptáka klanu Koga, |kterı je v této vesnici.
{103605}{103665}Voláš ptáka? Na co?
{103666}{103751}Odnese moji zprávu zámeckému komoøímu.
{103753}{103812}Zjistila jsem, proè jsou tady.
{103812}{103932}Za dvì jeho armáda obklíèí mìsto.
{103934}{103994}Není to tak jednoduché, jak si myslíš.
{103994}{104088}Klan Mochizuki nejspíš bude |celou tuhle vìc ignorovat.
{104103}{104128}Proè?!
{104262}{104312}V sázce je budoucnost klanu.
{104314}{104412}Tohle je mocnı zápas mezi |Tokugavou a Shogunem Temnoty.
{104413}{104528}Kdyby se do toho zapletl malı klan, |jako Mochizuki, byl by znièen!
{104624}{104733}Nevidìt, neslyšet.|To je nejlepší cesta pro klan.
{105088}{105168}Brzy to zjistíme, a u |Mochizuki pøijede, nebo ne.
{105463}{105532}Tak, na co si teï hraješ?
{105533}{105662}Ten mu, co sis ho najal,|zemøe na tvùj jed.
{105663}{105729}Øekni mi, jak ho zachránit.
{105731}{105883}Úasné! Zamilovala jsi se |do Jubeie, e jo?
{105928}{106033}Hlupáku! Dìlám to, jen abych |mu splatila svùj dluh!
{106054}{106114}To si nemyslím.
{106135}{106238}Zamilovaná ena ninja!|O co jde?
{106322}{106408}Kdy mì zabiješ, |tak ho nijak nezachráníš.
{106409}{106533}Ano, a tvoje mise bude neúspìšná.
{107002}{107043}Sakra!
{107061}{107103}Uh-oh!
{107120}{107240}Uklidni se!|To je ten správnı lék pro nìj.
{107241}{107323}Jestli mu chceš zachránit ivot, |není jiná monost.
{107324}{107393}Je to na tobì.
{108235}{108363}Muselo se to stát, |kdy jsem na chvíli odešel.
{108418}{108513}Nejspíš je mrtvá.
{108533}{108622}No, máme svoji práci.
{108624}{108701}Od klanu Mochizuki pomoc nepøijde.
{108811}{108888}Nechy se do jejich pasti.
{108898}{108942}Poèkej!
{108958}{109032}Co kdy pøijede jejich loï, |kdy budeš pryè?
{109033}{109136}Nech ji bıt! Mrtvá ninja |není tak dùleitá!
{109163}{109221}Není dùleitá v porovnání |s tvojí velkou misí?
{109223}{109281}Jsi stejné monstrum jako oni!
{109283}{109343}Blázne! Kdy bojuješ s monstry...
{109343}{109432}...stáváš se jedním z nich, |jinak nemùeš vyhrát.
{109462}{109611}Ty zabednìnı hlupáku!|Tak bì! BÌ DO PEKEL!
{109612}{109702}Proklatı cvoku...!!!
{111553}{111602}Jsi v poøádku?
{111651}{111693}Kagero!
{112248}{112367}Je tìké tì zabít, ale...|eno, uvolni jeho bolest.
{113054}{113132}Kibagami Jubei?
{113133}{113222}Ano. Ale u jsme je všechny zabili.
{113223}{113303}ldiote! Jsou stále naivu.
{113349}{113392}Zabiju ho, osobnì!
{113393}{113531}Zùstaò kde jsi.|Nalákej je tam a potom zabij.
{113534}{113571}Rozumìls?
{113572}{113613}Ano.
{113772}{113851}Nikdy jsem neoèekával, |e tì ještì uvidím.
{113852}{113927}Tìším se, e tì |znovu uvidím, Jubei.
{113980}{114023}Gemma!
{114179}{114223}Je mi líto.
{114242}{114360}Zapomeò na to. Ještì ádné |zprávy o záloze ze zámku?
{114413}{114483}U jsou to dvì hodiny.
{114502}{114543}Vím.
{114660}{114772}Proè... Vìdìl jsi, e je to léèka, |ale pøišel jsi mì zachránit.
{114773}{114871}Bylo to hloupé.|Proè riskovat tvùj ivot pro mùj?
{114871}{114933}Protoe jsi mùj pøítel.
{114939}{114973}Pøítel?
{114975}{115106}Ano. Od vèerejška jsme poøád|zachraòovali jeden druhého.
{115108}{115142}Jsi pro mì cennı pøítel.
{115422}{115462}Stùj!
{115462}{115540}Klan Mochizuki se tímhle nezabívá.
{115542}{115604}Tvoje mise je u konce.
{115605}{115709}Ne, není.|Poøád jsem ti dluná.
{115763}{115808}Mùeš to splatit pozdìji.
{115834}{115901}Ne pokud budeš mrtvı!
{115902}{115958}Splatím to tady!
{116261}{116312}Co to dìláš?
{116493}{116596}Ten staøec mi øekl, jak znièit ten jed.
{116638}{116701}""Znièit jed jedem.""
{116702}{116830}Øekl, e pokud se se mnou |budeš milovat, budeš uzdraven.
{116911}{116963}Vem si mì...
{118614}{118692}Proè?!|Zemøeš, pokud to neudìláš!
{118714}{118782}Proè...? JUBEl!
{119703}{119790}Èekali jsme!|Okamitì nalote loï!
{120593}{120663}Ty! Dobrá,varovalù jsem tì, nebo ne?
{120664}{120786}Jsme v hájí.|Nikdy neporazíme tolik muù.
{120804}{120937}Nezamıšlím nechat je odplout.|Brzy bude naše chvíle.
{120953}{120991}Co máš v plánu?
{120992}{121081}A dokonèí nakládání na loï...
{121082}{121142}...bì do vìe a zvoò.
{121144}{121247}Kdy budou vyrušeni, |tak se dostanu na loï.
{121248}{121337}A budeme na moøi,|nebudeme potøebovat ádnou bouøi.
{121338}{121392}Potopím ji sám.
{121393}{121442}Dobrá.
{121443}{121563}Mimochodem, Miloval ses s tou dívkou?
{121603}{121723}To tì nemusí ksakru zajímat!|Teï jdeme!
{122382}{122472}Gemmo... Kde jsi?
{122473}{122568}Kdy zemøu, vezmu tì s sebou do pekla!
{123533}{123605}Klan Mochizuki?!|Jedou proti nim!
{123771}{123842}Ah, Kagero!|Dobrá práce.
{123843}{123952}Rychle, ne odplují pryè!|Kde jsou ostatní?
{123954}{124039}Neboj se. Obklíèili tohle místo.
{124053}{124113}Tak rychle!
{124662}{124712}Jubei...
{124955}{125002}Kagero!
{125042}{125090}Pøestaò! Je to past!
{125112}{125229}Hlupáci! Sakaki Hyobu |zemøel pøed dvìma dny.
{125663}{125719}Osobnì jsem ho zabil.
{125733}{125818}GEMMO!!!
{126624}{126723}Pane, prosím bìte rychle na loï.
{126724}{126833}Sluhové Shoguna Temnoty èekají.
{126862}{126983}Nechte Jubeie mnì.|Postarám se o jeho smrt osobnì.
{127018}{127133}Prosím splòte mi tohle pøání.
{127243}{127298}Tak dobrá. Bì.
{128133}{128252}Dr se ode mì dál. U jsi nadìlala |dost ostudy.Jsem znechucen.
{128332}{128391}Tak, ty jsi Gemma?
{128393}{128501}Klan Mochizuki nemá |ádné podezøení, správnì?
{128502}{128561}Ano. Vše je v poøádku.
{128562}{128694}Udìlal jste skvìlou práci.|Obdivuji vás Ïáblové Kimonu.
{128695}{128782}Shogun Temnoty bude potìšen.
{129772}{129846}Svíjej se v bolestech, ne zemøeš.
{130913}{131002}Vypadá to, e se Yurimaru |neopatrnì chytil do mé pasti!
{131002}{131108}Byla to nehoda, |ale jeho vlastní chyba.
{131151}{131233}Teï jsem Královnou Ïáblù.
{131335}{131378}Odplouváme.
{131462}{131493}Kagero!
{131782}{131852}Dr se! Kagero!
{131963}{132013}Jubei...
{132014}{132092}Øíkal jsem ti, abys nechodila.
{132103}{132213}Chtìla jsem se...omluvit...
{132313}{132387}Bylo to poprvé...
{132388}{132502}Nechoval jsi se ke mnì jako k ninjovi...
{132503}{132603}...ale jako k normální enì.
{132628}{132743}Vìdìla jsem, e tì zaèínám pøitahovat, |a bála jsem se toho.
{132744}{132873}Tak jsem se tì snaila odradit.|Odpus mi...
{132952}{133052}Nezajímá mì, co si o mì myslíš!
{133093}{133232}Jestli jako protijed...nebo |z lítosti...nezajímá mì to...
{133253}{133353}Jen si pøeju...abys mì miloval.
{133563}{133691}Byla jsem hloupá...a slabá.
{133693}{133793}Proè jsem nemohla bıt upøímìjší?
{133802}{133913}Staèí.|U nic neøíkej...!
{135372}{135542}Jubei...|Jsem šastná...e jsem tì potkala...
{138363}{138533}Gemma, s pomocí zlata náš sen |se brzy stane skuteèností.
{138535}{138567}""NÁŠ"" sen?
{138568}{138658}Náš velkı sen svrhnout Shogunate...
{138659}{138749}...a obnovit vládu Domu Toyotomi.
{138752}{138810}Nerozumíš...
{138811}{138922}Jak jsme my, døívìjší |sluhové Toyotomi, trpìli.
{138927}{139034}Nyní to bude Tokugawa, kdo |bude trpìt v bolestech a muèení.
{139036}{139124}Pouijeme zlato, abychom koupili |nejlepší zbranì ze Španìlska...
{139126}{139213}...a porazili vládu Tokugawy.
{139214}{139346}Tohle je sen nás všech, |kteøí pracujeme pro Shoguna Temnoty.
{139366}{139416}Nesmysl.
{139456}{139501}Cos to øíkal?!
{139502}{139552}Øekl jsem "nesmysl".
{139554}{139645}MLÈ!|Jsi pouhı ninja!
{139646}{139703}Mùj sen je jinı.
{139705}{139793}To zlato nedostane Shogun Temnoty.
{139794}{139815}Coe?!
{139816}{139884}My, Ïáblové Kimonu, |si vezmeme to zlato.
{139886}{139934}Ty drzı...!
{139996}{140125}Pouiju ho, abych postavil |nejsilnìjší armádu ninjù všech dob.
{140127}{140270}A budeme ovládat zemi |terorem a silou z temnoty.
{140270}{140353}Kdokoliv se mi postaví,|Tokugawa nebo Toyotomi...
{140354}{140445}...edokonce Shogun |Temnoty osobnì, zemøe.
{140495}{140616}To znamená, e pravım |Shogunem Temnoty...budu já.
{141136}{141315}Vıbornì, jsi tady!|Právì jsem si pøál, abys pøišla.
{141315}{141365}To ráda slyším.
{141366}{141410}Jistì.
{141410}{141514}Bez tvojí pomoci by bylo nemoné|potopit tuhle loï!
{141546}{141606}Takhle!
{141766}{141826}Kazím ti plán!
{141846}{141891}Ani ne.
{142200}{142244}Co se dìje?
{142245}{142344}Oheò v podpalubí!|Potopíme se!
{142346}{142395}Idioti!|Uhaste ten oheò!
{142396}{142465}Nejde to!|Je to ohnivé moøe!
{142467}{142543}Uhaste to! Bojujte!
{142545}{142606}Rychle! Rychle!
{142625}{142686}Zapomeò na to! Utíkejte!
{142935}{142984}Mistøe Gemmo!
{142986}{143035}Pøedej všem tuhle zprávu:
{143036}{143194}""Opuste loï a schovejte se.|Jednou vás zavolám zpìt.""
{143195}{143224}Bì.
{144406}{144455}Gemmo!
{144511}{144616}Vidím, e sis pøivedl s sebou |pár ïáblù ze své cesty do pekla.
{144871}{144925}Kibagami Jubei...
{144927}{145031}Mìl jsem tì vyøídit sám.
{145042}{145126}Pøestaò fòukat.|Je pøíliš pozdì.
{145175}{145285}Chceš pomstít tu dívku Kagero?
{145286}{145383}Nebyla nic v porovnání |s tím, co ztrtaím s touhle lodí.
{145506}{145564}Pøiprav se na smrt!
{147162}{147274}Ještì tì nezabiju.|Ne dokud nebudeš trpìt.
{147275}{147345}Zaplatíš za nièení mého snu.
{147346}{147490}Tvùj sen? To, e budeš |opravdovı Shogun Temnoty?
{147514}{147581}Nechtìj mì rozesmát.
{147582}{147729}Jestli se staneš Shogunem, |udìláš z tohoto svìta, svìt ïáblù.
{147746}{147814}Jestli se ti v jejich |spoleènosti tak líbí...
{147816}{147895}...tak se vra do pekla!
{148405}{148476}Zabiju tì...!
{148556}{148615}Nikdo mì nemùe zabít.
{148748}{148836}Mìl bys pochopit, jako ostatní...
{148925}{149016}Jsem nesmrtelnı.
{149106}{149165}Vánì?
{149605}{149730}Jestli znovu oivneš...
{149731}{149846}...nepøestanu tì zabíjet, |dokud nechcípneš!
{151993}{152040}Nemùu umøít!
{153516}{153606}GEMMO! CHCÍPNI VE SVÉM ZLATÉM PEKLE!
{155355}{155396}Jubei!
{155397}{155536}Vypadá to, e ses zbavil toho |jedu, díky Kagero.
{155537}{155626}Kombinace ninja eny |obdaøené jedem...
{155627}{155744}...a schopného samotáøe fungovala |líp, ne jsem èekal.
{155746}{155796}Bì pryè.
{155921}{156065}Mimochodem, jemi líto ztráty |Kagero. Velká škoda!
{156066}{156154}Ale na pár chvil |se jí podaøilo...
{156154}{156260}...bıt normální dívkou a milovat tì.
{156276}{156345}Tohle bylo taky |souèástí tvého plánu?
{156346}{156424}Pøesnì tak. Èíst a |ovládat lidská srdce...
{156425}{156500}...je pravé tajemství ninji.
{156545}{156686}Stále platí, pouze opravdová upøímnost |mùe pohnout lidskım srdcem.
{156687}{156775}Zvrácenı starı bastard |jako já tohle nedokáe.
{156777}{156893}Jsi skuteènı hrdina.|Opravdu tì obdivuju.
{156894}{156974}Jak jsem slíbil, budu tì |èekat v Edo s tvımi 100 zlaáky.
{156976}{157036}Pøijeï si pro nì, jestli budeš naivu.
{157245}{157347}Jsme si kvit.|U nikdy se mi neple do ivota.
{157376}{157485}Porazil jsi mì. Myslel jsem, |e ti v Edo sklapne, ale...
{157486}{157613}Stejnì, V tomhle stavu se |nejspíš nedostaneš ani na bøeh.
{157615}{157696}Všechno skonèí tak, jak jsem èekal.