{320}{380}SBY (STAR BLAZERS)
{400}{620}DIGMEN_anime_FAN
{650}{900}uvádí 
{910}{960}japonskı animovanı seriál:
{980}{1108}Vesmírnı bitevník YAMATO!(1974)
{1200}{1350}Èást druhá: Vystøelit signální zbraní!
{1400}{1600}SuBtitleS_By_DiGmeN (digmen@seznam.cz)
{2700}{2862}Roku 2199, Zemì zaila své poslední momenty.
{2863}{2911}Tajemná vesmírná flotila...
{2912}{3044}...která zaèala osídloval známı vesmír, vztáhla své zlomocné ruce na Zemi.
{3063}{3187}Lidstvo budovalo podzemní mìsta,a tajnì schovávalo... 
{3188}{3244}...ale pomalu ztrácelo sílu vzdorovat.
{3245}{3361}A nyní Zemì padá pod tíhou meteorickıch bomb.
{3576}{3820}Náhle nabídli Iskandarané pomoc, aby záchránili lidstvo pøed kontaminací.
{4048}{4245}Iskandar je ovšem 148 tisíc svìtelnıch let od Svìtelné soustavy.
{4246}{4400}Øekli nám, e musíme jít vyzvednout Cosmo Cleanera-D.
{4428}{4650}Ale je na Zemi loï, která zvládne cestu 148 tisíci svìtelnımi roky?
{4701}{4774}Jistì! Je tu YAMATO!
{4775}{4915}Ale Yamato nebyl probuzen u 260 let ze svého spánku.
{4946}{5072}A radioaktivní jed zamoøoval Zemi stále více.
{5073}{5180}Lidstvu u zbıval pouze rok.
{5225}{5333}Nemùeme se spojit s New Yorkem! Vypadá to na vıpadek energie.
{5353}{5416}Neslyšíme Paøí...
{5417}{5495}Keòa je v panice...
{5496}{5598}Moskva øíká sbohem.
{5600}{5740}Signály s Pekingu a Ria se ozıvají, ale neudríme je...
{5805}{5900}Radioaktivní zamoøení Kantského území se odhaduje na pùl kilometru.
{6008}{6055}Jakı je stav Yamata?
{6059}{6150}Ještì 3 procenta, stále pokraèujeme.
{6152}{6248}Veliteli, odcházím. Nemùu u èekat ani minutu!
{6249}{6312}Zbytek prací mùeme dodìlat cestou.
{6314}{6375}Ale Okito, vaše zdraví není...
{6392}{6520}Cesta 148 tisíci svìtelnımi roky mì sice mùe stát ivot...
{6521}{6655}...ale vìøím, e cesta na Iskandar za to riziko stojí!
{6840}{6908}Slyšela jsem, e váš prùzkumnı plán selhal.
{6910}{7033}Ale myslím, e budeš v poøádku. Nemùeme si dovolit ztratit mladé mue v této dobì.
{7320}{7370}Néé, ty blbı perverzáku!!!
{7493}{7585}Z velitelství kadetùm Kodai Susumuovi a Shimovi Daisukemu...
{7586}{7660}Okamitì pøijïte k èekajícímu vzducholetu.
{7661}{7687}Co se dìje??
{7688}{7755}Pøímé volání z velitelství!
{7879}{7915}Hej, tady to je!
{8080}{8155}Ty nejdeš! Jsi pøíliš velkı!
{8191}{8243}Nepotøebuju moc místa..
{8379}{8457}Ne, s tím stejnì nic neudìláš!
{8458}{8536}Budeš potrestanı, za to es ignoroval tvou práci v nemocnici!
{8538}{8649}V nemocnici stejnì nemùu ukázat své schopnosti.
{8650}{8720}Nebudu se starat, kdy se ti nìco stane.
{9088}{9117}Kodai.
{9118}{9142}Co je to?
{9234}{9275}Coe, doktor Sado?
{9307}{9370}Héj kluci.
{9399}{9472}Oni vás taky zavolali?
{9474}{9527}Jasné!
{9528}{9592}Doktore Sado, vy víte co se tady dìje?
{9593}{9649}Nevim.
{10370}{10422}Kde to jsme?
{10424}{10467}Je to velkı prùmyslovı komplex.
{10468}{10527}Jdeme sem pracovat?
{10608}{10655}Co to je?
{10915}{11004}Co je to? Je to obrovské.
{11005}{11075}Vypadá to jako trup vesmírné lodi.
{11344}{11475}Kodai, Shimo, Doktore Sado, pouijte vıtah è.10.
{11818}{11838}Uuuuaaaaghhh!!
{11872}{11925}Je to trochu nakøivo.
{11928}{11980}Jo, to jo...
{12126}{12173}Á. tak jste koneènì tady!
{12537}{12590}Hej, tohle je...
{12591}{12681}Boí. To je mùstek kosmické lodi!
{12682}{12844}Kodai, Shimo, vítejte.Loï je pøipravena, tak buïte opatrní. 
{12913}{12950}Co...?
{13183}{13232}Co jsi zaè??
{13233}{13309}Jsem jejich nejlepší pøítel.
{13310}{13384}Chci poádat o vstup na tuto loï.
{13385}{13424}Udìluje se!
{13426}{13480}Dìkuju moc.
{13521}{13764}Úèel této speciální mise je pøipravit vás na vaše místa v této lodi. 
{13766}{13905}Teï jste pod mım velením! Pracujte tvrdì!
{13906}{14003}Ale kapitáne, je tahle loï pøipravena?
{14004}{14105}Samozøejmì,záeh motoru však ještì nebyl dokonèen.
{14106}{14213}Jeden u je hotov, mùeme vzlétnout s nouzovımi motory. 
{14215}{14405}Hlavní pohon máte popsanı ve zprávì kterou jste dostali na Marsu!
{14407}{14567}Je ovšem úplnì odlišnı od tohoto na Zemi.
{14581}{14709}Má oznaèení "Vlnovì-pohybovı" pohon a je urèen pro cestu na Iskandar.
{14710}{14770}Vlnovì-pohybovı motor??
{14771}{14891}Myslíte si, e mùeme bojovat úèinnì proti lodím Gamilus?
{14892}{14923}Jistìe.
{14924}{15102}Ale Kodai, opravdovı boj je odlišní od tréninku. Neber to na lehkou váhu.
{15120}{15320}Kadopádnì má naše mise vyšší cíle ne bojovat s Gamilusy.
{15347}{15380}Pøesto...
{15483}{15520}Co se to dìje?
{15538}{15599}Varovná zpráva z velitelství.
{15600}{15673}Mnoho bojovníkù se pøibliuje k naší lodi.
{15675}{15770}Vısadková loï Gamilusù je na obìné dráze Zemì.
{15823}{15910}Ti parchanti se snaí znovu zaútoèit na tuthle loï!
{15946}{16045}Je to pøímo nad námi. Vypouští rychle bojovníky.
{17795}{17862}Zapojeno 202 a 304.
{18434}{18510}Kapitáne, mùe tahle loï bojovì odpovìdìt?
{18720}{18789}Poèkáme ne pøíjde èas.
{18874}{18989}Pøevod energie to nouzovıch motorù je na 99%. Kontrola startovacího okruhu.
{18991}{19067}Okruj je v háji! Nouzové motory nejdou nahodit!
{19109}{19200}Bez motorù jsme jak sedící kachna.
{19632}{19742}S takovou jsme za chvíli v pytli, jestli nìco neudìláte!
{19744}{19766}Kapitáne!
{19767}{19809}Nepanikaøte!!!
{20508}{20600}Zpráva z velitelství Gamilusù vısadkové lodi.
{20610}{20677}Útok bojovníkù musí bıt dùslednı!
{20680}{20750}Kadı musí bıt eliminován!
{21016}{21115}Okruh øídícího mùstku je v provozu.
{21119}{21155}Dobrá. Zapínám!
{21361}{21463}Vısadková loï Gamilusù opouští obìnou dráhu a klesá.
{21601}{21702}Kapitáne, tahle loï bude znièena!
{21703}{21749}Mùeme se hnout?
{21757}{21863}Poslední kontrola motorù je kompletní. Tok energie je 100%.
{21864}{21946}Okruh v poøádku. Start je pøipraven.
{22081}{22143}Všichni na svá místa!
{22156}{22219}Aktivujte nouzové motory za 5 sekund...
{22220}{22270}Pøipravit na útok zbranìmi a torpédy!
{22539}{22647}Pøipojit k hlavnímu zdroji! Zapnout hlavní zdroj!
{22650}{22693}Správné naklonìní!
{22694}{22759}Pohnout trupem!
{22763}{22882}Motory na plnı chod! Vpøed!
{22942}{22981}Hıbe se...
{23202}{23263}Kodai, povedeš útok!
{23264}{23306}Shimo, vem si na starost pilotování!
{23307}{23367}Tahle loï má jedinì inenıry.
{23368}{23372}Ano pane!
{23375}{23410}Ano pane!
{23638}{23685}Je tohle....
{26360}{26465}Vıstup 120%. Pøipojuji pohon.
{26495}{26560}Zamìøování šokového dìla aktivováno.
{26565}{26607}Synchronizér zapojen.
{26608}{26659}Raketomety pøipraveny.
{26660}{26745}Jenom vlnová zbraò potøebuje víc energie.
{26747}{26849}Cílem je vısadková loï. Støílejte s hlavních zbraní v plnì automatickém módu!
{26860}{26985}Dosah 120 000. Úhel 45 stupòù. Rychlost 1000km/sec.
{26986}{27125}Všechny zbranì synchronní.Automaticky míøit mezi 9 hodinu, 9:05 a 20:45.
{27126}{27188}Kapitáne, pøebíráte kontrolu.
{27254}{27415}Tøetí vì je pomalejší o 0,2 sek.Pohyb! Klid a dìlej to jako v tréninku!
{27416}{27540}To se mu øekne. To je poprvé co dìlám s nìèím takovım.
{28003}{28058}Všichni se pøipravte na otøes!
{28106}{28139}Paaaaaaaal!!!
{28534}{28570}Gamiluské øídící centrum.
{28571}{28654}Základna na Zemi poblí Bogasaki nebylo jen tak obyèejné podzemní mìsto...
{28655}{28759}...ale bylo to pøístavištì bitevníku.
{28800}{28838}Tak to zniète!
{28839}{28899}Mùj pane, u je pøíliš pozdì.
{28902}{28972}Tato loï... Tato loï je u...
{29128}{29163}Zvládli jsme to!
{29504}{29557}Dokázals to.
{29571}{29628}Díky.
{29629}{29667}Pamatuj si to.
{29668}{29702}Ty taky.
{29805}{29837}Kodai, Shimo
{29839}{29885}Pane.
{29888}{29958}Tak jakı je Yamato?
{30017}{30088}Vesmírnı bitevník YAMATO.
{30089}{30196}Coe... Tenhle kus šrotu??
{30256}{30366}Toto je Yamato, na kterého jsme tak dlouho èekali!
{31172}{31286}Poslali jsme podpùrnou jednotku, na Zemi byla objevena velká loï... 
{31288}{31333}...a naše mobilní jednotka byla znièena!
{31334}{31497}Vrak kterı jsme objevili byl vzkøíšen do podoby velké bitevní lodi.
{31498}{31628}Pozemšané ho pojmenovali "Vesmírnı bitevník Yamato".
{31644}{31665}LORD DESLER
{31670}{31726}Yamato, øíkáš?
{31795}{31871}Ti pozemšané...
{31873}{31995}Vyšlete hvìzdnou flotilu a pøipravte se na operaci Yamato!
{32188}{32387}Trágédie jménem Yamato zaèala tehdy, kdy byl postaven jako bitevník.
{32396}{32542}Je to tragédie lodi, která byla zrozena pro boj.
{32833}{32906}Tati, slyším zvuk motoru.
{33051}{33230}V roce 1945, konèila 2. svìtová válka.
{33247}{33288}To je Yamato.
{33290}{33327}Yamato?
{33328}{33466}Dívej se pozornì. To je bitevník Yamato.
{33467}{33528}To je loï japonskıch muù.
{33531}{33600}Dívej se pozornì. A na to nezapomeneš.
{33634}{33700}V roce 1945...
{33701}{33820}...jako poslední flotila japonského námoønictva, opustil Yamato pøístav...
{33825}{34030}...vedl eskortu deseti lodí do protiútoku proti Americké flotile, èítající víc jak 300 lodí.
{34031}{34120}Bez letadel a nábojù, pouze s palivem jen na jednu cestu...
{34121}{34315}...byla to sebevraedná mise.
{34340}{34482}6. dubna v 7:04 ráno...
{34483}{34600}...zaútoèilo na bitevník Yamato zhruba 1000 letadel...
{34601}{34685}...vypuštìnıch z americkıch letadlovıch lodí.
{34760}{34840}Zachytili jsme nepøátelskou letku.
{34841}{34943}30 stupòu vpravo, dosah 200, vıška 6000.
{34945}{34987}Všechny vìe zacílit na letku!
{34988}{35070}Mraky jsou nízko. Pozor na náhlı útok!
{36477}{36515}Všichni opustit loï!
{36516}{36532}Kapitáne.
{36533}{36564}Zùstanu!
{36566}{36622}Pak zùstávám také!
{36623}{36712}Hlupáku. Mladí mui se musí zachránit !
{36822}{36925}Ve 3 odpoledne, nejvìtší loï na svìtì...
{36927}{37036}...opouštìl velkı èernı oblak kouøe...
{37038}{37155}...90 mil daleko,260 stupòù jihovıchodnì od Kjušského Bougasaki.
{37907}{38087}To byla marná víra v loï, která byla vyrobena k válce.
{38093}{38265}Bitevník Yamato pomalu usínal spolu s tøemi tisíci námoøníky.
{38680}{38798}Tento vesmírnı bitevník Yamato, nebyl postaven k boji.
{38800}{38915}Pùvodnì, byl postaven k opuštìní Zemì s vybranımi lidmi a zvíøaty...
{38917}{39047}...pøedtím, ne je vyhladí radioaktivita.
{39048}{39196}Kodai, Shimo. Byli jste trénováni pro misi na opuštìní Zemì.
{39197}{39259}Yamatova mise se ale zmìnila...
{39260}{39359}...ale mìli byste bıt schopni pouít to, co jste se nauèili v tréningu.
{39361}{39411}Spoléhám na vás.
{39460}{39556}Vím. Udìlám to kvùli mému bratrovi, kterı se nevrátil.
{39557}{39598}Prosím poslouchejte mì.
{39665}{39863}148,000 svìtelnıch let je dlouhá cesta, kterou lidstvo ještì nikdy neabsolvovalo.
{39864}{39993}Pøesto, kdy bude "vlnovì-pohybovı" pohon fungovat, mùeme to dokázat. 
{39995}{40105}Ne! Dokáu to! A vrátím se domù!
{41200}{41258}Vesmírnı bitevníku Yamato...
{41260}{41395}...tvá cesta, na záchranu lidstva, brzy zaène.
{41400}{41500}Ale radioaktivní kontaminace je den ode dne silnìjší.
{41503}{41620}Je tu 364 dní, které ještì lidstvo má.
{41624}{41735}Jdi, Yamato, celé lidstvo ti vìøí.
{42070}{42305}ZBİVÁ 364 DNÍ
{42340}{42380}Konec druhého dílu.
{42440}{42545}Subtitles_by_DiGmEn_2006 (digmen@seznam.cz)


