{100}{190}Sk subtitles by hitman
{219}{275}Èo do èerta?
{320}{390}Múzeum!Padá!!
{425}{445}Detektív!
{500}{530}Je to?
{690}{725}Zlatá lebka bola zachytená dnes ráno.|Mouse
{733}{845}Sakra!Iba kvôli Zlatej Lebke,|vykradol celé múzeum.
{860}{940}"Nie je niè, èo nedokáem ukradnú!"
{949}{1050}To povedal Mouse,|èo si o tom myslíte?
{1058}{1131}Ehhh?Ak povedal, |e môe ukradnú všetko.
{1143}{1260}Preèo sa nepokúsi ukradnú |novopostavenú veu Odaiba!
{1267}{1396}Èo ty na to, Mouse?Nemôe to spravi, e?|Choï a skús
{1406}{1444}Vieš, Chuu-chan ...
{1463}{1530}Môe Mouse ukradnú veu Odaiba?
{1538}{1588}Pre úasného Mousa,|to môe by aké.
{1595}{1690}Prajem si,aby to ukradol.|Môe to by ve¾mi zábavné!
{1697}{1751}Chuu-chan, èo si myslíš?
{1770}{1872}Pre úasného Mousa,|to bude pekne aké.
{1883}{2005}Ale, ide o prekonanie nemoného.|¼udia sa môu vyvíja.
{2020}{2058}Myslím, e môe to spravi.
{2285}{2315}Dovidenia, Sensei!
{2318}{2339}Uvidíme sa zajtra.
{2339}{2380}Ah, dovidenia.
{3235}{3313}U èakáme, Master Sama.
{3334}{3403}Vıskum vee Odaiba je ukonèenı.
{3418}{3473}Všetky údaje boli zozbierané.
{3550}{3590}Potom, mome zaèat?
{3610}{3755}Subtitles created by hitman.|2005
{5742}{5771}Kráde 02:|Nie je niè, èo by Mouse nemohol ukradnú
{5780}{5860}To je vıška Odaiby, Master Sama.
{5897}{5945}Myslím, e moem s tım daèo robi.
{5963}{6000}Vyzerá, e všetky ste robili usilovne.
{6032}{6078}Èo, èo robiš?Mei-san?!
{6089}{6120}Master Sama ...
{6132}{6184}Prosím odmeò nás za usilovnú prácu.
{6215}{6243}Odmeò nás.
{6245}{6293}Prosím ...
{6333}{6374}Nechoïte blišie.
{6465}{6495}V nede¾u zoberiem Odaibu.|Mouse. 
{6508}{6550}Sakra s Mousom.|artuje?
{6558}{6582}Detektív, televízor!
{6601}{6717}Ïakujem za vašu podporu.|V nede¾u ukradnem Odaibu.
{6725}{6755}Pripravte sa na úspech.
{6771}{6845}Arogantnı bastard!|Za èo ma povauje?!
{7325}{7399}Preèo neprišiel Master Sama do tejto krajiny?
{7405}{7510}Pouitie vojenskej helikoptéry |na ahanie Odaiby je nemoné.
{7522}{7585}Nie pre niè, èo je aké.
{7595}{7675}Celı plán má Master Sama v hlave.
{7687}{7757}My iba mu veríme a |nasledujeme jeho príkazy.
{7816}{7892}Je to hotové.Teraz|poïme do podvodnej základne.
{7900}{7915}Áno, pane!
{7972}{8082}Koneène je nede¾a.Deò, |v ktorı bude Mouse kradnú.
{8090}{8337}Polícia obk¾uèila okolie Odaiby a |taktie aj vzdušnı priestor kvôli Mousovi.
{8350}{8388}Ukáe sa?Mouse.
{8391}{8435}Zuki-chan, èo si myslíš?
{8460}{8521}Ukúe sa! Rozhodne!
{8654}{8690}Prosím, ostante stá!
{8733}{8805}Správa od tımu pri vei.
{8820}{8920}Poèas noènej hliadky neboli |nájdené iadne vıbušniny.
{8936}{9021}Sú nejaké správy o podozrivıch?
{9034}{9057}Nie, nie su.
{9067}{9219}Vyzerá, e Ouoyashima Co navrhla |zariadenia na udrania vee.
{9228}{9254}Bolo to skontrolované.
{9264}{9288}Plachtenie?
{9303}{9411}Povrch, na ktorom stojíme je danı na vode.
{9426}{9521}Bolo to pouité pri stavbe navádzacích svetiel na vode|Je to hight-tech.
{9530}{9571}Ah,  je to tak?
{9584}{9692}Pre ten istı dôvod, cítim zvláštnu bezpeènos.
{9693}{9724}Ty kus high-tech hovna!
{9830}{9912}Poïme!Je èas pre vyzdvihnutie Mastra.
{10260}{10275}To je Mouse!
{10291}{10373}Cie¾ sa pribliuje na motorke k vei!
{10383}{10400}Je tu!
{10501}{10546}Nie je niè, èo by Mouse |nemohol ukradnú!
{10618}{10630}Ty!
{10631}{10659}Uteká!
{11040}{11068}Èo?
{11350}{11408}Šialenı Mouse, predviedol |nebezpeèné kúsky.
{11450}{11490}Tım!Tım!
{11491}{11530}Všetky tımi boli vyradené!
{11532}{11581}Hey, Mouse sa chystá tou cestou.
{11593}{11623}Prejdite na nebezpeènı mod!
{11642}{11699}Èo sa deje?Odpovedz mi!
{11756}{11785}Je to strašne zlé.
{11798}{11850}Všetci spia.
{11875}{11924}Hádam,všetky problémy su vyriešené.
{12013}{12040}Poèkajte.Je ich viacej.
{12125}{12181}Vyzerajú odlišne od pravıch policajtov.
{12251}{12272}To nemôe by.
{12360}{12388}Detektív.To...
{12402}{12437}SAT je tu.
{12480}{12522}Špeciálny útoènı tım.
{12538}{12675}Tım SAT.Skupina špecializovaná |na nièenie teroristov.
{12690}{12768}Nemôem uveri, e boli vyslaní.
{12785}{12885}Správa od tımu, traja ušli z vee k moru.
{12904}{13030}Rozumiem.Mouse sa rozhodol zachráni svojich |parákov.
{13040}{13067}Smerujeme tam.
{13076}{13089}Rozumiem.
{13356}{13390}Neni kde utiec.
{13398}{13438}Èo spravíme, Mei?
{13625}{13655}Master Sama!
{13925}{13995}To je tu dobré!Neni cesty spá!
{13996}{14047}Ah, to je strašné.
{14055}{14095}Choï!To je tvoja odboèka!
{14096}{14133}Váne, Zuki-chan!
{14134}{14177}Dovo¾ mi tie pozrie!
{14241}{14276}Master Sama!
{14317}{14330}Ste všetky v poriadku?
{14336}{14358}Áno, pane.
{14441}{14480}Master Sama!Za tebou!!
{14495}{14514}To je ok!
{14530}{14551}Je èas.
{14640}{14658}Èo?
{14777}{14845}Èo do èerta?Riadenie je ...
{14948}{14975}Èo?!
{15128}{15155}To nemôe by!
{15170}{15209}Vea sa potápa.
{15281}{15336}Odaiba!Zloèin splnenı!
{15612}{15657}Nie!
{15759}{15792}Naozaj ju ukradol.
{15867}{15936}Ako zvyèajne, Chuu-chan mal pravdu.
{16213}{16266}Plán vyšiel, Master Sama.
{16278}{16326}Ah, to všetko vïaka vám.
{16465}{16528}Ale, bude to take |si poièa ponorku.
{16545}{16591}Všetko bolo mobilizované ku Západnej základni.
{16608}{16696}Všetko v jednom,všetko bolo |súhlasné s plánom.
{16713}{16844}Pri plnení spodku vee vodou |bola podpora Odaiby zbytoèná. 
{16859}{16977}A vea sa dala do pohybu kvôli magnetickej sile.
{16994}{17041}To bol perfektnı plán.
{17067}{17110}Ale, èo sa chystáš s tım spravi?
{17129}{17150}Oh yeah, to práve.
{17170}{17246}Nu, dôstojnos Mousa je poškodená.
{17268}{17310}Mohli by sme to napravi zajtra.
{17314}{17428}Potom, môeme prinajmenšom |si spravi z vee utoèište?
{17595}{17628}Potom, Master Sama ...
{17655}{17774}Do vıchodu slnka dova¾ nám |dosta to èo chceme.
{17794}{17851}Poèkajte chví¾u!
{17859}{17888}Nemôeme!
{17889}{17958}Preèo sa to musí skonèi takto?