{1000}{1250}Sk subtitles by hitman
{1507}{1562}U je èas,Detektív Onizuka.
{1702}{1744}Èo je to? Zemetrasenie?
{1962}{1969}Èo je to do èerta?
{2179}{2197}Detektív
{2220}{2253}Èo?
{2638}{2684}Znièím a!
{2691}{2740}Sakra!To všetko iba pre Zlatú lebku.
{2749}{2790}Zlatá lebka bola odcudzená dnes o 3:00.
{2796}{2863}Vykradol celé múzeum.
{2930}{2974}On robí tieto veci.
{2983}{3033}Dostanem a, ty šialenı zlodej!
{3131}{3299}Subtitles created by hitman.|2005
{5306}{5402}Kráde 01: Meno je Mouse.
{5450}{5490}Dobré ráno, moji drahí študenti.
{5499}{5585}Som riadite¾ Yamanoueho strediska.
{5606}{5730}Nastávajúce televízne vysielanie objasní |históriu našej školy.|
{5744}{5872}Ako všetci viete, toto stredisko pozostáva|zo všetkého od základnej školy po univerzitu.
{5878}{6000}Priblinı poèet študentov je 30 000.|Jeho história je dlhá a od roku '82
{6005}{6114}vytvárame poèetné spoloèenské skupiny,|ktoré su uitoèné spoloènosti.
{6279}{6328}Sensei Muon Sorata?
{6347}{6378}Aaah, áno?
{6385}{6460}Odkedy si iba študent fakulty umenia,
{6464}{6535}na strednej škole,si asistentom uèite¾a.
{6541}{6612}Inak, si niekto kto má|titul "Sensei".
{6619}{6669}Ako to, e moes prís neskoro?
{6679}{6724}Prosím viacej zodpovednosti za tvoje správanie.
{6740}{6796}Ako ste povedali, Sensei Momojono.
{6803}{6844}Myslíš vane svoju odpoveï?
{6874}{6906}Sensei Kakio?
{6937}{7015}Postav sa!Budeš potrestanı.
{7027}{7084}Váne.Nebude ti to prekáat?
{7087}{7131}Ah ... ako ste povedali.
{7140}{7199}Oh, ahoj Muon-san.
{7232}{7268}Yayoi-san?
{7282}{7365}Doniesla som ti skvelı materiál z pracovne.
{7414}{7500}Vyvinutı pre teba|"Zobúdzajúca medicína."
{7517}{7537}Je tu jedna vec ...
{7560}{7616}Nebudeš nikdy ospalı.
{7678}{7767}Ah, Chuu-chan je zase karhanı.
{7776}{7829}Nu, to je stále.
{7969}{8035}Ale, je to vdy rovnaké.
{8048}{8094}Stavím sa, e zase prišiel neskoro.
{8104}{8186}Ale, dostal prednášku od troch najkrajších|báb  strediska.
{8219}{8273}Nebol Chuu-chan v poslednej dobe šastnı?
{8275}{8370}Ako by mohol?Chuu-chan nebol štastnı.
{8387}{8417}Co si myslíš?
{8430}{8447}Mysliš?
{8453}{8472}Ano!
{8588}{8614}Pojdeš tu.
{8704}{8840}Zlatá lebka, ktorá bola vèera ukradnutá Mousom|sa našla.
{8848}{8953}Mouse...Èo do èerta sa pokúša splni?
{8977}{9074}Rekordy jeho krádei siahajú 100 rokov dozadu.
{9103}{9208}Jeho cie¾ová oblas nie je naša krajina,|ale celı svet.
{9218}{9326}H¾adá si predmety ako umelecké diela,|antika ...
{9335}{9398}Nie sme tu od toho,aby si nám vykladal základy!
{9407}{9469}Špeciálna jednotka je poverená vyjadnávat s Mousom.
{9475}{9641}Pıtam sa a,ako velite¾a, na informacie o Mousovi.
{9690}{9744}Pıtaš sa ma na identitu Mousa?
{9794}{9838}To chcem vedie tie.
{10032}{10083}Predpokladám, e všetci na mòa èakajú.
{10580}{10649}Vitaj spä, Master Sama!
{10690}{10819}Ospravedlòujeme sa za našu drzos|dnes ráno.
{10821}{10891}Ah, nie.Nemám oh¾adom toho starosti.
{10922}{10968}Master Sama ...
{10980}{11100}Master Sama,musíš by unavenı |z našeho tréningu, e?
{11104}{11124}Err, to nie ...
{11285}{11307}Ah ... nie teraz.
{11315}{11368}My, ktoré ti hovoríme pošetile,
{11381}{11440}My, ktoré jednáme k tebe pošetile..
{11452}{11508}My, ktoré prekroèujeme naše hranice ..
{11535}{11605}Zaslúime si tres, Master Sama.
{11773}{11822}Mote presta s tımito vecami?
{11822}{11876}Pravdae, nie!
{11896}{11926}Povedal som nie!!!
{11928}{11977}Ahhhhhh, Master Sama!
{12145}{12220}Dnešne slnko je jasnejšie ako zvyèajne.
{12249}{12285}Ty hlupák!
{12300}{12374}Vaša skupina dosiahla, |e zlodej je tak populárni!
{12387}{12426}Si iba jednoduchı vreckár!
{12449}{12522}Keby si bol mimo, tak by si nemal èo robit!
{12584}{12727}Avšak, Mouse volá svoje èiny krádee umenia|a sú to jeho vıhry.
{12728}{12765}Vıhry?
{12778}{12906}Prepáète mi, ale ale jeho zloèiny sú forma umenia.
{12928}{12983}Kradnutie nie je niè umelecké!
{12983}{13070}"Nie je niè, èo by som nemohol ukradnú."
{13077}{13181}Povedal Mouse.|Èo si o tom myslíte, detektív?
{13190}{13265}Ehh?Ak by povedal, |e moe ukradnú všetko ...
{13271}{13389}Preèo sa nepokúsil ukradnú |novo postavenú veu Odaiba?
{13395}{13531}Co ty na to?To nemôeš, e?|Choï a skús to!
{13609}{13679}Ha... to bude aké.
{13690}{13750}Mal by som vybuchnú nad takımito maniakmi.
{13757}{13803}To neni dobré, mam sa fajn.
{13830}{13884}Nie je niè, èo by si mal ma strach.
{13895}{14020}Tento typ chlapa nie je pre teba protivník,|Master Sama.
{14048}{14142}Ale, nemôem mu zabudnú uraku mena Mouse.
{14302}{14495}Mouse.Prvıkrát toto meno bolo |spomenuté pred 400 rokmi v ere Sankoku.
{14518}{14622}Vo vládnych záznamoch|policajnıch aktivít,
{14628}{14772}je povedané "Je tú zlodej,|ktorého ¾udia nazıvajú Mouse."
{14785}{14890}Najznámejších zlodejov ery Edo,|bola èas Mouse.
{14910}{14973}Tak, prešiel èas.
{14997}{15020}Súèastnos.
{15073}{15199}Neslávne meno Mouse bolo|venované nášmu Master Sama.
{15200}{15231}20-temu potomkovi rodiny Muon.
{15241}{15402}A my sme sa narodili slui Mastrovi Sama,|dokia¾ kradnutie neskonèí.
{15428}{15466}Poslušné sluobníèky.
{15516}{15569}Nie je niè èo by Mouse neukradol.
{15599}{15635}Mal by som to ukradnú?
{15666}{15694}Vea Odaiba.
{15740}{15763}Predtım ...
{15772}{15815}Mote mi da trochu priestoru?
{16073}{16103}Pozrite.
{16116}{16168}Skupina, ktorá postavila veu Odaiba.
{16176}{16250}Je to Ouayashima Co. zo skupiny Ooute?
{16572}{16628}Smiem hovori s CEO, prosím?
{16662}{16740}Povedzte mu, e som z rodiny Muon.
{17110}{17140}Vieš, Chuu-chan ...
{17162}{17230}Moe Mouse ukradnú veu Odaiba?
{17240}{17289}Pre úasného Mousa, to môe by aké.
{17297}{17391}Prajem si,aby ju ukradol.|Môe to by ve¾mi zábavné!
{17402}{17448}Chuu-chan, èo si myslíš?
{17471}{17570}Pre úasného Mousa,to|môe by ve¾mi aké.
{17586}{17705}Ale, ide o prekonanie nemoného.|¼udia sa môu vyvíja.Pod¾a mòa môe.
{17719}{17760}Myslím, e môe to spravi!