{1}{1}23.976
{8}{367}Název tohoto anime, Meine Liebe, je nìmecky|"má lásko". Rovnì spousta jmen a termínù, |se kterımi se bìhem nìj setkáte jsou |zaloená na nìmèinì (ie, nìmecké jméno "Ludwig").
{367}{609}V Kuchenu, jestli má jeden absolvent Akademie| Rozenstolz (Rùová pıcha) potenciál |stát se èlenem Strahl (Paprsek slunce). |Strahl, která se podobá Vládì v dnešním|moderním politickém dni, je skupina muù,|kteøí pomáhají Králi v rozhodování, øízení,|a podobnì. Jsou vybráni na základì souboru|extrémnì pøísnıch zákonù, zahrnující rodinné|postavení (jeden rodiè musí bıt šlechtic),|inteligenci a popularitu.
{609}{847}Všichni potenciální Kandidáti Strahl mají| pøezdívky stejnì jako formální dlouhá jména.||Národní jméno/Celé jméno/Pøezdívka||Orpheus/Orpheus Furst von Marmelade Nahe Gorz/Orphe|Eduard/Eduard Markgraf von sekt Braunschweig/Ed|Camus/Camus Pfalzgraf von Silvaner Luneburg/Camu|Ludwig/Ludwig Herzog von Mohn Nahe Liechetenstein/Lui|Naoji/Ishizuki Naoji/ -||Oznámení, e jedinı ne-Nìmec je Naoji, kterı je Japonec.
{868}{991}-Jestlie nastane destrukce,-
{1010}{1119}-nech všechno neuspoøádanì stát,-
{1166}{1258}-bez opìtovného pøestavování.-
{1402}{1488}-Máš minulost, na kterou nemùeš zapomenout?-
{1553}{1635}-Máš høích, kterı si pøeješ zapomenout?-
{1705}{1814}-Mùeš jít se svımi zranìními,.
{1839}{1991}- k symbolu, kterı byl nakonec zapomenut.-
{2007}{2134}-Pøed tebou na stezce, kde iješ,-
{2148}{2224}-jsou setkání jenom budoucí rozlouèení.-
{2236}{2299}-Násobí se a násobí se a budou se znovu násobit.-
{2312}{2439}-Pojïme pokraèovat tak, jak jsme to dìlali, s tìmi vyrytımi znaèkami,-
{2452}{2545}-take jednou mùeme bıt pyšní na-
{2604}{2700}-narození se v tomto svìtì.-
{2751}{2846}-Take mùu bıt pyšnı.-
{3169}{3244}V èasech, které politickı svìt naplòovali nestabilitou,
{3256}{3326}v Kuchenu, zemi na okraji Evropy,
{3326}{3382}neberou na vìdomí tlak obklopujících zemí
{3382}{3446}a kráèejí po vlastní nezávislé cestì.
{3466}{3534}Politika byla realizována inteligentním králem,
{3534}{3629}podporována nìkolika áky, kteøí touili obnovit království.
{3648}{3700}Mìli silné spoleèenské profily, logické myšlení,
{3700}{3801}a byli speciálnì uznávání Kutchenskou Církví.
{3812}{3937}Mnoho promovalo na prestiní Akademii Rosenstolz.
{3957}{4048}Nìkteøí mladíci, doufající v den, kdy se jim také tato odpovìdnost dostane,
{4048}{4122}se snaí bıt na špici akademie.
{4555}{4634}Jsou nazıváni Kandidáti Strahl.
{4651}{4706}PØÍLIŠNÉ SEBEVÌDOMÍ
{4891}{4963}Sestro, nebylo by lepší, kdybych doprovodil...
{4998}{5033}Jsem v poøádku, Orphe.
{5046}{5087}Jedu jen do mìsta.
{5103}{5214}Kromì toho, rozhodla jsem se dret svatební šaty v tajnosti a do obøadu.
{5247}{5296}Opravdu se vdáš.
{5296}{5329}Budu opravdu osamìlı.
{5362}{5392}Stále jako dítì.
{5409}{5459}Sestro, jsi šastná, správnì?
{5475}{5509}Ano, velmi.
{5608}{5658}Ale i kdy budu vdaná,
{5658}{5766}budeš stále mùj roztomilı malı bráška.
{5766}{5789}Ano.
{5828}{5859}Brzy se vrátím.
{5880}{5902}Cestuj opatrnì.
{6695}{6754}Orphee-sama! Robertine-sama, ona...
{7683}{7703}Sestro...
{7902}{7939}Sen?
{8543}{8600}Odcházím, Sestro.
{9047}{9089}To není jako ty, Orphe,
{9089}{9123}odejít od svého stráce.
{9139}{9195}Ede, jaká pošetilost tak brzy po ránu?
{9203}{9277}No, vypadáš tak vánì brzy po ránu...
{9305}{9320}Co se stalo?
{9369}{9385}Nic.
{9417}{9468}Mìl jsi znovu... ten sen?
{9567}{9614}U je to skoro dva roky?
{9637}{9682}Ještì stále nechápu,
{9699}{9759}proè musela má sestra zemøít.
{9782}{9846}Nakonec, nechytili pachatele, správnì?
{9863}{9926}Zdali to bylo varování z jiné zemì
{9926}{9992}nebo náhodná újma od nìjakého nespoøádaného rebela;
{9992}{10026}cokoli to je,
{10026}{10094}nevinná osoba byla cílena násilnım èinem.
{10139}{10184}Ano, kvùli tomu,
{10184}{10231}znièím zdroje tohoto šílenství.
{10246}{10312}Dovolit všem v této zemi ít beze strachu,
{10344}{10359}já...
{10383}{10416}Urèitì se jedním staneš.|/Pozn. pøekl.: Odkazuje na stání se èlenem Strahl./
{10416}{10456}Ty mùeš taky, Ede.|/Pozn. pøekl.: Odkazuje na stání se èlenem Strahl./
{10538}{10554}Orphe...
{10596}{10710}Ano, ale já nejsem tak moc posedlı stát se èlenem Strahl.
{10734}{10822}Stejnì si myslím, e nìkdo jako já se jím stát nemùe.
{10822}{10852}Jak mùeš...
{10879}{10957}Ale mohlo by to bıt pìknì zajímavé, kdy jsem s tebou.
{10979}{11022}Kromì toho, slíbil jsem ti...
{11053}{11114}Vdycky budu na tvé stranì.
{11640}{11653}Ede...
{11683}{11707}Tak to je.
{11978}{12004}Hej, Naoji!
{12059}{12078}Dobré ráno.
{12101}{12153}Vıbornì, opìt èasné cvièení.
{12153}{12234}Trvalé cvièení kadı den je dùleité nad všechno ostatní.
{12250}{12299}Dosud, jsem nezkušenı.
{12299}{12363}To je to, co nazıvám horlivostí.
{12377}{12456}Je to šermování tvé vlasti Japonska?
{12469}{12512}Ano. Je to Kendo.
{12525}{12554}Není to neobvyklé.
{12566}{12618}Mohl bys mì to pøíštì nauèit?
{12636}{12651}Nemohu.
{12662}{12739}Ještì nejsem dost zkušenı, abych uèil.
{12758}{12774}Chápu.
{12805}{12849}Hodina u skoro zaèíná.
{12867}{12880}Sbohem.
{12984}{13026}Zdá se, e mnou opovrhuje.
{13042}{13105}Není to tak, e tebou opovrhuje, jen...
{13119}{13135}Jen...?
{13151}{13171}Zapomeò na to.
{13171}{13227}Zanedlouho budou všichni postupovat.
{13250}{13268}Pojïme také.
{13419}{13504}Tvoje usuzování je špatné, Ludwigu!
{13579}{13654}Co ti dává právo to øíkat,
{13666}{13765}Orphee Furste von Marmelade?
{13794}{13820}Máme to tu zase.
{13836}{13872}Kdy budeme následovat tvùj plán,
{13872}{13921}jen to udìlá lidi více nešastnımi.
{13921}{13997}A tvùj plán je jen zmenšení ozbrojenıch sil.
{14010}{14109}Nevìøím, e by ti hrabiví, vypoèítaví obèané
{14125}{14199}rozumnìli tvému vyššímu myšlení.
{14214}{14228}To je...
{14239}{14293}Cesta k lepší budoucnosti mùe bıt jedinì otevøena,
{14293}{14364}jestlie ti, kteøí mají sílu øídí cestu.
{14364}{14428}Ale slabı má taky srdce!
{14439}{14492}Bez lidí nemùe bıt vybudována zemì.
{14521}{14605}Nemùeme udìlat tento svìt jednotnım, kdy obìtujeme nevinné obèany!
{14648}{14667}Co to všechno je?
{14667}{14699}Beruze-sensei.
{14778}{14811}Zase vy, mladíci?
{14826}{14883}Vidìt vás gentlemany tak horlivé ve vašich studiích je v poøádku a dobré,
{14883}{14958}ale prosím, debatujte si ve svém vlastním volném èase, dobrá?
{15053}{15146}Proè ho stále tak úmyslnì provokuješ?
{15146}{15200}Byl to on, kdo mì napadl první.
{15212}{15258}Není to tak, e jsem si to uíval.
{15258}{15282}Ale...
{15282}{15328}Stále jsi na jeho stranì?
{15341}{15392}Máš pro toho kluka slabost, e?
{15407}{15436}Slabost pro nìj?
{15459}{15562}Jeho pøímoèarost, upøenı pohled,
{15580}{15667}oslòuje nedùvìrníka jakım jsem.
{15678}{15735}Tvoje pokora ti sluší.
{15769}{15782}Lui...
{15801}{15856}Ale jestli budeš dret takto své pohrdání,
{15856}{15926}i tvé vlastní zvláštní dùvody se stanou trhlinami.
{15935}{15989}Jestli mì chceš následovat,
{15989}{16045}musíš dosáhnout vıš.
{16151}{16172}Ten Orphe,
{16185}{16257}odvauje se øíkat taková slova našemu Ludwigu-sama.
{16279}{16337}Mezi teoretiky se nikdo nemùe srovnávat s Ludwigem-sama.
{16361}{16425}Jen Ludwig-sama je dost dobrı, aby byl èlenem Strahl.
{16448}{16527}Ano, on je jedinı.
{16584}{16635}Akademie Rozenstolz?
{16659}{16709}Není divu, e ji nazıvají vıjimeènou.
{16709}{16738}Samozøejmì.
{16762}{16854}áci, kteøí souvisí s budoucností naší zemì jsou v té Akademii.
{16854}{16887}Vypadá to tak.
{16900}{16969}Ale je pro mì tìké psát o dùvìrnì neznámıch místech.
{16985}{17032}Oh? Pane, jste romanopisec?
{17052}{17068}Svım zpùsobem.
{17068}{17120}Pøišel jste si sem obstarat nìjaké nové psací potøeby?
{17152}{17205}Ne. Pøišel jsem sem pøi hledání neèeho.
{17413}{17542}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{17781}{17821}Tak to bylo, Beruze-kun,
{17821}{17863}jací byli studenti této akademie?
{17875}{17921}Velmi rozlišné osobnosti,
{17935}{17990}zvláštì Tøída Kandidátù Strahl.
{17990}{18082}Èasto dìlají vìci, které šokují nás uèitele.
{18098}{18135}Samozøejmì, samozøejmì.
{18147}{18260}Ale bıt schopnı pøijít a uèit na Akademii Rozenstolz,
{18260}{18307}cítím se hluboce poctìn,
{18332}{18461}protoe trénuji uèence, kteøí souvisí s budoucností naší zemì.
{18493}{18519}Pravdivì øeèeno.
{18519}{18614}Oèekávám, e tento rok budou nìkteøí Strahls vybráni.
{18614}{18695}Slyšel jsem, e minulı rok nebyl vybrán ádnı student.
{18695}{18732}Proè tomu tak bylo?
{18732}{18814}Byla zøejmì pøemíra excelentních studentù.
{18834}{18922}Spousta s neobyèejnımi známkami má potíe stát se Strahl,
{18922}{18983}a prohlásí se jen za budoucí primátory.
{18983}{19049}Co tím myslíte?
{19063}{19125}Ti, kteøí by mìli bıt Strahl, jimi budou.
{19125}{19237}Ne, ti, kteøí jsou pøedurèeni se jimi stanou.
{19286}{19337}Nerozumím.
{19374}{19427}Všímejte si trochu více, Beruze.
{19437}{19499}Tento rok je v této akademii seskupeno mnoho zkušenıch ákù.
{19601}{19638}Hej, uklidni se, Orphe.
{19638}{19665}U jsem klidnı.
{19665}{19699}Jo, jo.
{19699}{19726}No tak...
{19726}{19804}Musíš vdycky skonèit tak naštvanì, kdy se dohaduješ s Luiem?
{19870}{19888}Tudy.
{19901}{19911}Ede...
{19911}{19970}V dobách jako jsou tyto, bychom mìli smìøovat ke konejšivìjším místùm.
{20121}{20164}Jste dnes tak veselé.
{20164}{20216}Poèkejte chvíli a já vám dám nìjakou vodu.
{20340}{20379}Vìdìl jsem, e bys mìl bıt tady, Camu.
{20379}{20399}Promiò za obtìování.
{20409}{20451}Ede, Orphe-san,
{20451}{20482}vítejte.
{20505}{20570}Další hádka s Luiem, Orphe-san?
{20585}{20607}U to víš?
{20635}{20744}Tyhle dìti jsou vystrašené tvou zlostí, Orphe-san.
{20744}{20782}Jsou to jen kvìtiny.
{20782}{20866}Moná tomu nebudeš vìøit, ale je to pravda.
{21025}{21101}Omlouvám se. Nezamıšlel jsem tì znepokojit.
{21139}{21173}U se zotavily.
{21193}{21286}Ké by jen tvùj vztah s Luiem mohl bıt rovnì uzdraven.
{21299}{21325}Pøesnì tak.
{21325}{21436}Moná v budoucnu, budete muset vy dva pracovat spoleènì jako Strahl.
{21436}{21461}Nemoné.
{21461}{21535}Naše usuzování a osobnosti se pøíliš liší.
{21535}{21608}Jeho zpùsoby a nenáleité chuligánství, nepøimìøenì diktátorské.
{21641}{21677}Ah, omluv mì.
{21689}{21738}Je to tvùj pøíbuznı, správnì?
{21752}{21767}Ano.
{21779}{21842}Obdivuji tebe i Ludwiga, Orphee-san,
{21842}{21907}take kdybyste se vy dva mohli stát pøáteli,
{21907}{21928}byl bych potìšen.
{21984}{22004}Dovol mi pomoci.
{22004}{22054}Pokadé, kdy vidím ty kvìtiny tady,
{22054}{22111}uvnitø mého srdce, cítím hlubokı klid.
{22226}{22266}Dìkuji za tvoji pomoc.
{22266}{22297}To nestojí za øeè.
{22297}{22353}Byla to pìkná zmìna tempa, eh?
{22353}{22434}Je to jako by ty rostliny mohly mírnit lidské emoce.
{22446}{22488}Hodnì se jim líbíš.
{22488}{22575}Dobrá, vrame se domù. Je èas na veèeøi.
{22652}{22669}Copak je?
{22710}{22793}Právì teï... Cítil jsem chladnou pøítomnost.
{22793}{22821}Chladnou pøítomnost?
{22844}{22857}No...
{22872}{22969}Taky tomu úplnì nerozumím, ale to bylo nejznepokojivìjší.
{23014}{23062}Nemùu mu odpustit.
{23062}{23144}Odváil se odvrátit plány Ludwiga-sama.
{23144}{23205}Jestli se taková osoba stane èlenem Strahl...
{23205}{23233}Jsem si toho vìdom.
{23250}{23298}Rodinné postavení, inteligence a popularita.
{23298}{23388}Jedinì vıjimeènı s tìmito stributy se mùe stát Strahlem.
{23402}{23437}To je právì ono.
{23452}{23547}Ale stále, není málo tìch, kteøí následují Orphea.
{23547}{23584}Nemùu to vystát.
{23597}{23714}Spoustì lidem, kteøí nepatøí na tuto akademii se podaøilo vstoupit.
{23779}{23824}Neøíkejte to svìtu,
{23824}{23935}ale tato akademie pojala jednoho, kterı není úplnì urozenı.
{23989}{24016}To je pøesnì...
{24028}{24072}mìl by bıt vylouèen z této Akademie.
{24195}{24213}Hrozné zprávy!
{24213}{24265}Je nebezpeèné takhle bìhat, Camu.
{24265}{24317}Oznámení jako je tohle jsou pøilepené po celé akademii,
{24317}{24354}zpùsobují všude chaos!
{24435}{24487}Jak zvrácená zpráva.
{24487}{24521}Co to znamená?
{24521}{24550}Nedívej se na to.
{24550}{24573}Hej!
{24713}{24754}Aèkoli titulovanı jako Vikomt,
{24754}{24874}ve skuteènosti je to jen dítì bezejmenné eny z ulice.
{24874}{24948}Jak mohl nìkdo takovı vstoupit na naši akademii?
{24959}{25047}Nestydí se za to, e jsou jeho pøátelé?
{25070}{25092}Sprosté.
{25164}{25200}Radši odejdi døív, ne...
{25200}{25226}Dr jazyk za zuby!
{25260}{25353}Jestli budeš pokraèovat v uráené mého pøítele, nenechám to proklouznout.
{25417}{25492}Orphe, zapomeò na to. Nakonec, je to pravda.
{25492}{25519}I tak,
{25519}{25585}stále jsi vlastní syn Vikomta Braunschweiga.
{25585}{25672}Mùj drahı spoleèníku, není se za co stydìt.
{25715}{25727}Orphe...
{26037}{26057}Co chceš?
{26070}{26111}Není to tvoje práce?
{26111}{26150}Kdy jsem ti zkomplikoval plány,
{26150}{26183}proè mì odvánì nevyzveš?
{26203}{26253}Tvoje špinavé taktiky jsou neodpustitelné!
{26303}{26357}A kdyby to byla moje práce?
{26375}{26434}S vkladem povìsti mého pøítele a mì,
{26482}{26506}tì vyzıvám k duelu.
{26821}{26877}Zde nebudeme rušeni ostatními.
{26925}{26942}Dobrá.
{26988}{27029}Co dìlat? Co kdy bude nìkdo zranìn?
{27041}{27092}Kromì toho, šlechtici mají duel zakázán.
{27102}{27150}Jestli je nìkdo pøistihne, budou vyhnaní.
{27150}{27193}Nepochybnì, musíme je zastavit.
{27193}{27219}Nemoné.
{27219}{27261}Orphe je nezkrotnı, kdy jedná takhle.
{27279}{27328}Ale proè dìlá takovou vìc Lui?
{27348}{27376}Byl to opravdu on?
{27376}{27421}Ne, to je nemoné.
{27421}{27499}Lui by neudìlal nic tak odporného.
{27589}{27607}Proè?
{27623}{27696}Proè Ludwig-sama pøijal vızvu?
{27696}{27743}Víš nìco, co my ne?
{27799}{27820}Poèkej!
{27820}{27864}Puste! Puste mì!
{27864}{27894}Jsem nevinnı!
{27894}{27928}Tak proè jsi utíkal?
{27928}{27988}Nemusím to vysvìtlovat takovım jako jste vy.
{28000}{28069}Mohlo by to bıt... byla to tvoje práce?
{28086}{28100}Je to pravda?
{28137}{28163}Tak co?
{28163}{28231}Jen jsem všem øekl pravdu.
{28271}{28281}Ty...
{28682}{28703}Nejsi špatnı.
{28715}{28737}Stejnì tak ty.
{28883}{28907}Ludwigu-sama.
{28917}{28952}Hej! Pøestaò bojovat, Orphe!
{28952}{28990}Nemá to s Luiem nic spoleèného!
{29079}{29123}Je to k nièemu. Nemùe nás slyšet.
{29123}{29157}Jestli si nepospíšíme a nezastavíme to...
{29202}{29214}Nechávám ho tobì.
{29508}{29537}Dost!
{29780}{29804}Prosím, omluvte mì.
{29842}{29935}Jaká zábava. Vyøešme to v budoucnu.
{29963}{29997}Ludwigu-sama.
{30065}{30095}Jsi ostuda na pohled.
{30107}{30149}Zmiz mi z oèí.
{30470}{30532}Vytáhnout tak bláznivı kousek kvùli mì.
{30532}{30603}Jen jsem chtìl bránit tvou povìst.
{30603}{30661}No, není toho moc, co mùu udìlat, abych tì zastavil.
{30673}{30703}Ale jsem potìšen tím, co jsi udìlal.
{30703}{30769}Nicménì, nebyl to Lui, kdo za tím stál...
{30769}{30786}Vìdìl jsem to.
{30847}{30901}Na neposkvrnìném meèi nebyla ádná zloba.
{30915}{30958}Vìdìl jsem to jakmile jsme zaèali.
{31110}{31177}Proè jsi pøijal jeho vızvu?
{31177}{31236}Neudìlal jsi nic špatného.
{31255}{31343}Myslel jsem si, e to byla moje šance znièit toho chlapce.
{31361}{31485}Ale on není ten typ, co by se dal lehce znièit.
{31617}{31672}Ale, ale... jakı nepoøádek.
{31672}{31755}Skoro jsi znièil svou budoucí povìst.
{32446}{32516}-Tváø, kterou nikomu neukáeš.-
{32516}{32591}-Jen mì nech se podívat,-
{32591}{32696}-tak se uklidòuji zatímco tì hledám.-
{32754}{32816}-Unavenı vıraz,-
{32816}{32892}-pøisaju pohled na tebe.-
{32892}{32994}-Chci se tì dotknout tìma rukama. Utáhnu své sevøení.-
{33068}{33127}-Zaraenı, zmatenı,-
{33140}{33214}-mùj pohled je na tebe upøenı.-
{33253}{33314}-Tvou mìnící se tváøí-
{33314}{33394}-se mé srdce tøese.-
{33394}{33469}-Ale jednou pod tou tvojí maskou-
{33469}{33552}-chci ochránit tu zranìnou tváø.-
{33552}{33616}-Nevyhnutelná noc pøichází,-
{33629}{33697}-take tì ádám, pospìš.-
{33697}{33811}-Navìky chci bıt s tebou.-
{33811}{33907}-Pouze do té doby, ne si mì všimneš.-
{34294}{34323}Další epizoda
{34335}{34370}Od tvıch dìtskıch dní...
{34403}{34431}Léèky nenávisti...
{34465}{34493}Neochvìjné pøátelství...
{34530}{34585}Teï nejsi sám.
{34605}{34632}POMLUVA
