{1}{1}23.976
{28}{154}-Jestlie nastane destrukce,-
{172}{275}-nech všechno neuspoøádanì stát,-
{322}{417}-bez opìtovného pøestavování.-
{558}{644}-Máš minulost, na kterou nemùeš zapomenout?-
{704}{795}-Máš høích, kterı si pøeješ zapomenout?-
{861}{972}-Mùeš jít se svımi zranìními,-
{997}{1151}-k symbolu, kterı byl nakonec zapomenut.-
{1167}{1291}-Pøed tebou na stezce, kde iješ,-
{1308}{1382}-jsou setkání jenom budoucí rozlouèení.-
{1389}{1457}-Násobí se a násobí se a budou se znovu násobit.-
{1469}{1596}-Pojïme pokraèovat tak, jak jsme to dìlali, s tìmi vyrytımi znaèkami,-
{1612}{1702}-take jednou mùeme bıt pyšní na-
{1760}{1855}-narození se v tomto svìtì.-
{1908}{2003}-Take mùu bıt pyšnı.-
{3240}{3289}VESELÉ TVÁØE
{3689}{3749}Je to opravdu... tak?
{3974}{4009}Aèkoli tomu nechci vìøit...
{5172}{5184}Copak je?
{5195}{5205}No...
{5225}{5277}Nezúèastníte se, Ludwigu-sama?
{5298}{5349}Navštívil jsem vıroèí zádušní mši.
{5379}{5396}To staèí.
{5410}{5468}Není potøeba navštívit další nicotné slavnosti.
{5479}{5502}A-Ano.
{5569}{5640}Pøeji si oddávat se nìjakému tichému rozjímání.
{5663}{5691}Mùete odejít.
{5691}{5743}Ano. O-Omluvte nás!
{5743}{5764}Promiòte za rušení!
{5840}{5850}Tady.
{5869}{5920}Tato by mìla bıt odolná a snadná na starání se.
{5945}{5963}Roztomilá!
{6004}{6051}Brzy pro tebe nádhernì vykvete.
{6070}{6124}Jen si pamatuj ji napájet a dávat lásku.
{6134}{6140}Ano.
{6171}{6194}Dìkuji mnohokrát.
{6226}{6274}Mùu mít taky jednu?
{6274}{6311}Came-sama, já také!
{6320}{6328}Jistì.
{6382}{6426}Pak, rozkroè se jedním dechem, takhle.
{6490}{6513}Zvládla jsem to!
{6583}{6627}Naoji-sama! Naoji-sama!
{6645}{6677}Zatanèil byste si se mnou!
{6677}{6703}Ne, se mnou!
{6718}{6757}Ne, já...
{6757}{6802}Ale jestli ne teï,
{6802}{6881}nikdy si nezatanèíme se studenty této Akademie.
{6881}{6905}Prosím!
{6922}{6955}Tady jsi, Naoji.
{7008}{7038}Orphere-sama!
{7062}{7073}Orphe.
{7095}{7180}Rád bych byl ve tvé spoleènosti. Co ty na to?
{7192}{7225}D-Dobrá.
{7246}{7314}Omlouvám se. Dovolte mi vypùjèit si ho.
{7542}{7573}Mìl bych si hledìt svıch vlastních záleitostí?
{7621}{7653}Zdál jsi se bıt v potíích.
{7674}{7767}Ano. Bylo to lichotivé, e chtìly tanèit, ale...
{7823}{7875}Je to docela vzácné bıt zachránìn tebou.
{7899}{7915}Stejnì jako ty.
{7926}{7954}Kde je Ludwig?
{7979}{8034}Nemá zálibu v nepokojích.
{8084}{8168}Opravdu mám nìco o èem si pøeju s tebou mluvit.
{8185}{8209}Se mnou?
{8227}{8237}Ty...
{8326}{8366}Dnešek je docela úspìšnı.
{8366}{8389}Vy jste...
{8412}{8427}Isaac.
{8443}{8491}Vıroèní oslava Akademie
{8491}{8546}se stala festivalem pro celé mìsto.
{8564}{8592}To je pro vás pohoda.
{8609}{8662}Pøesnì jak jsem oèekával od Kuchenského Království.
{8677}{8699}Co se to pokoušíte øíct?
{8721}{8775}Nic. Jen jsem jednoduše pøemıšlel, co øíct.
{8797}{8879}Okolní zemì jsou teï pìknì podrádìné.
{8891}{8950}Nemají rády sledování takovıch událostí.
{8999}{9030}Mír této zemì
{9047}{9103}plyne z øízení Jeho Velièenstva a Strahlu,
{9113}{9151}spojené s pracovitostí lidí.
{9177}{9239}V tomto jsem pyšnı.
{9265}{9338}Ano, ano, mír je velice správnı a dobrı.
{9338}{9398}Znamená to, e dostanu k jídlu dobré jídlo.
{9438}{9463}Vıborné!
{9484}{9505}Tady jsou!
{9534}{9545}Huh?
{9558}{9567}Zdar!
{9587}{9613}Zase vy?
{9613}{9656}Nebuï takovı!
{9673}{9761}Pøišel jsem se podívat, jestli si pamatujete mé vyuèování.
{9761}{9835}Kolegové studenti, vidím, e si všichni uíváte.
{9887}{9932}Co dìlal Øeditel a do této doby?
{9945}{10014}Ten mu miluje tyhle shromádìní.
{10083}{10099}Dobrá, dobrá.
{10099}{10135}Je to urèitì vzrušující.
{10155}{10228}No, pøipravili jsme zajímavìjší událost.
{10243}{10334}Take, z toho dùvodu zaèíná Velké Hledání Pokladu na území Akademie!
{10363}{10384}Hledání pokladu?
{10400}{10461}Není to trochu dìtinská zábava pro mladé aristokraty?
{10471}{10559}Nìkdy je náš øeditel smìšnı.
{10559}{10650}Nejdøíve se všichni úèastníci nalosují do skupin po dvou.
{10673}{10688}Tady.
{10748}{10777}Zní to jako zábava.
{10796}{10825}Tìším se na to!
{10841}{10863}Já...
{10891}{10923}Dobrá! Tenhle!
{10953}{10968}Tenhle!
{11081}{11175}Neublíí tí to, kdy se jednou za èas budeš cítit volnì.
{11194}{11221}No tak, Naoji.
{11364}{11389}Proè se taky nepøidáte?
{11400}{11461}Jestli mì ádáš, abych bìhal jako malé dítì,
{11461}{11490}zapomeò na to.
{11506}{11585}Úèastníci se stejnımi èísly jsou tım.
{11603}{11657}Tak co? Našli všichni svého partnera?
{11690}{11729}Came, vypadá to, e jsme spolu.
{11744}{11769}Je to pravda!
{11781}{11812}Orphe, co ty?
{11823}{11833}Dostal jsem tohle.
{11860}{11897}Hm? Orphe, jsi s Naojim!
{11932}{11951}Vypadá to tak.
{11974}{12024}Dìlejme co mùeme, Naoji.
{12052}{12073}A-Ano.
{12124}{12154}Pøedmìtem hledání je...
{12174}{12224}malinkı zlatı klíè.
{12276}{12339}Hranicí je Akademie.
{12352}{12405}Budou schopni najít tak malinkı pøedmìt?
{12418}{12478}Ten, kterı opravdu sníí své ego
{12478}{12530}a podívá se nevinnıma oèima,
{12530}{12588}všechno, co si pøeje mu bude poskytnuto.
{12605}{12723}Komukoli, kdo najde klíè, bude udìlena nejvyšší pocta.
{12740}{12777}Pøeji všem hodnì štìstí.
{12800}{12812}Zaènìte!
{12834}{12868}Co bude ta nejvyšší pocta?
{12884}{12902}Kdo ví?
{12912}{12942}Protoe je to náš Øeditel,
{12942}{12985}oèekávám nìco nepøedstavitelného.
{13007}{13053}Tentokrát jsme rivalové.
{13068}{13119}Omlouvám se, ale poklad bude náš.
{13137}{13175}Také nebudeme milosrdní.
{13210}{13226}Pojïme, Came.
{13237}{13245}Dobrá.
{13287}{13304}Pojï, Naoji.
{13327}{13336}Ano.
{13428}{13471}Oh, nadšení mládí.
{13651}{13777}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{13972}{13989}U jsi to našel?
{13997}{14020}Tady to není.
{14114}{14126}Našel jsem to!
{14165}{14211}To není ono! Klíè musí bıt zlatı!
{14321}{14355}Nemyslím, e to budou ony.
{14541}{14625}Všichni jsou upøímnì tak veselí, Beruze-kun.
{14643}{14650}Ano.
{14674}{14697}Nicménì,
{14697}{14779}jako èást váeného shromádìní Akademie Rosenstolz,
{14779}{14798}je to trochu...
{14808}{14917}Mládí by se mìli cítít jednou za èas volnì a uívat si.
{14947}{15009}Zvláštì v èasech jako jsou tyto,
{15009}{15106}i kdyby jen trochu, mohou zapomenout své starosti a bıt šastní.
{15139}{15176}Zlatı klíè...
{15186}{15230}co to pøesnì je?
{15240}{15273}Oh, to.
{15297}{15324}Vlastnì,
{15324}{15414}ztratil jsem jeden ze svıch velice dùleitıch klíèù.
{15429}{15441}Huh?
{15457}{15550}Hledat ho sám by mi zabralo pøíliš mnoho èasu,
{15550}{15598}tak jsem si myslel, e bych nechal všechny pomoct.
{15618}{15669}Tedy, nejvyšší pocta...
{15686}{15722}To je pravda.
{15758}{15782}Ten klíè...
{15809}{15878}je také klíè odemykající dveøe do budoucnosti.
{16183}{16226}Ten Øeditel,
{16226}{16275}vsadím se, e musí bıt schovanı nìkdì nápadnì.
{16275}{16335}Ale tahle Akademie je tak velká...
{16335}{16390}stále si toho nebude lehké všimnout.
{16404}{16468}Mimochodem, Came, co tvùj...
{16480}{16512}Necítím vìc.
{16529}{16606}Nemùu cítit všechno, to víš.
{16619}{16676}Promiò. Nemyslel jsem to tak.
{16686}{16720}Ne, to je v poøádku.
{16781}{16833}Zajímá mì jestli jsou Orphe-san a Naoji v poøádku.
{16843}{16889}Ti dva...
{16918}{16970}Oh dobrá. Není to tak jako kdyby bojovali.
{16985}{17048}Mùe to bıt pro nì dobrá pøíleitost komunikovat.
{17450}{17510}Není to rozdílné od toho bıt sledován.
{17531}{17542}Odejdìme.
{17799}{17865}Naoji-sama! Orpere-sama!
{17865}{17892}Poèkejte na nás!
{18055}{18085}Teï by mìlo bıt snadnìjší hledat.
{18108}{18199}Tvé vzdálení se sem bylo od tebe neoèekávané.
{18231}{18333}Jako dítì jsem se èasto dostal s Eduardem do nezbedností
{18333}{18360}a byl jsem pokárán.
{18374}{18404}Ty?
{18443}{18500}Dívat se na tebe teï, je tìké si to pøedstavit...
{18534}{18649}Udìlal jsem vìci, které šokovaly mé rodièe a domácnost
{18677}{18767}a kdykoli jsem byl pokárán, šel jsem za svou sestrou, aby mì zachránila.
{19506}{19586}I za touto osobou zaplavenou svìtlem jsou stíny?
{19609}{19650}Stíny tragédie...
{19695}{19769}Jsi vskutku zajímavı kolega.
{19824}{19907}Tato tvá jasná vyrovnanost mì také uklidòuje.
{19943}{20013}Kdybych jen s tebou mluvil tímto zpùsobem døíve.
{20043}{20101}Ale ty mì nemáš rád, e?
{20120}{20149}Ne, e bych tì nemìl rád.
{20230}{20264}Není to tvoje chyba.
{20291}{20340}To já jsem ten, kdo je nezralı.
{20360}{20434}V tvé pøítomnosti se stydím.
{20449}{20478}Proè se stydíš?
{20496}{20593}No, to je mùj vlastní problém.
{20644}{20656}Aha.
{20678}{20740}Pak se dále nebudu ptát.
{20763}{20871}Prostì mì zajímá, proè by osoba jako ty mìla køáèet vedle Ludwiga.
{20871}{20898}Je to neuvìøitelné.
{20923}{21029}Vaše osobnosti a uvaování jsou tak rozdílné.
{21099}{21118}To pøipouštím.
{21606}{21673}Jsi pøeloenı student z Japonska?
{21755}{21799}Jsem Naoji Ishizuki.
{21839}{21867}Jsem Ludwig.
{21927}{21949}Pøesnì tak jsem si pøedstavoval.
{21996}{22023}Zvedni hlavu.
{22059}{22134}Nejsi tak slabı, jak si myslíš.
{22188}{22299}Máš potenciál kráèet vpøed vedle mì.
{22569}{22592}Ten Ludwig...
{22626}{22705}Luiho mysl je tìká k pøeètení a èasto nepochopená.
{22731}{22805}A on si je toho taky dobøe vìdom.
{22834}{22916}Ale já vím, e je ve skuteènosti citlivı.
{22938}{23024}Zdáš se bıt Luiem hroznì zaujatı.
{23044}{23093}Nemáš ho rád, e?
{23107}{23137}Není to tak, e ho nemám rád...
{23164}{23192}Jen mu nemùu rozumnìt.
{23230}{23293}Prozatím je to pravdepodobnì lepší tímto zpùsobem.
{23383}{23448}Nìkdo u pravdìpodobnì touto dobou našel klíè.
{23478}{23526}Moná ho našel Ed a jeho partner.
{24639}{24696}"Ten, kterı opravdu sníí své ego
{24696}{24747}a podívá se nevinnıma oèima,
{24747}{24808}všechno, co si pøeje mu bude poskytnuto."
{24852}{24895}Sníit své ego...
{25146}{25182}Oh, tady jste.
{25235}{25297}Nudil jsem se a pøišel jsem vás zkontrolovat, kluci.
{25313}{25363}Coe, našli jste klíè?
{25381}{25408}Ano. To je ono.
{25425}{25473}Není divu, e jste vy dva Kandidáti Strahl!
{25544}{25555}To je...
{25757}{25791}Je to vskutku ten klíè.
{25819}{25883}Blahopøeji. Vy dva jste vyhráli.
{25901}{25954}Na co je pøesnì ten klíè?
{26004}{26118}Ano, jak jsem øekl, tento klíè mùe vést k nejvyšší poctì.
{26139}{26182}Je to klíè velké dùleitosti.
{26394}{26498}Jen málo minulıch øeditìlù a Strahl o tomhle ví.
{26498}{26542}Je to tajnı sejf.
{26611}{26628}...tajnı?
{26682}{26795}To jsou zprávy o událostech uvnitø i vnì království,
{26826}{26928}vìtšinou od Strahl, kteøí zde promovali.
{26928}{26952}Pravidelnì mi oodávají zprávy.
{26995}{27091}A pak já podám zprávu Jeho velièenstvu a úøedníkùm.
{27135}{27160}Jak víte,
{27160}{27224}svìt je touto dobou ve stavu extrémního neklidu.
{27241}{27284}Nezáleí na tom, jak bezvıznamná data to jsou,
{27284}{27351}kadı kousek informace ja pro naše království vzácnı.
{27369}{27392}Kvùli tomu,
{27392}{27456}kdyby toto padlo do špatnıch rukou,| mohla by bıt zpùsobena nemyslitelná škoda.
{27481}{27494}Ano.
{27514}{27605}Je bezpeèné øíct nám tak dùleité tajemství?
{27630}{27700}Vìøím, e jako ti, kteøí mì informují,
{27700}{27797}budete myslet na svou zemi a na své krajany,
{27797}{27902}e obrátíte své domnìnky a budete kráèet dál smìrem k nim.
{27960}{27977}Není to tak?
{27996}{28004}Ano.
{28088}{28139}Porazili jste nás, huh?
{28152}{28170}Prohráli jsme.
{28187}{28222}Co bylo odmìnou,
{28239}{28268}Orphe-san, Naoji?
{28287}{28312}Jednou vám to øekneme.
{28328}{28348}Co s tím je?
{28360}{28381}Øeknìte nám to.
{28407}{28485}Vìøím, e vám to v blízké budoucnosti budeme schopni øíct.
{28521}{28651}Ano, dokud kráèíme po stejné cestì.
{28677}{28695}Co tím myslíte?
{28981}{29003}Lui!
{29023}{29056}Kde jsi byl?
{29056}{29097}Dnešek byl taková zábava!
{29363}{29383}Našel jsi to?
{29402}{29424}Ne, ještì ne.
{29445}{29474}To není jako ty.
{29484}{29509}Co tì zpomaluje?
{29523}{29562}Objevil jsem vodítka.
{29580}{29639}Spìchání bude nebezpeèné; nemùeme podceòovat øeditele.
{29664}{29738}Je k nìmu víc, ne jsem vidìl.
{29758}{29812}Král mu hodnì dùvìøuje.
{29826}{29845}Nechutné.
{29876}{29927}Musíš odstranit všechny ty trny v oku.
{29951}{30004}Mùu kontrolovat všechno svıma dvìma rukama.
{30036}{30072}Bude to, jak si pøeješ.
{30133}{30190}Od té doby co neznámí èlenové vstoupili na území,
{30190}{30258}myslel jsem, e nìkdo zpùsobil nìjakou akci.
{30291}{30320}Ale nestalo se tak.
{30393}{30450}Pøinejmenším dnešek nebyl úplnì marnı.
{30479}{30522}Brzy, budou jako ten klíè
{30522}{30623}a stanou se naprostou dùleitosí pro království.
{31598}{31671}-Tváø, kterou nikomu neukáeš.-
{31671}{31748}-Jen mì nech se podívat,-
{31748}{31854}-tak se uklidòuji zatímco tì hledám.-
{31906}{31973}-Unavenı vıraz,-
{31973}{32044}-pøisaju pohled na tebe.-
{32044}{32154}-Chci se tì dotknout tìma rukama. Utáhnu své sevøení.-
{32220}{32285}-Zaraenı, zmatenı,-
{32299}{32372}-mùj pohled je na tebe upøenı.-
{32410}{32473}-Tvou mìnící se tváøí-
{32481}{32552}-se mé srdce tøese.-
{32552}{32622}-Ale jednou pod tou tvojí maskou-
{32634}{32708}-chci ochránit tu zranìnou tváø.-
{32708}{32782}-Nevyhnutelná noc pøichází,-
{32782}{32854}-take tì ádám, pospìš.-
{32854}{32967}-Navìky chci bıt s tebou.-
{32967}{33060}-Pouze do té doby, ne si mì všimneš.-
{33453}{33470}Pøíští epizoda
{33504}{33538}Další doktátor.
{33568}{33594}Temnota srdce.
{33616}{33632}Zrada.
{33679}{33726}Teï nejsi sám.
{33765}{33795}TAKTIKA
