{1}{1}23.976
{28}{158}-Jestlie nastane destrukce,-
{171}{275}-nech všechno neuspoøádanì stát,-
{325}{417}-bez opìtovného pøestavování.-
{559}{645}-Máš minulost, na kterou nemùeš zapomenout?-
{704}{795}-Máš høích, kterı si pøeješ zapomenout?-
{864}{974}-Mùeš jít se svımi zranìními,-
{1001}{1151}-k symbolu, kterı byl nakonec zapomenut.-
{1168}{1292}-Pøed tebou na stezce, kde iješ,-
{1307}{1381}-jsou setkání jenom budoucí rozlouèení.-
{1394}{1457}-Násobí se a násobí se a budou se znovu násobit.-
{1471}{1595}-Pojïme pokraèovat tak, jak jsme to dìlali, s tìmi vyrytımi znaèkami,-
{1609}{1702}-take jednou mùeme bıt pyšní na-
{1766}{1859}-narození se v tomto svìtì.-
{1908}{2003}-Take mùu bıt pyšnı.-
{2959}{3026}U je to nìjakou dobu, sestro.
{3314}{3365}ZRCADLOVİ OBRAZ
{3577}{3596}Oh, Orphe-san.
{3611}{3630}Dobré ráno.
{3646}{3703}Dobré, Came, Naoji.
{3724}{3776}U je skoro èas na hodinu.
{3776}{3799}Mìli bychom si pospíšit.
{3972}{4004}Co se s ním dìje?
{4022}{4062}Zdá se bıt pøíšernì sklíèenı.
{4073}{4109}Jen ho nechte bıt.
{4126}{4172}Vdycky to takhle proívá,
{4172}{4205}kdy navštìvuje hrob své sestry.
{4224}{4246}Opravdu.
{4257}{4343}A jen pøedstírá, e se nic nedìje,
{4343}{4382}ale je nesnesitelné pro ostatní ho takhle vidìt.
{4831}{4908}Jeho sestra zemøela a on ještì neuronil jedinou slzu.
{4924}{4952}Je tak chladnı.
{4969}{5069}Ne, to je kultivované stanovisko syna markıze, které by mìl mít.
{5105}{5167}Všichni øíkáte všechno bezohlednì, prosím...
{5167}{5244}Nikdo z vás nerozumí bolesti, kterou cítí.
{5721}{5791}Zranìní, která dostal pøed dvìma lety
{5791}{5838}ještì nejsou zahojena; stále krvácejí.
{5847}{5866}Orphe-san...
{5922}{5972}Tedy, dnes tady skonèíme.
{6054}{6079}Orphere-kun?
{6099}{6109}Ano.
{6130}{6215}Je docela vzácné pøistihnout tì ve tøídì nepozorného.
{6215}{6253}Necítíš se dobøe, pravdìpodobnì?
{6266}{6321}Ne. Nejupøímnìji se omlouvám.
{6494}{6531}Nemysli na nìj, Orphe.
{6549}{6616}Tomu, kdo neumí zvládat své vlastné emoce,
{6616}{6700}nesluší bıt vùdcem muù.
{6700}{6716}Lui!
{6813}{6836}Co se dìje?
{6845}{6925}Neukáeš mi nìjakého svého obvyklého ducha?
{6933}{6966}Dìlá tì to tak zbabìlım?
{7008}{7030}Nezáleí na tom, co to je,
{7030}{7064}komukoli nemusí bıt do skoku, to víš.
{7089}{7135}Jen se ujišuju, e nikdo nevyuije tvé slabosti
{7135}{7192}a nevytrhne ti koberec zpod tvıch nohou, to je všechno.
{7523}{7530}Ano?
{7555}{7583}Hej, Orphe!
{7619}{7627}Ede?
{8090}{8150}Atmosféra je na denní dobu jistì nezvyklá.
{8161}{8251}A já jsem si myslel, e bys nikdy nesouhlasil s odplíením se ze školní pùdy.
{8303}{8334}Zapomnìl jsi?
{8348}{8436}V minulosti jsme èasto neuposlechli taková pravidla,
{8436}{8478}a byli hubováni našimi otci, pamatuješ?
{8502}{8525}Samozøejmì.
{8551}{8607}Uvolnit se jednou za èas neuškodí,
{8607}{8666}kromì toho, jsou vìci, které se ve tøídì nenauèíme.
{9216}{9295}Kráèet takhle mezi všemi
{9295}{9359}je jedinı zpùsob, jak cítit jejich radosti a bolesti.
{9385}{9459}Kdyby Ludwig poslouchal jejich srdce,
{9459}{9514}jeho myšlení by se aspoò o trošku zmìnilo.
{9514}{9547}Nejsem si tím tak jistı.
{9601}{9609}Ede,
{9676}{9690}díky.
{9743}{9762}Netøeba.
{9814}{9824}Hej!
{9824}{9852}Jak neoèekávané,
{9902}{9974}potkat vás na takovém místì v takovou hodinu.
{9988}{10000}Isaac...
{10030}{10050}Oh, boe.
{10339}{10391}Jste si jistí, e je to v poøádku?
{10391}{10452}Jste nakonec Kandidáti Strahl Akademie Rosenstolz.
{10452}{10486}Jen to drte v tajnosti.
{10507}{10605}Vsadím se, e jste ve vašich školních letech dìlal to samé.
{10617}{10733}No... jistì, nebyl jsem naprosto vzornı student...
{10733}{10856}V kadém pøípadì, chci se vás dvou na nìco zeptat.
{10872}{10893}Zeptat se nás na nìco?
{10940}{10953}Následujte mì.
{11019}{11030}Kam?
{11076}{11149}Jestli je to noc ve mìstì, kterou chcete, nechte to na mì.
{11363}{11376}Vítejte.
{11386}{11397}To je...
{11413}{11478}Hej, Isaacu! Co 'kolo zápasu'?
{11489}{11517}Promiò, chlape.
{11517}{11545}Hlídám dìti.
{11677}{11725}Dal byste tìm dvìma nìjakı dus.
{11778}{11878}Opravdu z nás dvou dìláte dìti.
{11910}{11933}Na co jste se nás chtìl zeptat?
{12037}{12110}No, kdy jsem nedávno navštívil Akademii,
{12110}{12181}myslím, e jsem vidìl nìkoho koho znám.
{12181}{12234}Myslím, e je na fakultì.
{12234}{12289}Je pìknì vysokı a nosí brıle.
{12289}{12319}Je kolem nìj chladnı vzduch.
{12335}{12365}Beruze-sensei?
{12398}{12417}Beruze.
{12612}{12667}Byl jmenován na zaèátku roku,
{12667}{12714}ale nebude mluvit o detailech.
{12731}{12795}Není úplnì nejpøístupnìjší osobou.
{12807}{12836}Take... co s ním?
{12888}{12899}Ne...
{12909}{12947}Já... pravdìpodobnì jsem se mılil.
{13003}{13021}Jak to mùe bıt?
{13053}{13072}Vyhrál jsem.
{13083}{13121}Tady, u jsem to dohnal.
{13135}{13188}Coe? Oblièej, kterı nepoznávám.
{13188}{13254}Poslední dobou je jich tu hodnì...
{13254}{13290}beznadìjní ztroskotanci nikdo neví odkud.
{13508}{13557}Slyšel jsem, e jsi dobrı.
{13574}{13608}Co zápas?
{13618}{13635}Promiò.
{13635}{13678}Dneska nemám náladu.
{13691}{13725}Coe? Utíkáš?
{13885}{13916}Dej mi tolik, kolik za tohle mùu vypít.
{13931}{13980}Dej si pauzu, Douglasi!
{13980}{14024}Jsi opilı kadou noc.
{14024}{14058}Zavøi hubu!
{14058}{14096}Jen mi to podej!
{14397}{14455}No tak, no tak, dáváš takové dobré víno nazmar.
{14479}{14502}Jako kdybych se staral!
{14514}{14538}Tohle mnoství nic není.
{14588}{14609}To staèí.
{14658}{14730}Nejsi tak politováníhodnı, aby si's zaslouil takové zoufalství.
{14730}{14746}Coe?
{14757}{14768}Orphe...
{14779}{14850}Dìlat tohle... nebude ti pomoci.
{14885}{14916}Co máš za problém?
{14926}{14971}Tak nadutı?
{15044}{15091}Oh, no tak.
{15103}{15141}Co ty víš?
{15156}{15225}Co ty víš o nìèem kromì míru tohoto království?
{15287}{15333}Zvìrstva, která jsem vidìl...
{15333}{15376}Tohle je jedinı zpùsob, jak je mùu zapomenout!
{15477}{15569}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{16099}{16122}Jsi velmi smutnı, e.
{16140}{16151}Came...
{16180}{16274}Ty kvìtiny mohou cítit smutek Orpha-san.
{16628}{16638}Orphe!
{16667}{16701}Co ty víš?
{16723}{16782}Má zemì byla smetena do války.
{16860}{16923}Udìlal jsem všechno, co jsem mohl, abych unikl se svou rodinou.
{17637}{17687}Byl jsem tak blízko.
{17748}{17829}Udìlal bych cokoli, abych na ten okamik zapomnìl.
{18775}{18826}Stále máš ten vıraz?
{18826}{18843}Lui...
{18907}{18983}Co se opravdu pokoušíš udìlat,
{18983}{19007}Orphere?
{19094}{19183}Vdycky mluvíš o té utopii, kterou plánuješ vybudovat.
{19201}{19260}Kde na to najdeš hybnou sílu?
{19326}{19394}Pohodové filozofování vìc nezmìní.
{19394}{19497}Mnohem ménì pøedstavivosti nìkoho, kdo |nechápe, kde mu jeho kroky budou sebrány.
{19976}{20023}Za jakım... úèelem...?
{20611}{20650}Jestli nic nesníš,
{20650}{20672}onemocníš.
{20706}{20714}Ede.
{20764}{20800}Nemùu zapomenout.
{20835}{20883}Nemìla by to bıt tak nesmyslná smrt.
{21301}{21357}Tehdy, jsem pøísahal.
{21379}{21468}Abych zabránil nevinnım, aby byli obìtování jako má sestra,
{21481}{21540}zkoušel jsem to nejlepší ze svıch schopností.
{21602}{21614}Ale...
{21671}{21738}Mohl jsem pouze popírat realitu?
{21746}{21763}Orphe.
{21780}{21873}On... Douglas a já... jsme stejní.
{21894}{21995}Obrátit mùj smutek ze sestøiny smrti ve zlobu,
{21995}{22091}sleduju své ideály pøedstírající, e jsem se zotavil.
{22149}{22163}Orphe.
{22215}{22338}Pravdepodobnì jsem nakonec nemìl pøemıšlet o lidech.
{22479}{22535}Orphe-san øekl takovou vìc?
{22561}{22613}A já onìmìl.
{22636}{22701}I poté, co jsem slíbil, e mu vdy pomùu a budu mu po boku.
{22737}{22801}Orphe-san jistì rozumí tvé dobré vùli, Ede.
{22823}{22895}Ano, musí si to pro sebe uvìdomit...
{22924}{22962}jako Lui,
{22962}{23062}vlastní fascinující charisma a sílu k odemèení budoucnosti.
{23096}{23147}Tím jsem si jistı.
{23436}{23450}Vítejte.
{23481}{23494}Oh?
{23521}{23568}Zase ty? Sám?
{23765}{23789}Kde je Douglas?
{23789}{23837}Oh, dnes nepøišel.
{23852}{23874}Co bys od nìj potøeboval?
{23977}{24006}Všechno...
{24006}{24110}je všechno jen sebe-utìšující pokrytectví?
{24160}{24176}Take,
{24176}{24235}všechno si's uvìdomil po setkání s Douglasem?
{24281}{24301}Je to pravda.
{24322}{24380}Douglas a ty jste odlišní lidé.
{24395}{24419}Vaše situace, také.
{24441}{24456}Vítejte.
{24488}{24500}Pøišel.
{24568}{24593}Oh!
{24593}{24625}To jsi ty!
{24648}{24737}Perfektní. Musíš si se mnou dneska zahrát!
{24737}{24818}Podívej jak jsi opilı. Nemìl bys tak moc, abys uchopil tágo!
{24818}{24847}Co jsi to øekl?
{24860}{24872}Pøestaò.
{24872}{24949}Kdo je to? Spratek ze vèerejška?
{24949}{24965}Pus!
{24977}{25058}Tvoje rodina by tì nechtìla takhle vidìt.
{25112}{25158}Pøestaò dìlat vìci, které ti ubliují.
{25158}{25178}Sklapni!
{25366}{25415}Není to zajímavı pøedmìt.
{25426}{25464}Vra to zpátky.
{25464}{25542}Zdá se to jako nìco, co by nosilo dítì z vyšší tøídy.
{25606}{25615}Poèkej!
{25918}{25933}Nechoï blí!
{25950}{25975}Vra to zpátky!
{26018}{26073}Musí to bıt nìco cenného,
{26073}{26134}kdy to mùe pøidìlávat starosti bohatému chlapeèkovi.
{26308}{26327}Jaká vìc.
{27224}{27243}Jsou všichni v poøádku?
{27283}{27292}Ano.
{27387}{27426}Proè jsi mì zachránil?
{27489}{27572}Jen jsem si myslel, e kdybys umøel,
{27605}{27648}tvá rodina by jistì truchlila.
{27675}{27702}Takhle se vmìšovat...
{27739}{27795}Moná jsem s nimi mìl bıt spojenı.
{27842}{27921}I tak jsem tì stále chtìl zachránit.
{27973}{28031}Jestli mì za to chceš nenávidìt, do toho.
{28132}{28199}Nemohl jsem ho zachránit.
{28235}{28295}Nepøedstavoval jsem si, e je nutné se nad tím znepokojovat.
{28322}{28367}Obìtoval jsi svùj vzácnı pøívìsek,
{28367}{28397}abys ho zachránil, ne?
{28416}{28426}To je...
{28446}{28520}Pøinejmenším pochopil, jak se teï cítíš.
{28545}{28613}Tvé pøesvìdèení se moná jednoho dne uvolní
{28613}{28664}do síly, která by mohla zachránit království.
{28711}{28775}Ah dobrá. Sleduj, aby tì nechytili mimo školní pùdu po setmìní,
{28775}{28824}abys nebyl vypovìzenı.
{29485}{29499}Orphe.
{29550}{29602}Ede, omlouvám se.
{29656}{29675}To je v poøádku.
{29904}{29919}Díkybohu.
{29932}{29976}Orphe-san je zase v poøádku.
{29997}{30022}Teï se nemusíme znepokojovat.
{30034}{30162}Bylo by to únavné, vidíte, bez nìj kolem, aby mi oponoval.
{30188}{30207}Oh, no tak Lui.
{30550}{30614}Vra mu to za mì.
{30692}{30706}Rozumím.
{30832}{30884}Protoe existují lidé jako on,
{30884}{30942}moná bych nemìl vzdávat budoucnost.
{31582}{31653}-Tváø, kterou nikomu neukáeš.-
{31653}{31725}-Jen mì nech se podívat,-
{31725}{31833}-tak se uklidòuji zatímco tì hledám.-
{31886}{31952}-Unavenı vıraz,-
{31952}{32029}-pøisaju pohled na tebe.-
{32029}{32131}-Chci se tì dotknout tìma rukama. Utáhnu své sevøení.-
{32202}{32260}-Zaraenı, zmatenı,-
{32281}{32356}-mùj pohled je na tebe upøenı.-
{32391}{32460}-Tvou mìnící se tváøí-
{32460}{32533}-se mé srdce tøese.-
{32533}{32602}-Ale jednou pod tou tvojí maskou-
{32602}{32690}-chci ochránit tu zranìnou tváø.-
{32690}{32763}-Nevyhnutelná noc pøichází,-
{32763}{32836}-take tì ádám, pospìš.-
{32836}{32939}-Navìky chci bıt s tebou.-
{32939}{33037}-Pouze do té doby, ne si mì všimneš.-
{33074}{33216}Jen pro zajímavost - Oni mají ten ending naèasovanı nìjak podivnì, |já ho mám dobøe, jen nesedí na ty titulky, ale pøímo na hudbu ;P
{33436}{33457}Pøíští epizoda
{33484}{33506}Sídlo na bøehu jezera.
{33530}{33555}Noèní zábavy.
{33585}{33616}Ráj a Oèistec.
{33660}{33710}Teï nejsi sám.
{33740}{33762}KALNOST
