{1}{1}23.976
{28}{159}-Jestliže nastane destrukce,-
{170}{275}-nech všechno neuspoøádanì stát,-
{323}{415}-bez opìtovného pøestavování.-
{560}{644}-Máš minulost, na kterou nemùžeš zapomenout?-
{711}{794}-Máš høích, který si pøeješ zapomenout?-
{857}{975}-Mùžeš jít se svými zranìními,-
{998}{1148}-k symbolu, který byl nakonec zapomenut.-
{1166}{1291}-Pøed tebou na stezce, kde žiješ,-
{1306}{1378}-jsou setkání jenom budoucí rozlouèení.-
{1392}{1457}-Násobí se a násobí se a budou se znovu násobit.-
{1470}{1595}-Pojïme pokraèovat tak, jak jsme to dìlali, s tìmi vyrytými znaèkami,-
{1609}{1701}-takže jednou mùžeme být pyšní na-
{1762}{1854}-narození se v tomto svìtì.-
{1909}{2004}-Takže mùžu být pyšný.-
{2515}{2564}Co se dìje, gentlemani?
{2587}{2653}Vlastnì, našli jsme tohle.
{2695}{2711}To je...
{2739}{2770}Zdá se, že je to odposlouchávací zaøízení.
{2795}{2815}Oh?
{2815}{2846}Odposlouchávací?
{2846}{2900}Bylo postavené ve váze v knihovnì.
{2929}{3004}Nìkdo se pokoušel poslouchat naše rozhovory.
{3047}{3136}Máte podezøení týkající se 'nìkoho', gentlemani?
{3199}{3239}Jsem tak podezøelý?
{3330}{3349}Ludwigu...
{3388}{3445}Viník možná není student.
{3473}{3505}Co tím myslíš?
{3531}{3575}Nemá to hlubší význam.
{3665}{3704}TAKTIKA
{3756}{3805}Výmìnný student?
{3822}{3860}Ano.
{3876}{3943}Dostal jsem pozvání od Gleichheit,
{3943}{4017}proslulé školy z Provincie Heartville.
{4029}{4076}Mluvit o Gleichheit...
{4076}{4174}Øediteli, slyšel jsem, že váš bývalý kolega je tam pøedsedou pøedstavenstva.
{4193}{4234}Ano, je tam pøedsedou pøedstavenstva.
{4234}{4296}Požádal mì, abych podpoøil pøátelství mezi dvìma akademiemi,
{4296}{4407}abych uvážil výmìnu studentù.
{4432}{4526}No, øíkáme "výmìnu", ale nebude to stálé,|jen po dobu dvou týdnù.
{4543}{4607}Myslím, že je to dobrý nápad.
{4626}{4660}Vìdìl jsem, že si to budeš myslet.
{4677}{4735}My na Akademii Rosenstolz
{4735}{4795}se ovlivòujeme s ostatními školami velmi zøídka, nakonec.
{4816}{4864}Kdo se plánuje na výmìnu?
{4984}{5004}Omluvte nás.
{5036}{5088}Oh, jste tu oba?
{5088}{5149}Pak to nechám na vás dvou!
{5196}{5206}Huh?
{5274}{5354}Jsem unavený Øeditelovou rozmarností!
{5372}{5428}Zavolal si nás tak najednou a teï tohle!
{5443}{5476}Protože jsi to ty,
{5476}{5513}i když budeš na Akademii Gleichheit,
{5513}{5557}jsem si jistý, že si hned najdeš pøátele.
{5580}{5654}Abychom nepošpinili povìst naší Akademie,
{5654}{5686}budeme obzvláštì opatrní.
{5711}{5779}Oba dva, buïte si jistí, že se o sebe dobøe staráte.
{5792}{5838}Jsou to jen dva týdny.
{5838}{5865}Není to tak hrozné.
{5890}{5920}Pojïme!
{5929}{5942}Ano.
{6051}{6079}Budeme osamìlí.
{6108}{6144}Necítím to stejnì.
{6194}{6286}Spíše, dva studenti, které dostaneme na výmìnu...
{6301}{6335}Zajímá mì, co mají  rádi.
{6566}{6613}Ishtar-sama, to je...
{6940}{6988}To je Anton Eckhart-kun,
{6988}{7032}Herman Jodell-kun,
{7032}{7082}a Ishtar Vermilia-kun.
{7164}{7279}Jsou to výmìnní studenti z Akademie Gleichheit.
{7301}{7335}Být schopni poznat
{7335}{7418}tak vzdìlané Kandidáty Strahl,
{7418}{7449}je opravdová èest.
{7481}{7495}Žena?
{7512}{7545}Ano. Správnì.
{7562}{7616}Proè jsi takto obleèená?
{7645}{7710}Mùj otec, který nemìl mužského dìdice,
{7710}{7794}povýšil mì, svou jedinou dceru, jako syna.
{7833}{7898}Je to dcera rodiny Vermilia,
{7898}{7942}která má blízké vazby s Králem.
{7957}{8027}Buïte si jisti, že jí nechybí žádný respekt.
{8045}{8092}Jako dítì,
{8092}{8175}jsem jednou na plese vidìl Markýze Vermiliu.
{8204}{8236}Jsem Orpherus.
{8417}{8432}Co se dìje?
{8478}{8494}Øeknu ti to pozdìji.
{8582}{8600}Temnota srdce?
{8630}{8681}Cítil jsi to uvnitø ní?
{8695}{8705}Ano.
{8738}{8791}Camova intuice je nakonec velice bystrá.
{8791}{8880}Ishtar musí nìco intrikovat.
{8906}{8934}Nemožné.
{8934}{8999}Je dcerou proslulé rodiny Vermilia.
{9015}{9023}To je jen krytí.
{9113}{9207}V domácnosti Vermiliù jistì nejsou žádné dìti,
{9239}{9318}a pokud jde o Markýze Vermiliu,
{9318}{9364}je zde o nìm spousta ošklivých øeèí.
{9392}{9415}Ošklivých øeèí?
{9433}{9574}Markýz je nadmìrnì pøitahován ženskou spoleèností.
{9587}{9634}Jinými slovy je to suknièkáø.
{9656}{9697}To je jen neodùvodnìná fáma.
{9724}{9800}Ale i ve fámách,
{9800}{9872}existuje informace na uvìøení.
{9892}{10021}Zítra mám nìjaké vìci na zaøízení v Heartville.
{10021}{10057}Jestli budu mít èas,
{10057}{10117}udìlám pro vás výzkum rodiny Vermilia.
{10133}{10148}Mohl byste?
{10174}{10238}No, nejdøíve mi budete dlužit jedno jídlo!
{10798}{10854}Je to vùnì kolínské?
{10931}{10941}To je.
{11040}{11066}Pìkná vùnì.
{11419}{11510}Tradice neznamená tvrdohlavì ochraòovat staré zvyky.
{11551}{11605}V našem Království Kuchen,
{11605}{11659}ženy, s druidy na vrcholu,
{11659}{11739}drží nejvyšší služby v náboženských kruzích, ale,
{11739}{11805}muži kontrolují politiku a ekonomiku.
{11823}{11902}Nicménì, já ochraòuji toto!
{11902}{11959}Teï není èas na mluvení;
{11959}{12015}s èiny, nechte nás opravit tuto nespravedlnost!
{12064}{12110}S pøíchodem nové éry,
{12110}{12143}ženy získají právo volit!
{12201}{12303}Vy všichni, kteøí podporujete mé ideály,
{12303}{12348}prosím sledujte mou cestu
{12348}{12405}a noste tuto èervenou stuhu na své hrudi.
{12484}{12513}Prosím, pro mì taky jednu!
{12797}{12837}Blahopøeji ti k tvému projevu.
{12851}{12871}Dìkuji mnohokrát.
{12895}{12926}S tím,
{12926}{13015}se snadno zmocníš srdcí tìchto hlupákù.
{13096}{13120}Co tím sleduješ?
{13215}{13351}Pokouším se zvýšit poèet následovníkù mých vìcí.
{13369}{13409}Politický motiv?
{13430}{13439}Ano.
{13439}{13463}Jaké pøekvapení.
{13501}{13520}Proè?
{13540}{13607}Ten, kdo touží velet zemi
{13607}{13664}by mìl mít jasné oèi.
{13753}{13883}"Vidìl jsem ženu sedící na šarlatovém zvíøeti."
{13883}{13958}"A žena byla obleèena ve fialové a šarlatové,"
{13958}{14007}"a ozdobena zlatem,"
{14007}{14135}"držící ve své ruce zlatý pohár plný opovržení"
{14135}{14253}"a špíny jejího smilstva."
{14271}{14285}To je...
{14330}{14391}Zjevení Jana, kapitola sedmnáct.|/Jinými slovy, Zjevení 17 z Bible./
{14455}{14528}Hodí se to dobøe k záhadné osobì jako jsi ty.
{14618}{14646}Ten muž...
{14646}{14712}možná už objevil mùj plán.
{14734}{14785}Opravdu, Ishtar-sama?
{14797}{14822}Ale jak?
{14838}{14870}To také nevím.
{14892}{14955}Ale, pokraèovat takto by bylo nebezpeèné.
{14976}{14995}Co dìlat?
{15041}{15104}Mám plán.
{15211}{15231}Mùžete odejít.
{15248}{15262}Sbohem.
{15706}{15733}Ludwigu-sama.
{15776}{15795}Ty jsi...
{15944}{15981}Èekala jsem na tebe...
{16386}{16504}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{16548}{16604}Nastrèit to blízko Ludwiga.
{16639}{16719}Pravdìpodobnì odkryl naše plány.
{16731}{16766}Zaznamenat jeho rozhovory,
{16766}{16828}tak že mùžeme pøedvídat jeho jednání. Rozumíš?
{16842}{16852}Ano.
{17161}{17234}Ishtar Vermilia navštìvovala Akademii týden,
{17272}{17355}a poèet jejich podporovatelù stále roste.
{17355}{17429}Sleèna nazývaná Ishtar
{17429}{17472}se zdá být docela osobností.
{17517}{17615}Její tvrzení, že je dcerou rodiny Vermilia je lež.
{17625}{17641}Lež?
{17656}{17702}Je to schovanka.
{17712}{17760}Je to pravda?
{17853}{17921}Ishtar má podporu Makrýze Vermilii,
{17939}{17992}a v Akademii Gleichheit,
{17992}{18091}se stala stínem pøedsedy, ovládající významnou moc.
{18104}{18209}Ale i s podporou Markýze,
{18209}{18309}pøinutit školu dìlat, co si pøeje je naprosto nemožné.
{18364}{18466}Je tu fanatická parta jejich následovníkù.
{18466}{18504}Pøišpendlí èervené stuhy na svou hruï
{18517}{18598}a zpùsobí všude rebelie,
{18617}{18722}nutí jejich Akademii souhlasit s každým Ishtaøiným požadavkem.
{18744}{18762}Èervené stuhy?
{18792}{18807}Mohlo by to být...
{18826}{18950}Ishtar chce udìlat to samé v naší Akademii?
{19028}{19090}Chci kontrolovat tuto Akademii?
{19157}{19215}O èem to mluvíš?
{19215}{19262}To je dost odporný vtip.
{19276}{19305}To není vtip.
{19348}{19401}Co se pokoušíš udìlat na téhle Akademii?
{19401}{19426}Ishtar-sama.
{19568}{19589}Ludwigu?
{19650}{19736}Ludwig-sama se stal naším ochráncem.
{19760}{19773}Ty blázne...
{19846}{19932}Víš, co plánuje udìlat na téhle Akademii?
{19932}{19966}Samozøejmì, že ví.
{19980}{19991}Cože?
{20010}{20079}Je to proto, že zná ambice Ishtar-sama,
{20079}{20140}tak je ochotný stát se jejím ochráncem.
{20284}{20321}Mohlo by to být... ty...
{20479}{20514}Stydím se za tebe.
{20788}{20822}Slyšel jsem to od Orpha.
{20838}{20870}Je to pravda, Lui?
{20912}{20946}Spøáhl jsi se s tou ženou?
{21019}{21068}Je to lež, že? To musí být...
{21281}{21305}Jsem s tím spokojený.
{21586}{21642}Civìt takhle na mìsíc...
{21653}{21695}mi pøipomíná tu noc.
{21740}{21753}Ano.
{21841}{21932}Jestli je tvùj plán použít tvé tìlo, abys mì pøesvìdèila,
{21932}{21966}pak to není potøeba.
{22007}{22021}Proè?
{22103}{22157}Protože sdílím tvé ambice.
{22391}{22429}Spøáhnìme se.
{22429}{22499}Nezradil bych tì.
{22516}{22559}Nezradil bys mì?
{22599}{22656}Mùžu ti vìøit?
{22679}{22725}To záleží na tobì.
{22739}{22842}Neøekl jsem to ani ze zodpovìdnosti ani z povinnosti,
{22868}{22937}ale z hrdosti.
{22993}{23119}Ale, s dnešní zmìnou událostí, zaèínám ti vìøit.
{23261}{23302}Co je to?
{23315}{23358}Studentské petice.
{23378}{23402}Petice?
{23420}{23580}Cítí, že by se mìla Ishtar Vermilia pøemístit natrvalo.
{23590}{23625}To je nemožné.
{23625}{23714}Ale studenti trvají na tom, že si ji musíme ponechat,
{23714}{23770}i kdyby to znamenalo zmìnìní pravidel.
{23795}{23860}Dovolávají se shromáždìní.
{23890}{23918}Co jsi to øekl?
{23946}{24025}Vytiskni mé jméno trochu vìtším.
{24039}{24059}Rozumím.
{24074}{24111}Ihned.
{24236}{24250}Lui...
{24304}{24340}Ta vùnì...
{24340}{24372}je velmi uklidòující.
{24404}{24464}Na konci tohoto shromáždìní,
{24464}{24521}se oficiálnì stanu studentem této Akademie.
{24586}{24669}Mým dalším cílem je stát se Kandidátem Strahl.
{24698}{24797}Jen muži se mohou stát Kandidáty Strahl.
{24812}{24897}Tak proè nezmìníme pravidla?
{24897}{25006}Povzbudila bych studenty a všechno bude fungovat.
{25045}{25152}Jsou užiteèné nástroje pro dosažení mých snù.
{25250}{25311}Upøela jsem zrak na tuto Akademii protože
{25311}{25367}je to zkratka do paláce.
{25391}{25478}Jednoho dne budu stát na vrcholu tohoto království.
{25505}{25518}Lui,
{25532}{25578}když ten èas pøijde, prosím buï po mém boku.
{25689}{25805}Ti, kteøí jsou o sobì ujištìni mají mnoho slabostí.
{25805}{25884}Takhle, byli snadno pøesvìdèeni mým proslovem.
{25906}{25986}Brzy se to samé stane v národním mìøítku.
{26036}{26056}Vskutku.
{26071}{26174}Ti, kteøí jsou o sobì ujištìni mají mnoho slabostí.
{26333}{26427}Zdá se, že nìkdo nahrával rozhovor v této místnosti.
{26475}{26537}Jestli bude tohle publikované,
{26537}{26623}tvoje povìst mezi studenty bude znièena.
{26702}{26732}Prosím nedìlej si legraci.
{26745}{26776}Jsi mùj...
{26860}{26895}L-Ledaže...
{26913}{26928}Myslíš to vážnì?
{27024}{27038}Proè?
{27072}{27164}Nesdílel jsi mé ambice?
{27179}{27202}Pøirozenì.
{27217}{27288}Mým cílem je také dosáhnout vrcholu tohoto království.
{27308}{27343}Ale ne jako ty,
{27359}{27457}která touží po moci provedením svých vlastních cílù,
{27482}{27563}pøeji si vydláždit budoucnost pro toto království,
{27563}{27597}takže potøebuji moc.
{27682}{27811}Takže... co chceš, abych udìlala?
{27851}{27887}Nezradil bych tì.
{28173}{28207}Udìlali jsme to jak jste naøídil.
{28237}{28337}Taková krása nesluší takovým zkaženým ambicím.
{28350}{28430}Odejdìte jak jste.
{28466}{28539}To je mé jediné pøání.
{28603}{28618}Lui...
{29100}{29140}Skoro jsme se dostali k Akademii.
{29157}{29208}Doufám, že jsou všichni v poøádku.
{29616}{29678}Ta sleèna se zdá být tak osamìlá.
{29699}{29724}Ano?
{29743}{29836}Pro mì, její oèi vypadají naprosto jasnì.
{30338}{30422}Zdá se, že Ishtar Vermilia odešla neoèekávanì.
{30468}{30514}Nìjací studenti šíøí
{30514}{30592}fámu, že jsi se toho zúèastnil.
{30755}{30817}Vìdìl jsem, že Lui ochraòoval Akademii.
{30850}{30874}Ludwigu...
{30936}{30984}Všechno je koneènì klidné.
{30993}{31023}Pùvodní atmosféra...
{31057}{31097}sluší této Akademii dobøe.
{31604}{31673}-Tváø, kterou nikomu neukážeš.-
{31673}{31747}-Jen mì nech se podívat,-
{31752}{31856}-tak se uklidòuji zatímco tì hledám.-
{31909}{31976}-Unavený výraz,-
{31976}{32052}-pøisaju pohled na tebe.-
{32052}{32153}-Chci se tì dotknout tìma rukama. Utáhnu své sevøení.-
{32224}{32284}-Zaražený, zmatený,-
{32294}{32373}-mùj pohled je na tebe upøený.-
{32412}{32478}-Tvou mìnící se tváøí-
{32478}{32556}-se mé srdce tøese.-
{32556}{32629}-Ale jednou pod tou tvojí maskou-
{32629}{32711}-chci ochránit tu zranìnou tváø.-
{32711}{32783}-Nevyhnutelná noc pøichází,-
{32783}{32857}-takže tì žádám, pospìš.-
{32857}{32972}-Navìky chci být s tebou.-
{32972}{33062}-Pouze do té doby, než si mì všimneš.-
{33452}{33476}Pøíští epizoda
{33507}{33529}Vyhnanství.
{33553}{33575}Nevýslovná zranìní.
{33599}{33636}Zrcadlo duše.
{33685}{33736}Teï nejsi sám.
{33766}{33795}ZRCADLOVÝ OBRAZ
