{1}{1}23.976
{28}{154}-Jestlie nastane destrukce,-
{169}{270}-nech všechno neuspoøádanì stát,-
{323}{416}-bez opìtovného pøestavování.-
{560}{645}-Máš minulost, na kterou nemùeš zapomenout?-
{705}{795}-Máš høích, kterı si pøeješ zapomenout?-
{861}{975}-Mùeš jít se svımi zranìními,-
{998}{1148}-k symbolu, kterı byl nakonec zapomenut.-
{1162}{1292}-Pøed tebou na stezce, kde iješ,-
{1302}{1380}-jsou setkání jenom budoucí rozlouèení.-
{1392}{1457}-Násobí se a násobí se a budou se znovu násobit.-
{1468}{1594}-Pojïme pokraèovat tak, jak jsme to dìlali, s tìmi vyrytımi znaèkami,-
{1608}{1703}-take jednou mùeme bıt pyšní na-
{1759}{1854}-narození se v tomto svìtì.-
{1906}{2003}-Take mùu bıt pyšnı.-
{2639}{2652}Sestro.
{2669}{2719}Pojï sem, Orphe.
{2801}{2846}To je mùj bráška Orpherus.
{2875}{2942}Orphe, to je Markız Shiraiya.
{2961}{3005}Je mi ctí vás poznat, Markızi.
{3021}{3051}Øíkej mi jen Albert.
{3072}{3132}Kromì toho, brzy budeme bratøi.
{3798}{3866}Teï u to nebude dlouho, Robertino.
{4080}{4133}SKUTEÈNOST
{4183}{4211}Jeho Velièenstvo?
{4224}{4235}Ano.
{4257}{4362}Brzy pøijede, aby pozoroval Akademii Rosenstolz.
{4378}{4415}Je to další krátkodobì oznámená vìc?
{4435}{4499}Pøeje si osobnì rozmlouvat s tìmi, kteøí
{4499}{4555}vezmou na svá bedra tíhu budoucnosti království.
{4585}{4632}Dále ještì pomoc s jeho pozorováním,
{4632}{4735}chci abyste ho vy, Kandidáti Strahl, doprovázeli|a provázeli po okolním území.
{4759}{4801}My?
{4820}{4871}Netøeba se rozèilovat.
{4890}{4968}Jako vy všichni, Jeho Velièenstvo promovalo na této Akademii.
{5244}{5312}Setkal jsi se s ním døíve, e, Orphe?
{5325}{5384}Ano, kdy jsem byl ještì dítì,
{5384}{5471}mì mùj otec vzal do Královského Paláce, aby mu oplatil návštìvu.
{6203}{6276}Jako kluk jsem se rozhodl,
{6276}{6404}e jednoho dne budu tomu mui slouit a pracovat pro tohle království.
{6417}{6491}Aèkoli jsem se s ním ještì nesetkal,
{6491}{6590}mùj otec mi øekl, e je to velmi milı mu.
{6615}{6685}Je také moudrım správcem,
{6685}{6773}pracující se starosty, aby ochránil
{6773}{6910}Kuchenské Království od sousedních zemí v této chaotické dobì.
{6924}{6975}Kdy u mluvíme o starostech, pøijedou také?
{6988}{7072}Pochybuji, e všichni, ale nìkolik z nich ho pravdìpodobnì doprovodí.
{7094}{7134}Byli jsme vybráni
{7145}{7221}nejenom abychom s ním rozmlouvali.
{7239}{7253}Lui?
{7303}{7320}Co tím myslíš?
{7333}{7470}Moná pro sebe zamıšlí potvrdit budoucnost Strahlu.
{7483}{7508}A?
{7549}{7625}Pravdìpodobnì si pøeje zabezpeèit budoucnost království,
{7667}{7793}protoe Kuchen není tak stabilní, jak se zdá.
{7819}{7828}Kdo je to?
{7993}{8060}Vısledkem toho jsme získali vıznamnı vliv.
{8090}{8141}Pohyby nepøítele jsou pøíliš nápadné.
{8155}{8292}Kdy budeme hledat, musí se objevit dùkaz objasòující viníkovu identitu.
{8310}{8413}I kdybychom nemohli chytit vùdce, kterı je za tím,|mùeme pøinejmenším zmaøit jeho plány.
{8475}{8493}Ludwigu...
{8505}{8657}Otèe, nenechám si uniknout tuto monost pozvednout naše spoleèenské postavení.
{8771}{8822}Nezáleí na tom, jak je strom velkı,
{8822}{8894}stále mùe spadnout jestli bude zamoøen škùdci.
{8907}{8996}Moudrı se zmocní vıhody útoèit první.
{9553}{9651}Fakt, e v jeho minulosti není nic podezøelého|ho dìlá ještì podezøelejším.
{9750}{9897}Jmenován jako uèitel na Akademii Rosenstolz|na doporuèení Sira Twala...
{9977}{10053}Pøejeme vám dobré zdraví, Vévodo Halberte.
{10090}{10121}Jsem zdravı!?
{10127}{10136}Já...
{10150}{10208}Co všichni dìláte!?
{10229}{10327}Teï kdy by i jeden další spojenec pøinesl prospìch naší vìci,
{10351}{10455}nebudu mít více tohoto triviálního nemyslu!
{10626}{10739}Kolik stoupencù se k nám doposud pøidalo?
{10957}{11000}Není èasu nazbyt.
{11020}{11065}Budu pkraèovat jak jsem plánoval.
{11080}{11140}To u víme moc dobøe.
{11161}{11261} Pøijde nová doba a svìt bude váš, Vévodo.
{11286}{11335}Ale my mùeme jen tajnì pokraèovat, protoe
{11353}{11481}starostové a Markız Liechenstein, kteøí jsou vìrní králi,
{11481}{11553}u objevili trasy našich èinností.
{11578}{11590}Mohlo by to bıt...
{11630}{11699}e je mezi námi...
{11699}{11723}zrádce?
{11740}{11751}To je...
{11751}{11781}To je nemoné!
{11814}{11835}Nezapomeòte.
{11856}{11925}Souèasnı politickı systém se soustøedí okolo starostù,
{11947}{12063}kterı vyluèuje vás všechny z kruhu pùsobnosti.
{12105}{12123}A-Ano.
{12141}{12199}Pod vaším vedením, Vévodo Halberte,
{12199}{12299}se budeme snait ze všech sil vytvoøit lepší budoucnost.
{12577}{12614}Skupina zbyteènıch idiotù.
{12628}{12703}Není to vaše vıhoda, Vévodo?
{12842}{12870}Co tím myslíš?
{12888}{12955}Jestli se objeví na vaší pozici mocnı soupeø,
{12955}{13032}poté, co vyhrajete korunu,
{13049}{13079}to prokáe pøekáky ve vašich plánech.
{13136}{13198}Drte se vaší moci pevnì, Vévodo.
{13209}{13315}Potøebujete jen poskytnout ostatním malé záblesky moci.
{13334}{13383}U jste kontaktoval ostatní národy,
{13383}{13454}a ony se pøislíbily vaší vìci.
{13479}{13554}S tímto druhem podpory se vám nikdo neodváí oponovat.
{13576}{13594}To bezpochyby.
{13609}{13677}Ale s tebou je zacházeno rozdílnì, pøedpokládám.
{13728}{13767}Za to jsem opravdu vdìènı.
{13824}{13885}Take s plánem z døívìjška nejsou problémy?
{13904}{13952}Jsou zde pøekáky.
{13952}{14005}Ale ty mohou bıt vylouèeny.
{14032}{14117}Jestli tentokrát uspìjeme, trùn bude mùj.
{14661}{14682}Úasné!
{14974}{15014}Vítìzství je mé, Ede.
{15024}{15043}Coe?!
{15056}{15089}Skoro jsem vyhrál.
{15106}{15133}V šermu nemám nikdy štìstí.
{15152}{15197}Pøíštì otestujeme naše schopnosti v jízdì na koni.
{15226}{15246}Ano, pøíštì.
{15264}{15327}Jak typické od Orphera-sama a Eduarda-sama!
{15343}{15380}Oh, tak tady jste vy dva byli!
{15390}{15401}Vıbornì!
{15413}{15473}Koukni! Další Kandidát Strahl!
{15509}{15574}Orphe-san, je tu host, kterı tì chce vidìt.
{15607}{15622}Vidìt mì?
{15716}{15834}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{15997}{16010}Vy jste...
{16130}{16144}Orphe-san...
{16283}{16327}U je to nìjakou dobu,
{16327}{16356}Markızi Shiraiyo.
{16396}{16449}Chci ti nìco øíct. Je to v poøádku?
{16477}{16487}Ano.
{16520}{16571}Mìl bych jít s tebou, Orphe?
{16596}{16637}Ne, to je v poøádku.
{17207}{17233}Kdo byl ten mu?
{17253}{17364}Cítil jsem, e Orphe-san byl pøíšernì šokovanı tím, e ho vidí.
{17393}{17403}Jo.
{17450}{17522}Také jsem cítil jeho hlubokı smutek prosakující skrz.
{17568}{17645}Ten mu je snoubenec Orphovy zesnulé sestry.
{17683}{17755}Orphe, vzdorující svému vnitønímu zármutku,
{17755}{17838}ještì poehnal její svatbì dokud byla šastná,
{17838}{17883}protoe on a jeho sestra si byli tak blízcí.
{17905}{18018}Ona a její snoubenec pro sebe navzájem hodnì znamenali.
{18506}{18549}U jsou to dva roky, e?
{18586}{18628}Stal jsi se vskutku bájeènım mladíkem.
{18666}{18717}Robertina by byla velmi potìšena,
{18717}{18761}kdyby tì teï mohla vidìt.
{18843}{18901}Pøedpokládám, e jsem se znaènì zmìnil.
{18945}{18958}Ne.
{19048}{19112}Pravdìpodobnì tì zajímá, proè jsem tì pøijel navštívit.
{19139}{19156}Ne.
{19488}{19540}Robertina zemøela...
{19540}{19558}kvùli mnì.
{19728}{19754}Je to tak náhlé.
{19776}{19802}Stalo se tvojí rodinì nìco?
{19819}{19894}Ne. Mùj otec si se mnou jednoduše pøeje mluvit.
{19916}{19929}Markız?
{19985}{20037}Moná to zabere nìjakı èas,
{20051}{20142}ale vrátím se pøed návštìvou Jeho Velièenstva.
{20152}{20160}Ano.
{20179}{20211}Vzhledem k souèasnému ovzduší,
{20231}{20281}to pravdìpodobnì není náhoda.
{20365}{20382}Nechávám záleitosti na tobì.
{20600}{20625}Zpùsobil jsi sestøinu smrt?
{20644}{20693}Co to má znamenat?
{20726}{20752}Je to tak, jak jsem øekl.
{20794}{20875}Tenkrát jsem dostal pøíkaz od starosty
{20889}{20922}vyšetøit jistou záleitost.
{20943}{20962}Od starosty?
{20996}{21083}Tajné vyšetøování zamìøené na aristokraty.
{21109}{21230}Byl to pøípad tıkající se budoucnosti tohoto království.
{21279}{21353}Ochotnì jsem souhlasil, e poskytnu své sluby,|i kdy to byl nebezpeènı úkol.
{21377}{21487}Udìlal bych pro Jeho Velièenstvo a pro tuto zemi cokoliv.
{21551}{21601}Ale byl tu následek.
{21601}{21637}Ztratil jsem osobu, která pro mì byla nejdùleitìjší.
{22220}{22272}Bylo to pro mì varování,
{22297}{22337}øíkající, abych u dál nevyšetøoval.
{22384}{22423}I kdy jsem litoval své hlouposti,
{22423}{22511}bylo pøíliš pozdì; u jsem ji ztratil.
{22546}{22576}Nemohl jsem vrátit èas.
{22636}{22760}Ale, stále si nemùu odpustit za to, e jsem ji ztratil.
{22778}{22853}Musím pykat za svùj høích za kadou cenu.
{22935}{23010}Aristokrat, kterého jsem vyšetøoval byl jen pìšák.
{23037}{23116}Byl zde nìkdo další øídící plán.
{23151}{23206}Abych odhalil jeho nièemnost,
{23206}{23249}potøeboval jsem získat dùkazy.
{23279}{23317}Zaèal jsem se tisknout k tomu kruhu.
{23335}{23423}Pravdìpodobnì se domnívali, e jsem neznal jejich zloèiny a plány,
{23423}{23482}a tak já, kterı jsem byl ztracenı v zoufalství,
{23482}{23518}byl snadno vyuitelnı.
{23559}{23647}Zabralo mi to dva roky, abych si zaslouil jejich úplnou dùvìru,
{23674}{23744}nìkdy dokonce zrazování krále.
{23861}{23984}Teï si myslí, e bych pro peníze a vliv udìlal cokoliv.
{24069}{24094}Díky tomu,
{24094}{24137}jsem získal závané dùkazy.
{24161}{24231}Teï mohou bız ztrestáni za své zloèiny.
{24331}{24344}Ale co bude...
{24373}{24408}Co se stane s vámi?
{24438}{24505}Aèkoli to bylo pro sbírání dùkazù,
{24505}{24560}skuteènì jsem zradil království a krále.
{24622}{24744}Jsem spokojen pokud jsem pomstil Robertinu.
{24782}{24801}Markızi...
{24845}{24895}Jsem velmi rád, e jsem s tebou mohl mluvit.
{24989}{25007}Tady.
{25064}{25115}Tohle mi dala Robertina,
{25115}{25166}øíkající, e to bylo na její náhrdelník, kterı jsem jí dal.
{25210}{25225}Moje sestra...
{25434}{25445}Ty...
{25512}{25546}musíš kráèet po poctivé stezce.
{25712}{25722}Alberte!
{25747}{25769}Nechej si to.
{25796}{25838}Do dne, ne se znovu setkáme.
{27411}{27451}Skuteènost tohoto království...
{27490}{27511}Tohoto království...
{27560}{27574}budoucnost.
{27903}{27942}Mìli bychom se vrátit do našich lonic.
{27959}{27978}Ano.
{28015}{28023}Came!
{28045}{28098}To je v poøádku. Jen jsem se píchl do prstu.
{28149}{28172}To je neobvyklé.
{28199}{28251}J-Jsem v poøádku.
{28431}{28443}Came.
{28476}{28570}Nìco... nìco strašného se dìje...
{31604}{31673}-Tváø, kterou nikomu neukáeš.-
{31673}{31752}-Jen mì nech se podívat,-
{31752}{31852}-tak se uklidòuji zatímco tì hledám.-
{31908}{31976}-Unavenı vıraz,-
{31976}{32052}-pøisaju pohled na tebe.-
{32052}{32150}-Chci se tì dotknout tìma rukama. Utáhnu své sevøení.-
{32222}{32285}-Zaraenı, zmatenı,-
{32298}{32371}-mùj pohled je na tebe upøenı.-
{32410}{32477}-Tvou mìnící se tváøí-
{32477}{32556}-se mé srdce tøese.-
{32556}{32629}-Ale jednou pod tou tvojí maskou-
{32629}{32710}-chci ochránit tu zranìnou tváø.-
{32710}{32779}-Nevyhnutelná noc pøichází,-
{32779}{32856}-take tì ádám, pospìš.-
{32856}{32968}-Navìky chci bıt s tebou.-
{32968}{33059}-Pouze do té doby, ne si mì všimneš.
{33449}{33473}Pøíští epizoda
{33508}{33524}Vıstøel.
{33556}{33577}Potenciální zamìstnanec.
{33599}{33621}Rozhodnutí.
{33681}{33732}Teï nejsi sám.
{33760}{33797}TROSKY
