{1}{1}23.976
{9}{244}V naší pøedchozí verzi bylo jméno Robertinina snoubence|pøepsáno. V této epizodì, nicménì, jsou všechny pøípady|"Shiraiyi" nahrazeny "Schreierem". "Schreier" znamená|"vykøiknout" nebo "osoba, která odkrıvá tajemství". |Omlouvám se za náš omyl v pøedchozí epizodì.||Zvláštní dík patøí Antyllus za naznaèení tohoto jména|a Nei za vysvìtlení vıznamu tohoto slova nám.
{263}{397}-Jestlie nastane destrukce,-
{410}{515}-nech všechno neuspoøádanì stát,-
{559}{657}-bez opìtovného pøestavování.-
{798}{884}-Máš minulost, na kterou nemùeš zapomenout?-
{946}{1033}-Máš høích, kterı si pøeješ zapomenout?-
{1101}{1212}-Mùeš jít se svımi zranìními,-
{1235}{1391}-k symbolu, kterı byl nakonec zapomenut.-
{1405}{1529}-Pøed tebou na stezce, kde iješ,-
{1541}{1621}-jsou setkání jenom budoucí rozlouèení.-
{1636}{1699}-Násobí se a násobí se a budou se znovu násobit.-
{1708}{1835}-Pojïme pokraèovat tak, jak jsme to dìlali, s tìmi vyrytımi znaèkami,-
{1852}{1942}-take jednou mùeme bıt pyšní na-
{1997}{2096}-narození se v tomto svìtì.-
{2144}{2242}-Take mùu bıt pyšnı.-
{4137}{4189}TROSKY
{4731}{4737}Ede.
{4772}{4820}Take on se ještì opravdu nevrátil?
{4854}{4902}Kdybych jen šel s ním..
{4917}{4994}Ale byl se snoubencem jeho sestry.
{5013}{5060}Nemyslím si, e by Orpherovi jakkoli ublíil.
{5135}{5191}Markız Schreier ho nenavštívil od té doby, co Robertina zemøela.
{5191}{5268}Pøece jen tak najednou Orpha navštíví?
{5288}{5312}Nìco musí bıt špatnì.
{5328}{5404}Ede, Orphe-san je nepochybnì v poøádku.
{5432}{5489}Ale necítil jsi nìco?
{5556}{5609}I tak musí bıt Orphe-san v poøádku.
{5634}{5652}Je silná osoba.
{5687}{5698}Came.
{6082}{6092}Prosím!
{6111}{6129}Nech a je v bezpeèí!
{6465}{6515}Vrátil jsem se, Otèe.
{6592}{6633}Jsem rád, e tì jsi zpátky, Ludwigu.
{6648}{6671}Copak je?
{6689}{6725}Slyšel jsem, e to bylo naléhavé.
{6750}{6784}Je to ohlednì záleitosti, o které jsme mluvili.
{7154}{7183}Ale tak rychle...
{7199}{7244}Myslel jsem, e by to zabralo nìjakı èas.
{7265}{7343}Ti, kteøí zpùsobili zmatek na tvé zásnubní oslavì
{7343}{7394}to mìli na mysli od zaèátku.
{7414}{7469}Kolik jich mùeme po tomhle zatknout?
{7481}{7511}V této dobì,
{7511}{7592}by obèanské neshody poskytly sousedním zemím "pákovı efekt",
{7611}{7717}zvláštì jestlie je konflikt zvnitøku Královského Paláce.
{7742}{7759}Ludwigu.
{7844}{7935}Jeho Velièenstvo nezamıšlí zvelièovat tento problém.
{7957}{8056}Chápu, e je to pro dobro království.
{8086}{8171}Ale jestlie lapneme jenom špeha a necháme hlavu uniknout, take mluvit,
{8171}{8209}jako by bylo zbyteèné.
{8238}{8304}Tahle hrozba by mohla nastat znovu v jakoukoli dobu.
{8346}{8388}Host pøichází.
{8424}{8436}Host?
{8492}{8562}Ten, kterı nám pøinese rozhodující zprávu.
{8588}{8615}Tajné vyšetøování?
{8635}{8639}Chápu.
{8676}{8772}S dùkazem mohou bıt tyto vnitøní konflikty snadno rozluštìny.
{8782}{8867}Ta osoba zde doruèí dùkaz dnes veèer.
{8890}{8953}Pak naše království koneènì mùe poznat mír.
{8972}{9063} A pak mùeme prosit Jeho Velièenstvo a starosty.
{9105}{9126}Dobrı manévr.
{9458}{9485}Kde je pasaér?
{9501}{9532}C-Co máš za problém?
{9540}{9576}Nebyli v tomhle dopravním prostøedku dva mui?
{9590}{9638}N-Ne, byl tak jen jeden mu.
{9651}{9713}Soudì podle jeho odìvu, øekl bych, e to byl mladı aristokrat.
{9730}{9790}Byl poslán do nemocnice, ale bylo nejisté zda bude ít.
{9798}{9814}Jeden mu?
{9879}{9926}Øidiè musel bıt Markız Schreier.
{9948}{10001}Ale, kde je Orphe, kdo s ním byl?
{10221}{10256}Úsvit?
{10281}{10388}Nebo temnota zase jednou zahalila tuto zemi?
{10446}{10487}Co je, Otèe?
{10507}{10574}Zdá se, e selhal.
{10848}{10910}Co je to? Zdá se, e je dnes spousta nepøítomnıch.
{10931}{10997}Ludwig nám oznámil svou nepøítomnost.
{11014}{11037}Kde jsou ti další dva?
{11051}{11061}Um...
{11082}{11162}Orphe a Ed se necítili dobøe a odpoèívají ve svıch pokojích.
{11181}{11228}Oh? Jak neobvyklé.
{11278}{11335}Pak tedy pokraèujme v naší lekci.
{11506}{11557}Nedomnívám se, e budou oklamáni na dlouho.
{11575}{11636}Všechno co mùeme dìlat je na èas se zastavit,
{11663}{11698}dokud se nevrátí.
{11728}{11741}Came?
{11741}{11798}A-Ano. To nic.
{11823}{11933}Jen nìkdy jsou oèi Beruzeho-sensei strašnì dìsivé.
{11949}{11963}Dìsivé?
{12099}{12135}Ede! Vrátil jsi se!
{12150}{12168}Kde je Orphe-san?
{12204}{12212}Nikde.
{12250}{12259}Ede.
{12289}{12324}Není nikde k nalezení.
{12345}{12369}Zatracenì!
{12396}{12406}Ede...
{12448}{12503}Automobil Makrıze Schreiera se dostal do nehody,
{12518}{12560}ale Orphe v tom dopravním prostøedku nebyl.
{12622}{12685}Kde jsi, Orphe?
{13271}{13288}Tohle místo je...
{13705}{13715}Sestro?
{13735}{13764}Ty jsi taková hrstka,
{13793}{13829}pøijít celou cestu a sem.
{13866}{13897}Kde je tohle místo?
{13933}{13979}Jsem...?
{14037}{14089}Bì zpátky. Na tu stranu.
{14121}{14137}Sestro?
{14162}{14251}Ještì není tvùj èas.
{14266}{14317}Pojï zpátky se mnou, Sestro.
{14410}{14446}Øekneš mu to za mì?
{14476}{14539}Øekni mu, aby pokraèoval v ití a byl šastnı.
{14552}{14571}Øíct to jemu?
{14606}{14655}Stejnì tak ty, Orphe.
{14680}{14724}Neztrácej se ve smutku.
{14753}{14766}ij,
{14791}{14817}a buï šastnı.
{14963}{14972}Sestro!
{14999}{15105}Stále jsou ti, kteøí oèekávají tvùj návrat.
{16270}{16285}Já...
{16757}{16786}Koneènì jsi se probudil.
{16991}{17113}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{17155}{17189}Co se to k èertu dìje?
{17206}{17254}Podporoval jsem Schreiera.
{17278}{17327}Myslel jsem si, e by mohl bıt uiteènı.
{17327}{17365}Ale on se ukázal bıt zrádcem!
{17376}{17419}Zdá se, e vás oklamal.
{17419}{17476}Slídil na našich záleitostech úplnì celou dobu.
{17492}{17569}U jsem pøijal opatøení, pøedtím ne by bylo moc pozdì.
{17586}{17632}Jsi si jistı, e to teï bude bezpeèné?
{17663}{17709}Mìlo by bıt nemoné uniknout té "nehodì" ivı.
{17709}{17773}Ale musíme si bıt jisti, e je mrtvı!
{17793}{17853}Koneènì jsme dokonèili všechny pøípravy.
{17865}{17933}Poté co zavradíme mého bratra, budu...
{17958}{17973}Vévodo.
{18022}{18071}Nesmíte to nechat tak snadno vyklouznout z vašich rtù.
{18145}{18192}Jen nechte všechno na mnì.
{18209}{18268}Nezradím vaši dùvìru, Vévodo.
{18293}{18328}Vévodo, všechno co potøebujete udìlat,
{18328}{18417}je trpìlivì èekat na den, kdy dosáhnete trùnu.
{18437}{18447}Ano.
{18468}{18516}Pak to nechávám na tobì, Beruze.
{18534}{18552}Ano.
{19115}{19164}Jak je na tom Markız Schreier?
{19175}{19221}Objevili jsme, do které nemocnice byl poslán,
{19221}{19257}ale u byl pøemístìn na jiné místo.
{19274}{19301}Neznáme jeho souèasné umístìní.
{19374}{19434}Budeme postupovat, jak jsme plánovali.
{19448}{19459}Rozumím.
{19487}{19576}Jen, nemluví se o tom, e by byl nalezen nìjakı mrtvı student Akademie.
{19629}{19644}Aha...
{19666}{19675}Huh?
{19730}{19767}Buï na strái.
{19969}{20007}Lui, vítej zpátky.
{20017}{20031}Díkybohu.
{20048}{20076}Co se stalo?
{20368}{20429}Markız Schreier a Orpherus?
{20452}{20486}Jak zvláštní pro nì bıt obeznámení.
{20504}{20510}Lui...
{20532}{20578}Take, co checete abych udìlal?
{20603}{20681}Nemyslím si, e mùeme pokraèovat ve skrıvání tohoto pøed Akademií.
{20696}{20781}Ale protoe nevíme co se opravdus stalo,
{20781}{20811}nemùeme podniknout ádnou akci.
{20929}{20950}Jen ho nechte bıt.
{20966}{20992}U není dítì.
{21013}{21023}Lui!
{21056}{21138}Kdyby nemohl vytáhnout sám sebe ze zaèínajících plamenù,
{21138}{21194}nikdy by nic neudìlal.
{21292}{21355}Kromì toho, bylo by problematické teï udìlt jakıkoli pohyb.
{21379}{21440}Jen by to poslouilo jako signál našemu nepøíteli.
{21456}{21513}Víš nìco o tom, co se stalo?
{21738}{21750}Lui!
{21977}{22054}Máš odvahu èelit pravdì?
{22094}{22140}Jednou ti to øeknu a u nebude cesty zpìt.
{22173}{22253}Jestli chceš nebo ne, je do toho zapojená|váná zodpovìdnost a povinnost.
{22330}{22438}Nebudeš mít na vıbìr kráèet po stezce, která|se støetává se zájmem tvıch pøátel.
{22473}{22538}I tak to chceš stále vìdìt?
{22819}{22903}Chci ivit království bez nejistoty, kde mùou bıt všichni šastní.
{22921}{22984}Tahle cesta není jednoduchá,
{23029}{23081}ale já se nebojím.
{23103}{23165}I kdybych byl zranìn a sraen,
{23194}{23210}stále budu...
{23430}{23486}Kdy jsem poprvé vstoupil do této Akademie,
{23486}{23560}nepokoušel jsem se stát Strahlem.
{23574}{23584}To je...
{23665}{23730}Nevím, kdy to zaèalo.
{23730}{23809}Pøedtím, ne jsem to poznal jsem zaèal cítit nadìji,
{23837}{23922}e by mohla bıt legrace vykonávat s vámi nìco kluci.
{23941}{23951}Ede...
{23994}{24042}Vím, e to co chci je moná mimo to, co mùu udìlat,
{24060}{24136}a není to jako bych mìl velké ideály jako Orphe.
{24167}{24272}I tak chci kráèet po cestì, kterou jsem si sám vydládil.
{24327}{24406}Teï se zaèínáš podobat Kandidátovi Strahl!
{24431}{24480}Ale zvládneš to?
{24493}{24607}Ano, a vím, e Orphe bude stejnı.
{24670}{24683}Vıbornì.
{24739}{24824}Rozumím. Cítím to stejnì.
{24832}{24862}Já také.
{24862}{24882}Udìlám cokoli, abych pomohl.
{24980}{25009}Ještì by se's nemìl pohybovat.
{25030}{25114}Zatím jsem tì ošetøil, ale nejsem doktor.
{25129}{25152}Nemùu nic zaruèit.
{25168}{25177}Vy...
{25208}{25257}Co... já...
{25304}{25331}Øíkal jsem ti, nehıbej se!
{25415}{25461}Vysvìtlím situaci podle mého nejlepšího vìdomí.
{25486}{25598}Byl jsem pìknì šokovanı, kdy jsem tì vytáhl z øeky.
{26226}{26240}To je váné.
{26353}{26379}Bude to bolet.
{26525}{26660}Tento pokus o ivot Kandidáta Strahl z Akademie|Rosenstolz je docela váná záleitost.
{26689}{26707}Víš, kdo to udìlal?
{26730}{26766}Byla tma, take jsem nemohl vidìt jeho tváø.
{26781}{26797}A ádnı motiv?
{26898}{26935}Je to to, co hledáš?
{27008}{27045}Drel jsi to tak pevnì.
{27080}{27104}Pravdìpodobnì je to pìknì dùleité, huh?
{27128}{27138}Ano.
{27266}{27335}Jestli jsem byl cílem, pak to musí bıt...
{27359}{27391}Hej! Ještì ne!
{27410}{27458}Je tu nìco, co si musím potvrdit.
{27472}{27537}Poèkej, co chceš vìdìt?
{27552}{27620}U si nepøeju vás dál obtìovat.
{27635}{27647}Já...
{27671}{27733}U jsi mì obtìoval.
{27763}{27819}Kromì toho, jsem na problémy zvyklı.
{27868}{27930}Kdo opravdu jste?
{27953}{27993}V poøádku, jen mluvme.
{28020}{28061}Jsem docela uiteènı, víš.
{28172}{28195}Markız Schreier, on...
{28221}{28301}Nepøítel objevil jeho úmysly a uèinil opatøení, aby ho zlikvidoval.
{28319}{28339}Co se mu tedy stalo?
{28384}{28413}Je stále naivu.
{28743}{28795}Je pro nás rozhodujícím svìdkem.
{28813}{28916}Nyní je umístìn v soukromém, dobøe-støeeném prostoru.
{28934}{28965}Je pro nì nemoné pokusit se o cokoli jiného.
{28991}{29054}Ne, i kdyby udìlali další akci,
{29054}{29104}pøineslo by nám to spíše úspìch.
{29127}{29169}Nepøítel není tak hloupı, nicménì.
{29189}{29268}Pak se o to nemusíme obávat.
{29289}{29333}Ale on nebyl s Orphem-san?
{29385}{29434}Orpherus nebyl pasaérem toho dopravního prostøedku.
{29453}{29560}Ale, vzhledem k tomu, e se Orpherus nevrátil|od té doby, co se rozdìlili pøed tou "nehodou",
{29560}{29584}se domnívám, e se mu nìco muselo stát.
{29648}{29722}Kromì toho, nemyslíš si, e je to všechno zvláštní?
{29740}{29755}Co je zvláštní?
{29787}{29819}Nepøítel jedná spìšnì.
{29843}{29974}Setkání Markıze Schreiera s Orpherem nemìlo bıt pøedpokládané.
{30006}{30061}Nicménì, nepøítel to okamitì objevil.
{30100}{30113}To znamená...
{30134}{30197}Nepøítel je uvnitø této Akademie?
{30262}{30299}To je jediná monost.
{30398}{30423}Albert?
{30444}{30486}Jestli je to, co jsi o nìm øíkal pravda,
{30486}{30521}pak to pravdìpodobnì nebyla nehoda.
{30667}{30693}To je døív, ne jsem si myslel!
{30708}{30719}Isaacu!
{31842}{31912}-Tváø, kterou nikomu neukáeš.-
{31912}{31992}-Jen mì nech se podívat,-
{31992}{32091}-tak se uklidòuji zatímco tì hledám.-
{32148}{32215}-Unavenı vıraz,-
{32215}{32290}-pøisaju pohled na tebe.-
{32290}{32394}-Chci se tì dotknout tìma rukama. Utáhnu své sevøení.-
{32457}{32525}-Zaraenı, zmatenı,-
{32535}{32607}-mùj pohled je na tebe upøenı.-
{32651}{32717}-Tvou mìnící se tváøí-
{32717}{32792}-se mé srdce tøese.-
{32792}{32866}-Ale jednou pod tou tvojí maskou-
{32866}{32947}-chci ochránit tu zranìnou tváø.-
{32947}{33020}-Nevyhnutelná noc pøichází,-
{33020}{33098}-take tì ádám, pospìš.-
{33098}{33209}-Navìky chci bıt s tebou.-
{33209}{33307}-Pouze do té doby, ne si mì všimneš.-
{33685}{33710}Pøíští epizoda
{33744}{33755}Bolest.
{33789}{33810}Pravda.
{33845}{33867}Shledání.
{33922}{33971}Teï nejsi sám.
{34000}{34032}MYŠLENKA
