{1}{1}23.976
{26}{153}-Jestlie nastane destrukce,-
{168}{274}-nech všechno neuspoøádanì stát,-
{323}{409}-bez opìtovného pøestavování.-
{556}{644}-Máš minulost, na kterou nemùeš zapomenout?-
{709}{793}-Máš høích, kterı si pøeješ zapomenout?-
{859}{973}-Mùeš jít se svımi zranìními,-
{995}{1145}-k symbolu, kterı byl nakonec zapomenut.-
{1162}{1290}-Pøed tebou na stezce, kde iješ,-
{1302}{1381}-jsou setkání jenom budoucí rozlouèení.-
{1391}{1454}-Násobí se a násobí se a budou se znovu násobit.-
{1464}{1593}-Pojïme pokraèovat tak, jak jsme to dìlali, s tìmi vyrytımi znaèkami,-
{1604}{1700}-take jednou mùeme bıt pyšní na-
{1761}{1855}-narození se v tomto svìtì.-
{1903}{2001}-Take mùu bıt pyšnı.-
{2609}{2664}Jestli je nepøítel v této Akademii,
{2681}{2717}kdo by to mohl bıt?
{2738}{2792}Nemáme èas na pátrání.
{2807}{2817}Ale...
{2841}{2851}Lui.
{2877}{2892}Nicménì,
{2986}{3098}máme perfektní šanci vykouøit ven našeho protivníka.
{3098}{3156}MYŠLENKA
{3445}{3467}Zdá se, e to vzdali.
{3513}{3530}Ještì iješ?
{3650}{3722}Kdo jsi, opravdu?
{3745}{3779}Jen skromnı spisovatel.
{3792}{3813}Nechme to tak.
{4481}{4584}Co to dìlám?
{5031}{5145}Nemohl jsem ani zachránit Alberta.
{5401}{5438}Take, co teï?
{5524}{5623}Budeš se tam krèit a truchlit po zbytek svého ivota?
{5642}{5736}Nebo pøemıšlíš o útìku z ohavnosti toho všeho?
{5858}{5939}Zabírá ti tohle všechno rozdrcení tvıch snù?
{5956}{5995}Jestli ano, jsem hodnì zklamanı.
{6016}{6029}Chápeš?
{6049}{6100}Všichni mají ideály,
{6100}{6181}ale jen nìkolik je mùe pøemìnit na skuteènost.
{6203}{6277}Mùeš to vyhrát nebo to chceš vzdát v pùli cesty?
{6357}{6418}Jedinì ty o tom mùeš rozhodnout.
{7302}{7411}Nechci vzdát ty ideály v mém srdci,
{7462}{7488}ne jestli jsou tu pro to...
{7791}{7805}To je...
{7850}{7863}Co je?
{7958}{7967}Orphe?
{8015}{8032}Alberte...
{8144}{8174}Je to nebezpeèné.
{8174}{8198}Nemusíš mì dál doprovázet-
{8246}{8290}U jsem došel tak daleko.
{8290}{8321}Moná tì taky budu následovat do konce.
{8349}{8367}Opravdu.
{8388}{8405}Unikli.
{8434}{8497}Bylo to jako by oèekávali naše jednání.
{8497}{8543}Pokraèujeme v pronásledování, ale...
{8621}{8655}To je v poøádku.
{8655}{8697}Pùvodní mise je dùleitìjší.
{8711}{8736}A-Ano, Pane.
{9118}{9186}Pøál jsem si za nìj vidìt svìtlo.
{9202}{9221}Vaše Velièenstvo.
{9243}{9261}Rozumím.
{9766}{9842}Vítejte v Akademii Rosenstolz,
{9858}{9873}Vaše Velièenstvo.
{9952}{9997}Teï prosím pojïte tudy.
{10461}{10541}Kráèet takto skrz Akademii s tebou
{10541}{10589}je jako cestování zpìt v èase.
{10589}{10644}V té dobì, Vaše Velièenstvo,
{10644}{10730}jsi byl docela neøád a mìl jsi ve zvyku pøíšernì šokovat uèitele.
{10748}{10776}Opravdu?
{11189}{11340}Jestli je trávením èasu zde je srdce Jeho Velièenstva|i nepatrnì utìšeno, pak jsem rád.
{11373}{11437}Mìl bych se svım bratrem více mluvit.
{11457}{11503}To je mé jediné zklamání.
{11592}{11652}Všechna nadìje svìta leí zde.
{11889}{11979}Vaše Velièenstvo, nadìje je zde stále naplnìna a po okraj.
{11990}{12078}Není to to, co udrí budoucnost tohoto Království?
{12113}{12171}Pøesnì jak jsi øekl, zpátky v ten den.
{12259}{12279}Ano.
{12476}{12529}U je to dlouho, Vaše Velièenstvo.
{12557}{12628}Vítejte v Akademii Rosenstolz.
{12643}{12716}Ludwig z domácnosti Markıze Liechtensteina, e?
{12731}{12755}Vypadáš dobøe.
{12769}{12822}Ludwigu, jsi sám?
{12841}{12880}Kde jsou ostatní Kandidáti Strahl?
{12880}{12926}Já nejsem sám.
{12946}{13055}Ostatní uskuteèòují své pøiøazené úlohy.
{13360}{13381}Támhle!
{13381}{13409}Take pøišli!
{13423}{13482}Teï opatrnì. Jsou to všichni hroznì nebezpeèní lidé.
{13495}{13510}Já vím.
{13526}{13593}I tak, je to to, co musíme udìlat.
{13605}{13617}Ano.
{13633}{13652}Nech nás pokraèovat.
{13870}{13975}A semhle chodí studenti relaxovat.
{14012}{14036}Skuteènì krásné.
{15041}{15163}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{15334}{15359}Vezmìte Jeho Velièenstvo do bezpeèí.
{15518}{15539}To bylo tìsné.
{15555}{15566}Díkybohu.
{15661}{15742}Myslel jsem, e jsem ti øekl, abys drel |Jeho Velièenstvo spolehlivì od všech hrozeb. 
{15761}{15780}Velice se omlouváme.
{15797}{15844}To proto jsi byl po jeho boku!
{15908}{15992}Nedovolím nikomu znesvìtit tuto Akademii.
{16302}{16315}Orphe!
{16359}{16373}Ahoj, Ede.
{16373}{16392}Ahoj, všichni.
{16505}{16531}Orphe, jsi v poøádku!
{16541}{16555}Ede.
{16609}{16642}Ušetøete si to slzavé shledání na pozdìji.
{16656}{16696}Jak øíká.
{18613}{18627}To jsi ty.
{18776}{18815}Pøišel jsi sem navzdory tomu zranìní?
{18833}{18861}Take jste to nakonec byl vy.
{18921}{18971}Proè, Beruze-sensei?
{18986}{18997}Proè?
{19013}{19081}I teï se mì ptáš proè?
{19100}{19137}Jsi opravdu naivní.
{19167}{19284}Domnívám se, e mé jméno bylo ve zprávì Markıze Schreiera?
{19311}{19325}Vy...
{19416}{19606}Zajímá mì jestli vùbec rozumíš hodnotì toho,|co jsi obìtoval jako své lidské právo.
{19675}{19730}Ne, vùbec nerozumíš.
{19764}{19793}Byla ti udìlena jasná budoucnost
{19809}{19848}tvımi aristokratickımi tradicemi.
{19885}{19938}Mùj otec byl šlechtic.
{19982}{20057}Kdyby mì jen uznával,
{20057}{20119}byl bych pøijat na Akademii Rosenstolz,
{20139}{20217}vyškolenı jako Kandidát Strahl,
{20233}{20304}a jednoho dne bych pomáhal øídit toto Království jako státník.
{20352}{20402}Ale skuteènost nevyšla tímto zpùsobem.
{20438}{20490}Mùj otec mì opustil.
{20523}{20641}Pøesnı opak toho, co se stalo tvému spoleèníkovi Eduardovi-kun.
{20730}{20822}Beruze-sensei, tvé krytí bylo odfouknuto.
{20822}{20885}Vévoda by teï také mìl bıt ve vazbì.
{20905}{20962}Jako bych se staral, co se stane jemu.
{21005}{21042}Nikdo z vás by nemohl rozumnìt.
{21068}{21204}Bolest z potøeby nìèeho pøed vašima oèima,|ale nikdy to nebıt schopnı získat.
{21231}{21252}Nenávist.
{21350}{21415}Tentokrát jsem povinen poslat tì na sestøinu stranu.
{21432}{21545}Tak se nebudeš moci dívat jak bude toto Království kopnuto do kolen.
{21579}{21594}Jak o tom víte?
{21910}{21987}Mám pochopení pro to, èím jste prošel.
{22065}{22186}Ale obìtování tohoto Království kvùli pomstì,
{22202}{22223}to nepøehlédnu!
{22593}{22605}Nesmíte!
{22678}{22684}Came!
{22780}{22834}To bylo nezodpovìdné, zpropadenì.
{22834}{22863}Dìkuji.
{23063}{23077}Orphe.
{23162}{23179}Vítej zpátky.
{23229}{23252}Jsem doma.
{23441}{23470}V-Vy všichni...
{24324}{24366}Boe, byla to jistì naprostá senzace, do které jste byli vtaeni.
{24405}{24477}Kdy jste pøedvídali tento prùbìh událostí,
{24477}{24519}mìli jste to se mnou projednat.
{24528}{24599}To protoe jsme si nebyli jistí identitou nepøítele.
{24626}{24648}Omlouvám se.
{24666}{24765}Umístil jsem vás všechny do nebezpeèí svou nerozhodností.
{24779}{24825}Ne, Vaše Velièenstvo.
{24825}{24847}Chápeme, jak jste se cítil.
{24942}{24980}Vidíte všichni, gentlemani?
{25005}{25032}Toto je skuteènost.
{25073}{25117}Pravá tváø reality je
{25117}{25145}vzájemné zabíjení.
{25145}{25183}vzájemné bojování.
{25183}{25210}Skuteènost...
{25229}{25278}Uspokojení všech,
{25278}{25379}i s moudrımi rozhodnutími a nejcílevìdomìjší horlivostí,
{25379}{25413}je nemoné dosáhnout.
{25428}{25475}Ne všichni budou šastní.
{25492}{25522}Vaše Velièenstvo...
{25561}{25663}Není to jen mùj bratr, kdo nesouhlasí s mım politickım postojem.
{25679}{25697}Vaše Velièenstvo.
{25728}{25783}Vykoøenìní všeho neštìstí,
{25840}{25883}zmírnìní všeho lidského utrpení
{25927}{25980}pøedtím, ne nás dohoní zoufalství,
{25980}{26026}zdá se blízko nemonému.
{26058}{26165}Ale nemùeme opominout horlivost a odvahu zapojenou do pokroku-
{26224}{26355}Kdy nemùeme provést toto, bude to znamenat, e jsme prohráli.
{26548}{26637}Jen protentokrát souhlasím s Orphem.
{26663}{26673}Lui.
{26896}{26960}Cesta je dlouhá.
{26984}{27037}Od tohoto dne dále kráèej vpøed.
{27065}{27076}Ano, Pane.
{27321}{27375}Do pøíštì, chlapci.
{28054}{28069}Orphe.
{28096}{28153}Všemu je konec.
{28203}{28218}Opravdu.
{28267}{28378}Vìdìl jsi, e jsi byl v nebezpeèí, e?
{28460}{28530}Nestaral jsi se, e by to mohlo znamenat tvou smrt, e?
{28662}{28714}Má sestra mì poádala, abych ti nìco øekl.
{28869}{28954}Prosím, pøipus si odpuštìní.
{28989}{29054}To je pøání mé sestry.
{29148}{29179}Robertino...
{29545}{29638}Opravdu se cítím šastnı, e jsem vstoupil na tuto Akademii.
{30080}{30101}Já také.
{31603}{31674}-Tváø, kterou nikomu neukáeš.-
{31674}{31749}-Jen mì nech se podívat,-
{31749}{31854}-tak se uklidòuji zatímco tì hledám.-
{31907}{31976}-Unavenı vıraz,-
{31976}{32050}-pøisaju pohled na tebe.-
{32050}{32153}-Chci se tì dotknout tìma rukama. Utáhnu své sevøení.-
{32224}{32281}-Zaraenı, zmatenı,-
{32292}{32373}-mùj pohled je na tebe upøenı.-
{32410}{32476}-Tvou mìnící se tváøí-
{32476}{32554}-se mé srdce tøese.-
{32554}{32625}-Ale jednou pod tou tvojí maskou-
{32625}{32710}-chci ochránit tu zranìnou tváø.-
{32710}{32781}-Nevyhnutelná noc pøichází,-
{32781}{32858}-take tì ádám, pospìš.-
{32858}{32969}-Navìky chci bıt s tebou.-
{32969}{33061}-Pouze do té doby, ne si mì všimneš.-
{33069}{33328}...a máme tu konec, dìkuji všem, kteøí to zvládli a do tohoto dílu...|...avšak ještì není konec...|...hurá na 2. øadu...||Pro pøipomínky se ozvìte na: www.mycolorfullife.blog.cz|Za TaSHee's Gang, WelW(etkaAa)-hime
