{535}{585}Zlatı prach! Zlato!|Je to zlato!
{589}{651}Ruky preè!|Je to vlastníctvo spoloènosti!
{655}{737}Ticho.|Náš host tu ešte stále je.
{879}{950}Sen, stojíš v ceste nášmu hosovi.|Vyjdi a otvor dvere.
{953}{1013}Otvor hlavnú bránu!|Odchádza!
{1655}{1753}Sen! Bola si fantastická!|Urobila si nám obrovskú slubu!
{1771}{1833}To je pre Boha Riek typické.
{1836}{1875}Vezmite si príklad zo Sen.
{1889}{1937}Dnes je sake na úèet podniku!
{1949}{2014}A teraz je èas na to, aby ste vrátili všetko zlato,|ktoré ste zobrali!
{2341}{2388}Dáš si?|Pripravila som to sama.
{2401}{2435}Ïakujem ti.
{2437}{2489}Ó, Boe.
{2551}{2587}Nevidela som Hakua.
{2589}{2631}Nie u zase Haku.
{2653}{2711}Niekedy sa proste vyparí.
{2721}{2812}Povráva sa, e ho Yubaba|núti robi zlé veci.
{2815}{2835}Skutoène...
{2837}{2872}Zhasni, Lin.
{2874}{2899}Jasné.
{3503}{3567}Tam je mesto.|Ale vyzerá ako oceán...
{3573}{3642}A èo si èakala|po takom dadi.
{3687}{3783}Prisahám, e jedného dòa pôjdem do toho mesta.|Odídem odtia¾to.
{4347}{4401}Èo sa deje?
{5111}{5147}Zlato!
{5215}{5289}Kto si?|Nie si zákazník.
{5292}{5331}Tu nemáš èo robi!
{5491}{5566}Hej! To je zlato, zlato!|To je pre mòa?
{5693}{5748}Vieš vyrába zlato?
{5883}{5904}Daj mi to!
{6103}{6143}Kto je tam?
{6171}{6225}Je èas ís spa.
{6311}{6389}Hej šéfe. Som hladnı.
{6392}{6420}Nenaranec.
{6423}{6444}Ten hlas...
{6446}{6491}Tu máš, dobre zaplatím.
{6509}{6573}Som zákazník a chcem kúpe¾!
{6576}{6614}Všetci vstávajte!
{6747}{6827}Mami, oci, Boh Riek|mi dal tento koláè.
{6829}{6899}Som si istá, e ak ho zjete,|zmeníte sa spä na ¾udí.
{6997}{7045}Oci, mami, kde ste?
{7055}{7084}Oci!
{7351}{7379}Bol to len zlı sen.
{7415}{7451}Lin...?
{7543}{7583}Kde sú všetci?
{7739}{7805}Vau... skutoène sa|to premenilo na oceán !
{7933}{8004}Odtia¾to vidím,|kde sú mama a ocko
{8093}{8145}Kamaji u zakúril?
{8148}{8198}Spala som a tak dlho?
{8277}{8348}Zákazník èaká.|Pohnite si!
{8351}{8447}Prineste všetko, èo máme.|Aj zbytky!
{8495}{8517}Sen!
{8520}{8543}Lin!
{8549}{8614}Práve som a išla zobudi.|Pozri!
{8621}{8674}Skutoèné zlato.|Dal mi skutoèné zlato.
{8683}{8735}Tento hos je skutoène vyššia trieda.
{8737}{8792}Nech sa páèi, pane, vyskúšajte toto!
{8794}{8852}Chutí to vynikajúco!
{8891}{8953}Dajte nám troška zlata!
{8983}{8999}Ste fantastickı!
{9001}{9081}Som hladnı, doneste mi všetko!
{9098}{9155}Nech sa páèi, pane!
{9193}{9224}Ten hos...
{9231}{9312}Poï, Sen, Yubaba ešte spí.|Teraz máme šancu.
{9323}{9367}Musím sa pozdravi s Kamajim.
{9381}{9434}To by dobre nedopadlo.
{9437}{9491}Má mizernú náladu,|lebo ho zobudili.
{9493}{9537}Poïme spä pre ïalšie, Lin.
{10142}{10222}Èo ak nespoznám|mojich rodièov?
{10241}{10308}Dúfam, e ocko|ve¾mi nepribral.
{10985}{11021}To je ten drak, ktorého som videla predtım.
{11035}{11069}Prichádza sem!
{11135}{11167}Èo sú zaè?|Vtáky nie.
{11440}{11514}Bráò sa, Haku!|Tadia¾to.
{11517}{11536}Haku!
{11553}{11579}Haku!
{12015}{12071}No toto...|Je to len papier...
{12749}{12801}Haku?|Si to ty, však?
{12949}{13029}Si zranenı?|Tie papierové vtáky zmizli.
{13032}{13062}U si v bezpeèí.
{13379}{13420}Ide za Yubabou...
{13435}{13493}Ó, nie!|Zomrie !
{13683}{13787}Najbohatší mu|na celom svete.
{13797}{13890}A ten mu sem|prišiel osobne.
{13920}{13970}Vitajte!
{13973}{14028}Èas zaèa prosi o prepitné.|Zaènite prosi.
{14031}{14101}Nech sa páèi, pane! Tadia¾to!
{14104}{14170}Teraz proste.
{14173}{14213}Teraz proste.
{14216}{14263}Prosím, dajte nám nieèo.
{14280}{14357}Prosím, aj sem nieèo hoïte!
{14453}{14488}Hej, èo to robíš?
{14490}{14514}Idem hore.
{14517}{14564}Nie, nejdeš.|Èo je toto?
{14581}{14610}To je krv!
{14705}{14759}Pohyb, pohyb.|Nechajte nášho hos prejs.
{14797}{14845}Ïakujem ti za to, e si mi predtım pomohol.
{14849}{14908}Nestoj tam len tak...
{15433}{15473}Nechcem to.|Nepotrebujem to.
{15544}{15600}Ponáh¾am sa, ospravedlòte ma, prosím
{15878}{15947}Ticho! Utíšte sa!
{15964}{16004}Spä, vráte sa!
{16013}{16064}Prosím, osprevedlòte jej spôsoby.
{16066}{16152}A navyše to dievèa je len èlovek|a je tu nová...
{16209}{16253}Neusmievaj sa tak.
{16256}{16276}Ten poh¾ad som u videl.
{16278}{16314}Preèo nikdy...
{16432}{16488}Zjedol ich!
{18573}{18609}Yubaba?
{20349}{20412}Sme v peknej kaši.
{20428}{20478}V skutoènosti je to mu Bez Tváre.
{20482}{20528}To je správne mu Bez Tváre!
{20536}{20604}Vaša chamtivos ho privolala.
{20617}{20696}Neurob iadnu hlúpos,|kım sa nerátim.
{20709}{20768}Pozri na koberec - akı neporiadok!
{20770}{20824}Zober Hakua odtia¾to.
{20827}{20871}Je pre mòa nepouite¾nı.
{21411}{21483}U opä si spinkal si ved¾a kolísky?
{21579}{21681}Je mi to ¾úto.|Spinkal si ako dobré bábätko.
{21684}{21752}Baba má ešte robotu.
{21822}{21888}Ešte spinkaj.|Dobré bábätko.
{22569}{22607}Au, rıchlo preè!
{22617}{22662}Ïakujem ti za pomoc.
{22665}{22744}Ale ve¾mi sa ponáhlam.|Prosím nechaj ma odís.
{22747}{22803}Prišla si, aby si ma urobila chorım?
{22816}{22876}Vonku sú zlé baktérie. Ve¾mi zlé.
{22899}{22991}Ja som èlovek.|Predtım si asi iadneho ešte nevidel.
{22997}{23053}Vonku ochorieš.
{23056}{23104}Zostaò tu a hraj sa so mnou.
{23109}{23147}Si chorı?
{23150}{23218}Som tu, pretoe|by som vonku ochorel.
{23221}{23280}Len zo stáleho ostávania tu ochorieš!
{23283}{23373}Vieš, niekto, o koho sa ve¾mi bojím,|je ako zranenı.
{23376}{23416}A preto musím teraz odís.
{23418}{23449}Prosím pusti moju ruku!
{23456}{23496}Ak odídeš, zaènem plaka.
{23498}{23581}A ak zaènem plaka, príde Baba|a zabije a.
{23584}{23624}Zlomím tvoju malú ruku.
{23626}{23655}To bolí!
{23657}{23717}Prosím, vrátim sa|a zahrám sa s tebou neskôr.
{23721}{23759}Nie. Chcem sa hra teraz!
{23856}{23908}To je krv! Chápeš?|Je to krv!
{24185}{24228}Haku!
{24230}{24280}Prestaòte, choïte preè!|Heš, heš!
{24283}{24307}Haku! Si to ty?
{24310}{24346}Vydr!
{24357}{24409}Buïte ticho!|Haku !
{24517}{24571}Šic, šic, choï preè.
{24636}{24668}Ale nie!
{25029}{25072}Nebojím sa krvi!
{25074}{25119}Budem plaka, ak sa so mnou nebudeš hra!
{25121}{25167}Prosím, buï dobrı chlapec a poèkaj.
{25177}{25249}Ak sa so mnou nezahráš,|budem plaka...
{25297}{25332}Prosím, poèkaj!
{25334}{25411}Èo je to za hluk.|Dole to vrie.
{25444}{25512}Si malá hrudka masla,|však?
{25689}{25744}Myslím, e som ešte stále trochu priesvitná.
{25746}{25764}Baba
{25781}{25880}Zlatko, nemôeš mi ani porozpráva|o svojej vlastnej mame?
{26076}{26146}Tu máš, vezmi si,|trocha a to uvo¾ní.
{26149}{26167}A teraz uvidím...
{26176}{26222}Na èo a mám premeni?
{26656}{26721}Toto je naše malé tajomstvo.|Nepovedz to nikomu.
{26724}{26771}Lebo ti odtrhnem ústa.
{26809}{26837}Kto ste?
{26841}{26900}Yubabiné dvojèa.
{26902}{26998}Ïakujem vïaka teba mám dobre poznám toto miesto,|teší ma to.
{27001}{27041}A teraz spä k drakovi.
{27047}{27104}Èo chceš urobi s Hakuom?|Je váne zranenı.
{27113}{27185}Tento drak je zlodej,|lokaj mojej sestry.
{27188}{27264}Ukradol mi vzácnu peèa.
{27266}{27332}Haku by nikdy...|Je takı milı.
{27345}{27432}Všetci draci sú milí.|Milí a hlúpi.
{27434}{27543}Horlivo sa uèí|pouíva mágiu od mojej sestry.
{27553}{27644}Tento chlapec tu urobí všetko,|èo tá lakomá enská chce.
{27646}{27696}Uhni z cesty.
{27699}{27759}Preòho je tak èi tak príliš neskoro.
{27761}{27837}Peèa bola chránená zaklínadlom...
{27840}{27890}A ten, kto sa ju pokúsi ukradnú, musí zomrie...
{27907}{27949}Nie, nesmieš!
{28129}{28178}Èo na òom vidíš?
{28181}{28244}Hej, vykašli sa nato!|Vrá sa do svojej izby.
{28432}{28486}No nie, vyzerá to, e som bola príliš nedbanlivá.
{28490}{28522}Haku!|Nie!
{29036}{29064}Haku!
{29736}{29776}Èo je zas toto!
{29778}{29812}Hej!|Poèkaj. 
{29884}{29913}Haku!
{29997}{30035}Bolí to?
{30123}{30173}Toto je váne.
{30221}{30252}Haku, nevzdávaj sa!
{30255}{30297}Nie, zomiera!
{30309}{30376}Nieèo v òom ho zabíja.
{30378}{30406}V òom?
{30409}{30485}Zaklínadlo je dobré.|U nie je niè, èo by som mohla urobi.
{30493}{30573}Haku, Boh Riek|mi dal toto.
{30576}{30626}Zjedz ho, mono e to pomôe.
{30681}{30735}Haku, otvor ústa!
{30741}{30804}Prosím, Haku, zjedz to!
{30845}{30888}Vidíš, sú bezpeèné.
{30896}{30944}Sú to bylinkové koláèiky?
{30952}{31023}Otvor.|To je dobrı chlapec...
{31116}{31158}Tak je to dobré.
{31161}{31195}Pouvaj!
{31636}{31668}Vyp¾ul to!|Vıborne!
{31973}{32001}Peèa!
{32005}{32049}Uteká preè!|Tam! Tadia¾to!
{32524}{32586}Fantastické, fantastické, Sen !|Absolútne fantastické.
{32688}{32710}Blahoelám.
{32713}{32779}Kamaji, Haku zobral toto|Yubabinej sestre.
{32788}{32850}Zenibe?|Èarodejnícka peèa!
{32862}{32912}Vzácna koris. Povedal by som.
{32975}{33021}Oh...|Vedela som, e je to Haku!
{33024}{33062}Pozri, Kamaji, je to Haku!
{33115}{33139}Haku!
{33141}{33176}Haku! Haku !
{33233}{33281}Kamaji! On nedıcha.
{33284}{33368}Ale dıcha, ale stále je|smrte¾ne chorı od toho zaklínadla...
{33592}{33663}Toto by mu malo trochu pomôc.
{33721}{33840}Haku sa tu jedného dòa objavil,|práve tak, ako ty.
{33842}{33910}Povedal, e sa chce nauèi èarova.
{33917}{33965}Nechva¾oval som to...
{33968}{33999}...sta sa èarodejníckym uèòom...
{34001}{34056}Varoval som ho,
{34065}{34125}ale nepoèúval ma.
{34132}{34172}Povedal, e nemá kam ís.
{34174}{34259}Podpísal Yubabinu zmluvu|a tak sa stal jej iakom
{34271}{34345}A po urèitom èase,|zaèal by bledším,
{34348}{34418}a jeho oèi dostali|divnı, ostrı lesk.
{34472}{34560}Kamaji, vrátim toto|Yubabinej sestre.
{34565}{34656}Vrátim to, ospravedlním sa|a poprosím ju aby pomohla Hakuovi.
{34658}{34702}Povedz mi, kde bıva.
{34713}{34769}Chceš ís za Zenibou?
{34780}{34826}Je to strašná èarodejnica.
{34829}{34847}Prosím.
{34853}{34908}Haku mi pomohol.
{34910}{34948}A teraz chcem ja pomôc jemu.
{34987}{35067}Nemôeš za òou ís, je to nebezpeèné...
{35069}{35116}Hneï sa vrátim...
{35124}{35166}Poèkaj tu.
{35224}{35302}Pozrime sa...|Niekde to tu musí by, aspoò myslím...
{35320}{35391}Hej vy, potrebujem, prosím,|moje topánky a obleèenie.
{35593}{35665}Sen! Všade som a h¾adala!
{35728}{35754}Lin.
{35757}{35820}To je Haku.|Èo sa tu stalo...
{35837}{35861}A kto sú zase títo?
{35888}{35942}Moji noví priatelia.
{35949}{36024}Yubaba tu všetko obracia hore nohami.|H¾adá a.
{36029}{36116}Ten novı zákazník sa zmenil|na príšernú obludu. Mu Bez Tváre.
{36128}{36186}Yubaba hovorí, e ty si ho pozvala.
{36269}{36296}Mono som to aj urobila.
{36299}{36351}To nemyslíš váne?!
{36353}{36397}Ja som si myslela,|e je to zákazník...
{36400}{36471}U stihol zjes|dve aby a jedného slimáka!
{36481}{36553}Našiel som to!|Tu je to, Sen!
{36564}{36604}Nemáme èas, dedko.
{36606}{36654}Môeš poui toto.
{36677}{36745}To je lístok na vlak.|Odkia¾ ho máš?
{36748}{36807}Mám ho u 40 rokov.
{36810}{36898}A teraz poèúvaj: Je to šiesta zástavka.|S názvom Dno bainy.
{36905}{36932}Dno bainy?
{36935}{36981}Presne tak. Je to šiesta zástavka.
{36984}{37006}Šiesta zástavka.
{37012}{37104}Dávaj si pozor, aby si vystúpila na správnej zastávke.|Kedysi jazdili vlaky oboma smermi,
{37106}{37152}ale teraz,|je to len jednosmernı vlak.
{37155}{37193}Ešte stále to chceš urobi?
{37196}{37274}Áno.|Spä sa vrátim popri elezniènej trati.
{37315}{37357}Ale èo s Yubabou?
{37360}{37395}Idem teraz za òou.
{37409}{37500}Haku, s¾ubujem ti, e sa vrátim spä.|Nesmieš zomrie!
{37516}{37556}Èo sa to tu deje?
{37569}{37628}Nevidíš?|Volá sa to... Láska...
{37817}{37873}Stále to rastie!
{37878}{37916}Nech ma to nezje!
{37919}{37940}Ide sem!
{38121}{38157}Vïaka bohu, Sen!
{38160}{38218}Yubaba  ho u nedokáe zabavi.
{38289}{38381}Netreba sa vzrušova.|Som si istı, e Sen sa vráti.
{38392}{38451}Kde je Sen! Chcem Sen!
{38459}{38499}Choï. Rıchlo.
{38627}{38673}Yubaba, je tu Sen.
{38676}{38711}Kde si!
{38714}{38818}Sen prichádza, drahı hos.|Hneï bude pri tebe.
{38843}{38917}Èo a tak dlho zdralo!|Toto je absolútna katastrofa!
{38920}{38987}Podlizuj sa mu|a vymıkaj z neho všetko zlato.
{39083}{39139}Èo je to za špinavého potkana?!
{39183}{39239}Nespoznávate ho?
{39245}{39312}Samozrejme nie.|Aké nechutné!
{39317}{39348}A teraz choï dnu.
{39385}{39440}Ak nás budeš potrebova, zavolaj.
{39461}{39516}Zvládne to sama?
{39522}{39566}Chceš zauja jej miesto?
{40057}{40133}Vyskúšaj toto, je to chutné.
{40179}{40286}Chceš nejaké zlato?|Nikomu inému ho nedám.
{40383}{40425}Poï sem, Sen.
{40428}{40514}Èo chceš, Sen?|Mne to môeš poveda.
{40523}{40569}Odkia¾ si prišiel?
{40572}{40628}Niekde existuje miesto,|kam patríš.
{40685}{40745}Mal by si sa vráti tam,|odkia¾ si prišiel.
{40748}{40819}Nedokáeš mi pomôc|v tom, èo chcem.
{40865}{40937}Kde máš domov?|Nemáš mamu a otca?
{40957}{41036}Nechcem...|Nechcem...
{41060}{41150}Som sám, samuèièkı...
{41169}{41205}Nemôeš sa vráti domov?
{41215}{41299}Chcem Sen, chcem Sen!
{41315}{41341}Vezmi si zlato.
{41355}{41383}Chceš ma zjes?
{41385}{41405}Vezmi si ho!
{41408}{41428}Vezmi si ho!
{41651}{41715}Ak ma chceš zjes,|daj si najprv toto.
{41731}{41827}Odloila som ich pre mojich rodièov,|ale daj si to.
{42327}{42359}Sen!
{42419}{42508}Dievèa nešastné!|Èo si mi to dalo?!
{42875}{42907}Z cesty!
{42935}{42979}Nie v mojom dome!
{43301}{43335}Tadia¾to.
{43353}{43385}Sem!
{44459}{44499}Za toto mi zaplatíš!
{44917}{44966}Sen, tadia¾to!
{45359}{45413}Tu som.|Tadia¾to !
{45416}{45455}Nevolaj ho sem.
{45547}{45635}Len sa necíti dobre v kúpe¾och.|Potrebuje sa len dosta odtia¾to.
{45639}{45691}Ale kam ho chceš zobra?
{45693}{45717}Neviem...
{45720}{45827}Nevieš...|Ide za nami.
{46248}{46271}Odtia¾to u pôjdeš pešo.
{46274}{46298}Jasné.
{46301}{46343}Nájdeš stanicu?
{46345}{46380}Ïakujem Ti.
{46395}{46433}Radšej sa vrá!
{46439}{46463}Jasné.
{46563}{46647}Volala som a nemehlo!
{46649}{46687}Beriem to spä!
{46883}{46982}Bez Tváre, ak skrivíš tomuto dievèau, èo len vlások|zaplatíš za to!
{47061}{47093}Tu je to.
{47371}{47428}Prichádza vlak. Ideme.
{47991}{48044}Idem do Dna bainy.
{48203}{48243}Chceš ís tie?
{48279}{48326}Aj on ide, prosím.
{49299}{49331}Poï sem.
{49345}{49385}Správaj sa slušne, jasné?
{52315}{52349}Kamaji.
{52407}{52469}Oh. Haku...|Prebral si sa.
{52472}{52508}Kde je Sen?
{52519}{52580}Èo sa stalo, prosím, povedz mi to.
{52587}{52655}Na niè sa nepamätáš?
{52669}{52719}Len útrkovite.
{52724}{52799}Chihiro volala moje meno...|V temnote...
{52805}{52901}Išiel som za jej hlasom|a zobudil som sa tu...
{52911}{52959}Chihiro, ha...
{52961}{53028}Jej skutoèné meno je Chihiro?
{53057}{53126}Ani Yubaba nedokáe porazi silu lásky...
{53215}{53289}Toto zlato len ako|pokryje všetky škody.
{53292}{53361}Hlúpa Sen!|Kvôli nej sa odomòa šastena odvrátila.
{53373}{53463}Ale Sen nás nakoniec všetkıch zachránila
{53465}{53493}Ticho!
{53496}{53554}Ona to ale spôsobila.
{53556}{53612}A teraz ušla preè.
{53615}{53678}Dokonca opustila|aj svojich vlastnıch rodièov!
{53695}{53786}Tí by mali by u dostatoène vykàmení.|Urobte z nich slaninu alebo šunku.
{53795}{53834}Poèkajte, prosím.
{53861}{53888}Pán Haku!
{53892}{53944}Èo? Ty ešte iješ?
{54003}{54082}Ešte stále si si nevšimla,|e si stratila nieèo ve¾mi vzácne?
{54095}{54162}Pekne si oil!
{54165}{54224}Keï si dovolíš takto rozpráva...
{55463}{55510}Bábo...
{55653}{55692}Bábo!
{55696}{55719}Je to len piesok!
{55723}{55790}Bábo!
{55801}{55892}Kde si bábo!
{55901}{55964}Vylez bábo!
{55981}{56012}Bábätko!
{56091}{56146}Bábo, bábätko!
{56257}{56364}Ty!
{56395}{56475}Povedz mi!
{56511}{56610}Kde si schoval moje bábätko?!
{56621}{56664}Je u Zeniby.
{56668}{56715}U Zeniby?
{57219}{57308}U rozumiem, tá zákerná bosorka.
{57312}{57375}Take ona si myslí, e ma porazila.
{57415}{57468}Tak akı je tvoj plán?
{57478}{57530}Donesiem ti bábo naspä.
{57533}{57635}A ty zato vrátiš Sen|a jej rodièov spä do sveta ¾udí.
{57641}{57696}A èo bude s tebou?!
{57703}{57792}Povedzme, e a, potom ako ich pošlem preè,|roztrhám na kúsky!
{58915}{58964}Myslím, e toto je správna zastávka...
{58985}{59016}Poïme.
{59660}{59705}Môeš si mi sadnú na rameno.
{61586}{61628}Poïte ïalej.
{61744}{61787}Prepáète...
{61834}{61892}Rıchlo, ponáh¾ajte sa a poïte dnu.
{61904}{61935}Boe môj, ponáh¾aj sa.
{62014}{62057}Tak, všetci ste to zvládli.
{62060}{62074}Um...
{62077}{62119}Sadnite si.
{62122}{62180}Urobím vám èaj.
{62316}{62416}Zeniba, Haku ti toto ukradol.|Doniesla som to spä.
{62496}{62553}Vieš, èo je to?
{62562}{62633}Nie, ale viem, e je to vzácne.
{62636}{62722}Som tu, aby som sa ospravedlnila za Hakua.|Mrzí ma to.
{62738}{62817}Cítila si sa dobre, keï si to drala?
{62820}{62842}Èo?
{62845}{62909}Èo je toto?|Kúzlo sa pominulo.
{62938}{63013}Mrzí ma to,|ale stupila som na toho divného chrobáka...
{63016}{63060}...ktorı bol na tej peèati.|A rozpuèila ho.
{63073}{63124}Rozpuèila ho!
{63174}{63253}Vieš, moja sestra nasadila toho chrobáka|do draka,
{63256}{63324}aby tak ho tak mohla kontrolova.
{63327}{63387}Rozpuèila ho!
{63454}{63496}Poï sadni si.
{63499}{63564}Ty si mu Bez Tváre, však?|Aj ty sa posaï.
{63589}{63677}Uhm, prosím, vráte|im ich pôvodnú podobu.
{63680}{63754}Naèo moja drahá,|veï kúzlo je u dávno zlomené.
{63757}{63815}Môete sa zmeni spä.
{63990}{64081}Moja sestra a ja sme dve polovice|jedného celku, ale v skutoènosti spolu nevychádzame.
{64084}{64146}Veï si videla,|akı má mizernı vkus.
{64149}{64223}Èarodejnícke dvojèatá sú len|recept na problémy.
{64320}{64427}Chcela by som ti pomôc, moja drahá,|ale nemôem s tım niè urobi.
{64430}{64477}Je to ia¾ jedno z našich pravidiel.
{64490}{64561}O svojich rodièov|a draèieho priate¾a
{64564}{64604}sa musíš postara sama.
{64607}{64675}Ale nemohli by ste mi|aspoò poradi?
{64686}{64771}Mám pocit, akoby sme sa ja a Haku,|u kedysi dávno stretli.
{64775}{64819}Tak v tom prípade je to ¾ahké.
{64828}{64891}Niè z toho èo sa stalo,|nie je zabudnuté na vdy,
{64894}{64945}aj keï si na to teraz|nemôeš spomenú.
{64978}{65057}U je neskoro.|Ostanete tu na noc?
{65068}{65135}Vy mi pomáhate?
{65282}{65329}Pozor na to.
{65402}{65503}Takto je to dobré. Ste vıborní.|Ve¾ká pomoc...
{65524}{65601}Èarodejník by|by to nezvládol lepšie.
{65634}{65737}Potiahni to tam...|A zopakuj to...
{65743}{65806}Skutoène musím|ís domov, starká...
{65821}{65904}Haku môe zomrie,|kım ja tu len vysedávam...
{65909}{65993}Môu zjes môjho otca a mamu!
{66046}{66112}Len vyèkaj ešte chví¾ku.
{66115}{66150}A je to.
{66172}{66225}Poui ju na upevnenie svojich vlasov.
{66348}{66363}Je taká pekná.
{66370}{66486}Ochráni a.|Urobila som s ich pomocou z vlákien priadze.
{66494}{66531}Ïakujem.
{66754}{66846}Aké dobré naèasovanie.|Máme ïalšieho hosa. Pusti ho ïalej.
{66849}{66875}Áno.
{67194}{67219}Haku!
{67250}{67287}Haku!
{67298}{67335}Vïaka bohu.
{67344}{67403}Ty nie si zranenı?|Skutoène si v poriadku?
{67410}{67432}Vïaka bohu.
{67478}{67532}Dobré naèasovanie, povedala by som.
{67548}{67607}Pozri, starká, Haku je naive.
{67620}{67719}Haku, u a neviním|z toho, èo si urobil.
{67722}{67801}Len ochráò to dievèa.
{67812}{67881}OK, chlapci. Je èas ís domov.
{67884}{67934}Príïte opä.
{67952}{68056}Ty tu zostaneš|a budeš mojím pomocníkom.
{68116}{68137}Starká!
{68154}{68205}Ïakujem ti. U pôjdem.
{68208}{68282}Som si istá,|e to zvládneš.
{68285}{68363}Moje skutoèné meno je Chihiro.
{68366}{68425}Chihiro... aké pekné meno.
{68428}{68476}Dávaj si naò dobrı pozor,|je tvoje.
{68479}{68492}Budem!
{68496}{68539}Tak u choïte.
{68580}{68653}Ïakujem ti starká.|Zbohom.
{69832}{69871}Poèúvaj, Haku...
{69874}{69959}Síce sa na to nepamätám,|ale moja mama mi to rozprávala...
{69969}{70055}Raz, keï, som bola ešte malá,|spadla som do rieky.
{70068}{70155}Povedala, e u ju vysušili|a na jej mieste nieèo postavili.
{70164}{70215}Ale ja som si práve spomenula, 
{70242}{70281}e tá rieka sa volala...
{70292}{70367}Jej meno bolo rieka Kohaku.
{70382}{70459}Tvoje skutoèné meno je Kohaku.
{70972}{71007}Chihiro, ïakujem ti.
{71010}{71086}Moje skutoèné meno je|Nigihayami Kohaku Nushi.
{71100}{71123}Nigihayami?
{71126}{71180}Nigihayami Kohaku Nushi.
{71183}{71242}To je krásne meno.|Ako pre boha.
{71252}{71357}Ja si tie pamätám, e |si do mòa padla, ako diea.
{71360}{71400}Stratila si topánku.
{71412}{71511}A ty si sa o mòa postaral.|Odniesol si ma do plytkej vody, Kohaku.
{71532}{71559}Som ti vïaèná...
{72348}{72381}Vrátili sa!
{72700}{72771}Doniesol si bábo spä, však?
{72834}{72856}Baba!
{72859}{72964}Nie si zranenı?|Akı príšernı èas si asi preíval.
{72995}{73068}Bábo, ty u vieš stá?|Odkedy?
{73084}{73135}Yubaba, s¾úbila si to.
{73138}{73206}Prosím vrá Chihiro|a jej rodinu do ¾udského sveta.
{73220}{73279}Nie tak rıchlo.
{73282}{73353}Tento svet má pravidlá, to vieš!
{73372}{73399}Èušte!
{73403}{73463}Baba, nebuï zlá.|Môeš to urobi.
{73472}{73531}Bábo sa tak dobre zabávalo.
{73544}{73611}Ale pravidlo je pravidlo.
{73614}{73668}Inak nebudem môc zlomi kúzlo.
{73676}{73749}Ak rozplaèeš Sen,|u a nebudem ma rád, Baba.
{73762}{73789}Preèo to...
{73792}{73826}Starká.
{73829}{73857}Starká!?.
{73868}{73915}Idem za tebou.
{74190}{74245}Haku mi povedal všetko o pravidlách.
{74248}{74292}Nakoniec máš odvahu.
{74295}{74372}Tu je tvoja zmluva.|Poï sem.
{74376}{74433}Nebude to ani minúta, bábo.
{74452}{74483}Neboj sa.
{74590}{74681}Pozri sa na nich a hádaj,|ktorí sú tvoji rodièia.
{74906}{74941}Máš len jeden pokus.
{74944}{75005}Uhádni, a ste všetci vo¾ní.
{75292}{75377}Starká, toto je zvláštne.|Moji rodièia tu nie sú.
{75386}{75467}Nie sú tu?!|To je tvoja odpoveï?
{75506}{75529}Áno.
{75598}{75675}Bingo!
{75678}{75738}Toto dievèa je super!|Vıborne!
{75832}{75863}Ïakujem vám, všetkım.
{75866}{75944}Choï! Vyhrala si.|Len si choï preè!?
{75956}{76001}Ïakujem za všetko.
{76018}{76049}Zbohom.
{76068}{76093}Ïakujem vám.
{76096}{76121}Príï nás niekedy pozrie.
{76130}{76143}Haku.
{76147}{76170}Poïme.
{76188}{76217}Kde sú mama a otec?
{76220}{76249}U išli popredu.
{76432}{76463}Nie je tu voda!
{76466}{76502}U nesmiem ís ïalej.
{76514}{76570}Vrá sa cestou,|ktorou si prišla, Chihiro.
{76573}{76646}Ale neobzeraj sa spä.|Dovtedy, kım nevyjdeš z tunela.
{76652}{76700}A èo bude s tebou, Haku?
{76712}{76779}Porozprávam sa s Yubabou.|Dám jej vıpoveï.
{76782}{76841}U som v poriadku.|Mám spä svoje meno.
{76856}{76899}Aj ja sa vrátim do svojho sveta.
{76902}{76936}Stretneme sa ešte niekedy?
{76939}{76958}Urèite.
{76961}{76975}S¾úb mi to.
{76978}{77000}S¾ubujem.
{77003}{77062}Teraz choï a neobzeraj sa.
{77608}{77643}Chihiro!
{77654}{77715}Kde si bola?|Ponáh¾aj sa.
{77802}{77845}Mami! Oci!
{77848}{77890}Nemôeš takto odbieha.
{77893}{77924}Poïme spä.
{77936}{77987}Mami, si skutoène v poriadku?
{77990}{78092}Èo? Som si istá,|e špeditéri tam u budú.
{78317}{78371}Ponáh¾aj sa, Chihiro.
{78580}{78621}Dávaj pozor, kam stúpaš.
{78624}{78704}Budeš ma vies, Chihiro|èo na to hovoríš?
{78997}{79032}Koniec tunela.
{79042}{79072}Hej...
{79080}{79111}Èo je to?
{79132}{79177}Pozri sa na to.
{79204}{79263}Je tam kopa prachu.
{79266}{79285}Je to nejakı art?
{79288}{79314}Myslíš?
{79317}{79376}Hovorila som ti, aby si sa tu nezastavoval.
{79510}{79569}V poriadku, poïme.
{79600}{79653}U meškáme, Chihiro.
{79656}{79722}Ponáh¾aj sa, Chihiro!
{80296}{80347}Hlasy postavám poièali:
{80351}{80426}Chihiro HllRAGl Rumi|Haku IRINO Miyu
{80429}{80504}Yubaba NATSUKI Mari
{80508}{80583}Otec NAlTO Takashi|Mama SAWAGUCHI Yasuko
{80586}{80661}Chichi-yaku KAMlJO Tsunehiko|Ani-yaku ONO Takehiko
{80664}{80739}Kamaji SUGAWARA Bunta
{80908}{80991}Vedúci produkcie|TOKUMA Yasuyoshi
{80994}{81073}Vedúci vırobného štábu|MATSUSHITA Takeyoshi, UJIIE Seiichiro,
{81076}{81156}NARITA Yutaka, HOSHlNO Koji,|UEMURA Banjiro & AIHARA Hironori
{81159}{81238}Príbeh a scenár|MIYAZAKI Hayao
{81241}{81320}Hudba|HISAISHI Joe
{81324}{81403}Texty piesní|KAKU Wakako
{81406}{81485}Hudobné prevedenie|KIMURA Youmi
{81488}{81568}Anglickı preklad|Linda HOAGLUND, Judith ALEY,
{81571}{81650}MORlYOSHl Ha'ruyo|and Steve ALPERT
{81653}{81732}Slovenské titulky |Andrea B.
{84217}{84295}Uviedli
{84298}{84376}Tokuma Shoten,|Studio GhibIi.
{84379}{84456}Nippon Television Netwo'rk,|Dentsu,
{84460}{84537}Buena Vista|Home Entertainment
{84540}{84615}Tohokushinsha Film|and Mitsubishi
{84884}{84967}Vyrobilo|Studio Ghibli
{84970}{85061}Producent|SUZUKI Toshio
{85133}{85307}Réia|MIYAZAKI Hayao
{85330}{85437}Koniec