{535}{585}Zlatı prach! Zlato!|To je zlato!
{589}{651}Ruky preè!|To je majetok spoloènosti!
{655}{737}Buïte ticho|Náš hos je tu stále s nami
{879}{950}Sen, stojíš mu v ceste|Nabok a otvorte dvere
{953}{1013}Otvorte hlavnú bránu!|Odchádza!
{1655}{1753}Sen! Viedla si si skvelo!|Zarobila si nám balík!
{1771}{1833}Tento rieèny boh je velmi známi
{1836}{1875}Všetci sa môte uèi od Sen
{1889}{1937}Saké na izby, pre dnešnú noc!
{1949}{2034}Tak a ja sa zatial postarám|o to zlato ktoré ste pozbierali!
{2341}{2388}Chceš trochu?|Šlohla som to
{2401}{2435}Vïaka
{2437}{2489}Páni, to bolo
{2551}{2587}Nevidela som tam Haka
{2589}{2631}Ách, nie zase Haku
{2653}{2711}Niekedy sa proste vyparí
{2721}{2812}Hovoria, e Yubaba ho|núti robi zlé veci
{2815}{2835}Naozaj?
{2837}{2882}Zhasíname svetlá, Lin
{2884}{2901}OK
{3503}{3567}To mesto|Vypadá ako oceán...
{3573}{3642}A èo si èakala|po takej búrke
{3687}{3783}Niekedy, prisahám e odídem do toho mesta|Vypadnem odtia¾to
{4347}{4401}Èo sa deje!
{5111}{5147}Zlato!
{5215}{5289}Kto si?|Ty niesi zákazník
{5292}{5331}Tu nemáš èo robi!
{5491}{5566}Hej! To je zlato, zlato!|Je premòa!?
{5693}{5748}Dokáeš vyrobi zlato?
{5883}{5904}Daj mi!
{6103}{6143}Kto je tam?
{6171}{6225}U je po veèierke
{6311}{6389}Hej šéfe. Som hladnı
{6392}{6420}Vyhladovenı
{6423}{6444}Ten hlas...
{6446}{6491}Tu. Zaplatím ti
{6509}{6573}Som zákazník, chem kúpe¾!
{6576}{6614}Zobuï všetkıch!
{6747}{6827}Mami, oci, rieèny boh|mi dal tento zákusok
{6829}{6899}Som si istá e keï ho ziete,|ope z vás budú ¾udia
{6997}{7045}Oci, mami. Kde ste?
{7055}{7084}Oci!
{7351}{7379}Hroznı sen
{7415}{7451}Lin...?
{7543}{7583}Kde sú všetci?
{7739}{7805}Fíha... Skutoène sa|to zmenilo na oceán!
{7933}{8004}Dovidím a k otcovi|a mame s tadeto
{8093}{8145}Kamaji u zapálil ohne?
{8148}{8198}eby som spala tak dlho?
{8277}{8348}Zákazníci èakajú|Pohnite si!
{8351}{8447}Naservírujte všetko èo máme|Aj zvyšky!
{8495}{8517}Sen!
{8520}{8543}Lin
{8549}{8614}Akurát som a išla zobudi|Pozri!
{8621}{8674}Skutoèné zlato|Dal mi ho
{8683}{8735}Ten hos je naozaj štedrı
{8737}{8792}Prosím, pane, skúste toto!
{8794}{8852}Chutná to lepšie!
{8891}{8953}Hoïte nám ešte trochu zlata!
{8973}{8999}Vaša láskavos!
{9001}{9081}Som vyhladovenı|prineste to všetko!
{9098}{9155}Prosím pane!
{9193}{9224}Ten hos...
{9231}{9312}Poï, Sen, Yubaba stále spí|Teraz máš šancu
{9323}{9367}Idem pozrie Kamajiho
{9381}{9434}Nechodila by som tam
{9437}{9491}Má zlú náladu,|pretoe ho zobudili
{9493}{9537}Poïme si ešte zobra, Lin
{10142}{10222}Èo ak nespoznám|svojich rodièov?
{10241}{10308}Dúfam e otec moc nepribral
{10985}{11021}Ten sen èo sa mi sníval
{11035}{11069}Ide tımto smerom!
{11135}{11187}Èo sú to zaè?|To niesu vtáci
{11440}{11514}Vrá im to, Haku!|Taïeto
{11517}{11536}Haku!
{11553}{11579}Haku!
{12015}{12071}Och...|Je to len papier...
{12749}{12801}Haku?|Si to ty?
{12949}{13029}Si ranenı?|Tie papierové veci sú u preè
{13032}{13062}Si v bezpeèí.
{13379}{13420}Ide za Yubabou...
{13435}{13493}Och, nie!|Zomrie!
{13683}{13787}Najbohatší mu|v celom šírom svete
{13797}{13890}Ten mu práve prichádza
{13920}{13970}Vitajte!
{13973}{14028}Èas na obranie o sprepitné|Zaènite obra
{14031}{14101}Prosím, pane! Aj sem!
{14104}{14170}obrajte
{14173}{14213}obrajte
{14216}{14263}Zlaté pramene z jeho rúk
{14280}{14357}Hoïte aj sem trochu, pane!
{14453}{14488}Hej, èo to tu robíš?
{14490}{14514}Idem hore
{14517}{14564}Nie, to nemôeš|Èo je to!
{14581}{14610}To je krv!
{14700}{14769}Hıb sa, nabok|Nechaj nášho hosa preis
{14797}{14845}Ïakujem vám za vašu pomoc predtım
{14849}{14908}Nestoj tam len tak...
{15433}{15493}Nechcem zlato|iadne nepotrebujem
{15544}{15600}Nemám èas, prosím prepáète mi
{15878}{15947}Ticho! Utíšte sa!
{15964}{16004}Spä, choïte spä!
{16013}{16064}Prosím odpustite jej tie spôsoby
{16066}{16152}Nakoniec, je to len èlovek|a je tu nová...
{16209}{16253}Neušklebuj sa tak
{16256}{16286}Videl som ten poh¾ad
{16288}{16334}Preèo, nikdy by som...
{16432}{16488}Ziedol ich!
{18573}{18609}Yubaba?
{20349}{20412}Máme celkom vány problém teraz
{20428}{20478}V skutoènosti, to je Mu bez tváre
{20482}{20528}Správne, Mu bez tváre!
{20536}{20604}Vaša nenásitnos ho prilákala
{20617}{20696}Nie e vyvediete nejakú hlúpos|dokia¾ tam neprídem
{20709}{20768}Pozrite, èo za bordel je tu na koberci
{20770}{20824}Postarajte sa o Haka
{20827}{20871}U ho viac nepotrebujem
{21411}{21483}Zase spíš mimo|svojej postie¾ky?
{21579}{21681}No tak prepáè, však si|spinkal ako dobré dieatko
{21684}{21752}Bába má ešte nejakú prácu
{21822}{21888}Ešte si trochu pospi|Dobré diea
{22569}{22607}Au, nechajma!
{22617}{22662}Och, ïakujem za pomoc
{22665}{22744}Ale ponáh¾am sa|Prosím pusti ma
{22747}{22803}Prišla si sem aby si ma nakazila
{22816}{22876}Zlé baktérie vonku, zlé
{22899}{22991}Som èlovek|Asi si ešte iadneho nevidel
{22997}{23053}Vonku ochorieš
{23056}{23104}Ostaò tu a hraj sa somnou
{23109}{23147}Si chorı?
{23150}{23218}Som tu preto,|lebo vonku by som ochorel
{23221}{23280}Keï budeš trèa tu|tak s toho ochorieš!
{23283}{23373}Vieš, niekto o koho si robím|starosti bol ve¾mi tako zranenı
{23376}{23416}Take musím u ís
{23418}{23449}Prosím pusti mi ruku!
{23456}{23496}Ak odídeš, zaènem plaka
{23498}{23581}A ak budem plaka,|Bába príde a zabije a
{23584}{23624}Zlomím ti tu tvojú malú ruèièku
{23626}{23655}To bolí!
{23657}{23717}Prosím, prídem sa s tebou|zahra neskôr
{23721}{23759}Nie. Chcem sa hra teraz!
{23856}{23908}To je krv! Vidíš!|Krv!
{24185}{24228}Hakuuu!
{24230}{24290}Prestaòte, choïte preè!|Heš. Heš!
{24293}{24317}Haku! Si to ty?
{24318}{24346}Vydr!
{24357}{24409}Pokojne!|Haku!
{24517}{24571}Heš, heš, choïte preè
{24636}{24668}Och. nie!
{25029}{25072}Nebojím sa krvy
{25074}{25119}Budem plaka ak sa somnou nebudeš hra
{25121}{25167}Prosím buï dobrı chlapec a poèkaj
{25177}{25249}Ak sa nebudeš somnou hra,|rozplaèem sa...
{25297}{25332}Prosím. Zadr!
{25334}{25411}Akı hurhaj|Utíšte sa
{25444}{25512}Ty si mi ale malı buclík
{25689}{25744}Stále som trochu priesvitná
{25746}{25764}Bába
{25781}{25880}Ach, drahúšik, nemohla mi|o tom poveda tvoja matka?
{26076}{26146}Toto by ti malo da|trochu viac slobody
{26149}{26167}Tak sa nato pozrime...
{26176}{26222}Naèo asi tak premeníme teba?
{26656}{26731}To bude naše malé tajomstvo|Niekomu to povieš...
{26734}{26781}a prídeš o ústa
{26809}{26837}Kto si?
{26841}{26900}Yubabine dvojèa
{26902}{26998}Vïaka tebe, som sa tu mohla|poobzera k môjmu pobaveniu
{27001}{27041}A teraz sa postarám o toho draka
{27047}{27104}Èo chceš robi s Hakom?|Je ako ranenı
{27113}{27185}Ten draèí zlodej,|je poskok mojej sestry
{27188}{27264}Ukradol mi moju|vzácnu peèa
{27266}{27332}To by nespravil!|Je velmi milı
{27345}{27432}Všetci draci sú milı|Milı a hlúpy
{27434}{27543}Dychtivı sa nauèi|mágiu mojej sestry,
{27553}{27644}tento chlapec spraví všetko|èo tá nenásitná ena chce
{27646}{27696}Ustúp nabok
{27699}{27759}Aj tak je u preòho neskoro
{27761}{27837}Peèa bola chránena|kúzlom...
{27840}{27900}A kto sa ju pokúsi ukradnú musí zomrie
{27907}{27949}Nie. To nemôeš!
{28129}{28178}Èo sa im stalo?
{28181}{28264}Hej vy tam, prestaòte s tım!|Choïte spä do svojej izby
{28432}{28486}Och. Drahı, zdá sa e som a podcenila
{28490}{28522}Haku!|Oh, nie!
{29036}{29064}Haku!
{29736}{29776}Èo má toto znamena!
{29778}{29812}Hej!|Poèkaj
{29884}{29913}Haku!
{29997}{30035}Bolí to?
{30123}{30173}Zdá sa e to je váne
{30221}{30252}Haku, nevzdávaj to!
{30255}{30297}Oh, nie. Umrie!
{30309}{30376}Má nieèo v sebe|èo ho zabíja
{30378}{30406}V sebe?
{30409}{30485}Je to kúzlo|Nemôem s tım niè robi
{30493}{30573}Haku. Rieèny boh|mi dal toto
{30576}{30636}Zjedz to, mono to pomôe
{30681}{30735}Haku. Otvor ústa!
{30741}{30804}Prosím. Haku, zjedz to!
{30845}{30888}Vidíš, je to dobré
{30896}{30944}eby to bol zákusok z byliniek?
{30952}{31023}Otvor|Dobrı chlapec...
{31116}{31158}To je ono
{31161}{31195}Spolkni to!
{31636}{31698}Vyvrátil to!|To je ono!
{31973}{32001}Peèa!
{32005}{32049}Ueká to!|Tam! Tamtım smerom!
{32524}{32586}Hrubá Sen!|Moc moc hrubá
{32678}{32710}A má to!
{32713}{32779}Haku to zobral|Yubabinej sestre
{32788}{32850}Od Zeniby?|Jeibabina peèa!
{32862}{32912}Cenná koris.
{32975}{33021}Oh...|Vedela som e to bol haku!
{33024}{33082}Pozri Kamaji, to je Haku!
{33115}{33139}Haku!
{33141}{33176}Haku! Hakuuu!
{33233}{33281}Kamaji! Nedıcha
{33284}{33368}Dıcha, len je stále|váne ranenı od toho kúzla...
{33592}{33663}To by ho malo trochu upokoji
{33721}{33840}Haku sa tu raz objavil,|presne ako ty
{33842}{33910}Hovoril e sa chce uèi mágiu
{33917}{33965}Neschva¾oval som to...
{33968}{34013}Sta sa èarodejníckym uèòom...
{34015}{34056}Varoval som ho,
{34065}{34125}Ale nepoèúval ma
{34132}{34172}Hovoril e nemá kam ís
{34174}{34259}A tak sa zapísal|za Yubabinho uèòa
{34271}{34345}A ako plynul èas,|tak postupne bledol,
{34348}{34418}a jeho oèi nadobudli|ostrı poh¾ad
{34472}{34560}Kamaji, idem toto vráti spä|Yubabinej sestre
{34565}{34656}Vráti jej to spä, ospravedlni sa,|a poiada o pomoc pre Haka
{34658}{34702}Povedz mi kde ije
{34713}{34769}Chceš ís za Zenibou?
{34780}{34826}Je to hrozná èarodejnica
{34829}{34847}Prosím
{34853}{34908}Haku mi pomohol
{34910}{34968}Tak mu teraz chcem pomôc ja
{34987}{35067}Dosta sa tam nieje problém...
{35069}{35116}Ale cesta spä...
{35124}{35166}Poèkaj tu
{35224}{35302}Pozrime sa...|Niekde to tu musí by, myslím...
{35320}{35391}Poèúvajte, potrebujem svoje topánky|a šaty. Prosím
{35593}{35665}Sen! Všade som a h¾adala!
{35728}{35754}Lin
{35757}{35820}To je Haku|Èo sa tu stalo...
{35830}{35881}A kto sú tıto dvaja?
{35888}{35942}Moji novı kamaráti
{35949}{36024}Yubabu ide roztrhnú,|všade a h¾adá
{36029}{36116}Z ve¾kého rozhadzovaèa sa stala|hrozná obluda - Mu bez tváre
{36118}{36206}Yubaba povedala e to|ty si ho sem doviedla
{36269}{36296}Mono e hej
{36299}{36351}To váne?
{36353}{36397}Myslela som|e to je zákazník...
{36400}{36471}U ziedol dve aby a slimáka!
{36481}{36553}Našiel som to!|Tu je to, Sen!
{36564}{36604}Teraz nemáme èas, starkı
{36606}{36654}Môes skúsi toto
{36677}{36745}To sú lístky na vlak|Odkial to máš?
{36748}{36807}Mám to u 40 rokov
{36810}{36898}A teraz poèúvaj. Je to  6. zastávka|"Bainné dno"
{36905}{36932}Bainné dno?
{36935}{36981}Správne, je to 6. zastávka
{36984}{37006}6. zastávka
{37012}{37104}Dobre si to zapametaj|Kedysi chodil aj spiatoènı vlak,
{37106}{37152}ale dnes u je to|jednosmerná jazda
{37155}{37193}Stále máš záujem?
{37196}{37274}Hej|Vrátim sa pešo, popri trati
{37315}{37357}Ale èo bude s Yubabou?
{37360}{37395}Idem zaòou teraz
{37409}{37500}S¾ubujem e sa vrátim, Haku|Nesmieš umrie
{37516}{37556}Èo sa tu deje?
{37569}{37628}Nevidíš?|Hovorí sa tomu... Láska...
{37817}{37873}Stále rastie!
{37878}{37926}Nenechajte ma spolknú!
{37929}{37960}U ide!
{38121}{38157}Vïaka bohu, Sen!
{38160}{38218}Yubaba ho nezvláda
{38289}{38381}Nieje dôvod sa rozèu¾ova|Som si istá e sen to zvládne
{38392}{38451}Kde je Sen! Ja chcem Sen!
{38459}{38499}Choï. Rıchlo
{38627}{38673}Yubaba, to je Sen
{38676}{38711}Kde si bola?
{38714}{38818}U je tu Sen, drahı hos|Hneï sme tam
{38843}{38917}Èo ti to tak dlho trvalo!|Toto je hotová pohroma!
{38920}{39017}Podliezaj sa mu a dostaò|z neho všetko zlato èo má
{39083}{39139}Èo je to za špinaú krysu?
{39183}{39239}Nespoznávaš ho?
{39245}{39312}Iste e nie.|Aké odporné!
{39317}{39348}Tak. Ideš nato
{39385}{39440}Zavolaj ak by si nás potrebovala
{39461}{39516}Bude vporiadku|keï je tam sama?
{39522}{39566}Chceš si to s òou vymeni?
{40057}{40133}Skús toto, je to pochúka
{40179}{40286}Chceš trochu zlata?|U ho nerozdávam kadému
{40383}{40425}Poï sem, Sen
{40428}{40514}Èo je TO èo chceš?|Povedz mi
{40523}{40569}Odial si prišiel?
{40572}{40628}Potrebujem sa dosta|na isté miesto
{40675}{40745}Ty by si sa tie mal vráti|tam s kade si prišiel
{40747}{40819}Nepomôeš mi|s tım èo chcem
{40850}{40937}Kde je tvoj domov?|Máš niekde mamu a otca?
{40957}{41036}Ja nechcem...|Nechcem...
{41060}{41150}Som osamelı, osamelı...
{41169}{41205}Nemôeš sa vráti domov?
{41215}{41299}Ja chcem Sen, chcem Sen
{41315}{41341}Zober si zlato
{41355}{41383}Chceš ma zies?
{41385}{41405}Zober si!
{41408}{41428}Zober!
{41651}{41715}Ak ma chceš zies,|skús najprv toto
{41731}{41827}Odkladala som si to pre rodièov,|ale môeš si to zobra
{42327}{42359}Sen!
{42419}{42508}Dievèa!|Èo si mi to dala?
{42875}{42907}Z cesty!
{42935}{42979}Nie v mojom dome!
{43301}{43335}Tadeto
{43353}{43385}Tu!
{44450}{44500}Za toto mi zaplatíš!
{44917}{44966}Sen, tadeto!
{45359}{45413}Tam je|Tadeto!
{45416}{45455}Nevolaj ho sem
{45547}{45635}Je zlı iba v tıch kúpe¾och|Musí sa s tade dosta
{45639}{45691}Ale kam ho chceš zobra?
{45693}{45717}Neviem...
{45720}{45827}Tak ty nevieš?|Ale ide zanami
{46248}{46271}Odtia¾to môeš ís pešo
{46274}{46298}OK
{46301}{46343}Nájdeš tam stanicu
{46345}{46380}Ïakujem
{46395}{46433}Bude lepšie ak sa vrátiš!
{46439}{46463}OK
{46563}{46647}Sen, viem e som a nazvala nemehlom!
{46649}{46687}Beriem to spä!
{46873}{46982}Mu bez tváre! Ak sa èo len dotkneš|toho dievèaa tak zato zaplatíš!
{47061}{47093}Tu je to
{47371}{47428}Prichádza vlak. Poïme
{47991}{48044}Idem k Bainnému dnu
{48203}{48243}Ty ideš tie?
{48279}{48326}On tie. Prosím
{49299}{49331}Poï
{49345}{49385}Chovaj sa slušne, dobre?
{52315}{52349}Kamaji
{52407}{52469}Oh. Haku...|U ti je lepšie?
{52472}{52508}Kde je Sen?
{52519}{52580}Èo sa stalo, povedz mi prosím
{52587}{52655}Ty si niè nepametáš?
{52669}{52719}Len útrky
{52724}{52799}Chihiro volala moje meno|v tej temnote
{52805}{52901}Išiel som za jej hlasom|a som sa zobudil tu...
{52911}{52959}Chihiro, ha...
{52961}{53028}Jej pravé meno je Chihiro?
{53057}{53126}Nieje to silnejšie ne láska...
{53215}{53289}Toto zlato|ledva pokryje škody
{53292}{53361}Ta bláznivá Sen!|Stojí ma majetok
{53373}{53463}Ale, Sen nás nakoniec zachránila
{53465}{53493}Ticho!
{53496}{53554}Taktie to zaèala.
{53556}{53612}A teraz utiekla
{53615}{53675}A opustila aj|svojich rodièov!
{53675}{53794}Z jej rodièov u musia by celkom tuèné prasce|Bude z nich slanina alebo šunka
{53795}{53834}Prosím poèkajte
{53861}{53888}Majster Haku!
{53892}{53944}Èo, ty si stále naive?
{54003}{54082}Stále to nevidíš e si|stratila nieèo cenné?
{54095}{54162}Nejakı si plnı sily
{54165}{54224}Odkedy somnou takto vyprávaš
{55463}{55510}Diea...
{55653}{55692}Diea!
{55694}{55729}Je to len piesok!
{55730}{55790}Diea!
{55801}{55892}Kde si. Dieatko!
{55901}{55964}Vylez, prosím!
{55981}{56012}Dieatko!
{56091}{56146}Dieatko, Dieatko!
{56257}{56364}Ty!
{56395}{56475}Hovor!
{56511}{56610}Kde si ukryl moje diea?
{56621}{56664}Je zo Zenibou
{56668}{56715}Zeniba?
{57219}{57308}Take to tá èertovská èarodejnica
{57312}{57375}Ona si myslí e ma porazila
{57415}{57468}Take, akı je plán?
{57478}{57530}Prinesiem diea spä
{57533}{57635}Ale navımenu, vrátiš Sen a|jej rodièov do ¾udského sveta
{57641}{57696}A èo bude s tebou?
{57703}{57791}Povedzme e a roztrhám na kúsky|potom èo ich pošlem spä!
{58915}{58964}Myslím e sme tu správne...
{58985}{59016}Poïme
{59660}{59705}Môeš sa odvies na mojom pleci
{61586}{61628}Poïte ïalej
{61744}{61787}Prepáète nám
{61834}{61892}Tak, poïte rıchlo dnu, teda
{61904}{61935}Poï
{62014}{62057}Take ste to všetci zvládli
{62060}{62074}Um...
{62077}{62119}Posaïte sa
{62122}{62180}Urobím vám trocha èaju
{62316}{62416}Zeniba, Haku vám toto ukradol|Priniesla som to spä
{62496}{62553}Vieš ty vôbec èo je to?
{62562}{62633}Nie, ale viem e je to ve¾mi cenné
{62636}{62722}Som tu aby som sa ospravedlnila za Haka|Prepáète mu
{62738}{62817}Cítila si sa dobre keï si to drala?
{62820}{62842}Èo?
{62845}{62909}Èo je to?|Kúzlo je preè
{62918}{63013}Je mi to ¾úto|Zašliapla som toho chrobáka
{63016}{63070}Bol na tej peèati|a rozpuèila som ho
{63073}{63124}Rozpuèila!
{63154}{63253}Vieš, to moja sestra nakazila|tım chrobákom toho draka,
{63256}{63324}aby ho mohla ovláda
{63327}{63387}Rozpuèila ho!
{63454}{63496}Tu sa posaï
{63499}{63564}Ty si Mu bez tváre, nie?|Ty sa tie posaï
{63589}{63677}Och, um, prosím vráte|im spä ich podobu
{63680}{63754}Preèo moja drahá,|však kúzlo u dlho nepôsobí
{63757}{63815}Môu sa premeni aj sami keby chceli
{63990}{64081}Ja a sestra sme dve rôzne polovièky,|ale nevychádzame spolu dobre
{64084}{64146}Videla si|akı mala zlı vkus
{64149}{64223}Dvojèatá èarodejníc sú|ako recept na problémy
{64320}{64427}Rada by som ti pomohla drahá,|ale nemôem niè robi
{64430}{64477}Je to jeden z našich zákonov
{64490}{64604}Budeš sa musie postara o svojich|rodièov a toho draèieho priate¾a sama
{64607}{64675}Ale, um, nemôete|mi aspoò poradi?
{64686}{64771}Cítim ako by sme sa s Hakom,|kedysi dávno stretli
{64775}{64819}V tom prípade to je jednoduché
{64828}{64891}Niè èo sa stalo,|sa nedá zabudnú,
{64894}{64965}aj keï si nato|nemôeš akurát spomenú
{64978}{65057}Je u dos neskoro|Preèo neostaneš na noc?
{65068}{65135}Pomôte mi chlapci
{65282}{65329}Neprestávajte
{65402}{65503}Tak je to správne, Ste úasnı|Ste ve¾ká pomoc...
{65524}{65601}Ani mágiou|by som to lepšie nespravila
{65634}{65737}Pretiahneš to tade...|A znovu
{65743}{65806}Naozaj u musím ís domov, starká
{65821}{65904}Haku môe umrie|a ja si tu len tak sedím...
{65909}{65993}Môu zjes moju mamu a otca!
{66046}{66112}Ešte chvı¾ku vydr
{66115}{66150}A je to
{66172}{66225}Zavia si s tım vlasy
{66338}{66369}Je to prekrásne
{66370}{66486}Ochráni a to|Spravila som to z vlákna ktoré upriadli
{66494}{66531}Ïakujem
{66754}{66846}Akurát naèas|Máme ïalšieho hosa, pusti ho dnu
{66849}{66875}Áno
{67194}{67219}Haku!
{67250}{67287}Haku!
{67298}{67335}Vïaka bohu
{67344}{67403}Niesi ranenı?|Si urèite vporiadku?
{67410}{67432}Vïaka bohu
{67478}{67532}Dobré naèasovanie, musím poveda
{67548}{67607}Pozri starká. Haku je naive
{67620}{67719}Haku, u sa nateba nehnevám|preto èo si mi spravil
{67722}{67801}Len mi s¾úb e ochrániš toto dievèa
{67812}{67881}OK, chlapci. Je èas ís domov
{67884}{67934}A príïte zase
{67952}{68056}Ty tu môes osta|a pomáha mi
{68116}{68137}Starká!
{68154}{68205}Ïakujem vám za všetko
{68208}{68282}Som si istá e|sa ti to podarí
{68285}{68363}Moje pravé meno je Chihiro
{68366}{68425}Chihiro... Aké pekné meno
{68428}{68476}Daj si naòho pozor,|je len tvoje
{68479}{68492}Dám!
{68496}{68539}Tak u choï
{68580}{68653}Ïakujem starká|Dovidenia
{69832}{69871}Poèuj, Haku
{69874}{69959}Moc si nato nepametám, ale|moja mama mi vravela...
{69969}{70055}e raz, keï som bola malá,|spadla som do rieky
{70068}{70155}Vravela e ju vysušili|a postavili tam nieèo
{70164}{70215}Ale práve som si spomenula
{70242}{70281}Tá rieka sa volala...
{70292}{70367}Jej meno bolo Kohaku
{70382}{70459}Tvoje pravé meno je Kohaku
{70972}{71007}Chihiro, ïakujem ti
{71010}{71086}Moje celé meno je|Nigihayami Kohaku Nushi
{71100}{71123}Nigihayami?
{71126}{71180}Nigihayami Kohaku Nushi
{71183}{71242}Krásne meno|Znie tak bosky
{71252}{71357}Tie si nato spomínam, ako|si domòa spadla keï si bola diea
{71360}{71400}Stratila si topánku
{71412}{71511}Áno, odnieso¾ si ma|do plytkej vody, Kohaku
{71532}{71579}Som ti ve¾mi vïaèná...
{72348}{72381}Vrátili sa!
{72700}{72771}Priniesol si mi spä moje diea?
{72834}{72856}Bába!
{72859}{72964}Niè ti nieje?|Jak strašne ti asi muselo by
{72995}{73068}Dieatko, u dokáeš stá samo na nohách?|Odkedy?
{73084}{73135}Yubaba, s¾úbila si
{73138}{73206}Prosím vrá Chihiro s rodinou|do jej sveta
{73220}{73279}Nie tak rıchlo
{73282}{73353}Tento svet má svoje pravidlá!
{73372}{73399}Ticho!
{73403}{73463}Bába, akı lakomec|Urob to
{73472}{73531}Dieatko sa malo velmi dobre
{73544}{73611}Ale, pravidlá su pravidlá
{73614}{73668}Inak nemôem zruši kúzlo
{73670}{73759}Ak sa kvôli tebe Sen rozplaèe,|U a nebudem ma viac rád
{73762}{73789}Preèo, to je...
{73792}{73826}Starká
{73829}{73857}Starká!?
{73868}{73915}Idem zatebou
{74190}{74245}Haku mi povedal všetko o tıch pravidlách
{74248}{74292}Prinajmenšom, máš odvahu
{74295}{74372}Tu je tvoja zmluva|Poï sem
{74376}{74433}Bude to len chvı¾ka diea
{74452}{74483}Neboj sa
{74590}{74681}Pozri sa... Èi uhádneš|ktorı z nich sú tvoji
{74906}{74941}Máš iba jeden pokus
{74944}{75005}Uhádni, a všetci ste vo¾nı
{75292}{75377}Starká, nieèo tu nesedí|Moji rodièia tu niesu
{75386}{75467}Niesu?|To je tvoja odpoveï?
{75506}{75529}Áno
{75598}{75675}Bingo!
{75678}{75738}To je ale dievèa!|Správne!
{75832}{75863}Ïakujem vám. Všetkım
{75866}{75944}Choï! Vyhrala si|Môeš odís!
{75956}{76001}Ïakujem vám za všetko
{76018}{76049}Dovidenia
{76068}{76093}Ïakujem
{76096}{76121}Príï zas
{76130}{76143}Haku
{76147}{76170}Poïme
{76188}{76217}Kde je otec a mama?
{76220}{76249}Išli napred
{76432}{76463}Voda je preè!
{76466}{76502}Ja u ïalej ís nemôem
{76514}{76570}Vrá sa kade|si prišla, Chihiro
{76573}{76646}Ale neobzeraj sa spä,|dokia¾ nebudeš za tunelom
{76652}{76700}A èo bude s tebou, Haku?
{76712}{76779}Porozprávam sa s Yubabou|Skonèím s uèením
{76782}{76841}Budem vporiadku. Teraz,|keï mám spä svoje meno
{76856}{76899}Vrátim sa spä do svojho sveta
{76902}{76936}Stretneme sa ešte?
{76939}{76958}Som si istı
{76961}{76975}S¾ubuješ?
{76978}{77000}S¾ubujem!
{77003}{77062}Teraz choï, a neobzeraj sa spä
{77608}{77643}Chihiro!
{77654}{77715}Kde si bola?|Poï rıchlo
{77802}{77845}Mami! Oci!
{77848}{77890}Nemôeš si len tak odbehnú kam chceš
{77893}{77924}Ideme preè
{77936}{77987}Mami, urèite si vporiadku?
{77990}{78092}Èo? Sahovacie auto|tam u urèite je
{78317}{78371}Poï rıchlo, Chihiro
{78580}{78621}Pozor kam stúpaš
{78624}{78704}Chihiro, Potknem sa ak sa|namòa budeš takto veša
{78997}{79032}Koniec tunela
{79042}{79072}Hej...
{79080}{79111}Èo je to?
{79132}{79177}Èo sa tu stalo?
{79204}{79263}Je to tu celé zaprášené.
{79266}{79285}Nejakı vtip?
{79288}{79314}Myslíš?
{79317}{79376}Vravela som ti aby si tu nezastavoval
{79510}{79569}OK. Poïme
{79600}{79653}Odchádzame, Chihiro
{79656}{79722}Chihiro, poï rıchlo!
{80370}{80500}Krièí to niekde hlboko v mojom srdci
{80510}{80640}Chcem ma vdy ten vzrušujúci sen
{80650}{80780}Je tu ve¾a smútku
{80790}{80925}No aj tak a je v òom vidie 
{80950}{81060}Vdy niekto môe spravi chybu
{81065}{81200}Niekto iste pozná to modré na nebi
{81208}{81340}Èo vypadá ako cesta bez konca
{81348}{81480}Ale v tıchto rukách moe by svetlo
{81535}{81665}Moje tiché srdce v èasoch lúèenia
{81675}{81805}Prázdne telo naèúva pozorne
{81815}{81950}Záhada ivota, a tajomstvo smrti
{81955}{82100}Je to rovnaké pre kvety, vietor a mestá
{82725}{82850}Krièí to niekde hlbko v mojhom srdci
{82860}{82988}Vytvorme si vlastnı sen vdy èas od èasu
{82996}{83123}Radšej ako pozera na ten smútok naokolo
{83129}{83270}Poïme nene spolu spieva
{83286}{83410}V uzavretıch spomienkach
{83415}{83540}Vdy poèujem tvoj šepot,|na ktorı nechcem zabudnú
{83546}{83675}Dokonca aj na rozbitom zrkadle
{83683}{83815}Sa nová krajina môe odrazi
{83875}{84000}A hneï z rána zaèa odzaèiatku|Cez pokojné okno
{84010}{84141}Naplni to telo èo všetko stratilo
{84150}{84272}U viac nato nechcem èaka|pozeraním na more
{84280}{84405}Však to¾ko skvelıch vecí tu vdy bolo
{84410}{84585}A našla som ich sama.
{84688}{84768}Anglickı preklad:|Linda HOAGLUND, Judith ALEY,
{84771}{84850}MORlYOSHl Ha'ruyo|a Steve ALPERT
{84853}{84932}Anglické titulky:|Aura & Nippon Cine Arts
{84940}{85200}Slovenské titulky: Killerko|EMAIL: killer@ultranet.sk|URL: http://killerko.host.sk
{85330}{85437}Koniec
