{1}{1}23.980
{148}{215}Ahoj nee-chan. Nevolali sme si roky.
{234}{279}Je skvelé to poèu od teba, Yuuta.
{295}{341}Myslela som, e budeš nostalgickı.
{360}{386}Zrejme nie.
{397}{442}Neporovnávaj ma s tebou.
{488}{568}Tvoj jazyk sa pred dvoma tıdòami zhoršil.
{596}{660}Hovor mi Aneki (staršia sestra).
{690}{755}Dovo¾ mi predstavi a mojím priate¾om.
{768}{810}Poèkaj.
{956}{1001}Toto je moja staršia sestra!
{1106}{1166}Je mi potešením. Som Joshua Grant.
{1181}{1231}Yuuta je veselı brat v okolí.
{1248}{1351}ije školou a prácou kadı deò. |Netreba sa o neho bá.
{1410}{1450}Ïakujem.
{1503}{1583}Som Haruya Kobayashi z Tokia.
{1606}{1646}Pohni a predstav túto èas!
{1662}{1687}Správne.
{1703}{1741}Ospravedlòujem sa za ten hluk.
{1760}{1801}To je v poriadku.
{1825}{1851}Na rade je Henri.
{1943}{1994}Som Henri-Hugues de Saint Germian.
{2045}{2096}Teší ma. Som Yuutova sestra.
{2173}{2192}Mono...
{2192}{2217}Ahoj!
{2251}{2293}Som Alfred Visconti.
{2306}{2332}Hovor mi proste Red.
{2372}{2402}Som Sylvain Clark.
{2402}{2453}Neskoèil som!
{2473}{2552}Chápem. Neèudujem sa, e Yuuta |o tebe hovoril s takou pıchou.
{2571}{2600}To u nerobím.
{2610}{2662}Yuuta o tebe vdy rozpráva.
{2675}{2690}Huh?
{2703}{2772}Hovorí, e si jemná, starostlivá a ve¾mi spo¾ahlivá.
{2791}{2813}Sylvain!
{2847}{2890}Nikdy som tie veci nepovedal!
{2907}{2929}Hej hej.
{2991}{3070}Prosím pomô mi ako matka a zvyšok sa vydarí.
{3086}{3135}Znova ti zavolám. Ahoj.
{3252}{3440}TaSHee's Gang uvádí|MARGINAL PRINCE
{5741}{5770}Si... Yuuta?
{5863}{5888}Páèi sa ti tá kresba?
{6014}{6077}Chcel by si sa uèi kresli?
{6127}{6141}Áno.
{6168}{6237}Mám jednoduchı motív študova na štúdiu v zahranièí.
{6325}{6399}Na ostrove v Atlantiku, ktorı je a moc| malı na to aby ste ho zbadali na mape,
{6446}{6497}všetci mui navštevujú školu| nazıvanú Akadémia Svätého Alfonsa
{6509}{6575}klamstvá sú tu oddelené od vonkajšieho sveta.
{6649}{6691}Nikto nevie kedy to zaèalo.
{6707}{6764}Ale záhadní študenti sú prezıvaní
{6811}{6891}Marginal Prince.
{6961}{7051}NEFRITOVÁ ŠKOLA
{7094}{7224}Nikdy som si nemyslel, e toto miesto bude také oèarujúce.
{7299}{7371}Takı ignorantskı chlap, èo robí hore krstiny.
{7391}{7427}Ï-ïakujem.
{7443}{7506}Pracuj ako, Marginal Prince.
{7730}{7839}Pracova ako? Mám....kráèa.
{8126}{8175}Potom som stretol...
{8282}{8308}...princov.
{8623}{8666}Si...Yuuta?
{8698}{8713}Áno.
{8744}{8886}Som Joshua – Študentskı zástupca.|Vitaj na Akadémii Sv. Alfonsa.
{8976}{9048}Prvı princ jazdil na bielom koni.
{9086}{9105}Nasadni.
{9105}{9123}Huh?
{9123}{9145}Poï.
{9163}{9178}Áno...
{9277}{9356}P-poèkaj chví¾oèku.
{9570}{9585}Sme tu.
{9681}{9716}T-toto je škola?
{9764}{9781}Èo sa deje?
{9797}{9885}Niè. Je trochu odlišná od ostatnıch škôl,| ktoré som navštevoval...
{9912}{10009}Tie si myslím. Má len 200 rokov a stále vyzerá novo.
{10076}{10091}Tadeto.
{10110}{10119}Áno.
{10431}{10513}Toto je kresba korunovácie Krá¾a Alfonsa.| Je to neskutoèná práca.
{10528}{10559}Krá¾ Alfonso?
{10582}{10676}Sú rôzne príbehy o tom ako sa priplavil na ostrov.
{10812}{10870}Je to akoby všetci boli ve¾mi.... Podobní.
{10888}{10939}Má rovnaké meno ako škola.
{10955}{11025}Namiesto toho aby sme ho volali krá¾om |by sme mohli poveda, e bol aj otrasnı jazdec.
{11281}{11365}Je to skutoènı šperk.
{11449}{11478}Èo sa deje?
{11501}{11559}Je toto... japonskı zvyk?
{11578}{11616}Nie je to tak, e neschva¾ujeme obuv...
{11661}{11713}Zabudol som, e tu nenosia topánky.
{11738}{11776}Nic. Opravdu nic.
{11813}{11854}Si ve¾mi zaujímavı Yuuta.
{11894}{11925}Ïalej pôjdeme okolo kninice.
{11951}{11966}Iste!
{11989}{12039}Prosím poèkaj!
{12198}{12220}Toto je skvelé!
{12264}{12311}Kninica je taká ve¾ká.
{12434}{12470}Predstavím ti ho, Haruya.
{12494}{12527}Yuuta práve prišiel.
{12541}{12579}Teší ma, e a spoznávam.
{12652}{12691}Som Haruya. Teší ma.
{12711}{12729}Si Japonec?
{12742}{12764}Áno.
{12778}{12793}Skutoène.
{12819}{12870}Podnebie na Alfonsovom ostrove nie je zlé.
{12891}{12916}Vzduch je sviei.
{12936}{12980}Myslím, e si to zamiluješ.
{13008}{13084}Musíš vedie kto je hlavná rodina, keïe si Japonec, Yuuta.
{13105}{13130}Haruya je jednım z nich.
{13167}{13197}Nie som, Joshua.
{13209}{13256}Mohol by to by môj otec.
{13273}{13314}Pravda. Prepáè.
{13338}{13386}Nemôem by hlavnı.
{13543}{13630}Zdalo sa, e druhı princ je z hlavnej rodiny.
{13674}{13741}Študenti navštevujú hodiny |vo vıskumnıch izbách profesorov.
{13764}{13798}Èo triedy?
{13811}{13828}Triedy?
{13853}{13932}Nerozlišujeme medzi vıbavou triedy.
{13966}{14013}Študenti navštevujú triedy, ktoré ich zaujímajú.
{14023}{14055}Tie si sami zariaïujú osnovy.
{14146}{14181}Je to Clark?
{14206}{14270}Tretí princ je Otaku.
{14289}{14328}Vydr. Èo to robíš?
{14339}{14420}Toto zajaèie monštrum sa objavilo| v prvej minúte 36. epizódy.
{14451}{14504}To je ve¾mi zvláštne. Voláš ho víaznı |maniak alebo nieèo podobné?
{14526}{14570}Neoèakával som to tu.
{14592}{14609}To...
{14620}{14633}Sylvain.
{14664}{14696}Ospravedlòujem sa. Neuvedomil som si...
{14727}{14755}Som Sylvain Clark.
{14829}{14848}Som Yuuta...
{14869}{14920}Toto nie je èas na také veci, Joshua.
{15150}{15207}Prepáè. Nieèo sa stalo.
{15228}{15254}Ospravedlòujem sa, Yuuta.
{15290}{15304}Hej...
{15362}{15380}Adieu.
{15470}{15524}Èo s ním....bolo.
{15602}{15696}Mali by to by dvere ubytovne priamo tu.
{15927}{15963}Èo je to?
{15977}{16005}Kto si?
{16039}{16082}Ja..Ja...
{16109}{16168}Zabudni na to. Zmizni odtia¾to.
{16261}{16282}Èo s ním je?
{16467}{16489}Taká nepríjemnos.
{16507}{16582}Štvrtı princ bol èudnı a nepríjemnı èlovek.
{16641}{16665}Odchádzam.
{16736}{16757}Èo sa mu stalo.
{16770}{16800}Preèo bol takı arogantnı?
{16820}{16881}Na tejto škole sú všetky druhy ¾udí.
{16977}{17025}Pozeraj sa kam ideš.
{17063}{17086}P-prepáè!
{17147}{17179}Zaujímavá osoba.
{17221}{17312}Èo je to? Mám pocit, e ho poznám.
{17361}{17375}Poslednı piráti
{17431}{17481}To je Alfred Visconti.
{17526}{17590}Uznal som ho. Je to tak dlho.
{17610}{17631}Maj sa.
{17673}{17768}Piaty princ je celebrita.
{18105}{18165}Koneène som tu.
{18326}{18385}Èakal som na vás, Yuuta-sama.
{18442}{18478}Šiesty je...
{18586}{18641}Yuuta....sama?
{18717}{18811}Nechajte ma predstavi sa.| Som váš majordómus.
{18836}{18919}Platia mi za to, e sa starám o všetkıch Pánov.
{18937}{18985}Tešilo ma vás spozna.
{19001}{19098}Prídem vás vyzdvihnú, keï bude veèera pripravená.
{19384}{19465}Som na skvelom mieste.
{19516}{19533}Nee-chan.
{19919}{19934}Yuuta.
{19960}{19977}Joshua!
{20007}{20041}Ospravedlòujem sa ti za to, èo sa dnes stalo.
{20059}{20102}Som na tvojej ubytovni.
{20133}{20168}Nechaj ma predstavi ti ostatnıch.
{20185}{20265}Stretol si Sylvaina a Haruyu.
{20302}{20334}Toto je Alfred Visconti.
{20357}{20388}Všetci mu hovoria Red.
{20417}{20446}Áno. Predchví¾ou...
{20503}{20537}Hmm?
{20566}{20604}Toto je Henri- Hugues de Saint Germain.
{20634}{20695}Teší ma.
{20725}{20778}Nie je tu nikto ïalší?
{20824}{20856}Sme tu len my.
{20880}{20980}Èo? Na takej ve¾kej ubytovni je len 6 ¾udí?
{21199}{21241}To je èudné.
{21265}{21349}To je zlé.
{21996}{22086}Preèo sú všetci iní ako predtım?
{22108}{22160}Chcel by ste nejaké víno, Yuuta-sama?
{22177}{22257}Som neplnoletı. Nepotrebujem to.
{22632}{22693}Môeš mi poveda, ak to u viac nemôeš znáša.
{22730}{22790}Všetci si myslia, e to urobil.
{22834}{22883}Èo? Hovoríte o mne?
{22898}{22956}Tú záleitos sme u vyriešili, Red.
{23001}{23099}Vyuili sme to v Manmente. |Novı šperk príde zajtra.
{23134}{23218}Máme náhradné riešenie problému. To je..
{23231}{23255}Je to školskı majetok.
{23282}{23326}Èo? O èom to rozprávate?
{23349}{23410}Konali sme pod¾a pravidiel.
{23432}{23455}To je celé.
{23488}{23576}Stále si elitnı študent, študentskı zástupca.
{23597}{23640}Nesmieš skrıva podradnı tovar za šperkami.
{23663}{23684}Šperky?
{23701}{23780}Je to tak vzrušujúce, e nieèo| také sa stalo blízko teba.
{23800}{23832}N-nieèo?
{23941}{23965}Yuuta?
{24002}{24023}To je tak sprosté!
{24070}{24125}Odovzdaj to a necháme a ís, keï nám to dáš.
{24142}{24188}Tak o èom to hovoríš?!!
{24202}{24255}Poï so mnou, idiot.
{24302}{24341}Vydr chví¾u. O èo ide?
{24440}{24466}Èo chceš?
{24474}{24495}Pozri sa.
{24521}{24542}Na èo?
{24656}{24713}Šperk... zmizol.
{24750}{24770}To som nebol ja.
{24789}{24834}Kráde nie je ve¾kı problém.
{24878}{24941}Keïe si neprivlastòujeme prive¾a hmotnıch vecí.
{24974}{25084}Neh¾adáme vinníka, keï nieèo zmizne.
{25116}{25189}Kradnutie na tejto škole je zvláštne,
{25208}{25265}pretoe tu nie je nikto kto |potrebuje kradnú veci ostatnıch.
{25286}{25334}Tento šperk zmizol.
{25360}{25405}Hneï ako si sa tu objavil.
{25422}{25452}Ako je to moné?
{25465}{25519}To nie je dôleité!
{25530}{25563}Vrá ho!
{25581}{25624}Nevzal som ho! Tak ako ho mám vráti?!
{25644}{25671}Ty idiot!
{25730}{25755}To staèí!
{25817}{25838}Dos.
{25874}{25919}Ïakujem vám všetkım.
{25949}{25967}Joshua.
{26023}{26094}Prepáè za to, èo sa stalo.
{26138}{26165}Neber si to k srdcu.
{26182}{26218}Je to len šperk.
{26248}{26275}Bol premiestnenı.
{26298}{26338}Poïme spä.
{26355}{26371}Zavesenı.
{26392}{26441}Kat.
{26524}{26563}Bude to v poriadku.
{26594}{26625}Ten portrét vyzerá ako...
{26649}{26692}Je to Joshuov...
{26902}{26976}Skutoène sa ospravedlòujem, e si to musel |znáša aj keï si sem ešte len prišiel.
{27008}{27076}Zabudnime na to a poïme ïalej, odteraz to bude dobré.
{27160}{27230}Skutoène sa môeme posunú vpred?
{27488}{27507}Joshua?
{27953}{28093}Keï sme sa prvı krát stretli,
{28112}{28226}všetko sa rozsvietilo.
{28270}{28408}Vdy si bol po mojom boku,
{28433}{28550}usmieval si sa na mòa.
{28576}{28641}Bezsenná noc,
{28653}{28719}ticho šepká.
{28736}{28871}Rozhovor s tebou je plnı lásky.
{28894}{29038}V noci v našich snoch stretneme ostatnıch.
{29057}{29239}Dobre si odpoèiòme.
{29335}{29435}Dúfam, e na teba táto pieseò dosiahne.
{29487}{29610}Aj keï si tak ve¾mi ïaleko.
{30166}{30179}Preèo?
{30193}{30223}Preèo som si to nevšimol?
{30254}{30278}Dalo mi to tak ve¾a námahy prís a študova tu.
{30303}{30327}Èo som to za idiota?
{30349}{30406}Mohol som to vidie v jeho oèiach...
{30533}{30601}Bolo to...Joshua túil po tej kresbe.
{30881}{30898}Yuuta-sama.
{30928}{30954}Áno?
{30975}{31000}Dobré ráno.
{31050}{31075}Naozaj sa ospravedlòujem.
{31075}{31150}Prijatie Yuuty-sama bolo zamietnuté.
{31317}{31351}P-poèka.
{31360}{31380}To nemôe by skutoènos.
{31408}{31430}Èo?!
{31442}{31494}Moje prijatie sa zamietlo?!
{31745}{31800}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime
{31800}{31897}www.mycolorfullife.blog.cz
{33717}{33830}V další epizodì:
{33848}{33940}S Yuutou bylo zacházeno jako se zloèincem|a jeho pøijetí bylo odmítnuto.
{33998}{34076}Objevil se pøed ním novı Marginal Prince.
{34162}{34225}Pøíštì: Drahokam pøed úsvitem
{34288}{34359}Svìtlo dungle svítí na zloèince.
