{1}{1}23.980
{147}{189}Nemùeš to øíkat takhle, Aneki.
{202}{245}Jinak bys tomu nerozumnìl.
{270}{300}V kadém pøípadì, nejsem dítì.
{312}{338}Rozumím tìmto vìcem.
{354}{369}Kdo ví.
{421}{462}Není divu, to je Yuutova sestra.
{494}{580}Yuuto, slyšel jsem, e tenhle |drák na mobil byl od tebe.
{599}{612}Opravdu?
{630}{657}Je hroznì roztomilı.
{680}{762}Je tìké tohle najít kdekoli mimo Japonsko.
{779}{810}Japonsko je úasné.
{824}{852}Taky chci jet do Japonska.
{870}{927}Sylvain byl v Japonsku?
{942}{970}Odmìnou za práci mıch rodièù,
{981}{1007}jsem tam jednou byl.
{1027}{1115}Vidìl jsem anime, manga a samurajské filmy.
{1138}{1216}Tato japonská zkušenost mi zmìnila ivot.
{1286}{1337}Navštívím tì, a pøístì navštívím Japonsko.
{1367}{1424}To moná taky zmìní mùj ivot.
{1459}{1530}C-c-co to povídáš, Sylvaine?
{1553}{1583}Sbohem, Aneki.
{1595}{1610}Zavìšuju.
{1641}{1851}TaSHee's Gang uvádí|MARGINAL PRINCE
{4218}{4293}Na ostrovì v Atlantském oceánu, kterı je|pøíliš malı na to, aby byl viditelnı na mapì,
{4340}{4383}všichni mui nastupují na školu|zvanou Akademie Sv. Alfonsa,
{4396}{4467}která leí zde odøíznuta od vnìjšího svìta.
{4541}{4583}Nikdo neví kdy to zaèalo.
{4603}{4657}Ale záhadní studenti jsou zde navzájem nazıváni
{4700}{4783}Marginal Prince.
{4843}{4936}SLUNEÈNÍ PØEDEHRA|(Vorspiel je nìmecky pøedehra, úvod.)
{5625}{5689}V tomto testu, je prohrávající ta|strana, která udìlá první krok.
{5760}{5792}Co to vy dvì dìláte?
{6738}{6752}Yuuto!
{6760}{6781}Jsi v poøádku?
{6813}{6845}Vem ho na oèetøovnu.
{7159}{7194}Snímání CT.
{7214}{7256}Zobrazovací test magnetické rezonance.
{7283}{7331}Snímací test magnetické rezonance.
{7355}{7386}Všechno je normální.
{7458}{7532}Je to... Nemocnice?
{7555}{7572}To je ošetøovna.
{7724}{7753}To je ta hrùzostrašná osoba.
{7775}{7822}Udeøil jsi se do hlavy a všechno si's popletl.
{7846}{7881}Nebo je to tvoje pøirozené já.
{7918}{7990}Jsem školní doktor.|Jsem také poradce.
{8023}{8081}Stanislav Sokurov.
{8173}{8203}Dej si naèas s odpoèinkem.
{8232}{8282}Mùeš jít zpátky kdykoli si to budeš pøát.
{8298}{8322}D-dobrá.
{8449}{8502}Nemám ani pomyšlení na to, co mi øekl.
{8735}{8761}Odkud to pøichází?
{8990}{9004}Pláèe to.
{9030}{9096}Omlouvám se, já...
{9138}{9180}T-to je v poøádku.
{9209}{9223}Omlouvám se.
{9373}{9391}Odešel.
{9441}{9483}Byl jsi ošklivì zranìnı, Yuuto.
{9500}{9557}Je mi fajn. Doktor øekl, e je všechno normální.
{9585}{9626}To je pravda.|Tak to mùeš urovnat s Haruyou.
{9716}{9746}H-hrát?!
{9764}{9801}Myslím, máš v úmyslu bojové scény.
{9815}{9843}Bojové scény.
{9857}{9901}Samurajské filmy mají scény, kde se navzájem zabijí.
{9916}{9952}Jako takhle, a takhle.
{9969}{10035}Mám to rád.
{10060}{10129}Tak jsem poádal Haruyu, aby mì uèil.
{10162}{10204}Tak jsme si vlastnì hráli.
{10222}{10319}Coe? Myslel jsem, e jste |doopravy bojovali a znepokojil jsem se.
{10362}{10386}Promiòte za vyšení.
{10403}{10437}Je tu pro vás telefonní hovor.
{10487}{10506}Sylvaine.
{10543}{10553}Pro mì?
{10577}{10594}Vezmu si to.
{10724}{10785}Není pøíliš èasté, e Sylvain vere telefon.
{10807}{10875}Vdycky to bıvá mùj otec.
{10904}{10948}To znamená jak moc si o Reda dìlá starosti.
{10975}{10991}Opravdu?
{11012}{11071}Nemám pocit, e opìtovné znepokojení je dobrá vìc.
{11085}{11190}Moje sestra se znepokojuje u všeho.
{11226}{11268}Zachází se mnou jako s dítìtem.
{11291}{11349}Vzplane kdykoli je nešastná
{11360}{11436}a vdycky øíká, e to øekne mé matce.|(Yuuto.)
{11480}{11512}Je to tak zlé jak to mùete slíznout.
{11553}{11620}Nemyslím takhle.
{11643}{11680}Myslím, e tvoje sestra je úasná osoba.
{11695}{11748}Já mám jen starší bratry, take na tebe árlím.
{11763}{11797}N-nic takového.
{11814}{11860}Jestli je tohle pøípad, kdy ti|mùu dát cokoli chci.
{11901}{11943}Dobrá. Pøijmu tvou nabídku.
{11990}{12015}Víš, Rede?
{12043}{12081}Ona má právo vybrat.
{12096}{12119}Omlouvám se, Henri.
{12119}{12163}Je to moje fanynka.
{12189}{12236}Ale, fanynka tvıch filmù.
{12267}{12297}Není moc rozkošnı.
{12332}{12389}Ne moc lidí si myslí, e jsem rozkošnı.
{12408}{12427}Myslím, e to bude pøípad pro mnohé.
{12427}{12478}Tvoji rodièe a tvoji bratøi to musí pokládat|za nesnadné, myslet si, e jsi rozkošnı.
{12491}{12526}Naneštìstí, jsem jediné dítì.
{12553}{12598}Má matka zemøela a otce nemám.
{12636}{12706}Kdo mì bude pokládat za rozkošného?
{12724}{12771}Pøestaò si hrát s Redem, Henri.
{12820}{12838}Merci.|(Francouzsky: Dìkuji)
{12854}{12872}Jsem šastnı.
{12894}{12909}Ten kluk.
{12909}{12975}Co chceš, abych udìlal?
{12998}{13059}Nejsem na tebe dost tvrdı.
{13090}{13166}Co tvoji bratøi nebo rodièe, Joshuo?
{13208}{13219}Já?
{13246}{13266}Nejsou nic zvláštního.
{13266}{13318}To neøíkej. Øekni mi to.
{13361}{13416}No, jsem taky jedináèek.
{13433}{13495}Moji rodièe také zemøeli, kdy jsem byl malı.
{13522}{13573}O-omlouvám se, já...
{13648}{13695}Jsi opravdu sladkı.
{13762}{13804}Sluší ti to.
{13842}{13867}Jsem poddajnı.
{13892}{13951}Mùu to udìlat s nebo bez nich.
{14021}{14116}Nevìdìl jsem, e Joshuovi rodièe zemøeli.
{14178}{14188}Sylvain?
{14449}{14471}Tak vysoko.
{14494}{14525}Pojï, Yuuto.
{14549}{14588}Chytím tì. Jen skoè.
{14650}{14675}Byli jsme objeveni.
{14709}{14754}Kam plánuješ jít?
{14774}{14799}Ne,...
{14817}{14858}Nemyslel jsem, e bys šel ven.
{14882}{14919}Nejsi vhodnı na schovávání a pátrací hry.
{14998}{15047}Je to velmi blízko mìsta, kdy pùjdeme touto cestou.
{15075}{15105}Chceš jít do mìsta?
{15129}{15177}Dìlal Sylvain tohle celou dobu?
{15213}{15277}No, myslel jsem, e to mùeš øíct.
{15301}{15342}Nebo bys mìl øíct e ano, kdy máš dobrou náladu.
{15361}{15417}Kdybych to byl já, bylo by to problematické zavolat taxi.
{15468}{15521}Máme štìstí, e jelo auto kolem, kdy jsme venku.
{15605}{15682}Máte dobrou náladu, Senora.|Stalo se nìco dobrého?
{15733}{15773}Dnes je zvláštní den.
{15805}{15891}Opustili jste vy Marginal Prince rodièe, abyste tu zùstali?
{15912}{15945}Jedli jste dobøe?
{15986}{16058}Promiòte, taky mám syna.
{16077}{16160}Cítím nutkání zeptat se na to, kdy vidím|jiné dìti, které ijí daleko od domova.
{16186}{16248}Má sestra je více...
{16289}{16332}Jak dobrosrdeèná sestra.
{16349}{16365}A co tvoje rodina?
{16380}{16447}Máš nìjaké vzpomínky, kdy se o tebe rodièe starali?
{16487}{16575}Moji rodièe nikdy nebyli doma a |nikdy jsme netrávili èas spoleènì.
{16596}{16663}Má matka mì nechala bıt...
{16680}{16767}Co to povídáš?|Všichni rodièe se starají o své dìti.
{16793}{16865}I kdy jsou to jen neupøímné sliby.|Dìlej co chceš a nevracej se zpátky.
{16884}{16933}Vdycky budou šastní vidìt jejich dítì|vracet se domù.
{16947}{17007}Ne, pøejí si, aby se jejich dìti vrátlily domù.
{17033}{17083}To je moná to, co normální rodièe oèekávají.
{17102}{17142}Všichni rodièe jsou stejní.
{17159}{17208}Mám tvrdohlavou povahu.
{17230}{17292}Dìlám opak toho, co øíká.|Nakonec jsem øekla nìco neodvolatelného.
{17318}{17347}Opouštím tenhle dùm.
{17362}{17404}Ukáu ti, jak umím pøeít sám.
{17421}{17442}Dìlej si co chceš!
{17532}{17570}Pak odešel a nikdy se nevrátil.
{17570}{17651}Ale dnes se mùj syn vrací.
{17683}{17744}Mùeme na tomhle ostrovì znovu spoleènì ít.
{17760}{17784}Urovnala jste to?
{17808}{17876}Aha. Není divu, je to zvláštní den.
{18282}{18373}Moc se omlouvám, mít Marginal Prince jako vıpomoc.
{18393}{18456}Svezla jste nás a zpívala nám.
{18484}{18504}Je to malá vìc.
{18522}{18537}Správnì, Yuuto?
{18552}{18599}Ano, Tetièka zpívá dobøe.
{18624}{18675}Nesuïte mùj vzhleded.|Vlastnì jsem zpìvaèka.
{18700}{18738}Jestli si vzpomenete na Senoru Martu,
{18738}{18782}udìlám si nìjakou popularitu.
{18797}{18846}Zpívám v tom Kulturním Domì.
{18875}{18945}Jaká náhoda. Taky tam jednou za èas zpívám.
{18968}{19016}Je to skupina zvaná Dead Prince.
{19038}{19067}Opravdu?
{19091}{19177}Kde bychom mìli povìsit tn vıvìstní štít, Marta-san?
{19201}{19218}Dìkuji.
{19233}{19387}Rozhodla jsem se u dávno, e bych poèkala| na návrat svého syna a povìsíme to spoleènì.
{19420}{19471}U nejsem mladá, myslím, e se moc znepokojuju.
{19489}{19524}Váš syn je šastlivec.
{19542}{19605}Opravdu chci, aby to slyšel.
{19801}{19828}Jak krásné mìsto.
{19847}{19884}Je tu Yuuta poprvé?
{19908}{19950}Mám tohle místo hodnì rád.
{19981}{19990}Eh...
{20157}{20170}To je on.
{20202}{20271}On mi vypomáhal, kdy chybìl klenot.
{20305}{20332}Yuuto!
{20463}{20477}Jak se máš?
{20638}{20665}Jsi zpátky, Carlosi.
{20710}{20771}Slyšel jsem, e se váš syn vracel, Senoro Marto.
{20798}{20864}Mùeš se vrátit. My u si navzájem nedluíme.
{20968}{21048}Tady je vpøedu úasná restaurace.|Chce to vyzkoušet!
{21100}{21136}Vezmìme to zkratkou.
{21157}{21183}Co to dìláte?
{21242}{21268}Nechte toho.
{21347}{21357}Marto-san.
{21418}{21431}Sylvaine.
{21440}{21520}Vypadají velcí a silní.
{21546}{21589}Pøedejme to policii.
{21605}{21633}To neudìláš.
{21645}{21718}I kdy pùjdeme, nemùeme pøíliš pomoct.
{21735}{21768}I tak, nemùeme se nadarmo dívat.
{21786}{21841}Nikdy jsem nepøedpokládal, e Sylvain |øekne ty chladná slova.
{21889}{21935}To je dost ctiádostivı vıvìsní štít.
{21965}{22004}Pøestaòte s tím. To je...
{22069}{22105}Nemùete to udìlat. Ten vıvìsní štít...
{22123}{22238}Rozhodla jsem se u dávno, e bych poèkala| na návrat svého syna a povìsíme to spoleènì.
{22280}{22296}Nechte toho!
{22393}{22435}Jen tohle... Jen tohle...
{22460}{22474}Marto-san!
{22572}{22632}Jen tohle... Jen tohle...
{22673}{22697}Matko!
{22728}{22742}Carlosi.
{22760}{22797}Nechte toho. Nedìlejte nic mé matce.
{22824}{22886}Nic neudìláme, kdy pùjdeš s námi.
{22908}{22960}Budeme hrát jak máme ve zvyku.
{22986}{23073}Odmítám. Kdo by pøedal svého syna?
{23099}{23114}Jdi do prdele!
{23170}{23208}U nejsem osoba, kterou jsem byl.
{23227}{23236}Odejdi.
{23254}{23265}Opravdu?
{23351}{23391}Pøestaò. Øekla jsem pøestaò.
{23445}{23467}Matko, uteè.
{23523}{23599}Vypaøádám se s nimi.
{23614}{23630}Carlosi.
{23695}{23729}Rychle, Matko!
{23754}{23847}Která Matka by opustila své dítì a utekla?
{23883}{23898}Ztra se!
{24712}{24795}Vdycky mì pøekvapíš.
{24811}{24824}Sylvaine.
{24880}{25033}Obdivuju tvùj nevinnı úsmìv.
{25033}{25096}(Mám rád tvou odvahu. Tvá láska pøinutí svìt jít oklikou.)|Kdo je to?
{25132}{25155}Chceš s náma bojovat?
{25212}{25242}Moná je to vychloubaèné, ale je to pravda.
{25242}{25293}Nech mi ukázat ti nìjakou barvu.
{25378}{25532}Los Angeles, Berlín, Shanghai...|Má cestovní trasa má mnoho zastávek.
{25561}{25702}To je poprvé|(Perfektní milenec)
{25735}{25787}jsi mùj nejdraší!
{25805}{25853}Láska pøinutí svìt jít oklikou.
{25870}{25946}Nikdy jsem se nestaral o následky.
{25967}{26092}Byl to zázrak, kdy jsem tì potkal.
{26137}{26195}Láska pøinutí svìt jít oklikou.
{26219}{26281}Vìø v sílu lásky.
{26301}{26451}Tak vyra do nového svìta se mnou a s tebou!
{26499}{26526}Láska pøinutí svìt jít oklikou.
{26526}{26626}Nikdy jsem se nestaral o následky.
{26653}{26784}Byl to zázrak, kdy jsem tì potkal.
{26822}{26848}Láska pøinutí svìt jít oklikou.
{26863}{26960}Vìø v sílu lásky.
{26996}{27194}Tak vyra do nového svìta se mnou a s tebou!
{28273}{28303}Sylvain je opravdu silnı.
{28321}{28354}Obdivuju tì.
{28376}{28437}Moná se cítíš nepøíjemnì slyšet |to po tvém komplimentu.
{28452}{28550}Byl jsem dost šastnı udeøit ho |s tím, co jsem se nauèil od Haruyi.
{28590}{28611}Byla to jen náhoda.
{28636}{28724}Promiò, prosím neøíkej jim to.
{28760}{28796}Dìlali by kolem toho povyk.
{28817}{28836}Já vím.
{28846}{28859}Budu to dret v tajnosti.
{28878}{28905}Díky.
{28951}{29012}Jestli se teï nevrátíme, nestihneme veèeøi.
{29034}{29086}Ne nìkdo zjistí, e jsme se vypaøili...
{29131}{29173}Potøebujeme povolení jít do mìsta?
{29195}{29246}Ne povolení, ale musíme se registrovat.
{29271}{29312}Je to napsáno ve studentnké pøíruèce.
{29333}{29369}T-To jsem nevìdìl.
{29398}{29492}Znamená to, porušil jsem školní pøedpisy tak rychle.
{29567}{29591}Promiòte za èekání.
{29609}{29641}Omlouvám se, Elvie.
{29659}{29701}Já to tak nemyslel.
{29719}{29750}Je to to stejné místo?
{29767}{29797}Máš pravdu. Díky.
{30058}{30114}Co bych udìlal kdybych nikdy znovu nevidìl svou rodinu?
{30169}{30263}Èetl jsem pøedtím nìco takového v manze.
{30290}{30373}Co by dìlal Yuuta jako Japonec?
{30429}{30471}Nikdy jsem o tom nepøemıšlel.
{30494}{30542}Pøedpokládáš, e tvá rodina zùstane v okolí.
{30561}{30610}Myslím, e to co znamená rodina, netrvá vìènì.
{30629}{30682}Není normální navrhovat, e je nikdy znovu neuvidíš.
{30712}{30759}Není to normální... Opravdu?
{30794}{30812}Je to pravda.
{30849}{30910}Stále mohu potkat své rodièe.
{31343}{31367}Vìc, o které jsi mluvil...
{31411}{31422}Ano.
{31473}{31485}Udìlal jsem to.
{31550}{31562}Sylvaine!
{31568}{31631}Má sestra tohle posílá Sylvainovi.
{31649}{31719}To je trièko Clokemana.
{31761}{31808}Jaké to je, jaké to je?
{31808}{31844}Není to ohromné?
{31889}{31916}Sluší ti.
{31916}{31938}Jo?
{31938}{31957}Co si myslíš, Rede?
{31957}{31985}Je to... Nakonec ádnı problém.
{31999}{32095}Pøeklad + korekce: WelW(etkaAa)-hime|Èasování: WelW(etkaAa)-hime
{34075}{34119}Dr jednoho, Rede a Yuuto.
{34136}{34171}Je to tak trapné bıt takto obleèení.
{34187}{34203}Jaká otrava.
{34218}{34270}Proè nemáme obleèené kimono?
{34324}{34416}Nevykvete ten strom brzy, Niisama?
{34464}{34519}V další epizodì,|ÈISTÁ VZPOMÍNKA|(Memoria = nìmecky vzpomínka)
{34575}{34689}P-p-problematická kreatura se pøibliuje.
