{1}{1}23.980
{188}{289}Aneki, Haruya je v meste a prihlásil sa do „jediacej súae“.
{351}{371}Neskutoèné!!!
{403}{432}Rıchlo Aneki..
{475}{577}Víazom je Haruya Kobayashi.
{624}{665}Pokraèovanie z predchádzajúcej| súae ïalšej fascinujúcej vıhry...
{665}{750}Najlepší jedlík všetkıch èias. |Trasieme sa s úctou k tebe!
{789}{823}Pozeraj Aneki pozri!
{823}{850}Neskutoèné!
{850}{883}Je víaz! Víaz!
{902}{928}Prepáè , e som a nechal èaka Yuuta.
{928}{953}Telefonuješ?
{977}{994}Uhm, s Aneki..
{1008}{1021}Zdravím...
{1021}{1086}Chcel som len poveda, e je to úasné ako si vyhral..
{1100}{1141}Tvoja rıchlos je úasná.
{1188}{1217}Preúvanie je aké.
{1239}{1266}Preúvanie je aké?
{1294}{1310}Pripomínaš mi...
{1340}{1359}Všetko sa prehltlo...
{1413}{1445}Musíš artova.
{1459}{1477}To je skvelé...
{1523}{1550}Preúval som mono trikrát..
{1606}{1646}Okej, ahoj Aneki.
{1665}{1690}Porozprávame sa nabudúce.
{1714}{1918}TaSHee's Gang uvádí|MARGINAL PRINCE
{4291}{4368}Na ostrove v Atlantiku, ktorı je a |moc malı na to aby ste ho zbadali na mape.
{4424}{4467}Na tomto místì, které bylo oddìleno od zbytku svìta
{4477}{4541}všetci mui navštevujú školu |nazıvanú Akadémia Svätého Alfonsa.
{4620}{4727}Nikto nevie kedy to zaèalo.|Ale záhadní študenti sú prezıvaní
{4789}{4873}Marginal Prince.
{4904}{4993}NEJÈISTŠÍ VZPOMÍNKY
{5659}{5674}To je tak problematické.
{5728}{5784}Haruya je z pravoslávneho klanu.
{5845}{5859}Dobre...
{5895}{5978}Yuuta je Japonec take by mohol vedie,| èo pravoslávne klany znamenajú.
{5994}{6027}Haruya k ním tie patrí.
{6082}{6124}Presnejšie povedané to nie je náš klan,
{6160}{6179}ale je to v poriadku.
{6225}{6246}Japonskı tanec.
{6246}{6316}Japonskı tanec. Ten, ktorı sa tancuje| v tradiènom kimone a s vejárom však?
{6329}{6365}Uhm, nieèo také.
{6374}{6411}To je skvelé, tak cool!
{6411}{6434}Vieš tancova?
{6467}{6510}Predtım na pódiu si to tie vykonal.
{6524}{6540}Preèo to neskúsiš?
{6579}{6592}Nie.
{6689}{6707}Je to príliš problematické.
{6735}{6796}A nevzal som si so sebou vejár.
{6824}{6832}Vejár?
{6854}{6876}Dobre, daj mi moment.
{7089}{7098}Pozeraj Aneki pozri!
{7153}{7161}Prestaò.
{7161}{7227}Toto je tak husté. Je toto leto v Japonsku?
{7262}{7283}Yuuta vie naozaj tancova.
{7355}{7394}Toto je ullambana tanec.
{7425}{7446}Ullambana tanec. Ullambana tanec
{7474}{7536}Aneki povedala, e je tu ve¾mi teplo tak nám toto poslala.
{7564}{7649}A potom toto...
{7862}{7898}Nechajte ma naservírova vám èaj.
{8080}{8116}Aneki!!!!!!!!!!!!!!!
{8477}{8498}Ïakujem za jedlo.
{8527}{8550}Nemôem uveri tomu, e u si to zjedol.
{8620}{8660}Je to vıborné.
{8675}{8714}Ale nebola tá ryba surová?
{8736}{8763}I keï to Alfred nezje bude to v poriadku.
{8813}{8836}Stále máš miesto na toto?
{8894}{8928}Dobre Haruya.
{9154}{9169}Kde je to?
{9218}{9285}Film reírovanı mojím starım otcom, Alphonse.
{9315}{9358}Nie je to napísané v japonèine ? Kde je to?
{9415}{9458}Toto je mierová pieseò napísaná Yingyuanom Daozhenom.
{9486}{9510}Nehovorí o tom kde to je.
{9536}{9579}Iritujúce, ten starı mu!
{9603}{9712}Vie, e nerozumiem japonsky tak pre mòa napísal toto.
{9731}{9832}Ale toto bolo napísané Daozhenom pre slivkové kvety na záhrade.
{9870}{9910}Mohol by to by k¾úè k tomu miestu.
{9944}{9981}Mohlo by to by v botanickej záhrade?
{9994}{10009}Botanické záhrady?!
{10009}{10054}Sú tam stále také miesta?
{10128}{10157}Hej, o èom tu vy dvaja rozprávate?
{10177}{10186}Idiot!
{10253}{10315}To je skvelé. Budeme skutoènı expediènı tím.
{10348}{10387}Vdy je dôleité sa obliec.
{10401}{10435}Táto cesta bude príliš problémová.
{10447}{10488}Ale preèo expediènı tím?
{10586}{10679}Odpoveï je vdy, kde je hranicou vietor,| napnime plachty a zaènime našu cestu.
{10730}{10755}Je to Orlie Oko Jimmy!!!
{10788}{10841}Mladı Yuuta, poïme.
{10853}{10890}Áno, kapitán!
{10929}{10966}Preèo musím ís tie?
{11286}{11306}Yuuta!
{11341}{11373}Kap...Kapitán!
{11406}{11445}Nestrate sa chlapci!
{11456}{11476}Nasledujte ma!
{11692}{11713}Toto je slivka.
{11794}{11850}Okej, rozde¾me sa a preh¾adajme okolie!
{11914}{11984}Nemyslel som si, e na strome je slivka.
{12083}{12139}Slivkové stromy ti pripomínajú Japonsko, e?
{12242}{12323}Ak junı vietor prinesie vôòu slivkovıch kvetov.
{12339}{12402}Vlastníci nikdy nezabudnú na letnú krásu.
{12464}{12522}Hovorí sa, e keï slivkové kvety zaèujú túto pieseò.
{12535}{12594}Nasledujú Daozhena k jeho domu...
{12627}{12667}Haruya, zdá sa , e vieš naozaj ve¾a.
{12700}{12779}Písali sme o nesúcej sa vôni slivkovıch kvetov.
{12795}{12856}V skutoènosti sa moj klan volá Meizhi.
{12890}{12933}Keï kvitnú slivkové kvety spomienky sa len priplavia spä.
{12980}{12988}Klan?
{13083}{13100}Hej vy dvaja!
{13127}{13149}Prestaòte sa tam hra a poïte mi pomôc.
{13149}{13172}Áno kapitán!
{13299}{13316}Je to ono?
{13348}{13430}Nevyzerá to na to aby sa do toho vmestil film.
{13461}{13474}Tie si myslím.
{13485}{13496}Nie poèka.
{13507}{13528}Je tam papier.
{13594}{13689}Choïte odtia¾to priamo juhozápadnım |smerom a nasledujte staroveké hviezdy.
{13800}{13823}Myslíš to vánì?
{13851}{13909}Rovno znamená priamo nadol, poïme chlapci!
{13921}{13959}Áno kapitán!
{14022}{14038}Je to tak problematické.
{14432}{14466}Neverím, e je tu miesto ako toto.
{14479}{14515}Èo by mohlo by v tıchto horách?
{14546}{14563}Je tu hvezdáreò.
{14563}{14584}Hvezdáreò?!
{14876}{14900}Ty si..
{14930}{14948}Ospravedlòujem sa...
{15000}{15043}Prepáète bola to všetko moja chyba.
{15118}{15126}Uteká..
{15143}{15164}Stále je rovnakı.
{15193}{15253}On je Mihael a je vdy takıto.
{15315}{15351}Take on je Mihael.
{15456}{15493}Toto je hvezdáreò?
{15558}{15596}Vyzerá tak staroveko.
{15618}{15637}Je to staroveké.
{15679}{15778}Presnejšie, je to staroveké vyhliadkové pamiatka.
{15816}{15837}Preto sa to volá hvezdáreò?
{15837}{15879}Ak sa ti to nepáèi môeš to vola ako len chceš.
{15916}{15950}I keï je to hvezdáreò je to fajn.
{15985}{16003}Deje sa nieèo?
{16025}{16095}Ešte nie je Kultúrny deò Akadémie Sv. Alphonsa, e?
{16126}{16148}Nie sme v kostımoch!
{16202}{16239}Okej, okej prepáè, e sme a obaovali.
{16290}{16298}Tu je to.
{16342}{16362}Je to ïalšia flaša.
{16444}{16458}Dovidenia.
{16458}{16529}Moja prekrásna samota. Ïakujem za otravovanie.
{16563}{16599}Není za co.
{16637}{16655}Znova ïalší kúsok papiera.
{16655}{16674}Otvorme to!
{16708}{16743}Èo sa tam píše?
{16755}{16813}Dobre...pokraèujte rovno...
{16830}{16851}Pokraèova? Znova?
{16996}{17052}Kapitán, seminko vniklo do mojej nosnej dierky!
{17066}{17088}Potom ho tam nechaj vyrás!
{17187}{17241}Kapitán had!
{17255}{17270}Rıchlo ho odhoï!
{17270}{17293}Útek!
{17325}{17344}Akı je stav?
{17393}{17435}Pomoc...pomôte mi!
{17449}{17485}Som v pohode, ale zdá sa, e sú tu pasti!
{17519}{17533}Naozaj?
{17590}{17610}Yuuta si v poriadku?
{17610}{17651}Padám!
{17651}{17699} Hej!
{17699}{17729}To bolo šastie!
{17794}{17804}Èo teraz?
{17835}{17871}Je to baina, moje nohy nedosiahnu na dno!
{17903}{17944}Alfred, vytiahneme a von!
{18092}{18116}August upokoj sa.
{18156}{18163}Je to dobré.
{18214}{18251}Okej, dobrı chlapec.
{18283}{18326}Obíïme pole so slamou.
{18353}{18377}Len pokraèujme rovno!
{18396}{18407}Hej, hej.
{18451}{18460} Ahoj Joshua.
{18470}{18477}Al...
{18477}{18542}Haruya teraz vypadáš šastnejšie.
{18555}{18566}Yuu...
{18566}{18616}Zdá sa , e máš rád seno.
{18616}{18643}Vyzerám snáï ako kôò?
{18643}{18665}Ahoj Joshua.
{18665}{18689}Har...
{18738}{18757}Uvidíme sa Joshua.
{18757}{18780}Poïme!
{18886}{18942}Nemyslel som si, e by Joshua mohol by v okolí.
{18958}{19021}Joshua je ako mama, miluje kone.
{19075}{19115}Jeho matka je slávna jazdkyòa.
{19174}{19232}Poèul som, e je dobrovo¾ník na humanitárnych akciách.
{19245}{19326}Do dòa kım odišla ho tu prišla raz |alebo dva krát do roka navštívi.
{19362}{19383}Raz alebo dvakrát do roka.
{19410}{19435}Josua vtedy musel by naozaj osamelı.
{19461}{19504}Keïe sa zdá, e jeho mama je trocha...
{19530}{19554}Je to fajn ak si na to zvykneš.
{19580}{19599}Je to rovnaké s mojou rodinou.
{19703}{19738}Haruya, tvoja rodina je tie taká?
{19753}{19819}Pravoslávny klan je naozaj zamestnanı,| tak to musí by aké.
{19819}{19886}Ale naša rodina má špeciálny status.
{19915}{19979}Dobre, ak nechceš nemusíš mi to hovori!
{20022}{20117}Tak to nie je, sú to naozaj komplikované veci.
{20135}{20173}Zabralo by to ve¾a èasu na vysvetlenie.
{20277}{20424}Zjednodušime to, doma prebieha boj.
{20471}{20526}Mám nevlastého brata.
{20540}{20625}A obaja sa uchádzame o práva budúceho nástupcu.
{20664}{20682}Tak je to ako..
{20709}{20729}Áno nieèo také.
{20758}{20799}Ale nezaujímam sa o to sta sa vládcom.
{20830}{20873}L´udia z okolia sa jednoducho rozdelili na dve súperiace strany.
{20903}{20941}Take, èo s tım budeš robi Haruya?
{20971}{20990}Niè.
{21046}{21065}Je to problematické, e?
{21110}{21138}Povedal som, e sa nestarám.
{21163}{21184}Nikto nepoèúval.
{21232}{21300}Bude to problematickejšie ak by sa stál vládcom.
{21337}{21377}Haruya, všetko vidíš problematicky.
{21409}{21471}Ale nie je tam niè problematické.
{21549}{21587}Ale hráme pre kapelu.
{21615}{21631}Dead Prince.
{21670}{21730}Pretoe prija ich je problematická èinnos.
{21756}{21766}Naozaj?
{21807}{21849}Si rovnakı Haruya.
{21902}{21922}U rozumieš?
{21922}{21951}Nie, vedel som to od zaèiatku.
{22059}{22068}Alfred!!!
{22099}{22121}Tak dlho som a h¾adal!
{22146}{22188}Môem si poièa Bielu Vranu?
{22239}{22302}Myslel som, e som ti povedal aby si tak môj bicykel nevolal.
{22316}{22359}Prepáè, èo Padajúca Hviezda?
{22382}{22405}Ok, ok poèúvaj ma!
{22457}{22482}Fajn vezmi si ho.
{22579}{22617}Okej u sme tam boli?
{22691}{22709}Èo je to teraz?
{22720}{22739}Pokraèova ?
{22739}{22766}Nemyslím si.
{22846}{22880}Nieèo, èo je niè.
{22913}{22925}Uttis?
{22962}{23022}Uttisov Byt. Uttis v gréètine znamená...
{23034}{23092}Nieèo, èo je niè.
{23108}{23127}Take, ak to je.
{23179}{23196}Tak to znamená!
{23276}{23299}Sme spä na nádvorí.
{23570}{23609}Èo to ešte hovorí?
{23637}{23675}Vstúpte.
{23711}{23748}Haruya, preèo si v tom takı rıchly?
{23748}{23798}Je to problematické chcem to ma rıchlo z krku.
{23812}{23826}Hej, hej.
{23853}{23869}Teraz èo?
{23981}{23994}To je...
{24028}{24041}Hodiny!
{24071}{24111}Poèka, poèka, je tu nieèo napísané.
{24143}{24226}Keï bude slnko na dvanástej a hodiny| na dvanástej otoè sa k ¾avej strane oblohy.
{24282}{24321}Koneène sme našli poklad!
{24411}{24442}Nie je to plastové.
{24573}{24590}Toto sú slová môjho starého otca.
{24651}{24684}Haroumi, Haruya.
{24696}{24733}Je to na vás.
{24766}{24785}Som Bliely Slivkovı Škriatok!
{24814}{24845}Ja som Èervenı Slivkovı Škriatok!
{24939}{25039}To znamená, e sme boli nádherne podvedení mojím starım otcom.
{25121}{25162}Prebehli sme a okolo školy pre niè.
{25162}{25211}V skutoènosti tam nebol iaden poklad.
{25223}{25243}Nebol? Poklad...
{25365}{25452}Ale vejár Haruyovho starého otca |bol v skutoènosti v Bytoch Uttis.
{25466}{25483}Je to neuverite¾né.
{25514}{25612}To preto, e Haruyov starı otec je absolvent tejto školy.
{25649}{25678}Mono to tí dvaja plánovali od zaèiatku.
{25695}{25720}Asi to tak je.
{25720}{25747}Hej Haruya.
{25770}{25794}Dobre je tu vejár, tak zatancuj!
{25817}{25839}Váne to chcem vidie!
{25839}{25946}Nie, nie bude to pre neho problematické.
{25986}{25994}Je to v poriadku.
{26102}{26121}Neuverite¾né!!
{26121}{26169}Nevidíš to problematicky?
{26178}{26198}Áno, problematicky.
{26222}{26287}Ale ak je to tá reakcia, ktorú dostanem |potom nebudem viac tancova.
{26323}{26344}Je to klamstvo, jedno ve¾ké klamstvo!
{26344}{26364}Chcem to vidie!!!!
{26364}{26411}Prosím Haruya.
{26881}{26996}Obèas sa cítim znepokojene.
{27069}{27215}Ako by všetko bol sen.
{27288}{27387}Dra a blízko, jemne a nikdy a nenecha odís.
{27401}{27481}Myslím, e je to naozaj problematické, |ale cítim sa naozaj šastne.
{27498}{27560}Haruya , stále nerozumieš však,
{27591}{27616}ale èoskoro porozumieš.
{27642}{27750}Nezáleí, kedy na tomto nekoneènom svete.
{27785}{27867}Nikdy nezabudnem.
{27887}{27924}Toto je zasnená, krásne.
{27924}{27951}Haruomi, Haruya.
{27951}{27977}Teraz je to na vás.
{28004}{28024}Som Bliely Slivkovı Škriatok!
{28038}{28070}Ja som èervenı Slivkovı Škriatok!
{28095}{28223}Tento súd je západ s naším pódiom.
{28244}{28302}Potom skúste obaja cíti srde Slivkovıch kvetov.
{28316}{28354}So elaním nikomu neublíi.
{28387}{28409}Nii-sama rozumieš?
{28409}{28473}Nekoneèné elanie milova padajúcu hviezdu.
{28485}{28501}Nerozumiem.
{28501}{28547}To je skvelé. Ani ja.
{29129}{29319}Láska, ktorú cítim kde bude urèite |dlhšia nech hociktorá iná.
{29352}{29519}Ihrisko na konci zeme.
{29567}{29729}I keï sen skoncèí moje pocity budú stále pretrváva.
{29764}{29859}A miesto, kde na stretneme.
{29877}{30108}Ako nekoneèná láska, v ktorú |sa verilo pod padajúcimi hviezdami.
{30281}{30425}Mám nekoneènú lásku, ktorú darujem tebe.
{30528}{30569}Cez to, e som netancoval tak dlho
{30618}{30646}som stále šastnı, e som to vedel ako by som mal.
{30670}{30726}Haruya, èoskoro porozumieš.
{30742}{30842}Nenahradite¾ná vec, ktorú môeme nájs v srdci kadého.
{30927}{30950}Skutoène tam je. Starı otec.
{31052}{31070}Bolo to nádherné.
{31070}{31096}Haruya bolo to skvelé!
{31096}{31117}Áno!
{31741}{31755}Haruya...
{32093}{32191}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime
{34071}{34087}V další epizodì:
{34104}{34111}Bonjour.|(francouzsky: Dobrı den)
{34134}{34146}Arret!|(francouzsky: Pøestaò)
{34162}{34181}Se Cher.|(francouzsky: Suchı)
{34181}{34208}Le pont du.|(francouzsky: Most)
{34261}{34288}Je nìco, co chceš øíct, Yuuto?
{34327}{34392}Chceš mluvit francouzsky tak plynnì jako já?
{34392}{34463}Pak tì budu uèit ruku v ruce.
{34499}{34517}Zabere to pravdìpodobnì stovky let.
{34517}{34582}Pøíští epizoda: SKVÌLÉ VİROÈÍ
{34617}{34700}Moje francouzština je velice plynná.
