{1}{1}23.980
{241}{255}Ahoj , Yuuta.
{292}{312}Huh? Kto je to?
{432}{474} Eh...ahoj...
{516}{564} Prepáè, ale si príliš blízko.
{617}{642} Aha. Toto je video hovor?
{642}{694} Áno. Kto si?
{707}{738}Prepáè, si Yuutov kamarát?
{754}{783} Tak to patrí tomu chlapcovi.
{802}{844} Priate¾? Kto vie.
{859}{904}Huh? Ale toto je Yuutov mobil.
{922}{945} Našiel som ho.
{957}{1010}Èo? Tım myslíš, e stratil telefón?
{1023}{1063}Tomu neverím. Aj v takomto veku je stále takı nedbalı.
{1070}{1100}Povedal, e šiel na plá...
{1100}{1162}ale skonèilo to tak, e stráca jeho osobné veci.
{1174}{1229}Som si istá, e to ešte nezistil.
{1263}{1311}Pr...prepáè! To je prvı krát, èo sa vidíme a...
{1379}{1410}Tie si dos podivná.
{1468}{1535}(Prosím nabite svoju batériu.) |Poèkaj chví¾u.... Batéria je slabá.
{1548}{1584}Hej... ako sa voláš?
{1584}{1792}TaSHee's Gang uvádí|MARGINAL PRINCE
{4162}{4236}Na ostrove v Atlantiku...
{4283}{4329}ktorı je a moc malı na to abyste ho zbadali na mape,
{4329}{4407}všetci mui navštevujú školu |nazıvanú Akadémia Svätého Alfonsa.
{4479}{4522}Nikto nevie kedy to zaèalo...
{4543}{4595}Ale záhadní študenti sú prezıvaní...
{4646}{4727}Princové hranic,|Marginal Prince.
{5915}{5939}Preèo si to spravil?!
{5968}{6008}Je nebezpeèné pláva v mori tak nedbalo.
{6065}{6148}Nesna sa ma poblázni napodobòovaním Jimmyho Gurua.
{6172}{6221}Napodbòovaním? Ja som Jimmy!
{6251}{6331}Jimmy by sa neprikradol k ostatnım.| Nie je takı opovrhnutia hodnı.
{6364}{6446}Neprikádal by sa... ne..
{6505}{6527}Do...dobre ako pirát,
{6527}{6575}pristúpim k hocièomu na dosiahnutie víazstva.
{6676}{6719}Potom toto! Yuutove rozdrvenie!
{6729}{6743}Èo?!
{6796}{6814}Blbec!
{6848}{6885}Haha....som bezoh¾adnı!
{6904}{6974}Fajn, potom vyskúšaj moje drvenie!
{6990}{7018}Iste, uká to!
{7301}{7336}Ïakujem, Butler.
{7354}{7368}Iste.
{7411}{7440}Pripravil som sojovú omáèku a èakal váš návrat.
{7464}{7479}Okej.
{7507}{7517}Skáèem.
{8502}{8513}Èakaj ma!
{8525}{8538}Sme spä!
{8566}{8598}Ah...umieram smädom.
{8615}{8658}Chceli by ste nieèo na pitie?
{8685}{8717}Prosím dajte mi rovnakı drink ako Joshuovi.
{8743}{8767}Ja by som chcel pomaranèovı dús.
{8782}{8799}Dobre.
{8834}{8862}Táto plá je naozaj úasná.
{8880}{8952}Ale na tomto krásnom mieste nie je nikto inı.
{8988}{9071}Je to súkromná plá, ktorú vlásní Akadémia.
{9108}{9183}Súkromná plá? Èo tım myslíš?
{9231}{9289}To znamená, e sem môu ís len študenti zo školy.
{9314}{9365}Inak povedané, vstup na plá je rezervovanı?
{9381}{9414}Vstup na plá.... úasné!
{9438}{9469}I plá ïaleko vpredu je rezervovaná.
{9484}{9537}Myslím, e je to tie malı prístav.
{9558}{9631}Áno... je to na opaènej strane pláe.
{9646}{9692}Táto plá je príliš ve¾ká. Som zmätenı.
{9713}{9739}Prepáète za èakanie.
{9767}{9824}Tu je vaša ¾adová káva a pomaranèovı dús.
{9857}{9872}Ïakujem, Butler.
{9888}{9900}Ïakujem.
{10117}{10165}Ah... je to tak horké.
{10198}{10249}Toto je rovnakı nápoj, èo ma Joshua?
{10269}{10292}Správne.
{10322}{10363}Pije horkú kávu...
{10388}{10431}Joshua je tak pôsobivı!
{11460}{11498}Huh...ako je to moné?
{11698}{11738}Znova som sa dopustil zbytoèného zabíjania.
{11753}{11814}To je tak úasné!
{11825}{11882}Je to tak dávno odkedy to povedal naposledy.
{12007}{12025}Je to skvelé.
{12037}{12088}Svieos a chu sú hornı zárez.
{12104}{12136}Jes to znova surové...
{12156}{12187}Oh dobre...Japonci...
{12201}{12233}Zaènem jes.
{12246}{12271}Nechaj ma vyskúša tie.
{12342}{12408}Nie zlé. Chutí to rovnako ako tie, ktoré |boli pripravené špeciálne v Japonsku.
{12433}{12465}Je to trocha nevırazné.
{12482}{12521}Preto je omáèka zo slanej vody dobrı doplnok.
{12534}{12554}Morská ryba, huh?
{12575}{12599}Butler, vyskúšajte tie.
{12611}{12686}V poriadku.
{12734}{12749}Je to vynikajúce.
{12757}{12767}e je?
{12796}{12843}Všetci to jedia surové.
{12868}{12930}Dúfam, e Henry a ja máme normálne stravovacie návyky.
{12953}{12972}Vcelku dobré.
{13035}{13051}Èo? Dobré?
{13063}{13119}Preèo to tie neskúsiš?
{13135}{13174}Áno. Hmmm...vynikajúce.
{13356}{13413}Môem sa opáli? Jop, môem.
{15393}{15408}Našiel som to.
{15595}{15612}Ty si ten chlapec...
{15661}{15692}Tvoj mobil.
{15729}{15761}Áno je. Ako si...?
{15785}{15807}Našiel som ho.
{15832}{15866}Èo? Stratil som môj mobil?
{15883}{15916}A ani som si to nevšimol.
{15957}{15977}Nechceš ho spä?
{15995}{16028}Prepáè. Ïakujem, e si mi ho vrátil.
{16042}{16100}Ak by sa sestra dozvedela , e som stratil mobil...
{16172}{16187}Prosím?
{16215}{16249}Yuu...Ta...!!!
{16294}{16347}Ako si mohol strati mobil? Èo sa s tebou deje?!
{16361}{16404}To...nie...
{16415}{16436}Nie? Èo nie?!
{16446}{16461}Stáva sa to len obèas.
{16461}{16479}Obèas?
{16490}{16523}Obèas je to len obèas....
{16541}{16595}Aneki, zavolám ti neskôr.
{16604}{16611}Nesklad-
{16681}{16708}Tvoja sestra...
{16780}{16819}Aj tvoja sestra je pekne divná.
{16921}{16980}Si podivín.
{17045}{17126}Ïakujem...e si mi vtedy pomohol.
{17161}{17201}Od toho incidentu som a h¾adal.
{17219}{17274}Môeme by z rovnakej školy, ale nemusíme sa stretnú ani raz.
{17303}{17364}To pretoe areál je príliš ve¾kı.
{17460}{17490}Môem vedie tvoje meno?
{17515}{17532}Som Yuuta.
{17557}{17575}Viem.
{17610}{17633}Oh pamätáš sa?
{17648}{17671}To preto, e si trocha zvláštny.
{17705}{17719}Enju.
{17768}{17843}Enju. Teší ma, e som a spoznal, Enju.
{17927}{17974}Hráme pláovı volleyball.
{18000}{18015}Chceš sa prida?
{18045}{18092}Predstavím a svojím priate¾om z Utisu.
{18152}{18206}Hej, Enju! Poèkaj!
{18521}{18574}Prepáè, je to celé moja chyba.
{18847}{18884}Nie je vám v tom obleèení teplo?
{18903}{19009}Vdy musím dentlemenom ukazova mravy a spôsoby.
{19033}{19134}To je hlavná poiadavka pre hlavného správcu z Utisu.
{19178}{19215}Ste tak cool...
{19259}{19326}Teraz, toto je najlepšia aktivita na plái.
{19344}{19366}Fantastickı vodnı melón.
{19405}{19472}Èo majú vodné melóny spoloèné s morom?
{19487}{19541}Je to Japonskı zvyk, ktorı sa vykonáva v lete.
{19773}{19788}Je teplo.
{19839}{19886}Hej! Ako sa opovauješ bra melóny bez môjho povolenia!
{20015}{20039}Dopekla.
{20084}{20125}Marginal Prince, huh?
{20318}{20352}Nie, neurobil som niè také.
{20376}{20418}Èo tak zahra si vıznamnú hru?
{20448}{20484}Znie to skvele. Poïme to vyskúša.
{20613}{20655}Poèkaj chví¾u. Toèíš prirıchlo!
{20681}{20728}Je to lepšie pre vzrušujúcu hru.
{20793}{20880}Po...è...poèkaj chví¾u.
{21142}{21186}Blázon! Poèkaj....Poèkaj!
{21191}{21199}Èo?
{21235}{21262}Dopekla. Netrafil som ho ani raz!
{21271}{21309}Hej, musíš vytàèa...!
{21323}{21341}Musíš vytàèa!
{21457}{21489}Má èo si zaslúil.
{21566}{21601}Èo robíš, Joshua?
{21615}{21641}Niè...dôveruj mi...
{21677}{21704}Vidíš, niè.
{21719}{21794}Aké hlúpe...naozaj robíš, èo chceš.
{21804}{21811}Toèi!
{22032}{22045}Aká škoda.
{22235}{22269}Úasné!
{22286}{22310}Vynikajúce Sylvain.
{22453}{22477}Správne, Sylvain...
{22497}{22523}Èo si robil v poslednej dobe?
{22540}{22566}Èo tım myslíš?
{22579}{22598}Neviem.
{22628}{22647}Èo sa deje?
{22666}{22723}Vyzeráš trochu zvláštne.
{22753}{22780}Nemyslím si.
{22805}{22879}Nie, v poslednej dobe vyzeráš zdravo.
{22897}{22935}Pravda tvoja stupidita je nákazlivá.
{22947}{22977}Moja stupidita je nákazlivá?!
{22994}{23029}Áno, narodil si sa tak.
{23064}{23108}Tak, èo sa s tebou deje Sylvain?!
{23130}{23173}I keï sa pıtaš...
{23199}{23241}Preèo sa od nás odvraciaš?
{23329}{23382}Rozhodne, nie je iadna èas,| ktorá by sa pred vami skrıvala.
{23839}{23877}Koneène som to získal!!
{23892}{23927}Klukoman super jojo!!!
{23986}{24031}Je to darèek, ktorı som dostal spolu s Klukomanovımi èokoládami.
{24043}{24102}dá sa, e mám konkurenta, ktorı kúpil zvyšné èokolády.
{24126}{24217}Neoèakával som, e sa na tomto ostrove nájde |niekto inı, kto bude chcie to jojo tie.
{24299}{24393}Preto som sa rozhodol porazi konkurenta ponáh¾aním sa |do obchodu okamite, keï skonèí vyuèovanie.
{24419}{24488}Definitívne sa mi po 385 dòoch podarilo získa jojo.
{24540}{24595}Zrazu sa cítim ako idiot.
{24617}{24653}Koneène si to zistil.
{24666}{24711}Zabudnite na to. Som rád, e sa Sylvain netrápi.
{24735}{24753}Aké problematické.
{24826}{24863}Ale nemôem im poveda pravdu.
{24954}{24993}Sylvain! To bolo tak husté!
{25024}{25052}Iba Yuuta sa zaujímal o môj príbeh.
{25070}{25099}Som zahanbenı.
{25385}{25405}Hej Yuuta!
{30486}{30530}Ospravedlòujem sa...je to celé moja chyba.
{30565}{30581}Mihael.
{30618}{30634}Je èas.
{30650}{30704}Nie je dobré aby si ostával príliš dlho na slnku.
{30719}{30759}Áno...Profesor Sokurov.
{30955}{30981}Ahoj...Yuuta.
{31046}{31077}Dnešok je takı mierumilovnı.
{31096}{31136}Je skvelé obèas urobi nieèo takéto.
{31156}{31228}Všetko je mírumilovné a bavili sme sa.
{31245}{31261}Áno...
{31282}{31314}Dobre, je èas bali sa.
{31447}{31501}Nabudúce musíme pracova ašie.
{31554}{31576}Èo tım myslel?
{31576}{31610}Hádam, e myslel zajtra.
{31610}{31644}Nemyslel náš budúci vılet sem?
{31707}{31732}O tıdeò neskôr.
{32087}{32195}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime
{34062}{34090}V pøíští epizodì:
{34164}{34183}Yuuto.
{34183}{34229}Opravdu si myslíš, e mì mùeš |s tvou úrovní porazit?
{34518}{34540}Omlouvám se...
{34604}{34639}Pøíští epizoda: HLUBOKİ LABYRINT
{34678}{34732}Osud mì zøejmì svádí.
