{1}{1}23.980
{165}{199}Hej, Yuuto.
{215}{255}Poslala jsem ti dnes balíèek.
{285}{303}Coe?
{318}{356}ádal jsem tì, abys nìco posílala?
{371}{390}Dìkovnı dárek.
{498}{555}Nezdá se, e jsem udìlal nìco co potøebuje díky.
{572}{599}Nedìkuju tobì.
{613}{677}Pomáhám ti dìkovat ostatním.
{677}{747}Take co tím myslíš?
{764}{856}Nìkdo naše tvùj mobil, kdy jsi ho|naposledy ztratil na plái.
{878}{926}To je vìc.
{952}{988}Jak jsem èekala, neposlal jsi dìkovnı dárek, e?
{999}{1037}U jsem té osobì dìkoval, vánì.
{1044}{1063}Nemùeš mu podìkovet jen slovy.
{1099}{1186}Poslouchej. A to dostaneš, |øádnì to odevzdej tomu studentovi.
{1206}{1243}Dìj mu vìdìt, e je to dìkovnı dárek.
{1254}{1294}Aneki, moc o tom pøemıšlíš.
{1311}{1349}Yuuto, ty jsi ten, kdo je necitlivı.
{1365}{1432}Mu se nebude obtìovat s takovımi vìcmi.
{1441}{1501}Enju také nikdy nemyslel na pøijímání dárkù.
{1516}{1564}Take ta osoba je Enju.
{1600}{1658}Take aneki, byla jsi velmi rozrušená?
{1683}{1710}Sklapni! Zavìšuju.
{1744}{1791}Jen jsem si dìlal legraci, legraci.
{1807}{2004}TaSHee's Gang uvádí|MARGINAL PRINCE
{4389}{4466}Na malinkém ostrovì v Tichém oceánu,|kterı nemùe bıt nalazen na mapì,
{4510}{4555}je chlapecká internátní škola,|Akademie Sv. Alphonsa,
{4567}{4641}která "sedí" na tomto izolovaném ostrovì.
{4709}{4754}Kdo ví, kdy to zaèalo,
{4772}{4830}studenti, kteøí byli naplnìni záhadami mìli pøezdívku
{4873}{4958}Princové hranic, Marginal Prince.
{5026}{5093}ZPUPNİ SMUTEK
{5321}{5384}...a pak se to stalo chaotickım...
{5397}{5409}Pro tebe.
{5495}{5553}Zdá se, e jsme se stali zamìstnanìjšími.
{5738}{5792}Jednou se tìlesná hmotnost zmìní a stane se...
{5795}{5812}Oh, ne!
{5838}{5878}Tak zbytek necháme na pøíští hodinu.
{5900}{5917}Dìkuji...
{6502}{6540}Pak to nechám na tobì, Alfrede.
{6556}{6618}Ok. Pøíštì to udìlám jak všichni poadovali.
{6618}{6661}Zaèneme pøíbìh odsud.
{6690}{6726}Tìším se na to.
{6751}{6769}Nech to na mnì.
{7725}{7773}Jak jsem èekal, škola je tak velká.
{7795}{7829}Jestli si nepospíšíme, aneki zavolá a |zase bude vyslıchat.
{7842}{7919}Pøišel ten balíèek? Pøedal jsi ho øádnì?
{7937}{8007}Kdy jí neodpovím, bude na mì zase rozzuøená.
{8029}{8086}Kal šel, Enju.
{8135}{8201}Kam jsi šel, nii-san.
{8317}{8370}Prostì poèkám u ubytovny Alprahd.
{8370}{8401}Yuuto.
{8451}{8497}Enju, jsem rád, e tì tu vidím.
{8532}{8563}Proè jsi tam?
{8639}{8676}Proè taky nejdeš nahoru?
{8731}{8780}Nejsem tak divokı.
{9144}{9154}Zatracenì.
{9175}{9224}Enju, jak jsi vyšplhal tak vysoko?
{9255}{9313}Onii-san, jak jsi vyšplhal tak vysoko?
{9400}{9434}Sakra, ještì jednou.
{9525}{9553}Obloha ztemnìla.
{9607}{9618}Copak?
{9655}{9722}Vlatnì myslím, e nejsem atletickı
{9735}{9756}a cítím, e jsem prohrál.
{9756}{9792}Ne, nejsi tady, protoe jsi mì shánìl?
{9813}{9826}To je pravda.
{9946}{9966}Onii-san, pojï.
{9992}{10014}Pojï na moment.
{10137}{10154}Jsou tady všichni, e?
{10204}{10275}Yuuto, jsi obleèenı jako slavík.
{10303}{10317}Coe?
{10331}{10365}Brzy pøijde kulturní festival.
{10385}{10410}Festival Akademie Sv. Alphonsa.
{10422}{10489}Je tradice se bìhem té doby pøestrojit.
{10507}{10544}Proè je to slavík?
{10562}{10592}Je to známá zdravotní sestra, e?|/nejspíš myslí Florence Nightingale ;)/
{10607}{10631}Je to pták. Pták.
{10649}{10696}Kdy pøišel Princ Alphonso na tenhle ostrov,
{10708}{10794}les byl moc temnı a øíkalo se,|e ptáci vedli cestu.
{10815}{10843}Je to slavík.
{10868}{10898}Co znamená øíct, e Yuuta je slavík.
{10898}{10957}Jsem pták.
{10976}{11060}To je pravda. Byla to stará tradice |pro nováèky, obléct se jako slavík.
{11091}{11115}ádnı odpor, e?
{11151}{11215}Je to dobré, ale za co se pøestrojíte vy?
{11232}{11265}Joshua je Princ Alphonso.
{11304}{11346}To je cool.
{11489}{11577}Je také tradicí, e zástupce studentù |je pøevleèenı za prince.
{11598}{11649}Rád bych si to taky s nìkım vymìnil.
{11664}{11677}STØIH, STØIH!
{11694}{11756}Jsem producent letošní ubytovny UTEISU.
{11766}{11780}Musíte dìlat, co øeknu.
{11823}{11843}Chápu.
{11892}{11923}Yuuto, máš hosta.
{11940}{12057}To je pravda. Skoro jsem ho zapomnìl pøedtavit,|poté co jsem byl Alfredem pøerušenı.
{12128}{12153}Enju z ubytovny Alphard.
{12170}{12281}To byl ten, co našel klenot,|kdy jsem poprvé nastoupil do školy.
{12660}{12731}Tak to jsi ty. Dìkuji ti.
{12731}{12771}Všechny díky tobì.
{12797}{12827}Nevím, jak ti mám podìkovat.
{12844}{12889}Jen jsem pomáhal tomuhle klukovi.
{12904}{12953}Staèí ochotnì pøijmout úmysly tìch klukù.
{12993}{13076}To je to, co se dìje. Mùj záhadnı a nosatı pøíteli.
{13107}{13129}Opravdu, Henry.
{13148}{13283}Promiò. Henry myslel, jak bıt dobrım pøítelem.
{13310}{13404}Všichni jsou opravdu šastní, e byl klenot nalezen.
{13424}{13465}To je pravda, a bylo tak vyøešeno |nedorozumnìní, které se mnou mìli.
{13564}{13595}Coe? Promiò.
{13634}{13708}Protoe jsi tady, proè se k nám nepøipojíš na jídlo?
{13740}{13751}To je skvìlé.
{13767}{13811}Dovolte, abych zavolal Butlera.
{13824}{13844}Øeknu mu, e máme další osobu.
{13844}{13875}Nechám to na tobì.
{13928}{13985}Promiò, máš nìco v programu?
{14009}{14057}Ještì jsme se neptali na tvùj názor.
{14101}{14119}Opravdu, Enju?
{14137}{14163}Tak mi dovolte, abych zavolal Alfreda.
{14185}{14266}Ne, to je v poøádku.
{14285}{14311}To je skvìlé.
{14346}{14365}Je to taková zábava.
{14427}{14471}To je pravda. Nìco jsem zapomnìl.
{14501}{14547}Pro tebe. Je to od aneki.
{14577}{14618}Je to dìkovnı dárek, za nalezení mého mobilu.
{14648}{14685}Jsou to sušenky dìlané mou sestrou.
{14717}{14775}Nii-san, tady jsou sušenky, které jsem ruènì udìlala.
{14846}{14902}Nemáš rád... sušenky?
{14946}{14957}Ne.
{14977}{14999}Pak je zkus.
{15088}{15291}Tlukot srdce, tlukot srdce, tlukot srdce...
{15368}{15386}Je to rozemleté.
{15620}{15634}Ale je to vynikající.
{15657}{15683}To je skvìlé.
{15699}{15757}Letìly sem speciálnì z Japonska?
{15826}{15881}Tvoje sestra je opravdu podivná.
{15942}{15995}Je to nìco, co jsem dokonce nikdy pøedtím nejedl.
{16012}{16048}Nikdy bych si nepomyslel.
{16103}{16120}Dìkuji.
{16188}{16248}Tentokrát je aneki opravdu pozorná.
{16281}{16328}Toto je pro ubytovnu. Prosím, vyzkoušejte je všichni.
{16345}{16361}To je skvìlé.
{16361}{16405}Dlouhı ivot aneki.
{16464}{16525}Je to vıborné. Aèkoli je to trochu pøepeèené.
{16525}{16611}Je to v poøádku, je to v poøádku...
{16630}{16678}Joshuo, Henry, vy taky zkuste.
{16814}{16913}Aneki vybrala ty lepší a dala je Enju.
{17035}{17053}Co se dìje, Joshuo?
{17095}{17172}Zdáš se bıt jinı ne normálnì.
{17226}{17258}Jsem v poøádku.
{17282}{17459}Tvar neovlivòuje chu.
{17483}{17516}To je moje sušenka. Co to dìláš?
{17530}{17568}Pøestaòte si hrát, kluci.
{17586}{17628}Je jich stále dost. Tak se pøestaòte hádat.
{17643}{17680}Henry, pøestaò se hádat s Alfredem.
{17713}{17730}Co se dìje?
{17744}{17787}Toto místo  je velice teplé.
{17816}{17843}Není špatné si takhle hrát.
{17885}{17909}To je pravda. Co Sylvain?
{17928}{17951}Nevidìl jsem ho.
{17978}{18000}Není ve svém pokoji?
{18024}{18076}Nech ho, nech ho. Je lepší mít |o jednoho ménì na schlamstnutí sušenek.
{18076}{18107}Souhlasím.
{18151}{18184}Stále to mùeme prosadit, Sylvaine.
{18256}{18269}Pøestaò s tím.
{18296}{18372}Nenávidím mít tajné špionáe na soukromí studentù.
{18393}{18444}Uzavøeli jsme pakt.
{18470}{18565}Jestli vykonáš svou misi, pak budeš schopnı vidìt své rodièe.
{18565}{18615}Ale jestli teï pøestaneš,
{18652}{18706}nikdy nebudeš schopnı vidìt svou rodinu.
{18731}{18808}LBKK JAK LHAL, posílit.|/nemám páru, co tím myslí :D/
{18858}{18915}Byla ubytovna UTEISU vdycky taková?
{18945}{18988}Nejsou všechny ubytovny stejné?
{19014}{19037}Jsou úplnì jiné.
{19052}{19156}Pak, nemáš rád hraní?
{19182}{19214}Ne, mìl bych øíct...
{19251}{19273}Co to znamená?
{19320}{19382}Zapomeò na to, jestli ti to pøipomíná špatnou minulost.
{19413}{19452}Enju, proè jsi pøišel na tuhle školu?
{19472}{19485}Co ty?
{19520}{19557}Díval jsem se na obrazy v umìlecké galerii,
{19581}{19630}pak nìkdo se mì nìkdo pøišel|zeptat jestli se chci uèit kreslit.
{19644}{19685}Ten mu byl pøítel mého otce...
{19727}{19757}Zeptal jsem se Enju.
{19800}{19909}Protoe jsem nikdy pøedtím nic neztratil...
{20068}{20104}Jakou vìc?
{20114}{20146}Protoe jsem nikdy pøedtím nic neztratil...
{20215}{20229}Je èas se vrátit.
{20372}{20418}Prosím vra se a bude èas na veèeøi.
{20441}{20471}Všichni na tebe budou èekat.
{21493}{21550}Onii-san, proè mi nerozumíš?
{21804}{21861}Jen nech ty vìci o samotì.
{21886}{21909}Je to všechno minulost.
{21921}{21957}Nemá to s námi nic spoleèného.
{22270}{22294}Ne...
{22753}{22767}To...
{22980}{23010}Jsem... Jsem v poøádku.
{23029}{23073}Ne, jestli teï nenajdeme Profesora Sokurova...
{23083}{23101}To není tøeba.
{23118}{23168}Ale... ale jestli jsi otrávenı...
{23238}{23274}Neobtìuješ mì.
{23305}{23384}Ale.. ale je to všechno moje chyba.
{23405}{23461}Ne, to je protoe nejsi dost zralı.
{23589}{23654}Nad èím váhám?
{24955}{25000}Bùh ti nedal trest smrti.
{25037}{25071}Ale je to nadìje ít.
{25159}{25253}Vede nás to hnout se kupøedu spoleènì.
{25267}{25284}Náš Král.
{25297}{25335}To je... BAREVNÉ SKLO.
{25352}{25436}Král mùe vybrat ze své vlastní vùle, aby íl nebo zemøel.
{25470}{25507}Král je rozhodující.
{25627}{25645}Jsi zranìnı.
{25667}{25701}Nech si to zkontrolovat na klinice.
{25721}{25741}To není tøeba.
{25760}{25807}Ne. Jestli s tebou nebude øádnì zacházeno...
{25823}{25875}Jsi stejnı jako ten kluk.
{25895}{25899}Ten kluk.
{25922}{25923}Yuuta?
{25988}{26000}Podivnı.
{26024}{26037}Podivnı?
{26057}{26150}Král Alphonso se vzdal svého ivota, aby ochránil své pøátele.
{26180}{26202}Co si myslíš?
{26267}{26301}Myslím, e je to šastnı mu.
{26326}{26350}Mimoøádné chování.
{26387}{26421}Nemyslíš si to?
{26448}{26479}Pokrytectví.
{26514}{26566}Král myslel jen na to, co je vpøedu.
{26593}{26647}Zatíen odpovìdností osudu Království.
{26667}{26702}Jestli vzdává své odpovìdnosti,
{26710}{26730}je to stále mimoøádné?
{26758}{26837}I kdyby hanebná osoba èelila odporu a nesnázím,
{26854}{26900}ití je cesta Krále.
{26927}{26967}To je Královské poslání.
{27008}{27041}Kdo vlastnì jsi...
{27313}{27378}Nemùe bıt rozhodující a vést lidi.
{27404}{27428}Ten, kterı je Králem.
{27571}{27616}Nebudu tebou.
{27635}{27667}Ty taky nebudeš mnou.
{27694}{27738}Jsem jinı ne ty.
{27843}{27902}Enju, neøíkej mi, e jsi...
{27920}{27953}Skonèil jsem svùj pøíbìh.
{27977}{28006}Minulost pøed velmi dlouhou dobou.
{28755}{28800}Moná tu není jen jeden vıchod.
{28820}{28861}Mùeme najít jiná øešení.
{28898}{28929}Neubliuj si.
{31050}{31120}Jakékoli monosti budou také nadìjí.
{31144}{31206}Hledám nadìji, nii-san.
{31234}{31261}Právì jako hvìzdy.
{31275}{31303}Záøí s nadìjí.
{31322}{31386}Nii-san, proè?
{31685}{31747}Hvìzdy zmizely.
{31827}{31875}Je tak pomalı, Enju.
{31909}{32019}Pøeklad + korekce: WelW(etkaAa)-hime|Èasování: WelW(etkaAa)-hime
{34077}{34120}Náhled, hvìzdy zmizely.
{34138}{34149}Onii-san.
{34166}{34204}Yuuta zmizel.
{34241}{34288}HRABÌ JAVAHGLL také zmizel.
{34306}{34365}Co chce Onii-san dìlat?
{34381}{34431}Má veèeøe taky zmizela.
{34455}{34500}Onii-san, snìz to.
{34523}{34608}Jsi opravdu podivná osoba.
{34650}{34701}Pøíštì, TRUBADÚROVA VÁŠNIVOST
{34727}{34742}Onii-san.
