{1}{1}23.980
{120}{144}Haló, Aneki?
{188}{230}Èo sa ti nepáèi na tomto pozdrave?
{293}{354}Stále sa trápiš kvôli tomu, èo sa stalo predtım?
{383}{438}Je to v pohode. Joshua sa má dobre.
{467}{500}Aj keï by som bol rád keby s nami telefonoval.
{500}{549}Ale som v inej ubytovni.
{572}{605}Získavám novıch priate¾ov.
{631}{691}Miheal, nechaj ma predstavi a mojej sestre.
{735}{757}Ale...ja...
{771}{813}Je to v poriadku. Nebude to ani trocha strašidelné.
{845}{883}Ale obèas je to stále desivé.
{925}{998}Je to v pohode. Aneki je len zlá k jej bratovi.
{1008}{1050}Ale k ostatnım je milá. Poï.
{1103}{1132}Dobrı deò.
{1149}{1217}Som Mihael Lulicovicchi Nevskii.
{1294}{1310}Prepáè, Yuuta!
{1317}{1337}Je to moja chyba!
{1337}{1412}Poèkaj! Poèkaj! Neplaè, Mihael.
{1437}{1467}Zavolám ti nabudúce. Ahoj.
{1486}{1514}Yuuta sa hnevá.
{1526}{1565}Akoby som mohol.
{1596}{1787}TaSHee's Gang uvádí|MARGINAL PRINCE
{4170}{4247}Na ostrove v Atlantiku, ktorı je a moc |malı na to aby ste ho zbadali na mape,
{4290}{4338}všetci mui navštevujú školu |nazıvanú Akadémia Svätého Alfonsa
{4338}{4419}klamstvá sú tu oddelené od vonkajšieho sveta.
{4491}{4531}Nikto nevie kedy to zaèalo.
{4554}{4605}Ale záhadní študenti sú prezıvaní,
{4655}{4735}Princové hranic, Marginal Prince.
{4793}{4862}BOUØLIVİ CIZINEC
{5063}{5098}Obloha je váne zamraèená.
{5193}{5200}Yuuta.
{5242}{5251}Joshua!
{5266}{5313}Ak je tam búrka prázdniny zaènú od poobedia.
{5342}{5414}Vráme sa na ubytovòu skôr po skonèení poobednej hodiny.
{5427}{5446}Búrka?
{5472}{5511}Cez leto sa to v Japonsku stáva tie, však?
{5521}{5573}Akoby som to mal poveda. To...
{5596}{5626}Myslúš tajfún?
{5635}{5700}Správne. Haruya povedal, e je to podobné ako tajfún.
{5727}{5788}Na tomto ostrove sa to stalo raz.
{6119}{6165}Cudzinci sa objavujú poèas búrky...
{6206}{6232}D...duchovia?
{6257}{6358}Musel si poèu, e škola je vybudovaná| na starovekıch pozemkoch.
{6396}{6439}Toto bolo tréningové pole.
{6452}{6516}Legenda hovorí, e druhá |generácia princov z rodu Alphonsového
{6558}{6616}mali pár dôveryhodnıch podriadenıch.
{6651}{6679}Medzi nimi,
{6695}{6756}náhle niekto zomrel poèas búrky.
{6842}{6956}Táto nevinná duša sa objavuje poèas búrky.
{6973}{7037}Bude sa pohybova po školskıch pozemkoch.
{7447}{7482}Bojíš sa duchov?
{7500}{7549}To...to nie je pravda.
{7590}{7638}Teda...pôjdem do triedy.
{7709}{7767}Zdá sa, e sa hrozne bojí duchov.
{7791}{7853}To je prvı krát, èo som poèul o duchovi |objavujúcom sa poèas búrky.
{7866}{7890}Vymyslel som si to.
{7920}{7961}Búrka koneèné prišla,
{7982}{8018}preto je to šanca zabavi sa.
{8551}{8566}Koniec vyuèovania..
{8578}{8599}Rıchlo, rıchlo...
{9272}{9319}Joshua povedal, e sa mám vráti skôr.
{9338}{9392}Predtım ne sa duch objaví v škole.
{9412}{9440}Bude lepšie vráti sa èoskoro.
{9631}{9687}Mihael, èo sa deje?
{9713}{9806}Som oèarenı akı zvuk vychádza z tohto klavíra.
{9836}{9855}Je ten klavír pokazenı?
{9871}{9944}Neviem. Je vdy zamkunutı.
{9970}{9979}Zamknutı?
{10040}{10061}Váne, nemôem to otvori.
{10080}{10162}Myslím, e by sa to dalo otvori preto som chcel pomôc.
{10177}{10216}Zdá sa, e dodnes je to stále nemoné.
{10241}{10324}Nebolo by to skvelé, keby som |mohol poèu zvuk tohto klavíru?
{10432}{10459}Strana je hotová.
{10495}{10524}Ïalšia je vıchodná èas.
{10601}{10609}V poriadku.
{10690}{10711}Okej. Je tu.
{10733}{10764}Pod¾a plánu a opustím.
{10785}{10847}Hej, Hej. Si tak problematickı.
{11000}{11084}Je to tu tak strašidelné, keï nie je nik naookolo.
{11114}{11173}Pretoe škola je príliš ve¾ká.| Nikdy nevidím nikoho naokolo.
{11274}{11330}Poriadne som to zavrel.
{11422}{11445}Z...zober sa.
{11464}{11510}Duchovia vôbec neexistujú.
{11945}{11978}Nebolo to prive¾a?
{12045}{12095}Reakcia bola prehnaná.
{12136}{12181}Èoskoro sa musíme vráti do ubytovne.
{12199}{12253}Zobuïme Yuutu a poïme spolu.
{12275}{12281}Yuuta!
{12307}{12337}Vstávaj Yuuta.
{12397}{12433}Du...Duch!
{12452}{12525}Ospravedlòujem sa. Ten príbeh o duchoch som si vymyslel.
{12582}{12623}Všetky pasti nastrail Red.
{12764}{12827}Èo? Take tak sa to stalo.
{12867}{12923}Od oboch to bolo prive¾a! Vystrašili ste ma!
{12949}{13000}Hovoril som, e to bude problematické| a nechcel som sa toho zúèastni.
{13014}{13057}Napriek tomu si mi šastne pomohol.
{13169}{13181}Zmizlo to.
{13239}{13289}Tamte trik ma neoklame.
{13324}{13393}Zdá sa, e niekto je za búrkového poèasia na streche.
{13417}{13431}artík.
{13449}{13511}Okej. Poïme sa pozrie!
{13532}{13550}Tak problematické.
{13574}{13601}Nerobte to!
{13608}{13634}Len nás nasleduj!
{14111}{14144}Zabudnime na to. Rıchlo sa vráme.
{14172}{14202}Vrátime sa hneï ako skontrolujeme strechu.
{14439}{14479}Ja nechcem ís.
{14679}{14696}Nikto tu nie je.
{14906}{14999}Joshua spomínal, e tieto dvere neboli otvorené u roky.
{15051}{15104}Videl si to? Tieò.
{15252}{15285}Všetci traja sme zle videli?
{15309}{15347}Ne...nehovor mi...
{15367}{15417}Duch... a náradie.
{16592}{16642}Hudba zapnú.
{18051}{18069}Èo to robíte?
{18080}{18101}Èo tu robíte?
{18124}{18168}Prišiel som pre zákazníka, tak som sem prišiel.
{18188}{18249}Myslel som, e obèas sa stavi môem.
{18288}{18313}Leòoch.
{18331}{18361}Ako sa vám darí?
{18375}{18428}Niè špeciálne. Èo vám?
{18444}{18492}Sú èasy, keï je to fajn.
{18507}{18543}Len sa to mení, keï to prenikne ku mne.
{18551}{18577}Tak to funguje.
{18591}{18634}Zabudnite na povzbudzovanie.
{18711}{18750}Táto poste¾ je stále pohodlnejšia.
{19052}{19103}Prepáè, e meškám.
{19121}{19178}Keïe tam boli len 3 od vás zabralo to èas.
{19210}{19231}Refitpatorfin
{19297}{19321}To je zvuk piana.
{19347}{19421}Búrka sa blíi. Sú v škole ešte stále študenti?
{19454}{19470}Poïme sa pozrie.
{19586}{19597}Klavír.
{19621}{19661}Èo? Je tam niekto?
{19676}{19731}Nemyslím, e sú tu nejakí duchovia, však?
{19754}{19792}Ale....ten klavír.
{19834}{19864}Bol vdy zamknutı.
{19880}{19893}Nemôe hra.
{20108}{20136}Zdá sa, e to ide odtia¾to.
{20301}{20343}Kto je tam?
{20780}{20807}iadna odpoveï.
{20823}{20896}Nechjme to. Musí to ma rád, preto tu ostáva.
{20915}{20953}Ako to je moné?
{20972}{21025}Tieto dvere sa dajú otvori len z vonku.
{21052}{21094}Poïme vzia k¾úèe.
{21125}{21155}Bolo by to hrozné keby uviazol vo vnútri.
{21393}{21456}To...ten klavír...
{21491}{21529}Akı jemnı zvuk.
{22223}{22246}Poèujem ïalšie zvuky.
{22265}{22283}Je to zo spodného poschodia.
{22409}{22444}Prichádza to...sem.
{23066}{23110}Je to divné. Nemohli by otvorené.
{23127}{23174}Toto je tie zamknuté.
{23194}{23231}Tieto dvere nemajú zámky.
{23247}{23289}Èo budeme robi? Nemôeme to otvori.
{23300}{23361}Èoe?! Skús to znova!
{23387}{23411}Skús to ešte raz.
{23527}{23552}Stále sa nedajú otvori!
{23567}{23603}Je to zbytoèné. Nedajú sa otvori.
{23681}{23703}Je... to tu.
{23718}{23755}Dopekla. Všetci traja to skúsime spolu.
{23770}{23814}Dobre. Skúsme to všetci traja spolu.
{23902}{23917}Nejde to otvori.
{24026}{24055}Skonèili sme.
{24377}{24452}Haló, Yuuta, Yuuta.
{24474}{24542}To som ja.
{24788}{24796}Yuuta!
{24843}{24876}Nechajte ma to skúsi.
{24919}{24933}Yuuta?
{25011}{25029}Mihael!
{25085}{25112}Nevedel som, e to bolo v tomto prípade...
{25233}{25265}Klavír ducha?
{25275}{25297}Prepáè, je to moja chyba.
{25297}{25350}Klavír v tejto izbe je zamknutı a nedá sa otvori.
{25368}{25383}Však, Mihael?
{25408}{25421}Prepáè.
{25439}{25483}Ale popravde ten klavír hrá.
{25496}{25547}A izba je zamknutá z vonku.
{25603}{25669}O èo vlastne ide? Moje srdce bije.
{25683}{25717}Prosím chví¾u vydrte.
{25761}{25837}Po pravde toto vieme urobi...
{25871}{25914}Bude to rıchlejšie ak vezmeme k¾úèe z recepcie.
{25929}{25997}Ale je nemoné odís zo školy v tomto poèasí.
{26068}{26091}Zvuky prestali.
{26136}{26165}Je to otvorené.
{26398}{26414}Otvorím dvere.
{26897}{26949}Èo je to?
{27083}{27159}Ten klavír skutoène...
{27178}{27239}Nehovor to. Nechcem si to pripomína.
{27256}{27334}Sme spä na ubytovni. Je to v poriadku.
{27351}{27366}Mono.
{27436}{27446}Mono...
{27542}{27569}Nie je to mladı pán?
{27597}{27644}Je to dos dlho. Prestaò mi tak hovori.
{27657}{27723}Je to dlho Someya-sama.
{27745}{27843}Je to 18 rokov od vášho odmaturovania.
{27866}{27905}Vôbec si sa nezmenil.
{27918}{27941}Ospravedlòte ma.
{27966}{28010}Pravda. Toto.
{28054}{28125}Nes¾úbil som, e ti jedno dám ak sa stanem klavíristom
{28132}{28158}a vydám album?
{28205}{28257}Aj keï sa to vlastne nedá povaova za album, ale len za CD.
{28289}{28330}Stále si spomínate.
{28364}{28396}Potom to prímam.
{28411}{28471}Èasto som pozeral vaše záznamy.
{28504}{28596}Ak by sme mohli by ako predtım| bolo by skvel poèu vás hra.
{28896}{28949}Butler hrá na klavír.
{28992}{29023}Nevie hra.
{29050}{29148}Ako ostatní preto je hudobnı salón zavretı.
{29192}{29228}To... to je..
{32052}{32154}Pøeklad + korekce: Kirosaku Ayra|Èasování: WelW(etkaAa)-hime
{34066}{34104}Bouøka zmizela.
{34133}{34148}Úèet?
{34163}{34213}To jsou poplatky za autopùjèovnu.
{34228}{34244}Coe?
{34244}{34296}Je v poøádku bıt varovanı Butlerem.
{34296}{34364}To... Pøíštì znovu pouiju autopùjèovnu.
{34377}{34417}Mùu ze tebe zaplatit.
{34429}{34463}Jsi mùj zachránce, Sokurove.
{34463}{34487}No, pak si vyber.
{34487}{34548}Vracíš se s jednoprocentním zájmem nebo se tvım tìlem?
{34555}{34565}Tìlem.
{34582}{34624}Pøíštì, ZPUPNİ SMUTEK
{34680}{34703}Marginal princes.
