{1}{1}23.980
{199}{235}Hej, hej, Yuuto.
{262}{286}Jaká je kulturní vımìna?
{355}{397}Dobrı den, Sleèno.
{457}{471}To je Henri-san.
{490}{512}Jak to mùeš øíct?!
{528}{556}Musíš øíct "Ciao tam".
{590}{617}Henri, ty jsi Ital.
{631}{649}Ital?
{678}{731}To je Henriho kostımová postava.
{731}{756}Je to Ital.
{765}{845}Pøekvapivì krásná milenko jedovatıch bylin.
{876}{890}Fantastické, e?
{913}{955}Vskutku velice velmi vhodné pro mì.
{1045}{1056}Dìkuji.
{1078}{1108}Mìla by to bıt Grazie.
{1128}{1174}Sylvain-san je Japonec.
{1234}{1315}Ano. Haruya a já jsme bratøi samurajové.
{1338}{1363}Co to dìláš, Sylvaine.
{1377}{1387}Ah, tìší mì.
{1446}{1497}Wow, Haruya-san je vdy vhodnì obleèen.
{1514}{1551}Jsem velmi vdìènı za tvé chvály.
{1576}{1617}Nemìla bys mì taky pochválit?
{1635}{1702}Sylvaine-san... jak to øíct?
{1734}{1771}Máš postavu... eh...
{1782}{1810}Dotyk elegance....
{1826}{1888}Moje postava má bıt její zatímco| Sylvainova postava je...
{1899}{1920}Surfaø.
{2031}{2062}V pramici jsou zbranì.
{2071}{2108}Pøíjemná postava na cestách.
{2133}{2214}Je to samurajskı hrdina, o kterého|Sylvain usiluje bıt.
{2228}{2269}Nechápu, jak by nad tím mohl pøemıšlet.|(...a dítì, které jsem pøinesl...)
{2294}{2322}Opravdu?|(...to dítì je tak rozkošné...)
{2336}{2400}Hej, Joshuo, to je Yuutova sestra.
{2466}{2483}Tìší mì.
{2508}{2538}Co se dìje?
{2564}{2613}Joshua-san je tak odvánı.
{2633}{2650}Dìkuji.
{2663}{2745}Dle legendy, studentskı zástupce musí |bıt maskován jako Král Alphonso.
{2761}{2851}Jen pro tvou informaci, jsem pirát Arwen Tyler.
{2873}{2911}Je tak hezkı!
{2959}{2979}Kde je Yuuta?
{3002}{3033}Je to slavík.
{3051}{3090}Ne ta zdravotní sestra, je to pták.
{3116}{3162}Nechci, nechci, aby mì vidìla.
{3177}{3198}Nebuï tak blbı, Yuuto.
{3211}{3220}Yuuto?!
{3243}{3254}Joshuo pojï a pomo mi.
{3254}{3281}Jakı kostım máš obleèenı?
{3378}{3401}Nedívej se aneki.
{3450}{3647}TaSHee's Gang uvádí|MARGINAL PRINCE
{6024}{6102}Umístìnı v Tichém oceánu, ostrov,|kterı nemùe bıt nalezen na mapì,
{6147}{6188}kterı se nazıvá Akademie Sv. Alphonsa,
{6202}{6279}je nalazena na zemi opaèné oblasti.
{6345}{6386}Nevím, kdy to zaèalo,
{6401}{6463}tito klopıtající studenti mají obyèejné jméno,
{6510}{6593}Marginal Prince.
{6643}{6723}ZAÈÁTEK FESTIVALU
{7016}{7042}Mùeš pøijmout?
{7115}{7134}Je to jen ètení.
{8061}{8105}Tak mohutné, tak mohutné, vidíš!
{8118}{8145}Je to opravdu úasné.
{9125}{9159}Protivník je profesionál.... jo?
{9224}{9249}Bylo to na tebe tìké.
{9310}{9353}Protivník je pro tebe pøíliš obtínı.
{9384}{9414}Jen nechej zbytek na nás.
{9435}{9488}Brzy zjistíme souèasné umístìní tvıch rodièù.
{9551}{9613}Váháš?
{9636}{9703}Nevybral si's tuto misi dobrovolnì?
{9806}{9843}V tomto pøípadì byste mìl bıt uvolnìnı.
{9948}{9993}Musíš si opravdu uívat kulturní vımìnu.
{10014}{10062}Haruyo, na koho èekáš?
{10080}{10091}Na bratra.
{10137}{10160}Poslal jsem mu pozvánku.
{10197}{10237}Ale moná nepøijde.
{10268}{10285}ádnı problém.
{10301}{10321}Urèitì pøijde.
{10321}{10334}Tvùj bratr.
{10362}{10371}Yuuto.
{10402}{10412}Díky.
{10438}{10527}Zpoèátku jsem si myslel, e si zabalíš|a odjedeš do Japonska.
{10559}{10604}Nemùeš nijak pøeít na Akademii Sv. Alphonsa.
{10638}{10690}Ale nakonec jsi tady stále s námi.
{10716}{10769}Vypadá to, e jsem se pøepoèítal.
{10791}{10830}Musí to bát zarmucující se pøepoèítat.
{10848}{10864}Je to naopak.
{10869}{10880}Huh?
{11075}{11093}Vaše Velièenstvo!
{11256}{11314}Vaše maskování je fantastické.
{11328}{11369}Neznevaujte mì, jsem kuøátko.
{11927}{11936}Sokurove!
{11984}{11998}Proè se to dìje teï...
{12264}{12275}Ty!
{12333}{12351}Já.
{12387}{12436}Protivník je pro tebe pøíliš obtínı.
{12476}{12538}Jen chci ochránit vìci, které jsou mi nejdraší.
{12930}{12962}Neváhej.
{12983}{12991}Poèkej!
{13393}{13419}Pojï a pomoz mi.
{13446}{13493}Ochranka ostrova leí v tvıch rukou.
{13546}{13630}Myslel jsem si, e pracovat na malém| ostrovì bude uvolòující práce.
{13662}{13697}Všechno je to kvùli Marginal Prince.
{13697}{13748}A ty nás musíš po celou dobu obtìovat,|ze skupiny v zákulisí.
{13773}{13845}Opravdu. Je více uvolòující zùstat v armádním oddíle.
{13881}{13921}Není to kadoroèní kulturní vımìna?
{13931}{13961}Ale stále si ji neumím uívat.
{14003}{14096}Ve srovnání s kulturní vımìnou,|jsem zajímavìjší ne tohle.
{14126}{14189}Pojï, nech mì slyšet, co musíš øíct.
{14465}{14485}Bráška je tak rozkošnı!
{14485}{14515}Tvùj kostım je fantastickı.
{14599}{14609}Enju?
{14672}{14706}Enju!
{14744}{14776}Velice se omlouvám za pøedchozí záleitost.
{14807}{14831}Proè se omlouváš?
{14852}{14893}Protoe jsem na tebe tlaèil,|aby si's dal se mnou veèeøi.
{14923}{14968}Aèkoli na tebe všichni rozrušenì èekali.
{15015}{15057}Nepøeji si tu zùstat.
{15082}{15144}Neøíkej mi, e ti vadí sdílení bytu.
{15185}{15254}Nepotøebujeme to, všichni jsme studenti na jedné škole.
{15281}{15346}Po této vımìnì by všichni mìli jít na oslavu.
{15367}{15391}Enju by mìl jít taky.
{15401}{15427}Jen to vem jako odškodnìní za poslednì.
{15444}{15452}Ok?
{15496}{15512}Kdybych mohl jít.
{15529}{15592}Budu se na to tìšit. Uvidíme se pozdìji.
{15631}{15721}Ah, skoro jsem zapomnìl. |Pozdìji budeme hrát hru v divadle.
{15749}{15781}Enju, musíš pøijít a podívat se.
{16002}{16023}Mám jedinou cestu.
{16840}{16863}Princi Joshuo Grante,
{16894}{16927}po vaší promoci
{16938}{16993}vás Král Cardiss I. plánuje jmenovat jako dalšího dìdice.
{17009}{17088}Královská rodina vás formálnì uvítá.
{17110}{17167}Jeho Velièenstvo si pøeje vidìt Korunního|Prince pøedtím, ne odejde.
{17198}{17291}A bude konec slavnosti Akademie Sv. Alphonsa,|budeme oèekávat vaši odpovìï.
{17340}{17396}Pøedtím se prosím rozhodnìte.
{17567}{17606}Potom, udìlej co si pøeješ.
{17664}{17690}Ano nebo ne?
{17708}{17731}Nedávej mi nejasnou odpovìï.
{17777}{17834}Já nevím, nevím co chci.
{17859}{17893}Nechci odvahu vystoupat na trùn.
{17924}{17949}Nìco je znepokojení.
{17970}{18009}Opravdu nechci utéct.
{18035}{18093}Pak to jen odmítni, jednoduché jako tohle.
{18128}{18173}Ale tohle je povinnost, kterou musím nést.
{18227}{18269}Cítím, e tuhle povinnost musím pøijmout.
{18309}{18348}Tak ji pøijmi.
{18364}{18372}Henri.
{18401}{18422}Zašel tento vtípek pøíliš daleko?
{18449}{18472}Øekl jsem to pøedtím.
{18506}{18564}Krev a jedincova vùle musí bıt jako jeden.
{18606}{18641}Ten, kterı dìlá koneèné rozhodnutí jsi stále ty.
{18718}{18731}Rozumím.
{18765}{18784}Aèkoli rozumím,
{18862}{18895}co bych mìl opravdu udìlat?
{18958}{18978}Co dìlat?
{19006}{19052}Je tam tolik divákù.
{19073}{19109}Je to ivı ruch.
{19132}{19162}Opravdu potøebujeme diváky.
{19186}{19198}Poèkej.
{19225}{19252}Je to pøírodní talent.
{19295}{19341}Protoe nevím o hrách nic.
{19380}{19416}Je to stále lepší, ne bıt jednoduchı idiot.
{19461}{19505}Necítíš, e je Henri podivnı?
{19519}{19540}Jo.
{19562}{19595}Nezáleí na tom v dobách klidu.
{19666}{19693}Máš nìjaké spojení a bratrem?
{19717}{19739}Bohuel ne.
{19768}{19815}Opravdu. Díky Butlere.
{19909}{19954}Opravdu nepøijel.
{19990}{20035}Je to pøíznívá vìc bıt schopnı se spojit s milovanımi.
{20082}{20125}I kdyby to vyadovalo èas.
{20326}{20366}Nehıbej se.
{20430}{20502}Bude to bránit zotavení tìch zranìní.
{20772}{20827}Všichni, jen pìt minut do zaèátku hry.
{21036}{21054}Jeho Velièenstvo.
{21054}{21079}Král Cardiss I.!
{21079}{21109}Král!
{21126}{21147}Tak hezkı!
{21254}{21314}Poèkat, poèkat, poèkat, není to...
{22053}{22120}Král Cardiss I.
{22382}{22462}Cardiss I., neèekal jsem, e pøijdeš osobnì.
{22501}{22516}Jsi v poøádku?
{22525}{22535}Joshuo.
{22563}{22616}Ah, jsem jen trochu nervózní.
{22687}{22762}Slyšel jsem, e tohle je amulet, tak si ho vem.
{22779}{22830}Díky za tvé povzbuzení.
{22976}{22999}Vıbornì, zaènìme!
{23284}{23438}Já vím. Mé srdce bylo dojaté.
{23484}{23635}Tvá láska se tøepetá v mém srdci.
{23701}{23765}Kdy jsem v noci sám,
{23805}{23871}plaèící sám v noci.
{23904}{24065}Myslet na tvùj úsmìv mì pøivádí do ivota.
{24111}{24209}Nezáleí na tom jak daleko jsme od sebe,
{24249}{24310}je tu láska.
{24323}{24415}Od koncù svìta,
{24455}{24519}ti to bylo posláno.
{24519}{24601}Mé upøímné modlitby
{24635}{24718}budou pokraèovat ve zpívání.
{24748}{24913}Miluji tì, navdy budu milovat jen tebe.
{24952}{25182}Z hlouby mého srdce se má láska|nikdy nezmìní. Dnes veèer.
{25573}{25590}Bratøe!
{25682}{25706}No tak, pojïme!
{25730}{25756}Nechte nás pøekroèit tento oceán!
{25812}{25856}Vypadá to, e je to velmi dlouhá cesta.
{25931}{25986}Prosím, dávej pozor, bratøe!
{26112}{26131}Díky, Mihaeli.
{26142}{26158}Za udìlání tak velké laskavosti.
{26172}{26200}Take je to dobré?
{26214}{26271}Samozøejmì, vedl si's velmi dobøe.|Je to velice slušivé.
{26313}{26383}Potom, budu schopnı dívat se z obecenstva.
{26405}{26430}Dìlej co mùeš, Yuuto!
{26446}{26454}Jo.
{26787}{26818}Jste v poøádku, sleèno?
{26860}{26883}Proísm, dejte mi svou ruku.
{26974}{27025}Omlouvám se, je to moje chyba.
{27099}{27119}Toto je budoucnost tohoto malého ostrova.
{27143}{27169}Budoucnost, která je vytvoøena z vašich rukou.
{27192}{27214}Tento ostrov je opravdu
{27231}{27276}místo praskající nadìjemi a sny.
{27307}{27372}Já... tvoøím budoucnost?
{27405}{27451}Mohu udìlat takové vìci?
{27480}{27519}Nemám prostı dibec energie.
{27541}{27588}Teï jsi tady.
{27618}{27667}S nièím se to nesrovnává.
{27700}{27803}Nevidìl jsi novou cestu vytvoøenou|právì teï pøed tebou?
{27846}{27894}Toto není jediná cesta.
{27922}{27959}Jen si nemusíme všimnout dalších cest.
{27992}{28035}Je to jen to, èeho jsme si nevšimli.
{28146}{28172}Bylo to na vás tìké.
{28196}{28238}Prosím, odpoèiòte si.
{28392}{28429}Cítím se jít to umıvárny.
{28544}{28564}To není dobré.
{28657}{28715}Yuuto, co se dìje? Nervozita?
{28731}{28741}Aneki.
{28764}{28822}Proè jsi tak nervózní?
{28844}{28872}Ah, jsi opravdu nervózní.
{28872}{28941}Vdycky jsi byl nervózní osoba.
{28958}{28990}NE!
{29006}{29044}Ok, ok, pøestaò to pøede mnou schovávat.
{29062}{29135}V této dobì, napiš si to na dlaò.
{29164}{29187}Ah, teï jen zvládni od toho neutéct.
{29208}{29237}Nìkdo fotí.
{29262}{29318}To by mìla bıt památka pøedtím ne zaène hra.
{29339}{29366}U zaèala!
{29483}{29513}Slyšel jsi nìco?
{29531}{29579}Zlomenı ocas ještìrky je bezcennı.
{29634}{29740}Take to znamená, e bych nemìl spoléhat na tu osobu |s jakoukoli informací. Nejsem tak hloupı.
{29770}{29832}Take jsi z nìj nezvládl nic dostat? Jen to pøipus.
{29852}{29906}Jsem si jistı, e jsem se na nic neptal.
{29985}{30031}Jsi vdycky taková. Hlupaèko.
{30053}{30123}Promiò, zapomnìla jsem na letní èas.
{30158}{30180}Opravdu.
{30196}{30257}Cítím, e je nìco špatnì.
{30276}{30340}Nìkdo nìco intrikuje.
{30362}{30407}Je nìco špatnì s dìdicem trùnu Krále Cardisse I.?
{30430}{30457}Je tu nìco špatnì?
{30457}{30486}Nenáleí Joshuovi?
{30501}{30530}To je tak, jak jsem sesbíral.
{30541}{30559}Take to znamená.
{30588}{30635}Cílem atentátu je...
{30659}{30674}Atentát?
{30701}{30722}Co je, Yuuto?
{30756}{30773}Kdo je to?
{30862}{30889}Další host.
{30908}{30931}Je to velice populární.
{30951}{30978}Musíš si dìlat legraci.
{30989}{31008}Je èas zaèít pracovat.
{31200}{31245}Poèkej chvíli, co se dìje, Yuuto?
{31275}{31302}Právì teï jsi zmínil atentát.
{31313}{31337}Take to znamená...
{31362}{31408}Take cílem je Joshua?!
{31428}{31463}Co se dìje s Joushuou-san?
{31475}{31524}Není to dobré. Linka je stále pøipojená.
{31537}{31554}To není dobré, co to znamená?
{31565}{31621}Nic. Jen si mumlám pro sebe.
{31648}{31663}No tak, aneki.
{31678}{31694}Poèkej, Yuuto!
{31767}{31781}Yuuto!
{31866}{31895}Yuuto!
{32096}{32200}Pøeklad + korekce: WelW(etkaAa)-hime|Èasování: WelW(etkaAa)-hime
{34088}{34107}Pøíští epizoda:
{34120}{34140}Promiò, aneki.
{34159}{34210}Aèkoli si pøeju øíct ti pravdu, |ale musím to na chvíli zachovat.
{34232}{34242}Protoe...
{34265}{34281}Nakonec jsem kluk.
{34306}{34329}Yuuto!
{34343}{34400}Jak se opovauješ jít proti mnì,|jak se opovauješ?!
{34413}{34455}Seer si to! Vícenásobné útoky!
{34498}{34528}Tìší mì, jsem Joshua.
{34559}{34606}Pøíští kolo, OSLNIVİ POTLESK
{34633}{34688}Promiòte, špatné èíslo.
{34758}{34770}Eh?
