{1072}{1177}"Yanbaru" je Okianwské slovo,které znamená les nebo hora.

{1177}{1200}Nech to tak.

{1177}{1230}A "kuin" je chřástal.

{1252}{1334}Takže Yanbarská kuin je chřástal, který ...

{1507}{1559}Pravděpodobně tu nikdo neni.

{1576}{1611}Něco sa tu stalo.

{1611}{1645}To je jasné.

{1669}{1717}Ne,takže otec je...

{1776}{1793}Tudy.

{1842}{1916}Když bylo toto místo vybudováno, obrovské množství zeme bylo odstraněno.

{1958}{2004}To bylo moudré maskování, ale ...

{2364}{2415}Toto je vchod do suterénu.


{4779}{4890}Otcovi ruce.

{4917}{4966}Nedospěli jste už k závěru?

{4981}{5062}Jestli se neunáhlíte, Okinawa bude zaplavena myšmi.

{5074}{5187}Veliteli,věřím že dále už nemáme jinou alternativu Jako Možnost D.

{5210}{5244}Pokud počkáme trochu déle,

{5248}{5306}nebudeme schopni zabránit před verejností existenci Myší.

{5454}{5477}Rozumím.

{5515}{5611}Nic jiného bych nečekal od světové policie,která má hlavní moc.

{5612}{5650}Skvostné rozhodnutí.

{5675}{5730}Podle možnosti by jsem to raději nepoužil,

{5731}{5764}Monsiňore Argeno.

{5772}{5892}Tato operace může zničit naše velmi dobré vztahy s Japonskem.

{5916}{5978}To je to,za co máte Status of Forces Act, že?

{5988}{6082}Důležitejší problém tu,jsou Myši a Delta 67.

{6083}{6200}Pokud je vyženeme, váš nejvyšší velitel bude po tom všem propuštěn.

{6286}{6412}Richard Brickman,dnešní kód je Tango Alpha Echo 0307.

{6422}{6486}Nařizuji vám vykonat Možnost D.

{6500}{6524}Ano pane.

{6525}{6540}Okamžitě.

{7823}{7849}Kde je otec?

{7865}{7898}Zrovna ho hledám.

{8012}{8076}Přemýšlím zda Saya-neechan najde Očka.

{8089}{8113}Nevím.

{8139}{8257}Jakmile se táta vrátí můžeme se vrátit zpět k našim obyčejným životům, že?

{8313}{8368}Ještě mám Atsuchiho hru,

{8381}{8451}a neřekl jsem mu nic o tom že odcházím pryč.

{8472}{8497}Můžeme.

{8516}{8544}Jsemm si tím jistý.

{8606}{8666}Proč se tohle stalo?

{8677}{8701}Nevim.

{8710}{8767}Od tý doby co se ti příšery Chiropterani nebo lidi se,ukázáli,

{8778}{8815}jsou věci na hovno.

{8823}{8846}Co?

{9102}{9120}Co se stalo?

{9183}{9266}Americká armáda zamýšlí zničit Yanabaru leteckým bombardováním za 3 hodiny.

{9284}{9302}Takže...

{9313}{9366}Mluvíš o Yanbaru?

{9418}{9500}Celá oblast je zablokovaná,nemůžem ho kontaktovat.

{9513}{9638}Cesta 58,je najkratší,ale je zablokovaná a autem to nezvládneme včas.

{9654}{9680}Pôjedeme na motorce.

{9706}{9770}To je všecho co právě teď můžem udělat?

{10090}{10104}Sayo...

{10116}{10134}Vydrž!

{10582}{10622}Diva tu neni?

{10663}{10698}Dozvěděli se něco?

{10727}{10844}Zdá se že zde, v Americké armádě běží experimenty na umělé vytvoření Chiropteranů.

{10876}{10902}Na co?

{10914}{10952}Podle našich záznamů,

{10968}{11084}už do války s Vietnamem tu bylo mnoho incidentů s Chiropterany.

{11107}{11170}Celosvětový několikaletý případ.

{11201}{11242}Avšak začátek této války,

{11251}{11341}obnáší informaci o vzhledu Chiropteranů a na to se začala zvětšovat jejich úroveň,která může být nazvána skoro bizardní.

{11384}{11440}A skoro s 100% přesmostí,

{11451}{11556}všechny tyto výskyty sa konali v oblastech z medzinárodním konfliktem.

{11568}{11590}Vietnam.

{11591}{11616}Střed-Jižní Ameriky.

{11617}{11647}Válka v zálivu.

{11648}{11676}Africká občanská válka.

{11688}{11709}Tolik?

{11726}{11740}Ano.

{11758}{11822}A v těchto místech,

{11823}{11931}nehledě na cenu, buď Americká armáda nebo Americká armáda-vedená mezinárodními silami byla rozmístěna.

{12082}{12117}Americká armáda?

{12118}{12128}Proč?

{12147}{12184}Mir.

{12184}{12208}Odplata.

{12214}{12246}Spravedlnost.

{12286}{12315}To mohou být důvody,

{12324}{12422}ale jistě se dá říci že skutečným cílem bylo armádní okupace oblasti.

{12442}{12461}A ješte jeden krát...

{12574}{12660}Pokud je přítomnost Chirtopteranů potvrzena v některé z těchto oblastí,

{12671}{12758}Americká armáda vyšle nějvětší množství pěchot právě tam.

{12782}{12814}A každý z nich,

{12815}{12931}bez výjimky, projde přes určitý základ na vzdáleném východě dříve než tam přijdou

{12940}{12959}Myslíte...

{12970}{13005}Ano,Okinawa...

{13034}{13066}Co je to tu?

{13088}{13140}Přišli jsme to sem přezkoumat.

{13191}{13222}Delta 67?

{13450}{13500}Přeložil : Dante

{13652}{13681}Sayo,bojuj!

{13718}{13740}Tas svůj meč!

{14205}{14222}Pojďme!

{14253}{14282}Pojďme hledat Georga!

{14286}{14302}Rychle!

{15076}{15110}Naše úniková cesta je odříznutá.

{15149}{15184}Promiňte.

{15184}{15201}Já...

{15224}{15262}Zabij nebo buď zabit!

{15278}{153724}Na bojišti jde tvůj život na úkor životů tvých oponentů.

{15382}{15465}Potřebujeme tam myslet pouze na přežití.

{15774}{15848}Za dvě hodiny budeme hotový.

{15862}{15882}Chápu.

{15898}{15925}Ale je to příliš zlé.

{15938}{16030}Zdá se že nemám čas na to, zůstat zde a vidět všechny ohňostroje.

{16050}{16135}Dostal jsem zprávu ze společnosti odejít k dalšímu místu.

{16162}{16194}Opouštíte nás přímo uprostřed?

{16226}{16266}Věřím vám.

{16302}{16397}Jako dobrý partner, modlím se za váš úspěch.

{16418}{16459}Au revoir,velitei.

{16964}{16988}Jen klid.

{17132}{17190}Vezmi to a bež k výtahu.

{17215}{17305}Mnoho mých společníků pro to zemřelo.

{17322}{17376}Musí to být přineseno zpět bez ohladu na to.

{17452}{17482}David-san, vy...

{17515}{17548}Vysvetlím ti plán.

{18201}{18212}Pojďme.

{18523}{18534}Rychle!

{18862}{18877}Příliš pomalé.

{19008}{19022}George!

{19233}{19306}To máte za to,že jste se chtěli dotknout mojí dcery!

{19320}{19346}Očko!

{19354}{19404}Hej,byla si dobrá?

{19475}{19497}Chápu.

{19497}{19538}Nechali jste tam Rika a Kaie?

{19538}{19555}Ano.

{19556}{19608}Více důležité je, jak jsou na tom tvoje zranění?

{19613}{19655}Když jsem se probral byly zahojené.

{19698}{19743}Víš co je D67?

{19804}{19846}Dali to do mé IV.

{19881}{19906}Delta 67.

{19932}{19951}Chápu.

{19960}{19985}Víš to?

{20290}{20322}Luisi,to jsem já!

{20322}{20338}Kaii.

{20341}{20353}Nestřílej!

{20370}{20390}Kaii?

{20402}{20432}Kde je Saya a ostatní?

{20432}{20473}Ještě jsou v centru.

{20488}{20542}Julie povídala,že chtějí Yanbaru zbombardovat!

{20564}{20586}Počkej!

{20606}{20646}Je to zablokované.

{20646}{20679}Nežertuješ?

{20679}{20698}Hey,Kaii.

{20699}{20722}Jdu jim o tom říct!

{20726}{20749}H-hej!

{21065}{21122}Pokud musím něco říct, je mi líto že odsud odcházím,

{21129}{21186}myslím že se nepotkám s tím samuraji.

{21431}{21454}Proč?

{21474}{21522}Proč jede výtah dolů?

{21528}{21544}Nevím.

{21559}{21584}Začalo to jít dolů.

{21584}{21634}Ok,počkejte až do té chvíle!

{21807}{21836}Co děláš? Sayo!

{21852}{21865}Správně.

{22135}{22178}Zatlačíme je k tomu vzduchovému uzávěru.

{22698}{22716}Zvládli jsme to!

{22830}{22861}SAYO!

{22926}{22957}Oteče?

{23048}{23112}TY PRÍŠERO!

{23557}{23582}Očko!

{23582}{23598}George!

{23836}{23851}Oteče?

{23884}{23902}Ne...

{24115}{24136}Máme problémy!

{24137}{24170}Tohle místo se chystají zbombardovat!

{24180}{24205}Zbombardovat?

{24258}{24274}Kaii...

{24360}{24379}Nie...

{24393}{24411}Nikdy!

{24479}{24496}Kaii...

{24510}{24533}Jsi tu?

{24582}{24599}Oči.

{24628}{24657}Je to divné,huh?

{24736}{24752}Ja...

{24762}{24840}Skončím jako příšera,přesně jako Forest.

{24908}{25062}Jak se moje zranění léčí,cítím jak moje vědomí slábne.

{25184}{25208}Sayo...

{25264}{25312}Jen tyto můžeš udělat.

{25328}{25407}Zabíjí tvoje krev tyhle příšery?

{25418}{25478}Smíchej to se svojí krví,

{25500}{25618}tak ještě můžu zemřít jako tvůj otec.

{25700}{25720}Sayo,

{25748}{25800}rozhodni se.

{25814}{25872}Hej, nemůžete něco udělat?

{25941}{25971}Do řiti...

{25990}{26022}Do řiti!

{26072}{26116}DO ŘITI!

{26414}{26430}Davide.

{26450}{26464}Prosím.

{26602}{26620}Sayo!

{26632}{26690}Myslím že by si si měla pospíšit.

{26876}{26902}Nemůžu!

{26910}{26942}Nemůžu to udělat!

{27036}{27053}Sayo,

{27068}{27128}Jsem ješte tvůj otec?

{27354}{27404}Kaii,neplač.

{27428}{27478}Ty idiote,jsi přece muž!

{27503}{27558}Dávaj pozor na Rika a Sayo!

{27567}{27588}Oteče...

{27732}{27748}Sayo,

{27762}{27842}ať se stane cokoli, dělej to co myslíš že je správné.

{27864}{27906}Příjmi svou minulost.

{27922}{28016}A pokud zakopneš, pamatuj si, zvedni se.

{28040}{28098}Žij dnes pro zítřek...

{28117}{28160}Nezapomeň na to.

{28352}{28378}Očko!

{28702}{28742}Očko!

{29034}{29062}Očko...

{29128}{29150}Očko...

{29168}{29205}OčKO!

{29500}{29574}Žij dnes pro zítřek.

{29597}{29648}Nezapomeň na to.

{29937}{29998}Neztratila kontrolu?

{30008}{30105}Saya si jen vzpomněla co musí udělat.

{30131}{30170}Pro záchranu, což je důležité.

{30196}{30256}Pro to,ona sama bojovala po celou tu dlouhou dobu ...
