{1}{1}23.976
{2254}{2362}Miketsukamiho transformace
{2401}{2539}Bylo to chvíli poté, co jsme spolu já a Miketsukami zaèali chodit.
{2565}{2589}Tady máte.
{2625}{2651}D-Dìkuji ti.
{2683}{2733}Oh, Ririchiyo...
{2755}{2784}To je tyèka.
{2850}{2886}N-Nesmìj se!
{2899}{3015}Omlouvám se, byla jste tak roztomilá, nemohl jsem si pomoci.
{3072}{3093}T-tohle nejde.
{3094}{3166}Jsem tak nervózní, a ze sebe dìlám hlupáka.
{3168}{3237}Moná spolu teï chodíme,
{3240}{3305}ale já se cítím nejistìjší ne kdy døív.
{3453}{3536}Jsme tu sami, v obrovské místnosti.
{3562}{3601}Jsem nervózní.
{3604}{3666}Chovám se, jako bych nìco skrıvala.
{3908}{4000}Ririchiyo-sama, nejste nervózní?
{4004}{4034}J-jistì e ne!
{4052}{4121}Z jakého dùvodu bych mìla bıt nervózní pøed teb-
{4172}{4268}C-co to bylo?
{4274}{4289}Omlouvám se.
{4294}{4430}Vaše nervozita ve mì vzbuzuje nezbedu.
{4436}{4484}Chtìl jsem vás poškádlit.
{4507}{4519}Nedìlej to.
{4579}{4627}Jsme tu sami e?
{4699}{4747}Dovolte mi vám to tu zpøíjemnit.
{5098}{5119}On...
{5203}{5227}Roztomilı.
{5323}{5347}Co myslíte?
{5395}{5538}N-No, není to tak e bych byla nervózní, take tohle není nutné,
{5541}{5706}Ale jsi moc velkı. Takhle je to lepší, uznávám.
{5709}{5754}Jsem poctìn vaši chválou.
{5824}{5944}Ririchiyo-sama, Ririchiyo-sama, milujete mì?
{5946}{6018}Prosím øeknìte: ''Miketsukami-kun, miluji tì.''
{6050}{6098}P-Proè to chceš slyšet teï?
{6122}{6162}Vy mì nenávidíte?
{6354}{6408}Samozøejmì e tì miluju.
{6426}{6521}Ririchiyo-sama, v tom pøípadì mì drte pevnìji.
{6545}{6567}Dobøe.
{6569}{6607}Hlaïte mì.
{6617}{6650}Neøíkej døív ne budu hotova.
{6701}{6833}Jste tak hebká.... a tak hezky voníte.
{6857}{6953}Ne tak rychle! Je ti 22! Jsi dospìlı!
{6955}{7049}Málem jsem se v tom ztratila. Proè jsem JÁ skonèila staráním se o TEBE?
{7051}{7121}Co se dìje, Ririchiyo-sama?
{7145}{7193}To u nebude fungovat!
{7195}{7337}Já ti nevìøím. Jsi oportunista co? To se ovšem dnes nestane.
{7339}{7457}Vidím, to je škoda. V tom pøípadì...
{7528}{7582}Co tohle?
{7582}{7684}Bude lehèí relaxovat a komunikovat se stejnım pohlavím?
{7699}{7768}T-ty se mùeš promìnit také v enu?
{7771}{7876}Ano. Ujišuji vás e jsem ena, jak zvenku tak uvnitø.
{7912}{8020}Chcete se ujistit? Jsem vdy pøipravena ukázat vám vše,
{8020}{8125}je jedno kdy a kde.
{8136}{8176}Toho mì ušetøi.
{8200}{8320}Ale musím pøiznat, ona/on má skvìlou postavu.
{8320}{8398}Úchvatnou, pøesnìji. Pøipadám si ménì jako dívka.
{8398}{8464}Ririchiyo-sama, mùeme zaèít lekci?
{8464}{8523}L-lekci?
{8535}{8679}Pøesnìji, pomoci vám zvyknout si na intimní kontakt.
{8721}{8751}Co to dì--
{8751}{8823}Drahá, proè jsi zèervenala?
{8847}{8895}Jsme tu jen my, dvì holky, nemusíš se stydìt.
{8895}{8997}T-ty narušuješ mùj osobní prostor! Co má tohle za smysl?
{8997}{9111}Jak jsem øekla, cvièíme aby jsi se necítila nervózní.
{9111}{9255}Náš vztah sotva zaèal. Pozdìji toho mùeš oèekávat víc.
{9279}{9375}Myslela jsem, e bychom na to mohli jít lehce, aby ses nebála.
{9399}{9447}N-na co...?
{9471}{9542}Jestli na mne reaguješ takto nyní,
{9542}{9638}mohu si pouze pøedstavit jaké to bude a se transformuji zpátky.
{9638}{9710}Ah, to mì vzrušuje ještì víc.
{9710}{9739}Nebuï tak nemravnı!
{9739}{9926}Já pouze plním svou roli tvého sluhy a milovníka tím,
{9926}{9998}e se tì pokouším uvolnit.
{10070}{10118}Proboha, já jsem tak ospalı.
{10166}{10214}A kdy nejsi?
{10717}{10813}Tlaèítko
{10957}{11011}Já se strašnì nudím...
{11011}{11077}Jo, to jsem taky zail.
{11101}{11149}Nedá se tu nìjak zabavit?
{11149}{11209}Já mám nìco na práci.
{11508}{11532}Ding-dong.
{11544}{11580}Maniac!
{11676}{11772}To je mùj ''zaèni imitovat Noboru'' èudlík.
{11820}{11868}Ding-dong.
{11868}{11916}Maniac!
{11916}{11940}Ding-Dong
{11940}{11964}Maniac!
{11964}{11988}Ding-Dong!
{11988}{12012}Maniac!
{12108}{12132}Hele nech toho koneènì.
{12132}{12156}Ding-dong
{12180}{12300}To bylo tlaèítko na pøepnutí mıch lenivıch pohybù na akèní!
{12348}{12372}Ding-dong!
{12372}{12396}Maniac!
{12420}{12539}Co to ty dva dìlají? Chovají se jako dìti...
{12659}{12683}C-co?
{12809}{12827}Pích.
{12971}{13045}Ty po mì chceš abych zaèal nìkoho imitovat?
{13045}{13103}Ale já si nic nepøipravil...
{13163}{13193}Tohle je...
{13193}{13283}tlaèítko ''mìj mì víc rád''.
{13307}{13367}K-Karuta...
{13376}{13451}Ale já si nemyslím e bych tì mohl mít radši ne u mám...
{13471}{13498}Málo. Víc.
{13546}{13582}Karuta...
{13762}{13882}T-to bolí...ale... jsem tak šastnı...
{14074}{14122}To je sranda...
{14146}{14242}Vrátil jsem se! Mùj lidskı noèníku!
{14314}{14386}Je to... e to není mùj odpad, co támhle zkolaboval?
{14386}{14458}Co to mohlo zpùsobit? Nehoda?
{14458}{14482}Pích.
{14625}{14649}Lidské noèníky.
{14721}{14769}Lidské noèníky
{14913}{15009}Ah, ano. Mám pro tebe dárek! Je to Sanuki udon!
{15009}{15057}Sanuki udon!
{15057}{15105}Dìkuji, Kage-sama.
{15129}{15177}Skvìle, skvìle!
{15201}{15225}Lidské noèníky
{15369}{15441}Lidské noèníky|Lidské noèníky
{15441}{15465}Li-Lidské. Li-Lidské.
{15465}{15512}L-L-L-L-L-L-
{15512}{15536}Lidské noèníky.
{15752}{15776}Dobytku.
{15800}{15824}Ding-dong!
{15824}{15836}Maniac!
{15836}{16016}Dobøe pøestaò u. Pøestaò u koneènì!|Ding-Dong. Ding-dong. Ding-dong.
{16022}{16064}Vy dva se rozhodnì bavíte.
{16066}{16088}Závidíš?
{16088}{16184}Ne, ani trošièku. Po pravdì, vidìt kluka s klukem je hnus.
{16184}{16232}Zemøete. Oèistìte tuto zem.
{16232}{16304}Aw, Nobora-chan. To nebylo pìkné!
{16529}{16549}Co je?
{16591}{16639}Ding-dong.
{16789}{16908}To bolí. Pøestaò. Pøestaò.
{16927}{17023}Kadopádnì nemáš studovat na test?
{17023}{17047}Co tu dìláš?
{17047}{17119}Huh? Mám pøestávku.
{17149}{17239}Pøestaò dìlat kraviny a mrhat èasem. Vra se do pokoje.
{17239}{17263}Pospìš!
{17479}{17598}Má snoubenko! Vydr, nech mne zmáèknout toto!
{17934}{18006}Uvnitø èi venku, nikdo není v bezpeèí.
{18006}{18054}Vskutku.
{18054}{18174}Vypadá to, e všichni hrají tu hru celı den.
{18174}{18222}Zajímalo by mì, kdo s tím zaèal.
{18222}{18318}Yukinokouji-san mì píchla u mockrát.
{18869}{18965}Toto tlaèítko aktivovalo opodìnou reakci.
{18989}{19061}Vše se stane ve správnı èas. Pøipravte se.
{19205}{19253}Myslím e budu tady.
{19445}{19564}Hra na rodinu.
{19948}{20001}Tohle je moje mladší sestra, Hana.
{20001}{20068}Naše matka má nìco na práci, tak jsem ji vzal s sebou.
{20068}{20146}Boínku není roztomilá?
{20164}{20284}Take ty se o ní teï staráš? Celkem jsi dospìl.
{20286}{20332}Ani ne. Je to mùj údìl jakoto staršího bratra.
{20350}{20428}Èièièi
{20428}{20464}Ona není zvíøe.
{20499}{20523}Je celkem rozkošná.
{20523}{20580}Ty máš rád dìti?
{20580}{20715}Ne, ovšem kdy si pøedstavím tebe jako malou...
{20715}{20787}tak sladká a rozkošná...
{20811}{20846}Prosím, vra se do reality.
{20907}{20979}Fajn. Tak si zahrajeme nìco spoleènì.
{21003}{21051}Hana-chan, co chceš hrát?
{21051}{21123}Bráška si s námi chce hrát, co bys chtìla?
{21219}{21280}N-na rodinu.
{21315}{21363}Take, jaké jsou naše role?
{21459}{21530}Bratøíèek je taka.
{21531}{21554}Take ty si mamka?
{21554}{21578}Malá sestøièka
{21698}{21746}Hana chce bıt tvojí malou sestøièkou.
{21746}{21842}Take ona chce bıt tvou sestøièkou nehledì na okolnosti co?
{21842}{21890}Ona rozhodnì miluje svého bratra.
{21890}{21986}V tom pøípadì otec ije se svou sestrou a poèetnou rodinou.
{21986}{22034}Jak je na tom rodina s penìzi?
{22058}{22130}Nemusíš zacházet tolik do detailù.
{22154}{22202}Onee-chan, ty jsi mamka.
{22202}{22250}J-já?
{22250}{22322}Onii-chan, ty jsi dìda.
{22346}{22394}Onee-chan, ty jsi babièka.
{22430}{22466}Tedy zbıvá...
{22729}{22777}Pošák Tagawavi.
{22873}{22921}Pokornì pøíjímám.
{22921}{22945}Ty pokornì pøíjímáš?
{22957}{23017}To pùjde.
{23017}{23053}Tak to zkusíme.
{23185}{23269}J-jdu do práce.
{23287}{23353}M-mìj se dobøe.
{23449}{23499}J-já nikdy pøedtím nehrála na dùm
{23499}{23544}Má to bıt takhle?
{23640}{23688}Je snídanì hotova drahá?
{23688}{23808}J-jasnì. Dej mi chvilièku.
{23904}{23952}Tady máš .
{24072}{24168}Ještì nikdy jsem si nehrála na dùm, ale myslím e mi to jde.
{24234}{24264}Blátovı knedlík.
{24264}{24312}To nás budeš krmit blátovımi knedlíky?
{24312}{24360}Ty jsi pøíšerná ena v domácnosti.
{24360}{24432}Nerespektuješ starší!
{24456}{24518}Nerespektuješ starší!
{24575}{24647}Omluvte mne, jsem z Tagawa doruèovací sluby.
{24671}{24755}O-okay, hned jsem tam.
{24791}{24839}Ty jsi strašnı poslíèek.
{24863}{24899}Omluvte mne, prosím.
{24911}{24959}Mám pro vás balík.
{25007}{25103}Pokud by jste mi to tady mohla podepsat.
{25151}{25175}Jistì...
{25343}{25415}Vidím, e nemáte prsten.
{25534}{25606}Vím, e vám to v manelství moc neklape.
{25606}{25678}T-tak poèkat.
{25966}{26046}Madam, vdy jsem vás pozoroval.
{26062}{26134}C-co to je? Nìjaká telenovela?
{26134}{26182}S-Slez ze mì!
{26182}{26278}Ona se dívá! Dívá se na nás dítì!
{26278}{26326}Není to víc vzrušující?
{26350}{26493}Omlouvám se, ale rád bych aby to zùstalo dìtskou hrou.
{26541}{26589}Chceš si dát pøestávku?
{26589}{26637}P-prohoïme si role!
{26637}{26661}Tentokrát mùe bıt maminkou-
{26661}{26733}Loli! Maniac!
{26757}{26853}Øeknìte mi, odkud je ta lolitka?
{26901}{26961}Y-Yukinokouji-san, chceš hrát s námi?
{26973}{27009}Samozøejmì!
{27021}{27069}RODOKMEN|Tím pádem,
{27069}{27147}Roromiya-san je babièka.
{27147}{27261}Sorinozuka-san a Yukinokouji-san jsou tatínek a maminka.
{27261}{27309}Proè jsem provdaná za nìj?
{27333}{27476}Tedy, Shirakiin-san je starší sestra a Hana a já jsme mladší sourozenci.
{27477}{27524}K-koneènì...
{27548}{27596}Miketsukami-san je pes.
{27596}{27620}Rozumím.
{27623}{27644}Ty rozumíš?!
{27668}{27740}Nech zapoène hra na dùm: Druhé kolo.
{27908}{27956}Fajn, jdu do práce.
{27980}{28028}Kde je mùj polibek na rozlouèenou?
{28124}{28196}Dobøe, to jsem mìl oèekávat.
{28196}{28316}Odejdi brzo, vra se pozdì a iv rodinu, víc nechci.
{28316}{28340}Jo, jo..
{28364}{28412}Tak já jdu pryè teda.
{28531}{28579}Oh boínku, babèa Karuta!
{28579}{28651}Drahá? Je ji snídanì?
{28675}{28747}Hladové holky! Maniac!
{28747}{28867}Koukám, e rodinná situace je napjatá.
{28867}{28891}Øádnì zapsáno.
{28891}{28987}Um, asi to moc øešíš.
{28999}{29059}Mí drazí sourozenci nebojte se.
{29059}{29155}Vaše sestøièka odmaturuje a najde si práci, aby jsme to tu opustily.
{29155}{29251}Nebojte se, ujistím se e budete moci chodit do školy.
{29275}{29347}Shirakiin-san to bere moc vánì.
{29395}{29490}A pùjdete, mohu s vámi?
{29514}{29538}Ten pes mluví!
{29538}{29706}Vskutku, jsem tvùj pes. Kdy opustíte tento dùm, mùj ivot bude prázdnı.
{29706}{29781}Poèkat, mùe pes mluvit?
{29781}{29874}Pokud ponecháme fantastické prvky, pøíbìh bude tìké kontrolovat.
{29874}{29970}Nue dobrá, v tom pøípadì nebudu mluvit.
{29994}{30066}Tahle hra na dùm je v celku zaloená na pravidlech.
{30090}{30138}Drahá, je ji snídanì hotova?
{30234}{30354}Promiò, ovšem vìtšina bytù nepøíjímá velké psy.
{30354}{30402}*kòuèí*
{30402}{30450}Nestarej se!
{30473}{30545}To jsem já! Mí lidští noèníci!
{30569}{30593}Moje sestra je tady.
{30593}{30665}Prosím neøíkej ''l-lidští noèníci''...
{30665}{30713}Bráško, on je narušitel! Zavolej 158!
{30713}{30809}Øekni hej! Øekni, øekni, øekni, øekni!
{30809}{30881}Pro tvou informaci, já nejsem narušitel.
{30881}{30977}Mimoto, nemusíš naøíkat nad problémy svıch rodièù.
{30977}{31001}A to proto...
{31097}{31169}Tvùj otec jsem já!
{31169}{31217}Jak politováníhodné.
{31217}{31289}Pojï se mnou mùj potomku!
{31289}{31385}Budeš si uívat tøi velké porce jídla a spánek kadı den se mnou.
{31385}{31480}Tøi jídla... TØI JÍÍÍDLA!
{31481}{31528}Babi! Nechoï!
{31576}{31624}Chlad!
{31624}{31672}Nenechám ti svou babièku!
{31678}{31696}Drahá!
{31720}{31768}Tak to koneènì zaèalo!
{31768}{31864}Maminka vs. skuteènı otec!
{31864}{31912}Ty jsi pøišel odnikud.
{31912}{31960}Kadopádnì, kde to jsme?
{31960}{32008}Zírají na sebe.
{32008}{32080}Koupil jsem ti hraèku.
{32080}{32152}Proè si nevezmeš tu hraèku?
{32152}{32248}Ou, u to jiskøí!
{32272}{32296}Pøipravit... BOJ!
{32499}{32607}A maminka posílá enormní kus ledu!
{32703}{32751}Vítìzí...mamka!
{32751}{32775}To je domácí násilí.
{32775}{32799}Vskutku.
{32823}{32847}Jsem doma.
{32871}{32919}Boe, já jsem utaha-
{33015}{33087}Co... tady dìlá...
{33135}{33231}Skuteènı otec zkolaboval a padl na zem.
{33231}{33303}Bude se matka nìkdy kát za své høíchy?
{33303}{33399}Kdo je skuteènım otcem dìtí?
{33698}{33758}Dnes jsem tvrdì cvièil!
{33758}{33818}Teï budu super vıtrník!
{33863}{33957}Watanuki-san...Drahı, je snídanì hotová?
