{633}{849}ŠEPOT SRDCE
{2906}{2959}- Dobrı veèer.|- Je horko, e?
{3057}{3079}U sem tady.
{3176}{3202}Dìkuju.
{3216}{3290}Na láhev mléka igelitku skuteènì nepotøebuješ.
{3294}{3329}Oni ho, do jedné zabalili.
{3333}{3406}Staèilo to odmítnout! Nalej mi taky.
{3415}{3455}Tati, dáš si trochu èaje?
{3466}{3535}Jistì, ano... Budu tam.
{3562}{3647}- U je volnı poèítaè?|- Ještì chvilku.
{3670}{3734}Mohla by sem si koupit elektronickı notebook.
{3808}{3867}Mohla si jít k svojí tetì.
{3884}{3938}S mojí sestøièkou?! V ádném pøípadì.
{3962}{4008}Hm, budu pracovat i zítra.
{4011}{4044}Mám ti pøipravit obìd?
{4047}{4087}Ne, najím se venku.
{4090}{4186}Máme teï hodnì práce.|Zavádíme systém èárovıch kódù.
{4188}{4261}Mìla sem radši kartotéky.
{4286}{4322}I já...
{4324}{4382}Tohle je špatnì...
{4384}{4416}Co? Kde?
{4442}{4502}POdívej tady!
{4529}{4565}Máš pravdu!
{4568}{4650}Pus mì k tomu. Musím to opravit,|nebo mùj šéf bude šílet.
{4664}{4736}<i>Amasawa Seiji</i>
{4753}{4785}Ten chlapec...
{4816}{4871}Mùeš si ještì èíst, ale nezùstávej dlouho vzhùru.
{4873}{4902}Dobøe... Dobrou noc.
{5124}{5193}Mìla sem pocit, e sem to jméno u nìkde vidìla...
{5263}{5287}Á tady je...
{5336}{5461}<i>Amasawa Seiji</i>
{5475}{5558}Pùjèoval si ty knihy pøede mnou.
{5744}{5868}Amasawa Seiji...jakı asi je.|jak vypadá?
{6054}{6124}<i>Amasawa Seiji</i>
{6306}{6378}Shizuku! Vstávej!
{6381}{6421}U musím jít!
{6471}{6556}Ty si spala obleèená?|Pøiprav rıi.
{6568}{6620}Pá!
{6697}{6767}Ale né! Mìla sem se sejít s Yuko!
{6829}{6863}Moje penìenka...
{6892}{6945}U zase si ji zapomnìla?
{6948}{6971}Jo.
{6991}{7036}To je zvláštní...
{7052}{7086}Zkus to u telefonu,...
{7108}{7131}Jasnì!
{7133}{7169}...kde si ji nechala?
{7172}{7232}Spìchám! Zamkni dveøe!
{7239}{7274}Sklerotièka!
{7478}{7538}Letí tak nízko!
{7653}{7692}Dnes mám šastnı den!
{8288}{8344}Ach, je tak horko!
{8539}{8599}Ahoj, jak se máš?
{9091}{9131}Pøihraj sem!
{9141}{9198}Ahoj, Shizuku!
{9210}{9286}Ahoj!|Uka jim to!
{9372}{9411}Sleèno Kosakao?
{9432}{9490}Tsukishima? Co tu dìláš?
{9492}{9543}Mùu vás poádat o laskavost?
{9552}{9608}Doufám, e o nic divného...
{9611}{9648}Pustíte mì do knihovny!
{9651}{9675}Co?
{9684}{9738}A to nemùeš poèkat,|dokud nezaène škola?
{9740}{9827}U sem pøeèetla všecky svoje knihy|a veøejná knihovna je zavøená.
{9859}{9927}Pøeètu i dvacet knih,|ne znova zaène škola.
{9930}{10030}Nezapomeò, e máš zkoušky.
{10042}{10071}Pospìš!
{10073}{10116}Tady je to!
{10120}{10150}Dones to sem.
{10200}{10273}Dej mi tvùj prùkaz a lístek od knihy.
{10288}{10323}Ano, paní.
{10355}{10435}Tudle knihu si ještì nikdo nepùjèoval!
{10453}{10538}Je vzácná. Nemají ji dokonce ani ve veøejné knihovnì.
{10664}{10731}<i>Darované</i>
{10744}{10803}„Amasawa”...sleèno!
{10814}{10876}Znáte toho Amasawu?
{10881}{10954}Koukni, co sem kvùli tobì udìlala!
{10958}{11036}Nìkdo nám ji daroval.|Asi ho neznám.
{11039}{11081}Zkus se zeptat nìkterého|ze starších uèitelù.
{11084}{11115}Shizuku!
{11124}{11246}Co tu Dìláš?|U od 11:00 tì èekám u pøední brány!
{11252}{11337}Jestli budu stát ještì chvilku na slunci,|budu celá pihatá!
{11339}{11360}Promiò!
{11363}{11450}Uklidni se, Harada.|Bereš ty pihy pøíliš vánì.
{11452}{11514}Sleèno, ale ony sou vánım problémem!
{11523}{11617}Dobøe, dobøe... A teï u jdìte.|To platí pro vás obì.
{11744}{11782}Pohyb! Pohyb!
{11834}{11947}Zkoušela sem to, ale moc se mi to nedaøilo.|Proè to jednoduše nezazpíváme Anglicky?
{11996}{12074}<i>Bíle oblaky plují nad kopcem...</i>
{12076}{12181}<i>...a cesta vine se polem.</i>
{12194}{12287}<i>Starı dùm s malımi okny,...</i>
{12289}{12388}<i>...kde èeká pes na paní.</i>
{12391}{12498}<i>Polní cesta vede do dály,...</i>
{12500}{12608}<i>...vede domù, nebo jinam?</i>
{12611}{12715}<i>Západní Virginia, hory Mamma...</i>
{12717}{12823}<i>Mùj starı domov, kde nejsem sem sama...</i>
{12828}{12874}- Není to špatnı.|- Nesouhlasím.
{12901}{12927}Je to pøíliš otøepané.
{12941}{12981}Co?
{13008}{13046}Napsala sem svoji verzi.
{13074}{13184}<i>Všude betón, nová cesta...</i>
{13190}{13305}<i>...zavede nás a do mìsta.</i>
{13309}{13367}<i>Západní Tokio...</i>
{13369}{13419}<i>Hory Tama...</i>
{13422}{13527}<i>V paneláku bıvám sama.</i>
{13559}{13602}Co to je?!
{13627}{13666}Tak co se dìje?
{13694}{13737}U ten text doufám nepotøebuješ?
{13739}{13814}Shizuku,... byla si u nìkdy zamilovaná?
{13828}{13851}Coe? Nechápu tì...
{13860}{13951}Uèení na zkoušky je lehèí,|kdy to nedìláš sama.
{13953}{13995}Mohli by jsme se vzájemnì podporovat.
{14015}{14074}Yuko! Ty si zamilovaná!
{14128}{14172}Dostala si milostnı dopis?!
{14179}{14198}Pssst!
{14200}{14250}Kdy? Kdo? Je pìknı?
{14253}{14332}Chodí do jiné tøídy. Není špatnı.
{14335}{14411}Tak se s ním sejdi! A jak se ti nebude líbit,|jednoduše øekni ne!
{14415}{14444}No, ale...
{14481}{14540}Take je nìkdo, koho máš rada!
{14592}{14680}To pøede mnou neschováš! Pøiznej se!
{14716}{14763}Je to Su...Su...
{14765}{14807}Tsukishima!
{14827}{14862}Podáš mi tašku?
{14884}{14903}Sugimura!
{14906}{14971}Tu modrou, sportovní tašku.
{14982}{15018}Pojïme, Tsukishima!
{15045}{15084}Pøihraj ji sem.
{15099}{15179}Zmlkni a vra se na lavièku!
{15181}{15269}Sem prvním v øadì|a dostanu se do regionálního kola!
{15272}{15298}Yuko?
{15584}{15663}Miluješ Sugimuru?
{15668}{15762}Co budeme teï dìlat?|Pøi tom, jak sem zareagovala, to moná u ví!
{15767}{15822}Neboj se. Na to je pøíliš hloupı.
{15849}{15914}A co ten chlapec, co ti to napsal?
{15995}{16061}Pøemıšlím i o nìm.
{16071}{16099}Aha.
{16110}{16197}Aspoò, e tì rodièe|neotravujou s uèením.
{16200}{16259}Mlèení není vdy a tak super.
{16268}{16306}Moná...
{16331}{16370}- Ale né|- Co?
{16372}{16426}Zapomnìla sem si tu knihu! Musím se vrátit.
{16428}{16451}Odvezu tì.
{16453}{16522}Ne, zmeškala by si douèování.
{16525}{16567}Zavolám ti.
{17508}{17550}Ta kniha...
{17564}{17622}Ach, je tvoje?
{17747}{17787}<i>Tady máš, Tsukishima Shizuku.</i>
{17803}{17835}Odkud znáš moje jméno?
{17870}{17907}Uhádnul sem ho!
{17939}{17991}Mùj prùkaz do knihovny...
{18000}{18091}<i>Na „Novou cestu” zapomeneme,|aspoò doufám.</i>
{18239}{18279}Ty si to èetl!
{18300}{18346}Blbec! Blbec! Blbec!
{18389}{18432}Blbec! Blbec! Blbec!
{18544}{18571}Blbec!
{18822}{18882}<i>Zapomeneme na Novou cestu.</i>
{18906}{18933}Jasnì!
{19870}{19899}U sem doma.
{19955}{20001}Shiho? U si se vrátila?
{20003}{20056}Sem znièená!
{20073}{20157}Odvezl mì jeden známı.
{20195}{20222}Kde je máma?
{20225}{20295}Na intenzivním letním semináøi.|Táta je v práci.
{20319}{20373}Mohla si tu trošku poklidit...
{20381}{20418}A co s veèeøí?
{20422}{20455}Jdu udìlat rıi.
{20458}{20530}Shizuku! Je tu ještì zbytek od rána!
{20544}{20593}Postarám se o to.
{20656}{20726}Máma má hodnì práce! Mìli by jsme jí pomoct!
{20864}{20961}Udìlej rıi a vynes prádlo.|Já si dám sprchu a udìlám veèeøi.
{21013}{21088}Teta øíkala, e a budeš|na støední, máš ji pøijít navštívit.
{21123}{21158}Uèíš se?
{21177}{21272}Nemysli si, e to zvládneš tak lehko,|jen proto, e tì rodièe nebuzerujou.
{21283}{21327}Já vím!
{21368}{21428}Chtìla, aby sem donesla domù|sójovou omáèku!
{21431}{21479}To je ta naše teta.
{21495}{21560}Stejné to bylo i minulı rok.
{21563}{21647}<i>Celou ohromnou mísu! Páni, to bylo tìké!</i>
{21650}{21701}Byli to dobrı dvì kila!
{22043}{22144}Shizuku! Vstávej a uprav si stùl!
{22157}{22199}Budeme prát povleèení.
{22208}{22249}A vyvìtrám peøiny.
{22283}{22311}Kde je máma?
{22314}{22343}U odešla.
{22456}{22523}Udìlej to a dones tátovi|jeho obìd.
{22526}{22550}Já?!
{22555}{22635}A proè né? Jdeš pøece do knihovny.
{22670}{22718}To mám jít radši já?
{22726}{22826}A ty zatím vyèistíš záchod, koupelnu |a balkón a pùjdeš do krámu?
{22851}{22943}A nezapomeò otoèit peøiny a dokonèit veèeøi.
{23023}{23068}Já pùjdu!
{23216}{23255}Shizuku!
{23272}{23320}Mohla by si to poslat?
{23323}{23352}Co?
{23356}{23407}P-O-S-L-A-T!
{23545}{23587}A neèti to!
{23603}{23647}Obálka je zalepená.
{23659}{23684}Tvému pøíteli?
{23687}{23714}Idiote!
{25077}{25118}Ahoj kocourku... si tu sám?
{25239}{25262}Kam jedeš?
{25352}{25388}Je tam nìco zajímavého?
{25439}{25490}Hej! Odpovìz mi!
{25797}{25844}Tak já vystupuju. A co ty?
{25952}{25987}Uvidíme se pozdìji.
{26306}{26342}Hej! Kocourku!
{26828}{26866}I knihovna je tím smìrem!
{27442}{27538}A vypadalo to jako|zaèátek zajímavého pøíbìhu...
{28403}{28432}Támhle je!
{29030}{29108}<i>VSTUP ZAKÁZÁN</i>
{29735}{29816}Co to je za kopec!|Jak daleko ještì asi pùjde?
{30275}{30308}Kocourku?
{30342}{30375}Kocourku?
{30481}{30539}Bydlíš tu nìkde?
{31308}{31394}Hej kocourku! Kam bìíš?|Bydlíš tu nìkde?
{31871}{31965}O tomhle místì sem|doteï ani nevìdìla...
{32427}{32510}To se nedìlá!|Proè zlobíš toho pejska?!
{32803}{32882}Moná, e i mì jen zlobíš.
{34139}{34222}Neèekala by sem tu takovı obchod...
{34915}{34961}To je pìkné!
{35155}{35202}Ty si ten kocourek?
{35499}{35525}Ach, vítej...
{35527}{35552}Um...
{35555}{35648}Neboj se. Prohlédni si co chceš.
{35655}{35706}I Baron se nudí.
{35736}{35803}Tahle figurka je Baron?
{35806}{35922}Ano. Baron Humbert von Jechingen.|Vlastním jménem...
{36133}{36184}Ach, promiò.
{36199}{36241}Dìkuji. U sem v poøádku.
{36243}{36281}To jsou krásné hodiny.
{36283}{36371}Byli v nìjakém hradì. U zrezivìli...
{36374}{36400}Podívej...
{36479}{36562}To je pøekrásné. Co je to?
{36636}{36694}Poèkej chvilku a uvidíš.
{37659}{37711}To jsou bezvadní trpaslíci!
{37714}{37844}Take ty si mladá dáma,|která má ráda trpaslíky?
{37894}{37987}POdívej se na ciferník...uvidíš co dìlá.
{38425}{38446}Víla!
{38448}{38515}Svìtlo se odráí na skle.|Pojï radši sem.
{38642}{38671}Princezna?
{38675}{38700}Pøesnì tak.
{38942}{38990}Sou zamilovaní?
{39003}{39108}Mhm, ale ijí kadı v jiném svìtì.|On je králem trpaslíku.
{39124}{39243}Jen kdy hodiny odbijí dvanáct,|pøemìní se zpìt v princeznu.
{39248}{39337}Ale on se objevuje kadou hodinu...
{39339}{39379}...a èeká na ni.
{39399}{39527}Umìlec, kterı to vytvoøil|se musel zklamat v lásce.
{39561}{39633}Proto oba vypadají tak smutnì...
{39721}{39763}Ty hodiny se pøedbíhají?
{39766}{39828}Asi tak o pìt minut, myslím...
{39831}{39860}Ale né!
{39888}{39947}Mìla sem bıt u v knihovnì!
{39964}{40010}Mùu se sem nìkdy vrátit?
{40027}{40109}Ovšem...ale jestli jdeš do knihovny,|mìla by si zahnout do leva!
{40395}{40438}Sem právì nad ní!
{40571}{40646}To je ale objev!|Místo, kde zaèínají pøíbìhy!
{40699}{40733}Fantastické!
{40771}{40803}Tsukishima!
{40807}{40846}Tsukishima Shizuku!
{40919}{40949}Není tohle tvoje?
{41087}{41132}Ty si ale zapomìtlivá.
{41137}{41179}Díky...ale jak...?
{41182}{41225}Hádej!
{41283}{41352}Kocourku! To je tvùj kocourek?
{41360}{41412}Ty si teda dáváš poøádnı obìd!
{41466}{41490}Tak to není!
{41495}{41578}<i> Všude beton, nová cesta...</i>
{41611}{41664}To není moje!
{41724}{41753}Aha, tak tady si...
{41836}{41890}Co je to s tebou?
{41902}{41947}To se tìko vysvìtluje.
{41983}{42062}Cítím se, jako kdyby sem objevila|jeskyni plnou skrytıch pokladù.
{42064}{42130}A potom nìkdo øekl nìco,|co mì málem pohøbilo zaiva.
{42135}{42181}To zní komplikovanì.
{42239}{42275}Chceš další knihy?
{42277}{42336}Aspoò tak sedm.
{42339}{42398}Ty se nikdy nezmìníš... A co s obìdem?
{42401}{42425}Nìco si koupím.
{42427}{42488}Koupíš? Tak dìkuju.
{43016}{43057}16. èervna...
{43075}{43155}Jéé! Amasawa èetl i tuhle knihu!
{43183}{43232}Co má rád?
{43311}{43357}Ne! On není  ty!
{44641}{44699}Shizuku! Pospìš!
{44738}{44766}Nestíhám!
{44798}{44824}Podej mi deštník.
{44909}{44969}Tenhle semestr stále prší.
{44992}{45074}Aspoò e tì studium baví.
{45080}{45104}Ano.
{45110}{45150}Usilovnì se uè!
{45152}{45187}Neboj se!
{45376}{45398}Shizuku!
{45400}{45423}Ahoj!
{45425}{45463}Pospìš si! Nebo zmeškáme!
{45500}{45550}Nenávidím všecky ty testy!
{45552}{45599}Kadı den nìjakı!
{45727}{45757}Odpovìdìla si mu?
{45759}{45784}Ne.
{45787}{45821}Øíkal nìco?
{45843}{45881}Odmítnu ho.
{45893}{45967}Co? Moná to tak bude lepší.
{45970}{46006}Sugimura!
{46036}{46071}Radši pohnìte!
{46087}{46132}Dobøe!
{46356}{46414}Èas vypršel. Seberte papíry.
{46563}{46605}Uvidíme se po obìdì.
{46699}{46747}Pojïme pozdravit sleènu Kosaku.
{46750}{46793}Dobøe, ale nejdøív se zastavíme ve sborovnì.
{46795}{46819}Jasnì.
{46828}{46877}- Tsukishima!|- Co je?
{46879}{46931}Všecko sem to otipoval!
{46934}{46962}Není to super?
{46970}{47034}Všecko, co sem se uèil tam bylo!
{47044}{47101}Take nejsi dobrı jen v baseballe...
{47103}{47202}Yuko je taky dobrá v hádaní.|Proè nestuduješ s ní?
{47215}{47236}S Haradou?
{47239}{47286}- Hej, Sugimura!|- Co je?
{47317}{47349}Pojï sem!
{47483}{47529}Pøestaò nás dávat dohromady!
{47531}{47556}Bylo to hroznì nápadnı?
{47559}{47607}To by sem nikdy neøekla!
{47610}{47634}Promiò!
{47673}{47707}Promiòte...
{47787}{47866}Dárce knih do knihovny?|Hmm, toho neznám...
{47873}{47964}Promiòte, e vás vyrušuji pøi obìdì.|Byla tam tato poznámka.
{47989}{48031}Ach...
{48095}{48152}To je Dr. Amasawa.
{48155}{48203}Èetl sem to. Je to dobrá kniha!
{48213}{48243}Ano, velmi.
{48245}{48311}Co je to za èlovìka?
{48323}{48417}Pøed pár lety byl vedoucím PTA.
{48419}{48511}PTA? A jaké má køestní jméno?
{48513}{48554}Jeho jméno?
{48556}{48663}Pane Kimuro, pamatujete se na|jméno Dr. Amasawy?
{48666}{48743}Dr. Amasawa? To byl „Koichi”.
{48758}{48791}Amasawa Koichi...
{48803}{48927}Jeho nejmladší syn, je v tvém vìku|Tsukishima. Neznáš ho?
{48935}{48981}Opravdu?!
{48991}{49029}Dìkuji vám pìknì!
{49062}{49094}Nashledanou!
{49123}{49150}Promiòte!
{49203}{49263}Shizuku, kam jdeš?
{49311}{49349}To je ale pøekvapení!
{49351}{49389}Povídej mi o tom!
{49409}{49467}Co je to s tebou?!
{49490}{49519}Promiò!
{49747}{49797}Hej, kam to jdeš?
{50199}{50251}On mì ignoroval! Ten má ale nervy!
{50254}{50323}Kdo je to? Kam jdeš?
{50325}{50390}Je to blbec! Ale vyhıbat se mu nebudu!
{50458}{50547}Nesla sem jí obìd celou cestu!
{50583}{50638}Tsukishima má pøítele?!
{50640}{50746}Myslím si, e na Shizuku koneènì|pøišlo jaro!
{50748}{50790}To není pravda!
{50793}{50868}Potkala si prince ze svıch kníek?
{50871}{50896}Je pìknı?
{50899}{50960}Jen sem chtìla zjistit, co má rád!
{50963}{51060}No tak, Yuko, slyšela si jeho jméno.|Øekni nám ho!
{51079}{51102}Yuko!
{51111}{51154}Stalo se to moc rychle.
{51156}{51251}„Ma” , nìco jako, „Masaki” , moná...
{51253}{51276}Hmm?
{51291}{51313}Hmm...
{51315}{51432}To ti je podobné Tsukishima, utéct od nìèeho|bez toho, aby si slyšela konec.
{51436}{51503}Chtìla by si to vìdìt, ale...
{51523}{51600}Ranìné srdce krvácí!
{51603}{51678}To je hroznì romantické!
{51700}{51822}Nemìli byste zlobit èlovìka,|kterı vám právì dopsal text písnì.
{51825}{51877}- U si ho dokonèila?!|- Uka nám ho!
{51926}{52026}Ó Shizuku! Ó ty velkı poeto!|Uka nám svùj text!
{52056}{52087}Dobøe.
{52115}{52146}Vlastnì, nejsem si tím jistá...
{52189}{52315}Nevím toho moc o starıch rodnıch mìstech|a tak sem napsala to, co sem cítila.
{52319}{52370}To je fantastické!
{52377}{52499}„Polní cesta”
{52506}{52624}„...vedeš tam,”
{52630}{52748}„kde v dálavách já domov mám...”
{52751}{52866}„...kde u nikdo není sám.”
{52879}{52932}Shizuku, je skvìlá. Líbí se mi to.
{52949}{52980}Není to pøíliš tìké na zpívání?
{52984}{53013}Zvládneme to.
{53015}{53118}Mùeme to dát mladším ákùm|a zazpívat to na dìkovacím veèírku našim uèitelùm!
{53120}{53151}Co? Uèitelùm na dìkovacím veèírku?!
{53154}{53174}Zpomal!
{53176}{53211}Miluju tuhle èást.
{53214}{53316}<i>Mìla sem sen,|jednoho rána...</i>
{53321}{53415}<i>...e iju beze strachu,|ale sama.</i>
{53418}{53472}Sleèny, zvoní.
{53655}{53709}Vyjasnilo se!
{53719}{53741}Shizuku!
{53755}{53844}Pøijï do uèebny zboru!|Ukáeme jim tvùj text!
{53847}{53903}Nemùu, já jdu do knihovny.
{53906}{53957}Zítra píšu další test...
{53968}{53999}Budu se tam uèit.
{54002}{54030}Knihomole!
{54046}{54070}Ahoj.
{54955}{54978}Harada...
{55052}{55110}Mùu si s tebou chvilku promluvit?
{55363}{55402}Je zavøeno.
{55435}{55493}Zalil nìkdo kvìtiny?
{55775}{55870}Baron zmizel... Moná si ho nìkdo koupil.
{56016}{56095}<i>Obchodník.</i> |Majitel Nishi Shiro.
{56108}{56205}’Nishi Shiro’... moná se i|ten blbec jmenuje „Nishi”.
{56530}{56599}Shizuku! Shizuku!
{56724}{56763}Volá ti Yuko!
{56784}{56829}Jednou ohluchneš, Shizuku.
{56847}{56875}Yuko?
{56889}{56948}Coe? neslyším tì.
{56972}{57031}Budu tam za chvíli.
{57034}{57083}Pá.
{57102}{57152}- Kam jdeš?|- Jen pøed dùm.
{57320}{57358}Co se stalo?
{57380}{57412}Shizuku!
{57415}{57475}Co se dìje?
{57482}{57532}Co mám dìlat?!
{57535}{57672}Kluk, kterı napsal ten dopis,|poslal Sugimuru, aby se mì zeptal na odpovìï!
{57714}{57775}Ach-och...
{57807}{57864}Proè ze všech lidí právì ty?!
{57915}{57932}Hej!
{58019}{58074}Sugimura je takovı pitomec!
{58084}{58182}Ale neví, co k nìmu cítíš...
{58231}{58400}Omluvím se mu. Ale takhle|nemùu jít do školy.
{58405}{58436}A zmeškáš testy?
{58448}{58471}Jo.
{58491}{58520}Och.
{58989}{59014}Idiot!
{59077}{59108}Coe?
{59158}{59190}Byl lehkı.
{59192}{59239}Zase do knihovny, Shizuku?
{59242}{59267}Jdu k Yuko.
{59270}{59319}Tak ji pozdravuj.
{59523}{59569}Tsukishima!
{59599}{59629}Poèkej!
{59793}{59835}Co je s Haradou...
{60007}{60135}...potom zaèala plakat.|Øekl sem nìco špatnì?
{60177}{60287}Nezeptala se tì Yuko,|proè si to udìlal?
{60299}{60371}Jo. Kámoš z baseballového teamu|mì poádal...
{60383}{60418}Ne!
{60421}{60496}Nechtìla od tebe slyšet nic takového!
{60499}{60533}Nerozumíš?
{60543}{60580}Ne, nerozumím!
{60591}{60615}Øekni mi to!
{60633}{60745}Víš, e si skuteènì poøádnì hloupı?|Líbíš se jí ty!
{60758}{60841}Coe?! V ádném pøípadì!|To je špatnı!
{60854}{60973}Špatnı? A jak myslíš, e se asi cítí Yuko?|Zùstala dnes nemocná doma!
{60987}{61069}Ale... Já miluju tebe!
{61078}{61104}Coe?!
{61130}{61187}Nedìlej si ze mì srandu! Ne teï!
{61189}{61218}Nedìlám si srandu!
{61221}{61267}Miluju tì u dlouho!
{61296}{61363}Ne mì! Nemùeš!
{61373}{61443}Ty mì nemáš ráda? Nebo máš pøítele?
{61458}{61510}Nemám pøítele...
{61536}{61564}Ale...
{61577}{61594}Mrzí mì to!
{61599}{61615}Poèkej!
{61631}{61675}Øekni mi pravdu!
{61688}{61831}Vdy jsme byli pøátelé...|Mám tì ráda, ale ne tak...
{61906}{61960}Mrzí mì to. Nedokáu to vyjádøit.
{62114}{62152}Jen pøátelé?
{62220}{62255}Navdy?
{62384}{62415}Dobøe...
{63555}{63619}Jedinı blbec sem tu já!
{63879}{63947}Tohle u mì nechal pošák.
{63950}{64007}Dìkuji vám pìknì!
{64355}{64404}Nemusíte to dìlat!
{64407}{64467}Sami to nemùeme sníst.
{64486}{64518}Ach, u si doma...
{64546}{64566}Shizuku?
{66511}{66550}Ahoj.
{66600}{66636}Ty si zavøenı tady venku?
{66726}{66809}Nejsi hladovı?
{66899}{66977}Nejsi moc milı. Asi jako já.
{67046}{67169}Proè jsme se tak zmìnily?|Bıvala sem milejší...
{67184}{67279}U ani knihy mì nebaví,|tak jako kdysi.
{67283}{67408}Stále slyším nìkoho ve mì,|jak øíká: „Ale vìci nejsou a tak lehké!”.
{67415}{67455}Nejsem moc milá.
{68063}{68099}Ahoj! Tsukishima!
{68149}{68197}Mìsíèek se s tebou mazlí?
{68206}{68254}Mìsíèku, nepùjdeš dovnitø?
{68257}{68298}To je jeho jméno?
{68300}{68350}Pøipomíná mi mìsíc v úplòku.
{68358}{68415}A proto sem ho tak pojmenoval.
{68518}{68567}To je tvùj kocour?
{68570}{68613}Nezùstává na jednom místì.
{68615}{68694}Slyšel sem, e mu jinde|øíkají Lopta.
{68701}{68751}A sem si jistı, e má i jiné jména...
{68756}{68820}Take se rád toulá...
{68853}{68915}Vìdìl si, e pøijídí vlakem!
{68939}{68957}Vlakem?
{68969}{69077}Ano, jezdí vlakem! Takhle sem jsem pøišla|i já. Sledovala sem ho.
{69090}{69197}Dovedl mì do malého útulného|obchùdku s pøekrásnımi pøíbìhy.
{69218}{69245}Urazila sem ho.
{69269}{69377}Øekla sem, e není moc milı,|stejnì jako já.
{69394}{69467}Ty nejsi v ádném pøípadì jako Mìsíèek!
{69481}{69557}Urèitì je skøíenı s nìjakım démonem...
{69748}{69777}- Um...|- Mohl by sem...
{69835}{69933}Je tvùj dìda v poøádku?|Obchod byl zavøenı a tak sem si myslela...
{69935}{70032}Je v poøádku. Toto je zvláštní obchod...|Má otevøeno jen obèas.
{70035}{70079}Sem ráda, e je v poøádku.
{70082}{70175}Nevidím pøes okno Barona.|Prodal ho?
{70178}{70256}Ty myslíš tu figurku? Chceš ji vidìt?|Pojï se mnou.
{70513}{70538}Zavøi dveøe.
{71026}{71080}Je to jako by jsme byli v oblacích!
{71288}{71313}Máš strach z vıšek?
{71315}{71385}Ne, miluju vysoká místa.|Tady je to úplnì super.
{71548}{71603}V tomto období je vıhled nejlepší.
{71606}{71628}Tady je to.
{72191}{72218}Perfektní naèasování.
{72239}{72271}Posaï se sem.
{72278}{72305}Hodiny sou pryè!
{72319}{72366}Ty, velké, které tu byli?
{72388}{72452}Dnes je dìdùv dodací den.
{72458}{72488}Prodal je?
{72506}{72551}Byli tu jen na opravu.
{72554}{72626}Ráda by sem je znovu vidìla.
{72628}{72720}Oprava trvala tøi roky. Dokonèil|je právì v ten den, kdy si zapomnìla obìd.
{72723}{72752}Ten obìd!
{72763}{72827}Vìdìl sem, e nebyl tvùj.
{72830}{72874}Podívej se do jeho oèí.
{72942}{72998}Rychle, ne zapadne slunce.
{73295}{73370}<i>Engelzimmer... „Andìlùv pokoj”.</i>
{73374}{73455}Umìlec ho omylem poškrábal,|kdy mu zašíval šaty.
{73458}{73498}To je krása.
{73503}{73577}Barona nikdy neprodáme.|Je to dìdùv poklad.
{73595}{73616}Poklad?
{73648}{73741}Moc pro nìho znamená.|Ale nikdy neøekne, co pøesnì.
{73750}{73824}Prohlíej si ho, jak dlouho budeš chtít.|Budu dole.
{73912}{73970}Jestli chceš, mùeš si rozsvítit.
{74285}{74410}Je to zvláštní. Mám pocit,|jako by sem tì znala celé roky.
{74413}{74470}Nìkdy sem tì opravdu touila vidìt...
{74575}{74646}Vypadáš nìjak smutnì...
{76296}{76336}Staèilo?
{76339}{76386}Ano. Dìkuju.
{76390}{76455}Vyrábíš housle?
{76465}{76500}Ano.
{76540}{76571}Ukáeš mi to?
{76686}{76715}Tohle patøí sem.
{76756}{76818}To si udìlal sám? Vlastnoruènì?
{76828}{76859}Samozøejmì!
{76862}{76900}Úasné!
{76905}{76983}Jejich tvar se za 300 let nezmìnil.
{76987}{77065}Jejich zvuk závisí na zruènosti|jejich vırobcù.
{77102}{77143}Všechno to si vyrobil ty?
{77148}{77241}Ne, to ne! Máme tady tøídu vırobcù houslí.
{77257}{77303}Ale jedny z nich jsou tvoje?
{77308}{77330}Ano.
{77344}{77380}Které?
{77384}{77410}Tyto.
{77418}{77454}Tyto.
{77462}{77581}Fíha! Ty si udìlal ty?|Sou skvìlé!
{77595}{77682}Jak to mùeš øíct s tak vánou tváøí?
{77701}{77766}Nechápu... Øekla sem jen to,|co si myslím.
{77776}{77835}To by dokázal udìlat kde kdo.
{77872}{77903}Musím ještì ujít dlouhou cestu.
{78079}{78132}Umíš hrát?
{78139}{78160}Jen trošku.
{78163}{78222}Zahraješ mi nìco? Prosím!
{78225}{78251}Ale...
{78254}{78314}Prosím, prosím, prosím!
{78326}{78383}Ale jen kdy budeš zpívat.
{78415}{78471}Já? Zpívám hroznì falešnì!
{78474}{78507}Super!
{78905}{78963}Zpívej. Tady tu píseò urèitì znáš.
{79539}{79662}<i>Mìla sem sen|jednoho rána,...</i>
{79680}{79798}<i>...e iju bez strachu,|ale stále sama.</i>
{79811}{79927}<i>Potlaèila sem svùj smutek|hluboko do sebe...</i>
{79930}{80041}<i>...a teï mi tøeba, u jen modré z nebe.</i>
{80048}{80179}<i>Polní cesta vede k dálavám...</i>
{80181}{80310}<i>... a já tu sama zùstávám.</i>
{80316}{80444}<i>A to skonèí, zítra snad,...</i>
{80448}{80571}<i>...zaènu myslet na návrat.</i>
{80606}{80728}<i>I kdy smutek v srdci døíme,...</i>
{80731}{80848}<i>...neuvidíš slzy temné.</i>
{80859}{80993}<i>Musím rychle utéct pryè,...</i>
{80997}{81106}<i>...ne vzpomínkám dám odpovìï.</i>
{81114}{81235}<i>Polní cesta zavede mì tam,...</i>
{81242}{81375}<i>...kde moje srdce a domov mám.</i>
{81381}{81511}<i>Nechci a nesmím se vrátit tam,... </i>
{81515}{81637}<i>...kde moje srdce pøebıvá.</i>
{81648}{81769}<i>A kdy zítra na tu cestu vykroèím,...</i>
{81783}{81908}<i>...doufám, e se vùbec nezmìním.</i>
{81916}{82045}<i>Chci jít domù, ale nevím kam...</i>
{82051}{82112}<i>...a tak polní cestì...</i>
{82199}{82263}<i>...opìt sbohem dám!</i>
{83035}{83073}To byla zábava!
{83137}{83223}Sem Shizuku Tsukishima.|U jsme se potkaly.
{83272}{83367}Doufal sem, e se vrátíš.
{83379}{83434}To jsou moji pøátelé|z hudebního krouku.
{83452}{83578}Pìknı zpìv. Take ty si mìla|to štìstí vidìt funkèní hodiny...
{83590}{83657}Seiji má jen pár pìknıch pøátel.
{83674}{83770}„Seiji”? Ty jsi Amasawa Seiji?
{83783}{83854}Ano... Nepøedstavil sem se?
{83867}{83945}Ne! Venku bylo napsané Nishi.
{83971}{84041}To je dìdeèkovo pøijmení.|Já sem Amasawa.
{84053}{84167}To snad ne! Pøedtím si mì pohøbil|za iva a teï na mì spadla obloha!
{84186}{84269}A jakı je rozdíl v tom, e víš jak se jmenju?
{84271}{84347}Velkı! Ty si mì znal|celım mojim jménem!
{84356}{84407}Ale ty si se na moje neptala!
{84410}{84455}Nemìla sem pøíleitost!
{84470}{84542}Moje pøedstava o Seijim Amasawi...
{84551}{84572}Coe?
{84575}{84622}...byla o nìkom tichém a jemném.
{84624}{84671}Èteš moc knih.
{84678}{84728}Asi jako ty!
{85116}{85187}Byla to zábava. Jsou to milí Lidé.
{85200}{85260}Pøíjï zase nìkdy. Líbilo se jim to.
{85263}{85332}Jen si nìco poslechni. Zpívat moc neumím...
{85353}{85443}Ale ty si dobrı houslista.|Je to to, co chceš v budoucnosti dìlat?
{85460}{85512}Je spousta takovıch, jako já.
{85522}{85587}To co by sem chtìl dìlat, je vyrábìt housle.
{85598}{85658}To ano... Si v tom dobrı.
{85677}{85761}Vıborná škola je v Cremonì,|v Itálii.
{85774}{85827}Hroznì rád bych se tam dostal.
{85846}{85887}Ty nechceš na vysokou?
{85903}{86049}Moji rodièe sou proti.|Jen v dìdovi mám spojence.
{86344}{86410}Je fantastické vìdìt,|co chceš dìlat.
{86424}{86532}Já vùbec nevím,|èím budu. iju ze dne na den.
{86550}{86662}A já nevím, jestli tam nìkdy pojedu,|protoe stále musím bojovat s rodièi.
{86684}{86802}I kdy tam budu moct jít,|tak nevím, jestli mám dost talentu...
{86878}{86912}Doprovodím tì domù.
{86915}{86984}Ne, to není tøeba. U jsme skoro tam.|Mìj se pìknì.
{87015}{87045}Tsukishima...
{87060}{87098}Ano?
{87101}{87147}Si talentovaná skladatelka.
{87163}{87265}To, co si tam zpívala, nebylo špatné,|ale moc se mi líbila i „Tvrdá cesta”.
{87275}{87338}Øíkal si, e na ni chceš zapomenout!
{87345}{87382}To sem øíkal?
{87385}{87408}Ano!
{87423}{87451}Opravdu?
{87500}{87562}Díky za všechno. Dobrou noc.
{88028}{88119}Nezapomeò pøed spaním|zhasnout svìtlo.
{88292}{88354}Ségra, kdy si se rozhodla|o své budoucnosti?
{88356}{88379}Co?
{88390}{88419}O své budoucnosti!
{88435}{88489}Nechystáš se na Suginomiyu ?
{88492}{88537}To sem nemyslela!
{88551}{88611}Sem na univerzitì, aby sem to zjistila.
{88656}{88686}Dobrou noc.
{88695}{88721}Dobrou noc.
{89071}{89150}Mámì dnes zrušili kurzy|a tak mì nevzbudila!
{89387}{89406}Dobré ráno!
{89414}{89444}Tobì taky!
{89463}{89502}Pobì rychleji!
{89510}{89546}Utíkej napøed!
{89819}{89893}<i>První hodina: Samostudium</i>
{89983}{90006}Super!
{90024}{90062}Shizuku!
{90071}{90106}Vypadáš hroznì!
{90109}{90174}Sem ráda, e si se u s tím vyrovnala.
{90178}{90244}Slyšela sem, e si|mìla minulou noc rande.
{90247}{90295}KDo ti to øekl?!
{90298}{90364}Malı ptáèek,...kterı mi zazpíval,|e ste vypadaly jako pár.
{90367}{90397}Nejsme pár!
{90598}{90694}Harada... Nemìl sem dìlat prostøedníka|kamarádovi. Promiò.
{90707}{90766}I mì to mrzí.
{90778}{90804}To je v poøádku.
{90919}{91004}Vidìli ste Sasukeho minulou noc v televizi?|Byl fantastickı!
{91184}{91278}Ten vzorec bude v testu,|tak si ho zapamatujte!
{91328}{91350}To je všechno!
{91848}{91898}Je tu Tsukishima?
{91924}{91957}Amasawa? Co tu dìláš?
{91977}{92016}Chodí do této tøídy Tsukishima?
{92034}{92099}Tsukishima? Jo, je tu.
{92110}{92166}Tsukishima! Máš návštìvu!
{92168}{92189}Nìjakej kluk!
{92308}{92344}Tam je.
{92404}{92431}Seiji?
{92449}{92494}Mùeme si promluvit?
{92515}{92546}Ano!
{92549}{92626}Tsukishima má pøítele!
{92703}{92772}Ne, nemám!
{92937}{92975}Co se dìje?
{92978}{93036}Jedu do Itálie.
{93039}{93060}Coe?
{93078}{93107}Pojï se mnou.
{93210}{93263}- Kam jdeme?|- Na støechu!
{93447}{93483}Fíha!
{93502}{93604}Mezi takovou hromadou lidí|se nedá v klidu mluvit.
{93612}{93691}Promiò, ale chtìl sem,|aby si se to dozvìdìla, jako první.
{93759}{93835}Je mi jedno, co si myslí.
{93851}{93937}Mùj otec to koneènì vzdal.|Pod jednou podmínkou.
{93953}{93985}Jakou?
{94003}{94112}Budu pracovat jako uèeò|dva mìsíce v obchodì dìdova známého.
{94134}{94159}Uèeò?
{94163}{94270}Èlovìk, kterı ho vede je velmi pøísnı.|Zjistí, jestli mám talent, a nebo ne. 
{94284}{94369}A taky, jestli mám dost trpìlivosti,|vydret to.
{94379}{94447}Jestli ne, pùjdu na vysokou.
{94458}{94537}Štve mì, e si nechali zadní dvíøka,...
{94550}{94585}...ale je to dobrá šance.
{94588}{94624}Kdy pùjdeš?
{94639}{94741}A dostanu svùj pas.|Otec to byl dnes dohodnout ve škole.
{94751}{94788}Take, brzo...
{94827}{94879}Super! Tvùj sen se uskuteèní.
{94882}{94954}Ano, budu se snait,|jak l´jen budu umìt.
{95015}{95042}- Hmm...|- Dobøe...
{95112}{95146}Pøestalo pršet.
{95152}{95173}Hej...
{95195}{95238}Podívej se tam.
{95378}{95418}Moná uvidíme i duhu...
{95691}{95801}Jak vypadá Cremona? Doufám, e pìknì.
{95814}{95940}Je to staré mìsto s hromadou|vırobcù houslí.
{95947}{96039}To je bezva. U si vykroèil|svou cestou.
{96054}{96095}Cítim se jako idiot.
{96103}{96186}Doufala sem, e budeme chodit|na stejnou vysokou...
{96214}{96274}Co za pitomost sem si to vymyslela...
{96701}{96811}Kdysi dávno sem vidìl tvoje jméno|na kartotékovém lístku v knihovnì.
{96833}{96906}Vdy jsme se v knihovnì minuly.
{96937}{97003}Dokonce i tehdy,|kdy sem sedìl vedle tebe.
{97037}{97167}Pøeèetl sem hromadu knih, |aby bylo moje jméno pøed tvım.
{97207}{97234}Já...
{97269}{97354}Budu si zpívat tvoji písnièku|v Itálii.
{97473}{97504}I já.
{97557}{97594}Netlaè se!
{97748}{97784}Hej!
{97840}{97895}Bacha, Tsukishima zuøí!
{97944}{97968}Zachraò se kdo mùeš!
{98787}{98816}- Prosím.|- Dìkuji.
{98819}{98842}Omluvte mì.
{98845}{98907}U si dojedla?
{98927}{98970}Mám sraz s Yuko.
{99038}{99096}A pùjdeš okolo obchodu, kup nìjaké mléko.
{99144}{99201}Vdy si ho pøece vypila, Shizuku!
{99220}{99284}V posledních dnech jen lenoší.
{99767}{99835}- Zmeškala si kvùli mì douèování?|- To je v poøádku.
{99839}{99883}Sem v jednom kole
{99904}{99943}Ahoj, Shizuku.
{99946}{99973}Dobrı veèer.
{100043}{100074}Ahoj.
{100079}{100112}Dobrı veèer.
{100154}{100211}Udìlám vám èaj.
{100243}{100322}Táta a já se spolu nebavíme.
{100477}{100535}Kluci mají takové štìstí!
{100572}{100707}Vrátí se za dva mìsíce, ale kdy to zvládne|znovu odjede na deset rokù!
{100710}{100763}To je jako navdy!
{100786}{100875}Ale mezi vámi nìco je!|Super!
{100879}{101000}Je o tolik lepší, ne já.|Dva lidé, kteøí ètou stejné knihy...
{101003}{101091}...a na to, e jeden u ví, co chce,|a ten druhı ne.
{101107}{101140}Jo...
{101156}{101242}Kinuyo s ním rok chodila do tøídy.
{101245}{101354}Øíkala, e vypadal fantasticky, uèení|mu šlo, ale byl dost uzavøenı.
{101366}{101458}To mi neøíkej!
{101462}{101498}Cítim se jen hùø!
{101508}{101591}A proè? Má tì pøece rád.|Øekl ti to!
{101594}{101643}Nejsem si tím tak jistá...
{101719}{101859}Tomu nevìøím! Bıt tebou, psala by|sem si s ním a povzbuzovala ho.
{101887}{101966}Nemùeš pøece øíkat „do toho”|nìkomu, kdo je ambicióznìjší ne ty.
{101979}{102018}Moná...
{102050}{102134}Ale nerozumím, co chceš.
{102140}{102215}Nedokáeš milovat nìkoho bez toho,|aby si si naplánovala budoucnost?
{102274}{102323}Si talentovaná.
{102326}{102412}Všichni milují tvùj pøeklad „Polní cesty.”
{102429}{102506}A ty se umíš vyjádøit...|na rozdíl ode mì.
{102563}{102619}„Je jich hodnì minimálnì|tak dobrıch, jako sem já.”
{102631}{102678}To øíkal.
{102680}{102775}Chce zjistit, jestli má talent.|Tak to udìlám i já!
{102838}{102898}Napíšu pøíbìh!
{102904}{102989}Je jeden, kterı u chci hroznì dlouho napsat.|Kdy to dokáe on, tak já taky.
{103019}{103054}Ale je pøece zkouškové období...
{103056}{103154}To je jedno. Díky Yuko.|Dodala si mi odvahu.
{103165}{103199}- U jdeš?|- Jo.
{103294}{103323}Dobrou noc.
{103337}{103381}Pozdravuj maminku.
{103472}{103507}I ty to zvládneš.
{103546}{103639}Sugimura na to taky pøíjde.
{103659}{103682}Pá.
{103731}{103826}Je to tak lehké!|Jen se musím snait!
{103923}{103951}Mìsíèku?
{104029}{104084}Muta?
{104099}{104177}Mami! Muta zase odešel!
{104186}{104216}Muta!
{104239}{104270}„Muta”...
{104334}{104475}<i>„Šepot srdce”|Naslouchej hlasu lesa...</i>
{105068}{105133}Baron jako hrdina?
{105149}{105192}Vadilo by vám to?
{105203}{105320}Seiji øíkal,|e ta figurka je vaším pokladem...
{105358}{105397}Nemusíš se ptát!
{105414}{105498}Samozøejmì, e mùeš.|Ale mám jednu podmínku.
{105535}{105553}jakou?
{105564}{105679}e budu první èlovìk,|kterı si bude moct pøeèíst ten pøíbìh.
{105695}{105734}No...
{105748}{105783}Dobøe?
{105789}{105907}Ale já ještì nevím,|jestli ho dokáu napsat...
{105978}{106046}Je to stejné,|jako by si byla øemeslníkem.
{106048}{106127}Neoèekávej dokonalost.
{106137}{106196}Pojï sem. Ukáu ti nìco.
{106357}{106389}Tady.
{106490}{106516}Podívej se na to.
{106720}{106779}Jmenuje se to slídová bøidlice.
{106783}{106838}Podívej se na ty prasklinky.
{106850}{106891}Jako tato...
{107154}{107187}To je nádhera!
{107197}{107312}Tohle se jmenuje „berylium”.|Obsahuje surové smaragdy.
{107323}{107369}Smaragd? Ten drahokam?
{107371}{107390}Ano.
{107395}{107478}Ty a Seiji ste jako tento kámen.
{107487}{107558}Surovı, nevyleštìní, stále pøirození.
{107571}{107641}Mám rád takové kameny.
{107647}{107761}Ale vyrábìt housle, a nebo psát pøíbìhy,|to je nìco jiného.
{107784}{107894}Surovı kámen máš ve svém nitru.|Musíš ho jen najít a vyleštit.
{107908}{107942}Chce to èas a námahu.
{107971}{108054}Vidíš ten velkı surovı drahokam uvnitø?
{108068}{108086}Ano.
{108098}{108217}Kdy ho vyèistíš a vyleštíš bude vypadat nádhernì.
{108228}{108307}Ty menší uvnitø sou ještì ryzejší.
{108320}{108437}Tam, uvnitø, kam nevidíš,|se mohou nacházet ty nejèistší kameny.
{108448}{108546}Promiò. Staøí lidé rádi káou.
{108596}{108698}Bojím se. Co kdy ve mì není ten|pøekrásnı drahokam?
{108716}{108811}Ale chci psát. A vy budete první,|kdo si to pøeète.
{108817}{108886}Dìkuji ti. U se na to tìším.
{109091}{109179}Neopracovanı kámen...akvamarín...
{109281}{109336}Vydejme se spolu hledat...
{109349}{109415}...poklad v tvém nitru.
{109462}{109555}Neboj se. Prostor je v | noci deformovanı mìsícem.
{109642}{109732}I vìci, které jsou daleko,|se zdají bıt velké.
{109815}{109879}Pole! Je dobrı vítr.
{110024}{110105}Rychle! Planety se pøibliují!
{110405}{110454}Vıbornì! Letíme s vìtrem!
{110491}{110538}Rovnou do zámku!
{110555}{110592}Je to tak vysoko!
{110595}{110660}A tam budeme, ani si to neuvìdomíš!
{111115}{111233}Kdy tì vzduch v poledne osvìí,|mùeš se dotknout hvìzd!
{111282}{111300}Opravdu?
{111405}{111520}To je zvláštní! Shizuku ète i |nìco jiného nì beletrii...?
{112460}{112534}Øemeslník vyrábìjící housle ve vìzení...
{113327}{113359}Seiji!
{113378}{113433}Myslela sem, e si u odešel!
{113437}{113505}Dìda mi øekl, e tì tady najdu.
{113535}{113597}Odjídím zítra.
{113612}{113641}Zítra...
{113690}{113790}Neboj se, poèkám, dokud neskonèíš.
{114428}{114474}Promiò, ale nemùu|tì doprovodit domù.
{114482}{114551}To je v poøádku. Sem ráda, e si pøišel.
{114568}{114639}Nemùu pøijít na letištì,|ale budu tì èekat.
{114642}{114692}Je to jen na dva mìsíce.
{114857}{114991}Mrzí mì to, sem stále tak nespokojená.|Budu se snait jak nejlépe budu umìt, a budeš pryè.
{115177}{115216}Potom se uvidíme.
{115284}{115337}Šastnou cestu!
{115772}{115895}Já a Luisa, moje snoubenka,|jsme se narodily v daleké zemi.
{116010}{116078}Ve mìstì, kde ještì poøád dıchá magie...
{116092}{116205}...a kde v ilách jeho umìlcù|teèe krev èarodìjù.
{116359}{116470}il tam jeden uèeò chudého|vırobce figurek, kterı nás stvoøil.
{116522}{116620}Ale Luisa a já jsme byli velmi šastní,...
{116648}{116717}...protoe nás vytvoøil, aby vyjádøil| svou neopìtovanou lásku.
{116755}{116782}Ale jednou...
{116948}{116974}Shizuku!
{116988}{117014}Shizuku!
{117059}{117086}Shizuku!
{117148}{117219}Co se dìje? Tsukishima!
{117253}{117310}Promiòte, nedívala sem se...
{117312}{117374}Dávej pozor! Toto je dùleité!
{117377}{117402}Promiòte, pane.
{117404}{117449}Harada, èti teï ty.
{117521}{117586}Zase si byla nahoøe do ètyø?!
{117588}{117650}To je v poøádku. Nejsem ospalá.
{117654}{117774}Ale si celı den mimo!|Pøesnì jako teï...
{117778}{117881}Mám hlavu plnou nápadù. Musím si promyslet,|co z toho chci napsat.
{117936}{117982}U nejsem malá...
{118663}{118730}Shizuku? Ty si doma...
{118747}{118796}Proè si tu tak potmì?
{118808}{118892}Mohla si se aspoò postarat o prádlo!
{118906}{118975}Shizuku! Pojï sem!
{119044}{119103}Kde je Shizuku?
{119115}{119152}Není malá.
{119743}{119821}- Promiòte, e sem vás nechala èekat.|- Promiòte, e sem vám zpùsobila problémy.
{119823}{119908}- Je nìkdo u vıchovného poradce?|- Ne.
{119948}{119969}Tady to, prosím.
{120121}{120152}U sem tu!
{120232}{120263}Ahoj.
{120280}{120325}Dnes si doma brzo, Shiho.
{120363}{120419}Sem znièená!
{120424}{120450}Dáš si kávu?
{120452}{120480}Ano, prosím.
{120547}{120619}Mami, mùeme si promluvit?
{120625}{120649}O èem?
{120776}{120833}Uvauju, e se odstìhuju.
{120855}{120890}A u vím kam.
{120892}{120940}Ale mùeš si to dovolit?
{120952}{121003}Naspoøila sem si nìco z mého platu.
{121012}{121091}A našla sem si u i práci na|douèování po škole. Vystaèí mi to.
{121115}{121207}Mám pocit, e sem si pøíliš zvykla,|e mi pomáháte.
{121220}{121275}Promluvím si o tom s tvım otcem.
{121293}{121345}Opravdu? Super!
{121399}{121495}S penìzi jsme na tom stále špatnì,|kdy na jaøe nevystuduju a nezaènu pracovat...
{121499}{121539}...ale potom ti pomùem.
{121552}{121587}To zní dobøe.
{121599}{121665}Promiò, e sem s tím pøišla|v dobì, kdy toho máš tolik...
{121667}{121696}To nevadí.
{121711}{121794}Pomohla si dost u tøídìním|údajù.
{121805}{121933}A Shizuku se mùe lépe soustøedit na uèení,|kdy bude mít pokoj jen sama pro sebe. Chová se divnì.
{121937}{121977}I ty si to myslíš?
{122002}{122074}Volali mi ze školy. Podívej se na to.
{122093}{122126}Co to je?
{122154}{122223}Klesla o sto míst!
{122257}{122354}Ale vdy je stále u stolu...|Co teda dìlá?
{122554}{122575}Dobrı veèer.
{122578}{122616}Dobrı veèer.
{122673}{122705}Promiòte.
{122839}{122922}Která vysoká tì pøijme|s takovımi známkami?!
{122925}{122977}Nejdu na vysokou!
{122984}{123118}Mysli hlavou! Co asi tak mùeš dìlat|se støedoškolskım vzdìláním?
{123130}{123181}O své budoucnosti|snad mùu rozhodovat sama!
{123192}{123223}Pozor na pusu!
{123225}{123336}Podívej se na fakta! Škola napsala|zprávu po vısledcích z druhého testu!
{123339}{123385}Tobì se to mluví!
{123394}{123466}Ani ty nestuduješ a zvládáš to!|A k tomu ještì pracuješ!
{123468}{123524}Dìlám, co musim!
{123538}{123640}A ty se svojim povinostem vyhıbáš!|Nechápeš?
{123654}{123733}Dìlám nìco dùleitìjšího!
{123743}{123815}Jako napøíklad co? Øekni mi to.
{123848}{123918}Shiho, Shizuku...to staèí.
{123920}{123997}Ale tati...poslouchej, co øíká!
{124005}{124088}Obì pojïte sem a øeknìte mi,|co se stalo.
{124092}{124156}Shizuku, pøevleè se.
{124213}{124243}Dìlej.
{124579}{124673}Je pravda, co øíkala Shiho?
{124675}{124729}Já se starám o svoje známky!
{124731}{124790}Ale øíkala si, e nejdeš na vysokou.
{124792}{124858}To proto, e si øíkala, |e se na ni nedostanu!
{124860}{124968}Shiho...mùu si se Shizuku|popovídat chvilku sám?
{124971}{124991}Ano.
{125067}{125086}Kde je máma?
{125088}{125122}U Tanaku.
{125139}{125159}U sem tu.
{125161}{125208}Ahoj mami.
{125211}{125244}Otec se u vrátil?
{125267}{125370}Asako, mohla by si pøijít sem?|Máme dùleitı rozhovor se Shizuku.
{125372}{125400}U jdu.
{125543}{125589}Dobøe, Shizuku...
{125635}{125733}Je to, co dìláš teï dùleitìjší,|ne škola?
{125784}{125845}Mùeš mi øíct, co to je?
{125868}{125913}A bude vhodná doba.
{125925}{126017}Je to nìco, co musíš dìlat|právì teï?
{126027}{126108}Potøebuju u jen tøi tıdny,|aby sem to dokonèila!
{126122}{126202}Testuju se.
{126210}{126233}Musím...
{126244}{126316}Testuješ sama sebe? Jak?
{126369}{126418}A jak to máme vìdìt, kdy nic neøekneš?
{126469}{126535}Je to nìco, co nemùeš|øíct ani nám?
{126572}{126595}Seiya!
{126597}{126645}Ach...promiò.
{126879}{127034}Cokoliv to dìláš v knihovnì,|obdivuju jak tvrdì pracuješ.
{127061}{127135}Nechme ji, a dìlá, co uzná za vhodné.
{127159}{127225}Nemusí jít kadı stejnou cestou.
{127264}{127373}Mìla by sem to vìdìt, byla sem taky taková...
{127407}{127490}Dobøe Shizuku, dìlej to, v co vìøíš.
{127515}{127608}Ale není to lehké vykroèit|svojí vlastní cestou.
{127628}{127690}A kdy ti to nevyjde, budeš se obviòovat.
{127737}{127810}A veèeøej zase s námi. Dobøe?
{127813}{127859}Ano. Jsme pøece rodina.
{127861}{127884}Ano.
{127895}{127934}Zavolej Shiho.
{128010}{128039}Udìlám èaj.
{128117}{128143}Shizuku...
{128187}{128293}Vím, co øíkal otec, ale ve skuteènosti|si velmi pøeje, aby si pokraèovala ve studiu.
{128302}{128364}Vím, mìl to napsané ve tváøi.
{128375}{128455}Odstìhuju se pøíští nedìli.
{128474}{128509}A ty budeš mít svùj vlastní pokoj.
{128519}{128560}Odcházíš z domu?
{128563}{128614}Ano. Dávej na sebe pozor!
{128881}{128902}Rychle!
{128919}{128962}Rychle!
{128998}{129054}Jen jeden je skuteènı.
{129064}{129119}Ale kterı to je?!
{129122}{129143}Rychle!
{129158}{129179}Rychle!
{129211}{129235}Rychle!
{131607}{131730}Luisa...nakonec si pøišla...|ale já jsem tak zestárnul...
{132374}{132406}Shizuku...
{132408}{132508}Pojï dál... Trochu sem si zdøíml.
{132540}{132654}Promiòte, e vás vyrušuji,|ale donesla sem svùj pøíbìh.
{132741}{132808}Je hotovı?
{132856}{132940}Slíbila jsem vám, e budete první,|kdo si ho pøeète.
{132943}{132990}To je román!
{132994}{133078}„Šepot srdce”
{133089}{133197}Mùete si ho teï pøeèíst?|Poèkám tak dlouho, jak bude tøeba.
{133207}{133330}Ale kdy si na tom tak tvrdì pracovala...|nemìl by sem si na to i já vzít víc èasu?
{133339}{133463}Kdy se vám to nebude líbit, nemusíte|to doèítat. Nerada vás nutím, ale...
{133490}{133543}Moje srdce bije jako zvon...
{133558}{133622}Dobøe, pøeètu to hned teï.
{133625}{133699}Sedni si k ohni. Je chladno.
{133824}{133882}Teï nás nebude nikdo rušit.
{133988}{134062}Mùu poèkat dole?
{134090}{134142}Je to v poøádku, nebude mi zima.
{134184}{134274}Samozøejmì... ale...
{136027}{136069}Ty si tu usnula?
{136075}{136127}Shizuku... skonèil sem.
{136187}{136243}Dìkuji ti. Je to moc dobré.
{136245}{136284}Ne! Není!
{136294}{136378}Øeknìte, co si o tom opravdu myslíte!|Nedokázala sem napsat, co sem opravdu chtìla!
{136389}{136464}Poslední pùlka nedává smysl.|Vím to!
{136471}{136567}Ano...je to neopracované,| nedokonèené,...
{136571}{136623}...pøesnì jako Seijiho housle.
{136687}{136812}Ale ukázala si mi neopracovanı kámen,|kterı je tøeba vytesat ze skály.
{136835}{136917}Tìce si pracovala.|Si vıborná.
{136955}{137059}Nemusíš se teï unáhlovat.|Dej tomu èas a vylešti to.
{137656}{137732}Venku se ochladilo. Pojï dovnitø.
{137735}{137761}Teï...
{137775}{137845}...kdy sem to dopsala vím,...
{137863}{137915}...e chtít nestaèí.
{137928}{137990}Musím se ještì hodnì uèit...
{138019}{138114}...ale Seiji jde dál a dál|dopøedu.
{138127}{138241}Cítila sem to, kdy sem se snaila psát|a byla sem tak vystrašená...
{138300}{138360}Máš ráda Seijiho?
{138865}{138904}Jaké to je?
{138933}{138961}Je to krásné.
{139003}{139126}Kdy Seiji dokonèil svoje první housle,|tøásla se nám ramena.
{139131}{139184}Velkou porci.
{139303}{139339}Dìkuji ti.
{139385}{139451}Take kde sem to byl?
{139455}{139533}Našli jste Barona v kavárnì...
{139555}{139579}Ano v Nìmecku...
{139623}{139724}Byl sem tehdy student.|Vypadal tak melancholicky...
{139728}{139799}Poprosil sem majitele,|aby mi ho prodal.
{139831}{139870}Ale on nechtìl.
{139874}{139993}Baron mìl toti milou|a on je nechtìl rozdìlit.
{140028}{140157}Èekal na ni, a se vrátí z opravy...
{140161}{140208}...z obchodu na vırobu figurek.
{140228}{140308}Jako v mém pøíbìhu!
{140320}{140391}Ano... pìkná náhoda!
{140398}{140495}Musel sem se u vrátit domù|a tak sem to skoro vzdal.
{140509}{140597}A potom jedna moje pøítelkynì...
{140619}{140700}...øekla, e a se druhá figurka|vrátí, ona si ji vezme...
{140703}{140771}...a donese ji té druhé figurce.
{140774}{140834}A tak se majitel vzdal.
{140848}{140940}A tak sem opustil Nìmecko|jen s Baronem.
{140943}{141097}Slíbil sem jí, e se vrátím a poádal|ji, aby opatrovala tu druhou figurku.
{141130}{141205}A se figurky opìt setkají...
{141220}{141298}...setkáme se i my dva.
{141339}{141462}Ale potom zaèala válka a já|sem nemohl dodret svùj slib.
{141507}{141626}Kdy sem se tam koneènì vrátil,|všude sem ji hledal.
{141653}{141776}Ale nenašel sem po ní ani stopu,|zrovna tak jako po Baronovì milé.
{141809}{141891}Musela pro vás hodnì znamenat...
{141899}{142063}Tvùj pøíbìh mi ji zase pøipomenul.
{142066}{142109}Ach...
{142308}{142357}Nastav ruce.
{142511}{142533}Ale...
{142536}{142641}Tento kámen se k tobì perfektnì|hodí. Dám ti ho.
{142659}{142750}A teï dokonèi svùj pøíbìh.
{142752}{142773}Ano.
{143151}{143188}Dìkuji vám!
{143287}{143321}Sbohem!
{143570}{143595}U sem doma.
{143610}{143638}Ahoj.
{143704}{143734}Kde je otec?
{143746}{143832}V koupelnì. Kde si byla doteï?
{143835}{143970}Mrzí mì, e jste se o mì báli.|Dnes se zaènu znovu uèit na ty pøíjmaèky.
{143982}{144042}Take tvùj pokus skonèil?
{144052}{144086}Prozatím.
{144136}{144191}Jedla si? Je tam kari...
{144194}{144216}Sem v poøádku!
{144264}{144301}„Prozatím”...
{144545}{144603}Shizuku, koupelna je volná.
{145079}{145125}Aha, dala si pøestávku.
{146725}{146754}Ne!
{146946}{146984}Poèkej tady!
{147352}{147403}To je zázrak! Ty si tady!
{147407}{147443}Nezdá se mi to?
{147448}{147521}Chytil sem døívìjší let. Naskoè.
{147538}{147613}Poèkej...nastydneš.
{147679}{147704}Nasedej.
{147736}{147766}Vezmu si kabát.
{147769}{147820}Nemáme èas! Nasedej.
{147878}{147914}Dr se pevnì.
{148049}{148142}V duchu sem na tebe volal:...
{148144}{148179}„Shizuku!”
{148184}{148259}A potom si se objevila v oknì!
{148272}{148298}Není to super?!
{148335}{148420}Ano... mám pocit, e se mi to zdá!
{148563}{148603}Jak bylo v Cremonì?
{148611}{148694}Jinak, ne sem èekal. Ale zvládnu to.
{148719}{148745}Vychází slunce!
{148967}{148994}Mám seskoèit?
{148996}{149022}To je v poøádku.
{149047}{149171}Umínil sem si, e tì vezmu|na ten kopec!
{149174}{149214}To není fér!
{149281}{149338}Nechci byt pøítìí!
{149415}{149494}Chci bıt uiteèná!
{149522}{149571}Dobøe! Tlaè!
{149590}{149615}A jsme skoro tam!
{149964}{150034}Shizuku! Naskoè!
{150474}{150501}Stihli jsme to!
{150621}{150670}- Pomùu ti.|- Není potøeba.
{150754}{150776}Tam...
{151188}{151276}Jeeej! V mlze to vypadá jako moøe!
{151280}{151371}Toto je moje tajné místo.|U je skoro èas.
{152451}{152505}Chtìl sem, aby si to vidìla.
{152587}{152652}Dìda mi všechno øekl.
{152657}{152767}S nièím sem ti nepomohl...|Myslel sem jen na sebe.
{152771}{152846}Ne...ty si byl dùvod, proè sem to dokázala.
{152867}{152981}Sem ráda, e sem to udìlala.|Teï u vím, co chci.
{152996}{153118}Budu se tvrdì uèit|a pùjdu na vysokou.
{153120}{153181}Poslouchej, Shizuku...
{153211}{153297}... ještì nemùu øíct, kdy to bude, ale...
{153316}{153363}...vezmeš si mì?
{153395}{153502}Budu vırobce houslí a potom...
{153629}{153654}Myslíš to vánì?
{153656}{153732}To je pøesnì to, co chci.
{153739}{153787}Opravdu? Super!
{153799}{153872}Poèkej... je chladno...
{153892}{153953}Shizuku...miluju tì!
{154226}{154447}O pøeklad se pokusil Sanguis, premek.d@centrum.cz

