{0}{199}Swing Girls.2004.DVDRip.XviD-TLF|23.976
{692}{810}A ijí prázdniny!|Tak zase na podzim!
{1098}{1177}Letní douèování|Dìjepis
{1218}{1288}Letní douèování|Obèanská vıchova
{1313}{1367}...se rovná 3.
{1394}{1465}Vlastnì... jsou to opravdu 3?
{1503}{1539}Je to správnì.
{1549}{1687}Kdy je X vìtší ne 1, tak horní èást, |kdy je menší, tak ta spodní.
{1695}{1803}Letní douèování,|Matematika, 13 studentù
{1804}{1840}Tavenı sır!
{1843}{1895}To spíš bláto...
{1966}{1989}Take?
{1990}{2016}Jen do toho..
{2016}{2039}Sleduj...
{2043}{2064}Fuj...
{2557}{2678}Ach jo, ti se mají...
{2980}{3083}Doufám, e dneska prohrajou.
{3087}{3158}Proè, kdy jim budeme hrát?
{3165}{3286}Pøátelé mì pozvali |na cestu na Havaj.
{3395}{3428}Ké bych mohla jet.
{3429}{3489}"Konec v kapele"|Ké bych mohla jet...
{3506}{3526}Ehm...
{3529}{3582}Volali jste jim?
{3585}{3661}U nemùeme èekat,|musíme jet.
{3665}{3768}To je dobré, urèitì bude |všechno v poøádku.
{3792}{3816}Ehm...
{4041}{4124}My jim ukáeme!
{4127}{4222}Zmrzlina Yoneyama!
{5014}{5110}Oni u odjeli?|Autobus s dechovou kapelou?
{5114}{5209}Coe? Jo, pøed chvilkou...
{5222}{5276}A co obìdy?
{5291}{5370}Mám ještì další rozváky...
{5419}{5456}Co se to tam dìje?
{5473}{5585}Pane uèiteli, |obìdy pro kapelu...
{5588}{5707}Ten pán má ještì další zakázky, |myslím, e bychom jim je mìli zavést...
{5710}{5765}Co si jen poènou bez obìdù?
{6298}{6325}Pøipraveni?
{6908}{6965}Co má tohle znamenat?
{6979}{7034}To je úplnì královskı pohoštìní.
{7038}{7076}Dej mi kousek.
{7126}{7208}Poèkej, já taky.
{7244}{7297}Chodím do tøídy |èíslo jedna. A ty?
{7300}{7370}My jsme všichni z trojky. |Jako uèitelku máme "babiznu".
{7381}{7455}Vy máte Kubotu, e?|To se máte...
{7456}{7536}Drím dietu, take |jen malej kousek...
{7611}{7656}Nechte mi taky!
{7725}{7790}Hej! To pøece nemùeme!
{7798}{7850}Jeden obìd jim nemùe chybìt...
{8344}{8408}Nevystupujeme tady?
{8440}{8469}Co?
{8485}{8572}Sakra! Dìlejte! |Vystupujeme!
{8575}{8600}Nezapomeòte obìdy!
{8651}{8704}Otevøete!
{8998}{9076}"Havaj"
{9428}{9503}Nakamuro! U zase ty?
{9523}{9554}Omlouvám se...
{9573}{9623}Po zápase si |musíme promluvit!
{9626}{9657}Dobøe.
{9662}{9736}Kde jsou s tìma obìdama, Nakamuro?
{9739}{9833}Nevydríme jen tak hrát, |umøeme hlady...
{9834}{9930}Nebojte, urèitì tady |kadou chvilku budou..
{10407}{10458}Za hodinu jede vlak zpátky.
{10461}{10503}Co budeme dìlat?
{10527}{10591}To je horko..|Nemáte nìco na pití?
{10594}{10622}Napij se z rıového pole.
{10625}{10682}Nikde ádnej automat..
{10721}{10790}Rozmae se mi make-up.
{10841}{10904}Urèitì se spálím.
{10908}{10947}Chcete nìkdo opalovací krém?
{10956}{10988}Já taky..
{10991}{11028}Dej mi trochu na ruku.
{11032}{11086}Nechodila jsi do solária?
{11089}{11156}Nech toho, zmìnila |jsem prostì názor.
{11604}{11650}U toho mám plnı zuby!
{11654}{11702}Jsem celá od bláta.
{11711}{11754}Podívejte...
{12349}{12470}Kde jste byli?|Ze školy jste vyrazily snad pøed tıdnem..
{12474}{12548}Zrovna ty máš co øíkat...
{12552}{12666}Vdìènost bereme, |ale nadávky si nech...
{12688}{12706}Promiòte..
{12709}{12793}Donesli jsme vám je, |protoe jsme s vámi cítily.
{12822}{12899}Dobøe, chápu, to u staèilo.|A teï nám je u koneènì dejte.
{12902}{12953}Proè bysme mìly?
{12957}{13043}No dobøe, ale rozdáme je samy.
{13197}{13259}Koneènì obìd.
{13696}{13743}Hej a co já?
{13746}{13767}Coe?
{13795}{13815}Jeden obìd chybí.
{13832}{13887}Co? Na mì se nedívej.
{14135}{14185}Pojïte na karaoke!
{14189}{14243}Jo! Jo!
{14628}{14675}Co je s váma?
{14676}{14722}Já jen...
{15053}{15098}Co se tady dìje?
{15397}{15484}Hurá! Hurá!
{15829}{15897}ádní skuteèní kluci |nevypadaj takhle...
{15924}{16055}Mùeš pro mì na poèítaèi udìlat |leták na mìstskou schùzi?
{16058}{16110}Musí to bıt jednoduchı, ne?
{16115}{16185}Jo, ale ne pro mì.|Neumím ho pouívat.
{16211}{16262}"Mùj milovanı poèítaè"|Nedala jsi babièce pokoj...
{16263}{16286}Nedala jsi  babièce pokoj...
{16289}{16353}...dokud ti ho nekoupila.
{16366}{16499}Návod je napsanej tak špatnì, |e mu vùbec nerozumím.
{16512}{16548}Neuvìøitelné...
{16615}{16727}To u nièeho nevydríš?|U ti nikdy nic nekoupím.
{16740}{16787}Jasnì, jasnì..
{17213}{17284}Haló, tady dùm Suzukiovıch.
{17287}{17379}Tady je Sasaki, |je Tomoko doma?
{17382}{17430}Jo, to jsem já.
{17434}{17520}Aha, to jsi ty.|Hele, pus si zprávy.
{17523}{17553}Coe? Proè?
{17556}{17602}Prostì to udìlej..
{17683}{17718}To nemùeš!
{17719}{17819}"...bìhem mistrovského zápasu v baseballu |mezi severovıchodními støedními školami..."
{17822}{17932}"...muselo bıt všech 42 èlenù dechové kapely |z yamakawské støední školy..."
{17935}{18034}"...spolu s uèitelem hospitalizováno kvùli |nevolnosti a aludeèním potíím..."
{18045}{18074}"Zdá se, e jejich obìdy..."
{18078}{18118}Co se stalo?
{18124}{18200}Pojï se podívat!|To je Tomoèina škola!
{18203}{18323}"...školní pøedstavitelé nemají |chu oslavovat vítìzství..."
{18337}{18396}"Náš kameraman, pøítomnı aby natáèel zápas,..."
{18399}{18496}"...zachytil obrázky studentù |odváenıch do nemocnice..."
{18510}{18607}"Nejdøíve byl prostor kolem |stadionu pøeplnìn sanitkami,..."
{18610}{18695}"...ale zápas se dohrál |bez vıraznìjších problémù..."
{18698}{18757}"Ach... Havaj..."
{18912}{18965}Vidìla jsi to?|Ha ha ha...
{18969}{19046}A taky jsem slyšela, |e protoe celá kapela...
{19049}{19134}...se musí léèit, tak nebudou |moct hrát na pøíštím zápase,...
{19137}{19228}...a hledají náhradníky, kteøí se mají |pøihlásit v uèebnì hudebky v 9 ráno.
{19231}{19310}Ale... já mám douèování.
{19313}{19426}Já zapomnìla. |Ale kadej by byl blázen...
{19429}{19498}...vzdát se 10 dní prázdnin|kvùli dechové kapele..
{19532}{19621}"Vzhledem k dnešnímu horku..."
{19625}{19709}"èinitelé pøedpokládají, |e obìdy byly špatnì skladovány.."
{20385}{20451}Inoue, trenér s tebou chce mluvit.|Dobøe.
{20814}{20846}"Konec v kapele"
{20930}{20960}Ehm...
{21076}{21118}Jsi tady kvùli kapele?
{21232}{21270}Umíš na nìco hrát?
{21564}{21597}Uhni.
{21608}{21650}Omlouvám se..
{21907}{21934}Ehm...
{21956}{22059}Naše kapela se rozpadla.|Prostì chceme dìlat kravál..
{22062}{22166}Umíme hrát jen na tohle, |ale pokud to nevadí...
{22260}{22377}No... v dechové kapele |se na kytaru nehraje..
{22425}{22465}Øíkals nìco?
{22516}{22547}Ne.
{22818}{22859}To je hroznı..
{23086}{23105}Hej!
{23185}{23259}To teda máte odvahu se |takhle hihòat a klábosit...
{23283}{23327}Vy za všechno mùete.
{23343}{23425}Proè to všechno zùstalo na mnì?
{23486}{23541}Vy jste to neslyšely?
{23553}{23646}Váš uèitel douèování øíkal,|e máte všechny hrát v kapele.
{23672}{23757}Proè bysme to jako mìly dìlat?
{23764}{23861}To je pøece jasnı! |Vy mùete za to, e se zkazily..
{23897}{23999}A kde máš dùkaz?|Moná u byly zkaenı...
{24002}{24045}Pøesnì tak...
{24048}{24097}Øíkali to i ve zprávách..
{24124}{24239}Ale já znám vaše tajemství..|Vy jste jeden snìdli po cestì.
{24244}{24288}No není to podezøelı?
{24353}{24463}Vaše tajemství se nikdo nedoví,|kdy vstoupíte do kapely.
{24530}{24648}Je èas se uèit.|Pojïte do tøídy.
{24791}{24817}Co se tam dìje?
{24823}{24863}Ale nic..
{25223}{25272}Pane uèiteli!
{25304}{25407}Co to melete?
{25417}{25548}Je hroznı horko..|Mluvte popoøadì.
{25562}{25679}Ehm, zná nìkdo z vás noty?|Nikdo?
{25684}{25737}Hrajete nìkdo na nìjakı nástroj?
{25784}{25846}Poslouchejte, prosím.
{25865}{25984}Pro sestavení dechové kapely |je potøeba aspoò 25 muzikantù.
{26010}{26087}Je nás poøád o dost míò.|Nehraje nìkdo z vašich známıch na nìco?
{26194}{26231}Hele, hele...
{26285}{26354}Kudlanèí kung-fu!
{26477}{26588}Zajímalo by mì, jestli je pravda, e hraním |na bubny èlovìk spálí nejvíc kalorií.
{26878}{26975}Ty jseš tu od toho,| abys nás pletla?
{27804}{27879}Jseš strašnej pøi høe na èinely, |ale za klavírem ti to fakt jde.
{27942}{28023}Ale ne, jen jsem jako |malej trochu hrál.
{28046}{28129}Wow, je prostì úasnej.
{28179}{28292}To bylo dobrı...|Kdo by to do tebe øekl..
{28295}{28315}No... ale...
{28316}{28418}Víš pøece, jak to je, ne?|Je to naše poslední šance ve škole.
{28422}{28494}A bez kapely nemùeme vyhrát.
{28509}{28647}Mám šanci dostat se do základní |sestavy, spolíhám se na tebe.
{28674}{28775}Víte, e na svìtì |jsou dva druhy lidí?
{28776}{28803}Ne...
{28811}{28934}Lidi, kteøí nìco dokáou a ti, |kteøí na to nemají - kam patøíš?
{28958}{28986}Netuším...
{28999}{29105}A co tyhle mají spoleènıho |s dechovou kapelou?
{29158}{29182}Co?
{29185}{29213}Nìjakej problém?
{29216}{29253}Co s tím je?
{29316}{29375}No...
{29453}{29537}..to je pøesnì ten styl,|co jsem mìl na mysli!
{30024}{30078}To jste všichni slyšeli |ve škole, e?
{30101}{30144}Nazıvá se to...
{30214}{30258}...Big Band jazz.
{30272}{30379}Na dechovou kapelu vás |je málo, ale dost na Big Band.
{30384}{30486}Ale jazz je jen takovı staøeckı pištìní...
{30490}{30584}...pro intelektuály nasávající brandy.
{30636}{30706}Nemùeme hrát nìco lepšího?
{30717}{30822}Kdo by nìco neobìtoval, |kdy jde o náš basebalovı tım.
{30826}{30881}Budeme hrát to, |co musíme hrát.
{30886}{30919}Co?
{31004}{31072}Tomu øíkám ubohost.
{31076}{31130}Na to je potøeba pøírodní talent.
{31225}{31357}Au, moje tváøe, urèitì |tam nìco je zaseknutı.
{31362}{31469}Kapacita vašich plic je ubohá.|Jak je monı, e jste na tom tak hroznì?
{31507}{31589}Budete muset trénovat,|a se z vás bude kouøit.
{31626}{31696}Opravdu souhlasíte s Big Bandem?
{31731}{31796}Samozøejmì...
{32178}{32280}Hele, proè ty dvì nemusí bìhat?
{32301}{32324}Ty se jich bojíš.
{32327}{32420}Neøíkej blbosti! |Ony umí hrát, tak nemusí bìhat.
{32439}{32501}U toho mám dost..
{32504}{32537}Já taky..
{32666}{32769}Mìla jsem radši zùstat |trèet v tom douèování.
{32772}{32818}Celı to byl tvùj nápad!
{32821}{32872}"Pøedstírat, e trénujeme,|pak s tím praštit..."
{32875}{32990}"...a pøitom se vyhnout douèování.|Zabít dvì mouchy jednou ranou."
{32996}{33115}Ty jseš ta, co dìlá oèi |na staršího hráèe basebalu.
{33130}{33200}Ten trénink je úplnì nanic.
{33387}{33424}Jsem znièená.
{33571}{33676}Foukejte na kapesník a udrte ho |na skle, jak dlouho jen dokáete.
{33679}{33710}Já mám svoje kapesníky!
{33713}{33782}To je prostì smìšnı!
{33785}{33810}Prostì to udìlejte.
{33846}{33904}Dobøe, na pozice.
{33931}{33972}Pøipravte se..
{33987}{34016}Teï.
{34026}{34117}1,2,3...
{34575}{34613}To je ono!
{34767}{34844}Vdechujte vzduch do aludku, ne do plic...
{34851}{34958}Vy, co je kontrolujete, ujistìte se, |e jejich aludky se naplní.
{35222}{35313}Tøi sady po tøiceti sedech-lezích |a protáhnutích zad.
{35316}{35425}A skonèíte, tak nádechy |z lahve a náustky.
{35775}{35805}Ano?
{35845}{35899}Sestavujete jazzovou kapelu?
{35939}{35991}Jsou úplnì k nièemu.
{35994}{36079}To není pravda,| snaí se ze všech sil.
{36082}{36185}Jakı to má smysl?|Jen se chtìjí vyhnout douèování.
{36199}{36260}Nemyslí to s hudbou vánì.
{36633}{36678}Pìknı chycení!
{36872}{36949}Drte se, spoléháme na vás.
{36973}{36998}Jasnì.
{37080}{37144}Co na nìm proboha vidíš?
{37163}{37244}Je prostì úasnej|s tou vyholenou hlavou.
{37285}{37354}Všichni basebaloví hráèi se støíhají nakrátko.
{37357}{37413}Rozdìlíme se, |dokud tady není.
{37478}{37519}No tak!
{37579}{37615}Kam si myslíte, e jdete?
{37618}{37637}Na toaletu.
{37640}{37728}Lháøko!|Musíte trénovat.
{37735}{37800}U zbıvá jen tıden do zápasu!
{37803}{37868}Ani nás nenechá vyèurat.
{38001}{38051}Vra mi to!
{38051}{38168}Ty jeden potrhlej...!|Zlodìji!
{38270}{38386}Není monı, aby z nás takovejhle |trénink udìlal muzikanty.
{38430}{38504}Byly jsme neschopnı u od zaèátku.
{38507}{38547}Pravda.
{38810}{38919}Dívejte! Jak je monı, |e Sekiguchi to dokáe a vy ne?
{39425}{39499}Zdá se mi, e tomu |zaèínám pøicházet na kloub.
{39729}{39802}Dobøe! A teï pozpátku.
{41325}{41370}Zaèíná se ti to líbit?
{41387}{41481}Jasnì, e ne!|Prostì nemám na vıbìr.
{42708}{42774}Díky..
{42806}{42878}Není zaè.
{42929}{42965}Na co to máš?
{42970}{43075}Koupil jsem si to a |beru to zítra na zápas.
{43087}{43137}Jseš z bohaté rodiny?
{43138}{43169}Jo.
{43251}{43314}Zaber!
{44717}{44764}To nebylo špatnı, ne?|Nebylo špatnı?
{44916}{45045}My budeme fakt vystupovat |pøed lidma, zaèínám mít trému.
{45115}{45174}Tady jste..
{45175}{45194}Co je?
{45237}{45315}Ehm... U je vám líp?
{45318}{45352}Jo.
{45405}{45528}Slyšeli jsme o tom, co jste pro nás udìlali. |Moc vám všem dìkujeme.
{45531}{45594}Trénovali jste Big Band, e?
{45597}{45670}To nebyl špatnej nápad, Nakamuro.
{45673}{45753}Je nám líto, e jsme vás |k tomu prakticky donutili, lidi.
{45756}{45866}Ale teï u nám je fajn.|Nechte to na nás, dobøe?
{45869}{45926}Ale... ehm...
{45987}{46126}Díky bohu! Mìla jsem hrùzu, |e bysme fakt musely hrát.
{46129}{46202}Douèování u skonèilo, |take všechno podle plánu.
{46205}{46299}Coe?! To byl váš |plán celou tu dobu?
{46302}{46374}Jasnì, e jo! |A tys nám na to skoèil..
{46377}{46439}Proè bysme to mìly brát vánì,|kdy to stejnì nemá budoucnost?!
{46453}{46503}To je úleva..
{46515}{46553}To u staèilo..
{46556}{46597}Díky vám..
{46666}{46710}Vypadneme.
{46886}{46947}Sekiguchi, co to dìláš?
{46950}{46973}No.. já...
{46976}{47045}Zapomeò na to, pojï!|Zapomeò na to.
{47139}{47185}Co je s nima?
{47384}{47504}Dìkuji vám, e jste je|omluvil z douèování.
{48310}{48409}Copak se stalo?|Umøel vám pan uèitel?
{48768}{48791}Nakamuro!
{49123}{49170}Zrovna jsme se potkaly.
{49298}{49378}Dva auty v poslední smìnì?
{49390}{49443}To je bez šance.
{49446}{49580}"Inoue, èíslo 15 jde na pálku..."
{49583}{49608}Coe?
{49872}{49912}Inoue! Dr se...
{49915}{49943}Inoue!
{50052}{50081}Uka jim to!
{50365}{50385}Tak pojï!
{50474}{50493}Strike!
{50532}{50561}Strike!
{50610}{50685}Máš poslední šanci!|Ty to dokáeš!
{50688}{50734}Inoue!|Dej poøádnou ránu!
{50737}{50796}Je to jedno, stejnì na to nemáš!
{50799}{50918}Ještì jeden nadhoz a jseš out!
{50996}{51081}Ještì jeden nadhoz a jseš out!
{51346}{51391}Tady je...
{51443}{51473}Je mùj!
{51476}{51509}Jsi v poøádku?
{51578}{51606}Co?
{51622}{51651}Co je?
{51760}{51788}Do prdele!
{52161}{52292}Všichni jste ještì rozevlátí z letních prázdnin. |Smiøte se s tím, e je konec.
{52920}{52951}Co se dìje? |Pojï dál.
{52954}{53006}Ne...
{53021}{53059}Kde je Nakamura Takuo?
{53062}{53109}Skonèil.
{53110}{53129}Coe?
{53132}{53177}Chceš se k nám pøidat?
{53207}{53237}Ne.
{53252}{53286}Ehm...
{53852}{53885}Ahoj.
{53908}{53942}Ahoj.
{53993}{54081}Yoshie, nezdruj.|Pojï.
{55078}{55100}Vstáváme...
{55795}{55857}350,000 yenù!
{55867}{55915}Chceš tenorovı saxofon?
{55935}{56008}Ne, jen se dívám.
{56011}{56082}Nemáte nìjaké pouité?
{56093}{56138}Pouité...
{56178}{56250}"Zastavárna Ebisuya"
{56495}{56515}"30,000 yenù"
{56516}{56536}30,000 yenù!
{56537}{56582}Jasnì, e ti nic tak drahıho nekoupím!
{56585}{56646}Proè ne? No tak...
{56649}{56719}Nikdy u nièeho nevydríš.
{56738}{56839}Mami..
{56948}{57029}Levnej šmejd..
{57186}{57221}Jsem doma!
{57231}{57285}Playstation, otevøi se!
{57332}{57355}Co je to?
{57371}{57438}Mami, moje hra je pryè...
{57519}{57545}Coe?
{57666}{57699}Tady je!
{57735}{57791}Seenu si práci a |koupím ji zpátky.
{57794}{57857}Kam s tím jedeš?
{57891}{57943}Stùj! To staèilo!
{57946}{57979}Co se dìje?
{57982}{58038}Hloupá, tupá sestra!
{60231}{60338}Poèkejte a co nástroje?|Mùeme si je pùjèit od kapely?
{60341}{60369}Ani náhodou.
{60372}{60393}Ukrást je?
{60396}{60421}Koupit je.
{60424}{60477}Ale.. nejsou drahı?
{60481}{60560}Kdy budeme kupovat pouité,|najdeme spoustu levnıch.
{60707}{60758}Nemyslím si, e pouitı |jsou dobrej nápad.
{60772}{60872}Mùou bejt poškozenı nebo si mùou |zachovat zvláštnosti minulıch vlastníkù.
{60878}{60924}A jak teda nìjakı seeneme?
{60927}{61012}Koupíme si novı, jak ty,|ty bohatej spratku!
{61015}{61048}To není spravedlivı.
{61051}{61087}"To není spravedlivı."
{61090}{61130}Takhle nemluvím.
{61133}{61178}"Takhle nemluvím."
{61181}{61208}Jseš úplnì blbá.
{61212}{61247}"Jseš úplnì blbá."
{61274}{61306}To víš, e jsem..
{61310}{61338}Koneènì ti to došlo.
{61342}{61373}A co tøeba sponzor?
{61376}{61447}Jako kdy fotbaloví hráèi |nosí na dresech loga?
{61457}{61525}Vy víte o nìjakıch spoleènostech |na vzestupu nìkde v okolí?
{61528}{61574}Podnikání mıho táty je na vzestupu..
{61577}{61652}Já si na záda nevezmu |nápis "Gynekologie Kubo".
{61655}{61747}Stejnì nemá smysl, |abysme nìèemu dìlaly reklamu.
{61753}{61809}Úplnì nereálnı.
{61812}{61887}Kayo, tvùj otec pracuje v bance.|Nedostaly bysme pùjèku?
{61887}{61936}Za to by ho vyhodili.
{61938}{61974}Víte... já...
{61977}{61996}Ty ne.
{61999}{62063}V supermarketu nabízí spoustu |pracovních míst na èásteènı úvazek.
{62067}{62125}Zrovna pøijali sestru jako pokladní.
{62129}{62150}To je ono!
{62258}{62354}Jdeme vydìlávat peníze, vydìlávat...
{62459}{62555}Tady máte nazpìt na 1,000 yenù.|Dìkujeme vám.
{62576}{62599}Dobrı den.
{62609}{62651}"Sleva 50%"
{62674}{62704}Mnì taky..
{62819}{62894}Nechcete vyzkoušet naše |nové, místní víno?
{62963}{63017}Vynikající, koupím si ho.
{63029}{63070}Dìkuji vám.
{63071}{63111}Ochutnejte, prosím.
{63152}{63208}Ochutnejte, prosím.
{63254}{63286}Ochutnejte...
{63324}{63375}Rychle, u se zavírá...
{63566}{63609}Sledujte...
{64063}{64131}"Dostihové novinky"
{64572}{64634}Ty s pøíchutí kari jsou skvìlé.
{64638}{64682}Ty se sırem taky.
{64685}{64733}Zkuste ty èokoládovı.
{64736}{64803}Mohly bysme z toho |mít poøádnı problémy.
{64859}{64887}Coe?
{64890}{64930}Pøidáme ještì trochu vína.
{64933}{64986}Nemyslím, e je to dobrı nápad.
{64989}{65064}Proè by ne?!|Dodá to tomu úroveò!
{65067}{65166}Tak co, vy jazzová dìvèata?|Pracujete tvrdì?
{65194}{65332}Nìkdy byste mohly vystoupit|ivì venku pøed obchodem.
{65382}{65427}Taky ochutnám.
{65430}{65520}Víte, zrovna se je chystáme podusit.
{65743}{65848}A naše platy...?
{65871}{65915}Ani omylem.
{65923}{65959}A u se nevracejte.
{66032}{66162}Jsme v pytli. |Koupíme to, na co máme.
{66171}{66209}To jako proè?
{66229}{66323}Vyhodili jen vás..|A navíc...
{66326}{66368}Já u si koupila Albu.
{66371}{66418}A já batoh a váèek Vuitton.
{66421}{66452}Perly Tasaki.
{66455}{66517}Skoro ádné peníze |nám nezbyly, e?
{66520}{66554}To je pravda.
{66560}{66601}Myslíte to s kapelou vánì?
{66605}{66676}Zdá se to bıt |strašná otrava.
{66721}{66764}Jak je?
{66806}{66861}Jdeme na bowling.
{66876}{66963}Ahoj, promiò, promiò...
{66967}{66993}Yoshie, chceš jít hrát?
{66996}{67018}Nemùu.
{67021}{67106}No? Nìkdo další chce |jít s náma?
{67157}{67239}Vìdìli jste, e na svìtì |jsou dva druhy lidí?
{67244}{67293}Ne...
{67296}{67418}Lidi, kteøí si mùou uívat a |ty, kteøí nemùou. Co je lepší?
{67421}{67512}Já si chci uívat!
{67518}{67641}A dost!|Zaloíme vlastní jazzovou kapelu.
{67645}{67736}Ale jak teï?|Najdeme si jinou práci?
{67758}{67817}No... já...
{67820}{67917}Kdy jsem byla malá, sbírala jsem |houby "matsutake" na dìdeèkovì hoøe...
{67920}{67977}..za docela dobré peníze.
{67986}{68047}Proè jsi to neøekla døív?
{68162}{68191}Další!
{68271}{68348}A proè tady trèím já?
{68351}{68425}Pro skupinu dìvèat je nebezpeèné |bıt samy v lese.
{68429}{68515}Hlavnì já.|Já jsem lákadlo pro úchyly.
{68519}{68556}Spíš tak lákadlo na medvìdy.
{68560}{68584}Jak se opovauješ!
{68588}{68657}Mám další!
{68730}{68790}Kolik u jich máme?
{68816}{68935}Jsem najednou nìjaká slabá.
{68938}{68985}Taky mám jednu!
{69030}{69068}Ne, ta je jiná.
{69082}{69131}Tahle houba je jedovatá.
{69199}{69242}Támhle je cenìná "matsutake".
{69338}{69462}Super.. To vaše rodina |vlastní celı ten les?
{69463}{69495}Ne.
{69504}{69568}Jak daleko mùeme sbírat?
{69588}{69630}Jak daleko...?
{69633}{69692}Ty lesy nepatøí tvému dìdeèkovi?
{69695}{69804}Ne, patøí dìdeèkovi sestøenice |kamarádky mojí mámy.
{69859}{69966}Dìdeèkovi...|To ale není TVÙJ dìdeèek!
{69969}{70038}Japonci dokáou bıt tak nechápaví...
{70062}{70100}A je to legální?
{70301}{70355}Všichni!
{70385}{70415}Podívejte!!
{70418}{70490}"POZOR! NEPOVOLANÉ OSOBY BUDOU |POKUTOVÁNY 500,000 YENÙ"
{70633}{70695}Sakra! Utíkejte!
{70771}{70812}A co houby?
{70815}{70848}Utíkej!
{72913}{73025}Omlouvám se, omlouvám se.|Moc se omlouvám! Omlouvám se!
{73149}{73182}Gratuluji.
{73314}{73372}"OCENÌNÍ PRO TANAKU NAOMI"
{73376}{73476}"KONEC ØÁDÌNÍ ZUØIVÉHO KANCE|TRIUMF 5 STØEDOŠKOLÁKÙ"
{73486}{73567}"Vám, kteøí jste nás zbavili kance, |kterı nièil naši úrodu..."
{73570}{73628}"Tady máte, jako dùkaz naší vdìènosti..."
{73706}{73779}Zvládli jsme to! Skvìlı!
{73782}{73838}Teï si koneènì mùeme |koupit ty nástroje.
{73841}{73883}Nenajdeme dalšího kance?
{73886}{73963}Bylo mi toho chudáka |kance trochu líto.
{73964}{74040}Vdy nièil pole,|byla to boí pìst..
{74151}{74264}Øíkala jsem ti, e nám |pouité nástroje staèí...
{74350}{74425}Hej! Co to dìláš?
{74426}{74447}Ale ne!
{74469}{74522}Hrùza...
{74536}{74572}Ani se nehne..
{74758}{74802}Co tam máš?
{74812}{74846}Podívej.
{74979}{75018}Co to..?|Co to je?
{75035}{75088}Kam to bìelo?|Kam to bìelo?
{75091}{75186}Pøesnì tohle jsem øíkal|o pouitıch nástrojích.
{75187}{75280}Tak proè jsi to neøek døív,|ne jsme si je koupily?
{75283}{75382}Ty jedinej tomu rozumíš!|Øekni nìco!!
{75385}{75404}Ale...
{75405}{75450}"Ale" na mì nezkoušej..
{75453}{75552}Utratily jsme všechny peníze!|Co budeme teï dìlat?
{75555}{75620}Moná bysme je|mohly nechat opravit...
{75624}{75695}Neøíkej, e...
{76097}{76176}No ne, je celkem pìknej..
{76245}{76290}To sou ty holky?
{76293}{76361}Tìm jste daly pøednost |pøed náma, jo?
{76368}{76440}Máte hodnì blbej pøístup..
{76442}{76524}A vy máte poøádnı nervy, |e se tady vùbec ukazujete..
{76527}{76552}Øekni jim to..
{76556}{76610}Jste zrádci.
{76611}{76665}Øíkal jsi, e nám opravíte vìci..
{76673}{76772}Jo, to jsem øíkal.|Øekl jsem ti to, abys sem pøišla.
{76773}{76832}Poøád jsem do tebe blázen.
{76841}{76914}Já do tebe taky.
{76916}{77009}Já vím. Ale je to dobrı..
{77012}{77083}..dokud víš, co k tobì cítím...
{77098}{77138}Ty taky, e brácho?
{77193}{77252}Necejtím ani hovno.
{77305}{77357}Nevzdávej to!
{77365}{77397}Dr klapaèku!
{77474}{77548}Musíš jít hledat svoje |sny sama, Hiromi.
{77585}{77644}Budu ti dret palce.
{77668}{77756}U buïte zticha!|Nesnáším, kdy takhle blbnete.
{77775}{77841}Vypadá to sloitì...
{77945}{78031}Ty u zase breèíš?|Neblbni s depkou, buï trochu chlap.
{78097}{78179}To proto se váš styl |nevyrovná vašemu hraní.
{78182}{78238}A proto jsme vás nechaly.
{78245}{78303}Ale to nevadí.
{78325}{78399}U jen to, e vás zase |vidíme, nám staèí.
{78448}{78520}Rozhodli jsme se, e |vytvoøíme folkové duo.
{78578}{78686}Dokonce máme i novou píseò.|Poslechnete si ji?
{78694}{78792}Dobøe, poslechneme.|To pøece chcete, ne?
{79079}{79124}Jmenuje se...
{79127}{79186}"Odkopla jsi mì, |ale já tì stejnì miluju"
{79288}{79389}"Bude ti to vadit..."
{79392}{79501}"...kdy budu breèet..."
{79581}{79696}"Promiò, jen pomyšlení na tebe..."
{79700}{79762}"...a zas mám slzy na krajíèku."
{79766}{79824}"Breèím zlato, jak slaboch a zbabìlec..."
{79828}{79943}"Jsem úplnì zoufalı..."
{79948}{79995}To je super..
{79998}{80085}Hele, hele, to je pìknı...
{80155}{80216}Tohle? Není to ono?
{80278}{80306}Je to o 1.5 milimetru kratší.
{80309}{80371}Ty seš ale vybíravej.|Komu to vadí?
{80374}{80428}Ne, najdi pøesnì stejnej.
{80468}{80517}Dívejte, co jsem našla.
{80758}{80789}Opatrnì.
{80892}{80944}Øíkám opatrnì!
{82391}{82432}Buïte tam zticha!
{82448}{82500}Vy chuligáni.
{82815}{82898}Co se to tady dìje?|Nechte toho u!
{82912}{82989}Proè bysme mìly?|Zaplatily jsme si za pokoj.
{83031}{83079}Dokonce pouíváte i moji elektøinu!
{83082}{83153}Ostatní hosté si stìují na hluk!
{83156}{83225}Sakra! A kam pùjdeme teï?
{83237}{83344}Poslyšte, mùete hrát |u mì, jestli chcete.
{83438}{83519}"Moderní Jazz od Dívek swingu"
{83913}{83944}- Nech toho!|- Promiò..
{84179}{84237}Téhle sraèce øíkáte jazz?
{84240}{84302}Jestli chcete hrát v kapele, |tak si fidlejte ve škole!
{84585}{84679}Pøestaòte, pøestaòte!
{84683}{84821}Vaše hudba mi odhání zákazníky.|Vùbec jsem vás sem nemìl zvát...
{84866}{84936}Zavolejte, kdybyste sehnali jinı místo.
{84939}{84994}Tomu nevìøte.
{85283}{85327}Kde je Sekiguchi?
{85768}{85804}Díky.
{85850}{85882}Kdo to byl?
{85891}{86020}Vidím špatnì...|Nìjakı pán, kterıho neznám... asi.
{86024}{86085}Øíkal, e musíme mít šmrnc.
{86114}{86201}Šmrnc? Ten tomu tak rozumí..
{86208}{86303}Prej to, e chytneme stejnej |rytmus, znamená víc ne noty.
{86306}{86340}Fakt?
{86491}{86537}Poèkejte chvilku, pane!
{86643}{86704}Dìlejte.
{86721}{86744}Sbalte to.
{86745}{86777}Pomozte mi nìkdo.
{86780}{86833}Za ním!
{86852}{87003}Poèkejte, pane!|Pane, poèkejte!
{87197}{87258}Hej, stùjte!
{87406}{87502}Uteèe nám!
{87826}{87921}To není dobrej nápad.
{88360}{88428}Super.
{88748}{88810}On opravdu pije brandy.
{89288}{89388}No... proè jste pøed námi |utíkal, pane uèiteli?
{89420}{89480}Nesnáším dìti.
{89503}{89629}A navíc, kdy slyším, |jak vradíte hudbu...
{89632}{89653}...strašnì mì to vytoèí.
{89721}{89754}Nesahat!
{89775}{89879}S deskami se musí zacházet opatrnì...
{89922}{90051}Tohle je album od hráèe na saxofon|jménem Cannonball Adderley.
{90057}{90111}Jmenuje se "Poll Winners"
{90135}{90231}Je to rarita, v Japonsku ho neseenete.
{90240}{90271}Omlouvám se..
{90358}{90430}Tohle je Eric Dolphy,
{90433}{90544}nahráno ze ivého vystoupení|v New Yorku v klubu Pìt teèek,
{90547}{90584}...v roce 1961.
{90591}{90634}V jeho kapele hrají...
{90649}{90742}Booker Little na trumpetu, na klavír...
{90745}{90800}Je super..
{90813}{90899}..na basu Richard Davis, na bubny...
{90925}{91005}"101 vìcí, co byste mìli vìdìt |o jazzu aneb jak se nauèit hrát"
{91016}{91120}Vy.. jste to koupil pro nás?
{91128}{91204}Jo, jo...
{91217}{91350}Myslím, e to bude pro vás |ten správnı startovní bod.
{91353}{91472}Já to vìdìla, vy nás |budete uèit jazz, e?
{91577}{91636}Bomba!
{91692}{91737}Prosím, pane uèiteli.
{91767}{91824}Ale ne, ne...
{91824}{91881}Prosím.
{91969}{92077}Myslím, e budu muset improvizovat...
{92366}{92407}To staèilo..
{92417}{92543}Nesnate se o sloité vìci,|dokud se nenauèíte základy.
{92547}{92563}Omlouvám se.
{92566}{92618}Byl to jen jeden velkej chaos.
{92619}{92701}Jak dlouho hrajete na saxofon?
{92725}{92756}"101 vìcí, co byste..."
{92779}{92870}Objednal jsem si saxofon spolu |s touhle knihou pøed tøemi lety...
{92885}{92993}...a trénoval jsem jeden tıden,|ale nic jsem se nenauèil...
{92996}{93048}To je pro mue typické..
{93049}{93100}Dìlají to jen proto,|aby na to balili holky.
{93105}{93179}Proè jste se rozhodnul |to znovu zkusit?
{93193}{93243}Mám svoje dùvody..
{93245}{93273}Vsadím se, e je za tím enská...
{93274}{93295}Urèitì?
{93298}{93329}Urèitì.
{93333}{93379}Tentokrát to tak není!
{93384}{93445}Nekritizujte mì, vy dva!
{93448}{93506}Uklidnìte se..
{93510}{93593}Ale noty neumíte, e?
{93599}{93614}Je mi to líto...
{93617}{93669}To je ale blbec!
{93678}{93754}S pomocí mé techniky |se dokonce i zaèáteèník...
{93757}{93843}...mùe nauèit hrát |velice dobøe. Vìøte mi.
{93847}{93964}Na zaèátek se zamìøíme na rytmus.
{93975}{94037}Jazz má jedineènı rytmus...
{94041}{94094}Dùraz se klade na konec taktu...
{94110}{94222}...zatímco ve vìtšinì jiné |hudby zdùrazòujete zaèátek.
{94351}{94421}Ale v jazzu je to naopak.
{94519}{94605}Prostì se drte toho rytmu |a dokáete zahrát cokoliv.
{94608}{94644}Zkuste to.
{95045}{95099}Ne, ne.|Úplnì špatnì.
{95441}{95475}Hm?
{95569}{95622}Co tam provádíš?
{96238}{96277}Není to jazz?
{96387}{96413}Zbláznila ses?
{96417}{96458}Ne, to teda není.
{96736}{96837}Wow! Teï u to je jazz! |Swingujeme!
{96916}{96942}Mami, kdo to je?
{96945}{96977}Nedívej se.
{97435}{97490}"U DNES NA PRODEJ"
{97760}{97815}Take tohle je ten jazz..
{97818}{97880}Pøesnì jako podomní obchodníci..
{98241}{98276}Dìkujeme, dìkujeme.
{98279}{98377}A teï co se tıèe |našich jednodenních slev:
{98380}{98460}300 gramù vepøového |jen za 198 yenù!
{98463}{98521}Pouhıch 198 yenù.
{98526}{98623}88 yenù za balíèek vajec!
{98626}{98710}Tyhle ceny platí jen dnes.
{98738}{98868}Tomoko, na veèeøi je miska s rıí a kuøecími vejci.|Èekáme na tebe s veèeøí jen do sedmi.
{98872}{98966}Myslíš praseèí vejce.
{98970}{99037}Nechte mì na pokoji...
{99049}{99130}Aki, my jdeme do obchodu.
{99133}{99177}Já se budu dívat |na ségru, jak hraje.
{99678}{99744}Tak zase zítra..
{100218}{100316}Kde jsou? Ty holky |se na nás vykašlaly...
{100559}{100591}To jsou ceny!
{100594}{100627}To jsou fakt ceny?
{100653}{100704}Nepøidali tam navíc|jednu nulu?
{100707}{100746}Co si pøejete?
{100747}{100813}Nemáte nìjaké pouité?
{100834}{100924}Prodejte ty znaèkovı hadry, co |máte na sobì a mùete si koupit novı.
{102929}{102955}Podívejte!
{102959}{103009}"Pøihláška na festival studenstkıch kapel"
{103101}{103193}Coe? To u to všichni víte?
{103281}{103411}Pøed chvilkou jsme se to dovìdìly.|Vıroèní festival ve mìstì.
{103414}{103536}Ve mìstì! Máme šanci zahrát si|ve velkım koncertním sále! To musíme zkusit!
{103539}{103595}To je snad jasnı!
{103598}{103671}Pane uèiteli, budete dirigovat?
{103677}{103753}Coe? No...
{103758}{103802}kdy na tom trváte...
{103805}{103857}Vıbornì.
{103861}{103899}Ale ne tak rychle..
{103902}{103974}Ještì nás nepøijali.
{104028}{104121}Musíme se nejdøív zùèastnit|konkursu s natoèenou videokazetou.
{104132}{104227}Konkurs? To jako,|e je tam porota?
{104233}{104327}Vìtšinou všechny pøijmou,|pokud nejsou úplnì nanic.
{104342}{104376}Dobrı.
{104388}{104437}To by byl pìknej trapas, |kdyby nás nepøijali.
{104440}{104498}Kdy to natoèíme? Dneska?
{104502}{104600}Kdy u jsme v tom,|tak by nám to mohlo jít od ruky.
{104604}{104630}Jdeme na to.
{105671}{105704}Tady ji máš.
{105707}{105777}Hned to pošlu.|Díky, e jste pøišel v nedìli.
{105780}{105802}O nic nejde.
{105805}{105877}Pane uèiteli...
{105878}{105968}...nezdálo se vám, e ta poslední |èást se mi trochu nepovedla?
{105971}{106074}Mám poøád pocit, e se drím |moc zpátky na tom vysokém tónu.
{106077}{106180}Pøesnì tady.|Mohl byste mi s tím pomoct...
{106217}{106335}Ale víš.. já bych øekl,|e to bylo docela dobré..
{106371}{106410}Ale pane uèiteli...
{106532}{106602}Jak se opovauješ!
{106780}{106821}Promiò!
{107206}{107252}Tak tos pøehnala!
{108614}{108661}Troubo!
{109049}{109095}A co tøeba tohle?
{109100}{109170}Chci vypadat parádnì.
{109173}{109258}Chytøe a dospìle.
{109259}{109292}Špehujete?
{109296}{109333}To jsem se lekl.
{109396}{109430}Jak dlouho u jste tady?
{109434}{109473}Od zaèátku.
{109490}{109607}Prohlííte si naše uniformy?
{109619}{109681}Slyšela jsem, e jste se taky pøihlásili.
{109684}{109710}Jo.
{109713}{109741}Jako jazzová kapela?
{109744}{109785}To je tajné.
{109788}{109858}Nepovídejte...|nìjaké pøekvapení?
{109861}{109907}Všechny nás pøeseknou |napùl pøímo na pódiu.
{109954}{110001}Jako Big Band.
{110009}{110097}No jasnì, samozøejmì.
{110101}{110194}Pro klasického hudebníka je jazz jako...
{110195}{110289}Je tìké chytit jeho rytmus |a získat si diváka.
{110293}{110387}Coe? A co teda všechny ty|jazzové desky na polièce?
{110444}{110552}Aha, to. Asi pøed 2 nebo 3 roky, |je sem náš uèitel matiky Ozawa,
{110556}{110649}zaèal nosit. |Kadı den jednu.
{110670}{110745}Myslíte jako, e jste se mu líbila?
{110800}{110932}Byl tak horlivı, e jsem mu øekla, |jestli s námi nechce hrát...
{110935}{111009}..ale pak znièeho nic|pøestal pøicházet.
{111014}{111056}Kdoví proè?
{111060}{111105}Kdoví...
{111154}{111262}A u vám dali vìdìt z festivalu? |Nám u napsali.
{111293}{111328}Ještì ne...
{111335}{111453}Vdycky pøijde jen málo pøihlášek,|urèitì vás pøijmou.
{111467}{111518}Jen se nás nesnate |napodobovat, OK?
{111758}{111816}"Pøihlašovací video na hudební festival"
{111816}{111874}Proiju celej ivot jen |s láskou k mé trumpetì.
{111874}{111912}To není monı.
{111920}{112002}Ale je. Líbám se s ní kadı den!
{112005}{112041}Ještì musím nìco zaøídit..
{112045}{112089}Coe? Pùjdeme domù spolu.
{112092}{112188}Slíbila jsi, e pùjdeme na nudle.
{112191}{112215}Pøíštì, dobøe? Pøíštì...
{112218}{112276}Nebolí tì bøicho?
{112306}{112381}Urèitì na ty nudle |jdeš bez nás!
{112384}{112464}To není pravda. |Nechte mì na pokoji..
{112483}{112523}Co to s ní zase je?
{112904}{112948}Prosím, dojdi vèas!
{113433}{113472}Sakra!
{113554}{113598}Proè to nedokáu zahrát?
{114004}{114041}To byl šok!
{114049}{114129}Mám to! |Zahrála jsem to!
{114137}{114249}Kam jsi bìela?
{114318}{114365}Jak se vám to líbí?
{114391}{114415}Dobrı.
{114539}{114678}"Hudební konzervatoø Yamaha"
{115138}{115181}Já u to nesnesu!
{115184}{115227}U nìkolikrát jsem vám øíkal,
{115228}{115348}e musíte hrát s citem jako ostatní.
{115353}{115418}Ještì jsem neslyšel o nikom,|komu by základy trvaly tak dlouho..
{115420}{115471}Take zase od zaèátku..
{115725}{115792}Jste úplnì neschopnej!|Naprosto nesnesitelnej!
{115795}{115868}Nenauèím se vùbec nic nového!
{115985}{116088}Moc se stydím. Nevadilo by ti,
{116094}{116163}...kdybys o tom ostatním neøíkal?
{116198}{116245}Slibuju, e jim nic neøeknu.
{116258}{116346}Kdybych jim øekl pravdu,|ztratily by víru.
{116354}{116432}Vzdávám se dirigování na festivalu.
{116451}{116505}Odteï je to jen na vás.
{116838}{116869}Je tady!
{116872}{116911}Dìkuji vám!
{117113}{117206}Tento rok kvùli neobvykle |velkému poètu pøihlášek...
{117209}{117331}...pøijímáme kapely systémem |"kdo døív pøijde, ten døív mele". Bohuel...
{117496}{117543}Vypadám sexy, e?
{117547}{117605}To nejde.
{117611}{117661}Gynekologie Kubo|Rodinné reklama, co?
{117662}{117670}Gynekologie Kubo
{117671}{117718}Gynekologie Kubo|Rodinné reklama...
{117739}{117772}Co to je?
{117797}{117863}Talisman pro štìstí.
{117877}{117912}Tak, hotovo.
{117923}{117957}To zírám...
{118026}{118107}Co se dìje?|Celı den jsi nìjaká zamlklá.
{118167}{118228}Ehm... ehm...
{118229}{118287}A co tvoje vlasy, Tomoko?
{118290}{118365}Jestli si je nenecháš pøistøihnout, |tak je aspoò trošku odbarvíme.
{118368}{118399}Já nechci.
{118402}{118473}Poèkej, odbarvi mi vlasy!
{118526}{118570}Vypadáš fakt smutnì.
{118622}{118665}Nìco jsem vám neøekla...
{118668}{118777}Tanako, u jsi si vyzkoušela kabátek?|Mùu ti to popustit, kdyby ti byl tìsnı..
{118780}{118827}Dobøe, poèkej, vyzkouším si ho.
{118830}{118921}Tomoko, není ti špatnì?
{118925}{119021}Snad mì pochopíš, |kdy ti øeknu, e jsem...
{119025}{119110}Sekiguchi, zkontroluj jízdní øád!
{119113}{119138}Dobøe.
{119283}{119399}Ehm! Nìco dùleitého vám musím øíct!
{119449}{119486}Poslouchejte.
{119489}{119595}Náš dirigent, Ozawa, |nemùe zítra pøijít na festival.
{119599}{119658}To ne!
{119678}{119716}Yoshie, došlo mi bìlidlo.
{119720}{119747}To ne!
{119772}{119809}Ehm...
{120121}{120245}U zítra. S dechovou kapelou |se vdycky zachází královsky..
{120305}{120369}Uvidíme se v sále.
{120596}{120630}Zaswingujte!
{120688}{120742}No tak, Tomoko.
{120879}{120954}A teï si sundejte kabátky,|musíme je ještì upravit.
{120957}{121020}Já si ho chci nechat na sobì.
{121568}{121609}Není ti špatnì z jízdy vlakem?
{121781}{121893}Koukejte! Vyznání lásky!
{122004}{122088}Mnì je vdycky špatnì, |kdy jedu vlakem,
{122092}{122149}..take jsem dneska nesnídal.
{122153}{122279}Ale obìd je ještì tak daleko,|moná bych mìl pøecejen nìco sníst.
{122282}{122390}Moná... co myslíš?
{122425}{122465}No...
{122508}{122564}Musím ti nìco dùleitého øíct...
{122878}{123008}Kvùli pøívalùm snìhu |spadnul na tra strom.
{123011}{123075}Nedokáeme odhadnout, |jak dlouho potrvá jeho odstranìní.
{123096}{123143}To snad ne! |Co budeme dìlat!?
{123146}{123190}Pùjdeme pìšky, puste nás ven!
{123193}{123236}To není moné.
{123239}{123277}Zavoláme si taxík?
{123280}{123328}Nemám signál..!
{123331}{123355}Ehm...
{123356}{123422}Tohle není vhodná chvíle na cukrování.
{123529}{123575}Všichni poslouchejte.
{123648}{123703}Ohlednì dnešního festivalu...
{123864}{123913}Coe!?
{123972}{124073}Tomu nevìøím.|A my se tak snaily...
{124091}{124156}To u je na mì moc!
{124159}{124220}To je naprosto smìšné.
{124221}{124313}To jsem si mohla myslet, |e nám všechno nìjak moc vychází.
{124360}{124422}To je blbost!|Neuvìøitelnı!
{126238}{126284}Buïte zticha!
{126473}{126522}Nazdar všichni!
{126671}{126806}Sníh zdrel další kapelu, |take máte hrát místo nich.
{126809}{126910}Všude jsme vás hledali..
{126926}{126976}To jste pøijela jen kvùli nám?
{126992}{127077}I já mám slabší chvilky.
{127096}{127207}Ale ne! Zapomnìla jsem |naše obleèení ve vlaku!
{127289}{127360}U se nemùeme vracet.|Je mi líto.
{127825}{127907}"Vıroèní 20. festival studenstké hudby"
{129147}{129182}Tobì se to líbí?
{129546}{129584}Mají poøádnı zpodìní.
{129626}{129737}Co se tıèe Dívek swingu |z yamakawské støední školy...
{129740}{129810}...které získaly své místo |na poslední chvíli...
{129832}{129925}...jejich vlak má |zpodìní kvùli snìhu...
{129928}{129962}To je trapnı.
{130012}{130067}Nemoné?|Nemùou to stihnout?
{130154}{130217}Bohuel...
{130231}{130334}...tímto uzavíráme letošní festi...
{130337}{130382}Poèkejte! |Budeme hrát!
{130478}{130573}Dívky swingu nám pøecejen zahrají!
{131066}{131160}Vıbornì. Stihli to.
{131639}{131680}Poslouchejte..
{131684}{131723}Není èas, pozdìji.
{131727}{131764}Ne, ehm...
{132278}{132340}A teï u poslední èíslo...
{132344}{132436}...jazzovı Big Band soubor, neobvyklé |to seskupení mezi školními kapelami.
{132442}{132533}Dívky swingu.
{132657}{132712}Raz, dva, tøi... pìt.
{132713}{132735}Poèkejte ještì!
{133445}{133529}Slyšíte mì?|Do toho dìvèata!
{133596}{133657}Ladí nástroje.
{133666}{133727}Snad jim neprochladly nástroje..
{135238}{135276}Ještì se hraje?
{135840}{135898}"Milujeme vás, milujeme vás, milujeme vás"
{137672}{137709}Pan uèitel!
{140599}{140662}Na svìtì jsou dva druhy lidí...
{140668}{140741}...ti, kteøí swingují a ti, kteøí ne.
{141663}{141715}Já jsem je uèil!
{141719}{141815}To jsou mí studenti!|Mí studenti! Já je uèil!
{141902}{141967}Myslela jsem, e jste je uèil..
{142034}{142120}Jazz.. je lepší ne jsem myslela.
{146220}{146300}Pøeloil Tadi
{146300}{146375}Hráli:|Juri Ueno
{146377}{146472}Yuta Hiraoka
{146479}{146573}Shihori Kanjiya
{146580}{146667}Yuika Motokariya
{146671}{146757}Yukari Toyoshima
{146765}{146848}Miho Shiraishi
{146855}{146949}Naoto Takenaka
{146951}{147047}Fumiyo Kohinata
{147049}{147150}Erika Watanabe
{147158}{147257}Mutsuko Sakura
{147273}{147375}Kei Tani
{147775}{147917}Produced by Chihiro Kameyama|Yoshishige Shimatani, Ryuichi Mori
{147923}{148022}Executive Producer: Shoji Masui
{148027}{148167}Co-Executive Producers: Kazuyoshi Seki|Masamichi Fujiwara, Takehiko Chino
{148172}{148271}Producers: Daisuke Sekiguchi Shintaro Horikawa
{148272}{148366}Script Consultant: Junko Yaguchi
{148371}{148461}Music: Mickie Yoshino Hiroshi Kishimoto
{148462}{148553}Director of Photography:|Takahide Shibanushi
{148559}{148645}Lighting Director:|Tatsuya Osada
{148651}{148735}Sound Mixer/Editor:|Hiromichi Kori
{148740}{148830}Production Designer:|Norihiro Isoda
{148835}{148925}Editor:|Ryuji Miyajima
{150032}{150104}An ALTAMIRA PICTURES production
{150110}{150206}FUJI TV NETWORK, ALTAMIRA PICTURES.|TOHO and DENTSU present
{150286}{150426}Written and Directed by Shinobu Yaguchi
{150458}{150548}English subtitles:|Linda Hoaglund
{150548}{150572}English subtitles conversion:|Ayumi