{1}{1}23.976
{625}{749}Poøád øíkala jen "Promiò".
{790}{881}Nikdy mi neodmlouvala.
{953}{1073}Ale toho dne, kdy jsem ji |nachytal, jak mì podvádí...
{1103}{1157}...se mi Misao neomluvila.
{1240}{1311}Tentokrát se mi neomluvila.
{1345}{1440}Proè se mi nemohla omluvit, |kdy na tom opravdu záleelo?
{1640}{1748}MISAO - ELVA
{2046}{2123}Dìkujeme vám.
{2466}{2539}Vrátí se, nevrátí se.
{2561}{2626}Vrátí se, nevrátí se.
{2678}{2740}Hej, Misao!
{2801}{2829}elvo.
{2971}{3021}Kolik stojí permanentka?
{3046}{3095}Já vdycky jednu chtìl.
{3348}{3410}A tohle jsem taky vdycky chtìl.
{3506}{3562}Svatba nic nestojí.
{3993}{4016}Nebraò se!
{4019}{4112}Kamei, prcháš pøed spravedlností!
{4307}{4352}Zase to všechno oholí.
{5189}{5231}To snad vybouchne.
{5326}{5354}Vítejte.
{5506}{5545}Vítejte, dobrı den.
{5551}{5610}Nakayama se v tom vrtal.
{5654}{5684}Zajdu pro nìjakı peníze.
{5686}{5725}Mám vzít benzín nebo naftu?
{5729}{5757}To je fuk.
{5788}{5820}Potøebuju jít na záchod.
{5830}{5873}Potøebuju sex po telefonu.
{6250}{6317}Hej, to jsi ty.
{6355}{6395}Ahoj, Zoote.
{6414}{6507}Neøíkej mi Zoote, jmenuju se Morita.
{6547}{6616}Poøád tì teï ukazujou v televizi.
{6681}{6740}Neutíkej pøede mnou.
{6785}{6829}Pìknej oblek, Zoote.
{6831}{6874}Je italskej, na zakázku.
{6925}{6996}Naposledy jsme se vidìli |na tom setkání u Asunary.
{7035}{7130}Byl jsem v šoku, kdy tì pak sebrali.
{7159}{7217}Co to kurva øíkáš, |vdy jsi mì prásknul.
{7218}{7278}Zapomeneme na to, |u je to dávno.
{7337}{7377}Asunarùv dùm poøád stojí?
{7395}{7471}Urèitì u ho dávno zbourali.
{7547}{7635}Od té doby jsi byl vdycky mùj hrdina.
{7664}{7724}A tys byl moje hovno.
{7727}{7797}Jo, ale já nebyl jen tak nìjakı hovno.
{7799}{7858}Já byl TVOJE hovno.
{7960}{7994}Pìknı boty.
{8023}{8073}Jsou z ovèí kùe.
{8097}{8154}Vydìlal jsem teï balík na jednom kšeftu.
{8157}{8204}Nevyrazíme si nìkam zavzpomínat?
{8242}{8279}Pozvem si pár holek,
{8282}{8324}necháme je serat naše semeno?
{8382}{8435}Víš, jak se øekne semeno v angliètinì?
{8482}{8515}Dick cheese|(ptaèí sır)
{8910}{8961}Hele, co to dìláš?
{9007}{9092}Kdo kurva jsi?|Vra mi to.
{9102}{9205}Dìlej, vra to.
{9208}{9295}Uvnitø jsou peníze!
{9302}{9327}Vra mi to.
{9330}{9405}Je to zisk za celej mìsíc.|Hej, hej!
{9409}{9492}Zvedni to, Kisaro.|Co to má znamenat?
{9497}{9546}Co tam dìlá?
{9559}{9601}To bych rád vìdìl...
{9603}{9646}Novej chlap?
{9654}{9780}Proè mi to sakra nezvedá?
{9787}{9837}Tak u to zvedni!
{9885}{9908}Co to...?
{10099}{10134}Kurva!
{10302}{10388}Celá mláde je zkaená.
{10934}{10953}Ani hnout!
{11007}{11030}Ani hnout!
{11082}{11173}Ani hnout! Ani hnout!
{11231}{11254}Ani hnout!
{11325}{11459}660, 670...
{11476}{11505}Bì si dát suši.
{11514}{11543}Dìkuji.
{12025}{12107}To bolí...!
{12110}{12153}Já nechci umøít!
{12158}{12204}Co to kurva...?
{12236}{12271}Nech mì!
{12285}{12365}Nech mì!|Do hajzlu!
{12378}{12457}A umøeme, tak v tom |zùstaneme sami!
{12478}{12597}A kdy u to tak musí bıt,|tak chci umøít vedle holky!
{12600}{12618}To myslíš vánì?
{12622}{12646}Sklapni!
{12648}{12675}Sklapni.
{12696}{12737}Blbej kreténe!
{12744}{12769}Pus mì.
{12782}{12820}Bì si! Debile!
{12842}{12893}Co ty o tom mùeš vìdìt?
{12996}{13026}Já mizím...
{14161}{14190}Vidíte ty prachy?
{14222}{14277}Všichni si koupíme novı |hadry a zapaøíme.
{14342}{14399}Super, tohle nám pomùe.
{14421}{14476}To nás chceš všechny zabít?
{14504}{14600}Padej to vrátit. To poslední,|co potøebujem je yakuza za prdelí.
{14626}{14695}Vrátit to? |To myslíš vánì?
{14815}{14874}Nedivím se, e tì tvùj syn nenávidìl.
{14938}{14969}Øekni nìco..
{15171}{15194}Shishido..
{15198}{15249}Poèkej, jednu bankovku, prosím..
{15559}{15595}Proè ho nezastavíš?
{15728}{15801}Zvedni to, Kisaro.
{15846}{15905}Proè jsi mu pùjèoval ten telefon?
{15908}{15956}Protoe se zeptal.
{15960}{16001}Proè jsi mu ho pùjèil?
{16005}{16078}Protoe mì poprosil.
{16086}{16192}No tak... Kisaro.
{16438}{16467}Kisaro?
{16584}{16625}Poøád ten samej otrava.
{16687}{16770}Ahoj Kisaro, vìdìl jsem, |e tì ještì uvidím.
{16779}{16819}Pøísahám, e jsem to vìdìl.
{16823}{16853}Pozor...
{16862}{16954}Jsi poøád stejnì krásná...
{17057}{17094}Zestárl jsi.
{17118}{17168}Já? Zestárl?
{17215}{17314}No, já bych neøekl...|Ale poslouchej...
{17317}{17388}Vrátíme se spoleènì do Yokosuky.
{17393}{17493}Máminy mraenı mandarinky |jsou úasnı, fakt...
{17497}{17598}Ani omylem.|Jsi ztracenej pøípad.
{17615}{17734}Moná jsem ztracenej pøípad,|ale poøád ještì mi stojí..
{17790}{17861}Mám ten šílenı svìt ráda.
{17938}{18009}A tì popraví, |pomodlím se u televize.
{18021}{18042}Pomodlíš se za co?
{18078}{18131}Aby zmizela tvoje |pohlavní nemoc.
{18134}{18197}K jakému bohu?
{18214}{18285}Bohu šlapek.
{18333}{18410}Poslyš. Jsem tvùj dluník.
{18426}{18539}To kvùli tobì jsem odsud utekl|a dostal se a sem...
{18552}{18629}To pøece víš, ne?
{18634}{18724}Koneènì jsem na to pøišel,|opravdu jsem na to pøišel.
{18747}{18811}Ty jsi mùj nejlepší plán útìku.
{18975}{19054}Øíkáš to, jako |bys byl naivu...
{19143}{19180}Já neumøu...
{20017}{20087}Hele, moje kára.
{20092}{20179}Ona ještì jezdí...
{20903}{21125}Volané èíslo neexistuje...
{21147}{21357}Zkontrolujte èíslo a zkuste to znovu...
{21518}{21621}Dùm Asunary
{21646}{21667}Dobrı den.
{21769}{21794}Je tady uèitel?
{21815}{21862}erou ho ryby.
{21991}{22127}Ahoj! Ahoj! Èau..
{22218}{22238}Ahoj!
{22415}{22517}Dejte to prosím uèiteli.|Mìlo by to staèit.
{22531}{22606}Udìlejte si bazén.|Bazény jsou super...
{22642}{22684}Zavøeli to tady.
{22734}{22796}My se tady jen poflakujeme.
{22866}{22941}Média po nás šly kvùli vám.
{22989}{23058}Malı dìti z toho nemaj rozum,
{23070}{23148}ale zmrd, kterej mùe za to, e jim |zavøou školu, nestojí ani za pohled.
{23274}{23308}Tak si to vezmìte.
{23415}{23447}Nepotøebujeme to.
{23533}{23628}Neèekali jsme, a za náma |pøijde nìjakej zmrd.
{26125}{26198}Policie? U si vzpomínám...
{26211}{26281}...ti uprchlíci tady byli!
{26294}{26381}Jeden z nich je |dokonce pøímo tady!
{26394}{26537}Bìte ven! V klidu, |v klidu, Yoshiko, v klidu...
{26551}{26721}Yoshiko, Yoshiko...|Tiše...
{26724}{26855}Honem, honem, honem...|Potichu, potichu...
{30394}{30426}Pøestaòte.
{32463}{32483}Hej! Hej ty!
{32552}{32588}Hej ty!
{33233}{33284}Hej, blbeèku.
{33635}{33714}Ty sraèko...|Hej, hej...
{33911}{33952}Nedìlejte mi pohøeb.
{33988}{34036}Nemodlete se za mì.
{34078}{34121}Neøíkejte nikomu, e jsem umøel.
{34163}{34209}Nehledejte mou rodinu.
{34232}{34273}Neoplakávejte mì.
{34291}{34321}Zapomeòte na mì.
{34340}{34388}Vysypte mùj popel do kanálu.
{34456}{34568}Øeknìte tìm chlápkùm,|e se tam sejdeme.
{34610}{34645}Neopozdìte se.
{34647}{34707}Banka pana Yamamoto
{35224}{35339}Všichni se sem vrate do 5 hodin.
{35354}{35397}Jestli se opozdíte, nechám vás tady.
{36075}{36146}Michiru, chceš nìkam jít?
{36170}{36279}Jestli jo, tak dobøe, |já jen, jestli...
{36290}{36413}Toto je 9 uprchlíkù...
{36518}{36610}...a tohle jejich èervená dodávka.
{37243}{37297}{Y:i}Prachù mám míò,
{37303}{37357}{Y:i}ne dìvky stály...
{37366}{37425}{Y:i}...rozkrok mì pálí.
{37430}{37483}{Y:i}Kdybych jen mìl škváru...
{37485}{37549}{Y:i}uil bych si áru...
{37551}{37589}{Y:i}v jejich objetí...
{37598}{37626}Pùjèky Kaneko
{37630}{37671}Peníze na dosah ruky.
{37680}{37796}Zdravím, moje pevná kundièko.|U je to dlouho, dlouho, dlouho...
{37799}{37898}Poøádnì to roztoèíme |na vodní posteli, zatím..
{37940}{38132}Zdravím, Parco, moje nejpevnìjší kundièko.|Jo, u je to dlouho, jo, dobøe.
{38135}{38236}Jasnì, e si pamatuju, Ferragamos,|Ferragamos, jasnì.
{38258}{38366}ádnej problém, koupím ti je. Jasnì..
{38370}{38423}..na pùjèku, jo...
{38542}{38620}Jasnì, jasnì, jasnì..|Na vidìnou, pa.
{38635}{38713}Vítej doma bráško!|To je pøekvápko.
{38740}{38781}Chceš èokoládovej koláè?|Máš chu na sladkı?
{38784}{38873}Noburu...|Co se to tady dìje?
{38875}{38912}Co jako?
{38921}{39018}Myslel jsem, e tuhle spoleènost |rozpustíš a zaloíš novou školu.
{39021}{39052}Ne, fakt?
{39058}{39089}Jo, fakt.
{39123}{39165}Uklidni se, bráško.
{39167}{39245}Lichva je fakt super.|Prachy se jen hromadí.
{39248}{39397}Tupci si pùjèujou prachy, aby byli šastní |a já jsem pak taky šastnej.
{39407}{39521}Tohle mìsto je celı jeden velkej kapitalistickej |experiment a oni jsou pokusní králíci.
{39533}{39598}Nepotøebujou ádnı školy.
{39643}{39744}Kruci, jsem rád, e jsem se |narodil v Japonsku. Fakt.
{39837}{39912}Brácho, udìlal jsi dobøe, |e jsi ho zabil.
{39946}{39993}Nìkdo toho zmrda musel zabít.
{40120}{40185}Jasnì, já byl ten, co ho rozètvrtil.
{40212}{40273}Jsem ti vdìènej, es to neprásknul.
{40382}{40437}Ozvi se, kdy ti dojdou prachy, |já ti nìjakı pøevedu.
{40464}{40572}Zdravím, Michan, pevòouèká |kundièko, jak jsi se mìla?
{41055}{41124}- Pøidej brácho.|- Dobøe.
{41131}{41182}- Rychleji.|- Pozor.
{41435}{41472}Dìlám si srandu.
{41497}{41532}Srandu si dìlám.
{42187}{42230}Hele, to je Kazuma.
{42234}{42259}Kazuma?
{42270}{42302}Vidìl jsem ho v televizi.
{42315}{42392}- Zabil ètyøi chlápky.|- Bacha, u je tady.
{43700}{43784}- Tady jsi døív bydlel, Kazumo?|- Jo.
{43820}{43853}- Nezdá se ti to riskantní?|- Ne...
{43862}{43971}Kdy zabiješ 4 pøátele, |zaplatíš za to zaslouenou cenu.
{44350}{44395}Umíš jezdit na kole, e?
{44437}{44459}Je tvoje.
{44587}{44627}Na co èekáš?
{44810}{44892}Zahraju si s váma.
{44903}{44987}Kazumo... zbláznil ses?
{45297}{45368}Já to tady podpálím!|Navalte prachy!
{45719}{45822}Obøad brzy zaène.|Prosím pojïte dovnitø.
{46638}{46667}Mami!
{47410}{47442}Táto?
{47955}{47979}Vezmi si to.
{48082}{48108}Nemùu.
{48237}{48260}Proè ne?
{48347}{48413}Myslíš si, e ti podìkuju?
{48514}{48557}Co chceš, abych ti øekla?
{48888}{48924}Pøestaò, Torakichi.
{49248}{49278}Jdeme.
{49719}{49815}Ona toho spratka pojmenovala po mnì...
{50468}{50501}Mají zpodìní...
{50540}{50578}U bylo 5 hodin.
{50610}{50638}Co budeš dìlat?
{50662}{50766}Popravdì øeèeno mám øidièák...
{50788}{50817}Poèkáme...
{50952}{51016}Máš nìjakej problém |s èekáním, blbe?
{51065}{51157}Tak já zajdu nakoupit pár vìcí.
{51178}{51207}Ale ádnı zlodìjiny.
{51694}{51725}Promiòte..
{51736}{51782}Vy jste ten uprchlík Inui, e?
{51794}{51899}Je to úplnì jasnı, |vypadáte stejnì jako v televizi.
{51899}{52064}Neutíkejte nebo zavoláme policii.|Poèkat, neutíkejte...
{52447}{52527}ijí chránìni systémem |v tomhle pøecpaném svìtì...
{52532}{52602}... a jsou neteèní...
{52660}{52725}Nikdy k nim nepronikne hlas pravdy...
{52740}{52792}...a budou se poøád jen smát.
{53238}{53286}Nìkteøí vyhroují.
{53345}{53396}Další se na vás vrhnou.
{53539}{53590}Nìkteøí se chovají otcovsky.
{53673}{53722}Další pøátelsky.
{53815}{53866}Nìkteøí lpí na svıch snech.
{53954}{54020}Další jen chtìjí bıt šastní.
{54093}{54148}Nìkteøí se chvástají svojí smùlou.
{54230}{54312}Další èekají, a je nìkdo zachrání.
{54385}{54466}Nìkteøí odmítají všechno nové.
{54542}{54606}Další odmítají všechno.....
{54682}{54780}ádnı vztah, vùbec.|Nemá s mojí firmou vùbec nic spoleèného.
{54785}{54828}Nemùu uvìøit, e to všechno udìlal.
{54834}{54945}Je to chlápek k nièemu.|Nechal se zavøít na 10 let.
{54950}{55032}Nechápu, co ho to popadlo.
{55036}{55093}Prostì ho popravte... |Popravte ho!!
{55098}{55138}Bude to tak nejlepší i pro nìho.
{55146}{55186}Co myslíte?
{55572}{55616}Nìkteøí podvádìjí jiné.
{55699}{55770}Další podvádìjí jiné pro peníze.
{55850}{55909}Nìkteøí se nechají unášet ostatními.
{55986}{56050}Další jsou ochromení strachem.
{56131}{56186}Nìkteøí nejsou schopni lásky.
{56262}{56330}Dalším je jedno, e jsou milováni.
{56413}{56476}Nìkteøí nemohou utéct.
{56566}{56646}Další jsou jako já.
{56770}{56846}Bráško, co se stalo?
{56853}{56886}Aha, došly ti peníze?
{56923}{56950}Co se stalo?
{57410}{57423}Jsi mrtvej!
{58152}{58188}Proè jsi tak nasranej?
{58193}{58258}Jakej je rozdíl, jestli jsi zavøenej |ve vìzení a nebo ve svım pokoji?
{58703}{58730}To tak nenávidíš ivot?
{59117}{59142}Hej, hej, hej, hej.
{59181}{59225}To si øíkáš èlovìk?
{59266}{59286}Dr hubu!
{63688}{63794}Máme nové zprávy ohlednì vıvoje |situace rukojmích v penìním ústavu...
{63797}{63837}...Pùjèky Kaneko.
{63845}{63950}Policii se podaøilo zjistit, |e podezøelı je Kaneko Michiru (21)....
{63953}{64024}...èlen skupiny hledanıch uprchlíkù.
{64045}{64158}Kaneko se stále ukrıvá v budovì, |pøièem vzal jako rukojmího...
{64162}{64211}...prezidenta spoleènosti, Kaneka Noboru...
{64214}{64324}...a nereaguje na pokusy policie o navázání kontaktu.|Situace uvázla na mrtvém bodì.
{64357}{64445}V okolí budovy je velkı poèet...
{64448}{64489}...pøihlíejících a policistù...
{64494}{64618}...ale podezøelı zachovává |ticho ji témìø 10 hodin.
{64624}{64657}A teï k dalším zprávám...
{64872}{64908}Shiratori...
{64978}{65032}...mùj syn...
{65077}{65121}...mì poádal, abych ho zabil.
{65189}{65318}"Chci umøít, zabij mì,"|øekl vlastnímu otci.
{65431}{65465}Musíš utéct.
{65564}{65612}Kdybych se s tím dokázal |vyrovnat jako ty...
{65730}{65784}Kadı to dokáe...
{66323}{66372}Øíkal jsem, abys tìch rozcvièek nechal.
{66522}{66572}Koupíme si spoleènou permanentku?
{66607}{66658}Trošku jsem se opil, |kdy jsem utrácel ty prachy.
{66674}{66725}Èas najít si jinou holku.
{66750}{66794}Uteèeme do Brazílie.
{66801}{66839}Zajdu koupit kávová zrna.
{66879}{66917}Mohli bysme zaloit basketbalovı tım.
{66932}{66977}Mám hromadu vıbušnin.
{67131}{67154}Jeden nám chybí.
{67684}{67704}Coe?
{67733}{67793}Ty øídíš?
{67922}{67981}Máte poøádnı zpodìní, pitomci.
{69663}{69746}Otevøi dveøe!
{69776}{69921}Kaneko Michiru, otevøi dveøe|a propus svého bratra.
{69981}{70063}Vzdej se..
{73135}{73204}HARADA Yashio
{73207}{73275}MATSUDA Ryuhei
{73279}{73348}CHIHARA Koji
{73350}{73420}ONlMARU
{73422}{73493}ITAO Itsuji
{73494}{73564}KEE
{73567}{73636}Mame YAMADA
{73639}{73708}SUZUKl Takuji
{73712}{73782}DAIRAKU Genta
{73786}{73881}{Y:i}You slip inside a space turned to ash,
{73941}{74041}{Y:i}don't care sending needles off their charts.
{74106}{74232}{Y:i}Heading back, only you miss the sign,
{74274}{74389}{Y:i}distressed by impossible meanings.
{74447}{74558}{Y:i}Melancholy bends your head.
{74614}{74732}{Y:i}How often did you bang|my rear window in panic?
{74781}{74912}{Y:i}The drifting riot tears you apart.
{74947}{75076}{Y:i}Your suspended heartbeat engulfed|by the dark.
{75107}{75209}{Y:i}Turning to ash, you reach out,
{75273}{75368}{Y:i}snatching, worn down by the routine.
{75438}{75557}{Y:i}Your nerves always on edge,
{75604}{75728}{Y:i}twisting in space turned to ash.
{75777}{75886}{Y:i}Melancholy bends your mind.
{75945}{76054}{Y:i}How often did you bang|my rear window in panic?
{76111}{76241}{Y:i}The drifting riot tears you apart.
{76278}{76342}{Y:i}Your suspended heartbeat engulfed|by the dark.
{76350}{76424}Written and directed by|TOYODA Toshiaki
{76450}{76600}Pøeloil Tadi|www.cesketitulky.com