{1}{1}23.976|Nine.Souls.2003.DVDRip.XviD-WRD
{96}{189}Eiso Gekijo Co Ltd, Film-Makers lnc.
{3495}{3549}Hej, Noburu, vstávej.
{3566}{3607}Já vím. Buï zticha.
{3611}{3700}Coe? Jak se opovauješ øíkat |svému otci, e má bıt zticha?
{3703}{3738}
{3741}{3793}Nech mì bıt!
{3827}{3925}Nezlobím se na tebe,|protoe jsi mi vzal peníze.
{3942}{4014}Ale pøíštì, kdy je budeš |potøebovat, tak mi o nì øekni.
{4017}{4081}Dej mi je na úèet,|jako Michiruovi.
{4083}{4124}Nemluv o svém bratrovi.
{4131}{4209}Proè? Deset let prakticky nevyšel z domu.
{4213}{4253}Tvùj bratr je nemocnı.
{4267}{4347}Potom je tvou rodièovskou |povinností ho léèit.
{4374}{4427}Nejde ho vyléèit!
{4431}{4505}Pouíváš ho jako záminku |pro hádky s mámou.
{4513}{4600}"Podívej, co se stalo tvému |synovi, kdy jsi nás opustila.."
{4608}{4654}Není to správnı.
{4654}{4729}Coe?|Ty spratku!
{4741}{4815}Do toho ti nic není!
{4818}{4879}Dej mi to, o cos obral chudáky!
{4885}{4978}Postavím pro Michirua novou školu, |do které by mohl chodit!
{4981}{5051}Myslíš, e tì budu poøád ivit?
{5059}{5140}Pøijï mi nìco vyèítat,|a budeš vydìlávat!
{5594}{5689}Nestìuj si.|Tohle je nejprázdnìjší cela.
{5710}{5775}A je nás deset.
{5810}{5863}Postarej se o nìj, Yamamoto.
{5892}{5957}Jasnì, nechte to na mnì.
{6111}{6215}Mìl bys to pøestat všechno dret |v sobì, nebo to tady nevydríš.
{6245}{6280}Máš pøed sebou dlouhej odpoèinek.
{6294}{6391}Prostì si den ij vlastním tempem.
{6420}{6450}Támhle je tvá matrace.
{7328}{7371}Dobrou chu.
{7374}{7417}Dobrou chu.
{8150}{8225}Radši umøu ne tady zùstat.
{8564}{8601}Odkud jsou ty chlupy?
{8930}{8973}Z prdele...
{8996}{9023}prdele.
{9086}{9146}ijeme v prdeli vesmíru,
{9227}{9356}co z nás všech dìlá |hovna v ucpané prdeli.
{9406}{9486}A stráe jsou pak projímadlo.
{9596}{9645}Hej, ucpanı hovna!
{9698}{9742}Pouzdro, pouzdro!
{9746}{9772}Nezapomeòte!
{9787}{9863}Pouzdro je v základní škole u hory Fuji!
{9886}{9923}Pohnìte si nebo ho spláchnou,
{9944}{9973}vy sraèky!
{10310}{10329}Sraèky!
{10402}{10435}Musím na záchod.
{10458}{10521}Jdeš srát, hovado?
{10524}{10617}Já jsem pan Yamamoto, Král podvodníkù!
{10620}{10657}Nezahrávej si se mnou!
{10706}{10791}Kreténi!|Projímadla!
{10800}{10931}Spláchnìte to, kurva!|Prosím, spláchnìte to!
{10950}{11054}Vykliïte celu 13.
{11078}{11156}Smrdí to, vy hajzlové, smrdí to!
{11198}{11301}{Y:i}Jasnì, e to bude sranda,|já vìdìl, e to bude sranda.
{11303}{11417}{Y:i}Tenhle sen, tamten sen,|všude samı sen."
{11426}{11533}{Y:i}Má kouzelná kapsièka|mi je všechny splní,
{11535}{11685}{Y:i}všechny moje sny,|všechny mi je splní.
{11704}{11819}{Y:i}Jak moc bych si pøál|létat v oblacích...
{12445}{12482}Tady je díra.
{16450}{16557}Torakichi - 10 let|Zabil vlastního syna
{16824}{16941}Kazuma - 18 let|Legendární násilnı motorkáø
{17034}{17141}Shishido - 11 let|Rozenı delikvent
{17336}{17445}Saruwatari - 10 let|Dealer drog na americké námoøní základnì
{17543}{17652}Shiratori - 20 let|Mistr na útìky
{17723}{17830}Kamei - 12 let|Pornokrál
{17891}{17998}Ushiyama - 14 let|Nebezpeènı ivel
{18058}{18164}Inui - 15 let|Specialista na vıbušniny
{18262}{18368}Kaneko - 13 let|Otcovrah
{18654}{18860}DEVÌT DUŠÍ
{19258}{19380}Hej, co to je?|Kurva!
{19550}{19599}Dus, dus.
{19610}{19644}Vodu.
{19646}{19683}Èaj.
{19686}{19710}Cokoliv studenıho.
{19770}{19797}Dus.
{19814}{19837}Mince.
{19952}{19973}Já to zvednu.
{20032}{20067}Našel jsem 10 jenù!
{20086}{20129}Já 50 jenù!
{20149}{20214}Hele, kolik teï stojí dus?
{20228}{20245}100 jenù?
{20249}{20322}100 jenù?|Take nám chybí ještì 20!
{20325}{20361}Blbe, chybí 50 jenù.
{20374}{20401}Najdeme je.
{20700}{20794}Z kadıho vìzení jde nìjak utéct.
{20804}{20863}Èlovìk má 9 dìr.
{20909}{20956}A ena ještì jednu navíc.
{21305}{21339}Budem stopovat?
{21402}{21478}Ty bys svezl devìt parchantù |ve vìzeòskejch uniformách...
{21481}{21541}...uprostøed noci?
{21686}{21734}ádní duchové, ádní duchové, |ádní duchové.
{21754}{21812}ádní duchové...
{21854}{21927}...padlıch váleèníkù støedovìku se neobjeví.
{22006}{22089}ádní duchové, ádní duchové, |ádní duchové.
{22112}{22317}ádní duchové, ádní duchové, |ádní duchové.
{22414}{22438}Duchové!!
{22488}{22522}Neslyším vás!
{22661}{22717}Postoj!|Narovnejte záda!
{22753}{22807}Jak dlouho u trénujete?
{22817}{22912}Dost dlouho, aby vám oholenı|oboèí dorostlo zpátky?
{22928}{23021}No, to je u kadıho rùznı.
{23023}{23089}U mì to je u 12 nebo 13 let.
{23154}{23288}To je kurevsky dlouhá doba.|Zvládáte to tam vzadu?
{23299}{23361}Jsou v pohodì.|Dal jsem jim poøádnì zabrat.
{23448}{23500}Èéèe, to je super!
{23520}{23588}S váma devíti bude vyhození |toho bordelu hned hotovı.
{23618}{23666}Dneska mám šastnej den.
{23683}{23721}Dost šastnej!
{23723}{23775}Dost, dost šastnej!
{23922}{24025}Dost, dost, dost, dost!
{24098}{24197}Nezkoušej na mì ty svı "dost tohle a|dost, dost, dost tamto" sraèky, hajzle!
{24210}{24235}Nesnáším takovı vatlání.
{24238}{24299}Nikdy vám to nezapomenu, vy svinì!
{24313}{24401}Za tohle vás dostanu!
{24432}{24481}Nemluv neslušnì!
{24498}{24533}A trochu úcty!
{24674}{24706}Bìte nìkdo øídit.
{24752}{24773}Hej!
{24778}{24797}Mám jít?
{24799}{24825}Ty ne.
{24842}{24899}No, já nemám øidièák.
{24922}{24975}Ani já.
{24990}{25039}Banda uboákù.
{25039}{25089}Ty bì.|Ty umíš øídit.
{25092}{25128}U neøídím.
{25145}{25191}A to má znamenat co?
{25193}{25221}Co to znamená?
{25227}{25313}Vyserte se na to!|Prostì se smiø s tím,
{25316}{25385}e tady nikdo jinej neøídí.
{25387}{25454}Èas zase s tím zaèít, Torakichi.
{25522}{25591}Nepovyšuj se.|Nejsme pøátelé!
{25608}{25702}Dobrı plot dìlá dobrı sousedy.|Chce to trošku respektu.
{26272}{26326}Je tady docela dost místa.
{27872}{27961}Mají moc pìknı oèi..
{27964}{28061}Ovce jsou super.|Pìknı a mìkkı.
{28226}{28271}Rozšoupneme se!
{28812}{28853}Teï je jí líp!
{28872}{28908}Nadzvedni jí prdel!
{28951}{29031}Hej, trosko!|Pomoz mi!
{29117}{29172}Ta je pìkná.
{29232}{29280}Tref se do správné díry!
{29288}{29339}Nemùu nìco chytnout?
{29375}{29421}Hele, to je samec.
{29442}{29468}To máš jedno.
{29545}{29641}Máte zpodìní, máte smùlu!|Zabednìnci!
{29690}{29753}Poèkejte, omlouváme se!
{29781}{29877}Prosím poèkejte!|Omlouváme se!
{29993}{30042}U nikdy nepøijdeme pozdì!
{30067}{30112}Proè jste tak nasraní?
{30395}{30480}Pane Nakayamo!|Dodávka!
{30534}{30581}Vydrte chvilku.
{30693}{30708}Zdravíèko!
{30737}{30760}Jak je?
{31038}{31073}Ty nevdìèníku!
{31094}{31147}Prosím, ne tak nahlas.
{31150}{31201}Zrovna jsem se oenil.
{31214}{31299}Jsi ještì v podmínce, e?
{31312}{31387}A ty máš poøád bejt za møíema, ne?
{31390}{31412}Co se stalo?
{31421}{31489}Jsem omluvenej...|Bùh mì omluvil...
{31492}{31543}...a øekl mi, abych zašel za Nakayamou.
{31557}{31608}Nech toho!
{31610}{31669}Ushiyamo, Ushiyamo!
{31754}{31869}Hej rup, hej rup...
{32618}{32671}Moje ena, Maria.
{32730}{32768}Dìkujeme vám, za vaši pohostinnost.
{32811}{32920}Tohle jsou staøí známí... rùzní...
{32974}{33036}Madam, nemáte v domì nìjaké jídlo?
{33055}{33089}Nemáte prachy?
{33090}{33137}Bìte si ho koupit sami!
{33188}{33234}To je filipínská koèka?
{33353}{33418}Jídlo pro devìt...
{33439}{33529}Mìli jsme dneska jít tanèit.
{33534}{33564}Lháøi!
{33916}{33982}Základní škola u hory Fuji,|základní škola u hory Fuji...
{33986}{34068}Našel jsem to, tady to je.
{34072}{34106}Tady jsou ty prachy.
{34110}{34209}Take je to poøád dál |po silnici èíslo 135.
{34224}{34265}Jasnı!
{34333}{34473}Co kurva mùe dìlat?|Zmìnila si èíslo?
{34505}{34585}Zvedni ten telefon, sakra!
{34663}{34705}Má nìkoho?
{34770}{34833}Ještì to minutu máèej.
{34888}{34941}Co tøeba "dìkuju"?
{35083}{35136}Nemusel jsi s náma chodit, |kdy na to nemáš.
{35258}{35293}Víc piva prosím, paní.
{35295}{35344}Zaplate, vy hajzlové!
{35373}{35401}Pìknì studené, prosím.
{35424}{35496}Došel vám záchodovej papír, madam.
{35508}{35549}Jez!
{35900}{35925}Proboha. Co to má...!
{36058}{36144}Fakt vám došel záchodovej papír, madam.
{36167}{36209}Pus mì!
{36220}{36271}Nech mì bıt!
{36274}{36317}Máte nìjakı nebo ne, madam?
{36325}{36471}Nedá se øíct, co se stane dál..
{36474}{36541}Co to dìláš, chlapèe?|Chce se ti chcát?
{36554}{36615}Muské sbliování zaèíná tím, |e se spolu vychèí.
{36627}{36685}Je èas jít chcát vestoje.
{36718}{36761}Ten nikdy nebude mít kamarády.
{36879}{36903}Co to dìláš?
{36906}{36939}U toho mám dost.
{36942}{36969}Nezùstanou napoøád.
{36972}{37006}To je mi jedno.
{37010}{37033}Prosím!
{37050}{37079}Zítra odejdou.
{37111}{37148}Marie!
{37164}{37187}Ty zvíøe!
{37207}{37234}Co to dìláš?
{37240}{37317}Kam to jdeš?
{37319}{37345}To staèilo.
{37367}{37398}Jsem unavená.
{37414}{37434}Nech mì bıt!
{37450}{37498}Máš kamarády.
{37523}{37553}Já se vracím na Filipíny!
{37555}{37576}Poèkej!
{37578}{37601}Sbohem!
{37615}{37637}Uívej si tady!
{38240}{38336}SASTNÁ DÍRA
{38948}{39020}Nech u tìch vìzeòskıch rozcvièek.
{39060}{39130}Necítím se dobøe, dokud je neudìlám.
{39133}{39149}Lezeš mi na nervy!
{39154}{39217}Vypadáte dobøe v novejch ohozech.
{39234}{39261}To urèitì.
{39450}{39498}Díky.
{39506}{39541}Opravil jsem vám dodávku.
{39545}{39594}Díky, díky.
{39599}{39694}Torakichi, nikdy neuteèete,|kdy budete spolu.
{39706}{39822}Kadej nìkam jdeme...
{39865}{39907}Tady je obìd...
{39950}{39980}...pro mladší.
{39983}{40025}Díky, díky.
{40039}{40110}Torakichi, co je tohle?
{40114}{40130}Nic.
{40134}{40165}To není nic.
{40168}{40230}Netrap se tím.
{40241}{40275}Ale to je mùj oblek.
{40279}{40305}Tak mi ho dej.
{40308}{40330}Ne, to nemùu.
{40333}{40415}Mám ho mít na sobì |na svatebních fotkách s Marií.
{40418}{40477}Vdy odjela na Filipíny.
{40482}{40513}Vrátí se.
{40517}{40584}Nemá ráda tvoje kamarády, |dej jí kopaèky!
{40587}{40662}Torakichi, je to mùj jedinej oblek.
{40666}{40715}Ushiyamo, Ushiyamo!
{40754}{40804}Vyøiï to.
{40842}{40912}Torakichi, hej, Torakichi.
{41128}{41205}Šílím hlady.|Èas na trochu rıe.
{41228}{41263}Poèkej, já chci taky.
{41322}{41379}Co to dìláš?
{41391}{41487}Ten chlápek vyvradil všechny |svı zamìstnance otrávenejma koláèema.
{41509}{41614}Øíkal, e je radši zabije, |ne aby je vyhodil.
{41630}{41731}Je to fakt dobrej chlápek, |jen trošku zmatenej.
{41745}{41778}Vyblij to.
{41789}{41816}Ty jsi to jedl?
{42059}{42088}Synu,
{42109}{42213}musíme najít novou mámu.
{42720}{42779}Máš dost tmavı chcanky.
{42807}{42891}Daroval jsem jednu ledvinu, dívce.
{42899}{42926}Kvùli penìzùm?
{43018}{43045}Z lásky.
{43068}{43101}Z lásky, jo?
{43337}{43371}Vyšlo to.
{43413}{43475}Èas na svaèinu.
{43534}{43576}Dáme si všichni.
{43682}{43705}Svaèina...
{43921}{44001}Bùh vás potrestá...|Jsou to obìti...
{44009}{44065}Peníze, které lidé darovali...
{44094}{44174}Víte, co se stane, |kdy vás bùh potrestá?
{44286}{44357}Hej, hej, hej!
{44792}{44901}To ne, fakt to ne!|No tak, to ne.
{44912}{45049}Prosím, to ne.|Loupe není dobrá.
{45052}{45141}Skonèíte zase ve vìzení, |kdy to udìláte.
{45146}{45235}Au, to ne, prosím,|musíte toho nechat.
{45243}{45297}ádné násilí, ádné násilí.
{45418}{45460}Øíkal jsem, ádné násilí.
{45832}{45879}Hajzlové!
{45998}{46085}Sakra!|To je posedmı, co mì okradli!
{46310}{46377}Všechno, co nám teï chybí...
{46380}{46501}...je obsah skrıše Krále podvodníkù|a pak je èas na...
{46522}{46645}A pak na...
{46647}{46723}Blbe, je to takhle...
{46733}{46759}...a takhle...
{46778}{46810}Co je to?
{46813}{46906}Pøekøííš holce stehna a pøímo tady...
{46908}{47021}Hele, to je nechutnı!|Nechutnı!
{47162}{47223}Necítíte nìco?
{47245}{47311}Devìt chlapù v malé dodávce, |jasnì, e je tady smrad.
{47327}{47365}Tvùj prst smrdí.
{47501}{47568}Myslíte, e ty prachy tam fakt jsou?
{47577}{47639}Øíkal, e hodnota falešnejch |bankovek, co udìlal...
{47641}{47700}..je vìtší ne hodnota|všech penìz na svìtì.
{47703}{47775}Nevypadal moc zazobanì.
{47782}{47848}Ale jo.|Mìl jsem z toho dobrej pocit, pocit...
{47854}{47909}Vsadím se, e tam jsou.
{47938}{48059}Od svejch ètrnácti let byl mimo vìzení |13 mìsícù, ale má z toho dobrej pocit...
{48062}{48127}To, co cejtíš, není péro.
{48136}{48234}Hele, tys našel enskou, jak tì |podvádí a zabil jsi toho chlápka,
{48238}{48281}...a jí jsi nic neudìlal?
{48306}{48355}Poøádnej chlap by tu kurvu |zabil taky, nemyslíš?
{48403}{48508}Tenhle schoval svou holku do auta a|poslal je v zátoce ke dnu.
{48514}{48553}Tomu øíkám chlap.
{48559}{48689}Kisara poøád ije. |Je naivu.
{48702}{48811}Vìø mi, e ije...|Nìkdy ti ji pùjèím na sex po telefonu.
{48814}{48857}Jasnı? Sex po telefonu.
{48901}{48998}Kde, kde, kde?|Tady?
{49045}{49122}Kamei je hodnı, |nikdy by enì neublíil.
{49126}{49198}Zaruèil bych se za jeho dobrotu.
{49232}{49304}Netouím po hlasu od zlodìje, |kterej o enskejch ví hovno.
{49330}{49361}To jsem já.
{49392}{49487}On je odborník na bomby, |kterej špehoval nìjakou hezkou holku.
{49490}{49513}Neøíkej jim to.
{49517}{49600}Zamiloval se do holky |od automatù, vzal bombu...
{49605}{49663}..."Já to zapálím!"
{49667}{49696}Neøíkej to.
{49706}{49752}To je zloèin, kterej se zapíše do historie.
{49754}{49792}Øíkal jsem ti, abys byl zticha.
{49796}{49832}Ten, co útoèí na paèinka!
{49837}{49922}Neøíkej jim to, neøíkej...
{49938}{49987}Opravdu to smrdí...
{49995}{50062}...a zhoršuje se to.
{50112}{50163}To smrdí jeho prst.
{50206}{50250}Smrdí leda tak tvùj nos.
{50275}{50305}Cos to øíkal...?
{50340}{50401}Nechte toho.
{50478}{50502}Nechte toho!
{50767}{50839}Èervené vozidlo, zastavte.
{50974}{51078}Drte klapaèky, debilové!
{51108}{51156}Pøidejte, vy kokoti.
{51160}{51186}Zastavte.
{52060}{52091}Bì první.
{52102}{52128}Ne, ne.
{52169}{52215}Øíká ti nìco úcta ke starším?
{52218}{52303}Však o to jde, pitomèe.
{52437}{52460}Tak potom...
{52541}{52599}Michiru, Michiru, bì první.
{52612}{52694}Jsi nejmladší, tak jsi na øadì.
{53018}{53049}Vítejte.
{53087}{53124}Bì dovnitø.
{53182}{53253}Dìkuji.
{53362}{53434}Myslím, e se najím pozdìji.
{53554}{53627}Promiòte, dal bych si ještì èaj.
{53790}{53831}Omlouvám se za zpodìní.
{54024}{54088}Ta je fakt moc pìkná...
{54287}{54368}Sleduj, transvestiti!|Tlusoch!
{54398}{54505}Ti chlápci jsou transvestiti!|Hej, skrèku!
{54650}{54705}Hele, tenhle se otoèil.
{55311}{55358}Hej, hej, hej, co je?
{55363}{55504}Raz, dva, tøi, ètyøi, pìt, šest,|sedm, osm set... tøicet.
{55674}{55709}Poèkat...
{55711}{55773}Chybí vám 20 jenù.
{55786}{55868}To je mi líto, odpuste nám.
{55881}{55979}Ne, ne. Ne, nemùete jíst jídlo, |za které pak nezaplatíte.
{55988}{56084}Dìcka si dnes myslí, e jim |všechno projde, kdy se pak ukloní.
{56087}{56136}Nesnáším ten pøístup.|Poslouchej...
{56138}{56205}...nezahrávej si se mnou.
{56218}{56333}Já vím, e jsi ve skuteènosti mu.
{56372}{56482}A kdo tvrdil, e bych mìl bejt enská?|To nikdo neøek.
{56482}{56542}Jsem chlap, máš s tím problém?
{56555}{56580}Ne, vlastnì ne.
{56583}{56632}Tak co tady meleš o 20 jenech?
{56634}{56700}Kdybyste byl ena, odpustil bych |vám to, ale chlapovi nemùu.
{56702}{56804}Vdy se ti omlouvám, |e je nemám, kreténe.
{57197}{57267}Nazdar Torako, jak se má starej?
{57318}{57373}Narvu ti horkej pepø do krku.
{57418}{57494}Pøestaòte posedávat a |rát jídlo zadara.
{57706}{57753}Hele, ty nìkam jdeš?
{57812}{57843}Kam to jdeš?
{58074}{58093}Vítejte.
{58095}{58153}Porno, cha, u je to dávno.
{58451}{58494}Dìlej, jeï, jeï!
{58542}{58670}Poèkat, poèkat!|Hej, hej!!
{58838}{58918}Pøidej, pøidej..
{58921}{58975}Ujedeme ti.
{58982}{59141}Poèkejte, prosím, poèkejte.
{59195}{59275}Opozdilcùm nepromíjím.|Nepromíjím..
{59349}{59386}Pøidej.
{59420}{59469}Pøidej trochu.
{59512}{59591}Blbe, jsi pomalej.
{59614}{59766}Honem, honem, pejsku.
{60381}{60409}Zastav prosím!
{61249}{61273}Co se dìje?
{61351}{61376}Jsi OK?
{61476}{61539}Kamei, tady.
{61592}{61737}Nadrenı panny.
{61810}{61871}Ty jsi hrál v "Nadrenejch pannách"?
{61906}{61943}Nadrenı panny.
{62088}{62115}Omlouvám se.
{62180}{62285}Bıval jsem doktor.
{62403}{62519}Za co vás zavøeli, pane Shiratori?
{62657}{62723}Napomáhání sebevradì.
{62742}{62957}Pro nìkteré lidi je sebevrada jedinım |vıchodiskem a záchranou z našeho svìta.
{63000}{63113}Nemohl jsem je odmítnout.
{64214}{64243}Chcípni!
{64319}{64373}Ty spratku jeden zasranej!
{64398}{64428}Chcípni!
{64528}{64605}Sere mì, e jsi ještì naivu!
{64876}{64905}Neperte se, prosím.
{64998}{65026}Co to...?
{65381}{65417}Všechny vás zabiju.
{65628}{65652}Zabiju tì!
{65746}{65781}Nechte toho.
{65855}{65899}Ushiyamo, chytni mu hùl.
{66622}{66647}Zabiju tì!
{66788}{66822}Sledujte...
{66827}{66846}Co je to?
{68063}{68112}Šastná díra.
{68162}{68215}U je to dobrı, ano?
{68574}{68609}Vítejte.
{68611}{68657}Kurva, to je on.
{68658}{68702}Spousta holek..
{68706}{68771}Nabízíme spoustu slev.|Jen pojïte dál.
{68795}{68921}Vstupte, spousta havıch koèek.
{69618}{69683}{Y:i}Ty jsi vdycky...
{69725}{69789}{Y:i}...tak strašnì flirtoval...
{69826}{69894}{Y:i}Nechával mì v nejistotì...
{69938}{70011}{Y:i}...e jsem jen tvùj klaun.
{70038}{70233}{Y:i}Teï u sbohem, ty se eníš...
{70266}{70444}{Y:i}...u nikdy na mì nepomyslíš..
{70478}{70546}{Y:i}Vdycky jsi byl...
{70589}{70654}{Y:i}...byl jsi tady...
{70690}{70758}{Y:i}...byl jsi tady se mnou....
{70803}{70873}{Y:i}...musela jsem dávat pozor.
{70907}{71088}{Y:i}Teï u sbohem, u jsem sama...
{71125}{71313}{Y:i}Nemìj strach, u jsem v pohodì...
{71627}{71693}{Y:i}...i kdy jsi vdycky...
{71737}{71801}{Y:i}...byl tak fajn.
{71835}{71906}{Y:i}Vra se, jestli zatouíš...
{71950}{72014}{Y:i}...po mé náruèi, i kdy to není moc.
{72050}{72258}{Y:i}Teï u sbohem, u zapadá slunce,
{72277}{72467}{Y:i}...nevìøím, e budeš plakat.
{72493}{72521}Yarino!
{72714}{72816}Moje ledvina...|...funguje?
{72865}{72895}Pane doktore?
{72945}{72981}Pane doktore Shiratori?
{73113}{73177}Je moje ledvina zdravá?
{73242}{73299}Ano, je v poøádku.
{73411}{73438}Dìkuji.
{73522}{73555}Doktore...
{73580}{73682}...kadı den jsem se modlila |za to, abyste nìkdy pøišel.
{73792}{73836}Touila jsem vás znovu vidìt.
{75249}{75301}Shiratori tady zùstává.
{75304}{75403}Opravdu?|Mistr únikù nás opouští.
{75538}{75607}To je fakt super.
{75826}{75874}Ty a ty, bìte domù.
{76030}{76140}Já nejsem opilej,|nejsem opilej.
{76142}{76188}Já taky ne.
{76241}{76342}To je ten, co nosí enskı šaty.
{76373}{76421}Je tak povıšenej.
{76424}{76501}Co je tak úasnıho na tom, |e èlovìk nìkoho zabil?
{76502}{76603}Tys nìkoho zabil, e jo?|Ale jsi tak nafoukanej.
{76605}{76688}Pìknì mì to sere.
{76793}{76897}Pøedstavím ti uprchlı vìznì!
{76934}{76965}Dìlám si srandu!
{77015}{77033}Dìlám si srandu...
{77037}{77072}Srandu si dìlám.
{77170}{77193}Kreténe jeden.
{77281}{77355}Dobrou noc.|Pøijïte zase.
{77424}{77520}Michiru, Michiru, UFO.
{77607}{77714}Pane, máte ušpinìnou bundu.
{77900}{77948}Take tady je škola pod horou Fuji?
{78002}{78030}Prachy, prachy.
{78052}{78088}Myslíš, e tam fakt jsou?
{78153}{78210}A nahoru... Koneènì jsme tady.
{79037}{79097}Král podvodníkù pan Yamamoto, ano?
{79128}{79161}Pøesnì tak.
{79163}{79204}Èasová kapsle hora Fuji
{79218}{79252}Klíè k budoucnosti
{79254}{79311}Pan Yamamoto.
{79350}{79377}Mám to.
{79397}{79433}Fakt?
{79465}{79539}Kolik?
{79553}{79577}Mapa?
{79595}{79635}Je to malı.
{79678}{79710}Co se tam píše?
{79759}{79857}"Klíè k budoucnosti, |kterı otevøe všechny dveøe.."
{79886}{79909}To je všechno.
{79938}{80005}To je všechno?
{80018}{80113}- ádná mapa nebo nìco?|- To není sranda.
{80170}{80241}- Jen tohle.|- Co to má znamenat?
{80245}{80289}Do prdele!
{80352}{80433}Taková škoda.
{80488}{80508}Hej...
{80540}{80568}Drsòáku.
{80610}{80632}Je tvùj.
{82969}{83046}Ten mrak vypadá jako duch.
{83094}{83133}A teï pulec, e?
{83154}{83215}Na tom nìco bude.
{83262}{83312}Pulèí dvojèata.
{83379}{83407}Máš pravdu.
{83498}{83541}Vsadím se, e z nich budou áby.
{83586}{83619}To urèitì ne.
{83765}{83821}Máš pravdu, áby!
{83881}{83922}Ètyølístek.
{83967}{83996}Taky jeden najdu.
{84109}{84144}Mám další.
{84310}{84349}A tøetí.
{84582}{84644}Taky na mì jedna èeká.
{84660}{84718}Mùe se èlovìk na útìku oenit?
{84735}{84760}Mizím.
{84858}{84908}Coe? Ty odcházíš?
{84921}{84953}Zatím.
{85629}{85719}Obèas vídá duchy...
{85771}{85828}Asi ty duchy potøebuje.
{85865}{85951}Kadı máme alespoò jednu |vìc, kterou potøebujeme.
{86044}{86079}Jak to myslíš?
{86218}{86396}Ushiyama strávil v nápravném ústavu |nìkolik let za vradu 10 spoluákù...
{86401}{86532}...a zavradil starší pár, |kdy vykrádal èistírnu.
{86534}{86589}Jde o surového zloèince.
{86601}{86708}Pùsobí velice laskavì, ale kdy je |vyprovokován, stává se z nìj divoké zvíøe.
{86717}{86802}Je èas zvíøe zavøít do klece.
{86817}{86847}Další...
{86870}{86993}Jeden z devíti uprchlíkù, Kaneko Michiru, |zøejmì ubodal svého otce k smrti...
{86995}{87049}...rozètvrtil jej a snìdl.
{87053}{87177}Alespoò ho nerozemlel do hamburgeru...
{87214}{87276}Omlouvám se, jestli jsem |vám tím znepøíjemnil jídlo.
{87284}{87410}Hasegawa Torakichi, kterı je také |na útìku, pøejel svého syna,
{87413}{87452}...kterı odmítal jít do školy.
{87455}{87517}To je další hroznı èin.
{87521}{87592}Syn byl slabší ne lívanec.
{87613}{87645}Podivná dvojka.
{87695}{87791}Kuruma Kazuma, èlen nechvalnì |proslulého motorkáøského gangu...
{87793}{87881}...zavradil 4 èleny tohoto gangu.
{87903}{87974}Jde o bezcitného a nelítostného jedince.
{87977}{88018}Vodu?
{88138}{88225}Další z uprchlíkù, jeho temnou stránku |chceme v našem poøadu pøedstavit...
{88229}{88325}...se jmenuje Inui Shinichi, "šílenı atentátník".
{88331}{88443}Dìkujeme za jídlo.|U je èas jít, pánové.
{88465}{88490}Dávají zvláštní program.
{88525}{88583}Promiòte, zaplatíme!
{88843}{88877}Dìkuji vám.
{88980}{89023}To je koèka.
{89042}{89150}U zase...|Jak dlouho jsi nemìl enskou?
{89197}{89235}Asi 5 let.
{89265}{89333}Mysli na to, v jaké jsi pozici.
{89410}{89474}Oenit se s dívkou, kterou miluju...
{89508}{89567}...otevøít si na venkovì bufet...
{89592}{89689}...a mít dùvìru okolí.|To je mùj sen.
{89918}{89946}Bì zaplatit.
{89995}{90044}Jakı je tvùj sen?
{90061}{90092}Nemám sny.
{90356}{90447}Celkem to dìlá 6,900 jenù.
{90566}{90628}Ehm, rád bych pracoval.
{90805}{90838}Pracoval tady.
{91097}{91184}Hej, televize nefunguje.
{91187}{91241}Ty nùky nechám tady.
{91315}{91403}Vítejte.
{91524}{91571}Objednávka na dvì kávy, prosím.
{91574}{91601}Ichiro, poèkejte.
{91603}{91647}Ano, co se dìje?
{91670}{91701}Tady máte jmenovku.
{91805}{91905}Suzuki Ichiro je jméno, které se |opravdu snadno zapamatuje.
{91918}{91965}Taky se mi líbí.
{92046}{92125}Pøísahala bych, e u jsem |vás nìkde vidìla.
{92133}{92177}Jsem si jistá.
{92192}{92278}Asi v televizi.|Nebyl jste na olympiádì?
{92283}{92323}Poøad o vaøení, e?
{92331}{92461}Ne, prostì mám jen |obyèejnou, obvyklou tváø.
{92738}{92865}Ty kombinézy nosila skupina z pøedmìstí.
{92868}{92967}Jejich vùdce, Nakayama, nosil pøímo tuhle.
{92987}{93055}Jsou skvìlı. Mají opravdu hodnotu.
{93070}{93224}No tak, chlapi, vám se nelíbí?|Zkuste si je.
{93229}{93387}Budete v nich vypadat skvìle, je to jedna velikost, |která padne všem a ještì vám pøidám tohle.
{93407}{93507}Jako bonus.
{93586}{93609}Promiòte.
{93612}{93648}Potøeboval bych oddací list.
{93899}{93923}Ještì jeden, prosím.
