{2350}{2378}Princezno... podívejte.
{2428}{2594}Vítìz dostane nejsilnìjší zdroj energie v celé zemi. \NS tímto pírkem nikdy neprohrajete.
{2633}{2764}Take, všichni závodníci co jste tam venku, vstupte do našeho Dragonfly závodu...
{2764}{2814}a vyhrajte pírko.
{3408}{3436}Nebojte se.
{3454}{3467}Podívejte.
{3861}{3870}Princezno.
{3892}{3920}Splnil jsem svùj slib.
{4092}{4134}Vedl sis dobøe.
{4455}{4471}Co se dìje?
{4493}{4509}Ten kdo za tím stojí...
{4565}{4586}je nìkdo z nich.
{4595}{4663}Tøi mince
{4684}{4727}A máme zde nejnovìjší informaci z Dragonfly závodu.
{4740}{4900}Dnešní losování o pole position pøenášíme ivì.
{4913}{5004}Dobrá, a teï obrame všichni svou pozornost k našim soutìícím.
{5159}{5245}Kdo si asi vylosuje nejlepší startovací pozici?
{5251}{5299}Vše je pøipraveno? Tak jdeme na to.
{5341}{5414}Take nìkdo z nich se pokusil sabotovat závod?
{5450}{5543}Jsem si jistı, e jim jde o pírko Sakury.
{5568}{5621}Uh, a máme zde první vylosované èíslo!
{5632}{5781}Wing Egg doslovnì znamená Okøídlené vejce
{5632}{5781}Naše sexy Sakura, závodící na vznášedle Wing Egg, si vylosovala nejlepší startovací pozici pro hlavní závod.
{5781}{5837}Sakura má na takové vìci štìstí, viïte?
{5892}{5917}Hned to vylosovala.
{5929}{6030}Neoplıvá Sakura náhodou nìjakou tajemnou silou?
{6040}{6047}Ano.
{6233}{6372}Pro všechny, kteøí se dnes kvalifikovaly do hlavního závodu jsem pøipravila malé pohoštìní.
{6403}{6486}Doufám, e se budete všichni bìhem dnešního veèera dobøe bavit.
{6508}{6583}A zároveò, pøeji všem hodnì štìstí v zítøejším závodì.
{6610}{6631}Na zdraví.
{6701}{6735}To je Mokony oblíbené jídlo.
{7068}{7157}Hej kámo, proè na mì celej den zíráš?
{7330}{7389}No... zaèínáš se mi líbit.
{7492}{7513}Nikdy se nevzdávej.
{7537}{7591}Pøipomínáš mi nìkoho, kdo ti je hodnì podobnı.
{7685}{7712}Tak nezírej.
{7722}{7784}A pøestaò mì oslovovat tím "kimi".
{7722}{7910}Pøípona kimi, se v japonštinì pouívá pro zdvoøilé, témìø a dívèí oslovování nìjaké osoby.
{7803}{7820}Promiò.
{7831}{7910}Jinak seš... celkem... fajn.
{7951}{7987}Jmenuju se Ryuuoh.
{8001}{8029}A ty seš?
{8060}{8082}Malé štìnì.
{8134}{8155}Coe?
{8168}{8188}To je moje pøezdívka.
{8203}{8262}Moje skuteèné jméno je Shaoran.
{8274}{8328}Mluvíš nìjak divnì.
{8378}{8411}Zaèínáš se mi líbit.
{8425}{8466}Rád tì poznávám, Malı štìnì.
{8481}{8493}Jasnì.
{9002}{9057}To cestování, nakonec zase tak špatné není, co?
{9074}{9164}Stejnì jako teï Shaorana, tak i nás zøejmì èekají podobná setkání.
{9187}{9301}Moná nás, ale i èekaj setkání s lidma, kterı se budou chovat úplnì opaènì.
{9378}{9472}Ano, jako tøeba, tihle chlapy...
{9488}{9499}Princezno...
{9515}{9527}zùstaòte tady!
{9609}{9633}Nechte to na mì!
{9920}{9973}Ty mu nepomùeš Kurosame?
{9985}{10004}A se stará.
{10725}{10768}Skvìle Shaorane.
{10824}{10857}To nebylo špatné.
{10890}{10912}Shouga.
{10964}{10998}Ty znáš mé jméno?
{11017}{11080}Neozbrojené lidi normálnì nenapadáme...
{11091}{11143}Nicménì, je to nezbytné k nalezení osoby, která za tím stojí...
{11181}{11215}Co ste k èertu zaè?
{11243}{11291}Jmenuji se Imonoyama Nokoru.
{11300}{11330}Takamura Suoh.
{11343}{11376}Ijuuin Akira.
{11385}{11413}Oh ano, vzpomínám si...
{11424}{11505}Dva z vás se kvalifikovaly do závodu...
{11524}{11577}Vy jste také byly pozváni na tento veèírek?
{11596}{11623}Ah, ano...
{11670}{11700}Pravdou je, e...
{11710}{11807}Oh, taková pøekrásná mladá sleèna, jsem si jistı, e s tím nemáte nic spoleèného.
{11911}{11954}Kdo doopravdy jste?
{12526}{12544}Vy jste...
{12560}{12634}Omlouvám se, za to nevlídné zacházení.
{12649}{12719}Vy jste ta osoba, která to všechno organizuje.
{12739}{12792}Mademoiselle Tomoyo je mùj dávnı pøítel.
{12804}{12837}Poádala nás o spolupráci.
{12851}{12897}V tomto mìstì udrujeme poøádek.
{12905}{12959}Já jsem vùdce Ochráncù.
{12976}{13053}Poádala mì, abych vás sem pøivedl.
{13066}{13150}Poprosila jsme je, aby vás sem pøivedli, chtìla bych vás toti poádat...
{13150}{13232}aby jste nám pomohli zjistit, kdo stojí za tím incidentem z kvalifikace.
{13249}{13300}Nìkdo se pokoušel ovlivnit závod...
{13317}{13328}Je to tak?
{13360}{13390}Dotklo se vás to?
{13458}{13549}Zjistili jsme, e bìhem závodu se ve vzduchu nacházelo toto.
{13564}{13623}Jsou to nanoroboti, lidskım okem jsou nepostøehnutelní.
{13638}{13696}Nic nedìlají, jen se pohybují vzduchem...
{13704}{13755}ale jsou schopni vést teplo.
{13787}{13871}Take, kdy se dostanou do mechanickıch èástí motoru vznášedel...
{13975}{14101}Den pøed závodem, jsme ve vzduchu nic nedetekovali.
{14116}{14270}Kdyby se uvolnili ze zemì, nebyly by schopni, vystoupat do tak velké nadmoøské vıšky.
{14285}{14438}Co znamená, e byli vypuštìní ze vznášedla, úèastnícího se závodu, take...
{14455}{14549}Take je jisté, e pachatelem je jeden ze závodníkù kvalifikace.
{14560}{14622}To je závìr, ke kterému jsem došla.
{14639}{14680}Také si to myslím.
{14708}{14845}Kdy jsme procházely registrace úèastníkù, \Nzjistili jsme, e jako jediní nemáte pøedchozí záznamy.
{14858}{14905}Proto vás ádám o pomoc.
{14923}{15012}Najala ste je aby nás napadli?
{15026}{15085}Take vaše nedùvìra u je pryè?
{15098}{15223}Ano! Hádám, e ten kdo to za tím stojí, bojuje špinavìji ne jak jste to pøedvedli vy.
{15287}{15362}Proto jsem taky øekl, e to neudìlala.
{15373}{15428}Jenom jsi se snail tu sleènu svést!
{15446}{15559}U jenom skuteènost, e na tomto svìtì existují eny, mì zalévá pocitem blaenosti.
{15633}{15780}Vyšetøovací tım naší spoleènosti, provìøuje všechny úèastníky závodu i osoby na nì napojené.
{15800}{15910}Nakonec toho èlovìka vypátrají a odhalí.
{15935}{16011}Take vás prosím, buïte bìhem závodu opatrní.
{16026}{16054}To nedává smysl.
{16111}{16230}Neøíkejte mi, e ste nás sem dotáhla jen proto, aby ste nám tohle øekla.
{16323}{16359}Nezatajujete nám nìco?
{16427}{16529}Dobøe, je tu ještì jedna vìc, na kterou se potøebuji zeptat.
{16598}{16655}Co máš na sobì bìhem závodu?
{16682}{16716}Tvoje vìci!
{16716}{16750}U jsi si nìjaké vybrala?
{16759}{16783}N-ne.
{16789}{16863}Potom mi tedy musíš dovolit, nìjaké ti vybrat.
{16881}{16959}Vím o nìèem, co je naprosto úasné a budeš v tom vypadat skvìle.
{16968}{17077}Moje hrdinka, v mıch vìcech, prohánìjící se oblohou.
{17092}{17122}To bude nìco neuvìøitelného.
{17133}{17178}Mokona chce taky.
{17204}{17235}Nechte to na mì.
{17247}{17283}Jsi si jistá?
{17300}{17331}To je v poøádku.
{17346}{17402}Jestli ti to sama navrhla, mìla by jsi to nosit Sakuro.
{17427}{17450}Sakuro.
{17488}{17573}Mohu ti øíkat Sakuro?
{17627}{17645}Samozøejmì.
{17658}{17727}Mohu ti øíkat Tomoyo?
{17738}{17779}Jistì, ovšem.
{17805}{17895}To je skvìlé, není nic lepšího, ne smìjící se dìvèata.
{17909}{17995}Úsmìvy všech en na tomto svìtì, \Nmì dostávají do stavu èisté blaenosti.
{18637}{18654}Co ty na to?
{18665}{18713}To je mùj Ryuuga.
{18728}{18774}Ten motor je ohromnı.
{18789}{18819}Trochu sem ho vyladil.
{18836}{18907}Chci ten závod opravdu vyhrát.
{18983}{19002}Co je tohle?
{19050}{19071}To neznáš?
{19085}{19135}To je EW senzor.
{19143}{19176}Pouívá se to pro odesílání a pøijímání rádiovıch vln.
{19188}{19306}Maj to všechny letadla, aby se pøedešlo problémùm s komunikací.
{19346}{19402}Ale kdy závodíš, tak to mùeš odstranit.
{19419}{19485}Znáš to, potøebuješ se zbavit nepotøebné zátìe.
{19508}{19558}Mohu si to pujèit?
{19603}{19627}Klidnì si to nech Štìnì.
{19647}{19666}Jsi si jistı?
{19680}{19703}Jasnì.
{19719}{19799}Ale nikdy sem neslyšel, e by to nìkdo bìhem závodu pouil.
{19815}{19856}Taky chceš vyhrát, e jo?
{19866}{19882}Jestli ano...
{19896}{19966}Nezajímá mì nic jiného, ne získání pírka.
{19977}{20020}Proto se snaíš vyhrát?
{20042}{20082}Pøestaò u s tìma blbostma.
{20242}{20352}Tsubasa Chronicle
{20506}{20540}Promiòte to zdrení.
{20630}{20678}Vypadáš skvìle Sakuro.
{20686}{20743}Tomoyo to udìlala celé sama!
{20757}{20789}Muselo to dát spoustu práce.
{20797}{20811}Vùbec ne.
{20821}{20885}Celou dobu jsem hledala osobu, na kterou bych nìco navrhla.
{20899}{20942}Jak ti to jen oplatím?
{20960}{21022}Dobøe, o nìèem bych vìdìla.
{21035}{21057}Co je to?
{21079}{21092}Keigo.
{21116}{21183}Øíkej mi od teï u jen Tomoyo.
{21195}{21313}Nechci aby jsi ke mì mluvila v Keigu Sakuro, bav se se mnou normálnì.
{21360}{21387}Skvìlé.
{21393}{21428}Ty, ale také Tomoyo.
{21440}{21522}Ale já nevím, jestli mohu.
{21529}{21554}Bude ti to tak vyhovovat?
{21560}{21582}A tobì?
{21582}{21593}Ano.
{21599}{21650}Jsem tak rád, za ty dvì.
{21658}{21718}A jak pokraèuje pátrání po tom bastardovy?
{21787}{21850}Bohuel, zatím jsme nic nového nezjistili.
{21867}{21916}Naøídila jsem, aby bìhem závodu panovala zvıšená bezpeènostní opatøení...
{21928}{21978}ale nemohu zaruèit, e se nic nestane.
{21997}{22029}Buïte prosím opatrní.
{22043}{22058}Ovšem.
{22069}{22136}Pokud vyhraju, je mi jedno, jestli se o nìco pokusí.
{22148}{22161}Pøesnì.
{22174}{22200}Dám do toho všechno.
{22216}{22233}Mokona taky.
{22244}{22298}Dobrá, pùjdeme tedy?
{22363}{22424}Èas Dragonfly závodu nadešel...
{22650}{22748}Èekání je u konce, Dragonfly závod zaèíná...
{22780}{22825}Platí pouze jediné pravidlo a to je prosté...
{22832}{22930}Ten kdo jako první, získá tøí zlaté mince, ze tøí rùznıch kontrolních stanoviš... 
{22930}{22989}a proletí s nimi cílem, se stane vítìzem.
{23014}{23087}Kdo bude tím šastnım, kterı si odnese domù hlavní cenu?
{23099}{23203}Dnešní historickı den vám samozøejmì zprostøedkujeme ivì.
{23584}{23637}Právì bylo odstartováno!
{23637}{23720}Kdo vyhraje a odnese si cenu pro vítìze?
{23774}{23788}Princezno.
{23794}{23851}Závod je teprve na zaèátku, netlaète se tolik dopøedu.
{23893}{24006}V této èásti závodu, se musí závodníci kromì tìchto budov, vyhnout i plovoucím reklamám.
{24218}{24303}Kurotan to dokázal. \NTo byl jeden z nejlepších prùletù jaké jsem kdy vidìl.
{24303}{24348}Povídal sem, abys mi tak neøíkal!
{24356}{24396}Dobrá, to je malièkost.
{24415}{24480}Vynikající manévr pilota letícího s Swallowem.
{24415}{24480}Swallow znamená doslovnì vlaštovka.
{24702}{24730}Hodnì štìstí...
{24778}{24800}vám obìma.
{24834}{24905}Vedoucí závodníci se blíí k prvnímu kontrolnímu stanovišti.
{24911}{25014}Pokud se jim nepodaøí získat minci, bude to pro nì znamenat váné komplikace.
{25041}{25079}Jak to máme sebrat?
{25101}{25121}Pravdìpodobnì...
{25207}{25226}takto.
{25546}{25574}Je to jasné.
{25588}{25669}Kdy se vznášedla pøiblíí dostateènì blízko, dojde k promìnì jako pøed chvílí.
{25679}{25734}Èím více závodníkù proletí stanovištìm, tím míò mincí zbude...
{25741}{25770}docela problém.
{26267}{26306}Princezno, zpomalte!
{26354}{26370}Pospìšte si!
{26455}{26523}Oh boe... co se to dìje?
{26523}{26587}Vypadá to, e se na trati stala nìjaká nehoda!
{26658}{26670}Princezno...
{27043}{27067}Mám jí.
{27123}{27248}Mokona se jako zázrakem vyhnul nehodì a získal minci. 
{27446}{27503}A to je zlé, tenhle propásl svou poslední šanci.
{27503}{27539}Teï u minci nezíská...
{27550}{27600}a je ze hry.
{27632}{27735}Vypadá to, e na to skoèili.
{27766}{27875}První tøi vedoucí závodníci, se nám rychle blíí k druhému kontrolnímu stanovišti.
{27929}{28018}Dobøe... postoupíme tedy dále.
{28032}{28064}Co to k èertu je?
{28089}{28157}Druhım kontrolním stanovištìm je Draèí vıvrtka.
{28162}{28285}Kadı kdo chce získat minci, musí proletìt skrz tuto vıvrtku.
{28305}{28322}Ten bastard...
{28335}{28394}Kurosan to opravdu nechce prohrát.
{28605}{28671}Buïte ostraití, protoe tato vıvrtka se mùe rùznì kroutit.
{28671}{28710}Kruci, to je trochu unfér!
{28807}{28902}Yellow Tiger a Snow White jako první, prolétli druhım kontrolním stanovištìm.
{28807}{28902}Yellow Tiger a Snow White doslovnì znamenají lutı tygr a Snìhurka.
{29240}{29274}Shaorane, podívej.
{29320}{29333}A sakra...
{29601}{29637}Dostalo mì to.
{29647}{29727}Ještì štìstí, e ta vıvrtka je z tak mìkkého materiálu.
{29740}{29789}Bohuel, tu máme další nehodu!
{29789}{29835}A jak Swallow, tak Clover jsou mimo hru.
{29840}{29900}Poèet závodníkù, nám tím pádem klesl na sedm.
{29943}{29967}Zmìním jedno z pravidel.
{29980}{30026}Vypnìte rotaci vıvrtky!
{30026}{30121}Jakmile to udìláte, tak to tam vyèistìte... a oznamte to centrále.
{30134}{30150}Ano.
{30262}{30328}Wing Egg je poslední vznášedlo, které se dostalo skrz vıvrtku.
{30358}{30396}Pøedletím Shougu.
{30402}{30421}Buï opatrnı.
{30612}{30677}Šílenı kluk, jako by ho Mokona poslouchala na slovo.
{30677}{30789}Teï u je i pøed Spiritem a rychle míøí k údolí.
{30970}{30987}Zvládl jsi to.
{31066}{31091}Èekal jsem na tebe Štìnì.
{31107}{31125}Musíme se spolu utkat.
{31164}{31178}Jasnì.
{31405}{31449}Oba dva jsou velmi nadaní.
{31457}{31520}Bohuel, jejich talent je bude stát ivot.
{31593}{31619}Ryuuohu, poèkej!
{31655}{31673}Ryuuohu!
{31712}{31722}Co to...
{31824}{31849}Za-tra-ce-nì.
{31912}{31934}Dr se stranou Štìnì.
{32058}{32104}Stùj! Chceš to schytat?
{32185}{32233}Stùj!
{32270}{32360}Oh ne, Mokona a Ryuuga se srazily!