{2191}{2245}Oba dva jsou velmi nadaní.
{2245}{2305}Bohuel, jejich talent je bude stát ivot.
{2381}{2410}Ryuuohu, poèkej!
{2441}{2458}Ryuuohu!
{2498}{2507}Co to...
{2611}{2631}Za-Zatracenì.
{2673}{2688}Ryuuohu.
{2698}{2725}Dr se stranou Štìnì.
{2847}{2884}Stùj! Chceš snad umøít?
{2971}{3017}Stùj!
{3055}{3149}Oh ne, Mokona a Ryuuga se srazily!
{3279}{3302}Shaorne.
{3470}{3540}Správná trefa
{3741}{3805}Nárazem do mıho vznášedla si mi zachránil ivot.
{3822}{3882}Ale, teï jsme tady zkejsly... promiò.
{3893}{3948}Hlavnì, e jsi v poøádku.
{3991}{4050}Ty seš fakt borec.
{4085}{4103}Shaorane.
{4180}{4191}Princezno.
{4237}{4249}Ok.
{4321}{4439}Zbylí závodníci se u rychle blíí k tøetímu kontrolnímu stanovišti.
{4542}{4632}V této èásti závodu, se musejí vyhnout náhodnì vytryskávajícím gejzírùm vody.
{4724}{4753}Naprosto šílené.
{4753}{4855}Kurotan, pravdìpodobnì nejvìtší kandidát na vítìzství, teï ukázal svojí sílu a dostává se vedení.
{4908}{4975}A u se zde objevuje i Wing Egg.
{5038}{5094}Nemohu øíct, kdy dojde k vytrysknutí vody.
{5155}{5170}Já ano.
{5365}{5458}Uááá... Wing Egg si protanèil cestu a druhému místu.
{5799}{5820}Kuropone.
{6025}{6043}Kurogane.
{6065}{6081}Le!
{6097}{6112}Ale...
{6144}{6179}Dokáeš to.
{6218}{6229}Le.
{6246}{6257}Dobøe.
{6635}{6672}Zpráva pro Mademoisele Tomoyo.
{6721}{6797}Doposud jsme ádnou podezøelou aktivitu, ze strany závodníkù nezaznamenali.
{6819}{6897}Nemohou vyhrát jinak, ne e zasáhnout do závodu.
{6922}{6983}Proto musí bıt jeden ze závodníkù pachatelem.
{7003}{7055}Pokud to tak je, tak proè \Nse nìkdo z nich nechová podezøele...
{7095}{7141}Protoe má nìjakého komplice...
{7179}{7283}Pravdìpodobnì to bude nìkdo z venku, kdo ovlivòuje závod.
{7303}{7372}Provìøte veškerou komunikaci na všech frekvencích.
{7596}{7648}To znamená, e i ty pøedchozí exploze...
{7663}{7714}A u je to kdokoliv, jde mu o pírko.
{7728}{7793}Klatì... ale kdo ze závodníkù by to mohl bejt?
{7825}{7848}To nevím.
{7869}{7925}Ale vím jistì, e je to nìkdo z nich.
{7944}{7987}Proto jsem si to namontoval do svého vznášedla.
{8001}{8028}Tak proto.
{8045}{8074}Ty seš, ale hlavièka Štìnì.
{8138}{8178}Signál vychází odtud.
{8186}{8231}Ale jak by mohli na takovou dálku...
{8434}{8492}Vezmeme vás do medical centra.
{8434}{8492}Medical centrum = zdravotnické zaøízení
{8511}{8583}Promiòte, ale mohly by jste nás místo toho vzít nìkam jinam?
{8633}{8654}Prosím.
{8859}{8942}Strhujícím závìrem se nakonec Youbi probil pøes tøetí kontrolní stanovištì.
{8963}{9047}Uvidíme, jestli se nìkdo pokusí o horní prùlet i pøes veliké nebezpeèí, které to pøedstavuje.
{9054}{9184}Ve vzdušném prostoru nad roklinou jsou toti umístìné mobilní laserové jednotky.
{9184}{9261}Jeden špatnı pohyb a zahájí palbu.
{9276}{9387}Zároveò jsou umístìny v minimální vıšce, co pro závodníky znamená, maximální moné riziko.
{9491}{9549}Youbi útoèí horem...
{9665}{9741}a to pro nìj znamená konec závodu.
{9810}{9837}Dìje se nìco?
{9850}{9912}Kuropon by s vámi rád mluvil.
{9931}{9975}O co tady jde?
{10161}{10176}Mluvte.
{10225}{10279}Ovlivnila jsem závod.
{10313}{10336}Neøíkejte.
{10356}{10430}Ale pouze v kvalifikaci pomocí tepla.
{10461}{10546}Proto jsem  uvolnila do vzdušného prostoru ty nanoroboty.
{10559}{10596}Proè jste to udìlala.
{10610}{10741}Protoe chci, aby Sakura získala zpìt své pírko.
{10930}{10962}Je tomu u rok...
{10983}{11083}co expedièní team mé spoleènosti, objevil záhadnı zdroj energie...
{11083}{11140}ve formì pírka na dnì oceánu.
{11193}{11323}Po nìjaké dobì jsem zjistila, e osobou, které patøí je Sakura.
{11356}{11456}Nicménì se tak stalo pøed tím, ne se o nalezení pírka dozvìdìla veøejnost.
{11513}{11637}Naše dvì sousední zemì, které s námi mají hranice, samozøejmì zaèali klást jisté poadavky.
{11661}{11728}Nezáleí na tom, jak velkı pøínos by to pro Piffle Princess spoleènost mìlo...
{11744}{11871}nemùeme si prostì pírko nechat a schovávat ho pøed celım svìtem.
{11911}{11992}Proto je jako hlavní cena.
{12017}{12098}Tím se zabrání tomu, aby bylo s pírkme špatnì naloeno.
{12125}{12210}A také tím mùeme také tajnì urèit, komu pírko pøipadne.
{12234}{12318}Nicménì to znamenalo, vystavit vás nebezpeèí.
{12340}{12458}Proto jsme bìhem kvalifikace, rozbìhli tajnou operaci...
{12463}{12510}aby jsme skryli náš hlavní zámìr.
{12524}{12577}Chci se zeptat jen na jedno...
{12587}{12642}Co se stane, kdy nikdo z nás ten závod nevyhraje...
{12669}{12709}Oh, s tím si nedìlejte starosti.
{12730}{12837}Nìkdo mi øekl, e vám mohu dùvìøovat.
{12846}{12876}O èem to k èertu mluvíte?
{12892}{12956}O co tady zase jde?
{12956}{12979}Kdo je to?
{13021}{13063}Lokalizovali jsme místo vysílání.
{13078}{13092}Odkud?
{13111}{13122}Vychází to...
{13177}{13202}Z mojí spoleènosti?
{13421}{13507}Koho by napadlo, e za vším stojí sponzoøi z Piffle Princess Company...
{13532}{13635}Docela by mì zajímalo, proè furt tvrdily, e se jedná o férovej závod.
{13658}{13731}A za touto roklinou u na nás èeká cíl.
{13731}{13821}Kdo se stane vítìzem? Snow White?... nebo snad Spirit?
{13845}{13927}Uh, Wing Egg se za pomoci pøídavnıch motorù dere do pøedu
{13942}{14020}A tímto manévrem se dostává do vedení.
{14063}{14134}Dalším cílem je Wing Egg.
{14171}{14199}Rozumím.
{14415}{14525}Shibetsudake Translations
{14682}{14719}Zamìø cíl.
{14737}{14798}Zaèni s nabíjením laserového paprsku.
{14883}{14949}Zniè Wing Egg.
{14967}{14978}Stùj!
{15069}{15096}C-co?
{15110}{15123}Jak?
{15142}{15159}Ty jsi...
{15270}{15320}Ten chlápek je z Piffle Princess Company.
{15568}{15614}Zabij ty vetøelce.
{15720}{15756}A jak mì chceš zastavit teï?
{15770}{15845}Nezbıvá ti, ne sedìt a sledovat jak zabiju tvojí pøítelkyni.
{15874}{15921}Jestli rychle nìco neudìláme, princezna...
{15960}{15995}Dr se Mokono!
{16190}{16220}Já se o nìj postarám.
{16260}{16286}Nalákám ho.
{16295}{16324}Ale to je nebezpeèné!
{16337}{16383}Dluím ti to.
{16693}{16707}Co?
{16855}{16876}Je konec.
{17011}{17030}Štìnì.
{17136}{17189}Teï u je to jenom na vás princezno.
{17473}{17501}Kde je cíl?
{17558}{17597}Jestli si nepospíšíš, tak nás pøedhoní.
{17673}{17687}Vítr...
{17793}{17832}Pevnì se dr Mokono!
{18098}{18151}Cíl.
{18160}{18252}Wing Egg jako první prolétává cílem a vyhrává.
{18293}{18317}Mlask, mlask...
{18324}{18363}Gratuluju... mlask.
{18398}{18419}To je...
{18434}{18452}Ano.
{18460}{18495}Vyhrála jsi.
{18522}{18537}Vyhrála?
{18615}{18637}Dokázali jsme to.
{18719}{18741}Jùùù...
{18741}{18775}Skvìlá práce Sakuro!
{18785}{18828}Oslavuj Kuropone.
{18838}{18855}Dy to dìlám.
{18874}{18902}Vánì, vánì.
{18972}{19034}Nechceš pøece, aby si Sakura dìlala starosti kvùli tomu, e pøed ní nìco tajíš, viï?
{19047}{19115}No tak Kurosame, jùùù, jùùù....
{19129}{19169}Pøestaò s tím blbım jùùù.
{19224}{19261}Vìdìla jsem, e to Sakura dokáe.
{19272}{19384}Od teï je pírko oficiálnì její.
{19548}{19581}Je skvìla, viï?
{19597}{19649}Ano, to opravdu je.
{19689}{19744}Ale ještì není konec.
{19812}{19914}Ještì zbıvá... chytit toho druhého.
{20035}{20105}A teï zaèíná vítìznı ceremoniál.?????????????????????????????????????????????????
{20145}{20224}Vítìzka Dragonfly Race je nejen nejkrásnìjší...
{20224}{20289}ale i nejrychlejší.
{20289}{20372}Není to nikdo jinı ne pilot vznášedla Wing Egg, Sakura.
{20653}{20684}Gratuluji.
{20711}{20729}Dìkuji.
{20861}{20911}Hele, vy se máte rádi, e jo?
{21075}{21089}Princezno.
{21169}{21183}Princezno.
{21431}{21467}Take jste se rozhodl nakonec ukázat.
{21480}{21491}Pozor.
{21545}{21571}Ty bastarde...
{21635}{21653}Ryuuohu.
{21667}{21736}Nedìlej si... starosti...
{21762}{21785}Je to omraèující paprsek.
{21791}{21841}Kadı kdo jim bude zasaen, ztratí na chvíli vìdomí.
{21869}{21888}Tomoyo.
{21906}{21961}Pospìš si a vezmi si zpìt sílu svého pírka Sakuro.
{22001}{22046}Jak to, e o tom víš Tomoyo?
{22364}{22422}Take, ty jsi tou druhou osobou.
{22445}{22485}To pírko náleí mì.
{22563}{22576}Tohle vám nepomùe.
{22752}{22765}Coe?
{22778}{22806}Vıbornì Mokono.
{22826}{22884}To je jedna ze stoosmi tajnıch schopností Mokony...
{22898}{22945}Super sací síla.
{22972}{23019}Na tuto vzdálenost tì ádnı energetickı štít neochrání.
{23048}{23081}Policejní sloky tu budou za pár minut.
{23105}{23148}Nemáš jak utéct.
{23170}{23225}Jestli se o nìco pokusíš, budeš toho litovat.
{23268}{23312}Kruci, zase sem ho nezískal.
{23395}{23510}Vše opìt zmaøeno kvùli té kreatuøe, tak jako ve svìtì Jade...
{23527}{23584}Nejsem ádná kreatura, jsem Mokona.
{23599}{23619}Moment...
{23634}{23669}Mluvil o svìtì Jade?
{23679}{23692}No jo.
{23719}{23737}To není moné...
{23973}{24006}Proè se na mì tak díváš?
{24038}{24137}Ty jsi Dr. Kyle ze svìta Jade.
{24503}{24605}V rùznıch svìtech potkáváte rùzné lidi se stejnım vzhledem.
{24633}{24731}Nicménì si nikdy nemùete bıt jisti, zda jsou skuteènì jiní nebo ne.
{24801}{24850}To je to, na co by jsi mìl vdy pamatovat.
{25175}{25189}Zmizel.
{25204}{25255}Nebo spíše, pøešel do jiné dimenze.
{25316}{25385}Pøesnì jak to øekla.
{25410}{25436}Skoro bych zapomnìl.
{25448}{25493}Øekni mi, kdo to k èertu je "ona"!
{25516}{25545}Pøeci princezna Tomoyo.
{25572}{25597}Co to øíkáš?
{25648}{25698}O všem ti povím....
{25724}{25826}o pírku... o existenci rùznıch svìtù...
{25848}{25942}a o tom, jak jednoho dne,  pøijde do tvého svìta skupina cestovatelù.
{25984}{26016}Kdo jsi?
{26042}{26099}Jsem z jiného svìta.
{26123}{26239}Já jsem ty, stejná tváø, stejná duše, jen z jiné èasové osy.
{26264}{26311}Existuje více ne jen jeden svìt.
{26404}{26473}Prosím, vra pírko její pravé majitelce.
{26497}{26536}Ale buï opatrná.
{26551}{26647}Mnoho lidí z rùznıch svìtù se ho snaí získat.
{26886}{26943}Take øíkáš, e za tebou princezna pøišla ve snu...
{26964}{26978}Ano.
{26992}{27092}Take se dá øíct, e jste nám lhali.
{27126}{27179}Záleí na tom, jak se to vezme.
{27189}{27233}Kadopádnì to nebylo férové.
{27261}{27374}Ohlednì toho útok na sleènu... cítil jsem, jakoby mé srdce, bylo pošpinìno neodpustitelnım høíchem.
{27390}{27508}Nebyli jsme schopni zjistit, e mìl komplice tak blízko mì.
{27526}{27564}Proto vám dìkuji.
{27636}{27711}Tobì se také omlouvám Sakuro.
{28382}{28402}Bolí tì to?
{28520}{28545}Tvá levá ruka.
{28569}{28590}To nic není.
{28691}{28704}V tvım snu...
{28756}{28783}ne, nic.
{28804}{28830}Zajímá tì to?
{28849}{28874}To nic.
{28893}{28939}Prosím, dopovìz to, co jsi chtìl øíct.
{29063}{29121}Jaká byla princezna Tomoyo z tvého snu?
{29139}{29166}Byla veselá.
{29222}{29312}Zdála se bıt šastná, kdy o tobì mluvila
{29331}{29394}Pravdìpodobnì se zapomnìla zmínit o tom, jak mì zradila.
{29409}{29549}Nic takového, øekla... Teï bude schopnı porozumìt, skuteènému vıznamu síly.
{29712}{29767}Nemìl by jsi si z toho dìlat tìkou hlavu.
{29835}{29885}Stejná duše...
{30481}{30513}Štìnì.
{30520}{30566}To u opravdu odcházíte?
{30630}{30675}Ale vím, e se opìt setkáme.
{30721}{30736}Jasnì.
{30748}{30771}Na to vem jed.
{30867}{30910}Mokona Modoki se u nemùe doèkat.
{31070}{31099}Bylo to tu zábavné.
{31118}{31147}Všem vám moc dìkuji.
{31163}{31224}Tomoyo, nìkdy se spolu zase setkáme.
{31271}{31353}Aèkoliv ještì neznáme zpùsob interdimenzionálního cestování...
{31360}{31409}moje spoleènost udìlá všechno proto aby na to pøišla.
{31430}{31491}Take, jsem si jistá, e se opìt uvidíme.
{31654}{31708}Jestli se ve svém snu zase potkáš s princeznou Tomoyo, øekni jí tohle...
{31737}{31777}Já se vrátím.
{31816}{31829}Ano.
{32124}{32211}Vypadá to, e naše pøímá intervence nezabrala.
{32252}{32321}Dá se øíct, e vısledek je znám ještì døív, ne zaèneme jednat.
{32354}{32435}Plánuješ je do svìta duchù?
{32461}{32570}Na vlastní oèi musím vidìt, co se z toho zázraku vyklube.
{32592}{32658}Ano, pošlu je tam.