{2478}{2527}Pøešli jsme do nového svìta.
{2540}{2566}Co do hajzlu znamená to "Puu"?!
{2577}{2635}Øíkal jsem ti, abys nás nechal pøistát na normálním místì!
{2635}{2683}Pøistát v oceánu, není zas a tak zlé..
{2691}{2739}Pøijde ti tohle jako normální místo?
{2739}{2787}Princezno... jste v poøádku?
{2801}{2836}Jen jsem se trochu polekala...
{2855}{2872}ale jsem v poøádku.
{2908}{2964}Ještì nikdy jsme nepøistaly tak, jak se to naplánovalo.
{2978}{3030}Pokud to tak bude pokraèovat, tak budeme brzo v pìknejch sraèkách.
{3063}{3100}Podívejte támhle!
{3390}{3455}IVOTNÍ ROZHODNUTÍ
{4040}{4065}Promiòte.
{4077}{4091}Vstupte.
{4167}{4185}Haló, vy jste...
{4382}{4433}Oh ne, to je zloun.
{4443}{4466}Jak jsi mi to øekl?
{4662}{4704}Ah, u je mi to jasnı...
{4715}{4784}Nìkomu, kdo vidí mùj ksicht poprvı, to tak asi pøijde.
{4784}{4813}Nejsi zloun?
{4834}{4897}Èlovìk, kterej ije na moøi, si z podobnıch kecù nic nedìlá.
{4914}{4975}Jsem kapitánem tıhle lodi... Lagosty.
{4975}{4991}Jmenuju se Tanbaru.
{5001}{5026}Já jsem Mokona...
{5034}{5064}A jsem idolem všech na svìtì.
{5073}{5102}Jasnì, jasnì.
{5115}{5155}A co je zaè ten idol?
{5169}{5240}Vypadáte jako dobrı èlovìk.
{5249}{5284}Ty mu to ereš?
{5297}{5326}Jeho duše je poøád stejná.
{5340}{5407}Ale co kdy jeho duše není jen plná zla?
{5421}{5447}Moná to tak je.
{5460}{5508}No, abych øekl pravdu, tak nevím.
{5545}{5575}Mimochodem...
{5660}{5693}rád bych s vámi o nìèem mluvil.
{5730}{5785}Na této lodi je hodnì práce, ale málo lidí.
{5812}{5877}Myslel sem, e by ste prozatímnì mohli dìlat kuchaøe.
{5908}{5925}Rádi.
{5947}{5987}Jsi nejlepší Mokono.
{5987}{6011}Jo jo jo.
{6155}{6225}Hej zelenáèi, vem si belík a pojï nám pomoct..
{6231}{6258}Nejsem zelenáè.
{6271}{6288}Jsem Kurogan.
{6299}{6317}Co si  to øíkal?
{6324}{6354}Budeš mít takovı jméno, kterı mi ti dáme!
{6381}{6403}To zní zajímavì.
{6503}{6516}Ale nechci.
{6571}{6627}Hej Mechaniku, seš tam?
{6634}{6649}Ano.
{6730}{6761}Takovı malı chlapec...
{6770}{6795}Je docela šikovnej.
{6820}{6882}Co se tıèe motorù, rozumí jim víc, ne kdejakej dospìlej.
{7286}{7299}Prosím.
{7315}{7330}Dìkuji.
{7364}{7380}Mimochodem...
{7400}{7415}Ano?
{7426}{7458}Nepotkali jsme se u nìkdy?
{7509}{7539}Nevzpomínám si.
{7557}{7582}Ah, ovšem.
{7603}{7641}Omlouvám se, e jsem o tom mluvil.
{7658}{7715}Jmenuje se Shaoran.
{7729}{7792}Øíkal, e ti rád pomùe.
{7792}{7817}To je skvìlé.
{7953}{7996}Já jsem Fujitaka... mechanik na této lodi.
{8009}{8041}O-otèe?
{8097}{8110}N-ne..
{8170}{8230}Omlouvám se, to nic.
{8613}{8642}Klidnì se toho dotkni.
{8975}{9001}Nechceš mi pomoct?
{9077}{9098}Nechceš mi pomoct?
{9182}{9256}Omlouvám se,zamyslel jsem se.
{9271}{9309}U zase?
{9715}{9735}Takhle.
{9758}{9776}Rozumím.
{9807}{9832}Trochu jemnìji...
{9847}{9888}Ano, to je ono.
{9923}{9976}Nechtìl by jsi jít se mnou pøíštì na vykopávky?
{10013}{10068}Archeologie je zajímá, nebo ne?
{10126}{10140}Ano.
{10316}{10361}Paluba je utøená.
{10374}{10395}Dobøe.
{10427}{10438}Díky.
{10530}{10564}Prosím, ochutnej.
{10579}{10596}Jistì, jistì.
{10616}{10648}A co je to?
{10656}{10739}Je to taková chuovka co jsem udìlala s Mokonou. Øíká se tomu "shisu".
{10745}{10794}Ne "shisu", ale "sushi".
{10801}{10832}Oh, zase jsem to spletla.
{10849}{10892}Voní to divnì.
{10902}{10954}Ta ryba je syrová.
{10980}{11028}Fai nemá rád sushi.
{11038}{11059}Vypadá to tak.
{11244}{11289}Co je to?
{11393}{11463}Je to trochu divné, ale chutná to opravdu skvìle.
{11477}{11577}Jednou jsem nìco takového jedl v jedné zemi se svım otcem.
{11589}{11670}Jakı je tvùj otec Shaorane?
{11744}{11821}No, je to u dlouho co odešel.
{11839}{11863}Rozumím.
{11879}{11893}Ale...
{11962}{12042}Ne, to nic.
{12071}{12129}Take ten chlapec je Shaoranùv táta?
{12135}{12279}Jedná se sice o jinou osobu, ale má stejnou duši, jako mìl Shaoranùv otec.
{12294}{12310}Ano.
{12310}{12372}Ale jak mùe bıt jeho otec, kdy je mladší ne on?
{12382}{12457}Lidé, které potkáváme v rùznıch svìtech...
{12457}{12546}mají sice stejnou duši, ale to neznamená, e musejí mít bezpodmíneènì stejnı vìk.
{12554}{12699}Tøeba se nám stane, e jednoho dne uvidíme malého Kurorina.
{12699}{12722}Blbost.
{12737}{12796}V kadém pøípadì, je na tomhle svìtì pírko?
{12803}{12874}Nic necítím.
{12879}{12919}Take tady jen ztrácíme èas.
{12939}{13000}Ale Mokona by tady rád chvíli zùstal.
{13037}{13097}A Shaoran urèitì taky.
{13116}{13131}Co, já?
{13158}{13222}Dokáu vycítit jak ti je Shaorane.
{13235}{13335}Shaoran by chtìl strávit nìjakı èas s tím chlapcem.
{13345}{13406}Take to je dùvod, proè tu chce Mokona zùstat o nìco déle.
{13452}{13491}Dìkuji, Mokono.
{14032}{14053}Pane Shaorane...
{14076}{14100}Øíkej mi jen Shaorane.
{14124}{14204}Co jsi dìlal, kdy jsi byl v mém vìku, Shaorane?
{14264}{14307}Pomáhal jsem svému otci.
{14322}{14375}On byl archeolog, e ano?
{14392}{14404}Ano.
{14413}{14497}Take jsi také cestoval a poznával rùzné zemì viï?
{14529}{14569}Tak nìjak... mám rád archeologii...
{14583}{14616}ale to není ten dùvod, proè cestuji.
{14647}{14734}Nìkde tam v dalekém svìtì je nìco, co musím nalézt.
{14810}{14827}Musí to bıt skvìlé.
{14904}{14973}Je pìkné jít za svım cílem.
{15022}{15080}Také bych chtìl najít svùj smysl ivota.
{15150}{15234}Zatím jsem ho ještì nenašel.
{15321}{15396}Zajímalo by mì, zda mùj otec, tímto také prošel.
{15491}{15531}Hej, hledá vás ten starouš.
{15576}{15603}Co se dìje, kapitáne?
{15638}{15672}Ztratili jsme náhle vítr..
{15691}{15719}Take pøichází bouøe?
{15727}{15745}Coe?
{16689}{16749}U nemùeme dál, musíme vysadit motor.
{16758}{16799}Ale k tomu nedal kapitán rozkaz.
{16813}{16836}To probereme pozdìji.
{16849}{16886}Pojï se mnou Shaorane.
{17018}{17064}Odlehèete trochu loï!
{17072}{17093}Honem!
{17107}{17147}Kapitáne, musíme vypnout motor...
{17231}{17252}Mechaniku!
{17324}{17351}Chytejte!
{17446}{17467}Shaorane.
{17487}{17512}Mechaniku.
{17572}{17589}Smích?
{17599}{17616}To není moné...
{17799}{17828}T-to je...
{18398}{18441}Héééj... Mechanikùùù!
{18452}{18474}Zelenáááèííí.
{18604}{18669}Takhle je nikdy nenajdeme.
{19298}{19330}T-to je...
{19607}{19625}K-kde to...
{19640}{19686}Zdá se, e nás proud zanesl na nìjakı ostrov.
{19725}{19744}Kde je Lagosta?
{19772}{19797}Neøíkej, e se potopila!
{19807}{19903}Pokud by to tak bylo, muselo by bıt pobøeí plné trosek.
{19920}{19961}Take je v bezpeèí.
{19971}{19988}Pravdìpodobnì.
{19995}{20013}Díky bohu.
{20074}{20168}Tak jako tak, musíme zjistit kde jsme a dát vìdìt ostatním, e jsme tady.
{20201}{20279}Jene kdy zùstaneme na plái, tak nás nenajdou.
{20310}{20361}Potom tedy pojïme nìkam odkuï nás uvidí.
{20580}{20595}To je...
{20636}{20647}Ovšem.
{20688}{20741}Je to Ostrov duchù.
{20808}{20841}Ostrov duchù...
{21244}{21258}Co je to?
{21271}{21330}To jsou hlasy duchù, spoèívající na tom ostrovì.
{21336}{21354}Duchù?
{21367}{21428}V mojí rodinì se o nìm vypraví u po celé generace..
{21453}{21524}Zlı duchové z toho ostrova...
{21538}{21604}nikdy nikomu nedovolí vstoupit na ostrov.
{21618}{21707}Ale Shaorana a Fujitaku to tam mohlo zanést.
{21723}{21779}Pokud to tak je, nemùeme jim pomoct.
{21800}{21859}Tomu nemùete rozumìt... vy tímto svìtem pouze procházíte...
{21859}{21990}ale my co zde ijeme, nemùeme porušit nepsaná pravidla našich pøedkù.
{22005}{22048}Je mi líto.
{22061}{22082}Oh ne..
{22367}{22389}Nejsi unavenı?
{22399}{22453}Ne... ani trochu pane.
{22494}{22540}Mohl by jsi pøestat mluvit v keigu?
{22580}{22590}Ale...
{22610}{22640}Nebudu se  zlobit.
{22761}{22774}To je...
{22781}{22802}To... to je duch.
{22962}{23031}Vypadá to, e zde kdysi ili lidé.
{23031}{23074}Take potom, to jsou...
{23086}{23104}Jsou to ruiny.
{23119}{23164}Vypadá to hodnì staøe.
{23181}{23211}To je mapa ostrova?
{23375}{23454}Boí dech, strašlivı proud tvoøí...
{23471}{23568}zatím co ty, zpìv Boí posloucháš, cesta pøed tebou se otevøe.
{23582}{23599}Ty to umíš pøeèíst?
{23656}{23729}Studoval jsem písmo, které je tomuto velmi podobné.
{23749}{23828}To èeho vskutku obávavat by jsi se mìl, jest stvoøením dlouhım a útlım.
{23861}{23897}Zbytek nemohu pøeèíst.
{23953}{24012}Tohle mi pøijde jako nejkratší cesta na vrchol ostrova.
{24048}{24125}Ale já ádnou cestu nevidím.
{24155}{24197}Ta cesta bude asi tohle.
{24306}{24347}Jsi skvìlı, Shaorane.
{24377}{24443}Všechno co znám, jsem se nauèil od svého otce.
{24764}{24805}e by duch?
{24818}{24832}Asi.
{24842}{24951}To co slyšíme, je pravdìpodobnì ten boí zpìv, o kterém byla zmínka v ruinách.
{25040}{25068}Duch se smìje...
{25086}{25095}K zemi.
{25350}{25381}To byl Boí dech.
{25398}{25467}Pøed vším jsme byli varování nápisama na  tìch ruinách.
{25487}{25596}Všichni si mysleli, e jde o duchy a on je to ve skuteènosti jen zvuk vìtru.
{25696}{25752}Jestli chceme najít loï, musíme se dostat na druhou stranu.
{25768}{25835}Ale aby jsme se tam dostali, musíme projít skrz tuto jeskyni.
{25851}{25936}Ale co kdy nás ten prudkı závan vìtru zasáhne uvnitø jeskynì?
{25980}{26027}Boí dech, strašlivı proud tvoøí...
{26049}{26143}zatím co ty, zpìv Boí posloucháš, cesta pøed tebou se otevøe.
{26173}{26190}Rozumím.
{26205}{26273}Take dokuï budeme slyšet zpìv vìtru, nic se nám nestane.
{26563}{26619}Opravdu tam šli...
{26696}{26732}Kormidlo zajištìno.
{27059}{27071}Jdeme.
{27081}{27092}Ano.
{28026}{28072}Zmìna smìru vìtru.
{28711}{28742}To bylo tìsné.
{28776}{28812}Dìkuji, Shaorane.
{28976}{28995}Jsou na ivu...
{29010}{29040}oba dva.
{29080}{29107}Tadııı.
{29179}{29228}Podívejte, podívejte... támhle jsou.
{29236}{29256}Díky bohu.
{29270}{29373}Héééj... zùstaòte na místì, plujeme k vám.
{29393}{29409}To je...
{29900}{29966}To èeho vskutku obávavat by jsi se mìl, jest stvoøením dlouhım a útlım.
{29986}{30051}To je to, co bylo napsáno na tìch ruinách.
{30103}{30224}Kdy nám naši pøedci, povídali o duchách...
{30224}{30305}byl to pravdìpodobnì zpùsob, jak nás varovat pøed tou nestvùrou.
{30623}{30693}Nakonec to vypadá, e místo duchù se skuteènì jednalo jen o vítr.
{30712}{30774}Pøesto si myslím, e bychom mìli toto tajemství, dret v tajnosti.
{30805}{30840}Svìt je velikı...
{30857}{30922}a my máme povinnost, jeho tajemství zachovávat.
{30939}{30948}Ano.
{30960}{31004}Omlouvám se, e jsem ti nepøišel na pomoc. 
{31017}{31028}To je v poøádku.
{31043}{31129}Dìkuji vám kapitáne, našel jsem nìco, co jsem hledal celou dobu.
{31241}{31268}Díky za všechno.
{31305}{31331}Musíme u, ale jít.
{31372}{31394}O èem to mluvíš?
{31402}{31432}Jsme uprostøed oceánu!
{31530}{31579}Mokona Modoki se u nemùe doèkat.
{31738}{31772}C-co...
{31865}{31877}Opatrujte se.
{32037}{32075}U jsem to našel Shaorane.
{32089}{32156}A vyrostu, chci bıt archeologem!
{32243}{32272}Vím, e to dokáeš..
{32308}{32324}Jsem si tím jistı.
{32407}{32476}Sbohem... otèe.

