{2969}{2994}Kdo jsi?
{3098}{3145}Není ti nic Shaorane?
{3170}{3220}To byl jen sen.
{3220}{3248}Byl ošklivı?
{3248}{3287}Kdepak.
{3429}{3611}I kdy nemám ádné vzpomínky na dobu pøed tím dnem, jsem si jistı, e jsem Shaoran.
{3615}{3678}ASHURA & YASHA
{3724}{3778}Pøešli jsme do nového svìta, e ano?
{3796}{3835}Kde jsou Kurogan s Faiem?
{3835}{3917}Vypadá to, e pøistáli na jiném místì ne my.
{3917}{3940}Coe?
{3940}{3983}Ale nachází se na tomto svìtì, stejnì jako my.
{4066}{4104}U jsi se probral...
{4104}{4159}U jsme si o tebe zaèali dìlat starosti.
{4159}{4243}Všichni jsou takovı roztomilí.
{4243}{4279}Tak moment!
{4314}{4441}U je skoro èas, jít do práce, take se tu pøestaòte flákat a marnit váš i mùj èas.
{4441}{4507}A jen tak pro poøádek, jestli je to kluk, nemùe tu zùstat!
{4541}{4579}Oh, Suzuran...
{4579}{4626}Já tady velím.
{4646}{4723}Nemohla by jste to pøehlednout?
{4752}{4782}Karen-taifu
{4752}{4852}Pozn. Taifu je dritel hlavní role v japonské høe NOH
{4782}{4908}Našla jsme je oba venku v bezvìdomí, pøièem ta dívka se probrala jako první...
{4908}{5071}Ten chlapec se dlouho neprobíral a tak jsem svolila s jeho pøenesením sem, i kdy vím, e to je zakázané.
{5126}{5167}Take jsi zranìnı?
{5167}{5221}Ne, tak to není.
{5221}{5275}Tak, proè jsi byl v bezvìdomí?
{5275}{5363}Protoe, u dlouho cestujeme...
{5363}{5410}Oh, musí bıt hladovı....
{5410}{5462}A unavenı, chudáèek...
{5462}{5507}Navíc je velmi mladı...
{5507}{5527}Šéfová!?!
{5652}{5767}I kdy se jedná o neznámé cestovatele, nemùeme odmítnout nìkoho, kdo se octil v nesnázích...
{5767}{5851}Jméno herecké spoleènosti Suzuran by tím bylo pošpinìno.
{5864}{5935}Já, Suzuran, se o vás postarám.
{5935}{5995}Take, buïte vítání, cestovatelé.
{6268}{6355}Bùh ví kde skonèil Shaoran a ostatní.
{6355}{6405}Zajímalo by mì, kde teï jsou.
{6405}{6429}Proè by mì to mìlo zajímat?
{6429}{6578}Jeliko se mùeme mezi sebou bavit, tak pøedpokládám, e moc daleko od nás nebudou.
{6594}{6727}Pokud jsme od Mokony pøíliš daleko, nejsme schopni se spolu bavit, nerozumíme si.
{6841}{6883}Také to cítíš, Kuropone?
{7146}{7171}Udeøil jsem ho jen tupou stranou svıho meèe.
{7185}{7267}Takovı amatéry jako vy, nemá cenu zabíjet.
{7303}{7327}Pøestaòte!
{7747}{7850}Za ten incident pøed naším domem se omlouvám.
{7850}{7867}To je v poøádku.
{7900}{7963}Nádherné místo.
{7977}{8125}Nejen tento dùm, ale i místo a vzduch, vše je tak èisté.
{8130}{8245}Toto je  svaté místo, které dává lidem zapomenout na své útrapy.
{8256}{8415}Mùj rod, se zde po staletí modlí, za blaho všech lidí.
{8415}{8475}Mimochodem, cestujete sami?
{8475}{8557}Ne, cestuje nás více, ale ztratili jsme se.
{8557}{8630}Pravdìpodobnì vás budou hledat.
{8630}{8715}Nechtìli by jste zde prozatím zùstat?
{8730}{8802}Pøinejmenším do doby ne vás najdou.
{8802}{8822}Mohly by jsme?
{8844}{8954}Je to naše poslání, pomáhat lidem v nesnázích.
{9395}{9468}Suzuranina herecká spoleènost je podobná cirkusu.
{9468}{9502}Cirkusu?
{9502}{9590}Herecká spoleènost, která cestuje a pøedvádí zábavná èísla a rùzné triky.
{9608}{9662}Nìco podobného bylo i v království Clow.
{9679}{9770}Nebylo to sice jako toto, ale vzpomínám si, e to byla opravdová legrace.
{9838}{9892}Shaorane... podívej, podívej.
{9892}{9934}Úasné... úasné.
{9934}{10016}Zajímalo by mì, jestli bych to zvládla, kdybych to trénovala.
{10016}{10048}Je to nebezpeèné.
{10048}{10108}Nevadí, budu tvrdì trénovat.
{10108}{10180}Ne, trénink by byl také  velmi nebezpeènı.
{10203}{10291}A to zvládnu, udìlám ti také pøedstavení Shaorane.
{10489}{10574}Pamatuji si to proto, e jsi mi vrátil má pírka Shaorane.
{10632}{10660}Dìkuji ti.
{10677}{10702}Nedìkujte mi.
{10737}{10809}Take Mokono, cítíš tady pøítomnost pírka?
{10809}{10856}Nic necítím...
{10856}{10917}Ale to neznamená, e tady není.
{10941}{11029}Take jich tu mùe bıt více, ale také nemusí.
{11029}{11097}Navíc nevíme, kde je Kurogan s Faiem.
{11457}{11493}Není to nádherné?
{11509}{11625}Cestujeme po zemi Shara a vystupujeme.
{11625}{11712}Omlouvám se za problémy, které s námi máte.
{11712}{11761}To je v poøádku.
{11761}{11877}Problémy našich hostù jsou i naše problémy.
{11892}{12041}Jednou za rok, kdy mìsíc ukazuje celou svou krásu, se sem vracíme.
{12073}{12161}Co se ale nemìní je fakt, e a u jsme kdekoliv, je to zábava.
{12161}{12260}Ale toto místo je pro nás zvláštní... je tady náš domov.
{12293}{12332}A naši blízcí....
{12431}{12452}Pøekrásné.
{12452}{12509}Princezno, jestli se dotkne plamenù, tak se...
{12509}{12584}Naše plameny vás nespálí ani kdy se jich dotknete.
{12650}{12728}To díky našemu Boskému stráci.
{12771}{12800}Boskému stráci?
{12870}{12914}Pøeci jen je to tìké...
{12914}{12958}Máte problémy s hùlkami?
{12958}{13029}Ano... závidím ti Kurosame.
{13029}{13094}Tato zemì je podobná té mojí.
{13163}{13191}Dìje se nìco?
{13191}{13255}Z tamté strany cítím pùsobení podivné síly.
{13275}{13351}Je to nìjaká bariéra.
{13365}{13496}Jako by ta síla chránila nìco, co je uvnitø.
{13546}{13711}Vaše umìní, v zacházení s meèem a vaše šactvo napovídá, e nejste obyèejní cestovatelé... kdo jste?
{13914}{13970}To je socha Yashi.
{13970}{13991}Ano.
{14344}{14368}Krvavé slzy.
{14383}{14584}V této dobì, kdy je mìsíc v plné své kráse, krvácí Yasha, ze svého zranìného oka.
{14603}{14674}A znáte dùvod?
{14692}{14837}Øíká se, e spojena s další sochou, která je uctívána jednou potulnou hereckou spoleèností.
{15027}{15076}Toto je náš Boskı stráce.
{15132}{15196}Jmenuje se Ashura.
{15280}{15350}Ta socha musela bıt vytesána opravdovım mistrem.
{15350}{15396}Urèitì je velmi stará.
{15396}{15424}Zajímalo by mì, co to je za materiál.
{15438}{15469}A o èem to vypovídá...
{15525}{15560}Hrozné...
{15575}{15763}Shaoran velmi rád zkoumá a prohlíí prastaré vìci...
{15763}{15793}Omlouvám se.
{15793}{15853}Ale já tvım pocitùm rozumím.
{15853}{15923}Ta socha je velmi pìkná.
{15923}{16008}Mì se také líbí, je pøekrásná.
{16008}{16031}Dìkuji.
{16111}{16179}Ale oni si to nemyslí.
{16325}{16419}Ashura je bohem války a neštìstí...
{16419}{16563}a Yasha, kterı je uctíván zde, je bohem noci a podsvìtí.
{16563}{16589}Podsvìtí?
{16589}{16644}Svìt, kam odchází mrtvı.
{16656}{16827}Øíká se, e slzy, která Yasha prolévá, jsou varováním pøed válkou a neštìstím, které mùe Ashura pøinést.
{16827}{16869}Aha.
{16967}{17031}U je èas Souseki.
{17031}{17069}Rozumím.
{17069}{17114}Omluvte mì, musím se vzdálit
{17163}{17191}Na moment...
{17191}{17219}Ano?
{17219}{17331}Vy necháte osoby, kterı vùbec neznáte, samotnı v chrámu?
{17345}{17462}Dùvod vašeho pøíchodu, je hledání lidského porozumìní.
{17467}{17519}To je to, èemu vìøím...
{17528}{17549}Omluvte mì.
{17647}{17702}Jako by ta socha chtìla nìco øíct...
{17702}{17846}Nebo nás køikem, pøe nìèím varovat...
{17866}{17988}aspoò tak na mì pùsobí.
{18038}{18178}Nemohu uvìøit tomu, e tak krásnı bùh jako tento, pøináší válku a utrpení.
{18178}{18230}Také tomu nemohu uvìøit.
{18648}{18691}Dnešní vystoupení bylo zrušeno...
{18718}{18836}take jsme pøipravili hostinu na pøivítanou, pro naše dva hosty, Shaorana a Sakuru.
{18853}{18896}Ha, tady jste, no tak pojïte.
{18985}{19028}Proè se tam schováváte?
{19028}{19064}Zbabìlèe!
{19157}{19232}Øíkala jsem ti to u pøedtím, e je sem muùm vstup zakázán.
{19232}{19352}Mimo zákazníku, sem ádnı mu nesmí, kdyby na to pøišel šéf, mìli by jsme z toho všichni problémy.
{19366}{19424}Je mi líto, ale budeš v tom muset chodit.
{19514}{19552}Máme problém, šéfová!
{19552}{19580}Ti lidé stojí venku.
{19666}{19718}Dnes, vás odtud všechny vykopem.
{19718}{19803}Nemám ponìtí o èem to mluvíte.
{19803}{19838}Zøejmì jste se spletl...
{19838}{19873}Nedìlej, e nevíš.
{19873}{19965}Minulou noc, socha Yashi zase ronila slzy krve.
{19965}{20026}Pøedpokládám, e to má bıt chyba Ashury...
{20026}{20054}Samozøejmì.
{20055}{20120}Take, jestli neodejdete tak...
{20120}{20174}Tak udìláte co?
{20174}{20222}Tak udìláme tohle!
{20348}{20443}A vás ani nenapadne se jí dotknout!
{20443}{20491}Odprejskni!
{20513}{20593}Hned po tobì, magore.
{20631}{20722}Všichni co zde ijí, jsou èlenové rodinné herecké spoleènosti Suzuran.
{20722}{20859}Dokud tu jsem já... tak nikdo nikomu nezkøiví ani vlásek.
{20859}{20905}Správnì Suzuran, jsme s tebou.
{20905}{20965}Práší se ti od huby...
{20969}{21001}Souseki vás u neochrání...
{21055}{21103}Dorate je!
{21387}{21419}Padáme.
{21435}{21501}Zase se nìkdy stavte, hlupáci.
{21501}{21550}Ty jsi tak silnı Shaorane.
{21550}{21580}Dìkuji ti, Shaorane.
{21580}{21644}Byl jsi úasnı.
{21644}{21735}Nechtìl by jsi s námi vystupovat, Shaorane?
{21762}{21854}Jestli se dokáeš takto pohybovat, mohl by jsi zvládnout i nìjaké akrobatické kousky.
{21854}{21917}To není špatnı nápad šéfová, máte dobrı odhad.
{21917}{21971}Skvìlé... co by jsi chtìl dìlat?
{21971}{21999}Budu tì uèit.
{21999}{22071}Hej, to já ho budu uèit!
{22571}{22630}Pojïme se podívat po Shaoranovy a ostatních.
{22651}{22718}Toto Japonsko, je podobné tvému, e ano Kurosame?
{22737}{22868}Setkání s Tomoyo... proto ti tento svìt pøipomíná ten tvùj.
{22868}{22982}Neøíkej mi, e se ti stıská po domovì.
{22982}{23016}Zklapni!
{23022}{23097}Ke svım spojencùm jsi dosti chladnı.
{23115}{23158}Legraèní, e to øíkáš.
{23158}{23223}Ty také nemáš v úmyslu se dvakrát otevøít.
{23223}{23283}Tøeba ne...
{23283}{23400}Vèera, kdy Souseki vyslovil to jméno... Ashura.
{23400}{23463}Tvùj vıraz ve tváøi se zmìnil... proè?
{23497}{23544}Slyšel jsi to ne?
{23561}{23619}Má se pøihodit nìco špatného.
{23771}{23871}Boe, jako by byl úplnì mimo, pøesto ale není.
{23882}{23929}Ale Souseki...
{23929}{24039}A u jde o cokoliv, na tu hereckou spoleènost nesmíte vztáhnout ruku.
{24128}{24195}Byl nìkdo z tìch lidí zranìn?
{24207}{24283}Ne, byli jsme jediní, kteøí utrili nìjaké rány.
{24283}{24363}Byla tam jedna osoba s excelentní kopací technikou.
{24363}{24456}Vypadala jako dívka, ale byla velmi silná.
{24476}{24557}Na chvíli jsem myslel, e je to Shaoran.
{24557}{24587}Vypadalo to tak.
{24587}{24624}Ale co kdy...
{24641}{24733}je Shaoran pøevleèen za dívku.
{24733}{24771}To je absolutnì vylouèenı!
{25341}{25388}Jsi dobrı, Shaorane.
{25388}{25450}Vypadá to, e zítra budeš moci vystoupit.
{25452}{25564}A-ale... já sem pøed lidmi nìco takového nikdy nedìlal.
{25564}{25614}Ale Sakura vypadá, e u to zvládne.
{25655}{25698}Aáá, princezno!
{25927}{25984}Princezno... spíte?
{26002}{26023}Ne.
{26038}{26088}Na chvíli odejdu.
{26088}{26142}Kam chceš v tuto hodinu jít?
{26142}{26202}Jdu zkusit najít Faie a Kurogana.
{26202}{26249}Potom jdu s tebou.
{26264}{26307}Ale, u je dost pozdì...
{26307}{26335}To je v poøádku.
{26335}{26400}Prosím, chci také pomoci.
{26413}{26441}Rozumím.
{26575}{26633}Nebyla to Suzuran?
{26633}{26710}Dnes se zdála velmi smutná...
{26710}{26742}Chápu.
{26839}{26860}Kdo to byl...
{26860}{26927}Moná nìkdo z tìch lidí, ze vèerejška...
{27149}{27179}Tady jsem.
{27570}{27627}Tolik jsem se na tebe tìšila Souseki.
{27627}{27730}Já také, celı rok jsem èekal na tuto noc.
{27743}{27814}Nech mì prosím, podívat se na tvou tváø.
{28066}{28131}Pøišel jsem se omluvit za vèerejšek.
{28131}{28211}Kadı rok je to to samé, zvykla jsem ji.
{28211}{28354}Nás Ashura a váš Yasha jsou bohové, kteøí si nebudou nikdy rozumìt.
{28354}{28450}Ráda bych vìdìla, proè tì tolik miluji.
{28466}{28579}Jeden miluje druhého, ikdy oba ví, e nemohou bıt spolu...
{28579}{28642}Takovı lidé jsou... (milenci)
{28774}{28911}V tomto svìtì, kde Ashura a Yasha stojí proti sobì, není ádná monost, jak ít šastnì spolu.
{28935}{28996}Vím to.
{28996}{29115}Proto si teï pøeji, aby jsi mì nepøestával dret ve své náruèi.
{29141}{29161}Suzuran...
{29624}{29673}Je mi tìch dvou tak líto.
{29673}{29689}Ano.
{29713}{29737}Shaorane...
{29782}{29887}Poprosme Ashuru, a jsou ti dva spolu šastní.
{29917}{29948}Rozumím.
{30472}{30485}Co se to...
{30774}{30800}Ty otøesy...
{30800}{30874}Ashura a Yasha k sobì promlouvají!
{30914}{30956}Pospìš si prosím, do svatynì Ashury.
{30956}{30988}Já se také vrátím.
{30988}{31001}Rozumím.
{31124}{31145}Princezno.
{31791}{31811}Ten chlap...
{31838}{31867}Kurosame, nebe...
{31987}{32057}Trhá... se...
{32266}{32291}Princezno!
{32703}{32759}Princezno, proberte se!
{32782}{32807}Princezno!
