{2484}{2523}Ten chlap...
{2542}{2580}Kurosame, nebe...
{2686}{2741}Trhá... se...
{2968}{2994}Princezno!
{3404}{3462}Princezno, proberte se!
{3483}{3515}Princezno!
{3560}{3628}NEKONEÈNÁ BITVA
{4050}{4133}Myslíš, e to má co dìlat s princezninım pírkem?
{4133}{4195}To nevím, ale...
{4339}{4483}jako by se nìco hrozného skrıvalo za tou oblohou.
{4524}{4555}To je...
{4657}{4771}Socha Yashi opìt roní krvavé slzy.
{4771}{4837}Princezno, otevøete prosím oèi.
{4837}{4854}Princezno!
{4939}{5015}Shaorane... já...
{5030}{5056}Princezno.
{5239}{5270}Ashura!
{5481}{5555}Cítím z toho, ohromnou ízeò po krvy...
{5555}{5596}Za tou oblohou...
{5770}{5803}Pøibliuje se to...
{5846}{5923}Ashura je náš Boskı stráce.
{5923}{5992}Ashura není bùh, kterı pøináší neštìstí!
{6017}{6110}Ne, není to chyba Ashury...
{6125}{6259}Pokud by tak bylo, nemohla bych se mu podívat znovu oèí.
{6307}{6352}Suzuran...
{7483}{7506}To je...
{7660}{7765}Na tomto svìtì, se pírko nenachází...
{7770}{7873}ale v tam tom svìte jedno je.
{7989}{8014}Co se to...
{8014}{8077}Odcházíme jinam?!?
{8089}{8141}Pøecházíme do dalšího svìta!?!
{8141}{8203}Ale Kurogan a Fai...
{8550}{8587}Kdo jste?
{9021}{9084}Princezno, otevøete prosím oèi.
{9084}{9111}Princezno!
{9206}{9234}Princezno.
{9268}{9335}Já... jsem...
{9362}{9392}Všechno je v poøádku.
{9419}{9499}Já... mìla jsem sen.
{9525}{9560}Kde to jsme?
{9579}{9598}Tìko øíct...
{9870}{9899}Tak mladí...
{10111}{10177}Co dìláte na místì, jako je toto?
{10491}{10546}Nejste zranìná, královno Ashuro?
{10546}{10571}Ne.
{10778}{10833}Shaorane, ta osoba je...
{10913}{10996}Vypadá to, e nebude opìt dosaeno konce...
{11100}{11137}S klanem Yasha.
{11542}{11667}Mìsíc je za zenitem, pro dnešek je bitva u konce.
{11869}{11900}Co se to stalo?
{11900}{11954}Jsme zase na jiném místì?!?
{12106}{12226}Mùeme tam bıt jen do doby, ne mìsíc dosáhne zenitu.
{12226}{12314}Kdy se tak stane, jsme vráceni zpìt...
{12329}{12393}Na toto místo.
{12407}{12573}Jsme pozvaní jen po dobu, co mìsíc mìní svou polohu na noèní obloze.
{12590}{12676}Ten hrad vznášející se v oblacích...
{12676}{12725}My jsme tam byli?!
{12725}{12799}Ale proè jste tam bojovali?
{12799}{12920}Chcete øíct, e nevíte nic o bitvì na Mìsíèním hradu?
{12920}{12958}Co tady dìláte?
{12958}{13021}Nejste náhodou èleny klanu Yasha?
{13021}{13092}Kdyby byli èleny klanu Yasha, jejich oèi by byli záøivì èerné.
{13092}{13129}Oni jimi nejsou.
{13129}{13155}Ale...
{13155}{13201}Vemte je do mého hradu!
{13209}{13261}Rozumím, spoutáme je a...
{13265}{13288}Takto ne...
{13325}{13363}Nakládejte s nimi jako s hosty.
{13371}{13395}Ale...
{13395}{13423}Kumarayo!
{13445}{13495}Nenu mì to opakovat.
{13551}{13591}Jak si pøejete...
{13679}{13827}Ráda vás uvítam na hradì Ashura.
{14479}{14581}Zajímalo by mì, jestli to pøedtím opravdu byli Kurogan s Faiem.
{14581}{14629}Kdo ví.
{14629}{14767}Ale jestli to byli oni, tak proè nezareagovali kdy nás vidìli?
{14767}{14808}To je dobrota.
{14880}{14905}Omlouvám se, e jsem vás nechala èekat.
{15008}{15083}Chutnalo mım hostùm?
{15093}{15144}Je to vıborné!
{15165}{15203}To ráda slyším.
{15406}{15443}Je nìco špatnì?
{15456}{15556}Ten hudební nástroj... podobá se jednomu nástroji z mojí zemì.
{15687}{15722}Je to ten samí!
{15722}{15785}Je zvláštní, vidìt ho v tak cizí zemi.
{15796}{15833}Zahraješ nám nìco, Sakuro?
{15849}{15899}No, ja nevím.
{15913}{15947}Ráda bych to slyšela.
{15957}{16054}Ale, já moc dobøe nehraji!
{16094}{16139}Také bych to rád slyšel.
{16239}{16305}Pokud to bude znít špatnì, tak mì prosím zastavte.
{16508}{16560}Zní to pìknì.
{17774}{17863}Cítíš v tom svìtì pøítomnost pírka, Mokono?
{17897}{17960}Cítím velkou sílu...
{17960}{18000}A odkud?
{18000}{18068}Nejvíce tam ze shora.
{18278}{18356}Hrad vznášející se v oblacích.
{18465}{18563}Tsubasa Chronicle
{19023}{19082}Sakura ještì špí?
{19082}{19133}Ano, ještì špí.
{19133}{19185}To cestovaní ji zmohlo.
{19197}{19229}Nìco tì trápí?
{19255}{19348}Vèera jsi Sakuru po celou dobu nezpustil z oèí.
{19348}{19421}Jste tu jako mí hosté.
{19421}{19534}Nikomu v této zemi nedovolím, aby na vás vztáhl ruku
{19604}{19652}Tahle vázièka je opravdu pìkná.
{19652}{19683}Yuuko by se urèitì líbila.
{19697}{19743}Pokud chceš, staèí øíci a bude tvá.
{19751}{19789}Jùùù... dìkuju.
{19861}{19943}Mimochodem, tato zemì se jmenuje Shura, je to tak?
{19943}{20056}Ano, tato zemì je kontrlováná námi, klanem Ashura.
{20056}{20099}A co klan Yasha?
{20099}{20208}S tìmi bojujeme u velmi dlouho.
{20225}{20295}Dvì rùzné strany spolu bojují.
{20328}{20353}Nedìlej, e nevíš.
{20353}{20440}Minulou noc, socha Yashi zase ronila slzy krve.
{20440}{20507}Pøedpokládám, e to má bıt chyba Ashury...
{20507}{20535}Samozøejmì.
{20535}{20602}Take, jestli neodejdete tak...
{20602}{20655}Tak udìláte co?
{20655}{20703}Tak udìláme tohle!
{20848}{20925}A vás ani nenapadne se jí dotknout!
{20925}{20973}Odprejskni!
{20988}{21075}Hned po tobì, magore.
{21106}{21201}Všichni co zde ijí, jsou èlenové rodinné herecké spoleènosti Suzuran.
{21201}{21333}Dokud tu jsem já... tak nikdo nikomu nezkøiví ani vlásek.
{21359}{21423}Je to stejné jako v zemi Shara.
{21423}{21531}Boskım strácem herecké spoleènosti Suzuran je socha Ashury.
{21623}{21672}a ta je velmi podobná této osobì.
{21701}{21774}Klan Yasha,  v tom hradì íje?
{21774}{21807}Ne.
{21825}{22010}Klan Yasha, je stejnì tak jako my pozván, jen kdy mìsíc dosáhne zenitu.
{22010}{22115}Z nìjakého okolního království pravdìpodobnì nebudou.
{22115}{22200}A pak jste tu vy... ti kteøí nevìdí, kde e to vlastnì jsou.
{22200}{22308}Take vy bojujete s lidmi o kterıch nevíte ani odkud jsou?
{22308}{22395}Ano, u od dávnıch dob.
{22418}{22455}Proè tomu tak je?
{22463}{22599}Øíká se, e ten kdo získá vládu nad hradem, splní se mu veškerá touhy. 
{22626}{22685}Veškeré touhy?
{22704}{22874}Kvùli této legendì prolévaji klany Ashua a Yasha svoji krev u po celé vìky...
{22911}{22958}... v tom mìsíèním hradu.
{22985}{23054}Kadı po neèem touí.
{23054}{23258}Lidé co tvrdí, e ádne touy nemají, nevidí do hloubin svıch srdcí.
{23319}{23411}Po èem touíte vy?
{23476}{23546}Øíkal jsi, e jsi na cestì, je to tak, Shaorane?
{23546}{23577}Ano.
{23577}{23614}Kvùli èemu?
{23614}{23659}Nìco hledám.
{23659}{23701}A je to tady?
{23717}{23809}To nevím, ale ta šance tady je.
{23854}{23889}Mohl bych vás o nìco poádat?
{23889}{23913}O co jde?
{23913}{23992}Vemte mì sebou na mìsíèní hrad.
{24024}{24078}To místo je váleèná zóna.
{24114}{24159}Mohl bys tam pøijít o ivot.
{24177}{24209}Nezemøu!
{24227}{24303}Protoe musím nìco udìlat.
{24337}{24360}Nejde to.
{24360}{24395}Královno Ashuro!
{24410}{24452}Ne, v tìchto šatech.
{24587}{24644}Sakura se ještì nevzbudila.
{24659}{24770}Moná je to proto, e u jsme dlouho nenašli zádné její pírko.
{24878}{24967}Jdu na to... princezno
{25077}{25179}Berete sebou nìkoho, koho neznáte k mìsíènímu hradu?
{25179}{25231}Jste si tím jista, královno Ashuro?
{25242}{25278}Ne, nejsem.
{25305}{25375}Jen z toho mám takovı...
{25431}{25495}... zvláštní pocit.
{25557}{25611}Jdeme, Shaorane.
{25611}{25635}Ano.
{25902}{25947}Kurogane, Fai?
{25956}{26013}Ty je znáš?
{26028}{26095}Nejsem si tím úplnì jistı...
{26095}{26157}... ale ta monost tu je.
{26167}{26227}Ti dva jsou opravdu silní.
{26227}{26301}Pravdìpodobnì nejsilnìjší, po králi Yasha.
{26302}{26397}Ten skrèek je nepochybnì spolèenı s klanem Yasha.
{26397}{26425}Jedu se ujistit.
{26425}{26445}H-Hej, poèkej!
{26529}{26577}Fai, Kurogane!
{26594}{26741}Och, klan Ashura posílá do války u i takovı skrèky.
{26741}{26799}Vypadá to, e u nemají dostatek lidí na vedení války.
{26824}{26883}Senryuu Hikougeki.
{26824}{26883}Jako, e útok Záøícího draka - rozprašující svìtelnı útok.
{27051}{27077}Hikougeki.
{27051}{27077}Jako, e Bleskovı útok.
{27140}{27226}Take to asi nebudou Fai a Kurogan, které znám.
{27226}{27301}V tomto svìtì jsou to úplnì jiné osoby ikdy mají stejné duše jako oni.
{27320}{27391}Ale tenhle meè je 100% Souhi.
{27407}{27487}Je to meè, kterı pochází ze zemì Outo.
{27565}{27625}Vypadá to, es mùj útok odrazil.
{27625}{27679}Dvakrát se ti to ale nepovede.
{27691}{27744}Hama Ryuuoujin!
{27691}{27744}Jako, e útok Královskım draèím meèem.
{27877}{27921}To jsou Kuroganovy útoky.
{28123}{28170}Je to Souhi!
{28170}{28220}Ale tohle není Kurogan.
{28239}{28292}Odra mì, skrèku!
{28506}{28561}V pøíštích dvou úderech tì zabiju.
{28951}{29041}To není zlı, ale je to pøíliš slabı.
{29107}{29196}Tenma Kuuryuusen
{29107}{29196}Jako, e útok Nebeského záøícího draka
{29568}{29613}Jsi pøíliš pomalı.
{30054}{30129}No ne, kralovna Ashura osobnì.
{30359}{30395}Velmi dobøe.
{30415}{30431}Zhebni!
{30525}{30590}To jsou moji protivn9ci, neple se do toho!
{30788}{30821}Co je to?
{30867}{30924}Yama Tenrouken.
{30867}{30924}Jako, e útok Noèního nebeského vlka.
{31111}{31203}Øíkal jsem, e to jsou moji protivníci králi Yasho!
{31417}{31533}Jak královna Ashura, tak král Yasha jsou silní.
{31576}{31643}Velmi silní.