{3255}{3270}Co se to dìje?
{3310}{3370}Dvì vzpomínky
{3660}{3700}Kdo je to?
{3940}{3965}To je...
{4750}{4815}Potom všem Yasho...
{4830}{4855}Ne.
{6070}{6110}Proè jsi tady?
{6295}{6445}Proè jsi tady? Ty, kterého mùu vidìt jen na mìsíèním hradu.
{6760}{6780}Rozumím...
{8035}{8090}Pøíštì na mì zaútoè s úmyslem mì zabít.
{8725}{8750}Nejsi zranìnı?
{8770}{8800}Nic mi není.
{8805}{8865}Nevypadáš zrovna nešastnìji.
{8870}{8930}Je to kvùli tomu, co musíš udìlat za kadou cenu?
{9020}{9140}Taková je síla tvé touhy, Shaorane.
{9790}{9845}To jsem celou tu dobu spala?
{9850}{9910}U je ráno?? Yup, out cold.
{9960}{10030}Take se mi to zdálo. 
{10035}{10065}Mìla jsi nìjakı pìknı sen?
{10130}{10160}Já nevím...
{10255}{10275}Shaorane!
{10325}{10370}Ty jsi zranìnı! Co se stalo?
{10375}{10425}No, umm...
{10430}{10515}Shaoran šel do mìsíèního hradu.
{10520}{10540}Mokono!
{10545}{10615}Oops, nìjak mi to vyklouzlo.
{10640}{10705}Prosím, neuzavírej se pøede mnou.
{10710}{10810}Vím, e nemohu nic udìlat, ale dovol mi se o tebe starat.
{10835}{10870}Omlouvám se.
{10875}{10915}Mohu se na to podívat?
{10965}{11060}U je to velmi dávno, co mì to otec uèil.
{11065}{11110}Øíkal tomu základní ošetøení.
{11125}{11270}Ikdy nemám ádnou kouzelnou moc, jsem schopná zmírnit tvou bolest.
{11315}{11360}Dìkuji.
{11375}{11415}Mokona tì také ošetøí.
{11440}{11475}Tobì také dìkuji, Mokono.
{11480}{11550}Narazil jsi na nìco na mìsíèním hradu?
{11555}{11625}Potkal jsem se tam s lidmi, kteøí vypadali jako Kurogan a Fai.
{11630}{11690}Opravdu to byli oni?
{11695}{11805}Jeden z nich vypadal jako Kurogan a mìl meè ze zemì Outo.
{11810}{11880}Ale nezareagoval ani kdyz jsme stáli tváøí v tváø.
{11935}{12010}Oba dva mìli èerné oèi.
{12050}{12150}Ale Fai má pøece oèi modré jako safír.
{12155}{12230}A Kuropon je ma èervéné jako zajíèek.
{12235}{12355}Vypadá to, e to jsou úplnì jiní lidé, ikdy mají stejnou duši.
{12360}{12510}A kde potom jsou naši pravı Kurogan a Fai?
{12765}{12870}Zdá se, e se dostali do svìta o kterém nevíme.(kterého jsme nìchtìli)
{12900}{13010}A doteï byli ve svìtech, ve kterıch jsme je chtìli)
{13040}{13120}Relativnì bezpeènıch svìtech, správnì?
{13140}{13190}Zhatí to naše plány, pokud zemøou.
{13195}{13285}Ta vìc byla stvoøena, právì kvùli tomuto plánu.
{13305}{13420}Kvùli té vìci, jen je pohøbená v tìch ruinách, je teï musíme nechat bıt.
{13435}{13520}Ale ne na dlouho
{13595}{13700}Kvùli ní, nejsme schopni kontrolovat jejich cestu.
{13720}{13795}V závislosti na dané situaci, je tady i monost smrti.
{13800}{13830}Vím.
{13835}{13935}Dokáete porazit... Èarodìjku dimenzí?
{13940}{14015}Uèinil sem nezbytná opatøení, vedoucí k jejímu odstranìní.
{14020}{14100}Zatím ještì, ale nejsou dostateèná.
{14120}{14235}Ona je je jedinou enou, která dokáe ovládat stejnou magii jako mùj rod, Clow Reed.
{14240}{14350}Ta ená ví, jak procházet dimenzemi a posílat lidi do jinıch svìtù.
{14365}{14400}Nicménì...
{14490}{14575}... u brzy bude ta síla v mıch rukou!
{14685}{14765}Jeho pøíchod bude moná rychlejší ne jsme oèekávali.
{15205}{15235}Jsi v poøádku?
{15240}{15295}Moje oko...
{15300}{15320}Bolí tì?
{15345}{15365}Tak trochu.
{15425}{15500}P-Princezno Sakuro...
{15525}{15565}To byla pusinka.
{15570}{15610}Pusinka na oèièko!
{15645}{15715}O-Omlouvám se... já jen...
{15720}{15800}Och, ne... umm... to nic...
{15805}{15865}Nechala jsem se unést.
{15870}{15925}Nevím, proè jsem to udìlala.
{15975}{16000}Pusinka.
{16400}{16485}Myslet na jiné je pìkná všc.
{16565}{16630}Musím promyslet své další kroky.
{16665}{16725}Obzvláštì ohlednì tìch dvou.
{16955}{17035}Tahle pusinka by mohla pomoci tvému tìlu si vzpomenout.
{17050}{17090}Yuuko to tak øíkala.
{17095}{17155}Jsou dva druhy vzpomínek.
{17160}{17220}Vzpomínky srdce a tìla.
{17225}{17330}Vzpomínky srdce jsou velmi dùleité, ale tìla také.
{17350}{17460}Na jisté vìci mùe srdce zapomenout, ale tìlo si na nì vzpomene, to je ,,to´´ co øekla.
{17465}{17610}Moc tomu nerozumím, ale jeho bolavé oko jsi políbila asi proto...
{17615}{17745}... e tvoje tìlo si na to vzpomnìlo, ikdy si svá pírka ztratila.
{17750}{17900}Take do doby, ne budeš mí všechny svá pírka, tvé tìlo ti bude pomáhat si vzpomenout, Sakuro.
{17935}{18020}Dìkuji, Mokono.
{18025}{18075}Mokona chce taky pusinku.
{18230}{18333}Shibetsukade Translations
{18495}{18570}Dìkuji ti za to, e mi dìláš prùvodce.
{18575}{18620}Byl to královnin pøíkaz.
{18625}{18700}Co máš v plánu dìlat, a do toho mìsta dorazíme?
{18705}{18815}Nehodláš nás zradit a pøedat klanu Yasha nìjaké informace?
{18820}{18910}Kdyby tomu tak bylo, tak bych spíš prozkoumával hrad, ne jel do toho mìsta.
{18915}{19000}To je bl... Hmm, to je pravda.
{19020}{19080}Nejsem souèástí klanu Yasha.
{19115}{19230}V kadém pøípadì, udìlej jeden poderelej pohyb a na místì tì zabiju. Pamatuj si to!
{19255}{19280}Ano.
{19395}{19440}Nevypadáš dobøe, Sakuro.
{19495}{19525}Omlouvám se.
{19530}{19570}Dìláš si starosti o Shaorana?
{19600}{19615}Ano.
{19620}{19690}V této zemi u nìjakou dobu je, nemusíš si o nìj dìlat starosti.
{19695}{19790}Ale Shaoran pokadé jedná tak unáhlenì.
{19795}{19820}To j pravda.
{19825}{19890}Ani nemyslí na to, e je zranìnı.
{19895}{19975}Proto si o nìj dìlá Skura starosti.
{20010}{20140}Ti, jen mají velkou touhu, na sebe nehledí, dokud svou touhu nenaplní.
{20175}{20215}Proto jsou tak silní.
{20275}{20330}Pro ty co je sledují to musí bıt tìké.
{20385}{20430}Obzvláštì je-li Shaoran...
{20645}{20740}Na tom nesejde... co bys øekla koupeli?
{20750}{20810}Jeee, koupel.
{20840}{20880}Pojïme honem, Sakuro.
{20905}{20945}Koupel, koupel...
{20950}{21065}Jestli-e na to nepøišli sami, nemám dùvod øíkat jim, kdo je Shaoran doopravdy.
{21090}{21120}Nemám pravdu, èarodìjko.
{21195}{21215}Oèividnì.
{21230}{21265}Dostala jsi to?
{21270}{21395}Ano, elixír vìèného mládí. Dostala jsem ho.
{21400}{21445}Ptám se, protoe jsem tì o nìco ádala.
{21450}{21575}Tvoji prosbu se mi podaøilo splnit na poslední chvíli.
{21590}{21730}Pomocí Mokony, se mi je povedlo pøevést do tvého domovského svìta.
{21735}{21785}To bylo to, co jsi chtìla.
{21790}{21935}Kvùli plánùm toho mue jsou nuceni cestovat po rùznıch svìtech.
{21940}{22040}Teï u ale nad nimi nemá kontrolu.
{22055}{22140}Normální lidé jsou svázání rùznımi omezeními, tebe jako èarodìjky se to nìtıka.
{22145}{22205}Pøesto jen plníš lidem jejich pøání.
{22210}{22415}Pokud nejsou ádná omezení, všechno nakonec vede k úpadku. Nemohu nechat toho mue dìlat si co chce.
{22430}{22465}Královno Ashuro...
{22500}{22650}... cena za splnìní tvého skuteèného pøání je opravdu... vysoká.
{22715}{22805}Ostatní... je u...
{22890}{22920}... na tobì.
{23120}{23255}Jeden s èernımi vlasty a druhı s blond a oba vyššího vzrùstu?
{23260}{23315}Vidìl jste je tu?
{23320}{23360}Ne, nevidìl.
{23410}{23535}Kdyby je tu nìkdo vidìl, tak a o tom podá zprávu na hrad.
{23540}{23575}Je to všem jasné?
{23580}{23645}Ano, samozøejmì.
{23645}{23695}Za zdrení se vám omlouváme.
{23700}{23715}To je vše.
{23740}{23790}Jdeme, vrátime se na hrad.
{23795}{23815}Ano.
{23845}{23870}Co se dìje?
{24100}{24125}Hej, jsi v poøádku?
{24130}{24180}A-Ano.
{24370}{24395}Co je to?!
{24765}{24830}Nechcete sebou vojáky? Co tím myslíte?
{24835}{24925}Dnešní noèní útok provedu jen já a Shaoran.
{24930}{24965}Ale...
{25000}{25035}U jsem se rozhodla.
{25040}{25090}Potom mì tedy nechte jít s vámi.
{25095}{25240}Pøísahal sem, e budu stát vdy pøi vás.
{25245}{25370}Den, kdy nebudu stát po vašem boku, bude znamenat mojí smrt.
{25375}{25450}Prosím, nechte mì jít s vámi.
{25505}{25560}Váím si tvé loajality, Kumaro.
{25565}{25585}Dìkuji.
{25610}{25670}Smíš mì doprovodit.
{25675}{25720}Dìkuji vám.
{25730}{25845}Ale bez ohledu na to, co se dnes v noci stane, nezemøi.
{25930}{26000}Kumara je s tím u obeznámen. Jak se rozhodneš?
{26040}{26065}V poøádku.
{26095}{26200}Jestli takhle budeš dál pokraèovat, jediného èeho dosáhneš bude, e rozèílíš všechny kolem sebe.
{26300}{26380}Skrıváním nièeho nedosáhneš.
{26495}{26540}Dobrá, pùjdeme.
{27185}{27200}To jsou...
{27360}{27415}Také pøišli bez svıch vojákù?
{27590}{27625}Máš se, skrèku?
{27735}{27830}Pamatuješ co jsem ti øíkal... zaútoè na mì s úmyslem mì zabít.
{28180}{28190}Co je to?
{28305}{28315}Moje ruce...
{28485}{28540}Moje ruce se pohnuli sami od sebe.
{28790}{28810}Paní.
{28945}{28965}Královno Ashuro!
{28970}{29000}Nechoï za mnou!
{29010}{29025}Ale...
{29060}{29100}Øekla jsem, nechoï za mnou!
{29640}{29685}Králi Yasho, skonèeme tento boj.
{30020}{30045}Sakuro?
{30440}{30530}Pøišla jsem si splnit své pøání.
{31465}{31510}To je zranìní, které jsem ti zpùsobila.
{31945}{31965}To je...
{32260}{32300}Princeznino pírko!