{1000}{2000}Naprosto dementní díl, doporuèuju vynechat a nekoukat!
{2490}{2520}Vypadá to, e jsme pøistáli.
{2535}{2590}Tohle není mùj svìt.
{2600}{2660}Ani mùj svìt, ze kterıho sem pøišel, to není.
{2680}{2725}Take to je novı svìt.
{2780}{2870}UCHHH.
{2900}{2950}Vypadáte dosti nezvykle, princezno.
{2980}{3025}Ty také, Shaorane.
{3055}{3100}Kurosam, vypadá taky divnì.
{3105}{3135}Ty taky!
{3170}{3195}Co se to...
{3245}{3275}... tu dìje?
{3280}{3345}Spisovatel, Mokona
{3585}{3640}Velmi vtipnì provedenı svìt.
{3645}{3675}Co tím myslíš?
{3680}{3790}Kdy se podíváš na tohle mìsto, tak je docela vhodné, e vypadáme zrovna takhle.
{3840}{3855}To je...
{3920}{3980}Dámy a pánové, herecká spoleènost Suzuran, dorazila pøímo k vám!
{3985}{4045}A dnešní pøedstavení je pro všechny zcela zdarma.
{4050}{4160}Proto neváhejte a pøijïte nás navštívit.
{4165}{4250}Hej, proè to øíkaš tak monotónì?
{4255}{4355}Nezveš na to pøedstavení mrtvoly, zapoj do toho i srdce!
{4360}{4380}A-Ano.
{4385}{4450}Dámy a pánové, herecká spoleènost Suzuran, dorazila pøímo k vám!
{4455}{4580}A dnešní pøedstavení je pro všechny zcela zdarma.
{4455}{4580}Vypadá to, e Souseki a Suzuran jsou pøáteli i v tomto svìtì.
{4585}{4610}Vypadá to tak.
{4640}{4680}Nechte u toho
{4685}{4830}Hele, ty bílej manju, mohl bys nám vysvìtlit proè vypadáme tak, jak vypadáme?
{4870}{4885}Ach.
{4910}{4970}Uch, och, ano.
{4975}{5015}Kde je Mokona?
{5715}{5790}Jsi tam Mokono? Jestli ano, odpovìz.
{5795}{5820}Jak to jde?
{5860}{5900}Vypadá to, e tady není.
{5905}{6000}Naposledy jsme pøistáli v jiném svìtì na rùznıch místech.
{6020}{6075}Podívejme se ještì támhle.
{6265}{6310}Ruiny?
{6325}{6415}Vzpomìla jsem si na nì po pøijetí posledního pírka.
{6475}{6550}Vidìla jsem je ze zámku v poušti.
{6555}{6680}Ty ruiny se vdy v píseøné bouøe jakoby ztratily a nìkdy se pøi tom tøásla i zem.
{6710}{6725}Témìø jako by...
{6810}{6925}... se ty ruiny snaily vyrvat ze zemì a odlétnout.
{6970}{7100}Nìco podobného u jsem døív vidìl v zemi Clow.
{7115}{7190}Och, rozumím, to je asi tam, kde jsi il døív, viï?
{7300}{7320}No vlastnì...
{7335}{7410}Moná jsi velmi, velmi dùleitá osoba...
{7935}{7955}Dìje se nìco?
{7980}{8045}Ne, ne, kdepak.
{8105}{8135}Pojïme, princezno.
{8430}{8475}Uch, kde to jsem?
{8480}{8510}Shaorane?
{8515}{8555}Sakuro?
{8560}{8580}Fai?
{8585}{8625}Kurorine?
{8730}{8815}Ten zpropadenej bìlásek! Kde jen mùe bejt?
{8820}{8950}Rozumíme jeden druhému, take asi nebude daleko.
{8950}{9025}A si odpoèineme, mìli bysme ho jít zase hledat.
{9030}{9075}Podívej, Shaorane.
{9705}{9740}To je Sakuøino pírko.
{9770}{9860}Mokona ho našel úplnì sám. Jsem prostì úasnı.
{10045}{10155}Shaoran, Sakura, Fai, Kurogane?
{10190}{10255}To pero má kouzelnou moc.
{10260}{10275}Kdo jste?
{10375}{10430}Jsem spisovatelka.
{10455}{10475}Spisovatelka?
{10475}{10660}Ano, moje práce je bavit lidi za pomoci barevnıch ilustrací a smyšlenıch pøíbìhù.
{10665}{10705}Smyšlenıch pøíbìhù?
{10735}{10870}Jako autorka, mohu vytvoøit jakıkoliv svìt a dìlat si s ním co chci.
{10885}{10960}Bez ohledu na tok èasu.
{10985}{11050}Vy mùete také, ovládat tok èasu?
{11065}{11115}Uvnitø pøíbìhu, ano.
{11120}{11155}To je úasné.
{11160}{11170}Ano.
{11175}{11255}Ale tohle je Sakuøino pírko.
{11275}{11410}Shaoran ho strašnì moc hledá. Je to velmi drahocenná vìc.
{11455}{11545}Prosím, vrate Sakuøe její pírko.
{11615}{11750}Ovšem, pøedtím ale, je tu ještì jedna vìc.
{11770}{11850}Musíme zachránit všechny úèastníky, tohoto pøíbìhu.
{11885}{11955}Ech, Sharaona a ostatní.
{11960}{12105}Ti, co jsou ve svìte tohoto pøíbìhu, jsou právì teï jeho souèástí.
{12110}{12325}Ten svìt, byl vytvoøen perem, jen je defacto Sakuøinım pírkem.
{12345}{12415}A jak jim tedy mùeme pomoct?
{12440}{12605}Pomocí kouzelného pera mùeme ovlivòovat dìj pøíbìhu a dostat je z nìj ven. 
{12655}{12770}Nicménì, aby jsme toho byli schopni, potøebujeme nìkoho se silnım srdcem, které v nì vìøí. A proto...
{12930}{13025}... budeš od této chvíle urèovat dìj pøíbìhu ty.
{13030}{13130}Èistá mysl, snaící se je chránit, dokáe pero rozpohybovat.
{13150}{13225}Ech?! A to má bıt, Mokona?
{13275}{13305}Fai, máme problém!
{13330}{13360}Co se stalo?
{13420}{13445}Kurogan...
{13460}{13570}Zatracenì, nech mì! Nevejkej mì!
{13710}{13735}Och, mùj boe.
{13915}{13940}A tady, to je.
{14195}{14275}Takhle jsem to nechtìl!
{14280}{14505}Kouzelné pero, pøepisuje to, co cítíš, musíš se více soustøedit.
{14510}{14550}Je to velmi tìké.
{14575}{14665}Mohu zmìnit prostøedí, ve kterém, Shaoran a ostatní jsou?
{14710}{14735}Co tím máš na mysli?
{14755}{14805}Mokona ví o jednom pøekrásném místì.
{14810}{14930}Umoní mi to, více se koncetrovat a vytvoøit poøádnı pøíbìh.
{14950}{14975}Pak je to v poøádku.
{15165}{15230}Och, prostøedí kolem nás mizí!
{15235}{15275}Co je tohle, k èertu, za svìt?
{15280}{15345}Drte se u mì, princezno.
{15350}{15375}Dobøe.
{15400}{15525}Dr se, Sakuro. Mokana se bude snait získat tvoje pírko, tak jako to dìlá, Shaoran.
{15635}{15675}C-Co se to...
{15980}{16080}Shibetsudake Translations
{16215}{16225}Vstyk!
{16240}{16250}Úklon!
{16280}{16295}Sednout!
{16365}{16430}Teï zkontrolujeme docházku! Jsou tady všichni?
{16470}{16585}Pojem ,,iruka´´ mùe znamenat ,,Jsi tady´´ nebo také ,,delfína´´.
{16470}{16490}Delfíni?
{16540}{16585}Právì jsem dostal skvìlı nápad.
{16660}{16775}Nyní vám pøedstavím, vašeho nového spoluáka. Vejdi!
{16835}{16905}Uch, toho jsem u nìkdy vidìla.
{16945}{17010}Jmenuji se Shaoran, tìší mì, e vás poznávám.
{17015}{17060}Posaï se támhle!
{17100}{17175}Ahoj, já jsem, Sakura.
{17195}{17235}Je hezké, tì opìt vidìt.
{17423}{17663}V pøíbìhu napsaného, Mokonou si, Sakura bude, Shaorana pamatovat.
{17675}{17781}U si vzpomínám, chodili jsme spolu do školky.
{17781}{17843}Dlouho jsme se nevidìli, jak se máš?
{17852}{17886}Dobøe.
{17886}{18032}Hele, pamatuješ si, jak sem øíkala, e si tì jednou vezmu, Shaorane?
{18046}{18145}Ano, myslel jsem na to hodnìkrát.
{18456}{18576}Sice to bude ohrané, ale Sakura a Shaoran, musí mít pìknı vztah.
{18615}{18713}Take teï iješ sám?
{18713}{18799}Ano, mùj otec je teï v cizinì a zkoumá tam prastaré ruiny.
{18799}{18849}A jíš poøádnì?
{18849}{18917}Já doma moc nevaøím.
{18917}{19001}V tom pøípadì k tobì pøíjdu a nìco ti uvaøím
{19047}{19092}Ber.
{19127}{19145}Fakt?
{19165}{19177}Jasnì.
{19677}{19724}A teï do toho pøidám další osobu.
{19724}{19756}Baf!
{19756}{19819}Lekli jste se?
{19819}{19991}Kdo je to? Uèitel Fai, pracující na vìdìckıch projektech a jen je velmi oblíbenı u dívek. 
{19991}{20064}Dìkuji, za velmi pìkné pøedstavení mé osoby.
{20064}{20156}Take, ty jsi Shaoran a tvım koníèkem je zkoumání prastarıch ruin, je to tak?
{20156}{20245}To je pìkné a jen tak mimochodem, mohu se na nìco zeptat?
{20245}{20322}Take, mùj pøítel pracuje na vykopávkách u ruin a má problémy...
{20322}{20389}...  s dešifrováním starodávného textu. Mohl bys mu s tím pomoci?
{20389}{20428}Pokud ano, pospìšme si a pojïme.
{20445}{20492}Tak honem, honem.
{20547}{20592}P-Poèkejte...
{20708}{20775}Take... tohle jsou ty ruiny?
{20775}{20804}Ano, jsou.
{20826}{20867}Jsem archeolog, Souseki.
{20867}{20919}A já jeho asistenka, Suzuran.
{20919}{20965}Take, ty jsi, Shaoran?
{20979}{21086}Ano, jakı starodávnı text nemùete dešifrovat?
{21103}{21123}Tento.
{21164}{21342}Snad to dokáe, ten text nedokázalo pøeloit mnoho archeologù, vèetnì nás dvou.
{21342}{21515}Nemyslím, e to dokáe pøeloit, ale drím mu všechny palce, je to naše poslední nadìje.
{21515}{21537}Mám to.
{21558}{21570}Tak rychle?
{21589}{21652}Je to varování...
{21652}{21713}... aby se nikdo nedotıkal zlaté vázy.
{21713}{21853}Pokud se té vázy nìkdo dotkne, zlé síly se uvolní a èernı démon znièí tento svìt.
{21865}{21901}Èernı démon?
{21901}{21946}Jaká zlatá váza?
{21946}{21992}Není to tahle vìc?
{22506}{22566}Co to...
{22718}{22750}To bylo u školy.
{22882}{22967}Gao.
{22993}{23035}Kurorin, vypadá skvìle.
{23107}{23150}Gao.
{23150}{23176}Honem, utíkejte.
{23190}{23270}Poèkejte, je tu ještì dovìtek.
{23294}{23472}Opìtovné zapeèetìní démona je moné, pokud se zamilovaní lidé políbí. 
{23472}{23528}Polibek, take...
{23528}{23585}Och, to je ten slavnostní ceremoniál s fazolkami.
{23528}{23610}Slovem ,,Seppun´´ se myslí polibek, ale Fai má namysli slovo ,,Setsubun´´...
{23610}{23703}... co je Japonskı slavnostní ceremoniál, konající se v únoru, ve kterém se pouívají fazole.
{23585}{23627}Je to polibek.
{23649}{23703}Snail jsem se bıt vtipnı, ale oni to nepochopily.
{23703}{23788}No nic, budu dál pokraèovat ve své roly.
{23805}{23903}Shaorane, Sakuro, musíte zachránit svìt.
{23903}{23983}Právì teï a tady, polibte se!
{23983}{24042}COE?
{24247}{24268}Paprsek!
{24859}{24885}Paprsek!
{24973}{25008}Shaorane.
{25072}{25105}Sakuro.
{25555}{25632}Suzuran... já...
{25632}{25674}Mistøe...
{26188}{26207}Gao?
{26513}{26579}Garururururu!
{26628}{26659}Paprsek!
{26708}{26736}Gao?
{27016}{27040}Dokázali jsme to.
{27537}{27578}Uch, kde to jsme?
{27578}{27610}Mokono.
{27631}{27675}Ahojky, všichni.
{27675}{27828}Hej, bìlásku, kam ses zase zašil? Hledali jsme tì a...
{27869}{27962}To je divnı, nemùu si na nic vzpomenout.
{27982}{28093}Opravdu... co jsme vlastnì celou tu dobu dìlali.
{28093}{28172}Tadá... tady ho mám.
{28172}{28208}To je...
{28208}{28263}Ty jsi ho našel, úplnì sám, Mokono?
{28263}{28384}Ne-e, sám ne, pomohla mi jedna pìkná sleèna.
{28384}{28518}Mìla moc, ovládat vše co chtìla, ve svìte, kterı vytvoøila.
{28528}{28628}Øíkala, e uvnitø tohoto svìta, mùe dokonce ovládat i èas.
{28671}{28704}Ovládat èas?
{28729}{28838}Hele, Shaorane, je moné, aby jsme byli stále ve svìte, o kterém jsme si mysleli, e jsme ho u opustily?
{28892}{29055}Naše pøítomnost v zemi Shura, která pøedcházela zemi Shara, zmìnila souèasnost.
{29069}{29219}I kdy všechno dopadlo dobøe, nic to nemìní na tom, e jsme pøepsali tok èasu.
{29219}{29322}Take, otazka zní, jestli nám nebylo dovoleno zmìnit budoucnost, která mìla nastat.
{29322}{29413}Moná se teï zase vrátíme do minulosti.
{29413}{29569}Ale jestli budeme takto dál pokraèovat, nezmìníme historii i v jinıch zemích?
{29615}{29745}I kdyby to tak bylo, nic s tím teï neudìláme.
{29759}{29781}Ale...
{29800}{29903}Musíme to teï hodit za hlavu.
{29932}{29998}Je tu toti nìco, co musíš udìlat a ve svém úsilí nesmíš polevit.
{30016}{30094}To jestli pøepsání historie je dobré nebo špatné, se mùeš zabıvat pozdìji
{30094}{30205}Tím pøiznávám, e v souèasnım postavení, s tím stejnì moc neudìláme.
{30254}{30275}Fai.
{30298}{30398}U sis promyslel co budeš dìlat dál?
{30435}{30507}Najdu a získám všechny Sakuøina pírka.
{30526}{30606}A u se stane cokoliv, musíme pokraèovat dál.
{30618}{30733}Také øekla, e teï mùe v klidu odejít.
{31042}{31121}Moná, e to u...
{31147}{31245}Chtìl bych s ní napsat spleènı pøíbìh, ale u to asi nepùjde.
{31270}{31346}Zapomìl jsem jí vrátit èepièku.
{31363}{31447}Chtìl by sis to pírko na chvíli pùjèit, Mokono?
{31476}{31579}Do doby, ne si na ní vytvoøíš vzpomínku.
{31626}{31649}Sakuro.
{31679}{31728}To je v poøádku, e ano, Shaorane?
{31728}{31749}Ano.
{31764}{31855}Dobøe, vrátím ti ho hned jak pøejdeme do dalšího svìta.
{31980}{32043}Mokona Modoki se u nemùe doèkat.