{2525}{2590}Pøešli jsme do nového svìta.
{2592}{2670}Fajn, vypadá to jako pìkné místo.
{2673}{2748}Dovol mi, vrátit ti tvé pírko, Sakuro.
{3045}{3076}Jste v poøádku?
{3113}{3136}Ano.
{3148}{3195}Och ne, podívejte.
{3640}{3714}Nebezpeèná cesta
{4015}{4128}Omlouvám se, stalo se to proto, e jsem byl neopatrnı.
{4130}{4227}Neomlouvej se, není to tvoje chyba.
{4253}{4300}Cítíš pøítomnost pírka, Mokono?
{4340}{4438}Je daleko pøed námi a pohybuje se velmi rychle.
{4538}{4573}Co budeme dìlat?
{4588}{4639}Tímhle tempem...
{4868}{4910}Vypadá to jako autobus.
{4916}{5002}Autobus je obdélníkovı automobil slouící k pøepravì lidí, správnì?
{5012}{5089}Nìco podobnıho jsme u vidìli pøedchozích svìtech, ve kterıch jsme byli.
{5110}{5173}Tøeba v republice Hanshin nebo ve svìtì Piffle.
{5180}{5248}Jene, tohle nikdo neøídí.
{5254}{5283}Myslím, e je to má automatické øízení.
{5338}{5382}Vítejte na lince Student Agency.-)
{5384}{5442}Pøedtím ne vstoupíte, prosím zaplate.
{5460}{5513}Vypadá to, e budeme potøebovat peníze.
{5515}{5652}Zrovna jsme tu pøistáli, ádné peníze u sebe nemáme.
{5665}{5697}Co budeme dìlat?
{5698}{5732}Mì se neptej.
{5746}{5773}To je v poøádku.
{5816}{5861}Já to za vás zaplatím.
{5880}{5929}Nastupte si.
{5945}{5976}Ty jsi...
{6007}{6144}Prosím, nastupte si. Prosím, dovolte mi vám pomoct.
{6215}{6273}Co se dìje, Shaorane?
{6274}{6321}Vypadá to, e dùvod je na snadì.
{7576}{7608}Take ten èlovìk je...
{7616}{7643}Pøesnì.
{7700}{7715}To je...
{7743}{7772}Ty ho znáš?
{7784}{7877}To je ten dìda, co nám prodal meèe v zemi Outo.
{7892}{7994}Vypadal jako hodnej staøík, ale vùbec nám nedal slevu.
{8264}{8360}To je ten dìda, kterı ti zpùsobuje tolik problémù?
{8370}{8502}Ano, všechno to zaèalo pøed tøemi dny, kdy na mì promluvil.
{8522}{8677}Ale jakmile jsem se s ním dala do øeèi, zaèal mluvil úplnì z cesty.
{8689}{8805}Aha, take proto chceš, aby jsme ti pomohli.
{8816}{8861}Mohu vás o to poprosit?
{8874}{8925}Jsou tu i jiní cestující.
{8950}{9083}Jene a u na nìj promluví kdokoliv, sotva otevøe oèi.
{9145}{9213}Tak co vy na to?
{9225}{9285}To nebude problém.
{9287}{9412}Zvláštì pro Kurosama. Jestli je tu nìkdo, kdo to umí se starımi lidmi, tak je to on.
{9416}{9471}Je to nejlepší øeèník na svìtì.
{9475}{9509}Co to zase meleš?!
{9510}{9641}Och, skuteènì? To je skvìlé, dìkuji.
{9657}{9735}Navíc, vlastnì sledujeme vaše pírko.
{9736}{9765}Ano.
{9770}{9870}Jestli ucítíš nìjakou zmìnu v intenzitì vlnìní pírka, dej nám prosím vìdìt, Mokono.
{9878}{9908}Rozkaz!
{10465}{10525}Pøicestovali jste z jiné zemì?
{10532}{10645}Ech, ano, vlastnì jsme jich procestovali u nìkolik. 
{10690}{10718}To je úasné.
{10725}{10782}Ano. Nìkdy je to, ale velmi obtíné.
{10790}{10865}Ne, mám na mysli... to jak o tom mluvíš.
{10892}{11009}Zní to, jako bys mì znala od malièka, Sakuro.
{11018}{11155}Och, omlouvám se, ale kdy jsem tì dnes poránu vidìla, tak...
{11165}{11342}Och, ne, to je v poøádku. Ráda bych se s tebou bavila normálnì.
{11400}{11430}Samozøejmì.
{11628}{11668}ivot je...
{11705}{11850}ivot je jako... tekoucí øeka.
{11855}{11892}Uch, ano.
{11926}{11955}To je pravda.
{12028}{12090}ivot je...
{12122}{12274}ivot je jako...  svázané lano. 
{12282}{12353}Uch, ano, to je pravda.
{12412}{12508}Dokonce i Kuropon má problémy s pochoponemím slov toho dìdeèka.
{12520}{12558}Vypadá to tak.
{12585}{12635}Co pírko, Mokono?
{12645}{12758}Necítím ádnou zmìnu, poøád je pøed námi a velmi rychle se pohybuje.
{13405}{13500}Chtìla bych vrátit ty èasy.
{13595}{13745}Asi tak za hodinu budeme projídìt kolem tohoto odpoèívadla.
{13760}{13833}A tenhle autobus, tam zøejmì zastaví.
{13835}{14008}Ano, a tam dorazíme, budeme mít tak dvì minuty, ne tenhle spoj znovu vyrazí na cestu.
{14015}{14102}Take, potøebujeme nìjakı plan, kterı nám umoní získat zpìt pírko bìhem dvou minut.
{14106}{14125}Ano.
{14152}{14192}Co to, k èertu, vyvádíš?
{14262}{14298}Co tam dìláš?
{14305}{14370}Ty nás špehuješ.
{14386}{14430}Ne, ani ne.
{14480}{14608}Vy po nás nejdete, e ne?
{14638}{14668}Co tím máš na mysli?
{14700}{14782}Opravdu, po nás... nejdete, e ne?
{14790}{14846}Díky bohu, e je to tak, jak jsme si mysleli.
{14865}{14965}Dobøe, potom se nenechte rušit, omlouvám se.
{15000}{15070}Co je to s ním?
{15095}{15145}Tak co, Shougo?
{15158}{15280}V poøádku, jsou to sice cizinci, ale nemají s námi nic spoleèného.
{15327}{15355}To je dobøe.
{15410}{15478}Hele, Shougo.
{15518}{15624}To co jsme udìlali nebylo špatné, správnì?
{15670}{15700}Ano.
{15808}{15878}Je v tom hodnì ivota.
{15926}{15984}Pírko se zastavilo, Shaorane.
{16440}{16485}Cítíš pøitomnost pírka, Mokono?
{16486}{16523}Cítím ho pøed námi.
{16605}{16620}To je...
{16720}{16758}To se mùe stát jenom nám.
{16820}{16840}Mokono!
{16888}{16928}Co je to?
{16938}{17048}Ti chlápci se bavili o získání nìjakého pírka nebo co.
{17060}{17075}Pírko?
{17210}{17228}Támhle je!
{17365}{17408}Honem, Shaorane.
{17622}{17734}Shibetsudake Translations
{17965}{17995}Pus se , Mokono!
{18335}{18364}Shaorane.
{18580}{18605}Shaorane.
{18770}{18815}V poøádku, hotovo.
{18832}{18860}Dìkuji.
{18862}{18934}Um, proè jsi udìlal nìco tak lehkomyslného?
{18955}{19027}To, kvùli tomu pírku?
{19052}{19078}Jak to, e o tom víš?
{19088}{19228}Øekli mi to ti lidé se sluneènımi brılemi, prı jste bavili o získání nìjakého pírka.
{19231}{19260}Rozumím.
{19264}{19350}Nevadilo by vám, kdybyste mi o tom øekli víc?
{19416}{19575}Nemohu ti øíct všechno, ale cestujeme kolem svìta, aby jsme našli pírka.
{19610}{19732}Ty pírka jsou pro mì velmi dùleitá.
{19745}{19892}Kvùli tìm pírkùm, dìláte takové nebezpeèné vìci jako pøed chvílí?
{19900}{20072}Ano, za získání tìch pírek jsem schopnı udìlat cokoliv.
{20222}{20270}Jsi v poøádku, Shaorane?
{20274}{20291}Ano.
{20310}{20479}Shaoran se kvùli Sakuøe nièeho nebojí. Patrnì jí...
{20572}{20602}... miluje.
{20644}{20725}Mìla bych jim nìjak pomoci.
{20905}{20935}Tak co vy na to?
{20962}{21049}Pomùeme najít Sakuøe její pírko?
{21078}{21182}Rádi bychom, ale nemùeme jim pomoci, je nám líto.
{21200}{21376}Ano, jak øekl Shouga, máme své vlastní problémy... a nemùe nic dìlat.
{21385}{21464}Och? Vy dva.
{21472}{21522}Øíkals nìco, dìdku?
{21555}{21660}Tady nejste venku, tak proè si nesundáte ty barevné brıle?
{21682}{21723}Pøestaòte nás takhle strašit.
{21738}{21814}Promiòte, ale nemohu si pomoci.
{21835}{21938}Take jsme náhodnì nastoupily do tohoto autobusu?
{21950}{21968}Ano.
{21970}{22000}To je pravda.
{22041}{22171}Nemohu si pomoci, ale zní to, e to zase taková náhoda není.
{22205}{22312}Vše souvisí se vším a i tady je nevidelné spojení.
{22329}{22603}Není to náhoda, e jsme se tu všichni potkali. Moná jsme se tu setkali proto, e máme spoleènì nìco udìlat.
{22847}{22902}Na tomto svìtì, ádné náhody neexistují.
{22913}{22985}Vše je nevyhnutelné.
{23017}{23048}Ta slova...
{23185}{23263}Nicménì, náhody na svìtì neexistují.
{23585}{23810}Hezká pohádka, ale nejsem typ èlovìka, kterı na všechno hned skoèí, take, je mi líto.
{23847}{23866}Promiòte.
{23910}{24195}ivot se mùe zdát místy prázdnı a aèkoliv bych rád øekl, e vám pomohu, nejsem nic víc, ne vetchı staøec.
{24210}{24350}Kdybych byl o dvacet, tøicet let mladší, bez váhání bych pomohl.
{24390}{24498}Dìkuji, nic se nedìje.
{24550}{24575}Yuzuriho?
{24610}{24770}Omlouvám se, ale lidé tu jsou pøíliš lhostejní, take nepomohou.
{24785}{24811}Nedìlej si s tím zbyteèné starosti.
{24820}{24886}Tvé snahy si velmi ceníme.
{25005}{25175}Prosím, odveï mì pryè do mìsta vìtru na druhé stranì èasu.
{25180}{25304}Splò tím mé pøání...
{25318}{25510}... nevinné jak bílá kvìtina.
{25640}{25776}Vezmi mou ruku svımi jemnımi prsty  a odveï mì pryè.
{25779}{26167}Veï mì do nitra svého, abych s tebou mohla bıt.
{26232}{26399}Dokonce i bez šepotu v tvé písni, v tomto osudném odpoledni...
{26410}{26560}... se dva milenci vìdomì spojí v jedno.
{26565}{26795}Aby poprvé zjistili, co je skuteèné štìstí.
{26812}{26970}Odveï mì pryè.
{27586}{27616}Zastavili jsme?
{27620}{27732}V této zemi, je zakázáno jezdit v noci.
{27752}{27773}To znamená...
{27786}{27843}Pírko se u také nepohybuje.
{27973}{28026}To by mohla bıt naše šance.
{28029}{28115}Hej, bìlásku, jak daleko je od nás pírko?
{28129}{28224}Pøesnì to nevím, ale vzdálenost, kterou by jste za noc ušli, to rozhodnì není.
{28225}{28398}Varování! Varování! Zjištena neregistrovaná vozidla. ádáme cestující, aby neopušteli autobus.
{28412}{28481}Neregistrovaná vozidlá? Neøikejte mi...
{28495}{28521}Jsou tady.
{28548}{28577}Koho tím myslíte?
{28872}{28936}Je to silnièní gang a jsou ozbrojeni.
{28960}{29058}Pøepadávají automobily na této silnici a okrádají cestující o jejich vìci.
{29061}{29130}Ne! Já se bojím, Shougo!
{29146}{29319}To je v poøádku. Tento autobus je vybaven nejnovìjším bezpeènostním systémem.
{30299}{30330}To není moné!
{30420}{30479}Zdá se, e naše ivoty jsou u konce.
{30483}{30505}Dìláš si ze mì srandu?
{30515}{30572}Zrovna se na povedlo utıct.
{30584}{30633}Nemùeme tady zemøít!
{30823}{30844}Shaorane?
{31033}{31060}Postarám se o to.
{31072}{31091}Je to nebezpeèné.
{31110}{31156}Nemusíš se u vrátit.
{31165}{31226}Beru to navìdomí.
{31308}{31387}Chce nás chránit. On...
{31447}{31501}Ta také, ale...
{32067}{32099}Kurogane...
{32125}{32214}Planuješ získat jednu z tìch vìcí a pak na ní dojet pro pírko.
{32379}{32460}Je snadné odhadnout to, na co myslíš.
{32515}{32530}Ano.
{32592}{32605}Jdeme?
{32614}{32631}Ano.