{2392}{2458}Tohle je zemì Kishim.
{2458}{2519}Co to tu k èertu smrdí?
{2519}{2586}Sova mohu dıchat.
{2586}{2639}Urèitì jsme na místì kde ijí démoni.
{2648}{2734}Jsi velmi smìlı, kdy øíkáš nìco takového, hmyze.
{2821}{2855}U zase je v jiné...
{2874}{2981}Spotøebovala jsem veškerou svou sílu, na to, abych nás sem pøenesla.
{3009}{3155}Jestli se nemılím, hledáte pírko s kouzelnou mocí, je to tak?
{3155}{3180}Ano.
{3180}{3264}Takové pírko v tomto svìtì je.
{3264}{3341}A je to také dùsledek, všech tìchto porblémù.
{3575}{3677}Všechno se vyjasní, jakmile získáte zpìt to pírko.
{3677}{3761}Detaily vám øeknu cestou.
{3761}{3816}Tak, pojïte za mnou.
{3833}{3905}Podstata Hijutsu
{4049}{4110}Tohle je opravdu divnı svìt.
{4139}{4250}Mokona tu není a pøesto spolu mùeme bez problémù mluvit.
{4250}{4319}Máš pravdu, to je divnı.
{4564}{4618}Svìt za zrcadlem?
{4618}{4703}Uvìdomil jsem si to kdy Shaoran a ostatní zmizeli.
{4732}{4790}Podívej se na tohle.
{4810}{4887}Tohle je svìt kde jsme teï.
{4887}{4951}Jùùù, docela prostı svìt.
{4951}{4998}To nesniuje kvalitu mé velekresby!
{4998}{5020}A tohle...
{5099}{5158}... je svìt, kde ije Kishima.
{5158}{5203}Teï u tomu rozumím.
{5218}{5378}Pøestoe to jsou dva rùzné svìty, tak jsou defacto spojené.
{5378}{5404}Správnì.
{5413}{5505}Jedinı rozdíl je v tom, e jeden svìt, je zrcadlovì pøevrácenou kopií toho druhého.
{5505}{5613}Take je moné, e Shaoran a ostatní jsou velmi blízko nás.
{5636}{5665}Zrcadlo...
{6105}{6231}Stalo se to neldouho poté, co se naše cesty rozdìlily.
{6283}{6339}Otèe!
{6358}{6400}A teï ty.
{6400}{6428}Pøiprav se.
{6430}{6464}NE!
{6481}{6545}ádám tì, ušetøi mì.
{6545}{6612}Nemá smysl, abys ádal o ušetøení svého smrdutého ivota.
{6626}{6819}Teï zaplatíš za to, e sis dovolil mì vìznit. Mì, královnu tohoto svìta.
{6975}{7005}Co to...
{7063}{7090}Zatracenì!
{7165}{7256}Dej mi sílu, mocné pírko!
{7461}{7519}Ryoshiho syn má princeznino pírko?
{7519}{7549}Bohuel.
{7549}{7597}Pravé teï ho má ve své moci.
{7597}{7680}A kde je ten imbecil teï?
{7680}{7715}Támhle.
{8213}{8326}Dokud mám tohle pírko, jsem nepøemoitelnı.
{8365}{8416}Všechno je tak, jak jste si pøál.
{8496}{8582}Ti špinavı lidskı psi se teï zamìøili na naší zemi.
{8582}{8624}Pøišel èas bojovat.
{8754}{8883}To jsou ty démoni, co se chtìj stát mımi vojáky?
{8883}{8969}Co dìlá lidskı pes jako jsi ty na tomto hradì?
{8969}{9014}Buïte zticha, démoni!
{9014}{9081}Od teï budete mımi poskoky!
{9081}{9113}Cos to øekl?
{9133}{9240}Tyto drahokamy, které byli vytvoøeny z duší lidí, jsou opatøeny Hijutsu.
{9240}{9371}Pomocí nich vás budu moct snadno ovládat.
{9406}{9454}Proè bys nìco takové dìlal?
{9454}{9494}Protoe chci!
{9494}{9626}Pomocí vás, démonù, chci rozpoutat válku se zemí Nayutaya.
{9647}{9684}Co?
{9710}{9865}Lidé se tam vzbouøili proti mému otci, Ryoshimu, a mì, jeho synovy.
{9865}{9929}Chci aby za to zaplatili.
{9929}{10014}Take ty zvìsti, e nás chtìjí lidé napadnout...
{10014}{10072}... jsou jen samé li, pomocí kterıch...
{10072}{10156}... chci ovládnout blázny jako jste vy.
{10156}{10186}K èertu s tebou.
{10349}{10463}Slibujete mi svou oddanost?
{10544}{10625}Ano, pane.
{10625}{10673}Dobøe.
{10673}{10719}Dobøe si to pamatujte.
{10853}{10876}Cítím ho.
{10876}{10924}Cítím vlnìní pírka, Sakuro!
{10949}{11057}I kdy nevím, jestli mùeme pøejít do dalšího svìta...
{11057}{11155}... pojïme se zkusit dostat na místo, kde je pírko.
{11236}{11297}Vypadá to, e chceš jít tam, kde je Chun Hyang.
{11324}{11396}Plazit se potají, není zrovna mùj styl.
{11396}{11513}Nemáme na vıbìr, tady mají lidi za své nepøátele.
{11513}{11587}Tohle je úplnı opak našeho svìta.
{11706}{11758}Našla jsou vhodné místo na úkryt.
{11793}{11821}Tohle místo...
{11821}{11925}Ano, v našem svìtì tohle místo máme také.
{11925}{12044}I kdy oba svìty pøedstavují rùzné pohledy na stejnou vìc, jsou tu i místa, která jsou pro oba svìty stejná.
{12044}{12106}Aspoò, e to tady nesmrdí.
{12115}{12168}To musí bıt díky té krystalicky èísté vodì.
{12168}{12188}Vidíte?
{12216}{12320}Tento èistı proud vody má pro lidi z toho svìta ivotnì dùleitı.
{12320}{12412}Proto se nikdo neodváí k nìmu ani pøiblíit.
{12450}{12519}Potom je to ideální skrıš.
{12519}{12626}Ale skrıvaním pírko nezískáme.
{12626}{12679}Musíme nìco udìlat.
{12679}{12700}Ano.
{12700}{12751}Prosím, vezmìte mì sebou.
{12795}{12819}Chun Hyang.
{12834}{12956}Jestli si myslí, e tu budu zalezlá jako myš, tak se plete.
{12956}{13019}Prosím, vezmi mì sebou, Shaorane.
{13049}{13163}Vím jak se cítíš, ale zùstaò prosím tady.
{13174}{13204}Ale...
{13217}{13277}Nepøítel má pírko.
{13277}{13337}Pokud nebudeš opatrná, mùeš pøijít o ivot.
{13337}{13409}Navíc, nemáš u sebe své zrcadlo.
{13439}{13544}To zrcadlo zesiluje tvoje Hijutsu, je to tak?
{13544}{13600}Mùeš bez nìj bojovat?
{13600}{13654}T-To já..
{13685}{13738}Souhlasím s nimi.
{13738}{13811}Pokud s nimi pùjdeš, budeš jenom pøekáet.
{13941}{13992}Kdybych tak mìla sebou své zrcadlo.
{14194}{14246}Hele...
{14246}{14287}... ty víš kde jsou?
{14287}{14311}Ano.
{14311}{14347}Jsou pøesnì támhle!
{14782}{14830}Jaká matka, taková dcera.
{14872}{15035}Tvá matka, mìla vdy takovı protáhlı oblièej, kdy se mnou prohrála v boji.
{15054}{15133}U ani nevim, kolikrát jsem s tvojí matkou bojovala.
{15133}{15201}Jednou jsem vyhrála pak zase prohrála.
{15213}{15270}Dokonce jsme mìli stejnı poèet vítìzství i poráek.
{15275}{15334}Ale nakonec jsem s tvojí matkou prohrála.
{15344}{15409}Jaké umìní moje maminka pouila, e vyhrála?
{15409}{15506}Tvoje matka mì porazila ultimativním Hijutsu. uááá.-)
{15506}{15547}Co to bylo?
{15547}{15577}To ti nemohu øíct.
{15577}{15595}Proè ne?
{15606}{15723}Protoe je to nìco, na co musíš pøijít sama.
{15761}{15845}Ultimativní Hijutsu?
{16045}{16110}Co budeme dìlat teï?
{16110}{16164}Zaútoèime pøímo.
{16164}{16194}Dobrá odpovìï.
{16338}{16378}Hama Ryuuoujin!
{16465}{16585}Proè... proè jsou v tomto svìtì?
{16599}{16637}Vy všichni.
{16637}{16679}Zastavte je za kadou cenu!
{16679}{16696}Ano, pane.
{16728}{16836}Teï si budou všichni myslet, e je lidé pøišli napadnout.
{16836}{16935}Potomhle tu budou všichni lidi nenávidìt.
{16935}{16956}Ano, pane.
{16978}{17038}Otravnı bastardi.
{17038}{17101}Teï všichni zaplatíme za to, co jste provedli mému otci.
{17479}{17530}Pìknì vøelé pøijetí.
{17530}{17618}Musí bıt ovládání Ryoshiho synem.
{17618}{17637}Take...
{17637}{17656}Jasnì.
{17668}{17692}Kurogane.
{17919}{17974}Teï u mi asi nic øíct nechceš, je to tak?
{17974}{17990}Ano.
{18211}{18313}Uch, kde to jsem?
{18313}{18350}To je..
{18350}{18435}Ty lidskı bastardi napadli hrad.
{18435}{18478}Musí ho jít bránit.
{18518}{18587}Shaoran a Kurogan jsou ve velkém nebepeèí.
{18587}{18625}Co budeme dìlat, Chun Hyang?
{18806}{18847}Co je to?
{18847}{18901}Zrcadlo odpovídá na tvé volání
{19145}{19212}Já... jdu.
{19238}{19264}Sakuro?
{19735}{19777}Co se to dìje?
{19777}{19807}Sakuro?
{19807}{19954}Ta dívka vyvolala skrytou sílu uvnitø zrcadla...
{19954}{20025}... která jí umonila pøejít do tohoto svìta
{20050}{20074}Chun Hyang.
{20186}{20249}Pokud mám toto zrcadlo, není se èeho obávat.
{20249}{20287}Dìkuji, Sakuro.
{20455}{20486}Pùjdu napøed.
{20486}{20526}Prosím, postarej se tu o to.
{20526}{20582}Zaèínáš bejt nìjak vostrej.
{20592}{20618}Omlouvám se.
{20618}{20678}No jo no, tak bì.
{20698}{20719}Dobøe.
{20737}{20793}Zastavme ty lidskı psi!
{20823}{20882}Pojïme chránit hrad!
{20978}{21048}Mokona cítí, Soratovy pocity.
{21071}{21192}Sorata si myslí, e místní lidé nám jsou hodnì podobní, je to tak?
{21192}{21252}A-Ano.
{21252}{21330}S lidmi tohoto svìta je manipulováno.
{21330}{21422}Nejsou to zlı lidé a u vùbec né démoni.
{21448}{21502}Nemìl jsem pravdu, zmılil jsem se.
{21528}{21566}Odputì mi.
{21566}{21701}Nedej na první pohled, pravá podstata je skryta uvnitø.
{21727}{21782}To je to, co je nejduleitìjší.
{21847}{21881}Jen ertuji.
{21881}{21968}Ve skuteènosti cituji Shaorana.
{21968}{22020}Shaoran øekl nìco takového?
{22020}{22042}Ano.
{22127}{22196}Vidìt pravou podstatu...
{22659}{22694}Èekal jsen na tebe.
{22753}{22825}Ó, mocné pírko, dej mi sílu!
{22922}{23005}Tvùj nepøítel nejsem jen já.
{23005}{23096}Všichni démoni tohoto svìta jsou u na cestì sem.
{23156}{23227}Aby tì mohli zabít!
{23770}{23834}Našli nás.
{23834}{23858}Co budeme dìlat?
{23858}{23895}Zustaòte tady!
{23920}{23938}Chun Hyang.
{24174}{24229}Zrcadlo, pouij svoje zrcadlo!
{24284}{24308}No tak!
{24308}{24334}Pouij ho!
{24355}{24465}Pokud bych pouila své Hijutsu, moná bych je dokázala zastavit.
{24484}{24548}Ale bude to staèit?
{24861}{24908}Neøekla bych.
{25108}{25210}Poslouchejte mì, prosím.
{25331}{25357}Chun Hyang.
{25569}{25620}Byla to jen ztráta èasu.
{25663}{25702}Vydr, skrèku!
{25702}{25797}Take ty tvrdíš, e jsme byli oklamáni?
{25797}{25824}Správnì.
{25824}{25888}Proè by jsme ti mìli vìøit?
{25888}{25918}Uhni nám z cesty!
{25918}{25977}Ne, ani se odtuï nehnu.
{26001}{26058}A u udìláte cokoliv...
{26090}{26122}... nejdøív mì musíte porazit.
{26217}{26338}Já... vám vìøím.
{26375}{26420}Stejnì tak jako kdysi.
{26623}{26722}Jsi normální? Proè jsi to udìlala?
{26737}{26827}A doteï jsem s tebou bojovala den za dnem...
{26850}{26890}... ale dnes to všechno skonèí.
{26890}{26928}Co tím myslíš?
{27008}{27147}Já... ti vìøím.
{27551}{27648}Teï kdy všichni odloili své zbranì, jejich emoce se zklidnili.
{27648}{27682}Nemohu tomu uvìøit.
{27682}{27799}Tehdy, kdy nepouiješ zbyteènì svou sílu, zrodí se v tobì síla nová.
{27826}{27880}To je podstata Hijutsu.
{28084}{28242}Stenì tak jako její zesnulá matka, bude i Chun Hayang jednoho dne ovládat veškerou sílu vycházející z Hijutsu.
{28242}{28317}Hmm.. kohopak to tu máme.
{28339}{28377}Špatné zprávy.
{28377}{28428}Byli jsme oklamáni!
{28841}{28894}Zatracenì.
{28960}{29019}Och, k èertu!
{29056}{29105}Pøes ze mì neprojdeš.
{29152}{29239}Zabte je, vy démoni!
{29239}{29265}Nemá to smysl.
{29332}{29386}Take vy všichni...
{29386}{29428}Mokona je tu také.
{29428}{29459}A já také.
{29481}{29566}Nikdo tì tu u nebude poslouchat!
{30196}{30310}Vypadá to, e bude chvíli trvat, ne opadne ta ochraná clona vytvoøená pomocí Hijutsu.
{30323}{30367}Jak dlouho to bude trvat?
{30367}{30415}Moc dlouho ne.
{30415}{30455}Rozumím.
{30473}{30518}Postarej se prosím, zatím o pírko, Mokono.
{30518}{30543}Rozkaz.
{30632}{30667}Co tím myslíš?
{30795}{30871}Chceš abych byla prostøedníkem?
{30871}{30902}Správnì.
{30920}{31036}Potøebujeme mezi našimi svìty nìjakého prostøedníka...
{31036}{31129}... aby jsme do budoucna tokovım to vìcem zabránili.
{31155}{31225}A ty chceš abych jím byla já?
{31441}{31513}Pøijímám, udìlám to ráda.
{31556}{31584}Dìkuji.
{31610}{31772}A se vrátím do Nayutayi, musím všem øíct o tom co se tu stalo.
{31791}{31813}Ano.
{32016}{32058}Promiòte, za ty problémy.
{32082}{32123}Dejte na sebe pozor, prosím.
{32123}{32167}Vy také.
{32247}{32302}Mokona Modoki se u nemùe doèkat.
{32378}{32437}Budu se modlit za vaší bezpeènou cestu.
{32437}{32522}Mìj se, mùj malı roztomilı hmyze.
{32541}{32562}Dobøe.