{2521}{2555}To je...
{2583}{2614}Síla.
{2648}{2827}Obrovské mnoství skryté síly... se dalo do pohybu.
{3382}{3584}Celı svùj ivot hledají své koøeny... pøestoe jejich moc je stejnì velká jako moc bohù.
{3617}{3775}Jejich touha je tak silná, e i nemoné dokaí pøetvoøit ve skuteènost.
{4291}{4363}Chaos, král všech pírek
{4680}{4713}Jééé.
{4713}{4742}To nic!
{4742}{4807}Vìdìl, e se jednou nìco takovıho stane.
{4807}{4835}Princezno!
{4835}{4860}Shaorane.
{5136}{5181}Nééé...
{5181}{5254}Hej, dy ty mùeš pøece kouzlit, ne?
{5254}{5286}Tak s tím nìco udìlej.
{5286}{5358}Vypadá to opravdu dìsivì, ale pohled je to pìknı.
{5358}{5425}Nemyslím, e tì slyšel.
{5425}{5473}Ten parchant.
{5473}{5551}Jen tak mimochodem, umíš lítat?
{5574}{5603}Potom s tím nìco udìlej ty.
{5663}{5706}Jsi skvìlı, Mokono.
{6171}{6239}Co to bylo za svìtlo?
{6239}{6303}Ty jsi pouil magii, Fai?
{6303}{6361}Ne, nepouil.
{6361}{6411}Poèkejte, nìkdo se blíí.
{6479}{6507}Hele, to je...
{6615}{6712}Není to ten kluk co s ním nedávno bojoval?
{6712}{6787}Pojïme se jich zeptat kde to jsme.
{6787}{6872}Mohl bys mì ještì pøedtím, Shaorane...
{6872}{6893}Ano?
{6902}{6989}Umm... mohl bys mì postavit na zem?
{7007}{7051}O-Omlouvám se.
{7119}{7159}Dìkuji.
{7159}{7199}N-Není zaè. Umm...
{7238}{7304}Oba dva jste jako zamilované hrdlièky.
{7452}{7513}To je taková zábava.
{7513}{7565}Dìkujeme vám za svezení.
{7565}{7586}Není za co.
{7586}{7644}Bez tak jsme na cestì do mìsta.
{7644}{7677}Nechte to bejt.
{7677}{7748}Vy jste urèitì odjinud, viïte?
{7748}{7786}Proè myslíte?
{7786}{7839}Kvùli vašemu obleèení.
{7839}{7895}Jak se tato zemì jmenuje?
{7895}{7958}Toto je zemì Tao.
{7958}{7992}Zemì Tao?
{8233}{8271}Zdá se, e jste zaskoèeni.
{8271}{8332}Tomu svìtlu se øíká senriki.
{8271}{8332}Senriki - jako, e nìjaká speciální síla.
{8332}{8368}Senriki?
{8368}{8389}Ano.
{8389}{8470}Celı svìt Tao je plnı senriki.
{8470}{8629}Kadı èlovìk v této zemi má tuto sílu a mùe jí pouívat podle libosti.
{8629}{8697}Ale jsou tu také urèité rozdíly.
{8787}{8899}Boskı Hermité jsou obdaøeni senriki, které se rovná síle boha.
{8899}{9058}Spirituální Hermité, dokáí ovládat nejrùznìjší senjutsu.
{8899}{9058}Senjutsu - jako, e speciální techniky
{9061}{9111}Tìch je jen pár.
{9125}{9229}Nebeští Hermité dokáí létat po obloze jako ptáci.
{9229}{9424}Zemští Hermité, co je vìtšina lidí jako jsme mi, dokáe jen pohybovat rùznımi vìcmi.
{9469}{9564}Take to záhadné svìtlo bylo...
{9564}{9697}A cizí lidé jako jsme my, mohou mít také senriki?
{9697}{9744}Moná ano.
{9744}{9838}U jste nìkdy senriki pouili?
{9865}{10001}Kdy jsme padali z oblohy tak nìco mìkkého nas ovinulo a zabránilo nám v pádu.
{10001}{10042}Je to pravda?
{10063}{10138}To je síla Nebeského Hermita.
{10138}{10254}K tomu abysme získali sílu Zemskıch Hermitù, musíme mnoho let tvrdì trénovat.
{10254}{10387}Není obvyklé aby cizí lidé, kteøí pøišli odjinud, byli hned obdaøeni silou Nebeskıch Hermitù.
{10387}{10456}Vy urèitì nejste obyèejní cestovatelé.
{10456}{10508}To nám øíkají èasto.
{10508}{10656}Znamená to teda, e mùeme pouívat sílù Nebeskıch Hermitù?
{10666}{10683}Ano.
{10683}{10737}A musíte pøi tom odøíkat nìjaké kouzlo?
{10737}{10805}Staèí kdy na to budete myslet.
{10805}{10881}Nejlepší bude, kdy si to vyzkoušíte sami.
{11101}{11133}My létáme!
{11189}{11205}Princezno!
{11268}{11323}Jste v poøádku, princezno?
{11323}{11372}Ano, dìkuji.
{11414}{11457}Podívej, Shaorane.
{12117}{12167}Tak co, Mokono?
{12183}{12258}Je tady... více Sakuøinıch pírek.
{12258}{12281}Cítím je.
{12281}{12322}Odkud je cítíš?
{12322}{12345}Od tamtud.
{12524}{12675}To je Kunlunskı hrad, residence krále Chaose, vládce této zemì.
{12692}{12787}Král Chaos je jedinım Boskım Hermitem v této zemi.
{12787}{12863}Ovládá senjutsu rovnající se síle boha.
{12899}{12939}Nìkdo sem letí.
{12999}{13031}To jsou...
{13031}{13100}Take to nejsou ptáci?
{13100}{13135}Nedìlejte si starosti.
{13135}{13199}To je strá, která hlídá hrad.
{13199}{13313}Také to jsou Nebeští Hermité, tak jako vy.
{13375}{13430}Vy musíte bıt princezna Sakura.
{13457}{13508}Jak to, e znáte mé jméno?
{13518}{13618}Náš král je schopen vidìt budoucnost.
{13618}{13753}Také víme, e jste na cestì, na které hledáte vaše pírka.
{13753}{13874}Náš král by s vámi rád mluvil.
{13874}{13962}Pojïte prosím s námi na Kunlunskı hrad.
{14023}{14058}Mìjte se.
{14058}{14088}Dejte na sebe pozor.
{14116}{14181}Urèitì dáme.
{14648}{14762}Hele, Hele, jak myslíte, e ten král vypadá?
{14762}{14798}Nezajímá mì to.
{14798}{14847}Tøeba nìjak takhle.
{14875}{14918}To je opravdu dobré, Mokono.
{14918}{14960}Kdy myslíš.
{15068}{15135}Jmenuji se Hokuto Shichiku.
{15135}{15196}A já Nanto Rokku.
{15196}{15268}Jsme královy ochránci.
{15268}{15340}Král vás za chvíli pøíjme.
{15340}{15399}Zdrte se prosím, jakéhokoliv nepatøièného chování.
{15555}{15638}Toto je jedinı právolpatnı vládce zemì Tao.
{15638}{15795}Jedinı èlovìk obdaøenı silou Boského Hermit, král všech pírek, Chaos.
{15910}{16025}Take vy jste ti cestovatelé, kteøí cestují dimenzemy a hledají ztracená pírka?
{16075}{16091}Ano.
{16110}{16212}Toto musejí bıt ty pírka, která hledáte.
{16240}{16296}To jsou Sakuøina pírka.
{16296}{16341}Je jich opravdu hodnì.
{16341}{16426}ádám vás, vrate mi prosím, ty pírka.
{16462}{16541}Tento vìjíø je královskı symbol moci.
{16541}{16600}Není ádnı zpùsob jak byste ho mohli dostat.
{16741}{16883}Nicménì, vy ty pírka pøesto chcete... za kadou cenu.
{17526}{17577}Jestli-e po nich touíte...
{17674}{17823}... øeknìte mi veškeré detaily ohlednì vaší cesty po rùznıch svìtìch.
{17848}{17897}To je všechno co za nì chcete?
{17981}{18148}Take, tak jak sem øekl, Mokona byl skvìlı ve všech smìrech.
{18167}{18389}A díky tomu se Shaoranovy a ostatním podaøilo získat pírko ve svìtì Piffle a pokraèovat pak do dalšího svìta.
{18389}{18540}Ty pírka dostaneme jen za odvyprávìní našeho pøíbìhu... král je opravdu velmi milı, nemyslíš?
{18540}{18582}Moná jo, moná ne.
{18582}{18633}Ty králi nevìøíš, Kurosame?
{18633}{18659}Ne.
{18659}{18718}Mohl by mì prosím nìkdo vystøídat?
{18718}{18801}Mokona je u z toho mluvení unavenı.
{18801}{18851}Já to beru.
{18923}{18982}Jsi skvìlı, Mokono.
{19005}{19095}Ale král byl opravdu milı.
{19095}{19141}Take mì to opravdu bavilo si s ním povídat.
{19156}{19261}Vypadá to, e je vše v poøádku, alespoò podle, Mokony.
{19261}{19334}Nikdy se nenech ošálit.
{19334}{19382}Nevadí mi, e mi nedùvìøuješ.
{19410}{19455}Vy jste nás slyšel?
{19455}{19575}I dobré jídlo bude chutnat mizernì pokud tomubudete vìøit.
{19591}{19702}A abych vás zbavil vašich pochybností, pøedám vám ty pírka právì teï.
{20047}{20124}Pírka máte zpìt.
{20124}{20154}Ano.
{20154}{20189}Dìkuji vám.
{20209}{20271}Odveïte hosty do jejich pokojù.
{20615}{20664}Vypadá to, e Sakura spokojenì spí.
{20664}{20731}Dokonce spí klidnìji ne obvykle.
{20731}{20798}Moná proto, e se jí najednou vrátilo více pírek.
{20798}{20864}Take teï spí hlubším spánkem ne normálnì.
{20864}{20906}To myslíš vánì?
{20906}{20954}Ano, ale jistı si nejsem.
{21117}{21150}To je Yuuko.
{21150}{21205}Och, jestli pak to není Èarodìjka dimenzí?
{21205}{21254}Dlouho jsme se nevidìli.
{21254}{21304}Och, u tam máte noc?
{21313}{21356}Ještì je veèer.
{21356}{21423}Princeznì se jen vrátily její pírka.
{21423}{21472}Bylo jich toti víc najednou.
{21472}{21540}Vrátil nám je toti král všech pírek, Chaos.
{21540}{21576}Rozumím.
{21596}{21646}A co tì jinak pøivádí, Yuuko?
{21646}{21684}Není to zøejmé?
{21695}{21771}Má to nìco spoleèného s Bílım dnem?
{21695}{21771}Pozn. - kdy ena dá mui na Velentına dárek, mìl by jí to mu druhı den oplatit. 
{21771}{21813}Ano, správnì.
{21813}{21888}Boe, ta je ale otravná.
{21888}{21920}Pššš, ona tì slyší.
{21920}{21953}Slyším tì jasnì a zøetelnì
{21953}{21993}Øekl jsem to nahlas, abys mì slyšel.
{22011}{22051}Nicménì...
{22051}{22275}... pokud si dobøe vzpomínám, všechno to zaèalo tím koláèem, kterı jsem vám na Valentına upekla.
{22308}{22463}Všechno to v tomto svìtì zaèalo a taky skonèí.
{22479}{22543}Dobrı skutek pøedchází dobré vìci.
{22543}{22623}A špatnı skutek, špatné vìci.
{22636}{22712}Lidé to nazıvají karmou.
{22864}{23037}A tomu budete jednoho dne èelit, vzpomeòte si na to, co jsem vám teï øekla.
{23521}{23609}Nemáme na vybranou, musíme ho co nejrychleji probudit.
{23609}{23638}Ale...
{23638}{23679}To nebude potøeba.
{23693}{23761}Pùjdu tam místo nìho.
{23761}{23798}O èem to mluvíš?
{23824}{23908}Jeho cílem je nìco jiného.
{24834}{24963}Koneènì jsme se zase potkali... má princezno. 
{25317}{25372}Je tady více princezninıch pírek?
{25372}{25431}Ano, vypadá to tak.
{25431}{25532}Na západì této zemì, leí posvátná hora Gourai...
{25532}{25630}... na které ije prastarı pták, zvanı Genkaku.
{25532}{25630}Genkaku - jako, e èáp.
{25635}{25795}Pírka, která byla nalezena a pouita na královskı vìjíø, patøí ve skuteènosti tomuto ptáku.
{25795}{25908}Genkaku, nejen, e zabíjí dobytek a nièí naše pole, ale proudem vzduchu od svıch køídel, kací i stromy.
{25908}{26044}Snaili jsme se ho mnohokrát porazit, ale veškeré pokusy selhali.
{26044}{26108}Tak proè se o to nepostará král?
{26108}{26173}Král je pøece Boskım Hermitem a jeho síla se rovná sile boha, ne?
{26173}{26212}To je pravda.
{26212}{26292}Jestli-e pouijete svoje senriky, nemìl by bıt problém se toho ptáka zbavit.
{26292}{26376}Nepouívám své senriki na zabíjení.
{26390}{26439}To je má zásada.
{26439}{26478}Rozumím.
{26478}{26560}Chtìli bysme vás... o nìco poádat.
{26560}{26625}Mohli byste za nás porazit, Genkaku?
{26625}{26837}Samozøejmì, jako odmìnu, si mùete nechat všechna pírka Genkaku.
{26860}{26889}Pøijímám.
{27068}{27131}Musím jít, princezno.
{27154}{27219}Dej na sebe pozor, Shaorane.
{27285}{27361}To byla jedna ze 108 tajnıch schopností, Mokony.
{27361}{27409}Imitace Sakuøina hlasu.
{27431}{27459}Mokono.
{27471}{27603}Kdyby byla Sakura vzhùru, jsem si jistı, e by ti øekla, dej na sebe pozor, Shaorane.
{27613}{27680}Mokona to cítí stejnì.
{27693}{27740}Dìkuji, Mokono.
{27740}{27789}Dej za mì, pozor na princeznu.
{27789}{27827}Nech to na mì.
{27845}{27924}Zapomìli jsme se o nìèem zmínit.
{27924}{28047}Hora Gourai je doupì démonù známıch jako Shiyu.
{28047}{28112}Dejte si pozor.
{28142}{28235}Nemohu uvìøit, e nám tokovou to vìc, øíkáte a teï.
{28235}{28331}Stejnì bysme tam šli i kdyby jsme o tom vìdìli.
{28331}{28356}Ano.
{28356}{28396}To je pravda.
{28396}{28458}Dejte prosím, pozor na priceznu.
{28489}{28537}Dobrá, pùjdeme.
{29168}{29230}To musí bıt hora Gourai.
{29261}{29284}Skrèku!
{29284}{29301}Ano.
{29385}{29432}Je opravdu obrovskı.
{29432}{29502}Není tak velkı, to se ti jen zdá.
{29600}{29622}To jsou...
{29706}{29759}... Sakuøina pírka.
{30101}{30159}Pomoc...
{30232}{30270}Jste v poøádku?
{30270}{30308}V pohodì.
{30357}{30409}Nìkdo tu je.
{30853}{30918}P-Pomoc...
{31873}{31912}Kdo jsi?
{32092}{32176}Ty budeš urèitì, princezna zemì Clow.
{32687}{32719}Kdo jsi?