{2527}{2651}Koneènì jsme se zase potkali... má princezno.
{3530}{3567}Kdo jsi?
{3752}{3831}Ty budeš urèitì, princezna zemì Clow.
{4221}{4293}Pochybné pøání
{4644}{4715}Všechno je u v poøádku, doprovodím vás zpátky.
{4750}{4787}Dìkuji.
{5068}{5153}Take ty jsi pøišel za mım tatínkem, Chaosi?
{5163}{5188}Správnì.
{5202}{5295}Usiloval jsem o audienci u tvého otce u døíve...
{5295}{5421}... ale a teï, se mi podaøilo podepsat s tvım otcem smlouvu o vzájemném pøátelství našich zemí.
{5434}{5513}Jaká je tvá zemì, Chaosi.
{5533}{5633}Zemì Clow je opravdu pøekrásná, ale má zemì také.
{5654}{5759}Všichni lidé ijí ve vzájemné harmonii bez jakıchkoliv konfliktù.
{5836}{5920}Byla jste nìkdy v cizí zemi, princezno?
{5956}{6053}Nikdy sem neopustila hranice této zemì.
{6067}{6183}Aèkoliv královské povinosti èasto nutí tatínka a bratra k cestování...
{6183}{6254}... nikdy sem s nimi nejela.
{6254}{6304}To musí bıt opravdu frustrující.
{6304}{6331}To je!
{6331}{6394}Já chci také jít.
{6394}{6430}Ale bratr vdy...
{6482}{6516}Prosím, omluvte mì.
{6540}{6642}Neuvìdomila jsem si, e hovoøím s králem jiné zemì.
{6684}{6714}Na všechny formality klidnì zapomeò.
{7016}{7074}Chci jít hodnì daleko.
{7086}{7216}Jsem si jistı, e a dospìješ, tvoje pøání se ti splní.
{7216}{7258}Nemùu se doèkat.
{7258}{7397}Sice nevím, co by mi na to øekl tatínek, ale bratr mi to jistì nedovolí.
{7433}{7614}Kdy mi to bratr zakáe, tak mì potom mùeš zachánit u jenom ty, Chaosi.
{7614}{7648}Co tím myslíš?
{7648}{7727}Chtìla bych abys mi pomohl pøesvìdèit bratra.
{7855}{7871}Udìláš to?
{7899}{7935}Dobøe.
{7935}{7991}Poèítej s mojí pomocí.
{7991}{8033}Bomba.
{8033}{8122}A jen tak mimichodem, není dvakrát bezpeèné zdrovat se na tomto místì.
{8140}{8325}A budeš moci jednou cestovat, tak tì budu doprovázet jako tvùj pøítel a chránit tì vlastním ivotem.
{8325}{8345}Vánì?
{8405}{8429}Dávám ti své slovo.
{8495}{8554}Jééé, dìkuji.
{8990}{9016}Sen?
{9062}{9121}Koneènì jsi se vzbudila, Sakuro.
{9145}{9231}Prospala si skoro celı den, Sakuro.
{9279}{9323}Shaoran a ostatní tady nejsou.
{9336}{9459}Všichni šli k hoøe Gourai hledat tvá pírka.
{9459}{9514}Ale nedìlej si starosti.
{9514}{9603}Øìkl jsem jim a dají na sebe pozor za tebe.
{9611}{9657}Dìkuji, Mokono.
{9657}{9697}Nemáš zaè.
{10356}{10435}Proti takové pøesile to bude opravdu tìké.
{10435}{10476}Pøestaò fòukat.
{10518}{10539}Ta mlha je...
{10709}{10787}Kurogane... Kurogane?
{10824}{10848}Fai!
{11025}{11066}Kurogane!
{11066}{11100}Fai!
{11116}{11174}Jestli mì slyšíte, odpovìzte.
{11551}{11623}Dlouho jsme se nevidìli, Shaorane.
{11680}{11713}Seishiro.
{12084}{12119}Král Ashura.
{12206}{12230}Kdo je tam?
{12416}{12448}Otèe?
{12448}{12500}Ahoj, chlapèe.
{12500}{12539}Docela jsi vyrost.
{12631}{12671}Kdo k èertu seš?
{12671}{12731}Hej, co tím myslíš?
{12731}{12808}Neøíkej mi, es zapomnìl na otcovu tváø.
{12808}{12858}Právì, e si jeho tváø pamatuji.
{12973}{13005}Ty seš...
{13203}{13228}... jen imitace.
{13307}{13365}Nejdøív jsem byl zaskoèen...
{13365}{13414}... ale teï tomu nevìøím.
{13644}{13729}Sbíráš tato pírka, e ano, Shaorane?
{13741}{13851}Co bys øekl na souboj o toto pírko?
{14124}{14180}Nenechám se oklamat.
{14213}{14336}Ty... nejsi skuteènı Seishiro.
{14666}{14714}Tak tady jste.
{14747}{14798}Pøivedli jsme princeznu.
{14856}{14882}Vypadáte pøekrásnì.
{14950}{15003}Dobrá, mùeme vyrazit?
{15003}{15026}A kam?
{15037}{15075}Do mìsta pod zámkem.
{15075}{15143}Je tam nìco, co bych vám rád ukázal, princezno.
{15143}{15253}Ale já musím èekat a se Shaoran a ostatní vrátí.
{15253}{15322}Nemusíte si o nì dìlat starosti.
{15322}{15431}Pøi vèerejším obìdì jsem poznal, e jsou skuteènì silní.
{15431}{15511}Jsem si jistı, e vrátí v poøádku.
{15519}{15548}Ale já...
{15579}{15718}Hele, Sakuro, ty jsi se s králem setkala, kdy jsi byla ještì malá, viï?
{15737}{15862}Mohla by to bıt skvìlá šance, jak zjistit jestli to je ta samá osoba jako pøedtím...
{15862}{15964}... nebo jen nìkdo se stejnou duší.
{16268}{16303}Dobøe.
{16731}{16768}To je vládce Chaos!
{16784}{16815}Rádi vás vidíme.
{17077}{17140}Máte dobrı obraz?
{17140}{17194}Teï se pohnu.
{17203}{17233}Dobøe.
{17255}{17419}Zjistìte, co uvolòuje to obrovské mnoství energie
{17554}{17596}Podívej, Sakuro.
{17762}{17809}Vypadá to stejnì, jako mùj...
{17809}{17837}Správnì.
{17837}{17904}Je to váš domov, zemì Clow.
{17927}{18069}Vytvoøil jsem to ze vzpomínek, které jsem si uchoval z návštevy zemì Clow.
{18173}{18258}Take vy jste opravdu...
{18258}{18324}Docela jste vyrostla, princezno.
{18359}{18407}A krásou pøíroda také nešetøila.
{19396}{19435}Hodnì ses zlepšil.
{19435}{19523}Teï ti mohu v klidu svìøit ochranu Suwy.
{19523}{19566}Dr hubu, bastarde.
{19566}{19608}O co ti jde?
{19669}{19720}Zesílil jsi, Shaorane.
{19733}{19832}A tvé zacházení s meèem se od minule o hodnì zlepšilo.
{19832}{19883}Co se dìje? Proè váháš?
{19883}{19931}A u øíkáš cokoliv, mì neoklameš.
{19931}{19967}Všechno je to jen trik.
{20003}{20054}V tom pøípadì zaútoèím první.
{20776}{20877}Pamatujete si ještì na náš spoleènı slib, princezno?
{20959}{20999}A-Ano.
{20999}{21245}Slíbil jsem vám, e vás budu doprovázet na vašich cestách jako váš pøítel a chránit vás vlastním ivotem.
{21291}{21367}A teï jste tady.
{21383}{21435}A já jsem pøipraven.
{21464}{21645}Hodlám s vámi cestovat a hledat vaše pírka namísto Shaorana a ostatních.
{21645}{21688}Poèkejte chvíli.
{21688}{21775}A co bude se Shaoranem a ostatními?
{21775}{21891}V prvé øadì to nejsou èlenové princezniny rodiny.
{21891}{22031}Pøesto neváhali a nasadily své ivoty na ochránu princezny pøi jejím hledání ztracenıch pírek.
{22088}{22156}Své ivoty, by ale mìli it pro sebe.
{22181}{22347}A jen vy, jim mùete jejich normální ivoty vrátit, princezno.
{22400}{22577}Jste ochotná cestovat se mnou, namísto Shaorana a ostatních, princezno?
{22578}{22635}J-Já...
{23121}{23144}To nemohu.
{23392}{23420}Rozumím.
{23599}{23622}V tom pøípadì...
{23847}{23870}Co je to zas?
{23882}{23914}Co se to dìje?
{24219}{24270}Fai! Kurogane!
{24270}{24310}Není ti nic, skrèku?
{24322}{24348}Podívejte!
{24482}{24523}Utíkej, Sakuro!
{24559}{24603}Mokona to cítí.
{24603}{24657}Král se zmìnil.
{24657}{24796}Nezastaví se pøed nièím aby tì donutil s ním cestovat.
{25008}{25039}Co se dìje?
{25039}{25062}Mé nohy...
{25113}{25198}Svìtlo znehybnìní je jedno ze shinsen technik.
{25211}{25320}Dokud toto kouzlo nezruším, nebudete se moc pohnout.
{25496}{25518}Princezno!
{25573}{25636}Take to seš ty, kdo to má všechno na svìdomí?
{25636}{25683}Co máš s princeznou v plánu.
{25683}{25851}Hodlám s princeznou cestovat a pátrat po jejic pírkách na místo vás.
{25879}{26040}Kdy byla princezna malá, dal jsem jí slib... e budeme jednou cestovat spoleènì.
{26070}{26135}A tìmhle sraèkám máme jako vìøit?
{26184}{26293}Ale princezna splnìní mého slibu odmítla.
{26323}{26368}Proto chci bojovat.
{26385}{26468}A ukázat princeznì jak jste slabı.
{26662}{26722}Tohle budou asi jeho oblíbenci.
{26722}{26743}Pozor.
{27094}{27139}Chceš si to rozdat?
{27139}{27204}Klidnì... aspoò se naereš trochu hlíny.
{27263}{27331}Jsi skuteènì silnı, Kurogane.
{27331}{27378}Ovšem.
{27481}{27577}Ale já sem silnìjší mnohem víc.
{27636}{27658}Kurogane!
{27704}{27758}Hama Ryuuoujin.
{27926}{27939}Coe?
{27968}{27998}To nebylo špatné.
{28023}{28075}Ale na mì to nestaèí.
{28272}{28335}Thunder Blade.
{28616}{28646}Kurosame!
{28750}{28787}Jak mùete vidìt...
{28822}{28891}... moje technika pøevyšuje tu jeho.
{29134}{29194}Thunder Blade.
{29379}{29449}Ovládáš magii, nebo ne?
{29463}{29551}Ale jaá také.
{29585}{29616}Kdy to øíkáš?
{29616}{29704}Ale síla je k tomu aby byla pouita.
{29723}{29784}Kdy jí nepouíváš, je to jako kdyby neexistovala.
{29856}{29889}Fai!
{30076}{30132}Má magická síla pøevyšuje tu jeho.
{30222}{30264}Není pochyb.
{30264}{30291}To je to místo.
{30459}{30651}Zjisti... odkud ta síla vychází.