{3840}{3912}Pravı kamarádi
{4323}{4349}Dostal ho?
{4362}{4433}To bylo docela dobré.
{4482}{4518}Teï to ukonèím.
{4598}{4685}Toto je jedna z mıch senriki technik, shikai.
{4710}{4829}Shikai je klonovací technika vyuívající meèù.
{5048}{5084}Thunder Blade.
{5334}{5403}Na nìco se tì zeptám, Shaorane.
{5464}{5526}Proè stojíš na princezninì stranì?
{5575}{5598}Odpovìz mi!
{5745}{5855}Nemáš ádnı dùvod abys s princeznou cestoval.
{5855}{5970}Take, proè s ní cestuješ?
{6210}{6241}Co se dìje?
{6241}{6270}Proè mi neodpovídáš?
{6342}{6385}To je zlı.
{6385}{6450}Skrèek bojuje co mùe, ale ten meè u moc dlouho nevydrí.
{6522}{6560}Já...
{6620}{6660}... princeznu miluji.
{6706}{6780}To je mùj dùvod.
{7031}{7097}Ó, plameny, dejte mi sílu.
{7205}{7270}Hien Thuner Blade
{7205}{7270}Pozn. - Hien je souèástí názvu Shaoranova meèe a je tím doslovnì myšleno Purpurovı plamen
{8636}{8887}Teï vidíte, e mé zacházení s meèem, magie a láska pøevyšuje tu jejich.
{8904}{9013}Pojïme, budeme cestovat a hledat vaše ztracená pírka.
{9057}{9107}Nemusíte se mì bát.
{9137}{9157}Ne...
{9190}{9253}Nikdy bych vám neublíil.
{9315}{9337}Ne.
{9393}{9481}Má síla bude slouit jen vám.
{9559}{9577}Ne!
{10113}{10142}Princezno.
{10152}{10199}Nechoï s ním, Sakuro!
{10941}{10982}Dobrá, pùjdeme tedy?
{11326}{11394}Princeznina pírka!
{11596}{11640}Vìdìl jsem to.
{11657}{11817}Pro nìkoho kdo je roven bohu, tak jako já, je velmi snadné cestovat dimenzemi.
{11968}{11993}Princezno.
{12311}{12359}Princeno Sakuro.
{12706}{12753}Nemá smysl abych s ní cestoval...
{12829}{12887}... pokud se její srdce nezmìní.
{13049}{13084}Princezno.
{13183}{13249}Princezno... Sakuro.
{13668}{13740}Uch, co se to s Mokonou stalo?
{13752}{13836}Prober se, Shaorane!
{13836}{13872}Shaorane!
{13898}{13964}Kurorine! Kurorine!
{13992}{14087}Otevøi prosím oèi, Fai!
{14087}{14180}Sakura! Sakura je pryè!
{14216}{14285}Co má Mokona dìlat?!
{14304}{14372}Proberte se všichni!
{14320}{14394}Ano, vidìla jsem to vlastní oèi.
{14421}{14563}Vìdìl jsem to. Má moc, která mu umoòuje cestovat dimenzemi.
{14563}{14625}Ale kdo ve skuteènosti je?
{14691}{14725}On je...
{14780}{14814}... nejspíše...
{15296}{15333}Jste vzhùru?
{15399}{15428}Kde to jsem?
{15488}{15522}Kde je Shaoran a ostatní?
{15555}{15594}Nebojte se.
{15594}{15642}Nezabil jsem se.
{15696}{15739}Není dùvod, abyste se mì bála.
{15756}{15843}Rozhodil jsem se, e prozatím odloím svùj plán ohlednì našeho spoleèného cestování.
{15993}{16043}Pøemıšlel jsem o tom.
{16066}{16105}A nakonec jsem si uvìdomil...
{16132}{16287}... e nejduleitìjší vìcí na naší cestì bude vzájemná dùvìra.
{16372}{16520}Rád... bych se o vás dozvìdìl víc, princezno Sakuro.
{17262}{17318}Dobrá, teï mi prosím dovolte odejít.
{17393}{17482}Kım jenom... on je?
{17809}{17840}Kdo je tam?
{18457}{18513}Koneènì jsi vzhùru, Shaorane.
{18513}{18544}Mokono.
{18582}{18614}Ahoooj.
{18614}{18661}Jsi v poøádku, Shaorane?
{18661}{18697}Ovšem, e je v poøádku.
{18814}{18897}Narazil jsem na toho malıho plyšáka ve mìstì.
{18897}{19003}Mokona šel pro pomoc, protoe jste všichni byli v bezvìdomí.
{19003}{19125}Ale co se vám stalo, e máte všichni taková zranìní?
{19309}{19346}Sakura je...
{19370}{19401}Ten bastard!
{19401}{19461}Musel to plánovat od zaèátku.
{19461}{19580}Za všechno mùe Mokona, protoe øekl o králi, e je to dobrı èlovìk.
{19580}{19611}Omlouvám se.
{19611}{19673}Zapomeò na to.
{19686}{19773}Problém teï je, jak dostaneme princeznu zpátky.
{19872}{19901}Co je?
{19901}{19934}Proè nic neøíkáš?
{20156}{20186}Princezno.
{20408}{20567}Pro nìkoho kdo je roven bohu, tak jako já, je velmi snadné cestovat dimenzemi.
{20782}{20817}Shaorane?
{20817}{20869}Neøikej mi, e chceš Sakuru opustit?
{20961}{20994}Shaorane...
{20994}{21032}Dìláš si prdel?
{21032}{21102}Nemùeme pøece jen tak stánout ocasy potom, co jsme to takhle posrali.
{21102}{21135}Hej, skrèku!
{21135}{21192}Od èeho máš meè?
{21293}{21371}Promluvme si o tom pozdìji, Kurosame.
{21371}{21397}Ale...
{21513}{21581}Shaoran to vzdal.
{21581}{21687}Myslí si, e bude nejlepší, kdy dá Sakuøe sbohem.
{21687}{21883}Jestli bude nìkdo tak silnı, cestovat se Sakurou, tak u nás není potøeba.
{21883}{21937}Ještì jsem to nevzdal.
{21950}{22006}Nezáleí na tom jestli vyhraješ nebo prohraješ.
{22034}{22075}Neøekl bych.
{22075}{22163}Kdy toho zasranıho Chaose porazíme, všechno se tím vyøeší.
{22204}{22230}Pleteš se.
{22239}{22277}Jak pletu?
{22313}{22506}City, které k sobì Shaoran a Sakura chovají, jsou teï pod tekou zkouškou.
{22506}{22602}Take budeme jen stát a sledovat co se bude dít?
{22621}{22663}To jsem neøekl.
{22663}{22782}Podnikne jen nezbytnì nutné kroky.
{23220}{23261}Mùu s tebou na chvíli mluvit?
{23337}{23366}O co jde?
{23406}{23438}Dobøe...
{23451}{23658}... rád bych navázal tam, kde jsem naposled skonèil, opravdu uvauješ o tom, e Sakuru opustíš, Shaorane?
{23713}{23739}Je to tak?
{23760}{23922}Pokud to udìlá princeznou šastnou, udìlám to.
{23936}{24014}Jsi opravdu skvìlı èlovìk, Shaorane.
{24014}{24078}Ale mìl bys bıt víc rozumìjší.
{24125}{24265}Ty necestuješ se Sakurou jen proto, abys jí vrátil zpìt její vzpomínky, Shaorane.
{24305}{24370}Tak to není, viï?
{24405}{24444}Nemám pravdu, Shaorane?
{24460}{24522}Proè nezkusíš bıt jednou sobeckı?
{24620}{24744}Proè nemyslíš víc na sebe ne na Sakuru?
{24779}{24866}Na... sebe?
{24926}{24993}Zapomeò na chvíli na všechna pírka.
{25006}{25181}Není snad pro tebe Sakura nepostradatelná... není to snad pro tebe nejduletìjší osoba na svìtì?
{25221}{25250}Fai.
{25887}{25925}Shaorane.
{26081}{26117}Princezno Sakuro.
{27525}{27570}Smrdí to opravdu strašnì.
{27570}{27601}Co to dìláte?
{27641}{27704}Jednu skvìlou medicínu.
{27958}{28006}Tak, a je to.
{28066}{28114}Pøemıšlela jsem kdo by to tak mohl bıt.
{28114}{28153}Co mi chceš?
{28173}{28214}Chtìl bych tì o nìco poádat.
{28214}{28303}Pošli mi mùj Ginryuu.
{28303}{28391}Och... to je ten tvùj meè.
{28391}{28476}Byla to vìc, kterou jsi zaplatil za monost cestování dimenzemi.
{28476}{28519}Nemohu ti ji vrátit.
{28519}{28558}Já vím.
{28558}{28632}Proto tì také neádám o to, abys mi ho vrátila.
{28632}{28693}Jen si ho chci na chvíli pùjèit.
{28693}{28776}Toj je tvé pøání?
{28796}{28824}Jo.
{28857}{28882}Prosím.
{29076}{29117}Promiò, to pøání je nesplnitelné.
{29132}{29220}Nemohu ti ho pùjèit.
{29220}{29256}Fajn.
{29256}{29296}Zapomeò na to!
{29296}{29426}Byl jsem pìknej idot, kdy jsem si myslel, e ti mùu vìøit.
{29426}{29535}Proè nevloíš svou dùvìru do rukou nìkoho jiného?
{29612}{29657}Nedìlej, e nevíš.
{29657}{29724}Odpovìï znáš, nebo ne?
{30324}{30408}Chtìla bych tì vidìt, Shaorane.
{30691}{30715}Fai.
{30790}{30826}Dìkuji.
{30919}{30990}Hodlám princeznu Sakuru zachránit.
{31003}{31102}Ale né kvùli princeznì samotné, ale kvùli sobì.
{31102}{31207}Vìdìl jsem, e to øekneš, tak sem ti nìco pøipravil.
{31207}{31284}Tady. Je to magickı lektvar, kterı jsem udìlal.
{31284}{31372}Kdy to vypiješ, budeš se pak cítit lépe.
{31372}{31407}Dìkuji.
{31407}{31460}Jestli ti to jen zahojí tvá zranìní, tak je to k nièemu.
{31522}{31557}Hej, skrèku!
{31581}{31618}Vem si ho!
{31632}{31672}Kurogane.
{31690}{31812}Kurogan ti vìøí Shaorane, proto ti dává svùj meè.
{31812}{31846}Pøestaò vanit.
{31938}{31978}Dìkuji.
{31978}{32085}A protoe je Kurogan hodnı, dostane od Mokony pusinku. 
{32085}{32121}Mlask.
{32121}{32156}Co to, k èertu, dìláš?
{32156}{32186}A ty taky Fai.
{32186}{32220}Mlask.
{32220}{32262}To lechtá.
{32285}{32349}Shaoran si na pusinku poèká.
{32349}{32435}Mokona dá Shaoranovy pusinku a se vrátí Sakura. 
{32435}{32460}Mokono.
{32460}{32562}Protoe, ty pøivedeš Sakuru zpátky, viï?