{2622}{2646}Fai.
{2719}{2754}Dìkuji.
{2836}{2905}Hodlám princeznu Sakuru zachránit.
{2918}{3018}Ale né kvùli princeznì samotné, ale kvùli sobì.
{3018}{3122}Vìdìl jsem, e to øekneš, tak sem ti nìco pøipravil.
{3122}{3202}Tady. Je to magickı lektvar, kterı jsem udìlal.
{3202}{3289}Kdy to vypiješ, budeš se pak cítit lépe.
{3289}{3324}Dìkuji.
{3324}{3376}Jestli ti to jen zahojí tvá zranìní, tak je to k nièemu.
{3438}{3473}Hej, skrèku!
{3496}{3534}Vem si ho!
{3549}{3582}Kurogane.
{3594}{3714}Kurogan ti vìøí Shaorane, proto ti dává svùj meè.
{3714}{3750}Pøestaò vanit.
{3843}{3882}Dìkuji.
{3882}{3988}A protoe je Kurogan hodnı, dostane od Mokony pusinku.
{3988}{4026}Mlask.
{4026}{4061}Co to, k èertu, dìláš?
{4061}{4089}A ty taky Fai.
{4089}{4124}Mlask.
{4124}{4167}To lechtá.
{4191}{4254}Shaoran si na pusinku poèká.
{4254}{4340}Mokona dá Shaoranovy pusinku a se vrátí Sakura.
{4340}{4364}Mokono.
{4364}{4466}Protoe, ty pøivedeš Sakuru zpátky, viï?
{4488}{4506}Ano.
{4574}{4646}Zamrzlé vzpomínky
{5150}{5192}Co se dìje, princezno Sakuro?
{5208}{5234}Proè nejíte?
{5712}{5798}Ten pták na té malbì mi je povìdomí! Jinak je to opravdu pìkné.
{5811}{5861}Fai, není to...
{5861}{5918}Ano, vypadá to tak.
{6213}{6359}Øíká se, e zemì Tao byla stvoøena ptákem s mystickou silou.
{6359}{6400}To je nìjaká legenda?
{6400}{6435}Ano.
{6435}{6634}Vìøíme, e nás Král, Chaos, je nositelem této síly.
{6634}{6754}Ale proè by potom takovı vznešenı král unášel Sakuru?
{6754}{6786}To je...
{6826}{6864}Ach, Kurorin.
{6864}{6894}Jak to šlo?
{6894}{6964}Pùjde Shaoranùv meè spravit?
{6964}{7018}Podaøilo se nám najít jedno dobrého kováøe.
{7018}{7095}Sice to bude chvíli trvat, ale pùjde to.
{7095}{7141}Dìkuji.
{7141}{7221}vypadá to, e vám obìma hodnì dluíme.
{7221}{7282}Och ne, to je v poøádku.
{7282}{7347}Také to chceme vìdìt.
{7347}{7380}Vìdìt?
{7401}{7489}O co našemu králi jde.
{7510}{7694}Tøeba, e to vypadá, e je to váš nepøítel, stále našemu králi Chaosovy vìøíme.
{7764}{7800}Hej, skrèku!
{7808}{7830}Ano.
{7942}{7988}Shaoran znovu trénuje?
{7988}{8030}Vypadá to tak.
{8030}{8157}Hele Fai, pojïme udìlat nìco, èím bysme zvıšili šanci na návrat Sakury.
{8157}{8205}To je dobrı nápad.
{8337}{8409}Musíš bejt poøád v synchronizaci se svım meèem. 
{8409}{8481}Pak budeš moct øíct, e je Souhi souèástí tvıho tìla.
{8481}{8502}Ano.
{8502}{8595}Ze všeho nejdøív, se ale musíš s tím meèem obeznámit.
{8595}{8640}Pokus se useknout tu vìtev.
{8855}{8888}Znova.
{8936}{8960}Ano.
{9176}{9242}Stráe jsou opravdu silné.
{9242}{9301}Take se dovnitø nedostaneme?
{9301}{9346}Nesmíme to pøehánìt.
{9346}{9409}Nakonec, jsme tu pouze jako špióni.
{9554}{9592}To je naše šance!
{9604}{9643}Poèkej, Mokono!
{10082}{10176}Nìco bych vám rád dal, princezno Sakuro.
{10490}{10542}Promiòte, e vás vyrušuji, králi Chaosy.
{10542}{10572}Co se dìje?
{10572}{10607}Do zámku pronikly vetøelci.
{11080}{11118}Thunder Blade.
{11467}{11513}Kdo probaha jsou ti lidé?
{11513}{11659}Zdá se, e kromì Shaorana, usiluje o princeznu i nìkdo jinı.
{11794}{11875}Take obrana je silnìjší ne jsme oèekávali.
{11899}{11932}Co budeme dìlat?
{11989}{12073}Naplánuji náš další krok.
{12221}{12256}Chaosy!
{12365}{12403}Ty odcházíš?
{12403}{12422}Ano.
{12422}{12446}To ne.
{12497}{12545}Opatrujte se, princezno.
{12779}{12819}Chaosy.
{12819}{12895}Nezapomeò se pro mì vrátit!
{12905}{12965}Budu na tebe èekat.
{12965}{13069}Nepøeji si nic jiného, ne s tebou cestovat.
{13069}{13164}I kdy to znamená, e opustím tatínka a bratra.
{13164}{13252}Kdy nejsem s tebou, cítím se osamìle, Chaosy.
{13280}{13316}Cítím se osamìle.
{13406}{13430}Já...
{13622}{13644}Já...
{13668}{13693}To není pravda.
{13720}{13800}Na tohle sem nikdy nepomyslela.
{13814}{13934}Otce a bratra velmi miluji.
{13990}{14067}Pokud je to pravda, tak proè...
{14088}{14110}Je to snad sen?
{14134}{14184}A co je to za sen?
{14205}{14319}Nebo to je... opravdu moje vpomínka?
{14656}{14680}Sakuro!
{14680}{14715}Co se dìje, Sakuro?
{14715}{14739}Co je ti?
{15081}{15109}Fai.
{15132}{15161}Já...
{15180}{15226}Jsi v poøádku, Sakuro?
{15226}{15248}To je zlé.
{15248}{15300}Ta pírka jsou falešná.
{15319}{15463}Pøestoe se to pírko podobá skuteènému, není to pravé pírko.
{15472}{15637}Pokud to tak je, tak vzpomínky, které Sakura získala, nejsou skuteèné.
{15664}{15794}Take vzpomínka, kde jsem se setkala s králem jako malá, je...
{15794}{15823}Ano.
{15823}{15936}Snail se tì oklamat pomocí falešnıch vzpomínek.
{15967}{15998}To není moné...
{16084}{16115}Je tady!
{16703}{16720}Princezno.
{16730}{16788}Nenám vzpomínky...
{16788}{16877}... protoe se pøemìnily do pírek a rozletìli se do rùznıch svìtù.
{16893}{16978}Proto jsem na cestì, na které ta pírka hledám.
{17057}{17139}Zkoušel jsi mì ovládnout, pomocí falešnıch vzpomínek.
{17159}{17211}Myslím, e to co jsi udìlal, bylo velmi hanebné.
{17868}{17890}Vy dva...
{17974}{18010}... øeknìte Shaoranovy tohle.
{18221}{18286}Chaos mì vyzval na souboj?
{18286}{18364}Øíkal, e na tebe bude zítra ráno èekat na hradním nádvoøí.
{18364}{18468}A pokud zítra vyhraješ, nechá Sakuru jít.
{18555}{18582}Rozumím.
{18582}{18731}Poøád nemohu uvìøit tomu, e vyuil ta falešná pírka k tomu, aby vytvoøil princeznì smyšlené vzpomínky.
{18731}{18758}Ano.
{18758}{18868}Taky máme pro tebe zpávu od Sakury, Shaorane.
{18888}{18931}Sakora ti vzkazuje tohle.
{18966}{19016}Øekni prosím Shaorannoy tohle.
{19016}{19156}Nedìlej si o mì starost a buï prosím opatrnı.
{19442}{19466}To staèí.
{19489}{19531}Teï u je to na tobì.
{19609}{19648}Dìkuji.
{20829}{20855}Princezno.
{20935}{21008}Porazím, Shaorana.
{21106}{21176}A vy to uvidíte na vlastní oèi.
{21457}{21539}U se rozednívá.
{21606}{21651}Jsi pøipravenı?
{21701}{21723}Ano.
{21819}{21837}Podívejte!
{22049}{22125}Prosím, vydrte, princezno Sakuro.
{23395}{23475}Èìkám tu na tebe, Shaorane.
{23967}{24002}Zaèneme.
{24519}{24585}Shaoran prohrává.
{24585}{24611}Neøekl bych.
{24611}{24634}Opravdu?
{24634}{24674}Podívej na jeho tváø.
{24753}{24828}Shaoranova tváø je stejná jako vdy.
{24828}{24878}Potom všem nezpanikaøil.
{24878}{24944}Opatrnì sleduje soupeøovy pohyby.
{24944}{24997}Co bys udìlal na jeho místì, Kurosame?
{24997}{25070}Provedl bych protiútok po dalších tøech úderech.
{25070}{25125}Jedna... dva...
{25161}{25186}... tøi.
{25515}{25532}Mì neuteèeš!
{25711}{25747}U to zaèalo.
{25788}{25853}Jste pøipraven?
{25913}{25952}Samozøejmì.
{26235}{26267}Shaorane.
{26267}{26302}Princezno.
{26401}{26437}Ty drzej...
{26766}{26774}Bastarde.
{27004}{27070}Thunder... Blade.
{27070}{27096}Teï.
{27127}{27153}Coe?
{27336}{27374}Dokázal to!
{27374}{27418}Ne! Ještì ne!
{27879}{27910}Shaorane...
{27977}{28012}Shaorane!
{28030}{28093}Dr se, Shaorane!
{28109}{28130}Princezno.
{28197}{28286}Jsem v poøádku, Shaorane.
{28286}{28322}Tak dej na sebe prosím pozor.
{28343}{28399}Nemysli na moje pírka.
{28409}{28439}Buï zticha!
{28492}{28520}Nebudu.
{28594}{28703}Shaoran zøejmì není jediny kdo bojuje.
{28810}{28871}Ukonèím to.
{29047}{29072}Princezno!
{29236}{29258}Shaorane!
{29380}{29404}Odpus mi, prosím.
{29512}{29534}Princezno!
{29648}{29835}Pokud nemohu vymazat tvoje vzpomínky, má princezno...
{29910}{29947}... chci...
{30283}{30312}Sakuro!
{30312}{30346}Co to s ní, k èertu, udìlal?
{30346}{30420}Sakura... zamrzla.
{30420}{30461}To vidím.
{30461}{30481}Ne!
{30503}{30600}To není zmraené jen její tìlo, ale i duše.
{30600}{30634}Co to øíkáš?
{30652}{30711}Souboj je u konce, Shaorane.
{30736}{30793}Vezmu princeznu a budu s ní spoleènì cestovat.
{30818}{30839}Ale...
{30951}{31063}Ještì pøedtím, se o tebe postarám.
{31063}{31090}Take...
{31224}{31248}To je?!
{31264}{31303}Koneènì.
{31355}{31399}Vypadá to tak.
{31839}{31911}Take ten pták existuje?
{31911}{31929}U je tady.
{32072}{32093}Rozdìlte se!
{32184}{32204}Jste v pohodì?
{32204}{32232}Ano.
{32232}{32265}Docela jo.
{32555}{32620}Drte se, princezno.
{32653}{32723}Zachráním vás.