{2239}{2320}Ve své cestì musí pokraèovat.
{2341}{2443}A ten, kdo bude tajnì urèovat smìr jejich cesty...
{2490}{2531}... budu já.
{3204}{3276}Na køídlech zítøka
{3949}{4003}Takhle nemáme šanci.
{4003}{4112}Pøesto po nás chceš, abysme proti tomu bojovali, viï?
{4128}{4157}Shaorane.
{4241}{4267}Princezno.
{5023}{5055}Kde to...
{5081}{5108}... jsem?
{5536}{5565}Ten parchant...
{5795}{5859}Myslím, e ho vùbec nezajímáme.
{5859}{5909}Vypadá to, e jde jen po skrèkovy.
{6016}{6042}Mìsto!
{6213}{6256}Musíš odtud utéct.
{6256}{6282}Ale...
{6319}{6359}To bude v poøádku. Bì.
{6404}{6436}Hledali jsme tì.
{6436}{6467}Vy jste...
{6488}{6534}Pøinesli jsme ho.
{6545}{6571}To je...
{7053}{7107}Nièí vlastní hrad.
{7107}{7149}Co tím sleduje?
{7149}{7241}Chaos udìlá cokoliv, aby Shaorana porazil.
{7289}{7397}Ale také cítím, e je velmi osamìlí.
{7669}{7702}Mohu vás o nìco poádat?
{7756}{7828}Mohli byste se postarat o princeznu za mì?
{7828}{7892}Neøíkej mi, Shaorane...
{7892}{7930}Chceš dìlat volavku?
{8001}{8023}To nesmíš!
{8023}{8055}Je to nebezpeèné.
{8055}{8124}Jestli nìco takového udìláš, mohl bys zemøít, Shaorane!
{8134}{8178}To bude v poøádku, Mokono.
{8206}{8257}Nehodlám zemøít.
{8276}{8307}Shaorane.
{8367}{8469}Pokud nás Shaoran tak hezky poádal, nemùeme mu odmítnout.
{8486}{8520}e ano, Kurosame?
{8536}{8595}U je to trapnı, øíkat furt, e nemáme šanci.
{8608}{8643}Dìkuji.
{9046}{9080}Zvládl jsem to.
{9080}{9109}Mokono.
{9109}{9181}Mokona chce bojovat se Shaoranem.
{9282}{9343}Mám Chaosovy pomoc?
{9361}{9406}Ano, udìlej to.
{9406}{9436}Proè?
{9455}{9527}V našich pøedpovìdích pøece nefiguroval.
{9542}{9579}To je pravda.
{9594}{9646}Ale mùeme ho vyuít.
{9646}{9814}Pøedtím jsme je ztratily z našeho pole vìdìní, aleteï bysme je mohli sledovat podle aury jeho síly.
{9839}{10056}Pokud by se to povedlo, mohli bysme v tichosti urèovat smìr jejich cesty, stejnì jako pøedtím.
{10074}{10187}A co s ostatními, mimo princeznu Sakuru samozøejmì?
{10239}{10332}Bez ohledu na to, co se stane, princeznu neopustí.
{10368}{10419}Fei Wang Reede...
{10419}{10477}... od zaèátku byl tvùj cíl...
{10570}{10599}Správnì.
{10618}{10745}Sílu, kterou jsme ztratili, kvùli intervenci té èarodìjky...
{10745}{10867}... získáme zpìt, jen kdy budeme kontrolovat smìr jejich cesty.
{11099}{11141}Fei wang Reede...
{11187}{11226}... ty se nikdy nepouèíš.
{11456}{11543}Kurogane... Fai... spoléhám na vás.
{11696}{11715}Co to...
{11832}{11877}Vy bastardi.
{11877}{11923}Hodláte nás zastavit?
{12007}{12047}Zastavím je.
{12072}{12096}Dobøe.
{12136}{12193}Náš èas nadešel.
{12246}{12271}Pohni se!
{12493}{12529}Co se dìje, Shaorane?
{12638}{12665}Shaorane!
{13396}{13416}Princezno...
{13452}{13494}... pomozte mi, prosím.
{13534}{13647}Jestli to tak bude pokraèovat, hodnì lidí zemøe.
{13691}{13755}Vèetnì tìch, kteøí jsou pro vás dùleití.
{13817}{13905}Nic víc u udìlat nemohu.
{13948}{14089}Pøál sem si jen bıt s vámi, princezno. Pomozte mi vrátit sebe sama.
{14135}{14207}Ale, co mám dìlat?
{14228}{14253}Tohle.
{14287}{14400}Vy a já jsme jedno srdce a jedna mysl.
{14654}{14763}Take, tohle je tvá pravá podoba?
{15196}{15276}Celı svùj ivot, hledají svùj pùvod...
{15297}{15419}... ikdy jejich moc je stejná moci bohù.
{15466}{15512}A touha, která je vede...
{15512}{15644}... je tak silná, e i nemoné se stává skuteèností.
{15806}{15843}Sakuro.
{15843}{15881}Co se to dìje?
{16097}{16137}Co se to dìje?
{16137}{16212}Díky bohu, e ti nic není, Shaorane.
{16342}{16372}Princezno Sakuro.
{16394}{16417}Shaorane.
{16428}{16451}Sakuro.
{16451}{16490}Ty jsi nás zachránila.
{16490}{16554}Ale, jak se vám podaøilo se sem dostat, princezno?
{16567}{16622}Choas mi dal svou sílu.
{16645}{16695}Shaorane, prosím...
{16715}{16759}... zachraò ho.
{16770}{16797}Zachránit?
{16815}{16878}Chaos je teï...
{17364}{17389}Poèkat!
{17510}{17547}Pøece to jste vy.
{17547}{17575}Tady jste.
{17575}{17609}Dobøe naèaovanı.
{17609}{17631}Kdo to je?
{17631}{17694}Nejlepší kováøi v tomto mìstì.
{17694}{17753}Chtìl jsem po nich, aby opravili, skrèkùv meè.
{17780}{17836}Jak jsem slíbil...
{17857}{17923}... vrácím ten meè.
{17923}{17972}Dáme ho teï tobì.
{17981}{18004}Dobøe.
{18569}{18591}Pricezno.
{18631}{18674}Vìøíte mi?
{18697}{18722}Ano.
{19112}{19145}Shaorane!
{19159}{19212}Jestli uteèu, všechno ztratím.
{19232}{19275}Musím dál bojovat.
{19298}{19332}Shaorane!
{19390}{19422}Tady je tvùj meè.
{19422}{19445}Chytej!
{19682}{19726}Do toho, Shaorane!
{20247}{20276}Skrèku!
{20291}{20319}Shaorane!
{22062}{22096}Vyhrál jsi...
{22138}{22160}... Shaorane.
{22659}{22686}Sakuro.
{23046}{23077}On je...
{23113}{23192}Chaos je... jen mùj.
{23192}{23231}Co tím myslíte?
{23803}{23906}Take Chaos je ve skuteènosti stvoøen z princezninıch pírek?
{23924}{23953}Správnì.
{24026}{24067}Teï u to víte.
{24104}{24151}A tak mohu odejít.
{25735}{25855}Take shluk Sakuøinıch pírek si bìhem cesty vytvoøil mysl
{25875}{25934}... a nakonec z nich vznikl Chaos.
{25951}{26077}Take touil potom bıt s princeznou, protoe byl souèástí jejich vzpomínek?
{26150}{26181}Shaorane.
{26205}{26251}Jsi velmi silnı.
{26282}{26436}A proto si sem jistı, e se ti podaøí najít, všechna Sakuøina pírka.
{26528}{26552}Shaorane.
{26607}{26634}Budu na tebe èekat.
{26664}{26683}Dobøe.
{26788}{26815}Sakuro.
{26867}{26892}Dìkuji.
{27805}{27851}Krása.
{27851}{27895}Kolik jich je?
{27895}{27942}Zdá se, e hodnì.
{27942}{28047}Spousta a spousta Sakuøinıch pírek, je ještì nìkde tam venku.
{28047}{28084}Coe?
{28084}{28159}A kdy jako bude konec naší cesty?
{28179}{28219}To u chceš aby skonèila?
{28254}{28332}Já chci ještì pokraèovat dál.
{28332}{28364}Mokona, taky.
{28392}{28425}Jen se mì snaíte naštvat.
{28587}{28610}Princezno.
{28645}{28738}Jednoho dne, najdu i vaše poslední pírko.
{29119}{29167}Ty seš, ale tvrdohlavı, bratøe!
{29167}{29219}No nevím, kdo z nás dvou je tady tvrdohlavı.
{29219}{29317}Takto byste mluvit nemìla, princezno Sakuro.
{29317}{29393}Take, ty u taky, Yukito.
{29409}{29489}Já jen chtìla trochu cestovat, to je vše.
{29581}{29647}To není zorvna nejleší nápad.
{29647}{29713}Jestli o tom nevíš, tak seš princezna zemì Clow.
{29713}{29842}Nemùu tì nechat odejít samotnou, jen tak.
{29842}{29885}Take, staèí, kdy budu mít nìkoho sebou?
{29970}{30030}Pojïme tedy spolu.
{30102}{30165}Prosím, pojï.
{30307}{30380}Pojïme... tedy spolu!
{30946}{31039}Déš... ustal.
{31085}{31162}Jejich cesta je ještì daleko od svého konce.
{31212}{31269}Mezitím promyslíme náš další krok.
{32192}{32257}Pøešli jsme do nového svìta.
{32257}{32329}U se tìším, co je to za svìt.
{32329}{32390}Pøestaòte civìt a pojïme.
{32390}{32457}Jdeme, Shaorane.
{32457}{32516}Ano, princezno Sakuro
{32572}{32622}Poèkejte na mì!
{32877}{32953}Všichni, všichni, všichni...
{32953}{33015}... vám moc dìkujeme.