{1}{1}23.976
{39}{175}Já, Kouno Tooru, jsem mìl na této slavné, soukromé,| chlapecké škole, na ní jsem pøestoupil v pololetí,
{175}{234}dveøe své budoucnosti otevøené dokoøán, |ani bych si to uvìdomil.
{234}{311}Myslel jsem si, e budu ít na této škole otupující ivot,
{311}{348}ale co tu dìlá tahle holka?
{348}{372}Já jsem kluk!
{372}{422}Eh? Ale nosíš naøasenou sukni…
{422}{474}Co to kecáš? Ty budeš mít taky takovou.
{487}{540}Všichni tøi jsme na stejné lodi.
{540}{584}Pojïme udìlat vše, co bude v našich silách.
{584}{614}Ne!
{636}{705}A takhle zaèal mùj ivot princezny.
{762}{826}TaSHee's Gang uvádí
{2646}{2869}PRINCESS PRINCESS
{3134}{3252}První práce, Princezna Iniciátorka
{3488}{3544}Ahoj~!
{3715}{3754}Fandíme vám!
{3882}{3943}Snate se co nejvíc na místní kvalifikaci, ano?
{4170}{4224}Fakt, netušil jsem, e to bude mít takovı efekt.
{4237}{4287}Byli jsme ve všech venkovních klubech, e?
{4287}{4343}Jo, zbıvaj ty vnitøní.
{4380}{4476}Take… vnitøní, to je tìlocvièna a doja kenda a juda. |(Pozn. Pøekl.: Dojo je cvièištì pro bojové sporty.)
{4476}{4511}Ach, a ještì lukostøelba!
{4511}{4554}A plaveckı bazén.
{4554}{4603}Navíc je tu ještì nìkolik vzdìlávacích klubù.
{4603}{4680}V ádném pøípadì! To v ádném pøípadì neudìlám!|… dechovı orchestr, poèítaèovı klub…
{4704}{4778}Rozhodnì u nechci jít ven fandit.
{4792}{4828}Tak, jak jsem øekl…
{4859}{4984}Princezny budou kadı den povzbuzovat všechny|kluby, kterım se blíí kvalifikaèní zápasy.
{5012}{5032}Kadı den?!
{5032}{5053}Všechny kluby?!
{5072}{5120}Volejbal, basketbal, stolní tenis, baseball,
{5120}{5163}atletika, fotbal, tenis, kendo,
{5163}{5227}judo, lukostøelba a plavání - jedenáct sportovních klubù.
{5238}{5336}Dechovı orchestr, sbor, shogi, poèítaèovı klub - ètyøi kulturní kluby.|(Pozn. Pøekl.: Shogi jsou japonské šachy.)
{5336}{5369}Celkem patnáct klubù.
{5384}{5410}Patnáct?!
{5445}{5499}Prosím podívejte se na tuto sloku pro pøesnìjší pokyny.
{5513}{5539}Pøesnìjší pokyny?
{5539}{5654}Ano. Stojí tam kde a jak chválit naše vıborné soutìící.
{5654}{5786}Abyste posílili jejich morálku, musíte jim vìnovat |efektivní podporu, odvahu a motivaci.
{5786}{5854}Ehm, dìlal tohle prezident pøedtím taky?
{5854}{5877}Jistìe!
{5900}{5943}Fandil jsem jako hereèka!
{5943}{6044}A díky tomu naši soutìící nešli jen |na krajské zápasy, ale taky na národní.
{6044}{6068}Vánì?!
{6083}{6122}Znamená to, e se budeme muset takhle oblíct i mimo školu?!
{6122}{6180}To ne! To rozhodnì neudìlám!|To jsem tušil.
{6180}{6263}Tento vzhled je pøijatelnı jen proto, |e jsme v uzavøeném prostøedí...
{6263}{6299}To rozhodnì neudìlám!
{6299}{6333}To je v poøádku.
{6333}{6421}Vìtšina místních kvalifikací se pøekrıvá s rozvrhem, |take nemùete bıt na kadém zápase.
{6437}{6524}Take, aby to bylo pro všechny spravedlivé, nebudete muset fandit.
{6524}{6549}Vánì?
{6549}{6570}Ale…
{6595}{6682}Jestli vyhrají kvalifikaèní kolo, budete muset jet a fandit jim.
{6723}{6808}Jinımi slovy, pokud chcete obdret povzbuzení od princezen,
{6808}{6854}musíte vyhrát!
{6854}{6923}Take… kdy vyhrajou kvalifikace…
{6923}{6987}No, berte to jako odmìnu pro vítìze.
{6987}{7030}Smím se zeptat, zda president…?
{7030}{7108}U jsem vám øekl. Byl jsem i na národním finále.
{7158}{7198}Byla to krása!
{7198}{7267}Dosud nemùu zapomenout ten ivı obraz.
{7267}{7327}I soutìící z jinıch škol byli zaujati.
{7473}{7568}Take, co budeme dìlat, pokud budem |muset jít fandit na veøejnost?
{7568}{7633}Pokud to øekl prezident, nemùeme utéct.
{7633}{7650}Ne!
{7650}{7696}Prostì tam nepùjdeme.
{7696}{7730}To není moné.
{7730}{7747}Proè?
{7747}{7865}Pokud nìkdo zbìhne, vıhody pro všechny| princezny budou zrušeny.
{7865}{7901}Tak to je.
{7941}{8017}Pokud uteèeš, budeme tím trpìt taky.
{8017}{8095}Ale já to nikdy nechtìl dìlat a nechci ádné vıhody!
{8095}{8152}Teï nemá cenu øíkat takové vìci.
{8152}{8195}U jsi prošel pøijímacím obøadem.
{8195}{8251}Take musím jít mimo školu takhle?
{8251}{8277}V ádném pøípadì! Nemùu!
{8277}{8318}Pøestaò se chovat jako dìcko.
{8318}{8350}Cos to øekl, Shihoudani?!
{8350}{8405}Celou dobu si mì dobíráš!
{8405}{8441}To proto, e jsi sobeckı, Mikoto.
{8441}{8455}Yuujirou…
{8455}{8487}Sobeckı?! O èem to mluvíš?!
{8487}{8524}Co tím chceš øíct, e jsem sobeckı…|To je v pohodì. Pokud opravdu nechce, nenu ho.
{8524}{8547}To je v pohodì. Pokud opravdu nechce, nenu ho.
{8547}{8567}Kouno…
{8567}{8596}Shihoudani,
{8610}{8680}chtìl jsem se zeptat u pøedtím… |musíš mì fakt nenávidìt, co?!
{8782}{8793}Jo.
{8830}{8852}Lhal jsem.
{8877}{8928}Fajn, pøestaò kecat blbosti.
{8928}{8966}Pojïme a zkusme si další kostımy…
{8966}{9043}Sh-Shihoudani, já tì fakt nenávidím!
{9061}{9094}/Nauka o vedení domácnosti/
{9104}{9153}Tak, tady to je!
{9165}{9241}Další šaty jsou ve stylu zdravotní sestøièky!
{9241}{9264}Vyrobil jsem je právì toto odpoledne!
{9264}{9281}Natashou.|Vyrobil jsem je právì toto odpoledne!
{9281}{9306}Uklidni se.|Vyrobil jsem je právì toto odpoledne!
{9306}{9396}Téma je "tìce pracující vojáci o|šetøováni milujícími sestrami"!
{9396}{9424}To je Arisadùv nápad.
{9443}{9470}Prezidentùv nápad?
{9470}{9543}Ji jsem navrhl kostımy pro všechny kola!
{9551}{9674}Naši nervózní soutìící na kvalifikacích budou nìnì|uklidnìni vaším ošetøovatelskıch vzezøením!
{9674}{9761}A vás na krajskıch zápasech uvidí v odìvech |roztleskávaèek, získají kurá a sílu!
{9761}{9801}A na národních finálovıch zápasech…
{9820}{9885}budete mít romantické svatební šaty!
{9885}{9910}NIKDY!
{9920}{9934}Mikoto...|Nikdy! V ádném pøípadì!
{9950}{9979}Co máš za problém?|Nikdy! V ádném pøípadì!
{9994}{10051}Svatební šaty! Slyšíte, svatební šaty!
{10065}{10117}Proè musím bıt nevìsta?!
{10117}{10152}Proè dìláš takovı povyk?
{10152}{10217}Vdycky nosíš princeznovskı kostım.
{10217}{10254}To není stejnı!
{10254}{10290}Tohle jsou svatební šaty!
{10290}{10353}Proè musím bıt nìèí nevìsta?!
{10353}{10373}Malı dìcko.
{10395}{10428}Jsi vánì jak malı dìcko.
{10443}{10501}Vdycky mluvíš tak sobecky.
{10501}{10579}Shihoudani, take ty mì opravdu…
{10579}{10601}Nenávidím?
{10645}{10680}U jsem ti øekl, e jsem lhal.
{10704}{10723}Proè vypadáš, e se co nevidìt rozbreèíš?
{10723}{10754}P-poprvé moná, ale teï taky?|Proè vypadáš, e se co nevidìt rozbreèíš?
{10754}{10798}P-poprvé moná, ale teï taky?|Vánì to není pravda…
{10813}{10884}Jenom kdykoliv tì vidím, nemùu si pomoct a nepotrápit tì.
{10884}{10939}Yuujirou, cos právì øekl, nic nevysvìtluje.
{10939}{11007}Vánì? Ale já nemám zlé úmysly.
{11027}{11097}Kdybych tì opravdu nenávidìl, nechtìl bych tì ani škádlit
{11097}{11147}nebo tì oslovovat jménem.
{11147}{11177}A navíc…
{11177}{11229}nechceš náhodou, abych tì fakt nenávidìl, Mikoto?
{11281}{11327}Fajn. Tak tedy, co bychom mìli dìlat?
{11351}{11493}Aèkoliv fandíme, mùeme povzbudit morálku| ale ne souèasnì schopnosti, nemyslíte?
{11493}{11528}Co tím myslíš?
{11528}{11634}Jak jsem øekl, i s naším fandìním, |vısledky stejnì záleí na soutìících.
{11634}{11737}Ach, to je pravda. Kdy prohrajeme všechny kvalifikaèní |kola, pak nebudeme mít ádnı problémy.
{11737}{11754}Pravda.
{11754}{11787}Jste tak naivní.
{11941}{11990}Kadı trénuje tak usilovnì.
{12000}{12035}Mikoto, usmìj se.
{12035}{12053}Já vím!
{12102}{12128}Je to v poøádku?
{12128}{12213}Nìnì polote obì dlanì na ruku drící pálku.
{12213}{12258}Jo, to je v pohodì, ne?
{12258}{12302}U-udìlám vše, co je v mıch silách!
{12347}{12393}Je to dobré, e? Mùu pustit?
{12393}{12432}Dobré? Ach… to ach… honem…
{12432}{12503}Hej, je to fakt v poøádku?
{12503}{12558}No, takhle yoko-shiho nevypadá. |(Pozn. Pøekl.: Yoko-shiho je pøišpendlovací technika| v judu - uzavøení strany a pøidrení konèetin.)
{12558}{12578}Tak jsem to nemyslel!
{12619}{12671}Dobøe. Velmi dobøe, princezny.
{12854}{12869}Jsem utahanej.
{12883}{12961}Teï mùeme odpoèívat, ale bude to pokraèovat…
{12993}{13033}Hej, vzchop se, Mikoto.
{13118}{13242}Ale i kdy se budeme øídit pøíruèkou, kterou nám |prezident dal, bude to fungovat?
{13242}{13268}Kdo ví.
{13268}{13343}Tak jako tak, jistì to všechny potìšilo.
{13343}{13359}To je pravda.
{13401}{13419}Tsuji-senpai.
{13419}{13472}Zdá se, e jste mìli pernı den.
{13472}{13494}Um…
{13506}{13521}Copak?
{13521}{13543}Co se tıèe tohohle stolu,
{13543}{13585}nemohl bys nìco udìlat?
{13700}{13736}Takhle nemluv.
{13751}{13778}I na koleji,
{13778}{13829}dokud jste ostatním studentùm na oèích,
{13829}{13902}byste se mìli chovat jako princezny.
{13928}{13956}No, dìlejte, co je ve vašich silách!
{13971}{13982}Ano.
{14033}{14098}Funguje to, take nemáme na vıbìr.
{14136}{14185}Vedeš si velice dobøe, Kouno.
{14211}{14252}Pøestoupil´s dost pozdì
{14252}{14295}a nejdøív jsi na to nebyl zvyklı,
{14295}{14336}ale teï si vedeš skvìle.
{14353}{14458}U jsi na to zvyklı víc ne jsem já;| jsi jako Shihoudani èíslo 2!
{14491}{14561}Kdy se vìci zmìní, není lepší si rychle |zvyknout na novou situaci?
{14600}{14665}Pokud je to tak, je lepší vìdìt, co máš dìlat.
{14678}{14748}Odmítání všeho a dìlání vìcí polovièatì to nijak neusnadní.
{14760}{14840}Závislost na pıše tì jenom zatíí.
{14851}{14980}Aby byl ivot jednodušší je nìkdy nejlepší |pøizpùsobit se tomu, co po tobì lidé chtìjí.
{15032}{15046}Kouno…
{15058}{15131}Jak jsem øekl, je to jako staré rèení:
{15131}{15225}"Jsi-li v Øíme, chovej se jako Øíman."
{15240}{15298}Místo, aby tì k tomu donutili ostatní,
{15298}{15361}je snazší chtít to udìlat sám, ne?
{15385}{15465}Mìl bys to zkusit, Mikoto. Budeš šastnìjší.
{15465}{15517}Kdybych mohl, nesnail bych se tak moc!
{15517}{15599}Nevím, zda øíct, e jsi upøímnı nebo neschopnı.
{15599}{15633}Tak pardon!
{15880}{15951}Dle pøedpokladu, tyhle poslední dva |tıdny byly kompletnì vyèerpávající.
{15951}{16005}Nikdy víc… Nemùu se ani hnout…
{16027}{16049}Povzbuzujete i dnes?
{16049}{16107}No jo, práce, práce.
{16107}{16135}Dìkuji, e se tak snaíte.
{16135}{16208}Ale víš, i kdy povzbuzujeme,| ještì to nezaruèuje dobrı vısledek.
{16208}{16242}Tak to není.
{16256}{16331}Nehledì na to jakı klub, všichni jsou |šastní díky povzbuzování od princezen.
{16331}{16402}Všichni mají dobrou náladu a moná…
{16402}{16430}V ádném pøípadì!
{16465}{16477}Princezny!|
{16506}{16542}Princezny, vyhráli jsme!
{16542}{16591}Vyhráli jsme místní kvalifikaèní zápas!
{16700}{16800}Pøeklad + korekce: Morgana Ehran
{16820}{16921}Èasování: WelW(etkaAa)-hime
{16935}{16989}Dobrá práce, princezny!
{17014}{17094}Náš baseballovı tım byl nejslabší ve Fujimori.
{17113}{17187}Nevyhráli místní kvalifikaci u deset let,
{17187}{17252}ale tento rok byli neèekanì první.
{17274}{17314}Nejenom to…
{17314}{17355}Volejbalovı a basketbalovı tım také vyhrává.
{17355}{17414}Atletickı tım dokonce láme rekordy.
{17414}{17473}Tımy juda a kenda v jednotlivıch zápasech jsou také napøed.
{17473}{17524}Páni, jaké pøekrásné vısledky!
{17536}{17586}A to jen díky povzbuzování od princezen.
{17586}{17614}Jste opravdové princezny.
{17635}{17692}Take je to opravdu úèinné.
{17692}{17725}Jak je to jen moné…
{17866}{18031}Take pøíští nedìli, v deset hodin ráno, |pùjdou princezny na zápas a budou fandit.
{18031}{18048}Dobøe?
{18048}{18106}N-no, myslím, e musíme.
{18106}{18172}Kdy to øíká prezident, tak nemáme na vybranou.
{18172}{18233}V ádném pøípadì! To rozhodnì ne!
{18233}{18255}Mikoto!
{18255}{18345}Dìláš si srandu? Jít takhle ven?!
{18345}{18372}A jsme zase u toho…|Mikoto!
{18389}{18455}U jsme jim slíbili, e kdy vyhrají, |pùjdeme na zápas a povzbudíme je.
{18455}{18498}Slíbili jsme, e bychom šli, ale poøád…
{18498}{18587}nikdo si nemyslel, e bychom opravdu museli.
{18587}{18628}To jo, ale…
{18628}{18738}Podívej, nejsem jedinı, kdo nechce|jít ven v princeznovském pøevleku!
{18738}{18854}Ale kdy nepùjdem, vıhody princezen budou…
{18948}{19025}Pøijímat vıhody, ale nedìlat svou práci?
{19025}{19060}T-To…
{19078}{19178}V porovnání s pøevlékáním za princeznu, tak se mu nechová.
{19205}{19310}N-ne… Já vím, e to není správné.
{19310}{19368}Ale stejnì nechci jít ven, obleèenı za princeznu,
{19368}{19444}a nikdy jsem se nestaral, zda máme nebo nemáme vıhody!
{19444}{19472}Zmlkni! Spratku!
{19488}{19523}Z-zase jsi to øekl!
{19523}{19573}Pøestaò bıt tak sobeckı.
{19573}{19589}Yuujirou!
{19589}{19621}Stejnì jsem sobeckı èlovìk!
{19621}{19669}Dobøe, dobøe. Uklidnìte se.|Tak kdy  to víš, naprav to!
{19669}{19725}Kdybych se mohl tak lehce zmìnit, tak bych se tolik nesnail!
{19725}{19766}Uklidnìte se.
{19820}{19895}V kadém pøípadì, bìte prosím na ten zápas a fandìte, ano?
{19927}{19942}Ano.
{20179}{20251}/Lázeò/
{20273}{20303}/Rezervováno pro princezny/
{20656}{20741}/èasovatelka dostává nosebleed... :D/
{20820}{20872}Ach, Princezno! Dìkujeme za tvou práci!
{20872}{20900}Dohlííte na princezny?
{20900}{20947}Dìkuji, e tak èiníte.
{20947}{20971}To nic není, vánì.
{20983}{21106}Vdycky se najdou idioti, kteøí se chtìjí dostat blí |k princeznám, aby si je vyfotili, dokonce i na kolejích.
{21106}{21146}Ale pak staèí udìlat tohle.
{21158}{21175}Stát!
{21189}{21223}Vidíš, stejnì jako teï.
{21223}{21258}T-tak je to?
{21419}{21470}Jsem hotovı! Mùe jít další…
{21556}{21616}Hej, slyšel jsi ten hluk pøed chvíli?
{21617}{21688}Ach, to jen stráe princezen dìlají svou práci.
{21721}{21770}Dokonce i sprchování je sloité, co?
{21785}{21803}Yuujirou…
{21824}{21839}Co?
{21851}{21936}Zpùsob, jakım jsi dnes s Mikotem jednal byl pìknì krutı.
{21982}{22003}Já vím.
{22003}{22090}Co? Taky to víš?
{22090}{22116}Mmm…
{22116}{22147}Já vím.
{22172}{22203}I kdy to vím,
{22203}{22263}stejnì si ho poøád chci dobírat.
{22263}{22349}Máš ho vlastnì rád, ale pokud se k nìmu budeš takhle chovat,
{22349}{22410}nepochopí to a nakonec tì bude nenávidìt.
{22423}{22459}U se stalo.
{22459}{22477}Yuujirou…
{22477}{22505}Ale…
{22527}{22569}Mikoto je pøíliš upøímnı.
{22698}{22759}Take to je dùvod, proè ho chceš škádlit?
{22771}{22804}Necítíš to samé?
{23050}{23062}Já?
{23089}{23122}Nechceš si mì taky dobírat?
{23136}{23153}Tebe…?
{23167}{23195}Ty jsi jinı.
{23210}{23282}I kdy toho o tobì moc nevím, nevypadáš tak jednoduše.
{23282}{23327}Myslím, e jsi mi podobnı…
{23351}{23414}Ale teï se tì nebudu na nic ptát.
{23432}{23530}Mikoto musel vyrùst v milujícím prostøedí.
{23544}{23577}Závidím mu.
{23577}{23652}Právì. Proto si nemùu pomoct a neškádlit ho.
{23871}{23932}No, jen se musíš trochu ovládat, a si ho budeš dobírat pøíštì.
{24007}{24066}Správnì, ovládat se.
{24449}{24463}Není tady?!
{24463}{24514}Co tím myslíš, e tu Mikoto není?!
{24514}{24555}Øekl jsem, e ho nemùu nikde najít.
{24555}{24627}Ale zápas brzy zaène!
{24645}{24661}Co budeme dìlat?
{24661}{24688}Co mùeme dìlat…
{24688}{24775}Yuu-chan! Mikoto nezískal povolení jít ven.
{24794}{24820}Potom…
{24820}{24897}Senpaii, mohl bys ses po nìm znovu podívat na koleji?
{24897}{24927}Tooru, jdeme!
{25014}{25063}Yuujirou! Èekej, Yuujirou!
{25112}{25128}Yuujirou!
{25223}{25256}Co se dìje, Yuujirou?
{25307}{25359}Mikoto je poøád ve škole.
{25376}{25488}Soudì podle jeho povahy, neporušil by pravidla a nešel by ven.
{25506}{25571}To mu mùeme vìøit. Stoprocentnì.
{25592}{25611}Yuujirou…
{25611}{25671}I kdy neustále fòuká,
{25686}{25743}nikdy nechybìl.
{25791}{25848}Tak jako tak, pokud ho nebudeme moct rychle najít, budem v prùšvihu.
{25870}{25991}Pokud nìkdo zbìhne, vıhody pro všechny princezny budou staeny.
{25991}{26025}Tak to je.
{26068}{26093}Dobøe, pojïme.
{26166}{26205}Mikoto!
{26205}{26229}Mikoto!
{26229}{26244}Mikoto!
{26244}{26266}Mikoto!
{26277}{26298}Mikoto!
{26320}{26334}Mikoto!
{26334}{26383}Yuujirou, je èas.
{26397}{26446}Vzdejme to a pojïme jen my dva.
{26446}{26474}Je to opravdu v poøádku?
{26491}{26539}Má to vùbec cenu bez vıhod?
{26693}{26707}Není jiná monost.
{26732}{26745}Kouno?!
{26745}{26799}Stejnì je to vše, co teï mùeme dìlat.
{26799}{26847}No tak, jdeme a pøevleèeme se.
{26871}{26880}Kouno!
{26917}{26951}Èekej, Kouno.
{26968}{26995}Dìlej, Yuujirou.|/Nauka o vedení domácnosti/
{26995}{27020}Kouno!|/Nauka o vedení domácnosti/
{27112}{27126}Mikoto?
{27276}{27321}Tys tu byl u od rána?
{27353}{27373}Proè?
{27373}{27410}"Tak se mu nechová."
{27410}{27447}Shihoudani, neøekl jsi to?
{27447}{27524}Myslím, e je to pravda, tak jsem o tom pøemıšlel.
{27538}{27587}Tak, jak Kouno navrhl,
{27598}{27659}chtìl jsem to zkusit dìlat z mé vlastní svobodné vùle.
{27676}{27766}Tak jsem sem ráno šel, abych si zkusil kostım.
{27827}{27841}Mikoto…
{27841}{27939}Take se stále nemùeš rozhodnout |a trápil ses tím celou tu dobu?
{27939}{28000}Ale tohle je oblek sestøièky! Sestøièky!
{28000}{28049}Jak to mùete tak snadno nosit?
{28097}{28159}No, u je èas. Mikoto, bì a pøevleè se.
{28175}{28210}Ještì nejsem pøipravenı!
{28210}{28245}Bez øeèí.
{28245}{28279}Pøijdeme pozdì, jestli si nepospíšíš.
{28279}{28296}Poèkej chvíli!|Pøijdeme pozdì, jestli si nepospíšíš.
{28296}{28324}Poèkej chvíli!|Zvedni ruce, honem…
{28324}{28362}Zvedni ruce, honem…
{28362}{28379}Sundej to!
{28605}{28637}Je to nemoné…
{28637}{28684}Nemùeme vyhrát. Nemùeme vyhrát!
{28684}{28717}Ahoj~!
{29091}{29130}Odpuste nám to èekání!
{29143}{29188}Zápas právì zaèíná.
{29197}{29269}Budeme vám fandit, jak bude v našich silách.
{29269}{29351}Tak se nevzdávejte. Dìlejte, co mùete!
{29516}{29529}Strike!
{29569}{29582}Out!
{29582}{29610}Tøetí out, zmìna!
{29738}{29819}Konec hry. 9 ku 22; Fujimori vyhrává.
{29959}{30001}/Dnes rezervováno pro princezny/
{30105}{30171}Lázeò je vánì mnohem lepší.
{30183}{30253}Koupel v lázni je rozhodnì dobrá odmìna.
{30253}{30339}Za všechno pokoøení, kterım jsem trpìl, se to jenom sluší.
{30353}{30415}Bylo by divné, pokud bychom se zde nemohli dostat.
{30415}{30445}To je pravda…
{30445}{30480}Navíc,
{30490}{30575}fotbalovı tım a dechovı orchestr |taky vyhráli své kvalifikaèní soutìe.
{30595}{30653}Jo a tenisovı tım vyhrál taky.
{30653}{30676}Poèkat!
{30676}{30742}Take musíme tak jít ven znova?
{30742}{30766}Tentokrát neutíkej.
{30785}{30811}Shihoudani!
{30811}{30873}Mikoto, tak se mu nechová!
{30873}{30948}Dobøe, udìlejme, co je v našich silách a nazítøí fandìme.
{30948}{30978}Kouno, øekni nìco!
{30978}{31002}No, proè se prostì nevzdáš?
{31025}{31051}Kouno!
{31090}{31122}Prosím tì, prosím!
{31122}{31136}Malé dìcko.
{31136}{31174}Co… Co to øíkáš?!
{31174}{31208}Zmlkni, malı dìcko…
{31208}{31256}Ach, zase jsi to øekl!
{31349}{31417}www.mycolorfullife.blog.cz
{33459}{33514}Pøíštì: Yuujirova minulost
{33514}{33543}Yuujirova minulost.
