{1}{1}23.976
{68}{189}Já, Kouno Tooru, jsem mìl na této slavné, soukromé, |chlapecké škole, na ní jsem pøestoupil
{189}{247}v pololetí, dveøe své budoucnosti otevøené| dokoøán, ani bych si to uvìdomil.
{264}{325}Myslel jsem si, e budu ít na této škole otupující ivot,
{325}{363}ale co tu dìlá tahle holka?
{363}{390}Já jsem kluk!
{390}{440}Eh? Ale nosíš naøasenou sukni…
{440}{493}Co to kecáš? Ty budeš mít taky takovou.
{493}{552}Všichni tøi jsme na stejné lodi.
{552}{601}Pojïme udìlat vše, co bude v našich silách.
{601}{629}Ne!
{629}{721}A takhle zaèal mùj ivot princezny.
{747}{822}TaSHee's Gang uvádí
{2659}{2826}PRINCESS PRINCESS
{3144}{3262}Yuujirouva minulost
{3296}{3425}Tak tedy, dávejte na sebe pozor, prosím, a uijte si své letní prázdniny.
{3425}{3443}To je vše!
{3510}{3538}Letní prázdniny…
{3557}{3688}Pro nás práce princezen znamená, e nemùeme| mít opravdu pohodové prázdniny, co?
{3688}{3715}To je fakt…
{3715}{3800}Ale pro kluky ze sportovních klubù, kterım fandíme,
{3800}{3879}musí bıt kadodenní trénink ještì otravnìjší.
{3879}{3910}Otravnı…
{3954}{3986}Chápu...
{3986}{4082}Co se mnì tıèe, asi budu mít celé prázdniny èas.
{4145}{4175}Princezny!
{4197}{4323}Vrátíme se, ale je tak smutné, e neuvidíme princezny tak dlouho!
{4323}{4422}Take prosím, prosím, zanechte nám váš úsmìv v našich myslích!
{4422}{4444}Mnì taky!
{4444}{4462}I mnì!
{4462}{4487}Prosím!
{4569}{4589}A tímhle taky skonèíte.
{4609}{4629}Prezidente?!
{4629}{4685}Pokraèujete jinde.
{4685}{4703}Pokraèujete?
{4703}{4760}Ano, princezny!
{5122}{5222}Ano! Tenhle design je zaloen na obraze dam, které| se chystají na èajovı dıchánek, v klasickém stylu!
{5222}{5276}Ten pocit krásy a svìesti!
{5276}{5324}Aaach! Prostì úasné, princezny!
{5324}{5395}Ano, ano! ádanky na fotografie jsou k dostání tady.
{5395}{5456}Prosím zaplate vırobní poplatek.
{5456}{5557}Abyste zahnali osamìlost bìhem dlouhıch, letních prázdnin,
{5557}{5611}Studentská ráda vám doporuèuje nakoupit si,| co jsme pro vás zde pøipravili.
{5652}{5714}Aèkoliv je to poprvé, kdy jsme uspoøádali fotografickou burzu,
{5714}{5756}je to neèekanı úspìch.
{5756}{5822}To musí bıt zase prezidentùv nápad.
{5822}{5908}Ne! Nechci, aby si mì kadı takhle fotil domù!
{5908}{5927}To rozhodnì nechci!
{5927}{6019}Buï trpìlivı! Taky z toho nìco vytìíme.
{6019}{6099}Získáš tak nìjaké peníze, abys mohl o prázdninách randit, ne?
{6145}{6209}Tak tedy, všichni se starejte o své zdraví a a se vám nic nestane!
{6209}{6275}Doufáme, e všichni budete mít pøíjemné prázdniny!
{6471}{6526}Naschle, princezny! Dìkujeme!
{6526}{6550}A se dostanou domù, uvidí skuteèné holky.|Naschle, princezny! Dìkujeme!
{6550}{6616}A se dostanou domù, uvidí skuteèné holky.
{6616}{6692}Proè se ohlíejí, aby vidìli ty falešné, ne odejdou?
{6692}{6722}Nejspíš aby se utìšili.
{6722}{6744}Jsem unavenı. |Nejspíš aby se utìšili.
{6744}{6835}I kdy jim dají jejich holky kopaèky, ve škole mají nás.
{6871}{6894}Díky za vaši tìkou práci!
{6894}{6907}Fotografická burza mìla obrovskı úspìch!|sakamoto-sama!
{6907}{6950}Fotografická burza mìla obrovskı úspìch!
{6950}{7025}Nemyslím, e by to bylo nìco tak úasného, e| si to zaslouí gratulaci od Sakamota-sama,
{7025}{7077}kterému se všichni klaní a respektují ho, kdekoliv se objeví…
{7077}{7114}To je fakt.
{7114}{7187}Umm… Kouno, ty nejedeš domù?
{7187}{7262}Zùstanu na koleji po celé prázdniny.
{7262}{7293}Shihoudani také?
{7293}{7307}Jo.
{7307}{7335}Já jedu domù!
{7380}{7437}Pøesnì jak jsem si myslel.
{7437}{7543}A neodjídíš ani první den prázdnin, ale hned po ukonèení.
{7565}{7660}Jsi tak bezcitnı, opouštíš nás a vracíš se ke své enì!
{7660}{7723}Jenom sis s námi pohrával? Jsi tak krutı, Mikoto-san!
{7723}{7864}Ne, upøímnì jsem to ji pochopil. Náš vztah je tak slabı.
{7864}{7921}Popravdì je náš vztah køehkı jako jedinı kousek papíru!
{7921}{7999}Hej, to u by staèilo! Pøestaòte s tou kravinou!|Popravdì je náš vztah køehkı jako jedinı kousek papíru!
{8034}{8105}Jak se dalo pøedpokládat, kamarádi se nedají srovnávat s pøítelkyní.
{8105}{8144}Jak bezcitnı mu.
{8144}{8200}Zùstávám s vámi kadı den a stejnì jsem bezcitnı?!
{8200}{8260}Sotva vídám svou pøítelkyni! To je bezcitné vùèi ní!
{8260}{8348}Chci jí to jen vynahradit! Co je na tom špatného?!
{8348}{8394}My si nemyslíme, e je na tom nìco špatného.
{8417}{8467}To je dobøe, e máš tak hlubokou lásku, ne?
{8467}{8502}Bıt zamilovanı je tak závidìníhodné.
{8502}{8567}A-Ale proè se se mnou tedy takhle hádáte?!
{8601}{8648}Oèividnì pro to, e tì nenávidím.
{8713}{8745}U jsem øekl, e kecám.
{8773}{8847}Ale vypadáš tak šastnì, e uvidíš svou holku.
{8847}{8956}Jen se bojíme, e z ní budeš tak mimo, e zapomeneš| a zbloudíš se od své práce princezny.
{8956}{8988}Tak ti to chcem pøipomenout.
{9018}{9062}Mùeš nás ujistit, e se to nestane?
{9087}{9125}Nech mì, abych ti poloil jednu otázku.
{9125}{9229}Kdyby nastal konflikty mezi poadavky bytí| princeznou a poadavky tvé pøítelkynì, co by sis zvolil?
{9262}{9403}/Co bych mìl dìlat? Nikdy jsem nechtìl vzít práci princezny. |Samozøejmì, e bych chtìl vyhovìt poadavkùm mé dívky. |Ale mé princeznovské povinnosti mají pøednost. Aaah… Ale i tak…/
{9424}{9456}Nebuï nerozhodnı!
{9456}{9526}Nebijte mì! A navíc papuèemi!
{9526}{9590}Zmlkni! To je jasné, e by sis mìl vybrat práci princezny!
{9590}{9628}Kruci, nemùeme bıt tak nedbalí!
{9628}{9695}Kdyby si vybral svou dívku, mohl by zanedbávat svou práci.
{9695}{9712}Co bychom mìli dìlat?
{9712}{9781}Dává pøednost své holce, to je jeho slabina!
{9781}{9803}Mikoto.
{9803}{9833}Co?!
{9833}{9962}Pokud nebudeš dìlat svou práci princezny, hodím øeè s tvou dívkou.
{9987}{10072}/V tom pøípadì by systém princezen byl odhalen, stejnì tak oblékání| jako princezna by bylo odhaleno -> "Nejhorší monı scénáø!"/
{10089}{10155}Prosím ušetøete mì toho! Prosím vás!
{10155}{10233}Správnì. Koneènì vidíš, z èeho vycházíme.
{10233}{10330}Chtìl jsem odjet domù, ani bych vám øekl,
{10330}{10386}ale bál jsem, e øeknete, e jsem bezcitnı, tak jsem si to rozmyslel.
{10386}{10441}Mìl jsem jet prostì domù a nic vám neøíct!
{10441}{10458}Idiote.
{10458}{10571}I kdybys jel domù, ani bys nás øekl, utahovali| bychom si z tebe, a bychom se znovu sešli.
{10586}{10641}Beze slova odejít… Takovı bezcitnı chlap, no ne?
{10641}{10731}S-Shihoudani… K-Kouno taky…
{10731}{10800}Opravdu vás nenávidím!
{10800}{10853}Nezapomeò na svou práci princezny!
{10853}{10906}J-Je to vánì v poøádku?
{10906}{10950}V pohodì.
{10950}{10997}Je to pro nìj takhle lepší.
{10997}{11064}Jinak, Sakamoto, ty nejedeš domù?
{11064}{11147}Ne, zanedlouho tu bude setkání Studentské rady.
{11168}{11197}To je kruté.
{11197}{11269}Mimochodem, pokud budete poblí bìhem| prázdnin, stavte se u mì a pobavíme se.
{11269}{11282}Jasnì!
{11282}{11307}Ahoj, všichni.
{11307}{11360}Hej, senpaii, jedeš taky domù?
{11360}{11399}Ne, zùstávám tady.
{11399}{11491}Ale je tu hroznı problém s kolejemi bìhem prázdnin.
{11510}{11593}Pøes den tam není ádná klimatizace,| take tam mùe bıt pìknì horko!
{11593}{11638}Ujistìte se, e to zvládnete.
{11720}{11811}Pøeklad + korekce: Morgana Ehran
{11835}{11931}Èasování: WelW(etkaAa)-hime
{11964}{12017}Vedro… vedro…
{12017}{12104}ádná klimatizace kdy jsou letní prázdniny;| to si snad dìláte srandu!
{12104}{12148}Stále tu jsou studenti.
{12161}{12216}Takhle se nedá uèit!
{12224}{12255}S tím nic nenadìláme.
{12255}{12347}Nejsou tu skoro ádní studenti, take by její spuštìní byla ztráta penìz.
{12347}{12443}Vdy já vím! Ale vedro je vedro!
{12443}{12503}"Vedro, vedro!" Kdy to øíkáš, jenom je ostatním ještì vìtší horko.
{12538}{12583}Ugh… pojïme do obchodu.
{12583}{12623}Tam se jistì dlouho zdríme.
{12623}{12666}A pak zajdeme k Sakamotovi.
{12666}{12690}To je moc náhlé.
{12690}{12735}To je fakt trochu hrrr, co?
{12735}{12781}Mimochodem, zítra mám narozeniny.
{12828}{12868}Tak tedy, všechno nejlepší.
{12868}{12898}Díky.
{12913}{12963}Neøíkej, chceš to oslavit?
{12963}{12986}Ani ne.
{13006}{13061}Nevadilo by mi sníst si nìjakı ten dort…
{13061}{13100}Neøíkám, e to musí bıt celı dort.
{13100}{13162}Dobøe! Zítra v obchodì koupím koláè…
{13162}{13223}Bylo by lepší ho koupit v pekaøství! Lakomèe!
{13223}{13269}Aspoò jsem ochotnı ti nìjakı koupit!
{13292}{13383}Shihoudani z prvního roèníku, tøídy D, má telefonát od své rodiny.
{13383}{13431}Opakuji: Shihoudani z prvního roèníku, tøídy D, má telefonát od své rodiny.|Hej, Yuujirou, to je pro tebe.
{13431}{13515}Opakuji: Shihoudani z prvního roèníku, tøídy D, má telefonát od své rodiny.
{13515}{13571}Prosím, zvednìte nejbliší telefon.
{13813}{13866}Ahoj? Co je, mami?
{13866}{13892}Dìje se nìco?
{13923}{13942}Zítra?!
{13959}{14059}Ale u jsem ti øekl, e mám plány na celé| prázdniny, take domù nepøijedu.
{14077}{14104}Ah, to je pravda…
{14128}{14228}V tomhle vìku je trapné slavit narozeniny s rodinou.
{14247}{14293}Jo, to je v pohodì.
{14293}{14330}Neboj se, dìlám vše, co je v mıch silách.
{14627}{14686}Hej, stalo se nìco? Ten telefonát?
{14686}{14784}Nic moc. Ptali se mì, jestli na svı narozeniny nepojedu domù.
{14784}{14834}Tak bys mìl jet.
{14834}{14917}To by bylo nemilosrdné, nechat tì tu samotného, co myslíš?
{14950}{14989}Nebyl bys osamocenı?
{15009}{15066}Yuujirou, vánì ti to nevadí?
{15205}{15221}Kouno.
{15244}{15282}Pojïme zítra balit holky!
{15344}{15426}To by byly pìknì nudnı narozeniny, kdybychom byli jen my dva.
{15426}{15489}Pojïme najít nìjaké holky a pobavme se!
{15538}{15558}Nemùeš?
{15698}{15726}Ok, rozumím.
{15733}{15760}Díky.
{16045}{16082}Jdem fakt balit holky?
{16082}{16095}Jo!
{16095}{16174}Jestli se chceš bavit, je v pohodì, jestli jsme to jen my dva.
{16174}{16226}Mùeme zajít do herny nebo na karaoke.
{16226}{16309}Tooru, pokud bychom šli na taková místa spolu, bylo by to rande.
{16375}{16396}Jdem balit holky!
{16396}{16475}Správnì! Nejdøív musíme najít nìjaké pìkné holky!
{16475}{16533}Mimochodem, jakı je tvùj typ holek, Tooru?
{16533}{16612}Hmm… Pokud bych si mìl vybrat, mám rád utìšovatelky.
{16612}{16659}Jako Sakamoto-sama?
{16659}{16710}Jo! Jo! Jako Sakamoto-sama!
{16791}{16838}Proè jsi musel uvézt pøíklad se Sakamotem?!
{16838}{16885}Normálnì bys pouil idoly èi hereèky!
{16885}{16932}Ale Sakamoto-sama je utìšitelka.
{16976}{17019}I tak, je to…
{17034}{17104}Jinak, jakı je tvùj typ?
{17104}{17122}Velkı prsa!
{17143}{17212}Velká prsa, o nich mluvím, nejsou jako lilky,
{17212}{17289}jsou to rozkošná prsa, do nich mùeš ponoøit svou tváø.| (Pozn. Pøekl.: Yuujirou, jsi mentál XD - èasovatelka souhlasí :D)
{17289}{17339}S tvojí tváøí?
{17339}{17377}To nemá nic spoleèného s mou tváøí.
{17377}{17450}Bylo by divné, kdybys jako mu nebyl zaujat enskımi prsy.
{17450}{17510}To ano ale není to trochu pøehnané?
{17510}{17601}Napøíklad, kdyby Mikoto mluvil o sexu,| nemyslíš, e by to bylo trochu divné?
{17601}{17741}Mám rád typ, kdy ji mùu pevnì chytnou |za útlé kotníky a dret její prsa svıma rukama!
{17755}{17780}Rozhodnì.
{17780}{17842}Mám závra, jen na to pomyslím.
{17859}{17882}Dejme si pauzu.
{17994}{18054}Nemùeme najít… ádné utìšitelky ani velká prsa.
{18054}{18103}To nebude lehké.
{18103}{18177}Hej, co ty holky támhle?
{18177}{18230}Ne, ne! Na nìkoho èekaj.
{18230}{18279}Poøád sledují hodinky.
{18279}{18331}V tomhle si fakt dobrı.
{18347}{18398}Tak, co tamty tøi?
{18398}{18445}ádná velká prsa. Ani nápad.
{18445}{18464}Hej, ty…
{18464}{18521}Bì sbalit tu, která sleduje svùj mobil.
{18521}{18545}Taková velká prsa!
{18560}{18623}Hej, ta je sama. Co já?
{18623}{18696}No, já mám dnes narozeniny!
{18696}{18720}Poèkej chvíli!
{18720}{18756}Dámy!
{18820}{18852}Jste samy?
{18852}{18890}My jsme taky sami.
{18890}{18949}Právì jsme si øíkali, e zajdem na bowling; šly byste s námi?
{18949}{18987}Zkoušejí to na nás?|Právì jsme si øíkali, e zajdem na bowling; šly byste s námi?
{18987}{19025}Nebo mùem jít na karaoke…
{19025}{19089}Idiote! To bude po bowlingu.
{19089}{19167}Och, jasnì. Tak, mùem zajít na bowling a pak…
{19167}{19184}To je fakt!
{19198}{19265}Jste slepí?!
{19265}{19333}Jsme kluci! Co si myslíte, e dìláte, kdy to na nás zkoušíte?!
{19333}{19351}Yuujirou!|Kluci?! To jste nás pìknì napálili, vypadáte jak holky!
{19351}{19438}Kluci?! To jste nás pìknì napálili, vypadáte jak holky!
{19438}{19471}Yuujirou!|To vy jste si to popletli!
{19471}{19487}To vy jste si to popletli!
{19487}{19510}O èem to mluvíš?
{19510}{19547}Yuujirou! Nech to bıt!
{19547}{19592}Yuujirou! Dìlej! Pojïme!
{19592}{19622}Yuujirou!
{19754}{19782}Co je to s tebou?
{19782}{19837}Málem se poprat kvùli takové blbosti… to nejsi ty.
{19837}{19919}Jen jsem se chtìl bavit, ne mì ti chlápci vyrušili.
{20158}{20206}Co budeme dìlat? Pokraèujeme v shánìní holek?
{20206}{20267}Nebo mùeme jít na film,
{20267}{20314}nebo do herny nebo na karaoke?
{20314}{20351}Balíš mì?
{20377}{20396}Vrame se.
{20417}{20443}Na kolej.
{20443}{20465}Yuujirou!
{20511}{20584}A pak, chci, aby sis poslechl mùj pøíbìh.
{20610}{20632}Yuujirou…
{20886}{20996}Oba mí rodièe zahynuli pøi nehodì. |Pak mì mùj strıc a má teta adoptovali.
{21015}{21102}Byli na mì milí, ale i tak, jsem šel sem.
{21124}{21175}Ztratil jsem rodièe a nemám kam jít.
{21175}{21309}Asi bych to nemìl sám øíkat, ale |myslím, e jsem mìl pìknì tìkı ivot.
{21379}{21488}Vdycky jsem si myslel, e jsi moná mìl stejné zkušenosti jako já.
{21609}{21674}Vypadá to, e jsi mluvil v telefonu s mámou,
{21674}{21733}ale proè nechceš jet domù?
{21750}{21840}Musí tu bıt dùvody, které je tìké vyjádøit.
{21888}{22002}Neztratil rodièe jako já, jeliko jeho máma mu volala.
{22002}{22076}Moná se nìco stalo mezi ním a jeho mámou?
{22092}{22128}Nebo jeho tátou?!
{22192}{22285}Mùe to bıt kvùli kráse tohoto kluka, e tajil svou sloitou minulost?!
{22379}{22391}Tooru...
{22423}{22444}C-Co je?!
{22444}{22562}Kdy ti povím pravdu, mohlo by to zmìnit tvùj postoj vùèi mì.
{22562}{22654}/Opravdu mìl ty kruté zkušenosti jaké mívají lidi z telenovel?/
{22654}{22689}Nepodceòuj mì!
{22689}{22759}Nechvástám se, ale má minulost byla taky smutná!
{22778}{22879}Tak… a uslyšíš cokoliv, nemìò svùj postoj ke mnì.
{22879}{22892}Jistì!
{22989}{23075}Vyrostl jsem v neúplné rodinì, sám se svou matkou.
{23094}{23165}Mùj otec zemøel na nemoc, kdy jsem byl hodnì malı.
{23165}{23264}Take klíèové slovo je chudı? |Nebo byl nucen spáchat s matkou sebevradu?!
{23264}{23321}Ale to mi nevadilo.
{23375}{23526}Nemìl jsem otce, s kterım bych zaèínal,| take jsem nevìdìl, jaké to je, ani ádného nechtìl.
{23526}{23623}Mimoto, jsem vdycky musel pøemıšlet, jak| podpoøit mou matku, kdy jsem byl malı,
{23623}{23690}take jsem nemìl èas myslet na nic jiného.
{23721}{23740}Ale…
{23758}{23781}Ale?
{23810}{23859}Kdy jsem byl ve ètvrté tøídì základní školy,
{23884}{23983}tøídní uèitel byl pøíjemnı a shovívavı.
{23983}{24084}Jak to mám øíct? Cítil jsem, e byl ideální postavou otce.
{24084}{24191}Kdybych mìl otce, pøál jsem si, aby byl jako on.
{24318}{24420}Tak abych byl jako ten uèitel, stal se ze mì vynikající student.
{24451}{24527}Uèitel mi taky nadroval nad ostatními.
{24550}{24661}Pak jednoho dne po škole jsem byl poádán, abych zùstal ve tøídì.
{24825}{24907}Uèitel vstoupil dovnitø, ale vypadal jinak ne normálnì.
{24907}{24998}Vypadal velmi vzrušenì a nemohl popadnout dech.
{24998}{25079}Chytil mì za ramena svımi zpocenımi dlanìmi…
{25079}{25126}Pak… Co se stalo pak?!
{25346}{25431}Zeptal se mì, zda bych mu dal svou mámu.
{25455}{25585}No, zdá se, e ani bych si toho všiml, zamilovali se do sebe navzájem.
{25602}{25678}Tak jsem mu jen øekl, je to v pohodì,
{25678}{25754}protoe jsem u cítil, e by byl perfektní otec.
{25754}{25826}A poté to šlo vánì dobøe.
{25826}{25925}Nyní mám mladšího bráchu a ijí spolu šastnì jako rodina.
{25925}{25962}Jen vteøinku…
{25983}{26014}Ponurá minulost?
{26014}{26037}Ne.
{26037}{26083}Krutá ivotní zkušenost?
{26083}{26109}Taky ne.
{26109}{26193}Tak proè vypadáš tak znièenì?!
{26193}{26289}To proto jsem ti øekl, e nehledì na to, co| ti øeknu, nemùeš zmìnit zpùsob, jak mì bereš.
{26289}{26354}Ale nìco takového øíkáš, jen kdy hodláš mluvit o nešastné minulosti!
{26354}{26463}Prosím tì! Tak proè nechceš jet domù?
{26463}{26501}Je to šastná rodinka, ne?
{26519}{26541}Beze mì ano.
{26813}{26887}Ne e bych nechtìl domù.
{26887}{27023}Jen se cítím jako outsider, kdy je vidím a já nesnáším ten pocit.
{27153}{27224}Kdy vidím svou mámu, tátu a malého brášku, všechny tøi pohromadì,
{27224}{27307}jen si myslím "Ach, jaká dokonalá rodina."
{27307}{27389}Ale kdy tam jsem, kouzlo je ztraceno.
{27389}{27450}Cítím mezi námi odstup.
{27450}{27515}Vím, e bych se mohl snait bıt blízko nim.
{27515}{27564}Ale nehledì na cokoliv, poøád to nemùu zmìnit.
{27564}{27642}Nemusíš bıt tak pesimistickı.
{27642}{27663}Jo.
{27681}{27733}Moná to bylo špatnì u od zaèátku.
{27733}{27786}Jako zmáèknout špatné tlaèítko.
{27805}{27947}Jsem vánì šastnı, e se vzali, protoe jsou to lidi, které mám nejradši.
{27947}{28059}Ale zároveò se poøád cítím trochu nepohodlnì,
{28059}{28153}jakoby mi mùj uèitel vzal mou mamku…
{28323}{28380}a oba dva mì opustili.
{28380}{28465}Ty jsi ten, kdo si zachovává odstup, není to tak, Yuujirou?
{28481}{28506}Je to tak.
{28506}{28602}Ve škole vdycky bdíš nad ostatními s pıchou,
{28618}{28673}proè jsi tak slabı pøed svou rodinou?
{28693}{28720}To je fakt…
{28767}{28838}Nezajímá mì, co si ti lidi ze školy myslí,
{28838}{28953}ale bojím se, e bych se odcizil a byl opuštìn svou rodinou.
{28968}{29004}Jenom jí.
{29004}{29044}Vánì?
{29112}{29137}V tom pøípadì…
{29137}{29162}Co?
{29162}{29229}Zkus to øíct své mámì.
{29255}{29290}Øekni jim, co si myslíš.
{29312}{29383}Nezmìní se to, pokud se jim budeš vyhıbat.
{29383}{29428}Bude se to dít poøád.
{29428}{29511}Ale k èemu to bude? U je to šest let.
{29511}{29553}Proto jim to musíš øíct teï.
{29572}{29642}Kdy je to minulost, nebude to bolet tak moc teï.
{29656}{29691}I mnì jsi to øekl.
{29846}{29936}Není ádnı èasovı limit na napravování našich chyb.
{29954}{30019}Pokud byly tlaèítka špatnì zmáèknuty, zruš je.
{30019}{30107}Jestli to nebude fungovat, mùeš se vdycky vrátit sem.
{30133}{30273}A aèkoliv nemùu vyléèit tvé rány, mùu tì vyslechnout, tak jako teï.
{30313}{30331}Tooru…
{30346}{30403}Nebo ti nejsem dost dobrı?
{30720}{30775}Ne, to je v poøádku.
{30827}{30861}Ale Tooru-kun!
{30881}{30948}To jsou fráze, které øíkají milenci.
{30965}{31012}Díky za pøemlouvání,
{31012}{31089}ale mezi námi mùe bıt pouze platonická láska, Tooru-kun.
{31089}{31138}Proè to mám s tebou dìlat?
{31152}{31192}Èistá láska není špatná!
{31192}{31211}Pøestaò!
{31211}{31276}Èistá láska! Èistá láska! Platonická!
{31302}{31359}Pøíští díl: Chycená Princezna
