{1}{1}23.976
{37}{178}Já, Kouno Tooru, jsem mìl na této slavné, soukromé, |chlapecké škole, na ní jsem pøestoupil
{178}{230}v pololetí, dveøe své budoucnosti otevøené|dokoøán, ani bych si to uvìdomil.
{230}{301}Myslel jsem si, e budu ít na této škole otupující ivot,
{301}{336}ale co tu dìlá tahle holka?
{336}{359}Já jsem kluk!
{359}{418}Eh? Ale nosíš naøasenou sukni…
{418}{466}Co to kecáš? Ty budeš mít taky takovou.
{466}{530}Všichni tøi jsme na stejné lodi.
{530}{577}Pojïme udìlat vše, co bude v našich silách.
{577}{615}Ne!
{615}{693}A takhle zaèal mùj ivot princezny.
{736}{815}TaSHee's Gang uvádí
{2654}{2862}PRINCESS PRINCESS
{3146}{3246}Chycená Princezna
{4013}{4054}Úasné!
{4054}{4127}Vypadají jako andìlé.
{4142}{4187}Musím vás najít.
{4680}{4724}Vidìly jste to, princezny?!
{4724}{4760}Skvìle!
{4760}{4815}To bylo opravdu cool!
{4843}{4891}Mikoto, pracuj!
{4908}{4939}Dìlejte, co mùete!
{4956}{5038}Dám další bod! Prosím sledujte mì!
{5038}{5059}Mì taky!
{5072}{5090}Mì taky!
{5122}{5191}Pøítomnost princezen jistì oivuje hru, e?
{5191}{5273}Oh, Prezident Arisada! A Sakamoto je tu taky.
{5273}{5313}Dìkuji za vaši tvrdou práci v takovı horkı den.
{5326}{5350}Tady je vaše odmìna.
{5350}{5381}Oh, dìkuji ti!
{5399}{5508}Tady to není tak špatné, ale venku u sportovních klubù...
{5547}{5568}Kvùli tomu...
{5601}{5649}Musí pro vás bıt pìknì tìké pracovat i v létì.
{5649}{5702}Take, proè jsi tady, Sakamoto-sama?
{5702}{5737}Um...
{5814}{5983}Sakamoto-sama, jakoto kandidát na dalšího| Prezidenta Školní Rady, se má pøes léto co uèit.
{6017}{6057}Sakamoto to má taky pìknì drsné.
{6152}{6224}Yutako-kun, omlouvám se, e jsem| tì musel poádat, abys pøišel,
{6224}{6302}ale u jsme ti øekli, e máme pøes letní prázdniny práci,
{6302}{6354}take mohl bys prosím pøestat dìlat ksichty?
{6354}{6471}Pravdìpodobnì jsi zapomnìl všechno o práci|princezen pøedtím, ne jsem ti zavolal, co Mikoto?
{6471}{6522}Je to nìco, na co chci zapomenout úplnì.
{6522}{6563}Opravdu si myslíš, e se ti to povede?
{6563}{6638}Není ádnı zpùsob, jak bys mohl nechat všechnu práci na nás;
{6638}{6669}nakonec jsme všichni na stejné lodi.
{6669}{6731}Dobrá, je èas jít povzbudit další klub.
{6731}{6786}Pus mì! Udìlám to!
{6786}{6800}Poèkejte!
{6839}{6890}Mizí vám make-up.
{6914}{6970}Mizí jednoduše, protoe se potíte.
{6970}{7042}Radìji byste mìly jít do maskérny, která je|rezervovaná pro princezny a upravit se.
{7042}{7090}Princenz by mìly stále vypadat krásnì.
{7090}{7127}Oh, tak pùjdeme.
{7127}{7150}Kluci!
{7170}{7282}Sakamoto-sama, jen pro pøípad, jdi s princeznami.
{7295}{7308}Ano.
{7430}{7466}/Rezervováno pro princezny - Maskérna/
{7466}{7537}Hmm... u je to trochu lepkavé.
{7537}{7609}Znaèka, kterou jme pouívali pøedtím, vydrela déle.
{7609}{7670}Ale tahle znaèka má lepší, prùsvitnìjší vzhled.
{7670}{7705}Ahh! Víc ne!
{7705}{7813}Proè ví studenti vyšší støední školy tak moc o make-upu?!
{7813}{7849}Protoe jsou to vìci pro naši práci.
{7867}{7902}Je to takhle dobré, ne?
{7917}{7963}napøíklad, mùeš dát své pøítelkynì nìjaké rady.
{7963}{8064}Ne, Megumi-san nevypadá, e by pouívala make-up.
{8064}{8140}Jo, myslí si, e nenosit make-up je roztomilejší.
{8140}{8227}Ahh, take jméno tvé pøítelkynì je Megumi-san?
{8227}{8316}Myslí si, e je to bez make-upu nejlepší? To je cool-
{8316}{8335}Shihoudani!
{8335}{8420}A zdá se, e je jeho pøítelkynì starší, ne on...
{8420}{8478}V tom pøípadì, budeš pod pantoflem. To není dobré.
{8497}{8536}To staèí!
{8552}{8575}U jste hotové?
{8575}{8619}Ah, promiò, e jsi musel èekat.
{8619}{8657}Tak, práce... práce!
{8657}{8692}Neignorujte mì!
{9001}{9031}Co se dìje, Tooru?
{9049}{9136}Oh, cítil jsem, jako by nás nìkdo pozoroval.
{9313}{9359}Nikdo tu není.
{9359}{9395}Moná je to jen moje pøedstavivost.
{9395}{9420}Co se dìje?
{9420}{9466}Ne, to nic.
{9466}{9525}Pospìšme si a pojïme nìkde, kde je chladnìji.
{9525}{9595}Hej, proè chceš tak najednou pracovat?
{9595}{9675}Zmlkni! Jen tu nechci chodit takhle!
{9675}{9715}Kouno, pojï!
{9744}{9769}Poèkejte na mì!
{9933}{9953}/Nauka o vedení domácnosti/
{10435}{10480}Co... Co to je?
{10480}{10515}Kdo to mohl udìlat?
{10515}{10561}To je naše obleèení!
{10561}{10588}Ne! Nechoïte dovnitø!
{10612}{10634}Sakamoto...
{10634}{10754}Musíme to tak nechat! A moná je to uvnitø nebezpeèné.
{10754}{10804}Mìli bychom jít najít Prezidenta Arisadu.
{10804}{10876}Oh! Není divu, e jsi kandidát na dalšího prezidenta.
{10876}{10919}Eh... no, to je...
{10919}{10954}Není divu.
{11122}{11175}Zdá se, e tu nikdo není, Arisado.
{11190}{11249}Není problém s obleèením princezen... ani skvrny.
{11249}{11396}I tak, všechny ty rùe... musely bıt|velmi drahé. Jaké plıtvání!
{11396}{11458}To není ten problém.
{11456}{11558}Okamitì nás o tom informovat| bylo dobré rozhodnutí, Sakamoto-sama.
{11558}{11688}Jestli se o tom dozví ostatní studenti, stane se z toho| velkı problém a mohlo by se nám to vymknout z rukou.
{11688}{11796}Ne, vlastnì, opravdu nevíme, co dìlat.
{11832}{11853}C-Coe?
{11853}{11891}Nic-
{11891}{11972}Dnes jsou všichni èlenové Nauky| o vedení domácnosti na prázdninách, e?
{11972}{11994}Kde je Natashou-senpai?
{11994}{12025}Dnes jsem ho nevidìl.
{12025}{12110}V tom pøípadì to musí bıt nìkdo z venku.
{12110}{12176}Myslíte, e je za tím špatnı úmysl, Arisado?
{12207}{12230}Mohl by to bıt stalker?
{12257}{12277}Stalker?!
{12277}{12326}Není to nutnì ten pøípad.
{12326}{12412}Nìkdo tu zøejmì nechal ty kvìtiny jen náhodou.
{12412}{12443}To je nemoné...
{12443}{12484}Je to jen spekulace.
{12511}{12592}No, pro teï nechte zbytek na nás.
{12592}{12649}Pokraèujte prosím ve své práci, princezny.
{12674}{12690}Ale!
{12690}{12710}Mikoto!
{12710}{12783}Co?! My jsme ti sledovaní!
{12783}{12840}Zùstat tady ti nepomùe.
{12840}{12879}Tak pracuj, pracuj.
{12879}{12903}Jak jsem si myslel.
{12925}{12961}Tenkrát nás nìkdo sledoval.
{13004}{13025}Co se stalo?
{13025}{13149}Právì pøed chvílí Kouno cítil, e ho nìkdo pozoruje zvenèí školy.
{13182}{13226}Dnes pøestaòte pracovat.
{13228}{13278}Jdìte zpátky na ubytovnu a poèkejte na pøíkazy.
{13284}{13352}Sakamoto-sama, mohl bys s nimi jít prosím na ubytovnu?
{13352}{13388}A-Ano.
{13411}{13477}Nejdøív musíme zkontaktovat èleny Nauky o vedení domácnosti.
{13477}{13493}Rozumím.
{13493}{13547}Potom prohledáme vnitøek školy.
{13547}{13559}Ano!
{13922}{13996}Hej, co si myslíš o tom, co se dneska stalo?
{14057}{14137}Moná to byl jen dárek od nìkoho.
{14137}{14155}To je nemoné.
{14189}{14228}Èím jsi si tak jistı?
{14228}{14295}Princezny jsou idoly lidí, ne?
{14296}{14335}Je normální dostávat dárky.
{14335}{14421}Dávat princeznám dárky osobnì je dovoleno.
{14435}{14448}Proè?
{14448}{14574}Kdyby nebylo, tento pokoj by teï u byl zahrabanı v dárcích.
{14574}{14694}Ahh, jo. To je pravda. Ale jestli je to ten pøípad...
{14718}{14789}Jak jsme podezøívali, je to ten èlovìk, kterého jsi vidìl bìhem dne.
{14817}{14889}Jen jsem cítil, e tam nìkdo byl...
{15017}{15040}Oh, mimochodem, kde je Mikoto?
{15076}{15144}Pøeklad + korekce: WelW(etkaAa)-hime
{15190}{15292}Èasování: WelW(etkaAa)-hime
{15421}{15469}Jo. To je pravda.
{15485}{15554}Ano, trochu se tu zdrím.
{15608}{15674}Jo, budu zpátky hned, jak to skonèí.
{15711}{15807}Já vím. No, dobrou noc, Megumi-san.
{16006}{16045}Voláš své pøítelkyni?!
{16074}{16135}Jistì jí neøekl o práci princezen.
{16135}{16182}Jak bych jí mohl øíct o takové vìci?!
{16182}{16271}Proè ne? Není hezké to pøed svou pøítelkyni skrıvat.
{16296}{16439}Jo, to je pravda! kdy nemùeš øíct svojí |pøítelkyni pravdu, je to neupøímnı vztah.
{16439}{16536}Take, je to vztah, kterı nemùe |pøeít bez spolehnutí na neupøímnost...
{16536}{16564}Jo! Jo!
{16564}{16590}Zmlknìte! Pøestaòte!
{16607}{16660}Vy ani pøítelkyni nemáte! Jak byste to mohli vìdìt?!
{16721}{16759}Je tedy v poøádku to øíct?
{16804}{16884}Je v poøádku, kdy o všem øeknu tvé pøítelkyni, e?
{16945}{17003}Promiò! Spletl jsem se!
{17034}{17068}Je dobøe, e tomu rozumíš.
{17068}{17150}No, bìhem letních prázdnin ještì zbıvá dost èasu.
{17150}{17235}Jestli chceš opravdu vidìt svou pøítelkyni, |je v poøádku, kdy ji zajdeš navštívit.
{17249}{17302}Tooru, proè ho tak moc nièíš?
{17302}{17332}Nemùu jet.
{17365}{17543}Jestli je tu opravdu stalker, mohlo by to lidi kolem mì|pøivést do nebezpeèí... lidi, kteøí jsou pro mì nejdùleitìjší.
{17543}{17579}Mikoto...
{17579}{17664}Kdyby se nìco stalo Megumi-san, já...
{17701}{17796}Opravdu máš svoji pøítelkyni rád, e?
{17812}{17894}Co máte za problém, kluci?!| Opravdu nemáte pøítelkyni?!
{17918}{18015}Stále hledám! Promiò, nemám.
{18015}{18090}Ahhh... jo, já taky ádnou nemám.
{18090}{18188}Vánì? Pro vás by mìlo bıt snadné sbalit holku.
{18188}{18260}Ah, teï zapomeòme na balení.
{18559}{18592}Princezny!
{18607}{18636}Slyšeli jsme to!
{18636}{18729}Nebojte se! Budeme dìlat, co je v našich |silách, abychom princezny ochránili!
{18729}{18825}Uh... to se všichni vrátili jen kvùli tomu?
{18825}{18852}Zdá se, e ano...
{18852}{18900}Správnì, všichni! Hlídejme toto místo!
{18934}{18964}Tady se taky nìco stalo.
{19005}{19061}Tohle bylo ráno pøede dveømi.
{19284}{19364}U jsem kontaktovali Arisadu, a budu víc ostraitı.
{19364}{19390}Nebojte se, princezny!
{19412}{19467}Nenecháme toho chlapa vztáhnout na princezny ani prst!
{19467}{19525}I  kdybychom museli poloit naše ivoty,|ochráníme princezny!
{19570}{19627}Take, jako náhrada...
{19666}{19749}Abychom ochránili svátost našich srdcí, prosím|vìnujte nám vaše milosrdenství!
{19749}{19773}Milosrdenství?!
{19773}{19840}Princezny, prosím!
{19861}{19902}Mluví o tom...
{19902}{19968}Co? Oh, to!
{19968}{20003}Mikoto, je to v poøádku, e?
{20003}{20022}Jo.
{20057}{20115}Dìkujeme všem!
{20167}{20214}Bıt naivu je tak skvìlé!
{20214}{20248}Dìkujeme vám, princezny!
{20362}{20414}/Místnost Školní Rady/|Take, ádná další vodítka?
{20414}{20530}Ne. Uvnitø není ádná stopa po neznámém èlovìku.
{20545}{20643}Zeptali jsme se kvìtináøe na kvìtiny, které byly v lonici.
{20643}{20712}Byly objednány mladım muem.
{20712}{20773}Mladım muem?! A co jeho jméno?
{20773}{20833}Bohuel, to ještì nevíme.
{20833}{20909}Take v podstatì stále nic nevíme.
{20909}{20972}No, aèkoli to nezpùsobilo ádné zranìní,
{20972}{21054}stále neznáme zámìr posílání kvìtin princeznám.
{21054}{21155}Jestli je to jednoduše dárek, pak je to jen porušení pravidel.
{21155}{21238}S jedním jsem se pøedtím setkal... s klukem, co porušil pravidla.
{21283}{21411}Byl z bohaté rodiny. Den po dni |jsem byl bombardován dárky.
{21411}{21543}I kdy jsem je odmítal, cítil jsem se za to trapnì, |ale on nemohl pøijmout za odpovìï "ne".
{21573}{21596}Oh, to je...
{21596}{21646}T-Take, co jste udìlal?
{21677}{21771}Samozøejmì... pøísnì jsem si s ním promluvil.
{21849}{21896}Jakı hloupı kluk!
{21896}{21936}Absolutnì nerozumné.
{21936}{22056}Ne, ne, mìli bychom øíct, e je to kluk, kterı se nepouèil.
{22056}{22142}O èem to mluvili?
{22142}{22212}Chci to vìdìt, ale nejsem si jistı, |jestli to chci opravdu vìdìt...
{22241}{22315}Tak, máme další vodítka?
{22315}{22406}Vùbec ne. Ale, známe zpùsob, jak ho chytit.
{22431}{22517}Jestli se neukáe, tak pouijeme|návnadu, abychom ho pøilákali.
{22537}{22589}Take, my budeme návnada?!
{22589}{22659}Samozøejmì. Ale byl by problém, |kdyby se vám nìco stalo,
{22659}{22692}take s sebou budete mít bodyguardy.
{22707}{22722}Ale...
{22722}{22745}Rozumím.
{22773}{22794}Chci to udìlat.
{22794}{22825}Myslíš to vánì, Mikoto?!
{22840}{22891}Nechci, aby to takhle pokraèovalo.
{22965}{23043}Rozumím. Prezidente, taky to udìlám.
{23043}{23062}Kouno!
{23062}{23085}Já taky.
{23085}{23120}Shihoudani, ty taky...
{23120}{23203}Øekl jsem ti to pøedtím; jsme na stejné lodi, správnì?
{23203}{23240}Shihoudani...
{23240}{23318}Tak je to. Prosím, postarej se o nás, Mikoto.
{23335}{23351}Kouno!
{23713}{23799}Nevíme, kdy se ten chlap ukáe. Buïte opatrní!
{23799}{23814}Jo.
{23869}{23917}Princezny! Nepolevujte se svou prací, prosím!
{23917}{23971}Vıbornì! Je skvìlé, e jsem tady v nápravné tøídì!
{23971}{24041}Jo! Je úasné vidìt princezny v létì!
{24041}{24115}P-Prosím, dejte do uèení všechno.
{24115}{24149}Ano!!
{24169}{24197}Co se dìje?
{24197}{24230}Promiòte, promiòte.
{24230}{24302}Ale nemùeme kontrolovat chování bìnıch studentù.
{24302}{24347}No tak...
{24367}{24397}Pøíštì budeme opatrnìjší.
{24867}{24895}Poøád se neukázal.
{24895}{24978}Je tu opravdu ten podezøelı?
{24978}{25013}Ty jsi to všechno vidìl, ne?
{25013}{25056}To je pravda, ale...
{25129}{25151}Ten chlap!
{25151}{25184}Koneènì jsme se potkali!
{25210}{25226}Chyte ho!
{25298}{25315}Jste všichni v poøádku?
{25361}{25389}Hej, mìl by se's chovat líp!
{25389}{25428}Vy... Chcete bıt idoly?!
{25428}{25442}Hej!|Vy... Chcete bıt idoly?!
{25442}{25490}Vy... Chcete bıt idoly?!
{25574}{25620}Huh? Idolové?
{25645}{25690}Tady. Je mi potìšením vás poznat.
{25706}{25743}Zábavnı poøad?
{25771}{25904}Ano. Šel jsem náhodou do herny a| spatøil tyto tøi krásné dívky.
{25904}{26034}Chtìl jsem, aby šly do naší spoleènosti a mìly debut.|Take jsem je pøišel prozkoumat.
{26303}{26359}Ale stejnì jsem nemohl nic najít.
{26359}{26414}Jste tu, abyste škole fandily, e?
{26440}{26502}Myslel jsem si, e tu bude víc spojení, tak jsem pøišel.
{26502}{26538}Ne, samozøejmì, e tu bylo!
{26569}{26634}Ah! byla udìlána i taková fotka?!
{26663}{26771}To je v poøádku. Nikdo tì v paruce nepozná.
{26771}{26801}Oh, opravdu?
{26801}{26839}Vìø mi!
{26870}{26966}Rád bych kdybyste nám dal |vysvìtlení také ohlednì tìch kvìtin.
{26966}{27033}Kvìtiny?! O tom nic nevím.
{27089}{27178}Jen jsem na vás èekal venku pøed školou.
{27178}{27209}Neudìlal jsem nic jiného.
{27234}{27289}P-Pak, kdo ty kvìtiny poslal?
{27628}{27705}Tady jste, princezny!
{27705}{27728}Tady máte!
{27728}{27748}To je...
{27748}{27786}Tady... tady!
{27854}{27930}N-Natashou-senpai, co je to...
{27930}{27971}Je to tady! Je to tady! Je to tady!
{27971}{28013}Jistì není moné spoléhat se èistì na pøedstavivost!
{28013}{28119}Vidìt skuteèné princezny s kvìtinami mi poprvé dává inspiraci!
{28119}{28233}Natashou-senpai, znamená to, e tyhle kvìtiny| mají nìco spoleèného s novım obleèením?
{28233}{28253}Samozøejmì!
{28253}{28334}Tentokrát to bude obleèení podle obrazu rùí!
{28334}{28422}Nicménì, chtìl jsem vidìt vizuální efekty |vytvoøené kombinací obleèení a rùí,
{28422}{28457}ale stále to nefungovalo.
{28612}{28706}Take jsem poslal kvìtiny do ubytovny, ale nedostali jste je.
{28706}{28768}Musel jsem jít koupit další.
{28768}{28807}Podívej co jsi udìlal, zpùsobit takovı skandál.
{28807}{28833}Opravdu!
{28833}{28933}Správnì! Teï máme obraz, mùu hned zaèít navrhovat!
{28933}{29013}Ale je dobøe, e známe pravdu, ne?
{29013}{29051}To je pravda.
{29051}{29110}Princezny, dìkuji za vaši tvrdou práci.
{29110}{29163}Postaráme se o zbytek.
{29163}{29202}To je skvìlé, Mikoto!
{29233}{29307}Takhle mùeš mít se svojí pøítelkyní rande bez obtíí, správnì?
{29307}{29335}Jo! Díky!
{29335}{29439}Um... omlouvte mì, ale co znamená|"mít rande se svou pøítelkyní?"
{29439}{29460}Ah, my...
{29460}{29519}Pojïme, proberme detaily támhle.
{29541}{29600}Stále je spousta vìcí, na které bych se vás rád zeptal.
{29639}{29662}Tudy, prosím.
{29662}{29782}J-Jen minutku! Hej! Vy... Opravdu se stanete idoly!
{29782}{29858}Hej! Promyslete si to! Hej!
{30237}{30280}Má ve tváøi šastnı vıraz.
{30280}{30351}Hej, dostali jsme se blí, tak mùeme| vidìt, jak jeho pøítelkynì vypadá.
{30351}{30369}Jo.
{30369}{30402}Dámy!
{30412}{30448}Hej, máte teï èas?
{30448}{30505}Co tady dìláte?
{30505}{30587}Pojïme spolu na karaoke, karaoke.
{30587}{30618}Znovu ne.
{30618}{30658}Byli jsme prokleti?
{30691}{30709}Jsou pryè!
{30709}{30741}Hej, dámy!
{30741}{30794}Povìzte, chcete jít vyzkoušet ten obchod?
{30794}{30844}Co to dìláte, lidi?!
{30844}{30901}Teï jsme je ztratili.
{30901}{30942}Radìji byste mìli pøevzít zodpovìdnost!
{33471}{33549}Pøíštì: Sakamotovo rodinné tajemství
