{1}{1}23.976
{54}{147}Na téhle hloupé chlapecké škole plné klukù,
{147}{222}dávají studentùm utìšující úsmìvy
{222}{262}a èas od èasu jemné povzbuzení
{262}{322}skuteèní idolové, kteøí velkımi událostmi rozehøívají atmosféru.
{322}{382}Toto je existence takzvanıch princezen.
{382}{414}Já nechci!
{414}{465}Vıbornì. Práce. Práce.
{496}{566}TaSHee's Gang uvádí
{2416}{2624}PRINCESS PRINCESS
{2893}{3012}Sakamotovo rodinné tajemství
{3291}{3314}Úasní!
{3314}{3343}Kdopak to je?
{3343}{3366}Nádherní!
{3366}{3402}Natáèejí?
{3402}{3443}Copak je, Aki-chan?
{3443}{3495}N-Nic. Jsem v poøádku.
{3495}{3593}Tak, Aki-chan, pospìš si a rozhodni se,|co z menu chceš. Mám hlad.
{3593}{3639}Uh... promiò, objednám si.
{3710}{3732}Aki-chan.
{3732}{3757}Podívej, podívej...|Aki-chan.
{3757}{3789}Promiò, objednám si.
{3789}{3809}Opravdu... jen on; taková škoda...|Promiò, objednám si.
{3809}{3845}Opravdu... jen on; taková škoda...
{3959}{4045}Hej, Akiro! Akiro, kam jdeš? Akiro!
{4194}{4212}Sakamoto-sama!
{4225}{4281}Dobré ráno, Sakamoto-sama!
{4281}{4334}D-Dìkuji vám. Dobré ráno.
{4334}{4415}Dìláte nìjakou práci pro Studentskou Radu, Sakamoto-sama?
{4415}{4486}Ano. Všichni ve svıch klubech také tvrdì pracují, e?
{4486}{4583}Ne! Ve srovnání s tím, co dìláte vy,|Sakamoto-sama, to nic není.
{4583}{4628}Pracujte prosím dobøe, Sakamoto-sama!
{4628}{4675}Dì-Dìkuji vám mnohokrát!
{5256}{5303}Uch! Koneènì je konec.
{5303}{5386}Co znamená, e všechno to povzbuzování|bìhem letních prázdnin skonèilo.
{5386}{5461}Jo! Mimochodem, kde je Mikoto?
{5461}{5610}Kouno! Shihoudani! Dobrá, zbytek nechám na vás!
{5663}{5707}Zase má ve tváøi ten šastnı vıraz...
{5707}{5777}Ani to neohlásil Prezidentovi Arisadovi, ten kluk...
{5777}{5807}Hej.
{5807}{5832}Yo.
{5832}{5887}Yo, Sakamoto!
{5887}{5943}Co se Yutakovi-kun stalo? Pospíchá?
{5943}{5992}Jde za svou pøítelkyní.
{5992}{6046}Všechna práce bìhem léta skonèila.
{6046}{6097}Sakamoto-sama, poøád dìláš poslíèka Studentské Rady?
{6118}{6193}Jo. Do druhého pololetí je poøád dost pøíprav.
{6193}{6245}Sakamoto taky tvrdì pracuje.
{6245}{6294}Ne, není to velkı problém.
{6294}{6336}Princezny, dìkuji za vaši tvrdou práci.
{6359}{6458}Slyšel jsem, e pìt sportovních |klubù se dostalo do prefekturních zápasù,
{6458}{6505} a dva do finále.
{6505}{6559}Skvìlı vısledek!
{6559}{6661}Ale bohuel, zdá se, e nebudeme na národních hrách.
{6661}{6701}To... no...
{6701}{6732}Jistì...
{6732}{6745}Jo...
{6745}{6757}Jo...
{6757}{6797}Co mùeme dìlat...
{6797}{6843}S Prezidentem se nemùeme srovnávat.
{6890}{6925}Tak to není!
{6960}{6997}A taaak...
{6997}{7079}Pracujete tvrdì, princezny. Dìkuji vám!
{7079}{7133}Aèkoli zbıvá u jen pár dní letních prázdnin,
{7133}{7215}mùete odpoèívat a uívat si, ne zaène škola.
{7215}{7248}Jsem zachránìni!
{7248}{7328}V tomhle obleèení je horko; koneènì budeme volní.
{7328}{7382}Tak já, Prezidente, dnes...
{7382}{7408}Sakamoto-sama!
{7408}{7435}Ano!
{7435}{7573}Sakamoto-sama, dál si musíte poslechnout detaily|o zrušenıch aktivitách na další pololetí.
{7573}{7609}A-Ano.
{7609}{7632}Je to v poøádku, e?
{7632}{7733}Sakamoto-sama, jsi mladším bratrem |bıvalého Sakamota-sama, ne?
{7733}{7840}Nikdo nemùe uspìt v mé práci a |kontrolovat budoucnost školy, kromì tebe.
{7840}{7922}To... ale já jsem jen obyèejnı student...
{7922}{7951}Sakamoto-sama!
{7951}{7986}Ano!
{8003}{8089}Mladší bratr té osoby nemùe bıt jen obyèejnı student.
{8089}{8186}Jako princezna se ani já nemùu|srovnávat s bıvalım Sakamotem-sama;
{8186}{8271}jako by byl jednoduše nad mraky.
{8271}{8310}O èem to mluvíš, Arisado?!
{8310}{8404}Sakamoto-sama byl jistì skvìlı šlovìk, ale ty...
{8404}{8470}To je pravda! Jak mùeš øíct, e|se nemùeš se Sakamotem-sama srovnávat?
{8470}{8529}Ne, ne. ádné srovnání...
{8529}{8557}To není pravda!
{8557}{8580}Buï sebejistìjší!
{8580}{8605}Arisado!
{8619}{8725}No, v kadém pøípadì ti dìkuji, Sakamoto-sama!
{8725}{8756}A-Ano.
{8828}{8867}On je opravdu úasnı èlovìk, e?
{9196}{9252}Tooru, rozumíš tomu?
{9252}{9289}Eh? Èemu?
{9307}{9421}Ne, to nechápu.
{9421}{9475}Ale myslím, e by to mìl vìdìt Sakamoto.
{9475}{9577}Ah, to je pravda! Sakamoto nás poádal,|a k nìmu zajdeme, ne?
{9577}{9618}Tak pojïme a poøádáme ho, aby nás uèil.
{9646}{9716}V tom pøípadì, oznaèím otázky, které vypadají|tìce a mùeme se ho na nì zeptat.
{9716}{9786}Hej, moná potkáme toho Sakamota-sama.
{9810}{9879}To je pravda! Bıvalı Sakamoto-sama|by tam nìl bıt taky, huh.
{9879}{9951}Jo, øíkal, e celá rodina ije spoleènì.
{9951}{9997}Tak u nich pár dní zùstaòme.
{9997}{10066}Takhle je šance potkat ho pìknì vysoká.
{10066}{10168}Jo. Máme tolik volného èasu, e nevíme co dìlat...
{10168}{10238}Správnì, zavolám mu.
{10238}{10275}Nechám to na tobì!
{10417}{10464}Je to severní vıchod, e?
{10464}{10541}Jo, tohle je jedinı severní vıchod.
{10541}{10628}Hej, vy dva! Tady!
{10628}{10684}Promiò, e jsi nás musel pøijít vyzvednout.
{10684}{10765}ádnı problém, to je v pohodì. |Je to sem jen deset minut.
{10765}{10796}Nejdøív otázka!
{10796}{10857}Je dneska doma legendární Sakamoto-sama?
{10857}{10881}Nebo není doma?
{10881}{10938}N-No... Nejsem si jistı.
{10938}{10988}Kdy jsem odcházel, tak se nezdálo, e by byl doma.
{10988}{11053}Hej, co budemì dìlat? Zùstaneme|na tøi dny a dvì noci?
{11053}{11074}Um...|Ne, jestli nezùstaneme dıl, nepùjde to.
{11074}{11122}Ne, jestli nezùstaneme dıl, nepùjde to.
{11122}{11171}Eh? Ale nevzal jsem si dost obleèení.
{11171}{11258}Jedna vìc... Doufám, e nebudete moc |pøekvapeni, a pùjdeme ke mnì domù.
{11258}{11290}Pøekvapeni?
{11290}{11307}Proè?
{11307}{11386}Ah... t-to... kvùli mému staršímu bratrovi.
{11386}{11436}Co? Myslíš...
{11436}{11544}Neboj. Jako princezny u jsme zvyklí na hodnì vìcí.
{11544}{11591}P-Pak to nebude problém.
{11749}{11765}Tady je to.
{11765}{11792}Obrovské.
{11792}{11853}Samostatnı dùm. Vypadá skvostnì.
{11853}{11915}Sakamoto, jsi bohaté dítì?
{11915}{11937}Take je bohaté dítì...
{11937}{11966}Nejsem!|Take je bohaté dítì...
{11966}{12007}Mùj otec dìlá ve stavebnictví.|Take je bohaté dítì...
{12007}{12036}Take proto...
{12036}{12122}V kadém pøípadì, pojïte dál a| dáme si nìco studeného k pití;
{12122}{12146}protoe je tady tak teplo.
{12146}{12213}Jo. Souhlasím, souhlasím.
{12233}{12252}Jsem zpátky!
{12252}{12308}Omlouváme se za vyrušení!
{12388}{12431}Aki-chan, pøišli tvoji pøátelé?
{12431}{12477}Jo, to je Kouno a Shihoudani.
{12477}{12519}Dobré odpoledne! Vítejte!
{12519}{12570}Ahh... A-Ano! Dobré odpoledne!
{12605}{12676}Zajdu pro nìco studeného k pití, ok?
{12676}{12771}Aki-chan, vezmi je do svého pokoje.
{12771}{12803}Mmm, dìkujeme.
{12828}{12914}Vidìl jsi... ty pohybujíví se kvìtiny za ní?
{12914}{13000}Ah, taky jsem je vidìl... laskavı styl mladé dívky.
{13000}{13071}Vy dva, mùj pokoj je v druhém patøe. |Pojïte se mnou, ok?
{13071}{13102}Sakamoto!
{13102}{13186}To je opravdu roztomilá dívka. |Je to tvá starší sestra?
{13186}{13204}Ne, ne. Vypadá na mladší sestru.
{13204}{13242}Jak jsem èekal...|Ne, ne. Vypadá na mladší sestru.
{13242}{13262}Ne, ne. Vypadá na mladší sestru.
{13262}{13336}Není! Mladší sestra by nebyla tak slušná!
{13336}{13366}Urèitì je to starší sestra!
{13366}{13471}Ne! Je roztomilá jako kuøátko,|take je to mladší sestra.
{13471}{13491}Starší sestra!
{13491}{13503}Mladší sestra!
{13503}{13539}Je to starší sestra!
{13539}{13563}Øíkám ti, e mladší!
{13563}{13600}Tak si poslechnìme odpovìï!
{13600}{13614}Jo!
{13614}{13650}Take kdo má pravdu?!
{13650}{13750}Ne, ta osoba je... moje...
{13750}{13858}Pøeklad + korekce: WelW(etkaAa)-hime
{13872}{13970}Èasování: WelW(etkaAa)-hime
{14020}{14057}Matka!
{14088}{14152}Take nejste starší sestra?
{14152}{14179}Ani mladší sestra?
{14179}{14300}Oh ne! Jací pochlebníci, jako dospìlí!
{14300}{14351}Bavte se!|Jste v poøádku?!
{14351}{14403}Kouno, Shihoudani?
{14403}{14435}Sakamoto...
{14435}{14454}Co?
{14454}{14526}Nevím jestli bych se na to mìl zeptat...
{14526}{14586}Ale... mohla by bıt ta osoba tvoje nevlastní matka?
{14611}{14633}Je to moje opravdová matka.
{14666}{14722}K-K-Kolik jí je let?
{14722}{14758}Ètyøicet tøi.
{14834}{14905}Um... Vlastnì, tohle není to skuteèné pøekvapení.
{14925}{14971}Aki-chan, máš chvilku?
{14996}{15014}Aki-chan?
{15056}{15083}Ah, Fuyuki. Teï...
{15083}{15169}Promiò, máš hosty. Pøijdu pozdìji.
{15169}{15226}Ne, ne. Nedìlej si s námi starosti.
{15226}{15263}Jestli nìco potøebuješ, do toho prosím.
{15263}{15311}Opravdu? Tak tedy dobrá.
{15417}{15487}Tady je vztané zájmeno...
{15487}{15558}Ah, tady mùe pouít "which" nebo|"whom". Které z toho preferuješ...
{15558}{15608}Jak krásnı...
{15608}{15658}Jo, to musí bıt mladší bratr.
{15658}{15766}Ne, ne. Poté, co jsme vidìli jeho matku,|u nemùeme bıt oklamání vzhledem.
{15766}{15805}Take je to starší bratr, nebo otec?
{15805}{15862}Ale kdyby to byl ten pøípad, nemohl|by mu pomáhat v uèení.
{15862}{15951}Jo, to je pravda. Zdá se, e je mladší, ne Sakamoto.
{15951}{16022}Dobrá, omluvte mì. Promiòte, e jsem obtìoval.
{16022}{16048}Ahh... to ni, to nic!
{16048}{16074}ádnı problém.
{16107}{16151}Take, to je tvùj mladší bratr?!
{16151}{16189}Nebo starší bratr nebo otec?!
{16189}{16225}Moje mladší sestra...
{16225}{16250}Mladší sestra?!
{16250}{16335}Lháøi! Vypadá úplnì jinak, ne tvá matka!
{16335}{16425}To proto jsem vám na zaèátku øíkal,|e budete pøekvapeni.
{16425}{16549}I kdy jsi to øekl, proè by tvoje jemná,|krásná matka mìla rozpustilou dceru?
{16670}{16708}Co-Co je, vy dva?
{16741}{16815}Tvá matka je taková, tvá mladší sestra je taková...
{16840}{16918}Pak legendární Sakamoto-sama...
{16918}{17003}Co-Co se vy dva snaíte øíct?
{17003}{17094}Jen... øíkal jsi, e pøekvapení teprve zaèalo, e?
{17094}{17130}J-Jo.
{17130}{17210}Pa-Pak, mohlo by toho bıt... víc?
{17269}{17297}M-Mohlo by...?!
{17321}{17401}Mohl by bıt tvùj otec a starší bratr.... |Mohli by bıt taky takoví?!
{17471}{17548}N-Ne, mùj otec je normální!
{17548}{17594}Mùj otec je normální!!
{17594}{17646}Mùj otec by mìl bıt normální!
{17701}{17783}Myslím si, e je normální... pravdìpodobnì.
{17783}{17817}Myslíš?
{17817}{17867}Pravdìpodobnì? To znamená...
{17895}{17923}Zase?!
{17923}{17970}Kdo je to tentokrát?!
{18000}{18094}Akiro, právì jsem dostala nìco dobrého.|Chceš si taky dát?
{18130}{18190}Ta osoba je nádherná!|Máš hosty. Tvoji kamarádi?
{18190}{18240}Kluk? Nebo holka? Kdo?|Máš hosty. Tvoji kamarádi?
{18240}{18271}Kluk? Nebo holka? Kdo?|Jo, Kouno a Shihoudani.
{18287}{18307}Tìší mì!
{18307}{18374}Vteøinku! Stále o tom pøemıšlíme!
{18374}{18443}Hej, nezapomeò na informace, které jsme získali.
{18443}{18505}Rozumím. Nejdøív bychom se nemìli|nechat oklamat vzhledem.
{18505}{18552}Musí to bıt ten... ten, koho oèekáváme.
{18552}{18581}Co se dìje?|Musí to bıt ten... ten, koho oèekáváme.
{18581}{18605}To nic.|Musí to bıt ten... ten, koho oèekáváme.
{18605}{18674}Ne, ne. Jak øekl Sakamoto, mohlo by bıt víc...
{18723}{18784}Správnì! Mùj odhad je, e je to |legendární Sakamoto-sama!
{18784}{18832}Mùj odhad je, e je to babièka z matèiny strany!
{18832}{18920}Bohuel, jsem Akirova starší sestra.
{18964}{19030}Vy dva jste opravdu roztomilí, ale trochu divní, huh?
{19030}{19072}Dejte si to prosím k èaji.
{19072}{19098}Ok, bavte se!
{19168}{19185}Sakamoto...
{19185}{19212}C-Co?
{19212}{19289}Právì jsi øekl, e jsou všichni divní, e?
{19289}{19348}N-Nezeptali jste se mì na mou starší sestru.
{19348}{19369}Sakamoto!
{19369}{19392}Ano!
{19392}{19458}Teï bys nám to mìl øíct jasnìji.
{19458}{19494}C-Co?
{19494}{19563}Kolik lidí máš v rodinì?
{19563}{19599}Š-Šest lidí.
{19637}{19707}To znamená, e zbıvá u jen otec a starší bratr!
{19707}{19754}Setkání s další osobou rozhodne mezi vítìzstvím a porákou.
{19754}{19814}Eh? Proè to rozhodne mezi vítìzstvím a porákou?!
{19840}{19860}Pøichází!
{19860}{19898}Dobré naèasování!
{19922}{19997}Ahoj! Slyšel jsem, e tu máš kamarády.
{20020}{20068}Uh.. jo, to je pravda.
{20221}{20261}D-Další oslnivá osoba!
{20261}{20323}Je to otec nebo starší bratr?
{20323}{20377}Ne, je pøíliš mladı na to, aby to byl otec.
{20377}{20472}Jestli je to otec, mohl by bıt nesmrtelnı jako matka?
{20472}{20561}Tahle rodina, jsou to opravdu lidé jako my?
{20640}{20684}Tìší mì. Jsem Akirùv...
{20684}{20708}Poèkejte!!
{20768}{20863}I kdy vypadá skvìle, nevidím pùvab, |kterım by mohl øídit celou školu.
{20863}{20996}Moná jsou všichni pøitaliví díky|jejich okouzlující laskavosti.
{21015}{21100}To je pravda. Jak mùou bıt všichni v téhle rodinì tak krásní?
{21100}{21159}Mohlo by to bıt tím, e nejsou lidé?
{21159}{21201}Vìdìl jsem to! Musí to tak bıt, jsem si jistı!
{21201}{21254}C-Co se dìje, vy dva?
{21254}{21296}O èem to mluvíte?
{21296}{21352}Hej, vy dva!
{21352}{21398}Je to v poøádku, e?
{21398}{21453}Tìší mì. Jsem Akirùv otec.
{21648}{21758}Ahh! Lidé èasto øíkají, e je naše rodina trochu divná.
{21788}{21845}Otec by mìl bıt normální, ale protoe...
{21845}{21870}Hide-kun!
{21890}{21977}Není to trochu... mìla by bıt hodnì divná.
{21977}{22064}Ah, Hide-kun, zajímalo mì, kde jsi.
{22064}{22145}Jak bys mì mohl nechat vaøit samotnou?
{22145}{22214}Promiò, promiò. Na oplátku...
{22214}{22279}Boe! Hide-kun, ty jsi...
{22279}{22299}Je lepší polibek na tváø?
{22299}{22343}Jak na to máme reagovat?|Je lepší polibek na tváø?
{22343}{22385}Opravdu je jim pøes ètyøicet?|Hide-kun, blbèe! Blbèe! Blbèe!
{22385}{22423}Opravdu je jim pøes ètyøicet?
{22423}{22486}Sakamoto, to se na nì vdycky takhle díváš?
{22486}{22511}Jo.
{22511}{22553}To musí bıt tìké, kadı den...
{22575}{22604}Je trochu pozdì.
{22604}{22640}To není pravda!
{22773}{22794}Hide-kun, pálí se to!
{22794}{22831}Honem, mám hlad!|Hide-kun, pálí se to!
{22831}{22850}Honem, mám hlad!|Oh, ne! Nedával jsem pozor.
{22850}{22884}Nebuï pøed hosty takovı.|Oh, ne! Nedával jsem pozor.
{22884}{22900}Nebuï pøed hosty takovı.
{22900}{22913}Ale...
{22913}{23046}Dneska jsem byl tak vzrušenı, protoe jsem si myslel,|e bych mohl potkat toho legendárního Sakamota-sama,
{23046}{23114}ale samotná tvoje rodina byla vzrušující.
{23142}{23198}Jo, potí se mi ruce.
{23228}{23334}Ale pro tebe to nemùe bıt jednoduché, |bıt obklopenı takovou rodinou.
{23334}{23431}Ah, to je pravda; pravdìpodobnì jsi to tak|nikdy necítil, protoe je to tvoje rodina.
{23431}{23477}Ne, tak to není.
{23526}{23556}Tak to není.
{23556}{23656}Stejnì, nemyslím si, e je moje rodina divná;
{23656}{23724}jen cítím, e jsem jinı, ne oni.
{23893}{24033}Podívejte, ve srovnání se svou rodinou vypadám|normálnì. Nevypadám jako oni.
{24033}{24062}Ne, to není pravda.
{24062}{24172}Nemusíte bıt tak zdvoøilí. U mi to øekla spousta lidí,
{24172}{24207}Pospìšte, trvá to moc dlouho.
{24207}{24273}take jsem mìl depresi a nìkdy mi to vadilo.|Pospìšte, trvá to moc dlouho.
{24273}{24338}take jsem mìl depresi a nìkdy mi to vadilo.
{24338}{24383}Teï jsem si na to zvykl,
{24383}{24465}a taky si uvìdomil, e jsem to byl |vlastnì já, kdo myslel divnì.
{24465}{24531}Nikdo z mé rodiny mì nikdy neodmítl.
{24568}{24636}Musím se spoléhat sám na sebe.
{24636}{24810}Takhle budu vìdìt, kde jsem a nebudu|nièit vìci, které jsou pro mì nejdùleitìjší.
{24849}{24906}Porozumìní mi hodnì pomohlo.
{24992}{25092}Chápu to! Sakamoto-sama musel z tìch|zkušeností získat skvìlé porozumìní
{25092}{25158}a stal se tak tolerantním, e mùe vykonat cokoli!
{25158}{25191}Ah, to je pravda!
{25191}{25229}S-Skvìlé porozumìní je pøíliš moc...
{25229}{25349}Mimo to, chtìl jsem vyuít pøíleitosti a øíct vám to...
{25349}{25413}Prosím, pøestaòte mi od teï øíkat Sakamoto-sama.
{25447}{25567}Kdy pøidáváte "-sama", cítím jako|by mezi námi byla neviditelná zeï,
{25567}{25639}jako bych se všemi mluvil skrz sklo.
{25639}{25737}To, e jste dneska pøišli, mi opravdu udìlalo radost.
{25760}{25847}Pøinejmenším jsem se chtìl potloukat se svımi|dobrımi pøáteli, jako to dìlají normální lidi.
{25871}{25897}Sakamoto...
{25918}{25976}Za dnešek jsem opravdu vdìènı.
{26049}{26115}Nemá to nic spoleèného s tvım starším bratrem.
{26115}{26241}Chceme se pøátelit se Sakamotem, Sakamotem Akirou.
{26267}{26298}To je pravda.
{26340}{26391}Kouno, Shihoudani...
{26391}{26501}Take ti budu øíkat Sakamoto jako Tooru.
{26501}{26602}Poèkej. Jestli je to ten pøípad, tak mu øíkejme køestním jménem.
{26623}{26666}Navzájem si øíkáme køestními jmény, ne?
{26686}{26726}Nebo je lepší øíkat ti Sakamoto?
{26726}{26794}Eh? Ne, vùbec ne.
{26794}{26808}Skvìle!
{26808}{26904}Take Tooru a já ti budeme øíkat Akiro.
{26904}{26993}Take Sakamoto nám bude taky øíkat køestními jmény.
{26993}{27050}Jo, chápu.
{27050}{27098}Tak si to vyzkoušejme.
{27098}{27137}Jsem Tooru.
{27137}{27176}Já jsem Yuujirou.
{27176}{27213}Ok, zkus to.
{27213}{27259}Tooru, Yuujirou.
{27361}{27404}J-Je mi u toho trapnì.
{27404}{27448}Nemusí ti bıt tak trapnì...
{27448}{27494}Poprvé je to vdycky takhle.
{27494}{27534}A si na to zvykneš, bude to v poøádku.
{27534}{27570}V kadém pøípadì, pøíštì...
{27570}{27599}Akiro!
{27970}{28006}Mohla by ta osoba bıt...
{28023}{28078}legendární Sakamoto-sama?
{28180}{28208}Akiro!
{28357}{28393}Jsi tak krutı, Akiro!
{28393}{28477}Proè jsi mi neøekl, e máme dneska barbecue?!
{28660}{28766}Proè jsi mi neøekl nìco tak dùleitého, Akiro?!
{28766}{28842}Poslal jsem ti zprávu na mobil, Haru-nii...
{29005}{29070}Oh, takhle to je... Aha...
{29070}{29114}Promiò, Akiro!
{29114}{29188}Akira je nakonec jedinı, kdo se o mì stará.
{29188}{29292}Haru-nii, jsou tady moji kamarádi, take...
{29345}{29377}S-Starší bratr...
{29377}{29431}Tahle osoba je legendární Sakamoto-sama?
{29431}{29473}Jdu si dát maso!|Je to jistì krásnı mu.
{29473}{29492}Haru-nii...|Je to jistì krásnı mu.
{29492}{29548}Jo, velmi pìknı.
{29548}{29614}Ale pøi jeho vìku a vzhledu se zdá neobvyklı.
{29614}{29658}A je snadné urèit jeho pohlaví.
{29658}{29713}O èem to mluvíte?
{29713}{29771}Podívej jak drel Akiru a breèel.
{29771}{29854}Necítil jsem charisma vùdce ani záhadnı pocit.
{29854}{29894}Hej, vy dva...
{29938}{30026}Poté, co jsem vidìl neobvyklé èleny téhle rodiny,
{30026}{30070}úasnì krásnı zaèátek a k vìtší normálnosti.
{30070}{30096}Ale...!|úasnì krásnı zaèátek a k vìtší normálnosti.
{30147}{30237}To je pravda! Dobré známky, vıjimeèné atletické schopnosti,
{30237}{30311}dobré zpùsoby, milován ostatními, dobré vedení...
{30344}{30375}O èem to mluvíte?
{30375}{30464}A taky je ve škole nástupcem Prezidenta Arisady...
{30482}{30551}Protoe jsou lidé okolo tebe tak vıjimeèní,|nevypadáš, e tak moc záøíš.
{30551}{30599}Ale taky nejsi normální!
{30599}{30644}Eh? Poèkejte!
{30644}{30729}Ne, ne. Akira je taky moc krásnı.
{30729}{30766}Ne, tak to není...
{30766}{30839}Nebuï tak skromnı! Všichni si to myslí.
{30839}{30894}Ale ve srovnání s Haruem-nii...
{30894}{30944}To proto, e jsi si vzal špatnou osobu ke srovnání.
{30944}{31014}Nezáleí na tom, co øíkají ostatní.|Akira je krásnı, ok?!
{31215}{31271}Huh?! Zapomnìl jsem si penìenku!
{33493}{33552}Pøíštì: Koncert sboru s potem a slzami
