{1}{1}23.976
{44}{159}Já, Kouno Tooru, jsem mìl na této slavné, soukromé,|chlapecké škole, na ní jsem pøestoupil
{159}{219}v pololetí, dveøe své budoucnosti otevøené|dokoøán, ani bych si to uvìdomil.
{219}{297}Myslel jsem si, e budu ít na této škole otupující ivot,
{297}{335}ale co tu dìlá tahle holka?
{335}{359}Já jsem kluk!
{359}{412}Eh? Ale nosíš naøasenou sukni…
{412}{468}Co to kecáš? Ty budeš mít taky takovou.
{468}{528}Všichni tøi jsme na stejné lodi.
{528}{572}Pojïme udìlat vše, co bude v našich silách.
{572}{603}Ne!
{603}{693}A takhle zaèal mùj ivot princezny.
{733}{803}TaSHee's Gang uvádí
{2655}{2865}PRINCESS PRINCESS
{3135}{3252}Existence princezen ohroena!?
{3689}{3727}Akademie Fujimori, huh...
{4211}{4313}Myslela jsem si, e by's to mohl cítit stejnì a mohl mì mít rád!
{4313}{4436}A kdybychom se vzali, stali bychom|se s tátou a mámou skuteènou rodinou!
{4436}{4532}Bylo by to pro tebe skvìlé, protoe|jsi ztratil rodièe, ne, Tooru-kun?
{4532}{4624}Take Sayaka jela domù?
{4624}{4687}Ano. Omlouvám se, Tooru.
{4687}{4753}Pøíštì ji nezpustím z oèí.
{4791}{4854}Moná to není nìco, co bych ti mìl øíkat,
{4854}{4911}ale Sayaka to myslí vánì.
{4911}{5000}Nemùu tì ádat, aby's jí kvùli tomu prominul její chování,
{5000}{5083}ale odpus jí, prosím.
{5083}{5166}Jo, rozumím strıèku.
{5328}{5406}Co se dnes s princeznou Tooruem dìje?
{5406}{5455}I jeho zachmuøenı vıraz je nádhernı.
{5455}{5519}Jo, jakı to oblièejík!
{5546}{5605}Myslíš si, e mì mùeš oklamat?
{5605}{5661}Ale je to pravda...
{5712}{5755}Nech mì... ti to dokázat.
{6301}{6344}Yuujirou je idiot!
{6344}{6396}Nemusel zacházet tak daleko.
{6500}{6522}Kam šel?
{6555}{6622}Take se stalo nìco takového,
{6622}{6680}a proto je Tooru trochu na dnì.
{6680}{6800}Sayaku to jen doèasnì odradilo; nevíme, kdy se zase ukáe.
{6800}{6866}Nevímì co dìlat.
{6866}{6953}Kouno nám øekl, abychom si s tím|nedìlali starosti, ale poøád se obáváme.
{6953}{7039}Take jsme si mysleli, e by's moná mohl mít nìjakı dobrı nápad.
{7039}{7126}Tooru je pro vás velmi dùleitı, e?
{7163}{7205}Dìláte si o nìj starosti, e?
{7205}{7249}Je v poøádku mít pøátele.
{7249}{7286}T-Tak to není!
{7286}{7395}Dìlám si starosti jen proto, e má Tooru depresi,|jinak mi to jakoto princeznu zpùsobí víc obtíí.
{7395}{7442}To co jsi øekl, je pravda.
{7442}{7542}Naše práce vdycky všem pøináší záøi a štìstí.
{7542}{7614}To znamená, e si's koneènì uvìdomil |svou povinnost jako princezny.
{7614}{7667}Nechci si nic uvìdomovat!
{7667}{7773}V kadém pøípadì je teï lepší bıt Tooruovi po boku.
{7773}{7840}Pravdìpodobnì o tom s námi stále nechce mluvit.
{7840}{7953}Bude lepší ho vyslechnout, |a bude pøipravenı nám to øíct.
{7989}{8039}To je pravda.
{8039}{8157}Jo, kdy vás má po boku, stane se silnìjším.
{8157}{8210}Proè o tom mluvíš jako kdyby to byl problém nìkoho jiného?
{8210}{8241}Ty jsi taky jeho kamarád, ne, Akiro?
{8276}{8294}Jo!
{8334}{8374}Take tady jsi byl.
{8374}{8389}Tooru!
{8408}{8460}Co tady dìláte?
{8460}{8496}To je náhoda.
{8496}{8582}Byl jsem trochu unavenı z udrování princeznovského|úsmìvu, tak jsem si sem pøišel odpoèinout,
{8582}{8607}a byl tu Akira.
{8607}{8674}J-Jo! A já jsem se snail utéct pøed ostatními.
{8674}{8723}Já taky; pøišel jsem sem, aby se mi zmìnila nálada.
{8769}{8819}V tom pøípadì pojïme pracovat.
{8906}{8953}/Nauka o vedení domácnosti/
{9067}{9115}Dnes jsi dokonalá jako vdy.
{9115}{9163}Pojïme, Tooruko-chan.|/Poznámka: Pro dívky je bìné, e mají na konci|jména "-ko". Jako Wakako, Tokiko, Sayako, atd./
{9163}{9217}Ano, Yuuko-chan.|/Poznámka: Pro dívky je bìné, e mají na konci|jména "-ko". Jako Wakako, Tokiko, Sayako, atd./
{9247}{9320}Pøestaòte s tím! Oba dva!
{9389}{9429}Oh, princezny!
{9429}{9485}Dneska jste nádherné! Dneska jste nádherné!
{9485}{9528}Jak jsem èekal, v tìchto krajkovıch|šatech vypadáte nádhernì.
{9528}{9585}I kdy vypadají trochu rezervovanì.
{9585}{9607}Je úasné se dotknout!
{9607}{9653}Pokadé je to stejné.|Je úasné se dotknout!
{9653}{9678}Dej mi svátek!|Je úasné se dotknout!
{9678}{9734}Radši by's s tím mìl pøestat, Natashou!
{9734}{9773}C-Co to dìláte?
{9773}{9811}Jdìte princezny!
{9811}{9840}Dìkujeme mnohokrát!
{9840}{9898}Hej, poèkejte!
{9898}{9953}Má nejlepší práce!
{10123}{10163}Dejte do toho všechno!
{10250}{10343}Pøesto jsem pøemoenı vášní Natashoua-senpai pro módu.
{10343}{10418}Toho chlapíka zajímá jen móda, huh?
{10418}{10491}Jak mohl pøijít s takovımi elegantními šaty?
{10526}{10572}Oh, pìknı kop!
{10671}{10704}Kouno je stejnı jako vdycky, huh?
{10704}{10774}Jak jsem èekal, práce princezny|mu pomáhá nemyslet na problémy.
{10903}{10937}Prezident Arisada?
{10937}{10994}Kam jdou?
{11272}{11380}Vítejte, øediteli Ryuusaki. Jsem |prezident Školní Rady, Arisada.
{11380}{11447}V zastoupení øeditele vás provedu po školní pùdì.
{11447}{11499}Dìkuji za vaši pomoc.
{11499}{11583}Jen nedávno jsem získal pozici øeditele pøedstavenstva|jakoto vısledek odchodu mého otce do penze.
{11583}{11635}Je tu spousta vìcí, se kterımi nejsem obeznámen.
{11789}{11851}Tohle je opravdu vıjimeèná škola.
{11851}{11907}Mùj otec je na ni velmi pyšnı.
{11907}{12018}Pøesto ji chci vidìt sám, zda to tak je.
{12018}{12092}Aèkoli to vypadá trochu brzy, |vezmìte mì na školní pùdu, prosím.
{12188}{12234}Ah, dobré naèasování.
{12234}{12297}Kouno-kun! Shihoudani-kun! Yutaka-kun!
{12297}{12338}Mohli byste sem pøijít?
{12415}{12466}Kam si myslíš, e jdeš, Mikoto?
{12466}{12522}Volá nás prezident Arisada.
{12522}{12600}A-Ale jak mùu dopustit, aby mì takhle vidìl nìjakı cizinec?
{12600}{12656}Nejdeme za ním, abychom nìjak vypadali.|Puste mì!
{12656}{12691}Kdy teï uteèeme,|Øekl jsem puste! Pøestaòte!
{12691}{12739}kdo ví, co by nám prezident Arisada udìlal?|Øekl jsem puste! Pøestaòte!
{12758}{12796}Copak je, prezidente Arisado?
{12796}{12842}Dìkuji vám za vaši tvrdou práci.
{12842}{12939}Co se to dìje? Na téhle škole jsou dívky?
{12939}{12982}Ty... ty šaty jsou...
{13248}{13275}Puste mì!
{13275}{13303}Chlapci?
{13303}{13366}To jsou naše školní princezny, na které jsme pyšní.
{13443}{13464}Tady máte.
{13574}{13599}Neuvìøitelné.
{13599}{13673}Opravdu jsou to studenti téhle školy?
{13673}{13726}Opravdu jsme kluci.
{13726}{13828}Je docela tìké, aby vypadali takhle.
{13928}{14001}Neslyšel jste o tom od bıvalého øeditele?
{14001}{14043}Otec nikdy...
{14087}{14155}Jen øekl, "Tato škola má velkolepé poklady."
{14155}{14225}"A je uvidíš, tak se ti urèitì budou líbit."
{14261}{14297}Neøíkejte mi, e to bylo...
{14297}{14355}Oni jsou zajisté vzácnımi poklady.
{14355}{14424}Jsme velmi šastní, jestli vás potìšili.
{14465}{14514}Je to pøíliš smìšné.
{14646}{14694}Chlapci ádaní, aby nosili dívèí šaty,
{14694}{14776}nazıváni princeznami a nuceni|uèástnit se školních událostí?
{14776}{14831}Na elitní škole jako je Fujimori, si to neumím pøedstavit,
{14831}{14878}studenti jsou tady hloupí jako je tohle.
{14912}{14990}Omlouvám se, e jste museli to obleèení nosit.
{14990}{15089}Zavolám okamitì pøedstavenstvu a zruším tento systém.
{15130}{15162}Co to dìláš?
{15162}{15246}Ale my jsme do toho nebyli nuceni.
{15246}{15287}Správnì, Tooru?
{15312}{15339}Ah... jo!
{15428}{15530}Pøesto nechat toto na škole existovat...
{15667}{15759}Systém princezen je na naší škole dlouholetou tradicí.
{15759}{15850}Vy to zamítáte a rozpuštíte jakoto|hloupé bez jediného pochopení.
{15850}{15885}Nebyslíte si, e je to pøíliš ukvapené?
{15885}{15919}To...
{15919}{16024}Já si pøinejmenším myslím, e bıt princeznou je skvìlé.
{16024}{16081}Získal jsem spoustu cennıch zkušeností,
{16081}{16129}a stal jsem se díky tomu prezidentem Školní Rady.
{16150}{16228}Arisada byl minulı rok princeznou.
{16245}{16425}Co kdybyste došel k závìrùm poté, co více porozumíte|této škole a nejdøíve systému princezen?
{16654}{16751}Pøeklad + korekce: WelW(etkaAa)-hime
{16765}{16865}Èasování: WelW(etkaAa)-hime
{16956}{17023}Take jste byli poádání øeditelem Ryuusakim,|abyste ho provedli po škole?
{17023}{17049}Jo.
{17049}{17147}Prezident Arisada øekl, e na krátkou dobu navštíví|naši školu, take náš poádal, abychom ho provedli po škole.
{17147}{17222}Prezident Arisada byl rozèilenı, huh?
{17222}{17351}Byl absolutnì zamítnutı jakoto bıvalá |princezna, samozøejmì, e byl rozèilenı.
{17351}{17405}Jo, já jsem taky rozèilenı.
{17426}{17519}V kadém pøípadì, ty si musíš myslet, e|by bylo lepší systém princezen zrušit, Mikoto.
{17519}{17572}Stal by se z tebe obyèejnı muskı student, e?
{17572}{17594}Já...
{17657}{17767}Aèkoli chápu dùleitost princezen na škole.
{17767}{17891}Ale kdy musím bıt princezna, je to pro mì víc ne trapné.
{17907}{17982}Kouno, mìl bys bez systému princezen problémy?
{18032}{18118}Já budu v poøádku. Ale bez princezen...
{18180}{18238}Princezny obìdvají spoleènì!
{18238}{18300}A je s nimi i Sakamoto-sama. Takovı luxus.
{18300}{18357}Jsem tak vdìènı za to, e jsem studentem téhle školy!
{18381}{18487}Kdy pøemıšlím o tom, co se stane, jestli všechna ta |energie, která se pøed nás staví jednoho dne exploduje...
{18524}{18561}To by bylo dìsivé.
{18561}{18597}T-To je pravda.
{18724}{18761}Toto je multimediální tøída.
{18761}{18798}Tohle je chemická laboratoø.
{18798}{18902}Všude máme dostaèující vybavení. Studenti jsou šastní.
{18902}{18975}Kouno-kun, ty jsi pøestoupil?
{18975}{18996}Ano.
{18996}{19095}Jako novì pøíchozí jsi musel bıt šokovanı,|kdy jsi byl nominován na princeznu.
{19095}{19130}To ano...
{19156}{19261}Ale souhlasil jsem a pøijal tu práci.
{19302}{19343}A ty, Shihoudani-kun?
{19372}{19477}Je to nekompenzovaná práce, ale cenná práce.
{19477}{19535}Uívám si bıt princeznou.
{19535}{19561}A ty, Yutako-kun?
{19575}{19662}Z tvého tónu je poznat, e urèitì nesnášíš bıt princeznou.
{19662}{19698}J-Já...
{19819}{19879}Taky nechci, aby se systém princezen zrušil.
{19879}{19963}Opravdu? Nenutíš se?
{19963}{20093}Vytvoøení prostøedí, ve kterém mùete klidnì|studovat a rozvíjet své tìlo a mysl
{20093}{20150}je zodpovìdností èlenù našeho pøedstavenstva.
{20150}{20238}No, jestli máš nìjaké problémy, neznepokojuj se a øekni mi to.
{20238}{20256}Ano.
{20256}{20415}Opravdu na nás tenhle chlápek myslí? Není to špatnı èlovìk?
{20432}{20544}Yutako-kun, slyšel jsem, e se tvoje známky|zhoršily, protoe jsi se stal princeznou.
{20544}{20621}Je to proto, e se práce princezny stává velkou obtíí?
{20621}{20670}Ne... tak to není.
{21191}{21233}Zdá se, e se s tím dá tìko vypoøádat.
{21233}{21405}On opravdu není špatnı èlovìk, ale jakmile|si nìco myslí, myslí si, e má pravdu.
{21405}{21474}Systém princezen bude zrušenı?
{21474}{21560}Ale prezident Arisada by mìl mít nìjakı nápad.
{21560}{21691}V kadém pøípadì to, e se Mikotovi zhoršily |známky nemá s princeznami nic spoleèného.
{21691}{21776}Je to proto, e tráví kadı den tolik èasu|na telefonu se svou pøítelkyní.
{21839}{21937}Dìlat to nonstop a nesoustøedit se na uèení...
{21937}{22003}Samozøejmì, e by se ti zhoršily známky!
{22003}{22070}Jestli bude náš systém princezen|zrušen kvùli toho, je to tvoje chyba!
{22103}{22132}Nedìlej si s tím starosti.
{22171}{22258}Yutako-kun, nech nás, abychom ti pomohli s uèením.
{22258}{22305}Takhle u nebude ádnı problém.
{22305}{22356}Všechno dùkladnì probereme, ne to pochopíš.
{22356}{22445}Uh, já chtìl, aby mì uèil Sakamoto-sama...
{22445}{22505}Jo, já s tím souhlasím.
{22505}{22604}Samozøejmì e ne! Nesmíš Sakamota-sama obtìovat.
{22604}{22695}Také nás poádal Arisada. Mìli bychom staèit.
{22695}{22751}Správnì. Pojïme, Yutako-kun.
{22751}{22833}Ne!!!
{22833}{22889}No, mùe za to podìkovat sobì.
{22889}{22907}To jo.
{22951}{22982}/Nauka o vedení domácnosti/
{23074}{23146}Oh, krajka se trochu zkroutila, kdy se to tady sešije...
{23146}{23188}Ah, trochu se to uvolnilo!
{23188}{23271}Uh, Natashou-senpai, èeká na nás host...
{23271}{23315}Nedìlejte si s tím starosti.
{23315}{23350}Ah, tady je taky zkroucená krajka...
{23350}{23433}Poèkejte, moná to bude lepší, kdy bude levá zkroucená.
{23433}{23447}Aj, ale...
{23447}{23540}Natashou-senpai je zodpovìdnı za obleèení pro princezny.
{23540}{23584}Je to velmi zruènı návrháø.
{23584}{23676}Tento rok vyhrál národní støedoškolskou soutì návrháøù.
{23676}{23724}Vdy byl velmi talentovanı,
{23724}{23773}ale protoe pøevzal zodpovìdnost |za navrhování obleèení pro princezny,
{23773}{23825}jeho talent se ještì zlepšil.
{23825}{23881}Podle toho, co slyším, tak kdy navrhuje|obleèení pro princezny,
{23881}{23975}tak má neustále úasnou inspiraci.
{23975}{24041}Dej si ruce sem, stùj rovnì,
{24041}{24072}s vìtší pıchou, o hodnì vìtší pıchou...
{24072}{24108}Oh, prazidente Arisado.|s vìtší pıchou, o hodnì vìtší pıchou...
{24108}{24181}Dnes pùjdu s vámi.
{24270}{24320}Dejte do toho všechno!
{24320}{24348}Ano!
{24533}{24588}Dìkujeme za vaši tvrdou práci, princezny.
{24620}{24650}Dejte do toho všechno!
{24650}{24788}Studenti jejich existenci pøirozenì akceptují.
{24788}{24851}Princezny existují, protoe si lidé jejich existenci lidé.
{24884}{24956}Úsmìvy princezen všem dodávají odvahu.
{25061}{25077}Co se dìje?
{25101}{25145}Co je to?!
{25145}{25163}To je špatné!
{25288}{25340}Co to bylo?! Øekni to znovu!
{25340}{25380}Pøerušujete náš trénink!
{25380}{25401}Všichni!
{25421}{25483}Co se tady dìje?
{25483}{25538}Nemìli byste se hádat!
{25538}{25629}Ah, no, mìli jsme malı spor kvùli høišti.
{25629}{25770}V tom pøípadì, co se takhle podívat |na rozdìlenı rozvrh u Studentské Rady?
{25770}{25887}Jestli to stále bude problém, mùete|podat Studentské Radì ádost.
{25887}{26004}Kdy se budete hádat a zpùsobíte |si nìjaká zranìní, nebudete moct hrát, ne?
{26070}{26118}To je pravda.
{26118}{26158}Trochu jsme to pøehnali.
{26158}{26221}Jo, nejdøív bychom se nad tím mìli zamyslet.
{26321}{26448}Jsou nejlepším lékem na vyléèení a uklidòují tlak ve škole.
{26448}{26545}Jsou na jejich práci velmi pyšní a také se usilovnì snaí.
{26545}{26605}Dejte prosím do svého tréninku vše!
{26605}{26645}Dejte do toho všechno!
{26886}{26954}Máte tuhle školu rádi?
{27019}{27037}Ano.
{27037}{27054}Máme.
{27054}{27089}Chápu.
{27507}{27563}Mikoto, iješ ještì?
{27595}{27670}Cítím jako by se vzorce, které mám v hlavì, chtìly vysypat...
{27670}{27723}Vypadá to na sparanskou vıchovu.
{27723}{27822}Po téhle hodinì u nebudeš poøád myslet na svoji holku.
{27822}{27864}Pøinejmenším vìnuj uèení nìjakou pozornost.
{27864}{27903}Já vím...
{27903}{27977}V kadém pøípadì, co se stalo s øeditelem Ryuusakim?
{27977}{27999}No...
{27999}{28073}V kadém pøípadì øíkal, e v bude v blízké budoucnosti schùze pøedstavenstva.
{28073}{28244}Pøedtím ne zaèneme, dovolte mi pøedstavit Ryuusakiho Kazushiho, kterı|se díky odchodu svého otce do penze, stal èlenem pøedstavenstva.
{28244}{28313}Toto je jeho první návštìva našich schùzí.
{28338}{28405}Jsem jen nováèek. Je mi potìšením vás poznat.
{28405}{28490}Slyšel jsem, e jste okamitì navštívil školu.
{28490}{28576}Co si myslíte o Akademii Fujimori, Ryuusaki-kun?
{28576}{28660}Ano. Upøímnì, byl jsem šokován.
{28660}{28723}Ah, musel jste narazit na princezny.
{28723}{28772}Jaké byly? Roztomilé, e?
{28798}{28888}Díky jejich existenci se ta škola zdá ještì krásnìjší.
{28888}{28965}Tento rok jsou princezny obzvláštì vıjimeèné.
{28965}{29045}Ve zprávì jsou fotky jejich nového obleèení.
{29045}{29099}Kde, kde? Oh, tady!
{29099}{29216}Ty fotky jsou dobré, ale radši bych je vidìl osobnì.
{29216}{29318}Díky jejich existenci je naše Akademie Fujimori tak klidná.
{29318}{29370}Um... Co to znamená?
{29370}{29471}Je neuvìøitelné, e ti, co se stanou| princeznami jsou velmi vıjimeèní lidé.
{29471}{29545}Pro studenty kolem nich je to stejné.
{29545}{29619}Díky tomu povìst naší školy roste.
{29619}{29696}Vlastnì, nìkteøí z našich èlenù jsou taky bıvalımi princeznami.
{29817}{29907}Netøeba to skrıvat. Pøedseda sám také bıval princezna.
{30305}{30434}Díky vašemu úsilí se pøedstavenstvo rozhodlo|zvıšit rozpoèet pro princezny.
{30447}{30478}Rozpoèet pro princezny?!
{30520}{30588}Zdá se, e poté, co øeditel Ryuusaki sledoval vaši èinnost,
{30588}{30668}si opravdu uvìdomil, e je existence princezen|pro tuto školu nutností,
{30668}{30737}a tak to s pøedstavenstvem projednal.
{30737}{30774}V tom pøípadì by to mohlo bıt...
{30774}{30812}To co jste od zaèátku chtìli...
{30812}{30892}Pøistrèili jste nás k øediteli Ryuusakimu s tímhle plánem?
{30892}{31009}Pøedstavenstvo se tìší na víc vašich energickıch vystoupení.
{31009}{31089}Boe! Teï mùeme uspoøádat velkou událost!
{31089}{31137}Právì nás ti chlapíci porazili.
{31137}{31170}Jo.
{31170}{31200}To je pravda.
{33506}{33539}Pøíštì: Zaèíná školní festival!
