{1}{1}23.976
{43}{172}Já, Kouno Tooru, jsem mìl na této slavné, soukromé,|chlapecké škole, na ní jsem pøestoupil
{172}{240}v pololetí, dveøe své budoucnosti otevøené|dokoøán, ani bych si to uvìdomil.
{240}{315}Myslel jsem si, e budu ít na této škole otupující ivot,
{315}{341}ale co tu dìlá tahle holka?
{341}{374}Já jsem kluk!
{374}{419}Eh? Ale nosíš naøasenou sukni…
{419}{477}Co to kecáš? Ty budeš mít taky takovou.
{477}{545}Všichni tøi jsme na stejné lodi.
{545}{587}Pojïme udìlat vše, co bude v našich silách.
{587}{618}Ne!
{618}{710}A takhle zaèal mùj ivot princezny.
{735}{794}TaSHee's Gang uvádí
{2650}{2862}PRINCESS PRINCESS
{3128}{3250}Èas milencù
{3367}{3386}/Školní festival/
{3405}{3453}Vítejte!
{3482}{3533}Vítejte všichni!
{3533}{3608}Toto je rozvrh dnešního programu. Vezmìte si, prosím.
{3608}{3654}Mikoto, rozdávej je!
{3672}{3750}Neøíkej mi, e jsi nervózní, protoe má pøijít tvoje holka?
{3750}{3829}Uh, promiò, ale brzo musím vypadnout.
{3829}{3882}Není èas, aby jsi se na schùzku s ní upravil.
{3882}{3922}Pøedtím máš poøád hodnì práce.
{3922}{3955}Ale...
{3955}{3987}Princezny!
{3987}{4075}Mohly byste oivit atmosféru u stánku naší tøídy?
{4075}{4113}Není tam dost zákazníkù.
{4113}{4150}Rozumím!
{4150}{4187}Ok, jdeme!
{4244}{4271}Oh skvìle!
{4271}{4315}Zvládla jsi to, princezno!
{4315}{4342}Sestøelila jsem to!
{4342}{4402}Princezny, mohly byste jít prosím ke stánku judo klubu?
{4402}{4476}Princezny, navštivte prosím taky vıstavu klubu biologie!
{4476}{4498}A umìleckı klub taky!
{4498}{4543}Ano! Navštívíme.
{4543}{4590}Kdy odsud mùu zmizet?
{4590}{4632}/Odpoèívárna Studentské Rady/
{4712}{4778}No, omlouvám se, e nechávám všechnu práci na vás. Dluím vám to!
{4778}{4844}Budu zpátky vèas na odpolední pøedstavení.
{4844}{4874}Jasnì, jasnì!
{4874}{5007}Zatímco budeš se svou holkou, budeme| dìlat všechnu práci princezen sami...
{5007}{5114}Správnì. Nemusíš se nièeho obávat.
{5114}{5149}Uij si to, ok?
{5214}{5268}Myslíte si, e se z toho snaím vyvlíknout, e.
{5268}{5343}Fajn. Nemusíte to takhle podávat.
{5402}{5502}No, jo. Kolem poledne není ádná dùleitá práce.
{5502}{5609}Jen musíme obcházet školu a oivovat rùzné aktivity.
{5627}{5691}Ale je tu jedna vìc, na kterou musíme dát pozor.
{5691}{5712}Jo, jo.
{5712}{5787}Dnes školu nenavštíví hodnì obyèejnıch hostù...
{5787}{5899}Jo, jo. Ale návštìvníci to taky neví, take se není èeho obávat.
{5899}{5922}Dávej pozor...
{5922}{5954}Jo, jo.
{5954}{6087}Nikdo nemùe s jistotou øíct, e na sebe cestou nenarazíme.
{6102}{6167}Promiòte! Opravdu se za to omlouvám!
{6167}{6198}Zase tohle?
{6198}{6271}Myslíš si, e ti lidi pomùou, jen kdy skloníš hlavu?
{6271}{6286}Jo...
{6286}{6366}Ne, není pro mì problém vám moji pøítelkyni pøedstavit.
{6366}{6452}Jen... to... s osobou, která pøijde s ní je tìké se vypoøádat.
{6452}{6481}Jistì, jistì!
{6481}{6527}Prostì nás nechceš v cestì.
{6527}{6600}Pokusíme se bıt opatrní a nenarazit na tebe. |Nedìlej si s tím starosti.
{6600}{6646}I tak vás ádám!
{6646}{6728}Neobjevujte se prosím pøed námi v tomhle divném obleèení!
{6728}{6760}Divném?!
{6798}{6820}Divném...
{6859}{6910}"Divné obleèení", øíkáš?!
{6910}{6956}Co myslíš tím "divnım obleèením"?
{6956}{7023}Taky nosíš tohle divné obleèení, ne?!
{7023}{7056}Je rozhodnuto!
{7056}{7113}Rozhodnì narazíme na Mikota a jeho kamarády!
{7141}{7168}Pojïme, Yuujirou!
{7187}{7217}P-Poèkejte!
{7312}{7330}Co mám dìlat?
{7390}{7461}Urèitì je nenechám, aby se pøed námi objevili!
{7644}{7658}Megumi-san!
{7699}{7760}Megumi-san! Jsi tu vèas, jak jsem èekal.
{7760}{7822}Hej, Mikoto! To ani nepozdravíš svoji sestru?|Jo, protoe mi Makoto ukázala cestu.
{7822}{7836}Hej, Mikoto! To ani nepozdravíš svoji sestru?
{7836}{7889}Megumi-san, ty šaty co máš na sobì jsou roztomilé.
{7889}{7994}Mikoto! Pøinejmenším bys mìl své sestøe prokázat alespoò malı vdìk!
{7994}{8014}P-Proè?
{8035}{8067}Podívej, podívej! Ladí nám obleèení!
{8067}{8127}Sama jsem s tím nápadem pøišla.
{8159}{8207}Sakra! Taky chci...
{8207}{8261}S Megumi-san, taky chci...
{8303}{8344}...aby to bylo takhle.
{8417}{8506}P-Proè se mi v hlavì objevila pøedstava princezny?
{8506}{8604}Proè vypadáš najednou tak divnì, Mikoto?
{8604}{8643}T-To nic!
{8643}{8707}Dobrá, pospìšme si a pojïme.
{8721}{8751}Makoto?!
{8751}{8799}Vy dva jen pøedstíráte, e jste pár.
{8799}{8855}I kdy se mi to nelíbí, nechám vás dva osamotì.
{8855}{8898}Nepøedstíráme! Jsme pár!
{8898}{8923}No, uvidíme se tak za hodinku.
{8923}{8964}Uvidíme se pozdìji, Makoto.
{8996}{9019}Mùj ty smutku...
{9043}{9064}Mikoto.
{9110}{9129}Pojïme!
{9143}{9184}Jistì! Provedu tì kolem.
{9403}{9452}Tady není, ten Mikoto...
{9452}{9503}Musí se nìkde schovávat...
{9503}{9536}Ale dùleitìjší je, Tooru...
{9536}{9577}Jo. Já vím.
{9577}{9660}Jsme jako Krysaø z Hameln.|/ Poznámka: Krysaø, z pohádky bratøí Grimmù, mìl moc svádìt hudbou své kouzelné flétny. |Svádìní ho slepì následovali, zhypnotizovaní jeho hudbou, a je dovedl k jejich smrti./
{9694}{9760}To si o nás myslí?
{9760}{9837}No, je školní festival, take si pravdìpodobnì| myslí, e je to obleèení na pøedstavení.
{9837}{9938}Nebo si moná myslí, e jsme opravdu holky, co je obvyklı pøípad.
{9969}{10069}Co budeme dìlat? Kdy nás budou takhle pronásledovat, bude to problém.
{10069}{10137}To jo. Jestli s tím nic neudìláme, bude to pìknì problematické.
{10137}{10175}Hej, vy dva!
{10175}{10221}Akiro!
{10221}{10280} Poøád tvrdì pracujete, i kdy je školní festival.
{10280}{10348}Ty taky Akiro; pracuješ, ne?
{10348}{10373}Co tu dìláš?
{10373}{10489}Hlídám všechny stánky a oblasti s událostmi,| ujišuju se, e nejdou ádné potíe.
{10489}{10563}Myslel jsme, e jsi s prezidentem.
{10588}{10660}To prezident mì poádal, abych na tyhle vìci dohlédl.
{10660}{10726}Ale tohleto stranou, ti lidé za vámi...
{10726}{10756}Tak je to...
{10756}{10797}To e nás sledují nám zpùsobuje bolest hlavy.
{10797}{10864}V kadém pøípadì by bylo hrubé, kdybychom je poádali, aby pøestali.
{10864}{10883}Rozumím.
{10883}{10937}Mohu si na vteøinku pùjèit mikrofon?
{11034}{11125}Ahoj všichni! To co dìláte zapùsobí na bìnı provoz.
{11125}{11223}Na jinıch místech je spousta zajímavıch událostí.
{11223}{11282}Co takhle jít se podívat?
{11282}{11346}V první tìlocviènì vystupuje orchestr.
{11346}{11392}V druhé tìlocviènì se promítá film.
{11392}{11452}V druhém patøe vıchodní budovy je strašidelnı dùm.
{11452}{11509}A v prvním patøe je herní koutek.
{11611}{11646}Teï by mìlo bıt všechno v poøádku.
{11646}{11667}Dobrá práce!
{11667}{11756}No, není divu, e jsi kandidát na prezidenta.
{11756}{11873}ádnı jinı èlovìk nevlastní tuhle vıjimeènou schopnost vedení.
{12044}{12120}Tohle je tvoje škola, huh?
{12120}{12168}Školní budovy jsou skuteènì nové, e?
{12168}{12275}Máme dlouhou historii, ale budovy byly renovovány.
{12275}{12323}Megumi-san je tak roztomilá!
{12356}{12455}Vdycky byla atraktivní, ale dneska| vypadá nádhernìji ne kdy pøedtím.
{12455}{12520}Ale nosit spárované obleèení s Makoto je...
{12520}{12557}Hej, Mikoto...
{12579}{12657}Všichni se dívají tímhle smìrem a øíkají nìco o princeznì.
{12657}{12696}Je to moje pøedstavivost?
{12696}{12730}Hej...
{12730}{12786}To proto, e Megumi-san vypadá jako princezna!
{12786}{12839}Zírají na tebe, protoe jsi tak krásná!
{12839}{12900}Ale Mikoto, zdá se, e se dívají na tebe.
{12900}{12929}Hej, princezno!
{12929}{12965}Miko-chan!
{13001}{13114}Nemluvte... na mì!!
{13135}{13179}Pojïme rychle pryè, Megumi-san.
{13242}{13300}T-To nebyl obvyklı Miko-chan, to byl...
{13330}{13377}U je pùl dvanácté.
{13377}{13459}Do vystoupení poøád zbıvá chvilka. Co budeme dìlat?
{13459}{13496}Pùjdeme zpátky?
{13496}{13571}Mikoto se moná nevrátí vèas. Je to trochu znepokojující.
{13571}{13615}U jsem vám øekla, e to není tøeba!
{13615}{13668}Nebuï taková. My ti to tady ukáeme!
{13668}{13728}Otravné! Nepøibliujte se ke mnì!|Jo, jo. Neznáš to tady, e?
{13728}{13760}Balí holky?
{13760}{13806}Není to zakázané, ale bude to obtìovat ostatní.
{13806}{13834}Mìli bychom to zastavit.
{13834}{13849}Jasnì.
{13849}{13932}Lidi... neslyšeli jste, co jsem øekla?
{13964}{14045}Nebo jste jen nerozumìli?
{14045}{14081}V tom pøípadì to øeknu naposledy.
{14081}{14132}Jste otravní! Vypadnìte!
{14132}{14148}Ano!!
{14148}{14233}Hej, nemyslíš, e ta holka vypadá jako Mikoto?
{14233}{14326}Jo, zvláš ve vzdorování.
{14326}{14358}Lidi...
{14358}{14401}Co...
{14401}{14461}Chtìli jsme je zastavit...
{14461}{14542}Ale pøedtím ne jsme mìli šanci, postarala jsi se o sebe sama.
{14542}{14602}Oh, taková malièkost? Samozøejmì, e jsem se o to postarala.
{14602}{14632}Samozøejmì?!
{14632}{14721}Vskutku, pøedtím ne jste pøišli, vyvádìli |kvùli princeznám nebo nìco takového.
{14721}{14759}O èem to mluvili?
{14759}{14856}Povìzte, máte tu nìjakého pøíbuzného?
{14856}{14902}Ano, svého mladšího bratra.
{14902}{14960}Mohl by to bıt... Yutaka Mikoto?
{14960}{14989}Jo. T-To je on.
{15015}{15040}Jak jsme si mysleli!
{15040}{15074}Není divu, e jsou si podobní!
{15074}{15094}Jsme?
{15094}{15142}Vy jste Mikotova sestra?!
{15142}{15209}Ne, jejich charakter je jinı.
{15209}{15258}Mikoto by nikdy neudìlal nic takového.
{15278}{15308}Take, vy...
{15308}{15346}Vy jste kluci, e?
{15346}{15408}To obleèení je pìknì roztomilé...
{15408}{15445}Není dobré!
{15445}{15521}Ale nìco takového by mému bratrovi urèitì slušelo!
{15545}{15587}I hùø...
{15609}{15693}V kadém pøípadì by opravdu nenávidìl, kdyby to musel nosit!
{15693}{15762}To je naprosto správnì, onee-sama.
{15762}{15786}Kam pùjdeme teï?
{15786}{15841}Megumi! A mimochodem, Mikoto.
{15859}{15890}Co máš s tím "mimochodem"?!
{15987}{16079}Pøeklad + korekce: WelW(etkaAa)-hime
{16093}{16207}Èasování: WelW(etkaAa)-hime
{16233}{16266}Ahoj, Mikoto!
{16266}{16338}Jsi tak podobnı své sestøe; hned jsme ji poznali, Mikoto.
{16354}{16411}Vy jste Mikotovi pøátelé?
{16411}{16456}Proè nosíte dívèí obleèení?
{16480}{16545}Ty musíš bıt Mikotova pøítelkynì, e?
{16545}{16602}Slyšeli jsme toho o tobì hodnì. Nikdy |se neunavil mluvením o tom, jak tì miluje.
{16602}{16677}Zaèínali jsme si myslet, e je s ním nìco špatnì,
{16677}{16749}ale kdy tì vidíme, tak tomu koneènì rozumím...
{16749}{16787}Ne... jen...
{16812}{16841}Opravdu atraktivní.
{16841}{16934}Nejménì mimoøádnì krásná dívka, bezpochyby.
{16934}{17045}Kdyby stála vedla Mikota, vypadali by jako skupina krásnıch holek.
{17045}{17064}Jo.
{17064}{17101}Vy dva!!
{17190}{17238}Co tady dìláte?!
{17238}{17336}Co myslíš tím "co tady dìláte"? To ty jsi na nás narazil.
{17336}{17427}V kadém pøípadì jsi nezapomnìl na odpolední práci, e ne?
{17427}{17486}N-Neøekli jste o tom Makoto, e ne?
{17486}{17548}Opravdu jsem chtìl, ale neøekl jsem jí to.
{17582}{17654}Ale tvá sestra si pravdu uvìdomila skoro sama.
{17654}{17698}Dìláte si legraci! Co øíkala?!
{17698}{17734}Hej, Mikoto.
{17751}{17811}Co tady dìláš, nechal jsi nás tam?
{17811}{17877}Uh, no...
{17877}{17941}Vy tøi vypadáte na dobré pøátele.
{17941}{17969}Jste ve stejné tøídì?
{17969}{18022}Ne, Mikoto-kun je v jiné tøídì.
{18022}{18060}Tak jste ve stejném klubu.
{18060}{18115}Ne, nejsme.
{18115}{18163}Take jakı vztah je mezi vámi?
{18163}{18177}To...
{18177}{18274}Ah... no, víš, jsme zapojení do Studentské Rady.
{18274}{18329}Pravda! Studenstká Rada...
{18376}{18447}Kdy u o tom mluvíme, poøád máme práci.
{18447}{18485}e, Mikoto? Ty taky.
{18485}{18529}Jo. To je pravda! Jo.
{18529}{18590}Oh, opravdu?
{18590}{18644}Tak my prostì pùjdeme a koukneme se kolem.
{18644}{18682}Pojïme, Megumi.
{18710}{18734}Ne!
{18734}{18791}Kdy tu zùstaneš, zpùsobí to problémy!
{18791}{18810}Proè?
{18810}{18843}Protoe...
{18843}{18872}Je tìké se na to dívat...
{18872}{18921}Po tomhle bude zase nosit dívèí obleèení...
{18948}{19048}Nechce, aby ti dotìrové otravovali jeho pøítelkyni.
{19048}{19165}Na chlapecké škole je spousta| nebezpeènıch tıpkù. Jen si dìlá starosti.
{19180}{19202}S-Správnì!
{19202}{19281}Nechci, aby tì ostatní kluci obtìovali, kdy jsi tady!
{19281}{19325}To proto by se's tu nemìla potulovat!
{19325}{19394}Rozhodnì bys mìla jít pøímo domù!
{19394}{19426}Rozumím.
{19458}{19536}Ale dìkuji ti, e jsi sem dnes pøišla.
{19536}{19586}To, e jsem tì vidìl, mi udìlalo radost.
{19586}{19647}Pozdìji ti zavolám a taky ti napíšu zprávu.
{19647}{19723}Jsi zaneprázdnìnı studiem. Nemusíš se nutit.
{19723}{19773}Vùbec se nenutím!
{19773}{19834}Kdybych tì nemohl kontaktovat, bylo by to bolestivìjší.
{19849}{19927}Pøíštì se uvidíme u tebe...
{20040}{20070}Promiòte, e vás obtìujeme.
{20070}{20141}U pùjdeme. Sbohem.
{20197}{20261}No, Megumi-san, taky musím jít.
{20261}{20364}Odprovázel jsem tì ke školní bránì, ale... omlouvám se.
{20364}{20395}To je ok, budu v poøádku.
{20395}{20453}Vánì, jsi rovnou domù, ok!
{20453}{20495}Chápu to.
{20495}{20571}Makoto, postarej se o Megumi-san, ok?
{20571}{20628}Nepotøebuju abys mi to øíkal!
{20628}{20671}/Odpoèívárna Školní Rady/
{20751}{20778}Copak je, vy dva?
{20840}{20865}Poslechni si to, Akiro!
{20865}{20948}Kdy je Mikoto se svou holkou, je to absolutnì jinı èlovìk!
{20948}{20972}Byl jako...
{21000}{21085}"Pøíštì se uvidíme u tebe..."
{21085}{21145}Nikdy by neøekl takovou vìc!
{21145}{21254}Fakt, e ti dva vypadají jako opravdu nádherné holky je srandovní!
{21254}{21330}No tak... øíkat takové vìci je pìknì neslušné.
{21475}{21537}C-Co jste sakra právì teï dìlali, kluci?!
{21537}{21633}No tak, vy dva. Jestli nebudete pøipraveni na hru, zaène pozdì!
{21633}{21659}Nesmìjte se!
{21722}{21782}Dobrá, na co se pùjdeme podívat teï?
{21821}{21860}Ti dva...
{21860}{21941}Ti dva jsou opravdu kluci, e?
{21941}{21966}Jo.
{22012}{22087}Opravdu jsou jen obyèejní pøátelé, e?
{22087}{22174}Megumi... v Mikotovıch oèích jsi jediná.
{22174}{22226}V kadém pøípadì ti dva jsou kluci.
{22252}{22346}Ale, jestli má rád nìkoho, jako jsem já...
{22346}{22413}Protoe je to tak, jak to je, kdy jsou to takoví pìkní kluci, moná...
{22413}{22440}Absolutnì ne!|Protoe je to tak, jak to je, kdy jsou to takoví pìkní kluci, moná...
{22469}{22561}Ve srovnání s Mikotovımi kamarády jsi roztomilejší!
{22561}{22666}Ne, není to o tom, kdo je roztomilejší...
{22666}{22760}Kdy jsou spoleèenì, vypadá tak klidnì, takovı se mnou není.
{22810}{22882}To proto, e je chování k pøítelkyním a ke kamarádùm jiné,
{22882}{22920}tak to prostì je.
{22920}{22938}Jo.
{22938}{23029}Díkybohu. Neøíkej Mikotovi, co jsme si øekly, ok?
{23029}{23123}Jo. Kdyby vìdìl, jak jsem ho a jeho pøátele podezøívala...
{23123}{23144}Ne!
{23144}{23268}Nechci, aby vìdìl, e na nìj tak moc myslíš.
{23268}{23287}Makoto?
{23287}{23325}Správnì, pojïme.
{23325}{23399}Eh?! Ale Mikoto nám øekl, abychom odešly!
{23399}{23554}Ten idiot... Jeho vyhıbavost nám jasnì øíká, e nìco skrıvá.
{23554}{23634}To proto, e je tu nìco, o èem nechce, abychom vìdìli.
{23634}{23698}Prostì udìlejme, o co ádal, Makoto!
{23712}{23733}Makoto?!
{23986}{24046}Teï u by mìla bıt Megumi-san doma...
{24046}{24083}Taková smùla!
{24083}{24131}Tvoje pøítelkynì nezùstala, aby se dívala.
{24148}{24167}Zmlknìte!
{24217}{24244}Zaèíná to.
{24244}{24288}Nedìlej ten kamennı oblièej, ok?
{24288}{24325}Kdo si myslíte, e to zpùsobil?!
{24325}{24379}Všichni, promiòte, e jste museli èekat.
{24379}{24521}Studentská Rada pøedstavuje "Ráj Princezen", |drama, ve kterém hrají princezny.
{24828}{24964}Byly nebyly tøi krásné princezny.
{24964}{25106}Ale jejich macecha velmi árlila na jejich mládí a krásu...
{25178}{25232}Mìli vystupovat s Alenkou v Øíši divù!
{25232}{25292}Kostımy se k téhle høe nehodí!
{25292}{25337}Kdy nebude pódium vypadat víc pohádkovì,
{25337}{25379}kostımy, které jsem udìlal, nebudou vypadat dobøe!
{25379}{25483}Zástìry a naøasené suknì nebudou fungovat, pokud to není Alenka!
{25508}{25569}Vidíš. To byl ten dùvod...
{25569}{25671}Jestli si myslíš, e mùeš udret mé tajemství, |na deset let je pøíliš brzy.
{25671}{25753}To je pravda, musíme do toho dát všechno a jít...
{25753}{25856}A teï si dáme desetiminutovou pøestávku.
{25885}{25924}Zbıvá jedno dìjiství...
{25924}{25950}Další je poslední!
{25950}{25986}Poèkejte tu!
{26032}{26075}Hej, proè jsme se zastavili?!
{26075}{26130}Tvoje hra byla skvìlá, Mikoto.
{26130}{26195}To obleèení ti opravdu sluší.
{26335}{26372}Mikoto strnul!
{26372}{26436}Co jsi to udìlala?!!
{26436}{26520}Zbıvá jen jedno dìjiství, ale jak mùeme takhle vystupovat?
{26520}{26567}Oh, omlouvám se.
{26567}{26657}Jsem na nìj jen naštvaná, e má pøed námi tajemství.
{26701}{26756}Bude to v poøádku, mám øešení.
{26756}{26805}Mùete najít prázdnou uèebnu?
{26821}{26861}No, Megumi, nechám to na tobì.
{26861}{26889}Fajn, ale...
{26889}{26952}kdy mì ádáš o pomoc, pøestaò si Mikota dobírat.
{27027}{27093}Dobrá, poèkejte tu chvíli.|/Odpoèívárna Studentské Rady/
{27174}{27218}Opravdu to bude fungovat?
{27218}{27320}Kdy je ten kluk na dnì, není lehké ho dát zase dohromady.
{27320}{27346}Bude to v poøádku.
{27653}{27673}Mikoto?
{27711}{27745}Jsi v poøádku, Mikoto?
{27768}{27787}Megumi-san!
{27837}{27860}Víš, Mikoto...
{27860}{27880}A-Ano!
{27880}{27963}Právì teï je ti asi dost trapnì, a pøeješ si, aby| si's mohl vykopat jámu a schovat se do ní,
{27963}{28092}nebo se vrátit v èase, nebo všem vymazat pamì nebo nìco takového.
{28113}{28144}Megumi-san...
{28144}{28228}Úplnì rozumím tomu, co si myslíš.
{28228}{28264}Nemusíš si dìlat starosti.
{28264}{28360}Neøíkám, e tì nemám ráda, protoe jsi obleèenı jako holka.
{28401}{28419}Megumi-san...
{28486}{28568}Nezáleí na tom, co máš na sobì, Mikoto je poøád Mikoto.
{28568}{28604}Megumi-san...
{28628}{28649}Dìkuji ti.
{28717}{28770}Musím jít. Poøád máme práci.
{28770}{28784}Jasnì.
{28877}{28897}No...
{28897}{28937}Mikoto!
{29107}{29149}Hej, jsi v poøádku, Mikoto?
{29149}{29186}Dej se dohromady!
{29186}{29212}Hej, Mikoto!
{29312}{29348}Dobrá, pojïme pracovat!
{29348}{29395}Vy dva byste si mìli pospíšit a pøevléct se!
{29452}{29468}Uvidíme se.
{29468}{29508}Megumi-san, uvidíme se pozdìji, ok?
{29508}{29574}Vidíte, ádnı problém.
{29574}{29649}Megumi ví, jak s Mikotem zacházet, víte.
{29649}{29694}Hej, Miko-chan?
{29694}{29743}Princezno, tady!
{29743}{29783}Ano!
{29783}{29855}Mùe se smáš tak pøirozenì?
{29855}{29903}Co se vlastnì stalo?
{30235}{30279}Školní festival je u konce.
{30279}{30298}Jo.
{30493}{30511}Mikoto!
{30831}{30862}Dìlej, co mùeš, ok.
{30897}{30965}Nad èím pøemıšlíš, Mikoto?
{30965}{31039}Povìz nám to! Radši bys mìl øíct pravdu. Øekni nám to!
{31087}{31115}Hej, já to chci vìdìt!
{31115}{31188}A se dìje cokoli, musí nám to øíct!
{31188}{31218}Hej, nesmìj se!
{31218}{31273}Dìláš si srandu!!
{33512}{33572}Pøíštì: Tajná minulost
