{1}{1}23.976
{512}{585}Je mi líto, e to zašlo tak daleko, Tooru.
{585}{620}To je v poøádku, strıèku.
{653}{737}Stejnì jsem vdy chtìl odejít na školu.
{737}{760}Ale...
{771}{866}Kdy tu nebudu… Urèitì…
{928}{964}No, já jdu!
{1231}{1254}Tak to je ono…
{1479}{1555}Musím si pospíšit. Pøijít pozdì hned první den by mi pøineslo jen potíe.
{1836}{1873}…Holka?
{2121}{2197}TaSHee's Gang uvádí....
{4054}{4185}PRINCESS PRINCESS
{4538}{4634}PRINCEZNA CHLAPECKÉ ŠKOLY
{5570}{5613}Ach… Err… To není, co si myslíš! To je… 
{5613}{5650}Princezno, kde jsi?
{5671}{5692}Princezno!
{5713}{5749}Kde jsi, princezno?
{5773}{5798}Princezno!
{6163}{6314}Dvùr plnı èernıch uniforem. Sakra, je to vánì pitomá chlapecká škola.
{6314}{6358}Je úasné, e zde nejsou ádné "kvìtiny".
{6402}{6482}Ale… kdo to jenom byl?
{6484}{6583}Student této školy… nemoné.
{6616}{6746}Ach, øíkal jsem, kdybyste jenom chodil na naši školu hned od zaèátku.
{6746}{6836}Pak by jste nemusel pøestupovat v tuto dobu semestru.
{6858}{6983}Rozpoznávací dny jsou za námi, take to bude pro vás zprvu tìké.
{7077}{7116}C-Co je?
{7116}{7166}Kouno-kun, vy jste krásnı hoch.
{7166}{7184}Heh?!
{7194}{7246}Musel jste bıt oblíbenı, ne jste pøestoupil.
{7246}{7292}P-Profesore!
{7292}{7349}Ne ne, to je v poøádku
{7349}{7445}Dostane se vám vøelého pøijetí hned na zaèátku.
{7486}{7557}Kdybych byl dívka, moná. Ale já jsem mu!
{7569}{7637}Nedostane se mi vøelého pøijetí.
{7654}{7756}Kouno-kun, selskı rozum tu obèas neplatí.
{7756}{7815}Tohle je chlapecká škola.
{7989}{8074}Tak, všichni pozor, pøedstavím vám nového pøestupujícího studenta.
{8074}{8110}Kouno-kun, pojïte dál!
{8305}{8328}Ticho!
{8343}{8412}Toto je Kouno-kun, kterı pøestoupil na tuto školu z osobních rodinnıch dùvodù.
{8552}{8590}Doufám, e spolu budete vycházet.
{8590}{8623}Jsem Kouno Tooru.
{8641}{8723}Doufám, e si zde zvyknu, co nejrychleji to bude moné. Rád vás poznávám.
{8759}{8889}Wow… Jsou tu opravdu jen kluci! Kluci, kam se podíváš.
{8957}{9049}Ale jak øekl profesor, jaksi se mi dostalo vøelého pøijetí.
{9070}{9138}Co je s tím jejich divnım nadšením?
{9153}{9181}Ach, Sakamoto?
{9181}{9216}Ano?
{9227}{9285}Tohle je tøídní pøedseda, Sakamoto.
{9296}{9349}Sakamoto! Prosím, postarejte se o Kounoa.
{9349}{9365}Ano.
{9412}{9466}Cítím se tak nìjak klidnı.
{9515}{9608}Je to v poøádku? Nebude tu problém? Je to nebezpeèné!
{9641}{9716}C-Co… Proè je tu takovı povyk?
{9716}{9835}Ticho! Pokud budete dìlat takovı hluk, zneklidníte Kounoa.
{9866}{9942}U jsem doopravdy zneklidnìnı.
{9967}{10064}Tak jako tak, se Sakamotem budete v poøádku.
{10064}{10150}No, tak si prosím sednìte na tamto volné místo vzadu.
{10150}{10161}Ano.
{10388}{10434}Jsem Shihoudani. Rád tì poznávám.
{10628}{10702}Co? Ta osoba vedle mì je… holka?
{10784}{10890}Není! Tohle je chlapecká škola! Krom toho má chlapeckou uniformu!
{10928}{10985}Ach, r-rád tì poznávám.
{11018}{11150}Ale i tak, takoví lidé existují. Nìco mezi klukem a dívkou.
{11167}{11263}Shihoudani, Kouno je kolejní student.
{11263}{11327}Mùete se o nìj v tomto ohledu postarat?
{11338}{11349}Jistì.
{11362}{11493}Vìc je ta, e Kouno je "to". Zùstane v okolí tvého rajonu, není to tak?
{11493}{11522}Ano, to je pravda.
{11522}{11550}Heh? Coe?
{11791}{11860}C-co je sakra tohle?
{11929}{11967}Hej, Yuu-chane. Co takhle obìd?
{11967}{12003}Shihoudani, pojïme spolu.
{12003}{12027}Jasnì.
{12096}{12270}Wow. Je to tak vdycky bìhem polední pøestávky? Je jako idol a jeho skalní fanoušci.
{12270}{12296}Kouno.
{12321}{12353}Copak je, Sakamoto?
{12353}{12410}Je obìd. Co bys chtìl dìlat?
{12410}{12496}Pokud sis vzal obìd sebou, ukáu ti školu, a se najíš.
{12496}{12569}Pokud ne, øeknu ti, kde najdeš kantınu a obchody.
{12595}{12633}Nevzal jsem si nic.
{12644}{12696}Dobøe. Pojïme tedy.
{12830}{12930}Tahle budova je pro bìné tøídy. Kadı stupeò má jiné patro.
{12950}{13012}Budova za halou je pro speciální tøídy.
{13056}{13127}Jazykové a volitelné tøídy jsou támhle.
{13139}{13185}Ukáu ti, a tam budeme.
{13210}{13228}Proè?
{13228}{13355}Koupelnu ti ukázali ráno, take víš kde je, e? Je to vedle schodù.
{13355}{13434}Proè se kadı uklání Sakamotovi?
{13455}{13528}Školní sklad je tady v hale.
{13528}{13613}Kantına je o patro vıš. Kde bys chtìl jít?
{13613}{13664}Prozatím by staèil školní sklad.
{13664}{13685}Sakamoto-sama!
{13701}{13727}"Sakamoto-sama?"
{13727}{13800}Máte k obìdu peèivo? To je nezvyklé.
{13800}{13858}Ne, jenom doprovázím kamaráda.
{13868}{13932}Ach! Ta osoba je z druhého roèníku!
{13952}{14068}(Je to tak? Ale pokud je nezískáte brzy, budou vyprodané!)|Proè se nìkdo z vyššího roèníku chová takhle k prvákovi jako je Sakamoto?
{14079}{14120}Ano. Dìkuji.
{14120}{14239}Sakamoto-sama! Sakamoto-sama! Sakamoto-sama! Dobré odpoledne! Sakamoto-sama! Sakamoto-sama!
{14456}{14476}Sakamoto-sama!
{14504}{14547}Prosím, sednìte si tady, Sakamoto-sama!
{14547}{14581}Díky.
{14596}{14684}Kouno, pokud nezaèneš rychle jíst, bude po pøestávce.
{14684}{14795}Nìjak si øíkám, e je tahle škola zvláštní.
{14795}{14902}Eh, no mùeš si i myslet, e je v témìø jiné dimenzi.
{14902}{14927}Jiné dimenzi?!
{14972}{15052}Kouno, tohle pozadí je vesmírnı prostor.
{15086}{15155}T-Tak jako tohle?
{15252}{15334}Do jakého hrozného místa jsem to jen vstoupil?
{15504}{15552}Vezmu tì na kolej.
{15563}{15613}Buï tak hodnı, Shihoudani, prosím.
{15635}{15688}Tak na vidìnou zítra, Kouno.
{15688}{15720}Jo, jasnì.
{16092}{16195}Shihoudani pùsobí jako ten typ, o kterém lidi pøemıšlí, na co asi myslí. 
{16195}{16229}V tomhle nejsem dobrı.
{16263}{16404}Øíkal jsi, e tvoje zavazadla pøijdou dneska? Obvykle je pošlou ještì pøed tvım pøíjezdem. 
{16404}{16491}Pøestoupit sem bylo náhlé rozhodnutí. To proto.
{16852}{16876}To je kolej.
{16890}{16952}Pøeklad + korekce: Morgana Ehran
{17019}{17089}Èasování: WelW(etkaAa)-hime
{17262}{17366}/Kolej Fujimori/
{17385}{17413}Boty patøí sem.
{17443}{17528}Tvoje jmenovka ještì není hotová. Postarám se o to.
{17543}{17591}Zajímalo by mì, jestli u je senpai zpátky.
{17621}{17634}Senpai!
{17645}{17727}Ach, Yuu-chane! Tohle je Kouno-kun?
{17727}{17743}Ano.
{17757}{17858}Jsem vedoucí kolejí, tøetí roèník, Tsuji. Pokud nìco budeš potøebovat, obra se na mì.
{17858}{17924}Jsem Kouno. Tìší mì.
{17924}{18040}K jeho pokoji… Bude v P-room, e?
{18040}{18149}Ach, není pochyb. Mìl by bıt v P-room.
{18265}{18335}No, pro Kounoa by bylo v poøádku bydlet sám,
{18335}{18427}ale nejspíš bude lepší dát ho k nìkomu, dokud si nezvykne na místní prostøedí. 
{18427}{18546}Co znamená, e buï Yuu-chan nebo Miko-chan se bude muset odstìhovat.
{18546}{18603}A tak nebo tak, nebude mi to vadit.
{18603}{18649}Zeptejme se Miko-chana.
{18682}{18774}To vypadá nebezpeènì; a co je "P-room"?
{18969}{19018}Miko-chane! Mohl bys na minutku?
{19018}{19044}Ano.
{19528}{19554}C-Copak?
{19554}{19603}To je ta holka s naøasenou sukní!
{19603}{19660}Ty jsi místní student?!
{19660}{19741}Hej… Tady jsou nìjaké holky?
{19741}{19829}Samozøejmì e ne! Jsem kluk!
{19829}{19874}Ale ráno jsem vidìl…
{19874}{19961}Ach, u chápu! Mikoto, on tì vidìl v "tom".
{20077}{20120}/Schùzovní místnost/
{20120}{20186}/Nevstupovat!/
{20229}{20301}Tak tedy, teï se mùeme uklidnit a probrat to.
{20319}{20411}Ehm… Kouno-kun, ty o tom nevíš, e?
{20411}{20476}Jo, ale co je "to"?
{20506}{20607}Úbor, v kterém jsi Miko-chana ráno vidìl, nepatøí k nìjakım jeho "zvláštním zájmùm". 
{20607}{20640}Tak co to je?
{20652}{20680}Jen dìlá svou práci.
{20680}{20707},,Práci?"
{20721}{20772}Tahle škola je plná chlapcù, e?
{20785}{20875}Take pøirozenì je tøeba, aby tu bylo nìco, co by obohacovalo jejich chmurné ivoty. 
{20875}{20980}Jeliko jsou tu ale mezi námi krásní chlapci, rozhodli jsme, e tihle chlapci mùou obohatit naše ivoty.
{20980}{21085}Vybereme chlapce, které všichni povaují za mimoøádnì krásné a obleèeme je jako dívky.
{21109}{21219}Nyní jsou vybráni Yuu-chan a Miko-chan.
{21235}{21384}Jeliko jejich tøídy jsou v odlišnıch budovách, øíká se jim Západní Princezna a Vıchodní Princezna. 
{21414}{21488}Princezno! Princezno! Kde jsi?
{21582}{21600}Princezna.
{21622}{21730}Ale já to nechci dìlat! Byl jsem donucen!
{21730}{21783}Jestli to nechceš dìlat, tak to nedìlej. 
{21783}{21937}Nemùu! To proto, e je zapojena celá škola! Ztratím školní kredity, pokud odmítnu. 
{21937}{21979}Co? Celá škola?
{21979}{22023}Mìl by tu bıt limit, kam a mùou zajít!
{22023}{22084}Je to pravda? Ztratíš školní kredity, kdy odmítneš?
{22130}{22238}Akademické stupnì této školy musí bıt opravdu nízké. (Pozn. Aut.: S tím jsem si vánì nevìdìla rady…) 
{22238}{22329}Nechci bıt chlubivı, ale tato škola je èíslo jedna v celém okolí.
{22329}{22397}Jsme známí jako elitní škola.
{22397}{22479}Právì, proè tedy dovoluje pokraèování takové divné tradice?
{22479}{22531}No, protoe je to chlapecká škola.
{22531}{22639}Jinak to nejde! I kdy jde o elitu, kluci jsou poøád kluci.
{22681}{22715}Nejsem si jistı, jestli bych to mohl øíct…
{22754}{22799}Tahle škola je divná.
{22841}{22919}Musím se snait, abych se do toho podivného zvyku nezapletl.
{22919}{23057}Co to plácáš, Kouno-kun? Proè myslíš, es byl poslán do P-room?
{23102}{23178}Princess Room. Zkrácenì P-room.
{23178}{23277}Abychom ochránili bezpeèí princezen, obyèejnım studentùm je vstup zakázán.
{23290}{23436}Pokud ti byl pøidìlen tento pokoj, znamená to, e Kouno-kun bude nadìjnı kandidát na princeznu.
{23436}{23489}Nemoné! Lete, e jo?
{23626}{23701}No, zjistíš to, a pùjdeš zítra do školy.
{23714}{23871}Navíc, procházet se po areálu se Sakamotem je skoro jako oznámení.
{23871}{23974}Novinky o tobì se po škole rozšíøily rychle.
{24416}{24461}Pìknì se to rozneslo, co?
{24461}{24572}Dozvìdìl jsem se to pøes Shihoudaniho. Ty za to taky mùeš.
{24572}{24627}Eh? Promiò.
{24676}{24757}Mimo to, kde je Shihoudani? Nebyl s tebou?
{24757}{24827}Øekl, e má nìco na práci a odešel.
{24827}{24878}To musí bıt to!
{24878}{24901}"To"?
{24913}{24926}Podívej.
{25292}{25377}Èau, Kouno. Dobré ráno, Sakamoto-sama.
{25391}{25412}Dobré ráno.
{25412}{25468}P-Proè jsi takhle obleèenı?
{25483}{25556}Takhle? Jen dìlám svou práci.
{25566}{25651}Byl jsem povzbuzovat sportovní kluby bìhem jejich ranních cvièení na blíící se hru.
{25664}{25734}Vèera jsi vidìl Mikota uprostøed jeho práce, ne?
{25734}{25828}I kdy to vypadalo, e utíká uprostøed své práce…
{25828}{25907}Ty jsi ten divnı, bıt tak veselı v tomhle divnım úboru.
{25921}{26041}Shihoudani, pomoz mi pøekonat temnotu mého školního ivota.
{26041}{26145}Prosím vìnuj nìjakou energii tomuto ubohému otrokovi!
{26145}{26189}Mnì taky! Mnì taky prosím!
{26189}{26221}Dobrá.
{26247}{26394}Dobré ráno všem. Pojïme vstøíc tomuto krásnému dni spoleènì.
{26408}{26515}Úsmìv andìla! Díky tomu mùeme pøeít další den!
{26515}{26649}Neøíkejte mi, e pokud bych se stal princeznou, musel bych tohle dìlat taky? 
{26649}{26727}Ne. Nemusíš to dìlat.
{26727}{26800}V mém pøípadì jen dìlám slubu navíc.
{26800}{26897}Tohle si pøáli, tak jsem jen odpovìdìl jejich potøebám.
{26941}{27069}V ádném pøípadì. Tohle dìlat nechci. Zachraò mì, Sakamoto.
{27069}{27151}To bude v poøádku. Není to jako bys u byl vybrán za princeznu.
{27162}{27282}Navíc, pokud to opravdu nechceš dìlat, tak vymyslím zpùsob, jak ti pomoct. 
{27282}{27486}Sakamoto! Jakımsi zpùsobem kdykoliv vidím tvou tváø, jsem záhadnì klidnı a utìšenı.
{27498}{27596}Jak to øíct? Je to jako bych vidìl Buddhùv úsmìv.
{27596}{27784}Omluv mì. Právì jsem ti vìnoval andìlskı úsmìv. To tì neuklidnilo?
{27784}{27815}Neuklidnilo!
{27829}{27925}Sakamoto, prosím dej mi své uklidòující síly!
{27925}{27948}Kouno?
{27948}{27990}Objímá Sakamota-sama!
{27990}{28025}On objímá Sakamota-sama?!
{28025}{28044}Je to v poøádku?
{28056}{28136}Právì jsem si vzpomnìl! Sakamoto má taky svá vlastní tajemství.
{28169}{28222}Tak jako tak, jdu se pøevlíct.
{28222}{28287}Bude lepší, kdy si pospíšíš nebo mùe tøída zaèít bez tebe.
{28287}{28303}Jo.
{28346}{28435}Naše princezna odchází. Kdyby jenom takhle mohla zùstat navdy!
{28447}{28494}O èem sakra je celı ten rozruch?
{28575}{28674}Mimo to, jak dlouho to bude pokraèovat? Jaké zklamání.
{28691}{28743}Jestli se mají rozhodnout, tak a to honem udìlají.
{28755}{28811}Nejdøív to bude tak za pár dní. 
{28811}{28877}Pøeiju to do té doby?
{28994}{29079}Promiò, e tì obtìuji bìhem tvé pøestávky. Jsi Kouno Tooru-kun?
{29079}{29114}Ano.
{29131}{29208}Bude se konat tajné setkání èlenù komise.
{29208}{29275}Prosím, abys šel po škole do místnosti studentské rady.
{29275}{29310}D-Dobøe.
{29310}{29372}Shihoudani-kun taky, prosím.
{29372}{29392}Ano.
{29392}{29425}Tak tedy, omluvte mì.
{29549}{29608}U pøišli. To bylo rychlé.
{29608}{29659}No, bude to v pohodì, dokud tam bude nìkdo se mnou.
{29704}{29775}Bylo by hezké, kdyby mi øekli, e nemusím bıt princezna.
{29775}{29809}Nebudeš muset.
{29809}{29871}Moná. Nakonec…
{29948}{29982}/Místnost studentské rady/
{30240}{30289}Pøesnì jak jsem si myslel, øekli Mikotovi, aby taky pøišel. 
{30289}{30307}Jo...
{30339}{30422}Nemìl jsem sem chodit.
{30501}{30539}No, tak jdem!
{30558}{30581}Omluvte nás!
{30635}{30762}Vítejte v sídle studentské rady, Západní Princezno, Vıchodní Princezno...
{30864}{30974}…stejnì jako novı kandidát na princeznu, Kouno Tooru-kun.
{30993}{31007}Ano.
{31027}{31101}Jsem prezident studentské rady, Arisada.
{31334}{31417}www.mycolorfullife.blog.cz
