{1}{1}23.976
{1}{46}/Místnost studentské rady/
{83}{158}Je mi líto, e vás pøipravuji o váš drahocennı èas.
{171}{215}Vy dva u mì znáte,
{215}{290}ale kvùli Kounovi-kun mì nechte pøedstavit se znova.
{349}{404}Jsem president, Arisada.
{522}{595}Tohle je vicepresident, Koshino.
{614}{636}To vypadá jako…
{653}{688}Tajemník, Tadasu.
{688}{731}Pokladník, Harue.
{746}{764}Všichni jsou…
{781}{857}Tohle jsou hlavní èlenové Studentské rady!
{882}{906}pìkní!
{1118}{1183}TaSHee's Gang uvádí...
{2992}{3198}PRINCESS PRINCESS
{3245}{3339}ZROZENÍ PRINCEZNY
{3435}{3534}Jsou na této škole èlenové Studentské |rady vybíráni podle vzhledu?
{3534}{3554}Jseš blbı?
{3554}{3620}Jak by mohli bıt vybíráni jen podle vzhledu?
{3620}{3678}Kdybychom takto vybírali èleny Studentské rady,
{3678}{3713}nebyli bychom elitní škola.
{3713}{3732}Ale…
{3732}{3818}Máte tady ten divnı systém Princezen, |tak co by ne.
{3838}{3895}Kdy se díváte na tyto pìkné èleny| Studentské rady,
{3895}{3942}musíte si to myslet.
{4024}{4061}Jsi vtipnı, Kouno-kun.
{4073}{4153}Oceòuji tvùj kompliment èlenùm Studentské rady.
{4153}{4257}Jak ji bylo øeèeno, není zde ádné pravidlo| na vybírání èlenù podle vzhledu.
{4257}{4363}Ale já byl vybrán jako president kvùli mému vzhledu.
{4416}{4443}O èem to mluvíš, Arisado!
{4443}{4479}To není moné!
{4479}{4524}Všichni víme, e jsi kvalifikovanı!
{4539}{4652}Ale ostatní jsou taky hezcí a vıjimeèní ve své práci.
{4652}{4726}Tenhle chlapík je pìknì úlisnı.
{4744}{4791}Dobrá, vrame se k tématu.
{4828}{4895}Myslím, e všichni víte dùvod, proè jsem si vás sem pozval.
{4906}{4947}Kvùli Princeznám?
{4947}{4964}Ano.
{4976}{5036}Kolik jsi toho slyšel o Princeznách?
{5036}{5127}Hm… protoe jsou tady samí mui,
{5127}{5166}potøebujeme nìkoho, kdo by obohatil jejich ivoty,
{5166}{5206}a úèastnil se školních akcí…
{5206}{5226}Správnì.
{5226}{5285}Jsou to záøivé vzory tohoto otupìlého muského svìta.
{5285}{5351}Vìtšinou pouze první roèníky mùou bıt |vybrány za princezny.
{5351}{5400}Mají více èasu, protoe nemají tolik práce ve škole.
{5400}{5447}Jejich tìla se ještì plnì nevyvinuly.
{5447}{5482}Je jednodušší je pøevléct za dívky.
{5498}{5534}Z celého prvního roèníku
{5534}{5599}vybereme ty, kteøí vypadají nejlépe |a mají vyhovující osobnost.
{5599}{5678}Pokud nìkdo jenom dobøe vypadá, ale není |oblíbenı, nebude to fungovat.
{5678}{5747}Co?! Take kdy se zmìním k horšímu,
{5747}{5790}tak nebudu muset bıt princezna, e?
{5790}{5847}Nemùeš zmìnit svou povahu tak lehce, jak bys chtìl.
{5867}{5898}Yutako Mikoto-kun,
{5922}{5958}tvá ádost nebyla vyslyšena.
{5958}{6012}Tvoje místo Princezny je nenahraditelné.
{6068}{6114}Tady je popis práce.
{6128}{6161}To nevypadá jednoduše.
{6177}{6202}Máš pravdu.
{6202}{6252}Není jednoduché bıt princeznou.
{6252}{6357}Ale abychom odmìnili tak tìkou práci,| máme nìco pøipraveného na oplátku.
{6384}{6544}Ze školního fondu máme spoustu |penìz na rozpoèet Princezen.
{6544}{6584}Je to tak, Harue?
{6584}{6619}Ano, presidente.
{6630}{6666}Øeknu ti tajemství.
{6666}{6741}Tohle je nejvìtší fond ze všech.
{6766}{6871}Kdy je tu problém s práci princezny a školou,
{6871}{6940}nepøítomnost nebo pøedèasné odchody |mohou bıt brány jako školní uvolnìní.
{6940}{7022}Jinımi slovy, neprojeví se to na záznamu docházky.
{7045}{7108}Ehm… to je ta takzvaná skvìlá vıhoda?
{7108}{7134}To není vše.
{7134}{7205}Co jsem právì uvedl, je pouhı pøedkrm.
{7205}{7258}Nyní se dostáváme k hlavnímu chodu.
{7258}{7298}Kadı mìsíc dostanete…
{7350}{7439}Tøicet stravenek na školní obìdy.
{7460}{7545}Jinak øeèeno, kdy budu obìdvat |ve škole, nemusím platit?
{7545}{7587}Všechny nezbytné školní potøeby…
{7587}{7762}Notebooky, sportovní obleèení - i boty |a uniformy - všechno pokrıvá fond.
{7762}{7815}Jinımi slovy, všechno je zadarmo.
{7864}{7900}Zadarmo? Všechno je zadarmo?
{7900}{7936}Samozøejmì.
{7936}{8006}Zadarmo? Všechny tyhle skvìlé vìci jsou zadarmo?
{8006}{8048}U se chytá, u se chytá.
{8048}{8095}Je tu ještì jedna vìc, kterou musím zmínit.
{8113}{8190}I kdy to nemá co dìlat s vıhodami.
{8219}{8311}Náš fotografickı krouek prodává fotky oblíbenıch studentù.
{8323}{8422}Za pouití portrétu získá model èást ze zisku.
{8422}{8455}Co to znamená?
{8466}{8554}To znamená, e tím mùeš získat nìjaké kapesné.
{8569}{8595}Kapesné!
{8630}{8709}Pokud se staneš princeznou, mùeš mít spousty fotek.
{8709}{8755}Bude to pìkná suma penìz.
{8770}{8789}Co myslíš?
{8789}{8818}Chceš bıt princeznou?
{8818}{8836}Ano!
{8836}{8869}Hej, Kouno!
{8869}{8907}Zní to tak lákavì.
{8907}{8936}Samozøejmì, e to chci dìlat.
{8949}{9054}Jo, myslím, e to bude nudná, bezvıznamná práce.
{9054}{9077}Kouno!
{9085}{9157}Shihoudani mi mìl øíct o tìchhle vìcech døív.
{9157}{9190}Ale, Kouno…
{9190}{9292}Byl jsi v šoku, kdy jsi o tom prvnì slyšel, nemohl jsi| ani jasnì uvaovat a vùbec jsi mì neposlouchal.
{9292}{9307}Kouno!
{9317}{9386}Co tì jen pøimìlo k tomu, abys tu práci tak lehce pøijal?
{9398}{9503}No, kdy se jen musíš oblíct jako holka a hezky |tváøit, abys mìl všechny ty vìci zdarma,
{9503}{9530}není to tak zlé!
{9530}{9605}Copak nemáš ádnou hrdost jako mu?
{9605}{9617}Ne!
{9658}{9734}Pro studenta, kterı si musí utahovat |opasek, aby il tìkı ivot,
{9734}{9771}dùstojnost nic neznamená.
{9771}{9837}Poslouchej! Musíš nosit naøasenou sukni
{9837}{9902}a upravovat si vlasy a malovat se.
{9902}{9948}Mùeš to opravdu vydret?
{9948}{10002}To proto, e mluvíš vdycky tak horlivì.
{10002}{10039}To je dùvod, proè tì poøád obtìují chlapi.
{10039}{10057}Coe?!
{10057}{10113}Mám svou dùstojnost jakoto mu.
{10113}{10139}Co je na tom špatného?
{10149}{10187}No, kdy øíkáš, e chceš bıt chlap,
{10187}{10267}proè utíkáš od své práce?
{10289}{10404}Pokud jsi schopnı projít jako dívka a |jestli tu není ádná jiná monost,|
{10404}{10496}mìj kurá k pokraèování v této høe.
{10496}{10530}To je opravdovı mu!
{10591}{10654}Proè to tak nesnášíš, Mikoto?
{10654}{10696}To proto, e má holku.
{10725}{10777}Muské srdce je sloité!
{10786}{10869}Chápu. Pokud má nìkdo holku, samo sebou |se mu nechce pøedstírat, e je holka.
{10869}{10899}O-O èem to mluvíš?
{10909}{10937}Promiò, Yutako-kun.
{10948}{10988}Tak tak je to.
{11000}{11075}Nue budu si muset s tvou dívkou promluvit.
{11075}{11095}Není tøeba!
{11103}{11124}Arisado!
{11124}{11162}U jsi domluvil?
{11162}{11204}Ach, Natashou-senpaii.
{11216}{11243}Dobré naèasování.
{11256}{11334}Kouno-kun právì souhlasil.
{11334}{11361}Opravdu?
{11361}{11392}Podívejme, podívejme.
{11392}{11434}Co... Co je?
{11504}{11582}Kouno je èernı, Shihoudani je hnìdı a Yutaka je èervenı.
{11582}{11611}Mùeme pouít usmìròující krajky.
{11611}{11664}Ne, mohli bychom pouít límeèky s odlišnımi barvami!
{11664}{11750}Samozøejmì hedvábné punèochy by mìli |ladit se sukní a se spoustou krajek.
{11750}{11830}Wow, to je úasné! Chlapci, jste vıborné modely!
{11877}{11899}Natashou-senpaii.
{11899}{11942}Dìsíte princezny.
{11983}{12002}Pardon, pardon.
{12002}{12054}Jsem pøíliš nadšenı. Nemùu jinak, ne køièet.
{12067}{12137}Musím si udret nápad, kterı jsem právì| dostal a zaèít s navrhováním.
{12179}{12214}Co to bylo…
{12214}{12282}Je to návrháø, kterı je zodpovìdnı za kostımy princezen.
{12294}{12344}Pøedseda nauky o vedení domácnosti, Natashou-senpai.
{12355}{12427}Byl jenom trochu nadšenı a pøedvedl svou zvláštní stránku.
{12427}{12464}Jinak je to milı èlovìk.
{12476}{12519}Je jen trochu posedlı svım koníèkem.
{12541}{12599}No, jestli to Kouno chce dìlat,
{12599}{12622}tak já…
{12622}{12639}V ádném pøípadì.
{12639}{12658}Prezidente!
{12658}{12698}U jsem øekl, e nemùeš.
{12712}{12743}Je to jen jeden rok.
{12743}{12772}Smiø se s tím.
{12772}{12844}To øíkáte jenom, protoe nevíte, jaké to je.
{12844}{12872}To není pravda.
{12889}{12963}Protoe Arisada ví, jaké to je.
{12963}{13006}Je to tak, protoe má zkušenosti.
{13006}{13054}Arisada bıval Princeznou.
{13132}{13190}To proto jsem øekl, e jsem byl vybrán kvùli vzhledu.
{13203}{13278}Protoe jsem byl princezna, stal jsem se presidentem.
{13298}{13390}Jen tak mimochodem, návrháø, kterı vyrábìl |mé kostımy, mìl opravdu rád kimona.
{13390}{13457}Obi byly velmi tìsná. Jaká to bolestivá vzpomínka. |(Pozn. Pøekladatelky: Pro neznalé: obi je ten pásek, kterım se uvazují kimona)
{13475}{13559}Ale byl jste tak rozkošnı, kdy jste nosil kimono.
{13567}{13649}Tradièní junihitoe, které jste nosil, bylo tak krásné.
{13663}{13735}Ne! Ne! Myslím, e obyèejné, elegantní kimono vypadalo lépe.
{13797}{13848}Nechme toho. Jak trapné!
{13874}{13889}Jo!
{13900}{13992}President vypadá nepochybnì dùvìrnì; |je pøesnì jako Shihoudani.
{14003}{14060}Zpùsob, jakım jedná s lidmi, je taky stejnı.
{14060}{14145}Hej, já netrápím lidi tak jako on.
{14155}{14171}Mimo to…
{14204}{14255}I já jsem to dìlal celı rok,
{14255}{14347}take nenechám ádného juniora, aby utekl.
{14393}{14424}Rozumíte?
{14507}{14526}Dobøe!
{14536}{14623}Musíme promyslet, jak ohlásit Kouna-kun jako princeznu.
{14640}{14674}Budeme mít všichni hodnì práce.
{14674}{14705}Sname se, co nejvíc to jde.
{14705}{14715}Ano!
{14727}{14760}Mimochodem, to platí i pro vás.
{14770}{14836}I kdy na to ještì nejsi zvyklı, Kouno Toorue-kun.
{14862}{14946}Udruj je poøád v lajnì, Shihoudani Yuujirou-kun.
{14960}{15035}Nemùeš utéct, Yutako Mikoto-kun.
{15056}{15105}Kadı z vás tøí svım jedineènım zpùsobem
{15105}{15187}pouijte svou krásu k uvolnìní napìtí na naší škole!
{15187}{15229}Dìlejme, co je v našich silách!
{15292}{15318}C… Co?
{15331}{15389}Tvoje jméno je Yuujirou?
{15389}{15441}Jo, a co s tím?
{15454}{15482}Yuujirou…
{15593}{15610}Yuujirou!
{15623}{15695}Yuu-ji-rou!
{15743}{15763}Yuujorou!
{15763}{15827}Hej Yuujirou, neslyšíš mì?
{15827}{15881}Jak bych tì mohl neslyšet, kdy jsi tak blízko?
{15893}{15924}Proè neodpovídáš?
{15924}{15955}Volám tì.
{15955}{16046}Odpovídám mlèením, protoe nejsem |spokojenı s tím, jak mì oslovuješ.
{16046}{16157}Víš, mìl bys mít jméno jako Kaoru, Miyabi nebo Haruka.
{16157}{16239}Taková elegantní jména k tobì sedí víc.
{16239}{16277}Jene ty jsi Yuujirou.
{16277}{16302}Yuujirou.
{16331}{16391}Jaké to vytøíbené a krásné jméno.
{16391}{16411}Tocchane.
{16433}{16481}Co tohle? Tocchan.
{16515}{16557}Tocchan? Jsi snad mùj otec?
{16558}{16632}Jen pouívám dùvìrnìjší zpùsob pouití tvého jména.
{16632}{16656}Jsi spokojenı?
{16760}{16835}Tocchane, Tocchane, Tocchane.|/Yuujirou, Yuujirou, Yuujirou./
{16847}{16865}Fakt...
{16880}{16926}Hádání se nad pøezdívkou… jak dìtinské.
{16964}{17021}Nechceš, abychom ti øíkali Miko-chan, e ne?
{17021}{17062}Co? Miko-chan?!
{17062}{17120}Neøíkejte mi tím kouzelnım, dívèím jménem!
{17120}{17166}Ale my jsme spoleèníci, ne?
{17166}{17184}Miko-chane.
{17184}{17224}Nejsem váš spoleèník!
{17224}{17277}Ale Miko-chan je Miko-chan.
{17277}{17327}Pøestaòte mi tak øíkat!
{17327}{17362}Zdá se, e to bude ještì zajímavìjší.
{17362}{17469}Pøeklad + korekce: Morgana Ehran
{17492}{17593}Èasování: WelW(etkaAa)-hime
{17615}{17652}/Pøijímací obøad nové princezny se bude konat na pøíští školní schùzi (5. èervna, støeda). |Všichni se prosím do té doby chovejte slušnì. Dìkujeme! Studentská ráda/|Tak, bylo rozhodnuto.
{17652}{17680}/Pøijímací obøad nové princezny se bude konat na pøíští školní schùzi (5. èervna, støeda). Všichni se prosím do té doby chovejte slušnì. Dìkujeme! Studentská ráda/|Jak rozkošné!
{17680}{17733}/Pøijímací obøad nové princezny se bude konat na pøíští školní schùzi (5. èervna, støeda). |Všichni se prosím do té doby chovejte slušnì. Dìkujeme! Studentská ráda/|Kouno musí bıt velice nadšenı ohlednì pøijímacího dne.
{17836}{17856}Zrovna jsme o tobì mluvili!
{17856}{17905}Princezno Kouno, dej ze sebe to nejlepší na pøijímací den.
{17905}{17927}Všichni tì podporujeme.
{17975}{17994}Velice vám dìkuji.
{17994}{18035}Prosím, tìšte se na to.
{18070}{18117}Kouno, ty…
{18117}{18156}/Nauka o vedení domácnosti/
{18173}{18203}Haló!
{18212}{18259}Pøišli jsme si vyzkoušet kostımy.
{18259}{18278}Promiòte.
{18278}{18328}Natashou tu ještì není.
{18328}{18387}Prosím, posaïte se támhle a chvíli poèkejte.
{18387}{18407}Dobøe.
{18467}{18485}Hej, Kouno…
{18512}{18586}Zdá se, e ses velmi rychle nauèil| jednat se svımi fanoušky.
{18586}{18627}Po tom, co se staneš princeznou,
{18627}{18688}èas, kterı strávíš takhle obklopenı ještì vzroste…
{18697}{18747}Pokud bych nevìdìl, jak to korigovat, obtìovalo by mì to.
{18747}{18771}Obtìovalo…
{18793}{18849}Kouno-kun, do toho!
{18859}{18900}Ehm… ach… jo…
{18900}{18949}Ach, tak roztomilı!
{18949}{18990}Chová se jako malá, rozkošná dívenka.
{19000}{19058}Jsi tak roztomilı!
{19058}{19092}Znám. Znám.
{19092}{19133}Vdycky mì takhle brali.
{19133}{19193}No jestli se chceš nauèit, jak s tím zacházet,
{19193}{19245}máš vedle sebe dobrı vzor.
{19295}{19311}Já?
{19324}{19338}Jo!
{19358}{19430}Nejdøív jsem si myslel, e to, co dìláš je fakt divnı.
{19430}{19469}Ale teï, kdy jsem na tvém místì,
{19469}{19520}myslím, e je to dobrı zpùsob, jak se chránit.
{19520}{19568}Myslíš dìlat tu milou, líbeznou pózu?
{19577}{19615}Nedívej se na to shora!
{19626}{19700}Líbeznost je kouzelná zbraò, která| mùe vyhrát bitvu s prvním úderem.
{19753}{19836}Pokud mùeš pouít sebedùvìru, povznášející úsmìv, |abys zabránil ostatním dostat se pøíliš blízko,
{19836}{19909}získáš vıhodu a donutíš ostatní, aby s tebou dreli krok.
{19921}{20000}Nedáš jim šanci a couvneš do svého útoèištì.
{20017}{20083}Proto, kdy se ke mnì bude nìkdo chtít dostat,
{20097}{20153}ostatní ho zastaví.
{20163}{20218}V-Vánì to funguje?
{20232}{20288}Je to tak. Funguje to pokadé.
{20311}{20401}Ale Mikoto, pokud reaguješ pøehnanì, jenom tím |nutíš lidi, aby tì ještì víc obtìovali.
{20401}{20426}To je…
{20471}{20527}Take se musím chovat mile a sladce.
{20552}{20598}Pokud se budeš snait, nebudeš mít problémy.
{20598}{20618}Vánì?
{20618}{20653}Nacvième si to.
{20664}{20695}Oslovíme tì.
{20730}{20756}Mikoto-kun!
{20756}{20802}Dnes jsi tak rozkošnı!
{20802}{20881}Prosím, vìnuj nám svùj kvetoucí úsmìv!
{20881}{21053}Ach... Haha... Um… Díky.
{21053}{21079}Špatnì!
{21079}{21112}Ne! Ne! Ne!
{21112}{21215}Tvùj stydlivı úsmìv je pro mue jako pozvánka,| jakoby øíkal: "Pojï a hraj si se mnou!"
{21215}{21299}Dokonce i kdy tì nìkdo uchvátí, neuka |svou slabost a nenech se jím ovlivnit!
{21299}{21345}Tak co? Co bych tedy mìl udìlat?
{21345}{21411}Musíš mít víc hrdosti.
{21411}{21490}A nech, aby ti lidé ukázali svou úctu.
{21502}{21523}Pøesnì takhle.
{21541}{21563}Královna!
{21615}{21674}Mikoto, jsi královna.
{21674}{21704}Budeš královnou!
{21704}{21720}Jo!
{21720}{21798}Potøebuješ mít elegantní a nedotèenı úsmìv.
{21798}{21827}Musíš ovládat tuto schopnost!
{21859}{21921}Hej, omlouvám se za to èekání.
{21921}{21966}Moje krásné princezny!
{22028}{22055}Kdy tì nìkdo osloví,
{22079}{22112}seber se…
{22143}{22185}a vìnuj mu královnin úsmìv.
{22239}{22273}To je nádhera!
{22273}{22344}Jsem tak vzrušenı vašim zpùsobem uvítání!
{22375}{22406}Vidíš, zvládl jsi to, Mikoto.
{22406}{22459}Je to vánì v poøádku?
{22473}{22524}Natashou-senpai se k tobì nepøiblíil, ne?
{22524}{22558}To je pravda, ale…
{22569}{22638}Moná jsme udìlali chybu.
{22691}{22723}To je…
{22723}{22779}Projev mé práce z lásky!
{22794}{22820}Podívejte!
{22836}{22871}Co myslíte? Není to krásné?
{22871}{22947}Pøemıšlel jsem o pouití speciální látky a |vırobì tmavì èervenıch šatù.
{22947}{22981}Ale to by bylo pøíliš provokativní.
{22981}{23015}Tak jsem vyrobil dvoudílné šaty se sakem a sukní. |/Zase.../
{23015}{23052}Tak jsem vyrobil dvoudílné šaty se sakem a sukní.
{23052}{23111}Ale! Ale! Ale! Kvalita není moc dobrá.
{23111}{23147}Nosíš vdycky takové vìci?|/Navíc teï je dešové období… Ale kdy byste to mohli nosit? /
{23147}{23171}Jo...|/Navíc teï je dešové období… Ale kdy byste to mohli nosit?/
{23182}{23199}Natashou!
{23213}{23274}Nepouívej technické termíny. Nikdo nerozumí.
{23274}{23346}Teï si to budou princezny zkoušet.
{23346}{23385}Bylo by lepší, kdybys je nechal bıt.
{23385}{23418}Jo… jo…
{23418}{23461}Dobøe, vyzkoušíme teï nové šaty.
{23461}{23486}Ok.
{23486}{23521}Nemáme na vıbìr.
{23567}{23608}Zkusme to.
{23624}{23678}Hej, jak se to nosí?
{23709}{23745}Nemùete se pøevlékat tady!
{23756}{23789}O èem to mluvíte?
{23789}{23824}Jsme všichni mui.
{23824}{23867}Já vím. Ale…
{23867}{23922}Máme svou pøedstavivost.
{23946}{23966}Zakryjte se!
{23966}{24016}Nechceme vidìt vaše pravá tìla!
{24016}{24043}Bìte tam, honem!
{24043}{24067}Pojïme tam.
{24164}{24191}Ano, pøesnì támhle.
{24191}{24253}Dejte to stranou, vedle princezen.
{24253}{24285}Prezidente Arisado.
{24305}{24364}U jste dozkoušeli obleèení?
{24364}{24379}Ano.
{24404}{24441}Proè je tu Sakamoto?
{24441}{24550}Protoe pøedseda tøídy se automaticky stává |úøedníkem vıkonného orgánu Studentské rady.
{24550}{24593}Jsem tu, abych pomohl s pøípravou místa ceremonie.
{24593}{24626}Nejen to,
{24636}{24736}Sakamoto-sama je navíc kandidát |na dalšího prezidenta Studentské rady.
{24736}{24775}Chci, aby si zapamatoval, jak usmìròuji a povìøuji.
{24800}{24850}Jak jsem si myslel, ty jsi…
{24850}{24881}Tak to není.
{24881}{24956}Chci tu jen bıt s prezidentem a zapamatovat| si poøadí bodù programu.
{25007}{25033}Prezidente Arisado!
{25056}{25127}Tak jako tak, je to mé rozhodnutí.
{25128}{25192}Co øíkáte? Zamyslete se nad tím.
{25239}{25301}Take to je to, co prezident dìlá.
{25316}{25372}Ten chlap je diktátor.
{25399}{25448}I tak… Sakamoto, kdo sakra jsi?
{25466}{25499}Oslovují tì Sakamoto-sama.
{25499}{25542}Dokonce i starší roèníky tì tak oslovují.
{25542}{25575}Kandidát na dalšího prezidenta.
{25592}{25627}Jsi snad šéfem tıhle školy?
{25627}{25663}Ne, tak to není.
{25663}{25710}Jsem jen obyèejnı prvák.
{25773}{25869}Mám bratra, kterı právì promoval, kdy jsem sem pøišel.
{25880}{26021}Mùj bratr je velmi krásnı. Byl opravdu oblíbenı.
{26021}{26119}Zdá se, e mì kvùli tomu lidi oslovují Sakamoto-sama.
{26244}{26316}I kdy vùbec nevypadám jako mùj bratr,
{26316}{26374}stejnì mì berou jako Sakamota-sama
{26389}{26437}a vyšší roèníky mi tak taky øíkají.
{26437}{26484}A prváci se nauèili dìlat toté.
{26510}{26551}Teï kdy o tom pøemıšlím,
{26551}{26627}i president mi øíká Sakamoto-sama.
{26679}{26748}Ten chlap vánì tahá za nitky.
{26916}{26946}Jsem tak unavenı.
{26946}{26985}Mìl bys bıt v pohodì.
{27001}{27067}Pro mì a Mikota je to druhı pøijímací obøad.
{27080}{27106}Jo, to je pravda.
{27122}{27154}Je to moje chyba, e to kvùli mnì musíte dìlat.
{27154}{27238}To nevadí. Dùleitìjší, budeš v budoucnu v poøádku?
{27256}{27287}Kdy jsi vzal práci princezny?
{27334}{27389}Vlastnì mi to celkem pomohlo…
{27400}{27466}…protoe se snaím ušetøit co nejvíc penìz.
{27545}{27576}Takhle...
{27580}{27633}nebudu strıci na obtí.
{27872}{27956}Nyní konèí diskuse plánu Studentské rady.
{27990}{28045}Dále pøijde to, na co všichni èekáte;
{28068}{28168}pøijímací obøad nové princezny.
{28186}{28221}Prosím, vstupte!
{28315}{28376}Nejdøív ty, s kterımi jste ji dùvìrnì obeznámeni,
{28391}{28447}Vıchodní Princezna, Princezna Shihoudani.
{28498}{28541}Západní Princezna, Princezna Yutaka.
{28600}{28664}Nyní naše hlavní osobnost,
{28681}{28718}pøestoupenı student,
{28718}{28783}novì pøijatá Princezna, Kouno Tooru!
{29231}{29328}Nyní je nechte projet a uvítat kadého.
{29361}{29415}Aèkoliv jsou velice krásné,
{29415}{29471}prosím, udrte nad sebou kontrolu.
{29517}{29548}Mikoto, nepøestávej se usmívat.
{29548}{29618}Buï královnou a vìnuj královnin úsmìv.
{29692}{29705}Páni!
{29705}{29736}Mikoto se také usmívá!
{29736}{29760}I on se usmívá!
{29762}{29864}Ale kadı ví, e jsme kluci pøevleèení za dívky.| Stejnì jsou tak nadšení.
{29864}{29909}To proto e postrádají povzbuzení.
{29919}{29985}Kdybychom byli smíšená škola, bylo by to lepší.
{29985}{30066}Ale stejnì je tu nìkdo, kdo má tajnì holku.
{30066}{30105}Nedìlej si ze mì srandu!
{30118}{30178}Ale i tak jsi obleèenı jako kvìtinka.
{30178}{30231}Proto jsem se ptal, jestli je to vánì v poøádku.
{30244}{30320}Tak jako tak, nehledì na cokoliv, jsme teï všichni na stejnı lodi.
{30343}{30407}Pro celı další rok dìkuju za všechnu pomoc.
{30442}{30459}Já taky.
{30469}{30548}Poøád jsem si tu nezvykl. Moná tì ještì poprosím| o trochu pomoci. Díky!
{30564}{30627}Ten, kdo potøebuji, aby o nìj bylo postaráno, je Mikoto.
{30627}{30653}Coe?!
{30832}{30854}Sakamoto-sama!
{30854}{30900}Zapamatoval jste si poøadí bodù programù?
{30900}{30924}P-Prezidente!
{30963}{31053}Pøíští díl |První práce, Princezna Iniciátorka
{31111}{31151}www.mycolorfullife.blog.cz
