{1}{1}23.976
{153}{276}DUEL Project
{293}{412}Office Crescendo
{453}{554}Nonami Maho      Koike Eiko
{607}{681}Original Screenplay: Tsutsumi Yukihiko|Screenwriter: Miura Uiko|Music: Mitake Akira
{750}{827}Director: Tsutsumi Yukihiko
{1290}{1324}Jsem doma.
{1485}{1521}Vrátila jsem se.
{1761}{1852}{Y:i}Vrátila jsem se domù do Tokya, |abych zde strávila svoji první zimu.
{1867}{1952}{Y:i}Mami, tohle mìsto je zvláštní.
{1964}{2098}{Y:i}Dokonce i v zimì je všude teplo.
{2334}{2433}2 LONICE, |OBYVÁK/JÍDELNA/KUCHYNÌ
{2652}{2707}"Enmusubi"|Svíèka lásky
{2898}{2953}Jsem doma, Lulu.
{3026}{3095}"Enmusubi"|Svíèka lásky
{3096}{3186}A provází štìstí Takuyu, |moji lásku.
{3242}{3313}{Y:i}Vèera øíkali v TV...
{3324}{3441}{Y:i}..e kdy se èlovìk má kde najíst, |do èeho obléct a kde sloil hlavu...
{3449}{3544}{Y:i}...patøí mezi 40% lidí, |kteøí se mají na svìtì dobøe.
{3563}{3645}{Y:i}iju Popelèin ivot tady v Tokyu...
{3650}{3755}{Y:i}...mám k dispozici byt o dvou lonicích...
{3775}{3931}{Y:i}...ale nepøipadám si, e bych |patøila mezi horních 40%.
{3949}{4118}{Y:i}Mezi dnem a vrcholem |je velká propast.
{4134}{4223}{Y:i}Èlovìk musí bıt vítìz, aby pøeil.
{4309}{4339}{Y:i}Mami...
{4351}{4412}{Y:i}myslíš, e dokáu bıt vítìz?
{5297}{5344}Nozomi, otevøi mi!
{5367}{5405}Nozomi!
{5498}{5544}Omlouvám se, Lulu!
{5617}{5666}Vydr chvilku!
{5835}{5901}Promiò, ještì øetìz.
{6073}{6126}Omlouvám se, usnula jsem.
{6133}{6170}U to nikdy nedìlej.
{6185}{6228}Doufám, e ti vyšel dobøe konkurs.
{6234}{6305}{Y:i}Batoh od Gucciho|54,000 jenù.
{6358}{6424}{Y:i}Boty Miu Miu|38,000 jenù.
{6649}{6690}Nákupy ti trvaly dlouho.
{6695}{6770}Po cestì zpátky jsem se |zastavila v agentuøe.
{6794}{6910}Jsou tak blízko, e si pøipadám |jako pod dohledem.
{6924}{7001}Šéf tam má milenku.
{7009}{7081}Aha.|{Y:i}Prasák jeden stará.
{7086}{7223}Øíkal, e jedna z nás ten konkurs udìlá.
{7227}{7281}Reisér mu to øekl.
{7291}{7341}Wow!|{Y:i}Budu to já.
{7348}{7387}{Y:i}Budu to já.
{7396}{7494}{Y:i}Sluneèní brıle Chanel|Asi 50,000 jenù
{7497}{7583}Ráda èekám na vısledek konkursu.
{7583}{7612}Je to napínavé!
{7627}{7696}{Y:i}Náramkové hodinky Hermes|230,000 jenù
{7712}{7768}{Y:i}V Kimuraye za polovinu.
{7784}{7842}Trošku se pøed zítøkem odváeme.
{7890}{7917}Pøipijeme si na štìstí.
{7938}{8000}{Y:i}Spojení zamilovanıch Cartier|260,000 jenù za pár
{8006}{8055}Já vlastnì ani nepiju.
{8064}{8140}Aha...|{Y:i}Dìláš ze sebe dámu nebo co?
{8150}{8249}Je šéfova milenka ze zahranièí?
{8282}{8321}Peruánka.
{8334}{8359}Z Peru?
{8394}{8460}Nechala mu toho ptáka.
{8469}{8567}V Peru je povaován za ztìlesnìní boha.
{8573}{8656}Øíkal, e nás vyrazí, |jestli se mu nìco stane.
{8665}{8751}Nejsme tady, abychom se |staraly o nìjakıho ptáka.
{8911}{9026}Ten konkurs nemìli dobøe zorganizovanı. |Ta tupá organizátorka.
{9035}{9095}Není tak mladá, za jakou se vydává!
{9115}{9175}Neèekala jsem, e se dostanu tak daleko.
{9179}{9284}Zaèáteèník se dostane do finále |o hrdinku "Goku-Nyo"?
{9285}{9301}"Goku-Nyo"?
{9309}{9389}Samozøejmì, to je zkratka názvu té série.
{9389}{9471}"GOKUdo no NYObo tachi (Gangsterova ena)".
{9476}{9543}Asi jsi nevidìla moc filmù.
{9550}{9610}Radši chodím na hry.
{9658}{9787}Mojí první inspirací byly |"Nylon" a "Caramel Box".
{9791}{9816}{Y:i}Nezajímá.{Y:n}
{9826}{9942}- Taky mám ráda "Come Come", "Asa Supa",...|{Y:i}- Nezajímá mì to!
{9950}{10040}Nespokojuj se s nìèím podøadnım.
{10062}{10089}Podøadnım?
{10097}{10220}Ty skupiny jsou pro nadšence.
{10244}{10308}Ty nechodíš do malıch divadel?
{10338}{10562}Všechny jsem je vyzkoušela. |Všude jen nepohodlná sedadla a špatní herci!
{10569}{10626}Kadı má jinı vkus.
{10630}{10676}{Y:i}Já tu mrchu probodnu.
{10686}{10755}Jsou mimo hledáèek médií.
{10766}{10841}Úspìšní herci pracují tvrdìji.
{10849}{10978}Sleduj víc filmy, jestli chceš bıt dobrá.
{10983}{11000}Budu.
{11018}{11054}Nezním moc vánì?
{11062}{11184}Ale filmovému prùmyslu stojí |za to se oddat.
{11185}{11249}{Y:i}Umíš tu oddanost napsat správnì?
{11258}{11334}Nejsem a moc nadšená?
{11345}{11387}{Y:i}Mnì je to jedno, ty krávo!
{11432}{11466}Pro nás.
{11479}{11575}Dìkuji.|{Y:i}Ten sáèek tuku jíst nebudu!
{11579}{11623}Dám ti peníze za polovinu pozdìji.
{11629}{11699}Dobøe.|{Y:i}Zapla hned!
{11988}{12034}"N [Nozomi]"
{12085}{12134}"N"
{12154}{12221}"R [Lana]" (vyslovováno "Rana")
{12248}{12268}{Y:i}Ta holka!
{12279}{12353}Dala jsem ti je stranou.
{12447}{12505}"R"
{12527}{12552}Ta holka!
{12595}{12670}Mùeš si vzít nìjaké moje vejce.
{12681}{12718}Urèitì?
{12730}{12765}Jasnì.
{12815}{12851}"N"
{13135}{13182}{Y:i}Mám z toho konkursu dobrı pocit.
{13281}{13330}"Mìstská kráska: První místo"
{13350}{13402}"Královna pláe: Druhé místo"
{13504}{13570}"Soutì v kráse pleti"
{14160}{14184}{Y:i}Urèitì to vyhraju.
{14199}{14230}{Y:i}Urèitì to vyhraju.
{14711}{14774}Debutovat jako hrdinka!
{14815}{14875}Poslyš, Nozomi!
{14886}{15022}Reisér se mì ptal na moje èíslo na mobil.
{15031}{15073}{Y:i}Ale na tvoje ne!
{15080}{15171}Udìlala jsi na nìho ohromnı dojem.
{15171}{15293}Málokteøí lidi udìlají takové chyby |ve ètení, které jsi udìlala ty.
{15300}{15328}{Y:i}Jako úplnı blbeèek.
{15342}{15448}Musíš se trochu odlišit.
{15464}{15527}Ty chodíš na wasedskou univerzitu?
{15574}{15617}- Zaèala jsem veèeøet.|- Dobøe.
{15652}{15671}{Y:i}Teï zaène zpívat.
{15738}{15764}{Y:i}Jako obvykle.
{16016}{16149}Do mého pokoje víc svítí slunce |a má lepší vıhled.
{16159}{16203}Nevadí, kdy si ho nechám?
{16217}{16299}Nevadí. Jsem alergická na pøedloky tatami.
{16305}{16332}Take potøebuji pokoj v západním stylu.
{16352}{16390}Teèe ti to po bradì..
{16408}{16431}Teèe? Omlouvám se.
{16451}{16547}Take ti to nevadí.|{Y:i}Nesnáším to, jak mluvíš.
{16550}{16664}{Y:i}To je hroznej módní vkus.|To trièko je moc upnuté.
{16675}{16724}{Y:i}A máš moc velkı prsa.
{17958}{18022}"Dívka tıdne: Nozomi Matsumoto"
{18044}{18158}- Prosím, neukazuj mi to!|- Proè? Sluší ti to tam.
{18178}{18294}Jsem soustøedìná na hraní.|Nejsem ádná fotomodelka.
{18300}{18355}{Y:i}Vdy je to jen mròavá foteèka.
{18356}{18395}Chápu, jak se cítíš.
{18407}{18447}{Y:i}To snad ne! U zase zaène.
{18456}{18505}Ze mì se stala hereèka...
{18513}{18536}{Y:i}Vdy jsem to øíkala...
{18541}{18739}kdy jsem byla ještì naivní støedoškolaèka.|Vìci nebyly tak, jak jsem si je pøedstavovala.
{18749}{18794}{Y:i}Nikdo neví, co to bylo za film.
{18797}{18895}Nabízeli mi tolik mimohereckıch prací.
{18904}{18981}A pak tolik erotickıch nabídek.
{18989}{19026}{Y:i}Nikdy jsem tì v nièem nevidìla!
{19032}{19130}Nikdy jsem je nepøijala. |Mùj manaer mi øíkal:
{19133}{19204}"Jsi u dost dobrá na to, |aby jsi mohla odmítat nabídky k práci?"
{19208}{19393}Já na to: "Jako hereèka udìlám všechno, |prostì mi seeòte tu správnou práci."
{19424}{19511}Take jsem se nevydala snadnou cestou...
{19523}{19588}ale udìlalo to ze mì to, co jsem teï.
{19596}{19641}Došla jsem a takhle daleko.
{19646}{19699}{Y:i}A nikam, co?
{19725}{19786}Promiò. Mluvím moc o sobì.
{19788}{19846}To nevadí. Tvé pøíbìhy jsou uiteèné.
{19852}{19912}Mimochodem, odkud jsi?
{19928}{20012}Ostrov Sadoga|{Y:i}Zase se ptáš!
{20042}{20087}{Y:i}Kde to v Japonsku je?
{20101}{20203}Máš pøítele?|Slyšela jsem, e jsi oblíbená.
{20218}{20282}Mám nìkoho, s kım chodím ven...
{20286}{20446}ale nejsem teï naklonìná vánému vztahu.
{20462}{20529}Radši budu hereèkou ne enou.
{20539}{20586}V hlavì mám teï jen "Goku-Nyo".
{20600}{20678}{Y:i}Nikdo ještì neøekl, e jsi tu roli dostala!
{20686}{20758}Tvùj milostnı ivot musí bıt nabitı.
{20762}{20820}- Ne, nemám dost pøíleitostí.|- {Y:i}Je nepopulární.
{20821}{20855}Opravdu?
{20874}{21017}Šéf mi øekl, abych se vyhnula vztahùm na pracovišti.|{Y:i}Jako nová hvìzda potøebuju dobrou image.
{21024}{21044}{Y:i}To urèitì.
{21045}{21108}A co chlapi z agentury?
{21114}{21227}- Spousta jich je nezadanıch.|{Y:i}- Snaí se ze mì udìlat blbce?
{21291}{21316}Co tøeba Ezaki?
{21338}{21352}No...
{21362}{21385}{Y:i}Bingo!
{21390}{21486}Ty ho neznáš? Ezaki Takuya.
{21496}{21571}Myslím, e minulı mìsíc skonèil.
{21585}{21672}Jo. Chtìl bıt spisovatel.
{21690}{21729}Teï chodí do školy.
{21756}{21843}Nechodí náhodou na tvoji univerzitu?
{21863}{21897}Moná...
{21912}{21997}Je roztomilej.|Nesmí se ale moc napít.
{22011}{22065}{Y:i}Odkud to víš?
{22070}{22165}Byli jste si blízcí?
{22198}{22348}Já s ním dokázala mluvit jen o filmech.
{22365}{22419}Nemám zájem o chlapa, |kterı je mi poøád nablízku.
{22425}{22537}Je opravdu fajn. |Mám ho pozvat?
{22606}{22670}Nemám zájem!
{22674}{22699}{Y:i}Protiútok!
{22700}{22786}Musím se soustøedit na "Goku-Nyo".
{22822}{22866}Pùjdu se vykoupat.
{23023}{23058}Sklapni!
{23226}{23244}Blbci.
{23270}{23290}Blbci!
{23316}{23359}Blbci. Lana i Izaki. Oba.
{23613}{23692}"Po zaznìní tónu zanechte svùj vzkaz..."
{23713}{23812}Ahoj. Hned mi zavolej zpátky.
{23995}{24126}"...není v dosahu sítì..."|- To je hroznı!
{24321}{24409}"...momentálnì mimo provoz..."
{24418}{24449}Zapla si úèty za telefon!
{24708}{24843}- Haló? Ahoj!|- Promiò, zrovna vjídím do tunelu!
{24941}{24969}Co to...
{25027}{25061}"TAKUYA"
{26087}{26112}Haló?
{26122}{26146}Haló?
{26268}{26313}Ten parchant Izaki!
{26437}{26506}Proè o mì chlapi nemají zájem?
{26523}{26578}Ani jeden...
{26594}{26633}Proè zrovna Lana?
{26639}{26698}Proè ne já?
{27199}{27213}Co je?
{27260}{27320}Pouila jsi mùj "Wash Anytime".
{27341}{27358}Prosím?
{27368}{27395}Mùj šampón!
{27410}{27444}Tvùj šampón?
{27471}{27488}{Y:i}Oh!
{27492}{27628}Nejde o nic velkého, |ale pravidla jsou pravidla.
{27651}{27720}Jen si je chci ujasnit.
{27726}{27802}Øekly jsme si, e nebudeme |v koupelnì nechávat vlasy.
{27815}{27862}Ale ty jsi je tam nechala!
{27875}{27983}Pro pøíštì! Cizí vìci by se |bez povolení nemìly pouívat!
{27983}{28032}To je pøece normální!
{28041}{28071}Samozøejmì, já...
{28072}{28169}{Y:i}Ona se bude vymlouvat?
{28186}{28224}{Y:i}Ona to myslí vánì!
{28233}{28266}{Y:i}Není nemocná?
{28273}{28306}{Y:i}Nebo na hlavu?
{28314}{28350}{Y:i}To je otravnı!
{28352}{28411}Posloucháš mì?
{28419}{28478}Zvonil ti mobil.
{28574}{28593}"Vzkaz v hlasové schránce"
{28596}{28627}"TAKUYA"
{28711}{28908}"Ahoj, tady Izaki. Omlouvám se, |ale v tu sobotu to nezvládnu."
{28912}{29038}"Mohly bychom se domluvit |na jindy. Brzy se ti ozvu."
{29191}{29225}Byla to tvá máma?
{29526}{29588}Musím bıt krásná!
{29700}{29736}"Obsazeno"
{29744}{29786}To je doba!
{30235}{30280}"TAKUYA"
{30598}{30703}"Ahoj. Nevolala jsi mi |pøed chvílí z pevné linky?"
{30716}{30727}"Omlouvám se, já..."
{30788}{30983}"Zpráva vymazána. |Nemáte ádné nové zprávy..."
{31360}{31521}Nozomi, chtìla bych se ti omluvit. |Jen jsem ten šampón chtìla vyzkoušet.
{31592}{31649}Mìla jsem se tì nejdøív zeptat.
{31687}{31727}Je mi to líto.
{31784}{31810}To je v poøádku.
{31848}{31889}Mám ti koupit novı?
{31917}{32035}Nedìlej si s tím starosti.|Omlouvám se, e jsem se tak rozèílila.
{32091}{32142}To ti volal Takuya?
{32249}{32359}Slyšela jsem, e se scházíte.
{32376}{32425}On ti to øekl?
{32452}{32510}Poslal mi e-mail.|Chceš ho vidìt?
{32643}{32682}{Y:i}Jsou si blízcí?
{32691}{32802}{Y:i}Email> Lano, jak se máš? Díky za minule (srdce).|Dávej pozor, a nenachladneš. Nìkdy zajdem do kina.
{32804}{32935}Je roztomilı. Líbí se mi jeho oèi.
{32967}{33071}Proè si s ním teda nìkam |nezajdeš? Asi je volnı.
{33086}{33219}Jsem radši, kdy jsme kamarádi. |Jako filmoví fanoušci.
{33220}{33284}Nevykládej si naše pøátelství špatnì.
{33427}{33456}{Y:i}Mám tì!
{33651}{33689}"Èistící prostøedek"
{35228}{35346}Ahoj, tady Nozomi. |Volám ti zpátky.
{35361}{35389}Ehm...
{35473}{35498}Blbeèku!
{35641}{35727}- Haló?|- "Ahoj, Nozomi."
{35742}{35883}- Mami?|- "Pøijdeš sestøe na svatbu?"
{35896}{36003}Øíkala jsem ti, e v šoubyznisu |není lehké udìlat si èas.
{36012}{36144}"Ještì jsem tì ani nevidìla v televizi."
{36149}{36313}"Ještì ty ses neusadila |a chodíš na univerzitu."
{36322}{36410}"Vra se na zem."
{36432}{36642}"Co kdyby ses provdala |za toho syna obchodníka s rıí?"
{36655}{36733}To by bylo plıtvání mım vzdìláním!
{36751}{36835}"Proè se nechceš vdát?"
{36849}{36922}U mi je z toho tvého stìování špatnì!
{37112}{37193}"Šastnı Novı rok"|"Bereme se..."
{37267}{37336}"Jsem nová hvìzda show businessu!"
{37460}{37534}"To je pìkné dìvèátko!"
{37539}{37629}"Má hezkı hlas a dobøe tanèí!"
{37636}{37698}"Je jako opravdová hereèka!"
{37702}{37771}"Tøeba z ní jednou nìjaká bude!"
{37777}{37867}- "V Tokyu?"|- "Ano, v Tokyu!"
{38528}{38565}Nebyla to moje chyba...
{38586}{38623}Nebyla to moje chyba!
{38823}{38883}Vstupní zkouška byla dobrá.
{38888}{38959}Èím víc vìnovaného úsilí, |tím blí byl cíl.
{39424}{39451}Èas jít do postele!
{40023}{40049}Co je?
{40062}{40134}Vzala jsi mi mùj nápoj |na doplnìní kolagenu!
{40137}{40164}Coe?
{40169}{40238}V lednièce! Zelená láhev!
{40257}{40372}Jak bych mohla? |Na všechno píšeš jména.
{40380}{40438}Ráda bereš to, co je moje.
{40469}{40496}Neuráej mì.
{40504}{40622}- Slyšela jsem, e udìláš všechno, abys tu roli dostala. |- To závisí na mıch dovednostech.
{40627}{40720}Šéf mi øíkal, abych si dávala |pozor na tvoji drzost.
{40750}{40855}Jsi si jistá, e jsi nenabídla |svoje èíslo reisérovi?
{40860}{40906}Jsi rozèilená?
{40922}{41012}Chci si to vyjasnit. |Omluv se!
{41023}{41057}Hned s tím pøestaò!
{41117}{41223}Nevzala jsem ho, |ale koupím ti novı.
{41546}{41564}Hups.
{41639}{41691}Poøádnì zavírej víèko!
{42253}{42270}"R"
{42292}{42347}Skladujte postavené.
{42750}{42772}Co chceš?
{42782}{42839}Ty taky kradeš.
{42852}{42869}Coe?
{42876}{42941}Nenadávej mi do zlodìjù.
{42968}{43040}Nechápu tì.
{43071}{43195}Vím, e si nemùeš Chanel dovolit. |Prostì se pøiznej.
{43204}{43245}Nepouila jsem ho!
{43255}{43368}Tak si to ujasnìme, |protoe spolu musíme ít.
{43378}{43438}Máme pravidla, tak se jich dr!
{43441}{43543}Ty jsi je porušila!|Omluv se stejnì jako já!
{43552}{43607}- Jenom jsem dovøela víèko!|- Nevìøím ti!
{43615}{43755}Tady jde o princip.|Tvùj pøístup nestojí za nic!
{43767}{43847}Zamysli se nad sebou!
{43864}{43986}Dobøe! |Koupím ti novı!
{44030}{44067}Tím to neskonèilo.
{44088}{44169}Tak se vymáèkni!|Co je?
{44182}{44217}Au!
{44271}{44388}Závidíš, protoe vyhraju ten konkurs.
{44397}{44451}Byla jsi na mì protivná!
{44546}{44675}Mùeme si o tom promluvit v klidu ráno?
{44693}{44739}Potøebuju se vyspat.
{44759}{44818}Obì bychom se mìly vyspat a odpoèinout si...
{44833}{44883}abychom si zítra vyslechly vısledek.
{44896}{44985}To je pøece normální!
{45166}{45227}Napustila jsi vanu?
{45267}{45376}Dodruj pravidla.|Nechceme suchı vzduch.
{45752}{45872}"Její manel mìl pomìr s porno hereèkou!"
{45878}{46008}- "Jake se jmenovala? Lana?"|- "Nìkteøí mui se nechají snadno svést!"
{46694}{46727}"N"
{48051}{48103}Nech toho!
{48914}{48938}Nebyla to moje chyba!
{48999}{49017}Nebyla to moje chyba!
{52787}{52822}Omlouvám se.
{53053}{53095}Vynahradím ti to.
{53205}{53233}Omlouvám se.
{54033}{54095}Jsem vrah?
{54137}{54155}Prosím?
{54200}{54273}Mùj bıvalı milenec...
{54319}{54363}Zabila jsi ho?
{54388}{54422}To ne.
{54456}{54624}Jeho ena ve vanì podøezala zápìstí |sobì a svému dítìti.
{54738}{54917}Nevìdìla jsem, e je enatı.
{54996}{55045}Hloupé, e?
{55183}{55248}Tvoje tváø...
{55264}{55287}Tváø?
{55337}{55453}...vypadá unavenì.
{55828}{55935}Podrádìní zpùsobuje køeè na tváøi.
{55967}{56011}Hlavnì kolem oèí.
{56707}{56749}Trochu to bolí...
{56770}{56831}Protoe máš unavené oèi.
{56881}{56952}Pøíznak stárnutí...
{57215}{57271}Pøíliš oleje...
{57548}{57650}Nemìla bys bıt tak dùvìøivá.
{57705}{57790}Proè neøekneš nìjakımu |roztomilımu takovi, a ti koupí...
{57795}{57833}nìjaké další podprsenky s vycpávkou?
{58312}{58347}Do hajzlu!
{58419}{58440}Hej!
{59180}{59268}Já u...
{59283}{59332}...s Takuyou spala.
{59378}{59509}Nemìla bys mladıho kluka |moc dlouho napínat.
{59575}{59624}Ty jsi panna.
{59624}{59743}To je k smíchu!
{59790}{59866}Proto se chováš tak nedospìle!
{59871}{59947}Vypadni na svùj ostrov a zaèni ít!
{60440}{60500}"Jsem alergická na pøedloky tatami."
{60655}{60689}Co to sakra...?
{60711}{60793}Ostrov Sadoga je pìkné místo.
{61070}{61120}Já jsem alergická na...
{61805}{61850}Pøestaò, ty mrcho!
{61992}{62028}Varuju tì!
{65928}{65976}Já tì zabiju!
{66840}{66898}Chytej nymfomanko!
{67085}{67103}Au!
{68217}{68242}Zùstaò kurva tady!
{69416}{69464}Jsi tak bezbranná!
{70744}{70769}"Takuya"
{70877}{70925}"Haló. Nozomi?"
{70938}{70984}"Koneènì jsem tì zastihnul!"
{70997}{71054}"Jsem pryè u své babièky."
{71057}{71249}"Vánì onemocnìla. |Omlouvám se, e jsem zrušil tu schùzku."
{71257}{71301}"Zlobíš se?"
{71372}{71405}"Miluju tì."
{71422}{71488}"Ha! Já to øekl!"
{71517}{71550}"Slyšíš mì?"
{71558}{71672}"Haló? Moc tì miluju!"
{71725}{71836}"Miluju tì, Nozomi."
{71846}{71957}"Je mi trapnì. Podívej, vrátím se..."
{72284}{72341}Poprvé, co jsem dala chlapovi kopaèky.
{72465}{72511}Je to dobrı pocit.
{72636}{72736}Teï mùu bıt hereèka.
{73129}{73177}Jsi "Cínovı panáèek"!
{73190}{73215}"Strašák"!
{73229}{73255}"Strašpytel lev"!
{73270}{73306}"Èarodìj ze zemì Oz"!
{73318}{73354}Já jsem "Dorothy"!
{73366}{73404}Já jsem hrdinka!
{73409}{73461}Hrdinka je moje!
{74423}{74458}Vypal.
{74473}{74526}Ty strašáku.
{74696}{74738}Dobøe.
{74939}{74997}Jestli chceš umøít spoleènì.
{75175}{75209}Zbabìlèe!
{76896}{76964}Zase zabíjím!
{77194}{77219}Prásk!
{77342}{77390}Prásk!
{77500}{77555}Prásk!
{77747}{77794}Zase vana.
{78561}{78603}Ty prášky...
{83327}{83417}Øekni mi tvùj první film.
{83435}{83458}Coe?
{83480}{83540}Ani šéf ho neví.
{83565}{83639}Vydali ho na DVD?
{83687}{83762}"Sleèna vìzeò - 1992"
{83775}{83880}1992? To je hodnì dávno.
{83900}{83929}Neser.
{83973}{84009}Koho jsi hrála?
{84035}{84118}Zrádné dìvèátko, které muèí.
{84157}{84223}Mìla jsi dlouhı text?
{84303}{84425}"Ne! Prosím ne!"|To je tak celé.
{84473}{84518}Jak srdcervoucí.
{84556}{84639}Bezejmennı enskı vìzeò.
{84666}{84816}- Svléknou ji?|- Bijou ji a ona køièí.
{85089}{85117}Nesmìj se.
{85250}{85332}Je po všem, jestli mi tuhle roli nedají.
{85358}{85425}Je to má poslední šance.
{85455}{85509}Nemùu skonèit jako neúspìšná.
{85530}{85632}Jestli se to stane, |nebudu vìdìt, kdo jsem!
{85727}{85798}Tak si ji vezmi.
{85827}{85867}Já to vzdám.
{85915}{86016}Stejnì se mi ten film nelíbí.
{86092}{86159}Ne. Mnì se nelíbí.
{86244}{86320}Na to jsem moc hrdá.
{86361}{86501}Jsi ubohé stvoøení.
{86623}{86686}Èasem budeš stejná.
{87377}{87463}Já ten konkurz chci vzdát.
{87546}{87621}Není tøeba.
{87686}{87740}Zabiješ mì?
{87760}{87856}Máma bude breèet na Jakémsi ostrovì.
{87897}{87947}Ostrovì Sadoga.
{88092}{88260}Stejnì nemùeš hrát s touhle tváøí.
{88315}{88631}Profesionální hereèka dokáe uzdravit |svoji tváø za jednu prospanou noc.
{88796}{88897}Sbohem. Sleèno Panno.
{88952}{88988}Polib mì.
{89050}{89106}Nebuï blbá.
{89141}{89194}Nikdy jsem se nelíbala.
{89240}{89294}Dopøej mi mùj první polibek.
{89394}{89457}Prosím.
{89541}{89629}Myslela jsem, e v Tokyu se doèkám.
{89683}{89728}Moc tì prosím.
{89783}{89823}Polib mì.
{90404}{90466}Jsi tak pìkná.
{91599}{91693}To bylo od tebe naivní.
{91718}{91798}Proto ti tvá láska proklouzla.
{91815}{91891}Dobrá práce, sleèno Panno.
{91912}{91943}Díky.
{91999}{92086}Proè nespolupracujeme?
{92126}{92170}Jako pár?
{92199}{92294}Mohly bychom mít vìtší šanci na úspìch.
{92330}{92397}Dobøe bychom vycházely.
{92433}{92459}Dobøe.
{92473}{92568}- Dìláš komedie?|- To si dìláš srandu!
{92589}{92660}Nikdy!
{92721}{92786}Nemáš ani na tu komedii.
{92869}{92990}Já jsem filmová hereèka!
{93395}{93439}Krásnı pocit.
{93484}{93553}Toho budeme litovat.
{93621}{93680}Bude to úleva.
{93723}{93781}Hodnì štìstí.
{93878}{93925}Tobì taky.
{95289}{95413}"Po zaznìní tónu zanechte svùj vzkaz."
{95478}{95608}"Omlouvám se za zpodìní. |Tady Asaka z produkèního."
{95627}{95703}"Mám pro vás dobrou zprávu."
{95731}{95871}"Ohlednì filmu Gokudo no Noybo tachi!"
{95882}{95970}"Vybraly vás obì!"
{95974}{96113}"Slyšíte? Obì budete hrdinky!"
{96147}{96251}"Pøepsali scénáø."
{96270}{96398}"Mohly byste pøijít ráno |ke mnì do kanceláøe?"
{96949}{97021}Hrály
{97050}{97153}Lana              Nonami Maho
{97160}{97273}Nozomi            Koike Eiko
{97637}{97695}Staff
{97724}{97762}Executive Producer: Kawai Shinya
{97767}{97839}Producers|Manabe Kazuki|Nakazawa Susumu|Ishida Yuji
{97841}{97889}Original Screenplay: Tsutsumi Yukihiko|Screenwriter: Miura Uiko
{97920}{97961}Music: Mitake Akira
{97961}{98002}Cinematography: Karasawa Satoru
{98002}{98055}Art Director: Inagaki Hisao
{99704}{99810}Office Crescendo
{99824}{99939}DUEL Project
{99994}{100136}Director      Tsutsumi Yukihiko
{100150}{100300}Pøeloil Tadi|www.cesketitulky.com