{1}{17}23.976fps  DivX  512x384  184,4 MB
{17}{113}Fujiwarano Sai, hráč GO z doby Heian
{113}{209}prošel časem a vrátil se do světa v mysli Shindoa Hikara.
{209}{343}za účelem dosáhnout Ruky Boha
{1335}{1390}Z angličtiny: Anakreon
{2750}{2798}Kdybych já...
{2798}{2846}uměl hrát...
{2846}{2894}hrát...
{2894}{3086}takhle!
{3086}{3190}Hikaru...
{3236}{3300}Čtvrtý zápas:|Kaga z klubu Shougi...
{3781}{3853}Sai..
{3843}{3936}Ty jsi právě...
{3936}{3984}Převzal...
{4059}{4081}Cože?
{4081}{4093}Hej ty!
{4138}{4174}Co přesně se stalo?
{4174}{4242}Neměl jsem ho nutit sem jít?
{4336}{4364}Jaký je?
{4428}{4489}V jeho hře není žádné rušení..
{4489}{4521}a žádná slabost, které by se dalo využít..
{4535}{4570}perfektní příklad hry Pro.
{4575}{4600}Takže..!
{4627}{4711}To je vše co můžu říct z pár začátečních tahů.
{4725}{4788}Nedokážu říct nic o jeho síle.
{4788}{4820}Hmm.
{4845}{4908}Ale...
{4908}{4932}Ale co?
{4932}{4961}No, nic...
{5004}{5124}*Ten poslední tah... byl jiný*
{5124}{5172}dalo by se říct, že je to špatný tah...
{5172}{5228}Avšak...
{5248}{5292}Ty kreténe!
{5292}{5339}Převzal jsi moje tělo?!| Podivné, co to dělá?
{5339}{5387}Nejen, že jsi vstoupil do mého vědomí, ale zkusil jsi převzít i moje tělo!
{5435}{5507}Není možné, že bych mohl hrát takhle!
{5507}{5548}N-ne!
{5548}{5627}Nemůžu převzít jen tak něčí tělo!
{5627}{5675}Chceš tím říct, že ten kámen jsem položil já?
{5675}{5720}Přesně tak.
{5720}{5747}Lháři!
{5747}{5819}Tak zkus položit támhleten kámen stejně jako GO kámen?
{5819}{5843}Dej svou ruku do takovéhle polohy.
{5854}{5884}Takhle?
{5891}{5905}Tak.
{5905}{5953}Dobře!
{6055}{6099}Neudělám to!
{6100}{6150}Ale ty jsi to zahrál!
{6155}{6203}Dokonce jsi to nezahrál tam kam jsem ti řekl!
{6203}{6298}Dobře, plánuješ převzít moje tělo, když dostaneš šanci, že jo?!
{6298}{6368}Jistě, říkej si co chceš!
{6404}{6422}*Ale, Hikaru.*
{6435}{6483}*to byl tvůj tah.*
{6504}{6549}*Začínáš se učit GO*
{6549}{6659}*a musel jsi cítit, že jsi chtěl položit kámen tam.*
{6730}{6848}Ale Touya-Meijin byl tak úžasný!
{6865}{6932}Touya se pravděpodobně naučil hrát GO od něho.
{6946}{7015}Já ani nedokážu správně zvednout kámen.
{7042}{7066}Hikaru...
{7066}{7138}Zkus to ještě jednou.
{7145}{7186}Vzdej to.
{7190}{7210}Vím, že to nedokážu.
{7210}{7275}Hikaru!
{7275}{7425}Akari...
{7409}{7465}Právě jsem se zastavila u tvého domu.
{7480}{7531}Co jsi dělal celou tu dobu?
{7545}{7569}Hrál jsem GO.
{7579}{7617}Go? Znovu?
{7630}{7689}Hikaru, zajímáš se teď o GO?
{7689}{7751}Ne, nic takového.
{7785}{7905}Rozumím,
{7905}{7953}Tohle...
{7953}{8019}Škola mé sestry pořádá výroční festival.
{8049}{8062}Pojďme!
{8063}{8088}Ani náhodou.
{8097}{8128}Proč?
{8176}{8250}A taky jsem ti chtěla koupit nějaké takoyaki...
{8255}{8277}To je v pořádku!
{8289}{8360}Takže v neděli ve 2 před vchodem školy Haze..
{8360}{8384}Řekl jsem že nejdu!
{8390}{8425}Hikaru!
{8432}{8507}Ok, asi půjdu domů a dám si nějaké nudle.
{8555}{8640}Ve 2 před vchodem školy Haze ok? 
{8720}{8768}Proč s ní nejdeš?
{8768}{8792}Ani náhodou.
{8800}{8887}Představ si, co by všichni říkali, kdybych šel na takové místo s holkou.
{8890}{8980}Hikaru, možná tě má ráda?
{9000}{9054}Co? O čem to mluvíš?
{9830}{9895}Ta holka....
{9895}{9960}Není tady?!
{9989}{10027}To je nějaký festival?
{10039}{10087}Festival pořádaný školou svatyně?
{10080}{10150}Jo...něco takového.
{10159}{10249}Ale důležitější je, že jsem si nevzal žádné peníze.
{10302}{10350}Hej, mám nějaké takoyaki
{10365}{10414}Vypadá to dobře, taky bych si dal.
{10422}{10480}Hikaru, podívej támhle!
{10494}{10560}Podívej, hrají Go!
{10586}{10655}Pojďme tam! Prosím, prosím, prosím!
{10662}{10705}Ale jen na chvíli, ok?
{10720}{10775}Tady je problém pro středně pokročilého hráče.
{10779}{10830}Ukažte mi první tři tahy.
{10900}{10960}Nejprv by černý měl hrát tsuke,
{10974}{11011}potom bílý táhne...
{11025}{11046}tady.
{11050}{11105}A co když bílý zahraje sem?
{11116}{11165}Aj, vidím.
{11174}{11243}Je to poměrně těžké.
{11259}{11275}Hikaru,
{11295}{11316}Co je to za knihu?
{11343}{11411}Tsumego ze zápasů Touyi Meijina..
{11422}{11501}Je to cena pro toho kdo uhodne tsumego správně.
{11500}{11545}Chceš to zkusit?
{11549}{11597}Hikaru, já chci! Já chci!!
{11607}{11661}Dobrě! Dobře!
{11679}{11701}Můžeš začít.
{11701}{11725}Díky.
{11741}{11770}Ve které jsi třídě?
{11778}{11820}6.třída, základní škola.
{11828}{11880}Tedy začněme s lehkým problémem.
{11905}{11940}Tady.
{11945}{12029}Myslím, že to zvládnu sám...
{12032}{12065}Nic neříkej, Sai.
{12070}{12099}Ano
{12461}{12534}Velmi dobře...to je správně.
{12545}{12570}Tady je tvoje cena
{12570}{12600}Cože?! Kapesníky?
{12622}{12670}Můžeš mi dát těžší?
{12674}{12720}Těžší?
{12735}{12760}Jsi si jistý?
{12770}{12796}Sai, spoléhám na tebe..
{12796}{12813}Ano
{12814}{12858}Tady je problém pro hráče nízké úrovně.
{12858}{12910}I já bych s ním měl problémy.
{12915}{12955}Ukaž mi první tři tahy.
{13100}{13140}To je správně..., to bylo ryché...
{13140}{13181}Odpověděl bez zastavení...
{13190}{13228}Tady je pomerančový džus.
{13228}{13315}Dej mi ten nejtěžší, za který můžu vyhrát tsumego knihu.
{13323}{13371}Nejtěžší?
{13375}{13395}Tady...
{13400}{13470}Jestli to uhodneš, jsi na stejné úrovni jako Touya Akira.
{13467}{13515}Touya Akira?
{13525}{13539}Znám ho!
{13550}{13591}Je opravdu tak silný?
{13600}{13680}Pravděpodobně dost dobrý, aby prošel zkouškami na Pro.
{13683}{13790}Učí dospělé hrát GO.
{13800}{13885}Touya Akira by měl být schopný vyřešit tento problém...
{13894}{13960}Můžeš začít, první tah je klíčový.
{13971}{14025}Touya Akira...
{14042}{14067}Dobře.
{14075}{14110}Chceš to zkusit sám?
{14316}{14390}První tah je... tady že?
{14390}{14425}Co si myslíš že děláš?!
{14450}{14480}IGO je stupidní,
{14490}{14540}Co je tak skvělého na Touyovi Akirovi?
{14540}{14620}Je to loser který prohrál se mnou.
{14642}{14700}Shougi je stokrát zábavnější než GO.
{14875}{14906}Touya prohrál?
{14912}{14961}Je silný jako Pro a prohrál?
{14965}{15040}Jsem silný, to je vše, imbecile.
{15080}{15122}To je Kaga.
{15140}{15235}Byl ve stejném kurzu Igo jako Touya Akira.
{15250}{15318}Vyřešil tohle obtížné tsumego bez přemýšlení.
{15340}{15361}Ten kluk..
{15375}{15400}Kdo je to?
{15415}{15457}Tsutsui
{15457}{15525}Jak to jde tvému GO klubu?
{15530}{15590}Nehledal jsi zoufale členy?
{15600}{15660}Můžu za vás hrát, pokud chcete.
{15700}{15730}Klub Go?
{15750}{15823}Naše škola nemá GO klub.
{15835}{15910}Kdybych sehnal 3 lidi k účasti v turnaji...
{15913}{15970}škola by z nás udělala klub.
{16005}{16057}Ty víš, jak jsem silný.
{16067}{16129}Jsem tisíckrát silnější než ty.
{16135}{16235}Nechci pomoc od někoho, kdo položil žvýkačku na desku.
{16249}{16280}Dobře, dobře!
{16295}{16395}A kdo to byl, kdo mě prosil abych vstoupil do turnaje?
{16402}{16425}Tady je tvoje cena.
{16425}{16485}Vezmi si ji a odejdi.
{16525}{16590}Tsumego ze zápasů Touyi Meijina?
{16710}{16861}Nenávidím.... GO...a Touyu Akiru!
{17130}{17160}Co? 
{17160}{17220}Proč nenávidíš Touyu Akiru?!
{17260}{17295}Ptáš se proč?
{17310}{17360}Říkáš mi co mám dělat?
{17410}{17492}Hej ty...
{17543}{17567}Máš kuráž...
{17580}{17605}Dívej se pozorně.
{17745}{17770}Ve které je to ruce?
{17783}{17855}Když uhodneš, řeknu ti to.
{17861}{17965}Ale pokud neuhodneš, zbiju tě do kuličky.
{17985}{18027}Co si myslíš, že děláš Kago?!
{18035}{18075}Hej ty, běž už domů.
{18075}{18130}Ha!Máš velkou hubu.
{18131}{18200}Ale nemůžeš založit svoje slova, že?
{18210}{18226}Hikaru...
{18235}{18266}Neměl bys.
{18276}{18330}Cítím v něm sílu.
{18340}{18395}Jestli s ním chceš bojovat, bojuj v GO.
{18413}{18475}Můžu ho porazit v GO.
{18480}{18536}Není žádná záruka, že vyhraješ.
{18546}{18586}Je silný.
{18596}{18646}Takže co takhle...
{18650}{18670}co takhle já?!
{18680}{18695}Hikaru!
{18718}{18730}Je to tenhle!
{18732}{18750}Hikaru!
{19070}{19130}Musím přiznat, že máš odvahu.
{19150}{19180}Nejsou tam žádné kameny!
{19215}{19245}Kago, ty....!
{19255}{19345}Jak důvěřivé, že jsi na to skočil!
{19346}{19430}Hej, proč neskončíš s GO a nepřejdeš k Shougi?
{19432}{19480}Naučím tě všechno.
{19484}{19520}Fuck off!
{19521}{19608}Radši se nikdy nebudu učit Shougi než se učit od tebe!
{19609}{19629}Cože?!
{19630}{19655}Přestaňte, oba!
{19660}{19701}Vyhrál jsi proti Touyovi?!
{19701}{19755}Nejspíš jsi podváděl stejně jako teď!
{19760}{19830}To, nebo se Touya nesnažil.
{19840}{19920}Potom jsi pravděpodobně utekl k Shougi protože jsi nemohl zvládnout GO!
{19960}{20000}Tsutsui, pusť ho!
{20021}{20065}Ty si myslíš, že jsem loser?
{20085}{20140}Ukážu ti, jak silný jsem!!
{20185}{20255}Jestli prohraju, pokloním se ti jako králi, jak budeš chtít.
{20260}{20350}Ale jestli prohraješ, půjdeš skočit do ledově studeného bazénu!
{20350}{20375}Dobře!
{20405}{20420}Sai!
{20460}{20525}17 - 4 Pravý horní roh - komoku
{20610}{20665}Proč držíš svůj kámen takhle?
{20670}{20713}Na tom jak držím svůj kámen nezáleží!
{20715}{20740}15 - 4
{20760}{20810}Mluv si takhle až vyhraješ.
{20945}{21025}Jak mi může dítě jako on rozumnět?
{21035}{21055}Dítě jako je on...
{21140}{21200}Tetsuo.
{21188}{21236}Hej, Tetsuo!
{21240}{21295}Proč proti tomu chlapci pořád prohráváš?
{21315}{21345}Touya Akira,
{21365}{21480}Díky tomu jsi vždycky #2, není ti hanba? A to jsi o 2 roky starší.
{21485}{21525}Samozřejmě chci vyhrát...
{21547}{21570}Ale Akira Touya je...
{21580}{21645}Poraž ho dnes! Nenechám tě v domě než ho porazíš!
{21785}{21860}Není nic co můžu dělat. Silní jsou prostě silní.
{21875}{21955}O tom není pochyb, ty hraješ GO na úplně jiné úrovni.
{21955}{22145}Ty jsi nesporně špička, ale jednoho dne tě překonám a budu #1.
{22160}{22190}Připrav se na to.
{22200}{22300}Dobře, začněme.
{22270}{22345}Chceš abych prohrál?
{22370}{22445}Chceš..abych...prohrál?
{22545}{22575}Parchant..
{22590}{22626}Parchant....
{22635}{22660}Parchant....
{22725}{22746}Já...
{22760}{22808}bral jsem ho jako svého protivníka.
{22845}{22910}Ale on se o mě nestaral.
{22925}{23000}Jemu nezáleželo na tom, jestli proti mě vyhrál nebo ne!
{24350}{24450}Na konci hry jsem vyhrál o 1,5 moku s komi...
{24470}{24500}ten parchant...
{24595}{24720}Jakmile můj otec zjistil, že nemůžu být nejlepší dokud je tam on, vzdal to.
{24765}{24810}Ten parchant...
{25345}{25390}Ale...tenhle hoch...
{25414}{25450}Je opravdu dobrý...
{26030}{26050}No..
{26051}{26154}Ten kluk je docela dobrý.
{26575}{26630}Hej, to si děláš srandu.
{26631}{26630}On si se mnou hraje na desce.
{26840}{26870}11 - 15
{27000}{27025}14 - 16
{27082}{27105}Zábavné.
{27120}{27200}Tenhle kluk není zdaleka tak silný jako Touya Akira...
{27205}{27290}ale odpovídá na moje tahy velmi zábavnými tahy.
{27330}{27370}Není problém s ním vyhrát...
{27390}{27440}ale já se chci dál bavit...
{27990}{28080}Černý vypadá v nebezpečí... ale myslím, že to může zvládnout...
{28090}{28110}což znamená...
{28130}{28170}Je to vyrovnané...
{28180}{28220}Ne, černý vede.
{28282}{28310}9 - 16
{28340}{28355}Co, opravdu?
{28356}{28470}Jeho obličej byl celý rudý, a zakřičel "Nehraj si se mnou!"|Akari!
{28473}{28505}Konečně se ukázala...
{28500}{28540}Pospěš a táhni!
{28545}{28565}Ah, promiň.
{28591}{28620}Hikaru! To není ono!
{28730}{28755}P..počkej!
{28760}{28785}Počkej?
{28785}{28810}To si děláš srandu.
{28830}{28880}Ah ne, umřelo to...
{28910}{28940}Není jiná možnost...
{28955}{28980}12 - 15
{29052}{29130}Ten poslední tah tě zabil!
{29295}{29310}Cože?!
{29315}{29340}Tolik?
{29445}{29510}Možná čas na rezignaci?
{29550}{29600}A ledově studený bazén tě očekává...
{30706}{30790}Z angličtiny: Anakreon
{31825}{31887}Go! Go! Igo!
{31889}{31920}Zajímalo by mě co je tohle.
{31930}{31985}Pravděpodobně něco jako rýžová koule
{32005}{32075}Dobře, pojďme hrát dneska s tímhle.
{32085}{32100}To je malé.
{32105}{32230}Ano, to je deska 6x6. Ale je to dost pro začátečníky.
{32231}{32281}Kdo první získá tři kameny vyhrál, ok?
{32281}{32291}Okay
{32305}{32330}Takže začněme|/Začátek Zajímací hry/
{32330}{32365}Hodně štěstí!|/Začátek Zajímací hry/
{32365}{32395}Hodně štěstí!|/Svojí 6x6 desku můžete udělat snadno nakreslením čar na papír./
{32395}{32460} |/Svojí 6x6 desku můžete udělat snadno nakreslením čar na papír./
{32460}{32530}Mai vzala kameny!|/Svojí 6x6 desku můžete udělat snadno nakreslením čar na papír./
{32547}{32560}Co udělá on?
{32560}{32625}|/Go kameny můžete získat z víček PET lahví./
{32625}{32720}To byl dobrý tah.|/Go kameny můžete získat z víček PET lahví./
{32720}{32755}Ó jo!
{32758}{32845}Mai vítězí. Gratuluji.|/Mai vítězí!/
{32845}{32960}Teď poděkujte soupeři za hru.|/Přivítejte soupeře na začátku hry a poděkujte mu na konci./
{33000}{33070}Sai, říkal jsi že je to v pořádku!
{33070}{33170}Tsutsui, členové na týmový turnaj byli rozhodnuti.
{33175}{33222}Myslím, že teď rozumím...
{33240}{33323}proč jsem byl přivolán k Hikarovi.
{33575}{33638}Jakmile položíš kámen, nemůžeš s ním hýbat,
{33638}{33676}taková je váha tahu.