{1}{72}DIV3 512x384 23.976fps 176.6 MB
{194}{274}Kdo je to?!
{286}{346}To není nejlepší tah...
{346}{426}ani ten nejsilnější...
{973}{1053}Do češtiny přeložil: Anakreon
{1094}{1214}Poznámka: v dialogách se často vyskytují názvy konkrétních tahů v Go, termíny nejsou přeložené a často jsou bez vyjasnění.|viz. Pravidla Go
{2520}{2600}První zápas:|Věčný protivník.
{2988}{3050}Poběž Akari! Dům mého dědy je támhle!
{3050}{3130}Věděla jsem, že jsme měli jít přímo domů!
{3146}{3180}Dědo?!
{3180}{3208}Dědo?!
{3208}{3248}Jdeme dovnitř!
{3248}{3328}Je to opravdu v pořádku?
{3378}{3456}Nic z tohohle nevypadá opravdu cenně.
{3456}{3506}Hikaru!|Pojďme pryč!
{3506}{3586}Je to tu děsivé!
{3637}{3698}Jsi si jistý, že to můžeš udělat?
{3698}{3788}Nemám na výběr, dostal jsem jen 8 bodů v minulém testu z historie.
{3802}{3878}A moji rodiče mi přestali dávat kapesné.
{3878}{3958}Hej, co tohle?
{4110}{4190}To znám! To je deska na "piškvorky" ne?
{4194}{4252}Vypadá opravdu staře.
{4252}{4324}Možná ji děda používal když byl mladý.
{4324}{4394}Možná bych za ni mohl něco dostat.
{4394}{4432}Jsi si jistý, že je to v pořádku?
{4432}{4460}Jasně, v pohodě.
{4460}{4512}Jsem si jistý, že děda ani neví, že tu ta deska je.
{4512}{4592}A když setřu ten prach...
{4648}{4718}Ale proč ta skvrna nejde dolů?
{4718}{4740}Co?
{4740}{4780}Nejsou tam žádné skvrny...
{4780}{4828}...je čistá.
{4828}{4880}Tady je skvrna.
{4880}{4952}Kde?|Tady!
{4952}{4982}Nic tam není...
{4982}{5016}...tam kde ukazuješ!
{5016}{5052}Přeci je tady!
{5052}{5082}Vidíš ji?
{5082}{5124}Vždyť říkám, že jí vidím...
{5124}{5204}Slyšíš můj hlas?!
{5220}{5296}Slyšíš ho, že ano?
{5296}{5376}Není tu žádná skvrna...
{5394}{5434}Kdo je to?!
{5434}{5510}Hikaru! Přestaň s těmi žerty!
{5510}{5548}Našel jsem někoho.
{5548}{5576}Konečně jsem našel někoho!
{5576}{5604}To jsi ty dědo?
{5604}{5642}Ukaž se...
{5642}{5722}Já jdu domů!
{5780}{5860}Bohové přede mnou, děkuji vám.
{5888}{5968}Já...
{6020}{6090}Já se teď, ještě jednou...
{6090}{6170}...vrátím do žijícího světa.
{6448}{6475}Co se děje?
{6475}{6520}Hikaru!
{6520}{6600}Dědo! Něco se mu stalo!
{6620}{6657}Kdo jsi?
{6657}{6718}Sai Fujiwarano.
{6718}{6754}Sai? |Co jsi zač?
{6754}{6834}Učil jsem císaře hrát GO v hlavním městě za doby Heian.
{6898}{6978}Den za dnem jsem hrál GO a byl jsem velmi šťastný.
{7096}{7176}Avšak císař měl ještě jednoho učitele GO.
{7234}{7314}Jednoho dne řekl císaři...
{7320}{7362}...že jen jeden učitel stačí.
{7362}{7442}Měli jsme hrát zápas, vítěz měl být učitelem.
{7462}{7532}A hráli jste ne?
{7532}{7579}Kdo vyhrál?
{7579}{7650}Průběh hry byl vyrovnaný.
{7650}{7769}Bylo to opravdu neuvěřitelné, že pod zraky tolika mužů jsem byl jediný kdo si toho všiml.
{7818}{7898}Bílý kámen byl přimíchaný v jeho misce.
{7912}{7986}Všiml si šance,
{7986}{8043}a položil ho do své agehamy!|(Agehama je miska zajatých kamenů)
{8043}{8090}Takže podváděl?
{8090}{8168}Když jsem se chystal o tom povědět...
{8168}{8238}Ty, Ty jsi právě...
{8238}{8290}TY!
{8290}{8410}Položil jsi přimíchaný kámen ze své misky do agehamy! Že?!
{8422}{8448}Cože?
{8448}{8494}To je to co jsi před chvílí udělal ty!
{8494}{8562}Jaká ubohá výmluva!
{8562}{8682}Využil jsi momentu, kdy byli všichni soustředěni na desku k položení dalšího kamenu do své agehamy!
{8724}{8774}To je lež!
{8774}{8854}Mlčte.
{8856}{8976}Ani si nepřeju pomyslet, že takovéto opovrženíhodné jednání se objevilo přede mnou.
{8998}{9078}Pokračujte ve hře.
{9100}{9176}Prohrál jsem...
{9176}{9296}Ještě s podezřením z podvodu jsem byl vyhoštěn z města.
{9348}{9428}Bez svého živobytí jsem neměl důvod pro život.
{9444}{9512}O dva dny později...
{9512}{9592}jsem se utopil.
{9720}{9840}Pořád jsem chtěl hrát GO, a chtěl jsem hrát ještě mnohem víc.
{9876}{9961}Neschopen nalézt útěchy, má duše sedla na GO desku,
{9962}{10042}a po dlouhé době,
{10054}{10134}jsem uslyšel hlas chlapce na ostrově u moře Seto.
{10250}{10330}Jmenoval se Tora-jirou.
{10354}{10434}Jestli vidíš slzy mého zármutku...
{10520}{10600}dovol mi prosím obydlet kus tvého srdce.
{10628}{10696}Totajirou se přejmenoval na Shuusaku...
{10696}{10752}a převzal místo svého mistra ve věku 20 let.
{10752}{10832}Ve věku 14 let převzal jméno Honinbou Shuusaku
{10862}{10930}Honinbou... Shuusaku?
{10930}{11050}Avšak, onemocněl z důvodu moru a jedné noci v mladém věku 34 let...
{11150}{11230}Krev na GO desce musela být jeho.
{11248}{11328}A ty jsi posedl mně protože chceš hrát více GO?
{11398}{11452}Ano.
{11452}{11572}Protože jsem stále ještě nedosáhl Ruky Boha!
{11900}{11930}Hikaru!
{11930}{11992}Slyšel jsem, že jsi jel sanitkou?!
{11992}{12044}Co? Jo...
{12044}{12124}Hikaru?
{12168}{12196}Hikaru?
{12196}{12268}Jsi opravdu v pořádku?|Co se včera stalo?
{12268}{12346}Sám si to dobře nepamatuju,
{12346}{12400}když jsem se vzpamatoval, byl už dnešek.
{12400}{12480}Prosím pošlete testy dozadu.
{12480}{12560}Dobře, můžete začít.
{12618}{12692}Oh, problém s historií, chápu...
{12692}{12770}Ty!
{12770}{12816}Co se stalo?
{12816}{12846}Eh, tedy...
{12846}{12914}Omlouvám se...
{12914}{12959}Sedni si a pokračuj v testu.
{12959}{13013}Ano madam.
{13013}{13066}Ta věc co se mi stala včera nebyl sen!
{13066}{13082}Ne, ne byl.
{13082}{13134}A jak že se jmenuješ?
{13134}{13156}Sai.
{13156}{13198}Oh, Sai?
{13198}{13234}Opravdu máš tak moc rád GO?
{13234}{13250}Ano!
{13250}{13277}A pořád chceš hrát GO?
{13277}{13298}Ano!
{13298}{13378}Oh, promiň, nemám v úmyslu hrát go.
{13502}{13530}Hikaru!
{13530}{13610}Shindou!
{13644}{13678}Co jsi to udělal?!
{13678}{13758}Nic jsem neudělal! Opravdu!
{13766}{13795}Hikaru, jsi v pořádku?
{13795}{13860}Shindou!
{13860}{13890}Shindou, jsi v pořádku?
{13890}{13916}Chceš jít k doktorce?
{13916}{13962}Ne, už je to dobré.
{13962}{14023}Zármutek, který jsem pocítil z pomyšlení, že nemůžu hrát GO,
{14024}{14077}prostě přešel do tvého podvědomí...
{14077}{14198}Tvá láska pro hru se udržela po tisíc let? Působivé.
{14218}{14298}Ale ja mám vlastní plány na život.
{14359}{14448}Jsi si jistý, že nemůžeš přejít do někoho jiného než mě?
{14452}{14532}Pravděpodobně ne...
{14604}{14688}Dobře, jestli mám od teď hrát, tak se s tím nějak smířím.
{14688}{14710}Co?
{14710}{14790}ALE: moje mysl je jen moje.
{14800}{14863}A ještě - nemluv na mě pokud tě neoslovím.
{14863}{14943}OK!
{15030}{15110}Kdo že to byl?
{15148}{15190}Zbývá 10 minut.
{15190}{15310}Jestli jste již hotovi, zkontrolujte si znovu správné odpovědi.
{15314}{15345}To neudělám.
{15345}{15425}Sai, nevíš něco o revoluci Tempou?
{15426}{15452}Revoluci Tempou?
{15452}{15528}Té kterou začal Roujyuu no Mizuno?
{15528}{15577}Tak, tak! To je ona.
{15577}{15657}Jak milá vzpomínka, jednou jsme hráli GO v zámku.
{15673}{15718}Víš něco o Perrym?
{15718}{15748}Perry?
{15748}{15813}Perry?! Víš? Vedl tu pár válečných lodí?
{15813}{15859}Á! Komandér Perry!
{15859}{15882}Jo, ten!
{15882}{15920}Kam ten Perry přišel?
{15920}{15987}Do Uragy. Byl tam obrovský nepokoj kvůli tomu incidentu.
{15988}{16048}Uraga...|Sai.
{16048}{16078}Ano?
{16078}{16123}Někdy jsi i užitečný.
{16123}{16190}Shindou, proč mluvíš pro sebe?
{16190}{16224}Skončil jsi s testem?
{16224}{16304}Skoro.|Hodně štěstí.
{16364}{16444}Prošla mým tělem a ani se neomluvila!
{16444}{16500}Jak sprosté!
{16500}{16576}Hikaru, jsou všechny ženy z této doby...
{16576}{16656}OK, OK, jen nekřič tak hlasitě v mé hlavě.
{16678}{16798}Vezmu tě někam kde můžeme hrát GO hned jak to tu skončí.
{16896}{16976}Je tu tolik lidí.
{16978}{17038}Koneckonců je to Tokyo...
{17038}{17114}A, a... kam jdeme hrát GO?
{17114}{17154}Do salonu GO.
{17154}{17214}Můj děda tam chodí pořád.
{17214}{17304}Je to místo kam všichni staří přátelé ze sousedství chodí hrát GO.
{17306}{17396}Nezáleží jaká je doba, vždycky se najdou milovníci GO!
{17410}{17490}Ahoj.|Pojď dovnitř.
{17546}{17610}Je tu plno starých lidí.
{17610}{17672}Jsi tady poprvé?
{17672}{17742}Ano, poprvé.
{17742}{17774}Může si tu někdo zahrát?
{17774}{17802}Samozřejmě.
{17802}{17862}Sem napiš svoje jméno.
{17862}{17914}Jak jsi silný?
{17914}{17988}Silný? Já... nejsem si jistý,|Cože?
{17988}{18100}Ještě jsem s nikým nehrál, ale jsem si dost jistý, že jsem dost silný.
{18100}{18178}Oh! Támhle je kluk! Můžu si s ním zahrát?
{18178}{18258}Ano... ale on je...
{18424}{18474}Hledáš někoho na hru?
{18474}{18490}Ano.
{18490}{18538}Dobře, zahraju si s tebou.
{18538}{18588}Ale on je...
{18588}{18644}Pojďmě dozadu.|Jistě!
{18644}{18672}Počkejte chvilku.
{18672}{18702}Za dítě to je 500 yenů.
{18702}{18752}Cože?! Musím platit?!
{18752}{18832}Je tu poprvé, můžete mu to odpustit?
{18856}{18936}Jestli je to pro tebe, Akiro!
{19084}{19146}Já jsem Akira Touya, jak se jmenuješ ty?
{19146}{19198}Shindou Hikaru, 6. třída
{19198}{19242}Já jsem také v 6.třídě!
{19242}{19322}To musí být nudné hrát s tak starými lidmi!
{19328}{19364}Jak jsi silný?
{19364}{19426}Ehm... nejsem si jistý.
{19426}{19506}Myslím, že jsem dost silný.
{19512}{19576}Nejsi si jistý, ale myslíš, že jsi silný?
{19576}{19656}Tak proč si nepoložíš 4 nebo 5 kamenů handicapu?
{19700}{19758}Handicap?
{19758}{19838}Nepotřebuju nic takového! Jsme přeci stejně staří.
{19838}{19896}Bez handicapu proti Touyovi Akirovi?!
{19896}{19956}To je šílené!
{19956}{20006}Ok. Jdi první.
{20006}{20086}Možná budu hrát trochu pomalu, omluv mne.
{20460}{20488}Sai...
{20488}{20558}jsi tak šťastný?
{20558}{20638}Bylo to více než sto let...
{20732}{20812}Hikaru, začnu.|OK!
{20822}{20896}17-4 horní pravý roh - komoku!
{20896}{20976}17...|1,2,3,4...
{21018}{21098}To je způsob, jakým začátečník drží kameny...
{21256}{21336}16-17 dolní pravý roh - komoku!
{21394}{21474}Tady je to.
{21502}{21582}3-16
{21706}{21786}16-5
{21802}{21882}Kosumi?
{21912}{21992}14-4
{22494}{22544}Drží kameny jako začátečník,
{22544}{22600}ale hraje dobře.
{22600}{22660}Není divu, že tvrdil, že je silný.
{22660}{22708}Co se stalo? Je tvůj tah.
{22708}{22788}Ah, promiň.
{22964}{23044}Ale... jeho joseki je staré...
{23046}{23126}a někdy... zpomalí v divných místech...
{23182}{23262}14-11
{23606}{23686}On se nebrání mým útokům, ne...
{23688}{23768}to není jen to, on se jim lehce vyhýbá.
{24638}{24718}Ten bílý kámen je tvůj. Seber ho z desky.
{24762}{24842}Ten?|Ano.
{24986}{25066}19-15
{25118}{25170}Je to v pořádku? On vzal ten kámen.
{25170}{25250}18-14
{25264}{25308}Tenhle si můžu vzít, že?
{25308}{25388}Ano
{25422}{25462}Co se stalo?
{25462}{25582}Ta skupina bílých kamenů je mrtvá, tyto kameny budou na konci hry tvoje.
{25614}{25694}Tohle všechno?! Takže jsme prakticky vyhráli!
{25694}{25774}Ne. On není tak slabý.
{25922}{26002}Já jsem nevzal tu skupinu, to on ho odhodil.
{26084}{26148}Podívej se pozorně.
{26148}{26228}Tohle...
{26234}{26268}Stále mám šanci.
{26268}{26326}Ten blok vlevo nahoře byl velký,
{26326}{26406}Ale já kontroluju střed.
{26414}{26458}Bude v pořádku?
{26458}{26478}Pravděpodobně.
{26478}{26558}4-13
{26658}{26738}8-5
{26752}{26832}Tady je to.
{26845}{26880}Tohle...
{26880}{26960}Tohle není nejlepší tah...
{26986}{27066}ani ten nejsilnější.
{27088}{27168}On mě testuje, aby viděl jak zareaguji...
{27184}{27245}On měří moji sílu...
{27245}{27325}Z mnohem vyšší pozice...
{27386}{27452}Uvidíme se. |Děkuji!
{27452}{27500}Ah, už jsi dohrál.
{27500}{27524}Jo...
{27524}{27594}Myslím, že ještě nejsem připravený na zápas.
{27594}{27660}Zabralo to opravdu hodně času a jsem vyčerpaný.
{27660}{27711}Opravdu?
{27711}{27791}Oh ano! Brzy bude dětský GO turnaj.
{27828}{27884}Tady...
{27884}{27917}Můžeš se jít podívat?
{27917}{27962}Budu o tom přemýšlet.
{27962}{28030}Díky za dnešek!
{28030}{28105}Přijď zase!
{28105}{28194}Řekla bych, že to pro něj bylo o 50 let moc brzo jít proti Akirovi.
{28198}{28222}Cože?! Prohrál?!
{28222}{28262}Nemožné!
{28262}{28308}Akira prohrál?!
{28308}{28377}Ale Akira je stejně silný jako Pro!|
{28377}{28408}Dal jsi mu handicap, že ano?
{28408}{28432}Jaký handicap jsi mu dal?
{28432}{28461}Ten druhý kluk hrál za černého a začínal.
{28461}{28484}Jaký byl výsledek?
{28484}{28508}Prohrál o 2 moku.
{28508}{28573}Jestli je to jen o 2 moku, vyhrává po odebrání komi.
{28573}{28653}To není otázka 2 nebo 3 moku.
{28677}{28748}Počkej chvilku.
{28748}{28828}Akiro, opravdu jsi prohrál?
{28895}{28944}Neuvěřitelné...
{28944}{29024}ale on předtím ještě s nikým nehrál.
{29078}{29106}Nikdy...
{29106}{29150}nehrál...
{29150}{29189}s nikým...
{29189}{29254}...předtím...
{29254}{29317}Kdo to ksakru je?!
{29317}{29397}Oh, jsem unavený.
{29428}{29483}Jsi teď spokojený Sai?
{29483}{29520}Ano.
{29520}{29593}OK! Takže uděláme můj domácí úkol z historie hned jak se dosteneme domů!
{29594}{29650}Dobře!
{29650}{29676}Běžíme domů.
{29676}{29722}Dobře!
{29722}{29802}Do češtiny: Anakreon
{31945}{32000}Go! Go! Igo!
{32010}{32045}Já jsem Umezawa Yukari.
{32050}{32155}V tomto krátkém programu vám budeme jednoduchým způsobem vysvětlovat základní pojmy Igo.  
{32160}{32215}Mai a Yuuki mi budou asistovat. Hodně štěstí
{32218}{32280}Hodně štěstí Vám sensei
{32300}{32344}Jak se hraje GO?|/Věci nezbytné pro hraní GO/
{32380}{32437}Takže potřebné věci jsou GO deska..|*Věci nezbytné pro hraní GO*
{32445}{32475}a tyto GO kameny.|/GO kameny (černé a bílé)/
{32475}{32573}Tah uděláte položením těchto kamenů na desku.|/Táhnete položením GO kamenů na desku/
{32585}{32695}Dobře, vyzkoušejme si pokládání kamenů na desku|/Kam pokládat kameny?/
{32735}{32935}Kdyby to byla kterákoli jiná hra, pak jste pokládali kameny správě, ale v Igo musíte pokládat kámen na průsečíky čar.|/Položte kámen na průsečík, kde se střetají čáry./
{32946}{33075}Tento tah... a tento..to je shidou GO.. kdyby to byla jeho pravá síla..
{33105}{33207}ne, takové dítě neexistuje! Kdo přesně to je?!
{33453}{33511}Konečně jsem tě našel!
{33525}{33560}Shindou Hikaru!