{1}{1}23.976
{1}{20}DIV3 512x384 23.976fps 171.8 MB
{21}{99}Fujiwarano, hráč GO z doby Heian,
{111}{223}prošel časem a vrátil se do tohoto světa v mysli Shindoa Hikara,
{223}{301}aby dosáhl Ruky Boha.
{708}{786}Z angličtiny: Anakreon
{2515}{2585}Možná čas na rezignaci?
{2625}{2675}A ledově studený bazén tě očekává...
{2755}{2880}Pátý zápas:|Předpověď probuzení
{2900}{2950}Řekl jsem abys čekal!
{3010}{3035}Hikaru...
{3045}{3093}Jakmile položíš kámen, nemůžeš s ním hýbat.
{3105}{3150}Taková je váha tahu.
{3155}{3175}Ale..!
{3176}{3210}Uklidni se Hikaru.
{3215}{3285}To je v pořádku, pořád máme šanci na výhru.
{3290}{3365}Pojďme teď hrát jen pro jeho porážku.
{3415}{3475}Hej, neslyšeli jste teď Hikarův hlas?
{3477}{3515}He? Shindou?
{3685}{3720}Ah, už vím!
{3721}{3783}Říkala jsi, že jsi požádala někoho před námi.
{3784}{3825}Byl to Shindou, že?
{3830}{3884}Och!! Hehe!
{3885}{3910}Co?!
{3911}{3950}Nebuď naštvaná.
{3965}{4015}To takoyaki chutná skvěle!
{4016}{4055}Pojďme si dát další.
{4075}{4104}Kde že jsme to koupily?
{4110}{4140}Na druhé straně školního hřiště.
{4440}{4475}Je to výtečné.
{4485}{4535}Máš něco na tváři.
{4690}{4730}Nebyla ta show skvělá?
{4732}{4755}Jo
{4756}{4809}Ale ta scéna s boxem byla trochu nevhodná.
{4809}{4865}Hej, není to Shindou?
{4875}{4920}Hm.. takže přece přišel.
{4950}{4985}Dobře, my jdeme.
{4986}{5010}Jo!
{5020}{5039}Ale!
{5040}{5085}Pozdravuj ode mně Shindoa!
{5085}{5105}Hej!
{5255}{5295}Hikaru, ty jsi přece přišel?
{5300}{5375}Přišla jsem se Sayakou, protože jsi řekl, že nejdeš.
{5390}{5410}Co děláš?
{5419}{5440}Go?
{5443}{5460}Zase?
{5610}{5675}Včetně komi má bílý 68,5 moku...
{5682}{5725}Černý 68 moku...
{5755}{5810}Prohráli jsme o půl moku...
{5815}{5860}Byli jsme o krok kratší.
{5875}{5900}Sakra!
{5901}{5965}Sai, říkal jsi že to bude v pořádku!
{5968}{6025}Dělal jsem co jsem mohl!
{6040}{6080}Blbče! Je to všechno tvoje chyba!
{6085}{6150}Neee... ledový bazén!
{6215}{6295}Prohrál z té situace jen o půl moku...
{6315}{6365}Ne... neuvěřitelné...
{6375}{6415}ten neuvěřitelný hon...
{6420}{6525}po té hloupé chybě, kterou by neudělal ani Tsutsui...
{6526}{6565}Co jsi tím myslel!
{6573}{6590}Tsutsui...
{6620}{6650}sundej si uniformu.
{6690}{6719}Cožee?! Není on ten kdo jde do bazénu?
{6720}{6765}Prostě si to sundej!
{6770}{6840}Aaaaaa!! Ledový bazén!!
{6935}{6970}Proč jsi to udělal?!
{6980}{7075}Tsutsui, máme tým na GO turnaj.
{7100}{7171}Já, ty a to dítě!
{7368}{7403}To nemůžeme!
{7405}{7433}Prohrál jsi...
{7435}{7480}takže jen dělej co ti řeknu.
{7510}{7555}...kdy je ten turnaj?
{7565}{7620}Tuhle neděli od 2.
{7625}{7645}Kde to je?
{7648}{7995}Škola Kaiou.
{8240}{8275}Páni!
{8285}{8335}Takže tohle je škola Kaiou.
{8345}{8365}Takže...
{8370}{8440}u vchodu se přezout...
{8441}{8510}a je to druhá místnost ve čtvrtém patře hlavní budovy...
{8511}{8540}Asi se ztratím...
{8550}{8685}Dobře, nikdy nebudu moct přijít do jedné z nejlepších národních škol bez něčeho takového.
{8780}{8825}Páni, trénují i v v neděli.
{8920}{8960}Oh.
{8982}{9000}Tady je to.
{9110}{9150}Vypadá to, že jsem tu příliš brzo.
{9151}{9202}Nevidím tu Tsutsueho.
{9230}{9305}Poslouchejte, nemyslete si, že můžete hrát lépe než hrajete normálně.
{9310}{9415}Pokud potkáte soupeře lepšího než vy, už se očekává že prohrajete.
{9420}{9470}Pojďme si teda zahrát.
{9480}{9545}Imai, zahraj si s Okatou. Takeshito, ty se mnou.
{9560}{9645}Vypadá to, že škola Kaiou i opět tento rok výjimečná.
{9646}{9710}Ale zajímá mě, kdo bude druhý.
{9715}{9775}Na jakém turnaji jsme dnes?
{9785}{9830}Je to týmový turnaj pro Junior High školy.
{9832}{9860}Ooh!
{9870}{9950}3 lidé hrají za tým, a tým se dvěmi výhrami je vítězný.
{9970}{10022}8 chlapeckých týmů a 6 dívčích,
{10023}{10063}ne příliš moc.
{10065}{10101}Kde je Haze...
{10110}{10140}Á, tady je.
{10170}{10260}Jak vzrušující, už si chci zahrát...
{10261}{10310}Á, mé srdce buší.
{10330}{10380}Sai, dnes nemůsíš nic dělat.
{10405}{10435}Já budu hrát.
{10440}{10460}Hikaru!
{10465}{10501}A... Ale!
{10505}{10570}Už jsem se něco naučil...
{10571}{10625}a já opravdu chci hrát sám.
{10650}{10693}Ale, minulou noc!
{10690}{10790}Řekl jsi "ó, zítra je turnaj" a nechal mě udělat tvůj úkol z historie!
{10805}{10900}Ale neřekl jsem nic o tom, že tě nechám hrát.
{10920}{10965}Hikaru! Jsi sobecký!
{10967}{11040}Prohraješ tak rychle!
{11044}{11095}Nezáleží, jestli prohraju.
{11105}{11165}Jsem tu jen do počtu.
{11167}{11205}Vidíš, už je tu pár lidí.
{11210}{11250}Ehh?
{11260}{11335}To je Takadův starší bratr!
{11345}{11370}Ó ne!
{11380}{11425}Proč si taky trochu nezahrajeme?
{11426}{11441}Jasně.
{11460}{11520}Ale Klub Kaiou je úžasný...
{11530}{11600}Slyšel jsem, že tahle hala je jejich klubovna.
{11601}{11656}Oni jsou jen na jiném měřítku.
{11660}{11722}/Slyšel jsem, že náš GO klub je nejlepší./|Slyšel jsem, že mají v klubu kolem 50 lidí. 
{11725}{11760}Nejspíš je to dobré vidět.
{11820}{11860}Asi tu budu jen sedět.
{12012}{12050}Díval jsi se na párování?
{12051}{12130}Jo, hrajeme s Kaiou až poslední zápas.
{12140}{12204}Když budeme dobří, můžeme být druzí.
{12205}{12220}Ah?
{13480}{13505}Oh!
{13540}{13570}Promiň, promiň.
{13570}{13620}Co děláš?!
{13622}{13660}Hmm...
{13706}{13730}Bylo to takhle že?
{13731}{13762}Ne, to nebylo!
{13765}{13800}O čem to mluvíš!
{13801}{13810}Bylo to takhle!
{13825}{13875}Ne, nebylo to tam!
{13876}{13910}Chcete, abych to udělal?
{13911}{13925}Eh?
{13940}{13975}Co to děláš?!
{13977}{13995}Hikaru?
{14035}{14050}Ty jsi zahrál sem..
{14067}{14130}a potom... tady.
{14143}{14181}potom...tady a..
{14960}{15010}hmm...potom to bylo..
{15010}{15045}Ah! Tady!
{15046}{15075}a potom...
{15235}{15295}a část, do které jste se právě dostali...
{15335}{15370}takhle a...
{15390}{15415}Hmm....
{15545}{15575}a tady jste skončili.
{15710}{15748}A co s tím?!
{15748}{15795}To už víme!
{15800}{15896}Kdokoli může přehrát hru od prvního tahu, pokud je dobrý.
{15900}{15920}Jdi pryč!
{15922}{15950}O.omlouvám se.
{16000}{16065}Sakra, kdyby se kámen trochu pohnul, mohl jsem vyhrávat.
{16070}{16140}Dobře, pokračujme. Kdo byl na tahu?
{16210}{16240}Hej..
{16255}{16295}opravdu to umíš udělat?
{16375}{16400}Sakra...
{16400}{16445}Ze které školy je?
{16465}{16485}Cože?!
{16490}{16525}Je tu někdo koho znáš?!
{16555}{16610}Takže nemůžeme vystoupit.
{16615}{16639}Jo.
{16640}{16680}Pokud na to přijdou, vypořádáme se s tím, až se to stane.
{16700}{16720}Pravda.
{16730}{16835}Pokud umíš hrát hru, přehrání je potom jednoduché.
{16845}{16865}Ale...
{16880}{16940}Hikaru začal před pár dny.
{16970}{17035}Můžu spočítat kolikrát se dotknul kamenů...
{17070}{17115}Myslím, že teď rozumím...
{17140}{17222}proč jsem byl přivolán k Hikarovi.
{17260}{17275}Je čas.
{17295}{17355}Takže teď začneme první zápas.
{17470}{17490}Hmm...
{17491}{17520}Dívčí první zápas...
{17530}{17580}Škola Kaiou proti škole Iwana u stolu A.
{17610}{17685}Škola Ayu proti škole Iwana u stolu B.
{17697}{17735}Chlapecké týmy...
{17736}{17810}Škola Kaiou proti škole Hamachi u stolu C.
{17825}{17890}U stolu D je škola Tai proti škole Iwana.
{17900}{17970}U stolu E je škola Ayu proti škole Sawara.
{17980}{18073}a..škola Haze proti škole Kawahagi u stolu F.
{18280}{18330}Jsou všichni na svých místech?
{18390}{18435}No jo, nemůžu být nápadný.
{18450}{18460}Heh?
{18555}{18600}Co..co to děláš?!
{18610}{18645}Hra ještě nezačala!
{18655}{18680}To nemůžeš!
{18700}{18760}Zápasové hodiny se rozběhnou po zmáčknutí.
{18775}{18810}Zápasové hodiny?
{18820}{18869}45 minut na osobu.
{18870}{18925}Zmáčkni to po tom, co uděláš tah...
{18945}{18960}Rozumíš?
{18995}{19091}Hej, nemáš se náhodou chovat nenápadně?
{19145}{19165}Sai!
{19175}{19210}Proč jsi nic neřekl?!
{19215}{19280}Mohl jsi mě říct o hodinách.
{19285}{19363}Takové věci za Shuusakovy doby neexistovaly.
{19390}{19540}a není divné, že se ptáš po tom, co jsi se vychloubal že dneska budeš hrát ty?
{19540}{19580}Á ty blbče.
{19585}{19610}Tak dobře!
{19610}{19655}Dneska můžeš zůstat vzadu!
{19680}{19720}Dělej si co chceš, Hikaru.
{19765}{19820}Jsi z klubu Shougi?
{19825}{19880}Proč je někdo z Shougi klubu tady?
{19910}{19950}Neměli jste dost členů?
{19975}{20020}Neměli jste ani 3 lidi?
{20022}{20070}Zmlkni a udělej nigiri!
{20085}{20170}Nigiri? Jsi si jistý, že nechceš použít furigomu?|(furigoma = kostka kterou se rozhoduje kdo začne v Shougi)
{20190}{20225}Máš štěstí, že hrajeme GO.
{20240}{20320}V Shougi by tvůj král zemřel v 5 minutách,
{20321}{20360}ale v GO mi to zabere 10 minut.
{20370}{20420}Budeš žít o 5 minut déle.
{20425}{20440}Sakra.
{20445}{20530}Jak můžeš říct něco takového bez toho, abys věděl jak jsem silný!
{20535}{20600}Rozdíl mezi loserem a opravdovým mužem se pozná snadno.
{20605}{20670}Někdo kdo rýpá do druhých je viditelně loser.
{20695}{20735}Hej vy tam, začněte už.
{20868}{20885}2...
{20895}{20910}4...
{20920}{20935}6...
{20950}{20961}8...
{20980}{20990}9...
{21010}{21040}Jsem bílý.
{21050}{21065}Bílý...
{21085}{21111}takže já jsem černý,
{21123}{21165}a Shindou je bílý.
{21171}{21187}Bílý.
{21290}{21330}Teď, prosím začněte.
{21345}{21390}Hodně štěstí.
{22155}{22195}Tsutsui! Co to děláš?!
{22225}{22255}Jsi imbecil?!
{22260}{22295}Hraješ při čtení knihy?!
{22297}{22346}Není to proti pravidlům...
{22340}{22415}Jsi slabý protože jsi závislý na takových věcech!
{22420}{22535}Pokud soupeř zahraje jinam než Joseki, pak je kniha zbytečná, nechápeš?
{22536}{22633}Jsem si toho více než vědom, ale bez knihy ztrácím sebevědomí...
{22630}{22670}Vy tam, ticho!
{22672}{22724}Prosím! Nevystupuj!
{22755}{22780}To by bylo!
{22790}{22815}Idioti.
{23075}{23130}Hej, zapomněls zmáčknout hodiny.
{23200}{23240}Jsem milý ne?
{23285}{23305}Hmmm...
{23325}{23355}Takový hrozný klub.
{23360}{23417}Kluk, který neví co jsou zápasové hodiny...
{23420}{23480}a idiot s otevřenou knihou s Joseki.
{23490}{23535}A chlapík ze Shougi klubu na doplnění počtu.
{23570}{23615}První zápas bude snadná výhra.
{23945}{23978}To je tak skvělé.
{23979}{24015}Já chci hrát taky...
{24020}{24100}Já chci taky hrát Hikaru! Hikaru!
{24140}{24170}Já tě neslyším!
{24260}{24295}Já.. vzdávám se.
{24310}{24340}Okey! 10 minut.
{24455}{24480}Nenechte se rozptýlit.
{24483}{24500}Sensei...
{24501}{24570}To je v pořádku. Strana se dvěma výhrama vyhrává.
{24580}{24620}Vy dva můžete vyhrát.
{24635}{24710}Je mi líto Moriyamy, ale jeho soupeř byl příliš silný.
{24755}{24790}Dobře...
{24800}{24860}Podívejme se jak silný je tenhle chlapík.
{24955}{25030}Co je to?! To je hrozné!
{25031}{25068}To je...
{25090}{25140}Tohle je politování hodná podívaná...
{25155}{25215}Byl ten šílený hon se mnou jen náhoda? 
{25218}{25260}To jsem byl já! Já!
{25370}{25420}Hej ty! Snažíš se vůbec?!
{25430}{25445}Jo.
{25455}{25485}Snažím se.
{25485}{25545}Tohle není tvá pravá síla!
{25546}{25585}Nebo se tu jen bavíš?
{25590}{25612}Já hraju.
{25615}{25635}Cože?!
{25660}{25678}Protože...
{25715}{25750}Podívej...
{25790}{25855}Na desce je 9 kamenů.
{25875}{25925}Tohle je vesmír!
{26035}{26145}A já na něj pokládám kameny, jeden za druhým.
{26210}{26290}Jako kdybych zvyšoval počet hvězd po jedné...
{26325}{26405}Já tvořím vesmír!
{26605}{26655}Je to jako kdybych byl Bohem...
{26690}{26760}Já se stanu Bohem!
{26785}{26825}Na této Go desce!
{28335}{28365}Hej, hrajeme pořád?
{28395}{28450}Já chci pokračovat.
{28460}{28483}Je to v pořádku?
{28475}{28565}No co, výhra a prohra je rozhodnutá.
{28575}{28610}Nemá smysl pokračovat ve hře.
{28627}{28745}Byla to jen náhoda, že Hikaru přehrál tu dřívější hru?
{28760}{28875}A já jsem myslel, že jsem v Hikarovi zahlédl génia na úrovni Touyi Akiry.
{28930}{28970}Teď je to jedna výhra a jedna prohra...
{28990}{29030}Tsutsui je naše poslední naděje.
{29682}{29778}Z angličtiny: Anakreon
{31830}{31885}Go!Go!Igo!
{31940}{31990}Pojďme se dnes naučit 2 důležité věci.
{32015}{32060}1 - Zakázané tahy.
{32065}{32130}Je zakázané, aby bílý hrál sem při takovémto postavení kamenů.|/Nemůžete hrát na místo, kde váš kámen bude sebrán./
{32130}{32200}Stejně by byl černým sebrán.|/Nemůžete hrát na místo, kde váš kámen bude sebrán./
{32200}{32245}Ale, je tady výjimka. | 2- Vyjímky k zakázaným tahům.
{32245}{32270}A to je, když se stane tohle.
{32270}{32320}A to je, když se stane tohle.|/Když tahem tam zajmete soupeřovy kameny, pak tam můžete táhnout./
{32320}{32398}Pokud bílý táhne sem, pak obklíčí tyto černé kameny.|/Když tahem tam zajmete soupeřovy kameny, pak tam můžete táhnout./
{32398}{32464}V takové situaci tam táhnout může.|/Když tahem tam zajmete soupeřovy kameny, pak tam můžete táhnout./
{32465}{32500}Vyzkoušejme to!
{32631}{32705}Ó, Yuuki, zlepšil ses!
{32713}{32780}Okay, je to 1 na 1. Co se stane.
{32845}{32910}Ach ne, už je tady ko!
{32910}{32922}Co se stalo sensei?
{32922}{32999}Co se stalo sensei? | Co se stalo učitelce Yukari...?!