{1}{1}23.976
{1}{20}DIV3 640x480 23.976fps 176.0 MB
{21}{99}Fujiwarano Sai, hráč GO z doby Heian,
{111}{223}prošel časem a vrátil se do tohoto světa v mysli Shindoa Hikara,
{223}{301}aby dosáhl Ruky Boha.
{708}{786}Z angličtiny: Anakreon
{2465}{2545}Rozdíl 12 a půl moku s komi.
{2545}{2590}Vyhrávám.
{2685}{2805}Dvanáctý zápas:|Jsi hráč na třetí desce
{2890}{2940}Přišel jsem sem přesně jak jsi mě požádal.
{2941}{2975}Teď mi dej 10000 yenů.
{2990}{3040}Ne dokud nevstoupíš do GO klubu.
{3085}{3115}Vstoupíš, že?
{3160}{3210}Jo, vstoupím do klubu,
{3220}{3305}Stejně nemůžu jít zpátky do toho GO salonu.
{3435}{3475}Dej mi zpátky mých 20 yenů!
{3500}{3520}Jistě.
{3550}{3585}Pojďme si zahrát!
{3825}{3867}Bez sázení.
{3867}{3915}Jsme přeci GO klub.
{3920}{3950}Můžu mít bílé?
{3970}{4005}Je mi to jedno.
{4020}{4065}Bez podvádění, ok Mitani?
{4075}{4110}Možná.
{4114}{4145}Mitani!
{4205}{4225}Tsutsui!
{4250}{4305}Mitani řekl, že se přidá do GO klubu
{4310}{4375}a že už nebude podvádět.
{4435}{4460}Co?
{4470}{4550}Jsi pořád naštvaný z toho, že jsem tě nechal udělat dva tahy za sebou?
{4565}{4635}Je tvoje chyba, že jsi tak hloupý a chytil ses na to.
{4680}{4720}Slyšel jsem od Shindoua.
{4725}{4790}Podváděl jsi v Seichi?
{4920}{4960}To není všechno.
{4970}{5090}Pohyboval jsem kameny, nebo jsem je schoval do kapsy a použil při Seichi.
{5100}{5135}Já neprohrávám.
{5165}{5237}Jsou to jen slova! On říká takové věci.
{5237}{5275}Takový už je.
{5304}{5325}Hikaru!
{5355}{5390}Á, Mitani.
{5405}{5445}Co je?
{5455}{5545}Udělala jsem dnes při hodině sušenky.
{5555}{5590}Tady nějaké pro tebe Tsutsui.
{5620}{5685}Můžu dostat taky? Mám hlad.
{5695}{5735}Jistě, když přestaneš podvádět.
{5770}{5845}Řekl jsi to všem?
{5860}{5920}Ale je to pravda, že?
{5980}{6050}Řekl jsem to jen Tsutsuimu a Akari!
{6050}{6080}Nebudeš, že ne?
{6085}{6120}Nebudu, nebudu.
{6130}{6155}Tady Hikaru.
{6155}{6174}Díky!
{6174}{6260}Skvělé, teď můžeme jít na turnaj.
{6290}{6320}Turnaj?
{6330}{6370}Tam nejdu.
{6370}{6430}C-Cože!?
{6430}{6485}Přitáhl jsem tě sem kvůli turnaji!
{6485}{6510}To není moje věc.
{6510}{6560}Jsi v našem týmu!
{6560}{6600}Bylo to rozhodnuto.
{6602}{6620}Ne.
{6621}{6660}Žádné "ne"!
{6670}{6705}Tsutsui...
{6705}{6755}řekni něco!
{6773}{6850}Nemusíme ho nutit tam jít, když nechce.
{6895}{6930}Ale...
{6940}{7010}Teď bude nemožné najít někoho jiného.
{7010}{7075}Do turnaje už nezbývá moc času.
{7085}{7150}Co bude s naším cílem porazit Kaiou?!
{7160}{7230}I když se přidá, stejně je nemůžeme porazit.
{7240}{7300}Kaiou jsou opravdu silní.
{7340}{7395}Je to jen klub Jr. High, že?
{7420}{7510}Proti Kaiou nemáš šanci!
{7540}{7640}Ale Tsutsui, ty jsi v minulém turnaji proti Kaiou vyhrál.
{7650}{7730}Ale jen proto, že udělal chybu!
{7758}{7785}Cože?
{7795}{7875}Já proti takovému chlapíkovi nemám šanci?
{7905}{7950}Chcete, abych je pro vás porazil?
{7965}{8000}Mitani...
{8015}{8060}Půjdeš na turnaj?!
{8115}{8165}Porazím je před vašima očima.
{8200}{8250}Nevíš, jak jsou silní.
{8260}{8285}Jak zábavné.
{8290}{8325}Říkal jsem
{8365}{8400}Já neprohrávám.
{8465}{8470}Hej,
{8500}{8530}začněme.
{8620}{8645}To nemůže být pravda!
{8645}{8710}Plánuje podvádět proti Kaiou?
{8720}{8760}Kaiou by si mohli všimnout!
{8885}{8935}Pokud se to stane...
{8945}{9005}co se stane s GO klubem Haze?
{9120}{9175}To je hrozné.
{9220}{9270}Rezignuji.
{9290}{9330}Děkuji za hru.
{9385}{9435}Vadilo by, kdybych nerozebíral hru?
{9510}{9595}Měl bych to vyjasnit.
{9730}{9770}Turnaj se blíží.
{9785}{9870}Pan Yu by měl brzy vyhlásit členy týmu.
{9880}{9995}Radši ukáži rozdíl mezi mojí a Touyovou silou,
{10005}{10125}takže si nebude nikdo stěžovat při vyhlášování.
{10205}{10235}Hej...
{10325}{10350}Touyo!
{10365}{10385}Ano?
{10405}{10435}Pojďme si zahrát.
{10540}{10602}Je to naše první hra. Vadilo by ti, když bude rovná?
{10603}{10625}Prosím.
{10685}{10705}Sempai
{10705}{10835}Jsou hráči na první, druhé a třetí desce v turnaji rozřazeni podle síly?
{10845}{10925}Jsou i týmy kde ne, ale obvykle jsou.
{11015}{11070}Soustřeďte se na vlastní hry.
{11071}{11100}Ok.
{11600}{11660}Shindou...brzy...
{11680}{11710}Brzy tě..
{11745}{11770}dohoním!
{11800}{11885}Touyo, turnajový registrační formulář ze školy Haze dorazil.
{11895}{11915}Podívej se na něj.
{11950}{11990}Shindou je na třetí desce?!
{11991}{12145}Občas se obsazení desek nerozhoduje podle síly pro strategické účely.
{12157}{12283}Ten Mitani je nejspíš nejslabší ze skupiny.
{12300}{12355}Odhozením první desky
{12360}{12425}nejspíš plánují jisté vzetí dalších dvou.
{12445}{12545}Tsutsui je ve 3. ročníku a prezident, je na druhé desce,
{12546}{12610}nejspíš nechávající Hikara na třetí.
{12670}{12755}Sensei prosím, nechte mě hrát na třetí desce.
{12835}{12855}Sensei!
{12880}{12915}Nech mě o tom přemýšlet.
{13125}{13245}Myslím, že jsi jediná osoba, která může hrát se Shindoem.
{13280}{13320}Děkuji!
{13420}{13450}Rezignuji.
{13470}{13500}Děkuji za hru.
{13600}{13645}Něměl jsem šanci.
{13670}{13700}To určitě ne!
{13701}{13745}Byl jsi daleko lepší, než jsem myslel.
{13765}{13815}Byl jsi prostě příliš dobrý,
{13830}{13865}viděl jsi mnohem hlouběji než já.
{13875}{13920}Možná jsem se příliš snažil ovládat střed.
{13940}{14010}To by nejspíš nefungovalo kvůli mezerám ve formacích kamenů.
{14010}{14085}Tady jsem se v zoufalství spojil
{14090}{14150}a potom jsem se pořád jen bránil.
{14160}{14205}Nenechal bys mě udělat nic.
{14280}{14365}Bylo ode mě správné, že jsem vzdal snahu stát se Pro.
{14405}{14475}Všichni chvíli poslouchejte.
{14525}{14625}Většina registračních formulářů na tento turnaj přišla. 
{14640}{14725}Omlouvám se za zpoždění, ale teď vyhlásím náš tým.
{14775}{14830}Nejprve chlapci.
{14855}{14890}První deska:
{14895}{14950}První ročník, Touya.
{15005}{15045}Druhá deska:
{15060}{15115}Třetí ročník, Kishimoto.
{15155}{15190}Třetí deska:
{15200}{15250}Třetí ročník, Kuno.
{15295}{15315}Teď dívky...
{15355}{15390}Sensei!
{15390}{15780}Neměl jste mě dát na třetí desku?!
{15645}{15675}Sensei!
{16215}{16280}Dobré ráno Kuwabaro
{16280}{16375}Ó, už jsem tě chvíli neviděl.
{16390}{16460}Perfektní, pojďme si tedy na chvíli promluvit.
{16470}{16580}Zápas Gosei příští měsíc, budu tě na něj vyzývat.
{16580}{16620}Přeji ti hodně štěstí.
{16625}{16660}Jsem si toho vědom.
{16665}{16745}Svoji silou jsi rozdrtil Ogatu.
{16745}{16830}A v tvém věku...to mě udivuje.
{16835}{16940}No tak, ty jsi sám stěží mladý.
{16945}{17025}Holik titulů máš teď? 4,5?
{17035}{17120}Chtěl bych ten, který máš jako svůj pátý.
{17165}{17250}Ale opravdu, ti mladí lidé mě zklamali.
{17260}{17345}I když dokážou vzít titul, hned ho ztratí.
{17350}{17435}Ani žádní opravdu ohromující noví lidé v poslední době.
{17460}{17530}Jsou Inseiové pořád slabší?
{17585}{17639}Jak to jde tvému synoví?
{17640}{17700}On není insei, že ne?
{17730}{17835}Pravidelně hraje se mnou a s každým Pro, který nás navštíví.
{17835}{17900}Nezaostává ve svém studiu hry.
{17910}{17955}Neskládá zkoušky na Pro?
{17975}{18000}Ne
{18010}{18110}Teď je v GO klubu své školy.
{18525}{18655}Když jsem slyšel, že jsi se přidal ke GO klubu Kaiou, nic jsem neřekl.
{18677}{18810}Ředitel mi řekl, že tvá přítomnost by povzbudila klub,
{18815}{18863}takže tě nechám dělat co chceš...
{18915}{19020}Ale proč jdeš na turnaj?
{19025}{19170}Nehodí se, abys šel na turnaj Junior High.
{19330}{19425}Právě teď se nezajímám o lidi kolem mě.
{19480}{19555}Pokud jde Shindou Hikaru na klubový turnaj,
{19560}{19615}pak ho tam budu následovat.
{19645}{19730}Otče, může to znít arogantně...
{19740}{19815}ale můj cíl jsi ty.
{19832}{19950}Do této doby jsem postupoval ke svému cíli stabilně.
{19975}{20025}Myslel jsem, že musím jít přímo k tobě.
{20080}{20205}Myslel jsem, že chůze přímo by mě dostala blíž k "Ruce boha".
{20230}{20275}Ale mýlil jsem se...
{20340}{20410}Nemohl jsem nic dělat...
{20440}{20475}proti Shindoovi Hikarovi.
{20545}{20645}Je jiný než ty nebo Ogata.
{20655}{20725}Jeho přítomnost je mým závažím.
{20740}{20835}Právě teď je on jediná věc v mé mysli.
{21095}{21170}Čelí překážce navzdory svému strachu...
{21225}{21290}to je jediný způsob, jak může člověk vyrůst.
{21300}{21360}Bylo to něco, co jsi předtím neměl.
{21375}{21505}Třást se při stíhání, bát se při vyzývání,
{21510}{21580}jen skrz to můžeš dosáhnout Ruky boha.
{21635}{21660}Sensei!
{21670}{21760}Neměl jste mě dát na třetí desku?!
{21775}{21880}Řekl jste sám, že já jediný proti němu mám šanci.
{21915}{21935}Já...
{21940}{21995}Já...jsem se přidal, abych bojoval...
{22010}{22030}Touyo!
{22060}{22115}Tohle je aktivita Junior High klubu.
{22195}{22340}Věřím, že nejsilnější osoba by měla hrát na první desce.
{22355}{22385}Sensei!
{22410}{22445}To není všechno!
{22470}{22580}GO klub Kaiou je model pro ostatní školy.
{22610}{22730}Řekl jsem, že jsi jediný, kdo má šanci proti Shindoovi Hikarovi z Haze.
{22780}{22805}Ale...
{22840}{22895}Tohle je místo vzdělání.
{22980}{23070}Nezměním svoji vůli jako učitel.
{23100}{23140}Jsi na první desce.
{23210}{23235}Ale...
{23495}{23540}Jen jednou...
{23600}{23700}Jen tenhle turnaj je všechno...
{23760}{23850}Jakmile turnaj skončí, opustím klub!
{23905}{23970}Sensei! Já..!
{24205}{24250}Sensei!
{24350}{24385}Touyo...
{24865}{24920}Hej! Mitani!
{25070}{25202}Skvělé! Myslel jsem, že bys nemusel přijít ze strachu z Kaiou.
{25203}{25240}To si děláš srandu.
{25280}{25350}Nic dobrého nepřijde z útěku té černé skupiny.
{25365}{25440}Kdyby utíkala, jiná černá skupina bude zajmutá.
{25475}{25505}Drž hubu!
{25575}{25615}Tsutsui...
{25645}{25780}Mitani, proč bys podváděl, když jsi tak silný?
{25830}{25875}Á, tady jsou.
{25900}{25985}Akari!Nemuselas chodit.
{25985}{26040}Nerozuměla bys i kdyby ses koukala.
{26040}{26080}Rozuměla!
{26081}{26145}Tsutsui mě poslední dobou učil.
{26145}{26225}Vím jak zajmout kameny a počítat území.
{26265}{26350}Co?! Ale udělala jsem vám všem obědy!
{26365}{26405}Jsi skvělá!
{26430}{26470}Hej, Mitani...
{26555}{26650}Fujisaki, ukážu ti pokoj kam to můžeš odložit.
{26650}{26675}Díky...
{26740}{26795}Mitani..pojďme si zahrát.
{26805}{26835}Ne, díky.
{26870}{26950}Opravdu to bude takhle v pořádku?
{26985}{27040}Oh? To je Shindou z Haze!
{27040}{27058}He?
{27059}{27090}Shindou?
{27090}{27120}Haze?
{27125}{27195}V minulém turnaji vyhrál proti Kaiou.
{27245}{27345}Byl jen v 6. třídě, ale zúčastnil se jako Junior High,
{27355}{27455}a všichni pozorovatelé byli ohromeni jeho hrou.
{27525}{27560}Tohle je problém...
{27570}{27610}To je v pořádku.
{27610}{27680}Prostě zkus hrát co nejlépe.
{27692}{27725}Jo!
{27730}{27772}Co nejlépe! Co nejlépe!
{27773}{27840}Napřed porazím třetí desku v prvním kole...
{27860}{27930}Je to opravdu tak jednoduché Hikaru?
{27930}{27995}On bude také hrát co nejlépe...
{27995}{28100}No tak, můj cíl je Kaiou.
{28101}{28155}Nemůžu si dovolit prohrát v prvním kole.
{28165}{28275}Potom, pokud budu hrát co nejlépe proti Kaiou...
{28275}{28305}možná...
{28305}{28415}Třetí deska Kaiou bude taky hrát co nejlépe Hikaru...
{28415}{28500}Páni! Nemůžu se dočkat zápasu s Kaiou.
{28520}{28580}Zajímalo by mě kdo je na třetí desce Kaiou...
{28580}{28605}Jsem to já.
{28680}{28740}Třetí deska Kaiou jsem já...
{28750}{28775}Shindou!
{28815}{28840}Touyo...
{28850}{28905}proč jsi...
{29020}{29110}Pamatuješ si, že jsi říkal, že se mnou nebudeš hrát?
{29160}{29250}A že půjdeš na GO turnaj?
{29285}{29330}Konečně jsem dorazil.
{29345}{29370}Touyo...
{29400}{29460}přošel jsi celou cestu sem...
{29475}{29520}abys dohnal...Saie?
{30000}{30090}Z angličtiny: Anakreon
{31820}{31885}Go! Go! Igo!
{31885}{31940}Zkusme jiný problém.
{31940}{32035}Pokud je černý na tahu, může zajmout pár bílých kamenů.
{32035}{32075}Přemýšlejte o tom.
{32075}{32145}I když zajmou jeden tvůj kámen, ty můžeš zajmout mnohem víc.
{32205}{32280}Bílý udělá tohle.|/Tip: I když zajmou jeden z tvých kamenů, můžeš zajmout mnohem víc./
{32360}{32385}A potom tohle.
{32400}{32490}Přemýšlejte o tom znovu. Ale je to jedno, ze tří míst.
{32530}{32555}Ano.
{32575}{32665}Já vezmu...|/Jeden kámen byl sebrán, ale.../
{32680}{32715}a pokud spojím...
{32725}{32790}Správně! Vezmi kameny, které jsi zajmul.
{32790}{32872}Zvládl jsi to Yuuki!
{32872}{32940}Šťastný nový rok!
{33230}{33315}Nemůžeš se smát, dokud to neskončí!