{1}{1}23.976
{1}{20}DIV3 640x480 23.976fps 176.0 MB
{21}{99}Fujiwarano Sai, hráč GO z doby Heian,
{111}{223}prošel časem a vrátil se do tohoto světa v mysli Shindoa Hikara,
{223}{301}aby dosáhl Ruky Boha.
{708}{786}Z angličtiny: Anakreon
{2450}{2470}Ale...
{2520}{2565}co když bude podvádět při turnaji?
{2605}{2690}Má nervy udělat to dospělým v GO salonu.
{2700}{2800}Pravděpodobně by neváhal proti dětem v turnaji.
{2825}{2910}Jeho soupeř si nevšimne, my si nevšimneme...
{2920}{3025}ale...můžeš mít někoho takového v týmu?!
{3080}{3165}Zastavit ho...Sai, jak?
{3175}{3200}Nevím.
{3210}{3270}Ale jsem si jistý, že to můžeme dokázat...
{3280}{3325}musíme ho zastavit!
{3340}{3460}Jedenáctý zápas:|Nejbezohlednější čin
{3490}{3510}Mitani!
{3520}{3575}He? Další dítě?
{3578}{3680}Tenhle už nevsadí 10000 yenů, že ne?
{3690}{3730}10-10000 yenů!?
{3740}{3800}Ah, kluk ze včerejška. Jdeš hrát?
{3810}{3870}Ne, budu se jen koukat.
{3870}{3940}Mohl bys teda zavřít ty dveře?
{3940}{4000}Venku je moc hlučno.
{4001}{4040}Oh, omlouvám se.
{4770}{4830}Zápas je pořád ve střední hře.
{4915}{5115}Hej, jestli jsi kámoš, mohl bys říct tomuhle klukovi, aby na nás starší šel zlehka?
{5155}{5250}Opravdu, tenhle kluk neví jak se držet zpátky.
{5305}{5345}Proč jsi přišel?
{5355}{5405}Co? Hmm..no..
{5480}{5540}Sai, Mitani vyhrává, že?
{5565}{5610}Nebude podvádět, pokud vyhrává, že ne?
{5665}{5730}Vypadá to, jako kdybys byl zklamaný.
{5731}{5770}Ne, nejsem.
{5800}{5845}O čem to mluvíš?
{5950}{5995}Hej, Tsutsui...
{6001}{6085}Jak Mitani podvádí v Seichi?
{6105}{6185}V GO se rozhoduje výhra podle velikosti uzemí.
{6186}{6258}Například tahle černá formace.
{6260}{6320}Spočítej počet vnitřních průsečíků.
{6320}{6345}Hmm...
{6505}{6535}12
{6536}{6615}To znamená, že tohle území má hodnotu 12 moku.
{6630}{6710}Po skončení hry obvykle vypadá takhle,
{6720}{6760}ale špatně se to počítá, že?
{6765}{6865}Takže uspořádáš území do čtverce pro snazší počítání.
{6905}{6980}Vše co děláš, je pohybování kameny uvnitř území.
{6980}{7060}takže to nezmenší ani nezvětší velikost tvého území.
{7075}{7140}Vidíš? Takhle 3x4 dá 12.
{7140}{7200}Jo, lépe se to počítá!
{7205}{7315}Takže tohle je seichi... a on v tom podváděl?
{7315}{7345}Jo.
{7345}{7415}Je to jednoduché?
{7460}{7495}Nezáleží na tom, jestli je nebo ne...
{7500}{7670}I kdybych to udělal nešikovně, soupeř by si nejspíš nevšiml.
{7680}{7745}Protože při Seichi...
{7745}{7825}obvykle nedáváš pozor na soupeře.
{7842}{7935}Přeci jen je dáno, že by žádná strana neudělala něco nečestného.
{7985}{8130}Hra GO je založena na důvěře.
{8165}{8350}Podvádění v Seichi je ten nejbezohlednější čin, který využívá důvěry.
{8435}{8500}A Hikaru chce vzít takové dítě?
{8620}{8715}Jak tenhle chlapík může vsadit 10000 yenů s jeho schopnostmi?
{8725}{8810}Je mnoho starých mužů bez opravdových schopností, kteří chtějí vypadat cool.
{8880}{8920}Hej chlapče...
{8930}{8990}Myslíš si, že už jsi vyhrál, že?
{9005}{9105}Slyšel jsi rčení "Neznáš výsledek zápasu, dokud neskončí"
{9120}{9210}Také tomu říkají "Nepočítej kůže, dokud je nemáš"
{9270}{9320}Ó, ty ses zasmál?
{9360}{9475}Nemůžeš se smát dokud to neskončí, při zápasu...
{9525}{9565}To je milé.
{9630}{9660}Ano?
{9670}{9740}Vypadáš, že rozumíš tomu co říkám.
{9755}{9810}Později by z tebe mohlo něco být.
{9815}{9925}Hej chlapče, můžeš mi podat ten popelník?
{10030}{10060}Díky.
{10200}{10230}Jste levák?
{10385}{10475}Taky máš dobré oči, pěkné.
{10477}{10505}Levák?
{10506}{10565}Dobře, je to pořád moc brzo...
{10595}{10730}ale naučím tě, co je to dospělé GO. Za cenu 10000 yenů!
{10775}{10905}Myslíš, že není možné abych tě teď dohnal, že?
{10905}{10960}Ale jen sleduj!
{11025}{11075}Hra teprve začíná...
{11115}{11140}Sai...
{11570}{11605}Sakra...
{11730}{11745}Tady!
{11750}{11815}Drží kameny mnohem lépe než předtím.
{11960}{12010}Teď doháním...
{12305}{12355}Podívejme, tady 5 moku!
{12715}{12750}10 moku!
{12835}{12860}15 moku!
{13035}{13060}On pohnul kamenem!
{13070}{13100}To si děláš srandu, kde?!
{13170}{13255}Hra se rychle obrací.
{13350}{13420}Ten kámen tam nebyl! Kdy?!
{13430}{13470}Co je chlapče?
{13480}{13525}Přehlédl jsi něco?
{13545}{13665}Vsadili jsme na hru, měl bys víc dávat pozor.
{13680}{13700}Mitani...
{13810}{13945}Jo, přesně. Nevíš dokud není konec.
{14350}{14440}To nezvládnu...je o moc lepší než já...
{14455}{14510}a pokud hýbe s kameny...
{16075}{16155}Okej, hra je u konce, víš kdo vyhrává?
{16156}{16225}Nemůžeš vyhrát pokud nebudeš podvádět v seichi.
{16330}{16385}Jsi pomalý! Pomalý!
{16415}{16490}Tenhle chlapík dělá to samé co jsem dělal já!
{16570}{16690}12 a půl moku rozdíl s komi... vyhrávám.
{16755}{16830}Hej chlapče, vytáhni 10000 yenů.
{17205}{17225}Mitani...
{17440}{17465}Sakra!
{17495}{17535}Je to všechno?
{17570}{17690}5,6,7...8... a ...
{17720}{17765}Chybí ti 20 yenů.
{17820}{17870}Mitani, já ti půjčím.
{17870}{17965}Hej Shuu, můžeš mi půjčit 20 yenů?
{17985}{18010}Mitani...
{18115}{18140}Děkuji.
{18140}{18170}Hej chlapče.
{18173}{18280}Když jsi moc podváděl, lidé jako já byli zavoláni.
{18280}{18305}Dake!
{18585}{18640}Půjčíš mi 20 yenů?
{18747}{18775}Děkuji mnohokrát
{18845}{18870}Mitani!
{18930}{18960}Co je s ním?
{18961}{18995}Mitani!
{19020}{19045}Počkej!
{19065}{19120}Kdy se tu z toho stalo závodiště?
{19170}{19190}Mitani!
{19390}{19500}Nakonec...svou lekci dostal...
{19525}{19575}Tomu se nejspíš nedalo vyhnout...
{19590}{19685}...lidé se učí jen z těch chyb, které je zasáhnou.
{19720}{19745}Ale!
{19760}{19790}Sai! Byla to past!
{19791}{19895}Ten chlapík hrál na začátku špatně, aby Mitaniho obelhal!
{19920}{19950}Ale...
{19970}{20025}bylo to příliš kruté.
{20045}{20100}Můžeme to pro něj získat zpátky?! Těch 10000 yenů!
{20115}{20200}Mitani se už poučil, ale ten chlapík je...
{20250}{20280}Sai!
{20305}{20380}Ani já už nemůžu zůstat zticha...
{20385}{20475}Musíme si poradit s lidmi jako on, kteří mají ledové srdce.
{20530}{20620}Kdo si myslíš, že je nejsilnější hráč v Go historii?
{20621}{20710}No, teď je špička Touya meijin se čtyřmi tituly...
{20710}{20805}Nejsilnější mladý hráč by mohl být buď Kurata 4 dan nebo Ogata 9 dan
{20830}{20920}Slyšel jsem, že tenhle reportér se na to zeptal Pro.
{20932}{20955}a?
{20965}{21055}A Pro bez zaváhání odpověděl:
{21070}{21145}"Honinbou Shuusaku z doby Edo"
{21175}{21275}GO z té doby je stupidní, v téhle době by nefungovalo.
{21285}{21390}Zítra dáme Mitanimu zpátky těch 10000 yenů a znovu ho požádáme o vstup do GO klubu!
{21420}{21510}Ale Sai, vyhraješ? Ten chlapík vypadal opravdu silně.
{21510}{21590}Viděl jsem ho hrát, je to v pořádku. Vyhrajeme.
{21595}{21635}A co když pohne s kameny?
{21650}{21685}Všimnu si toho.
{21690}{21810}Můžeš mu říct, žes ho viděl.
{21825}{21860}Co když bude podvádět v Seichi?
{21885}{21980}Nedojde to k Seichi, rezignuje.
{22055}{22145}Bylo to teprve nedávno, co začal podvádět.
{22155}{22305}Když sázením vydělával jen trochu, zákazníci ho měli rádi.
{22310}{22455}Rádi mu dali peníze, jako kdyby byl jejich vnuk.
{22480}{22600}Ale nemůžeš podvádět...proto jsem požádal, abys přišel.
{22601}{22705}Je to povinnost dospělého, dát dítěti lekci.
{22735}{22895}Shuu, s 10000 které jsem ti dal a 20000 poplatkem mi dej 30000 yenů.
{22940}{22990}Nejspíš už nepříde...
{22990}{23020}Mitani...
{23045}{23070}nejspíš nemůže přijít...
{23071}{23100}jak smutné.
{23170}{23225}Zavolej, kdykoli mě budeš potřebovat.
{23230}{23305}No, řekl bych že počkám na nějakou kořist.
{23305}{23420}O čem to mluvíš, už tě nepotřebuju, jdi domů.
{23425}{23490}To je sobecké Shuu.
{23535}{23565}Ojisan!
{23580}{23625}Jsem jeho přítel.
{23660}{23740}Když vyhraju, dáte mi zpátky těch 10000 yenů?
{23775}{23885}Pak pokud prohraješ, dáš mi 10000 yenů, že?
{23900}{23920}Hikaru, to je v pořádku.
{23922}{24040}Pak to neudělám, o tom je přeci sázka.
{24050}{24125}Dake, nech už děti na pokoji.
{24130}{24170}Chlapče, ty už bys taky měl jít domů.
{24175}{24235}Hikaru, já neprohraju.
{24270}{24300}Hikaru!
{24340}{24405}Dobře! Zaplatím 10000 yenů pokud prohraju.
{24420}{24495}Pak si s tebou zahraju. Promiň.
{24495}{24515}Dake!
{24625}{24670}Nedám ti handicap.
{24680}{24735}Žádný nepotřebuju.
{24765}{24815}Ty ho nepotřebuješ?
{24815}{24880}Děti v téhle době...
{24905}{24980}Už jsi viděl moji sílu
{24980}{25045}a jak silný jsi ty?
{25050}{25115}Jak silný? Hmm..
{25125}{25190}asi tak silný jako Honinbou Shuusaku.
{25235}{25340}To je sranda! Ze všech lidí Shuusaku?
{25370}{25435}Kdyby Shuusaku přišel,
{25435}{25510}jediná osoba která by s ním mohla hrát by byl Touya Meijin.
{25520}{25560}Jsem černý.
{25665}{25785}S respektem k Shuusakovi začnu svou levou rukou.
{25845}{25888}Pravý spodní roh, komoku.
{26010}{26045}17-5
{26175}{26210}6-17
{26580}{26650}Co budou dělat teď?
{26650}{26700}Sledují všichni?
{27440}{27475}Třetí strike!
{27515}{27605}Nemohl se trefit ani do dvou přímých míčků...
{27630}{27675}Oh jednou se trefil!
{27678}{27750}Útok byl trochu moc jednoduchý,
{27755}{27835}měli svůj způsob.
{27960}{28085}Páni, to skončilo rychle.
{28265}{28360}Opravdu, přestaň dělat takovéhle věci.
{28370}{28485}Nemůže být dobrý pocit krást peníze dětem.
{28520}{28595}Ten kluk byl taky hloupý, že chtěl hrát s Dakem.
{28595}{28675}Dobře Dake, odejdi až to dopiješ.
{28832}{28855}Dake!
{28995}{29050}Dake, tohle je!
{29110}{29170}H-Ho-Honinbou...
{29180}{29220}Shuusaku!
{29320}{29370}Á, tady to máme!
{29372}{29505}Home run! Skvělý zásah!
{29520}{29605}Zítra to dám Mitanimu a požádám ho o vstup.
{29605}{29700}Tak budeme tři, můžeme jít na turnaj!
{30000}{30090}Z angličtiny: Anakreon
{31825}{31885}Go! Go! Igo!
{31925}{31975}Jsou skoro Vánoce
{31985}{32100}Takže jsem dneska připravila takovouhle GO desku.
{32100}{32175}Dneska dám vám dvěma problém a vy ho zkusíte vyřešit, ano?|/Dneska dáme těm dvěma problém./
{32185}{32225}Tady je problém.
{32225}{32370}Teď je na tahu červený a je tu jedno místo, kde může zajmout stříbrné kameny. Kde?|/Kam může hrát červený aby zajmul stříbrné kameny?/
{32375}{32440}Položte tam kámen.|/Měli byste o tom také přemýšlet!/
{32505}{32545}Uteču.
{32560}{32615}A děkuji mnohokrát.|/Promiň Yuuki/
{32655}{32705}Teď zkus ty Mai.
{32825}{32900}Ano, to je správně!|/Mai to uhodla!/
{32900}{32945}Yuuki, byl jsi blízko.
{33005}{33075}Sensei prosím, nechte mě hrát na třetí desce.
{33075}{33135}Můj cíl je Kaiou!
{33135}{33190}Nemůžu si dovolit prohrát při prvním zápasu.
{33190}{33250}Shindou... brzy...
{33255}{33300}Brzy tě doženu...
{33575}{33650}Neměl jste mě dát na třetí desku?!