{1}{1}23.976
{1}{20}DIVX 512x384 23.976fps 178.9 MB
{21}{99}Fujiwarano Sai, hráč GO z doby Heian,
{111}{223}prošel časem a vrátil se do tohoto světa v mysli Shindoa Hikara,
{223}{301}aby dosáhl Ruky Boha.
{708}{786}Z angličtiny: Anakreon
{2445}{2470}Rezignuji.
{2585}{2705}Myslel jsem...myslel jsem, že jsem v tobě viděl Ruku Boha...
{2730}{2845}Patnáctý zápas:|Hráč na síti
{2860}{2905}Jaké to bylo?
{2905}{2975}Měl jsem se jednuduše spojit tady?
{2985}{3035}Ale co kdyby odsud šel na atari?
{3040}{3100}Sensei Akira dělá Pro zkoušky?
{3110}{3145}Jo, vypadá to tak.
{3150}{3215}Slyšel jsem o tom ráno od Muroie.
{3245}{3300}Je to pravda slečno Ichikawo?
{3325}{3370}Opravdu?! To je velká novinka.
{3395}{3510}Od příštího roku bude svět GO vzrušující.
{3545}{3700}Ale bylo to náhlé. Opravdu jsem nemyslel, že to zkusí tento rok znovu.
{3725}{3795}Stalo se Akirovi něco?
{3805}{3820}Kdo ví?
{3835}{3920}Zeptala jsem se ho na jeho školní GO klub, protože o něm přestal mluvit, ale...
{3945}{4105}"Na tom už nezáleží. Byla to jen objížďka" řekl.
{4115}{4150}Mohl bych sem dostat taky jedno?
{4150}{4175}Vteřinku.
{4195}{4255}Hej, televizní přenos NCC Cupu bude začínat!
{4475}{4545}Pokud si objednáte náš časopis na celý rok
{4545}{4605}dostanete jeden navíc za stejnou cenu.
{4620}{4700}V téhle době můžete hrát GO i přes internet!
{4720}{4780}Proč to jednou nezkusíte?
{4790}{4855}Hmm..29..á tady to je!
{4995}{5090}Ale je to vůbec zajímavé sledovat zápas z takové dálky?
{5105}{5205}Hráč Pro používá velkou desku a vysvětluje nám každý tah.
{5265}{5365}Neruší to hráče, když lidé mluví hned vedle nich tak hlasitě?
{5400}{5435}Jsem si jistý, že se baví.
{5445}{5505}Páni! Taková Go deska!
{5525}{5600}Skvělé, zdá se že i Sai se baví.
{5635}{5670}Bude to začínat.
{5690}{5780}Zdravím dámy a pány v publiku, a všechny sledující televizi.
{5800}{5925}Brzy začne pátá hra prvního zápasu čtrnáctého ročníku NCC Cup Go turnaje,
{5935}{6040}mezi Fijisawem Kikou 9danem a Takadou Kouichi 7danem.
{6115}{6210}Hru bude vysvětlovat Murase 9dan a tahy bude zaznamenávat Yoshinaga 2dan.
{6285}{6345}Pojďme teď začít hru.
{6395}{6530}Dobře, Murase 9dan, co si myslíte, že bude dnes ten nejzajímavější bod ve hře?
{6530}{6675}Dobře, Fujisawa 9dan je v lize Meijin i v lize Honinbou...
{6675}{6805}Udělal jsem Saiovi něco hrozného...hrál jsem jeho zápas s Touyou místo něho...
{6850}{6865}Touyo...
{6915}{7010}Zkusím to! Neuvidím to, dokud nebudu hrát sám!
{7020}{7085}Chci znát rozdíl mezi ním a mnou!
{7190}{7215}Přestaň dělat blbosti!
{7260}{7310}Co jsem udělal, bylo špatné i pro Touyu...
{7335}{7375}Chtěl hrát se Saiem tak moc...
{7400}{7524}Hmm..zajímavé, jak vzrušující vývoj.
{7540}{7600}Půjde příště někam sem?
{7670}{7750}25 sekund, 6, 7, 8...
{7760}{7805}4-12...hmm...
{7810}{7855}Páni, uhodl jste to!
{7885}{7960}Nevysvětluji vám hru pro nic za nic, víte?
{8675}{8765}Ale co budu dělat teď?
{8785}{8840}Chci nechat Saie hrát pořád, ale on je tak silný.
{8855}{8950}Byl bych potom mistr ve vyhrávání štěstím.
{9015}{9093}Vzniká tu prudká bitva.
{9093}{9185}10 sekund, 1, 2, 3, 4...
{9200}{9245}4-13
{9245}{9295}Oh...hrál sem?
{9305}{9380}Aj, vůbec jsem nedával pozor.
{9400}{9465}Byl tento kámen zabit?
{9470}{9570}Ano, ale možná by mohl jít z této strany do atari.
{9580}{9610}pojďme to zkusit zahrát.
{9630}{9705}Tohle a sem...a takhle...
{9705}{9770}Budeme to pořád sledovat Tsutsui?
{9780}{9840}Jen sleduj...ale ještě to není u konce!
{9865}{9915}Jdu se na chvíli projít kolem haly.
{9940}{9955}Hikaru!
{9960}{10040}Mám dost, už tu nemůžu jen tak sedět.
{10045}{10100}Ale!
{10120}{10190}Tolik jsem se na dnešek těšil!
{10230}{10255}Sai...
{10335}{10390}Hele, prodávají knihy o GO.
{10415}{10480}Podívej, támhle hrají GO na počítači.
{10510}{10570}Hej Sai, pojďme se na to podívat.
{11025}{11065}Přivedl tě sem otec, nebo tak někdo?
{11075}{11120}Ne, přišel jsem s kamarádem.
{11120}{11170}Páni, to se v dnešní době moc nevidí.
{11175}{11205}Máš doma počítač?
{11205}{11230}Ne, nemám.
{11235}{11305}Zajímají tě věci jako internet?
{11315}{11340}Internet?
{11350}{11440}Jo, tenhle chlapec právě hraje s někým přes internet.
{11450}{11640}Je černý a jeho soupeř právě položil bílý kámen a on teď hraje černým kamenem.
{11680}{11695}Hej, jestli tam zahraješ...
{11790}{11805}Vidíš?
{11875}{11910}Co si myslíš, že děláš!
{11920}{11955}Tohle není počítačová hra!
{11955}{11995}Musím se omluvit.
{12045}{12145}Omlouvám se za náhlé ukončení hry...
{12180}{12200}Co to říká?
{12210}{12345}Podívejme se..."Hej! Neukončuj hru jen proto, že jsem zajmul pár tvých kamenů! Blbče!"
{12355}{12395}Napsal něco dřív...
{12420}{12460}Páni, to je zajímavé!
{12470}{12515}Zajímalo by mě, jestli je to dítě.
{12530}{12545}Dítě?
{12560}{12595}On je dítě?
{12610}{12715}Podle toho co napsal a jeho přezdívky by mohl být dítě.
{12725}{12750}Přezdívky?
{12775}{12820}To je falešná totožnost, kterou používáš na internetu.
{12870}{12895}Zelda...jo?
{12905}{12960}Páni, jsou tam i děti?
{12980}{13095}Na internetu není odhalen tvůj obličej, jméno ani věk, takže nevíš.
{13110}{13200}Nejsou to jen děti, podívej, jsou ti i lidé z jiných zemí!
{13230}{13340}JPN je japonsko, CHN je čína, CAN je kanada.
{13350}{13390}Jsou tu USA a GER.
{13415}{13445}A co NLD?
{13450}{13470}To je Nizozemsko.
{13495}{13610}Lidé v tomto seznamu vyzývají jiné nebo jsou vyzváni ke hře.
{13635}{13700}Ovládá se to jednoduše.
{13710}{13780}Když chceš hrát hru, udělej tohle...
{13820}{13850}Potom udělej tohle...
{13900}{13920}chceš to zkusit?
{13925}{14095}Ne, ještě ne. Ale mohl byste mě říct víc o ovládání?
{14115}{14190}Napřed se musíš registrovat.
{14230}{14325}Chceš tedy začít načtením domovské stránky?
{14325}{14385}Neznají tvůj obličej, věk ani opravdové jméno!|Napřed vstup do světa igo net a zkus vyhledávat.
{14395}{14415}Tohle!
{14650}{14700}Promiň, že po tobě chci, abys hrál s někým tak slabým.
{14705}{14730}Ne, to je v pořádku.
{14740}{14775}A pokud bílý půjde sem?
{14805}{14825}Tady, že?
{14880}{14895}Tady?
{14905}{14915}Jo.
{14950}{15010}Sem? Nebo sem?
{15030}{15070}Jakmile jsi takhle daleko tak na tom nezáleží.
{15090}{15115}Tohle je v pořádku, že?
{15130}{15170}He? Jen vy dva?
{15220}{15245}Kde je Shindou?
{15265}{15300}Říkal něco o internetu.
{15310}{15360}Internet? Už?
{15365}{15390}Už?
{15395}{15498}Včera jsem šel se Shindoem sledovat zápas Pro, ale...
{15525}{15650}unavil se sezením a v půlce odešel.
{15675}{15725}Co potom Hikaru dělal?
{15735}{15770}Dělal něco na internetu.
{15775}{15830}Nejsem si jistý, co ho to přitáhlo.
{15840}{15915}Ale v hale ukazovali internetové GO
{15920}{15980}a on celou dobu poslouchal vysvětlování toho chlapíka.
{16015}{16085}Než jsem přišel po zápase.
{16280}{16375}Ale kam šel na internet?
{16405}{16495}Internet je v obchodě, kde pracuje Mitaniho sestra.
{16505}{16525}Mitaniho sestra?
{16550}{16620}Moje sestra pracuje v internetové kavárně.
{16645}{16705}Vyrazil odsud, když jsem mu řekl kde to je.
{16785}{16820}Tsutsui, chceš si zahrát?
{16825}{16855}Ne, to je v pořádku!
{16910}{16930}Tady.
{17000}{17065}Fujisaki, začínáš rozumět GO?
{17070}{17123}Jo, zrovna jsem se naučila Schichou a Geta
{17195}{17280}Je to mimo téma, ale je skoro léto, co budeme dělat s klubem?
{17295}{17370}Mám v létě školu, takže nemám moc čas.
{17380}{17465}Jo, Tsutsui se musí připravovat na přijímací zkoušky.
{17485}{17585}Podle toho jak se choval, Hikaru bude zřejmě celou dobu na internetu.
{17595}{17710}Já...půjdu znova do toho GO salonu.
{17730}{17860}Já půjdu do té školy, do které chodil Hikaru.
{17885}{17965}A jen co začne druhé čtvrtletí, seženu nějaké členky.
{17980}{18015}Taky chci jít na turnaje.
{18035}{18095}Můžeš se účastnit taky individuálních zápasů.
{18120}{18150}Ne! Skupinový zápas je lepší!
{18155}{18205}Myslela jsem si to, když jsem vás viděla hrát.
{18215}{18280}Skupinový zápas je rozhodně mnohem zábavnější!
{18410}{18430}Máš pravdu...
{18460}{18520}Prohráli jsme s Kaiou, ale byla to zábava.
{18555}{18650}Jo, skupinové zápasy jsou fajn.
{18760}{18840}Hej, pojďme se sejít alespoň jednou týdně přes léto!
{18850}{18910}Jo, alespoň jednou týdně to zvládnu.
{18915}{18935}Jo.
{19140}{19185}Světová síť Igo?
{19195}{19235}Musím jen vstoupit na tohle?
{19275}{19375}Ale i když znám počítače, nevím nic o Go.
{19385}{19485}To je v pořádku, sám jsem se naučil, jak hrát.
{19545}{19610}Světová Síť Igo
{19635}{19670}A vyhledávat!
{19720}{19760}Á tohle, že?
{19790}{19855}Můžeš tu hrát proti lidem po celém světě.
{19865}{19940}Po celém světě? Ale mluvíš anglicky?
{19955}{20040}Nemusím mluvit anglicky, vše co dělám je hraní Go.
{20100}{20240}Hikaru. Včera ses taky díval na takovouhle krabici. I když byla plošší...
{20250}{20290}Jo, ale uvnitř je to stejné.
{20365}{20430}Ale co chceš dělat?
{20455}{20535}Myslel jsem, že bych tě nechal hrát tolik GO kolik chceš.
{20550}{20615}He? Hikaru, co jsi to právě řekl?
{20650}{20680}No, počkej a uvidíš.
{20770}{20845}Hej, kde se Mitani naučil GO?
{20855}{20900}Od našeho dědečka.
{20905}{20940}Když byl na základní škole
{20941}{21020}měl učitele který uměl hrát, a hodně spolu hráli.
{21030}{21095}Potom začal chodit do GO salonů.
{21145}{21180}Je Yuuki dobrý?
{21195}{21215}Jo je!
{21240}{21265}Tys nevěděla?
{21270}{21345}Opravdu?! A co ty?
{21355}{21455}Já? Já...jsem ok, řekl bych.
{21465}{21560}Jsi jen ok a hraješ s lidmi z celého světa přes internet?
{21570}{21618}Jo, děkuji.
{21625}{21705}Promiň. Hádám, že na schopnostech nezáleží.
{21720}{21765}Zbytek už zvládneš, ne?
{21775}{21870}Hej, opravdu můžu hrát zadarmo?
{21880}{21995}Jo, to je dobrý. Ale nikomu to neříkej. A nemůžeš, když tady nejsem.
{22005}{22055}Ok, díky!
{22065}{22110}Zavolej mě, když budeš odcházet.
{22130}{22150}Takže, později.
{22185}{22235}No, takže nejprve musíme vybrat přezdívku.
{22285}{22370}Hej, kolik chci? Opravdu?
{22515}{22539}Jméno bude...
{22570}{22650}S...A...I...
{22710}{22720}Sai!
{22845}{22890}Dobře, pojďme!
{23450}{23550}Příští měsíc budu asi na týden v Japonsku mami.
{23600}{23720}Jo, byl jsem vybrán jako reprezentant US pro Mezinárodní Amatérský GO Turnaj.
{23810}{23865}Jo, okolo 50 národů.
{23875}{24020}Jeden reprezentant pro každý národ. Já jsem byl národní jednička při zkouškách.
{24060}{24210}Samozřejmě, Asie je silná. Japonsko, Čína a Korea.
{24235}{24290}US? Minulý rok jsme byli osmí.
{24305}{24415}Ale díky internetu jsme pořád silnější.
{24440}{24505}Můžeme hrát s někým silným, kdykoli chceme.
{24530}{24610}A slyšel jsem, že Japonsko je poslední dobou pořád slabší.
{24660}{24700}Jo, budu hrát co nejlépe.
{24745}{24840}Á, výzva právě, když jsem se chystal zavěsit.
{24860}{24920}Dobře mami, dej na sebe pozor.
{25080}{25165}Sai? Tohle jméno jsem ještě neviděl.
{25190}{25235}Dobře, uvidíme jak je silný.
{25285}{25310}Á, tady.
{25845}{25895}Mistře! Mohl bych dostat výukovou hru...
{25960}{26105}Mistr teď trénuje přes internet na Národní Amatérský GO Turnaj příští měsíc.
{26250}{26335}Škoda...takže nemám na výběr.
{26340}{26395}Zahraju si s tebou já.
{26405}{26455}Ano, děkuji.
{26970}{27055}Pro mistra nejsme žádní soupeři.
{27140}{27285}Je to reprezentant Nizozemska dva roky v řadě! Je neuvěřitelný.
{27310}{27380}Minulý rok byl šestý! Šestý!
{27390}{27465}Možná bude tento rok schopný zlomit kontrolu Asie!
{27480}{27540}Ale co jeho skutečná práce?
{27545}{27650}Je GO tak zaujatý, že dokonce otevřel tenhle kurz.
{27665}{27760}Ano, máš pravdu. Mohli by ho vyhodit z pozice Asistujícího Profesora.
{27895}{27910}Mistře?
{28100}{28175}Oh! Je to Pro! Je to Pro!
{28222}{28255}To musí být ono!
{28270}{28335}Nemůžeš říct, kdo to je přes internet.
{28350}{28480}Slyšel jsem, že Asijští Pro občas hrají přes internet proti Amatérům, aby zabili čas.
{28500}{28525}Mistře?
{28535}{28555}Mistře?
{28600}{28615}Mistře...
{28665}{28688}Prohrál jste?
{28730}{28765}Byl jsem rozsekán!
{28770}{28860}Myslel jsem, že dostanu infarkt z toho, jak špatně jsem prohrál.
{28910}{28975}He? Jeho jméno už není v seznamu.
{29010}{29055}Nikdy jsem o něm neslyšel...
{29075}{29135}Pochybuji, že někdo z mých kontaktů přes net bude vědět...
{29150}{29205}Sai...zajímalo by mě kdo to je...
{29260}{29300}Nebyla to zábava?!
{29300}{29315}Ano!
{29330}{29430}Dobře! Budeme chodit hrát přes síť každý den po zbytek léta!
{29460}{29515}Cože?! Necháš mě hrát každý den?!
{29535}{29635}Jo. Nechám tě hrát dokud tě to neunaví!
{29645}{29655}Ano!
{30000}{30090}Z angličtiny: Anakreon
{31825}{31885}Go! Go! Igo!
{31910}{32020}Minule jsme mluvili o Nigiri. Tentokrát budeme mluvit o něčem jiném co je důležité.
{32045}{32155}Když jste rozhodovali barvy přes Nigiri, černý musel dát bílému 5 a půl moku.
{32165}{32200}To se jmenuje Komi.
{32210}{32270}U Go, ten kdo hraje první je ve výhodě.
{32270}{32355}Takže pro vyrovnání dá 5 a půl moku soupeři.
{32370}{32410}Co je "půl" u 5 a půl moku?
{32415}{32470}To znamená polovinu jednoho moku.
{32475}{32505}Podívej se na GO desku.
{32510}{32560}Tohle je po Seichi.
{32560}{32615}Černého území je 25 moku.
{32615}{32665}Bílého území je 20 moku.
{32670}{32765}Pokud přidáš komi, bílého území je 25 a půl moku.
{32770}{32845}Kvůli tomu vyhraje bílý o půl moku.
{32850}{32930}Půl z Pěti a půl moku je pro zbavení se remíz.
{33005}{33070}Sensei! Je tam někdo opravdu silný!
{33080}{33210}Jak zvláštní. Proč můžeme hrát GO proti mnoha lidem s takovouhle krabicí?
{33215}{33265}Internet je tak zábavný!
{33270}{33315}OK, pojďme hrát s tímhle chlapíkem!
{33580}{33620}Kde jsi Sai?!