{1}{1}29.970
{2841}{2945}Teï jsem slavná. Puf!
{2951}{3036}Objevila se falešná Sailor Moon|a bojuje dobøe.
{3036}{3101}Ale to je jen nepøátelská past...
{3101}{3167}Tuxedo Kameni-sama, dej si pozor!
{3179}{3290}Teï nastal èas pro|skuteènou Sailor Moon.
{3292}{3380}Bojuji dobøe ve jménu|Mìsíce.
{3300}{3400}http://www.sweb.cz/umino.gurio
{3461}{3527}Já jsem Tsukino Usagi.
{3530}{3655}Jistì víte, e hájím lásku a spravedlnost|jako pùvabná bojovnice v námoønickém,
{3655}{3721}Sailor Moon! To je mé poslání!
{3726}{3800}Ale je to pìknì tìkej dob.
{3800}{3943}Musím najít legendární støíbrnı krystal,|døív ne se k nìmu dostanou zloèinci.
{3943}{4095}Ale nejdøíve musím shromádit|sedm Duhovıch krystalù.
{4138}{4272}Ale teï, kdy jsme ètyøi Sailor Senshi,|pak práce pùjde líp!
{4464}{4591}Epizoda #33|"Pøíchod poslední Sailor Senshi,|Sailor Venus!"
{4732}{4801}Pøiprav se potkat svùj osud,|Sailor Moon!
{4913}{4983}Budu s vámi bojovat, Nephrite!
{5046}{5102}Tuxedo Kamen-sama!
{5612}{5672}Vidìla jsem dost!
{5755}{5856}Zoisite, co to má znamenat?
{5870}{5953}Mám dost takovıch vıjevù.
{5983}{6030}Královno Beryl-sama,
{6038}{6273}Vidìla jste vıjev, ve kterém èarodìjnice témìø|dostali Sailor Moon, ale nìkdo jí zachránil, e?
{6334}{6412}Myslíte Tuxedo Kamen?
{6412}{6490}Kdo je tenhle mu?
{6498}{6562}Naneštìstí to není známo...
{6568}{6620}Samozøejmì, Královno Beryl-sama,
{6620}{6770}Tuxedo Kamen se vdy objevil,|pokud byla Sailor Moon v nebezpeèí.
{6779}{6939}Protoe to víme, mùeme ho tak pøilákat.
{6962}{7106}Chcete vzít zpátky Duhové krystaly,|které ukradl?
{7127}{7281}Zoisite, pøipomínám, e tohle je vaše|poslední šance.
{7281}{7372}Ano, chápu to velmi jasnì.
{7372}{7425}Poèkejte, Zoisite.
{7502}{7566}Kunzite-sama!
{7628}{7717}Návnada na Tuxedo Kamena,
{7724}{7890}ale jak udríte Sailor Senshi mimo hru?
{7917}{8058}Královno Beryl-sama, dohlédnu|na tuto èást plánu.
{8069}{8111}Velmi dobøe.
{8111}{8239}Vidím, e pøede mne poloíte|všech sedm Duhovıch krystalù.
{8244}{8294}Ano, Vaše Vısosti.
{8296}{8563}{Y:i}Kunzite-sama, pro vás. Budu mít|úspìch, i kdy vsadím svùj ivot.
{8801}{8880}Ruce vzhùru! Dejte sem peníze!
{8908}{8955}Rychle sem!
{9091}{9164}Kdo... kdo jste?
{9418}{9531}Nové zprávy. Hrdinka, která se dostala|do úvodù všech zpráv,
{9532}{9645}pùvabná bojovnice Sailor Moon,|zneškodnila bankovního lupièe.
{9669}{9805}Dnes ve dvì odpoledne, gangster pøepadl|Jubanskou poboèku Tozai Banky,
{9805}{9921}støelbou ohrooval úøedníky|a poadoval vydání hotovosti.
{9921}{10009}Coe, Usagi-chan!? Nemoné!
{10022}{10088}To je... To je...
{10141}{10211}To JE událost!
{10211}{10312}To jsou øádné prázdniny dívky|z mladší vysoké školy!
{10313}{10414}Usagi-chan, pokud budeš tolik|jíst, pak pøibereš!
{10414}{10483}Ale jak se mám zastavit?
{11509}{11564}To je strašné!
{11564}{11605}Pomoc!
{12362}{12410}To je Sailor Moon!
{12410}{12458}Tak to je Sailor Moon?
{12463}{12525}Ach, ta je pìkná!
{12891}{12953}Tomu nemùu uvìøit! Ona|úmyslnì pøestøihla ty lana.
{12976}{13023}Sailor Moon.
{13109}{13214}Kdo? Kdo je ta Sailor Moon?
{13214}{13309}A kdo jsem já?
{13309}{13364}Utiš se, Usagi-chan.
{13393}{13514}V kadém pøípadì se musíme spojit s Lunou|a ostatními. A musíme ji sledovat.
{14182}{14334}Jedinì Sailor Senshi a Tuxedo Kamen|mohou sledovat takovı pøesun.
{14335}{14483}Pøijï rychle. Èekáme tì,|Tuxedo Kameni.
{14933}{15039}Jsem si jistı, e šla tudy.|Kam se ztratila?
{15052}{15132}Tak ke všemu se objevila|falešná Sailor Moon.
{15132}{15252}Skuteènì. Vidìla jsem toho|bankovního lupièe ve zprávách.
{15254}{15351}A nikdy jsem si nemyslela, e by to byla Usagi.
{15362}{15519}Doufám, e skuteèná Sailor Moon pracuje|tak tvrdì, jak jen mùe.
{15519}{15584}Bez poznámek.
{15596}{15691}Otázka je, jakı zámìr má|ta nová Sailor Moon.
{15695}{15753}Je to nepøátelskı trik,|nebo novı spojenec?
{15766}{15823}Novı spojenec?
{15839}{15929}Mùe existovat pìt Sailor, Luno?
{15990}{16049}Dobøe...
{16049}{16107}No mám nìjaké podezøení.
{16107}{16218}Protoe, pokud se ona sama|nazıvá Sailor Moon,
{16218}{16313}pak by mi mìla platit licenèní poplatky!
{16353}{16439}Tohle nepotøebujeme slyšet!
{16485}{16533}Jdeme, všechny!
{16533}{16570}Dobøe!
{17198}{17284}Ten mu! Je z Temného|království?
{17314}{17372}Ale ne! Musíme ji zachránit!
{17384}{17427}Poèkej!
{17439}{17504}To je nebezpeèné! Mùe to bıt past!
{17504}{17640}Past nebo ne! Nemùu vidìt|Sailor Moon takhle!
{17640}{17694}Máš pravdu.
{17764}{17834}Všechny, transformujme se!
{17846}{17969}Moon Prism Power - Make Up!
{18007}{18112}Mercury Power - Make Up!
{18150}{18270}Mars Power - Make Up!
{18296}{18393}Jupiter Power - Make Up!
{20499}{20567}{Y:i}Jak neuiteèná všechna ta svìtla jsou.
{20576}{20666}{Y:i}Pravá krása je v temnotì.
{20695}{20813}{Y:i}Tma Temného království pøezáøí|všechna svìtla tohoto svìta.
{20827}{20901}Pøeji si vidìt takovou|nádhernou scénu brzy.
{20943}{21009}Chci vìdìt, co to dìláte!
{21101}{21229}To je velmi špatné, vychutnávat|si svázanou a zavìšenou dívku!
{21233}{21285}Za lásku a spravedlnost,
{21285}{21365}pùvabná bojovnice v námoønickém,
{21494}{21557}Sailor Moon!
{21557}{21642}A také Sailor Mercury!
{21643}{21728}A s ní Sailor Mars!
{21737}{21836}A nakonec, Sailor Jupiter.
{21970}{22095}Ve jménu Mìsíce, ztrestáme|vás ve chvíli!
{22098}{22253}Èekal jsem vás! Jsem Kunzite, jeden|ze ètyø Lordù Temného Království.
{22265}{22418}Sailor Moon a Sailor Senshi pøipravte|se potkat svùj osud.
{22521}{22570}Coe?
{22991}{23087}Tak, co si myslíte, není|to pøekrásnı stín?
{23110}{23169}Roztomilı trik.
{23169}{23248}Fire...
{23348}{23407}Soul!
{23518}{23609}Sailor Mars, jsi nanicovatá.
{23901}{23957}Je silnı.
{23997}{24041}Dobøe?
{24108}{24165}Supreme...
{24281}{24345}Thunder!
{24446}{24528}Tvá síla byla pohlcená tou temnotou!
{24638}{24779}To má bıt ta moc Sailor Sensi!
{25993}{26053}Sailor Moon!
{26114}{26171}Není to past?
{26417}{26454}Teï!
{27655}{27724}Co to dìláte, Sailor Moon?
{27801}{27841}Zoisite!
{27841}{27895}Ach, chudinko.
{27923}{28066}Nevydríte takovou dlouhou bolest,|Tuxedo Kameni-sama.
{28066}{28116}Zoi!
{28244}{28402}Nemùete nikam utéct. Teï nastala ta|chvíle, kdy získám Duhové krystaly.
{28402}{28437}Zoi!
{28872}{28958}Ne! Jsme lapené!
{28958}{29000}Zkusím s tím nìco udìlat!
{29047}{29111}Supreme...
{29233}{29297}Thunder!
{29368}{29474}To je bez úèinku! Bariéra|pohltila veškerou sílu!
{29898}{29988}Vzdejte se. Nemùete rozbít|tuhle bariéru.
{30136}{30191}Tady, tady, tady!
{30410}{30465}A mám vás.
{30500}{30553}Zemøi!
{30628}{30684}Zoi!
{30911}{30979}Ten... tenhle mu!
{31010}{31075}Hm, máš pìknou tváø.
{31076}{31141}Ale neodpustím ti.
{31141}{31257}Pøiprav se!
{31406}{31471}Crescent...
{31474}{31531}Beam!
{31538}{31601}Ouch! To zranìní!
{31752}{31797}Co jsi zaè?
{31797}{31842}Ale ne!
{31937}{32011}Arrgh! Podvedli jste mì!
{32011}{32121}Kdekoli jste, roztrhám|vás na kusy! Arrgh!
{32476}{32568}Nemùu dıchat, Vzduch je...
{32574}{32661}Jak se vám líbí dotyk temnoty?
{32661}{32738}Kunzite-sama, pozor!
{32740}{32874}Nìjakı nepøítel je nablízku.|Právì zachránit Tuxedo Kamena.
{32886}{33008}Zoisite! Tuxedo Kamen|vám vyklouzl?
{33016}{33108}Prosím, nerozèilujte se pro to!
{33118}{33237}Tuxedo Kameni, podívej!|Tak takhle Sailor Moon zemøe!
{33255}{33329}Tuxedo Kameni!
{33523}{33676}Mùeš ji zachránit, kdy|vydáš Duhové krystaly.
{33681}{33764}Vzdej se sám, Tuxedo Kameni.
{33774}{33878}Tuxedo Kameni, nechoï.
{33878}{33939}Ne...
{33947}{33991}Sailor Moon!
{33991}{34035}Poèkejte!
{34212}{34302}Zvítìzili jsme, Kunzite-sama.|Mìl jste dobrı vıbìr.
{34302}{34380}Hodnı hoch. Nemìl jste šanci|u od zaèátku.
{34389}{34461}Nepøišel jste zápasit.
{34464}{34536}To je dùleité vìdìt, kdy se vzdáváte.
{34542}{34664}Nemáte pravdu! Není dùleité, jak tìkı je boj,|ale nikdy se nevzdávejte.
{34696}{34749}Zase ten samı hlas!
{34793}{34853}Ten hlas!
{35127}{35181}Kdo je to?
{35392}{35513}Pùvabná bojovnice v námoønickém,|Sailor Venus!
{35556}{35622}Jsem tu! Koneènì!
{35694}{35752}Crescent...
{35752}{35821}Beam!
{35939}{35988}Kunzite-sama!
{36040}{36103}Bariéra je pryè!
{36230}{36282}Sailor V!
{36282}{36346}Ty jsi Sailor V-chan, u všech všady?
{36370}{36396}Sailor...
{36401}{36438}V?
{36468}{36541}Bojovnice spravedlnosti Sailor V!
{36541}{36614}Ale její skuteèná totonost je...
{36632}{36708}Pùvabná bojovnice v námoønickém,
{36708}{36832}Sailor Venus!
{36926}{36979}Luno, dlouho jsme se nevidìli.
{36979}{37020}Artemisi!
{37057}{37190}Jak se odvaujete! Kunzite-sama, prosím jdìte!|Vyøídím to sám.
{37293}{37362}Zastavte! Zoisite, Kunzite!
{37373}{37427}Královno Beryl-sama!
{37482}{37591}U dost. Situace se|zmìnila. Vrate se.
{37636}{37683}Ale proè?
{37684}{37765}Vrate se a neodmlouvejte!
{37786}{37833}Nemáme na vıbìr.
{37833}{37880}Ale Kunzite-sama...
{37912}{38022}Sailor Senshi, zase se uvidíme.
{38184}{38257}Tuxedo Kameni!
{38278}{38327}Je pryè.
{38328}{38394}Nakonec jsme zachránìné.
{38700}{38785}Teï máme pìt bojovnic a dvì koèky|pohromadì.
{38799}{38868}To pøipomínám všem,|co tu jsou.
{38877}{38969}Sailor V, ne Sailor Venus.
{39368}{39452}Nejsi Mìsíèní princezna?
