{1}{1}15.000000
{30}{79}Já jsem Usagi Tsukino. V osmé|třídě, čtrnáct let stará.
{80}{128}Zhoubná, s krevní skupinou|0. Mým znamením je smích.
{129}{202}Hádám, že jsem trošku nemotorné a ubrečené dítě.
{203}{280}Ale jeden den jsem potkala mluvící černou kočku|jménem Luna. Tak jsem se stala Sailor Senshi.
{281}{325}A nyní mi říká abych|bojovala se zločinci.
{325}{369}Ale o tom já skutečně nic nevím.
{394}{436}No dobrá. myslím že se mi to docela daří.
{527}{579}Epizoda 4 "Lekce Usagi! Jak zhubnout."
{877}{916}Přibrala jsem!
{933}{957}To není nic divného.
{957}{1003}Když jsi mladá, je|lépe mít trochu přes váhu.
{1004}{1016}Skutečně?
{1016}{1062}Mimochodem, sníš toho tolik jako prase.
{1062}{1108}A málo cvičíš.
{1108}{1140}Málo studuješ a hodně jíš.
{1141}{1173}Pak není divu, že tloustneš.
{1192}{1233}Jak můžete říkat něco takového?
{1268}{1302}Křik nepomůže.
{1303}{1336}Musíš jíst přiměřeně.
{1347}{1381}A skutečně cvičit.
{1414}{1438}Co to kreslíš?
{1452}{1481}Usagi za šest měsíců.
{1545}{1587}Luno. Neutahuj si ze mě.
{1767}{1784}Co je špatně?
{1795}{1813}Ale nic.
{1814}{1832}Usagi.
{1844}{1880}Pokud jsi už skončila se svým obědem...
{1881}{1930}Podívej. Bylo to výborné.
{1953}{1976}Promiň.
{2001}{2035}Tak ty držíš dietu.
{2045}{2068}Vím jak je to těžké.
{2069}{2112}Zkoušela jsem to mnohokrát.
{2112}{2142}Chápeme to.
{2145}{2174}Poslouchej Usagi. Zkus plavat.
{2175}{2197}To spálí kalorie.
{2215}{2252}Ale ona není dobrá v plavání.
{2252}{2267}To vidím.
{2268}{2351}Rychlé a bombastické diety nefungujou.
{2352}{2386}Ty mám všechny vyzkoušené.
{2389}{2410}Rozumíme tomu.
{2411}{2477}Trápení v lásce je ta nejlepší dieta.
{2486}{2508}Jak můžeš mít trápení v lásce?
{2538}{2559}Pochopily jsme to.
{2559}{2584}To vidím.
{2585}{2608}Hej! Co to má znamenat?
{2609}{2643}Nic jsme tím nemyslely.
{2643}{2677}Ty to od nás sneseš.
{2677}{2713}Ty jsi ta poslední osoba|od které bych to čekala.
{2714}{2736}Opravdu?
{2737}{2759}Chceš?
{2787}{2803}Rozmlouvání o dietě.
{2814}{2849}Haruna zhubla velmi rychle.
{2850}{2868}Jak to?
{2870}{2886}Nevím jistě.
{2897}{2923}Dobrý den všem.
{3050}{3094}Nikdy nebudu vypadat takhle.
{3101}{3135}Bylo to těžké dostat se jí pod sukni.
{3139}{3152}Podívej se.
{3159}{3194}To je před...
{3195}{3230}A to je po...
{3270}{3301}A mezi snímky jsou dva dni.
{3308}{3343}Umino, kde jsi získal ty fotografie?
{3344}{3381}To je obchodní tajemství.
{3382}{3411}Kde jsi...
{3412}{3426}Co?
{3426}{3462}Kde jsi získal ty fotografie?
{3470}{3485}Pověz!
{3486}{3501}Mluv!
{3524}{3544}Stůj!
{3544}{3578}Hej, Umino!
{3644}{3677}Nemůžu jim to prozradit.
{3681}{3693}Pověz.
{3699}{3734}Dobře. Všechno řeknu.
{3735}{3780}Sledoval jsem Harunu s fotoaparátem a...
{3780}{3809}To není důležité.
{3809}{3852}Řekni, kde je ten fitness?
{3909}{3951}Tak sem Haruna chodí.
{3952}{3999}Ale nebude takový fitness velmi drahý?
{4000}{4047}Podívejte, tam to je Rie Goto, ta herečka.
{4047}{4071}To je pěkné.
{4142}{4161}Jedno kilo v jednom dni.
{4162}{4181}Pět kilo ve dvou dnech.
{4182}{4224}Za tři dni budete vypadat nádherně.
{4225}{4260}Používáme speciální postupy.
{4261}{4296}Vítejte ve fitness Shaprin.
{4296}{4332}První den je členství zadarmo.
{4332}{4360}Zadarmo?
{4361}{4391}Nevím o ničem lacinějším než zadarmo.
{4391}{4420}Pojďme.
{4476}{4513}Tolik tlustých kačen.
{4513}{4543}Jen se hrnou, když je to zadarmo.
{4580}{4607}Dobře že jsme měli tělocvičný úbor.
{4608}{4632}Nyní budeme štíhlé.
{4752}{4785}Vítejte ve fitness Shaprin.
{4802}{4823}Oách.
{4823}{4846}Překrásný...
{4847}{4867}Jsem zamilovaná.
{4874}{4910}Jsem jeden z klubových instruktorů.
{4938}{4977}Um. Jsme nové.
{4978}{5018}Tudy prosím.
{5269}{5283}Ještě mnohokrát.
{5332}{5358}Zvedneme rychlost o deset procent.
{5394}{5429}Jedno zpocení za jedno kilo|dvakrát za pět.
{5429}{5472}Po třech vám získaná krása zůstane.
{5531}{5548}Kde je Usagi?
{5566}{5608}Je právě na běžeckém stroji.
{5626}{5682}Poslouchejte. Pokud nebudete tvrdě cvičit,|nemůžete být krásné.
{5684}{5712}Tak se rodí krása.
{5714}{5747}Pravda. Krásná, krása.
{5748}{5782}Naru, budeš krásná Naru.
{5830}{5877}V pořádku, pro dnešek to stačí.
{5898}{5918}Velmi jste se snažily.
{5918}{5977}Na závěr použijeme naše|speciální zeštíhlující paprsky.
{5984}{6018}Zeštíhlující paprsky?
{6045}{6075}Jsem vyčerpaná.
{6170}{6214}Zeštíhlet, to je velmi těžká práce.
{6233}{6268}Umírám hlady.
{6408}{6442}Postavte se sem, prosím.
{6466}{6523}Tyto zeštíhlující paprsky odeberou deset kilo z plných dam.
{6523}{6580}Pokud je dáma štíhlejší, mohou|odebrat nejvýše tři kila.
{6581}{6638}To koukám. Tak takhle mohla|Haruna ztratit váhu za den.
{6638}{6652}Jdu na to.
{6653}{6667}Já také.
{6667}{6682}A já taky.
{6826}{6870}Tahle energie z mladých děvčat.
{7244}{7262}Jadeite.
{7302}{7351}Ano. Poslouchám vaše rozkazy, královno Beryl.
{7366}{7398}Jadeite, jak jste se svým plánem daleko?
{7420}{7443}Nemáme žádné problémy.
{7444}{7507}Už jsme nashromáždili nějakou energii pro Vás.
{7509}{7547}Vidím. Pokračujte ve vaší práci.
{7547}{7561}Dobře.
{7562}{7612}Tolik zoufalých žen chce|zhubnout z nerozumných příčin.
{7613}{7669}Úspěch tohoto plánu je zaručen.
{7721}{7753}Jsem tak vyčerpaná.
{7754}{7784}Tak vyčerpaná.
{7787}{7832}Vidím jak jste zkrásněly.
{7858}{7877}To mám radost.
{7902}{7918}Já také.
{7927}{7979}Pokud chcete být ještě krásnější|přijďte zítra.
{7979}{7994}Ano.
{8261}{8363}Ta energie mladých žen, které|obětují životní sílu za štíhlost.
{8793}{8827}Jak mohla Naru odejít beze mne?
{8827}{8903}Taková kamarádka to je.
{8914}{8946}Jsem tak hladová.
{8977}{8998}Hej!
{9033}{9078}Vidím, že máš výborný masový piroh.
{9146}{9187}Mamí! Bojím se!
{9215}{9256}Jak jsem se mohla zapomenout pro piroh?
{9274}{9318}Ale pořád mám hlad.
{9329}{9406}Sailor-V asi nikdy nemusela|držet dietu, aby byla štíhlá.
{9417}{9436}Dávej pozor.
{9436}{9459}Usagi, je ti špatně?
{9459}{9482}Motoki.
{9482}{9505}Cítíš se dobře?
{9505}{9521}Jo.
{9527}{9562}Nechceš dovést do nemocnice?
{9562}{9597}Ne, raději do restaurace.
{9600}{9647}Nejedla jsem od poslední večeře.
{9648}{9673}Jsem vyhladovělá.
{9726}{9743}To je sen.
{9743}{9808}Spočívat v rukou mé lásky.
{9837}{9853}Usagi.
{9854}{9891}Usagi, jsi v pořádku?
{9905}{9954}Motoki.
{9962}{10050}Nedělej si starosti. Nasytíš se energií mé lásky.
{10057}{10099}Energií lásky?
{10112}{10164}To je pravda. Energií lásky.
{10178}{10210}Motoki.
{10211}{10243}Usagi.
{10340}{10375}Jsem tak šťastná. Žila jsem pro tento den.
{10426}{10455}Usagi. Vstávej!
{10471}{10520}Teplo. Energie lásky.
{10574}{10598}Promiň.
{10599}{10637}Jsem rád, že jsi se probudila.
{10638}{10676}Proč jsi od večeře nejedla?
{10685}{10700}Dobře...
{10701}{10765}Nedala ti snad máma najíst,|protože jsi měla špatnou známku?
{10765}{10795}Ne, to ne.
{10796}{10836}Jsem hladová, protože držím dietu.
{10836}{10864}Dietu?
{10894}{10939}Co je na tom směšného?
{10947}{10969}Promiň, omlouvám se.
{10970}{11004}Já si myslím, že dietu nepotřebuješ.
{11005}{11050}Dokonce myslím, že ty můžeš vážit o něco víc.
{11055}{11093}Nelíbí se mi vychrtlá děvčata.
{11094}{11158}Myslím si, že poněkud buclatější|jsou roztomilejší.
{11163}{11192}Skutečně?
{11213}{11258}Nádhera!
{11270}{11285}Lahodné.
{11286}{11328}Masový piroh po tom všem.
{11328}{11387}Jsem mladá, tak se nemusím omezovat,|pokud chci být trochu buclatější.
{11387}{11430}Podívejme se.
{11430}{11470}Knedlíková hlava jedící piroh.
{11473}{11523}Hleď si svého!
{11524}{11578}Pokud budeš jíst tak jako teď,|bude z tebe brzo knedlík.
{11578}{11607}Nech toho!
{11607}{11636}Prima lov.
{11647}{11689}Děkuji za piroh.
{11689}{11740}O jednu míň, tolik neztloustneš.
{11740}{11764}Trhni si.
{11764}{11793}Ale měl pravdu.
{11810}{11890}Jeden piroh, jedno kilo. Dva pirohy, pět kilo,|tři pirohy a je z tebe sele.
{11890}{11921}Luno!
{11926}{11948}Bez starosti.
{11948}{12003}Pro Motokiho budu roztomilejší.
{12011}{12028}Poslouchej Usagi.
{12029}{12064}Myslím, že si to vykládáš špatně.
{12064}{12076}Co tím myslíš?
{12077}{12120}On říkal, že má rád baculatá děvčata.
{12120}{12155}Ale neříkal tlustá.
{12155}{12167}Cože?
{12169}{12206}V každém případě je to velký problém.
{12206}{12230}Jo, je to velký problém.
{12230}{12280}Kolik jich bylo? Jedna, dvě, tři, čtyři...
{12280}{12316}Snědla jsem šest pirohů!
{12316}{12353}Něco je špatně s Harunou.
{12353}{12390}Zhubla tolik a tak náhle.
{12390}{12454}Čtyři, pět, šest... Příšerné...
{12455}{12484}To není poctivé k Haruně.
{12484}{12535}Mnoho dalších dívek dochází|do fitnesscentra Sharpin.
{12535}{12572}Všechny jsou strašně štíhlé.
{12574}{12596}Tak posloucháš?
{12597}{12619}To je to! Sharpin.
{12625}{12647}Usagi.
{12653}{12711}Jestli někde mohou zformovat mé|tlusté tělo, je to Sharpin.
{12724}{12742}Počkej, Usagi.
{12742}{12782}Tam mohou být skrytí nepřátelé.
{12830}{12872}Budu štíhlá. Budu štíhlá!|Budu štíhlá. Budu štíhlá!
{12872}{12907}Budu štíhlá. Budu štíhlá! Budu štíhlá.|Budu štíhlá! Budu štíhlá. Budu štíhlá!
{12908}{12931}Budu štíhlá. Budu štíhlá!|Budu štíhlá. Budu štíhlá!
{12932}{12984}Zapomenout na to. Vůbec neposlouchala.
{13015}{13050}Tam je.
{13051}{13081}To je Haruna.
{13089}{13111}Teď je skutečně vychrtlá.
{13111}{13151}Kam to jde?
{13227}{13266}Co je za tím schodištěm?
{13303}{13334}Co je to?
{13407}{13461}Skutečně dosáhla energetického limitu.
{13464}{13493}Dnes to bude poslední extrakce.
{13494}{13540}Zvadne a zemře.
{13569}{13581}To je strašné.
{13621}{13648}Usagi!
{13663}{13692}Co to děláš?
{13722}{13755}Zlobím se na tebe.
{13764}{13795}Luno. Kam jsi utekla?
{13824}{13864}Usagi. Haruna umírá.
{13864}{13923}Haruna nezemře před tebou.
{13974}{13994}Luno.
{13995}{14019}Poslouchej mě.
{14019}{14044}Nic nezkoušej.
{14045}{14080}Poškrábu ti tváře.
{14091}{14114}Vstávej.
{14115}{14153}Haruna může zemřít.
{14153}{14192}Usagi. Transformuj se na Sailor Moon.
{14193}{14236}Ale co mám dělat?
{14236}{14272}Dělej co ti říkám. Jinak...
{14306}{14334}V pořádku.
{14335}{14370}Ale skutečně nevím co dělat.
{14371}{14442}Moon Prism Power - Make-Up!
{15066}{15099}Skoro jsme dosáhli naší plánované hladiny.
{15099}{15135}Ihned propusť Harunu.
{15135}{15147}Cože?
{15157}{15184}Klameš dívky skrz jejich sen o štíhlosti.
{15185}{15235}Nepříteli žen nemůžu prominout.
{15255}{15283}To jsi zase ty.
{15286}{15376}Já jsem Sailor Senshi,|bojovnice za lásku a spravedlnost.
{15441}{15477}Sailor Moon.
{15499}{15559}Ve jménu Měsíce, ztrestám vás!
{15577}{15617}Drzost. Dostaňte ji.
{15746}{15787}Obklíčili mě.
{15833}{15868}Rozmáčkněte ji.
{15890}{15934}Luno. Udělej něco.
{15939}{15996}Sailor Moon. Prstence na jejich|hlavách je kontrolují.
{15997}{16025}Znič je.
{16052}{16080}Ale já jsem vyděšená!
{16080}{16120}Začni s nimi bojovat a možná trochu zhubneš.
{16121}{16148}Co to?
{16149}{16194}Začni bojovat a můžeš zhubnout.
{16210}{16238}Zhubnout?
{16304}{16335}Jedno zapocení za dvě kila.
{16347}{16388}Dvě zapocení za pět kilo.
{16435}{16476}Tři zapocení a budu krásná.
{16476}{16517}Dívky trpí, když chtějí hodně zhubnout.
{16539}{16558}To je má šance.
{16787}{16864}Moon Tiara - Action!
{16913}{16948}Nemožné!
{16975}{17004}Vraťte se zpět a buďte hodnými hochy.
{17032}{17084}Co se to dělo?
{17123}{17165}Ztratila jsem pár kilo.
{17300}{17319}Jadeite.
{17319}{17370}Vaše sbírka energie je působivá.
{17371}{17427}Ten plán byl úspěšný.
{17438}{17482}Děkuji, královno Beril.
{17499}{17535}Sailor Moon musí být mrtvá.
{17624}{17639}Cítím se tak dobře.
{17640}{17676}Usagi, přinesla jsem ti osušku.
{17689}{17705}Děkuji.
{17708}{17743}Je Haruna v pořádku?
{17763}{17803}Byla pryč týden|ale teď je zpátky.
{17803}{17843}To bylo strašné.
{17849}{17896}Mámo, proč někdo zkouší podivné diety?
{17897}{17919}To je v pořádku.
{17919}{17953}Usagi bude opatrnější.
{17953}{17987}Ona nikdy nebude OK.
{18015}{18025}Vidíš.
{18033}{18082}Jak je možné, že jsem přibrala?
{18083}{18131}Všechno cvičení bylo nanic.
{18132}{18164}Proč?
{18207}{18264}Závěrečná píseň "Srdce v pohybu"
{18265}{18321}Společně jsme snili, nebo ne?
{18322}{18434}Nás chránily hvězdy
{18578}{18663}Není špatné mít přítele
{18680}{18765}S kterým mluvíš nevázaně
{18783}{18904}Byli chvíle|kdy jsem se trápila pro tebe
{18904}{19010}Chci být půvabná právě teď
{19011}{19113}Když se zamiluji, něco se změní
{19113}{19215}Zavírám své oči a ujišťuji se sama
{19215}{19327}Objala jsem tě a srdce buší
{19327}{19438}Chci ti říci o svém citu
