{1}{1}15.000000
{26}{59}Já jsem Tsukino Usagi.
{61}{123}Jistě víte, že hájím lásku a spravedlnost|jako půvabná bojovnice v námořnickém,
{123}{156}Sailor Moon! To je mé poslání!
{159}{196}Ale je to pěkně těžkej džob.
{196}{267}Musím najít legendární stříbrný krystal,|dřív než se k němu dostanou zločinci.
{268}{343}Ale nejdříve musím shromáždit|sedm Duhových krystalů.
{365}{432}Ale teď, když jsme čtyři Sailor Senshi,|pak práce půjde líp!
{528}{591}Epizoda #33|"Příchod poslední Sailor Senshi,|Sailor Venus!"
{662}{697}Připrav se potkat svůj osud,|Sailor Moon!
{753}{788}Budu s vámi bojovat, Nephrite!
{820}{847}Tuxedo Kamen-sama!
{1103}{1132}Viděla jsem dost!
{1175}{1225}Zoisite, co to má znamenat?
{1232}{1273}Mám dost takových výjevů.
{1289}{1312}Královno Beryl-sama,
{1316}{1433}Viděla jste výjev, ve kterém čarodějnice téměř|dostali Sailor Moon, ale někdo jí zachránil, že?
{1464}{1503}Myslíte Tuxedo Kamen?
{1503}{1542}Kdo je tenhle muž?
{1546}{1578}Naneštěstí to není známo...
{1581}{1607}Samozřejmě, Královno Beryl-sama,
{1607}{1682}Tuxedo Kamen se vždy objevil,|pokud byla Sailor Moon v nebezpečí.
{1687}{1767}Protože to víme, můžeme ho tak přilákat.
{1779}{1850}Chcete vzít zpátky Duhové krystaly,|které ukradl?
{1861}{1938}Zoisite, připomínám, že tohle je vaše|poslední šance.
{1938}{1983}Ano, chápu to velmi jasně.
{1984}{2010}Počkejte, Zoisite.
{2049}{2080}Kunzite-sama!
{2112}{2156}Návnada na Tuxedo Kamena,
{2160}{2243}ale jak udržíte Sailor Senshi mimo hru?
{2257}{2327}Královno Beryl-sama, dohlédnu|na tuto část plánu.
{2333}{2353}Velmi dobře.
{2354}{2417}Vidím, že přede mne položíte|všech sedm Duhových krystalů.
{2420}{2445}Ano, Vaše Výsosti.
{2446}{2580}Kunzite-sama, pro vás. Budu mít|úspěch, i když vsadím svůj život.
{2699}{2738}Ruce vzhůru! Dejte sem peníze!
{2753}{2776}Rychle sem!
{2844}{2880}Kdo... kdo jste?
{3008}{3064}Nové zprávy. Hrdinka, která se dostala|do úvodů všech zpráv,
{3065}{3121}půvabná bojovnice Sailor Moon,|zneškodnila bankovního lupiče.
{3134}{3201}Dnes ve dvě odpoledne, gangster přepadl|Jubanskou pobočku Tozai Banky,
{3201}{3259}střelbou ohrožoval úředníky|a požadoval vydání hotovosti.
{3260}{3303}Cože, Usagi-chan!? Nemožné!
{3310}{3343}To je... To je...
{3370}{3404}To JE událost!
{3405}{3455}To jsou řádné prázdniny dívky|z mladší vysoké školy!
{3456}{3506}Usagi-chan, pokud budeš tolik|jíst, pak přibereš!
{3506}{3540}Ale jak se mám zastavit?
{4054}{4081}To je strašné!
{4082}{4102}Pomoc!
{4481}{4505}To je Sailor Moon!
{4505}{4529}Tak to je Sailor Moon?
{4532}{4562}Ach, ta je pěkná!
{4746}{4777}Tomu nemůžu uvěřit! Ona|úmyslně přestřihla ty lana.
{4789}{4812}Sailor Moon.
{4855}{4907}Kdo? Kdo je ta Sailor Moon?
{4908}{4955}A kdo jsem já?
{4955}{4982}Utiš se, Usagi-chan.
{4997}{5057}V každém případě se musíme spojit s Lunou|a ostatními. A musíme ji sledovat.
{5392}{5468}Jedině Sailor Senshi a Tuxedo Kamen|mohou sledovat takový přesun.
{5469}{5542}Přijď rychle. Čekáme tě,|Tuxedo Kameni.
{5768}{5821}Jsem si jistý, že šla tudy.|Kam se ztratila?
{5828}{5867}Tak ke všemu se objevila|falešná Sailor Moon.
{5868}{5927}Skutečně. Viděla jsem toho|bankovního lupiče ve zprávách.
{5929}{5977}A nikdy jsem si nemyslela, že by to byla Usagi.
{5983}{6061}Doufám, že skutečná Sailor Moon pracuje|tak tvrdě, jak jen může.
{6061}{6093}Bez poznámek.
{6100}{6147}Otázka je, jaký záměr má|ta nová Sailor Moon.
{6149}{6178}Je to nepřátelský trik,|nebo nový spojenec?
{6185}{6213}Nový spojenec?
{6222}{6266}Může existovat pět Sailor, Luno?
{6297}{6326}Dobře...
{6327}{6355}No mám nějaké podezření.
{6356}{6411}Protože, pokud se ona sama|nazývá Sailor Moon,
{6411}{6458}pak by mi měla platit licenční poplatky!
{6479}{6521}Tohle nepotřebujeme slyšet!
{6545}{6568}Jdeme, všechny!
{6569}{6587}Dobře!
{6902}{6944}Ten muž! Je z Temného|království?
{6960}{6988}Ale ne! Musíme ji zachránit!
{6995}{7016}Počkej!
{7022}{7054}To je nebezpečné! Může to být past!
{7055}{7122}Past nebo ne! Nemůžu vidět|Sailor Moon takhle!
{7123}{7150}Máš pravdu.
{7185}{7220}Všechny, transformujme se!
{7226}{7287}Moon Prism Power - Make Up!
{7307}{7359}Mercury Power - Make Up!
{7378}{7438}Mars Power - Make Up!
{7451}{7499}Jupiter Power - Make Up!
{8554}{8587}Jak neužitečná všechna ta světla jsou.
{8592}{8637}Pravá krása je v temnotě.
{8652}{8711}Tma Temného království přezáří|všechna světla tohoto světa.
{8718}{8755}Přeji si vidět takovou|nádhernou scénu brzy.
{8776}{8809}Chci vědět, co to děláte!
{8855}{8919}To je velmi špatné, vychutnávat|si svázanou a zavěšenou dívku!
{8921}{8947}Za lásku a spravedlnost,
{8947}{8987}půvabná bojovnice v námořnickém,
{9052}{9083}Sailor Moon!
{9083}{9126}A také Sailor Mercury!
{9126}{9169}A s ní Sailor Mars!
{9173}{9223}A nakonec, Sailor Jupiter.
{9290}{9352}Ve jménu Měsíce, ztrestáme|vás ve chvíli!
{9354}{9431}Čekal jsem vás! Jsem Kunzite, jeden|ze čtyř Lordů Temného Království.
{9438}{9514}Sailor Moon a Sailor Senshi připravte|se potkat svůj osud.
{9566}{9590}Cože?
{9801}{9849}Tak, co si myslíte, není|to překrásný stín?
{9861}{9890}Roztomilý trik.
{9890}{9929}Fire...
{9980}{10009}Soul!
{10065}{10110}Sailor Mars, jsi nanicovatá.
{10257}{10284}Je silný.
{10305}{10326}Dobře?
{10360}{10388}Supreme...
{10447}{10478}Thunder!
{10529}{10570}Tvá síla byla pohlcená tou temnotou!
{10625}{10696}To má být ta moc Sailor Sensi!
{11304}{11333}Sailor Moon!
{11364}{11392}Není to past?
{11516}{11534}Teď!
{12135}{12169}Co to děláte, Sailor Moon?
{12209}{12228}Zoisite!
{12228}{12255}Ach, chudinko.
{12270}{12341}Nevydržíte takovou dlouhou bolest,|Tuxedo Kameni-sama.
{12341}{12366}Zoi!
{12430}{12509}Nemůžete nikam utéct. Teď nastala ta|chvíle, kdy získám Duhové krystaly.
{12509}{12526}Zoi!
{12745}{12787}Ne! Jsme lapené!
{12788}{12808}Zkusím s tím něco udělat!
{12832}{12864}Supreme...
{12925}{12957}Thunder!
{12993}{13045}To je bez účinku! Bariéra|pohltila veškerou sílu!
{13258}{13303}Vzdejte se. Nemůžete rozbít|tuhle bariéru.
{13377}{13404}Tady, tady, tady!
{13514}{13541}A mám vás.
{13559}{13585}Zemři!
{13623}{13651}Zoi!
{13765}{13799}Ten... tenhle muž!
{13815}{13847}Hm, máš pěknou tvář.
{13848}{13880}Ale neodpustím ti.
{13880}{13938}Připrav se!
{14013}{14045}Crescent...
{14047}{14075}Beam!
{14079}{14110}Ouch! To zranění!
{14186}{14208}Co jsi zač?
{14208}{14231}Ale ne!
{14279}{14315}Arrgh! Podvedli jste mě!
{14316}{14370}Kdekoli jste, roztrhám|vás na kusy! Arrgh!
{14548}{14594}Nemůžu dýchat, Vzduch je...
{14597}{14641}Jak se vám líbí dotyk temnoty?
{14641}{14679}Kunzite-sama, pozor!
{14681}{14747}Nějaký nepřítel je nablízku.|Právě zachránit Tuxedo Kamena.
{14754}{14814}Zoisite! Tuxedo Kamen|vám vyklouzl?
{14819}{14864}Prosím, nerozčilujte se pro to!
{14870}{14929}Tuxedo Kameni, podívej!|Tak takhle Sailor Moon zemře!
{14938}{14975}Tuxedo Kameni!
{15072}{15148}Můžeš ji zachránit, když|vydáš Duhové krystaly.
{15152}{15193}Vzdej se sám, Tuxedo Kameni.
{15198}{15250}Tuxedo Kameni, nechoď.
{15250}{15280}Ne...
{15285}{15306}Sailor Moon!
{15307}{15328}Počkejte!
{15417}{15462}Zvítězili jsme, Kunzite-sama.|Měl jste dobrý výběr.
{15462}{15501}Hodný hoch. Neměl jste šanci|už od začátku.
{15506}{15541}Nepřišel jste zápasit.
{15543}{15579}To je důležité vědět, když se vzdáváte.
{15582}{15643}Nemáte pravdu! Není důležité, jak těžký je boj,|ale nikdy se nevzdávejte.
{15659}{15686}Zase ten samý hlas!
{15708}{15738}Ten hlas!
{15875}{15902}Kdo je to?
{16008}{16068}Půvabná bojovnice v námořnickém,|Sailor Venus!
{16090}{16122}Jsem tu! Konečně!
{16159}{16188}Crescent...
{16188}{16222}Beam!
{16282}{16306}Kunzite-sama!
{16332}{16363}Bariéra je pryč!
{16427}{16453}Sailor V!
{16453}{16485}Ty jsi Sailor V-chan, u všech všady?
{16497}{16510}Sailor...
{16513}{16531}V?
{16546}{16582}Bojovnice spravedlnosti Sailor V!
{16583}{16619}Ale její skutečná totožnost je...
{16628}{16666}Půvabná bojovnice v námořnickém,
{16667}{16728}Sailor Venus!
{16776}{16802}Luno, dlouho jsme se neviděli.
{16802}{16822}Artemisi!
{16841}{16907}Jak se odvažujete! Kunzite-sama, prosím jděte!|Vyřídím to sám.
{16959}{16993}Zastavte! Zoisite, Kunzite!
{16999}{17026}Královno Beryl-sama!
{17054}{17108}Už dost. Situace se|změnila. Vraťte se.
{17131}{17154}Ale proč?
{17155}{17195}Vraťte se a neodmlouvejte!
{17206}{17229}Nemáme na výběr.
{17229}{17253}Ale Kunzite-sama...
{17269}{17324}Sailor Senshi, zase se uvidíme.
{17405}{17441}Tuxedo Kameni!
{17452}{17476}Je pryč.
{17477}{17510}Nakonec jsme zachráněné.
{17663}{17706}Teď máme pět bojovnic a dvě kočky|pohromadě.
{17713}{17747}To připomínám všem,|co tu jsou.
{17752}{17798}Sailor V, ne Sailor Venus.
{17998}{18039}Nejsi Měsíční princezna?
