{1}{1}23.976
{2230}{2308}Pøi hledání Bible Claire|jsme dosáhli hor Kataho.
{2309}{2385}Naším cílem byla známá hora|Draèí Špièák, pod kterou sídlí spousty drakù.
{2387}{2461}A tam jsme potkali|zlatého draka jménem Milgasia...
{2462}{2523}...kterı podle všeho má|nevyøízené úèty s Xellosem...
{2525}{2595}...ale pøesto souhlasil,|e mì vezme k Bibli Claire
{2596}{2652}Skvìlé! Ale na oslavu|nám nezbyl èas...
{2653}{2714}...protoe se zas ukázal náš starı|známı, Monstrum Saygram.
{2715}{2790}Dokáu dojít vèas|k Bibli Claire?
{2812}{2947}TISÍC LET STARÁ PRAVDA!|Zrádnı Temnı Draèí Pán!
{3274}{3343}Vdy ty dva není|ani poøádnì vidìt.
{3345}{3383}To je ale bitka!
{3517}{3573}Hmpf! Tohle nikam nevede!
{3574}{3651}Propáníèka. Ty si myslíš,|e mì jen tak porazíš?
{3847}{3894}Kam oba zmizeli?
{3895}{3987}Ještì stále bojují.|Jen zmìnili bitevní pole.
{3988}{4034}Tento svìt za Astrální rovinu.
{4035}{4090}To nejspíš bude moc pìknı souboj.
{4091}{4145}A teï jsme tady ve vìtším bezpeèí.
{4146}{4176}To bych netvrdil.
{4476}{4505}Dr se zpátky.
{4506}{4536}Jistì!
{4611}{4641}Co myslíš, e to je?
{4642}{4746}Nìjaké dáreèky od Seygrama!|Vypadá to, e si také zabojujeme.
{5282}{5355}U jsme tu?|Tady je Bible Claire?
{5377}{5443}Toto místo bylo stvoøeno Biblí Claire...
{5444}{5521}...pøed tisíci lety, bìhem Války Pádu Monster.
{5522}{5586}Dr se u mne, èlovìèe.
{5587}{5641}Tímhle prostorem se èasto potulují Monstra.
{5648}{5731}Jo, jo, slyším.|Nejsem zas tak hloupá, abych..
{5788}{5819}Martino!
{5820}{5860}Co tady dìláš?
{5893}{5985}Mì neuteèeš Lino!|To já získám Bibli Claire...
{5986}{6072}...a s její pomocí znovu|vybuduji království Xoana!
{6090}{6161}Martino... Tentokrát bys mìla|ustoupit a nechat to na mì, dobøe?
{6162}{6226}Co to meleš?|Ty mi USTUP!
{6227}{6260}Cos to øekla!?
{6261}{6310}Pøesnì co jsi slyšela.
{6563}{6597}Diamant!
{6740}{6760}Buïte zticha, obì dvì.
{6778}{6871}Prostory labyrintu leí|velmi blízko Astrální roviny.
{6872}{6964}Jedinı špatnı krok a budete|se tady potulovat navìky.
{6966}{7014}U takhle jsme se ztratili...
{7015}{7118}Jediná malá chybièka nás|pøece nesvede z cesty, ne?
{7119}{7159}U je pozdì!
{7299}{7336}Jen ertuji.
{7337}{7404}Pøestaò si z nás dìlat blázny|a veï nás!
{7405}{7439}Dobøe, dobøe.
{7604}{7691}U jsem pochopil,|proè ti Xellos tolik vìøí.
{7692}{7820}Ale s tebou ve známosti s Xellosem|soutìit nemohu, ne?
{7820}{7869}Stará známost s Monstrem?
{7871}{7924}Pøestaòte mì škádlit!
{7925}{7977}Nebo toho budete litovat!
{7998}{8072}Tak jsem to nemyslela...|I kdy teï to chápu...
{8073}{8137}Starı známı...
{8138}{8213}Proè myslíte, e jsem|vás dovedl tak daleko?
{8233}{8287}Proè jsem vyhovìl všemu,|co Xellos chtìl?
{8288}{8386}Co? No.. já vím, e nejste|zrovna kamarádi, ale...
{8421}{8464}Jen proto, e se ho bojím. On sám...
{9298}{9350}Pøed 1000 lety, bìhem|Války Pádu Monster, jsme se utkali...
{9352}{9471}...nìkım, kdo prakticky znièil celı|jeden draèí klan jedním prstem.
{9488}{9544}Tím soupeøem byl Xellos.
{9581}{9652}Sám dokázal znièit celı klan drakù?
{9653}{9720}Nikdy nevyzıvejte Monstrum k boji.
{9722}{9818}Není nic hloupìjšího,|ne si myslet, e jej porazíte.
{9844}{9932}Hloupìjšího?! Jene, kdo nic|neriskne, nic nevyhraje.
{9933}{9979}To jsem od tebe èekala.
{9980}{10010}Tetièko Aquo!
{10011}{10064}Tak koneènì jsi sem dorazila, Lino.
{10065}{10160}A s tebou zlatı drak.|U jsme se dlouho nevidìli.
{10161}{10197}Zas ta stará babka!
{10198}{10259}ELMEKIA LANCE!
{10489}{10516}Vyjdi, svìtlo!
{11280}{11399}Nejsou špatní! Šedı má na starosti|obranu a èervenı útok!
{11840}{11942}Jen z nás dìlají hlupáky!
{12027}{12108}Je na èase, ukázat|jim moc Spravedlnosti!
{12247}{12343}Jsem tady, protoe|jsi mi to øekla tetièko.
{12344}{12403}Tak honem. Pospìš|a dej mi mou odmìnu.
{12405}{12463}Jenom klid.|Ušla jsi dlouhou cestu.
{12466}{12508}Co jsi trochu odpoèinout|a dát si šálek èaje?
{12509}{12554}Podívej, tetièko...
{12555}{12638}Kde je Bible Claire?|Kde je ta kniha?
{12678}{12724}Nerozmyslíš si to?
{12757}{12821}Nerozmyslíš si to, Lino?
{12969}{13008}Co jsi mám rozmıšlet?
{13009}{13112}Nevím urèitì, co v Bibli Claire vlastnì najdu...
{13140}{13218}Ale urèitì vím, e to|chci všechno vidìt!
{13219}{13296}Abychom mohli všechno|tohle pøeít a vyhrát
{13321}{13371}Abychom mohli pøeít a vyhrát?
{13387}{13454}Pøesnì to jsem od tebe|èekala. Hoplá!
{13514}{13574}Asi bych ti ji mìla ukázat.
{13611}{13649}Tak jdeme! Vpøed!
{13886}{13916}To... Tohle je ono?
{13917}{14000}Ano. zdroj vìèné moudrosti.
{14001}{14060}Opravdová Bible Claire.
{14162}{14198}Ta... tak tohle je Bible Claire.
{14234}{14300}Take s tímhle dokáu|vzkøísit království Xoana!
{14332}{14382}Koneènì se moje touha naplní!
{14452}{14512}AU! Co to dìláš?
{14533}{14614}Na chvíli tu tuhle otravnou|dívku pozdrím.
{14616}{14696}Hele! Proè øíkáš, e jsem|otravná holka?!
{14710}{14769}Coe? Hej! Lino, opova se,|mì tu zase nechat!
{14958}{15042}Zdroj vìèné moudrosti...|Bible Claire...
{15067}{15121}Opravdu mi ukáe jak|porazit kadé Monstrum?
{15476}{15553}Èlovìèe...|co si pøeješ poznat?
{15778}{15814}Co to dìlá?
{15815}{15920}Linino vìdomí se pøímo|spojilo s Biblí Claire.
{15946}{16006}Bible Claire v sobì|uchovává vìdomosti...
{16007}{16066}Vodního Draèího Krále|z dob jeho zkázy.
{16068}{16130}Je naplnìna nekoneènımi znalostmi.
{16159}{16213}Co si pøeješ poznat?
{16232}{16309}Za prvé. Proè se Gaav|obrátil proti rodu Monster?
{16310}{16389}Povìz mi dùvod.|Nemùu na to pøijít
{16390}{16434}Tak tedy dobrá
{16855}{16937}Pøed tisíci lety, bìhem Války Pádu Monster...
{17038}{17122}Vodní Draèí Král, deptanı|silou Temnıch Pánù a Gaava...
{17123}{17206}...pouil zbytek své moci|k uvìznìní Pána Temnot...
{17207}{17303}...a uzavøel Gaava|do lidského tìla.
{17337}{17395}Donutil ho k znovuzrození|v lidském tìle...
{17396}{17471}...a doufal, e to postaèí ke|zlomení jeho moci Monstra.
{17497}{17551}Jenome jak se Gaav|rodil znovu a znovu...
{17552}{17605}...tak se Gaavova duše|spojila s lidskou...
{17606}{17681}... a on se obrátil|proti rodu Monster.
{17702}{17727}Další otázka.
{17730}{17810}Existuje na svìtì síla,|se kterou se dá Monstrum porazit?
{17857}{17925}Abys pøekonala moc Monstra...
{17926}{17993}...musíš pouít moc vìtší.
{17994}{18061}To u vím.|To pøece dává smysl.
{18093}{18147}Take se tì zeptám jinak.
{18211}{18255}Co víš o Temném Pánu,|vládci všech ostatních.
{18257}{18347}Všechno co víš Pánu Dìsivıch Snù.
{18369}{18404}Tak tedy dobrá...
{18613}{18710}Jeho vlastní existence je pro|tebe pøíliš tìká k pochopení.
{18711}{18808}Ale povím ti o nìm vše,|co pochopit dokáeš.
{18831}{18929}Je otcem veškeré temnoty.|Skuteènı vládce rodu Monster.
{18930}{19038}Ten kterı se snaí znovu|získat svou pùvodní podobu.
{19039}{19157}Temnota v nejtemnìjší tùní.|Hlubina jako nejhlubší noc.
{19158}{19249}Ten co záøí zlatì|nad Oceánem Chaosu.
{19284}{19396}Prázdnota uvnitø všeho.|Zdroj veškerého chaosu.
{19418}{19491}Ten co vládne dìsivım snùm
{19493}{19565}Zkrátka - Pán Dìsivıch Snù.
{19611}{19680}To poslední mi zopakuj.
{19682}{19744}Zdroj veškerého chaosu.
{19745}{19806}Ten co vládne dìsivım snùm.
{19807}{19845}Zkrátka...
{19938}{20030}...Pán Dìsivıch snù.
{20139}{20177}Já taky!
{20303}{20376}Zdroj veškerého chaosu?
{20455}{20564}Pán Dìsivıch Snù.. Ne..!|Neuvìdomila jsem si...
{20565}{20673}Umím kouzlo, které|vyvolává jeho moc?
{20694}{20744}Pak je tedy GIGA SLAVE|opravdu tím kouzlem!
{20819}{20844}Ne...
{20901}{20948}Ukate mi taky Bibli Cla...
{21098}{21172}Rád tì zas vidím,|Králi vodního draka. A taky...
{21173}{21231}...tebe Lino Inverse!
{21232}{21257}Gaav...
{21260}{21310}Dostal ses hodnì daleko.
{21329}{21431}Ano, i kdy jsem mìl spoustu|problémù, abych vás našel.
{21446}{21507}A teï nadešel èas|s tímhle vším skonèit.
{21647}{21740}Ach... tak ty ses spojil|s mım nepøítelem Hellmastrem?
{21742}{21835}Nepøípustné. My draci|od nikoho rozkazy nepøijímáme.
{21836}{21883}Tak proè tu holku chráníš?
{21923}{22018}Proè asi?|Aby mohla zùstat naivu.
{22055}{22126}To vidím.|Pak mi nedáváš na vybranou.
{22127}{22184}Má zaít nová Válka Pádu Monster?
{22187}{22256}Je na èase, aby se k vám pøidala staøena.
{22257}{22324}Vy co bojujete za ivot a za znièení.
{22341}{22403}Nakonec nezvítìzí ani jeden z vás.
{22404}{22464}Pøišel èas, abychom se rozlouèili.
{22566}{22610}Ukate mi taky Bibli Claire!
{22637}{22724}ij svùj ivot Lino v pravdì.|Buï k sobì poctivá...
{22840}{22877}TETIÈKO!
{23014}{23043}ELMEKIA LANCE!
{23285}{23306}Mám!
{23424}{23461}Gourry! Za tebou!
{23501}{23539}Gaav Flare!
{23684}{23738}Uf! Tys mì|zachránila, Amélie!
{23762}{23807}Ony dokáou|zmìnit i barvu!
{24071}{24146}Proè mi taky nemohli|ukázat Bibli Claire?
{24147}{24202}Chtìla jsem se zeptat jak|obnovit království Xoana!
{24255}{24310}Nestalo se ti nic?
{24312}{24366}Ty..Ty ses on mì bál?
{24385}{24473}Všichni jsou na mì zlí!|Lina se mohla kouknout a já ne!
{24474}{24509}Ale jdi ty...
{24534}{24594}Takovéhle hloupé|znovuobjevení jsem ještì nevidìl!
{24744}{24759}Visfan Rank!
{24866}{24894}"Spravedlnost"
{24895}{24950}Teï ochutnáte Ostøí Spravedlnosti!
{24951}{25035}Monstra, která po svìtì šíøíte jen zlo!
{25036}{25118}Vaše tìla okusí zlobu spravedlnosti!
{25305}{25364}Kouzlem soustøedila svou|moc do svıch pìstí...
{25366}{25446}...aby se mohla Monstrùm postavit|sama. Jak typické pro Amélii.
{25447}{25499}Monstrum? Támhleto?
{25569}{25642}Tyhle hraèky pøece nemùou|bıt ádnı problém!
{25643}{25694}Upøímnì øeèeno, jsou dost velkı problém.
{25696}{25746}Tak se do nich pustíme pìknì spoleènì!
{25747}{25825}Nemluv jako by to bylo jednoduché.|I kdy, ten závìr...
{25856}{25896}Astral Vine!
{26374}{26419}Victory!
{26421}{26472}Amélie! Zele!
{26525}{26552}Amélie!
{26784}{26830}AMÉLIE! Je vánì zranìná!
{26831}{26872}K èertu, Amélie!
{26874}{26914}Nehıbej s ní!
{26998}{27070}To je na nic. Hojivé kouzlo|takové zranìní nezvládne.
{27072}{27167}Silphiel...|Pokud by s námi byla Sylphiel...
{27488}{27529}Milgasio?
{27530}{27584}Pøevezmu ji.|Tohle nezvládnete.
{27664}{27707}A tetièka Aqua?
{27760}{27810}Postarej se o Amálii...
{27976}{28000}Lino!
{28021}{28054}Xellos se tu chvíli neobjeví.
{28056}{28136}Obávám se, e se ponìkud|zaneprázdnìn v jiné dimenzi.
{28138}{28210}A to znamená, e vás|mohu zabít pomalu.
{28231}{28282}"Pane dìsivıch snù..."
{28283}{28387}"Meèi temnot a chladu,|uvolòuji se ze pout nebes!"
{28388}{28448}"Spoj svou moc s tìlem mım..."
{28449}{28496}"...a znième vše co pøed námi stojí!"
{28516}{28557}"Sílo co dokáeš duše èi znièit bohy!"
{28558}{28610}RAGNA BLADE!
{28743}{28789}Teï u vím jak to pouít!
{28791}{28847}Teï, kdy z Bible Claire|vím vše o Pánu Temnot...
{28866}{28937}To kouzlo...|Tohle pøece neumíš...
{28960}{29004}Tohle je plná síla Ragna Blade!
{29119}{29198}Snad sis nemyslel,|e mi uteèeš, Seygrame?
{29199}{29233}Xellosi?
{29586}{29601}Xellosi...
{29630}{29653}Lino!
{29704}{29736}Proè jsi zasahoval?
{29737}{29823}Prosím...|Vedla sis celkem dobøe, Lino.
{29823}{29874}Jak jsem oèekával...
{30091}{30116}Zase on!
{30117}{30143}Gaav!
{30173}{30248}Jedinou ranou dokázal Démonickı|Draèí Pán, Gaav dostat Xellose!
{30249}{30314}Co teï udìláme?
