{1}{1}29.970
{270}{390}Legenda o Náramku Soumraku
{420}{539}FATAL ERROR Subtitle Team pro vás pøipravil|Projekt .hack
{539}{659}Prosím,nekamenovat za nejasnosti v pøekladu
{659}{779}Jinak Onichan neznamená Tygøík ale starší bratr,|ale nám se ten Tygøík tak zamlouval,o)
{2697}{2817}Sídlo Teroru
{2877}{2930}Je to pravdìpodobné po tom všem?
{2930}{2960}Co je?
{2960}{3020}Naše monstra se ztratila...
{3020}{3110}Ah, ten pøíbìh
{3110}{3170}To byl Pøepisovaè Dat...
{3170}{3230}Pøepisovaè Dat?
{3230}{3320}Je schopnost zrecyklování|dat té pøíšery co jí oslabí.
{3360}{3410}Ten druh schopnosti...
{3410}{3540}Je tu jedinı èlovìk, kterı|má tuto schopnost ve "Svìtì"
{3589}{3640}Je to Drak!
{3644}{3704}On je jeden z legendárních hack-s.
{3704}{3764}To jméno jsem propásl.
{3764}{3810}Co udìláš?
{3815}{3854}Budu ten, kdo bude pøekáet a potom,|a ho vymaeme, mu øeknu: "Sbohem".
{3854}{3944}Jak?
{3944}{3974}A co ta prastará oblast?
{3974}{4034}To je dobré...
{4034}{4064}Pokud ho tam nalákáme bude to jednoduché..
{4130}{4184}Ano..
{4310}{4430}Oceán je pøekrásnı!!!¨
{4460}{4527}Hej!!Co to dìláš?
{4529}{4589}Já se omlouvám. Ty jsi ten, se kterım|jsem se pøed nìjakou dobou potkal...
{4589}{4679}právì kdy  jsem myslel, e my by|jsme mohli bıt svázáni èervenou nití osudu.
{4709}{4829}Proè se nechceš dát se mnou do spolku?
{4910}{4985}Pak ít spoleènì...
{4985}{5025}*hehe :)
{5035}{5065}Jen jsem ertoval...
{5065}{5095}Vra se moje léto...
{5095}{5155}Tygøíku, èekal jsi...
{5155}{5215}Co?
{5300}{5420}Koupila jsem to v obchodì|na ulici..vypadá to dobøe?
{5450}{5489}A...jasnì!
{5489}{5580}Mùj unikátní pøedmìt je poklad|Školy plavání. Je krásnı, e ano?
{5660}{5730}Ouka øíkala, e tu za chvilku bude.
{5730}{5760}Co?!
{5870}{5990}Ty mì chceš koupit, e ano?|*no jasnì ,o)
{6000}{6040}Èekali jste dlouho?
{6040}{6100}Ouko?
{6100}{6160}Je to ta strana?
{6160}{6220}Co je špatnì, Tygøíku?
{6220}{6250}To nic...
{6250}{6280}Ty jsi si v kadém pøípadì|pøedstavoval nìco jiného, e ano?
{6280}{6370}Ouko tiše.|Co tu dìláš?
{6370}{6430}Já jsem Bago
{6430}{6459}Bago?
{6669}{6755}Sanjuro?
{6759}{6849}Reno, Shugo chtìl bych|vám nìco øíci. O samotì.
{6919}{7039}Co?
{7399}{7518}Uhh, Sanjuro?
{7518}{7608}Je "Svìt" zábavná hra?
{7608}{7649}Ano!
{7649}{7709}To je samozøejmé!
{7709}{7739}Je to tak?
{7739}{7859}Jakkoliv, je zde mnoho vìcí,|které jsou zábavné ve vašem vìku...
{7919}{7955}Co..?
{7959}{7989}Uh co...to..?
{7989}{8100}Pøeháním, je to to samé jako nedìlat nic.
{8119}{8209}Bez ohledu na to, co je to,|pokud to pøetvoøíš mùe ti to ublíit.
{8209}{8329}Ty se mnì chceš zeptat jak ti dva mohli odejít ze "Svìta"?
{8359}{8479}Jedinı kdo øekl, e soumrak|pøichází si byl ty!
{8479}{8585}Drakovu...ne, Schugovu sílu by jsme mohly potøebovat?
{8588}{8620}Opravdu...
{8632}{8692}Tohle je hra!
{8692}{8780}Uivatelé tu z toho mají poitek...
{8800}{8920}dokonce i pøi minimu pravidel|není zde ádná povinnost nebo zodpovìdnost.
{8950}{8995}Nicménì...
{8995}{9055}Pokud to nechtìjí, nemùeme se|jim míchat do jakıchkoliv situací.
{9085}{9205}Tady jsou hráèi, kteøí se stanou|"ubohımi", to bude komplikované.
{9355}{9470}Proè máme chtít opustit "Svìt"?
{9475}{9564}Nìkdo koho znám je hluboko uvnitø "Svìta"...
{9564}{9684}-a opustil jeho skuteènı svìt funkcí.
{9684}{9745}Já jsem byl jen trochu ustaranı.
{9745}{9891}To je v poøádku.|My jsme rozpoznali ten rozdíl.
{9892}{9910}Jasnì!
{9912}{9942}To je skvìlé rozhodnutí.
{9942}{10080}V tom pøípadì zvítìzil nápad|pro tuto chvíli zmizet ze "Svìta"
{10080}{10200}A se vrátíte moná, e byste mohli| najít nìco více osvìujícího.
{10200}{10320}Pro tohle osvìující zkoumání. Chtìl|bych se stát o mnoho a mnoho silnìjším
{10350}{10435} Viïte, e ano...Mistøe?
{10438}{10527}Mistøe?
{10527}{10587}Mistøe. Nebo dáváte pøednost Sensei?
{10587}{10647}Mistr? -Jistì!|Sensei? -Jistì!
{10647}{10737}Zní to pøekrásnì.
{10737}{10827}Jakkoliv my máme ještì spoustu|úkolù, které jsme nesplnili.
{10923}{10955}Úkoly?
{10957}{11120}Jasnì. Kdy jsem poprvé hrál s|touto postavou, objevila se dívka v bílém a..
{11120}{11240}..tenhle náramek..
{11360}{11480}Pøepisovaè Dat...
{11480}{11569}Poádala mne abych zachránil tento "Svìt".
{11569}{11689}To je ..Aura?
{11689}{11749}Nezáleí na tom co øekla,|my jsme postavy hackers., e ano?
{11749}{11869}Já si myslím, e tu je úkol|pro limitovanou edici.
{11869}{11959}Já myslím ,e tohle normální|hráè nemùe vyzkoušet.
{11959}{12051}Jako monstra, která neumírají tak snadno...
{12051}{12111}Pravda.. pravda.
{12111}{12171}Chtìjí to pro sebe, nemohu je nechat|zamíchat do nìjakıch zkoušek.
{12371}{12491}Pokud se cokoliv stane kontaktujte mne kdykoliv.
{12491}{12580}Nezaleí na tom jak to bude triviálnì vypadat.
{12580}{12640}Dokonce s oblastí, se kterou nejsi obeznámen.
{12640}{12730}Pokud ucítíte nìco nebezpeèného nezpøístupòujte to.
{12760}{12820}Není nezbytnì nutné vyøešit úkol.
{12820}{12880}Ale...
{12880}{12940}"Svìt"existuje pro radost ze hry.
{12940}{13030}Není to místo, kde musíš|nasadit svùj ivot.
{13030}{13150}Co tím opravdu myslel?
{13150}{13270}Tøeba, abysme hráli kadı|den jen jednu hodinu?
{13270}{13360}Kázání mnì trápí...
{13360}{13420}Myslíš si, e Sanjuro je|v opravdovém ivotì uèitel?
{13509}{13629}Není to krásné?|Jenom malou chvilku?
{13629}{13720}Dej to zpìt. Ten míè je první|unikátní pøedmìt kterı jsem získala.
{13729}{13849}-Zkus si ho vzít. Zkus si ho vzít|-To je dobré.
{13849}{13939}Tohle nemùete dìlat!
{13969}{14069}Ona je dìvèe.|Není vám to blbé?
{14069}{14110}Vra ten míè zpìt!
{14110}{14140}Hej,hej,hej
{14140}{14200}Jsou to silní nepøátelé?
{14200}{14260}To je nebezpeèné.|Jsou to oni?
{14260}{14290}Hej!|Dám ti to zpátky!
{14290}{14440}Dobøe, potkáme se znovu!|Oba!
{14440}{14499}Je mi jen 14!
{14499}{14589}Mùj míè...
{14589}{14709}Jasnì..|*ha další zub odhalen ,o)
{14709}{14769}Jsi v poøádku? Kluci jsou jak vlci.|Nesmíš si to tak brát.
{14769}{14889}Holky jsou taky vlci.
{15069}{15119}Dìkuji.
{15119}{15149}Ne...je to povinnost.
{15239}{15281}Co?
{15336}{15380}Udìlala jsi to?
{15381}{15420}Je to snadné vítìzství.
{15420}{15500}Dokázala jsi to.|Dostali jsme Èlenskou adresu.
{15500}{15590}Tak to zaènem
{15590}{15650}Plán na eliminovaní hackers.
{15745}{15865}Jsem zpátky...!
{15925}{16045}Pošta?
{16165}{16285}Co?!
{16435}{16500}Co teï..?
{16500}{16560}Pomoz...mi...
{16560}{16590}Oblast
{16590}{16680}prokletı...zabíjí...
{16680}{16740}Nemohu to pøeèíst.
{16740}{16860}Prokletı...èarodìj... vraedné sídlo...
{16860}{16980}To je tak, jak to bylo napsané?
{16980}{17040}S mım unikátním pøedmìtem| dekóduju znièené vìci ze "Svìta"..
{17040}{17130}Já jsem dekódovala jméno té oblasti, ale...
{17130}{17220}...ale?
{17220}{17300}Textová èást toho je opravdu hodnì poškozená...
{17300}{17370}Nemohla jsem pøeloit celé vìty..
{17370}{17490}Ale, víme kde je ta oblast,|kde ta  dívka je...
{17509}{17629}Pospìšme si a ji zachráníme.
{17629}{17749}Jane..!Moje ruce jsou ztuhlé...
{17749}{17839}Pošta od Aury....
{17839}{17959}To nemùe bıt...!
{17989}{18109}Prokleté zabijácké sídlo za moøem a smaragdovımi listy!
{18678}{18728}Je to tady...?
{18728}{18812}Na tom nezáleí cítím, e nìco pøijde ...
{18812}{18902}Já cítím unikátní pøedmìty!
{18967}{19020}Reno? Je nìco v nepoøádku?
{19020}{19080}Ne..opravdu...
{19080}{19140}Nepøestaò ani na moment bıt|tam dole ve støehu, Shugo!
{19140}{19260}Já vím jsem pøipraven|Sanjuro!
{19260}{19320}Dobøe!|Tak pojïme všichni!
{19649}{19769}FATAL ERROR Subtitle Team pro vás|pøipravil Projekt .hack
{19799}{19919}titulky jsou neoficiální |a jen pro vnitøní pouití FATAL ERROR
{20109}{20229}Ten jas odhaluje mé nitro...
{20229}{20275}Pane Barmunku...
{20275}{20335}Reki. Obnova tohohle|místa je kompletní.
{20335}{20425}"Pro teï" já...
{20425}{20539}To není "pro teï"...|je zde pøe 200 nespokojenıch tvrzení...
{20539}{20659}Všechen personál..|je pøipraven se vzdát volného dne, ale..
{20659}{20749}ale poadují zvıšení, "pro teï"
{20749}{20806}Tato oblast má neobvyklı základ...
{20806}{20866}...je to prostá shoda okolností?
{20866}{20926}Reki!|Ano.
{20926}{20986}Já tì tu opustím.
{20986}{21046}Musím teï nìkam jít.
{21196}{21316}To vy jste pøedìlávali|tyto data, e ano?
{21316}{21376}Ve jménu Rytíøù Války vás zatıkám!
{21424}{21535}To je neuctivé.|Kdo si myslíte, e je tento èlovìk?
{21535}{21565}Já nevím.
{21567}{21600}Ty opravdu nevíš?
{21600}{21625}Já nevím.
{21625}{21675}Nedìlej si znovu srandu!
{21675}{21720}Kdy nevím tak nevím.
{21769}{21805}Dejte svoje meèe pryè!
{21850}{21950}Tito lidé jsou správci systému.
{21980}{22055}Kamui...
{22055}{22115}Barmunk..
{22540}{22600}Proè jsi tady?
{22650}{22790}Toto je jen sluba Rytíøù Války.|Udret mír a poøádek ve "Svìtì".
{22800}{22920}Dobøe jdeme na další místo.
{22920}{23010}Právo a mír je udren|na tomto serveru.
{23010}{23100}Jak to? V poslední dobì to vypadá,|e ze narùstají problémy..
{23220}{23340}Barmunk z Modrıch vıšin |je pøíliš mìkkı na uivatele.
{23340}{23460}nemùeš øíct,... |e se zde vyskytují velké potíe.
{23519}{23639}Dobøe pouijeme sousedství|pro naši základnu.
{23789}{23909}Nejsou tito Rytíøi Války podivní?
{23909}{23999}Jediní, kteøí vymaou nepoctivé|osoby  bez jakéhokoliv prominutí.
{23999}{24089}CC skupina ze systémové základny.|Jednotka okamitého dohledu veøejného míru.
{24119}{24239}Jsou to skupinovı psi.
{24508}{24628}Ta dívka je nìkde v tomto sídle.
{24628}{24700}Unikátní pøedmìt. Unikátní pøedmìt.
{24700}{24730}Kde jsou monstra?
{24860}{24910}Jsi hladová?
{24940}{25030}Teï to vypadalo jako, e|ti kruèí v bøiše, e ano?
{25270}{25390}Vypadá to jako... jídelna.
{25709}{25740}Je to brouk.
{25740}{25770}Já jsem lekla.
{25770}{25900}Tøeba Rena je ten typ|kterı se snadno lekne?
{25900}{26100}Teï, kdy na to myslím, ona se pokadé vylekala,|kdy bylo v televizi nìco strašidelného.
{26100}{26165}Kdy se zamyslím...
{26165}{26195}Neboj se!|Jsem hned vedle tebe!
{26195}{26270}To nám dìlá víc a víc starostí...
{26305}{26395}Je to v pohodì tohle místo|je absolutnì v poøádku.
{26395}{26484}A to sebevíc vypadá|reálnì je to pouze hra.
{26484}{26604}Nebuï nerozumná.|Jsem hned vedle tebe.
{26604}{26694}Tygøíku Dívej se na Renu,|která se nebojí nièeho.
{26694}{26730}Reno!
{26730}{26760}Poèkej na nás nechoï sama!
{26860}{26980}Je to tak... Rena je ten|typ, kterı se poleká?
{26980}{27070}Budu sledovat Renu a ostatní|kam pùjdou v této arénì.
{27070}{27160}Mìlo to cenu, e jsem|pøišel pøed nimi.
{27160}{27280}Hmmm pøekrásná situace.
{27310}{27430}Já se bojím!
{27430}{27519}Reno
{27519}{27609}Komiyamo, ty jsi tak krásnı.
{27849}{27969}Uhh..|Kterou cestou se dám?
{27969}{28089}Nesnáším to. Proè tu nikdo není.|Øíkala jsem jim a mnì následují...
{28179}{28299}To není ádná pomoc?
{28299}{28359}Dobøe, to je v poøádku.|Tento "Svìt" byl stvoøen...
{28478}{28598}Reno!
{28598}{28628}Reno....
{28958}{29040}Reno....
{29040}{29090}Nepøibliuj se!!!
{29090}{29120}Nenávidím to!|Nenávidím to! Nenávidím to!
{29340}{29460}Nenávidím to!
{29579}{29699}Ten zvuk pøicházel odtud?
{29699}{29759}Rena je v poøádku, e ano?
{29759}{29849}Neztrate hlavu! Je nebezpeèné se|procházet  sám touto arénou a vy to nevíte.!
{29879}{29999}Pojïme ji najít!
{30269}{30389}Tak to jsou opravdová... monstra!
{30718}{30838}Dostali je.
{30838}{30898}Proè tu není skøíòka s pokladem,|kdy dostali ty pøíšery?
{31408}{31527}Tygøíku?
{31527}{31617}Kam všichni zmizeli?
{31647}{31767}Kde je.. vıchod?
{31767}{31887}Bylo by lepší kdybych|nepøedstírala, e jsem silná...
{31947}{32067}Co..?
{32516}{32636}Nemám to tady ráda...
{32936}{33056}Nìkdo... otevøete!!
{33416}{33535}Chtìla jsem zavolat Draka...
{33535}{33625}Ale ten kdo se chytil do pasti je...
{33625}{33685}Èerná Rùe!
{33895}{34015}Opravdu musíte je zabít nìkolikrát...
{34015}{34075}Bakudon!
{34105}{34225}Tihle chlápci nevypadají|jako jednoduchá monstra!
{34315}{34435}Shugo!|Najdi Renu a pøiveï ji sem!
{34435}{34494}Pùjdem k vıchodu z této oblasti.
{34494}{34614}Ano!
{34614}{34734}Reno?
{35124}{35224}P..proè..
{35224}{35284}Jen jedním úderem...
{35553}{35673}Tygøíku...
{35673}{35733}Reno!Hned tì uzdravím.
{35733}{35823}Ty nemùeš,Tygøíku...
{35823}{35930}Ta vìc..vypadá jako pøedtím..|je to monstrum, které neumírá snadno..
{35973}{36093}To je proè...
{36093}{36213}Reno!
{36393}{36512}Pøepisovè Dat!!!
{36752}{36777}Reno!
{36811}{36840}Reno!!
{36840}{36900}Uzdrav ji rychle!!
{37060}{37150}Obnovení!
{37150}{37200}Proè?
{37200}{37260}Obnova!|*no doslovnì je to olistìní, ale ona není strom
{37260}{37320}Proè to nechce poslouchat?
{37320}{37380}Reno!
{37380}{37439}Tygøíku...
{37439}{37499}Reno!
{37499}{37589}Tygøíku..
{37589}{37679}Reno!
{37679}{37739}Tygøíku...
{37739}{37829}Reno...
{38324}{38421}Renoooooooooooooo...!!!
{39259}{39300}-V dalším dílu-