{1}{1}25.000|717 992 430 alebo 639 855 104 bytov
{250}{350}Kdy jsem byl malı,|mùj otec byl slavnı.
{350}{450}Byl to ten nejlepší samuraj v øíši.
{450}{550}To on sal hlavu Šógunovi.
{550}{812}Podle Šóguna sal hlavu|stotøicetijedna Šógunovıch muù.
{875}{1000}To byly zlé èasy pro øíši.
{1000}{1150}Šógun zùstával uzavøen ve svém hradu|ze kterého nikdy nevycházel.
{1150}{1250}Lidé se zaèali domnívat,|jeho mysl ovládli ïáblové
{1250}{1350}a e je øízen zlem.
{1350}{1486}Šógun øekl,|e mu lidé nejsou oddáni.
{1625}{1675}Tvrdil, e má mnoho nepøátel
{1675}{1784}a proto zabil mnoho lidí.
{1900}{2000}To byla zlá doba.
{2000}{2086}Všichni ili ve strachu.
{2200}{2300}Ale pøesto všechno,|my jsme byli šastni.
{2300}{2400}Mùj otec pøicházel domù|k mojí matce,
{2400}{2475}a kdy jí vidìl,|zapomínal na všechno špatné.
{2475}{2597}Mìl hrùzu ze Šóguna,|ale ten jí mìl zase z nìho.
{2597}{2619}- Mùj mui...
{2619}{2730}- A právì moná v tom byl problém.
{2786}{2821}- Azami
{2900}{2975}- Mìla jsem zlı sen...
{2975}{3025}- Neboj se.
{3025}{3125}Zlé sny jsou pouze sny.
{3125}{3233}Do jaké doby ses to narodil,|Dajgoro...
{3325}{3425}Té noci nám matka zpívala.
{3425}{3525}Otec šel do své svatynì,|aby se tam modlil za klid a pokoj.
{3525}{3625}Modlil se, aby se vìci zlepšily.
{3625}{3750}Tenkrát, jedné noci...
{3750}{3925}Šógun poslal svoje nindovské|špióny do našeho domu.
{3925}{4025}Oèekával od nich,|e zabijí mého otce.
{4025}{4155}Ale oni to neudìlali.
{4225}{4325}To byla ta noc, kdy se|úplnì všechno zmìnilo.
{4325}{4375}Navdy.
{4375}{4400}- Azami...
{4400}{4550}Azami!
{4550}{4600}Azami...
{4600}{4625}Azami...
{4625}{4675}Tvùj sen se musel uskuteènit...
{4675}{4725}- Daj... Dajgoro...
{4725}{4875}Musíš peèovat o našeho syna...
{4875}{5000}Za to mi zaplatí...
{5000}{5111}... potoky svojí krve!
{5225}{5325}To bylo tehdy, kdy mùj otec|opustil samurajskı ivot,
{5325}{5444}a stal se démonem.
{5450}{5500}Stal se nájemnım vrahem.
{5500}{5650}Procházel zemí...
{5650}{5684}a vzal mì s sebou.
{5950}{6125}Sám si vìtšinu toho všeho|nepamatuji.
{6125}{6200}Jediné co si pamatuji je to,
{6200}{6300}e nás šógunovi nindové pronásledovali|všude, kamkoli jsme šli.
{6300}{6350}A padající tìla...
{6350}{6388}a krev...
{7050}{7100}- Jsi oznaèen smrtí
{7100}{7175}kamkoli pùjdeš, nemùeš uniknout,
{7175}{7325}Šógunovi neuteèeš.
{7325}{7526}VRADA ŠÓGUNA
{7925}{8025}Mùj otec toho nikdy moc nenamluvil.
{8025}{8125}Kadı den jsme se dostali|o kousek dál,
{8125}{8200}a na noc jsme rozdìlali oheò,
{8200}{8275}udìlali bylinnı èaj
{8275}{8325}a poslouchali,|jestli neuslyšíme nindi.
{8325}{8400}Vdy jsme byli naprosto ticho.
{8400}{8475}Nìkdy mi otec vyprávìl o minulosti...
{8475}{8550}a o matce...
{8550}{8610}Snail jsem se na to nemyslet.
{8675}{8750}Ale mùj otec si nìkdy|nedokázal pomoci...
{8750}{8850}Obèas se ztrácel
{8850}{8925}v minulosti.
{9075}{9150}- Dajgoro.
{9150}{9250}Rozhodni to, jestli uprchnout
{9250}{9300}nebo válèit s Šógunem.
{9300}{9375}Dneškem nastoupím cestu do pekla.
{9375}{9523}Ale ty si vybereš|svojí vlastní cestu.
{9900}{9950}Take...
{9950}{10050}- Brzy moná uvidíš nebe.
{10050}{10100}Vyber meè
{10100}{10175}a pøipojíš se ke mnì.
{10175}{10225}Vyber míè
{10225}{10300}a pøipojíš se ke svojí mrtvé matce.
{10300}{10451}Nerozumíš mım slovùm,|ale musíš si vybrat.
{10625}{10675}- Take...
{10675}{10716}Pojï chlapèe.
{10727}{10790}Vyber ivot nebo smrt.
{11800}{11900}- Tvoje matka... by byla šastná.
{11900}{12000}Mùj vlastní syn porazí Šóguna!
{12000}{12127}Ty jsi moje dítì.
{12175}{12277}Vrah se synem!
{12400}{12450}- Z rozkazu našeho pána - Šóguna,
{12450}{12500}ve jménu našeho vládce Gonigi,|syna nebes
{12500}{12550}Máš nyní dvì monosti:
{12550}{12600}buï budeš pøísahat nekoneènou|oddanost svému pánovi
{12600}{12739}nebo i se svım synem spácháš harakiri.
{13000}{13075}- Mılíš se.
{13075}{13149}Mám ještì tøetí monost.
{13250}{13300}- Ty šílenèe!
{13300}{13357}Rozkazujeme ti!
{13400}{13450}- Stráe!!
{13450}{13500}Odpírá poslušnost Šógunovi!|Stráe!!
{13500}{13525}- Stráe!
{13525}{13550}- Zastavte ho!
{13550}{13600}Zadrte ho!
{13600}{13650}Na co èekáte??|Zabíte ho!
{13650}{13751}Copak nevidíte, e je to ïábel??|Zabíte ho!!
{15325}{15400}- Munedwane,|ukloò se pøed svım Šógunem!
{15400}{15475}Víme, e jsi v pasti.
{15475}{15550}Nikdy nemùeš uprchnout
{15550}{15600}svému osudu.
{15600}{15700}Podstup se ctí -
{15700}{15800}souboj s mojim synem, pánem Kurando.
{15800}{15875}- Proè nepøijmeš vızvu?
{15875}{15925}Pokud vyhraješ -
{15925}{16025}Šógun u tì nikdy nebude|zvát k boji.
{16025}{16050}Co ty na to?
{16050}{16150}- Pøijmi nabídku...
{16150}{16250}nebo tu zemøi.
{16250}{16294}Hned.
{16325}{16375}Pora mého syna|ve spravedlivém souboji,
{16375}{16519}a získáš svojí svobodu.
{16525}{16592}- Souhlasím.
{16800}{16900}Mùj syn, Kurando,|tì zabije jako dobytek
{16900}{17025}i s tim tvım malım parchantem.
{17025}{17150}Moje strategie nesele,
{17150}{17200}však se ukáe...
{17200}{17300}Slunce na nebesích,
{17300}{17400}oslep oèi tohoto mue - Vlka!
{17400}{17450}Le, Kurando, mùj chlapèe.
{17450}{17542}Le ke slávì!
{18825}{18900}Obèas jsme pøišli do mìsta.
{18900}{18936}Ale to pro nás nebylo dobré,
{18958}{19029}protoe jsme nebyli jako ostatní lidé.
{19042}{19095}Mìsta jsou nebezpeèná.
{19095}{19192}Šógunovi nindové jsou všude.
{19175}{19225}- Naše pokoje jsou hezké,
{19225}{19275}a máme horkou koupel.
{19275}{19350}Kadı mohl bıt ninda.
{19350}{19425}Dokonce i hezká ena|nebo milá paní.
{19425}{19525}A vy nikdy nevíte kdo.
{19525}{19550}- Hej.
{19575}{19650}Óó, jak sladkı.|Óóh, pane!
{19650}{19775}Dìkuji, velice dìkuji.
{19775}{19850}Smím vzít vozík dovnitø?
{19850}{19900}Mùete jít dovnitø, prosím?|Díky.
{19900}{19975}Ale obèas musíte podstoupit riziko,
{19975}{20075}chcete-li se vykoupat.
{20075}{20160}- Opláchni si nohy.
{20175}{20200}Prosím.
{20200}{20225}- Matsu!
{20225}{20268}- Ano?
{20275}{20375}- Matsu! Co to dìláš ty hloupá?!
{20375}{20425}Ten èlovìk je obyèejnı ebrák!
{20425}{20475}- Ale my máme pøeci volné místo!
{20475}{20575}- Copak sis neuvìdomila,|e je to samuraj?
{20575}{20600}Zpùsobí nám problémy.
{20600}{20650}Nebude mít èím zaplatit,|a pak zpùsobí vıtrnosti!
{20650}{20771}To pro nás bude nebezpeèné!
{21225}{21300}-Je mi to tak líto pane,|bylo to nedorozumìní.
{21300}{21325}U nemáme ádné...
{21325}{21350}- Mohu zaplatit hned?
{21350}{21375}- ?
{21375}{21450}- Mùete to ponechat u sebe?
{21450}{21500}Tisíc zlatıch kusù.
{21500}{21550}- Tolik?!
{21550}{21600}- Doufám, e to bude staèit.
{21600}{21650}- Velice dìkuji!|Jsem vám naprosto k dispozici!
{21650}{21775}Dìkuji!
{21775}{21850}Matsu, ty mizerná sluebná!
{21850}{21925}Je tøeba jim umıt nohy!
{21925}{22025}- Pane mùj...!|Óó, to je malı silnı samurajskı chlapeèek!
{22025}{22105}Dovol, abych ti|osušil noièky.
{22310}{22373}- Dìkuji.
{25050}{25121}- Mùeme jít?
{25525}{25600}Vìtšinu èasu jsme chodili.
{25600}{25650}Je to tak bezpeènìjší.
{25650}{25725}Vıchova je pøi tom obtíná.
{25725}{25775}Pouze stejné vìci
{25775}{25900}a poøád hledáte nindi.
{25900}{25975}Obèas jsem usnul.
{25975}{26050}Ale mùj otec nikdy.
{26050}{26125}To bylo dobøe.|Protoe, kdy jsem jednou usnul,
{26125}{26283}Šógun poslal svoje samuraje pro mì.
{26325}{26375}- Vrahu, uka se!
{26375}{26450}To je pán Bizen, tvùj starı kamarád.
{26450}{26500}Pøináším zprávu od mého otce,
{26500}{26550}tvého pøedchozího pána.
{26550}{26675}Vyhrál jsi svojí svobodu,|ale ne svobodu svého syna.
{26675}{26775}Smrtí svého syna|zaplatíš za svoje chyby - zloèin.
{26775}{26925}Pomalá smrt tvého syna|bude vıstrahou pro ostatní.
{26925}{26975}Kde je?
{26975}{27077}Otoète ho!
{27125}{27251}Pøiprav se, e budeš svìdkem|jeho konce.
{27290}{27350}- Brnìní?! Tolik se ho bojíte?!
{27350}{27449}- On je synem šíleného Vlka.
{27650}{27713}- Zabijte ho!
{28500}{28550}- Bizene, mùj synu!
{28550}{28675}Ty neškodnı hlupáku!|Vlk tì pošle do tvého hrobu!
{28675}{28800}Ale riskoval bych ivoty všech svıch synù,
{28800}{28931}abych vidìl jeho hlavu na kùlu.
{29025}{29130}Sbohem, mùj synu.
{29275}{29300}- Ty!
{29300}{29425}- Poslouchej mì, Vlka Samotáøe.
{29425}{29525}Chci tvojí hlavu.
{29525}{29600}- Nemùeš mnì zabít.|Mám nesmrtelnou sílu,
{29600}{29675}která tì znièí!!
{29675}{29800}- Budi ty i tvùj syn prokleti!
{29800}{29875}Navdy!
{29875}{29975}- Posílej si svoje nindi!|Všechny je zabiju!
{30075}{30225}- Já, pán Kuragawa, i moje|skupina nindù, tì zdraví.
{30225}{30350}Naslouchej pøáním Šóguna.
{30350}{30475}- Moje ninda - eny ijí jenom proto,|aby plnily pøání našeho pána Šóguna.
{30475}{30525}- Pronásledujeme mue,|kterı se nazıvá Vlk Samotáø,
{30525}{30600}a kterı se stal stínem na slávì Šógunovì.
{30600}{30700}- Jakı byl vısledek souboje?
{30700}{30745}- Hroznı.
{30840}{30877}- Zrádce!
{30975}{31075}Øekni mi, prosím... Co mùeme dìlat??
{31075}{31175}- Máme rozkaz ho zabít.|To nebude lehké.
{31175}{31225}- Jsi hlupák!
{31225}{31350}- Moná jenom podle Vás je vyøízení|Vlka Samotáøe jenom hraèkou.
{31350}{31471}- Chceš nìco vidìt?
{31975}{32025}To jsou tvoji mui?
{32025}{32075}- Ano.
{32075}{32175}- Uka mi tvého nejsilnìjšího mue.
{32175}{32275}- Junai.
{32850}{32975}- Junaii, zkus najít cestu z místnosti.
{32975}{33073}Zkus uprchnout z místnosti!
{34625}{34798}To je tvùj nejlepší mu?!|Moc se nehıbe!
{35125}{35257}- To moje eny ho popraví.
{35750}{35850}Na cestì jsme se zastavili|v mnoha svatyních,
{35850}{35994}abychom se pomodlili za duše zemøelıch.
{36025}{36176}Bylo tìké zbavit mého otce svobody.
{36225}{36275}Potom si ho najmuli, aby nìkoho zabil.
{36275}{36375}Báli se toti, e oni sami budou zabiti.
{36375}{36605}Na bránu chrámu nakreslili obrázek vlka.
{36625}{36784}Mùj otec jim zanechal znamení.
{37075}{37200}Poté se v tajnosti sešli.
{37925}{37975}- Znamení!
{37975}{38025}- Znak na silnici!
{38025}{38204}- Vlk Samotáø musí bıt zde.
{38500}{38575}- Jsem Hirado, vùdce klanu Hirogo.
{38575}{38650}Slyšeli jsme, e zabiješ|mue pro peníze.
{38650}{38775}- Mì nazıvají Vlk Samotáø,|Vrah se synem.
{38775}{38850}- Ve skuteènosti to tak øíkají.
{38850}{39017}Ale budeš mi muset ukázat nìco,|co by mì utvrdilo, e je to pravda.
{40025}{40154}- Moná ho poslal Šógun.
{40175}{40268}Je to dostateènı dùkaz?
{40350}{40416}Meè.
{41125}{41200}Spiklenci, nyní pokroème.
{41200}{41322}- Pøineste peníze.
{41600}{41675}Zkontroluj si to prosím.
{41675}{41817}Jeden tisíc kusù zlata.
{42000}{42075}Potøebujeme tvojí pomoc.
{42075}{42175}Lidé z mého klanu jsou hrdí|a oddaní Šógunovi.
{42175}{42225}Danì jsou velké.
{42225}{42325}Zabírá 2/3 úrody, ale i pøesto|si myslí, e ho podvádíme.
{42325}{42425}Kvùli tomu poslal svého|fanatického bratra, pána Kiru,
{42425}{42623}aby mezi naše bratry proniklo|mnoho nindù - špiónù.
{42700}{42775}Šógunovi bratøi jsou v|tìchto metodách experty.
{42775}{42950}Jeho nindové terorizují naše lidi v noci,|strašíce je svımi metodami muèení.
{42950}{43050}Pravdìpodobnì i nyní|podávají zprávy Kirovi.
{43050}{43200}A co hùø.|Šógun vyslal zvláštní eskortu lodí,
{43200}{43250}aby pøivezla Kiru bezpeènì zpìt domù.
{43250}{43350}Tøi bratøi zvaní "Vládci Smrti".
{43350}{43400}U si o nich mohl slyšet.
{43400}{43500}Jeden z bratrù pouívá hák.
{43500}{43550}Druhı bojuje s kyjem.
{43550}{43700}Tøetí pouívá eleznıch pìstí.
{43700}{43800}Spoleènì u zabili mnoho muù.
{43800}{43875}ádáme tì,|aby jsi zabil pána Kiru døíve
{43875}{43950}ne jejich eskorta|pøekroèí naše hranice.
{43950}{44175}Nech jsou s tebou naše modlitby,|aby jsi byl ve svém poslání úspìšnı.
{44175}{44300}Doufáme, e neseleš.
{44300}{44497}Budoucnost našeho klanu závisí na tobì.
{44800}{44850}Kdy jsme zapoèali tuto misi,
{44850}{45000}poèítal jsem, kolik nindù|mùj otec zabil.
{45000}{45050}Øíkal mi, abych nepoèítal,
{45050}{45150}ale abych se pouze modlil za duše.
{45150}{45200}Ale kdybych nepoèítal,
{45200}{45300}nevìdìl bych, za kolik duší se mám modlit.
{45300}{45401}A tak jsem poèítal.
{45475}{45667}Dohromady to je tøista ètyøicet dva.
{46350}{46523}Tøista ètyøicet... pìt.
{48300}{48358}- Dajgoro!
{51100}{51182}- Já jsem prvotøídní ninda!
{55050}{55093}- Dajgoro, jeï!
{59050}{59188}- Otèe? Potøebuju tì.
{59250}{59300}- Potkali jsme Vlka Samotáøe.
{59300}{59400}Nyní mohu oèekávat, e|proti nìmu pouiješ svoje jednotky.
{59400}{59650}- U s nimi bojoval a zabil|všechny kromì dvou.
{59650}{59800}- Take - co se stalo tvım šermíøùm,|mùe stát i tobì. Ne?
{59800}{59925}- Promiò, ale tvoje eny|jsou všechny mrtvé.
{59925}{60050}- To je nepøijmutelné.|Úplnì tì vystrašil!
{60050}{60150}- Buï bez obav. Jsme si naprosto|jisti, e ztratí svojí sílu,
{60150}{60200}jakmile ztratí svého syna.
{60200}{60504}Navíc vìz, e ten malı|chlapec je mu pøítìí.
{65953}{66059}Hej, pojï sem...
{66182}{66290}Hej, pojï sem...
{66875}{67028}- Dajgoro...
{68625}{68767}- Pøiprav se na smrt,|Vlku Samotáøi.
{68950}{69054}- Ty nestoudná podvodnice.
{69100}{69175}Ty muèiteli mého syna.
{69175}{69250}- Ta studna je pìknì hluboká.
{69250}{69369}Vzdej se teï nebo|se tvùj chlapec utopí.
{69375}{69450}Vzdej se Vlku Samotáøi.
{69450}{69530}- Odmítám.
{69575}{69650}- To je tvoje jistá smrt.
{69650}{69789}Odhoï svùj meè.
{69900}{70050}- Zabij ho, jestli se odváíš.|Mnì to neoslabí.
{70050}{70100}Mùj syn a já...
{70100}{70200}u jsme smíøeni se svım osudem.
{70200}{70325}A pøíliš hrdinské na jednoho,|kdy nemáš dalšího syna.
{70325}{70425}- Pøi pohledu smrti do oèí|se mùj syn nevzdá.
{70425}{70500}Nindo, teï uvidíš...
{70500}{70575}budeš si pøát,|abys byl moudøejší.
{70575}{70625}Dajgoro.
{70625}{70775}Za chvilku budeš stát|po boku své matky.
{70775}{70867}Rozumíš?
{73875}{73936}Dajgoro.
{74850}{74925}To bylo poprvé,|co jsem vidìl otce
{74925}{75025}jak ušetøil ivot nepøítele.
{75025}{75100}Mìl jí zabít.
{75100}{75175}Ale neudìlal to.
{75175}{75275}Moná kvùli tomu,|jak se na nìho dívala.
{75275}{75437}Moná mu nìkoho|pøipomínala.
{75650}{75775}Abychom našli Šógunova bratra|museli jsme jet lodí.
{75775}{75825}Byla to zábava.
{75825}{75875}Ale na lodi bylo pøíliš mnoho lidí.
{75875}{76007}Pøíliš mnoho nebezpeènıch lidí.
{76025}{76125}- Tak sem jí zmáèknul.
{76125}{76247}- Óó mùj Boe, jak ho enskı milujou.
{76725}{76811}- Hej.
{76825}{76901}Ahoj.
{77225}{77300}- Všichni na palubì|Všichni na palubì!
{77300}{77444}Všichni noví cestující -|a si vyndají peníze prosím!
{78050}{78111}- Vzbouøenci.
{78125}{78275}- Šógun má mnoho nepøátel.
{81075}{81150}- Zbav se jich,|nebo tì potká to samé.
{81150}{81175}- Ano.
{81175}{81200}- Hned.
{81200}{81313}- Ano.
{81850}{81967}- Se synem?
{82275}{82425}- Tfuj, "Vládci Smrti".|Skunkové!
{82425}{82545}- Nech mì vystoupit na pøíští zastávce!|Nebojte se! Nech mì...!
{82545}{82739}Udìlej nìco! Prosím!|Nemìjte obavy!
{83383}{83448}- To mì štve!
{83448}{83500}Ty svinì zabijí kadého,|kdo jim pøijde do cesty!!
{83500}{83609}Mám z toho zkaenou chu...
{83625}{83700}U nikdy víc.|Nikdy se nedostanou na bøeh.
{83700}{83773}U se na to tìším.
{84250}{84443}- Omlouvám se, e tì obtìuji.|Ale mohl bys mi vrátit mùj nù?
{85775}{85825}- Velmi divné...
{85825}{85950}Tyhle koláèe jsou plné oleje,|namísto pùvodní polevy.
{85950}{86133}e by nìkdo plánoval|zapálit loï??
{86175}{86275}- Oo, skunkové pijící saké...
{86275}{86375}Já u vás odnauèím takhle|mrzaèit nevinné lidi.
{86375}{86462}Dobrı.|Zùstaòte si dole.
{87600}{87720}A-ha! A teï se vy|pekelnı bestie usmaíte.
{88350}{88464}- Oheò!|Oheeeò!
{88575}{88675}- Poslouchej mì.|Jsi v pasti i s dítìtem.
{88675}{88750}V pøípadì, e by ses zachránil,|mìl bys vìdìt...
{88750}{88875}e jsme tì poznali. Šógun nikdy|nezapomene na to, co se stalo.
{88875}{88950}- Pøišli jsme doruèit pána Kiru.
{88950}{89100}- Ale nezaútoèíme na tebe, do té doby, dokud|proti tobì, Vlku Samotáøi, nebudeme nìco mít.
{89100}{89175}- Jestlie ty Vlku nebudeš|dìlat nìjakou neplechu.
{89175}{89225}- Budeš velmi moudrı,|nebudeš-li nás pronásledovat.
{89225}{89413}Dokonce i tvoje mystika je nièím|v porovnání s "Vládci Smrti".
{90650}{90743}- Dajgoro,|buï stateènı.
{96100}{96165}- Dajgoro.
{96300}{96325}Není tu ádnı oheò.
{96325}{96500}Musíme se zahøát|nebo zmrzneme.
{96500}{96600}- Jak mnì... mùeš ušetøit?
{96600}{96656}- Ty... tøeseš se.
{96692}{96817}Bojíš se víc míru ne války?
{101399}{101500}Cítili jsme se špatnì,|kdy jsme jí tam nechávali.
{101500}{101575}Vìdìli jsme, e musí|jít zpátky za Šógunem...
{101575}{101625}vykonat harakiri
{101625}{101750}... byla ninda a zklamala.
{101750}{101888}Hledali jsme dál Šógunova bratra.
{103075}{103150}-Jsou tady.
{103150}{103200}- Musí bıt blízko.
{103200}{103290}Tuším rebely.|Nìjak je cítím.
{103300}{103399}- Kde mohou bıt?|Sledují nás.
{103400}{103449}- Teï zaútoèí.
{103449}{103509}Buïte velmi opatrní.
{109875}{109900}- Take...
{109900}{110000}- Opìtovné shledání...
{110000}{110150}- Nyní ti ukáeme...|"Vládce Smrti".
{110150}{110222}- No tak pojïte.
{111650}{111813}- Jak jsi mohl...? Hodit svùj meè?
{112650}{112775}- Tttvoje... tech...nika...
{112775}{112925}je... ú...asn...á.
{112925}{113000}Kdy se pøetne krk
{113000}{113200}øíká se, e je slyšet zvuk.|Jako by enskı vítr...
{113200}{113325}Abychom nìco takového nìkdy slyšeli,
{113325}{113425}museli bychom nìkdy nìkoho podøíznout...
{113425}{113729}A to se stalo mému krku...|to je... smìšné...
{114675}{114775}- Ty se mì nesmíš dotknout!|Jsem bratr Šóguna!
{114775}{114844}- Vylez.
{114925}{115025}Šógun...|nic pro mì neznamená.
{115025}{115095}Zemøi!
{116075}{116150}Myslím, e bych si pøál,|aby to bylo jiné...
{116150}{116353}ale pøání je pouhım pøáním.
{116525}{116750}Titulky Z90waves|Thanks TB :-)