{119}{166}Keiko!|Keiko!
{368}{468}Naivo si to vyzkoušet...|Je to tìké udìlat.
{517}{567}Ale nikdy jsem nepochopil
{616}{701}vıznam úsmìvu,|s kterım mì opustila.
{991}{1023}Dìkuji ti...
{1644}{1681}Napiju se.
{1942}{2018}Ale proè hraješ zase znovu?
{2042}{2111}Zfetovali mì|a octnul jsem se tady...
{2143}{2209}Asi abych zpestøil hru.
{2213}{2298}Ale kdy jsem se tady probudil,|pøísahal jsem
{2326}{2371}e nezemøu.
{2375}{2466}Spíš, se budu snait rozluštit|poslední úsmìv Keiko.
{2580}{2617}Tomu nerozumím...
{2644}{2681}Èemu?
{2724}{2838}Nevím pøesnì|jak to Keiko cítila...
{2881}{2944}Ale musela mít...
{2989}{3088}Um... |Jak se jmenuju? Kawada.
{3094}{3153}Myslím, e tì opravdu milovala.
{3186}{3269}Nebo se chtìla smát,|chtìla ti tou cestou nìco øíct.
{3336}{3373}Myslíš...?
{3406}{3503}Jsem si jistá,|kdybych byla Keiko,
{3507}{3641}chtìla bych ti vìøit a podìkovat ti, za to,|e si mi dal dùvod k úsmìvu.
{3645}{3728}Myslím, e bych|taky øekla dìkuji...
{3886}{3956}Já znám cestu z|tohohle ostrova.
{3960}{3998}CO! Ale jak?
{4002}{4070}Mùu vám jen øíct,|kdy pøijde èas.
{4107}{4167}Døív, ne se tak stane,|tohle je má záruka.
{4193}{4271}Pouijte to ke své ochranì a...
{4296}{4333}Noriko.
{4337}{4370}Nanahara Shuya.
{4444}{4481}Svíèky!
{4595}{4637}K zemi!
{4641}{4689}Ten zvuk, co je to?
{4693}{4781}Pravdìpodobnì nìjakej èlovìk, |co má o zábavu postaráno.
{4785}{4821}Mìli jsme taky jednu UZI.
{5295}{5328}Dejte mi mapu.
{5332}{5431}Poslouchejte, kdy se rozdìlíme, |setkáme se ve svatyni Takano.
{5435}{5475}Nezapomeò!
{5479}{5517}Drte se pøi zemi!
{5688}{5735}Proè? Co jsem ti kdy udìlal?
{6586}{6712}Hergot! Zvládnul jsem to.|Má skvìlá neprùstøelná vesta!!
{7112}{7212}Chlapec #4 Oda mrtvı,|20 zbıvá.
{8342}{8379}Spìchej!
{8741}{8810}Jsi OK?| Fajn. Ona je taky v pohodì.
{8892}{8929}Postarej se o ni!
{8990}{9027}Nebuï blázen!
{9080}{9117}Nanaharo!
{10238}{10275}Bì, Nanaharo!
{10671}{10711}Pøesnì, jak si chtìl.
{10715}{10796}Hnojivo... pesticidy...|a benzín...
{10800}{10847}Síra a døevìnı uhlí...
{10851}{10914}Kdy s tím naloíme menší náklaïák...
{10918}{11011}Co chceš dìlat s|tìmahle všema sraèkama?
{11145}{11233}Tikající hodiny.|Co je to?
{11389}{11433}Pozdravy od mého strıèka.
{11437}{11500}Mùj strıèek byl|aktivista v 60tıch letech.
{11504}{11585}Øekl mi vìci, které|se nikdy neuèí ve škole:-)
{11590}{11673}Poøád bojoval v nìjakém|koutì svìta.
{11722}{11799}Nìkdy v budoucnu|se nad tím zasmìjete.
{11803}{11853}Zapomeò na to, my nejsme...
{11876}{11913}Shinji!
{12182}{12276}Detonátor. Pouil ho pøi pokusu | o odpálení parlamentu.
{12280}{12410}Je èas, abychom zaèali náš zápas, |protoe nezbıvá moc èasu.
{12414}{12449}Jdete do toho se mnou?
{12505}{12585}Nebo mì v tom|necháte samotného?
{12663}{12758}Mùeme se doopravdy dostat|spoleènì domù?
{12762}{12832}Ano, nabourám jejich systém.
{12863}{12925}Kdy uteèeme,|budeme pohromadì.
{13061}{13166}Den druhı 12:30
{13491}{13554}U jsi vzhùru? |Kde...
{13558}{13597}V majáku.
{13601}{13645}Utsumi, proè jsi...
{13649}{13735}To byl šok|Byla jsem na obhlídce dnes ráno,
{13739}{13810}kdy tì Sugimura pøinesla,|a ukázala mi tì.
{14106}{14220}Kde je Sugimura? |Pryè. Øíkala,|e nìkoho vidìla.
{14224}{14316}Chápu...| Kolik je hodin?
{14320}{14408}Poledne, právì|dokonèil polední hlášení.
{14412}{14470}A Kawada a Noriko?
{14474}{14533}Ty nebyly na seznamu...
{14571}{14685}Kdo zemøel?|Promeškal jsem 3 hlášení
{14689}{14789}Celkem pìt.|Oda zemøela v noci.
{14884}{14973}Dnes ráno pøibyly|Kaori a Mizuho.
{15034}{15091}Byli to mí kamarádi.
{15095}{15136}Já vím.
{15222}{15365}Dívka #1 Mizuho, |dívka #12 Kaori, mrtvá.
{15426}{15476}A teï v poledne pøibyli ještì...
{15481}{15533}...Takiguchi a Hatagami.
{15743}{15884}Chlapec #13 Takiguchi, |Chlapec #18 Hatagami, mrtvı|16 zbıvá.
{15904}{15951}A zpráva od Sugimury.
{15955}{16052}Mimura a chlapci jsou na západì, |èekají a tìší se, a tì uvidí.
{16056}{16107}Mimura...|Ano.
{16111}{16187}Tady je tvá mapa|Oznaèila jsem ji pro tebe.
{16211}{16293}Jsi tu v bezpeèí,|Oni jsou všichni mí pøátelé.
{16328}{16427}Je tam Haruka,|Satomi a Yuka, Chisato a Yuko.
{16519}{16567}Nanaharo...
{16571}{16694}Ohlednì té vìci s Oki...|Yuko vidìla co se stalo.
{16697}{16803}Ano...? |Spadli jsme dolù ze svahu.
{16807}{16860}Nehoda? |Samozøejmì e byla!
{16864}{16942}Je mi líto...|Pojïme si všichni pøipojit ke Kawado.
{16946}{17028}On zná cestu pryè. |Vìøíš mu?
{17033}{17093}On pøeil jednu z tìchto her.
{17098}{17160}Ale ty teï nemùeš chodit...
{17164}{17226}Je mi fajn... |Tak dobøe, odpoèni si.
{17230}{17323}Haruka a Chisato|pøipravují obìd.
{17365}{17416}To ty jsi mì obvázala, Utsumi?
{17444}{17481}Ano
{17520}{17583}Nikdy pøedtím jsem se nedotkla kluka...
{17731}{17779}Máš rád Noriko?
{17804}{17840}Proè...?
{17844}{17924}Všechno o tobì vím...
{17928}{17998}víš co to znamená?
{18002}{18044}Co?
{18048}{18081}Zapomeò na to...
{18085}{18193}Zamknu tì, OK?|Nikomu z tìch chlapcù nevìø.
{18197}{18237}Obìd je za moment, OK?
{18959}{19022}Hej, holky! |Nanahara se probudil.
{19026}{19070}Opravdu? |Mùe mluvit?
{19074}{19114}Vypadá hladovı...
{19150}{19225}Neboj se.|Zamknula jsem dveøe.
{19229}{19302}Ne. Promiò,|U se nebudu nervovat.
{19306}{19380}To co se stalo|Okimu byla nehoda.
{19384}{19471}Ano jistì.|Shuya nikdy nikoho nezabil.
{19475}{19519}Špageti za chvíli budou.
{19523}{19629}Haruko, bì vystøídat Yuki na hlídce. |Potøebujeme nìco probrat. 
{19633}{19670}Rozumím.
{19803}{19875}Všichni...
{19879}{19918}...zítra zemøeme.
{19956}{19995}Nezaèínej s tím zase.
{19999}{20090}Vzdáme se pøed koncem, OK?
{20094}{20213}Myslím, e bude lepší nejdøív|nakrmit Nanaharu, nemyslíš?
{20217}{20262}Správnì!|Prostøu mu.
{20266}{20303}Díky, Yuko.
{20558}{20594}Hej!
{20598}{20698}Máš stále ten lék proti bolesti?|Potøebovala bych nìjakı pro Nanahara.
{20702}{20761}Ve skøíni. |Dám mu ho.
{20766}{20806}Yukie!
{20810}{20900}Slyšela jsem, e se Nanahara probudil!|To je tak super! Hej ty!
{20927}{21041}Nedìlej... Vím, e jsi šastná. |Voní to skvìle...Dobrá práce, Chisato.
{21045}{21095}Nechte mì ochutnat.
{21099}{21160}Super! Vem si mì, Chisato!
{21164}{21228}No tak, Yuko! |Uklidni se...
{21232}{21304}Co si chtìla probrat, Yukie?
{21335}{21445}Nanahara øíkal, e Kawada|zná cestu z ostrova.
{21449}{21504}Kawada? |Mùeme mu vìøit?
{21509}{21654}To teï nemùu øíct, ale a bude moct Nanahara chodit,| pøipojíme se ke Kawadovi a Noriko...
{21687}{21729}Co je?!
{21755}{21796}Co se dìje???
{21838}{21870}Yuko!
{21926}{21967}Je mrtvá... |Proè...
{21971}{22016}Né, jídlo je otrávené...
{22020}{22100}Je otrávené smrtelnım jedem...|Chutnala jsem ho. Je mi fajn.
{22104}{22148}Je to jed!
{22153}{22190}Jed!
{22256}{22311}Kdo? Kdo? Kdo to udìlal???!!!
{22315}{22383}Satomi, ne! |To co dìláš je chyba!
{22387}{22481}Dríme pøi sobì!|Chisato. |Ty jsi to vaøila, je to tak?
{22485}{22562}To jsem nebyla já!|Haruka taky vaøila. Já a jed?!
{22566}{22673}Neudìlal to nikdo z nás, nepøerušujte mì! |Polo tu zbraò!
{22677}{22733}Podezíráme sebe!
{22738}{22831}Haruko! |Poslední 2 noci,|jsi vùbec nespala...
{22835}{22937}To znamená, e si nám nevìøila. |Zapomnìla jsem si mé prášky na spaní...
{22941}{23061}Prášky, v tvém vìku?|Nepøerušuj mì! Satomi, polo tu zbraò braò!
{23066}{23103}Zmlknìte sakra!!!!
{23176}{23252}Yukie, sniovala morálku! |Chisato...
{23256}{23359}Ty vytoèená travièko... |Jak tohle mùeš øíct?
{23363}{23448}Plánovala si, jak s Nanaharou|spoleènì uteèeš!
{23452}{23489}Byla jsi to ty?
{23563}{23600}Chisato!
{23761}{23801}Dobøe, hergot, k èertu!
{23962}{24076}Och! Zabije nás to, vy kreténi!|Krvácím sakra!
{24118}{24161}Podívejme, kdo mluví!
{24166}{24231}Zavøi kurva hubu!
{24235}{24323}Snaila ses ukrást zbraò,|tak buï zticha!
{24327}{24364}Vem si tohle!
{24785}{24901}Ty né, správnì... |Ty nepatøíš do jejich party...
{24982}{25085}Nakonec...|Já myslela, e budu ivá a do zítøka.
{25291}{25377}Co, vy idioti...|Mohli jsme všichni pøeít...
{25409}{25466}Jste všichni tak blbı...
{25502}{25534}Idioti!
{25755}{25866}Není to má chyba...|Není to má chyba...
{25889}{25940}Není to má chyba...
{25974}{26043}Co se stalo, Utsumi!
{26047}{26127}Co se stalo, hej, Utsumi!
{26438}{26491}Je mi to líto, Nanaharo...
{26527}{26638}Já jsem dokonce zapomnìla...|e jsou všichni mí pøátelé...
{27215}{27268}Proè...
{27272}{27314}Utsumi...
{27350}{27398}Proè...
{27402}{27475}Víš co to znamená?
{27914}{27981}Víš co to znamená?!
{28049}{28096}Jak to mám vìdìt?!
{28122}{28186}Nevím, co by to mìlo znamenat!
{28360}{28475}Dívky #2 Yukie, #9 Yuko, #12 Haruka, | #16 Yuka, #17 Satomi, #19 Chisato mrtvé|10 zbıvá. 
{30954}{30991}Hovor pro vás
{31148}{31231}Haló. Haló, pane.
{31235}{31274}Oh, Shiori?
{31278}{31333}Matka se opìt cítí špatnì.
{31367}{31454}Jsem na sluební cestì, nemùu se vrátit|døív, ne pozítøí.
{31503}{31560}Huh, neobtìuj se pøijít domù...
{31617}{31662}Povìsí se.
{31666}{31708}Uh huh...
{31712}{31841}Nedıchej tak.
{32208}{32246}Jsi OK?
{32270}{32311}Mìla jsem sen...
{32316}{32370}Jakı sen?
{32374}{32480}Byla jsem sama s Kitanem|na prázdném nábøeí.
{32484}{32536}To muselo bıt strašidelné
{32540}{32597}Ale Kitano ...
{32601}{32648}...  vypadal opuštìnı.
{32903}{33020}Pøedtím, vdycky jsem|chtìla bıt normální...
{33080}{33214}Chtìla jsem se vdát,|v normálním vìku, asi jako matka.
{33312}{33428}Ale kdy tahle hra zaèala...|Poznala jsem...
{33432}{33506}to, pøed èím jsem byla chránìna...
{33510}{33568}Nìkteré vìci je lepší|radìji naznat.
{33619}{33668}Zaèíná pršet.
{33714}{33804}Doufám, e nás tu Nanahara najde.
{34134}{34179}Øíkal jsem ti, abys èekal!
{34288}{34379}Další ztracenı den|Mùj telefon nikdy nezazvoní.
{34383}{34468}Dokonce mi je k nièemu. |Podívej, není tu signál.
{34472}{34535}Co si budete pøát??? |Chvíli poèkejte.
{34539}{34594}To je v poøádku.
{34598}{34704}Radìj se neptej, kolik|ádostí jsem napsal.|Prostì jsem utøel...
{34708}{34760}Vdycky mi to poloí...
{34792}{34882}Sleèno, pøineste mi trochu vody. |Ano, moment.
{34923}{35034}Objednat si... Co bys chtìl? |Zítra zaèneš 7 roèník, uè se.
{35070}{35158}"Øíkám ""uè se"", |ale nikdy jsem tì nic nenauèil."
{35162}{35223}U jste si vybrali? |Øíkal jsem, abyste poèkal!!!
{35293}{35332}Zkusíme to jinde?
{35688}{35779}" Máš na to, Shuya! "
{36170}{36215}Shuya...
{36219}{36335}Noriko, OK?|Slibuji, e tì budu ochraòovat.
{36827}{36871}Kam jdeš? |Jdu za Nanaharou.
{36874}{36938}Hej!|Jsme poblí nebezpeèné zóny!
{37232}{37309}Kde jsi! Noriko!
{37608}{37650}Mitsuko.
{37685}{37721}Co se dìje?
{37725}{37790}Hledám Nanahara.
{37794}{37836}Rozdìlili jste se?
{37840}{37910}Noriko, kde jsi?!
{37914}{37973}Co to je? 'Kawada.
{38047}{38132}Dva princové tì ochrání. |Skuteèní princové.
{38178}{38256}Mitsuko! |Chcípni, ošklivko.
{38426}{38463}Hej.
{38528}{38569}Nevypadáš tak špatnì.
{38618}{38685}Oh, máš tu|Nanaharu.
{38725}{38768}Nanaharo!
{39135}{39172}Shuya!
{39212}{39249}Shuya!
{39419}{39471}Neprostydni
{39692}{39739}Pøišla si za mnou?
{39908}{39944}Pøinesl jsem zbranì.
{40018}{40089}Zbranì... proè?
{40148}{40196}Jsem slabı...
{40245}{40288}...a k nièemu...
{40337}{40402}...ale chci ti stát po boku...
{40468}{40506}budu tì chránit.
{40547}{40600}Proto...
{40604}{40666}jsem pøinesl zbranì...
{40728}{40768}Shuyo...
{42857}{42933}Kotohiki... jsi to ty?
{43018}{43075}Kotohiki? |Odpovìz mi!
{43403}{43466}Pospìš si, bì...
{43470}{43504}Coe?
{43508}{43628}Nìkdo urèitì slyšel vıstøely|a pøijde sem... |Bì!
{43648}{43773}Proè? Sugimuro, proè?
{43797}{43872}Jsi tak sladká...
{43912}{44009}Oo, o èem to mluvíš?|Co je to?
{44050}{44096}Chtìl jsem tì vidìt...
{44136}{44225}Vlastnì abych tì zachránil...
{44286}{44324}To mi neøíkej...
{44328}{44414}Byl jsem do tebe zamilovanı,|Kotohiki...
{44418}{44528}u dlouho, dlouho...
{45364}{45400}Ale ty...
{45423}{45507}..nikdy si se mnou nemluvil.
{45552}{45666}Jak jsem to mohla vìdìt,|kdy si mi nikdy nic neøekl...
{45699}{45773}Co mám teï udìlat?
{45807}{45848}Zemøi...
{45974}{46066}Chlapec #11 Sugimura, |Dívka #8 Kotohiki, mrtvá.
{46141}{46195}Mìj se, Mitsuko!|Zítra!
{46199}{46236}Mìj se!
{46261}{46298}Jsem doma!
{46334}{46436}Kdo jste?|- Kdo jsem? No, já...
{46516}{46559}Co se stalo mami?
{46581}{46648}Maminku bolí aludek.
{46652}{46735}Co kdybychom si chvilku hrály spoleènì?
{46739}{46781}Ne!
{46826}{46878}Buï silná, Mitsuko.
{46907}{47018}Pokud to nedokáeš, |dopadneš stejnì jako já.
{47063}{47121}Ahoj, Mitsuko.
{47125}{47217}Tahle panenka se také jmenuje Mitsuko.
{47221}{47273}e je roztomilá?
{47277}{47339}Je roztomilá a taky velmi legraèní.
{47343}{47380}Podívej?
{47499}{47559}Teï má všechny šatièky sundané.
{47563}{47629}A teï si to s Mitsuko s tebou vymìní.
{47633}{47685}Dáme je taky všechny dolù.
{47690}{47727}Ne!
{48225}{48285}Nikdo tì nezachrání.
{48289}{48337}Takovej je ivot...
{49055}{49095}Chcípni!
{49707}{49830}U nikdy více|nechci bıt ten, kdo prohrává...
{50087}{50191}Dívka #11 Mitsuko mrtvá?|7 zbıvá.
{50434}{50496}Dívka #16 Yuka,
{50505}{50562}#19 Chisato,
{50567}{50624}#12 Haruka,
{50629}{50776}#17 Satomi, #2 Yukie, #9 Yuko
{50780}{50879}#8 Kotohiki, #11 Mitsuko,
{50889}{51020}a pouze jeden z chlapcù, |Sugimura, celkem 9.
{51083}{51186}Pojïme na západ. Ještì stále se mùeme|vyhnout novım nebezpeènım zónám.
{51205}{51290}Musím vidìt Mimuru
{51310}{51351}Dobøe...
{53426}{53481}Dokázal jsem to! Mám to!
{53485}{53530}My jsme to taky zvládli! |Skvìlé!
{53535}{53619}2 bomby, 100 Molotovù. |A 3 bomby s propanem.
{53624}{53732}Bude to chvilka a mùj poslední pomocník,|hackerskı program, je pøipraven!
{53786}{53839}Hacker! |Odkud?
{53843}{53894}To nemùu øíct! |Vyhledejte je!
{53898}{53959}Pøíliš mnoho pøipojení! |Naše linky jsou pøetíené!
{53963}{54043}Pøepisuje data! |GPS monitoring zmrznul!
{54227}{54322}Co to k èertu je?! Napadení virem! |Všechno mae!
{54328}{54385}Virus pracuje! |Satelitní systém zmrznul!
{54389}{54439}Hlavní ovládání vypadlo! |Pøipojení selhalo!
{54443}{54541}Nebezpeèné zóny jsou odstranìnı! |Dìlejte nìco!
{54617}{54650}Zatracené!|Pane!
{54658}{54700}Co dìláte!
{54809}{54850}Re-aktivujte.
{54893}{54944}OK, tak jdeme!
{55202}{55315}"Máme 15 minut, ne se jim podaøí znovu obnovit systém. |Vyhodíme "školu" a hry je konec!"
{55319}{55388}Mám pocit,|e jsem támhle nìkoho zahlédl...
{55392}{55440}Coe? |Nanaharo?
{55444}{55543}Nanaharo? |Tøeba mu Sugimura|øekl o nás.
{55548}{55642}Hej, Nanaharo,|pojï sem, pospìš si
{55689}{55730}Yutako!
{55839}{55881}Doprdele, kdo to je?!
{55938}{55984}To je on! |Ten pøeloenej!
{56089}{56151}Nemùu ho zasáhnout!|Miø klidnì!
{56184}{56239}Zase si minul!|Sklapni!
{56333}{56372}To není dobrı, ustupujeme!
{56484}{56530}Iijimo! lijimo!
{56580}{56657}...kdy uteèeme...|budeme spolu...
{56661}{56733}Hej! Kurva!
{57112}{57211}Chlapec #2 lijima, #12 Yutaka,| #19 Mimura, mrtví, 4 zbıvají.
{57912}{57949}To je on.
{58280}{58317}Zùstaò tady.
{59232}{59328}Chlapec #6 Kiriyama mrtvı|3 zbıvají.
{59560}{59607}Jsi zranìn?
{59611}{59653}Není to tak zlé.
{59681}{59804}Co se to stalo,|jsme poslední, kdo je naivu.
{59808}{59844}Ano.
{59848}{59906}Co chceš dìlat s tímhle?
{59931}{59974}Nevím.
{60000}{60091}Já jsem opravdu ještì...|nevìøil dospìlım.
{60140}{60234}Mùj otec a má matka.
{60283}{60373}utekli pryè nebo zemøeli,|nic o nich nevím, asi to tak chtìli...
{60482}{60598}Ale já budu bojovat,|aèkoliv nevím jak...
{60654}{60710}Døív, ne se stanu|opravdu dospìlım.
{60761}{60825}Vy nikdy nebudete.
{60829}{60879}Jak to, e ne?
{60883}{60961}Øekl jsem, e nebudete?|Nikomu nevìøit.
{61003}{61111}Dobøe... |Dobøe, vy oba jste|mi vìøili a moc.
{61140}{61219}Prohrál si. |Byl to špatnı vtip.
{61223}{61278}To byla má cesta z ostrova.
{61282}{61362}Promiò, ale vyuil jsem vás,|abych zachránil sám sebe.
{61391}{61467}Tomu nemùu uvìøit|A co  Keiko?
{61482}{61582}Není ádná Keiko. |Byl to jen pøíbìh, kterım jsem vás stáhnul...
{61586}{61622}Ale proè nás?
{61626}{61743}Byli jste perfektní,|dostateènì dùvìøivı.
{61814}{61920}Hej, Nanaharo. |Opravdu mì dovedeš zabít tou zbraní?
{62025}{62084}Hra skonèila.
{62212}{62285}Jdìte ven zkontrolovat mrtvoly! |Rozumím!
{62289}{62335}Operace skonèena.
{62340}{62405}Ale pane... |Øekl jsem operace dokonèena.
{62688}{62742}Konec hry|Den tøetí  4:30
{62746}{62801}Vítìz: Chlapec #5 Kawada.
{63605}{63652}BR Rádio cvièení
{63761}{63888}Zvednìte ruce pøed sebe|a postavte se na špièky...
{63892}{63974}1, 2, 3, 4...
{64024}{64074}Pohybujte rukama a nohama.
{64357}{64395}Houpejte rukama.
{64706}{64822}Stùjte mírnì rozkroèmo|a vypnìte hruï...
{65266}{65389}Dobrá práce. Potìšující, e si|spolu s Kiriyamem dobøe zapadli.
{65393}{65452}Nejdeš domù?|Nespìchám.
{65475}{65526}Ujasníme si jednu vìc.
{65753}{65864}Mùeš ho deaktivovat, je to tak?|Co to...
{65868}{65988}Naboural si se do systému a vymìnil si data, |je to tak?
{66031}{66068}Pomsta za Keiko?
{66110}{66198}To je pìknı. To je ten dùvod,|proè si hrál hru, je to tak?
{66229}{66295}Ale podvádìní není dobré...
{66462}{66534}Hej! Co je k smíchu?
{66556}{66625}Spolu pøeivší zamilované hrdlièky?
{66650}{66707}Znal jsem to...
{66712}{66830}Dìti si ze mì ve škole dìlali legraci,|mé vlastní dìti mì nenávidìli.
{66835}{66886}ádnı domov, ádná cesta zpìt.
{66907}{67007}Mohl bych vás vzít s sebou.
{67718}{67823}A jedinı, s kım budu umírat,|budeš ty, Noriko.
{67912}{68041}Mìl jsem vybrat jednoho z vás,|dobøe, budeš to ty, Noriko.
{68188}{68248}Co? Jdu k tobì, støílej.
{68349}{68406}Noriko, mùeš to udìlat...
{68481}{68547}Noriko, mùeš to udìlat...
{68744}{68819} Máš na to, Shuya! 
{68930}{69004}No tak?|Støel mì, ty mì chceš støelit.
{69115}{69166}Ouch!
{69170}{69213}To bolí, sakra!
{69461}{69592}Já jsem pøísahal.|Ochráním Noriko...
{69639}{69723}Já vím, já vím...
{70462}{70512}Haló...
{70516}{70561}Shiori?
{70565}{70688}Poslouchej, chci se vrátit|zase domù.
{70740}{70866}Poslouchej, jestli nìkoho nenávidíš,|uvìdom si taky dùsledky.
{70899}{70965}Bezohlednost?|Kdo se tì sakra ptal?
{71303}{71337}Poslední koláèek...
{71408}{71454}Koláèky byly opravdu dobré.
{72360}{72466}Je nádhernı... Pøestoe,|všichni na nìm zemøeli.
{72551}{72606}Umíš dokonce kormidlovat loï?
{72610}{72689}Jasnì, mùj táta je rybáø.
{72757}{72862}Tak hlavnì jeï rovnì|a narazíš na pevninu.
{72866}{72901}Zkusíš to?
{73020}{73126}Brzy se rozdìlíme|Pochybuji, e vás nìkdy znovu uvidím.
{73159}{73199}Proè ne?
{73203}{73251}Bude to tak nejlepší.
{73255}{73360}Byli to jen 3 dny, ale zato mnoho vzpomínek.|Radìji bych zapomnìl.
{73552}{73599}Kawado... |Jo?
{73659}{73693}Mnohokrát ti dìkuji
{73732}{73786}Nanaharo!
{73791}{73827}Jo?
{73831}{73878}Jdi vdy pevnì za svım cílem
{73917}{74000}Jo.. Já vím
{74087}{74180}Chce se mi nìjak spát|Èas si zdøímnout
{74234}{74342}Setkání s vámi|jsem koneènì završil
{74346}{74399}Hádanka úsmìvu Keiko.
{74424}{74470}Odpovìï?
{74474}{74524}Její slova na rozlouèenou.
{74574}{74655}Díky... a pak...
{74727}{74764}A pak?
{74884}{74925}Kawado?
{74929}{74966}Kawado?
{75068}{75190}A pak...|Jsem šastnı, našel jsem skuteèné pøátele.
{75337}{75529}A pak...|Jsem šastnı, našel jsem skuteèné pøátele.
{75768}{75946}Hledáni pro vradu.
{76578}{76670}Nanahara a Noriko se minulou noc.
{76674}{76739}doma rozlouèila se spícími rodièi...
{76743}{76895}Vzala si nù, kterım Nobu poøezal|uèitele Kitana.
{76958}{77048}Kadı z nás má nyní zbraò.
{77092}{77163}Ještì pøijde správná chvíle|na to ji znovu vyuít.
{77187}{77277}nebude to lehká volba.
{77338}{77454}Ale nemáme na vıbìr,|jdeme stále za svım cílem.
{77691}{77726}Tak pobì, Noriko.
{77730}{77767}Ano
{77814}{77904}Nezáleí, jak daleko,|bì za vším, co má pro tebe hodnotu...
{77958}{78049}BÌ!
{78128}{78260}Requiem I|9.B tøída - Pøátelé.
{79523}{79652}Requiem II|Shuya.
{80103}{80140}Nobu...
{80165}{80208}Shuya...
{80212}{80330}Postarám se o tebe, OK?.|Slibuji, e tì budu ochraòovat.
{80476}{80632}Requiem III|Noriko a Kitano.
{80966}{81028}Jsi OK?|- Co?
{81031}{81147}Pokud nás uvidí spoleènì, zaknou mì zase na záchodì.
{81151}{81213}Otoèí tím klíèem nìkdo jinı.
{81238}{81302}Jsou moje hodiny nudné? |- Ano.
{81306}{81343}Co si to dovoluješ.
{81382}{81423}Jdu do tøídy...
{81444}{81519}Ve tøídì vypadáte všichni naprosto stejnì.
{81523}{81630}Pohlavkování mi pomáhá studenty rozlišit. |A taky je mít rád. 
{81635}{81673}Ane u ne.-
{81701}{81775}Teï, kdy sáhneš na studenta,| vyhodí tì.
{81779}{81860}Kdy student pobodá tebe, |nic se mu nestane!
{81904}{81974}Jednu vìc ti øeknu. - Co?
{82000}{82057}Nù, kterı tì bodnul...
{82061}{82149}Vlastnì ho mám v mém stole doma.
{82196}{82257}Kdy ho drím,| nejsem si jistá...
{82282}{82363}... ale teï, |z nìjakého dùvodu, si ho cením.
{82470}{82505}Je to naše tajemství.
{82509}{82546}Jenom mezi námi.
{82598}{82656}Poslouchej Noriko. |- Ano?
{82660}{82759}Co si myslíš, |e by mìli teï dospìlí øíkat dìtem?
{82795}{82912}<B>Co si myslíš,| e by mìli teï dospìlí øíkat dìtem?</B>
{83010}{83063}Pøeklad titulkù pro vás zmáknul Deleter|Bazisoft@seznam.cz
{83108}{83202}
{83254}{83348}úpravy: banda a Atomix
{83394}{83489}
{83527}{83622}
{85081}{85176}
{85194}{85288}
{85368}{85463}
{85558}{85653}
{85658}{85748}
{85766}{85861}
{85878}{85973}
{85978}{86069}
{86086}{86180}
{86198}{86292}
{86310}{86405}
{86421}{86516}
{86533}{86628}
{86646}{86740}
{86757}{86852}
{86869}{86964}
{88259}{88372}
{88867}{88978}
{89088}{89210}