{759}{858}Na pøelomu tisíciletí... | ...se národ zhroutil.
{871}{952}Pøes 15% nezamìstnanıch,|10 milionù lidí bylo bez práce...
{957}{1114}800,000 studentù|bojkotovalo školu
{1167}{1244}Dospìlí ztrácejí autoritu,|a bojí se dìtí,
{1248}{1346}...nakonec navrhli | Vzdìlávací reformu tisíciletí
{1383}{1488}AKA: the BR Act.
{1594}{1706}Tento rok byla vybrána škola|v Zentsuji, tøída 9.E
{1710}{1785}mezi 43,000 ostatními tøídami|devátıch roèníkù.
{1789}{1890}Tento rok byla hra havìjší,|ne minule...
{1900}{1966}Óo, podívejte támhle! |To je ona!
{1970}{2014}Vítìz je dívka!
{2038}{2162}Pøeila nelítostnı boj,|kterı trval 2 dny, 7 hodin a 43 minut,
{2166}{2207}vítìz je dívka!
{2231}{2295}Podívejte, ona se smìje!|Smìje se!
{2299}{2367}Ta dívka se urèitì smìje!!
{2423}{2480}
{2693}{2731}BATTLE ROYALE
{3082}{3222}Matka zemøela, kdy jsem byl ve 4. tøídì,|a mùj první den v 7. tøídì...
{3226}{3269}...se mùj otec obìsil.
{3548}{3632} Máš na to, Shuya .
{3930}{3973}Vše bylo tak divné.
{4005}{4130}Nemìl jsem ponìtí, co dìlat, | a nikdo mi ani neporadil.
{4170}{4227}Dobré ráno Profesore!
{4283}{4412}Promiòte, jdu pozdì a...
{4415}{4510}...a nevím, co se dìje.
{5558}{5660}Bylo rozhodnuto o ukonèení vıuky.
{5752}{5842}Dny utíkaly,|protoe jsme chtìli.
{5863}{5934}
{6432}{6556}A tak naše povinné vzdìlání|spìlo ke konci.
{6959}{7019}Pane uèiteli! |Oh, promiò.
{7075}{7117}Tak pojï |Né...
{7121}{7171}Pojï, tak pojï! |Promiò.
{7175}{7213}Promiò, nech nás projít.
{7257}{7358}Nanaharo...| Upekla jsem pro nás koláèe,|rozdìlíme se..
{7362}{7436}Pro tebe taky, Nobu |Opravdu?
{7440}{7496}Podívej se sem |OK.
{7500}{7537}Øeknìte sır!
{7569}{7637}Noriko, poèkej, pak ti to dám.
{7642}{7727}Megumi! |Vezmeš si taky?
{7732}{7768}Né, já nebudu.
{7778}{7882}Díky, e jsi mì dostala zpátky do školy,|Noriko.
{7886}{7943}Díky |Já mám taky radost, Nobu.
{7947}{8018}Obrázek je hotovı! |Sotva tam jsem!
{10531}{10573}Hej, Noriko!
{10708}{10767}Nobu.
{13330}{13367}A po tobì.
{13663}{13716}Kitano! |Kitano?
{13720}{13758}To nemùe bıt pravda...
{13801}{13891}OK, sednìte si! |Sednìte si! Sednìte si!
{14036}{14077}U jsme se vidìli.
{14092}{14165}Jsem Kitano, váš bıvalı uèitel ze 7. tøídy.
{14169}{14276}Mám vás tu znovu ve tøídì B.|Buïme pøátelé.
{14309}{14402}Pøibyli k nám 2 studenti|Kawado, támhle.
{14434}{14489}Kiriyamo, tam!
{14516}{14552}Buïte na nì hodní.
{14645}{14700}Akce BR
{14708}{14746}Kde to sakra jsme?!
{14750}{14788}Co se tady dìje???
{14792}{14832}Kdo jsou tyhle lidi?!
{14865}{14902}Znáte tenhle zákon?
{15062}{15111}Né moc dobøe.
{15115}{15266}...né moc dobøe...|to je to, kam tahle zemì spìje|Vy víte proè...
{15270}{15312}ádnı šeptání, sakra!
{15353}{15391}Ty svinì!
{15425}{15507}Jestli nìkdo ještì promluví...|Drte hubu a poslouchejte!
{15539}{15603}Mùe jít na záchod,|pane uèiteli?
{15631}{15692}Chiguso, nemùeš chvíli poèkat?
{15710}{15746}Vynechal jsem vás, chlapci.
{15853}{15899}Kuninobu
{15924}{15968}Èlovìèe, bolí mì noha, vzpomínáš?
{16005}{16127}Døív ne jsem u vás skonèil,|øekl jsem, neobtìujte se pøijít protoe jste zlobili.
{16131}{16214}A vy jste doopravdy zaèali bojkotovat školu.
{16241}{16279}To není dobré.
{16315}{16481}Jste zkaení, ale váš zámìr...|Chtìli jste je spolu na školní vılet, huh.
{16600}{16648}Poslouchejte!
{16652}{16753}Kvùli lidem jako napøíklad|Kuninobu zde,
{16757}{16817}je tahle zemnì úplnì zkaená navdy.
{16821}{16967}Tak se dali velké hlavy dohromady| a schválili tenhle zákon.
{16971}{17009}Battle Royale
{17040}{17137}"Take, dnešní hodina je...|"Zabíjíme jeden druhého""
{17178}{17271}Dokud nezùstane jen jeden...|Nejsou ádná pravidla.
{17341}{17399}CO je k smíchu?!!
{17403}{17452}Pane uèiteli,
{17456}{17555}Nerozumím tomu, co øíkáte |To není moné...
{17590}{17691}Ve skuteènosti, váš uèitel Hayashida,
{17694}{17770}hluboce nesouhlasil s vıbìrem tøídy B.
{17937}{17978}Nyní, spí sladce.
{17982}{18048}OK, to je zkaenı èlovìk.
{18052}{18119}Neuèili jste se pøece pilnì,|aby jste pak byli jako on.
{18174}{18284}Je èas podívat se na video|Hlavnì teï neusnìte.
{18325}{18366}Správná cesta k boji|Battle Royale!
{18376}{18435}By the BR Act Committee
{18438}{18506}Ahoj, všichni ve tøídì B!
{18511}{18568}OK, Ahoj!
{18572}{18692}Jste vybraná šastná tøída|pro letošní Battle Royale!
{18696}{18763}Gratuluju! |Díky!
{18768}{18857}Tak. Teï vám vysvìtlím|pár pravidel.
{18861}{18951}Poslouchejte dobøe,|abyste mohli bojovat správnì a s elánem.
{18956}{19058}Jste na opuštìném ostrovì, kterı vypadá takhle.
{19062}{19204}Je skoro 10 kilometrù velkı,| ale evakuovali jsme všechny, take je prázdnı!:-)
{19237}{19283}Øíkal jsem, ádné šeptání!!!
{19478}{19532}Dobøe, pohyb, pohyb
{19645}{19736}Promiò, je protizákonné|zabíjet, není?
{19767}{19870}Dívka #18 Fujiyoushi mrtvá|41 zbıvá.
{20379}{20440}Noriko!
{20444}{20476}Svinì!!!! |Nobu!
{20621}{20663}Nobu!
{20707}{20744}Doprdele!
{20850}{20896}OK, zpìt k videu!
{20925}{20992}Ostrov je rozdìlen na mnoho zón
{20995}{21104}Kadıch 6 hodin váš uèitel|vysílá...
{21108}{21140}Tedy 4 krát za den
{21144}{21258}... o tom, které zóny se stanou nebezpeèné.
{21262}{21361}Kdy budete v nìkteré z tìchto zón,|brzo zemøete...
{21365}{21421}protoe nebezpeèí je...
{21425}{21510}...OK, v obojcích, které|máte na krku.
{21514}{21594}Jsou na 100% vodotìsné|a odolné proti nárazu
{21599}{21653}a trvale..
{21657}{21740}monitorují váš puls|a informují nás...
{21744}{21829}o vaší pozici a pohybech.
{21833}{21910}Take, kdy zùstanete|v nebezpeèné zónì,
{21915}{22039}nebo v pøípadì potíí,|vás mùeme identifikovat a pøenosem rádiovıch vln
{22043}{22138}spustit alarm a boom!!:-)
{22142}{22184}Vybuchne!
{22188}{22308}Kdy se budete snait ho odstranit,|vybuchne taky, take slibte mi, e to nebudete zkoušet OK?
{22332}{22368}Ty hajzle!
{22372}{22435}Sklapni! Neslyšíme video!
{22439}{22472}Sundej to, Nobu!
{22564}{22609}Sundejte to! |Ticho!
{22697}{22742}Opravdu nerad to dìlám...
{22924}{22979}Radìj uteète, hoši. |Co to je?!
{23173}{23212}Pomozte mi !
{23393}{23443}Shuya! |Nobu!
{23960}{23997}Nobu...
{24290}{24382}Hey, Shuya, jsi teï zamilovanı|do dívky?
{24403}{24500}Chlapec #7 Kuninobu mrtvı|40 zbıvá.
{24860}{24899}To je ostuda.
{24919}{24985}Mìl jsem na nìj svùj názor.
{25170}{25233}Na co se díváš, Nanaharo?
{25560}{25601}Oh, zapomnìla jsem na jednu|dùleitou vìc.
{25605}{25690}Je tu herní limit!|3 dny!
{25694}{25766}Kdy nebudeme mít vítìze do 3 dnù,
{25770}{25841}všechny obojky automaticky explodují!
{25845}{25897}A nikdo nevyhraje.
{25901}{26034}U jste toho slyšeli dost.|Tak bojujte tvrdì a nic takového se nemùe stát!
{26054}{26116}OK, nìjaké dotazy?
{26120}{26153}Ano.
{26157}{26193}Yeah, Motobuchi.
{26214}{26294}Kdy pøeiju, mùu jít domù?
{26347}{26442}Samozøejmì, ale všichni ostatní|musí bıt mrtví.
{26498}{26560}Ano. |Ano, Mimura.
{26564}{26624}Jakım zpùsobem jsme byli vybrání?
{26628}{26696}Nezávislım losováním.
{26700}{26763}Ještì nìco?| Ano.
{26779}{26832}Proè tohle dìláte?
{26836}{26891}Je to vaše vlastní chyba.
{26937}{26984}Vy, chlapci, jste se posmívali|dospìlım lidem.
{27009}{27130}Jdìte pøed nás a smìjte se nám|ale nezapomeòte.
{27152}{27207}ivot je hra.
{27211}{27347}Tak bojujte o pøeití | a naleznìte skuteèné hodnoty.
{27757}{27890}Budete opouštìt místnost|jeden za druhım |ale nejdøív dostanete vıbavu.
{27895}{27985}Uvnitø je jídlo a voda.|Mapa a kompas,
{27989}{28106}a baterka a zbraò,|tu si vyzkoušíte pozdìji venku, OK?
{28110}{28218}Dívky mohou uívat osobní vìci,|take si je mùete všechny vzít.
{28222}{28332}Kadá zbraò je jiná. |Pistole|nebo noe...
{28337}{28420}Je to náhodné, tak moná... | ...budete mít štìstí,|moná ne.
{28424}{28497}Odstraòuje to pøirozenou pøevahu.
{28538}{28595}Tahle má extra štìstí!:-)
{28614}{28707}Informujeme vaše rodièe.
{28711}{28801}OK, budete opouštìt tøídu|podle èísla ve vıkazu.
{28805}{28926}"Kdy øeknu vaše jméno, |chci slyšet zøetelnì a nahlas "ZDE"!"
{28954}{29032}Chlapec #1 Akamatsu
{29036}{29073}Zde!
{29251}{29371}Zaèátek hry|Den první 1:40
{29378}{29432}Dívka #1 lnada |Zde!
{29501}{29565}Jsi stále má kamarádka. |Já vím.
{29665}{29727}Chlapec #2 lijima
{29931}{29977}Dívka #2 Utsumi
{30194}{30268}Chlapec #3 Oki
{30434}{30502}Dívka #3 Elo
{30533}{30588}U musím jít, Noriko. |Megumi...
{30707}{30774}Chlapec #4 Oda
{30999}{31066}Dívka #4 Ogawa
{31400}{31446}Chlapec #5 Kawada
{31491}{31529}Kawada!
{31657}{31722}Dívka #5 Kanai
{31828}{31901}Chlapec #6 Kiriyama
{32032}{32066}Postøeh!
{32202}{32236}To je mùj baoh?
{32240}{32278}Co to?!
{32313}{32434}Pravdìpodobnì tušíte, e tihle dva| budou trochu nebezpeènìjší.
{32691}{32757}Dívka #14 Tendo
{32892}{32963}Chlapec #15 Nanahara
{32974}{33020}Nanahara!
{33162}{33209}Poèkám na tebe...
{33897}{33937}Nanahara...
{33967}{34006}Co se ti stalo?...
{34010}{34134}Co mi to udìlali...|Co to je?
{34138}{34176}Tendo!
{34462}{34500}Pozor, Noriko!
{34670}{34729}Kurva, co to dìlám?!
{34797}{34851}Co to dìláš, èlovìèe...
{34913}{34961}Není to tvoje?
{35117}{35161}Je to tvrdá realita...
{35228}{35333}Chlapec #1 Akamatsu mrtvı. |Dívka #14 Tendo mrtvá. 38 zbıvá.
{35573}{35622}Co ruka, je OK?|Byla jsem ztuhlá strachy.
{35626}{35663}Podívám se.
{35733}{35816}Je to jen škrábnutí,|smyju tu krev.
{35870}{35952}Co je to?|Bojovat s poklicí?
{35982}{36063}A tohle je moje...
{36067}{36131}Parchanti...prokletı
{36135}{36231}Tøeba Mimura,|Sugimura a my spolu uteèeme.
{36235}{36286}Nemyslím...|Proè ne?
{36312}{36479}Musíš mì mít rád,|kdy tohle øíkáš, |ale já nevìøím nikomu z nich.
{36510}{36584}Chcípni Noriko!! |Jsi ošklivá zakrslá hnida!
{36821}{36906}Noriko - ošklivá zakrslá hnida. | Proè já?
{36910}{36946}Coe?
{36950}{36990}Tolik se mì bojíš?
{37036}{37138}Jsi jedinı, komu vìøím,|Shuya. Ou, omlouvám se.
{37142}{37179}Proè?
{37183}{37259}Pomalu jsem tì Shuya|pøirovnala k Nobu...
{37390}{37429}Nobu...
{37534}{37600}Hej, Shuyo...
{37628}{37665}Huh?
{37685}{37770}Teï kadého rozdrtíš?
{37774}{37835}Proè myslíš?
{37877}{37984}Moná mám nìkoho rád...
{37997}{38043}Koho?
{38068}{38109}Noriko.
{38182}{38245}Z naší tøídy? |Ano.
{38280}{38337}Je to fajn holka...
{38363}{38414}Vánì? Taky si to myslíš?
{38491}{38575}Je doopravdy milá.
{38621}{38659}Psala mi
{38692}{38757}"Psala: "pøijï zpátky do školy..."
{38790}{38878}Pojedeme spolu všichni na školní vılet.
{38882}{38929}I kdy by to|nemohla bıt pravda...
{38934}{39064}Je milé mít nìkoho,|kdo na tebe èeká.
{39101}{39206}Byli jsme spolubydlící na internátì |po otcovì smrti.
{39238}{39318}Kdy jsem byl tulák|nechal jsem bassebalu,
{39322}{39381}uèil mì hrát na kytaru.
{39425}{39478}Mìl si ho pozvat...
{39482}{39567}Ne, byl šastnı,|vrátil se.
{39601}{39640}Opravdu šastnı...
{39682}{39782}Ale já jsem taky nemohl pomoci Nobu.
{39818}{39913}Potøeboval moji pomoc, ale|byl jsem bezmocnı.
{40033}{40131}Nemùu se s tím smíøit,|Pomstím se za nìj.
{40167}{40253}Ochráním tì a do konce,|na tomhle místì.
{40292}{40395}Dìkuji ti... Nanaharo.
{40456}{40591}Nikdy si neochutnal tyhle|koláèky, e?
{40991}{41054}Numai'siho gang dostal Kiriyama.
{41182}{41223}Neplıtvat èasem.
{41939}{41964}Co je to?
{41992}{42033}Máš dobrou zbraò.
{42055}{42127}Tajemnı pøeloenı studente, |jsi Kitanùv agent.
{42148}{42261}Pøišel si nás zabít, jako ostatní. |Nikdo z nás nikoho nezabije.
{42265}{42334}Mìl bys ses líp umejt
{42338}{42372}Poslouchej!
{42425}{42463}Ty bastarde!
{42643}{42710}Proè... Stop... stop...
{43299}{43393}Chlapec #9 Kuronaga,|chlapec #10 Sasagawa,|chlapec #14 Tsukioka,
{43397}{43442}chlapec #17 Numai,| dívka #3 Kanai mrtvá,|33 zbıvá.
{44075}{44117}Je mi líto
{44121}{44167}Nemùu ti pomoci
{44171}{44249}Né, já jsem ti vdìèná, e si šel se mnou.
{44291}{44340}Co se to s námi dìje?
{44344}{44396}Vím jednu vìc. |Co?
{44418}{44503}Nikdy jsem nechtìla hrát tuhle hru.
{44671}{44716}Nikdo nám nemùe pomoct?
{44789}{44827}Nikdo.
{44906}{44945}Pojïme.
{45190}{45228}Jdeme...
{45281}{45387}Chlapec #21 Yamamoto, dívka #4 Ogawa mrtvá, |31 zbıvá.
{45823}{45858}Mimuro...
{46075}{46117}Kdo je tam?!
{46160}{46224}Oh, to jsi ty, Megumi.
{46228}{46270}Kdo jsi?
{46383}{46423}Mitsuko...
{46452}{46519}Chceš mì zabít s tou paralizaèní zbraní?
{46522}{46588}Co?... oh, promiò.
{46592}{46708}Nikdy jsem nekamarádila|s tvojí partou ale jsi v pohodì.
{46734}{46806}Tak, mùu dál??|Jasnì, pojï.
{47014}{47078}Všechny obrázky Mimury.
{47082}{47122}Oh, ne...
{47167}{47214}To je tvá zbraò?
{47250}{47290}Ne moc uiteèná, huh.
{47294}{47385}Né bezpodmíneènì...|Jeden šok do nìkoho se slabım srdcem...
{47389}{47451}a je znìj napùl mrtvola.
{47455}{47499}Pouívala si ji u nìkdy pøed tím?
{47552}{47593}Samozøejmì e ne, promiò.
{47632}{47674}Tady
{47678}{47725}Mitsuko! Nedìlej to!
{47877}{47977}To je má zbraò,|myslela jsem, e je ubohá...
{47981}{48038}ale momentálnì není tak špatná.
{48078}{48165}Najdeš Yoshimi a|Kuramoto mrtvou pøede dveømi.
{48169}{48231}Povìšené pìknì spolu.
{48235}{48285}Takhle nedopadnu!
{48289}{48334}Já nikdy nechci takhle zemøít!
{48385}{48489}Dívka #3 Megumi,dívka #21 Yoshimi,|chlapec #8 Kuramoto mrtvı,|28 zbıvá.
{49130}{49235}
{49273}{49368}Je právì 6:00. |Pro spáèe, èas na probuzení.
{49415}{49529}Tady je seznam vašich mrtvıch pøátel. |V poøadí podle èasu jejich smrti.
{49590}{49658}Dívka #14 Tendo,
{49675}{49738}Chlapec #1 Akamatsu,
{49743}{49834}#9 Kuronage,|#10 Sasagawa,
{49843}{49943}#14 Tsukioka,|#17 Numai,
{49951}{49999}Dívka #5 Kenai,
{50004}{50120}Chlapec #21 Yamamoto, dívka #4 Ogawa,
{50125}{50162}Chlapec #8 Kuramoto,
{50181}{50295}Dívka #21 Yoshimi, #3 Megumi,
{50302}{50335}Megumi...
{50339}{50404}Nee...proè?
{50408}{50453}Nyní, nebezpeèné zóny.
{50457}{50546}Budu èíst zóny a èas, |tak si pøipravte mapy.
{50555}{50692}Poslouchejte!|Zaèínáme v 7:00, B-5. To je B-5.
{50696}{50763}Další, od 9:00, E-8..
{50770}{50851}pak v 1 1:00, F-2. |Máte to?
{50907}{51019}Je to tìké, kdy kamarádi umírají kolem vás, |ale pochopte to!
{51041}{51067}Zpìt do boje!
{51150}{51210}Noriko. |Megumi's...
{51214}{51308}Tohle bude nebezpeèná zóna. |Musíme jít na jih, pospìš si.
{51792}{51828}Oki?
{51832}{51889}Dostanu tì! Zabiju tì!
{52472}{52510}Oki...
{52702}{52750}jsi OK?
{52771}{52839}Promiò|je mi fajn, fajn.
{53012}{53043}Nanaharo!
{53047}{53158}Zabil jsem ho?|Øekni mi pravdu! Dívala ses!
{53162}{53230}Zabil jsem ho? |Byla to nehoda.
{53266}{53423}X = -b na 2a ...
{53427}{53508}Všichni jsou opravdovı,|huh, pìknì pomalu...
{53512}{53571}Chci pøeít... |jdi do dobré školy...
{53575}{53613}Stop!
{53770}{53812}jdi mi z cesty!
{54068}{54130}Co máte za zbranì?
{54133}{54215}Poklici od hrnce a dalekohled.
{54403}{54442}Všichni!
{54446}{54501}Pøestaòte bojovat!
{54505}{54574}Prosím, poslouchejte nás!
{54594}{54760}tady je Kusaka, s Yukiko, |na útesech na Severní hoøe.
{54765}{54874}Všichni pojïte sem. |Chceme to dotáhnout spoleènì dokonce.
{54878}{54978}Nechceme bojovat|Je to tak, Yukiko?
{55000}{55094}To je Yukiko!|Prosím, pøipojte se k nám.
{55098}{55166}Pøemıšlejme o tom spoleènì...
{55170}{55224}To je ta správná taktika...
{55228}{55280}Kam jdeš?! Pøivedu je zpìt.
{55285}{55323}Beze zbraní?
{55327}{55379}Nejsem tu jedinı zabiják.
{55529}{55591}Ostatní jsou horší kdy jsou v nebezpeèí.
{55725}{55770}Ty!
{55774}{55821}Pøestaò støílet!
{55850}{55916}Idioti! Bì!
{55920}{56025}To je... Nanahara?|To byl jeho hlas, je to tak?
{56029}{56130}Nanahara! |Támhle, pojï sem!
{56135}{56196}Yukiko's tì vdy milovala
{56200}{56242}ty idiote...
{57114}{57152}Kusako!
{57173}{57242}Kusaka! Yukiko!
{57258}{57361}øekni mi, e to není pravda!|Odpovìz mi! Kusako!
{57365}{57417}Teï pùjde sem,|já mizím
{57421}{57528}Jdi kam chceš... |Seš sebevrah!
{57532}{57599}Nanahara... |Byli to mí pøátelé!
{57621}{57733}To je bláznivé! |Jak mùou takhle zabíjet|jeden druhého!
{57737}{57805}Je tam cesta pryè|z téhle hry.
{57824}{57896}Zabijeme se tady, spoleènì,|teï.
{57900}{58015}Jestli to nechceš udìlat,|pak nevìø nikomu.|Jen utíkej..
{58109}{58195}Chlapec #3 Oki, #20 Motobuchi, |dívka #6 Yukiko, #7 Kusaka mrtvá,|24 zbıvá.
{58867}{58968}Druhé hlášení - Poledne.
{59052}{59154}Je poledne!|Všichni jste hladoví?
{59158}{59238}Dejte si od zabíjení malou pauzu na obìd.
{59242}{59331}Nyní seznam tìch, |kdo odešli dnešním ránem.
{59354}{59421}Chlapec #3 Oki,
{59429}{59489}Chlapec #20 Motobuchi
{59496}{59593}Dívka #6 Yukiko, #7 Kusaka.
{59597}{59632}Celkem 4.
{59643}{59746}Volání za mír byl dobrı nápad.|Nemùou vyhrát všichni.
{59750}{59845}Teï nebezpeèné zóny a hodiny.
{59850}{59946}Hodina od teï|do 13:00. l-4.
{59950}{60024}Pak do 15:00 E-9,
{60029}{60081}Od 17:00, F-1...
{60399}{60438}Mitsuko...
{60442}{60487}Hirono.
{60491}{60568}Oh, skvìlé, koneènì jsem tì našla.
{60618}{60678}To je tvá zbraò, Mitsuko?
{60682}{60773}Jo. |Hmm, huh
{60833}{60920}Yoshimi je mrtvá, je to tak?
{60924}{61023}S Kuramoto. |Huh, take si je vidìla.
{61028}{61130}Dobøe, vidìla jsem podøízlou Megumi.
{61155}{61219}Srpem nebo nìèím takovım...
{61261}{61352}Mitsuko!|Ty máš Meguminu zbraò?
{61356}{61395}Samozøejmì e ne.
{61399}{61471}Ale vidìla jsem, jako by|tam v noci nìkdo byl.
{61475}{61538}Našla jsem tampón v toaletì.
{61542}{61610}Megumi... |si je nebrala...
{61647}{61708}Zaèala si vèera, je to tak?
{61742}{61811}Co je to? |Nekecej sraèky, vrahu!
{61850}{61949}Pícháš všechny kluky... |ale okradla si mì!
{61953}{62009}Dìlala si psaèku Yoshimi!
{62013}{62102}Pravdìpodobnì si je obì povìsila! |Jak mùeš...
{62106}{62168}Vyli mi prdel! Zabiju tì!
{62191}{62264}Tak pojï, co je to?
{62268}{62326}Pøestaò vtipkovat, odpust mi.
{62330}{62364}Pøestaò pøedstírat!
{62368}{62452}Prostì se to stalo!|Proè se proti mnì všichni spolèí?!
{62456}{62501}Co jsem mìla dìlat!
{62505}{62576}Pøemıšlet o tom, co jsi udìlala!
{62580}{62651}Myslíš, e s tím mùeš odejít?
{62655}{62738}Vyplaè si oèi!|Omluv se Megumi a Yoshimi!
{62908}{62940}To bylo Megumi.
{62974}{63027}Ale tohle je to, pro co jsem se snaila.
{63032}{63103}Ty dìvko!! Vrahu!
{63107}{63207}Co je špatné na zabíjení? |Kadı má svùj dùvod...
{63313}{63417}Dívka #10 Hirono mrtvá, |23 zbıvá.
{64098}{64170}Noriko, jsi OK?
{64174}{64237}Jsem v pohodì, jen trochu unavená.
{64241}{64342}Teèe z tebe pot...|Máš hroznou horeèku.
{64379}{64473}Yukiko byla do tebe zamilovaná,|je to tak?
{64477}{64518}Co to øíkáš...
{64522}{64603}Promiò, jen trochu árlím, to je vše...
{64607}{64697}Za vesnicí je ošetøovna. |Mùeš vstát?
{64776}{64879}Hej, Noriko...|Pojï u...
{64883}{64921}Noriko!
{65693}{65762}Poklice a dalekohled...|Co chcete?
{66204}{66285}Skvìlı, ještì pravidelnì podávat léky.
{66326}{66372}Mùu se tì na nìco zeptat?
{66376}{66421}Na co?
{66425}{66460}Proè si nám pomohl?
{66464}{66555}Mùj táta je doktor|Mùeš tomu vìøit nebo ne.
{67375}{67412}Pøipraven?
{67470}{67505}Hej rup!
{67623}{67678}Mimura! |Sugimura!
{68019}{68066}Skvìlı, spolehlivì pracuje.
{68070}{68117}Jak si nás našel?
{68121}{68191}"Tohle je má "zbraò". |GPS ?"
{68195}{68236}Skvìlá zbraò.
{68240}{68288}Vidìl jsi Chigusu nebo Kotohiki?
{68292}{68353}Ne, nevidìl.
{68357}{68445}Dobøe... Já mizím... |Pøipraven?
{68449}{68538}Sugimuro, to bude moná|cesta pryè.
{68542}{68582}Chceš nám pomoct?
{68585}{68669}Promiò, ale já je vidìl.
{68673}{68758}Kdy nejdeš Nanaharu, |øekni jim, kde jsme.
{68762}{68833}Dobøe. |Já mizím.
{68938}{69000}Vdycky byl samotáø.
{69004}{69112}Proè se snail najít...| Chigusu a Kotohiki?
{69116}{69167}Myslím, e má rád Chigusu.
{69451}{69521}Sakra, take to je ten jejich trik!
{69525}{69566}Co je to?
{69709}{69757}Poslouchají.
{69810}{69882}Mikrofon v obojku.
{69930}{69997}Tohle je náš plán.
{70016}{70096}Najít následující:
{70108}{70197}1. Hnojivo 2. Pesticidy
{70207}{70260}3. Døevìné uhlí
{70264}{70302}4. Síru
{70311}{70346}5. Benzín
{70362}{70422}Hej, co je to?! |Tak pojï!
{70930}{71013}Chiguso, jak daleko chceš utíkat?
{71017}{71097}Budu vdycky bìet pøed tebou.
{71118}{71171}V tom pøípadì tì budu vdycky chránit.
{71207}{71245}Slibuju!
{72133}{72173}Hiroki.
{72198}{72244}Hej, Chiguso.
{72248}{72289}Co to dìláš?
{72293}{72350}Stále trénuješ?
{72354}{72403}Hej, poèkej.
{72407}{72500}Všichni si o nás povídají. |Za to mùeš ty.
{72504}{72542}Ale tobì se to líbilo.
{72547}{72607}Pojï, Chigusu, poèkej.|Zùstaò se mnou.
{72611}{72701}Nedotıkej se mnì!|Prase!
{72705}{72757}Stùj, nebo støelím.
{72761}{72825}Co je to? Smìšné...
{72846}{72966}Jsem do tebe zamilovanı, |teï, i pøed tím...
{72970}{73081}Wow, skvìlé! |Umyj si ksicht a skus to znovu, jestli pøeiješ.
{73085}{73166}Poèkej, jsi ještì panna, je to tak?
{73211}{73260}Vyli mi prdel!
{73264}{73335}Dobøe, mám snad poslouchat tyhle idioty?
{73339}{73416}Sugimura to s tebou nemohl dìlat.
{73420}{73462}Netahej do toho Hiroki.
{73496}{73553}Stejnì všichni zemøeme.
{73571}{73683}To to nechceš ani jednou zkusit,|døív ne zemøeš?
{73706}{73776}Nedìlej si starosti o mùj ivot...
{73780}{73856}Ještì k tomu kdy jsi|sám takovej uboák?
{73909}{74036}Rozhodl jsem se, e tahle hra je závod. |Take jedu naivo.
{74039}{74096}A jako co?
{74100}{74177}Radìj to chytni správnì,|a nech mì jít
{74197}{74317}Nebo pøedpokládám, e zemøeš, |protoe ti nakopu prdel.
{74395}{74436}Varuju tì.
{74440}{74489}Zavøi hubu!
{74493}{74596}U jsem zabil. |Pøinutím tì násilím,|udìlat to!
{74600}{74637}Zkus to!
{74672}{74714}Jseš...Jseš OK?
{74815}{74878}Škrábnul si mi oblièej.
{74916}{75004}Je to tvoje chyba.|Rozèílila jsi mì.
{75023}{75140}Vdycky viníš nìkoho jiného!|To je to, proè tì nenávidím.
{75346}{75407}Pojï ke mì.
{75411}{75462}Budu s tebou bojovat|a ubráním se ti!
{76756}{76854}Chlapec #16 Niida mrtvı, 22 zbıvá.
{77278}{77316}Hiroki.
{77358}{77448}Chiguso...neumírej. Dr se.
{77452}{77555}Dobøe, jestli je tohle špatnı vtip, |prosím, zastav to.
{77575}{77624}Jsem to já, Chiguso.
{77679}{77717}Hiroki...
{77721}{77762}Kdo tì dostal?
{77766}{77824}Mitsuko.|Dr se od ní dál.
{77848}{77911}Je mi to líto. |Ale co?
{77967}{78074}Minulou noc, èekal jsem na tebe|pøed školou.
{78117}{78192}Pozval jsem tì, je to tak?
{78196}{78273}Volal jsem, ale nevzala jsi to.
{78295}{78408}Já nevím...|Pomùeš mi sednout?
{78663}{78772}Hiroki...|Jsi do nìkoho zamilovanı?
{78808}{78849}Ano.
{78874}{78913}Ne do mnì, e?
{78970}{79007}Ne...
{79053}{79162}Tak zùstaò se mnou, jako jsi teï.
{79179}{79220}Nebude to dlouho.
{79338}{79473}Dobøe, mùe mi ještì|nìco øíct?
{79583}{79653}Vypadáš vánì skvìle, Hiroki...
{79697}{79800}Jsi ta nejkrásnìjší|holka na svìtì.
{79888}{79926}Díky...
{80193}{80230}Chiguso...
{80554}{80703}Dívka #13 Chigusa mrtvá,|21 zbıvá
{81161}{81258}Je 6 hodin.|Tady je seznam mrtvıch.
{81262}{81334}Dívka #10, Hirono.
{81339}{81406}Chlapec #16 Niida.
{81411}{81504}Dívka #13 Chigusa|Celkem 3.
{81511}{81597}Zvolnili jste.|Zklamal jsem se ve vás.
{81601}{81667}Pøidávám víc nebezpeènıch zón.
{81671}{81776}Kadou hodinu pøibude nová,|tak se jim vyhnìte!
{81780}{81901}Od 19:00 D-1,|Od 20:00 C-4.
{81905}{81971}I-3 od 21:00.
{82094}{82184}Chutná to dobøe. |Jo, jistì,|mùj táta je šéfkuchaø.
{82288}{82326}Um...
{82380}{82456}Dìkuji ti za všechno.
{82500}{82553}Napiješ se?
{82557}{82593}Ne...
{82878}{82922}Nechtìl jsem ...
{82949}{83042}Ale myslím, e bych vám mìl nìco ukázat...
{83229}{83283}Je nádherná...
{83287}{83356}Stejnì stará? |Stejná tøída.
{83378}{83459}9t tøída, Kobe Jr High #5,|tøída C.
{83463}{83537}Hráli jsme tuhle hru pøed tøemi lety.
{83541}{83614}Take jsi... |Jsem vítìz...
{83643}{83694}tıhle zkurvenı hry.
{83743}{83828}Hroznì jsem chtìl ochránit Keiko.
{83861}{83907}Dokonce zabít pøátele...
{83924}{83986}take 2 z nás mohli pøeít.
{84419}{84497}Ale kdy mohl pøeít jen|jeden z nás...
{84501}{84536}zmìnili jsme ...
