{1}{1}23.976
{318}{384}-Kdo to byl, e mì vedl za ruku?-
{384}{471}-Dìtské vzpomínky...-
{525}{697}-Vdycky kdy jsem se vzbudil, mé sny zmizely, pomíjivì jako bublina.-
{732}{915}-Vyléèím tvùj nekoneènı smutek.-
{915}{1075}-My, kdo nemùeme ít osamìle.-
{1131}{1224}-Co mùeme vidìt za naším osudem?-
{1224}{1325}-Pøíbìh o oslnivé slávì.-
{1325}{1502}-Sny v mé levé ruce, a drící se tì svou pravou,-
{1538}{1635}-chci záøit jako úsvit.-
{1635}{1738}-Pøíbìh o oslnivé slávì.-
{1738}{1921}-To vzácné svìtlo je v mé ruce...-
{2596}{2637}Prosím omluvte mì, Vaše Velièenstvo.
{2716}{2823}Orpherus od Markıze Görze se uchází o audienci.
{2847}{2882}Jak mám odpovìdìt?
{3043}{3077}VÍTÌZ
{3301}{3416}Um... co je zanecháno v Kuchenské historii, vìda, a jazyk...
{3443}{3480}Proè je jich tak moc?!
{3564}{3704}Není to jako, e se mùeme stát kandidáty Strahl,|tak proè musíme skládat zkoušku?
{3704}{3739}Nemáme na vıbìr.
{3739}{3891}Nejen kandidáti Strahl, ale všichni studenti budou|rozdìleni do tøíd zaloenıch na jejich schopnostech.
{3891}{3996}No, já vím, ale... Nelíbí se mi to.
{3996}{4071}Ale Orpherus a ostatní budou v poøádku, jsem si jistá!
{4071}{4153}Jsou vzdìlaní a velmi kultivovaní!
{4201}{4299}A já jsem si opravdu myslela, e novı|øeditel byl vıznamnı mu...
{4546}{4557}Zaènìte!
{4929}{4943}Tady pøestaòte!
{5029}{5058}Dáme si krátkou pøestávku.
{5112}{5139}To bylo tìsné.
{5139}{5177}Skoro jsi ho mìl.
{5227}{5260}Jen o malı kousek víc a mìl bych...
{5260}{5375}Jo, opravdu! Není èasté, e nìkdo |mùe tak moc zatlaèit Orpha.
{5375}{5410}Správnì, Orphe?
{5410}{5448}Jo. Na chvíli jsem se bál.
{5468}{5489}Pøesnì jak jsem èekal.
{5502}{5531}Prohra je prohra.
{5614}{5704}Teï chápu, jak tìce jsi pracoval.
{5764}{5825}Nikdy jsem nevidìl tak nedbalé šermování.
{5845}{5925}Musí to bıt proto, e se nikdy neuèil pod poøádnım uèitelem.
{5925}{5998}Ani se nepøibliuje Luimu krásnému šermu.
{5998}{6054}Hej! Není ádnı dùvod takhle mluvit!
{6124}{6161}Vy chlapi mì nikdy nepøestanete udivovat.
{6161}{6286}Jen protoe mì nikdo z vás nemùe porazit|s vaší silou, mì nesrovnávejte s ostatními lidmi.
{6312}{6391}Jestli o mì ani neumíte mluvit špatnì|bez vypùjèení vlivu nìkoho jiného,
{6391}{6440}nemyslíte si, e moná nejste pro Strahl stvoøení?
{6468}{6504}Jen jim odpus, Nicholasi.
{6522}{6651}Na svìtì jsou lidé, kteøí odmítají pøijmout realitu|dokud je úder pøed jejich oèima.
{6666}{6752}Jakmile bude zkouška u konce, budou donuceni|porozumnìt, zdali se jim to líbí nebo ne.
{6766}{6790}Jak se opovauješ tohle øíkat!
{6818}{6850}Chceš to vyøešit teï?
{6864}{6898}Oba dva, okamitì pøestaòte!
{6938}{6981}Jsme uprostøed zkoušky.
{7005}{7038}Vy dva jste zašli také daleko.
{7195}{7237}Budeme pokraèovat ve zkoušce.
{7404}{7465}Wow, tohle je úasnı pár.
{7709}{7786}Nevadí mi to. Vrhni se na mì v jakékolii formì je tvá silná stránka.
{7820}{7941}Rozhodnout tvou skuteènou schopnost meèem, mìl bys |bıt ohodnocen pouíváním stylu šermu, kterı ti nejvíce sedí.
{7956}{7978}Ale...
{7978}{8015}Hej, Naoji!
{8440}{8510}Zamıšlí bojovat s Ludwigem s døevìnım meèem?
{8531}{8603}Øíkali, e šermuje v japonském stylu.
{8616}{8667}A je docela silnı.
{8964}{8984}Zaènìte!
{9094}{9123}Pøesnì jak bych èekal.
{9123}{9157}Nìdìlá ádné zbyteèné pohyby.
{9157}{9188}Oba dva to myslí smrtelnì vánì.
{9354}{9393}To není všechno, co máš, e?
{9417}{9507}Uka mi všechno co máš, Naoji!
{10075}{10101}Ta-Tady pøestaòte!
{10151}{10217}Tvùj šerm je opravdu krásnı.
{10234}{10290}Skoro jsem jím byl uchvácen.
{10346}{10359}Lui...
{10446}{10526}Nemyslel jsem si, e by to byl tak vánı boj.
{10526}{10597}Úplnì jsem oèekával pøedem naplánovanou šarádu.
{10638}{10684}Stejnì, nerozumím.
{10684}{10769}Proè se chceš pøidat do Strahl?
{10769}{10829}Nemáš ádnı úmysl pøísahat vìrnost této zemi, správnì?
{11223}{11266}Také to všechny mùete cítit, e?
{11343}{11416}Ano, také jsem smutnı.
{11416}{11525}Je to jako by se školní atmosféra zmìnila...
{11525}{11617}Proè spolu musí všichni navzájem soutìit?
{11773}{11829}Vyrušil jsem tì? Omlouvám se.
{11848}{11915}Elmute! Ne, vùbec mì nerušíš.
{11935}{12001}Všiml jsem si, e si's také nevybral šerm.
{12001}{12042}Také nemám rád takové vìci.
{12042}{12066}Opravdu?
{12102}{12128}Jsou naprosto krásné.
{12146}{12190}Staráš se o nì?
{12190}{12273}Ano. Opravdu je miluji.
{12293}{12362}Ale právì teï se cítí trochu zachmuøenì.
{12392}{12467}Mùou cítit silnı školní tlak.
{12467}{12493}Chudinky...
{12532}{12601}Sám rád pìstuju rostliny.
{12623}{12690}Mìl jsem ve zvyku dìlat doma malé záhony na své zahradì.
{12690}{12720}To je bájeèné.
{12741}{12804}Zajímá mì, proè se vìci obrátily tímto zpùsobem.
{12804}{12854}Studenti spolu navzájem bojují...
{12854}{12919}Také nemám rád zápasy.
{12943}{12960}Ale...
{12987}{13074}Udìlám cokoli, abych se stal kandidátem Strahl.
{13338}{13397}Nemùu uvìøit, e jsem prohrál s nìkım takovım...
{13489}{13560}Oh, boe. Taková mizerná atmosféra.
{13560}{13609}Je to kadı den horší.
{13609}{13665}Chápu, e je to nevyhnutelné, ale...
{13683}{13744}Kdy u o tom mluvíme, Camus|dnes zase vypadal pod psa.
{13785}{13824}V takové atmosféøe, no...
{14111}{14129}Came?
{14161}{14188}Profesore Geralde!
{14247}{14300}Co dìláš tady venku? Dìje se nìco?
{14317}{14370}Ne, nic...
{14370}{14402}Tvùj oblièej je pøíšernì bledı.
{14426}{14475}Pojïme dovnitø, dobøe?
{14503}{14519}No tak.
{14757}{14785}Profesore Geralde.
{14835}{14873}Ano?
{14873}{14942}Proè lidé bojují?
{14942}{15041}Všichni ví, jak smutná vìc je|si navzájem ubliovat, a ještì...
{15265}{15384}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{15419}{15504}Tedy, zkouška pokraèuje hladce?
{15504}{15636}Ano, pane. Studenti pracují tvrdì, aby|vykonali vaše brilantní reformy...
{15671}{15697}Vstupte.
{15763}{15833}Omluvte mì. Mám vìc, kterou bych si pøál prodiskutovat.
{15833}{15894}Jsme uprostøed zkoušky.
{15894}{15938}Vstup do kanceláøe øeditele není povolen...
{15938}{15960}To je v poøádku.
{15960}{15979}Co je to?
{15979}{16028}Je to o zkoušce.
{16028}{16125}Co si myslíte o souèasném stavu|školní pùdy, Øediteli Wernere?c
{16148}{16239}Zdá se, e zde bylo nìkolik konfliktù mezi studenty.
{16239}{16377}Zobrazování plného rozsahu schopností jednotlivce|a pøijímání férového soudu.
{16377}{16453}Já, také, vìøím, e je to pozitivní vìc.
{16453}{16569}Ale je to pøíliš náhlé a všichni jsou zmatení.
{16569}{16662}Touto rychlostí bude nejen celá školní|pùda vhozena do nepoøádku,
{16662}{16767}ale na budoucnost studentù to mùe vrhat stíny.
{16788}{16842}Není to podceòování?
{16877}{17016}Studenti Akademie Rosenstolz nejsou tak slabí,|e by váhali nad nìèím takovım.
{17031}{17096}Toto je nìco nezbytného pro reformu.
{17096}{17236}Samozøejmì, vìøím, e je to nìco, co|pøinese budoucnosti studentù prospìch.
{17236}{17254}Ale...!
{17254}{17385}Rád bych slyšel více o tvém názoru, ale |právì teï, domnívám se, e toto má pøednost.
{17447}{17522}Toto je dopis pro tebe z královského paláce.
{17522}{17543}To je...?
{17543}{17617}Oznámení, e povolení o audienci bylo udìleno.
{17632}{17682}ádal jsi o nìj, ne?
{17708}{17725}Ano, pane.
{17743}{17816}Nicménì, datum je zítøejší odpoledne.
{17832}{17896}Stále ti zbıvá koneèná zkouška, ne?
{17896}{17968}Ujistím se, e se vrátím pøed èasem zkoušky.
{17968}{18037}Poèkej chvilièku! Takové sobectví nemùe bıt...!
{18037}{18103}Prosím, dovolte mi s vámi mluvit jinı den.
{18103}{18124}Omluvte mì.
{18222}{18326}Jste si jistı, e dovolovat toto nestoudné chování je vhodné?
{18326}{18446}Aèkoli je moná kandidát Strahl, mìl odvahu|kritizovat nápady øeditele!
{18446}{18499}To je v poøádku, Eilosi.
{18499}{18639}Myslím, e úèinkem mluvit smìle o tom, v co|jeden vìøí, je správné a úasné.
{18639}{18666}Ano, pane...
{18683}{18751}Nicménì jsou stále mladí.
{18751}{18874}Od teï budou muset získat schopnosti|prohlíet vìci ze všech úhlù,
{18874}{18956}a je naší povinností jako profesorù provázet je v tomto úsilí.
{19023}{19150}Nemyslíš, Eilosi, e by mìli dostat|takové vzdìlání tak brzy, jak je to moné?
{19296}{19374}Ano, vskutku. Je to v jejich nejlepším zájmu.
{19374}{19445}Jako profesor je budu uèit nepoddajnosti skuteènosti.
{19896}{19953}Dìlej, cokoli musíš dìlat, jen ho zdr.
{20408}{20423}Ede.
{20450}{20465}Pojïme.
{20693}{20742}Prosím poèkejte tady.
{20742}{20755}Dìkuji.
{21049}{21081}Prosím pokraèujte do Audienèní Sínì.
{21111}{21195}Není to brzy? Nemyslel jsem si, e u by byl èas.
{21507}{21658}...nicménì, by mìly bıt dány pøísnìjší pøedpisy|na místa cizích lodí hledající vstup do našich pøístavù.
{21658}{21720}Souèasná situace nás nechává otevøené do nebezpeèí.
{21720}{21872}Vìøím, e toto je jedinı zpùsob, jak |se ochránit od zahranièních nepøátel.
{22009}{22092}Právì teï, je pravdìpodobnì znepokojenı tím,|proè není na audienci u Jeho velièenstva.
{22092}{22132}Ale samozøejmì, byl vyzván.
{22132}{22195}Nikdy by neodešel a nevrátil se sem.
{22214}{22329}Kdyby nemohl skládat zkoušku, nemohl by se stát kandidátem.
{22377}{22437}Take ti dva ještì opravdu nejsou zpátky?
{22437}{22534}Ne, nejsou. Ale øíkal, e by se mìl|vrátit pøedtím, ne zkouška zaène.
{22551}{22596}Jestli nedorazí vèas...
{22799}{22824}Je tu nìco divného!
{22840}{22906}Pøišli jsme právì v pøedepsanı èas.
{22906}{22948}Proè nás nechávají èekat tak dlouho?
{22948}{22974}Uklidni se, Ede.
{22974}{23014}Jeho Velièenstvo je velmi zamìstnáno.
{23014}{23077}Mùeme bıt vdìèní, e i tak souhlasil, e se s námi sejde.
{23077}{23145}Já vím, ale nemáme èas!
{23145}{23165}Touhle rychlostí...
{23165}{23218}I tak, já budu èekat.
{23250}{23269}Ty jeï zpátky.
{23269}{23356}Nebuï idiot! Nikdy bych nejel zpátky sám!
{23370}{23427}Obávám se o pøedchozího øeditele tak, jako ty!
{23450}{23471}A kromì toho...
{23545}{23651}Kdybys tu nebyl, pak by nebyl ádnı smysl|stát se kandidátem Strahl!
{23666}{23685}Ede...
{23714}{23748}Je to pravda?
{23859}{23920}Chtìl bych se zeptat, jestli Jeho Velièenstvo ještì jednou znovu uváí ten bod...
{24246}{24306}My... teï nedorazíme vèas.
{24331}{24346}Ede.
{24363}{24457}I kdybych se kvùli tomu nemohl pøipojit ke Strahl, nièeho nelituji.
{24495}{24572}Myslím, e tohle je to, co teï musím udìlat.
{24620}{24694}Spojení se Strahl není jediná cesta.
{24694}{24785}Mùu pro sebe otevøít cestu, kterou uchopím.
{24864}{24895}...spoleènì s tebou, správnì?
{25030}{25053}Máš pravdu.
{25075}{25166}Jestli se staneme kandidáty Strahl nebo ne, pùjdu s tebou.
{25239}{25307}Nejupøímnìji se omlouvám, e jsem vás nechal èekat.
{25307}{25355}Zdá se, e jsme udìlali chybu.
{25355}{25399}Jeho Velièenstvo se s vámi setká okamitì.
{25621}{25746}Take je pravda, e pøedchozí øeditel,|Bartholomäus, zmizel?
{25746}{25857}Ano. Zmizel beze slova.
{25893}{25974}Mohlo by Vaše Velièenstvo pouít svou moc k jeho hledání?
{25974}{26022}Nemùu na to odpovìdìt.
{26022}{26054}Vaše Velièenstvo?
{26097}{26245}Byl to mùj nenahraditelnı pøítel od té doby,|co jsem byl studentem Akademie Rosenstolz.
{26268}{26333}Také ho nechci ztratit.
{26450}{26539}Ale právì teï... Nemohu dìlat nic, jen se modlit za jeho bezpeèí.
{26786}{26841}Jeho Velièenstvo nìco skrıvá.
{26841}{26925}Jo. Ale nevypadal jako, e nám øekne, co to je.
{26945}{26974}Co udìláme?
{26974}{27020}Touto dobou je zkouška...
{27129}{27171}Rychle! Nastupte!
{27171}{27209}Profesore Geralde!
{27209}{27241}Proè jste tady?
{27241}{27267}Mùeme mluvit pozdìji!
{27267}{27291}Pospìšte!
{27594}{27659}Je na èase. Teï tedy...
{27821}{27888}Pøijeli jsme pozdì. Omlouvám se.
{28566}{28674}Gratuluji všem. Jste noví kandidáti Strahl.
{28699}{28792}Ale toto je jen jeden novı krok smìrem k budoucnosti.
{28808}{28880}Tìším se na pokraèování vaší tvrdé práce.
{29495}{29527}U je to nìjakou dobu.
{29620}{29654}Co tím myslíš?
{29654}{29729}ádnı z nás si nepøeje vidìt toho druhého.
{29746}{29801}Je to ode mì špatné, chtít s tebou mluvit osobnì?
{29889}{29913}To není tøeba.
{29935}{29984}Musíš èinit jen tak, jak jsem ti øekl.
{30023}{30079}Jsem vdìènı za tvou spolupráci...
{30110}{30164}...bez ohledu na dùvod.
{30263}{30309}Myslel si's, e by se's mohl usmíøit?
{30400}{30456}Na to je pøíliš pozdì...!
{30680}{30806}I tak, já... nemùu udìlat nic jiného. Beruze.
{31520}{31634}-Oslnivá obloha, západ slunce.-
{31634}{31761}-Hráli bychom si pod poulièními lampami.-
{31783}{31896}-V mrazivou noc, lustr visí z oblohy-
{31896}{32040}-pomalu se hupající.-
{32065}{32289}-Mùj hlas existuje jen, aby volal tvé jméno.-
{32289}{32552}-Pevnì svírám tvé malé, tøesoucí se prsty...-
{32552}{32687}-Èas pro nás dva zaèal ubíhat,-
{32687}{32809}-netøeba nièeho, ani slov.-
{32809}{32932}-Oh, pták zavøenı v kleci, tvá køídla naproti tvım òadrùm.-
{32932}{33063}-Tato obloha poslala toho ptáka tobì...-
{33456}{33477}Náhled Pøíští Epizody
{33519}{33631}Lehká hudba. Oznámení. Neshoda.
{33662}{33724}Nemáš ádnı dùvod váhat!
{33770}{33798}NETRPÌLIVOST
