{1}{1}23.976
{315}{380}-Kdo to byl, e mì vedl za ruku?-
{380}{472}-Dìtské vzpomínky...-
{521}{694}-Vdycky kdy jsem se vzbudil, mé sny zmizely, pomíjivì jako bublina.-
{727}{911}-Vyléèím tvùj nekoneènı smutek.-
{911}{1073}-My, kdo nemùeme ít osamìle.-
{1125}{1218}-Co mùeme vidìt za naším osudem?-
{1218}{1325}-Pøíbìh o oslnivé slávì.-
{1325}{1501}-Sny v mé levé ruce, a drící se tì svou pravou,-
{1536}{1637}-chci záøit jako úsvit.-
{1637}{1742}-Pøíbìh o oslnivé slávì.-
{1742}{1904}-To vzácné svìtlo je v mé ruce...-
{2716}{2756}Vdycky mì zajímalo...
{2770}{2885}...jestli by se na mì jednoho dne usmála.
{2906}{2960}I jen malı úsmìv.
{3050}{3202}Aèkoli je to pøání bez nadìje stát se skuteèností,
{3245}{3291}jestli by ten den pøišel...
{3445}{3496}CHLADNİ DÉŠ
{3659}{3695}Jsi v poøádku, Came?
{3729}{3807}Neboj se o mì. Musíš jet za Edem, rychle!
{3807}{3870}Stalo se mu nìco?
{3892}{3911}Nevím.
{3964}{4062}Ale je kolem nìj velmi temná pøítomnost.
{4079}{4146}Touto rychlostí ho to pohltí...
{4212}{4237}Jen vy dva?
{4312}{4341}Ed tu není?
{4386}{4402}Nicholasi?
{4424}{4456}Máš s Edem nìjakou záleitost?
{4456}{4490}Já ne.
{4490}{4573}Je tu pro Eda návštìvník, tak ho jen hledám.
{4591}{4607}Návštìvník?
{4640}{4714}Nejváenìji se omlouvám. Zdá se, e zde také není.
{4909}{4949}Vikomt Braunschweig!
{5093}{5164}Take jste byl v paláci, Vikomte?
{5164}{5192}To je pravda.
{5192}{5307}Jel jsem na sluební záleitost, ale dostal |jsem tento dopis, kdy jsem byl tady.
{5436}{5498}"Bezpeèí vašeho syna je ohroeno."
{5577}{5649}Po pøeètení jsem spìchal sem, ale..
{5708}{5738}Stalo se nìco?
{5738}{5796}Naoji, postarej se za mì o Cama.
{5796}{5837}Co se dìje?
{5858}{5927}Musím jet za Edem.
{6037}{6084}Prosím nechej zbytek na mnì.
{6111}{6130}Spoléhám na tebe.
{6162}{6178}Pùjdeme?
{6178}{6191}Ano.
{6418}{6470}Nikdy jsem ho nevidìl tak znepokojeného.
{6470}{6494}Co se dìje?
{6533}{6563}Neznám detaily.
{6581}{6635}Ale zdá se, e se nìco stalo Edovi.
{6651}{6665}Oh?
{6686}{6790}Pak ten s ním je pravdìpodobnì|Edùv otec, Vikomt Braunschweig.
{6790}{6868}Všichni nakonec vìdí o skandálu té rodiny.
{6888}{6967}Moná mají víc nìjakıch rodinnıch problémù?
{6967}{7051}Pøestaò. Jen máš legraci z dìlání takovıch teorií.
{7051}{7094}To je tvùj zlozvyk.
{7116}{7260}Obousmìrnì to jen ukazuje, e i|šlechtické rodiny nejsou úplnì stabilní.
{7751}{7765}Tady máš.
{7793}{7880}Pití nìèeho teplého ti pomùe se uklidnit.
{7898}{7912}Dìkuji.
{7930}{8097}A? Oprherus doprovázel Vikomta Braunschweiga|na jeho zpáteèní cestì na jeho panství?
{8097}{8166}Ano, doprovázel. Co by to všechno mohlo znamenat?
{8166}{8276}Zpráva, která pøišla Edovi, øíkající, e jeho otec|je v kritickém stavu pøišla z Edova vlastního domu!
{8298}{8351}Past... Jsem si jistı.
{8434}{8559}Znamená to, e pøišel èas skoncovat s tìmi vìcmi.
{8577}{8702}Eduard utíkal pryè po celou tu dobu, aèkoli|ve svém srdci vìdìl, co musí bıt uèinìno.
{8730}{8783}Není ádné pøekvapení, e se to nakonec stalo.
{8797}{8854}Zajímá mì, co Ed zamıšlí udìlat...
{8879}{8983}Nemùe bıt rozhodnuto, jestli neèelí tomu problému.
{9075}{9135}Je špatné utéct?
{9135}{9164}Came?
{9282}{9359}Všichni nejsou silní jako ty, Lui.
{9359}{9391}Came...
{9444}{9465}Omlouvám se.
{10247}{10260}Ede...
{10303}{10328}Je to moje chyba.
{10388}{10412}Vikomte...?
{10628}{10712}Naše rodiny uspoøádaly mou svatbu s mou enou.
{11612}{11720}Povaoval jsem, e je to v mé pøirozené povinnosti jako toho,| kdo by byl nástupcem hlavy vikomství.
{11765}{11907}Narodily se mé dcery, a já jsem si myslel,|e jsem il ivot v úplném uspokojení.
{12039}{12075}To bylo, kdy jsem potkal ji...
{12344}{12433}Bylo to poprvé, co jsem opravdu zail štìstí.
{12506}{12620}Poté co zemøela, neváhal jsem v adoptování jejich dìtí.
{12645}{12756}Myslel jsem si, e kdy to udìlám, udìlal bych nìco|pro enu, kterou jsem udìlal neúspìšnì šastnou.
{12810}{12841}Ale bylo to...
{13448}{13515}A pak moje ena...
{13759}{13780}Lorde Eduarde!
{13825}{13865}Je mùj otec v poøádku?
{13865}{13951}Pán je pryè na návštìvì paláce.
{14123}{14186}Podívejte jak jsme mokrı! Nachladíte se!
{14186}{14245}Pøipravím okamitì horkou koupel.
{15049}{15162}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{15419}{15434}Ede...
{15527}{15600}No tak! Hodnı kluk. Jen se teï uklidni.
{15616}{15680}Omluvte mì, mohl byste nám pùjèit koèár?
{15696}{15751}Oh, Lorde Orphere!
{15768}{15827}Máte plány s Panem Eduardem?
{15843}{15878}Ed sem pøišel?
{15878}{15977}Ano, pøišel. Vlastnì, pùjèil jsem mu tohoto konì.
{15996}{16045}Ale kùò se vrátil sám.
{16113}{16219}Byl z nìjakého dùvodu velmi rozrušenı. |Mám plné ruce toho, jak se ho pokouším uklidnit!
{16284}{16303}Vypùjèím si ho.
{16317}{16365}Pojedu napøed.
{18105}{18145}Prosím buï v poøádku, Ede!
{18603}{18631}Jak se mají mé sestry?
{18664}{18707}Jsou ve vile.
{18920}{18974}Otec je v poøádku, e.
{18988}{19058}Dìlá nìjakou práci v paláci.
{19058}{19107}Nic se nezmìnilo.
{19183}{19266}Jsem v tvıch oèích opravdu taková pøekáka?
{19303}{19422}Jestli opustíš tento dùm...
{19682}{19745}øeknu ti, co chceš vìdìt.
{19808}{19886}Hledáš svou malou sestru, která byla dána k adopci, e?
{19914}{19939}Víš, kde je?
{19939}{20030}Tíha tohoto vikomství je na tebe pøíliš tìká.
{20030}{20088}Chápeš to, e?
{20130}{20210}Vdycky se na mì díváš svıma zvìdavıma oèima...
{20271}{20470}Vikomství Braunschweig by mìlo bıt zdìdìno tìmi|se správnou krví: mımi dcerami a jejich dìtmi.
{20497}{20532}Ano, to je pravda.
{20558}{20606}Ne dítìtem té eny...!
{20813}{20876}Teï. Øekni, e se vzdáváš svého titulu.
{21352}{21449}Je pravda, e i teï hledám svou mladší sestru.
{21480}{21538}Chci ji zase vidìt, bez ohledu na to, co musím udìlat.
{21649}{21770}Ale zaèal jsem kráèet touto cestou podle své vlastní|vùle, a chci jí kráèet dál.
{21835}{21902}Neskloním se pøed tvımi poadavky.
{21951}{22027}Mìl jsem s tìbou mluvit døíve.
{22079}{22219}Vìdìl jsem, e pøíchod mì a mé sestry zde znièí tvé štìstí.
{22219}{22403}A myslel jsem si, e uklidnit tvé utrpení,|mìl bych udìlat tvé pøání skuteèností.
{22434}{22471}Ale to nebyla pravda.
{22493}{22557}Nebylo to pro tebe dost...
{22657}{22702}Nepotøebuji tvùj soucit.
{22750}{22782}Kdybys jen...
{22848}{22866}zmizel...!
{23252}{23264}Ede!
{23683}{23782}Prosím nedìlej nìco, co udìlá mé sestry a otce smutné!
{23881}{23895}Henriette!
{24205}{24227}Odpus mi.
{24363}{24409}Zpùsobil jsem ti tolik bolesti.
{24562}{24578}Ede.
{24591}{24634}Znepokojil jsem tì, e.
{24634}{24696}Jestli jsi v poøádku, to je vše na èem záleí.
{24753}{24770}To je...
{24852}{24871}Zapomeò na to.
{25049}{25068}Eduarde.
{25174}{25246}Je pravda, e jsem se na tebe vdycky díval.
{25282}{25407}Protoe jsi mìla ve svıch oèích smutnı pohled,|a já jsem vedìl, e je to kvùli mnì.
{25463}{25509}Nebylo nic jiného, co jsem mohl dìlat.
{25551}{25597}Nemohl jsem najít slova, která jsem ti mohl øíct...
{25673}{25755}Nikdy jsem necítil, e tì nenávidím.
{25777}{25837}Bez ohledu na to, co si o mnì moná myslíš.
{25898}{25914}Matko.
{26793}{26846}Dostal jsem zprávu od Orphera.
{26863}{26894}Ed je v poøádku.
{26917}{26937}Jsem rád.
{27096}{27150}Promiò, Elmute.
{27184}{27200}To je v poøádku.
{27294}{27420}Poèítal jsem, e budeš znepokojenı tím, co|jsem ti øekl naposledy, co jsme mluvili.
{27466}{27533}Zajímá mì, proè se vìcí obrátily tímto zpùsobem.
{27533}{27576}Studenti spolu navzájem bojují...
{27576}{27633}Také nemám rád zápasy.
{27665}{27681}Ale...
{27711}{27799}Udìlám cokoli, abych se stal kandidátem Strahl.
{27986}{28054}Jsi citlivı k lidskım srdcím.
{28054}{28102}Nejsi vhodnı k bojování.
{28121}{28139}Já...
{28174}{28224}Myslím, e jsi v poøádku tak jak jsi.
{28248}{28320}Ale já mám cíl, kterého chci dosáhnout.
{28320}{28366}A nikomu se nevzdám.
{28427}{28527}Opravdu se chci stát tvım pøítelem.
{28527}{28578}Aèkoli se zdá, e to teï není moné...
{28920}{28958}Selhal, chápu...
{28958}{29065}No, tak to je. Dostal jsem, co jsem chtìl.
{29065}{29131}Teï pøeil dvakrát.
{29157}{29220}Vskutku musí mít velmi dobré štìstí.
{29254}{29349}Nebo pravdìpodobnì... má neoèekávaného spojence?
{29368}{29463}V kadém pøípadì, nejsi zaujatı, e madam je... hovorná?
{29486}{29531}Pokryl jsem naše základy.
{29531}{29710}Jestli se tento dokument zveøejní, její vzácné|vikomství nevyjde nezranìno.
{29710}{29745}Kdy to øíkáš.
{29778}{29900}Jen bych nesnášel vidìt misi zøícenou, kvùli nìèím osobním emocím.
{30334}{30425}Opravdu se cítím, e jsme zpátky, eh?
{30425}{30510}Nakonec, teï je to náš domov.
{30527}{30542}Jo.
{30560}{30596}Orphe! Ede!
{30627}{30680}Hej, Naoji! Promiò, e jsem tì znepokojil...
{30680}{30753}Camus opustil akademii!
{30797}{30815}Camus odešel...?
{31520}{31633}-Oslnivá obloha, západ slunce.-
{31633}{31756}-Hráli bychom si pod poulièními lampami.-
{31779}{31892}-V mrazivou noc, lustr visí z oblohy-
{31892}{32037}-pomalu se hupající.-
{32065}{32288}-Mùj hlas existuje jen, aby volal tvé jméno.-
{32288}{32543}-Pevnì svírám tvé malé, tøesoucí se prsty...-
{32543}{32684}-Èas pro nás dva zaèal ubíhat,-
{32684}{32806}-netøeba nièeho, ani slov.-
{32806}{32931}-Oh, pták zavøenı v kleci, tvá køídla naproti tvım òadrùm.-
{32931}{33062}-Tato obloha poslala toho ptáka tobì...-
{33456}{33477}Náhled Pøíští Epizody
{33513}{33633}Rodina. Krásné kvìtiny. Klidné dny.
{33663}{33726}Kam bych se mìl vrátit?
{33769}{33793}RÁJ
