{1}{1}23.976
{315}{386}-Kdo to byl, e mì vedl za ruku?-
{386}{470}-Dìtské vzpomínky...-
{522}{692}-Vdycky kdy jsem se vzbudil, mé sny zmizely, pomíjivì jako bublina.-
{728}{908}-Vyléèím tvùj nekoneènı smutek.-
{923}{1075}-My, kdo nemùeme ít osamìle.-
{1122}{1219}-Co mùeme vidìt za naším osudem?-
{1219}{1325}-Pøíbìh o oslnivé slávì.-
{1325}{1497}-Sny v mé levé ruce, a drící se tì svou pravou,-
{1536}{1630}-chci záøit jako úsvit.-
{1630}{1737}-Pøíbìh o oslnivé slávì.-
{1737}{1914}-To vzácné svìtlo je v mé ruce...-
{2242}{2267}Šel ven?
{2267}{2379}Ano. Zdál se bıt hluboce zamyšlenı...
{2379}{2411}Proè jste ho nezastavili?
{2411}{2453}Okamitì ho hledejte.
{2619}{2633}Came...
{3010}{3063}ZAÈÁTEÈNÍ BOD
{3245}{3333}Musíte bıt bez Cama také osamìlé.
{4027}{4071}To je mùj dùm.
{4284}{4311}Elmunte-niisan!
{4311}{4340}Vítej doma!
{4340}{4363}Jsem zpátky.
{4468}{4539}To je mùj malı bráška, Franz, a má mladší sestra, Nina.
{4559}{4623}Tìší mì, Franzi, Nino.
{4643}{4700}Je to pøítel z Akademie Rosenstolz.
{4700}{4756}Z Akademie Rosenstolz?
{4756}{4795}Opravdu? Wow!
{5138}{5242}Toto je poprvé, co si Elmunt pøivedl domù pøítele ze školy.
{5314}{5398}Je velmi nadanım kandidátem Strahl.
{5398}{5463}Je jeden z lidí, kteøí míøí vysoko.
{5509}{5554}Oh, opravdu?
{5576}{5654}Prosím vycházej s Elmuntem dobøe.
{5686}{5700}Budu.
{5731}{5748}Do toho, dej si.
{5763}{5780}Dìkuji.
{5817}{5865}Pravdìpodobnì jsi byl pøekvapenı, jak malı dùm to je.
{5865}{5956}Vùbec ne. Tento dùm má velmi srdeènou atmosféru.
{5956}{5994}Dìkuji.
{6118}{6218}Má rodina je šlechtická jen jménem. Nemáme ani ádnou vlastní pùdu,
{6234}{6287}a mùj otec je jen niší úøedník.
{6309}{6426}Právì fakt, e nìkdo jako já byl schopnı vstoupit |na Akademii Rosenstolz bylo slušné štìstí.
{6444}{6537}Kdy jsem byl pøijat, moje rodina za mì byla velmi šastná.
{6555}{6656}Myslím, e pøijetí nìkoho tak vynikajícího|jako jsi ty jde bez námitek.
{6671}{6795}Tìko jsem tomu mohl uvìøit, a na vrchol |toho všeho jsem se stal kandidátem Strahl.
{6822}{6897}Nechci si nechat tuto pøíleitost proklouznout.
{6964}{7023}Všichni z mé rodiny ve mì mají velká oèekávání.
{7040}{7138}Jestli budu mít úspìšnou kariéru, budu|schopnı otevøít cetu i mım mladším sourozencùm.
{7189}{7313}To proto udìlám cokoli, abych se pøipojil ke Strahl.
{7313}{7367}Protoe je to také mùj sen.
{7453}{7558}Niisan! Pøidáš se ke Strahl, a pak|se staneš nìkım opravdu dùleitım, správnì?
{7558}{7636}Budeš taky nìkım dùleitım, Came-oniichan?
{7689}{7709}Já...
{8179}{8250}Vypadá to, e kvìtiny jsou šastné, e jsi pøišel.
{8365}{8478}Elmunte. Proè jsi mì sem pøivedl?
{8478}{8581}Øekl jsem ti, e jsem s tebou chtìl víc mluvit.
{8595}{8609}Se mnou?
{8655}{8736}Nelhal jsem, kdy jsem øekl, e tì obdivuji.
{9407}{9487}Jestli chceš jít po jejich boku, jen s nimi zkus mluvit.
{9526}{9550}Øediteli!
{9606}{9652}Ne, nikdy bych nemohl...
{9667}{9688}Proè?
{9720}{9788}Jsou to vybraní kandidáti Strahl.
{9788}{9844}Jsou ode mì úplnì rozdílní.
{9863}{9891}Je to opravdu pravda?
{9969}{10039}Jsi také student Akademie Rosenstolz.
{10039}{10101}Jakı je mezi tebou a nimi rozdíl?
{10101}{10117}Ale...
{10134}{10251}Pravdou je, e jsou to vybraní synové rodin z vyšších tøíd.
{10265}{10388}Ale nezapamínají nezbytnì tvrdì pracovat,|aby splnili takovou tìkou odpovìdnost.
{10414}{10489}To proto se zdá, e záøí tak jasnì.
{10608}{10675}A ty máš záøi také.
{10859}{10891}To øeditel øekl...?
{10906}{11048}Øeditel Werner je ten, kdo poskytl pøíleitost,|abych se stal kandidátem Strahl,
{11048}{11147}ale byla to jeho slova, která mi dala nadìji...
{11164}{11218}a pohled na vás všechny.
{11285}{11417}Take vidìt tì takového, jakı jsi teï, bez |té záøe, mì také rmoutí.
{11454}{11486}Ale, já...
{11517}{11590}Vím, e jsi zranìnı.
{11624}{11645}Ale i tak...
{12078}{12137}Díky za návštìvu tvého domu, Elmunte.
{12151}{12206}Franz a Nina byli velmi šastní.
{12206}{12283}Kdyby ti to nevadilo, byl bych rád, kdybys nás pøijel zase navštívit.
{12283}{12298}Jistì...
{12553}{12565}Came!
{12639}{12686}Came, kde jsi byl?
{12686}{12741}Jsem doma, Niisama.
{12741}{12796}Omlouvám se, e jsem ti dìlal starosti.
{12796}{12826}Pokud jsi v poøádku.
{12845}{12880}Teï pojïme dovnitø.
{12895}{12910}Dobøe...
{13385}{13398}Vstupte.
{13608}{13663}Prosím ovìøte tohle.
{13736}{13840}Øediteli Wernere, není èas,|abyste se postaral o tu záleitost?
{13840}{13893}Jaká záleitost by to mìla bıt, Eilosi?
{13916}{14004}Odstoupení Cama Luneberga ze školy.
{14109}{14174}Nevrátí se.
{14174}{14320}Vìøím, e by to bylo nejlepší zaøídit pøedtím,|ne se Orpherus a ostatní zase ozvou.
{14444}{14605}A uvidí, e Camovo pøání o odstup je silné, pøijmou to.
{14615}{14679}Zamıšlím to zaøídit bìhem následujících pár dní.
{14692}{14790}Oh, opravdu? Omlouvám se, e jsem byl pøedèasnı.
{14790}{14845}Pak, kdybyste mì omluvil.
{14916}{15042}Sklíèenost na tváøi toho neomaleného |Orphera a jeho pøátel nìco uvidí, dobrá.
{15261}{15364}Opravdu to ulehèí tvému trápení?
{15380}{15444}I kdy jsou nevinní...
{15521}{15597}Ne, je to mé odpykání.
{15638}{15682}Není jiné cesty.
{15762}{15881}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{16034}{16053}Co se dìje, Naoji?
{16145}{16196}Tvùj oblièej je bledı.
{16196}{16223}Jsem v poøádku.
{16223}{16258}Lui tu není?
{16271}{16318}Ne, pøed chvílí odešel.
{16318}{16384}Oh? Jel koneènì ke Camovi?
{16384}{16479}Nevím. Odešel bez toho, aby nìco øekl...
{16479}{16539}Udìlal to, co poslední dobou docela èasto.
{16554}{16618}Dìje se ve vévodství Lichtenstein nìco?
{16671}{16736}Jsem si jistı, e se toho s jeho rodinou dost dìje, ale...
{16786}{16843}Co si myslí Lui?
{16860}{16873}Ede...
{16873}{16973}Vypadá to, jako by se ani o Cama neobával.
{16973}{17024}To je nemoné.
{17024}{17058}Naoji?
{17058}{17219}Lui se vdycky o Cama staral od té doby, co byli dìti.
{17219}{17316}My víme. Camus ho nakonec velice miluje.
{17316}{17341}Ano...
{17384}{17495}Jen to všechno dìlá tìší pochopit to, co si Lui myslí!
{17645}{17739}Tedy, Matko, prosím omluv mì.
{18546}{18635}Co ty na to, Came? Pojedeš se mnou na vılet?
{18669}{18727}Není špatné nìkdy od všeho odjdet pryè.
{18741}{18830}Ale jsi zamìstnanı prací, ne?
{18848}{18900}Oh, to se vyøeší samo.
{19024}{19143}No, jen o tom pøemıšlím. Máš všechen èas na svìtì.
{19162}{19179}Niisama...
{19340}{19403}Co chci udìlat?
{19570}{19665}Zdá se, e u skoro nemùeš slyšet hlasy kvìtin.
{19876}{19934}Lui! Jak jsi sem pøišel?
{19952}{20035}Chodil jsem sem èasto, kdy jsem byl dítì. Nebyl to vùbec problém.
{20035}{20093}Pøišel jsi mì vzít zpátky?
{20093}{20191}I kdybys teï jel zpátky, co bys mohl udìlat?
{20242}{20287}Musíš si pamatovat:
{20305}{20448}Proè jsi se nejdøíve rozhodl opustit tento pohodlnı ráj?
{20483}{20500}To je...
{20578}{20591}Poèkej!
{20970}{21047}Dùvod, proè jsem to tu chtìl opustit...
{21367}{21393}Vstoupit do školy?
{21405}{21442}Niisama, já...!
{21918}{21959}Niisan, u jedeš zpátky?
{21984}{22021}Hrej si s námi víc!
{22021}{22091}Omlouvám se. Budu zpátky bìhem dalšího volna.
{22091}{22121}Je to slib, dobøe?
{22138}{22210}Co to dìlám?
{22210}{22257}Zkoušet se zase spoléhat na ostatní lidi...
{22357}{22374}Came!
{22374}{22397}Niisama!
{22437}{22506}Came, zase se vykrást ze svého pokoje...
{22506}{22564}Niisama, promiò.
{22564}{22598}Pojï, pojïme domù.
{22607}{22673}Jestli zùstaneš doma, nebudeš se muset nièím znepokojovat.
{22898}{22912}Came?
{23000}{23052}Zase jsi nìco cítil, správnì?
{23052}{23132}Ne! Jestli pùjdeš, zase budeš zranìnı.
{23183}{23289}V prùbìhu let jsem sledoval, jak ti ta síla zpùsobuje utrpení.
{23303}{23333}Teï je to v poøádku.
{23333}{23460}Jen s námi ij doma, se klidem v mysli.|Nemusíš o nièem pøemıšlet.
{23797}{23837}Omlouvám se, Niisama.
{23860}{23875}Came!
{23924}{23971}Oniichan! To je nebezpeèné!
{23971}{24096}Je to v poøádku! Ujistím se, e Elmunt|jedno sní pøedtím, neı odjede zpátky na akademii!
{24190}{24239}Jen trochu víc! Je to v poøádku!
{24313}{24327}Zvládl jsem to!
{24327}{24363}Elmunte! Franz je...
{24421}{24434}Oniichan!
{24493}{24511}Franzi!
{24929}{24956}Elmunte...
{24956}{24994}Jste vy dva v poøádku?
{24994}{25045}Franzi, jsi zranìnı?
{25045}{25082}Ne. Dìkuju ti!
{25082}{25105}Oniichan!
{25115}{25150}Jsem v poøádku, Nino!
{25231}{25250}Came?
{25321}{25375}Chytil jsem ho svıma vlastníma rukama!
{25525}{25587}Díky za záchranu mého malého bratra.
{25617}{25680}Jen jsem se pohnul pøedtím, ne jsem to vìdìl...
{25779}{25798}Elmunte?
{25814}{25954}To nic. Jen jsem si všimnul, e tvoje záø,|kterou jsem obdivoval, se vrátila.
{26063}{26078}Came.
{26114}{26141}Niisama.
{26212}{26281}Nemyslel jsem si, e bys udìlal nìco tak nedbalého.
{26320}{26365}Omlouvám se, Niisama.
{26365}{26464}Ale cítil jsem, e jsem to musel udìlat...
{26524}{26561}Musíš si pamatovat.
{26580}{26735}Proè jsi se nejdøíve rozhodl opustit tento pohodlnı ráj?
{26756}{26838}To je pravda. Vdycky jsem se bál.
{26838}{26897}Chci vidìt více z vnìjšího svìta.
{26897}{26983}Chci vìdìt, co mùu udìlat s mou vlastní silou!
{27013}{27035}Came...
{27060}{27175}Niisama, miluji Akademii Rosenstolz.
{27211}{27273}A všechny lidi tam.
{27484}{27589}Pozvolna jsi se opravdu stal silnìjším, Came.
{28083}{28126}Vítej zpátky, Came.
{28126}{28174}Vìøili jsme, e se vrátíš.
{28174}{28239}Protoe tyto kvìtiny tak nádhernì rozkvetly.
{28396}{28419}Jsou tak pìkné...
{28547}{28611}Promiò, e jsem ti zpùsobil starosti, Lui.
{28731}{28798}Co to...? Jak bezcitnı mu.
{28798}{28826}Nemùe se trochu usmát?
{29216}{29277}Came, jsem rád, e jsi se vrátil.
{29292}{29323}Dìkuji vám mnohokrát!
{29955}{30029}Vidíš? Nakonec se vrátil, ne?
{30029}{30105}Vypadá to, e tvùj instinkt je jednou za èas správnı, Nicholasi.
{30105}{30155}To "jednou za èas" bylo zbyteèné.
{30155}{30201}Ale je to tak, jak to musí bıt.
{30201}{30287}Myslel jsem si, e jsem mìl o jednoho konkurenta ménì,|kterého jsem se také obával.
{30287}{30353}Udìlal jsi nìco, Elmunte?
{30370}{30403}Nic jsem neudìlal.
{30403}{30536}Jen jsem rád, e všechny kvìtiny na školní pùdì vypadají zase zdravì.
{30536}{30573}No, necháme to tak.
{30824}{30883}Jsem zpátky, všichni.
{31520}{31634}-Oslnivá obloha, západ slunce.-
{31634}{31759}-Hráli bychom si pod poulièními lampami.-
{31781}{31895}-V mrazivou noc, lustr visí z oblohy-
{31895}{32038}-pomalu se houpající.-
{32064}{32289}-Mùj hlas existuje jen, aby volal tvé jméno.-
{32289}{32549}-Pevnì svírám tvé malé, tøesoucí se prsty...-
{32549}{32685}-Èas pro nás dva zaèal ubíhat,-
{32685}{32809}-netøeba nièeho, ani slov.-
{32809}{32932}-Oh, pták zavøenı v kleci, tvá køídla naproti tvım òadrùm.-
{32932}{33061}-Tato obloha poslala toho ptáka tobì...-
{33458}{33475}Náhled Pøíští Epizody
{33528}{33617}Daleko od vlasti. Stopy. Rozhodnutí.
{33639}{33714}Je tu nìco, co chci ochránit!
{33773}{33798}SLUNEÈNÍ SVIT
