{1}{1}20.000
{264}{324}-Kdo to byl, e mì vedl za ruku?-
{324}{396}-Dìtské vzpomínky...-
{440}{581}-Vdycky kdy jsem se vzbudil, mé sny zmizely, pomíjivì jako bublina.-
{607}{764}-Vyléèím tvùj nekoneènı smutek.-
{764}{898}-My, kdo nemùeme ít osamìle.-
{941}{1022}-Co mùeme vidìt za naším osudem?-
{1022}{1111}-Pøíbìh o oslnivé slávì.-
{1111}{1250}-Sny v mé levé ruce, a drící se tì svou pravou,-
{1281}{1365}-chci záøit jako úsvit.-
{1365}{1448}-Pøíbìh o oslnivé slávì.-
{1448}{1588}-To vzácné svìtlo je v mé ruce...-
{2241}{2287}Opravdu za vše do teï dìkuji.
{2311}{2397}Nikdy nezapomenu dny, které jsem se všemi na akademii strávil.
{2442}{2470}Opravdu odešel, huh.
{2498}{2508}To je...?
{2524}{2553}Bylo to necháno zvenku pokoje.
{2553}{2613}Zdá se, e to nechal zvenku kadého pokoje,
{2625}{2648}vèetnì toho svého.
{2689}{2758}Blázen. Bralo mu èas se o nì tak láskyplnì starat,
{2775}{2842}ale jestli je nechal mì, okamitì uvadnou.
{3121}{3133}Came...
{3973}{3986}Jsem doma.
{4003}{4049}RÁJ
{4072}{4144}Take Camus pøedloil oznámení o odvolání ze školy a odešel?
{4144}{4192}Správnì, bohuel.
{4213}{4260}Proè jste to pøijal?
{4260}{4318}On sám to chtìl udìlat.
{4318}{4361}Jakı jsme mìli dùvod ho zastavovat?
{4361}{4399}Nebyl si sebou jistı.
{4399}{4493}Kdyby to s nìkım projednal, pak by tu jistì bylo jiné øešení.
{4493}{4573}Tato akademie není tak bezstarostná, e bychom| zdreli studenta, kterı není motivovanı.
{4597}{4650}Zvláštì v tomto pøípadì. Byl to kandidát Strahl.
{4650}{4704}Mùe brát za své jednání zodpovìdnost, ne?
{4704}{4715}To je...!
{4741}{4751}Orphe!
{4771}{4797}Promiò, Ede.
{4838}{4925}Byl to vynikající student. Pøeji si, abych ho mohl zadret.
{4938}{4991}Ale jeho vùle byla silná.
{5272}{5326}Je pravda, e se zdál bıt rozrušenı.
{5339}{5422}Nepovedlo se mi uvìdomit si, e bylo dost váné,|pøimìt ho, aby odešel z akademie.
{5422}{5464}Je to také má odpovìdnost.
{5491}{5506}Profesore Geralde...
{5542}{5621}V kadém pøípadì, nikdo z vás nemá právo zasahovat do této záleitosti.
{5636}{5647}Ale...!
{5668}{5727}Pøijal jsem jeho oznámení o odvolání.
{5727}{5766}Ale nemìl jsem v úmyslu ji okamitì zpracovat.
{5766}{5800}Øediteli Wernere!
{5943}{6024}Velice bych litoval dovolit mladému mui s oèekávanou|budoucností, aby odstoupil z akademie.
{6045}{6080}Dal jsem mu nìjakı èas.
{6103}{6124}Dìkuji vám mnohokrát!
{6160}{6171}To jsem rád.
{6191}{6215}Koupili jsme si nìjakı èas!
{6227}{6277}Pojïme pøivést Cama zpìt co nejdøíve mùeme!
{6277}{6290}Správnì.
{6301}{6365}Zajímá mì, jestli je to pro nìj to nejlepší.
{6365}{6384}Profesore Geralde?
{6397}{6440}Camus byl velmi rozrušenı.
{6440}{6522}Jestlie byl vısledek jeho bolesti rozhodnutí opustit akademii,
{6522}{6579}pøivést ho zpìt moná není v jeho nejlepším zájmu.
{6579}{6599}To nemùe bıt!
{6599}{6677}Myslím, opravdu tuto akademii miluje!
{6677}{6717}Jsem si jistı, e tu chce zùstat!
{6717}{6802}Ano, pravdìpodobnì... Pravdìpodobnì je to pøesnì tak, |protoe miluje tuto akademii a to je tak bolestivé.
{6819}{6886}Rozumím jeho pocitùm velmi dobøe.
{6886}{6964}My nechceme ztratit pøítele a bıt zanecháni smutku.
{6975}{7015}Rádi bychom udìlali cokoli mùeme.
{7062}{7073}Ano.
{7106}{7136}Hej, Naoji! Tady!
{7149}{7160}Kde je Lui?
{7170}{7213}Zdá se, e odjel...
{7213}{7241}Do Camova domu?
{7241}{7299}Ne, slyšel jsem, e jel domù.
{7299}{7363}Domù? Proè teï, ze všech dob?
{7376}{7448}Camus je jeho pøíbuznı a dìtskı pøítel, ne?
{7460}{7483}Ano...
{7503}{7569}V kadém pøípadì, pokusím se jet do Camova domu.
{7878}{7996}Aèkoli jsou moná kandidáti Strahl, takovı|vzpurnı postoj by nemìl bıt tolerován.
{7996}{8022}Jsou stále mladí.
{8022}{8081}Je vıhodou mládí neznat strach.
{8081}{8172}Tento svìt je plnı vìcí, které se nepøizpùsobují našim oèekáváním.
{8172}{8239}Nevyhnutelnì pøijde den, kdy tomu porozumí.
{8249}{8260}Toto, také...
{8310}{8368}A pøijde èas, oficiálnì to zpracuji.
{8368}{8400}Nejsou s tím ádné problémy, správnì?
{8436}{8451}Vùbec ádné.
{8556}{8592}Byly jste zdravé?
{8602}{8661}Rozvetly jste tak krásnì. To je úasné.
{8715}{8732}Vypadáš šastnì.
{8732}{8755}Bratøe!
{8815}{8905}Kdy se o nì staráš, i barva kvìtin vypadá jinak.
{8952}{8967}Omlouvám se.
{8982}{9055}Øekl jsem tolikrát, e budu dìlat, co je v mıch silách,|a ještì jsem se vrátil tak náhle...
{9055}{9082}To nevadí.
{9082}{9182}Otec, zbytek rodiny, a všichni v domì|jsou pøešastní, e jsi se vrátil.
{9182}{9202}Ano...
{9225}{9277}Jsem také šastnı, e jsi tady.
{9334}{9344}Dále.
{9399}{9415}Tudy, pánové.
{9575}{9612}Vítejte. Poctili jste mì svou návštìvou.
{9612}{9670}Prosím omluvte nás za tak náhlı pøíchod.
{9701}{9721}Came...
{9744}{9779}Jsem Camùv starší bratr, Leohart.
{9779}{9825}Budu poslouchat, cokoli si pøejete øíct.
{9840}{9911}Camus není ve stavu, aby mohl pøijímat hosty.
{10045}{10073}Je nemocnı?
{10086}{10132}Na povrchu se zdá bıt ve velmi dobré náladì.
{10153}{10230}Ale... Hlídal jsem ho ode dne, co se narodil.
{10242}{10291}Mùu øíct okamitì, kdy je zranìnı.
{10306}{10361}Také mu chceme pomoci.
{10374}{10392}Pomoct mu?
{10414}{10520}Z èeho je rozrušenı, co by mìl dìlat...|Chceme s ním o tìchto vìcech pøemıšlet!
{10543}{10570}Je to náš pøítel.
{10589}{10634}Slyšel jsem toho o vás od Cama hodnì.
{10648}{10708}Mluvil o akademii s velkım potìšením.
{10757}{10854}Ale teï nemluví o nièem. Tak zle byl zranìnı.
{10854}{10909}Zamıšlíte ho vzít zpátky, aby mu to zpùsobilo trápení?
{10945}{11108}Kvùli jeho unikátní schopnosti se Camus vdycky|bál nebo s ním bylo od ostatních nezvykle zacházeno.
{11151}{11204}Jak hluboce ho to zranilo...
{11217}{11270}A ještì nikdy nebyl k nikomu zlomyslnı.
{11422}{11495}Camus má opravdu jemného ducha.
{11512}{11618}Nestaèila by ádná slova, aby vyjádøila,| jak nás jeho jemnost zachránila.
{11632}{11678}Pak prosím nechte toho chlapce bıt!
{11699}{11711}Ale...!
{11934}{11972}Kvùli nìmu.
{11972}{12020}Tady mu nic neublíí.
{12035}{12065}Prosím, jen ho nechte bıt.
{12642}{12693}Stalo se doma nìco?
{12709}{12783}Zdá se, e je tam jistá skupina lidí dávající|zbyteèné nápady do hlavy mé matky.
{12796}{12847}Zøejmì mìli docela èas se s tím vypoøádat.
{12847}{12888}Tvoje matka je...
{12888}{12936}Mladší sestra Jeho Velièenstva.
{12936}{13000}Jinımi slovy, královská princezna provdána do rodiny Lichtenstein.
{13013}{13121}Ta ena se nikdy nezajímala na prvním místì o politiku...
{13135}{13202}Bylo to o královì mladším bratrovi, Halbertovi...?
{13214}{13274}Bez ohledu na to, jakı je to |mu, je to stále její starší bratr.
{13274}{13409}Zabralo nám to naše nejvìtší úsilí odradit ji |od ádání krále o schovívanı trest.
{13423}{13577}Moná je její pokrevní pøíbuznı, ale jestli k nìmu budeme pøíliš |schovívaví, jen nás to vystaví nebezpeèí.
{13768}{13836}Èaj, kterı uvaøíš, Naoji, mì vdycky uklidní.
{13876}{13943}Zamıšlíš nechat Cama bıt?
{13977}{14036}Potøebuje tvoji pomoc!
{14096}{14135}Opravdu si to myslíš?
{14166}{14232}Ještì tomu chlapci moc dobøe nerozumíš.
{14389}{14489}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{15189}{15225}Myslel jsem si, e bys nepøišel.
{15237}{15305}Ty jsi ten, kdo øekl, e má nìco dùleitého o èem chce mluvit.
{15305}{15394}I tak, nejsi mùj podøízenı. Jsem rád, e jsi pøišel.
{15394}{15486}Jen jsem se chtìl vyvarovat toho, aby| ostatní prokoukli mé spojení s tebou.
{15528}{15566}Take? Jakou záleitost se mnou máš?
{15612}{15640}Tady jsou vısledky vyšetøování.
{15714}{15729}Opravdu jsou.
{15729}{15748}Také...
{15772}{15843}Zdá se, e Camus Luneburg odstupuje ze školy.
{15864}{15969}Oh? Menší práce pro mì.
{16008}{16020}Beruze!
{16126}{16165}Je pøíliš pozdì zmìnit názor?
{16231}{16275}Znáš odpovìï na tuto otázku velmi dobøe.
{16473}{16548}Slyšel jsi o Camovi? Øíkali, e pøedloil oznámení o odvolání!
{16838}{16914}Jestli má jeden z vás co øíct, øekni to jasnì.
{17005}{17047}Pak mi dovol se tì upøímnì zeptat.
{17047}{17135}Domnívám se správnì, e se èíslo konkurentù sníilo?
{17180}{17220}Svobodnì se domnívej cokoli chceš.
{17220}{17339}Ztráta i jen jednoho konkurenta| dìlá cestu spojení se se Strahl snadnìjší.
{17360}{17384}Nelíbí se mi to.
{17412}{17510}Radìji bych znièil všechny své konkurenty| vlastní silou a pøipojil se ke Strahl.
{17510}{17568}Poèítal jsem s tím, e bys to øekl, Nicholasi.
{17589}{17684}Také, nemyslím si, e je ten kluk tak slabı, jak vypadá.
{18016}{18128}Je to, co se pokoušíme udìlat, zahnat Cama do úzkıch?
{18128}{18170}Je to závanı problém,
{18170}{18225}zvláštì, kdy nemùeme mluvit s Camem samotnım.
{18249}{18262}Je to jen...
{18280}{18292}Jen?
{18367}{18453}Chápu, e zranìním zabírá èas se zahojit.
{18483}{18494}Ede...
{18550}{18609}Ale právì teï nemáme èas.
{18609}{18660}Touto rychlostí opravdu odstoupí...
{18660}{18729}Camus miluje tuto akademii z hlouby jeho srdce.
{18767}{18778}To proto...
{18816}{18832}Pak myslím, e je rozhodnuto!
{18882}{18908}Zaènìme ihned...
{18908}{18931}To je opravdu úasné.
{18944}{18962}Profesore Geralde!
{18983}{19077}Dívat se na vás mi pøipomíná mì, kdy jsem byl ještì student.
{19096}{19216}Tenkrát jsme se také báli, zlobili se, a smáli se...|Kadı den byla zábava.
{19216}{19326}Ano, s nejlepšími pøáteli, kterım jsme nejvíce vìøili, pøesnì jako vy.
{19364}{19449}Jsem si jistı, e vaše pocity ke Camovi sahají.
{19449}{19587}Take... Domnívám se, e doufání a |èekání je také vyjádøení pøátelství.
{19747}{19750}Au!
{19761}{19776}Jsi v poøádku?
{19798}{19811}Ano...
{19872}{19917}Starat se o kvìtiny je spousta práce!
{19917}{19981}Camus to dìlal kadı den, ne?
{19981}{20025}Ano, máš pravdu. Tolik ho obdivuju!
{20048}{20094}Vypadá to, e nejsou moc zdravé.
{20094}{20166}Moná je to jen má pøedstavivost, ale |barva kvìtin se zdá bıt jednotvárnìjší.
{20184}{20255}Byly tak nádherné, kdy tu byl Camus.
{20273}{20330}I školní pùda se zdá bıt vybledlá.
{20330}{20436}Jen pomyšlení, e jeho úsmìv ji není |na této akademii je dost osamìlé...
{20820}{20908}Prosím vykonej dùkladné vyšetøování tìchto osob|a nava s nimi kontakt.
{20952}{20966}To je...!
{21000}{21129}Jak jsi dostal do rukou takové osobní informace?|A v tak krátkém èase?
{21146}{21237}Dìti chtìjí mluvit o svıch starostech se spolehlivım dospìlım, ano?
{21255}{21313}Zvláštì s tím, o kterıch vìdí, e ji mùou dùvìøovat.
{21313}{21389}Nemùeš myslet... Akademii Rosenstolz?
{21389}{21487}Místo profesora se ukázalo bıt docela |vhodné pro shromaïování informací.
{21502}{21567}Jinımi slovy, stále máš na akademii |nìkoho, kdo s tebou spolupracuje.
{21567}{21660}Znepokojuje tì fakt, e je mi ta osoba blízká?
{21679}{21740}Mì? Pøestaò vtipkovat.
{21740}{21800}Jsem teï na stranì jejich protivníka...
{21820}{21874}Ne, nikdy jsem nezaèal bıt jejich spojencem.
{21890}{21923}Nemám ádné povinnosti si o nì dìlat starosti.
{21948}{21998}Dávám své nejlepší úsilí mé vlasti.
{22514}{22527}Já...
{22734}{22747}Já...
{22811}{22849}Proè jsem sám?
{22871}{22923}Všichni... Kde jsou všichni?
{23641}{23713}Omlouvám se. Není to vùbec vaše chyba.
{23737}{23767}Je to jen, e já...
{24077}{24109}Ne! Já...!
{24203}{24256}Co to dìláš? To je nebezpeèné.
{24256}{24308}Elmunte... Proè jsi tady?
{24364}{24410}Pøišel jsi, abys mì vzal zpátky?
{24423}{24501}Ne, nepøijel. Jen jsem s tebou chtìl mluvit.
{24501}{24530}Mluvit...?
{24530}{24619}Pøijel jsem sem celou cestu, ale nevìdìl jsem,|jak bych se s tebou setkal.
{24644}{24673}Jsem rád, e jsem tì tu potkal.
{24716}{24766}Neznám tì moc dobøe.
{24805}{24853}Taky mì moc dobøe neznáš, správnì?
{24868}{24884}No, já...
{24925}{24988}Take bych s tebou rád mluvil.
{25646}{25659}Came?
{26291}{26385}-Oslnivá obloha, západ slunce.-
{26385}{26489}-Hráli bychom si pod poulièními lampami.-
{26506}{26599}-V mrazivou noc, lustr visí z oblohy-
{26599}{26722}-pomalu se houpající.-
{26743}{26930}-Mùj hlas existuje jen, aby volal tvé jméno.-
{26930}{27142}-Pevnì svírám tvé malé, tøesoucí se prsty...-
{27142}{27257}-Èas pro nás dva zaèal ubíhat,-
{27257}{27362}-netøeba nièeho, ani slov.-
{27362}{27463}-Oh, pták zavøenı v kleci, tvá køídla naproti tvım òadrùm.-
{27463}{27576}-Tato obloha poslala toho ptáka tobì...-
{27905}{27921}Náhled Pøíští Epizody
{27960}{28036}Sourozenci. Ideály. Pøání, které chce jeden udìlit.
{28061}{28125}Kam patøíš?
{28165}{28185}ZAÈÁTEÈNÍ BOD
