{1}{1}23.976
{311}{383}-Kdo to byl, e mì vedl za ruku?-
{383}{476}-Dìtské vzpomínky...-
{530}{688}-Vdycky kdy jsem se vzbudil, mé sny zmizely, pomíjivì jako bublina.-
{727}{916}-Vyléèím tvùj nekoneènı smutek.-
{916}{1068}-My, kdo nemùeme ít osamìle.-
{1127}{1221}-Co mùeme vidìt za naším osudem?-
{1327}{1492}-Sny v mé levé ruce, a drící se tì svou pravou,-
{1538}{1634}-chci záøit jako úsvit.-
{1634}{1734}-Pøíbìh o oslnivé slávì.-
{1734}{1914}-To vzácné svìtlo je v mé ruce...-
{4734}{4780}ÚTÌK
{4893}{4929}Copak je, Ede?
{4949}{5063}Oh, jen mì zajímalo, kdo hrál na ty píšalové varhany.
{5063}{5145}Ano. Byl to krásnı témbr.|/témbr = zabarvení tónu, barva zvuku/
{5145}{5261}Neèekal jsem, e je tu na akademii|nìkdo další kromì tebe, kdo hraje tak dobøe.
{5261}{5327}Byl to krásnı zvuk,
{5327}{5432}ale mìl jsem pocit, e mì nìco škrtilo na hrudi.
{5432}{5532}Hudební Nástroje jsou upøímnım odrazem|srdce hudebníka, kterı na nì hraje.
{5558}{5574}Ede...
{5604}{5676}Take? Našel jsi knihu, kterou jsi hledal?
{5686}{5699}Jo.
{5777}{5803}Co se dìje, Orphe?
{5803}{5911}Teï kdy jsi se o tom zmínil, ten mu jednou øekl, e je romanopisec.
{5911}{5950}Mluvíš o Isaacovi?
{5972}{6052}Ano. Zachránil mi ivot.
{6052}{6129}Zmizel ani by mi dal èas mu podìkovat.
{6154}{6206}A od té doby jsme ho nevidìli.
{6249}{6323}Zajímá mì, kdo to opravdu byl...
{6481}{6500}Podívej se na to.
{6574}{6703}Jestli se to stane oficiálním, budeš oloupen o svùj titul.
{6703}{6752}N-Ne, prosím!
{6767}{6825}J-Jestli jsou peníze to, co chceš, dám ti jakékoli mnoství!
{6846}{6887}Ne, díky.
{6903}{6985}Všechno co musíš udìlat, je mlèet a následovat mé pøíkazy.
{7008}{7030}To je...
{7359}{7399}Díky za tvou tvrdou práci.
{7399}{7474}Vidím, e jsi naprostı vyjednavaè.
{7493}{7554}Jsi v tìchto vìcech lepší ne já.
{7593}{7670}Pøesnì jako kdy si's získal pøízeò králova mladšího bratra.
{7684}{7773}Kvùli tomu incidentu u nejsem anonymní.
{7828}{7911}Kromì toho, je to pùvodní ádost z tvé zemì.
{7925}{7983}Jednoduše ti pomáhám.
{8026}{8097}Co chceš opravdu udìlat?
{8097}{8215}Pro teï, budu pracovat ve prospìch tvé zemì.
{8215}{8301}Dokud se to shoduje s tím, co chci dìlat,
{8301}{8339}nezradím tì.
{8391}{8488}Nicménì... jsi ubohı mu.
{8502}{8619}Pøipoutanı svou zemí, pøinucenı |dìlat vìci proti své vùli....
{9335}{9416}Co to sakra dìlám...
{9648}{9746}Kdybych jen opustil armádu, jak jsi øekla...
{10053}{10117}No, kdybych to mohl udìlat,|nemìl bych teï ádné problémy, ne?
{10189}{10294}Jestli je to moné, chci se vyvarovat setkání s nimi...
{10457}{10496}Teï vypadají o hodnì zdravìji.
{10496}{10592}Na chvilku kvìtiny ztatily svou vitalitu.
{10592}{10714}Jsem si jistı, e chápaly, e jsi se znovu rozveselil.
{10714}{10854}Myslíš? Cítím jako by byly jediné, kdo mì rozveselil.
{10918}{10975}Jak se od té doby vedlo tvojí matce?
{10975}{11054}Její smutek se dost povznesl.
{11054}{11145}Øíkala mi, abych vás zase nìkdy všechny pøivedl zpátky domù.
{11145}{11181}Chápu.
{11181}{11309}To rád slyším. Smutnı oblièej obasama nesluší.
{11615}{11652}Nìco takového...!
{11684}{11799}Bojím se, e je to nepopiratelná pravda, Vaše Velièenstvo.
{11819}{11918}Podezøelé osoby, které byly zatèeny pøed nìkolika dny|mìly ve svém majetku skrytı zvací dopis.
{11918}{12049}Ten dopis byl nepopiratelnì písmem|Vévody Liechtensteina, a nesl jeho peèe.
{12083}{12128}Také si to pamatuji.
{12157}{12173}Ale...!
{12201}{12285}Byl zde také pøed pár dny incident |zahrnující Jeho velièenstvo Halberta.
{12285}{12431}Teï je èas pro rozhodující rozhodnutí Jeho Velièenstva.|Záleitost by mìla bıt rychle rozhodnuta.
{12761}{12861}Oh, ne! Nemùu uvìøit tomu, e jsem byla tak |uchvácena nakupováním, e jsem ztratila pojem o èase!
{12861}{12929}Nestihnu to vèas na veèeøi!
{13414}{13437}To nemùe bıt...!
{13495}{13592}Zdá se to jako by poslední dobou vyèerpali vımluvy.
{13609}{13703}Šlechtici z vyšší tøídy nakonec proti sobì navzájem nezaèínají boje.
{13703}{13802}Únavné. Jestli neudìlají nìco víc, budu se nudit.
{13802}{13860}To je tvùj zlozvyk, Danieli.
{13860}{13943}Mìl by se's pøestat bavit tím, co dìlají ostatní,
{13943}{13971}nebo tì lidé nebudou správnì chápat.
{13971}{14009}To je mi jedno.
{14009}{14116}Dokud jsou tu na svìtì silní protivníci, nebudu se nudit.
{14167}{14185}Came?
{14263}{14319}Co se dìje? Jsi v poøádku?
{14388}{14408}Came!
{14408}{14441}Nìco...
{14523}{14549}Nìco pøichází!
{14570}{14685}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{14730}{14760}Co tím myslíš?!
{14776}{14841}Podle plánu, to bylo oèekáváno pozdìji...!
{14841}{14943}Pøíhodná chvíle pøišla døíve, ne jsme oèekávali.
{14968}{15025}Není to nic, èím bys mìl bıt šokovanı.
{15025}{15112}I tak, ani jsi to se mnou neprojednal!
{15128}{15227}Všechna moc je v mıch rukou.
{15242}{15334}Musíš se jen pohybovat, jak jsi øekl.
{15635}{15650}Pane!
{15714}{15755}Co je to?!
{15939}{15999}Musím jít za Luim...
{16062}{16082}Jsme obklopeni?
{16190}{16257}Co tady dìlá královská armáda?
{16990}{17033}Co to pro všechno na svìtì...?
{17083}{17233}Ludwigu Herzog von Mohn nahe Liechtenstein,
{17233}{17357}jsi zatèen za podezøení z vlastizrady proti království Kuchen!
{17399}{17428}To nemùe bıt...!
{17524}{17548}Pøíliš jsem se zpozdil?
{17569}{17601}Profesore Geralde!
{17601}{17644}To není pravda, e?
{17659}{17716}Lui by nikdy nespáchal vlastizradu!
{17763}{17797}Co to dìláte?
{17838}{17896}Vrate se do svıch lonic!
{17896}{17924}Ale...!
{17924}{17963}Dost s tím. Bìte zpátky!
{18008}{18081}Ludwig je stále uvnitø.
{18094}{18128}Øediteli Wernere!
{18128}{18181}Ano, zdá se, e je.
{18207}{18254}Nìvìøím tomuto skandálu!
{18254}{18328}V historii Akademie Rosenstolz nikdy nic takového nebylo!
{18345}{18405}A ze všech vìcí, vlastizrada...!
{18443}{18499}To nemùe bıt... Lui by nikdy...
{18499}{18523}To je le!
{18523}{18635}Vévodství Liechtenstein je naplnìno vírou|v královskou rodinu; jsou jedním z pilíøù této zemì!
{18664}{18708}Èlenové té rodiny by nikdy nespáchali vlastizradu!
{18733}{18804}Hmmm. Zajímavı zvrat událostí.
{18816}{18879}Lui? To je nemoné.
{18879}{19014}Kdyby mìl v úmyslu mít jakoukoli politickou moc, |nikdy by neudìlal takovou pošetilost jako je vlastizrada.
{19181}{19197}Lui!
{19197}{19235}Uklidnìte se trochu.
{19259}{19346}Vy nejste ti podezøelí.
{19346}{19366}Lui!
{19386}{19441}Je teï èas na øíkání nìèeho takového?
{19441}{19488}Co tím myslíš, Ludwigu?
{19488}{19530}Co se dìje?
{19559}{19601}Pøesnì to, co jste slyšeli.
{19619}{19673}Hej, to nic nevysvìtluje!
{19688}{19742}Co tvoji rodièe?
{19742}{19836}Samozøejmì, pro nì byla také pravdìpodobnì udìlána opatøení.
{19896}{19984}Ale doma nikdo není.
{20042}{20155}Mùj otec vzal mou matku na vılet, aby ji rozveselil.
{20182}{20236}Ani já neznám jejich cíl cesty.
{20313}{20383}Lui, vìdìl si, co by se mohlo stát?
{20383}{20489}Je to pro mì necharakteristické to øíct, mìl jsem špatnı pocit.
{20506}{20613}Aèkoli jsem to neèekal tak brzy...
{20613}{20696}A? Co budeš dìlat?
{20898}{20916}Utíkat.
{20980}{21005}To je smìšné!
{21019}{21062}Èeho si myslíš, e dosáhneš útìkem?
{21062}{21191}Jestli jsi nevinnı, mìl bys se's majestátnì| ospravedlnit pøed Jeho Velièenstvem!
{21191}{21351}Fakt, e z toho dìlají takovou zvelièenou šarádu|ukazuje, e mají znaènı dùkaz.
{21351}{21502}Dùkaz dost silnı, e nemùe bıt |pøehlíenı samotnou laskavostí Jeho Velièenstva.
{21502}{21523}To nemùe bıt...
{21572}{21666}Ne! Lui, co mùeš udìlat sám?
{21723}{21862}Jestli teï budu chycen, budu uvìznìn za falešné obvinìní|bez povolení monosti ospravedlnìní.
{21892}{21986}Nemám ádnı úmysl hrát nepøíteli takto do karet.
{22062}{22089}Ludwigu...
{22130}{22172}Nebojte se o mì.
{22186}{22308}Nebo mì chytíte a pøedvedete mì Jeho Velièenstvu?
{22397}{22504}Vaše pozice to èiní vaší skuteènou odpovìdností.
{22568}{22612}Poèkej vteøinku!
{22612}{22729}Musíme zaostøit na únik odsud, ne sem ti chlapi pøijdou!
{22729}{22807}Ale obklopili nás!
{22807}{22860}Jak se mùete dostat ven?
{22874}{22986}Geralde, prosím poruè tìmto dívkám vrátit se do svıch lonic.
{23003}{23054}Øekni jim, e není èeho se obávat.
{23054}{23071}Ano, pane.
{23071}{23104}Co udìláte, Øediteli?
{23104}{23206}Pokusím se pøesvìdèit Ludwiga, aby se vzdal.
{23229}{23295}Není tøeba, abyste dìlal takovou vìc!
{23343}{23401}Prosím zùstaòte vzadu. Budeme...
{23426}{23529}Ne. Ten podezøelı je studentem mé akademie.
{23548}{23664}Jako Øeditel si nepøeji dìlat nìco, |co by ublíilo jednomu z mıch vzácnıch studentù.
{23680}{23735}Prosím, dovolte mi s ním mluvit.
{24124}{24181}Kde je Ludwig?
{24242}{24381}Vtísnil se do svého pokoje a nevychází ven.
{24397}{24410}Aha.
{24444}{24601}Pravidla státu, e je to pod samosprávou studentù|a neznámí lidé nemají povoleno vstoupit.
{24601}{24723}Vzhledem k situaci si jsem jistı, e nikdo neprotestuje.
{24835}{24882}Jeho pokoj je tudy.
{25304}{25372}Pod lonicemi studentù je takovı podzemní tunel?
{25401}{25465}Je to tajná cesta známá jen hrstce studentù.
{25498}{25591}Zdá se, e tato budova bıvala sídlem šlechtické rodiny.
{25591}{25754}Tenkrát to bylo vybudováno jako nouzovı prùchod;|teï, ho studenti pouívají, aby se vykradli ze svıch lonic.
{25782}{25831}Jsi v poøádku, Came?
{25831}{25856}Jo...
{25999}{26059}Není pro vás ádnı dùvod mì doprovázet.
{26059}{26095}Vrate se.
{26110}{26133}Ale...
{26158}{26301}A do té doby, ne uvidíme, e jsi v bezpeèí |na bezpeèném místì, pùjdeme s tebou.
{26317}{26379}Bez ohledu na to, jak moc protestuješ.
{26416}{26448}Proè?
{26448}{26520}Nemá to s tebou nic spoleèného.
{26520}{26667}Ve skuteènosti, jestli budete chyceni se mnou, budete|obalováni jako moji spolupachatelé z toho samého trestného èinu.
{26683}{26755}Protoe vìøím, e jsi nevinnı.
{27204}{27269}Zdá se, e sem nepøišli.
{27328}{27345}Nìkdo tam je!
{27422}{27471}Slote své meèe. Nejsme vaši pronásledovatelé.
{27493}{27518}Nicholasi!
{27518}{27541}Elmunte!
{27541}{27580}Proè jste...?
{27580}{27691}Nemyslete si, e jste jediní, kdo zná ten prùchod.
{27691}{27782}Šli jsme napøed a potvrdili, e to nebyla léèka.
{27809}{27832}Elmunte!
{27860}{27930}Víc pomocníku je lepší, správnì?
{28282}{28297}Jdìte!
{29129}{29184}Myslím, e jsme všichni v poøádku, kdy jsme šli tak daleko.
{29203}{29249}Nevypadá to, e bychom bylo pronásledováni.
{29311}{29326}Orphe!
{29470}{29519}To nejsou vojáci z Kuchenské armády!
{29534}{29656}Nejspíše jsou to nìèí pìšáci, kteøí na mì napíèili past.
{29656}{29740}Pøedvídali naše pohyby takhle dobøe?
{29996}{30059}Kdo jste, lidi?!
{30117}{30129}Orphe!
{30405}{30452}Díky, Ede. Zachránil jsi mì.
{30479}{30494}Ede?
{30494}{30552}Err, ne, to nic...
{30618}{30649}Musíme také vyrazit.
{30701}{30723}Pojïme, Ede!
{30723}{30750}Správnì...
{31521}{31633}-Oslnivá obloha, západ slunce.-
{31633}{31755}-Hráli bychom si pod poulièními lampami.-
{31777}{31890}-V mrazivou noc, lustr visí z oblohy-
{31890}{32040}-pomalu se houpající.-
{32065}{32287}-Mùj hlas existuje jen, aby volal tvé jméno.-
{32287}{32540}-Pevnì svírám tvé malé, tøesoucí se prsty...-
{32540}{32685}-Èas pro nás dva zaèal ubíhat,-
{32685}{32808}-netøeba nièeho, ani slov.-
{32808}{32928}-Oh, pták zavøenı v kleci, tvá køídla naproti tvım òadrùm.-
{32928}{33061}-Tato obloha poslala toho ptáka tobì...-
{33460}{33476}Náhled Pøíští Epizody
{33528}{33610}Mìsto v noci. Nejistota. Rozlouèení.
{33635}{33674}Vìøil jsem ti...
{33769}{33795}SPLETITOST
