{1}{1}23.976
{312}{384}-Kdo to byl, e mì vedl za ruku?-
{384}{470}-Dìtské vzpomínky...-
{522}{697}-Vdycky kdy jsem se vzbudil, mé sny zmizely, pomíjivì jako bublina.-
{726}{915}-Vyléèím tvùj nekoneènı smutek.-
{915}{1075}-My, kdo nemùeme ít osamìle.-
{1126}{1222}-Co mùeme vidìt za naším osudem?-
{1222}{1327}-Pøíbìh o oslnivé slávì-
{1327}{1498}-Sny v mé levé ruce, a drící se tì svou pravou,-
{1538}{1635}-chci záøit jako úsvit.-
{1635}{1738}-Pøíbìh o oslnivé slávì.-
{1738}{1912}-To vzácné svìtlo je v mé ruce...-
{2622}{2686}Je teï na všechno... pøíliš pozdì?
{2752}{2839}Jsem neschopnı tì zachránit?
{3020}{3053}STÍN
{3148}{3177}Ty...!
{3219}{3336}Máš v úmyslu mi øíct, e kvùli své hrdosti|bys zahodil svùj ivot?
{3374}{3453}Je to opravdu nìco pro tebe to øíct, Orphere?
{3469}{3611}Tvá silná stránka je zpùsob, jakım si ceníš své hrdosti.
{3640}{3712}Proè jsi tím tak rozèilenı?
{3752}{3841}Nemá to s tebou nic spoleèného. Nech to bıt.
{3879}{3935}Co si pøesnì myslíš, e je tvùj ivot?!
{3935}{4000}Jakmile ho ztratíš, u ho nikdy nemùeš získat zpìt!
{4104}{4226}Uvaoval jsi nìkdy o tom, jak by se všichni cítili?
{4466}{4598}Je pravda, e mé staré já moná|myslelo stejnım zpùsobem jako to ty dìláš teï.
{4616}{4724}Ale teï vìøím, e bez ohledu na to,|jak kruté a bolestivé to mùe bıt,
{4724}{4788}je to jen bìhem ití, kdy mùeme otevøít cestu!
{4809}{4887}A vím, e jsou zde moji pøátelé.
{5419}{5541}Nemùu rozumnìt takové naivitì.
{5564}{5580}Lui!
{5767}{5842}Naoji. Také u sem znovu nechoï.
{5879}{5978}Nemìl bys dìlat nic, co by tì udìlalo|neschopnım vidìt svou rodinu v Japonsku.
{6453}{6498}Lui øekl nìco takového...?
{6527}{6647}Jsem si jistı, e jedná tímto zpùsobem|protoe má nìjakı plán.
{6665}{6745}Není typ èlovìka, kterı to takto vzdává.
{6763}{6794}Já to vím.
{6817}{6831}Orphe?
{6865}{6998}Lui pravdìpodobnì poèítal s tím, e jestli budeme pokraèovat|v zapojování se, také se zamotáme do té špíny,
{6998}{7058}a tak se nás pokouší od nìj distancovat.
{7058}{7145}Ano, souhlasím.
{7145}{7299}A já si myslím, e to mùe bıt kvùli jeho|rodinì která právì teï nemùe jednat.
{7377}{7547}Musí si dìlat starosti, protoe jestli udìlá neopatrnı krok,|pøinese nebezpeèí pro svou rodinu, která se hledá.
{7782}{7847}Lui je velmi milı.
{7899}{7954}Jsem vdìènı za jeho pocity.
{7954}{8069}Ale myslíte, e ho teï mùeme nechat bıt?
{8069}{8138}Já nemùu nechat vìci stát tak, jak jsou!
{8138}{8184}Rozzlobí to Luiho, ale...
{8184}{8281}Já, také! Chci, aby se sem Lui vrátil!
{8377}{8495}V kadém pøípadì, pokusím se znovu |dostat audienci u Jeho Velièenstva...
{8495}{8526}Moná je to tak, jak Lui øekl.
{8542}{8591}Moná bychom od toho mìli ustoupit.
{8616}{8631}Ede?
{8724}{8765}Co mùeme udìlat?
{8791}{8907}Mùeme bıt "kandidáti Strahl",|ale nakonec jsme jen studenti.
{8925}{8991}Stále postrádáme moc a schopnost|nést tíhu politiky této zemì.
{9022}{9110}To je situace, jsem si jistı, e úøady se o to postarají.
{9138}{9152}Ede...
{9190}{9246}Ede, co to øíkáš?
{9273}{9330}Jen poslouchejte, jestli se do toho dostanete jakkoli hloubìji...!
{9410}{9428}Ede?
{9563}{9639}Hej, mohl jsem vás všechny slyšet zvenku.
{9656}{9742}Teï je pro vás nejhorší doba bojovat mezi sebou.
{9767}{9812}Ne, to nic.
{9895}{9936}Came, co se dìje?
{9936}{10021}Oh, nic. Jsem v poøádku.
{10597}{10669}Øíkají, e konì mohou vnímat pocity svıch jezdcù.
{10712}{10744}Profesore Geralde!
{10914}{10964}Proè jste mì nechal jít?
{10985}{11042}Myslíš tvùj nedovolenı vılet?
{11287}{11342}Tak proè jste tady, Profesore?
{11370}{11480}Jestli ti to øeknu, dáš mi také upøímnou odpovìï?
{11596}{11689}Kdyby byl nalezen student Akademie Rosenstolz|na takovém místì, byl by to pøísnı trest.
{11717}{11912}I s tímto vìdomím jsi sem pøišel. |Musí to bıt nìco velmi dùleitého.
{12068}{12144}Bylo tu nìco, co jsem si pro sebe musel potvrdit.
{12253}{12318}Ale pøeji si, abych nepotrvrdil...
{12334}{12435}Ta pravda tì teï trápí, e?
{12535}{12641}Má to nìco spoleèného s Orpherem?
{12787}{12922}Je jedinı, pro koho bys udìlal sám nìco tak nedbalého.
{12922}{13061}A dùvodem, e se trápíš je bez odhledu na nìj, e?
{13140}{13211}Nemùu o tom Orphovi øíct.
{13232}{13411}Jakmile lidem vìøí, vìøí jim do konce.|Bez ohledu na to, co se dìje.
{13428}{13551}Ale kdyby zjistil tuto pravdu, byl by tak zranìnı...!
{13612}{13672}Je obtínì nìkomu vìøit.
{13689}{13814}To znamená pøesnì pro ty, kteøí mohou vìøit ostatním velmi silnì.
{13867}{13923}Znáš tu sílu, e?
{14585}{14698}Orphe vás povauje za mue, kterı mu zachránil ivot;|vìøí vám z hlouby svého srdce.
{14698}{14758}Øíkal i, e by se s vámi chtìl znovu setkat.
{14777}{14979}Take jsem mu to nemohl øíct. Nemohl jsem mu |øíct, e jste to byl vy, kdo vystøelil tu kulku.
{15066}{15238}Co je to všechno? Kdo sakra jste?
{15308}{15381}Myslíš si, e ti odpovím na tu otázku?
{15381}{15430}Máte nìjakı dùvod, správnì?
{15430}{15447}Øeknìte mi to, prosím!
{15558}{15655}Nemìli byste vìøit dospìlému jako jsem já, dìti.
{15814}{15853}Dìje se nìco?
{15921}{15976}Ne. Na chvilku vyráím.
{15994}{16029}Jen to nechápu.
{16058}{16166}Proè by se mu jako o nì tolik zajímal?
{16244}{16284}Jen je nemùu strpìt sledovat.
{16300}{16387}Je to banda rozmazlenıch dìcek,|jen èekající, aby se dostali do problémù.
{16428}{16554}Ta tvoje jemnost bude jednoho dne tvùj pád.
{16554}{16613}Mìl bys bıt opatrnı.
{16633}{16681}Jsem ti velmi zavázán za varování.
{16695}{16796}Jsi svobodnı ve volbì kterékoli cesty, kterou|si pøeješ, jestli jsi jedinı, kdo je znièenı.
{16821}{16897}Ale není tu nìco, co chceš ochránit?
{17023}{17075}Tohle je od tvojí sestry z domu.
{17226}{17367}Dret nìco, co je ti drahé je jako|dávání okovù na své vlastní nohy.
{17387}{17429}Rozumíš, ne?
{17634}{17763}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{18304}{18386}Aha. Vévoda Forst, hm...
{18662}{18711}Jakou má dnes Profesor Eilos náladu?
{18725}{18755}Samozøejmì, e pøíšernou,
{18755}{18828}Nemá ponìtí o doèasném místì Luiho pobytu, a aèkoli|se domnívá, e Orphe a ostatní pomohli Luimu utéct,
{18828}{18924}nebyl je schopnı chytit pøi dìlání |jakıchkoli podezøelıch pohybù.
{18924}{18966}Zdá se to jako by ho vyšachování znepokojovalo.
{18981}{19059}Všechno protoe ty, jeho malı špion, nedìláš svou práci, eh?
{19073}{19162}V kadém pøípadì bych nedosáhl tolik jistoty, kdybych pro nìj pracoval.
{19162}{19217}Nicholasi, Danieli.
{19217}{19367}Pamatujte, e Profesor Eilos to dìlá, protoe|vìøí, e je to v zájmu školy.
{19367}{19438}Ne, ne docela, Elmunte.
{19452}{19591}Jen se pokouší vyslouit si jízdenku k povıšení.
{19744}{19817}Vypadá to jako by se ti kluci o nìèem hádali.
{19840}{19879}Co si myslíš, e teï udìlají?
{19879}{19993}Bez ohledu na to, co Lui øíká, jsem si jistı, e|se ho mají v úmyslu dret a do konce.
{20020}{20123}Myslím, e bys je mohl nazıvat otevøenımi.|Jsou tvrdohlavá, neústupná skupina.
{20137}{20189}Neustoupí od toho.
{20210}{20279}To je to, co na nich mám rád.
{20279}{20381}Kdy je sleduju, je to jako bych mohl|cítit odvahu sílící uvnitø mì také.
{20381}{20486}Oni jsou opravdu vybráni kandidáti Strahl.
{20501}{20586}A my jsme také kandidáti Strahl.
{20645}{20733}Dìlejme, co mùeme.
{20802}{20818}Správnì.
{20853}{20919}Vidím, e máme v naší skupinì také neústupnou tvrdohlavost.
{21004}{21056}Co se právì teï sakra dìje?
{21074}{21119}Stalo se nìco?
{21119}{21164}Øíkám ti, e nic.
{21164}{21202}Jen jsem unavenı.
{21269}{21290}Nad èím váháš?
{21327}{21362}Øekl jsem ti, e nad nièím!
{21491}{21540}Vypadá to, e tu nade mnou nìkdo vyniká.
{21540}{21601}Nemìl jsem v úmyslu vás pøerušit.
{21699}{21739}Toto je velmi krásná akademie.
{21783}{21951}Poehnané prostøedí, vynikající uèitelé,|zaruèenì pøinese budoucnost...
{21971}{22006}Je to opravdu ideál.
{22027}{22155}Jsem velmi pyšnı, bıt schopnı uèit na Akademii Rosenstolz.
{22193}{22223}Ano...
{22257}{22366}Studoval jsem v zahranièí, take jsem|nikdy nemìl monost studovat tady,
{22383}{22503}ale od té doby, co jsem pøijel, zaèal jsem si|pøát, abych zde také strávil své mládí.
{22625}{22714}O Ludwigovi... co si myslíte?
{22753}{22813}Vìøím, e je nevinnı.
{22865}{23014}I tak, kdybyste zjistili, e opravdu spáchal zloèin?
{23028}{23173}Pak, bez ohledu na co, co se stalo,|bych se postaral o to, aby to odèinil.
{23197}{23271}I kdyby to znamenalo ztrátu pøítele?
{23289}{23399}Fakt, e je to pøítel je vìtší|dùvod proè musím napravit jeho chyby.
{23432}{23550}A jestli je to pøítel, kterı musí kráèet|po bolestivé cestì.. Chci ho podporovat.
{23646}{23794}A kdyby tì pokadé bez ohledu na to, jak vroucnì| si ho pøeješ zachránit, odmetl pryè kdy natáhneš ruku?
{23830}{23869}Nevzdal bych se.
{23915}{24033}Vzdát se a pustit jeho ruku|by znamenalo ho opravdu opustit.
{24313}{24413}Ano. Vzdát se opravdu znamená konec.
{24454}{24523}Nikdy nezapomeò tyto pocity.
{24553}{24572}Ano, pane.
{24766}{24829}Jsi opravdu silnı, Orphe.
{24829}{24842}Ede?
{24897}{24974}Chci tì ochránit.
{25060}{25187}Ale vidím, e to neznamená jen slepì|se tì pokoušet ode všeho ochránit.
{25219}{25319}Není ádná zmìna v mıch pocitech, e tì chci ochránit.
{25319}{25442}Ale v tu samou dobu, vìøím, e jsi pøítel, kterému mohu |svìøit své tìlo a kterı se mùe svìøit své tìlo mnì,
{25442}{25512}pøítel s kterım mohu spoleèenì kráèet.
{25560}{25575}Orphe...
{25687}{25803}Ano, také ti vìøím. Tvé síle.
{25933}{26014}Came, nelíbila se ti ta chu?
{26027}{26080}Ne, to není tím.
{26080}{26199}Já jen... domnívám se, e obloha vypadá opravdu tmavì.
{26217}{26237}Obloha...?
{26268}{26322} Nezdají se tam bıt ádnı dešové mraky.
{26344}{26404}Ne, ne to...
{26404}{26524}Nìco velkého a èerného se blíí.
{26571}{26606}Jsem tu, abych tì vystøídal.
{26606}{26663}Eh? Ještì není èas...
{26923}{26950}Co to znamená?
{26950}{27056}Mám povolení vidìt Jeho Velièenstvo!|Myslíte si, e mùete mít úspìch s...
{27126}{27155}To je státní pøevrat...
{27210}{27347}Take Vévoda a Vévodkynì Liechtenstein a|Ludwig ještì nebyli lokalizováni?
{27347}{27399}Ještì ne. Dìláme všechno, co mùeme.
{27422}{27553}Musíme je ukrıt pøedtím, ne je najdou ostatní.
{27879}{27932}Zabezpeèili jsme vìtšinu paláce.
{27932}{28040}Dobrá. Vìøím, e jste neublíili ádnému èlovìku uvnitø?
{28040}{28055}Ne, pane.
{28081}{28123}To není státní pøevrat.
{28123}{28222}Dìláme to, abychom dali do poøádku pøemıšlení|pro budoucí království Kuchen.
{28222}{28358}To je nejlepší prùbìh jednání, abychom zprostøedkovali naše|rozhodnutí Jeho Velièenstva a získali jeho pochopení.
{28396}{28450}Teï tedy, budeme pokraèovat do trùnního sálu.
{28468}{28529}Nemùu uvìøit, e jsem skonèil pøipojenı k téhle frašce...
{28563}{28581}Ale...
{28652}{28711}...to je jediná cesta, kterou mám!
{28748}{28775}Isaac?
{28795}{28919}Taky jsem tomu nevìøil... e je zapojenı|do záleitosti s Luiem.
{29067}{29128}Jsem si jistı, e má dùvod.
{29146}{29233}Není ádnı zpùsob, jak by udìlal takovou vìc ze své vlastní vùle.
{29251}{29270}Orphe...
{29674}{29710}Vévodo Forste.
{29729}{29772}Co tím myslíte?
{29824}{29956}Pøišel jsem s nìkolika mui, kteøí by|se velmi rádi setkali s Jeho Velièenstvem.
{30155}{30251}To je poprvé, co jsme se setkali osobnì, Vaše Velièenstvo.
{30374}{30401}Ty jsi...
{30906}{30942}Zaèali jednat!
{31522}{31634}-Oslnivá obloha, západ slunce.-
{31634}{31762}-Hráli bychom si pod poulièními lampami.-
{31780}{31893}-V mrazivou noc, lustr visí z oblohy-
{31893}{32039}-pomalu se houpající.-
{32065}{32285}-Mùj hlas existuje jen, aby volal tvé jméno.-
{32285}{32546}-Pevnì svírám tvé malé, tøesoucí se prsty...-
{32546}{32685}-Èas pro nás dva zaèal ubíhat,-
{32685}{32806}-netøeba nièeho, ani slov.-
{32806}{32931}-Oh, pták zavøenı v kleci, tvá køídla naproti tvım òadrùm.-
{32931}{33063}-Tato obloha poslala toho ptáka tobì...-
{33462}{33481}Náhled Pøíští Epizody
{33555}{33663}Uzavøenı palác. Volba. Hrdost.
{33692}{33761}Nechtìl jsem vás znovu potkat takhle.
{33761}{33783}MRTVİ BOD
