{1}{1}23.976
{314}{382}-Kdo to byl, e mì vedl za ruku?-
{382}{467}-Dìtské vzpomínky...-
{522}{694}-Vdycky kdy jsem se vzbudil, mé sny zmizely, pomíjivì jako bublina.-
{728}{912}-Vyléèím tvùj nekoneènı smutek.-
{912}{1074}-My, kdo nemùeme ít osamìle.-
{1125}{1224}-Co mùeme vidìt za naším osudem?-
{1224}{1327}-Pøíbìh o oslnivé slávì-
{1327}{1494}-Sny v mé levé ruce, a drící se tì svou pravou,-
{1537}{1634}-chci záøit jako úsvit.-
{1634}{1739}-Pøíbìh o oslnivé slávì.-
{1739}{1910}-To vzácné svìtlo je v mé ruce...-
{2389}{2441}Vrátil jsem se, Vaše Velièenstvo.
{2457}{2501}Zdá se, e jsem to stihl vèas.
{2522}{2550}Vskutku.
{2568}{2603}Jsem rád, e jsi zpátky.
{2665}{2698}Dìkuji ti, Geralde.
{2714}{2759}Vypadá to jako bys dodrel slib.
{2759}{2784}Ano, pane.
{2897}{2991}Je neblahé, e jsme se opìtovnì shledali za tìchto okolností,
{3108}{3124}Beruze.
{3237}{3282}NADÌJE
{3342}{3402}Domnívám se, e jsi mì v minulosti zachránil.
{3402}{3502}Jsem velmi šastnı bıt schopnı ti teï splatit ten dluh.
{3572}{3716}Toto je slib mezi tvou vlastí|a královstvím Kuchen,
{3716}{3780}aèkoli to ještì není oficiální.
{3795}{3840}Isaacova vlast?
{3890}{4004}Jestli je to pravda, znamená to, e moje mise bude upravena.
{4020}{4093}Jsem si jistı, e co nevidìt dostaneš pøíkazy ze své zemì.
{4093}{4148}Nemusíš ztrácet svùj ivot pro nic.
{4335}{4384}Zdá se, e jsem pìknì mírnı.
{4407}{4426}Isaacu.
{4471}{4495}Chápu.
{4542}{4629}Tvé zmizení bylo pod pøíkazy krále?
{4737}{4761}Co to znamená?
{4777}{4861}Pro království Kuchen je obtíné|uchovat si nezávislost
{4861}{4967}vzhledem k nepoøádku a chaotickım událostem souèasného svìta.
{4993}{5103}Vskutku, spousta zemí se pokouší|pøinutit Kuchen k aliancím.
{5118}{5234}Pro udrení nezávislosti a našeho míru,|musíme pouívat jakékoli pro nás pøístupné metody.
{5248}{5397} A tak jsme vyhledávali spolupráci se spoustou|absolventù Akademie Rosensrolz v kadé zemi,
{5397}{5536}a otevøeli jsme diskuzi a vyjednávání|s hlavami tìch zemí.
{5536}{5604}Byl jsem poádán jednat jako posel pro tento zámìr.
{5622}{5676}Nemìl by zde bıt nikdo kvalifikovanìjší.
{5676}{5763}A jedno z ovoce naší práce je toto.
{5851}{5926}Zdá se, e tento plán také selhal.
{5944}{6026}Vy všichni jste mi nikdy nepøestali vstupovat do cesty.
{6085}{6100}Øediteli!
{6428}{6451}Beruze.
{6658}{6673}Orphe.
{6673}{6696}Já vím.
{6715}{6768}Je to stejné jako tehdy...
{6814}{6924}Kdy èelil Orphovi v Akademii Rosenstolz.
{6972}{7086}Srdce toho mue je plné zloby a nenávisti,
{7127}{7178}ale ještì hloubìji ne je tohle všechno...
{7246}{7303}Musíme ho zastavit!
{7358}{7416}Mám pøedstavu, kam smìøuje.
{7442}{7459}Pojïme.
{7495}{7508}Ano.
{8568}{8699}Soudì podle toho, jak vypadáš, tvùj plán selhal, e, Beruze.
{8858}{8899}Jsi zproštìn, ne?
{8899}{9012}Znal jsem tvou slabost a byl jsi| donucen se mnou spolupracovat.
{9012}{9104}Ale ještì ne. Ještì není všechno u konce.
{9104}{9184}Prostì s tím pøestaò. Teï to chápeš, ne?
{9239}{9317}Bez ohledu na to, co dìláš, tvé opravdové pøání nikdy...
{9344}{9385}A co ty víš?!
{9403}{9421}Ty...!
{9662}{9685}Øediteli Wernere?
{9685}{9723}Co tady dìláte?
{9783}{9823}Take jsi dopaden.
{9823}{9953}Vyzpovídáš se ze svıch høíchù pøed svımi vlastními studenty?
{10078}{10170}V kadém pøípadì, musím ti to podat za zjištìní, kde jsem byl.
{10184}{10273}Tvùj dozor byla èást mé mise.
{10288}{10373}Ano. Na konci jsem po tom všem outsider.
{10373}{10442}Není ádnı zpùsob jak bych byl dùvìryhodnı, e?
{10468}{10578}Nikdy tu nebylo místo, kde|bych byl potøeba na prvním místì.
{10603}{10639}Vím to.
{10743}{10784}Øediteli Wernere, prosím pojïte tudy.
{10801}{10855}To je v poøádku, Orphere.
{10892}{11015}Pøišel jsem sem, protoe jsem si pøál bıt vedle mého mladšího bratra.|/tak teï mì nasrali... :D/
{11015}{11043}Mladší bratr?!
{11058}{11110}Máme stejného otce.
{11125}{11292}Pøestoe on je èestnı následník|dlouhotrvajícího a chrabrého vévodství,
{11323}{11425}kdeto mùj otec neuznal ani moji existenci.
{11909}{12001}Kdybych tì tenkrát zachránil...
{12001}{12068}Co by mohlo dítì jako ty udìlat?
{12089}{12205}Má matka zemøela brzy po tom,|a já sám jsem si pomáhal.
{12205}{12275}Tak jako tak jsem nepotøeboval tvou pomoc.
{12293}{12447}Oh, ale kdy jsem zjistil, e jsi byl vybrán|jako øeditel Akademie Rosenstolz,
{12462}{12505}myslel jsem si, e to musí bıt osud.
{12534}{12698}Myslel jsem, e poskytnutí tvého pøání by|bylo pøinejmenším smíøení, které jsem mohl vykonat.
{12768}{12781}Ale...
{12781}{12918}Co se tıèe mì, nejsi nic,|jen pìšák, s kterım mohu manipulovat.
{13007}{13051}Neøíkejte tak smutné vìci!
{13102}{13114}Came...?
{13138}{13235}Øeditel Werner se o vás opravdu stará.
{13268}{13327}A vy, vy opravdu...
{13344}{13357}Zmlkni!
{13369}{13391}Beruze!
{13391}{13429}Teï musíš pøestat.
{13446}{13489}Nepáchej ádné další høíchy!
{13507}{13568}Nemohl bys rozumnìt, ne?
{13568}{13645}Jak jsem se ty roky cítil...!
{13727}{13818}To byla jediná cesta, která pro mì byla zanechána.
{13882}{13895}Ede?
{13951}{14031}Øekl jsem to jednou pøedtím, e jste stejnı jako já.
{14088}{14154}Take myslím, e tomu rozumím.
{14172}{14331}Také jsem nikomu nemohl vìøit, a moná|jsem nenávidìl svou matku a otce.
{14407}{14511}Kdybych nepotkal Orpha, moná bych se stal stejnım jako vy.
{14534}{14551}Ede...
{14618}{14663}To proto vám nemùu odpustit!
{14677}{14720}Co dìláte je špatné!
{14720}{14831}Jste opravdu spokojenı s ubliováním ostatním lidem?
{14902}{15012}Celá vaše øeè je jen hloupı blábol zbabìlého ztroskotance.
{15067}{15175}Kladete vinu na vaše narození?|To mùe bıt vdy pøekonané.
{15175}{15413}Znám mue, kteøí vytlaèili své osudy|a upøímnì a slušnì mì vyzvali.
{15509}{15578}Není nic, co zahaluje svìtlo v jejich oèích.
{15578}{15683}Protoe ví, e ještì neprohráli.
{15744}{15872}Nejsou zde lidé, o které se opravdu staráte?
{15917}{16033}Co je to, co si pøejete udìlat tak nutnì,|e byste pošlapal takové pocity?
{16124}{16182}Prosím svìste svou zbraò.
{16357}{16459}Orphere, ty øíkáš to?
{16541}{16673}I ty musíš poadovat pomstu.
{16734}{16791}Nenechám tì øíct, e jsi nikdy nepoadoval.
{16890}{16964}Poaduješ pomstu na mì, na tom,|kdo napomohl smrti tvé sestry.
{17106}{17223}Mùeš mi upøímnì øíct, e to co cítíš, není nenávist?
{17348}{17469}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{18149}{18205}Nenávidìní vás mi nepøinese mou sestru zpìt.
{18205}{18268}Z pomsty se nic nevyklube.
{18284}{18344}Mohl jsem se to nauèit.
{18426}{18514}Právì teï, chci pøemıšlet o pomoci|vám a Øediteli Wernerovi.
{18699}{18729}Jen pìkná slova.
{18729}{18785}Nemùe pro mì bıt ádné odpuštìní.
{19778}{19875}Nikdy jsem si nemyslel, e vıbušniny, |které jsem pøipravil, by se mohly takhle hodit.
{19896}{19968}Jestli se odsud rychle nedostanete,|budete chyceni v plamenech.
{19985}{19997}Beruze!
{20061}{20083}Musíme odejít, Orphe!
{20083}{20097}Ale...
{20176}{20262}Pøišel sem rozhodnutı to udìlat.
{20360}{20434}Vymau ten trn v oku, kterım je má existence.
{20434}{20469}Nejsi šastnı?
{20565}{20615}Jsem rád, e jsem mohl vidìt ty mladé mue,
{20615}{20686}kteøí kráèí opravdovì smìrem pøes tuto dobu.
{20710}{20835}Díky nim jsem mohl poznat, co je mé opravdové pøání.
{20897}{20994}Nikdy u tì znovu neopustím.
{21221}{21243}Omlouvám se.
{21330}{21365}Øediteli Wernere! Beruze!
{21478}{21549}Idiote. Jsi...
{21775}{21811}Není ádnı dùvod, aby jsi tu taky zemøel!
{21826}{21887}Sbohem, bratøe.
{21975}{21989}Beruze!
{22068}{22083}Øediteli Wernere!
{22083}{22150}Tohle místo u to dlouho nevydrí!|Musíme se odsud dostat, Orphe!
{23530}{23610}Opìt jsem byl zachránìn vámi všemi.
{23610}{23638}Jsem vám vdìènı.
{23656}{23686}Dìkuji vám.
{23706}{23899}Ludwigu, velice se omlouvám za hození neèestného|podezøení na rodinu Liechtenstein.
{23899}{24022}Mùj otec si je dobøe vìdom, e to bylo v zájmu zemì.
{24047}{24134}Má matka je pøešastná, e je Vaše Velièenstvo v bezpeèí.
{24134}{24195}Dìlal jsem jí starosti.
{24233}{24330}U si nemùeme dovolit bıt |klidní kolem stavu svìtovıch událostí.
{24346}{24456}Království Kuchen bude jistì |také dostieno ve vodním víru.
{24474}{24574}Pøesnì proto budu potøebovat síly|spousty lidí v dobách, které pøichází.
{24589}{24760}Ti, kteøí znají bolest našich lidí pøestát ty,|kteøí jsou ještì pyšnìjší a ambicioznìjší.
{24776}{24875}Je mou nadìjí, e vy všichni budete|pilnì studovat na Akademii Rosenstolz
{24875}{24955}a pøidáte se k nadanım muùm, kteøí podporují tuto zemi.
{25041}{25182}Vskutku, nebyl bych pøekvapen, najít|vás jednoho dne stojící vedle mì,
{25197}{25247}pøesnì jako to dìlají moji èlenové rady.
{25399}{25425}Profesore Geralde!
{25451}{25491}Take vy jste byl èlen rady!
{25491}{25559}Samozøejmì e jste znal skrytı prùchod v paláci.
{25559}{25632}Proè by se èlen rady jako vy stal profesorem?
{25646}{25715}Byla to ádost od Øeditele Bartholomäa.
{25730}{25870}Pøedvídal, e tu chvíli, co byl pryè,|by mohlo nastat nìco takového.
{25894}{25983}A kdyby se to stalo, øekl, e chce, abych vám byl ku pomoci.
{26002}{26124}Byl to øeditel, kdo se pustil|do nebezpeèné cesty, a ještì...
{26141}{26183}Je to pøesnì jako on, udìlat nìco takového.
{26183}{26197}Ano.
{26216}{26402}Bylo to jen na chvíli, ale bıt s vámi všemi na Akademii Rosenstolz |mi pøipomnìlo mì, kdy jsem byl student. Byla to velká zábava.
{26417}{26447}Prosím, pøijïte zase.
{26464}{26600}Nakonec Akademie Rosenstolz všechny srdeènì vítá, správnì?
{26633}{26649}Samozøejmì.
{26722}{26785}Atmosféra školní pùdy je taková jako pøedtím!
{26785}{26888}Zajímá mì, jestli je to proto, e je Øeditel Bartholomäus zpátky.
{26888}{26942}Øeditel Werner byl také úasnı mu,
{26942}{27017}ale musel odcestovat do cizí zemì|za dalšími záleitostmi, e?
{27035}{27089}Ano, dnes odjídí.
{27156}{27238}Opravdu miluji tuhle akademii!
{27322}{27339}Eilosi.
{27352}{27380}A-Ano!
{27401}{27530}Wernerova reforma je èerstvı vítr, pøesnì,|co v této nové dobì potøebujeme.
{27530}{27606}Plánuju v jeho reformách pokraèovat.
{27606}{27698}Od teï na tebe také spoléhám.
{28291}{28318}Dlouho jsme se nevidìli!
{28337}{28408}Prostì jsem nemohl zapomenout chu èaje zde.
{28591}{28641}Díky, Elmunte.
{28661}{28732}Nevadí mi to. Také miluji kvìtiny.
{28763}{28870}Kolem celé té tìké zkoušky jsme udìlali všechno,|udìlali jsme to jednoduèe, protoe jsme chtìli.
{28870}{28920}Stále jsem vám vdìènı.
{28920}{28962}Je to všechno díky vám.
{28962}{28999}Opravdu, nic jsme neudìlali.
{29016}{29132}Všichni studenti této školy vám|pomáhali, protoe ve vás vìøí.
{29132}{29260}A kromì toho, teï mùeme volnì soutìit|o pozice ve Strahl bez rezerv.
{29329}{29407}Jsem rád, e nebyly ve tøídì kandidátù|Strahl udìlány ádné zmìny.
{29407}{29516}Mìl jsem pocit, e Øeditel Bartholomäaus|by takovou vìc neudìlal.
{29516}{29637}Nebylo by pro vás jednodušší pøidat|se ke Strahl, kdybychom nebyli kolem?
{29637}{29675}Ty opravdu nejsi upøímnı!
{29697}{29759}Nedìlá to ádné rozdíly, kdo je protivník.
{29772}{29862}Rozdrtím kadého, kdo mi èelí svımi vlastními schopnostmi.
{29877}{29934}Nemyslím si, e budeme rozdrceni tak jednuduše.
{29965}{30106}Soutìení s vámi všemi nám dovoluje míøit ještì vıš.
{31472}{31583}-Oslnivá obloha, západ slunce.-
{31583}{31706}-Hráli bychom si pod poulièními lampami.-
{31724}{31841}-V mrazivou noc, lustr visí z oblohy-
{31841}{31987}-pomalu se houpající.-
{32009}{32236}-Mùj hlas existuje jen, aby volal tvé jméno.-
{32236}{32497}-Pevnì svírám tvé malé, tøesoucí se prsty...-
{32497}{32637}-Èas pro nás dva zaèal ubíhat,-
{32637}{32759}-netøeba nièeho, ani slov.-
{32759}{32880}-Oh, pták zavøenı v kleci, tvá køídla naproti tvım òadrùm.-
{32880}{33018}-Tato obloha poslala toho ptáka tobì...-
{33032}{33135}Všem, kteøí jste to zvládli dosledovat a sem, dìkuji!|S tìkım srdcem se louèím s mım drahım Orphem...
{33155}{33212}...a tìším se na další projekt!
