{1}{1}23.976
{315}{385}-Kdo to byl, e mì vedl za ruku?-
{385}{481}-Dìtské vzpomínky...-
{521}{695}-Vdycky kdy jsem se vzbudil, mé sny zmizely, pomíjivì jako bublina.-
{727}{914}-Vyléèím tvùj nekoneènı smutek.-
{914}{1075}-My, kdo nemùeme ít osamìle.-
{1127}{1223}-Co mùeme vidìt za naším osudem?-
{1223}{1326}-Pøíbìh o oslnivé slávì-
{1326}{1492}-Sny v mé levé ruce, a drící se tì svou pravou,-
{1537}{1635}-chci záøit jako úsvit.-
{1635}{1736}-Pøíbìh o oslnivé slávì.-
{1736}{1912}-To vzácné svìtlo je v mé ruce...-
{2762}{2817}Kdo jste, lidi?
{2914}{2927}Orphe!
{3373}{3408}Jsem taky mírnı...
{3839}{3893}SPLETITOST
{4172}{4213}Nevìøím tomu.
{4213}{4314}Lui by nikdy nespáchal vlastizradu.
{4314}{4402}Ale je teï hledanı podezøelı.
{4402}{4488}Kdyby obvinìní nebyla pravda, nebyl|by dùvod utíkat, správnì?
{4488}{4518}Máš pravdu...
{4518}{4600}Vše co by musel udìlat, je pøedloit|dùkaz o své nevinnì pøed Jeho Velièenstvo.
{4614}{4718}Teï to nemùe udìlat. To proto se skrıvá.
{4718}{4747}Jsem si tím jistá.
{4747}{4806}Taky doufám...
{4806}{4871}Pravda se vyjasní.
{4910}{4953}A tak bude Lui nevinnı.
{4978}{5059}Nemùu uvìøit, e se stala taková vìc!
{5075}{5197}Toto je první skandál Akademie Rosenstolz,|od té doby, co otevøela dveøe!
{5197}{5314}Student této školy hledanı policií |za obvinìní z velezrady...
{5379}{5459}Vystopovali jste Ludwiga?
{5459}{5523}E-Err, nikterak.
{5523}{5599}Nemáme ponìtí, kdy vyklouzl z lonic...
{5599}{5647}Nezdá se, e by to studenti vedìli.
{6385}{6447}Fakt, e jeho rodièe také nemohou bıt nalezeni nasvìdèuje, e...
{6447}{6535}...se s nimi moná spojil a utekli za hranice.
{6550}{6581}Uprchli ze zemì?
{6598}{6686}Ale je tu také pravdìpodobnost, |e jsou stále uvnitø zemì.
{6702}{6777}Také kvùli nim ho chci najít tak brzy, jak je moné.
{6809}{6867}Pøeívání na utíkání není nic, jen bolestivé.
{6997}{7064}Ostatní studenti musí bıt velmi rozrušeni.
{7064}{7112}Rád bych abyste se o nì vy všichni starali a dohlíeli na nì.
{7127}{7141}Ano, pane.
{7397}{7452}Udìlali od té doby nìjaké pohyby?
{7486}{7583}Camus onemocnìl, a Naoji ho ošetøuje.
{7583}{7661}Mám také mue, kteøí sledují Orpha a Eda,
{7661}{7708}ale nejsou u nich ádné náznaky pohybù.
{7708}{7794}Zatracenì! Vím, e jsou ti, kteøí pomohli Luimu utéct!
{7794}{7872}Tentokrát je chytím pøi èinu!
{8274}{8409}Profesor Eilos by nikdy nesnil, e Daniel,|mu, o kterém si myslí, e je pouívanı jako špion,
{8409}{8472}vlastnì poskytuje útoèištì podezøelému v jeho vlastním domì!
{8494}{8565}Byl jsem opravd pøekvapenı.
{8565}{8626}Nikdy bych od vás všech neèekal takovı návrh.
{8809}{8864}Postaráme se o situaci v lonicích.
{8877}{8890}Rychle.
{8904}{8979}Prozatím jdìte zde. Je to Danielùv dùm.
{8979}{9065}Jeho rodina je na dovolené, take místo je prázdné.
{9065}{9088}Danielùv...?
{9117}{9178}Myslím, e je to nejbezpeènìjší útoèištì.
{9227}{9281}Proè byste...?
{9281}{9318}Jsme pøesnì jako vy.
{9335}{9425}Je pravda, e proti vám chci vyhrát a pøipojit se ke Strahl.
{9425}{9608}Ale nelíbí se mi mít naši soutì |znièenou takovımi špinavımi triky.
{9710}{9724}Dìkuji.
{9770}{9953}Jen doufám, e z nich Daniel mùe vymámit nìjaké informace.
{9968}{10089}Abych byl upøímnı, nemylel jsem si,|e by s námi tak znaènì spolupracoval.
{10089}{10224}Øíká spoustu ohavnıch vìcí, a má tendenci |vydrádit konflikt pro jeho vlastní pobavení,
{10224}{10253}ale není to špatnı kluk.
{10278}{10300}Ano, máš pravdu...
{10455}{10469}Ede?
{10506}{10586}Oh, zápas u je u konce?
{10604}{10631}Co se dìje?
{10631}{10688}Zdáš se bıt od minulé noci rozèilenı.
{10688}{10725}To nic.
{10725}{10793}Jen jsem moc nespal po problémech, do kterıch jsme se dostali.
{10812}{10888}Pak teï, co jít zkontrolovat Cama?
{11463}{11543}Na nemocnou osobu vypadáš pìknì zdravì, Came.
{11543}{11651}Nikdy jsem nezamıšlel, e bych pøedstíral nemoc.
{11651}{11689}Nemáme na vıbìr.
{11689}{11764}Bylo by to okamitì zpozorováno,|kdyby kdokoli z vás zmizel ze školní pùdy.
{11764}{11865}Ale jestli øekneme, e se stará o Cama,|na chvíli by to mohlo bıt platné jako omluva.
{11889}{11989}Naoji pouil podzemní tunel a |teï je s Luim, pøesnì jak jsme plánovali.
{12012}{12059}Zajímá mì, jestli je Lui v poøádku.
{12059}{12120}Je pro nìj bezpeènìjší se teï nehnout z místa.
{12139}{12217}A chvíli mùeme vyšetøovat tolik, kolik mùeme.
{12234}{12311}Ale Lui byl kolem toho všeho podivnì klidnı.
{12311}{12428}Moná ví, kdo tahá za provázky v pozadí toho incidentu?
{12454}{12504}Ano, pravdìpodobnì ví.
{12520}{12589}Ale nebude o tom s námi mluvit...
{12724}{12870}I uvnitø nìèího pokoje, jestli se zaènete spoleènì shromaïovat,|ostatní studenti se stanou podezøívavımi.
{12870}{12901}To je taktická schùzka.
{12946}{12975}To je adresováno tobì.
{12975}{13001}Díky.
{13061}{13079}Od koho to je?
{13108}{13139}Z královského paláce.
{13648}{13661}Orphe?
{13705}{13805}ádal jsem o audienci u Jeho|Velièenstva, ale mùj poadavek byl odmítnut.
{13880}{13939}Co se to sakra dìje...?
{14305}{14353}Zaoblil jsem své pøedpoklady,
{14387}{14425}ale nebyl tam nikdo podezøelı.
{14425}{14444}Chápu.
{14464}{14526}Jsem si jistı, e je to nepohodlné, ale prosím mìj s tím teï strpení.
{14548}{14661}Projednával jsem s Orphem a ostatními naše budoucí plány.
{14733}{14860}Je to v poøádku. Jsem si jistı, e prokáeme tvou nevinu.
{14913}{14974}Zase jsi se stal silnìjším, Naoji.
{15024}{15206}Síla vybrat si jednu vlastní cestu a|smìle ji následovat... získal jsi ji.
{15206}{15343}Ti, kteøí mì uèili, co je síla,|jsi byl ty, Orphe a ostatní.
{15362}{15517}Jak jsem vás všechny sledoval, mít tak vysoké ambice|a kráèet pøímo napøed, i kdy jste zranìní,
{15517}{15598}zaèal jsem cítit, e chci bıt taky takovı.
{15642}{15708}I kdy mì sleduješ jakı jsem teï?
{15739}{15841}Moná jsi byl pøinucenı udìlat pár krokù zpìt,|ale rozhodnì jsi se nevzdal.
{15993}{16039}Vìøím ti.
{16199}{16328}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{16850}{16881}Nechal jsi ho uniknout?
{16952}{17107}Ale fakt, e Vévoda Liechtenstein a jeho syn |uprchli jen prohlubuje podezøení z vlastizrady.
{17127}{17203}Jestli budou dopadeni, budou nepochybnì odsouzení...
{17203}{17312}To je pro vás nejlepší šance, Vévodo Forste,
{17312}{17445}porazit vašeho nejvìtšího politického|protivníka, Vévodu Liechtensteina.
{17633}{17724}Ale jestli selete, nebudete mít ádnou budoucnost.
{17753}{17829}Mìl byste je odstranit tak rychle, jak je moné.
{17860}{17962}Zvláštì následníka vévodství Liechtenstein.
{17962}{18026}Nmùete si dovolit nechat kolem nìj sníit své hlídky.
{18069}{18131}Udìlám opatøení, abych urychlil pronásledování.
{18131}{18199}A urychlenì vyøiïte plán, kterı jsme projednávali.
{18199}{18294}Mìli bychom jednat pøedtím, ne se nìkdo pokusí vejít nám do cesty.
{18343}{18364}Rozumím.
{18807}{18899}To je dost. U tì nepotøebuju na vyšetøování.
{18937}{18957}Proè?
{18974}{19068}Plán u postoupil na další stupeò.
{19104}{19172}U nejsi nutnı.
{19202}{19268}Teï se cítíš uvolnìnı, ne?
{19303}{19378}Tak jako tak si se mnou nebudeš muset dìlat starosti.
{19431}{19444}Beruze!
{19551}{19635}Opus se mnou zemi.|/já jsem k tomu nechtìla psát ádné poznámky, ale musím;|co ti dva spolu mají, já u ty jejich øeèi nevydıchám :D/
{19736}{19826}Myslíš si, e je to to, co chci?
{20435}{20471}Byl jsi to ty?
{20532}{20630}Co se dìje? Nepøedpokládal jsi jít dnes za Luim...
{20647}{20713}Naoji, nesmìøoval tam Ed?
{20731}{20836}Ed? Ne, nepøišel, ne jsem odešel.
{20890}{20920}Není v lonicích?
{20942}{20960}Ne, není.
{21512}{21594}Rozumím. Dejte  mi okamitì vìdìt, kdyby se nìco dìlo.
{22163}{22177}Came?
{22262}{22283}Co se dìje?
{22302}{22381}Pøedpokládal jsi, e nebudeš schopnı opustit svùj pokoj.
{22420}{22461}Já vím, ale...
{22461}{22536}Chápu, e si dìláš starosti o Luiho,
{22536}{22678}ale jestli nìco udìláme a zjistíme,|jen ho to dostane do nebezpeèí.
{22678}{22774}Já vím, ale jen jsem mìl špatnı pocit...
{22803}{22897}Cítím jako by se k nám pøibliovalo nìco horšího.
{23002}{23060}Hmmm, nevím. Nikdy jsem ho nevidìl.
{23075}{23096}Aha...
{23112}{23161}Vidìla jsem toho mue.
{23176}{23198}Opravdu?
{23212}{23280}Ano, myslím, e to byl pravdìpodobnì on.
{23299}{23327}Kde jste ho vidìla?
{23568}{23585}Co je to?
{23625}{23667}Nevracel se's?
{23667}{23687}Ne...
{23693}{23727}Pøišel sem Ed?
{23727}{23819}Všechno je pøesnì tak, jak to vidíš. |Není tu nikdo jinı, jen já.
{23922}{23984}Byl také v nìèem pøistien?
{24004}{24057}Ještì si nemùeme bıt jistí.
{24086}{24139}Ede, kde jsi sakra šel?
{24227}{24276}V kadém pøípadì, jdu ho hledat.
{24315}{24338}Orphere.
{24368}{24425}U sem nechoï.
{24444}{24459}Coe?
{24489}{24574}Nepotøebuji tvou pomoc.
{24897}{24927}Omluvte mì, prosím uhnìte z cesty!
{25486}{25503}Ede.
{25638}{25685}Jsem ohromenı, e jsi mì našel.
{25711}{25741}Pøišel jsi sám?
{25772}{25787}Jo.
{25808}{25888}Musel jsem se s vámi setkat a nìco si potvrdit.
{25913}{25931}Isaacu.
{26044}{26162}Ten mu, co tam byl vèera... opravdu jste to byl vy, e.
{26223}{26237}Ano.
{26272}{26402}Orphe vás povauje za mue, kterı mu zachránil ivot;|vìøí vám z hlouby svého srdce.
{26402}{26442}Øíkal i, e se s vámi chtìl znovu setkat.
{26465}{26554}Take jsem mu to nemohl øíct.
{26581}{26665}Nemohl jsem mu øíct, e jsi byl ten, kdo vystøelil tu kulku.
{26759}{26928}Co je to všechno? Kdo sakra... jste?
{27000}{27074}MYslíš si, e ti odpovím na tu otázku?
{27074}{27112}Máte nìjakı dùvod, správnì?
{27112}{27137}Øeknìte mi to, prosím!
{27329}{27414}To proto vás všechny nazıvám mírnımi!
{27414}{27512}Vdycky jste nás zachránil!
{27531}{27625}Bez ohledu na to, kım jste byl,|myslel jsem si, e jste byl nás spojenec!
{27670}{27705}To je tvé nedorozumnìní.
{27723}{27759}Nejsem nièí spojenec.
{27814}{27850}Jsem jen zbabìlec.
{27948}{27964}Isaacu?
{28031}{28067}Kdykoli pøíštì se do toho nezapojuj.
{28067}{28118}Jen dostaò Luiho ze zemì. Rozumíš?
{28141}{28153}Isaacu!
{28153}{28180}Eduarde.
{28334}{28362}Profesore Geralde?
{28384}{28436}Co dìláš na takovém místì?
{28436}{28483}Je dlouho po veèerce.
{28483}{28573}A tohle není místo, kde by chodil student.
{28588}{28601}Ano, pane...
{29514}{29629}Myslíš, e v takové situaci mùeš nìco udìlat sám?
{29650}{29721}Na  prvním místì je to mùj problém.
{29721}{29801}Prosekám si svou cestu bez pomoci kohokoli.
{29819}{29914}Vím, e to mùu udìlat.
{29939}{29955}Ale...
{30002}{30071}Jestli bych mìl nìjakou malou šancí selhat,
{30088}{30148}sám se dùstojnì ponesu.
{30275}{30291}Orphe!
{30476}{30494}Ty...!
{31520}{31631}-Oslnivá obloha, západ slunce.-
{31631}{31763}-Hráli bychom si pod poulièními lampami.-
{31781}{31892}-V mrazivou noc, lustr visí z oblohy-
{31892}{32038}-pomalu se houpající.-
{32063}{32286}-Mùj hlas existuje jen, aby volal tvé jméno.-
{32286}{32539}-Pevnì svírám tvé malé, tøesoucí se prsty...-
{32539}{32685}-Èas pro nás dva zaèal ubíhat,-
{32685}{32804}-netøeba nièeho, ani slov.-
{32804}{32931}-Oh, pták zavøenı v kleci, tvá køídla naproti tvım òadrùm.-
{32931}{33064}-Tato obloha poslala toho ptáka tobì...-
{33457}{33476}Náhled Pøíští Epizody
{33516}{33618}Zloba. Skrytá jemnost. Pøítel.
{33641}{33719}Nikdy si nedovolíme tì ztratit!
{33768}{33785}STÍN
