{1}{1}23.976
{161}{209}{C:$3399ff}Kiss Kiss Fall in love
{340}{433}{C:$3399ff}I notice that
{433}{484}{C:$3399ff}I'm always around you
{484}{560}{C:$3399ff}but is it hating? Liking?
{560}{613}{C:$3399ff}Or just paranoia?
{613}{706}{C:$3399ff}When I can see
{706}{761}{C:$3399ff}my feelings clearly,
{761}{834}{C:$3399ff}lady or host,
{834}{893}{C:$3399ff}it doesn't matter.
{905}{976}{C:$3399ff}The reason for which
{976}{1044}{C:$3399ff}people fall in love
{1044}{1129}{C:$3399ff}is different for everyone, but-
{1129}{1176}{C:$3399ff}MAYBE YOU'RE MY LOVE
{1176}{1241}{C:$3399ff}I want to meet you now
{1241}{1305}{C:$3399ff}and give you, a sweet person,
{1305}{1363}{C:$3399ff}a cherry blossom kiss.
{1363}{1420}{C:$3399ff}If your heart moves from it,
{1420}{1456}{C:$3399ff}let's have a romantic love!
{1456}{1522}{C:$3399ff}More important than the future
{1522}{1588}{C:$3399ff}is the present.
{1588}{1701}{C:$3399ff}The delightful spring love is
{1701}{1816}{C:$3399ff}a blossom virgin's aesthetic.
{1893}{1959}{C:$3399ff}MAYBE YOU'RE MY LOVE
{2479}{2540}Mohly by se tu objevit obludy.
{2548}{2638}Take musím rychle najít svého brášku.
{2677}{2732}Bráška je krásnı princ.
{2732}{2820}Bude mì pøed obludami bránit.
{3271}{3318}[TØETÍ HUDEBNÍ UÈEBNA]
{3676}{3704}Vítej.
{3766}{3844}Jejda, copak to tu máme za zvláštního hosta?
{3844}{3942}Vítej, zbloudilé koátko.
{3978}{4092}Kdy jsem otevøela dveøe,|našla jsem policejní stanici.
{4150}{4216}{C:$FF00FF}"Oniichama je princ"
{4286}{4363}Kdepak ses tu vzala, malièká?
{4450}{4491}Obrácenı harém!
{4505}{4569}Tohle je obrácenı harém!
{4613}{4640}Ale ale, tohle není dobré.
{4640}{4741}Vypadá to, e mám ještì z plavání vodu v uších.
{4778}{4834}Pøesnì tak, pane Generální inspektore!
{4834}{4996}Asi mámì nìco s ušima, jinak|bychom tu malou neslyšeli øíkat "obrácenı harém".
{5024}{5060}Shuchi nikurin!
{5060}{5159}[Suchi Nikurin je slavnost, kde z fontán prıští víno a maso pokrıvá stromy, oznaèení dekadentní párty.]
{5159}{5212}Tady je shuchi nikurin!
{5227}{5269}Brejloun.
{5282}{5309}Dìcko.
{5309}{5343}Nemluva.
{5359}{5397}Incest.
{5410}{5444}Gariben.|[Gariben je oznaèení nìkoho, kdo hodnì studuje.]
{5631}{5666}Bráška...
{5739}{5801}Jseš blonïák, take musíš bıt mùj bráška!
{5801}{5834}O tomhle jsme nikdy neslyšeli!
{5834}{5866}Ty máš sestru?
{5866}{5916}Ne. Jsem si naprosto jistı, e nemám sourozence!
{5916}{5955}Alespoò tedy myslím.
{5955}{6032}Ale vánì jste si podobní.
{6032}{6081}Oba jste blond.
{6081}{6174}Jsou 'brejloun' a 'bráška'|v té samé skupinì slov?
{6174}{6216}Hej, to není tak špatné.
{6216}{6267}Alespoò nejsi gariben jako já.
{6267}{6296}Umm...
{6296}{6343}Jak se jmenuješ, dìvèátko?
{6343}{6365}Kirimi!
{6365}{6390}Kirimi?
{6390}{6448}{C:$2020C7}[Stejná vıslovnost jako...|krájená syrová ryba]
{6448}{6522}Kirimi, urèitì si mì s nìkım nepleteš?
{6522}{6592}Jsem si jist, e nemám mladší sestru.
{6648}{6726}I kdy jsi blonïáèek, tak nejsi mùj bráška?
{6726}{6759}{C:$2020C7}[Má na krajíèku]
{6811}{6827}Já...
{6842}{6862}{C:$2020C7}[Má na krajíèku]
{6862}{6891}{C:$2020C7}[Citovì labilní]
{6933}{6949}Dobrá!
{6949}{7007}Od teï budu tvùj bráška!
{7007}{7036}Tvùj bráška!
{7047}{7087}Jak sladká, jak sladká!
{7087}{7157}I kdy jsi takhle citovì labilní,
{7157}{7238}...tak si opravdu myslíš, e je dobré|øíkat tyhle hlouposti malım dìtem?
{7238}{7299}To není hloupost! |Budu se o ní dobøe starat!
{7299}{7337}Take jí vezmu zpìt domù!
{7337}{7392}Co budeme dìlat, Kyouyo?
{7392}{7483}Moná má opravdu tady na škole blonïatého bratra.
{7483}{7499}Ne!
{7528}{7578}Kirimi~
{7603}{7637}Kirimi~?
{7769}{7790}Umm...
{7790}{7819}Kdo jsi?
{7836}{7871}To je cizinec!
{7880}{7950}e se zmìnil tvar tìch dveøí, e jo?
{7976}{7995}Kirimi...
{8038}{8058}Mladı pane.
{8058}{8099}Zapomnìl jste svùj pláš.
{8233}{8278}{C:$2020C7}[Prezident Klubu Èerné magie|Nekozawa Umehito] |Ahoj...
{8278}{8308}Nekozawa-senpai?!
{8329}{8365}{C:$2020C7}[U všech èertù!!]
{8376}{8451} Tady mladı pán Umehito nesnáší jasné svìtlo.|
{8451}{8489}{C:$2020C7}[Sluebná rodiny Nekozawa - Kuretake]
{8489}{8553}Take kdy nenosí tento pláš,
{8553}{8640}...nevydrí nápor svìtla a zkolabuje.
{8640}{8746}Musí nosit èernou paruku,|aby zakryl své svìtlé vlasy.
{8797}{8877}[Sekretáø rodiny Nekozawa - Kadomatsu]|Na druhou stranu, jeho sestra, sleèna Kirimi,
{8877}{8915}...nemá ráda temná místa.
{8941}{9013}Take tahle dívka je Nekozawova sestra?
{9038}{9075}Nemá smysl to skrıvat...
{9075}{9115}Ano, máte pravdu!
{9204}{9251}{C:$2020C7}[Nekozawa Kirimi]
{9277}{9319}K-Ki-Ki-Ki-Kirimi...
{9337}{9383}Tak tady jsi...
{9451}{9482}Na pozadí: OBLUDA
{9482}{9512}Obluda!!!
{9512}{9553}Neboj se...
{9567}{9661}Tahle prokletá panenka, Beelzenef, vlastnì není strašidelná.
{9676}{9769}Naše rodina uctívala koèky po generace.
{9769}{9880}No, vlastnì, ona se nebojí té loutky,|ale tebe, Nekozawo.
{9911}{9963}Nejspíš kvùli tomu ohozu.
{9963}{10036}{C:$2020C7}[Buï hezkı] |Pøestaòte! Já umøu!
{10053}{10121}No, tak zatemníme místnost.
{10121}{10135}Néé!
{10135}{10177}Nemám ráda tmu!
{10177}{10203}Jejda, no tak, no tak.
{10203}{10244}A teï si stìuje.
{10259}{10350}Tato tragédie, zpùsobená|naprostou rozdílností jejich povah...
{10350}{10440}...je dùvod, proè se jim øíká|Romeo a Julie rodiny Nekozawa.
{10490}{10555}Romeo a Julie nebyli sourozenci,
{10555}{10613}..a úplnì jiné byly i okolnosti...
{10622}{10649}Já vím.
{10660}{10750}To bylo jen pøirovnání, které mì zrovínka napadlo.
{10750}{10829}Drí nápis: Romeo a Julie rodiny Nekozawa |Napadlo mì, e by to znìlo víc dramaticky.
{10829}{10847}A - ha...
{10859}{10903}Jen tak na okraj, my jsme...
{10903}{10985}...odpovìdní za vyzvednutí sleèny Kirimi ze školy.
{10985}{11035}To všichni z rodiny Nekozawa...
{11035}{11078}...vypadají takhle podezøele?
{11090}{11129}O èem to mluvíte?!
{11129}{11261}Rodina Nekozawa je vznešenı rod, |odvozující svùj pùvod z dynastie Tokarevovcù v Rusku.
{11279}{11299}Tokarev?
{11327}{11386}{C:$3399ff}Také jméno staré sovìtské armádní pistole,|uívané od roku 1930. |TOKAREV
{11386}{11430}Nemyslíš náhodou... dynastii Romanovcù?
{11430}{11501}Existuje také legenda...|Ignoruje mì?
{11502}{11560}...e z neznámého dùvodu, jednou za nìkolik set let,
{11560}{11689}..se narodí nìkdo jako pan Umehito, |kdo miluje temnotu...
{11721}{11784}...bude èi nebude.
{11784}{11833}"Bude èi nebude"?
{11833}{11863}Kterı to je...
{11863}{11901}Kniha: Album Rodiny Nekozawa
{11901}{11955}Kvùli tomu tmavému plášti...,
{11955}{12034}...se mladı pán nikdy nemohl pøiblíit ke své sestøe,
{12034}{12071}...a sleèna Kirimi si namísto toho...
{12071}{12186}...zamilovala krásného prince, bratra jako z pohádky,|kterého vídala na portrétu.
{12195}{12265}Jakmile se dozvìdìla,|e sem její bratr chodí na støední skolu,
{12270}{12391}...chodí sem a pátrá po panu|Umehitovi jako napøíklad dnes.
{12405}{12424}Samozøejmì,
{12424}{12562}...celı ten èas jsme ji utìšovali kníkami o princích,
{12562}{12613}...a, ach bìda, nám došly zdroje,
{12613}{12720}...take jsme pøešli na dívèí mangy,|kde se objevují princové,
{12720}{12776}...a ona si je zamilovala...
{12792}{12830}Dívèí manga?
{12830}{12882}Tohle je obrácenı harém!
{12882}{12903}Shuchi nikurin.
{12920}{12974}Tady je shuchi nikurin!
{13014}{13064}Take tahle sluebná je pøíèina?!
{13074}{13128}Shuchi nikurin v dívèí manze?
{13141}{13180}{C:$2020C7}[Sashimi]
{13141}{13180}Tedy, Sashimi...
{13192}{13229}{C:$2020C7}[Kirimi]
{13192}{13229}Myslíš Kirimi, ne?
{13229}{13253}To je Kirimi!|[Její kanji znak znamená také "mlná kráska"]
{13281}{13380}Kirimi neví, e jsi její bratr?
{13398}{13414}Já...
{13429}{13531}Ano, snaili jsme se jí to mnohokrát vysvìtlit,|ale ona tomu nevìøí.
{13544}{13606}Ale Neko musí bıt tak smutnı.
{13622}{13637}Ano.
{13653}{13672}Proto...
{13698}{13816}...se kadı veèer modlím,|aby mìla Kirimi ráda temnotu.
{13835}{13879}Ale to by mìlo bıt naopak.
{13879}{13941}Ty by sis mìl zvyknout na jasná místa.
{13941}{13983}Co chceš udìlat svojí sestøe?
{13983}{14007}Tak tedy, sleèno Kirimi.
{14007}{14036}Vrátíme se domù.
{14036}{14059}Nééé!
{14059}{14113}Chci zùstat s bráškou!
{14113}{14165}Je lepší bıt s bráškou!
{14209}{14237}Nekozawo...
{14267}{14313}To je v poøádku, Suou.
{14328}{14388}Nedìlejte si o mì starosti.
{14408}{14427}Prosím...
{14436}{14481}Prosím, postarej se dobøe o Kirimi!
{14496}{14523}Nekozawo!
{14631}{14711}Sourozenci jsou pøíèinou potíí v kadé rodinì.
{14760}{14797}Závidím jim.
{14839}{14890}Já jsem jedináèek.
{14931}{15009}Pøesto... i kdy mají dalšího sourozence,
{15009}{15090}...je smutné, e nemohou bıt spolu.
{15224}{15274}Co se dìje, bráško?
{15297}{15333}Promiò, Kirimi.
{15362}{15421}Já nejsem tvùj bráška.
{15464}{15525}Ale neboj se.
{15549}{15693}Kirimi, máš mnohem lepšího brášku ne mì: svého pravého.|
{15746}{15767}Senpai?
{15793}{15827}Jakmile jsi pøekroèila náš práh,
{15837}{15900}...jsi hostem našeho klubu, Kirimi.
{15918}{15962}My, Ouranskı Hostitelskı Klub, existujeme...
{15973}{16038}...abychom pøinášeli dámám štìstí!
{16051}{16126}Tito dva sourozenci, kteøí chtìjí|bıt spolu, ale nemohou...
{16135}{16183}Takhle to nesmí zùstat!
{16198}{16220}Nyní...
{16235}{16357}...uskuteèníme velkı plán k pøetvoøení Nekozawy|na krásného prince, jaké má ráda Kirimi!
{16357}{16387}{C:$2020C7}[Ve zkratce]
{16387}{16435}{C:$2020C7}[Plán na pøetvoøení charakteru]
{16435}{16452}U zas...
{16472}{16500}A-ale...
{16500}{16578}Zmìnit temnou náturu pana Umehita?
{16599}{16643}Øíkáte, e to je moné?
{16656}{16743}Haló! Jen proto,|e se do všeho tak bezhlavì vrháš...
{16743}{16792}...nemusíš øíkat takovéhle nesmysly-
{16811}{16832}Copak jsi zapomnìla?
{16853}{16989}Máme silného spojence,|kterı je obzvláštì talentovanı v pøetváøení charakterù.
{17008}{17030}Ty myslíš...
{17030}{17058}Neøíkej mi...
{17058}{17120}Oh-hohohohohohohohoho...
{17120}{17157}{C:$2020C7}[VYSOKOVİKONNİ MOTOR]
{17157}{17202}Oh-hohohohohohohohoho...
{17202}{17227}Já to vìdìl...
{17243}{17324}Oh-hohohohohohohohoho...
{17334}{17342}Hoho!
{17610}{17663}{C:$2020C7}[Tøetí chemická/fyzikální uèebna]
{17663}{17708}{C:$2020C7}[S moností zatemnìní]
{17811}{17880}Tvé zlaté vlasy, které vlají skrz svíce...
{17895}{17950}Tvá záøivá ple, pøipomínající slonovinu...
{17950}{18058}Tvùj úsmìv, tajemnìjší ne pùlnoèní kvítí...
{18058}{18101}Ano, to je...
{18202}{18289}...hrozivé jako prokletá vosková figurka!
{18313}{18343}NE!!!
{18357}{18396}Ty... debile!
{18396}{18456}Kdo tì uèil tohle øíkat?!
{18456}{18509}Jasnì jsem øekla,|e okultní terminologie je zakázaná!
{18509}{18555}Jak dlouho bude trvat, ne to pochopíš?!
{18555}{18572}Ale...
{18584}{18658}Mùj slovník obsahuje jenom takovéhle obraty...
{18683}{18741}{C:$2020C7}[Sparanská vıchova!] |ádné odmlouvání!!!
{18741}{18818}ádnı princ nemùe tak snadno øíkat takovéhle ubohosti.
{18830}{18847}Poslouchej!
{18847}{18911}Je dobré mít stinnou stránku, ano, stinnou stránku.
{18911}{18982}A bıt samotáø na mladé dívky také zabírá!
{18982}{19077}Ale nyní jsou tihle okultní pitomci úplnì mimo hru!
{19077}{19139}Mori, napiš další zakázané slovo!
{19139}{19193}Vosková figurka, ano?
{19203}{19243}Renge pìknì bìsní.
{19243}{19282}Opravdu se v tom vyívá.
{19282}{19373}No, nevím nevím, jestli tohle na jeho sestru zabere...
{19392}{19456}Mùj pane, ty se na to budeš jen dívat?
{19456}{19501}No... nechci bıt potom proklet...
{19501}{19592}No vıbornì, zapamatoval sis vìtšinu slovních fází.
{19602}{19669}Mùeme pokroèit k 'tomu'.
{19695}{19715}Zadr...
{19736}{19794}Ještì je pøíliš brzy...
{19794}{19845}Ïáblùv paprsek!
{19893}{19910}{C:$2020C7}[Pouhá baterka]
{19911}{19959}Neztrácej hlavu kvùli obyèejné baterce!
{19960}{19989}Uka se!
{19989}{20092}Není to problém ve tvıch kvalitách...|...je to o síle tvé vùle!
{20092}{20171}I Edward si poradil s køíem silou vùle a trochou kuráe.
{20216}{20262}Copak jsi nezakázala všechno okultní?
{20262}{20346}Je to v poøádku jako pøíklad, ne jako styl oblékání.
{20346}{20367}Opravdu...
{20367}{20395}To ona vdycky...
{20395}{20450}...nosí divné cosplaye.
{20450}{20521}Ale co je nejdùleitìjší,|tvá øeè postrádá jakıkoliv zápal.
{20521}{20602}Musíš ve svém zkušebním partnerovi vidìt Kirimi.
{20602}{20650}Vím, co tím myslíš...
{20664}{20723}..ale Kirimina tváø nemá tak popelavou barvu.
{20723}{20755}{C:$2020C7}[Ve skuteènosti je to hnìdá]
{20755}{20788}ádné vımluvy!
{20788}{20852}Musíš ji vidìt oèima svého srdce.
{20852}{20886}Oèima svého srdce!
{20898}{20910}Ano,
{20910}{20960}...tohle všechno dìláš pro Kirimino dobro.
{20960}{21033}Pokud dokáeš otevøít své srdce,
{21015}{21109}...pak v této figurce uvidíš Kirimi.
{21261}{21294}Hej, mùj pane!
{21325}{21369}Nìco jsme ti pøipravili.
{21369}{21388}{C:$2020C7}[Pouhá figurína]
{21388}{21459}No tak, vyznej lásku téhle napodobeninì Haruhi!
{21459}{21516}{C:$2020C7}[Bez vırazu]
{21516}{21599}Tohle... má bıt Haruhi?
{21599}{21665}Všechno se nejlépe ukáe na pøíkladu!
{21884}{21926}Ha... Haruhi...
{21958}{21976}Já...
{22052}{22091}{C:$2020C7}[Pohled srdcem - Zapnuto!]
{22148}{22176}Senpai...
{22237}{22258}e vyrušuji...
{22299}{22319}Haruhi?!
{22319}{22351}Ta pravá?
{22351}{22391}Kdy ses tu-
{22391}{22469}Kirimi dnes zase pøišla do klubu...
{22481}{22554}...take kdy máš èas na takovéhle nechutnosti...
{22554}{22634}...mohl bys ho místo toho trávit s Kirimi?
{22656}{22718}Nápis na pozadí: Nechutné|Nech-Nechutné?!
{22835}{22891}Nechutné... Nechutné... Nechutné... |Co se dìje, Haruhi?
{22891}{22924}S dìtmi ti to nejde?
{22938}{23036}Ne, ne e bych nemìla ráda dìti...
{23036}{23079}{C:$2020C7}[Opakování] |Šprte, ještì!
{23079}{23175}*tlukot* *tlukot* | "Teï je otrokem mé lásky."
{23175}{23266}"Take, s kım se budu bavit dnes veèer?"
{23284}{23393}...ale, za poslední tøi dny|u jsem jí pøeèetla pìt knih dívèí mangy.
{23395}{23516}Èlovìèe, v nìkterıch bylo vánì plno|obrácenıch harému a shuchi nikurinù.
{23516}{23546}Bráško?
{23666}{23711}Je tu tak temno!
{23764}{23807}Ach, Kirimi!
{23807}{23867}Øíkala jsem ti, a na mì poèkáš v tamtom pokoji.
{23867}{23913}Ále, copak se stalo?
{23931}{23991}U je dobøe, u je dobøe, no tak!
{23991}{24030}U ádné strachy!
{24137}{24154}Hopla!
{24358}{24370}Senpai?
{24402}{24468}Jsem jako krásnı princ...
{24468}{24521}Jsem jako krásnı princ...
{24521}{24576}Jsem jako krásnı princ...
{24587}{24633}Jsem jako krásnı princ...
{24644}{24706}Jsem jako krásnı princ...
{24706}{24756}Nebojím se svìtla!
{24756}{24815}Ïáblùv paprsek na mì!!!
{24837}{24856}Super!
{24893}{24937}Nekozawa je koneènì...
{24949}{25018}...schopen odolat svìtlu baterky!
{25018}{25053}Bravo! Bravo!
{25064}{25094}Nekozawo!
{25094}{25123}Dokázal to!
{25132}{25186}Jsem si jistı, e Kirimi bude šastná!
{25186}{25223}Podívej, Kirimi.
{25224}{25344}{C:$2020C7}<= TOHLE
{25245}{25325}Tohle je tvùj pravı bráška.
{25410}{25436}Bráško!
{25450}{25469}Kirimi!
{25538}{25563}Pardon,
{25563}{25641}...ale pro ostatní je tohle vánì trapné,|mohl bys toho nechat?
{25641}{25654}Co?
{25668}{25689}Øíkala jsi nìco?
{25689}{25724}To je jedno.
{25755}{25775}Kirimi...
{25900}{25978}{C:$2020C7}[Strach, kterı nelze vyjádøit slovy]
{26054}{26073}Kirimi!
{26178}{26218}Ten ïáblùv paprsek...
{26218}{26266}...pro ní musel bıt strašnı.
{26283}{26304}Kirimi...
{26388}{26422}Nekozawo...
{26507}{26548}Vzdávám se...
{26548}{26613}Není tu ádná záruka, e další trénink...
{26613}{26681}...zaruèí, e mì Kirimi pøijme.
{26725}{26859}Bude šastnìjší, kdy její bratr bude Suou...|...místo aby mìla za bráchu mì.
{26922}{26996}Ty jsi ten, kterého chce vidìt, mám pravdu?
{27035}{27080}Pokud máš svou sestru opravdu rád,
{27080}{27139}...tak uka víc vùle!
{27282}{27299}Co?
{27312}{27361}Tvá sestra je poøád na nádvoøí.
{27361}{27405}Nìco tam má.
{27419}{27452}No jo, koèka.
{27487}{27537}Jak se dá èekat od koèky uctívající rodiny.
{27537}{27584}I toulavé koèky se k vám mohou pøijít lísat.
{27596}{27614}Ne!
{27630}{27689}I kdy naše rodina uctívá koèky,
{27706}{27830}...tak se nic tak okultního, jako strakatá|koèka jdoucí k tobì, nemùe stát.
{27855}{27900}Kirimi nemá ráda zvíøata,
{27921}{27996}...a nejvíc se bojí koèek!
{28146}{28171}Kirimi!!!
{28171}{28197}Nekozawo!
{28197}{28246}Bez pláštì nemùe vyskoèit z okna!
{28386}{28413}...pomoc...
{28439}{28467}Kirimi!!!
{28548}{28581}Kirimi!!!
{28829}{28873}Bráško!
{29029}{29054}Skvìlé!
{29081}{29130}A to díky mému vıcviku!
{29176}{29203}Podívej, Kirimi.
{29203}{29238}U se není èeho bát.
{29238}{29276}Zlé koèky jako tahle...
{29333}{29417}...mùeš zaplašit silou téhle prokleté loutky, Beelzenefa...
{29417}{29446}...takhle nìjak...
{29953}{29988}{C:$2020C7}[O nìkolik dní pozdìji]
{30158}{30192}Nekozawo...
{30192}{30286}Pravdìpodobnì onehdy utrpìl celoivotní dávku svìtla.
{30284}{30373}Musel se jako reakci vrátit do stavu pøed vıcvikem.
{30384}{30411}Škoda...
{30411}{30513}Take nakonec zase nosí tu ponurou róbu.
{30570}{30587}Ale...
{31471}{31557}I kdy se objeví obluda,|jsem v bezpeèí.
{31557}{31689}Protoe je tu nìkdo, kdo pro Kirimi vyskoèí|z okna do svìtla, kterého se štítí...
{31689}{31745}...a zachrání mì.
{31745}{31813}Mám prince brášku!
{31812}{31899}Pøeklad: Charlie|Korekce: Taylor
{31991}{32066}Bìet pìt tisíc mil,
{32074}{32129}Bìet bez dechu.
{32141}{32212}Sto litrù adrenalinu
{32212}{32304}Mì plní energií.
{32322}{32398}Jít tahle daleko je fajn, e?
{32398}{32463}Jak daleko bude OK?
{32463}{32542}Stromy, které zdobí mìsto
{32542}{32630}Stále mìní svùj vzhled.
{32650}{32723}Úplnì jiná bílá
{32723}{32768}Stále stejná slabost
{32779}{32909}Chci vìøit sám v sebe tady a teï.
{32909}{33000}Zdvíhám vysoko levou i pravou ruku
{33000}{33072}Prorazit temnotu a vpøed!
{33082}{33139}Nic není falešné
{33167}{33225}Moje rozhodnost slábne!
{33249}{33327}Start! Právì od teï...
{33327}{33413}Mùj svìt se musí otevøít!
{33464}{33501}Miluji sladkosti!
{33501}{33564}Honey, pak si nestìuj,|a tì budou bolet zuby.
{33564}{33581}To bolí!
{33581}{33603}Jako bych to neøíkala...
{33603}{33631}To je moje vina.
{33631}{33703}V pøíštím díle, |"Honeyho tøi dny bez sladkostí".
{33703}{33792}Ouranskı hostitelskı klub na vás bude,|jako obvykle, èekat i pøíští tıden.
