{1}{1}23.976
{161}{209}{C:$3399ff}Kiss Kiss Fall in love
{340}{433}{C:$3399ff}I notice that
{433}{484}{C:$3399ff}I'm always around you
{484}{560}{C:$3399ff}but is it hating? Liking?
{560}{613}{C:$3399ff}Or just paranoia?
{613}{706}{C:$3399ff}When I can see
{706}{761}{C:$3399ff}my feelings clearly,
{761}{834}{C:$3399ff}lady or host,
{834}{893}{C:$3399ff}it doesn't matter.
{905}{976}{C:$3399ff}The reason for which
{976}{1044}{C:$3399ff}people fall in love
{1044}{1129}{C:$3399ff}is different for everyone, but-
{1129}{1176}{C:$3399ff}MAYBE YOU'RE MY LOVE
{1176}{1241}{C:$3399ff}I want to meet you now
{1241}{1305}{C:$3399ff}and give you, a sweet person,
{1305}{1363}{C:$3399ff}a cherry blossom kiss.
{1363}{1420}{C:$3399ff}If your heart moves from it,
{1420}{1456}{C:$3399ff}let's have a romantic love!
{1456}{1522}{C:$3399ff}More important than the future
{1522}{1588}{C:$3399ff}is the present.
{1588}{1701}{C:$3399ff}The delightful spring love is
{1701}{1816}{C:$3399ff}a blossom virgin's aesthetic.
{1893}{1959}{C:$3399ff}MAYBE YOU'RE MY LOVE
{2111}{2137}A sakra...
{2194}{2227}Tys to teda zvrtal.
{2227}{2271}Tohle není naše vina...
{2271}{2312}P-Pitomci!
{2312}{2368}Strèili jste do mì!
{2380}{2432}No, Haruhi utíkala...
{2432}{2529}Koneènì jsme mìli šanci navlíknout Haruhi|do cosplaye a uít si trochu švandy.
{2529}{2585}Vdycky jsme v cosplayi!
{2585}{2643}Ne naše obvyklé klubové!
{2643}{2692}Ale sehnali jsme kostımek králíèka:
{2692}{2749}...mohli jsme jí dodat dívèí šmrnc.
{2749}{2775}Dívèí šmrnc?
{2775}{2821}{C:$2020C7}[Jsem dívka, abyste vìdìli...]
{2821}{2874}Ty by ses chtìl také podívat,|e ano, mùj pane?
{2895}{2988}{C:$2020C7}[Tamakiho Kino Bujné Pøedstavivosti]
{2988}{3025}Jo, jasnì, já-
{3025}{3090}Ne, teï na to není vhodná chvíle!
{3090}{3177}Hej, co to dìlají ty ruce,|nesnaíte se zneuít situace?!
{3177}{3226}Odstupte od Haruhi!!!
{3226}{3266}My nechcem~
{3290}{3315}Poslyšte...
{3315}{3426}Teï nemáme ádné hosty,|take mi nevadí nìjaké to pozdviení.
{3426}{3460}Ale víte, co dìláte?
{3460}{3507}Honey se mùe probudit.
{3715}{3788}On chodí odpoledne spát,|i kdy u je na støední škole?
{3788}{3851}No, s tím, co jste rozlili,|u nic nenadìláte.
{3851}{3894}Prostì ho probuïte a omluvte se.
{3894}{3953}Stùj! Nepøibliuj se k Honeymu!
{3953}{4006}Rychle! Schovej se tady!
{4006}{4029}Coe?
{4029}{4100}Honey je krapítek labilní, kdy se probudí.
{4100}{4118}He?
{4134}{4172}Je to jen povìst,
{4172}{4241}...ale jednou, v americkém tréninkovém táboøe,
{4241}{4316}...kdy rodina Haninozuka |zajišovala speciální bojovı vıcvik,
{4316}{4422}...spal Honey bìhem èekání na odlet.
{4440}{4505}Hej, chlape, si v poøádku?
{4505}{4660}A tehdy, kdy jeden z vojákù neopatrnì šel|a probudil Honeyho zrovna, kdy spal...
{4704}{4796}{C:$2020C7} Já Ještì Spím
{4833}{4868}Ó Mùj Boe
{4999}{5083}Dvì èety Zelenıch baretù, americkıch zvláštních sil...
{5083}{5163}...byly v okamiku vyhlazeny Honeym.
{5163}{5234}Povídá se, e ten inciden vyeskaloval|a do mezinárodní roztrky se Spojenımi státy.
{5234}{5263}Dìsivé...
{5263}{5305}A navíc, tohohle plyšového králíèka...
{5305}{5402}...Honeymu udìlala jeho oblíbená prababièka.
{5411}{5466}A fakt,e ho vdycky nosí s sebou...
{5466}{5513}...znamená, e je to pro nìj obzvláš drahocenná vìc.
{5513}{5579}Jestli ho probudíš a on uvidí...
{5579}{5644}...svého králíèka takhle zøízeného...
{5784}{5858}...skonèíme totálnì øízení taky!!!
{5876}{5907}To pøeháníte...
{5918}{6002}Ta povídaèka zní trochu blbì, a myslete si, co chcete.
{6028}{6116}Ne, jestli chceš zkoušet,|jestli má Honey zlé alter-ego,
{6116}{6140}...máme jich víc.
{6140}{6205}Honey má krevní skupinu AB.
{6205}{6223}No a?
{6236}{6349}No a... má stejnou krevní skupinu jako Kyouya.
{6371}{6419}{C:$2020C7}Extrémnì podezøelé!!
{6470}{6534}Co je špatného na mojí krevní skupinì?
{6576}{6687}Diváci, kteøí máte skupinu AB,|prosím nezlobte se na nás.
{6776}{6798}To je zlé.
{6798}{6853}Musíme nìco podniknout, ne se probudí.
{6853}{6872}Hikaru, Kaoru!
{6894}{6901}Rozkaz!
{6912}{6972}[Cessna - model letadla] |Seeòte vaší rodinnou Cessnu!
{6972}{7046}[Itako - nevidomé osoby, které umí rozmlouvat s mrtvımi,|obyèejnì se shromaïují na hoøe Osore] |Zalete na horu Orore a pøiveïte itaka.
{7046}{7117}Musíme si promluvit s Honeyho babièkou...
{7117}{7175}...aby nám udìlala nového králíèka!
{7175}{7208}Vezmìte si s sebou tuhle mapu prefekrury  Aomori!
{7220}{7283}Nezapomeòte cestou koupit jableènı dus a koláè,,
{7283}{7345}[Nabuta - festival, pøi kterém|po mìste vozí velké figurímy] |...a také nezapomeòte na figurku Nebuta!
{7345}{7377}Na to nemáme èas...
{7377}{7431}Mùeš zaèít panikaøit,
{7431}{7493}...anebo pøijít s nìèím konstruktivnìjším.
{7502}{7538}Tak zkusíme tohle...
{7538}{7593}Zatímco pošleme králíèka do èistírny,
{7593}{7662}...Haruhi... oblékni si tenhle kostım.
{7662}{7702}Dobrı nápad!
{7702}{7797}{C:$2020C7}[Tamakiho a Dvojèat Kino Bujné Pøedstavivosti]
{7819}{7843}Ani omylem!
{7855}{7919}A navíc, kde jste to vyhrabali?
{7919}{7956}To je tak okatı!
{7956}{7978}Neboj se!
{7978}{8002}Bude rozespanı,
{8002}{8060}...toho drobného rozdílu si nevšimne!
{8060}{8112}Tak si to obleè ty!
{8112}{8174}- Ne! Ne! Ne! Ne! | - Kdy si to oblíknu já, tak to nebude tak roztomilé!
{8174}{8199}- Ne! Ne! Ne! Ne! Ne! Ne! Ne! |- Moná jsem se musel vzdát králièího kostımku,
{8199}{8253}- Ne! Ne! Ne! |...ale s tímhle budeš alespoò králíèek!
{8253}{8310}{C:$2020C7}[Smysl nerozpoznatelnı]|Staò se králíèkem!
{8336}{8374}Ne, tohle nezvládnem!
{8374}{8396}Nemáme na vıbìr:
{8396}{8428}...pouijeme jinou náhraku!
{8874}{8910}Mùj medvídek!!!
{8922}{8970}Jsme další na øadì!!!
{8970}{9039}Uáá, králíèek byl objeven!!!
{9266}{9348}Kdo umazal mého králíèka?
{9355}{9463}{C:$2020C7}[Prosíme, pouijte svou pøedstavivost|k zobrazení vırazu jeho tváøe]
{9463}{9535}P-P-P-Pomoc, Mori!
{9555}{9660}Králíèek... se chtìl hroznì moc napít èaje.
{9742}{9768}Aha!
{9768}{9831}Proto má oblièejík celı špinavı!
{9841}{9880}Bude také jíst dortíky?
{9923}{9974}{C:$2020C7}[Staèilo tak málo?]
{10052}{10119}{C:$FF00FF}"Honeyho tøi dny bez sladkostí"
{10137}{10192}Honíku, jakou èokoládu máš nejradìji?
{10203}{10243}Šlehanou? Bonboniéru?
{10254}{10313}Nebo máš rád èokoládové dorty?
{10324}{10353}Umm...
{10367}{10406}Já mám rád všechny!
{10406}{10479}Mám rád èokoládu, mého králíèka, úplnì všechny!
{10479}{10530}Kyaa- jak sladké!
{10573}{10646}Honey - Haninozuka Mitsukuni (17):
{10653}{10738}...tøída 3-A, tøeák na Ouranské støední|a èlen Hostitelského klubu;
{10738}{10798}Jeho nejoblíbenìjší vìci jsou dortíky, èokoláda,|a jeho králíèek.
{10798}{10882}Je obdaøen roztomilostí,|kterou tøeáci obvykle nedisponují...
{10882}{10947}...a je nepøekonatelnı loli-shota charakter.|
{10947}{11010}Honey dnes vypadá hodnì šastnì.
{11010}{11110}Jsem rád, e se ta aféra|s králíèkem urovnala v míru.
{11124}{11223}Slabost pro sladké a roztomilé vìci jsou|Honeyho hlavní pøednosti...
{11223}{11284}...nebo tomu tak je alespoò teï,
{11284}{11358}...ale já osobnì takovéto bezvırazné|charaktery moc ráda nemám!
{11366}{11441}Není v tom dostatek smutku!
{11503}{11528}Honey,
{11537}{11595}...nemìl bys jíst tolik sladkostí.
{11607}{11676}Nestìuj si mi pak,|a tì rozbolí zuby.
{11676}{11697}Neboj se:
{11697}{11737}...èistím si zoubky.
{11746}{11774}[Auu]
{11865}{11887}Honey...
{11906}{11938}Neøíkej mi, e...
{11951}{12007}To nic... není...
{12007}{12057}No tak, otevøi pusu.
{12057}{12073}Hej!
{12073}{12125}Honey, zùstaò v klidu!
{12125}{12180}To nic není! To nic není!
{12180}{12211}Ne~!
{12359}{12396}Ano! Tohle! To je ono!
{12406}{12443}Tohle tomu chybìlo!
{12443}{12491}Tohleto MOE!
{12686}{12732}Je to kaz?
{12743}{12749}Ano.
{12756}{12826}Bolí to, co? |e to bolí, e jo?
{12841}{12860}Ne...
{12869}{12895}Jsem v poøádku...
{12921}{12940}Tamaki.
{12940}{12981}Ach, dobrá.
{12981}{13004}Rozumím.
{13060}{13078}Umm...
{13103}{13222}Honey, máš zakázané sladkosti,|dokud se tvùj zub nevyléèí.
{13222}{13305}Po tento èas, kadı v klubu...
{13305}{13391}...musí kontrolovat mnoství sušenek,|které se tu snìdí.
{13420}{13451}Ne, Takashi...
{13470}{13522}Nechci, aby byly sušenky zakázané...
{13522}{13609}To ne... bolí... u to nebolí!!
{13665}{13696}Stùj!
{13710}{13764}To je mùj dortík!
{13796}{13837}To je zakázané.
{13903}{13943}A takto zaèíná...
{13943}{14036}...Honeyho peklo na zemi.
{14235}{14285}Chudáèek Honík...
{14285}{14359}Slyšela jsem, e v klubu|zakázali všechny sladkosti.
{14359}{14402}Musí to bıt pro nìj šok.
{14402}{14459}Ale, i kdy to mùe znít indiskrétnì,
{14451}{14514}...jeho souèasnı stav je tak...
{14516}{14540}{C:$2020C7}[Malı Králíèek] |...e ano?
{14553}{14586}Tak rozkošnı!
{14716}{14761}Mitsukuni, tvoje aktovka.
{14761}{14796}Ponesu ji sám.
{14796}{14848}Ne, dej mi ji.
{14990}{15031}Chtìl jsem se na nì jen koukat,
{15031}{15088}...nechtìl jsem je jíst. | - Rozumím.
{15088}{15169}Jestli ses chtìl jen koukat,|vezmi si tohle.
{15271}{15311}Ty pravé si vezmu.
{15472}{15510}To musí bıt tvrdé.
{15510}{15547}{C:$2020C7}|[Trio prvákù kontroluje situaci]|Chudák...
{15563}{15660}Ale nikdy jsem si nepomyslel,|e by Mori mohl bıt a tak pøísnı.
{15660}{15691}Velmi neoèekávané.
{15704}{15797}Myslím, e prostì nedovolí nic,|co by Honeymu mohlo ublíi.
{15797}{15860}I náš pán ho musí poslouchat.
{15943}{15974}{C:$2020C7}[Hostitelskı Klub je právì otevøen]
{15974}{16015}Tamaki, je to škoda.
{16032}{16186}Chtìla jsem, abys okusil novou èokoládu od našeho patissiera.|(Patissier - cukráø v kuchyni, èasto pod vedením vedoucího kuchynì.)
{16206}{16267}Ale slyšela jsem,|e sladkosti jsou tu teï zakázané.
{16267}{16320}Nebuï tak smutná, má princezno.
{16320}{16407}Pro dobro Honeyho,|kterı se teï musí stranit sladkostí,
{16407}{16468}...ho chceme podpoøit, jak jen dokáeme.
{16468}{16552}Jejda, pøátelství mez mui je tak krásné...
{16605}{16672}Mimoto, tohle je to nejlepší, co jde dìlat.
{16672}{16724}A je èokoláda sebelepší,
{16724}{16771}...pøed naší planoucí láskou...
{16771}{16850}...se prostì rozpustí a zmizí.
{16879}{16909}Tamaki...
{16958}{16992}Dobrá práce, mùj pane.
{16992}{17026}Hezké pøedstavení.
{17026}{17055}Mìníš rychle.
{17068}{17095}Dejte mi pokoj.
{17095}{17167}Naším hlavním cílem je,|bez ohledu na situaci,
{17167}{17213}...úsmìv na tváøích našich zákaznic.
{17213}{17249}Vy byste se také nemìli flákat.
{17249}{17363}[*úšklebek*]|A nedávejte Honeymu ádné sladkosti,|bez ohledu na to, jaké triky pouije.
{17363}{17432}Ah, a jen tak pro poøádek,|tohle je Moriho pøíkaz.
{17432}{17464}Ne mùj.
{17478}{17568}Kyouya... si to, zdá se, uívá.
{17874}{17915}Já u to nevydrím...
{17932}{17964}Opravdu chci...
{17980}{18071}..aby mì mìl Mori rád...
{18194}{18216}Nemùeš?
{18266}{18403}To proto, e u máš rád nìkoho jiného?
{18497}{18551}Je tu nìjaká jiná, e ano?
{18684}{18701}Já...
{18748}{18763}Já...
{19083}{19162}Honeyho Strategie èíslo 1: Naléhej roztomile
{19183}{19221}Ta~kashi!
{19221}{19292}Mùj zoubek se uzdravil!
{19317}{19332}Aha.
{19348}{19398}A opuchlina je pryè!
{19416}{19436}Aha.
{19456}{19482}Tak...
{19499}{19588}Mohl bych dostat jeden dortík, prosím?
{19634}{19681}{C:$FFFF80}Nápis: Zmrzlina
{19775}{19835}Vypadá to, e plné uzdravení chvilku potrvá...
{19866}{19950}Honeyho Strategie èíslo 2: Nepøímı útok
{20106}{20152}{C:$FFFF80}[Vystrašené]
{20177}{20207}Copak to pijete?
{20229}{20279}Jen èaj, Honey.
{20279}{20301}Hmm...
{20317}{20352}A co jíte?
{20352}{20410}N-Nìjaké sendvièe.
{20410}{20440}Hmm...
{20499}{20624}Já... myslím, e k èaji by vıbornì|šly sladké sušenky!
{20624}{20701}Tøeba dortíky, e ano, e ano?
{20734}{20796}{C:$2020C7}[Oèekávání a vzrušení]
{20835}{20867}Zvuky okolo Honeyho a jeho mumlání: *vzrušenı*|Tak...
{20878}{20908}Ale my...
{20979}{21028}...promiò nám, Honíku!
{21041}{21083}Tohle je pro tvé dobro!
{21083}{21120}A-Ach, poèkejte!
{21278}{21369}Honeyho Strategie èíslo 3: Pomohou slzy
{21436}{21458}Honey?
{21505}{21525}Harunko.
{21539}{21584}Jsem zlobivé dítì?
{21609}{21714}Udìlal jsem nìco,|za co mì bùh nenávidí?
{21867}{21887}Poslouchej.
{21887}{21924}Jenom trochu, ano?
{21980}{21999}Sušenka?
{22015}{22028}Jo.
{22073}{22105}Tady.
{22148}{22188}Na krabici: Chaluhy Kyoto
{22188}{22232}Je to jako èokoláda... alespoò barvou.
{22262}{22337}{C:$FFFF80}Honey - > špatná osoba
{22425}{22532}{C:$2020C7}[Zákaz sladkostí - Den tøetí]
{22532}{22604}Bìící nápis: Roztrpèenı
{22753}{22777}Je naštvanı.
{22790}{22824}Nìkdo by s ním mìl promluvit.
{22836}{22868}Já se pøíliš bojím.
{22884}{22930}Áá, jde do skøíòky se sladkostmi!
{22930}{22986}Neboj, je prázdná.
{22998}{23067}Kyouyo, vypadáš šastnì.
{23388}{23499}Áá, mùj medvídek, u zase!
{23567}{23602}Ach, je mrtvı.
{23614}{23654}Vzdal to po tøech dnech?
{23688}{23728}H-Honey?
{23811}{23843}Zlomí mi jí!
{23864}{23897}Auvajs...
{24058}{24092}Mitsukuni.
{24092}{24165}Pøestaò si vylévat svùj vztek na vìcech a lidech.
{24252}{24279}Jsem zachránìn...
{24279}{24310}Nebudu serán...
{24365}{24389}Mìl by ses stydìt.
{24428}{24465}Takashi...
{24499}{24523}...ty pitomèe!!!
{24691}{24755}Jen málo by staèilo, ty neøáde!
{24755}{24780}Tvrdohlavı bejku!
{24780}{24803}Takashi...
{24821}{24902}Takashi... nenávidím tì!!!
{25062}{25088}Ach, Honey!
{25220}{25246}Mori...
{25258}{25288}Jsi v poøádku?
{25404}{25454}/Takashi... nenávidím tì!!!
{25454}{25497}/Takashi... nenávidím tì!!!
{25507}{25547}/Takashi... nenávidím tì!!!
{25574}{25630}Moriho se to vánì dotklo,
{25630}{25681}...ale s tím se nedá nic dìlat...
{25681}{25719}Mùe si za to sám...
{25719}{25844}Nemìl øíkat všechny ty vìci,|za které ho teï Honey nenávidí.
{25875}{25907}Udìlal to schválnì?
{25923}{25994}Mori, mohlo to bıt...
{25994}{26077}...tak, es chtìl, aby tì Honey nenávidìl?
{26100}{26137}Samozøejmì, e ne.
{26137}{26268}Bıt nenávidìn Honeym by byl|pro Moriho konec svìta.
{26283}{26332}Proè by to mìl dìlat?
{26332}{26401}Tøeba, aby si sám ublíil?
{26475}{26503}Mılím se?
{26561}{26611}Je to moje chyba.
{26686}{26779}Moje nedbalost mu zpùsobila tu bolest.
{26872}{26976}Zapomnìl jsem mu øíct, aby si|pøed spaním èistil zuby... dvakrát.
{27006}{27069}To nemùe bıt...
{27069}{27104}...pøeci Moriho vina?
{27117}{27179}Kdyby museli Mitsukinimu vytrhat všechny zuby...
{27191}{27215}Já... Já...
{27254}{27303}Ne, on ne, on ne...
{27303}{27353}Je nìjakı pesimistickı.
{27366}{27434}Kdyby mì Mitsukuni takhle neodhodil,
{27434}{27498}...nedokázal bych si odpustit.
{27512}{27562}Byl na Honeyho strohı...
{27586}{27668}...protoe tím trestal sebe, nebo ne?
{27683}{27759}Hej, to znìlo jako z nìjakého|laciného románu...
{27759}{27828}...ale proè všechno tohle kvùli malému kazu?
{28020}{28080}A to je celé, Honey.
{28113}{28156}Co teï udìláme?
{28364}{28393}Promiò mi!
{28393}{28452}Promiò, Takashi!
{28477}{28547}U nikdy si nezapomenu èistit zuby!
{28565}{28604}Nikdy...
{28872}{28916}{C:$2020C7}[O nìkolik dní pozdìji]
{28916}{28952}O nìkolik dní pozdìji,
{28952}{29072}....jakoby v reakci na zákaz sladkého,| se Honey uzdravil,
{29072}{29151}...a spoøádal horu dortíkù.
{29223}{29255}Kyouyo,
{29255}{29300}...vypadáš znièenì.
{29315}{29371}Honeyho úètenky za dortíky...
{29371}{29418}...byly tak vysoké?
{29437}{29454}Promiòte...
{29489}{29542}Och, e by nová klientka?
{29717}{29755}Moriho fanynka, co?
{29787}{29816}To je ta dívka...
{29983}{30032}Koneènì chápu...
{30061}{30128}...kdo je Moriho drahá osoba.
{30577}{30668}Nemohu uvìøit,|e pro tebe nejdùleitìjší...
{30668}{30693}...je Honey...
{30703}{30724}To je...
{30736}{30756}To je...
{30773}{30794}...tak...
{30794}{30823}...tolik...
{30845}{30875}...skvìlé!!!
{30900}{30913}Coe?!
{30979}{31083}Vypadá to, es vkroèila|do nového svìta.
{31206}{31271}Mitsukuni, máš tu nìjakı krém.
{31320}{31350}Kya-
{31350}{31367}Moe-
{31367}{31394}Totální Moe-
{31408}{31432}Tohle je nejlepší!!!
{31432}{31466}Nejlepší!!!
{31466}{31483}Kya-
{31483}{31580}Nálada jak u šastného konce.
{31580}{31607}Totální moe!
{31607}{31695}...ale je v pohodì, aby díl |jako tenhle mìl šastnı konec?!
{31695}{31760}MOE!!!
{31785}{31804}Dobrı Boe...
{31812}{31899}Pøeklad: Charlie|Korekce: Taylor|pouité titulky (aneb jak ušetøit práci s èasováním): luqas123
{31991}{32066}Bìet pìt tisíc mil,
{32074}{32129}Bìet bez dechu.
{32141}{32212}Sto litrù adrenalinu
{32212}{32304}Mì plní energií.
{32322}{32398}Jít tahle daleko je fajn, e?
{32398}{32463}Jak daleko bude OK?
{32463}{32542}Stromy, které zdobí mìsto
{32542}{32630}Stále mìní svùj vzhled.
{32650}{32723}Úplnì jiná bílá
{32723}{32768}Stále stejná slabost
{32779}{32909}Chci vìøit sám v sebe tady a teï.
{32909}{33000}Zdvíhám vysoko levou i pravou ruku
{33000}{33072}Prorazit temnotu a vpøed!
{33082}{33139}Nic není falešné
{33167}{33225}Moje rozhodnost slábne!
{33249}{33327}Start! Právì od teï...
{33327}{33413}Mùj svìt se musí otevøít!
{33457}{33521}Proè má Tamaki hedvábnı šátek?
{33521}{33581}Proè Kyouya sedí na houbì?
{33581}{33643}Vypadá to, e ti nošení tohohle|nepomáhá dret krok s pøíbìhem.
{33643}{33694}V pøíštím díle|"Haruhi v ríši divù"
{33694}{33781}Ouranskı hostitelskı klub na vás bude,|jako obvykle, èekat i pøíští tıden.|
