{1}{1}23.976
{161}{209}{C:$3399ff}Kiss Kiss Fall in love
{340}{433}{C:$3399ff}I notice that
{433}{484}{C:$3399ff}I'm always around you
{484}{560}{C:$3399ff}but is it hating? Liking?
{560}{613}{C:$3399ff}Or just paranoia?
{613}{706}{C:$3399ff}When I can see
{706}{761}{C:$3399ff}my feelings clearly,
{761}{834}{C:$3399ff}lady or host,
{834}{893}{C:$3399ff}it doesn't matter.
{905}{976}{C:$3399ff}The reason for which
{976}{1044}{C:$3399ff}people fall in love
{1044}{1129}{C:$3399ff}is different for everyone, but-
{1129}{1176}{C:$3399ff}MAYBE YOU'RE MY LOVE
{1176}{1241}{C:$3399ff}I want to meet you now
{1241}{1305}{C:$3399ff}and give you, a sweet person,
{1305}{1363}{C:$3399ff}a cherry blossom kiss.
{1363}{1420}{C:$3399ff}If your heart moves from it,
{1420}{1456}{C:$3399ff}let's have a romantic love!
{1456}{1522}{C:$3399ff}More important than the future
{1522}{1588}{C:$3399ff}is the present.
{1588}{1701}{C:$3399ff}The delightful spring love is
{1701}{1816}{C:$3399ff}a blossom virgin's aesthetic.
{1893}{1959}{C:$3399ff}MAYBE YOU'RE MY LOVE
{2184}{2245}{C:$2020C7}[Novináøskı krouek] |Pane pøedsedo!
{2245}{2318}Pøedplatné na naše noviny|nám nezaplatí ani inkoust.
{2331}{2386}Jaká je aktuální suma?
{2396}{2462}Kolik jsme prodali víkendovıch èísel?
{2462}{2487}Dvì.
{2517}{2535}Jenom?
{2544}{2562}Dvì.
{2581}{2600}Ukyo.
{2617}{2661}Koupil sis jedny?
{2661}{2680}Ano.
{2712}{2733}Sakyo.
{2749}{2784}Ty sis taky jedny koupil?
{2796}{2814}Ano.
{2844}{2933}Take mimo èlenù našeho klubu|si je nikdo nekoupil?
{2967}{3055}Pokud to takhle øeknete,|tak tedy ano.
{3084}{3113}Máme problém.
{3132}{3209}Pøíští víkendové èíslo je poslední v tomhle semestru.
{3209}{3284}Pokud pøed prázdninami|nepøijdeme s nìèím lepším,
{3284}{3361}...náš klub bude rozpuštìnı, jako tenhle semestr.
{3361}{3413}Mimochodem, jak se "jim" vede?
{3413}{3429}Ano.
{3439}{3544}Všech sto kopií fotokolekce Hostitelského klubu|"Náš miláèek Tamaki Speciál"...
{3544}{3588}...bylo rozprodáno ihned|po svém uvedení do prodeje.
{3597}{3676}A jejich doujinshi, které na svou pìst|publikuje Renge Houshakuji,|(Doujinshi je amatérská tvorba èerpající z oblíbenıch mang)
{3676}{3726}"Moe Moe Deník Ouran Vol. 8,"|(Na obálce také stojí "Speciální èíslo s brılemi", aèkoliv to neètou)
{3726}{3792}...byl takté vèera rozprodán,
{3792}{3857}...a teï si nechává dìlat dotisk.
{3857}{3884}Aha...
{3955}{4023}Vypadá to, e jsou právì teï trhák.
{4224}{4250}Vítejte.
{4351}{4416}{C:$FF00FF}"Interview se Slavnım Hostitelskım Klubem"
{4416}{4472}{C:$2020C7}[Hostitelskı klub je otevøen]
{4472}{4514}To nesmíte, pane Tamaki.
{4519}{4559}Jestli se k vám ještì víc pøiblíím,
{4559}{4672}...budou mì všechny vaše obdivovatelky nenávidìt.
{4672}{4695}Má princezno!
{4695}{4796}Tyto hortenzie nás pro tuto chvíli urèitì ukryjí.
{4825}{4866}V tuto chvíli jsem jen tvùj.
{4879}{4977}Ano, jen teï... |kdy nám hortenzie pomáhají se skrıt...
{4977}{5016}{C:$2020C7}[Zakázaná hra na rande] |Pane Tamaki...
{5016}{5059}{C:$2020C7}[Zakázaná hra na rande]|Chci se s vámi milovat.
{5059}{5079}Princezno!
{5135}{5199}{C:$2020C7}[Hra "Které mušle do sebe pasují?"]
{5235}{5271}Pardon~
{5292}{5324}Zase jsem prohrál?
{5362}{5417}Šetøete ho, milé dámy.
{5417}{5467}Kaoru je uplakánek.
{5467}{5510}Hikaru, ty lháøi!
{5510}{5546}Komu øíkáš uplakánek?
{5571}{5608}Zase se bráníš,
{5613}{5728}...ale kdy si hrajeme na trestání,|co se vdycky stane, Kaoru?
{5739}{5796}Ale to jsi byl ty a-
{5796}{5821}Coe? Coe?
{5821}{5857}Co se stalo?
{5857}{5969}Jejda, odkdy je na nádvoøí|tenhle pìknı potùèek?
{5969}{6010}Jmenuje se "yarimizu".|(Yarimizu je potok v zahradách,|kde se dá ruènì øídit proud vody)
{6010}{6128}V éøe Heian mìli lidé rádi,|kdy kvìty a okvìtní lístky pluly na hladinì...|(Éra Heian: 794-1185 n.l.)
{6128}{6191}...a takhle to mohli zaívat ve všech roèních obdobích.
{6191}{6263}A já mìl touhu strávit s vámi|všechna roèní období, mé krásky,
{6263}{6289}...take jsem ho nechal vybudovat.
{6303}{6343}A co tohle?
{6343}{6433}Zarezervujete si svá místa v exkluzívní|Èajové párty rudıch kvìtù ve vodopádu?
{6433}{6471}Zarezervujeme!|(Nápis: ZAREZERVUJEME!)
{6493}{6570}Budeme jíst soba v tomto dvoumístném haori.|(Haori bylo v éøe Heian pánské kimono, nyní je univerzální)
{6630}{6659}Huh?
{6686}{6728}Jak sladké!
{6757}{6794}Je tu tak pokojnì...
{6794}{6857}Tak tohle mìli na mysli,|kdy øíkali nìco podniknout.
{6857}{6929}Dìlám to od chvíle, kdy jsem nastoupila do školy.
{6929}{6967}Haruhi, kryj se!
{7156}{7172}Hikaru!
{7172}{7256}Haruhin plamen ivota byl málem uhašen!
{7256}{7300}Nebylo tu pokojnì?
{7328}{7402}Byla to tvoje chyba, es ho nechytil, mùj pane.
{7402}{7462}Jestli nedokáeš hrát kemari,|(Kemari je hra. pùvodem z éry Heian, ve které|se musí koenı míèek - mari - udret ve vzduchu.)
{7462}{7505}...tak zneuctíš svùj titul Ouranského Hikaru Genji. | (Hikaru Genji - Záøivı Genji - je hrdina Pøíbìhu o Genjim.)
{7506}{7520}Coe?
{7534}{7599}- Øekni to znova! |Za úèelem pøeití novináøského klubu...
{7599}{7672}...je nejspíš budem muset poprosit o pomoc, ano?
{7672}{7721}Poèkejte, pane Pøedsedo.
{7721}{7755}Zahrávat si s nimi je pøíliš nebezpeèné!
{7755}{7779}Pokud se nìco stane,
{7779}{7846}...nejene bude klub rozpuštìn,|ale i my vylouèeni!
{7846}{7866}Co?
{7866}{7905}Tak chytej!
{7905}{7975}Hvìzdnı kop!
{7989}{8000}Coe?
{8035}{8059}To je fofr!
{8059}{8109}Opatruj se!
{8137}{8176}{C:$2020C7}[Avšak, bez kontroly...]
{8176}{8218}Není se èeho bát.
{8218}{8276}Nejsem tak hloupı,|abych zpùsobil nìjaké škody...
{8276}{8337}...nezáleí na tom, jak se s nimi vypoøádám-
{8343}{8372}Pane pøedsedo!
{8394}{8448}Strašnì se omlouváme!
{8448}{8497}Ale no tak.
{8497}{8593}Je to jen rozbité okno a Mori,|co mi pøistálo pøímo na hlavì.
{8607}{8636}Velmi se omlouváme!
{8636}{8706}{C:$2020C7}[Pøedseda novináøského klubu| Komatsuzawa Akira - Tøeák]|Ale, jak pøíhodné.|
{8706}{8808}{C:$2020C7}[Èlen klubu Ukyo Chikage - druhák]| Vlastnì jsem chtìl váš klub poádat|o interwiew do našich školních novin.
{8808}{8838}{C:$2020C7}[Èlen klubu Sakyo Tomochika - druhák]
{8838}{8870}My máme novináøskı krouek?
{8870}{8925}Ano, ale dìlají tohle.
{8925}{8961}Také známé jako "Ou-Spo".
{8961}{9018}Vìci jako romantické klevety na koleji,|(Na titulku: Romantická láska mezi dvìma lidmi|z rozdílnıch sociálních skupin)
{9018}{9093}...nebo mocenské boje mezi rodinami,|které zpùsobují tøenice ve tøídách...
{9084}{9175}Bulvární plátek, kterı otiskává tyhle bombastické vımysly.|(Na titulku: Vzpoura ve fotbalovém tımu?)
{9185}{9219}Ale protoe je to všechno vymyšlené,
{9219}{9275}...tak to nikdo neète.
{9275}{9406}Je pravdou, e chceme upozoròovat|a upoutávat pozornost na pravdu.
{9406}{9484}Ale teï, kdy klubu hrozí zánik,
{9484}{9543}...jsme ztratili všechny iluze.
{9566}{9674}Pøišli jsme na to, o èem bychom mìli psát pro masy.
{9700}{9727}Prosíme vás.
{9741}{9802}V posledním èísle semestru...
{9798}{9872}bychom chtìli mít|"Speciální blízkı pohled na hostitelskı klub",
{9872}{9980}...chtìli bychom osobnì zblízka poznat|pravdu skrytou za šarmem vašich èlenù.
{9980}{10006}Prosím pomozte nám.
{10029}{10060}Na nás se mùete spolehnout!
{10060}{10118}Pøijímáme tento-
{10118}{10142}Odmítáme.
{10142}{10159}Kyouyo!
{10159}{10212}Má zranìní kvùli mì!
{10212}{10240}Naneštìstí,
{10240}{10345}...publikujeme tyto informace pouze našim zákaznicím.
{10345}{10436}O vyrovnání škod a bolestném se mùeme pobavit jindy.
{10436}{10455}Správnì.
{10455}{10553}Pomáhat lidem, kteøí celou dobu|píší vymyšlené pomluvy...
{10553}{10608}V tomhle nápadu nevidím ádnou vıhodu.
{10608}{10623}Ech,
{10623}{10723}...navíc nemáme rádi lidi,|kteøí ostatním pùsobí problémy.
{10723}{10793}Nìkteøí by se mìli podívat na sebe.
{10793}{10817}Chápu...
{10856}{10933}Naše minulé høíchy nemohou|bıt tak snadno vymazány...
{10933}{11023}Nedostaneme ani šanci je odèinit, ech...
{11041}{11101}Ach, mé srdce puká...
{11101}{11126}Pane pøedsedo!
{11138}{11206}Dìkuji vám, Ukyo, Sakyo.
{11210}{11277}Ach, opìt mì jímá závra! |Pane pøedsedo!
{11277}{11304}Jsem v poøádku-
{11326}{11358}Pane pøedsedo!!!
{11370}{11446}Asi budeme muset nechat|tento klub rozpustit...
{11446}{11475}To nesmíte!
{11489}{11537}Lidé mohou vdy zaèít znovu.
{11537}{11560}Tak dobrá.
{11560}{11617}Shromádím pro vás informace o našem klubu...
{11617}{11691}...a pomohu vašemu novináøskému|krouku, jak jen budu moci-
{11691}{11717}Ani nás nehne.
{11731}{11824}Nikdy to neskonèí, kdy se pokadé|necháme zlákat pánovım soucitem k ostatním.
{11824}{11864}A navíc to je nuda.
{11864}{11896}Odcházíme, Tamaki.
{11912}{11965}Jdeme na poradu do klubu.
{11965}{11990}Budeš hlavní téma.
{11990}{12019}Stùjte!
{12064}{12119}Co nemáte ádné city?
{12119}{12186}Zøíte tyto nešastníky,|jejich klub se rozpadá,
{12186}{12239}...a nesoucítíte s nimi?!
{12254}{12293}Tohle je rozvrat rodiny!
{12293}{12338}{C:$2020C7}[Naprosto nepochopitelné]
{12348}{12385}Toto jsou pøesedovy rozkazy!
{12393}{12439}Námitky se nepøijímají!
{12495}{12530}{C:$FFFF80}TOTÁLNÌ!!! |Odmítáme!
{12668}{12733}{C:$2020C7}[Tøetí Hudební Uèebna]
{12845}{12888}Je fakt naštvanej.
{12888}{12931}Dokonce se ani nepøevlík.
{12939}{13023}Tomu se øíká: "Jsem-blízko-vás-ale-ignoruji-vás",
{13023}{13060}... je to dìtskı zpùsob trucování.
{13060}{13131}Protoe Tamík je hodnì osamìlı, správnì?
{13141}{13198}Aktivity klubu jsou o utváøení rodin...
{13198}{13254}Proto je rozpad klubu rozpadem rodiny...
{13254}{13311}Proto je mi jich líto...
{13335}{13430}Vánì nám to zpùsobí nìjaké trable,|kdy jim pomùeme?
{13430}{13443}Co?
{13443}{13490}Take ty jsi na jeho stranì?
{13490}{13539}Ne úplnì.
{13539}{13638}Jene døív nebo pozdìji na nás|zaène koukat tìma jeho psíma oèima,
{13638}{13724}..a nakonec z toho budeme mít tak špatnı pocit,|e nám nezbude ne souhlasit.
{13724}{13776}Docela rychle se uèíš...
{13802}{13820}A navíc,
{13820}{13893}...není tohle nìco,|na èem byste normálnì spolupracovali?
{13893}{13915}Ale kdepak.
{13915}{13961}Tentokrát je to nuda.
{14002}{14036}A co vy, Honey?
{14036}{14138}No, musím sníst tyhle dortíky, víš?
{14138}{14153}Tak.
{14350}{14374}To je ten pohled!
{14472}{14502}Psí oèi...
{14688}{14763}Jedinì za našich podmínek.
{14763}{14853}Budou muset souhlasit s plánem,|kterı pro jejich speciální èíslo vymyslíme.
{14853}{14903}Interview jeden na jednoho budou samozøejmì zakázána.
{14903}{14959}Jakékoliv zapojení našich klientù je rovnì zakázáno,|pøineslo by jim to jen potíe.
{14991}{15019}Všichni souhlasí?
{15019}{15078}No, kdy souhlasí Kyouya...
{15078}{15099}...pak ano.
{15120}{15173}Já taky, kdy je Kyouya pro.
{15173}{15189}Tak.
{15198}{15252}Pohleïte na moc šedé eminence.
{15295}{15320}Samozøejmì!
{15320}{15401}Souhlasíme s vašimi podmínkami,|kdy nás o sobì necháte napsat.
{15401}{15472}Take mùete pøijít zítra a udìlat s námi rozhovor.
{15496}{15550}A jak se má tvé zranìní?
{15560}{15630}Ále, to nic není, vánì.
{15644}{15746}Vlastnì jsem za nìj trochu vdìènı,|protoe vás k nám pøivedlo.
{15756}{15810}Hluboce se omlouváme.
{15818}{15853}{C:$3399ff}Popiska: Lékárnièka.
{15853}{15930}Abychom vyjádøili naší soustrast,|pøijmìte prosím tyto medikamenty.
{15957}{16039}Toto je krabièka první pomoci|z továrny patøící naší rodinì.
{16049}{16080}To jste opravdu nemusel.
{16094}{16130}Tak tedy, omluvte mì, prosím.
{16166}{16202}Ach, Ootori.
{16223}{16352}Ty pocházíš z rodiny vyrábìjící zdravotnická zaøízení,|Ootori group, e ano?
{16352}{16423}Naším hlavním zájmem je hlavnì|menedment ve zdravotnictví.
{16423}{16494}Jsem rád, e jsme se mohli poznat.
{16494}{16609}Mùj otec je øeditelem|Vydavatelství a nakladatelství Komatsuzawa.
{16609}{16680}Ano, toho jsem si vìdom.
{16680}{16801}Je tvoje pøedsednictví v novináøském krouku|pøíprava na následnictví tvého otce?
{16824}{16896}Víš, mám mladšího bratra...
{16896}{16970}...a on má vánì talent.
{16970}{17109}Mùj otec plánuje, e mu pøenechá øízení vydavatelství,|a odejde do dùchodu,
{17109}{17209}...a mì z toho úplnì vynechává.
{17249}{17387}Ale kdy budu celé ty tøi roky dìlat pøedsedu|novináøského krouku tady na Ouranu,
{17387}{17480}...moná by mohl zváit moje nástupnictví.
{17507}{17533}Chápeš?
{17553}{17636}A to stojí, co to stojí,|tenhle klub se nesmí rozpadnout.
{17636}{17669}Omluv mì.
{17777}{17860}Pane pøedsedo, to se chcete Kyouyovi vetøít do pøíznì?
{17860}{17882}Pøesnì tak.
{17882}{17939}Suou Tamaki je mùj jedinı nepøítel.
{17956}{18020}Na zaèátku jsem chtìl pouít moc školních novin...
{18020}{18097}...abych se tu stal populární.
{18118}{18246}Jene pak Suou Tamaki zaloit ten jeho hostitelskı klub,|a ten na sebe stáhl veškerou pozornost.
{18266}{18329}Slyšel jsem, e ještì ne Suou vstoupil na školu,
{18329}{18424}...tak vaše noviny stejnì nebyly populární.
{18424}{18451}Zmlkni!!!
{18466}{18507}Kdybych poádal matku,
{18507}{18616}..mohu okamitì zrušit všechny smlouvy,|které máme s vašimi rodinami.
{18625}{18675}Zjistím pravdu.
{18675}{18788}Jejich zvláštní status, plynoucí z jejich nepøíslušnosti|ke sportovním nebo kulturním kroukùm a nevlastnìní rádce...
{18788}{18856}Klubové aktivity, sestávající z falešnıch romancí a švindlù...
{18856}{18955}Taková arogance musí bıt Suouovou manifestací síly.
{18955}{19038}Musí pouívat moc svıch rodièù,|aby byli jeho spoleèníci poslušní...
{19038}{19089}...a dìlali s dìvèaty cokoliv si pøeje.
{19089}{19213}Kadı z nich, poèínaje Kyouyou,|by mìl bıt mım poskokem!
{19213}{19320}Suou Tamaki... musí bıt opravdu mazanı.
{19320}{19392} I kdy se normálnì chová jako velmi milá osoba,
{19392}{19446}...musí v nìm bıt nìco ïábelského!
{19446}{19486}Vyrobím skandál...
{19486}{19527}...a ukáu mu, kdo je tady šéf.
{19691}{19752}Figura Daruma... kouká!
{19752}{19809}Tahle hra je to samé jako 1-2-3-ani hnout!
{19809}{19893}Fi-gu-ra-Da-ru-my... kouká!
{19910}{19962}Figura Darumy... kouká!
{20008}{20035}Figura Darumy kouká!
{20057}{20093}FiguraDarumykouká!
{20105}{20151}Fi- ...guraDarumykouká!
{20151}{20191}Hikaru, Kaoru, vy jste se pohli!
{20191}{20243}Pane pøedsedo, na co to vlastnì koukáme?
{20243}{20270}Ne, nepohli jsme se!
{20270}{20309}To je nìjaká nová sekta?
{20309}{20358}Jak to mám vìdìt?
{20375}{20420}ádnı div, e jste šokováni.
{20420}{20497}Tohle je stará hra prostého lidu.
{20497}{20540}A je jich ještì mnohem víc...
{20550}{20588}Nevyadují ádné peníze...
{20588}{20665}Jediné, co potøebuješ, jsi ty sám.|A nìkdo další.
{20665}{20734}A co to má spoleèného s naším rozhovorem?
{20745}{20776}Smysl pro pøátelství!
{20797}{20866}Abychom smazali negativní imid novinového krouku...
{20866}{20926}...a opìt chytili ètenáøe za srdce,
{20926}{20968}...jest pøátelství naprosto nezbytné!
{20968}{21017}Pøesnì jak jsem èekal.
{21017}{21106}"Krásní chlapci z Hostitelského|klubu hrají prosté hry."
{21106}{21175}Toto, skombinované s osvìující|scenérií raného léta,
{21175}{21236}...bude naprosto ideální k|ozdobení celé titulní strany.
{21236}{21280}A navíc, prostı lid...
{21280}{21342}...je také velmi šastnı, kdy si|mùe zavzpomínat na záitky z mládí.
{21342}{21380}Tohle je ten plán, kterı máme!
{21412}{21432}Skvìlé.
{21432}{21463}Asi kouká na mì.
{21463}{21528}{C:$2020C7}[Pøedstavitel obyèejného lidu] |Mám se chovat extrémnì šastnì?
{21538}{21616}- Ach! Kyouyo, ty ses trochu pohnul, e ano? | - Pane pøedsedo, nerozumìl jsem ani slovu.
{21616}{21679}- Pojï sem a zahákni se se mnou za malíèek.|- Mùe on bıt totální idiot?
{21679}{21729}Mìl by sis nechat vyšetøit oèi.|Musíme bıt stále ve støehu.
{21729}{21771}- Pøestaò koneènì odmlouvat a pojï sem.|- To je jeho strategie.
{21771}{21782}Dobrá, dobrá.
{21871}{21928}Take obyèejnı plebejec?
{21928}{21987}Mùeme s tím pøestat?
{21996}{22041}Pan Fujioka, pøedpokládám...
{22063}{22120}Mohu vám poloit nìkolik otázek?
{22135}{22152}Jistì.
{22168}{22209}Proè jste vstoupil do tohoto klubu?
{22239}{22292}No, tak trochu z neopatrnosti.
{22292}{22358}Vy jste ten speciální stipendista, e ano?
{22358}{22383}Ano, a?
{22383}{22468}Take jinımi slovy, skuteènost,|e jste èlenem klubu,
{22468}{22555}...tedy znamená, e jste|ukázkou moci rodiny Suou.
{22567}{22577}Co?
{22587}{22667}Mùete nás seznámit s jeho|pravou tváøí mimo jevištì?
{22667}{22733}Myslím, e tohle by vás mohlo zachránit.
{22745}{22803}On nemá ádnou "pravou tváø mimo jevištì".
{22834}{22861}Tak tedy co?
{22861}{22950}Opravdu si myslíš, e tohle|støedoškoláky jako jsou oni baví?
{23017}{23052}Co je na tom divného?
{23052}{23087}To nemùe bıt pravda!
{23087}{23108}Sek!
{23138}{23197}Hej, tam nemáte sekat!
{23218}{23253}A teï budeme hrát "kankeri".
{23255}{23309}Kankeri - upravená verze hry na schovávanou, kde ten, kterı poèítá,|musí pøinést zpìt odkopnutou plechovku a pak zaèít poèítat.|Kyouya bude poèítat.
{23309}{23318}Dobøe.
{23337}{23361}Tak jo...
{23361}{23462}Hvìzdnı kop!!
{23571}{23658}Neskoèím znovu na ten samı trik...
{23696}{23721}Pane pøedsedo!
{23721}{23739}Haruhi, tudy!
{23739}{23754}Pobì!
{23845}{23914}Vánì si nemyslím, e by tahle|osoba mìla nìjakou skrytou stránku,
{23914}{24026}...ale samozøejmì, naprosto netuším,|co je tamakiho rodina zaè.
{24120}{24167}Jedna... | Zatracenì!
{24167}{24184}Dva...
{24184}{24241}Mám tìhle blbovin dost.
{24241}{24273}Tøi... Ètyøi...
{24273}{24313}Tamaki, neodpustitelné...
{24301}{24316}Pìt...
{24316}{24346}Šest...
{24422}{24450}Ztratili jsme se?
{24483}{24518}Ztratili jsme se, e jo?
{24518}{24549}Hej, Haruhi!
{24549}{24596}Tady je bájeèná schovka!
{24623}{24658}Ztratili jsme se.
{24688}{24733}Vlastnì jsme v úzkıch.
{24761}{24825}Koneckoncù, Kyouya poèítá.
{24859}{24892}Dìláš si ze mì srandu?
{24965}{25069}Nikdy jsem si nemyslela,|e to budu hrát i na støední.
{25079}{25111}Tebe to nebaví?
{25130}{25233}No, na základce jsme to hráli hodnì.
{25233}{25260}Hmm...
{25260}{25278}Rozumím.
{25325}{25432}Já... nikdy jsem nemìl kamarády v mém vìku.
{25448}{25499}Moje máma mìla hodnì chatrné zdraví.
{25509}{25598}Jako dítì jsem se o ní tolik bál,|e jsem ani nechtìl chodit ven.
{25598}{25647}Abych jí rozveselil,
{25647}{25704}...hrával jsem jí na piáno.
{25717}{25790}Take mì tyhle hry s vámi baví.
{25872}{25905}Je to fakt skvìlı.
{25973}{26002}Mìli bychom si to zopáknout.
{26020}{26040}Jasnì.
{26092}{26121}Jdem napsat ten èlánek.
{26132}{26158}Ale pane pøedsedo!
{26158}{26266}Napsat ty Suouovy klepy bez dùkazù|by mohlo bıt nebezpeèné!
{26266}{26292}Nebojte.
{26292}{26340}Moná teï nemám ádné dùkazy,
{26340}{26394}...ale prostì o nìm musím napsat èlánek.
{26394}{26430}Kdybych to myslel vánì...
{26430}{26553}...mohl bych napsat destíky èlánkù,|které by tuto školu pøevrátily naruby!
{26553}{26609}V kadém pøípadì musím ukázat jeho druhou stránku.
{26664}{26686}Hmm...
{26694}{26730}Take nakonec to bylo nìco takového.
{26741}{26760}Vy dva...
{26760}{26821}No, bylo to tak trochu zøejmé.
{26821}{26885}Jsem si jistı, e to neèekal jen Tamaki.
{26885}{26954}Jak se jedná o nìj,|tak je trošku pomalejší.
{26954}{26994}Øeknu to takhle:
{26994}{27059}...jestli se o nìm jen trošku špatnì zmíníte,|tak budete mít co dìlat s námi.
{27059}{27081}Jste pøipraveni...
{27081}{27150}...postavit se Hitachiinùm a rodinám ostatních|èlenù klubu jako svım nepøátelùm?
{27171}{27283}Take Suou vyuívá moc svıch rodièù,|aby vydával takovéhle rozkazy?
{27283}{27304}Špatnì.
{27327}{27382}Tamík by to nikdy neudìlal.
{27409}{27427}Víš,
{27427}{27505}...my všichni ho máme rádi.
{27514}{27586}I kdy je beznadìjnı pitomec.
{27616}{27638}Kyouo!
{27662}{27698}Zalome spolu ten klub!
{27729}{27780}Ahoj, Haninozuko.
{27813}{27852}Vím, e je to neèekané,
{27852}{27904}...ale nechtìl bys se mnou zaloit klub?
{27926}{27950}Morinozuko!
{28040}{28083}Vy dva vypadáte celkem odvázanì.
{28110}{28153}Jestli jste, tak co vy na to?
{28153}{28196}Pøipojte se k mému klubu!
{28229}{28250}A?
{28250}{28275}Co se chystáš udìlat?
{28275}{28322}Okamitì s tím pøestaò.
{28350}{28371}Krucinál!
{28385}{28427}U to není jen o Suouovi!
{28437}{28485}Znièím vás všechny!
{28499}{28536}Buï mım hostem.
{28564}{28574}Ale...
{28674}{28734}Co asi udìláme s tímhle diskem,
{28734}{28788}...kterı to všechno nahrával...
{28788}{28822}...u od vèerejška?
{28863}{28892}Pane pøedsedo!
{28892}{28934}Jsme v koncích!
{29025}{29108}Jestli mám øíci nìco v tvém stylu,|tak to bude tohle:
{29108}{29198}S podíly, které vlastní naše a Hitachiinova rodina,
{29198}{29294}...mùeme bez problémù zmìnit|prezidenta ve vydavatelství tvého otce,
{29294}{29330}...tak na to mysli.
{29351}{29429}Jene my nejsme jako ty.
{29500}{29573}To, o co se snaíme,|je zásadnì jiné.
{29665}{29692}Máme vás!
{29755}{29790}Co se stalo s novináøskım kroukem?
{29790}{29859}Zrušili plánovanı rozhovor|kvùli nìèemu naléhavìjšímu.
{29859}{29919}Øíkali, e u budou psát èistou pravdu.
{29919}{29978}Take ten jejich klub nerozpustí.
{29978}{29996}Aha.
{29996}{30027}To bude fajn.
{30027}{30097}Rychle do klubovny, a sníme nìjaké dortíky!
{30105}{30116}Tak.
{30129}{30149}Tak.
{30175}{30213}Dortík, dortík!
{30238}{30279}Och ano, Kyouyo.
{30279}{30295}Hmm?
{30295}{30364}Je rodina Suou tak mocná?
{30364}{30472}No, mají hluboké vazby ve finanèním svìtì.
{30472}{30584}Napøíklad: slyšelas o hotelu Roi Grand,|nebo o divadle Outo?
{30597}{30670}A nebo, jak urèitì víš, ve školní správì...
{30683}{30715}Jaké školy?
{30864}{30897}Téhle, Ouranu.
{30929}{30945}Ech?
{30945}{31045}Asi by bylo lepší, kdybys koneènì|vìdìla jméno svého øeditele.
{31060}{31133}Vlastnì, kdy o tom zapøemıšlíš,
{31133}{31225}...mohlas na tuhle školu nastoupit|jen díky finanèní podpoøe tamakiho rodiny.
{31241}{31271}Buï mu za to vdìèná.
{31298}{31319}Haruhi!
{31434}{31494}Budeme tì muset popohnat, kdy si nepospíšíš.
{31507}{31552}Zase se ztratíš.
{31552}{31609}{C:$2020C7}[Øeditelùv syn]
{31777}{31791}Ech?!
{31812}{31899}Pøeklad: Charlie|Korekce: Taylor|pùvodní titulky: luqas123
{31991}{32066}Bìet pìt tisíc mil,
{32074}{32129}Bìet bez dechu.
{32141}{32212}Sto litrù adrenalinu
{32212}{32304}Mì plní energií.
{32322}{32398}Jít tahle daleko je fajn, e?
{32398}{32463}Jak daleko bude OK?
{32463}{32542}Stromy, které zdobí mìsto
{32542}{32630}Stále mìní svùj vzhled.
{32650}{32723}Úplnì jiná bílá
{32723}{32768}Stále stejná slabost
{32779}{32909}Chci vìøit sám v sebe tady a teï.
{32909}{33000}Zdvíhám vysoko levou i pravou ruku
{33000}{33072}Prorazit temnotu a vpøed!
{33082}{33139}Nic není falešné
{33167}{33225}Moje rozhodnost slábne!
{33249}{33327}Start! Právì od teï...
{33327}{33413}Mùj svìt se musí otevøít!
{33462}{33484}Mùj boe!
{33484}{33523}Haruhi zmizela?!
{33523}{33590}Jenom chci o prázdninách|pracovat v Karuizawì!
{33590}{33639}Nech takovou milou osobu jako mì tì potkat!
{33639}{33695}V pøíštím díle "Osvìující bitva v Karuizawì".
{33695}{33784}Ouranskı hostitelskı klub na vás bude,|jako obvykle, èekat i pøíští tıden.
