{1}{1}23.976
{161}{209}{C:$3399ff}Kiss Kiss Fall in love
{340}{433}{C:$3399ff}I notice that
{433}{484}{C:$3399ff}I'm always around you
{484}{560}{C:$3399ff}but is it hating? Liking?
{560}{613}{C:$3399ff}Or just paranoia?
{613}{706}{C:$3399ff}When I can see
{706}{761}{C:$3399ff}my feelings clearly,
{761}{834}{C:$3399ff}lady or host,
{834}{893}{C:$3399ff}it doesn't matter.
{905}{976}{C:$3399ff}The reason for which
{976}{1044}{C:$3399ff}people fall in love
{1044}{1129}{C:$3399ff}is different for everyone, but-
{1129}{1176}{C:$3399ff}MAYBE YOU'RE MY LOVE
{1176}{1241}{C:$3399ff}I want to meet you now
{1241}{1305}{C:$3399ff}and give you, a sweet person,
{1305}{1363}{C:$3399ff}a cherry blossom kiss.
{1363}{1420}{C:$3399ff}If your heart moves from it,
{1420}{1456}{C:$3399ff}let's have a romantic love!
{1456}{1522}{C:$3399ff}More important than the future
{1522}{1588}{C:$3399ff}is the present.
{1588}{1701}{C:$3399ff}The delightful spring love is
{1701}{1816}{C:$3399ff}a blossom virgin's aesthetic.
{1893}{1959}{C:$3399ff}MAYBE YOU'RE MY LOVE
{2388}{2408}Hikaru...
{2418}{2458}Zvoní ti mobil...
{2490}{2512}Hikaru!
{2588}{2625}Zvedni to ty, Kaoru.
{2662}{2681}Ne.
{2681}{2736}Tohle je zvonìní našeho pána.
{2748}{2780}Zatracenì!
{2780}{2909}Proè nás musí budit tenhle ošklivej tón|teï o prázdninách?
{2919}{2969}Proè vstává tak brzo?
{3042}{3065}Haló?
{3065}{3095}Moje dcerka...
{3095}{3130}Moje dcerka zmizela!!!
{3130}{3166}Nemùu se jí dovolat!!!
{3166}{3198}Museli jí unést!!!
{3198}{3226}Zavolejte policii!!!
{3226}{3300}Zmobilizujte Obranné síly, kdy to bude potøeba!!!
{3300}{3351}Uklidni se, pane.
{3362}{3383}Co?
{3402}{3415}Huh?
{3429}{3469}Haruhi zmizela?
{3552}{3609}Coe? Harunka zmizela?
{3642}{3701}Vyloupili jí uprostøed noci a utekli?
{3724}{3746}Pøesnì tak!
{3746}{3788}U od prvního dne prázdnin...
{3786}{3847}...se jí kadı den snaím dovolat!
{3847}{3910}Nemùu se ani dovolat jejímu tátovi do práce-
{3910}{3945}{C:$2020C7}[telefonní konference Hostitelského Klubu]|Urèitì to je proto, e nedokázali platit nájem...
{3945}{3996}...a tak je prodali do otroctví!
{3996}{4041}A jestli ne, tak museli uprchnout uprostøed noci!
{4041}{4081}Ne, Harunko...
{4094}{4153}[IDI-   -OTI]|Mùj pane, moc do toho køièíš.
{4153}{4205}Zavolej jí na mobil.
{4221}{4241}Mobil?
{4250}{4290}Jak by Haruhi nìco takového mohla mít?!
{4411}{4437}U vím.
{4449}{4549}Mezi obyèejnımi lidmi existuje zvláštní skupina|nazıvaná "pùlnoèní chodci"-
{4549}{4621}Promiò, e ti kazím tvojí paranoiu,
{4621}{4675}...ale Haruhi je právì teï v Karuizawì.
{4697}{4759}Karuizawa je populární letovisko v prefektuøe Nagano,|bohatí lidé tam mají svoje letní sídla. | Karuizawa?
{4759}{4943}Haruhi... zbankrotovala... utekla v noci... |unesena... a je v Karuizawì?
{4943}{4969}Okamitì se uklidni.
{5028}{5066}Dìkujeme za vaší návštìvu!
{5313}{5336}Vítejte!
{5372}{5415}Bìhem prázdnin budu...
{5415}{5483}...pracovat jako brigádník v Karuizawì.
{5602}{5662}{C:$FF00FF}"Osvìující bitva v Karuizawì".
{5694}{5747}Take Haruhi je v Karuizawì.
{5747}{5765}Aha.
{5777}{5802}Dobré ráno.
{5822}{5841}Dobré.
{5994}{6050}Vaše snídanì je pøipravena.
{6050}{6068}Dobrá.
{6068}{6085}Hned tam budeme.
{6110}{6134}Prosím omluvte nás.
{6212}{6311}Kdy tu není naše hraèka, tak je tu fakt nuda...
{6610}{6704}Trošku mì trápí, e jsem o tomhle nikomu neøekla,
{6704}{6815}...ale jsem si jistá, e nemají|dost èasu, aby mì tu rušili.
{6829}{6865}Je to tu pøekrásné.
{6865}{6905}A vzduch je tak svìí.
{6905}{6998}Tady na horách se budu moci|poøádnì pøipravit do školy.
{6998}{7039}Letošní prázdniny...
{7114}{7143}Haruhi!!!
{7143}{7174}Jsi v poøádku?!
{7174}{7225}Taka je tady!!!
{7266}{7337}...budou ty nejhorší v mém ivotì.
{7378}{7403}{C:$2020C7}[Penzion Misuzu]
{7403}{7440}Jéminkote!
{7440}{7485}Jak rozkošná skupina nádhernıch chlapcù!
{7485}{7520}{C:$2020C7}[Majitelka: Sonoda Misuzu (42 let)]|Jaká milá spoleènost krásnıch chlapcù!
{7520}{7578}{C:$2020C7}[Jeho pravé jméno: Sonoda Isao] |Vy jste všichni Haruhini známí?
{7578}{7616}Natøásající se transka...
{7643}{7699}Mùete mi øíkat Misuzu-cchi, ano?|Pozn: suffix "cchi" - silná zdrobnìlina
{7719}{7800}Pracovala s Rankou v baru.
{7810}{7847}Jak to všechno víš?
{7855}{7877}Ach, opravdu.
{7877}{7951}Otevøela jsem to tu pøed dvìma lety.
{7951}{7993}Byl to mùj sen, víte?
{7993}{8050}Provozovat takovıhle roztomilı penzionek!
{8050}{8120}Ale... proè tu Harunka pracuje?
{8120}{8192}Kdy se Ranka dala na umìleckou dráhu,
{8192}{8247}...bála se, e Haruhi zùstane sama,
{8247}{8291}...take se tu o ní starali.
{8291}{8354}Take, jak to všechno víš?!
{8354}{8383}Jo, pøesnì...
{8383}{8437}Och, neøíkejte "starali".
{8437}{8510}Ještì neprosperuji tak dobøe,|abych mohla najímat personál,
{8510}{8568}...take mi tu Haruhi pomáhá.
{8568}{8620}Je to pilná vèelièka,
{8620}{8684}...a se stydím, e jí tak málo platím.
{8684}{8762}Ach, e jí tahle zástìrka sluší?
{8762}{8792}Sama jsem ji ušila.
{8792}{8848}Vánì se ti povedla, Misuzu-cchi!
{8987}{9025}Práce na polovièní úvazek, co?
{9025}{9102}Tak proto's s námi nechtìla jet na Bali.
{9102}{9178}Taky jsme se ptali, jestli bys nejela do Švıcarska.
{9178}{9190}Ano.
{9206}{9255}Víte, já nemám pas.
{9255}{9370}A proto jsem navrhl, abychom pouili|jedno z mıch letovisek kvùli niší cenì.
{9405}{9506}Proè jste chtìli Haruhi všichni nìkam vylákat?
{9521}{9579}Take je v poøádku, kdy se všichni bavíte?
{9579}{9621}To nemáte ádnı smysl pro solidaritu?
{9641}{9682}Já, jakoto pøedseda klubu,
{9682}{9794}...se kadı den døu, abych vymyslel nìco,|u èeho bychom se mohli bavit všichni spoleènì...
{9794}{9832}Ty's vypnula svùj mobil, e jo?
{9832}{9853}To nedìlej!
{9853}{9888}Jene je otravnı.
{9899}{9939}{C:$2020C7}[Mobil?]
{9961}{10018}Ty... máš... mobil?
{10018}{10032}Jasnì.
{10032}{10093}Dali jsme jí jeden z našich.|
{10093}{10156}A mìl bych dodat, e jsou jen pro kámoše.
{10155}{10201}Mùj pane, ty jsi starší, take...
{10201}{10257}{C:$FFFF80}Na pozadí: Kámoši |Kámoši?!
{10326}{10375}To je tak super...
{10400}{10483}Take já jsem ve tvojí škatulce taka-kamarád-
{10483}{10542}Taková neexistuje.
{10542}{10602}Ale stejnì, mohli byste jít všichni domù?
{10613}{10698}Zase se všichni potkáme,|a zaène novı semestr.
{10698}{10776}Kadı má právo strávit prázdniny tak,|jak by si pøál, no ne?
{10776}{10821}Školní øád, paragraf devìt.
{10821}{10903}- "Studenti mají zakázáno pracovat jako brigádníci." | - Ech? Umm...
{10903}{10938}Vánì?
{10938}{10974}Vìdìls to?
{10974}{11059}Tahle osoba chodí na brigádu bez svolení školy.
{11059}{11118}Fíha, ta má ale kurá.
{11118}{11217}Pøijít sem, aby unikla pøed horkem,|byl vánì dobrı nápad.
{11217}{11274}Nás u to doma taky nudí.
{11274}{11367}Pøesnì tak, kadı má právo strávit|prázniny tak, jak chce...
{11375}{11456}Take, nemáš ádné právo nám bránit.
{11469}{11572}Zùstaneme tady v penzionu jako zvláštní hosté.
{11582}{11719}N-Nééééé!!
{11996}{12067}Dobré ráno, ty ospalèe.
{12081}{12140}Tady je tvá, mnou vlastnoruènì pøipravená, snídanì.
{12159}{12199}Ach, dobré ráno.
{12199}{12221}Pojï sem.
{12238}{12267}Nasnídáme se spolu.
{12294}{12314}Já nemohu.
{12314}{12435}Ne, ty jsi zde host,|a já zamìstnanec.
{12435}{12519}S tím si nedìlej starosti,|kdy jsme sami.
{12592}{12675}Jediné, co musíš, je zùstat u mì.
{12689}{12707}Senpai...
{12755}{12814}{C:$2020C7}[Tamakiho bujná pøedstavivost v Karuizawì] |Bájeèné!
{12814}{12861}Umm... Senpai?
{12894}{12928}Odpuste.
{12928}{12984}Chtìla bych, abyste tu všichni zùstali,
{12984}{13046}...ale u zùstaj jen jeden pokoj pro hosty.
{13046}{13102}Jen... jeden pokoj?
{13119}{13143}Dobrá.
{13143}{13215}Take já, jakoto pøedseda klubu,|ho musím reprezentovat a tak-
{13215}{13251}Tamíku, na tohle ti neskoèíme.
{13251}{13318}Take je v poøádku, kdy se budeš bavit?
{13318}{13421}- To nemáš ádnı smysl pro solidaritu?|- Tak si tak øíkám, kdopak si to tu pøed chvílí stìoval.
{13511}{13559}To jsem takovı bídák?
{13559}{13610}Osoba, které staèí, kdy je spokojená ona?
{13610}{13640}Hej, hej, mùj pane.
{13640}{13698}Nechtìl by ses zúèastnit jedné zábavné hry?
{13698}{13803}Jmenuje se: |"Soutì o pokoj v letním penzionu v Karuizawì".
{13824}{13956}Budeme jeden den pracovat tady v penzionu,|kterı tak zoufale potøebuje pracovníky...
{13956}{14055}...a kdo udìlá nejvìtší dojem na paní Mitsuzu,|bude moci zùstat.
{14055}{14079}Interesantní!
{14079}{14112}Vıbornì, vıbornì!
{14112}{14154}Tak rychle do toho!
{14154}{14256}{C:$2020C7}[Øeditelsı mód] | Ano, kdy to milé dítko,|které já vyberu, zùstane,
{14256}{14309}...vzroste tím i popularita mého penzionu.
{14309}{14327}Bezpochyby!
{14327}{14372}Jsme pøipraveni zaèít!
{14390}{14448}Dejte do toho všechno!
{14448}{14510}Dokud se nerozhodnu,|nebudu vás šetøit.
{14510}{14532}{C:$2020C7}Prázdniny
{14545}{14607}{C:$2020C7}Prázdniny||V tahu Prázdniny
{14607}{14636}Fakt zábava...
{14636}{14685}{C:$2020C7}[Proèe...]
{14864}{14980}Tohle je poprvé, co drím v ruce kladivo.
{14997}{15051}Jojo, práce je tìká.
{15051}{15072}Hej, ty tam!
{15072}{15105}ádné kòourání.
{15105}{15142}Mínus tøi body.
{15203}{15217}Auva...
{15240}{15261}To bolí...
{15261}{15345}Vypadáš alostnì, další mínus-
{15397}{15447}Sladkı kukuè ti nepomùe.
{15612}{15632}Ahoj...
{15632}{15668}...a vítejte!
{15712}{15800}My... máme tu zarezervovanı pokoj.
{15800}{15854}Ach, ano, ano, èekali jsme na vás!
{15854}{15892}A uijte si zdejší pobyt, ano?
{15892}{15960}Teï vás doprovodíme do vašeho pokoje.
{16002}{16044}Trochu arogantní v jejich postoji,
{16044}{16079}...ale nemùete je nemít rádi.
{16079}{16137}Osvìující hodnocení - plus pìt bodù.|Ach, Takashi.
{16137}{16185}Ten stùl  se trochu kıve.
{16185}{16231}Mohl bys ho vzadu spravit?
{16285}{16308}Rozumím.
{16379}{16420}ádné zbyteèné øeèi!
{16420}{16467}Osvìující hodnocení, plus pìt bodù!
{16467}{16524}Ehm, co je to to osvìující hodnocení?
{16536}{16655}Haruhinko, copak chtìjí hosté tady v Karuizawì?
{16668}{16730}Umm, chládek... špatnì?
{16745}{16783}Nejen to.
{16797}{16866}Osvìující vzduch,|kterı ve mìstì nemají,
{16866}{16892}...osvìující vıhled,
{16892}{16965}...a koneènì, a nikoliv na posledním místì, pohled na osvìující mladé mue!
{16989}{17091}Všichni jezdí do Karuizawy za tímto osvìujícím pocitem!
{17091}{17272}Tohle je soutì o to, kterı z nich dokáe|tento osvìující pocit pøenést na dívky, které sem pøijídìjí!
{17282}{17343}Fakt si to uívá...
{17360}{17443}A... hroznì mi nìkoho pøipomíná...
{17483}{17574}Ale celá tahle situace mi pøipomíná klub...
{17689}{17754}Kyouyo, ty se neúèastníš hry?
{17768}{17782}Ano,
{17791}{17883}...i kdybych vyhrál, není dùvod, abych tu zùstal sám.
{17883}{17938}Jen se tak koukám,
{17938}{17992}...a potom se pøesunu do našeho letního domu.
{17992}{18016}Letní dùm?
{18016}{18056}Tvojí rodiny?
{18056}{18074}Pøesnì tak.
{18089}{18140}Kadı tu má jeden.
{18210}{18245}Máte kde zùstat!
{18245}{18281}Tak mazejte!
{18297}{18350}A co se tıèe téhle osvìující soutìe...
{18350}{18396}Kdo si myslíš, e vyhraje, Haruhi?
{18396}{18422}Co si vsadit?
{18422}{18445}Ne, díky.
{18445}{18471}Nemám ani ponìtí.
{18471}{18498}Vánì?
{18498}{18558}Je to úplnì jasné, kdy se nad tím zamyslíš.
{18568}{18617}Za prvé, Honey.
{18617}{18687}Na pohled je spíš roztomilı ne osvìující.
{18687}{18714}Take vypadává.
{18756}{18817}Tamaki je osvìující, kdy nic nedìlá,
{18817}{18879}..ale pro tuhle soutì je pøíliš zapálenı.
{18879}{18910}Take vypadá trochu uštvanì.
{18960}{19025}Na první pohled se zdá, e vyhrají Hikaru a Kaoru...
{19108}{19169}...ale je tu ještì nìkdo...
{19276}{19324}{C:$2020C7}[Z nìjakého dùvodu štípá døíví...]
{19324}{19345}Je nádhernı...
{19345}{19394}{C:$2020C7}[Ale vypadá velmi osvìujícnì!] |Tak osvìující!
{19394}{19434}Plus dvacet bodù!
{19434}{19476}Take Mori?
{19488}{19558}Ale kdy Honey vypadne ze soutìe,
{19558}{19605}...Mori pravdìpodobnì odstoupí také.
{19605}{19678}Úèastní se toho jen s ním.
{19678}{19707}Take nakonec...
{19720}{19766}...vyhrajem my.
{19786}{19853}Ach, teï jsem si uvìdomila,
{19853}{19924}...ten pokoj je jen pro jednu osobu,
{19924}{19963}...take tu nemùete zùstat oba.
{19963}{19987}Ále, bez obav.
{19987}{20045}Pøineseme si sem postel.
{20045}{20109}A kdyby to nešlo,|tak prostì budem spát spolu.
{20136}{20199}Vy jste vánì nerozluèná dvojka.
{20208}{20231}No jasnì.
{20250}{20300}Narodili jsme se spolu,
{20300}{20349}...a nemáme ádné jiné kamarády.
{20364}{20479}Ještì pøed pár lety jsme si mysleli,|e jsou všichni ostatní idioti.
{20479}{20508}Aha...
{20508}{20522}Ale...
{20563}{20623}...e jsi to ty, tak se mùeš pøidat, Haruhi.
{20623}{20659}Budeme spát spolu, všichni tøi.
{20659}{20698}Ne, dík.
{20718}{20771}Soutì ještì neskonèila.
{20782}{20858}Mám víc zpùsobù,|jak jí udìlat zajímavìjší.
{20858}{20962}On je tak ïábelskı,|a ho to dìlá osvìujícím.
{20962}{20982}Co to?
{20982}{21037}Kyouyo, ty jdeš k našemu pánovi?
{21037}{21103}Ale i tak, my nehodláme prohrát.
{21322}{21388}Šéfová, oprava plotu skonèena.
{21388}{21449}{C:$2020C7}[Osvìující zpráva]
{21449}{21479}{C:$2020C7}[Opraveno velmi grotesknì]
{21479}{21530}Tvoje práce není osvìující,
{21530}{21571}...mínus tøi body.
{21626}{21702}Všechno své snaení upnul k bytí osvìujícím...
{21702}{21755}...a práci odvedl pìknì mizernì.
{21755}{21791}To je blbej, nebo co?
{21791}{21849}Nikdy v ivotì nepracoval.
{21903}{21934}Ta voda je studená!
{21967}{21994}Promiò, promiò.
{21994}{22052}Podívej, melouny u jsou vychlazené.
{22052}{22096}Pùjdem je sníst s našimi hosty!
{22096}{22143}Kya-! Jak osvìující!
{22194}{22219}Ale ne...
{22219}{22279}Tímhle tempem to s tìma dvìma prohraju...
{22294}{22339}Musím vyhrát za kadou cenu!
{22339}{22393}Vyhrát a prohloubit mé pouto s Haruhi,
{22403}{22426}...a...
{22437}{22536}....dosta se do... Haruhi oficiálnì|uznávané kamarádské skupiny!
{22536}{22601}I pøedtím jsem øíkal, e jsou tvé cíle pøíliš nízké,
{22601}{22656}...take bys mohl pøestat bıt tak alostnı?
{22678}{22693}Kyouyo!
{22704}{22795}Co nedokáeš porozumìt citùm|otce ke své dcerce?
{22795}{22843}Podìlím se s tebou o trochu informací.
{22880}{22931}Je tu nìco, co mùeš udìlat jen ty.
{22943}{23009}Ale nesmíš si vybrat špatné místo.
{23767}{23805}Napijeme se tady.
{23805}{23821}Jistì.
{24144}{24175}To nám to nandal, co?
{24209}{24224}He?
{24224}{24265}Ty jsi tu sám, Kaoru?
{24265}{24286}Kde je Hikaru?
{24300}{24341}Šel pro nìjaké pytle na odpadky.
{24341}{24355}Aha.
{24457}{24498}Jste si jistí, e vyhrajete tu soutì?
{24519}{24546}Kdo ví?
{24601}{24648}Brilantní tah, Kyouyo.
{24648}{24724}Doteï si nevšiml, e je tu piáno.
{24836}{24859}Pozor!
{25148}{25162}Promiòte!
{25162}{25183}Promiòte!
{25183}{25209}Jste v poøádku?
{25223}{25263}Bylo to tìsnì, ale jsme celí.
{25263}{25274}V poøádku?
{25287}{25335}Jasnì, díky.
{25345}{25358}Kaoru!
{25375}{25388}Ach...
{25421}{25479}Kaoru, máš na tváøi škrábanec!
{25479}{25519}Jo, trochu jsem se škrábl.
{25671}{25689}Hikaru?
{25739}{25789}U mì tak nedìs, chlape.
{25835}{25876}Jo, promiò.
{25892}{25919}Nic mi není.
{26081}{26106}BRAVO!!
{26106}{26137}BRAVO!!
{26137}{26193}Osvìující bratrská láska je tak nádherná!
{26193}{26228}Misuzu-cchi je dojata!
{26228}{26260}Dostáváte skvìlıch 100 bodù!
{26260}{26332}Vítìzi se stávají bratøi Hitachiinové!
{26484}{26511}To ne...
{26527}{26549}Opravdu?
{26612}{26635}Gratuluji.
{26692}{26736}Proè... dìkovat.
{26749}{26804}P-Poèkejte, neøíkejte, e...
{26834}{26877}...to bylo naplánované?
{26892}{26923}Och, e by?
{26923}{26950}Kdo ví?
{27130}{27167}Opravdu, nic mi není.
{27229}{27341}Navíc, nemuseli jsme pouít naší | strategii "osvìující bratrská bitka".
{27358}{27372}Jasnì...
{27856}{27907}Jak... jsem... øekl!
{27907}{27964}Omlouvám se, Kaoru.
{27964}{28020}Nepamatuju si, e bych tì shodil z postele...
{28020}{28042}...není to moje vina.
{28064}{28106}Spal jsem na studenı podlaze...
{28106}{28144}...a teï mì bolí záda.
{28262}{28307}Dones nám snídani, prosím.
{28307}{28395}Dal bych si toust s holandskım máslem|a zalitı sirupem, ano?
{28395}{28436}Já bych si dal vejce se šunkou,
{28436}{28487}...a lupínky Bisley.
{28487}{28533}Araiùv            Koloniál|Ty s kouskama ovoce.
{28533}{28548}A ještì...
{28548}{28565}Poèkej!
{28579}{28630}Tohle na jídelním lístku nemáme!
{28664}{28691}Vy dva!
{28705}{28766}Nechtìjte takové nesmysly, vy ïáblovi bratøi!
{28766}{28847}Nebo si myslíte, e jste teï|nìjaká bohatá smetánka?
{28847}{28897}No, my jsme.
{28897}{28943}Kruci, ty taky.
{28943}{28994}Kdy jsi v Øímì, chovej se jako Øímané.
{28994}{29029}To je základní pravidlo.
{29029}{29093}Kdy jste v Karuizawì, |uívejte, co Karuizawa nabízí.
{29093}{29116}To je elezná zásada.
{29137}{29230}Tohle je Jersey sterilizované|za nízké teploty a dus ze Shinshuu!
{29230}{29285}Dále tato kombinace horské zeleniny...
{29285}{29368}...a lososa s hranolkami, uzeného|tøešòovım døevem, co je místní specialita.
{29368}{29404}Na tyto peèené Campagne...
{29404}{29471}...si namate domácí dem pøinášející|pùvodní chu jeho ingrediencí.
{29484}{29524}Proè je tak najednou...
{29524}{29562}...Nagano maniak?
{29562}{29622}Pøišel brzy ráno,
{29622}{29674}take ho paní Misuzu trochu pouèila.
{29684}{29717}Tohle je...
{29717}{29750}Ach, chápu, chápu!
{29772}{29837}Zatímco jste vy dva spali,
{29837}{29899}...tak jsem pøipravil prùvodce pro náš vıcvikovı tábor.
{29899}{29952}Jako vıraz úcty od vašeho pøedsedy.
{29952}{30005}Spíš máš moc volného èasu.
{30005}{30057}{C:$2020C7}[Kampaò "Tamaki je kamarád" - zahájena] | Haruhi, v téhle sezónì...
{30057}{30099}...mì neber jako stašího a chytøejšího.
{30099}{30145}- To je pravidlo jedna. | - Ach...
{30155}{30174}Co je tohle?
{30174}{30215}"Pravidlo èíslo 5"
{30215}{30269}Píšeš tu "Vstávat v 6 ráno".
{30280}{30370}Myslíš, e se tím budou|Kyouya a Honey øídit?
{30431}{30461}{C:$2020C7}Oèi Ïábla
{30461}{30494}{C:$2020C7}Oèi Bestie
{30602}{30651}Ach, promiò, promiò, mùj pane.
{30651}{30747}- Muselo mu to pøipomenout nìjakou špatnou vzpomínku. | - Maminko...
{30747}{30776}Dobrı den!
{30776}{30812}To jsem já, Araiùv Koloniál!
{30812}{30863}Áno, dìkuji mnohokrát.
{30863}{30912}Och, vy jste novı pomocník?
{30912}{30962}- Støedoškolák? | - Ano.
{30962}{31037}Pøes prázdniny pomáhám našim v obchodì.
{31037}{31099}Boínku, jak osvìující!!!
{31099}{31174}Haruhinko, dej to do chadnièky, dobøe?
{31174}{31192}Bìím.
{31245}{31279}Haruhi, ty jsi...
{31289}{31324}Haruhi Fujioka?
{31418}{31444}Araii?
{31788}{31805}Ech?!
{31812}{31899}Pøeklad: Charlie               Korekce a vıpomoc s dialogy: Taylor|Pùvodní titulky: luqas123
{31991}{32066}Bìet pìt tisíc mil,
{32074}{32129}Bìet bez dechu.
{32141}{32212}Sto litrù adrenalinu
{32212}{32304}Mì plní energií.
{32322}{32398}Jít tahle daleko je fajn, e?
{32398}{32463}Jak daleko bude OK?
{32463}{32542}Stromy, které zdobí mìsto
{32542}{32630}Stále mìní svùj vzhled.
{32650}{32723}Úplnì jiná bílá
{32723}{32768}Stále stejná slabost
{32779}{32909}Chci vìøit sám v sebe tady a teï.
{32909}{33000}Zdvíhám vysoko levou i pravou ruku
{33000}{33072}Prorazit temnotu a vpøed!
{33082}{33139}Nic není falešné
{33167}{33225}Moje rozhodnost slábne!
{33249}{33327}Start! Právì od teï...
{33327}{33413}Mùj svìt se musí otevøít!
{33453}{33536}Proè musí jít Haruhi na rande|s tím lháøem Hikarem?
{33536}{33568}Hikaru, kam pùjdeme teï?
{33568}{33600}Líbání zakázáno!
{33600}{33638}Spoleèné lízání zmrzliny zakázáno!
{33638}{33704}V pøíštím dílu| "Haruhin a Hikarùv Bitevní plán První rande".
{33704}{33788}Ouranskı hostitelskı klub na vás bude,|jako obvykle, èekat i pøíští tıden.
