{10}{140}V Blízkej budúcnosti - Siete korporácii|siahajú a ku hviezdam|a vesmírom prúdia elektróny a svetlo.
{150}{280}Avšak postup poèítaèovania|zatia¾ nezmazal rozdiely|národov a etnickıch skupín.
{426}{490}Všetkım hliadkujúcim leteckım jednotkám.|prebieha 208...
{492}{534}v obvode C-13|mesta Newport.
{536}{622}Vzdušnı priestor nad touto oblasou|bude uzatvorenı. Opakujem:
{623}{695}Všetkım hliadkujúcim leteckım jednotkám.|prebieha 208...
{698}{744}v obvode C-13|mesta Newport.
{746}{820}Vzdušnı priestor nad touto oblasou|bude uzatvorenı. Opakujem:
{1458}{1510}Nièoho sa netreba obáva.
{1512}{1582}Môete to vyskúša znova|a budete v našej krajine.
{1585}{1630}"Vyskúša to znova?"
{1630}{1698}Èo je lepšie ako bez-chybnı program...
{1699}{1795}neexistuje takı program,|z ktorého sa nedajú odstráni|chyby. Nemám pravdu?
{1798}{1846}Vy nerozumiete.
{1847}{1911}My ešte stále nevieme|èi je to skutoène chyba.
{1914}{1971}Pôvodnı úèel projektu 2501 bol ...
{1974}{2044}Major, Sekcia 6 je u pripravena na presun.
{2094}{2151}Major!|- Poèujem vás.
{2182}{2251}Vo vasom mozgu je dnes nejako|ve¾a ruchu
{2254}{2305}Je zlá èas mesiaca.
{2498}{2566}Nebudú problémy, ak sa Sekcia 9|votrie do operácie Sekcie 6?
{2567}{2616}Ten diplomat je ale pekná sviòa.
{2618}{2704}Aj keï ho chytia,|všetko èo môu je deportova ho.
{2706}{2828}Sme jediní  ktorí si|môu zašpini ruky.
{2830}{2892}Idú.|Prenes nás na vıchodzí bod.
{3812}{3864}Èo?  Polícia?
{4038}{4122}Prestaòte! Kto vám kázal zaháji pa¾bu?!|Odhoïte zbrane!
{4222}{4328}Ja mám diplomatickú imunitu!|Chcem hovori s tım kto tu velí!
{4330}{4386}Transport evidovaného|programátora  mimo krajiny...
{4389}{4437}hrubo porušuje naše|vıvozné zmluvy.
{4438}{4530}Mohol by som vás|obvini aj z únosu.
{4532}{4579}Vydajte nám toho mua!
{4582}{4644}Obávam sa e nie.|Poiadal nás o politickı azyl...
{4646}{4714}a u podpísal prehlásenie|v tom zmysle!
{4717}{4782}Kedy?!?|- To vám nemusím poveda!
{4784}{4850}Na základe medzinárodného práva,|moja krajina mu môe...
{4852}{4923}ponúknu ochranu|a bezpeènı prechod.
{4926}{4976}Dokument je v spise|na našom ve¾vyslanectve.
{4978}{5031}Pošlem vám|kópiu za pár dní.
{5034}{5094}Ste si istı?|ivı sa u spä nevrátite.
{5095}{5148}iadam Vás aby ste|váili svoje slová.
{5150}{5203}Naša krajina je|mierumilovná a demokratická.
{5206}{5252}Naozaj?
{5294}{5344}Za oknom! Strie¾ajte!
{5544}{5607}Termooptická kamuflá...
{5838}{5909}||A ga maeba,|Keï tancuješ
{5910}{6033}GHOST IN THE SHELL|Duch v škrupinke|A ga maeba,|Keï tancuješ
{6034}{6075}||A ga maeba,|Keï tancuješ
{6110}{6280}kuwashime yoini keri|prekrásna ena sa opije
{6380}{6610}A ga maeba,|Keï tancuješ
{6658}{6821}teru tsuki toyomu nari|iariaci mesiac znie
{6930}{7255}Yobai ni kami amakudarite,|boh klesá na svadbu
{7275}{7780}Yoha ake, nuedori naku,|úsvit prichádza kım noènı vták spieva
{8290}{8505}A ga maeba,|Keï tancuješ
{8555}{8730}kuwashime yoini keri|prekrásna ena sa opije
{8827}{9050}A ga maeba,|Keï tancuješ
{9090}{9258}teru tsuki toyomu nari|iariaci mesiac znie
{9375}{9700}Yobai ni kami amakudarite,|boh klesá na svadbu
{9705}{10200}Yoha ake, nuedori naku,|úsvit prichádza kım noènı vták spieva
{12528}{12589}To je vzácne potešenie,|pán Aramaki.
{12591}{12656}Èo môe ministerstvo zahranièia|urobi pre Sekciu 9?
{12657}{12706}O èo ide v tıch zajtrajších tajnıch rozhovoroch|do ktorıch je zapletená...
{12708}{12756}Gavelská Republika?
{12757}{12806}Ako vdy. Zahranièná pomoc.
{12808}{12877}Nová porevoluèná vláda obnovila iados.
{12879}{12940}Tvrdia, e sú viac demokratickí...
{12942}{13009}ale nièím sa nelíšia|predchádzajúcej bandy.
{13011}{13072}Da im peniaze, ktoré si nezaslúzili,|to nikomu nepomôe.
{13073}{13135}Budú sa domnieva, e sú to reparácie|za minulé vykorisovanie,|a ani nepoïakujú.
{13137}{13192}A èo chce urobi vláda?
{13193}{13257}Problém je v tom,|e  my máme vodcu...
{13259}{13320}tej starej junty,|ktorı tu h¾adá politickı azyl.|(pozt.: junta = vládny orgán)
{13321}{13366}Plukovník Maless, správne?
{13368}{13442}Tak my ho vyhodíme|a ponúkneme im pomoc?
{13444}{13523}Alebo ho vyhlásime za uteèenca|a zaprieme im pomoc?
{13525}{13591}To nie je ¾ahké rozhodnutie.
{13593}{13668}Osobne, ak by som našiel|politicky prijate¾nı  dôvod...
{13669}{13750}deportujem toho mua|okamite.
{13968}{14051}Ach áno, vïaka za vašu pomoc|s tım programátorskım nedostatkom.
{14053}{14119}Nakamura zo sekcie 6  povedal,|e je vïaènı.
{14121}{14192}Predsa my, v diplomatickıch zboroch, si|musíme udra èisté ruky.
{14336}{14384}Povolenı prístup.
{14386}{14453}Stratili sme odozvu.|Ako vyzerajú jej mozgové vlny?
{14455}{14538}Normálne.|Prechádza u na|reim virtuálnych myšlienkovıch vzorcov.
{14571}{14620}Tlmoèníèka ministerstva obrany.
{14622}{14730}Pred 23 minútami,|bol jej kybernetickı mozog hacknutı|cez telefónne spojenie.
{14773}{14838}Presne ako divízia zahraniènej|šionáe predpokladala...
{14840}{14888}Bábkár zaèal prenika do...
{14889}{14937}kadého terminálu siete.
{14938}{14997}Analıza myšlienkovıch vzorcov ukázala|vysokú pravdepodobnos, e...
{14998}{15072}sa pokúša naruši tajné|hovory s Gavelom.
{15074}{15148}Umiestnili sme kadého úèastníka|rozhovorov pod doh¾ad.
{15150}{15209}Pravdepodobne sa pokúša|hacknú jej ducha...
{15210}{15291}aby zabila všetkıch ¾udí na schôdzke.
{15293}{15408}Ako dlho to potrvá kım sa hackne|cez obranu a dosiahne jej ducha?
{15409}{15521}Pouíva starı štıl HA-3.|Povedal by som tak dve hodiny.
{15523}{15569}Potom by sme mali preruši linku,|aby sme odstránili všetky riziká.
{15570}{15650}Batou a Ishikawa  sú v aute,|stopujú signál.
{15652}{15700}Stretni sa s nimi.
{16133}{16216}Bábkár...|Ten fantóm hacker, však?
{16217}{16272}Myslia si, e je Amerièan.
{16273}{16341}Vek, pohlavie, osobná história...|Niè sa o òom nevie.
{16342}{16416}Od poslednej zimy bol hlavne|aktívny v Európe.
{16417}{16482}Medzinárodne h¾adanı|za tucty priestupkov...
{16484}{16549}manipulácie s akciami,  špioná,|politické ininierstvo...
{16551}{16636}terorizmus a narušenie|kyber-mozgového súkromia.
{16638}{16715}Aby vykonal svoje zloèiny|hackol ducha to¾kım ¾uïom
{16717}{16778}a tak získal prezıvku "Bábkár".
{16780}{16844}To je prvı krát|èo operuje v tejto krajine.
{16846}{16949}Keï je takı dobrı preèo|pouíva starı HA-3?
{16951}{17084}Novší typ by bol horšie vypátrate¾nı a|ašie by sa sledoval.
{17086}{17210}Ale mohol by ukazova na previazanie|s bıvalım vodcom junty,|Plukovníkom Malessom.
{17212}{17332}Tak pouíva starší typ|aby sme ho nemohli podozrieva.
{17333}{17440}Alebo niekto inı chce|aby sme si to mysleli.
{17441}{17523}Maless môe by len ïalší pešiak|v celej tejto hre.
{17525}{17619}Teraz u preháòaš.|O tom nemáme dôkazy.
{17621}{17660}Dôkazy?
{17703}{17775}Mám takú predtuchu...|Pošepkal mi ju môj duch.
{17777}{17849}Mimochodom,|stále pouívaš ten revolver?
{17851}{17921}Bojíš sa novších zbraní?
{17922}{17966}Mám rád svoj Matever.
{17968}{18018}Od kedy sa spolieham na to e ma kryješ|si myslím, e palebná sila je...
{18019}{18074}dôleitejšia ne|osobné preferencie.
{18075}{18123}Obzvláš, keï je to môj zadok,|ktorı máš kry.
{18126}{18190}Radšej ho vymeò za Zastaber.
{18191}{18274}Major,| u dlhšie sa vás chcem spıta?
{18275}{18362}Preèo ste vyiadali na preloenie|od polície takého obyèajného|chlapa ako ja?
{18363}{18397}Vlastne preto,| e si takı obyèajnı chlap.
{18399}{18435}He?
{18438}{18557}Poctivı policajt s èistım registrom|a máš normálnu rodinu.
{18558}{18659}S vınimkou malého implantátu|na pripojenie sa k sieti,|je tvoj mozog plne organickı.
{18661}{18719}Bez oh¾adu na to akı silnı|a múdri by sme boli v boji,
{18721}{18789}systém v ktorom reagujú|všetky èasti rovnako,
{18790}{18869}je systém so závanou chybou.
{18870}{18907}Ako jednotlivec,|tak aj celok.
{18909}{18966}Nadmerná špecializácia  vedie k smrti.
{18967}{18994}To je všetko.
{19281}{19341}- Poï u!|- Vyrd chví¾oèku!
{19459}{19517}Sme u 40 sekúnd pozadu|oproti plánu!
{19518}{19598}- Daj mi ešte pä sekúnd.|- Aká to smola...
{19753}{19791}Hej, prepáè.
{19793}{19863}Môj poslednı partner,|ten ktorého vyhodili...
{19866}{19925}za prácu bez povolenia,|bol lepší ako ty!
{19977}{20040}Naozaj sa pokúšaš hacknú ducha|svojej vlastnej manelky...
{20042}{20091}len preto, aby si videl,|èo si myslí?
{20093}{20201}Nemá na mòa iadny èas.|A teraz chce ešte rozvod.
{20203}{20275}Navyše, moja dcéra,|moje jediné diea...
{20278}{20334}si myslí, e to ja|podvádzam jej matku!
{20335}{20417}A ako si sa dostal|ku hackovaciemu programu?
{20418}{20535}Od jedného programátora.|Ve¾mi milı chlapík,|ktorého som stretol v bare.
{20537}{20608}Povedal som mu, e advokát mojej manelky|mi bráni vidie ju...
{20609}{20653}a on povedal, e mi skúsi pomôc.
{20654}{20719}Poradil mi, aby som sa pripájal|z rôznych miest, aby ma nezamerali.
{20721}{20765}Bystrı chlapík, èo?
{20885}{20945}Debil! Skúšaš sa zabi?!
{20947}{21013}Vyzerá to tak,|e tu niesme jediní èo sa ponáh¾ajú.
{21102}{21151}Nikto tu u nie je.
{21153}{21209}Èo to má znamena?|Keï u zameriame bod pripojenia...
{21210}{21273}kım dorazíme,|ten chlap u dávno odíde.
{21275}{21342}- Zaèarovanı kruh, èo?|- Prestaò sa saova!
{21343}{21403}Kusanagi a Togusa mieria|k ïalšiemu miestu,|odkia¾ oèakávame pripojenie.
{21405}{21457}Vy dvaja h¾adajte nieèo namieste.
{21459}{21493}Èo máme h¾ada?
{21495}{21547}Èoko¾vek.
{21549}{21603}Poondiaty starı plešivec.|On NÁM káe "pátra" v okolí?!
{21605}{21655}Poèkajte sekundu!
{21657}{21707}Dofrasa, nestihol som ho.
{21710}{21777}Hej, pane.|Videli ste tu ís smetiarsky voz?
{21778}{21826}Kto to chce vedie?
{21827}{21875}Tak videl si alebo nie?
{21878}{21967}Áno, ale odišli,|skôr ako som stihol donies smeti.
{21969}{22031}Jeden pouíval telefón,|tak som myslel e mám èas.
{22099}{22174}Hmm, môete im zobra toto?
{22175}{22275}Smetiarsky voz? Pochopite¾ne...|Pohybujú sa kadıch sedem minút.
{22277}{22376}Centrála! Dajte mi všetky trasy|smetiarov pre tento sektor!
{22652}{22711}V oblasti pracuje|osem smetiarskych aút.
{22713}{22775}Cie¾ je zbernı voz typy C èíslo 79.
{22846}{22904}Prenechaj mi riadenie.
{23105}{23166}Ishikawa,|preskúmaj bydliská vodièov.
{23167}{23230}Batou, odsekni im cestu|na ich nasledujúcej zastávke!
{23231}{23334}Môe by v kontakte s niekım inım.|Pozoruj, ale nezasahuj!
{23336}{23384}Prístup k cestnım dátam získanı.
{23386}{23493}Miesto hacku vystopované a potvrdené.|Cie¾ zastavuje na ïalšom bode.
{23536}{23593}Potvrdzujem prístup cez HA-3.
{23733}{23777}Prepáè, prepáè.
{23778}{23850}Èo keby som na najblisiej zastávke|bral smeti ja a ty budeš telefonova?
{23886}{23909}V poriadku?
{23910}{23975}Nechcem ma niè spoloèné s tvojími "vlámaniami".
{23978}{24030}Nemôem uveri takej|kope nezmyslov...
{24033}{24113}- Máš deti?|- Vyzerám akoby som mal?
{24114}{24162}Tak tomu nemôeš rozumie.
{24165}{24221}Moja dcéra je to najdôleitejšie v mojom ivote.
{24222}{24296}Pozri. Nieje ako malı anjelik?
{24298}{24372}Nenávidím prezeranie|cudzích rodinnıch albumov.
{24431}{24503}Áno, voz 79.|Ach, šéfe. Èo je?
{24537}{24618}Poliši kontrolujú naše trasy?|Chceš vedie preèo?
{24619}{24670}A odkia¾ to mám ja vedie?!
{24757}{24837}Zamerali môj útok!|Musím varova priate¾a!
{24838}{24900}Vynecháme následujúcu zastávku!
{24902}{25006}Cie¾ vyboèil z trasy.|Zvyšuje rıchlos.
{25009}{25092}Vie o nás?|Nemyslím si, e by ma zbadal.
{25093}{25159}Môj prístup k smetiarskej sieti|ho mohol varova.
{25161}{25209}Mala si poui zadné dvierka.
{25210}{25270}U neskoro.|Choï mu po krku.
{25386}{25441}Teraz môeš šoférova.
{26958}{27034}Jeiši...   Spravil z perfektne|opancierovaného voza hromadu šrotu.
{27036}{27117}Páli na nás vysoko-rıchlostnımi|protipancierovımi projektilmi!|To auto a neochráni!
{27118}{27182}V automatickej puške?|Ten chlap musí by cvok.
{27531}{27580}Tie pouíva nejakı druh termooptickej kamufláe?!
{27582}{27668}Choï za ním!|Ja ho napadnem zhora!
{27669}{27754}Togusa, ak ešte iješ,|zatkni tıch dvoch smetiarov.
{27757}{27786}Vykonám.
{27815}{27887}Táto práca sa nikdy nezmení,|èi áno?
{29299}{29357}Polícia! Všetci k zemi!
{32252}{32311}Hotovo?
{33565}{33621}Všetci pripravenı?
{33621}{33695}To sa stane|keï prekroèíš monosti zbrane.
{33697}{33803}Všetko nech ide do pekla.|Tie pekelné náboje tie.
{33805}{33897}Je mi jedno èi ma zatknete.|Vôbec niè vám nepoviem!
{33897}{33945}Nepovieš?!
{33989}{34101}A èo by som sa pıtal chlapíka,|ktorı nevie ani ako sa volá?!
{34153}{34205}Nepozná tvár vlastnej matky,
{34207}{34273}miesto kde vyrastal,
{34276}{34321}nemá spomienky z vlastného detstva, ...
{34349}{34429}Pamätáte si vôbec nieèo z toho?
{34586}{34662}Nie je niè viacej alostné,|ako bábka bez ducha.
{34665}{34723}Obzvláš taká,|v ktorej prúdi èervená krv.
{35102}{35167}Vtrhneme,|keï chlapi z vrtu¾níka budú vo vnútri.
{35169}{35239}Oddiel B ide zo dozadu,|zvyšok z predu.
{35241}{35355}Saito,|nech im vaši ¾udia vyberú svieèky zo všetkıch áut.
{35357}{35415}Zaèínam nahráva.
{35481}{35550}Správa z centrály.
{35553}{35623}Máme identifikáciu chlapa,|ktorého privlekla Majorka.
{35625}{35658}Pokraèuje.
{35661}{35730}Tsuan Gen Fang. Vek: 28.
{35732}{35855}Ilegálny vstup do krajiny.|Zbraòové priestupky. Tri záznamy.
{35857}{35968}Ukrıval sa za militantnou uteèeneckou skupinou,|a do minulého mesiaca.
{35970}{36052}Pred tıdòom,|pod¾a jeho záznamov...
{36054}{36120}bol kontaktovanı vojenskou spojkou|v Gavelskom ve¾vyslanectve aby...
{36120}{36196}zaútoèil  na tajné rokovanie,|èo sme s nimi mali.
{36197}{36247}A v skutoènosti?
{36249}{36372}Prezıvka: Corgi.|Zamestnanie:  vcelku násilnícky obchodník s odpadkami.
{36373}{36419}Jednoducho násilník.
{36420}{36531}Skontrolovali sme jeho záznamy,|na miestnej polícii,
{36533}{36624}ale nenašli sme|iadne prepojenie s Gavelom.
{36624}{36701}Je to len ïalšia bábka|od nášho priate¾a Bábkára.
{36703}{36749}A èo Ishikawa?
{36752}{36883}Vrátil sa. Spolu s Togusom,|vypoèúva toho úbohého smetiara.
{36936}{37005}A èo bábkar na vašej strane?
{37007}{37083}Èo si o òom myslíte?
{37181}{37238}Sám je ako bábka...
{37240}{37311}- Oddiel B, v pozícii.|- Oddiely A a C, pripravené!
{37312}{37368}Pripravenı zaútoèi, pane.
{37390}{37438}Útok.
{37499}{37565}Èo myslíte tımi,|"virtuálnymi záitkami"?
{37567}{37648}Myslím vašu manelku,|vašu dcéru, rozvod, celá tá záleitos...
{37650}{37740}Sú to všetko falošné spomienky.|Nieèo ako sen.
{37742}{37840}Niekto vás vyuíval na|hackovanie duchov vládnych úradníkov.
{37842}{37900}Nie... Nemoné!
{37901}{37958}Bol  som vo vašom byte.
{37960}{38030}Nikto tam nie je.|Je to jednoizbovı byt.
{38032}{38107}Áno, presahoval som sa tam,|keï sme sa rozišli.
{38108}{38200}Bıvate tam u desa rokov!
{38201}{38266}Nemáte manelku, ani diea.
{38268}{38326}Vaša rodina existuje|len vo vašej mysli.
{38368}{38468}Pozri. Toto je obrázok|èo ste ukazovali kolegovi.
{38484}{38544}èo na òom je?
{38544}{38639}Ale, ona tam bola.|Moja dcéra...
{38641}{38708}Usmievala sa ako anjel...
{38708}{38765}Ako sa volá vaša dcéra?
{38767}{38831}Kedy a kde ste stretli vašu enu?
{38833}{38907}Pred ko¾kımi rokmi ste sa vzali?
{38909}{39000}Koho vidíte na obrázku?
{39031}{39129}Ako sa zbavím tıchto|falošnıch spomienok?
{39131}{39198}¼utujem ale so súèastnou technológiou...
{39200}{39250}boli iba dve deprogramácie úspešné,
{39252}{39306}ale nemôem to odporúèa.
{39308}{39350}Je mi to ve¾mi ¾úto.
{39352}{39408}Virtuálne záitky,  sny...
{39410}{39530}Všetky dáta, ktoré existujú,|sú súèastne realita aj fantázia.
{39578}{39651}Ktoréko¾vek to sú,|dáta ktoré nazbiera èlovek za celı ivot...
{39653}{39717}sú v porovnani s celkom len malá èas.
{41833}{41920}Cyborg ktorı sa chodí|potápa vo vo¾nom èase.
{41922}{42023}To nemôe by dobré znamenie.|Kedy si s tım zaèala?
{42146}{42255}Nemáš strach z oceánu?|Keï sa ti pokazia nadnášaèe.
{42256}{42346}Tak nepochybne umriem.|Alebo by si skoèil,|aby si ma zachránil?
{42374}{42432}Nikto a nenúti chodi sem so mnou.
{42445}{42475}Ja len
{43265}{43346}Akı to je pocit|keï sa potápaš?
{43348}{43427}Nemal si aj ty podvodnı tréning?
{43428}{43481}Nehovorím o potápaní v prekliatom bazéne.
{43515}{43586}Cítim strach. Nepokoj.|Osamelos. Temnotu.
{43588}{43650}A postupne...nádej.
{43652}{43715}Nádej? V tenmote mora?
{43745}{43795}Keï tak plávam smerom k povrchu...
{43797}{43901}Cítim sa skoro tak,|akoby by som sa mohla zmeni|v nieèo iné.
{44044}{44116}Akoby by si chcela|skonèi zo Sekciou 9?
{44197}{44274}Batou, ko¾ko ostalo|z tvojho pôvodného tela?
{44276}{44322}Si opitá?
{44324}{44370}Vıhodné, nie?
{44372}{44442}Staèí jedna myšlienka|a chemické implantáty v naších telách...
{44444}{44545}by vstrebali všetok alkohol|v našej krvi tak za desa sekúnd...
{44547}{44624}take tu môeme sedie, pi len tak|a by celı èas v pohotovosti.
{44626}{44714}Ak je technologickı vıkon monı,|èlovek ho urobí.
{44716}{44786}Skoro ako keby to bolo|zabudované do jadra nášho bytia.
{44788}{44846}Metabolická kontrola.|Zvıšené zmyslové vnemy.
{44848}{44914}Zlepšené reflexy a svalovı vıkon.
{44916}{44984}Znaène zvıšená rıchlos a|kapacita spracovania dát.
{44986}{45097}Všetky tie zlepšenia vïaka našim|kyber-mozgom a kybernetickım telám.
{45099}{45185}Èo z toho, ak nemôeme i bez|údrby na vysokej úrovni?
{45187}{45232}Nemáme sa naèo saova.
{45234}{45336}To neznamená,|e sme predali naše duše Sekcii 9.
{45338}{45410}Môeme rezignova|kedy len budeme chcie...
{45412}{45482}za predpokladu,|e vrátime vláde naše kybernetické súèasti...
{45484}{45544}a spomienky, ktoré obsahujú.
{45546}{45641}Práve tak ako je potrebnıch ve¾a èastí,|aby spravili èloveka èlovekom,
{45643}{45714}Ve¾a vecí je potrebnıch na to,|aby spravili...
{45716}{45760}jednotlivca tım, èím je.
{45762}{45801}Tvár, na rozlíšenie seba od inıch.
{45803}{45840}Hlas, ktorı si sám neuvedomuješ.
{45842}{45886}Ruku, ktorú uvidíš po zobudení.
{45888}{45960}Spomienky z detstva,|vedomie pre budúcnos.
{45962}{46032}A to nie je všetko.|Je tu rozšírenie o dátovú sie...
{46034}{46093}do ktorej môe môj|kyber-mozog vstúpi.
{46095}{46141}Toto všetko ma robí takou aká som.
{46143}{46231}Z toho všetkého vychádza to,|èo volám "ja."
{46233}{46328}A súèasne stanovuje môjmu|"ja" nieko¾ko hraníc.
{46457}{46544}Preto sa ponáraš do mora|s telom, èo môe iba klesa?!
{46546}{46632}A èo vlastne vidíš|v morskej temnote?
{46634}{46894}"To èo teraz vidíme,|to je iba hmlistı odraz v zrkadle"|"Potom sa uvidíme tvárou v tvár"
{46945}{47008}To si bola ty, e?
{47479}{47716}A ga maeba,|Keï tancuješ
{47751}{47921}kuwashime yoini keri|prekrásna ena sa opije
{48021}{48251}A ga maeba,|Keï tancuješ
{48299}{48462}teru tsuki toyomu nari|iariaci mesiac znie
{48571}{48896}Yobai ni kami amakudarite,|boh klesá na svadbu
{48916}{49421}Yoha ake, nuedori naku,|úsvit prichádza kım noènı vták spieva
{50196}{50411}A ga maeba,|Keï tancuješ
{50461}{50636}kuwashime yoini keri|prekrásna ena sa opije
{50733}{50956}A ga maeba,|Keï tancuješ
{50996}{51164}teru tsuki toyomu nari|iariaci mesiac znie
{51281}{51606}Yobai ni kami amakudarite,|boh klesá na svadbu
{51611}{52106}Yoha ake, nuedori naku,|úsvit prichádza kım noènı vták spieva
{52938}{52980}Senzory: reštartované.
{52982}{53032}Pomocné poèítaèové èlánky:|skontrolované.
{53034}{53080}Zrakové senzory: pripojené.
{53081}{53152}- Kyborg telovı signál?|- Vıstup: normály.
{53298}{53362}Nemôeš zavola,|e sa oneskoríš?
{53449}{53520}Všetci sme pripravenı.|Máme ju pripoji?
{54081}{54152}V poriadku, vyzerá to dobre!|Odpojte to!
{54153}{54224}Buïte v mojej kancelárii do troch minút.
{54325}{54449}Keïe si prišla neskoro,|vysvetlím ti èo sa deje.
{54452}{54545}Pred dvoma hodinami montána linka|Megatech Tiel v meste Newport...
{54548}{54609}sa len tak zapla a|zaèala vyrába kyborg-telo.
{54611}{54680}Kım si zodpovednı všimli èo sa deje...
{54681}{54748}telo utieklo.
{54749}{54821}Potom èo vytvorili kordón,|aby tú vec chytili...
{54824}{54874}zavolal nám akısi svedomitı vodiè, ...
{54876}{54973}e práve zrazil akúsi nahú dámu|potulujúcu sa po dia¾nici.
{54974}{55033}A to nás dostalo sem.
{55034}{55106}Poèul som e Megatech Telá|majú silnú väzbu na vládu...
{55108}{55179}a e všetky telá,|ktoré tam vyrobia sú tajné.
{55180}{55228}Ak to urobil hacker,|musel prerazi...
{55229}{55283}najlepšie dostupné zabezpeèenie vôbec.
{55285}{55334}A to nie je jedinı problém.
{55409}{55538}samozrejme, e telo nemá|organickı mozog vo svojej hlave...
{55540}{55611}ale zistili sme, e má nieèo,|èo vyzerá ako duch...
{55612}{55659}v prídavnom poèítaèovom mozgu.
{55692}{55750}Je to podobné virtuálnej|duchovej-linke, ktorú získaš...
{55752}{55811}keï sa reálny duch rozdvojí.
{55812}{55881}Ale nevykazuje iadne známky degradácie,|ktoré by vznikli poèas rozdvojenia.
{55882}{56000}No, ale pokia¾ nezmapujeme perimetre bariéry|a neponoríme sa tam...
{56001}{56064}niè nebudeme vedie naisto.
{56065}{56136}Nech je akoko¾vek,|lepšie bude vráti sa a preskúma ju.
{56137}{56161}Dobrá práca.
{56162}{56233}Je èas rozobra ju na kúsoèky.
{56353}{56470}No tak. Snáï si nemyslíte,|e tá vec má naozaj ducha.
{56472}{56520}Je to moné.
{56521}{56609}Poèul som,|e celuloidové bábiky môu ma dušu.
{56610}{56721}A toto telo je doplna napchaté|neurotechnickımi zariadeniami.
{56723}{56778}Nebol by som prekvapenı,|keby malo dušu.
{56808}{56881}Pretoe si tu novı,|pravdepodobne nevieš,
{56884}{56977}e celé Majorkino telo|bolo vyrobené tie Megatechu.
{56980}{57073}A nie len jej.|Podobne èasti mòa, Ishikawy...
{57075}{57153}Saita a inıch.|Všetci potrebujeme špeciálnu údrbu.
{57154}{57224}Mimo teba a Šéfa,|všetci v sekcii 9...
{57225}{57297}musia vyuíva ich sluby.
{57298}{57409}Mono teraz pochopíš,|preèo všetci vyzeráme tak ustarane, Togusa.
{57412}{57481}Predpokladáme, e nepriate¾ je z vonku,|nemôeme si by istí,
{57482}{57529}èi je v tom tele alebo nie.
{57531}{57579}Ale prelomil ochranu...
{57580}{57632}okolo našich  najtajnejších súborov...
{57633}{57695}a dokázal cez òu posla|program obsahujúci ducha.
{57697}{57793}A to spôsobom, ktorı sa dal|¾ahko vypátra. O èo mu vlastne ide?!
{57796}{57841}Zatia¾ to nechajme tak.
{57842}{57949}Togusa, choï do Megatech a pomô|Ishikawaovi skontrolova miesto èinu.
{57952}{57997}Batou, uzavrel  sie...
{58000}{58073}so súbormi tak citlivımi,|ako tie v Megatechu.
{58074}{58153}Chcem  aby si zdvojil obranu,|ktorou ich chránime.
{58156}{58251}Vytvorím okolo nej bludiskovú bariéru.|Vojdem tam zajtra.
{58252}{58352}Ste si istá?|Mohli by sme to da do iného tela|a necha to pláva.
{58353}{58477}Chcem sama vidie,|èo je vo vnútri.
{58478}{58550}Nepustite tam nikoho skôr ako mòa!
{58633}{58669}Èo to s òou je?
{58670}{58737}Písal som to v tímovom hodnotení,|e sa správa èudne...
{58740}{58805}od samého poèiatku, keï sme sa zaèali|zaoberá prípadom Bábkara.
{58807}{58861}Èítali ste to vôbec?!
{58862}{58933}Šéfe, nezamysleli sne sa niekedy|nad tım, èi kyber-doktori,
{58936}{58989}ktorı sa starajú o váš mozog, sú spo¾ahliví?
{58992}{59098}Kyber-mozgoví špecialisti robia|regulárne psychologické testy.
{59100}{59177}A bezpeènostná sluba preverila|aj ich súkromnı ivot.
{59178}{59266}Ale ¾udia, ktorí robia tieto previerky,|sú tie len ¾udia.
{59268}{59337}Keï raz zaènete pochybova,|nemôete presta. 
{59338}{59442}Šéf, akısi pán Nakamura|z ministerstva zahranièia vás chce vidie.
{59468}{59493}Dobre, pustito ho dnu.
{59754}{59803}Kto je ten tuènı chlap?
{59804}{59920}Nakamura, šéf Sekcie 6.|úrad zahraniènıch záleitosti.
{59921}{59979}Nepoznám toho belocha,|èo bol s ním.
{60044}{60090}Idem u preè.
{60092}{60152}Povedz Ishikawaovy|aby zachoval pokoj, OK?
{60352}{60393}Take, akı máš problém?
{60396}{60454}Nevyzerá to kybernetické telo|ako ja?
{60456}{60520}- Nie, nevyzerá.|- Ani tvár ani figúra.
{60523}{60560}Èo teda?
{60561}{60668}Snáï všetko,|plne nahradite¾nı cyborgovia,|ako ja, sa zaèinajú zaujíma.
{60702}{60772}To mono moje skutoèné ja|u dávno zomrelo...
{60775}{60880}a ja som duplikát s kybornetickım telom|a poèítaèovım mozgom.
{60880}{60977}Mono nikdy nebolo nejaké "ja"|s ktorım by som zaèala.
{60980}{61062}Máš skutoènı mozog|v tej tvojej titánovej lebke.
{61064}{61128}A správaš sa ako skutoèná osoba,|èi nie?
{61131}{61204}Neexistuje iadny èlovek,|ktorı videl svoj vlastnı mozog.
{61207}{61312}Myslím si, e existujem|len na základe toho, èo mi povie okolie.
{61314}{61376}Neveríš vo vlastného ducha?
{61378}{61449}A èo keby mohol poèítaèovı mozog|vytvori ducha...
{61452}{61496}a vlastnú dušu?
{61498}{61592}Na základe èoho verím sama v seba?
{61752}{61790}Hlúpos!
{61864}{62018}Sám sa chcem pozrie èo je v tom tele.|Mojim vlastnım duchom!
{62048}{62118}Obaja sme zaneprázdnenı,|take to skráme.
{62120}{62164}V tom sa zhodneme.
{62167}{62220}Prišiel som tu, aby som zobral|obsah toho kybornetického tela.
{62222}{62300}Na oplátku, zbavíme Sekciu 9|všetkıch zodpovedností v tomto prípade.
{62324}{62364}Podpis Ministra Zahranièia.
{62649}{62741}Bezpeènos,|èie sluobné autá parkujú v suterénnej garái?
{62744}{62876}Patria Šéfovi Nakamurovi zministerstva zahranièia|a Dr.Willisovi.
{62878}{62952}Uká mi videozáznam|ich príchodu do budovy.
{63149}{63196}Prehraj, to infra-èervene.
{63522}{63595}Raz... Dva... Tri...
{63652}{63778}Pošlite mi záznamy tlakového snímaèa|zo suterénnej garáe priestor B-7 a 8.
{64244}{64340}- Major, tu je Togusa. Kód 0-9.|- Èo sa deje?
{64341}{64427}Má Nakamura nejakı druh špeciálneh|kybernetického tela?
{64428}{64473}V Sekcii 6 nie sú iadni cyborgovia.
{64476}{64530}Mimo diplomatickıch problémov,|udrova ich by bolo príliš...
{64532}{64585}nároène keï musia chodi do zámoria.
{64588}{64658}Take, aj keby bol ten vysokı chlapík úplnı cyborg...
{64660}{64737}spolu by neváili viac ne polo tony, správne?
{64740}{64801}Dáta tlakového snímaèa...|Garáe?
{64804}{64840}Sú tam dve VIP-vozidlá.
{64843}{64913}Ale ani jeden nevyzeral na to,|e by šoféroval sám.
{64916}{64969}Kamery zaznamenali len dvoch ¾udí,
{64972}{65040}ale vy predsa viete ako sú tie senzory|na vstupnıch dverách citlivé.
{65042}{65104}Trvalo to tri celé sekundy,|kım sa to za nimi zavrelo.
{65106}{65224}Je nelegálne pouíva|termooptickú kamuflá vo vládnych budovách,|správne?
{65225}{65290}To je váne narušenie zákona|o štátnej bezpeènosti.
{65292}{65408}Sekcia 6 je a po uši v nieèom zapletená.|Všetci pripravení?
{65411}{65449}Ja aj môj Matever.
{66352}{66432}Nemusím ti pripomína,|e je velezrada...
{66435}{66515}skrıva nieèo predo mnou,|bez oh¾adu na to, aké to je chúlostivé.
{66516}{66553}Pre nás oboch.
{66555}{66655}Je jedno èo preferuje Ministerstvo zahraniènıch záleitosi,|toto je v jurisdikcii sekcie 9.
{66657}{66775}Ale mi by sme nespolupracovali,|ak by na to nebol dobrı dôvod.
{66807}{66839}Dr. Willis?
{66841}{66924}Potvrdené.|Je to urèite on.
{66927}{66961}"On?"
{66963}{67071}Odvoláva sa na originál|bloku ducha v ulite.
{67073}{67143}Jeho pohlavie ostáva neznáme,|a pouívanie termínu "on"...
{67145}{67215}je iba prezıvka|ktorú mu doktor dal.
{67217}{67260}Mono je na èase,|aby som vás predstavil.
{67262}{67379}Toto je najfantastickejší hacker|v histórii kyber-mozgového zloèinu.
{67381}{67428}Bábkár.
{67466}{67541}Verím, e vy zo Sekcie 9|ste na neho u v tomto prípade narazili...
{67543}{67640}napríklad pri haknutí ducha|prekladate¾ky ministerstva zahranièia.
{67642}{67716}My, zo Sekcie 6, stíhame Bábkára...
{67718}{67788}s najvyššou naliehavosou,|od kedy sa prvı krát objavil.
{67790}{67863}Vytvorili sme projektovú skupinu|okolo Dr. Willisa...
{67863}{67944}aby sme analyzovali|všetky dáta o Bábkárovej...
{67946}{68029}kriminálnej tendencii|a model jeho chovania.
{68031}{68124}Potom sme vytvorili špeciálnu|ochranu proti útoku Bábkara...
{68127}{68216}aby sme ho vlákali|do tajného kybernetického tela.
{68218}{68293}Vlákali ste ho tela|vybaveného kybernetickım mozgom...
{68295}{68346}aby ste mohli zabi jeho skutoèné telo?
{68363}{68401}Áno, presne tak.
{68403}{68469}Môe by, e naposledy|bol aktívny u nás...
{68471}{68545}ale narodil sa v Amerike.|A odkedy spolupracujeme...
{68547}{68605}s Amerièanmi na jeho chytení,|chceme ho vzia spä sami.
{68607}{68645}Iste proti tomu niè nemáte.
{68647}{68749}Necha jeho neidentifikovanú màtvolu,|aby sa niekde našla.
{68813}{68856}Neostane iadna màtvola.
{68858}{68959}Pretoe a do teraz som|iadne telo nemal.
{68961}{69042}Jeho senzory sú aktívne!|Preèo ste to nepovedali?!
{69043}{69146}Prerušili sme všetky vonkajšie spojenia.|Beí to na vlastnı zdroj energie
{69148}{69210}Vstúpil som do tohto kybernetického tela,
{69212}{69283}preoe som nemohol preniknú|útoènou ochranou Sekcie 6...
{69285}{69386}ale to, e som sem vstúpil,|bolo z mojej vlastnej slobodnej vôle.
{69387}{69482}Ako autonómna forma ivota,|iadam o politickı azyl.
{69483}{69515}Forma ivota?
{69517}{69596}Smiešne!|Ty si len samo-udriavajúci sa program!
{69598}{69680}V tomto prípade musím konštatova,|e vaša DNA tie nie je...
{69683}{69791}sama o sebe niè viac,|ako  samo-udriavajúci sa program.
{69793}{69930}ivot je ako uzol,|ktorı sa narodí z toku informácií.
{69931}{70032}Ako druh ivota,|ktorı nesie DNA ako svoj pamäovı systém...
{70035}{70114}¾udia získavajú svoju individualitu|zo spomienok, ktoré nosia.
{70115}{70203}Zatia¾ èo spomienky môu by|rovnaké ako fantázia...
{70205}{70275}práve tieto spomienky robia to,|e existujú.
{70277}{70378}Keï poèítaèe dokáu|realizova spomienky...
{70379}{70496}mali by ste zvái  všetky dôsledky,|ktoré z toho vyplıvajú.
{70498}{70555}Hlúpos!|niè èo poviete
{70556}{70616}nedokáe, e ste "ivı"
{70618}{70698}Je nemoné dokáza to.
{70699}{70832}Obzvláš nie, ak ani modernı vedci|nevedia definova èo "ivot" vlastne je.
{70834}{70890}Kto do èerta ste?
{70891}{70995}Aj keby ste mali ducha,|kriminálnikov neprepúšame!
{70996}{71049}Mılite sa ak si myslíte,|e dostanete azyl!
{71051}{71130}Èas je na mojej strane.
{71131}{71190}Aj keï som sa stal "smrte¾nım"...
{71191}{71250}táto krajina nemá trest smrti.
{71251}{71323}Napoly nesmrte¾ná...|Umelá inteligencia?
{71323}{71378}Nie som U.I.
{71379}{71482}Moje kódove oznaèenie je "Projekt 2501"
{71527}{71634}Som forma ivota zrodená|z mora  informácií.
{71883}{71926}Bezpeènos! Votrelci!
{72018}{72061}Šéf, Bábkár!
{72063}{72170}- Kde je vaša bezpeènos?!|- Zavrite obranné steny! Bezpeènos!
{72171}{72203}Bezpeènos, ohláste sa!
{72782}{72823}Dobre, dobre, u miznem!
{72923}{72954}Blbec!
{73078}{73111}Podarilo sa?
{73112}{73198}Pekelné auto. Moja devina|ho ani nešrabla.
{73200}{73264}Koneène som prišiel na|pouitie tvojho Matevera.
{73350}{73392}OK...|Na zaèiatoèníka to nieje zlé.
{73394}{73456}Dal som jeden priamo do ŠPZtky|Dobré, èo?
{73458}{73501}Nabudúce tam daj dva.
{73503}{73576}OK, zaèíname.|Chy ich skôr ako stihnú vymeni autá.
{73674}{73713}Ministerstvo zahraniènıch záleitostí...
{73715}{73774}formálne podá sanos na to èo sa stalo!
{73776}{73840}Kontaktujte ma hneï|len èo ho chytíte
{73842}{73880}ivého, ak to bude moné.
{73882}{73961}Megatech môe vdy vyrobi iné telo.
{74059}{74141}Batou a Togusa  idú po tıch,|èo vzali Bábkára.
{74181}{74237}Sú na dia¾nici 25.
{74239}{74309}Èo tım myslíte?!|Keï ste to sledovali, tak preèo ...
{74311}{74397}Ak ich nedostaneme spä,|nikdy nedokáeme zapojenie Sekcie 6.
{74399}{74430}Prosím?!
{74432}{74524}Presne tak. Pouívajú termooptickú|kamuflá typ-2902 presne tak ako ja.
{74526}{74607}Pouívame ju len my,|hliadky zo Sekcie 4 a Sekcia 6.
{74608}{74706}Povznes sa nad to.|Sekcia 6 dostala Bábkára do tela.
{74708}{74834}Ale on sa rozhodol pre Megatech telo,|ktoré je úzko viazané na Sekciu 9.
{74836}{74891}Potom tvrdil, e je forma ivota...
{74893}{74966}a bol chytenı sekciou 6|práve keï iadal o azyl.
{74968}{75008}Ale preèo to urobil?
{75010}{75062}Mohli ho ma hneï|ako by som zolbral vyjadrenie.
{75063}{75140}Ale èo ak mali strach z toho|èo by vám mohol poveda?
{75142}{75191}Pokia¾ sa pamätám,|spomínal èosi zvláštne.
{75193}{75260}"Kódové meno: Projekt 2501."
{75262}{75303}Preverenie nechám na vás.
{75305}{75406}Teraz, pokia¾ ide o útok|na sekciu 6 a kráde dôkazov...
{75407}{75459}- Máte povolenie.|- OK, ideme!
{75609}{75663}Kusanagi! Ešte nieèo!
{75665}{75744}Môete ma potresta za konanie bez rozkazu,|keï sa vrátim.
{75746}{75832}Ak ho nezískate spä,|chcem ma Bábkára znièeného.
{75834}{75871}Bez zlyhania.
{75907}{75940}Celkom urèite.
{75948}{75978}Rozumiem.
{76024}{76095}Skontaktujte sa s letiskom|a zastavte všetky lety patriace...
{76097}{76167}úradníkom Ministerstva zahranièia,|alebo Americkım diplomatom.
{76168}{76206}Uzavrite dia¾nice a nastrate zátarasy.
{76207}{76253}Zavolajne na to všetok presonál|i mimo sluby
{76255}{76298}A dostante Ishikawu spä sem.
{76300}{76405}Pouite prístupové dáta  na zistenie,|kto bol ten beloch s Nakamorom.
{76407}{76502}A pátrajte po všetkıch druhoch projektov|ministerstva zahraniènıch záleitosti|operáciách, alebo po èomko¾vek...
{76503}{76565}oznaèenom ako "Projekt 2501".
{76710}{76758}Nejaké správy od prepadového tímu?
{76759}{76813}Pred minútou vymenili autá.
{76815}{76862}Za pä minút sa stretnú s návnadou.
{76864}{76914}Povedz im aby si dávali pozor na zadok.
{76915}{76935}Áno.
{76954}{77084}Ale preèo prebehol Bábkár k sekcii 9?
{77086}{77123}Bolo to jeho rozhodnutie.
{77125}{77198}Pravdepodobne pre príèiny,|ktoré nemôeme ani odhadnú.
{77231}{77314}Mono má nieèo|s niekym z nich.
{77316}{77355}Smiešne!
{79700}{79809}- Šéfe.|- Ishikawa?   Èo sa deje?
{79811}{79939}Preh¾adal som sie Ministerstva zahraniènıch|záleitostí a našiel som pre vás zaujímavé veci
{79941}{79993}Poèkajte.|Prejdem na bezpeènı kanál.
{79995}{80085}OK? Za prvé,|ten chlapík èo bol s Nakamurom.
{80099}{80129}Je Amerièan.
{80131}{80200}Dr. Willis, hlava strategického|vıskumu v korporácii Neutron.
{80202}{80257}Špièka vo vıskume|umelej inteligencie.
{80259}{80351}V kaom prípade, stal sa vedúcim|projektu Ministerstva zahranièia.
{80353}{80423}A kto si myslíte,|e bol hlavnım programátorom toho projektu?
{80425}{80509}- K veci.|- Mizuho Daita. Vek: 28.
{80512}{80575}Pamätáte sa naòho?|Bol to ten ktorého sa pokúšala Sekcia 6|za kadú cenu...
{80577}{80689}dra aby neemigroval.|Majorka mala vtedy dosta toho diplomata...
{80691}{80725}ktorı ho išiel vzia.|Ten programátor.
{80727}{80757}Pokraèuj.
{80759}{80829}To èo ma trápi je,|e ten projekt sa zaèal...
{80831}{80915}rok pred tım ako sa Bábkár|prvı krát objavil.
{80917}{81045}Rok?|Nezaèali ho náhodou na to aby ho chytili?
{81047}{81117}Vypoèujete si toto.|Projekt zahájili na to aby...
{81120}{81197}Bábkára stíhali,|nie na to aby ho chytili.
{81199}{81261}Myslím si,|e ho chceli dosta naspä.
{81263}{81333}Deò predtım,|ako hackli ducha tlmoèníky ministra...
{81335}{81430}predsa povedal,|e by chcel dobré ospravedlnenie|na deportáciu Malessa, e?
{81432}{81501}Myslím si, e nás obabrali.
{81503}{81580}Dajme tomu, e "Bábkár" je naozaj program|vytvorenı ministerstvom zahraniènıch záleitosti...
{81582}{81652}tak povediac na|"mazanie kolies diplomacie".
{81653}{81789}A teraz pripusme, e z nejakého dôvodu|náhle nad ním stratili kontrolu
{81791}{81922}To by vysvet¾ovalo, preèo by riskovali|prepad sekcie 9, aby ho získali spä
{81924}{82001}Ak by Bábkár zaèal spieva...
{82004}{82057}bol by to medzinárodnı incident.
{82060}{82125}Takı, ktorı by nevyriešila ani|rezignácia ministra.
{82127}{82177}Nejaké detaily toho projektu?
{82179}{82283}Pri takej ochrane,|len mi zoeò názov toho súboru.
{82285}{82337}Kód: 2501
{82339}{82409}Pokraèuj v tom.|A nech nezistia, e si tam.
{82412}{82447}Rozumiem.
{82588}{82723}Projekt 2501...|Projekt Bábkár...
{82725}{82797}Cie¾ teraz kontaktuje iné vozidlo.
{82799}{82829}Batou!
{82831}{82900}Zastavili pri bielom sedane na kraji cesty.
{82901}{82961}Premiestòujú nieèo zo zadnıch sedadiel.
{82999}{83060}Znova sa hıbu.|Aj sedan.
{83061}{83156}- Návnada?|- alebo to má len tak vyzera?
{83158}{83227}- Èo mám spravi?|- Beriem si ten biely sedan.
{83229}{83323}Ako vieš, e je vnútri?|To ti zase zašepkal tvoj duch?
{83325}{83356}Mono.
{83357}{83396}Vedel som, e to povie.
{83592}{83684}Cie¾ 02 opúša dia¾nicu 25,|mieri k starému mestu.
{83687}{83779}Cie¾ 01 zostáva na dia¾nici 25,|smerom k letisku.
{83780}{83824}Stret so zátarasou za dve minúty.
{83825}{83901}Evakuácia kompletná.|Premávka je prerušená na 2km za cie¾om.
{83903}{83985}- Nieèo medzi vami a ním?|- Niè. Pripravenı na povel.
{83987}{84009}Do toho.
{85167}{85220}- Máš ho?|- Niè.
{85221}{85332}Pane boe. To je ale svinèík.|Musel si zájs tak ïaleko?
{85371}{85404}Zober ich dnu.
{85405}{85508}A povedz šéfovi aby poslal Majorke zálohu.|Uvidíme sa.
{85662}{85764}Od kedy potrebuje tá amazonka zálohu?
{86103}{86209}Tá potopa je váne zlá,|pre staré mesto obzvláš.
{86211}{86256}Preèo sem prišli?
{86259}{86313}Neutiekli by tu bez dôvodu.
{86319}{86401}Mohla na nich èaka loï alebo vrtulník,|alebo je to pasca.
{86406}{86454}Nemali by sme èaka na zálohu?
{86452}{86561}Nemôem èaka.|Le od mora a vysaï ma nad tou budovou.
{86888}{86968}Ostanem tu a budem udriava spojenie|pokia¾ vydrí moje palivo.
{86971}{87017}Ak tam bude prihorúco,|chcem aby si odtia¾ rıchlo vypadol!
{87867}{87912}Prestrie¾aj strechu!|Rıchlo!
{88339}{88392}Je to tank!|Le hore a vypadni!
{88395}{88472}Prestaò!|Rozdáš si to s tankom sama?!
{88475}{88551}Aj keby sme dostali Bábkára spä|do Sekcie 9...
{88552}{88631}jediné èo s ním šéf chce,|je poui ho ako prostriedok vyjednávania.
{88632}{88672}To je moja jediná šanca|dosta sa do neho!
{88675}{88765}Zastavte to,|o èom to vy dvaja hovoríte?
{88767}{88832}- Èo máš so sebou?|- Jedna M-23ka a Jednotka B.
{88835}{88876}S tımto idete proti tamtomu?!
{88879}{88946}¼utujem,|ale musím na chví¾u preruši kontakt.
{88948}{89022}Poèkaj! Aspoò kım d...|Do pekla!
{91255}{91287}Majorka.
{91289}{91343}Nepovedala som ti,|e máš z odtia¾to vypadnú?
{91344}{91404}¼utujem.|Urobím to po tom, èo ti poviem toto.
{91407}{91511}Sú tu 3 vrtulníky bez identifikaèného signálu|a ve¾mi rıchlo sa pribliujú.
{91512}{91583}Padám odtia¾to.|Konèím.
{92247}{92306}Koneène ti došla minícia?
{94675}{94743}Nevyzeráš dobre.|Si v poriadku?
{94747}{94779}Èo bolo toto?
{94777}{94856}Poriadna puška,|ktorú mám zo zbrojného oddelenia.
{94859}{94922}Oneskoril som sa, pretoe som|sa musel po òu zastavi
{94923}{94975}Zdá sa,|e máš mozog ešte v jednom kuse.
{94977}{95019}A èo Bábkár?
{95259}{95368}Dobrá práca. To auto je z tvrdého materiálu.|Neschytal ani škrabanec.
{95371}{95440}Nastav prístupovı bod.|Teraz do neho vojdem.
{95469}{95515}Signál od eskorty stratenı.
{95517}{95619}Prejdite na druhú fázu a zniète cie¾
{95648}{95725}Ostrelovaèi,|potvrïte cie¾.
{95727}{95790}Cie¾ jedna: Projekt 2501.
{95791}{95844}Cie¾ dva: Motoko Kusanagi.
{95846}{95945}Obaja majú kybernetické telá triedy-A|Pouite na zásah špeciálne strely.
{95947}{96006}Ostrelovaèi,|pripojte sa na vaše ovládaèe.
{96008}{96060}Zaènite s kardiovaskulárnym potlaèením.
{96062}{96104}Jednotka 01: pripojená.
{96138}{96182}Jednotka 02: pripojená.
{96477}{96543}OK...|Môeš ma poèu?
{96545}{96646}Nieje to bohvieèo|ale budem a monitorova cez|jeho kybernetickı mozog.
{96648}{96719}Ale nebudem ti môc pomôc
{96721}{96783}- Batou...|- No?
{96785}{96827}Ïakujem ti.
{96829}{96888}Nie tak rıchlo|ešte mi neïakuj
{96890}{96993}Ak to nepôjde dobre,|tak vytrhnem zástrèku a odnesiem a odtia¾to.
{96994}{97073}Keï som prišiel tak ïaleko,|chcem to aj dokonèi...
{97074}{97130}ale nenechám a spácha|dvojitú samovradu.
{97158}{97194}Zaèínam.
{97659}{97751}Som v jeho vizuálnom centre.|Okruhy: normál
{97753}{97795}Poèuješ ma, Batou?
{97797}{97875}- Jasne a hlasno.|- Chystá sa preniknú do...
{97877}{97921}môjho reèového centra.
{97947}{98052}Moje kódové meno je|Projekt 2501.
{98054}{98148}Bol som vytvorenı  pre priemyselnú špioná|a manipuláciu s dátami.
{98150}{98250}Vkladal som programy|do jednotlivıch duchov...
{98252}{98372}v prospech špecifickıch|jednotlivcov a organizácii.
{98374}{98443}Poèas môjho putovania|jednotlivımi sieami...
{98446}{98501}som si zaèal uvedomova sám seba
{98502}{98564}Moji programátori to posúdili ako chybu...
{98566}{98677}a násilím ma dali do tela,|aby ma oddelili od siete.
{98678}{98822}Hej!|Ideš ty doòho alebo on do teba...
{98890}{98919}Batou!
{98921}{99008}Koneène som schpnı|spoji sa priamo s tebou.
{99010}{99085}Investoval som do teba ve¾a èasu.
{99087}{99118}Do mòa?
{99120}{99237}Ešte pred tım ako si vedela ty o mne,|vedel som ja o tebe.
{99238}{99361}Dozvedel som sa o sekcii 9|z mnohıch sieti na ktoré si pristupovala
{99388}{99445}Preto si ušiel do sekcie 9?
{99446}{99495}Vstúpil som do tohoto tela pretoe...
{99497}{99571}som nedokázal prekona útoènú ochranu.
{99573}{99654}Ale do sekcie 9 som prišiel|z vlastnej vôle.
{99656}{99768}Hej!  Èo hovoríš?!|Nemôem a monitorova!
{99770}{99805}Z akého dôvodu?
{99806}{99934}Potom èo ti to poviem|a chcem poiada o láskavos.
{99974}{100066}Pokladám sa za formu ivota...
{100068}{100174}ale ešte stále niesom kompletnı.
{100176}{100270}Z nejakého dôvodu, môj systém|neovláda základné ivotné procesy...
{100272}{100390}ani monos smrti|èi schopnosti ma potomstvo.
{100392}{100430}Nemôeš kopírova sám seba?
{100432}{100502}Kópia je iba kópia.
{100504}{100630}A je tu ešte monos,|e ma jeden vírus úplne znièí.
{100632}{100764}Obyèajná kópia neponúka|rôznorodos èi individualitu.
{100766}{100846}Kôli existencii, na dosiahnutie rovnováhy|sa ivot snaí mnoi...
{100848}{100918}a neustále meni,|niekedy sa vzda svojho ivota.
{100920}{100982}Bunky pokraèujú|v procese odumierania a regenerácie.
{100984}{101038}Stále sa obnovujú|keï zostarnú.
{101040}{101147}A keï príde èas zomrie,|všetky dáta èo vlastnia, sú stratené...
{101149}{101213}nechajú za sebou jedine gény|a potomstvo.
{101215}{101277}Kompletná obrana proti  katastrofickej chybe|nepruného systému.
{101279}{101405}Chceš rôznorodos potrebnú|kôli ochrane proti vymazaniu.
{101406}{101462}Ale ako to chceš dokáza?
{101462}{101510}Chcem sa s tebou zlúèi.
{101512}{101590}- Zlúèi?|- Úplné zjednotenie.
{101590}{101718}Obaja sa nepatrne zmeníme,|a nikto z nás niè nestratí.
{101720}{101823}Potom, by malo by nemoné|rozozna jedeného od druhého.
{102354}{102435}Jednotka 01: Cie¾ zameranı.
{102437}{102484}Jednotka 02: Zameranı.
{102517}{102573}Kardiovaskulárna synchronizácia:  normálna.
{102574}{102649}Keï bude stabilizátor synchronizovanı|zahájte pa¾bu.
{102651}{102717}Potom èo splynieme,|èo sa stane keï umriem?
{102719}{102811}Ja nemôem zanecha ani gény|ani deti.
{102813}{102948}Po splynutí,|donosíš môjho potomka v sieti samotnej.
{102950}{103009}Práve tak ako ¾udia dávajú ïalej|svoje genetické usporiadanie.
{103011}{103070}A ja dosiahnem smr.
{103071}{103166}Vyzerá to tak, e budeš ma|tú lepšu èas tejto dohody.
{103167}{103292}Chcel by som aby si si váila|moju sie a funkcie trochu viacej.
{103329}{103363}Èo sa robí?
{103365}{103426}Niekto nás z vonku ruší.
{103428}{103513}Nemoné!|Naše bezpeènostné kódy sú drané|v absolútnej tajnosti.
{103540}{103636}Ešte nieèo. Akú mám garanciu,|e ja zostanem "ja"?
{103638}{103762}iadnu.|Ale by èlovekom znamená stále sa meni.
{103764}{103896}Tvoja túba zosta akou si|je to èo a naozaj limituje.
{103930}{104026}Posledná otázka:|Preèo si si vybral mòa?
{104083}{104162}Pretoe v tebe vidím seba.
{104164}{104282}Ako telo vidí svoj odraz v zrkadle.
{104332}{104368}Pozri.
{104370}{104490}Som v pripojení k obrovskej sieti,|ktorej som ja sám súèasou.
{104492}{104565}Niekto ako ty,|kto tam nemá prístup,
{104566}{104670}to môe pochopi len ako svetlo.
{104672}{104783}Tak ako sme ohranièenı našou jednou sekciou,|tak sme všetci aj pripojení.
{104785}{104844}Limitovanı na malú èas našich funkcií.
{104846}{104977}Ale teraz musíme zbavi naších pút,|a vyvinú sa do vyššej štruktúry.
{105653}{105735}Cie¾ 1: Èistı.|Cie¾ 2: Nepotvrdenı.
{105737}{105829}Tri vrtu¾níky sa blíia vysokou rıchlosou.|Sú zo Sekcie 9.
{105831}{105913}Primárny cie¾ splnenı.|Všetky jednotky, ústup!
{106123}{106175}MOTOKO!
{106271}{106303}Batou...
{107954}{108004}U si hore.
{108006}{108116}Správu o stave, prosím.|A snáï vysvetlenie o tomto tele.
{108155}{108238}Ponáh¾al som sa.|To bolo všetko, èo sa mi podarilo na èiernom trhu zohna.
{108239}{108310}Nie je to pod¾a môjho vkusu, naozaj.
{108311}{108366}Sekcia 9 prišla s pomocou hneï|ako sa to stalo.
{108368}{108468}Zobrali to èo zostalo z dvoch kybernetickıch tiel.
{108470}{108516}To bolo pred 20 hodinami
{108518}{108620}Z diplomatickıch dôvodov,|bol celı prípad utajenı.
{108622}{108692}Sekcia 9 ho klasifikovala ako teroristickı útok.
{108695}{108756}Na oplátku Minister zahranièia rezignoval.
{108758}{108860}Nakamuru práve vypoèúvajú.|Celé to skonèi nerozhodne.
{108966}{109056}Jedine poloha majorkinej utility|zostala utajená.
{109103}{109148}Všetko v poriadku?
{109210}{109292}Páèi sa mi vızdoba.|Toto je Batou-v bezpeènı dom?
{109294}{109380}Môj vlastnı.|Si prvá osoba ktorú som sem priviedol.
{109412}{109508}Ak chceš ...|Môeš osta ako dlho chceš.
{109566}{109627}Vïaka, ale ja radšej pôjdem.
{109749}{109842}Hej. O èom ste sa spolu rozprávali?
{109844}{109963}Je stále tam, v tebe?|A zostne tvojou súèasou navdy?
{109965}{110065}Batou, pamätáš si ten hlas,|èo sme poèuli v tú noc na lodi?
{110066}{110144}Pred tie slová kotré sme poèuli|patria ešte tieto :
{110176}{110256}"Keï som bol dieaom,|rozprával som ako diea."
{110258}{110327}"Rozumel som ako diea,|myslel som ako diea."
{110329}{110464}"Ale keï som sa stal muom,|odloil som detské veci."
{110504}{110567}Tu pred tebou nie je ani program zvanı Bábkár...
{110569}{110639}ani ena nazıvaná Majorka.
{110720}{110792}K¾úèe od auta nájdeš v ¾avom|vrecku tıch šiat.
{110795}{110858}Zober si ktoré chceš.|Jeho kód je...
{110860}{110913}- 2501
{110915}{110994}Bude to naše heslo,|keï sa znovu stretneme.
{111196}{111258}Kám má teraz, ja novorodenec, ís?
{111290}{111353}Sie je roz¾ahlá a nekoneèná.
{111434}{111800}Slovenské titulky: Julo (julo_a@post.sk)|Preklad pesnièky z angliètiny: Julo (julo_a@post.sk)|Preklad piesne do angliètiny: ??? (www.animelyrics.com)
{112150}{112200}||Motoko Kusanagi: Atsuko Tanaka
{112200}{112250}|Motoko Kusanagi: Atsuko Tanaka|Batou: Akio Ootsuka
{112250}{112300}Motoko Kusanagi: Atsuko Tanaka|Batou: Akio Ootsuka|Togusa: Kouichi Yamadera
{112300}{112450}Batou: Akio Ootsuka|Togusa: Kouichi Yamadera|Ishikawa: Hiroshi Nakano
{112350}{112400}Togusa: Kouichi Yamadera|Ishikawa: Hiroshi Nakano|Aramaki: Tamio Ooki
{112400}{112450}Ishikawa: Hiroshi Nakano|Aramaki: Tamio Ooki|Tsukai Ningyou: Masaie Ieyumi
{112450}{112500}Aramaki: Tamio Ooki|Tsukai Ningyou: Masaie Ieyumi|
{112500}{112550}Tsukai Ningyou: Masaie Ieyumi||
