{0}{144}V budoucnosti korporaèní sítì dosahují a ke hvìzdám, |elektronické svìtlo vane vesmírem.
{150}{299}Ale ani pokrok ve vıvoji poèítaèù nedokázal zamezit |sporùm mezi národy a etnickımi skupinami.
{422}{487}Všem leteckım jednotkám. |Kód 208...
{489}{531}...v sektoru C-13, Newport City.
{533}{618}Vzdušnı prostor kolem místa bude uzavøen.|Opakuji:
{620}{692}Všem leteckım jednotkám. |Kód 208...
{694}{741}...v sektoru C-13, Newport City.
{743}{817}Vzdušnı prostor kolem místa bude uzavøen. |Opakuji...
{1455}{1507}Puste to z hlavy.
{1509}{1578}Mùete to zkusit znovu |a dorazíte do naší zemì.
{1581}{1624}"Zkusit znovu?"
{1627}{1694}ádnı program nevznikne bez chyb...
{1696}{1792}...ale kadá chyba se dá zpìtnì opravit.|Nemám snad pravdu?
{1794}{1842}Vy tomu nerozumíte.
{1844}{1908}Ještì ani nevíme, jestli |to je programová chyba.
{1910}{1968}Pùvodním úkolem Projektu 2501 bylo---
{1970}{2041}Majore, Sekce 6 je pøipravena...
{2091}{2148}- Majore! |- Jo, slyším.
{2178}{2248}Máš hlavu plnou statickı elektøiny.
{2250}{2301}To je touhle dobou normální.
{2494}{2562}A to nevadí, e se Sekce 9 takhle|nasere do operace Sekce 6?
{2564}{2613}No, ten diplomat je pìkná svinì.
{2615}{2701}I kdy ho teï chytnou pøímo pøi èinu, |tak ho mùou maximálnì vyhostit.
{2702}{2825}Jedinì my si mùem dovolit |zašpinit ruce.
{2826}{2889}U se to rozjelo. |Dostaò nás tam.
{3809}{3861}Coe? Policie?
{4034}{4119}Nechte toho! Kdo vám naøídil støílet? |Odhoïte zbranì!
{4218}{4326}Mám diplomatickou imunitu! |Z èeho mì hodláte obvinit?
{4327}{4383}Transport evidovaného programátora ze zemì...
{4385}{4433}...porušuje zákon o vıvozu zbraní.
{4434}{4527}Klidnì vás mùu obvinit i z únosu.
{4529}{4576}Vydejte nám toho mue.
{4578}{4641}To bohuel nepùjde. |Poádal nás o politickı azyl...
{4642}{4711}...a u podepsal i oficiální ádost.
{4713}{4779}- Kdy?! |- To vám øíkat nemusím.
{4781}{4847}V souladu s mezinárodním právem |mu má zemì mùe...
{4849}{4920}...nabídnout ochranu a volnı |prùchod pøes hranice.
{4922}{4973}Všechny papíry máme na ambasádì.
{4975}{5028}Kopii vám samozøejmì pošleme. |Za pár dní.
{5030}{5090}Víte co dìláte? |Tohle tìko pøeijete.
{5092}{5145}Dejte si pozor na to co øíkáte.
{5146}{5200}Naše zemì je mírumilovná demokracie.
{5202}{5249}Urèitì?
{5291}{5341}Tam v oknì! |Støílejte!
{5541}{5604}Termooptická kamuflá...
{12525}{12586}Je mi potìšením, pane Aramaki.
{12588}{12653}Co mùe ministerstvo zahranièí |pro Sekci 9 udìlat?
{12654}{12703}Co to máte zítra za tajnou schùzku...
{12705}{12753}...se zástupci Gavelské Republiky?
{12754}{12803}Jako obvykle. |Zahranièní pomoc.
{12805}{12874}Nová vláda obnovila ádost, |hned po revoluci.
{12876}{12937}e prı budou více demokratiètí...
{12939}{13006}...ale bude to ta samá verbe |jako pøedtím.
{13008}{13069}Cpát do nich bezdùvodnì peníze, |nikomu nepomùe.
{13070}{13132}Øíkají tomu "reparace za vykoøisování" |a ani nepodìkují--
{13134}{13189}A co s tím hodlá vláda udìlat?
{13190}{13254}Ke všemu k nám vùdce staré chunty...
{13256}{13317}...pøijel poádat o politickı azyl.
{13318}{13363}Plukovník Maless, e?
{13365}{13439}No, a máme ho vyhodit a zaruèit |nové vládì pomoc?
{13441}{13520}Nebo ho prohlásit za uprchlíka |a pomoc zrušit?
{13522}{13588}To není snadné rozhodnutí.
{13590}{13665}Osobnì, pokud bych našel |politicky pøijatelnı dùvod...
{13666}{13747}...bych ho okamitì vyrazil.
{13965}{14048}A díky za pomoc s tím |pašovanım programátorem.
{14050}{14116}Nakamura ze Sekce 6 øíkal, |e byl velice vdìènı.
{14118}{14189}My diplomaté si musíme udret |èisté ruce za kadou cenu.
{14333}{14381}Jsem tam...
{14383}{14450}Ztratili jsme odezvu. |Jak vypadaj vıstupní data?
{14452}{14535}Normálnì. Pøepnìte do módu |virtuálních vzpomínek.
{14568}{14617}Tohle je tlumoènice ministra zahranièí.
{14619}{14727}Je to 23 minut, co nìkdo pøes telefon |hacknul její kybermozek.
{14770}{14835}Jak pøedpokládala vızvìdná sluba...
{14837}{14885}...Loutkáø se zaèal nabourávat...
{14886}{14934}...do kadého terminálu v síti.
{14935}{14994}Podle vzorové analızy |se urèitì pokouší...
{14995}{15069}...sabotovat naše jednání |s Gavelskou Republikou.
{15071}{15145}Sledujeme kadého, kdo se |mìl jednání zúèastnit.
{15147}{15206}Pokouší se hacknout její duši asi proto...
{15207}{15288}...aby pak skrz ní mohl |na jednání zabíjet.
{15290}{15405}Za jak dlouho se mu to povede?
{15406}{15518}Pouívá starı model HA-3. |Take asi tak za dvì hodiny.
{15520}{15566}Pak jí kvùli riziku radši odpojíme.
{15567}{15647}Batou a lshikawa jsou v autì, |lokalizují ten signál.
{15649}{15697}Jeï za nimi.
{16130}{16213}Loutkáø... |To je ten pøízraènej hacker, ejo?
{16214}{16269}Øíká se, e je to Amerièan.
{16270}{16338}Vìk, pohlaví, minulost... |nevíme o nìm vùbec nic.
{16339}{16413}Do konce minulıho roku o nìm |bylo slyšet hlavnì v Evropì.
{16414}{16479}Jsou na nìj vydanı tucty |mezinárodních zatykaèù za...
{16481}{16546}...finanèní manipulace, špioná, |politické inenırství...
{16548}{16633}...terorismus a porušování |kybermozkového soukromí.
{16635}{16712}Povedlo se mu hacknout |duše u tolika lidí...
{16714}{16775}...e si jméno "Loutkáø" právem zaslouí.
{16777}{16841}Tohle je jeho první akce u nás.
{16843}{16946}Kdy je tak dobrej, tak proè |pouívá starou HA-3?
{16948}{17081}Je fakt, e s nìèím novìjším |by nebyl tak nápadnej.
{17083}{17207}Ale zase by to pak spíš vypadalo |na práci plukovníka Malesse.
{17209}{17329}Take, aby od sebe odvrátil podezøení |radši pouívá starej typ. 
{17330}{17437}Anebo nìkdo chce, abysme |si právì tohle mysleli.
{17438}{17520}Maless mùe bejt jenom |další nastrèená figurka.
{17522}{17616}To u trochu pøeháníš. |Máš nìjakı dùkazy?
{17618}{17657}Dùkazy?
{17700}{17772}Jenom jsem zaslechla šepot... |Šepot v mı hlavì.
{17774}{17846}Poøád ještì máš ten revolver?
{17848}{17918}Bojíš se, e se nám všechny |zbranì zaseknou?
{17919}{17963}Mám svùj Matever prostì rád.
{17965}{18015}Co s tebou dìlám mám pocit, e ráe...
{18017}{18071}...je dùleitìjší ne osobní preference.
{18073}{18121}Zvláš, kdy je v sázce |moje vlastní prdel.
{18123}{18187}Pouívej radši Zastabera.
{18189}{18266}Majore, chtìl jsem se zeptat.
{18273}{18359}Proè jsi k vám nechala |pøevelet zrovna mì?
{18361}{18394}Protoe ty jsi ty.
{18396}{18433}Co?
{18435}{18554}Èestnej policajt, èistej záznam. |A máš i normální rodinu.
{18555}{18656}Mimo síovıch implantù |je i tvùj mozek èistej.
{18658}{18717}Mùeme se snait bıt ještì |silnìjší a ještì chytøejší...
{18718}{18786}...ale systém, kde všechny |souèásti reagují stejnì...
{18787}{18866}...je systém s osudovou chybou.
{18867}{18904}A u jde o jednotlivce |nebo organizaci.
{18906}{18963}Pøílišná specializace vede ke smrti.
{18965}{18991}To je všechno.
{19278}{19338}- Hoï sebou! |- Hned!
{19456}{19514}U teï máme 40 sekund zpodìní!
{19515}{19595}- Dej mi ještì pìt sekund. |- Pøi mojí zkurvenı smùle...
{19750}{19788}Hele, promiò.
{19790}{19857}Mùj poslední parák, co ho zavøeli |za práci bez povolení...
{19863}{19922}...byl o dost vìtší pracant ne ty!
{19974}{20037}To se vánì snaíš hacknout |duši svı vlastní eny...
{20039}{20089}...jen abys vìdìl, co se jí honí hlavou?
{20090}{20198}Nikdy na mì nemìla èas |a najednou se chce rozvést.
{20200}{20273}A nejhorší je, e moje jediná dcerka...
{20275}{20331}...si myslí, e její matku podvádím!
{20333}{20414}Kde si vùbec sebral ten |hackovací software?
{20415}{20533}Od jednoho programátora. Moc milej chlápek, |potkal jsem ho v baru.
{20534}{20605}Øek jsem mu, e kvùli právnikovi |enu ani nevidím...
{20606}{20650}...a von øek, e mi pomùe.
{20651}{20716}Prej se mám kvùli poldùm |pøipojoval z rùznejch míst.
{20718}{20762}Chytrej chlap, ne?
{20882}{20942}Ty debile? |Nebaví tì ivot?!
{20944}{21010}Koukám, e nejsme jedinı |co maj zpodìní.
{21099}{21148}Nikde nikdo.
{21150}{21206}Jakej to má smysl? |I kdy vysledujeme volání...
{21207}{21270}...ne sem dojedeme, je ten |chlap stejnì v trapu.
{21272}{21339}- Leze to na nervy, co? |- Pøestaòte reptat!
{21341}{21400}Kusanagi a Togusa jsou na cestì |k dalšímu terminálu.
{21402}{21454}Vy dva zatím prohledejte okolí.
{21456}{21490}A co máme hledat?
{21492}{21544}Cokoliv.
{21546}{21600}Ten starej páprda! |Zrovna nám dávat takovouhle práci?!
{21602}{21652}Poèkejte!
{21654}{21705}Sakra, jsou pryè.
{21707}{21774}Hele, nevidìl jsi tady popeláøskı auto?
{21775}{21823}Kdo to chce vìdìt?
{21825}{21873}Tak vidìl nebo ne?
{21875}{21965}No jo, ale ne jsem sebral smetí, |u byli pryè.
{21966}{22029}Myslel jsem, e to stíhám, |jeden z nich telefonoval--
{22097}{22171}Hele, nemohli byste jim to vzít?
{22173}{22272}Popeláøi? No jasnì... |Zastávky jim trvaj sedm minut.
{22274}{22373}Dispeèink! Chci rozpis tras popeláøù |pro tenhle sektor!
{22649}{22708}Ve vaší oblasti operuje devìt vozù.
{22710}{22772}Váš cíl je sbìrnı nákladní vùz |typ C, èíslo 79.
{22843}{22901}Nech mì øídit.
{23102}{23163}Ishikawo, prohledej byty tìch dvou.
{23165}{23227}Batoue, buï na pøíští |zastávce døív ne oni!
{23229}{23331}Boudou ve spojení s nìkım dalším. |Sledujte je, ale nezasahujte!
{23333}{23381}Rozpis tras zpøístupnìn.
{23383}{23490}Pøístupové terminály zamìøeny. |Cíl se blíí k další zastávce.
{23533}{23590}Potvrzen pøístup pøes HA-3.
{23730}{23774}Promiò, promiò.
{23775}{23848}Co kdybych se teï já postaral |o odpadky a ty o telefon?
{23883}{23906}Co ty na to?
{23908}{23973}Netahej mì do tı svı |zloèineckı frašky.
{23975}{24028}Pro mì je to všechno hromada |kravskejch sraèek...
{24030}{24110}- Ty asi nemáš dìti? |- Vypadám snad na to?
{24111}{24160}Tak tomu nemùeš rozumìt.
{24162}{24218}Moje dcerka pro mì znamená všechno.
{24220}{24293}Jen se podívej. |Není to snad andílek?
{24295}{24369}Nesnášim tyhlety rodinnı fotky.
{24429}{24501}Nojo, náklaïák 79. Zdravim šéfe. |Co se dìje?
{24534}{24615}e policajti hlídaj naší trasu? |A vy chcete vìdìt proè?
{24617}{24667}Jak to mám sakra vìdìt?!
{24754}{24834}Všimli si toho! |Musím varovat pøítele!
{24835}{24897}Musíme vynechat další zastávku!
{24899}{25004}Cíl odboèil z trasy. |Zrychluje k další zastávce.
{25006}{25089}Je to snad kvùli nám? |Nemohl mì pøece vidìt.
{25090}{25157}Asi je vystrašilo moje hledání |v síti sanitárního úøadu.
{25158}{25206}Mìla jsi pouít zadní vrátka.
{25208}{25267}U je pozdì. |Dostaòte je.
{25384}{25438}U mùeš øídit.
{26956}{27031}Jeíši... Udìlal z pancéøovanı |dodávky hromadu sraèek.
{27033}{27114}Bacha, má v tom prùbojnı AP náboje! |Ty dveøe tì neochránìj!
{27115}{27180}AP v samopalu? |Ten chlap je cvok.
{27529}{27577}A ještì navíc má termooptickou kamuflá?!
{27579}{27665}Jdi po nìm! |Já mu nadbìhnu horem!
{27666}{27752}Toguso, jestli iješ tak zatkni |ty dva popeláøe.
{27754}{27783}Rozkaz.
{27813}{27885}Copak se tahle práce nikdy nezmìní?
{29297}{29354}Policie! |Všichni k zemi!
{32249}{32309}Skonèil jsi?
{33562}{33618}Všechno pod kontrolou?
{33619}{33693}Takhle to dopadne, kdy |pøetáhneš munièní limity.
{33694}{33801}Struktura je celá zprohejbaná. |A hlaveò na sraèky.
{33803}{33894}Klidnì mì zatknìte! |Mluvit stejnì nebudu!
{33895}{33943}Mluvit?!
{33986}{34099}Co mi asi prozradí èlovìk, |co nezná ani svoje vlastní jméno?!
{34150}{34203}Oblièej tvé matky.
{34205}{34271}Místo, kde jsi vyrùstal.
{34273}{34330}Vzpomínky z dìtství.
{34346}{34426}Pamatuješ si na nìco z toho?
{34584}{34660}Není nic smutnìjšího, |ne loutka bez duše.
{34662}{34721}Zvláš ten druh, co mu tìlem |proudí èervená krev.
{35100}{35165}A budou ti mui z helikoptéry uvnitø, |tak tam vlítneme.
{35166}{35237}Èeta B pùjde zadem |a zbytek pøedem.
{35238}{35353}Saito, a se tvoji mui |postarají o auta.
{35354}{35413}Zaènìte nahrávat.
{35478}{35548}Zpráva z velení, pane.
{35550}{35621}U víme, kdo je ten mu, |co ho dostala Major.
{35623}{35656}Pokraèujte.
{35658}{35728}Tsuang Gen Fang. |Vìk: 28
{35730}{35853}Ilegální pøistìhovalec. Porušení zákona |o zbraních. Tøi pøípady.
{35855}{35966}Ještì pøed mìsícem se skrıval u partizánù.
{35968}{36050}Pøed tıdnem ho kvùli jeho minulosti...
{36052}{36117}...kontaktovalo vojenské køídlo Gavelské mise...
{36118}{36189}...aby pøerušil naše spoleèné rozhovory.
{36195}{36245}Co je opravdu zaè?
{36247}{36369}Alias: Corgi. |Zamìstnání: obchod s nebezpeènım odpadem.
{36371}{36417}Je to takovej gangster.
{36418}{36529}Prohlídli jsme jeho lokální |policejní záznamy...
{36531}{36621}...ale nenašli ádnou souvislost s Gavelem.
{36622}{36699}Je to jen další loutka |od pøítele Loutkáøe.
{36701}{36747}Jak je na tom lshikawa?
{36749}{36881}Zrovna s Togusou vyslıchají |toho chudáka popeláøe.
{36934}{37003}Tak co Loutkáø?
{37005}{37081}Co si o nìm myslíte?
{37179}{37236}Pøipadá mi sám jako loutka...
{37238}{37309}- Èeta B je na místì. |- Èeta A a C pøipravena!
{37310}{37365}Mùeme se do toho pustit, pane.
{37388}{37436}Do toho.
{37497}{37563}Jak to myslíte,|"Virtuální vzpomínky?"
{37565}{37646}Mluvím o vaší enì, dceøi, |rozvodu, nevìøe...
{37648}{37738}To všechno jsou falešné vzpomínky. |Jako sny.
{37740}{37838}Nìkdo vás zneuil pro nabourání |duše vládního úøedníka.
{37840}{37898}Ne... |To je nesmysl!
{37899}{37956}Byl jsem u tebe doma.
{37958}{38028}Nikdo tam nebyl. |Je to jen jedna místnost.
{38030}{38105}No jistì, pøestìhoval jsem |se kvùli rozvodu--
{38106}{38198}Vdy tam bydlíš u deset let!
{38199}{38264}Nemáš ádnou enu, |ani dítì.
{38266}{38324}Tvá rodina existuje jen v tvı hlavì.
{38366}{38465}Podívejte se. To je ta fotka, |co jste ukazoval parákovi.
{38482}{38541}Koho na ní vidíte?
{38542}{38637}Ale, vdy tam byla. |Moje dceruška...
{38639}{38705}Usmívala se jako andílek...
{38706}{38763}A jak se jmenuje?
{38765}{38829}Kde a kdy jste potkal vaší enu?
{38831}{38905}Jak je to dlouho, |co jste se vzali?
{38907}{38997}Koho vidíte na tom obrázku?
{39029}{39127}Jak se tìch vzpomínek zbavím?
{39129}{39196}Je mi líto. S naší stávající technikou...
{39198}{39248}Sice se u dvì odprogramování povedla...
{39250}{39304}...ale rozhodnì vám to nemùu doporuèit.
{39306}{39348}Je mi to vánì líto.
{39350}{39406}Virtuální vzpomínky, sny...
{39408}{39528}Všechno co víme, je jen realita |a fantazie spojená dohromady.
{39576}{39649}Ale i ta spousta dat, |co celej ivot shromaïuješ...
{39651}{39715}...je ve srovnání se vším úplnı hovno.
{41831}{41914}Kyborg, co volnej èas tráví potápìním...
{41920}{42021}To není normální.|Jak dlouho to dìláš?
{42144}{42253}Copak tì oceán nedìsí? |Kdy ti sele nadnášení...
{42254}{42344}Tak asi umøu. |Nebo bys mì zachránil?
{42372}{42430}Nikdo tì nenutil, |abys jel se mnou.
{42443}{42473}Já jenom--
{43263}{43340}Jak ti je, kdy se takhle potápíš?
{43346}{43425}Ty jsi neprošel potápìèskım vıcvikem?
{43426}{43479}Nemluvím vo nìjakım zkurvenım bazénu.
{43513}{43584}Cítím strach. Úzkost. |Samotu. Temnotu.
{43586}{43648}A snad i... nadìji.
{43650}{43713}Nadìji? |V temnıch moøskıch hlubinách?
{43743}{43793}Víš, jak stoupám k hladinì, cítím...
{43795}{43899}...jakobych se se mohla zmìnit v nìco jiného.
{44042}{44114}Chtìla bys odejít ze Sekce 9?
{44195}{44272}Kolik ti ještì zbıvá z pùvodního tìla?
{44274}{44320}Jsi opilá?
{44322}{44368}To je docela vhodná otázka.
{44370}{44440}Staèí chtít a chemické implanty |v našich tìlech...
{44442}{44543}...spálí veškerı alkohol v krvi |bìhem deseti sekund...
{44545}{44622}Mùeme tady sedìt a opíjet se vìènì.
{44624}{44712}Pokud nìco technologie umoòuje, |èlovìk to udìlá.
{44714}{44784}Máme to snad zakódováno |v podstatì našeho bytí.
{44786}{44844}Ovládání metabolismu. |Zrychlené senzorické reakce.
{44846}{44912}Zlepšené reflexy a ocelové svaly.
{44914}{44982}Nesmírnì vylepšené zpracovávání dat.
{44984}{45095}Všechno díky kybernetickım |mozkùm a tìlùm.
{45097}{45183}Co na tom, e nemùeme |ít bez nároèné údrby?
{45185}{45230}Nemáme si na co stìovat.
{45232}{45334}To neznamená, e jsme |Sekci 9 prodali své duše.
{45336}{45408}Jistì, mùeme odejít, |kdy se nám zachce.
{45410}{45476}Tedy pokud vládì vrátíme |svá kybernetická tìla...
{45482}{45542}...a v nich uloené vzpomínky.
{45544}{45639}Tak, jako je lidské tìlo tvoøeno orgány...
{45641}{45712}...tak jsou potøeba vìci k vytvoøení èlovìka...
{45714}{45754}...jako osobnosti.
{45760}{45795}Oblièej, k rozeznání sebe od ostatních.
{45801}{45834}Hlas, kterım o sobì |mùu pochybovat.
{45840}{45880}Ruka, co vidím kdy se probouzím.
{45886}{45958}Vzpomínky na dìtství, |oèekávání vìcí budoucích.
{45960}{46030}A ještì tu je expandující |datová sí...
{46032}{46091}...do které se mùu napojit.
{46093}{46139}Tohle všechno tvoøí to, |èím jsem.
{46141}{46229}Z toho pramení vìdomí, které |samo sebe nazıvá "já".
{46231}{46326}A zároveò mì mé "já" nutí |pøekonávat limity.
{46455}{46542}A proto lezeš do moøe s tìlem, |které samo klesá ke dnu?
{46544}{46630}Co vidíš v tı èernı vodì?
{46632}{46752}"Prozatím vidíme za sklem jenom temnotu."
{46943}{47006}Tos byla ty?
{52936}{52978}Senzory: restartovány.
{52980}{53030}Náhradní poèítaèové propojení: |v poøádku.
{53032}{53078}Vizuální senzory: zapojeny.
{53079}{53150}- Co signály kybertìla?|- Vıstup: nominální.
{53296}{53360}To jsi nemohla zavolat, |e pøijdeš pozdì?
{53447}{53518}Všechno je pøipraveno. |Máme jí nahodit?
{54079}{54150}Fajn, vypadá to dobøe.|Utni to!
{54151}{54222}Za tøi minuty buïte v mé kanceláøi.
{54323}{54448}Pøišla jsi pozdì, take ti øeknu |co se vlastnì stalo.
{54450}{54544}Jsou to dvì hodiny, co se v továrnì |Megatech Body v Newport City...
{54546}{54607}...sama spustila vıroba kyborgského tìla.
{54609}{54678}Ne vùbec nìkdo zaregistroval |co se dìje...
{54680}{54746}...tak tìlo uteklo.
{54748}{54820}Chvíli potom, co Megatech rozbìhl |pátrací akci...
{54822}{54868}...nám jeden svìdomitej øidiè |náklaïáku oznámil...
{54874}{54971}...e mu pod auto vbìhla nahá ena.
{54973}{55031}No a kvùli tomu jsme tady.
{55033}{55105}Prej je Megatech v tìsnım spojení s vládou...
{55106}{55177}...a všechny vyrobenı tìla jsou tajnı.
{55178}{55226}Jestli to udìlal hacker, |tak musel proplout...
{55227}{55281}...tou vùbec nejlepší ochranou.
{55283}{55333}A to není jedinej problém.
{55407}{55537}I kdy to v hlavì nemá organickej mozek...
{55538}{55609}...tak v tom náhradním, poèítaèovım...
{55610}{55657}...jsme našli nìco jako duši.
{55690}{55749}Vypadá to jako charakteristika, |co dostanete kdy...
{55750}{55809}...pøekopírujete skuteènou duši.
{55810}{55879}Ale nevidím ádnou datovou degradaci, |u kopírování obvyklou.
{55881}{55998}Dokud nezmapujeme ochrannı perimetr |a nevlezeme dovnitø...
{56000}{56062}...tak se pravdu stejnì nedozvíme.
{56064}{56134}Kadopádnì se tomu budu dál vìnovat.
{56136}{56159}Dobrá práce.
{56161}{56231}Je na èase jí rozkuchat.
{56351}{56469}No tak, snad si nemyslíte, |e je v tı vìci duše.
{56470}{56518}To je docela monı.
{56520}{56607}I celuloidovı panenky prı mùou mít duši.
{56609}{56719}A tohle je nacpanı neurotechnickejma krámama.
{56721}{56777}Nedivil bych se, |kdyby to mìlo duši.
{56806}{56880}Ty jsi tady novej, take to nevíš.
{56882}{56976}Megatech dìlal tìlo taky pro Majora.
{56978}{57071}A není jediná. Jedno mám já, |taky lshikawa...
{57073}{57151}...Saito a další. A všichni |potøebujeme údrbu a tak.
{57153}{57222}Mimo tebe a šéfa kadej v Sekci 9...
{57224}{57295}...obèas potøebuje jejich speciální sluby.
{57297}{57408}Snad chápeš, proè se tváøíme |tak trochu ustaranì, Toguso.
{57410}{57479}Loutkáø je velká neznámá, |take nemùeme vìdìt...
{57481}{57527}...jestli v tom tìlu opravdu je.
{57529}{57577}Ale prošel naší obranou...
{57578}{57630}...chránící ty nejtajnìjší soubory...
{57632}{57693}...a poslal skrz program s duší.
{57695}{57792}Ani se to nepokoušel utajit. |O co mu jde?
{57794}{57839}Teï toho nechte.
{57841}{57948}Toguso, jeï to s lshikawou |prohledat do Megatechu...
{57950}{57996}Batoue, odpojil jsem ze sítì...
{57998}{58071}...všechny soubory s údaji o Megatechu.
{58073}{58152}Poøádnì zkontroluj jejich ochranu.
{58154}{58249}Já se zatím budu vìnovat tìlu.|Zítra jdu dovnitø.
{58250}{58346}Urèitì? Mùeme to pøehrát do jinıho tìla |a nechat to plavat.
{58352}{58475}Chci vidìt na vlastní oèi, |co je uvnitø tı vìci.
{58477}{58549}Nepouštìjte tam nikoho |døív ne mì!
{58631}{58667}Co je to s ní?
{58669}{58736}e se od zaèátku loutkáøova pøípadu |chová divnì...
{58738}{58803}...jsem psal ve svım posledním hlášení.
{58805}{58859}Èetl jste ho vùbec?!
{58861}{58932}Šéfe, napadlo vás u nìkdy, |nakolik mùete vìøit...
{58934}{58988}...kyberdoktorùm, co se starají |o váš mozek?
{58990}{59097}Kybermozkové techniky pravidelnì |psychologicky testují.
{59098}{59175}Tìm dùleitìjším kontrolují |i osobní ivot.
{59177}{59265}Ale lidé co provádìjí tyhle testy |jsou jenom lidé.
{59266}{59335}Jak zaèneš pochybovat, |u se toho nezbavíš...
{59337}{59441}Šéfe, je tu pan Nakamura ze Sekce 6.
{59466}{59492}Dobøe, pošlete ho dovnitø.
{59753}{59801}Nebyl ten tlusoch...?
{59802}{59918}Nakamura, šéf Sekce 6. |Úøad pro mezinárodní styk.
{59920}{59977}Toho bìlocha, co s ním byl neznám.
{60042}{60089}Mizím odtud.
{60090}{60151}Øekni lshikawovi, |a je v pohodì, jo?
{60351}{60392}Tak v èem je tvùj problém?
{60394}{60453}Nebyl ten kyborg stejnı jako já?
{60455}{60519}- Ne.|- Nejde o oblièej a postavu.
{60521}{60558}A co teda?
{60560}{60667}Tøeba si to øíkají všichni |úplní kyborgové, jako jsem já.
{60701}{60771}e moje staré já pøed èasem zemøelo...
{60773}{60878}...a já jsem jen náhrada |s umìlım tìlem a mozkem.
{60879}{60976}Ale, moná ádné moje pùvodní já |nikdy neexistovalo.
{60978}{61061}V tı tvı titanovı lebce |máš pøece normální mozek.
{61063}{61127}A chováš se taky jako |skuteènej èlovìk, ne?
{61129}{61203}Není èlovìk, co by vidìl |svùj vlastní mozek.
{61205}{61311}Vìøím ve svou existenci jen na základì toho, |co mi øekne mé okolí.
{61313}{61375}Nevìøíš ve svojí vlastní duši?
{61377}{61448}Ale co kdy dokáe poèítaèovı mozek |vytvoøit duši...
{61450}{61495}...a poskytnout jí útoèištì?
{61497}{61590}Na základì èeho pak vìøí v sebe sama?
{61751}{61789}Hovno!
{61862}{62017}Já vím co se skrıvá v tom tìle!|Vím to díky mojí duši!
{62046}{62117}Oba máme dost práce, take |pùjdu rovnou k vìci.
{62118}{62163}To bych uvítal.
{62165}{62219}Jsem tady pro obsah toho |kyborgského tìla.
{62221}{62299}Zprostíme Sekci 9 vší odpovìdnosti |za tento pøípad.
{62323}{62362}Podpis ministra zahranièí.
{62648}{62740}Bezpeènost, kteøí úøedníci parkují |v podzemní garái?
{62742}{62875}Ty auta patøí Šéfovi Nakamurovi |a doktoru Willisovi.
{62877}{62951}Dejte mi videozáznam jejich |pøíchodu do budovy.
{63148}{63204}Znova, v infraèervenım pohledu.
{63521}{63593}Raz... Dva... Tøi...
{63651}{63777}Pošlete mi záznamy tlakovıch senzorù, |místa B-7 a 8.
{64242}{64338}- Majore, tady Togusa. Kód 0-9.|- Co?
{64340}{64425}Má Nakamura nìjakı zvláštní |typ kybertìla?
{64426}{64468}V Sekci 6 nejsou ádnı kyborgové.
{64474}{64529}Kromì diplomatickıch problémù |jde ještì o údrbu...
{64530}{64584}...pøi cestách do zahranièí.
{64586}{64657}Take, i kdyby byl kyborg ten |jeho spoleèník...
{64658}{64736}...stejnì by dohromady neváili víc |jak pùl tuny, ne?
{64738}{64800}Údaje tlakovıch senzorù... |Gará?
{64802}{64839}Stojí tady dvì auta pro V.I.P.
{64841}{64912}Ani jedno z nich nevypadá, |jako ten typ co se sám øídí.
{64914}{64968}Na záznamu jsou sice vidìt jenom ty dva...
{64970}{65039}...ale víš jak jsou senzory |u dveøí citlivı.
{65041}{65103}Trvá tøi sekundy, |ne se dveøe zavøou.
{65105}{65222}Termooptická kamuflá ve vládní |budovì je nelegální, ne?
{65224}{65289}Je to váné porušení Usnesení |o Národní Bezpeènosti.
{65290}{65407}Sekce 6 se na nìco chystá. |Jsi pøipravenej?
{65409}{65448}Jestli je Matever.
{66351}{66431}Nemusím vám pøipomínat, |jakı by byl podraz...
{66433}{66514}...mi cokoliv zatajit. |Je jedno, jak dùvìrné to mùe bıt.
{66515}{66552}To platí pro nás pro oba.
{66554}{66654}A ministr øíká cokoliv, |ten pøípad patøí Sekci 9.
{66656}{66774}Nespolupracovali bychom, |nemít dobré dùvody.
{66806}{66838}Doktore Willisi?
{66840}{66923}Je to tak. |Urèitì je to on.
{66925}{66960}"On?"
{66962}{67070}Mluví o pùvodním duševním bloku |v originálním tìle.
{67072}{67142}Pohlaví jsme nedefinovali |a oznaèení "on"...
{67144}{67214}...je jen pøezdívka od našeho doktora.
{67216}{67259}Moná je na èase, |abych vás pøedstavil.
{67261}{67378}To je nejunikátnìjší hacker |v historii kyberzloèinu.
{67380}{67427}Loutkáø.
{67465}{67540}Mám dojem, e jste se s ním |u setkali v záleitosti...
{67542}{67639}...ovládnutí duše ministerské |tlumoènice.
{67641}{67715}My ze Sekce 6 Loutkáøe pronásledujeme...
{67717}{67787}...u od první chvíle co se objevil.
{67789}{67861}Zformovali jsme tım vedenı doktorem Willisem...
{67862}{67943}...aby analyzoval všechna data o Loukáøovo...
{67945}{68028}...zloèineckıch snahách a o jeho chování.
{68030}{68123}Pak jsme sestavili anti-loutkáøskou |útoènou obranu...
{68125}{68215}...a nalákali ho do kyborgského tìla
{68217}{68292}Nechali jste ho vstoupit do tìla |s kybermozkem...
{68294}{68345}...a pak jeho skuteèné tìlo zemøít?
{68362}{68400}Pøesnì tak.
{68402}{68468}Mohli jsme ho klidnì vytáhnout tady u vás...
{68470}{68544}...ale pochází z Ameriky. |A kdy na dopadení spolupracujeme...
{68546}{68604}...s Amerièany, tak jsme jim ho chtìli vrátit sami.
{68606}{68644}Urèitì proti tomu nic nenamítáte.
{68646}{68748}Nechat jeho mrtvolu jen tak nìkde hnít.
{68812}{68855}Nebude ádná mrtvola.
{68857}{68958}Protoe dosud nebylo ádné tìlo.
{68960}{69041}Senzory jsou aktivní! |Proè jste mi nic neøekl?!
{69042}{69145}Všechno jsme odpojili. |Má energii z vlastního zdroje.
{69147}{69209}I kdy jsem vstoupit do tohoto tìla protoe...
{69211}{69282}...jsem nebyl schopen prolomit |útoènou obranu Sekce 6...
{69284}{69385}...tak má pøítomnost zde |je aktem mé svobodné vùle.
{69386}{69481}Jako samostatná ivotní forma |ádám o politickı azyl.
{69482}{69514}ivotní forma?
{69516}{69595}To je absurdní! |Jsi jen sám sebe chránící program!
{69597}{69679}Tento argument by se dal pouít i na vaší DNA...
{69681}{69781}...protoe co víc to je, ne sám |sebe zachovávající program.
{69792}{69929}ivot je jako vlna, která |se zrodí v øece informací.
{69930}{70031}Jako typ ivota, kterı pouívá DNA |coby svùj pamìovı systém...
{70033}{70113}...èlovìk získává individualitu |ze svıch vzpomínek.
{70114}{70202}I kdy vzpomínky mohou bıt stejnì |tak jen fantazie...
{70204}{70274}...jsou to právì vzpomínky, |co tvoøí èlovìka.
{70276}{70377}Kdy poèítaèe umonili |externalizovat pamì...
{70378}{70475}...mìli jste si uvìdomit |vyplıvající dùsledky.
{70497}{70554}Nesmysl! |A nám øekneš cokoliv...
{70555}{70615}...nemùeš nijak dokázat, |e jsi opravdu ivı!
{70617}{70692}To není moné nijak dokázat.
{70698}{70831}Ani moderní vìda není schopna definovat |co to ivot je.
{70833}{70889}Kdo k èertu jsi?
{70890}{70993}I kdyby jsi mìl duši, zloèince |na svobodu nepouštíme!
{70995}{71048}Nemysli si, e mùeš dostat azyl!
{71050}{71129}Èas je na mé stranì.
{71130}{71189}I kdy je teï moné mì zabít...
{71190}{71249}...právo této zemì neumoòuje |trest smrti.
{71250}{71321}Napùl nesmrtelná... |Umìlá inteligence?
{71322}{71377}Nejsem U.I.
{71378}{71481}Mé kódové oznaèení je Projekt 2501.
{71526}{71633}Jsem ivoucí forma, zrozená |z moøe informací.
{71882}{71925}Bezpeènost! |Vetøelci!
{72017}{72060}Šéfe, Loutkáø!
{72062}{72169}- Kde je vaše ochranka?!|- Vztyète obranou zeï! Bezpeènost!
{72170}{72202}Bezpeènost, dìlejte!
{72789}{72822}No jó, u jedu!
{72922}{72953}Kreténe!
{73077}{73110}Povedlo se ti to?
{73111}{73197}Byla to kára od Helluvy. |Moje devítka si ani neškrábla.
{73199}{73263}Koneènì se našlo vyuití |pro toho tvıho Matevera.
{73349}{73391}Dobrı... |Na zelenáèe to ujde.
{73393}{73455}Trefil jsem tu štìnici pøesnì na znaèku. |Dost dobrı, ne?
{73457}{73500}Pøíštì tam dostaò alespoò dvì.
{73502}{73575}Tak do toho. Musíme je dohonit døív, |ne si vymìnìj auto.
{73673}{73712}Ministerstvo zahranièních vìcí...
{73714}{73773}...na vás podá oficiální stínost.
{73775}{73839}Ozvìte se mi hned, jak |ho získáte zpìt!
{73841}{73879}ivého, pokud mono.
{73881}{73960}Megatech mùe vdycky |postavit další tìlo.
{74058}{74140}Batou a Togusa sledují ty chlápky |co vzali Loutkáøe.
{74180}{74236}Jsou na dálnici èíslo 25.
{74238}{74308}Co tím myslíš?! |Kdy jste to vìdìli, tak proè--
{74310}{74396}Zatknout je døív, tak nikdy nedokáeme, |e je v tom namoèená Sekce 6.
{74398}{74429}Sekce 6?!
{74431}{74523}Urèitì. Taky pouívají termooptickou |kamuflá typ-2902.
{74525}{74606}Ve vıbavì jí máme jenom my, |vısadkáøi Sekce 4 a Sekce 6.
{74607}{74705}Kdy to tedy shrnu. Sekce 6 |nalákala Loutkáøe do tìla.
{74707}{74833}Ale ten si vybral tìlo Megatechu, |kterı je úzce spojen se Sekcí 9.
{74835}{74890}Potom se Loutkáø prohlásil |za ivotní formu...
{74892}{74965}...a kdy poádal o azyl |tak ho Sekce 6 unesla.
{74967}{75007}Ale proè by to dìlali?
{75009}{75061}Vdy ho mohli dostat hned |jak jsem dostal hlášení.
{75062}{75139}Tøeba dostali strach, co |všechno mùe prozradit.
{75141}{75190}Kdy o tom pøemıšlím, opravdu |øekl nìco zvláštního.
{75192}{75259}"Kódové oznaèení: Projekt 2501."
{75261}{75302}Tohle je úkol pro vás.
{75304}{75405}Co se tıèe útoku na Sekci 9 |a krádee dùkazù...
{75406}{75458}- Máte moje svolení.|- Kopni do vrtule!
{75608}{75662}Kusanagi! Ještì nìco!
{75664}{75743}Za nepovolenou akci mì mùete |potrestat a se vrátím.
{75745}{75831}Pokud nepùjde Loutkáøe dostat zpátky, |chci ho radši mrtvıho.
{75833}{75870}Spolehlivì.
{75910}{75949}Tak co?!
{75951}{75981}Rozkaz.
{76023}{76094}Kontaktujte letištì a pozastavte odlety...
{76096}{76166}...úøedníkù ministerstva zahranièí |nebo americkıch diplomatù.
{76167}{76205}Uzavøete dálnice a postavte zátarasy.
{76206}{76252}Nasaïte na to všechny lidi.
{76254}{76297}A pošlete mi sem lshikawu!
{76299}{76404}Zjistìte mi, kdo byl ten bìloch s Nakamurou.
{76406}{76501}A pátrejte v databázi ministerstva |zahranièí po èemkoliv...
{76502}{76564}...s názvem "Projekt 2501."
{76709}{76757}U se ozval náš pøepadovı oddíl?
{76758}{76812}Pøed minutou si vymìnili auta.
{76814}{76857}Za pìt minut se setkají z návnadou.
{76863}{76905}A a si nezapomenou hlídat záda.
{76911}{76951}Ano, pane.
{76953}{77083}Ale proè Loutkáø utekl k Sekci 9?
{77085}{77122}Bylo to jeho rozhodnutí.
{77124}{77197}Jeho dùvody my tìko kdy pochopíme.
{77230}{77313}Tøeba nìkomu ze Sekce 9 nìco chtìl.
{77315}{77354}To je absurdní!
{79714}{79808}- Šéfe.|- Ishikawo? Tak co?
{79810}{79938}V síti ministerstva zahranièí jsem našel |nìco zajímavého.
{79940}{79992}Vydr, pøepnu na bezpeènı kanál.
{79994}{80084}Mùu? Nejdøív ten chlápek s Nakamurou.
{80098}{80128}Je to Amerièan.
{80130}{80199}Doktor Willis, vedoucí |vızkumu v Neutron Corp.
{80201}{80256}Jeden z nejlepších vìdcù kolem U.I.
{80258}{80350}Kadopádnì z nìj udìlali šéfa projektu |ministerstva zahranièí.
{80352}{80422}A kdo myslíte, e dìlal vedoucího programátora?
{80424}{80509}- K vìci.|- Mizuho Daita. Vìk: 28.
{80511}{80574}Pamatujete si na nìj? Je to ten, |co se ho Sekce 6...
{80576}{80689}...zachránila pøed únosem. Major |musela sejmout toho diplomata...
{80690}{80725}...co se to snail oficiálnì posvìtit.
{80726}{80756}Pokraèuj.
{80758}{80828}Zajímavìjší ale je, e ten |projekt byl zahájen...
{80830}{80914}...rok pøed prvním objevením Loutkáøe.
{80916}{81044}Rok pøed? Nebylo to snad odstartováno |kvùli jeho odchycení?
{81046}{81117}Jak tomu rozumím, projekt |sice vznikl kvùli sledování...
{81119}{81196}...Loutkáøe, ale nikdy nemìl |za úkol ho chytit.
{81198}{81260}Myslím, e ho chtìjí dostat zpátky.
{81262}{81332}Den pøed tím nabouráním do |ministrovo tlumoènice...
{81334}{81429}...vám ministr øekl, e hledá dùvod |k vyhoštìní Malesse, je to tak?
{81431}{81500}Myslím, e nás nìkdo tahá za nos.
{81502}{81579}Pøedpokládejme, e "Loutkáø" je |ministerstvem vytvoøenı program...
{81581}{81651}...k promazání koleèek diplomacie, |obraznì øeèeno.
{81653}{81788}Dále pøedpokládejme, e se prostì |vymkl jejich kontrole.
{81790}{81921}To by vysvìtlilo, proè Sekce 6 |riskovala útok na Sekci 9.
{81923}{82001}Kdyby Loutkáø zaèal mluvit...
{82003}{82057}...mohl by propuknout mezinárodní skandál.
{82059}{82124}Skandál, co by ho neurovnala ani |rezignace ministra zahranièí.
{82126}{82177}Víš o tom projektu ještì nìco?
{82178}{82275}Jejich ochrana mì zatím pustila jenom k názvu.
{82284}{82336}Kód: 2501
{82338}{82409}Pokraèuj dál. |A a si tì tam nikdo nevšimne.
{82411}{82446}Rozkaz.
{82587}{82722}Projekt 2501...|Projekt Loutkáø...
{82724}{82796}Cíl se dostal do kontaktu |s jinım vozidlem.
{82798}{82828}Batoue!
{82830}{82899}Zastavili u kraje, |vedle bílıho sedanu.
{82901}{82960}Pøenášejí nìco ze zadního sedadla.
{82998}{83059}Znova se rozjeli.|Take je to v tom sedanu.
{83061}{83155}- Návnada?|- Nebo nìco, co tak má vypadat.
{83157}{83226}- Co mám dìlat?|- Já si vezmu ten bílı sedan.
{83228}{83322}Jak víš, e tam je?|Zase šepot v hlavì?
{83324}{83355}Moná.
{83357}{83395}Vìdìl jsem, e to øekne.
{83591}{83684}Cíl èíslo 2 opouští dálnici 25, |míøí smìrem ke starému mìstu.
{83686}{83778}Cíl èíslo 1 zùstal na dálnici 25, |jede smìrem k letišti.
{83780}{83823}Za dvì minuty narazí na zátaras.
{83825}{83901}Evakuace ukonèena, do dvou km |za cílem není ádná doprava.
{83902}{83985}- Je mezi váma nìkdo?|- Nikdo. Èekám na pokyn.
{83986}{84009}Udìlej to.
{85166}{85219}- Tak co, máš ho?|- Samá voda.
{85221}{85331}Jeíši, takovej bordel!|Museli jste zajít tak daleko?
{85370}{85403}Zatkni je.
{85405}{85507}A øekni šéfovi, a pošle Majorovi |nìjakı posily. Mìj se.
{85661}{85763}Odkdy ta amazonka potøebuje |nìjakou pomoc?
{86102}{86209}Je to tady dìsnì zatopenı. |Dost i na starı mìsto...
{86210}{86252}Proè jeli zrovna sem?
{86258}{86313}Urèitì by sem neutekli bezdùvodnì.
{86315}{86401}Buï èekají na loï nebo vrtulník, |anebo je to bouda.
{86402}{86450}Nepoèkáme radši na posily?
{86451}{86561}Nemùu èekat. Nale tam od moøe |a vysaï mì nad tím barákem.
{86888}{86964}Poèkám tady dokud mi vydrí palivo.
{86970}{87017}Kdy se nìco podìlá, tak |odtud rychle vypadni!
{87866}{87912}Rozstøílej strop!|Hned!
{88338}{88392}Je to tank!|Zmiz odsud!
{88394}{88472}Poèkej chvíli! |Ty chceš ten tank dostat úplnì sama?
{88474}{88550}Kdybysme vrátili Loutkáøe do Sekce 9...
{88552}{88630}...tak ho šéf pouije jedinì na vyjednávání.
{88632}{88672}Tohle je jediná monost, jak |se do nìj mùu dostat!
{88674}{88765}Hej, vo èem to sakra mluvíte?
{88766}{88832}- Co tam máš za vıbavu?|- M-23 a Unit B.
{88834}{88876}Proti tanku s tímhle?
{88878}{88945}Promiò, musím konèit.
{88947}{89021}Poèkej! Vydr aspoò ne--|Blbá èubka!
{91254}{91283}Majore.
{91289}{91342}Neøíkala jsem, abys vypadnul?
{91344}{91404}Hned po tomhle.
{91406}{91510}Letí sem tøi neregistrované vrtulníky.
{91512}{91582}Mizím pryè. |Konec.
{92246}{92305}Došli ti koneènì náboje?
{94678}{94743}Ty jsi naprosto šílená, víš o tom?|Jinak dobrı?
{94745}{94775}Co to bylo?
{94777}{94856}Kurevsky velká bouchaèka, |vypùjèená ze zbrojní divize.
{94858}{94921}Kvùli tomu mi to trvalo tak dlouho.
{94923}{94975}Mozek máš ještì v jednom kuse.
{94977}{95019}A co Loutkáø?
{95258}{95368}Ještìe je ta kára tak odolná. |Nemá ani škrábnutí.
{95370}{95440}Pøiprav všechno k propojení. |Pùjdu dovnitø.
{95469}{95515}Ztratili jsme spojení s eskortou.
{95517}{95619}Pøejdìte na plán B a zniète ten cíl.
{95648}{95725}Odstøelovaèi, potvrïte cíle.
{95727}{95789}Cíl jedna: Projekt 2501.
{95791}{95844}Cíl dvì: Motoko Kusanagi.
{95846}{95945}Oba mají kyborgská tìla tøídy A, |pouijte flešetové náboje.
{95947}{96006}Odstøelovaèi, zapojte se |do svıch ovladaèù.
{96008}{96060}Spuste kardiovaskulární odrušení.
{96062}{96104}Jednotka 01: zapojen.
{96138}{96182}Jednotka 02: zapojen.
{96477}{96543}Take... Slyšíš mì?
{96545}{96646}Za moc to nestojí, ale mùu |tì alespoò sledovat.
{96648}{96719}Nemùu ti tam ale krejt záda.
{96721}{96774}- Batoue...|- Co?
{96785}{96827}Díky.
{96829}{96888}Ještì mi nedìkuj.
{96890}{96993}Jestli se nìco posere, vytáhnu |prostì zástrèku a zmizíme pryè.
{96994}{97073}Kdy u jsem se dostal tak daleko, |chci to vidìt a do konce...
{97074}{97129}...ale nenechám vás dva spáchat |dvojitou sebevradu.
{97158}{97193}Jdu na to.
{97659}{97751}Jsem v jeho zrakovém centru.|Cirkáda: normální.
{97753}{97795}Slyšíš mì, Batoue?
{97797}{97875}- Èistì a jasnì.|- Snaí se proniknout...
{97877}{97921}...do jejího øeèového centra.
{97947}{98052}Mé kódové oznaèení |je Projekt 2501.
{98054}{98148}Byl jsem stvoøen pro prùmyslovou |špioná a datovou manipulaci.
{98150}{98250}Vkládal jsem programy do duší jednotlivcù...
{98252}{98372}...za úèelem zisku jistıch osob a organizací.
{98374}{98443}Pøi svém putování skrze rozlièné sítì...
{98445}{98501}...jsem si však uvìdomil sám sebe.
{98502}{98564}Moji programátoøi to oznaèili |za chybu programu...
{98566}{98677}...a donutili mì se pøesunout |ze sítì do tìla.
{98678}{98821}Hej! Dostáváš se ty do nìj |nebo on do tebe--
{98890}{98919}Batoue!
{98921}{99008}Naštìstí jsem schopen se s tebou spojit.
{99010}{99085}Investoval jsem do tebe u hodnì èasu.
{99087}{99118}Do mì?
{99120}{99237}Døív, ne si ty poznala mne, |znal jsem u já tebe.
{99238}{99361}Díky tvım pøístupùm do sítì |jsem se dozvìdìl o Sekci 9.
{99388}{99445}Proto jsi tedy utekl do Sekce 9?
{99446}{99495}Vstoupil jsem do tohoto tìla, protoe...
{99497}{99571}...jsem nemohl prolomit útoènou |obranu Sekce 6.
{99573}{99654}Ale do Sekce 9 jsem pøišel |ze své svobodné vùle.
{99656}{99768}Hej! Co to øíkáš?! |Nic neslyším!
{99770}{99805}Z jakého dùvodu?
{99806}{99934}A ti øeknu své dùvody, chtìl |bych tì poádat o laskavost.
{99974}{100066}Øíkám o sobì, e jsem ivotní forma...
{100068}{100174}...ale ještì zdaleka nejsem hotov.
{100176}{100270}Z nìjakého dùvodu mùj systém postrádá |základní ivotní procesy...
{100272}{100390}...jako jsou smrt a schopnost |zanechat po sobì potomky.
{100392}{100430}Copak se nemùeš zkopírovat?
{100432}{100502}Kopie je pouhá kopie.
{100504}{100630}I jeden jedinı virus mì mùe zcela znièit.
{100632}{100764}Obyèejná kopie neposkytuje ádnou |individualitu.
{100766}{100846}Aby mohl ivot existovat a dosáhnout |rovnováhy, tak se mnoí...
{100848}{100918}...a pravidelnì obmìòuje v èase mu vymìøeném.
{100920}{100982}Buòky v procesu smrti a regenerace pokraèují.
{100984}{101038}Neustále odumírají a znovu se rodí.
{101040}{101147}A kdy pøijde èas zemøít, jsou všechna |nahromadìná data ztracena...
{101149}{101213}...a zùstávají zde jen geny a dìti.
{101215}{101277}To vše chrání ivot pøed katastrofickım |selháním nemìnného systému.
{101279}{101405}Touíš po rozdílnosti, potøebuješ |ji jako ochranu pøed vyhynutím.
{101406}{101461}Ale jak ji získáš?
{101462}{101510}Chci se s tebou slouèit.
{101512}{101589}- Slouèit?|- Kompletnì splynout.
{101590}{101718}Oba se sice zmìníme, ale ani |jeden z nás o nic nepøijde.
{101720}{101823}Potom bude nemoné rozeznat |jednoho od druhého.
{102354}{102435}Jednotka 01: cíl zamìøen.
{102437}{102485}Jednotka 02: zamìøen.
{102517}{102573}Kardiovaskulární synchronizace: nominální.
{102574}{102649}Jakmile bude synchronizace |kompletní, tak støílejte.
{102651}{102717}Ale i kdy se spojíme, |co se stane a zemøu?
{102719}{102811}Nemùu mít dìti a |nemám ani ádné geny.
{102813}{102948}A se spojíme, pøeneseš |mé dìti pøímo do sítì.
{102950}{103009}Stejnì jako pøedávají svou |genetickou strukturu lidé.
{103011}{103070}A já koneènì dosáhnu smrti.
{103071}{103166}Zdá se, e ty jsi ten, co |na tomhle obchodu vydìlá.
{103167}{103292}Mìla by si více ocenit mé |schopnosti v rámci sítì.
{103329}{103363}Co se dìje?
{103365}{103426}Nìkdo zvenku nás blokuje.
{103428}{103513}To je nemoné! Naše blokovací kódy |jsou absolutnì tajné!
{103554}{103636}Ještì nìco. Co mi zaruèí, |e zùstanu sama sebou?
{103638}{103762}Nic. Ale èlovìk se pøece neustále vyvíjí.
{103764}{103896}Tvá touha zùstat stále beze zmìny |tì absolutnì omezuje.
{103930}{104026}Poslední otázka: |Proè sis vybral právì mnì?
{104083}{104162}Protoe v tobì vidím sám sebe.
{104164}{104282}Tak jak tìlo vidí svùj odraz v zrcadle.
{104332}{104368}Dívej se.
{104370}{104490}Jsem napojen do sítì, |její jsem sám souèástí.
{104492}{104565}Nìkomu jako ty, bez mıch schopností...
{104566}{104670}...to mùe pøipadat jen jako svìtlo.
{104672}{104783}Jsme spojeni, ale oba nás naše |oddìlená existence svazuje.
{104785}{104844}Mùeme vyuít jen zlomku našich |skuteènıch schopností.
{104846}{104977}Je na èase shodit ta pouta |a postoupit na vyšší úroveò bytí.
{105653}{105735}Cíl 1: Èistı zásah.|Cíl 2: Nepotvrzen.
{105737}{105829}Rychle se blíí tøi vrtulníky. |Patøí pod Sekci 9.
{105831}{105913}Primární úkol je splnìn.|Všechny jednotky, odlet!
{106123}{106175}MOTOKO!
{106271}{106303}Batoue...
{107958}{108004}U jsi vzhùru.
{108006}{108117}Stavové hlášení, prosím. |A vysvìtlení ohlednì tohoto tìla.
{108155}{108238}Nebyl èas. Na èernım trhu se nic |lepšího sehnat nedalo.
{108239}{108310}Nic podle mıho gusta, vánì.
{108311}{108366}Pomoc od Sekce 9 dorazila hned po tom.
{108368}{108468}Posbírali dvì tìla, pomlácenıho |Batoua a odvezli nás domù.
{108470}{108517}To bylo pøed dvaceti hodinama.
{108518}{108620}Kvùli diplomatickejm dùvodùm |se všechno ututlalo.
{108622}{108693}Sekce 9 to ohlásila jako |teroristickej útok.
{108695}{108756}Na oplátku podal ministr |zahranièí rezignaci.
{108758}{108861}Nakamura musel hodnì vysvìtlovat. |Nakonec to vyznìlo do ztracena.
{108966}{109057}Jenom mozek z Majorova tìla |se nìjak nemùe najít.
{109103}{109148}Jsi v pohodì?
{109210}{109292}Líbí se mi to tady.|To je tvoje skrıš?
{109294}{109380}Moje vlastní. |Ty jsi první èlovìk co tu kdy byl.
{109412}{109508}Jestli chceš... Zùstaò tak dlouho |jak budeš potøebovat.
{109566}{109627}Díky, ale radši pùjdu.
{109749}{109842}Hej. O èem jste to vy dva mluvili?
{109844}{109963}Je tam nìkde, v tobì?
{109965}{110065}Batoue, pamatuješ na ten hlas, |tenkrát v noci, na lodi?
{110066}{110145}Pøed ta slova patøí tato:
{110177}{110257}"Kdy jsem byl dítì, |mluvil jsem jako dítì."
{110258}{110327}"Myslel jsem jako dítì, |chápal jsem jako dítì."
{110329}{110465}"Ale kdy jsem dospìl, |zanechal jsem dìtskıch vìcí."
{110504}{110567}Pøed tebou nestojí program zvanı Loutkáø...
{110569}{110639}...a ani ena, které jsi øíkal Major.
{110720}{110793}V levé kapse najdeš klíèe od auta.
{110795}{110858}Vyber si jakı chceš. |Kód je...
{110860}{110913}...2501?
{110915}{110994}Bude to naše heslo, a se |zase nìkdy setkáme.
{111196}{111258}Kam bych teï mìla jít?
{111290}{111353}Sí je neomezená a nekoneèná.
{111968}{112328}CZ Subtitles (1999-2001) by: |Toy Tec-Oil from Disharmony Visage
{112330}{112689}email: |Toy_Tec-Oil@seznam.cz
