{0}{0}23.967
{36}{209}Jedno setkání vede ke dvìma láskám, a tøi|tøesoucí se srdce zahrála nìnou melodii.
{209}{272}Kasuga Kyosuke, 15 let...
{291}{349}...proívá mládí!
{392}{488}Od otaku pro otaku|NENÍ URÈENO KE KOMERÈNÍMU VYUITÍ!
{570}{715}Pneumatiky køièí zrychlením.
{715}{815}Nechávám tebe, cizince,|vstoupit do kupé a vystupuji.
{815}{879}Before the summer takes you.  Right, now.
{879}{1009}Zavíráš dveøe, aby ses zbavil|stínù, které nás pronásledují.
{1021}{1138}Øíkáš "Kamkoliv, šlápni na to!"
{1183}{1242}Setkali jsme se na dálnièní køiovatce.
{1252}{1329}Ve chvíli, kdy byl vidìt pøístav...
{1329}{1430}jsem si uvìdomil, e jsem se zamiloval.
{1530}{1747}Namísto polibku chceš nìhu.
{1825}{2031}Zakryty nevinností|byly tvé oèi dospìlé.
{2080}{2195}...fall in your life...
{2195}{2332}Namísto nìhy chceš polibek.
{2364}{2428}...lost in the light...
{2428}{2509}Zmìnila ses.
{2509}{2576}Tvùj novı vzhled...
{2576}{2626}...je dospìlı.
{2672}{2740}KIMAGURE ORANGE ROAD
{2841}{2972}EPIZODA #3|Nálada kolísá.|První rande nepoèká.
{3887}{3932}Ayukawo.
{4088}{4128}Co to...?
{4128}{4156}Hej, Kasugo!
{4202}{4245}Co je s tebou?
{4245}{4281}Nic!
{4281}{4371}Myslels na nìco zvrhlého, co?
{4386}{4443}Kadopádnì jdeš s námi?
{4443}{4496}Nebudeš zklamanı.
{4518}{4577}O jednoho víc!
{4591}{4608}Hej!
{5044}{5106}Tadá!|Jsme na místì!
{5201}{5285}No a? Vdy je to obyèejnı fast food.
{5285}{5340}Jen poèkej, a to uvidíš uvnitø...
{5410}{5431}Aerobik
{5441}{5479}Vítejte!
{5589}{5650}Dìje se nìco?
{5650}{5703}To obleèení...
{5703}{5775}Veškerá obsluha zde chodí v trikotech.
{5775}{5804}Pìkné, e?
{5820}{5875}Dám si hamburger a malou colu.
{5875}{5936}Ah, já cheesburger a støední pomeranèovı dus.
{5954}{6000}A vy, pane?
{6000}{6028}Já?
{6028}{6076}Hamburger a mléènı shake.
{6076}{6172}Dìkuji. Posaïte se prosím nahoøe.
{6198}{6225}Jdeme.
{6225}{6258}Pospìš si.
{6469}{6497}Ta druhá zprava...
{6497}{6550}Ta tøetí zleva...
{6550}{6602}A vıš zvedat nohy!
{6708}{6755}To je všechno?
{7047}{7114}Proto jste mì sem táhli?
{7114}{7143}Pìkné, e?
{7143}{7181}Dìkuju.
{7185}{7262}Ah, máme ještì nìco skvìlého...
{7262}{7293}Tady.
{7334}{7415}Volná dámská vstupenka|na "Disco Moebius"?
{7453}{7511}Není to místo, kam chodí místní "vıkvìt"??
{7511}{7597}Ale prosimtì.
{7597}{7685}Slyšel jsem, e tam èasto chodí Ayukawa,|take to nemùe bıt úplnì špatné.
{7712}{7745}Ayukawa na diskotéce...
{7745}{7860}Plouáky.|Tváø na tváø, tìlo na tìlo...
{7914}{7941}Ayukawa...
{8409}{8464}Hej, Kasugo. Kasugo!
{8464}{8488}HEJ.
{8503}{8632}To není špatnı nápad, co? Pùjdeme|a pozveme i Kurumi a Manami!
{8648}{8696}To není dobrı nápad.
{8696}{8804}Jsou to ještì dìti a stejnì nejsou diskotékové typy.
{8804}{8848}Fakt?|Ale...
{8983}{9043}Já chci rùovı trikot!
{9043}{9091}Já bych se cítila trapnì!
{9091}{9163}Jedem!
{9586}{9619}Nedívat se, nedívat se!
{9825}{9853}COE?!
{9906}{9966}Lístek na jednu hodinu zdarma?!
{9966}{10054}Mhm. Byla to jen jedna hodina a zadarmo, take...
{10054}{10090}Samozøejmì!
{10090}{10195}Bylo to tak trapné, vidìt vás,|jak si tam takhle tancujete!
{10408}{10466}Øíkala jsem ti, e bude naštvanı.
{10466}{10525}Ale bylo to bezva.
{10686}{10716}Do háje.
{10716}{10776}A u vás tam nevidím.
{10776}{10800}Ano!
{10831}{10975}Ale sám jsem Komatsuovu pozvání neodolal a vzal si od nìho lístky.
{10975}{11140}Bylo to ode mì dost nezodpovìdné,|take vlastnì nemám právo sestry pouèovat.
{11996}{12036}Brácho!
{12036}{12101}Brácho, brácho!
{12125}{12168}Vstávat!
{12209}{12235}Co se dìje?
{12235}{12275}Co je tohle za lístek?
{12275}{12335}Nic, nic!
{12335}{12378}Kde je ten druhı?
{12378}{12406}Vìdìla jsem to!
{12406}{12431}Vìdìla co?
{12431}{12516}Kurumi pøed chvílí odešla, øíkala,|e jde ke kamarádce.
{12516}{12540}COE?!
{12918}{12985}Mají zpodìní...
{13061}{13092}Hej, Hatto!
{13109}{13138}Pardon pardon...
{13150}{13210}Nebylo lehké mamce zdrhnout.
{13339}{13406}Co Kurumi a Manami?
{13439}{13475}To je... ?!
{13490}{13578}Hej, co je to?
{13578}{13602}Co?
{13616}{13769}No, jdeme na diskotéku, tak jsem myslel,|e jich pár pøinesu na párty.
{13769}{13812}Ah, aha, jo tak...
{13812}{13867}Co sis myslel?
{13867}{13922}Je to normální balónek.
{13942}{13980}To jsem zvìdavı, kdy se objeví.
{14092}{14135}Vítejte.
{14147}{14220}Ah, dìkuji, jsem tu poprvé a mìl jsem|drobnı problém se schody...
{14814}{14903}Dobøe dobøe, jedem!
{14917}{15027}Bylo to tak hluèné místo a fakt,|e sem Ayukawa èasto chodí...
{15299}{15422}Kadopádnì to není jako ve škole|nebo kdy nìkde jsme.
{15422}{15536}Ayukawinu druhou stránku vùbec neznám.
{15576}{15619}Debile.
{15619}{15643}Uh?
{15672}{15706}Hikaru!
{15713}{15746}Zlato?!
{15746}{15802}Wow! Vánì se mi to nezdá?!
{15840}{15917}On také chodí po diskotékách?
{15917}{15978}Kdy je tu ona, mohla by tu...
{15978}{16038}Ahoj, jsi tu sama?
{16038}{16112}Ne, jsem tu s Madokou,|támhle je.
{16249}{16277}Ayukawa...
{16368}{16423}Ayukawa pije...
{16459}{16523}Zatanèíš si se mnou?
{16523}{16581}Nepøišel jsem sem...
{16662}{16758}Oukej, oukej, dámy a pánové...
{16758}{16901}Je èas si odpoèinout a dostat se do varu.|Je tu to, na co jste èekali...
{16901}{16937}Èas zatanèit si "tváø na tváø"!
{17075}{17169}Umíš tancovat plouáky?
{17212}{17264}Je to jednoduché, takhle...
{17451}{17568}Cítil jsem neuvìøitelnou, sladkou vùni a...
{17924}{17986}Dìje se nìco, zlato?
{17986}{18036}Ne, nic.
{18168}{18221}e tu mají skvìlou pizzu?
{18221}{18285}Mhm. A dojíme tuhle, pùjdeme.
{18354}{18424}Proè musí tancovat s takovımhle tıpkem.
{18431}{18598}Na druhou stranu, já pøed ní tancuji|plouák s jinou holkou.
{18610}{18710}Nemám právo cokoli øíkat.
{18754}{18933}Mìl jsem to v hlavì úplnì rozházené...
{18933}{19017}...a co Hikaru v tu chvíli øekla...
{19017}{19112}...mì velmi rozrušilo, ale...
{19112}{19208}Ne, mìl bych bıt šastnı...
{19208}{19315}...ale já si v tu chvíli nebyl jistı.
{19542}{19633}Kasuga a ostatní jdou pozdì.
{19633}{19720}Ten blb, já ho zabiju!
{19743}{19861}Titulky: Princ Chaosu              princCh@seznam.cz|NENÍ URÈENO KE KOMERÈNÍMU VYUITÍ!
{20253}{20355}Bylo to tak náhlé,|byl jsem pøekvapenı...
{20355}{20380}Ale...
{20401}{20420}Rande?!
{20420}{20451}Ano?
{20451}{20489}Zítra v jednu...
{20540}{20585}Super, lucky!
{20585}{20638}Jsem tak šastná!
{20641}{20676}Lucky, huh?
{20740}{20778}12 hodin?
{20778}{20824}Jsem tu o hodinu døíve.
{20824}{20912}No co, je to moje první rande.
{21020}{21077}Tady v jednu...
{21424}{21473}Támhle je jezero.
{21473}{21555}Mám èas. Mohl bych se projet na loïce.
{21587}{21646}Coe?! Odešel?!
{21654}{21711}Do háje, slíbil, e...
{21711}{21732}Divné...
{21747}{21802}Co slíbil?
{21854}{21901}Jo aha.|Mhm, slíbil.
{21901}{21938}To je problém, ne?
{21938}{22005}Chtìli jsme ho pozvat.
{22005}{22038}Jídlo?!
{22038}{22125}Mhm, máme pár kupónkù|na pizzu zdarma.
{22153}{22237}PIZZA?!!  Manami,|pojïme, pojïme!
{22282}{22316}Co se dìje?
{22430}{22478}Co si myslíš?
{23031}{23055}To je pøíjemné...
{23277}{23341}Proè Ayukawa...
{23886}{23917}Ayukawa!
{23975}{24104}Proè jsem se v tu chvíli schoval?
{24240}{24328}No tak, èekal jsem na tebe|venku takovou dobu.
{24328}{24391}Jen tak sis se mnou pohrála.
{24391}{24463}Ale odpustím ti, protoe máš tak hezkı oblièejík...
{24463}{24580}...pokud si se mnou dneska vyrazíš.|Co ty na to?
{24647}{24735}Pojïme, vím o prima místu.
{24747}{24823}To, e si s tebou jednou zatancuji, neznamená,|e mám zájem!
{24852}{24919}Co jsi to øíkala?|Zopakuj to.
{24919}{25000}Dìlá, e mì nemá ráda,|ale skuteènost je opaèná...
{25000}{25041}Viï?
{25055}{25082}Zmiz.
{25151}{25187}Ty dìvko!
{25187}{25292}Já tì nauèím!
{25345}{25376}Oh ne!
{25393}{25436}Radši abych tam šel!
{25878}{25904}Ayukawo!
{25904}{25947}Hned jsem tam!
{26033}{26057}Co?!
{26100}{26141}Kasugo...
{26141}{26169}Co tady dìláš?
{26169}{26224}Ale...
{26506}{26559}Manami, není to skvìlé?
{26559}{26621}Ale Komatsu nejí.|Je to vıteèné.
{26621}{26645}e?
{26946}{27051}Ještì jednu|"kombo" pizzu, prosím!
{27051}{27076}Smím?
{27157}{27212}Jasnì, jez kolik chceš.
{27250}{27279}Tak to já si také dám...
{27279}{27353}...ještì jednu "kombo"!
{27398}{27477}Kupóny nebudou staèit.|Kolik s sebou máš?
{27477}{27510}1500 jenù...
{27510}{27563}Já jen 1000.
{27843}{27893}Nesmìj se!
{27898}{27948}Já se nesmìju.
{28002}{28020}Hej...
{28020}{28084}Sundej si to a nech to uschnout.
{28084}{28113}Jasnì...
{28118}{28192}Hm, zábavné. Jak bych se asi mohl pøed holkou svléknout?
{28192}{28292}Ayukawa teï vypadá tak šastnì.
{28292}{28457}Zajímalo by mì, proè je pøed|ostatními tak nepøístupná.
{28529}{28565}Copak?
{28565}{28641}Chodíš sem èasto?
{28641}{28687}Sem tam...
{28751}{28785}Shou!
{28854}{28902}Ach ne!
{28919}{28966}Ayukawo...
{28993}{29145}Abych byl upøímnı, moc si v plavání|nevìøím, ale v této situaci...
{29145}{29188}Ayukawo!
{29188}{29236}Pùjdu já!
{29265}{29330}Musím!
{29375}{29537}To je asi poprvé, co mi na nìèem tak moc záleelo...
{29537}{29632}...a to nejen kvùli tomu dítìti.
{29632}{29858}Abych se dostal blíe k Ayukawì,|která je vdy tak vzdálená...
{31041}{31101}Co je?|Je na mnì nìco nalepeného?
{31130}{31166}Plankton.
{31240}{31336}Co? Nìco takového nemùeš vidìt!
{31360}{31448}Jak tu takhle sedíme sami dva,|je to jako bychom byli na rande.
{31448}{31493}Rande, huh?
{31493}{31537}RANDE?!
{31565}{31644}Moje rande s Hikaru...!
{31668}{31718}Rande s Hikaru?
{31718}{31766}No...
{31842}{31923}U bych mìla jít.
{31923}{31976}Zaplatím.
{31976}{32006}Ahoj.
{32006}{32060}Co ta bunda?
{32060}{32136}Vrátíš mi ji|a ji vypereš.
{32194}{32249}Kasuga Kyosuke...
{32249}{32301}...tohle parádnì podìlal.
{32556}{32595}Kyosuke je debil!
{33427}{33525}Kdy budeš kouøit v tomhle vìku,|nebudeš mít zdravé dìti!
{33666}{33714}Zvláštní kluk...
{34420}{34600}Hravì jsem seslal kouzlo.
{34607}{34768}Chci oèarovat tvé srdce.
{34789}{34964}Láska je deja-vu.  Nezvyklé vzpomínky...
{34971}{35133}...na vzájemnì se dotıkající rty,
{35206}{35281}...nìnì,
{35290}{35448}zlatavı letní pøelude.
{35551}{35693}Pokryj mé tìlo polibky, prosím.
{35702}{35863}Ráno mi smíš øíkat "miláèku".
{35969}{36118}Budu èekat navdy.
