{1}{1}23.976
{827}{1027}{Y:i}Mé srdce
{1615}{1655}Haló?
{2126}{2154}Ano?
{2190}{2222}Kapitáne!
{2250}{2311}Ano, vyzvedli jsme ho na letišti.
{2335}{2363}Ano.
{3082}{3158}Tahle fotografie.|Fotil jste ji vy, e?
{3170}{3234}Byla nalezena na místì èinu.
{3237}{3296}A vy jste ze zemì odjel |v ten samı den.
{3305}{3405}Tohle patøí mému synovi, |kterı chodí na základní školu.
{3412}{3509}Napsal to na zem a poprosil mì, |jestli bych to nemohl vyfotit
{3512}{3578}jeho dívce ze tøídy.
{3634}{3727}A moje cesta je naplánovaná |u od minulého semestru.
{3782}{3838}Fotil jste Ji Kyung-hee.
{3868}{3932}- Koho?|- enu, která vlastní ateliér.
{3933}{3995}- Fotil jste ji.|- Ne.
{4001}{4045}Nehrajte si se mnou.
{4049}{4081}Fotil jste ji!
{4085}{4139}Poádala mì o to.
{4142}{4182}Nechte si ty kecy!
{4190}{4283}Donesla nám fotografie, které jste |poøídil a všechno nám øekla.
{4287}{4339}Poádala mì!
{4342}{4411}Myslela to tak vánì, |e jsem nakonec souhlasil.
{4418}{4446}Nebylo to porno.
{4450}{4519}Fotil jsem ji nahou.|To je zloèin?
{4541}{4574}Nahou?
{4625}{4667}Vy jste ji fotil nahou?
{4704}{4736}Take vy mi chcete øíct, e...
{4757}{4790}Ji Kyung-hee
{4810}{4900}vás poádala, abyste ji fotil nahou?
{5034}{5069}Podívejte, detektive.
{5108}{5158}Mám rodinu.
{5176}{5230}Upøímnì je mi nepøíjemná...
{5233}{5273}u skuteènost, e tu jsem.
{5306}{5341}Kyung-hee, tak se jmenuje?
{5390}{5441}Myslím, e se do mì zamilovala.
{5476}{5506}Omlouvám se...
{5510}{5547}jenom jsem zkoušel fotoaparát.
{5573}{5628}Proè jste mi to neøekl pøedem?
{5638}{5692}Mohla bych vám stát modelem.
{5782}{5810}Dìje se nìco?
{5890}{5942}Zapamatovala jste si |moje jméno a telefonní èíslo!
{5952}{6040}Samozøejmì, vdy sem |chodíte kadı tıden!
{6082}{6167}Proè jste dìlal fotografie |vlastních nohou?
{6178}{6227}Ze všech mıch fotografií...
{6230}{6308}se nejvíc zajímala |o moje nahé fotky.
{6319}{6368}Proè jste se tam tedy vracel?
{6386}{6486}Jste pøece mu.|Vijte se do mé pozice.
{6504}{6580}Je pìkná a tajemná.
{6602}{6685}U eny není špatnou vlastností, |kdy je trochu smìlejší.
{6713}{6755}Take se mi to docela líbilo.
{6845}{6916}Ty hraješ v koncertní síni...
{6919}{6971}a já zpívám ve sklepní kavárnì.
{7009}{7059}Kadá jsme dopadla úplnì jinak.
{7093}{7160}- Rajèatovı dus?|- Pro ni.
{7180}{7210}Káva je moje.
{7244}{7275}Díky.
{7412}{7448}Proè to nepiješ?
{7602}{7661}Je docela dobrı.|Zkus.
{7717}{7814}Vídáš se poslední dobou |s Ki-hoonem?
{7906}{7941}Zmìò téma.
{7992}{8082}Mám toho dost.
{8088}{8113}Èeho?
{8117}{8210}- Ka-hee, prosím...|- Prosím co?
{8214}{8242}Øekni.
{8261}{8313}Tobì se líbí to, jak iješ?
{10256}{10293}Neøíkal jste mi, e...
{10323}{10380}fotografování osvobozuje duši...
{10412}{10466}...a èlovìk se cítí jako malı kluk.
{10519}{10549}Prosím.
{10784}{10855}Øíkala, e její manel je mimo mìsto...
{10870}{10929}a poádala mì, abych ji fotil nahou.
{10961}{11034}Myslel jsem si, e je to pøehnané, |tak jsem nejdøíve odmítnul.
{11606}{11687}Ale na druhou stranu si obèas |najímám profesionální modelku...
{11714}{11799}a ona to sama chtìla.
{11821}{11885}Take jste to udìlal?
{11972}{12020}Dáte mi jednu?
{12335}{12377}Vám se nelíbí to vzrušení?
{12428}{12461}Líbí.
{12491}{12533}Dostat se tam...
{12536}{12595}je mnohem vìtší zábava |ne tam bıt.
{12653}{12705}Vy nemáte takovou zkušenost?
{12726}{12783}Píchání je dobré...
{12786}{12847}ale ten pocit, kdy se udìláte...
{12946}{12988}Nespal jsem s ní.
{14864}{14902}- Mluv.|- Ano, pane.
{14905}{14986}Je pravda, e byl v knihovnì.|Jeho prùkaz to potvrzuje.
{14989}{15062}Co kdy ho nìkomu pùjèil?
{15077}{15134}Dál hledej svìdky.
{15137}{15192}A proklepni i jeho enu.
{15195}{15225}- Ano, pane.|- Dobøe.
{15317}{15355}Co zase?
{18005}{18040}Víte vy co?
{18087}{18205}Je docela nudné sedìt |sama v ateliéru.
{18288}{18354}Zaèal mi dìlat spoleènost...
{18384}{18419}a já byla ráda.
{18470}{18507}Dokonce vdìèná.
{18921}{18966}A tak to zaèalo.
{19019}{19056}Nejdøíve ruce.
{19086}{19128}Pak ramena.
{19208}{19258}Co myslíte, e to znamenalo?
{19339}{19372}Moná...
{19409}{19485}se se mnou chtìl vyspat.
{21652}{21723}Øekni mu o našem pravidle.
{21726}{21761}Ještì jeden pro toho, |kdo prohraje!
{21764}{21819}- Na zdraví!|- Na zdraví!
{21942}{21977}No tak!
{21980}{22028}Prohráls! Vypij ještì jednoho!
{22031}{22064}Omlouvám se.
{22084}{22102}Dej to sem.
{22105}{22133}- Kapitáne.|- Co je?
{22136}{22183}Nechte mì pít jen pivo.
{22186}{22231}Buï zticha.
{22246}{22291}Alkohol by se nemìl mixovat...
{22294}{22384}ale kdy u zaèneš, |je to potøeba udìlat poøádnì.
{22388}{22413}Piš si.
{22416}{22466}1. Alkohol by se nemìl mixovat.
{22469}{22550}2. Buï zticha a chlastej.
{22558}{22610}Ten, kdo dopije poslední, |dostane jeden navíc.
{22613}{22663}- Dobøe.|- Jasnì.
{23340}{23367}Ka-hee.
{23421}{23449}To jsem já.
{23608}{23646}{Y:i}Dejte prst na destièku, prosím.
{23707}{23740}{Y:i}Zkuste to znovu, prosím.
{23783}{23820}{Y:i}Dejte prst na destièku, prosím.
{23881}{23916}{Y:i}Zkuste to znovu, prosím.
{23929}{23964}Co to...
{24023}{24056}Ka-hee!
{24098}{24143}To jsem já! |Otevøi ty dveøe!
{24198}{24233}Ka-hee!
{24450}{24497}Já to taky nemám jednoduchı.
{24556}{24626}Dokonce ti ani nemùu koupit ten prsten, |kterı tak moc chceš.
{24780}{24844}Su-hyun šla na potrat |a ani mi o tom neøekla.
{24920}{24986}Tak otevøi ty zatracenı dveøe!
{24989}{25022}Otevøi je!
{25037}{25077}To jsem já!
{26488}{26568}- Su-hyun, já...|- Prosím.
{26656}{26686}Chci se rozvést.
{27252}{27280}19 vteøin.
{28101}{28134}Proboha, nechal jsem vás...
{28137}{28182}tak dlouho èekat.|Moc se omlouvám.
{28185}{28201}Nech to na mnì.
{28204}{28292}Moc se omlouvám.|Máme pøíliš zákazníkù!
{28296}{28328}Jakı styl byste si...
{28332}{28362}- Sestøièko.|- Ano?
{28425}{28456}Kde je Hyuk-ju?
{28495}{28556}Kdo je...
{28612}{28642}Kde je Hyuk-ju?
{28645}{28685}Nevím, pøísahám!
{28772}{28810}Kde bych ho mohl najít?
{28986}{29057}Opravdu to nevím.
{29068}{29165}Taky mi chybí!
{29209}{29302}Jmenuje se Oh Yeon-shim.|Potkali se v baru.
{29315}{29380}Hyuk-ju je do ní blázen.
{29391}{29438}Kde bych ji mohl najít?
{29460}{29493}Nejsem si jistı.
{29511}{29565}Slyšel jsem, e pracuje |v kavárnì jménem Purte.
{29700}{29772}S vlastníkem ateliéru jsem |se seznámila díky šéfovi.
{29782}{29824}Nabídnul se, e mi...
{29828}{29896}koupí byt, kdy mu donosím dítì.
{29921}{30033}Nešlo pøece o vradu dítìte, |ale o jeho pøivedení na svìt.
{30036}{30098}Ale Hyuk-ju se strašnì rozèílil...
{30101}{30151}kdy jsem mu to øekla.
{30173}{30244}Nechápala jsem to.|Já budu nosit to dítì a ne on!
{30408}{30448}Co to kurva...
{30453}{30510}Ty mi chceš tvrdit, |e se s nikım neschází?
{30525}{30601}A odkud se berou ty fotky?
{30604}{30635}Kyung-hee miluju tì?
{30638}{30680}Mám všechny dùkazy, ty debile!
{30684}{30728}To nedokáeš nic udìlat správnì?
{30940}{31011}Snail jsem se na tebe |bıt milı kvùli Yeon-shim.
{31050}{31102}Kretén jako ty...
{31105}{31167}a lemra jako Yeon-shim...
{31170}{31227}oba jste jen zaostalí dementi.
{31388}{31469}Potkala jsem ho |pozdìji ten den.
{31499}{31618}Díval se na "Polibky" v televizi|a z nièeho nic mi øekl:
{31631}{31780}"Rozmlátil jsem mu tu jeho |kurevskou hlavu."
{32064}{32126}Jo... Ne...
{32146}{32217}Nevysílali jste ten program ráno?
{32292}{32323}Chápu.
{32360}{32387}Díky.
{32750}{32845}{Y:i}Odhadovanı èas smrti?
{33307}{33354}{Y:i}Volanı úèastník právì hovoøí...
{33516}{33595}Mìli bychom se rozejít?
{34731}{34771}Do prdele s tím!
{35736}{35808}Zajdeme dnes na veèeøi ven.
{35812}{35861}Konèím dnes brzy.
{35987}{36029}Dám si ještì trochu od tebe.
{36136}{36171}Ach, tohle!
{36184}{36221}Botky pro naše dìátko.
{36232}{36267}Jsou rùové.
{36270}{36327}Rozhodnul jsem se, e chci dceru.
{36412}{36466}Koupil jsem ti panenku, ale...
{36469}{36524}nechal jsem ji v kufru auta.
{36536}{36578}Bude se ti líbit.
{36687}{36722}Mìj se.
{37915}{37972}Dopis uznání| Toto uznání je vám udìleno...
{37975}{38034}za vaše odhodlání s patriotismem...
{38037}{38096}potlaèovat násilí a zloèiny v naší zemi.
{38956}{39012}Uniforma ti sluší.
{39034}{39100}- Tobì to taky sluší.|- Díky.
{39111}{39165}- Gratuluji, kapitáne.|- Díky.
{39183}{39216}- Ehm... kapitáne.|- Ano.
{39219}{39283}Mohu vás vyfotit?
{39286}{39367}Aha, to je detektiv Cho?
{39406}{39467}Zdravím, skuteènı detektive Cho.
{39480}{39523}Nìkdy jsem i já detektiv Cho.
{39560}{39626}Bude vám vadit, |kdy vás vyfotím?
{39629}{39688}- Spoleènì.|- Samozøejmì.
{39692}{39748}Raz, dva...
{39818}{39851}Je pìkná.
{39945}{39978}Nezastavíme se tam?
{39981}{40019}{Y:i}Motel
{40075}{40120}Musíme si promluvit.
{40168}{40240}Dostal jsi uznání.|Je to tvùj den.
{40243}{40314}Nebudeme si ho kazit |v hloupém motelu.
{40336}{40412}Chtìl bych ti nìco øíct.
{40444}{40489}Dnes mám narozeniny...
{40497}{40554}take neøíkej nic, |èím bys to pokazil.
{42106}{42139}Všechno nejlepší...
{42184}{42229}Nevzpomnìl sis!
{42381}{42460}Hodnì štìstí, zdraví
{42468}{42541}Hodnì štìstí, milá Ka-hee
{42544}{42599}Hodnì štìstí, zdraví.
{42739}{42817}ádnı dárek?
{43942}{44023}- Proè jsi to udìlala?|- Nevím.
{44067}{44145}- Je to legrace.|- To teda není.
{44153}{44212}- Nehıbej se!|- Bolí to?
{44216}{44260}- Uhni kousek nohou.|- U je to dobré?
{44264}{44306}- Ještì kousek.|- Tak?
{44647}{44720}Ještìe není zima.
{44724}{44816}Bylo by to hrozné, kdyby mrzlo.
{44844}{44953}Neumøeme tady takhle, e ne?
{44956}{45013}O takovıch vìcech nemluv.
{45016}{45078}Nejsme daleko od hlavní silnice.
{45115}{45196}Co lidi øeknou, |a otevøou ten kufr?
{45220}{45313}Ty máš kalhoty na pùl erdi...
{45316}{45375}a já sukni vyhrnutou po pás.
{45383}{45425}Co je tohle?
{45488}{45531}Mám tì svléknout?
{45534}{45576}Nehıbej se.
{45580}{45622}- Zùstaò v klidu.|- To bolí.
{45625}{45670}Mùeš hıbat nohama?
{45836}{45922}Vidíš nìco?
{45983}{46032}Nikdy jsem tady nebyla.
{46036}{46107}Podr to.
{46156}{46185}Sakra! To pálí!
{46332}{46360}Na co to..?
{46416}{46449}Ty budeš støílet?
{46613}{46646}Co je tohle?
{46700}{46732}Nemùu dıchat.
{46884}{46941}Do prdele!
{47174}{47228}Celou noc se nevrátil.
{47299}{47382}Ne, ani slovo.
{47407}{47447}Dobøe, dìkuji.
{48397}{48432}Skluznice...
{48500}{48607}Kdy nás najdou mrtvé...
{48653}{48703}budeme ve zprávách, e?
{48711}{48789}Jak by to nazvali?
{48855}{48914}Konec špinavé aféry?
{48932}{48967}Zásobník...
{48982}{49017}Ne.
{49102}{49214}Nìkteøí by si mohli myslet, |e jsme chtìli zemøít spolu.
{49217}{49293}- Natáhnout...|- Nejdraší kapitán...
{49325}{49451}spáchal dvojitou sebevradu |spoleènì se zpìvaèkou...
{49478}{49508}Ka-hee.
{49536}{49580}Udìlej pro mì nìco.
{49598}{49647}Uhni kousek rukou.
{50047}{50108}{Y:i}"Polibky ve 4:05|Odhadovanı èas smrti?"
{50257}{50336}Co máš s "Polibky"?
{50339}{50429}Po vradì Hana se Hyuk-joo |vrátil do motelu...
{50432}{50484}a díval se na "Polibky" s Yeon-shim.
{50488}{50527}To bylo v 4:05!
{50531}{50645}Ale odhadovanı èas smrti je v pìt hodin!
{50996}{51033}Musíme se odsud dostat.
{51060}{51103}Zvládneme to?
{51207}{51300}Já to zvládnu.|Musíme!
{51459}{51580}Nechceš takhle umøít?
{51648}{51691}Nemìj strach...
{51716}{51779}svìt nás bude litovat.
{51823}{51892}Málokdo mùe umøít takhle tragicky.
{51933}{52009}Pøestaò vanit o umírání!
{52068}{52158}Su-hyun to pøejde...
{52178}{52232}jako by se nic nestalo.
{52269}{52338}I kdy umøeme spoleènì...
{52341}{52393}zachová si ten svùj klid.
{52418}{52520}Co je to s tebou?|Pøestaò vanit o smrti!
{52784}{52829}To je pìkné.
{52895}{52976}Ki-hoone, nejsi zranìná?
{53048}{53122}- Já se podívám.|- Nech mì bıt.
{53125}{53168}Uka...
{53883}{53935}Myslím, e je ráno.
{53976}{54007}To je krása.
{54041}{54105}Koneènì se mi splnilo moje pøání.
{54123}{54186}Probudila jsem se po tvém boku.
{54266}{54368}Ki-hoone, jsi v poøádku?
{54400}{54445}Jsi v poøádku?
{55172}{55212}Ka-hee?
{55256}{55308}Ka-hee, jsi doma?
{55446}{55479}Pøišel nìkdo?
{55506}{55584}Su-hyun! Co tady dìláš?
{55672}{55726}Znáte se u?
{55744}{55797}Tohle je Su-hyun, |chodily jsme spolu na vysokou.
{55805}{55840}A tohle je...
{55853}{55917}mùj kamarád.|Jmenuje se Lee Ki-hoon.
{56834}{56934}Jsi se Su-hyun šastnı?
{57031}{57138}Jsi s ní šastnı?
{57175}{57227}Miluje mì.
{57259}{57289}Opravdu?
{57349}{57380}Já...
{57404}{57452}Já tì taky miluju.
{57784}{57850}Všichni ti, které mám ráda...
{57875}{57932}nosí prsteny.
{57949}{57982}Jako by...
{58016}{58145}Jako by se s nimi u narodili.
{58224}{58300}Má ten stejnı prsten...
{58342}{58370}jako ty?
{59030}{59099}Musím se odsud dostat.
{59102}{59197}Musím se odsud dostat!
{59200}{59248}Èeká na mì.
{59251}{59334}Musím se odsud dostat!|Ona na mì èeká!
{59337}{59384}Èeká na tebe?
{59388}{59437}Ano, èeká na mì.
{59440}{59526}- Na koho?|- Prosím, puste mì.
{59539}{59574}Neøíkala jsem ti to?
{59582}{59651}Ty ji neznáš.
{59788}{59818}Já...
{59886}{59921}...milovala...
{59992}{60037}...svoji kamarádku.
{62322}{62376}U si nepamatuji...
{62418}{62463}kdy to zaèalo.
{62490}{62530}Jediná vìc, kterou vím je, e...
{62543}{62602}Já to zaèala.
{62684}{62722}Já to zaèala.
{62725}{62796}Ne, zboòovala jsem to.
{62819}{62876}Byly to krásné èasy.
{62884}{62938}I kdyby mùj ivot tenkrát skonèil...
{62993}{63038}nebyla bych smutná.
{63166}{63235}Kdy jsem pak potkala tebe...
{63238}{63290}otevøel se mi úplnì jinı svìt.
{63324}{63396}Mùj ivot nabral jinı smìr,
{63411}{63441}ale Su-hyun...
{63454}{63499}Mìla jsem strach,
{63538}{63599}e mì opustí, kdy se vdá.
{63620}{63755}Ano, vybral sis Su-hyun.
{63782}{63858}Su-hyun je ta zábavná.
{63876}{63930}Tím, e jsem si toho mue vzala...
{64000}{64055}jsem si chtìla udret Ka-hee.
{64130}{64271}Mám se pøestìhovat do Ameriky|a vychovat naše dítì?
{64387}{64494}Vlastì u jsem mu našla jméno.
{64514}{64551}Je to Jin-ju.
{64564}{64603}Jin-ju.
{64619}{64661}Laciné jméno?
{64720}{64783}Znamená to "perla" v angliètinì.
{64830}{64872}Jako ten...
{64888}{64990}krb mámina dìvèátka |v "Šarlatovém dopise".
{65087}{65156}Vychovám ji jako andílka tam,
{65176}{65230}kde nás nikdo neznám.
{65281}{65414}V zapomenuté pamìti...
{65424}{65548}ta myšlenka na tebe
{65561}{65664}pøíliš bolestivá, abych na ni myslela.
{65744}{65867}Podívej, jak jsem osamìlá
{65892}{66002}podívej, jak jsem prázdná.
{66256}{66311}Ki-hoone, podívej se na tohle.
{66314}{66344}Já krvácím.
{66348}{66411}Já krvácím tam dole!
{66520}{66551}Ach Boe!
{66631}{66695}Moje dìátko!
{66765}{66808}Dostaòte mì odsud!
{66823}{66872}Moje ubohé dìátko!
{67031}{67083}Musím se odsud dostat!
{67216}{67306}Sklapni kurva, ty krávo!
{67693}{67723}Já se bojím.
{67750}{67790}Tolik se bojím.
{67839}{67936}Ké bych mohla umøít ve spánku.
{67985}{68088}Pomùeš mi to udìlat?
{68129}{68179}- Prosím, zabij mì.|- Co se dìje?
{68182}{68229}Moje bøicho tak moc bolí.
{68273}{68354}Nemám ráda bolest.|Zabij mì, prosím.
{68357}{68433}- Prosím, ukonèi moje trápení.|-Já nemùu.
{68436}{68512}Udìlej to ty.|Sama sis to zavinila.
{68516}{68552}Nech mì bıt.
{68556}{68658}Ty jsi si nachcal a nasral do kalhot|a poøád ještì chceš ít?
{68673}{68716}Ty zasranej hajzle!
{68719}{68848}Ty jsi nás do toho dostala.|Je to tvoje chyba!
{68901}{68992}Zabij mì, prosím.|Já u tu bolest nevydrím.
{68995}{69066}Tak moc se bojím.
{69069}{69128}Bojím se strašnì moc.|Zabij mì, prosím.
{69812}{69879}Ka-hee, nedìlej to!
{69882}{69979}Omlouvám se!|Je to moje chyba!
{70009}{70054}- Zabiju se.|- Ne, nezabíjej se.
{70057}{70114}Budu se tady sám bát!
{70117}{70164}- Neplaè.|- Neumírej.
{70167}{70214}Je to dobré. Neplaè.
{70229}{70267}- Ne...|- Ne, ne.
{70270}{70334}Neplaè. Neplaè.
{70354}{70403}Všechno bude dobré.
{70527}{70584}Je to moje chyba.
{70616}{70670}Mohla jsem se seznámit |s nìkım jinım...
{70673}{70747}kdybych chtìla.
{70767}{70800}Je mi to líto.
{70803}{70881}Ale já nemohla.
{70918}{71020}Jedla jsem nìco vıborného, |myslela na tebe a breèela.
{71047}{71171}Probouzela jsem se v noci |a tak strašnì jsi mi chybìl.
{71222}{71286}"Prosím, a s ním mùu zùstat...
{71308}{71384}po celı zbytek mého ivota."
{71397}{71456}modlila jsem se kadı den a noc.
{71572}{71655}Omlouvám, Ka-hee.
{71659}{71743}- Ne.|- Já se omlouvám.
{71747}{71811}Je to dobré. Neboj.
{71855}{71928}U nechci víc klesnout.
{71932}{72003}Ne! Ne, Ka-hee!
{72006}{72101}Nikdy nebudu šastnìjší.|Udìlej to prosím pro mì.
{72172}{72202}Je to dobré.
{72224}{72293}- Je to dobré.|- Ne!
{74540}{74595}Ten hajzl...
{75140}{75271}Prosím... Prosím, nech mì ít.
{76784}{76812}Kapitáne?
{76878}{76906}Kapitáne!
{76919}{76947}Kapitáne!
{76952}{77000}Cho, rychle pojï sem!
{77020}{77050}Kapitáne!
{77065}{77095}To jsem já, Ahn.
{77144}{77180}Dìlej, Cho!
{77204}{77232}Kapitáne!
{77255}{77290}Vydrte!
{77296}{77335}Seeòte mu nìjaké šaty!
{77480}{77519}Je mi to líto.
{77592}{77654}Je mi to líto.|Je mi to tak líto.
{77667}{77716}Všechno je to moje chyba.
{77753}{77803}- Jste v poøádku?|- Všechno je to moje chyba.
{77806}{77836}Kapitáne!
{78595}{78632}Kapitáne! Kapitáne!
{78638}{78673}Ahne!
{78717}{78757}No tak, kapitáne!
{78808}{78870}Kapitáne, pøestaòte!
{78878}{78906}Puste mì!
{79177}{79232}Zbraò! Tu zbraò!
{79235}{79289}Vezmìte mu tu zbraò!
{79362}{79395}Kurva..
{79556}{79580}Kapitáne!
{79848}{79879}Dva dny...
{79925}{80016}Strávil jsem s Ka-hee |ještì další dva dny.
{80067}{80109}S pachem její krve...
{80199}{80234}Mezitím...
{80261}{80344}jsem øekl policii, |e se zabila.
{80458}{80557}Noèní mùry vás pronásledují navdy.
{80635}{80663}Kdy se chcete odstìhovat?
{80670}{80705}Èím rychleji, tím lépe.
{80716}{80802}Mùe chvíli trvat, ne najdeme kupce...
{80805}{80845}se stagnující ekonomikou.
{80848}{80888}- Spoléhám na vás.|- Samozøejmì, ozvu se vám.
{80892}{80939}- Dobøe. Sbohem.|- Sbohem.
{81086}{81123}Prodávám ateliér.
{81187}{81244}Nemùu ho provozovat sama.
{81266}{81324}Odešel jsem od policie.
{81419}{81476}Nemùu uvìøit, e jsem zavøel |nesprávnou osobu.
{81503}{81576}Na druhou stranu u byl ve vìzení, |urèitì to zvládne.
{81642}{81699}Promiòte, e o tom mluvím.|U je po všem.
{82072}{82144}Tahle se jmenuje |"Naše paní elegance"?
{82148}{82238}Jiná jména pro jiné pozice, e?
{82263}{82296}Øeknìte mi.
{82348}{82387}Co mohu dìlat?
{82594}{82624}{Y:i}Kyung-hee, miluji tì.
{82628}{82682}Øíkal jste, e nebyla pro mì.
{82798}{82888}Kontroloval jsem to ve škole, |kam chodí jeho syn.
{82908}{82995}ádná Kyung-hee v jeho tøídì není.
{83097}{83144}Teï u na tom nezáleí.
{83253}{83339}JUNG Myung-sik...|Milovala jste ho?
{83464}{83500}Kdy jsem ho milovala...
{83608}{83665}Kdy jsem ho milovala, |bude mi odpuštìno?
{86500}{86700}Pøeloil Tadi|www.cesketitulky.com