{1}{1}29.970
{300}{450}Full Metal Panic Second Raid
{2746}{2901}Pro Boha který mlčky vytvořil kraj moře,
{2901}{2975}prosím postarej se o naše přátelé|kteří jsou nuceni vyplout.
{2975}{3137}Pro Boha který může zkrotit|bouřlivé vlny a vichry,
{3137}{3213}prosím postarej se o naše přátelé|kteří jsou nuceni vyplout.
{3213}{3369}Pro Boha který může dokonce živit a formovat|bezedná,nepokojná údolí pod mořem.
{3369}{3446}prosím postarej se o naše přátelé|kteří jsou nuceni vyplout.
{3446}{3527}Pro Boha,zdroj všeho dobra,
{3527}{3606}prosím chraň nás během nebezpečných časů,
{3606}{3682}provázej nás do přístavu od našeho cíle.
{3729}{3822}Nyní,pojďme pokračovat s briefingem.
{3822}{3852}Vyplout!
{3870}{3922}Epizoda 10.:Dva v Hong Kongu
{3919}{4037}Mozkové vlny během 30-50Hz jsou nazývané Gamma vlny.
{4037}{4138}Jen když ampituda vln překračí určitou hranici
{4138}{4259}může jedině aktivovat silové pole Lambda Driveru.
{4284}{4355}V současné době má výzkum ukázat že
{4352}{4415}to je extrémně obtížné pro pilota
{4412}{4521}pro úmyslné generování a udržení takové vlny,
{4543}{4637}Nicméně,četná vědecká studie ukazuje že
{4634}{4754}použitím vzácné drogy,T1970,
{4752}{4830}produkuje stejný účinek uměle.
{4830}{4860}To znamená...
{4860}{4959}Použtí Lambda Driveru za prodlouženou dobu
{4959}{5022}je nemožné,obávám se.
{5027}{5107}Nicméně,Behemonth je vyjímka.
{5107}{5149}To může tedy.
{5149}{5241}Ale jestli že to nepřítel použije,|není nic co můžeme udělat.
{5241}{5316}To je jen předpoklad.
{5316}{5418}Na naší straně máme ještě Arbalesta.
{5418}{5521}Ale,jestli nemohl být aktivován,jako v Nanjingu...
{6970}{7048}Kontroluji,Seržant Sagara potvrzuji.
{7045}{7084}Ano,Seržante.
{7084}{7114}Jak postupuje tvoje oprava?
{7114}{7234}Výsledek z dnešní kontroly v 1730 byl uspokojivý.
{7234}{7302}Kontrolu provedl Poručík Sachs.
{7302}{7490}Záznamové číslo údržby je 051021-01B-F-001.
{7490}{7544}Přejete si prohlédnout tento záznam?
{7642}{7720}Pokud si přejete tuto jednotku znovu zkontrolovat,
{7717}{7800}současné nastavení bude must být změněno.
{7809}{7911}Tréninkový mod bude muset být ukončen,|spojení vnějšího zdroje energie...
{7908}{7989}Vzbudil jsem tě z rozmaru.
{8007}{8135}Tréniková správa:|Prosím vyjasněte slovo "rozmar".
{8135}{8192}Zkus to vytušit sám.
{8228}{8250}Kompletní.
{8250}{8324}Přejete si slyšet zprávu o výsledku?
{8324}{8354}Pokračuj.
{8354}{8384}Definice "rozmar".
{8384}{8431}Nejbližší nalezení:
{8431}{8512}Koncepčně podobné na |"rozvážnost" nebo "podmět".
{8512}{8549}Druhé nejpravděpodobnější nalezení:
{8549}{8628}Koncepčně podobné na |"úsilí"nebo"náladovost".
{8628}{8671}Třetí nejpravděpodobnější nalezení:
{8671}{8753}Koncepčně podobné na|"nepokoj" nebo "neregulérní".
{8753}{8794}Čtvrté nejpravděpodobnější nalezení
{8794}{8836}Koncepčně podobné na"pobavení".
{8836}{8892}Víš co je "pobavení"?
{8898}{8926}Potvrzuji.
{8926}{8991}Je to concepčně podobné na "rozmar" ?
{8991}{9042}Koncept je blíž k "zábavě" a "neregulérní".
{9073}{9126}Děkuji za spolupráci.
{9126}{9184}Kdo tě učil tyhle věci?
{9184}{9268}Vedoucí pracovník Bunny Morauta,Seržante.
{9268}{9343}Byl to ten technik co tě vyvinul?
{9343}{9361}Ano.
{9396}{9461}Tak,tenhle kus selhání byl jeho duchovní dítě.
{9461}{9582}Tréninková zpráva:|Jaký je význam "selhání"?
{9582}{9667}Přestaň mě bombardovat treninkovýma zprávama.
{9667}{9764}Prostě,zbraňový systém který nefunguje pořádně.
{9764}{9815}To znamená,ty.
{9809}{9838}Potvrzuji.
{9838}{9926}ARX systém je neúplný.
{9926}{9975}Ty to připouštíš?
{9981}{10005}Potvrzuji.
{10005}{10089}A vy jste část příčiny.
{10095}{10113}Co?
{10119}{10257}Vy jste také část systému ARX.
{10263}{10343}Bez vaší spolupráce systém zůstane neúplný.
{10343}{10413}Prosím oznam te mi váš problem.
{10413}{10539}Jsem ochotný vám kdykoliv nabídnout radu.
{10557}{10578}Radu?
{10591}{10614}Tvoji?
{10620}{10656}Potvrzuji.
{10662}{10719}Nemám žádný problem.
{10725}{10771}To si nemyslím.
{10771}{10795}Co to je?
{10792}{10838}Můj instinkt mi to říká.
{10835}{10856}Instinkt?
{10859}{10951}Slovo instinkt,kdo tě ho naučil?
{10954}{11093}Pak,řekni svému instinktu|ať nechá nesmyslné tušení!
{11096}{11159}Váš rozkaz je absurdní.
{11162}{11273}Instinkt nemůže být řízen ani přesvědčován.
{11276}{11356}Přichází z hloubi srdce.
{11359}{11438}Ty si jediný který chrlí nesmysly!
{11441}{11491}Zde je omezení pro hraní...
{11516}{11553}Sousuke,jsi tam?
{11559}{11586}Co se děje?
{11589}{11638}Major volá.
{11638}{11668}Je to mise.
{11687}{11708}Mise...
{11792}{11849}Jak všechni můžete vědět,
{11849}{11939}neidentifikované AS se oběvilo v Hong Kongu.
{11967}{12042}Tenhle stroj demolující v osamělém městě,
{12042}{12154}by se měl právě skrývat kdesi ve městě.
{12161}{12251}Obojí sevrská i jižní Čínská armáda utrpěla ztráty.
{12257}{12325}Navíc nedávný Nanjingský incident
{12328}{12429}má dané strany v kritickém stavu napětí.
{12432}{12600}Jestli to takhle bude pokračovat,Hong Kong může|být vytržen stranou a stát se krvavým bojištěm.
{12603}{12693}To znamená že nemůžeme být|neopatrní a zaplést se do politiky.
{12699}{12766}Poručíku Grouseauxi pokračujte.
{12778}{12848}Tak proto jsme byli zavoláni?
{12851}{12919}Toto bylo vzato před 26 hodinamy.
{12925}{13019}Poblíž Yaumatei,Kowlonův poloostrov.
{13022}{13133}Obávám se že tohle je stejný stroj|který byl viděn v Helmajistanu.
{13140}{13242}Po zdrcení obrněného sboru z Jižní Číny,
{13248}{13318}se ukryl použitím neviditelného zařízení.
{13327}{13434}Objevoval se na mnoha různých|místech v Kowloonu v Hong Kongu.
{13443}{13507}Ničí vše co mu přijde do cesty.
{13516}{13607}Asi 10 AS bylo posláno|skontrolovat co bylo zničeno.
{13604}{13664}Obětí je také mnoho.
{13670}{13773}Severní a Jižní Čínská armáda|nejsou schopni tento stroj zastavit,
{13773}{13842}nebo sledovat jeho stopu,
{13848}{13998}nejspíš kvůli jeho neviditelným schopnostem.
{14007}{14055}Jsou za tím teroristé?
{14064}{14085}Nevím.
{14094}{14145}Nikdo se k tomu zatím ještě nepřihlásil.
{14151}{14246}Věřím že mají zájem začít občanskou válku v Číně,
{14243}{14279}nebo naruši Hong Kongskou ekonomiku.
{14294}{14318}Nebo...
{14339}{14402}Nás vyzývají.
{14411}{14570}Navzdory všemu,je nemožné nezávisle|operovat přímo s AS po 24 hodin.
{14579}{14769}Doplnění munice,údržba vybavení,|stejně jako odpočinek pro pilota jsou nezbytné.
{14779}{14874}Za prvé,najdete jeho úkryt,
{14874}{14987}využijete malou skupinu M9 pro|obklíčení,útok a jeho zdolání.
{14996}{15085}Pro to potřebujeme průzkum.
{15088}{15112}Průzkum?
{15118}{15198}Je to společná operace s větví|Hong Kongské zpravodajsé divize.
{15204}{15309}Budou zásobou nezbytných|znalostí pro lokalizaci nepřítele.
{15321}{15396}Pošleme vás tam dnes večer helikoptérou.
{15405}{15466}Vy všichni musíte letět do Hong Kongu před námi.
{15481}{15521}Jde i Sousuke?
{15524}{15539}Ano.
{15548}{15633}Není Sousuke na pohotovsti s Arbalestem?
{15642}{15756}Strategie nevyžaduje použití|Arbalestu v téhle operaci.
{15756}{15774}Proč je tomu tak?
{15774}{15804}Protože je nespolehlivý.
{18276}{18318}Od pohledu z toho...
{18318}{18380}se tohle místo moc nezměnilo.
{18389}{18440}Ty si tu byla už předtím?
{18446}{18502}Byla jsem tady několikrát ještě před navrácením.
{18508}{18619}Příbuzný z matčiny strany|bydlí nedaleko odsud.
{18625}{18747}Vyžírala jsem ho tam dva měsíce|před vstupem do Mithrilu.
{18753}{18777}Spackala jsem to.
{18786}{18813}Spackala?
{18831}{18908}Poté co mě vyhodili od námořní pěchoty.
{18917}{18983}Jsem neměla vůli pro práci...
{18984}{19052}ani pro návrat domů do New Yorku.
{19058}{19114}Nechtěla jsme čelit rýpání od mého otce.
{19123}{19175}Tch!Ta nervoza.
{19181}{19236}Tvůj otec byl voják?
{19245}{19269}Přesně tak.
{19275}{19339}Stupidní pilot bombardéru.
{19345}{19422}Už odešel a nyní má vlastní společnost.
{19428}{19518}Byl to vždicky malicherný zbabělec,
{19518}{19577}co se staral pouze o svoje konspirace.
{19577}{19592}Konspirace?
{19598}{19619}Přesně.
{19625}{19718}Zatím co já hledala skutečnou práci po maturitě,
{19718}{19853}on byl jenom pro ty svoje podvody,|plánoval si mě vzít sebou na Harvard.
{19862}{19918}Byla jsem děsně naštvaná,bez žertu.
{19927}{20067}To je proč jsem ho neoptěžovala.|Připojila jsem se k mithrilu na den svatbi.
{20110}{20159}Zdrhla jsem přímo z kostela,
{20159}{20297}a šla jsem přímo do odvodové kanceláře|čtyři bloky dál,stále ještě|ve svatebních šatech.
{20303}{20389}Ten desátník na mě vyvalil oči takhle široký.
{20395}{20419}Zeptal se mě "Myslíte to vážně"?
{20425}{20491}Já odpověděla,"jistě".
{20497}{20590}Každý mě od toho odrazoval.
{20596}{20739}Říkali,"Paní Bridová,prosím rozmislete si to.|Vaši rodiče budou smutní".
{20745}{20788}Já jim řekla,
{20794}{20847}"Můj otec je u letectva."
{20856}{20919}Tak všichni řekli,
{20925}{21018}"Pak,to je snadné.Prosím zde se podepiště".
{21074}{21132}Jako co?Tenhle druh dívky...
{21138}{21162}To je opravdu skvělí.
{21168}{21245}Velmi dobrý.Správně,Uru?
{21248}{21275}To je opravdu skvělí.
{21345}{21381}Dobrý,huh?
{21402}{21491}Bylo to pak skutečně skvělí.
{21523}{21581}Poté co jsem udělala svoje rozhodnutí,
{21581}{21644}Cítila jsem jak se svět rožířil mimo mé obzory.
{21650}{21710}Cítila jasem že můžu dokázat cokoliv.
{21716}{21765}Mohla jsem jít kamkoliv se mi zachtělo.
{21794}{21815}Kamkoliv?
{21881}{21953}Hodně se od té doby stalo.
{21959}{22041}Zkusila jsem porážku a sklamání.
{22053}{22140}Přesto stále věřím|že jsem si vybrala správnou cestu.
{22152}{22255}Mám se ráde ještě víc než předtím.
{22267}{22329}Správně,takhle to bylo.
{22383}{22466}Právě jsem si vzpoměla na tohle,|po tom co jsme přišli sem.
{22469}{22513}Prosím nemysli na to.
{22574}{22642}Lituji že jste museli čekat.
{22651}{22752}Jsem Hunter z Hong Kongské zpravodajské divize.
{22812}{22869}Jak všichni víte,
{22875}{22986}obě Severní i Jižní armády jsou nervozní.
{22995}{23130}Provedeme naši operaci opatrně abysme se|vyhnuli oběma znepokojeným stranám.
{23133}{23254}Obě strany udržují svojí obranu.
{23257}{23308}Zabránili přístup k jejich přístavům.
{23314}{23365}Navíc,většina letů bylo zrušeno.
{23371}{23462}Kvůli tomu,ceny akcií a kurs měny klesl.
{23468}{23561}Hong Kong upadá ve více než jednom smyslu.
{23567}{23628}A co cílový AS?
{23634}{23739}Jako obyčejně,|jeho místo pobytu je neznámé.
{23745}{23890}Naposledy se obějil v 1015 hodin v|Saukeiwanu na Hong Kongském ostrovu.
{23893}{23983}To je uvnitř města,správně?
{23989}{24043}Nemůžu to potvrdit,
{24049}{24142}ale naši analitici a AI jsou tohoto předpokladu.
{24148}{24213}Moje dlouholeté zkušenosti dosvědčují to samé.
{24219}{24305}V každém případě,je to vše zde.
{24353}{24384}A co to?
{24487}{24583}Výjma předměstí a malých ostrovů,
{24590}{24658}budeme provádět hledání v této|oblasti spolu s helikoptérou.
{24664}{24768}Anti-ECS senzory nebudou|fungovat uvnitř města.
{24774}{24831}Tak můžeme hledat|jenom v jedné oblasti najednou.
{24837}{24937}A není třeba hledat v|oblastech s holuby a vránamy.
{24943}{24977}Co je s ptáky?
{24983}{25071}Zdá se že ptáci mohou vidět AS.
{25077}{25202}Pravděpodobně proto že ECS není|schopný se v ultrafialovém spektru schovat.
{25208}{25278}Ptáci,speciálně vrány,vždy reagují.
{25284}{25335}Psi také.
{25344}{25423}Jsou velmi citliví na ozonový štít ECS.
{25423}{25449}To je pravda.
{25472}{25494}Něco jiného?
{25573}{25613}Myslím že je to vše.
{25777}{25809}Nějaké připomínky?
{25818}{25880}Ne...vážně nic.
{25952}{26030}Mám pocit že je to vyřešené.
{26042}{26189}Těchto 49 oblastí na Hong Kongském ostrově|a 78 lokací v Kowloonu...
{26189}{26290}oddělíme,|můžeme všechny pokrýt do jednoho dne.
{26296}{26364}Jestli je situace příznivá.
{26467}{26602}Chlape,ten divnej patron je dobrej|ve svých povinostech.
{26681}{26740}Skvěle,odjíždíme.
{26746}{26808}Platí stanné právo,buďte opatrní.
{26814}{26908}Co když potkáme policii nebo armádu?
{26914}{26989}Je tam mnoho jednotek na které|nemá Hunter žádný vliv,správně?
{27007}{27028}Správně.
{27034}{27136}Běžte jestli můžete,|ale nemáte povolené zahájit palbu.
{27145}{27216}Armáda je nevinná.
{27222}{27355}Jestli vás chytí,budete vystavení krutému|výslechu než bude Huntre schopen|cokoliv udělat,přesto...
{27355}{27435}nic neprozraďte,|dokonce i kdyby vás mučili.
{27435}{27450}To je vše.
{27450}{27500}To je tvrdý...
{27506}{27592}Raději dvakrát přemýšlejte o vaší akci,|kdyby vás chytili.
{27598}{27711}Jestli tě zabijou bez mého vědomí a souhlasu,|neprominu ti to!
{27714}{27740}Rozuměl?
{27737}{27758}Rozuměl.
{28653}{28690}Jsem šokována.
{28696}{28764}Nikdy jsem neviděla centrum takovýhle.
{29410}{29499}Tak tedy,chystáme se to udělat hladce?
{29505}{29559}Jestli Hunter kontaktoval zátaras...
{29589}{29612}Zastavte!
{29621}{29658}Mao,teď to záleží na tobě.
{29655}{29688}Rozumím.
{29691}{29718}Stáhni okno.
{29741}{29765}Rozumím.
{29762}{29795}Stáhni okno.
{29887}{29992}Jsme pracovníci z Hantrovi|úklidové společnosti s.r.o.|Jsem si jista že jste byly informováni.
{30094}{30160}Co přepravujete v zadu?
{30160}{30279}Jak vidíte jenom čistící pomůcky.|Nějaký problém?
{30282}{30311}Ne.Je to v pořádku.
{30362}{30400}Říká že můžeme projet.
{30729}{30763}To je vzácné.
{30766}{30858}Tenhle tunel byl vždy zacpaný dopravou.
{30870}{30888}Rozumím.
{30897}{31004}Kdokoliv by byl šokovaný|kdyby viděl Hong Kong předtím.
{31033}{31072}Představ si to.
{31084}{31179}Kdyby se Tokyo ukázalo být|jako tohle,co bys udělal?
{31185}{31356}Shinjuku a Ginza jsou rozděleni na dva.|Obě strany jsou na pokraji války mezi sebou.
{31362}{31499}Město s vyšňořenejma holkama na nákupech,|nebo město těšící se ze zmrzliny,
{31499}{31567}by se stalo místem pro obrněná vozidla a AS.
{31568}{31722}Pláže pro lidi co vychází na procházku|jsou nyní složené z bunkrů a skrytých zákopů.
{31722}{31798}Tenhle laskavý Hong Kong,to je příliš jiné.
{31804}{31834}Je to všechno šílený.
{31982}{32014}Co je špatně?
{32023}{32070}Ni...nic.
{32577}{32609}Jaké překvapení.
{32618}{32681}Jižní armáda nás také nechá projít tak snadno.
{32776}{32851}Tenhle Hunter musí být opravdu někdo zvláštní.
{33885}{33925}Téměř jsme tam.
{33934}{34012}Co uděláme jestli to bude opravdu tady?
{34021}{34078}Nemysli na to.To je již...
{34274}{34316}Sagaro,uklidni se!
{34316}{34403}Zmátli tě!
{34664}{34696}Cos to udělal?
{34696}{34756}Co si to za řidiče?!|Vylez z tama!
{34804}{34850}Nechej to na mě.
{34850}{34883}Drž zavřenou hubu!
{34880}{34908}Já...
{34905}{34949}Dost,nic nedělej!
{35016}{35106}Omlouvám se.Byl to řidičův...
{35103}{35127}Zavři hubu!
{35154}{35187}Vylez!
{35352}{35409}Poslouchejte!Hmátli jste vedle!
{35406}{35470}Řidiči se dostal prach do očí!
{35467}{35522}Takhle nemůžeme pomoct!
{37131}{37187}Okamžitě nahlašte škody!
{37187}{37227}Tady někdo je!
{37224}{37272}Rychle sem přineste nosítka!
{37269}{37325}Dejte do karantény tuhle oblast,|zavolejte velitelství!
{37325}{37435}Na tohle teď není čas.
{37435}{37500}Budu předstírat že jsem nic neviděla.
{37509}{37530}Jedeme.
{37566}{37654}Jet na červenou.Opravdu si to udělal.
{37700}{37729}Omlouvám se.
{37748}{37805}Pořád myslíš na ni?
{37869}{37919}Zapomeň na ni!
{37922}{38010}Jestli to neuděláš tak padej z auta!
{38058}{38097}Rozumím tvojí situaci.
{38100}{38210}Přesto nejsem někdo abych na tebe změnkla.
{38216}{38278}Nechci takhle umřít.
{38339}{38412}Jestli chceš tohle,budu mnohem bezpečnější sama.
{38491}{38517}Rozumím.
{38605}{38633}Lituji.
{38659}{38715}Nemůžu to na sebe vzít.
{38727}{38779}Pokračuj v misi.
{41861}{41895}Uvidíte v další epizodě.
{41895}{41935}Přerušená mise..
{41935}{41994}Já,který stratil všechno,
{41994}{42060}potuluju je nazdařbůh ulicemi Hong Kongu...
{42072}{42116}Nemám místo kam bych šel.
{42116}{42189}Nemám už déle vlastního klidu.
{42198}{42275}V další episodě:Jeho problém.
{42275}{42397}Nemám žádný čas na zhojení mého prázdného srdce.|Situace se zhoršila ještě více.
