{1}{1}29.970
{300}{450}Full Metal Panic Second Raid
{2790}{2808}Díl 6.:Okraj nebe
{2802}{2841}Díl 6.:Okraj nebe|Starověcí Řekové.
{2862}{2880}Středozemní Moře.
{2940}{2986}Říše Wei,Wu,Shu.
{3003}{3033}Sjednocená dynastie Jin.
{3123}{3138}Oh,člověče...
{3234}{3282}Říkala jsem mu že s takovouhle selže.
{3327}{3347}Omlouvám se...
{3367}{3387}... že jdu pozdě.
{3461}{3528}Sagaro!|To jste přišel na test takhle najednou?!
{3537}{3598}Nejste v pozici abyste to bral na lehkou váhu!
{3613}{3686}Ano pane!Moc se omlouvám,já...
{3677}{3748}Nevadí.Rychle si sedněte.
{3762}{3784}Rozumím.
{4257}{4357}O misi tehdy v tunelu|na řece Nanjing Yangtze...
{4376}{4504}Vy jste byl jedinný odpovědný za zmatek|na komunikační lince|a maření operačního postupu.
{4517}{4539}Správně?
{4596}{4609}Odpověz!
{4689}{4755}Nevým chlapi o čem to mluvíte.
{4775}{4786}Dělej!
{4792}{4807}Ano,pane!
{5091}{5152}Bez obav,brzo to už skončí.
{5185}{5242}To nebude stačit i kdybyste|mu zlámali všechny prsty.
{5279}{5325}Zastav to!
{5350}{5368}Rozumím..
{5381}{5393}Řeknu vám všechno...
{5390}{5443}Tak,prosím...přestaňte...
{5459}{5600}Jste ten pachatel,který vypouštěl|naše informace během mise v tunelu?
{5600}{5665}Máte pravdu...Byl jsem to já!
{5671}{5698}Kdo si vás na to najal?
{5701}{5713}Nevím.
{5722}{5743}Lžete!
{5752}{5791}Počkejte...Já to opravdu nevím...
{5803}{5839}Já neznám jeho pravou totožnost...
{5856}{5998}Tvrdil že je agent z Amalgamu.
{6052}{6112}Nic než to,víc už nevím.
{6127}{6142}Je to pravda.
{6169}{6249}Myslel jsem že by mohli být|z Ruska nebo jiného státu.
{6275}{6319}Byl to jednoduchý úkol.
{6330}{6381}Zaplatili mi 200,000 předem.
{6401}{6454}Bylo to 200,000...
{6462}{6501}Nebyl žádný způsob,|jak bych to mohl odmítnout.
{6513}{6528}Jdeme.
{6604}{6653}Nějaká slitina vyrobená z rtutě.
{6689}{6733}Zdalipak to jméno má význam.
{6760}{6853}Miseli si uvědomit že Mithril|je smýšlený kov.
{6874}{6899}Nevím...
{6927}{6990}Ale...To bylo stále hrozné.
{7012}{7036}Míníte výslech?
{7051}{7144}Přestože je to nepopiratelné,|nebylo to nic co by ohrozilo život.
{7175}{7214}Já vím,přesto...
{7250}{7336}Kdybych tam byl já,|už bych měl jeho prsty uříznuté.
{7402}{7505}Admirál má právě telefonát,|ale můžete jít dovnitř,Kapitánko.
{7533}{7617}Jacksone,prosím neříkej mi Kapitáne.
{7617}{7739}Ale,na místě jako je toto,|by to nebylo vhodné slečno.
{7767}{7869}Rozumím.Sami rozhodneme v|tom případu nevhodného chování.
{7884}{7960}Samozřejmě,|budeme se držet záznamu z výslechu.
{7997}{8010}Co?
{8042}{8119}O tom problému promluvíme později.
{8128}{8174}Mám hosty.Končím.
{8267}{8317}Je potěšení mít vás tady.|Dáte si něco k pití?
{8327}{8383}Děkuji...Dala bych si obyčejnou vodu.
{8388}{8406}Nadporučíku veliteli?
{8416}{8433}Dám si to samé.
{8452}{8500}Hey,hey.Jak nudné.
{8579}{8646}Velitel zpravodajské divize právě volal.
{8669}{8733}Zpravodajská divize nás|chce požádat o předání Bluena?
{8745}{8793}Samozrejmě jsem odmítl.
{8821}{8939}Vapadá to že se jim nelíbí fakt,že|jsme zatkli Bluena bez jejich vědomí.
{8976}{9042}Mimochodem,pozorovala jste výslech?
{9075}{9090}Ano.
{9127}{9201}Pokud chcete pokračovat jako Kapitánka flotili,
{9210}{9327}budete potřebovat svědka těchto|věcí a dovědět se o nich víc.
{9366}{9424}To je cesta kterou musíte následovat.
{9514}{9553}Nepřemýšlejte o tom příliš mnoho.
{9570}{9596}Brzy porozumíte.
{9625}{9678}Blueno začal mluvit.
{9690}{9705}Co řekl?
{9719}{9772}Amalgam.|Zní to jako název nějaké organizace.
{9852}{9889}Víte o něčem?
{9898}{9936}Ne,ale..
{9969}{10074}Vysvětluje to událost v Perio Archipelagu|a nedávný incident v Nanjingu.
{10099}{10220}Jestli je za tím vším nějaká organizace,|která měla na nás odzačátku spadeno...
{10233}{10374}Pak,bychom potřebovali korigovat a|přeskupit naši aktualní infrastruktůru.
{10427}{10473}Tím míníte?
{10492}{10544}Zaprvé,pokud jde o Kaname Chidori.
{10544}{10616}Jsme včera dostali údaje|od zpravodajské divize.
{10692}{10918}Po zvážení případu Whispered,jsme se|rozhodly stahnout její ochranku.
{10935}{10981}Je tam také problém z Wraithem.
{11040}{11140}Jsem si jist,že spůsobem kterým jsme|to dělali doteť nebyl velmi účinný.
{11157}{11209}Máte pravdu,ale...
{11213}{11231}Copak?
{11260}{11307}A co Seržant Sagara?
{11324}{11401}Nědělejte si o něho starosti.|Má již důležitý úkol,pilotovat ARX-7.
{11417}{11450}Je to důležitý voják.
{11480}{11524}Mylím si ,že toto je jeho příležitost.
{11574}{11601}Máte něco jiného co chcete říct?
{11714}{11727}Ne...
{11796}{11866}Omluvil ses pořádně paní Kagurazakové?
{11886}{11967}Udělal jsem to.|Musel jsem slíbit že ji opravím auto tuto neděli.
{11981}{12138}Chlape...Dokonce když pomineme tvoje credity,|tak bys mohl skončit za takovýhle kousky.
{12144}{12162}Máš pravdu.
{12169}{12203}Neříkaj to tak,jako kdyby|to byl problém někoho jiného.
{12226}{12261}Ale,Sagaro.
{12277}{12349}Kde jsi byl během|poloviny zkouškového období?
{12365}{12388}Musel jsem se postarat o naléhavý obchod.
{12455}{12485}Je všechno v pořádku?
{12503}{12556}Vypadáš jako že máš nějaké starosti.
{12574}{12590}Bez problému.
{12627}{12646}Vidím.
{12891}{12917}Mimochodem...
{12944}{13025}Sagaro,tvoje vlasy v|poslední době pěkně vyrostly.
{13060}{13108}Teď když jses o tom zmínila.|Jsem si také všimla.
{13134}{13149}Vypadá to divně?
{13168}{13212}Ve skutečnosti ne,ale...
{13231}{13324}Chodíš do Tokoya pravidelně?
{13330}{13358}Co je to Tokoya?
{13370}{13384}Holič.
{13402}{13455}Ne,já si většinou vlasy uřežu.
{13525}{13562}Vím co máš na mysli.
{13604}{13677}Hey,hey!Právě jsem na něco přišla.
{13684}{13777}Proč nevezmeme Sagaru do salonu?
{13783}{13851}Můžeme ti nějak změnit image.
{13866}{13934}Salon?Na místo holiče?
{13934}{14113}Ano.Možná by pak nevypadal tak chaldně,|kdyby měl učes normálního středoškoláka.
{14116}{14179}Eh...Myslíš si?
{14197}{14257}Ale,není žádný způsob jak,|by v první řadě souhlasil...
{14256}{14277}Dobře,jdeme.
{14330}{14423}To je tam kde normální středoškoláci|dostávají svoje účesy,správně?
{14536}{14574}Prosím nějak mu to sestřihněte.
{14618}{14649}Tudy prosím.
{14709}{14835}To je vzácné od Sausukeho,|že vjenuje pozornost svému vzhledu.
{15008}{15127}Já mluvím o tvojim plánu pro život.|O tvojí budoucnosti!
{15142}{15183}Je ti pořád ještě 17,ne?
{15189}{15278}Přemýšlel jsi vůbec|někdy o svojí budoucnosti?
{15285}{15351}V pořádku,začneme tím že vás umyju.
{15546}{15567}Hey...!
{15618}{15662}Nic,prosím pokračujte.
{15737}{15815}Hey,tenhle časopis přináší styl Mohican.
{15821}{15845}Ah,máš pravdu.
{15885}{15923}Ty máš někde citlivý bod?
{15932}{15947}Ne.
{15986}{16030}Cítím se bezmocný.
{16091}{16179}Není třeba dělat si starosti.|Je to jenom normální šampon.
{16197}{16231}Je to jenom normální pomocník.
{16299}{16377}Normálně bych se tomu vyhnul,ale...
{16406}{16426}Je to jenom ručník...
{16438}{16580}Ročník-ručník-ručník-ručník-|ručník-ručník-ručník-ručník..
{16592}{16640}OK,teď začnu stříhat.
{16650}{16778}Ručník je tu jenom pro to|aby mi nepadaly vlasy na šaty.
{16795}{16857}Není tu proto aby omezil|moje ruce v pohybu.
{16860}{16933}A tohkle jsou jenom normální...|normální-normální-normální...nůžky!!
{17004}{17020}Nehýbej se!
{17258}{17279}Znova...?
{17799}{17882}Správně,bude to dobrá změna pro něho.
{17919}{17962}Je to moje chyba.
{18150}{18210}Tos byl ty kdo mi řekl ať ho tam vuzmu.
{18216}{18260}Proč jsi to udělal?
{18272}{18293}Omlouvám se.
{18320}{18372}Nakonec nás z toho obchoďáku vyhodili.
{18380}{18459}Dokonce nás obvinili jako bláznivé delikventy.
{18466}{18609}Ale je to příliš nebezpečné dovolit cizincům|zacházet s otrými předměty když seš bezbraný.
{18615}{18647}To vidím.
{18659}{18723}Jestli je tohle ten důvod,tak si mě v první řadě|neměl žádat abych tě brala do toho salonu.
{18732}{18830}To jsi tohle nemohl tušit od začátku?
{18841}{18943}Víš,ten nevinný holič mohl být zraněn|kdybys udělal nějakou chybu.
{18971}{19080}To nemůžeš jednou za čas|zapomenout na vrahy a nepřátelé?
{19107}{19142}To nemůžu udělat.
{19145}{19199}Nepřátelé existují.To je fakt.
{19225}{19276}Můžou tě kdykoliv napadnout.
{19305}{19328}To je...
{19344}{19446}Mojí hlavní prioritou je|ochránit tě před nepřítelem.
{19559}{19572}Přesto...
{19628}{19745}Na tohle jsem myslel vždy,|od té doby co jsem přijel před půl rokem.
{19802}{19882}Ačkoliv je pravda že se sem|už žádný nepřítel nevrátil.
{19904}{19950}Tak já způsobuji problémy každodenně.
{20007}{20047}Samozřejmě také tobě.
{20224}{20284}To už bylo půl roku,huh?
{20529}{20613}Ačkoliv je pravda že jsi neudělal žádný pokrok.
{20654}{20672}Je to tak?
{20720}{20735}Je.
{20959}{21052}Hey,proč se nezastavíš u mě doma?
{21075}{21174}Vkaždém případě potřebuješ ostříhat,|jestli mě necháš tak bych to udělala.
{21232}{21246}Nechceš?
{21243}{21281}Ne,to je jen...
{21316}{21363}To nevěříš ani mě?
{21406}{21456}Tak to není.S tebou je to jiné.
{21698}{21793}OK,pane.Jak to chcete?
{21876}{21896}Není to těsné?
{21908}{21943}Ne,bez problému.
{22060}{22107}Vpořádku.Poďme na to.
{22253}{22270}Ano?
{22284}{22333}Máš vůbec nějáké|skušenosti se stříháním vlasů
{22339}{22351}Ani ne.
{22450}{22561}Ale...Hrála jsem si s vlasy Kyoko.
{22567}{22602}Tohle je poprvé co stříhám.
{22649}{22736}Bez obav.Je to lepší než|kdyby sis je stříhal sám,správně?
{22784}{22829}Jen mi neodstřihni moje uši...
{22844}{22869}Zkusím to.
{23329}{23346}Co se děje?
{23388}{23466}Vynechal jsi test kvůli práci?
{23500}{23516}Správně.
{23550}{23588}Znovu jsi bojoval?
{23615}{23627}Správně.
{23648}{23663}Co stím?
{23678}{23693}Nic.
{23741}{23780}Měli jste nějaká zranění?
{23803}{23866}Jenom nějaké lehké|škrábance,bez problému.
{23920}{23935}Vidím.
{25088}{25191}Sousuke,byli jste víc obezřetní než obvykle?
{25206}{25218}Kdo?
{25278}{25295}Ty o tom víš?
{25310}{25366}Ano.Jestli jste byli jako ty dneska.
{25395}{25439}Ne,ty si vymýšlíš.
{25525}{25665}Předtím jste se také hádali,|ale teď jste opatrnější.
{25749}{25831}Nejsem zase znovu cílem?
{25878}{25916}Proč si to řekla?
{25948}{25969}Sehni se.
{26004}{26057}Ale,hodně věcí se doteď vyskytlo.
{26209}{26253}Bez obav.To není nepřítel.
{26275}{26358}Je tam další osoba,|která tě sleduje jako záloha.
{26380}{26397}Někdo koho znám?
{26418}{26440}Je to Kurz?
{26461}{26512}Ne,je to někdo koho neznáš.
{26531}{26562}Vlastně,ani já nevým kdo to je.
{26589}{26610}Vidím...
{26636}{26689}Nemůže odhalit svojí totožnost...
{26710}{26758}...nebo svou tvář.
{26805}{26910}Zdalipak by mi pomohl kdyby mě napadli...
{27157}{27176}Víš co?
{27229}{27314}Jsi jediná osoba které věřím,Sousuke.
{27460}{27476}Děkuji ti.
{27532}{27568}Není zač.
{27674}{27717}Můžeš se trochu natočit do prava?
{27744}{27756}Jistě.
{27759}{27799}Ne takhle.Naopak.
{28169}{28225}Myslím si že tomu přijdu na kloub.
{28491}{28523}Skvěle,hotovo!
{29288}{29344}OK!!Teď se chystám to spláchnout!!
{29646}{29676}Hey,kam jdete?
{29683}{29740}Dneska by se tady nemělo nic dít...
{29831}{29876}Hey,prestaň.
{29907}{29989}Co to je?Náhlý sváděcí útok?
{30001}{30130}Hmm?Já vím.Budu tam později.
{30586}{30672}Co?Ta koťata utekla?
{30680}{30740}To tady byly nespokojené?
{30753}{30875}I když jsou neplnoleté...Neudržel jsem je.|Vyšel jsem jim vstříc.
{30878}{30920}Nevím o tom.
{30930}{31017}Vzali CHODARM a utekly.
{31017}{31044}Cos to řekl?
{31047}{31145}Argh.to je zbytečný rozhovor.
{31148}{31175}Spoj mě snimi!
{31172}{31220}Roger!Změnil jsem komunikační kanál.
{31392}{31488}Slyšíš mě?Ty nezbedná Lolito.
{31495}{31545}O co se to pokoušíte?
{31569}{31593}Co chceš?
{31610}{31718}Kam chcete jít s tou drahou hračkou?
{31742}{31773}Kamkoliv se nám zlíbí.
{31819}{31905}Nadále budeme dělat cokoliv se nám zachce.
{31957}{32000}Kdo si vás najal?
{32013}{32154}Neříkej mi že plánujete|navštívit Mithril stím co máte?
{32160}{32194}Samozřejmě že chceme.
{32197}{32212}Co?
{32230}{32282}Chystáme se zabít ty děcka...
{32296}{32326}...pro Senseiho.
{32609}{32656}Omlouvám se,|tohle jsou jenom zbytky ze včerejška.
{32671}{32707}Ne,je to dobré.
{32855}{32875}Co je špatně?
{32872}{32905}Eh?Nic!
{32999}{33139}Vlastně...|Pořád máš kolem sebe ty děsivé zbraně?
{33197}{33262}To nikdy nic neděláš co|je klidnější a bezpečnější?
{33265}{33283}To je jen...
{33321}{33371}Možná že si vezmu něco jako ty na mě.
{33407}{33464}Vidím.To je dobrý nápad.
{33515}{33596}Slzný plyn,pouta,baterka...
{33615}{33714}I když je to použitelné.|Připravil jsem pro tebe omračující zbraň.
{33741}{33798}Vždicky mě zajímalo kde míváš tyhle věci.
{33813}{33898}Ale,není tohle trochu nebezpečné?
{33909}{33931}Je to smrtící?
{33944}{34075}To jen dává několik málo ticíc voltů přes dráty.
{34100}{34143}Normální chlap by neměl umřít.
{34156}{34287}Ale...to je normální chlap.|A co žena nebo dítě?
{34301}{34406}Chodiri,my nemůže být milosrdní v této době.
{34423}{34507}Pouze podřadná osoba by si|olizovala rty před kořistí.|(pozn.Tím míní"pouze stupidní osoba by|dělal stupidní věci v jeho posledním momeňtě")
{34539}{34627}Přežije pouze nejschopnější.
{34742}{34790}Díky dnes za všechno.
{34821}{34902}Kdybys potřebovala tak bych tě taky ostříhal.
{34907}{34932}To absolutně nepříchází v úvahu.
{35090}{35149}Překvapíš zítra Kyouko,OK?
{35248}{35324}Také dbej abys mi vrátil můj zápisník.
{35334}{35351}Samozřejmě.
{35363}{35395}Omlouvám se za potíže.
{35417}{35462}Jestli ho znova zapomeneš jako předtím,
{35474}{35536}tak se pak celou cestu budeš pro něho vracet.
{35545}{35614}Ne,tentokrát si na to rozhodně vzpomenu.
{35846}{35882}Dobrá tedy...Je čas na odchod.
{35898}{35951}Ok,uvidíme se.
{35976}{35995}Uvidíme se zítra.
{36372}{36442}Možná bych mu měla příšte|pomoci vybírat oblečení.
{36928}{37004}Jsi jediná osoba které důvěřuji,Sousoke.
{37095}{37115}Dobrá.
{37738}{37828}PŘÍKAZ NEJVYŠŠÍ PRIORYTY 05J005-3128
{37840}{37924}191121Z HQ ZE ZÁPADOPACIFICKÉ FLOTILI.
{37968}{38057}ŘÍDÍCÍ HQ-AKTUÁLNÍ OPERACE
{38061}{38150}05E001-3128 V 1500 HODIN
{38153}{38245}BYLA ZRUŠENA
{38248}{38341}URZU 7 JE STAŽEN Z BEZPEČNÉHO DOMU
{38344}{38434}VRAŤTE SE NA ZAKLADNU OSTROV MERIDA,|IHNED POUŽIJTE CESTOVNÍ ROZKAZ-3B
{38437}{38528}OCHRÁNCE KANAME CHIDORI-|AGENT KODOVÉOZNAČENÍ "WRAITH"
{38531}{38610}PŘEVEZME OPERACI
{38625}{38712}KONTAKT S KANAME CHIDORI|JE NADÁLE ZAKÁZANÝ
{41893}{41908}Uvidíte v další epizodě.
{41905}{41951}Uvidíte v další epizodě.|Nebyl tam žádný záměr pro útěk.
{41966}{42007}Nebyl tam žádný úmysl opustit ji.
{42027}{42066}Neočekávaný zakázkový list.
{42079}{42125}Nešťastný rozhovor s duchy zemřelých.
{42157}{42214}V příští epizodě:Left behind
{42248}{42305}Pevné prohlášení,které nemůže být bojovné.
{42323}{42395}Tam je pouze bezmocnost|beroucí se z mé duše.
