{1}{1}23.976
{53}{133}/Jinı den/
{172}{276}/Jinı svìt/
{318}{364}/a/
{427}{583}/Jiné vzpomínky na/
{1078}{1133}Je ráno. Je urèitì ráno.
{1147}{1253}Dùkazem faktu, e jsem ve vlaku, |kterı smìøuje smìrem k Sumisoøe,
{1383}{1441}ale proè jsem tu jedinı?
{1458}{1572}Obvykle je plnı studentù niší støední, |vyšší støední, a obchodníkù.
{1572}{1760}Mìlo by bıt pro mì nemoné získat místo.
{1760}{1797}Je to nìjaké spiknutí?
{1797}{1883}Nebo jsme byli uneseni mimozemšany?
{1883}{2015}Nebo pravdìpodobnì, pøedtím, ne jsem odjel| do Sumisory, obyvatelé mìsta u byli pryè.
{2015}{2123}Nikdo by nemohl slyšet o vyššsí støední škole Sumisora...
{2141}{2203}Jako by kadı den bylo tohle všechno prázdné.
{2258}{2337}Jo správnì, jako by. Je to víc |tak, e se probudili døíve.
{2458}{2505}To je... um...
{2505}{2532}To je...
{2874}{2893}Huh?
{2944}{2977}Umm...
{3003}{3031}Ah! Oh, ne.
{3147}{3166}Pospìš a vystup.
{3182}{3203}Ano.
{3255}{3270}Hej, ty!
{3270}{3292}Sakra, pojïme.
{3455}{3469}Jsi v poøádku?
{3469}{3536}Jo, dìkuju ti mnohokrát!
{3659}{3766}-Bez ohledu na to, co mùe pøijít, kdy jsme ztraceni,-
{3766}{3865}-bez ohledu na to, jak daleko utíkáš,-
{3865}{4018}-záøivé ráno urèitì pøijde.-
{4018}{4309}TaSHee's Gang uvádí|MEMORIES OFF
{4339}{4499}-Oèekávání tvého znepokojení,-
{4530}{4705}-staneš se zbabìlım, zanevøeš na sebe.-
{4722}{4804}-Lidé se nìkdy-
{4815}{4895}-bojí zítøka,-
{4909}{5129}-tak se vrací do høejivého dìtství.-
{5129}{5251}-Bez ohledu na to, co mùe pøijít, kdy jsme ztraceni,-
{5251}{5338}-bez ohledu na to, jak daleko utíkáš,-
{5338}{5505}-chci ti vìøit bez ohlíení se.-
{5505}{5622}-Bez strachu ze zranìní se,-
{5622}{5715}-otevøu nové dveøe,-
{5715}{5869}-a jemnì zavøu tvùj deštník.-
{6011}{6113}/Zlaté moøe/
{6144}{6163}Nech mì ti to vzít.
{6201}{6218}Pojïme.
{6244}{6262}Díky.
{6358}{6394}Ibuki-san, jsi èlenkou vıtvarného krouku.
{6394}{6544}Ano, miluju kreslení. Právì teï jsem dìlala|hrubı náèrt kvìtiny a ztratila jsem pojem o èase.
{6544}{6611}Tak to proto jsi vystupovala |z vlaku na poslední chvíli.
{6624}{6733}Omlouvám se, kvùli mì, máš také zpozdíš do školy.
{6761}{6801}Nedìlej si s tím starosti.
{6834}{6991}V kadém pøípadì, mìl bych dìkovat Boku, e jsem |poznal tak roztomilou mladší spoluaèku jako je Ibuki-san.
{7002}{7030}Um...
{7030}{7102}Ah, øekl jsem nìco, co bych nemìl?
{7117}{7140}Ne, tak to není.
{7157}{7294}Jen, e jsem v prvním roèníku, a nezdá|se bıt pro tebe správne, abys byl tak formální.
{7328}{7382}Oh? Je to?
{7394}{7484}Je to! Take mi prosím øíkej Minamo.
{7508}{7570}Dobrá, Minamo-chan.
{7584}{7602}Jo.
{7737}{7771}Je to kamarádka?
{7807}{7846}Je to kamarádka, kterou znám u dlouhou dobu.
{7952}{7970}Dívka-kamarádka, eh?
{7970}{8012}Ale co ty, Tomo-chan?
{8025}{8072}Jakı druh vztahu máš s Minamo-chan?
{8096}{8167}Neøíkej mi, e randíte za mımi zády!
{8184}{8225}Co to najednou všechno povídáš?
{8225}{8295}Jo, Yue-chan. Tak to není.
{8295}{8322}Opravdu?
{8322}{8376}Zrovna dneska jsme se poznali.
{8393}{8476}Hmm... No, tak je to v poøádku.
{8491}{8546}Oh správnì, potøebovala jsi na nìco mou pomoc?
{8615}{8700}Zajímalo mì jestli bys mi mohl pomoct s mım stylem psaní.
{8700}{8805}Stylem psaní? Pomoc Tomy-chan? Jsi si jistá?
{8819}{8927}Jo, nechala jsem nìjaká prázdná místa, |a opravdu tomu nerozumím.
{8927}{8991}Oh, to proto.
{9095}{9130}Tomo-chan ti s tím mùe pomoct.
{9145}{9171}Prosím pomoz mi.
{9336}{9406}Dobrá, jestli opravdu chceš, abych ti|pomohl, mùu tì kdykoli uèit.
{9410}{9433}Opravdu?
{9452}{9503}Aèkoli nevím, jak moc ti mùu pomoct.
{9530}{9550}Kdy chceš, abych ti pomohl?
{9550}{9648}Dneska! Nebo, co zítra po škole?
{9664}{9678}Jistì.
{9696}{9748}Vıbornì! Dìkuju mnohokrát.
{9748}{9813}Je v poøádku setkat se tady?
{9813}{9832}Jo, je to v poøádku.
{9832}{9952}Tomo-chan, bez ohledu na to, jak roztomilá |Minami-chan je, radìji bys nemìl dìlat ádné pohyby.
{9982}{10014}Neudìlal bych nic takového.
{10179}{10200}Co je to s tebou?
{10229}{10266}Oblièej Tomy-chan je celı èervenı.
{10425}{10443}Vstaòte.
{10464}{10478}Ukloòte se.
{10478}{10561}Nezapomeòte na zápis, protoe to bude na testu.
{10905}{10923}Tomoyo.
{10959}{11048}Nemìl bys dìlat takové smutné oblièeje, Tomoyo.
{11097}{11112}Ayako.
{11467}{11568}Kdy dìlát takové oblièeje, nemùu se uvolnit.
{11761}{11815}Aya... Ayako! Jsi v poøádku!
{12310}{12334}Koneènì jsi se vzbudil.
{12356}{12380}Uvidím tì pozdìji, Minamo-chan.
{12380}{12433}Jistì. Díky, Yue-chan.
{12570}{12634}Yue mì prostì mìla vzbudit.
{12646}{12722}Není to její chyba. Zastavila jsem ji pøi buzení tì.
{12733}{12803}Tak jsme si mohly Yue a já chvíli povídat.
{12897}{12912}Jsem hotová.
{12932}{12947}U?
{12963}{12984}Uka mi to.
{12984}{13077}Ne, pøeètu to. Jen poslouchej.
{13123}{13223}Dívka se zeptala "Co to tak záøí, bílı balónek?"
{13223}{13340}Øekl jsem, e se to nazıvá veèerní rosa.
{13340}{13466}Ale v tu dobu, jsem pøemıšlel, e bych| radìji zmizel s veèerní rosou.
{13499}{13520}No, jaké to je?
{13598}{13703}Je to jako báseò, kterou mùeš|pochopit, bez toho, aby se's cítil smutnì.
{13722}{13756}Je to smutná báseò, ne?
{13793}{13896}Ale mám ráda tu dívku. Závidím jí.
{13921}{13936}Proè?
{13936}{14045}Protoe byla unesena pro peníze,|a pak utekla opouštìjící svùj svìt.
{14045}{14124}Bıt vzata pryè osobou, kterou má ráda...
{14322}{14409}Omlouvám se. Taková vìc se nestává, správnì?
{14429}{14463}Tak jsem si myslela, e by to bylo hezké.
{14516}{14593}Lidé u nepíšou "Chci ti podìkovat", e?
{14652}{14690}Psaní? Jo, nepíšou to.
{14690}{14784}Stalo se z toho "Dìkuji ti", správnì?
{14805}{14889}Je to podivné, ne? Nepsat u "chci ti podìkovat".
{14916}{14997}Vdycky jsem chtìla pouívat, "Dìkuji ti".
{15096}{15124}U je pozdì.
{15156}{15184}Tady bychom mìli pøestat.
{15216}{15291}Tomoyo-san, máš stále nìjakı volnı èas?
{15291}{15346}Chci ti podìkovat za to, e mi pomáháš.
{15346}{15359}Podìkovat?
{15499}{15528}Tak dobré!
{15588}{15634}Nemáš hlad, Tomoyo-san?
{15665}{15719}Nebo nemáš rád sladké vìci?
{15748}{15879}Tak to není. V mém prvním roce na Støední škole| Sumisora jsme byl znám jako perfektní maniak.
{15879}{16016}Jen pohled na tuhle barvu a objem, je to perfektní.
{16016}{16115}Vıbornì, sním to! Budu jíst dokud nebudu plnı!
{16212}{16229}Díkybohu.
{16572}{16627}Kreslíš obrazy, správnì Minamo-chan?
{16627}{16641}Ano.
{16641}{16672}Jaké kreslíš?
{16701}{16749}Moje obrazy?
{16768}{16855}Jo, tak nìjak chci vidìt tvé obrazy.
{16958}{16974}Tady.
{16974}{17010}Je v poøádku, kdy se na nì podívám?
{17010}{17088}Jo. Jsi mimoøádnı, tak se na nì prosím podívej.
{17088}{17103}/Skicáø/
{17149}{17168}Wow!
{17425}{17446}Jsou opravdu dobré.
{17446}{17482}Myslíš si to?
{17570}{17597}Byla jsem poctìna.
{17639}{17654}Huh?
{17769}{17803}Nìco je špatnì?
{17803}{17827}Ne.
{17882}{17943}Cítím se tak nìjak nostalgicky.
{17943}{17990}Nostalgicky?
{18005}{18064}Ale jsou opravdu dobøe udìlané.
{18064}{18128}Proè jsi chtìla kreslit obrazy?
{18162}{18182}To je...
{18236}{18298}protoe vydrí navdy.
{18298}{18325}Navdy?
{18362}{18490}Protoe pocity a myšlenky tvùrce|mùou bıt v obrazech vidìny.
{18808}{18834}Tomoyo-san.
{18854}{18870}Co je to?
{18870}{18962}Mám další prosbu.
{19013}{19036}Sledovat padající listí?
{19054}{19163}Tuhle nedìle budu èekat v parku Sumisora.
{19163}{19252}Rande? Je to rande, správnì?
{19307}{19326}Tomoyo-san!
{19353}{19391}Minamo-chan.
{19433}{19456}Ahoj!
{19606}{19683}Ah! Kitami-san!
{19683}{19713}Co-Coe?
{19714}{19789}Myslet si, e tu byl druh vıborného |zeleného èaje na svìtì.
{19789}{19880}Po vypití tohoto, všechno ostatní,|co jsem vypil chutná jako blátivá voda.
{19911}{19967}Jsem tak šastnı, e jsem naivu!
{19967}{20005}Pøeháníš.
{20005}{20035}Ten Shin.
{20054}{20096}Jsou to hovìzí kulièky?
{20114}{20161}Jo, jsou to hovìzí rıové kulièky.
{20161}{20203}Jaj! Hovìzí kulièky!
{20223}{20269}Hovìzí Kulièky jsou tak roztomilé.
{20269}{20296}Roztomilé?!?
{20381}{20418}Yue-chan, jsou tohle...
{20458}{20484}Vysušené tìstoviny.
{20533}{20552}Vysušené?
{20618}{20681}Yue-chan, nauè mì, jak je dìlat!
{20681}{20758}Byly by skvìlé s chlebem.
{20758}{20778}Byly by?
{20778}{20863}Jaj! Víš, co? Yue...
{20880}{20904}Co se dìje?
{20948}{20989}Jsi unavená, protoe jsou všichni tak nadšení?
{20989}{21046}Ne, tak to není.
{21046}{21178}Pravdou je, e mé tìlo je slabé a|jsem poøád v nemocnici.
{21199}{21310}Toto je poprvé, co jsem se mohla bavit|se všemi, take jsem opravdu šastná!
{21310}{21331}Take proto.
{21482}{21506}Vidìl jsi to?
{21534}{21584}Jo, ten list mìl zlatavou barvu.
{21584}{21693}Je to tak krásné i kdy je to dejme tomu, mrtvı list.
{21693}{21851}Je to jako by list zkoušel to nejlepší,| co mùe, aby se dostal k oceánu.
{21914}{21930}Jo.
{21947}{21983}Tak úasné.
{21994}{22101}Nemyslíš, e je ten list úasnı?
{22119}{22312}Protoe je to jako by chtìl navdy|záøit zlatì jako oceán.
{22570}{22606}Dnes bylo hodnì zábavy, e?
{22606}{22663}Minamo-chan vypadala, e se hodnì bavila.
{22679}{22699}To je skvìlé.
{22787}{22860}Slyšel jsi o stavu Minamo-chan?
{22860}{22930}Jo, e je její tìlo slabé.
{22946}{22963}Jo.
{22980}{23080}Prosím buï pro mì na Minamo-chan milı.
{23080}{23095}Eh?
{23095}{23170}Protoe je to dívka-kamarádka.|/Co jsem tak hledala, tak gal pal znamená prostì dívka, |která se svou kamarádkou nemá sexuální, ale jen romantickı |vztah, no, take si to zkuste pøeloit :P/
{23206}{23232}Pospìšme domù.
{23477}{23511}Tak najednou prší.
{23564}{23595}Co je to za dopis?
{23654}{23749}"Budu na tebe èekat po škole u zadních dveøí. Minamo."
{23768}{23791}Minamo-chan?
{23854}{23873}Minamo-chan?
{23931}{23990}Co to dìláš bez deštníku?
{24005}{24267}Protoe jsem øekla, e tu na tebe budu èekat, take jsem |sem pøišla hned po vyuèování, ale pak, najednou zaèalo pršet.
{24267}{24353} Nedìlej si s tím starosti, musím tì| dostat do kanceláøe sestry.
{24408}{24433}Dr se pevnì.
{24466}{24504}Minamo-chan, nachladila jsi se, e?
{24522}{24633}Je mi dobøe. Mùeš jít trochu pomaleji?
{24650}{24670}Pomaleji?
{24670}{24817}Myslím, e by tì princezna v mé básni |taky poádala, abys šel trochu pomaleji.
{24844}{24951}Mùj sen se stává skuteèností. Není to zázrak?
{25087}{25109}Cítíš se teï lépe?
{25129}{25179}Jdu vyhledat uèitele.
{25202}{25231}Poèkej chvíli.
{25231}{25284}Ne, musíš odpoèívat.
{25305}{25382}Tomoyo-san, je tu nìco, co ti musím øíct.
{25382}{25482}Vìdìla jsem o tobì dlouho pøedtím, ne jsme se potkali.
{25497}{25541}Slyšela jsi o mì od Yue?
{25541}{25682}Ne, slyšela jsem o tobì od Ayaky-chan.
{25721}{25738}Ayaka?
{25738}{25821}Ayaka a já jsme sestøenice.
{25852}{25962}Posílala mi dopisy, kdy sjem byla v nemocnici.
{25962}{26064}Byla pro mì víc jako sestra.
{26064}{26185}V dopisech mluvila hodnì o Yue-chan a o tobì.
{26185}{26209}O tobì...
{26234}{26354}Kdy psala o tobì, musela bıt Ayaka-san šastná,
{26354}{26417}...protoe jsem byla šastná jen jejich ètením.
{26417}{26522}Díky ní jsem kreslila obrazy na støeše nemocnice.
{26596}{26681}Není to senzaènì nakreslené? Dostala jsem to od kamarádky.
{26724}{26755}Take, ten nostalgickı pocit byl...
{26755}{26791}Pravdìpodobnì kvùli tomu.
{26836}{26901}Omlouvám se, kvùli mì, Ayaka...
{26901}{27032}Kdybych nepoádal Ayaku, aby| vyšla ven v dešti, Ayaka by...
{27087}{27172}Tak nìjak k Ayace cítím lítost.
{27194}{27284}Cítím k Ayace lítost toho, koho tak moc milovala.
{27284}{27393}Nemyslím si, e by tì chtìla vidìt deprimovaného.
{27468}{27585}Vím, e Ayaka-chan s tebou musela bıt velmi šastná.
{27706}{27728}Tomoyo-san.
{27757}{27804}Je mi fajn. Teï jdu najít uèitele.
{27873}{27910}To je Minami-chan.
{27910}{27934}Stalo se to mım zavazadlem. Nechala jsem to tam,
{27988}{28087}od té doby, co jsem pìknì dobøe poznala zdravotní sestru.
{28107}{28144}Tak krásná kresba oceánu.
{28159}{28181}Nedívej se na to.
{28199}{28210}Proè ne?
{28210}{28331}Nejsem dobrá v kreslení oceánu. Pøeju si, |abych mohla nakreslit hustší a rozlehlejší oceán...
{28331}{28379}...tak jak vypadá oceán v noci.
{28416}{28444}Pak pøíštì pojïme.
{28460}{28476}Opravdu?
{28476}{28538}Jistì, vezmu tì.
{28564}{28663}Minamo-chan, pojïme spoleènì. Je to slib.
{28663}{28697}Jistì.
{28966}{28982}Ayaka.
{29080}{29097}Ayaka.
{29159}{29247}Teï jsem v poøádku.
{29362}{29375}Tomo-chan!
{29375}{29426}Brı ráno! Jsi tu brzy.
{29426}{29465}Minamo-chan je...
{29665}{29741}Neøíkej mi, e je to kvùli tomu dešti.
{29771}{29847}Ne, nevedla si poslední dobou skvìle.
{29870}{29949}Vìdìla jsem, e musela bıt znovu pøijata, ale...
{29949}{30051}ale byla na tom hùø, ne jsem si myslela.
{30116}{30174}Tomo-chan, prosím jdi a navštiv ji, dobøe?
{30215}{30429}Ty, take ty jsi pøítel Ibuke? |Zajímalo mì, kdo jsi.
{30465}{30506}Díky tobì se zdá bıt velmi šastná.
{30506}{30639}Šastná? Poøád se usmívala, ale...
{30776}{30826}Nemyslím si, e by se to s ní zlepšovalo.
{30826}{30905}Doktore, jaké je nemoc Minamo-chan?
{30905}{30975}Jak ji vyléèíte? Doktore!
{31032}{31106}Potøebuje transplantaci.
{31106}{31128}Transplantaci?
{31128}{31190}Ale nemùeme najít dárce.
{31208}{31275}Kdokoli by nebyl dárcem?
{31275}{31338}Potøeboval bys stejnou krevní skupinu jako je její,
{31338}{31378}ale je tìké ji najít.
{31378}{31430}Doktore, nechte mì bıt dárcem.
{31430}{31443}Coe?
{31455}{31563}Prosím pouijte mì. Transplantujte cokoli potøebujete.
{31563}{31626}Uklidni se. Není to tak snadné.
{31626}{31670}Nejdøíve musím provìrit tvou krevní skupinu.
{31670}{31722}Prosím provìøte mou krevní skupinu.
{31722}{31841}Slíbil jsem jí, e jí ukáu noèní oceán, a jí bude líp.
{31841}{31913}Ale... teï je Mimao-chan...
{31945}{31976}Prosím.
{32041}{32057}Rozumím.
{32057}{32126}Test mùe bıt bolestivı.
{32122}{32138}To je v poøádku.
{32138}{32199}Nejdøíve, bì na sluebnu sester...
{32295}{32336}Co se dìje, Tomoyo-san?
{32365}{32402}Nevypadáš moc dobøe.
{32426}{32471}To není pravda. Vypadám!
{32605}{32620}Co se dìje?
{32639}{32712}Zajímá mì, proè nemùu nakreslit svou vlastní tváø.
{32782}{32820}Znám dùvod.
{32859}{32904}Je zmoená, protoe vdycky vypadá jako ona,
{32924}{32994}její ruka nemùe pochytit zmìny jejího oblièeje.
{33032}{33164}Jestli mùe dostat Minamo-chan |transplantaci, znovu se stane dobrou.
{33197}{33313}Šance na to jsou moná velmi malé,|ale budu v nì vìøit.
{33339}{33369}Uvidíme se pozdìji, Tomoyo-san.
{33385}{33426}Nemusela jsi mì vyprovázet.
{33426}{33502}Kdy se nebudu hıbat, moje tìlo ztuhne.
{33547}{33572}Vypadáš opravdu šastnì.
{33572}{33603}Jo, jsem v poøádku.
{33603}{33621}To ráda slyším.
{33621}{33635}Jo.
{33648}{33677}Je to "Ano", správnì?
{33677}{33700}Ah. Ano!
{33805}{33866}Tomoyo-san, pamatuješ na náš slib?
{33895}{33933}Noèní oceán, správnì?
{33933}{33975}Není ádnı zpùsob, jak bych zapomnìl.
{33975}{34011}Chci ho vidìt teï.
{34011}{34074}Teï chci vidìt noèní oceán.
{34074}{34149}te´d to není dobré. Musíš poèkat, a ti bude líp.
{34149}{34226}Tomoyo-san, nevezmeš mì, abych vidìla oceán?
{34241}{34324}Nemùeš mì vzít pøedtím, ne mi bude líp?
{34562}{34618}Opravdu by se's nemìl obviòovat.
{34618}{34705}Šance, e máš stejnou krevní skupinu byly velmi mizivé.
{34704}{34777}Ale, pak je Minamo-chan...
{34777}{34906}Nedìlej si s tíms tarosti. Stále hledáme |odpovídajícího. Urèitì jednoho najdeme.
{34922}{35011}Má štìstí. Pøedtím jsme pro ni našli dárce.
{35062}{35105}Mùu poádat tu osobu o darování?
{35105}{35185}Ta osoba u není naivu.
{35229}{35263}Zemøela pøed tøemi lety.
{35322}{35348}Tøi roky...
{35422}{35489}Zemøela pøi automobilové nehodì| právì pøed transplantací.
{35593}{35690}Jestli si to pamatuju správnì, byla to|její sestøenice, Hizuki Ayaka-san.
{35946}{36064}V tuto chvíli nejsme doma. |Prosím nechte zprávu po zvukovém znamení.
{36126}{36169}Tomoyo? Tady je tvoje matka.
{36169}{36275}Jaké byly vısledky testu?| Tvùj otec je velmi znepokojenı,
{36275}{36313}...a tvá matka je...
{36334}{36369}Tomo-chan, tady Yue,
{36369}{36442}proè nenavštìvuješ Minamo-chan?
{36442}{36536}Minamo-chan se sama usilovnì snaí u tıden.
{36564}{36604}Neuvidí mì.
{36604}{36663}Tomo-chan! Tomo-chan!
{36663}{36684}Nemám ádné právo jít...
{36684}{36870}V tuto chvíli nejsme doma. |Prosím nechte zprávu...
{36940}{36992}Kvùli mì, Minamo-chan...
{36992}{37060}Bylo to právì pøed její operací.
{37076}{37207}Cítím k ní lítost. Byla to dobrá sestøenice, a |muselo to bıt pro ni ještì více šokující.
{37322}{37358}Nejsme doma...
{37421}{37456}Nemám právo jít.
{37522}{37549}To není pravda.
{37873}{37961}Prosím ochraòuj Minaminy pocity.
{38059}{38078}Ayako.
{38209}{38228}Minamo-chan.
{38261}{38277}Pøišla jsem...
{38329}{38410}Není pro tebe dobré tohle dìlat |s tvıms slabım tìlem.
{38445}{38561}To proto jsem pøišla, jinak bych| nemohla dodret náš slib.
{38561}{38609}Miluju tì, Tomoyo-san.
{38609}{38742}Chci bıt s osobou, kterou miluji a do úplného konce.
{38772}{38790}Minamo.
{38790}{38808}Omlouvám se.
{38999}{39013}Orion.
{39117}{39142}Jsi v poøádku?
{39142}{39153}Ano.
{39335}{39360}Noc u je skoro u konce.
{39382}{39505}Jo, ale je opravdu krásnı, oceán.
{39703}{39735}Ah, zlaté moøe!
{39735}{39838}Úasné, opravdu existuje!
{40505}{40637}-My dva jsme pøijeli na toho høejivé místo.-
{40658}{40820}-Je to tajemné, nemyslíš? Dìlá mì to také nostalgickou.-
{40820}{41146}-Nepotøebuju modlitby ani sliby, kdy jsi tady.-
{41146}{41283}-Pøesnì jak to bylo starostlivì pøedpovídáno.-
{41304}{41475}-Øekni, e jsi il vdycky takto.-
{41498}{41632}-Bylo to jemné; dal jsi mi polibek,-
{41646}{41806}-a já jsem ti dala svìtlo.-
{41870}{42038}-Èas vìènosti! Jestli, na této zemi,-
{42038}{42176}-fouká jemnı vítr,-
{42176}{42358}-uvnitø mé hrudi se to pøehne ve smutek.-
{42358}{42496}-Leme k prázdnotì k daleké hvìzdì.-
{42614}{42907}-Dr mì a øekni mi, e není èeho se bát.-
{42922}{42994}Pøeklad + korekce + èasování: WelW(etkaAa)-hime|www.mycolorfullife.blog.cz
{43881}{43895}Dìkuji t...
{43927}{44024}/Konec/
