{1}{1}23.976|Love.So.Divine.2004.DVDivX.AC3-CiMG
{1172}{1285}{Y:i}Korea Pictures presents
{1411}{1523}{Y:i}A KiHweck ShiDae production
{2402}{2487}Benedicamus Domino!
{2490}{2585}Deo Gratias!
{2754}{2959}LÁSKA TAK BOSKÁ
{3459}{3492}Kde jsi byl?
{3543}{3647}Víš, ta zeï je dost vysoká.
{3670}{3697}Spadnul jsem!
{3806}{3899}Byl jsem zachraòovat zbloudilou oveèku.
{3991}{4019}Co je tohle?
{4037}{4062}Co?
{4123}{4187}Oveèka zdaleka, co?
{4190}{4271}Pøesnì tak, havá ruska...
{4274}{4314}Víš ty, co si myslím?
{4318}{4357}Jako nastávající knìzové...
{4361}{4438}bychom nemìli ruské oveèky zanedbávat.
{4473}{4542}Dneska jsme ministranti, pamatuješ?
{4545}{4578}Jo, jasnì.
{4581}{4652}A co naše vysvìcení za mìsíc?
{4655}{4705}Jo, jasnì.
{4718}{4745}Jdeme.
{4809}{4834}Hej!
{4862}{4892}Poèkej!
{4956}{4981}{Y:i}Kwon Sang-woo
{4984}{5074}Kyu-shiku, zkoušel jsi u whisky?
{5076}{5161}- Úplnı boí dar!|- Buï zticha a utíkej!
{5162}{5220}{Y:i}Ha Ji-won
{5221}{5318}{Y:i}Kim Inkwon
{5370}{5390}Zpomal!
{5391}{5430}{Y:i}Executive Producer |Soma H.Z. Chung
{5478}{5546}{Y:i}Producer |Yoo In-taek
{5710}{5798}{Y:i}Line Producers|Jung Sook-jung, Nam Jin-ho
{5802}{5859}{Y:i}Pouze seminaristé|Zákaz vstupu
{5883}{6057}{Y:i}Directed by Huh In-moo
{6339}{6415}Kde to má díru?
{6550}{6597}Chlape, to bylo tìsnì.
{6600}{6700}Zapomnìl jsi, e to posvìtil sám pape?
{6722}{6812}Kdy to rozbiješ...
{6815}{6845}...mohli by tì vylouèit.
{6849}{6920}Tak jednoduše se èlovìk |ze semináøe nedostane.
{6923}{7021}To øíkáš ty.|To si zapamatuju.
{7036}{7102}- Jdeme.|- Necháš to!
{7146}{7201}Ty vezmeš kadidelnici.
{7238}{7304}Ten je tak nafoukanej!
{9465}{9574}Neøíkal jsi mi, |e to vysvìtil sám pape?
{9578}{9625}Proè je to tak køehké?
{9990}{10017}Potøebuješ pomoct?
{10098}{10166}Nemìj strach.|Je to v pohodì.
{10170}{10245}Jedinı, co nás èeká je poøádná práce.
{10249}{10354}Minulı rok mi to šlo skvìle.|Vìø mi.
{10357}{10413}Tím, e jsem jim slíbil |vyèištìní jejich septikù...
{10417}{10498}jsem obrátil na víru tolik, |kolik by ti trvalo dva mìsíce.
{10527}{10591}- A co kdy mi to nepùjde tak skvìle?|- Vylouèí tì.
{10611}{10716}Nemìj strach.|Prostì se mì dr.
{10770}{10886}Tam nahoøe je obchod |s levnım zboím.
{10889}{10953}Tam odboèíš na druhou cestu.
{10956}{11063}Bì rovnì a pak...
{11066}{11166}- Zatoèit doprava a pak rovnì.|- Take mám zatoèit vpravo?
{11170}{11262}- Ne, pùjdeš touhle cestou.|- Není ta cesta vpravo?
{11266}{11363}- Bì doprava a...|- Vy si je schováváte na prodej?
{11366}{11454}I ta troška pomùe.|Asi 30 krokù...
{11477}{11526}Mluvím snad do zdi?
{11807}{11854}Tak hoøké!
{11894}{11924}Sakra!
{12134}{12171}To je alkohol.
{12261}{12301}Sleduj..
{12350}{12439}Tomuhle øíkám poehnání.
{13131}{13228}Jdeš pozdì.|Jak je to moné?
{13265}{13362}Nezapomeò, proè jsi tady.
{13366}{13437}Myslím, e jste si nás s nìkım spletla...
{13853}{13907}Kde je otec?
{13910}{13950}Brzy se vrátí.
{14121}{14158}Podívej na to.
{14198}{14247}Co kdy nás s nimi |bude chtít mlátit..
{14459}{14506}Tak se na to podívejme.
{14562}{14624}Co jste na semináøi studovali?
{14637}{14739}O duchovním dvoøe, |kdy vládnul Trientskı koncil.
{14742}{14770}Po vysvìcení...
{14774}{14856}bych se chtìl zabıvat vlivem |støedovìkıch filosofií...
{14859}{14966}na moderní církev.|- Dobøe. A ty?
{15010}{15082}Já studoval...
{15085}{15180}jak ruští stoupenci ovlivnili |korejskou teologii.
{15183}{15247}Po vysvìcení...
{15250}{15302}eny z jihovıchodní Asie...
{15306}{15372}Mım hlavním zámìrem bude studovat |stoupence enského pohlaví.
{15375}{15453}To zní velmi komplexnì.
{15457}{15530}- U jste jedli?|- Prosím?
{15534}{15628}Bìte do kuchynì a najezte se.
{15672}{15753}Poehnání vám nepomohou, |kdy budete hladoví.
{15756}{15817}Jídla nikdy nevynechávejte, jasné?
{15821}{15846}Dobøe.
{16214}{16290}Benedicamus Domino!
{16303}{16345}Deo Gratias.
{16737}{16798}Vysvìcení se blíí.
{16833}{16918}Prosím dávej na mì pozor.|Deo Gratias.
{18048}{18148}Kdo jsi?|Co tady dìláš?
{18178}{18253}Prosím, odejdi.|Tohle je dùm pánì.
{18348}{18402}Proè radši...
{18684}{18717}Mùj Boe!
{18863}{18903}To je slané!
{18971}{19035}To je svìcená voda!|Odejdi!
{19178}{19215}S dovolením...
{19238}{19311}Z tohohle bych mohl mít problémy.
{19574}{19632}Byla to nehoda.
{19635}{19694}Nikdy pøedtím jsem ji nevidìl.
{19698}{19771}- Opravdu!|- A ty jsi ji políbil?
{19786}{19862}Dobøe, nechám si to pro sebe.
{19866}{19958}- Nápadník znamená potíe.|- To je pravda.
{19962}{20004}Na co jsi myslel?
{20007}{20054}Doteï jsi byl bezproblémovı.
{20058}{20119}Hanba ti!
{20139}{20191}V tom to není!
{20194}{20318}Coe? To sem letìla takovou dálku |jen proto, aby s ní byly potíe?
{20322}{20406}Ani náhodou!|Nemùe tady zùstat.
{20410}{20473}Vezmìte si ji zpátky!
{20568}{20646}Otèe, odpuste mi.
{20664}{20711}Vysvìcení je za mìsíc.
{20714}{20783}Vylouèí mì, kdy se teï vrátím.
{20786}{20860}- Coe?|- Nemohu a nemìl bych..
{20863}{20965}Chci øíct.. já se z toho zblázním!
{20969}{21045}- Ty se z toho tady zblázníš?|- Ne, špatnì jste mi rozumìl.
{21048}{21181}Nechtìl jsem, aby se to stalo.
{21184}{21250}Nechtìl jsem ji políbit.
{21254}{21336}- Ty jsi líbal?|- Strıèku Name!
{21352}{21428}- Moje hlava je na prasknutí.|- Yang Bong-hee, ty!
{21431}{21545}Ty jsi sem utekla z Ameriky?|Takové plıtvání penìzi!
{21549}{21639}- Vrátila jsem se, abych se vdala.|- To si mùeš jen pøát.
{21642}{21687}U jsem mluvil s tvojí matkou.
{21690}{21771}Pojï se mnou.|A zakryj si pupík.
{21784}{21927}S tebou jsem ještì neskonèil.
{21930}{21977}No tak.
{21992}{22056}No tak.|Honem.
{22242}{22289}Jaké to bylo?
{22306}{22332}Co?
{22347}{22421}Ten polibek!|Bylo to pro tebe poprvé.
{22503}{22548}Hej, Kyu-shiku.
{22604}{22639}Pouil jsi jazyk?
{22674}{22735}Bylo to dobré? Jaké to bylo?
{22770}{22847}Políbil jsi ji jako první?
{22874}{22948}No tak, pochlub se!
{23050}{23118}Vy tady kouøíte cigarety?
{23134}{23202}To máme radši kouøit trávu?
{23232}{23373}- Ještì na to nemáte vìk!|- Ty jsi tady novej, kdo sakra jsi?
{23376}{23469}Kdo jsem?|Jsem seminarista, kterı bude knìzem!
{23472}{23588}Seminarista?|Take jsme všichni studenti.
{23591}{23660}Nestrkej nos do našich vìcí, jasné?
{23663}{23708}- Jak se opovaujete, vy...|- Sakra!
{23711}{23792}Moje máma mi øekla, e je v poøádku, |kdy budu v kostele dìlat problémy.
{23795}{23861}Máš s tím nìjakej problém?
{23946}{23991}- Sun-dale!|- Co je?
{24011}{24075}- Co je?|- Pojï sem.
{24107}{24183}- Ony tady kouøí.|- Opravdu?
{24227}{24281}Sleduj, poehnání odjídí.
{24285}{24363}- Ahoj!|- Ahoj!
{24397}{24425}Protentokrát máte štìstí.
{24582}{24624}- Svezete mì?|- Naskoè si.
{24627}{24758}- Díky.|- Promiò? Promiò!
{25093}{25123}Poèkej!
{25483}{25523}Díky.
{26082}{26122}Kde jen mùe bıt?
{26219}{26249}Taxi!
{26390}{26417}Promiò.
{26471}{26545}- Musím ti nìco øíct.|- Co se dìje?
{26548}{26614}- Já...|- Spìchám. Co mi chceš øíct?
{26618}{26657}Já...
{26678}{26751}Aha, u chápu.
{26766}{26853}Promiò.|Jsem zadaná.
{26857}{26894}Jeïte.
{26972}{27019}Hej...|Hej, poèkat!
{27097}{27146}Musíme si promluvit.
{27164}{27194}Nasedej!
{27236}{27355}Øíkám, e spìchám.|Nasedej! Hned!
{27358}{27410}Jsi tak panovaèná..
{27586}{27621}Tak co je?
{27636}{27721}- Dnes ráno...|- Podr mi to.
{27725}{27765}- Coe?|- Dr.
{27900}{28000}Nehıbej s tím, |dìlá se mi špatnì.
{28034}{28091}Jeïte klidnì, prosím.
{28169}{28245}Jaké je moje oboèí?
{28494}{28525}Úplnì stejné.
{28646}{28757}Dnes ráno... Polibek...
{28809}{28904}Znáte to tady, e?|Zavezte mì sem.
{29317}{29390}- Promiò? Peníze!|- Poplatek za taxi!
{29456}{29491}Jin-ho!
{29542}{29590}Jin-ho!
{29605}{29697}- Pøekvapila jsem tì, e?|- Jo, poøádnì.
{29701}{29757}Chybìla jsem ti?
{29830}{29868}Rozejdeme se.
{29974}{30128}Coe? Zapomnìl jsi, |co jsi mi øekl na stadionu?
{30132}{30294}"Jako homerun v baseballu budu |já tvım vítìzstvím v lásce."
{30314}{30417}Jsem pro tebe spíš jen |obyèejnı nadhazovaè...
{30451}{30510}ne ten homerun.
{30689}{30717}Nestalo se vám nic?
{30791}{30877}Promiò.
{30897}{30946}- Promiò?|- Co je zas?
{30969}{31030}- Jo, odkopnul mì.|U jsi spokojenı?
{31041}{31165}Víš co? Nezaslouil si tì.
{31182}{31210}Take...
{31235}{31361}Poøád máš o mì zájem?|U jsem ti øekla, e jsem zadaná!
{31394}{31558}- Byla jsem...|- Já jen øíkám...
{31562}{31627}Vidíš svoji šanci, co?
{31630}{31670}Ani na to nemysli.
{31712}{31771}Coe?
{31774}{31836}Máš vùbec potuchy, |jaké problémy jsem kvùli tobì mìl?
{31839}{31910}O èem to mluvíš?
{31976}{32037}- Dnes ráno..|- Co dnes ráno?
{32041}{32126}- Polibek!|- S kım?
{32412}{32437}Sestro!
{32461}{32520}Ráno mùeš odjet.
{32522}{32646}Všichni chlapi jsou prasata, |kromì tvého táty a knìzù.
{32724}{32817}Strıèku, pùjèíš mi nìjaké peníze, |abych se mohla vrátit?
{32839}{32877}Na letenku?
{32894}{32989}Kadı halíø tady náleí Bohu.
{33007}{33093}To je ubohá vımluva!
{33120}{33229}Není.|Myslíš, e by ti knìz lhal?
{33232}{33341}Myslíš, e tì máma pøijme zpátky?|Radši šetøi za elektøinu a bì spát.
{33345}{33394}Taková ztráta èasu...
{33834}{33908}Na pøíští mìsíc jsem vaše sluka.
{33911}{34022}Letenka stojí 1,500.|Dávejte mi kadı den 50 dolarù.
{34129}{34166}Uhnìte!
{34470}{34612}- Co je? Co poøád chceš?|- Nebuï tak protivná, sestro.
{34616}{34656}- Otèe?|- Sestro?
{34659}{34709}To je tvá balící hláška?
{34712}{34782}- Ohlednì sestry Bong-hee..|- Já jsem seminarista!
{34786}{34852}- a jejího setrvání v kostele...|- Kam to ten svìt spìje?
{34855}{34900}- Je to proti pravidlùm.|- Seminarista...
{34903}{34943}napadá eny?
{34946}{35056}Vdy není ani pokøtìna.
{35059}{35200}Bùh s ní má svùj zámìr.|Proto ji k nám poslal.
{35530}{35593}Co je to s tebou?
{35766}{35871}Od chvíle co jsem ji potkal |mám samé problémy.
{35908}{36003}- Má budoucnost je zpeèetìna.|- Rok hada, co?
{36038}{36178}"Snaí se ze všech sil,|ale nic mu nepøináší ovoce."
{36268}{36303}Shin Sun-dale Thomasi!
{36306}{36432}Vìštìní je jen pro slabomyslné.
{36529}{36554}U ho to zase chytá...
{36582}{36607}No a co..
{36918}{36969}{Y:i}ZKONTROLUJTE SI SVÙJ OSUD|NIJAK PØÍZNIVİ
{37062}{37135}Kdo to kurva hodil?
{37176}{37285}- Vy nechodíte do školy?|- Máme odklad.
{37392}{37432}Dávej si bacha co meleš, debile.
{37481}{37540}Zahráváte si, dìvèata.
{37562}{37595}ádné klení!
{37658}{37694}Blbej kretén...
{37747}{37816}Pro seminaristy je normální |slouit kostelu!
{37846}{37983}Poslední dobou zvoní za svítání zvon.|Kdo na nìj zvoní?
{37986}{38043}Není to osvìující?
{38046}{38134}- Otèe!|- Nezvoòte na ten zvon!
{38171}{38249}Farmáøi potøebují klidnì spát.
{38284}{38386}Jestli se to ještì stane, |pøejdu na buddhismus.
{38390}{38475}A je to svatynì nebo kostel, |poèítá se to, jestli se modlíte.
{38488}{38564}- To myslíte vánì?|- Co se øíká?
{38589}{38629}Šastnou cestu.
{38646}{38753}- Díky, vrátím se brzy.|- Dobøe, otèe.
{38845}{38899}U je tu dodávka!
{39346}{39449}Bong-hee nám pomáhá s dìtmi.
{39650}{39741}Zpomal. Naè ten spìch?
{39794}{39851}Je tady omezená rychlost na 60 km/h.
{39878}{39928}Zpomal.
{40099}{40125}Øiï si sám!
{40176}{40247}Nelíbí se ti, jak øídím?|Pøesedneme si.
{40282}{40324}Já nemám øidièskı prùkaz.
{40346}{40383}A to si øíkáš chlap?
{40403}{40462}Co to má spoleèného s tím, |jestli jsem mu?
{40466}{40503}Není to proto, |e bych ho nemohl mít...
{40506}{40532}ale protoe ho nepotøebuju.
{40535}{40659}Máš pravdu, jsi pøece seminarista.|Nepotøebuješ auto na randìní.
{40662}{40700}Rozumím.
{41087}{41151}Zpomal, jo?
{41648}{41707}To je moje.|Kurva!
{41732}{41810}Taková slova se neøíkají.|On je nemá rád.
{41814}{41885}- Pán nahoøe?|- Tohle taky nemá rád.
{41888}{41975}Nepotøebuju, aby mì |pouèoval chlap v sukni!
{41978}{42045}Pìkná Bong-hee má |tahle slova ráda.
{42048}{42162}Nasrat, kurva, nasrat, kurva...
{42178}{42237}Pøestaò...
{42240}{42321}nebo ti naplácám døív ne Bùh.
{42418}{42479}Blbèe!
{43365}{43393}Sestro Bong-hee!
{43621}{43754}Pøíliš se odhaluješ pøed domem pánì.
{43791}{43850}Sluneèní paprsky jsou boí dar...
{43854}{43944}a já ho pohlcuju celım tìlem.|Máš s tím nìjakej problém?
{43947}{44037}Nemáš strach z boího soudu?
{44098}{44186}To mám vìtší strach z tebe.|Nech mì na pokoji, jo?
{44484}{44517}Nedívejte se!
{44681}{44713}Boe!
{44813}{44853}Vyznej se ze svıch høíchù.
{44935}{45001}Mám v mysli nenávist.
{45005}{45042}Pokraèuj.
{45046}{45154}Nemohu øíct, o koho jde...
{45186}{45258}ale poslední dobou tu osobu |èasto potkávám.
{45261}{45298}Proèpak?
{45302}{45380}Dìti mìly vèera kvùli ní málem nehodu.
{45383}{45478}A pøed chvílí udìlala rouhaèskou |scénu na zahradì.
{45482}{45553}Šíøí ïáblova slova...
{45556}{45584}mezi nevinnımi dìtmi.
{45587}{45620}Nasrat, kurva, nasrat, kurva...
{45623}{45692}Bong-hee by se mìla zpovídat a ne ty.
{45695}{45723}Pøesnì tak!
{45782}{45809}Ne.
{45830}{45962}Já pøiznávám svùj høích, e ji nenávidím |a e jsem jednal bez smyslù...
{45966}{46022}v pøítomnosti Boha.
{46047}{46094}Zaslouím si pokání.
{46098}{46195}Pokání?|Ale nejde o vánı høích.
{46198}{46303}Ale ano.|Jako nastávající knìz...
{46306}{46358}si zaslouím bıt potrestanı.
{46362}{46425}Bong-hee by mìla bıt potrestána.
{46429}{46541}Mám nápad.|Zkus ji pøesvìdèit, aby se nechala pokøtít.
{46575}{46656}Otèe, to je pøíliš kruté.|Zadejte mi jiné pokání.
{46659}{46737}Uè ji katechismus, |aby mohla bıt pokøtìna.
{46748}{46845}Povauj to za souèást vıcviku.
{46872}{46950}Otèe? Otèe?
{47018}{47133}Kdo ví?|Tøeba bude souhlasit.
{47160}{47260}Ty ji neznáš.|Ona není èlovìk.
{47275}{47337}To není ádná ena.
{47352}{47385}Jsou to boí poehnání.
{47503}{47531}Nemùe to bıt tak tìké.
{47560}{47617}Je to jako domlouvat schùzku naslepo.
{47634}{47653}Schùzku naslepo?
{47790}{47818}Kyu-shiku!
{47838}{47893}Nejdùleitìjší je...
{47896}{47986}jak obì strany pøedstavíš.
{47990}{48096}To je hlavní.|Náš Pán je machr.
{48100}{48133}Pan Machr!
{48136}{48205}- Je tak skvìlı!|- Skvìlı!
{48208}{48267}- Proklatì skvìlı.|- Proklatì skvìlı!
{48270}{48322}Vychval ho do nebes.
{48512}{48576}To máme krásnı den!
{48630}{48727}Promiò?|Nìco jsem ti donesl.
{48829}{48890}Proè jsi na mì tak milı?
{48920}{49034}Tohle je taková letenka do nebe.
{49038}{49087}Spíš toaletní papír.
{49152}{49221}Kdy si pøeèteš prvních deset stran...
{49224}{49295}slovo boí se tì dotkne...
{49387}{49412}Mám ji!
{49670}{49756}Šel jsi na to špatnì.
{49865}{49997}Úspìch schùzky naslepo závisí |na osobì, která to pøipravuje.
{50001}{50067}Vij se do její situace.
{50070}{50144}Øekl bys ANO nìjakému otrhanci?
{50147}{50225}"Bong-hee, Bùh je Pan Machr.|Chceš se s ním seznámit?"
{50229}{50297}Chápeš kam tím míøím?
{50462}{50499}To je ono!
{50854}{50892}Sluší ti to.
{50991}{51077}Bùh vypadá ještì lépe ne já.
{51111}{51180}Jako bys ho nìkdy vidìl!
{51207}{51235}Coe?
{51344}{51420}Paneboe!|Dal jsi mi to.
{51459}{51480}Sundej si to.
{51483}{51542}U se zase šklebíš.
{51546}{51589}Hned to sundej!
{51638}{51719}Rùenec není náhrdelník.|Slouí k modlitbì!
{52003}{52045}Co jsi? Nìjakej vychytralec?
{52337}{52388}Toho bude litovat!
{52401}{52474}Ne, e by mi záleelo|jestli pùjde do pekla.
{52518}{52640}Je to ztracená oveèka.|Doveï ji bezpeènì do ráje.
{52689}{52774}Mám nápad, Kyu-shiku.
{52785}{52889}Musíš jí dát to, |co potøebuje nejvíc.
{52970}{53014}Ta odpovìï je NEBE!
{53631}{53668}{Y:i}Hledám boha!
{53696}{53757}- Odteï jsi v tom sám!|- Kam jdeš?
{53761}{53813}Mìli jsme si vzít nìco jiného.
{53816}{53875}My tady nejsme, |abychom se bavili...
{53878}{53916}ale kvùli poslání.
{53919}{54002}Tenhle vohoz v NEBI funguje.|Uka zuby.
{54005}{54073}Sleduj svoji oveèku!|Postarej se o ni.
{54077}{54126}Já jdu hledat padlé andìly.
{54130}{54196}- Poèkej!|- No jasnì!
{54535}{54609}Pane Matrix!
{54612}{54657}Chcete se seznámit se skvìlejma holkama?
{54660}{54721}Tady je, dìvèata.
{54755}{54850}Proboha, ty vypadáš skvìle!
{54854}{54936}Je to Zen styl, kterı je teï in.
{54940}{55045}- Kde jsi to koupil?|- V obchodì jménem Panna Marie.
{55048}{55121}- Kde to je?|- To nám neøekne.
{55125}{55285}- Jeho styl je všechno.|- No tak, napijeme se.
{55298}{55345}- Já nemùu, jsem nachlazenı.|- S dovolením.
{55391}{55457}Jsi tak zábavnı.
{55461}{55532}A do dna.
{55535}{55601}- To je v poøádku. Jen do toho.|- A do dna!
{55604}{55694}- Chlapi jsou prasata!|- Na zdraví.
{55698}{55742}A do dna!
{55772}{55829}- Na zdraví.|- Jen do toho!
{55856}{55941}Promiòte.|Doufám, e potkáte hodné mue.
{55952}{55985}- Coe?|- Co se dìje?
{56082}{56179}- Co je?|- Toèí se mi hlava, pùjdeme.
{56209}{56249}Jin-ho?
{56262}{56294}Jin-ho!
{56310}{56344}Jin-ho!
{56390}{56433}To nejsi ty.
{56436}{56541}Není taková sraèka jako ty.
{56561}{56653}Je mi špatnì z tvıho ksichtu.
{56657}{56699}Coe?
{56702}{56766}Já se o ni postarám, brácho.
{56772}{56821}- Hej!|- Kdo jste vy kreténi?
{56825}{56862}Pøeskoèilo ti?
{56882}{56922}- Proè jsi mì praštil?|- Coe?
{57012}{57078}Prosím, nerozèilujte se.
{57082}{57133}Je mentálnì zaostalá.
{57148}{57193}Odcházíme.
{57256}{57310}- Ne tak rychle!|- Brácho!
{57350}{57404}Nechte mì bıt!|Chyte ji! Brácho!
{57407}{57447}Chyte ji!
{57458}{57485}Chyte ji!
{57770}{57876}- Vzpamatuj se.|- Najdìte je!
{58009}{58106}Támhle jsou!|No tak, zdrhnou nám!
{58225}{58289}To neumíte ani bìhat?
{58292}{58399}Jste totální budiknièemové!
{58503}{58567}Dìlejte, pitomci!
{58570}{58601}Ty bì tudy!
{58683}{58761}To je slepá ulièka!|Podívej se kam bìíš, blbe!
{58764}{58811}- Tady taky nejsou?|- Ne, brácho.
{58814}{58871}Dìlejte, idioti!
{58992}{59058}Dejte nám pokoj, rychle.
{59062}{59140}Podívej se na ni.|Nemyslím, e musíš spìchat.
{59158}{59212}Chceš platit za hodinu nebo za noc?
{59215}{59277}Hodiny nám staèit nebudou.
{59280}{59404}Zkoušíš nové vìci?|Všeho moc škodí.
{59642}{59753}Ty si myslíš, e mi uteèeš?
{59757}{59813}Ty parchante.
{59966}{59998}Vypadni!
{62845}{62913}Hej, hej.
{63030}{63141}- Ty jsi mì sem odnesl?|- Protoe jsi byla...
{63145}{63261}Proè mì poøád sleduješ?|Poøád jsi do mì zamilovanı?
{63265}{63314}Nelicho si.
{63318}{63403}Nebıt mì...
{63406}{63451}tak jsi byla ve velkém...
{63454}{63499}Neøíkej, e neumíš jezdit na kole.
{63571}{63599}Jedeme.
{63626}{63669}Jedeme!
{63684}{63733}Èí si myslí, e to kolo je?
{63828}{63904}Zpomal, kámo.|Chce se mi zvracet.
{63907}{63973}Proè jsi toho tolik pila?
{63989}{64084}A mimochodem, neøíkej mi kámo.
{64087}{64127}Promiò kámo.
{64193}{64233}Nepùjdem radši pìšky?
{64260}{64321}Dobøe, stejnì to není pohodlné.
{64562}{64633}Co to dìlají?
{64689}{64741}Hrají Stùj a bì.
{64744}{64817}- Ty to neznáš?|- Ne.
{64821}{64906}Øeknou "stùj" a musíš se zastavit.|Øeknou "bì" a mùeš bìet.
{64926}{64993}Ty jsi to nehrála, |kdy jsi byla malá?
{65044}{65096}Je mi to líto.
{65144}{65203}Je to jako platonická láska.
{65502}{65529}Stùj!
{65610}{65678}Nechce se mi vìøit, |e jsi opravdu zastavil!
{65828}{65939}- Coe?|- Sedej! Nebo chceš jít pìšky?
{65981}{66006}Dobøe.
{66019}{66047}Moje hlava!
{66283}{66364}Kde je Kyu-shik?
{66389}{66493}Má poslední dobou dost práce |s tím svım misionáøskım úkolem.
{66497}{66587}- Pouívá svoji pohlednost?|- Já?
{66641}{66707}- Pohlednost...|- Jdu za hlavou vesnice.
{66710}{66841}Zase vám bude dávat psí maso?
{66890}{66934}Já nevím.
{66938}{66982}Já vám pomùu, otèe.
{66995}{67035}Je to na vás moc tìké.|Pùjdeme?
{67067}{67199}{Y:i}Seznam úkolù.|Pokøtít Bong-hee ... X
{67314}{67400}Trénují svatební píseò?
{67451}{67505}Dneska mi sva na noc ruce.
{67509}{67608}Nìco jsem snìdl |a cítím se strašnì silnı.
{67618}{67653}Bì pryè.
{67681}{67706}Copak to je?
{67827}{67951}Ani náboenství, ani románek |by nemìly bıt vynucené.
{67969}{67999}Támhle jde.
{68002}{68078}Proè se jí nezeptáš, |jestli se nechce pøidat ke sboru?
{68082}{68196}Bì pryè.|Chceš, abych to udìlal já? Dobøe!
{68238}{68273}Sleduj!
{68362}{68394}Sestro Bong-hee.
{68422}{68447}Co je?