{1}{1}23.976
{370}{424}Zaèínáme zítra?
{560}{702}- Co jsi jí øekl?|- Jen pár medovıch slovíèek.
{705}{736}Díky.
{761}{882}Mimochodem..|mì poprosila o pár kazet.
{885}{921}Pìt novıch titulù kadı tıden...
{924}{988}nepøístupnıch horrorù a akèních flákù.
{991}{1076}Na takové se v kostele nesmí dívat.
{1097}{1151}Dobøe, ádnı problém.
{1154}{1240}A basu vína.
{1243}{1300}Mešního vína?|Pøeskoèilo ti?
{1317}{1384}Chceš ji pokøtít?|Chceš bıt knìz?
{1409}{1433}Dobøe.
{1441}{1522}- A...|- Co ještì?
{1525}{1608}Vracela se sama domù pøes les...
{1612}{1690}a pøemıšlela, jak hladové |budou její dìti.
{1693}{1812}A najednou... vyskoèil z køoví tygr!
{1837}{1899}Dej mi ten koláè |nebo tì seeru.
{1902}{1983}- To bylo strašnı.|- Co jsi, nìjaké kotì?
{1996}{2057}Tygr otevøel svoji |obrovskou pusu plnou zubù.
{2061}{2132}Byla tak strašnì vystrašená...
{2135}{2196}e hodila tygrovi ten koláè.
{2212}{2292}Zatímco ho tygr jedl, utíkala, |jak jen nejrychleji mohla...
{2295}{2390}ale na dalším kopci...
{2463}{2584}Dej mi ten koláè |nebo tì seeru!
{2609}{2637}Zabte tygra!
{2657}{2731}Umøi!
{3096}{3160}Bong-hee, u usnuly.
{3365}{3414}Musíme trénovat se sborem.
{3444}{3498}Nech mì ještì chvilku spát.
{3535}{3577}Mám je probudit?
{3662}{3747}Jsi moc podlı na to, |abys byl knìz.
{3952}{4090}- Takhle to dovedou nejlíp.|- Amen.
{4110}{4208}To není moc vhodné na svatbu, e?
{4609}{4680}Díky, e jsi mi pomohl s dìtmi.
{4781}{4809}Ahoj!
{5609}{5634}U jsou tady!
{5793}{5872}- Co tam dìlají?|- Tamten je roztomilej.
{5875}{5924}- Ten napravo!|- Ne, tenhle je hezèí.
{5928}{5963}- To teda ne!|- Ten je ošklivej..
{5966}{6018}Ne, je o dost hezèí.
{6031}{6068}Kdo mì to kurva praštil?
{6079}{6145}Pozor na jazyk, dìvèe.
{6149}{6226}Vdy jste knìz.|Nesahejte enì na zadek.
{6229}{6288}Kdy jsi byla malá, |mìnil jsem ti pleny.
{6292}{6363}- Uvádíte mì do rozpakù! Bìte, otèe.|- Dobøe.
{6625}{6653}Vítejte.
{6676}{6756}- To je mùj bratr.|- Je pohlednı.
{6789}{6845}Já, Yang Bong-hee...
{6858}{6953}a šastná nebo smutná...
{6978}{7058}dokud nás Bùh nerozdìlí.
{7061}{7173}Slibuji ti lásku navdy.
{7645}{7716}- Co to dìláš?|- Co to dìláš TY?
{7762}{7814}Ptal jsem se, co to tam dìláš.
{7862}{7967}Oblékla jsem si ty šaty,|aby se nezmaèkaly.
{8131}{8233}To musí bıt zmetek.|Roztrhly se moc snadno.
{8241}{8310}Hlídej nevìstu.
{8397}{8507}Byla by z tebe skvìlá manelka.
{8510}{8650}Umíš vaøit a uklízet|a dokonce šít.
{8653}{8770}Bùh má radìji ty, kteøí se dobøe modlí,|ne ty, kteøí umí dobøe vaøit.
{8785}{8844}Kromì Boha...
{8848}{8921}Nemá vìtšina muù radši eny, |které umí vaøit?
{8953}{9070}Jin-hovi nechutnalo, co jsem vaøila.
{9109}{9154}Myslíš, e tì proto odkopl?
{9191}{9296}Jestli ano, bude ti bez nìj líp.
{9299}{9375}Lidi se neberou kvùli dobrému jídlu.
{9378}{9415}Kvùli sexu!
{9449}{9516}To mi pøipomnìlo.
{9519}{9607}Seminaristi se nemùou oenit.
{9610}{9691}- Jak uspokojují svoje potøeby?|- Au, píchnul jsem se.
{9725}{9806}Pøestaò si hrát na naivku. |Odpovìz.
{9829}{9919}Coe?
{9997}{10058}Nejsi pøece impotentní, ne?
{10217}{10244}Ach Boe!
{10279}{10357}To je mi líto.|Tak a je to.
{10507}{10535}Hotovo.
{10771}{10883}Abychom popøáli enichovi |a nevìstì svìtlou budoucnost...
{10886}{10993}pøipravili jsme svatební píseò.|Prosím pøivítejte sbor.
{11409}{11508}{Y:i}* Kdy je noc
{11512}{11614}{Y:i}* tichá a klidná
{11617}{11777}{Y:i}* sepnu ruce a modlím se
{11847}{11935}{Y:i}* Ach, posvátná noci
{11938}{12019}{Y:i}* bolest, kterou cítíš
{12032}{12122}{Y:i}* kdy touíš po smilování
{12125}{12196}{Y:i}* po nepøicházejícím dešti.
{12200}{12290}{Y:i}* Sešli mu enu
{12293}{12422}{Y:i}* Nikdy nedrel v dlani|enskou ruku
{12425}{12475}{Y:i}* za svùj ivot
{12478}{12554}{Y:i}* Podívej se do jeho nevinnıch oèí
{12572}{12661}{Y:i}* Sešli mu enu
{12665}{12738}{Y:i}* Jen kdy na ni pohlédne
{12741}{12848}{Y:i}* jeho tváø zrudne
{12852}{12964}{Y:i}* Je jemnı jako hedvábí
{12967}{13004}{Y:i}* Pochval je
{13008}{13045}{Y:i}* Ten pøekrásnı pár
{13061}{13098}{Y:i}* Pøemıšlím
{13101}{13144}{Y:i}* co jim dìlá radost
{13147}{13280}{Y:i}* Posvì je prosím
{13315}{13405}{Y:i}* nekonèící láskou
{13409}{13486}{Y:i}* Závidím jim, ale nevadí
{13489}{13589}{Y:i}* Jste teï spolu jedním
{13593}{13661}{Y:i}* starajíc se o druhého
{13665}{13776}{Y:i}* Prosím, milujte mì taky|Sešli jim jen lásku
{13780}{13908}{Y:i}* svìt je krásnìjší ne kdy byl
{13912}{13964}{Y:i}* stejnì jako jejich láska
{13967}{14033}{Y:i}* O ní si nemùeme ani nechat zdát
{14037}{14124}{Y:i}* Já ano.|To bude problém.
{14128}{14241}{Y:i}* Nechejme si to pro sebe.|Prosím, buïte nìní
{14245}{14323}{Y:i}* Budete u navdy
{14336}{14378}{Y:i}* spolu
{14451}{14560}{Y:i}* Amen.
{15149}{15181}Min-woo!
{15204}{15272}Dlouho jsme se nevidìli.|To je pøekvapení!
{15276}{15304}Rád tì zase vidím.
{15324}{15419}U je to skoro rok, |co se z tebe stal knìz.
{15437}{15517}Ještì nikdy jsem tì nevidìl |v obyèejnıch šatech.
{15521}{15546}Opravdu?
{15576}{15637}Drahı, kdo je to?
{15662}{15735}- To je moje snoubenka.|- Ahoj.
{15777}{15819}Pøíští mìsíc se bereme.
{16127}{16222}Kadı nemùe bıt knìzem.
{16240}{16304}Jak to jen mohl udìlat?
{16367}{16397}Hej!
{16413}{16445}Sedej!
{16470}{16503}Proè?
{16506}{16589}Neptej se.|Prostì nasedni!
{16625}{16680}To auto tady není pro tvoji zábavu.
{16755}{16836}Já vím, e jsi sklíèenı a naštvanı.
{16882}{16984}Pøemıšlela jsem, které místo |by ti tu náladu spravilo.
{17012}{17064}A jedno jsem našla.
{17134}{17159}Nebe!
{17309}{17344}No tak!
{17438}{17545}Shlíet na 10 milionù lidí.|Jakı je to pocit?
{17573}{17648}Ty nìjaké vidíš?|Já vidím jen domy.
{17652}{17759}No tak, vìøíš na Boha,|kterı je neviditelnı.
{17777}{17857}Nedivím se, e nevidíš |do srdce svého kamaráda.
{17880}{17924}Je to jen tím...
{17942}{18025}e prostì nìkoho miluje.
{18029}{18100}- My bychom nemìli.|- Proè ne?
{18125}{18228}- Protoe jsme jiní.|- V èem jiní?
{18249}{18296}Pøece nejsi Bùh.
{18544}{18620}- Pìkné.|- Není obyèejnı.
{18630}{18727}Vídáš ji kadı den.|Proè její obrázek ještì nosit?
{18743}{18780}Neomrzí se ti?
{18796}{18860}Tebe omrzí mu, kterého miluješ, |kdy ho uvidíš kadı den?
{19006}{19077}Mùj táta mi to dal,|kdy jsem nastoupil do semináøe.
{19129}{19185}Nemohl bıt šastnìjší.
{19210}{19298}Mìl jsem v nìm fotografii rodièù.
{19333}{19392}Ale táta ji vyndal...
{19443}{19533}a øekl, e by tam mìl bıt nìkdo, |koho miluji ze všeho nejvíc...
{19537}{19586}a dal tam tenhle obrázek.
{19652}{19699}Pak jsem si to uvìdomil.
{19724}{19837}A hned jsem se pomodlil |k Bohu a Pannì Marii...
{19881}{20015}jak moc je mi líto, e jsem zapomnìl, |koho miluji nejvíc.
{20292}{20332}Øekni "á".|- Á.
{20450}{20483}Dáme si taky.
{20580}{20631}Dejte nám jednu, prosím.
{20653}{20684}- Tady máte.|- Vypadáš jako dìda.
{20687}{20724}Ještì nikdy jsem to nemìl.
{20740}{20816}- Øekni podìkování.|- A to dojím!
{21018}{21063}To je dobré.
{21237}{21286}Proè se tak tváøíš?
{21289}{21368}Zlobíš se, e jsem to snìdl.
{21371}{21419}Øíkala jsi, e si dáš...
{21797}{21873}Co je tohle?|Bliká to.
{21877}{21986}Ukazatel benzínu!|Došel nám benzín!
{22033}{22092}Ta dodávka je benzínorout!
{22184}{22216}Sestro Bong-hee!
{22245}{22273}Sestro Bong-hee!
{22329}{22374}Vdy leje!
{22421}{22456}Nech mì bıt!
{22459}{22525}Vdy nastydneš!
{22569}{22597}Bì pryè!
{22725}{22777}Vzpamatuj se!
{22826}{22878}Láska nejde vynutit!
{22984}{23096}Co ty o tom víš?|Nikdy jsi nebyl zamilovanı!
{23368}{23460}Vzduch venku je dobrı.|Není to kyselı déš.
{23845}{23894}Co na nìm vidíš?
{23972}{24086}Proè tì to zajímá?|Stejnì nikdy nepùjdeš na rande.
{24118}{24199}Nemùu si pomoct.
{24445}{24511}Minulı rok touhle dobou...
{24536}{24601}byl pár bot, po kterıch |jsem strašnì touila.
{24645}{24707}Ale ádnı obchod |u je neprodával.
{24753}{24877}Jin-ho mì na moje narozeniny |vzal na zápas v baseballu...
{24919}{25000}a dal mi dárek.
{25039}{25122}Byly to ty boty, e?
{25142}{25225}- Obyèejná náhoda.|- Byl to osud!
{25255}{25328}Pouto, která nás spojilo!
{25363}{25404}Ale...
{25441}{25496}nebylo dost silné.
{25537}{25577}Øekni.
{25607}{25652}Poøád ti chybí?
{25741}{25820}Ráda jsem s ním chodila na baseball.
{25852}{25892}Dostanu se z toho.
{25929}{25964}Mìla bych.
{26001}{26031}Mìla bych.
{26264}{26390}Tohle se zabavuje.|Nepomùe ti to.
{26557}{26606}Umírám hlady.
{26847}{26872}Tady.
{26900}{26944}Ty u sebe nosíš jídlo?
{27060}{27102}Deo Gratias!
{27160}{27198}To je latinsky?
{27225}{27253}Co to znamená?
{27307}{27354}"Dìkuji ti, Boe."
{27389}{27428}Nic dùleitého.
{27487}{27572}- Je to takovı tajnı kód.|- Tajnı kód?
{27681}{27769}Kdy se vyznáváš z lásky...
{27773}{27869}a nìkdo tì slyší, je to trapné.
{27894}{28023}Tak šeptám jen k Bohu..
{28060}{28145}e ho miluji a dìkuji mu.
{28165}{28222}Deo Gratias?
{28273}{28316}Deo Gratias.
{28988}{29104}Ještì stále má horeèku.|Nebude jíst.
{29108}{29200}Jako bych to neèekal!
{29204}{29272}Nemoc zmizí, a èlovìk dostateènì vytrpí.
{29276}{29364}- To je pravda.|- Jestli jste u dojedli, tak pojïte.
{29455}{29500}Hned tam budu.
{29560}{29629}Dát to, po èem nejvíc touí?
{29661}{29742}Tak umyj nádobí.
{29745}{29773}Zatím.
{29887}{29944}{Y:i}Dnešní zápas:|LG : KIA (14:00)
{30069}{30126}Nevìdìla jsem, e máš rád baseball.
{30129}{30192}Samozøejmì!|Je to mùj oblíbenı sport.
{30268}{30303}Bong-hee!
{30829}{30912}Co to má znamenat?
{30916}{31012}Nic!|Sna se dobøe bavit!
{31261}{31317}Co to dìláš?
{31335}{31428}Náš tım prohrává |a ty nepovzbuzuješ?
{33119}{33171}Nìkdo je opravil.
{33289}{33405}Ale mnì u se stejnì nelíbí.
{33408}{33470}Jsou moc køiklavé.
{33504}{33559}Ze zdvoøilosti jsem si je |vzala na sebe...
{33562}{33662}ale zítra je vyhodím.
{33785}{33902}- Mìla bych se nechat pokøtít?|- Opravdu?
{33939}{33969}Proè?
{34001}{34058}To je všechno, co k tomu øekneš?
{34076}{34142}Nejsi rád, e se nechám pokøtít?
{34145}{34247}Ty budeš pokøtìná.|Proè bych se mìl já radovat?
{34269}{34367}Víš co?|Sun-dal mi všechno øekl.
{34406}{34467}Díky mì z tebe bude knìz.
{34495}{34520}Nech toho!
{34687}{34732}Dìkuji ti, Boe.
{34862}{34897}Dìkuji!
{35039}{35093}To všechno si mám zapamatovat?
{35121}{35194}Nemyslím, e to tentokrát zvládneš.
{35209}{35312}To je obrácená psychologie?
{35315}{35362}Pøedveï mi to.
{35365}{35456}Zvládnu to, kdy to zvládneš ty.|No tak!
{35524}{35585}Znám celou Bibli nazpamì.
{35588}{35652}Já to vím.|Stejnì to zkusíme.
{35699}{35727}Modlitba lítosti.
{35811}{35882}Dìlej. A zavøi oèi!
{35900}{35966}Pøestaò na mì jeèet.
{36015}{36076}Boe na nebesích, |spáchal jsem mnoho høíchù...
{36080}{36144}Teï prosím o odpuštìní.
{36147}{36252}S láskou k Tobì pøísahám, |e u tì nikdy nezradím.
{36255}{36333}Prosím, poehnej mi.|Amen.
{37226}{37292}Nìkteré korálky jsem nemohla najít...
{37296}{37362}tak jsem tam místo nich |dala svoje perly.
{37388}{37433}Vezmi si ho.
{37492}{37527}Jsi ohromenı?
{37585}{37743}To, to a tohle...|Do zítøka si je zapamatuj.
{37840}{37932}To u konèíme?
{37936}{37973}To je ale línej uèitel!
{37976}{38043}Došly nám svíèky.
{38046}{38105}Zajdi pro nové.
{38108}{38234}Pìknì mì vytáèí.|Pøála bych si, aby umøel.
{38237}{38320}Uèí dobøe Bibli.
{38324}{38392}Jeho jméno, Kyu-shik, |je tak staromódní.
{38434}{38567}Znám jednoho kluka, |kterej mì taky tak štve.
{38571}{38625}Já mám ráda vepøové,|on má rád hovìzí.
{38629}{38692}Já mám ráda domácí cigarety,|ale on kouøí jen ty z dovozu.
{38696}{38762}Nemáme vùbec nic spoleèného!
{38765}{38827}A co je na tom všem nejhorší je, e...
{38830}{38896}ho mám ráda, ale jemu |se líbí moje kamarádka.
{38900}{38952}No a?
{38972}{39056}Jestli ho máš ráda, tak jdi do toho.|Pøeber jí ho!
{40043}{40112}Bong-hee!|Yang Bong-hee...
{40362}{40397}Kde asi je?
{40628}{40696}Mohli bychom to ještì zkusit?
{41105}{41148}Pøeju jí to.
{41184}{41229}Opravdu.
{41292}{41392}- Co tady dìláš?|- Zapaluju svíèky.
{41508}{41567}Nemohla jsem spát.
{41601}{41665}Proè? Nìco se dìje?
{41772}{41888}Jin-ho tady dnes byl.
{41952}{42054}Myslíš, e se k sobì hodíme?
{42093}{42124}Jin-ho a já?
{42181}{42221}Proè se ptáš mì?
{42272}{42375}Jak víš, nikdy jsem nebyl zamilovanı.
{42409}{42452}Tak se mì neptej.
{42731}{42792}Kde jsi byl?
{42841}{42896}Zase se šklebíš?
{42980}{43060}- Pojï se mnou.|- Kam?
{43064}{43135}No tak, uvidíš.
{43292}{43358}- Všechno pøipraveno?|- OK.
{43361}{43432}Jen do toho, otèe.
{43472}{43593}Poèkejte!|Osvìtlovací obøad zaèíná.
{43623}{43656}Pøipravte se...
{43659}{43744}Raz... dva... teï!
{44059}{44128}Myslím, e osvìtlování ulic...
{44131}{44185}mi jde lépe ne kázání.
{44188}{44269}Myslíš?|Tak osvìtli i ten zbytek.
{44299}{44327}Jasnì.
{44371}{44432}Co na to øíkáš?|Pìkné, ne?
{44500}{44628}Vypomáhali jsme, abychom si |na ty svìtla vydìlali.
{44696}{44746}- Je to pìkné.|- e?
{44812}{44837}Víš ty co?
{44840}{44947}Nikdy jsem se tolik nebál, |kdy jsme byli v semináøi.
{45018}{45075}Co, kdy ze mì opravdu bude knìz?
{45100}{45202}- Otèe, já to vezmu.|- To je v poøádku.
{45440}{45516}{Y:i}Oznámení o vysvìcení: |Kim Kyu-shik, Peter a Shin Sun-dal, Thomas
{45526}{45573}Je to hned za rohem.
{45693}{45728}{Y:i}Úvod do katolického katechismu
{45732}{45823}Za osmé: Nevzneseš falešného obvinìní |proti svému sousedovi.
{45826}{45928}Za deváté: Nebudeš touit po sousedovì enì.
{45932}{46036}Za desáté: Nebudeš dychtit po sousedovì domu.
{46076}{46164}Neple se tak u skuteèného testu.
{46167}{46191}Dobøe.
{46250}{46278}To by pro dnešek staèilo.
{46334}{46417}Blíí se tvé vysvìcení, e?
{46442}{46535}Tak mì napadlo...
{46569}{46626}Pøijdeš se podívat, a mì budou køtít?
{46629}{46715}Budu muset pryè, take...
{46747}{46792}Zkusíme to naneèisto.
{46850}{46875}Zkusíme co?
{46900}{46928}Køestní obøad.
{46975}{47021}- Dìláš si legraci.|- Hele!
{47024}{47124}Ty nejsi zvìdavı na køestní obøad |svého prvního áka?
{47128}{47220}A budeš knìzem, tak budeš køtít.
{47236}{47340}Cvièení dìlá mistra, ne?
{47514}{47547}Ve jménu...
{47596}{47623}otce...
{47665}{47693}i syna...
{47825}{47889}i ducha svatého...
{47936}{48031}køtím tebe, sestro Yang Bong-hee.
{49530}{49587}Sluší ti to víc, kdy to máš takhle.
{49883}{49911}Hotovo.
{49931}{49966}To staèilo.
{50032}{50057}Stùj!
{50154}{50229}Nemùeš se pohnout.|Øekla jsem "Stùj".
{50314}{50411}Ty a já jsme se zastavili v èase.
{50441}{50486}Stejnì tak i Panna Marie.
{50506}{50551}Dokonce i Bùh.
{50621}{50668}Nikdo nevidí.
{50703}{50750}Nikdo neslyší.
{50849}{50937}Jestli se mi chceš |k nìèemu pøiznat...
{50972}{50999}teï máš šanci.
{51120}{51150}Nic?
{51242}{51294}Kradl jsi?
{51316}{51411}Byl jsi exhibicionista?
{51453}{51488}Nebo...
{51530}{51599}Máš mì rád?
{51660}{51690}Nic?
{51791}{51816}Nic.
{51942}{52023}Já bych ti chtìla nìco øíct.
{52199}{52359}Nemùu se teï nechat pokøtít.
{52420}{52491}A nebudu moci vidìt tvoje vysvìcení.
{52537}{52653}Vracím se do Ameriky s Jin-hem.
{52793}{52884}Pøeju ti to. Opravdu.
{52887}{52984}- Vdycky jsi se chtìla vrátit.|- Myslíš?
{52988}{53028}Patøíš do Ameriky.
{53040}{53071}To je dobøe.
{53112}{53140}Opravdu moc dobøe.
{53300}{53335}Jo...
{54313}{54370}{Y:i}Nevstupuj do mého srdce
{54558}{54583}Hlupáèku!
{55812}{55849}Chtìl bych se na nìco zeptat.
{55872}{55957}Knìzùm je zakázáno milovat |jen jedinou osobu, e?
{56109}{56140}To vím.
{56200}{56226}Ale...
{56294}{56355}Dopustil jsem se høíchu.
{56443}{56478}Prosím, odpuste mi.
{56711}{56744}Ale...
{56874}{56928}kdy se budu kát...
{57042}{57094}ty pocity...
{57200}{57303}mohou bıt tak èisté, jako byly?
{57576}{57674}Udìlali pro náš kostel hodnì dobrého...
{57677}{57732}a brzy se vrátí do školy.
{57735}{57844}Prosím o potlesk pro tyto |dva seminaristy.
{59502}{59575}No tak.
{59854}{59882}Jedeme.
{59993}{60040}Poèkejte!
{60113}{60141}Dìkuji!
{60585}{60628}Byla bych ráda, |kdyby jsi se na to podíval.
{60715}{60784}- Co, e jsi najednou tak zdvoøilá?|- Jenom tak.
{60888}{60920}Co to má bıt?
{60938}{60997}Je jeden kluk, kterého mám ráda...
{61029}{61091}ale zdá se, e on o mì nemá zájem.
{61094}{61155}Tak jsem napsala dopis.
{61159}{61194}Podívej se na nìj.
{61248}{61287}A co dál?
{61310}{61390}Mám problém s pravopisem.
{61393}{61445}Podívej se, jestli tam |nejsou nìjaké chyby.
{61448}{61496}Nechci se ztrapnit.
{61535}{61632}"Jestli se mnou nikam nepùjdeš...
{61636}{61738}tak jsi Deo Gratias..."
{61775}{61846}- Jak jsi na to pøišla?|- Na co?
{61856}{61884}{Y:i}DEO GRATIAS...
{61888}{62019}Bong-hee to øíkala za tvımi zády, |kdy jsi šel kolem.
{62022}{62076}Deo Gratias... Deo Gratias...
{62080}{62146}Tak jsem se jí zeptala, |jestli to je nìjaká kletba.
{62184}{62215}Kletba?
{62244}{62320}Vdy víš, e tì nenávidí.
{62324}{62380}Tak jsem si jednoduše myslela, |e je to kletba.
{62384}{62491}Ale ona mi to nechtìla øíct |a poøád opakovala, e je to tajnı kód.
{62561}{62592}Tajnı kód?
{62624}{62704}Kdy se vyznáváš z lásky...
{62708}{62800}a nìkdo tì slyší, je to trapné.
{62830}{62951}Tak šeptám jen k Bohu..
{62992}{63073}e ho miluji a dìkuji mu.
{63076}{63126}Deo Gratias?
{63129}{63164}Deo Gratias.
{63352}{63407}Ty u se nevrátíš, e?
{63410}{63488}- Sbohem, otèe.|- Sbohem.
{63492}{63567}- Pøestaò chodit za školu!|- Sbohem!
{63571}{63642}- Zavolej mi, a dostuduješ.|- Sbohem!
{63983}{64032}{Y:i}Shin Sun-dale Thomasi, |uka nám, co dovedeš.
{64036}{64061}{Y:i}Buï dobrım pastorem.
{64606}{64639}Jsem tak nervózní!
{64668}{64751}Víc, ne kdy jsem poprvı |koukal na porno.
{64848}{64881}Nebuï nervózní, chlape.
{64896}{64994}Tréninkem jsme prošli bez zaváhání.
{65067}{65140}Takhle se budu cítit u oltáøe?
{65211}{65251}Sun-dale.
{65283}{65325}Øekni upøímnì.
{65357}{65413}Myslíš, e jsem dost dobrı, |aby ze mì byl knìz?
{65445}{65504}Ano, jsi dost dobrı na to, |aby z tebe byla lièka.
{65534}{65598}- Lièka?|- Knìzové jsou jako líce.
{65625}{65723}Mùeš jíst i bez ní za pomoci |hùlek nebo rukou.
{65726}{65785}To, co je dùleité je jídlo, ne líce.
{65880}{65929}Zhøešil jsem.
{65978}{66049}To není høích.|To je láska.
{66108}{66135}Sun-dale.
{66186}{66233}Bùh je na tebe pyšnı...
{66256}{66327}víc ne kdokoliv na zemi.
{69006}{69084}Moje nabídka stále platí.
{69148}{69183}Bì. Vím, e spìcháš.
{69258}{69307}Kim Woo-jine Paule...
{69311}{69407}na dùkaz, e svùj ivot |zasvìtíš Kristu...
{69411}{69453}na vìky vìkù...
{69456}{69539}a chceš slouit lidem a Bohu...
{69543}{69645}jsi ochoten sloit slib celibátu?
{69648}{69700}Deo Gratias.
{69807}{69900}- Shine Sun-dal, Thomas.|- Tady.
{70387}{70434}Shin Sun-dale Thomasi...
{70437}{70540}na dùkaz, e svùj ivot |zasvìtíš Kristu...
{70543}{70650}jsi ochoten sloit slib celibátu?
{70684}{70724}Deo Gratias.
{70795}{70912}- Kim Kyushik, Peter.|- Tady.
{71684}{71739}Kim Kyu-shiku Petere...
{71742}{71848}na dùkaz, e svùj ivot |zasvìtíš Kristu...
{71852}{71937}a chceš slouit lidem a Bohu...
{71940}{72057}jsi ochoten sloit slib celibátu?
{72212}{72331}Sloíš slib celibátu?
{73346}{73426}Mùj táta mi øekl, e by tam mìl bıt nìkdo, |koho miluji ze všeho nejvíc...
{73429}{73479}a dal tam tenhle obrázek.
{73520}{73601}Øekl jsem Bohu, e je mi líto, |e jsem zapomnìl...
{73638}{73671}koho miluji ze všech nejvíc.
{78019}{78047}Hej!
{78135}{78181}Øíkal jsem ti u jednou, |e se to nepije!
{78395}{78456}To jsi se nic nenauèila?
{78546}{78641}Co tady dìláš?|Myslel jsem, e odjídíš.
{78671}{78723}Co tady dìláš TY?
{79037}{79077}Nesluší mi, e?
{79215}{79303}Vypadám lépe v šatech.
{79368}{79471}Nemáš tušení, |jak je to nepohodlné.
{79565}{79639}Chození nahoru a dolù po schodech...
{79676}{79768}Chození na záchod...
{79848}{79962}Jízda na kole, kdy sedíš vzadu...
{80035}{80147}A ze všeho nejhorší je...
{80325}{80389}se k tobì pøiblíit, |kdy to mám na sobì.
{81121}{81168}Nebreè.
{81766}{81931}Dìkuji ti, e jsi mì |poctil tìmito šaty.
{81975}{82012}Deo Gratias.
{82200}{82314}Vypadáš staøe.
{82324}{82379}Nech to trošku volnì.
{82401}{82470}Proè jsi nepoèkala ještì chvilku?
{82492}{82520}Já?
{82545}{82669}Chtìla bych nìco øíct Bohu.
{82747}{82828}Taky bych mu nìco chtìl øíct.
{83087}{83280}Kdekoliv budu a jakkoliv se budu cítit,|budu tì vdycky milovat.
{83303}{83345}Deo Gratias.
{83600}{83800}Pøeloil Tadi|www.cesketitulky.com