{1}{1}23.976|Project.A.II.1987.WS.DVDRIP-DiGi
{500}{700}Èeské titulky Frogg 7.2005|{y:i}Pøeklad na asijskou verzi (cca 1:46)
{3050}{3130}P R O J E K T   A   2
{3170}{3229}{y:i}Pomoz mi.|{y:i}- U jdu.
{3283}{3306}Jak mu je?
{3309}{3383}Nejprv ho vytáhnìte z vody.|- Gatore! Gatore!
{3400}{3462}Gator je mrtvej.|{y:i}Jsme v Hong Kongu.
{3500}{3587}Kdy jsme se plavili|se San-po, nic jsme nechtìli.
{3590}{3659}Mìli jsme všechno.|{y:i}A podívej se teï!
{3662}{3707}{y:i}Jsme jak naplavenı døevo.
{3710}{3755}{y:i}Kdo nám tohle zpùsobil?
{3777}{3860}Drak Ma, roztrhám tì na cucky.
{3863}{3939}Dobrá, pøísahejme.
{4262}{4351}Nepøestaneme, dokud Drak Ma nezemøe.
{4426}{4460}Dobré ráno, pane Chune.
{4474}{4507}Dobré ráno.
{4510}{4547}Dobré ráno.|- Dobré ráno.
{4550}{4576}{y:i}Prosím, posaïte se.
{4602}{4654}Jako obvykle?|- Ano, díky.
{4892}{4935}Úèet.|- Úèet, prosím.
{5039}{5144}Jsou pøipraveni jít do vìzení.|Jejich rodiny budou odškodnìny.
{5147}{5209}A reportéøi?|- Jsou nahoøe.
{5212}{5284}My jsme pøipraveni, èeká se na tebe.|- Objednáme si nìco k jídlu.
{5305}{5348}Jídlo je nahoøe.
{5351}{5397}Zajdu pro to.|- Dìkuju.
{5400}{5450}Chvilièku strpení.|- Poslute si.
{5515}{5590}Ani hnout! Tohle je pøepadení!|- Ani hnout!
{5603}{5655}Ne!|- Moje peníze!
{5678}{5724}Moje peníze ...
{5775}{5823}Ani hnout!|- Jdeme.
{5863}{5914}Zastavte je!
{5941}{5996}Pøepadení!|- Zapla to.
{6104}{6149}Policie, stát!
{6342}{6371}Pane!
{6418}{6473}Odveïte je.|- Zkontrolujte restauraci.
{6506}{6538}Pane Chune.
{6541}{6585}Chan-jim?
{6588}{6640}Jsme od novin.|- Jste bájeènı.
{6643}{6692}Udìláme si fotku.|- Pojïte.
{6695}{6788}To není nic pro mne.|- Dostal jste je tak snadno.
{6791}{6884}Dostal jste na nì echo?|- Ne, byl jsem na pravidelné pochùzce.
{6887}{6965}Pane Chune, mohu vám øíkat|poruèíku Chune?
{6968}{7023}Popravdì mi to lichotí.
{7026}{7120}Z èeho jsou obvinìni?|- Loupe a útok na policistu.
{7123}{7201}Udìláme foto. Stoupnìte si k sobì.
{7239}{7292}{y:i}Pane!|Majitel restaurace je mrtev.
{7327}{7403}Mìli by bıt obvinìni z vrady.|- Souhlasím s vámi.
{7406}{7434}Coe?
{7437}{7478}Udìlali jsme co jste nám øekl!
{7481}{7549}Nezavradili jsme ho!|- Zavøete je!
{7643}{7673}Stát.
{7743}{7801}Dostali jsme jen HK$300! Slíbil jste ...
{7938}{8005}Pokusili se utéct. Odneste tìla!
{8045}{8095}Pane Chune, tady.
{8137}{8179}{y:i}Mùe mi to nìkdo vysvìtlit?
{8182}{8280}Všichni jsme vìdeli, e|Chun fingoval svoje zatèení.
{8283}{8333}Teï do toho bude šourat veøejnost.
{8336}{8390}Kdybyste jen po nìm nechtìli tolik, ...
{8393}{8457}... nemusel by podvádìt se zatıkáním.
{8460}{8497}Svìøili jste mu tøi okrsky!
{8500}{8579}Chun je jedinı policista|v Èínì, kterı mùe nosit zbraò.
{8582}{8618}Vìdìl jsem, e se to stane.
{8621}{8717}Jsem proti nošení zbraní èínskımi policisty.|- A jste i proti vıplatám, ne?
{8720}{8812}Situace by mìla rozhodovat,|kdo dostane zbraò a kdo ne, ...
{8815}{8873}... nikoliv barva pleti.
{8876}{8928}A mzdy by mìly bıt rovné.
{8931}{9028}O tom budeme diskutovat jindy.|Teï se soustøeïme na Chuna.
{9031}{9135}Vede tøi okrsky.|Nemùeme ho jen tak propustit.
{9152}{9240}Pozvolna ho nahradíme,|poèínaje Sai Wanskım okrskem.
{9243}{9284}Ale kdo ho nahradí?
{9287}{9338}Vím o nìkom.
{9341}{9420}O nìkom, kdo mìl na starosti "Projekt A".
{10115}{10147}Vemte je zpátky!
{10284}{10331}Pane, ale na to nemám kvalifikaci.
{10334}{10411}To ale nikdo neví a za pokus to stojí.
{10437}{10488}A zmìna prostøedí se ti bude líbit.
{10685}{10775}{y:i}To je za vaší vynikající slubu.|Gratuluji!
{10823}{10885}Dìkuji, pane. Dìkuji, pane.
{10888}{10981}Také vám chceme trošku|odlehèit od toho tlaku.
{10984}{11017}To není tøeba.
{11020}{11100}Nechceme naše nejlepší mue pøetìovat.
{11103}{11219}Take svìøíme jeden|z vašich okrskù nìkomu novému.
{11222}{11264}Dostali jsme nìjaké nové zbranì.
{11267}{11362}Vaše pistole slouila u nìjakı|ten pátek. Chci jí nechat zkontrolovat.
{11365}{11421}Podívat se jestli nepotøebujete novou.
{11600}{11640}Hlásím se do sluby, pane.
{11643}{11730}Draku, teï budete Chunovım|zástupcem v Sai Wanském okrsku.
{11733}{11778}To jsou vaše oficiální rozkazy.
{11899}{11978}Od teï, vy a Chun budete spolupracovat.
{11981}{12052}Máte-li otázky, ptejte se jeho.
{12055}{12098}Je mi ctí s vámi pracovat.
{12101}{12214}Vítejte, jsem si jist,|e budete uiteènou posilou.
{12217}{12267}Dejte mi vìdìt,|kdy budete nìco potøebovat.
{12270}{12339}Chune, moná jste|pøišel o jeden okrsek, ...
{12342}{12449}... ale mùete získat jinı.
{12452}{12477}Opravdu?
{12480}{12518}Nikdy nevíte.
{12557}{12599}Aha. Chápu.
{12925}{13033}Díky zkorumpované manduské|vládì je naše zemì chudá.
{13036}{13122}Stali jsme se poddanou rasou.|- Nechcete si koupit kvìtinu?
{13125}{13220}{y:i}Jedinì správnım|{y:i}postojem, mùete pomoci Èínì.
{13223}{13337}{y:i}K zajištìní lepší ivotní|{y:i}úrovnì, musíme svrhnout vládu.
{13340}{13468}Doktor Sun zaloil|"Revive China Society" pro podporu revoluce.
{13471}{13557}{y:i}Jenom øeèi Èínu|{y:i}nespasí, potøebujeme skutky.
{13560}{13642}{y:i}Potøebujeme peníze na zbranì.
{13645}{13675}Policie.
{13694}{13732}Dìkuji, e jste mì vyslechli.
{13735}{13781}Chcete si koupit kvìtinu?
{13927}{13961}{y:i}Maggie!
{13972}{14020}Regina!|- Stùjte.
{14023}{14109}Kde jsi byla?|- Hledala jsi mì?
{14112}{14168}Ne tak úplnì. Kam jdeš?|- Sai Wan.
{14171}{14206}Naskoè.
{14259}{14317}Moje sestøenice Carina,|moje spoluaèka Regina.
{14320}{14399}Nesetkali jsme se u?|- Právì pøijela.
{14487}{14551}Poøádám veèírek pøíští|tıden. Ráda bych vás pozvala.
{14554}{14631}To bude tvoje narozeninová párty?|- Je tam vdycky taková sranda.
{14634}{14659}Pøiveï Carinu.
{14662}{14707}Pøijdeš?|- Co si ale obleèu?
{14710}{14759}Však ona ti nìco pùjèí.|- Urèitì.
{14791}{14849}Podpoøte revoluci a kupte si kvìtinu.
{14852}{14928}Ne, díky.|- Mohu si jednu koupit?
{14931}{15019}Jestlie on chce zachránit|Èínu, tak mi dejte taky jednu.
{15022}{15100}Dobrı nápad, já chci taky jednu.|- Dìkuji, pánové.
{15135}{15206}Jojo. Já chci taky jednu.|- Kolik?
{15217}{15304}Pane, revoluce by mohla|uspìt, pokud bude kadı jako vy.
{15307}{15338}Taky doufám.
{15534}{15607}Dìkuju.|- Kde je obvykle prodáváte?
{15610}{15685}Kdekoliv jsou lidé,|kteøí si je koupí.
{15714}{15757}Pojïme jíst.
{15805}{15864}Co je to?|- Policajti, schovejme krabice.
{15988}{16120}Šíøíte pomluvy,|podkopáváte mír a ebráte, správnì?
{16140}{16226}Nemáte ádné dùkazy.|- Ty kytky jsou dùkazy.
{16276}{16344}A podívejte se na kytky co jste prodaly.
{16368}{16454}Vy pánové, jste moji svìdci.|Prodala vám tahle ena kvìtiny?
{16457}{16492}Ne.
{16521}{16548}Coe?!
{16551}{16628}Tak jak to, e máte v klopì kytky?
{16631}{16746}Vidíme se poprvé, døíve jsme si|jen dopisovali, tak abychom se poznali.
{16749}{16856}Take dìvèata mìli dret|košík a my mìli pøinést rùi.
{16859}{16934}Málem jsme si vás nevšimli!|Mìli jste je dret vıš.
{16937}{16968}Pojïte, sednìte si.
{16988}{17047}Vypadáš krásnìji ne tvé písmo.
{17050}{17156}Take já nás pøedstavím -|Pan A, já jsem pan B, pan C, pan D.
{17205}{17254}Je snad setkávání dopisovatelù nezákonné?
{17295}{17347}Dobøe, tentokrát jste vyhráli.
{17353}{17450}Dávejte si pozor. Nepøejte si,|abych vás nachytal prodávat kytky.
{17453}{17522}A my rozhodnì nehrozíme jen tak naprázdno.
{17617}{17652}Èaj, sleèno?
{17655}{17742}Nesnáším tyhle utlaèovatele|ve slubách cizích pánù.
{17745}{17821}Pøesnì. Myslí si kdoví jak|nevypadají v té uniformì úchvatnì.
{17824}{17894}Jsou to kreténi. Souhlasíte?|- Ne tak úplnì.
{17897}{17970}Nìkteøí policisté|jsou poctivı døíèi.
{17973}{18035}Tak to jsem adného ještì nepotkala.|- Ale urèitì ano!
{18038}{18116}My jsme všichni od policie.|A nikdy jsme nikoho neutlaèovali.
{18183}{18258}Take všichni jste od policie.|- Omluvte nás.
{18288}{18389}Sleèno, osud Èíny závisí|na vlastencích jakımi jste vy.
{18392}{18440}Nezapomeòte si pokladnièky.
{18722}{18836}Draku, myslíš, e bysme jim|pomohli, kdyby nebyly tak pìkné?
{18839}{18896}Platit, èíšníku.|{y:i}- Ano, pane.
{18919}{18964}{y:i}Ti policisti byli opravdu milí.
{18967}{19034}Nebıt jich, tak máme poøádnı trable.
{19037}{19107}{y:i}Dobøí policisti prostì neexistujou.
{19110}{19182}{y:i}Kolik si toho prodala?|{y:i}- Docela dost.
{19185}{19229}{y:i}Tak to je tvùj šastnı den.
{19232}{19273}A ty?|- Nic moc.
{19313}{19400}Pomoc!|- Pomoc!
{19507}{19552}{y:i}Vrate se!
{19908}{19947}Ne tak rychle.
{20176}{20259}Take znovu vy.|Co se tu dìje?
{20262}{20367}Snaili se okrást tyto dámy.|{y:i}- Udìlejte cestu.
{20435}{20516}Opravdu? Jaké dámy?|{y:i}- Z cesty.
{20519}{20577}Uhnìte.
{20580}{20628}{y:i}Zvláštní, kam zmizely?
{20643}{20721}Stráníku, co se tu stalo?|- Nic. Vemte je na stanici.
{20724}{20790}Mùeš to odvyprávìt mì.
{20793}{20861}Radìji bych mluvil s nìkım nadøízenım.|- Nemá èas.
{20864}{20910}Pane?|- Co je?
{20951}{21003}Pracujeme pro tygra.|- Pøesnì tak.
{21006}{21061}To ale není ádná omluva.|- Správnì.
{21064}{21128}Ale my ádnı enskı nepøepadli.|- Opravdu?
{21130}{21216}Tak jak víš, e to byly eny?|- Zmlkni! Ptal se tì nìkdo?
{21219}{21277}Hele, je tu serant Chi?|- Serant Chi?
{21280}{21337}Prohráls. Mám ti podat stejnou sázku?
{21349}{21384}Zvedni to na dolar.|- Opravdu?
{21387}{21412}Jo.
{21415}{21486}Poèkej, tyhle chtìjí vidìt seranta Chi.
{21499}{21526}Tudy.
{21562}{21613}{y:i}Tak a vy chásko, tohle podepište.
{21632}{21698}Nemìli byste dìlat takovej bordel!
{21701}{21778}Jsme nevinní, pane.|- Kecy.
{21781}{21869}201, vyprovoï je.|- Vypadnìte odsud.
{22014}{22091}Mohu mluvit?|- Co chceš øíct? Poslu si.
{22094}{22151}Chci vidìt vašeho nadøízeného.|- Proè?
{22180}{22252}Chci nahlásit špatnou práci policistù.
{22255}{22329}Dobrá. Shangu, vezmi je dozadu.
{22406}{22486}Poèkat! Po jednom.|Ty pojï se mnou.
{22501}{22545}Sungu!|{y:i}- U jdu.
{22548}{22589}{y:i}Tudy.
{22675}{22758}Tak kde je?|- Tohle je náš nadøízenı.
{22761}{22842}Take co e to bylo|za stínost na policisty?
{22845}{22883}Jen se mu vypovídej.
{22886}{22985}Snad si neèekal, e ta tvoje|poslední šou zùstane bez odezvy, ne?
{23014}{23062}Dám ti pìknou lekci.
{23384}{23459}Ne, pomoc.|{y:i}Pomozte mi nìkdo!
{23538}{23583}Dost. Nech toho.
{23914}{23995}Zùstaòte kde jste.|Jsem váš novı velitel pro Sai Wan.
{23998}{24048}Tady jsou mé doklady.
{24111}{24175}Veliteli, došlo ke strašnému omylu.
{24177}{24253}Jestlie si stráníci|myslí, e mohou zneuívat ...
{24256}{24292}... svıch pravomocí ...
{24295}{24373}... k vyøizování úètù a ochranì grázlù ...
{24393}{24506}To je taky nedorozumìní.|- Pane, musíte nám vìøit.
{24509}{24559}Vidìl jsem to právì na vlastní oèi.
{24589}{24625}Kdo si myslíte, e jste?
{24628}{24706}Jestli to chcete|takhle, tak já konèím.
{24709}{24763}Správnì, mùete si tu|dìlat práci za nás za všechny.
{24777}{24832}Take vy jste nikdy neudìlal chybu?
{24835}{24886}Opravdu chcete,|aby dali všichni vıpovìï?
{24889}{24924}{y:i}Dobrá, taky konèím!
{24927}{25017}Co to do vás vjelo kluci?|On to s vámi myslí dobøe.
{25020}{25085}Prosím, neberte je vánì.
{25088}{25179}Jestli od teï budete dìlat|svoji práci poøádnì, zapomenu co se stalo.
{25182}{25215}Slyšeli jste?
{25268}{25314}Vítejte, veliteli Ma!
{25324}{25389}Malı dárek na|uvítanou, pro vás, pane.
{25392}{25463}Od všech chlapcù?|- Ano, pane.
{25505}{25577}Take v Sai Wan se dá pøijít na pìknı prachy.
{25580}{25634}Jen ukázka našeho ocenìní.
{25637}{25731}Jen jeden stráník odmítl pøispìt.
{25734}{25757}Kdo?
{25760}{25825}Stráník Ho,|je stále ještì na obchùzce.
{25828}{25861}Pošlete ho ke mì, a se vrátí.
{25864}{25922}Ano, pane.|Kdy bude nìco potøebovat ...
{25925}{25968}Dobøe.
{26012}{26081}Pane, to je krásná kvìtina.
{26103}{26135}Díky.
{26326}{26400}Hele. Je hledanı u tøi roky!
{26403}{26495}Je podezøelım v hromadì nedávnıch|pøípadù. A poøád ije v Sai Wan.
{26498}{26536}Tady je taky uvedenı jako podezøelı.
{26539}{26634}Tak proè ho ještì nesebrali?|Moná, e nechtìli.
{26659}{26780}Veliteli. Stráník Ho, pane.|- Vy jste na mì nepøispìl. Proè?
{26783}{26840}Protoe neberu úplatky,|tak jsem si to nemohl dovolit.
{26843}{26930}Take ostatní tedy berou?|- To jsem neøekl.
{26933}{27003}Kdy nebudeš rozumnı,|nevydríš v téhle práci dlouho.
{27006}{27078}Mojí prací je slouit|lidem a dohlíet nad zákonem.
{27081}{27209}Radìji dám vıpovìï, ne brát úplatky.|- Vypadáš jako èestnı chlap.
{27211}{27311}Øekni mi víc o tìch nevyøešenıch pøípadech.
{27314}{27434}Tygr Au je tady místním šéfem.|Nejradši bych ho zavøel.
{27437}{27516}Ale nemám na to.|{y:i}Má kolem sebe moc strácù.
{27519}{27603}Tyhle grázlové jsou jeho lidi.|- A kde bysme ho našli?
{27606}{27675}Šéfuje celımu|organizovanım zloèinu v Sai Wanu.
{27678}{27730}Obvykle bıvá v hotelu Po Luk.
{27733}{27808}Øekni ostatním,|a pøijdou zítra ráno døíve.
{27986}{28070}Dobøe, dokud budete dìlat|svoji práci poctivì, budu spokojenı.
{28073}{28123}Nepotøebuji ádné obálky.
{28158}{28211}Chtìli byste bydlet vedle bordelu?
{28214}{28322}Nebo vidìt své dìti|hrát hazard nebo kouøit opium?
{28325}{28386}{y:i}S vìdomím jak to nièí celou rodinu?
{28389}{28472}Nechtìli a to nechtìjí|ani obyvatelé Sai Wanu.
{28475}{28559}Ale bordely,|hazardní doupata jsou na kadém rohu
{28562}{28624}{y:i}A vy víte komu patøí.
{28627}{28712}Naším úkolem je chránit|obyvatele a to taky hodlám dìlat.
{28715}{28786}A proto, dneškem poèínaje,|zaèneme èistit mìsto.
{28840}{28867}Jdeme.
{28870}{28952}Veliteli, pokud máte dost|muù, já bych zùstal tady.
{28974}{29047}Mohu si vzít volno?|- Proè?
{29050}{29137}Já bych si dneska taky vzal volno?|- A proè. Jeden po druhém.
{29151}{29216}ena je tìhotná.|- Má sestra je tìhotná.
{29219}{29294}To je mi náhoda!|- Moje sestra je jeho ena.
{29297}{29338}Moje ena je jeho sestra.|- Jo jo.
{29358}{29432}Pane, mohu dát vıpovìï?|- Z jakého dùvodu?
{29435}{29521}Jsem jediné dítì v rodinì.|Take radìji nechci jít.
{29524}{29668}Já, také. Ty peníze|za to nestojí, konèím.
{29671}{29735}Já taky.|- Zrovna tak.
{29775}{29837}Dobøe, operace se ruší.
{29857}{29886}Rozchod.
{30075}{30101}Ale Draku ...
{30160}{30200}Pojïme.
{30320}{30415}Take teï víte, proè jsem tak|znechucen. V podstatì nechtìjí dìlat nic.
{30418}{30464}Teï donutili Draka, zrušit operaci.
{30467}{30552}Co tím myslíš?|Urèitì má nìjakı dùvody.
{30555}{30642}Moná chce poslat nìkoho,|aby tygra nejdøív okouknul.
{30645}{30788}Ne. Testuje lidi,|kdo má odvahu a kdo je srab.
{30791}{30856}Teï ví, e se na nì|nemùe spolehnout. Je to tak?
{30859}{30964}Má pravdu. Jsme s Drakem|u tak dlouho, u víme jak myslí.
{30967}{31002}Ach, vánì?
{31005}{31083}Tak tentokrát jste vedle.|- Dìláš si srandu?!
{31086}{31171}Jestli tahle operace sele,|tak si budeme muset sbalit a jít.
{31174}{31257}Má pravdu.|Nemùeme selhat jinak jsme vyøízenı.
{31270}{31349}Marsi, vezmeš dopis k námoønictvu.
{31365}{31475}Chceš se nechat pøeloit zpìt?!|- Dnes v noci sbalíme tygra.
{31526}{31604}Léta jsme se takhle všichni nesešli.
{31607}{31646}Na vaše zdraví.
{31727}{31784}Tygøe, slyšel jsem,|e pro nás máš nìjakou fušku.
{31787}{31855}To je pravda.|Právì jsem se setkal s Chunem.
{31858}{31952}Odebrali mu okrsek Sai Wan|a dostal ho nìjakej zelenáè.
{31979}{32051}My poèkáme na Marse tady.|Ty to bì obhlídnout.
{32179}{32202}Dìkuju.
{32294}{32359}Jsme se pøevlíkli,|tak proè tak èumí?
{32362}{32403}Máš obrácenì èepici.
{32424}{32465}A co teï?|- To ujde.
{32468}{32505}Na co to je?|- Tady.
{32508}{32598}Kašli na to.|Pojïme se nejdøív najíst.
{32601}{32673}Tygøe, kdy jsme ztratili Chunovu ochranu, ...
{32676}{32721}... kdo pak bude dohlíet na naše zájmy?
{32724}{32833}Jakmile si øekne o laskavost,|musíme mu vyhovìt, a to stojí co chce.
{32879}{32961}Jakmile se ten novej|tıpek ukáe nìkde kolem, ...
{32964}{33008}... tak na to do smrti nezapomene.
{33032}{33108}Proè èekat a pøijde sem?|Bì si pro nìj na stanici.
{33138}{33247}Kdo to vùbec je?|Je to snad nìjakej velkej drsòák?
{33275}{33320}Marsi, tady jsme.
{33391}{33414}Mluvil jsem s Ying.
{33417}{33488}Øíkala, e námoøníci|jsou nìkde na manévrech.
{33491}{33547}Budeme i tak pokraèovat?
{33550}{33637}Zvládneme to sami.|- Teï u nemùeme couvnout.
{34448}{34481}Nicmoc se nedìje.
{34505}{34589}Jak si øíkal, e se jmenuje?|- Drak Ma.
{34605}{34635}Drak Ma?
{34638}{34705}Pamatuješ ten co vymlátil piráty?
{35895}{35966}Kdo z vás si øíká Tygr?|- Já.
{35983}{36065}V tom pøípadì,|pùjdeš s námi na stanici.
{36068}{36153}Na stanici? Kdo sakra jsi?|- Drak Ma.
{36195}{36279}Jsi hledán ve spojení|s 3 vradami, 4 loupeemi, ...
{36282}{36344}... jedním únosem a 3 útoky.
{36347}{36394}Tady je zatykaè.
{36397}{36441}To jsem všechno udìlal já?
{36444}{36482}Ukate mi to.
{36599}{36646}Promiò, netrefil jsem se.
{36754}{36799}Draku, odcházíme?
{36873}{36906}Pøestaòte hrát.
{36922}{36945}Pøestaòte.
{36948}{37046}Dobøe, jsme policisté.|Pokud tu nemáte nic dùleitého, ven!
{37055}{37154}Èas jít.|Rychle, všichni. Jdìte.
{37212}{37251}{y:i}Draku Ma.
{37371}{37449}Je milé, e jste se stavil.|Chtìl jsem se s vámi setkat.
{37452}{37545}Vdycky jsem chtìl|potkat slavného Draka Ma.
{37548}{37580}Asi mì hledáte.
{37583}{37677}Ty dvì vrady v zátoce|"Causeway", obì jsou moje práce.
{37765}{37872}Mì byste mìl taky sebrat,|protoe se chystám oddìlat fízla.
{37875}{37989}Draku Ma, nikdo vám to neøekl?|Jste mrtvej.
{37992}{38068}Jednoho dne|urèitì umøu jako všichni.
{38084}{38143}Ale zatím, vás zatıkám.
{38466}{38506}Draku!
{38599}{38682}Draku, tøetí jednotka|je venku, èekají na rozkazy.
{38701}{38738}Draku!
{38772}{38836}Zbylé dvì jednotky jsou na pozici.
{38850}{38892}Nikdo mi o tomhle neøekl.
{38895}{38956}Nestùj tam jen tak.|Pøiveï je dovnitø.
{38959}{39003}Pøiveï je.|- Jo.
{39055}{39098}Dám pøíkaz k útoku.
{39125}{39158}Jsou pøipraveni.
{39161}{39286}Zapomeòte na to.|Konec blafování, jsme v tom sami.
{39303}{39341}Máš odvahu.
{39412}{39487}Nemìl by ses starat o zatıkání, ...
{39490}{39583}... ale o to,|jak se dostat odsud ivej.
{39634}{39682}Dveøe.|{y:i}- Ano.
{39732}{39768}V klidu.
{39771}{39804}V klidu.|- V klidu.
{39809}{39846}Klid.|- Klid.
{39862}{39895}Zmizte odsud!
{39898}{39930}V klidu!
{39967}{40004}A co teï?
{40015}{40060}Teï ...
{40063}{40128}... zapomeòte, e se odsud dostanete.
{40334}{40357}Na nì!
{40910}{40933}Pozor!
{41446}{41525}Bastarde! Teï tì nìco nauèím.
{41623}{41657}Bastarde!
{42946}{42980}Zatknout mì?!
{42996}{43084}{y:i}To bys musel mít|{y:i}víc ivotù ne koèka, abys mì zatkl.
{43241}{43324}Vy ètyøi na kolena. Chyte ho!|- Rozkaz!
{44232}{44288}U máš dost?
{44291}{44333}Nezapomeò jmenuji se Wong.
{44468}{44514}Vpøed!
{44678}{44726}Po schodech. Rozmístit!
{45332}{45380}Draku, jsi v poøádku?
{45459}{45544}Draku, jaké pøekvapení!|Koukám, e tvrdì døeš.
{45561}{45603}Jak to jde?
{45606}{45683}Kladli odpor pøi zatıkání.
{45686}{45785}Vánì? Chápu, odveïte je.
{45788}{45837}Poèkat. Coe?
{45854}{45908}Jsme snad piráti? Nebo pašeráci?
{45929}{45993}Tady jste na souši, tady nemáte pravomoce!
{45995}{46089}Toho jsem si vìdom, pane.|Ale mám podezøení na piráty, tady v hotelu.
{46092}{46221}Veliteli, prosím pokraèujte,|nerad bych vás pøerušoval.
{46260}{46312}Spoutejte je.
{46365}{46456}Obkliète je, a vemte je na základnu.
{46459}{46521}Tam je vyslechnìte,|jestli to nejsou piráti.
{46556}{46658}Ty. Ty. Obklíèit.|Odveïte je na základnu!
{46661}{46708}Tak tak.
{46926}{46953}Odveïte je.
{46967}{47031}Jsi v poøadku?|- Mohli jste pøijít rychleji.
{47033}{47078}Pohyb.|- Jdeme.
{47081}{47149}Dìkuji. Máš to u mì.|- Byli na moøi.
{47152}{47218}Pøipluli jakmile dostali zprávu.
{47229}{47267}Draku Ma!
{47270}{47308}Kdyby nebylo ...|- Dr hubu
{47326}{47360}Poèkat!
{47411}{47456}Tyhle dva puste.
{47513}{47606}Pokud se vám povede|odsud odejít, jste volní.
{47633}{47673}Tak, teï nás nechte.
{47676}{47711}Ty taky.
{49584}{49637}Spoutejte je!
{49862}{49922}Ty se nikdy nezmìníš.
{49947}{50040}Kdyby policejní práce byla|tak lehká, u dávno bych to vzal.
{50043}{50076}Já vím, pane.
{50095}{50159}Ale nezapomeò,|jsi poøád jedním z nás.
{50161}{50206}Musíme nìkdy zajít zase na ryby.
{50255}{50356}Draku, otec øíká, e na souši|se vìci mají jinak a zvláš tady.
{50359}{50405}Musíš bıt opatrnı.
{50428}{50477}Vemte je na stanici.
{50480}{50528}Pohyb! Dìlej!
{50621}{50676}Co to bylo?|- To byl urèitì Drak Ma.
{50679}{50721}Sejmem ho!|- Deme na to.
{50724}{50781}Jak? Má tam celou armádu.
{50784}{50835}Policajti šli po pirátech.
{50838}{50902}Vidíš? Musí u vìdìt o našem plánu.
{50904}{50960}Co budeme dìlat?|- Mùeme jít døív spát.
{50963}{51029}A kde budeme spát?|- Kde budeme spát?
{51032}{51094}Teï ho zabít nemùeme, najdem si hotel.
{51097}{51128}Musíme vyèkat.
{51152}{51185}Máš pravdu.|- Jo.
{51188}{51222}Cigaretu?|- Ne, díky.
{51225}{51294}Chune, berete si ty sloky?|- Mám to v úmyslu.
{51297}{51388}Budu je potøebovat a se sem vrátím.|- Opravdu? A kdy to bude?
{51391}{51479}Vìøím, e brzy.|Ne kadı je vhodnı pro tuhle idli.
{51482}{51510}Máte pravdu, pane.
{51529}{51602}Nìkam je ulote.|On se brzy vrátí.
{51696}{51742}Serante, mohl byste ...?
{52080}{52120}Draku Ma!
{52145}{52231}Vdycky jsem chtìl pochytat|tyhle grázly, a teï je máte.
{52234}{52271}To je úasné.|- Dìkuju.
{52274}{52308}Chune.|- Dr hubu!
{52311}{52354}Co tím chceš øíct?|- Zamknout.
{52357}{52421}Ses nám nìjak vybarvil.|- Odveïte je.
{52423}{52459}Chune!|- Sklapni!
{52471}{52523}Neslyšels?! Odvést!
{52542}{52594}Slyšíš? Odveï je!
{52850}{52881}201.
{52884}{52945}Tygr pøijde do bezpeènostního køídla.
{52948}{52986}267, 357.
{52989}{53053}Wong taky.
{53072}{53147}282, vezmi pár muù a zapeèe hotel.
{53165}{53197}Serante Chingu.
{53200}{53293}Pozavírejte ten zbytek a sepište vıpovìdi.
{53296}{53358}Zbytek zaène dìlat|na dalších hledanıch kriminálnících.
{53361}{53406}Jasné?|- Ano, pane.
{53422}{53457}Tak to práce.
{53478}{53507}Pohyb!
{53584}{53657}Pracoval jste velmi tvrdì.|Odpoèiòte si.
{53675}{53711}Uvidíme se pozdìji.
{53758}{53828}{y:i}Správnì pane.|{y:i}Dejte si nohy hezky nahoru.
{53831}{53879}Hned jsem u vás se šálkem kávy.
{53882}{54014}Kam mam dát tyhle sloky?|- Idiote! Nìkam to odnes.
{54150}{54260}{y:i}Draku, komisaø je|{y:i}se zátahem velice spokojen.
{54282}{54382}{y:i}Nedìkuj mì.|{y:i}Zatím ti ještì nemùeme dát ádnou medaili.
{54385}{54445}Pamatuj, nenechte se tím unést.
{54448}{54525}Nenechám, pane.|- Proto jsem tady, abych na to dohlédl.
{54572}{54663}Na oslavì komisaøovi|dcery mìj oèi na stopkách.
{54666}{54704}Budu v pohotovosti.
{54707}{54745}To nestaèí.
{54748}{54844}Musíš pøedvídat kadı Chunùv tah.
{54874}{54953}Kdy se nìco semele, obvinìn budeš ty.
{54956}{54996}Dìkuji, pane.
{54999}{55065}Mìl by sis sehnat vhodné obleèení.
{55068}{55162}Ty i tvoji mui potøebujete|nové obleèení. Tohle by to mìlo pokrıt.
{55469}{55514}Tahle krysa nenasytí ani jednoho z nás.
{55554}{55587}Kam jdeš?
{55590}{55675}Vykrást obchod.|Chci normální jídlo, ne krysy.
{55678}{55734}Nemáme co ztratit.|- To je pravda.
{55737}{55789}Ale pøišli jsme zabít Ma.
{55792}{55869}Kdy vylezeme ven,|tak nás za pár minut zašijou, ...
{55872}{55944}... a pak nikdy nepomstíme kapitána.
{56024}{56075}Mám udìlat krysí polívku?
{56078}{56139}Nejedl jsem polévku s masem u léta.
{56238}{56296}Hoši, mluvil jsem s Chunem.
{56299}{56388}Souhlasil jsem s krádeí|náhrdelníku na narozeninové párty.
{56391}{56423}To nechápu.
{56426}{56487}Nedìláme to pro Chuna.
{56490}{56570}Dìláme to pro revoluci.
{56573}{56642}Dobøe nám za to zaplatí|a mi si pak koupíme zbranì.
{56645}{56773}Ví Chun, co jsme zaè?|- Ví, e pašuju zbranì.
{56775}{56840}Ale myslí si, e jsem jen zlodìj.|- To je dobøe.
{56843}{56883}Myslím, e za pokus to stojí.
{56886}{56972}Mimochodem, ne jsem odjel|z Kantonu, doktor Sun mne varoval.
{56975}{57035}Po vradì Kantonského guvernéra, ...
{57038}{57129}... na nás poslala|vdova císaøovna tajné agenty.
{57132}{57215}Øeknìte Maggie a Carinì|a jsou opatrné pøi prodáváni kytek.
{57233}{57283}Rozchod. Pojï se mnou.
{57384}{57426}Našel jsem to.|- Cos našel?
{57429}{57463}Humra.|- Fakt?!
{57466}{57534}Je to jeho krunıø.|- Jenom krunıø.
{57537}{57599}Tady je nìjaká ryba.|- To je super.
{58215}{58295}Co jste zjistil?|- Normálnì...
{58298}{58395}Jsou roztroušeni po celém mìstì.|Je tìké zjistit kde jsou.
{58398}{58495}Ale Carina je èasto|tady v okolí a prodává kytky.
{58498}{58532}Mohli bychom zaèít s ní.
{58545}{58618}Tentokrát je musíme znièit všechny.
{58650}{58685}Ano, samozøejmì.
{58737}{58764}To je nádhera!
{58805}{58849}Cítím se trapnì, jít tam takhle.
{58852}{58902}Nebuï hloupá.|- Ale fakt.
{58905}{58957}Uvnitø se pøevleèeme.
{59023}{59049}To je pan B.
{59281}{59335}Ta pozvánka je pouze pro jednu osobu.
{59345}{59383}Je to tu napsáno.
{59386}{59466}Ale mohla by jít se mnou, prosím?
{59481}{59541}Jistì, myslím, e to nebude problém.
{59544}{59644}Maggie. No koneènì.|- Jdeš pozdì.
{59647}{59683}Pojï!
{59752}{59789}Co vás tak zdrelo?
{59792}{59853}Bìte napøed.|- A to netrvá.
{59874}{59949}Pojï, vybereme ti nìjaké šaty.
{60025}{60119}Ten gentleman nechtìl pustit|moji sestøenici dovnitø bez pozvánky.
{60139}{60205}A vy jste kdo?|- Jsme od policie.
{60215}{60252}Máme na starosti bezpeènost.
{60255}{60298}A jak se jmenujete?
{60322}{60364}Tohle je Drak Ma.
{60387}{60468}Zapomnìla jsem jí dát|pozvánku, mùe zùstat?
{60471}{60499}Samozøejmì.
{60518}{60602}Dìkuju. Tak jdeme!|- Dìkuju, pane Ma.
{60726}{60778}Pardon.|- V poøádku.
{60898}{60954}Øekni Marsovi, a na nì dohlédne.
{60993}{61051}Co jsou zaè?|- Tomu chlapíkovi øíkají Mu.
{61054}{61134}Tu enu neznám.|- Pozor na cizince.
{61305}{61337}Dìkuju.
{61340}{61375}Je nádherná.
{61378}{61438}Víš kdo to je?|- Nemám ponìtí, pane.
{61441}{61491}Take mì nikdo nepøedstaví?
{61494}{61543}Já vás jí pøedstavím, pane.
{61580}{61644}Vy ji tedy neznáte?
{61766}{61806}Pøipraveni?
{61809}{61895}Tudy. Náhrdelník je|v pracovnì za obrazem.
{61898}{61950}Nádech.|- U to bude.
{61997}{62034}To je ono.
{62037}{62098}Ty šaty jsou dost tìsné.
{62101}{62144}To jsou všechny.
{62147}{62187}Otoè se.|- Nehıbat.
{62190}{62278}To staèí. Co myslíš?|- Nádhera!
{62306}{62401}Take jste vyrùstala|v Šanghaji, ale nemáte pøízvuk.
{62404}{62501}Moná nemám, ale nemusíte mít|obrovskou nohu, abyste mohl bıt atlet.
{62504}{62527}Promiòte.
{62530}{62628}Sleèno, jste velmi vıøeèná.|Je mi potìšením potkávat lidi jako vy.
{62631}{62706}Tohle øíká všem enám.|Vùbec ho neposlouchejte.
{62709}{62798}Vaše excelence|objevila vskutku vzácnou perlu.
{62827}{62892}Vypadáš nádhernì v tìch šatech.
{62969}{63021}Radìji se soustøeï.|- Jasnì.
{63044}{63089}Tatínku, jsem krásná?
{63092}{63156}Samozøejmì, zlatíèko.
{63158}{63201}A co šaty?
{63204}{63258}Ale já mluvil o šatech.
{63307}{63375}Mohu mít první tanec. Pojïme.
{63710}{63774}Sleèno, smím prosit?
{63777}{63843}Jen bì. Bude se ti to líbit.|- Smím prosit?
{64061}{64126}Nikdy pøedtím jsem|netanèila mezi tolika lidmi.
{64372}{64428}Tatínku, jsi šastnı?|- Samozøejmì.
{64431}{64521}Dnes ti to náramnì sluší.|- A proè se na mì nedíváš?
{64524}{64571}Kde bydlíte?|- "James Street".
{64574}{64638}Je to nebezpeèné|místo, musíte bıt opatrná.
{64641}{64757}S policisty jako vy, kteøí|chytají zloèince, je to celkem bezpeèné.
{64760}{64852}Myslíte, e Hong Kong|je nebezpeèné místo k ivotu?
{64855}{64897}Nebezpeèné? Ani ne.
{64900}{65009}Co dìláte celı den?|- Sedím v kanceláøi a piju kafe.
{65045}{65096}A opustím parket,
{65099}{65192}Jdi nahoru s Carinou odlákat stráce.
{65195}{65245}Neboj. Víme co dìlat.
{65248}{65314}Jak mùete øíct, e je to|bezpeèné, se vším tím zloèinem?
{65317}{65406}Kdyby nebylo zloèinu,|nebylo by tøeba policie.
{65409}{65460}Moná bychom si mohli dát spolu èaj.
{65470}{65527}Promiòte, mìla jsem k obìdu èesnek?
{65653}{65735}Komisaøova pracovna|je naproti Meggiínì lonici.
{65746}{65819}Vylezu tam z venku.|Poèkej na mì v jejím pokoji.
{65822}{65854}Dobøe.
{65868}{65997}Ve volném èase nakupuji,|chodím do divadla, a maluju.
{66000}{66062}Malujete? Miluji malování.
{66933}{66989}Co to?|- Roztrhla jsem si šaty.
{66992}{67023}Co se dìje?
{67041}{67092}To spravíme.|- Omluvte mne.
{67244}{67290}Nikdo si s námi nevymìnil partnera.
{67293}{67345}Nevyhovuje vám má spoleènost?|- Ale ovšem.
{67348}{67442}Ale musím na dámy.|- Ach ano, chápu.
{67445}{67513}Ukái vám cestu.|- Dìkuji.
{67569}{67616}Tak uka spravím ti to.
{67761}{67807}Stíníš mi. Nehıbej se.
{67880}{67924}Je tu horko.|- Není.
{67927}{67999}Máš pravdu, otevøi okno.|- Já to udìlám.
{68002}{68082}Pozvánky jsou pravé,|ale jak se k nim dostali?
{68085}{68136}Na parketu není, myslíš, e ...
{68408}{68455}Øekni mi, které se ti líbí.
{68510}{68549}Ty jsou krásné.|- Které?
{68571}{68594}Tiše.
{68597}{68620}Co se dìje?
{68664}{68768}Nic. Máš krásnou postavu.|- Vánì? Díky.
{68790}{68850}Co se dìje, Carino?|- Nic.
{68916}{68976}Které si mám vzít?
{68979}{69003}Jdi!
{69130}{69204}Promiòte, omlouvám se ... prosím.
{69248}{69319}Tati, myslela jsem,|e bych si vzala tyhle k dortu.
{69322}{69376}Proè se nezeptáš mé pøítelkynì sleèny Pak?
{69379}{69446}Vypadáš nádhernì v èemkoliv.|- Dìkuju.
{69449}{69498}Líbili se mi ty, cos mìla prve.
{69518}{69567}Tak to si je moná opìt obleèu.
{69570}{69614}Ta dìvèata ...
{69694}{69745}Nevidìl jste ...|- Já nevidìl nic, ...
{69748}{69802}... ale vy jste vidìl mou dceru svleèenou.
{69805}{69900}To e máte na starost bezpeènost neznamená,|e mùete vlítnout kam se vám zlíbí. Ven.
{70042}{70094}{y:i}Pomatenec!
{70331}{70427}{y:i}Tak dámy. A to netrvá moc dlouho.
{70502}{70535}Má lonice je zde.
{70538}{70600}A jak vypadá vaše lonice?
{70623}{70704}{y:i}Rychle.|Èekají na mì s dortem.
{71153}{71183}{y:i}Váš pokoj je obrovskı!
{71186}{71283}Od smrti mé eny|si myslím, e je a moc velkı.
{71323}{71371}Prosím.
{71414}{71445}To je nádhera!
{71448}{71521}Je to je obyèejná pracovna|pro mue ve slubách impéria.
{71524}{71640}Mé jsou jen|obrazy, zbytek patøí vládì.
{71643}{71712}{y:i}Take mi nemùete dát suvenır?
{71734}{71796}{y:i}Právì jsem je koupil.|{y:i}Proto nejsou orámovány.
{71799}{71883}{y:i}Mohu je vidìt?|{y:i}- Jestli chcete, klidnì.
{71886}{72008}Samozøejmì. Tenhle jsem|koupil v Londınì. Moc se mi líbil.
{72011}{72113}{y:i}Mì se také moc líbí!|{y:i}Ten druhı se vám také bude urèitì líbit.
{72116}{72149}Hned ho donesu.
{72152}{72206}Krom toho, e je sbíráte, malujete?
{72209}{72290}{y:i}Ano, obèas.
{72293}{72372}Ale stydìl bych se|své obrazy nìkde ukazovat.
{72375}{72443}{y:i}A vy? Co nejradìji malujete?
{72446}{72565}{y:i}Èínské krajinky.|{y:i}- Opravdu? Ty mám rád.
{72568}{72611}{y:i}Ale moc toho o nich nevím.
{72614}{72715}{y:i}Ještì mám nìkde dva|{y:i}dalši, ale nemohu si vzpomenout kde.
{72742}{72816}Tady nejsou.|Moná ještì nejsou vybalené.
{72819}{72870}{y:i}To nevadí, jestli je nemùete najít.
{72873}{72961}{y:i}Máme èas, dort ještì není.
{72964}{73024}{y:i}Tady nejsou. To je zvláštní.
{73027}{73072}{y:i}Moná je ještì nepøivezli.
{73341}{73378}Ani hnout!
{73381}{73431}Zadr!|- Co se dìje?
{73446}{73494}Co se dìje?|- Zlodìj, pane.
{73582}{73615}Co se stalo?
{73647}{73714}Co to dìláte?|- Došlo k loupei!
{73777}{73810}Sakra!
{74190}{74246}Jakı krásnı dort!
{74311}{74354}Je tak velkı.
{74390}{74429}To je krása.
{74575}{74608}Omlouvám se.
{74630}{74665}Zùstaòte kde jste.
{74686}{74724}Omlouvám se všem.
{74743}{74780}Jste zatèen.
{74801}{74840}Já?|- Co se dìje?
{74860}{74941}Tohle nemùe popøít.|Vidìl jsem ho krást v pracovnì.
{74944}{75044}Nìkdo ukradl náhrdelník,|kterı jsem koupil dceøi k narozeninám.
{75047}{75070}To on.
{75073}{75146}Obviòujete mne z krádee? A dùkazy?
{75149}{75193}Pro jistotu ho prohledejte.
{75196}{75284}Bude mít øadu kumpánù,|pochybuji, e jej má u sebe.
{75293}{75406}Draku, kdy nìkoho obviníš,|musíš to podloit.
{75409}{75489}Dámy a pánové,|nelíbí se nám to o nic víc ne vám.
{75492}{75531}Ale aby byla prokázána vaše nevina, ...
{75534}{75608}... vìøím, e nebudete mít|policistùm za zlé, kdy vás prohledají.
{75611}{75703}Chcete mì šacovat?|- Jestli jste nevinnı, tak vám to nevadí.
{75706}{75758}Klidnì, mùu bıt první.
{75761}{75868}Aèkoliv, aby to byl fér,|by mìl zaèít pan Ma.
{75871}{75912}Dobrá.
{75915}{75979}Chune, prohledáte ho?
{75981}{76059}Šéfe, lepší, kdy to udìláte vy.
{76062}{76106}Dobøe, kdy myslíte.
{76363}{76413}Je to èást diamantového náhrdelníku.
{76444}{76482}Kde jsi to vzal?
{76485}{76535}Nìkdo to na nìj musel nastrait.
{76665}{76727}Pan Ma je vánì skvìlı herec.
{76730}{76837}Dámy a pánové,|to vše bylo souèástí programu veèera.
{76840}{76940}Jeliko je pan Ma|tak dobrı herec, všechny nás nachytal.
{76943}{77005}Doufám, e se kadı bavil.
{77008}{77059}Tatínku!|- Pøekvapení.
{77062}{77144}Vydìsil jsi mì k smrti.|- Dáme si dort.
{77323}{77375}Opravdu to bylo pøichystané, pane?
{77378}{77434}Jistì, e ne. Kde je náhrdelník?
{77437}{77468}Nemám tušení, pane.
{77471}{77535}Tak co dìlalo tohle u vás v kapse?
{77561}{77626}Poaduji vysvìtlení!
{77677}{77707}Take to nebyla hra?
{77710}{77793}Pøipadalo vám to jako hra?|- Ne, asi ne.
{77796}{77849}A co teï?|- To bych se mìl ptát já vás.
{77852}{77933}Vy jste policista.|- Zatknìte ho.
{77936}{77989}Ale, pane ...|- Ticho! Je to rozkaz.
{77992}{78079}Oèekávám, e tomu|rychle pøijdete na kloub.
{78140}{78183}Odveïte ho.
{78264}{78337}Musíš si nìco pøát.|- Dobøe.
{78634}{78705}{y:i}Nastrailas to na Draka s tím náhrdelníkem?
{78709}{78776}{y:i}Moc o tom nevím, ale je nevinnı.
{78779}{78820}{y:i}Je to hodnı èlovìk.
{78823}{78912}Nezapomeò, e to bylo pro dobro naší zemì.
{78915}{78961}{y:i}Horké knedlíky!
{78964}{79029}Dáš si knedlíky?|- Dobøe.
{79102}{79141}S èim je chceš?
{79157}{79214}Carino.
{79412}{79451}Kde jsi?
{79554}{79597}Maggie, co se dìje?
{79637}{79692}Moje sestøenice zmizela.|- Coe?!
{79695}{79797}Najednou se vypaøila.|- Vypaøila?
{79880}{79921}Nechce mluvit, ale našel jsem tohle.
{79924}{79995}Bìte na tu adresu,|jestli tam nejsou ostatní.
{79998}{80021}Ano, pane!
{80024}{80118}Musíte se vyhıbat policii.|- Ano.
{80121}{80198}{y:i}Jestli to šéf zjistí,|{y:i}èekají tì velké problémy.
{80201}{80242}{y:i}Ne, kdy najdeme ten náhrdelník.
{80245}{80298}{y:i}Myslíš, e je v tom Carina zapletená?
{80301}{80374}Ona a Mu tancovali celı veèer.
{80417}{80520}Pane! Tady je propustka.|Mám povolení vzít jej ven.
{80564}{80646}Je to snad váš první|den ve slubì? A co náramky.
{80680}{80720}No proto.
{80832}{80884}Tohle si nechám u sebe, pro jistotu.
{80984}{81059}Co je?|- Nemusí to kadı vidìt.
{81120}{81168}Pùjdeme za dozorcem.
{81191}{81300}Jediné co po vás chci je, aby|byl vìzeò pøeváen cestou smìrem k moøi.
{81303}{81387}Potom u nebudete|muset nikdy v ivotì pracovat.
{81390}{81465}Je to vánì tak jednoduché?|- Pøesnì tak.
{81492}{81520}Dohodnuto.
{81569}{81604}Je tu nìkdo?
{81762}{81812}S trochou štìstí se brzy vrátí.
{81897}{81920}Tiše!
{81954}{81999}Carino. Carino!
{82137}{82188}Ach, ne. Nikde ji nevidím.
{82191}{82295}To by mì zajímalo, kdo ji unesl.|{y:i}- Nìkdy je lepší nevìdìt.
{82356}{82387}To je ona!
{82438}{82462}Znovu vy dva.
{82465}{82543}Jo. Nìco nového o Carinì?|- Ještì se nevrátila. A vy?
{82546}{82580}{y:i}Pracujeme na tom.
{82583}{82624}Poèkejte, dopøevléknu se.
{82649}{82688}Kdo je to?|- Drak a jeho kolega.
{82691}{82748}Jde o náhrdelník.|Radìji se schovám.
{82786}{82863}Nìjakı nápad?|- Urèitì to souvisí s tím náhrdelníkem.
{82866}{82919}To bude pravda.|- Máš v tom prsty?
{82922}{82978}To jen komisaø kamufloval trapnou situaci.
{82981}{83069}Nezná tvoje sestøenice nìkoho, kdo si øíká Mu?|- Ne, nezná.
{83083}{83126}Posaïte se, prosím.
{83265}{83314}Jsme jako bratøi.|- Jo jo.
{83475}{83520}Nepotøebuješ na záchod?|- Ne.
{83523}{83577}Ale prve si øíkal, e potøebuješ.|- Kdy?
{83580}{83632}Jojo, vlastnì jo.
{83635}{83711}Kde tu máte koupelnu?|- Koupelnu?! Támhle.
{83714}{83772}Díky.|- Ale je tam jen jeden záchod.
{83775}{83864}Vdycky chodíme spolu.|- Jo, u od dìtství.
{83986}{84037}Èístej vzduch?|- Jsou v koupelnì.
{84040}{84085}Dobøe. Tak já mizím.
{84391}{84448}Chvilièku, zrovna se pøevlékám.
{84494}{84582}Šéfinspektor Tung je tady!|- Co ten tady chce?
{84585}{84647}Zabav ho, jdu se schovat dozadu.
{84650}{84706}Šéfinspektor Tung?
{84728}{84777}Prosím pojïte dál.|- Pro vás.
{84780}{84844}Dìkuji. Èemu vdìèím za vaši návštìvu?
{84846}{84929}Mìl jsem zrovna cestu kolem.|- A ty kvìtiny?
{84932}{84990}Ty jsem zrovna zabavil.
{85013}{85085}Musím øíct, e to tu máte velice pìkné.
{85088}{85167}{y:i}Tak svìtlé a vzdušné|{y:i}a krásnì dekorované.
{85170}{85253}{y:i}Z celého místa vyzaøuje jakısi enskı cit.
{85256}{85347}{y:i}A samozøejmì tak krásná|{y:i}vùnì èerstvıch kvìtin.
{85358}{85408}Oh, ano, vaši dva dùstojníci ...
{85435}{85477}Co moji dva dùstojníci?
{85607}{85686}Co je s nimi?|- Kde jste je nechal?
{85713}{85795}{y:i}Všichni na mì èekají dole.
{85818}{85904}Chodím na obchùzku do této|ètvrti kadı den. Jen pro jistotu.
{85937}{85975}{y:i}Co se dìje?
{86020}{86086}Jste v poøádku?|- Jen zaívání.
{86191}{86234}To je škytavka. Znám na ni lék.
{86268}{86307}Zabírá to?
{86310}{86391}Je to starobylı recept.|Vdycky zabírá.
{86428}{86502}A jste vyléèena. Jak jsem øíkal.
{86521}{86568}U se cítíte lépe?|- Ano.
{86571}{86636}Teï kdy zase nìkdy dostanete|škytavku, tak u víte co dìlat.
{86639}{86666}Zajímalo by mì ...
{86669}{86751}Nedáme je do vázy?|- Jo, jistì!
{86894}{86947}Pomohu vám.
{86950}{87020}Kde máte vodovod?|- Za vámi.
{87139}{87244}Toto okno normálnì pøi vaøení zavírám.
{87272}{87306}{y:i}A teï nìco vaøíte?
{87380}{87459}Ne, zrovna ne,|take jej mùu nechat otevøené.
{87462}{87546}Tady máte malej problém,|ale opravím vám to.
{87549}{87582}Dìkuji.
{87603}{87636}Tudy.
{87756}{87783}Ani se nehni.
{87876}{87937}To nic, je to jen voda.
{87948}{88036}Radìji si stoupnìte dál,|a se nenamoèíte. Bude to minutka.
{88054}{88098}Skoèím vám pro ruèník.
{88330}{88380}V poøádku, vzduch je èistı.
{88557}{88633}Pardon. Opravil jsme to,|ale jsem celı zmáèenı.
{88651}{88678}Dìkuji.
{88681}{88727}Take se vyznáte v instalatérství?|- Zajisté.
{88730}{88797}Døíve jsem dìlal šéfa ve vodárnách.
{88828}{88865}Moje uniforma je celá mokrá.
{88868}{88934}Tak já vám ji povìsím.|- To byste byla hodná.
{88960}{89002}Dost bylo hrdinství.
{89174}{89202}Vy jste tu ještì?!
{89205}{89255}Dole je hromada policajtù.
{89258}{89301}Klíèe.
{89392}{89425}Rychle!
{89470}{89500}Maggie!
{89583}{89625}Kdepak jste?
{89673}{89766}Hotovo! Kam je mám postavit?|- Do obıváku.
{89769}{89853}Mohla byste tohle dát sušit|a pùjèit mi nìjaké triko?
{90071}{90116}Co se dìje?|- Nejde to otevøít.
{90119}{90161}Ukate, zkusím to.
{90226}{90300}Vlivem vlhka se døevo|mùe roztáhnout. Podrte to.
{90303}{90347}Zkuste tuhle stranu.
{90350}{90381}A je to.
{90485}{90558}Doufám, e vám to bude.|- Bude muset.
{91034}{91089}Dìkuji.|- Pøeehlím vám svršek.
{91092}{91173}Nene, to se nesmí ehlit. Pouze vyvìsit.
{91176}{91248}Ale to je v poøádku.|Jsem trpìlivı. Klidnì poèkám.
{91536}{91581}Tak to mì tlaèilo!|- To jsou ...
{91584}{91644}To jsou náramky. Zajišujeme jimi vìznì.
{91647}{91750}Kdy zatkneme zloèince,|tohle dáme na jeho ruku ...
{91753}{91836}... a ten druhı konec na|svoji ruku a on tak nemùe utéct.
{91839}{91911}No a kdy jsou zlodìji dva|a jeden se dá na útìk, pak ...
{91936}{91987}Bingo! A ten první u neuteèe.
{91990}{92088}A zatím mùu bìet za tím|druhım, ten první u na mì poèká.
{92156}{92239}Nechal jsem klíèek ve svršku.|- Dojdu pro nì.
{92348}{92401}To musí bıt vaše sestøenice.
{92464}{92487}Ahoj.
{92528}{92607}To je Chun!|- Opravdu? Øeknìte mu, e tu nejsem.
{92610}{92661}On ale pøišel nejspíš za mnou.
{92664}{92741}Tak mu øeknìte, e tu nejste.|- Ale on mì u pøeci vidìl!
{92744}{92796}Proè jsem se to jen spoutal?|Musím se schovat.
{92875}{92918}Potøebuju úkryt.
{92963}{92993}Zrovna se pøevlékám.
{93070}{93120}Pomozte mi.|- Jdìte tudy.
{93123}{93189}Dobrá, rychle.|- Tam tudy!
{93192}{93224}Tudy.
{93227}{93272}Au! To bolí!
{93317}{93365}Rychle!|- Kam se mám schovat?
{93368}{93416}Pod postel.|- Ok.
{93419}{93489}Radìji pod tuhle.|- Dobøe, tak nejdøív ten gauè.
{93492}{93551}Nejdøív si tam vlezte vy.
{93554}{93622}Kdy myslíte.|- Tak rychle.
{93875}{93898}Ani se nehni.
{93929}{93987}Omlouvám se, zrovna jsem se pøevlékala.|- To je v poøádku.
{93990}{94076}Chune, jste tu sluebnì?|- Ano, jsem.
{94079}{94130}{y:i}Máte to tu pìkné.
{94218}{94327}{y:i}Máte nìjaké stínosti ohlednì ètvrti?
{94330}{94424}{y:i}Ano, mnoho.|{y:i}- Opravdu? Sem s nimi?
{94427}{94520}{y:i}Tak, zaèíná to tu bıt|{y:i}pìknì nebezpeèné. Minulou noc ...
{94559}{94595}{y:i}Zapomeòte na to.
{94598}{94659}{y:i}Prosím, posaïte se.|{y:i}- Dìkuji.
{94662}{94726}{y:i}Pùjdu udìlat trochu èaje.|{y:i}- Moc díky.
{94728}{94826}{y:i}Ach ne, nemám horkou vodu.|{y:i}Skoèím pro nìco k pití ven.
{94829}{94865}{y:i}To nemusíte.
{94868}{94976}Chune, to takhle navštìvujete|v rámci sluby všechny obèany?
{95011}{95045}Ano, samozøejmì.
{95057}{95117}No, radìji bych u mìl jít.|- Dobrı nápad.
{95149}{95232}Nashle! Mìjte se, Chune.
{95235}{95356}Nezapomeòte se stavit|a budete mít zase cestu kolem.
{95483}{95513}Já?
{95530}{95559}Jo ...
{95945}{96013}{y:i}Kdy Chun šel, tak já radìji taky pùjdu.
{96029}{96060}Co to dìláte?
{96063}{96120}Myslel jsem ... polibek na rozlouèenou.
{96130}{96163}Ne, není tøeba!
{96182}{96223}{y:i}To byla krása.
{96244}{96299}{y:i}Pospìšte si, nebo pøijdete pozdì.
{96337}{96380}{y:i}Polibek jste dostal, tak bìte.
{96470}{96509}Kdy pùjdete?|- Teï.
{96512}{96573}Slíbil jsem,|e se setkám s pár dùstojníky.
{96581}{96648}Tak co?|- Nahoøe jsou dva chlapi.
{96651}{96681}Další dva?
{96684}{96746}Jak se sem všichni dostali?|- Co teï?
{96765}{96821}Pojïte, tudy.|- Dobøe.
{96897}{96932}Kde jsou ty zatracenı klíèe?
{98201}{98233}Pokraèujte, pokraèujte.
{98647}{98726}{y:i}Co jste zaè? Na nìj!
{98729}{98785}{y:i}Jsi tu sám?{y:i}|{y:i}- Cos tady dìlal?
{98788}{98839}{y:i}Byls to ty?|{y:i}- Dìlej vypal mu jednu.
{98842}{98917}{y:i}Mluv!|{y:i}- Bodni ho, bodni ho do srdce.
{98922}{98990}{y:i}Nakopej mu prdel.|{y:i}- Dobøe.
{99013}{99057}{y:i}Chcípni!
{99060}{99120}{y:i}Tak budeš mluvit nebo co?!
{99123}{99184}{y:i}Dìlej!|{y:i}- Poèkej, u ho nemla.
{99187}{99268}{y:i}Dost. Nehejbe se. Je mrtvej?|{y:i}- Ne, není.
{99285}{99333}{y:i}Mluv nebo ti ustøelím palici.
{99338}{99442}Dost! Mám dvì rukojmí.|Pohnìte se a oba je oddìlám.
{99445}{99500}My máme taky rukojmí.|- Choyi, jsi v poøádku?
{99503}{99538}Jistì, pøeije to.
{99560}{99643}Dobøe, vymìníme si|rukojmí, ale ádnı triky.
{99646}{99679}Pohyb!
{99815}{99859}Choyi, si ranìnı?
{99980}{100019}Ani se nehni.
{100036}{100113}Pane, dostal ho!|- Seeò mi klíèe.
{100116}{100159}{y:i}Mìla jsem o tebe strach.
{100196}{100239}Pracuju pro její velièenstvo.
{100242}{100306}A co tedy dìláte tady?
{100308}{100402}Jsem tu abych zatkl rebely.|Hong Kongská policie na nás nemùe.
{100405}{100442}My tu ale máme jiné zákony.
{100445}{100548}A ty v Hong Kongu|platí pro kadého, tedy vèetnì vás.
{100561}{100637}Spoutej ho s tímhle dohromady.
{100660}{100697}A pošli je hezky domù.
{100700}{100797}Pane, nemùu je najít.|Hmm, tak je ustøelíme.
{100800}{100852}Co kdy mineš?|- Neminu.
{100855}{100897}Nejprve je spoutej.
{100900}{100964}A co já? Kouknìte na mì.
{101052}{101085}Opatrnì, pane.
{101088}{101204}O mne se nestarejte,|hlavnì vrate Ma do vìzení.
{101207}{101262}Pøíštì se podepíšu jinak.
{101387}{101429}Šéfe, vaše ruka.
{101443}{101553}Má ruka drí dùkaz,|e se jedná o zlodìje.
{101556}{101624}Kde máte klíèe? Otevøete mi to.|- Ano, pane.
{101654}{101715}Mám sice náramky, ale klíè ne.
{101733}{101775}Dobrá, jdu je odvést.
{101778}{101899}Draku, jste stále vìzeò|do západu slunce musíte bıt zpìt.
{101917}{101999}Odvedu jej zpìt.|- Klidnì to udìlám za vás, pane.
{102031}{102080}Tak jdeme, jdeme.|- Pohyb.
{102083}{102128}Víte, co máte dìlat.
{102171}{102218}Z cesty! Uhnìte.
{102221}{102289}Draku, znáš pravidla, ne?
{102292}{102325}Ano.
{102451}{102531}Pane, mùete mi sundat náramky?|Já neuteèu.
{102534}{102580}Nemám zrovna u sebe klíèe.
{102734}{102798}Draku Ma, seš mrtvej mu!
{102819}{102889}Kdo jste?|- Jsme obìti tvého hraní si na hrdinu.
{102892}{102924}A dneska tì zabijem.
{102964}{103005}S tím nemám nic spoleèného.
{103008}{103066}Tak zmizni.
{103091}{103135}A co já?!|- Hodnì štìstí.
{103138}{103204}Tohle je za kapitána San-poa.
{103238}{103281}Moje klíèe! Moje klíèe!
{103284}{103389}Stát. Víte kdo to je?|- Jsem inspektor.
{103424}{103469}{y:i}Tak na to ti serem!
{103560}{103598}Nahoru.|- Co?
{103665}{103717}Øekl jsem nahoru.|- Neslyšel jsem tì.
{103810}{103877}No tak, musíme spolupracovat.
{103974}{104013}Vıš.
{104016}{104051}Z cesty!
{104088}{104131}Ne tudy ne.
{104206}{104274}Jsme od policie!|Pomoc, jsme napadeni.
{104341}{104385}Tudy, rychle.
{104437}{104473}Musíme skoèit.
{104504}{104536}Rychle!
{104618}{104696}Stùjte.|- Rychle!
{104814}{104847}Rychle, tudy.
{104919}{104948}Otevøete. Otevøete.
{105207}{105243}Zadrte!
{105246}{105327}Tady, stráníku.|- Tady, stráníku.
{105489}{105529}Proè jste mì praštil?
{105775}{105814}A co tohle.
{105830}{105872}Pojïte.
{105888}{105928}Rychle.|- Nahoru.
{105966}{106009}Ne.
{106148}{106181}Ne, tudy.
{106276}{106309}Tudy.
{106383}{106420}Pojïte.
{106616}{106662}Málem jste mì zabil!
{106792}{106828}Tudy!
{107101}{107165}Ty! Øekni mi co jste zaè nebo tì zabiju.
{107411}{107444}Pomoc!
{107481}{107513}Rychle.
{107643}{107671}To bolí!
{107679}{107743}To jsou oni.|- Tyhle jsou od policie!
{107746}{107810}Seberte ty chlapy uvnitø, rychle!
{107812}{107890}Slez dolù, jdou sem fízlové. Padáme.
{108088}{108131}Chleba?!|- Rychle, bìíme.
{108134}{108185}Ale to je chleba!|- No a?
{108218}{108285}Jsou pryè.|- Všichni zpátky na stanici.
{108288}{108343}Coe?! Pronásledujte je!
{108451}{108515}Odkud jste, pane?|- Shandong.
{108518}{108595}V celém Shandongu, není nikdo tak ...|- Tak vysokı jako já?
{108598}{108635}Ne, takovı støevo.
{108638}{108677}Coe?
{108680}{108711}Jdeme!
{109031}{109107}{y:i}A se vrátíš do Kantonu,|{y:i}mìla bys sis radìji dávat pozor.
{109110}{109191}{y:i}Jsou tam na kadém kroku špióni.|{y:i}- Dám si pozor.
{109194}{109275}Nemám moc èasu.|Prosím pøedej tohle Maggie.
{109278}{109349}Doufám, e a se setkáme pøíštì,|tak budeme oslavovat vítìzství.
{109352}{109382}Jistì.
{109385}{109421}Na shledanou.|- Na shledanou.
{109939}{109991}To je Chun.
{109994}{110068}Hej, inspektore.|- Pane dozorèí. Rád vás tu vidím.
{110071}{110125}Jste v poøádku?|- Málem mì zabili.
{110128}{110180}Kam jdete?|- Zpìt do mé kanceláøe.
{110183}{110236}Skvìlé, mohl byste ho vzít zpìt do vìzení.
{110239}{110279}Máte klíèe?
{110408}{110451}Bì sehnat ostatní.
{110478}{110516}Dìkuji.|- Nemáte zaè.
{110525}{110561}Sbohem, Draku.
{110583}{110613}Nashle.
{110686}{110735}Èíšníku, šálek èaje.|{y:i}- Jistì.
{110789}{110838}Tudy se ale nejde k vìznici.
{110841}{110894}Je to taková zkratka na jiné místo.
{110897}{110943}Kam?
{110966}{111007}Do pekla.
{111173}{111244}{y:i}Co to dìláte? Puste mì!
{111257}{111292}{y:i}Co to dìláte?
{111370}{111404}Rychle!|{y:i}- Puste mì!
{111490}{111533}{y:i}O co vám jde?
{111655}{111719}Kdyby se nìkdo ptal,|tak spadl do vody a utonul.
{111722}{111754}Jistì.
{111843}{111872}Jdeme.
{111992}{112053}Nevypadá moc dobøe.|- Má hlad.
{112056}{112129}Jak to mùeš vìdìt?|- Ty snad nemáš?! Všichni máme.
{112132}{112199}Má fakt horkı èelo.|- Má horeèku.
{112202}{112257}Za to mùe Drak Ma.
{112260}{112369}Nemùe, mùeme si za to sami.
{112372}{112495}Kdybych nám po pøistání našel|všem poøádnou práci místo hledání Maa, ...
{112498}{112550}... nikdy by to takhle nedopadlo.
{112553}{112618}Tak si to ale mìl øíct na zaèátku.
{112621}{112666}Ale zabil spoustu našich bratrù.
{112669}{112784}Je to jeho práce, je to policajt,|stejnì jako naše práce byla vradit.
{112787}{112862}Proè si to neøekl døív?|- Jo!
{112865}{112929}To je fuk! Musím teï|pøijít na to, co s ním.
{112932}{112965}Jsi v poøádku?
{112980}{113032}Je mi horko i zima.
{113048}{113112}Horko i zima!|- Coe?!
{113115}{113183}Musíme sehnat nìjakı léky.|- Jdeme.
{113200}{113283}{y:i}Dìkuji za propuštìní mıch muù.|{y:i}- Je ještì nìco, s èím vám mohu pomoci?
{113286}{113360}{y:i}Pøijel jsem sem, dopadnout skupinu vrahù.
{113363}{113411}{y:i}Nabízí vláda nìco na oplátku?
{113414}{113479}{y:i}Na kadého z nich byla vypsána odmìna 5,000.
{113482}{113533}{y:i}Pak bych vám moná mohl bıt k uitku.
{113567}{113637}To by bylo skvìlé.
{113967}{114056}Tak to vy jste mi zachránili ivot.|- Kdyby jsme neudìlali co po nás Chun chtìl, ...
{114059}{114112}... nebyl bys skonèil ve vìzení.
{114115}{114177}Dluili jsme ti to.|- Proè jste to na mne ušili?
{114180}{114259}Potøebovali jsme peníze na zbranì,|take jsme se dohodli s Chunem.
{114262}{114340}Pak jsme si ale uvìdomili,|e jsme pomohli obvinit nevinného.
{114343}{114379}Kde je náhrdelník?
{114382}{114460}Je v komisaøovì pracovnì,|v jedné z jeho knih.
{114499}{114604}Zachránili jste mi ivot.|Asi bych pro tentokrát mìl pøimhouøit oko.
{114607}{114653}Odcházíte?|- Bez obav.
{114656}{114772}Nikomu o vás nic neøeknu.|- Tím pomùete naší revoluci.
{114775}{114829}Ale stejnì nám dìláte starosti.|- Vánì?
{114832}{114888}Chcete i nadále zùstat u policie?|- Co jiného mi zbıvá?
{114891}{114955}Pøipojte se k nám.
{114973}{115078}S kolegy jako vy,|bychom mìli vìtší šanci.
{115081}{115114}Nechci se pøidat.
{115150}{115203}Jste stále naštvanı?
{115206}{115270}Nìkdy je potøeba porušit pár|pravidel pro dosaení vyšších cílù.
{115272}{115358}Jsme pøipraveni za revoluci poloit naše ivoty.
{115361}{115473}Právì proto se k vám nemùu|pøidat. Nemohu prostì porušovat zákony.
{115476}{115538}Nehledì na dùleitost|cíle, a nemohu to zmìnit.
{115541}{115662}Co se mì tıèe,|nemùu prostì porušit zákon.
{115678}{115766}Aèkoliv vás obdivuju.|A myslím, e jednoho dne uspìjete.
{115769}{115892}Chápu, e svrení vlády|si vyádá nejeden lidskı ivot.
{115895}{115938}Ale já bych o to nikoho ádat nemohl, ...
{115941}{116044}... protoe nevím, co by zbylo|a by krveprolití pominulo.
{116076}{116116}Take radìji zùstanu policistou.
{116119}{116228}Podle mne je kadı ivot vzácnı|a chci aby kadı ivot byl šastnı.
{116231}{116312}Zemì se 400 miliony lidmi|je zaloená na individualistech.
{116315}{116401}Pokud nesnáší svoje ivoty,|tak jak mohou milovat svoji zem?
{116404}{116479}Chápu co tím myslíte.|A budu si vaše slova pamatovat.
{116482}{116556}Oba pracujeme pro lid,|ale kadı svım zpùsobem.
{116559}{116619}Take bıt policistou|je pøeci jen ušlechtilé.
{116622}{116731}Ale oni nechtìjí ádné|"dobré" policisty v koloniích.
{116734}{116767}Znièí vás.
{116770}{116818}Jsem tu, abych se tìmhle lidem postavil.
{117007}{117051}Dávejte na sebe pozor.|- Na shledanou.
{117203}{117284}Strıèku Koone,|nechala mi jen tenhle dopis.
{117287}{117373}Proè by odjídìla v takovém spìchu?|- Moná to bylo naléhavé.
{117376}{117446}Dìkuju, u pùjdu. Mìjte se.|- Taky.
{117568}{117597}Dobøe, pùjdu já.
{117612}{117684}Dej mi tu sekeru.|- Doufejme, e to vyjde.
{117687}{117722}Buï milı.
{117725}{117826}Promiòte. Bratøe, potøebuji|léky, ale zaplatil bych pozdìji?
{117829}{117876}Je mi líto, ale takové vìci nedìláme.
{117879}{117923}Ale je v sázce lidskı ivot.
{117926}{117959}Nejsme èervenı køí.
{117962}{118051}Kdyby kadı byl jako vy,|tak brzy zkrachujeme.
{118054}{118087}Dejte mu je.|- Jistì.
{118090}{118197}Ale stejnì chci vìdìt,| co jste zaè a co jsem vám provedl.
{118211}{118284}Moná jsem omylem|nìkdy zatkl vaše pøátele.
{118340}{118433}Wane, musím jít.|Klidnì mi to napiš na úèet.
{118467}{118516}Pøíteli.|- Pøíteli.
{118536}{118624}A co je vašemu kolegovi?|- Horkost a zimnice.
{118627}{118687}Coe?|- To bude asi tyfus.
{118816}{118847}Buï potichu!
{118920}{118957}Strıèku Koone, uteète!
{118960}{119035}Teï kdy máte zatykaè,|nikdo vás nemùe otravovat.
{119038}{119079}Tudy, pane.
{119102}{119161}Rozejdìte se.|- Tohle je policejní akce.
{119181}{119210}Tady je.
{119213}{119258}Sehnal?|- Jasnì, podívejte.
{119261}{119342}A taky jsem potkal Draka Ma.|- A zabil jsi ho?
{119345}{119404}Ne, koupil mi ty léky.
{119478}{119524}Všichni jsou nahoøe.
{119636}{119667}Strıèku Koone, vy první.
{119670}{119709}Uvidím se pozdìji.|- Vem si to.
{119712}{119735}Jdeme.
{119738}{119792}To je Drak Ma.|- Jak to, e ještì ije?
{120116}{120161}Na, vezmi to.|- Buï opatrnı.
{120321}{120356}Jdeme.
{120685}{120758}Pane Chun, je nìco v nepoøádku?|- Ne, je to jen zatıkání.
{120761}{120867}Ale slyšeli jsme støelbu.|- Do toho vám nic není, zmizte.
{120874}{120898}Dìlejte!
{120901}{120940}Vypadnìte.
{121038}{121072}Uteè!
{121462}{121517}Draku Ma, zabiju tì.
{121676}{121756}Pohyb.|- Zrychli.
{121954}{122015}Myslím, e o tohle vám celou dobu jde.
{122018}{122065}Chune, co to sakra dìláte?
{122068}{122165}Víte co, vy máte svoje|problémy a já zase svoje.
{122168}{122250}Dìkuju. To je ono.
{122253}{122301}Yan-kite, proè si nás zradil?
{122304}{122345}Ty hajzle!
{122410}{122508}No a? S radostí plním|svoje poslání pozatıkat rebely.
{122511}{122547}Co chcete?
{122586}{122621}Chune.|- Ano, pane.
{122638}{122681}Vaše odmìna.|- Dìkuju, pane.
{122684}{122752}A co s ostatníma?|- Vezmu si je sebou.
{122755}{122819}Krabice jsou pøipraveny, pane.|- Do pekla s tebou, Chune!
{122858}{122934}Øíkal jsi nìco?|- Víš co to dìláš?
{122957}{123047}Co mi navrhuješ?|- Tohle ti neprojde.
{123077}{123125}Neboj, ale projde.
{123128}{123222}A co máš proti mì?|Byl jsi proti mì u od zaèátku.
{123225}{123323}Nic osobního,|ale pleteš se mi poøád pod nohy.
{123326}{123364}A zatıkal jsi mé mue.
{123367}{123468}Èím déle tì nechám it,|tím více problémù mi zpùsobíš.
{123471}{123533}Dìlal jsem jen|svoji práci jako policista.
{123536}{123655}Jsi dobrej polda a já|špatnej, nikdy bysme se neshodli.
{123658}{123745}Je to buï já nebo ty.|Chápeš?
{123748}{123847}To staèí.|Nehodlám tu poslouchat vaše báchorky.
{123850}{123939}Máte pravdu. Radìji|jdìte ne zaènou veèerní trhy.
{123942}{123991}Ale chci, aby tenhle chlap zmizel.
{123994}{124089}Samozøejmì, postarám se|o nìj jen co odejdete.
{124111}{124159}Postarejte.|- Jdeme.
{124205}{124242}Pomoc!|- Maggie.
{124245}{124292}Sklapni!|- Ona o nièem neví.
{124295}{124376}Zapomeòte na ní.|Pro vás mám v plánu nìco speciálního.
{124379}{124443}Vemte ho pryè.|- Ano, pane. Pohyb!
{124468}{124511}Pohni!|- Dost!
{124752}{124791}Hoïte ho dovnitø.
{124955}{125012}Jdìte pomoct ostatním.|- Ano, pane.
{125032}{125082}Yan-kite, zapni to.
{125133}{125264}Zapomeò, e by ses|dostal ven. Je to nemoné.
{125516}{125585}Tahle várka Sojovky bude znamenitá.
{125601}{125707}Naše spoleènost je proslavena|svoji sojovou omáèkou, kterou exportuje.
{125710}{125839}Tvoje kùe a krev bude|v kadé láhvi poslané za moøe.
{125842}{125899}No není to nádhera? Co?
{126233}{126268}Zatím si vedeš dobøe.
{126557}{126628}Uvidíme jak dlouho ti to vydrí.
{126702}{126771}Myslím, e bysme mìli pøidat trochu oleje.
{127111}{127162}A ještì trošku sem.
{128058}{128100}Utekl!|- Za ním!
{128346}{128379}Bì!
{128455}{128506}Vemte mu ten zápisník.
{128509}{128568}Rychle, honem. Po schodech!
{128645}{128693}Co je?|- Je to slepı.
{128696}{128734}Rychle, tudy.
{129161}{129195}Pospìšte! Tudy.
{129207}{129255}Honem!
{129403}{129467}Rychle!|- Pohnìte.
{129473}{129516}Nenechte je utéct.
{129719}{129756}Musíš slézt dolù.
{129780}{129836}Je to v pohodì. Neboj se.|- Ne.
{129853}{129895}Pouijeme košík.
{129933}{129975}Pojï.|- Vydr.
{129988}{130033}Zopakuj to po mì. Já pùjdu první.
{130243}{130279}Dole tì chytím.
{130641}{130691}Tak, skoè!
{130918}{130986}U je to dobré. Mùeš slézt.|- Rychle!
{131055}{131089}Tudy.
{131212}{131290}Rychle, ale opatrnì.
{131393}{131454}Honem! Pomoz jí.
{131510}{131540}Pomoc!
{131700}{131771}Zkus se zachytit nohou ...
{131783}{131819}Podej mi ruku.
{131822}{131868}Nepøibliuj se.
{132038}{132074}Dr se pevnì!
{132281}{132364}Skoè, chytím tì.|Ne. poèkejte chvíli, seenu prkno.
{132449}{132502}A teï skoè!
{132690}{132755}Pus se!
{132979}{133048}Vezmi si ten zápisník.|- Ty si ho vem. Já to nezvládnu.
{133051}{133099}Vem si ho a uteè.
{133124}{133161}My se odsud nedostaneme.
{133188}{133219}Dobøe.|- Bì!
{133229}{133272}Pohlídejte ty dvì.
{133525}{133571}Zablokujte vıchod.
{133813}{133854}Drak Ma?!
{134051}{134097}Dej nám ten zápisník.|- Snìdl jsem ho.
{134100}{134207}Vra nám ho a mùeš jít.|- Kdybych chtìl utéct, tak u jsem pryè.
{134210}{134245}Dost kecù.
{134394}{134484}Dáme ti ještì jednu šanci.|- Ne dík. Nepotøebuju.
{134527}{134556}Chyte ho!
{134580}{134617}Docela mi padne.|- Jdeme.
{134620}{134661}Jak vypadám?|- Jdeme.
{135242}{135272}Tak dìlej.
{135786}{135833}Štìstí je na mojí stranì.
{137846}{137881}Vezmeme ten notes.
{137965}{138001}Máš ho?
{138431}{138475}Co to dìláte?
{138478}{138519}Proè ho mlátíte?
{139368}{139401}Za ním!
{139564}{139592}Bì tamtudy.
{140586}{140622}Vra se!
{141838}{141903}Jdìte mu zablokovat cestu pryè.|- Ano, pane.
{142673}{142717}Drak Ma není náš pøítel.
{142732}{142802}Ale sáhnìte na nìj jen|prstem a pøijdete o nìj.
{142805}{142832}Tak jest.
{143379}{143427}Nebojte postarám se o to.
{143445}{143503}Šéfe, pan Chun má situaci pod kontrolou.
{143506}{143536}Poèkat!
{143610}{143662}To je dozorèí.|- Parchanti!
{143698}{143745}Promiòte, mám ještì schùzku.
{144599}{144651}Z cesty!
{145524}{145552}Poèkej, Chune!
{145577}{145610}Tady máš svoje peníze.
{145673}{145767}Netahejte za ten provaz.|Nebo to celé spadne.
{146043}{146131}Pozor, padá to.|Všichni z cesty!
{146477}{146517}Ujistìte se, e je Drak v poøádku.
{146761}{146808}Díky, milosrdnı boe.
{146811}{146837}Je v poøádku!
{146840}{146889}Chun je pod tím!
{146979}{147028}Propuste mé mue.|- Proè?
{147041}{147101}Jsem vládní zástupce.
{147104}{147168}Moji mui jednali v sebeobranì.
{147171}{147229}Musíte je nechat jít.
{147368}{147400}Co jste øíkal?
{147442}{147493}Slyšeli jste nìco?|{y:i}- Ne, pane.
{147496}{147558}Vy jste nìco slyšeli?|- Ne nic.
{147561}{147604}Myslel jsem si to.
{147635}{147709}Draku, jsi v poøádku?|- Ano.
{147712}{147745}A vy jste skonèil!
{147801}{147839}Nechte je jít.
{147900}{147954}Dìkujeme.|- Netøeba, dluím vám to.
{147957}{148009}Draku, o co tu jde?
{148012}{148055}Draku Ma.
{148140}{148223}Pamatujete proè jsme tady?|- Jasnì.
{148226}{148290}Mrtvej. Jdeme.
{148427}{148491}Draku, co jsou zaè?|- Jen pár pøátel.
{148494}{148578}es nás nepøedstavil.|- Neznám je jménem.
{148581}{148615}Rozchod!
{148660}{148709}Rozchod!
{148800}{149000}Èeské titulky Frogg 7.2005|{y:i}Pøeklad na asijskou verzi (cca 1:46)