{83}{141}Chlapec má právo sníva.
{163}{230}Rozprestierajú sa pred ním|nekoneèné monosti.
{251}{354}Èo ho oèakáva na ceste, ktorú|si vyberie?
{371}{408}To chlapec nevie.
{434}{510}Skôr, ako sa to dozvie, chlapec|dospeje...
{515}{590}...a zistí, kto sa z neho|za ten èas stal.
{601}{660}Sprevádza to rados i smútok.
{695}{838}Keï sa to stane, rozlúèi sa|v srdci so svojou minulosou?
{868}{963}A chlapec raz dospeje,|u sa nemôe znovu sta chlapcom.
{979}{1041}Z chlapca je teraz mu.
{1075}{1128}Mono poveda len jedno:
{1138}{1200}Chlapec má právo sníva.
{1212}{1287}Rozprestierajú sa pred ním|nekoneèné monosti.
{1317}{1410}Všetci mui boli kedysi chlapcami.
{2757}{2800}|BillSK & Pedro uvádzajú:
{2817}{2933}|OUTLAW STAR: Svet túob. 
{2950}{3025}|Produkcia: BillSK
{3025}{3100}|Slovenské titulky: Pedro (pedro_k@post.sk)
{3100}{3175}|Spracovanie videa: Randy
{3175}{3275}|Nie je urèené pre komerèné pouitie.
{3997}{4049}Soidei bei...
{4139}{4178}Našla som ich.
{4180}{4209}Poïme.
{4426}{4475}G-Gene...
{4517}{4590}Èo je, do èerta, toto?
{4620}{4676}Prebieha kontrola resuscitaèného|systému.
{4703}{4753}Kto je to?
{4758}{4790}Melfina.
{4794}{4811}Melfina?
{4813}{4919}System normálny. Odhadovanı|èas resuscitácie, 600 sekúnd.
{4920}{4967}Zaèína odpoèítavanie.
{4987}{5002}Tri.
{5008}{5025}Dva.
{5028}{5050}Jeden. 
{5085}{5150}Resuscitácia za 600 sekúnd.
{5155}{5230}Resuscitácia? Je v studenom|spánku?
{5279}{5314}O èo sa to pokúšaš?
{5323}{5457}Ak sa chceš dozvedie o Melfine,|oprav mi ruku a ja ti to poviem.
{5475}{5510}Kybernetická protéza?
{5511}{5572}Tak preto si si objednala|tie súèiastky...!
{5575}{5662}Myslím, e si neuvedomuješ,|v akej si situácii, Hilda.
{5708}{5761}Ak chceš vystreli, tak do toho.
{5771}{5870}Ale ak to urobíš, budeš prenasledovanı|tımi pirátmi...
{5874}{5940}...a ani nebudeš vedie kto som.
{6025}{6086}Jim, oprav Hilde ruku.
{6118}{6153}Nestoj tam len tak.
{6160}{6227}Odovzdaj tú zbraò, èo máš.
{6232}{6261}Fajn.
{6263}{6298}To by mohlo by zaujímavé.
{6303}{6332}Mono, e aj bude.
{6351}{6406}Gene, nemôeme jej veri ani|trochu!
{6408}{6431}Veï neverím.
{6435}{6510}Keï vravíš. Ja len, e eny|a vdy privedú do problémov.
{6512}{6535}To urèite!
{6538}{6646}Ale skôr, ne jej opravíš ruku,|priprav sa na spoloènos a schovaj auto.
{6648}{6670}Jasné.
{6706}{6785}Toto je NanoPrometheus špièkovej|kvality!
{6858}{6921}Dobre teda. Kto, do pekla, si?
{6927}{6977}Volám sa Hilda. Som Outlaw.
{6982}{7091}Dokonca aj tu na Sentineli, si hocikto|aj so svojím psom hovorí, e je Outlaw.
{7102}{7153}Povedz nám, kto naozaj si.
{7158}{7205}Nie je to niè zvláštne, naozaj.
{7215}{7298}Som Outlaw, ktorá sa dostala|do urèitıch problémov s tımi pirátmi...
{7304}{7359}...keï som išla po istom poklade,|a utiekla na túto planétu.
{7363}{7392}Prišla si z vesmíru?
{7395}{7414}Hej.
{7419}{7448}V svojej vlastnej lodi?
{7454}{7549}Nechala som svoju loï na orbite.|Prišla som dole v module.
{7574}{7663}No a preèo je to dievèa pokladom,|za ktorım sa enú tí piráti?
{7667}{7701}Kto vie?
{7707}{7798}Chceli ju, tak som im ju uchmatla.
{7800}{7836}Iste.
{7838}{7890}A to by ma malo ako presvedèi, e?
{7899}{7976}Problémy medzi nami sa nezaèali|a vtedy.
{7979}{8038}Máme zlú minulos.
{8053}{8086}Skús s tım pohnú.
{8135}{8184}Rád by som si ešte nieèo o|tom vypoèul.
{8188}{8242}Potrebujem dôvod, aby som|nemala rada pirátov?
{8248}{8317}Ale piráti majú dôvod, aby|nemali radi teba, je tak?
{8324}{8410}Odpravila som jedného z vodcov|Gildy.
{8414}{8458}Stálo ma to dos.
{8460}{8480}Hotovo.
{8551}{8630}Ak mi nedáš priamu odpoveï,|bude a to stá ešte viac.
{8631}{8692}Kvôli èomu má to dievèa takú|ve¾kú cenu?
{8706}{8778}Resuscitácia za 360 sekúnd.
{8798}{8858}Keï sa zobudí, spıtaj sa jej|sám.
{8866}{8928}Take ty sa chceš ïalej hra|na blbú, èo?
{8950}{8971}Piráti?
{8974}{8997}Zhasnite svetlá!
{9106}{9178}Vieme, e ste tam!
{9181}{9209}Vydajte Melfinu!
{9211}{9246}Mal som tušenie, e sa ukáu...
{9248}{9319}Nebudem vás iada o pomoc,|len sa mi drte z cesty!
{9323}{9377}Teraz je u na to trochu neskoro!
{9380}{9408}Gene!
{9416}{9485}Resuscitácia za 300 sekúnd.
{9501}{9569}Musíme zosta naive,|a kım sa Melfina nezobudí.
{9575}{9610}Jim, daj mi náboj è. 3.
{9611}{9630}Došli nám.
{9636}{9666}Nemohli nám dôjs!
{9677}{9730}S normálnymi nábojmi sa mi|toho deda nepodarí zloi!
{9755}{9822}Máme len jeden è. 5 a jeden è. 19.
{9826}{9899}Èíslo 5 a 19, èo...?|Dobre teda, daj mi ich.
{9927}{9961}Sú drahé, vieš o tom?
{9983}{10039}Dokáete vy dvaja vydra|15 minút?
{10042}{10064}Èoe?
{10077}{10140}Pokım prebieha resuscitácia,|nemono s Melfinou hıba.
{10157}{10209}Ale ak tu zostaneme, sme màtvi.
{10214}{10340}Ak by ste ich dokázali zdra,|môem privola svoj modul.
{10347}{10412}Chce akurát utiec. Never|jej, Gene.
{10415}{10461}Teda, niè z toho nedáva zmysel...
{10465}{10527}Okej, Jim, choï s òou.
{10548}{10574}Ja?
{10577}{10630}Ak sa pokúsi zdrhnú, tak|nech to o¾utuje.
{10643}{10706}Kruci, ja som mal by mozgom|tejto akcie...
{10710}{10784}Prestaò márni èas. Dajme|sa do toho!
{10787}{10812}Jasné.
{11010}{11034}Choïte!
{11137}{11170}Ja si s tım poradím.
{11313}{11338}Kde je to?!
{11341}{11374}Potopila som ho v rybníku!
{11417}{11441}Sprav to rıchlo!
{11502}{11547}Máš rád Geneho?
{11569}{11610}Kadı potrebuje partnera.
{11643}{11682}Pochopíš u èoskoro. 
{11762}{11806}Feng leiiku!
{11819}{11868}Oh, do prèíc... Ten chlap|je Tao majster?
{11887}{11918}Feiga!
{12056}{12087}Stará mágia?
{12089}{12124}Tu na okraji hraníc?
{12127}{12227}Není špatné na è. 5... Take|mi u zostáva len è. 19.
{12239}{12269}Èas prevzia iniciatívu...
{12277}{12325}Dedo, hra skonèila!
{12472}{12503}Náboj zlyhal!
{12553}{12580}Oh, sakra...
{12617}{12672}Choïte! Zabite všetkıch okrem|Melfiny!
{12842}{12866}Hilda?
{12867}{12906}Je to príliš nebezpeèné! Preskupte sa!
{13059}{13092}Tomu sa vraví masaker...
{13107}{13155}Resuscitácia ukonèená. Resuscitácia|ukonèená.
{13163}{13190}Prebieha aktivácia.
{13700}{13819}Pod¾a Hviezdneho kalendára 156:|Bol zaloenı Projekt Leyline.
{13867}{13897}Melfina...?
{14167}{14277}Preèo? Preèo som sa musela|narodi?
{14304}{14384}Gene! Teraz nie je èas necha|sleènu plaka.
{14387}{14405}To nie kvôli mne!
{14407}{14457}Gene, vezmi Melfinu preè!
{14460}{14492}Hilda nás pôjde vyzdvihnú.
{14498}{14518}Rozumiem.
{14521}{14584}Ale najprv treba tuto pre|Spiacu Krásavicu zohna nejaké šaty.
{14587}{14620}Hej, je to trochu rozpty¾ujúce.
{14663}{14701}Ste tam dole pripravení? Poïme|teda!
{14703}{14725}Okej!
{14727}{14770}Zdá sa, e vy dvaja u spolu|vychádzate.
{14779}{14814}Dosiahli sme porozumenie.
{14932}{14959}Snaia sa ujs?
{14980}{15008}Za tou loïou!
{15087}{15107}Hıbte sa!
{15369}{15393}Kruci!
{15569}{15688}Èert a ber, Hilda... Nemysli si,|e pred Gildou uteèieš!
{15714}{15776}Opúšam orbit a potom opúšam|aj tento systém.
{15778}{15818}Tak ako? Chcete ís so mnou?
{15820}{15879}Presne tak! Veï sme ešte nedostali|naše peniaze!
{15883}{15911}Však, Gene?
{15962}{15999}Èo je s ním?
{16004}{16050}Gene má hrôzu z vesmíru.
{16051}{16082}Vôbec nemám!
{16086}{16150}Prvı krát to bolo akurát príliš|skoro, to je všetko.
{16205}{16238}Si ale srandovnı.
{16241}{16324}Vydr, Gene! Chytím a za ruku!
{16327}{16391}Nie, vïaka. Mimochodom, preferujem|skôr eny.
{17213}{17294}Horus, vyber najkratšiu trasu|k asteroidu Modré Nebo.
{17296}{17319}Rozumiem.
{17321}{17347}Modré Nebo?
{17356}{17426}Slobodné mesto. Navštevujú|ho Outlaws.
{17432}{17497}Horus sa tam dostane na dva|skoky.
{17559}{17620}Desa sekúnd do sub-éterového|letu.
{17626}{17646}Devä.
{17648}{17666}Osem.
{17672}{17693}Sedem.
{17697}{17716}Šes.
{17721}{17748}-Pä. -U to preskoè, hej?
{17748}{17762}-Štyri. -U to preskoè, hej?
{17768}{17786}Tri.
{17792}{17810}Dva.
{17816}{17835}Jeden.
{17845}{17866}Štart.
{18255}{18325}Zvládol som u celé ovládanie, otec!
{18800}{18821}Otec!
{18825}{18859}Chcem, aby si il, Gene!
{18871}{18895}Otec!
{18927}{18950}Ve¾a šastia.
{19093}{19170}OTEC!
{19288}{19316}Ja...
{19369}{19398}U si hore?
{19404}{19433}Je v tom problém?
{19516}{19578}Nie, ak dokáeš by ticho.
{19584}{19635}Vstúpili sme do priestoru|Modrého Neba.
{19807}{19866}Prístup k sieti Modrého Neba|ukonèenı.
{19867}{19922}Teraz zobrazujem pouite¾né|doky.
{19955}{19993}Poui dok 8.
{19995}{20047}Dok 8, rozumiem.
{20050}{20140}Pripravujem pristátie na Modré|Nebo cez trasu 2-2-1.
{20220}{20266}Prepínam na reim autopilota.
{20270}{20286}Tri.
{20290}{20303}Dva.
{20309}{20326}Jeden.
{20335}{20374}Teraz riadi autopilot.
{20376}{20439}Gene, máš strach z vesmíru?
{20445}{20474}Nie, vôbec nie.
{20475}{20509}Tak èo je to?
{20517}{20565}Len isté zlé spomienky, to|je všetko.
{20572}{20607}Spomienky, hm?
{20609}{20696}Hilda, u si vo vesmíre dlho?
{20707}{20782}Dlho. Mono.
{20786}{20838}Zase si taká, znovu uhıbaš|pred mojími otázkami...
{20858}{20906}Hej, zobudil si sa, Gene?
{20931}{20963}Rád a vidím ivého.
{20966}{20993}Padaj.
{20995}{21037}Ah, to je ale roztomilé!
{21041}{21078}Ja ti ukáem "roztomilé"!
{21880}{21912}Si v poriadku, Gene?
{21938}{21966}Hej.
{22017}{22080}Raz mi u nebude vadi vnútrajšok|kozmickej lode.
{22084}{22132}Myslím, e tvoj strach sa|teraz oficiálne prejavil.
{22134}{22216}Sklapni, lebo ti jednu prejavím|po hube.
{22221}{22308}Hilda! Ako dlho je to u?|Môeš sa zdra na chví¾u?
{22311}{22392}Teraz nie. Potrebujem, aby|si zásobil a opravil Horus.
{22396}{22431}Iste. Len to nechaj na mòa.
{22445}{22521}Pozri, Gene! To je Corbonit!|iadneho som ešte nikdy nevidel!
{22523}{22546}Ani ja.
{22548}{22626}Kto sú zaè? Robíš teraz turistickú|sprievodkyòu?
{22651}{22698}Povedzme, e hej.
{22752}{22775}Dobre.
{22779}{22840}Po pravde, mám pre teba odkaz, ale...
{22854}{22888}To je okej. Môeš mi to poveda tu.
{22891}{22934}McCoy vraví, e to nemôe|spravi.
{22936}{22952}Preèo nie?
{22955}{23048}Neviem naisto. Vyzeralo to,|e si to nechce rozhádza u pirátov.
{23051}{23094}Ten sra¾o.
{23096}{23138}A mám ešte jednu zlú správu.
{23141}{23212}Bratia MacDougallovci sa na|teba pıtali.
{23215}{23245}Prekliata svorka hyen...
{23248}{23266}Hej!
{23269}{23318}"McCoy" sem, "MacDougall"|tam...
{23319}{23366}Kedy zaènete, ¾udia, vravie|nieèo zmysluplné?!
{23383}{23457}Neple sa do rozhovoru dospelıch,|diea.
{23463}{23489}Diea?
{23497}{23519}Èoe?
{23523}{23657}Hej, ak sa necháš všetkım|len tak vytoèi, tak dlho nevydríš, diea.
{23691}{23791}Pouíva tieto veci je tu|zakázané. Pamätaj si, diea.
{23806}{23891}K¾ud, nie je nabitá. Len som|blafoval.
{23893}{23973}Take strie¾a zo zbrane je|v slobodnom meste zakázané?
{23979}{24094}Hej. Ak by zblúdená gu¾ka|prerazila stenu a unikol by vzduch...
{24097}{24165}...kadı, kto tu ije by to|u mal za sebou.
{24167}{24260}Hlupáci, èo sa nevedia riadi|pravidlami nemajú právo tu ïalej i.
{24265}{24347}Alebo tie, e tu ijú iba|hlupáci, èo sa riadia pravidlami.
{24361}{24399}Take toto znamená by Outlaws, ha?
{24405}{24442}Sú to piráti?
{24453}{24536}Zdá sa, e ani tento tu mládenec|neporozumel.
{24539}{24591}Vo vesmíre existujú tri sily:
{24594}{24650}Vesmírne jednotky, Piráti|a Outlaws.
{24652}{24713}Rozdiel je v tom, èo ich motivuje.
{24716}{24795}To, èo motivuje Outlaw, závisí|od konkrétneho èloveka.
{24798}{24881}Dobro alebo zlo, to nevplıva|na ich solidaritu a zmysel pre povinnos.
{24885}{24930}Take toto z nich robí Outlaws...
{24933}{25017}Pozri sa na toto, Swanzo!|To nebude práca pre jedného!
{25019}{25073}Do èerta... V poriadku, hneï|tam budem!
{25077}{25109}Hilda, tak sa teda maj.
{25112}{25142}Iste. Dobre sa oòho postaraj.
{25148}{25190}Èau, decká.
{25244}{25279}Ja nejdem.
{25295}{25372}Jak to, e ja musím ís nakupova šaty?
{25374}{25414}Ona ide s tebou, nie?
{25416}{25506}Musím kamsi ís a Melfina|potrebuje obleèenie.
{25510}{25558}Bola by som radšej, keby si|s òou šiel ty.
{25560}{25618}Melfina je dôleité dievèa.
{25622}{25651}To viem.
{25657}{25776}A èo takto teda? Ja pôjdem|s tebou a Jim pôjde s Melfinou?
{25780}{25826}U iadne vıhovorky.
{25837}{25859}Platí.
{25866}{25895}Platí.
{25915}{25978}Stretneme sa potom v hoteli.|Okej, Jim?
{25980}{26004}Dobre.
{26064}{26119}Vitajte v Modrom Nebi.
{26340}{26410}Pristúpte, pristúpte! Mám|vynikajúce mäsové pirohy!
{26411}{26458}Pristúpte!
{26478}{26505}Prepáè, Jim.
{26510}{26545}S tım sa netráp.
{26762}{26797}Tak ako?
{26844}{26882}Èo myslíš?
{26914}{26955}Vyzerá to úasne!
{26957}{26994}Hej, nie je to zlé!
{27028}{27054}Vïaka.
{27211}{27263}Tak, èo teraz?
{27271}{27333}Tu sa stretávajú Outlaws.
{27349}{27415}Keby som zistila, e je tu niekto|aspoò spolovice poriadny, najala by|som ho.
{27417}{27473}Take to nie je práca, s ktorou|by si si poradila sama...
{27494}{27582}Mono by si mi mohla poveda,|èo je to za prácu.
{27663}{27691}V poriadku.
{27733}{27784}Idem si vyzdvihnú istú loï.
{27823}{27854}Istú loï?
{27861}{27900}Špeciálnu loï.
{27907}{28025}Grappler loï s dostatkom energie,|aby sa dostala do Ether Sargasso.
{28043}{28103}Grappler loï?
{28110}{28226}Ak plánuješ ís tie, porozmıš¾aj nad tım.
{28247}{28320}Ale zdá sa, akoby si nemal rád vesmír.
{28322}{28354}Staraj so o svoje veci.
{28356}{28417}Hej. Ty si Hilda?
{28423}{28486}Poèul som, e máš nedostatok ¾udí.
{28490}{28537}Vypomôeme ti, ak chceš.
{28544}{28582}McCoy, ty bastard...
{28587}{28653}Prepáè. H¾adám len ¾udí, s urèitımi schopnosami.
{28655}{28698}Je ich tu plno!
{28703}{28776}Hovoríme tu o tom, ako zarobi|trochu peòazí, nie? Nebuï taká lakomá!
{28778}{28818}My, Outlaws, sme všetci partneri, pravda?
{28820}{28846}Partneri?
{28847}{28906}Prišla si sem, pretoe h¾adáš|partnerov, však, Hilda?
{28907}{28969}Pravda, Hilda?
{28987}{29019}Au!
{29114}{29146}Take tak!
{29150}{29194}Chceš si nieèo zaèa, bastard?
{29264}{29294}Sleduj toto.
{29346}{29373}Chceš schyta, hej?
{29375}{29443}Nebudeme a šetri len preto, e si ena!
{29708}{29750}Nabudúce nebudem taká dobrá.
{29752}{29800}Stiahnite chvost a uteète.
{29806}{29879}Ksakru, to si zapamätáme!
{29931}{29988}Chlapi, ako títo, sú tie Outlaws?
{29990}{30099}Je to tak ako s hviezdami:|niektoré sú jasné a iné matné.
{30101}{30145}A ty si aká?
{30148}{30186}Rozhodni sám.
{30191}{30238}Chceš to zisti?
{30345}{30392}Gene a Hilda majú spoloènú izbu?!
{30394}{30411}Áno, pane.
{30413}{30460}Sakra, ten podliak...
{30462}{30509}Hádam si s òou nechce nieèo zaèa...
{30520}{30577}Jak je moné, e ona s tım súhlasila?
{30578}{30638}Nie, stavím sa, e on pod¾ahol zvádzaniu.
{30639}{30695}K¾úè od vašej izby, pane.
{30697}{30721}Našej izby?
{30723}{30795}Áno, pane. Izba 345. Dvojposte¾ová.
{30863}{30894}No, poèula si...
{30979}{31067}Kruci, Gene... teraz nie je|èas ani miesto na takéto veci.
{31099}{31142}Ako to vyzerá?
{31146}{31188}Myslím, e nie zle.
{31219}{31270}Dnes v noci budeme spa tu?
{31272}{31290}Hej.
{31291}{31312}Spolu?
{31322}{31377}Uh... V-vezmi si tú poste¾ tamto! Tamtú poste¾!
{31379}{31403}Áno.
{32146}{32172}Je prázdna!
{32247}{32295}Chlapi z baru?
{32303}{32364}S tebou sa èlovek ani chví¾u nenudí, však?
{32366}{32413}Na niè iné nie je ani èas.
{32415}{32441}Buï v strehu.
{32453}{32522}Èo sa deje tam hore? Dostali ste ich?
{32533}{32558}Sakra!
{32580}{32629}Poïme. Nepouívaj pišto¾.
{32912}{32978}Ale, no tak! Ani proti tomuto|nemôem poui pišto¾?
{32979}{33031}Nie. Ani on nemá iadnu.
{33066}{33093}To fakt?
{35455}{35502}Stratil som svoj strach z vesmíru!
{35511}{35576}Teraz títo vesmírni piráti nemajú šancu!
{35585}{35640}Alebo tak som si pomyslel,|keï som si našiel trochu èasu...
{35647}{35740}Pred našimi vesmírnymi hrdinami|sa objavuje nová hrozba!
{35749}{35874}Ale, preèo to musia by zrovna|tí brutálni Ctarl-Ctarl?!
{35876}{35913}Situácia speje od zlého k horšiemu!
{35934}{36044}Nabudúce v Outlaw Star!|"Do horiaceho vesmíru"
{36046}{36108}Radšej sa pripravte!
