{63}{130}Toto mladé dievèa vyrastalo na slnku.
{142}{212}Necítila niè, len potešenie, e môe by|na svojom mieste pod slnkom.
{227}{344}Toto dievèa, narodené v hrdej, vznešenej|rodine, obklopené láskou,
{352}{448}so cou absolvovalo základnú, strednú i vyššiu|školu.
{471}{579}Prvı krát zaclonil tieò jej slnkom zaliate|miesteèko...
{591}{650}...keï skladala skúšky na najvyššej akademickej|inštitúcii v krajine.
{664}{737}Nepromova medzi najlepšími by nebolo niè|hrozné,
{742}{835}ale v jej krajine, kde hodnos hrala ve¾kú|rolu, to znamenalo ve¾a.
{854}{940}Pôsobisko pre tıch, ktorí promovali so cou,|bol vesmír.
{944}{1027}Bola vyhnaná zo svojho miesta na slnku.
{1041}{1119}Dôstojníèka Aisha Clanclan z Impéria Ctarl-Ctarl.
{1125}{1219}U nikdy sa jej nevráti potešenie z jej miesta|na slnku.
{1276}{1346}NEMÔE TO SKONÈI TAKTO!

{2757}{2800}|BillSK & Pedro uvádzajú:
{2817}{2933}|OUTLAW STAR: Dievèa-šelma, pripravená zaútoèi!.
{2950}{3025}|Produkcia: BillSK
{3025}{3100}|Slovenské titulky: Pedro (pedro_k@post.sk)
{3100}{3175}|Spracovanie videa: Randy
{3175}{3275}|Nie je urèené pre komerèné pouitie.

{3651}{3684}Si tam, Swanzo?
{3686}{3759}Mikey, nevravel som ti, aby si mi sem nevolal?
{3761}{3797}Sorry, je to naliehavé.
{3798}{3855}Pamätáš na tıch ¾udí, èo boli vtedy s Hildou?
{3857}{3900}Oh, máš na mysli tie decká?
{3902}{3942}iadajú o povolenie pristá.
{3944}{3995}Chcú, aby sme nieèo spravili v riadiacej|miestnosti.
{4004}{4074}Ako to? Horus by nemal ma iadne problémy|s pristávaním.
{4083}{4109}Kde je Hilda?
{4113}{4164}Tá loï nie je Horus.
{4175}{4242}A nezdá sa, e by Hilda bola s nimi.
{4259}{4301}Hilda s nimi nie je?
{4513}{4573}Nemôem tomu uveri... Hilda je màtva?
{4575}{4639}Je to tak, èi tomu veríte alebo nie.
{4642}{4699}Táto loï je všetko, èo zostalo.
{4708}{4746}Ah, take tak.
{4778}{4833}Tak, synu, èo chceš robi teraz?
{4839}{4913}Neviem. Vôbec nechápem o èo tu ide.
{4921}{5037}Hilda, piráti, Galaktickı Leyline, MacDougall...
{5045}{5106}Myslím, e zaènem tım, e sa to pokúsim zisti.
{5108}{5145}Iste. Ale buï opatrnı.
{5147}{5183}Zaujímalo by ma, èi by ste mi mohli spravi|slubu.
{5185}{5207}Èo?
{5208}{5300}Tuto Outlaw Star nemá registraèné èíslo,
{5303}{5353}take nemôeme vstúpi do legitímnych prístavov.
{5355}{5437}Loï nie je ešte vybavená. Sakra, veï nemá|ani náter.
{5449}{5519}Chápem o èo ti ide. Take, máš nejaké peniaze?
{5523}{5563}Sorry, ale nemám u seba niè.
{5575}{5619}My tu nepracujeme len tak zdarma.
{5630}{5668}Èo povieš, keï zaplatím, a sa mi podarí|nieèo ve¾ké?
{5670}{5700}Nieèo ve¾ké?
{5710}{5766}Vyzerá snáï na to alebo èo?
{5777}{5803}Platí.
{5821}{5858}To myslíš váne, Swanzo?!
{5860}{5897}Dlím to Hilde.
{5901}{5925}Eeh...
{5931}{5953}Prepáète...
{5955}{5975}Èo je?!
{5977}{6029}Chıba nám aj mnoho inıch vecí.
{6033}{6079}Môe síce lieta, ale to je všetko.
{6086}{6141}Potrebujeme tie zbrane a muníciu.
{6146}{6242}Registraèné èíslo a náter budú mojou splátkou|za to, èo dlhujem Hilde.
{6269}{6374}Avšak, tu nezoeniete zbrane pre Grappler|loï.
{6385}{6482}Ïalej, chlapèe, je u na tebe, aby sa ti|podarilo nieèo ve¾ké.
{6497}{6547}Jasné, rozumiem. Je tu ešte jedna vec.
{6549}{6578}Èo takého?!
{6591}{6633}Povedzte mi, èo viete.
{6635}{6721}O Hilde a o tejto lodi. A o pirátoch a MacDougallovi.
{6767}{6868}Pred piatimi rokmi ma Hilda zachránila, keï|ma napadli piráti Ban.
{6875}{6914}Vtedy sme sa prvı krát stretli.
{6916}{7001}Všetko, èo viem o jej minulosti sú len dohady.
{7006}{7084}To isté platí aj o Galaktickom Leyline, ktorı|h¾adala.
{7086}{7138}Take, vy dvaja ste spolu vychádzali fajn,|e?
{7141}{7241}Fajn? Bolo to dos horúce, pokia¾ ide o mòa.
{7243}{7297}Pre "Horúcu ¾adovú" Hildu, tie.
{7306}{7332}Horúca ¾adová?
{7334}{7373}Prezıvka Hildy.
{7386}{7505}Nerozprávala príliš ve¾a o sebe. Nech bolo|akoko¾vek horúco.
{7509}{7615}Po Hilde pátrali piráti Kei. To je všetko,|èo viem.
{7619}{7651}A MacDougall?
{7655}{7744}Ten chlap je profík v zahladzovaní stôp.|Neviem o òom vôbec niè.
{7771}{7865}To mi vyhovuje. Som loveckı pes, ktorı stopuje|pod¾a pachu.
{7868}{7930}Je tu jedna vec, ktorú by si mal vedie.
{7943}{8002}Poneviera sa tu nejaká ena z Ctarl-Ctarl
{8005}{8094}a snaí sa zisti kam šli Horus a Hilda.
{8097}{8153}Ctarl-Ctarl?! Urèite je z tej lode!
{8157}{8214}Tá ich bojová loï u odišla.
{8218}{8272}No, radšej sa pustíme do práce.
{8283}{8348}Zatia¾ sa choï porozhliadnu po meste.
{8354}{8382}Ïakujem.
{8384}{8411}To niè.
{8413}{8466}Mimochodom, Gene, aká je tvoja ob¾úbená farba?
{8488}{8551}Musíš rozhodnú akou farbou má by natretı|trup.
{8565}{8612}- Myslím, e táto farba.|- Jasné.
{8614}{8678}Gilliam, sna sa zatia¾ slušne správa.
{8683}{8721}V poriadku.
{8978}{9021}Hej, vzchop sa!
{9023}{9055}Len ju nechaj tak, Jim.
{9078}{9117}Poèkaj, Gene, ja som len--
{9119}{9224}Nevie o sebe vôbec niè. Preèo by mala cíti|smútok?
{9226}{9246}Ale...
{9247}{9274}To je v poriadku.
{9286}{9352}Ja tie cítim smútok.
{9368}{9455}Hilda ma zachránila.
{9474}{9566}Smútok? Take, chceš poveda, e cítiš smútok?
{9567}{9638}Vraví, e sa tak cíti, a to staèí, Gene!
{9639}{9673}Si len rozèúlenı.
{9680}{9714}Rozèúlenı?
{9989}{10014}Mono.
{10084}{10191}Take, nespomínaš si na niè, èo sa stalo|predtım, ne a Hilda zachránila?
{10193}{10206}Nie.
{10207}{10238}Kruci.
{10249}{10323}No, ak si na nieèo spomenieš, na hocièo,|povedz nám.
{10325}{10344}Áno.
{10346}{10449}Mimochodom, Gene, u si prekonal tú svoju|vesmírnu fóbiu?
{10451}{10480}Nie som si istı...
{10490}{10559}Ešte stále sa mi nejak ako dıcha...
{10579}{10605}Nikdy to neprekonám!
{10606}{10707}Teda, je zázrak, e si sem dokázal dopilotova|Outlaw Star.
{10721}{10755}S tou loïou je to iné.
{10758}{10844}Jak to vysvetli...? Akosi sa tam necítim|takı stiesnenı.
{10846}{10905}To je tım Fyzickım Navigaènım Systémom.
{10961}{11035}Eeh... Tak ty si pamätáš tie veci o tej lodi?
{11037}{11129}Ja... ani sama neviem preèo.
{11203}{11298}No tak, no tak, poïme si nájs nieèo dobré|na jedenie! Mám hlad!
{11301}{11341}Hej, máš pravdu. Poïme!
{11343}{11386}Èo by si si zajedla, Melfina?
{11390}{11417}Ja sa prispôsobím.
{11419}{11474}Stojte, kde ste.
{11527}{11588}Èakala som a èakala, a u viac èaka nebudem...
{11597}{11642}Kto si?
{11653}{11694}Kde je Hilda?
{11699}{11740}Poznáš Hildu?
{11742}{11786}Ja tu kladiem otázky.
{11787}{11861}Odpovedz mi. Kde je Hilda?
{11864}{11958}Take ïalšia namyslená sleèinka tu predvádza|svoj vıstup?
{11960}{11988}Ako sa voláš?
{11990}{12064}Ja som... Aisha Clanclan!
{12076}{12113}Ona je Ctarl-Ctarl!
{12131}{12163}Tak, ty si...
{12164}{12247}Viem u, e pracuješ s Hildou.
{12255}{12303}Povedz mi, kde je Hilda!
{12312}{12418}Pozri, mrzí ma to malé nedorozumenie. Ponáh¾ali|sme sa.
{12421}{12461}Vaša loï nebola poškodená, pravda?
{12474}{12519}Bol to môj koniec!
{12525}{12600}Odpovedz mi... Kde je Hilda?!
{12606}{12634}Je màtva.
{12641}{12668}Èoe?!
{12676}{12753}No, tvoja otázka je zodpovedaná. Maj sa!
{12759}{12805}S-stoj!
{12850}{12907}Povedz mi súradnice Galaktického Leyline!
{12909}{12967}Keïe si pracoval s Hildou, mal by si to|vedie!
{12974}{13016}Galaktickı Leyline...?
{13053}{13089}Tak to by si chcela vedie...
{13091}{13129}Povedz mi!
{13141}{13174}Iste.
{13184}{13210}Poèúvaš?
{13256}{13317}TO BY SOM AJ JA RÁD VEDEL!
{13343}{13396}Krucinál! Prestaò si robi srandu!
{13401}{13443}Fakt! Naozaj nevieme!
{13445}{13503}Take sa chcete hra na blbıch a do úplného|konca, rozumiem...
{13507}{13570}Potom teda vytiahnem z teba odpoveï nasilu.
{13574}{13655}Hej, prestaò! Nechcem sa bi s dievèaom!
{13659}{13707}-Mono na to nevyzerám, ale... -Zbytoèné|reèi!
{13713}{13749}V tom prípade...
{13755}{13781}UTEKAJME!
{13792}{13831}Zbabelci!
{13898}{13922}Gene!
{13930}{13952}Ksakru!
{13971}{13992}Pozor!
{14177}{14253}Je to zlé, Gene! Bojuješ s Ctarl-Ctarl!
{14711}{14736}Celkom dobré.
{14753}{14855}Ctarl-Ctarl, èo? Správate sa len ako priemerní|zabijáci!
{14876}{14947}A ty sa len tak vyberieš a pustíš sa do boja|so mnou...
{15058}{15095}Èoe--?
{15104}{15218}Ukáem ti skutoènú hrôzu Ctarl-Ctarl...
{15537}{15578}Èo to robí?
{15590}{15688}U viem! Ctarl-Ctarl vedia metamorfova!
{15690}{15707}Metamorfova?
{15709}{15765}Zmenia sa na nejaké naozaj zúrivé zviera!
{15767}{15807}Komu hovoríš zviera?!
{15809}{15904}Len sleduj silu, ktorú som zdedila po svojich|predkoch!
{15939}{15975}Je to zlé, Gene...!
{15979}{16090}Táto forma, dokáe rozdrvi obyèajného èloveka|a je zvyèajne ovládaná vô¾ou!
{16096}{16197}Túto silu zosilòujú fázy mesiaca planéty!
{16256}{16309}Modré Nebo nemá mesiac.
{16371}{16421}Keï na to tak myslím, nemá...
{16431}{16474}Teraz! Bete!
{16491}{16534}Hej! Vráte sa!
{16590}{16616}Stojte!
{16661}{16682}Gene!
{16687}{16720}Vráte sa!
{16728}{16770}Jim! Choï kúpi nejaké náboje!
{16774}{16802}Èo? Náboje?
{16807}{16840}Náboje do Casteru!
{16842}{16926}Stojte! Vráte sa!
{17054}{17119}Náboje? Pochybujem, e sa tu nachádzajú nejaké|náboje...
{17121}{17145}Èo mám robi...?
{17597}{17643}Zdá sa, e sme sa jej stratili.
{17820}{17854}Si v poriadku?
{17873}{17920}Tamto je lavièka.
{18193}{18253}Mono to nikdy neprekonám...
{18462}{18527}Èo je? Ešte nikdy si nevidela kvety?
{18529}{18565}Sú umelé.
{18589}{18674}Tieto kvety boli vyrobené. Tak ako ja.
{18739}{18816}Preèo som bola vytvorená?
{18831}{18889}Kım? Kvôli èomu?
{18921}{18956}Ja...
{18994}{19039}Kto som?
{19319}{19386}Ešte nikdy predtım som nevidel androida ako|si ty.
{19387}{19480}Aj keï sa a takto dotknem, neviem a odlíši|od èloveka.
{19495}{19609}Ješ. Cítiš smútok. Trápiš sa nad vlastnou|existenciou.
{19645}{19739}Hilda by mi mohla da odpoveï, ale teraz|je preè.
{19886}{19943}A-Au! To bolí!
{19945}{19978}Prestaò, prosím!
{19997}{20085}Dokáeš by prekvapená. A cítiš boles.|A sauješ sa. 
{20139}{20230}Stavím sa, e by som mohol preh¾ada galaxiu|a predsa by som nenašiel nikoho ako si ty.
{20232}{20300}Jedného dòa nájdem pre teba odpoveï.
{20317}{20432}Je to teraz moja zodpovednos... Hildine|ciele a ty.
{20434}{20458}Ja?
{20463}{20558}Vyrieši nejakú tú záhadu navyše niè nezmení.
{20575}{20646}Zistím to kvôli tebe. Objavím tvoju minulos.
{20672}{20745}Ale po pravde, nemáme jedinú stopu, po ktorej|sa vyda.
{20751}{20858}Spıta sa pirátov by bolo najrıchlejšie,|ale radšej by som zjedol hovno...
{20869}{20908}Tie tak uvaujem. 
{20917}{20958}Radšej zjes hovno, ha?
{20963}{21007}Nie! Teda...
{21019}{21042}Áno.
{21089}{21208}Melfina, bude to dlhá cesta, ale pôjdeš|s nami?
{21245}{21306}Ak nebudem príliš na obtia...
{21312}{21352}Vôbec nebudeš na obtia!
{21359}{21471}Aj tak, bez teba by bolo lietanie s Outlaw|Star ve¾kım utrpením.
{21481}{21508}Áno!
{21525}{21564}Fajn, take dohodnuté!
{21583}{21605}Jim!
{21609}{21666}Poèuješ ma, Jim? Kde si?
{21671}{21745}Niekde, kde zrejme nemajú iadne náboje.
{21751}{21826}Zdá sa, e sme sa jej zbavili. Stretneme|sa znovu na tom rohu.
{21831}{21848}Okej.
{21879}{21924}Èo je? Èo sa deje, Gene?!
{21929}{21978}Buï dobrı chlapèek a vzdaj sa.
{21985}{22015}Sakra, ty si ale neodbytná!
{22017}{22043}Ticho!
{22081}{22105}Ustúp, Mel!
{22753}{22793}Z èoho tá tvoja koa je?!
{22794}{22845}To bola len polovièná sila.
{22846}{22929}Myslím, e ti ukáem ako vyzerá naša celková|beštiálna sila...
{23263}{23349}Asi som spálila prive¾a kalórií...
{23691}{23774}Take a tu zanechali na Modrom Nebi, kvôli|tomu, èo sa stalo.
{23781}{23879}Mám titul miestna zastupite¾ka!
{23888}{23944}Ale nedostávaš plat, e?
{23947}{23998}Jednoducho nedostávam od impéria iadne peniaze.
{24067}{24126}Keï som pouila vlastné peniaze aby som vás|vystopovala,
{24127}{24176}bola som zakrátko švorc!
{24188}{24266}Keï nedáme pozor, zje nám tie všetko naše|jedlo.
{24355}{24411}Toto je vynikajúce! Ochutnaj!
{24413}{24441}Vïaka.
{24593}{24645}Teda, ty si fakt paravá...
{24647}{24700}Z toho by sa najedli štyria ¾udia...
{24702}{24734}Um...
{24738}{24764}Èo?
{24766}{24822}Chcem ïalšie!
{24869}{24904}Poslú si...
{24908}{24958}Ïalšie! Ïalšie!
{24960}{25027}Mimochodom, my nevieme niè.
{25034}{25098}Nemáme iadne informácie, ktoré by ti mohli|by uitoèné.
{25241}{25282}Je to chutné!
{25284}{25349}Všake, všake? Ja si dám tie!
{25439}{25499}Som plná! U by som nezjedla ani kúsok!
{25511}{25585}Ponúkol som sa, e ti kúpim jedlo, lebo som|sa cítil trochu vinnı.
{25591}{25621}Teraz sme si kvit!
{25828}{25866}Èo robíš?
{25917}{25992}Blbec! Vy Pozemšania ste takí tupí!
{25996}{26099}Takımto biednym odškodnením si nezmierite|Ctarl-Ctarl!
{26122}{26182}"Zmieri"? Tak, pozeraj...
{26186}{26298}Hrdım Ctarl-Ctarl nezáleí na nepriate¾ovom|súcite!
{26306}{26407}Myslím, e tvoje správanie nie je v poriadku...
{26415}{26443}Ticho!
{26447}{26498}Netvrï mi, e niè neviete!
{26503}{26583}V mene Impéria Ctarl-Ctarl vás zatıkam!
{26594}{26638}Ak sa vám na tom nieèo nepáèi...
{26641}{26691}Znova sa chceš zmeni na zviera?
{26697}{26744}Komu hovoríš zviera?!
{26792}{26887}Keï sa transformujem, moja sila staèí, aby|som vás roztrhala na kusy!
{26889}{26967}Teraz mám energie viac ne dos, aby som|vyuila všetku svoju beštiálnu silu!
{26971}{27018}A komu za to môeš poïakova?
{27028}{27084}Neoèakávaj iadnu vïaènos.
{27088}{27174}Myslíš, e to na nás Ctarl-Ctarl, platí?
{27187}{27264}Teda, títo Ctarl-Ctarl sú èosi iné...
{27269}{27305}Poui toto, Gene.
{27316}{27331}Našiel si nejakı?
{27333}{27399}Hej, èíslo 12. Ten chlap ma ošlklbal,|e by si neveril, ale choï na to.
{27401}{27442}Súhlasím s tım.
{27462}{27494}Vedel som, e to dokáeš, partner!
{27554}{27671}Snáï si nemyslíš, e tá zbraò bude pôsobi|na nesmrte¾nıch Ctarl-Ctarl...
{27691}{27734}Naozaj?
{27912}{27970}Hej, tak toto je pod¾a teba nesmrte¾ná Ctarl-Ctarl...
{28034}{28097}Èašník, dajte všetko na jej úèet.
{28104}{28170}Povedala, e je tu miestnou zastupite¾kou|Ctarl-Ctarl.
{28182}{28221}Nedovo¾te, aby sa z toho vyvliekla!
{28411}{28451}Úasné!
{28466}{28501}Pekné!
{28556}{28612}Takisto som získal pre loï registraèné èíslo.
{28622}{28673}Povedal som ho palubnému poèítaèu.
{28678}{28777}Èo je s tım starım poèítaèom? Tá prekliata|vec nie je nikdy ticho!
{28790}{28848}Viem, èo myslíš, ale my s tım niè nenarobíme.
{28850}{28895}Je integrovanı s loïou.
{28902}{29016}Prepáète, ale nebola to nepriama uráka?
{29018}{29058}Sekaj dobrotu, krucinál!
{29060}{29118}Oh, nie. Spôsobuje mi to starosti, oh¾adne|mojej budúcnosti...
{29119}{29145}Sklapni!
{29152}{29209}Cením si vašu pomoc, Swanzo, Mikey.
{29218}{29272}Tak, èo mieniš robi teraz?
{29287}{29342}Zatia¾ sa vrátime na Sentinel III.
{29350}{29398}Èo potom, to je vo hviezdach.
{29478}{29571}Teritórium pirátov Kei, ktorí prenasledovali|Hildu,
{29572}{29639}je v skutoènosti tu nablízku, v Tempa Empire.
{29647}{29733}Oblas v ktorej sa nachádzame je v teritóriu|pirátov Ban.
{29741}{29835}Títo Kei zrejme neurobia niè drastické,
{29854}{29934}ale dávajte si pozor, keï vyjdete z Heifongu.
{29937}{29956}Jasné.
{29958}{30017}Èo chceš robi na Sentineli III?
{30022}{30107}Vyuijem konexie, aby som získal vybavenie|a zbrane, ktoré nám chıbajú.
{30120}{30189}Gene, snáï nie on...!
{30191}{30232}Máme snáï na vıber?
{30236}{30329}Obchodník na Sentineli III? Myslíš on?|Fred Luo?
{30336}{30369}U ste o òom poèuli?
{30377}{30458}Mal som nejaké dobré obchody s jeho otcom.
{30467}{30562}Prijmem jedno akı horúci obchod Fredom!
{30564}{30614}No tak, no tak, Gene!
{30616}{30710}Hej, on nepatrí medzi tıch zlıch. Èo ti na|tom nesedí, James?
{30736}{30810}Vïaka za pomoc. Mono ju budeme niekedy opä|potrebova.
{30812}{30859}Keï bude treba, ozveme sa.
{30860}{30954}Nech to vyjde! U mám dos tej práce zadarmo.
{30956}{31018}Na, harukuru suna n'n!
{31034}{31069}To je korbonézsky?
{31070}{31133}Oh, prepáète. "Šastnú cestu".
{31143}{31191}Jasné. Vïaka.
{31376}{31481}Riadiaca miestnos, tu je Outlaw Star.|Opúšame prístav!
{31483}{31577}Máte povolenie. Navádzací signál potvrdenı.
{31581}{31667}Pôjdeme pod¾a majákov, pokım neopustíme oblas|Modrého Neba.
{31695}{31746}Fred Luo...?
{31766}{31818}Je naozaj a takı zlı?
{31830}{31915}Ty sa nemusíš nièoho bá, Melfina.|Ty si dievèa.
{31922}{31972}Má nejaké problémy s mumi?
{31978}{32025}To bude okej! To bude okej!
{32038}{32085}Neboj!
{32132}{32186}Zabudni na to! Kdee!
{32188}{32242}Nikdy! Nikdy! Nikdy!
{32251}{32323}Poïme! Outlaw Star, štart!
{32522}{32609}Sakra! Ako to, e jedna z hrdıch Ctarl-Ctarl...
{32617}{32698}...je nútená zníi sa k takejto podradnej|práci?!
{32704}{32802}Za to mi zaplatíš, Pozemšan! Pamätaj|na moje slová!
{32807}{32870}Hej! Prestaò sa fláka!
{32872}{32916}Naspä do práce, darmoráèka!
{32918}{32958}Á-áno, pane!
{33038}{33096}Toto si zapamätám!
{35343}{35449}Krásna atentátnièka Suzuka prenasleduje môjho|starého priate¾a Freda Luo!
{35454}{35549}Odloil som nabok svoje zásady správania|sa k peknım dámam...
{35553}{35662}...a riskujem ivot, aby som ochránil svoj|vzácny zdroj peòazí -- eh, priate¾a!
{35673}{35745}Ale krásnu enu je ve¾ká škoda odstráni!
{35749}{35868}Nabudúce v Outlaw Star!|"Krásna atentátnièka"!
{35875}{35929}Radšej sa pripravte!
