{149}{268}Svet Toward Star, kde sa Gene nachádza,|je pustı.
{303}{393}Na samom okraji hraníc, ïaleko|od centrálnych oblastí,
{395}{434}súperia o nadvládu štyri ve¾ké pirátske skupiny.
{455}{557}A práve jedna z tıchto štyroch h¾adá|Outlaw Star a Melfinu.
{567}{644}Piráti zo systému Hoppo, zvaní Stoosem Hviezd,
{654}{758}sú najbrutálnejším èlenom Èínskej gildy.
{852}{993}Vedie ich Tendo a pozostávajú z desa|alebo dvadsa-èlennıch skupín.
{1039}{1120}Vodcovia tıchto skupín riadia|nezávislé organizácie...
{1124}{1181}...a sledujú svoje vlastné ciele.
{1227}{1353}Šéf pirátov, ktorí teraz prenasledujú Geneho|sa volá Hazanko.
{1374}{1454}Má medzi Stoôsmimi Hviezdami ve¾kı vplyv,
{1463}{1535}ale kvôli rozsahu jeho moci, jeho organizácie,
{1537}{1600}a úèinnosti metód, ktoré pouíva|na dosiahnutie svojich cie¾ov...
{1610}{1679}...hovorí sa, e ostatní vodcovia ho povaujú|za svojho predstaveného.
{1710}{1772}Hovorí sa tie, e oddiely,|ktoré vykonávajú jeho rozkazy...
{1775}{1838}...pouívajú super silu zvanú senjutsu,
{1846}{1945}a vdy zlikvidujú tıch,|ktorí sa proti nim postavia.
{2757}{2800}|BillSK & Pedro uvádzajú:
{2817}{2933}|OUTLAW STAR: Plíiace sa zlo. 
{2950}{3025}|Produkcia: BillSK
{3025}{3100}|Slovenské titulky: Pedro (pedro_k@post.sk)
{3100}{3175}|Spracovanie videa: Randy
{3175}{3275}|Nie je urèené pre komerèné pouitie.
{4364}{4398}Si pripravenı, Gilliam?
{4399}{4425}Všetko je okej.
{4430}{4454}Fajn...
{4466}{4509}Zapínam všetky senzorové systémy.
{4534}{4568}CFS, aktivované.
{4598}{4642}Podpriestorovı radar, aktivovanı.
{4657}{4715}Všetky senzory fungujú normálne.
{4731}{4785}Systém éterového pohonu, aktivovanı.
{4795}{4846}Systém kontroly gravitácie, aktivovanı.
{4863}{4919}Systém subéterového pohonu, aktivovanı.
{4943}{5028}Aktivácia navigaèného systému potvrdená.|Všetky systémy v poriadku.
{5041}{5094}Jednotka gravitaèného cyklu, aktivovaná.
{5095}{5136}Najprv ide Newtonov reaktor.
{5138}{5158}Kruci!
{5179}{5228}Newtonov reaktor sa teraz aktivuje.
{5248}{5295}Sub reaktor 1, funguje.
{5307}{5330}Èíslo 2, funguje.
{5347}{5385}Èíslo 3, chyba.
{5387}{5400}Èoe?!
{5402}{5429}Vıkon klesá.
{5432}{5450}70.
{5454}{5514}- 50. 30. - Uh... Èo mám vlastne robi?
{5516}{5577}Spusti u zvyšnıch reaktorov vyrovnanie energie.
{5585}{5611}Tımto, e?
{5613}{5665}Reaktory 2 a 4, vıkon stúpa.
{5671}{5691}120.
{5696}{5716}130.
{5722}{5742}140.
{5748}{5770}160.
{5775}{5794}180.
{5802}{5841}Chystajú sa explodova.
{5856}{5877}Èo?!
{5888}{5938}T-mínus-10 do kritického stavu.
{5949}{5966}Devä.
{5970}{5988}Osem.
{5994}{6011}Sedem.
{6012}{6047}- Šes.|- Hej, Gilliam...!
{6049}{6062}Pä.
{6069}{6083}Štyri.
{6090}{6108}Tri.
{6115}{6134}Dva.
{6140}{6156}Jedna.
{6400}{6456}Ako vidím, ïalší neúspešnı vzlet.
{6462}{6503}To ty si to dokazil!
{6505}{6552}Kadı jeden mizernı krát sa dostanem do problémov!
{6555}{6650}Úèelom simulácií je príprava na neoèakávané situácie.
{6669}{6766}Ak nie si schopnı manuálne zvládnu|takıto malı problém,
{6771}{6836}zrejme na nejakı èas nemono poèíta s odletom.
{6871}{6895}Sklapni!
{7116}{7190}Nu, loï nie je ešte kompletne vybavená,
{7208}{7261}preto myslím, e sa netreba náhli.
{7436}{7465}Take...
{7471}{7527}Zdá sa, e by som sa mal do toho pusti.
{8092}{8118}Vitaj doma!
{8123}{8150}Je nieèo nového?
{8151}{8180}Nie, vôbec niè.
{8206}{8221}Kde je Jim?
{8223}{8247}Na policajnej stanici.
{8261}{8286}Na policajnej stanici?
{8292}{8357}Áno. Pravdepodobne odtiahli jeho auto.
{8358}{8390}Ehefrau, èo?
{8400}{8434}Tak to vravel.
{8469}{8530}Takéto nieèo sa v Locuste nestáva moc èasto.
{8597}{8686}Nepáèi sa mi to. Deje sa nieèo podozrivé...
{8739}{8790}Gene! Našiel som ju! Našiel som ju!
{8792}{8822}Je v bezpeèí a v poriadku!
{8836}{8933}Ehefrau, u a nikdy znovu neopustím, fakt...
{8964}{9002}Aj tak sa mi to nepáèi...
{9104}{9163}Vraveli, e sa nazbierala príliš ve¾a|parkovacích tiketov.
{9167}{9213}Snail som sa, jak sa len dalo,|aby som vymyslel nejakú vıhovorku.
{9219}{9285}-Mal si im jednoducho poveda, e nás napadli piráti.|-Kdee! Nikdy by mi neuverili.
{9348}{9474}Neveril by si, na ko¾ko vyšla pokuta a odtiahnutie.
{9767}{9790}Èo to bude?
{9791}{9860}Gene! Vy dvaja ešte ijete?
{9869}{9920}Tie a rád vidím, Clyde.
{9927}{10015}Poèul som, e šli po tebe piráti,|tak som si pomyslel...
{10017}{10039}Gene!
{10070}{10105}Som tak rada!
{10117}{10154}Èo je, veï sa niè nestalo.
{10164}{10207}Tak som sa o teba strachovala!
{10212}{10307}Rozprávaš tak roztomilo... Fajn, fajn dievèa.
{10314}{10361}Daj dole ruku z jej zadku.
{10378}{10427}Èo si robil? Sú to u dva tıdne!
{10430}{10483}Je to dlhı príbeh, take ti ho nepoviem.
{10495}{10518}Si takı zlı!
{10547}{10585}A toto je kto?
{10602}{10659}Melfina. Nová priate¾ka.
{10696}{10725}Iris!
{10727}{10756}Áno!
{10875}{10951}Clyde, pıtal sa na nás niekto?
{10961}{10993}Otázky, ktoré by sa nemal pıta?
{10995}{11103}Boli tu nejakí po tej roztrke vtedy,|ale niè neobvyklé.
{11135}{11167}Váne sa mi to nepáèi.
{11171}{11207}Èo a trápi?
{11213}{11240}To niè.
{11364}{11483}Zdá sa to by tak dávno, ale nie sú to ešte|ani dva tıdne...
{11510}{11561}Tak, èo teraz?
{11576}{11647}Zvyšok kontajnerov od Freda by mal prís zajtra.
{11668}{11734}Musíme da Outlaw Star do perfektného|prevádzkového stavu.
{11735}{11774}To by bolo fajn, ale...
{11784}{11807}Èo ale?
{11814}{11857}Po pravde, sme švorc.
{11860}{11903}Èo vravíš?! Ale èo náš úèet?
{11911}{11954}U sme ho takmer celı vyèerpali.
{11972}{12020}Poplatky za pouívanie kozmodrómu sú fakt mastné.
{12030}{12055}Kruci!
{12063}{12120}Po prvé! Zarob peniaze akım spôsobom.
{12127}{12183}Nezostal by mi èas pracova na Outlaw Star.
{12193}{12235}Po druhé! Zarob peniaze ¾ahkım spôsobom.
{12242}{12302}Clyde! Nevyskytli sa posledne nejaké ve¾ké odmeny?
{12307}{12401}Nie, odkedy si zloil "Smrtiaceho" Roba.
{12426}{12470}Po tretie! Zarob peniaze slizkım spôsobom.
{12471}{12491}Ako?
{12506}{12540}Predávaj svoje telo alebo tak nejak.
{12542}{12576}-Tvoje by sa predávalo lepšie.|-Tretia monos teda odpadá.
{12623}{12666}Po štvrté! Poièa si!
{12676}{12723}-Od koho? -Neviem.
{12725}{12769}Ja tu úvery neposkytujem.
{12905}{12955}Take to bude teda prvá monos, e?
{12962}{12998}A èo s Outlaw Star?
{13007}{13111}To nechám na teba. Ja zatia¾ zoeniem pre|nás nieèo na ivobytie.
{13123}{13154}Ja teda neviem...
{13155}{13178}Um...
{13195}{13258}Ak by som mohla nieèo urobi, povedz mi, prosím.
{13285}{13322}Vieš aspoò uvari vajcia?
{13355}{13453}Ja... nikdy predtım som nevarila.
{13469}{13544}-Tak sa nauèíš. Melfina, budeš ma slubu v kuchyni.|-Áno.
{13670}{13730}Hej, niè nie je také upokojujúce ako mesto,|v ktorom si si navykol i...
{13733}{13778}Hej, hej, tie myslím...
{13796}{13873}Ale èoskoro odídeme.
{13906}{13933}To je fakt...
{13935}{14037}Kam pôjdeme? Ako ïaleko pôjdeme...?
{14083}{14177}Je fajn díva sa do neba, ale pozerajme|kam kráèame, hej?
{14187}{14226}Od zajtra to bude aké.
{14238}{14278}Hej, ja viem.
{14965}{15016}Èo je? Nemôeš spa?
{15025}{15045}Nie.
{15059}{15171}Stavím sa, e si praješ, aby bio-androidi|nemuseli by takí ¾udskı, e?
{15177}{15205}Máš pravdu.
{15288}{15357}Eeh, vôbec nièomu tu nerozumiem...
{15414}{15472}Dovo¾ mi takto zosta, a kım nezaspím.
{15490}{15631}Keï som takto, mám pocit, e tie dokáem sníva.
{16053}{16109}Èo si myslíš, e robíš, ty chlípnik?
{16123}{16225}Ja, uh... len som si pomyslel,|e sa pozriem aká ¾udská naozaj je.
{16238}{16285}Aká je ¾udská?
{16311}{16369}Mel je ¾udskejšia ne èlovek.
{16417}{16438}Jim!
{16458}{16512}Je pre mòa ako mama...
{16843}{16962}Kryty motorov nie sú regulérnymi dielmi,|tak ich prosím, všetky vymeòte.
{16966}{17008}Èo takto trochu pomôc, ha?
{17016}{17090}Keby sme boli v nulovej gravitácii, poradil|by som si s akou prácou,
{17096}{17179}ale pri tejto gravitácii som bezmocnı.
{17189}{17231}Tak pracuj na interiéri!
{17234}{17273}Pracujem, samozrejme.
{17368}{17421}Prosím, skontrolujte si to neskôr.
{17431}{17462}Jasné, jasné...
{17471}{17502}Pán Starwind!
{17517}{17537}Èo je?
{17542}{17603}Musíme sa porozpráva. Môte prís do kancelárie?
{17647}{17677}Vedel som to...
{17687}{17721}Poèkajte chví¾u.
{17767}{17866}Keï to zaène vrie, zníte teplotu. Varte,|kım to nie je uvarené.
{18046}{18082}Tá vec je kaput!
{18124}{18222}Musím tam da novı motor alebo skoro všade|kúpi nové súèiastky.
{18230}{18286}Keby som mal to¾ko peòazí,|vzal by som to k predajcovi.
{18291}{18323}Áno, pane! Rozumiem!
{18325}{18431}Toto je èas, kedy nastupuje firma|Starwind and Hawking!
{18444}{18515}V skutoènosti, zrovna takıto motor akurát máme.
{18523}{18577}Samozrejme, budeme si úètova ove¾a menej|ne nejakı predajca!
{18580}{18647}Vedel som to! Vedel som, e s vami môem ráta!
{18662}{18690}To si píšte!
{18742}{18830}Myslím, e som vás iadal, aby ste zaplatili|všetky parkovacie poplatky vopred!
{18848}{18933}Ak sa tu chcete chví¾u zdra, musíte za|to tie zaplati.
{18942}{18999}Zaplatili sme vám za ïalšie tri dni, nie?
{19015}{19075}Vidím, e ste nezaplatili za povolenie odštartova.
{19082}{19134}Zaplatíme vám kadı nedoplatok, okej?
{19146}{19188}Ako dlho sa tu zdríte?
{19194}{19248}Nie som si istı. Porozmıš¾am...
{19628}{19685}Upozornenie! Toto nie je kapitán!
{19723}{19742}Gene!
{19745}{19771}Gilliam! Èo je?
{19773}{19796}Je to narušite¾!
{19979}{20013}Vitaj doma!
{20457}{20498}Gilliam! Kde je narušite¾?!
{20512}{20562}Uniká vıahom è. 2!
{20943}{20966}Gene! Nad tebou!
{21061}{21097}Bastard! Vrá sa naspä!
{21798}{21853}Prišla som navštívi Geneho Starwinda,|a èoe tu nájdem?
{21870}{21951}Ve¾mi zaujímaví ¾udia sa ho pokúšajú zabi...
{22035}{22083}Patríš medzi pirátov Kei?
{22123}{22155}Nemiešaj sa.
{22170}{22198}Moja reè.
{22209}{22293}Gene Starwind je moja koris.
{22326}{22354}Choï nabok.
{22368}{22392}A-Áno.
{22411}{22478}Poviem to znovu. Nemiešaj sa.
{22500}{22614}V tom prípade, bude to skvelá príleitos|spravi Geneho mojím dlníkom.
{22993}{23033}Koneène som sa trochu odreagoval.
{23043}{23094}Trochu si ubral z ostraitosti.
{23111}{23159}Nie je tak, pán Pirát?
{23187}{23223}Kde je Hilda?
{23284}{23362}Nechápeš v akej si kaši, e, kámo?
{23394}{23422}Váne?
{23595}{23678}Odpovedz mi. Èo je s Hildou?
{23686}{23721}Niè nepoviem!
{24474}{24523}Vidím, e si majster senjutsu.
{24543}{24598}Aj ty máš urèité zaujímavé techniky.
{24607}{24645}Len som sa zahrievala.
{24664}{24742}Nikto ešte nevidel viac ako|tri moje tajné techniky.
{24780}{24833}Súmrak ešte nenastal.
{24849}{24910}Ko¾ko ich uvidíš, skôr ako zomrieš?
{24926}{24971}Budeš to ty, kto zomrie.
{26379}{26437}Poïme na to! Hagan-raggo!
{26848}{26882}Èo to bolo?
{26899}{26955}Štandardnı Hi'en, varianta è. 1.
{27002}{27039}Iste.
{27154}{27187}U je to v poriadku.
{27199}{27244}Uh. Um...
{27272}{27338}Môem poèka na Geneho v jeho obchode?
{27357}{27378}Áno.
{27611}{27674}Zdá sa, e je màtvy.
{27711}{27786}Chcel som sa ho nieèo spıta, ale zdá sa,|e nebolo na vıber.
{27919}{27945}Èo--?
{28512}{28529}Bastard!
{28636}{28716}Mám na teba pár otázok.
{28737}{28793}Budeš poslúcha a odpovieš mi?
{28801}{28874}Moja ob¾úbená farba je èervená.|Moje šastné èíslo je jedna.
{28902}{28941}Kde je Hilda?
{28950}{29017}Preèo ste sa ty a tvoji priatelia vrátili|na Sentinel sami?
{29026}{29109}Èo sa stalo s mojimi ¾uïmi? Odpovedz mi!
{29130}{29163}Èo za to, keï ti to poviem?
{29193}{29242}Doprajem ti rıchlu smr.
{29269}{29322}Musíš mi da lepšiu ponuku.
{29335}{29393}To záleí na tvojej odpovedi.
{29395}{29450}Èo to tu mohlo na poli vybuchnú?
{29451}{29506}Neviem! Preto nám povedali,|aby sme to šli skontrolova!
{29558}{29576}To bol vıstrel!
{29582}{29602}Tamto!
{29624}{29693}Vezmeme si XGP naspä! S tım poèítaj!
{29755}{29774}Zavolajte posily!
{29777}{29796}Jasné!
{30187}{30212}Boli tam nejakı svedkovia?
{30214}{30291}Nie, nikto tu nie je. Majú strach|sa do toho zamieša.
{30298}{30355}Keby šlo o pirátov, myslím,|e by som spravil to isté.
{30553}{30610}M-Mel! Èo sa, do èerta, stalo?!
{30646}{30672}Vitaj spä!
{30697}{30790}T-Ty si u prišla? Si tu kvôli nemu?
{30804}{30838}Kde je Gene?
{30851}{30899}Hej, to ti tak poviem.
{30903}{30972}Je v tvojom najlepšom záujme sa s ním|èo najskôr stretnú.
{30984}{31059}Vypadá to, e po vás idú piráti Kei.
{31064}{31095}P-Piráti?!
{31106}{31169}Suzuka ma zachránila.
{31187}{31226}P-Preèo?
{31251}{31315}Pretoe sa zdáte by celkom zaujímaví.
{31486}{31523}Gilliam, otváraj!
{31529}{31614}Ah, Jim. Mali sme tu trable. Napadli nás piráti.
{31621}{31667}Tu tie? Kde je Gene?
{31672}{31716}Vnútri, pracuje.
{31728}{31766}Kadopádne, pusti nás dnu.
{31769}{31810}Istee. Ale...
{31812}{31835}Èo také?
{31858}{31915}A èo bude s tou mladou dámou?
{31927}{31991}Nie je zaregistrovaná ako èlen posádky.
{32100}{32142}Pusti ju zatia¾ dnu.
{32361}{32382}Gene!
{32387}{32444}Boli tu piráti, ja viem.
{32446}{32474}Èo budeme robi?
{32483}{32578}Naloíme všetko vybavenie, èo pôjde|a odletíme, len èo sa bude da.
{32582}{32671}Vysvetlil by si mi, èo sa to tu deje?
{32718}{32822}Ak budete bojova s pirátmi Kei,|nebude mi vadi, keï vám pomôem.
{32855}{32908}Momentálne nám nezostáva niè, len s nimi bojova.
{32931}{33014}Avšak nepoznám pravı dôvod...
{33042}{33084}...preèo po nás idú.
{33095}{33118}Gene?
{33163}{33216}Gene! Èo sa deje?
{33227}{33248}Gene!
{33409}{33458}È-Èo ksakru?
{33515}{33610}Ošetril som si to, ale myslím, e nie poriadne.
{33689}{33725}GENE!
{36093}{36117}Au!
{36131}{36194}Krucinál, ja som hviezda tohto seriálu!|Toto sa nemalo sta!
{36201}{36282}Je to zlé! Je to a príliš moc vzrušujúce,|nemyslíte?
{36292}{36423}A ja idem hore do vesmíru po prvı krát...|Bez pomoci.
{36434}{36497}Ak to zbabrem, bude to koniec tohto seriálu?!
{36512}{36614}Nabudúce v Outlaw Star!|"Vynútenı odchod"!
{36622}{36673}Radšej sa pripravte!
