{71}{171}Gene Starwind. Èo h¾adáš?
{180}{215}Kde sa nachádza objekt tvojej túby?
{225}{260}Èo a uspokojí?
{280}{396}Gene Starwind, budeš i alebo tu zomrieš?
{412}{450}Rozhodnutie je na tebe.
{459}{503}Len jedna vec je v ivote istá!
{509}{571}Ver v seba a vytváraj si svoj vlastnı osud!
{577}{677}Neboj sa neúspechu! Nemáš èo strati.
{684}{732}By mladı znamená nadobúda veci.
{754}{842}Tebe sa dostala do vlastníctva|Outlaw Star a Melfina.
{860}{919}Jedinou otázkou akurát je, ako ich pouiješ.
{936}{1047}Choï nájs Galaktickı Leyline!|Nikto a nedokáe zastavi.
{1060}{1100}Oèakáva a dobrodrustvo!
{1117}{1167}Teraz by si to u mal chápa.
{1181}{1249}Gene Starwind, èas sa kráti!
{1256}{1319}Otvor oèi, vykríkni, a choï vpred!
{1340}{1459}Gene Starwind, toto je zaèiatok tvojho príbehu!
{2757}{2800}|BillSK & Pedro uvádzajú:
{2817}{2933}|OUTLAW STAR: Vynútenı odchod. 
{2950}{3025}|Produkcia: BillSK
{3025}{3100}|Slovenské titulky: Pedro (pedro_k@post.sk)
{3100}{3175}|Spracovanie videa: Randy
{3175}{3275}|Nie je urèené pre komerèné pouitie.
{3892}{3916}Gene...
{4014}{4061}Ihly prešli skrz,
{4086}{4122}ale rany sa zapálili.
{4125}{4169}Zdá sa, e tie ihly boli otrávené.
{4171}{4194}Otrávené?
{4201}{4246}Potrebujeme protijed.
{4259}{4292}Èo urobíme...?
{4304}{4382}Nepriate¾ môe vyui túto situáciu,|aby nás prinútil vyjednáva.
{4409}{4460}Prosím, prepáète za vyrušenie.
{4461}{4519}Z vonku prichádza vysielanie.
{4523}{4547}Pusti to!
{4563}{4632}Nazdar! Ako sa má kapitán Gene?
{4638}{4722}Ak nebude jeho krv vyèistená,|nedoije sa veèera.
{4874}{4963}Ak všetci opustia loï, dám vám protijed.
{4989}{5018}Protijed...?
{5148}{5204}Kašli na to, Jim...
{5206}{5234}Gene!
{5245}{5313}Myslíš, e by nás nechali odís?
{5435}{5507}Zdá sa, e má stále dobrú náladu...|Tak, èo urobíte?
{5508}{5551}Gilliam! Ukonèi spojenie!
{5652}{5691}Aké zábavné...
{5754}{5839}To som ja. Èoskoro tu bude trochu rušno.
{5848}{5928}Pozerajte sa len niekam inam,|a budete dobre odmenení.
{6009}{6040}Poïme.
{6053}{6106}Gene...! Èo budeme robi?
{6116}{6196}Súhlasím s Geneom, èo sa tıka pirátov.
{6204}{6239}Ale ak nieèo nespravíme, tak on...
{6275}{6340}Nie som si istá, èi naozaj majú protijed,
{6351}{6397}ale zdá sa, e našou jedinou monosou|je ís ho ukradnú.
{6399}{6434}Fajn, ja idem tie!
{6436}{6465}Poèkajte, prosím!
{6539}{6591}Ja by som to mono dokázala.
{6603}{6635}Èo také?
{6726}{6771}Rátame s tebou, Melfina...
{6778}{6801}Áno.
{6896}{6953}Upozornenie! Nepriate¾ sa pribliuje.
{7171}{7222}Gilliam! Nahoï všetky systémy!
{7238}{7335}Bez pomoci Melfiny máme k dispozícii|len obmedzenı poèet systémov.
{7344}{7410}Rozumiem. Daj nepriate¾a na monitor.
{7440}{7466}Daj mi detail.
{7488}{7556}Sme tu, aby sme vám predali protijed.
{7562}{7644}My loï nevydáme! Ak sa ešte priblíite,|budem strie¾a!
{7681}{7783}Ale, ale... Vzdávate sa teda|ivota kapitána Genea?
{7793}{7848}Stavím sa, e má teraz ve¾ké bolesti.
{7915}{7943}Gene...
{8159}{8228}Otec! Zvládol som u celé ovládanie!
{8708}{8728}Otec!
{8730}{8771}Chcem, aby si il, Gene!
{8772}{8801}Otec!
{8828}{8856}Ve¾a šastia!
{9000}{9063}OTEC!
{9189}{9308}Som... Som sám.
{9357}{9381}Gene.
{9402}{9430}Gene.
{9498}{9525}Gene.
{9594}{9636}Nie si sám.
{9674}{9704}Melfina...
{9742}{9816}Gene, ja a vylieèim.
{9844}{9885}Otvor svoje srdce...
{10363}{10384}Gene...
{10406}{10436}Gene...
{10454}{10483}Gene...
{10504}{10533}Gene...
{10555}{10583}Gene...
{10612}{10688}To je v poriadku. Rozumiem.
{10713}{10811}Zdá sa, e ti môem by na úitok.
{10839}{10934}Dokáem a zachráni, Gene.
{11280}{11329}Blíia sa nejaké divné zbrane!
{11335}{11359}Èo je to?
{11552}{11593}Len ich tam zadrte.
{11600}{11661}No, myslím, e mi nebude vadi,|keï to trochu poškodíte.
{11675}{11725}To sú pirátski obrnení mechanizovaní vojaci.
{11727}{11753}Sakra!
{11871}{11934}Lúèe neúèinkujú! Ale na pouitie rakiet|sú zas príliš blízko!
{11936}{12003}Jim, mám telefonát od pána Luo z Huga.
{12005}{12051}Teraz? Tak ho pusti!
{12060}{12133}Èau, Jim! Si roztomilı ako vdycky!
{12140}{12194}Èo chceš? Máme zrovna plno práce!
{12196}{12216}A Gene?
{12217}{12250}Zrovna tu nie je.
{12257}{12294}Poviem to teda tebe.
{12300}{12391}K Sentinelu III mieri nieko¾ko lodí pirátov Kei
{12396}{12475}a èoskoro dosiahnu kozmodróm West Virginia.
{12489}{12554}Ale nie sme v teritóriu Ban?
{12559}{12588}Veï práve to.
{12592}{12649}To, e zaèali vyjednávania tu v pohranièí...
{12653}{12714}...znaèí, e tu chcú zrejme rozpúta riadny chaos.
{12728}{12764}Ako to vieš?
{12770}{12869}No, uh... Fungova ako sprostredkovate¾|je mojou prácou, vieš.
{12882}{12935}Vykaš¾a sa na nich by bolo zlé pre biznis,
{12936}{13015}ale nechcel som pokazi náš vzah,|tak som sa rozhodol vám zavola!
{13016}{13069}Vïaka za varovanie! Koniec vysielania!
{13096}{13135}Sakra!
{13360}{13404}Nepriate¾ sa prichytil na vonkajšok lode.
{13438}{13475}Èo mám robi?!
{13653}{13684}Prepáè za zdranie.
{13686}{13708}Gene!
{13710}{13751}Jim, pusti ma na miesto pilota.
{13758}{13804}Ale tvoje zranenia sa ešte nezahojili...
{13814}{13882}Ty si ma zbavila jedu, pravda?|A ostatné u vydrím.
{13922}{14008}Vïaka, Melfina. Zachránila si mi ivot.
{14036}{14076}To niè.
{14120}{14180}Nepriate¾ské zbrane sa pokúšajú|nasilu otvori poklop!
{14311}{14371}Vezmem si XGP naspä!
{14461}{14547}Kvôli nepriate¾skému útoku je teraz|loï v nebezpeèenstve!
{14659}{14695}Ja viem, ja viem...
{14719}{14806}Len èo sa Melfina vráti, prerazíme si cestu von.
{14943}{14978}Všetky systémy pripravené.
{14994}{15023}Presne na to som èakal.
{15624}{15649}Bastard!
{15679}{15731}Èo sú to za Grappler ramená?!
{15748}{15822}Ale ak nedokáu dosiahnu cie¾, sú zbytoèné...
{15824}{15858}Zbabelec.
{16086}{16173}Poèuješ ma, Gene? Tento je môj.
{16177}{16229}Èo si myslí, e proti mne zmôe?
{16487}{16507}Èo to--?!
{16674}{16703}Èistá práca.
{16950}{16977}Je koniec.
{17004}{17058}Ušetri ma! Ja... ja...
{17200}{17248}Si zbabelec, e?
{17477}{17519}Nie je zlé, Suzuka.
{17528}{17581}Pokia¾ bojujem s pirátom Kei...
{17583}{17673}To je dobré vedie. Kadopádne, je naèase vyrazi.
{17684}{17770}V takejto chvíli by som poiadal|o pomoc Ctarl-Ctarl. Vrá sa dnu!
{17772}{17799}Tu je riadiaca vea!
{17800}{17881}Dok 26, Outlaw Star, èo sa to tam deje?!
{17899}{17970}Niè váne. Chystáme sa teraz na štart.
{17985}{18046}Pošlite nám údaje o poèasí a letovıch podmienkach.
{18060}{18122}Zamieta sa! Nedám vám povolenie k odletu!
{18132}{18182}Zistili sme si, e na štartovej ploche|došlo k vıtrnostiam!
{18184}{18264}Outlaw Star bude preverená správou prístavu.
{18274}{18313}-Zostaòte, tam kde ste.|-Sklapni!
{18324}{18368}Uvo¾ni všetky systémy z pohotovostného reimu!
{18380}{18431}Zaèni prechod do navigaèného reimu!
{18433}{18469}Èo plánujete urobi?
{18476}{18547}Odštartova bez navádzania z riadiacej vee.
{18963}{19003}Kontajner bol naloenı!
{19197}{19304}CFS aktivované. Newtonov reaktor sa spúša.
{19329}{19363}Systémy ukazujú normál.
{19384}{19422}Všetky stupnice ukazujú normál.
{19433}{19522}Moja posádka je banda šialencov...
{19527}{19603}Nabúral som sa do ich údajov o poèasí.|Posielam ti to na obrazovku.
{19604}{19650}Systém éterového pohonu funkènı.
{19697}{19750}Systém sub-éterového pohonu funkènı.|Systémy vykazujú normál.
{19776}{19831}Funkènos motora overená.
{19832}{19885}Zachytávam vysielanie z riadiacej vee.
{19896}{19960}Gene Starwind, okamite vıjdite z tej lode!
{19973}{20011}Prišla vás zatknú polícia!
{20028}{20087}Uvedomujete si, èo robíte?!
{20115}{20150}Èo budeme robi, Gene?
{20210}{20283}Myslím, e na Sentinel sa vráti nemôeme...
{20324}{20370}Zbavme sa ich a vypadnime odtia¾to.
{20389}{20425}Vyhovuje ti to, Suzuka?
{20427}{20459}Pôjdem s vami.
{20620}{20668}Ak sa tam budete zdriava, popálite sa!
{20779}{20806}Poïme, Jim!
{20813}{20836}Hej!
{20838}{20863}Pripravená, Melfina?
{20872}{20894}Áno!
{20913}{20988}Jednotka gravitaèného cyklu funkèná.|Systémy vykazujú normál.
{21089}{21193}Gene Starwind, stoj! Nerob to!
{21195}{21228}Sklapni!
{21284}{21336}Vidím, e naozaj sa do toho chcete pusti...
{21344}{21399}Loï je vzduchotesná.
{21408}{21461}Všetky navigaèné údaje nominálne!
{21469}{21519}ivotné podporné systémy vykazujú normál.
{21535}{21581}Všetko ovládanie vykazuje funkènos.
{21595}{21626}Všetky systémy v poriadku!
{21636}{21716}Vıkon motora stabilnı. Zaèínam odpoèítavanie.
{21724}{21760}T-mínus-30 do štartu.
{21987}{22020}T-mínus-20.
{22109}{22187}Take moje putovanie sa koneène zaèína, èo?
{22302}{22351}Zbohom, Hilda.
{22376}{22409}T-mínus-10.
{22420}{22439}Osem.
{22443}{22459}Sedem.
{22464}{22482}Šes.
{22484}{22503}Pä.
{22509}{22527}Štyri.
{22535}{22551}Tri.
{22558}{22577}Dva.
{22582}{22601}Jedna.
{22611}{22623}Nula.
{22624}{22650}Ideme!
{23192}{23239}Štart lode ukonèenı!
{23810}{23928}Otec! Keï vyrastiem, budem vesmírnym pilotom!
{23952}{24052}Naozaj? No, ak sa budeš snai, mono raz budeš.
{24056}{24123}Hej! Ja to dokáem!
{24441}{24523}Opustili sme atmosféru. Prosím,|vynes nás na orbit.
{24532}{24612}Úspešne sme ukonèili odlet z planéty.
{24619}{24646}Zvládli sme to!
{24805}{24915}Istee sme to zvládli!|Som perfektnı vo všetkom, èo robím!
{24997}{25030}Urèite...
{25101}{25144}Akí zábavní ¾udia...
{25146}{25247}Blahoelám, Gene. Mrzí ma,|e ruším vaše oslavy, ale...
{25260}{25283}Èo je?
{25284}{25363}Upozornenie! K našej pozícii sa blíia nejaké lode!
{25364}{25382}Piráti?
{25384}{25447}Vzdialenos, 20 000. Zdá sa, e nás zbadali.
{25779}{25860}Gakkie! Onok! Vidíte ich?|Zaútoèíme za dve minúty!
{25928}{25987}Take tí dole to zbabrali, èo?
{26061}{26132}Hej, ja som v pohode! Poïme sa trochu pobavi!
{26145}{26191}Neodpovedajú na naše vızvy.
{26207}{26302}To je rušièka. Vyzerá to, e to sú pirátske|Grappler lode.
{26309}{26332}Gene...
{26355}{26388}Pripravte sa na Grappler boj!
{26390}{26443}Gilliam, ako sa pouívajú tie zbrane?
{26448}{26524}Len èo uvo¾níte poistky, mali by sa vyzbroji samé.
{26528}{26584}Si si tım istı? Nikdy predtım si to nerobil!
{26587}{26670}Bez obáv. Keï sa jedná o manipulátory,|som jednièka!
{26684}{26784}Kadopádne, pomô mi, aby som to zvládol, partner!
{26932}{26992}Teraz prepínam do Grapplerového bojového reimu.
{27162}{27210}Boj zaène za 30 sekúnd.
{27216}{27280}Rozumiem! Jim, vypusti kamery!
{27292}{27318}Jasné!
{27360}{27379}Take...
{27381}{27426}Nepriate¾ské lode rozmiestòujú kamery takisto.
{27428}{27470}Ako som si myslel, sú to Grappler lode.
{27568}{27611}Nepriate¾ vypustil nieko¾ko striel!
{27613}{27648}Vypúšam antirakety!
{27796}{27819}Ideme na to!
{27995}{28038}Snaíš sa seka frajera, èo? Je po tebe!
{28176}{28204}Kruci, schytal som to!
{28262}{28286}Si okej, Onok?
{28288}{28319}Hej, dostanem ho!
{28322}{28369}Si myslíte, e so zbraòou sa mi vyrovnáte?!
{28416}{28464}-Nestrie¾a to!|-Zásobník je prázdny!
{28466}{28515}Treba ho vymeni za rezervnı!|Zaberie to jednu minútu!
{28524}{28604}Daj sa do toho! Zatia¾, poïme na boj zblízka!
{28781}{28804}Poïme na to, Gakkie!
{28811}{28861}Hej! Kúpim pre nás rundu, keï sa vrátime!
{29197}{29219}Bastard!
{29511}{29533}Dostal ich!
{29538}{29567}Ešte stále jeden zostáva.
{29572}{29615}Motor è. 2 vykazuje nepravidelnosti.
{29621}{29671}Vıkon klesol o 30%.
{29676}{29742}Rozumiem! Dorazím rıchlo tohto!
{29787}{29833}Zabil si Onoka a Gakkiho, ty bastard!
{29844}{29882}Si màtvola!
{30328}{30351}Bastard!
{30974}{31032}Ten chlap je... celkom dobrı...
{31248}{31277}Dokázal si to, Gene!
{31284}{31329}Teraz opúšam bojovı mód.
{31351}{31459}Teda, bola to riadna fuška...|Dal by som si sprchu!
{31517}{31564}Gene, vıborne.
{31584}{31615}Vïaka, Mel.
{31633}{31681}To niè. Zvládol si to sám.
{31704}{31778}Vıborne, všetci.
{31810}{31936}Prekonali sme gravitáciu Sentinelu III.
{31961}{32033}Mám pripravi sub-éterovı pohon?
{32063}{32118}Fajn... Poïme do Heifongu.
{32127}{32150}Preèo tam?
{32154}{32215}Heifong je teritórium pirátov Ban.
{32219}{32280}Títo Kei tam asi za nami nepôjdu, však?
{32316}{32370}To nie je isté.
{32372}{32464}Ale Heifong má ve¾ké mestá, take mono sa|nám tam pritrafí dobrá práca.
{32475}{32498}Práca?
{32501}{32590}Ako inak zaplatíme za údrbu, opravy a muníciu?
{32596}{32622}Máš pravdu...
{32627}{32683}Fakt sme zdedili ve¾kú oštaru...
{32686}{32779}No dovo¾te, ale ja som Gilliam II,|a nie "ve¾ká oštara"
{32785}{32857}a táto loï sa nazıva Outlaw Star.
{32883}{32941}Je v poriadku, ak nastavím kurz na Heifong?
{32956}{33050}Iste, pusti sa do toho. Je to vılet asi|na 20 svetelnıch rokov.
{33093}{33164}Zbohom, Sentinel III!
{35481}{35541}Prei najväèšiu krízu svojho ivota|je úplne fajn a v pohode,
{35544}{35630}ale mal by si pamäta, e potom|u nemáš èo robi!
{35636}{35690}Toto, e je tá "najotravnejšia" èinnos,|o ktorej som poèul?
{35696}{35784}Nu, v takej chvíli, pusti sa do práce...
{35786}{35828}...je tım najlepším liekom, však, Jim?
{35867}{35939}Nad èím sa rozèu¾uješ?
{35952}{36062}Nabudúce v Outlaw Star!|"Dobrodruné putovanie! Ha?"
{36073}{36128}Radšej sa pripravte!
