{93}{185}"Ktovie, èo je tam za tım morom...?"
{219}{338}Takto uvaujúc, mladík|nakoniec opustí svoj domov. 
{364}{432}"Èo je tam? Èo ma tam oèakáva?" 
{447}{522}Odchádzajú, len preto, aby to zistili.
{538}{616}Leia pred nimi nespoèetné útrapy.|Zúfalstvo.
{632}{679}Pokušenie kráèa po ostrí noa. 
{687}{780}Nádej. Rados.|Spoznávanie novıch priate¾ov.
{801}{844}Mladí zanechávajú svoju nevinnos, 
{851}{950}uèia sa, trpia a spoznávajú samıch seba.
{967}{1004}Toto je putovanie. 
{1021}{1138}Keï dobyjú novú krajinu, v ich oèiach|sa u odráa ïalšie more. 
{1167}{1223}"Èo je tam za tım morom...?" 
{1244}{1356}Keï sa z chlapcov stanú mladí mui,|opä na to zaènú myslie. 
{1385}{1457}Toto je putovanie. 
{2757}{2800}BillSK & Pedro uvádzajú:
{2817}{2933}OUTLAW STAR: "Dobrodruné putovanie! Ha?". 
{2950}{3025}Produkcia: BillSK
{3025}{3100}Slovenské titulky: Pedro (pedro_k@post.sk)
{3100}{3175}Spracovanie videa: Randy
{3175}{3275}Nie je urèené pre komerèné pouitie.
{3910}{3986}Toto je fakt prive¾a.|Trèím na tejto nebezpeènej ceste... 
{3994}{4080}...pretoe on stále zotrváva pri tom|svojom nezodpovednom správaní. 
{4843}{4895}Èo robíte, Gene? 
{4942}{4969}Fajn, èo? 
{4971}{5038}Ohromná sranda. A teraz,|išli by ste si odpoèinú?  
{5123}{5166}Mono som bol námesaènı... 
{5174}{5212}Sorry, idem do postele. 
{5214}{5250}Dobrú noc. 
{5310}{5333}Gilliam... 
{5335}{5378}Deje sa nieèo? 
{5447}{5483}To niè. 
{5552}{5642}AU! 
{6069}{6092}Jim? 
{6115}{6156}Melfina? Èo je? 
{6163}{6202}Um... Nemáme iadnu so¾. 
{6207}{6289}So¾? Myslím, e som tu|nejakú so¾ niekde videl... 
{6301}{6344}Mám ju! Tu máš! 
{6399}{6426}Ïakujem. 
{6438}{6519}Len chví¾ku vydr a ja pripravím veèeru.
{6525}{6546}Okej! 
{6709}{6728}Gilliam? 
{6734}{6762}Áno, Jim? 
{6763}{6828}Kde je Gene? Ešte sa nezobudil? 
{6834}{6926}Nie. Pokúšal som sa ho dosta z postele,|ale neúspešne. 
{6971}{7008}Sakra... 
{7024}{7062}Gene, vstávaj! 
{7074}{7086}Gene! 
{7092}{7111}Gene! 
{7115}{7129}Gene! 
{7132}{7152}Gene! 
{7208}{7261}Gene, zobuï sa. 
{7267}{7280}Gene! 
{7283}{7294}Gene! 
{7298}{7312}Gene! 
{7315}{7330}Gene! 
{7371}{7398}Gene! 
{7407}{7463}Kruci, tak vstaneš u?! 
{7468}{7521}Jak dlho mieniš zosta v posteli? 
{7593}{7657}Pobozkaj ma, Rosie...|Potom vstanem...
{7701}{7737}Prestaò s tım, ksakru! 
{7742}{7773}Dobre, dobre... 
{7775}{7814}Vylez z postele, krucinál! 
{7932}{8042}Keï a nikto nevyenie,|preflákaš v posteli celı deò! 
{8043}{8074}Tak v èom je problém? 
{8076}{8130}Momentálne sa nemusíme bá,|e by nás niekto napadol, 
{8132}{8167}a ináè tu nie je fakt niè,|èo by bolo treba robi. 
{8181}{8235}A z toho všetkého, èo sa posledne udialo,|som znièenı! 
{8239}{8283}To ostatní takisto! 
{8289}{8345}Navyše, je tu hromada vecí,|ktoré treba spravi. 
{8407}{8466}Predovšetkım, táto loï si vyaduje údrbu.|
{8470}{8533}Ak èosi neurobíme, èoskoro|bude vány problém s varením. 
{8599}{8635}Èo, do èerta, sa tam dole stalo?! 
{8637}{8703}Nebol èas všetko zabezpeèi,|keï sme odštartovali, pamätáš? 
{8705}{8763}A potom sa všetko pomiešalo|poèas toho grapplerového boja, 
{8765}{8812}take vidíš, èo sa stalo. 
{8814}{8838}Oh, nie... 
{8839}{8908}Taktie si musíme sadnú|a premyslie si, èo bude ïalej, 
{8913}{8968}a tak nemáme èas celı deò|sa pova¾ova v posteli. 
{8985}{9019}Èo bude ïalej? 
{9025}{9082}Hej. Oh¾adne firmy Starwind & Hawking.
{9113}{9147}Èo máš na mysli? 
{9333}{9359}Dobré ráno! 
{9367}{9393}Dobré. 
{9402}{9458}Kadopádne, Heifong je ve¾ká planéta,|take ak tam pôjdeme, 
{9459}{9551}myslím, e u nebudeme ma|ïalšie problémy s tımi pirátmi Kei. 
{9556}{9624}Ale ja si nemyslím, e galaxia je taká|skvelá a fajn... 
{9629}{9696}...e si nájdeme dobrú prácu len preto,|e tam pôjdeme. 
{9718}{9751}Dobre to vonia... 
{9752}{9776}Gene! 
{9796}{9839}Váne máš z toho také obavy? 
{9841}{9907}Obavy? Ty to nechápeš, Gene?! 
{9934}{9960}Èo také? 
{9962}{9993}To mi ani nehovor! 
{10003}{10103}Pozri, nikdy sme na Heifongu neboli|a nemáme tam iadne konexie! 
{10107}{10165}Ak nezaèneme zhromaïova informácie|a nevymyslíme nejakı plán, 
{10170}{10218}len samotné splatenie našich dlhov|bude našou najmenšou starosou! 
{10221}{10268}V dobe, keï pristaneme,|budeme na tom ve¾mi zle s jedlom! 
{10276}{10331}Neboj, to bude v pohode. 
{10332}{10399}K èomu je dobré teraz sa nad tım trápi?
{10403}{10492}Tak u si sa rozhodol, do ktorého mesta|na Heifongu pôjdeme, Gene? 
{10499}{10559}A èo spravíme s poplatkami za parkovanie,|hm?! 
{10568}{10636}Vdycky si takıto!|Nikdy si veci nepremyslíš!
{10643}{10690}Vdy nechávaš všetko na náhodu! 
{10694}{10758}Ak nezaèneme pouíva svoje hlavy|a správa sa chytro, 
{10761}{10832}nikdy nesplatíme tıch 750 000 wongov!
{10836}{10887}Ah, nechcem o tom poèu... 
{10896}{10969}Akurát si musíme nájs poriadny dob,|pravda? 
{10979}{11058}Potom môme splati, èo dlíme|a po zvyšok svojho ivota si naíva ako králi! 
{11216}{11285}Um... Prosím, prestaòte sa háda. 
{11323}{11352}Aké decko... 
{11541}{11604}Nesmieš to necha tak dlho vrie. 
{11606}{11653}Takto sa ti vyvarí aj chu. 
{11657}{11682}Oh. Ï-Ïakujem. 
{11793}{11862}Smiem sa k vám pripoji na veèeru? 
{11870}{11902}I-Iste! 
{11919}{11987}Tak. A je tu ešte jeden problém. 
{12064}{12111}Nazvala a deckom! 
{12132}{12181}Tak buï teda ticho a jedz, diea!
{12195}{12257}Po pravde, mala som na mysli,|e si ve¾mi nedospelı. 
{12387}{12458}Èoe? To si hovorila mne?! 
{12465}{12512}Tebe to tak nepripadalo? 
{12514}{12537}Ty jedna...! 
{12538}{12564}Gene? 
{12584}{12674}Ja si tie myslím,|e sa správaš smiešne.
{12678}{12754}Èoe, take vravíš,|e všetko je moja chyba? 
{12759}{12787}Nie, to nie-- 
{12805}{12863}Dajte mi pokoj...|U mám dos tıchto hovadín. 
{12869}{12902}Gene? A èo tvoje jedlo? 
{12904}{12931}Nechcem iadne. 
{13099}{13151}Èo budeme robi s tou dámou? 
{13153}{13212}Viem, e veci sa tak vyvinuli,|ale necha ju ís s nami len tak...? 
{13216}{13280}Èo tım myslíš? Nemôeme niè robi. 
{13289}{13390}Idú po nás piráti Kei.|Potrebujeme ju ma zo sebou. 
{13394}{13503}To je síce fakt,|ale nepokúsi sa a opä zabi? 
{13507}{13626}Ktovie? A keby aj, na palube tejto lode|sa o niè nepokúsi. 
{13633}{13664}Pozri, netráp sa tım. 
{13666}{13704}To si celı ty, Gene! 
{13714}{13814}Jim, môj otec mi kedysi dávno povedal|jednu vec. 
{13833}{13897}"¼udia, ktorí chcú ve¾a, myslia vo ve¾kom."|
{13899}{14014}"¼udia, ktorí myslia v malom,|zarobia toho málo." 
{14015}{14077}"A na tomto všetkom je zaloenı biznis"|povedal. 
{14089}{14127}Take, o èo ti ide? 
{14137}{14175}Oh, niè. 
{14177}{14227}Tak, prepáè, e myslím v malom. 
{14231}{14292}Môeš si vypráva o robení ve¾kıch vecí,
{14297}{14390}ale ja radšej zostanem takıto|a všetko si najprv vdy premyslím. 
{14403}{14428}Èo si povedal? 
{14430}{14458}Èo? 
{14512}{14558}Gilliam, kde sme? 
{14561}{14634}O ïalších 20 svetelnıch rokov|vstúpime do priestoru Kozat. 
{14645}{14748}Pod¾a èasu na Sentineli, to bude trva|na Heifong asi tak tri dni. 
{14774}{14810}Tri dni, èo? 
{14830}{14946}Krucinál, Jim! Poupratuj|alebo choï pra! Vyber si! 
{15003}{15095}Máme šastie, e nás zatia¾|ešte nenapadli piráti. 
{15097}{15196}Váne? Ja by som si to prial.|Nudím sa. 
{15204}{15253}Prosím, nehovorte také veci. 
{15263}{15304}Èo by sa stalo, keby prišli? 
{15308}{15381}Šiel by som na to a vyprášil ich,|tak veru. 
{15547}{15627}Myslím, e nebudem jes,|kım budem ma pred sebou svoje trenírky... 
{15706}{15802}Gene, èo to robíte? Prestaòte!|To je môj-- 
{15804}{15874}Èo mám iné robi?|Nemám ich kam zavesi!
{15875}{15950}Nemôete ich zavesi|v nákladnom priestore? 
{15952}{16046}Jim si zabral nákladnı priestor|pre seba. Nepustí ma tam. 
{16050}{16110}Tak si to robte v svojej|vlastnej kajute. 
{16118}{16174}Veša ich na údrbársku ko¾aj|rozhodne nepripadá do úvahy! 
{16188}{16235}To mám akoe spa so svojimi|trenkami nad hlavou? 
{16236}{16265}Veï sú vaše... 
{16288}{16349}Veï práve preto. 
{16589}{16656}Ešte stále je naštvanı? 
{16729}{16825}Gilliam, vravel si, e sa chystáme|vstúpi do priestoru Kozat, e? 
{16829}{16865}Áno, to je pravda. 
{16875}{16953}Je tam nablízku stanica zvaná|Toward Stars Inn? 
{16955}{16986}Áno, je. 
{17056}{17085}Skvelé... 
{17111}{17133}Jim! 
{17207}{17264}Èoe, stále sa hneváš? 
{17271}{17299}Èo chceš? 
{17301}{17319}No... 
{17507}{17574}Vedel som to. Vedel som,|e budem na posmech. 
{17592}{17668}Èo ksakru? To si spravil ty? 
{17702}{17742}Ja som to bol! 
{17751}{17864}iadal som ho, aby to vrátil|do pôvodného stavu, ale nepoèúva ma. 
{17875}{17950}Hej, v èom je problém? Je to pekné!
{17985}{18021}Koniec koncov... 
{18022}{18115}Je ich tu ve¾a, take je fajn,|keï sa bude jeden odlišova, nie? 
{18169}{18240}Oh, iste. Mal by si to ís ukáza|aj Melfine. 
{18292}{18345}Ja tu mám stále ešte kopec roboty. 
{18351}{18416}Prepáè, ale keï skonèíš,|mohol by si odís? 
{18429}{18514}Nu, myslím, e sa zastavím na stanici,|aby som si zariadil istú nudnú záleitos.
{18519}{18547}Na stanici? 
{18554}{18646}Hej. Èi prídeš na palubu alebo nie,|je na tebe. 
{18654}{18713}Mimochodom, prišiel som,|len aby som ti to povedal. 
{18720}{18746}Ale preèo? 
{18752}{18810}Aj keï sa zastavíme na tej stanici,|nemáme peniaze! 
{18818}{18862}Èo zamıš¾aš, Gene? 
{18864}{18913}Hej, tım sa netráp. 
{20191}{20237}Gene, èo máš v úmysle? 
{20239}{20306}Keï budeme odchádza,|tie si prebojujeme cestu von? 
{20311}{20400}Nie. Nechcem si znepriateli|aj tıchto chlapíkov z Ban. 
{20403}{20433}Èo teda? 
{20439}{20517}Náš problém je, e sme švorcoví,|však? Sme bez peòazí. 
{20523}{20569}Nehovor mi, e si tu zamıš¾aš|zarobi peniaze! 
{20571}{20630}Dalo by sa tak poveda.|Heifong je neïaleko, 
{20634}{20693}take si potrebujeme napcha peòaenky,|skôr ne sa tam dostaneme. 
{20702}{20730}Oh, pre lásku b... 
{20735}{20803}Mám tu nieèo na práci,|tak sa teraz vzdialim. 
{20811}{20853}Odchádzame o 20:00 hodine,|pravda? 
{21366}{21442}Najprv sa najedzme!|Keï sa nenajeme, nemôme pracova! 
{21447}{21518}Neartujem!|Zostalo nám len pár drobnıch!
{21523}{21553}Ïalšie u nedostaneš. 
{21555}{21618}Tak prestaò fòuka a zaèni jes!
{21624}{21663}Zjem to všetko! 
{21716}{21751}Víazstvo patrí šikovnım! 
{21757}{21789}Sakra... 
{22134}{22157}Um... 
{22176}{22226}Je to vynikajúce. 
{22263}{22292}Ïakujem. 
{22322}{22387}Jim, v poslednom èase si bol|akısi nesvoj, tak som mala obavy. 
{22389}{22434}Dobre sa najedz, áno? 
{22435}{22485}Huh? To je, uh... 
{22503}{22593}Teda, decká sa majú!|Všetky enské sú k nim milé. 
{23081}{23108}Tak? 
{23131}{23187}Èo máš v úmysle, Gene? 
{23189}{23225}Vysyp to. 
{23231}{23278}Dobre, tak ti to teda poviem. 
{23285}{23370}Dopoèul som sa o tom,|keï som sa raz rozprával s Fredom. 
{23378}{23463}Hovorí sa, e za mestom ije|legendárny h¾adanı mu. 
{23465}{23503}Má cenu 10 000 wongov. 
{23505}{23535}Desa tisíc?! 
{23625}{23673}Nemám iadne informácie o takom chlapovi.
{23679}{23712}Nie sú iadne informácie! 
{23714}{23767}Ale všetci tu naokolo ho poznajú. 
{23769}{23839}Si si istı, e to je dobrı nápad|zaobera sa tım chlapom, Gene? 
{23842}{23900}"Ak máš nieèo spravi,|tak nech to stojí za to." 
{23902}{23951}To je motto firmy Starwind & Hawking.
{23962}{24046}Nie, to je tvoje motto!|Ja s tım nechcem ma niè spoloèné. 
{24058}{24103}Hej, to je ono! 
{24115}{24141}Rob ako chceš. 
{24143}{24226}Keï získam tıch 10 000 wongov,|zase si zájdem do dobrej reštaurácie, 
{24229}{24268}ale tebe, Jim, zostanú len nejaké drobáky,
{24271}{24338}take predpokladám, e mieniš|asi dojeda zvyšky a tak. 
{24355}{24413}Poèka! Kto povedal,|e do toho nepôjdem?
{24426}{24495}Oh, váne? Tak teda ideš alebo nie?
{24516}{24555}Myslím, e sa pridám. 
{24562}{24610}Rátam s tebou, partner! 
{24614}{24656}P-Prestaò, Gene! 
{24658}{24682}Um... 
{24684}{24754}Deje sa nieèo? 
{24856}{24916}Prepáè, Mel, ale mohla|by si sa vráti na loï? 
{25071}{25108}Èo to bude? 
{25118}{25183}Mám tam hore nejaké jednanie|s muom menom Zomba. 
{25461}{25494}Ste lovec odmien? 
{25496}{25524}Nieèo také. 
{25653}{25697}Povedzte mi svoje meno a vıšku. 
{25699}{25725}Svoju vıšku? 
{25726}{25783}Budem musie objedna ïalšiu rakvu.
{25786}{25876}Hej, to rád poèujem! Ten chlap|asi fakt stojí za tıch 10 000!
{26127}{26188}Aké nezdvorilé. Èo chcete? 
{26199}{26226}Vy ste Zomba? 
{26232}{26259}Áno. 
{26270}{26339}Som Gene Starwind,|mu, ktorı vás dostane...
{26342}{26389}...a zapíše svoje meno do legiend. 
{26394}{26462}Na náhrobnı kameò, chcete poveda? 
{26529}{26598}Vyriešme to vonku.|Nechcem si ušpini izbu. 
{26599}{26655}Oèakávate v noci priate¾ku? 
{26662}{26744}Nediskutujem s ostatnımi|o svojom súkromnom ivote. 
{26748}{26824}V dnešnej dobe to len viac|priahuje pozornos. 
{26833}{26867}Budem si to pamäta. 
{27403}{27496}Vrana vám u spieva svoju pieseò smrti.
{27505}{27595}Mne to pripadá, akoby spievala vám.
{27615}{27687}To zistíme u èoskoro. 
{27866}{27926}Ako vám to vyhovuje. Do toho. 
{28175}{28196}Jim? 
{28200}{28229}Za moment! 
{28238}{28294}Gene, jeho slabım miestom je chrbát!
{28295}{28336}Musíš sa dosta zaòho! 
{28342}{28382}To sa ¾ahko povie... 
{28487}{28566}Zdá sa, e tá vrana spievala mne,|predsa len... 
{28662}{28702}Aké sklamanie. 
{28723}{28763}Gene! Ešte nie je po òom! 
{28869}{28908}Tá pieseò bola pre vás. 
{28932}{28954}Myslíš? 
{29024}{29058}Staèí. 
{29090}{29193}Sorry, ale keï bojujem s kyborgmi,|idem naplno. 
{29203}{29237}Vïaka, Jim. 
{29248}{29291}To niè! 
{29471}{29534}Dokázali sme to!|2 000 wongov! Dvetisíc!
{29536}{29595}Myslím, e to malo by desatisíc. 
{29596}{29626}Hej, nedá sa niè robi. 
{29628}{29731}Bol to falošnı android|a nie samotnı Zomba. 
{29741}{29831}Hej, nemôme sa saova.|Dvetisíc je ve¾a! 
{29833}{29856}Tie myslím. 
{29858}{29931}A u èoskoro dostanem|aj skutoèného Zombu! 
{29935}{29982}Chlap musí spravi to,|èo spravi treba! 
{29993}{30096}Keï si chlap, musíš robi|poriadne veci. Je tak, Jim? 
{30098}{30117}Ako myslíš. 
{30122}{30175}Aha, veï to je Gene. 
{30183}{30211}Ha? Suzuka? 
{30227}{30275}Zdá sa, e sme mali rovnakı nápad. 
{30277}{30338}Hej! Máme 2000 wongov! 
{30394}{30454}Dostali sme legendárneho h¾adaného mua.
{30462}{30493}Legendárneho...? 
{30505}{30618}Hej. Bol fakt tuhı, a bez mojej rady
{30619}{30654}by mal Gene naozaj ve¾ké trable. 
{30656}{30708}Hej, o èom to hovoríš? 
{30728}{30787}Tak, ko¾ko si zarobila? 
{30804}{30853}Oh, len malièkos. 
{31021}{31046}Pozrite! To je ona! 
{31052}{31111}Dostala Zombu?! Fakticky? 
{31118}{31165}Vraví sa, e mal cenu 10 000 wongov!
{31329}{31384}Suzuka dostala skutoèného Zombu...?
{31388}{31473}Vypadá to, e naša šanca dokáza|si svoju munos sa práve rozplynula. 
{31520}{31568}Veï som to vravel, Gene... 
{31582}{31642}Ak spolu nieèo nepodnikneme, 
{31647}{31704}firma Starwind & Hawking bude ma problémy.
{31829}{31903}Pre tento jeden jedinı deò, 
{31907}{31959}sa tu lode tıch, ktorí zdokona¾ovali|svoje zruènosti... 
{31963}{32035}...zhromaïujú jedna za druhou! 
{32044}{32113}Nájde sa niekto v tomto|13. Heifongskom vesmírnom závode, 
{32123}{32256}kto prekoná všetky prekáky|a získa veniec víaza?! 
{32286}{32342}Do štartu zostáva pä dní! 
{32493}{32518}Tá loï... 
{32527}{32570}Deje sa nieèo, Gene? 
{32577}{32620}Nie, len som si pomyslel, e... 
{32626}{32688}Poïme na Heifong, partner. 
{32702}{32727}Jasné! 
{32743}{32770}Vitajte spä! 
{32778}{32814}Ihneï odlietame. 
{32815}{32840}Dobre. 
{33172}{33290}Tá loï... To bola MacDougallova loï,|o tom niet pochıb. 
{35571}{35623}Ve¾ké mesto, o ktorom snívajú|všetci mladí mui! 
{35630}{35682}Koneène sme sa dostali na Heifong! 
{35691}{35783}Aby si tu našiel svoje šastie,|musíš preda svoje meno! 
{35797}{35899}A tak sme vstúpili|do okúz¾ujúceho sveta motošportu. 
{35923}{35982}Len poèkajte, MacDougallovci! 
{35999}{36098}Nabudúce v Outlaw Star!|"Príprava na vesmírny závod"! 
{36108}{36157}Radšej sa pripravte! 
