{95}{175}História závodenia vo vesmíre je dlhá. 
{198}{263}Pred vynájdením Munchausenovho pohonu...
{269}{381}...prebiehali závody v slneènej sústave|s vyuitím primitívnych lodí. 
{404}{514}S vytvorením FTL lodí sa rozsah závodov rozšíril,
{524}{609}a dnes sa od nich odvodené súae... 
{611}{650}...odohrávajú po celej galaxii. 
{672}{752}Továrne vyvíjajúce vesmírne lode riskujú|svoju prestí a svoje podniky... 
{754}{801}...tım, e utápajú peniaze vo firemnıch lodiach,
{811}{915}zatia¾ èo neznámi nezávislí piloti nastupujú|s vlastnımi loïami, veriac v ich schopnosti.
{932}{1090}Ale nech u sú firemní alebo nezávislí,|všetkım pilotom na pretekoch ide o rovnakú vec. 
{1111}{1184}Sláva a èes pripadajúca víazovi... 
{1190}{1251}...ich enie vpred v tıchto nebezpeènıch závodoch. 
{1273}{1335}Slávne závody, na ktorıch sa zúèastòuje mnoho lodí... 
{1343}{1436}...sú všetkım známe kvôli obtianosti ich tratí. 
{1454}{1542}Avšak tomu, kto prekoná tieto prekáky...
{1553}{1638}...tomu pripadne koneèná sláva. 
{1790}{1869}Semenaide, kesanaide, makenaide... 
{1871}{1990}...daredatte motteru| hazu yuzurenai mono. 
{2002}{2075}Ai dake, yume dake, kimi dake... 
{2079}{2221}...sore dake wa hanasanai,| donna toki demo. 
{2279}{2378}Dou shiyou mo naku,| ochitsukanai yoru... 
{2383}{2493}...nani mo ka mo nagedashitaku naru. 
{2498}{2595}Tsubekobe iwazuni,| sassa to doa wo akena.
{2600}{2707}Rikutsu nante, koneteru hima wa nai. 
{2710}{2913}Juu'ou-mujin tobimawaritai,| you'i-shuutou mamoritakunai! 
{2919}{3098}Nakushita wakeja nai,| mada hajimattenai dakara. 
{3119}{3200}Semenaide, kesanaide, makenaide... 
{3203}{3319}...daredatte motteru| hazu yuzurenai mono.
{3332}{3414}Ai dake, yume dake, kimi dake... 
{3416}{3532}...sore dake wa hanasanai,| donna toki de mo. 
{3564}{3670}Nani ga hoshii? Nani ga| shitai? Doko ni ikitai? 
{3672}{3824}Yami wo saite hashirinukete| tsukamitore through the night! 
{4023}{4095}Tu je Heifong, riadiaca vea kozmodrómu Dailong.
{4099}{4173}Outlaw Star, mám vás na navádzacom majáku.
{4193}{4245}Koneène sme sa dostali do Heifongu... 
{4247}{4350}Heifong je mestská planéta,|nebudú prístavné poplatky príliš drahé? 
{4358}{4398}To sa vyrieši samo. 
{4763}{4794}To je úasné, Gene! 
{4796}{4848}Nevzrušuj sa tak...|Je to trápne. 
{4850}{4890}Ale pozri na toto! 
{5010}{5075}Teda, Heifong je oblas s ve¾komestami,|to je fakt! 
{5081}{5102}Hej! 
{5113}{5183}Tak, kam sa chceš vyda teraz? 
{5198}{5256}Do kancelárie pre Heifongské vesmírne závody!
{5271}{5303}Vesmírne závody? 
{5307}{5385}Vstúpime s Outlaw Star do vesmírnych závodov
{5500}{5632}Áno, to je pravda. Heifongské vesmírne závody|sú otvorené pre kadého. 
{5642}{5718}Vstupnı poplatok môe zaplati buï firma|alebo jednotlivec, 
{5723}{5765}a ani trieda lode nie je dôleitá. 
{5775}{5838}Ešte stále sa mono zaregistrova. 
{5839}{5918}Je tu ešte jedna vec, ktorú by som rád vedel.
{5936}{6006}Rád by som si pozrel údaje|o ostatnıch lodiach na pretekoch. 
{6007}{6093}Pod¾a pravidiel, nemôete|preskúmava ostatné lode. 
{6095}{6146}Zaujímam sa len o jednu loï. 
{6158}{6197}To by nebolo férové. 
{6203}{6236}Ste si istá, e nemôete? 
{6238}{6260}Áno. 
{6307}{6404}Nu, v tom prípade, je tu ïalšia vec,|ktorú by som rád vedel. 
{6411}{6442}Èo také? 
{6443}{6482}Vaše telefónne èíslo. 
{6491}{6578}Som si istá, e u poznáte èíslo|do tejto kancelárie. 
{6587}{6635}Nu, keï to beriete takto... 
{6637}{6702}Take, len èo bude po závodoch,|zavolám do kancelárie. 
{6709}{6797}Poviete nám teraz, èo treba spravi,|aby sme mohli letie vo Vesmírnych závodoch?
{6801}{6873}Staèí vyplni potrebné údaje na tıchto formulároch.
{6877}{6974}Náš personál vykoná jednoduchú kontrolu na|palube pred zaèiatkom pretekov. 
{6987}{7010}To je všetko? 
{7012}{7073}Áno. Taktie potrebujete vloi 150 000 wongov...
{7076}{7151}...na urèenı úèet ako vstupnı poplatok. 
{7201}{7234}Ko¾ko? 
{7235}{7322}150 000 wongov. Obsahuje aj poistenie. 
{7328}{7372}"Otvorené pre všetkıch", èo?! 
{7376}{7440}Aj keï vyhrám závody, nedostanem spä|ani jedinı wong, pravda?! 
{7442}{7497}iadny súkromnı pilot nemá to¾ké peniaze!
{7503}{7557}Za to by sa dalo kúpi desa slušnıch áut!
{7559}{7650}Preto si takí ¾udia h¾adajú sponzora. 
{7663}{7690}Sponzora? 
{7691}{7795}Áno. Na Heifongské vesmírne závody nahliada...
{7797}{7882}...mnoho firiem ako na vysoko úèinnú reklamu.
{7891}{7913}Avšak... 
{7914}{7941}Èo také? 
{7943}{8062}Pre nového úèastníka môe by aké|nájs si sponzora. 
{8068}{8105}Ïakujem pekne! 
{8107}{8195}Len sa dívajte!|Nastúpime do závodov a vyhráme ich! 
{8227}{8274}Ibae neviem ako... 
{8539}{8577}Nechaj to tak, Gene. 
{8583}{8656}Nikdy sa nám nepodarí da dokopy 150 000,|nech budeme robi èoko¾vek. 
{8679}{8742}Poletíme vo vesmírnych závodoch.|Sú na to dva dôvody: 
{8744}{8852}Po prvé, preda naše mená. Lebo ak nie,|ve¾ké kšefty sa nám nepohrnú. 
{8854}{8911}Myslíš, vyui to ako firemnú reklamu? 
{8913}{8972}Nu, ak nám závody nevynesú iadne peniaze...
{8978}{9057}Po druhé, MacDougall. Zdá sa,|e jeho loï bude na pretekoch. 
{9062}{9145}Váne? Myslíš toho MacDougala? 
{9159}{9261}Nemám iaden konkrétny dôkaz,|ale videl som loï, ktorá vyzerala ako tá jeho... 
{9263}{9317}...v správach, keï ukazovali lode,|ktoré budú na pretekoch. 
{9320}{9362}Ale to niè neznamená! 
{9376}{9423}Nikdy nezabudnem na tú loï. 
{9430}{9480}Chcem vstúpi do závodov, aby som sa uistil.
{9494}{9571}Tak, teraz viem preèo,|ale èo bude s tım ako? 
{9579}{9604}Poièa si? 
{9667}{9753}Riadim sa zásadou,|"Nepoièiavaj sebe ani nikomu inému". 
{9810}{9874}Sú to tri wongy, však?|Platím svoj podiel úètu. 
{9899}{9935}Hej, kam ideš? 
{9952}{10075}Nezujímajú ma vesmírne preteky,|a nie je tu niè, s èím by som mohla pomôc, pravda?
{10087}{10164}Keï závody skonèia, ohlásim sa vám. 
{10173}{10200}Neunúvaj sa! 
{10222}{10255}Urèite? 
{10273}{10307}Je to jej rozhodnutie. 
{10309}{10350}Tak, èo budeme robi? 
{10351}{10397}Myslím, e budeme musie ís tam. 
{10403}{10441}Ha? Kam? 
{10442}{10512}Sídlo Luo Company. 
{10563}{10628}Ale, ale! Gene a Jim! 
{10636}{10706}Musel to by osud,|ktorı nás znovu zviedol dokopy! 
{10720}{10779}Som prekvapenı, e si prišiel na Heifong.
{10791}{10865}Myslel som, e prevádzkovanie|poboèiek nechávaš na inıch. 
{10869}{10956}Naozaj by som mal ïakova bohovi obchodu.
{11052}{11164}Sme tu kvôli biznisu, Fred. Je to tak,|ako som vysvet¾oval cez telefón. 
{11167}{11246}Iste, rád a budem sponzorova. 
{11253}{11270}Naozaj?! 
{11271}{11319}Je to dobrá reklama, aj pre nás. 
{11326}{11395}Ak vyhráš peniaze,|vyriešime všetky tvoje vıdavky. 
{11405}{11495}"Vyhra peniaze"?|To keï skonèím medzi prvımi troma, e? 
{11500}{11598}Veru. Ak skonèíš štvrtı alebo nišie,|budeš mi dli ešte viac. 
{11607}{11653}Vidíš? Èo som ti vravel, Gene? 
{11656}{11686}To je v pohode, Jim. 
{11700}{11747}Fajn, sme dohodnutí. 
{11752}{11825}S osobnımi vıdavkami to vyjde|na 400 000 wongov, tak ich maj pripravené. 
{11833}{11893}Som pripravenı u dávno. 
{12051}{12081}Èo je to? 
{12165}{12274}Keï budete na stupni víazov chcem,|aby ste obaja mali obleèené toto. 
{12285}{12392}Ak to ¾udia uvidia na stupni víazov,|tıch 400 000 bude ako zadarmo. 
{12401}{12438}Vidíš? Èo som ti vravel, Gene? 
{12443}{12487}Máme snáï na vıber? 
{12497}{12557}Melfina si nemusí obliec niè? 
{12566}{12692}Gene, nemyslím, e by si ju mal|predvádza na verejnosti. 
{12723}{12778}Èo vieš, Fred? 
{12786}{12821}Niè moc. 
{12829}{12964}Akurát, e piráti Kei h¾adajú teba a obzvláš ju. 
{12973}{13036}Pokúšaš sa nás zapreda? 
{13039}{13069}Kdeeby. 
{13076}{13158}Pokraèova s tebou v obchode je ove¾a vınosnejšie.
{13176}{13215}Nesklameme a. 
{13226}{13266}Rátam s vami. 
{13275}{13357}Maj sa, Fred. Ui si sledovanie závodov.
{13366}{13407}Kedy to vlastne zaèína? 
{13418}{13452}Za 30 hodín. 
{13462}{13500}No, máme toho ve¾a na práci. 
{13650}{13710}Nepokazte to. Rátam s vami. 
{13720}{13822}Hej, nikdy by som nepomyslel,|e ma budete povzbudzova. 
{13832}{13895}Myslel som, oplati lásku mladého pána k vám. 
{13903}{13933}Hej, iste... 
{13966}{14020}Outlaw Star, tu riadiaca vea. 
{14029}{14079}Negatívny návrat je potvrdenı. 
{14101}{14184}Tu Outlaw Star. Negatívny návrat potvrdenı.
{14194}{14265}Takto by veru mali vyzera planetárne štarty.
{14269}{14329}Rozvinuté mestá sú úasné. 
{14333}{14421}Mono, ibae parkovné stálo hodne|a to sme tam boli len pol dòa! 
{14427}{14470}Bez peòazí nemôeš robi niè. 
{14476}{14549}Ale ak sa k nejakım peniazom dostaneš,|tak môeš takmer všetko. 
{14555}{14587}Takı je Heifong. 
{14592}{14662}Teraz zobrazujem trasu k|urèenej štartovnej pozícii. 
{14679}{14698}Jasné. 
{14703}{14752}"Štartovná pozícia?" 
{14764}{14835}Gilliam, máš podrobné mapy okolia Heifongu?
{14837}{14931}Moja kninica sa vyrovná tej,|na kríniku Vesmírnych jednotiek. 
{14942}{14971}Tak ich priprav. 
{14975}{15015}Onedlho ich budeme potrebova na závodoch.
{15023}{15061}Èoe? Aké závody? 
{15063}{15180}A ešte stále ste nevysvetlili,|preèo s vami nie je Suzuka. 
{15202}{15254}Vysvetlím neskôr. 
{15483}{15527}Nevidím jeho loï. 
{15535}{15573}Rozoznáš to odtia¾to? 
{15580}{15612}Keby tu bol, vedel by som. 
{15614}{15645}Keby, heh...? 
{15746}{15829}Oh, dobre.|Chceš sa pozrie na predzávodnú párty? 
{15831}{15851}Uhm. 
{15903}{15965}Mel sme nechali na lodi, ale si si istı,|e je to v poriadku? 
{15968}{16012}Mám obavy z toho, èo povedal Fred, 
{16017}{16081}ale ona povedala, e tam chce zosta,|take myslím, e to je okej. 
{16088}{16173}Tak jej prinesme nejaké jedlo z párty ako suvenír. 
{16249}{16368}Gilliam, môeš mi sprístupni|najväèšiu databanku na Heifongu? 
{16384}{16469}To bude pravdepodobne Dailongská Univerzita.
{16472}{16509}Okamih, prosím. 
{16523}{16593}Na èo by ste sa radi pozreli? 
{16597}{16631}Na seba. 
{16635}{16694}Na vás? Èo tım myslíte? 
{16706}{16830}Hocijakú stopu. Kto som?|Preèo som bola vytvorená?
{16844}{16879}Chcem to vedie. 
{16909}{17080}Rozmıš¾a o sebe mi nie je dovolené,|ale dokáem pochopi ako sa cítite. 
{17093}{17161}Urobím všetko, èo je v mojich silách. 
{17194}{17219}Ïakujem. 
{17221}{17314}Heifongské vesmírne závody práve vstúpili|do svojho trinásteho roèníka... 
{17319}{17413}a stali sa skutoène populárne,|s doteraz najväèšou úèasou, 
{17417}{17562}pozostávajúcou z 13 firemnıch lodí|a 29 súkromnıch lodí súaiacich o víazstvo. 
{17575}{17637}Ktovie, èi tu je? 
{17650}{17742}Celkovo 40 lodí sa zúèasòuje|èisto len kvôli sláve... 
{17748}{17851}...v tomto vyèerpávajúcom, nebezpeènom závode,|èo je naozaj-- 
{17855}{17929}H¾ada ho k nièomu nevedie. Nevieš ako vyzerá.
{17938}{17967}Iste, ale... 
{17969}{18075}Pozri, zaplatili sme ve¾ké prachy, aby sme|mohli závodi, tak nech to stojí za to. 
{18079}{18139}Daj si! Toto je fakt dobré! 
{18142}{18166}Aah... 
{18269}{18316}Dali by ste si nejakı nápoj, pane? 
{18376}{18450}Hej, zlato. Môem tie dosta drink? 
{18455}{18475}Áno! 
{18481}{18519}Som smädnı, obzvláš-- 
{18714}{18736}Èau. 
{18789}{18845}Našla som a, Gene Starwind! 
{19166}{19183}Èau. 
{19223}{19298}Našla som a! Našla som a! Našla som a!
{19323}{19354}Èo tu robíš? 
{19359}{19431}Toto je boie riadenie Boha Ctarlov...! 
{19440}{19498}Vïaka ti, Boe všetkıch Ctarlov! 
{19534}{19632}Aj bez peòazí z Impéria som bola|rozhodnutá a vystopova, 
{19635}{19702}a tak som jazdila stopom celım vesmírom.
{19711}{19773}To si celú cestu sem išla stopom?! 
{19779}{19866}Bolo to aké... Išla som tam,|kam mali lode namierené, 
{19870}{19938}a na palube ma oèakávala tvrdá práca. 
{19946}{20010}Išla som ïalej a ïalej,|a som skonèila tu, na Heifongu, 
{20012}{20115}a bola som vïaèná, e som dostala|túto prácu servírky, aby mala aspoò na jedlo. 
{20121}{20182}A práve keï som lamentovala nad svojím nešastím,
{20243}{20335}kto inı sa predo mnou objaví, ak nie vy dvaja?!
{20344}{20390}Teda, nemôem uveri nášmu šastiu... 
{20399}{20431}Je to smiešne. 
{20437}{20513}Prestaòte tára! Teraz buïte takí dobrí a--
{20515}{20547}Ovládajte sa, Aisha! 
{20672}{20710}Oh! Uh, šéf! 
{20712}{20785}Um... Títo dvaja bastardi, páni,|chcem poveda--
{20791}{20834}Vaše ospravedlnenia si vypoèujem neskôr.
{20863}{20938}Prestaòte! Pustite ma! 
{20945}{21015}Ak zapríèiníte ešte ïalšie scény,|nedostanete zaplatené! 
{21087}{21127}Ve¾mi ma to mrzí, páni. 
{21143}{21187}To je v poriadku, niè sa nestalo. 
{21224}{21323}Nebolo dos údajov, aby sa dalo pokraèova.
{21371}{21428}Iste. Rozumiem. 
{21431}{21518}Mohli by sme sa pokúsi preveri pirátov|prostredníctvom Vesmírnych jednotiek, 
{21527}{21582}ale mohlo by to by obtiane. 
{21595}{21646}Netráp sa, Gilliam. 
{21647}{21733}Neèakala som, e sa dozviem všetko hneï naraz.
{21743}{21845}Áno. Som si istı, e sa|nakoniec dostaneme na správnu stopu. 
{21853}{21930}Istee. Gene mi to tie s¾úbil. 
{21936}{22055}S¾úbil vám to? Ah, keï u o òom hovoríme,|práve sa vrátili. 
{22079}{22101}U sme tu! 
{22102}{22148}Tu máš, Mel, priniesli sme ti nieèo! 
{22161}{22184}Pre mòa? 
{22186}{22205}Uhm! 
{22210}{22278}Tak, potrebujeme zásobi loï,|spravi údrbu a trochu si odpoèinú. 
{22279}{22342}Je dvanás hodín do štartu. Dajme sa do práce.
{22353}{22374}Áno! 
{22378}{22401}"Štart?" 
{22431}{22587}Štart 13. Heifongskıch vesmírnych závodov|je takmer tu! 
{22599}{22677}Zúèastnené lode sa jedna za druhou|zhromaïujú na štartovnej pozícii! 
{22685}{22779}Ktorı tím získa veniec víazstva? 
{22808}{22923}Vyráame odtia¾to, z Heifongu IV|a najprv zamierime k 3. planéte, Heifongu III. 
{22939}{22980}Vraj je to podvojná planéta! 
{22997}{23067}Fakt vybrali nepríjemné miesto|na kontrolnı bod... 
{23074}{23118}Ïalej je to ešte horšie. 
{23127}{23201}A potom obená dráha okolo 5. planéty,|tohto plynového oblaku. 
{23205}{23262}A potom prejs tımto pásom asteroidov. 
{23268}{23354}Uvádza sa, e mono vyui|kontrolnı bod na 2. alebo 1. planéte. 
{23360}{23413}Cesta k druhej planéte je dlhšia, 
{23419}{23482}ale cesta k prvej planéte je o trochu nebezpeènejšia.
{23494}{23554}A potom sa vraciame spä na Heifong, e?
{23563}{23623}Je to vılet asi na 1,6 miliardy kilometrov.
{23632}{23696}Keï u sme na tıch závodoch,|môme ich vyhra, Gene! 
{23706}{23750}Aké nadšenie! 
{23757}{23870}iadna loï sa nevyrovná Outlaw Star. 
{23873}{23948}Okej, ukáme im, èo Outlaw dokáe! 
{23966}{24028}Doeniem a, MacDougall! 
{24034}{24055}Gene! 
{24063}{24131}Pamätaj si len, e ak neskonèíme medzi|prvımi troma, všetko je to naniè. 
{24139}{24165}Viem to. 
{24171}{24201}Keï vravíš. 
{24215}{24276}Ale ak skonèíme medzi prvımi troma,|máme 400 000 wongov, 
{24278}{24358}a keï odrátame vstupnı poplatok a ostatné,|zostáva 200 000! 
{24399}{24458}Lode budú štartova jedna za|druhou v dvojminútovıch intervaloch. 
{24462}{24538}Prvá loï sa teraz pribliuje|k štartovnej bráne! 
{24546}{24616}Je to súkromník, veterán,|ktorı súail v poslednıch šiestich závodoch. 
{24618}{24685}Je to Blue Continental,|pilotuje ju Ernest Blue! 
{24699}{24785}Všetky systémy v poriadku,|vıkon motorov je stabilnı. 
{24800}{24873}Sme a 26. Chví¾u to potrvá. 
{24887}{24952}Loï èíslo 7 je trochu neobvyklá. 
{24959}{25056}Pán Nubata Kunono, obchodujúci tu,|na Heifongu, pozdravuje od Ctarl-Ctarl. 
{25067}{25111}Jeho loï je Niburu-Boribori. 
{25127}{25178}Povedal, e to je loï Ctarl-Ctarl! 
{25179}{25204}Eh? 
{25220}{25342}Uhm, dôstojníèka Aisha...|Môme absolvova |tieto vesmírne závody normálne? 
{25347}{25403}Kım vám nedám rozkaz,|môete si robi, èo chcete. 
{25413}{25486}Ale povaujte moje rozkazy za rozkazy z Impéria.
{25491}{25510}Áno! 
{25550}{25606}Èo, do èerta, robí imperiálna vyslankyòa|tu na Heifongu? 
{25611}{25695}Nemáme na vıber... Musíme poslúchnu Impérium!
{25706}{25762}Len sa dívajte! 
{25783}{25829}Tak teda odštartujeme. 
{25839}{25951}Newtonov reaktor a jednotka|gravitaèného cyklu sa zapínajú. 
{25961}{26026}Oh, zdá sa, e to stihol práve vèas! 
{26033}{26132}El Dorado, ktorá prišla neskôr,|to stihla do štartovného èasu! 
{26183}{26280}El Dorado, ktorá sa minulı rok umiestnila|ako piata, je tohtoroènım favoritom! 
{26284}{26327}Jej kapitánom je Harry William! 
{26346}{26412}"William?" To nie je MacDougall? 
{26471}{26576}Prepáète, cestou sem ma zastihla|éterová búrka. 
{26590}{26669}El Dorado má urèenı èas štartu za sedem minút.
{26676}{26702}Zvládnete to? 
{26703}{26722}Iste. 
{26726}{26759}Ve¾a šastia, teda. 
{26923}{27035}Harry, prichádza sem vysielanie.|Vraví, e je na Outlaw Star. 
{27043}{27126}Nepoznám takú loï. Ignoruj to.|U je takmer èas vyštartova. 
{27131}{27169}Sakra, on neodpovedá! 
{27175}{27242}Outlaw Star, otvorenı kanál|na štartovnej pozícii... 
{27244}{27292}...je len na sluobné úèely.|Prosím, rešpektujte to. 
{27298}{27376}Take, El Dorado mieri k štartovnej bráne!
{27393}{27453}Spusti motory! Chcem sa dosta k tej lodi!
{27458}{27510}Usporiadatelia nás urèite zastavia. 
{27514}{27615}Gene, nerob iadne hlúposti.|Nie je isté, èi je to tá loï. 
{27662}{27690}Hej, myslím, e máš pravdu. 
{27710}{27787}Je to dlhı závod. Urèite dostanem šancu,|aby som sa ubezpeèil. 
{27820}{27867}El Dorado, je èas vyštartova. 
{27893}{27941}Vpred! A choï naplno. 
{28161}{28232}Za Bonapartem, sponzorovanım|Penelope Corporation... 
{28238}{28305}...je Outlaw Star, súkromník,|súaiaci po prvı krát. 
{28307}{28358}Kapitánom je Gene Starwind. 
{28462}{28518}Dvadsatisíc na Outlaw Star. 
{28700}{28739}Poèka, tá loï... 
{28741}{28799}Deje sa nieèo, profesor Khan? 
{28814}{28882}Nie, nie. Vôbec niè. 
{28887}{28922}To je v poriadku. 
{29013}{29122}Niet pochıb, tá loï je XGP15A-2... 
{29138}{29180}Ale preèo? 
{29223}{29275}Toto je posledná kontrola.|Ste pripravení?
{29286}{29319}Všetko v poriadku. 
{29370}{29446}Take, Outlaw Star,|je èas vyštartova. 
{29502}{29527}Štart! 
{29809}{29875}Na Heifong III je to|230 miliónov kilometrov.
{29882}{29944}ETA je pribline 1000 hodín, 
{29951}{30014}Prosím, prenechajte ovládanie|autopilota na mòa. 
{30019}{30074}Všetky pomalé lode zanechaj v prachu! 
{30080}{30110}Samozrejme! 
{30212}{30258}Prešlo 14 hodín od zaèiatku závodov... 
{30260}{30331}...a prvé lode u dosiahli|prvı kontrolnı bod. 
{30340}{30385}Bonaparte je momentálne vo vedení, 
{30386}{30449}a práve prechádzajú kontrolnım bodom|jedna za druhou! 
{30463}{30507}Èo zdralo Genea? 
{30517}{30583}Vyštartovali uprostred skupiny,|koniec koncov. 
{30657}{30726}Prispôsobím obenú rıchlos Heifongu III.
{30737}{30771}Teda, to je úasné! 
{30775}{30812}Kontrolnı bod je... 
{30889}{30929}Uvádza sa, e je priamo uprostred! 
{30942}{31020}Zaznamenal som ïalšie lode zrıch¾ujúce|nad rovinou otáèania. 
{31034}{31097}Zdá sa to by ašia oblas,|ne naznaèovali údaje. 
{31099}{31154}Existujú dve cesty, zobrazím ich. 
{31166}{31272}Môeme prejs vertikálne|vzh¾adom na rovinu otáèania. 
{31284}{31322}To presne robia ostatné lode. 
{31337}{31406}Druhá monos je vysledova otáèanie planét...
{31413}{31486}... a preletie priamo cez kontrolnı bod.
{31498}{31524}Èo je rıchlejšie? 
{31533}{31596}Ís vertikálne je pravdepodobne bezpeènejšie.
{31604}{31677}Nemuseli by sme prekríi orbit planéty.
{31687}{31722}Èo je rıchlejšie? 
{31731}{31758}Ís priamo skrz. 
{31771}{31814}Pôjdeme teda priamo skrz! 
{31823}{31846}Tak moment! 
{31851}{31915}Je tu príliš ve¾a faktorov,|vrátane vplyvu gravitácie planét, 
{31923}{31997}ich obenej rıchlosti a magnetizmu! 
{32010}{32083}Pozri, je to ako skáka cez švihadlo,|akurát e s planétami! 
{32087}{32118}Môeme to dokáza, ak pôjdeme hneï teraz!
{32127}{32154}Poïme na to! 
{32171}{32263}Tak moment! Keï sú planéty|Heifongu III blízko seba, 
{32267}{32374}nastáva prílivovı efekt|a spustia sa striedavé vlny! 
{32382}{32427}Aké vlny? Morské? 
{32429}{32482}Ak to chcete niekam zatriedi,|tak skôr kovové.
{32494}{32525}Ja niè nevidím! 
{32535}{32603}Vstúpili sme do oblasti medzi dvoma planétami.
{32693}{32751}Prerazíme skrz! Do toho! 
{32818}{32861}H-Hej, èo je to? 
{32867}{32985}Upozornenie. Od prvej planéty|sa pribliuje rozmernı objekt. 
{32990}{33027}Èo tım myslíš, "rozmernı"? 
{33038}{33074}Je to pravdepodobne vlna. 
{33159}{33190}Uká mi únikovú cestu! 
{33191}{33216}iadna nie je. 
{33221}{33247}Èoe?! 
{33254}{33334}Gene, kontrolnı bod!|Bude pohltenı! 
{33695}{33842}Oto no nai mahiru... 
{33846}{34013}...kaze wa tada akarui. 
{34016}{34325}Sukoshi nemutasou ni|hanabira ga yureta.
{34355}{34546}Nanigenai kono omoi, 
{34554}{34937}nee, hito wa donna|kotoba de yonde iru no?
{34952}{35246}Shiroi suna no tsuki,|tojikometa hanashi o... 
{35252}{35578}...hikarifurasu you|ni kikasete ne, sotto.
{35711}{35768}Koneène som a chytil,|MacDougall! 
{35783}{35893}Tento mu sa správa ve¾mi milo,|ale rozhodne to je podozrivé... 
{35902}{35954}Teda, tie dnešné decká sú hrozné! 
{35963}{36052}A to maèacie dievèa sem príde uprostred pretekov!
{36056}{36098}To má by vzrušujúce, alebo èo?! 
{36107}{36193}Kadopádne, Outlaw sa enie vpred,|za vidinou víazstva! 
{36207}{36308}Nabudúce v Outlaw Star!|"Stratení v subpriestore!"
{36322}{36379}Radšej sa pripravte! 
