{1}{1}23.976
{122}{202}Éterovı tok naráa na boky lodí.
{230}{310}Hviezdy planú, bièované búrkami.
{350}{431}Dravé prúdy z hlbín|ich prekonávajú.
{446}{534}Vyvrhnuté zvyšky planét|preráajú cez ich trupy.
{566}{626}Ale je jedno ko¾ko tísícok lodí|sa zmení na trosky...
{644}{735}...alebo ko¾ko desatisícov ivotov|sa stratí v prázdnote,
{763}{832}lode neprestávajú pláva do tohto mora.
{852}{926}Plavcov, ktorí sa po òom|chcú plavi je stále ve¾a.
{955}{1145}To preto, lebo aj dnes ich v tom|nekoneènom mori oèakávajú nepreskúmané oblasti.
{1303}{1385}Neobviòuj to, neniè to, nepodceòuj to...
{1387}{1505}...to nieèo jedineèné, èo kadı má.
{1522}{1546}Moja láska...
{1547}{1570}Moje sny...
{1572}{1597}A tie ty.
{1599}{1742}Nevzdám sa toho, za iadnu cenu.
{1800}{1897}V tie noci, keï si nepokojnı,|nech robíš èoko¾vek,
{1902}{2010}...máš chu to všetko odhodi preè.
{2014}{2113}Nevrav u niè, len otvor dvere.
{2116}{2221}Nemám èas sa tu|s tebou bavi.
{2226}{2335}Chcem sa tadeto vo¾ne preletie,
{2345}{2435}a nedba pritom na opatrnos!
{2442}{2534}O niè som neprišiel,
{2536}{2621}veï som ešte ani nezaèal.
{2638}{2718}Neobviòuj to, neniè to, nepodceòuj to...
{2721}{2840}...to nieèo jedineèné, èo kadı má.
{2856}{2884}Moja láska...
{2886}{2913}Moje sny...
{2914}{2933}A tie ty.
{2937}{3056}Nevzdám sa toho, za iadnu cenu.
{3085}{3108}Èo by si chcel?
{3110}{3135}Èo chceš robi?
{3137}{3189}Kam pôjdeš?
{3192}{3347}Schmatni, èo chceš, pretni temnotu,|keï budeš uteka nocou!
{3502}{3526}Uká mi únikovú cestu!
{3527}{3548}iadna nie je.
{3555}{3578}Èoe?!
{3660}{3706}V takom prípade bude pohltenı!
{3725}{3770}Zostáva nám akurát prehna sa|tade plnou rıchlosou!
{3818}{3849}To je šialené!
{3862}{3913}Myslel som si,|e si najrıchlejšia loï v galaxii!
{3927}{4021}Vıkon motorov 108%.|Všetky motory vykazujú normál.
{4033}{4069}Ideme na to!
{4303}{4327}Dokázali sme to!
{4380}{4480}BillSK & Pedro uvádzajú:|OUTLAW STAR:"Stratení v subpriestore!"
{4498}{4565}Ešte nie sme mimo orbitu planét.
{4573}{4655}Ale najprv, prosím,|vráte vıkon motorov na normálnu úroveò.
{4662}{4724}Teda, ty sa musíš saova na všetko, e?
{4769}{4832}Prešli ste kontrolnım bodom 1, Outlaw Star.
{4846}{4897}Avšak vystrájali ste tam riadne kúsky.
{4909}{4943}Na ktorom sme mieste?
{4956}{4999}Predbehli ste dvanás lodí.
{5007}{5081}Pred vami je 13 lodí,|ale pod¾a vášho èasu ste šiesti.
{5082}{5133}Po tom všetkom,|to sme len šiesti...?
{5142}{5198}Nie ste jediní,|kto si zvolil tú cestu.
{5211}{5286}Ale ste jediní,|kto to stihol pred tou vlnou.
{5292}{5350}Povedal som si, e spravím|preteky trochu vzrušujúcejšie.
{5357}{5418}Iste. Tak teda, ve¾a šastia.
{5443}{5555}Ïalšia je piata planéta, Heifong V.|Vzdialenos asi 500 miliónov kilometrov.
{5558}{5634}Poïme do subéteru a preskoème ten úsek.
{5638}{5706}Loï Outlaw Star,|ktorá neèakane poskoèila v poradí,
{5709}{5783}keï dosiahla prvı kontrolnı bod,|je momentálne na šiestom mieste!
{5790}{5851}Èo myslíte, e sa stane ïalej,|pán Ishigaki?
{5853}{5936}Dobrá otázka. Outlaw Star,|teraz šiesta, je jednoznaènım prekvapením.
{5988}{6085}Spravi jedinı okruh okolo tohto|je ¾ahkı kontrolnı bod, e, Jim?
{6177}{6205}Hej, Jim!
{6230}{6299}Vydr, Jim. U sme takmer|na servisnej stanici.
{6379}{6405}Hej, máš pravdu.
{6406}{6510}Mali by sme sa natiahnu aspoò|na hodinu a spravi údrbu.
{6514}{6576}Všetky systémy ukazujú normál.|Všetko v poriadku.
{6585}{6685}V tom prípade, vykonajme údrbu|na sebe. Poïme si nieèo zajes.
{7267}{7345}To je tá loï. Koneène som ho dostihol.
{7582}{7655}Vy ste posádka z El Dorada?
{7674}{7730}Tak je. Kto ste?
{7733}{7780}Ktorı z vás je MacDougall?
{7812}{7845}Nie je tu nikto s takım menom.
{7857}{7890}Istee je.
{7897}{7963}El Dorado je loï bratov MacDougallovcov.
{7973}{8032}Nemám potuchy o èom rozprávate.
{8043}{8073}O kom to hovoríte?
{8082}{8110}Nerob blbého!
{8125}{8206}Nezdá sa, e by tu bol ten chlap,|s ktorım hovorila Hilda,
{8223}{8294}ale spoznávam tú loï!
{8329}{8414}To je tá loï, èo na nás zaútoèila|pri Farfallase.
{8443}{8480}O èo sa to tu snaíš, bastard?
{8490}{8528}Pusti Harryho!
{8530}{8578}To netreba, Terry, Leo.
{8590}{8655}Pozrite, neviem o èom to hovoríte.
{8665}{8719}Nikdy som nebol na "Farfallase",|èi èo to je.
{8730}{8811}Preèo piráti Kei h¾adajú XGP?
{8819}{8898}Preèo ste sa vy pokúšali XGP znièi?
{8914}{8986}Ak sa budete snai vyvola bitku,|zavolám usporiadate¾ov pretekov.
{8993}{9093}Len zavolaj.|Ale chytrejšie by bolo vyhovie mi.
{9100}{9166}Kde ste kto!|Tento chlap narúša závody!
{9179}{9207}Je tu nejakı problém?
{9210}{9317}Kdee, rozprával mi len|o špecialitách podniku, však?
{9323}{9425}Nu, radšej u pôjdem.|Špeciality musia poèka nabudúce.
{9553}{9595}Hej, Harry, o èo mu išlo?
{9597}{9624}Vydr.
{9646}{9761}Ten jeden... Nemôem tomu uveri.|Preil Farfallas?
{9797}{9841}Sú nejaké problémy?
{9862}{9909}Nie, to niè nie je.
{9937}{10008}Dos mi to nahnalo strach,|keï som sa díval, Gene.
{10016}{10078}Nešiel si na to moc priamo?
{10093}{10150}Jedine, ak by to nebol MacDougall.
{10167}{10237}Ale ak je, u nás viac|nemôe ignorova.
{10253}{10298}Skontaktuje sa.
{10302}{10354}Tá loï práve štartuje.
{10438}{10466}Kedy môme vyštartova?
{10478}{10509}A za 11 minút.
{10518}{10559}Len, èo ho dostihnem,|tak to s ním vybavím.
{10586}{10676}Do pozornosti všetkım lodiam.|Dostali sme správu, e sa formuje éterovı prúd,
{10679}{10776}ktorı sa tiahne od Heifongu V|a ku kontrolnému bodu 4A na Heifongu I.
{10790}{10855}Odporúèa sa poui|kontrolnı bod 4B na Heifongu II.
{10865}{10906}- Opakujem...|- Poèul si ho.
{10908}{10950}Všetko závisí od El Dorada.
{11030}{11127}Leo, daj mi úradné záznamy o lodi,|ktorá odchádza po nás.
{11134}{11160}Okej.
{11256}{11311}Je to XGP?
{11319}{11399}Loï na poslednom mieste práve dosiahla|2. kontrolnı bod.
{11404}{11482}Dve lode práve odstúpili kvôli|problémom s motormi...
{11498}{11546}Kde myslíte, e je Gene?
{11558}{11649}Toto vysielanie je fakt zlé|pokia¾ ide o informácie o súkromnıch lodiach.
{11650}{11717}Tretím kontrolnım bodom je|Lione Lagrange Point,
{11719}{11773}ktorı je 140 miliónov kilometrov od Heifongu V!
{11790}{11869}Sleèna Aisha? Za okamih dosiahneme 3. kontrolnı bod.
{11885}{11915}Èo je tam?
{11934}{12018}Hovorí sa, e kedysi dávno|obiehal okolo Heifongu V satelit,
{12034}{12116}ktorı bol znièenı|a jeho kusy sa tam nahromadili.
{12125}{12159}Uber rıchlos.
{12169}{12215}Ako keby som nevedel...
{12386}{12413}Je tvoja, Harry!
{12419}{12489}Neby mojej zruènosti,|nikdy by sme nezískali to¾ko èasu!
{12644}{12688}Deje sa nieèo, sleèna Aisha?
{12698}{12751}H¾adám miesto na uskutoènenie prepadu.
{12754}{12801}- Èo? Prepad?|- Èo? Prepad?
{12809}{12837}Pripravte sa na boj!
{12841}{12881}- Èo? Boj?|- Èo? Boj?
{12886}{12982}Táto loï teraz vykoná|prekvapivı útok na Outlaw Star!
{13043}{13105}S jedinım gu¾ometom?
{13109}{13148}Jedinı gu¾omet...?
{13170}{13224}A èo vaše Guriguri strely|alebo Gagagan kanón?!
{13229}{13277}S nièím takım nie sme vybavení!
{13285}{13335}A tomuto vravíte imperiálna loï?!
{13340}{13417}Niburu Boribori je loï|na obchodovanie s Heifongom!
{13490}{13566}Neviem aké rozkazy ste dostali|z Impéria, sleèna Aisha,
{13574}{13620}ale zaútoèi s touto loïou|na nieèo je beznádejné.
{13626}{13662}Nemôem tomu uveri...
{13670}{13745}Dobre teda, je èas na posledné riešenie!
{13782}{13801}Tam je to!
{13811}{13886}Hustota éteru stúpa a nepravidelne kolíše.
{13898}{13979}Chyba subpriestorového radaru|stúpla na 24%...
{13987}{14058}a úèinnı dosah štandardného radaru|zas klesol o 30%.
{14078}{14136}Musíme sa obís bez prístrojov|a spo¾ahnú sa na vlastné oèi.
{14141}{14193}Tak potom uvidíte, akı dobrı naozaj som.
{14229}{14271}Spoma¾, Gene!
{14285}{14319}Ja viem!
{14341}{14393}Súèasná rıchlos je 12 km/s.
{14409}{14528}Nasledujúcich 180 km je prázdno.|Potom tam vidím nejaké ve¾ké asteroidy.
{14538}{14579}Aká je najkratšia cesta|ku kontrolnému bodu?
{14586}{14645}Prosím, zmeò kurz o jednu hodinu dole.
{14650}{14676}Rozumiem.
{14808}{14824}Tam je to!
{14838}{14864}Poïme na to!
{14980}{15019}Kontrolnı bod dosiahnutı!
{15021}{15042}Fajn!
{15046}{15101}Teraz nám akurát zostáva|rıchlo stadeto vypadnú!
{15131}{15158}Mayday! Mayday!
{15165}{15232}Tu je Niburu Boribori!|Zrazil som sa s asteroidom!
{15239}{15295}Opustil som loï kvôli|monosti vıbuchu!
{15298}{15319}iadam o pomoc!
{15322}{15349}iadam o pomoc!
{15362}{15402}To je SOS.
{15424}{15479}Zaznaèil som jeho polohu.|Dám to na obrazovku.
{15557}{15599}Èo urobíme, Gene?
{15601}{15670}Myslím, e usporiadatelia|pretekov ho onedlho vyzdvihnú.
{15723}{15757}Pomôeme mu.
{15761}{15825}To... sa ti vôbec nepodobá, Gene.
{15832}{15950}Nie je to iadna sranda|plavi sa vesmírom úplne sám.
{16153}{16186}Vidíš ho, Gene?
{16190}{16209}Hej.
{16246}{16268}Kruci...
{16270}{16295}Èo je, Gene?
{16325}{16368}Mám trochu závra...
{16380}{16410}Budeš v poriadku?
{16418}{16470}Hej, poradím si s tım.
{16549}{16601}Okej, budete v pohode.
{16686}{16729}Vyrovnávanie tlaku skonèené.
{16777}{16857}Boli ste jedinı èlen posádky|alebo sú tam aj ïalší?
{16949}{17001}Tentokrát mi neujdeš!
{17023}{17061}Èo ty tu robíš?!
{17108}{17188}Produkcia: BillSK|Spracovanie videa: Randy
{17190}{17252}Slovenské titulky: Pedro (pedro_k@post.sk)
{17254}{17380}Nie je urèené pre komerèné pouitie.
{17404}{17538}Fakt? Tí MacDougallovci naozaj|majú k¾úè ku Galaktickému Leyline?
{17548}{17632}Prinajmenšom majú|viac informácií o Hilde ako ja.
{17640}{17751}Ty váne nevieš niè|o Galaktickom Leyline?
{17761}{17821}Keby som vedel,|u by sme tam dávno išli.
{17832}{17909}Pozri, keï nieèo nájdeme,|povieme ti.
{17918}{17950}Take si niekde vystúpiš z lode, ok?
{17954}{18041}Kdee!|Nemôem sa takto vráti do Impéria!
{18048}{18110}Nemôem sa vráti!|Povaovali by ma za úplne neschopnú!
{18122}{18165}Vy ste moja jediná stopa.
{18169}{18227}Kım nieèo nezískam, neodídem!
{18233}{18273}Èo chceš robi, Gene?
{18290}{18333}By u ien ob¾úbenı nie je ¾ahké...
{18335}{18370}To som nemal na mysli.
{18392}{18498}Toto je divná loï.|Nepohla by sa bez toho, aby si nebola nahá?
{18502}{18575}Totálne zaostáva za hocijakou|loïou Ctarl Ctarl.
{18582}{18669}Ako sa to opovauješ rozpráva|o najrıchlejšej, najdokonalejšej lodi v galaxii!
{18670}{18725}Èo? Èo je to?
{18729}{18808}Ja nie som "to". Volaj ma,|prosím, Gilliam.
{18834}{18885}Èoe--? To je poèítaè?
{18914}{18958}Kadopádne,|vráme sa spä k pretekom.
{18969}{19065}Môj plán dostihnú El Dorado|je u urèite v ahu.
{19078}{19149}Kruci, ukáe sa jedno|maèacie dievèa a všetko je v keli.
{19152}{19225}Ak neskonèíme tretí alebo lepšie,|budeme ešte viac zadåení.
{19234}{19333}Teraz pripravujem vstup do subéteru.|Prosím, nastavte opravu kurzu.
{19346}{19368}Rozumiem.
{19374}{19450}Odhadovanı èas vstupu do subéteru, 24 minút.
{19479}{19505}Nevidím!
{19577}{19643}Po dosiahnutí 3. kontrolného bodu|odstúpili tri lode,
{19649}{19718}take k 4. kontrolnému bodu mieri|len 35 lodí.
{19726}{19745}Ïalej--
{19807}{19901}Celé toto cestovanie ma vyèerpalo,|idem si zdriemnu.
{19906}{19945}Zobuïte ma, keï tam budeme, hej?
{19956}{19985}Hej, ako chceš...
{20082}{20129}Teraz prepínam na subéterovı pohon.
{20138}{20193}Vıkon Munchausenovho reaktoru stúpa.
{20203}{20257}Prahová hodnota éteru dosiahnutá.
{20294}{20359}Kurz zadanı.|Relatívne súradnice potvrdené.
{20430}{20473}Teraz vytváram subéterovú bublinu.
{20573}{20630}Ah, buï ticho...
{20638}{20753}Zo zadu sa blíia nejaké objekty.|87% pravdepodobnos, e sú to strely.
{20757}{20816}Ja to nechápem!|Myslel som, e za nami nikto nie je!
{20823}{20856}Kadopádne, oplame im to!
{20864}{20919}Prechádzame do subéterového módu.|Nie je to moné.
{20934}{20974}Ko¾ko ešte, kım vôjdeme do subéteru?
{20978}{20999}Osemnás sekúnd.
{21005}{21053}Strely narazia za 16 sekúnd.
{21098}{21128}Strasiem sa ich!
{21188}{21225}Èo sa deje?
{21236}{21279}Prípravy na skok|do svetelnej rıchlosti ukonèené.
{21281}{21335}Prienik do subéteru za osem,
{21337}{21356}sedem,
{21358}{21377}šes,
{21381}{21400}pä,
{21404}{21422}štyri,
{21427}{21441}tri,
{21452}{21465}dva,
{21477}{21489}jedna...
{21500}{21536}- Nula.|- Dokáeme to!
{21951}{22009}Sakra, Harry! To bolo ohromné!
{22032}{22109}Vošli do subéteru ešte pod|vplyvom normálnej gravitácie!
{22119}{22157}Zrejme boli rozdrvení.
{22167}{22221}Fajn, pripravme sa vojs do subéteru.
{22230}{22298}Hej, Harry, o èo sa jednalo s tou loïou?
{22307}{22390}Bola prekákou pre mòa a môjho brata.
{22559}{22620}Vôbec sa nedá poveda, kam ideme.
{22623}{22675}Subéterovı pohon, núdzové zastavenie!
{22682}{22740}Munchausenov reaktor sa vymkol kontrole!
{22743}{22792}È-Èo sa to deje?!
{22816}{22902}Tlak na loï narastá.|Práve prekraèuje bezpeènú hodnotu!
{22921}{22965}Vypínam všetky pohonné systémy!
{23250}{23307}Hej. Zobuï sa.
{23347}{23386}Si v poriadku, Melfina?
{23394}{23433}Áno, som.
{23446}{23504}V súèasnosti fungujeme|na náhradnú energiu,
{23509}{23547}take nemáme iadene informácie|o dianí vonku.
{23550}{23581}Prosím, naštartujte loï.
{23622}{23698}A ivot ide ïalej, e?
{23926}{23992}- Testujem, testujem...|- Kde, ksaskru, sme?
{23994}{24073}Vyzerá to, e sme sa bezpeène vrátili|do normálneho vesmíru.
{24088}{24190}Našastie, zdá sa, e nie sme|príliš ïaleko od Heifongského systému.
{24196}{24230}Pokúsim sa vypoèíta našu polohu.
{24232}{24280}Táto loï je odolnejšia,|ne som si myslela...
{24283}{24329}Myslím, e u som to spomínal,
{24332}{24381}som najrıchlejšia,|najdokonalejšia loï v galaxii.
{24394}{24415}Vieš, kde sme?
{24417}{24505}Áno. Sme kúsok od obenej dráhy|Heifongu V...
{24509}{24614}...a asi 360 miliónov kilometrov|nad jeho rovinou obehu.
{24630}{24673}Ako dlho je to u, èo sme skoèili?
{24682}{24778}Lodné hodiny udávajú 2 minúty,|24 sekúnd od vstupu do subéteru.
{24794}{24838}Daj mi hlásenie stavu.
{24847}{24948}ivotná podpora, komunikácia|a všetky senzory vykazujú normál.
{24952}{25005}Potvrdené nepravidelnosti|v systéme éterového pohonu,
{25014}{25084}Newtonove reaktory 1 a 3 sú nefunkèné.
{25117}{25176}Aktivuj Newtonove reaktory 2 a 4.
{25189}{25229}Nastav kurz ku kontrolnému bodu 4.
{25236}{25289}Stále chcete pokraèova v závode?
{25303}{25374}Si myslíš, e to vzdám,|keï sa ešte vládzeme hıba vlastnımi silami?
{25382}{25421}Subéterovı pohon stále pracuje, e?
{25422}{25527}Ano, ale dva reaktory sú na 50% vıkone.
{25536}{25594}To na vstup do subéteru nestaèí.
{25602}{25662}Ako dlho by trvalo dosiahnutie 4. kontrolného|bodu s pouitím len éterového pohonu?
{25666}{25710}Vzdialenos je 600 miliónov kilometrov.
{25714}{25813}Na 50% vıkon... by to trvalo asi 96 hodín.
{25853}{25892}Závody by medzitım u skonèili.
{25997}{26074}Èo je? Vzdali ste sa?
{26083}{26169}Niekto nás len trafil|pár raketami a hneï, e...
{26174}{26200}"Loï je znièená!"
{26203}{26227}"Sme v keli!"
{26248}{26273}"Všetkému je koniec."
{26275}{26332}Tak, èo sa deje?
{26338}{26419}Pod¾a Ctarl-Ctarl je to vaše|správanie zlé!
{26430}{26502}Pod¾a Ctarl-Ctarl, ide o spravodlivos!|Odvahu! Vytrvalos!
{26511}{26557}S tımito troma ideálmi sa nikdy|nevzdávame a vdy robíme, èo sa dá...
{26558}{26624}- My nie sme Ctarl-Ctarl, jasné?|- ...aby sme prácu dokonèili!
{26632}{26751}Vy nemáte ani vytrvalos|ani odvahu plavi sa v éterovom mori!
{26759}{26824}Gilliam! Môeš mi poveda,|kde sa formuje éterovı prúd?
{26830}{26875}Oh, jej... Pozrime sa.
{26884}{26909}Ah, tu je to.
{26914}{27015}Prúd sa šíri od Heifongu V|k Heifongu I. U som ho lokalizoval.
{27022}{27062}Aisha, sadni si!
{27064}{27086}Èo?
{27128}{27164}Èo zamıš¾aš, Gene?
{27173}{27284}Je mi jedno, èi prehráme, ale práve|som objavil nieèo, èo môme ešte skúsi.
{27293}{27337}Poèkaj, snáï nemyslíš...
{27347}{27448}Kadá normálna loï, ktorá by vstúpila|do éterového prúdu by u bola históriou.
{27456}{27490}Kadá normálna loï.
{27497}{27552}Toto nie je obyèajná loï.
{27563}{27591}Presne!
{27594}{27658}Keï som sa díval do návodu na obsluhu,|objavil som nieèo prekvapivé.
{27663}{27738}Táto loï si dokáe poradi|s hocijakım éterovım prúdom.
{27753}{27779}A to znamená...
{27783}{27815}Nechcem to poèu!
{27822}{27876}...e prejdeme tımto éterovım prúdom!
{27902}{27937}Poïme!
{28050}{28124}Dostali sme sa do kontaktu a prepli sa|do Grapplerového bojového módu.
{28156}{28220}Verte mi trochu a vydajte sa so mnou na plavbu.
{28231}{28254}Ja si s tım poradím!
{28263}{28282}Dokáem to!
{28284}{28309}A z èoho tak usudzuješ...?
{28312}{28347}- Z nièoho!|- To som si myslel...
{28349}{28432}Ale veï všetko je raz po prvı krát!
{28641}{28688}Boj je perfektnım tréningom!
{28694}{28765}Do toho!|Nepod¾ahni tomu bastardovi s raketami!
{28900}{28960}Dosiahli ste kontrolnı bod 4, El Dorado.
{28980}{29008}Aká je naša pozícia?
{29020}{29109}Pod¾a údajov z kontrolnıch bodov|ste v súèasnosti na 4. mieste.
{29122}{29211}Take to závisí od toho,|ktoré lode mieria k Heifongu I?
{29218}{29349}Avšak, máme správy o éterovom prúde|okolo Heifongu I.
{29359}{29407}Take je isté, e skonèíme lepšie ako štvrtí, však?
{29454}{29512}Preèo mi tak bije srdce?
{29608}{29659}Èo?! Kde sa tu vzali?!
{29663}{29722}Vypadá to, e prešli éterovım prúdom!
{29723}{29741}Náhodou?
{29742}{29782}Nie, zdá sa, e úmyselne.
{29791}{29876}Sú snáï blbí?!|Môeš mi k nim otvori kanál?
{29966}{30051}Tu je loï è. 26, Outlaw Star.|Aká je naša pozícia?
{30058}{30125}Ako to mám vedie?|Ale ste na prvom mieste medzi pošahanımi kaskadérmi!
{30129}{30189}To rád poèujem! Outlaw Star, konèím!
{30201}{30273}Gilliam, vyuijeme Heifong I|na gravitaèné zrıchlenie!
{30309}{30347}Myslel som, e je po nás...
{30371}{30443}Ale ak budeme pokraèova,|môme by medzi prvımi troma...
{30493}{30579}Ako prvı prichádza Sunbeam 545|z Trihorse Corporation!
{30581}{30621}Prvé miesto je u isté!
{30623}{30677}A ïalší je Bonaparte|z Penelope Corporation!
{30679}{30738}Èasové rozdiely medzi prechádzajúcimi|loïami by mohli by problémom!
{30744}{30768}Kde je Gene?!
{30777}{30833}Bonaparte si zaistil druhé miesto!
{30838}{30880}A súboj o tretie miesto?
{30890}{30976}A loï na treom mieste...|je u na doh¾ad!
{30990}{31029}Je to Outlaw Star!
{31034}{31083}Cie¾!
{31094}{31172}Outlaw Star, súkromník,|je treou loïou idúcou do cie¾a!
{31176}{31274}Ale Hisetsu, ktorı zaèal|o dve minúty neskôr, sa blíi ku èiare!
{31290}{31314}Ustúpte!
{31322}{31375}Ak skonèí viac ako dve minúty po nás,|vyhrali sme!
{31390}{31454}Hisetsu zo Siven Industries|práve dosiahol cie¾!
{31457}{31540}A jeho èas...?|Vyradil Outlaw Star z tretieho miesta!
{31576}{31616}Boli tak blízko...
{31779}{31805}Musíte sa poponáh¾a!
{31806}{31836}Preèo?
{31838}{31900}Skonèili sme štvrtí, tak èo má s nami|spoloèné odovzdávanie cien?
{31903}{31995}Celkovo ste skonèil štvrtí,|ale boli ste prví v kategórii súkromníkov.
{32005}{32079}Ako keby Fredovi Luo na tom zálealo...
{32092}{32126}Hej, èo to robíte?
{32132}{32214}Sme Outlaw Star, na prvom mieste|medzi súkromníkmi!
{32218}{32252}Rozumiete?
{32379}{32447}Hoci prišli štvrtí, ale aj tak myslím,|e to je celkom dobrá reklama.
{32457}{32499}A èo teda sponzorskı poplatok?
{32505}{32558}Myslím, e im dám polovicu.|200 000.
{32564}{32646}Je to trochu krik¾avé, ale myslím,|e to nie je a také zlé.
{32650}{32678}Èo vravíte?!
{32702}{32753}Èo tım myslíte,|El Dorado vypadlo?!
{32764}{32893}Nu, oh¾adne tohto...|Máme pre vás odkaz z El Dorada.
{32921}{32947}Èoe?
{33216}{33337}Jedného tichého dòa,
{33355}{33507}vietor bol èerstvı a sviei.
{33520}{33815}Lupene kvetov sa chveli,|akoby spali.
{33825}{34045}Tento pocit pokoja...
{34058}{34434}Tak, aké mu ¾udia dali meno?
{34456}{34751}V bielom piesku mesiaca,|príbeh je uschovanı,
{34770}{35097}Poèúvam ho,|ako keï svetlo svieti, pokojne.
{35226}{35281}Ten MacDougall mi posiela vızvu...
{35294}{35346}Teda, ten chlap je staromódny...
{35359}{35424}Zaprisahal sa mi,|e to bude férovı boj,
{35427}{35487}ale stále na mòa zákerne útoèí!
{35529}{35601}Zdá sa, e budem musie|doòho vtåc nejaké spôsoby!
{35618}{35694}Ozaj, nevadilo by ti by|ticho, Aisha?!
{35710}{35825}Nabudúce v Outlaw Star!|"Smrtiaci boj s El Doradom!"
{35833}{35891}Radšej sa pripravte!
