{1}{1}23.976
{157}{253}Zabíjajú, okrem iného.|Ak im to vynesie peniaze, zabijú.
{270}{350}Piráti? Outlaws?|Odpadlíci z Vesmírnych jednotiek?
{352}{391}Nie, iadni z nich.
{398}{463}Ale vezmú prácu od hocikoho.
{476}{533}Presne tak. Ak im to vynesie peniaze.
{553}{642}Nech u sú hocikto, sú to hyeny,|ktorıch si cenia všetky mocnosti.
{665}{743}Sú nebezpeèní, ak sa k nim dostanete|príliš blízko, ináè sú dobrí.
{774}{863}Keby neboli, niekto by ich bol|u dávno strelil odzadu.
{880}{948}Je to silnejšie ne nenávis ostatnıch ¾udí k nim.
{966}{1049}Kadı v podsvetí pozná to meno,|"Bratia MacDougallovci".
{1062}{1173}Ale nikto nevie,|kto bratia MacDougallovci naozaj sú.
{1182}{1254}Sú opatrní, odváni, prefíkaní,|a za peniaze urobia všetko.
{1262}{1304}Sú spo¾ahliví a vytrvalí.
{1320}{1434}Kadı, kto sa dozvedel viac ne treba,|bol zabitı.
{1469}{1569}Veru. Rukami bratov MacDougallovcov.
{1672}{1753}Semenaide, kesanaide, makenaide...
{1754}{1876}...daredatte motteru|hazu yuzurenai mono.
{1893}{1967}Ai dake, yume dake, kimi dake...
{1969}{2111}...sore dake wa hanasanai,|donna toki de mo.
{2169}{2269}Dou shiyou mo naku,|ochitsukanai yoru...
{2271}{2383}...nani mo ka mo nagedashitaku naru.
{2385}{2483}Tsubekobe iwazuni,|sassa to doa o akena.
{2485}{2592}Rikutsu nante, koneteru hima wa nai.
{2600}{2806}Juu'ou-mujin tobimawaritai,|youi-shuutou mamoritakunai!
{2812}{2991}Nakushita wakeja nai,|mada hajimattenai dakara.
{3007}{3090}Semenaide, kesanaide, makenaide...
{3091}{3210}...daredatte motteru|hazu yuzurenai mono.
{3227}{3307}Ai dake, yume dake, kimi dake...
{3309}{3427}...sore dake wa hanasanai,|donna toki de mo.
{3455}{3559}Nani ga hoshii? Nani ga shitai?|Doko ni ikitai?
{3566}{3718}Yami o saite hashirinukete|tsukamitore through the night!
{3983}{4053}Vzdialenos k okraju Lione|Lagrange Point, 30 000 kilometrov.
{4170}{4205}Nejaká známka po El Dorade?
{4210}{4243}Stale niè.
{4252}{4336}Lene senzory sú trochu ovplyvnené|magnetickou búrkou...
{4346}{4480}Pod¾a poslednıch meteorologickıch správ,|slneèné erupcie sú stále aktívne.
{4493}{4559}Táto magnetická búrka bude zrejme chví¾u trva.
{4567}{4617}Oni sú na tom rovnako.
{4624}{4685}Je èas odplaty, El Dorado...
{4684}{4776}BillSK & Pedro uvádzajú:|OUTLAW STAR:"Smrtiaci boj s El Doradom!"
{4794}{4819}Èo vravíš?
{4825}{4868}Èo tım myslíte, El Dorado vypadlo?!
{4874}{4890}Eh?
{4901}{4943}P-Pıtate sa nesprávneho!
{4952}{4983}Kam sa podel?
{4990}{5029}Nu, oh¾adne tohto...
{5042}{5121}Máme tu pre vás odkaz z El Dorada.
{5150}{5175}Èoe?
{5288}{5325}Vzdialenos k Lagrange point, 10 000.
{5330}{5376}Stále iadna stopa po nepriate¾ovi...
{5398}{5456}Nebude vnútri toho po¾a asteroidov?
{5464}{5545}Nechcem tam ís, kım sa nepresvedèím.
{5551}{5576}Spoma¾ujem.
{5598}{5677}U mám dos toho tvojho šastia.
{5686}{5760}Chcem s tım u skoncova,|tak príï do Lione Lagrange Point,
{5776}{5813}Príï do 50 hodín.
{5821}{5894}Ak ma porazíš, poviem ti èoko¾vek chceš vedie.
{5944}{5965}Gene...
{5970}{6018}Vızva na súboj, èo?
{6026}{6056}To bude zaujímavé...
{6203}{6229}Oh, nie.
{6244}{6356}Magnetické búrky, rušivı éterovı prúd,|nahromadenı medziplanetárny materiál...
{6364}{6439}Podmienky sú v tomto regióne hrozné.
{6443}{6513}Nezdá sa, e by radar,|CFS alebo subpriestorovı radar...
{6518}{6586}...tu boli k nieèomu dobré.
{6593}{6665}Take sa budeme musie spo¾ahnú|na vlastné oèi, e?
{6679}{6739}Nechajte to teda na mòa!
{6750}{6832}Iste. Poèul som, e Ctarl-Ctarl|majú dobré oèi.
{6863}{6929}Preèo a musíme aha zo sebou?
{6935}{7011}To vy ste mi znièili šance nieèo|v svete dosiahnu.
{7020}{7137}Musíte mi to vynahradi!|Musím nájs Galaktickı Leyline!
{7150}{7218}Pozri, chcem sa a nieèo spıta.
{7230}{7288}Èo, ksakru, je ten Galaktickı Leyline?
{7293}{7364}Èo? Vy neviete ani to?
{7370}{7421}Hilda nám toho moc nepovedala.
{7430}{7528}V Galaktickom Leyline sa nachádza|neuverite¾nı poklad!
{7536}{7596}Poklad? Nejakı druh vzácneho kovu?
{7602}{7653}Mono, alebo zásoby Dragonitu!
{7665}{7712}Spravodajská sluba Impéria odhaduje,
{7717}{7810}e jeho cena by staèila na|kúpenie celého solárneho systému!
{7814}{7858}Wow! Úasné!
{7865}{7931}Nech je to akoko¾vek "úasné",|stále je to len vec.
{7942}{8053}Z toho mála, èo som poèul,|mi to nepripadá moc ako poklad.
{8058}{8095}Èo je to teda?
{8105}{8177}Brána. Poèul som, e je to nejakı druh brány.
{8184}{8290}Tak potom je tá brána urèite|urobená z Dragonitu!
{8306}{8425}Kadopádne, nemôeme a vzia zo sebou.|Toto je náš súboj.
{8488}{8585}Ak tí bratia MacDougallovci|vedia nieèo o Galaktickom Leyline,
{8591}{8641}tak jednoznaène idem s vami!
{8752}{8789}Nevidím po nich ani stopy...
{8796}{8826}Mono je to pasca.
{8833}{8917}Istee je to pasca. Chcú znièi túto loï.
{8927}{8979}Loï zvanú XGP, veru tak.
{9195}{9262}Poèkajte. Poèkajte na okamih, panstvo.
{9268}{9307}Huh? My?
{9313}{9370}Presne tak, vy.
{9384}{9448}Ako sa vám dostala do vlastníctva tá loï?
{9470}{9491}Áno, tá loï...
{9498}{9533}Vy ste kto?
{9580}{9618}Som Gwen Khan.
{9623}{9739}Veru, som Gwen. Som funkcionár závodov.|Tohoto závodu, rozumiete.
{9757}{9809}Veru, to som. Funkcionár.
{9818}{9905}Nu, pán Funkcionár,|preèo sa tak zaujímate o našu loï?
{9914}{9957}Zaujímama sa, iste. Zaujímam sa.
{9963}{10072}Hm. Je to ve¾mi vıkonná loï,|postavená neznámym vırobcom.
{10082}{10157}Veru, je to ve¾mi vıkonná loï, tak je.
{10162}{10180}Hej.
{10220}{10331}No tak, no tak, povedzte mi.|Ako ste sa k tej lodi dostali?
{10334}{10410}Je to záhada. Veru, je to záhada.
{10599}{10621}Našli sme ju.
{10622}{10651}Našli?
{10656}{10737}Hm? Našli? Je to moné?
{10746}{10770}Nie... Aké zvláštne...
{10772}{10820}Našli ste ju?
{10822}{10881}Tak. Bola to vec bez majite¾a.
{10886}{10975}To znaèí, e tá loï je teraz naša.|Je s tım nejakı problém?
{10979}{11025}Problém? Problé...?
{11042}{11091}Nie, nie je iaden problém.
{11103}{11155}Nie, naozaj nie je iaden problém.
{11163}{11220}Prepáète, ale ponáh¾ame sa.
{11353}{11377}Dentlmeni!
{11409}{11457}Chcem, aby tá loï--
{11463}{11489}Èoe?
{11515}{11563}Nie, to niè.
{11579}{11624}Vôbec niè.
{11634}{11671}Niè, niè...
{11795}{11836}Nudím sa...
{11838}{11889}Èo to malo znamena s tım dedom?
{11891}{11917}Viem ja?
{11922}{12041}Mimochodom, Gene. To chceš stále krúi|okolo toho po¾a asteroidov?
{12057}{12123}Hej, nemôeme nájs svojho partnera|do tanca, tak èo máme robi?
{12125}{12181}No, mono ešte trochu spomalím.
{12190}{12238}Všetky pohonné systémy sú v poriadku.
{12255}{12321}A èo Newtonove reaktory 1 a 3?
{12330}{12358}Fungujú normálne.
{12369}{12403}Nu, samozrejme.
{12405}{12498}Mono to bola rıchla práca,|ale opravy boli dokonèené.
{12505}{12577}Hej, hej, tvoja neprekonate¾nos|nás opä zachránila.
{12587}{12634}Vaša chvála mi lichotí.
{12645}{12665}Oh, nie.
{12671}{12689}Èo je?
{12694}{12754}Blíia sa strely, na 9 hodinách hore!
{12755}{12791}Bez varovania? To je nezdvorilé!
{12946}{12989}Nepriate¾ská loï pred nami!
{13100}{13189}Toto bude súboj jeden na jedného.|Nebude ti to vadi, e?
{13194}{13237}Nie je to celkom fér.
{13250}{13307}Práve si nás chcel znièi,
{13314}{13390}avšak my máme pár otázok|skôr ne znièíme teba.
{13392}{13438}Budete musie teda riadne zabojova.
{13446}{13533}Navyše, toto je tvoje ihrisko,|take my sme vo ve¾kej nevıhode.
{13539}{13586}V tomto prípade vás uisujem,
{13602}{13663}e nechodím moc èasto do oblasti Heifongu.
{13672}{13743}Váne? Tak kde je teda|tvoje obvyklé pôsobisko?
{13756}{13785}Naokolo.
{13890}{13916}Hlupák!
{13991}{14023}Èo urobíme, Gene?
{14027}{14066}Zostáva nám akurát akceptova to, nie?
{14078}{14150}Gilliam! Vypusti kameru!|Bude to náš sprievodca!
{14361}{14441}Vnútri po¾a asteroidov sú podmienky|ešte horšie.
{14445}{14517}Vysiela ju príliš ïaleko je zbytoèné.
{14524}{14621}Èo znaèí, e jeho pasca mu celkom nevıjde.
{14631}{14678}Nie je tu vôbec iadna známka|po nepriate¾skej lodi.
{14689}{14750}Aisha, chcem, aby si nám|dávala pozor na chrbát!
{14754}{14783}Len to nechaj na mòa!
{14962}{15078}Kruci... Preèo si, ksakru,|vybral na súboj zrovna takéto miesto?
{15090}{15138}Detekované strely. Sú priamo pod nami.
{15180}{15210}Ty jeden...!
{15301}{15378}Zdá sa, e je vybavenı|celkom presnımi raketami.
{15383}{15449}Teraz u chápem.|Preto si vybral toto miesto.
{15522}{15575}Ak sa nám to podarí zmeni na boj zblízka,|tak je náš!
{15631}{15650}Tam je!
{15654}{15674}Bastard!
{15756}{15787}Neujdeš mi!
{15826}{15850}Kam sa podel?!
{15990}{16014}Za nami!
{16015}{16037}Èoe?!
{16074}{16110}Ten hajzel!
{16268}{16351}Tá jeho loï je manévrovate¾nejšia|ako Outlaw Star?!
{16361}{16465}Táto loï pouíva najpokroèilejší|navigaènı systém v galaxii.
{16471}{16549}Je nemoné, aby moja manévrovate¾nos|bola horšia ako u lode rovnakej triedy.
{16554}{16617}Hej, urèite ide naplnı vıkon.
{16699}{16742}Blíia sa strely na 10 hodinách hore.
{16847}{16901}Postav sa proti nám zoèi-voèi, sakra!
{16905}{17007}Bratia MacDougallovci|sa fakt radi zakrádajú...
{17027}{17050}Èo--?
{17054}{17105}Sú tu ïalšie strely! Na pravoboku!
{17111}{17140}Sú na 4 hodinách hore.
{17142}{17207}Èoe?! On sa u dostal za nás?!
{17247}{17289}Nedokáeme sa strias tıch na pravo!
{17294}{17334}Tak ich zostrelíme.
{17936}{17989}Budem musie ís proti tomu chlapovi naplno...
{17983}{18062}Produkcia: BillSK|Spracovanie videa: Randy
{18064}{18125}Slovenské titulky: Pedro (pedro_k@post.sk)
{18128}{18260}Nie je urèené pre komerèné pouitie.
{18674}{18717}Blíia sa strely, 9 hodín hore.
{18791}{18850}Blíia sa strely na troch hodinách hore.|V poète pä.
{19157}{19214}Gene! Ak to bude pokraèova,|je po nás!
{19225}{19312}Èoskoru mu rakety dôjdu!|A vtedy sa zaène ozajstnı boj!
{19316}{19454}Prestaòte tu vysedáva!|Vrazte tam a rozmliadite ho na kašu!
{19459}{19477}Stíchni!
{19486}{19520}Keby som mohol,|tak by som sa tu tak netrápil!
{19559}{19605}Komu vravíš, aby stíchol?!
{19613}{19655}Povedal som ti stíchni, tak stíchni!
{19657}{19684}ÈOE?!
{19694}{19787}Gilliam, nie je na mostíku príliš horúco?
{19801}{19889}Prepáète. Hneï uberiem dva stupne.
{19895}{19937}Teraz prichádzajú ïalšie!|Na desiatich hodinách hore!
{19958}{19978}Kruci!
{20046}{20070}Kde je El Dorado?
{20074}{20103}Stratil som ho.
{20105}{20149}Èo tam robíš, sakra?!
{20160}{20229}Preèo nevypustíme všetky kamery|a nerozmiestnime ich okolo nás?
{20242}{20324}Náš úèinnı dosah signálu|v tıchto podmienkach je asi 100 kilometrov,
{20332}{20404}take je nepravdepodobné,|e by sme získali nejaké uitoèné zábery.
{20408}{20520}A preto vravím, e by ste tam|mali vrazi a rozdrvi ho!
{20531}{20564}Zmåkni u, krucinál!
{20566}{20603}Iste, ja tak urèite budem ticho!
{20608}{20657}Ak nesklapneš, vyhodím a von!
{20661}{20704}Èoe?!
{20721}{20740}Ha?
{20742}{20789}Vyhodi ju von...
{20802}{20888}Hej, za starıch èasov pozorovate¾ dával signál.
{20900}{20945}Silnım svetlom alebo tak...
{20954}{21061}Aisha. Potrebujem, aby si mi spravila sklubu,|ty ve¾ká, silná Ctarl-Ctarl.
{21068}{21126}Ha? Èo taká náhla zmena názorov?
{21134}{21185}Dovo¾, aby som a vyhodil z lode.
{21208}{21327}Šanca je to malá,|ale vdy lepšie ne by takto.
{21448}{21496}Teraz by u z toho mali by riadne zblbnutí.
{21507}{21541}Zrejme máš pravdu.
{21570}{21618}Dorazíme ich, Harry?
{21620}{21666}Ešte sa s nimi trochu pohrám.
{21679}{21711}Ko¾ko striel zostalo?
{21713}{21758}Zostáva nám 24%.
{21793}{21834}Vidíš? Zostala nám ich kopa.
{21852}{21891}Dostaòme sa za nich.
{21927}{21973}Skôr ne zistia,|e tu je ešte jedna loï...
{22114}{22134}Èoe--?!
{22245}{22304}Tam sú! Tam sú! Našla som ich!
{22314}{22349}Boli sme objavení?!
{22354}{22374}Neexistuje!
{22382}{22421}Outlaw Star sa blíi!
{22478}{22516}Teraz si môj!
{22524}{22573}Myslíš si, e sa nechám tak ¾ahko dosta?
{22702}{22741}Grapplerové ramená?!
{22749}{22825}Myslel si si,|e El Dorado je len obyèajnı krínik?
{22997}{23017}A èo toto?
{23239}{23287}Skap! Skap! Skap! Skap!
{23515}{23545}Tu máš!
{23878}{23912}Prevezmi to, Jim!
{23918}{23940}Gene!
{23974}{24011}Ja idem tamto!
{24252}{24314}Tu je El Dorado! Nepriate¾ ma chytil!
{24318}{24347}- Tu je El--|- Prestaò.
{24355}{24412}Keï u došlo k tomuto, vyriešim to raz a navdy.
{24421}{24460}Vlastnımi rukami.
{24608}{24628}Bastard!
{24696}{24745}T-To bolí!
{24772}{24839}Ty nie si MacDougall.
{25273}{25307}Kde je MacDougall?!
{25489}{25553}Tak, èo chceš vedie?
{25701}{25735}O-Oh, nie.
{25740}{25772}Èo je, Gilliam?
{25782}{25860}Niekto sa pokúša do mòa hacknú.
{25874}{25917}Spúšam teraz núdzovú ochranu.
{25929}{25966}Dobrú noc.
{25968}{25993}Gilliam!
{26082}{26099}Mel!
{26101}{26160}Prestaò! Choï preè!
{26174}{26214}Ty si MacDougall?
{26216}{26253}Harry MacDougall.
{26263}{26322}Nikdy som ešte svoje meno|nepriate¾ovi nepovedal.
{26330}{26413}Preèo piráti Kei chcú XGP?
{26422}{26487}Nu, bola to vlastne ich loï, nie?
{26496}{26564}Preèo si sa pokúšal znièi XGP?
{26574}{26629}Nepıtam sa svojich zamestnávate¾ov na dôvody.
{26637}{26669}Kto je tvoj zamestnávate¾?
{26681}{26710}To je...
{26780}{26868}Rozumiem, tak toto je|hlavnı poèítaè tejto lode.
{26874}{26891}Hej!
{26898}{26958}Oh, nikdy som ho osobne nestretol.
{26968}{27020}Prišiel za nami s ponukou práce.
{27030}{27114}Chcem, aby si mi viac povedal o XGP.
{27138}{27179}Pıtaš sa toho nepravého.
{27210}{27312}Vravel, e o Galaktickı Leyline|sa zaujímajú piráti.
{27325}{27357}Leyline?
{27411}{27468}Zlikvidujem túto vec za okamih...
{27536}{27563}ena?
{27669}{27721}Prestaò! Choï preè!
{27835}{27870}Tak to u je nieèo iné!
{27889}{27937}Èo to robíš, ty bastard?!
{28138}{28154}Sakra!
{28299}{28317}Moja ruka...
{28324}{28392}Moja... MOJA RUKA!
{28486}{28534}Mel, si v poriadku?
{28543}{28562}Hej.
{28568}{28622}Zdá sa, e prístup bol prerušenı.
{28638}{28735}Èo má XGP do èinenia s Galaktickım Leyline?
{28737}{28793}Neviem... Neviem!
{28813}{28901}Preèo si pred šiestimi rokmi|znièil loï môjho otca?
{28903}{28998}Neviem! Pred šiestimi rokmi som mal 12!
{29002}{29117}Hej, MacDougall.|Stále poèúvam o bratoch MacDougallovcoch.
{29122}{29234}Ak ty nevieš niè, ešte stále|sa môem spıta tvojho brata.
{29246}{29285}Poèkaj! Poèkaj, prosím!
{29290}{29345}Keï na to tak myslím, kde je tvoj brat?
{29359}{29448}Gene, máme problém!|Je tu ïalšie El Dorado!
{29461}{29481}Èo vravíš?!
{29615}{29644}Vrá sa ihneï sem!
{29653}{29695}Rozumiem... Tak to je jeho brat, èo?
{29780}{29846}Harry, èo sa stalo?|Odpovedz, Harry!
{29919}{29964}Pošlem ich do pekla!|Pošlem ich do pekla!
{29966}{29997}Pošlem ich do pekla!
{30075}{30125}Nu, tımto sa koneène vyriešila záhada.
{30130}{30205}Nekrúili okolo nás preto,|e by lepšie manévrovali,
{30207}{30246}bola tam ïalšia loï!
{30248}{30292}Teraz nie je èas na analızy!
{30297}{30356}Gene, vyahujem útoènı vrták!
{30526}{30578}Ten druhı je skutoènı MacDougall.
{30586}{30613}Koho myslíš?
{30618}{30650}Jeho staršieho brata.
{30671}{30701}Neuteèieš mi!
{30893}{30919}Sakra!
{31222}{31294}Sme v nebezpeèenstve.|Prosím, vykonajte úhybnı manéver.
{31465}{31496}Kruci!
{31505}{31540}To bolí, braèek!
{31546}{31605}Moja ruka! Moja ruka!
{31607}{31659}Upokoj sa, Harry. Upokoj sa!
{31665}{31746}Ak patríš medzi MacDougallovcov,|nerozèu¾uj sa kvôli ruke!
{31772}{31830}Iste... Prepáè, braèek.
{31839}{31877}To je v poriadku, Harry.
{31883}{31956}Tomu, kto ti to vykonal,|spravíme ešte horšie.
{31967}{32074}Máš pravdu, Ron.|U nemienim znovu takto utiec.
{32108}{32135}Tá ena...
{32150}{32193}Tá ena...
{32234}{32286}Je to márne. Nikde ich nemôem zachyti.
{32291}{32332}Nepriate¾ská loï sa stratila, èo?
{32352}{32388}Tak èo teraz, Gene?
{32395}{32478}Akoby sme mali na vıber...|Vrátime sa na Heifong a budeme skúša znovu.
{32493}{32577}Prepáè, Melfina.|Stratil som ïalšiu stopu.
{32634}{32676}Nie, to niè.
{32710}{32840}Hej! Poïte rıchlo sem a vyzdvihnite ma!
{32853}{32935}Myšlienka, e sa jej budem musie|ospravedlni je fakt deprimujúca...
{32944}{32980}Radšej by si ju tam nechal?
{32994}{33052}Urèite by sa vrátila a strašila ma,|take ju poïme vyzdvihnú.
{33054}{33128}Hej! Švihnite si!
{33154}{33253}Harry MacDougall... Èo on...?
{33266}{33344}Ja som tu!
{33589}{33708}Oto no nai mahiru...
{33728}{33880}...kaze wa tada akarui.
{33893}{34188}Sukoshi nemutasou ni|hanabira ga yureta.
{34198}{34418}Nanigenai kono omoi,
{34430}{34805}nee, hito wa donna|kotoba deyonde iru no?
{34827}{35124}Shiroi suna no tsuki,|tojikometa hanashi o...
{35142}{35470}...hikarifurasu you|ni kikasete ne, sotto.
{35600}{35653}Zdá sa, e si koneène môme da pauzu,
{35655}{35704}avšak treba pracova,|aby bolo z èoho i, e?
{35711}{35732}Èo je toto?
{35735}{35785}H¾adanie zvierat a boj proti škodcom?
{35792}{35850}Okej! Zvyšok nechám na treba, Jim!
{35858}{35976}Ochránim mier v galaxii,|všetko kvôli jednému dievèau!
{35980}{36030}Okej, odchádzam na rande!
{36045}{36145}Nabudúce v Outlaw Star!|"Vysunutá hliadka z iného sveta!"
{36151}{36200}Radšj sa pripravte!
