{1}{1}23.976
{76}{150}Ako sa ¾udstvo šírilo po vesmíre,
{166}{254}dochádzalo k mnohım stretnutiam s mimozemskımi rasami.
{274}{330}Tieto stretnutia niekedy prepukli do vojny,
{332}{452}a inokedy rokovania viedli k vytvoreniu priate¾skıch vzahov.
{474}{564}V súèasnosti je známych šes mimozemskıch rás, s ktorımi sa ¾udstvo stretlo.
{574}{653}Nayani a Corboniti sú k ¾uïom pomerne priate¾skí.
{673}{769}Niektorí myslia zas, e Silgriáni,|sú a príliš priate¾skı.
{788}{846}Vzah ¾udí s Rorganmi je o nieèo horší,
{848}{925}a vyskytujú aj prekáky v jednaní zo Sithmi.
{950}{1084}Po nespoèetnıch bitkách s Ctarlmi boli nakoniec uzavreté obchodné dohody.
{1098}{1165}Tak ako sa bude ïalej šíri ¾udská sféra vplyvu,
{1166}{1216}dôjde pravdepodobne i k ïalším stretnutiam.
{1240}{1298}Treba si vzia pouèenie z príkladov minulosti.
{1308}{1358}Stretnutia sú len zaèiatkom.
{1364}{1428}Všetko sa zaèína pochopením uvaovania toho druhého.
{1442}{1517}Mono tu uplatni jeden poznatok z lásky:
{1530}{1608}Stretnutia sú vdy neoèakávané.
{1737}{1817}Neobviòuj to, neniè to, nepodceòuj to...
{1818}{1939}...to nieèo jedineèné, èo kadı má.
{1958}{1981}Moja láska...
{1982}{2006}Moje sny...
{2007}{2031}A tie ty.
{2034}{2176}Nevzdám sa toho, za iadnu cenu.
{2234}{2333}V tie noci, keï si nepokojnı, nech robíš èoko¾vek,
{2334}{2445}máš chu to všetko odhodi preè.
{2449}{2545}Nevrav u niè, len otvor dvere.
{2547}{2656}Nemám èas sa tu s tebou bavi.
{2662}{2770}Chcem sa tadeto vo¾ne preletie,
{2776}{2870}a nedba pritom na opatrnos!
{2876}{2965}O niè som neprišiel,
{2967}{3063}veï som ešte ani nezaèal.
{3070}{3151}Neobviòuj to, neniè to, nepodceòuj to,
{3154}{3273}to nieèo jedineèné, èo kadı má.
{3289}{3317}Moja láska...
{3319}{3346}Moje sny...
{3348}{3369}A tie ty.
{3371}{3490}Nevzdám sa toho, za iadnu cenu.
{3518}{3544}Èo by si chcel?
{3546}{3569}Èo budeš robi?
{3571}{3623}Kam pôjdeš?
{3626}{3781}Schmatni, èo chceš, pretni temnotu, keï budeš uteka nocou!
{4220}{4300}BillSK & Pedro uvádzajú:|OUTLAW STAR:"Vysunutá hliadka z iného sveta!"
{4501}{4572}Haló, tu je firma Starwind & Hawking.
{4582}{4601}Áno.
{4605}{4717}Hej, prevádzkujeme medziplanetárnu prepravu,|avšak nosnos našej lode je pomerne malá.
{4727}{4747}Akı je náklad?
{4760}{4830}Ah. To bude problém.
{4842}{4889}Áno. Prosím, zavolajte znovu.
{4903}{4928}Èo vravel?
{4940}{5002}Pıtal sa, èi by sme mohli na Outlaw Star previez nejaké...
{5004}{5065}...obrovské stavebné vybavenie, ale nie je šanca, aby sme to uviezli.
{5067}{5089}Oh.
{5146}{5207}Nie je tu iadna dobrá práca?
{5221}{5330}Dal som na net nejaké inzeráty, ale odozva nie je moc dobrá.
{5336}{5411}A ak aj by bola, tak je to robota len za pár drobnıch.
{5414}{5467}Musíme zohna prácu, nech je to èoko¾vek.
{5474}{5545}Naša peòaenka je v zlom stave, Gene.
{5554}{5634}Parkovacie poplatky sú a nehorázne vysoké.
{5646}{5733}Je to v podstate parkovanie na ulici, ale aj tak stojí ve¾a.
{5737}{5854}Nedá sa niè robi. V takomto ve¾kom meste môme by radi, e sme našli miesto.
{5886}{5919}Vïaka, Melfina.
{5931}{5954}To niè.
{5962}{6020}Nenašli ste ešte iadnu prácu?
{6026}{6082}Gene je moc prieberèivı.
{6086}{6147}Keï to niè nevynesie, tak èo z toho?
{6184}{6213}Zákazník?
{6220}{6274}- Vitajte--|- Jak sa vám vedie?
{6283}{6338}Oh, to si ty. Ide to.
{6342}{6375}Nemáme niè.
{6448}{6533}Myslela som si. Ale nebojte sa!
{6544}{6625}Mám tu prácu pre vás oboch.
{6634}{6669}Fakt? Èo také?
{6681}{6746}V mestskej oblasti, ved¾a Heifongského kozmodrómu,
{6752}{6825}vraj ije v kanáloch nejaké zdivoèelé zviera.
{6834}{6901}Údajne je to uteèené domáce zviera, èi také èosi.
{6904}{6935}Prácou je zlikvidova ho.
{7126}{7178}Tak, èo je to s vami?!
{7186}{7247}Chceš, aby som liezol dole do kanála?
{7249}{7303}Táto práca mi nejak smrdí.
{7309}{7405}Bolo to odoslané z Heifongskej mestskej vodárne, je to teda legálne!
{7418}{7450}Ko¾ko za to?
{7452}{7488}500 wongov!
{7668}{7705}Èo je to za nápad?!
{7709}{7819}Fajn! Ak to chcete takto, spravím tu prácu sama!
{7875}{7942}Veru tak, keï nevedia ani oceni malú láskavos,
{7944}{7984}je to koniec celého ¾udstva!
{7998}{8053}Tak u dos! Èo si myslí?
{8054}{8106}Znie to ako práca za 500 wongov...
{8124}{8182}Vieš o nejakej dobrej práci, Gilliam?
{8183}{8235}No, to naozaj neviem.
{8274}{8323}Mono je to ponuka práce.
{8334}{8384}Èau, Jim! Ako sa darí?
{8388}{8444}F-Fred! A-Ahoj.
{8499}{8553}Ak ide o tie peniaze, èo ti dlíme, tak ti fakt ešte nemôeme zaplati.
{8563}{8633}To som si domyslel, tak som si povedal, e vám poviem o nejakej práci.
{8650}{8743}Po pravde, jeden môj obchodnı partner sa dostal do istıch problémoov.
{8766}{8782}Akıch?
{8784}{8864}Priviezol sem nejakı náklad zo systému Silgry.
{8871}{8955}Ale keï prišiel sem, na Heifong, náklad zmizol.
{8960}{9013}Vraví, e chce, aby ste sa na to pozreli.
{9021}{9071}Nie je to práca pre políciu?
{9078}{9157}Je to dos blízke pašovaniu, take to neprichádza do úvahy.
{9163}{9181}Zbrane?
{9182}{9230}Pod¾a všetkého novı druh hmyzu.
{9232}{9261}Sorry, Fred.
{9270}{9301}To nie je práca pre nás.
{9306}{9338}Poèkaj, Gene!
{9343}{9384}Fred, ko¾ko je za tú prácu?
{9390}{9475}Sedemsto vopred, plus ïalších 2000, ak sa náklad vráti v poriadku.
{9478}{9509}Vezmime to, Gene!
{9517}{9581}Nejakú takúto úbohos? Mòa vynechaj.
{9585}{9612}Fajn!
{9614}{9652}Fred, ja to beriem.
{9656}{9724}Take, je v doku è. 8 na kozmodróme neïaleko od vás.
{9726}{9787}Zavolám mu a poviem, e ideš.
{9810}{9868}Teda, ty fakt makáš pre niekoho, kto vymyslí tak málo...
{9870}{9917}Gene, si príliš prieberèivı!
{9926}{9987}Èoskoro sa naskytne väèší dob, nie?
{9989}{10046}Jim, nechceš, aby som išla s tebou?
{10048}{10089}Iste! Len poï, Melfina!
{10098}{10152}Hej! To tu mám akoe sedie sám?
{10163}{10201}Ja som tu tie, Gene.
{10218}{10266}A èo mám akoe robi s tebou?
{10274}{10354}Hej, príde ve¾kı dob, pravda? Nenechaj si ho ujs, Gene!
{10379}{10413}Tie slová ešte o¾utuješ!
{10421}{10457}Maj sa, Jim.
{10514}{10549}Hej! To bolo rıchle!
{10605}{10660}Haló, firma Starwind & Hawking!
{10666}{10734}Je to pravda, e vyriešite hocijakı problém?
{10738}{10801}Samozrejme! Tak, ako vám môeme pomôc?
{10808}{10885}Na zmrzline, ktorú predáva ved¾ajší predavaè je nieèo podozrivé!
{10890}{10929}Zmrzlina?
{10930}{10990}Urèite porušuje nejakı zákon alebo tak!
{10994}{11067}Ako ináè by mal takı úspech, keï to má takú chu?!
{11069}{11124}Vïaka nemu je môj biznis v kıbli!
{11129}{11185}Na tej zmrzline je nieèo podozrivé! Viem--
{11215}{11264}Ani ste sa ho nespıtali na plácu.
{11270}{11311}Nie som vyšetrovate¾.
{11416}{11501}Haló? Pamätáte si ma? Hej, tu je Gene.
{11508}{11558}Gene, našli ste nejakú dobrú prácu?
{11577}{11612}Preèo ste to urobili?!
{11614}{11673}Iste, iste, s¾úbil som vám, nie?
{11683}{11738}Bol som zvedavı, èi by sme si nemohli zájs na veèeru alebo tak.
{11750}{11834}- Keï pomyslím, e tento mu je mojím kapitánom...|- Váne? Okej, hneï tam budem!
{11866}{11930}Naozaj neviem, èo s tım robi...
{11938}{11993}Stalo sa to pred piatimi dòami.
{12001}{12055}Dal som si vo¾no, keï som pristál tu, na Heifongu,
{12058}{12111}a keï som sa koneène chcel pusti do biznisu,
{12115}{12186}kontajner bol prázdny, tak ako ho tu vidíte.
{12190}{12243}Ak sa s tım nieèo nespraví, tak na tom fakt ve¾a stratím!
{12248}{12310}A teraz pravdu, akı bol váš náklad?
{12331}{12420}Fred vás dvoch odporuèil, tak vám to poviem.
{12435}{12504}Bol to extrémne vzácny hmyz a rastlina.
{12510}{12562}Mono ten hmyz len utiekol.
{12574}{12638}A otvoril si kontajner aj poklop na mojej lodi?
{12650}{12698}Nie, to nie je moné.
{12707}{12766}Aj keby to tak bolo, ale èo tá rastlina?
{12772}{12818}Mono ju ten chrobák zjedol.
{12822}{12874}Nie, je mäsoravı.
{12886}{12950}Niekto ich musel ukradnú.
{12955}{13041}Moja posádka a ja sme h¾adali všade, ale niet po nich ani stopy!
{13061}{13115}Preèo nejdete na políciu?
{13119}{13206}Nezaplatili sme clo, vám ¾uïom,
{13208}{13262}ani za hmyz, ani za rastlinu.
{13277}{13319}Oh, nemusíte sa nièoho obáva.
{13327}{13379}Neprenášajú iadne škodlivé vírusy, ani niè také.
{13386}{13457}To sme si sami preverili.
{13482}{13567}Ide o to, e vybavi všetku tú byrokraciu dlho trvá, viete?
{13577}{13609}Uh... Iste.
{13621}{13764}Keï tak uvaujem, ani neviem, preèo som vzal na seba také ve¾ke riziko.
{13778}{13851}Take, èo sú ten chrobák a tá rastlina zaè?
{13858}{13924}Dám vám prospekt, ktorı som pripravil kvôli predaju.
{13938}{14051}Tá rastlina vyzerá ako jeden z tıch "kaktusov" z vašeho sveta.
{14068}{14109}Kaktus?
{14232}{14302}Moji robotníci vraveli, e to videli tu.
{14338}{14414}Hlásili, e to bolo ve¾ké mäsoravé zviera,
{14421}{14465}ale je tomu aké uveri.
{14466}{14534}Len to nechajte ma Aishu! Ja si s tım poradím!
{14536}{14649}Som naozaj rád, e sa nám na to podarilo získa Ctarl-Ctarl.
{14662}{14713}Tak, nechám to na vás.
{14748}{14789}Môte sa na mòa spo¾ahnú!
{14830}{14940}Dobre, príšera! Aisha prichádza, tak poslúchaj a nehıb sa!
{15181}{15204}U sme tu!
{15240}{15265}Gene?
{15268}{15285}Huh?
{15291}{15329}Vitaj spä, Jim.
{15330}{15389}Suzuka, si tu sama? Kde je Gene?
{15393}{15464}Keï som prišla, bol u preè.
{15487}{15562}Ktovie kam šiel? Mono sa mu pritrafil dobrı dob...
{15573}{15612}Tak, preèo si sa tu, Suzuka?
{15615}{15734}Len tak. Prišla som sa len pozrie ako sa darí.
{15743}{15784}No, ako tak to ide.
{15789}{15882}Tak, ja idem urobi prieskum na trhu so zvieratami.
{15886}{15960}Áno. A ja by som mala skontrolova bezpeènostnú sekciu kozmodrómu...
{15964}{16031}...a pozrie, èi sa tam pred piatimi dòami neudialo nieèo podozrivé, e?
{16037}{16073}Hej. To by bolo skvelé.
{16106}{16166}Vyzeráte by zaneprázdnení, tak ja u pôjdem.
{16170}{16206}Oh, maj sa.
{16212}{16264}Prosím, pozdrav odo mòa Genea.
{16389}{16412}Hej!
{16463}{16508}Prepáète, èakali ste dlho?
{16513}{16554}Nie, vôbec nie.
{16562}{16605}Take, máte teraz trošku èasu?
{16614}{16665}Teraz, keï sa závody skonèili, tak ho mám ve¾a.
{16698}{16793}Aj tak, bolo to úasné, súkromník dosiahol štvrté miesto na svojom prvom závode.
{16802}{16857}Keby sme nenarazili na malı problém, boli by sme skonèili prví.
{16862}{16930}Nu, toto rozprávanie je fajn, ale èo takto da si èaj alebo tak?
{16934}{16957}Iste.
{16973}{17054}Aby som povedal pravdu, ešte stále nepoznám Heifong City moc dobre.
{17070}{17095}Poznáte nejaké dobré miesto?
{17100}{17160}Poprechádzajme sa teda trošku a ja vám to tu poukazujem.
{17164}{17186}Skvelé.
{17218}{17258}Èo robíte teraz?
{17260}{17345}Zaèali sme podnika. Firma Starwind & Hawking.
{17349}{17408}Predávame riešenia na všetky druhy problémov.
{17422}{17448}Ako ide biznis?
{17450}{17468}Okej.
{17470}{17546}To je fakt. Skonèili ste štvrtí v Heifongskom vesmírnom závode.
{17551}{17590}Je samozrejmé, e sa vám darí.
{17596}{17620}To si myslím.
{17622}{17677}Nevadí vám, e ste si museli spravi vo¾no na stretnutie so mnou?
{17692}{17758}Vidie vás je dôleitejšie ne práca.
{17813}{17872}Hej, èo takto da si zmrzlinu?
{17900}{17927}Zmrzlinu?
{17929}{17965}Vidíte? Tamto!
{18068}{18110}Odrazu som na òu dostala chu.
{18116}{18211}Nikdy nebıvala a taká ob¾úbená. Mono zmenili recept, ktovie....
{18213}{18283}Zmrzlina, to znie dobre. Z nejakého dôvodu, myslím, e si dám tie.
{18286}{18315}Tak ju idem kúpi.
{18319}{18342}Hej, ja--
{18354}{18405}To je na oslávu vášho štvrtého miesta.
{18498}{18518}Huh?
{18576}{18660}Tá zmrzlina od toho ved¾ajšieho predavaèa sa mi zdá nejaká podozrivá!
{18706}{18731}Prepáète, e to tak dlho trvalo!
{18746}{18768}Vïaka.
{18861}{18891}Hm. Celkom priemerná.
{18909}{18937}To je pravda...
{19124}{19206}Produkcia: BillSK|Spracovanie videa: Randy
{19208}{19267}Slovenské titulky: Pedro (pedro_k@post.sk)
{19269}{19325}Nie je urèené pre komerèné pouitie.
{19562}{19583}Tu?
{19586}{19689}Áno. Pred piatimi dòami tu bol plot ohnutı.
{19699}{19741}Vyzerá to, e ho u opravili.
{19753}{19785}A èo bezpeènostné systémy?
{19791}{19877}Majú infraèervené detektory a detektory kovov,
{19884}{19921}ale zdá sa, e nezareagovali.
{19922}{19991}Hej, myslím, e hmyz by ich nespustil...
{20009}{20049}No, monoe utiekol sám od seba.
{20055}{20090}Mono...
{20118}{20202}Keï meria meter, mono aj takı chrobák dokáe poui svoj mozog.
{20215}{20252}A ak je to tak...
{20274}{20323}Èo je to?
{20339}{20386}Vravia, e sú to odtoky odpadovej vody z kozmodrómu.
{20392}{20446}Sú zrejme napojené na kanalizáciu.
{20448}{20480}Kanalizáciu?
{20484}{20566}Huh? Nevravela o tom nieèo Aisha...?
{20720}{20767}Poèkaj na mòa, príšera!
{20770}{20819}U som na ceste!
{20870}{20923}Èo je, ksakru, toto?!
{21033}{21069}Èoe...?
{21302}{21403}Presne, tá práca zabi príšeru v kanáloch.
{21406}{21478}Ah, u som na to niekoho nasadil.
{21481}{21539}enu Ctarl-Ctarl?
{21543}{21580}Oh, vy ju poznáte?
{21583}{21666}Chcem, aby ste mi povedali, kde h¾adá a ako je to prepojené...
{21667}{21710}...s odpadovım potrubím z kozmodrómu.
{21861}{21901}To je teda divné.
{21911}{21977}Ako to, e ten zmrzlinár má takú dlhú radu,
{21983}{22035}...keï tá jeho zmrzlina vôbec nechutí tak dobre?
{22042}{22069}To je pravdu.
{22073}{22127}Nu, zabudnime na to.
{22144}{22205}Zmrzlina nie je jediná vec, kvôli ktorej je  Heifong slávny, pravda?
{22215}{22264}Iste, je tu ve¾a inıch vecí.
{22276}{22314}Vy ste ešte nikde neboli?
{22320}{22372}Vstúpili sme do závodov hneï, ako sme sem prišli.
{22375}{22408}Kde ste ili predtım?
{22413}{22456}Na zastrèenej planéte menom Sentinel.
{22477}{22512}Gene! Gene!
{22516}{22544}Prepáète na okamih.
{22552}{22594}Èo je? Nepoèká to?
{22598}{22685}Ak nezastavíme Aishu, nebudeme môc získa tıch 2000 wongov!
{22701}{22736}O èom to, do èerta, hovoríš?
{22772}{22877}Tá príšera, ktorú išla zabi do kanála, je Silgrianov chrobák!
{22883}{22944}Aisha ho roztrhá na kusy! Som si tım istı!
{22948}{22991}Nerozumiem ani slovo z toho, èo vravíš.
{23172}{23232}Neviem, èo sa stalo s tım kaktusom,
{23240}{23290}ale toho chrobáka musíme chyti!
{23298}{23319}Kaktus?
{23414}{23441}Kaktus?
{23551}{23572}Kaktus...
{23574}{23617}Gene! Poèúvaš ma?
{23619}{23645}Hej! Gene!
{23734}{23759}Èo?
{24392}{24417}Èo je to?!
{24610}{24635}Claire! Schovaj sa!
{24640}{24661}Áno!
{24974}{25036}Gene! Èo je to za nápad?!
{25050}{25073}Prepáè!
{25078}{25104}To je divné...
{25202}{25230}Vracia sa?
{25359}{25381}Èo to...?
{25388}{25421}Gene, šibe ti!
{25426}{25481}Máš proti mne nieèo alebo èo?!
{25516}{25550}Nie, kdee...
{25689}{25749}Chceš ešte, ty bastard?
{25772}{25820}Dobre teda, dorazím a.
{25823}{25856}Gene! Nerob to!
{25862}{25881}Jim?
{25884}{25936}Keï tú vec chytíme, má cenu 2000 wongov!
{25942}{25986}Ak ho zabijem, je to pästo!
{26004}{26032}Chy ho, Gene!
{26036}{26061}Zabi ho!
{26067}{26092}Je to 2000 wongov!
{26095}{26157}No a èo?! Zabijem ho!
{26172}{26226}O èom to, sakra, vy dvaja rozprávate?
{26232}{26346}Gene, na chví¾u som ucítila podivné vysokofrekvenèné vlnenie.
{26354}{26384}Vysokofrekvenèné vlnenie...
{26421}{26444}To je ono!
{26538}{26559}Toto?
{26582}{26607}Jim! Kam ideš?
{26612}{26644}Neviem!
{26707}{26737}To robí ten kaktus?
{26775}{26810}È-Èo to vystrájaš?!
{26816}{26842}Jak mám vedie?!
{26896}{26925}Take, ty si si uvedomil moju skutoènú podstatu.
{26961}{27022}Musím a pochváli, niší ivoèích.
{27033}{27092}Hej, o èom to rozprávaš, Jim?
{27103}{27177}To nie ja! Moje ústa sa hıbu samé od seba!
{27214}{27262}Ty! Èo si, ksakru, zaè?
{27290}{27339}Môeš ma nazıva "Ve¾kı".
{27350}{27446}Som vyššia ivotná forma, ktorá je hodná toho vládnu celému vesmíru.
{27458}{27535}Nemáte iadne prostriedky ako uniknú mojej kontrole.
{27539}{27609}Ty kaktusovı bastard! Ty si bol za tım všetkım!
{27615}{27703}Vládca vesmíru, èo? Jak to, e si predával zmrzlinu?
{27709}{27751}Pozorovanie a experimentovanie.
{27759}{27864}Aby som videl, aká úèinná je moja kontrola nad vami.
{27870}{27927}Moje pozorovanie a experimentovanie je teraz ukonèené.
{27954}{27976}Gene!
{27978}{27997}Jim!
{28127}{28165}Moja koris mi uniká!
{28180}{28235}Môj plán teraz prechádza do druhej fázy.
{28242}{28302}Nie! Gene!
{28309}{28343}Jim! Sakra...
{28389}{28411}Melfina?
{28418}{28472}Stoj, niší ivoèích.
{28545}{28585}Stoj! Vravím, stoj!
{28638}{28674}Stoj! Stoj!
{28687}{28759}Ako to, do èerta? Preèo moja moc na teba nepôsobí?!
{28762}{28810}Prestaò robi Jimovi tie hrozné veci!
{28853}{28917}È-Èo si to urobila?!|Rıchlo! Zdvihni ma!
{29015}{29048}Èo mám robi?
{29054}{29078}Rozpuè ho!
{29098}{29135}Naozaj chceš, aby som ho rozpuèila?
{29140}{29170}Nie, Melfina!
{29178}{29232}Ak ho rozmliadiš, prídeme o hodne peòazí!
{29247}{29273}Hej...
{29276}{29361}Urob to, Melfina! Jim je pod jeho kontrolou!
{29374}{29398}Á-Áno.
{29406}{29433}Prepáè, Jim.
{29436}{29477}Nerob to, Melfina!
{29517}{29541}Prestaò, ksakru!
{29547}{29585}Stoj! Stoj, krucinál!
{29634}{29724}Nie! Patrím k ove¾a vyššiemu druhu! Èo mi to robíš?
{29736}{29777}Prestaò! Prestaò s tım!
{29840}{29920}Ako sa opovaujete, vy niší ivoèíchovia!
{29951}{29983}Prestaò! P-Prestaò s tım!
{29987}{30017}Prestaò, prosím!
{30030}{30124}Prosím a... Prestaò, prosím...
{30195}{30223}Je po òom.
{30233}{30315}U ma viac nedonútiš jes iadnu hnusnú zmrzlinu.
{30334}{30380}Hnusnú zmrzlinu...?
{30412}{30442}Krucinál, nie!
{30462}{30525}Idem zabi tú obludu!
{30532}{30602}Nedovolím, aby polícia zoala všetku slávu!
{30603}{30638}Akı zmätok.
{30639}{30725}Ten Silgrian teraz skrachuje, a my u neuvidíme iadne prachy.
{30729}{30769}Hej, tie si myslím.
{30771}{30861}Kadopádne, asnem, e a tá vec nedokázala ovládnu, Melfina.
{30867}{30938}Nie som ako normálni ¾udia.
{30994}{31045}Práve to zachránilo Jima.
{31046}{31106}Má pravdu. Ïakujem moc, Melfina.
{31140}{31165}Áno!
{31290}{31329}Vypadá to, e ten Silgrian bol...
{31330}{31396}...pod kontrolou toho "Ve¾kého", keï ho sem priviezol.
{31422}{31516}Vraj bol v kapsuli, ktorú Vesmírne jednotky našli hlboko vo vesmíre.
{31522}{31551}Rozumiem.
{31562}{31657}Nakoniec, všetko, èo za to máme je tá záloha 700 wongov...
{31670}{31694}A èo ty, Gene?
{31701}{31717}Ja?
{31719}{31768}Mal si prácu, pravda?
{31774}{31862}Hej, ale ten rozruch to všetko prekazil.
{31866}{31926}Sakra, rozhodne to všetko pokazil...
{31942}{32026}Keby nenastal ten blbı zmätok, urèite by som bodoval.
{32035}{32061}Bodoval?
{32066}{32134}Uh, hej. V poriadnej práci, mám na mysli.
{32150}{32189}Oh. Nehovorte?
{32210}{32242}Sklapni!
{32244}{32283}Vrá sa spä na loï!
{32285}{32303}Dobrı deò.
{32305}{32335}- Vitajte--|- Vitajte--
{32350}{32385}Èo? To so ty.
{32389}{32435}Ako idú obchody?
{32446}{32461}Ide to.
{32462}{32498}Vôbec nie.
{32537}{32640}Mala som pocit, e by to tak mohlo by, tak som vám prišla poveda o práci.
{32642}{32663}Èo také?
{32665}{32722}Na okraji Heifong City sa nachádza zábavnı park
{32727}{32810}a h¾adajú tam ¾udí do šou o Divokom západe.
{32919}{32962}Èo to má znamena?! Aké hrubé!
{32968}{33061}Keï ¾udia nedokáu prija s vïakou malú láskavos, je to koniec ¾udstva!
{33094}{33144}Dúfam, e sa èoskoro naskytne dobrá práca...
{33155}{33176}Haló!
{33196}{33225}Istee.
{33242}{33297}Gene! Potrebujú vleènú loï!
{33304}{33352}Vezmi to. Nemáme na vıber.
{33354}{33396}Nieèo sa èoskoro vyskytne.
{33651}{33773}Jedného tichého dòa,
{33791}{33942}vietor bol èerstvı a sviei.
{33956}{34250}Lupene kvetov sa chveli, akoby spali.
{34261}{34481}Tento pocit pokoja...
{34494}{34868}Tak, aké mu ¾udia dali meno?
{34890}{35187}V bielom piesku mesiaca, príbeh je uschovanı,
{35206}{35533}Poèúvam ho, ako keï svetlo svieti, pokojne.
{35671}{35730}Tentokrát sa pozrieme na zneškodòovanie takej malej bomby!
{35736}{35813}Posledné odpoèítavanie môjho ivota sa zaèalo!
{35829}{35858}Èo mám robi, ksakru?
{35866}{35910}Nevyznám sa v takıchto jemnıch prácach...
{35914}{35983}...a som takı vystresovanı, e sa nemôem ani vyèúra!
{35987}{36079}Chápete, pravda? Keï nedám pozor, BUM!
{36099}{36194}Nabudúce v Outlaw Star!|"Posledné odpoèítavanie!"
{36207}{36256}Radšej sa pripravte!
