{1}{1}23.976
{109}{183}Jeden zlodej raz povedal toto:
{192}{262}"Mono kradnem, ale nie som ne¾udskı."
{276}{361}A Outlaws, ktorí teraz putujú vesmírom vravia toto:
{370}{442}"Aj keï neporušuješ zákon, nebuï ním viazanı."
{455}{525}Pıcha zlodeja. Kódex piráta.
{530}{573}Hrdos Outlaw.
{594}{690}Mono je to len biedna lo na presvedèenie samıch seba a ostatnıch,
{701}{817}e takí naozaj sú poved¾a poctivıch a èestnıch ¾udí.
{846}{941}Ale, èi u je to pravda alebo nie,
{954}{1073}Outlaws majú kódex, na ktorı sú hrdí.
{1094}{1193}Ale na druhej strane, ïalšou pravdou je,
{1202}{1362}e grázli, ktorí nemajú iaden kódex, spôsobujú ve¾ké problémy.
{1485}{1565}Semenaide, kesanaide, makenaide...
{1566}{1688}...daredatte motteru|hazu yuzurenai mono.
{1706}{1780}Ai dake, yume dake, kimi dake...
{1782}{1923}...sore dake wa hanasanai,|donna toki de mo.
{1981}{2081}Dou shiyou mo naku,|ochitsukanai yoru...
{2083}{2195}...nani mo ka mo nagedashitaku naru.
{2197}{2295}Tsubekobe iwazuni,|sassa to doa wo akena.
{2297}{2405}Rikutsu nante, koneteru hima wa nai.
{2412}{2617}Juu'ou-mujin tobimawaritai,|you'i-shuutou mamoritakunai!
{2622}{2803}Nakushita wakeja nai,|mada hajimattenai dakara.
{2819}{2902}Semenaide, kesanaide, makenaide...
{2904}{3022}...daredatte motteru|hazu yuzurenai mono.
{3039}{3119}Ai dake, yume dake, kimi dake...
{3121}{3239}...sore dake wa hanasanai,|donna toki de mo.
{3268}{3372}Nani ga hoshii? Nani ga|shitai? Doko ni ikitai?
{3378}{3530}Yami wo saite hashirinukete|tsukamitore through thenight!
{3952}{4001}Gene! Si si istı, e to chceš?
{4006}{4088}Upokoj sa. Musím akurát prestrihnú jeden z nich.
{4201}{4275}Ak prestrihneš nesprávny drôt, vybuchne nám to do tváre!
{4285}{4348}Take šance sú 50 na 50...
{4350}{4378}Hej, dôverujte mi!
{4385}{4441}Mono to neviete, ale hazardovanie je moja špecialita!
{4442}{4471}Klamár!
{4473}{4548}BillSK & Pedro uvádzajú:|OUTLAW STAR:"Posledné odpoèítavanie!"
{4706}{4769}Dok 217, pripravenı na vstup.
{4786}{4885}Gorgeous Mitsuru, poïte zo smeru 7A 12, prosím.
{4902}{4959}382, poponáh¾ajte sa s tımi prípravami!
{5059}{5088}Perfektné...
{5097}{5208}Jak to, e mi prischla taká biedna práca vesmírneho remorkéru?
{5217}{5333}Súhlasím. Toto nie je práca pre najdokonalejšiu grapplerovú loï v galaxii.
{5374}{5417}Nad èím tam fòukáte?
{5426}{5501}Dostali ste akurát za úlohu odtiahnu reklamnú loï!
{5505}{5611}Mieri vaším smerom na kurze 9C3, tak ju dotiahnite spä do prístavu!
{5621}{5729}Vlastne, vy ¾udia ste zvyknutí pracova kadı deò!
{5738}{5799}- Zarábaj na svoj kadodennı chleba!|- Jim, zavri kanál.
{5811}{5832}Take--
{5879}{5945}Nu, keï pomôeme s touto prácou na stanici,
{5946}{6011}dajú nám z¾avu na parkovacom poplatku.
{6018}{6151}Aj tak, prvı medzi súkromníkmi na vesmírnych závodoch a funguje ako remorkér...
{6160}{6246}Keï o tom hovoríme, zdá sa, e ten závod bol dobrou reklamou.
{6262}{6315}Sme akurát na smiech!
{6321}{6414}Kruci, èo je tu taká tlaèenica?
{6422}{6488}Poèul som, e klenotníctvo na stanici má...
{6498}{6547}...nejakú ve¾kú vıstavu na oslavu svojej renovácie.
{6578}{6641}To je ona. To je tá reklamná loï, ktorú Aisha spomínala.
{6754}{6805}Mel! Vypoèítaj kurz na miesto stretnutia!
{6810}{6825}Áno.
{6827}{6896}Zásnubnı prsteò stojí tri mesaèné platy.
{6904}{6938}Je obrovská...!
{6946}{6980}Je prive¾ká.
{6982}{7058}Upúta pozornos, to je fakt, ale nedokáe robi ostré zákruty,
{7060}{7101}take dosta ju do prístavu je problém.
{7106}{7160}A práve preto potrebujú vleènú loï, nie?
{7166}{7220}Dos bolo reèí, ide sa do práce.
{7325}{7371}Zosúlaïujem vzájomné rıchlosti.
{7474}{7522}Okej, hotovo.
{7530}{7598}Dobre, zaènem spoma¾ova a navediem nás na pristávací kurz.
{7734}{7754}Èo to--?
{7810}{7849}"Mám a"?
{7851}{7886}Prenikanie vírusu.
{7890}{7926}Prenikanie vírusu.
{7931}{7995}Nemoné vyèisti. Systém sa vypína.
{8198}{8266}Vírus sa dostal do systému cez tie kotvy.
{8277}{8322}Gilliam je úplne vypnutı.
{8369}{8405}Blahoelám!
{8407}{8494}Boli ste vybraní na vılet do neba!
{8509}{8532}Èoe?
{8572}{8645}Aisha, máme prácu! Zavolaj neskôr!
{8662}{8764}¼udia, ktorım zostáva len pä hodín ivota nemajú moc èasu na "neskôr".
{8769}{8801}Kto, ksakru, si?
{8810}{8901}Môete ma zatia¾ vola Crackerjack.
{8914}{8941}Zatia¾?
{8942}{8978}Upokojte sa.
{8986}{9063}Moje meno je momentálne váš najmenší problém.
{9069}{9195}Tá reklamná loï, s ktorou ste spojení, obsahuje ve¾mi silnú bombu.
{9197}{9232}Bombu?
{9244}{9386}Ak nebudú splnené naše poiadavky, vybuchne aj s vašou loïou.
{9402}{9465}Èasovı limit je pä hodín.
{9470}{9501}To je šialené!
{9510}{9555}Aké sú tie vaše poiadavky?
{9559}{9597}Sledujte toto.
{9619}{9710}Opakujem, my, ¼udovı oslobodzovací front, iadame...
{9715}{9760}...okamité odstúpenie miestokrá¾a Heifongu,
{9762}{9824}ktorı je len bábkou Impéria Tempa,
{9826}{9904}rovnako ako aj zaruèenie úplnej nezávislosti Heifongu!
{9910}{9919}Preè so zlou koloniálnou vládou...
{9919}{9950}Nezávislos?|Preè so zlou koloniálnou vládou...
{9950}{9976}Nezmysel...|...ako vtedy na starej Zemi!
{9976}{9998}...ako vtedy na starej Zemi!
{10006}{10037}Poèuli ste teda.
{10038}{10129}Ak budú naše poiadavky bezpodmieneène splnené, budete vo¾ní
{10134}{10219}Ozaj, bomba je ve¾mi chúlostivá.
{10225}{10299}Ak sa ju pokúsite zneškodni, okamite vybuchne.
{10303}{10380}Prosím, nepomıš¾ajte na iadnu hlúpos.
{10392}{10465}Uite si to, dentlmeni.
{10568}{10602}- Èo teraz?|- Vybuchne to?
{10659}{10692}Zmenil našu dráhu.
{10704}{10748}Mel! Vypoèítaj našu dráhu!
{10753}{10776}A-Áno.
{10783}{10832}Jim, daj dokopy hlásenie o škodách.
{10835}{10854}Idem na to!
{10902}{10978}Poiadavkou teroristickej skupiny ¼udovı oslobodzovací front,
{10980}{11063}ktorá je zodpovedná za únos vleènej lode neïaleko stanice,
{11065}{11117}nie je niè iné ne nezávislos Heifongu!
{11124}{11254}Ako odpovie miestokrá¾ na takéto neslıchané poiadavky?
{11272}{11331}Heifong nikdy nebude nezávislı.
{11346}{11448}Nemôeme ustúpi teroristom, ani tu na pohranièí.
{11453}{11470}Áno.
{11472}{11545}Ani keï to znamená obetova ivoty rukojemníkov.
{11571}{11663}Práve máme potvrdenú registráciu unesenej vleènej lode!
{11674}{11730}Tak, kto sú tí blbci?
{11742}{11800}Zistilo sa, e tou loïou je Outlaw Star,
{11803}{11906}a rukojemníkmi sú jej kapitán, Gene Starwind, plus ïalší dvaja.
{11916}{11941}Gene?!
{11965}{12008}Vymazal som vírus,
{12016}{12106}ale pamä je dos poškodená, take Gilliam je stále vypnutı.
{12114}{12172}Systém cirkulácie kyslíka stále ešte funguje,
{12178}{12214}ale regulátor teploty je odstavenı.
{12228}{12305}Zbrane a navigácia sú samozrejme úplne mimo prevádzku.
{12312}{12356}Ovládanie vıšky je asi tak všetko, èo môeme.
{12366}{12401}Ani poklopy nejdú otvori!
{12411}{12501}Take nemôeme nakoniec ani opusti loï, ani keby sme chceli.
{12517}{12559}Je tu nieèo, èo funguje?
{12561}{12625}Grapplerové ramená sú asi tak všetko.
{12634}{12698}Ich systém je napojenı priamo na kokpit.
{12732}{12799}Dokonèila som vıpoèet našej dráhy. Dám to na obrazovku.
{12826}{12905}Obiehame nad rovníkom Heifongu III a strácame vıšku.
{12923}{13042}To je zlé! Znamená to, e aj keï tá bomba nevybuchne, za pä hodín...
{13055}{13138}...narazíme aj s tou bombou priamo do stanice.
{13165}{13219}Pre túto stanicu bol vyhlásenı príkaz na evakuáciu.
{13229}{13298}Všetci, prosím, pokojne, ukáznene evakuujte stanicu.
{13311}{13358}Opakujem, príkaz na evakuáciu...
{13360}{13383}Moje šperky!
{13389}{13441}Pani, dosta sa odtia¾to je dôleiejšie!
{13453}{13491}Veï sú poistené, nie?!
{13494}{13516}Ale--!
{13518}{13565}Prosím, nepanikárte! Prosím, zachovajte pokoj!
{13567}{13634}V lodiach je dos miesta pre kadého.
{13644}{13690}Gorgeous Mitsuru, odlietam!
{13702}{13737}Mierte k palube 28!
{13748}{13787}Presne pod¾a plánu...
{14018}{14046}Spustite operáciu!
{14054}{14126}Lode opúšajú stanicu jedna za druhou.
{14131}{14149}Vıpoèty ukazujú, e stanica...
{14149}{14210}- Gene! Èo sa deje tam hore, Gene?!|- Vıpoèty ukazujú, e stanica...
{14210}{14224}...bude zasiahnutá podmínovanou loïou...
{14224}{14241}- Buï ticho!|- ...bude zasiahnutá podmínovanou loïou...
{14241}{14286}- Jim! Vypni vysielanie!|- Miestokrá¾, aby zabránil ohrozeniu ivotov...
{14291}{14331}- Komu vravíš, aby bol ticho?!|- vydal evakuaènı--
{14350}{14368}Ha?
{14371}{14438}Krièa naòho odtia¾to niè nevyrieši.
{14451}{14499}Tak, èo budeme teda robi?
{14525}{14614}Idem sa spıta toho, kto tú bombu zostrojil, ako ju zneškodni.
{14667}{14731}Spıta sa toho, kto to spôsobil, je najistejšie.
{14778}{14810}H-Hej, poèkaj!
{14816}{14871}Ako chceš nájs toho bombera?!
{14890}{14921}Mám zlé správy, pán miestokrá¾!
{14926}{14947}Èo také?
{14953}{15010}Simulácia nárazu podmínovanej lode do stanice...
{15011}{15077}...predpovedá, e orbitálny vıah sa zrúti na pevninu!
{15078}{15097}Èoe?!
{15098}{15155}Nesmieme ohrozi planétu!
{15174}{15276}Skôr ne sa dostane ku stanici, musíme ju odpáli aj s rukojemníkmi.
{15278}{15302}To je...
{15314}{15363}Pod¾a teroristov je tá loï naloená...
{15365}{15432}...ve¾kım mnostvom rádioaktívneho materiálu.
{15467}{15506}Nemôeme urobi niè?
{15539}{15575}Gene, naozaj to chceš spravi?
{15585}{15633}Máš nejakı inı nápad?
{15638}{15725}Nie, ale je to šialené, keï sa amatér pokúša zneškodni bombu!
{15736}{15765}Uká trochu odvahy!
{15767}{15813}Mel, ty vykonaj skenovanie.
{15818}{15837}Áno.
{15839}{15885}Teraz spúšam infraèervenı skener.
{16244}{16309}Potrebujeme akurát preruši prívod energie do rozbušky.
{16320}{16401}Nelíši sa to od prestrihnutia kábla k zapa¾ovacej svieèke, e?
{16411}{16506}Motor nevybuchne, keï prestrihneš nesprávny kábel k svieèke.
{16527}{16611}Infraèervené skenovanie hotové. Dám to na obrazovku.
{16642}{16707}Èoe, je to takmer prázdne?
{16716}{16748}Je to kamuflá.
{16761}{16848}Mono práve preto prešli kontrolou, skôr ako sa vydali k prístavu.
{16873}{16942}Take, nedokáeme zisti, èo je vnútri, kım to neotvoríme, e?
{16978}{17062}A èo registrácia majite¾a tej reklamnej lode?
{17064}{17158}T-túto informáciu môeme da iba polícii...!
{17168}{17224}Prestaò sa vykrúca a povedz nám, èo chceme vedie!
{17316}{17396}Musíme to risknú. Musíme sa pozrie dnu!
{17400}{17429}Nerob to, Gene!
{17433}{17457}Tie si myslím.
{17475}{17499}To je ono?
{17554}{17581}Poïme...
{17619}{17658}Nammaida, nammaida, nammaida,
{17660}{17706}nammaida, nammaida, nammaida,,,
{17857}{17881}Èoe--?!
{17978}{17990}Gene!
{17994}{18068}Produkcia: BillSK|Spracovanie videa: Randy
{18070}{18116}Nie je urèené pre komerèné pouitie.
{18117}{18194}Slovenské titulky: Pedro (pedro_k@post.sk)
{18380}{18451}Nedostávam iadnu odozvu z konca pravého grapplerového ramena.
{18468}{18531}Okrem tohto, nezdá sa, e by bolo nejaké váne poškodenie.
{18538}{18586}Vznikol problém...
{18590}{18642}Veï som vravel, e by sme na to mali zabudnú!
{18695}{18734}Jim, vystopuj signál!
{18738}{18761}U idem!
{18810}{18843}Tu je Outlaw Star.
{18858}{18920}Nevravel som vám, aby ste neskúšali iadne vylomeniny?
{18922}{18979}Sklapni! Bol to len nejakı blbı bluf!
{18986}{19040}Nemalo to vari celé vybuchnú?
{19049}{19118}Prišli by sme o všetko, keby to takı idiot ako ty odpálil...
{19121}{19226}...skôr ako miestokrá¾ vyhovie naším poiadavkám.
{19241}{19349}Aj tak, ak sa ešte o nieèo pokúsite, nabudúce nevyviaznete len s varovaním.
{19357}{19470}Take, to môme rovnako skúsi tú bombu, na ktorú si tak hrdı, aj zneškodni?
{19472}{19540}To nie! Teroristu by si nemal rozèu¾ova!
{19620}{19719}Ohromné! Naletel si hneï na tú najjednoduchšiu pascu,
{19725}{19823}a tvrdíš, e zneškodníš bombu, ktorú som osobne vyrobil?
{19834}{19912}Nerob zo seba frajera, pilot remorkéru!
{19928}{19997}Ani šialenı bomber nemá právo tak machrova.
{20019}{20090}Ak chceš, pusti sa do toho a uká, èo v tebe je.
{20095}{20137}Ve¾a šastia zatia¾.
{20162}{20207}Ten bastard sa fakt rád poèúva...
{20214}{20244}Vystopoval si ho?
{20246}{20271}Je to beznádejné.
{20277}{20333}Normálne rádiové vlny nemajú smer.
{20343}{20460}Ale nebola tam iadna èasová odozva, take je zrejme do 30 000 km alebo tak.
{20470}{20506}30 000, èo...?
{20514}{20586}V tomto okruhu nezaznamenávam iadne vesmírne lode.
{20603}{20641}Vyzerá to, e túto oblas evakuovali.
{20646}{20675}Sú teda na povrchu?
{20677}{20745}Hlupák. Myslíš, budú trèa na povrchu,
{20746}{20804}keï hrozí, e orbitálny vıah padne dolu?
{20831}{20878}Tak, kde si myslíš, e sú?
{20894}{20948}Jim! Môeme vysiela rušiaci signál?
{20958}{20991}Rušiaci signál?
{21006}{21087}Komunikaènı systém funguje, take myslím, e by som mohol nieèo vymyslie.
{21321}{21392}Zdá sa, e má predsa len rozum...
{21489}{21578}Tón sa zmenil. Toto je jediné miesto, kde to znie odlišne.
{21585}{21618}Fajn, take toto je ono!
{21621}{21661}Jim, môem poui plameòovı rezaè?
{21674}{21720}Nie, je napojenı na energetickı systém.
{21728}{21789}Avšak kotúèová píla má vnútorné batérie, take môeš poui tú.
{21914}{21996}Anokutara sanmyaku sanbodai, anokutara sanmyaku sanbodai...
{22171}{22220}Bingo! To je ono!
{22222}{22270}Neblbni! Toto je ozajstné!
{22284}{22312}Poïme...
{22543}{22600}Preèo si musel spravi toto?
{22606}{22693}Ten malı, podlhovastı predmet, sa zdá by detonátor.
{22703}{22763}Myslíš, e je vnútri vıbušnina?
{22777}{22867}Jeden z tıch dvoch drôtov prenáša detonaènı signál!
{22880}{22937}Èo myslíš, naèo je potom ten druhı?
{22953}{23026}Vyrástol som na filmoch, kde boli bomby.
{23042}{23118}V okamihu, keï sa prestrihne nepravı drôt, zopne sa spínaè,
{23122}{23188}ktorı vyšle signál do toho pravého a BÁC.
{23202}{23237}Èo urobíme, Gene?
{23244}{23294}Zostáva len jediná vec!
{23566}{23612}Gene, si si istı, e to chceš?
{23623}{23703}Pokojne. Musím akurát prestrihnú jeden z nich, nie?
{23714}{23786}Ak prestrihneš nesprávny drôt, vybuchne nám to do tváre!
{23797}{23860}Take šance sú  50 na 50...
{23866}{23897}Hej, dôverujte mi!
{23901}{23955}Mono to neviete, ale hazardovanie je moja špecialita!
{23958}{23990}Klamár!
{24141}{24198}Èervenı... èi modrı...?
{24238}{24335}To¾ko vıbušniny, e ak to zvàtam, je naisto po nás.
{24450}{24506}Teda, nemôem uveri, e sa zrovna teraz dokáeš smia.
{24510}{24549}Si u fakt frajer.
{24570}{24685}Keï mám strach... blbé veci sa mi zdajú smiešne...
{24700}{24749}...a ja sa nemôem presta smia.
{24804}{24835}Je to šibnuté, e?
{24910}{24987}Bude to v poriadku. Viem, e všetko vıjde.
{25022}{25053}M-Mel...
{25054}{25113}Tak, èo poviete, vyskúšame svoje šastie?
{25173}{25198}Poïme na to!
{25298}{25359}Èo je...? Vari si nevyslal rušiaci signál?
{25370}{25449}Je to usmernenı laserovı prenos! Prichádza zo stanice.
{25460}{25521}Zo stanice? Niekto je stále tam?
{25539}{25574}Èo to tam robíte?!
{25575}{25590}Aisha?
{25592}{25654}Vysielaèka nefungovala, take nebolo ¾ahké sa s vami spoji!
{25658}{25709}Èo robíš na stanici?
{25714}{25787}Sledovala som teroristov pach a ten ma doviedol sem!
{25794}{25818}Jeho pach?
{25820}{25854}Vymıš¾a si.
{25859}{25921}Pokúsili sme sa vystopova informáciu o majite¾ovi lode,
{25924}{25986}ale bola falošná, take sme sa ocitli v slepej ulièke.
{25988}{26061}Take sme presvedèili Freda Luo, aby nám to povedal!
{26069}{26142}Fred, èo? Urèite a to ve¾a stálo.
{26150}{26172}Nie.
{26195}{26281}Ve¾mi spolupracoval, keï som mu povedala, e to je pre tvoje dobro.
{26286}{26363}Dokonca nám zdarma poièal raketoplán, aby sme sa sem dostali!
{26373}{26418}Tak, èo ste zistili o teroristoch?
{26433}{26505}Pod¾a Lua, registrácia tej reklamnej lode je v skutoènosti falzifikát,
{26507}{26594}ktorı piráti predali na èiernom trhu!
{26602}{26624}Piráti?
{26630}{26738}A tak sme Lua presvedèili, aby zistil komu to piráti predali.
{26742}{26808}Prestaòte to tak naahova. Hovorte priamo k veci!
{26821}{26895}Kupcom bol šéf známej bandy lupièov.
{26928}{26990}Nemôem obetova ivot nikoho na Heifongu III.
{26995}{27071}Miestokrá¾ tımto akceptuje vaše poiadavky.
{27075}{27126}Uznávam nezávislos Heifongu!
{27139}{27273}My chceme uznanie z Impéria Tempa.
{27281}{27363}Rozhodnutie miestokrá¾a je pre nás úplne zbytoèné.
{27367}{27457}Èoe?! Chcete poveda, e ste nikdy nemali v úmysle--
{27609}{27696}Nie sú to teroristi, sú to lupièi...?
{27705}{27806}Preèo by lupièi iadali nezávislos Heifongu?
{27815}{27891}U viem! Tá vyhráka bombou je trik!
{27910}{27989}Všetko to bol trik ako vyprázdni vesmírnu stanicu!
{27999}{28037}Ale preèo?
{28344}{28408}Teraz u viem ako ten chlap uvauje.
{28426}{28458}Stavím sa, e toto je tie falošné.
{28468}{28533}Vybuchne to nech prestrihnem ktorıko¾vek drôt!
{28539}{28612}Kde je teda skutoènı detonátor?
{28628}{28693}Skontrolujem vnútro toho otvoru, kde to predtım vybuchlo.
{28700}{28774}Ak dobre uvaujem, detonátor je tam!
{28782}{28867}Rozumiem... Nikto by neh¾adal niekde, kde sa u díval.
{28966}{28987}Je tam stena!
{29041}{29081}Zaznamenávam slabı mechanickı zvuk.
{29087}{29120}To je urèite ono...
{29122}{29175}Jim, môem ešte poui pílu?
{29183}{29263}Ak vyreeš len malú dieru, tak by to batérie mohli vydra!
{29267}{29327}Fajn, tentokrát to dokáeme!
{29333}{29390}Ale ak tam aj je skutoènı detonátor,
{29394}{29453}èo urobíš, keï tam zase budú dva drôty?
{29460}{29578}Ten chlap si o sebe ve¾a myslí. Nemyslím, e by pouil rovnakú pascu.
{29584}{29667}No a keby aj, jednoducho ver môjmu šastiu a intuícii!
{29793}{29824}Dobre, je èas.
{29889}{29909}Poïme!
{29958}{29981}Kto ste?!
{29982}{30068}Naša reè, Crackerjack.
{30082}{30153}Lúpe pod pláštikom terorizmu...
{30158}{30221}Áno, musíš by skvelı, to je fakt.
{30238}{30268}A-Ako ste to zistili?
{30270}{30337}Fakt neznášam bastardov ako ste vy,
{30341}{30384}ktorí si naplánujú kadú malièkos!
{30402}{30423}Na nich!
{31186}{31273}Jedine ty si zostal, Crackerjack.
{31289}{31356}È-Èo chcete, vy dve?
{31412}{31482}Ak chcete podiel, èo takto polovicu?
{31489}{31527}T-Takmer nám vypršal èas.
{31532}{31614}Tá loï s bombou mieri k stanici!
{31622}{31685}- Oh¾adne tohto...|- S tım sa netrápte.
{31692}{31717}Èoe?
{32151}{32222}Hej! Napokon sme sa stretli, Crackerjack!
{32238}{32277}Nie je moné! Ty?!
{32284}{32322}Tomu ver.
{32329}{32427}Zneškodnili sme tú tvoju bombu a zbavili sa jej u dávno.
{32432}{32449}Ty--
{32565}{32628}Bolo to srandovnıch pä hodín, Crackerjack.
{32658}{32683}Bastard!
{32987}{33043}Odpoèítavanie skonèilo.
{33233}{33339}Obloha, ïaleká obloha...
{33350}{33468}Šepotavı hlas...
{33491}{33755}Tvoje sny teraz otáèajú kolesom hviezd.
{33779}{34037}Nikdy som nikde nebola.
{34054}{34167}Tak som sa cítila,
{34172}{34319}kım som nespoznala poh¾ad tvojich oèí.
{34326}{34545}V kúte môjho srdca je len kúsok mesiaca.
{34562}{34859}Ale je dos jasnı, aby osvietil aj tú najušiu cestu.
{35403}{35518}Títo Kei to koneène zaèali bra váne a pokúšajú sa nás rozdrvi.
{35528}{35567}Je ich sedem?
{35574}{35615}Vyzerám snáï ako Snehulienka?
{35622}{35704}Kadopádne, zdá sa, e príbeh zaèína by koneène zaujímavı!
{35717}{35779}Robi takéto nieèo nie je ¾ahké!
{35786}{35831}Dajte mi viac peòazí niekto!
{35833}{35927}Nabudúce v Outlaw Star!|"Sedmièka sa objavuje!"
{35937}{35989}Radšej sa pripravte!
