{1}{1}23.976
{110}{270}Vytvorenie Munchhausenovho pohonu|bolo moné vïaka éterovému fyzikovi...
{293}{383}Dr. Samovi Kaseinpowovi,|echnologickej skupine spoloènosti Chosong Science,
{397}{457}ktorú viedol profesor Hata Ikke,|obrovskım peòanım príspevkom...
{458}{540}od kadej krajiny,|a predovšetkım vïaka Dragonitu.
{568}{639}V roku 1 Hviezdneho kalendára sa|Dragonite, neznámy kryštalickı materiál...
{641}{712}...objavenı v meteorite, ktorı sa zrútil...
{714}{770}...v Arašanskej púšti v severnej Èíne,|ukázal by katalyzátorom,
{772}{890}ktorı uvo¾òuje nesmierne mnostvo energie|z nevyèerpate¾ného éteru.
{917}{1004}V honbe za Dragonitom sa ¾udstvo|vydalo do vesmíru.
{1015}{1106}Bola to zlatá horúèka Vesmírneho veku.
{1130}{1265}Avšak Dragonit bol v roz¾ahlom vesmíre ve¾mi vzácny.
{1286}{1358}Skúmajú sa síce chemické metódy umelej syntézy,
{1359}{1445}ale k dokonalosti majú ešte ïaleko.
{1461}{1527}Ako neobnovite¾nı zdroj je Dragonit vysoko cenenı...
{1537}{1656}a je najvzácnejšou, najcennejšou substanciu na tomto svete.
{1786}{1867}Semenaide, kesanaide, makenaide...
{1870}{1989}...daredatte motteru|hazu yuzurenai mono.
{2007}{2081}Ai dake, yume dake, kimi dake...
{2084}{2225}...sore dake wa hanasanai,|donna toki de mo.
{2285}{2382}Dou shiyou mo naku,|ochitsukanai yoru...
{2386}{2494}...nani mo ka mo|nagedashitaku naru.
{2498}{2597}Tsubekobe iwazuni,|sassa to doa o akena.
{2599}{2704}Rikutsu nante,|koneteru hima wa nai.
{2710}{2918}Juu'ou-mujin tobimawaritai,|youi-shuutou mamoritakunai!
{2925}{3105}Nakushita wakeja nai,|mada hajimattenai dakara.
{3121}{3202}Semenaide, kesanaide, makenaide...
{3205}{3324}...daredatte motteru|hazu yuzurenai mono.
{3337}{3419}Ai dake, yume dake, kimi dake...
{3422}{3541}...sore dake wa hanasanai,|donna toki de mo.
{3570}{3673}Nani ga hoshii? Nani ga shitai?|Doko ni ikitai?
{3677}{3832}Yami o saite hashirinukete|tsukamitore through the night!
{4423}{4514}BillSK & Pedro uvádzajú:|OUTLAW STAR:|"Démon z vodnej planéty!"
{4738}{4781}Vonia to dobre!
{4891}{4929}Hej, brigádnièka!
{4931}{5003}Èo tam tak postávaš?!|Odnes to k tomu stolu!
{5008}{5031}Áno...
{5042}{5079}Prepáète za zdranie...
{5154}{5233}V-V-Vy?! Preèo?!
{5290}{5325}A-Aisha?
{5332}{5411}Èo tu robíte?! Ako to, e si môte objedna takéto jedlo?!
{5418}{5466}Kde ste vzali to¾ké peniaze?!
{5472}{5509}Platí to zákazník.
{5526}{5562}Èakáme tu naòho.
{5567}{5623}Je to fakt štedrı klient.
{5630}{5708}Povedal, e si môeme da hocièo, kım tu budeme naòho èaka.
{5731}{5752}To je skvelé!
{5754}{5837}Je to tuèné a šavnaté, ale pritom to nemá zlú pachu!
{5846}{5865}Však, Mel?
{5866}{5905}Oh. Tak je.
{6001}{6055}No... Ak chceš, vezmi si toto.
{6091}{6123}Dám si to!
{6125}{6157}HEJ, BRIGÁDNIÈKA!
{6163}{6223}Prestaò sa fláka!|Švihaj sem!
{6254}{6290}Áno...
{6627}{6675}Náš klient je tu.
{6717}{6766}Tak, èo môeme pre vás urobi?
{6780}{6853}Po telefóne ste vraveli, e nieèo h¾adáte.
{6899}{6941}Poklad.
{6945}{6963}Huh?
{6965}{6990}Poklad?
{7011}{7109}Po pravde, u som ten poklad našiel.
{7122}{7189}Na istú planétu sa zrútila loï.
{7196}{7257}Vy musíte akurát ten poklad vyzdvihnú.
{7304}{7413}Záchranná operácia? S naším vybavením to môe by trochu...
{7422}{7476}S Grapplerovou loïou to nebude problém.
{7492}{7600}Videl som vašu loï v prístave.|Je to dobré plavidlo.
{7614}{7657}Gilliam by bol šastnı, keby to poèul.
{7669}{7716}Ale preèo Grapplerovú loï?
{7730}{7803}Prostredie na tej planéte je trochu... vınimoèné.
{7809}{7862}Grapplerova loï je pre to najlepšia.
{7881}{7914}Èo myslíte tım "vınimoèné"?
{7926}{7979}Momentálne nemôem poveda viac.
{7989}{8018}A ten poklad?
{8022}{8087}Nieèo v hodnote najmenej pä miliónov wongov.
{8089}{8126}P-Pä miliónov?
{8128}{8150}Drahokamy?
{8170}{8221}Vravel som, e vám nemôem poveda viac.
{8234}{8290}Závisí to na vašej odpovedi.
{8339}{8381}L-Len okamih, prosím.
{8401}{8430}Èo spravíme?
{8432}{8470}Je to podozrivé.
{8491}{8561}Staèí sa pozrie na toho deda a hneï vieš, e nieèo nesedí.
{8562}{8653}To je isté. H¾adanie pokladu a ten starı pán.
{8660}{8718}Normálne by som sa o nieèo takéto nezaujímal.
{8728}{8816}Aj keby to bola polovica, je to stále 2,5 milióna. Budeme boháèi!
{8834}{8889}Ale pomáha tomu dedovi?|Ja ti neviem...
{8891}{8947}Hej, to je problém, fakt...
{8949}{9010}Je to prekliato podozrivé.
{9035}{9113}Hej, ale naša peòaenka je prekliato prázdna.
{9121}{9168}Nepáèi sa mi to, ale èo treba to treba.
{9176}{9219}Èo vravíš?|Ís len tak naslepo?
{9226}{9291}A dúfa, e rıchlo zbohatneme!
{9360}{9398}Prepáète, e to trvalo tak dlho.
{9400}{9513}Po starostlivom prehodnotení sme sa, váenı pane, rozhodli prija vašu ponuku.
{9546}{9562}Ale...
{9564}{9609}Volajte ma len Dedo.
{9617}{9639}Nie!
{9648}{9710}"Váenı pane" znie prehane lichotivo.
{9720}{9790}Volajte ma "Starı pán" alebo "Dedo",|akoko¾vek chcete.
{9848}{9919}Niet divu, e mi nedôverujete.
{9934}{9997}Ten príbeh je dos podozrivı.
{10010}{10050}No... To je...
{10102}{10183}Fajn, fajn! Niekto prostoduchı,
{10185}{10233}kto by tú prácu vzal okamite, by to nezvládol!
{10245}{10297}Ale to znamená, e ja sa tie nespolèím len tak s hocikım,
{10299}{10353}kto nemá vôbec odvahu ís za svojim snom.
{10366}{10406}Prešli ste, ¾udia.
{10430}{10457}Som poctenı.
{10482}{10527}Páèi sa mi vıraz v tvojich oèiach.
{10568}{10671}Sú to oèi Outlaw, ktorı by v honbe za svojim snom išiel kamko¾vek!
{10770}{10797}Skap, dedo!
{10799}{10828}Toto je za nášho brata!
{11002}{11038}Vylez dedo!
{11098}{11161}Zdá sa, e idú len po tom starom muovi.
{11236}{11303}Kadı, kto strie¾a mojím smerom je nepriate¾.
{11394}{11421}To je smiešne.
{11590}{11662}Nikto nebude beztrestne plıtva jedlom!
{12063}{12125}Keï to Aishu pochytí,|úplne sa vymkne kontrole...
{12130}{12173}Nemal si sa mieša a zaèa strie¾a.
{12185}{12241}Ale, èo sú to za ¾udia?
{12258}{12309}¼udia, ktorí sa ma snaia zabi.
{12349}{12369}Kedy ste--?
{12370}{12456}Zabudol som vám poveda, ale idú po mne istí ¾udia,
{12458}{12525}ktorí chcú získa informáciu o poklade.
{12567}{12634}No? Teraz je môj príbeh trochu realistickejší, e?
{12910}{12964}Èo je to za nápad, spôsobi to¾kú škodu?!
{12998}{13030}Š-Šéfe!
{13514}{13604}Vy, chlapec a tá sleèna?|Vy ste celá posádka?
{13630}{13736}Obèas máme dvoch ïalších, ktorí sú nieèo ako posádka,
{13751}{13798}ale v podstate sme traja.
{13826}{13857}To sú zlé správy...
{13874}{13937}V poslednej etape cesty bude fyzická sila dôleitá.
{13961}{14000}Hej! Gene Starwind!
{14014}{14089}Zaplatíš za tú škodu v reštaurácii!
{14208}{14249}Presne tá, ktorú som chcel vidie!
{14259}{14325}Ak chcete silu, toto zviera tu má sily za desiatich!
{14350}{14393}Komu vravíš zviera?!
{14482}{14524}Všetky navigaèné údaje v poriadku.
{14535}{14603}Vıkon všetkıch motorov stabilnı. Môeme odštartova.
{14625}{14666}Dedo, kam máme namierené?
{14676}{14732}Heifong VII, Vodná planéta!
{14748}{14789}Fajn, poïme!
{15169}{15238}Vrátil som sa! Znovu som sa vrátil!
{15249}{15319}Èo tım myslíte, "znovu," dedo?
{15327}{15442}Zabudol som vám poveda, ale chodievam sem znovu a znovu.
{15452}{15493}Poslednıch 30 rokov.
{15497}{15533}T-Tridsa rokov?
{15590}{15659}Údaje pre náš poèiatoènı kurz k Vodnej planéte.
{15702}{15733}Okej, okej!
{15918}{15998}Nevravia tomu Vodná planéta pre niè za niè...
{16009}{16064}Je to akoby sme boli skôr vo vode, ne v plyne.
{16081}{16158}Tlak na planéte stlaèil plyn na kvapalinu.
{16168}{16217}Je to ako oceán vodíka.
{16230}{16257}Vypnite motory.
{16268}{16301}Tichı chod!
{16302}{16331}A preèo?
{16338}{16364}Urobte, ako vravím!
{16402}{16466}Mel! Nastav pohonné systémy do vyèkávacieho reimu.
{16472}{16521}Rozumiem. Nastavujem Éterovı pohonnı systém...
{16526}{16601}...a Sub-éterovı pohonnı systém do vyèkávacieho reimu.
{16614}{16665}Skloò nás dole o tri stupne.
{16675}{16700}Okej!
{16917}{16949}Ryba!
{16966}{17019}Na tomto mieste sú ryby?
{17044}{17081}Vyzerajú chutne!
{17274}{17334}Èo--? Èo to práve bolo?
{17366}{17396}Démon.
{17404}{17427}Démon?
{17437}{17505}Démon, ktorı obıva Vodnú planétu.
{17627}{17672}Démon? Èo tım myslíte?
{17741}{17805}U niè iné netajíte, e?
{17806}{17857}Chcem, aby ste nám povedali všetko.
{17858}{17936}Produkcia: BillSK|Spracovanie videa: Randy
{17939}{18001}Nie je urèené pre komerèné pouitie.
{18007}{18080}Slovenské titulky: Pedro (pedro_k@post.sk)
{18176}{18268}Èo chcete vedie? eby o vıbušnine v tejto protéze?
{18272}{18304}V-Vıbušnina?
{18370}{18414}Som zvyknutı na zradu.
{18422}{18503}Je tam toho viac ne dos, aby to roztrhalo túto loï.
{18522}{18594}Myslíte, e naletím na nieèo také?
{18607}{18663}Chcete zisti, èi blafujem?
{18782}{18808}Dobre teda.
{18859}{18987}Pred tridsiatimi rokmi sa pirátska loï napadnutá rodinou Outlaw...
{18989}{19037}...zrútila tu, na Vodnej planéte.
{19047}{19111}Spolu so svojím nakladom, 15 tonami Dragonitu.
{19113}{19163}P-Pätnás ton Dragonitu?
{19170}{19260}To sa rovná rozpoètu pohranièného štátu na pä rokov.
{19272}{19319}Tí Outlaws išli po tom.
{19334}{19416}Hnali sa za pirátskou loïou, keï sa potopila do oceánu plynu.
{19426}{19510}A keï pirátska loï dosiahla dno oceánu kovového vodíku,
{19519}{19592}vtedy sa objavili tie príšery!
{19617}{19728}Tie monštrá sa vzniesli z morského dna a zaútoèili na lode Outlaws.
{19743}{19790}Ich pazúry trhali ich pancierové pláty...
{19792}{19845}a ich tesáky drvili ich trupy!
{19860}{19957}Príšery, ktoré v okamihu zmasakrovali 12 lodí rodiny...
{19968}{20045}...boli svorkou primitívnych ivotnıch foriem, ktoré obıvali Vodnú planétu.
{20063}{20150}Primitívne ivotné formy? Chcete poveda, e tá obluda, èo sme videli--
{20152}{20240}Oblas, kde sa pirátska loï potopila je ich kolóniou.
{20257}{20316}Majú silnı teritoriálny inštiknt.
{20323}{20397}Všetko, èo prenikne do ich teritória je mez milosti napadnuté.
{20406}{20511}Outlaws, piráti, Vesmírne jednotky,|kadı, kto h¾adal ten poklad...
{20513}{20590}...bol roztrhanı ich pazúrmi a poslanı ku dnu.
{20618}{20721}Vodná planéta sa stala obávanou ako planéta, kde ije démon...
{20734}{20809}a ¾udia tu prestali chodi h¾ada poklad.
{20831}{20965}Ale nie vy. Len vy, ktorı ste prvı krát stretli démona pred 30 rokmi...
{20967}{21031}sa ešte aj dnes eniete za pokladom.
{21037}{21075}Èo tım myslíte?
{21085}{21157}To bola vaša rodina, èo napadla tú pirátsku loï.
{21165}{21195}Mám pravdu?
{21276}{21323}Stratil som mnoho vecí.
{21332}{21429}Svoje oko. Ruku. Nohu.|Svoju nenahradite¾nú rodinu...
{21436}{21481}Oni my ich vzali!
{21511}{21600}Ale ja stále idem po nich!|Po príšerách! Po poklade!
{21606}{21645}Celıch tıch tridsa rokov!
{21662}{21689}Kvôli pomste?
{21696}{21750}Nie! Takı je ivot Outlaw!
{21762}{21893}Mám sen, za ktorım idem a nepriate¾a, ktorého chcem zabi, take bojujem!
{21906}{21957}Budem bojova tak dlho, pokia¾ budem Outlaw!
{22011}{22046}Vidím nieèo pred nami.
{22125}{22146}To je ono!
{22152}{22223}Take, 15 ton Dragonitu èaká tam...
{22232}{22277}V-Vypadnime odtia¾to, Gene!
{22294}{22392}Okolitá oblas je prelezená príšerami, ktoré sú schopné rozdrvi loï!
{22408}{22442}Máte plán, pravda?
{22443}{22467}Samozrejme.
{22469}{22502}Gene...!
{22510}{22604}Myslíš, e ujdem, keï je tam 15 ton Dragonitu?
{22620}{22697}Vezmeme si poklad, ktorı tam leal tridsa rokov!
{22702}{22733}L-Lene...
{22741}{22777}Vzchop sa, Jim!
{22779}{22833}Toto je naša ve¾ká šanca ako rıchlo zbohatnú!
{22848}{22880}Kruci!
{22886}{22938}Hej, dedo! Èo urobíme najprv?
{22951}{22983}Pripravíme nejaké návnady.
{22990}{23014}Okej.
{23050}{23087}Nabitie návnad vykonané!
{23094}{23142}Vystre¾ ich smerom k pirátskej lodi!
{23267}{23319}Znie to ako tie ryby predtım...
{23321}{23367}Ty to poèuješ, Aisha?
{23374}{23406}Istee áno!
{23489}{23508}Uhnite sa im!
{23510}{23535}Rozumiem!
{23668}{23719}Motory na maximum!|Pretnite laná!
{23721}{23744}Aye-aye, sir!
{23889}{23920}Fajn, vyšlo to.
{23926}{23974}Hej, je to ¾ahšie ne som si myslel!
{23982}{24085}Nenamıš¾aj si! Zo svojho teritória sa vzdialia len na 10 minút!
{24093}{24186}Vyuijeme ten èas, aby sme sa dostali na pirátsku loï a naloili poklad!
{24378}{24409}Je v nákladnom priestore è. 3!
{24416}{24443}Jasné!
{24645}{24691}Ak sa budete moc namáha, vaše srdce to nevydrí!
{24727}{24788}Nezomriem, kım nebudem ma v rukách ten poklad!
{25070}{25106}Sakra, nejde to otvori!
{25108}{25132}Ustúpte!
{25346}{25409}Dobre teda! Je èas, aby sa dala do práce Aisha!
{25578}{25617}A je to.
{25657}{25684}Èo to má znamena?!
{25810}{25843}Do èerta s tım!
{25914}{25987}T-Toto všetko je Dragonit!
{26139}{26216}Trvalo to tak dlho...|Ten deò koneène nadišiel.
{26259}{26313}Sorry, starı mu, ale na toto nemáme èas.
{26329}{26393}Môte sa veseli, a ten poklad budeme ma.
{26410}{26430}Iste.
{26461}{26494}Podarí sa im to?
{26520}{26585}Môme akurát veri tomu, èo nám ten starı mu povedal.
{26593}{26637}Gene! Máte tri minúty!
{26645}{26693}Rozumiem. Toto je posledné.
{26762}{26793}Jim! Èo je?!
{26802}{26850}Tie príšery! Vracajú sa!
{26852}{26874}Èoe?!
{27032}{27073}Toto ste nám nepovedali!
{27075}{27138}Zdá sa, e som sa prepoèítal.
{27146}{27183}Prepoèítal?!
{27193}{27222}Èo urobíme, Gene?
{27224}{27261}Vydrte, kım sa nevrátime!
{27309}{27344}Môj trup je poškodenı!
{27348}{27439}Èo robíš, Jim?|Bráò sa predsa Grapplerovımi ramenami!
{27453}{27492}Upokoj sa, hej?
{27494}{27565}Nemôem poui ramená, kım sa nevráti Gene a ostatní.
{27643}{27723}Dobre, Jim! Poklad máme naloenı! Vytiahni nás spä!
{27733}{27757}Okej!
{27978}{28042}Zruš vyèkávajúci reim! Dostaò nás stadeto na plnı vıkon!
{28050}{28069}Áno!
{28096}{28138}Vıkon všetkım motorov stabilnı.
{28179}{28199}Èo je?!
{28201}{28248}¼avé rameno je preaené.
{28274}{28298}Èoe?
{28470}{28500}Tu máš!
{28589}{28629}Sakra! Tá vec je silná!
{28818}{28851}Obrovské!
{28853}{28883}To je vodca!
{28894}{29012}To je ten démon spomedzi démonov, ktorı mi vzal oko, ruku i nohu!
{29024}{29067}Krá¾ démonov z Vodnej planéty!
{29088}{29131}Krá¾ démonov z Vodnej planéty...?
{29133}{29173}Mel! Spus motory!
{29206}{29253}Pôjdeme na plnı vıkon a oslobodíme sa!
{29417}{29505}Nejde to! Tá vec je pevne zachytená o pirátsku loï!
{29682}{29718}Ramená to nevydria!
{29809}{29856}Sakra! Ešte trochu a je po nás!
{29889}{29925}Nákladnı priestor sa otvára.
{29938}{29961}Èoe sa?
{30087}{30132}Dedo! Èo to robíte?!
{30158}{30211}Vyrovnávam si to s tım bastardom.
{30218}{30324}Nerobte hlúposti! Èo zmôete v tej mini-ponorke?
{30338}{30433}Vïaka vám sa mi podarilo splni si svoj sen.
{30442}{30555}Mám v rukách sen, h¾adaním ktorého som ako Outlaw strávil celı ivot.
{30565}{30588}Dedo...
{30671}{30706}Teraz zostal akurát on!
{30710}{30811}Je priamo predo mnou, a èes Outlaw mi vraví, aby som ho zabil!
{30813}{30847}Dedo! Nerobte to!
{30865}{30941}Ešte stále je èas!|Nerobte to! Nechajte to tak!
{30952}{30998}Prestaòte! Nerobte to!
{31075}{31148}Choï za svojím vlastnım snom, mladı Outlaw.
{31158}{31226}A potom zaòho bojuj!|Bojuj, aby si chytil svoj sen!
{31235}{31275}Stojte! Nerobte to!
{31575}{31664}Dedo!
{31778}{31861}Hurá! Hurá!|Je to poklad ako hora!
{31928}{32002}No tak? No tak? Akı je môj podiel?
{32022}{32047}Nula!
{32062}{32133}Èo tım myslíš?!|Veï je to samı Dragonit!
{32135}{32179}Snaíš sa ma podvies?!
{32183}{32246}Mono to vyzerá ako ve¾a,|ale je málo kvalitnı.
{32258}{32327}Na èiernom trhu to vychádza len na 1,8 milióna wongov.
{32338}{32422}Tu je úèet za palivo. A náklady na opravu Grapplerovıch ramien.
{32429}{32482}A tu sú náklady na vımenu pancierovıch plátov...
{32498}{32543}A toto je za údrbu lode.
{32551}{32612}A tu sú parkovacie poplatky a nájomné za budovu, ktoré sa nakopilo.
{32618}{32673}Sluby, telefón, inzercia.
{32677}{32725}A keï pridáš tie nepredvídané vıdavky, zostalo nám toto!
{32857}{32892}Je to pravda?
{33010}{33069}Preèo sa to muselo sta mne?!
{33547}{33653}Sora, tooi sora...
{33664}{33783}Tsubuyaita koe...
{33806}{34067}Anata noyume wa ima|hoshi no sharin o mawasu.
{34092}{34350}Watashi, itsumo doko ni mo inai.
{34367}{34480}Sou kanjite ita,
{34485}{34634}sono hitomi shiru made wa.
{34642}{34860}Mune no katasumi kaketa|tsuki ga hitotsu dake.
{34877}{35174}Demo donna ni hosoi michi|mo terasu you ni hikaru.
{35710}{35785}Tajomstvo Outlaw je odhalené!
{35795}{35881}A MacDougall sa pokúša získa|Melfinu do svojich rúk!
{35895}{35995}Veru! Vyzerá to ako vyvrcholenie ve¾kej vesmírnej drámy, e?!
{36004}{36069}Nabudúce budem dokonca pilotova ve¾kého robota!
{36085}{36129}Huh? Alebo nie?
{36146}{36255}Nabudúce v Outlaw Star!|"Medzi ivotom a strojom!"
{36263}{36313}Radšej sa pripravte!
{36308}{36403}"Medzi ivotom a strojom!"