{1}{1}23.976
{77}{173}Aj dnes, keï existujú zbrane,|ktoré dokáu vyhladi celú planétu,
{182}{261}nevyšli z módy bojovníci, ktorí veria iba svalom...
{263}{301}...a ustaviène bojujú o väèšiu silu!
{314}{414}Pre hocijakú bytos, hocijakého veku je prirodzené, e chce by silnou!
{426}{494}Vesmírny turnaj silákov bol prvım turnajom,
{505}{623}ktorı rozhodoval, kto je najsilnejším muom a enou!
{643}{733}Napriek pravidlám chráni ivoty bojujúcich,
{735}{771}boje zúria a do extrému!
{776}{870}A do doby 10. turnaja, nikto nevyhral dvakrát za sebou!
{879}{938}Avšak, objavil sa jeden súaiaci,
{940}{997}ktorı zmenil doterajšiu históriu turnaja!
{1009}{1082}Rıchlos! Vytrvalos!|Technika! Taktika!
{1093}{1142}Tento súaiaci, excelujúci v tomto všetkom,
{1148}{1255}vyhral u totito štyri turnaje za sebou!
{1266}{1372}Hovoria jej Najsilnejšia ena vo vesmíre!
{1502}{1584}Semenaide, kesanaide, makenaide...
{1586}{1705}...dare datte motteru|hazu yuzurenai mono.
{1722}{1797}Ai dake, yume dake, kimi dake...
{1802}{1941}...sore dake wa hanasanai,|donna toki de mo.
{2002}{2098}Dou shiyou mo naku,|ochitsukanai yoru...
{2102}{2211}...nani mo ka mo|nagedashitaku naru.
{2214}{2313}Tsubekobe iwazuni,|sassa to doa o akena.
{2315}{2420}Rikutsu nante,|koneteru hima wa nai.
{2427}{2633}Juu'ou-mujin tobimawaritai,|youi-shuutou mamoritakunai!
{2642}{2821}Nakushita wakeja nai,|mada hajimattenai dakara.
{2838}{2917}Semenaide, kesanaide, makenaide...
{2922}{3039}...daredatte motteru|hazu yuzurenai mono.
{3054}{3134}Ai dake, yume dake, kimi dake...
{3139}{3256}...sore dake wa hanasanai,|donna toki de mo.
{3286}{3389}Nani ga hoshii? Nani ga shitai?|Doko ni ikitai?
{3394}{3546}Yami o saite hashirinukete|tsukamitore through the night!
{3769}{3845}Take, chceš, aby som ti poièal ïalšie peniaze, e?
{3859}{3937}Nemám èas zaobera sa robotami za pár drobákov!
{3949}{4023}Prosím, Fred! Si jedinı, na koho sa môem obráti!
{4122}{4178}Nebuï takı formálny, Gene...!
{4186}{4264}Vari som ti niekedy odmietol láskavos?
{4271}{4293}Take teda--
{4306}{4389}Ale len pod jednou podmienkou.
{4424}{4461}Nemienim sa s tebou vyspa.
{4481}{4533}Chcem, aby si pre mòa vykonal prácu.
{4547}{4570}Prácu?
{4578}{4667}Odteraz za tri dni bude v Heifongskom Koloseu...
{4675}{4752}...prebieha "Galaktickı turnaj silákov".
{4762}{4858}Je to boj bez pravidiel medzi ¾uïmi, ktorí si myslia, e sú najsilnejší,
{4870}{4923}kde víaz získava prestí najsilnejšieho v galaxii,
{4925}{4979}a tie odmenu 100 000 wongov.
{4983}{5055}Nechceš odo mòa, aby som tam vsúpil a vyhral ho, e?
{5057}{5100}By tvoj bojujúci billboard?
{5106}{5209}Kdee, kdee... Problémom je enská divízia turnaja.
{5214}{5249}eny tam bojujú tie?
{5378}{5445}Je celkom pekná!
{5455}{5538}Reiko Ando, vyhrala titul...
{5539}{5590}...Najsilnejšej eny vesmíru štyri roky za sebou.
{5596}{5667}Si robíš srandu!|Takáto koèka?
{5834}{5950}Je mi jedno, èo urobíš, ale zabráò jej vyhra po piaty raz!

{5957}{6050}BillSK & Pedro uvádzajú:|OUTLAW STAR:|"Najsilnejšia ena vo vesmíre!"

{6196}{6252}Avšak, nechápem to.
{6266}{6355}Bude problém, keï tá svalnatá koèka opä zvíazí?
{6365}{6411}Budem sa musie oeni.
{6430}{6461}Èo si povedal?
{6466}{6491}Oeni...
{6493}{6528}Èo? Èo také?
{6534}{6618}Budem sa musie oeni!|Ja s tou enskou!
{6646}{6679}Oeni...?
{6830}{6881}To nie je na smiech, Gene!
{6925}{7005}V èom je problém, Fred?|Do toho, oeò sa!
{7006}{7073}Ja sa ešte nechcem eni!
{7093}{7189}Chcem ešte zai mnoho uasnıch milostnıch dobrodrustiev!
{7195}{7311}No a èo má tvoja svadba spoloèné s tım, kto vyhrá turnaj?
{7326}{7377}Tradícia rodiny Luo vraví, e naše nevesty...
{7378}{7445}...musia by najsilnejšie vo vesmíre.
{7462}{7485}Èo tım myslíš?
{7496}{7588}Po pravde, znamená to, aby nevesta bola silná duševne,
{7597}{7678}ale keï som jej diktoval podmienky, tradíciu som vyuil len ako zámienku.
{7715}{7782}Take si jej povedal, e musí vyhra turnaj, èo?
{7784}{7839}Pä krát za sebou! Pä krát!
{7854}{7902}Bol som si istı, e to nedokáe!
{7914}{7996}Ale ona vyhrala kadı roèník za posledné štyri roky...
{7998}{8058}Take tento rok to bude piaty krát za sebou...
{8060}{8116}a nabudúce u bude zbiera body  u teba!
{8118}{8208}iadam a, aby si tomu zabránil, Gene!
{8220}{8338}Ale keï vyhrám, budem si môc od teba poièa ïalšie peniaze, hej?
{8346}{8390}Zaplatím ti, samozrejme.
{8458}{8482}Èo povieš na toto?
{8558}{8602}Nebuï takı formálny, Fred...!
{8604}{8670}Vari som ti niekedy odmietol slubu?
{8672}{8695}Gene!
{8697}{8749}Fajn, sme dohodnutí!
{8751}{8794}Spolieham na teba, Gene!
{8976}{9108}Rozumieš, Aisha? Musíš akurát porazi tú svalnatú enskú.
{9116}{9234}Len to nechaj na mòa! Nikto v tomto vesmíre nedokáe porazi Aishu!
{9252}{9332}Vesmír je ve¾kı.|Bude to naozaj také ¾ahké?
{9362}{9429}Suzu, ty si ale bojko!
{9431}{9499}Myslím, e som a poprosila, aby si ma tak nevolala.
{9518}{9574}Nechajte len všetko na Aishu!
{9582}{9650}A tie si dopomôem aj k tej peòanej odmene!
{9711}{9760}U sa celá trasiem od nedoèkavosti!
{9797}{9858}Èoe?! Nemôem sa zúèastni?!
{9870}{9973}Pod¾a turnajovıch pravidiel,|Ctarl-Ctarl nemajú povolenú úèas.
{9976}{10002}Preèo nie?
{10013}{10100}Preèo sa Ctarl-Ctarl nemôu zúèastni?!|To je diskriminácia!
{10109}{10216}P-Pred piatimi rokmi sa Ctarl-Ctarl, ktorá súaila na turnaji...
{10222}{10305}...prive¾mi rozrušila, zmenila sa na zviera, èi také èosi,
{10321}{10388}a odhryzla svojej protivníèke ucho!
{10404}{10461}artujete!
{10483}{10575}Bola diskvalifikovaná, ale to ju ešte viac rozzúrilo.
{10586}{10637}Bolo tu 984 obetí,
{10650}{10718}5379 váne zranenıch...
{10726}{10804}...a to¾kí s ¾ahkımi zraneniami, e sme ich ani nespoèítali!
{10806}{10897}Bola to neslıchaná pohroma v celej histórii turnaja!
{10923}{11047}Odvtedy, všetci Ctarl-Ctarl majú zakázané úèastni sa turnaja!
{11059}{11113}T-To nie...!
{11152}{11197}Èo budeme robi, Gene?
{11198}{11235}Èo môme urobi?
{11240}{11285}Ak sa Aisha nemôe zúèastni, tak--
{11298}{11322}Suzuka?
{11341}{11449}Chceš, aby som vzala prácu od Freda Luo?
{11464}{11495}Nie, akurát--
{11511}{11558}To si nemyslím.
{11574}{11616}Take sme vyèerpali monosti...
{11646}{11673}No...
{11700}{11750}Èo keby si išiel ty, Gene?
{11894}{11995}Ja nemôem!|Èo si myslíš?
{11999}{12053}Nie, to nie je celkom pravda...
{12066}{12123}Hlupák, ja som predsa mu!
{12127}{12219}No tak, no tak, Gene. V skutoènosti to je celkom dobrı nápad.
{12234}{12270}Suzuka, u aj ty!
{12289}{12358}Vdy existuje riešenie.
{12418}{12536}13. roèník Vesmírneho turnaja silákov sa práve zaèína!
{12570}{12677}Ale najprv tu je Ikki Kajin,|predseda vıkonného vıboru,
{12679}{12714}s úvodnım príhovorom!
{12747}{12883}Všetkım vám, ktorí ste vstúpili do Vesmírneho turnaja silákov,
{12886}{12929}ïakujem z håbky svojho srdca!
{12934}{13025}A tie tımto 32 enám, ktoré sem prišli bez oh¾adu na svoje ivoty--
{13033}{13147}Aha, Gene! Takto trápne si sa vyobliekal len kvôli mne!
{13154}{13197}Do èerta s nimi...
{13216}{13269}Monoe táto farba je príliš konzervatívna...
{13274}{13320}Nie, ja si myslím, e toto by mu pristalo lepšie.
{13322}{13397}Podplatili sme toho úradníka, tak neblbni.
{13405}{13464}Be tam a zarob pre nás nejaké peniaze, Jenny-chan!
{13487}{13530}Vychutnávali si kadı okamih...
{13574}{13619}Ako dlho chce ešte keca?
{13627}{13674}Je to tak...|Skonèi u!
{13694}{13761}Som takı ospalá, e sa ledva drím...
{13770}{13813}Urıchli to, hej?
{13826}{13867}Ako sa--?|Stal som sa obeou...
{13867}{13886}Stal som sa obeou...
{13888}{13962}...neodôvodneného oèieròovania a ohovárania|tıch, ktorí neveria schopnostiam!
{14093}{14145}Ako si sa sem dostala, ty zviera?
{14154}{14195}Nehovor mi zviera!
{14198}{14222}Èoe?
{14230}{14257}Gene?
{14317}{14354}Èo to máš na sebe?
{14362}{14434}Sklapni! Nie si v situácii, aby si sa mi mohla smia, Aisha!
{14450}{14493}O èom to hovoríš?
{14501}{14596}Ja-Ja som tajomná maskovaná bojovníèka Firecat.
{14606}{14685}Nie... Nie som Aisha Clanclan.
{14710}{14759}My sme a hneï vedeli odhali, Aisha.
{14761}{14815}Ako chceš oklama ich, Aisha?
{14817}{14868}Prestaòte ma furt vola Aisha, Aisha!
{14929}{14969}Ja som naozajstná Fire--
{15049}{15075}T-Ty si...!
{15077}{15193}Aj tak, budem bojova ako|Firecat a zvíazím!
{15202}{15269}Obèas si, pre zmenu, dokáeš aj nieèo premyslie!
{15274}{15308}Èo--? Hej, James!
{15311}{15380}Takmer si vyzeral sklamanı, Gene.
{15382}{15449}Sú to dobré správy, nie?|Teraz môe bojova Aisha.
{15450}{15486}Mel! U aj ty!
{15494}{15588}Zvíazím a prinavrátim èes Ctarl-Ctarl!
{15610}{15648}Hej! Buï tam ticho!
{15673}{15706}Ako chceš...
{15784}{15845}Rozmyslite si to, prosím, Lady Iraga!
{15847}{15918}Ak sa o tom Lord Hazanko dopoèuje, tak...
{15926}{15988}Ticho! Myslíš, e dovolím, aby rozhodovali o tom,
{15990}{16061}kto je najsilnejšia ena vo vesmíre bezo mòa?
{16063}{16106}Ale našou úlohou je--
{16114}{16213}Ja viem. Aj tak, u èoskoro získam oboje.
{16223}{16323}Víazstvo v tomto turnaji aj ivot Genea Starwinda...
{16330}{16402}Prvé kolo prvého zápasu sa práve zaèína!
{16411}{16490}V modrom rohu, reprezentujúca zápasnícky štıl Outlaw,
{16492}{16546}Jenny Starwind!
{16611}{16701}A v èervenom rohu, reprezentujúca|komplexnı bojovı štıl Ando,
{16703}{16783}najsilnejšia ena vo vesmíre po štyri roky za sebou,
{16785}{16867}Reiko Ando!
{16913}{16979}Vyhrám tento turnaj, nech to stojí èoko¾vek...
{17022}{17135}A potom sa vrátim domov s Fredom ako jeho nevesta!
{17185}{17237}Èo to? Akoby ma práve niekto spomenul...
{17318}{17404}Prosím a, Gene...|Vyhraj to za kadú cenu!
{17559}{17594}Je stavaná jak skala.
{17606}{17640}Gene, do toho!
{17642}{17722}Nevolaj ho "Gene"!|Pre dnešok je to Jenny!
{17726}{17755}Oh, to je fakt.
{17917}{17968}Ty! Preèo to robíš inej ene?
{17977}{18060}Vyzerá to tvrdé ako skala, ale je to mäkšie ne sa zdá!
{18087}{18142}Na to teraz nie je èas, Jenny!
{18151}{18185}To je všetko súèasou plánu!
{18200}{18264}Tak u sa zastav!|Nevieš to bra váne?!
{18274}{18301}Kdeeby!
{18308}{18340}Tomuto hovorí plán?
{18346}{18463}Zrejme sa ju snaí rozzúri a porazi ju svojím vlastnım tempom.
{18477}{18536}Ich rozdiel v sile je príliš ve¾kı.
{18561}{18591}Tu som! Tu som!
{18613}{18668}Ge-- Vlastne, Jenny!
{18734}{18779}Èo sa stalo s tım tvojím plánom?
{18790}{18879}Hej, tvoje prsia sú tie celkom mäkké!
{18967}{19040}Produkcia: BillSK|Spracovanie videa: Randy
{19050}{19100}Nie je urèené pre komerèné pouitie.
{19107}{19185}Slovenské titulky: Pedro (pedro_k@post.sk)
{19302}{19344}Myslím, e u sa preberá!
{19367}{19389}Kde som?
{19390}{19418}Na ošetrovni.
{19424}{19446}A èo zápas?
{19448}{19490}Gene, dostal si na frak.
{19494}{19582}Èo to malo znamena, Gene?!|Ako si mohol tak prehra?!
{19595}{19626}Upokoj sa, Fred.
{19628}{19669}Ako môem by teraz pokojnı?!
{19679}{19752}Ešte stále máme eso v rukáve.
{19798}{19864}Ganymedian Seaside Upper!
{19869}{19918}Víazkou je Firecat!
{19927}{19971}To je naša tromfová karta.
{19974}{20074}Je poriadne silná.|To je asi tak jediné, v èom je dobrá.
{20086}{20164}Andromedskı meteorickı kop!
{20177}{20231}Dokázala to! Zvládla u druhé kolo!
{20322}{20358}Je dobrá, fakt.
{20414}{20504}Víazkou prvého zápasu semifinále je Firecat!
{20577}{20612}V pohode!|V pohode!
{20619}{20704}Prosím, Firecat! Si jediná, na koho sa môem spo¾ahnú!
{20716}{20759}Len to nechaj na mòa!
{20766}{20818}Nenafukuj sa a makaj...
{20826}{20949}Ale? Veï to je Jenny, ktorá to zlizla u v prvom zápase...
{20984}{21037}Druhı zápas semifinále sa skonèil!
{21040}{21108}Tá svalnáèka vyhrala, e?
{21110}{21134}Toti...
{21140}{21182}Reiko prehrala.
{21220}{21243}Èoe?
{21254}{21317}Prehrala po 19 sekundách zápasu.
{21323}{21404}Pre Iragu a jej Hokke štıl tieòového boxu to bolo rıchle víazstvo.
{21411}{21441}To nie je moné!
{21542}{21568}Skvelé!
{21582}{21665}Dokázal si to, Gene! Teraz sa u nemusím eni!
{21676}{21707}To rád poèujem, Fred.
{21709}{21788}Ïakujem! Toto je najšastnejší deò môjho ivota!
{21790}{21837}A teraz, oh¾adne platenia...
{21855}{21883}Platenia?
{21891}{21941}"Peniaze za vykonanú prácu"|vdy znamenali...
{21942}{22009}...peniaze zaplatené niekomu, kto úspešne dokonèil svoj dob.
{22013}{22072}A èo si vykonal ty, Gene?
{22081}{22154}Nu, poèkám, a budeme nabudúce robi biznis!
{22164}{22202}Maj sa, Gene!
{22346}{22372}Fred!
{22374}{22430}Prepáè, Reiko.
{22442}{22473}Fred...
{22525}{22562}Poèkaj ešte chví¾ku!
{22569}{22674}Budem trénova a od budúceho roku sa pokúsim zase vyhra 5-krát za sebou!
{22680}{22786}I-Iste. Ale myslím, e zatia¾ by si si mala odpoèinú.
{22790}{22838}Máš pred sebou dlhı boj.
{22840}{22942}Máš o Reiko obavy!|Som taká šastná!
{22956}{23059}Reiko... Reiko sa stane tvojou enou!
{23102}{23161}Finále sa práve zaèína!
{23169}{23256}V èervenom rohu, reprezentujúca profesionálny wrestling,
{23262}{23326}Firecat!
{23343}{23378}Yeah!
{23386}{23479}V modrom rohu, reprezentujúca|tieòovı box Hokke,
{23486}{23549}Iraga!
{23602}{23662}Gene Starwind?|Èo ten tu robí?!
{23693}{23753}Musím zosta pokojná...|Najprv zápas.
{23777}{23881}Kvôli cti Ctarl-Ctarl musím vyhra!
{24175}{24226}Èo sa deje? Nehıbu sa!
{24233}{24280}Hovorí sa, e dvaja skúsení bojovníci dokáu posúdi...
{24282}{24354}...silu svojho protivníka, u keï sa na seba pozrú.
{24622}{24646}Ty...!
{24723}{24753}Fajn, teraz to schytala!
{24756}{24785}Doraz ju, Aisha!
{24798}{24841}Jasné!
{25142}{25175}Hej! Pozbieraj sa!
{25177}{25223}Myslel som, e Ctarl-Ctarl sú nezranite¾ní!
{25258}{25305}Normálne by som a teraz nechala tak,
{25310}{25389}ale zdá sa, e si priate¾kou|Genea Starwinda.
{25396}{25429}Neodídeš odtia¾to ivá!
{25438}{25469}To nie! Ona ju chce zabi!
{25473}{25554}Ani Ctarl-Ctarl nepreijú,|ak prídu o hlavu!
{25562}{25589}Skap!
{25592}{25612}Nie!
{25794}{25839}Moc ti to kecá.
{25842}{25907}Keï chceš s niekım skoncova, nesmieš rozpráva.
{25918}{25970}Ale, ale, na chví¾ku ma vy¾akala...
{25974}{26024}Do toho, Firecat!
{26032}{26076}Len to nechajte na mòa!
{26190}{26226}Tu máš!
{26267}{26290}Ako èo toto?!
{26315}{26358}Je koniec!
{26384}{26412}Je koniec.
{26415}{26503}Nech je akoko¾vek silná, nemôe sa oslobodi--
{26559}{26598}To je nemoné!
{26712}{26824}Ako to!? Hocièo iné by som pochopil,|ale ona je silnejšia ako Aisha?!
{27076}{27096}To je--
{27098}{27141}Ona je tie Ctarl-Ctarl?
{27167}{27193}Ty si--
{27197}{27291}Nezdá sa, e sa mi teraz hneï podarí dokonèi náš zápas ...
{27302}{27356}Take najprv dokonèím svoju prácu!
{27400}{27490}Gene Starwind!|Si màtvy mu!
{27501}{27529}To je Ctarl-Ctarl!
{27531}{27577}Poïme odtia¾to!|Zoerie nás!
{27800}{27827}Piráti?
{27840}{27861}Sakra!
{28030}{28053}Gene!
{28253}{28333}Je mi fakt jedno, èi si pirát alebo vlk,
{28344}{28451}ale nikto mi nebude bráni v mojom víazstve!
{29011}{29033}Èoe--?
{29045}{29069}Suzuka!
{29087}{29110}Aisha!
{29154}{29172}Suzuka!
{29174}{29193}Suzuka!
{29203}{29232}Som v poriadku.
{29238}{29265}To je dobre.
{29282}{29306}A èo Aisha?
{29327}{29374}Aisha! Kde si, Aisha?!
{29375}{29400}Gene.
{29416}{29502}Vypadnime odtia¾to. Inak sa udusíme v tomto dyme.
{29509}{29525}Lene--
{29527}{29560}Upokoj sa, Gene.
{29569}{29645}Teraz by sme sa k Aishi aj tak nedostali.
{29938}{29967}A èo Aisha?
{30135}{30168}To nie...!
{30199}{30225}To je...?
{30412}{30468}To je Aisha! Aisha vyhrala!
{30471}{30494}Vıborne...
{30500}{30565}Dokázala to! Dokázala to!|Aisha je úasná!
{30566}{30623}Ctarl-Ctarl sú naozaj nezranite¾ní...
{30641}{30744}Zrejme by som si z nej mal na chví¾u presta uahova.
{31130}{31218}Ako to, e sa tam dostala ïalšia|Ctarl-Ctarl...
{31222}{31329}Mıliš sa! Medzi Ctarl-Ctarl nie sú iadni takí druhotriedni vlci!
{31334}{31385}Poèul som, e piráti Kei|majú zabijáèku,
{31386}{31462}ktorá sa mení na vlkodlaka, keï zabíja.
{31494}{31522}Piráti?
{31530}{31602}Spä do reality,|èo teraz, Gene?
{31604}{31658}Nedostali sme zaplatené, a minuli sme všetko, èo sme mali.
{31660}{31695}Bolí ma hlava...
{31714}{31762}Haló, Starwind & Hawking--
{31770}{31799}Ah, to si ty, Fred.
{31811}{31879}Ale, zdá sa, e keï som odišiel, mali ste problémy.
{31894}{31957}Pozri, Fred, nemám zrovna náladu sa s tebou rozpráva.
{31959}{31988}Hej, vydr!
{32000}{32058}Vlastne, spomenul som si na svoj ïalší s¾ub.
{32062}{32093}Ïalší s¾ub?
{32104}{32205}S¾úbil som predsa, e ti poièiam peniaze, ak vezmeš tú prácu?
{32213}{32236}Fred...
{32246}{32299}U som vyplnil príkaz na prevod.
{32301}{32358}Mal by si to dosta zajtra.
{32373}{32418}Take, bon voyage!
{32433}{32456}Fred...
{32458}{32487}Èo je?
{32489}{32514}Jim!
{32552}{32581}Ideme na vılet.
{32682}{32764}Všetky systémy v poriadku. Povolenie na štart, prijaté.
{32773}{32844}A odlietame za|Galaktickım Leyline!
{32847}{32882}Fajn, poïme!
{32894}{32954}Outlaw Star, štart!
{33258}{33365}Sora, tooi sora...
{33376}{33494}Tsubuyaita koe...
{33518}{33779}Anata noyume wa ima|hoshi no sharin o mawasu.
{33806}{34039}Watashi, itsumo doko ni mo inai.
{34081}{34191}Sou kanjite ita,
{34198}{34345}sono hitomi shiru made wa.
{34354}{34585}Mune no katasumi kaketa|tsuki ga hitotsu dake.
{34590}{34885}Demo donna ni hosoi michi|mo terasu you ni hikaru.
{35430}{35492}Boli sme uväznení pohraniènou bezpeènostnou slubou!
{35502}{35561}Nemyslíte, e je od nich hodne nezdvorilé,
{35562}{35623}e nazvali poctivého Outlaw ako ja, pirátom?
{35634}{35705}Je naozaj aké ob¾úbi si niekoho, kto je takı tvrdohlavı, e?
{35712}{35765}Musíš sa viac uvo¾ni! Uvo¾ni!
{35804}{35863}Oops! Na chví¾u som zadriemal.
{35878}{35976}Nabudúce v Outlaw Star!|"Právo a bezprávie!"
{35980}{36020}Radšej sa pripravte!
{36021}{36117}Právo a bezprávie