{1}{1}23.976
{86}{160}Okrem národnıch Vesmírnych jednotiek,
{162}{225}existujú tie Súkromné bezpeènostné jednotky.
{262}{328}Ako sa ¾udské teritórium rıchlo rozširovalo,
{334}{413}a boli zakladané rôzne medzihviezdné štáty,
{426}{515}boli zaloené aj Vesmírne jednotky,|aby poskytovali rovnakú ochranu pre všetkıch.
{544}{728}Avšak v šírom vesmíre, nie všetky kolónie|dôverovali tejto ochrane.
{753}{872}To bol zaèiatok Súkromnıch bezpeènostnıch síl|prevádzkovanıch súkromnımi spoloènosami.
{876}{941}Bezpeènostné sily pozostávajú|z bezpeènostnıch agentúr...
{947}{1005}...a najlepších prepravnıch firiem.
{1022}{1120}Chránia vyvíjajúce sa planéty|a medziplanetárne obchodné spoloènoti...
{1128}{1205}...pred pirátmi a inımi druhmi problémov.
{1228}{1322}Lene enormné zmluvné a prevádzkové náklady...
{1328}{1447}...sa pri nízkych ziskoch v pohranièí|stávajú zdrojom problémov.
{1594}{1674}Neobviòuj to, neniè to, nepodceòuj to...
{1674}{1796}...to nieèo jedineèné, èo kadı má.
{1814}{1837}Moja láska...
{1838}{1862}Moje sny...
{1864}{1888}A tie ty.
{1890}{2033}Nevzdám sa toho, za iadnu cenu.
{2094}{2189}V tie noci, keï si nepokojnı,|nech robíš èoko¾vek,
{2192}{2302}máš chu to všetko odhodi preè.
{2306}{2403}Nevrav u niè, len otvor dvere.
{2405}{2513}Nemám èas sa tu s tebou bavi.
{2518}{2627}Chcem sa tadeto vo¾ne preletie,
{2634}{2727}a nedba pritom na opatrnos!
{2734}{2825}O niè som neprišiel,
{2827}{2921}veï som ešte ani nezaèal.
{2929}{3010}Neobviòuj to, neniè to, nepodceòuj to,
{3013}{3131}to nieèo jedineèné, èo kadı má.
{3148}{3176}Moja láska...
{3178}{3205}Moje sny...
{3206}{3226}A tie ty.
{3230}{3349}Nevzdám sa toho, za iadnu cenu.
{3378}{3404}Èo by si chcel?
{3404}{3430}Èo budeš robi?
{3430}{3481}Kam pôjdeš?
{3485}{3640}Schmatni, èo chceš, pretni temnotu,|keï budeš uteka nocou!
{3818}{3898}Pirátska loï sa nehıbe.|Vyhrali sme.
{3911}{3999}Aká škoda munície!|A zrovna sme odštartovali...!
{4018}{4093}Tento nevyzerá na Kei|ani na Ban piráta...
{4098}{4186}Zrejme sú súèasou skupiny, ktorá|vyuíva túto oblas ako základòu pre operácie.
{4207}{4237}Netráp sa tım.
{4277}{4310}Kotvy 1 a 2 uchytené.
{4316}{4374}Prinútim ich zaplati za muníciu,|ktorú sme minuli.
{4382}{4466}A ešte aj nejaké jedlo za spôsobené problémy.
{4513}{4549}Kto je tu vlastne pirátom?
{4562}{4612}My sme tí dobrí.
{4614}{4671}Náš príjem je trochu nestabilnı,|to je všetko.
{4674}{4701}Poèkaj, Gene.
{4712}{4781}Smerom zozadu spoza satelitu sa blíia tri lode.
{4807}{4835}Mali priate¾ov?
{4843}{4892}Nevyzerá to tak. Zväèším to teraz.
{4912}{4955}Vy dve lode! Stojte!
{4957}{4977}Èoe?
{4978}{5081}Toto je hliadková loï String 4,|momentálne stráiaca systém Heifong.
{5083}{5141}Odzbrojte sa a vzdajte sa!
{5153}{5216}Vo-Vojnová loï!|Patrí bezpeènostnım jednotkám!
{5220}{6300}BillSK & Pedro uvádzajú:|OUTLAW STAR:|"Právo a bezprávie!"
{5603}{5690}Miestnos pre nakladanie strojov|bude uzavretá od 12:00 do 14:00.
{5699}{5787}Modrı team, riaï sa inštrukciami|Sekcie Alfa. Zmena rozvrhu.
{5804}{5899}Bezpeènostná sekcia, pozor. V doku 4|bude uzamknutá èervená pirátska loï.
{5922}{5962}Èervená pirátska loï?
{5992}{6053}Títo verejní èinitelia si a fakt|vedia zaradi...
{6063}{6089}Uzamykám.
{6149}{6165}Blbci!
{6167}{6193}Pozor, Outlaw Star!
{6229}{6327}Vaša posádka sa odzbrojí|a prejde na urèenú palubu!
{6362}{6392}V pohode, Gilliam?
{6394}{6449}Budem tu èaka.
{6520}{6599}Ak by ti to nevadilo, radšej by som sa|nechal ohmatáva tamtou koèkou...
{6606}{6641}Èomu sa vyškieraš?!
{6653}{6694}Nech myslíš na èoko¾vek,|zabudni na to!
{6696}{6742}Nie sme iadni chudáci na tejto stanici.
{6756}{6783}Fajn! Ïalší!
{6814}{6841}To sú ale veci...
{6894}{6929}Gene, je to divné.
{6938}{6953}Èo také?
{6955}{7054}Prezerala som údaje, ktoré sme|pred chví¾ou získali z AI tej pirátskej lode.
{7062}{7125}Sú neúplné, ale ich rozvrh operaèného èasu...
{7126}{7195}...sa vzahuje na túto stanicu.
{7208}{7237}Na túto stanicu?
{7251}{7282}Èo to znamená?
{7284}{7343}Urèite nieèo plánujú.
{7363}{7398}Osobná prehliadka skonèená!
{7417}{7489}Tadeto, vy pirátska zberba! A hoïte sebou!
{7494}{7529}My nie sme piráti!
{7540}{7577}To vravia všetci.
{7580}{7637}Preklati vojaci...
{7671}{7728}Mui a eny sú draní oddelene?
{7731}{7775}Keby nám aspoò dali èaj alebo tak...
{7779}{7905}Gene Starwind, na civilistu|máte dos pôsobivú loï.
{7927}{8033}Môj otec bol medziplanetárny obchodník.|Je to jedna z jeho lodí.
{8046}{8115}Je registrovaná na Modrom Nebi.|Všetko je legálne!
{8121}{8177}Obchodník s grapplerovou loïou?
{8178}{8234}Èo keby sme prestali s blbosami?
{8240}{8328}Èo? Prevádzkujem legálny biznis!
{8333}{8393}Ty si ten z tej hliadkovej lode, e?!
{8395}{8430}Skús mi to poveda do oèí!
{8432}{8491}Dobre teda, dúfam, e a neprekvapím.
{8636}{8684}Èo je to za jaštericu?
{8690}{8727}Volám sa Duuz.
{8734}{8825}Som taktickı dôstojník jednotiek|bezpeènostnej sluby Angel Links.
{8835}{8889}On je Saurian!|Nijakého som ešte nevidel!
{8894}{8942}Boli vytvorení pomocou|genetického ininierstva!
{8944}{9018}Genetika? Chceš poveda,|e pochádza z obdobia Jury?
{9054}{9100}Ja som jeho kolegyòa, Valeria.
{9111}{9207}V skutoènosti sme èlenovia jednotiek|bezpeènostnej sluby zo systému Oracion,
{9216}{9313}ale v rámci svojej sluby|sme boli umiestnení sem...
{9326}{9400}...a prichytili sme vás pri boji a zajali vás.
{9410}{9477}Je fajn, keï sa eny do mòa|zamilujú na prvı poh¾ad,
{9479}{9509}ale toto s nami nemá niè do èinenie.
{9522}{9603}Videli ste tam ten vrak, e?|To oni sú piráti!
{9624}{9694}My sme tí dobrí, ktorí ich dostali.
{9700}{9726}Tak, tak...
{9753}{9778}Gene...
{9794}{9873}Vidím, e si mladı Outlaw,|ktorı sa preslávil na Heifongu.
{9890}{9953}Tie som videla video z tıch|vesmírnych závodov.
{9958}{9989}To rád poèujem.
{9992}{10059}Hej, hej. Nezaèínaj s tım.
{10069}{10150}Tak, èo robí takı mu v|tıchto konèinách vesmíru?
{10154}{10226}Prekvapilo by a, keby som povedal,|e h¾adám poklad?
{10234}{10346}Len, èo sa objaví nieèo cenné,|u sa tento sektor hemí pirátmi.
{10360}{10416}eby sa jednalo o pirátsky poklad?
{10418}{10519}To dúfam. Som a po uši v dlhoch.
{10577}{10665}Tvoja Grapplerová loï má vybavenie,|ktoré sa vyrovná pirátskej lodi.
{10679}{10738}A tie divné vıhovorky to robia|ešte podozrivejším.
{10754}{10851}Aj keï tu tvrdí, e je Outlaw,|je to len drzı cicavec.
{10856}{10913}Pravdepodobne nieèo pašoval.
{10917}{10945}Silné reèi.
{10947}{11009}Nikdy som o vás z bezpeènosti|nepoèul niè dobré.
{11016}{11089}Bra peniaze za ochranu nie je|o niè lepšie ako pirátstvo!
{11147}{11162}Gene!
{11164}{11177}Duuz!
{11199}{11227}Èo to malo by?!
{11230}{11341}Neplaè kvôli tomu pot¾apkaniu.|Nedovolím nikomu, aby nás ohováral!
{11355}{11437}Ani ja sa nenechám od teba uráa!
{11442}{11497}To staèí, Duuz!|A ty tie!
{11502}{11534}Upokoj sa, Gene!
{11545}{11651}¼udia, ktorí si hovoria Outlaws|sa od kriminálnikov nijak nelíšia!
{11655}{11681}Duuz!
{11726}{11764}Preverte si nás ako chcete.
{11777}{11867}Ale myslím, e by ste sa mali|strachova o tıch pirátov, ktorıch ste chytili.
{11891}{11918}Èo tım myslíš?
{11926}{12001}Vravím, e sem prišli,|lebo to tu chcú napadnú.
{12013}{12047}S jedinou loïou?
{12050}{12102}Hoci je to doèasné, ale stále|je to námornı prístav.
{12111}{12149}Preèo to vravíš?
{12153}{12267}Poèas letu našiel náš navigátor|v ich AI isté súbory.
{12270}{12361}Pirátske súbory?|Tie boli všetky zmazané.
{12365}{12462}A aj keby to bola pravda,|nepomôe vám to k prepusteniu!
{12472}{12518}Aké š¾achetné od teba!
{12524}{12580}Si dokonalı model ochrancu zákona!
{12594}{12640}Som na to hrdı.
{12646}{12743}Duuz, len tak pre kadı prípad,|pôjdeš vypoèu tıch pirátov?
{12771}{12794}Dobre teda.
{12796}{12885}Odzbrojte loï tıchto ¾udí!|Chcem ju ma preh¾adanú skrz naskrz!
{12886}{12909}Áno!
{12956}{13013}Poèul som, e Sauriani sú tvrdohlaví.
{13014}{13045}Vôbec nie!
{13062}{13149}Môj ¾ud má hrdos bojovníkov,|to je všetko.
{13153}{13217}Zloèinci to zrejme nepochopia.
{13277}{13321}To ale trvá...
{13412}{13437}Vlez tam!
{13453}{13493}Gene! Tvoja tvár...?
{13502}{13533}Tım sa netráp.
{13547}{13621}Tak, èo bude teraz, sleèna dôstojníèka?
{13633}{13698}Prepáète, ale na nejakı èas vás zadríme.
{13702}{13753}Núdzová situácia.|Neberte to osobne.
{13762}{13783}Istee.
{13785}{13827}Chcem, aby ste sa všetci pozreli na toto.
{13841}{13864}Na èo?
{13912}{14018}Krá¾ovná letnej noci.|Civilná loï, ktorá onedlho pristane.
{14154}{14202}Pirátsky prepad?
{14204}{14295}Hej. Kım sme od nej dostali SOS,|bolo u neskoro.
{14302}{14340}Zabili niekoho?
{14347}{14437}Preilo ich 128,|10% z jej pasaierov.
{14452}{14477}Gene...
{14495}{14569}Kto to urobil...?|Taká spúš...
{14607}{14690}Pripomína ti to príhodu s|tvojím otcom spred piatich rokov?
{14763}{14832}Máš v záznamoch aj staré èlánky z novín?
{14846}{14916}Našou prácou je strái hranicu.
{14922}{15019}Dríme si záznamy aj o najmenších|pašeráckych prípadoch.
{15037}{15081}Memôem strpie pirátov.
{15106}{15132}Veï ani my.
{15222}{15313}Vyzerajú by z rovnakej skupiny ako piráti,|s ktorımi sme bojovali predtım.
{15315}{15345}Dobrı postreh.
{15347}{15377}V istıch veciach.
{15384}{15449}Na hranici sa stanete citlivım na nebezpeèenstvo.
{15463}{15515}Títo piráti sú tu povestní,
{15520}{15574}a obèas sa dokonca pokúšali|postavi aj proti nám.
{15594}{15649}Dívajú sa na nás zvrchu, pretoe sme|"len" Súkromná bezpeènostná sluba.
{15651}{15715}Tak potom by ste sa mali aspoò|pozrie na tie súbory.
{15725}{15774}Je to len záznam o operaènom èasovom pláne,
{15776}{15833}ale údaje sú stale na našej lodi.
{15858}{15899}Popremıš¾am o tom.
{15901}{15976}Beriem pritom do úvahy,|e ste nebezpeèné elementy.
{16018}{16100}Si poriadne obozretná.|Presne ako ten jašter.
{16145}{16198}Krá¾ovná letnej noci práve pristáva.
{16207}{16259}Všetky sekcie, riadte sa inštrukciami.
{16301}{16334}Take, uvidíme sa neskôr.
{16355}{16430}Prístavná èata,|pripravte doèasné kotvisko è. 5!
{16440}{16498}Trup plavidla je poškodenı.
{16522}{16573}Dávajte pozor pri pripájaní káblov.
{16586}{16644}Záchrannı tím Titan,|pripravte sa na vysadenie.
{16648}{16736}Dostaòte z lode všetkıch civilistov,|ranení nech majú prednos.
{16752}{16825}Valeria, oh¾adne tıch ¾udí z tej|èervenej pirátskej lode...
{16830}{16915}Sú to malé ryby, e?|Za tıch toho moc nedostaneme.
{16930}{17000}Súkromnım bezpeènostım jednotkám|ide o viac, ne o peniaze.
{17004}{17062}Istee. Potrebujem sem tvoj podpis.
{17100}{17128}Prijímam správu.
{17142}{17204}Môeš to prida k budúcemu|nákladu smerujúcemu na Oracion?
{17206}{17227}Vykonám!
{17231}{17265}A èo tá druhá loï?
{17271}{17313}Duuz má s nimi práve rozhovor.
{17318}{17365}To je v poriadku, èoskoro prehovoria.
{17378}{17413}Aj tak, toto je dôleitejšie.
{17415}{17463}Cesta je vo¾ná!|Pustite ju dnu!
{17485}{17529}Poponáh¾ajte sa s tou druhou kontrolou.
{17557}{17584}Èo je?
{17595}{17648}Natlakujte doèasnı prístav 5, prosím.
{17663}{17756}Lodná lávka pripevnená.|Dostaòte von tıch civilistov!
{17846}{17908}Zachovajte pokoj, prosím!|Pustite najprv zranenıch!
{17939}{17967}Sem nesmiete!
{17969}{18010}Toto je vojenské zariadenie!
{18026}{18065}Hej, som hladnı!
{18077}{18124}Dajte mi sendviè so slaninou a vajcom!
{18128}{18172}Ja si dám jumbo biftek!
{18178}{18214}Mäsové gule!
{18225}{18278}Úhora. A vıvar z peèienky.
{18334}{18385}Dám si tie polievku s vajcom.
{18442}{18493}Kruci! Prekliata jašterica...
{18506}{18547}Nezahrávaj si s ¾udskım alúdkom!
{18587}{18665}Je zbytoèné ís proti autoritám...
{18670}{18705}To teda nie!
{18708}{18781}Len sleduj! Ja z nich nieèo dostanem.
{18873}{18910}Èo to--? Èo sa stalo?
{18914}{18994}Produkcia: BillSK|Spracovanie videa: Randy
{18996}{19055}Nie je urèené pre komerèné pouitie.
{19059}{19137}Slovenské titulky: Pedro (pedro_k@post.sk)
{19354}{19388}Z civilnej lode prilietajú strely!
{19398}{19466}V centrálnom doku je viacero explózií!|Lode sú èiastoène poškodené!
{19476}{19505}Pirátska pasca?!
{19514}{19590}Riadiaca miestnos!|Tí civilisti sú ozbrojení!
{19628}{19656}Ako to!
{19671}{19727}Piráti sa infiltrovali na stanicu!
{19731}{19788}Všetci, okamite ich zlikvidujte!
{19802}{19833}Hoci sa jedná o námornú stanicu,
{19835}{19896}ale keï sú napadnutí znútra,|sú bezmocní.
{19898}{19937}Fakticky si to premysleli...
{19940}{19956}Stojte!
{19974}{20023}Vedeli sme, e s nimi spolupracujete!
{20027}{20085}Pokojne. My nie sme piráti.
{20092}{20112}My sme--
{20138}{20171}Hej, nie je zlé!
{20194}{20217}Ponáh¾ajme sa.
{20262}{20305}Ak to pôjde ïalej, budeme v pasci!
{20313}{20344}Nepriate¾, vzdialenos 4!
{20346}{20366}Èoe?
{20368}{20438}Blíi sa jeden carrier a tri grapplerové lode!
{20633}{20699}Delové vee 7, 9 a 11 neodpovedajú!
{20706}{20748}Všetkı brány v dokoch sú nefunkèné!
{20762}{20800}Tu je String 4!|Kde je Duuz?
{20829}{20861}Stratili ste spojenie?
{20868}{20906}Dobre. Idem ja.
{20977}{21004}U zase...
{21068}{21118}Tlak je na druhej strane v poriadku!|Gravitácia tie!
{21131}{21144}Aisha!
{21146}{21175}Len to nechaj na mòa.
{21287}{21322}Je to zlé...
{21410}{21434}To je--
{21601}{21641}To je ten dinosaurus z|Bezpeènostnıch jednotiek!
{21642}{21661}Ten...
{21663}{21691}Úboiak...
{21772}{21832}Ja... ešte nie som màtvy!
{21834}{21880}Èoe! Je naive!
{21900}{21970}Prekliati zloèinní cicavci...|Pokúšate sa utiec, e?
{21977}{22050}Dovo¾, aby som ti opä pripomenul,|e sme civilisti.
{22063}{22132}V prípade nebezpeèenstva máme by|evakuovaní ako prví.
{22137}{22190}Èo ste urobili so svojimi stráami,|vy grázli?
{22234}{22255}Hm?
{22287}{22349}To je ale kanón...
{22379}{22463}Kto by pomyslel, e ma zabije|obyèajnı cicavec...
{22470}{22531}Hrdos 65 miliónov rokov mi to nedovolí!
{22543}{22566}No toto...
{22574}{22662}Na to, aby som sa ti odplatil,|by nestaèilo ani tıch 65 miliónov rokov...
{22874}{22896}Aisha! Pomô mi!
{22911}{22960}Ty? Èo to zamıš¾aš?
{23031}{23059}Aké š¾achetné od teba.
{23062}{23106}Tie si myslím.|Poïme!
{23159}{23190}Vypadni odtia¾!
{23439}{23470}Preèo si ma zachránil?
{23498}{23534}Lebo mám hrdos.
{23537}{23614}Hrdos? Zloèinec ako ty a hrdos?
{23631}{23712}Jedna ena mi raz povedala,|e vo vesmíre sú tri sily.
{23722}{23756}Tri sily?
{23769}{23804}Piráti a armáda.
{23807}{23838}A tá tretia je--
{23883}{23901}Vráte sa spä!
{23903}{23957}Tak zatia¾, ty tvrdohlavá jašterica!
{24035}{24076}Len dovtedy, kım nebudeme|môc poui svoje strely!
{24082}{24134}Ak sa rıchlo nezbavíme tej|civilnej lode, bude po nás!
{24140}{24223}Beznádejné! Najprv si musíme|odstráni z cesty trosky!
{24237}{24284}Vojaci by mali by predsa|dobrí v improvizovaní!
{24291}{24316}Valeria!
{24325}{24352}Duuz! Si v poriadku?
{24354}{24397}Prepáè, nedával som pozor.
{24404}{24486}Dokáeš sa sem dosta?|Terorizmus je tvoja špecializácia.
{24493}{24517}Rozumiem.
{24526}{24594}Ten ryšavı Outlaw šiel|tvojím smerom! Dávaj si pozor!
{24602}{24629}Gene...?
{24645}{24674}Kto si ty?
{24682}{24701}Stojte!
{24753}{24799}Toto nie je dobrá zbraò.
{24808}{24865}Suzuka, loï je tımto smerom.
{24887}{24926}U ste naspä?
{24928}{24962}Gilliam! V akom si stave?
{24963}{25054}Povedali, e mám by odzbrojenı,|take bola odstránená všetká ostrá munícia.
{25062}{25125}Jediná pouite¾ná stre¾ná zbraò je blaster.
{25131}{25192}Aké milé od nich. Môeš sa hıba?
{25201}{25281}Moje pohonné systémy sú nedotknuté,|ale keï mám na sebe ten oce¾ovı rám...
{25283}{25356}Máš predsa ramená, nie?|Poïme na to!
{25420}{25469}Tá èervená pirátska loï odštartovala?
{25478}{25533}Gene Starwind, èo máš v úmysle?
{25535}{25565}Èo myslíš?
{25567}{25623}Padáme preè, samozrejme!
{25632}{25690}Zdúchneme, kım sa zaoberáte tou stre¾bou!
{25694}{25740}To ja nemôem.
{25743}{25783}Èo? Èo chceš teda robi?
{26000}{26042}Pracovné teamy! Neseïte tam len tak!
{26048}{26085}Odstráòte tú prekáku z cesty!
{26094}{26183}Gene, ty... Ty nám pomáhaš?
{26191}{26267}Nemám odvahu by h¾adanım muom.
{26275}{26368}Myslím, e by som moohol by uitoènejší,|ne tamtie pracovné èaty.
{26381}{26411}Rozumiem.
{26416}{26515}Dobre, Gene. Dokáeš nám získa dos èasu,|aby sme sa odtia¾to dostali?
{26522}{26565}To je nieèo úplne iné.
{26569}{26633}Ponúkaš tomuto Outlaw prácu, dôstojníèka?
{26666}{26751}Tak teda prácu. Od Outlaw|toho oèakávam ve¾a.
{26794}{26836}Daj nám svoje údaje o nepriate¾ovi!
{26914}{26980}Poïakujem sa ti neskôr, Gene.
{26986}{27080}Valeria! Dovolíš tomu ryšavcovi,|aby si robil, èo chce?!
{27094}{27155}Pripravte sa na štart!|Nemárnite èas!
{27192}{27244}Poškriabal som náter!
{27253}{27292}Blíia sa grapplerové lode!
{27344}{27373}So mnou si nezahrávajte!
{27400}{27461}Inerciálne ovládaèe naplno!|Ideme na to!
{27577}{27620}Útoèné kotvy na prevzatie riadenia.
{27625}{27648}Fajn!
{27705}{27745}Štvorka, ved¾a. Dvojka, ved¾a.
{27771}{27800}Nie sú lacné!
{27826}{27854}Trojka, zachytená.
{27856}{27880}Mám ho!
{27886}{27924}Preberám kontrolu nad|nepriate¾skım poèítaèom.
{27978}{27999}Tu máš!
{28044}{28078}Blíi sa viacero striel!
{28082}{28113}Z obidvoch strán súèasne?
{28117}{28135}Vyhni sa im!
{28138}{28173}Nejde to!|Nedokáem sa vyhnú všetkım!
{28177}{28209}20% z nich zasiahne!
{28214}{28240}Vymysli nieèo!
{28243}{28273}Uvidím, èo sa dá robi!
{28282}{28304}Èo?
{28346}{28370}Èoe--?
{28502}{28537}Èo sa deje?
{28563}{28628}Dia¾kovo som ovládal ich poèítaè,|to je všetko.
{28636}{28661}Oh, rozumiem...
{28663}{28691}To je ono, Jim!
{28695}{28736}Bez pomoci Mel by som to nedokázal.
{28741}{28774}Blíia sa dve nepriate¾ské lode!
{28954}{28989}Ešte dve kotvy zostali?
{28994}{29025}Vypúšam 5, 6.
{29075}{29098}Ideme na to!
{29161}{29187}Tu máš!
{29258}{29295}Sila je zhruba rovnaká, e?
{29308}{29338}Prichádza tá druhá loï!
{29408}{29440}Máme problém, Gene!
{29446}{29532}Dávajte pozor! Pokúša sa na mòa|napoji poèítaè nepriate¾skej lode.
{29678}{29705}Èoe--?
{29774}{29812}Zdá sa, e sme to stihli vèas.
{29814}{29841}Jašterica!
{29847}{29920}Gene, nechaj nás postara sa o carrier.
{29923}{30010}Chlapèe, kecal si èosi o nejakıch|troch silách vo vesmíre.
{30021}{30111}Dobre teda. Ukáem ti,|èo je to vojenská sila.
{30185}{30225}Všetky lode, spustite pa¾bu!
{30521}{30560}Tak to je riadna sila...
{30580}{30646}Èo sa stalo, chlapèe?|Stále potrebuješ pomoc?
{30658}{30683}Nie, netreba!
{30801}{30842}Skap, bastard!
{31228}{31284}Vrátili sme muníciu, ktorú sme zabavili,
{31290}{31335}take zostáva akurát vıplata|za vašu prácu, e?
{31342}{31373}Príjmete, dúfam, Dragonit?
{31374}{31429}To je úplne v poriadku!
{31441}{31461}Ale...
{31465}{31503}Je tu ešte nieèo?
{31511}{31576}Nepoèuli ste nieèo o tom,|e by armáda v centrálnych systémoch...
{31578}{31664}...vyvinula grapplerovú loï|zvanú "XGP" alebo nieèo také?
{31764}{31799}Nechaj to tak, Valeria.
{31821}{31877}Nenašli sme iadne falošné|registraèné údaje.
{31887}{31959}Èas našich údajov bola|poškodená kvôli tım pirátom.
{31975}{32040}Nechajme to teda tak.
{32071}{32104}Tak dobre.
{32158}{32214}Jedná sa o tvoju hrdos,|e, Duuz?
{32228}{32281}Dobre. Zachránil si si tvár.
{32291}{32323}Gene, Gene...!
{32362}{32439}Na h¾adaní pokladu alebo snahe|rıchlo zbohatnú nie je niè zlého.
{32446}{32511}Obidvoje znamená, e máte ve¾ké sny.
{32519}{32570}Hej. Som ti vïaènı.
{32575}{32633}Dostal si svoj Dragonit,|tak padaj odtia¾to!
{32645}{32738}Ale ak sa niekedy dozviem,|e si spáchal zloèin, nájdem si a.
{32750}{32788}Budem si to pamäta.
{32885}{32994}Posádka Outlaw Star,|šastnú cestu!
{33066}{33112}Poïme, Outlaw Star!
{33359}{33466}Obloha, ïaleká obloha...
{33476}{33594}Šepotavı hlas...
{33618}{33881}Tvoje sny teraz otáèajú kolesom hviezd.
{33904}{34164}Nikdy som nikde nebola.
{34179}{34292}Tak som sa cítila,
{34297}{34448}kım som nespoznala poh¾ad tvojich oèí.
{34453}{34685}V kúte môjho srdca je len kúsok mesiaca.
{34689}{34986}Ale je dos jasnı, aby osvietil|aj tú najušiu z ciest.
{35522}{35560}Tu Jim Hawking!
{35566}{35645}Vdy som musel by ten zodpovednı,|lebo Gene ním nie je,
{35650}{35709}ale nieèo mi hovorí,|e u aj mòa si našla láska!
{35718}{35763}Kvôli èomu ijú ¾udia?
{35769}{35801}Aby si uili radovánok!
{35818}{35866}Potom si navzájom s¾úbia veènú lásku,
{35870}{35937}a potom sa pohádajú,|a ena sa vráti domov k svojim...
{35944}{35990}Poèka, to neznie správne...
{36006}{36121}Nabudúce v Outlaw Star!|"Maèky a dievèatá a vesmírne lode!"
