{1}{1}23.976
{86}{153}James Hawking, pre priate¾ov "Jim".
{166}{248}Vek: 11.|Vıška: 140 cm.
{256}{338}Hmotnos: 32 kg.|Krvná skupina: A.
{359}{473}Geniálny chlapec, syn slávneho|hackera známeho ako Poèítaèovı èarodej.
{493}{561}Je opatrnı typ, presnı opak Genea,
{566}{611}a vdy zo sebou nosí poèítaè.
{617}{699}Pozorne sleduje hodnotné|informácie a pohyby nepriate¾a.
{710}{787}Vie rıchlo uvaova, ale tie sa vie|ve¾mi unies svojimi èinmi.
{794}{872}Má pomerne dospelé správanie,|ktoré nepôsobí príliš detsky.
{887}{974}Hoci niekedy ho Geneova neschopnos|myslie dopredu vie napáli,
{976}{1055}neopustil ho, ale posudzuje teraz|jeho èiny ako jeho manaér,
{1071}{1161}a v skutoènosti Genea obdivuje.
{1164}{1200}Veru, je to tak.
{1211}{1270}Kadopádne, som typ èloveka,|ktorı je absolútne nevyhnutnı,
{1271}{1348}aby Geneovi jeho staromládeneckı|spôsob ivota neprerástol cez hlavu.
{1356}{1393}Hej, prestaò preháòa!
{1402}{1441}Odteraz to u nechám na teba.
{1442}{1505}Ja by som ocenil, keby ste ma|nevyrušovali, keï pracujem.
{1515}{1545}- Iste!|- Iste!
{1631}{1712}Semenaide, kesanaide, makenaide...
{1714}{1834}...daredatte motteru|hazu yuzurenai mono.
{1852}{1926}Ai dake, yume dake, kimi dake...
{1929}{2070}...sore dake wa hanasanai,|donna toki de mo.
{2130}{2227}Dou shiyou mo naku,|ochitsukanai yoru...
{2230}{2341}...nani mo ka mo|nagedashitaku naru.
{2342}{2444}Tsubekobe iwazuni,|sassa to doa o akena.
{2444}{2551}Rikutsu nante,|koneteru hima wa nai.
{2557}{2763}Juu'ou-mujin tobimawaritai,|youi-shuutou mamoritakunai!
{2770}{2950}Nakushita wakeja nai,|mada hajimattenai dakara.
{2966}{3047}Semenaide, kesanaide, makenaide...
{3050}{3169}...daredatte motteru|hazu yuzurenai mono.
{3185}{3265}Ai dake, yume dake, kimi dake...
{3268}{3386}...sore dake wa hanasanai,|donna toki de mo.
{3416}{3519}Nani ga hoshii? Nani ga shitai?|Doko ni ikitai?
{3522}{3677}Yami o saite hashirinukete|tsukamitore through the night!
{3850}{3916}Letíme celkom bezpeène.
{3923}{3976}Vnútri ani mimo lode nie je niè neobvyklé.
{3988}{4100}Odhadujem, e za 30 minút|prídeme k tranzitnej stanici Symka 5.
{4208}{4375}Taká jednotvárna cesta toho moc|eponúka pre také ivé dievèa ako Aisha...
{4385}{4434}Monoe je to len taká zhoda okolností,
{4438}{4505}ale fakt sme si vybrali divnú posádku...
{4538}{4602}Jim! Decko, ktoré ešte nevyrástlo|zo svojich plienok...
{4610}{4690}...by nemalo ohovára dospelú dámu!
{4708}{4730}Poèula si to?
{4734}{4849}Upozoròujem a, Ctarl-Ctarl|majú najlepšie uši v Galaxii!
{4857}{4888}Zapamätaj si to.
{4894}{4913}Okej!
{4914}{4956}Akı poslušnı chlapec!
{4965}{5082}Nedávno sa ukázalo, èo sa stane,|keï sa rozhnevá Ctarl-Ctarl.
{5111}{5169}Zdá sa, e si zaèal dospieva.
{5170}{5197}Vïaka tebe.
{5221}{5309}Jim a Aisha tak spolu vychádzajú,|e to vyzerá akoby boli naozaj rodina.
{5337}{5365}Váne?
{5408}{5434}Èaj je vynikajúci.
{5458}{5528}Zaznamenal som loï,|ktorá sa k nám rıchlo pribliuje.
{5538}{5625}Neodpovedajú na moje vızvy.
{5638}{5646}Nepriate¾?
{5650}{5740}BillSK & Pedro uvádzajú:|OUTLAW STAR:|"Maèky a dievèatá a vesmírne lode"
{5767}{5800}Preèo si ich nezbadal skorej?
{5806}{5915}Zdá sa, e pouívajú nejaké prostriedky,|aby sa vyhli môjmu systému senzorov.
{5926}{5979}Take, nevieš, èo sú zaè!
{5981}{6010}Nanešastie.
{6017}{6064}Gene, pribliujú sa!
{6082}{6124}Prechod do grapplerového bojového reimu!
{6394}{6438}Zachytávam z tej lode signál.
{6458}{6481}Pusti to!
{6488}{6546}Vy ste Outlaw Star|a Gene Starwind, pravda?
{6549}{6582}Niè osobné, ale prišiel som a zabi.
{6583}{6613}Tak predsa nepriate¾!
{6617}{6661}Je to jeden z našich kolegov pirátov?
{6670}{6702}Si dos populárny...
{6704}{6743}Nepriate¾ská loï je na dostrel, Gene.
{6761}{6816}Pošli im jeden z mojich horúcich bozkov!
{6824}{6844}Odpa¾ujem strely!
{6924}{6943}Je to návnada!
{7072}{7166}Chceš ma dosta v grapplerovom boji?!
{7412}{7446}Tento nie je moc silnı.
{7545}{7566}Èoe--?
{7698}{7742}Ten chlap je slaboch!
{7746}{7785}Dorazme ho!
{7794}{7826}Èo sa deje?!
{7842}{7901}Tlak na lodi stúpa.
{7910}{7986}Ak to bude pokraèova,|neodporúèa sa zotrváva v bojovom reime.
{7995}{8095}To ja viem, ale oni sú|ednoducho príliš rıchli!
{8109}{8180}Bojová charakteristika Outlaw Star|nie je stavaná na toto.
{8195}{8267}Ale existuje spôsob...|Potrebujem akurát trochu èasu.
{8279}{8334}Jim! Na môj signál, vystre¾ všetko,|èo máme!
{8336}{8375}Jasné! Posledné riešenie prichádza!
{8381}{8403}Posledné riešenie?
{8961}{8984}Bolo to tesne!
{8990}{9050}Tvojím "poslednım riešením" je útek?
{9059}{9089}Zbabelci!
{9094}{9170}Èakal by som trochu vïaènosti za to,|e si ešte stále naive.
{9174}{9241}Pravda, pravda... Dôleité je,|e sme neprehrali.
{9245}{9281}Vy dvaja--
{9283}{9334}Naozaj tvoríte dobrı team.
{9375}{9446}Nu, a také to zas nebolo.
{9498}{9544}Keï mi povedia, e tvorím dobrı team...
{9546}{9594}...s niekım takımto,|tak ma to moc nenadchıòa.
{9602}{9656}Èo to malo znamena, James?
{9658}{9691}Gene, ty si to poèul?
{9695}{9750}Zdá sa mi, e si budeme musie|prediskutova isté veci.
{9752}{9777}Nie, nie, nie!
{9779}{9802}Ale hej.
{9804}{9896}Dámy a páni,|za okamih prídeme na Symka 5.
{10277}{10329}Take, nemali by sme sa poohliadnu|za opravami a vızbrojou?
{10331}{10349}Hej.
{10353}{10390}Ale, kde je Suzuka?
{10392}{10444}Suzu povedala, e si ide zdriemnu.
{10454}{10509}Tá enská jednoducho nevie|pracova ako súèas teamu.
{10510}{10572}Gene, e to vravíš zrovna ty.
{10603}{10657}Tak, Aisha sa ide trocha zabavi!
{10699}{10746}Tá enská jednoducho nevie|pracova ako súèas teamu.
{10747}{10813}Gene, e to vravíš zrovna ty.
{10818}{10837}Sklapni.
{10853}{10912}Èo? Chcete po mne, aby som všetko|opravil a zohnal vızbroj...
{10914}{10950}...pri takomto rozpoète?
{10959}{11018}Dúfali sme, e by sme si mohli nieèo zarobi...
{11022}{11097}Nu, myslím, e si musíte zohna to¾ko,|aby to pokrylo všetky vaše náklady.
{11114}{11130}Èo budeme robi?
{11132}{11166}Akoby sme mali na vıber...
{11167}{11216}Zaènite zatia¾ s opravami trupu.
{11222}{11270}A nešetrite na tom, pane.
{11276}{11338}Pod¾a vybavenia aké tu máte,|dokáem usúdi akı ste dobrı.
{11347}{11421}Rozumiem. Len èo vyplníte papiere,|hneï sa do toho pustím.
{11438}{11466}Vïaka moc!
{11483}{11542}Tá loï by tie mohla by na tejto stanici.
{11545}{11569}Nemali by sme ju poh¾ada?
{11573}{11637}To je v poriadku. Ak po nás pôjdu,|postarám sa o nich.
{11657}{11695}Tomu sa vraví sebadôvera...
{11698}{11740}Alebo mono len lenivos.
{11748}{11769}Èo vravíš?
{11780}{11855}Ale kım sme na stanici,|nesmieme po¾avi v opatrnosti.
{11880}{11903}Gene?
{11937}{11956}Hej.
{11961}{12034}A mimochodom, Jim...|Odchádzam sa napi!
{12039}{12100}Idem to roztoèi|a pusti všetko z hlavy!
{12105}{12155}A ja si tu robím starosti!
{12170}{12225}No tak, no tak! Uvo¾ni sa, partner!
{12238}{12264}Ako chceš!
{12266}{12353}Melfina, prepáè,|ale mohla by si zosta s tımto chruòom?
{12358}{12375}Áno!
{12383}{12401}H-Hej!
{12403}{12457}T-Tak moment!|Chcem pi sám!
{12466}{12486}Bang!
{12503}{12545}Preèo zrovna ja...?
{12574}{12613}Ty si nedáš nieèo?
{12617}{12676}Toto parfait mi úplne staèí.
{12727}{12754}To rád poèujem.
{12956}{13034}Jak to, e ja som vdycky ten,|na ktorom zostane práca?
{13059}{13100}Musí to by aké, Jim.
{13143}{13254}Vïaka. Ty si jedinı, kto chápe|ako ako pracujem, Gilliam.
{13262}{13318}Mám bojové údaje o nepriate¾skej lodi.
{13326}{13390}Bez stratégie tú loï neporazíme.
{13406}{13524}Gene vdy len improvizuje na mieste,|take je to všetko na mne...
{13526}{13584}Mám prinies trochu kávy?
{13594}{13624}Hej, to by bolo skvelé.
{13892}{13977}U je ráno, Jim.|Mono, e by si si mal oddıchnu.
{14000}{14086}Ešte nejdem do postele, avšak|prejdem sa na èerstvom vzduchu.
{14623}{14691}Hej, na staniciach|je vidno maèku len zriedka...
{14759}{14801}No tak, poï ku mne...
{14952}{14989}Fajn...
{15126}{15165}Aha ako pradie...!
{15251}{15322}Hej, poèkajte! Zahrajme sa ešte!
{16502}{16568}Ahoj. To sú tvoje maèky?
{16570}{16626}Tak je. Èo by si chcel?
{16664}{16713}Vlastne niè...
{16723}{16753}Oh.
{16822}{16909}Akurát...|chcel by som sa tebou porozpráva.
{16984}{17009}To je pozvanie?
{17026}{17067}Tak som to nemyslel!
{17094}{17121}Alebo, monoe je...
{17154}{17196}iješ tu, na stanici?
{17205}{17253}Nie, cestujem.
{17302}{17332}So svojimi maèkami?
{17336}{17388}Tak. Toto sú Mata a Kemi.
{17402}{17430}Ako sa voláš?
{17432}{17481}Ja? Som Hanmyo.
{17483}{17604}Ja som Jim Hawking.|Cestou som sa zastavil tu na stanici.
{17666}{17710}Tak, to je osud.
{17733}{17845}Stretli sme sa, lebo sme obaja boli|na svojich lodiach a náhodou sa tu zastavili.
{17852}{17879}Je to osud.
{17904}{17921}Tak je.
{17970}{18030}Musím sa u vráti a nakàmi maèky.
{18047}{18137}A, eh, môem sa dnes poobede|s tebou opä stretnú?
{18172}{18193}Tak dobre!
{18194}{18246}Takr, stretneme sa tu o jednej!
{18248}{18278}Uhm! Maj sa!
{18398}{18474}Produkcia: BillSK|Spracovanie videa: Randy
{18480}{18540}Nie je urèené pre komerèné pouitie.
{18543}{18622}Slovenské titulky: Pedro (pedro_k@post.sk)
{18693}{18725}Dáš si ešte kávu?
{18730}{18753}Vïaka.
{18764}{18791}Mel, kde je Gene?
{18796}{18877}Ešte spí. Vèera toho hodne vypil.
{18878}{18957}Bola si s ním, tak si ho mohla zastavi,|Melfina!
{18959}{19039}Keï som chcela, aby prestal,
{19043}{19090}Gene zaèal pi ešte viac.
{19099}{19125}To sa na Genea podobá...
{19127}{19165}Èo také?
{19176}{19217}Dobré ráno, Gene.
{19231}{19256}Dobré...
{19258}{19291}Èoe sa tak tváriš?
{19293}{19358}Rıchlo sa najedz, a potom do práce!|Dneska toho máme ve¾a!
{19363}{19394}Hej, hej...
{19567}{19604}Hej, pane! Ako to ide?
{19606}{19663}Ide to, ale ja z toho niè nemám.
{19665}{19721}Zdá sa, e vaša loï je špièková.
{19722}{19779}Takıto model som tu|v pohranièí ešte nevidel.
{19783}{19813}Dobrá loï, e?
{19816}{19862}Hej, je dobrá.
{19868}{19897}Tak, pokraèujte v práci!
{19898}{19925}Len to nechaj na mòa!
{19980}{20017}Tak, Gene, ako to ide?
{20030}{20092}Uvedomujem si,|e musíme obmedzi naše vıdavky,
{20096}{20145}ale preèo tie trochu nepomôeš?
{20155}{20238}To, èo si mi tu nadelil,|nie je len také obyèajné opravovanie.
{20242}{20314}Chceš po mne, aby som vymieòal|kabelá v grapplerovıch ramenách?
{20319}{20380}Gene Starwind! Nemáš v sebe nieèo,
{20382}{20426}èo by ti povedalo, e musíš maka|ešte viac ne ja,
{20428}{20486}aby si zaplatil svoju|vèerajšiu útratu v bare?
{20516}{20580}Eeh, bola to moja chyba.
{20586}{20672}Môem pre vás urobi ešte nieèo,|pán James?
{20682}{20757}Akı darèek sa najviac hodí|na prvé rande?
{20852}{20877}Èo je?
{20890}{20944}Koneène si objavil dievèatá?
{20978}{21009}Veru, veru!
{21013}{21071}Toto je tvoj prvı krok na ceste k munosti.
{21073}{21122}K¾udne sa skúsenejšieho na hocièo spıtaj.
{21124}{21177}Kdee! Bol som blbı,|e som sa vôbec opıtal!
{21185}{21219}Moje city sú úprimné!
{21222}{21277}Nie ako tie tvoje nekalé!
{21282}{21347}Èoe?! Cheš poveda,|e moja láska je nekalá?
{21349}{21400}Nekalá, slizká a nechutná!
{21404}{21445}Moc ti to kecá, diea!
{21447}{21490}Oh, nie, aká hanba...
{21660}{21688}Kto je?
{21710}{21734}Hanmyo!
{21741}{21766}Presne!
{21785}{21828}Um... Tieto sú pre teba.
{21857}{21900}Darèek pre mòa?
{21941}{21969}Skvelé!
{22090}{22133}Sú pekné.
{22242}{22290}Uchytenie osi X-axis je normálne.
{22292}{22337}Poškodenie je menšie, ne som si myslel.
{22342}{22369}To sú dobré správy, nie?
{22370}{22428}Hej, táto loï je fakt úasná.
{22444}{22482}Ja si to tie myslím!
{22531}{22567}Deje sa nieèo?
{22581}{22618}Nie, to niè.
{22626}{22645}Gene?
{22649}{22679}Niè to nie je!
{22739}{22801}Ja... ti prekáam?
{22836}{22875}Tak to nie je.
{22898}{22930}Tak to vôbec nie je!
{22954}{23000}Potrebujeme a.
{23007}{23039}Áno.
{23074}{23193}Prepáète za vyrušenie,|ale prišiel video-mail od Freda Luo.
{23209}{23229}Pusti to.
{23238}{23289}Èau, Gene! Máš sa dobre?
{23299}{23363}Toto vysielanie je drahé,|tak to skrátim.
{23365}{23453}Mám nejaké správy o zaujímavom mieste|tıkajúcom sa Galaktického Leyline.
{23460}{23531}Detaily som poslal Jimovi|v zakódovanom súbore.
{23540}{23626}Tak, teda ve¾a šastia.|Dávaj na seba pozor.
{23628}{23646}Koniec správy.
{23648}{23689}Zdá sa, e tam budeme musie ís.
{23705}{23758}Zaèína to by fakt zaujímavé.
{23763}{23837}U zaèínam cíti poklad!
{23848}{23882}Kedy si sa--?
{23936}{23963}Bola to zábava, e?
{23970}{23992}Hej.
{24018}{24068}Rád by som sa s tebou zase|stretol zajtra.
{24073}{24150}Dobre! Budem tu èaka v rovnakom|èase ako dneska. Stihneš to?
{24152}{24196}Budem tu! Budem tu!|Môeš sa spo¾ahnú!
{24202}{24229}Ja tie.
{24278}{24293}Jim?
{24306}{24369}Ïakujem za kvety.|Nikdy som iadne ešte nedostala.
{24380}{24410}To niè. Maj sa!
{24412}{24440}Bye-bye!
{24933}{24990}Hanmyo, nezabudla si na našu prácu,|však?
{24993}{25065}Veru, veru.|Nezabudla si, e?
{25070}{25129}To je v poriadku.|Mám akurát vyradi Outlaw...
{25131}{25186}...a zabi toho chlapa "Genea"|vo vnútri, nie?
{25188}{25269}Okej, okej... Outlaw|ešte neodštartovala.
{25270}{25339}Nemala si to robi, Hanmyo,|dohodnú si zase ïalšiu schôdzku...
{25342}{25373}Mala si sa porozpráva najprv so mnou.
{25379}{25421}A so mnou takisto.
{25427}{25486}Prepáète, prepáète...|Ale je to osud.
{25498}{25561}V poriadku, prácu dokonèím!
{25629}{25667}Všetky systémy v poriadku.
{25684}{25716}Fajn, odštartujeme!
{25728}{25787}Hej, Jim, èo sa deje?|Vyzeráš deprimovanı.
{25792}{25841}Mimochodom, aké bolo rande?
{25850}{25922}Odpá¾! Mal som sa skvele!
{25931}{25965}Poïme u odtia¾to!
{26009}{26077}Prepáè, Hanmyo,|nestihnem to.
{26302}{26384}Zo zadu sa pribliuje jedno plavidlo.
{26503}{26534}Èo má v úmysle?
{26542}{26571}Trvá mu to.
{26574}{26631}Je to ako keï sa maèka zahráva s myšou.
{26643}{26680}Robí si z nás srandu!
{26686}{26758}Zdá sa, e mu musíme ukáza,|èo dokáe myš zahnaná do kúta.
{26767}{26819}Èo by sme mali urobi, James?
{26822}{26896}Koniec korunuje prácu.
{26903}{26933}Èo to znamená?
{26938}{26983}Nájdi si to v slovníku.
{26995}{27031}Ideme do grapplerového boja!
{27039}{27062}Rozumiem.
{27265}{27292}Som pripravenı.
{27294}{27320}Ja takisto!
{27322}{27381}Dorazme ho rıchlo.|Musím stihnú schôdzku.
{27383}{27404}Sústreï sa...
{27406}{27437}...a uvo¾ni sa!
{27438}{27485}Je to v poriadku, cítim to.
{27488}{27543}Sila prichádza. Sme silní.
{27554}{27597}Bude to naozaj fungova?
{27598}{27669}Neviem, ale ak to spravíme ako minule,|tak prehráme.
{27673}{27702}Zrejme.
{27704}{27772}Gilliam! Vypni všetky externé|onitory okrem môjho!
{27782}{27811}Priprav sa aktivova systém!
{27819}{27850}Gene, ty sa koncentruj na pilotovanie.
{27852}{27894}Budem a podporova bez|iadnych inštrukcií od teba.
{27899}{27952}Reakcia ramien bola zvıšená na 150%.
{27958}{28014}Aisha a Suzuka, je to na vás.
{28026}{28084}¼ahké, ¾ahké!|Je to ako hra!
{28095}{28159}Ale keï táto hra skonèí,|nemôeš stlaèi reset.
{28200}{28267}Systém vydrí by funkènı iba|jednu minútu.
{28273}{28342}Prajem všetkım ve¾a šastia.
{28350}{28391}Pustime sa spoloène do toho.
{28404}{28468}Ak to niekto dokáe, tak sme to my.
{28479}{28526}Mám pocit, e nás nikto nedokáe porazi.
{28544}{28581}To by èloveka aj rozplakalo...
{28647}{28673}Poïme!
{28722}{28748}Zaútoèil!
{28822}{28849}Bastard!
{28922}{28947}Robí ïalší nálet!
{29238}{29259}Teraz!
{29384}{29415}Zabil si Kei!
{29417}{29445}Za to zaplatíš!
{29870}{29914}U som pochopila túto hru.
{29925}{29955}Pusti Mata!
{30104}{30131}Odpa¾ujem všetky strely!
{30261}{30289}Mata!
{30300}{30329}Do èerta!
{30632}{30657}Dostali sme ho?
{30678}{30750}Nehıbe sa...|Torarato sa nehıbe...
{30768}{30801}Kemi... Mata...
{30909}{30937}Skvelé!
{30961}{31053}Ale tie sme utrpeli ve¾ké poškodenie.
{31070}{31180}Nemáme na vıber... Budeme sa musie|vráti na Symka 5 kvôli opravám.
{31182}{31209}Èo urobíme s peniazmi?
{31213}{31262}Netráp sa tım!|Nieèo vymyslíme!
{31264}{31307}Èo si takı vyrehotanı?
{31334}{31398}Ja? O niè nejde...
{32449}{32513}Take, vpred za Leyline, za Leyline!|Poklad! Poklad!
{32524}{32585}By Ctarl-Ctarl musí by fajn,|nikdy nema iadne starosti...
{32587}{32684}Èoe? Samozrejme, e také|jemné dievèa ako ja má nejaké starosti!
{32688}{32713}Napríklad?
{32780}{32808}Mám hlad.
{32889}{32936}Tomu hovoríš problém?
{32938}{32983}No a èo je pod¾a teba problém?
{32987}{33091}Napríklad "Akı je zmysel ivota",|"èo je v mojom srdci"...
{33098}{33137}...a "Kto som" a tak!
{33139}{33165}Chıba ti šport!
{33166}{33201}Vôbec!
{33387}{33494}Sora, tooi sora...
{33505}{33623}Tsubuyaita koe...
{33646}{33910}Anata noyume wa ima|hoshi no sharin o mawasu.
{33934}{34193}Watashi, itsumo doko ni mo inai.
{34210}{34321}Sou kanjite ita,
{34327}{34476}sono hitomi shiru made wa.
{34483}{34716}Mune no katasumi kaketa|tsuki ga hitotsu dake.
{34719}{35016}Demo donna ni hosoi michi|mo terasu you ni hikaru.
{35554}{35628}Nabudúce bude tajomstvo Galaktického|Leyline odhalené...
{35630}{35676}...v ruinách na záhadnej planéte!
{35690}{35739}Nechcem by sebeckı ani niè podobné,
{35742}{35795}ale príbehy by mali dodriava|isté pravidlá, však?
{35808}{35839}Chcete to tie vedie?
{35847}{35966}Okej. Verte èi nie,|Leyline je v skutoènosti--
{35974}{36013}Pravdu povediac...
{36014}{36051}...ani ja sám neviem.
