{1}{1}23.976
{106}{230}V takzvanom Pohraniènom regióne,|v oblasti vyše 50 svetelnıch rokov od Zeme,
{246}{315}sa zákony stali prísnejšími...
{324}{389}aby tak vyváili ve¾kı rozsah|ich porušovania.
{413}{488}Zloèinec, uväznenı u len za jedinı závanı èin,
{499}{604}dostane trest smrti po krátkom a rıchlom súde.
{629}{733}Väznica vybudovaná na Hecatoncheir,|svete s vysokou gravitáciou,
{743}{822}je takisto produktom tejto drsnej|pohraniènej spravodlivosti.
{838}{922}Odkedy bola otvorená, stala sa|známa ako pekelné miesto,
{935}{1028}z ktorého sa nikto nedostal von ivı.
{1045}{1129}Prirodzene, nie je ani iaden|prípad úspešného pokusu o útek.
{1154}{1205}A doteraz.
{1357}{1439}Semenaide, kesanaide, makenaide...
{1439}{1561}...daredatte motteru hazu yuzurenai mono.
{1578}{1654}Ai dake, yume dake, kimi dake...
{1654}{1796}...sore dake wa hanasanai, donna toki de mo.
{1854}{1956}Dou shiyou mo naku, ochitsukanai yoru...
{1956}{2070}...nani mo ka mo nagedashitaku naru.
{2070}{2170}Tsubekobe iwazuni, sassa to doa wo akena.
{2170}{2277}Rikutsu nante, koneteru hima wa nai.
{2285}{2491}Juu'ou-mujin tobimawaritai,|you'i-shuutou mamoritakunai!
{2497}{2676}Nakushita wakeja nai,|mada hajimattenai dakara.
{2692}{2776}Semenaide, kesanaide, makenaide...
{2776}{2894}...daredatte motteru hazu yuzurenai mono.
{2912}{2994}Ai dake, yume dake, kimi dake...
{2994}{3112}...sore dake wa hanasanai,|donna toki de mo.
{3140}{3245}Nani ga hoshii? Nani ga shitai?|Doko ni ikitai?
{3251}{3403}Yami wo saite hashirinukete|tsukamitore through the night!
{3518}{3601}Orbitálna stanica na Hecatoncheir,|tu je väzenskı transport 108.
{3606}{3682}Mám jedného väzòa.|iadam o povolenie pristá.
{3696}{3743}Rozumiem, máte povolenie.
{3822}{3903}Curse Hawkwind. odsúdenı|na doivotie za vradu 1. stupòa,
{3905}{3982}lúpe, znásilnenie a ïalších 17 zloèinov.
{3998}{4042}S tımto by mohla by zábava.
{4042}{4078}Pošlite ho hneï dolu.
{4134}{4171}Toto je tvoj jedinı majetok?
{4178}{4244}To je môj talizman pre šastie.|Dobre sa oòho postarajte.
{4484}{4579}BillSK & Pedro uvádzajú:|OUTLAW STAR:|"Útek z gravitaèného väzenia"
{4925}{4994}Vezmi si tácku s jedlom a sadni si!
{5025}{5140}Poèul som, e vonku si bol frajer, ale ak sa|nedokáeš hıba pri tejto nízkej gravitácii,
{5143}{5205}tak tu dlho nepreiješ, Curse!
{5254}{5303}Tri G nie sú niè.
{5310}{5400}V trestnom zariadení na|severnom póle je to vyše 10 G!
{5405}{5522}Za takıchto okolností zomrieš na|zlyhanie srdca ešte skorej, ne ti uplynie trest!
{5606}{5654}Vy tam! Èo si to šomrete?
{5659}{5697}Tak sa u pohnite!
{5774}{5850}Vstávaj, ty nanièhodník!
{5872}{5950}Tak poï, Jake. Nemal by si|robi dorozorcovi problémy.
{5955}{6011}Saiyo, ty sa do toho neple.
{6036}{6059}Oops!
{6154}{6206}Nesna sa uhıba!
{6234}{6290}Pardón, pošmykol som sa.
{6290}{6333}Dos bolo tvojich kecov!
{6450}{6491}To si èo urobil?
{6494}{6539}Nedokáeš reva na niekoho ináè,
{6539}{6601}ne cez kameru tejto svojej bábky,|e, ty úchyl?
{6633}{6687}Ty, tak sa dívaj!
{6730}{6756}Tak, aké to je?
{6970}{7018}Myslíte si, e ste chytrí?
{7024}{7079}Obja ste práve získali 24 hodín|v trestnom zariadení.
{7090}{7195}Práve si sa dostal do Gehenny, Curse,|a tak je naèase, aby si sa jej nauèil bá.
{7201}{7254}Ostatní väzni, pozorne sa dívajte.
{7262}{7381}Z tejto väznice niet úniku,|a nikto mi tu nebude ani odporova!
{7526}{7617}Ty si teda divnı, e si si nieèo|také zaèal dobrovo¾ne.
{7634}{7656}e to vravíš ty.
{7656}{7727}Prestaòte keca a nasadajte!
{7774}{7840}Teda, je drsnı, e?
{7861}{7892}Vdy je takı.
{7969}{8014}Mono som ho nemal to¾ko provokova...
{8182}{8234}Planéta Hecatoncheir?
{8234}{8262}Tak, tak, tak, tak, tak.
{8262}{8386}Je to podivnı svet, príliš hmotnı|na planétu pozemského typu,
{8386}{8434}má neuverite¾ne vysokú rıchlos rotácie,
{8434}{8510}na rovníku má gravitáciu 1 G a je|vytvarovanı do podoby gu¾ky na abakuse.
{8510}{8530}Gilliam.
{8530}{8569}Áno, zobrazím údaje.
{8624}{8669}Èo je to abakus?
{8669}{8828}Ibae, problémom nie je tá podoba|s abakusom, ale gravitácia.
{8843}{8960}Na póloch je 10,4 G a tam, kde sa|nachádza väzenie má stále ešte 3 G.
{8975}{9036}Take by som tam váil trikrát viac, e?
{9043}{9106}Veru tak ! Si chytrı chlapec.
{9117}{9193}A to je dôvodom, e ešte|iaden väzeò nikdy neutiekol.
{9204}{9333}Navyše, pre kadı prípad, nie je|na planéte iaden ovládaè gravitácie.
{9338}{9386}Taktie, vïaka svojej vysokej|rıchlosti rotácie,
{9386}{9506}sa celá planéta správa ako obrovské|dynamo a vytvára silné magnetické pole,
{9511}{9598}take vysielaèka ani radar|na povrchu dobre nefungujú.
{9616}{9697}Pod¾a ¾udského èasu jeden deò trvá 74 minút?
{9697}{9725}Bolo by mi z toho zle...
{9742}{9809}Väznica Gehenna na planéte Hecatoncheir...
{9814}{9873}Poèula som, e nikto sa|odtia¾ ešte nedostal ivı.
{9878}{9993}Gene, tvoja obvyklá zbrklos|ti tentoraz na niè nebude.
{9993}{10091}Suzu má pravdu. Ak do toho skoèíš|bez rozmyslu, je koniec!
{10103}{10140}e to vravíš zrovna ty.
{10140}{10179}Gene...!
{10194}{10249}Mám rád miesta, ktoré sú|povaované za neprekonate¾né.
{10259}{10293}Poïme na to!
{10361}{10388}Kde sú Suzuka a Aisha?
{10392}{10444}Tak ako si povedal, Aisha je s Mel...
{10447}{10493}a Suzuka sa drí Khana ako lep.
{10510}{10557}Fajn, neprestávajte by v strehu.
{10600}{10655}Hej. Urobili ste, o èo som poiadal?
{10666}{10752}Áno. Tu je to, veru tak.|Monopól.
{10760}{10824}Neviem, naèo to chcete poui,|ale je to o to drahšie,
{10824}{10901}e Dragonit je vzácna vec,|take sa snate prinies to spä.
{10911}{10958}Dobre? Rozumiete?
{10970}{11077}Hej, hej, rozumiem.|Mimochodom, dali ste tam to zariadenie?
{11086}{11177}Samozrejme. Ako ste povedali,|zamaskoval som to ve¾mi dobre.
{11180}{11260}Som celkom dobrı, myslím.|Úasné, e?
{11274}{11310}To ste povedali vy.
{11357}{11404}Maj sa, Jim.|Spolieham na teba.
{11404}{11425}Vykonám!
{11936}{11979}Nebude iadne privítanie?
{12145}{12256}Tá poste¾... je len, aby nás trápila,|èi èo?
{12270}{12331}Hej, ty novı. Nehıb sa.
{12358}{12421}Bez obáv, dozorca nepoèúva.
{12434}{12503}Jeho vysielaèka funguje iba vo väzení.
{12509}{12553}Nemajú to¾ko financií,|aby natiahli káble a sem...
{12555}{12642}...a umonili mu prevádzkova robotov|a dohliada na nás kamerami.
{12654}{12750}Tak preèo... teda... postavili toto?
{12760}{12822}Ako formu príuèky.|Avšak je to na zabitie.
{12842}{12926}V tomto pekle s 10 G nemôeš utiec.
{12935}{13039}Urèite... za chví¾u... omdliem.
{13071}{13157}Som prekvapenı, e dokáeš to¾ko rozpráva|pri svojom prvom vılete do chladnièky.
{13173}{13221}Som Saiyo Wong. A ty?
{13279}{13317}To je ale náhoda...
{13322}{13433}Saiyo Wong, prišiel som sem...|za tebou.
{13468}{13490}Èoe?
{13505}{13604}Chcel som... sa a opıta...|na súradnice Galaktického Leyline.
{13619}{13708}Leyline?|Chlapèe, ty si kto vlastne?
{13725}{13797}Len Outlaw... ktorı prechádza okolo.
{13802}{13882}Èo si blbı? Aj keby som ti povedal tie súradnice,
{13890}{13962}keï si raz tu, u sa odtia¾to nedostaneš.
{13965}{14009}Ty si... robíš srandu!
{14026}{14107}Ty si myslíš...|e ja tu chcem strávi zvyšok svojho ivota?
{14130}{14237}Ak chceš, vezmem a... so sebou.
{14304}{14329}Hlupák.
{14336}{14455}Èo je? Hej, tak ako, Saiyo?
{14505}{14594}Je od nich fakt milé,|e nás dovedli spä u po jednom dni.
{14621}{14673}Nemôem uveri, e 3 G môe by také ¾ahké.
{14680}{14777}Ak sa pozabudneš a pokúsiš sa vyskoèi,|tvoje kosti sa ti polámu ako špáratká.
{14778}{14857}Hej, odvèera si bol furt ticho,|a teraz si koneène nieèo povedal!
{14875}{14925}Máš záujem o to, èo som spomínal?
{15006}{15032}Hej!
{15251}{15280}Èo to--?
{15286}{15432}Páni, trvalo to, avšak objavil|sa medzi vami mu s odvahou.
{15442}{15516}Je to Nikolai Illiviè,|ktorého priviedli do väzenia...
{15516}{15588}...pred sedemnástimi dòami|solárneho štandardného èasu.
{15601}{15664}Znièil väzenskı múr s pouitím vıbušniny,
{15664}{15777}ktorú mal šikovne ukrytú vnútri svojho tela,|a potom sa pokúsil o útek.
{15782}{15853}Urèite tu takéto hrdinské pokusy|moc èasto nevidíte, však?
{15910}{16008}Tak, èo keby sme sa pozreli ako sa mu darí?
{16491}{16570}Produkcia: BillSK|Spracovanie videa: Randy
{16574}{16635}Nie je urèené pre komerèné pouitie.
{16638}{16716}Slovenské titulky: Pedro (pedro_k@post.sk)
{17268}{17304}Chapeš to u?
{17312}{17425}Niet sa tu kde ukry v tejto pustine,|a navyše je tu 3 G.
{17438}{17531}Dostanú a skôr ne si to uvedomíš,|a keby si ich aj striasol,
{17531}{17597}jediné miesto, kam môeš utiec je rovník,|kde je gravitácia najslabšia.
{17603}{17642}Pôjdu ti tam oproti a všetkému bude koniec.
{17647}{17709}Nie je šanca uniknú z tohto väzenia.
{17732}{17790}A skúsil si niekedy, ty pako?
{17842}{17863}Hlupák.
{18348}{18389}Fajn, ïalší!
{18449}{18468}Hej!
{18478}{18515}iadne reènenie!
{18522}{18565}Ale no tak, chcel som len pozdravi!
{18661}{18681}Sakra.
{18745}{18794}Divil som sa, e aké monštrum tu nájdem,
{18794}{18842}keï som poèul, e si nejakı|majster bojovıch umení,
{18842}{18902}ktorı v tom bol lepší ešte ne piráti Kei.
{18907}{18993}Ale si len chudáèik, ktorı èaká,|kım nezomrie na zlyhanie srdca.
{19007}{19063}A ja som si myslel, e máš nejakı potenciál,
{19063}{19137}ale ty si len blbı grázlik,|ktorı vie len divoèi.
{19154}{19211}Ja nie som grázel! Som Outlaw!
{19215}{19261}Ak sa chceš nazıva Outlaw, fajn,
{19266}{19327}ale nech na tvoje unáhlené prianie|zomrie nedoplatí aj niekto inı.
{19327}{19353}Unáhlené?
{19357}{19405}Iaden Outlaw by nesedel a neèakal|na smr v tomto pekle,
{19405}{19473}keï nemá èo strati!
{19487}{19577}Ak existuje šanca, nech je|akoko¾vek malá, vyui ju.
{19583}{19630}To znamená by Outlaw!
{19682}{19740}Ty si myslíš, e som tu, lebo chcem?
{19781}{19838}Máš pravdu. Tu v tomto pekle|u niet èo strati.
{19848}{19934}Vieš, e ešte nikto si neodsedel|svoj trest a neopustil toto väzenie?
{19943}{20017}Kadému zlyhalo srdce a zomrel skôr|ne mu vypršal trest.
{20034}{20095}Táto gravitácia je pre ¾udí prive¾ká.
{20095}{20153}Toto miesto je len okázalé popravisko!
{20382}{20410}Chcete nieèo?
{20420}{20510}Ty si ten bastard, èo otravoval pána Wonga?
{20517}{20552}Vy ste tí Saiyoovi poskokovia?
{20571}{20609}Pozor na ústa, chlapèe.
{20625}{20756}Pán Wong sa o nás stará, aj keï to znamená|ís proti tomu bastardovi dozorcovi.
{20766}{20825}Zasran, ako ty sa nemá|èo okolo neho poneviera.
{20875}{20949}Ak je spokojnı s tım,|e je vodcom svorky zbitıch psov,
{20949}{20988}tak to je pre Saiyo Wonga koniec.
{20993}{21021}Zasran!
{21058}{21076}Kruci!
{21178}{21210}Èo je to za rozruch?
{21210}{21254}Vravia, e v saune je bitka.
{21258}{21326}Èo, vari nevedia, e pôjdu do|chladnièky? Kto je ten blbec?
{21332}{21403}Zdá sa, e Jose a ostatní|sa pustili do toho nového.
{21475}{21522}Len schytávam a schytávam...
{21532}{21583}Nebojujete s nesprávnym chlapom?
{21589}{21677}Èo keby ste robili problémy|tomu dozorcovi namiesto mne?
{21826}{21930}Príliš vytàèaš.|Máš prive¾a energie.
{21934}{21961}Èo to má znamena?
{21989}{22052}Kadı si naozaj elá odtia¾to utiec.
{22056}{22099}Ale nemôu s tım niè narobi.
{22104}{22150}Môu buï urobi nieèo šialené|a zomrie tak ako Illiviè,
{22153}{22202}alebo sa všetkého vzdajú|a budú èaka na smr.
{22214}{22314}Medzi tımito ¾uïmi príliš vytàèaš,|pretoe máš prive¾a energie.
{22359}{22389}A èo ty?
{22416}{22434}Èo?
{22441}{22523}Tie u si sa vzdal všetkého?
{22529}{22591}Sklapni! Tımto správaním|len ¾udí naserieš!
{22603}{22685}Zrovna ja by som sa vzdal všetkej|nádeje a èakal, e zomriem na takomto mieste!
{22895}{23019}Tak, èo urobíš, keï ti poviem,|e mám tutovı plán na útek?
{23106}{23141}Bitka! Bitka!
{23283}{23369}Pán Wong ide koneène zmláti|toho nového vychytralca!
{23380}{23426}Nedovo¾te, aby sa tí prekliaty|roboti miešali!
{23432}{23463}Tak èo? Tak èo?
{23463}{23526}Chce si niekto vsadi jedlo|na toho nového?
{23534}{23580}Kde je to? Kde je tá bitka?!
{23586}{23646}Miestnos s osobnım majetkom!|Sú v miestnosti s osobnım majetkom!
{23702}{23725}Hajzel!
{23736}{23765}Vy dvaja, prestaòte!
{23914}{23946}Tu máš, zasran!
{23985}{24013}Najprv ty!
{24120}{24173}Hej! Èo si myslíte, e robíte?!
{24179}{24263}Ak máte to¾ko energie navyše,|postarám sa, aby ste ju minuli!
{24266}{24329}48 hodín v chladnièke!|Hneï teraz!
{24329}{24348}Hej, hej...
{24348}{24401}Rozèu¾ovanie škodí vášmu krvnému tlaku.
{24406}{24427}Dr hubu!
{24446}{24478}Nevravel som to u?
{24478}{24555}Dokázal by si krièa na niekoho,|keby to nebolo cez kamery tıch tvojich bábok?
{24560}{24584}Ty jeden...
{24654}{24678}Nedával som pozor...
{24750}{24769}Kruci...
{24774}{24814}To máš za tie reèi...
{24814}{24933}Nemôem uveri, e som dôveroval|takému idiotovi ako ty... Vychádzam z cviku?
{24942}{24995}Tak, získal si, èo si potreboval?
{25006}{25048}Hej. A èo ty?
{25136}{25159}Len to nechaj na mòa.
{25238}{25342}Upozornenie. Upozornenie.|Abnormalita na lineárnom vozni 002.
{25352}{25401}Vozeò sa vymkol kontrole a je neovládate¾nı.
{25417}{25451}Ako to?
{25545}{25633}Si si... istı, e to je naozaj v poriadku?
{25646}{25679}Neboj.
{25687}{25785}Ak aj...vyskoèíme... na zastávke,
{25793}{25914}gravitácia je... taká silná...|e radšej by sme mali zastavi u teraz.
{25926}{25960}Vydr!
{25972}{26006}Rob nieèo!
{26006}{26068}Je to úplne mimo moju kontrolu.
{26073}{26159}Aby sa to zastavilo,|je treba vypnú všetky systémy.
{26166}{26216}Mám zaèa s vypínaním?
{26231}{26269}To nemôem urobi!
{26475}{26562}Lineárny vozeò 002 prerazil|bránu trestaneckého centra.
{26562}{26595}Teraz sa prediera snehovım po¾om.
{26611}{26695}Myslia si, e sú chytrí, e?|Okamite ich chyte!
{26695}{26749}Budú si ela, aby sa nikdy nenarodili!
{27074}{27178}Dosia¾ šlo všetko pod¾a tvojho plánu,|ale èo urobíme teraz?
{27213}{27251}Len sleduj.
{27271}{27339}Hej, hej... Èo chceš robi s tım amuletom?
{27347}{27384}Chceš sa zaèa modli?
{27399}{27452}Toto nie je obyèajnı kompas.
{27457}{27534}Sú tam dva monopóly,|magnetické èastice s jednım pólom,
{27534}{27587}ale je to urobené tak,|e to vyzerá ako benı kompas.
{27594}{27633}Máš nejakı trik v rukáve?
{27638}{27663}Nieèo také.
{27670}{27745}Curse! Wong!|Odtia¾to niet úniku!
{27754}{27823}Ak sa pokojne vzdáte,|zaruèujem vám rıchlu smr.
{27853}{27899}Sklapni, ty kretén!
{27913}{27986}Škoda. Mal som sa tu tak dobre...
{27992}{28017}H-Hej!
{28017}{28071}Hej, tak poèuj.|Toto je severnı pól, e?
{28078}{28153}Magnetickı junı pól je priahovanı,|a severnı pól je odpudzovanı.
{28163}{28244}Ale magnetickı monopól má len jedinı pól,
{28244}{28325}take junı monopól|bude vahovanı do zeme--!
{28337}{28434}A severnı monopól vzlietne|v smere magnetickıch siloèiar!
{28473}{28496}Èoe?!
{28593}{28646}Aj keby niekto vymyslel takı šialenı nápad,
{28650}{28694}nemyslel som, e bude takı šibnutı,|aby to urobil!
{28704}{28752}A ako vysoko vlastne chceš ís?
{28758}{28801}Kım si nás nevyzdvihnú.
{28812}{28929}Akurát sa modli, aby moji|priatelia zaleteli, èo najnišie.
{28933}{29029}Tebe šibe, Curse! U nikdy s tebou|nechcem ma niè spoloèné! Nikdy!
{29064}{29110}Moje skutoèné meno nie je Curse.
{29110}{29161}Som Gene. Gene Starwind.
{29179}{29225}Zachytávam magnetickú stopu po monopóle.
{29245}{29291}Stúpa nad severnım pólom.
{29291}{29316}To je Gene!
{29322}{29371}Okej! Nad pólom je pomerne prázdno.
{29378}{29432}Zachytíme ich v plnej rıchlosti!
{29432}{29462}Rozumiem.
{29637}{29704}Nad planétou sú detekované|sub-éterové stopy...
{29704}{29751}...zostupujúce blízko severného pólu.
{29760}{29789}Èoe to je?
{29830}{29859}N-Nemohli predsa--
{30117}{30152}To nie je moné!
{30161}{30232}Za nimi!|Ak uteèú, som znièenı!
{30238}{30277}Za nimi! Dostaòte ich!
{30279}{30364}Nikto by to nestihol vèas,|ani z prístavu na stacionárnom orbite.
{30409}{30450}Do èerta s nimi!
{30522}{30607}Ten dozorca má teraz urèite záchvat.|Prial by som si vidie jeho vıraz.
{30607}{30687}Buï vány. Aj keby sa rozplakal,|u nikdy ho nechcem znovu vidie.
{30714}{30739}To je fakt.
{30748}{30782}Gene! Dobrá práca!
{30782}{30800}Vïaka.
{30800}{30885}Vıborne! Vıborne!|Ve¾mi dobre!
{30891}{30949}No a Leyline? A èo súradnice k Leyline?
{30956}{31012}Ešte si sa nespıtal?|Nespıtal si sa?!
{31018}{31042}Mel má prednos.
{31051}{31095}Oh. Istee.
{31095}{31144}Oh, aká otrava,|aká otrava...
{31158}{31219}Znamením pre raòajky je strieborná lyièka.
{31246}{31267}Vyšlo to!
{31267}{31295}Si v poriadku?
{31346}{31367}Melfina...
{31367}{31393}To je... To je...?
{31414}{31474}Gene? Kedy si sa prezliekol?
{31510}{31574}Tak, u si spokojnı?|Rıchlo sa ho spıtaj na Leyline--
{31618}{31666}Je tento chlap dobrı alebo zlı?
{31666}{31706}Je to hlupák. Hlupák.
{31718}{31763}Môeš poui loï tohto mua.
{31765}{31851}Na oplátku, mohol by si ho na|nejakom vhodnom mieste vyloi?
{31864}{31902}Nezabi ho?
{31902}{31987}Veï som ti povedal, nie? Som Outlaw,|ale nie som zloèinec.
{32017}{32045}Fakt.
{32071}{32139}Analyzuj toto. Je v tom dátovı súbor.
{32148}{32225}Heslo je "Miranda".|Je to meno mojej dcéry.
{32260}{32288}Pekné meno.
{32300}{32343}Iste. Veï to ja som jej ho dal.
{32348}{32421}Take, v tom dátovom súbore|sú súradnice Leyline.
{32421}{32474}Môeš sa tam ís zabi, mne je to jedno,
{32484}{32525}ty jeden Outlaw.
{33118}{33225}Sora, tooi sora...
{33235}{33354}Tsubuyaita koe...
{33378}{33641}Anata noyume wa ima|hoshi no sharin o mawasu.
{33665}{33923}Watashi, itsumo doko ni mo inai.
{33941}{34053}Sou kanjite ita,
{34058}{34207}sono hitomi shiru made wa.
{34214}{34440}Mune no katasumi kaketa|tsuki ga hitotsu aru dake,
{34443}{34745}demo donna ni hosoi michi|mo terasu you ni hikaru.
{35314}{35357}Keï máme Galaktickı Leyline|u takmer priamo pod nosom,
{35360}{35454}ideme navštívi istú planétu kvôli nábojom|do Casteru, aby sme doplnili svoju zbrojnicu.
{35466}{35545}Tam sme narazili na troch záhadnıch èarodejov,
{35550}{35660}a tie na raj plnı vzrušujúcich dievèat!
{35666}{35736}Je dobré by naive!|Vïaka ti, Boe!
{35753}{35858}Nabudúce v Outlaw Star!|"Planéta horúcich prameòov, Tenrei!"
{35866}{35919}Radšej sa pripravte!
{35921}{35965}Rıchlo, rıchlo, rıchlo!
{35882}{35976}Planéta horúcich prameòov, Tenrei