{1}{1}23.976
{93}{175}Semenaide, kesanaide, makenaide...
{175}{297}...daredatte motteru hazu|yuzurenai mono.
{314}{390}Ai dake, yume dake, kimi dake...
{390}{532}...sore dake wa hanasanai,|donna toki de mo.
{588}{690}Dou shiyou mo naku,|ochitsukanai yoru...
{690}{803}...nani mo ka mo|nagedashitaku naru.
{803}{903}Tsubekobe iwazuni,|sassa to doa wo akena.
{903}{1011}Rikutsu nante,|koneteru hima wa nai.
{1019}{1225}Juu'ou-mujin tobimawaritai,|you'i-shuutou mamoritakunai
{1230}{1412}Nakushita wake ja nai,|mada hajimattenai dakara.
{1427}{1512}Semenaide, kesanaide, makenaide...
{1512}{1630}...daredatte motteru hazu|yuzurenai mono.
{1648}{1730}Ai dake, yume dake, kimi dake...
{1730}{1848}...sore dake wa hanasanai,|donna toki de mo.
{1876}{1979}Nani ga hoshii? Nani ga shitai?|Doko ni ikitai?
{1985}{2138}Yami wo saite hashirinukete|tsukamitore through the night
{2398}{2494}BillSK & Pedro uvádzajú:|OUTLAW STAR: "Návrat do vesmíru"
{2518}{2591}Preskúšame tvoju spôsobilos.|Uká dievèa.
{2602}{2632}Tu je.
{2922}{2949}Je to dievèa.
{3044}{3089}Leyline zvauje.
{3100}{3182}Leyline sa bude zhovára so iadate¾om.
{3341}{3465}Ty, ktorı si prišiel s dievèaom,|aké je tvoje prianie?
{3474}{3504}Chcem moc.
{3520}{3579}Takú nesmiernu moc, e sa aj|krá¾ Tendo predo mnou skloní,
{3582}{3693}a ktorá mi dovolí rozdrvi aj cisára.
{3724}{3786}To je tvoje prianie?
{3802}{3852}Tak teda moment!
{3990}{4017}Cie¾...
{4037}{4080}Prišiel som si vyzdvihnú|cenu za druhé miesto.
{4088}{4150}Ksakru... Gene Starwind?
{4160}{4189}Tu máš!
{4572}{4634}Hm. Tak predsa len,|som tu tretí...
{4638}{4718}Aké vıhodné. Teraz|nemusím nikoho zabi.
{4766}{4838}Je Leyline Akašickou kronikou?
{4850}{4946}Má tú moc, ale nielen tú moc.
{4989}{5030}Aha! Èiary èchi!
{5030}{5118}Odtia¾to mono ovláda zákonitosti dejov!|Preto meno Leyline!
{5126}{5172}Manipuláciou všetkıch èiar|èchi v tomto vesmíre,
{5174}{5265}sa ovláda faktor, ktorı nazıvame "osud",|ako keby išlo o fyzikálny zákon!
{5282}{5368}Môem sa koneène nauèi, èo chcem vedie?|Všetko, èo chcem vedie?
{5389}{5437}Odpoviem na všetko.
{5452}{5501}Poskytnem všetko.
{5575}{5601}Gwen Khan.
{5710}{5773}Toto je môj poslednı naboj.|Chceš ho pocíti?
{5783}{5821}P-Poèkaj!|Zadr!
{5824}{5943}Keï nebudem naive, vieš... Ak zomriem,|to èo sa nauèím vıjde nazmar, nie?
{5958}{6010}Toto je miestnos s pokladom?
{6060}{6104}Melfina! Si v poriadku?!
{6119}{6144}Melfina!
{6152}{6175}Gene...
{6221}{6273}Ako vrátim Melfinu|spä do normálu?
{6280}{6411}Gene, dosiahli sme Leyline!|Mali by sme oslavova!
{6423}{6534}Môeme si to necha.|Môeme ma všetko. Všetko.
{6534}{6562}Hocièo!
{6570}{6626}No tak! Èo by si chcel?
{6642}{6717}Peniaze? Politickú moc?|Informácie?
{6729}{6825}Všetko, èo chceš je priamo tu.|Priamo tu!
{6834}{6974}Ty, ktorı si prišiel s dievèaom,|aké je tvoje prianie?
{7098}{7130}Èo to? Èo to?
{7288}{7339}Som Hazanko.
{7348}{7449}Útok Casterom na mòa nepôsobí.|Je to márne.
{7473}{7520}Ja som Gene Starwind,
{7526}{7587}Outlaw, ktorı nemá|vo zvyku poèúva varovania.
{7590}{7635}Prišiel som si sem po Melfinu.
{7690}{7755}Èo ty o nej vieš?
{7768}{7911}Melfina je bábka, ktorú sme vytvorili|pomocou znalostí, ktoré sme odkryli.
{7954}{8035}Tak, tak, tak. Tak je.|Je to celkom tak.
{8035}{8059}Prestaò!
{8059}{8181}Projekt Leyline bol zaloenı|na vedomostiach z Hrobu Draka.
{8200}{8294}Vytvoril bábku obsahujúcu|navigaènı systém pre vstup do Leyline,
{8294}{8441}ktorá je tie k¾úèom na|otvorenie dverí k Leyline.
{8453}{8513}A to si ty, Melfina.
{8539}{8590}Bábka... to som ja?
{8590}{8618}Prestaò!
{8618}{8658}Vedel si to, Gene?
{8658}{8730}Melfina. Toto nie je minulos,|ktorú by si potrebovala.
{8745}{8787}Odpoveï, ktorú si h¾adala je...
{8787}{8909}Dám ti tú odpoveï.|Melfina je nástroj, ktorı sme potrebovali.
{8915}{8987}Priviedol si ma sem,|lebo si o tom vedel, Gene?
{8987}{9012}Nie!
{9012}{9043}Váne nie?
{9049}{9094}Som len nástroj?
{9094}{9129}Presne tak.
{9129}{9151}Nie!
{9151}{9182}Absurdné.
{9239}{9261}Gene!
{9680}{9713}Nebezpeèenstvo.
{9720}{9751}Nebezpeèenstvo.
{9813}{9840}Sú màtvi.
{9845}{9873}Sú màtvi.
{9882}{9913}Vrá ich.
{9915}{9949}Vrá ich.
{10072}{10171}Je to u 24 hodín,|èo Lord Hazanko odišiel...
{10195}{10254}Nikto sa neskontaktoval s loïou...
{10331}{10384}Gilliam. Je nejaká|správa od Genea?
{10384}{10443}Mrzí ma to, ale nezachytil som|dosia¾ iadnu správu.
{10455}{10520}Jim, zostaòme pokojní a èakajme.
{10520}{10607}Presne tak.|Pokojní, pokojní, pokojní...
{10631}{10693}Ako môem by teraz pokojná?
{10834}{10885}Tak, braèek. Zobudil si sa?
{10888}{10917}Harry?
{10917}{11024}Nie. Som teraz|v poèítaèi Shangri La.
{11040}{11133}Spravil som si zálohu pre prípad,|e by sa nieèo stalo s mojím originálom.
{11138}{11166}Take tak.
{11178}{11266}Vystopoval som senzory v tvojom tele|a priniesol a naspä sem.
{11271}{11353}Si ako zranenı, take tu|na nejakı èas musíš zosta.
{11367}{11441}Ron, èo sa stalo s mojím originálom?
{11486}{11534}Nieèo zlé.
{11548}{11601}Harry, poïme zatia¾ preè.
{11617}{11667}Ale toto nie je ešte koniec.
{11667}{11697}Presne tak.
{11697}{11807}Ukáeme im, èo sa stane, keï si|zaènú s bratmi MacDougallovcami.
{11821}{11874}Bratia MacDougallovci...?
{12241}{12301}Gene Starwind.
{12486}{12546}Melfina.
{12546}{12571}Hazanko.
{12571}{12632}Gwen Khan.
{12899}{12922}Gene.
{12938}{12966}Gene!
{12981}{13010}Gene!
{13561}{13593}Gene!
{13642}{13666}Melfina...?
{13714}{13809}Gene, som napojená na vô¾u|Galaktického Leyline.
{13820}{13908}Hazankova Tao mágia a energia|z tvojho Castera zreagovali,
{13915}{13969}a my všetci sme prestali fungova.
{13985}{14012}Sme màtvi?
{14016}{14075}Odpoveï na to je áno i nie.
{14093}{14198}Vô¾a Leyline nás drí|naive na inom mieste.
{14219}{14317}V svojom súèasnom stave ti dokáem vysvetli,|èo je to Galaktickı Leyline.
{14338}{14445}Je to galaktická kninica, ktorú zanechala|vyhynutá rasa ovládajúca...
{14445}{14510}...vysoko rozvinutú vedu a technológiu.
{14523}{14620}Pre ¾udstvo je to nieèo ako strojovı boh.
{14629}{14696}Len èo sa ukonèí lieèba|a nastane návrat do reality,
{14708}{14769}Leyline ti pravdepodobne|splní tvoje prianie.
{14790}{14831}Toto nie je realita?
{14840}{14869}Sú to dáta.
{15010}{15064}Toto je kyberpriestor?
{15105}{15135}Hej, Gene.
{15141}{15200}Vïaka tebe som sa koneène dozvedel,|èo som chcel vedie.
{15206}{15257}U mám svoju odpoveï.
{15270}{15345}Take zbohom.|Ja som dáta a dáta sú ja.
{15354}{15391}Zbohom. Zbohom.
{15424}{15474}Teda, v tom èloveku sa nedá vyzna.
{15474}{15516}Toto je skladisko údajov.
{15520}{15605}Prianím profesora Khana|zrejme bolo získa vedomosti.
{15619}{15679}Gene, èo si praješ ty?
{15690}{15820}Dokáem to teraz splni|za pouitia moci Leyline.
{15927}{15948}Gene?
{15958}{16009}Ja od Leyline nechcem niè.
{16015}{16078}Jediné, èo chcem je,|aby si sa vrátila so mnou.
{16078}{16109}Gene...
{16190}{16291}Opä som a rozplakal?|Melfina, ty si èo eláš?
{16291}{16410}Chcem zosta taká aká som.|Chcem zosta s tebou, Gene.
{16444}{16481}Toto je to, èo chcem.
{16695}{16751}Poï so mnou, Melfina.
{16761}{16785}Áno.
{16812}{16830}Èo je?
{16830}{16945}Hazanko sa chystá odís.|Získal moc, ktorú si prial.
{16966}{17037}Ak ho nezastavíme, vesmír sa|ocitne v nebezpeèenstve.
{17042}{17066}Èo urobíme?
{17074}{17169}Spojím svoju silu s tvojou|a budeme s Hazankom bojova.

{17170}{17250}Produkcia: BillSK|Spracovanie videa: Randy
{17256}{17317}Nie je urèené pre komerèné pouitie.
{17320}{17397}Slovenské titulky: Pedro (pedro_k@post.sk)

{17615}{17700}Mám ju. Mám tú moc. Moc.
{17906}{17938}Èo sa deje?
{17990}{18020}Èoe...?
{18024}{18070}È-Èo je to?
{18194}{18231}Všetky systémy v poriadku.
{18261}{18296}Prepáète, e som vás prekvapila.
{18310}{18343}Gene, tu som.
{18422}{18446}Gene?!
{18456}{18529}Zasvätím a do tıch|magickıch trikov neskôr, James.
{18548}{18583}Outlaw, ideme.
{18603}{18642}Je to zázrak?
{18642}{18698}Hej. Stretol som Boha.
{18712}{18793}Gene, teraz sme napojenı na Leyline.
{18805}{18852}Uvo¾ni si myse¾ a bojuj.
{18868}{18916}Mal by si by silnejší ne zvyèajne.
{18927}{18967}Rozumiem. Poïme na to.
{19450}{19546}Zaplatíš. Donútim a|zaplati, Gene Starwind.
{19689}{19725}Sklapni!
{20642}{20664}Bastard!
{21002}{21027}Ty jeden...!
{21329}{21421}Absorbujem a do seba...!
{21476}{21540}Gene! Nie sme sami!
{21546}{21592}Spoloène! Pracujme spoloène!
{21592}{21606}Gene!
{21608}{21618}Gene!
{21620}{21638}Gene!
{21654}{21682}Všetci...
{21710}{21729}Èoe?
{22871}{22894}Skap!
{23845}{23866}Melfina!
{23875}{23898}Melfina!
{23904}{23929}Melfina!
{23997}{24039}Som rada, e sme sa spoznali, Melfina.
{24039}{24064}Ty si...
{24064}{24134}Galaktickı Leyline|sa presúva na nové miesto.
{24138}{24201}Idem s ním, tak som sa prišla rozlúèi.
{24205}{24246}Ty si... ja?
{24262}{24329}Správne. Tvoje ja,|ktoré je dievèaom z Leyline.
{24338}{24378}U ma viac nepotrebuješ, e?
{24378}{24525}Okrem toho, teraz u vieš,|ako da svojmu srdcu krídla, nie?
{24532}{24577}Hej. Ïakujem.
{24615}{24637}Zbohom.
{24656}{24683}Zbohom.
{25343}{25444}"Priekopník" McCoy. "Zamraèenı" Lotus.|Hilda "Horúci ¾ad".
{25466}{25554}Keï si Outlaw získa reputáciu,|dostane prezıvku, ktorá ho vystihuje...
{25554}{25614}Hm... Aká by sa hodila pre toto decko?
{25634}{25680}Èo takto "Raz ti to zaplatím" Gene?
{25680}{25715}To je trošku prehnané.
{25715}{25822}Keï o tom tak vravíš, poèul som,|e sa vrátil na Sentinel III.
{25930}{26007}Poèula som, e Gene sa vrátil|spä na Sentinel,
{26007}{26056}tak preèo sa nezastavil v bare?
{26070}{26114}To je fakt.
{26199}{26250}Môeš ís, Gene Starwind.
{26278}{26310}Nie som prekvapenı.
{26313}{26367}Nemôem uveri,|e na to nezabudli...
{26373}{26438}Buï rád, e a to stálo|len 200 000 wongov.
{26438}{26493}Riadne si rozbil|zariadenie kozmodrómu.
{26504}{26569}To preto, e nás prepadli|piráti, spomínaš?
{26578}{26637}A vôbec, vraj, kontrolór|vzdušnej prevádzky bol tie v tom.
{26650}{26703}Veï preto si z toho vyviazol|len s pokutou.
{26727}{26758}Zákon je zákon.
{26764}{26805}A zloèin je zloèin.
{26830}{26885}Hej, kde si vzal 200 000?
{26890}{26933}Tam, kde vdy.
{26940}{26980}Poièal nám, èo sme si potrebovali doplni,
{26982}{27045}ale povedal, e by si chcel vypoèu,|ako mu chceme zaplati.
{27045}{27066}Akı je plán?
{27066}{27108}Zloèin je zloèin.
{27133}{27201}Ak nechce poèka,|kım nieèo získame, tak zdrhneme.
{27207}{27252}Získame...?
{27289}{27394}Nemôem uveri, e Tasogare no Suzuka|putovala spolu s Geneom.
{27403}{27435}Neboj sa.
{27439}{27501}Zdá sa, e môj zamestnávate¾|mi u nemôe zaplati,
{27506}{27567}take u nemám dôvod,|aby som a zabíjala.
{27575}{27634}Robil som, èo som mohol.
{27647}{27701}Take, zostaneš s ním?
{27706}{27777}Gene povedal, e má namierené|do systému Oracion,
{27782}{27878}ale ja som tam u bola,|take myslím, e odmietnem.
{27890}{28000}Aisha tu zatia¾ zostane,|kım ju Impérium neodvezie domov.
{28049}{28101}Fred. Sú náhradné diely naloené?
{28122}{28165}Boli naloené u dávno.
{28173}{28252}S tımto robí moja pôièka|1,6 milióna wongov.
{28257}{28325}Platbu si iadaj od toho flákaèa.
{28330}{28367}A kde je Gene?
{28370}{28442}Oh. Išiel na návštevu.
{28738}{28777}Pre koho sú tie kvety?
{28823}{28914}Pre kadého, kto zomrel kvôli Leyline.
{28938}{28965}Ach tak.
{29219}{29307}Nezabudni, èo sa tam stalo.|Ty si ty.
{29370}{29441}Nezabudla som, Gene. Ja som ja.
{29449}{29484}To je všetko, èo potrebujem.
{29894}{29955}Take, èo keby sme u šli?
{29962}{29986}Hej.
{31339}{31393}Outlaw Star, ideme!
{31847}{31954}Sora, aoi sora...
{31961}{32080}Tsubuyaita koe...
{32103}{32365}Anata no yume wa ima|hoshi no sharin o mawasu.
{32390}{32647}Watashi, itsumo doko ni mo inai.
{32665}{32777}Sou kanjite ita,
{32782}{32931}sono hitomi shiru made wa.
{32938}{33157}Mune no katasumi kaketa|tsuki ga hitotsu aru dake,
{33174}{33471}demo donna ni hosoi michi|mo terasu you ni hikaru.
{34089}{34165}Teda, jak to, e máme poruchu?
{34174}{34238}Pretoe furt šetríme|na vıdavkoch na údrbu.
{34242}{34317}Zdá sa, e vımena dielov|a opravy sú ukonèené.
{34337}{34400}Hotovo. Len to tu podpíšte, prosím.
{34414}{34442}Hej, hej...
{34488}{34552}Dobre, to je všetko.|Tak, šastnú cestu.
{34555}{34590}Hej, vïaka...
{34605}{34653}Cesta spä bude pokojná a tichá...
{34782}{34825}Tak, èo keby sme u šli?
{34851}{34875}Suzuka?
{34890}{34910}Aisha?
{34922}{34961}Èo vy tu robíte?
{34981}{35040}Napadlo ma,|e keï som s vami,
{35040}{35094}tak aj miesta, ktoré som u navštívila,|sa ešte môu ukáza ako uzaujímavé.
{35103}{35157}Zviezli sme sa na tej|opravárenskej lodi.
{35157}{35248}A keï na to tak myslím,|ste mi stále ešte dlní.
{35254}{35326}A kım mi všetko nezaplatíte,|bez preháòania...
{35329}{35387}...môem poveda,|e vaša loï patrí mne!
{35433}{35483}Dobre, dobre...
{35522}{35611}Ste všetci pripravení?|Odlietame.
{35617}{35655}Všetky systémy v poriadku.
{35669}{35713}Outlaw Star, štart.
{35719}{35743}- Rozumiem.|- Rozumiem.
{35907}{35969}Gene Starwind. Pozemšan.
{35969}{36008}Vek 20. Outlaw.
{36014}{36111}Jeho partnerom je Jim Hawking, vek 11.|Poèítaèovı technik.
{36117}{36200}A je tie potvrdené,|e jeho navigátor sa volá Melfina.
{36211}{36294}Hovorí sa, e ho sprevádza|zabiják menom Suzuka...
{36294}{36389}...a Ctarl-Ctarl menom Aisha,|ale zostáva to nepotvrdené.
{36411}{36460}Jeho loïou je Outlaw Star.
{36469}{36534}Na to, e je novı Outlaw,|ktorı si ešte len musí získa meno,
{36542}{36621}predchádzajú tohto|neobvyklého mua mnohé chıry.
{36630}{36758}Prezıvka, ktorú si pre seba vyslúi,|bude závisie od jeho budúcich èinov.
