{301}{348}Gene! Grappler lode, pøímo pøed námi!
{350}{416}Jinak by to nebyla ádná sranda!|Jdeme na to!
{559}{646}Stále nemùu uvìøit, e se to dìje...
{658}{761}Ale musím to udìlat. Vykroèím|cestou, která je pøede mnou.
{775}{846}Ano... Chtìl sem sem jít.
{858}{886}Do vesmíru.
{959}{1006}Tak, jdi mi z cesty, k sakru!
{2757}{2800}|
{2817}{2933}|OUTLAW STAR: Svìt Outlaw.
{2950}{3025}|
{3025}{3100}|Ze Slovenskıch titulkù: A-H-Sarvill 
{3100}{3175}|
{3175}{3275}|Není urèeno pro komerèní pouití.
{3979}{4022}Vesmír...
{4499}{4562}Nedovolíme jí ádnı další útìk.
{4566}{4639}Vypuste stíhaèky. Na tuhle|vzdálenost jí mùeme dostat.
{4718}{4781}Tady Modrı 3. Pøipravenı na start.
{4787}{4834}Tady Modrı 5. Pøipravenı na start.
{4841}{4892}Tady Modrı 2. Pøipravenı na start.
{4899}{4943}Dobøe. Tady Modrı velitel.
{4950}{5011}Poslouchejte, sráèi. Jdeme proti "Ledovı" Hildì.
{5018}{5044}Dávejte bacha!
{5049}{5122}Nebude to lehké, ale chyte|jí a vezmìte poklad!
{5125}{5146}Jasné?
{5148}{5167}Jasné!
{5169}{5193}Jdeme na to!
{5453}{5506}Rakety! Vypalte pár raket|na A-3, aby jste ji spomalili!
{5507}{5526}Jasnı!
{5630}{5680}Bariéra?! Kruci, nemáme na vıbìr, take...
{5682}{5736}Pøiblite se a vystøelte kotvy,|aby ste jí zachytili!
{6267}{6290}Pøíliš mnoho zásahù.
{6291}{6329}Stav trupu kritickı.
{6333}{6392}Doporuèuje se pouít nouzovı|únikovı modul.
{6483}{6504}Není moné opìtovat palbu.
{6511}{6541}Není moné opìtovat palbu. 
{6718}{6742}Není moné opìtovat palbu.
{6754}{6785}Není moné opìtovat palbu.
{6788}{6859}Zùstat znamená smrt a odejít|znamená smrt...
{7375}{7428}Pøepla na subéterovı pohon.
{7437}{7515}Sakra, ten Horus... Nemùu|uvìøit, e to aktivoval za takovejch podmínek.
{7539}{7583}K èertu s tebou, Hildo...
{7756}{7846}Planeta Sentinel III. Terraformovanı svìt Úroveò-4 .
{7849}{7887}Industriální tøída: 3.
{7891}{7933}Úroveò veøejného poøádku: 4.
{7939}{7996}Populace: 1,52 miliónu.
{8237}{8266}Co to bude?
{8273}{8318}Hledám chlapa jménem Gene?
{8329}{8394}Gene? Co od nìho chcete?
{8423}{8491}Zeptat se ho na mého bratra.
{8505}{8526}Okej...
{8579}{8615}Zdvihám.
{8625}{8684}Slyšel sem, e sem chodí pravidelnì.
{8689}{8726}Mùe bıt.
{8731}{8759}Tak, co povíš?
{8762}{8827}Budeš hlásit? Sloíš?
{8838}{8872}Pojïme, pojïme!
{8874}{8957}Tak? Chodí sem Gene nebo ne?
{8967}{9006}No, já...
{9027}{9052}Co to dìláš?!
{9056}{9134}Musím ukonèit hru. Mám tu|hosta do bitky.
{9162}{9234}Sakra, to není fér! Vìdìl|si pøece, e prohraješ!
{9284}{9315}Co do pekla?
{9342}{9390}Oèekávals nìkoho jiného?
{9484}{9542}Hledáš mì?
{9547}{9696}Gene Starwind? Sráè jako ty|dostal Butche?
{9703}{9812}"Butch"? Ten suchar, co tady|vyvolal bitku minulı mìsíc?
{9820}{9879}Sem za òej dostal celkem slušnı|prachy na to, jaká byl padavka.
{9885}{9921}Sleduj, kurva.
{9927}{10027}Mìl by si vìdet, kdo sem|pøedtim ne zemreš. Sem Rob Cain.
{10041}{10104}Zabil sem 30 lidí a ty budeš 31.
{10106}{10137}"Smrtící" Rob?! /"Shinigami" - Smrt/
{10150}{10190}Nìkteøí lidé mi tak øíkají.
{10260}{10344}Take, ty jsi "Smrkající" Rob?|/"Hanagami" - papírovı kapesník/
{10347}{10378}Sem "Smrtící"!
{10625}{10690}Eštì po nìm nejni, Gene!|Ten chlap je kyborg!
{10926}{10977}Co, uteèeš teï, Kdy nemáš zbraò?
{10979}{11018}To jen, kdyby sem ádnou nemìl.
{11103}{11130}To nefunguje.
{11171}{11249}Gene, on je Typ C! Jdi po|spojovací linii na jeho boku!
{11254}{11285}Jasnı!
{11560}{11617}Zavolej šerifa, Clyde.
{11619}{11674}Gene! Mìla sem takovı strach!
{11731}{11770}U je všechno okej.
{11775}{11829}Tak jí sundej ruku ze zadku.
{11855}{11966}Co myslíš tím "okej"? A co|škody v mim baru?
{11975}{12047}Jime! Jaká je odmìna na "Smrtícího" Roba?
{12049}{12083}4000 wongù.
{12085}{12150}Zapla opravy v baru a zbytek mi vypla.
{12164}{12210}Dnešní noc si to chystám uít!
{12237}{12278}Slyšel sem, e se Gene dnes opìt èinil.
{12279}{12330}Byla to bitka nebo lov odmìn?
{12339}{12386}Øíkají, e u Clydea je to|celé rozbité!
{12398}{12455}Genemu to celkem dobøe jde!
{12580}{12657}Tak, co chceš dìlat, Gene?|Dát si nìjaké dobré jídlo?
{12660}{12732}Jít do kasína? Nebo jít jen...
{12930}{12967}To se nevidí kadı den...
{12969}{13047}Nìkdo jinı ne pravidelnı|let pøistává na Sentinel...
{13063}{13154}Okej! Dnešní noc pùjde kadı|svou cestou, Jime!
{13155}{13199}Co? Proè?
{13210}{13279}Jdu nìkam, kde to není|pro dìti zajímavé.
{13288}{13369}Hej, dìvèata vdy rozvinou|èervenı koberec, kdy jdu!
{13380}{13464}Teda, chceš jít se mnou,|aby se z tebe stal opravdu mu?
{13490}{13544}No, já... Uh...
{13573}{13602}Mnìj se!
{13637}{13731}Gene Starwind, ty podláku!
{14573}{14665}Jsme si jistí, e Hilda utekla|do tohoto svìta.
{14667}{14713}Pred tøemi dny, pøedpokládáme.
{14720}{14806}Pokud se vyhla všem našim|nástrahám, tak zùstává jen tahle oblast.
{14808}{14834}Prohledejte jí!
{15330}{15400}Gene, pùjdeš nìkdy do vesmíru?
{15431}{15496}Jsem si jistá e zùstaneš jakı si, Gene,|dokáeš to.
{15535}{15622}Co budeš dìlat tam nahoøe? Hledat|poklady?
{15627}{15658}Lovit odmìny?
{15667}{15745}Nebo budeš romantikem a jen|tak vyhledávat dobrodruství?
{15754}{15786}Lovit piráty.
{15787}{15836}Coe! To není moné.
{15840}{15885}Také si myslím.
{15896}{16015}Nemám ani vlastní loï, a nikdy|sem tam nahoøe nebyl.
{16106}{16154}Hej, nebuï tak vánı.
{16156}{16182}Jistì.
{17027}{17081}Hej, Gene! U je skoro poledne!
{17094}{17145}Vylez z postele a pojï mi sem|dolu pomoct!
{17288}{17405}Dnes odpoledne nás èeká oprava|traktoru pro Henryho.
{17459}{17510}To je práce tak za 50 wongù, co?
{17511}{17559}Kvùli nìèemu tak malému|nevylezu z postele...
{17561}{17640}V kolik si se v noci koneènì vrátil?
{17682}{17710}V pìt ráno.
{17715}{17774}Zøejmì si o tom ještì neslyšel,|tak ti to radši povím.
{17783}{17867}Ta loï, co pøiletìla minulou|noc byla pirátská.
{17887}{17910}Piráti?
{17914}{17967}Nevím, ke kterı organizaci patøila.
{18096}{18131}Neprošli pøes karanténu?
{18173}{18291}Vesmírné jednotky sem nechodí,|tak staèí jen nìkoho podplatit.
{18405}{18513}Ale, co by je mohlo zajímat|tady na Sentinelu?
{18519}{18584}Ptáš se toho nepravého.
{18678}{18741}Haló, dovolali jste se do firmy|Starwind & Hawking.
{18747}{18842}Opravujeme všechno od traktorùa po lodì |Co pro vás mùeme udìlat?
{18855}{18897}Mám pro vás práci.
{18903}{18972}Rozumím.Mùete mi|øíct detaily?
{18979}{19100}Chtìla bych si objednat nìkolik|speciálních souèástek a tìlesného stráce.
{19115}{19137}Rozumím.
{19151}{19213}Dobøe tedy. A vaše jméno, madam?
{19215}{19276}Ráchel. Dìkuji.
{19638}{19659}No?
{19683}{19765}Ta ena mì poádala o nìjakej|poøádnej hardware.
{19775}{19860}Hej, je to zákaznice. A koèka.
{19914}{19973}eny se ti jednoho dne stanou|osudnımi.
{19976}{20065}Jistì, nesmím to zapomenout|zahrnout do svıch plánù o ideálním ivotì...
{20073}{20145}Dala ti peníze, aby si objednal|souèástky, pravda?
{20151}{20199}Byli pøevedeny na náš úèet,
{20202}{20290}ale jedná se o takové vìci jako bioelementy,|organické systémové díly a nanotechniku.
{20294}{20394}Tyhle vìci sou drahı a tìko se sháòejí.
{20417}{20476}Fakt mì zajímá, na co je potøebuje.
{20480}{20508}Podíval ses na její ID?
{20517}{20564}Všechno v poøádku. Je bezpeèná.
{20624}{20757}Okej. Pùjdu se setkat se|sleènou Bezpeènou a uvidím, jestli je taková doopravdy.
{20769}{20840}Proè by asi sleèna Bezpeèná|ádala o ochránce?
{20855}{20922}Tady máš. U sem ti tam nahrál|všechny údaje.
{20924}{20959}Setkáme se potom na obvyklém místì.
{20960}{20983}Okej.
{21198}{21280}Nelíbí se mi, jak sem chodí|všechny ty zvíøata od té doby co se tu Gene bil.
{21282}{21375}Oh, nebuï taková. Jdou nám z|toho pøece peníze.
{21379}{21480}Nenávidím ho. Podívej na nìj|jak tam flirtuje s tou enou.
{21489}{21536}Nebuï taková árlivá!
{21538}{21588}Tak, pro koho bude ten ochránce?
{21590}{21614}Pro mì.
{21639}{21747}Nevìdìla sem, e toto místo|mùe bıt pro neskušené tak nebezpeèné.
{21753}{21797}Teï jste poprvé v Locustì?
{21807}{21867}Jste turistka? Ne, není tu|na co se dívat...
{21871}{21932}Kvùli své práci. Zastupuju|tady svého otce.
{21959}{22030}Tak, jak dlouho potrvá moje|práce ochránce?
{22034}{22133}Odteï, a dokud neopustím|oblast a skonèím svou práci.
{22136}{22222}Bude to 800 na den, plus vıdaje.
{22243}{22273}Dobøe.
{22278}{22334}Okej. Jsme dohodnutí.
{22420}{22498}Kdy jste tu, Gene, myslím,|e moje práce bude mnohem pøijemnìjší.
{22539}{22590}Co to Jimovi trvá tak dlouho...?
{22606}{22655}Promiòte, mìl by tu bıt kadou|chvíli.
{22657}{22683}To je v poøádku.
{22690}{22723}Kam máme namíøeno?
{22730}{22806}Na farmu 30 km severovıchodnì.
{22810}{22859}Ale to je uprostøed pšeniènıch|polí!
{22862}{22967}Áno. Musím tam opravit farmáøské|vybavení.
{22983}{23032}To proto potøebuje bioelementy?
{23143}{23187}Ten chlapík je váš pøítel?
{23189}{23213}Není!
{23274}{23349}Ty. Nech tu enu a odejdi.
{23353}{23406}Jinak z tebe bude mrtvola.
{23418}{23456}Oh, to je skvìlé...
{23466}{23567}Vyhrouješ mi? Gene Starwindovi?
{23582}{23634}Opravdu? Tak poïte!
{23864}{23898}Hra skonèila!
{24149}{24210}Dlouho èakáte? Zdrel sem se v obchodì!
{24213}{24244}Co budem dìlat?
{24265}{24304}Jseš tu pozdì!!
{24331}{24381}Kdo byli ti chlapi?
{24383}{24409}Jak to mám, do pekla, vìdìt?
{24440}{24492}Fajn, pojïme teda.
{24495}{24518}Dobrá.
{24529}{24572}Mám z toho blbej pocit...
{24593}{24636}Ale práce je práce.
{24641}{24674}Vpøed!
{24938}{25001}Neøíkal sem ti vdycky, aby|si to skontroloval pøedtím ne odjedeš?
{25003}{25075}Nestaráš se o takového veterána,|a chceš v nìm jezdit!
{25327}{25426}Obával sem se zbyteènì. Tahle|práce je asi lehèí, ne sem si myslel.
{25440}{25518}Moná ,e si ti chlapi co vás napadli| mysleli, e jste nìkdo jinı.
{25528}{25604}Vypadali, jakoby mìli napsané|"Pirátská Gilda" pøímo na èele.
{25611}{25691}Není šance, aby piráti šli|po nìkom jako je Ráchel.
{25731}{25846}Kdy teï odboèíš,|dál je jen rovná cesta, Gene.
{25847}{25880}Jo, ja vím.
{26362}{26413}To jsou oni! Piráti!
{26422}{26468}Dobøe trochu si teï zahrajem.
{26478}{26560}Kdy se teï vzdáš, ušetøíme|tvùj ivot, Hildo.
{26571}{26595}Hildo?
{26602}{26626}Hildo?
{26630}{26651}Hildo?
{26691}{26716}Zakryjte si oèi!
{26767}{26792}Dupni na to!
{26917}{26955}K èertu s tebou, Hildo!
{26965}{26987}Já si s tím poradím!
{27521}{27587}Kolik z toho je le, a kolik|pravda?
{27588}{27641}Neexistuje nikdo jménem Ráchel.
{27687}{27750}Ale to, e potrebuju ochránce|je pravda.
{27754}{27851}Take tvoje skuteèné jméno|je Hilda? Proè jdou ti piráti po tobì?
{27856}{27935}Sem jejich nepøítel. Jdeme po|stejném pokladu.
{27938}{28021}Poklad? To jsou zlé správy,|Gene! Kašleme na to!
{28031}{28091}Myslíš, e nás teï nechají jít?
{28112}{28137}U jdou.
{28162}{28190}Co,je k èertu tohle?
{28191}{28224}Pouívají Tao magii?
{28243}{28281}Hildo! Chy volant!
{28299}{28349}Jime! Bláster s krátkou hlavòí!
{28369}{28391}Mám to!
{28519}{28544}Jak se ti to líbí?!
{28697}{28721}Uhni!
{28803}{28824}Bastard!
{28937}{28960}Rozšoupneme se!
{29057}{29089}Houby.
{29184}{29222}Jime! Dej mi èíslo tøi!
{29224}{29271}U nám zùstal jen jeden z tìch nábojù!
{29274}{29303}Jen mi ho dej!
{29355}{29386}Caster?
{29446}{29498}Tu máš, bastarde!
{29761}{29789}Byli zabití.
{29799}{29874}Zdá se, e jsme naše protivníky podcenili.
{29905}{29980}Tak, tady je ukrytı ten tvùj poklad?
{29983}{30020}Mise dokonèená!
{30028}{30094}Dìkuji. Opravdu si toho váím.
{30256}{30278}G-Gene!
{30279}{30304}Stùj!
{30322}{30378}Ještì mám pro tebe práci.
{30583}{30641}Fajn, vytáhni ten kufr.
{30674}{30703}Nalo ho do auta.
{30710}{30772}Co je v tom kufru?
{30778}{30795}Jak si se...?
{30797}{30824}Gene!
{30826}{30939}Promiò, Jime. Zdá se, e budeme|muset postrádat tvùj PDA.
{30950}{30984}Podívej se, co je uvnitø, Jime.
{31032}{31066}Je tam elektronickı zámek...
{31069}{31107}Potøebujem kód!
{31111}{31136}Jakı je kód?
{31138}{31197}Je ve vašem vlastním zájmu,aby jste to neotvírali.
{31210}{31240}Jakı je kód?
{31275}{31327}VSDO2C.
{31387}{31426}Okej, funguje to!
{31513}{31562}G-Gene ..podívej..
{31579}{31649}C-Co do pekla?Co to je..?
{34050}{34077}Ah, teda!
{34082}{34130}Nejprve, nahá dívka v kufru,
{34135}{34188}a potom se za námi znovu enou|piráti!
{34191}{34227}Co se to tu k èertu dìje?
{34245}{34322}Ale teï u nemùem utéct.
{34336}{34392}Jdem spìt do vesmíru.
{34409}{34521}Pøíštì v Outlaw Star!|"Svìt pøání"!
{34531}{34582}Radši se dobøe pøipravte!
