{83}{141}Chlapec má právo snít.
{163}{230}Rozprostírají se pøed ním|nekoneèné monosti.
{251}{354}Co ho oèekává na cestì, kterou|si vybere?
{371}{408}To chlapec neví.
{434}{510}Témìø, kdy se to dozví, chlapec|dospìje...
{515}{590}...a zjistí, kdo se z nìj|za ten èas stal.
{601}{660}Provází to radost i smutek.
{695}{838}Kdy se to stane, rozlouèí se|v srdci se svou minulostí?
{868}{963}A chlapec dospìje,|u se nemùe znovu stát chlapcem.
{979}{1041}Z chlapce je nyní mu.
{1075}{1128}Mùeme povìdìt jen jediné:
{1138}{1200}Chlapec má právo snít.
{1212}{1287}Rozprostírají se pøed ním|nekoneèné monosti.
{1317}{1410}Na jedno pamatujme.Všichni mui byli kdysi chlapci.
{2757}{2800}|
{2817}{2933}|OUTLAW STAR: Svìt pøání. 
{2950}{3025}|
{3025}{3100}|Ze Slovenskıch titulkù: A-H-Sarvill
{3100}{3175}|
{3175}{3275}|Není urèeno pro komerèní pouití.
{3997}{4049}
{4139}{4178}Našla sem je.
{4180}{4209}Pojïme.
{4426}{4475}G-Gene...
{4517}{4590}Co je,k sakru, tohle?
{4620}{4676}Probíhá kontrola resuscitaèního|systému.
{4703}{4753}Tak Hildo.Kdo je to?
{4758}{4790}Melfina.
{4794}{4811}Melfina?
{4813}{4919}Systém normální. Odhadovanı|èas resuscitace, 600 sekund.
{4920}{4967}Zaèíná odpoèítávání.
{4987}{5002}Tøi.
{5008}{5025}Dva.
{5028}{5050}Jedna. 
{5085}{5150}Resuscitace za 600 sekund.
{5155}{5230}Resuscitace? Je ve studém|spánku?
{5279}{5314}O co se to pokoušíš?
{5323}{5457}Jestli se chceš dozvìdìt o Melfine,|oprav mi ruku a ja ti to povím.
{5475}{5510}Kybernetická protéza?
{5511}{5572}Tak proto jsi si objednala|ty souèástky...!
{5575}{5662}Myslím, e si neuvìdomuješ,|v jaké si situaci, Hildo.
{5708}{5761}Jestli chceš vystøelit, tak do toho.
{5771}{5870}Ale jak to udìláš, budeš pronásledovanı|tìmi piráty...
{5874}{5940}...a ani nebudeš vìdìt kdo sem.
{6025}{6086}Jime, oprav Hildì ruku.
{6118}{6153}Nestùj tam jen tak.
{6160}{6227}Odevzdej tu zbraò co máš.
{6232}{6261}Fajn.
{6263}{6298}To by mohlo bıt zajímavé.
{6303}{6332}Moná, e taky bude.
{6351}{6406}Gene, nemùeme jí veøi ani|trochu!
{6408}{6431}Vdy nevìøím.
{6435}{6510}Kdy øíkáš. Já jen, e eny|tì vdycky pøivedou do problémù.
{6512}{6535}To urèitì!
{6538}{6646}Ale døív, ne jí opravíš ruku,|pøiprav se na spoleènost a schovej auto.
{6648}{6670}Jasnı.
{6706}{6785}Tohle je NanoPrometheus špièkové|kvality!
{6858}{6921}Dobøe teda. Kdo, k sakru, jsi?
{6927}{6977}Jmenuju se Hilda. Sem Outlaw.
{6982}{7091}Dokonce i tady na Sentinelu, jsi kde kdo| se svım psem povídá, e je Outlaw.
{7102}{7153}Povìz nám, kdo doopravdy jsi.
{7158}{7205}Není to nic zvláštního, doopravdy.
{7215}{7298}jsem Outlaw, která se dostala|do urèitıch problémù s tìmi piráty...
{7304}{7359}...kdy sem šla po jistém pokladu,|a utekla na tuto planetu.
{7363}{7392}Pøišla jsi z vesmíru?
{7395}{7414}Jo.
{7419}{7448}Ve své vlastní lodi?
{7454}{7549}Nechala sem svou loï na orbitì.|Pøišla sem dolu v modulu.
{7574}{7663}No a proè je to dìvèe pokladem,|za kterım se enou ti piráti?
{7667}{7701}Kdo ví?
{7707}{7798}Chtìli jí, tak sem jim jí ukradla.
{7800}{7836}Jistì.
{7838}{7890}A to by mì mìlo jako pøesvìdèit, jo?
{7899}{7976}Problémy mezi námi nezaèali|u tam.
{7979}{8038}Máme zlou minulost.
{8053}{8086}Skus s tím pohnout.
{8135}{8184}Rád by sem si o tom ješte nìco poslechl.
{8188}{8242}Potøebuju dùvod, aby jsem|nemìla ráda piráty?
{8248}{8317}Ale piráti mají dùvod, aby|nemìli rádi tebe, je to tak?
{8324}{8410}Zabila sem jednoho z vùdcù|Gildy.
{8414}{8458}Stálo mì to dost.
{8460}{8480}Hotovo.
{8551}{8630}Kdy mi nedáš pøímou odpovìï,|bude tì to stát ještì víc.
{8631}{8692}Kvùli èemu má to dìvèe tak|velkou cenu?
{8706}{8778}Resuscitce za 360 sekund.
{8798}{8858}A se probudí, zeptej se jí|sám.
{8866}{8928}Take ty si chceš dál hrát|na blbou, co?
{8950}{8971}Piráti?
{8974}{8997}Zhasnìte svìtla!
{9106}{9178}Víme, e jste tam!
{9181}{9209}Vydejte Melfinu!
{9211}{9246}Mìl sem tušení, e se ukáou...
{9248}{9319}Nebudu vás ádat o pomoc,|jen se mi drte z cesty!
{9323}{9377}Teï u je na to trochu pozdì!
{9380}{9408}Gene!
{9416}{9485}Resuscitace za 300 sekund.
{9501}{9569}Musíme zùstat naivu,|a dokud se Melfina neprobudí.
{9575}{9610}Jime, dej mi náboj è. 3.
{9611}{9630}Došli nám.
{9636}{9666}Nemohli nám dojít!
{9677}{9730}S normálními náboji se mi|toho dìdu nepodaøí sloit!
{9755}{9822}Máme jen jeden è. 5 a jeden è. 19.
{9826}{9899}Èíslo 5 a 19, co...?|Dobøe teda, dej mi je.
{9927}{9961}Jsou drahé, víš o tom?
{9983}{10039}Dokáete vy dva vydret|15 minut?
{10042}{10064}Coe?
{10077}{10140}Pokuï probíhá resuscitace,|není moné s Melfinou hıbat.
{10157}{10209}Ale jestli tu zùstaneme, jsme mrtví.
{10214}{10340}Pokud by jste je dokázali zdret,|mùu pøivolat svùj modul.
{10347}{10412}Chce akorát utéct. Nevìø|jí, Gene.
{10415}{10461}Teda, nic z toho nedává smysl...
{10465}{10527}Okej, Jime, jdi s òí.
{10548}{10574}Já?
{10577}{10630}Pokud se pokusí zdrhnout, tak| toho bude litovat.
{10643}{10706}Kruci, já sem mìl bıt mozkem|tıhle akce...
{10710}{10784}Pøestaò mrhat èas. Dejme|se do toho!
{10787}{10812}Jasnì.
{11010}{11034}Jdìte!
{11137}{11170}Já si s tím poradím.
{11313}{11338}Kde je to?!
{11341}{11374}Potopila sem ho do rybníku!
{11417}{11441}Udìlej to rychle!
{11502}{11547}Máš rád Geneho?
{11569}{11610}Kadı potøebuje partnera.
{11643}{11682}Pochopíš to zachvíli. 
{11762}{11806}Feng leiiku!
{11819}{11868}Oh, do prèic... Ten chlap|je Tao mistr?
{11887}{11918}Feigo!
{12056}{12087}Stará magie?
{12089}{12124}Tady na okraji hranic?
{12127}{12227}Není špatná na è. 5... Take|mi u zùstává jen è. 19.
{12239}{12269}Èas prevzít iniciativu...
{12277}{12325}Starèe, hra skonèila!
{12472}{12503}Náboj selhal!
{12553}{12580}Oh, sakra...
{12617}{12672}Jdìte! Zabijte všechny kromì|Melfiny!
{12842}{12866}Hildo?
{12867}{12906}Je to príliš nebezpeèné! Pøeskupte se!
{13059}{13092}Tomu se øíká masakr...
{13107}{13155}Resuscitace ukonèena. Resuscitace|ukonèena.
{13163}{13190}Probíhá aktivace.
{13700}{13819}Podle Hvìzdného kalendáøe 156:|Byl uspìšnì dokonèen Projekt Leyline.
{13867}{13897}Melfino...?
{14167}{14277}Proè? Proè sem se musela|narodit?
{14304}{14384}Gene! Teï není èas nechat|sleènu plakat.
{14387}{14405}To není kvùli mnì!
{14407}{14457}Gene, vezmi Melfinu pryè!
{14460}{14492}Hilda nás pùjde vyzdvednout.
{14498}{14518}Rozumím.
{14521}{14584}Ale nejprve je tøeba pro tuhle|spící krasavici sehnat nìjaké šaty.
{14587}{14620}Pravda, je to trochu rozptylující.
{14663}{14701}Ste tam dole pripravení? Pojïme|tedy!
{14703}{14725}Okej!
{14727}{14770}Zdá se, e vy dva u spolu|vycházíte.
{14779}{14814}Dosáhli sme porozumení.
{14932}{14959}Snaí se utéct?
{14980}{15008}Za tou loïí!
{15087}{15107}Pohnìte si!
{15369}{15393}Kruci!
{15569}{15688}Èert tì vem, Hildo... Nemysli si,|e pøed Gildou uteèeš!
{15714}{15776}Opouštím orbit a potom opustím|i tenhle systém.
{15778}{15818}Tak jak? Chcete jít se mnou?
{15820}{15879}Pøesnì tak! Vdy jsme ješte nedostali|naše peníze!
{15883}{15911}e, Gene?
{15962}{15999}Co je s ním?
{16004}{16050}Gene má hrùzu z vesmíru.
{16051}{16082}Vùbec nemám!
{16086}{16150}Po prvé to bylo akorát pøíliš|, to je všechno.
{16205}{16238}Ty jsi ale legraèní.
{16241}{16324}Vydr, Gene! Chytím tì za ruku!
{16327}{16391}Ne, díky. Mimochodem, upøednostòuju eny.
{17213}{17294}Horus, vyber nejkratší trasu|k asteroidu Modré Nebe.
{17296}{17319}Rozumím.
{17321}{17347}Modré Nebe?
{17356}{17426}Svobodné mìsto. Navštevují|ho Outlaws.
{17432}{17497}Horus se tam dostane na dva|skoky.
{17559}{17620}Deset sekund do sub-éterového|letu.
{17626}{17646}Devìt.
{17648}{17666}Osum.
{17672}{17693}Sedum.
{17697}{17716}Šest.
{17721}{17748}-Pìt. -U to pøeskoè, jo?
{17748}{17762}-Ètyøi. -U to pøeskoè, jo?
{17768}{17786}Tøi.
{17792}{17810}Dva.
{17816}{17835}Jedna.
{17845}{17866}Start.
{18255}{18325}Zvládl sem u celé ovládání, otèe!
{18800}{18821}Otèe!
{18825}{18859}Chci, aby jsi il, Gene!
{18871}{18895}Otèe!
{18927}{18950}Hodnì štìstí synu.
{19093}{19170}OTÈE!
{19288}{19316}Díky bohu...
{19369}{19398}U si se probral?
{19404}{19433}Je v tom problém?
{19516}{19578}Ne, jestli dokáeš bıt ticho.
{19584}{19635}Vstoupili jsme do prostoru|Modrého Nebe.
{19807}{19866}Pøístup k síti Modrého Nebe|pøijat.
{19867}{19922}Nyní zobrazuji pouitelné|doky.
{19955}{19993}Pouij dok 8.
{19995}{20047}Dok 8, rozumím.
{20050}{20140}Pøipravuji pøistání na Modré|Nebe pøes trasu 2-2-1.
{20220}{20266}Pøepínám na reim autopilota.
{20270}{20286}Tøi.
{20290}{20303}Dva.
{20309}{20326}Jedna.
{20335}{20374}nyní øídí autopilot.
{20376}{20439}Gene, máš strach z vesmíru?
{20445}{20474}Ne, vùbec ne.
{20475}{20509}Tak co je to?
{20517}{20565}Jen z jisté zlé spomínky, to|je všechno.
{20572}{20607}Spomínky, hm?
{20609}{20696}Hildo, u jsi ve vesmíru dlouho?
{20707}{20782}Dlouho. Moná...
{20786}{20838}Zase jsi taková, znovu uhıbáš|pøed mími otázkami...
{20858}{20906}Hej, zbudil si se, Gene?
{20931}{20963}Rád tì vidím ivého.
{20966}{20993}Padej.
{20995}{21037}Ah, to je ale roztomilé!
{21041}{21078}Ja ti ukáu "roztomilé"!
{21880}{21912}Jsi v poøádku, Gene?
{21938}{21966}Jo.
{22017}{22080}Teï u mi nebude vadit vnitøek|kosmické lodì.
{22084}{22132}Myslím, e tvùj strach se|teï oficiálnì projevil.
{22134}{22216}Sklapni, nebo ti jednu projevím|pøes hubu.
{22221}{22308}Hildo! Jak dlouho to u je?|Mùeš se na chvilku zastavit?
{22311}{22392}Teï ne. Potøebuju, aby|jsi nabral záboby a opravil Horus.
{22396}{22431}Jiste. Jen to nech na mnì.
{22445}{22521}Podívej, Gene! To je Corbonit!|ádného jsem ješte nikdy nevidìl!
{22523}{22546}Ani já.
{22548}{22626}Kdo jsou zaè? Dìláš teï turistickou|prùvodkyni?
{22651}{22698}Øeknìme, e jo.
{22752}{22775}Vlastnì...
{22779}{22840}Po pravdì, mám pro tebe vzkaz, ale...
{22854}{22888}To je okej. Mùeš mi to øíct tady.
{22891}{22934}McCoy vkazuje, e to nemùe|spravit.
{22936}{22952}Proè ne?
{22955}{23048}Nevím to jistì. Vypadalo to,|e si to nechce rozházet u pirátù.
{23051}{23094}Ten sráè.
{23096}{23138}A mám ještì jednu zlou správu.
{23141}{23212}Bratøi MacDougallové se na|tebe ptali.
{23215}{23245}Prokletá dvojka hyjen...
{23248}{23266}Hej!
{23269}{23318}"McCoy" sem, "MacDougall"|tam...
{23319}{23366}Kdy zaènete, lidi, øíkat|nìco smysluplného?!
{23383}{23457}Neple se do rozhovoru dospìlıch,|dítì.
{23463}{23489}Dítì?
{23497}{23519}Coe?
{23523}{23657}Jo,jestli se necháš vším|tak lehko vytoèit, tak dlouho nevydríš, dítì.
{23691}{23791}Pouívat tyto vìci je tu|zakázané. Pamatuj si to, dítì.
{23806}{23891}Klid, není nabitá. Jen sem|blafoval.
{23893}{23973}Take støílet ze zbranì je|ve svobodném mìstì zakázané?
{23979}{24094}Správnì. Kdy by zbloudilá kulka|prorazila stìnu a unikl by vzduch...
{24097}{24165}...kadı, kdo tu ije by to|u mìl za sebou.
{24167}{24260}Hlupáci, co se neumìjí øídit|pravidly nemají právo tady dál ít.
{24265}{24347}A nebo taky, e tu ijí jen|hlupáci, co se øídí pravidly.
{24361}{24399}Take tohlo znamená bıt Outlaws, co?
{24405}{24442}Jsou to piráti?
{24453}{24536}Zdá sa, e ani tento mládenec|neporozumìl.
{24539}{24591}Ve vesmíru existují tøi síly:
{24594}{24650}Vesmírné jednotky, Piráti|a Outlaws.
{24652}{24713}Rozdíl je v tom, co je motivuje.
{24716}{24795}To, co motivuje Outlaw, závisí|na kádém konkrétním èlovìku.
{24798}{24881}Dobro nebo zlo, to nemá vliv|na jejich solidaritu a smysl pro povinnost.
{24885}{24930}Take tohle z nich dìlá Outlaws...
{24933}{25017}Podívej se na tohle, Swanzo!|To nebude práce pro jednoho!
{25019}{25073}K sakru... V poøádku, hned|tam budu!
{25077}{25109}Hildo, tak se teda mìj.
{25112}{25142}Jistì. Dobøe se o òej postarej.
{25148}{25190}Èau, dìcka.
{25244}{25279}Já nejdu.
{25295}{25372}Jak to, e ja musím jít nakupovat šaty?
{25374}{25414}Ona jde s tebou, ne?
{25416}{25506}Musím nìkam jít a Melfina|potøebuje obleèení.
{25510}{25558}Byla by sem radši, kdyby jsi|s ní šel ty.
{25560}{25618}Melfina je dùleité dìvèe.
{25622}{25651}To vím.
{25657}{25776}A co takle teda? Ja pùjdu|s tebou a Jim pùjde s Melfinou?
{25780}{25826}To je domluva.
{25837}{25859}Platí.
{25866}{25895}Platí.
{25915}{25978}Sejdeme se potom v hotelu.|Okej, Jime?
{25980}{26004}Dobøe.
{26064}{26119}Vítejte v Modrém Nebi.
{26340}{26410}Pøistupte, pøistupte! Mám|vynikající masové pirohy!
{26411}{26458}Pøistupte!
{26478}{26505}Promiò, Jime.
{26510}{26545}S tim se netrap.
{26762}{26797}Tak jak?
{26844}{26882}Co myslíš?
{26914}{26955}Vypadá to úasnì!
{26957}{26994}Jo, není to zlé!
{27028}{27054}Díky.
{27211}{27263}Tak poslouchám, co teïka?
{27271}{27333}Tady se setkávají Outlaws.
{27349}{27415}Kdyby sem zjistila, e je tu nìkdo|alespoò trochu dobrı, najala |by jsem ho.
{27417}{27473}Take to není práce, s kterou|by jsi si poradila sama...
{27494}{27582}Moná by si mi mohla øíct,|co je to za práci.
{27663}{27691}Dobrá.
{27733}{27784}Jdu si vyzvednout jistou loï.
{27823}{27854}jistou loï?
{27861}{27900}Velice speciální loï.
{27907}{28025}Grappler loï s dostatkem energie,|aby se dostala do Ether Sargasso.
{28043}{28103}Grappler loï?
{28110}{28226}Jestli plánuješ jít také, zamysli se nad tím.
{28247}{28320}Ale zdá se, jakoby si nemìl rád vesmír.
{28322}{28354}Starej se o svoje vìci.
{28356}{28417}Hej. Ty si Hilda?
{28423}{28486}Slyšel sem, e máš nedostatek lidí.
{28490}{28537}Vypomùeme ti, chceš.
{28544}{28582}McCoy, ty bastarde...
{28587}{28653}Promiò. Hledám jen lidi s urèitımi schopnostmi.
{28655}{28698}Tìch máme plno!
{28703}{28776}Hovoøíme tu o tom, jak vydìlat|trochu penìz, ne? Nebuï taková  lakomá!
{28778}{28818}My, Outlaws, jsme všichni partneøi, pravda?
{28820}{28846}Partneøi?
{28847}{28906}Pøišla si sem, protoe hledáš|partnery,e , Hildo?
{28907}{28969}Pravda, Hildo?
{28987}{29019}Au!
{29114}{29146}Take tak!
{29150}{29194}Chceš si nìco zaèít, idiote?
{29264}{29294}Sleduj tohle.
{29346}{29373}Chceš to schytat, co?
{29375}{29443}Nebudem tì šetrit jen proto, e jsi ena!
{29708}{29750}Dobudoucna nebudu tak hodná.
{29752}{29800}Stáhnìte ocas a uteète.
{29806}{29879}Ksakru, to si zapamatujeme!
{29931}{29988}Chlapi, jako tyhle, jsou také Outlaws?
{29990}{30099}Je to tak jako s hvìzdami:|nìkteré jsou jasné a jiné matné.
{30101}{30145}A ty jsi jaká?
{30148}{30186}Rozhodni sám.
{30191}{30238}Chceš to zjistit?
{30345}{30392}Gene a Hilda mají spoleènı pokoj?!
{30394}{30411}Ano, pane.
{30413}{30460}Sakra, ten podlák...
{30462}{30509}Doufám e si s òí nechce nic zaèít...
{30520}{30577}Jak je moné, e ona s tím souhlasila?
{30578}{30638}Teï, co by dìlal on?
{30639}{30695}Klíè od vašeho pokoje, pane.
{30697}{30721}Našeho pokoje?
{30723}{30795}Ano, pane. Pokoj 345. Dvoulùkovı.
{30863}{30894}No, slyšela jsi...
{30979}{31067}Kruci, Gene... teï není|èas ani místo na takové vìci.
{31099}{31142}Jak to vypadá?
{31146}{31188}Myslím, e ne zle.
{31219}{31270}Dnes v noci budeme spát tady?
{31272}{31290}Jo.
{31291}{31312}Spolu?
{31322}{31377}Uh... V-vezmi si tu postel tamhle! Tamtu postel!
{31379}{31403}Ano.
{32146}{32172}Je prázdná!
{32247}{32295}Chlapi z baru?
{32303}{32364}S tebou se èlovìk ani chvíli nenudí, e?
{32366}{32413}Na nic jiné není ani èas.
{32415}{32441}Buï ve støehu.
{32453}{32522}Co se dìje tam na hoøe? Dostali jste je?
{32533}{32558}Sakra!
{32580}{32629}Jdeme. Nepouívej pistol.
{32912}{32978}Ale, no tak! Ani proti tomuhle|nemùu pouít pistol?
{32979}{33031}Ne. Ani on nemá ádnou.
{33066}{33093}To jako fakt?
{35455}{35502}Stratil sem svùj strach z vesmíru!
{35511}{35576}Teï nemají vesmírní piráti šanci!
{35585}{35640}A nebo to jsem si myslel,|kdy sem si našel trochu èasu...
{35647}{35740}Pøed našimi vesmírnımi hrdiny|se objevuje nová hrozba!
{35749}{35874}Ale, proè to musí bıt zrovna|tito brutální Ctarl-Ctarl?!
{35876}{35913}Situace spìje od zlého k horšímu!
{35934}{36044}Pøíštì v Outlaw Star!|"Do hoøícího vesmíru"
{36046}{36108}Radši se dobøe pøipravte!
