{63}{130}Toto mladé dìvèe vyrostlo na slunci.
{142}{212}Necítila nic, jen potìšení, e má|svoje místo pod sluncem.
{227}{344}Toto dìvèe, narozené v hrdé, vznešené|rodinì, obklopené láskou,
{352}{448}se ctí absolvovalo základní, støední i vysokou|školu.
{471}{579}Poprvé padl stín na její slunkem zalité|místo...
{591}{650}...kdy skládala skoušky na nejvyší akademické|instituci v kraji.
{664}{737}Nepromovat mezi nejlepšími by nebylo nic|hrozného,
{742}{835}ale v její krajinì, kde hodnost hrála velkou|roli, to znamenalo hodnì.
{854}{940}Pùsobištì pro ty, kteøí promovali se ctí,|byl vesmír.
{944}{1027}Byla vyhnaná ze svého místa na slunci.
{1041}{1119}Dùstojník Aisha Clanclan z Impéria Ctarl-Ctarl.
{1125}{1219}U nikdy se jí nevrátí potìšení z místa|na slunci.
{1276}{1346}TAKHLE TO NEMÚE SKONÈIT!

{2757}{2800}|
{2817}{2933}|OUTLAW STAR: Dìvèe-šelma, pøipravená zaútoèit!.
{2950}{3025}|
{3025}{3100}|
{3100}{3175}|
{3175}{3275}|Není urèené pro komerèní pouití.

{3651}{3684}Si tam, Swanzo?
{3686}{3759}Mikey, neøíkal sem ti, aby si mi sem nevolal?
{3761}{3797}Sorry, je to naléhavé.
{3798}{3855}Pamatuješ na ty lidi, co byli pøedtím s Hildou?
{3857}{3900}Oh, máš na mysli ty dìcka?
{3902}{3942}ádají o povolení pøistát.
{3944}{3995}Chtìjí, aby jsme nìco provedli v øídící|místnosti.
{4004}{4074}Coe? Horus by nemìl mít ádné problémy|s pøistáváním.
{4083}{4109}Kde je Hilda?
{4113}{4164}Ta loï není Horus.
{4175}{4242}A nezdá se, e by Hilda byla s nimi.
{4259}{4301}Hilda s nimi není?
{4513}{4573}Nemùu tomu uvìøit... Hilda je mrtvá?
{4575}{4639}Je to tak,vìøte nebo ne.
{4642}{4699}Tahle loï je všechno, co zustalo.
{4708}{4746}Ah, take tak.
{4778}{4833}Tak, synu, co chceš dìlat teï?
{4839}{4913}Nevím. Vùbec nechápu o co tady jde.
{4921}{5037}Hilda, piráti, Galaktickı Leyline, MacDougall...
{5045}{5106}Myslím, e zaènu tím, e se to pokusím zjistit.
{5108}{5145}Jistì. Ale buï opatrnı.
{5147}{5183}Mùu vás poádat o slubu ??
{5185}{5207}Jakou?
{5208}{5300}Tady Outlaw Star nemá registraèní èíslo,
{5303}{5353}take nemùeme vstoupit do legitimních pøístavù.
{5355}{5437}Loï není ještì vybavená. Sakra, vdy nemá|ani nátìr.
{5449}{5519}Chápu o co ti jde. Take, máš nìjaké peníze?
{5523}{5563}Sorry, ale nemám u sebe nic.
{5575}{5619}My nepracujeme jen tak za nic.
{5630}{5668}Co by jsi øekl, kdy zaplatím, a se mi podaøí|nìco velkého?
{5670}{5700}Nìco velkého?
{5710}{5766}Vypadá to snad na nìco?
{5777}{5803}Platí.
{5821}{5858}To myslíš vánì, Swanzo?!
{5860}{5897}Dluím to Hildì.
{5901}{5925}Eeh...
{5931}{5953}Promiòte...
{5955}{5975}Co je?!
{5977}{6029}Chıbí nám i mnoho jinıch vìcí.
{6033}{6079}Mùe sice lítat, ale to je vše.
{6086}{6141}Potøebujeme také zbranì a munici.
{6146}{6242}Registraèní èíslo a nátìr budou mojí splátkou|za to, co dluím Hildì.
{6269}{6374}Bohuel, tady zbranì pro Grappler|loï neseenete.
{6385}{6482}Dál, chlapèe, je u na tobì, aby se ti|podaøilo nìco velkého.Rozumíš?
{6497}{6547}Jasnı. Je tu ještì jedna vìc.
{6549}{6578}Copak to je?!
{6591}{6633}Povìzte mi, co víte.
{6635}{6721}O Hildì a o této lodi. A o pirátech a MacDougallovi.
{6767}{6868}Pøed pìti lety mì Hilda zachránila, kdy|mì napadli piráti Ban.
{6875}{6914}Tenkrát jsme se vidìli po prvé.
{6916}{7001}Vše, co vím o její minulosti jsou jen dohady.
{7006}{7084}To stejné platí i o Galaktickém Leyline, kterı|hledala.
{7086}{7138}Take, vy dva jste spolu vycházeli fajn,|e?
{7141}{7241}Fajn? Bylo to dost horké, pokuï jde o mnì.
{7243}{7297}Pro "Horkı led" Hildu, té.
{7306}{7332}Horkı led?
{7334}{7373}Pøezdívka Hildy.
{7386}{7505}Pøíliš o sobì nemluvila. A u bylo kolem|jakkoliv "horko".
{7509}{7615}Po Hildì pátrali piráti Kei. To je vše,|co vím.
{7619}{7651}A MacDougall?
{7655}{7744}Ten chlap je profík v zahlazování stop.|Nevím o nìm vùbec nic.
{7771}{7865}To mi vyhovuje. Sem loveckı pes, kterı stopuje|podle pachu.
{7868}{7930}Je tu jedna vìc, kterou by si mìl vìdìt.
{7943}{8002}Pohybuje se tu nìjaká ena z Ctarl-Ctarl
{8005}{8094}a snaí se zjistit kam putovali Horus a Hilda.
{8097}{8153}Ctarl-Ctarl?! Urèitì je z té lodì!
{8157}{8214}Ta jejich bojová loï u odletìla.
{8218}{8272}No, radši se pustíme do práce.
{8283}{8348}Zatím se bì porozhlédnout po mìstì.
{8354}{8382}Díky.
{8384}{8411}Za nic.
{8413}{8466}Mimochodem, Gene, jaká je tvoje oblíbená barva?
{8488}{8551}Musíš rozhodnout jakou barvou má bıt trup.
{8565}{8612}- Myslím, e tahle barva.|- Jasnı.
{8614}{8678}Gilliame, sna se zatím slušnì chovat.
{8683}{8721}Tedy dobrá.
{8978}{9021}Hej, vzchop se!
{9023}{9055}Jen jí nechej tak, Jime.
{9078}{9117}Poèkaj, Gene, ja jsem jen--
{9119}{9224}Neví o sobì vùbec nic. Proè by mìla cítit|smutek?
{9226}{9246}Ale...
{9247}{9274}To je v poøádku.
{9286}{9352}Já té cítím smutek.
{9368}{9455}Hilda mì zachránila.
{9474}{9566}Smutek? Take, chceš øíct, e cítíš smutek?
{9567}{9638}Øíká, e se tak cítí, a to staèí, Gene!
{9639}{9673}Si jen rozèílenı.
{9680}{9714}Rozèílenı?
{9989}{10014}Moná e to tak bude.
{10084}{10191}Take, nevzpomínáš si na nic, co se stalo|pøed tím, ne tì Hilda zachránila?
{10193}{10206}Ne.
{10207}{10238}Kruci.
{10249}{10323}No, a jsi na nìco, cokoli vzpomeš,|øekni nám to.
{10325}{10344}Ano.
{10346}{10449}Mimochodem, Gene, u jsi pøekonal tu svojí|vesmírnou fóbii?
{10451}{10480}Nejsem si jistı...
{10490}{10559}Ješte stále se mi nìjak tìko dıchá...
{10579}{10605}Nikdy to nepøekonám!
{10606}{10707}Teda, je zázrak, e si sem dokázal dopilotovat|Outlaw Star.
{10721}{10755}S touhle lodí je to jiné.
{10758}{10844}Jak to jen vysvìtlit...? Nìjak se tam necítím| stísnìnı.
{10846}{10905}To je tím Fyzickım Navigaèním Systémem.
{10961}{11035}Eeh... Tak ty si pamatuješ vìci o té lodi?
{11037}{11129}Já... ani sama nevím proè.
{11203}{11298}No tak, no tak, pojïme si dát nìco dobrého|k jídlu! Mám hlad!
{11301}{11341}Jo, máš pravdu. Jdem!
{11343}{11386}Co by jsi si dala, Melfino?
{11390}{11417}Já se pøispùsobím.
{11419}{11474}Stùjte, kde jste.
{11527}{11588}Èekala jsem, a èekala ... u víc èekat nebudu...
{11597}{11642}Kdo jsi?
{11653}{11694}Kde je Hilda?
{11699}{11740}Znáš Hildu?
{11742}{11786}Já tady kladu otázky.
{11787}{11861}Odpovìz mi. Kde je Hilda?
{11864}{11958}Take další namyšlená sleèinka tu pøedvádí|svùj vıstup?
{11960}{11988}Jak se jmenuješ?
{11990}{12064}Jsem... Aisha Clanclan!
{12076}{12113}Ona je Ctarl-Ctarl!
{12131}{12163}Tak, to sem pøekvapen...
{12164}{12247}Vím u, e pracuješ s Hildou.
{12255}{12303}Povìz mi, kde je Hilda!
{12312}{12418}Podívej, mrzí mì to malé nedorozumìní. Unáhlili|jsme se.
{12421}{12461}Vaše loï nebyla poškozená, ne?
{12474}{12519}Byl to mùj konec!
{12525}{12600}Odpovìz mi... Kde je Hilda?!
{12606}{12634}Je mrtvá.
{12641}{12668}Coe?!
{12676}{12753}No, tvoje otázka je zodpovìzená. Mìj se!
{12759}{12805}S-stùj!
{12850}{12907}Povìz mi souøadnice Galaktického Leyline!
{12909}{12967}Kdy jsi pracoval s Hildou, mìl by jsi to|vìdet!
{12974}{13016}Galaktickı Leyline...?
{13053}{13089}Tak to by jsi chtìla vìdìt...
{13091}{13129}Odpovìz mi!
{13141}{13174}Jistì.
{13184}{13210}Posloucháš?
{13256}{13317}TO BY JSEM I JÁ RÁD VÌDÌL!
{13343}{13396}Krucinál! Pøestaò si dìlat srandu!
{13401}{13443}Fakt! Opravdu nevíme!
{13445}{13503}Take jsi chcete hrát na blbı a do úplného|konce, rozumím...
{13507}{13570}Potom to teda z tebe vytáhnu silou.
{13574}{13655}Hej, pøestaò! Nechci se rvát s dìvèetem!To není mùj styl.
{13659}{13707}-Moná na to nevypadám, ale... -Zbyteèné|øeèi!
{13713}{13749}V tom pøípadì...
{13755}{13781}UTÍKEJME!
{13792}{13831}Zbabìlci!
{13898}{13922}Gene!
{13930}{13952}Ksakru!
{13971}{13992}Pozor!
{14177}{14253}Je to zlé, Gene! Takhle bojují Ctarl-Ctarl!
{14711}{14736}Celkem dobrı.
{14753}{14855}Ctarl-Ctarl, co? Bojujete jen jako prùmìrní|zabijáci!
{14876}{14947}A ty jsi jen tak vybereš a pustíš se do boje|se mnou...
{15058}{15095}Coe já si dìlal jen legraci?
{15104}{15218}Ukáu ti skuteènou hrùzu Ctarl-Ctarl...
{15537}{15578}Co to dìlá?
{15590}{15688}U vím! Ctarl-Ctarl dovedou metamorfovat!
{15690}{15707}Metamorfovat?
{15709}{15765}Zmìní se na nìjaké opravdu zuøivé zvíøe!
{15767}{15807}Komu øíkáš zvíøe?!
{15809}{15904}Jen sleduj sílu, kterou jsem zdìdila po svıch|pøedcích!
{15939}{15975}Je to zlé, Gene...!
{15979}{16090}Tato forma, dokáe znièit obyèejného èlovìka|a je zvìtšiny ovládaná vùlí!
{16096}{16197}Tuto sílu zesilují fáze mìsíce!
{16256}{16309}Modré Nebe nemá mìsíc.
{16371}{16421}Kdy na to tak myslím, nemá...
{16431}{16474}Idiot..Teï! Bìte!
{16491}{16534}Hej! Vrate se!
{16590}{16616}Stùjte!
{16661}{16682}Gene!
{16687}{16720}Vrate se!
{16728}{16770}Jime! jdi koupit nìjaké náboje!
{16774}{16802}Co?Jaké náboje?
{16807}{16840}Náboje do Casteru!
{16842}{16926}Stùjte! Vráte se!
{17054}{17119}Náboje? Pochybuju, e se tady nacházejí nìjaké|náboje...
{17121}{17145}Co mám dìlat...?
{17597}{17643}To bylo tìsné.Zdá se, e jsme se jí stratili.
{17820}{17854}Jsi v poøádku?
{17873}{17920}Támhle je lavièka.Sedneš si tam.
{18193}{18253}Moná to nikdy nepøekonám...
{18462}{18527}Co je? Ještì nikdy jsi nevidìla kvìtiny?
{18529}{18565}Jsou umìlé.
{18589}{18674}Tyto kvìty byly vyrobené. Tak jako já.
{18739}{18816}Proè jsem byla vytvoøena?
{18831}{18889}Kım? Kvùli èemu?
{18921}{18956}Já...
{18994}{19039}Kdo jsema co tady dìlám?
{19319}{19386}Ještì nikdy pøedtím jsem nevidìl androida jako|jsi ty.
{19387}{19480}I kdy se tì dotknu, nedokáu tì odlišit|od èlovìka.
{19495}{19609}Navíc. Cítíš smutek. Trápíš se vlastní|existencí.
{19645}{19739}Hilda by mi mohla dát odpovìï, ale teï|je pryè.
{19886}{19943}A-Au! To bolí!
{19945}{19978}Pøestaò, prosím!
{19997}{20085}Dokáeš bıt pøekvapená. A cítíš bolest.|A stìuješ si. 
{20139}{20230}Vsadím se, e by sem mohl prohledat galaxii|a stejnì by jsem nenašel nikoho jako jsi ty.
{20232}{20300}Neboj.Jednoho dne pro tebe najdem odpovìï.
{20317}{20432}Je to teï moje zodpovìdnost... Hildiny|cíly a ty.
{20434}{20458}Já?
{20463}{20558}Vyøeši nìjakou tu záhadu navíc nic nezmìní.
{20575}{20646}Zjistím to kvùli tobì. Objevím tvojí minulost.
{20672}{20745}Ale po pravdì, nemáme jedinou stopu, po které|se vydat.
{20751}{20858}Zeptat se pirátù by bylo nejrychlejší,|ale to by sem radìji snìdl hovno...
{20869}{20908}Taky jsi myslím. 
{20917}{20958}Radši sníst hovno, coe?
{20963}{21007}Ne! Teda...
{21019}{21042}Ano.
{21089}{21208}Melfino, bude to dlouhá cesta, ale pùjdeš|s námi?
{21245}{21306}Pokud nebudu pøíliš na obtí...
{21312}{21352}Vùbec nebudeš na obtí!
{21359}{21471}Navíc, bez tebe by bylo létání s Outlaw|Star velkım problémem.
{21481}{21508}Ano!
{21525}{21564}Fajn, take dohodnuto!
{21583}{21605}Jime jsi tam?
{21609}{21666}Posloucháš mì, Jime? Kde jsi?
{21671}{21745}Nikde, kde zøejmì nemají ádné náboje.
{21751}{21826}Zdá se, e jsme se jí zbavili. Støetneme|se znovu na tom rohu.
{21831}{21848}Okej.
{21879}{21924}Co je? Co se dìje, Gene?!
{21929}{21978}Buï hodnı chlapeèek a vzdej se.
{21985}{22015}Sakra, ty jsi ale neodbytná!
{22017}{22043}Ticho!
{22081}{22105}Ustup, Mel!
{22753}{22793}Z èeho je ta tvoje kùe?!
{22794}{22845}To bylo jen pùl síly.
{22846}{22929}Myslím, e ti ukáu jak vypadá naše celá|bestiální síla...
{23263}{23349}Asi jsem spálila moc kalorií...
{23691}{23774}Take tì tu zanechali na Modrém Nebi, kvùli|tomu, co se stalo.
{23781}{23879}Mám titul místní zastupitelka!
{23888}{23944}Ale nedostáváš plat, co?
{23947}{23998}Jednoduše nedostávám od impéria ádné peníze.
{24067}{24126}Kdy jsem pouila vlastní peníze aby sem vás|vystopovala,
{24127}{24176}byla jsem zachvilku švorc!
{24188}{24266}Kdy nedáme pozor, sní nám také všechno naše|jídlo.
{24355}{24411}Tohle je vynikající! Ochutnej!
{24413}{24441}Díky.
{24593}{24645}Teda, ty si fakt nenaraná...
{24647}{24700}Z toho by se najedli ètyøi lidi...
{24702}{24734}Um...
{24738}{24764}Co?
{24766}{24822}Chci další!
{24869}{24904}Poslu si...
{24908}{24958}Další! Další!
{24960}{25027}Mimochodem, my nevíme nic.
{25034}{25098}Nemáme ádné informace, které by ti mohli|bıt uiteèné.
{25241}{25282}Je to chutné!
{25284}{25349}Opravdu,e? Já jsi dám také!
{25439}{25499}Jsem plná! U by sem nesnìdla ani kousek!
{25511}{25585}Øíkal sem si, e ti koupím jídlo, protoe sem|se cítil trochu vinnı.
{25591}{25621}Teï jsme si kvit!
{25828}{25866}Co to k sakru dìláš?
{25917}{25992}Blbe! Vy Pozemšané jste tak tupí!
{25996}{26099}Takovımto bídnım odškodnìním jsi nezmírníte|Ctarl-Ctarl!
{26122}{26182}"Zmírnit"? Tak, podívej...
{26186}{26298}Hrdım Ctarl-Ctarl nezáleí na nepøátelovì|soucitu!
{26306}{26407}Myslím, e tvoje myšlení není v poøádku...
{26415}{26443}Ticho!
{26447}{26498}Netvrï mi, e nic nevíte!
{26503}{26583}V ménu Impéria Ctarl-Ctarl vás zatıkám!
{26594}{26638}Jestli se vám na tom nìco nelíbí...
{26641}{26691}Znova se chceš zmìnit na zvíøe?
{26697}{26744}Komu øíkáš zvíøe?!
{26792}{26887}Kdy se transformuju, moje síla staèí, aby|jsem vás roztrhala na kusy!
{26889}{26967}Teï mám energie víc ne dost, aby jsem|vyuila všechnu svojí bestiální sílu!
{26971}{27018}A komu za to mùeš podìkovat?
{27028}{27084}Neoèekávej ádnou vdìènost.
{27088}{27174}Myslíš, e to na nás Ctarl-Ctarl, platí?
{27187}{27264}Teda, tihle Ctarl-Ctarl jsou nìco jiného...
{27269}{27305}Pouij tohle, Gene.
{27316}{27331}Našel jsi nìjakı?
{27333}{27399}Jasnı, èíslo 12. Ten chlap mì oškulbal,|e by si nevìøil, ale kašlu na to.
{27401}{27442}Souhlasím s tím.
{27462}{27494}Vìdìl sem, e to dokáeš, partnere!
{27554}{27671}Snad si nemyslíš, e ta zbraò bude pùsobit|na nesmrtelné Ctarl-Ctarl...
{27691}{27734}Doopravdy?
{27912}{27970}Jo, tak tohle je podle tebe nesmrtelná Ctarl-Ctarl...
{28034}{28097}Èíšníku, dejte vše na její úèet.
{28104}{28170}Povídala, e je tady místní zastupitelkou|Ctarl-Ctarl.
{28182}{28221}Nedovolte, aby se z toho vyvlékla!
{28411}{28451}Úasné!
{28466}{28501}Pìkné!
{28556}{28612}Také jsem získal pro loï registraèní èíslo.
{28622}{28673}Øekl jsem ho palubnímu poèítaèi.
{28678}{28777}Co je s tím starım poèítaèem? Ta prokletá|vìc není nikdy ticho!
{28790}{28848}Vím, co myslíš, ale my s tím nic neudìláme.
{28850}{28895}Je integrovanı do loïi.
{28902}{29016}Promiòte, ale nebyla to nepøímá uráka?
{29018}{29058}Sekej dobrotu, krucinál!
{29060}{29118}Oh, neee. Spùsobuje mi to starosti, ohlednì|mojí budoucnosti...
{29119}{29145}Sklapni!
{29152}{29209}Cením si vaší pomoci, Swanzo, Mikey.
{29218}{29272}Tak, co hodláš dìlat teï?
{29287}{29342}Zatím se vrátíme na Sentinel III.
{29350}{29398}Co potom, to je ve hvìzdách.
{29478}{29571}Teritorium pirátù Kei, kteøí pronásledovali|Hildu,
{29572}{29639}je ve skuteènosti dost nablízku, v Tempa Empire.
{29647}{29733}Oblast v které se nacházíme je v teritoriu|pirátù Ban.
{29741}{29835}Ti Kei zøejmì neudìlají nic drastického,
{29854}{29934}ale dávejte si pozor, kdy vyjdete z Heifongu.
{29937}{29956}Jasnı.
{29958}{30017}Co chceš dìlat na Sentinelu III?
{30022}{30107}Vyuiju konexe, aby sem získal vybavení|a zbranì, které nám chıbìjí.
{30120}{30189}Gene,to snad ne!Ty chceš kontaktovat|jeho?! 
{30191}{30232}Máme snad na vıbìr?
{30236}{30329}Obchodník na Sentinelu III? Mluvíš o?|Fredu Luo?
{30336}{30369}U jste o nìm slyšeli?
{30377}{30458}Mìl sem nìjaké dobré obchody s jeho otcem.
{30467}{30562}Pøijmu jakkoliv horkı obchod s Fredem!
{30564}{30614}No tak, no tak, Gene!
{30616}{30710}Hej, on nepatøí mezi ty zlé. Co ti na|tom nesedí, Jamesi?
{30736}{30810}Díky za pomoc. Moná jí budeme nìkdy opìt|potøebovat.
{30812}{30859}Kdy bude tøeba, ozveme se.
{30860}{30954}A to vyjde! U mám dost tı práce zadarmo.
{30956}{31018}Na, harukuru suna n'n!
{31034}{31069}To je korbonézsky?
{31070}{31133}Oh, promiòte. "Šastnou cestu".
{31143}{31191}Jasnı. Díky.
{31376}{31481}Rídící místnosti, tady Outlaw Star.|Opouštíme pøístav!
{31483}{31577}Máte povolení. Navádìcí signál potvzenı.
{31581}{31667}Pùjdeme podle majákù, dokud neopustíme oblast|Modrého Nebe.
{31695}{31746}Oh Fred Luo..furt tomu nemùu uvìøit.
{31766}{31818}Je doopravdy a tak zlı jak øíkáš ???
{31830}{31915}Ty se nemusíš nièeho bát, Melfino.|Ty jsi dìvèe.
{31922}{31972}Má nejaké problémy s mumi?
{31978}{32025}To bude v poøádku! Všechno bude okej!
{32038}{32085}Nemìj strach ,viï Jime?
{32132}{32186}Zapomeò na to!Nikdy! Nikdy! Nikdy 
{32188}{32242}
{32251}{32323}Pojïme! Outlaw Star, start!
{32522}{32609}Sakra! Jak to, e jedna z hrdıch Ctarl-Ctarl...
{32617}{32698}...je nucená sníit se k takovéhle podøadné|práci?!
{32704}{32802}Za to mi zaplatíš, Pozemšane! Pamatuj|na moje slova!
{32807}{32870}Hej! Pøestaò se flákat!
{32872}{32916}Nespát a do práce, zadarmoerko!
{32918}{32958}A-ano, pane!
{33038}{33096}Tohle jsi zapamatuju!
