{102}{167}Zabíjet. To je povolaní této eny.
{183}{293}Zabíjet. To je spùsob, díky nìmu pøeívá.
{307}{359}Její jméno je Suzuka.
{370}{418}Není nikdo, kdo by znal její minulost.
{427}{482}Není nikdo, kdo by se na její minulost ptal.
{502}{559}Prostøedníctvím zabíjení nachází samu sebe.
{571}{613}Teèou jí slzy, kdy se dívá do vìtru,
{614}{671}a cítí proudìní vesmíru na své kùi.
{682}{742}Tak taková ena je Suzuka.
{758}{875}Není vyjímeènou enou. Všechny eny jsou vyjímeèné.
{893}{962}Všechny eny mají mnoho tváøí.
{975}{1053}Ale ádnı mu ještì nevidìl tváøe, které|má Suzuka.
{1059}{1171}Všichni mui mùou vidìt ahavı meè, kterı|drí v rukou.
{1183}{1319}A i kdy je tìmto muùm, kteøí uvidí její|ahavı meè, dopøán lehkı úsmìv,
{1332}{1386}dokud jsou ještì naivu, tak ho neuvidí.
{1406}{1458}Ta ena se jmenuje Suzuka.
{1474}{1569}Zabíjet. Takové je její povolání.

{2757}{2800}|
{2817}{2933}|OUTLAW STAR: Krásnı zabiják. 
{2950}{3025}|
{3025}{3100}|Ze Slovenskıch titulkù: A-H-Sarvill
{3100}{3175}|
{3175}{3275}|Není urèeno pro komereèní vyuití.

{3815}{3877}Nebuïte blbı! Zaènìte svùj pøistávací manévr|znovu!
{3879}{3960}Nemám palivo! Pøibliuju se!
{4038}{4101}Spomalte! Musíte ještì víc ubrat rychlost!
{4106}{4134}Øiïte se navádìcím signálem!
{4135}{4171}Vdy to dìlám!
{4179}{4261}Dnes vùbec nefouká vítr! O jaké pøistání|se to tam pokoušejí?!
{4265}{4334}Hej, nepilotoval sem vesmírnou loï u šest|let!
{4343}{4448}A otec mì nikdy neuèil jak sestoupit na planetu,|take tohle je moje první pøistávání!
{4454}{4531}Co to øíkáš? O tom si nikdy nic neøekl,|Gene!
{4540}{4598}Teï se mi u podaøí sladit s navádìcím|signálem.
{4603}{4690}Proè se nepostaráš o celı proces, Melfino?
{4696}{4746}Nezvládnu se starat naráz o vše.
{4754}{4801}Je to moje loï! Já to udìlám!
{4807}{4858}Stále se blííme pøíliš rychle!
{4866}{4902}No tak, ty kuse...
{5072}{5097}Tak jak?
{5099}{5134}To nebyl dobrı nápad.
{5171}{5212}Gene!
{5215}{5239}Sakra!
{5261}{5338}100 k povrchu. Vysuò pøistávací podpìry.
{5349}{5376}Jasòaèka!
{5378}{5418}Teï jemnì. Opatrnì.
{5419}{5451}Trhni si!
{5608}{5647}Je zle!
{5676}{5702}Kruci!
{5733}{5788}Prosím vypni motory. Dostanu nás pod kontrolu.
{5799}{5884}Stav tøetí pøistávací nohy - lutı. Za tìchto|podmínek se zlomí.
{5886}{5949}Sklapni! Tato loï není tak køehká a ty|to víš!
{6227}{6362}Vítejte na Sentinelu III, Kosmodromu|West Virginia, Outlaw Star.
{6407}{6447}Zvládl sem to...
{6455}{6529}Co jsi zvládl?! Témìø jsi nás zabil!
{6535}{6638}Pokuï jde o kapitánovu techniku pilotáe,|mám obavy o svojí budoucí existenci...
{6660}{6732}Tak, jak to bude? Odletíte, jen co si doplníte|zásoby
{6734}{6781}a nebo tady chvíli budete parkovat?
{6783}{6831}Odvezte nás do vašeho nejlacinejšího doku.
{6835}{6910}Pøesto e jsme registrovaní na Modrém Nebi, naše|posádka je odtud.
{7228}{7296}Co chceš dìlat, Gene? Vrátit se nazpìt do|firmy?
{7298}{7376}Chci hned zajít do Huga, za Fredem Luo,
{7383}{7427}ale zajímalo by mì, co se stalo s naším|autem?
{7456}{7505}Ještì stále je v tom silu!
{7510}{7543}Kdoví,jestli ho neukradli?
{7555}{7579}To není moné!
{7601}{7668}Kadopádnì, pùjèíme si auto a pojedem|do Huga.
{7673}{7715}Pokud si chvátneme, mùme to stihnout tak za|tøi hodiny.
{7823}{7893}Doufám, e moje Ehefrau je v poøádku...
{7896}{7966}Jistì, Jistì... Jen co si seeneme vìci, pùjdeme|se na nìj podívat.
{7971}{8046}Fajn, ale s tím chlapíkem se fakt necítím|dobøe...
{8056}{8111}Nemluv tak o nìm. Není ani podle mého|vkusu...
{8322}{8404}Oh, ne! Dlouho jsme se nevidìli, Gene!
{8406}{8448}Vypadáš dobøe, Frede.
{8456}{8551}Nikdy nezavoláš! Nikdy nenapíšeš!
{8576}{8635}Jsem šastnı, e jsi se na mì pøišel podívat !
{8637}{8699}Já-já jsem také šastnı.
{8710}{8753}To je Fred Luo?
{8755}{8830}Gene pro nìho jednou pracoval.
{8853}{8881}Jamesi!
{8903}{8971}Zdá se, e rosteš!Obejmi mì rychle.
{8981}{9002}Ano.
{9046}{9110}A-Ahoj, Frede taky tì rád vidím.
{9111}{9168}Tìším se, a tì uvidím za další dva-tøi|roky.
{9170}{9258}Myslím, e za dva-tøi roky budu nìkde velmi,|velmi daleko.
{9273}{9361}Tak za tebou pøídu. Tøeba a na kraj svìta.
{9369}{9406}Kdo je tato mladá dáma?
{9454}{9511}Ráda vás poznávám. Jmenuji se Melfina.
{9515}{9545}Tìší mì.
{9553}{9674}Frede, chtìli by jsme prodiskutovat nìjakı obchod.|Jsem rád, e jsme tì našli tady na Sentinelu.
{9683}{9771}Otec pøesídlil centrálu naší spoleènosti do|Heifongu.
{9784}{9862}Teï, kdy tady šéfuju, chci se soustøedit|na pohranièí.
{9874}{9934}Jestli nerozšíøím obchodní prostor rodiny Luo|dál ne mùj otec,
{9938}{9972}budu jen pro smích.
{9974}{10012}A co Zemì?
{10014}{10097}Obchodníci federace jsou tam dost silní.
{10108}{10167}Take, jakı obchod jsi to øíkal?
{10169}{10212}Jde o mojí vemírnou loï. Potøebuju--
{10244}{10288}To byl jen ert! ert!
{10414}{10497}Myslím, e sem ti povídal, e nemám rád ty|tvoje erty.
{10499}{10562}Jasné, jasné... U ádné erty.
{10569}{10587}Dobrá.
{10589}{10627}Odteï u budu vánı.
{10630}{10672}Ještì víc nemám rád, kdy jsi vánı.
{10703}{10757}Tak, co je s tou vesmírnou lodí?
{10766}{10807}Jedna se mi dostala do rukou.
{10809}{10838}Jo, to je skvelé!
{10842}{10910}U dávno jsi mìl jít do vesmíru!
{10912}{10975}Ale ta loï nemá ádné zbranì ani vybavení.
{10979}{11018}Chci, aby jsi mi nìjaké prodal.
{11019}{11099}Gene, moná jsme pøátelé, ale byznys je|byznys.
{11109}{11190}Máš vùbec ponìtí kolik stojí zbranì a vybavení|pro loï?
{11196}{11265}Jo, ale nejsem jsi jistı ohlednì tohohle.
{11270}{11327}Mám toti Grappler loï.
{11375}{11481}Pravidlem v rodinì Luo je nikdy se zákazníka|neptat "Proè".
{11488}{11566}To znamená, e prodáme zákazníkovi vše,|co chce a na nic se neptáme,
{11574}{11664}ale teï po prvé v ivotì se mi chce |pravidlo porušit.
{11671}{11734}Mìl by si se radìji dret pravidla.
{11748}{11818}U Grappler lodi je to ješte draší...
{11825}{11887}Nemùeme pouít naše legitimní cesty.
{11895}{12002}Mùu ti pomoct s vybavením, ale jak to bude|s placením?
{12004}{12030}Zaplatím ti, jak se mi nìco podaøí!
{12032}{12114}Gene, v rodinì Luo máme ještì další pravidlo:
{12115}{12202}Dùvìru si za peníze koupit nejde, ale také|s ní není moné ani platit.
{12203}{12299}Dùvìøovat ti a vìdìt, e mi zaplatíš jsou|dvì rozdílné vìci.
{12301}{12352}Tohle pravidlo mùeš porušit.
{12354}{12438}Nemùeš dìlat obchod, bez toho, aby jsi nezaplatil|alespoò nìjakou zálohu.
{12440}{12519}Kdy ti napíšu, co chci, mohl by jsi mi|dát alespoò odhad?
{12521}{12540}Dobrá.
{12542}{12622}Ale kdy uvidíš tu sumu, myslím, e si to|rozmyslíš.
{12635}{12701}Pouij vıstavní plochu. Je èas|na mojí další schùzku.
{12708}{12733}Jiste.
{12847}{12871}Hej.
{12887}{13004}Víš, proè jsme to nechali tak, kdy jsi byl|tak nezdvoøilı k mladému pánovi?
{13011}{13069}Protoe by jste si ublíili, kdyby jste se do|mnì pustili?
{13075}{13138}Ne.Protoe mladı pán tì miluje.
{13216}{13252}C-coe?
{13254}{13286}Nechci vìdìt.
{13303}{13362}Fakticky, je ještì lakomìjší, ne jsom si myslel.
{13364}{13416}Jednoduše nevíš jak to ve svìtì chodí,|Gene.
{13502}{13562}Gene, nechtìl jsi dát dohromady ten pøedbìnı|seznam?
{13573}{13600}Jasnı.
{13627}{13732}Vítejte, sleèno. Vidím, e vás doporuèil|pan Oh.
{13763}{13839}Potøebujete velké mnoství vojenskıch pušek,|e?
{13841}{13887}Nechci pušky.
{13907}{13933}Co tedy chcete?
{13940}{14002}Doporuèení od pana Oh je jistì le.
{14363}{14412}To, co chci je váš ivot.
{14513}{14590}Dovolím vám ít ješte pìt minut.
{14595}{14694}V klidu si mùete napsat svoje parte.
{14705}{14797}Avšak, pokud by jste nechtìl pøijmout svou smrt,|zemøete hned teï.
{14801}{14836}P-proè chcete mnì?
{14841}{14939}Kdy vy rozšíøíte svùj trh, u nìkoho jiného|se zase zmenší.
{14953}{15004}Nìkteøí lidé to mùou povaovat za nepøijatelné.
{15007}{15074}Je to Ralph? A nebo Otto? A nebo je to moná...
{15083}{15186}Máte ètyøi minuty. Slunce za chvilku zapadne|za horizont.
{15187}{15247}To je vhodnı èas na smrt.
{15248}{15306}Poèkat... Ty si "Tasogare" Suzuka?!|/Tasogare=soumrak/
{15317}{15438}Kdy to víte, tím víc by jste se mìl snait|vyuít tu trochu èasu navíc.
{15510}{15586}Dìje se nìco? Máte tøi minuty.
{15808}{15827}Frede!
{15944}{15974}Svìtelnı štít, co?
{16111}{16160}Gene! Zachraò mì!
{16167}{16190}Gene!
{16192}{16216}Zalehni!
{16803}{16860}Ja mám té svìtelnı štít!
{17092}{17127}Nebudu tolerovat ádné vyrušovaní.
{17195}{17221}Jen okamik.
{17278}{17361}Jak zajímavé. Chceš mì vyzvat s meèem...?
{17747}{17771}Co je to?
{17809}{17860}Je pøíliš pozdì na to ho zabít!
{18148}{18173}Jsem v poøádku Gene!
{18185}{18298}Frede Luo! Poèkám si na tvùj ivot, do dalšího|západu slunce!
{18305}{18365}Kruci, ta teda ví jak se rychle stratit...
{18379}{18439}Gene! Zachránil jsi mi ivot!
{18443}{18496}Jestli mùeš, chci, aby jsi mì ochraòoval, dokud|tohle všechno neskonèí!
{18499}{18552}Take, chceš, aby sem s ní nìco udìlal,|e?
{18563}{18641}Vezmu ten dob, ale jedinì, pokud udìláš nìco|s tímhle.
{18674}{18726}Jestli to je všechno, je to v pohodì!
{18731}{18754}Coe?
{18763}{18868}Nikdo, koho si vybrala za cíl "Tasogare"|Suzuka ještì nepøeil.
{18874}{18922}Je to špièkoví atentátník.
{18927}{18951}Ach tak...!
{18963}{18991}Co dìláš?
{19001}{19064}Pøidávám trochu raket, které sem si nechal|v záloze.
{19366}{19420}Nejprve se musím vypoøádat s tím ochráncem...
{19903}{19966}Nezdá se, e by to byla porucha senzorù.
{19983}{20058}Senzory nezachytili vùbec nic...
{20060}{20089}Byl to bokuto.
{20111}{20190}Døevìná katana. Nedá se zachytit senzory.
{20199}{20233}Døevìnı meè...?
{20375}{20434}Chceš øíct, e to dokázala s døevìnım|meèem?
{20443}{20496}To je pøesnì to co si myslím.
{20604}{20662}Frede, máš nìjaké patrony do Casteru?
{20667}{20704}Do teï nebyl ádán.
{20708}{20785}Navíc, je to staroitnost. To není náš|styl.
{20788}{20815}Tak, co chceš dìlat?
{20819}{20848}Co tím myslíš?
{20856}{20942}Chceš tady na ní èekat, dokud se neukáe a nebo|nìco podniknout?
{20948}{21003}Povídala, e si poèká do dalšího západu|slunce.
{21005}{21075}Takoví jako ona se vdy drí svıch zásad.
{21078}{21161}Jdou po kadém, kdo se s nimi zaplete.
{21164}{21232}Tak potom máš problém, Gene! Ty si jí zastavil!
{21256}{21278}K sakru.
{21285}{21386}Moment, nechejte mì to promyslet. Moná|existuje vıchodisko.
{21391}{21480}U to mám! Co takhle, najít jejího zamìstnavatele|a zabít ho jako prvního?
{21485}{21587}Za pøedpokladu, e ho najdeme do dalšího|soumraku, co je u za 23 hodin...
{21591}{21623}Tak, nepùjdeme u?
{21628}{21662}Kam?
{21667}{21734}Jsem unavenı. Chci najít hotel a trochu si|odpoèinout.
{21737}{21805}Nemùeš! Musíš zùstat se mnou, Gene!
{21807}{21850}Jestli se potøebuješ ubytovat, mùeš pouít mùj|pokoj!
{21854}{21910}Zùstaò se mnou, kdy budu v posteli i|ve vanì!
{21912}{21945}D-díky, ale u pùjdu!
{21947}{22006}Neboj, ona dodrí svoje slovo.
{22014}{22032}Mìj se!
{22034}{22056}Gene!
{22067}{22110}Ozvu se ti, jen co si najdu hotel!
{22196}{22251}Hej, to chceš vánì bıt jeho ochránce?
{22259}{22295}Mám snad na vıbìr?
{22298}{22371}Outlaw Star potøebuje celı kopec vybavení.
{22375}{22420}Øíká, e mu nemusím zaplatit, kdy se|mi to podaøí--
{22422}{22468}Taková monost u není.
{22540}{22587}Já jsem "Tasogare" Suzuka.
{22589}{22661}ádám, aby jsme náš souboj zaèali znovu.
{22671}{22706}Já jsem Gene Starwind.
{22719}{22799}Ale i tak, souboje nejsou u Outlaws zvykem.
{22810}{22869}Jen co se protivníci pøedstavili, zaèíná se|boj!
{23017}{23051}Coe?To si ze mì dìláš asi srandu.
{23062}{23109}Melfino! Vra se naspìt k Fredovi!
{23119}{23139}A co já?!
{23147}{23174}Kryj mì!
{23176}{23200}Neexistuje!
{23279}{23304}Fajn...
{23513}{23567}Kruci! Moje pistol nestaèí?
{24153}{24186}Úasné! To bylo skvìlé!
{24188}{24230}To byl jeden z tìch trikù, co dokáou mistøi?
{24235}{24279}To byla jen záleitost síly.
{24284}{24359}Proti nìkomu, kdo jen utíká, nejsou tajné|techniky potøebné.
{24379}{24409}Hej, to mì ranilo.
{24431}{24498}Pøestaò utíkat a bojuj se mnou!
{24529}{24546}Gene dovnitø! 
{24557}{24580}Mìj se!
{24633}{24661}Poèkej!
{24690}{24739}Gene! Ona nás sleduje!
{24799}{24880}K sakru, ta je ale vytrvalá... Zdá se, e|se jí budu muset vìnovat.
{24887}{24954}Jime, dokud jsme na cestì, potøebuju, aby jsi|nìco udìlal.
{25287}{25366}U si se koneènì rozhodl, e mi budeš èelit|v boji na smrt?
{25376}{25471}Jestli s tebou nìco neudìlám, nedostanu od|Freda, co chci.
{25481}{25583}Svìtské touhy jsou bláznovství. Budou tì stát|ivot.
{25590}{25681}Kvùli nìkterım touhám se vyplatí riskovat|ivot!
{25711}{25795}Kvùli tomu musím dát svùj ivot do sázky!
{25813}{25849}Co zamıšlíš?
{25853}{25889}Pojï sem dolu!
{25893}{25938}A nebo máš strach?
{25943}{25971}Hlupáku.
{26251}{26275}Štít?
{26280}{26363}Pokud ho soustøedíš do jediného bodu, mùeš|s ním udìlat i nìco takovéhleho...
{26403}{26450}Musíš akorát vìdìt jak na to.
{26470}{26515}To ti nevyjde!
{26795}{26827}Kruci!
{27050}{27074}Poèkej!
{27423}{27450}Mám to!
{27455}{27479}Vra mi to!
{27491}{27514}Které?
{27516}{27539}Oboje!
{27621}{27656}Pøestaò!!Co to dìláš?!
{27674}{27746}Pìkná vùòì z tebe dìlá pìknou enu...
{27755}{27793}Pøestaò blbnout!
{27795}{27888}Pokud chceš ten pás a meè naspìt, nechej|Freda Luo ít.
{27910}{27954}Dokonèím svojí práci!
{27959}{27989}Tak to ti to potom nedám.
{27991}{28055}Pás pùjde do mojí zbírky a meè zlomím.
{28079}{28119}To ti nedovolím!
{28127}{28169}Jako kdyby jsi s tím mohla nìco dìlat!
{28234}{28256}Ty jeden...!
{28258}{28298}Nechci to slyšet!
{28300}{28395}Nechci nic víc ne remízu, tak dohodnìme|dohodu.
{28399}{28430}Remízu?
{28439}{28513}Kdyby sem pouila tajnou techniku u pøedtím,|nemuselo se tohle stát!
{28515}{28594}Pokud nesouhlasíš s remízou, tak potom jsi prohrála,|protoe jsi mì podcenila.
{28600}{28658}Já jsem... prohrála?Nemùu...
{28748}{28798}Pokuï jde jen o boj mezi tebou a mnou.
{28802}{28888}Ale pokuï by jsme bojovali o Fredùv ivot,|nikdy by jsem nemìl šanci.
{28893}{28949}Nemùu zùstat s Fredem a chránit ho po zbytek|svého ivota.
{28951}{29002}Vracím se za chvíli do vesmíru.
{29012}{29080}Øíkáš e  nejsi jeho ochránce?
{29088}{29152}Ne.Vdy u sem ti to povídal. Jsem Outlaw.
{29154}{29174}Outlaw?
{29175}{29196}Pøesnì tak.
{29241}{29330}Dokonèím svojí práci. Budu se snait, dokud|budu ít.
{29331}{29371}Mám svojí hrdost!
{29373}{29406}Tak zemøi.
{29465}{29523}"Tasogare" Suzuka právì zemøela.
{29567}{29613}Zapomeò na svùj kontrakt.
{29616}{29688}Takováhle logika mì nepøesvìdèí,|aby jsem se vzdala!
{29695}{29811}Rozumím ti. Nechej si to jako odplatu|za Fredùv ivot.
{29812}{29898}Poèkej! S takovou dohodou nemùu souhlasit!
{29927}{29995}Proè?Protoe tì zavazuje tvùj kontrakt?
{29997}{30039}Ne, moje hrdost!
{30044}{30122}Fajn. Potom to sem já, kdo urazil tvojí|hrdost.
{30127}{30173}Co s tím, teda udìláme?
{30179}{30237}Jestli tedy chceš zabít Freda, musíš nejprve zabít|mnì.
{30243}{30281}Jo.To je bez debaty.
{30283}{30333}Skvìlé! Jsme teda dohodnutí!
{30337}{30393}Jde o tvojí hrdost, nezapomeò, co jsi øíkala.
{30395}{30425}Co?
{30426}{30450}Ale...
{30453}{30510}Budu jsi dávat pozor za soumraku. Dobrá?
{30526}{30573}Dobrá.
{30581}{30622}Dobøe! Take dohodnuto!
{30654}{30718}Gene!Jsi si jistı, e to byl dobrı nápad takhle|mluvit?
{30723}{30842}Mìl sem snad na vıbìr? Chránit sebe je lehèí|ne chránit Freda.
{30853}{30910}Ok...dobøe. Mì to netrápí!
{31068}{31136}Ten mu... Proè?
{31163}{31254}Mám to teda poslat do doku è. 26 na kosmodromu|v Locuse?
{31256}{31291}Jo. Díky.
{31299}{31378}Vìdìl sem, e s tebou mùu poèítat,kdy mi pùjde o ivot Gene!
{31388}{31468}"Tasogare" Suzuka u po mne nepùjde, e?
{31474}{31528}Jo, ale nejsem si jistı, jestli se to tıká i|toho chlapíka, co si jí najal.
{31530}{31610}S tím si poradím. Dej mi èas a já ho najdu.
{31614}{31667}No, doufám, e se mi od tebe ještì dostane|pomoci.
{31669}{31742}Øeknìme, e jsi mi dlunı za to, e mì chce|Suzuka teï zabít.
{31756}{31828}To, co ti dluím dìlá 750 000 wongov.
{31831}{31858}Coe?
{31863}{31929}Tolik zùstalo, kdy sem odeèetl cenu toho,|co jsi objednal...
{31930}{31989}...od toho, kolik by stálo najmout si Suzuku!
{32006}{32038}Ksakru, Frede!
{32058}{32110}Hej! Myslel sem, e jste øíkali, e mì miluje!
{32116}{32175}Mladı pán vám dal 30% slevu.
{32203}{32242}To je pravda, Gene!SLEVU
{32279}{32394}Tìším se na naše dluhotrvající pøátelství!|Údrba takové lodì je dost nákladná!
{32398}{32463}A navíc pokuï je to Grappler loï!
{32484}{32551}Jo Frede vím ...Prokletí obchodníci...
{32689}{32728}Tak a je to.Vyjednávání skonèilo.
{32730}{32753}Jistì.
{32755}{32825}Myslíš, e jsi pøesvìdèil tu atentátnièku,|aby to vzdala?
{32834}{32890}Nenazval by jsem to pøesnì, e "pøesvìdèil"...
{32895}{32946}Nemohl sem jí zabít! Tak mi to vyèítej!
{33162}{33287}Gene Starwind, tohle není konec...

