{149}{268}Svìt Toward Star, kde se Gene nachází,|je pustı.
{303}{393}Na samém okraji hranic, daleko|od centrálních oblastí,
{395}{434}soupeøí o nadvládu ètyøi velké pirátské skupiny.
{455}{557}A právì jedna z tìchto ètyø hledá|Outlaw Star a Melfinu.
{567}{644}Piráti ze systému Hoppo, zvaní Sto osm Hvìzd,
{654}{758}jsou nejbrutálnìjším èlenem Èínské gildy.
{852}{993}Vede je Tendo a skládají se z deseti|nebo dvanácti-èlennıch skupin.
{1039}{1120}Vùdcové tìchto skupin øídí|nezávislé organizace...
{1124}{1181}...a sledují své vlastní cíle.
{1227}{1353}Šéf pirátù, kteøí teï pronásledují Geneho|si øíká Hazanko.
{1374}{1454}Má mezi Sto osmi Hvìzdami velkı vliv,
{1463}{1535}ale kvùli rozsahu jeho moci, jeho organizace,
{1537}{1600}a úèinnosti metod, které pouívá|na dosáhnutí svıch cílù...
{1610}{1679}...se øíká, e ostatní vùdcové ho povaují|za svého pøedstaveného.
{1710}{1772}Øíká sa té, e oddíly,|které vykonávají jeho rozkazy...
{1775}{1838}...pouívají super sílu zvanou senjutsu,
{1846}{1945}a vdy zlikvidují ty,|kteøí se proti nim postaví.
{2757}{2800}|
{2817}{2933}|OUTLAW STAR: Plíící se zlo. 
{2950}{3025}|
{3025}{3100}|Ze Slovenskıch titulkù: A-H-Sarvill
{3100}{3175}|
{3175}{3275}|Není urèeno pro komereèní vyuití.
{4364}{4398}Pøipravenı, Gilliame?
{4399}{4425}Všechno okej.
{4430}{4454}Fajn...
{4466}{4509}Zapínam všechny senzorové systémy.
{4534}{4568}CFS, aktivované.
{4598}{4642}Radar, aktivovanı.
{4657}{4715}Všechny senzory v normálu.
{4731}{4785}Systém éterového pohonu, aktivovanı.
{4795}{4846}Systém kontroly gravitace, aktivovanı.
{4863}{4919}Systém subéterového pohonu, aktivovanı.
{4943}{5028}Aktivace navigaèního systému potvrzená.|Všechny systémy v poøádku.
{5041}{5094}Jednotka gravitaèního cyklu, aktivovaná.
{5095}{5136}Nejprve jde Newtonùv reaktor.
{5138}{5158}Kruci!
{5179}{5228}Newtonùv reaktor se teï aktivuje.
{5248}{5295}Sub reaktor 1, funguje.
{5307}{5330}Èíslo 2, funguje.
{5347}{5385}Èíslo 3, chyba.
{5387}{5400}Coe?!
{5402}{5429}Vıkon klesá.
{5432}{5450}70.
{5454}{5514}- 50. 30. - Uh... Co mám vlastnì dìlat?
{5516}{5577}Spus u zbylıch reaktorù vyrovnání energie.
{5585}{5611}Tímto, e?
{5613}{5665}Reaktory 2 a 4, vıkon stoupá.
{5671}{5691}120.
{5696}{5716}130.
{5722}{5742}140.
{5748}{5770}160.
{5775}{5794}180.
{5802}{5841}Chystají sa explodovat.
{5856}{5877}Co?!
{5888}{5938}T-mínus-10 do kritického stavu.
{5949}{5966}Devìt.
{5970}{5988}Osm.
{5994}{6011}Sedm.
{6012}{6047}- Šest.|- Hej, Gilliame...!
{6049}{6062}Pìt.
{6069}{6083}Ètyøi.
{6090}{6108}Tøi.
{6115}{6134}Dva.
{6140}{6156}Jedna.
{6400}{6456}Jak vidím, další neúspìšnı vzlet.
{6462}{6503}To ty si to pokazil!
{6505}{6552}pokadé se dostanem do nìjakého mizerného problému!
{6555}{6650}Úèelem simulací je pøíprava na neoèakávané situace.
{6669}{6766}Pokud nejsi schopnı manuálnì zvládnout|takovıto malı problém,
{6771}{6836}zøejmì nebude nìjakı èas monost poèítat s odletem.
{6871}{6895}Sklapni!
{7116}{7190}Nue, loï není ještì kompletnì vybavená,
{7208}{7261}proto myslím, e není tøeba chvátat.
{7436}{7465}Take...
{7471}{7527}Zdá se, e by sem se do toho mìl pustit.
{8092}{8118}Vítej zpìt!
{8123}{8150}Je nìco nového?
{8151}{8180}Ne, vùbec nic.
{8206}{8221}Kde je Jim?
{8223}{8247}Na policejní stanici.
{8261}{8286}Na policejní stanici?
{8292}{8357}Ano. Pravdìpodobnì odtáhli jeho auto.
{8358}{8390}Ehefrau, e?
{8400}{8434}Tak to øíkal.
{8469}{8530}Nìco takového se v Locustì nestává moc èasto.
{8597}{8686}Nelíbí se mi to. Dìje se nìco podezøelého...
{8739}{8790}Gene! Našel sem jí! Našel sem jí!
{8792}{8822}Je v bezpeèí a v poøádku!
{8836}{8933}Ehefrau, u tì nikdy znovu neopustím, opravdu...
{8964}{9002}I tak se mi to nelíbí...
{9104}{9163}Øíkali, e nazbírala pøíliš|parkovacích lístkù.
{9167}{9213}Snail sem se, jak se jen dalo,|aby sem vymyslel nìjakou vımluvu.
{9219}{9285}-Mìl si jim jednoduše povìdìt, e nás napadli piráti.|-Coe! Nikdy by mi neuvìøili.
{9348}{9474}Nevìøil by jsi, na kolik vyšla pokuta a odtáhnutí.
{9767}{9790}Co to bude?
{9791}{9860}Gene!Nevìøím e vy dva ještì ijete?
{9869}{9920}Také tì rád vidím, Clyde.
{9927}{10015}Slyšel sem, e po tobì šli piráti,|tak sem si myslel...
{10017}{10039}Gene!
{10070}{10105}Sem ,díky bohu!
{10117}{10154}Co je, všechno je ok.
{10164}{10207}Tak jsem se o tebe strachovala!
{10212}{10307}Mluvíš tak roztomile... tak sladké.
{10314}{10361}Dej ruku dolu z jejího zadku.
{10378}{10427}Co jsi dìlal? jsou to u dva tıdny!
{10430}{10483}Je to dlouhı pøíbìh, take ti ho nepovím.
{10495}{10518}Jsi tak zlı!
{10547}{10585}A tohle je kdo?
{10602}{10659}Melfina. Nová pøítelkynì.
{10696}{10725}Iris!
{10727}{10756}Ano!
{10875}{10951}Clyde, ptal se na nás nìkdo?
{10961}{10993}Na otázky, na ktré by se nemìl ptát?
{10995}{11103}Byli tu nìjaké po té roztrce tehdá,|ale nic neobvyklého.
{11135}{11167}Vánì se mi to nelíbí.
{11171}{11207}Co tì trápí?
{11213}{11240}To nic.
{11364}{11483}Zdá se to bıt tak dávno, ale nejsou to ještì|ani dva tıdny...
{11510}{11561}Tak, co teï?
{11576}{11647}Zbytek kontejnerù od Freda by mìl pøijít zítra.
{11668}{11734}Musíme dát Outlaw Star do perfektního|pøehlídkového stavu.
{11735}{11774}To by bylo fajn, ale...
{11784}{11807}Co ale?
{11814}{11857}Po pravdì, jsme švorc.
{11860}{11903}Co to øíkáš?! Ale co náš úèet?
{11911}{11954}U jsme ho témìø celı vyèerpali.
{11972}{12020}Poplatky za pouívání kosmodromu jou fakt mastné.
{12030}{12055}Kruci!
{12063}{12120}Za prvé! Vydìlej peníze tìkım spùsobem.
{12127}{12183}Nezùstal by mi èas pracovat na Outlaw Star.
{12193}{12235}Za druhé! vydìlej peníze lehkım spùsobem.
{12242}{12302}Clyde! Nevyskytli se za poslednì nìjaké velké odmìny?
{12307}{12401}Ne, od té doby co jsi sloil "Smrtícího" Roba.
{12426}{12470}za tøetí! vydìlej peníze slizkım spùsobem.
{12471}{12491}Jak?
{12506}{12540}Prodávej svoje tìlo,nebo tak nìjak.
{12542}{12576}-Tvoje by se prodávalo lépe.|-Tøetí monost tedy odpadá.
{12623}{12666}Za ètvrté! Pùjè jsi!
{12676}{12723}-Od koho? -Nevím.
{12725}{12769}Já tu úvìry neposkytuju.
{12905}{12955}Take to bude teda první monost, e?
{12962}{12998}A co s Outlaw Star?
{13007}{13111}To nechám na tobì. Já pro nás zatím seenu|nìco na ivobytí.
{13123}{13154}Já teda nevím...
{13155}{13178}Um...
{13195}{13258}Pokud by jsem mohla nìco udìlat, øekni mi, prosím.
{13285}{13322}Umíš aspoò uvaøit vejce?
{13355}{13453}Já...nejsem si jistá.. nikdy pøedtím jsem nevaøila.
{13469}{13544}-Tak se nauèíš. Melfino, budeš mít slubu v kuchyni.|-Ano.
{13670}{13730}Jo, nic není tak uklidòující jako mìsto,|v kterém jsi si zvykl ít...
{13733}{13778}Jo, jo, také myslím...
{13796}{13873}Ale brzo odejdeme.
{13906}{13933}To je fakt...
{13935}{14037}Kam pùjdeme? Jak daleko pùjdeme...?
{14083}{14177}Je fajn dívat se do nebe, ale podívejme se|kam kráèíme, co?
{14187}{14226}Od zítra to bude tìké.
{14238}{14278}Jo, já vím.
{14965}{15016}Co je? Nemùeš spát?
{15025}{15045}Ne.
{15059}{15171}Myslím, e jsi pøeješ, aby bio-androidi|nemuseli bıt tak lidští, e?
{15177}{15205}Máš pravdu.
{15288}{15357}Eeh, vùbec nièemu tu nerozumím...
{15414}{15472}Dovol mi takhle zùstat, a dokud neusnu.
{15490}{15631}Kdy jsem takhle, mám pocit, e také dokáu snít.
{16053}{16109}Co si myslíš, e dìláš, ty chlípníku?
{16123}{16225}Já, uh... jen jsem si myslel,|e se podívám jak lidská doopravdy je.
{16238}{16285}Jak je lidská?
{16311}{16369}Mel je lidštìjší ne ty.
{16417}{16438}Jime!
{16458}{16512}Je pro mnì jako máma...
{16843}{16962}Kryty motorù nejsou regulérními díly,|tak je prosím, všechny vymìòte.
{16966}{17008}Co takhle trochu pomoct, ha?
{17016}{17090}Kdyby jsme byli v nulové gravitaci, poradil|by sem si s tìkou prací,
{17096}{17179}ale pøi této gravitaci jsem bezmocnı.
{17189}{17231}Tak pracuj na interiéru!
{17234}{17273}Pracuju, samozøejmì.
{17368}{17421}Prosím, skontrolujte si to co nejdøíve.
{17431}{17462}Jasnı, jasnı...
{17471}{17502}Pane Starwind!
{17517}{17537}Co je?
{17542}{17603}Musíme si promluvit. Mùete pøijít do kanceláøe?
{17647}{17677}Vìdìl sem e to musí pøijít...
{17687}{17721}Poèkejte chvíli.
{17767}{17866}Kdy to zaène vøít, snite teplotu. Vaøte,|dokud to není uvaøené.
{18046}{18082}Ta vìc je kaput!
{18124}{18222}Musím tam dát novı motor a nebo skoro všude|vymìnit souèástky.
{18230}{18286}Kdyby jsem mìl tolik penìz,|vzal by jsem to k prodejci.
{18291}{18323}Ano, pane! Rozumím!
{18325}{18431}Tohle je èas, kdy nastupuje firma|Starwind a Hawking!
{18444}{18515}Ve skuteènosti, zrovna takovı motor tady akorát máme.
{18523}{18577}Samozøejmì, budeme si úètovat o mnoho ménì|ne nìjakı prodejce!
{18580}{18647}Vìdìl sem to! Vìdìl sem, e s vámi mùu poèítat!
{18662}{18690}To si pište!
{18742}{18830}Myslím, e sem vás ádal, aby jste zaplatili|všechny parkovací poplatky dopøedu!
{18848}{18933}Pokud se tu chcete chvíli zdret, musíte za|to té zaplatit.
{18942}{18999}Zaplatili jsme vám za další tøi dni, ne?
{19015}{19075}Vidím, e jste nezaplatili za povolení odstartovat.
{19082}{19134}Zaplatíme vám kadı nedoplatek, okej?
{19146}{19188}Jak dlouho se tu zdríte?
{19194}{19248}Já ...nejsem jsi jistı...
{19628}{19685}Upozornìní! Toto není kapitán!
{19723}{19742}Gene!
{19745}{19771}Gilliame! Co je?
{19773}{19796}Je to narušitel!
{19979}{20013}Hej.Vítej zpìt!
{20457}{20498}Gilliame! Kde je narušitel?!
{20512}{20562}Uniká vıtahem è. 2!
{20943}{20966}Gene! Nad tebou!
{21061}{21097}Bastarde! Vra se zpátky!
{21798}{21853}Pøišla jsem navštívit Geneho Starwinda,|a co tu najdu?
{21870}{21951}Velmi zajímavı lidé se ho pokoušejí zabít...
{22035}{22083}Øekni..patøíš mezi piráty Kei?
{22123}{22155}Nemíchej se do toho.
{22170}{22198}Pøesnì to je moje øeè.
{22209}{22293}Gene Starwind je moje koøist.
{22326}{22354}Jdi stranou.
{22368}{22392}A-Ano.
{22411}{22478}Povím to znovu. Nechtìj mì nasrat.
{22500}{22614}V tom pøípadì,to bude skvìlá pøíleitost|udìlat Geneho mím dluníkem.
{22993}{23033}Koneènì jsem se trochu odreagoval.
{23043}{23094}Trochu jsi ubral z ostraitosti.
{23111}{23159}Není to tak, pane Pirát?
{23187}{23223}Kde je Hilda?
{23284}{23362}Nechápeš v jaké si kaši, co, kámo?
{23394}{23422}Vánì?
{23595}{23678}Odpovìz mi. Co je s Hildou?
{23686}{23721}Nic nepovím!
{24474}{24523}Vidím, e jsi mistr senjutsu.
{24543}{24598}I ty máš urèité zajímavé techniky.
{24607}{24645}Jen sem se zahøívala.
{24664}{24742}Nikdo ještì nevidìl víc ne|tøi moje tajné techniky.
{24780}{24833}Soumrak ještì nenastal.
{24849}{24910}Kolik jich uvidíš, døív ne umøeš?
{24926}{24971}Budeš to ty, kdo zemøe.
{26379}{26437}Pojïme na to! Hagan-raggo!
{26848}{26882}Co to bylo?
{26899}{26955}Standartní Hi'en, varianta è. 1.
{27002}{27039}Jistì.
{27154}{27187}U je to v poøádku.
{27199}{27244}Uh. Um...
{27272}{27338}Mùu poèkat na Geneho v jeho obchodì?
{27357}{27378}Jistì.
{27611}{27674}Zdá se, e je mrtvı.
{27711}{27786}Chtìl sem se ho na nìco zeptat, ale zdá se,|e bude pozdì.
{27919}{27945}Co--?
{28512}{28529}Bastarde!
{28636}{28716}Mám pár otázek na které bych se rád zeptal.
{28737}{28793}Budeš hodnej kluk a odpovíš mi?
{28801}{28874}Moja oblíbená barva je èervená.|Moje šastné èíslo je jedna.
{28902}{28941}Kde je Hilda?
{28950}{29017}Proè jste se ty a tvoji pøátelé vrátili|na Sentinel sami?
{29026}{29109}Co sa stalo s mími lidmi? Odpovìz mi!
{29130}{29163}Co za to, kdy ti to povím?
{29193}{29242}Dopøeju ti rychlou smrt.
{29269}{29322}Musíš mi dát lepší pøání.
{29335}{29393}To záleí na tvé odpovìdi.
{29395}{29450}Co to tu mohlo na poli vybouchnout?
{29451}{29506}Nevím! Proto nám øekli,|aby jsme to šli skontrolovat!
{29558}{29576}To byl vıstøel!
{29582}{29602}Támhle!
{29624}{29693}Vezmeme si XGP naspìt! S tím poèítej!
{29755}{29774}Zavolejte posily!
{29777}{29796}Jasnı!
{30187}{30212}Byli tam nìjací svìdkové?
{30214}{30291}Ne, nikdo tu není. Mají strach|se do toho zaplést.
{30298}{30355}Kdyby šlo o piráty, myslím,|e bych øekl to samé.
{30553}{30610}M-Mel! Co se, k sakru, stalo?!
{30646}{30672}Vítej spìt Jime!
{30697}{30790}T-Ty jsi u pøišla? Jsi tu kvùli nìmu?
{30804}{30838}Kde je Gene?
{30851}{30899}Jo, to ti tak povím.
{30903}{30972}Je v tvém nejlepším zájmu se s ním|co nejdøív setkat.
{30984}{31059}Vypadá to, e po vás jdou piráti Kei.
{31064}{31095}P-Piráti?!
{31106}{31169}Neboj,je to v poøádku,Suzuka mì zachránila.
{31187}{31226}P-Proè?
{31251}{31315}Protoe se mi zdáte bıt celkem zajímavı.
{31486}{31523}Gilliame, otvírej!
{31529}{31614}Ah, Jime. Mìli jsme tu trable. Napadli nás piráti.
{31621}{31667}Tady také? Kde je Gene?
{31672}{31716}Uvnitø, pracuje.
{31728}{31766}Kadopádnì, pus nás dolu.
{31769}{31810}Jistìe. Ale...
{31812}{31835}Co jako?
{31858}{31915}A co bude s tou mladou dámou?
{31927}{31991}Není zaregistrovaná jako èlen posádky.
{32100}{32142}Pus jí zatím dolù.
{32361}{32382}Gene!
{32387}{32444}Byli tu piráti, ja vím.
{32446}{32474}Co budeme dìlat?
{32483}{32578}Naloíme všechno vybavení, co pùjde|a odletíme, jen co to pùjde.
{32582}{32671}Vysvìtlil by jsi mi, co se to tu dìje?
{32718}{32822}Kdy budete bojovat s piráty Kei,|nebude mi vadit, kdy vám pomùu.
{32855}{32908}Momentálnì nám nezùstáva nic, jen s nimi bojovat.
{32931}{33014}Avšak neznám pravı dùvod...
{33042}{33084}...proè po nás jdou.
{33095}{33118}Gene?
{33163}{33216}Gene! Co se dìje?
{33227}{33248}Gene!
{33409}{33458}C-Co ksakru?
{33515}{33610}Ošetøil sem si to, ale myslím, e ne poøádnì.
{33689}{33725}GENE!
