{93}{185}"Kdo ví co je tam za tím moøem...?"
{219}{338}Takhle uvaující, mladík|nakonec opustí svùj domov. 
{364}{432}"Co je tam? Co mì tam èeká?" 
{447}{522}Odcházejí, jen proto, aby zjistili.
{538}{616}Leí pøed nimi nespoèetné útrapy.|Zoufalství.
{632}{679}Pokoušejí se kráèet po ostøí noe. 
{687}{780}Nadìje. Radost.|Poznávání novıch pøátel.
{801}{844}Mladí odhazují svojí nevinnost, 
{851}{950}uèí se, trpí a poznávají samy sebe.
{967}{1004}Toto je putovaní. 
{1021}{1138}Kdy dobudou novou krajinu, v jejich oèích|se u odráí další moøe. 
{1167}{1223}"Co je tam za tím moøem...?" 
{1244}{1356}Kdy se z chlapcù stanou mladí mui,|opìt na to zaènou myslet. 
{1385}{1457}Toto je putovaní. 
{2757}{2800}
{2817}{2933}OUTLAW STAR: "Dobrodruné putovaní! Huh?". 
{2950}{3025}
{3025}{3100}Ze Slovenskıch titulkù: A-H-Sarvill
{3100}{3175}
{3175}{3275}Není urèeno pro komereèní vyuití.
{3910}{3986}Tohle je u fakt moc.|Furt trèim na téhle nebezpeèné cestì... 
{3994}{4080}...protoe Gene stále trvá na tom|svém nezodpovìdném chování. 
{4843}{4895}Co dìláš, Gene? 
{4942}{4969}Dobrı, co? 
{4971}{5038}Ohromná sranda. A teï,|nepujdete si odpoèinout?  
{5123}{5166}Moná sem byl námìsíènı... 
{5174}{5212}Sorry, jdu do postele. 
{5214}{5250}Dobrou noc. 
{5310}{5333}Gilliame... 
{5335}{5378}Dìje se nìco? 
{5447}{5483}To nic. 
{5552}{5642}AU! 
{6069}{6092}Jim? 
{6115}{6156}Melfino? Co je? 
{6163}{6202}Um... Nemáme ádnou sùl. 
{6207}{6289}Sùl? Myslím, e sem tu|nìjakou nìkde vidìl... 
{6301}{6344}Mám jí! Tu máš! 
{6399}{6426}Dìkuju. 
{6438}{6519}Jen chvilku vydr a já pøipravím veèeøi.
{6525}{6546}Okej! 
{6709}{6728}Gilliame? 
{6734}{6762}Ano, Jime? 
{6763}{6828}Kde je Gene? Ještì se nevzbudil? 
{6834}{6926}Ne. Pokoušel sem se ho dostat z postele,|ale neúspìšnì. 
{6971}{7008}Sakra... 
{7024}{7062}Gene, vstávej! 
{7074}{7086}Gene! 
{7092}{7111}Gene! 
{7115}{7129}Gene! 
{7132}{7152}Gene! 
{7208}{7261}Gene, vzbuï se. 
{7267}{7280}Gene! 
{7283}{7294}Gene! 
{7298}{7312}Gene! 
{7315}{7330}Gene! 
{7371}{7398}Gene! 
{7407}{7463}Kruci, tak vstaneš u?! 
{7468}{7521}Jak dlouho míníš zùstat v posteli? 
{7593}{7657}Polib mì, Rosie...|Potom vstanu...
{7701}{7737}Pøestaò s tím, ksakru! 
{7742}{7773}Dobøe, dobøe... 
{7775}{7814}Vylez z postele, krucinál! 
{7932}{8042}Pokud tì nikdo nevyene,|proflákaš v posteli celı den! 
{8043}{8074}Tak v èem je problém? 
{8076}{8130}Momentálnì se nemusíme bát,|e by nás nìkdo napadl, 
{8132}{8167}a navíc tu není vùbec nic,|co by bylo tøeba udìlat. 
{8181}{8235}A z toho všeho, co se poslednì událo,|jsem znièenı! 
{8239}{8283}To ostatní také! 
{8289}{8345}Navíc, je tu hromada vìcí,|které je tøeba spravit. 
{8407}{8466}Pøedevším, tahle loï vyaduje údrbu.|
{8470}{8533}Pokud nìco co nejdøív neudìláme,|bude vánı problém s vaøením. 
{8599}{8635}Co, se k sakru, tam dole stalo?! 
{8637}{8703}Nebyl èas všechno zabezpeèit,|ne jsme odstartovali, pamatuješ? 
{8705}{8763}A potom se všechno zamíchalo|kvùli tomu grapplerovému boji, 
{8765}{8812}take chápeš, co se stalo. 
{8814}{8838}Oh, ne... 
{8839}{8908}Také si musíme sednout|a promyslet, co bude dál, 
{8913}{8968}a tak nemáme celı den èas| povalovat se v posteli. 
{8985}{9019}Co bude dál? 
{9025}{9082}Jo. Ohlednì firmy Starwind & Hawking.
{9113}{9147}Co máš na mysli? 
{9333}{9359}Dobré ráno vy dva! 
{9367}{9393}Dobré. 
{9402}{9458}Kadopádnì, Heifong je velká planeta,|take pokud tam pùjdeme, 
{9459}{9551}myslím, e u nebudeme mít|další problémy s piráty Kei. 
{9556}{9624}Ale já si nemyslím, e ta galaxie je tak|skvìlá, fajn... 
{9629}{9696}...a e si najdeme dobrou práci jen proto|e tam pùjdeme. 
{9718}{9751}Voní to dobøe... 
{9752}{9776}Gene! 
{9796}{9839}Vánì z toho máš takové obavy? 
{9841}{9907}Obavy? Ty to nechápeš, Gene?! 
{9934}{9960}Co jako? 
{9962}{9993}To mi ani neøíkej! 
{10003}{10103}Podívej, nikdy jsme na Heifongu nebyli|a nemáme tam ádné konexe! 
{10107}{10165}Jak nezaèneme shromaïovat informace|a nevymyslíme nìjakı plán, 
{10170}{10218}jen samotné splacení našich dluhù|bude naší nejmenší starostí! 
{10221}{10268}V dobì pøistání,|na tom budeme velmi zle s jídlem! 
{10276}{10331}Neboj, to bude v pohodì. 
{10332}{10399}K èemu je dobré se nad tím trápit teï?
{10403}{10492}Tak u si se rozhodl, do kterého mìsta| Heifongu pùjdeme, Gene? 
{10499}{10559}A co udìláme s poplatky za parkování,|hm?! 
{10568}{10636}Vdy jsi takovı!|Nikdy si vìci nepromıšlíš!
{10643}{10690}Vdy necháváš vše náhodì! 
{10694}{10758}Pokud nezaèneme pouívat hlavy|a chovat se chytøe, 
{10761}{10832}nikdy nesplatíme tìch 750 000 wongù!
{10836}{10887}Ah, nechci o tom slyšet... 
{10896}{10969}Akorát si musíme nájít poøádnı dob,|e? 
{10979}{11058}Potom mùme splatit, co dluíme|a po zbytek svého ivota si uívat jako králové! 
{11216}{11285}Um... Prosím, pøestaòte se hádat. 
{11323}{11352}Jaké dìcko... 
{11541}{11604}Nesmíš to nechat tak dlouho vaøit. 
{11606}{11653}Takhle se ti vyvaøí i chu. 
{11657}{11682}Oh. Dìkuji. 
{11793}{11862}Smím se k vám pøipojit na veèeøi? 
{11870}{11902}Ji-Jistì! 
{11919}{11987}Tak. A je tu ještì jeden problém. 
{12064}{12111}Nazvala tì dìckem! 
{12132}{12181}Tak buï teda ticho a jez, dítì!
{12195}{12257}Po pravdì, mìla sem na mysli,|e jsi velmi nedospìlı. 
{12387}{12458}Coe? To jsi hovoøila o mì?! 
{12465}{12512}Tobì to tak nepøipadalo? 
{12514}{12537}Ty jedna...! 
{12538}{12564}Gene? 
{12584}{12674}Já si také myslím,|e se chováš smìšnì.
{12678}{12754}Coe, take tvrdíš,|e to vše je moje chyba? 
{12759}{12787}Ne, to ne-- 
{12805}{12863}Dejte mi pokoj...|U mám dost tìchto hovadin. 
{12869}{12902}Gene? A co tvoje jídlo? 
{12904}{12931}Nechci nic. 
{13099}{13151}Co budeme dìlat s tou dámou? 
{13153}{13212}Vím, e vìci sa tak vyvinuli,|ale nechat jí jít s námi jen tak...? 
{13216}{13280}Co tím myslíš? Nemùeme nic dìlat. 
{13289}{13390}Jdou po nás piráti Kei.|Potøebujeme jí mít tady. 
{13394}{13503}To je sice fakt,|ale nepokusí se tì znovu zabít? 
{13507}{13626}Kdo ví? A i kdyby, na palubì této lodì|se o nic nepokusí. 
{13633}{13664}Podívej, netrap se tím. 
{13666}{13704}To si celı ty, Gene! 
{13714}{13814}Jime, mùj otec mi kdysi dávno øekl|jednu vìc. 
{13833}{13897}"Lidé, kteøí chtìjí hodnì, myslí ve velkém."|
{13899}{14014}"Lidé, kteøí myslí v malém,|vydìlají málo." 
{14015}{14077}"A na tomhle je zaloenı biznis"|øekl. 
{14089}{14127}Take, o co ti jde? 
{14137}{14175}Oh, nic. 
{14177}{14227}Tak, promiò, e myslím v malém. 
{14231}{14292}Mùeš si vyprávìt o dìlání velkıch vìcí,
{14297}{14390}ale já radši zustanu takhle|a vše si nejprve vdy promyslím. 
{14403}{14428}Co si povídal? 
{14430}{14458}Co? 
{14512}{14558}Gilliame, kde jsme? 
{14561}{14634}Za dalších 20 svìtelnıch rokù|vstoupíme do prostoru Kozat. 
{14645}{14748}Podle èasu na Sentinelu, to bude trvat|na Heifong asi tak tøi dny. 
{14774}{14810}Tøi dny, co? 
{14830}{14946}Krucinál, Jime! Uklízej|a nebo jdi prát! Vyber si! 
{15003}{15095}Máme štìstí, e nás zatím|ještì nenapadli piráti. 
{15097}{15196}Vánì? Já by jsem si to pøál.|Nudím se. 
{15204}{15253}Prosím, neøíkejte takové vìci. 
{15263}{15304}Co by se stalo, kdyby pøišli? 
{15308}{15381}Šel by jsem na to a rozmlátil je. 
{15547}{15627}Myslím, e nebudu jíst,|dokud budu mít pøed sebou svoje trenırky... 
{15706}{15802}Gene, co to dìláte? Pøestaòte.|To je moje kolej. 
{15804}{15874}Co mám dìlat?|Nemám je kam povìsit!
{15875}{15950}Nemùete je zavìsit|v nákladním prostoru? 
{15952}{16046}Jim si zabral nákladní prostor|pro sebe. Nepustí mì tam. 
{16050}{16110}Tak si to dìlejte ve své|vlastní kajutì. 
{16118}{16174}Vìšet je na údrbáøskou kolej|rozhodnì nepøipadá v úvahu! 
{16188}{16235}Take to mám spát se svımi|trenkami nad hlavou? 
{16236}{16265}Vdy jsou vaše... 
{16288}{16349}Tyhle vìci musej skoncil.Musim vypadnout. 
{16589}{16656}Ještì stále je naštvanı? 
{16729}{16825}Gilliame, øíkall jsi, e se chystáme|vstoupit do prostoru Kozat, e? 
{16829}{16865}Ano, to je pravda. 
{16875}{16953}Je tam nablízku stanice nazvaná|Toward Stars Inn? 
{16955}{16986}Ano, je. 
{17056}{17085}Skvìlé... 
{17111}{17133}Jime! 
{17207}{17264}Coe, stále ještì se na mì hnìváš? 
{17271}{17299}Co chceš? 
{17301}{17319}No... 
{17507}{17574}Vìdìl sem to. Vìdìl sem,|e budu k smíchu. 
{17592}{17668}Co ksakru znamená ta jiná barva? To sis udìlal ty? 
{17702}{17742}Ne to byl mùj nápad! 
{17751}{17864}ádal sem ho, aby to vrátil|do pùvodní modré, ale neposlouchá mì. 
{17875}{17950}Hej, v èem je problém? Je to pìkné!
{17985}{18021}Konec koncù... 
{18022}{18115}Je jich tu hodnì, take je fajn,|kdy se bude jeden odlišivat, ne? 
{18169}{18240}Oh, jiste. Mìl by jsi to jít ukázat|i Melfinì. 
{18292}{18345}Já tu mám stále ještì hromadu práce. 
{18351}{18416}Promiò, ale a skonèíš,|mohl by si odejít? 
{18429}{18514}No, myslím, e se zastavím na stanici,|aby sem si zaøídil jistou nudnou záleitost.
{18519}{18547}Na stanici? 
{18554}{18646}Hej. Jestli pøídeš na palubu a nebo ne,|je na tobì. 
{18654}{18713}Mimochodem, pøišel sem,|jen aby sem ti to øekl. 
{18720}{18746}Ale proè? 
{18752}{18810}I kdy se stavíme na té stanici,|nemáme peníze! 
{18818}{18862}Co zamıšlíš, Gene? 
{18864}{18913}Hej, tím se netrap. 
{20191}{20237}Gene, co plánuješ? 
{20239}{20306}A budeme odcházet,|také budeme bojovat? 
{20311}{20400}Ne. Nechci si znepøátelit|i tyhle chlapíky z Ban. 
{20403}{20433}Co teda? 
{20439}{20517}Náš problém je, e jsme švorc,|e? Jsme bez penìz. 
{20523}{20569}Neøíkej mi, e si tu hodláš|vydìlat peníze! 
{20571}{20630}Dalo by se to tak øíct.|Heifong je nedaleko, 
{20634}{20693}take potøebujeme nacpat penìenky,|døív ne se tam dostaneme. 
{20702}{20730}Oh, pro lásku b... 
{20735}{20803}Mám tu nìco na práci,|tak se teï vzdálím. 
{20811}{20853}Odchádzíme v 20:00 ,|e? 
{21366}{21442}Nejprv se najíme!|Kdy se nenajíme, nemùeme pracovat! 
{21447}{21518}Neertuju!|Zùstalo nám jen pár drobnıch!
{21523}{21553}Další u nedostaneš. 
{21555}{21618}Tak pøestaò fòukat a zaèni jíst!
{21624}{21663}Sním i to tvoje! 
{21716}{21751}Hej si pomalej! 
{21757}{21789}Jo?!Sleduj... 
{22134}{22157}Um... 
{22176}{22226}Je to vynikající. 
{22263}{22292}Dìkuji. 
{22322}{22387}Jime, v poslední dobì jsi byl|takovı nesvùj, tak sem mìla obavy. 
{22389}{22434}Dobøe se najez, ano? 
{22435}{22485}Huh? To je, uh... 
{22503}{22593}Teda, dìcka se mají!|Všechny enské jsou k nim milé. 
{23081}{23108}Tak? 
{23131}{23187}Co máš v plánu, Gene? 
{23189}{23225}Vysyp to. 
{23231}{23278}Dobøe, tak ti to teda povím. 
{23285}{23370}Doslechl sem se o tom,|kdy sem mluvil s Fredem. 
{23378}{23463}Øíká se, e za mìstem ije|legendární hledanı mu. 
{23465}{23503}Má cenu 10 000 wongù. 
{23505}{23535}Deset tisíc?! 
{23625}{23673}Nemám ádne informace o takovém chlapovi.
{23679}{23712}Nejsou ádné informace! 
{23714}{23767}Ale všichni tady okolo ho znají. 
{23769}{23839}Jsi si jistı, e je to dobrı nápad|zajímat se o toho chlapa, Gene? 
{23842}{23900}"Kdy máš nìco udìlat,|tak a to stojí za to." 
{23902}{23951}To je motto firmy Starwind & Hawking.
{23962}{24046}Ne, to je tvoje motto!|Já s tím nechci mít nic spoleèné. 
{24058}{24103}Hej, to je ono! 
{24115}{24141}Dìlej jak chceš. 
{24143}{24226}Kdy získám tìch 10 000 wongù,|zase si zájdu do dobré restaurace, 
{24229}{24268}ale tobì, Jime, zùstanou jen nìjaké drobáky,
{24271}{24338}take pøedpokládám, e míníš|asi dojídat zbytky a tak. 
{24355}{24413}Poèkat! Kdo øíkal,|e do toho nepùjdu?
{24426}{24495}Oh, vánì? Tak teda jdeš nebo ne?
{24516}{24555}Myslím, e se pøidám. 
{24562}{24610}Poèítám s tebou, partnere! 
{24614}{24656}P-Pøestaò, Gene! 
{24658}{24682}Um... 
{24684}{24754}Je nìco špatnì?Všichni se na nás koukají. 
{24856}{24916}Promiò, Mel, ale mohla|by jsi se vrátit na loï? 
{25071}{25108}Co to bude? 
{25118}{25183}Mám tam nahoøe nìjaké jednání|s muem jménem Zomba. 
{25461}{25494}Jste lovec odmìn? 
{25496}{25524}Nìco takového. 
{25653}{25697}Povìzte mi svoje jmeno a vıšku. 
{25699}{25725}Svojí vıšku? 
{25726}{25783}Budu muset objednat další rakev.
{25786}{25876}Hej, to rád slyším! Ten chlap|asi fakt stojí za tìch 10 000!
{26127}{26188}Jak nezdvoøilé. Co chcete? 
{26199}{26226}Vy jste Zomba? 
{26232}{26259}Ano. 
{26270}{26339}Jsem Gene Starwind,|mu, kterı vás dostane...
{26342}{26389}...a zapíše svoje jméno do legend. 
{26394}{26462}Na náhrobní kamen, chcete øíct? 
{26529}{26598}Vyøešme to venku.|Nechci si ušpinit místnost. 
{26599}{26655}Oèekáváte v noci pøítelkyni? 
{26662}{26744}Nediskutuji s ostatními|o svém soukromém ivotì. 
{26748}{26824}V dnešní dobì to jen víc|pøitahuje pozornost. 
{26833}{26867}Budu si to pamatovat. 
{27403}{27496}Vrána vám u spívá svojí píseò smrti.
{27505}{27595}Mnì to pøipadá, jakoby spívala vám.
{27615}{27687}To zjistíme u za chvilku. 
{27866}{27926}Jak vám to vyhovuje. Do toho. 
{28175}{28196}Jime? 
{28200}{28229}Moment! 
{28238}{28294}Gene, jeho slabım místem jsou záda!
{28295}{28336}Musíš se dostat za òej! 
{28342}{28382}To se lehko poví... 
{28487}{28566}Zdá se, e tá vrána spívala pøece jen mnì... 
{28662}{28702}Jaké sklamání. 
{28723}{28763}Gene! Ještì není po nìm! 
{28869}{28908}Ta píseò byla pro vás. 
{28932}{28954}Myslíš? 
{29024}{29058}Staèí. 
{29090}{29193}Sorry, ale kdy bojuju s kyborgi,|jdu do toho naplno. 
{29203}{29237}Díky, Jime. 
{29248}{29291}To nic! 
{29471}{29534}Dokázali jsme to!|2 000 wongoù! Dva tisíce!
{29536}{29595}Myslím, e to mìlo bıt deset tisíc. 
{29596}{29626}Hej, nedá se nic dìlat. 
{29628}{29731}Byl to falešnı android|a ne samotnı Zomba. 
{29741}{29831}Hej, nemùeme si stìovat.|Dva tisíce je dost! 
{29833}{29856}Také myslím. 
{29858}{29931}A co nejdøív dostanem|i skuteèného Zombu! 
{29935}{29982}Chlap musí dìlat to,|co je tøeba dìlat! 
{29993}{30096}Kdy si chlap, musíš dìlat|poøádné vìci. Je to tak, Jime? 
{30098}{30117}Jak myslíš. 
{30122}{30175}Ale ale, vdy je to Gene. 
{30183}{30211}Ha? Suzuko? 
{30227}{30275}Zdá se, e jsme mìli stejnı nápad. 
{30277}{30338}Hej! Máme 2000 wongù! 
{30394}{30454}Dostali jsme legendárního hledaného mue.
{30462}{30493}Jakého legendárního...? 
{30505}{30618}Hej. Byl fakt tuhı, a bez mé rady
{30619}{30654}by mìl Gene opravdu velké trable. 
{30656}{30708}Hej, o èom to mluvíš? 
{30728}{30787}Tak, kolik jsi vydìlala? 
{30804}{30853}Oh, jen malièkost. 
{31021}{31046}Koukejte! To je ona! 
{31052}{31111}Dostala Zombu?! Fakticky? 
{31118}{31165}Øíká se, e mìl cenu 10 000 wongù!
{31329}{31384}Suzuka dostala skuteèného Zombu...?
{31388}{31473}Vypadá to, e naše šance dokázat|si svojí munost se právì rozplynula. 
{31520}{31568}Vdy sem to øíkal, Gene... 
{31582}{31642}Jestli se sebou neco neudìláme, 
{31647}{31704}firma Starwind & Hawking bude mít problémy.
{31829}{31903}Pro tento jeden jedinı den, 
{31907}{31959}se tu lodì tìch, kteøí zdokonalovali|svoje zruènosti... 
{31963}{32035}...zhromaïují jedna za druhou! 
{32044}{32113}Najde se nìkdo v tomto|13. Heifongském vesmírném závodì, 
{32123}{32256}kdo pøekoná všechny pøekáky|a získá vìnec vítìze?! 
{32286}{32342}Do startu zùstává pìt dní! 
{32493}{32518}Ta loï... 
{32527}{32570}Dìje se nìco, Gene? 
{32577}{32620}Ne, jen sem si pomyslel, e... 
{32626}{32688}Pojïme na Heifong, partnere. 
{32702}{32727}Jasnì! 
{32743}{32770}Vítejte spìt! 
{32778}{32814}Ihned odlétáme. 
{32815}{32840}Dobøe. 
{33172}{33290}Ta loï... To byla MacDougallova loï,|o tom není pochyb. 
