{95}{175}Historie závodìní ve vesmíru je dlouhá. 
{198}{263}Pøed vynalezením Munchausenovo pohonu...
{269}{381}...probíhali závody ve sluneèní soustavì|s vyuitím primitivních lodí. 
{404}{514}Se vznikem FTL lodí se rozsah závodù rozšíøil,
{524}{609}a dnes se od nich odvozené soutìe... 
{611}{650}...odehrávají po celé galaxii. 
{672}{752}Továrny vyvíjející vesmírné lodì riskují|svojí presti a svoje podniky... 
{754}{801}...tím, e utápìjí peníze ve firemních lodích,
{811}{915}zatím co neznámí nezávislí piloti nastupují|s vlastními loïmi, vìøíc v jejich schopnosti.
{932}{1090}Ale a u firemní a nebo nezávislí,|všem pilotùm jde o tu samou vìc. 
{1111}{1184}Sláva a èest pripadající vítìzi... 
{1190}{1251}...je ene vpøed tìmito nebezpeènımi závody. 
{1273}{1335}Slávné závody, kterıch se zúèastòuje mnoho lodí... 
{1343}{1436}...jsou všem známé kvùli obtínosti tratí. 
{1454}{1542}Avšak tomu, kdo pøekoná tyto pøekáky...
{1553}{1638}...tomu pøipadne koneèná sláva. 
{1790}{1869}Semenaide, kesanaide, makenaide... 
{1871}{1990}...daredatte motteru| hazu yuzurenai mono. 
{2002}{2075}Ai dake, yume dake, kimi dake... 
{2079}{2221}...sore dake wa hanasanai,| donna toki demo. 
{2279}{2378}Dou shiyou mo naku,| ochitsukanai yoru... 
{2383}{2493}...nani mo ka mo nagedashitaku naru. 
{2498}{2595}Tsubekobe iwazuni,| sassa to doa wo akena.
{2600}{2707}Rikutsu nante, koneteru hima wa nai. 
{2710}{2913}Juu'ou-mujin tobimawaritai,| you'i-shuutou mamoritakunai! 
{2919}{3098}Nakushita wakeja nai,| mada hajimattenai dakara. 
{3119}{3200}Semenaide, kesanaide, makenaide... 
{3203}{3319}...daredatte motteru| hazu yuzurenai mono.
{3332}{3414}Ai dake, yume dake, kimi dake... 
{3416}{3532}...sore dake wa hanasanai,| donna toki de mo. 
{3564}{3670}Nani ga hoshii? Nani ga| shitai? Doko ni ikitai? 
{3672}{3824}Yami wo saite hashirinukete| tsukamitore through the night! 
{4023}{4095}Tady je Heifong, øídící vì kosmodromu Dailong.
{4099}{4173}Outlaw Star, mám vás na navádìcím majáku.
{4193}{4245}Koneènì jsme se dostali do Heifongu... 
{4247}{4350}Heifong je mìstská planeta,|nebudou pøístavní poplatky pøíliš drahé? 
{4358}{4398}To se vyøeší samo. 
{4763}{4794}To je úasné, Gene! 
{4796}{4848}Nebuï tak vzrušenı...|Je to trapné. 
{4850}{4890}Nemùu si pomoct! 
{5010}{5075}Teda, Heifong je oblast s velkomìsty,|to je fakt! 
{5081}{5102}Hej! 
{5113}{5183}Tak Gene, kam se chceš vydat teï? 
{5198}{5256}Do kanceláøe pro Heifongské vesmírné závody!
{5271}{5303}Vesmírné závody? 
{5307}{5385}Vstoupíme s Outlaw Star do vesmírnıch závodù.
{5500}{5632}Ano, to je pravda. Heifongské vesmírné závody|jsou otevøené pro kadého. 
{5642}{5718}Vstupní poplatek mùe zaplati buï firma|,nebo jednotlivec 
{5723}{5765}a ani tøída lodì není dùleitá. 
{5775}{5838}Ještì stále je moné registrovat se. 
{5839}{5918}Je tu ješte jedna vìc, kterou by jsem rád vìdìl.
{5936}{6006}Rád by jsem vidìl údaje|o ostatních lodích v závodì. 
{6007}{6093}Podle pravidel, nemùete|proskoumat ostatní lodì. 
{6095}{6146}Zajímám se jen o jednu loï. 
{6158}{6197}To by nebylo fér. 
{6203}{6236}Jste si jistá, e nemùete? 
{6238}{6260}Ano. 
{6307}{6404}Nu, v tom pøípadì, je tu další vìc,|kterou by jsem rád vìdìl. 
{6411}{6442}Co to je? 
{6443}{6482}Vaše telefoní èíslo. 
{6491}{6578}Jsem si jistá, e u znáte èíslo|do této kanceláøe. 
{6587}{6635}Nu, kdy to berete takhle... 
{6637}{6702}Take, jen co bude po závodech,|zavolám do kanceláøe. 
{6709}{6797}Povíte nám teï, co je tøeba udìlat,|aby jsme mohli letìt ve Vesmírnıch závodech?
{6801}{6873}Staèí vyplnit potøebné údaje na tìchto formuláøích.
{6877}{6974}Náš personál vykoná jednoduchou kontrolu na|palubì pøed zaèátkem. 
{6987}{7010}To je vše? 
{7012}{7073}Ano. Takté potøebujete vloit 150 000 wongù...
{7076}{7151}...na urèenı úèet jako vstupní poplatek. 
{7201}{7234}Promie,kolik e ste øíkala? 
{7235}{7322}150 000 wongù. Obsahuje i pojištìní. 
{7328}{7372}"Otevøené pro všechny", co?! 
{7376}{7440}I kdy vyhraju závody, nedostanu spìt|ani jedinı wong ,e?! 
{7442}{7497}ádnı soukromı pilot nemá takové peníze!
{7503}{7557}Za to by se dalo koupit deset slušnıch aut!
{7559}{7650}Proto si takoví lidé hladají sponzora. 
{7663}{7690}Sponzora? 
{7691}{7795}Ano. Na Heifongské vesmírné závody nahlíí...
{7797}{7882}...mnoho firem jako na vysoce úèinou reklamu.
{7891}{7913}Avšak... 
{7914}{7941}Co? 
{7943}{8062}Pro nového úèastníka mùe bıt tìké|najít si sponzora. 
{8068}{8105}Dìkuji pìknì! 
{8107}{8195}Jen se dívejte!|Nastoupíme do závodù a vyhrajeme je! 
{8227}{8274}Tøebae nevím jak... 
{8539}{8577}Nechej to tak, Gene. 
{8583}{8656}Nikdy se nám nepodarí dát dohromady 150 000,|i kdy budeme dìlat cokoli. 
{8679}{8742}Poletíme ve vesmírnıch závodech.|Jsou proto dva dùvody: 
{8744}{8852}Za prvé, prodat naše jména. Protoe jak ne,|velké kšefty se nám nepohrnou. 
{8854}{8911}Myslíš, vyuít to jako firemní reklamu? 
{8913}{8972}No,pokud nám závody nevynesou ádné peníze...
{8978}{9057}Za druhé, MacDougall. Zdá se,|e jeho loï bude na závodech. 
{9062}{9145}Vánì? Myslíš toho MacDougala? 
{9159}{9261}Nemám ádnı konkrétní dùkaz,|ale vidìl jsem loï, která vypadala jako jeho... 
{9263}{9317}...ve správách, kdy ukazovali lodì,|které budou na závodech. 
{9320}{9362}Ale to nic neznamená! 
{9376}{9423}Nikdy nezapomenu na tu loï. 
{9430}{9480}Chci vstoupit do závodù, aby jsem se ujistil.
{9494}{9571}Tak, teï vím proè,|ale co bude jako s tím? 
{9579}{9604}Pùjèit si? 
{9667}{9753}Øídím se zásadou,|"Nepùjèuj sobì ani nikomu jinému". 
{9810}{9874}Jsou to tøi wongy, e?|Platím svùj podíl. 
{9899}{9935}Hej, kam jdeš? 
{9952}{10075}Nezajímají mì vesmírné závody,|a není tu nic, s èím by jsem mohla pomoct, e?
{10087}{10164}Nebojte,a závody skonèí, ohlásím se vám. 
{10173}{10200}Nezlob se! 
{10222}{10255}Urèitì? 
{10273}{10307}Je to její rozhodnutí. 
{10309}{10350}Tak, co budeme dìlat? 
{10351}{10397}Myslím, e budeme muset jít za naším pøítelem. 
{10403}{10441}Ha? Ouu... 
{10442}{10512}Sídlo Luo Company. 
{10563}{10628}Ale, ale! Gene a Jim! 
{10636}{10706}Musel to bıt osud,|kterı nás znovu svedl dohromady! 
{10720}{10779}Jsem pøekvapenı, e jsi pøišel na Heifong.
{10791}{10865}Myslel jsem, e provozování|poboèek nechávaš na jinıch. 
{10869}{10956}Opravdu by jsem mìl podìkovat bohu obchodu.
{11052}{11164}Jsme tu kvùli biznisu, Frede. Je to tak,|jak jsem vysvìtloval do telefonu. 
{11167}{11246}Jistì, rád tì budu sponzorovat. 
{11253}{11270}Opravdu?! 
{11271}{11319}Je to dobrá reklama, i pro nás. 
{11326}{11395}Jak vyhraješ peníze,|vyøešíme všechny tvé vıdaje. 
{11405}{11495}"Vyhrát peníze"?|To kdy skonèím mezi prvními tøemi, e? 
{11500}{11598}Vìru. Jak skonèíš ètvrtı a nebo ní,|budeš mi dluit ještì víc. 
{11607}{11653}Vidíš? Co jsem ti øíkal, Gene? 
{11656}{11686}To je v pohodì, Jime. 
{11700}{11747}Fajn, jsme dohodnutí. 
{11752}{11825}S osobními vıdaji to vyjde|na 400 000 wongù, tak je mìj pøipravené. 
{11833}{11893}Jsem pøipravenı u dávno. 
{12051}{12081}Co je to? 
{12165}{12274}Kdy budete na stupni vítìzù chci,|aby jste mìli oba obleèené tohle. 
{12285}{12392}Jak to lidé uvidí na stupni vítìzù,|tìch 400 000 bude jak zadarmo. 
{12401}{12438}Vidíš? Co jsem ti øíkal, Gene? 
{12443}{12487}Máme snad na vıbìr? 
{12497}{12557}Melfina si nemusí obléct nic? 
{12566}{12692}Gene, nemyslím, e by jsi jí mìl|pøedvádìt na veøejnosti. 
{12723}{12778}Co tím chceš øíct, Frede? 
{12786}{12821}Nic moc. 
{12829}{12964}Akorát, e piráti Kei hledají tebe a obzvláš jí. 
{12973}{13036}Pokoušíš se nás zaprodat? 
{13039}{13069}Kdee. 
{13076}{13158}Pokraèovat s tebou v obchodì je mnohem vınosnìjší.
{13176}{13215}Nesklameme tì. 
{13226}{13266}Poèítám s vámi. 
{13275}{13357}Mìj se, Frede. Uij si sledování závodù.
{13366}{13407}Kdy to vlastnì zaèíná? 
{13418}{13452}Za 30 hodín. 
{13462}{13500}No, máme toho hodnì na práci. 
{13650}{13710}Nepokate to. Poèítám s vámi. 
{13720}{13822}Hej, nikdy by jsem nepomyslel,|e mì budete povzbuzovat. 
{13832}{13895}Myslel jsem, oplatit lásku mladého pána k vám. 
{13903}{13933}Oh, tak... 
{13966}{14020}Outlaw Star, tady øídící vì. 
{14029}{14079}Negativní návrat je potvrzen. 
{14101}{14184}Tady Outlaw Star. Negativní návrat potvrzen.
{14194}{14265}Takhle by opravdu mìli vypadat planetární starty.
{14269}{14329}Rozvinuté mìsta jsou úasné. 
{14333}{14421}Moná, tøeba e parkovné stálo hodnì|a to jsme tam byli jen pùl dne! 
{14427}{14470}Bez penìz nemùeš dìlat nic. 
{14476}{14549}Ale jak se k nìjakım dostaneš,|tak mùeš témìø vše. 
{14555}{14587}Takovı je Heifong. 
{14592}{14662}Nyní zobrazuji trasu k|urèené startovní pozici. 
{14679}{14698}Jasné. 
{14703}{14752}"Startovní pozice?" 
{14764}{14835}Gilliame, máš podrobné mapy okolí Heifongu?
{14837}{14931}Moja knihovna se vyrovná té,|na køíníku Vesmírnıch jednotek. 
{14942}{14971}Tak je pøiprav. 
{14975}{15015}Zanedlouho je budeme potøebovat na závodech.
{15023}{15061}Coe? Jaké závody? 
{15063}{15180}A ještì stále jste nevysvìtlili,|proè s vámi není Suzuka. 
{15202}{15254}Vysvìtlím pozdìji. 
{15483}{15527}Nevidím jeho loï. 
{15535}{15573}Rozeznáš to odtuï? 
{15580}{15612}Vìø mi,kdyby tu byl, vìdìl by jsem to. 
{15614}{15645}Kdyby, heh...? 
{15746}{15829}Oh, dobøe.|Chceš se podívat na pøedzávodní párty? 
{15831}{15851}Uhm. 
{15903}{15965}Mel jsme nechali na lodi, ale jsi si jistı,|e je to v poøádku? 
{15968}{16012}Mám obavy z toho, co povídal Fred 
{16017}{16081}a ona øíkala, e tam chce zùstat,|take myslím, e je to okej. 
{16088}{16173}Tak jí pøinesem nìjaké jídlo z párty jako suvenır. 
{16249}{16368}Gilliame, mùeš mi spøístupnit|nejvìtší databanku na Heifongu? 
{16384}{16469}To bude pravdìpodobnì Dailongská Univerzita.
{16472}{16509}Okamik, prosím. 
{16523}{16593}Na co by jste se rádi podívali? 
{16597}{16631}Na sebe. 
{16635}{16694}Na vás? Co tím myslíte? 
{16706}{16830}Nìjakou stopu. Kdo jsem?|Proè jsem byla vytvoøena?
{16844}{16879}Chci to vìdìt. 
{16909}{17080}Pøemıšlet o sobì mi není dovoleno,|ale dokáu pochopit jak se cítíte. 
{17093}{17161}Udìlám vše, co je v mıch silách. 
{17194}{17219}Dìkuji. 
{17221}{17314}Heifongské vesmírné závody právì vstoupili|do svého tøináctého roèníku... 
{17319}{17413}a stali se skuteènì populární,|s doteï nejvìtší úèastí, 
{17417}{17562}stávající se z 13 firemních lodí|a 29 soukromıch lodí soutìících o vítìzství. 
{17575}{17637}Kdoví, jestli tady je? 
{17650}{17742}Celkovì se 40 lodí zúèastòuje|èistì jen kvùli slávì... 
{17748}{17851}...v tomto vyèerpávajícím, nebezpeèném závodì,|co je doopravdy-- 
{17855}{17929}Hledat ho k nièemu nevede. Nevíš jak vypadá.
{17938}{17967}Jistì, ale... 
{17969}{18075}Podívej, zaplatili jsme velké prachy, aby jsme|mohli závodit, tak a to stojí za to. 
{18079}{18139}Dej si! Tohle je fakt dobré! 
{18142}{18166}Aah... 
{18269}{18316}Dali by jste si nejakı nápoj, pane? 
{18376}{18450}Hej, zlato. Mùu té dostat drink? 
{18455}{18475}Ano! 
{18481}{18519}Mám ízeò, obzvláš-- 
{18714}{18736}Èau. 
{18789}{18845}Našla jsem tì, Gene Starwinde! 
{19166}{19183}Èau. 
{19223}{19298}Našla jsem tì! Našla jsem tì! Koneènì našla!
{19323}{19354}Ok . Co tu dìláš? 
{19359}{19431}Tohle bylo boí vnuknutí Boha Ctarlù...! 
{19440}{19498}Díky ti, Boe všech Ctarl! 
{19534}{19632}I bez penìz z Impéria jsem byla|rozhodnutá tì vystopovat, 
{19635}{19702}a tak jsem jezdila stopem celım vesmírem.
{19711}{19773}To jsi celou cestu sem jela stopem?! 
{19779}{19866}Bylo to tìké... Šla jsem tam,|kam mìli lodì namíøeno, 
{19870}{19938}a na palubì mì oèekávala tvrdá práce. 
{19946}{20010}Šla jsem dál a dál,|a jsem skonèila tady, na Heifongu, 
{20012}{20115}vdìèná, e jsem dostala|tuhle práci servírky, abych mìla aspoò na jídlo. 
{20121}{20182}A právì kdy lamentuji nad svım neštìstím,
{20243}{20335}kdo jinı se pøede mnou objeví, ne vy dva?!
{20344}{20390}Teda, nemùu uvìøit našemu štìstí... 
{20399}{20431}Je to smìšné. 
{20437}{20513}Pøestaòte vanit! Teï buïte hodní hoši a--
{20515}{20547}Ovládejte se, Aisho! 
{20672}{20710}Oh! Uh, šéfe.. 
{20712}{20785}Um... Tihle dva bastardi, chci|øíci páni--
{20791}{20834}Vaši omluvu si poslechnu pozdìji.
{20863}{20938}Pøestaòte! Puste mì! 
{20945}{21015}Pokud udìláte ješte další scény,|nedostanete zaplaceno! 
{21087}{21127}Velmi mì to mrzí, páni. 
{21143}{21187}To je v poøádku, nic se nestalo. 
{21224}{21323}Nebylo dost údajù, aby se dalo pokraèovat.
{21371}{21428}Jistì. Rozumím. 
{21431}{21518}Mohli by jsme se pokusit provìøit piráty|prostøedníctvím Vesmírnıch jednotek, 
{21527}{21582}ale mohlo by to bıt obtíné. 
{21595}{21646}Netrap se, Gilliame. 
{21647}{21733}Neèekala jsem, e se dozvím vše hned najednou.
{21743}{21845}Ano. Jsem si jistı, e se|nakonec dostaneme na správnou stopu. 
{21853}{21930}Jistìe. Gene mi to té slíbyl. 
{21936}{22055}Slíbyl vám to? Ah, kdy u o nìm hovoøíme,|právì se vrátili. 
{22079}{22101}U jsme tady! 
{22102}{22148}Tady máš, Mel, pøinesli jsme ti nìco! 
{22161}{22184}Pro mnì? 
{22186}{22205}Uhm! 
{22210}{22278}Tak, potøebujeme zásobit loï,|udìlat údrbu a trochu si odpoèinout. 
{22279}{22342}Je dvanáct hodin do startu. Dejme se do práce.
{22353}{22374}Ano! 
{22378}{22401}"Start?" 
{22431}{22587}Start 13. Heifongskıch vesmírnıch závodù|je témìø tady! 
{22599}{22677}Zúèastnìné lodì se jedna za druhou|shromaïují na startovní pozici! 
{22685}{22779}Kterı tım získá vìnec vítìzství? 
{22808}{22923}Vyráíme odtud, z Heifongu IV|a nejprve zamíøíme k 3. planetì, Heifongu III. 
{22939}{22980}Øíkáš e je to dvojitá planeta! 
{22997}{23067}Fakt vybrali nepøíjemné místo|pro kontrolní bod... 
{23074}{23118}Dál je to ještì horší. 
{23127}{23201}A potom obìná dráha okolo 5. planety,|tohoto oblaku plynu. 
{23205}{23262}A potom projít tímto pásem asteroidù. 
{23268}{23354}Uvádí, e je moné vyuít|kontrolní bod na 2. a nebo 1. planetì. 
{23360}{23413}Cesta k druhé planetì je delší, 
{23419}{23482}ale cesta k prvé planetì je o trochu nebezpeènìjší.
{23494}{23554}A potom se vracíme spìt na Heifong, e?
{23563}{23623}Je to vılet asi na 1,6 miliardy kilometrù.
{23632}{23696}Kdy u jsme na tìch závodech,|mùeme je vyhrát, Gene! 
{23706}{23750}Jaké nadšení! 
{23757}{23870}ádná loï se nevyrovná Outlaw Star. 
{23873}{23948}Okej, ukáem jim, co Outlaw dokáe! 
{23966}{24028}Doenem tì, MacDougalle! 
{24034}{24055}Gene! 
{24063}{24131}Pamatuj si jen, e jak neskonèíme mezi|prvními tøemi, všechno je to nanic. 
{24139}{24165}Vím to. 
{24171}{24201}Kdy øíkáš. 
{24215}{24276}Ale jak skonèíme mezi prvními tøemi,|máme 400 000 wongù, 
{24278}{24358}a kdy odeèteme vstupní poplatek a ostatní,|zùstává 200 000! 
{24399}{24458}Lodì budou startovat jedna za|druhou v dvouminutovıch intervalech. 
{24462}{24538}První loï se teï pøibliuje|k startovní bránì! 
{24546}{24616}Je to soukromník, veterán,|kterı soutìil v posledních šesti závodech. 
{24618}{24685}Je to Blue Continental,|pilotuje ji Ernest Blue! 
{24699}{24785}Všechny systémy v poøádku,|vıkon motorù je stabilní. 
{24800}{24873}Jsme a 26. Chvíli to potrvá. 
{24887}{24952}Loï èíslo 7 je trochu neobvyklá. 
{24959}{25056}Pan Nubata Kunono, obchodující zde,|na Heifongu, pozdravuje od Ctarl-Ctarl. 
{25067}{25111}Jeho loï je Niburu-Boribori. 
{25127}{25178}Povídal, e to je loï Ctarl-Ctarl! 
{25179}{25204}Eh? 
{25220}{25342}Uhm, dùstojnièko Aisho...|Mùeme absolvovat |tyto vesmírné závody normálnì? 
{25347}{25403}Dokud vám nedám rozkaz,|mùete si dìlat, co chcete. 
{25413}{25486}Ale povaujte moje rozkazy za rozkazy z Impéria.
{25491}{25510}Ano! 
{25550}{25606}Co, k sakru, dìlá imperiální vyslankynì|tady na Heifongu? 
{25611}{25695}Nemáme na vıbìr... Musíme poslechnout Impérium!
{25706}{25762}Jen se dívejte! 
{25783}{25829}Tak teda odstartujeme. 
{25839}{25951}Newtonùv reaktor a jednotka|gravitaèního cyklu se zapínají. 
{25961}{26026}Oh, zdá se, e to stihl právì vèas! 
{26033}{26132}El Dorado, která prišla pozdìji,|to stihla do startovního èasu! 
{26183}{26280}El Dorado, která se minulı rok umístila|jako pátá, je tento rok favoritem! 
{26284}{26327}Jeji kapitán je Harry William! 
{26346}{26412}"William?" To není MacDougall? 
{26471}{26576}Promiòte, cestou sem mì zastihla|éterová bouøka. 
{26590}{26669}El Dorado má urèenı èas startu za sedum minut.
{26676}{26702}Zvládnete to? 
{26703}{26722}Jistì. 
{26726}{26759}Tedy,hodnì štìstí. 
{26923}{27035}Harry, pøichází sem vysílání.|Øíká, e je na Outlaw Star. 
{27043}{27126}Neznám takovou loï. Ignoruj to.|U je témìø èas vystartovat. 
{27131}{27169}Sakra, on neodpovídá! 
{27175}{27242}Outlaw Star, otevøenı kanál|na startovní pozici... 
{27244}{27292}...je jen pro sluební úèely.|Prosím, respektujte to. 
{27298}{27376}Take, El Dorado míøí k startovní bránì!
{27393}{27453}Spus motory! Chci se dostat k té lodi!
{27458}{27510}Poøadatelé nás urèitì zastaví. 
{27514}{27615}Gene, nedìlej ádné hlouposti.|Není jisté, jestli je to ta loï. 
{27662}{27690}Jo, myslím, e máš pravdu. 
{27710}{27787}Je to dlouhı závod. Urèitì dostanem šanci,|aby sem se ubezpeèil. 
{27820}{27867}El Dorado, je èas vystartovat. 
{27893}{27941}Vpøed! A jdi naplno. 
{28161}{28232}Za Bonapartem, sponzorovanım|Penelope Corporation... 
{28238}{28305}...je Outlaw Star, soukromník,|soutìící po prvé. 
{28307}{28358}Kapitánem je Gene Starwind. 
{28462}{28518}Dvacet tisíc na Outlaw Star. 
{28700}{28739}Poèkat, ta loï... 
{28741}{28799}Dìje se nìco, profesore Khane? 
{28814}{28882}Ne, ne. Vùbec nic. 
{28887}{28922}To je v poøádku. 
{29013}{29122}Není pochyb, ta loï je XGP15A-2... 
{29138}{29180}Ale co dìlá tady? 
{29223}{29275}Toto je poslední kontrola.|Jste pøipraveni?
{29286}{29319}Vše v poøádku. 
{29370}{29446}Take, Outlaw Star,|je èas vystartovat. 
{29502}{29527}Start! 
{29809}{29875}Na Heifong III je to|230 miliónù kilometrù.
{29882}{29944}ETA je pøiblinì 1000 hodin, 
{29951}{30014}Prosím, pøenechejte ovládání|autopilota na mnì. 
{30019}{30074}Všechny pomalé lodì zanechej v prachu! 
{30080}{30110}Samozøejmì! 
{30212}{30258}Ubìhlo 14 hodin od zaèátku závodu... 
{30260}{30331}...a první lodì u dosáhli|prvního kontrolního bodu. 
{30340}{30385}Bonaparte je momentálnì ve vedení, 
{30386}{30449}a právì procházejí kontrolním bodem|jedna za druhou! 
{30463}{30507}Co zdrelo Genea? 
{30517}{30583}Vystartovali konec koncù uprostøed|skupiny. 
{30657}{30726}Pøispùsobím obìnou rychlost Heifongu III.
{30737}{30771}Teda, to je úasné! 
{30775}{30812}Kontrolní bod je... 
{30889}{30929}Uvádí se, e je pøímo uprostøed! 
{30942}{31020}Zaznamenal jsem další lodì zrychlující|nad rovinou otáèení. 
{31034}{31097}Zdá se to bıt tìší oblast,|ne naznaèovali údaje. 
{31099}{31154}Existují dvì cesty, zobrazím je. 
{31166}{31272}Mùeme projít vertikálnì|vzhledem k rovinì otáèení. 
{31284}{31322}To pøesnì dìlají ostatní lodì. 
{31337}{31406}Druhá monost je vysledovat otáèení planet...
{31413}{31486}... a proletìt pøímo pøes kontrolní bod.
{31498}{31524}Co je rychlejší? 
{31533}{31596}Jít vertikálnì je pravdepodobnì bezpeènìjší.
{31604}{31677}Nemuseli by jsme pøekøíit orbit planety.
{31687}{31722}Co je rychlejší? 
{31731}{31758}Jít pøímo skrz. 
{31771}{31814}Pùjdeme tedy pøímo skrz! 
{31823}{31846}Tak moment! 
{31851}{31915}Je tu pøíliš moc faktorù,|které plynou z gravitace planet, 
{31923}{31997}jejich obìné rychlosti a magnetizmu! 
{32010}{32083}Podívej, je to jako skákat pøes švihadlo,|akorát e s planetami! 
{32087}{32118}Mùeme to dokázat, kdy pùjdeme hned teï!
{32127}{32154}Jdeme na to! 
{32171}{32263}Tak moment! Kdy jsou planety|Heifongu III blízko sebe, 
{32267}{32374}nastává pøílivovı efekt|a spustí se støídavé vlny! 
{32382}{32427}Jaké vlny? Moøské? 
{32429}{32482}Pokud to chcete nìkam zaøadit,|tak tøeba kovové.
{32494}{32525}Já nic nevidím! 
{32535}{32603}Vstoupili jsme do oblasti mezi dvìmi planetami.
{32693}{32751}Prorazíme skrz! Do toho! 
{32818}{32861}H-Hej, èo je to? 
{32867}{32985}Upozornìní. Od první planety|se pøibliuje rozmìrnı objekt. 
{32990}{33027}Co tím myslíš, "rozmìrnı"? 
{33038}{33074}Je to pravdìpodobnì vlna. 
{33159}{33190}Uká mi únikovou cestu! 
{33191}{33216}ádná není. 
{33221}{33247}Coe?! 
{33254}{33334}Gene, kontrolní bod!|Bude pohlcen! 
{33695}{33842}Oto no nai mahiru... 
{33846}{34013}...kaze wa tada akarui. 
{34016}{34325}Sukoshi nemutasou ni|hanabira ga yureta.
{34355}{34546}Nanigenai kono omoi, 
{34554}{34937}nee, hito wa donna|kotoba de yonde iru no?
{34952}{35246}Shiroi suna no tsuki,|tojikometa hanashi o... 
{35252}{35578}...hikarifurasu you|ni kikasete ne, sotto.
