{1}{1}23.976
{122}{202}Éterovı tok naráí na boky lodí.
{230}{310}Hvìzdy planou, bièované bouøkami.
{350}{431}Dravé proudy z hlubin|je pøekonávají.
{446}{534}Vyvrhnuté z vıšky planet|proráejí pøes jejich trupy.
{566}{626}Ale je jedno kolik tísícù lodí|se zmìní na trosky...
{644}{735}...a nebo kolik desetitisícù ivotù|se stratí v prázdnotì,
{763}{832}lodì nepøestávají plavat do tohoto moøe.
{852}{926}Plavcù, kteøí se po nìm|chtìjí plavit je stále mnoho.
{955}{1145}To proto, e i dnes je v tom|nekoneèném moøi oèekávají neprozkoumané oblasti.
{1303}{1385}Neobviòuj to, neniè to, nepodceòuj to...
{1387}{1505}...to nìco jedineèné, co kadı má.
{1522}{1546}Moje láska...
{1547}{1570}Moje sny...
{1572}{1597}A té ty.
{1599}{1742}Nevzdám se toho, za ádnou cenu.
{1800}{1897}V té noci, kdy jsi nepokojnı,|kdy dìláš cokoliv,
{1902}{2010}...máš chu to vše odhodit pryè.
{2014}{2113}Neøíkej u nic, jen otevøi dveøe.
{2116}{2221}Nemám èas se tu|s tebou bavit.
{2226}{2335}Chci všude volnì letìt,
{2345}{2435}a nedbat v letu na opatrnost!
{2442}{2534}O nic jsem nepøišel,
{2536}{2621}vdy jsem ještì ani nezaèal.
{2638}{2718}Neobviòuj to, neniè to, nepodceòuj to...
{2721}{2840}...to nìco jedineèné, co kadı má.
{2856}{2884}Moje láska...
{2886}{2913}Moje sny...
{2914}{2933}A té ty.
{2937}{3056}Nevzdám se toho, za ádnou cenu.
{3085}{3108}Co by jsi chtìl?
{3110}{3135}Co chceš dìlat?
{3137}{3189}Kam pùjdeš?
{3192}{3347}Vezmi co chceš, pøetni temnotu,|kdy budeš utíkat nocí!
{3502}{3526}Uka mi únikovou cestu!
{3527}{3548}ádná není.
{3555}{3578}Coe?!
{3660}{3706}V takovém pøípade bude pohlcen!
{3725}{3770}Zùstává nám akorát prohnat se|tím plnou rychlostí!
{3818}{3849}To je šílené!
{3862}{3913}Myslel jsem si,|e jsi nejrychlejší loï v galaxii!
{3927}{4021}Vıkon motorov 108%.|Všechny motory vykazují normál.
{4033}{4069}Jdeme na to!
{4303}{4327}Dokázali sme to!
{4380}{4480}OUTLAW STAR:"Ztraceni v subprostoru!"
{4498}{4565}Ještì nejsme mimo orbitu planet.
{4573}{4655}Ale nejprve, prosím,|vrate vıkon motorù na normální úroveò.
{4662}{4724}Teda, ty si musíš stìovat na všechno, co?
{4769}{4832}Prošli jste kontrolním bodem 1, Outlaw Star.
{4846}{4897}Ale vyvádìli jste tam velké vìci.
{4909}{4943}Na kterém jsme místì?
{4956}{4999}Pøedbìhli jste dvanáct lodí.
{5007}{5081}Pøed vámi je 13 lodí,|ale podle vašeho èasu jste šestí.
{5082}{5133}Po tom všem,|to jsme jen šestí...?
{5142}{5198}Nejste jediní,|kdo si zvolil tu cestu.
{5211}{5286}Ale jste jediní,|kdo to stihl pøed tou vlnou.
{5292}{5350}Øíkal jsem si, e udìlám|závody trochu víc vzrušující.
{5357}{5418}Jistì. Tak teda, hodnì štìstí.
{5443}{5555}Další je pátá planeta, Heifong V.|Vzdálenost asi 500 miliónù kilometrù.
{5558}{5634}Pojïme do subéteru a pøeskoème ten úsek.
{5638}{5706}Loï Outlaw Star,|která neèakanì poskoèila v poøadí,
{5709}{5783}kdy dosáhla první kontrolní bod,|je momentálnì na šestém místì!
{5790}{5851}Co myslíte, e se stane dál,|pane Ishigaki?
{5853}{5936}Dobrá otázka. Outlaw Star,|nyní šestá, je jednoznaènım pøekvapením.
{5988}{6085}Udìlat jedinı okruh okolo tohohle|je lehkı kontrolní bod, e, Jime?
{6177}{6205}Hej, Jime!
{6230}{6299}Vydr, Jime. U jsme témìø|na servisní stanici.
{6379}{6405}Hej, máš pravdu.
{6406}{6510}Mìli by jsme se natáhnout aspoò|na hodinu a udìlat údrbu.
{6514}{6576}Všechny systémy ukazují normál.|Vše v poøádku.
{6585}{6685}V tom pøípadì, vykonejme údrbu|na sobì. Pojïme nìco sníst.
{7267}{7345}To je ta loï. Koneènì jsem ho dostihl.
{7582}{7655}Vy jste posádka z El Dorada?
{7674}{7730}To jsme. Kdo jste?
{7733}{7780}Kterı z vás je MacDougall?
{7812}{7845}Není tu nikdo s takovım jménem.
{7857}{7890}Jistì e je.
{7897}{7963}El Dorado je loï bratrù MacDougallovıch.
{7973}{8032}Nemám potuchy o èem mluvíte.
{8043}{8073}O kom to mluvíte?
{8082}{8110}Nedìlej blbého!
{8125}{8206}Nezdá se, e by tu byl ten chlap,|s kterım hovoøila Hilda,
{8223}{8294}ale poznávam tu loï!
{8329}{8414}To je ta loï, co na nás zaútoèila|u Farfallase.
{8443}{8480}O co se to tady snaíš, bastarde?
{8490}{8528}Pus Harryho!
{8530}{8578}To není tøeba, Terry, Leo.
{8590}{8655}Podívejte, nevím o èem to mluvíte.
{8665}{8719}Nikdy sem nebyl na "Farfallasu",|nebo co to je.
{8730}{8811}Proè piráti Kei hladají XGP?
{8819}{8898}Proè jste se pokoušeli XGP znièit?
{8914}{8986}Jestli se budete snait vyvolat boj,|zavolám poøadatele závodu.
{8993}{9093}Jen zavolej.|Ale chytøejší by bylo vyhovìt mi.
{9100}{9166}Kde jste kdo!|Ten chlap narušuje závody!
{9179}{9207}Je tu nìjakı problém?
{9210}{9317}Kdee, povídal mi jen|o specialitách podniku, e?
{9323}{9425}Nu, radši u pùjdu.|Speciality musí poèkat do budoucna.
{9553}{9595}Hej, Harry, o co mu šlo?
{9597}{9624}Zavøi hubu.
{9646}{9761}Ten chlap... Nemùu tomu uvìøit.|Pøeil Farfallas?
{9797}{9841}Jsou nìjaké problémy?
{9862}{9909}Ne, to nic není.
{9937}{10008}Dost mi to nahnalo strach,|kdy sem se díval, Gene.
{10016}{10078}Nešel jsi na to moc pøímo?
{10093}{10150}Jedinì, pokud by to nebyl MacDougall.
{10167}{10237}Ale jestli je, u nás víc|nemùe ignorovat.
{10253}{10298}Skontaktuje nás.
{10302}{10354}Ta loï právì startuje.
{10438}{10466}Kdy mùeme vystartovat?
{10478}{10509}A za 11 minut.
{10518}{10559}Jen, co ho dostihnu,|tak to s ním vyøídím.
{10586}{10676}Upozornìní všem lodím.|Dostali jsme správu, e se formuje éterovı proud,
{10679}{10776}kterı se táhne od Heifongu V|a ke kontrolnímu bodu 4A na Heifongu I.
{10790}{10855}Doporuèuje se pouít|kontrolní bod 4B na Heifongu II.
{10865}{10906}- Opakuji...|- Slyšel jsi ho.
{10908}{10950}Vše závisí na El Doradu.
{11030}{11127}Leo, dej mi úøední záznamy o lodi,|která odchází po nás.
{11134}{11160}Okej.
{11256}{11311}Je to XGP?
{11319}{11399}Loï na posledním místì právì dosáhla|2. kontrolní bod.
{11404}{11482}Dvì lodì právì odstoupili kvùli|problémùm s motory...
{11498}{11546}Kde myslíte, e je Gene?
{11558}{11649}Tohle vysílání je fakt špatné|pokuï jde o informace o soukromích lodích.
{11650}{11717}Tøetím kontrolním bodem je|Lione Lagrange Point,
{11719}{11773}kterı je 140 miliónù kilometrù od Heifongu V!
{11790}{11869}Sleèno Aisho? Za okamik dosáhneme 3. kontrolní bod.
{11885}{11915}Co je tam?
{11934}{12018}Øíká se, e kdysi dávno|obíhal okolo Heifongu V satelit,
{12034}{12116}kterı byl znièen|a jeho kusy se tam nahromadili.
{12125}{12159}Uber rychlost.
{12169}{12215}Jako kdyby jsem to nevìdìl...
{12386}{12413}Je tvoje, Harry!
{12419}{12489}Nebıt mé zruènosti,|nikdy by jsme nezískali tolik èasu!
{12644}{12688}Dìje se nìco, sleèno Aisho?
{12698}{12751}Hledám místo na uskuteènìní pøepadu.
{12754}{12801}- Co? Pøepad?|- Co? Pøepad?
{12809}{12837}Pøipravte se na boj!
{12841}{12881}- Co? Boj?|- Co? Boj?
{12886}{12982}Tato loï nyní vykoná|pøekvapivı útok na Outlaw Star!
{13043}{13105}S jedinım kulometem?
{13109}{13148}Jedinı kulomet...?
{13170}{13224}A co vaše Guriguri støely|a nebo Gagagan kanón?!
{13229}{13277}Nièím takovım  nejsme vybaveni!
{13285}{13335}A tomu øíkáte imperiální loï?!
{13340}{13417}Niburu Boribori je loï|na obchodování s Heifongem!
{13490}{13566}Nevím jaké rozkazy jste dostala|z Impéria, sleèno Aisho,
{13574}{13620}ale zaùtoèit s touhle loïí|na cokoli je beznadìjné.
{13626}{13662}Nemùu tomu uvìøit...
{13670}{13745}Dobrá tedy, je èas na poslední øešení!
{13782}{13801}Tam je to!
{13811}{13886}Hustota éteru stoupá a nepravidelnì kolísá.
{13898}{13979}Chyba subprostorového radaru|stoupla na 24%...
{13987}{14058}a úèinnı dosah standartního radaru|zas klesl o 30%.
{14078}{14136}Musíme se obejít bez pøístrojù|a spolehnout se na vlastní oèi.
{14141}{14193}Tak uvidíte, jak dobrı doopravdy jsem.
{14229}{14271}Spomal, Gene!
{14285}{14319}Ja vím!
{14341}{14393}Souèasná rychlost je 12 km/s.
{14409}{14528}Následujících 180 km je prázdno.|Potom tam vidím nìjaké velké asteroidy.
{14538}{14579}Jaká je nejkratší cesta|ke kontrolnímu bodu?
{14586}{14645}Prosím, zmeò kurz o jednu hodinu dole.
{14650}{14676}Rozumím.
{14808}{14824}Tam je to!
{14838}{14864}Pojïme na to!
{14980}{15019}Kontrolní bod dosáhnut!
{15021}{15042}Fajn!
{15046}{15101}Nyní nám akorát zùstává|rychle odsud vypadnout!
{15131}{15158}Mayday! Mayday!
{15165}{15232}Tu je Niburu Boribori!|Srazil jsem se s asteroidem!
{15239}{15295}Opustil jsem loï kvùli|monosti vıbuchu!
{15298}{15319}ádám o pomoc!
{15322}{15349}ádám o pomoc!
{15362}{15402}To je SOS.
{15424}{15479}Oznaèil jsem jeho polohu.|Dám to na obrazovku.
{15557}{15599}Co udìláme, Gene?
{15601}{15670}Myslím, e poøadatelé|závodù ho zanedlouho vyzvednou.
{15723}{15757}Pomùeme mu.
{15761}{15825}To... se ti vùbec nepodobá, Gene.
{15832}{15950}Není to ádná sranda|plavit se vesmírem úplnì sám.
{16153}{16186}Vidíš ho, Gene?
{16190}{16209}Hej.
{16246}{16268}Kruci...
{16270}{16295}Co je, Gene?
{16325}{16368}Mám trochu závra...
{16380}{16410}Budeš v poøádku?
{16418}{16470}Jo, poradím si s tím.
{16549}{16601}Okej, budete v pohodì.
{16686}{16729}Vyrovnávání tlaku skonèeno.
{16777}{16857}Byl jste jedinı èlen posádky|a nebo jsou tam i další?
{16949}{17001}Tentokrát mi neunikneš ty cucáku!
{17023}{17061}Co ty tu dìláš?!
{17190}{17252}Ze Slovenskıch titulkù: A-H-Sarvill
{17254}{17380}Není urèeno pro komerèní pouití.
{17404}{17538}Fakt? Ti MacDougallové mají|opravdu klíè k Galaktickému Leyline?
{17548}{17632}Pøinejmenším mají|víc informací o Hildì ne já.
{17640}{17751}Ty vánì nevíš nic|o Galaktickém Leyline?
{17761}{17821}Kdyby jsem vìdìl,|u by jsme tam dávno šli.
{17832}{17909}Podívej, kdy nìco najdeme,|øekneme ti.
{17918}{17950}Take si nìkde vystoupíš z lodì, ok?
{17954}{18041}To nejde!|Nemùu se takhle vrátit do Impéria!
{18048}{18110}Nemùu se vrátit!|Povaovali by mì za úplnì neschopnou!
{18122}{18165}Vy jste moje jediná stopa.
{18169}{18227}Dokud nìèo nezískám, neodejdu!
{18233}{18273}Co chceš dìlat, Gene?
{18290}{18333}Bıt u en oblíbenı není lehké...
{18335}{18370}To jsem nemìl na mysli.
{18392}{18498}Tohle je divná loï.|Nepohla by se bez toho, aby si nebyla nahá?
{18502}{18575}Totálnì zaostává za lecjakou|loïí Ctarl Ctarl.
{18582}{18669}Jak se to opovauješ takhle mluvit|o nejrychlejší a nejdokonalejší lodi v galaxii!
{18670}{18725}Co? Co je to?
{18729}{18808}Já nejsem "to". Øíkej mi,|prosím, Gilliam.
{18834}{18885}Coe--? To je poèítaè?
{18914}{18958}Kadopádnì,|vrame se spìt k zavodu.
{18969}{19065}Mùj plán dostihnout El Dorado|je u urèitì v tahu.
{19078}{19149}Kruci, ukáe se jedno|koèkovité dìvèe a vše je v kelu.
{19152}{19225}Jak neskonèíme tøetí a nebo lepší,|budeme ješte víc zadlueni.
{19234}{19333}Nyní pøipravuji vstup do subéteru.|Prosím, nastavte opravu kurzu.
{19346}{19368}Rozumím.
{19374}{19450}Odhadovanı èas vstupu do subéteru, 24 minut.
{19479}{19505}Nevidím!
{19577}{19643}Po dosáhnutí 3. kontrolního bodu|odstoupili tøi lodì,
{19649}{19718}take k 4. kontrolnímu bodu míøí|jen 35 lodí.
{19726}{19745}Dìlej--
{19807}{19901}Celé tohle cestování mì vyèerpalo,|jdu si zdøímnout.
{19906}{19945}Probuïte mì, a tam budeme, jo?
{19956}{19985}Jo, jak chceš...
{20082}{20129}nyní pøepínám na subéterovı pohon.
{20138}{20193}Vıkon Munchausenového reaktoru stoupá.
{20203}{20257}Prahová hodnota éteru dosáhnuta.
{20294}{20359}Kurz zadanı.|Relatívní souøadnice potvrzené.
{20430}{20473}Nyní vytváøím subéterovou bublinu.
{20573}{20630}Ah, buï ticho...
{20638}{20753}Ze zadu se blíí nìjaké objekty.|87% pravdìpodobnost, e jsou to støely.
{20757}{20816}Ja to nechápu!|Myslel jsem, e za námi nikdo není!
{20823}{20856}Kadopádnì, oplame jim to!
{20864}{20919}Pøecházíme do subéterového módu.|Není to moné.
{20934}{20974}Kolik ješte, ne vejdeme do subéteru?
{20978}{20999}Osumnáct vteøin.
{21005}{21053}Støely narazí za 16 sekund.
{21098}{21128}Musíme je setøást!
{21188}{21225}Co se dìje?
{21236}{21279}Pøípravy na skok|do svetelné rychlosti ukonèeny.
{21281}{21335}Prùnik do subéteru za osum,
{21337}{21356}sedum,
{21358}{21377}šest,
{21381}{21400}pìt,
{21404}{21422}ètyøi,
{21427}{21441}tøi,
{21452}{21465}dva,
{21477}{21489}jedna...
{21500}{21536}- Nula.|- Dokáeme to!
{21951}{22009}Sakra, Harry! To bylo ohromné!
{22032}{22109}Vešli do subéteru ješte pod|vlivem normální gravitace!
{22119}{22157}Zøejme byli rozhození.
{22167}{22221}Fajn, pøipravme se vejít do subéteru.
{22230}{22298}Hej, Harry, o co se jednalo s tou loïí?
{22307}{22390}Byla pøekákou pro mnì a mého bratra.
{22559}{22620}Vùbec se nedá øíct, kam jdeme.
{22623}{22675}Subéterovı pohon, nouzové zastavení!
{22682}{22740}Munchausenùv reaktor se vymkl kontrole!
{22743}{22792}C-Co se to dìje?!
{22816}{22902}Tlak na loï narùstá.|Právì pøekraèuje bezpeènou hodnotu!
{22921}{22965}Vypínám všechny pohonné systémy!
{23250}{23307}Hej. Probuï se.
{23347}{23386}Jsi v poøádku, Melfino?
{23394}{23433}Ano, jsem.
{23446}{23504}V souèastnosti fungujeme|na záloní zdroj,
{23509}{23547}take nemáme ádné informace|o dìní venku.
{23550}{23581}Prosím, nastartujte loï.
{23622}{23698}Neuvìøitelné. A ivot jde dál.To je trochu moc.
{23926}{23992}- Testuji, testuji...|- Kde, k sakru, jsme?
{23994}{24073}Vypadá to, e jsme se bezpeènì vrátili|do normálního vesmíru.
{24088}{24190}Naštìstí, zdá se, e nejsme|príliš daleko od systému Heifongu.
{24196}{24230}Pokusím se vypoèítat naši polohu.
{24232}{24280}Tahle loï je odolnìjší,|ne jsem si myslela...
{24283}{24329}Myslím, e u sem to øíkal,
{24332}{24381}sem nejrychlejší a|nejdokonalejší loï v galaxii.
{24394}{24415}Víš, kde jsme?
{24417}{24505}Ano. Jsme kousek od obìné dráhy|Heifongu V...
{24509}{24614}...a asi 360 miliónù kilometrù|nad jeho rovinou obìhu.
{24630}{24673}Jak dlouho je to u, co jsme skoèili?
{24682}{24778}Lodní hodiny udávají 2 minuty a|24 vteøin od vstupu do subéteru.
{24794}{24838}Dej mi hlášení o stavu.
{24847}{24948}ivotní podpora, komunikace|a všechny senzory vykazují normál.
{24952}{25005}Potvrzené nepravidelnosti|v systému éterového pohonu,
{25014}{25084}Newtonové reaktory 1 a 3 jsou nefunkèní.
{25117}{25176}Aktivuj reaktory 2 a 4.
{25189}{25229}Nastav kurz ke kontrolnímu bodu 4.
{25236}{25289}Stále chcete pokraèovat v závodì?
{25303}{25374}Si myslíš, e to vzdám,|kdy se ješte zvládáme hıbat vlastní silou?
{25382}{25421}Subéterovı pohon stále pracuje, e?
{25422}{25527}Ano, ale dva reaktory na 50% vıkonu.
{25536}{25594}To na vstup do subéteru nestaèí.
{25602}{25662}Jak dlouho by trvalo dosáhnout 4. kontrolního|bodu s pouitím éterového pohonu?
{25666}{25710}Vzdálenost je 600 miliónù kilometrù.
{25714}{25813}Na 50% vıkon... by to trvalo asi 96 hodin.
{25853}{25892}Závody by mezi tím u skonèili.
{25997}{26074}Co je? Vzdali jste se?
{26083}{26169}Nìkdo nás jen trefil|pár raketama a hned, e...
{26174}{26200}"Loï je znièená!"
{26203}{26227}"Jsme v kelu!"
{26248}{26273}"Všemu je konec."
{26275}{26332}Tak, co se dìje?
{26338}{26419}Podle Ctarl-Ctarl je to vaše|chování špané!
{26430}{26502}Podle Ctarl-Ctarl, jde o spravedlivost!|Odvaha! Vytrvalost!
{26511}{26557}S tìmito tøemi ideály se nikdy|nevzdáváme a vdy udìláme, co se dá...
{26558}{26624}- My nejsme Ctarl-Ctarl, jasné?|- ...aby sme prácu dokonèili!
{26632}{26751}Vy nemáte ani vytrvalost|ani odvahu plavit se v éterovém moøi!
{26759}{26824}Gilliame! Mùeš mi øíct,|kde se formuje éterovı proud?
{26830}{26875}Oh, ouu... Podívám se.
{26884}{26909}Ah, tady je to.
{26914}{27015}Proud se šíøí od Heifongu V|k Heifongu I. U jsem ho lokalizoval.
{27022}{27062}Aisho, sedni si!
{27064}{27086}Neøíkej co mám dìlat.
{27128}{27164}Co máš v plánu, Gene?
{27173}{27284}Je mi jedno, jestli prohrajem, ale právì|sem objevil nìco, co mùeme ješte skusit.
{27293}{27337}Poèkej, snad nemyslíš...
{27347}{27448}Kadá normální loï, která by vstoupila|do éterového proudu by u byla historií.
{27456}{27490}Kadá normální loï.
{27497}{27552}Tohle není obyèejná loï.
{27563}{27591}Presnì!
{27594}{27658}Kdy jsem se díval do návodu na obsluhu,|objevil jsem nìco pøekvapivého.
{27663}{27738}Tahle loï si dokáe poradit|s lecjakım éterovım proudem.
{27753}{27779}A to znamená...
{27783}{27815}Nechci to slyšet!
{27822}{27876}...e projdeme tímto éterovım proudem!
{27902}{27937}Jdem na to!!!
{28050}{28124}Dostali jsme se do kontaktu a pøepli se|do Grapplerového bojového módu.
{28156}{28220}Vìøte mi trochu a vydejte se mi do rukou.
{28231}{28254}Já si s tím poradím!
{28263}{28282}Dokáu to!
{28284}{28309}A z èehoho tak usuzuješ...?
{28312}{28347}- Z nièeho!|- To sem si myslel...
{28349}{28432}Ale vdy je vše jednou po prvé!
{28641}{28688}Boj je perfektním tréningem!
{28694}{28765}Do toho!|Nepodlehni tomu bastardovi s raketami!
{28900}{28960}Dosáhli jste kontrolního bodu 4, El Dorado.
{28980}{29008}Jaká je naše pozice?
{29020}{29109}Podle údajù z kontrolního bodu|jste v souèasnosti na 4. místì.
{29122}{29211}Take to závisí na tom,|které lodì míøí k Heifongu I?
{29218}{29349}Avšak, máme zprávy o éterovém proudu|okolo Heifongu I.
{29359}{29407}Take je jisté, e skonèíme lepší jak ètvrtí, e?
{29454}{29512}Proè mi tak bije srdce?
{29608}{29659}Co?! Kde se tu vzali?!
{29663}{29722}Vypadá to, e prošli éterovım proudem!
{29723}{29741}Náhodou?
{29742}{29782}Ne, zdá se, e úmyslnì.
{29791}{29876}Jsou snad blbí?!|Mùeš mi k nim otevøít kanál?
{29966}{30051}Tady je loï è. 26, Outlaw Star.|jaká je naše pozice?
{30058}{30125}Jak to mám vìdìt?|Ale jste na prvém místì mezi pošahanımi kaskadéry!
{30129}{30189}To rád slyším! Outlaw Star, konèí!
{30201}{30273}Gilliame, vyuijeme Heifong I|na gravitaèní zrychlení!
{30309}{30347}Myslel jsem, e je po nás...
{30371}{30443}Ale pokud budeme pokraèovat,|mùeme bıt mezi prvními tøemi...
{30493}{30579}Jako první pøichází Sunbeam 545|z Trihorse Corporation!
{30581}{30621}První místo je u jisté!
{30623}{30677}A další je Bonaparte|z Penelope Corporation!
{30679}{30738}Èasové rozdíly mezi pøicházejícími|lodìmi by mohli bıt problémem!
{30744}{30768}Kde je Gene?!
{30777}{30833}Bonaparte si zajistil druhé místo!
{30838}{30880}A souboj o tøetí místo?
{30890}{30976}A loï na tøetím místì...|je u na dohled!
{30990}{31029}Je to Outlaw Star!
{31034}{31083}Cíl!
{31094}{31172}Outlaw Star, soukromník,|je tøetí loïí jdoucí do cíle!
{31176}{31274}Ale Hisetsu, kterı zaèal|o dvì minuty pozdìji, se blíí k èáøe!
{31290}{31314}Ustupte!
{31322}{31375}Pokud skonèí víc jak dvì minuty po nás,|vyhráli jsme!
{31390}{31454}Hisetsu z Siven Industries|právì dosáhll cíl!
{31457}{31540}A jeho èas...?|Vyøadil Outlaw Star z tøetího místa!
{31576}{31616}Byli tak blízko...
{31779}{31805}Nemusíte spìchat!
{31806}{31836}Proè?
{31838}{31900}Skonèili jsme ètvrtí, tak co s námi má|spoleèné pøedávání cen?
{31903}{31995}Celkovì jste skonèili ètvrtí,|ale byli jste první v kategorii soukromníkù.
{32005}{32079}Jakoby na tom Fredovi Luo nìjak záleelo...
{32092}{32126}Hej, co to dìláte?
{32132}{32214}Jsme Outlaw Star, na prvém místì|mezi soukromníky!
{32218}{32252}Rozumíte?
{32379}{32447}Sice pøišli ètvrtí, ale i tak myslím,|e je to celkem dobrá reklama.
{32457}{32499}A co teda sponzorskı poplatek?
{32505}{32558}Myslím, e jim dám polovinu.|200 000.
{32564}{32646}Je to trochu køiklavé, ale myslím,|e to není tak špatné.
{32650}{32678}Co øíkáte?!
{32702}{32753}Co tím myslíte,|El Dorado vypadlo?!
{32764}{32893}Tak, ohlednì toho...|Máme pro vás vzkaz z El Dorada.
{32921}{32947}Coe?Vzkaz pro mì?! 

