{1}{1}23.976
{157}{253}Mimo jiné,zabijejí.|Pokud jim to vynese peníze, zabijejí.
{270}{350}Piráti? Outlaws?|Odpadlíci Vesmírnıch jednotek?
{352}{391}Ne, ani jedni.
{398}{463}Ale berou práci od kdekoho.
{476}{533}Pøesnì tak. Pokud jim to vynese peníze.
{553}{642}A u jsou kdokoli, jsou to hyeny,|kterıch si cení všechny mocnosti.
{665}{743}Jsou nebezpeèní, pokud se k nim dostanete|pøíliš blízko.Jináè jsou dobøí.
{774}{863}Kdyby nebyli, nìkdo by je byl|u dávno støelil do zad.
{880}{948}Je to silnìjší ne nenávist ostatních lidí k nim.
{966}{1049}Kadı v podsvìtí zná jméno,|"Bratøi MacDougallovy".
{1062}{1173}Ale nikdo neví,|kdo bratøi MacDougallové opravdu jsou.
{1182}{1254}Jsou opatrní, odvání, chytøí,|a za peníze udìlají vše.
{1262}{1304}Jsou spolehliví a vytrvalí.
{1320}{1434}Kadı, kdo se dozvìdìl víc ne je tøeba,|byl zabit.
{1469}{1569}Všichni. Rukou bratrù MacDougallovıch.
{1672}{1753}Semenaide, kesanaide, makenaide...
{1754}{1876}...daredatte motteru|hazu yuzurenai mono.
{1893}{1967}Ai dake, yume dake, kimi dake...
{1969}{2111}...sore dake wa hanasanai,|donna toki de mo.
{2169}{2269}Dou shiyou mo naku,|ochitsukanai yoru...
{2271}{2383}...nani mo ka mo nagedashitaku naru.
{2385}{2483}Tsubekobe iwazuni,|sassa to doa o akena.
{2485}{2592}Rikutsu nante, koneteru hima wa nai.
{2600}{2806}Juu'ou-mujin tobimawaritai,|youi-shuutou mamoritakunai!
{2812}{2991}Nakushita wakeja nai,|mada hajimattenai dakara.
{3007}{3090}Semenaide, kesanaide, makenaide...
{3091}{3210}...daredatte motteru|hazu yuzurenai mono.
{3227}{3307}Ai dake, yume dake, kimi dake...
{3309}{3427}...sore dake wa hanasanai,|donna toki de mo.
{3455}{3559}Nani ga hoshii? Nani ga shitai?|Doko ni ikitai?
{3566}{3718}Yami o saite hashirinukete|tsukamitore through the night!
{3983}{4053}Vzdálenost k okraji Lione|Lagrange Point, 30 000 kilometrù.
{4170}{4205}Nìjaká známka po El Doradu?
{4210}{4243}Stále nic.
{4252}{4336}Ale senzory jsou trochu ovlivnìné|magnetickou bouøkou...
{4346}{4480}Podle posledních meteorologickıch zpráv,|jsou sluneèní erupce stále aktivní.
{4493}{4559}Tahle magnetická bouøka bude zøejmì chvíli trvat.
{4567}{4617}Oni jsou na tom stejnì.
{4624}{4685}Pøišel èas odplaty, El Dorado...
{4684}{4776}OUTLAW STAR:"Smrtící boj s El Doradem!"
{4794}{4819}Co øíkáš?
{4825}{4868}Co tím myslíte, El Dorado vypadlo?!
{4874}{4890}Eh?
{4901}{4943}P-Ptáte se špatné osoby!
{4952}{4983}Kam se podìl?
{4990}{5029}Nu, ohlednì toho...
{5042}{5121}Máme tady pro vás vzkaz z El Dorada.
{5150}{5175}Coe?Vzkaz pro mì?!
{5288}{5325}Vzdálenost k Lagrange point, 10 000.
{5330}{5376}Stále ádná stopa po nepøíteli...
{5398}{5456}Nebude uvnitø toho pole asteroidù?
{5464}{5545}Nechci tam jít, døív ne se pøesvìdèím.
{5551}{5576}Spomaluji.
{5598}{5677}U mám dost toho tvého štìstí.
{5686}{5760}Chci s tím u skoncovat,|tak pøiï do Lione Lagrange point,
{5776}{5813}Pøiï do 50 hodin.
{5821}{5894}Pokud mì porazíš, povím ti cokoliv chceš vìdìt.
{5944}{5965}Gene...
{5970}{6018}Vızva na souboj, e?
{6026}{6056}To bude zajímavé...
{6203}{6229}Oh, ne.
{6244}{6356}Magnetické bouøky, rušivı éterovı proud,|nahromadìnı meziplanetární materiál...
{6364}{6439}Podmínky jsou v tomhle regiónu strašné.
{6443}{6513}Nezdá se, e by tady radar,|CFS a nebo subprostorovı radar...
{6518}{6586}... byli k nìèìmu dobré.
{6593}{6665}Take se budeme muset spolehnout|na vlastní oèi, e?
{6679}{6739}Nechejte to teda na mne!
{6750}{6832}Jistì. Slyšel sem, e Ctarl-Ctarl|mají dobré oèi.
{6863}{6929}Proè tì musíme tahat sebou?
{6935}{7011}To vy jste mi znièili šance nìco|ve svìtì dosáhnout.
{7020}{7137}Musíte mi to vynahradit!|Musím najít Galaktickı Leyline!
{7150}{7218}Podívej, chci se tì na nìco zeptat.
{7230}{7288}Co, ksakru, je ten Galaktickı Leyline?
{7293}{7364}Co? Vy nevíte ani to?
{7370}{7421}Hilda nám toho moc neøekla.
{7430}{7528}V Galaktickém Leyline se nachází|neuvìøitelnı poklad!
{7536}{7596}Poklad? Nìjakı druh vzácného kovu?
{7602}{7653}Moná, a nebo zásoby Dragonitu!
{7665}{7712}Spravodajská sluba Impéria odhaduje,
{7717}{7810}e jeho cena by staèila na|koupení celého solárního systému!
{7814}{7858}Wow! Úasné!
{7865}{7931}A u je to jakkoliv "úasné",|stále je to jen vìc.
{7942}{8053}Z toho mála, co jsem slyšel,|mi to nepøipadá moc jako poklad.
{8058}{8095}Co to teda je?
{8105}{8177}Brána. Slyšel jsem, e je to nìjakı druh brány.
{8184}{8290}Tak potom je ta brána urèitì|vyrobena z Dragonitu!
{8306}{8425}Kadopádnì, nemùem tì vzít sebou.|Tohle je náš boj.
{8488}{8585}Pokud ti bratøi MacDougallové|vìdí nìco o Galaktickém Leyline,
{8591}{8641}tak jdu jednoznaènì s vámi!
{8752}{8789}Nevidím po nich ani stopu...
{8796}{8826}Moná je to past.
{8833}{8917}Jistìe je to past. Chtìjí znièit tuhle loï.
{8927}{8979}Loï jménem XGP, je to tak.
{9195}{9262}Poèkejte. Poèkejte okamik, panstvo.
{9268}{9307}Huh? My?
{9313}{9370}Pøesnì tak, vy.
{9384}{9448}Jak se vám dostala do vlastniství ta loï?
{9470}{9491}Ano, ta loï...
{9498}{9533}Vy jste kdo?
{9580}{9618}Sem Gwen Khan.
{9623}{9739}Ano, jsem Gwen. Jsem èlen závodù.|Tohoto závodu, víte.
{9757}{9809}Ano, to jsem. Èlen.
{9818}{9905}No, pane Èlen,|proè se tak zajímate o naši loï?
{9914}{9957}Zajímám, jistì. Zajímam se.
{9963}{10072}Ano. Je to velmi vıkonná loï,|postavená neznámım vırobcem.
{10082}{10157}Ano, je to velmi vıkonná loï, tak to je.
{10162}{10180}No co.
{10220}{10331}Nìco mi øeknìte. Øeknìte mi.|Jak jste se k té lodi dostali?
{10334}{10410}Je to záhada. Ano, je to záhada.
{10599}{10621}Našli jsme jí.
{10622}{10651}Našli ji?
{10656}{10737}Hm? Našli? Je to moné?
{10746}{10770}Ne... Jak zvláštní...
{10772}{10820}Vy jí našli?
{10822}{10881}Ano. Byla to vìc bez majitele.
{10886}{10975}To znamená, e je loï teï naše.|Je v tom problém?
{10979}{11025}Problém? Problém...?
{11042}{11091}Ne, ádnı problém.
{11103}{11155}Ne, ádnı problém tu není.
{11163}{11220}Promiòte, ale spìcháme.
{11353}{11377}Pánové!
{11409}{11457}Chci, aby ta loï--
{11463}{11489}Co?
{11515}{11563}Ne, to nic.
{11579}{11624}Vùbec nic.
{11634}{11671}Nic, nic...
{11795}{11836}Nudím se...
{11838}{11889}Co to mìlo znamenat s tím staøíkem?
{11891}{11917}Vím já?
{11922}{12041}Mimochodem, Gene. To chceš stále krouit|okolo toho pole asteroidù?
{12057}{12123}Jo, nemùeme najít svého partnera|do tance, tak co máme dìlat?
{12125}{12181}No, moná ješte trochu spomalím.
{12190}{12238}Všechny pohonné systémy jsou v zelené.
{12255}{12321}Zelená je dobrá.A co Newtonové reaktory 1 a 3?
{12330}{12358}Fungují normálnì.
{12369}{12403}Dobrá, samozrejmì.
{12405}{12498}Moná to byla rychlá práce,|ale opravy byli dokonèeny.
{12505}{12577}Gee, tvoje nepøekonatelnost|nás opìt zachránila.
{12587}{12634}Vaše chvála mi lichotí.
{12645}{12665}Oh, ne.
{12671}{12689}Co je?
{12694}{12754}Blíí se støely, na hoøe na 9 hodinì  !
{12755}{12791}Bez varování? To je nezdvoøilé!
{12946}{12989}Nepøátelská loï pøed námi!
{13100}{13189}Tohle bude souboj jeden na jednoho.|Nebude ti to vadit, e?
{13194}{13237}Ne je to celkem fér.
{13250}{13307}Právì si nás chtìl znièit,
{13314}{13390}ale my máme pár otázek|døív ne znièíme tebe.
{13392}{13438}To budete muset bojovat tvrdì.
{13446}{13533}Navíc, tohle je tvoje høištì,|take my jsme ve velké nevıhodì.
{13539}{13586}V tomhle pøípadì vás ujišuji,
{13602}{13663}e do oblasti Heifongu nechodím èasto.
{13672}{13743}Vánì? Tak kde je tedy|tvoje obvyklé pùsobištì?
{13756}{13785}Okolo.
{13890}{13916}Hajzle!
{13991}{14023}Co udìláme, Gene?
{14027}{14066}Zùstává nám akorát to pøijmout, ne?
{14078}{14150}Gilliame! Vypust kameru!|Bude to náš prùvodce!
{14361}{14441}Uvnitø pole asteroidù jsou podmínky|ješte horší.
{14445}{14517}Vyslat jí pøíliš daleko je zbyteèné.
{14524}{14621}To znaèí, jeho past mu celkem nevyjde.
{14631}{14678}Není tady ani známky|po nepøátelské lodi.
{14689}{14750}Aisho, chci, aby jsi nám|dala pozor na záda!
{14754}{14783}Jen to nechej na mnì!
{14962}{15078}K sakru... Proè si, k sakru,|vybral na souboj zrovna takové místo?
{15090}{15138}Støely detekovány. Jsou prímo pod námi.
{15180}{15210}Ty zasra...!
{15301}{15378}Zdá se, e je vybaven|celkem pøesnımi raketami.
{15383}{15449}U to mám.|Proto si vybral tohle místo.
{15522}{15575}Pokud se nám tohle podaøí zmìnit na boj zblízka,|tak je náš!
{15631}{15650}Tam je!
{15654}{15674}Bastarde!
{15756}{15787}Není cesty!
{15826}{15850}Kam se podìl?!
{15990}{16014}Za námi!
{16015}{16037}Coe?!
{16074}{16110}Ten hajzl!
{16268}{16351}Ta jeho loï je manévrovatelnìjší|ne Outlaw Star?!
{16361}{16465}Tahle loï pouívá nejpokroèilejší|navigaèní systém v galaxii.
{16471}{16549}Je nemoné, aby moje manévrovatelnost|byla horší ne u lodì stejné tøídy.
{16554}{16617}Jasnı, urèitì do toho jde na plno.
{16699}{16742}Blíí se støely na 10 hodinách na hoøe.
{16847}{16901}Postav se proti nám èelem, k sakru!
{16905}{17007}Bratøi MacDougallové|se skrıvají fakt rádi...
{17027}{17050}Co--?
{17054}{17105}Jsou tu další støely! Na pravoboku!
{17111}{17140}Jsou na 4 hodinách na hoøe.
{17142}{17207}Coe?! On se u dostal za nás?!
{17247}{17289}Nedokáeme se zbavit tìch v pravo!
{17294}{17334}Tak je sestøelíme.
{17936}{17989}Budem muset jít proti tomu chlapovi naplno...
{18064}{18125}Ze Slovenskıch titulkù: A-H-Sarvill
{18128}{18260}Není urèeno pro komerèní pouití.
{18674}{18717}Blíí se støely, 9 hodin na hoøe.
{18791}{18850}Blíí se støely na 3 hodiny na hoøe.| Poèet: pìt.
{19157}{19214}Gene!Jak bude pokraèovat,|je po nás!
{19225}{19312}Co nejdøíve mu rakety dojdou!|A tehdy zaène opravdovı boj!
{19316}{19454}Pøestaòte tady vysedávat!|Vlítni tam a rozemelte ho na kaši!
{19459}{19477}Ztichni!
{19486}{19520}Kdyby jsem mohl,|tak by jsem se tady netrápil!
{19559}{19605}Komu øíkáš, aby byl ticho?!
{19613}{19655}Øikal jsem ti ztichni, tak ztichni!
{19657}{19684}Ty ztichni?!
{19694}{19787}Gilliame, není na mùstku pøíliš horko?
{19801}{19889}Promiòte. Hned uberu dva stupnì.
{19895}{19937}Teï pøicházejí další!|Na 10 hodinách na hoøe!
{19958}{19978}Mám je!
{20046}{20070}Kde je El Dorado?
{20074}{20103}Stratil jsem ho.
{20105}{20149}K sakru Gilliame. Co tam dìláš?!
{20160}{20229}Proè nevypustíme všechny kamery|a nerozmístíme je okolo nás?
{20242}{20324}Náš úèinnı dosah signálu|v tìchto podmínkách je asi 100 kilometrù,
{20332}{20404}take je nepravdìpodobné,|e by jsme získali nìjaké uiteèné zábìry.
{20408}{20520}A proto øíkám, e by jste tam|mìli vlítnout a rozdrtit ho!
{20531}{20564}Mlè u, k sakru!
{20566}{20603}Jistì, já tak budu urèitì ticho!
{20608}{20657}Jak nesklapneš, vyhodím tì ven!
{20661}{20704}Coe?!
{20721}{20740}He?
{20742}{20789}Vyhodit jí ven...poèkat..
{20802}{20888}Ano, za starıch èasù dával signál pozorovatel.
{20900}{20945}Silnım svìtlem nebo tak...
{20954}{21061}Aisho. Potøebuju aby jsi mi udìlala slubu,|ty velká, silná Ctarl-Ctarl.
{21068}{21126}Huh? Co ta zmìna?
{21134}{21185}Dovol, aby jsem tì vyhodil z lodì.
{21208}{21327}Šance je to malá,|ale urèitì lepší ne tohle.
{21448}{21496}Teï u by z toho mìli bıt opravdu zblbnutí.
{21507}{21541}Zøejmì máš pravdu.
{21570}{21618}Dorazíme je, Harry?
{21620}{21666}Ještì si s nimi trochu pohraju.
{21679}{21711}Kolik støel zùstalo?
{21713}{21758}Zùstává nám 24%.
{21793}{21834}Vidíš? Zùstalo nám jich hodnì.
{21852}{21891}Dostaòme se za nì.
{21927}{21973}Døív ne zjistí,|e tu je ješte jedna loï...
{22114}{22134}Coe--?!
{22245}{22304}Tam jsou! Tam jsou! Našla jsem je!
{22314}{22349}Byli jsme spatøeni?!
{22354}{22374}Nemoné!
{22382}{22421}Outlaw Star se blíí!
{22478}{22516}Teï jsi mùj!
{22524}{22573}Myslíš si, e se nechám tak lehko dostat?
{22702}{22741}Nevìdìl jsem e mají Grapplerová ramena?!
{22749}{22825}Myslel jsi si,|e El Dorado je jen obyèejnı køíník?
{22997}{23017}A co je tohle?
{23239}{23287}Zemøi! Zemøi! Zemøi! Zemøi!
{23515}{23545}Seer tohle!
{23878}{23912}Pøeber to, Jime!
{23918}{23940}Ale proè?!
{23974}{24011}Protoe já jdu tam.
{24252}{24314}Tady je El Dorado! Nepøítel mì chytil!
{24318}{24347}- Tu je El--|- Prestaò.
{24355}{24412}Kdy u došlo k tomuhle, vyøeším to teï a tady.
{24421}{24460}Tak jak budu chtít.
{24608}{24628}Bastarde!
{24696}{24745}T-To bolí!
{24772}{24839}Ty nejsi MacDougall.
{25273}{25307}Kde je MacDougall?!
{25489}{25553}Tak øekni, co chceš vìdìt?
{25701}{25735}O-Oh, ne.
{25740}{25772}Co je, Gilliame?
{25782}{25860}Nìkdo se do mnì pokouší hacknout.
{25874}{25917}Spouštím teï nouzovou ochranu.
{25929}{25966}Dobrou noc.
{25968}{25993}Gilliame!
{26082}{26099}Mel!
{26101}{26160}Prestaò! Jdi pryè!
{26174}{26214}Ty jsi MacDougall?
{26216}{26253}Harry MacDougall.
{26263}{26322}Nikdy jsem ješte svoje jméno|nepøíteli neøekl.
{26330}{26413}Proè chtìjí piráti Kei XGP?
{26422}{26487}No, byla to vlastnì jejich loï, ne?
{26496}{26564}Proè jsi se pokoušel znièit XGP?
{26574}{26629}Neptám se svıch zamìstnavatelù na dùvody.
{26637}{26669}Kdo je tvùj zamìstnavatel?
{26681}{26710}Tedy...
{26780}{26868}Chápu, tak tohle je|hlavní poèítaè lodì.
{26874}{26891}Hej!
{26898}{26958}Oh, nikdy jsem ho osobnì nepotkal.
{26968}{27020}Pøišel za námi s nabídkou práce.
{27030}{27114}Chci, aby jsi mi øekl víc o XGP.
{27138}{27179}Ptáš se toho nepravého.
{27210}{27312}Øíkal, e o Galaktickı Leyline|se zajímají piráti.
{27325}{27357}Leyline?
{27411}{27468}Znièím tuhle vìc za okamik...
{27536}{27563}ena?
{27669}{27721}Pøestaò! Jdi pryè!
{27835}{27870}Tohle je neuvìøitelné!
{27889}{27937}Co to dìláš, ty bastarde?!
{28138}{28154}Do prdele!
{28299}{28317}Moje ruka...
{28324}{28392}Nevìøím...nestøílej do mé ruky!!
{28486}{28534}Jsi v poøádku?
{28543}{28562}Ano Jime.
{28568}{28622}Zdá se, e pøístup byl pøerušen.
{28638}{28735}Co má XGP s Galaktickım Leyline?
{28737}{28793}Nevím... Nevím!
{28813}{28901}Proè jsi pøed šesti lety|znièil loï mého otce?
{28903}{28998}Nevím! Pøed šesti lety mi bylo 12!
{29002}{29117}Hej, MacDougalle.|Stále slyším o bratrech MacDougallovıch.
{29122}{29234}Pokud ty nevíš nic, ješte stále|se mùu zeptat tvého bratra.
{29246}{29285}Poèkej! Poèkej, prosím!
{29290}{29345}Kdy na to tak myslím, kde je tvùj bratr?
{29359}{29448}Gene, máme problém!|Je tu další El Dorado!
{29461}{29481}Co to øíkáš?!
{29615}{29644}Vra se ihned sem!
{29653}{29695}Rozumím... Tak to je jeho bratr, e?
{29780}{29846}Harry, co se stalo?|Odpovìz, Harry!
{29919}{29964}Pošlu je do pekla!|Pošlu je do pekla!
{29966}{29997}Pošlem je do pekla!
{30075}{30125}No, tímhle se koneènì vyøešila záhada.
{30130}{30205}Nekrouili okolo nás protoe|lépe manévrovali,
{30207}{30246}ale byla tam další loï!
{30248}{30292}Teï není èas na analızu!
{30297}{30356}Gene, vytahuji útoènı vrták!
{30526}{30578}Ten druhı je skuteènı MacDougall.
{30586}{30613}Jak skuteènı?
{30618}{30650}Jeho starší bratr.
{30671}{30701}Není cesty!
{30893}{30919}K sakru!
{31222}{31294}Jsme v nebezpeèí.|Prosím, vykonejte úhybnı manévr.
{31465}{31496}Do prdele!
{31505}{31540}To bolí, Rone!
{31546}{31605}Moje ruka! Moja ruka!
{31607}{31659}Uklidni se, Harry. Uklidni se!
{31665}{31746}Kdy patøíš mezi MacDougallovce,|nerozèiluj se kvùli malému zranìní!
{31772}{31830}Jistì... Promiò, bratøe.
{31839}{31877}To je v poøádku, Harry.
{31883}{31956}Tomu, kdo ti to udìlal,|udìláme nìco horšího.
{31967}{32074}Máš pravdu, Rone.|U nemíním znovu utéct.
{32108}{32135}ena...
{32150}{32193}Ta ena...
{32234}{32286}Je to beznadìjné. Nemùu je zachytit.
{32291}{32332}Nepøátelská loï se ztratila, co?
{32352}{32388}Tak co teï, Gene?
{32395}{32478}Jakoby jsme mìli na vıbìr...|Vrátíme se na Heifong a budeme  to skoušet znovu.
{32493}{32577}Promiò, Melfino.|Ztratil jsem další stopu.
{32634}{32676}Ne, to nic.
{32710}{32840}Hej! Pojïte rychle sem a vyzvednìte mì!
{32853}{32935}Myšlenka, e se jí budu muset|omluvit je fakt deprimující...
{32944}{32980}Radši by jsi jí tam nechal?
{32994}{33052}Urèitì by se vrátila a strašila mì.
{33054}{33128}Hej! Chvátnìte si!
{33154}{33253}Harry MacDougall... Co je zaè...?
{33266}{33344}Já sem tady!Vidíte mì! Tady !
{33589}{33708}Oto no nai mahiru...
{33728}{33880}...kaze wa tada akarui.
{33893}{34188}Sukoshi nemutasou ni|hanabira ga yureta.
{34198}{34418}Nanigenai kono omoi,
{34430}{34805}nee, hito wa donna|kotoba deyonde iru no?
{34827}{35124}Shiroi suna no tsuki,|tojikometa hanashi o...
{35142}{35470}...hikarifurasu you|ni kikasete ne, sotto.