{1}{1}23.976
{115}{180}Pod pøímım velením Hazanka,
{182}{227}vùdcem pirátské skupiny Sto osm hvìzd,
{229}{342}je Antenská Sedmièka, obávaná skupina zabijákù.
{380}{472}Tobigera, mistr pøevlekù a nástrojù na zabíjení.
{508}{613}Hanmyo, zázrak vesmírného boje vyuívající koèky.
{650}{752}Iraga, vlkodlak s témìø zázraènou ivotní sílou.
{789}{885}Jukai. Jeho schopnosti jsou zahalené tajemstvím.
{908}{976}Hitoriga. Mu kterı se vyzná v bojovıch umìních,
{978}{1031}a také nìco jako vùdce Antenské Sedmièky.
{1062}{1171}Hamushi. Kráska, která okouzluje mue sex apelem.
{1201}{1265}Shimi, bojovník s takovımi schopnostmi,
{1268}{1363}e se v Pirátské gildì nenajde nikdo, kdo by o nìm neslyšel.
{1402}{1483}Nìkomu, kdo mìl tu smùlu,
{1485}{1547}e jsi znepøátelil Antenskou Sedmièku|a bojoval s ní,
{1567}{1615}by jsem øekl jen:
{1651}{1706}"Zbohem, pøíteli."
{1818}{1899}Neobviòuj to, neniè to, nepodceòuj to...
{1899}{2020}...to nìco jedineèné, co kadı má.
{2038}{2063}Moja láska...
{2063}{2088}Moje sny...
{2088}{2112}A té ty.
{2115}{2257}Nevzdám se toho, za ádnou cenu.
{2315}{2413}V té noci, kdy jsi nepokojnı,|kdy dìláš cokoliv,
{2415}{2526}...máš chu to vše odhodit pryè.
{2530}{2628}Neøíkej u nic, jen otevøi dveøe.
{2628}{2737}Nemám èas se tady|s tebou bavit.
{2742}{2851}Chci všude volnì letìt,
{2858}{2949}a nedbat v letu na opatrnost!
{2955}{3048}O nic jsem nepøišel,
{3048}{3145}vdy jsem ještì ani nezaèal.
{3152}{3233}Neobviòuj to, neniè to, nepodceòuj to,
{3236}{3355}...to nìco jedineèné, co kadı má.
{3370}{3400}Moja láska...
{3400}{3429}Moje sny...
{3429}{3450}A té ty.
{3453}{3572}Nevzdám se toho, za ádnou cenu.
{3599}{3627}Co by jsi chtìl?
{3627}{3653}Co chceš dìlat?
{3653}{3705}Kam pùjdeš?
{3708}{3863}Vezmi co chceš, pøetni temnotu,|kdy budeš utíkat nocí!
{4206}{4325}Lorde Hazanko, Antenská|Sedmièka se shromádila.
{4383}{4481}Pokud jsme jediní, kdo se dokáe o toho chlapa postarat, tak je asi dobrı.
{4484}{4563}Smím se s ním vypoøádat já?
{4565}{4617}Mnì by ta práce nevadila.
{4647}{4754}Hitorigo, Antenská Sedmièka|se zdá bıt neùplná.
{4763}{4849}Pan Hazanko to pøedvídal.
{4850}{4936}Jako prvního zabijáka jsem vyslal Shimiho.
{4938}{4986}Vıbornì, pane Hazanko.
{4988}{5073}Jak znám Shimiho, jisto jistì vyplní vaše rozkazy.
{5077}{5231}Ten mu moná ukradl XGP, ale je to jen ubohı a bezmocnı Outlaw.
{5240}{5315}Proè potøebujeme zabíjet nìkoho takového?
{5319}{5461}Hmm, síla Geneho Starwinda není nic v porovnání s naší.
{5470}{5577}Ale cítím silnı tok "chi"|proudit smìrem k nìmu.
{5590}{5708}Zatím je to jen malı náznak,|ale pokud to necháme jen tak,
{5720}{5826}myslím, e nakonec sešle temnı stín na cestu, kterou kráèíme.
{5842}{5952}A tak vás povìøuji touto úlohou.|Ve jménu Antenu,
{5973}{6050}speèete osud Geneho Starwinda!

{6060}{6146}OUTLAW STAR:"Sedmièka se objevuje!"

{6162}{6228}Gene, stále jsme hodnì v mínusu.
{6266}{6314}Potøebujeme se dostat k velkım penìzùm...
{6322}{6377}Gene! Slyšíš vùbec?!
{6386}{6410}Jo...
{6417}{6441}Gene!
{6446}{6533}Sklapni u... Nepotøebuju, aby jsi mi to øíkal.
{6603}{6641}Lháøi!
{6677}{6757}Nedostáváš ádné pracovní nabídky,|tak se vybijíš na Jimovi!
{6764}{6832}Ta tvoje proklatá hra také dìlá rámus.
{6835}{6896}Vylévat si to na mnì ti nijak nepomùe.
{6898}{6939}Proè si to nepøiznáš sám?
{6957}{7001}Sklapni u!
{7111}{7196}Konec hry!|Je to všechno tvoje vina, Gene!
{7199}{7234}Sklapni u...
{7236}{7275}Udìlala jsem kávu.
{7278}{7295}Díky!
{7297}{7366}Sem vyprahlá!|Já si dám také!
{7382}{7461}Co budeme dìlat? V ivotì potøebuješ mít plán.
{7470}{7530}Vyøešíme záhadu Galaktického Leyline...
{7557}{7601}...a sebereme poklad!
{7627}{7687}Kdoví, co je to za poklad?
{7767}{7793}Tady máš.
{7902}{7975}Gene Starwinde! jestli jsi tam, vylez!
{8075}{8152}Kdo to mùe bıt? Nìkdo s nabıdkou práce?
{8175}{8213}Co ten chlap chce?
{8314}{8361}Gene Starwind?
{8369}{8397}Tak to bude.
{8404}{8462}Nic osobního, ale pøišel jsem tì zabít.
{8470}{8501}Jsi pirát?
{8504}{8545}A kdyby?
{8555}{8617}Pro zaèátek se tì zeptám na jméno.
{8642}{8675}Jmenuji se Shimi.
{8687}{8746}Chci si s tebou zahrát takovou malou hru.
{8756}{8786}Hru?
{8790}{8836}Vyzıvám tì na souboj.
{8844}{8907}Zítra v poledne na tebe budu èekat na kopci Monkoku.
{8916}{8965}Pøines si zbraò jakou jen chceš.
{8969}{9045}Pokud odmítneš, zabiju tvoje pøátele.
{9052}{9102}Ta tvoje hra není moc taktní.
{9126}{9210}Pøíjdeš si sem, øekneš aby jsem vylezl a potom mì vyzveš.
{9234}{9273}Jde mi to na nervy.
{9276}{9322}Mì by vyhovovalo, kdyby si to chtìl vyøešit pøímo tady!
{9544}{9588}To není špatné na malého chlapa.
{9596}{9673}Vdy se snaím bojovat fér.
{9674}{9742}Mnì se vùbec nezdáš a tak èestnı.
{9752}{9813}Zabiju tì a zlepším si tak jméno.
{9823}{9888}Zabil jsi nás u pøíliš mnoho.
{9898}{9976}To sedí. Myslím, e jsem dost populární.
{9981}{10014}Opravdu ,je to tak.
{10060}{10108}Dneska jsi mìl štìstí.
{10117}{10174}Ale zítra to tak nebude.
{10193}{10253}Já nejsem jako ti ostatní zabijáètí chudáèkové.
{10276}{10321}A jakı teda jsi?
{10329}{10362}Já jsem já.
{10368}{10482}Ale pokud mì zítra porazíš,|øeknu ti to.
{10511}{10549}Pokud budu ještì naivu.
{10600}{10641}Gene, chceš tam jít?
{10668}{10695}Ó ano.
{10844}{10864}Gene?
{10922}{10941}Gene!
{10982}{11004}Co je?
{11007}{11053}Nemìl by jsi se pøipravovat?
{11062}{11073}Na co?
{11074}{11099}Na souboj!
{11106}{11165}Jak se pøipravuje na souboj?
{11168}{11190}Ale...
{11195}{11273}Bez obav, Jamesi.|Spravedlivost vdy zvítìzí.
{11353}{11373}Tady skus to?
{11378}{11434}Jsi si tím jistı?
{11481}{11528}Zajdu si na drink.
{11934}{12000}To bude v poøádku, Jime. Gene je silnı.
{12009}{12028}Jasnı...
{12035}{12151}Fakt? V porovnání s Ctarl-Ctarl,|není nic moc.
{12343}{12402}Èau! Popijíš sám?
{12406}{12454}Nechceš jít nìkam jinam a pobavit se?
{12492}{12523}Ne dík.Dnes v noci ne.
{12525}{12618}Proè? Takovı fešák jako ty by nemìl vypadat tak deprimovanì.
{12622}{12702}Dnes ,poprvé v ivotì, mám chu pít sám.
{12705}{12735}Nudnı chlap.
{12751}{12780}Moná pøíštì.
{12840}{12902}Pokud bude nìjaké Pøíštì.
{13026}{13069}Co je tady legraèní, šéfe?
{13079}{13115}To nic. Promiò.
{13125}{13183}Nechtìl sem odposlouchávat.
{13197}{13291}Ale kdy se tak na tebe dívám, pøipomínáš mi mnì, kdy jsem byl mladı.
{13297}{13369}Ó boe, staøí lidé tohle øíkají vdy...
{13371}{13433}Hej, nebuï takovı. Poslechni.
{13447}{13566}Co kdyby jsme se napili spolu jako zástupci lidstva?
{13590}{13685}Zdá se, e dnes kadı èlovìk na této planetì chce pít se mnou.
{13694}{13776}Mìl by jsi poslechnout, co ti praví starší...
{13820}{13864}Moje jméno je Gene Starwind.
{13866}{13934}Kdy jsi mladı, dìláš ze sebe chytrého,
{13940}{13992}pøesto nedokáeš nic, èím by jsi to podloil.
{14028}{14091}Máš drsnı spùsob jak hovoøit s lidmi.
{14095}{14173}Jsem Leilong.|Rád tì poznávám.
{14201}{14281}Všechny systémy na Outlaw fungují normálnì.
{14316}{14373}Take on opravdu nikde nic nenastrail...
{14394}{14489}Znamená to, e to opravdu bude férovı souboj?
{14497}{14605}Moná se obávají mého neproniknutelného obranného systému.
{14622}{14685}To je dobré... Stroje pøece nemají ádné obavy.
{14689}{14750}No dovol? Co tím myslíš?
{14757}{14849}Zøejmì tì budem muset upgradovat, aby jsi pochopil.
{14863}{14916}Jinımi slovy, potøebuješ peníze.
{14928}{14974}Potøebujeme peníze na údrbu lodì...
{14977}{15021}Ohroují nás piráti...
{15042}{15103}Proè je to všechno takhle?!
{15113}{15215}Mel! Co dìláš?|Pojï sem rychle a pomáhej!
{15266}{15287}U bìím!
{15371}{15448}Tohle je specialita Ctarl-Ctarl!|Guláš Gejidabo!
{15454}{15500}He? Kde je Gene?
{15514}{15576}Pokud to sníte, dodá vám to sílu pìti muù!
{15578}{15605}Tak moment.
{15615}{15697}Kdy to lidé snìdí, pøeijí to?
{15704}{15733}Samozøejmì!
{15735}{15761}Nevdìèníku!
{15771}{15825}Mimochodem, pùvod guláše Gejidabo sahá...
{15829}{15878}...a do prvního roku kalendáøe|Ctarl-Ctarl, kdy v dìdinì--
{15906}{15983}Chci øíct, e jeden z nás zítra zemøe!
{15994}{16035}Myslím, e je to tak.
{16038}{16101}Ty u jsi mìl nìkdy souboj?
{16177}{16225}Jo. Mìl.
{16254}{16309}Take jsi ho pøeil, co?
{16310}{16443}Nechci se zpovídat, ale tehdy jsem nemìl na vıbìr.
{16466}{16546}Svım spùsobem, prokazujem úctu tìm, kteøí zemøeli.
{16578}{16621}Úctu? Úctu, he?
{16665}{16719}Zemøít znamená konec, e?
{16754}{16826}Jo. Mì záleí na mém ivotì.
{16842}{16891}Proto jsem stále naivu.
{16916}{16998}No, nemám v úmyslu prohrát.
{17022}{17085}To povídali všichni.
{17140}{17193}Radši dnes skonèím.
{17206}{17235}Jdeš?
{17238}{17295}Pokud chceš ještì pít,|mùeš si dát z tohohle.
{17329}{17361}Hodnì štìstí.
{17825}{17866}Jsi v poøádku, Gene?
{18698}{18738}Co je s tebou?!
{18747}{18830}e si hraješ na "milé dìvèe", to je také jen nìjakı program?!
{18836}{18873}Naco jsi, ksakru, byla vyrobena?!
{18875}{18916}Nevím! Nevím!
{18978}{19046}Gene, povídal jsi, e to zjistíme spoleènì...
{19222}{19249}Kruci...
{19352}{19427}Naco, ksakru, vlastnì ijem?
{19526}{19589}Není urèeno pro komerèní pouití.
{19590}{19667}Ze Slovenskıch titulkù: A-H-Sarvill
{19767}{19870}ít znamená zatlaèit ostatní bokem.
{19884}{19919}Moná.
{20264}{20374}Promiò, Gene Starwinde. Chce se mi ještì ít, to je vše.
{21065}{21133}Tohle je moná poslední vejce, které jím.
{21138}{21178}Pøestaò. To není sranda.
{21182}{21244}Bylo by lepší, kdyby jsi vyhrál.
{21246}{21321}Ale pokud prohraješ, Aisha tady dohlédne na vše místo tebe!
{21326}{21379}Jdi pracovat a vydìlávat peníze!
{21400}{21448}Kadopádnì, nedej se!
{21450}{21492}Ta enská nemá ádnej takt...
{21515}{21544}Dobré ráno.
{21546}{21567}Dobré!
{21707}{21775}Gene, vyhrajem nad tím chlapem,|za kadou cenu.
{21783}{21806}Jasnı.
{21822}{21858}Sranda právì zaèíná.
{22058}{22085}Jsi tu brzo.
{22094}{22168}Je nezdvoøilé nechat hosta èekat.
{22186}{22237}Odejdu, co nejdøív,|pokud ti to nevadí.
{22250}{22288}Z tohoto ivota.
{22339}{22361}Jdem na to.
{22364}{22386}Jistì.
{23034}{23060}Poèkej...
{23074}{23184}Nechci tady zanechat takovéhle uboze vypadající tìlo...
{23387}{23417}Tak jak jsem oèekával.
{23427}{23503}Zdá se, e jsem jedinı, kdo se o tebe dokáe postarat.
{23522}{23616}To jsi ty, Leilongu? Máš i skuteèné jméno, e?
{23625}{23702}Leilong je moje skuteèné jméno.|Moje obchodní jméno je Shimi.
{23716}{23778}Take, ten chlap byl tvùj poskok, e?
{23786}{23853}Popravdì, byl spíš nìco jako ák.
{23870}{23917}Nemìl ádnı talent, proto zemøel.
{23937}{23970}To je vše, na èem záleí.
{23972}{24037}Nelíbí se mi tvùj tón hlasu!
{24306}{24319}Jime!
{24328}{24382}Gene! Štít toho chlapa je silnı!
{24389}{24412}Pouij Caster!
{24445}{24481}U mám pouít tajnou zbraò?
{24483}{24501}Jsi zranìnı?
{24502}{24563}Støela mì jen škrábla,|ale ten náraz mi zlomil ebro.
{24577}{24608}Trochu mì to spomaluje.
{24678}{24709}Mám tì!
{24869}{24885}Skvìlé!
{24887}{24922}Je po nìm?
{25031}{25107}Caster, co? Máš zajímavé hraèky.
{25157}{25174}Tu máš!
{25304}{25422}Neèekal jsem, e by to vydrelo jen tak zásah z Casteru...
{25454}{25482}Co je to za chlapa?!
{25626}{25657}Game over.
{25683}{25734}Dovolím ti odejít.
{25764}{25800}Ty to nechápeš.
{25823}{25894}Kdy jsi pøesvìdèen, e jsi ve vıhodì, pøestaneš se krıt.
{25914}{25960}Dokud boj neskonèí, nikdy nepøestávej bıt ve støehu.
{26194}{26262}Tohle je konec hry, Gene Starwinde.
{26348}{26401}Zbohem, Gene.
{26409}{26432}Poèkejte!
{26455}{26502}Gene a já jsme paráci.
{26503}{26550}Bojovat s ním bez hendikepu není fér!
{26554}{26585}Já si to také myslím!
{26596}{26621}Melfino?
{26630}{26678}Gene je pro mì dùleitı!
{26685}{26785}Pokud mu chcete vzít ivot,|tak zabijte nejprve mì prosím.
{26854}{26917}Melfino, nemùu tì zabít.
{26938}{27008}Ale zabiju ostatní, tam kde stojí.
{27010}{27057}Zadr! Okamitì zadr!
{27075}{27183}Pokud zemøe, budeš mít problémy s Ctarl-Ctarl.
{27226}{27273}Já za ním stojím také.
{27278}{27369}Geneho ivot je momentálnì v mém vlastníctví.
{27374}{27431}Nelíbylo by se mi, kdyby jste si ho chtìl vzít.
{27452}{27489}Jste dobøí pøátelé.
{27549}{27597}Ale ani tak nemùete vyhrát.
{27600}{27629}Nechci to poslouchat!
{27794}{27811}Aisho!
{27816}{27838}Bastarde!
{27869}{27905}Jime! Uteè, ty hlupáku!
{27986}{28007}Jime!
{28050}{28079}Za to zaplatíš...
{28130}{28156}Unikl?
{28544}{28566}Suzuko!
{28582}{28686}Øíkal jsem ti.|Vy mì nedokáete porazit.
{28697}{28729}Ty jeden--!
{28748}{28770}Gene!
{28910}{28952}Zdá se, e se nemùeš hıbat.
{28965}{29034}Mì se to takhle také zdá nudné.
{29057}{29133}Co by jsi øekl souboji na jeden vıstøel?
{29153}{29217}Zdá se, jakoby tì to bavilo...
{29218}{29312}Lhal by jsem, kdybych øekl e ne, ale práce je práce.
{29625}{29648}Pøipraven.
{29763}{29787}Pojïme na to.
{29946}{29969}Gene!
{29995}{30021}Gene!
{30029}{30054}Gene!
{30138}{30168}Gene...
{30201}{30232}A co on?
{30371}{30430}Take, já jsem také hotov?
{30449}{30543}Umírám, protoe selhala zbraò...|Tomu se øíká smùla.
{30564}{30673}Pøeij je...|Pøeij Antenskou Sedmièku...
{30684}{30726}Antenskou Sedmièku?
{30737}{30803}Jo... Zùstalo jich šest.
{30890}{30976}Take mùj talent bylo jen štìstí?
{31002}{31081}Všichni jsou mrtví.|Stálo nás to mnoho...
{31083}{31138}To máš teda pravdu, Gene Starwinde.
{31158}{31182}-Jime?!|-Jime?!
{31210}{31259}Pro dnes je to u vše.
{31268}{31350}Zdá se, e ještì urèitì musím trénovat.
{31359}{31454}Kdyby jsem nesnìdla ten Ctarl-Ctarl guláš|a nepokazila si alùdek...
{31456}{31537}Suzu, tomu se øíká pøenášet vinu.
{31541}{31609}Neøíkej mi "Suzu", prosím.
{31612}{31701}Gene! Za tohle jsi mi také dluen!
{31712}{31762}Rychle vyøeš záhadu Galaktického Leyline...
{31764}{31811}...a dej mi ten poklad!
{31822}{31878}Co myslíte, proè takhle mluví?
{31886}{31933}Nemá ádnı takt.
{32034}{32115}Nezabil nás...|Moná to byl dobrı èlovìk.
{32169}{32220}Zbohem, Leilong.
{32346}{32417}Kèertu stebou Shimi...|Byl si nanic.
{32434}{32495}Nechejte to na nás, prosím.
{32516}{32709}Gene Starwinde, já,|Hazanko se s tebou chci støetnout.
{32878}{32947}Sakra, pochovali mì moc hluboko...
{33116}{33216}Kdy jsem je vidìl, zaèali mi v mysli pobíhat divné myšlenky...
{33286}{33386}Moná zauvauju a také se stanu potulnım Outlaw.
{33420}{33465}Mìj se, Gene.
{33580}{33686}Obloha, daleká obloha...
{33697}{33815}Šepotavı hlas...
{33838}{34102}Tvoje sny teï otáèejí kolem hvìzd.
{34126}{34385}Nikdy jsem nikde nebyla.
{34402}{34514}Tak jsem se cítila,
{34520}{34667}dokud jsem nespatøila pohled tvıch oèí.
{34674}{34893}V koutku mého srdce je jen kousek mìsíce.
{34910}{35206}Ale je dost jasnı, aby osvítil i tu nejuší cestu.

