{1}{1}23.976
{149}{233}Na domovskıch planetách|nejcivilizovanìjších ras,
{242}{324}existují starobylé ruiny,|které se nedají vysvìtlit.
{356}{405}Tıká se to, samozøejmì, Pozemšanù,
{410}{470}a také ruin Orogoriya na Ctarl-Ctarl.
{492}{538}Chrámu Zabundre Corbono.
{570}{614}Piyoyoronote na Silgry.
{654}{769}Nikdo neví, kdo ani jak ruiny postavil.
{801}{946}A ve vesmíru také existují ruiny,|které nenáleí ádné známé rase.
{974}{1049}Nìkteøí odborníci usoudili,|e by mohli bıt...
{1049}{1123}...vıtvorem starobylé,|vyhynulé rasy,
{1131}{1191}a e starobylé ruiny na Zemi|a ostatních planetách...
{1198}{1316}...by mohli bıt také jejich,|ale na to nejsou dùkazy.
{1356}{1471}Ruiny, zahalené tajemstvím,|tu tedy pøetrvávají a do dnešních dní.
{1598}{1680}Neobviòuj to, neniè to, nepodceòuj to...
{1680}{1801}...to jedineèné, co kadı má.
{1818}{1843}Moje láska...
{1843}{1869}Moje sny...
{1869}{1892}A té ty.
{1895}{2038}Nevzdám se toho, za ádnou cenu.
{2096}{2193}V té noci, kdy jsi nepokojnı,|kdy dìláš cokoliv,
{2196}{2307}...máš chu to vše odhodit pryè.
{2310}{2409}Neøíkej u nic, jen otevøi dveøe.
{2409}{2517}Nemám èas se tady|s tebou bavit.
{2522}{2631}Chci všude volnì letìt,
{2638}{2731}a nedbat v letu na opatrnost!
{2738}{2830}O nic jsem nepøišel,
{2830}{2924}vdy jsem ještì ani nezaèal.
{2932}{3013}Neobviòuj to, neniè to, nepodceòuj to,
{3015}{3134}...to jedineèné, co kadı má.
{3150}{3180}Moje láska...
{3180}{3209}Moje sny...
{3209}{3229}A té ty.
{3233}{3352}Nevzdám se toho, za ádnou cenu.
{3379}{3406}Co by jsi chtìl?
{3406}{3433}Co chceš dìlat?
{3433}{3485}Kam pùjdeš?
{3488}{3643}Vezmi co chceš, pøetni temnotu,|kdy budeš utíkat nocí!
{4029}{4056}To je ono?
{4056}{4107}To je Galaktickı Leyline!
{4114}{4189}Ještì døív, ne jsme vyrazili|sem øíkal e není!
{4196}{4249}Ale øíkal jsi, e to je Leyline!
{4255}{4335}Ne, je to planeta nazıvající se "Drak"|nebo "Cesta Draka",
{4335}{4385}na které jsou nìjaké starobylé ruiny!
{4388}{4428}A to je Leyline!
{4454}{4537}Kdyby byl, vıskumnı tım by|zanechal podrobnìjší správu!
{4541}{4634}Nespekuluj nad tím. Musíme se|na to podívat sami, ne?
{4640}{4686}Tak, kde pøistaneme?
{4714}{4765}Co takhle na stejném místì|jako prùskumnı tım?
{4773}{4851}Je tam rovina, take nemyslím,|e by to bylo pøíliš tìké.
{4866}{4900}Fajn, pøipravit na pøistání!
{4902}{4997}OUTLAW STAR:|"Hrob Draka"
{5142}{5198}Ale vdy tu vùbec nic není...
{5211}{5274}Není divu, e tady nejsou ádní obyvatelé.
{5287}{5334}Tak, kde je to, Jime?
{5334}{5404}Fakt, beze mnì nic nedokáeš,|e...?
{5418}{5464}Ale vdy si to našel, ne?
{5469}{5573}Bylo dost tìké hacknout se do databáze|Vesmírné archeologické spoleènosti.
{5587}{5647}Bylo to chránìno, jakoby to bylo|pøísnì tajné nebo co.
{5657}{5702}Co takhle trochu vdìènosti?
{5726}{5809}Fajn! Je to odtud asi|2 km na jihovıchod.
{5814}{5843}Dva kilometry?
{5894}{5979}Hej! Proè si se rozhodl pøistát tak daleko?
{6030}{6090}Si tak dobrı, e by si pøistál támhle?
{6262}{6356}Tak, co kdyby sme si udìlali malı vılet?
{6783}{6833}Fajn, dáme si pauzu.
{6978}{7068}Gene, co myslíš, co je vlastnì| ten Galaktickı Leyline zaè?
{7093}{7142}Proè se mì na to ptáš teï?
{7155}{7233}Jen mì napadlo, e ti moná|Hilda nìco øekla.
{7239}{7271}Vùbec nic.
{7278}{7417}Akorát to, e to chtìjí piráti Kei,|take ona to chtìla získat jako první.
{7421}{7458}Take je to poklad!
{7458}{7515}Jo, to by bylo fajn.
{7526}{7583}Potom by sem mohl zaplatit vše Fredovi!
{7586}{7646}Urèitì to musí mít vìtší cenu!
{7658}{7746}Jak se Ctarl-Ctarl dozvìdìli o Leyline?
{7769}{7817}To je, to je... Tohle je...
{7821}{7852}Státní tajemství!
{7860}{7933}A ty to tajemství neznáš, e?
{7939}{8018}Pøišla si jen proto, e ti to pøikázali?
{8023}{8049}Sklapnìte!
{8071}{8107}Oèividnì to tak je.
{8129}{8229}Mám trochu obavy, jak dlouho se|ješte budeme povaovat za pøátelé.
{8239}{8271}Co tím myslíš?
{8278}{8351}Øíkám tím, e je stále pøíslušnicí|impéria Ctarl-Ctarl.
{8414}{8481}Nemyslíš, e by sme to prozatím mohli odloit?
{8490}{8546}S tebou je to stejné.
{8546}{8606}Opravdu mám nìjaké nedostatky?
{8622}{8671}Momentálnì ne.
{8680}{8726}Ja mıslím, e nebudou ani potom.
{8726}{8758}Jistì...
{8801}{8826}Co je?
{8834}{8859}Nic.
{8859}{8889}Ven s tím.
{8912}{9018}Kdy najdeme Galaktickı Leyline,|dozvím se i nìco o sobì?
{9024}{9085}Dobrá otázka. Sám nevím.
{9094}{9159}Co povídáš, Gene?|Urèitì se dozví!
{9183}{9213}e, Mel?
{9293}{9348}Nebudu to vìdìt jistì dokud se tam nedostaneme.
{9388}{9423}To je pravda.
{9440}{9466}Gene!
{9518}{9551}Našla sem to!
{9555}{9620}Hej! Pojïte se podívat!
{9652}{9712}To jsou ruiny Leyline!
{9914}{9984}Fakt si museli vybrat další divnou planetu.
{9997}{10029}Pùjdem dolù, bráško.
{10034}{10091}Tentokrát bude urèitì moje...
{10099}{10185}Jistì, vdy proto sme je celou tu cestu sledovali.
{10192}{10223}Dokonèíme to.
{10729}{10764}Úasné...
{10862}{10957}To uprostøed nazıvají Draèí sfinga.
{10970}{11030}Èára, která k ní vede je Cesta Draka.
{11051}{11106}Tak proto to nazıvají Leyline...
{11134}{11252}Vıskumnı tım odhadl, e to bylo|vytvoøeno asi pøed 10 000 lety.
{11329}{11402}Proè vıskumnı tım ukonèil prùskum?
{11426}{11490}Oficiální dùvod udává, e jim došli finance...
{11490}{11567}...døív ne mohli získat nìjaké vısledky.
{11584}{11652}Nepøímo do toho byli zapleteni piráti Kei.
{11659}{11700}Co to znamená?
{11714}{11809}Piráti pøerušili zásobovací|trasy tımu.
{11816}{11889}Zdá se, e byli pøinuceni odejít.
{11897}{11969}Místo zvané Leyline a piráti Kei...
{11980}{12031}To je podezøelá shoda.
{12126}{12164}Zjistil si o tom nìco?
{12171}{12256}Vùbec nic. Nebylo to ani v databázi.
{12302}{12383}Vıskumnı tım proskoumal|vstupní komoru do pyramidy,
{12391}{12438}ale nejsou o tom záznamy.
{12438}{12554}Hej! Co má tahle vìc spoleèného|s Galaktickım Leyline?
{12566}{12634}Vdy proto jsme tady ne? Aby jsme| na to pøišli!
{12650}{12756}Tak, skontrolujme ubytovnu vıskumného tımu,|jestli tam není nìco uiteèného.
{13040}{13066}Pøipravenı, bráško.
{13076}{13191}Poèkáme do soumraku a potom zaútoèíme.|Nejprve tu enu.
{13205}{13263}Všechny ostatní mùeme zabít,e?
{13275}{13301}Jistì.
{13623}{13688}Hej, proè je tohle místo tak dùleité?
{13710}{13740}Podívej se na podlahu.
{13755}{13839}Øíkali, e to ukazuje,|e pùvodne tam nìco mohlo bıt.
{13872}{13911}Co jako?
{13921}{13986}To nikdy nezjistili.
{13997}{14097}"Leyline" je pùvodnì termín|pouívanı vesmírnımi piráty.
{14106}{14181}Pochází z feng-shui, pøedstavuje cestu,|po které proudí chi.
{14186}{14253}Take Leyline je místo,|kde se zhromaïuje chi.
{14262}{14321}To nám doopravdy nic neøíká.
{14338}{14385}Hej, já tomu taky nerozumím.
{14385}{14506}Ale øíká se, e ovládnout Leyline|znamená ovládnutí všeho.
{14530}{14554}Co je, Mel?
{14592}{14646}Cítím, e odtud nìco pøichází.
{14655}{14687}Co cítíš?
{14708}{14756}Nevím. Jen...
{14918}{14947}Co to bylo?!
{14966}{14989}Mel!
{15006}{15045}Ani sama nevím.
{15071}{15134}Teï necítím nic.
{15234}{15260}Kde je Melfina?
{15260}{15308}Ríkala, e chce bıt na chvilku sama.
{15308}{15355}Zøejmì si šla odskoèit...
{15395}{15446}Pokud chtìla jít na záchod,|tak ten je támhle.
{15446}{15478}Kdoví, co se s ní dìje?
{15478}{15574}Nevšímej si to, Jime.|Pokud chce bıt sama, tak jí nech.
{15589}{15668}Gene, jak mùeš bıt k Melfinì|tak hrubı?
{15678}{15705}Nejsem.
{15705}{15733}Ale si!
{15733}{15795}Chováš se divnì od doby| co jsme odešli hledat Leyline!
{15818}{15842}Co tím myslíš?
{15850}{15898}Je to jakoby si se Melfinì vyhıbal.
{15898}{15923}Sem takovı.
{15926}{15953}Takovıhle ne!
{15953}{15988}Ano jsem.
{16090}{16117}Kam jdeš?
{16117}{16154}Chci bıt sám.
{16204}{16258}Ve skuteènosti s Jimem souhlasím.
{16285}{16305}Opravdu se mılí?
{16405}{16459}Opravdu nechci øíkat, e mì to mrzí,
{16459}{16518}a i kdyby, k èemu by to bylo dobré?
{16534}{16567}Co tì mrzí?
{16582}{16701}Dal sem Melfinì slib,|ale zatím není vidìt ádnı pokrok.
{16701}{16745}Slib?
{16766}{16830}e o ní nìco zjistím.
{16924}{17074}Jednoho klidného dne,
{17089}{17261}vítr byl èerstvı a svìí.
{17281}{17611}Kvìty se chvìli, jakoby spali.
{17630}{17868}Ten pocit pokoje...
{17884}{18304}Tak, jaké mu lidé dali jméno?
{18410}{18441}Harry MacDougall...
{18523}{18582}Pojï se mnou.
{18610}{18650}Já tì nikdy nenechám osamìlou.
{18734}{18797}Není urèeno pro komerèní pouití.
{18799}{18875}Ze slovenskıch titulkù: A-H-Sarvill
{18961}{19057}Dìlal sem frajera a øekl jí,|e najdu odpovìï, ale nic sem nedokázal.
{19066}{19109}Tak to není.
{19116}{19193}Pøišel si a sem na toto místo,|aby si ho proskoumal.
{19290}{19319}Co se dìje?
{19324}{19361}Jdu na záchod...
{19465}{19569}Podle toho, co øíkal MacDougall,|byla Melfina vytvoøena jako souèast...
{19569}{19639}...navigaèního systému pro|dosáhnutí Galaktického Leyline.
{19656}{19732}Ale je to odpovìï, kterou chce opravdu slyšet?
{19783}{19852}To urèitì ne.|To vím.
{19863}{19892}Ale i tak...
{19922}{19969}Osamìlá? Já?
{19978}{20017}Ano. Pøesnì tak.
{20017}{20043}Tak to není.
{20043}{20128}Dám ti vše co chceš.
{20147}{20177}Ty?
{20177}{20220}Pøesnì tak! Já!
{20265}{20343}Myslel sem si, e se dozvíme víc,|kdy dosáhneme Leyline.
{20346}{20410}Nevím ale jak to bude cítit ona.
{20454}{20533}Nejsem si si jistı, jestli to má nìco|spoleèného s odpovìdí, kterou hledá.
{20549}{20601}Ale ty nemáš jinou monost,|ne tam jít, e?
{20615}{20658}Ale za tìchto okolností tam jít nemùeme.
{20698}{20745}To ty jsi osamìlı.
{20754}{20802}Já? Nebuï smìšná.
{20809}{20870}Mám bratra. A mám také pøátelé.
{20891}{20932}jsi osamìlı.
{20942}{21024}Jediné, co dokáeš je vzít si, co chceš.
{21042}{21089}To, co chci jsi ty.
{21174}{21203}Pojï.
{21314}{21371}Moná e jsem k ní byl trochu necitlivı...
{21402}{21518}Akorát sem si nebyl jistı,|jestli dokáu dostát svého slibu.
{21543}{21590}Jsi na sebe moc pøísnı.
{21617}{21669}Kdyby sem se tak nechoval,|nemohl bych bıt mu.
{21802}{21829}Poï.
{21878}{21950}Mám u nìkoho, kdo mi dal slib.
{21960}{22055}Nìkoho, kdo mi dal slib,|e najde to, co hledám.
{22065}{22107}Gene Starwind?
{22130}{22176}Zapomeò u na toho chlapa!
{22186}{22213}Nemohu.
{22219}{22297}My dva jsme jediní, kteøí si skuteènì|dokáou porozumìt!
{22305}{22381}Já... Já vlastnì nerozumím ani sama sobì.
{22406}{22426}Melfino...
{22426}{22450}Pøestaò.
{22499}{22565}Zazpívej mi ještì.|Zazpívej tu píseò.
{22572}{22609}Harry MacDougall!
{22626}{22667}Co to dìláš?!
{22880}{22924}O èem ste si povídali?!
{22924}{22945}Gene...
{22951}{22995}Je mezi vámi nìco?!
{23104}{23176}Si mrtvı mu, Gene!|Melfina je moje!
{23185}{23239}Tvoje? To si ze mì dìláš srandu ne ?!
{23536}{23617}Netrap se tím, chlapèe.|Dospìlí jsou komplikovaní.
{23628}{23670}Nechovej se ke mnì jako k dítìti!
{23670}{23709}Si dítì..
{23721}{23803}Mìl by sis uívat ivota|a netrápit se pøitom tolik.
{23824}{23884}Velká slova od nìkoho,|kdo se sám moc nelíší od dítìte.
{23905}{23925}Co je to?
{24235}{24253}Gene!
{24485}{24507}Ty...!
{24723}{24742}Kruci!
{24882}{24965}Gene! Kam si utekl? Vylez!
{25129}{25150}Sorry, nikdo není doma :)
{25211}{25236}Nejdøív se zvoní...
{25286}{25311}Je konec!
{25451}{25494}Zemøi! Zemøi!
{25668}{25702}Gene!
{26192}{26214}Co to--?
{26219}{26241}To je--
{26241}{26279}Zemìtøesení!
{26437}{26457}Pojï!
{26502}{26536}Tak vylez!
{26597}{26641}Co to--? Kruci!
{26641}{26676}Tak vydr!
{26850}{26896}Myslím e tentokrát neminu.
{26990}{27029}Harry! Harry!
{27037}{27069}Co se stalo?! Odpovìz, Harry!
{27166}{27212}Proè to zaèalo teï?
{27220}{27276}Jime! Vra se spìt na Outlaw Star!
{27353}{27426}Rychle, všichni! Porucha podloí!
{27440}{27494}Jestli to bude pokraèovat pøevrátí se loï!
{27632}{27741}Melfino... jesli nechceš,|nemusíš jít s námi.
{27766}{27815}Jen co se dostaneme do vesmíru,|mùeš si dìlat, co chceš.
{27834}{27902}Hej! Gene! Co dìláš?!
{28032}{28075}Vezmi mì sebou,prosím.
{28152}{28196}Vezmi mì sebou,prosím Gene.
{28206}{28254}Samozøejmì. Vezmu.
{28279}{28332}Vezmu tì sebou kdykoliv.
{28338}{28359}Dìkuji.
{28773}{28871}Povrch se stále otøásá.|Ruiny jsou v troskách...
{28894}{28958}Zdá se Mel, e budeme muset|najít jinou stopu.
{28958}{28982}Ano.
{28992}{29021}Harry!
{29070}{29092}Harry!
{29134}{29173}Vydr, Harry!
{29212}{29269}Harry... Co se stalo...?
{29541}{29580}Nejprve doplníme zásoby a odpoèineme si.
{29587}{29631}Potom rozhodneme, co dál.
{29637}{29721}Zachytil sem vysílání.|Je to profesor Gwen Khan.
{29734}{29792}Khan? Je to v reálném èase?
{29792}{29841}Vysílaní je ze stanice.
{29858}{29924}Aj jaj! U sem na vás èekal!
{29936}{29988}Uhm, cítil sem, e se tu zastavíte.
{29997}{30047}Ok Khane ,co tu vlastnì dìláte?
{30053}{30091}Stejnì by sem mohl zeptat já.
{30102}{30177}Putuji z velké dálky|a koneènì sem vás dostihl.
{30183}{30234}Nebylo to jednoduché, aby jste vìdìli!
{30240}{30311}Sem zvìdavı, jak nás mùe|stále sledovat?
{30316}{30384}Dobrá otázka. eby na nás|umístil vysílaè?
{30393}{30449}Ale, ale! Jak jste to vìdìli?
{30458}{30490}Co tím myslíte?
{30490}{30542}Ještì pøi navrhovaní XGP.
{30542}{30656}Pøi navrhovaní... Nu, není to vysílaè,|ale je to podobné.
{30664}{30713}Opravdu! Ještì v etapì návrhu.
{30730}{30803}Ale udìlal sem to tak,|aby o nìm nevìdìl nikdo jinı...
{30815}{30879}Hej, poèkat! V jaké|"etapì návrhu"?!
{30885}{30946}Zapomìòte na to, našel sem nìkoho,|kdo zná...
{30946}{31001}...souøadnice Galaktického Leyline.
{31008}{31034}Opravdu sem našel.
{31046}{31089}Radìji zaènìte tím, e se zeptáte na nìj.
{31094}{31165}Faktem je, e je momentálnì| ve vìzení Gehenna.
{31169}{31216}Byl toti odsouzen na 300 let.
{31216}{31256}Nemá povolené návštìvy.
{31256}{31355}Take se tam budete muset dostat|a zeptat se ho na souøadnice.
{31359}{31396}Tak, tak... Tak to je.
{31407}{31497}Co to breptáte?|Já do ádného vìzení nepùjdu!
{31510}{31565}Ale on zná souøadnice!
{31576}{31641}Urèitì existuje i nìkdo jinı,|kdo je zná!
{31654}{31733}Ano, ale ti druzí jsou| vysoko postavení piráti Kei...
{31739}{31797}...a já se s nimi nehodlám zaplést!
{31805}{31854}Nemùu se s nimi zaplést!
{31862}{31909}Tak se zapletu já.
{31926}{31996}Moc se mi nechce vìøit tìm|vašim divnım øeèem.
{32006}{32044}Gilliame, priprav se na start.
{32048}{32097}U? Vdy sme sotva dorazili.
{32107}{32133}Poèkejte moment. Jste blázni?
{32141}{32173}U sem se rozhodl!
{32186}{32274}Dosud jsme se dreli mimo teritorium Kei,|ale teï se chystáme vejít dovnitø.
{32282}{32361}Pùjdu tam a pøinutím je, aby mi|øekli tajemství Galaktického Leyline!
{32370}{32406}Èekej, ty blázne!
{32414}{32436}Zapomeò!
{32441}{32461}Melfino!
{32474}{32523}Zadání pøíkazu do Projektu Leyline!
{32527}{32586}"To ty jsi rozbila mùj Meissenskı štít!" 
{32644}{32665}Mel?
{32683}{32772}To já sem vytvoøil její øídící|systém a pøíkazy.
{32781}{32833}Pozastavil sem v Melfinì osobnost.
{32838}{32881}Ty bastarde! Co máš v úmyslu?!
{32884}{32929}Vra Melfinu spìt do normálu!
{32939}{32986}Vrátím, neboj.
{32994}{33087}Jen co zjistíš v tom vìzení souøadnice Leyline.
{33096}{33125}Ty jeden...
{33358}{33465}Obloha, daleká obloha...
{33476}{33594}Šepotavı hlas...
{33618}{33881}Tvoje sny teï otáèejí kolem hvìzd.
{33906}{34163}Nikdy jsem nikde nebyla.
{34181}{34293}Tak jsem se cítila,
{34298}{34447}dokud jsem nespatøila pohled tvıch oèí.
{34454}{34680}V koutku mého srdce je jen kousek mìsíce.
{34685}{34985}Ale je dost jasnı, aby osvítil i tu nejuší cestu..
