{1}{1}23.976
{84}{193}Gene Starwind. Jim Hawking.|Melfina.
{219}{317}Suzuka. Aisha Clanclan.|Fred Luo.
{349}{468}Ron MacDougall. Harry MacDougall.|Gwen Khan.
{493}{652}Hazanko. Hitoriga. Hamushi.|Jukai. Tobigera.
{686}{796}Outlaw Star. Geomancer.|Shangri La.
{822}{873}Tak, úèinkující se shromádili!
{873}{941}Ukáu vám, co je Galaktickı Leyline!
{950}{1021}Coe? Pokud to víte,|nemuete bıt pøekvapeni.
{1036}{1110}Kdy se záhada vyøeší,|pøestává bıt záhadou...
{1110}{1160}...a také nìco|co se chcete dozvìdìt.
{1170}{1245}S tímto pøesvìdèením lidé vyhledávají|záhady, protoe rádi øíkají,
{1248}{1333}"Oh! Take, tak to bylo!"
{1349}{1464}Opravdu. Tohle je jedna ze záhad,|o kterıch se chcete dozvìdìt,
{1469}{1583}a já vám pomùu najít odpovìdi.
{1698}{1780}Semenaide, kesanaide, makenaide...
{1780}{1901}...daredatte motteru hazu yuzurenai mono.
{1919}{1995}Ai dake, yume dake, kimi dake...
{1995}{2136}...sore dake wa hanasanai,|donna toki de mo.
{2193}{2295}Dou shiyou mo naku, ochitsukanai yoru...
{2295}{2409}...nani mo ka mo nagedashitaku naru.
{2409}{2509}Tsubekobe iwazuni,|sassa to doa wo akena.
{2509}{2617}Rikutsu nante, koneteru hima wa nai.
{2625}{2830}Juu'ou-mujin tobimawaritai,|you'i-shuutou mamoritakunai!
{2836}{3017}Nakushita wakeja nai,|mada hajimattenai dakara.
{3033}{3118}Semenaide, kesanaide, makenaide...
{3118}{3236}...daredatte motteru hazu yuzurenai mono.
{3253}{3334}Ai dake, yume dake, kimi dake...
{3334}{3453}...sore dake wa hanasanai,|donna toki de mo.
{3482}{3584}Nani ga hoshii? Nani ga shitai?|Doko ni ikitai?
{3590}{3742}Yami wo saite hashirinukete|tsukamitore through the night!
{4005}{4106}Gene, Jime, jak se máte?|Tady jdou obchody dobøe.
{4133}{4221}Sem vám za to moc vdìènı.
{4251}{4353}Proto nadále souhlasím s vašimi|opakovanımi ádostmi o finanèní vıpomoc,
{4366}{4489}ale nezapomínejte, e peníze, které posílam|jsou z mé strany jen investicí.
{4515}{4565}Tak, èekám od vás dobré správy.
{4668}{4696}Vidíš? Co sem ti øíkal?
{4702}{4769}Opravdu doufám, e v tom|Galaktickém Leyline bude poklad.
{4789}{4833}Jinak to Fredovi nesplatíme.
{4866}{4917}Kolik nábojù se ti podaøilo sehnat?
{4922}{5026}Mám dvì ètyøky, a po jedné|devítku a tøináctku.
{5034}{5089}Ale tyhle jsou dùleité.
{5107}{5153}Ještì nikdy pøedtím si je nemìl, e?
{5155}{5230}Ètyøka, devítka a tøináctka...
{5239}{5311}Øíkali, aby sem nestøílel|tyhle tøi typy nábojù za sebou.
{5327}{5412}Varovali mì, e pokud to udìlám|vyèerpám svojí ivotní sílu.
{5421}{5449}To sotva...
{5458}{5513}To by sem si i já rád myslel...
{5550}{5642}Øíkali, e jsou pøíliš silné a vysají|ivot z kadého, kdo je vystøelí.
{5671}{5701}Není moná...
{5719}{5743}Gene...
{5778}{5828}Hej...notak,nekoukaj tak na mì.
{5828}{5849}Ale...
{5852}{5901}Nedostaneme se do situace,|kdy budem muset støílet...
{5901}{5952}...tak silné náboje vícekrát za sebou.
{6046}{6106}Øíkali mi, e zásoby jsou u doplnìny.
{6112}{6152}Promiòte!Poèkejte!Omluvám se za spodìní!
{6166}{6215}Aisha se u o vše postarala!
{6220}{6248}Dobrá tedy.
{6260}{6302}Vydejme se na cestu.
{6311}{6358}Galaktickı Leyline èeká.
{6359}{6448}|OUTLAW STAR:|"Prùnik do Galaktického Leyline"
{6584}{6630}Jak se cítíš, Harry?
{6646}{6741}Dobøe. Mùu si dìlat s lodí,|co chci.
{6758}{6863}To není vše. Ne, to není.
{6874}{7022}Mìl by si bıt schopen navigovat|do Galaktického Leyline, tak jako Melfina.
{7028}{7066}Nemìj obavy.
{7066}{7128}Líbí se mi, kdy mì k ní pøirovnáváte.
{7138}{7217}Profesore Khane, nepodstoupil sem|všechny ty problémy,
{7222}{7296}aby sem vás našel, jen aby ste|zachránil Harryho.
{7296}{7389}Rozumím, Rozumím.|Rozumím, samozøejmì.
{7395}{7547}Nikdy by sem vám nepomáhal,|kdyby mì tam ti lidé nezanechali.
{7558}{7613}Máme spoleèné zájmy.
{7617}{7657}Tak, tak... je to tak!
{7667}{7757}Mùj vysílaè na Outlaw Star|funguje perfektnì.
{7764}{7836}Pokud je budeme sledovat,|dostaneme se a k Galaktickému Leyline!
{7849}{7896}Èekej na mì, Melfino...
{8924}{8962}Pokraèujte!
{9114}{9143}Hazanko!
{9162}{9266}Co to má znamenat?|Neøídíte se rozkazy krále Tendo!
{9266}{9314}Jistìe ano.
{9322}{9452}Našel sem cestu k Leyline,|jak bylo pøikázáno, to je vše.
{9460}{9531}Tak proè jste to nenahlásil králi Tendo?
{9542}{9594}Proè otvíráte Leyline sám od sebe?
{9617}{9720}Nemáš jine ambice,|ne se stát královım oblíbencem?
{9728}{9771}Jak sem pøedpokládal, Hazanko!
{9780}{9888}Máš v úmyslu zradit krále a nechat|si Leyline pro sebe, e?!
{9902}{9950}Nejenom krále Tendo.
{9954}{10041}Moc Leyline pøekonává i císaøe Tenpa.
{10048}{10118}Ne, je ještì vìtší!
{10122}{10144}Chcípni!
{10324}{10389}Ty bastarde... Hazan--
{10500}{10529}Dokonèete to.
{10678}{10776}Pokud se pozorovatel nevrátí,|král zaène mít podezøení.
{10781}{10880}Tou dobou budu mít v rukou vše,|co Leyline obsahuje!
{10908}{10957}Ze subéterového prostoru vystoupila loï.
{10967}{11014}Smìøuje pøímo k Leyline.
{11082}{11120}To je-- To je nemoné!
{11120}{11158}XGP?
{11181}{11227}Tato oblast vesmíru je divná.
{11239}{11301}Elektromagnetické vlny,|gravitaèní vlny, éterové vlny...
{11306}{11346}Nic, co vysílám se nevrací.
{11346}{11398}Chceš øíct, e se ti nezobrazuje|nic na senzorech?
{11402}{11425}Pøesnì tak.
{11425}{11485}Máš poruchu zrovna, kdy máme|Leyline rovnou pod nosem?
{11485}{11525}Moje senzory fungují normálnì.
{11525}{11592}Na okraji této oblasti zachytávám lodì.
{11598}{11656}Lodì?! Proè si nic neøekl?!
{11661}{11696}Zvìtším to na monitoru.
{11769}{11834}Piráti Kei! Je jich spousta!
{11842}{11866}Pøepadení?
{11866}{11909}Zdá se, e je tam hodnì pracovních lodí.
{11931}{11966}To je Geomancer!
{11976}{12010}Poznáváš tu loï?
{12010}{12043}Je to loï mue jménem Hazanko,
{12043}{12121}o kterém se povídá, e je to obzvláštì silnı|Tao mistr a to i mezi vùdci Kei.
{12121}{12146}Hazanko?
{12146}{12264}Je to nebezpeènı mu.|A Anten pracují pro nìj.
{12278}{12324}Ta banda, co jde po nás?
{12347}{12425}Pirátské lodì vypouštìjí stíhaèky!|Velké mnoství!
{12443}{12480}Pøipravte se na boj!
{12782}{12875}Chyte XGP!|Získejte Melfinu!
{13059}{13089}Zkus tohle!
{13205}{13263}Snaí se nás udret mimo Leyline!
{13283}{13365}Ze subéteru vychází loï.|Je 700 kilometrù od pravoboku.
{13370}{13394}Posily?
{13394}{13421}Zvìtšuji.
{13449}{13500}Podívej na to... Máme trable.
{13500}{13534}Poèkat, není to--
{13545}{13626}To je plavidlo Vesmírné|flotily Impéria Ctarl-Ctarl,
{13636}{13725}køíník tøídy Nipopopolas,|Orta Honehone!
{13761}{13860}Impérium Ctarl-Ctarl získá Galaktickı Leyline!
{13877}{13945}Rozdrte kadého,|kdo se nám postaví do cesty!
{13950}{13998}Gagagan kanóny! Pal!
{14110}{14148}Co jsi to udìlala?!
{14170}{14260}Pokadé kdy jsme byli nìkde|v pøístavu, tak jsem kontaktovala Impérium!
{14267}{14330}Co?! Ty jsi jim dala|i souøadnice Leyline?!
{14335}{14448}Kdyby sem neøekla, kam jdu,|tak by o mì mìla moje rodina starost.
{14457}{14544}Vojenská loï Ctarl-Ctarl míøí|pøímo k Leyline.
{14554}{14607}Nechejte je, a si dìlají, co chtìjí.
{14622}{14735}Kdyby se jim podaøilo otevøít cestu k Leyline,|nemuseli jsme podstupovat všechny ty trable.
{14754}{14789}Vpøed! Vpøed!
{14789}{14845}Jsme neporazitelní Ctarl-Ctarl!
{14858}{14976}Nic nás nemùe zastavit!|Jsme neporazitelní Ctarl-Ctarl!
{14994}{15053}Nièeho se nebojíme!
{15113}{15133}Dokázali to!
{15142}{15218}To znamená, e poklad patøí|Impériu Ctarl-Ctarl!
{15230}{15293}Kruci...|Øíká ti nìco "fair-play?
{15346}{15392}Myslím, e nemá smysl|se nad tím rozèilovat.
{15467}{15497}Bastarde...!
{15559}{15621}Ja chci jít pøece také do Leyline!
{15638}{15702}XGP je opravdu vyjímeèná...
{15762}{15778}Co je?
{15788}{15826}Vracejí se!
{16038}{16109}Orta Honehone?|Proè se vrací?
{16116}{16177}Zdá se, jakoby støíleli náhodnì...
{16188}{16230}Klesnout, smìr 3 hodiny!
{16230}{16298}To je šílené!|Dostane se nám do cesty Orta Honehone!
{16310}{16364}To je naše jediná šance dostat se do Leyline!
{16451}{16489}Nepodaøí se nám vyhnout se všem!
{16504}{16539}Štíty na maximum!
{16696}{16723}Jdeme na to!
{16768}{16853}Vyšlo to, Gene!|Teï je cesta k Leyline volná!
{16869}{16975}Na svıch senzorech nic neregistruji.|Nemùu pøed námi nic detekovat.
{16987}{17005}Melfino?
{17012}{17065}Pøepni všechno ovládání na mì.
{17135}{17221}XGP úspìšnì pronikla do Leyline!
{17369}{17405}Detekuji novou loï!
{17465}{17492}Zachytávám vysílání.
{17502}{17564}Ale, ale, vdy je to Hazanko.
{17577}{17646}Jaké neoèekávané potìšení,|potkat vás na takovémhle místì.
{17650}{17696}Ronald MacDougall?
{17699}{17737}Co tu chceš?!
{17744}{17861}Sledoval sem XGP|a ona mì pøivedla a sem.
{17944}{18006}Není urèeno pro komerèní pouití
{18009}{18088}Z Aj. a Sk. titulkù A-H-Sarvill
{18173}{18302}Co zamıšlíš?|Hyeny jako ty sem nemají pøístup.
{18304}{18332}Hyeny?
{18341}{18390}Ne, my jsme lovci.
{18403}{18510}Jdeme po XGP a všem,|co Leyline mùe nabídnout.
{18518}{18615}Tak, tak, ...|Znalost vesmíru bude moje.
{18622}{18653}Gwen Khan?!
{18662}{18727}ádnı z mıch senzorù|nic nezaznamenává.
{18738}{18810}Nemám pøedstavu, co se dìje okolo lodì.
{18828}{18859}Stav lodì?
{18859}{18892}Vše v poøádku.
{18966}{19008}Co je to za zvuk?
{19015}{19055}Zvuk? Jakı zvuk?
{19058}{19100}Ja nic nedetekuji.
{19176}{19233}Jakoby mi nìco chtìlo otevøít hlavu!
{19233}{19269}Mel! Co se dìje?!
{19276}{19322}Poèkej. Poèkej, prosím.
{19330}{19384}Vydrte, všichni!
{19399}{19466}Shangri La vstupuje do Leyline.
{19482}{19557}Nemùu uvìøit, e Gwen Khan je s nimi...
{19582}{19605}Kolik?
{19610}{19653}U zùstává jen jeden.
{19717}{19771}Ja nic necítím!|Vùbec nic!
{19867}{19906}Tohle je spirála.
{20026}{20075}Upravila sem navádìní lodì.
{20085}{20119}Tohle nás tam dovede.
{20142}{20167}Melfino?
{20171}{20237}Tohle nás dovede do støedu Leyline.
{20305}{20351}C-C-Co se to dìje?!
{20363}{20426}C-Co se to dìje?!
{20451}{20477}H-Harry?!
{20484}{20549}Vše je v poøádku, bráško.|Vím co dìlám.
{20562}{20594}Vidím cestu.
{20618}{20670}A ona je na jejím konci...
{21458}{21497}J-Je to ovìøené.
{21504}{21567}Jdeme do Galaktického Leyline!
{21745}{21775}Mel, jakı je náš stav?
{21784}{21832}Vıkon motorù 70%.
{21838}{21913}Jdeme po spirálovité|dráze vedoucí do støedu.
{21931}{21992}Bez tebe by jsme nevìdìli,|kam jdeme, Mel.
{22007}{22031}Pravda.
{22058}{22124}Take Orta Honehone to nedokázala...
{22137}{22208}To je zøejmì dùvod, proè Geomancer|udroval svou pozici.
{22215}{22275}Ale co tam dìlali?
{22284}{22315}Kdo ví?
{22326}{22407}Ale urèitì nejsou z tìch,|co by tam jen sedìli a nic nedìlali.
{22481}{22550}U vùbec nezachytávám svùj vysílaè!
{22565}{22646}Vím, kde jsou. Vím,|e jsou pøímo pøed námi.
{22666}{22704}Ona je moje!
{22718}{22810}Podívejme, podívejme. Zdá se,|e jsi s ní mìl nìjaké problémy.
{22818}{22873}Kdo ví, co se stalo...?
{22886}{22954}Já u vím, e je bio-android!
{22966}{23005}e je Bio-android?
{23033}{23172}Ne, ne, ona je trochu odlišná|od ostatních bio-androidù.
{23202}{23255}Ne, ne, ne, ne. Velmi odlišná.
{23262}{23294}Jak se liší?
{23362}{23461}Pøišli za mnou piráti Kei a poádali mì,|aby sem rozluštil...
{23468}{23529}...nìjaké údaje genetického|inenırství a podobnì, které objevili...
{23529}{23589}...v jakıchsi ruinách zvanıch "Hrob draka".
{23602}{23703}Vím, e jste navrhl XGP,|kdy jste ty údaje rozluštil, profesore.
{23712}{23813}Aby sem øekl pravdu,|nepodaøilo se mi je rozluštit úplnì.
{23838}{23915}To "a podobnì", co sem pøipomínal,|bylo nìco, co sem ani já nedokázal pochopit.
{23915}{23990}Mùu to akorát popsat jako "èernou skøíòku".
{24011}{24103}XGP a Melfina byly|vytvoøeny s vyuitím...
{24103}{24208}...této èerné skøíòky,|kterou neumím aktivovat
{24211}{24286}a s vìdomostmi pøes 30 000 let,|které nám zanechal bùh ví kdo.
{24311}{24365}Øíkate, e v XGP|a Melfinì je ukryto tajemství,
{24365}{24445}které nedokáete rozluštit ani vy, profesore?
{24448}{24495}Tak, tak, tak! Pøesnì tak!
{24506}{24590}Oh, proè je ve vesmíru tolik záhad,
{24590}{24669}které ani já nedokáu rozluštit?
{24684}{24742}V kadém pøípadì,|tady máš odpoveï.
{24746}{24795}Ona je pøíliš velkou záhadou.
{24822}{24850}Cítím je!
{24911}{24957}Našel sem tì, Melfino!
{25017}{25044}Otoè loï!
{25044}{25102}Co oni tady vlastnì chtìjí?
{25153}{25173}Mel?
{25173}{25207}Spirála mizí.
{25338}{25371}Mel, co se stalo?!
{25382}{25446}To je... vír?
{25446}{25476}Detekuji další loï!
{25527}{25561}To je Geomancer!
{25622}{25712}Chyte XGP!|Zniète MacDougalla!
{25797}{25823}Neotravujte!
{25909}{25972}Nesna se s nimi bojovat!|Jdi za XGP!
{26049}{26077}Ok ty bastarde...!
{26227}{26256}- Sakra!|- Gene!
{26256}{26290}- Gene!|- Blbec!
{26350}{26399}Myslíš, e ti nechám Melfinu?
{26474}{26518}Maximální rychlost! Uteèeme jim!
{26578}{26591}Za nimi!
{26591}{26614}Vím.
{26699}{26737}Nedovolte jim uniknout!|Za nimi!
{26738}{26795}To nesmíme, Lorde Hazanko.
{26808}{26913}Pokud se odchılíme od té cesty,|nikdy nedosáhneme Leyline.
{26974}{27017}Mel! Kde je ta spirála?
{27050}{27080}Dosáhli sme støedu.
{27207}{27271}Detekuji kinetické vlny!|Nìco je pøed námi!
{27285}{27317}Co to je?
{27330}{27354}T-To je--
{27374}{27429}To je to, co hledají piráti Kei...
{27429}{27485}Èeká tam na nás kopec pokladù!
{27500}{27558}Je to srdce Galaktického Leyline?
{27778}{27843}Co tam najdeme?|Poklad a nebo pøíšery?
{27854}{27877}Pojïme zjistit--
{27917}{28000}Loï zaèíná bıt vtahována.|Je to jakoby jsme byli navádìni.
{28009}{28065}Navádìni? To je pøiliš jednoduché!
{28139}{28177}Narazíme!
{28274}{28337}Rychlost klesla na 70%.
{28337}{28386}Venku detekuji atmosféru.
{28391}{28435}Gene! Co budeme dìlat?!
{28457}{28536}Uka trochu odhodlání.|Leyline nám posílá pøivítání.
{28544}{28583}Myslím, e to pøijmeme.
{28820}{28858}Koneènì sme se dostali na konec cesty?
{28860}{28882}Oh, ne.
{28894}{28990}Podívejte na tohle. Zdá se,|e to je umìlá struktura.
{29006}{29069}Znamená to "Vstupte dál, prosím"?
{29075}{29189}Atmosféra je dıchatená.|Gravitace je pøiblinì 0,974 G.
{29197}{29249}Mysleli na všechno.
{29267}{29305}Dávej pozor na loï, Gilliame.
{29315}{29381}Šastnou cestu.|Buïte opatrní.
{29450}{29528}Tobigera, ty a posádka budete|chránit Geomancera!
{29528}{29549}Ano.
{29558}{29604}Vy ostatní, pojïte se mnou!
{29611}{29637}Ano!
{29658}{29724}Tak jak, Harry?|Co tvoje tìlo?
{29737}{29856}Je to dobré. Cítím se lehèí,|ne ve svém skuteèném tìle.
{29866}{29984}Je silné, to je pravda, ale to tìlo|je tvùj ivotní podpùrnı systém.
{29991}{30028}Dobrá, rozumím.
{30057}{30110}Tohle místo mi nahání strach.
{30149}{30192}Co, slepá ulièka?
{30206}{30248}Gene, co teï?
{30257}{30304}Co asi? Jdeme naspìt--
{30327}{30358}Co je to za svìtlo?
{30413}{30438}Je pryè!
{30438}{30465}Co to--?!
{30479}{30509}Co je to?
{30525}{30564}Jeskynì je pryè!
{30597}{30646}Jako kdyby jsme byli nìkde jinde!
{30653}{30693}Co se to dìje?
{30702}{30742}Jak to mám vìdìt?
{30767}{30831}Kadopádnì, se zdá,|e jsme uvnitø toho valce.
{30848}{30889}Co je, Melfino?
{30937}{30986}Ani já nevím.
{31017}{31069}Nevím ani jak sem to udìlala!
{31078}{31164}Jak to, e sem byla schopná|sem dovést Outlaw Star?
{31179}{31245}Nikdy pøedtím sem tu nebyla,|tak jak...?
{31299}{31367}Pøišli jsme sem,|aby jsme to zjistili, ne?
{31392}{31440}Mám ti to teda øíct?
{31475}{31500}Kdo je tam?
{31500}{31601}Je to proto, e Melfina| v sobì má tajemství Leyline.
{31614}{31661}To je Hazanko. A--
{31676}{31719}Zase ti "Antenskı"?
{31727}{31822}Vrate Melfinu.|Ona patøí nám!
{31829}{31899}Melfina není vìc, ty pako!Zapomeò!
{31940}{32011}Jak úasné!|To byla teleportace?!
{32023}{32052}MacDougall!
{32058}{32114}Proè je s nimi Gwen Khan?!
{32262}{32335}Proè? Proè se vracíš?
{32343}{32373}C-Coe?
{32373}{32450}Proè? Proè se vracíš?
{32478}{32545}Já...? Vrátila sem se?
{32561}{32582}Melfino!
{32618}{32690}Jaké je tvoje pøání?
{32695}{32717}O co jde?
{32717}{32786}Jaké je tvoje pøání?
{32786}{32810}Ten hlas...
{32810}{32927}Obìv svoje pøání zde, v této krajinì.
{32969}{33006}"Obìvit svoje pøání"?
{33153}{33233}Proè se vracíš?
{33250}{33341}Kdo je ten mu?
{33461}{33568}Sora, tooi sora...
{33578}{33696}Tsubuyaita koe...
{33718}{33981}Anata noyume wa ima|hoshi no sharin o mawasu.
{34006}{34264}Watashi, itsumo doko ni mo inai.
{34282}{34393}Sou kanjite ita,
{34399}{34548}sono hitomi shiru made wa.
{34555}{34782}Mune no katasumi kaketa|tsuki ga hitotsu aru dake,
{34786}{35087}demo donna ni hosoi michi|mo terasu you ni hikaru.