{1}{1}23.976
{72}{221}Jednoho tichého dne,
{231}{406}vanul èerstvı a svìí vítr.
{421}{749}Lupeny kvìtù se chvìli,|jakoby spali.
{768}{1008}Ten pocit pokoje...
{1018}{1441}Tak øekni mi..  Jaké mu lidé dali jméno?
{1458}{1802}V bílém písku mìsíce,|pøíbìh je uschován,
{1822}{2175}vnímám ho, jako kdy svítí svìtlo,tak klidnì.
{2291}{2374}Neobviòuj to, neniè to, nepodceòuj to...
{2374}{2493}...to jedineèné, co kadı má.
{2511}{2536}Moje láska...
{2536}{2562}Moje sny...
{2562}{2585}A té ty.
{2589}{2730}Nevzdám se toho, za ádnou cenu.
{2790}{2888}V té noci, kdy jsi nepokojnı,|kdy dìláš cokoliv,
{2890}{2999}...máš chu to vše odhodit pryè.
{3002}{3102}Neøíkej u nic, jen otevøi dveøe.
{3102}{3209}Nemám èas se tady|s tebou bavit.
{3215}{3324}Chci všude volnì letìt,
{3330}{3424}a nedbat v letu na opatrnost!
{3430}{3523}O nic jsem nepøišel,
{3523}{3619}vdy jsem ještì ani nezaèal.
{3626}{3707}Neobviòuj to, neniè to, nepodceòuj to,
{3710}{3829}...to jedineèné, co kadı má.
{3845}{3874}Moje láska...
{3874}{3903}Moje sny...
{3903}{3924}A té ty.
{3927}{4046}Nevzdám se toho, za ádnou cenu.
{4074}{4101}Co by jsi chtìl?
{4101}{4127}Co chceš dìlat?
{4127}{4179}Kam pùjdeš?
{4182}{4337}Vezmi co chceš, pøetni temnotu,|kdy budeš utíkat nocí!
{4462}{4551}Proè se vracíš?
{4604}{4700}Proè se vracíš?
{4738}{4834}|OUTLAW STAR: "Bludištì zoufalsví"
{4924}{4973}Je tu jen jedna cesta.
{5014}{5075}Je tu jen jedna cesta.
{5152}{5205}Jime? Posloucháš mì, Jime?
{5217}{5254}Gene! Jsi v poøádku?
{5262}{5284}Hej.
{5284}{5326}Co se tam dìje?
{5330}{5385}Co to znamená,|"Je tu jen jedna cesta"?
{5393}{5489}Vím já? Ale zdá se,|e se tím musíme øídit.
{5602}{5666}Tahle hra mì unavuje.
{5689}{5717}Si tam, Jukai?
{5749}{5798}Samozøejmì, k slubám.
{5798}{5895}Zdá se, e ostatní|byli posláni jinam.
{5907}{6069}To je jedno. To na èem záleí je,|aby sem se dostal k bránì první a získal klíè.
{6081}{6117}A je to tak.
{6337}{6397}Bratøe? Slyšíš mì, brácho?
{6410}{6436}Jo, slyším tì.
{6445}{6521}Zdá sa, e naší jedinou|moností je jít po té cestì.
{6529}{6570}Rozumím. Pùjdem dál.
{6578}{6601}Dávej si pozor.
{6635}{6678}Melfino, u jdu...
{6894}{6913}Suzuko.
{6920}{6982}Vypadá to, e se|cesty postupnì setkávají.
{6989}{7020}Spìchejme.
{7051}{7105}To je úasné...|Tak úasné.
{7115}{7162}Jednoznaènì úasné...
{7175}{7266}Moná bylo chybou dávat|MacDougallovi souøadnice tohohle místa.
{7273}{7321}A nebo to byl dobrı nápad?
{7321}{7389}No, bylo to pro moje vlastní dobro.
{7405}{7451}Èeká na konci této cesty.
{7463}{7495}Vıbornì.
{7502}{7553}Pravda.|Budu spìchat... budu ...
{7562}{7620}Opravdu bude na konci poklad?
{7634}{7668}Jak to mám vìdìt?
{7695}{7773}Suzuko, proè si s námi šla?
{7790}{7863}Mui chtìjí vdy| vìdìt "proè"...
{7877}{7952}Poznat dùvod však neznamená,|e na tom mùeš nìco zmìnit.
{7968}{8070}Urovnej si své vlastní pocity,|Gene Starwinde.
{8299}{8352}Kde jsou kopce, jsou i údolí.
{8361}{8392}Prosím, a po tobì.
{8403}{8476}Suzuko ,ty tedy víš jak prokázat mui úctu.
{8489}{8561}To já jen e na druhé|stranì nemusí bıt pevná pùda.
{8571}{8630}Take budu pokusnı králík?
{8637}{8659}Jdu na to.
{8714}{8745}Experiment se podaøil.
{8859}{8928}S tebou není nikdy nuda, e, Gene?
{8947}{8981}Díky.
{8992}{9029}Není tøeba mi dìkovat.
{9097}{9154}Dlouho sme se nevidìli, Suzuko.
{9171}{9225}Vypadáš dobøe, Hitorigo.
{9234}{9287}Jaké pøekvapení,|e tì tady potkávám.
{9287}{9321}Co se dìje, Suzuko?
{9351}{9451}Chtìl jsi vìdìt,|proè jsem šla s vámi, Gene?
{9477}{9549}Jak sem øíkala,|jste velmi zajímaví,
{9562}{9614}ale je to i proto,|e si chci vyrovnat úèty s piráty Kei,
{9614}{9725}a obzvláš tady s Hitorigem.
{9754}{9873}Zdálo se, e jste si dost blízcí,|a tak sem vás vyuila.
{9910}{9985}Jdi, Gene.|Tohle je moje záleitost.
{9998}{10033}Jdi dál sám.
{10077}{10109}Melfina na tebe èeká.
{10199}{10262}Opravdu pøekvapení nikdy nepøestanou?
{10262}{10325}Jsem pøekvapen, e máš partnera.
{10332}{10402}Si do nìj zamilovaná, Suzuko?
{10418}{10475}Nemám v úmyslu ti to øíct.
{10487}{10603}Kdy tì zabiju, povím ti to za odmìnu|pøi odchodu na onen svìt.
{10612}{10730}To, e sem ti zabil rodinu není|pøece dùvod, aby si mì tak nenávidìla.
{10737}{10819}Oba pracujeme jak zabijáci, ty i já.
{10829}{10941}Jsi jen jeden z mnoha pirátù.|Já patøím sama sobì.
{10948}{11005}Vypadá to, e máme rozdílné názory.
{11330}{11412}Tenhle boj by mohl bıt zajímavı,|e, Suzuko?
{11426}{11453}To by mohl.
{11494}{11613}A na samém konci uvidíme,|komu bude patøit tahle nádherná tváø.
{11635}{11678}To bude opravdu zajímavé.
{11742}{11827}Tohle je Galaktickı Leyline?|Co tu vlastnì dìlám?
{11887}{11958}Nemùu nic s tím nic nadìlat!|Co mám dìlat?!
{12170}{12285}Nakonec sme se potkali.|Ty jsi Gene Starwind?
{12336}{12378}Jakı fešák...
{12393}{12450}Nechtìl by jsi se semnou pobavit?
{12460}{12530}Ještì nikdy sem neodmítl|nabídku od eny.
{12550}{12669}Ale za prvé.|Mezi piráty a mnou to nikdy neklapalo.
{12684}{12742}A za další, nemám náladu.
{12852}{12874}Fei ga!
{13056}{13134}Caster?|To na mì neplatí.
{13143}{13237}To je otrava.|enská a je silná...
{13237}{13271}To je blbé.
{13279}{13326}To byla jedenáctka.
{13332}{13388}Tohle je desítka.
{13439}{13541}Stùjte. Kadı, kdo odporuje|Lordu Hazankovi, zemøe.
{13550}{13641}Ale, kohoe to tady máme?|Snad to není pirátskı poskok?
{13655}{13726}Jime, nechej to na mì.|Ty jdi dál.
{13734}{13792}Proè? Budu bojovat spolu s tebou.
{13807}{13862}S tímhle si budu muset poradit sama.
{13869}{13887}Aisho?
{13890}{13917}Tak u jdi.
{14045}{14117}Koneènì mùu bojovat|bez strachu o nìj.
{14117}{14249}Pocítila jsi mojí sílu|a chceš umonit útìk tomu dìcku?
{14256}{14293}Jak milé.
{14323}{14370}Pøestaò si vymıšlet.
{14379}{14458}Jsem jako tvoje noèní mùra.
{14469}{14560}Ale jak to, e se takové vìci|dìjí pøi hledání pokladù?
{14578}{14696}No nic. Vdy se pust do problémù,|které máš pøímo pøed sebou.
{14703}{14731}Pøesnì tak.
{14993}{15065}Je mi jedno kolikrát to budeš zkoušet,|na mì to neplatí.
{15085}{15137}Kolik nábojù ti ještì zùstává?
{15146}{15210}Øeknu ti to. Pøesnì ètyøi.
{15210}{15331}A ti dojdou, tak zemøeš,|Gene Starwinde.
{15355}{15402}Díky za varování.
{15415}{15470}Vysaje tvùj ivot, e...?
{15511}{15539}Tu máš!
{15598}{15635}Co je to?
{16076}{16152}Prokleté vìci...|vysají z tebe ivot...
{16366}{16402}Co se tu dìje?
{16597}{16623}Melfino!
{16679}{16754}Melfino, hned ti pomùu.
{16779}{16825}Pøišel sem pro tebe, Melfino.
{16838}{16921}Nemùu bıt takovou, jakou mì chceš.
{16962}{17070}Tak to není. Mì staèí,|kdy tì budu mít pøi sobì.
{17134}{17195}Miluji tì.
{17246}{17282}Našel sem tì.
{17332}{17416}Nakonec se setkáváme,| moje drahá Melfino.
{17436}{17477}Tak, otevøi bránu.
{17493}{17541}Dávej si pozor,|kdy mluvíš s dámou.
{17558}{17629}Melfina je šastná, kdy je semnou.
{17635}{17664}Smìšné.
{18074}{18118}Za to zaplatíš, ty èerve.
{18323}{18347}Harry!
{18386}{18506}To je... poprvé,|co jsi semnou takhle promluvila...
{18559}{18576}Harry!
{18662}{18724}Není urèeno pro komerèní pouití.
{18725}{18804}Z Sk. a Aj. titulkù A-H-Sarvill (Uhh ...jak moc se liší!)
{18888}{18921}Co jsi to udìlal...?
{18962}{19061}Nemusíš se tím trápit.|Udìlej jen svojí úlohu.
{19076}{19121}Svojí úlohu...?
{19129}{19211}To u staèilo. Vzpomeò si, Melfino.
{19226}{19308}Jsi klíè urèenı pro otevøení brány,|která stojí za tebou.
{19318}{19416}Jako dìvèe z Leyline,|splníš moje pøání.
{19464}{19568}Pøipouštím, byla to naše vlastní chyba,|e nám XGP byla ukradena.
{19568}{19680}Kvùli tomu sem se soustøedil|jen na to, aby sem došel sem.
{19689}{19717}Co to øíkáš...
{19723}{19750}Co tím myslíš...
{19750}{19867}Nemusíš odpovídat.|Konec koncù jsi jen loutka.
{19896}{19979}Tak, otevøi mi bránu.
{20066}{20107}Pøestaòte. Pøestaòte, prosím.
{20164}{20221}Pøíkaz Projektu Leyline.
{20221}{20285}"To ty jsi rozbila mùj Meissenskı štít"
{20442}{20490}Cesta je volná.
{20778}{20831}Si úasná ena, Suzuko...
{20849}{20949}Opravdu tì miluji.|Proto sem si vybral tuhle tváø.
{20960}{21020}Podstoupila si to všechno,|jen aby si se semnou støetla.
{21024}{21118}Místo kopy pokladù, kterou máš|pøed sebou, jsi si vybrala mì...
{21129}{21184}Moje individualita je pro mì dùleitá.
{21184}{21245}Od toho se odvijí i svìt.
{21289}{21342}Ty tomu zøejmì nerozumíš, e?
{21347}{21389}Ne, nerozumím...
{21404}{21474}Ale potom ani ty|nechápeš moje pocity, e?
{21492}{21524}Zanpa randou!
{21654}{21760}To je smùla.|Chtìl sem tì dostat ivou.
{21802}{21851}Dovolila sem ti zasáhnou mì.
{21883}{21973}Chtìla sem poznat bolest tìch,|ktoré jsi zabil.
{21989}{22034}Teï jsem na øadì já.
{22034}{22093}Coe?|Zanpa randou!
{22269}{22328}Tuhle techniku sem nikdy pøedtím nevidìl.
{22341}{22374}Nazıvá sa Kurenai|/Karmín/.
{22402}{22457}Tehdy si jí nepouila.
{22466}{22549}Vynalezla sem jí a potom,|jen pro tebe.
{22584}{22614}Vidím...
{23318}{23349}Trochu moc mluvíš...
{23562}{23610}Jsem jen trochu unavená...
{23622}{23685}Chvíli jsi odpoèinu|a bude mi dobøe...
{23705}{23788}Gene, nalo nìjakı Dragonit i pro mì...
{23820}{23883}Jak fascinující!
{24037}{24131}Hazanko?|Hazanko se sem dostal jako první?
{24169}{24209}Harry... Harry
{24227}{24295}Byl si jedinı bratr,|kterého sem mìl...
{24329}{24450}To udìlal Harrymu Hazako, e?|Zabiju ho vlastními rukami.
{24475}{24563}Tady? Tady to je, e?|To je ono?
{24563}{24628}Poèkejte, profesore.|Vy zùstanente tady.
{24637}{24726}Proè? Proè musím zùstat tady?
{24736}{24814}Vdy se nikdo nesnail víc|ne já, aby sme se sem dostali.
{24831}{24913}A pokud následkem toho|mùj bratr zemøel, profesore,
{24913}{24982}té jste za to|trochu zodpovìdnı, ne?
{24987}{25071}Huh? To není moné.|To není logické.
{25071}{25166}Pro nìkoho, kdo ztratil svého|mladšího bratra je to dost logické.
{25179}{25293}Koneènì sem se dostal do cíle,|ale ádná kráska tu na mì neèeká...
{25316}{25353}Kde je Melfina?
{25367}{25427}Gene Starwind?|Kdy to tak vezme,
{25427}{25507}byl si to ty a Hilda,|kto zaèal celou tuhle párty.
{25675}{25732}Zkoušíš to samé|znovu a znovu, e?
{25739}{25821}Donutím tì trpìt tak,|jako trpìl Harry.
{25830}{25858}Na to je trochu pozdì.
{25862}{25927}Ten náboj, co jsem pouil,|byl èíslo 9.
{25935}{26001}Devítka? Oni opravdu existují?
{26009}{26073}Ale nezdá se,|e by to nìèo udìlalo.
{26794}{26845}...projekt Leyline aktivován...
{26910}{26971}Ona plakala?
{26989}{27050}Ale kvùli tomu si jí nezachránil.
{27050}{27074}Hilda?
{27074}{27162}Outlaw musí bıt osamìlı vlk.
{27180}{27225}Nesmíš spoléhat na nikoho kromì sebe.
{27242}{27332}Ale obèas chceš|pocítit teplo jiného tìla.
{27332}{27411}Gene, chceš jít do vesmíru|se svım otcem?
{27541}{27630}Kráèej vlastní cestou,|Gene Starwinde.
{27635}{27710}Gene, il sem kvùli svému snu.
{27718}{27757}Nièeho nelituji.
{27768}{27850}A nyní si na øadì ty.|Vkladám do tebe nadìje.
{27850}{27890}Hodnì štìstí Gene Starwinde.
{27890}{27925}Hodnì štìstí Gene Starwinde.
{28010}{28102}To pøece ne...!|Co tu mám dìlat úplnì sám?
{28113}{28162}Ne! Sem úplnì sám!
{28310}{28330}Gene!
{28330}{28349}Gene!
{28366}{28391}Gene.
{28476}{28531}Díky bohu!|Si v poøádku, Gene?
{28541}{28589}Co se stalo?
{28589}{28653}Našel sem tì tu leet v bezvìdomí.
{28658}{28730}Zdá se, e mladší z bratrù|MacDougallovıch je mrtvı.
{28738}{28792}Já sem ho nezabil.
{28792}{28829}Gene, kde je Mel?
{28834}{28901}Asi nìkde tam, zøejmì.|Musím jít za òí.
{28906}{28931}Fajn.
{28946}{29013}Jime, vra se nazpìt na Outlaw!
{29020}{29120}Gene...|Opravdu ti nemùu nijak pomoci?
{29136}{29182}U mi zùstávají jen dva náboje do Casteru.
{29206}{29309}A je mít nebudu,|mojí jedinou nadìjí je Outlaw.
{29337}{29417}Vdy se nám všechno podaøilo|díky skvìlé tımové práci.
{29431}{29474}Já sem první linie a ty jsi...
{29478}{29507}Záloha.
{29548}{29613}Pøivedu Melfinu zpìt.|Spolehni se.
{29617}{29700}Najdi Suzuku a Aishu|a èekejte pøipraveni v lodi.
{29751}{29779}Dr se!
{29786}{29853}Pøinesu nazpìt kopec pokladù.
{30038}{30114}Jaké je tvoje pøání?
{30131}{30208}Jaké je tvoje pøání?
{30383}{30414}Co to...?
{30414}{30461}Jaštì stále sem se nedostal do cíle?
{30508}{30555}Vítej, Gene.|Vítej.
{30570}{30594}Gwen Khan.
{30594}{30629}Pøesnì tak.|Pøesnì tak.
{30633}{30690}Sem Gwen Khan.|Sem Gwen.
{30702}{30776}Ale mám takovı problém.|Nemùu dál.
{30776}{30813}Opravdu, mám problém.
{30813}{30869}Ty dveøe jsou zamèené zevnitø.
{30882}{30964}Brána je otevøená,|take by to nemìlo bıt tìké...
{30974}{31047}Opravdu musím dál.|Jakı problém...
{31052}{31097}Ty, tak udìlej nìco!
{31102}{31153}Opravdu jsi to nebyl ty,|kdo zaèal tuhle hru?
{31153}{31196}Pøestaò! Tak pøestaò!
{31196}{31263}Chci vìdìt, to je všechno.|Chci vìdìt.
{31390}{31417}Harry?
{31445}{31551}Jo. Vdy se cítím mizernì,|kdy se probudím.
{31560}{31645}Není tady Melfina?|Pøišel jsem za òí.
{31654}{31732}Ne, nedìlej to. On u je mrtvı.
{31742}{31825}Pøístroje v jeho tìle ho sotva|drí pøi ivotì, to je vše.
{31840}{31894}Je jako duch.
{31907}{31936}Opravdu.
{31948}{31996}Myslíš, e by jsi dokázal|otevøít ty dveøe, Harry?
{32002}{32073}Dokázal by jsi to?|Na druhé stranì je Melfina.
{32184}{32252}Cestu musí otevøít dìvèe.
{32270}{32345}Cestu musí otevøít dìvèe.
{32413}{32443}Melfino?!
{32450}{32512}Chudák...|Okolo ní je ochrannı program.
{32527}{32569}Já to všechno vymau.
{32592}{32621}Melfino?
{32657}{32684}Harry.
{32690}{32740}Sem rád, e sem to stihl vèas.
{32754}{32893}Promiò, Melfino. Jediné, co pro|tebe teï mùu udìlat, je vzbudit tì.
{32911}{32961}Promiò, e jsem ti nedokázal pomoct.
{32961}{33023}U dlouho ti chci nìco øíct.
{33030}{33088}Harry...
{33109}{33138}Zbohem.
{33183}{33214}Harry.
{33270}{33365}Jdi, Gene.|Jdi si poslechnout její píseò.
{33373}{33396}Píseò?
{33396}{33489}Poádej jí, a zazpívá i pro mì.
{33736}{33782}Úasné. Dveøe se otevøeli.
{33799}{33840}Poádám jí, Harry.
{33881}{33912}Spolehni se.
{34055}{34162}Obloha, daleká obloha...
{34172}{34290}Šepotavı hlas...
{34314}{34576}Tvoje sny teï otáèejí kolem hvìzd.
{34600}{34858}Nikdy jsem nikde nebyla.
{34876}{34988}Tak jsem se cítila,
{34994}{35142}dokud jsem nespatøila pohled tvıch oèí.
{35150}{35368}V koutku mého srdce je jen kousek mìsíce.
{35385}{35682}Ale je dost jasnı, aby osvítil i tu nejuší cestu..