{1}{1}23.976
{55}{86}TaSHee's Gang uvádí
{183}{262}NODAME CANTABILE
{2234}{2296}Brahmsova symfonie èíslo jedna...
{2316}{2455}Jeho první symfonie, øíkalo se, e mu zabrala více ne 20 let k dokonèení.
{2471}{2502}A Chiaki.
{2520}{2564}Tuhle èást jsi nestudoval dost dobøe.
{2564}{2611}Nepodceòuj Brahmse!
{2644}{2739}Zaèal jsem dìlat toto dílo s S orchestrem, ale Stresemann mi ho vzal.
{2811}{2830}LEKCE 17
{2868}{2917}Brahmsova symfonie èíslo jedna?
{2917}{3014}Pro mì to zní dobøe. S Mozartem to pùjde dobøe, a toto dílo ti sedí.
{3014}{3043}Dílo, které mi sedí?
{3043}{3115}V kadém pøípadì, pospìš a vyber si taky poslední dílo.
{3115}{3174}Touto rychlostí nebudeme mít dost èasu na naši raklamu.
{3174}{3240}Reklama? Ještì nemáme zamluvenı ani sál.
{3263}{3282}Kimuro-kun.
{3309}{3364}Zamluvila jsem pro tebe Sál Weltraum.
{3364}{3411}Opravdu? Díkybohu!
{3411}{3434}P-Pøedsedkynì?|Opravdu? Díkybohu!
{3434}{3448}P-Pøedsedkynì?|Znají mì a mám tam hodnì pøátel, take...
{3448}{3488}Znají mì a mám tam hodnì pøátel, take...
{3488}{3603}Byla jste skvìlou pomocí. Chiaki-kun je ve styku|s tìmito vìcmi. Jen je neobstaral.
{3603}{3706}Jsem si jistá, e jeho mysl není zaplnìna nièím, jen vystoupením, take se nedá nic dìlat.
{3706}{3780}Ale nemùu uvìøit, e jsi pro nás rezervovala Sál Weltraum.
{3780}{3832}Zajímá mì, jestli zvládneme zaplnit 750 sedadel.
{3832}{3898}No, byl by to problém, kdybych rezervovala menší sál.
{3898}{3997}Zamluvila jsem ten vìtší! Mùeme usadit 1600 lidí.
{3997}{4062}Sál pro 1600 lidí?!
{4062}{4185}Dìláš si legraci! bez ohledu na co, jak moc si dìláme reklamu, poádat| 1600 lidí, aby navštívili vystoupení neznámého orchestru?
{4231}{4307}Jestli si dìláte starosti s reklamou, prostì to nechte na nás!
{4307}{4372}Mìli bychom pro vás dát reklamu do Classic Life?
{4372}{4409}Aèkoli to bude stát dost penìz.
{4428}{4479}Koupíme celou stranu!
{4479}{4516}Jak velkorysé od vás!
{4516}{4590}Víte, jak moc by stálo místo reklamy v novinách?
{4590}{4695}Oh, budete dìlat Brahmse? Jeho první symfonii?|Opravdu se vyhoupnete na vıznamnìjší dílo!
{4695}{4756}C-Co tady vy dva dìláte?
{4756}{4878}Dostali jsme anonymní typ øíkající, e jste vytvoøili orchestr s nìjakımi skvìlımi èleny.
{4878}{4915}Anonymní typ?
{4952}{5008}Take, "skvìlí èlenové" znamenají, e s sebou máš profesionály?
{5022}{5057}Vìtšina z nich jsou stále studenti.
{5072}{5142}Vìtšina z nich vystupovala v orchestru na Hudebním Festivalu Nina Lutz.
{5142}{5184}Ah, z tehdy!
{5184}{5199}Poèkej!
{5217}{5293}Øíkala jsi, e bys mi pomohla cvièit, kdybych tì nechal zùstat pøes noc!
{5293}{5354}Zaspala jsem, take u na to nemám ádnı èas!
{5368}{5404}Zpozdím se na své vyuèování!
{5404}{5468}Byla jsi tu jen pro jídlo zdarma, útoèištì a masá ramen?!
{5468}{5519}Kiyoro, ty lháøko!
{5519}{5581}Ona je naší koncertní mistriní.
{5581}{5648}Je to aèka Kaie Dowina, známého uèitele.
{5648}{5727}Kai Dowin? Koncertní mistr z Berlínské Filharmonie?
{5727}{5844}Právì teï, z Kiyori-san udìlal finalistku hudební soutìe.
{5868}{5930}Jistì vyhraje!
{5984}{6082}Take se dostala do finále Oshi-Com. To je úasné.
{6082}{6153}Jestlie vyhraje, bude to pro vás skvìlá reklama.
{6173}{6214}Prosím uveïte ji v "Dream-colored classics"!
{6214}{6259}Soutì sponzorována Novinovou Spoleèností Oshiiuri je nejvìtší v Japonsku.|Samozøejmì, e uvedeme!
{6259}{6312}Soutì sponzorována Novinovou Spoleèností Oshiiuri je nejvìtší v Japonsku.
{6312}{6338}Známá jako "Oshi-Com" zkrácenì.
{6360}{6405}A Kiyora v ní není jediná.
{6424}{6539}Bez ohledu na to zdali hrají na dechové, smyècové, nebo na cokoli, |spousta èlenù, kteøí se rozhodli úèastnit se, se dostali do finále.
{6571}{6637}Ale kvùli tomu, jsme schopni zkoušet tento mìsíc jen dvakrát.
{6637}{6654}No, odcházím tedy.|Ale kvùli tomu, jsme schopni zkoušet tento mìsíc jen dvakrát.
{6672}{6733}Dìlej ve cvièení, co mùeš. A nepodvádìj mì, ok?
{6733}{6800}Nebuï hloupá. Jsi pro mì ta jediná, Izumi-chan.
{6827}{6846}Pa!
{6846}{6888}Pozdìji ti zavolám!
{6888}{6964}Kikuchi, co se stalo s Yukko-chan?
{6964}{7073}Chiaki-kun, dnes je skvìlı den na zkoušku, nemyslíš?
{7073}{7103}Venku není pøíliš dusno.
{7103}{7173}K-Kuroki-kun... co je to za kytku?
{7173}{7269}Oh, tohle? Prostì jsem ji vidìl v kvìtináøství na cestì sem, tak jsem ji koupil.
{7269}{7316}Chiaki-kun, vìdìl jsi?
{7316}{7394}V kvìrtomluvì symbolizuje konvalinka ctnost a èistou lásku.|/Hroznì nemocnı/
{7394}{7519}To mi pøipomíná! Myslíš, e by se té dívce, Nodì Megumi-chan,|líbilo tohle jako dík za její rıové koule?
{7519}{7590}Kuroki-kun, co na ní shledáváš atraktivního?
{7590}{7629}Huh? Co na ní shledávám atraktivního?
{7629}{7741}Je roztomilá, má záøivou a èestnou osobnost, je sladká...
{7741}{7825}Je èistá a upravená, má úasnı zpùsob se slovy, a je velmi krásná.
{7825}{7867}"Èistá a upravená" a "velmi krásná"?!
{7867}{7989}Je to podivná, necitlivá, a nestoudná ena, která nosí|to stejné obleèení po dny na ulici, kdy dìlá divnı hluk!
{8017}{8039}O kom to teï mluvíš?
{8061}{8108}Zní to jako podivínka.
{8108}{8140}Øíkám ti to, je to Noda Megumi!
{8160}{8196}Tahle ena kouká na lidi, kdy se oblíkají,
{8196}{8246}navštìvuje placené porno stránky na poèítaèích jinıch lidí,
{8246}{8297}a sbírá nedopalky z cigaret jinıch lidí!
{8351}{8416}Není ádnı zpùsob, jak by mohla bıt  Megumi-chan takovı zvrhlík.
{8465}{8501}/Vhodná doba zachránit Kurokiho-kun - Selhání/
{8544}{8629}Právì teï, je celı mùj orchestr udeøen láskou.
{8629}{8669}Chiaki-sama!
{8669}{8712}Chybìl jsi mi!
{8754}{8789}Nepustím tì!
{8789}{8837}P-P-Pøestaò s tím!
{8853}{8977}Pøedtím, ne jsem to vìdìl, moji kolegové, kteøí bıvali zaujati|orchestrem, se stali zaujati jeden druhım.
{8977}{9018}Budeme opravdu v poøádku, jestli budou všichni takoví?
{9431}{9517}Kuroki-kun opravdu dává víc a víc lesku do té rùové barvy, kterou pro nás namaloval.
{9551}{9714}A je to skvìlé. Je to Mozart, take je pro nìj nejlepší pøidat lesk do jeho not.
{9738}{9933}Nicménì, jestli mùe ztratit sebe tak moc v jedné lásce,|co se stane, kdy ho Nodame odmítne?
{9933}{9997}Kuroki-kun se také dostal do finále!
{10040}{10124}Hej, nevypadá Chiaki-sama trochu unavenì?
{10124}{10144}Myslíš?
{10144}{10188}Kdy ho opomíjíš...
{10388}{10478}Hej. Zkoušej a zùstaò trochu víc soustøedìná, Kiyoro!
{10516}{10562}J-Jsem!
{10562}{10583}Leš!
{10583}{10658}Vím, e si dìláš starosti se svou skladbou na hudební soutì,
{10658}{10700}ale musíš teï musíš zmìnit rychlost!
{10700}{10728}Jsi koncertní mistrinì.
{10728}{10796}A i kdyby jsi nebyla, nemohli bychom zkoušet tak moc, jak to je!
{10796}{10882}To platí taky pro všechny! Vypadá to, jako by v tomhle u nikdo nebyl.
{10882}{10948}Jak stojí vìci teï, rád bych øekl, e byli všichni lepší bìhem hudebního festivalu!
{10948}{11031}Ale nedá se nic dìlat, dokud nebude soutì u konce, nemyslíš?
{11031}{11078}Budoucnost všech je naøádkovaná.
{11078}{11156}Má budoucnost je naøádkována s tímto orchestrem!
{11215}{11242}Dobøe!
{11242}{11267}Není to tak, e jsme profesionálové.
{11267}{11284}Naše budoucnost je naøádkovaná tady?|Není to tak, e jsme profesionálové.
{11284}{11357}To proto jste všichni tady v tomhle orchestru?!
{11357}{11388}Proè jsme tady?
{11388}{11472}No, já jsem chtìl znovu vystupovat v orchestru jako byl ten na hudebním festivalu.
{11472}{11565}Jo. Bylo to velmi povzbuzující, a taky je tu Chiaki-kun.
{11592}{11692}Jen cítím, e mùeme udìlat nìco opravdu úasného s tebou a všemi.
{11692}{11739}Jo! Všichni to cítí stejnì, e?
{11739}{11816}Jestlie se staneme slavnımi a získáme sponzory, kteøí nás vdycky budou chtít vidìt,
{11816}{11872}budeme mít peníze, abychom to mohli udret a mohli v tom pokraèovat navdy!
{11872}{11911}Pak bychom mohli bıt stejní jako ostatní profesionálové.
{11911}{11946}To je mùj sen!
{11946}{12052}Nebude to jen nìjaká legenda, ale orchestr, kterı bude pokraèovat navdy!
{12110}{12226}Myslím, e je to velice hezkı sen, kterı máš, ale pøíští ro se vracím zpátky do Bostonu.
{12262}{12281}Proè?!
{12281}{12376}Jsou tu rùzné okolnosti, a jsem tento rok v huedbní soutìi tady v Japonsku,
{12376}{12404}ale pøíšté rok...
{12417}{12523}Po mé promoci pøíští rok, pojedu taky do Nìmecka, a stále mám toho hodnì na studování.
{12560}{12626}Taky jsem plánovala se pøíští rok vrátit zpátky do Vídnì.
{12626}{12645}To ne!
{12645}{12720}Je pravda, e bych ráda dìlala nìjaké vìci s tímto orchestrem,
{12720}{12816}ale mùj sen je vystupovat po celém svìtì a udìlat svùj domov v zámoøí.
{12830}{12889}Pro tebe je to taky stejné, e Chiaki-kun? Je to prostì pøirozené, e?
{12889}{12955}No, bez legrace. Nakonec je to Stresemannùv ák.
{12955}{13003}Stejnì, proè jsi stále v Japonsku?
{13003}{13110}Jsem si jistı, e bys také mohl snadno vyhrát soutìe v zahranièí, Chiaki-kun!
{13133}{13176}"Je to prostì pøirozené," huh?
{13176}{13250}Pøestávka je u konce. Dále budeme pracovat na Brahmsovi!
{13250}{13306}Pro teï, projdìme si celı první rytmus.
{13554}{13581}Co je to?
{13599}{13637}Všichni jsou najednou po celém místì.
{13827}{13904}Co to sakra? Proè se všichni smìjí Minemu?
{13938}{13957}Já, také...
{14184}{14293}To pro dnešek staèí. Ne, nebudeme znovu zkoušet, dokud nebude soutì u konce.
{14308}{14332}Hodnì štìstí.
{14383}{14450}Myslel jsem si, e u jsem vìdìl, e všichni odejdou.
{14479}{14551}Senpai, jsi zase nìèím deprimovanı, ne?
{14584}{14637}Ne opravdu. Jsem v poøádku.
{14637}{14753}Jsem spokojená s konzervovanım zboím, ale ráda bych, aby si's byl vìdom,
{14753}{14847}e je tu spousta dalších vìcí, kterı bychom mohli v noci jíst.
{14847}{14883}Jestli si budeš staovat, tak to nejez!
{14883}{14939}Nestìuju si.
{14939}{15034}Ale proè nezkoušíš a máš jeden z tìch plátkù medvìdího masa?!
{15034}{15093}/Medvìdí plátky/
{15112}{15143}Právì teï nemám chu.
{15178}{15276}To mi pøipomíná" Dnes veèer budou hrát v televizi Puri-Gorotu.
{15276}{15347}Sledujme to! Hlavní postava Kazuo je tentokrát kolem!
{15347}{15390}Budeš se cítit líp!
{15411}{15426}Senpai.
{15451}{15495}Mùu to nahrát pøes tohle?
{15495}{15520}Sakra ne!
{15584}{15622}Musím jít koupit VHS pásku!
{15644}{15665}Berlínská Filharmonie?
{16313}{16362}Nepodneòuj Brahmse!
{16420}{16458}Rozumíš této èásti?
{16458}{16536}Podívej se na tento oddíl pro snící lesní roh, kterı spojuje tyto dvì fráze.
{16536}{16608}Šestı akord, odezva prvního rytmu!
{16608}{16733}Kadá jednotlivá nota v Brahmsovì symfonii je tam z dùvodu.
{16762}{16840}Všechno je nezbytné a smysluplné.
{16931}{17054}Chiaki-senpai... ummm, jestli nìco nesníš...
{17134}{17199}M-Mìl by se's pravdìpodobnì taky oholit a okoupat.
{17214}{17236}Senpai.
{17263}{17419}I kdyby tenhle orchestr skonèil tento rok, tentokrát udìlám| kadou vteøinu nezbytnou a smysluplnou!
{17419}{17498}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{17701}{17743}Toto je úasná skladba.
{17743}{17800}Dvanáctá skladba, která zdobí "Scraggly-Haired Medley":
{17800}{17853}"Duhovì zbarvenı se štìstím v nízkém B dur."
{17883}{17973}Vyvolává to vıraz a pocit v pøíbìhu, a je to udìláno moderním zpùsobem.
{17998}{18052}Mìlo cenu do teï tvrdì pracovat.
{18082}{18102}Poèkej vteøinku!
{18102}{18172}To je scéna, kdy si Scraggly a prince slíbí navzájem lásku, e?
{18203}{18238}Je to opravdu dùleitá èást!
{18238}{18287}Proè nezkusíš pøidat tady tento akord?
{18325}{18398}Právì zde! Proè bys najednou zmìnila rytmus?
{18398}{18433}Není to tam, kde medvìdi tanèí?
{18457}{18516}Ale králík a veverka se hned pøidají!
{18516}{18604}Proè to nerozèleníš na tøi oddìlené èásti, a hraješ èást, kde|tanèí veverka ve vyšších notách, abys to udìlala roztomilejší?
{18604}{18657}Ale pak to nebude odpovídat skladbì.
{18657}{18686}Tak co tohle?
{18686}{18730}To by vùbec nebylo roztomilé!
{18869}{18887}Sensei!
{18927}{18944}Jo.
{19006}{19049}/Dokonèení Scraggly-Haired Medley/|Dìkuji vám mnohokrát!
{19081}{19254}No tedy, sensei, má pøíští lekce nebude dokud se nevrátím| z mıch vzdìlávacích studií, ale prosím, buïte v poøádku!
{19254}{19285}Jen vteøinku.
{19285}{19374}Tvá vzdìlávací studia byla odsunuta na øíjen.
{19374}{19431}Vèera tu byl hovor od tvé alma mater.
{19458}{19533}A teï se ukázalo, e by byli rádi, abys jela nìkam jinam, jestlie pøípadnì...
{19533}{19589}Jen co bys tam dìlala?
{19607}{19647}No v kadém pøípadì, tak je to, take to vezmi.
{19686}{19766}Vyber si tøi skladby odsud, zhodno povlak hudby, a|buï pøipravena je perfektnì hrát do pøíští lekce.
{19766}{19823}Tøi skladby?! Zhudnotit povlak hudby?!
{19823}{19917}A jako extra trest za zmeškání tøí lekcí pøedtím,
{19917}{20036}si budeš muset vzít tøi náhradní lekce bìhem letních| prázdnin, take bys mìla bıt radši pøipravena.
{20100}{20134}/Mysle pøedtím, ne jednáš. |Plácaè-papírovım-vìjíøem je lichváø./
{20181}{20247}Senpai! Stále jsi se neokoupal?!
{20247}{20358}Padající smùla hoboje bude pøekrıvat pøi návratu melodii tøí-tónového akordu.
{20384}{20449}Dvì oddìlené melodie se setkají. Jak krásné.
{20485}{20582}Myslela jsme, e krásná hudba pøicházela z krásného ivotního stylu!
{20582}{20679}Ah! Taky jsi nesnìdl rıové koule! Musíš do sebe nìco dostat.
{20717}{20780}Tady máš, Senpai. Otevøi doširoka.
{20900}{20960}Senpai, koupel je pøipravená.
{20960}{21012}Pro teï, vyèistìme se, ok?
{21070}{21134}Taky ti umyju šamponem vlasy.
{21277}{21319}Stále v nìm byl zanechán kousek zdravého rozumu.
{21769}{21815}Zítra je finálové kolo soutìe.
{21815}{21874}Pøeju si, aby Megumi-chan mohla slyšet mùj hoboj.
{21889}{21948}Ne, po pravdì, ty jsi dùvod, proè budu hrát!
{22066}{22102}Megumi-cha-|Ahoj!
{22126}{22143}Megumi-chan!
{22170}{22210}Kam tak pospícháš?
{22210}{22257}Do supermarketu Yuuji-kun!
{22257}{22356}Je tam dnes speciální limitovaná nabídka, pìt sladkovodních úhoøù jen za 300 yenù!
{22356}{22430}Musím dát Chiakimu-senpai úhoøe! Musím do nìj vlít sílu úhoøù!
{22430}{22477}Chiaki-kun? stalo se mu nìco?
{22494}{22554}Skoro se vèera utopil ve vanì!
{22554}{22639}Kdybych nenakoukla dovnitø, kdo ví, co by se stalo?!
{22639}{22667}T-Ty jsi nakoukla dovnitø?
{22696}{22780}Nechte limitovanou nabídku pìti sladkovodních úhoøù za 300 yenù zaèít!
{22999}{23017}A skonèili jsme!
{23035}{23058}Netrafila jsem se...
{23058}{23107}J-Jsi v poøádku, Megumi-chan?
{23121}{23182}Zajímá mì, jestli by ho místo toho oivil slanovodní úhoø.
{23182}{23270}Omlouvám se. Mìl bych se ti taky pokusit pomoct.
{23289}{23331}To je v poøádku, Kuroki-kun.
{23331}{23403}Vdycky dìláš co mùeš v orchestru, take to pomáhá víc ne dost.
{23429}{23525}Právì teï se nemùu zamotat do hudby Chiakiho-senpai,
{23525}{23611}take jestli to mùe stát prvním tìlem a kostmi, pøinejmenším...
{23651}{23681}Taky ïábelsky drahé.
{23681}{23777}Zajímá mì jak by ho mìl Chiaki radši? Uvaøeného nebo grilovaného?
{23777}{23855}Byla to... èistá láska.
{23905}{24076}Teï to vidím. Vdycky kdy jsem tì vidìl, byla jsi opravdu naplnìna pocity k Chiakimu-kun.
{24076}{24104}/Finále Hudební Soutìe Oshiuri/
{24184}{24202}/Kategorie hobojù - Finále/
{24233}{24293}Chiaki-kun musí vìdìt, jaké k nìmu má pocity.
{24318}{24377}To proto se mi pokoušel øíct, e ji vidí jako nìjakého zvrhlíka.
{24398}{24451}Musel jsem vypadat jako naprostı debil.
{24497}{24579}Teï není èas takhle pøemıšlet. Musím se soustøedit.
{24579}{24630}Musím se vrátit do svého normálního klidu a vyrovnat se.
{24630}{24721}Jsem v poøádku. Témìø jsem se zabil pøípravou na tento den-
{24744}{24761}Oh ne!
{24812}{24857}Nechal jsem svùj jazıèek ve vodì pøíliš dlouho!
{24857}{24912}Je to znièenı! Nemùu ho vùbec pouít!
{24912}{24979}Tenhle není tak dobrı jako jinı, ale musím ho pouít jako náhradu.
{25029}{25094}Další, prosím. Kuroki Yasunori-kun?
{25094}{25132}Prosím vystupte.
{25161}{25294}Nemám ádnı èas... pøipravit jazıèek.
{25373}{25448}/Kategorie houslí - Finále/
{26109}{26129}Gratulujeme!
{26129}{26169}Gratulujeme!
{26169}{26204}Prosím podívejte se tady!
{26204}{26245}Prosím nechte nás s vámi udìlat interview.
{26245}{26307}Jaké je to bıt ocenìna druhım místem?
{26368}{26467}Váš vıstup byl velmi dobrı a jemnı, naprosto jinı od kvalifikace!
{26467}{26516}Pokud jde o vaše studium v zahranièí právì teï...
{26516}{26531}Kiyoro!
{26603}{26651}Kiyoro, co se ti stalo s krkem?
{26651}{26724}Já... spala jsem špatnì a dostala jsem do nìj køeè.
{26724}{26830}Proè jsem spala poprvé špatnì ze všech dní dneska?!
{26830}{26844}Proè?!
{27063}{27092}Gratulujeme, Kikuchi-kun!
{27092}{27127}Jaké to je vyhrát první místo?
{27127}{27183}Je to jako sen, opravdu.
{27183}{27294}Rád bych podìkoval svım rodièùm a mému uèiteli, kteøí mì a do teï podporovali.
{27310}{27424}Váš úasnı vıstup opravdu záøil s vaší srdeènou povahou!
{27450}{27479}Toru-kun, zvládl jsi to!
{27479}{27527}Gratuluju, Kikuchi-kun!
{27527}{27570}Zvládl jsi to, Toru!
{27631}{27656}Kdo sakra jsi?!
{27656}{27682}Ty jsi Yukko?!
{27682}{27709}Já jsem Yukko!
{27767}{27814}Prosím, mìjme naše intervier támhle.
{27886}{27969}Take Kikuchi vyhrál první místo a Aizawa a Katayama... jak jsem èekal.
{28009}{28036}Kiyora dostala druhé místo?
{28058}{28089}A nevidìl jsem uvedeného Kurokiho-kun.
{28109}{28124}Neøíkejte mi...
{28161}{28253}Kuroki-kun? Jo, vrazila jsem do nìj onehdy.
{28253}{28297}Mluvili jste vy dva o nìèem speciálním?
{28297}{28360}Nìèem zvláštním? Ne opravdu...
{28360}{28412}Jen jsem s ním projednávala své milostné problémy.
{28450}{28466}Ty...
{28466}{28540}Ah, senpai, je tohle árlivost?
{28540}{28601}Nenech, aby tì nìco takového obtìovalo. Nepodvádím tì.
{28601}{28691}Jestli si s tím dìláš starosti, proè mì nepøiváeš, abych nemohla?
{28806}{28851}Hoboj byl vdycky se mnou.
{28895}{29010}Vdycky jsem se o tebe tolik staral, a ty jsi mi to vdycky oplatil úasnou hudbou...
{29010}{29087}aby ukonejšila mé srdce bìhem mého ivota.
{29114}{29152}Ale tentokrát jsem tì zradil.
{29173}{29245}Nemùu uvìøit, e jsem se takhle ztratil v lásce.
{29280}{29307}Cítím se tak uboze.
{29455}{29508}Dostat køeè do mého krku není omluva.
{29508}{29605}Váš vıstup byl velmi dobrı a jemnı!
{29605}{29689}To bylo vystoupení, které ode mì dnes všichni slyšeli.
{29715}{29785}Je to tak frustrující! To není tak, jak hraju!
{29854}{29902}Chci znovu vystupovat na jevišti!
{29925}{30008}A pøíštì je chci jistì slyšet, jak opravdu hraju!
{30047}{30068}Ještì jednou!
{30200}{30233}Dobré ráno!
{30233}{30259}Dobré ráno.
{30276}{30339}Zkoušky mého orchestru zaènou zase zítra.
{30366}{30515}Právì teï, jestli udìlám to nejlepší ve všeho, co mùu udìlat,|pak to bude v poøádku.
