{1}{1}23.976
{46}{78}TaSHee's Gang uvádí
{183}{255}NODAME CANTABILE
{2236}{2276}Orchestr Chiakiho-sama?
{2276}{2367}Jo, zøejmì jsou to jeho èlenové.
{2386}{2449}Vypadá to, e od teï budou cvièit v naší škole.
{2468}{2507}To je Kikuchi-senpai!
{2507}{2541}Znáš ho?
{2541}{2578}Byl to mùj senpai na vyšší støední.
{2578}{2657}Byl známı za to, e byl opravdu dobrı na cello.
{2657}{2712}Pøedpokládalo se, e bude studovat v zahranièí v Bostonu.
{2729}{2832}Slyšela jsem, e se celá skupina úèastnila minulı| rok Hudebního Festivalu Nina Lutz.
{2871}{2932}Pak, všichni sem pøišli zvenèí?
{2932}{3027}Proè cvièí na naší škole? Je to vùbec dovolené?
{3027}{3122}No, samozøejmì. Nakonec, je to orchestr Chiakiho-sama.
{3158}{3183}LEKCE 16
{3394}{3435}Jak chcete hrát tuhle frázi tady?
{3435}{3544}Myslel jsem, e bychom tady mohli vytvoøit rozechvìní, |a udìlat tuhle èást jemnì a lehce.
{3544}{3566}Co?
{3566}{3685}Chápu. Ale pak pøechod do dalšího pohybu, kdy|hudba mìní charakter, bude tìkı.
{3685}{3741}Pak, chceš a to zkusím a hraju to víc jasnì?
{3741}{3783}Jo, to by bylo skvìlé.
{3783}{3797}Ok.
{3824}{3853}Všichni, zaèneme.
{3853}{3878}Dobrá!
{3878}{3918}Projdeme dnes všechno?
{3918}{3938}Poèkejte vteøinku.
{3955}{3989}Vy dva! Proè tam sedíte?
{4014}{4043}Tak jsme byli prokouknuti.
{4058}{4151}Tento koncert pro hoboj zamıšlí mít jen 35 hudebníkù.
{4151}{4238}Je tu deset prvních houslí a osm druhıch houslí.
{4238}{4296}Vy dva se v nìm neobjevíte.
{4296}{4315}Bìte domù.
{4315}{4363}Coe?! Opravdu?!
{4363}{4412}No, u jsem to vìdìl.
{4412}{4450}Stejnì jsem se pøišel jen podívat.
{4450}{4475}Coe?!
{4475}{4555}Sakra! Proè byste mìli dìlat naše první dílo tohle?!
{4755}{4900}Mozartùv "Koncert pro Hoboj v C dur," K. 314.
{4921}{5000}Toto dílo bylo napsáno jako sonáta a zvìtšilo se na koncert.
{5036}{5075}Orchestr je jen doprovod.
{5089}{5136}Po prvních dvou vykonanıch pohybech...
{5160}{5194}zaèíná sólo hoboje.
{5508}{5533}Je opravdu úasnı.
{5651}{5678}Technika je ohromující.
{5692}{5734}Je jemná pøesto zvuèná.
{5755}{5791}A jeho tìištì je neoblomné.
{5870}{5915}Ale co je to s jeho hraním?
{5955}{6017}Kuroki se zdá bıt jako váleèník.
{6173}{6209}Slabìji!
{6209}{6313}Tady je to, kde se melodie hoboje opakuje, |take se snate a zajistìte prostøedí.
{6463}{6532}Dìlejte tady staccato kratší!|/Pozn.: Staccato odkazuje na noty, které jsou jednotlivé|a oddìleny od sebe navzájem chvilkou ticha./
{6532}{6568}Dìlejte rozdíly mezi tìmi hoslouvımi vázáními zøetelné.|/Pozn.: Staccato odkazuje na noty, které jsou jednotlivé|a oddìleny od sebe navzájem chvilkou ticha./
{6601}{6666}Mìl jsem to èekávat. Všichni jsou opravdu nadaní, a mají skvìlou intuici.
{6693}{6738}Reagují na všechno okamitì pøesnì tak jak chci.
{6768}{6856}Všechno to, co je zanecháno pro kadı oddíl,|prohlubuje porozumìní, jak dílo pøedpokládá postupovat.
{6903}{6917}Ale, i tak...
{6948}{6992}Tento orchestr je neuvìøitelnı.
{7092}{7153}Chiaki-senpai, hraješ Mozarta?
{7199}{7258}Chiaki-senpai, ty a Mozart?!
{7258}{7281}Co je na tom tak smìšného?!
{7281}{7396}Jen to, e Mozart je rùovı! Je rùovı!
{7396}{7446}Rùovı? O èem to mluvíš?
{7461}{7512}Jakmile dojíš, pohni a jdi domù!
{7512}{7550}Musím se vrátit ke svım studiím.
{7550}{7585}Ah, prosím poèkej!
{7585}{7631}Víc, prosím. Ráda bych víc.
{7648}{7712}Stále mùeš jíst víc? To bude tvoje ètvrtá miska.
{7749}{7855}Promìnilo se to všechno o èem se mluvilo o Nodame na "picím veèírku" ve stín?|/za tu vìtu se omlouvám, ale prostì mi nedává smysl.../
{7878}{7930}Pøijdu domù, a ona je stejná jako vdycky.
{7930}{7968}Pøijde sem a celou dobu jí.
{7986}{8040}Jak se ti daøí s tvımi vlastními studiemi?
{8052}{8085}Ah, to mi pøipomíná, Senpai.
{8101}{8209}Pøíštì ti ti nìjakou svaèinu na zkoušku tvého orchestru.
{8209}{8269}Byly by citrony s dotekem medu zase dobré?
{8269}{8300}Neopovauj se pøijít!
{8300}{8323}Neopovauj se!
{8347}{8372}Proè ne?!
{8372}{8402}Neptej se. Jen nechoï.
{8428}{8470}Tentokrát není mùj orchestr jen pro zábavu.
{8491}{8539}Vezme to peníze, aby se to stalo, ale také to získá peníze.
{8556}{8632}A, pokud jde o mì...
{8632}{8687}Nechci mít víc ádnıch divnıch vztahù jako pøedtím.
{9125}{9207}Místo nazıvání tohoto rùovım, rád bych |øekl, e to bylo víc kouøové støíbrné.
{9236}{9362}Kdyby jen mohl hrát s trochou víc toho lehkého|citu, kterou normálnì cítíš v Mozartovıch dílech...
{9428}{9465}Koneènì, pøestávka!
{9480}{9502}Jsem vyèerpanı.
{9502}{9560}Chiaki-kun je tak pøísnı!
{9731}{9793}Pøinesla jsme ti nìjakou polévku miso a rıové koule!
{9793}{9857}Hej... neøekl jsem si, abys nechodila?
{9857}{9926}Jsem tu jen, abych tu nechala obèerstvení. Brzo odejdu.
{9952}{10020}Ah, támhle jsou všichni z orchestru?
{10020}{10053}Musím se pøedstavit.
{10077}{10096}Poèkej vteøinku!
{10096}{10136}Proè by se's jim musela pøedstavovat?
{10136}{10171}P-Protoe jsem tvoje manelka.
{10171}{10234}Nepøedpokládala jsi dneska mít vyuèování?
{10272}{10361}N-No, Sensei dneska zvracel...
{10395}{10415}Proè se díváš pryè?
{10477}{10553}Pak pùjdu dát Taniokovi-sensei hovor brzkého uzdravení.
{10574}{10608}Ne, mılila jsem se!
{10608}{10664}Opravdu jsem myslela øíct, e je na dovolené se svou rodinou v Mexiku!
{10679}{10722}Vìdìl jsem to. Pùsobíš trochu divnì.
{10748}{10804}Nikdy pøedtím jsi nevynechala své vyuèování.
{10827}{10849}Proè se schováváš?
{10891}{10909}Chiaki-kun.
{10923}{10959}Ah, promiò.
{10972}{11016}Jestli jsi zaneprázdnìnı, mùu tì dohonit pozdìji.
{11060}{11130}To je v poøádku! Je v poøádku. Vùbec není zaneprázdnìnı.
{11162}{11242}Umm, jsi èlenem orchestru Chiakiho-senpai, e?
{11242}{11288}Uh, ano.
{11288}{11324}Dnes jsem pro všechny pøinesla nìjaké obèerstvení. Prosím vem si nìco.
{11324}{11378}Dnes jsem pro všechny pøinesla nìjaké obèerstvení. Prosím vem si nìco.|/Úsmìv dobré manelky./
{11378}{11433}Je to jen polévka miso a rıové koule.
{11433}{11490}Prosím, dìlej co mùeš v dnešním cvièení.
{11490}{11524}Promiò, e jsem tì vyrušila.
{11524}{11590}/Chùze dobré manelky - Pùvabnì/
{11607}{11635}Ta holka...
{11635}{11684}Urèitì to na ni pozdìji prásknu!
{11684}{11712}Chiaki-kun.
{11740}{11800}To je tvoje pøítelkynì?
{11800}{11862}Coe? M-Musíš si dìlat legraci.
{11862}{11904}Je to jen jedna z mıch kouhai na univerzitì.
{11904}{11928}Ještì jednou, jaké bylo její jméno?
{11945}{12039}N-Noda Megumi. Kuroki-kun?
{12134}{12190}Noda... Megumi-chan.
{12200}{12253}/Jemnı vánek/
{12601}{12658}To je jedna z Bachovıch "Sonát a Partit pro Sólové Housle."
{12658}{12703}Miluji tohle dílo a také ho hodnì hraju.
{12740}{12791}Ale, její verze zní od mé naprosto rozdílnì!
{12791}{12815}Je úasná!
{12870}{12902}Jak mùe udìlat hra na housle takovı zvuk?
{12984}{13015}Prosím udìlej ze mì tvého áka!
{13050}{13080}Prosím dávej mi soukromé lekce!
{13080}{13118}Kdykoli máš volno by bylo dobré!
{13118}{13199}Pohostím tì èímkoli! Namasíruju ti ramena!
{13199}{13236}P-Proè bych mìla?
{13268}{13302}Máš uèitele ve škole, ne?
{13302}{13362}Jsi daleko lepší ne oni!
{13362}{13419}Ne, je to tak, e to miluju!
{13419}{13473}Miluju tvou hru na housle, Kiyoro!
{13582}{13606}Hej, no tak.
{13621}{13669}Zlobili byste se vy dva, kdybych zaèal cvièení?
{13753}{13779}Ano! Prosím!
{13826}{13863}Tentokrát ádné divné vztahy!
{13908}{13951}Vezmìme to od vrcholu tøetího pøesunu.
{13982}{14058}Ah, pardon. Zapomnìl jsem si vypnout svùj mobil.
{14058}{14105}Poèkejte vteøinku.
{14121}{14210}Ahoj, Yukko-chan? Právì teï uprostøed zkoušky.
{14210}{14229}Vypni to!
{14229}{14321}Coe? Nelu. Je to pravda.
{14321}{14365}Nepodvádím tì.
{14424}{14461}Vidíš? Mùeš to slyšet?
{14488}{14525}Všechny tyhle pøíliš útulné vztahy...
{14795}{14860}Orchestr hrál kouøovou støíbrnou.
{14879}{14950}Teï hraje r-rùového Mozarta?!
{15092}{15133}Nodo Megumi!
{15133}{15166}Kde jsi?!
{15166}{15227}Vím, e jsi nìkde na školní pùdì!
{15253}{15335}Jestli vynecháš všechny své lekce, budeš muset celı tento rok opakovat!
{15335}{15363}Slyšíš mì?!
{15363}{15425}Teï je tvoje jediná šance vylézt!
{15425}{15462}Cítím se tak ponuøe...
{15462}{15500}Pøeklad + korekce + èasování: WelW(etkaAa)-hime
{15548}{15600}"Uèební plán Nodame-sensei"?
{15600}{15705}Nodame, neøíkej mi, e budeš uèitelkou?
{15705}{15766}Jo. Vracím se v èervnu ke své alma mater.
{15766}{15850}Ugh! Ty, Nodame, uèitelkou?
{15850}{15896}Co myslíš tím, "Ugh"?
{15896}{15966}Ale je to pro studenty niší støední, ne?
{15966}{16011}Budou si tì opravdu dobírat.
{16011}{16034}Budeš donucená.
{16034}{16129}Nodame, nechtìla jsi bıt uèitelkou v mateøské školce?
{16149}{16243}No, jo, ale máma øekla, e bych tohle mìla dìlat taky, jen pro pøípad.
{16243}{16348}A mimoto, nemùu dostat licenci stát se uèitelkou v mateøské|školce na mé hudební univerzitì doma.
{16348}{16395}To ne! Opravdu?
{16395}{16459}Jo, zjistila jsem to minulı rok.
{16476}{16647}To proto jakmile odpromuju, budu dìlat brigádu v mimoškolním|centru hlídání dìtí, kde mi Minùv táta øekl, e mì pøedstaví,
{16647}{16731}a udìlám si dálkové studium, abych dostala uèební licenci.
{16731}{16776}To je úasné.
{16776}{16829}Opravdu pøemıšlíš o své budoucnosti.
{16865}{16880}Jsem v hlubokıch problémech.
{16944}{17014}Maki-chan, ještì jsi nepomyslela na svou vlastní budoucnost.
{17014}{17107}Všichni studenti niší støední projdou pubertu se zmìnou hlasu!
{17107}{17157}"Nodame-sensei, máte pøítele?"
{17157}{17269}"Oh boe, nejsti ty pøedèasnì vyspìlı chlapeèek! Samozøejmì, e mám."
{17269}{17314}"To je mùj pøítel."
{17314}{17355}"Nue, ahoj tady. Jsem její manel."
{17355}{17445}Oh ne! Nakreslila jsem Chiakiho-senpai pøíliš tlustého!
{17445}{17492}Vypadá jako ten uèitel plácající-papírovım-vìjíøem.
{17492}{17527}Kdo je teï pøíliš tlustı?
{17640}{17687}Nodamin novı uèitel je ten plácaè-papírovım-vìjíøem?
{17687}{17766}Oh, ještì jsi to nevìdìl, Chiaki-kun?
{17766}{17817}P-Proè ta náhlá zmìna?
{17839}{17882}Tak proto onehdy vynechávala svoje lekce!
{17882}{17980}Nehráli jste vy dva minulı rok Rachmaninova?
{18028}{18128}Po poslechu vašeho duetu, zaèal bıt Etou-sensei zaujatı Nodou-kun.
{18128}{18188}Take on nás ten den slyšel hrát.
{18233}{18251}Poèkej!
{18251}{18330}Dneska nemám vyuèování! Porušujete pravidla!
{18330}{18386}Dnes si nahradíme ten den, co jsi vynechala!
{18386}{18462}Dnes se necítím dobøe!
{18462}{18502}Utíkáš!
{18502}{18543}Pøedstavujete si vìci!
{18543}{18593}Jako by!
{18609}{18632}Vidím, e vìci jsou u mezi nimi napjaté.
{18632}{18653}Poèkej!|Vidím, e vìci jsou u mezi nimi napjaté.
{18679}{18758}Není ádnı zpùsob, e by všechno dopadlo dobøe.
{18777}{18824}Ani já jsem ho nemohl vystát.
{18848}{18983}Jestli z ní chcete nìco udìlat, mìl byste bıt tím, kdo to udìlá, Tanioko-sensei.
{19002}{19042}Chápej, Chiaki-kun,
{19042}{19177}nejsem dostateènì odhodlanı jako uèitel,| abych motivoval nemotivované studenty.
{19274}{19349}Ale studenti jsou mí vzácní zákazníci.|/Naprosto motivovanı/
{19349}{19472}Chci jim poskytnout všechnu pomoc a asistenci, kterou mùu,|tak, e si splní své sny a nadìje.
{19472}{19666}A ptoto za poslední tøi roky, dávám všechno své usíli|do pøedvedení jejího Fart Calisthenics a Scraggly-Haired Medley.
{19700}{19835}Vím, e to øíkám dost pozdì, ale podle jejího|názoru to pravdìpodobnì není ádná naše starost.
{19857}{19937}To je, motivace Etoua-kun a pocity, které k ní máš ty a já.
{20000}{20129}Ale cítím, e se na Nodì-kun v poslední dobì nìco zmìnilo,
{20129}{20204}aèkoli si to sama ještì moná neuvìdomila.
{20349}{20380}Mami! Podívej se támhle!
{20400}{20444}Starı chlap je pøilepenı na plotì.
{20444}{20501}No tak, no tak! Nemìl bys na vìci takhle dívat!
{20857}{20893}Noda... Megumi-chan?
{20965}{21005}Kluk z orchestru Chiakiho-senpai...
{21050}{21078}Nejdøíve mì nech potvrdit, jestli je to bezpeèné.
{21078}{21095}Nikde ádné kníry.
{21141}{21175}Jak se máš?
{21206}{21232}Ah, vím.
{21232}{21291}Díky za obèerstvení onehdy.
{21306}{21364}Jsem Kuroki Yasunori z Hudební Univerzity Morimitsu.
{21364}{21430}Tvé rıové koule... byly opravdu vynikající.
{21459}{21491}Jaká byla polévka miso?
{21491}{21602}Ah. P-Polévka miso byla samozøejmì taky dobrá.
{21602}{21622}V kadém pøípadì mi to chutnalo.
{21622}{21659}/Èestnı mu/
{21696}{21757}Je dneska další zkouška orchestru?
{21757}{21772}Jo.
{21821}{21886}Take všichni se shromaïují tak brzy.
{21886}{21968}Ne. Zkouška není a do tohoto veèera.
{22001}{22048}Jen jsem tì chtìl znovu vidìt.
{22063}{22155}Myslel jsem si, e bych pøišel trochu døíve, abych si vyøezal své jazıèky.
{22155}{22169}Tvoje jazıèky?
{22221}{22274}Dneska nemám školu, take mám ve svıch rukou nìjakı volnı èas.
{22299}{22349}Hraješ na dechovı nástroj, Kuroki-kun?
{22349}{22387}Jo, na hoboj.
{22440}{22490}Take takhle vypadá jazıèek hoboje.
{22538}{22612}Vyøezal jsi tyhle všechny sám?
{22626}{22754}Prodávají jazıèky pro klarinety a saxofony, e|mùeš pouít právì ty bez toho, abys je vyøezával.
{22754}{22811}Ale pro hoboj si je musíš udìlat sám.
{22811}{22864}Zní to jistì jako hodnì práce.
{22864}{22936}Jestli nejsou udìlány poøádnì, zvuk nebude dobrı, e?
{22936}{22950}Jo.
{22974}{23079}Jak je udìláš je samozøejmì taky dùleité, ale poèasí mùe taky zmìnit vìci,
{23079}{23153}take to zabere hodnì práce, a jsem nad tím vdycky zpocenı.
{23170}{23256}Hodnì lidí øíká, e není ádná taková vìc jako dokonalı jazıèek,
{23256}{23347}ale øíkající, e tímto zpùsobem zní hoboj jako nedokonalı nástroj.
{23373}{23396}Nedokonalı...
{23433}{23494}Ale navzdory tomu to dìlám rád!
{23494}{23591}Opravdu miluju dìlání jazıèkù, a vlastnì se cítím víc| pøipojenı k jazıèkùm, které trvají déle.
{23591}{23686}Taky miluju zvuk, kterı dìlají, aèkoli si hodnì lidí| vdycky myslí, e je to jen prostı nástroj.
{23686}{23751}Huh? Lidé o nìm pøemıšlí tímto zpùsobem?
{23751}{23779}No, ne...
{23779}{23862}Taky miluju zvuk, kterı dìlá hoboj.
{23887}{23919}/Štìstí.../
{23939}{24031}Orchestrování zní opravdu jako velká zábava.
{24031}{24105}Megumi-chan, ty hraješ na klavír?
{24105}{24134}Ano.
{24134}{24153}Není to zábava?
{24176}{24260}Je. Miluju klavír.
{24306}{24360}Proè nemíøíš vıš?!
{24394}{24466}Objevím v tobì hraní na klavír!
{24514}{24631}Kuroki-kun, míøíš vıš, jako stát se profesionálem nebo nìco?
{24631}{24678}Huh? Vıš?
{24736}{24784}No, pro teï, rád bych øekl, e je to mùj cíl.
{24784}{24933}Pak by nemìlo bıt podivné pro nìkoho, jeho cíl je bıt|uèitelkou v mateøské školce, míøit pro stejnı "vyšší" cíl?
{24991}{25060}Nejsem si jistı tímhle "vyšším" cílem, o kterém mluvíš,
{25060}{25162}ale jestli hraju jednoduše hudbu dobøe, dìlá mi to radost.
{25162}{25249}A jestli se zlepším, rád bych si myslel, e by to byla ještì vìtší zábava ne pøedtím.
{25268}{25324}To proto, kdy o tom pøemıšlím tímhle zpùsobem, opravdu si hraní uívám.
{25341}{25377}Nemyslíš si to?
{25600}{25615}Chiaki!
{25762}{25822}Co se dìje s tvou enou?!
{25838}{25913}Jakı druh èlovìka je?
{25913}{25945}Je to nìjaká pneumotická-hlava podivínka?
{25945}{26046}Nebo mì obtìuje kvùli tomu, co jsi jí øekl?
{26060}{26129}Není to moje ena, ale je to podivínka.
{26154}{26182}A neøekl jsem jí o vás nic.
{26182}{26280}Tak proè s ní nemùu mít normální vyuèování?
{26280}{26336}I jestli je podivínka, stále je studentkou hudební univerzity!
{26351}{26424}Sám nedìláte normální vyuèování, ne?
{26470}{26569}Nikdy jsem kolem nevidìl jiného uèitele, kterı nosí papírovı vìjíø.
{26607}{26658}To není obyèejnı papírovı vìjíø.
{26658}{26691}Je to ztìlesnìní mé lásky.
{26723}{26826}Poslal jsem hodnì klavíristù do svìta s tímto papírovım vìjíøem.
{26842}{26903}A kadı z nich je teï za to vdìènı!
{26926}{26961}Aèkoli tu byla jedna vıjimka...
{26961}{26975}Aèkoli tu byla jedna vıjimka...|/Vıjimka/
{27010}{27067}Pojïme se nad tím zamyslet, já taky...
{27097}{27161}dìlal vìci, jako bití jí papírovım vìjíøem.
{27222}{27332}Ale pak, proè utekla od plácaèe-papírovım-vìjíøem, ale ne ode mì?
{27360}{27394}Jakı je mezi námi rozdíl?
{27394}{27420}/Pøíliš sebejistı/
{27420}{27457}Je to o sympatii a antipatii?|/Pøíliš sebejistı/
{27486}{27500}Umm...
{27544}{27595}Pro teï, moná jste schopnı...
{27615}{27645}Dìkuji vám mnohokrát.
{27663}{27684}Vítejte.
{27749}{27842}To je Puri-Gorota! Wow! Jsou opravdu vzácné!
{28372}{28439}To je jedna z tìch Puri-Gorota figurek, které pøicházejí se sladkou sodovkou lamune!
{28439}{28488}350 yenù jedna!
{28568}{28580}Fiona!
{28661}{28677}Michael!
{28765}{28782}Máma!
{28815}{28835}Curly!
{28867}{28886}Táta!
{29001}{29035}A koneènì Kazuo...
{29155}{29209}Dnes jsem ti pøinesl balenı obìd na naši lekci.
{29223}{29243}Hej!
{29243}{29280}Neutíkej! Poèkej vteøinku!
{29280}{29330}U jsem odhodil svùj papírovı vìjíø!
{29382}{29420}Je to pravda! Podívej se na mì.
{29420}{29447}Jsme neozbrojenı!
{29462}{29556}Zmìnil jsem se. Taky se ti omlouvám za bití tì pøedtím.
{29556}{29581}Omlouvám se!
{29581}{29668}Take, prosím vezmi mé lekce jako normální èlovìk.
{29789}{29859}Mám tedy jen jednu laskavost na poádání.
{29958}{30007}Vytvoøme spolu úasnou Scraggly-Haired Medley.
{30045}{30117}Pak, zaènìme s balenım obìdem!
{30117}{30218}Ne! Jezme a po lekci!
{30330}{30367}Jen musím vydret tuhle jednu píseò.
{30441}{30534}Jakmile ukonèíme vytváøení této písnièky, má skuteèná lekce mùe koneènì zaèít!
{30588}{30656}Mìla by si's to lépe zapamatovat, Nodo Megumi!
