{1}{1}23.976
{40}{85}/Lidské vzpomínky mají sklon stávat se zdobenımi/
{102}{149}/Vzpomínka/|Stop! Stop!
{227}{266}V té druhé èásti, kdy hraje trubka, je chyba.
{443}{477}Nechceš sem jít a dirigovat místo mì?
{477}{498}Opravdu mùu?!
{498}{532}/Realita/
{572}{623}Sni dál! U se tu víckrát nepotuluj!
{648}{682}/Vzpomínka/
{694}{723}Prosím, chci bıt váš student!
{788}{818}Umíš hrát na nìjakı hudební nástroj?
{840}{884}Na housle a trochu na klavír!
{884}{915}/Realita/
{931}{1001}Chápu… ale u sem nikdy nechoï, rozumìl's?
{1001}{1036}/Lidské vzpomínky mají tendenci stávat se hezèími/
{1061}{1081}/Aèkoli.../
{1093}{1105}/Nìkdy se vzpomínky…/
{1149}{1223}Za chvíli budeme pøistávat! Prosím pøipoutejte se a skloòte hlavy dolù!
{1223}{1247}/Vzpomínky…/
{1295}{1346}/Vzpomínky…/
{1416}{1464}TaSHee's Gang uvádí...
{1521}{1612}NODAME CANTABILE
{3517}{3545}LEKCE 1
{3616}{3653}/Vzdìlávací nadace hudební akademie Momogaoka/
{3673}{3691}Ona stojí za houby.
{3729}{3748}On stojí taky za houby.
{3806}{3843}Kadı tady sakra stojí za houby!
{3872}{3936}Hej, dívej, dívej! To je Chiaki!
{3936}{3979}TEN Chiaki!
{4002}{4028}Take to je on, o kom se poøád mluví.
{4046}{4167}Je to syn pianisty Masayukiho Chiaki a stejnì jako jeho otec, i on bude hodnì dobrı ve høe na piáno.
{4201}{4233}Mnì pøijde dost nafoukanı.
{4369}{4422}Hele! Ten dirigující student Hayakawa pojede studovat do Nìmecka!
{4435}{4471}Nekecej! To je bomba!
{4486}{4580}Sakra u s tím! Co tu ještì dìlám?
{4641}{4674}Co to k èertu dìláš?!
{4723}{4789}Neukonèuj tu skladbu tak, kdy jsi zaèal hrát tak vesele! Zatracenı idiote!
{4817}{4883}Myslel jsem, e máš Beethovenovy skladby rád!
{4926}{5002}Proto jsem si tì taky vybral jako mého studenta, abys hrál na školním koncertì.
{5048}{5063}Co to sakra je?
{5083}{5105}Part pro dirigenty…?
{5130}{5187}Proè k èertu ty, pianista, máš s sebou part pro dirigenty?
{5213}{5269}Dokonce si pøidal své vlastní noty…
{5310}{5383}Ty snad plánuješ bıt dirigent nebo co?
{5395}{5413}Nebuï smìšnı!
{5413}{5468}Tak tak ti jde hraní na klavír tak pøestaò vymıšlet takové blbosti a…
{5468}{5498}Mohl byste sklapnout, dìdku jeden?
{5523}{5579}Uèíte svoje hodiny, jakoby vám studenti nìco dluili!
{5579}{5642}Tak mají vypadat "elitní hodiny uèené velkım Etou?" To urèitì!
{5661}{5697}"Forte, forte con fuoco!"|/"Silnì, silnì, jako oheò."/
{5697}{5771}Všichni vaši studenti hrají sakra úplnì stejnì!
{5771}{5788}Je mi z toho nanic!
{5788}{5825}Proè se prostì nevrátíte zpátky do Španìlska, vy uèebnicovej kreténe!
{5919}{5962}Je to všechno?
{5974}{6003}Jakoe mám pokraèovat?
{6003}{6043}Ne, zapomeò na to.
{6077}{6148}Nejsi dobrı. Spletl jsem se v tobì.
{6260}{6275}Ano.
{6319}{6359}Chci se stát dirigentem.
{6417}{6524}Kdy jsem byl malı, mùj táta mì vzal na všechny moné typy pøedstavení.
{6569}{6619}Nejvelkolepìjší orchestry v celé Evropì!
{6650}{6693}Dirigování Sebastiana Viery...
{6736}{6768}Jo, to je ono…
{7106}{7164}Beethovenova klavírní sonáta Pathétique…
{7211}{7248}Naprosto nesladìné.
{7302}{7333}S tímhle hraním by se to mohlo jmenovat "Ubohé!"
{7454}{7516}Ne… moná to neladí, ale vùbec to nezní špatnì!
{7623}{7655}Zní to opravdu ohromnì!
{7655}{7684}Odkud to jde?
{7725}{7743}Kdo to…
{7769}{7786}Shinichi!
{7848}{7914}Je pravda, e tì profesor Etou vyhodil?
{7929}{7947}Saiko...
{8005}{8047}Bì se omluvit a poádej ho o odpuštìní!
{8063}{8081}Proè?
{8094}{8112}"Proè?"
{8129}{8214}Je to ten nejproslulejší a nejschopnìjší uèitel na celé škole!
{8241}{8337}Na to kašlu. Stejnì nechci bıt pianista.
{8394}{8472}Tak proè prostì neodejdeš z klavírní školy a nezkusíš to dirigování?
{8488}{8508}Musím víc cvièit na klavír.
{8530}{8599}A mimo to, jedinı uèitel dirigování pro mne je mistr Viera.
{8617}{8653}Nechci se uèit nic jiného, bylo by to k nièemu.
{8714}{8757}Tak proè nejdeš studovat do zahranièí?
{8788}{8861}Všechno to jsou kraviny, ani nejsi schopnı nastoupit do letadla, protoe se jich bojíš!
{8922}{8982}Jak to mùeš pochopit, kdy si nikdy nebyla v letadle, které pøistálo na bøicho!
{8982}{9024}Tak jeï lodí.
{9069}{9098}S lodìmi je to podobné!
{9134}{9171}Moøe je stejné jako vesmír!
{9188}{9246}Není tam vzduch, a jsi uvìznìna sama v temnotì!
{9320}{9383}Chápu, málem se's kdysi utopil.
{9445}{9504}Moná… bych mìl s hudbou nadobro skoncovat.
{9535}{9618}I kdy se stanu profesionálem v Japonsku, pokud nebudu hrát v Evropì, nemá to smysl.
{9643}{9728}Moná mì tvoji rodièe nechají pracovat jako dìlníka v jejich rodinné firmì Tagaya Musical Instruments.
{9837}{9884}Nechoï dnes domù…
{9945}{9965}Nech tìch øeèí!
{9977}{10043}My u spolu nechodíme.
{10066}{10080}A kromì toho...
{10080}{10114}Nesnáším takové ztroskotance!
{10204}{10219}Sakra!
{10454}{10537}Jedno malé koátko, pam pam…
{10621}{10684}Tyhle tìké schody, pam pam…
{10935}{10968}To je ten…!
{11426}{11440}Vítr!
{11479}{11511}Slyším vìtøík, jak fouká…
{11565}{11616}A teï…klavír?
{11670}{11697}Co je to za píseò?
{11745}{11847}To je… ta co jsem slyšel u døíve, Beethovenova…
{12230}{12288}Uprostøed hromady odpadkù… tahle krásná sonáta…
{12346}{12380}Capriccioso cantabile.
{12406}{12460}Nepøedvídatelná… stejnì jako ta skladba.
{12803}{12845}U jsem si vzpomnìla! Ty jsi Chiaki, e?
{12912}{13000}Hehe, pamatuješ si nìco z toho, co se stalo vèera?
{13091}{13115}Hej, senpai!
{13341}{13391}To je… mùj panelák?
{13416}{13443}A tohle jsou dveøe vedlejšího bytu…
{13508}{13557}Chiaki-senpai!|/Svinstvo/
{13573}{13623}Co to bylo za holku?!
{13623}{13649}Pøeklad: j-dawe
{13649}{13687}Korekce + èasování: WelW(etkaAa)-hime
{13787}{13824}Tøeští mi hlava.
{13837}{13875}To sem vánì vèera pil tak moc?
{13887}{13939}Sakra, kvùli Saiko…
{14055}{14092}Krom toho, kdo byla ta holka?!
{14110}{14155}Chiaki-senpai!
{14170}{14210}Tvùj pásek!
{14266}{14315}Nechal si ho u mì!
{14378}{14417}Ten… ten není mùj!
{14436}{14449}Ha?
{14463}{14480}Nodame?
{14480}{14579}Je tvùj, vím to, protoe jsem ti ho vèera sundala.
{14579}{14600}Musíš si mì s nìkım plést!
{14618}{14642}To není mùj pásek.
{14642}{14684}Byl jsi to ty, senpai!
{14684}{14696}Ne, nebyl.
{14696}{14731}Našla jsem tì pøed svım bytem.
{14731}{14763}To jsem urèitì nebyl já!
{14763}{14796}Ale ty voníš stejnì jako ten pásek!
{14808}{14829}Nodame...
{14846}{14880}…chodí s Chiakim?!
{14961}{15056}Tanioka Hajime… to jméno jsem ještì neslyšel.
{15082}{15147}Dobrá, stejnì nemùe bıt horší ne ten uèitelskej zoufalec.
{15166}{15188}Hej!
{15198}{15212}Hej!
{15222}{15245}Prd!
{15282}{15311}Ta holka…!
{15362}{15423}Není to super jako souèást hraní?
{15452}{15486}Je! Skvìlé!
{15486}{15514}Zvláš ten konec!
{15557}{15607}Dobøe, pojïme to zkusit ještì jednou.
{15607}{15621}/Ano!/
{15646}{15731}Tohle má bıt mùj novı uèitel??? |/Trochu ivota do toho. Pojïme si poslechnout nìco dobrého!/
{15731}{15783}/Do re mi fa prd prd prd! Bam!/ 
{15783}{15819}Jsem snad prokletı nebo co?
{15833}{15892}Slyšet profesora Tanioku smát se…
{15892}{15962}Prı jen bere studenty, co jsou pozadu, e?
{16007}{16051}Jeho hodinám øíkají "škola fiaska."
{16103}{16162}Jsem… fiasko?
{16330}{16354}Sakra...
{16354}{16426}Tady v Japonsku je takové dusno, e nemùu dıchat.
{16491}{16598}Kdy nemùu odsud utéct, moná bych se mìl hudby vzdát.
{16655}{16682}/Zápach/
{16682}{16712}Co je to za smrad?!
{16730}{16748}Line se to od sousedù?
{16768}{16797}Z jejího pokoje, heh?
{16846}{16918}C-Co to k èertu je?
{16989}{17016}/Dus/
{17037}{17053}/Mravenci/
{17150}{17163}U jdu!
{17196}{17221}Chiaki-senpai!
{17221}{17269}Co se dìje?
{17303}{17379}Ah, u vím! Ty chceš svùj pásek zpátky!
{17379}{17400}Z cesty!
{17482}{17552}Vypadá to vánì… jako stejnı typ mého bytu?
{17572}{17624}Senpai? Mám tvùj pásek právì tady.
{17624}{17652}Èištìní...
{17677}{17718}Okamitì vyndej všechny èistící prostøedky!
{17761}{17819}Sakra! Co to je paneboe za horu odpadkù?!
{17832}{17849}Zbavím se toho všeho!
{17849}{17866}Hej, toho ne!
{17866}{17944}V té krabici mám všechny sešity a uèebnice!
{17969}{17987}Co je tohle?!
{18002}{18032}P-Pøipálená smetana...
{18032}{18049}A tohle?!
{18049}{18076}Lososí jikry s rıí…
{18088}{18107}A tahle houba?!
{18107}{18135}Nìco co by mìlo bıt umyto…
{18146}{18157}Tohle?!
{18167}{18183}Nemìla jsem jinou monost!
{18210}{18245}Hej, moje podprsenka!
{18245}{18270}Moje kalhotky!
{18270}{18307}Hlína, kterou jsem nasbírala na Koshien stadionu!
{18307}{18339}Zmlkni!
{18339}{18369}/O nìkolik hodin pozdìji/
{18466}{18494}Jsem to ale vùl.
{18540}{18627}Nejdøív se tak orat, pak tady dìlat uklízeèku…
{18760}{18786}Pathétique…?
{18874}{18896}Její hraní na klavír…
{18963}{19005}…prostì skvìlé.
{19043}{19058}Má na to dobré ruce.
{19082}{19122}Hraje ty nejsloitìjší úseky jakoby nic!
{19210}{19221}Ah!
{19221}{19248}Tady jsi to pokazila!
{19286}{19323}Sna se tu èást hrát znovu stejnì dobøe jako pøedtím!
{19349}{19435}Jak jsem to pøedtím hrála?
{19503}{19529}Takhle, vzpomínáš?
{19576}{19637}Ona to vánì hraje takhle dobøe.
{19657}{19695}Ale… je to zajímavé .
{19746}{19818}Cantabile… hraje to jako píseò.
{19908}{19951}Co? My dva spolu?
{19965}{20063}/Jé! Senpai! Dìkuji za další lekci!/|Nechceš to zkusit? Zahrát si duet s Nodou? 
{20083}{20095}Nebuïte smìšnı!
{20111}{20150}Proè jako musím hrát spolu s touhle nulou?
{20160}{20191}Já se jmenuji Noda Megumi!!!
{20205}{20236}Ale prosím tì øíkej mi Nodame.
{20236}{20340}To je mi fuk a stejnì není moné, abych se sladil s jejím bláznivım stylem hraní!
{20359}{20449}Jsem si jistı, e to zvládneš. Jsi nejlepší pianista na škole.
{20471}{20529}A se svımi dirigentskımi zkušenostmi…
{20541}{20615}/Slyšel jsem, e jsi Nodu nauèil jednu skladbu hrát perfektnì. To samo o sobì je úasné! /|Myslím, e mì hraní na klavír baví víc! 
{20636}{20702}Zkus si to promyslet, mohl bys ji vést.
{20726}{20761}Vést ji??
{20810}{20912}Zaènìme s Mozartovou Sonátou v D major pro dva klavíry.
{20957}{20977}Tuhle neznám…
{21005}{21035}Ani já ne.
{21035}{21106}Je to opravdu rychlá skladba, take si myslím, e to bude tìké udret hraní synchronizovanì.
{21106}{21157}Teï si to klidnì zkuste v pomalejším tempu.
{21182}{21193}/Netrpìlivı/
{21193}{21262}Hej, dáme si pìt minut na prostudování a potom zaèneme.
{21291}{21357}Chiaki, ta skladba je dlouhá zhruba osm minut.
{21357}{21385}Tak si dáme osm minut!
{21385}{21414}Osm minut!
{21414}{21439}/O 8 minut pozdìji…/
{21465}{21517}To není ostuda zaèínat v pomalém tempu…
{21518}{21534}Tak do toho.
{21574}{21666}Na zaèátku hrají klavíry spolu ve tøetí oktávì.
{21787}{21838}Musíš to kazit u po dvou taktech?!
{21869}{21882}Ještì jednou!
{21882}{21911}A-Ano...
{22113}{22127}Proè...
{22152}{22185}Proè to zní tak blbì?!
{22264}{22303}Vdy ty se ani nedíváš na noty!
{22316}{22444}Noda si umí zapamatovat vše, co uslyší, take není moc zvyklá èíst noty.
{22489}{22543}Tak proto je její hraní vdycky tak nahodilé?
{22659}{22682}U jsem se o ten binec postarala.
{22682}{22734}Já tu nejsem, abych uklízel! Jsem tady, abych s tebou cvièil!
{22734}{22745}Ne!
{22745}{22773}Co myslíš tím "Ne?!"
{22953}{23024}Vdy to ještì není ani tıden..!
{23063}{23112}Je-Je mi to líto…
{23159}{23214}Je to proto, e jsem si ještì nebyla tu skladbu schopna zapamatovat…
{23214}{23265}Ale nìjak to u zvládnu, tak…
{23284}{23326}Kdybys mi dal ještì tıden…
{23358}{23389}Nemùu èekat tak dlouho.
{23416}{23500}Ukáu ti, jak na to, tak dobøe poslouchej tìma zázraènıma ušima.
{23652}{23711}U to chápeš? Pùvodní skladatelovu myšlenku máš pøímo tady!
{23731}{23798}Pøed tím, ne to budeš hrát se mnou, musíme se ujistit, e to zvládneš zahrát sama.
{23846}{23889}Špatnì! Nehrej to tak nebo onak!
{23912}{23944}Poslouchej dobøe, jak to zní, kdy hraju.
{23991}{24014}Pøestaò se tak ksichtit!
{24021}{24061}/Nevìdoma si toho/
{24090}{24131}V kadém pøípadì u nedìlá tolik chyb.
{24182}{24226}Ale je to trochu…
{24241}{24295}Zkazila jsem zase nìco?
{24309}{24328}Kde to bylo?
{24328}{24344}...zvláštní...
{24344}{24378}Nièeho jsem si nevšimla…
{24462}{24475}Nìco tu smrdí…
{24506}{24526}Tvoje hlava smrdí.
{24541}{24637}Fakt? Ale jsem si jistá, e jsem si myla vlasy pøed ètyømi dny…
{24822}{24861}To je pøíjemné…
{24861}{24908}Co to dìlám?
{24924}{24968}Dobrovolnì se obìtovat a dìlat tohle…
{24987}{25048}Cítím se jako královna!
{25076}{25113}A já se cítím takhle…
{25150}{25218}Vánì? Jako peèovatel psù? To je bomba!
{25218}{25312}Lidi mì vdycky pøirovnávali spíš k rybì, jako k ropušnici nebo tak…|/Bıt s ní, to bude trochu…/
{25312}{25362}…ale tohle je poprvé co mì nìkdo pøirovnává k savci!
{25362}{25428}Ne… bude to trochu problematické, dalo by se øíct.|/A jaké jsem plemeno?/
{25495}{25516}Tak, teï vám to zahrajeme.
{25516}{25551}Dobrá, snate se.
{25629}{25756}Nodame, hrej jakkoliv to cítíš. Dneska to smíš zahrát libovolnì.
{25800}{25890}Uznávám, e je v ní nìco zvláštního…
{25923}{26049}A… jedinı kdo s ní umí dret tempo… jsem já!
{26212}{26243}Do teï jsme zatím skvìlí.
{26261}{26326}Problémy… právì zaèaly.
{26326}{26380}Právì otevøela víko Pandoøiny skøíòky…
{26421}{26511}Protoe jsem jí øekl, aby to hrál libovolnì… nejde pøíliš do hloubky.
{26535}{26553}Ale já jí staèím!
{26599}{26623}Udrím s ní krok, a se stane cokoliv!
{27224}{27345}Protoe se moji rodièe rozvedli, byl jsem nucen odejít s matkou domù do Japonska…
{27373}{27541}Mistøe, já se rozhodnì stanu dirigentem, tak vás ádám, a vyrostu, slibte, e mne budete uèit!
{27569}{27619}Dobøe, budu na tebe èekat.
{27634}{27692}Protoe jsi mùj student.
{27746}{27787}To mi øekl mistr Vierra!
{27861}{28014}Je velice vzácné udìlat z vystoupení tak emocionální záitek, e s nìkım uvnitø pohne.
{28129}{28265}Jenom snìní o tomto momentu jsem vzdal. A do vèerejška.
{28337}{28415}Ale… teï, naprosto bez pochyb…
{28462}{28548}Cítím, jak to se uvnitø tøesu!
{28631}{28646}Neuvìøitelné…
{29438}{29479}Bravo! Bravo!
{29510}{29546}To bylo úchvatné, Chiaki.
{29564}{29604}Vypadá to, e si se zvládl pøenést pøes ty zábrany.
{29670}{29722}Byla to snad nakonec lekce pro mì?!
{29821}{29855}Ten zatracenı zákeønı uèitel!
{29887}{29965}Já… chci skoèit do tvého náruèí, senpai, ale jsem nervózní.
{30055}{30115}Znamená to snad, e jsem zamilovaná?!
{30198}{30211}Ne!
{30224}{30244}Rozhodnì ne!
{30268}{30348}Ale mám tak sevøené srdce, a to bolí, senpai!
{30348}{30382}Mılíš se!
{30382}{30433}To je poprvé, co se takhle cítím!
{30433}{30464}Posloucháš mì vùbec?!
{30520}{30650}Mistøe Vierro, vypadá to, e mám v Japonsku ještì malou práci…
{30744}{30828}www.mycolorfullife.blog.cz
