{1}{1}23.976
{31}{79}TaSHee's Gang uvádí...
{185}{262}NODAME CANTABILE
{2165}{2189}LEKCE 2
{2336}{2355}Prùmìrnı.
{2399}{2420}Prùmìrná.
{2475}{2515}Všichni jsou tak prùmìrní.
{2539}{2589}Wow, kdo to je?
{2589}{2671}Oh, to je ten kluk z Urakenu.
{2671}{2693}Urakenu?
{2693}{2706}/Èínská restaurace Uraken/
{2706}{2772}Ta èínská restaurace za školou?
{2772}{2816}Jo. Je syn majitelù.
{2816}{2853}Take tu pøišel jako poslíèek?
{2853}{2894}Ale nemá u sebe krabice s jídlem.
{3266}{3310}Boe, miluju rock!
{3354}{3432}Hej, co by mìla naše kapela zahrát na školním festivalu?
{3455}{3548}Hele Mine, nemáš náhodou pøíští tıden zkoušku z houslí?
{3562}{3618}Co budeš dìlat, kdy to zase nedáš?
{3618}{3733}Ten poslední doprovodnı hráè na klavír, kterého jsem ti sehnal, to s tebou vzdal.
{3756}{3781}Dobøe, to bylo…
{3815}{3834}Jsi na nic.
{3845}{3871}Je to dìs. Jdu domù.
{3871}{3964}Ten Chiaki nerozumìl mému umìleckému cítìní, take…
{3980}{4065}Mùj doprovod by mìl bıt více technicky zdatnı, flexibilní,..
{4078}{4141}A hlavnì umìleckı!
{4174}{4216}C-Co je?
{4216}{4249}Je to vypnuté.
{4249}{4266}K èertu!
{4284}{4333}Kdo sakra…?!
{4333}{4396} Pøerušil… šòùru…
{4501}{4584}Jenom jsem se snaila naplnit aludek!
{4584}{4640}A byla to treska s kaviárem!
{4640}{4663}H-Hej!
{4733}{4781}J-Je pìkná…
{4781}{4816}U-Umm...
{4833}{4876}Ty jsi studentka klavíru?
{4888}{4943}Jo, to jsem.
{4960}{5030}Mùu se tì poádat, jestli bys nechtìla bıt mùj klavírní doprovod na zkoušky?
{5030}{5075}Najednou je ti jedno, co je zaè?
{5218}{5269}Zbıvá u poslední krok...
{5417}{5437}Hotovo!
{5492}{5560}A rychle! K sousedovi na veèeøi!
{5644}{5695}Hmm, jsem tu moc brzy?
{5728}{5797}Zase dìlám dobrovolnou práci.
{5820}{5894}Wow! To vypadá úasnì! Co to je?
{5894}{5933}Kuøecí Capri.
{5933}{5959}"Capri?"
{5989}{6050}Proè tì musím krmit?!
{6055}{6075}Veèer co veèer!
{6075}{6088}/Chleba/
{6088}{6126}U je to dva tıdny…
{6126}{6201}/jdeme jíst!/| …co jsem pøišla a tvrdila, e uvaøila jídlo…
{6232}{6253}To je makrela.
{6253}{6270}Je to kus popela!
{6283}{6305}Dej si!
{6305}{6331}Snaíš se mì snad zabít?!
{6342}{6438}Jestli mi chceš tvrdit, es nìco zvládla uvaøit, tak alespoò tohle snìz dobøe!
{6466}{6491}To je tak dobré!
{6491}{6521}Co to je?!
{6521}{6613}Millerighe alla panna con i broccoli.
{6614}{6675}Kouzelné jídlo! Ty jsi tak úasnı, senpai!
{6675}{6743}Jsi génius! Vaøíš líp ne moje máma!
{6743}{6779}Ale to zas…
{6820}{6862}Gyabo! Deštník!
{6862}{6940}A tak jsem ji zkazil tím, e ji krmím.
{7001}{7038}Dìkuji za veèeøi.
{7095}{7148}Manelskı ivot je tak fajn, e?
{7148}{7184}Kdo je sakra enatı za koho?!
{7184}{7308}Oh, senpai, znáš Beethovenovu houslovou sonátu è. 5?
{7308}{7333}Ta se jmenuje "Jaro," ne?
{7333}{7424}Mám ji teï hrát jako doprovod. Ale neznám ji. Mohl bys mi ji zahrát?
{7468}{7494}Pøinesla jsi noty?
{7494}{7531}Pøinesla.
{7613}{7668}Opravdu jí to jde…
{7694}{7760}Po veèeøi vdycky hraje na klavír.
{8086}{8131}To je úplnì blbì!!!
{8572}{8599}To je skvìlé…
{8655}{8708}Tak skvìle jsem to ještì necítil!
{8821}{8880}S-Sakryš!
{8880}{8914}Na první pokus to bylo moc dobré!
{8914}{8950}Bravo, Nodame!
{8950}{9005}Ve tvém hraní je duše!
{9005}{9030}"Duše?"
{9030}{9060}Pøesnì tak, duše!
{9074}{9164}Koneènì jsem našel toho pravého partnera!
{9164}{9230}Jo! Tentokrát ty zkoušky udìlám!
{9398}{9450}Co bychom si dneska na veèeøi mohli udìlat?
{9469}{9565}Teï je vhodné období pro okouna, ropušnici a chòapala,
{9565}{9599}kterı je mimochodem moc drahı.
{9599}{9644}A vlastnì ani nemáme ádnı dùvod oslavovat.
{9747}{9791}Ty idiotské skøeky jsou od…
{9893}{9966}Tady máte! Jedna objednávka smaené rıe Uraken!
{10031}{10082}Tati, ještì gyazo! |(èínské plnìné knedlíèky - pozn.)
{10082}{10110}Dobrá.
{10110}{10176}Nodame, jak ti chutná naše jídlo?
{10212}{10277}A tak? A taaak? Je to dobré?
{10277}{10387}To je ten nanicovatej houslista, Mine!|/Kdy se tady zastavíš, nakrmíme tì kdykoli!/
{10387}{10405}e, tati?
{10405}{10495}No jasnì. Jestli je pøedurèena pro tebe…
{10495}{10574}/Pøesnì, tati! Pøedurèena!/|Tak to byl on, kdo ji poádal, aby mu dìlala doprovod.
{10616}{10735}Fajn, mùou si zkoušet, co chtìjí, ale i kdy se budou snait sebevíc, stejnì budou oba k nièemu.
{10810}{10855}"Jak ti chutná naše jídlo?"
{11009}{11026}Pche.
{11041}{11058}Zatracená holka!
{11058}{11155}Její úplnì ukradené s kım je dokud jí nìkdo nedá najíst!|/Tady to máš./
{11155}{11185}Mòau.
{11233}{11256}To je tak na hlavu!
{11468}{11510}To je první poklidnı veèer za dlouhou dobu.
{11569}{11654}Udìlám si veèer s Beethovenem s novımi nahrávkami mistra Vierry.
{12415}{12431}Dopr…!
{12445}{12487}Jak daleko chce zajít, dokud mne nepøivede na pokraj šílenství?!
{12523}{12610}Sakra u, ty vtìrko! Co ode mì chceš tak…
{12610}{12641}pozdì...
{12702}{12719}Saiko?
{12734}{12767}Vtìrko?
{12791}{12811}To je spíš pro…
{12811}{12881}Ne-e, to nebylo na tebe…
{12881}{12941}Take ona je tvá nová pøítelkynì?
{12973}{13002}Ta sleèna Vtìrka?
{13002}{13028}Jistìe ne!
{13245}{13315}Paneboe! Senpai, ty u máš pøítelkyni?
{13315}{13362}Pøeklad: J-dawe
{13362}{13396}Korekce + èasování: WelW(etkaAa)-hime
{13506}{13526}No-Nodame!
{13526}{13556}Co se dìje?!
{13556}{13605}Kam se podìla tvá duše?! Tvùj duch?!
{13665}{13683}Láska...
{13717}{13766}Jest pøelud...
{13766}{13812}A on je modrá rùe...
{13848}{13903}Dìlej, Shinichi! Jdeme pozdì!
{13925}{13998}Kde jsi schovávala všechnu tu energii, Saiko?
{13998}{14064}Dneska berete solmizaèní slabiky a pak máš soukromé lekce, ne?
{14087}{14175}Mùj boe… Ona zùstala celou noc?
{14213}{14264}A tahle rùe…
{14264}{14314}Tahle rùe pùvabnì uvadá...
{14314}{14348}Ty jsi ztratila svou lásku?!
{14348}{14479}Sakra! Zkouška je u pøíští tıden! Tohle mùe znièit mùj vıkon!
{14491}{14567}Kdo to byl?! Dám vás dva zase dohromady!
{14567}{14644}Je to student z téhle školy.
{14659}{14681}Kterı?
{14681}{14739}Ten, co si támhle na lavièce ète kníku.
{14768}{14823}To je Chiaki.
{14850}{14918}Shinichi! Koneènì jsem tì našla!
{14977}{15017}Co to èteš?
{15017}{15036}Vlastnì nic…
{15074}{15115}Take to je ta rivalka?
{15115}{15134}Jo.
{15167}{15190}Tak to's prohrála.
{15204}{15313}To je Tagaya Saiko. Øíká se jí krásná a talentovaná Madonna pìvecké tøídy.
{15313}{15382}A je také dcerou majitele Tagaya Music.
{15382}{15495}Jestli chce Chiaki randit s touhle koèkou, tak nemáš ádnou šanci, e by si tì vùbec všiml.
{15511}{15590}Tak se na nìj pìknì vykašli a pojï cvièit!
{15617}{15649}AAAAH! Teï jsem ale ještì více dojebaná!
{15689}{15755}Proè ta tlustá pitka bude zpívat roli Paminy?!
{15755}{15860}O tom u jsi mlela celou vèerejší noc.
{15897}{15996}A co je na tom? To jen znamená, e jsem maximálnì uraená!
{16027}{16136}Vypadá to, e Saiko nedostala tu roli v "Kouzelné flétnì," kterou produkuje operní spoleènost…
{16136}{16229}…kvùli holce, do které by nikdy neøekla, e jí mùe konkurovat .
{16284}{16385}Hej, Shinichi. Mohli bychom se k sobì vrátit?
{16561}{16596}Nesnáším takové ztroskotance.
{16619}{16638}C...
{16718}{16748}Coe?!
{16794}{16851}Byl jsem takovı a donedávna, e?
{16892}{16923}Sakra, byl jsem tak chladnej.
{16945}{16999}Ok, pouèil jsem se.
{17016}{17083}Nodame, u se koneènì vzchop!
{17083}{17129}Klavír je to jediné, co ti zbylo!
{17129}{17211}Aspoò zahraj dobøe na klavír a uka mi nìjaké známky ivota!
{17211}{17228}Hej!
{17268}{17308}Chci vidìt senpaie.
{17350}{17398}Chci jíst u senpaie.
{17429}{17492}Chiakiho jídlo? Coe?
{17504}{17575}Capri bla bla broccoli bla bla...
{17575}{17623}Ty lahodné veèeøe!
{17623}{17692}Ty jsi ho donutila, aby ti vaøil?!
{17730}{17803}To je úasné! Moná máš nakonec ještì šanci!
{17834}{17857}Šanci?
{17857}{17918}Kluk nevaøí pro holku, kterou nesnáší!
{17929}{17987}Moná e kdy se budeš snait, mùeš jí ho ukrást!
{17987}{18034}Mùu ho ukrást?! Jak?!
{18069}{18126}Já bych… se s ním vyspal.
{18141}{18159}Vyspal se s ním?
{18171}{18262}Uka mu svou enskost a hrej na jeho muské instinkty!
{18278}{18323}"Jsem tvoje tøešnièka na dortu."
{18323}{18392}Já jen… Myslím tím… mue takové kydy berou!
{18392}{18466}Moje enskost… Tøešnièka na dortu…
{18545}{18575}Dachuno!
{18589}{18636}Vypadáš jak dùchodce! A taky odpudivì!
{18655}{18695}Nemáš nìjaké sexy hadry?
{18695}{18738}No, myslím, e mám nìjaké letní šaty.
{18738}{18754}A make up?!
{18754}{18814}Nìjakı jo!|/Make up, kterı kamarádce ukradla/
{18844}{18917}Vypadá nìjak tak, ne? Myslím Marilyn Monroe.
{18917}{18994}Sakra u! To sis nikdy na sebe pøedtím nepatlala make up?!
{19012}{19077}M-Moná bychom tak dvì kila toho make-upu mohli ubrat.
{19116}{19131}Nebreè!
{19140}{19170}Já se smìju!
{19170}{19206}Boe, za co?!
{19206}{19242}Uka mi tyhle!
{19260}{19297}Zkusíme trochu pøirozenìjší look.
{19310}{19353}Tøeba je Chiaki skrytı perverzák.
{19364}{19398}A skrytım perverzákùm se líbí pøirozenı look?
{19398}{19508}Jo. Pravdìpodobnì ho víc pøitahují pøirozené feromony ne prvoplánové strojení.
{19508}{19604}Hej. O èem to vy dva mluvíte?
{19691}{19729}U pøišel...
{19729}{19762}aby mì vidìl...
{19790}{19860}Chiakiiiii!
{19902}{19931}Co to k èertu vyvádíš?!
{19931}{19983}Nemìli byste cvièit na tvoje zkoušky?!
{20016}{20054}Kvùli tobì se Nodame stala k nièemu!
{20054}{20156}Pøedtím následovala mé umìlecké cítìní úplnì skvìle!
{20175}{20248}Hej, bejby! Jsem tøešeò...
{20248}{20339}Jsi si vánì jistı, e jsi tak dobrı?
{20356}{20390}J-Jasnì, e jsem!
{20390}{20448}Skonèil jsem tøetí v národní juniorské soutìi!
{20486}{20506}Tak se na to podíváme…
{20506}{20520}Co-
{20564}{20634}"Jaro." Pouhı zaèátek je dost dobrı, ne?
{20902}{20987}Pokud jde o juniorské soutìe, jednu jsem vyhrál a ve Vídni.
{21025}{21079}Take moná bych mohl zvládnout tì uèit, co øíkáš?
{21113}{21150}Nikdy ho nenechám!
{21150}{21218}Ten rytmus a intonace! Hrej všechno pøesnì tak, jak øíká hudba?!
{21218}{21324}To urèitì, kašlu ho a zahraji si to po svém. Všimnou si jediné chybièky a je po všem!
{21324}{21368}Proto nesnáším klasiku!
{21577}{21641}Minovo a moje je totálnì rozdílné.
{21660}{21690}To je "Jaro?"
{21706}{21754}Vdy vy jste hráli "Novı rok".
{21754}{21849}Senpai, nezahrál bys pro mì trochu na housle?
{21904}{21932}Jen jednou, dobøe?
{22330}{22387}Jedno poslechnutí CD a ona u hraje o tolik lépe?
{22405}{22437}Je vánì dìsivá.
{22520}{22563}To bylo moc fajn.
{22616}{22653}Pøestaò mluvit takovım úchylnım hlasem!
{22653}{22693}Zajímalo by mì proè…
{22693}{22856}…nemùu hrát tak dobøe s Minem. Ale i tak øekl, e to bylo to nejlepší, co kdy cítil.
{22856}{22910}No, to je protoe…
{22910}{22973}Øíká se tomu masturbace!
{22973}{22997}OK?
{22997}{23045}Znamená to, e uspokojuješ jen sebe!
{23059}{23094}Oh? Co??
{23094}{23203}A taky, nechápeš, co to je fungovat spoleènì. OK?
{23203}{23281}Vùbec nenasloucháš klavíru!
{23281}{23347}Zní to strašnì, kdy se pokoušíš hrát po svém! OK?
{23365}{23449}Ještì, pøestaò se tolik starat o techniku!
{23460}{23553}To jsou ètyøi rady, které ti mùu dát!
{23637}{23817}Ksakru s tím… Je borec v klavíru a ještì k tomu dost dobrı na housle. To není fér!
{23817}{23900}Vím, e jsem k nièemu a e nemám talent.
{23927}{24009}Mine, jsi køehkı jako køišál…
{24009}{24029}Dej mi pokoj!
{24040}{24151}Ale Chiaki-senpai nikdy neøekl, e nestojíš za nic.
{24163}{24284}Øíkal, e máš jedineènou interpretaci. A e nejsi dobrı ve høe s doprovodem, ale sólovì ti to jde.
{24284}{24314}Vlastnì tì hodnì vychvaloval.
{24354}{24391}Chiaki mì chválil?
{24391}{24456}OK? Tak jdem cvièit, Mine!
{24456}{24519}Jestli se nám povede se sladit, bude to pìkná hra!
{24533}{24596}"Jaro". To je louka plná kvìtin.
{24632}{24742}Pøestaò si pohrávat s tak dìtinskımi pøedstavami jako je pole s kytkami.
{24771}{24806}Tak jakou pøedstavu bych mìla mít?
{24818}{24917}Nìco jako záøící radost mládí a bleskù.
{24951}{25002}Houslovı idiot a klavírní idiot.
{25075}{25156}Teï, jak mu asi ty zkoušky dopadnou?
{25319}{25362}Nachlazená?!
{25377}{25469}Oblékla jsem se asi moc lehce, snaila jsem se bıt sexy.
{25482}{25539}I tak jsem ji pøinesl. Na!
{25567}{25664}Heh? Co jako mám dìlat s takovou zdechlinou?
{25664}{25683}To není mùj problém!
{25724}{25761}Co se dìje, Nodame?
{25796}{25821}Chápu.
{25840}{25922}Øíká, e se jí udìlá líp, kdy dostane polibek od svého prince!
{25922}{25974}A dost! Dobøe.
{25989}{26032}Zahraju ti ten klavírní doprovod, Mine.
{26032}{26052}Není èas na nácvik.
{26052}{26095}To ne!
{26253}{26298}Ten je té na nic.
{26298}{26386}Závidím ti, jak seš dobrej bez špetky námahy.
{26386}{26408}He?
{26425}{26547}Na klavír i housle pravidelnì hraji u od svıch tøí let.
{26547}{26625}Hlavnì na housle. Hrál jsem na nì od rána do veèera, ne jsem nastoupil na konzervatoø. Ještì teï je mi z toho zle.
{26666}{26744}Kdy to porovnám s houslemi, byl jsem otøesnı ve høe na klavír.
{26744}{26796}Proto se tady hlavnì uèím na klavír.
{26796}{26917}Vzal jsem to opravdu vánì a tak jsem se stal nejlepším u v druhém roèníku.
{26936}{26979}Ale v poslední dobì jsem se trochu flákal.
{26993}{27057}Poèkej, co mi tím chceš øíct?
{27080}{27183}Koneènì, mùj skuteènı sen je stát se dirigentem.
{27183}{27296}Proto studuji mnoho rozdílnıch pøedmìtù, ale ádnı z nich se mi ještì nevyplatil.
{27336}{27357}Dirigent?
{27382}{27434}Mine! Jsi na øadì!
{27434}{27468}Pospìš si!
{27496}{27509}Jdeme.
{27531}{27553}O-OK.
{27567}{27621}Dneska si nedìlej starosti s technikou.
{27658}{27719}A hlavnì, naslouchej mım notám.
{27760}{27838}A nakonec, mùeš hrát jak chceš.
{28117}{28226}Záøící radost mládí a bleskù...
{28493}{28600}Wow, jakmile jsem mu øekl, a hraje svobodnì, zní tak opravdovì.
{28621}{28666}Jako Nodamin, jeho styl je šílenı.
{28698}{28766}Ale podpoøím ho!
{29202}{29232}Úasné…
{29259}{29293}Je tam, kde jsem chtìl, aby byl.
{29327}{29414}U to chápu... Chiakiho dirigování pøes klavír.
{29459}{29489}Jde to hladce.
{29526}{29547}To je vánì pøíjemné!
{29653}{29681}Je to jako louka plná kvìtin...
{29842}{29937}Mine! Slyšel jsem, e jsi dal zkoušky!
{29937}{29969}Pojïme teï zkoušet s kapelou.
{29986}{30030}Promiò, ale odcházím z kapely.
{30060}{30132}Budu teï ít jen pro klasiku.
{30348}{30392}Tak, co po mì chceš?
{30403}{30477}Donáška! Pojïme to všechno sníst! Všichni tøi!
{30477}{30554}Senpai, nakrm mì prosím!
{30554}{30613}Proè sakra leíš v mém pokoji?!
{30613}{30674}Nodame! Pøinesl jsem ti vajeènou polévku!
{30743}{30805}www.mycolorfullife.blog.cz
