{1}{1}23.976
{40}{78}TaSHee's Gang uvádí...
{183}{267}NODAME CANTABILE
{2170}{2199}LEKCE 3
{2342}{2379}Kadence 120…
{2405}{2450}126...
{2450}{2496}132...
{2507}{2560}162...
{2587}{2660}Ne!!! U to nemùu vydret!
{2714}{2780}Co to s ním je?
{2780}{2821}Ha? S Masumim?
{2860}{2954}Má klaustrofobii, take nevydrí pøíliš dlouho dlouho ve zkušebnì.
{2965}{3034}Ale je vánì dobrı na tympány.
{3034}{3086}A taky na marimbu a bicí.
{3086}{3110}Sama sebe nazıvá královnou úderovıch nástrojù.
{3128}{3206}Ona? Královnou?!
{3267}{3290}Nenávidím to!
{3290}{3328}Chci zpátky domù do Yamagaty!
{3328}{3418}Chci ít pod širım nebem v Yagamatì!
{3479}{3497}Ale...
{3514}{3562}Podívej, to je Chiaki!
{3574}{3599}Chiaki?!
{3725}{3896}Ale kvùli Chiakiho nemùu odjet z Tokya! Neopustím tuhle školu.
{3896}{3955}Ké bych s ním mohl alespoò jednou mluvit!
{3955}{4009}Chiaki-senpai!
{4038}{4083}Promiò, e jsem tì nechala èekat!
{4106}{4122}/Svírá ho nenávist!!/
{4122}{4150}Já na tebe neèekal!
{4167}{4236}Míøíš na cvièení?
{4236}{4304}Chci si tì poslechnout jak hraješ na klavír!
{4317}{4343}Nedolízej!
{4343}{4408}Ej, proè ne?
{4408}{4470}To je ta klavírní borka…
{4504}{4583}Právì si øekla o pøidání na vrchol mé èerné listiny.
{4957}{4987}Myslím, e tak by to šlo.
{4987}{5030}To je tak dobré!
{5030}{5100}To jsi sloil sám?
{5100}{5176}Je to tak hezouèké! A tak romantické!
{5187}{5233}Romantické? Vánì?
{5233}{5312}Urèitì se to jmenuje "Óda na Nodame," e?
{5312}{5355}Vra se laskavì na zem!
{5388}{5471}Mìl jsem na mysli napsat tuhle skladbu s kompletním orchestrem.
{5513}{5608}Kompletním orchestrem? Take máš v plánu udìlat celou instrumentaci sám?
{5608}{5649}No, jo.
{5649}{5682}Úasné!
{5703}{5773}Neznám ádnı orchestr, kterı by to zahrál, i kdybych to dokonèil.
{5835}{5875}Orchestr, co?
{5938}{6020}Co se dìje? Vypadáš nešastnì!
{6020}{6072}e by nìco s…?
{6072}{6166}Oh! Na dnešní veèeøi ti pøinesu ohøívaè!
{6234}{6311}Hm, tak problém co dnes na veèeøi to nebyl.
{6361}{6387}Ale...
{6433}{6489}Bingo! Poádal mì, abych koupila suroviny na veèeøi!
{6489}{6529}My jsme naprosto dokonale boí pár!
{6847}{6868}Hele, dopis!
{6868}{6907}Od Yoko? (= matky)
{6907}{7025}Jestli nepošleš tento dopis stovce lidem do dvou dnù, zemøeš!
{7089}{7160}Prosím pomo mi napsat pár dopisù!!!
{7191}{7219}Blbko!
{7219}{7263}To je jasnı ert!
{7263}{7317}ert?! Od koho?
{7317}{7342}Nevím!
{7361}{7420}Kadopádnì, kde jsou ty potraviny, o které jsem tì ádal?
{7420}{7496}Pøímo tady.
{7496}{7603}Ale nákupní lístek se zmaèkal a nemohla jsem ho správnì pøeèíst…
{7634}{7685}Take jsem vzala jen to, co jsem rozluštila.|/Nakládaná hoøèice zha cai, cvrèci, vajeèné rolky/
{7685}{7740}ádal jsem tì o potraviny na vaøení v hrnci!
{7777}{7852}Moøská øasa, pekingské zelí a jedlou chryzantému!
{7852}{7915}VYpadalo to jako cvrèci, zha cai a vajeèné rolky...
{7915}{7949}Proè cvrèky?!
{7972}{8003}Nemùeme ty cvrèky uvaøit v hrnci?
{8025}{8051}U s tím pøestaò!
{8462}{8516}Maki, promiò mi!
{8516}{8584}To já ti pøedevèírem snìdla vepøovou kapsu!
{8584}{8632}To's byla ty?!
{8632}{8682}To mì vùbec nepøekvapuje!
{8682}{8735}I tak, já to nebyla.
{8774}{8835}To jsou klasické ertíky.
{8835}{8880}To je úasné, musí bıt od nìkoho z tvého okolí!
{8906}{8995}Nevím, kdo to dìlá, ale zaslouíš si to.
{8995}{9065}Jestli se ti to nelíbí, tak nejez u moje vepøové kapsy!
{9065}{9115}To ti nemùu slíbit!
{9115}{9147}Ještì si se nepouèila, co?
{9203}{9228} Tadá!
{9228}{9359}Láskou naplnìnı obìd, kterı udìlal Chiaki ze vèerejších zbytkù.
{9394}{9443}Udìlal ho jen pro mì!
{9478}{9529}Musím se nìjak zbavit tìch cvrèkù!
{9553}{9597}Chiaki? Vánì myslíš toho Chiakiho?
{9597}{9670}Jen si vymıšlí To je její obvyklé bláznovství.
{9670}{9702}Jdeme jíst!
{9790}{9837}/Bylo to vıborné./
{9895}{9923}Neee! To je neodpustitelné!!!
{9923}{9958}Já ho zabiju!
{9979}{10035}Já ho obìsím!
{10035}{10078}Jakmile se do toho zatáhlo i jídlo…
{10078}{10118}Tak se z ní stala úplnì jiná osoba.
{10455}{10488}A mám tì.
{10488}{10513}Chytla jsem tì!
{10549}{10610}Nee! Vy jste mì podvedli!|/Hej, uklidni se./
{10610}{10630}Co jsi zaè?!
{10630}{10666}Sundej tu paruku!
{10666}{10774}Au! To jsou moje pravé vlasy! Pøestaò!
{10787}{10860}Ty jsi… ten tympanista Masumi!
{10860}{10896}On je tvùj kámoš?
{10909}{11019}No, spíše spoluák, máme nìkteré spoleèné hodiny…
{11019}{11083}Nech mì bıt, ty vìènì propadající lamo!
{11083}{11115}Jmenuju se Ryutaro!
{11144}{11199}Proè na mì chystáš ty pasti?!
{11199}{11271}Nejeè na mì! Bolí mì z toho hlava!
{11271}{11381}Kadopádnì, pokud jde o tebe Nodo Megumi, nepøibliuj se k Chiakimu!
{11381}{11457}Aha, tak proto…
{11457}{11578}Co tím myslíš? Proè Chiaki?
{11590}{11650}Chiaki je mùj princ!
{11650}{11787}On je mùj Apollo! Dává mi odvahu a nadìji ít kdy se na nìj z dálky dívám!
{11802}{11833}Jinımi slovy, on je moje slunce!
{11865}{11953}Ale potom se na scénì objevila ta špinavka!
{11996}{12043}Prosím, nemáš kopie?!
{12064}{12130}I kdy bydlíš hned vedle, ometáš se kolem nìj a moc!
{12130}{12185}Tøeba jak ho nutíš, aby ti kadı veèer vaøil!
{12204}{12245}Tys o tom všem vìdìl?
{12266}{12312}To je neodpustitelné, ty skrèku!
{12312}{12385}Radši budu trpìt Tagayu Saiko ne tebe!
{12411}{12437}Skrèku…
{12437}{12522}No, a víš o tom e Chiaki je kluk?
{12522}{12569}No a? Máš nìjakı problém?
{12569}{12615}Jo tak on má tenhle typ orientace…
{12628}{12721}Nodo Megumi, vyzıvám tì na souboj!
{12721}{12749}Souboj?
{12773}{12846}Ukáu ti, kdo je lepší ena!
{12860}{12911}Souboj mezi dvìma blbama…
{12911}{12948}Ale jak chcete soupeøit?
{12966}{13000}Hrou na tympány!
{13000}{13048}Fajn, já budu hrát na klavír!
{13048}{13097}Jak to pak mùe bıt souboj??
{13115}{13142}Ale...
{13142}{13192}U vím! Co tohle:
{13204}{13331}Kdo první pùjde na rande s Chiakim dvacátého ètvrtého za dva tıdny, vyhrává?
{13347}{13373}Dvacátého ètvrtého?
{13385}{13425}Rande?
{13425}{13494}Bitva o rande na Štìdrı veèer!
{13561}{13596}Tadá!
{13596}{13706}Lístek na japonskı koncert krále dirigování Inzagiho!
{13719}{13814}Wow! Ten musel bıt drahı, není to dokonce V.I.P.?
{13843}{13893}Udìlal jsem pro nìj všechno!
{13893}{13949}Myslíš, e má Chiaki rád Inzagiho?
{13949}{14046}Jo, má! Tohle ho urèitì rozhoupe!
{14062}{14109}Hej kámo, to je trochu nuda.
{14109}{14161}V podstatì jsi u skoro vyhrál.
{14172}{14260}Ale nejdøív se s ním musím spøátelit.
{14281}{14325}Musím… musím s ním promluvit!
{14343}{14466}Ale co kdy øekne, e se mnou jít nechce?!
{14466}{14527}To bych nepøeil!
{14527}{14672}Neboj se. Dám ti svùj tajnı návod jak stoprocentnì uspìt na schùzce s Chiakim!
{14672}{14707}Vánì?!
{14769}{14794}Dvacátého ètvrtého?
{14813}{14918}Jo. Nešel bys se mnou dvacátého ètvrtého na veèeøi?
{14920}{14996}Proè bych s tebou mìl nìkam jít?
{14996}{15045}No, na veèeøi…
{15045}{15085}My vdycky jíme spolu.
{15085}{15156}Myslela jsem, e jednou bychom mohli jíst nìkde venku…
{15334}{15453}Cello by v téhle pasái mìlo hrát spolu s violou a klarinet by se pøidal odsud.
{15484}{15512}Senpai...
{15527}{15665}Dvacátého ètvrtého si uklidím byt a upeèu vánoèní dort! Prosím, e pøijdeš!
{15666}{15680}Jo!
{15713}{15750}Trumpety plnou parou!
{15766}{15794}Juchù!
{15861}{15945}Hej, koukni se na tohle. Není to Hayakawa?
{15945}{16008}No jo! Wow!
{16008}{16079}Myslíš toho Hayakawu? Ten nejlepší student dirigování co odjel do Nìmecka?
{16079}{16234}Není to skvìlé, e se zúèastnil slavného gerhaimské konference?
{16234}{16279}Úèastník Gerhaimu?
{16279}{16324}Student odsud?
{16324}{16362}Mùu se na to na chvíli podívat?
{16388}{16412}Oh, samozøejmì!
{16412}{16460}Je tak cool!
{16460}{16570}Chiaki-sama... On na mì promluvil!|/Mistr Vierra chodí na tu konferenci!/
{16633}{16660}To není moné…
{16675}{16717}Pøeklad: j-dawe
{16717}{16751}Korekce + èasování: WelW(etkaAa)-hime
{16867}{16950}Skládání téhle skladby je na nic!
{16985}{17074}Nezáleí na tom, jak tvrdì studuji, poøád jsem oproti nìmu pozadu!
{17120}{17168}Jen proto, e nemùu nastoupit do letadla…
{17402}{17526}Chiaki-senpai! Jakou pøíchu si pøeješ do vánoèního dortu?
{17548}{17619}Vánoce? O èem to mluvíš?
{17644}{17798}Vánoce jsou svatá noc, kdy ty a já budeme spolu jíst dort!
{17798}{17860}Slíbil jsi to, pamatuješ?
{17886}{17910}Nepamatuju!
{17953}{18016}Ale máš pøijít ke mnì domù dvacátého ètvrtého a…
{18016}{18050}Nepamatuji na ádnı takovı slib!
{18068}{18100}A nemám teï èas!
{18115}{18186}Nechoï za mnou poøád s kadou kravinou co vymyslíš!
{18412}{18449}A jde nìkam s Vánocemi!
{18472}{18545}Strávit èas s hloupımi lidmi mì deprimuje ještì víc!
{18545}{18601}Chiaki!
{18601}{18646}No super, další permanentní blb.
{18661}{18705}Chiaki, máš teï volno?
{18705}{18738}Ne, nemám.
{18738}{18801}Co? Neskonèil jsi náhodou teï?
{18821}{18912}Orchestr A teï právì nacvièuje. Nechceš se pøijít kouknout?
{18912}{18993}Mùj kamarád tam hraje na tympány.
{18993}{19030}Minùv kamarád?
{19056}{19075}Nezájem!
{19075}{19201}Proè ne?! Je vánì dobrej! Bude to fakt stát za to!
{19201}{19230}No tak!
{19313}{19361}Co to máš s obleèením?
{19361}{19475}Ale no tak, Masumi. To není koncert roku! Proè ses tak oblékl?
{19475}{19531}Ticho! Máte snad s tím nìjakı problém?
{19531}{19600}Vloím do téhle zkoušky celı svùj ivot!
{19600}{19693}Opovate se nìco pokazit!
{19693}{19759}Proè?!|/Je to jen zkouška…/
{19780}{19834}Protoe… Protoe dnes…
{19897}{19964}Zaènìte hrát pøi prvním pohybu.
{20131}{20200}Chiaki, tys pøišel!
{20408}{20457}Sleduj mì prosím, Chiaki.
{20473}{20644}Já, Okuyama Masumi, 21, vloím svoje nejvášnivìjší pocity do mého hraní.
{20804}{20863}Chiaki! Prosím staò se…
{20897}{20946}…mım pøítelem!
{21534}{21562}Stop, stop!
{21604}{21641}Tympány! A ven!
{21767}{21839}Tak to je ten tvùj kamarád, Mine?
{21839}{21881}Nee, to byl…
{21920}{21954}Je to mega blb.
{21954}{22019}Mega blb. MEGA blb.
{22020}{22081}Blb. Blb. Blb. Blb. Blb. Blb.
{22153}{22223}Byl by skvìlı, kdybych ho poslouchal se zavøenıma oèima.
{22284}{22360}Orchestr je skvìlı.
{22418}{22490}Ale tady, jediné co mùu je sledovat.
{22549}{22608}Upøímnou soustrast vám obìma.
{22608}{22695}Vánoèní "dej si rande s Chiakim" pohár - oba soutìící diskvalifikováni
{22747}{22863}Proè si to senpai tak najednou rozmyslel?!
{22863}{22924}Proè mne vyhodili?!
{22924}{22973}Jen jsem vyjadøoval svoji lásku!
{22973}{23039}Myslíš, e se mu nezamlouval ten pizzovı vánoèní dort?
{23039}{23115}Je to chyba dirigenta, nemyslíš?!
{23132}{23189}Myslím, e všechno bylo blbì.
{23224}{23256}Nechoï sem! Nech mì bıt!
{23256}{23302}Co mám teï dìlat?
{23302}{23362}Máš to jednodušší ne já!
{23362}{23393}Øekl...
{23393}{23436}Je to mega blb.
{23436}{23553}Nejene jsem se nestal jeho kamarádem, ale teï mì navíc nesnáší jako osobu!
{23553}{23643}Èlovìèe, mìl si hrát jako obvykle.
{23643}{23714}Nikdy pøedtím jsem nevidìl baletícího tympanistu.
{23714}{23777}Ty obèas baletíš taky Mine.
{23777}{23896}Co mám dìlat? Dokonce mì vyhodili z orchestru.
{23896}{23990}Nemùu vystát sám sebe, jak hraju na tympány!
{23990}{24025}Jsem odepsanı!
{24025}{24104}Nemám jinou monost ne se vrátit domù do Yamagaty!
{24104}{24184}Nemìl bys to tak pøehánìt…
{24184}{24243}Vy dva to máte lehké.
{24244}{24444}Vás nikdo nevylouèil! A navíc housle i klavír jsou sólové nástroje!
{24483}{24510}Masumi…
{24557}{24657}Ehm, nechtìl bys zkusit hrát s náma tøema?
{24732}{24751}Tak co?
{24793}{24887}Shinichi, co letos plánuješ na Vánoce?
{24887}{24945}Zas ty Vánoce…
{24945}{24993}Vlastnì nic moc.
{24993}{25061}Vypadá to, e budeme tento rok poøádat veèírek. Nechceš pøijít?
{25061}{25130}Nebo bys radši strávil nìjakı èas jen se mnou?
{25183}{25267}Moná bych u tebe mohla upéct dort.
{25284}{25376}Dvacátého ètvrtého si uklidím byt a upeèu vánoèní dort!
{25420}{25458}Prosím, e pøijdeš!
{25476}{25493}Jo!
{25531}{25565}U si vzpomínám...
{25565}{25618}Shinichi, posloucháš mì vùbec?
{25642}{25669}Promiò Saiko…
{25700}{25810}Tohle se mi vánì nepodobá, ale… Nakonec, slíbil jsem to.
{25831}{25889}Odmítnu zdvoøile.
{25976}{26011}Aha, není asi doma.
{26037}{26130}Jsem si jist, e brzo pøijde.
{26165}{26264}Hej, Nodame se s náma v poslední dobì moc nebavila, nemyslíš? Tak poslední tøi dny?
{26264}{26344}Jo jo, máš pravdu.
{26344}{26385}Myslím, e teïka moc šprtá.
{26403}{26455}Zajímalo by mì, co dìlá.
{26512}{26546}To je Chiaki!
{26569}{26604}Je úasnı...
{26604}{26654}Normálnì se na mì furt lepí…
{26691}{26779}…teï u na mì Nodame zapomnìla.
{26917}{26942}Ta skladba!
{26942}{27036}Ne! Ne! Kazíš poøád ten rytmus!
{27048}{27164}Tak proè mìníš tempo, kdy já udruju bubnování na 120?!
{27164}{27193}To je na nic!
{27193}{27289}Byla jsem tak špatná?
{27289}{27365}Tvùj rytmus je pøíliš uhlazenı, Masumi.
{27365}{27469}Je to jazzová skladba, tak to zkus trochu hrubìji!
{27470}{27505}Je to dobré na protaení a tak.
{27532}{27624}Protaení je fajn, ale a No-Dumb-Me nespìchá (No-Dumb-Me doslova Ne-blbka-Me).
{27655}{27681}Jmenuji se Nodame!
{27748}{27768}Kadopádnì,
{27768}{27822}zahrajme si to ještì jednou.
{27950}{27980}To je ta skladba, kterou jsem sloil.
{28037}{28107}Slyšela ji jen jednou…
{28140}{28191}Naaranovali ji do jazzu…
{28398}{28520}To je pìkná skladba! Miluji Chiakiho práci!
{28530}{28620}Ale víš, e té skladbì schází basa.
{28631}{28748}Kdybych mìla ještì jednu ruku, mohla bych hrát basu na klavír.
{28775}{28844}Jestli vám chybí jen jedna ruka, mùu se pøipojit.
{28941}{29000}Co to je za reakci?!
{29000}{29019}Nìco se vám na mì nelíbí?!
{29047}{29070}Chiaki-sama...
{29129}{29175}Masumi omdlel!
{29203}{29265}Nemá cenu závidìt ostatním lidem ivot.
{29302}{29392}Musím si sám zmìnit svùj ivot.
{29473}{29570}A teï je 24. prosince neboli Štìdrı veèer.
{29634}{29730}Nodame, uber trochu tady a nech to na houslích.
{29750}{29823}Mine, zaèínáš hrát pøíliš brzo, kdy zaèínáš své sólo.
{29823}{29916}Afro, zaèneš hrát s frekvencí 38, dva údery pøed tím.
{29950}{30001}Zaènìme znovu od zaèátku.
{30090}{30171}Co-co zas tahle reakce?
{30171}{30197}Zas nìjakı problém?
{30197}{30238}U dost!
{30238}{30303}Prosím, neøíkej mi Afro!
{30317}{30400}Øíkals, e máme dneska spolu vánoèní veèírek!
{30400}{30444}Dort! Katsudon (smaená rıe s vepøovım).
{30444}{30500}Tak u to koneènì zahrajte dobøe!
{30518}{30695}A tak, naše první souhra neskoèila pøed koncem roku, díky Chiakimu puntièkáøství.
{30752}{30804}www.mycolorfullife.blog.cz
