{1}{1}23.976
{23}{74}TaSHee's Gang uvádí...
{191}{261}NODAME CANTABILE
{2226}{2270}Milı mistøe Vieiro,
{2304}{2471}u jsem se rozhodl. Musím zmìnit svùj ivot svıma vlastníma rukama.
{2471}{2503}LEKCE 4
{2650}{2680}Gejša...
{2680}{2716}Sukiyaki…
{2729}{2751}Sushi...
{2773}{2818}Gejšu chci víc ne cokoli jiného.
{2845}{2932}Kdo je ten cizinec? Není to tøeba novı profesor?
{2936}{3018}Nevím. Neslyšela jsem o tom nic.
{3213}{3321}Pøipadá mi, e jsem se poslední dobou v houslích o dost zlepšil! 
{3353}{3367}/Úchvatnı/
{3500}{3521}Kdo je tam?!
{3653}{3682}e by fanoušek?
{3790}{3887}U je to mìsíc co jsem se stal kamarádem Chiakiho.
{3887}{3955}Takhle šastnì jsem se ještì necítil!
{3973}{4028}Jsem doslova zaplaven štìstím!
{4174}{4204}Úchylák!!!
{4243}{4305}Hej, vidìlas u toho divného, starého cizince, co se tu potlouká?
{4305}{4338}Jo, vidìla!
{4338}{4389}On mì šmíroval, kdy jsem cvièil!
{4389}{4447}Mì taky! Nedìsí tì to?
{4447}{4470}Je to snad zlodìj?
{4868}{4890}Bravo.
{5063}{5133}Zajímalo by mì, co bude dnes na veèeøi!
{5133}{5167}Promiòte!
{5211}{5312}Vy jste ta talentovaná dívka z døívìjška!
{5312}{5367}Koneènì jsem vás našel!
{5400}{5423}Cizinec...
{5423}{5459}Ahoj.
{5459}{5519}Mùete mi øíct, kde najdu taxi?
{5519}{5578}Potøebujete najít taxi?
{5578}{5656}Jedno mùete najít na hlavní tøídì, ok?
{5656}{5797}Hlavní tøída… Jdìte tudy, pak odboète doleva a pak doprava...
{5797}{5837}Vùbec vám nerozumím.
{5848}{5967}Slièná dívko, dovedla byste mì tam, prosím?
{5967}{6008}Kdy u jsme u toho, co øíkáte na veèeøi?
{6008}{6027}Veèeøi?
{6027}{6133}Ano. Koupím vám sushi, sukiyaki nebo cokoliv jiného máte ráda.
{6133}{6196}Sushi... sukiyaki...
{6218}{6302}Ale moje máma mi øekla, e nemám chodit s cizinci.
{6302}{6387}Nein! Já nejsem cizinec!
{6387}{6486}Jsem jen poèestnı turista z Nìmecka, Milch Holstein.
{6486}{6571}Zítra mám s nìkım schùzku, ale dneska mám volno.
{6592}{6699}Jsem jenom osamìlı starı mu opuštìnı v téhle cizí zemi… Jsem tak sám...
{6745}{6765}Sám...
{6806}{6969}No dobøe! Poblí je jedno místo, kde se podává lahodné jídlo!
{6969}{7015}Pojïme tam a najíme se!
{7036}{7078}Nodame...
{7143}{7223}Všechno je u pøipraveno! Pøišli jsme právì vèas!
{7260}{7291}Hmm, voní to nádhernì!
{7291}{7396}Cítím vùni Garni. Stará dobrá francouzská kuchynì!
{7409}{7469}Snìzme to, ne to vychladne!
{7469}{7540}Ou, je tu i víno!
{7550}{7610}Oh, Chiaki-senpai, nestyï se a pøisedni si.
{7656}{7723}A èí dùm to asi je, co myslíš, ty parazite?!
{7723}{7762}Jdi nìkam s "pøisedni si"!
{7762}{7811}A kdo sakra je ten staøík?!
{7811}{7862}Tys ho pozvala bez mého svolení!
{7862}{7900}Co jako jste vy dva? Zlodìji?
{7938}{7980}A nechte moje víno bıt!!!
{8004}{8079}Nodame, tohle není restaurace?
{8079}{8114}To je byt mého kluka.
{8114}{8149}Já nejsem tvùj kluk!
{8149}{8200}Kdo je ten podezøele vypadající èlovìk?!
{8200}{8254}Není podezøelı!
{8254}{8303}Je to mùj kámoš!
{8303}{8381}Zrovna jsem ho potkala na ulici. Jmenuje se…
{8402}{8439}Ummm...
{8439}{8483}Aha a ty ho nazıváš kámošem?
{8508}{8606}Milch! Jasnì! Jmenuje se Milch Holstein!
{8623}{8682}Milch Holstein?
{8682}{8721}To zní povìdomì...
{8795}{8908}A to je Chiaki-senpai, je mùj starší spoluák na konzervatoøi.|/Urèitì je to falešné jméno!/
{8920}{8959}Ja? Na konzervatoøi?
{8973}{9020}Tak proto tu má klavír?
{9020}{9109}Ano! Je moc dobrı.
{9109}{9213}Rád bych si ho poslechl.
{9213}{9313}Oh, to je velmi pìknı klavír!|/O co mu jde?/
{9332}{9370}Je to nìjakı falešnı umìlec?
{9456}{9493}Chiaki...
{9511}{9569}Znáš tohohle mue?
{9569}{9619}Je to mùj uèitel dirigování.
{9619}{9643}Nedotıkat se!
{9659}{9695}Jeden z Vieirovıch studentù?
{9715}{9767}Ty se chceš stát dirigentem?
{9767}{9828}Je v tom nìjakı problém? Proè na mì tak zíráte?
{9883}{9943}Nodame, pojïme nìkam jinam.
{9961}{10032}Chikakimu pøipadáme na obtí.
{10079}{10106}Pojïme nìkam jinam?
{10151}{10255}V hotelu, kde bydlím, je moc dobrá sushi restaurace.
{10269}{10301}Hotelu?!
{10324}{10361}Jdeme.
{10361}{10398}P-Poèkejte!
{10419}{10507}Nodame, mùu ti dnes po veèeøi pomoct s uèením.
{10507}{10552}Uèení...
{10588}{10661}Mohu tì nauèit nìco mnohem lepšího!
{10661}{10710}Jako tohle a tamto…
{10710}{10762}Co je to a tamto?
{10762}{10822}Zøejmì nìco, co zatím neznáš...
{10843}{10894}Ten zatracenı starı úchyl…
{10894}{10970}ádné obavy, nebudeš se bát.
{10970}{11032}Jsem v tom mistr.
{11067}{11105}Nodame!
{11128}{11180}Mùeš tu dnes veèer zùstat!
{11229}{11251}V moji posteli.
{11293}{11327}Spoèívat v mém náruèí.
{11366}{11385}Nodame!
{11424}{11473}Spoèívat ve tvém náruèí…
{11473}{11521}Tak, starèe...
{11549}{11572}Šastnou cestu!
{11611}{11683}Oh, to je asi pro vás. Našel jsem to ve schránce.
{11746}{11780}Oh yeah!
{11793}{11837}Chiaki!...
{11908}{11973}Pojï za mnou, Chiaki-senpai.
{11973}{12034}Pøestaò s tím ty blbko!
{12050}{12117}Proè jsi sem toho starého chlapa pøivedla?
{12117}{12165}Nemusíš rozšiøovat své pøátelíèkování s podobnımi kreaturami na mezinárodní úrovni!
{12165}{12265}Bì se vyspat domù! |/Lháøi! A kdo le, ten krade!/
{12366}{12381}Fajn.
{12402}{12441}Aspoò mám Chiakiho polštáø.
{12541}{12568}Sakra práce s tebou, Nodame…
{12587}{12629}Nemìl jsem šanci ti øíct…
{12660}{12753}No dobøe, Nodame s tím nemá nic spoleèného. U jsem se rozhodl.
{12821}{12902}Chiaki! To musíš slyšet! To je bomba!
{12915}{13051}Profesor dirigování, kterı mìl pøijet… Je super slavnı…
{13063}{13094}Stresemann!
{13117}{13146}Stresemann?
{13171}{13363}Franz von Stresemann… Nìmeckı maestro, kterı dirigoval ve Vídni, Berlínì, Londınì a po celém svìtì?
{13376}{13489}To není moné. Proè by nìkdo tak slavnı pøišel uèit na japonskou konzervatoø?
{13489}{13588}Mluvím vánì! Bì se sám pøesvìdèit, kdy mi nevìøíš!
{13588}{13635}Je teïka ve sborovnì!
{13635}{13814}Proè? Právì kdy se rozhodnu zmìnit svùj obor… Je moné, e bych mìl takové štìstí?
{13881}{13976}Tahle škola je plná sympatickıch uèitelù.
{13976}{14004}Ale jdìte...
{14022}{14100}Jste dobrı v japonštinì i lichocení. 
{14156}{14214}Vidíš ho?
{14214}{14246}Je to vánì on, i kdy jsem si ho pøedstavoval trochu jinak!
{14271}{14329}Ten úchyl je Stresemann?
{14357}{14408}Vypadá úplnì jinak ne na fotce!|/Pozn.: Jeho mladá léta/
{14430}{14519}Chcete zaloit novı studentskı orchestr?
{14530}{14624}Ano. Mùj orchestr, sloenı ze studentù, které si vyberu.
{14624}{14756}Ale chtìli jsme, abyste uèil studenty dirigování a Orchestr A...
{14756}{14944}Jistì, s nimi budu pracovat takté. Chci jen dát šanci více studentùm bıt mımi áky.
{14944}{15038}Chci toho udìlat co nejvíc bìhem tohoto roku, co budu v Japonsku.
{15038}{15073}To je úasné…
{15073}{15112}Je to opravdovı maestro!
{15136}{15207}Vlastnì, u jsem si ty studenty vybral.
{15219}{15301}Prosím, prohlédnìte si studenty na tìchto fotografiích!
{15345}{15368}Jej, moje chyba!
{15368}{15448}To jsou mé pohlednice, které jsem si koupil v Shibuyi.
{15448}{15485}Tady jsou ty správné fotky!
{15534}{15617}Ehm, jste si s nimi jistı?
{15629}{15641}Samozøejmì.
{15656}{15721}Ten starı úchylák uèí dirigování?
{15761}{15781}Co se dìje Chiaki?
{15827}{15857}Nemùu teïka zmìnit svùj obor!
{15857}{15894}Pøeklad: j-dawe
{15894}{15938}Korekce + èasování: WelW(etkaAa)-hime
{15958}{16045}Stresemannùv Speciální Orchestr?
{16045}{16092}Jsem tam!
{16092}{16115}Ty jo, já taky...
{16115}{16180}Podle èeho rozhodovali o èlenech?
{16180}{16207}To musí bıt omyl.
{16207}{16235} Kdo to rozhodl?
{16240}{16261}/První housle - Mine Ryuutarou/
{16261}{16287}/Bicí - Okuyama Masumi/
{16352}{16376}Stresemann!
{16376}{16446}Jsem v Stresemannovì orchestru!|/Mega!/
{16515}{16658}Kdy jsem poprvé uslyšel Mahlerovu 8. Symfonii, dirigovanou Stresemannem, byl jsem v šoku.
{16692}{16766}Nutilo mì to pøemıšlet, kdo dokáe tak úasnì dirigovat Mahlera.
{16818}{16881}Nikdy mì nenapadlo, e to bude takovı mu!
{17017}{17061}I tak chci, aby mì uèil!
{17105}{17161}Nemùu odplout, i kdybych chtìl!
{17186}{17263}U nikdy nebudu mít šanci bıt maestrovım studentem!
{17287}{17323}Musím to všechno pøehodnotit!
{17349}{17372}Nodame!
{17393}{17510}Slyšela jsem, e je tvé jméno na seznamu èlenù pro Stresemannùv orchestr!
{17533}{17559}Co? Orchestr?
{17559}{17621}Ale v orchestru není místo pro klavír.
{17633}{17661}Proè zrovna Nodame?
{17661}{17681}Štípni mì!
{17681}{17709}/Maskotka - Noda Megumi/
{17724}{17757}Maskotka...
{17757}{17829}Nodame, ty jsi maskotem orchestru.
{17862}{17926}Jediné co musíš, je mi stát po boku.
{17926}{17998}Milchi! Co tu dìláte?
{17998}{18058}Protoe tohle je mùj orchestr.
{18070}{18109}Take vy jste Stresemann?
{18109}{18183}Správnì. Promiò, e jsem ti to do teï neøekl.
{18183}{18245}Take to bylo vaše umìlecké jméno?!
{18245}{18283}Ne, to je moje vlastní jméno.
{18295}{18343}Coe? Take ty mìníš svùj obor, Chiaki?
{18360}{18414}Ano. Na dirigování.
{18436}{18479}U nad tím nìjakou dobu pøemıšlím a koneènì jsem se rozhodl.
{18498}{18558}Mám v plánu podat ádost u dnes.|/ádost o zmìnu oboru/
{18558}{18625}Chápu. Ty u jsi nìjakou dobu uvaoval o dirigování, e?
{18640}{18720}Tìšil jsem se, a uvidím, jak se tvá hra na piáno zaène zlepšovat.
{18720}{18761}Mockrát vám dìkuji za…
{18761}{18825}Ne, senpai! Nemìò svùj obor!!!
{18839}{18916}Nebudeš moci hrát se mnou na klavír, kdy ho zmìníš!
{18928}{18975}Vdy na nìj hrajeme u mì doma kadı den!
{18975}{19046}Ale nebudeme u mít stejnı obor!
{19046}{19072}Proè se chováš tak divnì?
{19072}{19123}Dobrá, dobrá, Nodo!
{19195}{19261}Neuznám tvou zmìnu oboru na dirigování.
{19278}{19306}P-proè?
{19329}{19380}Protoe tì nemám rád.
{19380}{19403}Naštval jsi mì.
{19403}{19446}Takovı dùvod nehodlám pøijmout!
{19446}{19504}V dnešním svìtì to není neobvyklı dùvod.
{19504}{19561}Jste moná maestro, ale tady jen obyèejnej profesor!
{19561}{19587}Jaké na to máte právo?!
{19587}{19683}I kdybych na to nemìl právo, mám na to moc.
{19683}{19802}Kdy øeknu je to modrá, tak i èervená bude modrá.
{19818}{19944}Vy zatracenej dùchodce… Máte v sobì záš kvùli tomu, co se stalo vèera veèer?
{19980}{20030}Takové podøadné vìci jsou mi ukradené.
{20054}{20116}Øekl's, e jsi Vieirùv student, e?
{20149}{20230}Je to u patnáct let, co jsem poprvé potkal Vieiru.
{20250}{20285}Nikdy na to nezapomenu.
{20369}{20436}Tohle je u tøetí obchod. Ale koneènì jsem to našel!
{20436}{20470}Pro mì je to u pátı!
{20470}{20534}Chci to dát svoji vnuèce! Mojí vnuèce Chelsea!
{20534}{20611}Vdy jste se nikdy neoenil! Jdìte nìkam s nìjakou Chelsea!
{20611}{20676}Víte vy, kdo já jsem?!
{20676}{20726}Ano, a moc dobøe.
{20726}{20836}Slyšel jsem, jak jste sexuálnì obtìoval a mìl aférky s èlenkami rùznıch orchestrù.
{20836}{20917}No a? Do toho, co dìlám, vám nic není!
{20917}{21057}Ta ena, se kterou jste pøedevèírem na tom veèírku tak vášnivì flirtoval byla moje manelka.
{21057}{21095}Máte teï nìjakı problém?
{21147}{21252}Jak si takovı bastard mùe zaslouit tak nádhernou enu?!|/Dìkuji vám./
{21271}{21303}To vám neodpustím!
{21303}{21332}Poèkejte!
{21332}{21375}Vy ho nesnášíte kvùli dìtské hraèky?!
{21375}{21408}Ehm, ne, kvùli té eny!
{21408}{21510}Vy si myslíte, e mùete odmítnout, aby nìkdo byl vašim studentem kvùli své osobní zahoøklosti?!
{21510}{21601}Jistìe mùu. Jestli je uèitel mùj nepøítel, pak jeho student taky.
{21601}{21654}Vemte je, dokud jsou mladí.
{21654}{21718}Mìl bys svého uèitele teï nesnášet.
{21775}{21801}Ten had...
{21830}{21917}Senpai, radìji se dirigování vzdej.
{22080}{22109}Stihl jsem to vèas…
{22109}{22151}Hej, Tamaki.
{22151}{22230}Dneska jsem nemìl mít školu, ale na tohle jsem spìchal.
{22256}{22278}Já taky!
{22292}{22398}Jsem tak nadšená, e mì vybrali do Stresemannova speciálního orchestru!
{22398}{22423}Jojo!
{22423}{22495}Ale není trochu moc brzo?
{22495}{22554}A navíc jsme si nemìli brát nástroje, e?
{22554}{22584}Zajímalo by mì proè?
{22584}{22631}Ale jsem tak nadšená!
{22664}{22707}Vítejte všichni!
{22707}{22777}Wow, opravdovı Stresemann!
{22789}{22894}Moc si cením, e jste všichni pøišli na toto krátké oznámení.
{22894}{22928}Jeho japonština je dobrá.
{22944}{23051}Vybral jsem vás všechny pro svùj speciální orchestr.
{23051}{23113}Všichni jsme od teï jako rodina.
{23113}{23249}Ale nìjakı èas a úsilí trvá, ne se staneme opravdovou rodinou.
{23249}{23355}ádnı orchestr není dokonalı po prvním dnu.
{23355}{23395}To je dobrá poznámka!
{23395}{23431}JE TO OPRAVDOVİ MAESTRO!
{23449}{23555}Mìl jsem v úmyslu kadého z vás osobnì poznat co nejdøíve.
{23583}{23656}Ale dneska...
{23656}{23697}Jdeme se všichni promíchat!
{23724}{23867}Tato èást japonské kultury, kde lidé se jdou promíchat, aby se lépe poznali, je celkem známá.
{23867}{24031}Pojïme se spolu uvolnit a popovídat si o hudbì v promíchání.
{24031}{24061}Jde se!
{24106}{24131}Promíchání?
{24146}{24201}Jsem si jist, e tím myslí nìco jiného…
{24201}{24261}Jo, já taky…
{24306}{24377}Go, go, go, go, go!
{24403}{24425}Máte pøítele?
{24447}{24472}Ne!
{24472}{24526}Aha, nemáte?
{24569}{24615}On moc dobøe ví, co to je to promíchání.
{24615}{24682}Má drahá flétnistko, jak se jmenujete?
{24682}{24707}Suzuki.
{24718}{24769}A vy, moje milá houslistko?
{24769}{24814}Vaše køestní jméno?
{24814}{24839}Jsem Mika.
{24874}{24899}No, na jakı nástroj hraješ?
{24937}{25010}Hej, je to vánì Stresemann?
{25010}{25070}Jeho právé jméno je Milch Holstein.
{25070}{25141}Hm, myslel jsem, e si jdeme popovídat o hudbì.
{25141}{25214}Pøeskakujeme taková váná témata prozatím...
{25214}{25268}Zkouška nezaène døíve jako zítra odpoledne.
{25268}{25353}Dneska je to úplnì neformální setkání.
{25353}{25451}Hej ty taneèníku, zatanèi nìco.
{25451}{25481}Já? A taneèník?
{25493}{25542}Louskáèek?
{25542}{25582}Kolem a kolem!|/Masumi?/
{25613}{25723}Hej, Nodame, je pravda, e chtìl Chiaki zmìnit svùj obor?
{25723}{25832}Aaah, tohle? Milch tu ádost roztrhal.
{25832}{25875}To není moc dobrı.
{25875}{25999}Myslel jsem si, e Chiakiho promoce mùe bıt posunuta, kdy si zmìní obor.
{26024}{26122}On by nepromoval pøíští rok, kdyby si zmìnil obor na dirigování, e?
{26137}{26168}Moná bude promovat se mnou!
{26193}{26292}Zajímalo by mì, jestli by jel po studiu do Evropy nebo nìkam daleko…
{26305}{26354}Za tím svım "nevím-jak se-jmenuje" uèitelem?
{26371}{26392}To by byla nuda…
{26422}{26447}Evropa...
{26510}{26534}Milchi!
{26546}{26616}Musíte pøijmout Chiakiho ádost o zmìnì oboru!
{26692}{26746}/ádost: Prosím, nechte mì zmìnit obor na dirigování! Chiaki Shinichi/
{26746}{26811}Ou, lutı kapesníèek štìstí!
{26862}{26954}Pojï Nodame. Dej si pití na mém klínì.
{27079}{27110}Chiaki-senpai.
{27125}{27145}Uèíš se?
{27145}{27173}/Oznámení o odchodu/
{27173}{27224}Coe?!
{27224}{27253}Odchod?!
{27253}{27413}No, kdy nemohu zmìnit svùj obor tady, pùjdu na školu, kde mohu.
{27499}{27584}Pùjdeme za øeditelkou a u ní si budeš moct zmìnit obor!
{27584}{27605}Jdeme!
{27605}{27622}Hej!
{27622}{27653}/Øeditelka/
{27675}{27694}Paní øeditelko!
{27694}{27747}Copak, Nodame?
{27789}{27875}Øeditelka mi právì zašla koupit cigarety.
{27875}{27926}Pokud si pøeješ, mùu jí vyøídit vzkaz.
{27926}{27976}Vy vyuíváte paní øeditelku jako poslíèka?!
{28200}{28263}Ten starej páprda má zpodìní!
{28263}{28305}To myslí s tou zkouškou vánì?!
{28305}{28372}Neøíkej mi, e budeme muset jít na další promíchání!
{28372}{28443}Hej, myslíte, e je to podvodník?
{28472}{28494}Podvodník?
{28519}{28606}Je to zbyteèné, Nodame Kašli na to.
{28625}{28647}Milchi!
{28678}{28752}Prosím akceptuj jeho ádost o zmìnì oboru!
{28752}{28843}Ne. Nemùu ji pøijmout, ani kdy mì ádáš ty.
{28843}{28878}Proè?!
{28878}{28927}Jsem tvá kámoška, ne?
{28927}{28965}A taky maskotka, ne?
{28979}{29041}To ano. Tak to je.
{29052}{29138}Prosím, Milchi, vyslyš mou prosbu!
{29153}{29216}Kdy ne, Chiaki-senpai…
{29294}{29322}Nodame?
{29393}{29463}Dobrá, uznávám poráku.
{29484}{29503}Milchi!
{29503}{29614}Kdy mi dáš pusu, pøijmu Chiakiho ádost zmìnit obor!
{29614}{29665}Vùbec nic jste neuznal!
{29679}{29739}Ne. To je to samé jako má poráka.
{29739}{29829}V západní kultuøe není jedna pusa nic váného.
{29856}{29902}No, to je fakt...
{29902}{29958}Nebuï si tak jistı!
{29958}{29991}Je to docela váná vìc!
{30010}{30107}Zajímalo by mì, jestli by jel po studiu do Evropy nebo nìkam daleko…
{30189}{30236}Za tím svım "nevím-jak se-jmenuje" uèitelem?
{30236}{30276}Neboj, Nodame.
{30321}{30364}Pusa a on mùe zmìnit obor.
{30364}{30414}Nebude pusa, nezmìní si nic.
{30414}{30482}Zlatá cesta nebo støíbrná cesta?
{30511}{30534}Nodame?
{30534}{30590}Prosím rozhodni se.
{30740}{30801}www.mycolorfullife.blog.cz
