{1}{1}23.976
{43}{118}Snìzme to, ne to vychladne!
{118}{187}Oh, je tu i víno!
{228}{294}A èí dùm to asi je, co myslíš, ty parazite?!
{319}{372}A nechte moje víno bıt!!!
{372}{429}To musíš slyšet! To je bomba!
{441}{543}Profesor dirigování, kterı mìl pøijet…
{543}{621}je super slavnı Stresemann!
{639}{681}Stresemann?!
{681}{746}Chcete zaloit novı studentskı orchestr?
{746}{848}Ano. Mùj orchestr, sloenı ze studentù, které si vyberu.
{892}{950}Ten starej páprda se opozdil!
{950}{1000}To myslí s tou zkouškou vánì?!
{1000}{1068}Neøíkej mi, e budeme muset jít na další promíchání!
{1068}{1137}Hej, myslíte, e je to podvodník?
{1137}{1237}Prosím, Milchi, vyslyš mou prosbu!
{1237}{1313}Kdy ne, Chiaki.senpai…
{1384}{1421}Nodame?
{1483}{1557}Dobrá, uznávám poráku.
{1578}{1598}Milchi!
{1598}{1708}Kdy mi dáš pusu, pøijmu Chiakiho ádost zmìnit obor!
{1708}{1758}Vùbec nic jste neuznal!
{1774}{1830}Ne. To je to samé jako má poráka.
{1830}{1922}V západní kultuøe není jedna pusa nic váného.
{1946}{2000}No, to je fakt.
{2000}{2047}Nebuï si tak jistı!
{2047}{2086}Je to docela váná vìc!
{2101}{2199} Zajímalo by mì, jestli by jel po studiu do Evropy nebo nìkam daleko…
{2260}{2309}Za tím svım "nevím-jak se-jmenuje" uèitelem?
{2339}{2384}Pusa a on mùe zmìnit obor.
{2384}{2435}Nebude pusa, nezmìní si nic
{2435}{2502}Zlatá cesta, nebo støíbrná cesta?
{2527}{2543}Nodame?
{2543}{2597}Prosím rozhodni se.
{2785}{2808}Hej…
{2948}{2994}TaSHee's Gang uvádí...
{3112}{3188}NODAME CANTABILE
{5104}{5130}LEKCE 5
{5173}{5218}Coe? Podvodník?
{5337}{5393}Moná je to Stresemannùv bratr?
{5393}{5453}Moná se jmenuje Schtrezemann?
{5453}{5505}Moná...
{5505}{5579}Jste si opravdu jisti, e je to podvodník?
{5579}{5639}Ale ještì jsem ho vlastnì nevidìl chovat se vánì.
{5639}{5705}e jo?! Dokonce ten orchestr…
{5742}{5779}Pravda…
{5779}{5870}Vypadá to, e se dostavili jen slabí hráèi ...
{5888}{5923}/Kadı z nich si musí myslet, e jen on je ten nejlepší/
{5923}{5985}Kruci! Tohle je nanic!
{5985}{6067}Kde ten starej páprda vìzí?!
{6201}{6286}Hej… Co teï udìláme?
{6348}{6402}Kdy si mu jednu zèistajasna ubalila?|/To je moje holka! - pozn. èas./
{6402}{6519}Ale kdy Milch na mì tak najednou skoèil a…
{6532}{6565}Je mrtvı?
{6668}{6741}Jste tak všechny krásné…
{6754}{6832}Myslím, e nejspíš sní! O enách!
{6832}{6896}Tøeba mu bude lépe, kdy ho pohøbíme.
{6922}{6949}No jo...
{7027}{7098}Dneska má bıt první zkouška Orchestru S...
{7238}{7303}Chikai-senpai, nemohl bys dirigovat?
{7387}{7419}U to nemùu vydret!
{7449}{7486}Soráè, ale já mizím domù.
{7508}{7531}Hej!
{7581}{7604}Já jdu taky.
{7604}{7638}Tak to já té.
{7638}{7731}Ale ne, a já kvùli tomu zmeškala svoje soukromé lekce!
{7731}{7796}Tak tohle mì vánì naštvalo...
{7796}{7835}Hej.
{7835}{7878}Musí to bıt podvodník.
{7878}{7922}Je to a moc velkı podivín.
{7922}{7983}Moná e má jen stejné jméno.
{8013}{8071}Poèkejte chvíli!
{8149}{8192}Poøád máme zkoušku!
{8192}{8221}Jdeme na to!
{8221}{8255}Nodame…
{8255}{8343}Coe? Budeš nás snad dirigovat, maskotko?
{8381}{8457}Milch onemocnìl, take on bude…
{8457}{8493}Hej!
{8516}{8545}dirigovat!
{8545}{8571}Coe?!
{8701}{8739}Chiaki to vánì udìlá?
{8739}{8775}Proè Chiaki?
{8775}{8804}Není to pianista?
{8804}{8825}Ale je to úasné!
{8825}{8883}Mám dirigovat tenhle orchestr?|/Ah mùj  Boe, Chiaki!!!/
{8892}{8936}Chiaki, ty umíš dirigovat?
{8936}{8971}Jo, je to hraèka!
{8971}{9014}Nemluv za mì!
{9172}{9196}Kterou skladbu máme hrát?
{9196}{9226}Ehm…
{9263}{9321}Beethovenovu Symfonii è. 7.
{9383}{9400}È. 7?
{9422}{9531}Uèil jsem se ji den poté, co mì inspirovalo CD mistra Vieiry...
{9570}{9589}To zvládnu!
{9616}{9659}Chiaki-senpai!
{9687}{9746}Take, u to nìkdo z vás nìkdy hrál?
{9746}{9821}Rozhodli jsme se to zkusit, kdy jsme byli na promíchání...
{9821}{9875}Take jsme to zkoušeli doma.
{9875}{9917}Já taky!
{9917}{9966}Chiaki bude dirigovat…
{9966}{10014}Teï zaèíná ta pravá zábava.
{10035}{10160}Dobøe! Jdeme na to s Chiakim, zatímco tu ten staøík není!
{10160}{10204}No, asi jo teda.
{10204}{10259}Oh, Chiaki!!!
{10345}{10397}Není Chiaki-senpai skvìlı?
{10424}{10493}Plán zatím vychází…
{10704}{10737}Zaèneme s ladìním!
{10737}{10765}Hoboj!
{10839}{10906}Dobøe, první já...
{10961}{11003}To je úplnì blbá nota! Jseš o pùl tónu ní!
{11003}{11047}Vánì?
{11047}{11130}Mimoto, proè se chováš jako koncertní mistr?
{11130}{11163}Nestojíš na jiném místì?
{11163}{11233}No dovol?! Já jsem koncertní mistr!
{11285}{11305}Heh?
{11305}{11351}Maestro to sám tak rozhodl!
{11390}{11423}To snad ne…
{11423}{11466}To nemùu uvìøit.
{11466}{11499}Ze všech lidí proè Mine?
{11499}{11552}Mine je koncertní mistr?|/Proè Mine?/
{11552}{11629}Tohle nedopadne dobøe|/Co je?! Máte nìjakı problém?!/
{11660}{11741}Tak si to jednou zkusíme, zaèínáme na první máchnutí.
{11766}{11815}Heh, kde je dirigentská hùl?
{11815}{11925}Mohu ti pùjèit svou? Pouívám ji v mıch hodinách dirigování.
{11925}{12012}Ne! Prosím, pouij mou! Je mnohem kvalitnìjší!!
{12012}{12049}Moje je úplnì nová!
{12049}{12128}Oh, mì úplnì staèí jedna…
{12128}{12180}Prosím, vem si mou!
{12229}{12279}Kámen, nùky, papír! Kámen, nùky, papír! Kámen, nùky, papír!|/Co se to sakra…/
{12279}{12390}Kámen, nùky, papír! Kámen, nùky, papír! Kámen, nùky, papír!|/Chiaki je dìsnì populární mezi holkami, to je známé…/
{12390}{12480}Kámen, nùky, papír! Kámen, nùky, papír! Kámen, nùky, papír!|/Kadopádnì, umí vánì dirigovat?/
{12480}{12559}Kámen, nùky, papír! Kámen, nùky, papír! Kámen, nùky, papír!|/Je dobrı na klavír a dobøe vypadá, e?/
{12559}{12600}Kámen, nùky, papír! Kámen, nùky, papír! Kámen, nùky, papír!|/Já jsem ale hezèí!/
{12610}{12688}Já vyhrála! Tady, Chiaki!|/Bude jen chaoticky máchat hùlkou/
{12688}{12730}Já vyhrála! Tady, Chiaki!|/To bude sranda./
{12740}{12838}Musím Chiakimu ukázat, co umím! U nebudu tancovat!
{12859}{12925}Ukáu mu, jak skvìlı koncertní mistr jsem!
{13015}{13034}Tak jo.
{13056}{13117}Moná jsem jen náhrakou na téhle zkoušce, ale vím jak dirigovat orchestr.
{13134}{13169}Tohle je pro mì mimoøádná šance.
{13228}{13245}Zaènìme.
{13531}{13651}Vzbuïte se u, Milchi|Prosím, pojïte se podívat na Chiakiho dirigování!
{13667}{13761}Nikdy to asi neuvidím, ale vím, e bude úasnı.
{13761}{13833}Studoval hodnì kadı den.
{13833}{13902}Jsem si jistá, e by se vám to okamitì zalíbilo!
{13902}{13974}A pak ho budete chtít uèit dirigování!
{14180}{14267}Beethovenova Symfonie è. 7 v A-dur.
{14298}{14381}Všechny pohyby jsou sjednocené v jednom rytmu.
{14381}{14439}Je to velmi zvuèná symfonie.
{14615}{14654}Hej!
{15026}{15082}Co se to dìje s tímhle orchestrem?
{15147}{15182}To je strašné!
{15182}{15215}Špatnì!
{15215}{15357}I kdyby to byla jejich první zkouška, takovı nevkusnı |Beethoven by nemìl nikdy vzniknout!
{15420}{15472}Ten zatracenı starouš!
{15548}{15667}On snad sjednotil nejhorší hráèe a lamy z celé téhle školy!
{15703}{15776}Pøeklad: J-dawe|Korekce + èasování: WelW(etkaAa)-hime
{15918}{16077}Jak víte, Sedmá je fakt pìkná,|ale proè ji neudìláme trochu víc velkolepìji?
{16077}{16093}Au!
{16093}{16131}Jdi s velkolepostí nìkam!
{16131}{16169}Vdy na to nemáš!
{16208}{16255}Tvé hraní je plné chyb!
{16255}{16305}Koncertní mistr by nemìl kazit celı orchestr!
{16305}{16348}Vánì jsi doma cvièil?!
{16404}{16447}Chudák "koncertní mistr"!
{16470}{16503}Ty jsi kazila vıšky!
{16503}{16547}Urèitì studuješ tady na konzervatoøi?!
{16571}{16682}Druhá trubka! Nehraj to dlouhé fortissimo tak krátce! Zní to bídnì!
{16682}{16790}Druhı klarinet! Tvùj tón není èistı! Pøestaò tolik pištìt!
{16810}{16878}Viola! Hraješ moc nahlas!
{16952}{17004}Zahrajeme si to od zaèátku po pìtiminutové pauze.
{17128}{17184}Chikai-senpai má vıbornı sluch!
{17184}{17256}O kadém pøesnì vìdìl, co a jak hrál.
{17256}{17295}e, Milchi?
{17403}{17432}Milchi?
{17534}{17585}On je opravdu úasnı!
{17585}{17635}Je jako opravdovı dirigent!
{17635}{17703}Jak elegantnì mává s hùlkou.
{17703}{17754}Oh, je to tak rozkošné!
{17782}{17821}Pøestaò pištìt!
{17821}{17900}Jak se opovauješ tohle øíkat pøed Kaoru?
{17900}{17963}Jenom jsem mìl trochu problém s plátkem!
{17995}{18083}Jenom poukázal na oèividné chyby.
{18133}{18200}Je to jen suplující dirigent. Nic víc.
{18200}{18267}Jo! Jen se snaí bıt drsòák!
{18267}{18325}Hej, nechceš si z nìj trochu vystøelit?
{18506}{18558}Dobrá. Zaènìme!
{18558}{18654}Poukázání na individuální chyby nepomùe.
{18843}{18892}Je to moje šance dirigovat orchestr.
{18931}{19085}Dám do toho mistrovství, které Beethoven vloil do této skladby, jak nelépe dovedu.
{19975}{20057}Housle! Hraj ten šestnáctı takt jemnìji!
{20057}{20103}Druhá trubka! Jseš pozadu!
{20329}{20360}Viola, zníš zase moc hlasitì!
{20371}{20416}Cello, trochu vıš!
{20471}{20515}To je pøíšernı orchestr...
{20541}{20610}Ne! Kolikrát vám to mám ještì opakovat?!|/Chudák Chiaki…/
{20610}{20677}Tak, teï sleduj, Chiaki!
{20677}{20780}Prohodíme si klarinet a hoboj na místì, kde si toho ani ty nevšimneš!
{20780}{20813}A…
{20813}{20899}Jsem rád, e si Chiaki mé chyby vùbec nevšiml!
{20946}{20988}/Zbabìlı trik/|Ujistím se, e se ztrapní!
{21006}{21029}Teï!
{21721}{21757}Poznal to!
{21981}{22028}Zase ty, cello! Pøestaò se vyèleòovat!
{22028}{22078}Co to zase dìláš, druhá trubko?!
{22078}{22151}Viola! Kolikrát ti to mám øíkat - hraješ moc hlasitì!
{22244}{22399}Proè… To hraní zní falešnì a divnì…
{22483}{22552}Proè?! Proè, sakra?!
{22830}{22867}Senpai…
{22867}{22908}To je šílené...
{22936}{23020}Oni se to nenauèí. Ignorují všechny mé instrukce.
{23020}{23084}A dokonce na mì zkouší i nìjaké blbé triky!
{23084}{23167}Nemùu takovı dìsnı orchestr vystát!
{23258}{23298}Dobøe. To staèí!
{23298}{23342}Chiaki, nezvládl jsi to!
{23369}{23389}Milchi!
{23417}{23450}Chiaki…
{23490}{23542}Omlouvám se všem za to èekání!
{23542}{23616}Pøichází pravı vùdce!
{23711}{23761}Hej, nezvládl? Jakto?
{23761}{23827}Rozbreèel jsi dívku.
{23827}{23876}To je ten nejhorší høích, co mùe mu udìlat.
{23933}{23978}Neplaè, Shizuko.
{23995}{24035}To je holka?!
{24071}{24109}Ale… no a?
{24131}{24260}Pojïme zmìnit pøístup a zaènìme od zaèátku.
{24260}{24280}Hej…
{24301}{24332}Senpai…
{24332}{24483}Mine, teï se ještì netrap technikou smyèce a prstokladem.
{24515}{24611}Prostì mi dej víc hezkıch tónù. Tak jako obvykle.
{24611}{24655}O-OK.
{24655}{24770}Ty tam s tou trubkou. Jestli ti dnes není dobøe, tak netlaè pøíliš na pilu.
{24791}{24811}OK!
{24811}{24945}A ty na klarinet, ten špatnı zvuk je kvùli tomu plátku, e?
{24945}{24986}Mìl by si's ho nejspíš vymìnit.
{24986}{25008}OK!
{25040}{25148}Miho, která hraje na cello. Mùeš na mì zírat jak je libo.
{25188}{25255}Dej mi tøeba i sexy tón.
{25255}{25274}OK!
{25295}{25444}A pro tu plaèící houslistku,|dáme si na pøíštím promíchání další zábavnı závod, OK?
{25773}{25834}Ok, zkusíme si to zahrát naposledy!
{25834}{25889}Hrejte to tak, jak øekl Chiaki.
{26405}{26503}Špatnı plátek a zdraví...
{26535}{26564}Obojí sou jejich vina!
{26600}{26633}Mìli to vìdìt sami!
{26862}{26984}Ale… Jenom jeho dirigování…
{26984}{27023}Pøináší orchestru ivot.
{27138}{27251}Je to tak, jak øekl Chiaki?
{27284}{27297}Ne...
{27344}{27477}Musí nesmírnì obdivovat obojí - hudbu i lidi.
{27499}{27689}Miluje a zalévá kadého hráèe a notu,
{27709}{27774}a na oplátku oni vzkvétají
{27891}{27917}Je mnohém dál ne já...
{28021}{28074}Je to opravdovı mistr...
{28207}{28251}/ádost o zmìnu oboru/
{28333}{28387}Klidnì. Roztrhejte to, jak chcete.
{28408}{28509}Budu se pøihlašovat tak dlouho, dokud mì nepøijmete.
{28545}{28639}Mùeš bıt mùj student beze zmìny svého oboru.
{28670}{28841}Vypadáš, e tì to zaujalo. Napadlo mì, e by bylo |mrhání Vieirovım èasem nechat tì bıt jeho student.
{28872}{28919}Ale nemìò si svùj obor.
{28919}{28980}Bude pro tebe dobré pokraèovat v klavíru.
{28993}{29092}Ale zbytek svého èasu strávíš se mnou, jasné?
{29121}{29166}Maestro, znamená to snad…
{29302}{29385}Dobrá, teï kdy máme dohodu…
{29385}{29442}Pojïme do Shibuyi to oslavit!
{29442}{29463}Heh?
{29463}{29551}Pokud se mì budeš dret, holky na nás jen poletí.
{29660}{29777}Milchi, vy blbe!|Co pøesnì zamıšlíte s vyuèováním Chiakiho?!
{29817}{29845}Jdeme balit holky.
{29876}{29991}Nemùete vzít Chiakiho! Jsme spolu svázaní!
{30017}{30109}Tak Nodame pojï balit s náma, hm?
{30243}{30272}Pojï, jdeme domù.
{30332}{30589}Katastrofa na první zkoušce, kterou jsem vedl, |zmìnila smìr mého ivota o 180 stupòù,|ale nemìl jsem nejmenší tušení, e se to stalo právì vèas.
{30739}{30805}www.mycolorfullife.blog.cz
