{1}{1}23.976
{40}{67}TaSHee's Gang uvádí...
{196}{271}NODAME CANTABILE
{2211}{2293}Coe?! Vy budete pøíští mìsíc hrát na pøíspìvkovém koncertu?
{2293}{2365}Ano. Orchestr S tam bude debutovat.
{2365}{2475}Budeme hrát proti Orchestru A Beethovenovu Symfonii è. 3, "Eroicu"
{2499}{2586}Ale to u je za mìsíc! S tímhle orchestrem a tímhle koncertním mistrem.
{2586}{2621}Mùj debut koncertního mistra…|Ale to u je za mìsíc! S tímhle orchestrem…
{2621}{2637}Mùj debut koncertního mistra…|Myslíte to vánì?!
{2637}{2695}Orchestry mají smysl jen pøed publikem.
{2695}{2774}Byli jste mnou osobnì vybráni jako èlenové speciálního orchestru.
{2774}{2823}Buïte sebevìdomí a snate se pøipravit co nejusilovnìji!
{2823}{2867}Jo! Budeme!
{2867}{2895}Porazíme orchestr A!
{2895}{2924}Nastává období orchestru S!
{2924}{2951}Jsme géniové!
{2951}{3052}Teï nastane má éra!|Myslím, e jejich nejvìtším problémem je pøehnaná sebedùvìra.
{3052}{3099}No dobøe. Není to jako, kdybych je vedl já...
{3099}{3210}A taky, ode dneška, Chiaki bude asistující dirigent tohoto orchestru.
{3210}{3236}LEKCE 6
{3236}{3256}Coe?
{3256}{3309}Chiaki bude asistent dirigenta?
{3309}{3365}Tı jo, bude maestrovım osobním pomocníkem!
{3365}{3399}Ne, je to jeho ák.
{3399}{3433}Já jsem asistující dirigent?
{3450}{3589}Tak, Chiaki, tady. Instrukce jsou vepsané v notách.
{3603}{3705}Mám teïka rande, tak se prosím tì postarej o zbytek.
{3737}{3922}Mám velice dùleitou povinnost, take |musím jít, Chiaki to vezme za mì.
{3923}{4015}Obracejte se se všemi dotazy nebo ádostmi o radu na Chiakiho.
{4067}{4104}e, Chiaki?
{4154}{4195}Zatím!
{4195}{4246}Rande s Kameko!
{4246}{4289}Co to k sakru dìlá…
{4289}{4344}Dobrá Chiaki, zaènìme zkoušet.
{4344}{4377}Nemáme moc èasu do našeho prvního debutu.
{4497}{4530}Já e jsem asistující dirigent?
{4541}{4652}To je nìjaké podezøelé, ale koneènì mùu dirigovat orchestr èestnì.
{4652}{4702}Mìl bych bıt vdìènı a vydat ze sebe to nejlepší.
{4759}{4774}Jsem...
{4815}{4852}Promiòte, e jdu pozdì!
{4865}{4915}Zase ty, Sakuro?!
{4968}{5012}Je nástroj v poøádku?
{5012}{5064}Myslím, e ano.
{5064}{5097}Jdeš pozdì zase kvùli práci?
{5097}{5212}Ne, nemìla jsem peníze na lístek do metra,| tak jsem šla pìšky a z domu.
{5241}{5314}Na studentku základní školy máš moc starostí.
{5314}{5346}Jsem studentka støední školy, víš.
{5364}{5408}Student s finanèními problémy?
{5596}{5703}Maestrovy instrukce jsou drsné, ale vkusné.
{5703}{5759}Silné a odváné.
{5888}{5940}Tympány! Trochu hlasitìji!
{5951}{5969}Ano!
{6162}{6253}Tenhle orchestr nemá problémy s odvahou ale…
{6253}{6314}Cello a basa, hlídejte si vıšky!
{6461}{6487}Kontrabas, dávej bacha na vıšky!
{6528}{6593}Vıšky…kazím to já?
{6675}{6725}Chiaki se dívá pøímo na mì!
{6725}{6773}Já to kazím…
{6812}{6848}Všichni jsou tak dobøí!
{6848}{6921}Takhle dobøe nedokáu hrát!
{7104}{7195}Promiòte, mùete mi ukázat, jak se táhne smyècem?
{7195}{7322}Nevím, jestli si musela pracovat nebo co, ale jsi dost |pozadu, protoe nechodíš vèas na zkoušky.
{7347}{7411}A ještì nìco, mìla bys zapracovat na vıškách.
{7411}{7428}Je to docela špatné.
{7544}{7584}Chiaki-senpai!
{7616}{7632}Tady je...
{7632}{7727}Dobrá práce pro dnešek.|Na, pøinesla jsem ti ruèník a medové citrónky.
{7727}{7753}Mám tì ráda!
{7766}{7820}Ty zatracená holko! Tentokrát tì u vánì zabiju!
{7820}{7846}Ale celé citróny…
{7859}{7898}Ehm, Chiaki…
{7898}{7935}Chiaki…
{7957}{8016}Tahle èást mi dìlá problém.
{8016}{8111}Dobrá, podíváme se na to…hraj tenhle takt jednodušeji
{8111}{8165}Ehm, poradil bys mi trochu taky?
{8165}{8206}Já mám taky otázku!
{8276}{8336}Chiaki je vlastnì docela drsnej.
{8336}{8389}Jo, a…
{8389}{8448}vypadá hezèí ne pøedtím.
{8535}{8563}Jdu se zeptat také!
{8563}{8589}Já taky!
{8680}{8753}Proè nemùe bıt v tomhle orchestru místo pro klavír?
{8751}{8813}No, tohle crescendo…
{8813}{8907}Chiaki, øíkal jsi, e dnes veèer budeme spolu dusit maso.
{8907}{8971}Oh, u to chápu! Chápu...
{8986}{9028}Supermarket u za chvíli zavírá...
{9028}{9064}Hej, hej, Chiaki, ohlednì této èásti...
{9105}{9154}Pak tedy pùjdu domù bez tebe!
{9204}{9231}Heh? Studium v zahranièí?
{9244}{9352}Moji rodièe mi øekli, a si najdu práci, |ale já chci jít studovat do ciziny.
{9352}{9387}Co myslíš, Chiaki?
{9396}{9424}Mì je to jedno!
{9424}{9467}Neptej se mì na takové vìci!
{9467}{9483}Argh!
{9542}{9554}Ano?
{9554}{9619}Tady Tamaki od klarinetu.
{9619}{9715}Hej, co si myslíš o Suzuki Kaoru…
{9733}{9800}Kdo jim sakra dal moje èíslo?!
{9891}{9955}Neádej mì o ten skvìlı recept na kari!
{10062}{10121}Nejsem horká linka pro teenagery!
{10180}{10218}A teï Nodame?!
{10366}{10394}Zdá se mi to snad?
{10394}{10461}Musím bıt unavenı…
{10461}{10534}Nodame?|Senpai! Prosím tì, otevøi!
{10534}{10554}Tady je Nodame!
{10580}{10611}Fakt se mi to jen nezdálo?
{10654}{10710}Prosím, nakrm nás!
{10767}{10842}Je tohle snad souèást práce asistujícího dirigenta?
{10958}{11000}To je neskuteèné…
{11000}{11071}Hej! Proè je Saku Sakura s tebou?!
{11071}{11151}Našla jsem na ulici v bezvìdomí,| tak jsem ji vzala s sebou.
{11192}{11282}Je to u dlouho co jsem mìla tak extravagantní |tìstoviny s tolika ingrediencemi.
{11282}{11313}Extravagantní?
{11313}{11370}My u doma nemáme ani rıi.
{11370}{11478}Øekla mi, e se obchodu jejího otce |pøíliš nedaøí a její rodina tím trpí.
{11478}{11621}Máme hodnì dluhù. Dokonce i máma si vzala práci| na pùl úvazku, ale nepokryje to všechny platby.
{11621}{11732}Hraní hudby stojí peníze, a musím si pøispívat i na školné.
{11751}{11821}Vzala jsem práci øídit dopravu.
{11893}{11949}Take nemohu moc cvièit.
{11971}{12088}Všichni ostatní ze sekce bas jsou i v Orchestru A a všem to moc jde.
{12088}{12123}Já jsem daleko za nimi.
{12147}{12216}U nemùu zùstat v Orchestru S!
{12216}{12242}Sakuro!
{12242}{12322}Jediné, co potøebuješ, je více cvièit.
{12333}{12385}Ale já nemám vùbec èas kvùli té práci!
{12385}{12413}Skonèi s prací.
{12413}{12475}To ale nebudu schopna si platit školné!
{12475}{12537}Tak proè prostì nenecháš školy?
{12537}{12584}Jak to mùeš vyøešit takovou radou?!
{12599}{12713}Pokud nemá èas na cvièení kvùli školnému,| pak nemá smysl dál chodit na konzervatoø.
{12723}{12746}Ale má!
{12746}{12796}Tøeba zamilování se, setkávání s lidmi a jiné vìci mohou bıt pøínosné!
{12796}{12809}/Ignoruje ji/
{12809}{12875}Já bych cvièil, místo chození do školy.
{12875}{12970}Jestli se nechceš zlepšit, tak jsi teï docela dobrá.
{12982}{13008}Já se chci zlepšit!
{13040}{13060}Jo?
{13074}{13153}Ale moná bys to mìla vzdát.
{13153}{13251}Ne ti dojde, e bys mìla radši cvièit| místo chození sem a fòukání.
{13262}{13284}Chiaki-senpai!
{13340}{13383}Omlouvám se, e sem vás obtìovala!
{13383}{13403}Sakuro!
{13524}{13554}Není to proto, e jsem chudá.
{13568}{13646}Byla to… Byla to jen moje chyba!
{13648}{13713}Pøeklad: J-dawe|Korekce + èasování: WelW(etkaAa)-hime
{13722}{13744}Dobrá!
{13763}{13827}To vypadá dobøe. Zapracujeme na tom druhém| pohybu pøíštì, tak pøijïte pøipraveni.
{13892}{13936}Maestro zase dnes veèer nepøišel.
{13936}{13994}Zajímalo by mì, jakou mìl dùleitou povinnost .
{13994}{14018}Mìl rande!
{14031}{14078}Sakura dneska nepøišla.
{14078}{14112}Musela zase do práce?
{14112}{14217}Ale vdycky si bere volno, kdy máme zkoušku.
{14256}{14347}Aaah, Chiaki-senpai! Sakura dneska nepøišla!
{14347}{14384}Co tak najednou?!
{14384}{14400}Kde máš citrónky?
{14400}{14464}Sklapni! Ztrate se u!
{14499}{14520}Co to s ní je?!
{14520}{14611}Sesypala se, protoe jsi ji øekl, a nechá školu!
{14611}{14677}Sesypala? Jen z tohohle?
{14716}{14778}Chikai-senpai, ty hade! Jsi naprosto bezcitnı!
{14791}{14948}Chopin a Beethoven byli taky chudí, ne se stali slavnımi.|Nevíš nic o tom, jaké je to bıt chudı!
{15003}{15037}Já vím jaké je to bıt chudı!
{15059}{15121}Kupte zápalky! Prosím, kupte si zápalky!
{15193}{15222}Jsou tak høejivé…
{15350}{15376}Chudinka…
{15466}{15577}Proè musíme jít celou cestu a k ní kvùli chvilky tlachání?
{15577}{15626}Nemáme na vybranou.
{15626}{15716}Sakura nemá mobil a pevnou linku jim odpojili.
{15779}{15819}Co je? Proè se na mì takhle díváš?
{15856}{15965}Zlepšil ses… tím, e jdeš za Sakurou se ji omluvit.
{15965}{16074}Nejdu se omluvit. Jenom jí øeknu, e by nemìla vynechávat zkoušky.
{16114}{16218}Byla by to moje chyba, kdyby nìkdo odešel, zatímco je maestro pryè, take…
{16334}{16371}Pøestaò dìlat tenhle oblièej!
{16400}{16434}Boe, ne!
{16434}{16458}Jak nevychované.
{16495}{16551}Oh, senpai. To je její dùm.
{16622}{16667}Je ohromnı…
{16667}{16712}Jsi si jistá, e je to její dùm?
{16712}{16807}Proè… Sakura mi øekla, e byli chudí…
{16906}{16950}Opìtovné pøevzetí majetku?
{16950}{17055}Omluvte mì, ale obì dcery i ena zde nejsou, protoe pracují.
{17109}{17161}Já sám mám potom obchodní cestu do Itálie.
{17161}{17195}Itálie?
{17195}{17281}Pardon, mohu se zeptat… Jakou práci to dìláte?
{17295}{17500}Jsem prezident spoleènosti dováející nábytek.|Luxusní nábytek se neprodává dobøe kvùli mizerné ekonomice.
{17500}{17544}Cítím se trochu trapnì.
{17544}{17561}Aha…
{17579}{17656}Mimoto, máte vy dva rádi housle?
{17680}{17771}Chiaki-senpai na nì umí hrát opravdu dobøe!
{17771}{17823}Jestli je to tak,
{17851}{17902}pøišli byste se na tohle podívat?!
{18004}{18041}To je moje sbìratelská místnost.
{18060}{18085}Stradivarius?!
{18085}{18117}Tomaso Eberie?!
{18117}{18157}No to mì pos…!
{18157}{18211}Tolik nástrojù má hodnotu milionù jenù!
{18211}{18239}Nejsou nádherné?
{18239}{18390}Od doby, kde se ve ètrnáctém století takhle|koncipovaly, se dodnes prakticky nezmìnily.
{18390}{18432}Je to podivuhodnı nástroj.
{18755}{18790}No, já vlastnì neumím hrát na housle.
{18790}{18868}Vy idiote! Máte takovou ohromnou sbírku a neumíte hrát?!
{18868}{18893}A jste chudı?!
{18893}{18937}Bìte je všechny prodat!
{18937}{18995}Senpai, ty hoøíš.
{18995}{19080}Tohle je moje sbírka a je mnohem dùleitìjší, ne mùj ivot!
{19080}{19129}I mnohem dùleitìjší ne vaše vlastní dcera?!
{19129}{19212}Není její pøání zlepšovat se pøednìjší?!
{19223}{19255}Odpovìzte mi, kruci!
{19385}{19420}- O nìkolik dní pozdìji -
{19463}{19507}Vypadá to tak extravagantnì!
{19507}{19613}Moje mamka to posílá vám dvìma jako podìkování, Nodame a Chiaki.
{19631}{19788}Protoe táta prodal housle, naše ivoty se vrátily do starıch| kolejí. Dokonce i jeho obchod si zase vede dobøe!
{19788}{19809}Jeho obchod taky?!
{19809}{19963}Ano! Je to, jako by jedno z jeho houslí bylo prokleté. |Teï u mu to myslí normálnì.
{19981}{20014}Prokleté…
{20513}{20579}Sekce bas si vede moc dobøe.
{20627}{20699}Fajn. No, zas tak fajn ne.
{20719}{20772}Do koncertu zbıvají u jen dva tıdny.
{20772}{20845}U jsme dokonce zaèali s druhou èástí,| ale Stresemann se ještì neukázal.
{20872}{20902}Nemáme ádné další instrukce!
{21084}{21120}Co to kruci…?!
{21149}{21176}Stop! Stop!
{21199}{21246}Co k èertu vyvádíte?!
{21259}{21289}Není to bezva?
{21289}{21376}Myslel jsem, e bychom mohli pøinést trochu |rockového feelingu do tohohle orchestru.
{21376}{21395}Heh?
{21395}{21475}Øekl jsem o tom vèera kadému a trénovali jsme to. e?
{21489}{21550}Hraní stylem Jimiho Hendrixe… Není to cool?|/Co má tohle spoleèného se stylem Jimiho Hendrixe?/
{21550}{21629}V téhle dobì musí bıt i orchestry cool.
{21629}{21671}Hovadina!
{21671}{21736}Nejdøív hrajte poøádnì, ne se zaènete pøedvádìt!
{21736}{21786}Druhá èást je pohøební pochod!
{21786}{21811}Ale…
{21827}{21890}Co si myslel, opustit tenhle orchestr v téhle situaci?
{21903}{21949}Zatracenı starı páprda!
{21988}{22026}Oh, Milchi!
{22026}{22105}Zahrajme si striptızovou verzi kámen, nùky, papír.
{22105}{22149}Zaènu s kamenem…
{22149}{22183}Hej, vy parchante!
{22193}{22306}Tohle jste vánì dìlal noc co noc?!
{22306}{22337}Chiaki…
{22365}{22388}Vypadá roztomile!
{22388}{22419}Je hezkı!
{22419}{22448}A taky mladı!
{22448}{22483}Jsi Milchùv známı?
{22483}{22516}Ne, já…
{22555}{22623}Co to dìláš, ty donchuáne!
{22623}{22661}No-Nodame?!
{22674}{22705}Proè jsi…
{22705}{22744}Vylepšuji si svùj sex-appeal!
{22744}{22867}Milch mi to poradil, kdybych tì chtìla pobláznit.
{22867}{22901}Pobláznit mì?
{22901}{22981}Take to je ten, do kterého si zamilovaná, Nodame?
{22981}{23016}Vypadá na milého kluka!
{23016}{23042}Já nejsem její kluk!
{23071}{23094}Proè ne?!
{23094}{23128}On není?
{23128}{23164}Tak to si ho zamlouvám!.
{23164}{23197}Ne, já!
{23197}{23236}Je mùj!|Ne...
{23236}{23288}Prohlášení!
{23373}{23562}Prohlašuji, e odcházím z Orchestru S a od nynìjška| se soustøeïuji pouze na Orchestr A!
{23626}{23682}Proè?! Proè tak najednou?!
{23682}{23873}Orchestr S u má skvìlého, krásného - eh, myslím tím úasného| dirigenta, Chiakiho, kterı je stejnì dobrı, jako já.
{23873}{23934}Budete beze mì v pohodì.
{23934}{23953}Jake?!
{23953}{24004}Ale to vy jste zaloil Orchestr S!
{24036}{24138}Tak… Vy jste se naštval za ten vèerejšek?
{24138}{24268}To víš, e jo. Narušil jsi mùj harém.
{24268}{24301}To ti nikdy neodpustím!
{24301}{24332}Budeš èelit mé odplatì.
{24365}{24390}Odplatì?
{24400}{24493}Kadopádnì, nechám si Orchestr A a ty si nech Orchestr S.
{24493}{24558}Na tom koncert tì totálnì znemoním.
{24558}{24612}Radìji si dávej bacha.
{24749}{24788}Sakra…
{24788}{24884}Hej, všichni! Orchestr S nepadne tak snadno, jasnı?
{24884}{24926}To znamená, e se musíme rozpadnout...
{24926}{24947}Nedá se nic dìlat.
{24947}{25004}Poèkejte! My se nerozpadáme!
{25004}{25049}Myslím, e se musíme rozpadnout.
{25049}{25068}Chiaki?!
{25068}{25170}Jestli Stresemann nehodlá v tomhle pokraèovat, |není dùvod dirigovat tenhle orchestr.
{25187}{25278}Ale já chci zùstat v tomto orchestru s Chiakim!
{25306}{25483}Kdyby ses nestal asistujícím dirigentem, byla bych poøád |zaneprázdnìna prací a nemohla bych dost cvièit.
{25518}{25588}A nemìla bych blízko ke Kaovi…
{25617}{25650}Správnì.
{25650}{25700}Pojïme spoleènì udret Orchestr S.
{25700}{25773}Já chci taky zùstat v Orchestru S s Chiakim.
{25773}{25873}Stresemann stejnì nikdy nepøišel na zkoušku.
{25873}{25910}Myslím, e Chiaki to zvládne.
{25910}{26004}Nikdy neodpustím tomu, kdo by zradil Chiakiho!
{26025}{26056}Vidíš je všechny?
{26056}{26103}Hej, já neøekl…
{26103}{26179}Jooo! Spoleènì porazíme Orchestr A!
{26179}{26222}Rozdrtíme Stresemanna!
{26222}{26253}Jo!
{26253}{26281}Rozmašírujeme zrádce!
{26281}{26341}Tohle znamená válku!
{26341}{26387}Proè válku?
{26387}{26452}A já mám bıt vedoucí dirigent tohohle orchestru?!
{26503}{26571}Gratuluji ti k povıšení na vedoucího dirigenta!
{26571}{26606}Dáme si toast.
{26606}{26672}Dal by sis whisky a vodu? |/Zrovna se to nauèila a zkouší to…/
{26672}{26728}Proti Orchestru A, vedenım maestrem…
{26827}{26872}Máme šanci tak moná jedna k milionu.
{26922}{27045}Nejen to, ale dokáu udret Orchestr S pod kontrolou?
{27158}{27184}/Zaèíná bıt vzrušená/
{27184}{27237}Teï…Teï se nedívá!
{27382}{27416} Ne, mìl bych si uvìdomit, e je to moje šance!
{27449}{27558}Všude na svìtì jsou dirigenti, kteøí neumí dirigovat| orchestr bez ohledu na to, jak jsou dobøí.
{27576}{27647}I kdy jsou mizerní, je to Orchestr, kterı zformoval Stresemann.
{27658}{27696}Zmìním je!
{27696}{27718}Zvládnu to sám!
{27718}{27742}Je tu horko…
{27829}{27904}Beethovenova Symfonie è. 3, "Eroica".
{27929}{28066}S touhle symfonií zaèal Beethoven skládat historicky prùkopnická díla.
{28167}{28238}Sakra! Proè to musíte poøád dìlat?!
{28238}{28350}Proè?  Tohle je skladba, kterou Beethoven napsal na poèest Napoleona!|/Vyrobil trièka s logem Orchestru S/
{28350}{28431}Na poèest Napoleona, kterı bojoval za demokracii ve Francii!
{28443}{28532}Snaíme se vyjádøit toho samého hrdinského ducha, kterého mìl!
{28532}{28589}Vyjádøete to hudbou!
{28589}{28630}Nepøidávejte ádné svoje historky nebo vize!
{28630}{28691}Heh?! Hudba znìla dobøe, nemyslíš?!
{28691}{28779}Vùbec! Ty vysoké tóny znìly hystericky! Dìs!
{28779}{28809}A pøestaò s tím ujetım fidlováním!
{28809}{28870}Ale no tak, pojï se víc odvázat, Chiaki.
{28882}{28930}Rockovı orchestr! To bude mega!
{28930}{28964}Rockovı orchestr?!
{28964}{28993}To je skvìlé!
{28993}{29019}To je nìco nového!
{29124}{29186}Na tohle nemáme èas! Pøestaòte na mì mluvit!
{29196}{29240}Jsem to já, kdo vás všecky poslouchá!
{29240}{29297}Hrajte tak, jak vám øeknu!
{29307}{29379}Mine, jestli si se mnou ještì budeš zahrávat,| tak tì zbavím funkce koncertního mistra!
{29390}{29456}Cello! Dávej si pozor na zmìnu tóniny! A tvoje vibrato je otøesné!
{29466}{29521}Kontrabas! Hlídej si rytmus!
{29521}{29557}Vy e jste taky v Orchestru A?
{29557}{29640}Hoboj a klarinet! Hrajete jako byste zaøíkávali hada!
{29640}{29722}Pøedtím, ne zaènete fòukat, zaènìte hrát lépe!
{29722}{29742}Jste všichni na nic!
{29846}{29893}Je zpátky tam, kde zaèal.
{29893}{29947}Zrovna, kdy jsem myslel, e je milejší...
{29974}{30047}Je jak Napoleon poté, co stal císaøem.
{30047}{30088}Dost daleko od demokracie…
{30110}{30133}Chiaki…
{30168}{30332}Chiaki, Beethoven zmìnil názor na vìnování tohohle |díla Napoleonovi, poté co se stal císaøem…
{30504}{30585}Zbıvá u jen jeden tıden... Musím nìco udìlat…
{30773}{30833}www.mycolorfullife.blog.cz
